### ISSUE TITLE
OneDrive support

### ISSUE THREAD

**Issue by ismail** [ncw/rclone#10]
Would be nice to support Microsoft OneDrive. There seems to be some API documentation available at http://msdn.microsoft.com/en-us/library/windows/apps/hh826521.aspx

**Comment by bobobo1618** [comment]
They've introduced a [new API](https://onedrive.github.io/README.htm) which among other things, supplies a sha1sum.

**Comment by phudson** [comment]
"Me too". Now that it's easy /cheap to get a terabyte or more on OneDrive, this would be really useful

**Comment by ncw** [comment]
Now that rclone supported remotes which don't have md5sum or modtime properly this should be straightforward.

**Comment by ncw** [comment]
@ismail @bobobo1618 @phudson I've release the first version of this in rclone v1.24.  Give it a go and make issues if you find problems!

See the page in the docs about in, in particular the limitations: http://rclone.org/onedrive/

Thanks

Nick

**Comment by ismail** [comment]
Very nice! Just one bug:

2015/11/10 11:18:27 Documents/Quick Notes: Failed to open: itemNotFound: The specified item does not exist, or does not have content.
2015/11/10 11:18:27 Documents/Computing: Failed to open: itemNotFound: The specified item does not exist, or does not have content.
2015/11/10 11:18:27 Documents/Programming: Failed to open: itemNotFound: The specified item does not exist, or does not have content.

No need to give errors for these files because these are "OneNote" links which points to some undocumented link on onenote website. If you can detect those it would be nice to silently ignore them.

Thanks again!

**Comment by ncw** [comment]
@ismail  thanks for pointing that out.  Can you make a new issue please?

Thanks

Nick
