### ISSUE TITLE
improved logging and -v options

### ISSUE THREAD

**Issue by vesper8** [ncw/rclone#1000]
using the latest beta rclone v1.35-18-g35a6436β

there's two things I would like to see added

1) the ability to filter out certain messages when using -v
For example I am interested in any file operation where a file is copied or deleted
But I would like to no longer see the "sizes identical / skipping" which is really clogging up my log file

2) the ability to send error, info (warn) and debug to different log files when using --log-file

So maybe --log-file-info, --log-file-debug and --log-file-error ?

If that's not too much work, it would make my life a lot easier when trying to troubleshoot!

Thanks

**Comment by ncw** [comment]
I think this is related to #739

**Comment by ncw** [comment]
I'm currently re-working the logging.

Rather than allow sending different logs to different files, I'm going to put a tag on the front of each log message, NOTICE, INFO, DEBUG, ERROR which will make grepping the log files trivial.

**Comment by ncw** [comment]
I have reworked the logging - please have a go with it in this beta

http://beta.rclone.org/v1.35-87-g006227b/ (uploaded in 15-30 mins)

Here are the bits from the docs

## Logging ##

rclone has 4 levels of logging, `Error`, `Notice`, `Info` and `Debug`.

By default rclone logs to standard error.  This means you can redirect
standard error and still see the normal output of rclone commands (eg
`rclone ls`).

By default rclone will produce `Error` and `Notice` level messages.

If you use the `-q` flag, rclone will only produce `Error` messages.

If you use the `-v` flag, rclone will produce `Error`, `Notice` and
`Info` messages.

If you use the `-vv` flag, rclone will produce `Error`, `Notice`,
`Info` and `Debug` messages.

You can also control the log levels with the `--log-level` flag.

If you use the `--log-file=FILE` option, rclone will redirect `Error`,
`Info` and `Debug` messages along with standard error to FILE.

If you use the `--syslog` flag then rclone will log to syslog and the
`--syslog-facility` control which facility it uses.

Rclone prefixes all log messages with their level in capitals, eg INFO
which makes it easy to grep the log file for different kinds of
information.

**Comment by ncw** [comment]
I messed up with that beta - try this one instead http://beta.rclone.org/v1.35-92-g18c75a8/ (uploaded in 15-30 mins)
