### ISSUE TITLE
rmdir ineffective on ACD fuse mount

### ISSUE THREAD

**Issue by gordan-bobic** [ncw/rclone#1002]
rmdir command doesn't seem to do anything on the ACD fuse mount. The command succeeds and the directory temporarily disappears until the metadata cache expires, but the folder deletion doesn't propagate upstream to the ACD. This makes it very difficult to delete empty directories on encrypted volumes.

I am not sure if this is a duplicate of https://github.com/ncw/rclone/issues/100

**Comment by ncw** [comment]
I've just fixed this - try the latest beta

**Comment by gordan-bobic** [comment]
Confirmed fixed. Thank you.
