### ISSUE TITLE
Encrypted remote: add debug message showing the full encrypted pathname+filename for each file

### ISSUE THREAD

**Issue by DurvalMenezes** [ncw/rclone#1004]
As suggested here: https://github.com/ncw/rclone/issues/999#issuecomment-271154761

**Comment by ncw** [comment]
I'll probably do this with a flag `--crypt-show-mapping` which in combination with `-v` will show the mapping of crypted files to unencrypted files whenever they are listed.  So this could be used with `rclone ls` or `rclone sync` etc.

**Comment by ncw** [comment]
I've just implemented this - please find the beta here

http://beta.rclone.org/v1.35-46-g390f3cf/ (uploaded in 15-30 mins)

**Comment by benamira** [comment]
Great!

**Comment by DurvalMenezes** [comment]
Warning on a possible "documentation regression": the "--crypt-show-mapping" option isn't in the docs on the last rclone beta I downloaded:

```
grep -i show-mapping rclone-v1.35-99-g6fc114d??-linux-amd64/rclone.1
      -> Shows nothing.

rclone-v1.35-99-g6fc114d??-linux-amd64/rclone --help 2>&1 | grep -i show-mapping
      --crypt-show-mapping                For all files listed show how the names encrypt.
```

I saw on the commit above that  docs/content/crypt.md was updated with an entry documenting this, and I *think* that this file (along with the other .md files) are used to generate the manpage I checked above, so this is why I'm calling this a "documentation regression".

Cheers, 
   Durval.

**Comment by ncw** [comment]
@DurvalMenezes that will get sorted out when I make the release.  Unfortunately the betas come out with the old docs due to the way they are made.  I should probably work out how to fix that!  Thanks for reporting.

**Comment by DurvalMenezes** [comment]
Hello @ncw,

Just reporting back, I had the opportunity to use `--crypt-show-mapping` and it worked great; much better than try to divine the file/dir names by looking at the GDrive web interface. 

Cheers, 
   Durval.

**Comment by ncw** [comment]
@DurvalMenezes :-)

**Comment by DurvalMenezes** [comment]
Hi @ncw, 

> @DurvalMenezes :-)
LOL, I'm serious ;-) What I did before `--crypt-show-mapping` was to find an encrypted directory with the exact number of files and subdirectories as the one I was looking for, and then looking for a file in it with the exact size. That was a lot of work, but usually successful... 

Cheers, 
   Durval.
