### ISSUE TITLE
Feature Request: Expose Password Hash Obscure Function

### ISSUE THREAD

**Issue by tcf909** [ncw/rclone#1011]
Related to #1010 

I'm hoping to have the Obscuring function from the Config command exposed in a way that allows me to run a password against it and get the output that would go in the "password = xxxx" and "password2 = xxxxx" fields of the .rclone.conf.

This seems to be an absolute blocker for any type of scripted config / install where CLI input isn't available. Am I missing something? thanks!

Btw, side note: Been using rclone mount with crypt for a couple of days and it has worked amazingly...way better than some of the other solutions out there. Very glad to have the project available. Thanks so much!!!

**Comment by tcf909** [comment]
I submitted a very small PR to achieve desired result. See #1012

**Comment by ncw** [comment]
This has been merged in d4c923a5ccadb4f189ce2f501afbfc0ca0bf263e
