### ISSUE TITLE
Allow for root configuration within rclone 

### ISSUE THREAD

**Issue by EnorMOZ** [ncw/rclone#1014]
Allowing rclone to have a subdir configuration by setting the root path would make transferring to subdir paths easier.

An example:

```
[google]
type = drive
client_id =
client_secret =
token = {"access_token":"ASDFSAFAASD"}

[g_t]
type = drive
remote = google:DIR/SUBDIR WITHSPACE/
client_id =
client_secret =
token = {"access_token":"ASDFSAFAASD"}

[g_m]
type = drive
remote = google:DIR/SUBDIR/
client_id =
client_secret =
token = {"access_token":"ASDFSAFAASD"}
```

**Comment by ncw** [comment]
We have made the alias feature in #1049 which I think is probably sufficient for your needs.

You can find it in [the latest beta](https://beta.rclone.org).

I'm going to close this now.
