### ISSUE TITLE
Unexpected HTTP Status Code 460

### ISSUE THREAD

**Issue by TylerNakamura** [ncw/rclone#1015]
When filing an issue, please include the following information if possible as well as a description of the problem.  Make sure you test with the [latest beta of rclone](http://rclone.org/downloads/).

If you've just got a question then please use the [rclone forum](https://forum.rclone.org/) instead of filing an issue.

> What is your rclone version (eg output from `rclone -V`)

rclone v1.35

> Which OS you are using and how many bits (eg Windows 7, 64 bit)

Linux ubuntu 4.4.0-31-generic #50-Ubuntu SMP Wed Jul 13 00:07:12 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

> Which cloud storage system are you using? (eg Google Drive)

Moving from Dropbox to Google Drive (the error is the open on the Dropbox side I think)

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

rclone move tylerdropbox:/3P/ driveencrypted:/2016-11-13/3P/

> A log from the command with the `-v` flag (eg output from `rclone -v copy /tmp remote:tmp`)

2017/01/10 07:47:07 stuff.zip: Failed to copy: failed to open source object: unexpected HTTP status code 460
2017/01/10 07:47:07 stuff.zip: Not deleting source as copy failed: failed to open source object: unexpected HTTP status code 460
2017/01/10 07:47:07 Attempt 3/3 failed with 1 errors and: failed to open source object: unexpected HTTP status code 460
2017/01/10 07:47:07 Failed to move: failed to open source object: unexpected HTTP status code 460

**Comment by TylerNakamura** [comment]
It has successfully moved a lot of data with this command. However, it is literally just this one small zip (~170kB) that it cannot move for some reason.

**Comment by DurvalMenezes** [comment]
Humrmrmr... GDrive returning undocumented status codes... could this be GDrive-side data corruption? See #999. 

Also, you say you can't move the file, but can you read it without error? Can you "cat" it? Are its internal contents consistent?

**Comment by TylerNakamura** [comment]
Actually this one is coming from Dropbox, right? Seeing as I get the same error code from running
```
rclone copy mydropbox:/path/to/file.zip .
```
I downloaded the file directly from the Dropbox web interface and checked its contents, but I don't have the original checksum so I can't really tell. It unzips successfully (containing source code for an old project).

**Comment by DurvalMenezes** [comment]
> Actually this one is coming from Dropbox, right? Seeing as I get the same error code from running

You are correct. Thanks for setting me straight.

Glad to hear the ZIP unzips successfully; that means it is very probably uncorrupted; apart from the fact that corruption on compressed files tend to bring decompression errors (due to the fact that it messes up the internal state of the decompressor algorithm), ZIPs additionally have 32-bit CRCs for the entire file... any corruption not caught by the decompressor would then almost certainly be detected by the CRC.

**Comment by ncw** [comment]
A 460 error from dropbox means "Restricted Content".  That means that dropbox thinks the file has a virus, or contains copyright material or something like that.  [Search on Dropbox 460](https://www.google.co.uk/search?q=dropbox%20460&rct=j) and you'll see lots of stuff about it.

You can download it using the web interface though?

**Comment by TylerNakamura** [comment]
Wow. It's actually just a copy of the mirai source code (https://github.com/jgamblin/Mirai-Source-Code). I just wanted to save a zip for myself in case it got taken down from Github. I am just surprised to see that Dropbox is monitoring the stored content with such scrutiny at this point. I suppose this is why I am moving to encrypted remotes :P 

I am able to download it fine from the Dropbox web interface.

Thank you guys for the good work, I love the project and use it every day! I even created a few sample video tutorials for friends and family to get them interested:

https://www.youtube.com/playlist?list=PL31dut3vyk8MEXwmlHRNBmVfxylddPth1

<3
