### ISSUE TITLE
Make a third party tools page

### ISSUE THREAD

**Issue by ncw** [ncw/rclone#1019]
To link things which work with rclone

Eg
  * https://github.com/rhummelmose/rclonesyncservice

Any suggestions should have a desired link text and a link.

See also [forum thread](https://forum.rclone.org/t/suggestions-for-third-party-tools-which-use-rclone-or-enhance-rclone)

**Comment by ncw** [comment]
@hashbackup do you want to put hashbackup here?

**Comment by hashbackup** [comment]
Sure, thanks

**Comment by flixajki** [comment]
Need to check with dokany (fuse windows) I see something is being done with rclone https://github.com/dokan-dev/dokany/issues/406

**Comment by ncw** [comment]
@hashbackup - can you do me a link + link text for the page please?

**Comment by brandur** [comment]
https://github.com/brandur/rhttpserve

> A tiny HTTP server that can serve files out of any rclone remote. Includes a command line utility to generate time expiring Ed25519-based signed URLs (similar to a signed S3 URL) that will be verified by the server before it agrees to send a file.

This one is sort of "meware" in that it's largely created to be personally useful, but could potentially be interesting to someone else.

**Comment by ncw** [comment]
@brandur nice one :-)

**Comment by hashbackup** [comment]
http://www.hashbackup.com

HashBackup is an efficient multi-threaded command-line backup system for Linux, FreeBSD, and OSX.  Features: multiple versions of files, file retention, combining small files into larger arc files, splitting huge files, variable-block dedup, local encryption, mountable backups (fuse), backup verification, and support for many "dumb" storage systems such as S3, Google, ftp, rsync, ssh, etc.  Rclone is supported as a transport protocol for storage systems not natively supported by HashBackup.

Thanks Nick!

**Comment by mmozeiko** [comment]
I've made simple cross-platform GUI for rclone: https://mmozeiko.github.io/RcloneBrowser/
Works on Windows, macOS and GNU/Linux.

**Comment by ncw** [comment]
@mmozeiko 
> I've made simple cross-platform GUI for rclone: https://mmozeiko.github.io/RcloneBrowser/
Works on Windows, macOS and GNU/Linux.

That looks amazing! I'll certainly put that on the page.

It would be interesting to know if there are things you'd like rclone to do to make your life easier.

**Comment by mmozeiko** [comment]
I think almost everything is pretty good already now.

There are few minor things that could be better:
- show full file name for upload progress, currently rclone cuts characters from front if the total length is greater than 45 chars.
- somehow combining lsl and lsd commands in one. Currently I'm invoking both of them every time user goes into folder to get both files and folders.

**Comment by ncw** [comment]
I've put these in the wiki now: https://github.com/ncw/rclone/wiki/Third-Party-Integrations-with-rclone

And the wiki will link from the main website shortly.

Please update your entries as you wish!

BTW @mmozeiko I recently made the `lsjson` command for integration purposes - you should find it works much better than `ls` and `lsd`.

**Comment by mmozeiko** [comment]
Hmm, is json format best for this? Currently I'm reading ls and lsd output line-by-line. As soon as rclone produces new line, I'm reading, parsing and processing it. For json most likely I'll need to parse whole output before starting to process (which means UI will block, or I'll need to move reading to separate thread). Or I'll need to write some hacky incremental parser... which I would prefer not to do.

**Comment by ncw** [comment]
@mmozeiko I designed the output format so you can either read it in one gulp, or read it line by line. Eg

```
$ tree /tmp/ls
/tmp/ls
├── directory
│   └── file3.txt
├── file1.txt
└── file2.txt

1 directory, 3 files
```

```
$ rclone lsjson /tmp/ls
[
{"Path":"directory","Name":"directory","Size":-1,"ModTime":"2017-07-10T11:04:28.271497613+01:00","IsDir":true},
{"Path":"file1.txt","Name":"file1.txt","Size":9,"ModTime":"2017-07-10T11:04:01.43147201+01:00","IsDir":false},
{"Path":"file2.txt","Name":"file2.txt","Size":9,"ModTime":"2017-07-10T11:04:03.991474451+01:00","IsDir":false}
]
```

```
$ rclone lsjson -R /tmp/ls
[
{"Path":"directory","Name":"directory","Size":-1,"ModTime":"2017-07-10T11:04:28.271497613+01:00","IsDir":true},
{"Path":"file1.txt","Name":"file1.txt","Size":9,"ModTime":"2017-07-10T11:04:01.43147201+01:00","IsDir":false},
{"Path":"file2.txt","Name":"file2.txt","Size":9,"ModTime":"2017-07-10T11:04:03.991474451+01:00","IsDir":false},
{"Path":"directory/file3.txt","Name":"file3.txt","Size":9,"ModTime":"2017-07-10T11:04:28.271497613+01:00","IsDir":false}
]
```

So if you want to parse it line by line, ignore lines with only `[` and `]` and strip any trailng commas of lines to get a valid JSON object.

**Comment by mmozeiko** [comment]
Oh, this is nice. I'll definitely check it out. Thanks!

**Comment by caspertone2003** [comment]
@ncw 

> I've put these in the wiki now: https://github.com/ncw/rclone/wiki/Third-Party-Integrations-with-rclone
> 

Perhaps you could update the page to point to a new incarnation of the repo, just put up to date...

see

https://github.com/kapitainsky/RcloneBrowser/releases

**Comment by ncw** [comment]
> @ncw
> 
> > I've put these in the wiki now: https://github.com/ncw/rclone/wiki/Third-Party-Integrations-with-rclone
> 
> Perhaps you could update the page to point to a new incarnation of the repo, just put up to date...
> 
> see
> 
> https://github.com/kapitainsky/RcloneBrowser/releases

Well you can do that - it is a wiki :-)

**Comment by caspertone2003** [comment]
Done
