### ISSUE TITLE
when checksums aren't available and -c is used, imply --ignore-times, not --size-only

### ISSUE THREAD

**Issue by hashbackup** [ncw/rclone#1020]
HashBackup can use rclone to sync individual files.  To ensure an accurate sync, HB uses the rclone -c option.  However, some remotes (Dropbox) don't support -c.  HB doesn't know whether a remote supports checksums or not, and can't easily determine this.

Now, rclone falls back to --size-only if a remote does not support checksums.  But if -c is used, it implies that there may be cases where the size (and time) are the same and the user wants a more strict test.  To me, rclone should fall back to --ignore-times, to ensure an unconditional transfer if -c is used and checksums aren't available.

Here is an example of a failed sync with dropbox, even though -c was used:
```
$ echo abc>abc
$ rclone -c -v copyto abc drop:test/abc
2017/01/11 10:48:22 rclone: Version "v1.35" starting with parameters ["rclone" "-c" "-v" "copyto" "abc" "drop:test/abc"]
2017/01/11 10:48:29 Dropbox root 'test': Modify window not supported
2017/01/11 10:48:29 abc: Size of src and dst objects identical
2017/01/11 10:48:29 abc: Unchanged skipping
2017/01/11 10:48:29
Transferred:      0 Bytes (0 Bytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:        6.9s
2017/01/11 10:48:29 Go routines at exit 5
$ echo def>abc
$ rclone -c -v copyto abc drop:test/abc
2017/01/11 10:48:53 rclone: Version "v1.35" starting with parameters ["rclone" "-c" "-v" "copyto" "abc" "drop:test/abc"]
2017/01/11 10:48:59 Dropbox root 'test': Modify window not supported
2017/01/11 10:49:00 abc: Size of src and dst objects identical
2017/01/11 10:49:00 abc: Unchanged skipping
2017/01/11 10:49:00
Transferred:      0 Bytes (0 Bytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:          7s
2017/01/11 10:49:00 Go routines at exit 5
```
For HashBackup, I'm switching to -I to ensure an accurate sync, but thought I'd suggest this change for future releases.  Thanks!

**Comment by ncw** [comment]
I don't really want to change the meaning of the `--checksum` flag like that.  In the docs it says

> Normally rclone will look at modification time and size of files to see if they are equal. If you set this flag then rclone will check the file hash and size to determine if files are equal.

I think checking the modification time as a last resort would be surprising for the user.

>  HB doesn't know whether a remote supports checksums or not, and can't easily determine this.

Perhaps this is the thing we should be working on?

rclone should be able to generate the tables in: http://rclone.org/overview/ in some programmatic format quite easily, or maybe just the values for a given remote.

What would work for you here?

**Comment by hashbackup** [comment]
To me, the reason for using -c is that you know you are transferring
files that may have identical size and times, but different contents.
Let's say you have a backup program that creates 10MB file chunks
named 0, 1, 2, 3, etc.  You sync those.  Now you realize you backed up
the wrong stuff and start over, creating new 0, 1, 2 files.  You sync
those with -c.  On dropbox, rclone says "nothing transferred".  To me,
that's a bug.

You mentioned checking modification time, but that was not my
suggestion.  My suggestion was, if -c is used and you can't verify the
checksum, then transfer the file unconditionally.  It's the only way
to be sure you are in sync.

For HashBackup, I'm going to switch to unconditional transfers (adding
--ignore-times).   I don't want to take the risk of something not
being transferred because rclone didn't think it was necessary, even
though it doesn't know that for sure.  99% of the time, HashBackup
will only send new files anyway, and I'd rather have it send a file
redundantly 1% of the time than have a broken backup.

It's solved for me, so if you want to close this, okay.  Thanks!

On 1/12/17, Nick Craig-Wood <notifications@github.com> wrote:
> I don't really want to change the meaning of the `--checksum` flag like
> that.  In the docs it says
>
>> Normally rclone will look at modification time and size of files to see if
>> they are equal. If you set this flag then rclone will check the file hash
>> and size to determine if files are equal.
>
> I think checking the modification time as a last resort would be surprising
> for the user.
>
>>  HB doesn't know whether a remote supports checksums or not, and can't
>> easily determine this.
>
> Perhaps this is the thing we should be working on?
>
> rclone should be able to generate the tables in: http://rclone.org/overview/
> in some programmatic format quite easily, or maybe just the values for a
> given remote.
>
> What would work for you here?
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/ncw/rclone/issues/1020#issuecomment-272201040


-- 
HashBackup: easy onsite and offsite Unix backup
http://www.hashbackup.com
