### ISSUE TITLE
1.35: copyto gives misleading error if source file doesn't exist (Dropbox)

### ISSUE THREAD

**Issue by hashbackup** [ncw/rclone#1022]
Example:
```
$ echo abc>abc
$ rclone copyto abc drop:test/abc
2017/01/11 15:36:31 
Transferred:      4 Bytes (1 Bytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:        2.5s
$ rm abc
$ rclone copyto abc drop:test/abc
2017/01/11 15:36:42 Failed to create file system for "drop:test/abc": is a file not a directory
```

**Comment by ncw** [comment]
I see!

**Comment by ncw** [comment]
I'm going to fix this as part of the changes I'm making to simplify the remotes in 1.37

**Comment by ncw** [comment]
This is now fixed in [the latest beta](https://beta.rclone.org)

**Comment by hashbackup** [comment]
I tried this with 1.38-232:
```
[jim@mb ~]$ rclone -V
rclone v1.38-232-g2fd0bec4β
- os/arch: darwin/amd64
- go version: go1.9.2
[jim@mb ~]$ rclone ls drop:
   905827 Get Started with Dropbox.pdf
[jim@mb ~]$ echo abc>abc
[jim@mb ~]$ rclone copyto abc drop:test/abc
[jim@mb ~]$ rclone ls drop:
   905827 Get Started with Dropbox.pdf
        4 test/abc
[jim@mb ~]$ rclone copyto abc drop:test/abc
[jim@mb ~]$ rm abc
[jim@mb ~]$ rclone copyto abc drop:test/abc
2017/12/14 08:23:17 Failed to create file system for "drop:test/abc": is a file not a directory
```
Shouldn't the error have been something like "local file abc: No such file or directory"?

**Comment by ncw** [comment]
Sorry got over excited and closed the issue to soon...

**Comment by ncw** [comment]
OK I really have fixed this this time!

The error message is now `Source doesn't exist or is a directory and destination is a file` which is the best I can do without reading the directory which will introduce more operations which is undesireable.

https://beta.rclone.org/v1.38-235-g2a01fa9f/ (uploaded in 15-30 mins)

**Comment by hashbackup** [comment]
Yeah, that sounds good - thanks!
