### ISSUE TITLE
rclone mount crypt on acd cp error

### ISSUE THREAD

**Issue by tcf909** [ncw/rclone#1024]
Hello,

When I try to use cp against a Crypt -> ACD mount the system hangs most the time. I have this in the system logs:

Jan  9 13:58:16 localhost kernel: INFO: task cp:27494 blocked for more than 120 seconds.
Jan  9 13:58:16 localhost kernel:      Tainted: G        W    3.14.47 #1
Jan  9 13:58:16 localhost kernel: "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
Jan  9 13:58:16 localhost kernel: cp              D ffff88087fc73240     0 27494   7760 0x00000084
Jan  9 13:58:16 localhost kernel: ffff8801045e3c28 0000000000000082 ffff880823c243d0 0000000000013240
Jan  9 13:58:16 localhost kernel: ffff8801045e3fd8 0000000000013240 ffff880823c243d0 ffff880104d137e8
Jan  9 13:58:16 localhost kernel: ffff8808516fb000 ffff8801045e3c58 ffff880104d138c8 ffff880104d137e8
Jan  9 13:58:16 localhost kernel: Call Trace:
Jan  9 13:58:16 localhost kernel: [<ffffffff819bde99>] schedule+0x29/0x70
Jan  9 13:58:16 localhost kernel: [<ffffffffa0550465>] __fuse_request_send+0x125/0x290 [fuse]
Jan  9 13:58:16 localhost kernel: [<ffffffff810b8160>] ? abort_exclusive_wait+0xb0/0xb0
Jan  9 13:58:16 localhost kernel: [<ffffffffa05505e2>] fuse_request_send+0x12/0x20 [fuse]
Jan  9 13:58:16 localhost kernel: [<ffffffffa05599f6>] fuse_send_write+0xd6/0x110 [fuse]
Jan  9 13:58:16 localhost kernel: [<ffffffffa055b4cd>] fuse_perform_write+0x28d/0x520 [fuse]
Jan  9 13:58:16 localhost kernel: [<ffffffffa055ba01>] fuse_file_aio_write+0x2a1/0x340 [fuse]
Jan  9 13:58:16 localhost kernel: [<ffffffff811c8897>] do_sync_write+0x67/0xa0
Jan  9 13:58:16 localhost kernel: [<ffffffff811c908a>] vfs_write+0xba/0x1e0
Jan  9 13:58:16 localhost kernel: [<ffffffff811c8f64>] ? vfs_read+0xf4/0x160
Jan  9 13:58:16 localhost kernel: [<ffffffff811c9ae5>] SyS_write+0x55/0xd0
Jan  9 13:58:16 localhost kernel: [<ffffffff819caf49>] system_call_fastpath+0x16/0x1b

And the rclone log shows a 429 error (no retries) and passes that back to the stack.

I know writes on mounts are fairly new for ACD. Is writing to a crypt volume that is using an ACD volume supported?

rclone mount --max-read-ahead 200M --transfers 20 --checkers 20 --log-file /root/ACD.log -v ACD_CRYPT: ACD_CRYPT

OS: Linux
Version: rclone v1.35-DEV
Command: cp file.bin

**Comment by ncw** [comment]
I haven't been able to reproduce this.

How big is the file you are copying?  How often does the cp go wrong?

Can you share the rclone log (redact it if necessary) showing the 429 error and what happened before and after?

What should have happened is that rclone should have returned an error on the 429 error and cp should have failed.

**Comment by tcf909** [comment]
I'll work on reproducing. It was an immediate response (didn't ever start copying files as far as I could see).
