### ISSUE TITLE
Enhancement: Always check if the target file is already already there just before uploading it

### ISSUE THREAD

**Issue by gordan-bobic** [ncw/rclone#1025]
It would appear that rclone checks what files are in local and remote locations only at the beginning of the sync. It doesn't seem to check again just before uploading the file. It would be really useful if it would also check just before sending the file, just in case something else uploaded the file into place.

The obvious use case where this would be useful is if the file exists on multiple machines, and they are both trying to back up the files to the remote location simultaneously. The two machines may have different files locally, but we want to merge them all into the same remote location. What seems to be happening now is that if one machine uploads a file, the other machine will end up uploading it, too, if it began the sync before the particular file was there, but the file was uploaded by a different process before the machine got around to uploading it itself. Note that we are talking about the same file, with he same size and mtime on both machines.

**Comment by ncw** [comment]
> It would appear that rclone checks what files are in local and remote locations only at the beginning of the sync. It doesn't seem to check again just before uploading the file.

That is correct.

I don't usually recommend using rclone from two places simultaneously.

However, doing a metadata refresh and check just before uploading a file would be relatively cheap compared to uploading a file.  It could be an option maybe?

**Comment by gordan-bobic** [comment]
I am aware that multi sourced sync is an edge case with an inherent unavoidable race condition.
As an option or otherwise, it would be a very appreciated feature.

**Comment by ncw** [comment]
rclone has got much better at this now it does a directory by directory sync, so I'm going to close this as it is much less of a problem.
