### ISSUE TITLE
mount: Prefetch and cache all file metadata periodically instead of fetching on-demand

### ISSUE THREAD

**Issue by gordan-bobic** [ncw/rclone#1027]
The sync command retrieves the full payload of remote file names and mtimes, and this takes seconds. However, doing ls -laR or another command that fetches all of the data file-by-file using stat() takes several minutes, presumably beause each stat() call ends up fetching metadata entries one file at a time.

While this behaviour may be advantageous in some cases (many files where only very few need to have metadata retrieved), for many cases it would be much cheaper to fetch all the metadata at cache expiring interval in one shot, and cache it. This would massively speed up things like find invocations, and the metadata cache expiry time would still provide similar freshness guarantees to what is available anyway.

This would obviously need to be togglable because it could burn a lot of CPU and I/O in cases where there are huge directory trees and the cache expiry time is set short. As a default, perhaps it should be enabled below some threshold, say, 2000 files per minute of metadata caching time, with the initial fuse mount operation doing it once anyway to establish whether the counts are above or below the threshold.

**Comment by ncw** [comment]
Nice idea.  Something like it has been in my mind but it has never made it to an issue.

Your analysis is spot on.  Prefilling the cache using the sync listing routines should be relatively easy.

Some thought needs to be given to when to do it.

Initially to keep it simple, it might be best to do it initially, and on the same frequency as the `--dir-cache-time` maybe.

**Comment by gordan-bobic** [comment]
I just measured it with 5000 files or so, and it takes about 3 minutes to do ls -laR the first time, and only 1s on the immediate subsequent attempt.

I think it would be approximately optimal to do a refresh at an interval of --dir-cache-time minus 1 minute. That would keep the refresh is seamless without a slow period, and unless somebody is on dial-up, one minute should be able to fetch down a LOT of metadata. If the caching time is set to less than a minute, disable metadata prefetching completely (i.e. current behaviour).

**Comment by flixajki** [comment]
It would be great if we could store the cache directly on the cloud mount and update just the changes once rclone copy/move was done.  In that case you would only need to rescan anything if you use any other tools to upload new stuff in cloud.  

The main reason for that is gdrive as regardless whats cache expiry time is once you do full lib update you will be locked for 24h.

**Comment by gordan-bobic** [comment]
@flixajki , I think this is quite different and for a different  porpose from the original proposal. Probably best handled in a separate ticket with a detailed description of what exact problem it is intended to solve and on which back-end.

**Comment by gordan-bobic** [comment]
This appears to be mostly a duplicate with https://github.com/ncw/rclone/issues/1027 which is scheduled for 1.37. Any chance this issue could be piggy-backed onto it?

**Comment by ncw** [comment]
This issue will get fixed as part of #897 I think...

**Comment by ncw** [comment]
I think the new cache backend serves this purpose, so I'm going to close this issue
