### ISSUE TITLE
Throwing error when an excluded directory is inaccessible

### ISSUE THREAD

**Issue by Plup-io** [ncw/rclone#1028]
Hi guys, 

My problem seems the same than #624. But the solution doesn't work for a strange reason. 

I have a folder with docker volumes that I excluded according to @ncw answer in the #624. But it doesn't solve the problem : 
~~~
$ rclone --exclude "/vm/**" --exclude "/job/**/src/" ls /home/plup/ > /dev/null
2017/01/12 14:57:03 failed to open directory "/home/plup/vm/docker/volumes": open /home/plup/vm/docker/volumes: permission denied
~~~

The strangest part to me : if I go down in the "vm" folder, the exclusion works:
~~~
$ rclone --exclude "/docker/**" ls /home/plup/vm/ > /dev/null
2017/01/12 15:06:40 
Transferred:      0 Bytes (0 Bytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:          0s
~~~
I'm to confused to debug it by myself !

Info : 
~~~
$ rclone -V
rclone v1.34-DEV
$ uname -a
Linux Thor 4.6.0-1-amd64 #1 SMP Debian 4.6.4-1 (2016-07-18) x86_64 GNU/Linux
~~~

**Comment by Plup-io** [comment]
It actually might be linked  of the order of the exclusion flags. This gives me the same error but in another excluded folder : 
~~~
$ rclone --exclude "/job/**/src/" --exclude "/vm/**" ls /home/plup/ > /dev/null
2017/01/12 15:18:56 failed to open directory "/home/plup/job/zazzo/src/cache/smarty/compile/b4": open /home/plup/job/zazzo/src/cache/smarty/compile/b4: permission denied
~~~
So it might just be an overlap. I should probably read the doc again about filtering (I swear I did it already !).

**Comment by ncw** [comment]
Exactly which version are you using? Multiple --exclude flags is a relatively recent feature. 

Have you tried with the latest beta? 

Post the output of --dump-filters also.

**Comment by Plup-io** [comment]
I'm using the version from the debian testing repository. So it's probalby the ultimate one. 

I'll try to install the last one and give some update. Anyway, I use sync with --filter-from and it's working. So if you think it's a bug related to an outdated version, you can close the ticket without deeper investigation. Don't waste your time. 

Thanks for your answer.

**Comment by ncw** [comment]
I think if you upgrade to 1.35 (which seems to be in debian unstable - not sure about testing) then this should be fixed.

I had no idea rclone had been packaged for debian - thanks for letting me know!

I'll close this - please reopen if necessary.

Thanks

Nick
