### ISSUE TITLE
'rclone sync --drive-use-trash' fails to delete files if owned by another user.

### ISSUE THREAD

**Issue by lickdragon** [ncw/rclone#1029]
rclone v1.35
Debian 8.6 - 64 bit
Google Drive

Hi,
  First, thanks for a great utility!
  'rclone sync --drive-use-trash does not delete files if file is owned by a different account but the account can edit (including delete) from web interface

To reproduce:
# create a directory permtest on google drive owned by gdrive_backups_o
# share with gdrive_backups2_o as an editor
# As gdrive_backups2_o, go to "Shared with me" in google drive
# find permtest and "add to My Drive"

mkdir /tmp/permtest
touch /tmp/permtest/owner_gdrive-backups_o
touch /tmp/permtest/owner_gdrive-backups2_o

# copy two files using two accounts
/usr/local/bin/gdrive/rclone copyto -v --config /scratch/rclone.creds /tmp/permtest/owner_gdrive-backups_o gdrive-backups_o:permtest/owner_gdrive-backups_o
/usr/local/bin/gdrive/rclone copyto -v --config /scratch/rclone.creds /tmp/permtest/owner_gdrive-backups2_o gdrive-backups2_o:permtest/owner_gdrive-backups2_o

# remove the files
rm /tmp/permtest/owner_gdrive-backups_o
rm /tmp/permtest/owner_gdrive-backups2_o

# sync the directory with one of the accounts - file which is owned gets removed (owner_gdrive-backups2_o), file which is edittable is not removed (owner_gdrive-backups_o)
/usr/local/bin/gdrive/rclone sync --drive-use-trash -v --config /scratch/rclone.creds /tmp/permtest/ gdrive-backups2_o:permtest/

Not using '--drive-use-trash' does not change the outcome.

thanks again!
C.

**Comment by ncw** [comment]
This issue came up before in #34 - and there we decided that `--drive-use-trash` was a reasonable workaround - that doesn't seem to be working for you though?

What error message does it give?

**Comment by lickdragon** [comment]
Oh dang, I had planned on giving the output.  Thanks for reminding me.

Here is one run of the commands above:

root@drbl:/ceph/drbl# mkdir /tmp/permtest
mkdir: cannot create directory ‘/tmp/permtest’: File exists
root@drbl:/ceph/drbl# touch /tmp/permtest/owner_gdrive-backups_o
root@drbl:/ceph/drbl# touch /tmp/permtest/owner_gdrive-backups2_o
root@drbl:/ceph/drbl#
root@drbl:/ceph/drbl# # copy two files using two accounts
root@drbl:/ceph/drbl# /usr/local/bin/gdrive/rclone copyto -v --config 
/scratch/rclone.creds /tmp/permtest/owner_gdrive-backups_o gdrive-backup
s_o:permtest/owner_gdrive-backups_o
2017/01/13 10:09:31 rclone: Version "v1.35" starting with parameters 
["/usr/local/bin/gdrive/rclone" "copyto" "-v" "--config" "/scratch/rclone
.creds" "/tmp/permtest/owner_gdrive-backups_o" 
"gdrive-backups_o:permtest/owner_gdrive-backups_o"]
2017/01/13 10:09:31 gdrive-backups_o: Saved new token in config file
2017/01/13 10:09:32 Google drive root 'permtest': Modify window is 1ms
2017/01/13 10:09:32 owner_gdrive-backups_o: Modification times differ by 
-21h54m46.735369495s: 2017-01-13 10:09:31.471369495 -0600 CST, 2017-0
1-12 18:14:44.736 +0000 UTC
2017/01/13 10:09:33 owner_gdrive-backups_o: Updated modification time in 
destination
2017/01/13 10:09:33 owner_gdrive-backups_o: Unchanged skipping
2017/01/13 10:09:33
Transferred:      0 Bytes (0 Bytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:        2.2s
2017/01/13 10:09:33 Go routines at exit 6
root@drbl:/ceph/drbl# /usr/local/bin/gdrive/rclone copyto -v --config 
/scratch/rclone.creds /tmp/permtest/owner_gdrive-backups2_o gdrive-backu
ps2_o:permtest/owner_gdrive-backups2_o
2017/01/13 10:09:33 rclone: Version "v1.35" starting with parameters 
["/usr/local/bin/gdrive/rclone" "copyto" "-v" "--config" "/scratch/rclone
.creds" "/tmp/permtest/owner_gdrive-backups2_o" 
"gdrive-backups2_o:permtest/owner_gdrive-backups2_o"]
2017/01/13 10:09:33 gdrive-backups2_o: Saved new token in config file
2017/01/13 10:09:34 Google drive root 'permtest': Modify window is 1ms
2017/01/13 10:09:34 owner_gdrive-backups2_o: Couldn't find file - need 
to transfer
2017/01/13 10:09:36 owner_gdrive-backups2_o: Copied (new)
2017/01/13 10:09:36
Transferred:      0 Bytes (0 Bytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:        3.1s
2017/01/13 10:09:36 Go routines at exit 8
root@drbl:/ceph/drbl#
root@drbl:/ceph/drbl# # remove the files
root@drbl:/ceph/drbl# rm /tmp/permtest/owner_gdrive-backups_o
root@drbl:/ceph/drbl# rm /tmp/permtest/owner_gdrive-backups2_o
root@drbl:/ceph/drbl#
root@drbl:/ceph/drbl# # sync the directory with one of the accounts - 
file which is owned gets removed, file which is editable is not removed
root@drbl:/ceph/drbl# /usr/local/bin/gdrive/rclone sync 
--drive-use-trash -v --config /scratch/rclone.creds /tmp/permtest/ 
gdrive-backups2_o:permtest/
2017/01/13 10:09:36 rclone: Version "v1.35" starting with parameters 
["/usr/local/bin/gdrive/rclone" "sync" "--drive-use-trash" "-v" 
"--config" "/scratch/rclone.creds" "/tmp/permtest/" 
"gdrive-backups2_o:permtest/"]
2017/01/13 10:09:37 Google drive root 'permtest': Modify window is 1ms
2017/01/13 10:09:37 Google drive root 'permtest': Reading ""
2017/01/13 10:09:37 Google drive root 'permtest': Finished reading ""
2017/01/13 10:09:37 Google drive root 'permtest': Waiting for checks to 
finish
2017/01/13 10:09:37 Google drive root 'permtest': Waiting for transfers 
to finish
2017/01/13 10:09:37 Waiting for deletions to finish
2017/01/13 10:09:38 owner_gdrive-backups_o: Couldn't delete: googleapi: 
Error 403: Insufficient permissions for this file, forbidden
2017/01/13 10:09:39 owner_gdrive-backups2_o: Deleted
2017/01/13 10:09:39 Attempt 1/3 failed with 1 errors and: failed to 
delete 1 files
2017/01/13 10:09:39 Google drive root 'permtest': Reading ""
2017/01/13 10:09:39 Google drive root 'permtest': Finished reading ""
2017/01/13 10:09:39 Google drive root 'permtest': Waiting for checks to 
finish
2017/01/13 10:09:39 Google drive root 'permtest': Waiting for transfers 
to finish
2017/01/13 10:09:39 Waiting for deletions to finish
2017/01/13 10:09:40 owner_gdrive-backups_o: Couldn't delete: googleapi: 
Error 403: Insufficient permissions for this file, forbidden
2017/01/13 10:09:40 Attempt 2/3 failed with 1 errors and: failed to 
delete 1 files
2017/01/13 10:09:40 Google drive root 'permtest': Reading ""
2017/01/13 10:09:40 Google drive root 'permtest': Finished reading ""
2017/01/13 10:09:40 Google drive root 'permtest': Waiting for checks to 
finish
2017/01/13 10:09:40 Google drive root 'permtest': Waiting for transfers 
to finish
2017/01/13 10:09:40 Waiting for deletions to finish
2017/01/13 10:09:40 pacer: Rate limited, sleeping for 1.287113937s (1 
consecutive low level retries)
2017/01/13 10:09:40 pacer: low level retry 1/10 (error googleapi: Error 
403: User Rate Limit Exceeded, userRateLimitExceeded)
2017/01/13 10:09:40 pacer: Rate limited, sleeping for 2.54916732s (2 
consecutive low level retries)
2017/01/13 10:09:40 pacer: low level retry 2/10 (error googleapi: Error 
403: User Rate Limit Exceeded, userRateLimitExceeded)
2017/01/13 10:09:45 pacer: Resetting sleep to minimum 10ms on success
2017/01/13 10:09:45 owner_gdrive-backups_o: Couldn't delete: googleapi: 
Error 403: Insufficient permissions for this file, forbidden
2017/01/13 10:09:45 Attempt 3/3 failed with 1 errors and: failed to 
delete 1 files
2017/01/13 10:09:45 Failed to sync: failed to delete 1 files

**Comment by ncw** [comment]
@mmozeiko Google says you don't have enough permissions and rclone can't change that...  Can you get the owner of the shared folder to give you more permissions?

**Comment by mmozeiko** [comment]
I believe this is not permission issue. I have "Organize, add & edit" rights on this folder. And (as I wrote already) I can delete files from this folder using web interface just fine.

**Comment by ncw** [comment]
@mmozeiko wrote
> I believe this is not permission issue. I have "Organize, add & edit" rights on this folder. And (as I wrote already) I can delete files from this folder using web interface just fine.

I don't think there are any other parameters that rclone could be sending to drive [to delete](https://developers.google.com/drive/v3/reference/files/delete) something so I'm not sure how I could solve the problem.

Any ideas?

**Comment by mmozeiko** [comment]
I've googled around and it seems this is API limitation of Google Drive. In multiple places people say that API does not allow to remove files from shared folders, but Web UI allows. Unless you are owner...
https://stackoverflow.com/questions/21737495/why-is-google-drive-api-is-not-allowing-to-delete-a-folder-for-user-who-has-can
Sad :(

**Comment by bumerankkk** [comment]
I have just got into this issue too.
As **mmozeiko** writes, it is a known limitation of Google Drive API unfortunately. The possible workaround is to purge the complete target directory with `rclone purge` and then recreate it..if it fits your use-case.
Hope this helps.

BTW, many thanks for the **rclone** tool!

**Comment by ncw** [comment]
@mmozeiko thanks for looking this up.

Perhaps worth a section in the docs?  Anyone fancy adding a bit to [drive.md](https://github.com/ncw/rclone/blob/master/docs/content/drive.md) the [limitations section](https://github.com/ncw/rclone/blob/master/docs/content/drive.md#limitations) seems good?

**Comment by burtonis** [comment]
After running into this issue, I've found that updating the folder permissions to "full" works (I'm using a team drive, but assume it'll be the same).

Obviously edit is read/write/modify but only "full" allows "delete".  A very *nix-y approach!

**Comment by mmozeiko** [comment]
What is "full" permission? I see only "Can organize, add & edit" and "Can view only" access permissions.

**Comment by ncw** [comment]
I'm going to close this now since this isn't an rclone problem as there is a work-around :-)

**Comment by mwittmann** [comment]
Just a follow up idea. Although, as noted in https://github.com/rclone/rclone/issues/1029#issuecomment-375992345, there is a workaround to delete Google Drive files owned by others by `purge`ing the folder that contains them and then recreating the purged folder, this has the negative consequence that the newly created folder, even though it has same name, has a different Google Drive URL. Any permissions, etc., for the folder will be lost, and anyone trying to navigate to the Drive folder using a saved URL will get an error since the original URL is no longer valid.

Fortunately, the Google Drive API **does** allow you to do a server-to-server **move** of files owned by others. So, assuming a use case of wanting to `move` files from Google Drive to a local folder, an alternative workaround goes something like the following, using a temporary server-side folder:

1. For files you want to `move` to a local folder from `GDrive:/folder1`, execute `rclone mkdir GDrive:/folder1.DLtmp` to create a temporary server-side folder.
2. Do a server-to-server move: `rclone moveto GDrive:/folder1/ GDrive:/folder1.DLtmp`
3. Copy from Google Drive to local: `rclone copy GDrive:/folder1.DL ./local_folder`
4. Purge the temporary folder: `rclone purge GDrive:/folder1.DLtmp`

In principle, the above logic could even be incorporated into the `rclone` code base to workaround the (annoying) Google Drive API limitation.
