### ISSUE TITLE
Dropbox upload is really slow

### ISSUE THREAD

**Issue by mrschyte** [ncw/rclone#103]
Dropbox upload seems to be really slow with the rclone client. Using the official dropbox client I get reasonable speeds (around ~1-2 MB/s), but with rclone I get terrible speeds, around 40-50 kb/s.

**Comment by ncw** [comment]
I can see the slow uploads here too,

I'm not entirely sure this is an rclone problem though, there are lots of complaints about slow upload speeds in the [dropbox forum](https://www.dropboxforum.com/hc/en-us/community/posts/201863435-Slow-Upload-Speeds-Why-)

I'll ask dropbox developer support for their opinion on whether I can do anything about this.

Thanks for the report

**Comment by ncw** [comment]
I received this reply from Dropbox support

> Thanks for writing in. Unfortunately the official Dropbox desktop client
> doesn't use the Dropbox API, and the client is substantially more
> complex and works somewhat differently, so it's difficult to draw a
> direct comparison here.
> 
> Also, note that all of the Dropbox servers are located in the US. Your
> connection speed to Dropbox depends on the routing you get between your
> ISP and our servers, and may be slower than your ISP's rated speeds.
> 
> Sometimes resetting or retrying your connection gets you a different
> route and better speeds, but that is outside of our control. Some ISPs
> also throttle sustained connections so if you see an initial high
> connection speed followed by lower speeds, that could be the reason.
> 
> We're always working on improving our infrastructure, but otherwise, as
> user or developer, there's not much else you can do to change the
> overall speeds you get, which depends on many different factors.
> 
> Sorry I don't have a more straightforward answer here!

So I think this probably isn't an rclone problem.

I tried again at work (we are an ISP) where we have a 10 Gbit/s direct to the London Internet Exchange and I got the same result a measly 64kB/s upload speed.

I'm sure that dropbox has worked faster in the past.

It seems to be limited to 64kB/s per file, so if I transfer 4 files at once I can get 256 kB/s transfer speed which is better but still not brilliant.

I'm following up with Dropbox support for more info!

**Comment by ncw** [comment]
@mrschyte Dropbox suport haven't come up with anything from their end.

I'm convinced this is some kind of network problem though, rather than an rclone problem.

I tried rclone again this morning and got a slightly improved 88 kB/s.

Can you paste a [traceroute](http://blog.iweb.com/en/2009/09/how-to-do-a-traceroute-on-windows-linux-and-osx/3111.html) to `content.dropboxapi.com` so I can compare it with mine?

**Comment by austinginder** [comment]
I'm also seeing slow speeds. Here is my traceroute.
```
traceroute to content.dropboxapi.com (107.20.189.103), 30 hops max, 60 byte packets
 1  192.3.29.129 (192.3.29.129)  0.792 ms  1.298 ms  1.325 ms
 2  10.8.17.93 (10.8.17.93)  0.726 ms  0.717 ms  0.747 ms
 3  10.8.40.233 (10.8.40.233)  7.484 ms  7.460 ms  7.428 ms
 4  10.8.24.73 (10.8.24.73)  0.324 ms  0.335 ms  0.319 ms
 5  78.152.57.110 (78.152.57.110)  0.623 ms 78.152.60.38 (78.152.60.38)  0.482 ms  0.595 ms
 6  eth6-1.edge1.nyc4.us.as5580.net (78.152.45.217)  9.889 ms  9.606 ms  9.576 ms
 7  eth2-5.edge1.nyc1.us.as5580.net (78.152.44.78)  9.277 ms  8.911 ms  8.892 ms
 8  paix01-jfk1.amazon.com (198.32.118.102)  9.018 ms  9.080 ms  9.607 ms
 9  * 54.240.229.78 (54.240.229.78)  33.877 ms 54.240.229.84 (54.240.229.84)  34.813 ms
10  * * 54.239.41.217 (54.239.41.217)  34.757 ms
11  * 54.239.108.114 (54.239.108.114)  51.359 ms 54.239.109.0 (54.239.109.0)  74.313 ms
12  54.239.108.111 (54.239.108.111)  33.741 ms * 54.239.108.67 (54.239.108.67)  34.719 ms
13  54.239.109.20 (54.239.109.20)  35.300 ms 54.239.111.252 (54.239.111.252)  53.771 ms 54.239.108.238 (54.239.108.238)  57.044 ms
14  54.239.108.97 (54.239.108.97)  34.411 ms 54.239.108.63 (54.239.108.63)  34.447 ms 54.239.108.199 (54.239.108.199)  34.332 ms
15  205.251.245.55 (205.251.245.55)  34.452 ms 205.251.245.240 (205.251.245.240)  34.621 ms 205.251.245.55 (205.251.245.55)  34.403 ms
16  * * *
17  * * *
18  * * *
19  216.182.224.215 (216.182.224.215)  35.359 ms 216.182.224.217 (216.182.224.217)  35.125 ms 216.182.224.211 (216.182.224.211)  38.797 ms
20  * * *
21  * * *
22  * * *
23  * * *
24  * * *
25  * * *
26  * * *
27  * * *
28  * * *
29  * * *
30  * * *
```

**Comment by ncw** [comment]
[This thread](http://www.scootersoftware.com/vbulletin/showthread.php?13640-Dropbox-poor-upload-speed-and-upload-problems-with-large-files) suggests that increasing the chunk size could improve performance. I'll try that in a bit and report back!

**Comment by ncw** [comment]
Yes, that is it!  I set the chunk size to 64 MB (from 64kB) and my upload went fro 64kB/s to 1.5 MB/s.

I'll experiment with the buffer size and find the smallest sensible value.

I'll also put a flag in so users can change it.

**Comment by austinginder** [comment]
Awesome!

**Comment by ncw** [comment]
Testing the new flag

On a super fast Internet connection, uploading a 222MByte file

```
rclone -v --dropbox-chunk-size=2M --stats=10s copy bigfile dropbox:test
```

Record second reading and final reading

Chunk size | Speed after 20s | At Completion
---------- | --------------- | ---------------
64k        | 78.85 kByte/s   | 
128k       | 154.41 kByte/s  | 
256k       | 263.91 kByte/s  | 
512k       | 419.83 kByte/s  | 
1M         | 737.77 kByte/s  | 
2M         | 1382.89 kByte/s | 1013.74 kByte/s
4M         | 1414.69 kByte/s | 2173.71 kByte/s
8M         | 2765.42 kByte/s | 2626.53 kByte/s
16M        | 3152.70 kByte/s | 3049.36 kByte/s
32M        | 3161.28 kByte/s | 3608.87 kByte/s
64M        | 5051.45 kByte/s | 3502.92 kByte/s
128M       | 6319.20 kByte/s | 4017.70 kByte/s

Chunks aren't buffered into memory, so no real disadvantage making
them very big.

Choose 128M as the default.

**Comment by ncw** [comment]
I've released a binary with this fix in at http://rclone.org - a massive improvement - thanks for raising the issue.

**Comment by klokan** [comment]
BTW Does the chunk size have similar speed boost effect on Google Drive upload? It almost seems so. Would it make sense to change defaults for Google Drive as well?

**Comment by ncw** [comment]
Alas no. You can change the default chunksize with drive with a flag, but I think you'll find it's about right already.
