### ISSUE TITLE
Feature request: skip google documents

### ISSUE THREAD

**Issue by okaresz** [ncw/rclone#1035]
Hey,

I would like to sync a directory which contains google documents on Gdrive. Copying to localhost exports the documents fine, but when using the "sync" command to sync back the local dir to drive, rclone will report an error: "Can't delete google document". (As the local copy doesn't have the native google docs of course, only the exported files.)

Now, I'm happy with the result, as I'm fine with keeping my google docs on drive in their native format, and a local export won't hurt. But I don't like to rely on an error so that my google docs on drive won't get deleted someday.

Can you implement a "skip google docs" switch so that google docs are excluded altogether when the switch is used?

_Using rclone 1.34 on Linux Mint 64bit._

**Comment by ncw** [comment]
Good idea.

Not too tricky - fancy having a go?

**Comment by okaresz** [comment]
I just browsed the source  to see how this all works...
I'm not familiar with Go either, but I'll try, I think I get the idea where to start this little addition. :)

**Comment by ncw** [comment]
That would be great

**Comment by jfneis** [comment]
Just stumbled upon this feature searching for an "ignore Google Docs at all" feature.

Just to see if I got it clear: @okaresz is talking about ignoring Google Docs when syncing/copying files from one place to another or just about "deleting" Google Docs files if they are not present in the source location?

**Comment by ncw** [comment]
> Just to see if I got it clear: @okaresz is talking about ignoring Google Docs when syncing/copying files from one place to another or just about "deleting" Google Docs files if they are not present in the source location?

Ignoring them.  I'd imagine a flag `--drive-no-docs` which would stop rclone reporting the google docs in listings.

**Comment by okaresz** [comment]
Exactly.
I'm also thinking of a next step, when gdocs are only synced (exported) one way (_from_ the drive). This requires that rclone recognizes the exported file belonging to the original gdoc. For example checking if the file name is the same and the extension respects the given `--drive-formats` switch.

This weekend I've got a bit of time to work on this.

**Comment by okaresz** [comment]
@ncw, can you help me pointing out what doc files should I update for this new cmd line switch? :) I don't see which md files are auto-generated, or whether I should build/update the website as well with hugo, etc... (I haven't found any documentation about documentation :D)

**Comment by ncw** [comment]
@okaresz wrote
> can you help me pointing out what doc files should I update for this new cmd line switch? :) I don't see which md files are auto-generated, or whether I should build/update the website as well with hugo, etc... (I haven't found any documentation about documentation :D)

You are right, I should right some docs on how the docs are built!

You should only need to edit `docs/content/drive.md` - everything else is auto created from that.

I make the full docs, the man page, website when doing a release.

**Comment by ncw** [comment]
I added a section in the docs about writing docs!  20c033b48442dfd866074aee6a0f2dd1e6a2abb6

**Comment by okaresz** [comment]
thanks!
pull request with my proposal: #1076

**Comment by ncw** [comment]
Thanks for doing this @okaresz 

A beta with this feature is here

http://beta.rclone.org/v1.35-54-gff8f11d/ (uploaded in 15-30 mins)

**Comment by jfneis** [comment]
Just tested it (1.35-54) and worked as expected. No more Docs exported and no more "cant copy gdocs files". My whole copy (both ways) became much faster. Thanks @okaresz!

**Comment by okaresz** [comment]
I'm glad you found it useful :)

**Comment by WiliTest** [comment]
Awesome! The tag `--drive-no-docs` works (it skip google doc)

**Comment by felipegallego** [comment]
I have just seen a bug or improvement, depends on each person:

I'm using the --drive-skip-gdocs flag because I don't want my google docs to be downloaded nor uploaded from rclone. It works fine. But when I use the "rclone check" feature, it finds 'missing files' because the gdocs are not in the local filesystem. 

Is there a way for the 'rclone check' to avoid google docs? Or can it be implemented somehow? 

Thanks!
