### ISSUE TITLE
Possible edit needed in documentation

### ISSUE THREAD

**Issue by friendlytherapist** [ncw/rclone#1036]
According to [doccumentation]( http://rclone.org/commands/rclone_mount/), to unmount on OSX, use the command `umount -u /path/to/local/mount`. This doesn't work on OSX. To fix it I just left out `-u` and it works fine.

**Comment by ncw** [comment]
Yes you are right there is no mention of `-u` in the [darwin docs](https://developer.apple.com/legacy/library/documentation/Darwin/Reference/ManPages/man8/umount.8.html)
