### ISSUE TITLE
Feature request: follow symbolic link

### ISSUE THREAD

**Issue by kcwu** [ncw/rclone#1037]
> What is your rclone version (eg output from `rclone -V`)
rclone v1.35-DEV

> Which OS you are using and how many bits (eg Windows 7, 64 bit)
FreeBSD

> Which cloud storage system are you using? (eg Google Drive)
Google Drive

When `rclone copy` encountered symbolic links, it rejects and say ` Can't transfer non file/directory`.

Feature request: add a command line option `--follow-links` to `copy` and maybe other commands. Then `rclone copy` dereference the link if the flag is specified.

**Comment by ncw** [comment]
I think this a duplicate of #40 which is scheduled for the next release.

**Comment by kcwu** [comment]
Ah, nice. Sorry for duplication.
