### ISSUE TITLE
suggestion: ability to add the amazon glacier remote if not currently possible

### ISSUE THREAD

**Issue by marrie** [ncw/rclone#1038]
I've ben asked to file this as a suggestion on behalf of  a friend. They and others I know use glacier for cold storage. Is there a way for them to add glacier until the dev team can add it, once we know all is working with b2, s3 etc?

Loving the program

**Comment by ncw** [comment]
I think this is a duplicate of #923 ?

If so could you add your support to that issue please?

Also if you have any ideas about how rclone would implement it, please add there!

**Comment by marrie** [comment]
I will try and find that, thanks.
