### ISSUE TITLE
rmdirs on google drive failing with "directory not empty"

### ISSUE THREAD

**Issue by karan** [ncw/rclone#1040]
> What is your rclone version (eg output from `rclone -V`)

v1.35

> Which OS you are using and how many bits (eg Windows 7, 64 bit)

Mac 10.11.6 64 bit

> Which cloud storage system are you using? (eg Google Drive)

Google Drive

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

`rclone rmdirs <remote>`

The error I get is:

```
2017/01/16 22:49:49 Failed to rmdirs: directory not empty: []*drive.ChildReference{(*drive.ChildReference)(0xc4205fe000), (*drive.ChildReference)(0xc4205fe080)}
```

**Comment by ncw** [comment]
Can you post a log with -v of the problem 

What does 

    rclone ls remote:

And

    rclone lsd remote: --max-depth 100

Say?

Is there some sort of file in the directory tree that rclone doesn't see but does appear on the web interface?

**Comment by reallove0810** [comment]
I'm getting the same problem.
This problem only occurs when you try to backup your files to the same directory by two remotes. Ex: remote1 on this server and remote2 on another server. Both try to rmdirs directory DATABASE.

the 1st one
`rclone copy /dir1 remote1:DATABASE`
`rclone -q --min-age 30d delete remote1:DATABASE`
`rclone -q --min-age 30d rmdirs remote1:DATABASE`
the 2nd one
`rclone copy /dir1 remote2:DATABASE`
`rclone -q --min-age 30d delete remote2:DATABASE`
`rclone -q --min-age 30d rmdirs remote2:DATABASE`

**Comment by ncw** [comment]
I saw a suggestion somewhere (can't find it now) that this was caused by trashed files

I just tried it and that replicates the problem exactly.

```
$ rclone ls drive:a_file
$ rclone rmdirs --retries 1 drive:a_file
2017/01/27 21:07:42 : Failed to rmdir: directory not empty: []*drive.ChildReference{(*drive.ChildReference)(0xc420410300)}
2017/01/27 21:07:42 Attempt 1/1 failed with 1 errors and: directory not empty: []*drive.ChildReference{(*drive.ChildReference)(0xc420410300)}
2017/01/27 21:07:42 Failed to rmdirs: directory not empty: []*drive.ChildReference{(*drive.ChildReference)(0xc420410300)}
```

I'm not sure how to fix this though!  Any ideas?

**Comment by gustavorochakv** [comment]
Isn't that check made on rclone's side? On Google Drive's v3 API the behaviour for the file delete API when applied to a folder is removing both the folder and all of its contents, but I'm not so sure about v2.
If v2 is the same, shouldn't that check simply be bypassed?

**Comment by ncw** [comment]
@gustavorochakv you are right!

I've adjusted the drive code to trash the directory if it has any trashed files in (and no non trashed files).  Otherwise the directory will be trashed or deleted as normal depending on `--drive-use-trash` flag.

Here is a beta with the fix

http://beta.rclone.org/v1.35-104-g33c2873/ (uploaded in 15-30 mins)
