### ISSUE TITLE
Naming of current beta file

### ISSUE THREAD

**Issue by jaketame** [ncw/rclone#1047]
This is a suggestion to create the following files to allow for scripted/ansible rclone updates based on the latest available beta version. It would also be cool if there was changelog to identify what to look at for.

- http://beta.rclone.org/rclone-beta-latest-linux-amd64.zip 
- http://beta.rclone.org/rclone-beta-latest-linux-amd64.md5 
- http://beta.rclone.org/rclone-beta-latest-linux-amd64.version
- http://beta.rclone.org/rclone-beta-latest-linux.changelog

**Comment by ncw** [comment]
Good idea.

The changelog for rclone is hand made by me at each rclone release - I don't want to do that for the betas.  However I could put the git log in which is what I generate the changelog from.

**Comment by metaveli** [comment]
I completely understand - take a look at this -https://pypi.python.org/pypi/gitchangelog, should be able to automate it.

**Comment by ncw** [comment]
This is done in

http://beta.rclone.org/v1.35-128-g86cc9f3/ (uploaded in 15-30 mins)

I made the links as per your suggestion and put a git-log.txt file in the zip

**Comment by ncw** [comment]
Foo, I see I've put the files in the wrong place!

**Comment by ncw** [comment]
Second attempt: http://beta.rclone.org/v1.35-129-g980cd5b/ (uploaded in 15-30 mins)
