### ISSUE TITLE
Rclone mount GSuite Crypted don´t work

### ISSUE THREAD

**Issue by Massaguana** [ncw/rclone#1051]
Hello, having Problems to mount an GSuite Drive...

> What is your rclone version (eg output from `rclone -V`)
v1.35
> Which OS you are using and how many bits (eg Windows 7, 64 bit)
Cent OS 7 64-Bit
> Which cloud storage system are you using? (eg Google Drive)
GSuite Business
> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone mount "GSuite:Plex Cloud" /GSuiteCrypt &
> A log from the command with the `-v` flag (eg output from `rclone -v copy /tmp remote:tmp`)
[root@Plex /]# rclone mount -v "GSuite:Plex Cloud" /GSuiteCrypt &
[1] 21918
[root@Plex /]# 2017/01/19 10:08:18 rclone: Version "v1.35" starting with parameters ["rclone" "mount" "-v" "GSuite:Plex Cloud" "/GSuiteCrypt"]
2017/01/19 10:08:18 Google drive root 'Plex Cloud': Modify window is 1ms
2017/01/19 10:08:18 Google drive root 'Plex Cloud': Mounting on "/GSuiteCrypt"
2017/01/19 10:08:18 Fatal error: failed to mount FUSE fs: fusermount: exec: "fusermount": executable file not found in $PATH

**Comment by flixajki** [comment]
Something is wrong with paths.
Can you do 
rclone listremotes

**Comment by Massaguana** [comment]
[root@Plex /]# rclone listremotes
GSuite:
GSuiteCrypt:
[root@Plex /]#

**Comment by flixajki** [comment]
You should mount with 
rclone mount --allow-non-empty --allow-other GSuiteCrypt:  /local-path/ &

So whatever you uploaded to your crypt folder will be shown in above mounted /local-path/
To upload or move files you would use 
/usr/bin/rclone copy /upload-path/ GSuiteCrypt: 

Iam assuming GSuiteCrypt is remote crypt mount with path GSuite:**/**Plex Cloud
( note iam not sure how rclone handles spaces in folders ... i would change it to Plex-Cloud )

This means that whatever you upload to GSuiteCrypt: will be encrypted in Plex-Cloud folder. 
If your current Plex Cloud folder contains unencrypted files then you need to point crypt remote to new folder eg GSuite:/crypt and you can copy files from current GSuite:/Plex Cloud to GSuiteCrypt: ( the files will be encrypted inside )

**Comment by Massaguana** [comment]
So far I had no problems with spaces...This is my command for uploading files:

'rclone -v sync /Volumes/x264 "GSuiteCrypt:Plex Cloud Crypted/x264"'

name enycption ist set to "standard"... folder Names are crypted too. can not change it with GSuite Homepage... because i see only "ölbjlsjkbfgpsojkhoüjk" or something like that...

Here are my new command for mounting the crypted folder:

'rclone mount -v --allow-non-empty --allow-other "GSuiteCrypt:Plex Cloud Crypted" /var/lib/plexmediaserver/Media/ &'

Thas now the error message:

'''
[root@Plex /]# rclone mount -v --allow-non-empty --allow-other "GSuiteCrypt:Plex Cloud Crypted" /var/lib/plexmediaserver/Media/ &
[1] 22768
[root@Plex /]# 2017/01/19 12:01:37 rclone: Version "v1.35" starting with parameters ["rclone" "mount" "-v" "--allow-non-empty" "--allow-other" "GSuiteCrypt:Plex Cloud Crypted" "/var/lib/plexmediaserver/Media/"]
2017/01/19 12:01:37 Encrypted Local file system at /GSuite/b669l9s6eji1ue9p52ev5st12n8vfl1d8pb0nge59fk3sjdlj91g: Modify window is 1ns
2017/01/19 12:01:37 Encrypted Local file system at /GSuite/b669l9s6eji1ue9p52ev5st12n8vfl1d8pb0nge59fk3sjdlj91g: Mounting on "/var/lib/plexmediaserver/Media/"
2017/01/19 12:01:37 mount helper error: fusermount: mount failed: No such device
2017/01/19 12:01:37 Fatal error: failed to mount FUSE fs: fusermount: exit status 1
^C
[1]+  Exit 1                  rclone mount -v --allow-non-empty --allow-other "GSuiteCrypt:Plex Cloud Crypted" /var/lib/plexmediaserver/Media/
[root@Plex /]# 
'''

**Comment by ncw** [comment]
This error leads me to think your fuse installation might be broken.  Can you try updating it?  Maybe try a new kernel?

```
2017/01/19 12:06:35 mount helper error: fusermount: mount failed: No such device
```

**Comment by Massaguana** [comment]
This is an VPS Server... The Support told me Fuse is running correct, the kernel are new

Is there an way to test fuse?

**Comment by flixajki** [comment]
Try:
`modeprobe fuse` 
and
`fusermount -V`

**Comment by Massaguana** [comment]
> root@Plex /]# modeprobe fuse
> -bash: modeprobe: Kommando nicht gefunden.
> [root@Plex /]# fusermount -V
> fusermount version: 2.9.2
> [root@Plex /]# 

modeprobe told me error "command not found"

**Comment by flixajki** [comment]
You need to write your provider to enable it for you.

I assume they are using openvz so all they need to do:
`vzctl set vpsid --devnodes fuse:rw --save`

**Comment by ncw** [comment]
@Massaguana if you want to test fuse you could try sshfs which your distro probably has a package for.

You then do `sshfs hostname: mountpoint` where hostname is somewhere you can ssh to (maybe the the same server).

**Comment by Massaguana** [comment]
I think my VPS provider does not like what I do with rclone ... Has my server deleted, as there were too many complaints regarding fuse...

Now i am search for an new provider...

**Comment by Massaguana** [comment]
Okay... fuse and modprobe are running now...

mount my GSuite without encryption works fine...

use this command: `rclone mount -v --allow-non-empty --allow-other GSuite: /var/lib/plexmediaserver/Media/ &`

but mount my crypted GSuite don´t work

`rclone mount -v --allow-non-empty --allow-other GSuiteCrypt: /var/lib/plexmediaserver/Media/ &`

In terminal are only this:

[root@Plex /]# 2017/01/28 16:29:20 rclone: Version "v1.35" starting with parameters ["rclone" "mount" "-v" "--allow-non-empty" "--allow-other" "GSuiteCrypt:" "/var/lib/plexmediaserver/Media/"]
2017/01/28 16:29:21 Encrypted Local file system at /GSuite: Modify window is 1ns
2017/01/28 16:29:21 Encrypted Local file system at /GSuite: Mounting on "/var/lib/plexmediaserver/Media/"
2017/01/28 16:29:21 : Dir.Attr
2017/01/28 16:29:21 Encrypted Local file system at /GSuite: Root()
2017/01/28 16:31:19 : Dir.Attr
2017/01/28 16:31:19 : Dir.ReadDirAll
2017/01/28 16:31:19 : Reading directory
2017/01/28 16:31:19 : Dir.ReadDirAll OK with 0 entries

What can i do?

**Comment by Massaguana** [comment]
okay, i think i find my mistake...
