### ISSUE TITLE
Configuration Password Error

### ISSUE THREAD

**Issue by ftl88** [ncw/rclone#1052]
I am unable to use rclone mount with a configuration password. I can successfully set a password in rclone config but when rclone prompts me for the password when I use the rclone mount command it actually types the password.

ie. 
password:password <- actually shows in plaintext while I'm typing
instead of:
password: <- what happens in rclone config. It stays blank while I type 

> What is your rclone version (eg output from `rclone -V`)
v1.35
> Which OS you are using and how many bits (eg Windows 7, 64 bit)
Ubuntu 16.04-64bit
> Which cloud storage system are you using? (eg Google Drive)
ACD
> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone mount
> A log from the command with the `-v` flag (eg output from `rclone -v copy /tmp remote:tmp`)

Your configuration is not encrypted.
If you add a password, you will protect your login information to cloud services.
a) Add Password
q) Quit to main menu
a/q> a
Enter NEW configuration password:
password:
Confirm NEW configuration password:
password:
Password set
Your configuration is encrypted.
c) Change Password
u) Unencrypt configuration
q) Quit to main menu
c/u/q> q

trp@sd-62570:~$ rclone mount -v eacd:A/ ~/mount &
[3] 25791
trp@sd-62570:~$ Enter configuration password:
password:password
No command 'password' found, did you mean:
 Command 'assword' from package 'assword' (universe)
password: command not found

[3]+  Stopped                 rclone mount -v eacd:A/ ~/mount

[3]+  Stopped                 rclone mount -v eacd:A/ ~/mount

**Comment by ncw** [comment]
Try the command without the & 

Then when it is running you can put it into the background with CTRL-Z and then type bg. 

Or you can set an environment variable with the password in - see the docs for more info.

**Comment by ftl88** [comment]
Ahhh, it works perfectly now. Thanks!
