### ISSUE TITLE
Bug: Fast renames of different files in the same directory on ACD cause a non-fatal panic

### ISSUE THREAD

**Issue by gordan-bobic** [ncw/rclone#1053]
> What is your rclone version (eg output from `rclone -V`)
v1.35-DEV

> Which OS you are using and how many bits (eg Windows 7, 64 bit)
Linux x86-64

> Which cloud storage system are you using? (eg Google Drive)
ACD

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
bash loop doing mv in a directory to rename many files

This ends up on stdoud:

2017/01/19 22:27:07 fuse: panic in handler for Rename [ID=0xd2 Node=0x74 Uid=501 Gid=501 Pid=10603] from "file1" to dirnode 0x74 "file2": runtime error: invalid memory address or nil pointer dereference
goroutine 46 [running]:
github.com/ncw/rclone/vendor/bazil.org/fuse/fs.(*Server).serve.func2(0x7f1d2c1a8a00, 0xc8201b0660, 0xc8204dbeb8, 0xc8204dbdd7)
	/home/mock/gopath/src/github.com/ncw/rclone/vendor/bazil.org/fuse/fs/serve.go:857 +0xaf
panic(0xdb29c0, 0xc82000e110)
	/usr/lib/golang/src/runtime/panic.go:443 +0x4e9
github.com/ncw/rclone/vendor/github.com/ncw/go-acd.(*Node).Rename(0xc820130420, 0xc820135951, 0x4d, 0x48c6d8, 0xc8201b1e00, 0x0, 0x0)
	/home/mock/gopath/src/github.com/ncw/rclone/vendor/github.com/ncw/go-acd/nodes.go:310 +0x36f
github.com/ncw/rclone/amazonclouddrive.(*Fs).renameNode.func1(0xc8201b1e00, 0x0, 0x0)
	/home/mock/gopath/src/github.com/ncw/rclone/amazonclouddrive/amazonclouddrive.go:1025 +0x7b
github.com/ncw/rclone/pacer.(*Pacer).call(0xc8201b1e00, 0xc8203bf3c0, 0xa, 0x7f1d2c225028, 0xc821346600)
	/home/mock/gopath/src/github.com/ncw/rclone/pacer/pacer.go:334 +0x8a
github.com/ncw/rclone/pacer.(*Pacer).Call(0xc8201b1e00, 0xc8203bf3c0, 0x0, 0x0)
	/home/mock/gopath/src/github.com/ncw/rclone/pacer/pacer.go:357 +0x7a
github.com/ncw/rclone/amazonclouddrive.(*Fs).renameNode(0xc8201b1ec0, 0xc8204b6180, 0xc820135951, 0x4d, 0xc82132b300, 0x0, 0x0)
	/home/mock/gopath/src/github.com/ncw/rclone/amazonclouddrive/amazonclouddrive.go:1027 +0x15c
github.com/ncw/rclone/amazonclouddrive.(*Fs).moveNode(0xc8201b1ec0, 0xc8213a4e60, 0x9e, 0xc820135951, 0x4d, 0xc8213da360, 0x16, 0xc8204b6180, 0xc8213a4eb1, 0x4d, ...)
	/home/mock/gopath/src/github.com/ncw/rclone/amazonclouddrive/amazonclouddrive.go:1073 +0x38b
github.com/ncw/rclone/amazonclouddrive.(*Fs).Move(0xc8201b1ec0, 0x7f1d2c16a0a8, 0xc8203cdea0, 0xc820135900, 0x9e, 0x0, 0x0, 0x0, 0x0)
	/home/mock/gopath/src/github.com/ncw/rclone/amazonclouddrive/amazonclouddrive.go:653 +0x369
github.com/ncw/rclone/crypt.(*Fs).Move(0xc8203a8190, 0x7f1d2c16a120, 0xc8203b2080, 0xc8203bf340, 0x3d, 0x0, 0x0, 0x0, 0x0)
	/home/mock/gopath/src/github.com/ncw/rclone/crypt/crypt.go:230 +0x209
github.com/ncw/rclone/cmd/mount.(*Dir).Rename(0xc8202185b0, 0x7f1d286e8300, 0xc8203bf200, 0xc8201b0660, 0x7f1d286e8270, 0xc8202185b0, 0x0, 0x0)
	/home/mock/gopath/src/github.com/ncw/rclone/cmd/mount/dir.go:371 +0xbfb
github.com/ncw/rclone/vendor/bazil.org/fuse/fs.(*Server).handleRequest(0xc8201ec540, 0x7f1d286e8300, 0xc8203bf200, 0x7f1d286e8270, 0xc8202185b0, 0xc8203819c0, 0x7f1d2c1a8a00, 0xc8201b0660, 0xc8204dbeb8, 0x0, ...)
	/home/mock/gopath/src/github.com/ncw/rclone/vendor/bazil.org/fuse/fs/serve.go:1335 +0x3899
github.com/ncw/rclone/vendor/bazil.org/fuse/fs.(*Server).serve(0xc8201ec540, 0x7f1d2c1a8a00, 0xc8201b0660)
	/home/mock/gopath/src/github.com/ncw/rclone/vendor/bazil.org/fuse/fs/serve.go:878 +0x740
github.com/ncw/rclone/vendor/bazil.org/fuse/fs.(*Server).Serve.func1(0xc8201ec540, 0x7f1d2c1a8a00, 0xc8201b0660)
	/home/mock/gopath/src/github.com/ncw/rclone/vendor/bazil.org/fuse/fs/serve.go:425 +0x6d
created by github.com/ncw/rclone/vendor/bazil.org/fuse/fs.(*Server).Serve
	/home/mock/gopath/src/github.com/ncw/rclone/vendor/bazil.org/fuse/fs/serve.go:426 +0x580

**Comment by ncw** [comment]
Which version of rclone is that from? make vars in the source directory and it will tell you. 

 I think I fixed that very recently in #973

**Comment by gordan-bobic** [comment]
You are right that looks like the same bug. I'll update. Apologies for the noise, closing.

**Comment by ncw** [comment]
No worries - I'd rather have two bug reports than none!
