### ISSUE TITLE
[feature request] Support for Canadian S3 region

### ISSUE THREAD

**Issue by jyergatian** [ncw/rclone#1054]
Rclone does not offer the new Canadian region when configuring an S3 remote.

> What is your rclone version (eg output from `rclone -V`)
v1.35
> Which OS you are using and how many bits (eg Windows 7, 64 bit)
CentOS 7 & macOS 10.12 - both 64 bit
> Which cloud storage system are you using? (eg Google Drive)
Amazon S3
> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone config

**Comment by ncw** [comment]
Fancy sending a PR? It should be quite straight forward.

**Comment by jyergatian** [comment]
Done. PR #1092
