### ISSUE TITLE
Prevent Drive API Bans limiting requests/sec in a flag

### ISSUE THREAD

**Issue by NeoPhyTe-x360** [ncw/rclone#1057]
A lot of people is injured with daily google API bans because of the amount of request done by scanning apps like plex, infuse, renamers, etc.

So, as I said, I thought to include a flag in Drive mounting, to avoid 24h bans from google API, scan will be slower, or a bit less performance, but I prefer it that get a daily ban, or maybe you can mount the drive with the flag to scan, and when you have finished, mount it normally. I consider it a need for people who have big libraries or who do continous scans in their libs.

I thought in a flag to control seeks/reads/requests/gets per second ,like,

--drive-request-by-second  (or --drive-limit-requests)

that's because I've been banned from google API 4 times in 5 days scanning my library (scanning 1 folder with 950 items I was banned in less than 10 minutes (with checkers 1 transfers 1). 

So a little request queue, limiting the requests by second, would be useful too with plex or scanning file apps. I don't know if it will help, but I think It'll do because the api limits, maybe a beta to try how api responses to that limit could be done

Regards

**Comment by NeoPhyTe-x360** [comment]
#485

**Comment by NeoPhyTe-x360** [comment]
https://github.com/ncw/rclone/issues/485 #485

**Comment by NeoPhyTe-x360** [comment]
This problem is said on issues:
#485 
and
#972

**Comment by NeoPhyTe-x360** [comment]
#485

**Comment by NeoPhyTe-x360** [comment]
GH-485

**Comment by breunigs** [comment]
I believe this feature has been available since 1.37 through the tpslimit and tpslimit-burst flag. See here for more details: https://github.com/ncw/rclone/commit/6f71260acf5235bd86b27ff664bd692d985e9a41
