### ISSUE TITLE
Better handling of "--no-traverse" by "rclone sync"

### ISSUE THREAD

**Issue by DurvalMenezes** [ncw/rclone#1059]
As discussed [here](https://forum.rclone.org/t/no-traverse-does-not-work-with-sync-possible-improvement/816/4), when "--no-traverse" is specified as an option to "rsync clone", the code should be changed to:

1) Raise the warning for "--no-traverse" to be an ErrorLog (like the other messages in that bit of code)
2) Patch the docs to explicitly state sync is not compatible with --no-traverse
3) Remove the remote name from the log message (it isn't relevant to any particular remote) which will make it stand out more

**Comment by ncw** [comment]
I will do this once #517 has landed.

**Comment by ncw** [comment]
I've done this in this beta

http://beta.rclone.org/v1.35-77-gc0ad29c/ (uploaded in 15-30  mins)
