### ISSUE TITLE
Scripting installation of rclone

### ISSUE THREAD

**Issue by mlanner** [ncw/rclone#106]
I've been installing rclone across multiple hosts using Ansible recently and it works well. I just drop the latest rclone into my "files" dir and deploy. However, sometimes I just want/need to do a quick scripted installation of rclone on a single, one-off host without using Ansible. I have a little script similar to the "linux binary" description here: http://rclone.org/install/. However, it requires that I specify the version I want, like: http://downloads.rclone.org/rclone-v1.18-linux-amd64.zip.

It would be awfully convenient to be able to instead reference something like:

http://downloads.rclone.org/linux-amd64/latest

... which could just be a symlink to the latest version.

Thoughts?

**Comment by ncw** [comment]
I think that is a very good idea.  Unfortunately the downloads server (hosted on Swift) doesn't support symlinks so I'll have to upload everything twice, but that isn't a big deal I think.

Eg, I'll upload a `rclone-v1.19-linux-amd64.zip` and a `rclone-current-linux-amd64.zip`.

This would probably be useful to the Arch AUR rclone install: https://aur.archlinux.org/packages/rclone/

**Comment by mlanner** [comment]
Hehe ... didn't think about it being hosted on Swift. Makes sense on the no symlink thing. Your suggested workaround would be great, though. Thanks!

**Comment by ncw** [comment]
I've just released this - you'll see the new links at http://rclone.org/downloads/ in the downloads for scripting section.

Thanks for the suggestion

**Comment by mlanner** [comment]
Fantastic. I'm going to try it out this weekend. Thanks! 
On Aug 28, 2015 3:01 AM, Nick Craig-Wood <notifications@github.com> wrote:I've just released this - you'll see the new links at http://rclone.org/downloads/ in the downloads for scripting section.

Thanks for the suggestion

**Comment by mlanner** [comment]
The new 'current' downloads are great. I built a simple shell script that installs the latest version of rclone for Linux (amd64), which seems to work pretty well. Let me know if you're interested in it.

**Comment by ncw** [comment]
@mlanner great!  I'd be interested to see your script - can you email it?  Thanks Nick

**Comment by mlanner** [comment]
Done.

**Comment by koen-serry** [comment]
Sorry to bring up this thread again, but would it be possible to either drop the version from the path in the zip or drop the embedded folder in the zip altogether? While it's great to have 1 url to download the latest, it's a bit useless to have the version in the foldername.

eg. 
```
  Length      Date    Time    Name
---------  ---------- -----   ----
        0  2015-09-15 07:46   rclone-v1.20-linux-amd64/
    46243  2015-09-15 07:42   rclone-v1.20-linux-amd64/README.txt
 14151616  2015-09-15 07:43   rclone-v1.20-linux-amd64/rclone
    57796  2015-09-15 07:42   rclone-v1.20-linux-amd64/README.html
    51388  2015-09-15 07:42   rclone-v1.20-linux-amd64/rclone.1
---------                     -------
 14307043                     5 files

````

**Comment by ncw** [comment]
@koen-serry can you use the `-j` flag of unzip which ignores the internal directory structure?

**Comment by koen-serry** [comment]
Yes thanks didn't know you could use the -j with the extract just one file (with a wildcard).

**Comment by mlanner** [comment]
Koen, 
I wrote an install script that takes care of that. At first I thought the same as you, that it was a bit unnecessary to wrap it like that. However, I think it's actually good so that you can know what version you're installing. If you automate the installation against "current", it's arguably good to know. 
On Sep 17, 2015 12:57 AM, Koen Serry <notifications@github.com> wrote:Sorry to bring up this thread again, but would it be possible to either drop the version from the path in the zip or drop the embedded folder in the zip altogether? While it's great to have 1 url to download the latest, it's a bit useless to have the version in the foldername.

eg. 

  Length      Date    Time    Name
---------  ---------- -----   ----
        0  2015-09-15 07:46   rclone-v1.20-linux-amd64/
    46243  2015-09-15 07:42   rclone-v1.20-linux-amd64/README.txt
 14151616  2015-09-15 07:43   rclone-v1.20-linux-amd64/rclone
    57796  2015-09-15 07:42   rclone-v1.20-linux-amd64/README.html
    51388  2015-09-15 07:42   rclone-v1.20-linux-amd64/rclone.1
---------                     -------
 14307043                     5 files
