### ISSUE TITLE
Add filtering for rclone mount

### ISSUE THREAD

**Issue by kardus** [ncw/rclone#1060]
Would be great to allow filtering for mounting, for example if one wanted to --exclude a crypted directory/remote from the root remote's listing.

**Comment by ncw** [comment]
I've done this in this beta

http://beta.rclone.org/v1.35-103-gdac4bb2/ (uploaded in 15-30 mins)

**Comment by zenjabba** [comment]
Does this mean I could filter our .grab directory that Plex DVR makes?

**Comment by ncw** [comment]
> Does this mean I could filter our .grab directory that Plex DVR makes?

You can use [rclone's normal filtering](https://rclone.org/filtering/) with mount, yes

**Comment by zenjabba** [comment]
so I have this filter file, am I doing something wrong?

If i create a folder in /Plex/videos/tv/.grab (that's the folder layout according to google drive) it shows up in my google drive, but I'm asking it to ignore doing that... basically anything in .grab I want it to ignore.

- /Plex/videos/tv/.grab
+ *

**Comment by ncw** [comment]
I think you probably want to say this to ignore the directory and anything under it

```
- /Plex/videos/tv/.grab/**
+ *
```

**Comment by zenjabba** [comment]
I'll give that a try
