### ISSUE TITLE
[Feature Request] Output JSON

### ISSUE THREAD

**Issue by Wundark** [ncw/rclone#1063]
It would be great if rclone could output JSON (with a flag), so if a script wanted to process the output it could easily.

**Comment by ncw** [comment]
Which output are you interested in?

**Comment by Wundark** [comment]
The output of commands such as: ls and lsd

**Comment by ncw** [comment]
That would be relatively easy. Fancy giving it a go?

**Comment by Wundark** [comment]
I had a look before created this request and I kind of got lost in the code. Care to point me in the right direction?

**Comment by ncw** [comment]
In fs/operations.go examine the ListLong function.

You'd want to write a variant of that and call it from cmd/ls/ls.go when a --json flag is set.

Something like that!

**Comment by Wundark** [comment]
After a few hours of playing with this, it looks to be a little beyond my skill set. As rows are currently being printed as needed to the console, there isn't a definitive array of values to get. There would need to be a way to collect all of the rows from the data source, then the array can be converted to JSON.

**Comment by ncw** [comment]
@Wundark 
I would encode each line at a time, so at the start print a `[` then encode each line then print a `]` at the end.

**Comment by jahands** [comment]
This feature would be really helpful for me. I use rclone from PowerShell a lot and have to manually parse the output. But if rclone had --json I could do something like `$fileList = rclone ls remote: | ConvertFrom-Json`

**Comment by mh-cbon** [comment]
@ncw 

>  I would encode each line at a time, so at the start print a [ then encode each line then print a ] at the end.

May i suggest to do a json stream with one json object per line.

Doing so the client reader of the son does not need to wait until the end of the backup to interpret the json feed.

 So given that output, (-vv)

```
2017/03/11 12:59:34 INFO  : 
Transferred:   7.328 MBytes (62.472 MBytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:       100ms
Transferring:
 * "file1": 86% done, 0 Bytes/s, ETA: -
 * "file2": 21% done, 0 Bytes/s, ETA: -
 * "file3": 14% done, 0 Bytes/s, ETA: -
 * "file4": 11% done, 0 Bytes/s, ETA: -

2017/03/11 12:59:34 INFO  : file1: Copied (new)
2017/03/11 12:59:34 INFO  : folder2/some/other/emptyfile2: Copied (new)
```

Rclone would return three objects,
```json
{...stats}
{copied + new + path}
{copied + new + path}
```

**Comment by ncw** [comment]
@mh-cbon interesting idea.  That is a whole new level of JSON-ness - I've interpreted this issue as being about just having a version of ls which outputs JSON

**Comment by vesper8** [comment]
really interested in using this feature as currently the output of ls is a bit difficult to parse into a mysql db because there seems to be no way to specify the desired formatting from ls so it just seperates by space, but weirdly the first field which is the filesize in bites is center aligned when piping out to a text file?

is there a work-in-progress version of this json output? Or is there any other way to tell the rclone ls command what type of formatting is desired? EG comma separated at the least?

Would be great to be able to output the dates and mime type as well!

Looking forward to using this as it would help with using a better advanced search system than the joke-of-a-search that is currently implemented on dropbox

**Comment by ncw** [comment]
I've implemented a new command lsjson in this beta - let me know what you think.

https://beta.rclone.org/v1.36-185-g64662bef/ (uploaded in 15-30 imins)

**Comment by jahands** [comment]
This is fantastic, thank you! Now I can `rclone lsjson | ConvertFrom-Json` in PowerShell to really easily work with GDrive in PS!

Soon I'll be able to throw away my terrible PowerShell rclone parsing code :)

**Comment by schui95** [comment]
Generally speaking, rclone should have this JSON flag for every available command, such as listremotes.
Is an global approach already there?

**Comment by ncw** [comment]
@schui95 there isn't a global `--json` approach yet.  However there are a lot commands which do dump JSON `rclone config dump` for instance is a superset of `rclone listremotes` and `rclone config providers` will show how to configure each backend.

**Comment by schui95** [comment]
@ncw Thank you for this superset!

**Comment by autr** [comment]
A `--json` flag would be fantastic for the entire CLI!

Here is a quick'n'hacky solution for viewing totals from `rclone check` in a JS API:

```

const ids = ['matching_files', 'differences_found', 'files_missing', 'errors_while_checking'];
stderrStr.split('\n').forEach( line => {

	ids.forEach( id => {
		let i = line.indexOf(id);
		if (i == -1) i = line.indexOf( id.replace(/_/g, ' ') );
		if (i != -1) {
			const ii = line.lastIndexOf(':');
			if (ii != -1) {
				let num = line.substring(ii + 1, i);
				out[id] = parseInt(num);
			}
		}
	});

});

console.log('----------')
console.log(out)
console.log('----------')  
```

ie.

```
{
  files_missing: 5,
  differences_found: 5,
  errors_while_checking: 5,
  matching_files: 6
}
```
