### ISSUE TITLE
--delete-excluded not deleting files from remote

### ISSUE THREAD

**Issue by SukkoPera** [ncw/rclone#1064]
> What is your rclone version (eg output from `rclone -V`)

rclone v1.35 (Linux ARM32 precompiled binary)

> Which OS you are using and how many bits (eg Windows 7, 64 bit)

Linux xxx 4.1.15+ #830 Tue Dec 15 16:58:28 GMT 2015 armv6l BCM2708 GNU/Linux

> Which cloud storage system are you using? (eg Google Drive)

Amazon Drive

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

I was trying to sync a pics folder to AD. The folder has some cruft from OS X and from my Synology NAS, which was copied to remote as soon as the command started. So I stopped the command and rerun it with some --exclude's to filter out the cruft. I also wanted the cruft to be deleted from the remote, so I added --delete-excluded. Now, maybe I don't understand how this flag works, but the cruft remains on the remote. My command is:

    rclone sync somefolder amazon:/Foto/somefolder/ -v --exclude '@eaDir/*' --exclude '._*' --exclude .DS_Store --delete-excluded

In the logs I get:

    2017/01/23 21:33:49 .DS_Store: Excluded from sync (and deletion)

Why is the file getting excluded from deletion? And besides that, why do I get the same behaviour regardless of whether I use the --delete-excluded option or not? Is this a bug?

**Comment by ncw** [comment]
Are files being left behind on the remote, or only directories?

rclone doesn't remove directories at the moment - use `rclone rmdirs` for that.

**Comment by SukkoPera** [comment]
You are right. Files are being deleted, only directories are left behind.

I'm fine with that (so this is getting closed), but maybe the docs should be improved about this feature.

Also, the `rclone rmdirs` command is not documented at http://rclone.org/docs/.

**Comment by vesper8** [comment]
@ncw I came here with the same issue. using rmdirs works fine for the root path but how can we run it so that it removes empty directors recursively?

I have a bunch of nested .git folders that I want to remove, rclone is doing a good job of syncing recursively but I need help understanding how I can tidy it up and remove all empty dirs everywhere

your advice is always appreciated. thanks!
