### ISSUE TITLE
copy, sync, move considerations.

### ISSUE THREAD

**Issue by thr0nic** [ncw/rclone#1070]
When doing a daily automated transfer of files, I currently perform a **rclone copy** action in a bash script that also looks for 2 days old files, and clean them up manually (find -mtime). My concern is that **rclone move** could create data loss if e.g. interrupted by system reboot, process killed by any reason, network connection loss, attempting to move incomplete files in the middle of being copied, or anything similar unforeseen interruptions.

A copy action will simply retry the same files on the next time the script runs regardless, so I consider it safer by default. Is there a chance move action could loose files entirely in the above scenario? Am I wrong in my thinking, or is copy safer to use?

If not, then move is obviously simpler than copy+cleanup. I'd just like an official comment on this.

**Comment by ncw** [comment]
Move will only delete the source **after** the copy has completed successfully.

Move will retry things in the same way as copy, so if some files fail to move, then they will be moved on the next run.

> Is there a chance move action could loose files entirely in the above scenario?

Move is designed not to lose files so (barring bugs) it should do what you want.

**Comment by thr0nic** [comment]
Thank you for the quick response.
