### ISSUE TITLE
"Invalid Credentials, authError" - Google drive sync fail

### ISSUE THREAD

**Issue by isaiah36** [ncw/rclone#1071]
When filing an issue, please include the following information if possible as well as a description of the problem.  Make sure you test with the [latest beta of rclone](http://rclone.org/downloads/).

If you've just got a question then please use the [rclone forum](https://forum.rclone.org/) instead of filing an issue.

> What is your rclone version (eg output from `rclone -V`)
1.35
> Which OS you are using and how many bits (eg Windows 7, 64 bit)
Win 7 64
> Which cloud storage system are you using? (eg Google Drive)
Google Drive
> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
sync
> A log from the command with the `-v` flag (eg output from `rclone -v copy /tmp remote:tmp`)

This is the first time I have used rclone on Windows.  (The objective was to avoid multiple versions of files being created by Google's desktop app.)

Here is how the output ends:
"Failed to sync: error listing: Google drive root 'Documents': couldn't list directory: googleapi: Error 401: Invalid Credentials, authError"

**Comment by ncw** [comment]
> "Failed to sync: error listing: Google drive root 'Documents': couldn't list directory: googleapi: Error 401: Invalid Credentials, authError"

I suspect you filled in 

```
client_id = 
client_secret = 
```

You need to leave these blank.

**Comment by isaiah36** [comment]
Nope, I left them blank, as prompted. It took me to a web page where I gave rclone permission.

It detected many duplicate files. It did something for 2h 44m before putting out the error.

**Comment by ncw** [comment]
> Nope, I left them blank, as prompted. It took me to a web page where I gave rclone permission.

Ah, OK

> It detected many duplicate files. It did something for 2h 44m before putting out the error.

I wonder if the token expired.

Do you know what it was doing when it went wrong?  Try with the -v flag.

**Comment by isaiah36** [comment]
Ok. I am running this now -

`rclone sync -v --log-file C:\Users\Isaiah\Downloads\rclone-log.txt C:\Users\Isaiah\My_Documents Gdrive:Documents`

**Comment by isaiah36** [comment]
Log file attached
[rclone-log.txt](https://github.com/ncw/rclone/files/736602/rclone-log.txt)

**Comment by zenjabba** [comment]
2017/01/27 19:16:22 pacer: low level retry 3/10 (error googleapi: Error 403: User Rate Limit Exceeded, userRateLimitExceeded)

You ran out of API calls by the looks of things

**Comment by ncw** [comment]
@isaiah36 
I would say that is working properly.  A few userRateLimitExceeded is perfectly normal - it is just google telling rclone to slow down.

The sync failed because of this

    2017/01/27 17:40:35 Attempt 1/3 failed with 0 errors and: error listing source: Local file system at \\?\C:\Users\Isaiah\My_Documents: directory not found

So apparently the directory you were trying to sync doesn't exist.

The fact it did a complete remote traversal before telling you is in #1067 which should be fixed shortly.

**Comment by isaiah36** [comment]
The directory does exist. What is the proper way to account for black spaces in directory names? I used an underscore to join the word.

Windows sucks generally. I will complete my hardware upgrade in a day or two, and return to running rclone on Linux. Meanwhile, I'll manually back up files that I've edited.
