### ISSUE TITLE
unable to access mounted drive and all files/folders inside

### ISSUE THREAD

**Issue by trippinshrumes** [ncw/rclone#1072]
The issue is that I'm not able to access my entire mounted drive and all files/folders inside

> What is your rclone version (eg output from `rclone -V`)
1.35
> Which OS you are using and how many bits (eg Windows 7, 64 bit)
Ubuntu 16.04
> Which cloud storage system are you using? (eg Google Drive)
amazon drive

My cloud is set up with a Zeus folder in the root, then 4 category folders inside etc

I mount my cloud with "/home/plex/sbin/rclone mount acd:Zeus /home/plex/.acd --allow-other &"

Then I use "encfs /home/plex/.acd /home/plex/acd"

When I view the contents .acd I see the 4 category folders, although when I go to acd I see 1 Zeus folder then 4 category folders. The unencrypted acd folder is not displaying anything in the movie folder for instance, yet I can confirm that it is encrypted on the cloud.

When I perform an upload I use "sudo rclone copy /home/plex/.local/* acd:Zeus" This ensures all of my category folders get uploaded.

Although what I realized then was I had been uploading everything to the incorrect directories.

So I changed my mount script to "/home/plex/sbin/rclone mount acd:Zeus/Encryptedfoldername /home/plex/.acd --allow-other &"

But when I do this, I see files in the encrypted folder but not in the unencrypted folder. The only way the unencrypted folder shows anything is only if it can display Zeus first. Also I don't understand why that isn't unencrypting into the directory propery, this encryptedfoldername through Zeus is just another copy of Zeus but encrypted. I encrypted it with my encfs file and password shouldn't it just mirror everything back through the unencrypted folder?

I'm not sure if this is a bug from encfs or rclone so I'm going to post it on both and see what happens. Thanks!

**Comment by ncw** [comment]
I don't 100% understand your setup, but this

> When I perform an upload I use "sudo rclone copy /home/plex/.local/* acd:Zeus" This ensures all of my category folders get uploaded.

means that you are uploading unencrypted files to acd doesn't it?

You will probably be better off asking on the forum about this

**Comment by trippinshrumes** [comment]
It was my problem, I had my directory structure incorrect. 

I don't see an option to delete this thread, so can you please close it. 

Thanks!

**Comment by ncw** [comment]
Glad you sorted it!
