### ISSUE TITLE
GSuite Drive mount for Plex usage

### ISSUE THREAD

**Issue by Massaguana** [ncw/rclone#1074]
Hello rclone Team,

ich wood like to use your rclone with an VPS Server runs CentOS 7 64-Bit with running PlexMediaServer on it.

Mounting my GSuite Drive works, but i can Play/ Access any file...

My mount looks like this:
`nohup rclone mount -v --allow-non-empty --allow-other GSuiteCrypt: /var/lib/plexmediaserver/Media/ &`

> What is your rclone version (eg output from `rclone -V`)
v1.35
> Which OS you are using and how many bits (eg Windows 7, 64 bit)
CentOS 7 64-Bit
> Which cloud storage system are you using? (eg Google Drive)
GSuite Drive Business
> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
[root@Plex ~]# rclone copy /tmp remote:tmp
2017/01/29 11:28:36 Failed to create file system for "remote:tmp": didn't find section in config file
[root@Plex ~]# 
> A log from the command with the `-v` flag (eg output from `rclone -v copy /tmp remote:tmp`)

**Comment by banjopotato** [comment]
This is a question for the [rclone forum](http://forums.rclone.org).

**Comment by Massaguana** [comment]
There are a lot of question about it, but no answer...

**Comment by ncw** [comment]
Check that your fuse.conf has `user_allow_other`.

```
$ cat /etc/fuse.conf
# /etc/fuse.conf - Configuration file for Filesystem in Userspace (FUSE)

# Set the maximum number of FUSE mounts allowed to non-root users.
# The default is 1000.
#mount_max = 1000

# Allow non-root users to specify the allow_other or allow_root mount options.
user_allow_other
```

If that doesn't work, you'll get more help in the forum.

**Comment by Massaguana** [comment]
This are my settings:
```
[root@Plex ~]# cat /etc/fuse.conf
# mount_max = 1000
# user_allow_other
[root@Plex ~]# 
```

**Comment by ajkis** [comment]
Change line `# user_allow_other ` to `user_allow_other`

**Comment by Massaguana** [comment]
you mean --allow-other to --user_allow_other right?

`nohup rclone mount -v --allow-non-empty --user_allow_other GSuiteCrypt: /var/lib/plexmediaserver/Media/ &`

**Comment by TerrorFactor** [comment]
You need to change the line in /etc/fuse.conf, your command was correct.

**Comment by Massaguana** [comment]
okay, change the fuse.conf to

```
# mount_max = 1000
user_allow_other
```
and use this command for mount: 

`nohup rclone mount -v --allow-non-empty --allow-other GSuiteCrypt: /var/lib/plexmediaserver/Media/ &`

**Comment by saitoh183** [comment]
@Massaguana 

Did it work?

**Comment by Massaguana** [comment]
Yes
