### ISSUE TITLE
Suggestion: show config pathname with -v

### ISSUE THREAD

**Issue by hashbackup** [ncw/rclone#1086]
Had a user with an rclone problem that I think is because once he ran it as his normal userid (it worked), then ran it as root (it failed).  The error was:
```
2017/01/31 03:01:08 Failed to create file system for
"gdrive_alberto:<pathname>":  didn't find section in config file
```
No idea what that error message means, but I think it's using the wrong .rclone.conf file.

Suggest that when using -v, display a message like "Reading rclone config from <pathname>"

**Comment by ncw** [comment]
Nice idea - thanks!

I also keep meaning to make `rclone config file` and `rclone config show` to show the location of the config file and dump it...
