### ISSUE TITLE
Bind networking to a specific interface or IP

### ISSUE THREAD

**Issue by author2** [ncw/rclone#1087]
I made a question in https://forum.rclone.org/t/rclone-bound-to-particular-interface-ip/936

I was hoping to be able to bind rclone to a specific interface.For example if you are using a VPN on tun0, rclone will always connect through here, but i want to be able to change this, and be able to connect to eth0 and avoid use of the VPN. 

It'd be great if this could be considered in rclone's development.

Thank you.

**Comment by seuffert** [comment]
this could include: use IPv4 or IPv6 only

**Comment by ncw** [comment]
I've done this with the `--bind` flag - give it an IPv4 address and IPv6 address or a host name.

https://beta.rclone.org/v1.37-021-g9f246395/ (uploaded in 15-30 mins)

**Comment by seuffert** [comment]
thanks a lot!

please see my comment in the commit:
https://github.com/ncw/rclone/commit/9f2463956884c0e995cf6f7140af0dc06af096e0#commitcomment-23251156

**Comment by ncw** [comment]
Here is a beta for all platforms (the previous one only built for windows)

https://beta.rclone.org/v1.37-023-gc3d6cc91

(Will fix the typo in the commit - thanks)

**Comment by ncw** [comment]
New beta with the fixed message

https://beta.rclone.org/v1.37-024-g1ecf2bcb/ (uploaded in 15-30 mins)
