### ISSUE TITLE
[feature request] multi-part downloading and delta updates

### ISSUE THREAD

**Issue by 2600box** [ncw/rclone#1095]
When I download a large file, I top out at about 500KB/s. If I use a multi-part downloader, I can push my downloads over 10MB/s. 

This is a limitation of my connection, because from fast datacentre connections I pull 20MB/s - but multi-part concurrent downloads would speed up home downloads.

Is there any way to add this functionality to rclone? For many files, they can already run concurrently, but I am talking about single large files.

I think this is related, - is there anyway to replicate rsync functionality of delta downloads like the switches: --checksum --inplace --no-whole-file - this would also be useful to resume large downloads and to check integrity.

**Comment by jtagcat** [comment]
#87 related
Resuming probably depends on the remote, if you can initiate a download from point x.
When you want multi-threaded AND resuming, you need to know, when exactly did your net go down. For that rclone would need to keep track of it in a file somewhere, achieving that may be difficult with rclone, as it tries to not add any other unnecessary files. That said, a temporary hidden file for a feature might be acceptable.

**Comment by ncw** [comment]
rclone now supports multithreaded downloads: https://rclone.org/docs/#multi-thread-cutoff-size which works very well for large files.

The delta checksum idea isn't possible as it would need support from the cloud provider.

I shall close this now.
