### ISSUE TITLE
google cloud storage: setup problems

### ISSUE THREAD

**Issue by chuan137** [ncw/rclone#110]
Nice project, sadly I couldn't make it work. Could anybody give me some hints.
I set up the configuration like this
```
type = google cloud storage
client_id = 
client_secret = 
project_number = 307110069872
object_acl = private
bucket_acl = private
```
but i always get error, eg.

>rclone mkdir gd:sync
>2015/08/23 19:36:38 Failed to mkdir: googleapi: Error 403: The account for the specified project has been disabled., accountDisabled

**Comment by ncw** [comment]
According to [stackoverflow](http://stackoverflow.com/questions/18672860/can-not-create-bucket-the-account-for-the-specified-project-has-been-disabled)

This can happen when the Cloud Storage service isn't turned on for your project.  Do the following:

  1. Visit http://cloud.google.com/console
  2. Select your project
  3. Visit the APIs & Auth tab
  4. Find Google Cloud Storage in the list of services
  5. Turn on Google Cloud Storage

Does that help?

**Comment by chuan137** [comment]
It is already enabled.

I created a new project under google developer console, 'RcloneSync'. The cloud storage api is enabled by default. And I use the project number of this 'RcloneSync', in the configuration. Is that correct?

**Comment by ncw** [comment]
If if I look in my developer console I seem to have `Google Cloud Storage` and `Google Cloud Storage JSON API` enabled. Have you got both of those?  I think that the one with JSON in is the important one!

Using the project number is correct.

If that doesn't work: Did you create the config using `rclone config`? There should be a token in `.rclone.conf` if so - can you check?  `rclone --help` will show the location of the config file under the help for `--config`.  If there isn't a token line, then use `rclone config` and run through the configuration again.

**Comment by ncw** [comment]
@chuan137 did you try the above?  Let me know how it went - thanks

**Comment by ncw** [comment]
I'm going to close this for the moment.  Please feel free to re-open with more comments.

Thanks

Nick

**Comment by jaslinfernando** [comment]
it does not work...sorry... billing?

**Comment by ncw** [comment]
@jaslinfernando are you having the same problem? Did you try the above steps?

**Comment by geostant** [comment]
I might have found the problem, had a similar issue just now.
Bucket names need to be unique and `rclone` won't let you know if a name already in use.

Better to create the bucket from the UI and continue from there with rclone.
