### ISSUE TITLE
--dry-run updates modification time in destination

### ISSUE THREAD

**Issue by balazer** [ncw/rclone#1100]
rclone v1.35-40-gb6848a3ß
running in Windows XP 32-bit
Google Drive is the remote.

When I do an rclone sync with the --dry-run option, if a file has identical contents but has a different modification time, rclone updates the remote modification time.  According to the docs, --dry-run should not make any permanent changes.

`rclone sync -v --dry-run test remote:test`

>2017/02/04 12:18:33 rclone: Version "v1.35-40-gb6848a3ß" starting with parameters ["rclone" "sync" "-v" "--dry-run" "test" "remote:test"]
2017/02/04 12:18:34 Google drive root 'test': Modify window is 1ms
2017/02/04 12:18:34 Google drive root 'test': Not making directory as dry run is set
2017/02/04 12:18:34 Google drive root 'test': Reading ""
2017/02/04 12:18:34 Google drive root 'test': Finished reading ""
2017/02/04 12:18:34 test.txt: Modification times differ by -1m25.375s: 2017-02-04 12:18:27.696 -0800 PST, 2017-02-04 20:17:02.321 +0000 UTC
2017/02/04 12:18:34 Google drive root 'test': Waiting for checks to finish
2017/02/04 12:18:35 test.txt: Updated modification time in destination
2017/02/04 12:18:35 test.txt: Unchanged skipping
2017/02/04 12:18:35 Google drive root 'test': Waiting for transfers to finish
2017/02/04 12:18:35 Waiting for deletions to finish
2017/02/04 12:18:35
Transferred:      0 Bytes (0 Bytes/s)
Errors:                 0
Checks:                 1
Transferred:            0
Elapsed time:        1.6s
2017/02/04 12:18:35 Go routines at exit 5

**Comment by ncw** [comment]
I just checked the code - yes you are right!

I'll fix this.

**Comment by balazer** [comment]
Thanks. :)  It's not a big deal, really, but the behavior was unexpected.  

I'm still rocking the --backup-dir option.  It's working extremely well and I can't thank you enough.

**Comment by ncw** [comment]
@balazer You should definitely win a prize for noticing that - it has been like that since the very first version of rclone!

**Comment by ncw** [comment]
I've fixed this in http://beta.rclone.org/v1.35-102-gb52c80e/ (uploaded in 15-30 mins)
