### ISSUE TITLE
lsl with max-depth for Dropbox remote doesn't list files

### ISSUE THREAD

**Issue by mmozeiko** [ncw/rclone#1103]
I use rclone 1.35 on Windows. When trying to execute rclone with `lsl` command on non-root folder together with `--max-depth 1` I get strange behavior.

For some folders it works fine, `rclone lsl --max-depth 1 MyDropbox:data/folderA` correctly shows:

       352545 2014-12-21 06:10:53.000000000 a.pdf
       139217 2014-12-20 09:11:34.000000000 b.pdf

But for other it shows error, `rclone lsl --max-depth 1 MyDropbox:data/folderB`

    2017/02/04 22:56:48 path "/data/folderB/some-file.pdf" is not under root "/data/folderB/"

Dropbox web interface shows that `some-file.pdf` file is really inside data/folderB folder.
Adding -v shows following:

    2017/02/04 22:59:49 rclone: Version "v1.35" starting with parameters ["C:\\bin\\rclone.EXE" "lsl" "--max-depth" "1" "-v" "MyDropbox:data/folderB"]
    2017/02/04 22:59:50 Dropbox root 'data/folderB': Modify window not supported                                                                                           
    2017/02/04 22:59:50 path "/data/folderB/some-file.pdf" is not under root "/data/folderB/"

Doing `rclone lsl MyDropbox:data/folderB` correctly displays all files in folderB (and its subfolders).
Doing `rclone lsl --max-depth 2 MyDropbox:` shows error message:

    2017/02/04 23:03:14 level value not supported

What is wrong here?

**Comment by mmozeiko** [comment]
`lsd` also fails for some folders. But not all. Here's example with -v argument:

    C:\test>rclone lsd --max-depth 1 -v MyDropbox:data/folderC
    2017/02/04 23:28:26 rclone: Version "v1.35" starting with parameters ["C:\\bin\\rclone.EXE" "lsd" "--max-depth" "1" "-v" "MyDropbox:data/folderC"]
    2017/02/04 23:28:26 Dropbox root 'data/folderC': Modify window not supported
    2017/02/04 23:28:26 path "/data/folderC/doc.pdf" is not under root "/data/folderC/"

folderC doesn't have any subfolders, but rclone complains about files in it?

Here's one with subfolders

    C:\test>rclone lsd --max-depth 1 -v MyDropbox:data/folderD
    2017/02/04 23:29:36 rclone: Version "v1.35" starting with parameters ["C:\\bin\\rclone.EXE" "lsd" "--max-depth" "1" "-v" "MyDropbox:data/folderD]
    2017/02/04 23:29:36 Dropbox root 'data/folderD': Modify window not supported
    2017/02/04 23:29:36 path "/data/folderD/temp" is not under root "/data/folderD/"

`temp` is a valid subfolder inside `data/folderD`

**Comment by ncw** [comment]
I think this is the same issue as #693 and #691

It is to do with dropbox not always returning the directories with the same case.

I could do with some help fixing this - it requires a new approach to the dropbox internals.

Probably what someone should do is re-write the dropbox remote using the v2 API and fix this issue along the way!

**Comment by mmozeiko** [comment]
Oh, sorry I tried to search, but didn't found those issues.
It seems this is the same problem. Feel free to close this issue.

**Comment by ncw** [comment]
I may have fixed this in #1165 - would you mind testing with this beta and let me know what happens please?

http://beta.rclone.org/v1.35-138-g527099a/

**Comment by mmozeiko** [comment]
Nice, now it works correctly for me.

**Comment by ncw** [comment]
Excellent - thanks for testing.
