### ISSUE TITLE
rclone sync not deleting files in target using --include and "/" as source folder.

### ISSUE THREAD

**Issue by hkbakke** [ncw/rclone#1104]
Trying to use sync to ACD using encryption to the root folder backup-1:

`2017/02/05 14:18:30 rclone: Version "v1.35" starting with parameters ["/usr/local/sbin/rclone" "--include" "zpools/media-1/media/**" "--include" "zpools/media-2/media/**" "sync" "/" "acd-encrypted:" "--max-size" "50000M" "--verbose"]`

The issue I am having is that if I at some point had another folder in sync, i.e "--include" "zpools/prod-1/temp/**" those files are not removed from the destination when I remove the include. The sync prints out no errors non-verbosely, but with --verbose it initially prints:

```
2017/02/05 14:18:32 Encrypted amazon drive root 'backup-1': Modify window not supported
2017/02/05 14:18:32 amazon drive root 'backup-1': Reading ""
2017/02/05 14:18:32 initrd.img.old: Can't transfer non file/directory
2017/02/05 14:18:32 vmlinuz: Can't transfer non file/directory
2017/02/05 14:18:32 initrd.img: Can't transfer non file/directory
2017/02/05 14:18:32 vmlinuz.old: Can't transfer non file/directory
```

These are symlinks in the local source folder "/". Are these errors preventing deletion?
Why are files in "/" even checked for transfer when "/" are not in the included list?

Expected behaviour is that anything not included is deleted. "/" is used as source to be able to easily include anything I want regardless of location on the host only changing includes.

**Comment by ncw** [comment]
Sounds like you want --delete-excluded - try with --dry-run first! 

The warnings about symonds won't affect anything.

**Comment by hkbakke** [comment]
Sorry for wasting your time. I even looked specifically for that option (after being used to using it with rsync) in the --help output but managed to overlook it.

**Comment by ncw** [comment]
@hkbakke no worries!
