### ISSUE TITLE
Amazon Cloud Too Many Request

### ISSUE THREAD

**Issue by mmiat** [ncw/rclone#1106]
> What is your rclone version (eg output from `rclone -V`)
v1.35
> Which OS you are using and how many bits (eg Windows 7, 64 bit)
QNAP QTS 4.2.2 witk kernel 3.19.8
> Which cloud storage system are you using? (eg Google Drive)
Amazon Cloud
> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone sync /share/CACHEDEV1_DATA/Data/Folder/ AmazonCloud:/Data/Folder/ -v
> A log from the command with the `-v` flag (eg output from `rclone -v copy /tmp remote:tmp`)
2017/02/06 11:45:50 pacer: Rate limited, sleeping for 841.778805ms (1 consecutive low level retries)
2017/02/06 11:45:50 pacer: low level retry 1/1 (error HTTP code 429: "429 Too Many Requests": response body: "{\"logref\":\"6a02c6ae-ec59-11e6-8d6c-1548436a0e11\",\"message\":\"Rate exceeded\",\"code\":\"\"}")
2017/02/06 11:45:50 potree16/data/r/203222/r2032221117.bin.gz: Received error: HTTP code 429: "429 Too Many Requests": response body: "{\"logref\":\"6a02c6ae-ec59-11e6-8d6c-1548436a0e11\",\"message\":\"Rate exceeded\",\"code\":\"\"}" - low level retry 1/10
2017/02/06 11:45:50 pacer: Resetting sleep to minimum 20ms on success

I suppose Amazon Cloud has some limitations, but which? data transfer, concurrent upload, max file per second? is there someone that have a working script?
thanks

**Comment by mmiat** [comment]
maybe this is a duplicate of https://github.com/ncw/rclone/issues/1099

**Comment by mmiat** [comment]
here
https://forum.rclone.org/t/not-deleting-as-copy-failed-failed-to-open-source-object/147
they speak about --acd-upload-wait-time=TIME and --acd-upload-wait-limit=TIME parameters, that I can't see if I launch rclone 
are there still active? maybe they are old parameters? they can be useful for my problem?
thanks

**Comment by ajkis** [comment]
Those are old flags now you have universal new flag 
`--acd-upload-wait-per-gb duration   Additional time per GB to wait after a failed complete upload to see if it appears. (default 3m0s)`

**Comment by mmiat** [comment]
ok thanks

but I've many of these errors:

> 2017/02/07 09:04:01 potree16/data/r/666620/274713/r666620274713744.bin.gz: Error detected after finished upload - waiting to see if object was uploaded correctly: HTTP code 429: "429 Too Many Requests": response body: "{\"logref\":\"fbdda9ea-ed0b-11e6-b6d5-55883d685ff9\",\"message\":\"Rate exceeded\",\"code\":\"\"}" ("429 Too Many Requests")
2017/02/07 09:04:01 potree16/data/r/666620/274713/r666620274713744.bin.gz: Object not found - waiting (1/1)
2017/02/07 09:04:06 potree16/data/r/666620/274713/r666620274713744.bin.gz: Giving up waiting for object - returning original error: HTTP code 429: "429 Too Many Requests": response body: "{\"logref\":\"fbdda9ea-ed0b-11e6-b6d5-55883d685ff9\",\"message\":\"Rate exceeded\",\"code\":\"\"}" ("429 Too Many Requests")
2017/02/07 09:04:06 pacer: Rate limited, sleeping for 627.942564ms (1 consecutive low level retries)
2017/02/07 09:04:06 pacer: low level retry 1/1 (error HTTP code 429: "429 Too Many Requests": response body: "{\"logref\":\"fbdda9ea-ed0b-11e6-b6d5-55883d685ff9\",\"message\":\"Rate exceeded\",\"code\":\"\"}")
2017/02/07 09:04:06 potree16/data/r/666620/274713/r666620274713744.bin.gz: Received error: HTTP code 429: "429 Too Many Requests": response body: "{\"logref\":\"fbdda9ea-ed0b-11e6-b6d5-55883d685ff9\",\"message\":\"Rate exceeded\",\"code\":\"\"}" - low level retry 1/10
2017/02/07 09:04:06 pacer: Resetting sleep to minimum 20ms on success

I can't understand the problem.... I've uploaded 2GB in 20 hours....

**Comment by mmiat** [comment]
now I'm trying with BackBlaze and I'm uploading at 17Mbit/s !

**Comment by seuffert** [comment]
had this for about an hour or two yesterday. disappeared later. might just have been something on amazons side

**Comment by mmiat** [comment]
the problem is still here.... I've uploaded 100GB in a day, and then 10GB in 2 days....

**Comment by ncw** [comment]
I don't think there is a problem with rclone, I think it is amazon being unreliable...

Keep trying and it should come good in the end.

**Comment by mmiat** [comment]
yesterday evening at 23:39 I've finished upload. this morning I've launch a new one and now it's uploading at 17Mbit/s (and I've set  --checkers 2 --transfers 2 --bwlimit 2M)

I'll update about this issue as soon as possible

**Comment by mmiat** [comment]
today with "--checkers 3 --transfers 3 --bwlimit 3M" I'm uploading at 25Mbit/s

**Comment by mmiat** [comment]
yesterday I've tried to upload without parameters, and immediately I've received error "429 Too Many Requests"
so I rewrite my script with "--checkers 6 --transfers 6 --bwlimit 6M" and now I'm uploading at 50Mbit/s

**Comment by jdrydn** [comment]
Based on [this Reddit thread](https://www.reddit.com/r/PlexACD/comments/6bto4y/acd_429_too_many_requests/) and [this rclone forum thread](https://forum.rclone.org/t/acd-429-too-many-requests/1792/238) I think all the traffic from acd_cli has moved to rclone and Amazon will be rate limiting the application key 🤦‍♂️. Which would be fine if we could just generate our own keys, but they've locked down that process 😩

**Comment by jdrydn** [comment]
@mmiat Are you using Backblaze with `rclone` and `rclone mount`? What's that like in terms of performance? I'm considering migrating (somehow, if I can't use `rclone`..) from ACD to B2, which'll cost me roughly the same, if not more for the data transfer per day based on usage.

**Comment by mmiat** [comment]
not I'm not, but I've done a try
it was good, but I don't remember details
however, you can try with a free account if I remember right (10GB)

**Comment by andronat** [comment]
I have the same issue `error HTTP code 429: "429 Too Many Requests"`. Can't upload anything to ACD.

**Comment by mbarbeaux** [comment]
Same here since yesterday

**Comment by Neo00724** [comment]
same here.... can't mount my encrypted drive...

**Comment by iisaphd** [comment]
Same for me over the past 24 hours. I also have acd_cli installed and get the following error trying to mount the amazon drive which points to an Amazon issue: 

<body text=#000000 bgcolor=#ffffff>
<table border=0 cellpadding=2 cellspacing=0 width=100%>
<tr><td bgcolor=#3366cc><font face=arial,sans-serif color=#ffffff><b>Error</b></td></tr>
<tr><td>&nbsp;</td></tr></table>
<blockquote>
<H1>Over Quota</H1>
This application is temporarily over its serving quota.  Please try again later.

**Comment by m4vr0x** [comment]
Same here on amazon.fr from two different servers

**Comment by tophee** [comment]
I am also seeing ` Failed to copy: failed to open source object: HTTP code 429: "429 Too Many Requests": response body: "{}"` with ACD. I don't understand much of how all of this works, but I thought I'd mention that duplicati seems to have solved the issue here:
https://github.com/duplicati/duplicati/issues/2129

**Comment by jdrydn** [comment]
@ncw Perhaps close this thread with a final message, unless ACD has changed in any way since May (AFAIK not at all)?

**Comment by ncw** [comment]
@tophee the 429 errors are a normal part of rate limiting with ACD.  Rclone should retry stuff where it can but if it gets too many errors - see `--low-level-retries` then it will fail out.

There isn't anything I can do to fix these errors unfortunately, so I'm going to close the issue now.
