### ISSUE TITLE
Win32 ignore filter in exclude-from

### ISSUE THREAD

**Issue by naeloob** [ncw/rclone#1107]
When filing an issue, please include the following information if possible as well as a description of the problem.  Make sure you test with the [latest beta of rclone](http://rclone.org/downloads/).

If you've just got a question then please use the [rclone forum](https://forum.rclone.org/) instead of filing an issue.

> What is your rclone version (eg output from `rclone -V`)

Rclone 1.35

> Which OS you are using and how many bits (eg Windows 7, 64 bit)

Win7 32 Bits

> Which cloud storage system are you using? (eg Google Drive)

gDrive

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

rclone.exe copy "C:/" RemoteCrypt:"/BackupC_170202/" --log-file BackupC_170202.log --verbose --exclude BackupC_170202.log --exclude-from Exclude.txt --transfers 8 --checkers 16

> A log from the command with the `-v` flag (eg output from `rclone -v copy /tmp remote:tmp`)

2017/02/06 11:24:46 ProgramData/Microsoft/Windows Defender/IMpService925A3ACA-C353-458A-AC8D-A7E5EB378092.lock: Failed to copy: failed to open source object: open \\?\C:\ProgramData\Microsoft\Windows Defender\IMpService925A3ACA-C353-458A-AC8D-A7E5EB378092.lock: The process cannot access the file because it's open by another process.

I have an exclude file called Exclude.txt with this exclude line : 
"Windows Defender/*.lock"

Thats the regex used : 

```
rclone --exclude "Windows Defender/*.lock" --dump-filters
--- start filters ---
--- File filter rules ---
- (^|/)Windows Defender/[^/]*\.lock$
--- Directory filter rules ---
--- end filters ---
```

It's so simple filter rule that i think the rule is right.
It could be a problem with  "LONGNAMES" pathnames?

Regards

**Comment by ncw** [comment]
The .lock file isn't directly in the "Windows Defender" directory, so you need this I think

    Windows Defender/**/*.lock

**Comment by naeloob** [comment]
Yes, It's at "Windows Defender" level.
That's on the error log : 
C:\ProgramData\Microsoft\Windows Defender\IMpService925A3ACA-C353-458A-AC8D-A7E5EB378092.lock

**Comment by ncw** [comment]
Sorry, my eyes deceived me there - you are right!

What happens if you do this - does it list the lock file? (Send the output to a file and search the file.)

    rclone --exclude "Windows Defender/*.lock" ls "C:/"

Can you paste the contents of your `Exclude.txt` and also what happens when you do

    rclone --exclude-from Exclude.txt --dump-filters

**Comment by naeloob** [comment]
The lock file does not appear listed on rclone --exclude "Windows Defender/*.lock" ls "C:/"

Exclude.txt
`pagefile.sys
hiberfil.sys
"/System Volume Information/**"
/Windows/**
/$Recycle.Bin/**
"Windows Defender Advanced Threat Protection/**"
/ProgramData/USOShared/**
/Boot/**
swapfile.sys
ntuser.dat
ntuser.dat.*
UsrClass.dat
UsrClass.dat.*
/ProgramData/Microsoft/Diagnosis/**
/ProgramData/Microsoft/Crypto/**
/ProgramData/Microsoft/Search/**
"/ProgramData/Microsoft/Microsoft Antimalware/**" 
/ProgramData/Microsoft/Windows/LfSvc/**
/ProgramData/Microsoft/Search/**
AppData/Local/Comms/**
"AppData/Local/Google/Chrome/User Data/ShaderCache/**" 
"AppData/Local/Google/Chrome/User Data/Default/Cache/**"
"AppData/Local/Google/Chrome/User Data/Default/Current Session"
"AppData/Local/Google/Chrome/User Data/Default/Current Tabs"
"AppData/Local/Google/Chrome/User Data/lockfile"
AppData/Local/Temp/**
AppData/Local/Microsoft/Windows/**
AppData/Local/TileDataLayer/**
AppData/Local/Microsoft/Internet Explorer/Recovery/**
/Program Files/Trend Micro/OfficeScan Client/**
"Windows Defender/*.lock"
"Windows Defender/Scans/**"`

rclone --exclude-from Exclude.txt --dump-filters
`--- start filters ---
--- File filter rules ---
- (^|/)pagefile\.sys$
- (^|/)hiberfil\.sys$
- (^|/)"/System Volume Information/.*"$
- ^Windows/.*$
- ^\$Recycle\.Bin/.*$
- (^|/)"Windows Defender Advanced Threat Protection/.*"$
- ^ProgramData/USOShared/.*$
- ^Boot/.*$
- (^|/)swapfile\.sys$
- (^|/)ntuser\.dat$
- (^|/)ntuser\.dat\.[^/]*$
- (^|/)UsrClass\.dat$
- (^|/)UsrClass\.dat\.[^/]*$
- ^ProgramData/Microsoft/Diagnosis/.*$
- ^ProgramData/Microsoft/Crypto/.*$
- ^ProgramData/Microsoft/Search/.*$
- (^|/)"/ProgramData/Microsoft/Microsoft Antimalware/.*"$
- ^ProgramData/Microsoft/Windows/LfSvc/.*$
- (^|/)AppData/Local/Comms/.*$
- (^|/)"AppData/Local/Google/Chrome/User Data/ShaderCache/.*"$
- (^|/)"AppData/Local/Google/Chrome/User Data/Default/Cache/.*"$
- (^|/)"AppData/Local/Google/Chrome/User Data/Default/Current Session"$
- (^|/)"AppData/Local/Google/Chrome/User Data/Default/Current Tabs"$
- (^|/)"AppData/Local/Google/Chrome/User Data/lockfile"$
- (^|/)AppData/Local/Temp/.*$
- (^|/)AppData/Local/Microsoft/Windows/.*$
- (^|/)AppData/Local/TileDataLayer/.*$
- (^|/)AppData/Local/Microsoft/Internet Explorer/Recovery/.*$
- ^Program Files/Trend Micro/OfficeScan Client/.*$
- (^|/)"Windows Defender/[^/]*\.lock"$
- (^|/)"Windows Defender/Scans/.*"$
--- Directory filter rules ---
- ^Windows/.*$
- ^\$Recycle\.Bin/.*$
- ^ProgramData/USOShared/.*$
- ^Boot/.*$
- ^ProgramData/Microsoft/Diagnosis/.*$
- ^ProgramData/Microsoft/Crypto/.*$
- ^ProgramData/Microsoft/Search/.*$
- ^ProgramData/Microsoft/Windows/LfSvc/.*$
- (^|/)AppData/Local/Comms/.*$
- (^|/)AppData/Local/Temp/.*$
- (^|/)AppData/Local/Microsoft/Windows/.*$
- (^|/)AppData/Local/TileDataLayer/.*$
- (^|/)AppData/Local/Microsoft/Internet Explorer/Recovery/.*$
- ^Program Files/Trend Micro/OfficeScan Client/.*$
--- end filters ---`

**Comment by ncw** [comment]
I see the problem

In your exclude file you don't want the "quotes" around

    "Windows Defender/*.lock"

You want

    Windows Defender/*.lock

You should remove all the " from that file.

**Comment by naeloob** [comment]
I think i tried too without ", but i make so many test that i cannot know.

I wil try again without " and i will tell you if it fails.

Thank you!!

**Comment by naeloob** [comment]
That was the problem... It must be without Quotes "

Thank You very much.
