### ISSUE TITLE
Log verbose output to seperate file

### ISSUE THREAD

**Issue by AzureBlaze** [ncw/rclone#1108]
I usually use the --log-file option in rclone and follow the progress with tail -f but when I turn on verbose output it can make it hard to keep track of transfer progress, if there was an --verbose-log-file option to log all verbose output to a seperate file it would make it possible to easily keep track of transfers and keep track of errors on the backend.

**Comment by ncw** [comment]
What would you think if I put an easy to grep INFO, DEBUG, TRANSFER in the log - would that be enough?

**Comment by AzureBlaze** [comment]
Actually that's a much better idea, that way it doesn't need to be specified when initially running the command.

**Comment by ncw** [comment]
Great!  I'm planning on re-vamping the logging for 1.36 and I'll put that in.

**Comment by ncw** [comment]
I have reworked the logging - please have a go with it in this beta

http://beta.rclone.org/v1.35-87-g006227b/ (uploaded in 15-30 mins)

Here are the bits from the docs

## Logging ##

rclone has 4 levels of logging, `Error`, `Notice`, `Info` and `Debug`.

By default rclone logs to standard error.  This means you can redirect
standard error and still see the normal output of rclone commands (eg
`rclone ls`).

By default rclone will produce `Error` and `Notice` level messages.

If you use the `-q` flag, rclone will only produce `Error` messages.

If you use the `-v` flag, rclone will produce `Error`, `Notice` and
`Info` messages.

If you use the `-vv` flag, rclone will produce `Error`, `Notice`,
`Info` and `Debug` messages.

You can also control the log levels with the `--log-level` flag.

If you use the `--log-file=FILE` option, rclone will redirect `Error`,
`Info` and `Debug` messages along with standard error to FILE.

If you use the `--syslog` flag then rclone will log to syslog and the
`--syslog-facility` control which facility it uses.

Rclone prefixes all log messages with their level in capitals, eg INFO
which makes it easy to grep the log file for different kinds of
information.

**Comment by ncw** [comment]
I messed up with that beta - try this one instead http://beta.rclone.org/v1.35-92-g18c75a8/ (uploaded in 15-30 mins)

**Comment by AzureBlaze** [comment]
I tested it out and it works as expcted

**Comment by AzureBlaze** [comment]
I can't help but think that the Info should be included by default, that's the most important part of the log for me, I generally only enable the more verbose options for debugging but the info is needed to keep track of progress.

**Comment by ncw** [comment]
@AzureBlaze I'm taking my lead from rsync here which prints almost nothing unless you pass `-v`.  Now `-v` will just print useful stuff!

**Comment by AzureBlaze** [comment]
I see, I've never actually used rsync before, but in any case it's hardly an issue now that defaults can be set in the enviroment.

**Comment by ljr9600** [comment]
Any chance that we can APPEND to the log file, rather than clobber it and recreate it each time?  I like to log all my transfers, and if I forgot to change the log file name, it gets wiped.  Could the default be APPEND?  (ask around and see what people want).

**Comment by ncw** [comment]
@ljr9600 that sounds like a good idea can you please make a [new issue on github](https://github.com/ncw/rclone/issues/new) about it.
