### ISSUE TITLE
[ACD][mount] - mount breaks on too many open connections

### ISSUE THREAD

**Issue by rwenz3l** [ncw/rclone#1111]
> What is your rclone version (eg output from `rclone -V`)
rclone v1.35

> Which OS you are using and how many bits (eg Windows 7, 64 bit)
Linux (ubuntu 16.04 LTS, 64bit)

> Which cloud storage system are you using? (eg Google Drive)
Amazon CloudDrive

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

`rclone mount acd:/ /mnt/acd/ --allow-non-empty --allow-other --dir-cache-time 3m --max-read-ahead 1G --acd-templink-threshold 0 --bwlimit 0 --checkers 32 --contimeout 15s --low-level-retries 1 --no-check-certificate --retries 3 --timeout 30s --transfers 32 --no-modtime &`

> A log from the command with the `-v` flag (eg output from `rclone -v copy /tmp remote:tmp`)

`Get https://cdws.eu-west-1.amazonaws.com/drive/v1/nodes?filters=parents%3AyM8ImUfGTsmNBhBugdl3Ig: Post https://api.amazon.com/auth/o2/token: dial tcp: lookup api.amazon.com on 62.210.16.7:53: dial udp 62.210.16.7:53: socket: too many open files`

**Comment by Coornail** [comment]
You should probably raise your maximum open files settings in ulimit.
For example: `ulimit -n 9000`

**Comment by ncw** [comment]
The ulimit suggestion by @Coornail sounds like the right one, unless `rclone mount` has a file descriptor leak.

How many open files are there at once?

What happens if you use `lsof` on the rclone mount process - do you see the number of file descriptors continuously rising?

It is possible that the application you are using isn't closing its files properly also - you can check that with lsof too.

**Comment by rwenz3l** [comment]
Ok, Let's check on the current open files
`lsof | grep "rclone" | wc -l`
returns 6458

Now, Check on current ulimit
`ulimit -n`
returns 1024

Set that to 9000 and Check again
`ulimit -n 9000 && ulimit -n`
returns 9000

looks good so far, now check if any app is not closing files properly:

`lsof | grep "rclone" | grep -i "close"`
returns :
```
rclone    32495            lugia  421u     IPv4           27339327        0t0                  TCP 51-15-0-251.rev.poneytelecom.eu:43382->ec2-52-48-13-92.eu-west-1.compute.amazonaws.com:https (CLOSE_WAIT)
rclone    32495  9414      lugia  421u     IPv4           27339327        0t0                  TCP 51-15-0-251.rev.poneytelecom.eu:43382->ec2-52-48-13-92.eu-west-1.compute.amazonaws.com:https (CLOSE_WAIT)
rclone    32495 32496      lugia  421u     IPv4           27339327        0t0                  TCP 51-15-0-251.rev.poneytelecom.eu:43382->ec2-52-48-13-92.eu-west-1.compute.amazonaws.com:https (CLOSE_WAIT)
rclone    32495 32497      lugia  421u     IPv4           27339327        0t0                  TCP 51-15-0-251.rev.poneytelecom.eu:43382->ec2-52-48-13-92.eu-west-1.compute.amazonaws.com:https (CLOSE_WAIT)
rclone    32495 32498      lugia  421u     IPv4           27339327        0t0                  TCP 51-15-0-251.rev.poneytelecom.eu:43382->ec2-52-48-13-92.eu-west-1.compute.amazonaws.com:https (CLOSE_WAIT)
rclone    32495 32499      lugia  421u     IPv4           27339327        0t0                  TCP 51-15-0-251.rev.poneytelecom.eu:43382->ec2-52-48-13-92.eu-west-1.compute.amazonaws.com:https (CLOSE_WAIT)
rclone    32495 32500      lugia  421u     IPv4           27339327        0t0                  TCP 51-15-0-251.rev.poneytelecom.eu:43382->ec2-52-48-13-92.eu-west-1.compute.amazonaws.com:https (CLOSE_WAIT)
rclone    32495 32501      lugia  421u     IPv4           27339327        0t0                  TCP 51-15-0-251.rev.poneytelecom.eu:43382->ec2-52-48-13-92.eu-west-1.compute.amazonaws.com:https (CLOSE_WAIT)
rclone    32495 32502      lugia  421u     IPv4           27339327        0t0                  TCP 51-15-0-251.rev.poneytelecom.eu:43382->ec2-52-48-13-92.eu-west-1.compute.amazonaws.com:https (CLOSE_WAIT)
rclone    32495 32515      lugia  421u     IPv4           27339327        0t0                  TCP 51-15-0-251.rev.poneytelecom.eu:43382->ec2-52-48-13-92.eu-west-1.compute.amazonaws.com:https (CLOSE_WAIT)
rclone    32495 32516      lugia  421u     IPv4           27339327        0t0                  TCP 51-15-0-251.rev.poneytelecom.eu:43382->ec2-52-48-13-92.eu-west-1.compute.amazonaws.com:https (CLOSE_WAIT)
rclone    32495 32517      lugia  421u     IPv4           27339327        0t0                  TCP 51-15-0-251.rev.poneytelecom.eu:43382->ec2-52-48-13-92.eu-west-1.compute.amazonaws.com:https (CLOSE_WAIT)
rclone    32495 32518      lugia  421u     IPv4           27339327        0t0                  TCP 51-15-0-251.rev.poneytelecom.eu:43382->ec2-52-48-13-92.eu-west-1.compute.amazonaws.com:https (CLOSE_WAIT)
rclone    32495 32519      lugia  421u     IPv4           27339327        0t0                  TCP 51-15-0-251.rev.poneytelecom.eu:43382->ec2-52-48-13-92.eu-west-1.compute.amazonaws.com:https (CLOSE_WAIT)
rclone    32495 32572      lugia  421u     IPv4           27339327        0t0                  TCP 51-15-0-251.rev.poneytelecom.eu:43382->ec2-52-48-13-92.eu-west-1.compute.amazonaws.com:https (CLOSE_WAIT)
```

as well as: 
`lsof | grep "rclone" | grep -i "close" | wc -l`
returns 15

Wait a minute to let files close?
Check again:
`lsof | grep "rclone" | grep -i "close"`
returns nothing

as well as:
`lsof | grep "rclone" | grep -i "close" | wc -l`
returns 0

That seems to be ok.

Also for future use:
To make the ulimit more persistent you can either edit /etc/security/limits.conf
and add : `*               soft    nofile          9000` + rebootz

**or** write it into your user's .bashrc

**Thanks to @Coornail and @ncw - I'll close this for now and observe what happens.**

**Comment by ncw** [comment]
Cross fingers! :-)

**Comment by kuraga** [comment]
rclone 1.36, the same issue

**Comment by kuraga** [comment]
rclone 1.36, the same issue on sync
