### ISSUE TITLE
Latest rclone beta doesn't expand enviroment variables

### ISSUE THREAD

**Issue by AzureBlaze** [ncw/rclone#1112]
> What is your rclone version (eg output from `rclone -V`)

rclone v1.35-77-gc0ad29cβ

> Which OS you are using and how many bits (eg Windows 7, 64 bit)

Windows 10 64 bit

 In the latest beta rclone on windows won't expand on variables contained in the environment.
For example my config path is set in the enviroment as %HOMEDRIVE%%HOMEPATH%\Documents\rclone.conf

In the latest beta if I run any command I get 
`* Config file "%HOMEDRIVE%%HOMEPATH%\\Documents\\rclone.conf" not found - using defaults`
and running rclone help also shows 

`--config string                     Config file. (default "%HOMEDRIVE%%HOMEPATH%\Documents\rclone.conf")`

but in an earlier build `rclone v1.35-62-g9d331ceβ` it resolves properly to
` --config string                     Config file. (default "C:\Users\*REDACTED*\Documents\rclone.conf")`
`

**Comment by ncw** [comment]
This is probably a consequence of 9d362589233e50f9ca8befd3e9ef7f01b08e408b

@kynikos - fancy taking a look at this?

**Comment by kynikos** [comment]
Hmm... can you try to apply kynikos@9c25d09 and see if it fixes the problem? I don't even have an easy way to test on Windows at the moment ^^

**Comment by ncw** [comment]
@AzureBlaze how did you set the environment variable?  I can't seem to set it without it being immediately expanded! Eg

```
X:\go\src\github.com\ncw\rclone>set RCLONE_CONFIG=%HOMEPATH%\Documents\rclone.co
nf

X:\go\src\github.com\ncw\rclone>set
[snip]
RCLONE_CONFIG=\Users\Dev\Documents\rclone.conf
[snip]
```

I'll try your patch @kynikos when I've worked that out.

**Comment by AzureBlaze** [comment]
@ncw I tried out the latest beta v1.35-79-g50e190f (I assume that contains the patch) and the path now correctly expands. Also RCLONE_CONFIG expanded properly in both cmd (set) and powershell ($env:RCLONE_CONFIG) for me as well it just didn't expand in the rclone v1.35-77-gc0ad29c build but its working fine now.

**Comment by ncw** [comment]
OK - that is strange! That version doesn't contain the patch.  As far as I can see the difference between 77 and 79 shouldn't affect that code at all.

**Comment by AzureBlaze** [comment]
@ncw that's strange I checked to make sure it was the versions by running `.\rclone.exe version;.\rclone.exe listremotes`  for both versions and it works for both now, so I suspect it may have been a combination of my Windows version and rclone version since I'm running the insider builds and updated today.

**Comment by ncw** [comment]
OK.  I'll close this for the moment - please re-open if you get this problem again and can reproduce it reliably.

Thanks

Nick
