### ISSUE TITLE
Unable to refresh Backblaze B2 auth token

### ISSUE THREAD

**Issue by ThomasMoller** [ncw/rclone#1118]
When reaching 24 hours of runtime rclone failed to re-auth the Backblaze B2 auth token. It seems that it retries, but fails.

After restaring rclone it was able to auth again.

> What is your rclone version (eg output from `rclone -V`)

rclone v1.35

> Which OS you are using and how many bits (eg Windows 7, 64 bit)

Linux 3.10.77 #8451 SMP Wed Jan 4 00:30:12 CST 2017 armv7l GNU/Linux synology_armada38x_ds416j
(Synology diskstation with 32 bit arm processor)

> Which cloud storage system are you using? (eg Google Drive)

Backblaze B2

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

rclone sync /volumeUSB1/usbshare/ b2:name-of-bucket --log-file /var/log/rclone.log

> A log from the command with the `-v` flag (eg output from `rclone -v copy /tmp remote:tmp`)
```
Transferred:   116.733 GBytes (1.383 MBytes/s)
Errors:                 0
Checks:                 0
Transferred:         8612
Elapsed time:     24h0m1s
Transferring:

2017/02/11 00:04:48 B2 bucket xxx-xxx-xxx-xxx: Unauthorized: Authorization token has expired (401 expired_auth_token)
2017/02/11 00:04:50 Path/to/file: Clearing upload URL because of error: Authorization token has expired (401 expired_auth_token)
2017/02/11 00:04:50 pacer: Rate limited, increasing sleep to 20ms
2017/02/11 00:04:50 pacer: low level retry 1/1 (error Authorization token has expired (401 expired_auth_token))
2017/02/11 00:04:50 Path/to/file: Received error: Authorization token has expired (401 expired_auth_token) - low level retry 1/10

```

Thanks for an awesome tool! Your work is much appreciated.

**Comment by ncw** [comment]
I've fixed this already - try the latest beta :-)

See #825

The fix will be in the 1.36 release
