### ISSUE TITLE
Ubuntu snap created for rclone

### ISSUE THREAD

**Issue by Dedsec1** [ncw/rclone#1120]
Hi ncw

i wanted to make it easier for people to install rclone on different types of Linux distros, so i went ahead and setup an Ubuntu snap for rclone. you can install rclone by doing the following command listed below. luckily snaps can be deployed on other distro's as well such as Redhat, CentOS, Debian etc. currently i have my launchpad account pulling from my fork automatically using git and building an new snap each time an change is  detected. so you could add my snapcraft.yaml file to the main repo for rclone, then you could  update the version in the file when an new version is pushed out.  then i can have launchpad pointed at the main repo for rclone if you would like.

https://github.com/Dedsec1/rclone/

https://github.com/Dedsec1/rclone/blob/master/snapcraft.yaml

sudo snap install rclone --classic

Regards

Dedsec1

**Comment by ncw** [comment]
That looks great!

Do you think you could send a pull request with

  * the snapcraft.yml
  * some updates to the docs (you only need to edit docs in `docs/content` the others are auto generated) describing how to configure snap and install rclone

Then I can integrate the changes :-)

Thanks

Nick

**Comment by Dedsec1** [comment]
docs has been created https://github.com/Dedsec1/rclone/blob/master/docs/content/rclone%20snap.md

**Comment by ncw** [comment]
I've merged your PR now thank you!

I've got some questions about it though...

Are you willing to maintain the snap going forwards?  If so I'd like to put some details for you in the install.md (or you could send a PR).

Can you point your builder towards the official rclone source now?

Is the snap builder checking out a release or is it just using the latest commit?

And do I need to update the version number in the snapcraft file when I make new releases? I presume so...

**Comment by Dedsec1** [comment]
sure thing, i dont mind maintain the snap going forward, the only thing i have to do is change the version number in the yaml file each time. i already pointed the auto builder for your git repo so Ubuntus servers will do the rest when it comes to building.

**Comment by ncw** [comment]
Great.  Can you give me a URL to point to the builder for the docs?

**Comment by Dedsec1** [comment]
here is the repo i created on my launchpad account, https://launchpad.net/~deathero291/+snap/rclone
as of right now i have it setup to pull any changes from your repo every few hours.

**Comment by ncw** [comment]
I can't merge this as it stands.  What you need to do is reset your master branch back to origin/master, then make a feature branch with this change it.

I'd really like it to pull the current stable version, so it should use the git tag of that version number.

And we should make a separate rclone-dev to install the development version.

Is that possible?

**Comment by joewashear007** [comment]
This is a great idea! I tried using it and seems to be working fine. Though I think it needs more permissions. I am using it on a raspberry pi, so obviously my storage is external. To access it, rclone needs to access the `removable-media` plug. 

Also, you might want to try the `fuse-support` to see if you can get `mount` working.

Thanks!

**Comment by ncw** [comment]
@Dedsec1 any chance you could look at @joewashear007 s comments?  I think fixing them would probably fix #1188

**Comment by Dedsec1** [comment]
i will have to look into this since fuse might have different deps that it needs to run. but it should be possible

**Comment by jnederhoff** [comment]
I'm new to snapd, so correct me if I am wrong here.

In the documentation it says to install rclone in classic mode, which I believe means rclone will not be sandboxed to its snap directories on the filesystem.  However, in snapcraft.yaml the confinement mode is strict.  Thus, when I try to access files outside of the snap sandbox, or my home directory, access is denied.

I think one of two things should change:

1. The documentation should be updated to reflect the filesystem limitations of snaps.
2. snapcraft.yaml should be updated to classic confinement

Which is the best choice I am not sure.

**Comment by ncw** [comment]
@Dedsec1 do you have an opinion on this?

**Comment by tuapuikia** [comment]
Regarding the sandbox file system, you can use mount --rbind <remove directory> /home/<user>/directory. I maintain few snap myself but setting classic confinement are very risky and most of the time it won't get approve.

**Comment by ncw** [comment]
I'm going to close this for the moment as a snap is created.

However I would much appreciate PR to update the snap or the docs.

**Comment by Dedsec1** [comment]
sure thing nick, i will update it today

**Comment by lunarthegrey** [comment]
Is the snap dead? It seems it's at version 1.36 and latest is 1.40 :(

**Comment by ncw** [comment]
We've stopped releasing rclone with snap as it became to hard to make it work especially with rclone mount.  If you look at the rclone.org/downloads page you'll see there are lots of convenient way of installing rclone nowadays.

**Comment by lunarthegrey** [comment]
Darn I really wanted a way I could install it safely and have it confined in a snap.
