### ISSUE TITLE
Corrupted config file

### ISSUE THREAD

**Issue by PiscisSwimeatus** [ncw/rclone#1122]
> What is your rclone version (eg output from `rclone -V`)
rclone-v1.35-75-g381b845β-windows-amd64
> Which OS you are using and how many bits (eg Windows 7, 64 bit)
Windows Server 2016 Standard with desktop
> Which cloud storage system are you using? (eg Google Drive)
Amazon Cloud Drive
> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone move --checksum
> A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

**Comment by PiscisSwimeatus** [comment]
Config:
`
[CryptUS1]
type = crypt
remote = AmazonUS1:/Crypt/
filename_encryption = standard
password = REMOVED
password2 = REMOVED

[CryptUS2]
type = crypt
remote = AmazonUS2:/Crypt/
filename_encryption = standard
password = REMOVED
password2 = REMOVED

[CryptDE1]
type = crypt
remote = AmazonDE1:/Crypt/
filename_encryption = standard
password = REMOVED
password2 = REMOVED

[CryptUK1]
type = crypt
remote = AmazonUK1:/Crypt/
filename_encryption = standard
password = REMOVED
password2 = REMOVED

[AmazonUS1]
type = amazon cloud drive
client_id = 
client_secret = 
token = {"access_token":"Atza|REMOVED","token_type":"bearer","refresh_token":"Atzr|REMOVED","expiry":"2017-02-12T09:52:28.2484507+01:00"}

[AmazonUS2]
type = amazon cloud drive
client_id = 
client_secret = 
token = {"access_token":"Atza|REMOVED","token_type":"bearer","refresh_token":"Atzr|REMOVED","expiry":"2017-01-14T12:54:49.2835129+01:00"}

[AmazonDE1]
type = amazon cloud drive
client_id = 
client_secret = 
token = {"access_token":"Atza|REMOVED","token_type":"bearer","refresh_token":"Atzr|REMOVED","expiry":"2017-02-07T11:14:18.3836249+01:00"}

[AmazonUK1]
type = amazon cloud drive
client_id = 
client_secret = 
token = {"access_token":"Atza|REMOVED","token_type":"bearer","refresh_token":"Atzr|REMOVED","expiry":"2017-02-07T11:14:57.5827282+01:00"}
7.5827282+01 = 00"}
`

**Comment by PiscisSwimeatus** [comment]
Issue happened arround 08:52, line ~48800

[rclone.txt](https://github.com/ncw/rclone/files/769178/rclone.txt)

**Comment by ncw** [comment]
What does the corruption look like - is it just the config file but mixed up (that is what I'm expecting)?

**Comment by PiscisSwimeatus** [comment]
This last line it the extra garbage:
7.5827282+01 = 00"}

**Comment by ncw** [comment]
@PiscisSwimeatus sorry I missed that.  Yes that looks like it was part of the config file.

**Comment by ncw** [comment]
I think this should be fixed by 9cede6b372002a739cca8d5db589c61c6d229bba so I'm going to close this - let me know if it re-occurs!
