### ISSUE TITLE
(Question) Hubic, auth via login password not authkey

### ISSUE THREAD

**Issue by ffloress** [ncw/rclone#1125]
Hello, I would like to auth hubic with username and password, instead of the api auth. Is this possible?

**Comment by ncw** [comment]
If you can somehow get the swift credentials for hubic, then you can just set up a swift remote with them and not use the oauth flow.  Is that what you mean?

**Comment by ffloress** [comment]
Yes.. I guess they wont provide swift credentials?

**Comment by ncw** [comment]
The way you get the swift credentials is to do the oauth bit, and use the API.

**Comment by ffloress** [comment]
Ok.
I see there is a refresh token too in .rclone.config generated on my remote raspberry pi.
Can i expect rclone to auto generate new access token (and update .rclone cofig file) when access token is due?

I expect this raspberry to keep uploading files to hubic, without interaction non-stop for months

**Comment by ffloress** [comment]
I guesa this is the way to get swift credentials, but rclone already does the same ?
https://github.com/puzzle1536/hubic-wrapper-to-swift/

**Comment by ncw** [comment]
Yes rclone will grab the token and refresh it when it expires so you only have to log in once.
