### ISSUE TITLE
Cross Building (MIPS related)

### ISSUE THREAD

**Issue by sbr481** [ncw/rclone#1128]
Hi, i've opened this issue, because i'm trying to make a cross build of rclone to MIPS arch (mips32 le), and i'm stuck.
Using latest beta of go lang, and the latest version of rclone git. 
I'm using perfectly the binary posted in this issue (1.34 version): https://github.com/ncw/rclone/issues/849
But i'd like to build the latest (and of course next builds). I' tried to make by different ways the cross build process:

- using go lang feature of cross building (settin GOOS and GOARCH env variables), i get a binary, but doesn't run in the MIPS machine (i get some different errors when i try to run, as bus error, illegal instruction... This error changes if i use a different -ldflag, -w, -s, or both).

- using gccgo with a toolchain, compiled also with success, and i get the binary running in the MIPS machine, but fails because it's dinamically linked, and there are some missing instructions by not static libraries. By the moment i don't know how to build with static linking (i'll continue the research). I can build perfectly i368 or amd64 binaries.

But i'd like to know what was used to compile (and the process) 1.34 version that i mention above, and maybe this help to know if i'm doing something bad, or it's related to my host OS, or something related.
I'd like to test fuse mount function with a Google Drive account. With 1.34 version, transfer rate is very slow (an average of 75 KB/s, 90 KB/s as max rate), and maybe with later releases it could be fine and useful.

Thanks in advice, and your efforts.  Any help will be appreciated.

**Comment by ncw** [comment]
I built those binaries using go tip (the latest beta should work though) with these commands.

    GOOS=linux GOARCH=mipsle go build

and 

    GOOS=linux GOARCH=mips go build

To build the two versions.

Attached is the result of this

```
 GOOS=linux GOARCH=mipsle go build
 mv rclone rclone-mipsle
 GOOS=linux GOARCH=mips go build
 mv rclone rclone-mips
 zip -9 rclone-v1.35-95-g5419292-mips.zip rclone-mipsle rclone-mips
```

[rclone-v1.35-95-g5419292-mips.zip](https://github.com/ncw/rclone/files/773747/rclone-v1.35-95-g5419292-mips.zip)

**Comment by sbr481** [comment]
Hi ncw,

I'm going to test your binaries right now. I know how to build, but i don't understand why don't run on my machine. I get the compilation perfectly, without errors, checked with file command to see output format.
Using Ubuntu 16.04 i386 and tested also in Ubuntu 16.10 amd64 (using virtual machines), but i don't think these aspects could be the problem... Using go 1.8rc3 (latest beta).
What's your OS host to make the cross building?

Thanks for answering and building the binaries. I'll tell you if them works (i can only test mips le version).

**Comment by ncw** [comment]
I'm using ubuntu 16.04 amd64 to build.

Try building it with this command on a single line

    GOOS=linux GOARCH=mipsle go build

That should work

**Comment by ncw** [comment]
I'm going to close this now as we build mips and mipsle builds by default now.
