### ISSUE TITLE
[Feature request] Crypt Decode from file 

### ISSUE THREAD

**Issue by ajkis** [ncw/rclone#1129]
When copying from local drive to crypt mount on ACD I see a lot of files appearing in Trash, most likely some unsuccessful uploads ( not sure ). 

It would be great if we could get option eg `rclone cryptdecode=file.txt` where we would get output of unencrypted file name.  The file.txt would contain encrypted names 1 per line.

Image of my trash after rclone move from local to crypt
http://puu.sh/u2IZ2/62213369b9.png

**Comment by ncw** [comment]
The command would need to take your crypt remote as a parameter, so it would need to be something like

    rclone cryptdecode crypteremote: filename1 filename2 filename3

Good idea!

**Comment by ishuah** [comment]
I think it would also be useful to have
`rclone cryptdecode cryptremote:` 
whose output is a list of the files with their encrypted names.

output sample:
```
file01.txt         dilbg9q6279jnu0ijjvqjs61d4
file02.txt         pbeg45u31rucld7im4736ol418 
subdir/file03.txt  0jm0g78djsffjnplhaa3n80mp4/t0or8gsk41hio1p51pto0ukp5c
subdir/file04.txt  0jm0g78djsffjnplhaa3n80mp4/dilbg9q6279jnu0ijjvqjs61d4
```

**Comment by ishuah** [comment]
Please find a beta with the fix in: https://beta.rclone.org/v1.38-093-gc65734ee/ (uploaded in 15-30 mins)
