### ISSUE TITLE
copyto creates an empty directory if remote src doesn't exist

### ISSUE THREAD

**Issue by hashbackup** [ncw/rclone#1131]
With Dropbox, rclone 1.35 copyto creates and leaves an empty directory if the remote src file doesn't exist:
```
[jim@mb ~]$ mkdir xyz
[jim@mb ~]$ rclone ls drop:
   905827 Get Started with Dropbox.pdf
[jim@mb ~]$ rclone -I -q --stats=0 --no-gzip-encoding copyto drop:test/DUMMY xyz/DUMMY.tmp
[jim@mb ~]$ echo $?
0
[jim@mb ~]$ ls -l xyz
total 0
drwxr-xr-x  2 jim  staff  68 Feb 14 11:57 DUMMY.tmp
```
There are a couple of issues here:
- no error was reported in the exit code for a src file that doesn't exist
- rclone assumed the thing being transferred was a directory and left one behind in the target

With Google Drive, the behavior is slightly different.  It still creates a directory on the target, but it does report the non-existing object error (different filename here, but same issue) an returns a non-zero exit status:
```
2017/02/14 11:52:52 Attempt 1/3 failed with 0 errors and: error listing source: Google drive root 'test2/DESTID': directory not found
2017/02/14 11:52:52 Attempt 2/3 failed with 0 errors and: error listing source: Google drive root 'test2/DESTID': directory not found
2017/02/14 11:52:52 Attempt 3/3 failed with 0 errors and: error listing source: Google drive root 'test2/DESTID': directory not found
2017/02/14 11:52:52 Failed to copyto: error listing source: Google drive root 'test2/DESTID': directory not found
```

**Comment by ncw** [comment]
Looks odd I agree!

**Comment by ncw** [comment]
> no error was reported in the exit code for a src file that doesn't exist

This is now fixed.

> rclone assumed the thing being transferred was a directory and left one behind in the target

The assumption that the thing being transferred was a directory is the way rclone works, however I've fixed the spurious directory creation in 
f88300a153a63a08abd026f20dc93da3b76cafc9
