### ISSUE TITLE
Socket: too many open files

### ISSUE THREAD

**Issue by Maxou44** [ncw/rclone#1132]
Thanks a lot for Rclone, it's just awesome for Plex and ACD !

I use rclone "v1.35-DEV" and last night, Rclone was planted, he filled me the logs of that:

ERROR : Plex/TVShows/XXXXXXXXXXXXX: Dir.Lookup error: Get https://cdws.eu-west-1.amazonaws.com/drive/v1/nodes?filters=parents%3AXXXXXXXXXXXXXXXXXX: dial tcp: lookup cdws.eu-west-1.amazonaws.com on 10.1.94.8:53: no such host

ERROR : Plex: Dir.Lookup error: Get https://cdws.eu-west-1.amazonaws.com/drive/v1/nodes?filters=parents%3AXXXXXXXXXXXXXXXXXX: Post https://api.amazon.com/auth/o2/token: dial tcp: lookup api.amazon.com on [::1]:53: dial udp [::1]:53: socket: too many open files

ERROR : Plex: Dir.Lookup error: Get https://cdws.eu-west-1.amazonaws.com/drive/v1/nodes?filters=parents%3AXXXXXXXXXXXXXXXXXX: Post https://api.amazon.com/auth/o2/token: dial tcp: lookup api.amazon.com on 10.1.94.8:53: dial udp 10.1.94.8:53: socket: too many open files

What does it mean ? Why after restarting my server everything work away without a problem?

**Comment by ncw** [comment]
Check out the ulimit suggestions in this issue #1111

**Comment by Maxou44** [comment]
Thank you for your reply, I close the issue and I test it :)
