### ISSUE TITLE
rclone 1.35 ls returns different exit codes for missing files

### ISSUE THREAD

**Issue by hashbackup** [ncw/rclone#1135]
HashBackup has a verify command that can be used to check that the remote storage service has the backup data it should have, and with rclone destinations, it uses the rclone ls command. 

rclone ls rem:file where file is missing on the remote:
- returns empty stdout and exit code 0 on Dropbox
- returns empty stdout, warning on stderr, and exit code 1 on Google drive
These are the only 2 remotes I tested.
```
[jim@mb ~]$ rclone ls drop:xyz
[jim@mb ~]$ echo $?
0
[jim@mb ~]$ rclone ls gdrive:xyz
2017/02/15 14:07:11 directory not found
[jim@mb ~]$ echo $?
1
[jim@mb ~]$ rclone ls gdrive:xyz >/dev/null
2017/02/15 14:07:32 directory not found
```
For HashBackup, it would be better if rclone returned a zero exit code if a file isn't there, so that it's possible to distinguish between "file not there" and "rclone had a problem".

**Comment by ncw** [comment]
I agree that this should be consistent - I suspect I've missed a test from the test suite so the remotes have differing behaviour.

**Comment by hashbackup** [comment]
To give a better idea why this is a problem, when trying to verify a file is on a remote, HashBackup will do rclone ls gdrive:filename.  When the file isn't there, stdout is null, stderr says "directory not found", and exit code is 1 (for Google Drive).  But if there's an error in the command, like the user adds --xyz to the command line (there's an option to do that), stdout is null, stderr has an error message, and the exit code is 1.  These responses look the same, so I can't determine whether a file is there or not.  It's probably not a good idea to look at stderr and try to figure out the difference: I don't know if rclone is internationalized or not, but that "directory not found" error could easily change in the future.   Thanks!

**Comment by ncw** [comment]
I think this is fixed now all the remotes I tried now product

```
$ rclone ls /tmp/potato ; echo $?
2018/01/11 14:04:41 ERROR : : error listing: directory not found
2018/01/11 14:04:41 Failed to ls: directory not found
3
```

**Comment by hashbackup** [comment]
Thanks for the fix.  Since the initial bug report, I've changed HashBackup to verify files using just one list command rather than file-by-file.  Way faster.
