### ISSUE TITLE
rclone size: report total space available and free as well as used

### ISSUE THREAD

**Issue by niranjanshr13** [ncw/rclone#1138]
Can you add the cloud storage space.
1. Total space(capacity) storage of the cloud service.
2. How much space has been taken already.
3. Available space.

**Comment by ncw** [comment]
This would require rclone to know the total storage of the remote which it doesn't at the moment.

You can do 2 with `rclone size remote:`

**Comment by niranjanshr13** [comment]
thanks didn't know that.

**Comment by ncw** [comment]
I'll re-open this so we can do this some time!

**Comment by ncw** [comment]
OK here is probably the final version of about before I merge it - comments appreciated!

https://beta.rclone.org/v1.40-089-gef3bcec7-about/ (uploaded in 15-30 mins)

See the docs here: https://github.com/ncw/rclone/blob/about/cmd/about/about.go#L44

This is supported for local, crypt, cache, drive, swift, hubic, onedrive, pcloud, dropbox

**Comment by TowerBR** [comment]
Nick, worked perfectly:

**Gdrive:**
```
Total:   30G
Used:    20M
Free:    28.440G
Trashed: 0
Other:   1.541G
```
**Dropbox:**
```
Total:   1.009T
Used:    398.448G
Free:    635.177G
```
**Onedrive:**
```
Total:   12G
Used:    89.062M
Free:    11.913G
Trashed: 0
```

Thanks for this feature!

**Comment by ncw** [comment]
rclone about is merged to master now:

https://beta.rclone.org/v1.40-090-g2b855751/ (uploaded in 15-30 mins)

Thank you for testing.
