### ISSUE TITLE
Verbose Log not working in latest commit?

### ISSUE THREAD

**Issue by Givemeyourgits** [ncw/rclone#1141]
Version: rclone v1.35-99-g6fc114dβ
Ubuntu 16.04 x64
Amazon Cloud Drive
rclone mount w/ --verbose & log-file

If I look at log, I get certain errors, but not getting any verbose output.  Not sure if timeouts are showing up, I only seem to be able to see low level errors.

**Comment by ajkis** [comment]
Are you using -vv flag (  flags changed )

**Comment by Givemeyourgits** [comment]
No, that would make sense.
Thanks!
