### ISSUE TITLE
Entering amazon id

### ISSUE THREAD

**Issue by arilando** [ncw/rclone#1155]
So, in order to make rclone work with amazon drive, you need to enter an amazon client id and a client secret. I had never heard of those terms before, so i googled it, and the only thing that came up was something you can see by registering your account with something called amazon seller central. So i did that. But entering the client id and secret i get from there doesn't work, and i get this error when trying to authorize:
We're sorry!
An error occurred when we tried to process your request. Rest assured, we're already working on the problem and expect to resolve it shortly.

Error Summary
400 Bad Request
An unknown scope was requested
So, what should i do? I don't know if this is an error on amazon's part of if i haven't gotten the correct client_id and secret.

**Comment by CrossR** [comment]
Are you sure you need one?

I didn't supply one when I setup ACD, and when I just made a test one now I got the follwing:

    Amazon Application Client Id - leave blank normally.
    client_id>
    Amazon Application Client Secret - leave blank normally.
    client_secret>

So have you tried just leaving them blank?

**Comment by arilando** [comment]
Okay, that works.

**Comment by ncw** [comment]
Yes the application_id and user_id are optional.  It is possible to get your own but quite a difficult process, so just use rclone's by leaving them blank.
