### ISSUE TITLE
SFTP slow down due to latency

### ISSUE THREAD

**Issue by justusiv** [ncw/rclone#1158]
When filing an issue, please include the following information if possible as well as a description of the problem.  Make sure you test with the latest beta of rclone.

    http://beta.rclone.org/
    http://rclone.org/downloads/

If you've just got a question or aren't sure if you've found a bug then please use the [rclone forum](https://forum.rclone.org/) instead of filing an issue.

> What is your rclone version (eg output from `rclone -V`)

Latest

> Which OS you are using and how many bits (eg Windows 7, 64 bit)

Windows

> Which cloud storage system are you using? (eg Google Drive)

SFTP

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

It appears as latency goes up. Transfer speeds go down at an unnatural rate.
https://forum.rclone.org/t/slow-sftp-transfers-compared-to-alternatives/1097/7
At 1ms delay I get 100 MB/s
At 10ms delay I get 73 MB/s
At 100ms delay I get 9 MB/s

**Comment by ncw** [comment]
I made an issue https://github.com/pkg/sftp/issues/158 to ask for some help with this.

**Comment by ncw** [comment]
I've been unable to replicate the speedup with FileZilla - was the tests you did with the same files from the same server in the same direction?

Were you uploading or downloading?

**Comment by justusiv** [comment]
Same files, same server, with the test back to back.
I was downloading files for my testing. My upload isnt fast enough to test that direction.

**Comment by justusiv** [comment]
I found a public sftp server to do another test on using this webpage
http://www.sftp.net/public-online-sftp-servers
demo.wftpserver.com:2222	demo-user/demo-user

Downloading only 1 100MB file i maxed my connection at 120mbps with filezilla. i pulled only about 15mpbs with rclone.

**Comment by ncw** [comment]
This might be fixed by #1561 when done

**Comment by ncw** [comment]
This implements connection pooling for multiple ssh connections
    
    A connection may be opened for each `--transfers` and `--checkers`
    now.  Connections are checked when putting them in the pool and
    getting them out the pool so it should recover from network errors
    much better.

https://beta.rclone.org/v1.37-076-g5b6585f5/ (uploaded in 15-30 mins)

Please test and reopen the issue if you are still having a problem, or make a new issue with more info.

Thanks

**Comment by ncw** [comment]
Hmm, it appears that connection pooling, while excellent in itself, doesn't solve the fundamental problem.

I set up a local sftp server and ran

    sudo tc qdisc add dev lo root netem delay 50ms

Check that ping localhost gives the expected delay

```
$ ping localhost
PING localhost (127.0.0.1) 56(84) bytes of data.
64 bytes from localhost (127.0.0.1): icmp_seq=1 ttl=64 time=100 ms
64 bytes from localhost (127.0.0.1): icmp_seq=2 ttl=64 time=101 ms
^C
```

(Use this to remove the delay)

    sudo tc qdisc del dev lo root netem

To make a 100ms roundtrip delay.

I can get about 18 MB/s with the sftp binary

    sftp sftptest@localhost:1GB

Whereas if I try this with rclone I get about 1.5 MB/s

    rclone --stats 1s -v copy TestSftp:1GB /tmp

If I try them both with no latency then they are very similar 105MB/s rclone vs 128 MB/s sftp.

I tried a comparison with netcat also.  So running a netcat server in one window

    netcat -k -l localhost 9999 </dev/zero

I measured the speed with netcat in another

    netcat localhost 9999 | pv >/dev/null

Which came about at about 25 MB/s.

Using a simple [go netcat replacement](https://play.golang.org/p/cVPXSu3m23M) I wrote I get a very similar 26 MB/s

    ~/Go/netcat localhost 9999 | pv >/dev/null

So it doesn't appear to be a problem with the go TCP stack.  I did try increasing SO_RCV_BUF with no improvments.

**Comment by ncw** [comment]
@justusiv I've commented further on https://github.com/pkg/sftp/issues/158 - it now looks to me like a bug in that package.  I made an ssh transfer with go at full speed and a tcp transfer it is just the sftp transfers which are slow over a long latency link.

**Comment by ncw** [comment]
I've managed to fix this issue by using a different interface in the sftp package :-)

https://beta.rclone.org/v1.41-069-gd4213c0a/ (uploaded in 15-30 mins)

Can you give it a test and see if you agree?

In my tests the above works at the same rate as the `sftp` binary.  This may still be slower than FileZilla but it was over 10 times faster on a 100mS ping roundtrip link.

**Comment by justusiv** [comment]
@ncw maxed my connection at 45MB/s! Thank you so much!

**Comment by ncw** [comment]
> With 1 transfer i am getting 12.5MB/s Not sure if there is a reason at the cap seemingly right at 100Mbps. Either way this light years improvement and am so thankful for the work you guys do.

What is the round trip ping time?  I suspect it is over 100mS.  I guess someone could have made a throttle for sftp at 100Mbit/s but that certainly isn't rclone.

There are probably some more speedups to be gained with some more intrusive changes in the sftp module.  I'm glad we've got to speed on a par with the openssh sftp code though :-)
