### ISSUE TITLE
[Feature Request] Amazon JP Support

### ISSUE THREAD

**Issue by hanulis** [ncw/rclone#1159]
Amazon.co.jp can't use amazon.com's username/password.

(http://amazon.co.jp/clouddrive)

It seems to be managed independently.

**Comment by ncw** [comment]
Can you try again?  There have been problems with this in the past, but I think it takes a bit of time for the new account to be synced to amazon.com or something like that.

As far as I know there isn't a separate oauth for any of the non .com Amazon's.  I know that amazon.co.uk works and also amazon.de.

**Comment by hanulis** [comment]
It works after change to another email address and change system language.

Thanks =)
