### ISSUE TITLE
rclone sync from remote http and mount in ro mode

### ISSUE THREAD

**Issue by vtolstov** [ncw/rclone#1161]
What do you think about one way sync from http/https ?
I'm already write small utility to mount remote http with directory index files to local fs via fuse.
And i think that this ability can be useful in rclone. Yes this is only one way sync, but why not?
Also i don't think that this bring new deps..

**Comment by ncw** [comment]
Do you mean making an `http` remote which looks at standard nginx or apache directory listing?

I got part of the way through writing `rclone serve` to serve a remote via http.  My plan was to make this so you could optionally upload files too.  This could serve to such a remote...

**Comment by vtolstov** [comment]
No, I mean that I'm already have nginx that serve files, and I want to
mount it to local FS or sync that remote nginx to local.

21 Фев 2017 г. 15:00 пользователь "Nick Craig-Wood" <
notifications@github.com> написал:

**Comment by ncw** [comment]
I think we are talking about the same thing.

What I'd like to do is 
  * make an `rclone serve` command which can serve an rclone remote over http
  * make an rclone remote which can read files from `rclone serve`
    * this could in addition read files in a read only fashion from nginx/apache directory listing (that is what you are talking about)

**Comment by vtolstov** [comment]
Yes... And I need fuse mount to..
Where i can find you work for this if you already have some code?

21 Фев 2017 г. 16:57 пользователь "Nick Craig-Wood" <
notifications@github.com> написал:

**Comment by ncw** [comment]
I only have code for the serve bit of it.  I pushed that to the `serve` branch if you want to have a go.

To do the remote bit of it will be a bit more work...

**Comment by vtolstov** [comment]
as i understand for serve remote i can take sftp remote as base?

**Comment by ncw** [comment]
Yes it can take any rclone remote
