### ISSUE TITLE
https:// for *.rclone.org/rclone.org

### ISSUE THREAD

**Issue by leonelwilliams** [ncw/rclone#1162]
Thanks for the beta builds & the project! They're really quite excellent.

Would it be possible to have the project sites served over a secure connection? (mainly beta.rclone.org and downloads.rclone.org)?

Downloading and running binaries/code over non-secure http:// wigs me out a little

**Comment by ncw** [comment]
There are secure links for downloads on the downloads page...

However I want to make everything secure and I plan to do this quite soon :-)

**Comment by ncw** [comment]
I've now migrated all the rclone sites onto their own server running caddy. Letsencrypt have provided certs so everything is https now!

Let me know if I've missed any links.

**Comment by marvwatson** [comment]
The repository's [website field](https://github.com/ncw/rclone) (under the `Code | Issues | ...` tab list) can be updated to point to the https version

**Comment by ncw** [comment]
@marvwatson - thanks I - I did that.  There were a few more in the README as well.

**Comment by ncw** [comment]
@marvwatson - I see your PR fixing them - thanks :-)
