### ISSUE TITLE
escape problem with brackets?

### ISSUE THREAD

**Issue by calisro** [ncw/rclone#1164]
I believe this should work but it does not:

$ cat /tmp/rclonefilelist.txt
Series/Colony/Season.1/Colony.S01E02.INTERNAL.HDTV.x264-KILLERS[ettv].nfo
 
$ rclone  --include-from $TMPFILE copy $OPT -v "/data/Media1/Videos/" "robacd-cryptp:Media/Videos"  --ignore-times 2>&1 | grep S01E02.INTERNAL.HDTV.x264-KILLER | grep nfo

2017/02/21 14:40:54 Series/Colony/Season.1/Colony.S01E02.INTERNAL.HDTV.x264-KILLERS[ettv].nfo: Excluded from sync (and deletion)

If I replace the brackets with stars, then it picks it up.  I wouldn't think I should have to start escaping file names in the include file.  That will get messy quickly.  

This is if I replace the brackets with stars:
DTV.x264-KILLERS[ettv].nfo: Copied (replaced existing)

My use case here is that I am using rsync to generate a list of files that have differing MD5 sums from the source so that I can force replacement of those files since crypt doesn't support MD5 sums.  

This is the full use case just for reference:

rsync $OPT --inplace -rlvxi --checksum -n --out-format="%n" \
 --include="*.nfo" \
 --include="*/" \
 --exclude="*" \
 /data/Media1/Videos/ /data/Media2/Videos/ | egrep -v "/$|^sent|^total|^sending" | tee $TMPFILE

echo +---------------------------------------+
echo  Replace files with diff chksums from list
echo +---------------------------------------+
rclone \
  --one-file-system \
  --transfers=8 --checkers=16 \
  --stats 5m \
  --bwlimit=10000 \
  --config="$RCLONECONF" \
  --include-from $TMPFILE \
 copy $OPT -v "/data/Media1/Videos/" "robacd-cryptp:Media/Videos" \
  --ignore-times 2>&1 | egrep -v "$CRYPTLOGFILTER"

**Comment by calisro** [comment]
I see.  It is using regexp and te [] and {} have meaning.  Let me ask this way.  Is there a way to disable regexp and use literal file names?

**Comment by calisro** [comment]
I'm going to close this because its technically not a bug.  I can deal with the brackets and braces with sed.

**Comment by ncw** [comment]
You probably want `--files-from` to make a list of exactly which files you want.  These don't need escaping.

**Comment by calisro** [comment]
Brilliant.  I knew I must be missing something but I could not find it in the docs.  But my wife says I can't find the peanut butter in the pantry a lot either.

**Comment by ncw** [comment]
> But my wife says I can't find the peanut butter in the pantry a lot either.

Hehe - mine too ;-)
