### ISSUE TITLE
Dropbox Sync issue - Path not under root.

### ISSUE THREAD

**Issue by CrossR** [ncw/rclone#1165]
> What is your rclone version (eg output from `rclone -V`)

rclone v1.35 & rclone v1.35-129-g980cd5bβ

> Which OS you are using and how many bits (eg Windows 7, 64 bit)

Windows 10 64 bit.

> Which cloud storage system are you using? (eg Google Drive)

Dropbox and ACD.

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

`rclone sync -c -vv --checkers=15 --transfers=15 dropbox: secret:Dropbox/`

> A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
 
    2017/02/21 20:44:15 DEBUG : rclone: Version "v1.35-129-g980cd5bβ" starting with parameters ["rclone" "sync" "-c" "-vv" "--checkers=15" "--transfers=15" "dropbox:" "secret:Dropbox/"]
    2017/02/21 20:44:17 INFO  : Encrypted amazon drive root 'xxxxxxxxxxxxxxxxxxxxxxxxxx': Modify window not supported
    2017/02/21 20:44:17 DEBUG : amazon drive root 'xxxxxxxxxxxxxxxxxxxxxxxxxx': Reading ""
    2017/02/21 20:44:17 DEBUG : amazon drive root 'xxxxxxxxxxxxxxxxxxxxxxxxxx': Finished reading ""
    2017/02/21 20:44:18 INFO  : Encrypted amazon drive root 'xxxxxxxxxxxxxxxxxxxxxxxxxx': Waiting for checks to finish
    2017/02/21 20:44:18 INFO  : Encrypted amazon drive root 'xxxxxxxxxxxxxxxxxxxxxxxxxx': Waiting for transfers to finish
    2017/02/21 20:44:18 ERROR : Encrypted amazon drive root 'xxxxxxxxxxxxxxxxxxxxxxxxxx': not deleting files as there were IO errors
    2017/02/21 20:44:18 ERROR : Attempt 1/3 failed with 0 errors and: error reading source directory "Important": path "/Important/Test.txt" is not under root "/Important/"
    2017/02/21 20:44:18 DEBUG : amazon drive root 'xxxxxxxxxxxxxxxxxxxxxxxxxx': Reading ""
    2017/02/21 20:44:18 DEBUG : amazon drive root 'xxxxxxxxxxxxxxxxxxxxxxxxxx': Finished reading ""
    2017/02/21 20:44:19 INFO  : Encrypted amazon drive root 'xxxxxxxxxxxxxxxxxxxxxxxxxx': Waiting for checks to finish
    2017/02/21 20:44:19 INFO  : Encrypted amazon drive root 'xxxxxxxxxxxxxxxxxxxxxxxxxx': Waiting for transfers to finish
    2017/02/21 20:44:19 ERROR : Encrypted amazon drive root 'xxxxxxxxxxxxxxxxxxxxxxxxxx': not deleting files as there were IO errors
    2017/02/21 20:44:19 ERROR : Attempt 2/3 failed with 0 errors and: error reading source directory "BackUps": path "/BackUps/Android Backups" is not under root "/BackUps/"
    2017/02/21 20:44:19 DEBUG : amazon drive root 'xxxxxxxxxxxxxxxxxxxxxxxxxx': Reading ""
    2017/02/21 20:44:20 DEBUG : amazon drive root 'xxxxxxxxxxxxxxxxxxxxxxxxxx': Finished reading ""
    2017/02/21 20:44:20 INFO  : Encrypted amazon drive root 'xxxxxxxxxxxxxxxxxxxxxxxxxx': Waiting for checks to finish
    2017/02/21 20:44:20 INFO  : Encrypted amazon drive root 'xxxxxxxxxxxxxxxxxxxxxxxxxx': Waiting for transfers to finish
    2017/02/21 20:44:20 ERROR : Encrypted amazon drive root 'xxxxxxxxxxxxxxxxxxxxxxxxxx': not deleting files as there were IO errors
    2017/02/21 20:44:20 ERROR : Attempt 3/3 failed with 0 errors and: error reading source directory "Photos": path "/Photos/4K" is not under root "/Photos/"
    2017/02/21 20:44:20 Failed to sync: error reading source directory "Photos": path "/Photos/4K" is not under root "/Photos/"

When I run the exact same command in rclone v1.35 (With -v not -vv), it's fine.

    2017/02/21 20:49:17 rclone: Version "v1.35" starting with parameters ["rclone.exe" "sync" "-c" "-v" "--checkers=15" "--transfers=15" "dropbox:" "secret:Dropbox/"]
    2017/02/21 20:49:18 Encrypted amazon drive root 'xxxxxxxxxxxxxxxxxxxxxxxxxx': Modify window not supported
    2017/02/21 20:49:18 amazon drive root 'xxxxxxxxxxxxxxxxxxxxxxxxxx': Reading ""
    2017/02/21 20:49:18 amazon drive root 'xxxxxxxxxxxxxxxxxxxxxxxxxx': Finished reading ""
    2017/02/21 20:49:18 amazon drive root 'xxxxxxxxxxxxxxxxxxxxxxxxxx': Reading "xxxxxxxxxxxxxxxxxxxxxxxxxx/"
    2017/02/21 20:49:18 amazon drive root 'xxxxxxxxxxxxxxxxxxxxxxxxxx': Finished reading "xxxxxxxxxxxxxxxxxxxxxxxxxx/"
    2017/02/21 20:49:18 amazon drive root 'xxxxxxxxxxxxxxxxxxxxxxxxxx': Reading "xxxxxxxxxxxxxxxxxxxxxxxxxx/xxxxxxxxxxxxxxxxxxxxxxxxxx/"
    2017/02/21 20:49:18 amazon drive root 'xxxxxxxxxxxxxxxxxxxxxxxxxx': Finished reading "xxxxxxxxxxxxxxxxxxxxxxxxxx/xxxxxxxxxxxxxxxxxxxxxxxxxx/"
    2017/02/21 20:49:20 Dropbox root '': 1748 delta entries received
    2017/02/21 20:49:23 Photos/Backgrounds/1920x1080.jpg: Copied (new)

It carries on fine from here to perform the sync.

Not sure what changes have occurred between these two versions, but looks like its altered something?

**Comment by ncw** [comment]
That looks like a regression - thanks for reporting.

It seems like the depth 1 listing code in dropbox is broken:

```
$ rclone ls --max-depth 1 dropbox:Photos
2017/02/22 09:28:41 Failed to ls: path "/Photos/XXXX" is not under root "/Photos/"
```

I'll post a beta for you to try when I've figured out what is going on.

**Comment by ncw** [comment]
I've fixed this in the beta below

    http://beta.rclone.org/v1.35-131-g12aa03f/ (uploaded in 15-30 mins)

Let me know if it works for you - re-open the ticket if it doesn't

Thanks

**Comment by CrossR** [comment]
The sync itself has been fixed, but there is some weird issue with Capitalisation of the folders now.

    rclone lsd --max-depth=2 secret:Dropbox/:

          -1 2017-02-22 19:08:09        -1 Work
          -1 2017-02-22 19:08:00        -1 Important
          -1 2017-02-22 19:07:59        -1 backups
          -1 2017-02-22 19:08:02        -1 photos
          -1 2017-02-22 19:08:04        -1 work
          -1 2017-02-22 19:07:52        -1 important
          -1 2017-02-22 19:07:51        -1 BackUps
          -1 2017-02-22 19:07:37        -1 Photos
          -1 2017-02-22 19:07:38        -1 temp files
          -1 2017-02-22 19:08:13        -1 work/yr2
          -1 2017-02-22 19:10:23        -1 work/yr3
          -1 2017-02-22 19:07:57        -1 work/yr1
          -1 2017-02-22 19:07:57        -1 important/uni
          -1 2017-02-22 19:08:29        -1 photos/4K
          -1 2017-02-22 19:08:48        -1 photos/Portrait
          -1 2017-02-22 19:10:23        -1 photos/Backgrounds
          -1 2017-02-22 19:08:06        -1 backups/file backups
          -1 2017-02-22 19:08:06        -1 backups/config backups
          -1 2017-02-22 19:07:51        -1 backups/Android Backups
          -1 2017-02-22 19:07:40        -1 backups/File Backups
          -1 2017-02-22 19:08:04        -1 BackUps/Android Backups
          -1 2017-02-22 19:08:09        -1 Work/yr3
          -1 2017-02-22 19:07:40        -1 temp files/Receipts
          -1 2017-02-22 19:08:00        -1 Important/Personal

I'm not really sure what is causing this issue though.
I think its something to do with having a mix of files and folders in a single directory.

**Comment by CrossR** [comment]
I'm not sure, it wasn't this way with 1.35.
I purged the directory and resynced with 1.35 again and am now seeing:

          -1 2017-02-22 19:27:19        -1 Important
          -1 2017-02-22 19:26:59        -1 Temp Files
          -1 2017-02-22 19:27:00        -1 BackUps
          -1 2017-02-22 19:26:58        -1 Photos
          -1 2017-02-22 19:26:09        -1 Work
          -1 2017-02-22 19:26:54        -1 Work/yr2
          -1 2017-02-22 19:26:55        -1 Work/yr1
          -1 2017-02-22 19:28:33        -1 Work/yr3
          -1 2017-02-22 19:27:01        -1 BackUps/Config Backups
          -1 2017-02-22 19:27:08        -1 BackUps/File Backups
          -1 2017-02-22 19:27:05        -1 BackUps/Android Backups
          -1 2017-02-22 19:26:24        -1 Photos/Portrait
          -1 2017-02-22 19:26:24        -1 Photos/Spanned
          -1 2017-02-22 19:27:22        -1 Photos/4K
          -1 2017-02-22 19:27:06        -1 Photos/Backgrounds
          -1 2017-02-22 19:27:12        -1 Temp Files/Receipts
          -1 2017-02-22 19:26:56        -1 Important/Personal
          -1 2017-02-22 19:26:57        -1 Important/Uni

Which is how it should be.

This looks like the sync itself is causing strangely named folders, rather than the listing command.
In the log output in the latest beta, I can see


    2017/02/22 19:31:18 INFO  : backups/Android Backups/Reddit Sync/file.1: Copied (new)
    ...
    2017/02/22 19:31:18 INFO  : BackUps/Android Backups/Action Launcher Pro/file.2: Copied (new)

Which looks like its physically writing new folders of backups and Backups, rather than it being a listing error.

**Comment by ncw** [comment]
The reason why it is different between v1.35 and the latest beta is that rclone uses a different method of listing the files.

I'm going to re-open this issue and think some more on how to fix it.

**Comment by CrossR** [comment]
Ah that would make sense! 

I only mentioned since it means that files synced in 1.35 are the new beta are incompatible.

Running `rclone sync` with the latest beta on a backup made with 1.35 does a full recopy of all files (well almost all), which whilst it isn't an issue for me with 4GB of files, could be an issue for other people expecting to only move a file or two.

**Comment by ncw** [comment]
I think I have fixed this here.  Would you mind trying the sync again and see if it is fixed for you?

http://beta.rclone.org/v1.35-138-g527099a/ (uploaded in 15-30 mins)

Thanks

Nick

**Comment by CrossR** [comment]
Perfect! That has fixed it for me!

Cheers for the quick fix, and amazing project!

**Comment by ncw** [comment]
Thanks for testing :-)
