### ISSUE TITLE
[Enhancement] stats show the amount data transferred not just %  

### ISSUE THREAD

**Issue by ajkis** [ncw/rclone#1167]
It would be great if stats in logs would show us the amount of data transferred in kb/mb and not just %

eg
movies/Alien (1979)/Alien (1979).mp4:  **10MB** 0% done, 1.702 MBytes/s, ETA: 17m3s

p,s, If average transfer per file could be showed would be awesome as well so we get general idea if cloud is preforming well enough for streaming eg we know that at least 20Mibs+ we need for full 1080p and now with buffer its hard to monitor ... maybe current buffer value of the transfer

**Comment by ncw** [comment]
> It would be great if stats in logs would show us the amount of data transferred in kb/mb and not just %

Something like this?

    movies/Alien (1979)/Alien (1979).mp4: 5MB/10MB 0% done, 1.702 MBytes/s, ETA: 17m3s

>  If average transfer per file could be showed would be awesome as well so we get general idea if cloud is preforming well enough for streaming eg we know that at least 20Mibs+ we need for full 1080p and now with buffer its hard to monitor ... maybe current buffer value of the transfer

That figure `1.702 MBytes/s` is the average transfer for that file.  Did you mean something different?

**Comment by ajkis** [comment]
Ya i meant overall average as you show 10 seconds ( or some other timeframe average ) 

p.s. Do you think you could add the buffer stats as well ( that one can be in % since its fixed ammount )
`buffer 70%`

**Comment by ncw** [comment]
I see what you mean :-)

**Comment by ajkis** [comment]
Ideally we could get such print in log 
`movies/Alien (1979)/Alien (1979).mp4: 5MB/10MB 0% done, 1.702 MBytes/s / 7,200 MBytes/s, ETA: 17m3s  (Buffer: 250MB/500MB 50%)`

**Comment by Givemeyourgits** [comment]
+1 on the buffer, that's what I'm most interested in seeing.

**Comment by ishuah** [comment]
Please find a beta with fix in: https://beta.rclone.org/v1.38-169-gb4aa920a/ (uploaded in 15-30 minutes)
