### ISSUE TITLE
Rclone website

### ISSUE THREAD

**Issue by baro77** [ncw/rclone#1169]
Page http://rclone.org/docs/ , "Exit Code" section at the bottom

I think the sentence:  " [...] and only exit with an NON-zero exit code if (after retries) there were NO transfers with errors remaining. " should have that 'NON' xor that 'NO' ,  but not both because, if I got it right:

==0 no errors
!=0 still errors after retries

Bye & thanks for your work

**Comment by ncw** [comment]
Fixed - thank you!
