### ISSUE TITLE
Update Google Drive config documentation

### ISSUE THREAD

**Issue by kubark42** [ncw/rclone#1174]
> What is your rclone version (eg output from `rclone -V`)
rclone v1.35-DEV (installed from `brew`)

> Which OS you are using and how many bits (eg Windows 7, 64 bit)
macOS 10.12.2

> Which cloud storage system are you using? (eg Google Drive)
Google Drive

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rconfig

Just discovered this project, it's **awesome**. Followed the directions at http://rclone.org/drive/ and ran into a minor problem configuring the storage type. The docs show choosing `6` but in reality the number is now `7`. This is the current output of the command:

```
Choose a number from below, or type in your own value
 1 / Amazon Drive
   \ "amazon cloud drive"
 2 / Amazon S3 (also Dreamhost, Ceph, Minio)
   \ "s3"
 3 / Backblaze B2
   \ "b2"
 4 / Dropbox
   \ "dropbox"
 5 / Encrypt/Decrypt a remote
   \ "crypt"
 6 / Google Cloud Storage (this is not Google Drive)
   \ "google cloud storage"
 7 / Google Drive
   \ "drive"
 8 / Hubic
   \ "hubic"
 9 / Local Disk
   \ "local"
10 / Microsoft OneDrive
   \ "onedrive"
11 / Openstack Swift (Rackspace Cloud Files, Memset Memstore, OVH)
   \ "swift"
12 / Yandex Disk
   \ "yandex"
```

Of course, if you accidentally choose 6-- because it's been seeded in your head by the docs--, everything goes normally, including the part where it opens a browser window and gets the google API key. And, of course, nothing works for Google Drive because you get a `can't list buckets without project number` error. So there's a little bit of confirmation bias going on there, and it's not until you google the problem that you catch that the error is self-inflicted.

It's a reasonable guess that the same problem was had here: https://forum.rclone.org/t/cant-list-buckets-without-project-number/581.

Anyway, cheers to this project! Can't believe how seamless this has made my cloud experience. Wish I would have found it before.

**Comment by ajkis** [comment]
What do you mean ? 
at 6 you have **(this is not Google Drive)**

**Comment by kubark42** [comment]
@ajkis What I have pasted above is the current result. The below is taken from http://rclone.org/drive/:

```
n) New remote
d) Delete remote
q) Quit config
e/n/d/q> n
name> remote
Type of storage to configure.
Choose a number from below, or type in your own value
 1 / Amazon Drive
   \ "amazon cloud drive"
 2 / Amazon S3 (also Dreamhost, Ceph)
   \ "s3"
 3 / Backblaze B2
   \ "b2"
 4 / Dropbox
   \ "dropbox"
 5 / Google Cloud Storage (this is not Google Drive)
   \ "google cloud storage"
 6 / Google Drive
   \ "drive"
 7 / Hubic
   \ "hubic"
 8 / Local Disk
   \ "local"
 9 / Microsoft OneDrive
   \ "onedrive"
10 / Openstack Swift (Rackspace Cloud Files, Memset Memstore, OVH)
   \ "swift"
11 / Yandex Disk
   \ "yandex"
Storage> 6
```

There's a ` 5 / Encrypt/Decrypt a remote   \ "crypt"` insertion which pushed the rest of the numbers down.

**Comment by ajkis** [comment]
A nice catch.

**Comment by ncw** [comment]
With the latest beta you can use the name of the remote, eg `drive` instead of the number.

I really need to be able to update these docs automatically - there are 11 remotes and their numbers keep changing!

In the mean time any takers to send a PR?

**Comment by kubark42** [comment]
@ncw I went to submit a PR for this, but it looks like it's already in the `master` branch? https://github.com/ncw/rclone/blob/master/docs/content/drive.md

**Comment by ncw** [comment]
@kubark42 this release has been going on to long - I'd forgotten that!  3c87a0d0dcc822ae53b65edd1878e5e1f18ab5a6 was the commit - it is probably out of date though since the sftp remote got added after that

**Comment by kubark42** [comment]
> I really need to be able to update these docs automatically - there are 11 remotes and their numbers keep changing!

@ncw there seem to be a few ways of importing external content into Markdown documents. I'm not sure if any apply to how `rclone` docs are generated, but here's a list of a few:

* https://randomdeterminism.wordpress.com/2012/06/01/how-i-stopped-worring-and-started-using-markdown-like-tex/
* http://fletcher.github.io/MultiMarkdown-4/transclusion.html
* https://obedm503.github.io/bootmark/docs/examples.html / https://obedm503.github.io/bootmark/
* http://assemble.io/docs/Markdown.html
