### ISSUE TITLE
Copying to encrypted GDrive remote: "write:  broken pipe" doesn't get retried? 

### ISSUE THREAD

**Issue by DurvalMenezes** [ncw/rclone#1177]
Hello, 

Just saw the following while copying from local to an encrypted Google Drive remote while running rclone v1.35-99-g6fc114dβ on Devuan 1.0 (Debian Jessie systemd-free fork) 64 bits, the precise rclone command line was:

`rclone copy --low-level-retries 100 --checkers 12 --transfers 12 -v --log-file=./20170224Z150635_rclone_copy_REDACTED /REDACTED egd:REDACTED
`

And here is the error line from the log: 
`2017/02/26 05:39:17 ERROR : REDACTED/REDACTED/REDACTED/REDACTED/REDACTED_flat: Failed to copy: Post https://www.googleapis.com/upload/drive/v2/files?alt=json&uploadType=resumable&upload_id=AEnB2UpXDdbm-LARKqeF61sVhpzHstC9I_NJ5WqyrhGVlW2ltBaQ4tru4X_z06ZQyOsH5cu1dkv7pE60d_D-X7_sCxEIfh3_Y6WDbtOpelHRNQWkiEORmyM: write tcp 192.168.0.250:59945->172.217.29.74:443: write: broken pipe
`

There are *no* "low-level retry" lines before or after the above, so the entire upload got scrapped (right after a "Transferring: " line reported 97% of its ~128GB uploaded... :-/ )

Also, no "high level retries" (ie, trying to send the file again from the beginning) either: the file simply got skipped, so I will have to run the above command again later, just for that file and possibly others that will get the same error  (the above command has been running for ~50h and still hasn't finished :-/ ). 

Cheers, 
   Durval

**Comment by ncw** [comment]
That is bad luck :-(

Note that you need `-vv` to see all the low level retries now as they are DEBUG messages.

Only certain errors get retried - ones that are considered to be temporary.  Obviously that one didn't get considered to be temporary (or maybe didn't).

It should do a high level retry when the sync has finished and try again.  However this will involve uploading the entire file again.

Now because this file is uploading in chunks, there might be an argument that all errors should be retried, not just "retriable" ones.

Anyway I will add "broken pipe" to the list of retriable erros (not sure why go wasn't classifying it as that anyway - maybe that is a bug in go).

**Comment by DurvalMenezes** [comment]
> Note that you need -vv to see all the low level retries now as they are DEBUG messages.

Thanks for the info, @ncw -- I was not aware of that. Will be running with `-vv` from now on. 

> It should do a high level retry when the sync has finished and try again. However this will involve uploading the entire file again.

I will make sure to check the log and see whether this happens (I estimate it's still a few days off from finishing this copy) 

> Now because this file is uploading in chunks, there might be an argument that all errors should be retried, not just "retriable" ones.
? Anyway I will add "broken pipe" to the list of retriable erros (not sure why go wasn't classifying it as that anyway - maybe that is a bug in go).

That will be great -- IMHO large files like these are the ones more likely to get such an error, and retrying just the chunk that got the error (and then uploading the subsequent ones) will certainly be way more efficient than uploading the whole file.

Cheers,
   Durval.

**Comment by sws78** [comment]
Good evening,
I noticed that this is happening on my B2 encrypted backup also.  The first sync is still running but I noticed this showing up quite a bit in the logs.

**Comment by ncw** [comment]
@sws78 "broken pipe" usually indicates Internet problems.  rclone will retry anything that failed the first time, so don't worry too much about it - the Internet isn't 100% reliable!

**Comment by ncw** [comment]
I have fixed the "broken pipe" not being retried in 798502b2040a41ea7dc08b1a1df096e80e50db95 and #1660 so I'm going to close this now.
