### ISSUE TITLE
Shell escaping

### ISSUE THREAD

**Issue by calisro** [ncw/rclone#1183]
I'm having a bit of a problem with shell escaping.

I use a variable to store a bunch of my default switches but no matter how I escape the quotes, don't use them, or use different quotes, it isn't interpreting like i'd expect.

Example:
STD_SWITCHES="--stats 5m 
--config='$RCLONECONF' 
--transfers=16 --checkers=32 
--one-file-system 
--bwlimit="07:00,6M 23:00,10M" "

-># echo $STD_SWITCHES
--stats 5m --config='/home/robert/.rclone.conf' --transfers=16 --checkers=32 --one-file-system --bwlimit="07:00,6M 23:00,10M"
root@HS: ~
-># rclone $STD_SWITCHES rmdirs
Error: invalid argument ""07:00,6M" for --bwlimit="07:00,6M: invalid time specification (hh:mm): ""07:00"
Usage:
...
...
2017/02/27 12:14:21 Fatal error: invalid argument ""07:00,6M" for --bwlimit="07:00,6M: invalid time specification (hh:mm): ""07:00"

I've tried all of the following:
STD_SWITCHES="--stats 5m 
--config='$RCLONECONF' 
--transfers=16 --checkers=32 
--one-file-system 
--bwlimit='07:00,6M 23:00,10M' "

STD_SWITCHES="--stats 5m 
--config='$RCLONECONF' 
--transfers=16 --checkers=32 
--one-file-system 
--bwlimit=07:00,6M 23:00,10M "

STD_SWITCHES="--stats 5m 
--config='$RCLONECONF' 
--transfers=16 --checkers=32 
--one-file-system 
--bwlimit=07:00,6M\ 23:00,10M "

Seems to be the parser in general. I've never run into this because I didn't have spaces in any of the variables until the bwlimit one was introduced but this doesn't work for the config variable either. Basically there is no way to escape it properly but it isn't the bwlimit parsing itself. It is the command line parser in general.

**Comment by ncw** [comment]
I think this is all to do with the shell.  The problem I think is the use of " within the quotes

This should work

```
STD_SWITCHES="--stats 5m
\"--config=$RCLONECONF\"
--transfers=16 --checkers=32
--one-file-system
\"--bwlimit=07:00,6M 23:00,10M\""
```

Note that when you do `rclone --bwlimit="07:00,6M 23:00,10M"` it is the shell parsing the quotes, not rclone.

So your original command passed the quotes to rclone which it doesn't parse - it is expecting the shell to do that.

**Comment by calisro** [comment]
I would have though so, but it doesn't.  here:
```

set -x
+ set -x
#STD_SWITCHES="--stats 5m \"--bwlimit=07:00,6M 23:00,10M\""
+ STD_SWITCHES='--stats 5m "--bwlimit=07:00,6M 23:00,10M"'
#rclone ls /tmp $STD_SWITCHES
+ rclone ls /tmp --stats 5m '"--bwlimit=07:00,6M' '23:00,10M"'
Usage:
  rclone ls remote:path [flags]


```

Now, if I take that exact command and run it without a variable:

```
#rclone ls /tmp --stats 5m "--bwlimit=07:00,6M 23:00,10M"
+ rclone ls /tmp --stats 5m '--bwlimit=07:00,6M 23:00,10M'
        0 dyndnslogin_output_***AzoO
        0 rclonefilelist.txt
...
...
```

rclone is doing something really non-standard when pulling in the variables.  This type of variable substitution is pretty typical.

**Comment by calisro** [comment]
I just verified rsync behaves the same way with switches with spaces in them.  I'll close this as it isn't an rclone problem.  I'm not sure how to deal with this but one way may be to use eval to eval the command before running it.  Pretty clumsy though.

**Comment by marcopaganini** [comment]
You're being bitten by shell expansion.

When you do this:

$ cmd a b "foo bar"

You get:
argv[1] = "a"
argv[2] = "b"
argv[3] = "foo bar"

Which is what you want. But then you're setting this on a variable:

a="a b \"foo bar\""
cmd $a

cmd will actually see:

argv[1] = "a"
argv[2] = "b"
argv[3] = "foo"
argv[4] = "bar"

Notice how the space between foo and bar caused the expansion of foo and bar into two different arguments. This is not what you want. An alternative would be to avoid expansion by quoting $a:

$ cmd "$a"

But that will break in a different way. "cmd" will see:

$argv[1] = "a b foo bar"

The easiest way in your case would be:

eval "cmd $a"

**Comment by calisro** [comment]
Thanks Marco.  Makes total sense.

**Comment by adautoserpa** [comment]
@calisro Did you solve this problem? I tried it in several ways, but I could not.

**Comment by ncw** [comment]
@adautoserpa I'd solve this by [setting environment variables to set switches](https://rclone.org/docs/#environment-variables) which eases the shell escaping pain.

**Comment by adautoserpa** [comment]
@ncw @calisro Good solution. I solved it like this:

```
declare -a PARAMETERS=()
PARAMETERS=(\
--bwlimit="08:00,3M 21:00,3M" \
--log-file $LOG_DIR/rclone-$DATE_BACKUP.log \
--transfers 4
--low-level-retries 50 \
--retries 50 \
--stats=0 \
--checksum \
-v)

LOCAL_FOLDER=Local_Folder_Path
REMOTE_FOLDER=Cloud_Drive:Remove_Folder_Path

rclone sync $LOCAL_FOLDER $REMOTE_FOLDER "${PARAMETERS[@]}"
```
