### ISSUE TITLE
sync like command but first remove from dest all files that absent from source, and after that cleanup source

### ISSUE THREAD

**Issue by vtolstov** [ncw/rclone#1184]
I need sync like command but first remove from dest all files that absent from source, and after that cleanup source.
As i see this is can't be done with current rclone sync command. How can i deal with this or i need to create additional flag to sync command ?

**Comment by ncw** [comment]
> I need sync like command but first remove from dest all files that absent from source

sync with --delete-before will do that

It will remove all files in dest that are absent from the source

> and after that cleanup source

Not sure I understand what you mean here?  rclone never touches the source directory.

**Comment by vtolstov** [comment]
> Not sure I understand what you mean here? rclone never touches the source directory.

I know. My use case - sync local to remote (and delete from remote all files absent from local) and after that cleanup local.
I can do this like sync and delete. But may be possible to add this via one command?

**Comment by ncw** [comment]
If by cleanup local you mean delete everything, then `rclone move` will do what you want.  You can use `--delete-before` with that if you want.

**Comment by vtolstov** [comment]
nice! does it possible to rclone move --delete-after so firstly rclone moves new files, and after that cleanups old stuff ?

**Comment by ncw** [comment]
Yes `--delete-after` is the default and what I'd recommend using.

**Comment by vtolstov** [comment]
Ok,
