### ISSUE TITLE
rclone sync - dont delete dest if no content on source

### ISSUE THREAD

**Issue by ajkis** [ncw/rclone#1186]
We really need the flag for rclone to not delete destination remote if there is 0 content on source.
eg if cloud provider decide to delete all your files on source and you sync it to another cloud provider those files will be deleted.

I assume if you sync specific folder eg remote1:/myfolder remote2/myfolder that if remote1:/myfolder is missing the sync wont be preformed ?

But if sync whole drive eg sync remote1: remote2: if provider deleted all files on remote1: your files on remote2 will be gone as well. 

Maybe rclone could have stat command so we could check specific file and continue only if present. 
(its probably double even now, without mounting drive )

**Comment by ncw** [comment]
I think #1032 covers this too?

**Comment by ajkis** [comment]
ah yea i forgot i made an issue about it a while ago.

Iam a bit in panic mode since all my content is sycning over multiple cloud providers and if main one goes down will loose all.

**Comment by ncw** [comment]
OK I put that one on the 1.37 milestone and I'll close this one.
