### ISSUE TITLE
ACD rclone copy --retries 0 aborts with errror

### ISSUE THREAD

**Issue by felixbuenemann** [ncw/rclone#1189]
If I try to copy from one ACD drive to another with `--retries 0` the process aborts with an error:

```
rclone copy --retries 0 --size-only acd1:Media/Movies acd2:Media/Movies
amazon drive root: 'Media/Movies': Modify window not supported
```

The same command with `--retires 1` works, but this retries at least once, but I want disable retries.

Tested on rclone 1.3.5. The same error happens with a gdrive source, so it seems to be related to the copy target.

**Comment by ncw** [comment]
Actually `--retries 1` should really be called `--tries 1` so it will only try the once.

**Comment by felixbuenemann** [comment]
Well, `--retries 1` does retry once, if a transfer fails at lets say 8%, it retries:

```
Transferring:
 *          Movie.mkv:  8% done, 934.945 kBytes/s, ETA: 1h14m35s

2017/03/01 12:40:55 Movie.mkv: Upload error detected but didn't finish upload: HTTP code 400: "400 Bad Request": response body: "{\"message\":\"Cannot complete upload\"}" ("400 Bad Request")
2017/03/01 12:40:55 pacer: Rate limited, sleeping for 774.306533ms (1 consecutive low level retries)
2017/03/01 12:40:55 pacer: low level retry 1/1 (error HTTP code 400: "400 Bad Request": response body: "{\"message\":\"Cannot complete upload\"}")
2017/03/01 12:40:55 Movie.mkv: Received error: HTTP code 400: "400 Bad Request": response body: "{\"message\":\"Cannot complete upload\"}" - low level retry 1/10
2017/03/01 12:40:56 pacer: Resetting sleep to minimum 20ms on success
2017/03/01 12:40:56
Transferred:   364.932 GBytes (12.270 MBytes/s)
Errors:                 5
Checks:               493
Transferred:           15
Elapsed time:  8h27m36.6s
Transferring:
 *          Movie.mkv:  0% done, 0 Bytes/s, ETA: -
```

**Comment by ncw** [comment]
That is a `--low-level-retry`

**Comment by felixbuenemann** [comment]
Thanks, would you care to explain the difference between the two?

**Comment by ncw** [comment]
Sure...

`--low-level-retries` are used to retry individual actions immediately.  Stuff that goes wrong all the time.

`--retries` are used to retry the entire sync/copy/move if there was an error.

**Comment by felixbuenemann** [comment]
So, if rclone has exhausted all low-level-retries it would then do a whole retry that counts towards the retries limit?

**Comment by ncw** [comment]
If it exhausts the low level retries it will count that file as errored, log a message and move on.

When it gets to the end of the sync if there are errors and it has retries left it will retry the whole sync.

**Comment by felixbuenemann** [comment]
Aah, that makes sense. So what I actually want is something like `--low-level-retries 1 --retries 2`, because on acd files that errored tend to fail again if immediately retried, but will usually work if retried at a later point. There api has the most terrible error rates…
