### ISSUE TITLE
rmdirs not showing what actions were taken.

### ISSUE THREAD

**Issue by calisro** [ncw/rclone#1192]
I would expect that it would tell me what it did for logging. 

rclone    --bwlimit="07:00,6M 23:00,10M"    --stats 5m    --config=$RCLONECONF    --transfers=16 --checkers=32    --one-file-system    --exclude=".unionfs" rmdirs $OPT -vvv /data/Media3/apk
2017/03/01 12:10:19 INFO  : Starting bandwidth limiter at 6MBytes/s
2017/03/01 12:10:19 DEBUG : rclone: Version "v1.35-137-ge2f0feeβ" starting with parameters ["rclone" "--bwlimit=07:00,6M 23:00,10M" "--stats" "5m" "--config=/home/robert/.rclone.conf" "--transfers=16" "--checkers=32" "--one-file-system" "--exclude=.unionfs" "rmdirs" "-vvv" "/data/Media3/apk"]
2017/03/01 12:10:19 INFO  : Local file system at /data/Media3/apk: Modify window is 1ns
2017/03/01 12:10:21 INFO  : 
Transferred:      0 Bytes (0 Bytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:        1.3s
2017/03/01 12:10:21 DEBUG : Go routines at exit 7
2017/03/01 12:10:21 DEBUG : rclone: Version "v1.35-137-ge2f0feeβ" finishing with parameters ["rclone" "--bwlimit=07:00,6M 23:00,10M" "--stats" "5m" "--config=/home/robert/.rclone.conf" "--transfers=16" "--checkers=32" "--one-file-system" "--exclude=.unionfs" "rmdirs" "-vvv" "/data/Media3/apk"]

**Comment by ncw** [comment]
Yes I agree with you.  I'll put a Debug or Info log in when directories are deleted.

**Comment by ncw** [comment]
I have fixed this in https://beta.rclone.org/v1.36-222-gf3c7e1a9/ (uploaded in 15-30 mins)

**Comment by calisro** [comment]
Beautiful. Thanks Nick.
