### ISSUE TITLE
Owncloud support

### ISSUE THREAD

**Issue by hdijkema** [ncw/rclone#1194]
It would be great if owncloud would be natively supported.

**Comment by ncw** [comment]
When we get round to doing WebDav in #580 - this should make Owncloud work

**Comment by putty182** [comment]
An OwnCloud App that makes calls directly to `rclone` might be a simpler way to approach this - I'm surprised one doesn't exist already! 

Useful things:
- [OwnCloud Developer Manual - External Storage Backends](https://doc.owncloud.org/server/9.2/developer_manual/app/extstorage.html)
-  Adapter could parse JSON Output #1063 or use nasty regex like [mmozeiko/RcloneBrowser](https://github.com/mmozeiko/RcloneBrowser/blob/1.2/src/item_model.cpp#L93) does

**Comment by ncw** [comment]
Here is the first version of the webdav remote

https://beta.rclone.org/v1.38-017-g7f3dc9b5/ (uploaded in 15-30 mins)

I've tested it with owncloud and nextcloud but I haven't tested it with any other webdav servers though.

Here are [the docs](https://github.com/ncw/rclone/blob/master/docs/content/webdav.md)

Please report issues with this in #580.
