### ISSUE TITLE
using --files-from when that file is blank causes rclone to copy everything

### ISSUE THREAD

**Issue by calisro** [ncw/rclone#1196]
When using --from-files I would expect a blank file to mean to do nothing rather than copy everything.  I dynamically create that file and it can be blank if there is no work to do.  I will check in the shell for an empty file and not continue but rclone should not copy everything again because of a empty file passed via --files-from

**Comment by ncw** [comment]
I agree this is unintended behaviour.

:star: for finding 3 bugs in a one day :-)

**Comment by ncw** [comment]
I've fixed this in 

http://beta.rclone.org/v1.35-155-g10e532b/ (uploaded in 15 - 30 mins)
