### ISSUE TITLE
Beta: config variables

### ISSUE THREAD

**Issue by calisro** [ncw/rclone#1198]
I can't seem to get rclone to recognize some of the environment variables outlined here:

https://github.com/ncw/rclone/issues/616

Example.
```

# env | grep RCLONE
RCLONE_STATS=5s
RCLONE_CONFIG=/home/robert/.rclone.conf
```

The RCLONE_CONFIG works but the RCLONE_STATS does not.  Also there is no way to tell what variables have been applied.  My suggestion is to include in the INFO or DEBUG output the parameters applied similarly to the echo'd command line already does.  That way we don't need to guess if there was a typo. :)  

```
rclone -vvv ls robacd:
2017/03/02 13:08:13 DEBUG : rclone: Version "v1.35-137-ge2f0feeβ" **starting with parameters** ["rclone" "-vvv" "ls" "robacd:"]
```

Can you also tell me why RCLONE_STATS doesn't work?  Is that a bug?

**Comment by ncw** [comment]
The environment vars change the default values of the flags as you can see here

```
$ rclone -h | grep stats
      --stats duration                    Interval between printing stats, e.g 500ms, 60s, 5m. (0 to disable) (default 1m0s)
$ RCLONE_STATS=5s rclone -h | grep stats
      --stats duration                    Interval between printing stats, e.g 500ms, 60s, 5m. (0 to disable) (default 5s)
```

So you can check that they are applied like that.

The `--stats` is a slightly special case as commands which don't normally give stats (like `ls`) won't give stats unless you actually pass the `--stats` parameter. 

Logging the variables read from the environment is complicated by the fact that you need them set up to log stuff...

**Comment by calisro** [comment]
ahhhhh.  Beautiful.  Adding that tidbit to the DOCs may make sense for the rclone -h to verify. Great stuff.

**Comment by ncw** [comment]
I've done exactly that - thanks for the suggestion :-)

**Comment by calisro** [comment]
I realize you said that --stats was a special case:

> The --stats is a slightly special case as commands which don't normally give stats (like ls) won't give stats unless you actually pass the --stats parameter.

I would, however, expect that this would print stats.  But it is not.  

```
-># export RCLONE_STATS=5m
-># export RCLONE_CONFIG=/home/robert/.rclone.conf
-># export RCLONE_TRANSFERS=16
-># export RCLONE_CHECKERS=64
-># export RCLONE_ONE_FILE_SYSTEM=true
->#  rclone \
>   --size-only \
>  copy -v /data/Media1 /data/Media2

```
I actually thought the rclone may have been hung so I killed it but then I checked other things and it is copying data.

**Comment by calisro** [comment]
Human error. reclosed. :+1:
