### ISSUE TITLE
Path should never be truncated in stats output

### ISSUE THREAD

**Issue by allanlaal** [ncw/rclone#1206]
## use case:

I want to see what file is being uploaded, I go to my rclone window and see a verbose log of events to check it.

## expected result

	2017/03/04 02:57:59 
	Transferred:   1.947 GBytes (56.809 kBytes/s)
	Errors:              1219
	Checks:            195898
	Transferred:        16559
	Elapsed time:   9h59m0.5s
	Transferring:
	 * /complete/full/path/to/lib/postgresql/9.4/main/base/48337/48343.5: 61% done. avg:  582.8, cur:  636.9 kByte/s. ETA: 10m36s

I see the file being uploaded and can take action to prune it for the next time or whatever.

## actual result:

	2017/03/04 02:57:59 
	Transferred:   1.947 GBytes (56.809 kBytes/s)
	Errors:              1219
	Checks:            195898
	Transferred:        16559
	Elapsed time:   9h59m0.5s
	Transferring:
	 * ...lib/postgresql/9.4/main/base/48337/48343.5: 61% done. avg:  582.8, cur:  636.9 kByte/s. ETA: 10m36s

I get no idea from this which actual file is being uploaded, as there are many files with path ending with "lib/postgresql/9.4/main/base/48337/48343.5"

**Comment by rjgough** [comment]
I would like to see this too on -vv(v) passed options

**Comment by manfromafar** [comment]
Any word on this being added soon? 
It's kind of annoying have multiple files that end in the same format and not knowing exactly where the copy is at

**Comment by soofuzz** [comment]
going to +1 this also. I dont need the FULL path. But atleast the complete file name during the transfers. 

maybe using an option like --fullpath --filename to differentiate between displaying the Absolute path or just the full name of the file being uploaded/downloaded/checked etc.

**Comment by WillGunn** [comment]
I added a PR that’s allows arbitrary length file paths, and I’m using it successfully as a local patch right now.

**Comment by ncw** [comment]
The new flag can be found  here

https://beta.rclone.org/v1.39-020-g6d333da6/ (uploaded in 15-30 mins)

It is called `--stats-file-name-length`

**Comment by allanlaal** [comment]
thank you!

**Comment by allanlaal** [comment]
why not make this default behaviour? :)

**Comment by ncw** [comment]
@allanlaal The log output is supposed to look nice on the terminal that is why...

Anyway you can set `RCLONE_STATS_FILE_NAME_LENGTH=0` in your environment if you wish that to be on all the time.

**Comment by allanlaal** [comment]
other *nix commands don't truncate their output, that what `cut` is for ;)
