### ISSUE TITLE
Create version file in beta.rclone.org

### ISSUE THREAD

**Issue by ghost** [ncw/rclone#1216]
The new rclone-beta-latest-*-.zip links are very useful for updating by script, but it would be nice if there was a small text file in the folder like version.txt or something containing the latest version so you could avoid downloading if you already have the latest version.

**Comment by ncw** [comment]
That wouldn't be hard...

I guess you could use ETags also...

**Comment by xerrni** [comment]
It`s already implemented. 
https://beta.rclone.org/version.txt
@ncw
I think you can close this issue.

**Comment by ncw** [comment]
Thanks @xerrni .  We also have the [script install which uses this file](https://rclone.org/install/#script-installation)
