### ISSUE TITLE
acd: implement optional interfaces

### ISSUE THREAD

**Issue by ncw** [ncw/rclone#122]
Implement these for Amazon Cloud Drive
- [ ] Copier - Maybe patch the parents to include multiple parents? See below
  - there isnt an API for a straight forward copy though.
  - the file has to have the same name so impractical to implement (see @breunigs comment below)
- [ ] Mover - PATCH the node to change the parent directory
- [ ] DirMover - PATCH the directory to change the parent directory

**Comment by klauspost** [comment]
There isn't any server-side copy, but the other two have server support.

Also `SetModTime` should be implemented, if that is possible. The file PATCH function documentation states *"The allowed fields to updates are name, labels, description"*.

**Comment by ncw** [comment]
@klauspost my reading of that was that `SetModTime` wasn't possible, but if it is that would elevate ACD to first class supported file system.

**Comment by E6L** [comment]
I propose to split this ticket - one for "Mover" and "DirMover" and one for "Copier". I think "Mover" and "DirMover" are easier to implement; and canbe very helpful for anyone using amazon cloud drive for backups.

**Comment by E6L** [comment]
[doc](https://developer.amazon.com/public/apis/experience/cloud-drive/content/nodes) -> Files -> Resource Model  indicates a file has a "parents" property which is "{String...} List of parent folder Ids.". Suggesting a File can have multiple parents. Is this a way to implement server side copy?

**Comment by ncw** [comment]
@E6L thanks for the note about the duplicate issue. 

Interesting idea about making multiple parents - yes that would make a copy sort of like taking a hard link in Unix. I wonder what delete does whether in would just remove one of the links - you'd probably have to unmatched it to delete a multiple linked file.

**Comment by breunigs** [comment]
implementing the `Copier` interface works as long as the file name is the same. All future renames will have to account for this and then maybe do an actual download+reupload to rename a "copy". I.e. this works differently from how hardlinks on POSIX filesystems work.

Also, to delete a file in multiple locations from one parent, you'd just have to remove that parent and leave the others. However, if you remove all parents from a file, it is instead attached to the *root* of your ACD – regardless of where rclone's remote on ACD is located. I think the root folder id is then again present when you refresh the metadata, but I didn't check.

Either way, implementing a proper copy is going to be leaky into all sorts of other interfaces.

**Comment by ncw** [comment]
@breunigs Well spotted :-(  I think all those nasty corner cases make Copy impractical :-(  However Move is a very useful primitive.
