### ISSUE TITLE
Cannot exclude folder

### ISSUE THREAD

**Issue by lv913** [ncw/rclone#1225]
Hi ncw, I'm trying to work with filters on version 1.35 (Linux ARM).
I've the following directory structure:

Foto (under /media/backup)
| - 2013-1
| - 2013-2
| - ...
|  - Archivio

I'm trying to launch a sync of all jpg files contained on "Foto" and subdirs, but excluding "Archivio" (for that I'd use a separate "copy" action).
My command line has been up to now:

`rclone --bwlimit=40k --include '*.[Jj][Pp][Gg]' --exclude 'Archivio/**' --log-file=/root/backup_amazon/log_backup_08-03-2017_2106.log --dry-run sync /media/backup/Foto/ amazon:Foto`

Unfortunately, in the log file, I see that rclone would have tried to copy also files on "Archivio" folder. How can I effectively exclude it from the sync?

Thanks.

Ps. your software is really great!

**Comment by ncw** [comment]
Mixing --include and --exclude on the command line is a bit hit and miss due to the command line parser! This is mentioned in the docs: http://rclone.org/filtering/#repeating-options

Either covert them all to --filter, eg 

    --filter '- Archivio/**' --filter '+ *.[Jj][Pp][Gg]' 

Or use --filter-from which is probably what I'd do

**Comment by lv913** [comment]
Thanks, but I still have some problems...
Look here:

`rclone ls --filter-from filter-backup.rclone --dump-filters amazon:`

filter-backup.rclone has:

```
+ *.[Jj][Pp][Gg]
- **/Archivio/**/*.*
```
About the last row, I also tried `'- Archivio/**'`, `'- **/Archivio/**'` but without difference.

The output is:

```
--- start filters ---
--- File filter rules ---
+ (^|/)[^/]*\.[Jj][Pp][Gg]$
- (^|/).*/Archivio/.*/[^/]*\.[^/]*$
--- Directory filter rules ---
+ ^.*$
--- end filters ---
...
  1331216 Foto/Archivio/2006-2012/Eventi/Umbria 08_19-08-06/P1010698b.jpg
```
  
That file should be skipped, being it located in "Archivio" folder.
What would you suggest?

Thanks!

**Comment by naeloob** [comment]
That's not what @ncw has told to you.
The rules apply in order so, if you dont want nothing from Archivio you must put first the line "- Archivio/**" and down the line "+ .jpg"

So try filter-backup.rclone as : 
- Archivio/**
+ *.[Jj][Pp][Gg]

**Comment by lv913** [comment]
Thanks, now it's clear.
I was approaching it with TSM style, reading rules from the bottom to the top... my fault.

Bye!
