### ISSUE TITLE
Enhancement: pull config information from variables and/or stdin

### ISSUE THREAD

**Issue by internetimagery** [ncw/rclone#1227]
Hi!

Firstly this is amazing software. Love it, and use it all the time!

Would it be possible to support config information coming in through stdin / env variables?

So for instance, we currently have:

`rclone copy src dest --config configfile.txt`

We might support something like:

`cat configfile.txt | rclone copy src dest --config PIPE`

Or:
```
export RCLONE_ACCESS_ID=numbers
export RCLONE_ACCESS_SECRET_KEY=jargon
rclone copy src dest
```

**Comment by naeloob** [comment]
AFAIK at least Betas can get conf options from env variables.

**Comment by internetimagery** [comment]
@naeloob thanks! After digging much deeper I noticed [this here.](https://github.com/ncw/rclone/blob/b2a4ea9304644c6ed2a7f541562ecb93b79153c9/docs/content/docs.md#config-file) Pretty awesome.

Unfortunately, trying out the code in the example doesn't work, leaving me with: `2017/03/10 02:40:57 Failed to create file system for "MYS3:": didn't find section in config file`

Has this been fixed since version 1.35?

Also the naming is inconsistent:

> To find the name of the environment variable, you need to set, take RCLONE_ + name of remote + _ + name of config file option and make it all uppercase

But the example uses RCLONE_ + CONFIG_ + name of remote + _ + config option.

> `$ export RCLONE_CONFIG_MYS3_TYPE=s3`

I'll gladly fix that doc issue if I know which option is supposed to be correct. (I assume RCLONE_CONFIG_... is correct?).

**Comment by ncw** [comment]
You'll need a beta for this to work - see beta.rclone.org - the 1.36 release with this in is imminent!

**Comment by internetimagery** [comment]
@ncw Can't wait! 😀
