### ISSUE TITLE
embed rclone ?

### ISSUE THREAD

**Issue by mh-cbon** [ncw/rclone#1229]
Hi,

I d like to know how you consider a third party should proceed to embed rclone within another GO project.

Should i use the internal API, or am i better suited to parse the cli output ?

Currently i m working on a small gui, using rclone under the hood, its written in go for the server part.

I diged the source a bit, but could not find a quick and easy way to re use rclone as an API.

On the other hand i found i could simply parse the output (with -vv) to get a whole detailed set of information about the progress.

Thus i made a cli output parser to transform the raw text into JSON objects, 
and yes that works, but it will give some little trouble that i d like to get ride, 
- i will have to pack rclone exe file into my app (working, just little weird imho)
- i will 1+[all transfers] running process on the target system (some waste in here)

So yeah, just like to know if you any remarks or recommendations.

Thanks!

**Comment by ncw** [comment]
I haven't designed the rclone API to be re-used, except from within rclone.  It is possible though - I often write little scripts embedding rclone.

What I'd like to do is fix #633 - you can see some code there.

That would enable you to call rclone from within your binary.

With a bit of thought, it would be possible to make an API so you could do what you want...

**Comment by mh-cbon** [comment]
Thanks! I ll give it a check.
