### ISSUE TITLE
[Feature] RESTful API and web application front end

### ISSUE THREAD

**Issue by jdahmen** [ncw/rclone#1230]
_I wanted to put this here officially so that it was known someone is working on an API and front end, but also so that I could get some feedback._

# Purpose
To provide a more user friendly way of interacting with rclone, and setting up tasks. While the CLI is solid, many users may want to carry out more complicated tasks which traditionally have required Cron jobs and scripting. A GUI would also allow for more interactive information such as progress statistics and granular control over what would normally be a very long list of CLI parameters.

# The idea
I'm working on a RESTful API so that others can hit an always active rclone instance directly. In the beginning running the server will be a command line option. Maybe later, it could be made into a daemon.  At a real high level, there would be the API endpoints, a manager for rclone operations, and then web based front end, all of which stores persistent data in a database.

# Breaking it down
### Front end
The biggest addition to rclone's current library set would be that of [Angular (v2+)](https://angular.io/). I've been writing web applications in Angular about a year now, and when combined with Webpack, it makes for a great build system with a lot of options. I'm also preferential to [Twitter's Bootstrap](http://getbootstrap.com/) as a quick way to build out a clean UI.
### API endpoints
I'll use Go's existing `net/http` to build out some concurrent endpoints. In order to get a minimum viable product (MVP) across the finish line, I'll probably forgo authentication at first, and add it in later. Since this will initially be a command line option, those who consider it too much of a security risk will not be obligated to run in. All endpoints will use the RESTful model of `GET`, `PUT`, `POST`, `DELETE`, etc...
### Manager
To support operations running outside a single user's session, a process manager will need to be made. This manager will interface directly with the rest of rclone, translating user tasks into operations, and operation data into user viewable information that is pushed to the front end. The manager will also implement a few additional features, such as scheduling.
### Database
Some sort of database will be needed to track persistent data (jobs, users, options, etc). At the moment I'm partial to [SQLite](https://www.sqlite.org/), but I'm open to suggestions.

_Pros:_ It's lightweight, portable, and requires not user setup.
_Cons:_ It doesn't have as many features as some of the bigger names, nor is it as strict.

**Comment by tynor88** [comment]
Sounds interesting. [Duplicati](https://github.com/duplicati/duplicati) also has a Web UI, maybe you can use it as an inspiration.

**Comment by ncw** [comment]
Do you see this as being a separate app to rclone?  Or an option or command for rclone?

If it isn't a separate app, then it should probably be a command `rclone webui` say.

To be part of rclone it will need to not use any C components which will rule SQLite out unfortunately.

**Comment by vampywiz17** [comment]
i open a ticket here https://github.com/mmozeiko/RcloneBrowser/issues/38,

it is similar request...

**Comment by mmozeiko** [comment]
There are some good go only simple databases, for example: https://github.com/boltdb/bolt

**Comment by mh-cbon** [comment]
@jdahmen Hi, i m interested into that too.

I taken that as an exercise and made a quick and simple http api. 
I made a frontend on top of vue, but imho, it does not really matter.
I did not give a damn about a robust db, i used some json files so far.

Anyhow, i d just like to put the idea that, imho,

- if rclone embed the http api, that s a great simplicity for anyone else
- the frontend, imho should not be embedded into rclone, it should be left open to the developer to add rclone as a dependency and he will decide how to pack that all.

**Comment by jdahmen** [comment]
@ncw, I was thinking this would be packaged with rclone as a command line options. `rclone webui` sounds good to me. To @mh-cbon 's point, I see what you're saying, however I disagree. The way I see this progressing is it will be built as a part of rclone. At least for the time being. A well written front end and a well featured API go hand in hand. And by getting feedback on the web UI, I think it will influence some of the API's later features. If down the road @ncw or the community decide it doesn't fit, I'd be happy to spin it off into a separate project and host it there. However, for now I think it would benefit the most people just to package them together. If in the mean time other developers decide they can build a better UI, there is nothing stopping them from building one. I'd even be happy to add a command line option to disable serving the static front end files and only serve up the API.

@ncw: When I use flags for the server, such as `--port` or '--host`, where should I put those? In `rclone/cmd/webui/webui.go` with the option? Or `rclone/fs/config.go`?

Also, I was looking around for alternatives to SQLite and @mmozeiko 's suggestion is a good one. Either Bolt or a JSON-esque persistent storage tool would do nicely. To confirm, do these meet the criteria?

**Comment by ncw** [comment]
> When I use flags for the server, such as --port or --host, where should I put those? In rclone/cmd/webui/webui.go with the option? Or rclone/fs/config.go?

In `cmd/webui/webui.go` then they will be specific to that command.

I've been looking at boltdb for some other purposes in rclone, so that would be a good choice.  JSON files would be fine too.

**Comment by mattheys** [comment]
Is this dead or in a fork? I'm interested in this too.

**Comment by jdahmen** [comment]
@mattheys; I apologize. I started pursuing this around the exact same time that Amazon changed their "unlimited" cloud storage, which was my main purpose for using `rclone`. I forgot to follow up with this fork.

So, to answer your question, yes it is dead.
