### ISSUE TITLE
GCS permission issue

### ISSUE THREAD

**Issue by lavalamp** [ncw/rclone#1232]
When using a service account with GCS, it'd be nice to give the service account only storage object creater & viewer. Unfortunately, one must currently also give it the *project* viewer role due to this function:

https://github.com/ncw/rclone/blob/v1.35/googlecloudstorage/googlecloudstorage.go#L456

This assumes a bucket get failure is due to the bucket not existing, when it is actually due to lack of permission (even though one has permission to write to the bucket).

(I might send a PR to fix but don't count on it :) )

**Comment by ncw** [comment]
A PR would be much appreciated!

**Comment by lavalamp** [comment]
It appears that it now works, whether rclone changed or GCS is just more granular now, I'm not sure. I was able to give a service account only create and list permissions and use rclone to write a file. I have a patch that makes it work even if you don't give it list permissions, but it's not clear that's actually useful.

**Comment by ncw** [comment]
Yes this was fixed in 0cb5c4aa730118fbf0c25f3636abbcc4c36e8452
