### ISSUE TITLE
Include filters don't seem to work

### ISSUE THREAD

**Issue by tcf909** [ncw/rclone#1233]
```
rclone --config /etc/rclone/rclone.conf copy "/data/.Local/Movies/Allegiant (2016)/" "ACD_VAULT:/Media/Movies/Allegiant (2016)/" --include "/Allegiant (2016) - [1080p, x264, AAC, BluRay].mkv" -vv --dump-filters
--- File filter rules ---
+ ^Allegiant \(2016\) - [1080p, x264, AAC, BluRay]\.mkv$
- ^.*$
--- Directory filter rules ---
- ^.*$
--- end filters ---
2017/03/12 10:34:33 DEBUG : Allegiant (2016) - [1080p, x264, AAC, BluRay].mkv: Excluded from sync (and deletion)
```

It looks like the filter is exactly what it needs to be to include the file in the copy...but it doesn't pick it up.

```
2017/03/12 10:37:45 NOTICE: Config file "/root/.config/rclone/rclone.conf" not found - using defaults
rclone v1.35-164-g488353cβ
```

**Comment by tcf909** [comment]
Looks like inputs aren't being properly escaped. I see that (). are all escaped but not [ ].

used
```
rclone --config /etc/rclone/rclone.conf copy "/data/.Local/Movies/Allegiant (2016)/" "ACD_VAULT:/Media/Movies/Allegiant (2016)/" --include "/$(printf "%q" "Allegiant (2016) - [1080p, x264, AAC, BluRay].mkv")" -vv --dump-filters
```
To work around for now.

**Comment by ncw** [comment]
Things passed to an `--include` filter are shell globs, so can be `*.jpg` or `file[123].txt`.  `[` and `]` are metacharacters.

You probably want to use  `--files-from` which just reads file names from a file without interpreting them as a glob.

**Comment by tcf909** [comment]
Makes more sense. Felt like a reg expression more than a glob.

Ideally I would be using copyto and move to in my scripts, but as a work
around to that other issue I posted Im using copy and move with dynamic
include. Would rather save the file writing and reading for each file at
this point.

I will say though, 1.36 beta is looking really nice overall. Those buffers
really seemed to help with Plex playback.

**Comment by tcf909** [comment]
I'll go ahead and close. Thanks Nick.
