### ISSUE TITLE
[Mount] can't rename non empty directory

### ISSUE THREAD

**Issue by Powerbless** [ncw/rclone#1234]
Hello.

Using newest Rclone Beta under Linux Alpine 64bit

Command:
rclone mount --allow-non-empty --allow-other --checkers 10 encrypt: /med
ia/EACD/ &

when i try to RENAME a folder then linux print this::

`2017/03/12 17:28:36 _Kodi/SD Filme/Der Prinz hinter den sieben Meeren (1982).(tt0084535).SDp..mp2.2: Dir.Rename can't rename non empty directory
2017/03/12 17:28:36 _Kodi/SD Filme/Der Prinz hinter den sieben Meeren (1982).(tt0084535).SDp..mp2.2: Dir.Rename can't rename non empty directory`

i think there is a problem with the Folder name? because when i try to rename Folder "Film.1990" to "Film.1990a" works fine. EDIT: but after a refresh, the folder is renamed to the old name....

**Comment by ncw** [comment]
Can you check you are using the latest beta please - that error text doesn't exist in the code any more.

**Comment by Powerbless** [comment]
I have again downloaded the latest BETA.
the renaming and deleting now WORK!

my steps: (for other users who have the problem)
after rclone mount command run this:
chmod 777 /media/eacd/

and in smb.conf i added:
[global]
dos charset = cp866
unix charset = UTF8
display charset = UTF8

now, renaming, deleting and all the other works

**Comment by ncw** [comment]
Excellent :-)
