### ISSUE TITLE
The new --backup-dir option does not work with OneDrive if backup-dir does not exist, or files already exist in backup-dir

### ISSUE THREAD

**Issue by traynier** [ncw/rclone#1236]
> What is your rclone version (eg output from `rclone -V`)
v1.35-167-g0faf827β

> Which OS you are using and how many bits (eg Windows 7, 64 bit)
Windows 10 64 bit

> Which cloud storage system are you using? (eg Google Drive)
OneDrive

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
See below.

As requested, a follow-up from #1224.

I get unexpected results when the backup-dir does not exist on the destination.

i.e. do the following:

; create a file in the test folder and copy folder to onedrive
mkdir test
echo 1 >> test/test.txt
rclone copy ./test one:test --backup-dir one:testold -vv

; change the file and run the copy again
echo 2 >> test/test.txt
rclone copy ./test one:test --backup-dir one:testold -vv

At this point I would expect one:testold/test.txt to contain the old version. But it does not use the backup-dir, and instead the old test.txt ends up in the root folder as one:test.txt

If the one:testold directory exists then it does work as expected. However I had to manually create it (I used rclone browser).

Continuing from that, if I make another change

; change the file and run the copy again
echo 3 >> test/test.txt
rclone copy ./test one:test --backup-dir one:testold -vv

it then fails:

Failed to copy: test.txt: async operation "ItemCopy" returned "failed"

presumably due to the file one:testold/test.txt already existing?

Repeating the test for an encrypted onedrive remote get slightly different result; if the backup-dir does not exist you just get an error instead of the old file ending up in the root folder:

Failed to copy: 002i3q2u20jlcd0ietvoa93ri8: async operation "ItemCopy" returned "failed"

But otherwise works the same (works if no file in testold, fails if file already in testold).

**Comment by ncw** [comment]
I've fixed this in

http://beta.rclone.org/v1.35-173-g986a285/ (uploaded in 15-30 mins)

Let me know if it doesn't work for you!

Thanks

Nick

**Comment by traynier** [comment]
Working great in the new beta.  Thanks!

**Comment by ncw** [comment]
Thanks for testing :-)
