### ISSUE TITLE
Feature Request: drive-templink-threshold

### ISSUE THREAD

**Issue by jrarseneau** [ncw/rclone#1239]
Hi @ncw 

As you know, many of us are trying to find a way to use rclone mount with Google Drive and Plex without being banned. There is an issue for caching which may/may not fix this, but after deconstructing another tool that does not exhibit bans when using Plex (https://github.com/thejinx0r/node-gdrive-fuse), it would appear that the files are accessed using that tool via their HTTPS link and not via the API directly.

Would it therefore be possible to create similarly to the `acd-templink-threshold` to create a `drive-templink-treshold` feature so that rclone will always use HTTPS to get the file over a particular threshold.

The idea being that if this attribute is set to `0` then rclone would always use the HTTPS link, which may very well save the bans for us Plex users.

Thanks!

**Comment by jaketame** [comment]
Happy to test this too :)

**Comment by jrarseneau** [comment]
Worse case, if this doesn't avoid bans, it would still be a good feature.

**Comment by Givemeyourgits** [comment]
All for it!

**Comment by NumberedThought** [comment]
Anything to avoid the bans

**Comment by ncw** [comment]
rclone downloads files from drive using the downloadUrl which is just a straight forward https fetch, but it does need authorization (I just tried it without).

I don't immediately see a way to generate a templink in the api docs - do you?

[api docs](https://developers.google.com/drive/v2/reference/files)

**Comment by jaketame** [comment]
Doesn't look that way.

From what I can see Plex is requesting the file to grab metadata info however google sees this as a full file download so when Plex is processing hundreds of files google thinks your downloading the whole file thus to avoid causing other users issue it bans you.

Only way round that would be to cache the metadata.

**Comment by ncw** [comment]
Caching the metadata is part of #897

**Comment by felixbuenemann** [comment]
Interestingly there seems to be a way to generate pre-authenticated urls, but I couldn't find any documentation on it.

If I play a file on Google Drive in Plex Cloud, it redirects to an URL that looks like:

```
https://<50-character-hex-id>-apidata.googleusercontent.com/download/drive/v3/files/<fileId>?qk=<base64-encoded-auth-string>
```

The URL support range requests, so it would be fully seekable.

**Comment by ncw** [comment]
@felixbuenemann is that in the v3 API?  I've only looked at the v2 API

**Comment by felixbuenemann** [comment]
The URL suggest it is part of the v3 API, but I couldn't find any documentation on it in the v3 docs. The endpoint mentioned is different from anything listen in [Download FIles](https://developers.google.com/drive/v3/web/manage-downloads) of the Drive v3 API Docs and the presigned URLs carry an expiration date which is likely encoded in the `qk` query parameter.

So unless someone can come up with some more info about this, it's not of much use right now.

**Comment by TripleFrequency** [comment]
Is there any update on this? I have been looking for information regarding signed URLs, but have had no luck yet. Temp links could be greatly beneficial for one of my projects.

**Comment by qnorsten** [comment]
This is really interesting. Is it possible to sniff the plexcloud traffic to see if we can figureout how to generate this type of links?

**Comment by TripleFrequency** [comment]
Unfortunately, it is server-side for Plex Cloud. I have contacted Google concerning signed URLs, but they couldn't provide help on the matter. I have also recently contacted a Plex employee regarding it, but doubt I will get a response. [This article](https://cloud.google.com/storage/docs/access-control/signed-urls) could be of use, but is only slightly related in that it uses Google Cloud Storage instead of Drive.

**Comment by TripleFrequency** [comment]
I wanted to provide an update on this:

Generating temp-links is actually quite easy.
Simply make the same API call, so
`GET https://www.googleapis.com/drive/v2/files/${FILE_ID}?alt=media&access_token=${CURRENT_ACCESS_TOKEN}`
So one example could be
`GET https://www.googleapis.com/drive/v2/files/0B4h...?alt=media&access_token=ya29.SxckzJk...`

This link then redirects to the links as described by @felixbuenemann, and as provided by Plex Cloud.

**Comment by jrarseneau** [comment]
Closing this as newer betas support caching which will fix the ban issues with rclone and Plex.
