### ISSUE TITLE
Is it possible to make only file names encrypted but keep folder names intact?

### ISSUE THREAD

**Issue by fragiledream** [ncw/rclone#1240]
> What is your rclone version (eg output from `rclone -V`)
1.35
> Which OS you are using and how many bits (eg Windows 7, 64 bit)
10 64Bit
> Which cloud storage system are you using? (eg Google Drive)
Amazon Cloud Drive

**Comment by ncw** [comment]
It would be possible with a bit of patching if someone wanted to have a go

**Comment by ishuah** [comment]
Please find a beta with the fix in: https://beta.rclone.org/v1.38-093-gc65734ee/ (uploaded in 15-30 mins)
