### ISSUE TITLE
Can't assign custom google drive api token

### ISSUE THREAD

**Issue by Tidyl** [ncw/rclone#1241]
> What is your rclone version (eg output from `rclone -V`)

rclone v1.35

> Which OS you are using and how many bits (eg Windows 7, 64 bit)

SSHed into Ubuntu 4.8.4-2ubuntu1~14.04.3. Executing from OSX 10.11.6

> Which cloud storage system are you using? (eg Google Drive)

Google Drive

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

rclone config with custom token

> A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
2017/03/15 06:59:58 Failed to configure token: failed to get token: Post 

https://accounts.google.com/o/oauth2/token: dial tcp: i/o timeout

**Comment by Tidyl** [comment]
I need this because when I was trying to upload I recieved.

 ```
   "domain": "usageLimits",
    "reason": "dailyLimitExceededUnreg",
    "message": "Daily Limit for Unauthenticated Use Exceeded. Continued use requires signup.",
```

**Comment by Tidyl** [comment]
For some reason when I tried to run it with -vv it just randomly worked... literally nothing different.

**Comment by ncw** [comment]
Glad you got it working!
