### ISSUE TITLE
[Solved] Backup of rclone conf file with crypt ?

### ISSUE THREAD

**Issue by vincegre** [ncw/rclone#1242]
Hi

I'm currently using rclone with full crypt to Google Drive (so everything is crypted on GDrive). I have backuped the two keys when I created that profile in rclone.
I noticed in the rclone config file it's not the same key (I guess they are manipulated so they are not easily readable). If I backup the rclone config file will it work on an other computer for the crypt part ? or does it use also random stuffs specific to computer where it's running ?

Thanks,

Vincèn

**Comment by Cr0nixx** [comment]
Just copied the .rclone.conf from a Debian server to my windows pc to try out Rclone Browser and yes the crypt storage works.

**Comment by vincegre** [comment]
Thanks for confirmation and fact it's also cross-platform :+1:

**Comment by ncw** [comment]
Glad it is all sorted :-)
