### ISSUE TITLE
Extend dedupe to support merging multiple directories

### ISSUE THREAD

**Issue by kubark42** [ncw/rclone#1243]
> What is your rclone version (eg output from `rclone -V`)

v1.35-99-g6fc114d

> Which OS you are using and how many bits (eg Windows 7, 64 bit)

macOS

> Which cloud storage system are you using? (eg Google Drive)

Google Drive

---

[Dedupe](https://github.com/ncw/rclone/blob/v1.35/docs/content/commands/rclone_dedupe.md) removes identical files, but sometimes when doing several `rclone copy` simultaneously, Google Drive will create several directories. This is a race condition, as it depends on whether the directory already exists or not when an individual `rclone` process is launched.

It would be nice if dedupe allowed merging of those directories.

**Comment by ncw** [comment]
I've noticed this too!

**Comment by ncw** [comment]
I've implemented this in - please test!

https://beta.rclone.org/v1.37-073-gbfe812ea/ (uploaded in 15-30 mins)

**Comment by DurvalMenezes** [comment]
I'm getting the "Failed to dedupe [...] can't merge directories" with rclone v1.44 (linux amd64 version running on Ubuntu 18.04 with local on ZFS and remote on an encrypted Google Drive).

Is it a regression?

**Comment by ncw** [comment]
> I'm getting the "Failed to dedupe [...] can't merge directories" with rclone v1.44 (linux amd64 version running on Ubuntu 18.04, with remote on an encrypted Google Drive).
> 
> Is it a regression?

Possibly!  Can you please make a [new issue on github](https://github.com/ncw/rclone/issues/new) with a log with `-vv` and we can work it out - thank you!

**Comment by DurvalMenezes** [comment]
> > I'm getting the "Failed to dedupe [...] can't merge directories" with rclone v1.44 (linux amd64 version running on Ubuntu 18.04, with remote on an encrypted Google Drive).
> > Is it a regression?
> 
> Possibly! Can you please make a [new issue on github](https://github.com/ncw/rclone/issues/new) with a log with `-vv` and we can work it out - thank you!

Right away, Nick!
