### ISSUE TITLE
rclone mount should unmount folder on exit

### ISSUE THREAD

**Issue by j-vizcaino** [ncw/rclone#1244]
## Environment

* Linux 64 bits
* rclone v1.35

## Description 

Killing (or interrupting using Ctrl+C) `rclone mount` do not unmount the target folder.
To solve this, one needs to run `fusermount -u <dir>`

Handling SIGINT and SIGTERM signals in order to properly unmount the folder would be the way to go.
Don't know if there's a proper way (ie. using FUSE bindings) to do this or if `rclone` simply needs to exec `fusermount -u -z`

**Comment by ncw** [comment]
That is a good idea.  Do other FUSE tools do this do you know?

What should rclone do if the mount is in use?  Just do a `fusermount -u -z` and let the user deal with the consequences?

**Comment by j-vizcaino** [comment]
That's how gocryptfs does it but I am not really found of this: it works
but is not portable (hello MacOS) and using the -z flag is lazy unmount.
Maybe looking at how mergerfs does this would add another alternative. I'll
dig into that.

**Comment by tcf909** [comment]
as a work around I just use:
```
trap 'fusermount -u -z -q $MOUNT_POINT' INT TERM EXIT
```

-z for lazy (in case it's being used
-q for quiet since I want lazy
-u for unmount

In my mount scripts. Basically does the same thing Nick would need to do to catch the trap and exit cleanly in the go code.

**Comment by ncw** [comment]
rclone mount now does this :-)
