### ISSUE TITLE
Invalidate directory cache on remote changes

### ISSUE THREAD

**Issue by tcf909** [ncw/rclone#1245]
I was pretty sure that RCLONE invalidated the directory cache one a remote change (copy, move, mkdir, etc)...

As of 164, at least with the copy command, this does not seem to be the case any longer:

```
rclone mount REMOTE:/Vault /mount/.Vault
rclone copy /mount/.Local/test REMOTE:/Vault/test --include "/testfile.file"
ls /mount/.Vault (empty)
rclone ls REMOTE:/Vault (shows test/testfile.file)
```
rclone v1.35-164-g488353cβ

Not a high priority, but I thought I'd let you know just in case.

**Comment by ncw** [comment]
> I was pretty sure that RCLONE invalidated the directory cache one a remote change (copy, move, mkdir, etc)...

If you make the change through the mount it will, otherwise you'll have to wait for the --dir-cache-time

**Comment by tcf909** [comment]
Ahh, so if I use copy or copy to it's not affecting some shared memory
struct? Makes sense. Thank you sir.
