### ISSUE TITLE
Running 'rclone move' command in etc/rc.local doesn't work

### ISSUE THREAD

**Issue by buttpain** [ncw/rclone#1248]
I'm trying to have rclone move files from a folder on boot using the command by inserting the command to rc.local

'rclone move /root/plexorigin/tv_shows Google:/plex/tv_shows' 

For some reason it doesn't seem to do anything. But if I was to run this command manually in putty then it works in an instant. 

EDIT: Forgot to mention it also doesn't work when I have deluge run the command on torrent completion.

What is your rclone version - rclone v1.35

Which OS you are using and how many bits - Ubuntu Xenial (16.04 LTS)

Which cloud storage system are you using? - Google Drive

**Comment by ncw** [comment]
You need to get some logging in there to find out what is happening

    rclone move /root/plexorigin/tv_shows Google:/plex/tv_shows >>/tmp/rclone.log 2>&1

At a guess it will be because rclone can't find the home directory because HOME isn't set...

**Comment by buttpain** [comment]
100% right, i'm retarded thanks :)
