### ISSUE TITLE
Use Content-Length instead of Transfer-Encoding: chunked

### ISSUE THREAD

**Issue by nodughere** [ncw/rclone#125]
When rclone transfers data it uses Transfer-Encoding: chunked instead of Content-Length: <objectSize> when sending data.

This causes 2 issues.
1. When transferring a file that is larger than the Max Object Size with Transfer-Encoding, the transfer does not fail until after the data has been transferred exceeding the Max Object Size.  However, when using Content-Length header instead a 413 Request Entity Too Large can be passed back immediately, and rclone can save the users bandwidth.

2. Since the size is not transmitted, Rclone, must check the object after transmission with a HEAD request to ensure the size is correct and if wrong delete the object.  With Content-Length header if the data transmitted does not match the Content-Length given a 400 Bad Request (The data is invalid) will allow rclone to know a retransmit is required, and a delete will not be necessary as the object was not written.  This will also greatly aid systems like Swift that are eventually consistent, as the head after the transmission may not return data even though a 200 was given.  

When using Content-Length the 200 given for a successful transfer will be trust worthy improving the speed and efficiency of rclone.

Thanks for the great software,
Doug Soltesz

**Comment by ncw** [comment]
That is a good idea - thanks.  When doing an upload with rclone we always know the size of the object - telling it to the remote in a `Content-Length` header seems very sensible.  It might be a little tricky to implement though due to the layers involved.

rclone does that additional request to read the MD5SUM as well as the length so it can't stop doing it unfortunately.  Swift has very good integrity checking on upload with MD5SUMs, but not all the other cloud storage systems do.

**Comment by nodughere** [comment]
I didn't realize that a MD5SUM was performed during upload and compared on the head after successful upload.  That is a good implementation.

I am glad to test your substitution of Transfer-Encoding for Content-Length or get you access to a Swift VM where you can run Swift & S3 API testing and see the headers in the proxy logs.

Please do note that there is a possibility that in an eventually consistent system such as Swift that after the update of an object, heading of the object may return the old data.  Maybe you could make a switch called --verify that the user could set to false if they knew that the operations were to a system that was eventually consistent.

Doug

**Comment by ncw** [comment]
@nodughere Thanks for the offer of a test swift.  I wrote and maintain the [swift library](https://github.com/ncw/swift) for Go.  I'd be interested if you have access to a swift installation with v3 auth?

I note your concern about the eventually consistent system causing a problem.  In practice (and through 100s of runs of the unit tests) it doesn't except very occasionally.  If it does detect a problem like that then rclone will just retry the transfer.
