### ISSUE TITLE
Detect file sizes changing during Copy

### ISSUE THREAD

**Issue by ncw** [ncw/rclone#1250]
In Copy, check to see if can read more bytes from the reader after the copy has finished.

If this is the case, then make an error - "file size changed while copying" and abort the copy.

This would have detected #902 also.

**Comment by daylightbrightledlight** [comment]
Maybe instead of aborting the copy, it should spit out an error and move onto the next copy. This is if you're assuming there are multiple files being copied.

**Comment by ncw** [comment]
Note that there are some similar [discussions on the forum](https://forum.rclone.org/t/backup-with-file-in-writing/4631/2) - I came up with this

> What I'm imagining is that during a transfer in the local backend, rclone would check the size and modification time of the file it is transferring every 10s (say).  If the size or mod time differs from when the transfer was started then it will abort the transfer.

That might fix this issue better as it will detect the change before rclone gets to the end.

**Comment by ncw** [comment]
This fix should be in [the latest beta](https://beta.rclone.org) in 30 mins or so!
