### ISSUE TITLE
mount command seems to be scanning the entire amazon cloud drive incessantly

### ISSUE THREAD

**Issue by garypaduana** [ncw/rclone#1256]
> What is your rclone version (eg output from `rclone -V`)

1.36

> Which OS you are using and how many bits (eg Windows 7, 64 bit)

macOS Sierra 10.12.3

> Which cloud storage system are you using? (eg Google Drive)

Amazon Cloud Drive

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

    $ rclone mount -vv ACD_crypt:/ Mounts/acd

> A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

    2017/03/19 23:36:11 DEBUG : file.mp3: Dir.Lookup
    2017/03/19 23:36:11 DEBUG : file.mp3: Dir.Lookup OK
    2017/03/19 23:36:11 DEBUG : file.mp3: File.Attr valid=1m0s ino=0 size=6117912 mode=-rw-r--r--

Literally every single file on my amazon cloud drive is appearing in the DEBUG output for the mount command after mounting and navigating to a single folder.  Folders that have no relation to the folder I'm in are being scanned.  rclone is consuming ~1MB/sec just scanning directory structures in other non-related directories.  It appears as if there is a way too optimistic fetch occurring for the directory structure of the remote.  I don't remember this happening in previous versions.

**Comment by ncw** [comment]
I suspect there is something scanning the mount.  

Use `lsof | grep Mounts/acd` to try to find out what.

**Comment by garypaduana** [comment]
It's definitely Finder doing this.  Just navigating to any folder within the mount will cause the entire rest of the remote to be scanned.   Commander One file browser does not exhibit this behavior.  Thanks for the tip.

**Comment by ncw** [comment]
Thanks for working that out
