### ISSUE TITLE
Store checksum in GDrive file properties 

### ISSUE THREAD

**Issue by kyl191** [ncw/rclone#1257]
GDrive supports properties on files (as per https://developers.google.com/drive/v2/web/properties). It looks like it would be a matter of hashing the file, and using the result as the JSON body of this request: https://github.com/ncw/rclone/blob/master/drive/upload.go#L62

**Comment by ncw** [comment]
Drive supports md5sum - I'm not sure why we would want to store the checksum on a property given that?

**Comment by kyl191** [comment]
Ah - I was under the impression Drive didn't support any sort of hash.

Does it also work for crypted backends?

**Comment by nagualcode** [comment]
My rclone sync gdrive local job is treating changed files as unchanged ( and not downloading them) as of now.

**Comment by ncw** [comment]
@nagualcode open a new issue with a log with -vv please

**Comment by kyl191** [comment]
Found my answer in https://github.com/ncw/rclone/issues/888#issuecomment-289411073, closing this.
