### ISSUE TITLE
these items in the changelog for 1.36 are not listed in the documention

### ISSUE THREAD

**Issue by left1000** [ncw/rclone#1258]
when reading:
http://rclone.org/changelog/
I see:
rclone check: Add --download flag to check all the data, not just hashes
rclone cat: add --head, --tail, --offset, --count and --discard

Then I go to:
http://rclone.org/docs/
and I see no explanation of these new commands/flags

I could guess about them, but ideally I think they should be given a write-up? if --download does what I think it does, it's going to be very useful for me, and help solve an issue I've had in the past, that I've been handling manually.

**Comment by ncw** [comment]
You can find docs for the cat command here

http://rclone.org/commands/rclone_cat/

And check here

http://rclone.org/commands/rclone_check/
