### ISSUE TITLE
Stats not showing when doing copy command

### ISSUE THREAD

**Issue by Synopis** [ncw/rclone#1263]
When filing an issue, please include the following information if possible as well as a description of the problem.  Make sure you test with the latest beta of rclone.

    http://beta.rclone.org/
    http://rclone.org/downloads/

If you've just got a question or aren't sure if you've found a bug then please use the [rclone forum](https://forum.rclone.org/) instead of filing an issue.

> What is your rclone version (eg output from `rclone -V`)
1.36
> Which OS you are using and how many bits (eg Windows 7, 64 bit)
Ubuntu 16.10
> Which cloud storage system are you using? (eg Google Drive)
Amazon Cloud, Google Drive
> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone copy --stats 10s "local/directory" "Amazon:/path/to/folder
> A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

2017/03/22 00:22:11 INFO  : amazon drive root 'Remote/folder: Modify window not supported
2017/03/22 00:22:11 DEBUG : amazon drive root ''Remote/folder: Reading ""
2017/03/22 00:22:11 DEBUG : amazon drive root 'Remote/folder: Finished reading ""
2017/03/22 00:22:12 DEBUG : amazon drive root ''Remote/folder': Reading "H-L/"
2017/03/22 00:22:12 DEBUG : amazon drive root 'Remote/folder': Finished reading "H-L/"
2017/03/22 00:22:13 DEBUG : E-G/ES).7z: Upload error detected but didn't finish upload: HTTP code 429: "429 Too Many Requests": response body: "{\"logref\":\"371b40c9-0e8d-11e7-8834-e7f23a952529\",\"message\":\"Rate exceeded\",\"code\":\"\"}" ("429 Too Many Requests")
2017/03/22 00:22:13 DEBUG : pacer: Rate limited, sleeping for 472.644968ms (1 consecutive low level retries)
2017/03/22 00:22:13 DEBUG : pacer: low level retry 1/1 (error HTTP code 429: "429 Too Many Requests": response body: "{\"logref\":\"371b40c9-0e8d-11e7-8834-e7f23a952529\",\"message\":\"Rate exceeded\",\"code\":\"\"}")
2017/03/22 00:22:13 DEBUG : E-G/E.7z: Received error: HTTP code 429: "429 Too Many Requests": response body: "{\"logref\":\"371b40c9-0e8d-11e7-8834-e7f23a952529\",\"message\":\"Rate exceeded\",\"code\":\"\"}" - low level retry 1/10
2017/03/22 00:22:13 DEBUG : pacer: Resetting sleep to minimum 20ms on success
2017/03/22 00:22:21 INFO  :
Transferred:   216.387 MBytes (16.969 MBytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:       12.7s
Transferring:
 *                     E-G/E  3% done, 3.625 MBytes/s, ETA: 8m59s
 *           E-G/ES.7z:  2% done, 3.296 MBytes/s, ETA: 11m37s
 *        E-G/E.z: 11% done, 1.645 MBytes/s, ETA: 2m37s
 * ... In).7z: 18% done, 2.676 MBytes/s, ETA: 1m26s

**Comment by Synopis** [comment]
Also happening on Windows.

**Comment by pcjonathan** [comment]
See #1180

**Comment by ncw** [comment]
You'll need to use `-v` to see the stats at the moment.  I'm investigating further in #1180 so I'll close this issue.
