### ISSUE TITLE
nil pointer error 1.36 and beta

### ISSUE THREAD

**Issue by gdog1212** [ncw/rclone#1265]
When filing an issue, please include the following information if possible as well as a description of the problem.  Make sure you test with the latest beta of rclone.

    http://beta.rclone.org/
    http://rclone.org/downloads/

If you've just got a question or aren't sure if you've found a bug then please use the [rclone forum](https://forum.rclone.org/) instead of filing an issue.

> What is your rclone version (eg output from `rclone -V`)
1.36 and beta 1.36-05-g216499d
> Which OS you are using and how many bits (eg Windows 7, 64 bit)
ubuntu linux vm amd 64
> Which cloud storage system are you using? (eg Google Drive)
amazon cloud drive
> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
./rclone lsd amazon:
> A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
can not get a log file off server quickly
![error](https://cloud.githubusercontent.com/assets/24951122/24179879/412f4a34-0e88-11e7-9255-ff8dc419d0d3.jpg)
nil pointer error

**Comment by ncw** [comment]
This looks like the config file has got corrupted somehow.

What does it look like?  Can you give me some idea (without pasting the secret token stuff!)

If you remake the amazon remote does it start working?

**Comment by ncw** [comment]
I'm going to close this issue now since we have put in workarounds to stop the config file getting corrupted.
