### ISSUE TITLE
Verbose output shut off in 1.36 by default?

### ISSUE THREAD

**Issue by Dedsec1** [ncw/rclone#1272]
Hey Nick, 

not sure if you meant to shut off the verbose output in 1.36 by any chance, seems when i run any command without -v i dont see anything when i try rclone sync, copy, move, just wanted to let you know incase you missed something before you pushed out 1.36 

Thanks 

Dedsec1

**Comment by pcjonathan** [comment]
See #1180. (FWIW, it's also in the release notes.)

**Comment by ncw** [comment]
Yes, this is working as intended to make rclone behave more like rsync.
