### ISSUE TITLE
Google Cloud Platform (GCP) Cloud Storage's `gsutil` vs `rclone`

### ISSUE THREAD

**Issue by danemacmillan** [ncw/rclone#1275]
This is not a bug. I wanted to let you, @ncw, know how amazing `rclone` has been. I originally got it for my own hobbyist reasons to transfer data into GDrive, but now use it for critical business operations.

For work, I use GCP to host our infrastructure. I've been using Google's official `gsutil` tool to interact with their cloud storage offering. It's really slow, especially when running their `gsutil -m rsync -r [source] [dest]` command. Its purpose is to sync between a source and destination. We have 2.6M tiny `jpeg` files, spanning thousands of directories. These assets grow every day, and they need to be in sync. The operation also needs to run multiple times an hour. `gsutil` takes 46 minutes to run a sync on these assets, which makes that requirement impossible. `rclone` takes five.

The difference in performance is incredible.

```
Transferred:   195.364 kBytes (578 Bytes/s)
Errors:                 0
Checks:           2610503
Transferred:           22
Elapsed time:     5m45.8s
```

For anyone using the Google Cloud Storage (GCS) `gsutil` tool to sync data between two locations, I *highly* recommend trying `rclone`. 

@ncw This tool is officially part of my toolbelt. It's fantastic. Thanks man!

Feel free to close this. I just wanted it to get picked up by search engines for future queries into the performance of these tools.

**Comment by ncw** [comment]
Thanks for the feedback, always nice to hear from happy users :-)

**Comment by egarciarivera** [comment]
Indeed I found this while searching for alternatives to gsutil. Performance is excellent and far beyond gsutil cp or rsync speeds. Great tool.
