### ISSUE TITLE
New sync method in v1.36 and Backblaze B2 Class C Transaction Cap

### ISSUE THREAD

**Issue by rasssimo** [ncw/rclone#1277]
The new sync method in v1.36 is creating a lot of class C transactions in Backblaze B2 and using up the daily free allowance (2,500 transactions). Syncing just under 500,000 files is creating nearly 60,000 transactions - if I apply the --old-sync-method flag about 400 transactions are created.

See [forum thread](https://forum.rclone.org/t/new-sync-method-in-v1-36-and-backblaze-b2-class-c-transaction-cap/)

**Comment by talkingpixels** [comment]
I'm having a similar issue. I have about ~275GB of data synced from Dropbox to B2 (~200,000 files in ~35,000 directories). I'd like to have a daily cron run to keep it up to date. However, each time I run rclone without --old-sync-method, it uses ~10,000 transactions.

Although the cost is negligible for a day, over a year this would nearly double the cost of my B2 back-up.

Keeping some kind of low-transaction method, without too higher price to pay in terms of speed and memory usage, would be ideal for use-cases similar to this. I understand this might be asking too much though! :)

**Comment by jasongill** [comment]
I am having this issue as well; on 1.35, our Class C costs were free. On 1.36, we are spending ~$20 per day in Class C transactions - more than we spend in storage! - so our bill has more than doubled.

We do have a large number of files (and a large number of directories). Is it possible to create some kind of "cache" file (upon first run of a new Rclone version), and store it in the root of the bucket - then use that cache instead of scanning each directory with every run?

Obviously this would become a problem if you were manipulating files outside of rclone, but for many enterprise users like us, we just use B2 for rclone storage only.

**Comment by jwiegley** [comment]
I agree with @jasongill: when using rclone mainly for archival purposes, any optimization the new sync method is trying to gain in terms of speed is not only not a benefit, it comes at a $$ cost.

**Comment by ncw** [comment]
I'm just about to fix this, so watch this space! Use --old-sync-method in the mean time, but I've pushed my changes you'll use --fast-list.

**Comment by jasongill** [comment]
@ncw thank you so much for looking at this. We are faced with "spend thousands of dollars per month on Class C transactions" or "struggle with memory usage" so I'm very thankful that you've hopefully found a good middle ground

**Comment by jwiegley** [comment]
Yes, this is all about "choosing which resource you want to spend".

**Comment by ncw** [comment]
Please try using this beta with the --fast-list flag.  It will still use more memory that without but it will definitely use less transactions.

https://beta.rclone.org/v1.36-185-g64662bef/ (uploaded in 15-30 imins)

**Comment by joshslater** [comment]
has --fast-list flag made it into a release yet? This is affecting me on B2 as well...

**Comment by joeytwiddle** [comment]
Yes `--fast-list` is in release. I can confirm it has reduced the number of C transactions used during the checking phase, and hence reduced my bill. :+1:

For that reason, I suggest that `--fast-list` **should be the default for b2**. Or perhaps gentler, rclone could recommendation `--fast-list` in the log, if the service is B2 and the number of files is greater than 1000.

But even then, whilst `--fast-list` improves checking, it looks like (my best guess) I am still paying 1 C transaction for every file I upload. So if I have a large number of files to upload, then this is still making b2 too costly. Can we prevent that?

Perhaps using [b2's own command-line tool](https://www.backblaze.com/b2/docs/quick_command_line.html) for the initial upload might avoid this. Or just use a different service!

**Comment by ncw** [comment]
> Yes `--fast-list` [is released](https://rclone.org/docs/#fast-list). It does appear to have reduced the number of C transactions made during the checking phase, and hence reduced my bill. 
> 
> For that reason, I suggest that `--fast-list` **should be the default for b2**. Or perhaps gentler, rclone could recommend `--fast-list` in the log, if the service is b2 (and the number of files is greater than 1000).

There is this bit in the docs: https://rclone.org/b2/#fast-list
