### ISSUE TITLE
Windows SFTP fails on connection to SSH

### ISSUE THREAD

**Issue by kubark42** [ncw/rclone#1279]
> What is your rclone version (eg output from `rclone -V`)

1.36

> Which OS you are using and how many bits (eg Windows 7, 64 bit)

Windows 10

> Which cloud storage system are you using? (eg Google Drive)

SFTP

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

`rclone lsd foo:`

> A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

I get a `socket: An address incompatible with the requested protocol was used.` error. 

This is similar to hashicorp/terraform#3423 (with specific details at hashicorp/terraform#3423 (comment)). https://github.com/hashicorp/terraform/pull/4323/files was a very easy fix for Terraform, and in Go to boot! Hope that's useful info.

C.f. https://github.com/ncw/rclone/issues/1218#issuecomment-289129726

**Comment by kubark42** [comment]
Spent a bit of time looking at this, but without detailed comments I don't think I have gotten very far. I can see similarities starting at https://github.com/ncw/rclone/blob/6bad0ad9c474749b1d8588a1ecdb0129e47607c3/sftp/sftp.go#L102, but I lose the thread quickly thereafter. I'm unfamiliar with Go, so this might have something to do with it.

@ncw, how would you go about integrating the terraform fix into rclone?

**Comment by ncw** [comment]
The fix doesn't look too complicated - it uses the small module https://github.com/xanzy/ssh-agent to make sure the windows code does the right thing.

I made a test on a branch here - fancy giving it a go on windows?

https://pub.rclone.org/v1.36-22-g06ea13a-ssh-agent%CE%B2/

**Comment by kubark42** [comment]
Thanks, I'll try to test it right away!

**Comment by ncw** [comment]
@kubark42 Did it work?

**Comment by kubark42** [comment]
@ncw, I tried to get it to work, but couldn't remember the steps I had taken to make the SSH keys load correctly. I've been distracted by work so haven't been able to give it another shot. I hope sometime in the coming weeks to put the correct windows environment back together.

**Comment by ncw** [comment]
I've merged this to master as it nearly got lost!

https://beta.rclone.org/v1.36-136-g5455d34f/ (uploaded in 15-30 mins)

Please re-open the ticket if it doesn't work properly.
