### ISSUE TITLE
is it possible to search or generate file listings (index) with rclone?

### ISSUE THREAD

**Issue by vesper8** [ncw/rclone#1285]
This may be outside the scope of rclone but I also figure that since it's capable of doing all these other things.. sync in particular, then perhaps these two features could be added

the thing is.. ever since Dropbox removed it's advanced search capability it's just become sooo hopeless. I have nearly 1tb of files in my Dropbox and lots of those are small files and searching by file extension for example just does not work at all.. and searching for files that "contain" a keyword seems utterly broken as well.

if rclone supported search that would be great.. however what I would be even more interested is just a means of dumping to a text file the full file listing of a folder (including the root folder).

This would simply dump every filename and it's full path recursively.

Is this something that can be done with rclone currently? if not.. would you consider adding this feature?

If I had this file dump I could just use grep to perform a much superior and much faster file search than dropbox can.

if there's another way to get this kind of file index I would love to know about it.

Thanks!

**Comment by MeltedLux** [comment]
[rclone ls](http://rclone.org/commands/rclone_ls/) should work for your needs I believe?

**Comment by ncw** [comment]
`rclone ls` will dump everything just fine.

You can also use

    rclone ls --include "*keyword*" remote:

**Comment by laocoi** [comment]
Query very slow with big folder ```rclone ls --include "*keyword*" remote:```

**Comment by ncw** [comment]
If you have a recent rclone, then [rclone lsf ](https://rclone.org/commands/rclone_lsf/)is the recommended way of doing this.  It give a a lot more control over the output.

@laocoi you can speed listings up by either increasing `--checkers` or using `--fast-list` if the remote supports it (see [the overview table](https://rclone.org/overview/#optional-features) ListR column).
