### ISSUE TITLE
Config file can be deleted if filesystem is full

### ISSUE THREAD

**Issue by Bippers** [ncw/rclone#1287]
> What is your rclone version (eg output from `rclone -V`)
1.34

> Which OS you are using and how many bits (eg Windows 7, 64 bit)
Raspbian

If the file system is completely full and there are other things also trying to write then it is possible that when rclone updates the config file it will delete it and then there wont be any space to write the new version. You then need to restore the config file from a backup if one exists, or set it up again.

Bit of an edge case but can be serious. Noticed because my Raspberry Pi only has 32gb and the file system quickly becomes full. Could cause loss of data if rclone is backing up to an encrypted remote and there is no backup of the config file.

I'm using 1.34 and haven't tested it in 1.36, but this isn't really something I want to recreate as it means I have go through setup again and reorganise my Pi. Sorry if it has been fixed in newer versions.

**Comment by ncw** [comment]
The handling of the config file has improved from 1.34, but I'll check that this case is handled properly.

I should probably change the config file handling to

* read config
* write config.new
* delete config.old if it exists
* rename config config.old
* rename config.new config

**Comment by sketch242** [comment]
This has happened to me several times in the past, including while uploading data on 1.36 the other day.

Why does rclone even need to write to the config file just to upload data to a remote?

**Comment by calisro** [comment]
It refreshes the auth token.
