### ISSUE TITLE
Feature Request: implement Content HASH for DROPBOX

### ISSUE THREAD

**Issue by cstm** [ncw/rclone#1302]
Content HASH has been implemented from DropBox API since few days
https://www.dropbox.com/developers/reference/content-hash

any news on putting this into rclone ?

**Comment by ncw** [comment]
This would have to go in as part of #349 the v2 API.

It is annoyingly non standard!  It isn't either md5sum or an sha1sum or even an sha256sum  it is an sha256sum of 4 MB blocks, all concatenated then the sha256sum of those.

However it will do perfectly for upload and download integrity checking.

**Comment by chmercesmoreira** [comment]
This is really necessary since Plex uses the file hash to search for subtitles.

**Comment by ncw** [comment]
Dropbox v2 API has just hit master with content hashing

Please try this beta

https://beta.rclone.org/v1.36-144-g178ff62d/ (uploaded in 15-30 mins)

**Comment by ncw** [comment]
Bit of trouble building: beta now here: https://beta.rclone.org/v1.36-146-g71028e0f/
