### ISSUE TITLE
Encrypted directory names shows with `sync` and `copy` into subdirectories

### ISSUE THREAD

**Issue by sweharris** [ncw/rclone#1305]
With rclone-1.35 create a standard encrypted directory

```
[t1]
type = crypt
remote = Amazon:t1
filename_encryption = standard
password = ***
password2 = ***
```

Now we can make a directory and copy a file into it

```
$ rclone mkdir t1:testdir
$ rclone copy ANSWERS t1:testdir
2017/04/01 14:32:52 Encrypted amazon drive root 't1/2gg8tqhmpm0ve4dphjipib63ag': Waiting for checks to finish
2017/04/01 14:32:52 Encrypted amazon drive root 't1/2gg8tqhmpm0ve4dphjipib63ag': Waiting for transfers to finish
2017/04/01 14:32:53 
Transferred:    166 Bytes (99 Bytes/s)
Errors:                 0
Checks:                 0
Transferred:            1
Elapsed time:        1.6s
```

Note the encrypted name "2gg8tqhmpm0ve4dphjipib63ag" shows.

Everything works correctly, just the wrong name is displayed

```
$ rclone ls t1:
      166 testdir/ANSWERS
```

**Comment by azureblaze** [comment]
The name gets decrypted when you access it via the crypt interface. Try `rclone ls Amazon:t1` and it should be encrypted.

**Comment by sweharris** [comment]
@azureblaze The problem isn't the decryption when I do an `ls t1:`, it's that the _encrypted_ name is shown during the output of the `copy` command.

```
$ rclone copy ANSWERS t1:testdir
2017/04/01 14:32:52 Encrypted amazon drive root 't1/2gg8tqhmpm0ve4dphjipib63ag': Waiting for checks to finish
```

Or, more simply, it _should_ display "t1:testdir" or similar at that point, rather than  '2gg8....' 

It appears to be a consequence of the "layering" done by the encryption system; the underlying copy process works on the encrypted names, but this causes the wrong names to be displayed.  It may not be trivial to change this behaviour, either, and is just something to be lived it.  But it definitely makes things harder to track in output of cron jobs!

**Comment by azureblaze** [comment]
I see, I misread what you meant based on the last part, there is the flag       --crypt-show-mapping:
`--crypt-show-mapping                For all files listed show how the names encrypt.` which alleviates your problem somewhat but it's quite verbose since it prints both the full encrypted path as well as the full decrypted path, I'd post an example but the filenames of my encrypted files are sensitive. You seem to still be on 1.35 so you need to upgrade to 1.36 first in order to use the flag.

**Comment by sweharris** [comment]
No, that's the wrong way round and still doesn't work with `copy`

eg with 1.36-DEV

```
% rclone -v --crypt-show-mapping copy rclone t1:testdir
2017/04/01 17:13:17 INFO  : Encrypted amazon drive root 't1/4n5hj7nl3mvq98ekhjfceth090': Modify window not supported
2017/04/01 17:13:18 INFO  : Encrypted amazon drive root 't1/4n5hj7nl3mvq98ekhjfceth090': Waiting for checks to finish
2017/04/01 17:13:18 INFO  : Encrypted amazon drive root 't1/4n5hj7nl3mvq98ekhjfceth090': Waiting for transfers to finish
2017/04/01 17:13:27 INFO  : rclone: Copied (new)
2017/04/01 17:13:27 INFO  : 
Transferred:   27.998 MBytes (2.455 MBytes/s)
Errors:                 0
Checks:                 0
Transferred:            1
Elapsed time:       11.4s
```

The INFO messages don't display the "testdir" value at all.

**Comment by ncw** [comment]
This would be reasonably easy to fix...  The code in question is

https://github.com/ncw/rclone/blob/master/crypt/crypt.go#L143

Fancy having a go?

**Comment by sweharris** [comment]
Ah, I see; the String() function is implemented in each filesystem type, and the one for crypt just calls the underlying filesystems entry.  We can simply just use the values the user entered from the crypt's Fs object, and not the lower one.  Hopefully pull #1321 is good!  Just a one line change.

**Comment by ncw** [comment]
This will be in

https://beta.rclone.org/v1.36-26-g82b8d68/ (uploaded in 15-30 mins!)
