### ISSUE TITLE
pipe configuration password - inappropriate ioctl for device

### ISSUE THREAD

**Issue by ddomingues1970** [ncw/rclone#1308]
Can anyone help me please?
I'm trying to pipe the configuration password from a file to rclone. 

> What is your rclone version (eg output from `rclone -V`)
rclone v1.36

> Which OS you are using and how many bits (eg Windows 7, 64 bit)
Linux 4.8.0-36-generic #36~16.04.1-Ubuntu SMP Sun Feb 5 09:39:57 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

> Which cloud storage system are you using? (eg Google Drive)
DropBox / GoogleDrive / AmazonDrive / OneDrive / Yandex

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
cat rclone_passphrase | rclone -v sync .DropBox/ DropBox:

> A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

2017/04/03 19:11:13 Failed to read password: **inappropriate ioctl for device**

**Comment by azureblaze** [comment]
You can always export RCLONE_CONFIG_PASS=<rclone_passphrase>

**Comment by ncw** [comment]
This is a bug in the golang.org/x/crypto/ssh/terminal library I think... - I have reported it as such here: https://github.com/golang/go/issues/19909

@azureblaze work-around is a good one though.

**Comment by ncw** [comment]
I've fixed this here

https://beta.rclone.org/v1.42-014-g947e10eb/ (uploaded in 15-30 mins)

This will be in [the latest beta](https://beta.rclone.org) and in v1.42
