### ISSUE TITLE
--dry-run --verbose says both "Not deleting" and "Deleted"

### ISSUE THREAD

**Issue by rprieto** [ncw/rclone#1309]
> What is your rclone version (eg output from rclone -V)

v1.36

> Which OS you are using and how many bits (eg Windows 7, 64 bit)

macOS 10.11.3 El Capitan

> Which cloud storage system are you using?

Amazon S3, but also happens with local remotes

> The command you were trying to run

```bash
$ mkdir -p a b

$ touch a/same a/new b/same b/old

$ rclone sync a b --dry-run
# 2017/04/04 20:06:48 NOTICE: new: Not copying as --dry-run
# 2017/04/04 20:06:48 NOTICE: old: Not deleting as --dry-run

$ rclone sync a b --dry-run --verbose
# 2017/04/04 20:06:51 NOTICE: new: Not copying as --dry-run
# 2017/04/04 20:06:51 NOTICE: old: Not deleting as --dry-run
# 2017/04/04 20:06:51 INFO  : old: Deleted
```

The log is as expected in quiet mode (the new default since 1.36). In verbose mode however, `old` says both "not deleting" and "deleted". This seems to be a bug in the log only, since the file was actually not deleted.

**Comment by ncw** [comment]
I have fixed this now - thanks for reporting

https://beta.rclone.org/v1.36-22-gbc25190/ (uploaded in 15-30 mins)
