### ISSUE TITLE
Is there a way to use more than one thread with a single command?

### ISSUE THREAD

**Issue by rpgdev** [ncw/rclone#1312]
Is there a way to use more than one thread with a single command? I don't mean --transfers I mean actual threads in order to take more advantage of my CPU. 

> What is your rclone version (eg output from `rclone -V`)
rclone v1.36

> Which OS you are using and how many bits (eg Windows 7, 64 bit)
Linux 64bit

> Which cloud storage system are you using? (eg Google Drive)
Amazon Cloud Drive

**Comment by pskuza** [comment]
Why do you think your CPU is limiting the transfer? Slow encryption? What have you noticed?

**Comment by rpgdev** [comment]
@pskuza I never said that. I'm just wondering if this is possible to do.

**Comment by pskuza** [comment]
No.

**Comment by rpgdev** [comment]
I understand. I ask because I've seen "rclone" processes (on shared Linux servers) that seem to use more than one thread and that left me wondering if it was possible. It was probably a random script named "rclone" then.

**Comment by ncw** [comment]
rclone doesn't change the go default which is to make one OS thread per CPU.  goroutines are then sheduled over these OS threads - there can be many more goroutines than OS threads.  OS threads are also made for certain kinds of IO (eg disk IO).

So rclone should already be using the maximum amount of CPU it needs.

You can change the number of OS threads rclone creates initially by setting the [GOMAXPROCS](https://golang.org/pkg/runtime/) environment variable.  I think you are unlikely to see any performance changes if you do that, but I would be interested in reports if you do notice a difference.

> The GOMAXPROCS variable limits the number of operating system threads that can execute user-level Go code simultaneously. There is no limit to the number of threads that can be blocked in system calls on behalf of Go code; those do not count against the GOMAXPROCS limit.
