### ISSUE TITLE
Upload file to remote storage from URL

### ISSUE THREAD

**Issue by ext4** [ncw/rclone#1320]
Directly uploading to remote storage from a URL would be a useful feature, for example:

`rclone copy http:https://example.com/some_large_file.tar remote:/Files`

This would be useful for systems without enough free space to save the entire file before upload (for example a VPS).

I understand that currently `rclone` needs to know the size of the file before upload (https://github.com/ncw/rclone/issues/230#issuecomment-161762623), however properly configured webservers should send a [`Content-Length`](https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.13) header which indicates the size of the file.

**Comment by ncw** [comment]
Nice idea!

I think that would be best implemented as a separate command, say

    rclone copyurl https://example.com/file.tar remote:File/file.tar

Yes rclone does need to know the size of files in advance, however for a lot of remotes, you can just use 0 and it will work.  This doesn't work with b2 for instance.  You mostly likely will get a Content-Length as you suggest though.

**Comment by chmercesmoreira** [comment]
This is amazing, currently I'm running a VPS from OVH that has only 10gb of disk space (~8gb available for use), this surely will help a lot.

**Comment by pmwoodward3** [comment]
+1 this would be awesome, would be even better if you could pass a list of URLs.

**Comment by chmercesmoreira** [comment]
I'm dreaming:
Imagine if we could integrate [jdownloader2](https://support.jdownloader.org/Knowledgebase/Article/View/40/0/myjdownloaderorg-api-docu) with rclone?
Something like:
`rclone jd2 http://linkToCloudProvider remote:path`
I know, I know, I'm thinking too much big haha.

**Comment by pmwoodward3** [comment]
I think a URL list and/or the ability to take an open directory and directly send that to a cloud destination would be amazing :)

**Comment by desimaniac** [comment]
+1

I need this so bad!

**Comment by scriptzteam** [comment]
nice idea :)

**Comment by xiaolei0125** [comment]
+1
nice idea

**Comment by gidoBOSSftw5731** [comment]
I understand this ISNT golang, but I think we should all take https://github.com/golang/go/wiki/NoPlusOne into account.

**Comment by ncw** [comment]
Anyone want to work on the `copyurl` command?  Happy to walk people through what needs to be done?

**Comment by gidoBOSSftw5731** [comment]
I can try to work on it @ncw, but my experience is limited (all ive done is setup [this](https://imagen.click) and some tinkering in golang and py.)

**Comment by ncw** [comment]
@gidoBOSSftw5731 that would be great if you wanted to have a go.

First step get the rclone source (use `go get github.com/ncw/rclone`) then change the origin to point to your fork on github.  Let me know if you need more detail here.  I should probably write some "how to set up a dev environment for rclone" instructions.

What you'll be doing is making a new command.  These are in the `cmd` directory.  You'll need to make a new directory called `copyurl`.  Take a look at the other commands and see what is in a simple one (say `cmd/delete/delete.go`).  Make the new command compile (just get it to print something).  Add the command to `cmd/all/all.go`, compile rclone (go build or go install from the rclone root) and check you have a new command.

That is the first steps.  Next the coding of the actual command...  Use the [net/http](https://golang.org/pkg/net/http/) to make a GET request to the URL in the command line.  This will give you an `http.Response`.  To get things going use `operations.Rcat` to upload the content to the Fs you will parse out of the command line.

I just remembered - we do this already in the `serve restic` command

https://github.com/ncw/rclone/blob/6301e15b793d9e53f3dce67e11bad521358c873e/cmd/serve/restic/restic.go#L333-L369

Probably what we want to do is factor that out into `operations.UploadHttpResponse` (write tests) and call that. It does the more efficient thing if we know the ContentLength.

Anyway that was a bit of a brain dump - let me know if you want more help. Post PRs and I'm happy to comment on them.

**Comment by ncw** [comment]
@gidoBOSSftw5731 reading the above again, I think what we should do is get your PR as calling `operations.Rcat` then it will work and I'll think about the refactor job!

**Comment by gidoBOSSftw5731** [comment]
Out of curiosity, since I assume we would have to save the file for a few moments (to then execute a upload command,) should I use memory? tmpdir?

**Comment by ncw** [comment]
@gidoBOSSftw5731 No you'd stream the file so no storage required. So you'd pass the `resp.Body` to `operations.Rcat`...

**Comment by ncw** [comment]
Thanks to @kfur this is now implemented here:

https://beta.rclone.org/v1.42-148-g1c578ced/ (uploaded in 15-30 mins)

This will be in [the latest beta](https://beta.rclone.org) then and in 1.43

Thank you @kfur - great job :-)

**Comment by kfur** [comment]
@ncw thanks for grate software and your help !
