### ISSUE TITLE
Incredibly slow gdrive speed - Web upload fast

### ISSUE THREAD

**Issue by Rhainland** [ncw/rclone#1324]
When filing an issue, please include the following information if possible as well as a description of the problem.  Make sure you test with the latest beta of rclone.

    https://beta.rclone.org/
    https://rclone.org/downloads/

If you've just got a question or aren't sure if you've found a bug then please use the [rclone forum](https://forum.rclone.org/) instead of filing an issue.

> What is your rclone version (eg output from `rclone -V`)
Latest(downloaded as of 20 minutes ago)

> Which OS you are using and how many bits (eg Windows 7, 64 bit)

Windows server 2012
> Which cloud storage system are you using? (eg Google Drive)

Google drive
> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
Ccopy --ignore-existing --checksum --ignore-size --verbose --transfers 15 --checkers 9 --contimeout 60s --timeout 300s --retries 3 --low-level-retries 10 --stats 1s
> A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

Transfering 2 roughly 2gig files results in this;
http://i.imgur.com/OEBcs6k.png

I dont get it, uploading via web panel is fast. It will eventually crawl to 1kbps after a while, making it impossible for me to use rclone now, i didnt used to act like this. Anyone else ever experienced this?

**Comment by Rhainland** [comment]
It appears the transfers actually just halts at 0kb/s, for a while, then picks up eventually for a short period, and then halts again. This happens continiously and causes slow uploads.

Could it be related to this, despite it being an older issue?;
https://forum.rclone.org/t/rclone-stalls-on-acd-upload-done-0-bytes-s-eta-0s-and-must-be-restarted/727/22

**Comment by Yoitsu** [comment]
I have the same problem. Google Drive upload starts at my maximum upload speed (roughly 6MB/s) and over a span of 1 minute the upload speed drops to ~300kB/s. This happens on Windows 7 64bit with latest rclone beta, both with the shared client id and my own.
[log.txt](https://github.com/ncw/rclone/files/919537/log.txt)

**Comment by memeplex** [comment]
Most probably you will need to get your own google credentials in order to avoid sharing quotas will every rclone user out there: https://github.com/ncw/rclone/issues/560. This worked like a charm for me.

**Comment by Rhainland** [comment]
I am using my own google api, and this issue is still a problem

**Comment by Rhainland** [comment]
Okay, so i did some digging on this, and i came up with some info.

 I am using  --drive-chunk-size to increase transfer speed as per https://github.com/ncw/rclone/issues/397

However, odd things seems to be happning to rclone when using this. I am transfering several 1 gig files.

With a buffer of 256, the transfer of each file will within a few seconds reach 25%, and halt here for 4-6 minutes, before jumping from 25 to 50%. 

With a buffer of 512, the transfers will move to 50% initially, wait a while and then jump to 100.

With the buffer at 1024, the file transfers will indicate 100% complete after just 20-25 seconds, and be stuck at 100% for a longer period of time, while they are 100% no files have actually been applied on my google drive. 

Anyone else experience this behaviour? How do we actually see the file transfer speeds with this behaviour?

**Comment by yonjah** [comment]
The speed you are seeing with chunked upload are inaccurate (see issue #970) 
Try setting `--drive-upload-cutoff` to high value and upload a file smaller than that so it will not be chunked.
If you are getting a proper upload speed you can try with a chunked file but you'll need to manually calculate the time it should take to upload (file size / upload speed) and see if rclone manages to upload the file in similar time.
If so the actual upload speed is OK it is just the stats that are not showing correctly

**Comment by ncw** [comment]
I think @yonjah is probably correct - try checking the actual internet usage with a different tool

**Comment by Rhainland** [comment]
The actual speed of rclone was slow, with 15 files, maybe 15-20MB/s, on a 1gbps line, i was under the impression that chunk size would increase the speed, but it appears it does not. I guess ill deal with the speed ^^

Thanks!

**Comment by ncw** [comment]
No probs!
