### ISSUE TITLE
Add and ask before destructive change option

### ISSUE THREAD

**Issue by memeplex** [ncw/rclone#1327]
For bulk updates it's better to do a dry run before, but for -say- daily syncs in which a few files change, it might be convenient to just allow/disallow the change on a per conflicting file basis while the update is running. For every file that is about to be deleted or overwritten by a file with an older modification date (it's true that files with newer modification dates might yet destroy local-only changes, but I'm proposing the same criterion than the --update flag adopts as a practical choice), an "are you sure?"-like prompt would be presented to the user if the `--ask-before-destroy` or whatever option is set at the cli.

**Comment by ncw** [comment]
I'm afraid that getting rclone to ask about individual files doesn't fit within the architecture of rclone.

However if you are worried about data loss, use the `--backup-dir` option which will save any files that get overwritten into a different directory.

**Comment by memeplex** [comment]
Great, somehow I didn't notice there was such an option. Thanks!
