### ISSUE TITLE
Allow to avoid synchronization of files that changed in the target

### ISSUE THREAD

**Issue by memeplex** [ncw/rclone#1328]
Well... almost. What I'm thinking about here is the following scenario:

1. The date T of the last sync was recorded at the target side.
2. Some files changed in between.
3. The next sync will overwrite or delete those files (even in case the `--update` option was set, there is still a risk of both destructive operations).
4. So I create an exclusion filter to exclude every local file that was updated after T and run the sync.

Now, what I propose is to add an option to avoid modifying files that changed at the target side after T. There is already an option to avoid transferring files that are too new, but that's not exactly the same. And I think the use case is compelling enough that a special flag might be preferable over a list of excluded files.

**Comment by memeplex** [comment]
Thinking a bit more about this I realize it's not only a matter of convenience (exclude list vs apecial option) since it's not feasible to produce exclude lists for every kind of store in a practical way. I believe this should be a primitive: "don't destroy things that changed in the target since this time". It's hard to implement any kind of reliable multiway sync without something like that. Maybe --update-older-than. Also, aborted potentially destructive operations (those excluded by --update or --update-older-than) should be reported in a distinct way, so the user is able to take effective conflict resolution actions (merge, replace, etc.). This may be coupled with my suggestion to add a flag so that rclone asks the user upon destructive operations.

**Comment by ajkis** [comment]
You can do that with copy and skip existing.

**Comment by memeplex** [comment]
No, it's not a matter of files existing or of target files having a newer modification time than respective source files, but of target files having a modification time that's newer than a specified one (for the described use case, that's the time of the last sync). Besides, I'm interested on syncing, not copying.

**Comment by yonjah** [comment]
Doesn't the update option solve this for you ?
`-u, --update                            Skip files that are newer on the destination.`

**Comment by yonjah** [comment]
Oh sorry do you mean if both files have changed both on source and target ?
And source is still newer than target but they have basically diverged ?

I guess if you save the last proper sync time that might be useful, but you really need to be careful about how to manage those timing.
Also there has to be a warning displayed to the user that files are out of sync since this is something you'll want to manually fix ASAP, or your putting yourself at risk of eventually loosing data

**Comment by memeplex** [comment]
No, newer on the destination is not the same as newer than the last sync date or some other date. The problem here is that you need to check for modifications after some common version (mod date) of a files upon which both sides agreed at the "branching" time. And after thinking more and more about the issue I realized that that date is file dependant, it can't be assumed to be just a single date for all the sync operation, so I'm not sure this proposal is really worthy as a way to implement some limited but cheap form of two-way sync through a shared remote (a la dropbox), at least in the general case. Nevertheless I would use git annex with the rclone remote for serious versioning, but --update-older-than may help implement more robust sync schema than plain --update, albeit not bullet proof.

**Comment by memeplex** [comment]
Just think about this example:
1. A pulls f
2. B pulls f
3. A changes f at time T1 > T (the mod date of f)
4. B changes f at time T2 > T1
5. B pushes f
6. A pulls f with sync --update: A changes get silently overwritten by B changes!!

**Comment by yonjah** [comment]
Yea I thought that what you meant.
Which is actually a two way sync. This can be done by the file update time but I wouldn't trust it.
It would be much safer to keep the hash of the last synced version and not allow overwrites if it has changed. 
There is a feature request for two way sync #118  and I guess overwrite protection should be part of it

**Comment by memeplex** [comment]
I will close this since I see you're heading towards a much better and comprehensive solution for 2 way sync using more metadata.

I would like to add that I'm very happily using git annex with the rclone special remote, but that's not to say it wouldn't be useful to get rclone solving simple sync scenarios by itself.
