### ISSUE TITLE
Colon file handling

### ISSUE THREAD

**Issue by esticle** [ncw/rclone#1331]
Hi,

I seem to be unable to make rclone attempt to copy a directory containing a colon character in it's name, bug or user? :) It seems to be interpreting the colon as a config fragment for the endpoint name.

> What is your rclone version (eg output from `rclone -V`)

rclone v1.36-22-gbc25190β & rclone v1.36

> Which OS you are using and how many bits (eg Windows 7, 64 bit)
Linux x64

> Which cloud storage system are you using? (eg Google Drive)
Amazon Cloud Drive

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
> A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

```
$ mkdir "test:directory" ; touch "test:directory/test.file.txt"

$ ./rclone -vv copy "test:directory" "acd-data:.tmp/test:directory/"
2017/04/14 16:33:08 DEBUG : rclone: Version "v1.36-22-gbc25190β" starting with parameters ["./rclone" "-vv" "copy" "test:directory" "acd-data:.tmp/test:directory/"]
2017/04/14 16:33:08 Failed to create file system for "test:directory": didn't find section in config file

$ ./rclone -vv copy "test:directory" "acd-data:.tmp/"
2017/04/14 16:33:36 DEBUG : rclone: Version "v1.36-22-gbc25190β" starting with parameters ["./rclone" "-vv" "copy" "test:directory" "acd-data:.tmp/"]
2017/04/14 16:33:36 Failed to create file system for "test:directory": didn't find section in config file

$ ./rclone -vv copy 'test:directory' acd-data:.tmp/
2017/04/14 16:34:00 DEBUG : rclone: Version "v1.36-22-gbc25190β" starting with parameters ["./rclone" "-vv" "copy" "test:directory" "acd-data:.tmp/"]
2017/04/14 16:34:00 Failed to create file system for "test:directory": didn't find section in config file

$ ./rclone -vv copy test\:directory acd:.tmp/
2017/04/14 16:38:39 DEBUG : rclone: Version "v1.36-22-gbc25190β" starting with parameters ["./rclone" "-vv" "copy" "test:directory" "acd:.tmp/"]
2017/04/14 16:38:39 Failed to create file system for "test:directory": didn't find section in config file

$ ./rclone -vv copy test\\:directory acd:.tmp/
2017/04/14 16:38:43 DEBUG : rclone: Version "v1.36-22-gbc25190β" starting with parameters ["./rclone" "-vv" "copy" "test\\:directory" "acd:.tmp/"]
2017/04/14 16:38:44 INFO  : amazon drive root '.tmp': Modify window not supported
2017/04/14 16:38:44 DEBUG : amazon drive root '.tmp': Reading ""
2017/04/14 16:38:44 DEBUG : amazon drive root '.tmp': Finished reading ""
2017/04/14 16:38:44 INFO  : amazon drive root '.tmp': Waiting for checks to finish
2017/04/14 16:38:44 INFO  : amazon drive root '.tmp': Waiting for transfers to finish
2017/04/14 16:38:44 ERROR : Attempt 1/3 failed with 0 errors and: error reading source directory "": directory not found
2017/04/14 16:38:44 DEBUG : amazon drive root '.tmp': Reading ""
2017/04/14 16:38:44 DEBUG : amazon drive root '.tmp': Finished reading ""
2017/04/14 16:38:44 INFO  : amazon drive root '.tmp': Waiting for checks to finish
2017/04/14 16:38:44 INFO  : amazon drive root '.tmp': Waiting for transfers to finish
2017/04/14 16:38:44 ERROR : Attempt 2/3 failed with 0 errors and: error reading source directory "": directory not found
2017/04/14 16:38:44 DEBUG : amazon drive root '.tmp': Reading ""
2017/04/14 16:38:44 DEBUG : amazon drive root '.tmp': Finished reading ""
2017/04/14 16:38:44 INFO  : amazon drive root '.tmp': Waiting for checks to finish
2017/04/14 16:38:44 INFO  : amazon drive root '.tmp': Waiting for transfers to finish
2017/04/14 16:38:44 ERROR : Attempt 3/3 failed with 0 errors and: error reading source directory "": directory not found
2017/04/14 16:38:44 Failed to copy: error reading source directory "": directory not found

# To prove the endpoints actually exist...
$ ./rclone ls acd-data:.tmp ; echo $?
0
$ ./rclone ls acd:.tmp ; echo $?
0

``` 

Any ideas?

Thanks!

**Comment by ncw** [comment]
That is a fault of the parser which parses the remote name off the front....

You can work around this by making a remote of type "local" then using that.

I should probably improve the parse so it recognises backslashes or something like that, or maybe make it so it doesn't parse a /, so you could then write ./test:directory

**Comment by ncw** [comment]
Actually I just noticed that the ./ workaround works right now, so 

    ./rclone -vv copy ./test:directory "acd-data:.tmp/test:directory/"

should work fine

**Comment by ncw** [comment]
I've documented the workaround in the referenced commit.

**Comment by michaelmagan** [comment]
@ncw Hey thanks for documenting this fix! I'm running into, I believe, this issue in the reverse direction (SOURCE to LOCAL. When I run:

`sudo rclone copy --dry-run REMOTE:/BUCKET_NAME/. /PATH/TO/DESTINATION/ -vvP`

I get:

`NOTICE: S3 bucket . path BUCKET_NAME/.: Odd name received "urn:oid:10292"`
 
I've read your documentation changes but not sure how to apply it to my case where the SOURCE has directrories with ":" in them. When I try this I get the same error as above:

`sudo rclone copy --dry-run REMOTE:./BUCKET/. /PATH/TO/DESTINATION/`

How should format rclone copy when the remote has ":" in the directory names and I want to copy to a local host (linux). I can create a new issues but it seems spiritually similar to this one.

**Comment by ncw** [comment]
@michaelmagan you shouldn't have to do anything special to copy names with `:` to a linux host.

So I'd just do this (no dot).

    rclone copy --dry-run REMOTE:/BUCKET_NAME/ /PATH/TO/DESTINATION/ -vvP

**Comment by michaelmagan** [comment]
@ncw Got it, maybe this is a different problem but this is what happens if run the command that way:
```
2021/07/30 21:45:32 DEBUG : rclone: Version "v1.50.2" starting with parameters ["rclone" "copy" "--dry-run" "REMOTE:/BUCKET_NAME/" "/PATH/TO/DESTINATION/" "-vvP"]
2021/07/30 21:45:32 DEBUG : Using config file from "/root/.config/rclone/rclone.conf"
Transferred:   	         0 / 0 Bytes, -, 0 Bytes/s, ETA -
Errors:                 0
Checks:                 0 / 0, -
Transferred:            0 / 0, -
Elapsed time:          0s
```
It just stalls here until I stop the process.

If I run:
`rclone copy --dry-run REMOTE:/BUCKET_NAME/. /PATH/TO/DESTINATION/ -vvP`

I get this error for all my folders because the they all have ":"
`2021-07-30 23:37:25 NOTICE: S3 bucket  path BUCKET_NAME .: Odd name received "urn:oid:10975"`

Do you think this is a different problem?

**Comment by ncw** [comment]
> It just stalls here until I stop the process.

Has Bucket got a very large number of files in it all in the same directory? If so waiting longer will help.  If you want to see that rclone is doing HTTP transactions then add `-vv --dump headers`.

I think this is not related to this issue. Probably would be best to open a new thread in [post on the rclone forum](https://forum.rclone.org/) about this to discuss.
