### ISSUE TITLE
How to merge two folders via copy/sync?

### ISSUE THREAD

**Issue by Givemeyourgits** [ncw/rclone#1343]
version: rclone v1.36
platform: ACD & GDrive

I've been working around this manually for a while, but it would be nice to find a solution.  

I have two folders, both have 10 files.   I initially do a rclone sync to sync the first folder into a remote directory.  Now I want to copy the files into the second folder also into that same remote directory.

If I use rclone copy * from the second directory -> remote directory, it complains copy only supports two parameters.

If I do a sync, it will delete the first set of files during the sync.

I've tried sync with the each of these options individually, and it still deletes the first set of files during or after the sync:

--ignore-existing
--delete-excluded

The only way I have successfully done it is to sync the first folder, then manually one by one copy each file from the second folder to the remote folder.

Is there an easier way I am missing here?  If not, can you make one?

**Comment by yonjah** [comment]
What are the exact commands your using ?

And why are you trying to sync two folders into the same target. There is no reason it shouldn't work it just sounds like it can cause a mess

**Comment by Givemeyourgits** [comment]
Say I have GDrive (G:) with a folder "out".
Then I have two local folders on my drive in1 & in2 with 10 files in each.

I will first do a rclone sync in1 G:out
Then I need some way to get in2 also in G:out, I have tried:

rclone sync in2 --ignore-existing G:out 
and
rclone sync in2 --delete-excluded G:out 

both of these will sync in2 into G:out but will then delete the files originally synced from in1.

The only way I have managed to do it, is to first 

rclone sync in1 G:out
then 

rclone copy in2/file1 G:out/ 
...
rclone copy in2/file10 G:out/

Trying to do 

rclone copy in2/* G:out/ 

will throw error that copy only accepts two parameters and all the sync options seem to remove the existing files.

**Comment by yonjah** [comment]
You don't want to use sync for that since sync will remove files on target which are not available on source.
with copy you don't need to add * in so just 
`rclone copy in1 G:out`
and
`rclone copy in2 G:out`

Notice that if you have identical file names in in1 and in2 they will overwrite each other.
I don't understand why you want to do it instead of just having two folders `out1` and `out2` or even `out/in1` and `out/in2` so you wont loose your original structure

**Comment by Givemeyourgits** [comment]
I am merging the two folders into one on to the cloud destination.
I will give that a try, but I also have situations when the files are not in the a folder.

For example, the destination (G:out has 30 files) and I have 10 files in my current local path I need to move over but there are 100 files in my local path.  

What I want to do is this:

rclone copy job50* G:out

This would copy all files that start with job50xxxx to the destination that already has files.  I do this just as often as copying two folders into one.   

I would like to avoid first copying the files into some temporary path using OS commands before moving them up, so ideally I need some way to do wild cards or easily specify multiple files.  The rclone copy folder1 G:out will help in some situations and will try that out.

**Comment by yonjah** [comment]
You will need to use a filter to do what your asking -
https://rclone.org/filtering/
Just make sure you quote the string to prevent bash from expending the wildcard

**Comment by Givemeyourgits** [comment]
I will give that a try, thanks.  It would be nice if you could do

rclone copy *.* G:out

**Comment by astrodad** [comment]
I want to do the same thing. I have multiple TV file folders on different external hard drives and want to merge them into a single tree. I'm trying to figure out how to make this work with filters but I'm too stupid to figure it out. I'm also toying with unionfs to stack the directories into a single view before running copy or sync.

**Comment by alex-w-k** [comment]
@astrodad This is exactly what I'm trying to do, have you found a solution for that?

**Comment by astrodad** [comment]
@alek-w-k I’m using unionfs to make that happen. It works pretty well but unionfs is quite old.

**Comment by ncw** [comment]
I'm going to close this now as I don't think there is an actual bug or feature to discuss.

Maybe move the discussion to [the rclone forum](https://forum.rclone.org/)?
