### ISSUE TITLE
Reduce traffic to google drive by using fields parameters

### ISSUE THREAD

**Issue by ncw** [ncw/rclone#1346]
I received this from the google drive team

> We have increased the queries per second to your project ID, you will be able to see the increase shortly. However, it is strongly recommended that you use the fields parameter so that our backends don't have the load of providing information that is not needed. Our documentation is at https://developers.google.com/drive/v3/web/performance#partial-response.

The Go API has `Fields()` calls which can be given a list of strings.  These need to be the strings as used in the JSON api as listed in the v2 docs.

It should be a straightforward exercise to add calls to `Fields()` in the drive API and run through the integration tests to make sure nothing is broken. 

The most important place to add this is in the listing routine, and the reading metadata.

I know that some of the other APIs (OneDrive springs to mind - there may be others) can also do this.

**Comment by NeoPhyTe-x360** [comment]
Sounds great mate

**Comment by jrarseneau** [comment]
Watching. Would love to try a beta with this implemented.

**Comment by felixbuenemann** [comment]
I think partial responses require the v3 api and rclone is currently using the v2 api.

**Comment by azgul** [comment]
Ran out of time but I found the possible fields here: https://developers.google.com/apis-explorer/#p/drive/v2/drive.files.list

Will check back on tests once they finish running locally

**Comment by romanturbo** [comment]
Any idea when will this be fixed?

**Comment by ncw** [comment]
I have merged @azgul patch in - thank you :-)

https://beta.rclone.org/v1.36-33-g7d9faff/ (uploaded in 15-30 mins)

I tried both sorts of integration tests and it worked fine for me - it could do with some real world testing too and some performance testing.

I did a rough before and after test like this

```
$ rclone ls drive:1000files -vv --dump-bodies 2>z-after
$ rclone-v1.36 ls drive:1000files -vv --dump-bodies 2>z-before
$ grep -v DEBUG z-before  | wc
 100991  187367 3719012
$ grep -v DEBUG z-after  | wc
  37967   70302 1227481
```

So the bytes used was reduced from 3.5M to 1.2M which is a reduction to 33% of the original size.

**Comment by felixbuenemann** [comment]
I tried to test this build, but ran into #1362 which appears unrelated to this change, because it also happened with the previous build 31.

**Comment by ncw** [comment]
Next update from @azgul - don't ask for owner info if not needed

https://beta.rclone.org/v1.36-34-g0d6e1af/ (uploaded in 15-30 mins)

**Comment by dfunkt** [comment]
Seems like I encountered an issue with this. Starting from commit https://github.com/ncw/rclone/commit/d7df065320d180b4388e4366370974a30237f219 some folders are missing from the list, here's an example of how it should look (used commit https://github.com/ncw/rclone/commit/84d4d7f9d9dd5b8bf990b289c63bebe8251a3489)

> ./rclone lsd EGD:/ | grep Kamisama         
> -1 2016-11-25 18:42:37        -1 [Commie] Kamisama Hajimemashita [BD 720p AAC]
> -1 2016-11-23 23:02:07        -1 [Commie] Kamisama Hajimemashita 2 [BD 720p AAC]
> 
And here's how it looks with the latest commit:

> rclone lsd EGD:/ | grep Kamisama
> -1 2016-11-25 18:42:37        -1 [Commie] Kamisama Hajimemashita [BD 720p AAC]

And it's not the only folder missing either :(
Should I open a new issue?

**Comment by ncw** [comment]
@dfunkt That is reproducible before and after that commit?

What would be most useful is a dump with `-vv --dump-bodies` of your `lsd` command before and after.  You can email that to me if you want subject "rclone issue 1346" if you want as it will have lots of personal info in.

**Comment by dfunkt** [comment]
It's reproducible from commit https://github.com/ncw/rclone/commit/d7df065320d180b4388e4366370974a30237f219 to the latest one, commit https://github.com/ncw/rclone/commit/84d4d7f9d9dd5b8bf990b289c63bebe8251a3489 and below show everything just fine.

**Comment by azgul** [comment]
I cannot reproduce your issue with my own gdrive account. `rclone lsd` for my gdrive produces the same output for me with the following rclone versions:
```
rclone v1.35-169-g320c53eβ
rclone v1.36
rclone-v1.36-33-g7d9faffβ
```

Everything has been uploaded from acd with `rclone v1.36`. About 300 folders at this point.

**Comment by ajkis** [comment]
Something is off with latest beta
rclone size gdrive: is giving me wrong info

The website reports 60,3 TB ( correct / same value on ACD )

ACD FILES & SIZE (rclone size acd:/crypt)
Total objects: 46414
Total size: 61737.670 GBytes (66290318868698 Bytes)
24.04.2017/13:47 ACD: It took 201 seconds

GDRIVE FILE & SIZE (rclone size gdrive:/crypt)
Total objects: 40265
Total size: 39090.101 GBytes (41972676663843 Bytes)
24.04.2017/13:47 GDRIVE: It took  286 seconds


p.s. also rclone sync does not update mod times on gdrive for existing files (  its like default behavior is same as --no-update-modtime )

**Comment by ncw** [comment]
Here is the fix for the missing files, and it should fix your size problem too @ajkis 

https://beta.rclone.org/v1.36-35-gdd968a8/ (uploaded in 15-30 mins)

Thanks @azgul

**Comment by felixbuenemann** [comment]
I'm still running into "User Rate Limit Exceeded" within seconds on v1.36-41 when doing *server side* copies, eg. to create unlinked copies of a shared folder, even with `--transfers 1`.

It looks to me like rclone is not trying to adhere to the rate limiting by throttling request to a certain rate, but instead works as fast as it can until it gets rate limited and then uses the pacer for exponential back-off, however that doesn't seem to work well with google drive's rate limiting.

Here a screenshot of the api usage graph when using my own client id (throttlin happens just as fast with rclone's built-in client id):

![google api console screenshot](https://www.dropbox.com/s/i05l6ouqkb5i7fz/Screenshot%202017-04-27%2001.27.57.png?dl=1)

My ping to the google drive servers is around 18ms, so both skipping over existing identical files and copying new files is very fast.

**Comment by ncw** [comment]
@felixbuenemann This probably merits its own issue.

> It looks to me like rclone is not trying to adhere to the rate limiting by throttling request to a certain rate, but instead works as fast as it can until it gets rate limited and then uses the pacer for exponential back-off, however that doesn't seem to work well with google drive's rate limiting.

rclone will limit requests to 100/s normally with drive.  If it gets a 403 then it does exponential back-off.  As far as I know this is the correct way of working with drive - why doesn't it work well for you?

You can experiment with changing the `minSleep` parameter in `drive/drive.go` and see what difference that makes.

Are you using your own credentials or rclones?

**Comment by ncw** [comment]
The fields parameter is now working properly, so I'm going to close this issue now.
