### ISSUE TITLE
Any way to run rclone from python other than using os.system(' ') ? ie without using rclone shell commands. 

### ISSUE THREAD

**Issue by PrinceShaji** [ncw/rclone#1347]
Hi there, total noob here. Sorry if I sound stupid.

I am doing a project and right now, we use os.system(' ') to upload files to googledrive (rclone copy local remote). I am just wondering if we can do this using python language without having to use the shell command. 

It'd be great if someone could help me improve my script (StreamBox/pycam.py). Sorry for the crappy code. I'm only learning. 

Thanks :)

**Comment by calisro** [comment]
subprocess.call ?

**Comment by ncw** [comment]
There isn't a python library for rclone I'm afraid.  So `os.system` or better as @calisro suggested use the subprocess module.  I'd probably use `subprocess.check_call` in fact (but hey, I contributed that to python a long time ago ;-)

**Comment by jaketame** [comment]
I would use Popen

        command = ([RCLONE, 'move', '--log-file=rclone_upload.log', '--transfers', RCLONE_TRANSFERS, '--drive-chunk-size=16M', '--exclude', 'filepart', LOCAL_DIR + dir + '/', REMOTE_NAME  + REMOTE_DIR + dir + '/'])
        result = subprocess.Popen(command)
        result.communicate()

**Comment by cropse** [comment]
`Popen` is the best solution I guess, otherwise someone wrapping to the api, but I think it is not necessary

**Comment by PrinceShaji** [comment]
Thanks a lot. I hope there will be a python library for rclone in the future.

**Comment by ddragosd** [comment]
Good idea. I've published a python package for `rclone` at https://pypi.org/project/python-rclone/

**Comment by cjangrist** [comment]
I've had great success and ease using standard binary and the cli python wrapper lib sh

https://amoffat.github.io/sh/
