### ISSUE TITLE
No progress bar while uploading.

### ISSUE THREAD

**Issue by PrinceShaji** [ncw/rclone#1348]
rclone-v1.36-linux-arm
Raspberry Pi 3

When using rclone copy, there is no progress bar or ETA. Sometimes it looks like it is stuck.

**Comment by ncw** [comment]
Use -v flag to show some more progress.

Or when I've done #1180 you can just use --stats.

**Comment by ncw** [comment]
I've fixed this by adding a new flag, use `--stats-log-level NOTICE` to see the stats without using `-v`

https://beta.rclone.org/v1.36-219-gaa204864/ (uploaded in 15-30 mins)

**Comment by dandv** [comment]
`rclone sync remote:dir ./ --stats-log-level NOTICE` didn't show any stats for me, but files were being created locally. rclone v1.38.

**Comment by cy18** [comment]
-v works, and -vvvv shows much more information。
I don't think the default "verbose=-1" is a good idea, what's the consideration?

**Comment by riopardo** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  monitoramento@wktecno.com
    Domain wktecnomedia.com has exceeded the max emails per hour (340/300 (113%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o11.sgmail.github.com ([167.89.101.202]:13051)
	by hcomm35.dns-wk.info with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89)
	(envelope-from <bounces+848413-9a47-wao=agencia.pw@sgmail.github.com>)
	id 1eHljV-0003R7-5d
	for wao@agencia.pw; Thu, 23 Nov 2017 05:15:42 -0200
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=Af3yNE8F0m6JuEee4rsICO9dqvI=; b=b93XhsZBc1fHOCnX
	xLNFrJA7Pm66zXATeWle63j0ciTBSVP17oEAdrMVJfE9OAmGPc6MeaYbVcSdivbC
	7yitm9XjpCZ2YcCF437yqFSgPAqoCEdpU6M1S/vb07B3Q5deRXnDq2gpKwLgPEyP
	NKD97y5gK0uHe4D5XsKkGAkIUwI=
Received: by filter0151p1iad2.sendgrid.net with SMTP id filter0151p1iad2-24698-5A167597-1
        2017-11-23 07:15:35.109226187 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0008p1iad1.sendgrid.net (SG) with ESMTP id zpAIqojPTZiRrFTtBo7oZA
	for <wao@agencia.pw>; Thu, 23 Nov 2017 07:15:34.985 +0000 (UTC)
Date: Thu, 23 Nov 2017 07:15:35 +0000 (UTC)

**Comment by ncw** [comment]
I think this issue is now done!

**Comment by kpcyrd** [comment]
I've just started using rclone and was very confused by the lack of progress indication and the output of `-v` wasn't what I expected. Please have a look how this is done in git-annex, its interface is quite pleasant to use.

Progressbars would be very appreciated compared to upload-status-snapshots being written through a logging system every minute, which seems a bit user unfriendly.

If there is an option to enable the progressbar, please let me know how! :)

**Comment by ncw** [comment]
@kpcyrd this is in progress in #2347 - would appreciate your input there.  If you could do an https://asciinema.org/ of what git-annex looks like that would be very helpful.

**Comment by diman82** [comment]
--progress --stats-one-line works like a charm
