### ISSUE TITLE
Option to create links to google documents instead of converting it

### ISSUE THREAD

**Issue by pckapps** [ncw/rclone#1349]
When syncing with Google Drive, would it be possible to add an option so that links to google documents are created instead of converting the files? Double clicking on the file should then open the browser with the relevant file. I believe this is how it works when using the official Drive client by Google. This should be similar to how "--drive-skip-gdocs" works.

**Comment by ncw** [comment]
How does that actually work?  What type of file is created and what is in it?  I suspect this intercepted by the google drive client somehow.

**Comment by pckapps** [comment]
Yes, the Google Drive client creates a file called "WorkbookName.gsheet". Inside is simple json, something like this:

```
{"url": "https://docs.google.com/open?id=aaabbbccc",
"doc_id": "aaabbbccc",
"email": "myname@gmail.com",
"resource_id": "document:aaabbbccc"}
```

My suggestion is to create a similar file that natively opens the link in the browser. It's not ideal to edit my Google documents in Libre office and uploading it back to Google Drive.

What do you think?

**Comment by agilmor** [comment]
The solution/alternative that [odeke-em/drive](https://github.com/odeke-em/drive) client does is to create a ``.desktop`` for all google docs with this fields:
```
Type=Link
URL=https://drive.google.com/...
```
I guess that it's the same idea, but for Linux.

This also works for other Drive but not Docs files like Zoho's ones, etc...
I'm movimng from odeke-em/drive to rclone and I'm missing this feature... so +1 to this feature!!

Thanks!

**Comment by crysman** [comment]
:+1:  for this, as **this is how the official Google Drive Stream client behaves on Windows**. Would be great if this client behaved the same way! I am now looking for some good working alternative to Google Drive Stream, but not yet successfully because of this :(

**Comment by ncw** [comment]
Does anyone want to work on this issue?

I'm happy to talk people through what needs to be done.

**Comment by B4dM4n** [comment]
I have looked a bit into this issue while working on Google documents uploads.

It seems like there are different concepts of `link` files:

Windows and macOS have `.url` files.
```ini
[InternetShortcut]
URL=https://rclone.org/
```
Source: [stackoverflow](https://superuser.com/questions/689441/how-do-i-create-a-url-file-on-os-x)

macOS also has `.webloc` files.
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>URL</key>
    <string>https://rclone.org/</string>
</dict>
</plist>
```
Source: [stackoverflow](https://stackoverflow.com/questions/146575/crafting-webloc-file)

Linux has `.desktop` files.
```ini
[Desktop Entry]
Encoding=UTF-8
Name=rclone.org
URL=https://rclone.org/
Icon=text-html
```
Source: [stackoverflow](https://superuser.com/questions/986527/how-to-create-a-hyperlink-file#986543)

A simple cross platform solution could use `.html` files:
```html
<html>
<head>
<meta http-equiv="refresh" content="0; url=https://rclone.org/" />
</head>
</html>
```
Source: [stackoverflow](https://superuser.com/questions/986527/how-to-create-a-hyperlink-file#986533)

To be cross platform compatible we should implement at least `.html` files and probably `.url` and `.desktop` files for native users.

I will try to integrate this into my current work at uploading documents.

**Comment by Fabian42** [comment]
Comment history:
Part 1: https://github.com/cjnaz/RCloneSync/issues/22
Part 2: https://github.com/cjnaz/rclonesync-V2/issues/1
Part 3: https://github.com/ncw/rclone/issues/2413

In short: Not having this option completely breaks Google Drive sync for me (which I need for other programs). RClone sees Google documents as having file size -1 and doesn't properly copy back and forth, that messes up RCloneSync, which fails to build a file index that is needed for two-way sync.

**Comment by ncw** [comment]
@Fabian42 there is always this flag

      --drive-skip-gdocs                      Skip google documents in all listings.

which will make syncs work properly just skipping the google docs.

**Comment by B4dM4n** [comment]
There has been progress for this issue:
#2479 is a work in progress rewrite of the drive documents handling. 
If anyone wants to help testing the new implementation, there is a beta branch containing the changes: https://beta.rclone.org/branch/v1.42-162-g6a66967c-drive-documents/

**Keep in mind this is not tested thoroughly yet and therefore be considered experimental.**

Please post any feedback in #2479. Updated releases will also be anounced there.

**Comment by B4dM4n** [comment]
#2479 has been merged lately.

This feature can be used since https://beta.rclone.org/v1.43-112-ga20fae03-beta/, the [latest beta](https://beta.rclone.org/) and in v1.44
