### ISSUE TITLE
Rclone mount rate limited / rate exceeded

### ISSUE THREAD

**Issue by trippinshrumes** [ncw/rclone#1351]
When filing an issue, please include the following information if possible as well as a description of the problem.  Make sure you test with the latest beta of rclone.

    https://beta.rclone.org/
    https://rclone.org/downloads/

If you've just got a question or aren't sure if you've found a bug then please use the [rclone forum](https://forum.rclone.org/) instead of filing an issue.

> What is your rclone version (eg output from `rclone -V`)
v1.36
> Which OS you are using and how many bits (eg Windows 7, 64 bit)
UBUNTU 16.04
> Which cloud storage system are you using? (eg Google Drive)
Amazon Drive
> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
I use "/home/plex/library/scripts/rclone mount secret: /home/plex/library/.acd &" to mount the amazon drive. secret: is tied to a folder within my amazon drive
> A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
plex@ZZeus:~/library/scripts$ /home/plex/library/scripts/rclone mount secret: /home/plex/library/.acd -vv
2017/04/18 22:33:02 DEBUG : rclone: Version "v1.36" starting with parameters ["/home/plex/library/scripts/rclone" "mount" "secret:" "/home/plex/library/.acd" "-vv"]
2017/04/18 22:33:03 DEBUG : pacer: Rate limited, sleeping for 287.113937ms (1 consecutive low level retries)
2017/04/18 22:33:03 DEBUG : pacer: low level retry 1/10 (error HTTP code 429: "429 Too Many Requests": response body: "{\"message\":\"Rate exceeded\"}")
2017/04/18 22:33:04 DEBUG : pacer: Rate limited, sleeping for 549.16732ms (2 consecutive low level retries)
2017/04/18 22:33:04 DEBUG : pacer: low level retry 2/10 (error HTTP code 429: "429 Too Many Requests": response body: "{\"message\":\"Rate exceeded\"}")
2017/04/18 22:33:04 DEBUG : pacer: Rate limited, sleeping for 3.632969758s (3 consecutive low level retries)
2017/04/18 22:33:04 DEBUG : pacer: low level retry 3/10 (error HTTP code 429: "429 Too Many Requests": response body: "{\"message\":\"Rate exceeded\"}")
2017/04/18 22:33:04 DEBUG : pacer: Rate limited, sleeping for 5.331776148s (4 consecutive low level retries)
2017/04/18 22:33:04 DEBUG : pacer: low level retry 4/10 (error HTTP code 429: "429 Too Many Requests": response body: "{\"message\":\"Rate exceeded\"}")
2017/04/18 22:33:08 DEBUG : pacer: Rate limited, sleeping for 13.183117216s (5 consecutive low level retries)
2017/04/18 22:33:08 DEBUG : pacer: low level retry 5/10 (error HTTP code 429: "429 Too Many Requests": response body: "{\"message\":\"Rate exceeded\"}")
2017/04/18 22:33:13 DEBUG : pacer: Rate limited, sleeping for 24.480279449s (6 consecutive low level retries)
2017/04/18 22:33:13 DEBUG : pacer: low level retry 6/10 (error HTTP code 429: "429 Too Many Requests": response body: "{\"message\":\"Rate exceeded\"}")
^C
plex@ZZeus:~/library/scripts$ sudo vi mount.sh
plex@ZZeus:~/library/scripts$ /bin/fusermount -uz /home/plex/library/.acd
plex@ZZeus:~/library/scripts$ /bin/fusermount -uz /home/plex/library/media
plex@ZZeus:~/library/scripts$ /home/plex/library/scripts/rclone mount secret: /home/plex/library/.acd -vv
2017/04/18 22:33:40 DEBUG : rclone: Version "v1.36" starting with parameters ["/home/plex/library/scripts/rclone" "mount" "secret:" "/home/plex/library/.acd" "-vv"]
2017/04/18 22:33:41 DEBUG : pacer: Rate limited, sleeping for 666.145821ms (1 consecutive low level retries)
2017/04/18 22:33:41 DEBUG : pacer: low level retry 1/10 (error HTTP code 429: "429 Too Many Requests": response body: "{\"message\":\"Rate exceeded\"}")
2017/04/18 22:33:41 DEBUG : pacer: Rate limited, sleeping for 235.010051ms (2 consecutive low level retries)
2017/04/18 22:33:41 DEBUG : pacer: low level retry 2/10 (error HTTP code 429: "429 Too Many Requests": response body: "{\"message\":\"Rate exceeded\"}")
2017/04/18 22:33:41 DEBUG : pacer: Rate limited, sleeping for 287.113937ms (3 consecutive low level retries)
2017/04/18 22:33:41 DEBUG : pacer: low level retry 3/10 (error HTTP code 429: "429 Too Many Requests": response body: "{\"message\":\"Rate exceeded\"}")
2017/04/18 22:33:42 DEBUG : pacer: Rate limited, sleeping for 4.54916732s (4 consecutive low level retries)
2017/04/18 22:33:42 DEBUG : pacer: low level retry 4/10 (error HTTP code 429: "429 Too Many Requests": response body: "{\"message\":\"Rate exceeded\"}")
2017/04/18 22:33:42 DEBUG : pacer: Rate limited, sleeping for 7.632969758s (5 consecutive low level retries)
2017/04/18 22:33:42 DEBUG : pacer: low level retry 5/10 (error HTTP code 429: "429 Too Many Requests": response body: "{\"message\":\"Rate exceeded\"}")
2017/04/18 22:33:46 DEBUG : pacer: Rate limited, sleeping for 21.331776148s (6 consecutive low level retries)
2017/04/18 22:33:46 DEBUG : pacer: low level retry 6/10 (error HTTP code 429: "429 Too Many Requests": response body: "{\"message\":\"Rate exceeded\"}")
2017/04/18 22:33:54 DEBUG : pacer: Resetting sleep to minimum 20ms on success
2017/04/18 22:34:16 DEBUG : pacer: Rate limited, sleeping for 760.398084ms (1 consecutive low level retries)
2017/04/18 22:34:16 DEBUG : pacer: low level retry 1/10 (error HTTP code 429: "429 Too Many Requests": response body: "{\"message\":\"Rate exceeded\"}")
2017/04/18 22:34:16 DEBUG : pacer: Rate limited, sleeping for 263.669287ms (2 consecutive low level retries)
2017/04/18 22:34:16 DEBUG : pacer: low level retry 2/10 (error HTTP code 429: "429 Too Many Requests": response body: "{\"message\":\"Rate exceeded\"}")
2017/04/18 22:34:17 DEBUG : pacer: Resetting sleep to minimum 20ms on success
2017/04/18 22:34:17 DEBUG : pacer: Rate limited, sleeping for 884.491574ms (1 consecutive low level retries)
2017/04/18 22:34:17 DEBUG : pacer: low level retry 1/10 (error HTTP code 429: "429 Too Many Requests": response body: "{\"message\":\"Rate exceeded\"}")
2017/04/18 22:34:17 DEBUG : pacer: Rate limited, sleeping for 1.414458836s (2 consecutive low level retries)
2017/04/18 22:34:17 DEBUG : pacer: low level retry 2/10 (error HTTP code 429: "429 Too Many Requests": response body: "{\"message\":\"Rate exceeded\"}")
2017/04/18 22:34:18 DEBUG : pacer: Rate limited, sleeping for 3.211445515s (3 consecutive low level retries)
2017/04/18 22:34:18 DEBUG : pacer: low level retry 3/10 (error HTTP code 429: "429 Too Many Requests": response body: "{\"message\":\"Rate exceeded\"}")
2017/04/18 22:34:19 DEBUG : pacer: Resetting sleep to minimum 20ms on success
2017/04/18 22:34:19 DEBUG : pacer: Rate limited, sleeping for 838.182873ms (1 consecutive low level retries)
2017/04/18 22:34:19 DEBUG : pacer: low level retry 1/10 (error HTTP code 429: "429 Too Many Requests": response body: "{\"message\":\"Rate exceeded\"}")
2017/04/18 22:34:19 DEBUG : pacer: Rate limited, sleeping for 1.472644968s (2 consecutive low level retries)
2017/04/18 22:34:19 DEBUG : pacer: low level retry 2/10 (error HTTP code 429: "429 Too Many Requests": response body: "{\"message\":\"Rate exceeded\"}")
2017/04/18 22:34:20 DEBUG : pacer: Resetting sleep to minimum 20ms on success
2017/04/18 22:34:22 DEBUG : pacer: Rate limited, sleeping for 910.584091ms (1 consecutive low level retries)
2017/04/18 22:34:22 DEBUG : pacer: low level retry 1/10 (error HTTP code 429: "429 Too Many Requests": response body: "{\"message\":\"Rate exceeded\"}")
2017/04/18 22:34:22 DEBUG : pacer: Rate limited, sleeping for 539.11079ms (2 consecutive low level retries)
2017/04/18 22:34:22 DEBUG : pacer: low level retry 2/10 (error HTTP code 429: "429 Too Many Requests": response body: "{\"message\":\"Rate exceeded\"}")
2017/04/18 22:34:23 DEBUG : pacer: Resetting sleep to minimum 20ms on success
2017/04/18 22:34:23 INFO  : Encrypted amazon drive root 'ZZeus': Modify window not supported
2017/04/18 22:34:23 DEBUG : Encrypted amazon drive root 'ZZeus': Mounting on "/home/plex/library/.acd"
2017/04/18 22:34:23 DEBUG : Encrypted amazon drive root 'ZZeus': Root()
2017/04/18 22:34:24 DEBUG : : Dir.Attr valid=1m0s ino=0 size=0 mode=drwxrwxr-x
2017/04/18 22:34:24 DEBUG : : Dir.ReadDirAll
2017/04/18 22:34:24 DEBUG : : Reading directory
2017/04/18 22:34:24 DEBUG : amazon drive root 'ZZeus': Reading ""
2017/04/18 22:34:25 DEBUG : amazon drive root 'ZZeus': Finished reading ""
2017/04/18 22:34:25 DEBUG : : Dir.ReadDirAll OK with 5 entries
2017/04/18 22:34:25 DEBUG : Tv Shows: Dir.Lookup
2017/04/18 22:34:25 DEBUG : Tv Shows: Dir.Lookup OK
2017/04/18 22:34:25 DEBUG : Tv Shows: Dir.Attr valid=1m0s ino=0 size=0 mode=drwxrwxr-x
2017/04/18 22:34:25 DEBUG : Movies: Dir.Lookup
2017/04/18 22:34:25 DEBUG : Movies: Dir.Lookup OK
2017/04/18 22:34:25 DEBUG : Movies: Dir.Attr valid=1m0s ino=0 size=0 mode=drwxrwxr-x
2017/04/18 22:34:25 DEBUG : Sports: Dir.Lookup
2017/04/18 22:34:25 DEBUG : Sports: Dir.Lookup OK
2017/04/18 22:34:25 DEBUG : Sports: Dir.Attr valid=1m0s ino=0 size=0 mode=drwxrwxr-x
2017/04/18 22:34:25 DEBUG : Stand Ups: Dir.Lookup
2017/04/18 22:34:25 DEBUG : Stand Ups: Dir.Lookup OK
2017/04/18 22:34:25 DEBUG : Stand Ups: Dir.Attr valid=1m0s ino=0 size=0 mode=drwxrwxr-x
2017/04/18 22:34:37 DEBUG : : Dir.Attr valid=1m0s ino=0 size=0 mode=drwxrwxr-x
2017/04/18 22:34:37 DEBUG : : Dir.ReadDirAll
2017/04/18 22:34:37 DEBUG : : Dir.ReadDirAll OK with 5 entries
2017/04/18 22:34:37 DEBUG : : Dir.Attr valid=1m0s ino=0 size=0 mode=drwxrwxr-x
2017/04/18 22:34:39 DEBUG : Movies: Dir.ReadDirAll
2017/04/18 22:34:39 DEBUG : Movies: Reading directory
2017/04/18 22:34:39 DEBUG : pacer: Rate limited, sleeping for 853.353331ms (1 consecutive low level retries)
2017/04/18 22:34:39 DEBUG : pacer: low level retry 1/10 (error HTTP code 429: "429 Too Many Requests": response body: "{\"message\":\"Rate exceeded\"}")
2017/04/18 22:34:39 DEBUG : pacer: Rate limited, sleeping for 324.778273ms (2 consecutive low level retries)
2017/04/18 22:34:39 DEBUG : pacer: low level retry 2/10 (error HTTP code 429: "429 Too Many Requests": response body: "{\"message\":\"Rate exceeded\"}")
2017/04/18 22:34:40 DEBUG : pacer: Rate limited, sleeping for 3.138149956s (3 consecutive low level retries)
2017/04/18 22:34:40 DEBUG : pacer: low level retry 3/10 (error HTTP code 429: "429 Too Many Requests": response body: "{\"message\":\"Rate exceeded\"}")
2017/04/18 22:34:40 DEBUG : pacer: Rate limited, sleeping for 693.774911ms (4 consecutive low level retries)
2017/04/18 22:34:40 DEBUG : pacer: low level retry 4/10 (error HTTP code 429: "429 Too Many Requests": response body: "{\"message\":\"Rate exceeded\"}")
2017/04/18 22:34:44 DEBUG : pacer: Rate limited, sleeping for 14.183515637s (5 consecutive low level retries)
2017/04/18 22:34:44 DEBUG : pacer: low level retry 5/10 (error HTTP code 429: "429 Too Many Requests": response body: "{\"message\":\"Rate exceeded\"}")
2017/04/18 22:34:44 DEBUG : pacer: Rate limited, sleeping for 30.821866378s (6 consecutive low level retries)
2017/04/18 22:34:44 DEBUG : pacer: low level retry 6/10 (error HTTP code 429: "429 Too Many Requests": response body: "{\"message\":\"Rate exceeded\"}")
2017/04/18 22:34:58 DEBUG : pacer: Rate limited, sleeping for 33.342231109s (7 consecutive low level retries)
2017/04/18 22:34:58 DEBUG : pacer: low level retry 7/10 (error HTTP code 429: "429 Too Many Requests": response body: "{\"message\":\"Rate exceeded\"}")
2017/04/18 22:35:29 DEBUG : pacer: Rate limited, sleeping for 35.797652072s (8 consecutive low level retries)
2017/04/18 22:35:29 DEBUG : pacer: low level retry 8/10 (error HTTP code 429: "429 Too Many Requests": response body: "{\"message\":\"Rate exceeded\"}")

My issue is that after mounting, I can see the folders inside, I try to go inside one of those folders and run an ls though and that's where these last low level retries came from. I'm curious if this is an amazon issue or an rclone issue, and what the cause of this could be and what a fix for this issue might be. Also, after mounting rclone if trying to play any media through it I get these same errors.  I've seen this happening the past couple days when watching certain shows, although it's only temporary and will just cause the plex to stop playing for a minute or 2.  Now it's permanent. Thanks for the help!

**Comment by francesco2013** [comment]
Hi same issue here and a lot of other people that posted on the rclone forum. There is a new post just made that makes me think a lot cause apparently with acd_cli everything works. Did rclone's api access got  banned by ACD or something similar ?

**Comment by ali-l** [comment]
Same here

**Comment by animosity22** [comment]
It's happening on anything I can test with via the API. 

acd_cli
ARQ

also generate the same errors.

Same post here too-> https://www.reddit.com/r/DataHoarder/comments/664hbt/acd_upload_rate_limited_even_though_i_havent_used/

**Comment by tcf909** [comment]
Looks like ACD is maybe having some issues. Same issues here.

**Comment by ajkis** [comment]
Yup unusable atm 

> 2017/04/19 07:12:01 INFO  : Starting bandwidth limiter at 100MBytes/s
> 2017/04/19 07:12:01 DEBUG : rclone: Version "v1.36-22-gbc25190β" starting with parameters ["/usr/bin/rclone" "copy" "gdrive:" "acdde:" "-vv" "--bwlimit=100M" "--transfers=50" "--checkers=50" "--log-file=/home/plex/logs/gdrive2acdde.cron.log"]
> 2017/04/19 07:12:01 DEBUG : pacer: Rate limited, sleeping for 287.113937ms (1 consecutive low level retries)
> 2017/04/19 07:12:01 DEBUG : pacer: low level retry 1/10 (error HTTP code 429: "429 Too Many Requests": response body: "{\"message\":\"Rate exceeded\"}")
> 2017/04/19 07:12:02 DEBUG : pacer: Rate limited, sleeping for 549.16732ms (2 consecutive low level retries)
> 2017/04/19 07:12:02 DEBUG : pacer: low level retry 2/10 (error HTTP code 429: "429 Too Many Requests": response body: "{\"message\":\"Rate exceeded\"}")
> 2017/04/19 07:12:02 DEBUG : pacer: Rate limited, sleeping for 3.632969758s (3 consecutive low level retries)
> 2017/04/19 07:12:02 DEBUG : pacer: low level retry 3/10 (error HTTP code 429: "429 Too Many Requests": response body: "{\"message\":\"Rate exceeded\"}")
> 2017/04/19 07:12:02 DEBUG : pacer: Rate limited, sleeping for 5.331776148s (4 consecutive low level retries)
> 2017/04/19 07:12:02 DEBUG : pacer: low level retry 4/10 (error HTTP code 429: "429 Too Many Requests": response body: "{\"message\":\"Rate exceeded\"}")
> 2017/04/19 07:12:06 DEBUG : pacer: Rate limited, sleeping for 13.183117216s (5 consecutive low level retries)
> 2017/04/19 07:12:06 DEBUG : pacer: low level retry 5/10 (error HTTP code 429: "429 Too Many Requests": response body: "{\"message\":\"Rate exceeded\"}")
> 2017/04/19 07:12:11 DEBUG : pacer: Rate limited, sleeping for 24.480279449s (6 consecutive low level retries)
> 2017/04/19 07:12:11 DEBUG : pacer: low level retry 6/10 (error HTTP code 429: "429 Too Many Requests": response body: "{\"message\":\"Rate exceeded\"}")
> 2017/04/19 07:12:25 DEBUG : pacer: Rate limited, sleeping for 54.760398084s (7 consecutive low level retries)
> 2017/04/19 07:12:25 DEBUG : pacer: low level retry 7/10 (error HTTP code 429: "429 Too Many Requests": response body: "{\"message\":\"Rate exceeded\"}")
> 2017/04/19 07:12:49 DEBUG : pacer: Rate limited, sleeping for 263.669287ms (8 consecutive low level retries)
> 2017/04/19 07:12:49 DEBUG : pacer: low level retry 8/10 (error HTTP code 429: "429 Too Many Requests": response body: "{\"message\":\"Rate exceeded\"}")
> 2017/04/19 07:13:44 DEBUG : pacer: Rate limited, sleeping for 2m26.884491574s (9 consecutive low level retries)
> 2017/04/19 07:13:44 DEBUG : pacer: low level retry 9/10 (error HTTP code 429: "429 Too Many Requests": response body: "{\"message\":\"Rate exceeded\"}")
> 2017/04/19 07:13:44 DEBUG : pacer: Rate limited, sleeping for 2m35.414458836s (10 consecutive low level retries)
> 2017/04/19 07:13:44 DEBUG : pacer: low level retry 10/10 (error HTTP code 429: "429 Too Many Requests": response body: "{\"message\":\"Rate exceeded\"}")
> 2017/04/19 07:13:44 Failed to create file system for "acdde:": failed to get endpoints: HTTP code 429: "429 Too Many Requests": response body: "{\"message\":\"Rate exceeded\"}"

**Comment by toomuchio** [comment]
If you login to Amazon's website web view is fine but storage calculations are 0 bytes, anybody else getting that? Sounds like something wrong at Amazon not an API limit.

**Comment by jbub** [comment]
@toomuchio yes also getting 0 bytes, i also see the rate limit messages

**Comment by francesco2013** [comment]
Same here and apparently according to the rclone forum all the third party apps have the same problem (acd_cli,arq and so on). Amazon closed them all ? End of the story ?

**Comment by vip32** [comment]
rclone + amazon (ACD) also stopped working for me. now i get the 429 (too many requests, message: rate exceeded). the behavior seems a lot like this older issue https://github.com/ncw/rclone/issues/472, however that had to do with the auth token and resulted in 401s.

seems like ACD is blocking any requests made by rclone at the moment, the rate exceeded messages comes right away. not a single file gets copied.

```
2017/04/19 08:59:31 pacer: Rate limited, sleeping for 947.77941ms (1 consecutive low level retries)
2017/04/19 08:59:31 pacer: low level retry 1/10 (error HTTP code 429: "429 Too Many Requests", reponse body: {"message":"Rate exceeded"}
)
2017/04/19 08:59:31 pacer: Rate limited, sleeping for 1.082153551s (2 consecutive low level retries)
2017/04/19 08:59:31 pacer: low level retry 2/10 (error HTTP code 429: "429 Too Many Requests", reponse body: {"message":"Rate exceeded"}
)
````

this would be very bad from amazon, hope this is just a hickup (not sure how long this has been misbehaving)

**Comment by vampywiz17** [comment]
Same with me. Amazon Close all API connections....

**Comment by vip32** [comment]
Did they announce anything?

**Comment by animosity22** [comment]
As I noted above, it isn't just rclone, it's all API at this point.

**Comment by vip32** [comment]
@animosity22 yes that's clear, i meant if amazon announced anything regarding this. so we know it's the new policy instead of a outage.

**Comment by trippinshrumes** [comment]
I contacted amazon, the devs came back and told me they want me to send them my logs from my amazon drive web gui... not sure if I want to do that. They should know if something changed in their platform and give me a proper answer.

**Comment by francesco2013** [comment]
Yep Amazon drive 3rd party (opensource) apps support is over. They are a shame.

**Comment by animosity22** [comment]
@francesco2013  - Where did you see that ?

**Comment by francesco2013** [comment]
@animosity22

Because all the 3rd party apps are having the same problems while all others services are working fine and customer support of acd keeps on saying everything is very fine on their side. They cut them all cause they got overloaded and of course they don't want this. It is also written in the service agreement that they can interrupt at any time without notice every non-compliance behavior. I got an account on Gsuite and bye bye Amazon.

**Comment by animosity22** [comment]
@francesco2013  - so no facts, just your opinion?

**Comment by francesco2013** [comment]
@animosity22 it is not MY opinion. Read the posts of the people on the rclone forum myself I tried rclone and acd_cli both not working and both with the same error. Other people are saying also ARQ has the same problem. Which "facts" do you need more ?

**Comment by Trentflix** [comment]
It's more of a conjecture than an opinion really. Although the latest news is it is a known issue and Amazon is working on it.

**Comment by animosity22** [comment]
@francesco2013 - lots of posts also in regards to a glitch with the API. 

Fact: Expandrive still works as a 3rd party app btw. I'm sure there are more but that's one that I personally confirmed as I've got that mounted on Windows box now copying over to my GDrive.

**Comment by francesco2013** [comment]
@animosity22 I am doing exactly the same using exactly the same app (Expandrive) and I am moving to my  GDrive. Leave the sinking ship leave and dont look back :) 

Expandrive is a commercial app btw

**Comment by animosity22** [comment]
Arq is also a commercial app. It's really all guessing until something is announced or released officially from amazon. My point was that commercial or non-commercial, you have some 3rd party apps that are working.

**Comment by francesco2013** [comment]
The whole thing is indeed very weird man

**Comment by animosity22** [comment]
@francesco2013  - fyi, working fine for me now via rclone.

**Comment by jbub** [comment]
yep seems like its fixed now

**Comment by vip32** [comment]
problem solved, sync is working again :) they must have fixed something on the ACD side.
hope it keeps working...

**Comment by trippinshrumes** [comment]
This is fixed, no point in keeping open, was clearly not an issue with rclone anyhow

**Comment by gimulnautti** [comment]
Seems like the problem came up again though..

`2017/05/18 20:12:17 Failed to create file system for "amazondrive:": failed to get endpoints: HTTP code 429: "429 Too Many Requests": response body: "{\"message\":\"Rate exceeded\"}"`

**Comment by francesco2013** [comment]
Indeed you should not use rclone to import your libraries with plex

**Comment by trippinshrumes** [comment]
I closed this, how is this being commented on?

**Comment by chimpy** [comment]
Closing an issue doesn't stop comments. Only limiting comments to contributors only or something like that can stop comments.

You can unsubscribe from the thread though.
