### ISSUE TITLE
[AWS authentication] To support named profiles

### ISSUE THREAD

**Issue by n-my** [ncw/rclone#1352]
Rclone let us use 3 ways to authenticate to AWS
- credentials in the rclone config file
- credentials as env vars
- EC2 IAM role

This misses the preferred way to authenticate to AWS : [the named profiles](http://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html#cli-multiple-profiles)

This ticket is about supporting this feature. Rclone would read the env var `AWS_DEFAULT_PROFILE` and then get the right credentials from the file ~/.aws/credentials

**Comment by ncw** [comment]
I'd be happy to receive a PR for this if you wanted to help?

**Comment by n-my** [comment]
I won't send a PR for the moment since don't have enough time but I might do it in a couple of month if no one else is interested in developing this feature.

**Comment by n-my** [comment]
I'm not using rclone anymore and I won't spend time on this issue so I'm closing it. Thanks for your reply.

**Comment by siran** [comment]
this would be indeed a nice to have feature

**Comment by siran** [comment]
@n-my what tool are you using now?

**Comment by ncw** [comment]
@siran are you sure this doesn't work now if you set `env_auth = true` in the config?

**Comment by derekhh** [comment]
@ncw - Yes. I can confirm this doesn't work now even if we set `env_auth = true`.

**Comment by ncw** [comment]
I'll re-open this then.

I've made this work with `env_auth = true` in the config file.

@siran @derekhh Can you have a go with this beta?

https://beta.rclone.org/v1.40-086-ga9e27dda-fix-1352-s3-auth/ (uploaded in 15-30 mins)

Note the new docs:

### Authentication ###

There are a number of ways to supply `rclone` with a set of AWS
credentials, with and without using the environment.

The different authentication methods are tried in this order:

 - Directly in the rclone configuration file (`env_auth = false` in the config file):
   - `access_key_id` and `secret_access_key` are required.
   - `session_token` can be optionally set when using AWS STS.
 - Runtime configuration (`env_auth = true` in the config file):
   - Export the following environment variables before running `rclone`:
     - Access Key ID: `AWS_ACCESS_KEY_ID` or `AWS_ACCESS_KEY`
     - Secret Access Key: `AWS_SECRET_ACCESS_KEY` or `AWS_SECRET_KEY`
     - Session Token: `AWS_SESSION_TOKEN` (optional)
   - Or, use a [named profile](https://docs.aws.amazon.com/cli/latest/userguide/cli-multiple-profiles.html):
     - Profile files are standard files used by AWS CLI tools
     - By default it will use the profile in your home directory (eg `~/.aws/credentials` on unix based systems) file and the "default" profile, to change set these environment variables:
         - `AWS_SHARED_CREDENTIALS_FILE` to control which file.
         - `AWS_PROFILE` to control which profile to use.
   - Or, run `rclone` in an ECS task with an IAM role (AWS only).
   - Or, run `rclone` on an EC2 instance with an IAM role (AWS only).

If none of these option actually end up providing `rclone` with AWS
credentials then S3 interaction will be non-authenticated (see below).

**Comment by ncw** [comment]
I've merged this to master in

https://beta.rclone.org/v1.40-109-g311a9620/ (uploaded in 15-30 mins)

which will be in [the latest beta](https://beta.rclone.org) and 1.41

**Comment by derekhh** [comment]
Thanks @ncw! I did some test but maybe I was wrong - does this support named profile stored in the config files? For example, if I want to use [IAM roles in the form of named profiles](https://docs.aws.amazon.com/cli/latest/userguide/cli-roles.html), would this work? I tried to use it locally but doesn't seem to be working. :(

**Comment by ncw** [comment]
@derekhh I've tested using the `.aws/credentials` file works as per this doc: https://docs.aws.amazon.com/cli/latest/userguide/cli-multiple-profiles.html

It looks like [the docs say](https://docs.aws.amazon.com/sdk-for-go/api/aws/session/) if you set the environment variable `AWS_SDK_LOAD_CONFIG=true` or maybe `AWS_SDK_LOAD_CONFIG=1` it will load the config.

Can you see if that works?

If it does, do you think rclone should always look at that file (so you don't have to set the env var)?

**Comment by imw** [comment]
@ncw I've tested in 1.41 release, and while it appears to load the right credentials, it does not seem to assume the correct role, as discussed here: https://docs.aws.amazon.com/cli/latest/userguide/cli-roles.html

Let me know if I can provide further information.

**Comment by ncw** [comment]
@imw Sorry for the delay in replying...

I'm not really sure what is going on here.  Which environment variables have you got set?  Have you got `AWS_PROFILE` set?

Here are the SDK docs:

https://godoc.org/github.com/aws/aws-sdk-go#hdr-Configuring_Credentials

And here is the rclone code which does the config for the credentials:

https://github.com/ncw/rclone/blob/4d793b8ee842b177225e730a8c099edd54ccaeda/backend/s3/s3.go#L634-L658

Any ideas on what I'm doing wrong?

**Comment by eriksw** [comment]
Note: the version of aws-sdk-go in rclone 1.44 doesn't handle:
    [myprofile]
    credential_source = Ec2InstanceMetadata
    role_arn = arn:aws:iam::...

See: https://github.com/aws/aws-sdk-go/commit/16cef773033e77d97f42fa5655c13bace6b9edc7

I think master is already up to date with a version of aws-sdk-go that does support it, however.

**Comment by oscarg933** [comment]
Oscarg933.github.io

**Comment by eriksw** [comment]
Ah, nevermind, upstream support is still interfering with my use case for this.

See: https://github.com/aws/aws-sdk-go/issues/1019
