### ISSUE TITLE
No info during sync, not sure if it

### ISSUE THREAD

**Issue by michaldybczak** [ncw/rclone#1358]
After typing: rclone sync /home/michaldybczak/GoogleDrive/ remote:Backup
I was getting some verbose info on what is happening. Now it just moves cursor to the next line and nothing more. Since I am sending large files, I can't check if it's working. Is there any way to troubleshoot it?

**Comment by Qwatuz** [comment]
use -v or -vv on the end.

https://rclone.org/docs/#log-file-file

**Comment by michaldybczak** [comment]
Thanks, It worked with -v parameter. I deleted a bunch of big files in google drive (I though I was running out of space, because of this strange issue) and forgot to do the same on my computer so the whole transfer would take several hours. That is why without verbose response, it seemed not to do anything.

Although, why did I have a verbose mode without -v for over a year or even two on different computers and system installs? I always just hit the command as above and I was shown info what was being done. Is that some sort of latest "improvement" to mute the output and introduce -v?

**Comment by ncw** [comment]
> Is that some sort of latest "improvement" to mute the output and introduce -v?

Yes.  The aim was to make rclone behave more like rsync which is quiet unless you add `-v`.  It has caught a  lot of people out though, so apologies!

**Comment by michaldybczak** [comment]
Ah, so I'm not crazy after all ;). Thanks for the explanation.
