### ISSUE TITLE
Multiple Part File with maximum Size

### ISSUE THREAD

**Issue by Firemad03** [ncw/rclone#1360]
Hi,

I didn't find a way to do it and I'm sorry if rclone already have this option.

I know that Amazon Drive and others cloud storage have a limit for the maximum file size.

Does rclone have a way to create multiple file with a maximum of 2 gigs ? Like winzip or others like that do.

I want to encrypt my files, set a maximum file size for each file and sync it back to the cloud.

Is it possible with rclone ?

**Comment by Firemad03** [comment]
tar with lz4 will do the job if I do it before rclone but I wanted to know if it's possible without it or you are planning to support it in the future ?

**Comment by ncw** [comment]
There is an issue about that here: #497 - can you add your support to that and close this one please.

**Comment by Firemad03** [comment]
@ncw  Thanks ! I will.
