### ISSUE TITLE
google drive v1.36 hung transfers

### ISSUE THREAD

**Issue by felixbuenemann** [ncw/rclone#1362]
There appears to be a regression in current builds of rclone v1.36 (recently tested on build 31 and 33, but noticed in earlier builds as well) at least on osx-amd64:

Transfers to google drive simply hang with no output from rclone, this even happens with server side copies, where rclone might show a file as checking or transferring forever.

I'm not sure what causes this or how to best debug it, however switching back to v1.35 fixes the problem.

I have not tested with other remoted recently, so this issue might not be drive specific.

Please advise what options to run rclone with to debug this issue.

**Comment by francesco2013** [comment]
I confirm same problems all of a sudden. 

2017/04/24 01:41:37 DEBUG : XXXXXXXX: File.Open OpenReadOnly
2017/04/24 01:41:39 ERROR : XXXXXXXX: File.Open failed: open for read: bad response: 403: 403 Forbidden
2017/04/24 01:41:39 DEBUG : XXXXXXXX: File.Open OpenReadOnly
2017/04/24 01:41:39 ERROR : XXXXXXXX: File.Open failed: open for read: bad response: 403: 403 Forbidden
2017/04/24 01:42:00 DEBUG : XXXXXXXX: File.Open OpenReadOnly
2017/04/24 01:42:00 ERROR : XXXXXXXX: File.Open failed: open for read: bad response: 403: 403 Forbidden
2017/04/24 01:42:00 DEBUG : XXXXXXXX: File.Open OpenReadOnly
2017/04/24 01:42:00 ERROR : XXXXXXXX: File.Open failed: open for read: bad response: 403: 403 Forbidden
2017/04/24 01:42:00 DEBUG : XXXXXXXX: File.Open OpenReadOnly
2017/04/24 01:42:01 ERROR : XXXXXXXX: File.Open failed: open for read: bad response: 403: 403 Forbidden


Same repeated hundreds of times

**Comment by felixbuenemann** [comment]
@francesco2013 not sure that's the same error, your log output looks like rate limiting or temporary account ban.

**Comment by francesco2013** [comment]
I had it all of a sudden on my account with gsuite. I have it mounted on two machines and Plex Cloud.

here is the mount:

/bin/rclone mount GsuiteXXXXXt:Plex_Media /mnt/googledrive --buffer-size 256M --allow-other --gid 113 --uid 108 -vv --log-file /var/log/rclone-gdrive.log

**Comment by ncw** [comment]
@felixbuenemann 
> Transfers to google drive simply hang with no output from rclone, this even happens with server side copies, where rclone might show a file as checking or transferring forever.

I'm not seeing this with a very brief test.

Can you try running with `-vv --dump-bodies` (you probably tried this already though).

If no joy with that then try `strace` and see if that gives any clues.

Is it some kind of networking problem?  DNS resolution hanging?

**Comment by felixbuenemann** [comment]
I tried running with `-v`, haven't tried `-vv` or `--dump-bodies` yet. There's no `strace` on macOS, but `dtruss` should probably do the trick.

**Comment by felixbuenemann** [comment]
@francesco2013 I think you account is locked out, it can happen for example if there's too much traffic and should unlock automatically after 24 hours. Please open a new issue or post on the rclone forum if the issue persist, to keep the discussion on this issue focused.

**Comment by felixbuenemann** [comment]
I have a feeling this might be related to #1150, because on v1.35 I would often get the "x509: certificate signed by unknown authority" at the first try invoking rclone, but it would work fine if retried.

I just retried a copy of a simple file and it hung on the first try (sadly forgot to add -vv to that call) but worked fine after hangup (Ctrl+C) and retry.

I also attached dtruss to the process after it had started, but it only showed incomplete info due to system integrity protection (SIP) being enabled, from what I could see, go was idling in an event loop:

```
…
select(0x0, 0x0, 0x0, 0x0, 0xC42003DF20)		 = 0 0
select(0x0, 0x0, 0x0, 0x0, 0xC42003DF20)		 = 0 0
write(0x6, "\0", 0x101D)		 = -1 Err#35
kevent(0x5, 0x0, 0x0)		 = 0 0
select(0x0, 0x0, 0x0, 0x0, 0xC42003DF20)		 = 0 0
kevent(0x5, 0x0, 0x0)		 = 1 0
dtrace: error on enabled probe ID 2132 (ID 165: syscall::write:return): invalid kernel access in action #12 at DIF offset 92
…
```

I'll retry with a full capture and SIP disabled.

**Comment by felixbuenemann** [comment]
I've yet to see this problem reappear after rebooting to change SIP settings and since upgrading to v1.36-35 and v1.36-41. One of my guesses is that the problem might be related to dead IPv6 addresses.

I'm using an ISP with dual stack support, so my Mac gets both an internal IPv4 address that is NATed by the router as well as a fixed and a temporary public IPv6 address. The temporary addresses are cycled regularly and the old ones stick around for some time to keep running TCP6 connections from failing.

However if for example the router looses its connection to the ISP it receives a new IPv6 prefix at which point the Mac now has IPv6 addresses from both the old and the new prefix, but the old ones are no longer routable.

This does not appear to cause any problems on Linux clients, but I've occasionally had issues with this on macOS where I had to reset the IPv6 addresses to get rid of the dead prefix.

I also noted that v1.35 was still built with go1.7 while v1.36 uses go1.8 or go1.8.1 in the latest builds and there where some changes related to IPv6/IPv4 fallback in go1.8:

> * The [DefaultTransport.Dialer](https://golang.org/pkg/net/http/#DefaultTransport) now enables DualStack ("[Happy Eyeballs](https://tools.ietf.org/html/rfc6555)") support, allowing the use of IPv4 as a backup if it looks like IPv6 might be failing.

Note that Google Drive supports both IPv4 and IPv6.

While this is a wild guess it would explain the strange behavior where rclone appeared to be completely stuck opening a network connection.

**Comment by ncw** [comment]
That sounds plausible...

You can adjust `/etc/gai.conf` (in linux - I expect there is an OSX equivalent) if you'd prefer to use IPv4 addresses if available.

If it happens again an IPv6 traceroute to the drive servers would tell you whether it is the problem or not.

**Comment by HeroCC** [comment]
Same issue here, doing only server side copies, 7 mins and 7 files copied. When running with `-vv --dump-bodies`, I get a lot of warnings about rate limits: 
```
2017/04/28 22:26:49 DEBUG : pacer: Rate limited, sleeping for 16.389300587s (34 consecutive low level retries)
2017/04/28 22:26:49 DEBUG : pacer: low level retry 9/10 (error googleapi: Error 403: User rate limit exceeded, userRateLimitExceeded)
```

**Comment by felixbuenemann** [comment]
@HeroCC This issue is not about rate limits, but about hung network connections.

**Comment by felixbuenemann** [comment]
I haven't seen this issue in a long time, will close for now.
