### ISSUE TITLE
[CRITICAL BUG] GDRIVE files/folders  missing 

### ISSUE THREAD

**Issue by ajkis** [ncw/rclone#1366]
latest rclone version 

rclone sync acd: gdrive: , website reports same size (60.3 TB on both) , but if i check:

> 24.04.2017/13:47 START
> ACD FILES & SIZE (rclone size acd:/crypt)
> Total objects: 46414
> Total size: 61737.670 GBytes (66290318868698 Bytes)
> 24.04.2017/13:47 ACD: It took 201 seconds
> 
> GDRIVE FILE & SIZE (rclone size gdrive:/crypt)
> Total objects: 40265
> Total size: 39090.101 GBytes (41972676663843 Bytes)
> 24.04.2017/13:47 GDRIVE: It took  286 seconds
> 
> 24.04.2017/13:47 ACD&GDRIVE SIZE: TOTAL TIME  487 seconds
> ACDCRYPT FILE/FOLDER COUNT
> 4951 directories, 46064 files
> 24.04.2017/13:47 ACD COUNT: It took 453 seconds
> GDRIVE FILE/FOLDER COUNT
> 2360 directories, 39892 files
> 24.04.2017/13:47 GDRIVE COUNT: It took  1694 seconds
> 24.04.2017/13:47 ACD&GDRIVE SIZE & COUNT: TOTAL TIME  2634 seconds

**Comment by ajkis** [comment]
In previous version is working 
```
rclone v1.36-22-gbc25190β
plex@sync /dev/shm/rclone-v1.36-22-gbc25190β-linux-amd64 $ rclone size gdrive:
Total objects: 46417
Total size: 61745.682 GBytes (66298920868818 Bytes)

```

**Comment by azgul** [comment]
#1367 should fix this. nextPageToken was missing

**Comment by ncw** [comment]
This should be fixed by

https://beta.rclone.org/v1.36-35-gdd968a8/ (uploaded in 15-30 mins)

**Comment by ajkis** [comment]
great closing issue
