### ISSUE TITLE
Rclone encryption file detection.

### ISSUE THREAD

**Issue by niranjanshr13** [ncw/rclone#1378]
This Issues isn't about **BUG** but actual remainder to user that online storage can know which file is encrypted by rclone.
When the file is upload through the crypt system. Anyone can detect that file is a rclone encrypted file. 
How it works:
[1]  Upload any file with crypt to the cloud.
[2]  Download that encrypt version from browser.
[3 ] Cat that file.

--
The header of file contain "RCLONE".
I don't know if that intentional for reference that rclone could detect to find which is encrypted version.

**Comment by roytomeij** [comment]
What's the issue exactly?

**Comment by 2600box** [comment]
that instead of appearing as random data, the data is broadcasting its origin as 'rclone'

**Comment by ncw** [comment]
> I don't know if that intentional for reference that rclone could detect to find which is encrypted version.

Yes that is right.

It is important that rclone can manage to detect its own files.  There are two nulls after rclone which I will use for file versioning eventually, then a header - all of which could be detected.  The underlying format for the blocks, nacl secretbox might also have some recognisable features (I'm not sure).

Every encryption system I've seen uses some kind of header...

**Comment by niranjanshr13** [comment]
@
