### ISSUE TITLE
rclone mount no longer working

### ISSUE THREAD

**Issue by Enf0** [ncw/rclone#1384]
Is there currently an issue with rclone? If I try to mount a remote (either GD or ACD) it just hangs, with no error message. I tried mounting different remotes on 3 different systems and the same problem occurs on all of them. 

Browsing the remote with 'ls' or Rclone Browser works fine, and browsing an existing mount seems to work too.

> What is your rclone version (eg output from `rclone -V`)
v.1.36

> Which OS you are using and how many bits (eg Windows 7, 64 bit)
Debian 8.7 x64

> Which cloud storage system are you using? (eg Google Drive)
Google Drive & Amazon Cloud Drive

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
```
# rclone mount -vv gd: /mnt/gd
2017/05/03 16:10:55 DEBUG : rclone: Version "v1.36" starting with parameters ["rclone" "mount" "-vv" "gd:" "/mnt/gd"]
2017/05/03 16:10:56 INFO  : Google drive root '': Modify window is 1ms
2017/05/03 16:10:56 DEBUG : Google drive root '': Mounting on "/mnt/gd"
2017/05/03 16:10:56 DEBUG : Google drive root '': Root()
```

**Comment by calisro** [comment]
The command hangs.  That is normal.  put a '&' on the end. and ls the directory.

**Comment by Enf0** [comment]
I'm stupid. Thanks..
