### ISSUE TITLE
rclone mount worked in a directory with existing files, causing problems on macOS

### ISSUE THREAD

**Issue by garypaduana** [ncw/rclone#1386]
If you've just got a question or aren't sure if you've found a bug then please use the [rclone forum](https://forum.rclone.org/) instead of filing an issue.

> What is your rclone version (eg output from `rclone -V`)

v1.36

> Which OS you are using and how many bits (eg Windows 7, 64 bit)

macOS Sierra Version 10.12.4
FUSE for macOS v3.5.6

> Which cloud storage system are you using? (eg Google Drive)

Amazon Cloud Drive, but any should work in this case

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

`rclone mount -vv ACD_crypt:/ ~/.`

> A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

I lost the output but everything worked when it should have failed because the directory was not empty.

I mounted my cloud drive to my home directory by mistake, I intended to mount it to `~/Mounts/acd`.  The mount worked, however, despite the directory not being empty.  This caused Finder to panic and reset all of my preferences for the application dock, Finder file browser, icons, wallpaper, etc.  It was like I just turned on a new computer or created a new user account.  I received an error message from MySQL Workbench stating that it could not write to a file in my home directory.  I then unmounted the rclone drive, restarted the computer, but it was still in the corrupted state.  I had to restore my user directory from a Time Machine backup to get everything back to a good state.  Existing files were still present such as Documents and Downloads, but a condition was created where normal access to my home directory was no longer available and other applications that depend on it panicked and reset to defaults.

This item has already been discussed on the forum at: https://forum.rclone.org/t/rclone-mount-clobbered-my-home-directory-after-a-typing-mistake/2032

**Comment by xerrni** [comment]
I`m working on it.
