### ISSUE TITLE
http branch | sources set up to respond only with the specified domain and not via direct IP will cause ioerror

### ISSUE THREAD

**Issue by pleyar** [ncw/rclone#1388]
> What is your rclone version (eg output from `rclone -V`)

rclone v1.36-DEV (http branch)
> Which OS you are using and how many bits (eg Windows 7, 64 bit)

Debian, 64 bit
> Which cloud storage system are you using? (eg Google Drive)

HTTP source - specimen: http://bookdl.online/
to
Google Drive
> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

rclone copy http1: Google:http/bookdl.online/ --transfers 8 --no-traverse --stats 30s --ignore-existing
> A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

2017/05/04 14:28:17 Failed to create file system for "HTTP1:": couldn't connect http: Head http://bookdl.online/: dial tcp 5.160.139.139:80: i/o timeout

**Comment by ncw** [comment]
Can you post a log with `-vv --dump-headers` please?

**Comment by pleyar** [comment]
Here it is

2017/05/04 21:13:58 DEBUG : rclone: Version "v1.36-DEV" starting with parameters ["rclone" "copy" "HTTP1:" "Google2:wgets/bookdl.online"
 "--transfers" "8" "--stats" "30s" "-vv" "--dump-headers" "--ignore-existing"]
2017/05/04 21:13:58 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2017/05/04 21:13:58 DEBUG : HTTP REQUEST (req 0xc42015d300)
2017/05/04 21:13:58 DEBUG : HEAD / HTTP/1.1
Host: bookdl.online
User-Agent: rclone/v1.36-DEV
2017/05/04 21:13:58 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2017/05/04 21:14:58 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2017/05/04 21:14:58 DEBUG : HTTP RESPONSE (req 0xc42015d300)
2017/05/04 21:14:58 DEBUG : Error: dial tcp 5.160.139.139:80: i/o timeout
2017/05/04 21:14:58 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2017/05/04 21:14:58 Failed to create file system for "HTTP1:": couldn't connect http: Head http://bookdl.online/: dial tcp 5.160.139.139
:80: i/o timeout

**Comment by ncw** [comment]
That looks like an IO timeout.  Does it work from your web browser?

When I try

```
curl --head 'http://bookdl.online/' -H 'User-Agent: rclone/1.36-DEV'
```

It works fine.  How does that work for you on the system you are running rclone on?

**Comment by pleyar** [comment]
curl: (7) Failed to connect to bookdl.online port 80: Connection timed out

I run it on Google Cloud instance server, I tried it on my live server and it worked normally, looks like IP ban for me...
