### ISSUE TITLE
Google Drive personal OAuth2 API credentials

### ISSUE THREAD

**Issue by bchen88c** [ncw/rclone#139]
Hi,
In rclone 1.20 (and in compiled go builds after 1.19, as of last week) I can't seem to authorize access to my Drive account using my own client id and key; copying and pasting the link or using auto config mode both ask for permissions using the built-in credentials in rclone, rather than my own. 1.19 doesn't seem to have this problem; however, when upgrading the precompiled binary to 1.20, the Drive account that I had authorized loses its token by failing to renew (and getting a 401 error, I presume because of the API credential clash)

Thanks for the software, it's been pretty efficient at pushing hundreds of GBs to my Drive in the last week alone.

**Comment by ncw** [comment]
Yes you are correct - that is an oversight in the recent oauth changes. It's easy to fix though!

Thanks for the report and glad you like the software

Nick
