### ISSUE TITLE
OneDrive Spaces to Plus

### ISSUE THREAD

**Issue by sullo** [ncw/rclone#1393]
rclone v1.36 / Mac OSX 10.12.3 (Sierra) / OneDrive

`rclone copy itunes --exclude-from excludes.txt  onedrive:/musictest --delete-excluded`

When I try clone to OneDrive, it is creating files/dirs with a + instead of a space, but it is also creating the directories without the space. 
Bit from the log:

> 2017/05/06 00:27:06 INFO  : 808 State/808 Utd. State 90/04 Kinky National.mp3: Copied (new)
> 2017/05/06 00:27:09 INFO  : 808 State/808 Utd. State 90/01 Pacific 202.mp3: Copied (new)
> 2017/05/06 00:27:14 INFO  : 808 State/808 Utd. State 90/03 Ancodia.mp3: Copied (new)
> 2017/05/06 00:27:21 INFO  : 808 State/808 Utd. State 90/02 Boneyween.mp3: Copied (new)
> 2017/05/06 00:27:34 INFO  : 808 State/808 Utd. State 90/06 Cubik.mp3: Copied (new)

Screen shots attempt to show what I'm talking about:
![1](https://cloud.githubusercontent.com/assets/1474884/25769848/77318092-31f2-11e7-887e-314bd480b81f.png)
![2](https://cloud.githubusercontent.com/assets/1474884/25769850/7936c352-31f2-11e7-8698-3d4ab48af281.png)
![3](https://cloud.githubusercontent.com/assets/1474884/25769852/7a7c022c-31f2-11e7-9ecf-0c452c72aa83.png)

I've read through docs and forum, and searched github, but I don't see this particular issue--sorry if there is an easy answer or this is a dupe.

Thank you!

**Comment by ncw** [comment]
Can you try the latest beta please - this is likely fixed already.

Thanks

**Comment by sullo** [comment]
Indeed--beta works great. Thank you, and thanks for your work on this program!
