### ISSUE TITLE
make fails on git source

### ISSUE THREAD

**Issue by ole-tange** [ncw/rclone#1396]
Builing from git source fails:

    $ git clone https://github.com/ncw/rclone.git
    $ cd rclone
    $ make
    touch fs/version.go
    go install -v --ldflags "-s -X github.com/ncw/rclone/fs.Version=v1.36-47-gd86ea86"
    rclone.go:9:2: cannot find package "github.com/ncw/rclone/cmd" in any of:
        /usr/lib/go-1.6/src/github.com/ncw/rclone/cmd (from $GOROOT)
        ($GOPATH not set)
    rclone.go:10:2: cannot find package "github.com/ncw/rclone/cmd/all" in any of:
        /usr/lib/go-1.6/src/github.com/ncw/rclone/cmd/all (from $GOROOT)
        ($GOPATH not set)
    rclone.go:11:2: cannot find package "github.com/ncw/rclone/fs/all" in any of:
        /usr/lib/go-1.6/src/github.com/ncw/rclone/fs/all (from $GOROOT)
        ($GOPATH not set)
    Makefile:15: recipe for target 'rclone' failed
    make: *** [rclone] Error 

I had expected either the system would build or it would tell me how to install the missing packages. This information could also be in the file INSTALL.

May I suggest you try building on a newly installed distribution? This will make it clear which packages, software and environment settings you depend on for building. Then document this in INSTALL or make the makefile more intelligent.

This is similar to #1395.

**Comment by sjurtf** [comment]
Yo need to setup your $GOPATH in order to build from source.
See https://golang.org/doc/code.html#Workspaces for more details.

**Comment by ole-tange** [comment]
In the binary package I found README.txt (It should also be in the source package and in git):

    $ go get -u -v github.com/ncw/rclone
    github.com/ncw/rclone (download)
    package fmt: unrecognized import path "fmt" (import path does not begin with hostname)
    package bufio: unrecognized import path "bufio" (import path does not begin with hostname)
    [... many more ...]

**Comment by ole-tange** [comment]
@sjurtf If setting $GOPATH is needed it should say so in the installation instructions. Non-go-developers should be able to compile from source, just like non-C-programmers can compile most C programs if they follow the instructions.

I have now tried:

    $ GOPATH=$HOME/gopath
    $ export GOPATH
    $ go get -u -v github.com/ncw/rclone
    github.com/ncw/rclone (download)
    package fmt: unrecognized import path "fmt" (import path does not begin with hostname)
    package bufio: unrecognized import path "bufio" (import path does not begin with hostname)
    package bytes: unrecognized import path "bytes" (import path does not begin with hostname)

**Comment by ncw** [comment]
You need to set your [GOPATH](https://golang.org/doc/code.html#GOPATH) - all go packages need that.

I'd suggest

```
mkdir ~/go
export GOPATH=~/go
go get -u -v github.com/ncw/rclone
```

Like it says in the [installing from source](https://rclone.org/install/#install-from-source) section in the docs.

**Comment by ncw** [comment]
The error

> package fmt: unrecognized import path "fmt" (import path does not begin with hostname)

Indicated you've set GOROOT I think.  Do `unset GOROOT` and all should be fine hopefully.

**Comment by ole-tange** [comment]
That solved it.

May I suggest the above either goes into github.com/ncw/rclone/INSTALL.txt or that the Makefile does that?

**Comment by anhydro** [comment]
Well, it does say in the documentation how to do it.

https://rclone.org/install/#install-from-source

**Comment by ole-tange** [comment]
At the very least split MANUAL.txt into:

INSTALL (with all instructions for installation)
Changelog (with the changelog)
LICENSE (with the license)
FileFormat (with the file format description)

Also consider formatting `rsync.1` to look like a normal man page.

**Comment by MurzNN** [comment]
I have the same problem with compiling from sources, when I try to run `go build` - I got the errors:
$ go build
rclone.go:7:2: cannot find package "github.com/ncw/rclone/backend/all" in any of:
```
        /usr/lib/go-1.10/src/github.com/ncw/rclone/backend/all (from $GOROOT)
        /home/murz/go/src/github.com/ncw/rclone/backend/all (from $GOPATH)
rclone.go:8:2: cannot find package "github.com/ncw/rclone/cmd" in any of:
        /usr/lib/go-1.10/src/github.com/ncw/rclone/cmd (from $GOROOT)
        /home/murz/go/src/github.com/ncw/rclone/cmd (from $GOPATH)
rclone.go:9:2: cannot find package "github.com/ncw/rclone/cmd/all" in any of:
        /usr/lib/go-1.10/src/github.com/ncw/rclone/cmd/all (from $GOROOT)
        /home/murz/go/src/github.com/ncw/rclone/cmd/all (from $GOPATH)
```
If I change `$GOPATH` to my custom folder location (`/home/murz/rclone-from-git`) - `go` continue lookup packages into `/home/murz/rclone-from-git/src/github.com/ncw/rclone/backend/all` subfolder instead of `/home/murz/rclone-from-git/backend/all`.

How can I fix this problem?

**Comment by Cnly** [comment]
This issue seems very obsolete already. rclone has switched to go mod and you'll need **go 1.11 or above** to build it. Also, you don't need to touch `$GOPATH` any more.

**Comment by gregsadetsky** [comment]
Small note that the Install documentation [states](https://github.com/ncw/rclone/blob/master/docs/content/install.md#install-from-source) that "Make sure you have at least Go 1.7 installed". I installed go using `apt-get install golang-go` which installed version 1.10.4.

I saw the same errors as MurzNN ("cannot find package" 3 times). Running `go get -u -v github.com/ncw/rclone` worked for me.

Should the documentation state that you need go 1.11?

(Sorry, I have no knowledge about go -- just my personal experience above trying to compile from source) :-) Cheers

**Comment by ncw** [comment]
> Small note that the Install documentation [states](https://github.com/ncw/rclone/blob/master/docs/content/install.md#install-from-source) that "Make sure you have at least Go 1.7 installed". I installed go using `apt-get install golang-go` which installed version 1.10.4 (so I thought I was ok).
> 
> I saw the same errors as MurzNN ("cannot find package" 3 times). Running `go get -u -v github.com/ncw/rclone` worked for me.
> 
> Should the documentation state that you need Go 1.11?
> 
> (Sorry, I have no knowledge about Go -- just my personal experience above trying to compile from source) :-) Cheers

Go 1.10 is a supported target for rclone (see the travis builds: https://travis-ci.org/ncw/rclone) so it should work, however you will need to unpack rclone in the GOPATH.  The easiest way is to unpack rclone at `~/go/src/github.com/ncw/rclone` as the default GOPATH is `~/go`.

One of the aims of `go mod` was to remove this friction setting GOPATH.
