### ISSUE TITLE
--bwlimit Not Honored

### ISSUE THREAD

**Issue by Flash619** [ncw/rclone#1398]
When running RClone with the following command:

> rclone sync /my/dir my-remote: --bwlimit .3M --transfers 32 --copy-links

You can see in my screenshot here (notice that I put .3 above and not 3, /my/dir has one 1.6GB file in it.) 

![2017-05-06_2300](https://cloud.githubusercontent.com/assets/1608113/25782438/bcb9888e-3310-11e7-8d9b-72cb8ba8152d.png)

That the bandwidth usage is far exceeding the limit I had placed in the command for rclone. 

I am using FreeBSD 11.0 and RClone 1.36 pushing data to a Backblaze B2 remote with crypt. If I set bwlimit to 11k, the bandwidth usage is not visible on a graph, however 300k still is still max at 6Mbp/s (which kills my entire network).

**Comment by ncw** [comment]
Note that rclone measures its bandwidth limits in kByte/s and MByte/s not not bit/s

Using `--bwlimit 0.3M` gives you `Starting bandwidth limiter at 307.199kBytes/s`

Which should be approx 2.5 Mbit/s.  Not sure why you are seeing nearly 3 times that.

What happens if you try using `--bwlimit 37k` which should get you around 300kBit/s?

**Comment by Flash619** [comment]
Setting --bwlimit to 37k completely kills rclone's upload speed. After about twenty minutes my B2 bucket shows a 0byte file (start of large file) which was created when rclone started. I have yet to see upload speeds go beyond 100KB/s, usually they sit around 10KB/s.

![2017-05-07_1615](https://cloud.githubusercontent.com/assets/1608113/25785202/74b73b32-3340-11e7-8281-7111c0cd4999.png)

**Comment by Flash619** [comment]
So I've confirmed that --bwlimit 150k and below causes almost nothing to transfer at all, and --bwlimit 200k or greater causes it to use 796KB/s (6 megabits).

**Comment by ncw** [comment]
Thanks for investigating further.

The sharp cutoff makes me think this might be to do with the timer or sleep resolution of FreeBSD.

Which processor are you running?

I can send you some binaries to try.

**Comment by Flash619** [comment]
The server is running an Intel i7 Xeon lga1155 CPU.

**Comment by ncw** [comment]
I presume you are running 64 bit - if not I'll have to remake the binaries...

Can you post the results of what happens when you run this binary please?

https://www.craig-wood.com/nick/pub/timer-test

It should print something like this

```
time.Sleep(1s) actually slept for 1.000089761s
time.Sleep(500ms) actually slept for 500.201545ms
time.Sleep(250ms) actually slept for 250.153946ms
time.Sleep(125ms) actually slept for 125.16933ms
time.Sleep(62.5ms) actually slept for 62.704354ms
time.Sleep(31.25ms) actually slept for 31.35135ms
time.Sleep(15.625ms) actually slept for 15.832816ms
time.Sleep(7.8125ms) actually slept for 7.963973ms
```

And if you try running this version of rclone with `-vv`  to do your copies to b2 it will print lots of messages like this

https://www.craig-wood.com/nick/pub/rclone

2017/05/09 17:20:55 DEBUG : bwlimit sleep 0s
2017/05/09 17:20:55 DEBUG : bwlimit sleep 0s
2017/05/09 17:20:55 DEBUG : bwlimit sleep 100ms
2017/05/09 17:20:55 DEBUG : bwlimit sleep 100ms

I'd be interested in a sample of what those look like.

Can you also try copying to a different provider to see if you get the same problem?  (Eg sftp/google drive)

Thanks

**Comment by Flash619** [comment]
```
$ ./timer-test
time.Sleep(1s) actually slept for 1.046278595s
time.Sleep(500ms) actually slept for 524.094102ms
time.Sleep(250ms) actually slept for 266.564617ms
time.Sleep(125ms) actually slept for 133.186994ms
time.Sleep(62.5ms) actually slept for 67.088254ms
time.Sleep(31.25ms) actually slept for 35.048683ms
time.Sleep(15.625ms) actually slept for 18.007113ms
time.Sleep(7.8125ms) actually slept for 9.468951ms
time.Sleep(3.90625ms) actually slept for 4.731283ms
time.Sleep(1.953125ms) actually slept for 2.862512ms
time.Sleep(976.562µs) actually slept for 1.925895ms
time.Sleep(488.281µs) actually slept for 1.988602ms
time.Sleep(244.14µs) actually slept for 1.989031ms
time.Sleep(122.07µs) actually slept for 1.988843ms
time.Sleep(61.035µs) actually slept for 1.986532ms
time.Sleep(30.517µs) actually slept for 1.99215ms
time.Sleep(15.258µs) actually slept for 1.988729ms
time.Sleep(7.629µs) actually slept for 1.989285ms
time.Sleep(3.814µs) actually slept for 1.989527ms
time.Sleep(1.907µs) actually slept for 919.469µs
time.Sleep(953ns) actually slept for 995.658µs
time.Sleep(476ns) actually slept for 3.11µs
time.Sleep(238ns) actually slept for 2.744µs
time.Sleep(119ns) actually slept for 2.696µs
time.Sleep(59ns) actually slept for 2.519µs
time.Sleep(29ns) actually slept for 2.469µs
time.Sleep(14ns) actually slept for 2.148µs
time.Sleep(7ns) actually slept for 1.936µs
time.Sleep(3ns) actually slept for 2.105µs
time.Sleep(1ns) actually slept for 2.021µs
```

I'll test the other script shortly.

**Comment by Flash619** [comment]
After a few seconds in, this is what I'm seeing with `--bwlimit .3M`

```
2017/05/09 12:40:41 DEBUG : bwlimit sleep 100ms
2017/05/09 12:40:41 DEBUG : bwlimit sleep 0s
2017/05/09 12:40:41 DEBUG : bwlimit sleep 0s
2017/05/09 12:40:41 DEBUG : bwlimit sleep 0s
2017/05/09 12:40:41 DEBUG : bwlimit sleep 0s
2017/05/09 12:40:41 DEBUG : bwlimit sleep 0s
2017/05/09 12:40:41 DEBUG : bwlimit sleep 0s
2017/05/09 12:40:41 DEBUG : bwlimit sleep 0s
2017/05/09 12:40:42 DEBUG : bwlimit sleep 100ms
2017/05/09 12:40:42 DEBUG : bwlimit sleep 0s
2017/05/09 12:40:42 DEBUG : bwlimit sleep 0s
2017/05/09 12:40:42 DEBUG : bwlimit sleep 0s
2017/05/09 12:40:42 DEBUG : bwlimit sleep 0s
2017/05/09 12:40:42 DEBUG : bwlimit sleep 0s
2017/05/09 12:40:42 DEBUG : bwlimit sleep 0s
2017/05/09 12:40:42 DEBUG : bwlimit sleep 0s
2017/05/09 12:40:42 DEBUG : bwlimit sleep 100ms
2017/05/09 12:40:42 DEBUG : bwlimit sleep 0s
2017/05/09 12:40:42 DEBUG : bwlimit sleep 0s
2017/05/09 12:40:42 DEBUG : bwlimit sleep 0s
2017/05/09 12:40:42 DEBUG : bwlimit sleep 0s
2017/05/09 12:40:42 DEBUG : bwlimit sleep 0s
2017/05/09 12:40:42 DEBUG : bwlimit sleep 0s
2017/05/09 12:40:42 DEBUG : bwlimit sleep 100ms

```

**Comment by ncw** [comment]
No that all looks normal which is good.

I tried it on a FreeBSD VM and it worked fine with using --transfers 32, --bwlimit 0.3M to b2.

I compared the rates printed by rclone (in Bytes/s) to the speeds shown in `iftop` (in bits/s - divide by 8 to get bytes/s) and they matched quite closely for `--bwlimit 0.3M` and `--bwlimit 0.1M`.

Can you send me a log of  the file transferring with `-vv --stats 10s` please.

Can you also check the bandwidth with `iftop` so we can both be using the same tools?

Thanks

**Comment by Flash619** [comment]
I'm really confused saying this, but `--bwlimit` seems to work flawlessly now for no apparent reason. I didn't update any drivers, and only updated other unrelated packages, so I'm not sure what caused this in the first place.

**Comment by ncw** [comment]
Are you still trying it on the same large >100MB file?

**Comment by Flash619** [comment]
Yes, actually its several files. Its a total size of 89GB. The server was rebooted however, which may have accounted for an increase in stability. But at this point Rclone seems to be maintaining accurate bandwidth allocation.

**Comment by ncw** [comment]
That is good to hear!  I'll close this then, but please re-open if necessary.
