### ISSUE TITLE
Question: Is there an option to constantly backup/copy files to dest folder, keeping all the files in dest folder no matter what happens in source folder?

### ISSUE THREAD

**Issue by PrinceShaji** [ncw/rclone#1401]
Hi there,

I'm trying to figure out a way to constantly copy/backup video files from my raspberry pi to google drive (the data is recorded at random). I am currently using rclone copy along with a script o delete old files, but most of the time the device either run out of memory or files fail to be copied (slow internet, so files get deleted before it could be uploaded and also the pi will be turned off during weekends). It is a lecture recording device. I could throw in an hard disk, but I'm told to make a low profile device. lol. Also, rclonecopy should be run at all times so that more files will get uploaded when the bandwidth is high.

The ideal solution for me will be rclone constantly monitoring the source folder for new files, copying them to dest folder and then deleting the original file from source folder. That way, rclone start to copy files when the pi is turned on, and frees up space instantaneously. 

**EDIT: Just went through the documentation and found rclone moveto.** 

Can we make **moveto** constantly monitor the folder for new files so that it can be set to run on boot?

Thanks.

**Comment by qnorsten** [comment]
I think you could accomplish this with a simple cronjob. Just run it on boot and once per minute or so. 
Include a check in the script to see if it is already running, so you only have one script running at a time.

**Comment by ncw** [comment]
A cronjob is the only way to achieve this at the moment.

Getting rclone to loop is part of #1119 - please add your support to that ticket if you'd like to see this built in to rclone.  Or even better send a PR :-)

Thanks
