### ISSUE TITLE
How to know folder size? (Google Drive)

### ISSUE THREAD

**Issue by bit2qubit** [ncw/rclone#1402]
https://rclone.org/drive/
https://rclone.org/commands/rclone_size/

I couldn`t found this feature in any programs...

**Comment by ajkis** [comment]
what do you mean ?

> plex@flix ~ $ rclone lsd gdrivecrypt:
>           -1 2017-02-22 05:00:10        -1 tmp
>           -1 2017-02-02 07:16:19        -1 movies
>           -1 2017-01-29 13:57:40        -1 series
>           -1 2017-01-29 13:56:44        -1 readme
>           -1 2017-01-29 13:56:39        -1 backup
> plex@flix ~ $ rclone size gdrivecrypt:/backup
> Total objects: 1104
> Total size: 1069.608 GBytes (1148482883237 Bytes)

**Comment by breunigs** [comment]
Additionally there now is `rclone ncdu` which shows folder sizes nicely: https://rclone.org/commands/rclone_ncdu/

I will close this ticket now, but please reopen it if none of the mentioned features site your needs!
