### ISSUE TITLE
compiling go errors

### ISSUE THREAD

**Issue by calisro** [ncw/rclone#1404]
Im trying to compile go for the first time.  I'm new to go.  I'm getting this message and I am a bit lost on how to proceed.  I checked my ubuntu certificate store and it seems to be correct.  I realize this probably isn't a rclone issue but was just looknig for some help trying to compile it.  I tried a few go versions with the same errors.  I'm currently on 1.7.5

HS -> lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty

HS -> go version
go version xgcc (Ubuntu 4.9.3-0ubuntu4) 4.9.3 linux/amd64

HS -> go get -u -v github.com/ncw/rclone
github.com/ncw/rclone (download)
Fetching https://bazil.org/fuse?go-get=1
https fetch failed.
Fetching http://bazil.org/fuse?go-get=1
import "bazil.org/fuse": http/https fetch: Get https://bazil.org/fuse?go-get=1: x509: certificate signed by unknown authority (possibly because of "x509: cannot verify signature: algorithm unimplemented" while trying to verify candidate authority certificate "COMODO ECC Certification Authority")
package github.com/ncw/rclone
	imports bazil.org/fuse: unrecognized import path "bazil.org/fuse"
Fetching https://bazil.org/fuse/fs?go-get=1
https fetch failed.
Fetching http://bazil.org/fuse/fs?go-get=1
import "bazil.org/fuse/fs": http/https fetch: Get https://bazil.org/fuse/fs?go-get=1: x509: certificate signed by unknown authority (possibly because of "x509: cannot verify signature: algorithm unimplemented" while trying to verify candidate authority certificate "COMODO ECC Certification Authority")
package github.com/ncw/rclone
	imports bazil.org/fuse/fs: unrecognized import path "bazil.org/fuse/fs"
github.com/Unknwon/goconfig (download)
github.com/VividCortex/ewma (download)
github.com/aws/aws-sdk-go (download)
github.com/go-ini/ini (download)
github.com/jmespath/go-jmespath (download)
github.com/ncw/go-acd (download)
github.com/google/go-querystring (download)

**Comment by ncw** [comment]
It looks like you are using gccgo

```
HS -> go version
go version xgcc (Ubuntu 4.9.3-0ubuntu4) 4.9.3 linux/amd64

```
Your go version should look like this if you are using normal go (that is what I'd recommend)

```
$ go version
go version go1.8.1 linux/amd64
```

So maybe there is another go binary on your path?  See [SO answer](http://stackoverflow.com/questions/29514456/go-is-printing-xgcc-version-but-not-go-installed-version)

That should hopefully fix it.

**Comment by calisro** [comment]
ah. that was it!  Such simple things. When I removed the ubuntu packaged go (version 1.35)  and installed a new version it left that.  I just assumed it was gone.  Thanks.  I needed that kick in the right direction.
