### ISSUE TITLE
fs/TestLsLong test failure on Windows

### ISSUE THREAD

**Issue by klauspost** [ncw/rclone#141]
I don't know if this is Windows specific, but I will investigate further:
```
--- FAIL: TestLsLong (0.00s)
        operations_test.go:495: empty space: Modification time difference too big |-59m59.999999911s| > 100ns (2011-12-25 13:59:59.1234567 +0000 UTC vs 2011-12-25 13:59:59.123456789 +0100 CET) (precision 100ns)
        operations_test.go:495: potato2: Modification time difference too big |-59m59.999999901s| > 100ns (2001-02-03 05:05:06.4999999 +0000 UTC vs 2001-02-03 05:05:06.499999999 +0100 CET) (precision 100ns)
FAIL
FAIL    github.com/ncw/rclone/fs        0.272s
```

**Comment by ncw** [comment]
Looks like a timezone thing. If I remember rightly windows stores local time on files, whereas unix based systems store UTC so it might be something to do with that.

**Comment by klauspost** [comment]
The test passes if I change the time to UTC:

```Go
// List the Fs to stdout
//
// Shows size, mod time and path
//
// Lists in parallel which may get them out of order
func ListLong(f Fs, w io.Writer) error {
	return ListFn(f, func(o Object) {
		Stats.Checking(o)
		modTime := o.ModTime().UTC()
		Stats.DoneChecking(o)
		syncFprintf(w, "%9d %s %s\n", o.Size(), modTime.Format("2006-01-02 15:04:05.000000000"), o.Remote())
	})
}
```
But is that really what we want? Don't we want it to be displayed in local time?

**Comment by ncw** [comment]
The times in the error message are suspicious

  * 2011-12-25 13:59:59.1234567 +0000 UTC
  * 2011-12-25 13:59:59.123456789 +0100 CET

The first looks like it was read off a windows file system as it has 100ns less precision.  However it is the same time (but not timezone) as than is expected.

So if you write a simple prog to read an os.FileInfo from a file and run ModTime on it - do you get the correct time & timezone on windows? Or just the correct time?

I contributed the code to read higher precision timestamps on windows in the go standard library, so quite possibly I got it wrong!

Another thing to think about - why are the test times showing as CET - I thought they were defined with the Z timezone which should be UTC...

Probably the right approach is to make sure everything is UTC internally (which probably just requires a .UTC()) but then change to localtime for display purposes (in list only).

Grrrr, timezones!

**Comment by klauspost** [comment]
>Another thing to think about - why are the test times showing as CET

There is a .Local() in [the test](https://github.com/ncw/rclone/blob/master/fs/operations_test.go#L504), which explains why test times are local (CET).

However, there isn't any conversion in [ListLong](https://github.com/ncw/rclone/blob/master/fs/operations.go#L640), so the time is written in the same timezone as it receives it from [local.ModTime](https://github.com/ncw/rclone/blob/master/local/local.go#L479).

The test however, uses [Time.Parse()](https://github.com/ncw/rclone/blob/master/fs/operations_test.go#L489) with no timezone info, so it assumes UTC.

It seems like there are two bugs:
1. ListLong should explicitly convert to .Local()
2. The test should be modified to parse as local TZ, not UTC.

**Comment by ncw** [comment]
> The test however, uses Time.Parse() with no timezone info, so it assumes UTC.

It uses time.RFC3339Nano format with the `Z` suffix which means UTC, so yes they should be UTC.

> 1. ListLong should explicitly convert to .Local()

Agreed.

> 2. The test should be modified to parse as local TZ, not UTC.

1 => 2, yes

I'm not convinced that there isn't an underlying problem with file timestamps on windows though.

**Comment by ncw** [comment]
I've fixed this and tested it on windows, will merge shortly!

**Comment by klauspost** [comment]
Nice - thanks!
