### ISSUE TITLE
Getting a lot of TLS handshake timeouts on ACD

### ISSUE THREAD

**Issue by dereulenspiegel** [ncw/rclone#1415]
> What is your rclone version (eg output from `rclone -V`)
v1.36
> Which OS you are using and how many bits (eg Windows 7, 64 bit)
Linux (Ubuntu) and MacOS X
> Which cloud storage system are you using? (eg Google Drive)
Amazon Cloud Drive
> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone mount
> A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
```
2017/05/17 22:19:28 DEBUG : pacer: Rate limited, sleeping for 1m57.331776148s (8 consecutive low level retries)
2017/05/17 22:19:28 DEBUG : pacer: low level retry 8/10 (error Get https://cdws.eu-west-1.amazonaws.com/drive/v1/nodes?filters=parents%3A%22skO1iDKZRhWRV-4BjR8yMw%22+AND+name%3A%22MRhqSwzW5OYp48molnrG4Mgx%22: net/http: TLS handshake timeout)
```
I noticed a really really bad performance of a folder I mounted with rclone from ACD. A look into the log revealed that a lot of requests seem to fail with TLS handshake timeouts. Normally rclone runs on a VPS, mounting a folder on ACD which is then mounted through encfs. 
I recreated the same setup on my local machine (MacOS) on a different network and I get the same results.
I am not sure if this is a bug, a problem with my account (is usage of rclone mount detetactable and a violiation of their TOS) or is Amazon having problems with Cloud Drive offering?

**Comment by left1000** [comment]
I am getting nothing but http error 429 rate limit exceeded tonight. looks like ACD isn't giving rclone enough requests/second allowance.
shame we all have to share the same api ID and ACD can throttle us all at once like this.

**Comment by MrHillard** [comment]
I get nothing but 429 on mounts, copies, syncs at the moment.

**Comment by dereulenspiegel** [comment]
now I also get 429. But before it were always timeouts. Were the timeouts a side phenomen of the rate limiting? I just want to make sure that we don't mix up problems here. A response code of 429 is rate limiting (pretty clearly), but the TLS handshake timeouts could be either a bug, a problem on Amazons side, or a side effect of the rate limiting. Would be nice to rule out a bug in rclone (like the these guys had in their firebase client https://medium.com/@contact_16315/firebase-costs-increased-by-7-000-81dc0a27271d).

**Comment by unnfav** [comment]
rclone's credentials might have been revoked by Amazon.  See this [post](https://github.com/ncw/rclone/issues/1409#issuecomment-302316487).

**Comment by kiding** [comment]
> 2017/05/18 16:40:40 Failed to create file system for "remote:[redacted]": failed to get endpoints: HTTP code 429: "429 Too Many Requests": response body: "{\"message\":\"Rate exceeded\"}"

As mentioned in #4209, rclone returns 429 error as of now. 😢

**Comment by ncw** [comment]
All 429 errors for me too.

I'll email my contacts at amazon and see what they have to say.

**Comment by jdrydn** [comment]
It's annoying because they've disabled new signups to the ACD API, otherwise the logical step for us would be to create our own API keys!

**Comment by ncw** [comment]
> It's annoying because they've disabled new signups to the ACD API, otherwise the logical step for us would be to create our own API keys!

Yes you used to be able to create your own keys and and use them on your own account before having the app whitelisted (which is the hard part).

**Comment by jdrydn** [comment]
@ncw yeah I went to the trouble of making a new security profile and trying it with `acd_cli` and instantly got hit with permissions errors! 😩

**Comment by left1000** [comment]
not sure if anyone has reported this yet, but I no longer get 429 errors. I get this instead:

Response: {"error_description":"Client authentication failed","error":"invalid_client"}

so rclone is blocked on purpose now in addition to on accident?

**Comment by barnabyc** [comment]
@left1000 - I'm seeing the same thing. Comes back immediately with exact same message.

**Comment by calisro** [comment]
Yes. If look in the manage apps section in cloud drive, rclone is no longer listed just like acdcli was removed.  This looks like permanent or at least long term ban now....

**Comment by SamuelTilly** [comment]
Got this response from amazon support "I've checked our Amazon Drive data sources and see that Rclone app access has been revoked and it no longer supports Amazon Drive access. I'm sorry for this disappointment."

**Comment by ncw** [comment]
I'm going to close this issue now - for the resolution see https://forum.rclone.org/t/rclone-has-been-banned-from-amazon-drive/
