### ISSUE TITLE
400 Bad Request Unknown client_id 

### ISSUE THREAD

**Issue by dhs227** [ncw/rclone#1420]
with the '-vv' flag, the following output is captured:
"Storage> 1
Amazon Application Client Id - leave blank normally.
client_id> 
Amazon Application Client Secret - leave blank normally.
client_secret> 
Remote config
Use auto config?
 * Say Y if not sure
 * Say N if you are working on a remote or headless machine
y) Yes
n) No
y/n> y
2017/05/19 00:43:47 DEBUG : Starting auth server on 127.0.0.1:53682
If your browser doesn't open automatically go to the following link: http://127.0.0.1:53682/auth
Log in and authorize rclone for access"

The following is captured thereafter from browser window:
We're sorry!
An error occurred when we tried to process your request. Rest assured, we're already working on the problem and expect to resolve it shortly.

Hide Details
Error Summary
400 Bad Request
Unknown client_id
Request Details
client_id=amzn1.application-oa2-client.6bf18d2d1f5b485c94c8988bb03ad0e7
redirect_uri=http%3A%2F%2F127.0.0.1%3A53682%2F
response_type=code
scope=clouddrive%3Aread_all+clouddrive%3Awrite
state=d03097e18a138894b25c1a27e2d0edf0

**Comment by unnfav** [comment]
Please refer to issue [1409](https://github.com/ncw/rclone/issues/1409)

rclone's tokens might have been banned temporarily.  Nothing concrete yet though.

**Comment by ncw** [comment]
I put a [post in the forum](https://forum.rclone.org/t/rclone-has-been-banned-from-amazon-drive/2314) which I'll update as and when I hear more info.

**Comment by jyanes83** [comment]
I have noticed the same issue.   I hope rclone is not band.

**Comment by docbill** [comment]
Same issue here.

**Comment by yonjah** [comment]
@ncw sorry for posting here but I don't have a forum user.
You updated that amazon have banned since the secret are kept in code
Does that mean the fail to implement the oAuth2 protocol regarding native app shared secret ?
https://tools.ietf.org/html/draft-ietf-oauth-native-apps-07#section-8.9a

We had this discussion regarding g drive in #309 before .
Having an external server might cause more issues than it actually solves and the only situation where it might make sense is if Amazon has security flaws in the way the implement oAuth2.0

**Comment by georgeAustralia** [comment]
Hi there, thanks for the wonderful tool.  I encountered bad 400 error also.

THIS FROM MY POWERSHELL:

PS C:\rclone> c:\rclone.exe copy --retries 999 --low-level-retries 10 c:\source remote:target
2017/05/24 12:44:49 Failed to create file system for "remote:target": failed to get endpoints: Get https://drive.amazonaws.com/drive/v1/account/endpoint: oauth2: cannot fetch token: 401 Unauthorized
Response: {"error_description":"Client authentication failed","error":"invalid_client"}
PS C:\rclone>

THIS IS FROM CHROME:

We're sorry!
An error occurred when we tried to process your request. Rest assured, we're already working on the problem and expect to resolve it shortly.

Hide Details
Error Summary
400 Bad Request
Unknown client_id
Request Details
client_id=amzn1.application-oa2-client.6bf18d2d1f5b485c94c8988bb03ad0e7
redirect_uri=http%3A%2F%2F127.0.0.1%3A53682%2F
response_type=code
scope=clouddrive%3Aread_all+clouddrive%3Awrite
state=a4c18c7e455cf7e1c3730354d9527db3

**Comment by ncw** [comment]
@yonjah wrote
> You updated that amazon have banned since the secret are kept in code
Does that mean the fail to implement the oAuth2 protocol regarding native app shared secret ?
https://tools.ietf.org/html/draft-ietf-oauth-native-apps-07#section-8.9

I've not seen that before, but it hits the nail on the head - thanks for pointing that out.

Yes, amazon are treating the client ID/ client secret as confidential even for native apps.

> We had this discussion regarding g drive in #309 before . Having an external server might cause more issues than it actually solves and the only situation where it might make sense is if Amazon has security flaws in the way the implement oAuth2.0

I don't really want to run an auth server and personally think it is the wrong approach.  However if it gets rclone back online then I'll go with it.

I've yet to hear back from Amazon though.

**Comment by PieterBreugelmans** [comment]
As a workaround, it is also not an option for people to get them selves their own Security Profile from Amazon, and use their personal Client ID 	/ Client Secret values? I thought that this odd to work but having tried that just now (rclone authorize), even that appears to be a no-go:

Error Summary
400 Bad Request
An unknown scope was requested 
Request Details
client_id=<personal secret>
redirect_uri=http%3A%2F%2F127.0.0.1%3A53682%2F 
response_type=code 
scope=clouddrive%3Aread_all+clouddrive%3Awrite 
state=5d0c7c86489f4ee4803c89744ea69ded

**Comment by docbill** [comment]
What I don't understand, is what just keeps another client from pointing to
the same authorization server?   I can't really see how an authorization
server adds security...  If anything it reduces security, because it adds
one more layer that can be hijacked to steal login credentials.

**Comment by sbias** [comment]
hmm, acd_cli solved this issue, is there any progress with rclone?

**Comment by georgeAustralia** [comment]
How about go through the normal web approach using Python?  That way no matter how Amazon changes its protocol we can always get through.

**Comment by carlyuanliu** [comment]
I have the same problem (400 Bad Request Unknown client_id) when trying to configure a new remote for amazon drive.

Before that, I encountered the following problem 
> 2017/05/27 08:47:53 Failed to create file system for "amazon:/KQA/20170520/": failed to get endpoints: Get https://drive.amazonaws.com/drive/v1/account/endpoint: oauth2: cannot fetch token: 401 Unauthorized
> Response: {"error_description":"Client authentication failed","error":"invalid_client"}
(I am in Taiwan time GMT+8)

This is response to a similar copy command I have been using for months.

After a short search, I decided to remove the remote 'amazon' and reconfigure it again.  Then I ran into the problem above.

Looks like rclone is having a problem with Amazon.

So, I just have to wait for the rclone guys to sort it out with Amazon people and help us with a workaround?

**Comment by LoopControl** [comment]
Same issue here about unknown client_id with latest rclone download on Ubuntu

**Comment by jtHunter** [comment]
same issue on my side: 400: "unknown client_id"

**Comment by sjurtf** [comment]
@carlyuanliu, @LoopControl and @jtHunter.

Please read this forum post 
https://forum.rclone.org/t/rclone-has-been-banned-from-amazon-drive/2314

**Comment by ncw** [comment]
I'm going to close this issue now - for the resolution see https://forum.rclone.org/t/rclone-has-been-banned-from-amazon-drive/

**Comment by ilkarataev** [comment]
Had same problem with yandex disk. In the last beta version at 02/13/2020 all works fine.
links https://beta.rclone.org/

**Comment by buengese** [comment]
@ilkarataev This is entirely unrelated and the situation regarding Amazon Cloud Drive hasn't changed. This type of issue almost never translate from one backend to another and should always be discussed in a separate issue.
