### ISSUE TITLE
Sometimes b2 stalls/throttles

### ISSUE THREAD

**Issue by joeytwiddle** [ncw/rclone#1425]
Sometimes it appears when using `rclone sync` that the transfer+checking stalls.

As you can see below, for a few minutes the number of checks and the number of transfers does not increase.

<details>

```
2017/05/20 14:18:53 
Transferred:   857.928 MBytes (37.315 kBytes/s)
Errors:                 0
Checks:             67737
Transferred:         2699
Elapsed time:  6h32m22.5s

2017/05/20 14:19:53 
Transferred:   857.928 MBytes (37.221 kBytes/s)
Errors:                 0
Checks:             67737
Transferred:         2699
Elapsed time:  6h33m22.5s

2017/05/20 14:20:53 
Transferred:   857.928 MBytes (37.127 kBytes/s)
Errors:                 0
Checks:             67737
Transferred:         2699
Elapsed time:  6h34m22.5s

2017/05/20 14:21:53 
Transferred:   857.928 MBytes (37.032 kBytes/s)
Errors:                 0
Checks:             67737
Transferred:         2699
Elapsed time:  6h35m22.5s

2017/05/20 14:22:53 
Transferred:   857.928 MBytes (36.939 kBytes/s)
Errors:                 0
Checks:             67737
Transferred:         2699
Elapsed time:  6h36m22.5s

2017/05/20 14:23:53 
Transferred:   857.928 MBytes (36.847 kBytes/s)
Errors:                 0
Checks:             67737
Transferred:         2699
Elapsed time:  6h37m22.5s
```

</details>

.
Fortunately after a while (sometimes a few minutes, sometimes many), things resume. So this is not a fatal issue.

**I am guessing that b2 is throttling. If that is the case, is there anything I can do to prevent it?**

I am using rclone v 1.35 with `--checkers 8 --transfers 8 --bwlimit 700k --filter-from large-filter-file`

I don't think it is the case that rclone is simply chugging through filtered-out files during this time, because I see no disk activity in my OS monitor (gkrellm).

**Comment by ncw** [comment]
That does seem strange!

Can you get a log with `-vv` of it happening?

It might be that the directory listing thread is having lots of retries at b2 maybe.

**Comment by ncw** [comment]
This is probably related to  #1443  I think.

Because the chunks for large files are buffered in memory...

I'll check the code.

I'll still like to see those logs if possible.

**Comment by Codematic71** [comment]
I think i am seeing this issue... i have -vv set, do you still want logs ?

**Comment by ncw** [comment]
As #1443 is closed, I'm going to close this too as I think it fixes the issue
