### ISSUE TITLE
Very slow Google Drive upload

### ISSUE THREAD

**Issue by SirJMD** [ncw/rclone#1428]
When ACD worked I could usually get around 5 MB/s upload speed. With Google Drive I never seem to get above ~700 kB/s. If I started multiple transfer then I just have multiple 700 kB/s transfers. It almost seems like there's a hidden speed cap somewhere.

Am I doing something wrong, or what is going on here?

Here's a test with a single 2,27 GB file and three additional files with a combined size less than 275 kB.

**Upload:**
Transferred: 2.274 GBytes (707.319 kBytes/s)
Errors: 0
Checks: 0
Transferred: 4
Elapsed time: 56m10.9s

**Download:**
Transferred: 2.274 GBytes (13.883 MBytes/s)
Errors: 0
Checks: 0
Transferred: 4
Elapsed time: 2m47.7s

Rclone: v1.36
Rclone browser: 1.2
Running on Win 7 64 bit
Internet: 200/200 MBit/s fiber (about 18 ms to 8.8.8.8)

**Comment by SirJMD** [comment]
Did another couple of simultaneous transfers and they all end up at roughly 700 kB/s.. 

Transferred:   7.200 GBytes (707.199 kBytes/s)
Errors:                 0
Checks:                 0
Transferred:            2
Elapsed time:    2h57m56s

Transferred:   7.233 GBytes (701.817 kBytes/s)
Errors:                 0
Checks:                 0
Transferred:            2
Elapsed time:    3h0m6.7s

Transferred:   7.342 GBytes (707.889 kBytes/s)
Errors:                 0
Checks:                 0
Transferred:            2
Elapsed time:   3h1m15.8s

Transferred:   7.280 GBytes (700.320 kBytes/s)
Errors:                 0
Checks:                 0
Transferred:            2
Elapsed time:   3h1m39.8s

**Comment by scriptzteam** [comment]
No :) Probably your internet provider s(u)cks!

I do every single day 1,5TB of transfer! Speed is not going bellow 10 MBytes/s.

**Comment by Massaguana** [comment]
Here are also no Speedproblems with GSuite... Stable at 2,5 MB/s for the last 4 month

**Comment by sjurtf** [comment]
This is not related to rclone, but merely a peering issue between you and Google.

**Comment by SirJMD** [comment]
A peering problem just one way..? Seems a bit unlikely?

**Comment by sjurtf** [comment]
It looks like your provider, or their upstream provider is traffic shaping each connection to Google. Network load is not necessarily equally shared on upstream and downstream, and it is likely that congestion occurs on one of these and traffic shaping is implemented.

Anyways, this is not an issue with the rclone code, and I suggest using the forums for troubleshooting this network related issue further.

**Comment by SirJMD** [comment]
> I suggest using the forums for troubleshooting this network related issue further.

Thanks, will do.
