### ISSUE TITLE
is this the reason why rclone was banned from ACD?

### ISSUE THREAD

**Issue by amunhoz** [ncw/rclone#1429]
rclone/amazonclouddrive/amazonclouddrive.go
line 37    rcloneClientID = "amzn1.application-oa2-client.6bf18d2d1f5b485c94c8988bb03ad0e7"
line 38    rcloneEncryptedClientSecret = "ZP12wYlGw198FtmqfOxyNAGXU3fwVcQdmt--ba1d00wJnUs0LOzvVyXVDbqhbcUqnr5Vd1QejwWmiv1Ep7UJG1kUQeuBP5n9goXWd5MrAf0"

This is a private key for using amazon services.
Other opensource softwares was not banned and they dont show this information in their code.
They provide an external server to authenticate.

You can check 
https://www.npmjs.com/package/clouddrive
https://drivesink.appspot.com/

**Comment by sjlu** [comment]
Highly likely. AWS actually runs an internal program which runs queries for client ids and secrets to ensure accounts are not compromised. I'm sure this is the same program running to clean out ACD keys.

**Comment by azgul** [comment]
https://forum.rclone.org/t/rclone-has-been-banned-from-amazon-drive/2314

> Update 2017-05-20
>
> I have now heard back from Amazon. Rclone has been banned for having the encrypted secrets in the source code.
> 
> I've asked for new credentials so I can build an auth server and get rclone going again - I haven't heard back on that reply yet, but it is plausible we could get rclone running again with Amazon Drive in the not too distant future.
>
> Thank you all for your patience

yes

**Comment by toddfries** [comment]
rclone is an amazingly powerful tool.  I find I am using it in many ways via cron.  If you need a vm somewhere or other hosting resources I'd be willing to help!

**Comment by ncw** [comment]
I'm going to close this issue now - for the resolution see https://forum.rclone.org/t/rclone-has-been-banned-from-amazon-drive/
