### ISSUE TITLE
sftp: Windows sync/copy folders (recursive copy) problem

### ISSUE THREAD

**Issue by rtpm** [ncw/rclone#1432]
Using https://beta.rclone.org/ (versioned May 19th 2017)

OS: Windows 10.

Trying to copy/sync local directory to my Synology NAS via sftp using:

rclone c:\Test\attachments LocalNas-sftp:home/Test

It does copy files correctly, but it does not do the same with folders.

Getting error:

> Failed to copy: Put mkParentDir failed: mkdir dirExists failed: dirExists stat failed: failed to send packet header: EOF

Instead of creating a "attachments" directory in "Test" it creates a "Test\attachments" dir on my NAS.

There's also a new thread created at:
https://forum.rclone.org/t/rclone-on-windows-to-ssh-making-excessive-folders-with-on-the-root-dir/2378 

created by another user.

Sorry if there's already a similar issue (couldn't find any tohugh)

Thanks!

**Comment by ncw** [comment]
Could you easily try this on linux or OS X?  I suspect it isn't related to Windows.

This is probably a quirk of the sftp daemon running on your NAS.

Can you attach a log with `-vv` of your test command please?

**Comment by rtpm** [comment]
Hello @ncw, thanks for your response.

Both stable & beta windows versions do not copy folders.
Linux version works fine with both stable & beta.

Here's the log, hope you find it helpful. If you need more info / testing let me know.


> R:\rclone-beta-latest-windows-amd64\rclone-v1.36-124-ge75db0b1-windows-amd64>dir /s /b r:\rclone_test
> r:\rclone_test\test_dir
> r:\rclone_test\test_file
> r:\rclone_test\test_test_file
> r:\rclone_test\test_dir\test_file2

BETA VERSION@Windows:

> R:\rclone_bin\rclone-v1.36-124-ge75db0b1-windows-amd64>rclone sync r:\rclone_test nas-sftp:/home/rclone_test --config .rclone.config -vv
> 2017/05/24 12:16:54 DEBUG : rclone: Version "v1.36-124-ge75db0b1" starting with parameters ["rclone" "sync" "r:\\rclone_test" "nas-sftp:/home/rclone_test" "--config" ".rclone.config" "-vv"]
> 2017/05/24 12:16:55 INFO  : sftp://backup@192.168.0.240:22//home/rclone_test: Modify window is 1s
> 2017/05/24 12:16:55 INFO  : sftp://backup@192.168.0.240:22//home/rclone_test: Waiting for checks to finish
> 2017/05/24 12:16:55 INFO  : sftp://backup@192.168.0.240:22//home/rclone_test: Waiting for transfers to finish
> 2017/05/24 12:16:55 INFO  : test_file: Copied (new)
> 2017/05/24 12:16:55 INFO  : test_test_file: Copied (new)
> 2017/05/24 12:17:55 INFO  :
> Transferred:     14 Bytes (0 Bytes/s)
> Errors:                 0
> Checks:                 0
> Transferred:            2
> Elapsed time:      1m0.7s
> Transferring:
>  *                           test_dir/test_file2:  0% done, 0 Bytes/s, ETA: -

RESULT: Only 1 depth level files copied (without dirs). It hangs for 20? seconds before the "Transferred: 14 bytes..."

STABLE (1.36)@Windows:

> R:\rclone_bin\rclone-v1.36-windows-amd64>rclone sync r:\rclone_test nas-sftp:/home/rclone_test --config .rclone.config -vv
> 2017/05/24 12:18:53 DEBUG : rclone: Version "v1.36" starting with parameters ["rclone" "sync" "r:\\rclone_test" "nas-sftp:/home/rclone_test" "--config" ".rclone.config" "-vv"]
> 2017/05/24 12:18:55 INFO  : sftp://backup@192.168.0.240:22//home/rclone_test: Modify window is 1s
> 2017/05/24 12:18:55 INFO  : sftp://backup@192.168.0.240:22//home/rclone_test: Waiting for checks to finish
> 2017/05/24 12:18:55 INFO  : sftp://backup@192.168.0.240:22//home/rclone_test: Waiting for transfers to finish
> 2017/05/24 12:18:55 INFO  : test_file: Copied (new)
> 2017/05/24 12:18:55 INFO  : test_test_file: Copied (new)
> 2017/05/24 12:19:55 INFO  :
> Transferred:     14 Bytes (0 Bytes/s)
> Errors:                 0
> Checks:                 0
> Transferred:            2
> Elapsed time:      1m1.8s
> Transferring:
>  *                           test_dir/test_file2:  0% done, 0 Bytes/s, ETA: -
> 
> 2017/05/24 12:20:55 INFO  :
> Transferred:     14 Bytes (0 Bytes/s)
> Errors:                 0
> Checks:                 0
> Transferred:            2
> Elapsed time:      2m1.8s
> Transferring:
>  *                           test_dir/test_file2:  0% done, 0 Bytes/s, ETA: -

RESULT: the same as beta version.

Stable@Linux:

> [root@telefon rclone-v1.36-124-ge75db0b1β-linux-amd64]# ./rclone sync /tmp/rclone_test nas-sftp:/home/rclone_test --config .rclone.config -vv
> 2017/05/24 12:23:17 DEBUG : rclone: Version "v1.36-124-ge75db0b1β" starting with parameters ["./rclone" "sync" "/tmp/rclone_test" "nas-sftp:/home/rclone_test" "--config" ".rclone.config" "-vv"]
> 2017/05/24 12:23:18 INFO  : sftp://backup@192.168.0.240:22//home/rclone_test: Modify window is 1s
> 2017/05/24 12:23:18 INFO  : sftp://backup@192.168.0.240:22//home/rclone_test: Waiting for checks to finish
> 2017/05/24 12:23:18 INFO  : sftp://backup@192.168.0.240:22//home/rclone_test: Waiting for transfers to finish
> 2017/05/24 12:23:18 INFO  : test_file: Copied (new)
> 2017/05/24 12:23:18 INFO  : test_dir/test_file2: Copied (new)
> 2017/05/24 12:23:18 INFO  : test_test_file: Copied (new)
> 2017/05/24 12:23:18 INFO  : Waiting for deletions to finish
> 2017/05/24 12:23:18 INFO  :
> Transferred:     10 Bytes (9 Bytes/s)
> Errors:                 0
> Checks:                 0
> Transferred:            3
> Elapsed time:          1s
> 2017/05/24 12:23:18 DEBUG : Go routines at exit 13
> 2017/05/24 12:23:18 DEBUG : rclone: Version "v1.36-124-ge75db0b1β" finishing with parameters ["./rclone" "sync" "/tmp/rclone_test" "nas-sftp:/home/rclone_test" "--config" ".rclone.config" "-vv"]
> [root@telefon rclone-v1.36-124-ge75db0b1β-linux-amd64]#

Result: OK

Beta@Linux:

> [root@telefon rclone-v1.36-linux-amd64]# ./rclone sync /tmp/rclone_test nas-sftp:/home/rclone_test --config .rclone.config -vv
> 2017/05/24 12:24:41 DEBUG : rclone: Version "v1.36" starting with parameters ["./rclone" "sync" "/tmp/rclone_test" "nas-sftp:/home/rclone_test" "--config" ".rclone.config" "-vv"]
> 2017/05/24 12:24:42 INFO  : sftp://backup@192.168.0.240:22//home/rclone_test: Modify window is 1s
> 2017/05/24 12:24:42 INFO  : sftp://backup@192.168.0.240:22//home/rclone_test: Waiting for checks to finish
> 2017/05/24 12:24:42 INFO  : sftp://backup@192.168.0.240:22//home/rclone_test: Waiting for transfers to finish
> 2017/05/24 12:24:42 INFO  : test_file: Copied (new)
> 2017/05/24 12:24:42 INFO  : test_test_file: Copied (new)
> 2017/05/24 12:24:42 INFO  : test_dir/test_file2: Copied (new)
> 2017/05/24 12:24:42 INFO  : Waiting for deletions to finish
> 2017/05/24 12:24:42 INFO  :
> Transferred:     10 Bytes (12 Bytes/s)
> Errors:                 0
> Checks:                 0
> Transferred:            3
> Elapsed time:       700ms
> 2017/05/24 12:24:42 DEBUG : Go routines at exit 12
> 2017/05/24 12:24:42 DEBUG : rclone: Version "v1.36" finishing with parameters ["./rclone" "sync" "/tmp/rclone_test" "nas-sftp:/home/rclone_test" "--config" ".rclone.config" "-vv"]
> [root@telefon rclone-v1.36-linux-amd64]#
> 

Result: OK

Stable@Windows (different sftp target on linux box instead of synology NAS):

> R:\rclone_bin\rclone-v1.36-windows-amd64>rclone.exe sync r:\rclone_test telefon-sftp:/tmp/rclone_test --config .rclone.config -vv
> 2017/05/24 12:33:39 DEBUG : rclone: Version "v1.36" starting with parameters ["rclone.exe" "sync" "r:\\rclone_test" "telefon-sftp:/tmp/rclone_test" "--config" ".rclone.config" "-vv"]
> 2017/05/24 12:33:39 INFO  : sftp://root@192.168.0.15:22//tmp/rclone_test: Modify window is 1s
> 2017/05/24 12:33:39 INFO  : sftp://root@192.168.0.15:22//tmp/rclone_test: Waiting for checks to finish
> 2017/05/24 12:33:39 INFO  : sftp://root@192.168.0.15:22//tmp/rclone_test: Waiting for transfers to finish
> 2017/05/24 12:33:39 INFO  : test_file: Copied (new)
> 2017/05/24 12:33:39 INFO  : test_test_file: Copied (new)
> 2017/05/24 12:34:39 INFO  :
> Transferred:     14 Bytes (0 Bytes/s)
> Errors:                 0
> Checks:                 0
> Transferred:            2
> Elapsed time:      1m0.1s
> Transferring:
>  *                           test_dir/test_file2:  0% done, 0 Bytes/s, ETA: -

RESULT: no directories copied

**Comment by ncw** [comment]
Ok there is something very obviously wrong with the Windows support!  Try this and see if it fixes it.  If not I'll dig further.

https://beta.rclone.org/v1.36-126-ga243ea63/ (uploaded in 15-30 mins)

**Comment by ncw** [comment]
That is uploaded now - had to give the builder a kick!

**Comment by rtpm** [comment]
Seems like it's ok now.

Thank You!

> R:\rclone_bin\rclone-v1.36-126-ga243ea63-windows-amd64>copy ..\rclone-v1.36-124-ge75db0b1-windows-amd64\.rclone.config .
>         1 file(s) copied.
> 
> R:\rclone_bin\rclone-v1.36-126-ga243ea63-windows-amd64>rclone sync r:\rclone_test nas-sftp:/home/rclone_test --config .rclone.config -vv
> 2017/05/24 21:51:39 DEBUG : rclone: Version "v1.36-126-ga243ea63" starting with parameters ["rclone" "sync" "r:\\rclone_test" "nas-sftp:/home/rclone_test" "--config" ".rclone.config" "-vv"]
> 2017/05/24 21:51:40 INFO  : sftp://backup@192.168.0.240:22//home/rclone_test: Modify window is 1s
> 2017/05/24 21:51:40 INFO  : sftp://backup@192.168.0.240:22//home/rclone_test: Waiting for checks to finish
> 2017/05/24 21:51:40 INFO  : sftp://backup@192.168.0.240:22//home/rclone_test: Waiting for transfers to finish
> 2017/05/24 21:51:41 INFO  : test_test_file: Copied (new)
> 2017/05/24 21:51:41 INFO  : test_file: Copied (new)
> 2017/05/24 21:51:41 INFO  : test_dir/test_file2: Copied (new)
> 2017/05/24 21:51:41 INFO  : Waiting for deletions to finish
> 2017/05/24 21:51:41 INFO  :
> Transferred:     21 Bytes (15 Bytes/s)
> Errors:                 0
> Checks:                 0
> Transferred:            3
> Elapsed time:        1.3s
> 2017/05/24 21:51:41 DEBUG : Go routines at exit 13
> 2017/05/24 21:51:41 DEBUG : rclone: Version "v1.36-126-ga243ea63" finishing with parameters ["rclone" "sync" "r:\\rclone_test" "nas-sftp:/home/rclone_test" "--config" ".rclone.config" "-vv"]
>

**Comment by ncw** [comment]
Excellent  and many thanks for testing.

I'll close this now.
