### ISSUE TITLE
FTP bug - use of closed network connection

### ISSUE THREAD

**Issue by easy90rider** [ncw/rclone#1435]
I already wrote here: https://forum.rclone.org/t/rclone-ftp-support/2320 but it's easyer to track bugs on github.

Issue:
`use of closed network connection`

Paste of log. https://paste.ee/p/rO89x - full log, I was too lazy to filter out stuff, sorry about that.

**Comment by ncw** [comment]
Thanks for making the issue - much better for tracking!

**Comment by ncw** [comment]
I've attempted to fix this here - can you have a go please!

https://beta.rclone.org/v1.36-125-g51d2174c/ (uploaded in 15-30 mins)

**Comment by easy90rider** [comment]
I remembered that I work in IT and I would also prefer if people would use the ticketing system!

I updated now, I will let you know if I have some other bugs.

**Comment by easy90rider** [comment]
Error fixed! :)
