### ISSUE TITLE
[Google Drive] 'error reading source directory' when directory name contains " " 

### ISSUE THREAD

**Issue by RomeSilvanus** [ncw/rclone#1439]
> What is your rclone version (eg output from `rclone -V`)  

Latest Beta (rclone v1.36-126-ga243ea63β)

> Which OS you are using and how many bits (eg Windows 7, 64 bit) 

Ubuntu 16.04 LTS

> Which cloud storage system are you using? (eg Google Drive)  

Google Drive

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)  

rclone sync -v --stats 1s Google:Pony/Music www/[dir]/Pony/Music
(Same with rclone copy)

> A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

`2017/05/24 18:53:54 ERROR : Attempt 3/3 failed with 0 errors and: error reading source directory "Artists/IvoryKeysADSR/\"It's Muh Policy\"": directory not found
2017/05/24 18:53:54 Failed to sync: error reading source directory "Artists/IvoryKeysADSR/\"It's Muh Policy\"": directory not found`

If a folder has a name like this then rclone throws an error.
This folder name works on the Google Drive web interface, my MacBook Pro, and my Ubuntu server, so I see no reason why it should error out of the transfer. The same error also happens when I copy the folder to my server manually.

**Comment by ncw** [comment]
That folder has single quotes, double quotes and spaces in - all of which should work fine (and are part of the integration tests).

I tried to replicate the problem, but I didn't succeed.

Do you have any other examples of it failing?

Can you attach a log with `-vv` of it going wrong please?

```
$ rclone ls "drive:Issue 1440"
  6624250 "It's Muh Policy"/etcd-v0.4.6-linux-amd64.tar.gz
$ rclone -v copy "drive:Issue 1440" /tmp/Issue-1440
2017/05/24 23:19:23 INFO  : Local file system at /tmp/Issue-1440: Modify window is 1ms
2017/05/24 23:19:23 INFO  : Local file system at /tmp/Issue-1440: Waiting for checks to finish
2017/05/24 23:19:23 INFO  : Local file system at /tmp/Issue-1440: Waiting for transfers to finish
2017/05/24 23:19:25 INFO  : "It's Muh Policy"/etcd-v0.4.6-linux-amd64.tar.gz: Copied (new)
2017/05/24 23:19:25 INFO  : 
Transferred:   6.317 MBytes (1.752 MBytes/s)
Errors:                 0
Checks:                 0
Transferred:            1
Elapsed time:        3.6s
```

**Comment by RomeSilvanus** [comment]
-vv just gives out the same error:

2017/05/25 00:44:53 INFO  : Local file system at /home/user/www/iwatchitfortheplot/Pony/Music/Fan-made/Equestrian Beats (EQBeats.org) full rip/Artists/IvoryKeysADSR: Waiting for transfers to finish  
2017/05/25 00:44:53 ERROR : Local file system at /home/user/www/iwatchitfortheplot/Pony/Music/Fan-made/Equestrian Beats (EQBeats.org) full rip/Artists/IvoryKeysADSR: not deleting files as there were IO errors  
2017/05/25 00:44:53 ERROR : Attempt 1/3 failed with 0 errors and: error reading source directory "\"It's Muh Policy\"": directory not found  
2017/05/25 00:44:53 DEBUG : Google drive root 'Pony/Music/Fan-made/Equestrian Beats (EQBeats.org) full rip/Artists/IvoryKeysADSR': Reading ""  
2017/05/25 00:44:54 DEBUG : Google drive root 'Pony/Music/Fan-made/Equestrian Beats (EQBeats.org) full rip/Artists/IvoryKeysADSR': Finished reading ""  
2017/05/25 00:44:54 DEBUG : profile.txt: Size and modification time the same (differ by 0s, within tolerance 1ms)


If it helps, I copied the directory exactly with the same path as it is on my GDrive here:
https://drive.google.com/drive/folders/0BwltBLFvlO78emRiSlBNc0RoTTQ?usp=sharing

**Comment by ncw** [comment]
Thanks for the share of the path - that was very helpful.

I've tracked down the problem and fixed it.  The fix also will speed up the nothing to do case of syncing by almost a factor of 2.

Here is the beta

https://beta.rclone.org/v1.36-159-g3fe94482/ (uploaded in 15-30 mins).

**Comment by RomeSilvanus** [comment]
That fixed it, thanks!

**Comment by dahankzter** [comment]
I get this still, is this merged?

**Comment by ncw** [comment]
@dahankzter yes this was merged in  3fe9448

If you can reproduce with [the latest beta](https://beta.rclone.org) then please make a [new issue on github](https://github.com/ncw/rclone/issues/new) with reproduction instructions - thanks.

**Comment by dahankzter** [comment]
I will try to test it. I have installed rclone via Archlinux AUR repo. The betas work as is? No need to install any dependencies?

**Comment by ncw** [comment]
@dahankzter wrote
> The betas work as is? No need to install any dependencies?

No dependencies needed!

**Comment by SimpleBobster** [comment]
@ncw I'm still having this problem as well.

> What is your rclone version (eg output from rclone -V)
rclone v1.39
- os/arch: linux/arm
- go version: go1.9.2

> Which OS you are using and how many bits (eg Windows 7, 64 bit)
LuCI lede-17.01 branch (git-17.290.79498-d3f0685)
https://github.com/openwrt/luci

> Which cloud storage system are you using? (eg Google Drive)
Google Drive

Log:
```
root@LEDE:~# rclone copy '/mnt/sda1/Downloads/Coco (2017) (1080p).mkv' gappsucla:Movies -vv
2018/02/21 07:22:09 DEBUG : Using config file from "/root/.config/rclone/rclone.conf"
2018/02/21 07:22:09 DEBUG : rclone: Version "v1.39" starting with parameters ["rclone" "copy" "/mnt/sda1/Downloads/Coco (2017) (1080p).mkv" "gappsucla:Movies" "-vv"]
2018/02/21 07:22:10 DEBUG : Keeping previous permissions for config file: -rwxr-xr-x
2018/02/21 07:22:10 DEBUG : gappsucla: Saved new token in config file
2018/02/21 07:22:11 INFO  : Google drive root 'Movies': Modify window is 1ms
2018/02/21 07:22:11 ERROR : : error reading source directory: directory not found
2018/02/21 07:22:11 INFO  : Google drive root 'Movies': Waiting for checks to finish
2018/02/21 07:22:11 INFO  : Google drive root 'Movies': Waiting for transfers to finish
2018/02/21 07:22:11 ERROR : Attempt 1/3 failed with 1 errors
2018/02/21 07:22:12 ERROR : : error reading source directory: directory not found
2018/02/21 07:22:12 INFO  : Google drive root 'Movies': Waiting for checks to finish
2018/02/21 07:22:12 INFO  : Google drive root 'Movies': Waiting for transfers to finish
2018/02/21 07:22:12 ERROR : Attempt 2/3 failed with 1 errors
2018/02/21 07:22:12 ERROR : : error reading source directory: directory not found
2018/02/21 07:22:12 INFO  : Google drive root 'Movies': Waiting for checks to finish
2018/02/21 07:22:12 INFO  : Google drive root 'Movies': Waiting for transfers to finish
2018/02/21 07:22:12 ERROR : Attempt 3/3 failed with 1 errors
2018/02/21 07:22:12 INFO  : 
Transferred:      0 Bytes (0 Bytes/s)
Errors:                 1
Checks:                 0
Transferred:            0
Elapsed time:        2.5s

```
