### ISSUE TITLE
Onedrive replaces spaces with + signs

### ISSUE THREAD

**Issue by edimusrex** [ncw/rclone#1440]
When filing an issue, please include the following information if possible as well as a description of the problem.  Make sure you test with the latest beta of rclone.

    https://beta.rclone.org/
    https://rclone.org/downloads/

If you've just got a question or aren't sure if you've found a bug then please use the [rclone forum](https://forum.rclone.org/) instead of filing an issue.

> What is your rclone version (eg output from `rclone -V) 

rclone v1.36-129-gae9f8304

> Which OS you are using and how many bits (eg Windows 7, 64 bit)

Windows 10 x64

> Which cloud storage system are you using? (eg Google Drive)

Microsoft Onedrive

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

rclone copy D:\ megatron:D_drive --config=.rclone.conf --exclude-from excluded.txt --checksum --update --retries 5 --transfers=6 --ask-password=false --stats=10s --log-file=D_sync.log -v

> A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

Here's a sample of the output

> Transferring:

>  * ... AmpliTube 4 v4.0.2 WiN X64 FULL.part1.rar: 50% done, 810.632 kBytes/s, ETA: 31s
>  * ... AmpliTube 4 v4.0.2 WiN X64 FULL.part2.rar: 39% done, 637.069 kBytes/s, ETA: 48s
>  * ... AmpliTube 4 v4.0.2 WiN X64 FULL.part3.rar: 39% done, 563.986 kBytes/s, ETA: 54s
> * ... AmpliTube 4 v4.0.2 WiN X64 FULL.part4.rar: 52% done, 931.460 kBytes/s, ETA: 26s

The issue is that the above files will always continue to be copied regardless of if they exist on the destination or not.  Once copied the file name is changed by onedrive (I assume) and every space is replaced with a + sign.  This is only an issue because rclone does not recognize the new file name when doing a comparison so files are not properly skipped on copy or sync.

**Comment by ncw** [comment]
This issue has a lot in common with #1296 which is fixed.  You've said you've tried it with the latest beta though.

@yonjah did we miss a QueryEscape in 32e9c86fcdb38d77dc5018f6184e4f3607c714d9 ?

**Comment by ncw** [comment]
Are you sure you tried this with the latest beta - I just attempted to replicate and it seemed to work fine.

```
$ rclone copy -vv space-test onedrive:space-test
2017/05/25 09:18:43 DEBUG : rclone: Version "v1.36-DEV" starting with parameters ["rclone" "copy" "-vv" "space-test" "onedrive:space-test"]
2017/05/25 09:18:44 DEBUG : onedrive: Saved new token in config file
2017/05/25 09:18:45 INFO  : One drive root 'space-test': Modify window is 1s
2017/05/25 09:18:46 DEBUG : One drive root 'space-test': Reading ""
2017/05/25 09:18:46 DEBUG : One drive root 'space-test': Finished reading ""
2017/05/25 09:18:46 INFO  : One drive root 'space-test': Waiting for checks to finish
2017/05/25 09:18:46 INFO  : One drive root 'space-test': Waiting for transfers to finish
2017/05/25 09:18:46 INFO  : file with spaces.txt: Copied (new)
2017/05/25 09:18:46 INFO  : 
Transferred:      6 Bytes (1 Bytes/s)
Errors:                 0
Checks:                 0
Transferred:            1
Elapsed time:        3.4s
2017/05/25 09:18:46 DEBUG : Go routines at exit 7
2017/05/25 09:18:46 DEBUG : rclone: Version "v1.36-DEV" finishing with parameters ["rclone" "copy" "-vv" "space-test" "onedrive:space-test"]

$ rclone ls onedrive:space-test
        6 file with spaces.txt

$ rclone copy -vv space-test onedrive:space-test
2017/05/25 09:19:14 DEBUG : rclone: Version "v1.36-DEV" starting with parameters ["rclone" "copy" "-vv" "space-test" "onedrive:space-test"]
2017/05/25 09:19:14 INFO  : One drive root 'space-test': Modify window is 1s
2017/05/25 09:19:14 DEBUG : One drive root 'space-test': Reading ""
2017/05/25 09:19:14 DEBUG : One drive root 'space-test': Finished reading ""
2017/05/25 09:19:14 INFO  : One drive root 'space-test': Waiting for checks to finish
2017/05/25 09:19:14 DEBUG : file with spaces.txt: Size and modification time the same (differ by -474.334908ms, within tolerance 1s)
2017/05/25 09:19:14 DEBUG : file with spaces.txt: Unchanged skipping  <<<<<<<<<<<< file not copied again
2017/05/25 09:19:14 INFO  : One drive root 'space-test': Waiting for transfers to finish
2017/05/25 09:19:14 INFO  : 
Transferred:      0 Bytes (0 Bytes/s)
Errors:                 0
Checks:                 1
Transferred:            0
Elapsed time:       500ms
2017/05/25 09:19:14 DEBUG : Go routines at exit 7
2017/05/25 09:19:14 DEBUG : rclone: Version "v1.36-DEV" finishing with parameters ["rclone" "copy" "-vv" "space-test" "onedrive:space-test"]
```

**Comment by edimusrex** [comment]
I'm pretty sure I tried the latest beta but I will definitely try it again.

**Comment by ncw** [comment]
Thanks!  If there is a problem with the latest beta can you make a little demo like the one I made to show exactly how to reproduce it.

**Comment by edimusrex** [comment]
I am currently testing it from the version you listed above and it is working fine.  I will re test with the current beta as well, thank you

**Comment by ncw** [comment]
I'm going to close this one as fixed - please re-open if you think otherwise.

Thanks

**Comment by edimusrex** [comment]
yes, it was in fact fixed.  Thank you!
