### ISSUE TITLE
Backup-dir not working with mount

### ISSUE THREAD

**Issue by calisro** [ncw/rclone#1446]
It doesn't appear that the backup-dir switch works with mounts.  It's this something that could be added? I'd like to be able to track and have a backup of all changes occurring in my mounts.  

It also doesn't appear to work with regular local filesystems or local remotes.

**Comment by ncw** [comment]
backup-dir wasn't intended to work with mounts.

What would you want it do do?

Whenever you overwrite a file or delete one it moves the old file to backup-dir would be the obvious choice.  That is pretty much how backup dir works for sync.

**Comment by calisro** [comment]
I was intending on using it exactly like sync/copy works now just like you said. The only thing that just came to mind though it's the fact that a date driven directory structure won't work because it's evaluated at mount time which effectively makes it less useful since multiple files 'backups' will overwrite. I might as well use the gdrive-use-trash switch instead.

**Comment by ajkis** [comment]
Hmm did not find gdrive-use-trash in docs

**Comment by calisro** [comment]
@ajkis  --drive-use-trash                   Send files to the trash instead of deleting permanently.

**Comment by calisro** [comment]
Closing this as I cant think of a better way to handle it.
