### ISSUE TITLE
Feature: ACD - switch back end to use web scraping instead of the API.

### ISSUE THREAD

**Issue by gordan-bobic** [ncw/rclone#1454]
As the title says - how viable would it be to switch the ACD back end to use web scraping instead of the API interface?

**Comment by madyoda** [comment]
I imagine it requires a lot of work, never mind the complications and errors that will it cause.

**Comment by ncw** [comment]
This might be possible, but I don't really want to do it as I'm sure it would end up with rclone being in trouble with Amazon again!

**Comment by ncw** [comment]
I'm going to close this ticket now as I don't think this is a good direction for rclone to go in.
