### ISSUE TITLE
Doc Improvement: Required S3 Perms

### ISSUE THREAD

**Issue by ebridges** [ncw/rclone#1455]
Hi,

After doing some research I figured out a policy for S3 that includes the least permissions required for `rclone sync` to function.

I provide it here because I'm not sure where you'd like to share such info -- couldn't find an appropriate place on the `s3.md` doc & the forum seems it would get lost. Glad to relocate elsewhere as you direct.

Some notes/caveats:
* This is a policy that can be used when creating bucket.  It assumes that `USER_NAME` has been created.
* The `Resource` entry must include both resource ARNs, as one implies the bucket and the other implies the bucket's objects.

Example Ansible playbook to generate one or more buckets:
https://gist.github.com/ebridges/ebfc9042dd7c756cd101cfa807b7ae2b

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": {
                "AWS": "arn:aws:iam::USER_SID:user/USER_NAME"
            },
            "Action": [
                "s3:ListBucket",
                "s3:DeleteObject",
                "s3:PutObject",
                "s3:PutObjectAcl"
            ],
            "Resource": [
              "arn:aws:s3:::BUCKET_NAME/*",
              "arn:aws:s3:::BUCKET_NAME"
            ]
        }
    ]
}
```

**Comment by ebridges** [comment]
cf.: https://forum.rclone.org/t/what-permissions-does-rclone-require-for-s3/2702

**Comment by ncw** [comment]
That looks very useful :-)

I think the best place would be in `docs/content/s3.md` as a new section - say "S3 permissions".  If you could explain in words what permissions are needed and link to your ansible playbook that would be perfect I think.

Fancy sending a PR for that?

**Comment by ebridges** [comment]
Just noticed that this is not on the website documentation page: 
https://rclone.org/s3/

How does that get updated?  Should I submit an additional PR for that?

**Comment by sjurtf** [comment]
From what I understand, the documentation pages follows the rclone release cycle. 
The page will be updated when rclone 1.37 is released.

**Comment by vogd** [comment]
those permissions are not enough.
Please follow an article:
 https://aws.amazon.com/premiumsupport/knowledge-center/s3-access-denied-bucket-policy/

You should add those to avoid following error 
"
ERROR : S3 bucket home: Failed to update region for bucket: reading bucket location failed: AccessDenied: Access Denied
	status code: 403, request id: xxxxx, host id: yyyyyy
2021/07/15 22:04:12 ERROR : : error listing: BucketRegionError: incorrect region, the bucket is not in 'us-west-2' region at endpoint ''
	status code: 301, request id: , host id:
"
