### ISSUE TITLE
Latest beta can't write to config file on windows

### ISSUE THREAD

**Issue by azureblaze** [ncw/rclone#1458]
> What is your rclone version (eg output from `rclone -V`)
```
~ rclone.exe version
rclone v1.36-151-g48508cb5
```
> Which OS you are using and how many bits (eg Windows 7, 64 bit)

Windows 10 64 bit

> Which cloud storage system are you using? (eg Google Drive)

All

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

All

> A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
```
~ rclone.exe ls gdrive:
2017/06/01 HH:mm:ss Failed to create temp file for new config: open C:\Users\*redacted*\AppData\Local\Temp\C:\Users\*redacted*\.config\rclone\rclone.conf059243011: The filename, directory name, or volume label syntax is incorrect.
```

Any command that requires writing to the config, for example `rclone config` or any command involving a remote like google drive which requires writing to the config fails as a result.

**Comment by ncw** [comment]
@breunigs this is probably related to your changes.

**Comment by ncw** [comment]
This had an easy fix - please find a beta here:

https://beta.rclone.org/v1.36-154-gb0474022/ (uploaded in 15-30 mins)
