### ISSUE TITLE
Google Drive Mount shows no modified date of folders

### ISSUE THREAD

**Issue by xanthos84** [ncw/rclone#1460]
I am using Subsonic/Madsonic MP3 Server with a mounted Google Drive on Debian Jessie,
and all the folders on the mounted drive have the modification date == creation date.
But for Subsonic to scan again the folder for new files,
it searches for the modtime on the folders - which are not changed, even if you upload files ( i am not using rclone to upload files! I am using the google drive interface on another pc)

So, could you add a flag for the startup mount process which pulls and refreshes the modtime on folders?

> What is your rclone version (eg output from `rclone -V`)
latest beta
> Which OS you are using and how many bits (eg Windows 7, 64 bit)
Debian Linux Jessie
> Which cloud storage system are you using? (eg Google Drive)
Google Drive
> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone mount --allow---config /root/.rclone.conf g:/my google drive/ /home/mount/

**Comment by xanthos84** [comment]
Okay, I guess its not rclone's fault here... did some more research and came up that the folder date on Google Drive itself gets not updated.
So for a workaround I wrote a script which renames the parent-folders to a temporary name and back,
which gets the modified date updated.

**Comment by ncw** [comment]
Rclone doesn't currently support syncing the dates on folders.  It will at some point, probably as part of #100

**Comment by breunigs** [comment]
Here's another workaround idea: you can simply chmod the folders on the rclone mount. It is stored locally in memory, so it will be lost once you restart rclone. This would be just one API call though, and probably less prone to race conditions.

**Comment by pjsurk** [comment]
Did you find an easy solution to this? I'm also trying to use Subsonic with gdrive mounted with rclone.
