### ISSUE TITLE
Crypt mount underlying dir reference

### ISSUE THREAD

**Issue by tcf909** [ncw/rclone#1461]
When a Crypt store is mounted against a directory and that underlying directory is unmounted (de-referenced, etc), rclone does not make any attempt to re-reference the directory.

Example:

Using another fuse filesystem to mount: /data
Setup a Crypt mount to use /data
Other fuse filesystem crashes or is forced to unmount
The Crypt mount now appears empty

Example 2:

rclone mount starts before you are able to mount another filesystem at /data (so you have an empty /data dir still). The other filesystem then starts and mounts /data. the rclone crypt mount still appears empty (referencing the old /data dir).

This could be considered a feature, but definitely causes problems (bug) with layered fuse filesystems.

**Comment by ncw** [comment]
Does rclone recover after the directory cache expires?  I would expect it to.  In which case you could send SIGHUP to reread the mount in these situations. (That is only in the beta I think)

**Comment by tcf909** [comment]
I'll have to double check, but as of latest release (not beta) it does not.
Could also be that I'm lazy unmounting and the old dir is still floating in
memory to reference.
