### ISSUE TITLE
failed to mount FUSE fs: exit status 255

### ISSUE THREAD

**Issue by alitrack** [ncw/rclone#1463]
When filing an issue, please include the following information if possible as well as a description of the problem.  Make sure you test with the latest beta of rclone.

    https://beta.rclone.org/
    https://rclone.org/downloads/

If you've just got a question or aren't sure if you've found a bug then please use the [rclone forum](https://forum.rclone.org/) instead of filing an issue.

> What is your rclone version (eg output from `rclone -V`)
v1.36
> Which OS you are using and how many bits (eg Windows 7, 64 bit)
Mac OS X
> Which cloud storage system are you using? (eg Google Drive)
OneDrive
> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone mount -v --allow-non-empty --allow-other onedrive:job/ ~/onedrive

> A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

```
2017/06/03 06:23:32 DEBUG : rclone: Version "v1.36" starting with parameters ["rclone" "mount" "-vv" "--allow-non-empty" "--allow-other" "onedrive:job/" "/Users/steven/onedrive"]
2017/06/03 06:23:33 INFO  : One drive root 'job': Modify window is 1s
2017/06/03 06:23:33 DEBUG : One drive root 'job': Mounting on "/Users/steven/onedrive"
2017/06/03 06:23:33 Fatal error: failed to mount FUSE fs: exit status 255
```

**Comment by ncw** [comment]
Can you try the latest beta please to see if it is the same? Also double check the installation of OSXFUSE.

Thanks

**Comment by alitrack** [comment]
also tried the latest beta, same issue, and installed the last version OSXFUSE

**Comment by ncw** [comment]
Does the path "/Users/steven/onedrive" exist?

Can you get any other OSXFUSE file systems to work, eg sshfs?

**Comment by alitrack** [comment]
need reboot after install OSXFUSE.

it works now, thanks!

**Comment by ncw** [comment]
Excellent :-)
