### ISSUE TITLE
Hubic Problems 500 Internal Error

### ISSUE THREAD

**Issue by kaileu** [ncw/rclone#1469]
I wanted to try Hubic but evertme i want to upload something i get a 500 Error.

rclone -vv copy README.html HubicDrive:Serien --no-check-certificate
2017/06/08 17:23:52 DEBUG : rclone: Version "v1.36" starting with parameters ["rclone" "-vv" "copy" "README.html" "HubicDrive:Serien" "--no-check-certificate"]
2017/06/08 17:23:54 DEBUG : Hubic: Got swift credentials (expiry 2017-06-09 16:41:08 +0200 CEST in 23h17m13.7863541s)
2017/06/08 17:23:54 INFO  : Hubic Swift container Serien: Modify window is 100ns
2017/06/08 17:24:54 INFO  :
Transferred:      0 Bytes (0 Bytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:      1m1.9s

2017/06/08 17:25:54 INFO  :
Transferred:      0 Bytes (0 Bytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:      2m1.9s

2017/06/08 17:26:38 ERROR : Attempt 1/3 failed with 1 errors and: HTTP Error: 500: 500 Internal Error

**Comment by ncw** [comment]
I see these too.  I don't think it is an rclone problem - I think it is a Hubic problem.  Specifically if you try to use anything but the default bucket it seems to take a very long time with lots of errors to create it.  Once it is created it is OK, so I suggest you keep trying.

**Comment by hienntbdg** [comment]
"500 Internal Error" when filename has special character.

**Comment by qopencc** [comment]
use defult path
rclone -vv copy README.html HubicDrive:default/Serien --no-check-certificate

**Comment by ashleyconnor** [comment]
If you need to prepend `default` then you can't encrypt filenames as default gets encrypted too 😢
