### ISSUE TITLE
[Google Drive] Allow retrieving file/folder ID

### ISSUE THREAD

**Issue by pgcd** [ncw/rclone#1473]
I'm trying to use rclone in a script to move local media to Google Drive and replace them with a STRM file (that can be parsed and played back by Kodi). The STRM file requires the id of the file (or the parent folder) to be played back - the same ID that constitutes the last part of the URL when opening the file or folder in the browser, and that is returned in the JSON response.
I have tried with every verbosity level and I've pored over the docs but there seems to be no way of returning this ID, except (possibly) with the --dump-bodies flag and some extremely unwield response + JSON parsing.
Since it appears to me that rclone uses the ID internally, would it be possible to add a command (or a flag) to display the ID so that it can be parsed by scripts? 
Absolute best would be a flag that can be applied to copy/move as well, but I realize that pertains to my specific case.

Unfortunately, I have never attempted anything with Go so I don't think I can contribute a PR, but if it turns out that time is very scarce, I might try and see if I can do it nonetheless.

**Comment by ncw** [comment]
Assuming you are only interested in file IDs, then you could do this by changing the `newObjectWithInfo` in `drive/drive.go` to add just before the return `fs.Debugf(o, "ID = %q", o.id)`.  This might open the door for logging other stuff like the download URL which I know I've been asked for.

Have a play with that and see if that is useful then we can think about how to integrate it properly.

**Comment by pgcd** [comment]
That's absolutely enough for my current needs and I have implemented it with a (probably unneeded) PR. Also, reading a bit about Go and scrolling through the code I found it to be extremely interesting, so I'll see if I can write some real code next weekend (unless somebody beats me, of course, which would definitely be preferable for rclone itself =))
