### ISSUE TITLE
New auth Proxy - Token expires after 1h

### ISSUE THREAD

**Issue by Axcy** [ncw/rclone#1475]
`> What is your rclone version (eg output from `rclone -V`)`
rclone v1.36 (Latest beta)

`> Which OS you are using and how many bits (eg Windows 7, 64 bit)`
Windows(For token) - Debian Jessie x64 for transferring

`> Which cloud storage system are you using? (eg Google Drive)`
Google to Amazon

`> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)`
rclone -vv --dump-headers copy --size-only --transfers=12 --drive-chunk-size=64M "Gkcrypt:/TV Shows/" "Acrypt:/TV Shows/" --log-file=/home/jsd/rclone-upload.cron.log

`> A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)`
[rclone-upload.cron.zip](https://github.com/ncw/rclone/files/1066504/rclone-upload.cron.zip)

As discussed in https://forum.rclone.org/t/proxy-for-amazon-cloud-drive/2848/23 - The token doesn't seem to get refreshed and expires after about an hour.

**Comment by ncw** [comment]
I've treid to replicate this using a long upload.  I failed though - the token got renewed just fine.

Looking at your log it is trying to renew the token with Amazon rather than the proxy... The user agent is `User-Agent: rclone/v1.36` so that probably means you are not using the beta on the linux box.

I suspect if you use the beta on the linux box too it will work fine.

**Comment by Axcy** [comment]
Is there any way to get the exact rclone version output? Because I've downloaded the latest version and installed multiple times?

**Comment by ncw** [comment]
`rclone version` or `rclone -V`.  If you got an official build then it will have a correct version number.  If you built it yourself it won't unless you used the Makefile.

**Comment by Axcy** [comment]
Apologies - This has been a unintentionally error from my side . On a OVH/Kimsufi Debian Jessie, it seems despite following the official rclone install guide rclone is copied to both /usr/bin AND /usr/sbin/ !

I was following the guide and deleting from /usr/bin/, however not removing from the /usr/sbin/ at the same time :( I've done that now, and it seems to be working fine. 

Closing the issues.

**Comment by ncw** [comment]
Glad you got it working.  The official docs changed at some point from /usr/sbin (which is incorrect) to /usr/bin so understandable there was some confusion.
