### ISSUE TITLE
Investigate not normalising file names and normalising them in the sync routine instead

### ISSUE THREAD

**Issue by ncw** [ncw/rclone#1477]
Investigate this: I'm beginning to think I've made a mistake normalizing the file names, what I should be doing is normalizing them in the sync routine when rclone is comparing source and destination directory, rather than normalizing them all the time.

Normalizing the file names causes issues with other tools which don't (it doesn't seem to be the expected way of doing things).

Originally from #1472

See also #1515 for normalization problems when using a single file copy (and thus --files-from and all the other filters...)

Note from #62 

> One other thing I noticed regarding the drive code, is for directories ending in one or more spaces. The Google Drive Windows App will replace the ending spaces with "_", because Windows doesn't like directories ending in blank spaces. For Linux, it doesn't matter.

It occurs to me that the filename matching code should transform the input strings using the OS transformation before comparison. so if either src or remote is local on windows, it should transform the input into the Windows safe version before doing the comparison.

Likewise if one of the remotes is case insensitive then it should transform everything into lower case (checking for case folded matches).

Would also need to convert the check routine to use this framework.

So the pipeline of filename transformations might look like

  * -> normalize unicode
  * -> lower case (if dst is case insensitive, or possibly if src | dst case insensitive for bidirectional goodness)
  * -> make Windows safe

And then do the name comparisons in `matchListings`

Could have an optional transform function for each Fs which does lossy translation of unacceptable characters.  Local would do the Windows transforms on windows.  Others might get rid of control characters (or perhaps there should be a default one which does that).  Fses would then use their Transform function when writing objects.

Need to think carefully about

  * copyto/moveto
  * filters - especially single file copies

**Update** after a bit of testing with `rclone info` there are no remotes which complain about denormalized UTF-8.  There are some (eg onedrive, dropbox) which will read denormalized UTF-8 or normalized UTF-8.

Have two types of transform, one for comparison purposes and one for writing the file purposes.  Perhaps these are identical except for the case insensitivity.

**Comment by 2600box** [comment]
thanks for the important label! looking forward to this

**Comment by ncw** [comment]
This is all done now

https://beta.rclone.org/v1.37-149-g4ac9a650/ (uploaded in 15-30 mins)
