### ISSUE TITLE
fusermount nonempty message isnt clear enough

### ISSUE THREAD

**Issue by FernandoMiguel** [ncw/rclone#1479]
Some less experienced users might find the following message confusing:
2017/06/12 11:25:02 mount helper error: fusermount: if you are sure this is safe, use the 'nonempty' mount option

maybe capture this and either fallback to use --allow-non-empty  or show the user the error message stating to try with --allow-non-empty , which is a proper native command for rclone

**Comment by ncw** [comment]
It might actually be easier for rclone to check the mount directory is empty itself.

**Comment by xerrni** [comment]
https://github.com/ncw/rclone/pull/1814

My pull request fixes this issue.

**Comment by xerrni** [comment]
@ncw 
I think you can close it now. 
Fix has been merged as #1814

**Comment by ncw** [comment]
Thanks for the reminder @xerrni  (apologies for the delay in responding).  Next time Put `Fixes #1479` in your commit message and it will get closed automatically :-)

@FernandoMiguel - please find the fix in [the latest beta](https://beta.rclone.org)
