### ISSUE TITLE
ACD: Is this correct?

### ISSUE THREAD

**Issue by klauspost** [ncw/rclone#148]
Just stumbled upon: 

https://github.com/ncw/rclone/blob/master/amazonclouddrive/amazonclouddrive.go#L470

It seems like it does the opposite of what is intended... ie use "size" if it is 0, doesn't if it is something else,

**Comment by klauspost** [comment]
ok, so this is for the file size is exactly 0 bytes, right?

Maybe `PutSized` should be called `PutZeroSized`?

**Comment by ncw** [comment]
In theory both of those methods should work. However Put works for files which are non zero sized. PutSized works for empty files and some other files (data dependent). 

So yes you are probably right, PutSized should be PutZeroSized . I really think Put should be able to upload zero sized files though - I couldn't figure out why Amazon doesn't like it.

**Comment by ncw** [comment]
Note also that Put does Base64 encoding whereas PutSized doesn't and should be more efficient.

**Comment by klauspost** [comment]
So we should actually never use "Put"?

**Comment by klauspost** [comment]
The weird thing is that "PutSized" is 10x slower than "Put" fro some reason.

**Comment by ncw** [comment]
Strange! I think we are stuck with Put over PutSized since the latter doesn't actually work with Amazon very well :-(
