### ISSUE TITLE
way to specifically ignore symlinks so i don't get the warning message?

### ISSUE THREAD

**Issue by vesper8** [ncw/rclone#1480]
I like to use sync feature with -v on, however right now this is causing my sync jobs to show a lot of spam related to "Can't follow symlink without -L/--copy-links"

I would appreciate it if I could specifically tell rclone to ignore symlinks so that it doesn't show those warning messages

**Comment by ncw** [comment]
It should probably only print that message once I think.  Would that be acceptable?

**Comment by vesper8** [comment]
it does only print it once.. once per symlinks. There are thousands of symlinks as part of the folders that I sync

I notice that the symlinks message is a "NOTICE" whereas the deletions and copy are "INFO"

I would like to either set a flag so that it specifically ignores symlinks so as to not show any notices, or alternatively I would like the -v to only show INFO messages but not NOTICE messages

I had asked for this before and you had seemed to be interested.. in basically allowing us to have more control over what -v outputs

**Comment by darren12345** [comment]
Just adding my vote to this too.

**Comment by goneafk** [comment]
Seconding this. My log reports are basically nothing but symlink warnings.

**Comment by 2600box** [comment]
thirding this

**Comment by 2600box** [comment]
just wondering, since this is tagged "easy/quickie/ if there is a chance it could be included in 1.37?

**Comment by ncw** [comment]
This has now been fixed with the `--skip-links` flag.

https://beta.rclone.org/v1.37-020-g8b30023f/ (uploaded in 15-30 mins)

**Comment by vesper8** [comment]
awesome thanks!

@ncw i'm noticing none of the 1.37 betas have mac builds.. they only have 2 each for windows.. is it because the other builds haven't been generated yet?

**Comment by ncw** [comment]
I broke the build - now fixed. Try a later build, eg https://beta.rclone.org/v1.37-024-g1ecf2bcb/

**Comment by CottonEaster** [comment]
`--skip-links` doesn't seem to work when `--log-level` is set to `INFO` (in rclone 1.37). Is this by design? I'd rather not see those warnings even at that log level.

**Comment by ncw** [comment]
@CottonEaster  you'll need [the latest beta](https://beta.rclone.org) to use this

**Comment by CottonEaster** [comment]
Thank you. I do have the latest, or at least a recent, beta. On the other hand, I think my backup script was passing commands to rclone wrongly. So I think this bug can stay closed. Apologies.
