### ISSUE TITLE
"AcquireSRWlockExclusive" not found in KERNEL32.dll

### ISSUE THREAD

**Issue by lechunlx** [ncw/rclone#1481]
I'm getting an error on beta-latest-windows-386 (rclone v1.36-169-g9a11d3ef) about "AcquireSRWlockExclusive" not found in KERNEL32.dll - using my Windows 2003 SP1 32bit.

It didn't work even with a rclone -V command.

**Comment by ncw** [comment]
That function `AcquireSRWlockExclusive` is only available in windows 2008 or Vista and above, however Go should work with WIndows XP+.

Can you try this binary please?

I compiled it without cgo and therefore without `rclone mount`.

[rclone-v1.36-173-g68333d34.zip](https://github.com/ncw/rclone/files/1075001/rclone-v1.36-173-g68333d34.zip)

**Comment by lechunlx** [comment]
Yes, now it works on Win2k3 perfectly!

**Comment by ncw** [comment]
@billziss-gh do you have an thoughts about this? Is this related to the WinFSP intiialization?

**Comment by billziss-gh** [comment]
WinFsp uses Vista and higher API's. `AcquireSRWlockExclusive` is only available on Vista and higher as you correctly observe.

However cgofuse does not load the WinFsp DLL unless `Mount` is called. It also loads it dynamically, so that if WinFsp is not installed it will fail gracefully. So it is not immediately obvious to me how WinFsp is responsible for this.

**Comment by billziss-gh** [comment]
@ncw I can make the necessary changes in cgofuse and you can then pull them. But I have no Windows XP anywhere to test them anymore.

**Comment by ncw** [comment]
@billziss-gh thanks for looking into this.

I plan to support XP as long as go does.

I don't think we need to support mount on XP though, so would it be possible just to set an unsupported flag in the init which produces an error when mount is called? I'm guessing that wouldn't work unless we dynamically load the AcquireSRWlockExclusive symbol?

Another alternative is I just make a build without mount for XP era Oses and we leave the mount code alone which might be simpler all round.

**Comment by billziss-gh** [comment]
WinFsp will not load/run on XP, so cgofuse `Mount` will naturally fail. For this to work I will eliminate the slim lock and replace it with a critical section, which exists on XP. I will make this change in the weekend.

**Comment by ncw** [comment]
Thanks @billziss-gh that would be perfect :-)

**Comment by billziss-gh** [comment]
I have updated cgofuse to eliminate the dependency on `AcquireSRWlockExclusive `:

https://github.com/billziss-gh/cgofuse/commit/35bcf037030dcadcd247618c75c00c6cd17482d7

However none of the CI services (TravisCI, AppVeyor or CircleCI) have kicked in to test the change. I am not certain why this is the case. Is there some kind of intermittent github issue?

In any case once this is tested I will tag it so you can pull the changes using godep.

**Comment by billziss-gh** [comment]
All cgofuse tests pass. Latest version of cgofuse has been tagged `v1.0.2`.

**Comment by ncw** [comment]
Thanks for fixing that @billziss-gh :-)

A beta test which includes those fixes can be found in

https://beta.rclone.org/v1.36-196-g4ce31555/ (uploaded in 15-30 mins)

Please re-open if it doesn't fix the problem.

Thanks

Nick

**Comment by balazer** [comment]
rclone-v1.36-219-gaa204864-windows-386 and rclone-v1.37-101-g0158ab69-windows-386 fail for me in Windows XP SP2 32-bit with this error:  "The procedure entry point RegGetValueW could not be located in the dynamic link library ADVAPI32.dll".  A bit of googling shows that RegGetValueW is only supported in 64-bit Windows XP.
 
Your rclone-v1.36-173-g68333d34.zip without cgo and therefore without rclone mount works fine.

**Comment by billziss-gh** [comment]
@balazer thanks for tracking this down.

WinFsp is only supported on Win7+ and (the Windows portion of) cgofuse was written with this in mind. However since rclone supports WinXP, cgofuse should fail gracefully on that platform. We should create a workaround for RegGetValueW in [`FspLoad`](https://github.com/billziss-gh/cgofuse/blob/master/fuse/host.go#L94-L152). If anyone is willing to tackle this I will happily accept a cgofuse PR, or I can look at it when I am back from vacation.

**Comment by rivo** [comment]
I'm not familiar enough with that part to help out but I'm getting the same message as @balazer, on startup (so unfortunately, I cannot use rclone on my old XP SP2 machine at the moment which I need to back up). Will there be a separate issue to follow?

**Comment by billziss-gh** [comment]
@rivo and/or @balazer 

Please open an issue with [cgofuse](https://github.com/billziss-gh/cgofuse) and reference this issue as this is where this should be fixed.

**Comment by rivo** [comment]
@billziss-gh Shouldn't this error only occur when `rclone mount` is run, though? At this point, I'm getting the error even if I just want to list the command-line options. Personally, I don't need `rclone mount` on XP. Not sure if @balazer agrees but if we could get the basic operations (`ls`, `copy`, `sync`) to work on XP, that would already help.

**Comment by balazer** [comment]
@rivo, until the Windows XP issue is fixed, you can use an older version of rclone.  https://downloads.rclone.org/rclone-v1.36-windows-386.zip and https://github.com/ncw/rclone/files/1075001/rclone-v1.36-173-g68333d34.zip work fine, as do 1.35 and earlier.

**Comment by billziss-gh** [comment]
@rivo I agree. Unfortunately cgofuse is statically linked into rclone, which causes this problem. I will see if I can get a quick fix.

**Comment by billziss-gh** [comment]
@ncw I have release a fix for the `RegGetValueW` problem on WinXP 32-bit. The fix is tagged 1.0.3. Please pull and test.

Related cgofuse issue: billziss-gh/cgofuse#17

**Comment by rivo** [comment]
rclone runs now on Win XP SP2 without this error message. Thanks a bunch!

**Comment by billziss-gh** [comment]
@rivo thanks for the confirmation. I am assuming that you built your own rclone version with cgofuse 1.0.3?

**Comment by rivo** [comment]
If `go get -u github.com/ncw/rclone` retrieves cgofuse 1.0.3, then yes. ;-)

**Comment by balazer** [comment]
Building from source works for me too in Windows XP SP2 32-bit.  But the latest rclone beta still has the error.  Does that mean Nick needs to explicitly pull the new cgofuse version?

**Comment by billziss-gh** [comment]
The latest version in the master branch still uses cgofuse 1.0.2:

https://github.com/ncw/rclone/blob/master/Gopkg.lock#L52-L56

I believe that this should be updated to point to cgofuse 1.0.3 for the fix to be included in future builds of rclone. I also note that this issue was piggybacked on an earlier closed issue, so perhaps @ncw is ignoring these discussions.
