### ISSUE TITLE
Uploading to dropbox speed is fluctuating abnormally

### ISSUE THREAD

**Issue by SanderM2** [ncw/rclone#1483]
I just tried uploading a 16Gb file to my dropbox account using the command "rclone copy file dropbox:" and according to my bandwidth monitor the upload didn't start right away but it started after waiting about 10 seconds or so. It then jumped to 30mbit/s and a couple seconds later it falled back to doing nothing at all...

I let it run and I can clearly see in my bandwidth graphs that it's uploading like 2 seconds at 30mbits/sec and then wait 10seconds or more doing nothing at all.

I assume this is a bug but what info do you need in order to get this sorted out? 
I'm using ""rclone-v1.36-linux-amd64"

**Comment by SanderM2** [comment]
Maybe good to know:

When the upload speeds stall, the process is also not busy doing anything else. "top" is showing 0% cpu....

**Comment by ncw** [comment]
Are you using `--bwlimit`?

Can you try with the latest beta please?  I've completely re-written the dropbox code to use the v2 API since 1.36!

**Comment by SanderM2** [comment]
I'm not using --bwlimit but will try again with latest beta later today (asap) and report back.

**Comment by SanderM2** [comment]
I thought I had to compile it myself but you have precompiled binaries available too. So I retried with "rclone-v1.36-170-g2ca477c5β-linux-amd64" and I'm having exactly the same issue.

When using dropbox's own client it's a steady 10mbyte/sec  while uploading but with rclone it peaks to 30mbyte/sec and then stalls.. repeating the process.

And I now realize I said mbit in my previous posts but I was talking about mbyte/sec actually.. I have a fast connection here.

**Comment by SanderM2** [comment]
I have tested an upload with this version and added -vv as parameter.

It now shows things like this:

2017/06/13 18:41:56 DEBUG : tst: Uploading chunk 1/5
2017/06/13 18:42:38 DEBUG : tst: Uploading chunk 2/5
2017/06/13 18:43:18 DEBUG : tst: Uploading chunk 3/5
2017/06/13 18:43:55 DEBUG : tst: Uploading chunk 4/5
...

It shows "Uploading chunk x/y" and as soon this message appears I see my traffic go up to 30mbyte/sec for a couple seconds and then stalls. It's not just slowing down, it's not generating any traffic at all, cpu is 0% too.
When the next "Uploading chunk x/y" message appears it does exactly the same.

It looks like the script is waiting for something after uploading?

**Comment by SanderM2** [comment]
Today I started a different test. Uploading many files, instead of big ones, with rclone to dropbox.
It's now uploading many many image files and it looks like it's only able to upload one picture per second at best. Which is pretty slow and going to take a long time :(

Now, I'm not sure if this would be faster with the original Dropbox client, I never tested this.
But I can't easily test it either because the images are on a NAS and the original dropbox client has no support for that afaik.

While rclone is running I see messages like this:

2017/06/14 16:14:19 DEBUG : pacer: Rate limited, increasing sleep to 20ms
2017/06/14 16:14:19 DEBUG : pacer: low level retry 1/1 (error too_many_write_operations/.)
2017/06/14 16:14:19 DEBUG : album/10036/26668/1515498.JPG: Received error: upload failed: too_many_write_operations/. - low level retry 1/10
2017/06/14 16:14:19 DEBUG : pacer: Reducing sleep to 15ms

I'm just telling this because maybe this might be related to the initial problem discussed here..
Or maybe it's something different as it's telling things like "rate limited". 

On the other hand I did do some more tests with Dropbox original client and uploading files 10Gb in size is always about the same speed: about 8 - 9mbyte/sec on my network graphs.

Uploading the same file with rclone is fluctuating a lot like already discussed above and on average the speed is more like 3mbyte/sec (calculated, based on time & file size). That's like half the speed of the original client?

**Comment by SanderM2** [comment]
I'm not a real programmer here but looking at the dropbox code it looks like it has a minSleep and maxSleep setting that's hardcoded in the source. But Dropbox has a documentation about data ingress and rate limits here : https://www.dropbox.com/developers/reference/data-ingress-guide

As you can see there it should return a header called "Retry-After" which should be used to avoid those rate limit warnings.

I'm not sure but it looks like rclone doesn't have this implemented? Am I right?

**Comment by ncw** [comment]
I think what is happening with the chunked uploads is that rclone is reading a chunk off disk then uploading it, so the pause is the read off disk bit.  Or it could possibly be dropbox processing the chunk.

Can you try  `--buffer-size 128M` - this should let the buffer get 1 upload chunk ahead.  Try it bigger and smaller too if it is easy.  Note that it will use 128M for each transfer in progress potentially - so just try this on your 16GB file to start with.

Some of the other remotes have more sophisticated multipart uploads where you can upload the parts in parallel, but [I don't think that is possible with dropbox](https://www.dropbox.com/developers/documentation/http/documentation#files-upload_session-append_v2).  rclone could be making more of an effort to parallelize the loading of chunks and the sending of data.  If the `--buffer-size` experiment is successful then I can have a think about how to do that.

> As you can see there it should return a header called "Retry-After" which should be used to avoid those rate limit warnings.

You are right, rclone doesn't look at Retry-After yet.

Here is what the docs say

> Rate limited responses include a Retry-After header that provides the duration, in seconds, your app should wait before retrying the request to avoid a subsequent rate limit response. Note that this duration is an upper cap on how long an app would wait to guarantee the next request will not be rate limited. A request made sooner may not be rate limited. If you’re finding that waiting the duration provided by the Retry-After header is causing a bottleneck in your app’s execution, you may want to implement your own back-off mechanism wherein you start by waiting a fraction of the Retry-After value before retrying and wait a little longer after each consecutive request that is being rate limited.

Which is in fact exactly what rclone does - it uses an exponential backoff.  So I think seeing `too_many_write_operations` errors is normal.  If rclone retries the same file many times with the same error then rclone's algorithms will need a tweak - have you seen that?

**Comment by SanderM2** [comment]
In order to speed things up. I'm not sure if it's possible at all: but maybe we can already start uploading the next chunk while waiting at confirmation of the previous chunk?
Reading the dropbox API docs I don't see a problem with that and maybe we can have it going a lot faster this way? Not sure... Love to hear your thoughts.

**Comment by ncw** [comment]
> I have just retried with --buffer-size 128M but honestly, it doesn't make any difference. I even tried putting a 8Gb file in ram drive and the problem persists, so it's not a disk-read issue I'm pretty sure...

OK thanks for testing that.

> I also tried with --dropbox-chunk-size 25m and this made the burst/stall network pattern repeat more often so maybe you're right that it's dropbox needing more time to process the request.

We could test this out possibly...  If you run rclone with `-vv --dump-headers` it will show the http transactions as they come and go.  What would be interesting to see is the time between rclone finishing one transaction and starting the next and whether the network bursti finishes before rclone gets the response.

> But then I wonder.. why would it be this slow using the API while their own application can do it a lot faster? Isn't their own application using their own API ? :-)

I'm pretty sure in the past that dropbox's own app didn't use the public API since it could set client_modified, but you couldn't do that in the API.  I don't know what the status is now though.

I saw this [blog post about streaming sync](https://blogs.dropbox.com/dropbox/2014/07/introducing-streaming-sync-supercharged-sync-for-large-files/) - I wonder if that is related.

Any chance you could investigate which API it is using?

> In order to speed things up. I'm not sure if it's possible at all: but maybe we can already start uploading the next chunk while waiting at confirmation of the previous chunk?
Reading the dropbox API docs I don't see a problem with that and maybe we can have it going a lot faster this way? Not sure... Love to hear your thoughts.

That would be the idea solution.  However there are two things that give me pause, one is the name of the method [Append](https://www.dropbox.com/developers/documentation/http/documentation#files-upload_session-append_v2) and the other is this error 

> incorrect_offset UploadSessionOffsetError The specified offset was incorrect. See the value for the correct offset. This error may occur when a previous request was received and processed successfully but the client did not receive the response, e.g. due to a network error.

that said it might be worth an experiment...

**Comment by ncw** [comment]
I asked a quetion in the developer forum about parallel uploading [here](https://www.dropboxforum.com/t5/API-support/Using-upload-session-append-v2-is-is-possible-to-upload-chunks/m-p/225845#M12296)

**Comment by SanderM2** [comment]
I just asked a dropbox tech support guy about this and his reply was:

"Unfortunately, no, you can't proceed on to subsequent chunks until the current one has completed.""

**Comment by SanderM2** [comment]
I also asked the tech guy if the original dropbox client is using the same API or not and he said it uses a proprietary protocol so we cannot use the same method in our own applications.

**Comment by ncw** [comment]
:-( that is a shame.  However rclone can upload lots of stuff at once with `--transfers` which ups the parallelism.

**Comment by SanderM2** [comment]
--transfers defaults to 4 if I'm not mistaken but I never tried increasing it for my dropbox account because I guess it'll cause more errors like these: "upload failed: too_many_write_operations/. - low level retry 1/10"

**Comment by SanderM2** [comment]
After talking to dropbox tech guys they confirmed now that the problem is in the API and not in rclone. It's their servers needing more time to confirm file uploads and nothing can be done about this right now. They added their tech guys are working on it to improve performance, but we all know it will probably not change at all...

So I'm forced to try different cloud storage providers besides dropbox.
I just tried OneDrive with rclone and guess what : It's a lot faster than dropbox! I instantly goes about 20mbyte/sec average. Dropbox never reached this speed at all...

So I thought, let's switch to onedrive but I just read that rclone doesn't really support onedrive for business ....

**Comment by ncw** [comment]
Ok thanks for the confirmation. They said the same thing in the forum too.

There is a ticket for onedrive for business. It should be quite simple buy whenever I've tried I get bogged down in Microsoft terminology and needing developer subscriptions which I don't have, so help needed!  The API should just work it is registering the app etc which is the problem.

**Comment by ncw** [comment]
I'm going to close this now as we've finished the discussion.

**Comment by nh2** [comment]
> upload failed: too_many_write_operations/

For others who found this issue, this improvement looks very relevant: https://github.com/rclone/rclone/issues/5156#issue-838633716
