### ISSUE TITLE
Can't add dropbox account with beta version -> easy fix

### ISSUE THREAD

**Issue by SanderM2** [ncw/rclone#1484]
# ./rclone authorize "dropbox"
If your browser doesn't open automatically go to the following link: http://127.0.0.1:53682/auth
Log in and authorize rclone for access
Waiting for code...

When you point your browser to that URL you'll be redirected to a URL like this:

https://www.dropbox.com/1/oauth2/authorize?access_type=offline&client_id=xxxxxxxx&redirect_uri=http%3A%2F%2Flocalhost%3A53682%2F&response_type=code&state=xxxxxxxxx

Dropbox complains about an unknown parameter "access_type" and won't continue.
When removing "access_type=offline" from the URL it works and I can click accept.

So the "access_type=offline" parameter has to be removed it seems...

**Comment by ncw** [comment]
Thanks for figuring out the problem - saved me lots of hair pulling!

This was introduced by c59a292719ad574357f96f8e19b65b02a6e135f1

I've fixed this in this beta

https://beta.rclone.org/v1.36-174-g1e88f070/ (uploaded in 15-30 mins)
