### ISSUE TITLE
Google Drive Trash Support (Cleanup/Empty)

### ISSUE THREAD

**Issue by timwhite** [ncw/rclone#1489]
It would be great to support Google Drive "Cleanup", or at least the ability to empty the Trash. Both V2 and V3 of the API support it https://developers.google.com/drive/v3/reference/files/emptyTrash

> What is your rclone version (eg output from `rclone -V`)

rclone v1.36-156-gca76b3fb-team-driveβ

> Which OS you are using and how many bits (eg Windows 7, 64 bit)

Linux 64bit

> Which cloud storage system are you using? (eg Google Drive)

Google Drive (Team Drive)

```
./rclone cleanup -n Drive:
2017/06/16 18:39:21 ERROR : Attempt 1/3 failed with 0 errors and: Google drive root '' doesn't support cleanup
2017/06/16 18:39:21 ERROR : Attempt 2/3 failed with 0 errors and: Google drive root '' doesn't support cleanup
2017/06/16 18:39:21 ERROR : Attempt 3/3 failed with 0 errors and: Google drive root '' doesn't support cleanup
2017/06/16 18:39:21 Failed to cleanup: Google drive root '' doesn't support cleanup
```

**Comment by ncw** [comment]
There is an issue about this already at #575 - can you add your useful links to that issue please?

**Comment by timwhite** [comment]
@ncw Done. My searching for an existing issue failed because I refer to it as "Google Drive", yet it appears lots of issues just call it "drive". Thanks
