### ISSUE TITLE
ACD: Investigate POST/GET gzip compression

### ISSUE THREAD

**Issue by klauspost** [ncw/rclone#149]
With some minor changes to the `go-acd` package, it should be fairly easy to add gzip compression to uploads. However, gzip POST is rarely supported.

The overhead for uncompressible content is extremely small ( < 0.1 %), and the gains are of course the same as a gzip compression.

So for me, whether to implement it is a given.

However, should we make the compression level selectable? IE add a `--compression=n` parameter?

My default would be compression level 1, which in a worst case scenario has a throughput of ~50Mbyte/s per core when using my [compression library](https://github.com/klauspost/compress) on a mediocre laptop (Intel i5 2540M). I think that should be acceptable for everybody.

Edit: If we are using the default transport, it will be automatically handled on GET. I will check if that happens.

ACD is at the moment only spewing out `500 Internal Server Error`. When they have fixed it, I will do some tests.

**Comment by klauspost** [comment]
Nope. No go. Seems like there is no way of enabling comrpession neither for up- nor downloads :(

Maybe some day I will ask in the forum. Closing for now, though...

**Comment by ncw** [comment]
That is frustrating :-( 

Thanks for investigating
