### ISSUE TITLE
Create Service Account - GDrive

### ISSUE THREAD

**Issue by dav1303** [ncw/rclone#1491]
Hi

When migrating to Gdrive actually we create you own credentials and you need to authenticate the first time to create and allow the connection. 

Can we imagine using a service account to allow to migrate all users on Gsuite domain without having to launch authentication on each account where we want to upload files.

The only step to had after with this method is to allow the client id with the drive api (genererated in the Google Cloud Project) on the admin console

Regards

**Comment by ncw** [comment]
This was recently done for google cloud storage in 022ab4516db76b8b57b60e9e81eeb6be5c491184

@mwitkow you did the changes for GCS service accounts - do you think the same methodology would work for Google drive?

**Comment by dav1303** [comment]
@mwitkow whet do you think about that ?

**Comment by gustavorochakv** [comment]
Unless there's some workaround I'm not familiar with, there would be a few additional steps involved compared to Google Storage, related to enabling domain wide delegation.

It essentially involves ticking a box on the account permissions on the Cloud console and allowing the required API scopes on the Admin console for the G Suite Domain.
I'm  not aware of any way of doing this programmatically.

Official docs on how to enable domain wide delegation:
https://developers.google.com/identity/protocols/OAuth2ServiceAccount

List of scopes required:
https://developers.google.com/drive/v2/web/about-auth

PS: the Google Drive API has a big red warning stating that this should only be used for performing delegation where the effective identity is that of an individual user in a domain, otherwise there could be severe performance issues. If that's the case, then the code would differ a bit from Cloud Storage, since rclone would need to authenticate impersonating a user.

For the use case described on this issue (domain migration), that means impersonating one user on each domain (user on source domain => user on destination domain), leading to either additional command line arguments or config files (so that the domain migration can be scripted).

**Comment by dav1303** [comment]
Hi

I just want to be able to migrate only from one account on the users
account using wide delegation but on the same domain, without having to
authenticate each time

Regards

Le 3 juil. 2017 4:06 PM, "gustavorochakv" <notifications@github.com> a
écrit :

**Comment by dav1303** [comment]
Hi

@ncw this feature can be very interesting

What do you think about that ?

Regards

**Comment by JohNan** [comment]
+1 for being able to use a Service Account for Gdrive

**Comment by ryancastle** [comment]
This is sort of implemented in the latest build, but I'm not sure it will be useful until it can do user masquerading.

**Comment by dav1303** [comment]
In fact actually I was not able to migrate data to another drive account or I don't know how to do it

**Comment by ncw** [comment]
@dav1303 
Here are the [instructions for using a service account](https://github.com/ncw/rclone/blob/master/docs/content/drive.md#service-account-support) with google drive. This will only work with [the latest beta](https://beta.rclone.org).  Are those the instructions you followed?

@ryancastle can you link to some docs about user masquerading?  I'm not familiar with that.  What support would rclone need?

**Comment by dav1303** [comment]
Hi Nick

Yes I follow the instructions but if I setup my service account with my
admin account and I want to push my datas to another drive account trough
the SA how can I do ?

Thanks

Le 21 déc. 2017 15:56, "Nick Craig-Wood" <notifications@github.com> a
écrit :

**Comment by ryancastle** [comment]
Not sure about go... There's an example of setting a subject on a transport here.

https://github.com/golang/oauth2/blob/0448841f0cbe9d174c6c1cedd177f583337b8e2c/google/example_test.go#L94-L124

Once you create a service account and set domain-wide delegation, that account can act as any user (there may be some restrictions).

We are using it for a Google Drive app using the JS API that's fully in-browser. But we delegate that delete actions to a server-based controller (PHP). It checks if the user is an "editor" and uses the service account to masquerade as the owner in order to delete the file.

In PHP it's basically just this...

        $client = new \Google_Client();
        $client->setAuthConfig($this->credentials); // JSON file for service account
        $client->setSubject($ownerEmail);
        $drive = new \Google_Service_Drive($client);
        $drive->files->delete($fileId);

We've also developed a script that takes a Google Drive audit history log and runs "undo" on it. That also uses a service account to masquerade as the user that performed the original action.

**Comment by ryancastle** [comment]
rclone seems to intrinsically operate on a single user's "My Drive". But files within that Drive can by owned by other users. A "service account" doesn't really have a useable "My Drive", but it can help deal with some funny cases.

So I'd imagine something like this in the rclone config instead of "token".

[drive]
service_account = client.json
owner = user1@domain.com

**Comment by dav1303** [comment]
Hi

I Think this information could be différent each time ?

Why we don't pass this information on the command ?

Rclone copy owner:david@gmail.com

Regards

**Comment by ncw** [comment]
@dav1303 
> Yes I follow the instructions but if I setup my service account with my
admin account and I want to push my datas to another drive account trough
the SA how can I do ?

I'm not 100% sure!

@cooijmanstim - can you explain how to use a service account to access existing drives?

**Comment by dav1303** [comment]
@ncw 

Normally adding entries on the Gsuite Admin Console and using SA with domain wild Delegation give us the opportunity to migrate datas on other accounts whitout needing anything else than the ownership of the Datas

As suggested by @ryancastle I think we need to add on the command line the _owner_ of the datas that we migrate an optionnaly adding our admin account as Editor. 

In that case the folders & files appears on the "My Drive" of the other owner account.

Regards



Regards

**Comment by cooijmanstim** [comment]
Sorry, I can't be of much help here. The service account's private drive served my purposes so I haven't looked into it further.

**Comment by dav1303** [comment]
Hi

An old video explaining how it works
https://www.youtube.com/watch?v=iK14bfd6qhs

Sorry I'm not advanced on dev part to help more

**Comment by ryancastle** [comment]
@dav1303 Yes. A command line option is probably nice. I was suggesting a config file option, because it would make Google Drive storage operate more like other cloud services, without really having to change the paradigm at all.

**Comment by dav1303** [comment]
That would be fine with the config file

**Comment by ncw** [comment]
I'd prefer a config file option too...

I'm going to have to say I need help with this - I skimmed the docs and there are lot of terms I don't understand, so calling anyone who can help!

**Comment by dav1303** [comment]
Hi

I've done some tests using the service account unfortunatly thé files are
migrated but not visible on the drive Web UI.

When I launch rclone ls I can see them on remote but not on drive.

Regards

Le 28 déc. 2017 14:46, "Nick Craig-Wood" <notifications@github.com> a
écrit :

**Comment by JohNan** [comment]
I tried this none of the files that was uploaded was visible in the Web YI with my regular account. I think we are missing the equivalent to `.setServuceAccountUser()` found in the Java SDK. The uploaded files need to belong to a normal user. 

```
GoogleCredential credential = new GoogleCredential.Builder()
    .setTransport(httpTransport)
    .setJsonFactory(JSON_FACTORY)
    .setServiceAccountId(emailAddress)
    .setServiceAccountPrivateKeyFromP12File(new File("MyProject.p12"))
    .setServiceAccountScopes(Collections.singleton(SQLAdminScopes.SQLSERVICE_ADMIN))
    .setServiceAccountUser("user@example.com")
    .build();
```

**Comment by ryancastle** [comment]
I think setting the subject on a JWT will achieve a similar thing.

https://godoc.org/golang.org/x/oauth2/jwt

**Comment by JohNan** [comment]
That sounds like a equivalent option yes. Any chance we can be able to set it during config?

**Comment by ncw** [comment]
@ryancastle what format does that string take?

@JohNan wrote:
> That sounds like a equivalent option yes. Any chance we can be able to set it during config?

Sounds plausible!

I tried wedging in `conf.Subject = "me@email.com"` [here](https://github.com/ncw/rclone/blob/master/backend/drive/drive.go#L455) but that gives me `Client is unauthorized to retrieve access tokens using this method.`

I made a beta with a new flag `--drive-impersonate` which sets that.  It didn't seem to work for me but tell me what you think!

https://pub.rclone.org/v1.39-103-ga4e93129-drive-service-account-1491%CE%B2/

```patch
diff --git a/backend/drive/drive.go b/backend/drive/drive.go
index f2549fd5..eca3b0c9 100644
--- a/backend/drive/drive.go
+++ b/backend/drive/drive.go
@@ -62,6 +62,7 @@ var (
 	driveTrashedOnly   = flags.BoolP("drive-trashed-only", "", false, "Only show files that are in the trash")
 	driveExtensions    = flags.StringP("drive-formats", "", defaultExtensions, "Comma separated list of preferred formats for downloading Google docs.")
 	driveListChunk     = flags.Int64P("drive-list-chunk", "", 1000, "Size of listing chunk 100-1000. 0 to disable.")
+	driveImpersonate   = flags.StringP("drive-impersonate", "", "", "Impersonate this user when using a service account.")
 	// chunkSize is the size of the chunks created during a resumable upload and should be a power of two.
 	// 1<<18 is the minimum size supported by the Google uploader, and there is no maximum.
 	chunkSize         = fs.SizeSuffix(8 * 1024 * 1024)
@@ -454,6 +455,9 @@ func getServiceAccountClient(keyJsonfilePath string) (*http.Client, error) {
 	if err != nil {
 		return nil, errors.Wrap(err, "error processing credentials")
 	}
+	if *driveImpersonate != "" {
+		conf.Subject = *driveImpersonate
+	}
 	ctxWithSpecialClient := oauthutil.Context(fshttp.NewClient(fs.Config))
 	return oauth2.NewClient(ctxWithSpecialClient, conf.TokenSource(ctxWithSpecialClient)), nil
 }
```

**Comment by JohNan** [comment]
installed the latest beta but the flag is not available
`2018/02/01 12:07:25 Fatal error: unknown flag: --drive-impersonate`

```
rclone --version
rclone v1.39-103-g3c7a7556β
- os/arch: linux/amd64
- go version: go1.9.3
```

**Comment by JohNan** [comment]
Good news @ncw ! It works perfectly! The file is uploaded with the service account but the owner is set to the user that I provided with the new flag! 

Thanks alot!

**Comment by johnavp1989** [comment]
@ncw Working great thanks! It looks like it doesn't work for listing files and directories in a specified user's account though. This is not a huge deal for me personally but might be nice. Not sure if that's outside the scope of the intended purpose service accounts.

**Comment by ncw** [comment]
@JohNan @johnavp1989 thanks for testing and glad it is working!

I can't get that flag to do anything - maybe that is because I don't have the right kind of drive account...

If you'd like me to merge it, then I need to write some docs, but I don't really know what to day about it!

Something like

### --drive-impersonate USER

When using a service account with drive, you can impersonate a user using this flag.  This means that you can upload files owned by the user you pass in.

This flag does not allow you to list files as the user.

XXX what format is USER?

Where do the files end up in the users drive?

Why would you use this feature?

Suggestions for more helpful text here welcome!

**Comment by mattkaye** [comment]
@ncw 
I'm also getting that same error that @JohNan was getting, but I'm _not_ using **g3c7a7556β**:
`Fatal error: unknown flag: --drive-impersonate`

For reference, this is the package I'm using:
https://pub.rclone.org/v1.39-103-ga4e93129-drive-service-account-1491%CE%B2/rclone-v1.39-103-ga4e93129-drive-service-account-1491%CE%B2-linux-amd64.zip

And I'm running this command:
`rclone ls --drive-impersonate user@domain.com drive-name:someones-drive`

Any advice? Since there's no documentation, is this the correct way to pass the flag? Use the users email address I suppose? Thank you!

**Comment by JohNan** [comment]
@ncw Im able to list files using the flag, so I wouldnt say it's not possible. Maybe it has to do what privileges you gave to the service account and what scope you set when configuring the drive in rclone?

@mattkaye here's the version Im using.
```
rclone --version
rclone v1.39-103-ga4e93129-drive-service-account-1491β
- os/arch: linux/amd64
```

as for the docs, have a look here: https://developers.google.com/identity/protocols/OAuth2ServiceAccount#delegatingauthority

What we do is essentially taking advantage of what they call "Delegating domain-wide authority to the service account".


> Authorizing a service account to access data on behalf of users in a domain is sometimes referred to as "delegating domain-wide authority" to a service account.
> [...]
> Your application now has the authority to make API calls as users in your domain (to "impersonate" users). When you prepare to make authorized API calls, you specify the user to impersonate.

The files end up on the drive as if it was the impersonated user who uploaded them. That user is the owner of the files. The format should be a email address.

**Comment by mattkaye** [comment]
@JohNan 
I'm using the same version you are, but I get that fatal error.
You're sure we're using the same?
https://pub.rclone.org/v1.39-103-ga4e93129-drive-service-account-1491%CE%B2/rclone-v1.39-103-ga4e93129-drive-service-account-1491%CE%B2-linux-amd64.zip

On the Google side of things, I've already delegated my service account to be able to use drive

Is this how you're calling the command?
`rclone ls --drive-impersonate user@domain.com drive-name:someones-drive`

**Comment by JohNan** [comment]
@mattkaye yes, that is the command line I used. Try `rclone - - version ` to make sure that you are using that version.

**Comment by dav1303** [comment]
Hi
I have tested in version 1.39-103 and with this command
rclone ls --drive-impersonate user@domain.com drive-name:

2018/02/02 23:33:30 Failed to create file system for "XXX:": couldn't get Drive exportFormats: Get https://www.googleapis.com/drive/v3/about?alt=json&fields=exportFormats: oauth2: cannot fetch token: 401 Unauthorized
Response: {
  "error" : "unauthorized_client",
  "error_description" : "Client is unauthorized to retrieve access tokens using this method."
}

**Comment by dav1303** [comment]
Hi

Sorry for last message, after having added the clientID in the Admin Gsuite Console / Security / Client API Access with this scope : https://www.googleapis.com/auth/drive

Now it seems working fine with my account, butI'll need to do a test with another account

Thanks

**Comment by dav1303** [comment]
Hi

It works fine for me, good job !

Regards

**Comment by mattkaye** [comment]
I did get this working finally. Started transferring data last night and it's still going this morning. 136GB pushed to drive so far with no errors, so this software is working very well. I have hundreds more of GB to go.

Please do add this feature to a stable release as soon as possible. It's very important. Certainly needs good documentation. It took a fair amount of trial and error to get the Google configuration correct. Thanks for the awesome work!

**Comment by mattkaye** [comment]
I followed the directions from Google, but there's one step that I just happened to stumble upon to make it work. You not only have to create the service account ,BUT you also need to create a client ID from that service account. They call it an OAuth 2.0 client ID. Only then was I able to impersonate a drive user. The docs don't make that entirely clear. Hope this helps someone out.

**Comment by johnavp1989** [comment]
@JohNan You're right about the file and directory listing. It does work with the flag. I thought it was still listing the files in the service account but after a second look it does appear to be working.

**Comment by alexanderkjeldaas** [comment]
This might work with GSuite, but how about a folder shared by one drive user to another?

I can share a folder with the email of a service user, and I *think* that means the service user somehow should be able to access it.

However, that doesn't mean the service user can impersonate the user!

The shared drive also doesn't show up in `rclone ls myremote:`

**Comment by alexanderkjeldaas** [comment]
Would it be possible to list files starting with a folder id for service users to capture this use-case?

**Comment by alexanderkjeldaas** [comment]
hmm.. it looks like `rclone ls --drive-shared-with-me myremote:` does the correct thing and only lists what is shared, while `rclone ls myremote:` does not show any shared files.

**Comment by ncw** [comment]
@mattkaye wrote
> Please do add this feature to a stable release as soon as possible. It's very important. Certainly needs good documentation. It took a fair amount of trial and error to get the Google configuration correct. Thanks for the awesome work!

That seems to be the consensus that it does work which is good!

As for good documentation - I'd really like someone to contribute that as I don't have much of a clue as to what is going on.  Perhaps this should be a section in [the drive docs](https://rclone.org/drive/) say "Using service accounts".

Any takers?  If anyone would like to drop some words in this thread then I'll put them in the docs.

I've merged the flag into trunk - it will be available here

https://beta.rclone.org/v1.39-127-g8a25ca78/ (uploaded in 15-30 mins)

And in [the latest beta](https://beta.rclone.org) from now on.

**Comment by StefanLindblom** [comment]
Hi!
Just wanted to drop in here and say thank you for implementing the `--drive-impersonate` option! It took me quite some googling to get all the API's, service account, allowing API client access etc to work... and then I stumbled upon this feature being added to the beta release.
Seems to work fine so far!

**Comment by ncw** [comment]
@StefanLindblom great - thanks!

I'd love someone who really understands this stuff to [update the docs](https://github.com/ncw/rclone/blob/master/docs/content/drive.md#service-account-support) as I only have a vague clue as to what it is supposed to do!

**Comment by ncw** [comment]
I'm going to close this issue as I think it is done now!  Thanks all for your help.

**Comment by StefanLindblom** [comment]
@ncw You mean something like this? :)
https://github.com/ncw/rclone/pull/2148

**Comment by ncw** [comment]
@StefanLindblom perfect :-)

**Comment by pjhfggij** [comment]
I found StefanLindblom's instructions immensely helpful when setting up "impersonating service account" for the first time
