### ISSUE TITLE
just show stats like old version

### ISSUE THREAD

**Issue by jxer** [ncw/rclone#1496]
v1.36

appears -stats doesn't work without the -v flag,

how do i only get the -stats output like in the old version? i don't want a per file log

**Comment by calisro** [comment]
I think you can do this on Linux:

Rclone copy /x/  y:    -v --stats 5m  2>&1 | egrep "^E|^T|^C"

I know it's not exactly what you want but it would work......

**Comment by jxer** [comment]
rclone copy -v --stats 5s /home/jxer/files Gdrive:/media |& grep -v 'INFO'"

this works but i think the stats flag should be allowed to be set without the above

**Comment by jxer** [comment]
@calisro i guess slightly different syntax but it works both ways i guess

**Comment by calisro** [comment]
Yes but I do agree with you. .

**Comment by ncw** [comment]
I'm going to fix this in #1180 so I'm going to close this as a duplicate.  Please subscribe to that bug for updates!

Thanks
