### ISSUE TITLE
Cannot create folders in B2

### ISSUE THREAD

**Issue by mrdana** [ncw/rclone#1497]
I'm unsure if this intended behaviour or not, but I hope it isn't. I am unable to use rclone to create a folder within a B2 bucket. This does not work regardless if the remote is encrypted or normal.

> What is your rclone version (eg output from `rclone -V`)

1.36

> Which OS you are using and how many bits (eg Windows 7, 64 bit)

Mac OS 10.10.5, 64 bit.

> Which cloud storage system are you using? (eg Google Drive)

B2

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

rclone mkdir remote:BucketName/FolderName

> A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

2017/06/21 19:06:45 DEBUG : rclone: Version "v1.36" starting with parameters ["rclone" "mkdir" "[remote]:[bucketName]/testfolder" "-vv"]
2017/06/21 19:06:46 INFO  : B2 bucket [bucketName] path testfolder/: Modify window is 1ms
2017/06/21 19:06:46 DEBUG : Go routines at exit 4
2017/06/21 19:06:46 DEBUG : rclone: Version "v1.36" finishing with parameters ["rclone" "mkdir" "[remote]:[bucketName]/testfolder" "-vv"]

After doing this, this is the output from "rclone lsd remote:BucketName".

2017/06/21 19:07:41 DEBUG : rclone: Version "v1.36" starting with parameters ["rclone" "lsd" "[remote]:[bucketName]" "-vv"]
2017/06/21 19:07:42 INFO  : B2 bucket [bucketName]: Modify window is 1ms
          -1 0001-01-01 00:00:00        -1 <other folder present, but not 'testfolder'>
2017/06/21 19:07:43 DEBUG : Go routines at exit 6
2017/06/21 19:07:43 DEBUG : rclone: Version "v1.36" finishing with parameters ["rclone" "lsd" "[remote]:[bucketName]" "-vv"]

Thanks!

**Comment by ncw** [comment]
B2 (and S3, swift, GCS) don't have the concept of folders - they are object stores only. So mkdir does nothing except create the bucket if necessary.

As soon as you copy files in, folders will appear. This effectively means you can't have empty folders on B2.

**Comment by mrdana** [comment]
Ah I see, this makes sense. I see that I was able to run `rclone sync MyFolder [remote]:[bucketName]/MyFolder` and even though "MyFolder" did not exist yet on B2, it was created as part of the upload process.

Thank you!
