### ISSUE TITLE
Filesystem lock on hubic mount with complex filename.

### ISSUE THREAD

**Issue by ulmeck** [ncw/rclone#1498]
With both the latest release and beta.

When using wget to download the following URL:

wget https://dnd.rem.uz/Advanced%20D%26D%20%28unsorted%29/AD%26D%20Accessory-FR-Volo%E2%80%99s%20Guide%20to%20All%20Things.pdf

Directly to a rclone FUSE mount to hubic, the FUSE fileshare locks, and requires a reboot to kill the involved processes (wget, rclone, etc).

This is on a current Debian 8 VM.

Downloading directly to the extfs4 filesystem works fine.

Logs:

2017/06/18 22:08:16 DEBUG : Documents/DND/dnd.rem.uz/Advanced D&D (unsorted)/AD&D Accessory-FR-Volo's Guide to Cormyr.pdf: Dir.Lookup
2017/06/18 22:08:16 DEBUG : Documents/DND/dnd.rem.uz/Advanced D&D (unsorted)/AD&D Accessory-FR-Volo's Guide to Cormyr.pdf: Dir.Lookup OK
2017/06/18 22:08:16 DEBUG : Documents/DND/dnd.rem.uz/Advanced D&D (unsorted)/AD&D Accessory-FR-Volo's Guide to Cormyr.pdf: File.Attr valid=1m0s ino=0 size=7607882 mode=-rw-r--r--
2017/06/18 22:08:16 DEBUG : Documents/DND/dnd.rem.uz/Advanced D&D (unsorted)/AD&D Accessory-FR-Volo�%80%99s Guide to All Things.pdf: Dir.Lookup
2017/06/18 22:08:16 DEBUG : Documents/DND/dnd.rem.uz/Advanced D&D (unsorted)/AD&D Accessory-FR-Volo�%80%99s Guide to All Things.pdf: Dir.Lookup
2017/06/18 22:08:16 DEBUG : Documents/DND/dnd.rem.uz/Advanced D&D (unsorted)/AD&D Accessory-FR-Volo�%80%99s Guide to All Things.pdf: Dir.Lookup
2017/06/18 22:08:16 DEBUG : Documents/DND/dnd.rem.uz/Advanced D&D (unsorted)/AD&D Accessory-FR-Volo�%80%99s Guide to All Things.pdf: Dir.Lookup
2017/06/18 22:08:17 DEBUG : Documents/DND/dnd.rem.uz/Advanced D&D (unsorted)/AD&D Accessory-FR-Volo�%80%99s Guide to All Things.pdf: Dir.Lookup
2017/06/18 22:08:17 DEBUG : Documents/DND/dnd.rem.uz/Advanced D&D (unsorted)/AD&D Accessory-FR-Volo�%80%99s Guide to All Things.pdf: Dir.Lookup
2017/06/18 22:08:17 DEBUG : Documents/DND/dnd.rem.uz/Advanced D&D (unsorted)/AD&D Accessory-FR-Volo�%80%99s Guide to All Things.pdf: Dir.Lookup
2017/06/18 22:08:17 DEBUG : Documents/DND/dnd.rem.uz/Advanced D&D (unsorted)/AD&D Accessory-FR-Volo�%80%99s Guide to All Things.pdf: Dir.Create
2017/06/18 22:08:17 DEBUG : Documents/DND/dnd.rem.uz/Advanced D&D (unsorted)/AD&D Accessory-FR-Volo�%80%99s Guide to All Things.pdf: Dir.Create OK
2017/06/18 22:08:17 DEBUG : File.Attr valid=1m0s ino=0 size=0 mode=-rw-r--r--
2017/06/18 22:08:17 DEBUG : Documents/DND/dnd.rem.uz/Advanced D&D (unsorted)/AD&D Accessory-FR-Volo�%80%99s Guide to All Things.pdf: WriteFileHandle.Write len=106

(nothing after this point)

Using 'wget --restrict-file-names=nocontrol' is a valid workaround, btw.

**Comment by ncw** [comment]
I can't replicate this - it worked just fine when I tried

    rclone mount -vv hubic:default ~/mnt/tmp/

And in another terminal window

    cd ~/mnt/tmp
    wget https://dnd.rem.uz/Advanced%20D%26D%20%28unsorted%29/AD%26D%20Accessory-FR-Volo%E2%80%99s%20Guide%20to%20All%20Things.pdf

Was this just a one-off or can you replicate it at will?

**Comment by ulmeck** [comment]
I can. Let me poke at it again.

**Comment by ulmeck** [comment]
```jfulmer@localhost:~$ sudo bash
[sudo] password for jfulmer: 
root@localhost:/home/jfulmer# rclone mount -vv hubic:default /storage/temp
2017/06/23 12:08:19 DEBUG : rclone: Version "v1.36" starting with parameters ["rclone" "mount" "-vv" "hubic:default" "/storage/temp"]
2017/06/23 12:08:20 DEBUG : hubic: Saved new token in config file
2017/06/23 12:08:22 DEBUG : Hubic: Got swift credentials (expiry 2017-06-24 18:08:30 +0200 +0200 in 24h0m7.607557015s)
2017/06/23 12:08:22 INFO  : Hubic Swift container default: Modify window is 1ns
2017/06/23 12:08:22 DEBUG : Hubic Swift container default: Mounting on "/storage/temp"
2017/06/23 12:08:22 Fatal error: failed to mount FUSE fs: mountpoint does not exist: /storage/temp
root@localhost:/home/jfulmer# ls /storage
gdrive	hubic  test
root@localhost:/home/jfulmer# rclone mount -vv hubic:default /storage/test
2017/06/23 12:08:34 DEBUG : rclone: Version "v1.36" starting with parameters ["rclone" "mount" "-vv" "hubic:default" "/storage/test"]
2017/06/23 12:08:35 DEBUG : Hubic: Got swift credentials (expiry 2017-06-24 18:08:30 +0200 +0200 in 23h59m54.452635801s)
2017/06/23 12:08:35 INFO  : Hubic Swift container default: Modify window is 1ns
2017/06/23 12:08:35 DEBUG : Hubic Swift container default: Mounting on "/storage/test"
2017/06/23 12:08:35 DEBUG : Hubic Swift container default: Root()
^Z
[1]+  Stopped                 rclone mount -vv hubic:default /storage/test
root@localhost:/home/jfulmer# bg
[1]+ rclone mount -vv hubic:default /storage/test &
root@localhost:/home/jfulmer# 
root@localhost:/home/jfulmer# 
root@localhost:/home/jfulmer# cd /storage/test
2017/06/23 12:08:45 DEBUG : : Dir.Attr valid=1m0s ino=0 size=0 mode=drwxr-xr-x
root@localhost:/storage/test# ls
2017/06/23 12:08:46 DEBUG : : Dir.ReadDirAll
2017/06/23 12:08:46 DEBUG : : Reading directory
2017/06/23 12:08:46 DEBUG : : Dir.ReadDirAll OK with 1 entries
Documents
root@localhost:/storage/test# ls
2017/06/23 12:08:48 DEBUG : : Dir.ReadDirAll
2017/06/23 12:08:48 DEBUG : : Dir.ReadDirAll OK with 1 entries
Documents
root@localhost:/storage/test# cd Doc2017/06/23 12:08:50 DEBUG : : Dir.ReadDirAll
2017/06/23 12:08:50 DEBUG : : Dir.ReadDirAll OK with 1 entries
2017/06/23 12:08:50 DEBUG : : Dir.Attr valid=1m0s ino=0 size=0 mode=drwxr-xr-x
2017/06/23 12:08:50 DEBUG : Documents: Dir.Lookup
2017/06/23 12:08:50 DEBUG : Documents: Dir.Lookup OK
2017/06/23 12:08:50 DEBUG : Documents: Dir.Attr valid=1m0s ino=0 size=0 mode=drwxr-xr-x
uments/
root@localhost:/storage/test/Documents# ls
2017/06/23 12:08:51 DEBUG : Documents: Dir.ReadDirAll
2017/06/23 12:08:51 DEBUG : Documents: Reading directory
2017/06/23 12:08:52 DEBUG : Documents: Dir.ReadDirAll OK with 1 entries
DND
root@localhost:/storage/test/Documents# wget https://dnd.rem.uz/Advanced%20D%26D%20%28unsorted%29/AD%26D%20Accessory-FR-Volo%E2%80%99s%20Guide%20to%20All%20Things.pdf
2017/06/23 12:09:02 DEBUG : Documents: Dir.Attr valid=1m0s ino=0 size=0 mode=drwxr-xr-x
2017/06/23 12:09:02 DEBUG : Documents/AD&D Accessory-FR-Volo?%80%99s Guide to All Things.pdf: Dir.Lookup
2017/06/23 12:09:02 DEBUG : Documents/AD&D Accessory-FR-Volo?%80%99s Guide to All Things.pdf: Dir.Lookup
2017/06/23 12:09:02 DEBUG : Documents/AD&D Accessory-FR-Volo?%80%99s Guide to All Things.pdf: Dir.Lookup
--2017-06-23 12:09:02--  https://dnd.rem.uz/Advanced%20D%26D%20%28unsorted%29/AD%26D%20Accessory-FR-Volo%E2%80%99s%20Guide%20to%20All%20Things.pdf
Resolving dnd.rem.uz (dnd.rem.uz)... 163.172.43.158
Connecting to dnd.rem.uz (dnd.rem.uz)|163.172.43.158|:443... connected.
HTTP request sent, awaiting response... 200 OK
2017/06/23 12:09:03 DEBUG : Documents/AD&D Accessory-FR-Volo?%80%99s Guide to All Things.pdf: Dir.Lookup
Length: 8871505 (8.5M) [application/pdf]
2017/06/23 12:09:03 DEBUG : Documents/AD&D Accessory-FR-Volo?%80%99s Guide to All Things.pdf: Dir.Lookup
2017/06/23 12:09:03 DEBUG : Documents/AD&D Accessory-FR-Volo?%80%99s Guide to All Things.pdf: Dir.Create
2017/06/23 12:09:03 DEBUG : Documents/AD&D Accessory-FR-Volo?%80%99s Guide to All Things.pdf: Dir.Create OK
2017/06/23 12:09:03 DEBUG : File.Attr valid=1m0s ino=0 size=0 mode=-rw-r--r--
Saving to: ‘AD&D Accessory-FR-Volo\342%80%99s Guide to All Things.pdf’

AD&D Accessory-FR-V   0%[                      ]       0  --.-KB/s             2017/06/23 12:09:03 DEBUG : Documents/AD&D Accessory-FR-Volo?%80%99s Guide to All Things.pdf: WriteFileHandle.Write len=106

```

**Comment by ncw** [comment]
Hmm, that isn't quite what I see - I see the correct character for the quote symbol not \342%80%99.

What is your locale set to? Is it not UTF-8? I don't understand why curl is saving the file name with % signs in instead of using the UTF-8 character.

I guess I can try saving a file with the name exactly as from your log and see what happens. It has invalid UTF-8 characters in so maybe that is what hubic doesn't like.

I should be able to try this on a Debian 8 VM (I tested on Ubuntu)

**Comment by ulmeck** [comment]
Yeah, it's supposed to be UTF.

It may be something bad interacting with wget (after all, telling it
not to interpret filenames works fine), but rclone should throw an
error, not just hang, I would think. That's the only reason I bring it
up.

jfulmer@localhost:~$ locale
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=

**Comment by ncw** [comment]
I managed to recreate this by attempting to copy a file I made like this.  This is the troublesome part of your filename above. 

```
$ python
>>> f =open("/tmp/volo/Volo\342%80%99s", "w")
>>> f.write("hello world")
>>> f.close()
```

This will now give this error if you attempt to copy it into the mount rather than hang.

```
2017/06/26 11:35:03 ERROR : volo/Volo�%80%99s: WriteFileHandle.New Put failed: HTTP Error: 412: 412 Precondition Failed
2017/06/26 11:35:03 ERROR : volo/Volo�%80%99s: WriteFileHandle.Write error: io: read/write on closed pipe
```

The problem is that the filename is not a valid UTF-8 string which hubic will reject with a 412 error.

I'm not quite sure why your wget does what it does, but when I try it onUbuntu 17.04 I get a different (much more sensible!) result with a valid UTF-8 filename

```
$ wget https://dnd.rem.uz/Advanced%20D%26D%20%28unsorted%29/AD%26D%20Accessory-FR-Volo%E2%80%99s%20Guide%20to%20All%20Things.pdf
--2017-06-26 12:04:00--  https://dnd.rem.uz/Advanced%20D%26D%20%28unsorted%29/AD%26D%20Accessory-FR-Volo%E2%80%99s%20Guide%20to%20All%20Things.pdf
Resolving dnd.rem.uz (dnd.rem.uz)... 163.172.43.158
Connecting to dnd.rem.uz (dnd.rem.uz)|163.172.43.158|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 8871505 (8.5M) [application/pdf]
Saving to: ‘AD&D Accessory-FR-Volo\’s Guide to All Things.pdf’

AD&D Accessory-FR-V 100%[===================>]   8.46M  5.14MB/s    in 1.6s    

2017-06-26 12:04:02 (5.14 MB/s) - ‘AD&D Accessory-FR-Volo\’s Guide to All Things.pdf’ saved [8871505/8871505]
```

```
$ ls -l AD*
-rw-rw-r-- 1 ncw ncw 8871505 Jun 24  2016 AD&D Accessory-FR-Volo’s Guide to All Things.pdf
```

```
 dpkg -l | grep wget
ii  wget                                        1.18-2ubuntu1                               amd64        retrieves files from the web
```

Anyway, please find a fixed rclone here

https://beta.rclone.org/v1.36-211-g0b649a02/ (uploaded in 15-30 mins)

And please reopen if it doesn't fix it for you.
