### ISSUE TITLE
Suddenly slow from Amazon Cloud

### ISSUE THREAD

**Issue by dzg** [ncw/rclone#1499]
> What is your rclone version (eg output from `rclone -V`)

1.36

> Which OS you are using and how many bits (eg Windows 7, 64 bit)

Windows Server 2012 64 bit

> Which cloud storage system are you using? (eg Google Drive)

Amazon Cloud, Google Drive

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

rclone copy acd: gd:

> A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

```
DEBUG : pacer: Rate limited, sleeping for 19.527008449s (6 consecutive low level retries)
DEBUG : pacer: low level retry 9/10 (error HTTP code 400: "400 Bad Request": response body: "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>InvalidArgument</Code><Message>Only one auth mechanism allowed; only the X-Amz-Algorithm query parameter, Signature query string parameter or the Authorization header should be specified</Message><ArgumentName>Authorization</ArgumentName><ArgumentValue>Bearer Atza|______</ArgumentValue><RequestId>____</RequestId><HostId>____</HostId></Error>")

```

I had success with the method [here](https://np.reddit.com/r/DataHoarder/comments/6clkdn/xpost_how_to_get_rclone_working_after_the_acd_ban/?st=j49vabxr&sh=d90f50e7) using Cloudberry and Fiddler.

Transfer was flying at 2 Gbps ... for about an hour ... then I stopped it to tweak a parameter.

Since I started again, it's going very slow. I see many of these errors.

I went back into Cloudberry and reconnected, got a new token, etc.

But still slow.

Am I screwed?

**Comment by ncw** [comment]
I suggest you checkout [this thread in the forum](https://forum.rclone.org/t/proxy-for-amazon-cloud-drive) for a better auth way.

I'm going to close this since it isn't really a bug report - if you need more help please post in the forum - thanks!

**Comment by dzg** [comment]
OK, thanks ... though I thought that other method wasn't working as reported a few hours ago...
