### ISSUE TITLE
Can't access ACD (failed to create file system)

### ISSUE THREAD

**Issue by ceptonit** [ncw/rclone#150]
Ubuntu 14.04 using rclone-v1.20-linux-amd64.zip

After configuring rclone, all seemed to work (I named the remote: "remote") good.
30min later, impossible to access my ACD. Any command returns a:

"Failed to create file system for "remote:": Failed to get endpoints: HTTP code 503: "503 Service Unavailable", reponse body: <html><body><b>Http/1.1 Service Unavailable</b></body> </html>"

Not sure what's wrong.

**Comment by ceptonit** [comment]
Nevermind, it seems ACD is actually having issues with one of their data centers.
So the service is actually down.

**Comment by ncw** [comment]
@ceptonit Thanks for the update.  Other people have also told me they have been having trouble with ACD being down too.
