### ISSUE TITLE
rclone 'forgetting' custom Google Drive API keys

### ISSUE THREAD

**Issue by dzg** [ncw/rclone#1503]
I followed the instructions for [Making your own client ID](https://rclone.org/drive/#making-your-own-client-id), which worked well for about an hour.

But then I started getting errors and noticed that somehow both the client id and secret got erased from my config, during the transfer.

This happened twice, with 2 fresh keysets.

**Comment by ncw** [comment]
Which version of rclone were you using? Can you try again with the latest beta please?

Were you maybe running two versions of rclone at once?
