### ISSUE TITLE
Warn about duplicate files when syncing

### ISSUE THREAD

**Issue by toomuchio** [ncw/rclone#1506]
As you can see file4 is duplicated same filesize and name, is this some file revision issue?
When I try and sync this drive to another what should be identical drive sync constantly tries to upload this duplicate file and fails, no matter how many times I run it, it copy new's this file over and over again.

Running the latest beta.

./rclone ls drive_database_backup1:somefolder/someotherfolder/someotherotherfolder
1311587023 file1
1517502971 file2
1396104784 file3
1499103085 file4
1499103085 file4
1338074238 file5
1194734563 file6
1345642954 file7
1381247260 file8
1269234928 file9
1521290370 file10
1334744546 file11
1179343849 file12

**Comment by toomuchio** [comment]
Looks like the file is completely identical, except for the id when using --dump-bodies. So rclone can't handle situations like that I guess. Not even sure how to get rid of these duplicates now, I guess the web browser client.

**Comment by toomuchio** [comment]
Ah I see, I can use dedupe to correct this. I'd still class this as a bug since sync/copy will never be satisfied in this situation and constantly try and copy the same file every execution.

**Comment by ncw** [comment]
Drive duplicating files is an old problem - see #28.  I'm pretty sure there is a bug in drive itself as rclone is not the only app to have this problem.  Even google photos on android duplicates pictures!

Your suggestion of warning when it encounters a duplicate is a good one, and one that is now possible with the new style sync routines, so I shall use this amend this issue to implement that.

**Comment by ncw** [comment]
PS the old sync method did used to warn about duplicate files, so this functionality has gone missing.

**Comment by toomuchio** [comment]
It was odd indeed, I wasn't sure how those duplicates even came about, cleaned them out with redupe and sync was fine. Would be good indeed to prevent duplicates with sync.

I ran sync a few times before I figured out what was going on, I had renamed and moved some files around so I thought there was some other conflict, quite odd indeed.

**Comment by ncw** [comment]
NB this is also causing a problem [being discussed on the forum](https://forum.rclone.org/t/rclone-sync-bug-files-are-being-erroneously-erased-moved-on-the-remote-causing-subsequent-rclone-syncs-to-copy-them-over-and-over-again-was-repeated-rclone-sync-commands-from-a-read-only-local-fs-copying-the-same-files-over-and-over-again/2252)

**Comment by ncw** [comment]
This will warn about duplicated files

https://beta.rclone.org/v1.36-231-g575e779b/ (uploaded in 15-30 mins)
