### ISSUE TITLE
Failure to follow a symlink should not result in transfer failure.

### ISSUE THREAD

**Issue by darren12345** [ncw/rclone#1509]
> What is your rclone version (eg output from `rclone -V`)

Tested with beta release v1.36-222-gf3c7e1a9β

> Which OS you are using and how many bits (eg Windows 7, 64 bit)

Debian 8.8 armv5tel 32-bit

> Which cloud storage system are you using? (eg Google Drive)

Dropbox

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

 ./rclone --stats=0 -L -vv sync  /etc dropbox:Backups/settings/etc

> A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

```
2017/06/28 10:19:59 INFO  : Dropbox root 'Backups/settings/etc': Waiting for checks to finish
2017/06/28 10:19:59 INFO  : Dropbox root 'Backups/settings/etc': Waiting for transfers to finish
2017/06/28 10:19:59 ERROR : Dropbox root 'Backups/settings/etc': not deleting files as there were IO errors
2017/06/28 10:19:59 ERROR : Attempt 3/3 failed with 1 errors and: error reading source directory "systemd/system/sysinit.target.wants": stat /etc/systemd/system/sysinit.target.wants/resolvconf.service: no such file or directory
2017/06/28 10:19:59 Failed to sync: error reading source directory "systemd/system/sysinit.target.wants": stat /etc/systemd/system/sysinit.target.wants/resolvconf.service: no such file or directory
```

If using the -L switch to follow symlinks, rclone transfer should not fail in the event the symlink target is not accessible (such as missing file, on a different file system).

**Comment by 2600box** [comment]
Just my 0.02c but I think it should result in failure. If I want to follow symlinks, I want to know when that fails...

**Comment by darren12345** [comment]
By all means it should throw an error or adjust the exit code, but I don't think a transfer of 1000 files should fail totally because of one broken symlink.

**Comment by ajkis** [comment]
> By all means it should throw an error or adjust the exit code, but I don't think a transfer of 1000 files should fail totally because of one broken symlink.

I agree it should be marked as failed/error like failed transfers are and continue to upload the rest of the files.

**Comment by ncw** [comment]
Yes that is what rsync does - it carries on with a non fatal error, giving a non-zero exit code at the end.

What rclone should do is skip directories if they couldn't be read for some reason. This needs a little care as we need to make sure a skipped directory is treated differently from an empty directory, but I don't think that is too hard.
