### ISSUE TITLE
Cannot ls Camera Roll on OneDrive

### ISSUE THREAD

**Issue by latitudehopper** [ncw/rclone#1510]
I want to copy down from OneDrive the contents of the Camera Roll folder. When I list the dirs it is there but I cannot do anything with it

```
jamie@blackbox:~/Downloads$ rclone lsd "onedrive:Pictures"
          -1 2017-06-07 10:24:17      1029 1900-1999
          -1 2017-06-07 09:43:53       232 2000
          -1 2017-06-07 10:06:13       221 2001
          -1 2017-06-07 09:48:40        89 2002
          -1 2017-06-07 09:43:59       164 2003
          -1 2017-06-07 09:48:48       665 2004
          -1 2017-06-07 10:36:35      1154 2005
          -1 2017-06-09 19:39:31        11 2006
          -1 2017-06-07 12:09:42        11 2007
          -1 2017-06-09 19:46:50        11 2008
          -1 2017-06-09 19:47:38        12 2009
          -1 2017-06-09 19:46:29        12 2010
          -1 2017-06-09 19:47:16        12 2011
          -1 2017-06-07 12:53:41        12 2012
          -1 2017-06-09 19:47:08        12 2013
          -1 2017-06-09 19:44:32        12 2014
          -1 2017-06-18 11:36:35        12 2015
          -1 2017-06-18 11:35:16        12 2016
          -1 2017-06-26 19:00:24         6 2017
          -1 2017-06-15 16:46:04       173 baker
          -1 2017-06-29 14:23:33        33 Camera Roll
          -1 2017-06-09 20:32:35       285 dunbar
          -1 2015-12-23 22:53:11       249 scotland
          -1 2016-09-30 18:20:45         0 Screenshots
          -1 2017-06-09 22:14:31         8 vhs

```

> What is your rclone version (eg output from `rclone -V`)

rclone v1.36

> Which OS you are using and how many bits (eg Windows 7, 64 bit)

Ubuntu 17.04

> Which cloud storage system are you using? (eg Google Drive)

OneDrive

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

`rclone ls "onedrive:Pictures/Camera Roll"
`
> A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

```
jamie@blackbox:~/Downloads$ rclone -vv ls "onedrive:Pictures/Camera Roll"
2017/06/29 15:28:44 DEBUG : rclone: Version "v1.36" starting with parameters ["rclone" "-vv" "ls" "onedrive:Pictures/Camera Roll"]
2017/06/29 15:28:47 INFO  : One drive root 'Pictures/Camera Roll': Modify window is 1s
2017/06/29 15:28:47 Failed to ls: directory not found
```

**Comment by ncw** [comment]
I think this bug may have been fixed already - try the latest beta from https://beta.rclone.org

**Comment by latitudehopper** [comment]
You are correct. I had _tried_ with the beta but I was actually still calling on the stable release. Apologies, this is not an issue in the beta. Thanks again.

**Comment by ncw** [comment]
No problems - thanks for updating the issue.

**Comment by jowagner** [comment]
v1.37 is out and it seems to contain the fix. It copied my "Camera Roll" folder successfully. (This folder was created by my Microsoft Lumia phone.)
