### ISSUE TITLE
Wasabi

### ISSUE THREAD

**Issue by geoffjukes** [ncw/rclone#1511]
Hi,

I am trying to use rClone to sync with an S3-compatible bucket on Wasabi.

It successfuly write *small* files, but anything over a few MB, and the console is flooded with:

`Request body type has been overwritten. May cause race conditions`

I do not know if it's an issue with rClone of Wasabi (so I'll be asking them too).

Any thoughts?

Geoff

**Comment by ncw** [comment]
This message is from an old version of the AWS SDK for go, so it is definitely an rclone problem.

Can you try again with the latest beta from https://beta.rclone.org please?

**Comment by geoffjukes** [comment]
Egg on my face....

It looks like FreeNAS have bundled version v1.33-DEV, which has this problem. I was downloading v1.36 but not calling it specifically, so the 1.33 version was running.

I just tested, and the current v1.36 version is working just fine.

Time to log a bug with FreeNAS lol.

Thanks for looking into it.

Geoff

**Comment by ncw** [comment]
Glad it is solved!
