### ISSUE TITLE
OneDrive files repeatedly uploading 

### ISSUE THREAD

**Issue by latitudehopper** [ncw/rclone#1512]
Certain files are being uploaded every time I run a copy. The logs provided are incomplete but provided to show the repeat upload over two runs.

> What is your rclone version (eg output from `rclone -V`)
rclone v1.36-222-gf3c7e1a9β
> Which OS you are using and how many bits (eg Windows 7, 64 bit)
Ubuntu 17.04
> Which cloud storage system are you using? (eg Google Drive)
OneDrive
> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone copy /mnt/data0/photos onedrive:Pictures
> A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

**Upload 1**
```
2017/06/30 16:29:06 INFO  : 2015/2015-12/IMG_5837.jpg: Copied (new)
```
**Upload 2**
```
2017/06/30 16:30:29 INFO  : 2015/2015-12/IMG_5837.jpg: Copied (new)
```

**Comment by ncw** [comment]
Possibly related to #1506.

Any chance you could put a complete log with -vv somewhere?

**Comment by latitudehopper** [comment]
With pleasure. I have truncated the upload to one folder.

http://termbin.com/1xww

**Comment by latitudehopper** [comment]
As a test I have renamed the target folder and I am re-running. Early indications suggest that it is working as when I stop the process and restart, the existing files are correctly skipped.

**Comment by latitudehopper** [comment]
OK - more clues. I have just ```ls``` the directory locally and there are duplicates where some have ```.jpg``` and some ```.JPG```
I am also getting these errors.
```
2017/06/30 18:08:51 ERROR : IMG_5838.jpg: Failed to copy: resourceModified: ETag does not match current item's value
2017/06/30 18:08:51 INFO  : IMG_5838.JPG: Copied (new)
2017/06/30 18:08:51 INFO  : IMG_5839.JPG: Copied (new)
2017/06/30 18:08:51 ERROR : IMG_5839.jpg: Failed to copy: resourceModified: ETag does not match current item's value
2017/06/30 18:08:53 INFO  : IMG_5840.JPG: Copied (new)
2017/06/30 18:08:54 INFO  : IMG_5840.jpg: Copied (new)
2017/06/30 18:08:55 INFO  : IMG_5841.JPG: Copied (new)
2017/06/30 18:08:56 INFO  : IMG_5841.jpg: Copied (new)
2017/06/30 18:08:57 INFO  : IMG_5843.jpg: Copied (new)
2017/06/30 18:08:57 INFO  : IMG_5843.JPG: Copied (new)
2017/06/30 18:08:57 ERROR : IMG_5842.JPG: Failed to copy: nameAlreadyExists: An item with the same name already exists under the parent
2017/06/30 18:08:58 ERROR : IMG_5844.jpg: Failed to copy: nameAlreadyExists: An item with the same name already exists under the parent
```
My guess is that OneDrive sees them as the same through the API? They both upload but only one version can be seen through the webclient.

**Comment by ncw** [comment]
Ah that makes sense.

onedrive is case insensitive, which means you can only have one of "file.jpg" and "file.JPG".

So when rclone syncs, it will continually replace the files.  You can see it doing it in your log

```
$ grep -i IMG_5746.jpg 1xww 
2017/06/30 17:36:27 DEBUG : IMG_5746.JPG: Size and modification time the same (differ by -336.28768ms, within tolerance 1s)
2017/06/30 17:36:27 DEBUG : IMG_5746.JPG: Unchanged skipping
2017/06/30 17:36:30 INFO  : IMG_5746.jpg: Copied (new)
```

Unfortunately there isn't a solution to this other than to rename your files so they are all different even when made lowercase.

rclone should do a better job warning about this

**Comment by ncw** [comment]
I'm going to close this now as rclone does have better warnings for same case files now.
