### ISSUE TITLE
Can't upload file that contains special characters

### ISSUE THREAD

**Issue by nsuper** [ncw/rclone#1515]
> What is your rclone version (eg output from `rclone -V`)
`Version "v1.36-DEV"`

> Which OS you are using and how many bits (eg Windows 7, 64 bit)
`Linux Ubuntu`

> Which cloud storage system are you using? (eg Google Drive)
`Google Drive`

I think it's a bug when upload single file. Passed if upload a directory.

- Upload a directory `test/` to `drive:test2`
```
rclone copy -c -vv /home/ubuntu/test drive:test2
2017/07/02 11:35:14 DEBUG : rclone: Version "v1.36-DEV" starting with parameters ["/home/ubuntu/bin/rclone" "copy" "-c" "-vv" "/home/ubuntu/test" "drive:test2"]
2017/07/02 11:35:15 INFO  : Google drive root 'test2': Modify window is 1ms
2017/07/02 11:35:15 INFO  : Google drive root 'test2': Waiting for checks to finish
2017/07/02 11:35:15 INFO  : Google drive root 'test2': Waiting for transfers to finish
2017/07/02 11:35:17 INFO  :    ầềm: Copied (new)
Transferred:   4.451 MBytes (1.165 MBytes/s)
Errors:                 0
Checks:                 0
Transferred:            1
Elapsed time:        3.8s
```

- Upload a file: `test/   ầềm` to `drive:test3`
```
rclone copy -c -vvv '/home/ubuntu/test/   ầềm' drive:test3
2017/07/02 11:39:59 DEBUG : rclone: Version "v1.36-DEV" starting with parameters ["/home/ubuntu/bin/rclone" "copy" "-c" "-vv" "/home/ubuntu/test/   ầềm" "drive:test3"]
2017/07/02 11:40:00 INFO  : Google drive root 'test3': Modify window is 1ms
2017/07/02 11:40:00 DEBUG :    ầềm: Excluded from sync (and deletion)
2017/07/02 11:40:00 INFO  : Google drive root 'test3': Waiting for checks to finish
2017/07/02 11:40:00 INFO  : Google drive root 'test3': Waiting for transfers to finish
2017/07/02 11:40:00 INFO  : 
Transferred:      0 Bytes (0 Bytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:        1.1s
```
```
rclone ls drive:test3
2017/07/02 11:45:05 ERROR : : error listing: directory not found
2017/07/02 11:45:05 Failed to ls: directory not found
```

**Comment by nsuper** [comment]
`file` command can read this file

**Comment by nsuper** [comment]
[test-special-chars.tar.gz](https://github.com/ncw/rclone/files/1118023/test-special-chars.tar.gz)

**Comment by ncw** [comment]
I know what is causing this problem... It is the unicode normalization problem again.

```
$ python
>>> import unicodedata
>>> u"ầềm"
u'a\u0302\u0300e\u0302\u0300m'
>>> unicodedata.normalize("NFC", u"ầềm")
u'\u1ea7\u1ec1m'
>>> 
```

The unicode string you've supplied is not normalized.  However by default rclone uses unicode normalization when listing directories.  However when it is building the filter for the single file copy it doesn't use normalization which is probably a bug.

This means there is a work-around - use 

```
      --local-no-unicode-normalization    Don't apply unicode normalization to paths and filenames
```

I'm thinking about unicode normalization in #1477 so I expect I will fix this as part of that.

In the mean time use the work-around, or use a directory sync.

**Comment by ncw** [comment]
I'm going to close this in favour of #1477  - please follow that issue if you are interested.
