### ISSUE TITLE
File Tagging

### ISSUE THREAD

**Issue by scisci** [ncw/rclone#1523]
Some of the backends supported by rclone support some form of file tagging. Would it be possible to add syncing of file tags? If given some guidance, I'd be interested in implementing this. 

My use case is for syncing tags from MacOS to S3. I mainly use the built in tags to organize images rather than folders, it'd be nice if these tags could get synced.

**Comment by ncw** [comment]
How would you see the user interface of this working?

Do your files have tags applied as xattrs or something like that?

Or would the user supply a `--tag potato` command line flag?

**Comment by scisci** [comment]
After considering this more, I don't think its a good feature. Sorry for the premature post.

I thought it could be a feature of the file system. So for any file you could query the filesystem for which tags it has. So on OSX this would be xattrs, then on S3 they have key/value tags. So I would do all my tagging on OSX and then when it syncs to S3 those tags would get saved there.

However, I now see the problem that it would be tough to track added/removed tags. So I can't see this actually working. Also making tags compatible across all of the backends would be tough. For instance S3 only allows 10 key value tags.

So sorry for the noise!
