### ISSUE TITLE
Google Drive: Add flag for keepRevisionForever

### ISSUE THREAD

**Issue by jahands** [ncw/rclone#1525]
Google Drive by default keeps previous versions of a file for 30 days.
However they can be kept forever if you set keepRevisionForever to true.
https://developers.google.com/drive/v3/web/manage-revisions

This would be really useful for certain documents where I may need to revert to a previous version.
While I do of course have other backups, sometimes it's just easier to revert via Drive.

Would it be possible to add this?
Thanks.

> What is your rclone version (eg output from `rclone -V`)
1.36
> Which OS you are using and how many bits (eg Windows 7, 64 bit)
Win10, 64
> Which cloud storage system are you using? (eg Google Drive)
Google Drive
> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone copy file gd: --drive-keep-revision
> A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
2017/07/12 09:45:38 Fatal error: unknown flag: --drive-keep-revision

**Comment by jahands** [comment]
Looks like it's only available in the golang v3 drive package: https://godoc.org/google.golang.org/api/drive/v3#FilesCopyCall.KeepRevisionForever

**Comment by ncw** [comment]
This was discussed [in the forum](https://forum.rclone.org/t/google-drive-revisions-control/3078) and the conclusion was the v2 API could pin things which is nearly as good.

**Comment by jahands** [comment]
Ok, reading the [Migration to v3 guide](https://developers.google.com/drive/v3/web/migration), it looks like pinned and keepRevisionForever are equivulent.

I think the flag should be `--drive-keep-forever` or `--drive-keep-revision-forever` so it matches the flag in the v3 API.

**Comment by timofonic** [comment]
Is it possible then? I'm going to use different services and Google Drive is one of them. I would be interested a lot in this feature.

**Comment by Cubox-** [comment]
Implementing keepRevisionForever requires using the v3 drive API.
Once we are using the v3 api, it's pretty easy to add a flag for it. (Two lines of code).

**Comment by jahands** [comment]
Does #2007 mean this could possibly get added soon? :)

**Comment by ncw** [comment]
@jahands don't see why not!

**Comment by lewapm** [comment]
I would like to solve this issue.

**Comment by ncw** [comment]
That's great @lewapm let me know if you need help with anything.

**Comment by ncw** [comment]
Thanks to @lewapm this is now done in this beta

https://beta.rclone.org/v1.42-004-g84424986/ (uploaded in 15-30 mins)

Which will be in [the latest beta](https://beta.rclone.org) from now on and v1.43

**Comment by xponentia** [comment]
@lewapm Thanks so much I was just looking for this feature and looking forward to testing it out.
