### ISSUE TITLE
Rclone check for superset / subset (one way check)

### ISSUE THREAD

**Issue by jtratner** [ncw/rclone#1526]
(I'd be interested in implementing this feature if you want help, but definitely would follow your instinct on API design)

I appreciate the rclone check command - it's pretty nice. But sometimes I want to check that every local file is on the remote, but I don't care if the remote has more files (or vice-versa). Would that be a feature you'd accept?

Maybe syntax could be:

```
rclone check --one-way local remote
```

Essentially like rclone move but without the delete step, and with some kind of exit code to let you script whether or not it was successful.

**Comment by ncw** [comment]
Sorry, I don't know why I didn't reply to this earlier!  Yes that sounds like a great feature and if you'd like to implement it, even better :-)

I'd add the `--one-way` flag to the `check` command line flags (see `lsjson` for how to add them).  I would have thought the implementation would be quite simple - probably just ignoring one check...

**Comment by ncw** [comment]
@ishuah if you were looking for small ticket - this would be a good one :-)

**Comment by jtratner** [comment]
Yeah unfortunately I no longer have time to do this personally :-/

**Comment by ncw** [comment]
This is now done in - thank you @byrdal 

https://beta.rclone.org/v1.41-076-g2b332bce/ (uploaded in 15-30 mins)
