### ISSUE TITLE
Summary log mode

### ISSUE THREAD

**Issue by mooop12** [ncw/rclone#1527]
I have rclone sync running in the background each night, and I'm piping the output of it to a notification system that goes to my email. The problem is there doesn't seem to be a "summary" kind of log option. You either get a lot of redundant information, or not enough of it. What I had in mind is that rclone would list only the files that are uploaded/removed etc. without progress, as they are processed, and at the end it could print a short summary, such as total transfers, avg. speed etc. Could this be done?

**Comment by ncw** [comment]
That sounds pretty much like what the `-v` flag does.  Have you tried that on a version of rclone 1.36 or [the latest beta](https://beta.rclone.org)?

It will print each file uploaded or deleted and at the end it will print a summary.  It will also print status every minute - if you don't want that then pass --stats 0.

**Comment by mooop12** [comment]
Passing `--stats 0` skips the summary at the end altogether. I'm using rclone 1.36, has this behavior been changed in the beta?

**Comment by ncw** [comment]
Yes `--stats 0` still skips the summary at the end.

You could use something like `-stats 24h` though?

**Comment by mooop12** [comment]
Yup, that seems to be working, thanks. `-v --stats 24h` seems to be more or less what I wanted.
