### ISSUE TITLE
tree command

### ISSUE THREAD

**Issue by adamboche** [ncw/rclone#1528]
It'd be really nice to have a `tree` command for checking the structure of a remote quickly. An [example](https://www.cyberciti.biz/faq/linux-show-directory-structure-command-line/) is below. [The command homepage](http://mama.indstate.edu/users/ice/tree/) has the source.

```
$ apt-get install tree

$ tree

etc
|-- abrt
|   |-- abrt-action-save-package-data.conf
|   |-- abrt.conf
|   |-- gpg_keys
|   `-- plugins
|       |-- CCpp.conf
|       `-- python.conf
|-- acpi
|   |-- actions
|   |   `-- power.sh
|   `-- events
|       |-- power.conf
|       `-- video.conf
|-- adjtime
|-- aliases
|-- aliases.db
|-- alsa
|   `-- alsactl.conf
|-- alternatives
|   |-- links -> /usr/bin/elinks
|   |-- links-man -> /usr/share/man/man1/elinks.1.gz
|   |-- mta -> /usr/sbin/sendmail.postfix
|   |-- mta-aliasesman -> /usr/share/man/man5/aliases.postfix.5.gz
|   |-- mta-mailq -> /usr/bin/mailq.postfix
|   |-- mta-mailqman -> /usr/share/man/man1/mailq.postfix.1.gz
|   |-- mta-newaliases -> /usr/bin/newaliases.postfix
|   |-- mta-newaliasesman -> /usr/share/man/man1/newaliases.postfix.1.gz
|   |-- mta-pam -> /etc/pam.d/smtp.postfix
|   |-- mta-rmail -> /usr/bin/rmail.postfix
|   |-- mta-sendmail -> /usr/lib/sendmail.postfix
|   `-- mta-sendmailman -> /usr/share/man/man1/sendmail.postfix.1.gz
|-- anacrontab
|-- asound.conf
|-- at.deny
|-- audisp
|   |-- audispd.conf
|   `-- plugins.d
|       |-- af_unix.conf
|       |-- sedispatch.conf
|       `-- syslog.conf
|-- audit
|   |-- auditd.conf
....
..
..
|-- xinetd.d
|   `-- rsync
|-- xml
|   `-- catalog
|-- yum
|   |-- pluginconf.d
|   |   |-- product-id.conf
|   |   |-- protectbase.conf
|   |   |-- rhnplugin.conf
|   |   `-- subscription-manager.conf
|   |-- protected.d
|   |-- vars
|   `-- version-groups.conf
|-- yum.conf
`-- yum.repos.d
    |-- epel.repo
    |-- epel-testing.repo
    |-- ksplice-uptrack.repo
    |-- redhat.repo
    `-- rhel-source.repo

208 directories, 1452 files
```

**Comment by ncw** [comment]
Nice idea!

You might want to try [the latest beta](https://beta.rclone.org) and the `rclone ncdu` command in the mean time!

**Comment by Skylion007** [comment]
Also no reason to reinvent the wheel here. Found this programmatic Go tree CLI implementation we can [import](https://github.com/ncw/rclone/issues/1528).

**Comment by adamboche** [comment]
@Skylion007 Is that the right link?

**Comment by Skylion007** [comment]
It is not. https://github.com/a8m/tree is an example of what I was thinking of. There is also https://github.com/DiSiqueira/GoTree and https://github.com/xlab/treeprint which are more specialized just for printing. Also there are some designed just for file systems such as https://github.com/rjeczalik/fs in addition all the pretty printing ones.

**Comment by ncw** [comment]
I had a go with this using  https://github.com/a8m/tree  - here is a beta (I haven't merged the code yet) - let me know if it works!

https://pub.rclone.org/v1.37-028-g9e3ad0f7-tree%CE%B2/

**Comment by adamboche** [comment]
Looks great!

Trying it on an empty directory gives "ERROR : : error listing: directory
not found" -- not sure if something's supposed to go between those colons?

**Comment by kajeagentspi** [comment]
The rclone tree beta doesn't list folders starting with a dot

ex .Media

**Comment by Skylion007** [comment]
or better yet just add a -a specific argument to tree for consistency, or a standard flag for hidden files.

**Comment by ncw** [comment]
Look at the help for the tree command you should see  -a flag.  Not at computer - it is possible I renamed it to avoid a conflict.  rclone tree --help

**Comment by ncw** [comment]
I've merged this to master now - please find it in the latest beta

https://beta.rclone.org/v1.37-031-gf3060caf/ (uploaded in 15-30 mins)

**Comment by adamboche** [comment]
Super -- thanks!
