### ISSUE TITLE
Feature idea: folder size

### ISSUE THREAD

**Issue by austinginder** [ncw/rclone#153]
Cloud storage providers are bad at telling you how large a folder is. I primarily use Dropbox. There is no way to click on a folder and ask how large it is. While this might be outside of rclone's primary purpose, it would be amazing if I could do something like this:

    rclone size [remote:path]
    List total size of a directory

Output could be something like: 2.54GB [remote:path]

**Comment by ncw** [comment]
Nice idea!  And reasonably easy to implement too.

**Comment by ncw** [comment]
This is all done in 1.23 - let me know what you think!

Thanks for the suggestion

Nick

**Comment by austinginder** [comment]
Awesome. Works great for general usage. Thanks so much!

I did attempt a stress test with Dropbox and received the following error. It ran for 1h9m42.2s so a super massive folder :). Looks like Dropbox error out on one of the listings. After further investigation, this folder appears to be different in that it's the only shared folders. I tried out the size command on that folder directly and everything worked good. I'm going to assume it's just a coincidence and maybe that 502 list error may just happen randomly with Dropbox.

     2015/10/03 15:03:01 Dropbox root 'Backup/Sites': Couldn't list: unexpected HTTP status code 502
     2015/10/03 15:03:01 nameTreeNode/"Sites": WalkFiles: exact name of the directory "example.com" is unknown (parent path: "Backup/Sites")
     Total objects: 190954
     Total size: 39.183G (42072034942 bytes)

**Comment by ncw** [comment]
@austinginder Thanks for doing some testing.

The above error looks like a transient problem...  Error 502 is bad gateway which means some bit of dropbox's architecture wasn't working properly - maybe the front end proxies couldn't speak to the backend servers or something like that.  Not anything rclone could cause anyway!
