### ISSUE TITLE
count files command

### ISSUE THREAD

**Issue by adamboche** [ncw/rclone#1530]
I often want to count files in a remote directory. [`rclone size`](https://rclone.org/commands/rclone_size/) can take some time on large remote directories. Would it be possible to make a faster `count` command to just count the files, rather than also describing their sizes?

**Comment by ncw** [comment]
I'm afraid it wouldn't make it any quicker - all the remotes give back sizes in the directory listings.

You can try increasing `--checkers` to speed it up, or alternatively try [the latest beta](https://beta.rclone.org) and `--fast-list` which may or may not help depending on which remote you are using.

**Comment by ncw** [comment]
I'm going to close this now - please re-open if you want more info.
