### ISSUE TITLE
panic in handler for Rename

### ISSUE THREAD

**Issue by Dopefish123** [ncw/rclone#1533]
> What is your rclone version (eg output from `rclone -V`)
1.36-251-g0b2b4243-tps-limitβ
> Which OS you are using and how many bits (eg Windows 7, 64 bit)
Ubuntu 16.04
> Which cloud storage system are you using? (eg Google Drive)
Google Drive
> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
mount
> A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
[panic.txt](https://github.com/ncw/rclone/files/1150896/panic.txt)

2017/07/16 10:05:08 fuse: panic in handler for Rename [ID=0xba9 Node=0x19 Uid=1000 Gid=1000 Pid=20284] from "Brain.on.Fire.2016.1080p.WEB-DL.DD5.1.H264-FGT.mkv" to dirnode 0x3a "Brain.on.Fire.2016.1080p.WEB-DL.DD5.1.H264-FGT.mkv": assignment to entry in nil map
goroutine 4587 [running]:
github.com/ncw/rclone/vendor/bazil.org/fuse/fs.(*Server).serve.func2(0x130b760, 0xc4202f40c0, 0xc420a81ef8, 0xc420a81e57)
        /home/ncw/go/src/github.com/ncw/rclone/vendor/bazil.org/fuse/fs/serve.go:857 +0x1b1
panic(0xd19740, 0xc4203bffa0)
        /opt/go/go1.8/src/runtime/panic.go:489 +0x2cf
github.com/ncw/rclone/cmd/mountlib.(*Dir).addObject(0xc420492100, 0x7f90d5974790, 0xc420a1dc80, 0x1307260, 0xc4201b9ea0, 0x2)
        /home/ncw/go/src/github.com/ncw/rclone/cmd/mountlib/dir.go:132 +0x103
github.com/ncw/rclone/cmd/mountlib.(*Dir).Rename(0xc42184da80, 0xc420e6e2c0, 0x32, 0xc420e6e300, 0x32, 0xc420492100, 0x1, 0xc4214cf290)
        /home/ncw/go/src/github.com/ncw/rclone/cmd/mountlib/dir.go:471 +0x9c6
github.com/ncw/rclone/cmd/mount.(*Dir).Rename(0xc420538140, 0x7f90d5a0b7d0, 0xc420e704c0, 0xc4202f40c0, 0x1301660, 0xc420538070, 0x0, 0x0)
        /home/ncw/go/src/github.com/ncw/rclone/cmd/mount/dir.go:185 +0x36c
github.com/ncw/rclone/vendor/bazil.org/fuse/fs.(*Server).handleRequest(0xc4200cae40, 0x7f90d5a0b7d0, 0xc420e704c0, 0x1301660, 0xc420538140, 0xc420a74e00, 0x130b760, 0xc4202f40c0, 0xc420a81ef8, 0x101000000000060, ...)
        /home/ncw/go/src/github.com/ncw/rclone/vendor/bazil.org/fuse/fs/serve.go:1335 +0x2779
github.com/ncw/rclone/vendor/bazil.org/fuse/fs.(*Server).serve(0xc4200cae40, 0x130b760, 0xc4202f40c0)
        /home/ncw/go/src/github.com/ncw/rclone/vendor/bazil.org/fuse/fs/serve.go:878 +0x495
github.com/ncw/rclone/vendor/bazil.org/fuse/fs.(*Server).Serve.func1(0xc4200cae40, 0x130b760, 0xc4202f40c0)
        /home/ncw/go/src/github.com/ncw/rclone/vendor/bazil.org/fuse/fs/serve.go:425 +0x6e
created by github.com/ncw/rclone/vendor/bazil.org/fuse/fs.(*Server).Serve
        /home/ncw/go/src/github.com/ncw/rclone/vendor/bazil.org/fuse/fs/serve.go:426 +0x3c4

**Comment by Dopefish123** [comment]
Another
[panic3.txt](https://github.com/ncw/rclone/files/1150934/panic3.txt)

**Comment by ncw** [comment]
I've fixed this in https://beta.rclone.org/v1.36-264-gc223464c/ (uploaded in 15-30 mins)

Let me know if there are any problems with it ASAP please because I want to cut the 1.37 release this weekend!

**Comment by Dopefish123** [comment]
Okay, will test it very soon. Just need to sync some files first. Should have a reply in an hour or two.

**Comment by Dopefish123** [comment]
@ncw Sync finished starting testing now...

**Comment by Dopefish123** [comment]
@ncw Its looking good, not been able to reproduce the error so far..

**Comment by Dopefish123** [comment]
@ncw damn it happened again: [panic4.txt](https://github.com/ncw/rclone/files/1167377/panic4.txt)

2017/07/22 15:17:54 fuse: panic in handler for Flush [ID=0x1a8838 Node=0x7bd Uid=1000 Gid=1000 Pid=9099] 0x1 fl=0x0 lk=0xb25bb827c732b0d4: assignment to entry in nil map
goroutine 1739480 [running]:
github.com/ncw/rclone/vendor/bazil.org/fuse/fs.(*Server).serve.func2(0x13112a0, 0xc42e266370, 0xc4294fdef8, 0xc4294fde57)
        /home/travis/gopath/src/github.com/ncw/rclone/vendor/bazil.org/fuse/fs/serve.go:857 +0x1b1
panic(0xd1a680, 0xc42d2c7870)
        /home/travis/.gimme/versions/go1.8.3.linux.amd64/src/runtime/panic.go:489 +0x2cf
github.com/ncw/rclone/cmd/mountlib.(*Dir).addObject(0xc4205dc800, 0x7fd7bcfc0b50, 0xc42068d000, 0x130d260, 0xc4206b50a0, 0xc4294fd880)
        /home/travis/gopath/src/github.com/ncw/rclone/cmd/mountlib/dir.go:132 +0x103
github.com/ncw/rclone/cmd/mountlib.(*File).setObject(0xc4206b50a0, 0x1317440, 0xc42068d000)
        /home/travis/gopath/src/github.com/ncw/rclone/cmd/mountlib/file.go:149 +0x107
github.com/ncw/rclone/cmd/mountlib.(*WriteFileHandle).close(0xc42a793c80, 0xe79f10, 0xc42a793c80)
        /home/travis/gopath/src/github.com/ncw/rclone/cmd/mountlib/write.go:129 +0x452
github.com/ncw/rclone/cmd/mountlib.(*WriteFileHandle).Flush(0xc42a793c80, 0x0, 0x0)
        /home/travis/gopath/src/github.com/ncw/rclone/cmd/mountlib/write.go:172 +0x89
github.com/ncw/rclone/cmd/mount.(*WriteFileHandle).Flush(0xc42a61c120, 0x7fd7bcfc09d0, 0xc42e970b40, 0xc42e266370, 0x0, 0x0)
        /home/travis/gopath/src/github.com/ncw/rclone/cmd/mount/write.go:56 +0x156
github.com/ncw/rclone/vendor/bazil.org/fuse/fs.(*Server).handleRequest(0xc420308e40, 0x7fd7bcfc09d0, 0xc42e970b40, 0x13076e0, 0xc42a61c118, 0xc42a7aff00, 0x13112a0, 0xc42e266370, 0xc4294fdef8, 0x0, ...)
        /home/travis/gopath/src/github.com/ncw/rclone/vendor/bazil.org/fuse/fs/serve.go:1282 +0x32fa
github.com/ncw/rclone/vendor/bazil.org/fuse/fs.(*Server).serve(0xc420308e40, 0x13112a0, 0xc42e266370)
        /home/travis/gopath/src/github.com/ncw/rclone/vendor/bazil.org/fuse/fs/serve.go:878 +0x495
github.com/ncw/rclone/vendor/bazil.org/fuse/fs.(*Server).Serve.func1(0xc420308e40, 0x13112a0, 0xc42e266370)
        /home/travis/gopath/src/github.com/ncw/rclone/vendor/bazil.org/fuse/fs/serve.go:425 +0x6e
created by github.com/ncw/rclone/vendor/bazil.org/fuse/fs.(*Server).Serve
        /home/travis/gopath/src/github.com/ncw/rclone/vendor/bazil.org/fuse/fs/serve.go:426 +0x3c4

**Comment by Dopefish123** [comment]
@ncw I'm confident this issue is resolved, not able to reproduce it. Great!

**Comment by ncw** [comment]
Excellent - thank you very much for testing :-)

Good to get this fix in to 1.37
