### ISSUE TITLE
fuse: panic in handler for Rename - assignment to entry in nil map

### ISSUE THREAD

**Issue by johnybeegood** [ncw/rclone#1536]
Hi Good, 

> What is your rclone version (eg output from `rclone -V`)
rclone v1.36-DEV

> Which OS you are using and how many bits (eg Windows 7, 64 bit)
Linux Debian 9.0 (64 bit)

> Which cloud storage system are you using? (eg Google Drive)
Google Drive

Same problem as for ACD : 

- fuse: panic in handler for Rename #973
https://github.com/ncw/rclone/issues/973

And 

- Rename Panic #1226
https://github.com/ncw/rclone/issues/1226

But i'm using GSuite (Google), and the last version in developpment for the test(s)

Please let me know.. 

Regards,

**Comment by ncw** [comment]
Can you paste in the actual panic message please?

**Comment by ncw** [comment]
Note that this is probably the same problem as #1533

**Comment by ncw** [comment]
I'm going to close this now as I'm 99% sure it is fixed in 1.37 - if not please re-open.

Thanks

Nick
