### ISSUE TITLE
keep alive interval for mount (crypted) sftp

### ISSUE THREAD

**Issue by efenka** [ncw/rclone#1538]
I'm using the rclone mount command to mount an SFTP directory to my local filesystem. This works like expected, but unfortunately the sftp server cuts my connection if more than a few minutes nothing was send. 

I used sshfs before, what has the option `-o ServerAliveInterval=20` what sends some package every 20 seconds to work around this issue. For normal file transfers (using rclone without mount) this is no issue because there are transfers all the time. The better solution would be maybe to detect the issue and reconnect then.

The reason i don't want to use sshfs anymore is encryption. So i don't mount sftp directly but through the crypt remote.

When the timeout occured and i do a directory listing on the mount point this is in the logs: 
```
2017/07/17 12:28:34 DEBUG : /: Attr:
2017/07/17 12:28:34 DEBUG : /: >Attr: attr=valid=1m0s ino=0 size=0 mode=drwxr-xr-x, err=<nil>
2017/07/17 12:28:34 DEBUG : /: ReadDirAll:
2017/07/17 12:28:34 DEBUG : : Re-reading directory (20m6.309653207s old)
2017/07/17 12:28:34 DEBUG : : Dir.ReadDirAll error: List failed: dirExists stat failed: failed to send packet header: EOF
2017/07/17 12:28:34 DEBUG : /: >ReadDirAll: item=-1, err=List failed: dirExists stat failed: failed to send packet header: EOF
```

rclone version: v1.36-231-g575e779bβ
operating system: Ubuntu 16.04.2 LTS x86_64
command: /root/bin/rclone mount --uid=65534 --gid=65534 --allow-other crypted_share: /mnt/crypted_share

I have setup a cron job now to do a `ls` to the mountpoint every minute. But of course i want to get rid of this crappy workaround.

**Comment by ncw** [comment]
The go ssh library doesn't have keepalive support by the look of it.

t looks relatively easy to send keepalives over ssh.

First open a new channel then

```go
	if _, err := ch.SendRequest("keepalive@openssh.com", true, nil); err != nil {
		t.Errorf("unable to send channel keepalive request: %v", err)
	}
```

However it might be better to do an ssh operation like "Stat" (there doesn't seem to be a NO-OP) in the background if we haven't done any other operations which is quite similar to your solution.

An alternative would be to implement re-opening the connection as the FIXME in the source code indicates!  This would be a bit more work as it entails adding retries to the ssh operations, but it would probably be the best thing to do in the long run.

**Comment by ncw** [comment]
This implements connection pooling for multiple ssh connections
    
    A connection may be opened for each `--transfers` and `--checkers`
    now.  Connections are checked when putting them in the pool and
    getting them out the pool so it should recover from network errors
    much better.

https://beta.rclone.org/v1.37-076-g5b6585f5/ (uploaded in 15-30 mins)

Please test and reopen the issue if you are still having a problem, or make a new issue with more info.

Thanks
