### ISSUE TITLE
s3: anonymous access (connecting to a public repo)

### ISSUE THREAD

**Issue by ryanlayer** [ncw/rclone#154]
Hi, I am trying to get data from a public repo (e.g., s3://1000genomes).  I cannot seem get a listing for anything but my personal directories.  Tried making the endpoint in the config file "s3://1000genomes", "//1000genomes", and "http://s3.amazonaws.com/1000genomes".  Also tried making the path on the lsd "//1000genomes".  None of that worked.  Do you have any guidance?

**Comment by ncw** [comment]
You want to refer to the remote as `s3:1000genomes` - no `//` required.  Did you see that form in the docs somewhere (that was the old way)?

I'm not sure how you specify anonymous access with the S3 API (or even if it is possible), but if you have some AWS credentials you can read this repo just fine with rclone.

Here is what I have in my config file

```
[s3]
type = s3
access_key_id = secret
secret_access_key = secret
```

And here is what I typed to get a listing

```
rclone lsl s3:1000genomes
```

And like this to sync to local disk

```
rclone -v sync s3:1000genomes /tmp/1000genomes
```

**Comment by ncw** [comment]
I figured out how to fix the anonymous access - I'll put this in the next release

**Comment by ncw** [comment]
Anon access should work fine now.  I put a section in the s3 help showing how to set it up.

http://rclone.org/s3/

Thanks for the report

Nick

**Comment by ryanlayer** [comment]
Great.  Thanks.

On Sat, Oct 3, 2015 at 9:37 AM, Nick Craig-Wood <notifications@github.com>
wrote:

> Anon access should work fine now. I put a section in the s3 help showing
> how to set it up.
>
> http://rclone.org/s3/
>
> Thanks for the report
>
> Nick
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ncw/rclone/issues/154#issuecomment-145258524>.
>



-- 
Ryan Layer
