### ISSUE TITLE
rclone cat remote:/path/to/file

### ISSUE THREAD

**Issue by ArthurKnoep** [ncw/rclone#1540]
Enhancement :

It will be very cool if we can print the content of a text file on the terminal with a `rclone cat` command

I use rclone for encrypt and save lots of text file, and it's very hassle for me to `rclone copy` and after that use `cat` command

Cordially

**Comment by ncw** [comment]
`rclone cat` is already implemented!  It was done in v1.33 I think.

**Comment by ncw** [comment]
I'm going to close this since it is already done.

**Comment by ArthurKnoep** [comment]
Ok thanks,

Effectively my rclone binary was not up to date
