### ISSUE TITLE
rclone does not timeout on sftp backend when client ip address changes

### ISSUE THREAD

**Issue by dirk777** [ncw/rclone#1541]
After reconnect forcement of DSL, client gets a new ip address, but rclone does not reconnect or timeout

> What is your rclone version (eg output from `rclone -V`)

rclone v1.36

> Which OS you are using and how many bits (eg Windows 7, 64 bit)

macOS Sierra

> Which cloud storage system are you using? (eg Google Drive)

sftp

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

rclone sync

> A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

```
2017/07/18 07:22:52 INFO  : 
Transferred:   7.391 MBytes (12.604 kBytes/s)
Errors:                 0
Checks:                 5
Transferred:            0
Elapsed time:     10m0.3s
Checking:
 * data/41/410883dfee13fc6dd57059db8bd20ba90c1e30678018baa1e320b19133f05a53
 * data/b0/b033e57a1bf1e60262bf47c212ffc77eec61bfdf4571da1bd9280e8270549ec6
 * data/b9/b919f39bd9e6e1da7850bbed78444ef438a73ed12c05b7ff72c9c25c26830b2d
Transferring:
 * ...29988f9d56dd9edd60264cc9547d448b3f5eab1ada:  8% done, 0 Bytes/s, ETA: 0s
 * ...3bf2422f479f0c92cea9a7243887c2d16a22a64b1f: 45% done, 0 Bytes/s, ETA: 0s
 * ...44a6794f30c5a62bdf6711224d9e1e15f6252761b2: 73% done, 0 Bytes/s, ETA: 6135h35m13.167859712s
 * ...71c258dc05a410af921fff854f90af24d824754ecb: 22% done, 0 Bytes/s, ETA: 769937h14m41.232273408s
```

**Comment by ncw** [comment]
Fixing this would also fix #1538

**Comment by ncw** [comment]
This implements connection pooling for multiple ssh connections
    
    A connection may be opened for each `--transfers` and `--checkers`
    now.  Connections are checked when putting them in the pool and
    getting them out the pool so it should recover from network errors
    much better.

https://beta.rclone.org/v1.37-076-g5b6585f5/ (uploaded in 15-30 mins)

Please test and reopen the issue if you are still having a problem, or make a new issue with more info.

Thanks

**Comment by Chainfire** [comment]
I'm still seeing stalled connections with this beta version, multiple lines of:

* ..: 23% done, 0 Bytes/s, ETA: 0s

(sftp, rclone copy, 12 transfers

**Comment by ncw** [comment]
@Chainfire those connections should timeout eventually (5 minutes) and then rclone will open new ones

**Comment by Chainfire** [comment]
I found 11 of 12 transfers stalled both this morning and yesterday morning, apparently for several hours already (the transfers weren't much further along than I left them the night before)... I wish there was something more helpful I could say at this point.
