### ISSUE TITLE
Add the possibility to use internal/external endpoint type for swift

### ISSUE THREAD

**Issue by kayrus** [ncw/rclone#1542]
This feature is already supported in swift library, but it is not yet supported in rclone. I tried to make a pull request, but I'm a bit confused about current implementation... I would rework everything, thus I assume to delegate this to @ncw directly. I suppose he knows how to painlessly implement this.

Some references: https://github.com/ovh/svfs/pull/143

**Comment by ncw** [comment]
I just made the [ApplyEnvironment](https://godoc.org/github.com/ncw/swift#Connection.ApplyEnvironment) method for the swift library which lets you configure everything from environment variables.

For 1.38 I plan to use this in rclone so that will give you a way of setting this.

**Comment by kayrus** [comment]
@ncw I knew that you'll make this in a different way. Thanks.

**Comment by ncw** [comment]
I've updated the swift config to take an endpoint_type and also allow configuring from the environment.

https://beta.rclone.org/v1.37-090-g9c47b767/ (uploaded in 15-30 mins)

Here are the new docs

### Configuration from the environment ###

If you prefer you can configure rclone to use swift using a standard
set of OpenStack environment variables.

When you run through the config, make sure you choose `true` for
`env_auth` and leave everything else blank.

rclone will then set any empty config parameters from the enviroment
using standard OpenStack environment variables.  There is [a list of
the
variables](https://godoc.org/github.com/ncw/swift#Connection.ApplyEnvironment)
in the docs for the swift library.

#### Using rclone without a config file ####

You can use rclone with swift without a config file, if desired, like
this:

```
source openstack-credentials-file
export RCLONE_CONFIG_MYREMOTE_TYPE=swift
export RCLONE_CONFIG_MYREMOTE_ENV_AUTH=true
rclone lsd myremote:
```
