### ISSUE TITLE
B2: delete files during sync instead of marked hidden (necessitating separate cleanup)

### ISSUE THREAD

**Issue by jpap** [ncw/rclone#1547]
As [discussed on the forum](https://forum.rclone.org/t/b2-delete-files-during-sync-and-without-cleanup/3179), it would be of benefit to have an opt-in for a `rclone sync` that permanently deletes files during a sync.  Presently files are hidden, and require a separate `cleanup` run to be removed permanently (see #462).

This would have a number of benefits:

* Minimized bucket disk space (and storage cost) if there are large additions to the bucket during sync because we don't have to wait until the sync completes to recover the space with a cleanup.  This makes it more straightforward for a user implementing a backup system with quota, for example, by purging old backups stored locally prior to syncing.  On sync with `--delete-before`, the remote B2 bucket is then kept within a given quota (storage cost), for example the 10GB free tier.
* By leveraging `--fast-list during` during the sync these file deletions are unmetered (i.e. no additional Class C transactions as `b2_delete_file_version` are free Class A).
* Users do not have to separately run a `rclone cleanup`.

**Comment by ncw** [comment]
Please find a beta with this change in here

https://beta.rclone.org/v1.37-017-g6ae29df4/ (uploaded in 15-30 mins)
