### ISSUE TITLE
OneDrive  having trouble with folder names.. 

### ISSUE THREAD

**Issue by Dutchglory** [ncw/rclone#1549]
> What is your rclone version (eg output from `rclone -V`)
1.36

> Which OS you are using and how many bits (eg Windows 7, 64 bit)
Debina Linux  (buster/sid)   

> Which cloud storage system are you using? (eg Google Drive)
Onedrive

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone -W copy /home/verwijs/Dropbox/Public/Windows Onedrive:Openbaar/Windows

> A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
there' s no -W  flag .... 
 
instead I run: 
rclone --log-file rclone.log --log-level DEBUG copy /home/verwijs/Dropbox/Public/Windows Onedrive:Openbaar/Windows  

output rclone.log: (see attachments with screenshot) 

Issue:
whe copy folder with white space, rclone adds duplicate folders and folder with a "+" character instead of a white space (using a "`\`" character)   

screenshot:
![rclone-copy-test](https://user-images.githubusercontent.com/461485/28489223-5b2518b0-6ebe-11e7-8b9b-03207030b346.png)
 
added log file.... 
[rclone.log.txt](https://github.com/ncw/rclone/files/1167169/rclone.log.txt)

**Comment by ncw** [comment]
This is fixed already in [the latest beta](https://beta.rclone.org) which I'm going to release as 1.37 this weekend hopefully.

**Comment by Dutchglory** [comment]
ok :) thank you..

**Comment by ncw** [comment]
The fix is now in 1.37 - just released.  I'm going to close this now - please re-open if you are still having a problem.

**Comment by Dutchglory** [comment]
ok :) thank you..

**Comment by firewater2** [comment]
Thank you very much for this!
