### ISSUE TITLE
Cannot create/edit ACD remote

### ISSUE THREAD

**Issue by shawnbissell** [ncw/rclone#155]
I just upgraded to rclone 1.2.2 and tried to do a sync and immediately got a 401 error
```
2015/09/28 14:00:16 Failed to create file system for "acd:Movies": Failed to get endpoints: Get https://drive.amazonaws.com/drive/v1/account/endpoint: oauth2: cannot fetch token: 401 Unauthorized
Response: {"error_description":"Client authentication failed","error":"invalid_client"}
```
So I figured I needed a new token so I edited my acd remote with rclone config and tried to refresh the token at the last step which launched my browser and got this error in the browser
```
Error Summary
400 Bad Request
Unknown client_id
Request Details
client_id=my_correct_client_id
redirect_uri=http%3A%2F%2F127.0.0.1%3A53682%2F
response_type=code
scope=clouddrive%3Aread_all+clouddrive%3Awrite
state=a48b42b71a60f3e0e5950e0a675ab384
```
Also I tried to remove the remote and create a new one but got the same error. Not sure what happened here, did my AWS account get disabled or something? I'm able to use the ACD web interface no problem.

**Comment by ncw** [comment]
It says unknown client_id and it appears to be blank which is odd.

I did change something in the reading of client ids in 0872ec3204a605b4aa6f14cecb0392c80068d8ae which went into v1.21.

If you try 1.20 does it work?

I wonder whether you've got a space or some invisible character at in your config file, or maybe the config file has windows line endings for some reason?

Can you check your config file?  It should look like this where there is nothing after the `=` sign in `client_id` or `client_secret`

```
[acd]
type = amazon cloud drive
client_id = 
client_secret = 
token = {"access_token":...secrets...
```

**Comment by shawnbissell** [comment]
No sorry the client_id was correct in the error message. I was trying to be clever and wrapped in angle brackets which github treats as markup apparently

**Comment by shawnbissell** [comment]
Just tried 1.20 and I was able to add my acd remote back as normal.

**Comment by shawnbissell** [comment]
Version 1.21 does not work either fyi

**Comment by ncw** [comment]
It seems likely that the change  0872ec3 is the cause of the problem but I can't figure out why!

What platform are you on (Windows/OS X/Linux, 32/64 bit)?  I'll send you a test binary to print out the `client_id` as I think that is the key to the puzzle.

**Comment by shawnbissell** [comment]
@ncw OS X 64bit. Send away.

**Comment by ncw** [comment]
@shawnbissell [Here](http://www.craig-wood.com/nick/pub/rclone-osx-amd64) you'll find an OSX 64 bit binary which should produce two extra logs like this

```
2015/09/30 09:29:37 Read from config file client_id=""
2015/09/30 09:29:37 Using client_id="amzn1.application-oa2-client.6bf18d2d1f5b485c94c8988bb03ad0e7"
```

When using amazon cloud drive.

The above is what it should say, I wonder what yours will say!

Thanks

Nick

**Comment by shawnbissell** [comment]
Here is what mine says when I do a token refresh
2015/10/01 23:05:23 Read from config file client_id="shawnxxxx@gmail.com"
2015/10/01 23:05:23 Using client_id="shawnxxxx@gmail.com"

**Comment by ncw** [comment]
When you add the remote just leave the client id and client secret blank -  that should work (ie use rclone's)

**Comment by shawnbissell** [comment]
Yes totally worked! Did I miss something in the docs or was there an actual change there?

**Comment by ncw** [comment]
What happened in 1.21 is that I corrected a bug which was ignoring those settings completely, so it didn't matter what you put in them.  So it should have never worked except for the bug!

Thanks for spending the time to work this out with me - I'll add something to the docs to try to make it clearer what those fields are for.

**Comment by ncw** [comment]
I've put some wording changes in to hopefully make this clearer in future

Thanks

Nick
