### ISSUE TITLE
Test failure with more recent github.com/stretchr/testify

### ISSUE THREAD

**Issue by stapelberg** [ncw/rclone#1550]
The currently vendored version of `github.com/stretchr/testify` in the `rclone` repository is at commit https://github.com/stretchr/testify/commit/4d4bfba8f1d1027c4fdbe371823030df51419987 (2017-01-30).

In the meantime, `github.com/stretchr/testify` has gained commit https://github.com/stretchr/testify/commit/46b3c8225b20f01377eeefe3e6b7b147bb742eff, which breaks your tests:
```
% go test github.com/ncw/rclone/fs       
--- FAIL: TestSetDefaults (0.00s)             
	Error Trace:	http_test.go:27
	Error:      	Invalid operation: (func(string, string) (net.Conn, error))(nil) == (func(string, string) (net.Conn, error))(nil) (cannot take func type as argument)
	Messages:   	when checking .Dial
	Error Trace:	http_test.go:28
	Error:      	Invalid operation: (func(string, string) (net.Conn, error))(nil) == (func(string, string) (net.Conn, error))(nil) (cannot take func type as argument)
	Messages:   	when checking .DialTLS
```

Please fix the test.

Also, in the future, please regularly update the vendored versions of your dependencies (using e.g. `dep ensure -update`) :)

I noticed this when investigating why the Debian packaging for `rclone` fails to build (Debian’s `github.com/stretchr/testify` is more recent than your vendored version, and Debian un-vendors everything).

**Comment by ncw** [comment]
I re-vendor everything at the start of the release cycle for rclone.  SInce I just released 1.37 that will be shortly!

> I noticed this when investigating why the Debian packaging for rclone fails to build (Debian’s github.com/stretchr/testify is more recent than your vendored version, and Debian un-vendors everything).

That policy is bound to cause problems with projects like rclone with lots of dependencies.  I didn't used to use vendoring with rclone and people were always complaining that the rclone build was broken.

**Comment by ncw** [comment]
I've fixed this now - see above for the commit.

**Comment by stapelberg** [comment]
Yep, already uploaded to Debian. Thanks!
