### ISSUE TITLE
Add an option to disable server side copies

### ISSUE THREAD

**Issue by Cubox-** [ncw/rclone#1551]
We need a way to disable server side copies in rclone. Such need can be found in issue #1339

**Comment by ncw** [comment]
This is a good idea. I was thinking of a general framework to disable any of the optional features which would be quite easy to implement.

**Comment by Cubox-** [comment]
A way to do that for the server side copies would be to add a check here: https://github.com/ncw/rclone/blob/master/fs/operations.go#L296

I will write a PR for that if you confirm that here is the best place for it.
I do not know what you mean by "optional features", I am not that familiar with rclone's source.

**Comment by Cubox-** [comment]
Just a quick poke @ncw, if the file and line I linked is good for the feature, I'll send a PR fixing this issue instantly. Thanks :)

**Comment by ncw** [comment]
I've fixed this here

https://beta.rclone.org/v1.37-078-gec2ea37a/ (uploaded in 15-30 mins)

Sorry @Cubox - I missed your poke!  I ended up doing it in a more general way.

### --disable FEATURE,FEATURE,... ###

This disables a comma separated list of optional features. For example
to disable server side move and server side copy use:

    --disable move,copy

The features can be put in in any case.

To see a list of which features can be disabled use:

    --disable help

See the overview [features](/overview/#features) and
[optional features](/overview/#optional-features) to get an idea of
which feature does what.

This flag can be useful for debugging and in exceptional circumstances
(eg Google Drive limiting the total volume of Server Side Copies to
100GB/day).

**Comment by Cubox-** [comment]
That's a way better wait to fix the problem rather than my band-aid! I'm happy to have helped you get the idea!
