### ISSUE TITLE
Failed to create file system for "od-plex": didn't find section in config name

### ISSUE THREAD

**Issue by lamarios** [ncw/rclone#1556]
I'm facing a strange issue, I run 4 rclone jobs every night using a shell script so all jobs are using the same command with source and destination set differently.
Script found below: 

`sync() {
	LOG=$3
	SOURCE=$1
	DEST=$2

	echo "Syncing $SOURCE to $DEST, logs: $LOG"

	rm -Rf $LOG
	touch $LOG

	./rclone sync -vv  --transfers 1 --delete-after --retries 999  --log-file $LOG  $SOURCE  $DEST

	
	SUBJECT="$SOURCE  to $DEST complete"
	BODY="`tail -n 20  $LOG`"

	curl -F "AuthorizationToken=sometoken" -F "Title=$SUBJECT" -F "Body=$BODY" https://pushalot.com/api/sendmessage

	curl -s \
	  --form-string "token=sometoken" \
	  --form-string "user=token2" \
	  --form-string "message=$BODY" \
	  --form-string "title=$SUBJECT" \
	  https://api.pushover.net/1/messages.json
	
}

cd /home/gz/scripts/rclone

if [ ! -f syncing.lock ]
then
	
	touch syncing.lock

	sync /mnt/media/Pictures od-paul:Pictures/HTPC pictures-sync.log
	
	sync /home/gz/cloud/joanne/iPhone-pictures od-joanne:Pictures/iPhone joanne-pictures-sync.log

	sync /mnt/media/backups/server/ od-paul:Backups/htpc backups-sync.log

	sync /mnt/media/plex-optimized/ od-plex:/Plex plex-sync.log

	rm -f syncing.lock
else
	echo "Syncing already running"
fi`
I'm running it as root as a cron.

Where it gets weird is that if i run the script as root (sudo) or via run-parts /etc/cron.daily it works fine.
Only when triggered via the cron job I get the error and only for **one of the four**  synchronizations.

I checked the config in /root/.config and in my own home folder /home/gz/.config/rclone and the od-plex is present in both.

It's pretty weird.  is cron using a different config location ? but in that case, all 4 jobs would fail and not only one ?

The 4 jobs are all using different OneDrive accounts.

> What is your rclone version (eg output from `rclone -V`)
1.37

> Which OS you are using and how many bits (eg Windows 7, 64 bit)

Ubuntu 16.04 64bits

> Which cloud storage system are you using? (eg Google Drive)
OneDrive
> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
`./rclone sync -v  --transfers 1 --delete-after --retries 999  --log-file plex-sync.log  /mnt/media/plex-optimized   od-plex:/Plex`
> A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

`2017/07/25 15:18:48 DEBUG : rclone: Version "v1.37" starting with parameters ["./rclone" "sync" "-vv" "--transfers" "1" "--delete-after" "--retries" "999" "--log-file" "plex-sync.log" "/mnt/media/plex-optimized/" "od-plex:/Plex"]
2017/07/25 15:18:48 Failed to create file system for "od-plex:/Plex": didn't find section in config file
`

**Comment by ncw** [comment]
Do they run simultaneously the jobs?  I wonder if they are all updating the config file at the same time?

If you want to rule out a different config file location you could add the `--config` flag.  I suppose if cron's HOME directory was set differently they could use a different file but it seems unlikely.

**Comment by lamarios** [comment]
The jobs were run sequentially but to be sure, i added a one minute sleep between each. Then i used the --config parameter as well. It seems to be working now.

Thanks !
