### ISSUE TITLE
Allow setting a custom user-agent for http backends

### ISSUE THREAD

**Issue by Nothing4You** [ncw/rclone#1557]
> What is your rclone version (eg output from `rclone -V`)

`rclone v1.37`

> Which OS you are using and how many bits (eg Windows 7, 64 bit)

`Debian x86_64`

> Which cloud storage system are you using? (eg Google Drive)

`http`

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

`rclone config` -> `new http` -> `custom user-agent`

> A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

`-`

**Comment by ncw** [comment]
This would be reasonably easy - why do you need it?

**Comment by Nothing4You** [comment]
Some http backends have different ratelimits for different useragents, e.g. increased for browsers or custom downloaders.

**Comment by ncw** [comment]
This should be a matter of making a flag `--user-agent` in fs/config.go and using it to set the UserAgent variable.

Fancy having a go?

**Comment by Nothing4You** [comment]
I don't know any go unfortunately
