### ISSUE TITLE
Entry doesn't belong in directory - Capitalization Issue

### ISSUE THREAD

**Issue by martinzellner** [ncw/rclone#1558]
### System Info:
`rclone -V`: 
    
     rclone v1.37-024-g1ecf2bcbβ
`uname -a` (dockerized):

     Linux cfa773f6935a 4.4.52+ #1 SMP Thu Jun 15 15:23:01 PDT 2017 x86_64 x86_64 x86_64 GNU/Linux

`lsb_release -a`:
    
    Distributor ID:	Ubuntu
    Description:	Ubuntu 16.04.2 LTS
    Release:	16.04
    Codename:	xenial

### Issue

The command I am trying to run (sync a Dropbox folder)

       rclone -vv --fast-list    --bwlimit 30M --tpslimit 10.0  --config /code/rclone.config sync  dropbox:/ /backups/dropbox/

I see the following Log output:

      2017/07/26 07:46:50 ERROR : Some Example/03_for_example/zip-files/20170725.zip: Entry doesn't belong in directory "Some Example/03_For_Example/zip-files" (too short) - ignoring

It looks like Dropbox is having issues with capitalization.

Best,
Martin

**Comment by ncw** [comment]
Hmm, this is a problem with the new dropbox v2 API.  I will look into it!

I might need to get you to test things as I think only old files have those funny lower case paths.

**Comment by martinzellner** [comment]
Cool, thanks! Let me know if I need to test something!

**Comment by milan616** [comment]
@martinzellner I ran into this today and since I'm impatient I ended up changing my path /Plex/Movies to /plexy/movie on Dropbox and this finally let rclone get to the files. Dropbox is weird.

**Comment by tskeeley** [comment]
Ran into this as well.  @ncw let me know if you could use another tester or log files!

**Comment by ncw** [comment]
I've fixed this here - I managed to make it go wrong with my dropbox account which was a bonus - let me know how you get on!

https://beta.rclone.org/v1.37-088-gd54fca4e/ (uploaded in 15-30 mins)

**Comment by tskeeley** [comment]
Confirmed!  It's working again!!  Thank you @ncw , you are amazing!!

**Comment by oliverdain** [comment]
I think I'm hitting the same issue with the latest beta. I downloaded https://downloads.rclone.org/rclone-current-osx-amd64.zip today and ran it. It reports its version as 1.37 so maybe it's not actually a recent beta build?? Anyway, it gives me this:

```
2017/08/29 10:12:48 ERROR : 2017-08-6 [wb, es, od] kitesurf day/Cam3 Konstantin + Nick/REVL0001.LRV: Entry doesn't belong in directory "2017-08-6 [wb, es, od] Kitesurf Day/Cam3 Konstantin + Nick" (too short) - ignoring
2017/08/29 10:12:48 ERROR : 2017-08-6 [wb, es, od] kitesurf day/Cam3 Konstantin + Nick/REVL0001.THM: Entry doesn't belong in directory "2017-08-6 [wb, es, od] Kitesurf Day/Cam3 Konstantin + Nick" (too short) - ignoring
2017/08/29 10:12:48 ERROR : 2017-08-6 [wb, es, od] kitesurf day/Cam3 Konstantin + Nick/REVL0002.CSV: Entry doesn't belong in directory "2017-08-6 [wb, es, od] Kitesurf Day/Cam3 Konstantin + Nick" (too short) - ignoring
... etc
```

**Comment by oliverdain** [comment]
Interesting. The link to the latest doesn't appear to be the latest. I just downloaded the latest beta explicitly from https://beta.rclone.org/v1.37-103-g672c4102/rclone-v1.37-103-g672c4102%CE%B2-osx-amd64.zip and that works fine. Isn't https://downloads.rclone.org/rclone-current-osx-amd64.zip supposed to be a link to the most recent beta?

**Comment by ncw** [comment]
@oliverdain wrote
>  Isn't https://downloads.rclone.org/rclone-current-osx-amd64.zip supposed to be a link to the most recent beta?

That is the most recent release, for the most recent beta you want https://beta.rclone.org/rclone-beta-latest-osx-amd64.zip

**Comment by MaRCoMLXXV** [comment]
Hi @ncw , rclone newbie here. Just discovered your tool yesterday, looking for a way to sync my Dropbox folder to my ARMv7l based router (and use LAN syncing for the other clients at home). I'm running rclone on my Asus RT-AC68U router with Asuswrt-Merlin 380.68 firmware installed, syncing my Dropbox folder to an attached 64Gb USB 3.0 thumb drive. Ran into the same issue syncing Dropbox as the OP, found out only about half of my Dropbox contents where downloaded. Downloaded rclone-v1.37-117-g58f7b4edβ-linux-arm this morning after reading this thread as suggested. The remaining ~6Gb of data was downloaded rapidly, not a single error. Ran a sync again, rclone checked about 16000 files in about 45 seconds, no issues or errors again, so I'm really please finding this 'little' gem. Thanks, definitely very useful! Now of to dive into the documentation to see what else I can do with it :)

**Comment by jondavidjohn** [comment]
@ncw Thanks for such a useful tool!

Any idea when this fix might land in a stable release?

**Comment by ncw** [comment]
It will be in 1.38 Which is scheduled for the end of the month.

**Comment by santoshbs** [comment]
I have the same Dropbox error. I tried to install the beta. It gives me "bash: /usr/bin/rclone: cannot execute binary file: Exec format error" when running the beta.

**Comment by ncw** [comment]
@santoshbs make sure you downloaded the correct version for your architecture. Also try redownloading. If that doesn't help then please paste the URL that you downloaded and a bit more about your machine

**Comment by taskinosman** [comment]
```
root@updatesource-miami:~# timeout 1h /bin/rclone sync desktop:updatesource /web/mirror/.
2017/12/20 18:08:25 ERROR : sv-dev/: Entry doesn't belong in directory "sv-dev" (same as directory) - ignoring
2017/12/20 18:08:25 ERROR : sv/: Entry doesn't belong in directory "sv" (same as directory) - ignoring
2017/12/20 18:08:25 ERROR : gw/: Entry doesn't belong in directory "gw" (same as directory) - ignoring
2017/12/20 18:08:25 ERROR : hx/: Entry doesn't belong in directory "hx" (same as directory) - ignoring
2017/12/20 18:08:25 ERROR : hx-dev/: Entry doesn't belong in directory "hx-dev" (same as directory) - ignoring
```

```
root@updatesource-miami:~# rclone -V
rclone v1.38
- os/arch: linux/amd64
- go version: go1.9
```

using S3 with read-onlt IAM

**Comment by ncw** [comment]
@taskinosman this is a different issue - most likely #1621
