### ISSUE TITLE
Do I need to keep rclone around after uploading files?

### ISSUE THREAD

**Issue by r3muxd** [ncw/rclone#1559]
When filing an issue, please include the following information if possible as well as a description of the problem.  Make sure you test with the latest beta of rclone.

    https://beta.rclone.org/
    https://rclone.org/downloads/

If you've just got a question or aren't sure if you've found a bug then please use the [rclone forum](https://forum.rclone.org/) instead of filing an issue.

> What is your rclone version (eg output from `rclone -V`)

> Which OS you are using and how many bits (eg Windows 7, 64 bit)
N/A
> Which cloud storage system are you using? (eg Google Drive)
N/A
> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
N/A
> A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
N/A

I'm on a live environment. Can I upload (to B2) and reboot without losing data?

**Comment by ncw** [comment]
> Do I need to keep rclone around after uploading files?

No, provided rclone finished successfully your data is on B2 and you don't need to keep rclone around

> I'm on a live environment. Can I upload (to B2) and reboot without losing data?

Provided rclone finished successfully yet.  If you are concerned then use `rclone check` to check the status of the upload.

**Comment by r3muxd** [comment]
How can I run it in the background if it's running?

**Comment by ncw** [comment]
If you didn't start it in the background, you'll need to stop it and restart it in a screen maybe.  rclone is good at starting where it left off.

**Comment by ncw** [comment]
I'm going to close this now as I think the issue has been dealt with.
