### ISSUE TITLE
 Entry doesn't belong in directory "" (contains subdir) - ignoring

### ISSUE THREAD

**Issue by guidtz** [ncw/rclone#1560]
Hello,
  I am newby with rclone but I test with many Object Storage and I have the same error when I do a ls or a copy : 

> Entry doesn't belong in directory "" (contains subdir) - ignoring

I use rclone version 1.37 on Debian 8 Amd64 with swift OVH Object Storage : 

```
# rclone ls -vv test-rclone:/
2017/07/27 10:04:50 DEBUG : rclone: Version "v1.37" starting with parameters ["rclone" "ls" "-vv" "test-rclone:/"]
2017/07/27 10:04:51 INFO  : Swift container : Modify window is 1ns
2017/07/27 10:04:51 ERROR : Apache/Apache.pdf: Entry doesn't belong in directory "" (contains subdir) - ignoring
2017/07/27 10:04:51 ERROR : Apache/Formation_Apache.odp: Entry doesn't belong in directory "" (contains subdir) - ignoring
2017/07/27 10:04:51 ERROR : Apache/Formation_Apache.pdf: Entry doesn't belong in directory "" (contains subdir) - ignoring
2017/07/27 10:04:51 ERROR : Apache/htaccess.pdf: Entry doesn't belong in directory "" (contains subdir) - ignoring
2017/07/27 10:04:51 DEBUG : Go routines at exit 4
2017/07/27 10:04:51 DEBUG : rclone: Version "v1.37" finishing with parameters ["rclone" "ls" "-vv" "test-rclone:/"]
```
remote config : 
```
--------------------
[test-rclone]
type = swift
user = *******
key = **********
auth = https://auth.cloud.ovh.net/v2.0
domain = 
tenant = **************
tenant_domain = 
region = GRA1
storage_url = https://storage.gra1.cloud.ovh.net/v1/AUTH_****************/test-rclone
auth_version = 
--------------------
```

I done a mistake somewhere ?

**Comment by ncw** [comment]
> I done a mistake somewhere ?

Take the container off the end of the `storage_url` and add it to the path you give rclone - I think that is confusing rclone.

So 

```
storage_url = https://storage.gra1.cloud.ovh.net/v1/AUTH_****************/
```

And

```
rclone ls test-rclone:test-rclone
```

Why are you specifying the storage URL BTW? You should specify the auth_url instead

**Comment by ogerasymenko** [comment]
Got same issue with S3 storage and rclone version 1.37

rclone.conf:
[Storage-Name]
type = s3
env_auth = false
access_key_id = id
secret_access_key = key
region = us-east-1
endpoint = 
location_constraint = 
acl = private
server_side_encryption = 
storage_class = 

command example:
./rclone copy --delete-before --copy-links Storage-Name:bucket-name/dirnamel/ /home/user/dest-dir/

**Comment by ncw** [comment]
@ogerasymenko please make a [new issue on github](https://github.com/ncw/rclone/issues/new), and follow the instructions there by trying the latest beta and including a log with `-vv` - thanks!

**Comment by ncw** [comment]
I'm going to close this issue as I think the original question is answered.
