### ISSUE TITLE
SFTP and ability to open multiple SSH connections vs multi transfer with 1 SSH connection

### ISSUE THREAD

**Issue by justusiv** [ncw/rclone#1561]
People are seeing faster speeds with applications like filezilla. I believe the secret in the speed is multiple SSH connections. Per the request of @ncw opening this issue. 

Possible to close earlier issues? 
https://github.com/ncw/rclone/issues/1158

**Comment by dominik-code** [comment]
Got the same results today.
Tested: 1GB RAW Data with Windows 7 64Bit Upload
Ping to SFTP/FTP: ~ 37ms , 10MBit/s Upload
rclone Version 1.36 and 1.37 SFTP

- Filezilla got around 1 MB/s
- rclone getting around 560 KB/s
- 2 x rclone getting 1 MB/s (NOT transfers=2, used 2 different tasks)

Interesting:

- rclone Version 1.36 with ARM64 is reaching the full 1MB/s without problem on my odroid C2

Workaround is using Crypt -> FTP or opening two seperate rclone sessions with Windows

Would be nice to see support for SFTP transfers larger than 1

**Comment by ncw** [comment]
This implements connection pooling for multiple ssh connections
    
    A connection may be opened for each `--transfers` and `--checkers`
    now.  Connections are checked when putting them in the pool and
    getting them out the pool so it should recover from network errors
    much better.

https://beta.rclone.org/v1.37-076-g5b6585f5/ (uploaded in 15-30 mins)

Please test and reopen the issue if you are still having a problem, or make a new issue with more info.

Thanks

**Comment by justusiv** [comment]
@ncw Not sure i can re-open. 
I havent messed with this in a while but just got faster internet net speeds and i can max filezilla at 360Mbps which is my internet speed with 6 connections. Rclone with 6 tansfers is going about 60Mbps 
This was tested with 1.41
