### ISSUE TITLE
Add command to generate download link

### ISSUE THREAD

**Issue by Maxou44** [ncw/rclone#1562]
The latest version with the Windows mount is awesome, thanks a lot !

Can you add a command to generate HTTP download link when it's possible (not available when files are encrypted)

`./rclone link 'gdrive:/dir/myfile.avi'`

And it's generate / get the download link from the backend ?

I think adding this feature would not be very complicated, each backend already gets the file link from its API.

**Comment by ncw** [comment]
To implement this it would need a new optional feature for each Fs which took an object and returned a link.

Quite a lot of the remotes can do this, but not all.

Fancy having a go?

**Comment by Maxou44** [comment]
I will try to add it :)
