### ISSUE TITLE
ERROR from running with cronjob

### ISSUE THREAD

**Issue by denisgolius** [ncw/rclone#1563]
ERROR from running with cronjob

```
2017/07/28 13:50:01 DEBUG : rclone: Version "v1.37" starting with parameters ["/usr/bin/rclone" "-vv" "--log-file=/var/log/rclone.log" "--drive-chunk-size=32768k" "--drive-upload-cutoff=32768k" "copy" "/var/backup/remote:sitename" "remote:sitename"]
2017/07/28 13:50:01 Failed to create file system for "remote:sitename": didn't find section in config file
```

Omg guys, what I'am doing wrong? From Terminal I run command:
```/bin/bash /root/gdrive.sh```
and it's works well! But with running from cronjob it's give me error! Facepalm

ubuntu server 16.04

**Comment by justusiv** [comment]
I don't know for a fact but it seems like when you run it as a cronjob its running as a different "profile" and doesn't have a configured config file.
I'm a windows guy but for example if your script is normally accessing the config located at c:\users\USER123 when running through the cronjob its trying to get the config file from c:\users\admin for example. 
Change your command to manually point the the config file is one solution 
https://rclone.org/docs/
--config=CONFIG_FILE
Specify the location of the rclone config file.

Normally the config file is in your home directory as a file called .config/rclone/rclone.conf (or .rclone.conf if created with an older version). If $XDG_CONFIG_HOME is set it will be at $XDG_CONFIG_HOME/rclone/rclone.conf

If you run rclone -h and look at the help for the --config option you will see where the default location is for you.

Use this flag to override the config location, eg rclone --config=".myconfig" .config.

In addition this is something that should be posted to the forums from help not the issue tracker.

**Comment by denisgolius** [comment]
Ok, I will try in 2 minutes =) Thank's!

**Comment by denisgolius** [comment]
Cheers **justusiv** ! IT'S WORKS!

**Comment by ncw** [comment]
Glad it is working.  https://forum.rclone.org is the best place for this sort of question in future.
