### ISSUE TITLE
rclone about command to give used/quota/other stats from the provider directly

### ISSUE THREAD

**Issue by ColeMundus** [ncw/rclone#1564]
I think it would help if there was a flag to query the API for the size used on supported remotes rather than having rclone recurse through everything and finding the size. Obviously, this would only be supported when querying the size of the whole remote and not individual folders. 

You could use a flag like `--use-api`

An example of this would be when using Google Drive as the remote so when you do `rclone --use-api size google-drive:` it doesn't recurse through all the folders, but instead just queries the API for the size of the remote.

**Comment by mayli** [comment]
maybe a new command called `quota`? Seems works for most storage vendors
onedrive: https://dev.onedrive.com/facets/quotainfo_facet.htm
google drive: https://developers.google.com/drive/v2/reference/about

**Comment by ncw** [comment]
I like the idea of `rclone about`.

This would need a new optional feature for the Fs which would have to return a struct with the superset of all the info - some of which might be blank.

So

  * total bytes used
  * total bytes free
  * total bytes quota
  * total bytes in trash
  * state string?

onedrive

  * total | Int64 | Total allowed storage space, in bytes. Read-only.
  * used | Int64 | Total space used, in bytes. Read-only.
  * remaining | Int64 | Total space remaining before reaching the quota limit, in bytes. Read-only.
  * deleted | Int64 | Total space consumed by files in the recycle bin, in bytes. Read-only.
  * state | string | Enumeration value that indicates the state of the storage space. Read-only

google drive

  * quotaBytesTotal | long | The total number of quota bytes. |  
  * quotaBytesUsed | long | The number of quota bytes used by Google Drive. |  
  * quotaBytesUsedInTrash | long | The number of quota bytes used by trashed items.
  * quotaBytesUsedAggregate | long | The number of quota bytes used by all Google apps (Drive, Picasa, etc.).

Anyone want to have a go at this?

**Comment by mayli** [comment]
I could _try_ learn golang again by impl this :)

**Comment by daylightbrightledlight** [comment]
I like this idea. I think this is similar to https://github.com/ncw/rclone/issues/1138.

**Comment by ncw** [comment]
OK here is probably the final version of about before I merge it - comments appreciated!

https://beta.rclone.org/v1.40-089-gef3bcec7-about/ (uploaded in 15-30 mins)

See the docs here: https://github.com/ncw/rclone/blob/about/cmd/about/about.go#L44

This is supported for local, crypt, cache, drive, swift, hubic, onedrive, pcloud, dropbox

**Comment by ncw** [comment]
rclone about is merged to master now :-)

https://beta.rclone.org/v1.40-090-g2b855751/ (uploaded in 15-30 mins)
