### ISSUE TITLE
http endpoint problems with % in filenames

### ISSUE THREAD

**Issue by zenjabba** [ncw/rclone#1565]
Version: Release 1.37

```
2017/07/29 16:40:22 ERROR : Error parsing "03 - Duke Dumont Feat. AME - Need U (100%).mp3" as URL: parse 03 - Duke Dumont Feat. AME - Need U (100%).mp3: invalid URL escape "%)."

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x64ce36] 
```

**Comment by ncw** [comment]
Can you paste the full backtrace please?

**Comment by zenjabba** [comment]
goroutine 4540 [running]:
net/url.(*URL).ResolveReference(0xc42059f080, 0x0, 0xe521f2)
        /opt/go/go1.8/src/net/url/url.go:944 +0x36
github.com/ncw/rclone/http.urlJoin(0xc42059f080, 0xc425e08300, 0x2e, 0x2e)
        /home/ncw/go/src/github.com/ncw/rclone/http/http.go:71 +0x15c
github.com/ncw/rclone/http.parseName(0xc42059f080, 0xc422876690, 0x46, 0x1, 0x2, 0xc420307420)
        /home/ncw/go/src/github.com/ncw/rclone/http/http.go:203 +0x6c
github.com/ncw/rclone/http.parse.func1(0xc4205b2380)
        /home/ncw/go/src/github.com/ncw/rclone/http/http.go:243 +0x18d
github.com/ncw/rclone/http.parse.func1(0xc42018d180)
        /home/ncw/go/src/github.com/ncw/rclone/http/http.go:252 +0x147
github.com/ncw/rclone/http.parse.func1(0xc42018cee0)
        /home/ncw/go/src/github.com/ncw/rclone/http/http.go:252 +0x147
github.com/ncw/rclone/http.parse.func1(0xc42018cc40)
        /home/ncw/go/src/github.com/ncw/rclone/http/http.go:252 +0x147
github.com/ncw/rclone/http.parse.func1(0xc42018cbd0)
        /home/ncw/go/src/github.com/ncw/rclone/http/http.go:252 +0x147
github.com/ncw/rclone/http.parse(0xc42059f080, 0x7fe0a63bbba8, 0xc420306e40, 0xc420307420, 0x2, 0x2, 0x1, 0x2)
        /home/ncw/go/src/github.com/ncw/rclone/http/http.go:255 +0x109
github.com/ncw/rclone/http.(*Fs).readDir(0xc420187d00, 0xc425e09170, 0x26, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/ncw/go/src/github.com/ncw/rclone/http/http.go:278 +0x40f
github.com/ncw/rclone/http.(*Fs).List(0xc420187d00, 0xc425e09170, 0x26, 0x451180, 0xc42000f020, 0xc4205676e8, 0x4106af, 0xc420567690)
        /home/ncw/go/src/github.com/ncw/rclone/http/http.go:301 +0xc3
github.com/ncw/rclone/fs.ListDirSorted(0x13127c0, 0xc420187d00, 0x428b00, 0xc420321a10, 0x25, 0x0, 0x737b23, 0xc420567748, 0xc420567740, 0xc420618680)
        /home/ncw/go/src/github.com/ncw/rclone/fs/operations.go:615 +0x63
github.com/ncw/rclone/fs.(*syncCopyMove).makeListDir.func1(0xc420321a10, 0x25, 0xc42045bd40, 0x180001, 0x0, 0x0, 0x0)
        /home/ncw/go/src/github.com/ncw/rclone/fs/sync.go:134 +0x53
github.com/ncw/rclone/fs.(*syncCopyMove)._run.func1(0xc42045bd40, 0xc420346c60, 0xc42045bd20, 0xc42035f1e0, 0xc420321a10, 0x25, 0x7ffffffc, 0x0, 0x100)
        /home/ncw/go/src/github.com/ncw/rclone/fs/sync.go:923 +0x72
created by github.com/ncw/rclone/fs.(*syncCopyMove)._run
        /home/ncw/go/src/github.com/ncw/rclone/fs/sync.go:924 +0x987
root@scw-33334e:/usr/local/bin# rclone --version
rclone v1.37

**Comment by vguitar30** [comment]
I have the same problem with rclone v1.37
Here is my log and cmd:
https://pastebin.com/FagtvvyF
Cmd:  rclone -v --checkers=128 --drive-upload-cutoff=16384k --drive-chunk-size=16384k --stats=30s --transfers=16  copyto comics:'/DataHoarder/Comics/Valiant 1992-2017/' Gsuite:'/DataHoarder/Comics/Valiant 1992-2017/'
Go version: 1.8

**Comment by ncw** [comment]
I think this should fix it, please re-open if it doesn't

https://beta.rclone.org/v1.37-038-gb0fd187c/ (uploaded in 15-30 mins)

**Comment by zenjabba** [comment]
Fixed
