### ISSUE TITLE
Relative symbolic links to directories don’t work under Windows

### ISSUE THREAD

**Issue by kkk80** [ncw/rclone#1567]
I get errors if I try to list a directory which contains <b>realtive</b> symbolic links to directories under Windows.

> What is your rclone version (eg output from `rclone -V`)

rclone v1.37-029-gda9926d5

> Which OS you are using and how many bits (eg Windows 7, 64 bit)

Windows 10, 64 bit

> Which cloud storage system are you using? (eg Google Drive)

To reproduce the error no cloud storage system is required.

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

Execute following in a directory in an elevated command window (I've done this in the directory C:\temp\test)
```
mkdir link_target
mkdir to_backup
mklink /d to_backup\link ..\link_target
rclone ls to_backup -L -vv
```
> A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
```
2017/07/31 09:23:30 DEBUG : rclone: Version "v1.37-029-gda9926d5" starting with parameters ["rclone" "ls" "to_backup" "-L" "-vv"]
2017/07/31 09:23:30 INFO  : Local file system at \\?\C:\temp\test\to_backup: Modify window is 100ns
2017/07/31 09:23:30 ERROR : : error listing: GetFileAttributesEx ..\link_target: The system cannot find the file specified.
2017/07/31 09:23:30 Failed to ls: GetFileAttributesEx ..\link_target: The system cannot find the file specified.
````

**Comment by ncw** [comment]
Looks like this is a bug in Go which is fixed in the forthcoming 1.9 release

https://github.com/golang/go/issues/19870

Can you tell me if this works properly which I compiled with the 1.9 beta?

[rclone-v1.37-038-gb0fd187c.zip](https://github.com/ncw/rclone/files/1188131/rclone-v1.37-038-gb0fd187c.zip)

Thanks

**Comment by kkk80** [comment]
Yes, with the 1.9 beta version it is working properly!

**Comment by ncw** [comment]
As go1.9 has been released, I'm now compiling rclone with it.

If you try [the latest beta](https://beta.rclone.org) you should find it works now - please re-open if not!

**Comment by EnoraNedelec** [comment]
With version rclone-v1.40, you should use the flag --copy-links .
This is working both way (upload and download):
```
rclone sync "myremote":"folder" "C:\Users\user\Desktop\folder"  --copy-links  
rclone sync "C:\Users\user\Desktop\folder"  "myremote":"folder"  --copy-links  
```
