### ISSUE TITLE
Failed to move newly written config - v1.37

### ISSUE THREAD

**Issue by MrFr1day** [ncw/rclone#1569]
Hi,

After updating to the last rclone version, every time the access token expires, I get this error:

Failed to move newly written config from C:…\Temp\usr.conf496256607 to final location
: rename C:…\Temp\usr.conf496256607 usr.conf: The system cannot move the file to a different disk drive.

Windows 7
rclone v1.37
Run as Admin, UAC is disabled.

Command used:
`F:\rclone>rclone.exe --config usr.conf ls UD:Backups`

The current copy of the config file gets an ".old" added to it's name, copying the newly created config file manually solves the problem until the access token expires again.

Using the same exact command and same OLD config file with the previous rclone version works as expected.

Thanks.

**Comment by ncw** [comment]
I can see the problem here.  The temp file needs to be saved as config.new in the same place as the config file otherwise the cross file system rename fails.

@breunigs this is your baby - want to have a go at fixing it?

**Comment by breunigs** [comment]
@MrFr1day should be fixed in this beta: https://breunig.xyz/share/rclone-beta/v1.37-043-gcfd3f75b-1569-different-filesystems%CE%B2/
