### ISSUE TITLE
[rclone mount] I need execute permission for every remote file

### ISSUE THREAD

**Issue by Saren-Arterius** [ncw/rclone#1575]
So basically I have came up a crazy idea of getting Steam library on gsuite unlimited so that I can game on my work pc with very very small HDD. 

However, Steam client requires files to be executable for the mounted drive. 

I have googled for 1 hour, I tried using `--umask 000`, `-o`, `--fuse-flag`, `--default-permissions`, and even thought of using overlayfs, unionfs. All the remote files remain 644 and can't be changed.

Is there any way I can have 755 permission on remote files on rclone mounted drive? Thanks.

> What is your rclone version (eg output from `rclone -V`)
rclone v1.37
> Which OS you are using and how many bits (eg Windows 7, 64 bit)
Arch Linux x86_64
> Which cloud storage system are you using? (eg Google Drive)
Google Drive
> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone mount ...
> A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
N/A

**Comment by ncw** [comment]
I think the only way you can do it at the moment is to [hack the source code](https://github.com/ncw/rclone/blob/master/cmd/mountlib/mount.go#L36)

If you try it, I have a nasty feeling you still won't be able to run executables - I'm not sure I've implemented enough of the FS.

I'd be interested to know what happens!

In general there isn't anywhere to store whether a file is executable or not so it would have to be implemented with a flag - `--default-permissions` looks good.

**Comment by Saren-Arterius** [comment]
Hi, I replaced 0666 with 0777, every file gets execute permission and it works. However, steam reports disk write error when downloading games, probably because of lack of random write support. My evil plan is foiled :(
