### ISSUE TITLE
drive: unable to verify on headless machine

### ISSUE THREAD

**Issue by mhkohne** [ncw/rclone#158]
I'm trying to use rclone on a system that doesn't have a browser or even a desktop.
rclone is version 1.22, system is CentOS 6 something, rclone binary is the 64 bit one downloaded from the rclone web site.

The transcript of my rclone config session is below:
(rclone is installed in ~/bin not in /usr/bin, and is being run as the mhkohne user)

2015/10/02 13:58:22 Failed to load config file /home/mhkohne/.rclone.conf - using defaults: open /home/mhkohne/.rclone.conf: no such file or directory
No remotes found - make a new one
n) New remote
q) Quit config
n/q> n
name> rdrive
What type of source is it?
Choose a number from below
 1) amazon cloud drive
 2) drive
 3) dropbox
 4) google cloud storage
 5) local
 6) s3
 7) swift
type> 2
Google Application Client Id - leave blank to use rclone's.
client_id>
Google Application Client Secret - leave blank to use rclone's.
client_secret>
Remote config
Use auto config?
 * Say Y if not sure
 * Say N if you are working on a remote or headless machine
y) Yes
n) No
y/n> n
If your browser doesn't open automatically go to the following link: https://accounts.google.com/o/oauth2/auth?client_id=202264815644.apps.googleusercontent.com&redirect_uri=http%3A%2F%2F127.0.0.1%3A53682%2F&response_type=code&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive&state=acc8a46e5988323e34828af1574585cf
Log in and authorize rclone for access
Enter verification code>

Now, I take that big https URL, paste it into a browser (Chrome, on a desktop PC), and then get asked whether to allow it to have access or not. I grant access, and the browser tries to redirect to http://127.0.0.1, which obviously fails. 

What's going on here? Clearly what's given isn't going to work. Is the 127.0.0.1 supposed to be the address of the server that rclone is running on? 
If so, why did it use 127.0.0.1 when I've already told it the server is headless, and therefore implied that I'm running a browser on another system.

**Comment by ncw** [comment]
Yes you are right this is a bug.

I'll fix it for the next release, but in the mean time you can work around it by changing the URL - the redirect_url bit should look like this `&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob` (replace it up to but not including the next `&`).

**Comment by ncw** [comment]
This should be all fixed in 1.23 - thanks for the report

**Comment by mhkohne** [comment]
FYI, replacing the 'redirect_uri' in the URL did NOT work - it gave me a
code, but when I pasted the code back into rclone, rclone said
'redirect_uri_mismatch'.

v1.23 works just fine, of course.

Thanks!

This should be all fixed in 1.23 - thanks for the report

—
Reply to this email directly or view it on GitHub
<https://github.com/ncw/rclone/issues/158#issuecomment-145258041>.

**Comment by ncw** [comment]
Ah, didn't think of that. Glad 1.23 working though!

**Comment by nikoskarapanagou** [comment]
This was an issue when using on Google Compute Engine instances. Great work! Thanks.
