### ISSUE TITLE
amazon drive sync: folders not removed at destination (no mirror)

### ISSUE THREAD

**Issue by mathieucarbou** [ncw/rclone#1586]
The locally deleted folders are kept at the destination and not removed. So this is not a real mirror sync.

I do not see which option is wrong so I am opening this issue.

local folders:

```
[~] # ls -al /share/Backups/mathieu/
total 40
drwxrwx---    5 admin    administ      4096 Aug  5 12:29 ./
drwxrwxrwx    5 admin    administ      4096 Aug  5 10:22 ../
drwxrwx---    2 mathieu  everyone      4096 Jul 30 20:06 Container/
drwxrwx---    4 admin    administ      4096 Jul 21 20:37 SteamBackups/
drwxrwx---    3 mathieu  everyone      4096 Aug  5 12:48 mathieu@ALIENWARE/
```

after sync:

```
[~] # /share/System/rclone/rclone.sh lsd amazon:NAS/Backups/mathieu
          -1 2017-08-05 14:24:51        -1 Container
          -1 2017-08-05 16:50:15        -1 NetBakData
          -1 2017-08-05 14:24:51        -1 SteamBackups
          -1 2017-08-05 16:50:15        -1 mathieu@ALIENWARE
```

`NetBakData` folder is still there with all its content but has been removed locally.

> What is your rclone version (eg output from `rclone -V`)

```
rclone v1.37-067-gee13ea74β
- os/arch: linux/amd64
- go version: go1.8.3
```

I have also tested rclone v1.37 and it is the same behavior.

> Which OS you are using and how many bits (eg Windows 7, 64 bit)

`Linux NAS 4.2.8 #1 SMP Thu Jul 27 01:09:44 CST 2017 x86_64 GNU/Linux`

> Which cloud storage system are you using? (eg Google Drive)

`Amazon Drive`

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

```
"$RCLONE" sync "$SOURCE" "$REMOTE:/$BUCKET" \
    --log-level "INFO" \
    --retries 10 \
    --transfers 2 \
    --delete-during \
    --delete-excluded \    
    --backup-dir "$REMOTE:/Backups/$BUCKET/$DT" \
    --config "$CONFIG" \
    --filter-from "$FILTERS"
```

**Comment by mathieucarbou** [comment]
here is the content of the filter file:

```
# Excludes

- Multimedia/Movies/**
- System/logs/**
- **/desktop.ini
- **/Thumbs.db
- ._.DS_Store
- .DS_Store
- .Thumbnails
- **/.@__thumb/**
- **/.@upload_cache/**
- **/@Recycle/**
- **/.AppleDB/**
- **/.Qsync/**
- **/.qos_bgImg/**
- **/.qsync/** 
- **/.syncing_db/**
- **/.streams/**
- **/medias Previews.lrdata/**
- **/medias Smart Previews.lrdata/**
- **/others Previews.lrdata/**

# Includes

+ Backups/**
+ Download/**
+ homes/**
+ Public/**
+ System/**
+ Web/**
+ Websites/**
+ Installation/**
+ Books/**
+ Photography/**
+ workspace/**
+ Multimedia/**

# Defaults

- *
```

**Comment by ncw** [comment]
This is an old issue #100 which should be fixed soon hopefully!  In the mean time you can use [rclone rmdirs](https://rclone.org/commands/rclone_rmdirs/) to tidy up.

**Comment by mathieucarbou** [comment]
@ncw : I don't understand how to use it, especially concerning the filtering.

If I want to get a mirror, do I need to run this, with also the filters ?

```
"$RCLONE" rmdirs "$REMOTE:/$BUCKET" \
    --log-level "INFO" \
    --retries 10 \
    --transfers 2 \
    --delete-excluded \    
    --backup-dir "$REMOTE:/Backups/$BUCKET/$DT" \
    --config "$CONFIG" \
    --filter-from "$FILTERS"
```

**Comment by mathieucarbou** [comment]
Note: I did a dry-run and it works approximately because it removes some folders (i.e. all empty folders from the `.svn` folder in projects).

I guess it is not yet possible to make this command only consider files and folders that have been removed locally or that are excluded ?

**Comment by ncw** [comment]
I've now implemented #100, so if you try [the latest beta](https://beta.rclone.org) then you should find it works properly.

**Comment by mathieucarbou** [comment]
I'll try it for a few days and let you know. thanks!

**Comment by mathieucarbou** [comment]
Hi,
I did a test.
Logs: https://gist.github.com/mathieucarbou/6fda402cfedb93c0ccba9393d8cfaaa8
So this is working fine, removed folders are moved to backup dir also.

**Comment by ncw** [comment]
Great!  I'll close this issue then.
