### ISSUE TITLE
which port does rclone used for uploading file to google drive?

### ISSUE THREAD

**Issue by hendranata** [ncw/rclone#1588]
which port does rclone used for uploading file to google drive?

**Comment by sjurtf** [comment]
The source port is controlled by the TCP implementation on your machine.
The destination port is https/443

**Comment by ncw** [comment]
BTW If you are wanting to do QoS then look at the `--bwlimit` flag.

**Comment by hendranata** [comment]
using port 443 if i am not wrong

**Comment by hendranata** [comment]
thanks @sjurtf

**Comment by xhaloz** [comment]
> 
> 
> BTW If you are wanting to do QoS then look at the `--bwlimit` flag.

This is not correct. bwlimit flag is a permanent bwlimit.  QOS throttles the application while other network devices are in use and has the ability to provide full speed when they are not in use.  This is a preferred option as it is more efficient.
