### ISSUE TITLE
Handle Google Drive interruptions

### ISSUE THREAD

**Issue by bobobo1618** [ncw/rclone#159]
When rclone receives a 503 response from Google Drive (I'm getting a lot of them for some reason), it stops and retries the upload. The Google Drive API documentation [suggests](https://developers.google.com/drive/web/manage-uploads#resume-upload) that the upload should be resumed instead.

**Comment by ncw** [comment]
How big are the objects you are uploading?

Can you paste a log with the `-v` flag showing me what is going on?

Thanks

Nick

**Comment by bobobo1618** [comment]
They're RAW images, ~27M each.

Here's an excerpt: 

```
2015/10/02 16:09:14 pacer: Rate limited, increasing sleep to 1.28s                                                                                                                                                                                   [12/1891]
2015/10/02 16:09:15 RAW/2015/2015-07-29/_DSC0581.dng: Sending chunk 28573696 length 248666
2015/10/02 16:09:15 pacer: Rate limited, increasing sleep to 2s
2015/10/02 16:09:16 RAW/2015/2015-07-29/_DSC0581.dng: Sending chunk 28573696 length 248666
2015/10/02 16:09:18 RAW/2015/2015-07-29/_DSC0581.dng: Sending chunk 28573696 length 248666
2015/10/02 16:09:19 RAW/2015/2015-07-29/_DSC0581.dng: Received error: googleapi: Error 503: Transient failure, transientError - retrying 1/10
2015/10/02 16:09:19 RAW/2015/2015-07-29/_DSC0581.dng: Removing failed copy
2015/10/02 16:09:20 pacer: Reducing sleep to 1.5s
2015/10/02 16:09:20 RAW/2015/2015-07-29/_DSC0581.dng: Failed to remove failed copy: googleapi: got HTTP response code 404 with body: Not Found
```

**Comment by bobobo1618** [comment]
Also worth noting that my Drive settings have the rate limits at:

```
Remaining	
999,981,977 requests/day
100% of total
Per-user limit	
100,000 requests/second/user
```

So I'm not sure what's happening there either.

**Comment by bobobo1618** [comment]
Actually I think it must be something else. I'm seeing the same blocks uploading over and over and pacer rate bumping up the rate limiting a ton (this is about the fourth iteration):

```
2015/10/02 20:50:02 pacer: Rate limited, increasing sleep to 2s
2015/10/02 20:50:02 RAW/2015/2015-07-29/_DSC0586.dng: Sending chunk 0 length 28792942
2015/10/02 20:50:05 RAW/2015/2015-07-29/_DSC0587.dng: Sending chunk 0 length 28443290
2015/10/02 20:50:10 RAW/2015/2015-07-29/_DSC0588.dng: Sending chunk 0 length 28319552
2015/10/02 20:50:28 RAW/2015/2015-07-29/_DSC0581.dng: Sending chunk 0 length 28822362
2015/10/02 20:50:34 RAW/2015/2015-07-29/_DSC0585.dng: Sending chunk 0 length 28722442
2015/10/02 20:50:50 RAW/2015/2015-07-29/_DSC0586.dng: Sending chunk 0 length 28792942
2015/10/02 20:50:56 
Transferred:    143100588 Bytes ( 464.83 kByte/s)
Errors:                 0
Checks:             18025
Transferred:            0
Elapsed time:      5m0.6s
Transferring:
 *              RAW/2015/2015-07-29/_DSC0581.dng: 100% done. avg:  117.9, cur:    0.0 kByte/s. ETA: 0s
 *              RAW/2015/2015-07-29/_DSC0585.dng: 100% done. avg:  116.6, cur:    0.0 kByte/s. ETA: 0s
 *              RAW/2015/2015-07-29/_DSC0586.dng: 100% done. avg:  117.8, cur:    0.0 kByte/s. ETA: 0s
 *              RAW/2015/2015-07-29/_DSC0587.dng: 100% done. avg:  115.5, cur:    0.0 kByte/s. ETA: 0s
 *              RAW/2015/2015-07-29/_DSC0588.dng: 100% done. avg:  115.0, cur:    0.0 kByte/s. ETA: 0s

2015/10/02 20:51:00 RAW/2015/2015-07-29/_DSC0587.dng: Sending chunk 0 length 28443290
2015/10/02 20:51:08 RAW/2015/2015-07-29/_DSC0588.dng: Sending chunk 0 length 28319552
2015/10/02 20:51:13 RAW/2015/2015-07-29/_DSC0581.dng: Sending chunk 0 length 28822362
2015/10/02 20:51:15 RAW/2015/2015-07-29/_DSC0585.dng: Sending chunk 0 length 28722442
2015/10/02 20:51:34 RAW/2015/2015-07-29/_DSC0586.dng: Sending chunk 0 length 28792942
2015/10/02 20:51:45 RAW/2015/2015-07-29/_DSC0587.dng: Sending chunk 0 length 28443290
```

**Comment by bobobo1618** [comment]
Ah, I'm getting `410 Gone` responses from Drive and Pacer seems to be responding to that with rate limits.

**Comment by bobobo1618** [comment]
I'm going to close this because my issues appear to be coming from Drive itself.

**Comment by ncw** [comment]
Drive is really fussy about uploads - it can manage no more than 2 per second in my tests, and loves throwing a whole heap of different errors at you.

Only files bigger than 256k (by default) will be uploaded in chunks.  If there is an error in a smaller file then it will be just be retried.  For the larger files the individual chunks are retried, and if that fails (which it does sometimes) then the whole file is retried.  Failing all of that, rclone will retry the whole sync.

It looks like rclone is doing the right things with the retries from the logs you pasted.

The main thing is that does rclone complete properly? In the final summary does it say `Errors: 0`.  In my testing `rclone` pretty much always manages that no matter how badly drive is behaving!

**Comment by bobobo1618** [comment]
Yeah, rclone appears to be working properly, doing what it can given Drive's errors.

In the meantime, I'm fortunate enough to pay or Apps for Work so I've filed a ticket with them.
