### ISSUE TITLE
Issue using rclone copy to existing bucket

### ISSUE THREAD

**Issue by adamlievrouw** [ncw/rclone#1590]
> What is your rclone version (eg output from `rclone -V`)
```
[user@some-server ~]$ rclone -V
rclone v1.37
```

> Which OS you are using and how many bits (eg Windows 7, 64 bit)
```
[user@some-server ~]$ cat /etc/*-release
CentOS Linux release 7.3.1611 (Core)
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

CentOS Linux release 7.3.1611 (Core)
CentOS Linux release 7.3.1611 (Core)
```
```
[user@some-server ~]$ uname -a
Linux some-server 3.10.0-327.3.1.el7.x86_64 #1 SMP Wed Dec 9 14:09:15 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

I’m not sure what I’m doing wrong here. I’m specifying an existing bucket in the configured gcloud project. I’m simply trying to copy a single file into that bucket. It appears to be trying to create a bucket? I’m confused.
```
[user@some-server foo]$ ls
hello-world.txt
[user@some-server foo]$ pwd
/tmp/foo
[user@some-server foo]$ ls
hello-world.txt
[user@some-server foo]$ rclone -vv copy ./hello-world.txt some-gcloud-project:some-gcloud-bucket
2017/08/09 19:22:13 DEBUG : rclone: Version "v1.37" starting with parameters ["rclone" "-vv" "copy" "./hello-world.txt" "some-gcloud-project:some-gcloud-bucket"]
2017/08/09 19:22:13 INFO  : Storage bucket some-gcloud-bucket: Modify window is 1ns
2017/08/09 19:22:13 DEBUG : storage: Excluded from sync (and deletion)
2017/08/09 19:22:13 INFO  : Storage bucket some-gcloud-bucket: Waiting for checks to finish
2017/08/09 19:22:13 INFO  : Storage bucket some-gcloud-bucket: Waiting for transfers to finish
2017/08/09 19:22:14 ERROR : hello-world.txt: Failed to copy: can't make bucket without project number
2017/08/09 19:22:14 ERROR : Attempt 1/3 failed with 1 errors and: can't make bucket without project number
2017/08/09 19:22:14 DEBUG : storage: Excluded from sync (and deletion)
2017/08/09 19:22:14 INFO  : Storage bucket some-gcloud-bucket: Waiting for checks to finish
2017/08/09 19:22:14 INFO  : Storage bucket some-gcloud-bucket: Waiting for transfers to finish
2017/08/09 19:22:14 ERROR : hello-world.txt: Failed to copy: can't make bucket without project number
2017/08/09 19:22:14 ERROR : Attempt 2/3 failed with 1 errors and: can't make bucket without project number
2017/08/09 19:22:15 DEBUG : storage: Excluded from sync (and deletion)
2017/08/09 19:22:15 INFO  : Storage bucket some-gcloud-bucket: Waiting for checks to finish
2017/08/09 19:22:15 INFO  : Storage bucket some-gcloud-bucket: Waiting for transfers to finish
2017/08/09 19:22:15 ERROR : hello-world.txt: Failed to copy: can't make bucket without project number
2017/08/09 19:22:15 ERROR : Attempt 3/3 failed with 1 errors and: can't make bucket without project number
2017/08/09 19:22:15 Failed to copy: can't make bucket without project number
[user@some-server tmp]$ rclone config
Current remotes:

Name                 Type
====                 ====
some-gcloud-project  google cloud storage

e) Edit existing remote
n) New remote
d) Delete remote
r) Rename remote
c) Copy remote
s) Set configuration password
q) Quit config
e/n/d/r/c/s/q> e
Choose a number from below, or type in an existing value
 1 > some-gcloud-project
remote> 1
--------------------
[some-gcloud-project]
type = google cloud storage
client_id =
client_secret =
project_number =
service_account_file = /opt/rclone/some-gcloud-project-service-account.json
object_acl =
bucket_acl =
location = us-central1
storage_class = MULTI_REGIONAL
--------------------
```

**Comment by ncw** [comment]
If you do

    rclone copy foo some-gcloud-project:some-gcloud-bucket -vv --dump-bodies --retries 1

Can you paste (or attach) the output?

Feel free to edit it for confidentiality.  I'm interested in what exactly is going on when it tries to HEAD (or maybe GET) the bucket.

**Comment by adamlievrouw** [comment]
I don't think the full output is needed here.
```
   {
    "domain": "global",
    "reason": "forbidden",
    "message": "some-gcloud-bucket@some-gcloud-project.iam.gserviceaccount.com does not have storage.buckets.get access to bucket some-gcloud-bucket."
   }
```
It appears that this is a permissions limitation with the service account I have configured rclone to use. I've run into things like this before when using WAL-e for backups. If you would still like the full output I can email it to you directly.  I will adjust the permissions the service account has, retest and post my results here tomorrow.

Also, I think outputting the HTTP response error message when using -v might be a worthwhile addition in the future.

**Comment by adamlievrouw** [comment]
I did some quick testing. I had to give the service account both "Storage Legacy Bucket Reader" and "Storage Legacy Bucket Writer" permissions. I had previously given it "Storage Object Creator" and "Storage Object Viewer". These permissions were causing the errors we were seeing. After finding that it the service account didn't have "storage.buckets.get" access I added swapped those two for "Storage Object Admin" which still caused the same error. At that point I added the two legacy permissions and was able to run the command successfully. We can discuss more tomorrow. Thanks for the help!

**Comment by ncw** [comment]
I changed the logic around the test to see if the bucket exists, to only carry on to create the bucket if the error was that the bucket didn't exist, otherwise report it to the user.

Can you give that a go?  It should report a more sensible permission denied message

https://beta.rclone.org/v1.37-083-g76c5aa85/ (uploaded in 15-30 mins)

**Comment by adamlievrouw** [comment]
I've been swamped for the last few days. I'll test this out as soon as I can. Thanks again for your help.

**Comment by ncw** [comment]
I'm going to assume this is fixed - please re-open if not!
