### ISSUE TITLE
anic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by docgonzo2015** [ncw/rclone#1592]
ERROR : Error parsing "An%20Introduction%20to%20Computer%20Viruses%20(and%20other%2.pdf" as URL: parse An%20Introduction%20to%20Computer%20Viruses%20(and%20other%2.pdf: invalid URL escape "%2."
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x64ce36]

goroutine 8804 [running]:
net/url.(*URL).ResolveReference(0xc4223fa700, 0x0, 0xe521f2)
	/opt/go/go1.8/src/net/url/url.go:944 +0x36
github.com/ncw/rclone/http.urlJoin(0xc4223fa700, 0xc4205efb80, 0x40, 0x40)
	/home/ncw/go/src/github.com/ncw/rclone/http/http.go:71 +0x15c
github.com/ncw/rclone/http.parseName(0xc4223fa700, 0xc4223d50e0, 0x4e, 0xc4205efaaf, 0x10, 0xc4205ef901)
	/home/ncw/go/src/github.com/ncw/rclone/http/http.go:203 +0x6c
github.com/ncw/rclone/http.parse.func1(0xc42004a930)
	/home/ncw/go/src/github.com/ncw/rclone/http/http.go:243 +0x18d
github.com/ncw/rclone/http.parse.func1(0xc42004a8c0)
	/home/ncw/go/src/github.com/ncw/rclone/http/http.go:252 +0x147
github.com/ncw/rclone/http.parse.func1(0xc42004a770)
	/home/ncw/go/src/github.com/ncw/rclone/http/http.go:252 +0x147
github.com/ncw/rclone/http.parse.func1(0xc4204b3810)
	/home/ncw/go/src/github.com/ncw/rclone/http/http.go:252 +0x147
github.com/ncw/rclone/http.parse.func1(0xc4204b37a0)
	/home/ncw/go/src/github.com/ncw/rclone/http/http.go:252 +0x147
github.com/ncw/rclone/http.parse.func1(0xc4204b3030)
	/home/ncw/go/src/github.com/ncw/rclone/http/http.go:252 +0x147
github.com/ncw/rclone/http.parse.func1(0xc4204b2cb0)
	/home/ncw/go/src/github.com/ncw/rclone/http/http.go:252 +0x147
github.com/ncw/rclone/http.parse.func1(0xc4204b2b60)
	/home/ncw/go/src/github.com/ncw/rclone/http/http.go:252 +0x147
github.com/ncw/rclone/http.parse(0xc4223fa700, 0x7f39f307d7d8, 0xc4204efae0, 0xc4205ef900, 0x4, 0x4, 0x2, 0x2)
	/home/ncw/go/src/github.com/ncw/rclone/http/http.go:255 +0x109
github.com/ncw/rclone/http.(*Fs).readDir(0xc420173b80, 0xc4202b8000, 0x2e, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/ncw/go/src/github.com/ncw/rclone/http/http.go:278 +0x40f
github.com/ncw/rclone/http.(*Fs).List(0xc420173b80, 0xc4202b8000, 0x2e, 0x10, 0xcba7c0, 0xcb1580, 0xc420376360, 0xc4205bbed0)
	/home/ncw/go/src/github.com/ncw/rclone/http/http.go:301 +0xc3
github.com/ncw/rclone/fs.ListDirSorted(0x13127c0, 0xc420173b80, 0x428b00, 0xc4202b8810, 0x2d, 0xc42030bd10, 0x737b23, 0xc4205bbf48, 0xc4205bbf40, 0xc4202fe480)
	/home/ncw/go/src/github.com/ncw/rclone/fs/operations.go:615 +0x63
github.com/ncw/rclone/fs.(*syncCopyMove).makeListDir.func1(0xc4202b8810, 0x2d, 0xc424224a30, 0x0, 0x1301fe0, 0xc420135ce0, 0x732eb6)
	/home/ncw/go/src/github.com/ncw/rclone/fs/sync.go:134 +0x53
github.com/ncw/rclone/fs.(*syncCopyMove)._run.func1(0xc424224a30, 0xc4204ef8a0, 0xc4242249f0, 0xc4201bf040, 0xc4202b8810, 0x2d, 0x7ffffffc, 0x0, 0x100)
	/home/ncw/go/src/github.com/ncw/rclone/fs/sync.go:923 +0x72
created by github.com/ncw/rclone/fs.(*syncCopyMove)._run
	/home/ncw/go/src/github.com/ncw/rclone/fs/sync.go:924 +0x987

When filing an issue, please include the following information if possible as well as a description of the problem.  Make sure you test with the latest beta of rclone.

    https://beta.rclone.org/
    https://rclone.org/downloads/

If you've just got a question or aren't sure if you've found a bug then please use the [rclone forum](https://forum.rclone.org/) instead of filing an issue.

> What is your rclone version (eg output from `rclone -V`)

rclone v1.37

> Which OS you are using and how many bits (eg Windows 7, 64 bit)

CentOS6.9

> Which cloud storage system are you using? (eg Google Drive)
http -> Google Drive

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
Rclone copy 
> A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

**Comment by ncw** [comment]
Can you try with [the latest beta](https://beta.rclone.org) - I think this is fixed already.

**Comment by ncw** [comment]
Please re-open if it isn't fixed with [the latest beta](https://beta.rclone.org).  Thanks
