### ISSUE TITLE
rclone touch

### ISSUE THREAD

**Issue by ncw** [ncw/rclone#1594]
Make a new command `rclone touch` which either
  * updates the modification time on a file if it exists
  * or if the file doesn't exist then uploads a 0 length file

If the remote can't set mod times (ie SetModTIme returns fs.ErrorCantSetModTime or fs.ErrorCantSetModTimeWithoutDelete) then it should just return that error to the user.

**Comment by ewirch** [comment]
Linux' own `touch` command clears contents of the file. Is this intentional?

**Comment by anchepiece** [comment]
Linux' own `touch` command should not clear the contents, only update the file's last access and modification time or creates a new file if it doesn't exist as @ncw suggests.

What is the spec of such a feature and what is the use case?  Would this feature re-create a file/folder structure in a remote location (full of empty files)?

**Comment by ncw** [comment]
> What is the spec of such a feature and what is the use case? 

An easy way to create an empty file, or update the modtime of a file

> Would this feature re-create a file/folder structure in a remote location (full of empty files)?

Yes it would (that is how rclone works in general).

**Comment by kubatasiemski** [comment]
Hi,
I would like to work with this issue.

**Comment by ncw** [comment]
@kubatasiemski that would be great

**Comment by kubatasiemski** [comment]
Hi,
I have implemented basic functionality and I am working on flags.
On macOS (on linux most likely too) when we try create file in folder that doesn't exists command returns error

Ex.
$ touch dirA/fileB
"touch: dirA/fileB: No such file or directory"

The better way is return any error (which one will the most appropriate?) or create missing dir?

**Comment by anchepiece** [comment]
Yes I suggest that the default implementation recreates the folder structure.

**Comment by kubatasiemski** [comment]
@anchepiece 
Och, yes. Sorry, my bad.
Thanks!

**Comment by ncw** [comment]
@kubatasiemski how are you doing with this?  Are you ready to send a PR?

**Comment by kubatasiemski** [comment]
I have been very busy with study this week. I will send PR tomorrow. Now I have touch command and most of the flags. I have to create documentation and unit tests.

**Comment by ncw** [comment]
I've have merged this now - thank you very much

https://beta.rclone.org/v1.38-124-gde98e248/ (uploaded in 15-30 mins)

**Comment by anchepiece** [comment]
Thanks for squash/merging @ncw!

**Comment by nagualcode** [comment]
Hello, how can I touch all files in remote using a wildcard, like:
rclone touch google-drive:/dirA/*  
?

**Comment by ncw** [comment]
@nagualcode wrote:
> Hello, how can I touch all files in remote using a wildcard, like:

You can't at the moment, you could do it with some shell scripting (untested)

for i in `rclone lsf --files-only google-drive:dirA`; do rclone touch google-drive:$i ; done

Needs [the latest beta](https://beta.rclone.org) for `lsf`

**Comment by BazzaCuda** [comment]
As a token of my appreciation to the last two posters for pointing me in the right direction, here are the contents of my touch-Audio.bat file:

rclone lsf -R --files-only --min-age 2d bn:Audio | sort > Audio.txt
for /F "tokens=*" %%A in (Audio.txt) do rclone touch --no-create --timestamp "2019-09-07T20:00:00" bn:"Audio/%%A"

where bn: is my Google Drive remote, and Audio is a folder at the root of bn:

Fully tested and repeated for the other 30 root folders of my Google Drive.
You can also target a subfolder:

rclone lsf -R --files-only --min-age 2d bn:Audio/Comedy | sort > Audio.txt
for /F "tokens=*" %%A in (Audio.txt) do rclone touch --no-create --timestamp "2019-09-07T20:00:00" bn:"Audio/Comedy/%%A"

I cannot urge enough the necessity of including --no-create. One slip with the editing and you could end up with 1000s of new, 0-length files.

This is by no means a quick operation, but it does chug along smoothly. 
I find it best to set the batch job running and then forget about it until later :)
But it definitely gets the job done.
