### ISSUE TITLE
snap not up to date

### ISSUE THREAD

**Issue by sscotth** [ncw/rclone#1595]
Still uses v1.3.6 https://uappexplorer.com/snap/ubuntu/rclone

```
$ sudo snap install rclone --classic
rclone 1.36 from 'fireeye' installed
```

I'm guessing that the [snapcraft build server](https://build.snapcraft.io) integration was lost or there was a build failure

**Comment by Dedsec1** [comment]
hm, thats strange, will look into this asap.

**Comment by breunigs** [comment]
@Dedsec1 it was an oversight when 1.37 was released – the version number was bumped in one place, but not the other. I have pushed a fix for the missing "fusermount", in which I accidentally broke the whole build. I pushed another patch, where it builds fine using`SNAPCRAFT_CONTAINER_BUILDS=1 snapcraft`. I am currently waiting for your daily build to trigger again – see #1188 to details.

**Comment by sscotth** [comment]
Are we still waiting on a build?

**Comment by breunigs** [comment]
No, it built after my last commit. The build process fails because it is apparently built with an outdated go version. I'm not quite sure what happens here, since rclone's test suite passes even with go 1.6.x. Since I have no access to the build machine and/or setup, I cannot debug this.

**Comment by Dedsec1** [comment]
that is strange as hell, since i was using launch pad's build service for snaps, but something must be up on their end. i think for now suggest using Brew for linux, its an fork of homebrew and rclone does come with it as well.  http://linuxbrew.sh/

**Comment by sscotth** [comment]
Should we remove the snap installation instructions for brew?

https://rclone.org/install/#installation-with-snap

**Comment by breunigs** [comment]
So, the instructions for snap have been removed. I recommend to either install rclone through the normal repositories (I think they're called universe in Ubuntu) or download directly from rclone.org. It's easy, too, since you literally just need one binary which contains everything. The erosion from the repository is maintained, but always lags a bit behind.

Unfortunately I don't know how the remove the old version from the snap shop, in order not to mislead newcomers. If you know, please advise!

**Comment by yassineim** [comment]
According to [this](https://forum.snapcraft.io/t/how-to-delete-snap/1590/2), you'd have to file a bug [here](https://bugs.launchpad.net/snapstore/) to ask for removal of the snap.

**Comment by simos** [comment]
The snap package of `rclone` is still shown as published on the Snap Store:

```
$ snap info rclone
name:      rclone
summary:   "rsync for cloud storage"
publisher: Josh Whiterose (fireeye)
store-url: https://snapcraft.io/rclone
contact:   https://rclone.org
license:   Proprietary
description: |
  "rsync for cloud storage" - Google Drive, Amazon Drive, S3, Dropbox,
  Backblaze B2, One Drive, Swift, Hubic, Cloudfiles, Google Cloud Storage,
  Yandex Files
snap-id: IsLsJunB7e4PJIEtB0VEzfrSWBxgWYlR
channels:
  latest/stable:    1.36 2017-07-19 (466) 6MB -
  latest/candidate: ↑                         
  latest/beta:      ↑                         
  latest/edge:      ↑              
```

If it does not work anymore and new users should not install it, then you can _close_ the channels. 

To do so,
1. Visit https://snapcraft.io/rclone/releases You will  be presented with the four default channels (stable, candidate, beta, edge).
2. Click on the _gear_ icon to **Clone** each channel. I think that if you close the _Edge_ channel, it should close all of them. Your aim is to close all channels. 

That's it!

**Comment by ivandeex** [comment]
The same request is described in the more recent ticket #4971
