### ISSUE TITLE
Sync folder, but skip one of the subfolders

### ISSUE THREAD

**Issue by firewater2** [ncw/rclone#1596]
I want to sync: "C:\Users\Matthew\AppData\Roaming\foobar2000" but skip the folder "wsh_data". How do I do this?

I'm sorry if this is really easy, but I couldn't find it on the documentation.

**Comment by breunigs** [comment]
Filtering has it's own documentation page: https://rclone.org/filtering/

Try something like this: `rclone sync --filter "- wsh_data/" foobar2000 someRemote:/`

**Comment by ncw** [comment]
I'm going to close this now - please ask questions in [the rclone forum](https://forum.rclone.org/) - thanks!
