### ISSUE TITLE
Will rclone support proxy setting ?

### ISSUE THREAD

**Issue by geekpi** [ncw/rclone#160]
I've checked the offical document and it seems that there is no proxy option for this tool. Since dropbox is blocked in China, I have to use global proxy setting (e.g. vpn). Is it possible to support local proxy option like socks, http? Thanks

**Comment by dav1303** [comment]
Hi 
Did you try with http_proxy = http://....:port or https_proxy=https://.....:port

**Comment by klauspost** [comment]
@dav1303 is right. Setting the environment variables "HTTP_PROXY" and "HTTPS_PROXY" (or their lower case equivalent should be picked up. It must be a parseable URL and http type, so I guess "socks" doesn't work.

**Comment by geekpi** [comment]
OK，I'll try it.Thanks a lot

**Comment by ncw** [comment]
The standard go proxy environment vars should work. I should put what the are into the docs!

**Comment by ncw** [comment]
There is now an item in the FAQ about this - see "Can I use rclone with an HTTP proxy?" at http://rclone.org/faq/

Thanks for the report

Nick

**Comment by xiaosong0911** [comment]
I'm using a socks5 proxy, but in the FAQ only http/https proxies are mentioned. So does rclone still not support sock proxy yet?

**Comment by xiaosong0911** [comment]
The worse thing is that golang uses its own network libraries rather than call glibc, so proxywrappers like 'proxychains' and 'tsocks' won't work. https://github.com/rofl0r/proxychains-ng/issues/199

**Comment by ncw** [comment]
@xiaosong0911 it would be relatively easy to make socks5 work at least for the http based remotes - can you please make a [new issue on github](https://github.com/ncw/rclone/issues/new) about support of a socks5 proxy?

**Comment by xiaosong0911** [comment]
@ncw I just made a new issue as you've said. https://github.com/ncw/rclone/issues/1861

**Comment by johnwc** [comment]
If the proxy requires authentication, how does this work if at all?
