### ISSUE TITLE
Failed to create file system / couldn't read info about Drive/ read: connection refused

### ISSUE THREAD

**Issue by RomeSilvanus** [ncw/rclone#1600]
> What is your rclone version (eg output from `rclone -V`)

rclone v1.37-093-gb510c70cβ (latest beta as of now)
os/arch: linux/amd64
go version: go1.8.3

> Which OS you are using and how many bits (eg Windows 7, 64 bit)

Ubuntu Server 17.04

> Which cloud storage system are you using? (eg Google Drive)

Google Drive (Google Apps for Business)

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

`rclone sync -v --stats 1 --transfers 10 [Drive] [Local]`

There is apparently a similar issue for Android but I'm not sure how well it applies here.

I was running `rclone sync -v --stats 1 --transfers 10 [Drive] [Local]` for a few hours already. Sometimes the following error would pop up: `2017/08/13 22:49:51 ERROR : Paws.ru old backup/paws.ru male/thumb/138448173138s.jpg: Failed to copy: failed to open source object: Get https://doc-10-70-docs.googleusercontent.com/docs/securesc/g5qtbhhqm170ckmato0mk8v0jd2h1l2p/ba910k9d0o491aciovki6dbhhef6sln7/1502647200000/00657329702755641360/00657329702755641360/0BwltBLFvlO78U1hOcU5JVUNKLVk?h=06546088761589105300&e=download&gd=true: dial tcp: lookup doc-10-70-docs.googleusercontent.com on 127.0.1.1:53: read udp 127.0.0.1:56297->127.0.1.1:53: read: connection refused` while other file transfers continued on normally at the same time.

This went on for maybe 2 hours after which it completely died. A retry of the same command (`rclone sync -v --stats 1 --transfers 10 [Drive] [Local]`) gave out the following error: `2017/08/13 23:01:19 Failed to create file system for "Google:Furry": couldn't read info about Drive: Get https://www.googleapis.com/drive/v2/about?alt=json: dial tcp: lookup www.googleapis.com on 127.0.1.1:53: read udp 127.0.0.1:33528->127.0.1.1:53: read: connection refused`

I though that maybe something has happened to the network so I tried restarting the server, after which the error changed to: `2017/08/14 19:56:43 Failed to create file system for "Drive:": couldn't read info about Drive: Get https://www.googleapis.com/drive/v2/about?alt=json: Post https://accounts.google.com/o/oauth2/token: dial tcp: lookup accounts.google.com on [::1]:53: read udp [::1]:57669->[::1]:53: read: connection refused`

If I run `rclone config` the following error appears: 
`2017/08/14 21:08:10 Failed to configure token: failed to get token: Post https://accounts.google.com/o/oauth2/token: dial tcp: lookup accounts.google.com on [::1]:53: read udp [::1]:40676->[::1]:53: read: connection refused`

On a side note: While the sync was running I played around with Docker, I also created a Docker network. Though removing said network now didn't change anything. But I rather say it for the off chance that it could have something to do with it.
I did not change any other network settings. Every other service works normally.

**Comment by breunigs** [comment]
The error messages mean that rclone can't resolve the domains to IP addresses. Please double check that your DNS setup is working correctly. This (not yet live) FAQ entry has some more information: https://github.com/ncw/rclone/commit/ee52365e88d0afead00ea2172c1081cd1a9c79b3

**Comment by RomeSilvanus** [comment]
@breunigs Thanks. I got it fixed.

After a bit of search I found this link to [this question on Superuser](https://superuser.com/a/1200745) where it was suggested that disabling DNSSEC will fix this problem. Which, in my case, it did.

Maybe this will help other people.

Guess this can be closed now. Even though I find it weird that literally only rclone had a problem with the DNS.

**Comment by breunigs** [comment]
I don't think rclone is special in regards to DNS, it just doesn't cache it apparently. I couldn't find anything obvious that Go doesn't support DNSSEC and I'd be surprised if DNSSEC is used while querying localhost. I would assume that other tools like `curl` should also fail while DNSSEC is enabled, if the answer you linked is accurate. Did you try?
