### ISSUE TITLE
Support OVH Public Cloud Archive

### ISSUE THREAD

**Issue by wlhlm** [ncw/rclone#1603]
In addition to their Swift-compatible cloud storage, OVH offers a [Cloud Archive](https://www.ovh.co.uk/public-cloud/storage/cloud-archive/) service, which "freezes" data for very low storage costs, but data can take multiple hours to be available for retrieval. Cloud Archive uses the same Swift API albeit with some modifications. For example, in order to create containers on Cloud Archive, an additional header has to be sent:
```
X-Storage-Policy: PCA
```
Otherwise, it defaults to normal object storage for the container.

This can be surprising when uploading files larger than 5GiB (by default), since this means the files get split into segments and rclone creates a new container ("\<containername\>"+"_segments") in which these segments are stored. Since rclone doesn't send the special header this newly created container uses the standard Swift object storage instead of the Cloud Archive service, which has higher storage costs. Luckily, inbound traffic for normal object storage is free, though it can get costly if you don't notice right away (since retention cost is significantly higher).

A workaround is to manually create the _segments container in the web interface where you can choose storage type and rclone will happily use that.

Another thing that's different is, since data takes hours to be available for retrieval, trying to read cold data returns status code `429 Too Many Requests`. Upon the first request, a retrieval job is initiated and there have been addition to the swift API to query when the objects will be available.

- [Cloud Archive developer guide](https://docs.ovh.com/gb/en/cloud/storage/pca/dev/)
- [API perculiarities](https://docs.ovh.com/gb/en/cloud/storage/pca/api/)

**Comment by ncw** [comment]
What would be the minimum changes needed for rclone to support this?

A new flag `--swift-storage-policy` which would add the paramenter to a `X-Storage-Policy` header on container create.  Would that make is useful enough?

The user could attempt to read cold data, get a 429 error, wait for a bit, try again and then it will work?

**Comment by wlhlm** [comment]
> A new flag --swift-storage-policy which would add the paramenter to a X-Storage-Policy header on container create. Would that make is useful enough?

Yes, I think that is enough for basic support. It mostly works now by using the generic Swift driver and manually creating the _segments-container beforehand.

> The user could attempt to read cold data, get a 429 error, wait for a bit, try again and then it will work?

Yes, that works.

**Comment by DougParker1992** [comment]
I agree, I just had this happen to me. For now I can just manually created the segment container for cold storage but it would be ideal if rclone supported a flag that adds a parameters for the X-Storage-Policy Header.

**Comment by ncw** [comment]
I'd love some help with this.  If anyone wants to work on it I'd be very happy to walk you through code changes needed.

**Comment by ncw** [comment]
This is done here - thanks to @rubenbe  

https://beta.rclone.org/v1.42-076-g7f3d5c31/ (uploaded in 15-30 mins)

This will be in [the latest beta](https://beta.rclone.org) and v1.43.

Use it from the `rclone config` wizard or use the `--swift-storage-policy` flag
