### ISSUE TITLE
Bandwidth limiter toggle fails in conjunction with schedules

### ISSUE THREAD

**Issue by cbruegg** [ncw/rclone#1607]
When using a schedule like `--bwlimit "08:00,768 13:00,512 23:00,off"`, signaling `USR2` to rclone yields unexpected results. Initially, disabling the bwlimit works fine, but if a later schedule overrides the `tokenBucket`, sending the signal seems to activate the `tokenBucket` that was disabled with the first signal. 

I believe this is the case due to the variable swap in `account_unix.go` as well as the ticker in `startTokenTicker()` not considering whether the bwlimit is currently disabled or enabled. If it's disabled, it should probably not set `tokenBucket` to the scheduled bwlimit, but instead `prevTokenBucket`, s.t. the scheduled bwlimit only becomes active when toggled again. However, unfortunately I currently don't have the time to verify this, but I hope this helps fixing the issue.

> What is your rclone version (eg output from `rclone -V`)

`d025066fae88173d165cff5c109bab6226a09a7f` (But it looks like this issue is still present in the current code in `master`)

> Which OS you are using and how many bits (eg Windows 7, 64 bit)

Linux, ARM32

> Which cloud storage system are you using? (eg Google Drive)

SFTP

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

sync

> A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

--

**Comment by breunigs** [comment]
You seem to have this debugged in great detail already, which is quite nice. Would you like to try to make a patch, too?

**Comment by cbruegg** [comment]
It's just a theory right now, I haven't actually verified the variable contents for example. I'll try fixing this issue this weekend.
