### ISSUE TITLE
Colon in files inside HTTP remote

### ISSUE THREAD

**Issue by Necrul** [ncw/rclone#1613]
Hello. Having trouble copying from http remote to gdrive remote. I'm able to upload fine not sure why it says the 403 rate limit error in debug log. But it always stops when parsing and comes across a filename with a colon.

> What is your rclone version (eg output from `rclone -V`) 1.37

> Which OS you are using and how many bits (eg Windows 7, 64 bit) Ubuntu Xenial (16.04 latest)

> Which cloud storage system are you using? (eg Google Drive) Google Drive

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`) rclone copy -v httpremote: gdrive:/path/to/folder

> A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

2017/08/18 23:18:56 DEBUG : rclone: Version "v1.37" starting with parameters ["rclone" "copy" "-vv" "dark:" "gdrive:Personal/Sort"]
2017/08/18 23:18:57 INFO  : Google drive root 'Personal/Sort': Modify window is 1s
2017/08/18 23:18:57 DEBUG : pacer: Rate limited, sleeping for 1.723032673s (1 consecutive low level retries)
2017/08/18 23:18:57 DEBUG : pacer: low level retry 1/10 (error googleapi: Error 403: Rate Limit Exceeded, rateLimitExceeded)
2017/08/18 23:18:57 DEBUG : pacer: Rate limited, sleeping for 2.788632838s (2 consecutive low level retries)
2017/08/18 23:18:57 DEBUG : pacer: low level retry 2/10 (error googleapi: Error 403: Rate Limit Exceeded, rateLimitExceeded)
2017/08/18 23:18:57 ERROR : Error parsing "UFOs 1973: Aliens, Abductions and Extraordinary Sightings (2010).avi" as URL: parse UFOs 1973: Aliens, Abductions and Extraordinary Sightings (2010).avi: first path segment in URL cannot contain colon
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x64ce36]

goroutine 54 [running]:
net/url.(*URL).ResolveReference(0xc420234080, 0x0, 0xe521f2)
        /opt/go/go1.8/src/net/url/url.go:944 +0x36
github.com/ncw/rclone/http.urlJoin(0xc420234080, 0xc42059c500, 0x44, 0x44)
        /home/ncw/go/src/github.com/ncw/rclone/http/http.go:71 +0x15c
github.com/ncw/rclone/http.parseName(0xc420234080, 0xc420522de0, 0x5a, 0xc42059fc58, 0x19, 0xc4202e6001)
        /home/ncw/go/src/github.com/ncw/rclone/http/http.go:203 +0x6c
github.com/ncw/rclone/http.parse.func1(0xc4204155e0)
        /home/ncw/go/src/github.com/ncw/rclone/http/http.go:243 +0x18d
github.com/ncw/rclone/http.parse.func1(0xc42029aa10)
        /home/ncw/go/src/github.com/ncw/rclone/http/http.go:252 +0x147
github.com/ncw/rclone/http.parse.func1(0xc42029a770)
        /home/ncw/go/src/github.com/ncw/rclone/http/http.go:252 +0x147
github.com/ncw/rclone/http.parse.func1(0xc42029a2a0)
        /home/ncw/go/src/github.com/ncw/rclone/http/http.go:252 +0x147
github.com/ncw/rclone/http.parse.func1(0xc42029a230)
        /home/ncw/go/src/github.com/ncw/rclone/http/http.go:252 +0x147
github.com/ncw/rclone/http.parse(0xc420234080, 0x7fdaeb82a628, 0xc42043a2e0, 0xc4202e6000, 0x1e2, 0x200, 0x1, 0x2)
        /home/ncw/go/src/github.com/ncw/rclone/http/http.go:255 +0x109
github.com/ncw/rclone/http.(*Fs).readDir(0xc42019fa40, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/ncw/go/src/github.com/ncw/rclone/http/http.go:278 +0x40f
github.com/ncw/rclone/http.(*Fs).List(0xc42019fa40, 0x0, 0x0, 0x0, 0x0, 0x0, 0x42909f, 0xc4204e46b8)
        /home/ncw/go/src/github.com/ncw/rclone/http/http.go:301 +0xc3
github.com/ncw/rclone/fs.ListDirSorted(0x13127c0, 0xc42019fa40, 0x428b00, 0x0, 0x0, 0x0, 0x737b23, 0xc4204e4748, 0xc4204e4740, 0xc42050a0c0)
        /home/ncw/go/src/github.com/ncw/rclone/fs/operations.go:615 +0x63
github.com/ncw/rclone/fs.(*syncCopyMove).makeListDir.func1(0x0, 0x0, 0xc4204361e0, 0x0, 0x0, 0x0, 0x0)
        /home/ncw/go/src/github.com/ncw/rclone/fs/sync.go:134 +0x53
github.com/ncw/rclone/fs.(*syncCopyMove)._run.func1(0xc4204361e0, 0xc420450300, 0xc4204361a0, 0xc420492340, 0x0, 0x0, 0x7ffffffe, 0x7ffffffe, 0x0)
        /home/ncw/go/src/github.com/ncw/rclone/fs/sync.go:923 +0x72
created by github.com/ncw/rclone/fs.(*syncCopyMove)._run
        /home/ncw/go/src/github.com/ncw/rclone/fs/sync.go:924 +0x987

**Comment by Necrul** [comment]
the http site fixed the colon for me so this is not an issue for me now. But hopefully can be worked around or fixed for others. As the ./ or / before the remote path didn't work for me earlier when I tried.

**Comment by breunigs** [comment]
I think this is already fixed in the upcoming 1.38. see here: https://github.com/ncw/rclone/issues/1573
You can try the beta from there and see if it fixes your issue even when the Name so contian colons. If it doesn't work, please reopen this ticket!
