### ISSUE TITLE
Implement Streaming Upload for all remotes that support it

### ISSUE THREAD

**Issue by breunigs** [ncw/rclone#1614]
- [x] ~~Amazon Drive~~
- [x] Amazon S3
- [x] Backblaze B2 – [help wanted](https://github.com/ncw/rclone/issues/1614#issuecomment-324721170)
- [x] Box
- [x] Dropbox
- [x] FTP
- [x] Google Cloud Storage
- [x] Google Drive
- [x] ~~HTTP~~
- [x] Hubic
- [x] ~~Microsoft Azure Blob Storage~~
- [x] ~~Microsoft OneDrive~~
- [x] Openstack Swift
- [x] ~~QingStor~~
- [x] SFTP
- [x] Yandex Disk
- [x] The local filesystem

(strike through = no operator support, checkmark = implemented, if possible)

**Comment by breunigs** [comment]
Amazon S3 looks like it could support streaming uploads – at least rclone doesn't hand in the content-length. However, they do not have a free tier that works without accidentally accumulating a bill, so I do not wish to test them.

**Comment by Kael9527** [comment]
>  looks possible, need to try
Content-Length for QingStor is also require unless set it value of 0, if do it that will only upload data less than 5gb. So, I already submit a commit to handle this.  See, [https://github.com/ncw/rclone/pull/1602/commits/78549c6f370997edb0b875517e4329107bd3f66b](url)

> might you be able to help out here? 
If necessary, I can cooperate with the test;

**Comment by breunigs** [comment]
@Kael9527 Hm. I don't think having streaming for *just* small files (< 5 GB) makes sense. If someone tries to stream a file bigger than that, it will just fail without fallback. I think the current approach of "spooling, then uploading" is fine for QingStor then. If you want to try anyway, try this with the most recent commit:
```
./rclone info -vvv someQingStorRemote:/testFolder/ --check-control=false --check-length=false --check-normalization=false
```
This will stream a tiny file (~20 bytes) to the specified remote/path. Of course, you might want to merge master into https://github.com/ncw/rclone/pull/1602/commits/78549c6f370997edb0b875517e4329107bd3f66b and try there.

**Comment by Kael9527** [comment]
@breunigs 

I have rebase the latest commit  and make it again, then I try to run

`rclone info -vvv TestQingStor:rclond-test-wuyu-02 --check-control=false --check-length=false --check-normalization=false`

It looks running successful with following check:

`[Traveler@TravelerdeMacBook-Pro ~]$rclone ls TestQingStor:rclond-test-wuyu-02
       32 checkStreamingTest
[Traveler@TravelerdeMacBook-Pro ~]$rclone cat TestQingStor:rclond-test-wuyu-02/checkStreamingTest
thinking of test strings is hard
`

> Amazon S3 looks like it could support streaming uploads .....

 I'm also do the same test for Amazon S3  remote, and get the same result as QingStor

**Comment by breunigs** [comment]
@Kael9527 thanks a lot for looking into this. As I wrote earlier, I would keep it for now as is. Once QingStor allows multi part uploads with unknown size, just implement the `PutStreamer` interface to take advantage of these features.

**Comment by breunigs** [comment]
I took a closer look at B2 and there are the following options:
1. streaming only supports small files (< 5GB), breaks for smaller files
2. streaming only supports big files (>`b2-chunk-size`+1)
3. spool `b2-chunk-size`+1 bytes in memory, then start uploading.

I don't think 1 or 2 are viable options. 3 works and is an improvement over spooling the whole file. Right now I don't see this is worth the effort unless there is actual demand. I had to duplicate a bunch of code for `largeUpload.Upload()` already and right now the code allocates an extra buffer to make the decision which upload strategy to use. If it's a large upload this buffer is then needlessly copied in memory again, taking up `2*chunkSize` and ignoring the implied limit through `--transfers`. Not unsolvable, but finicky. I consider B2 Streaming Uploads as a "Help Wanted" feature :). My unfinished attempt is at https://github.com/breunigs/rclone/tree/wip-b2-streaming-upload.

**Comment by breunigs** [comment]
All current providers that generally allow uploading files without specifying the total file size in advance now support the streaming interface. If one of the unsupported providers change their API, please open a new ticket so support may be implemented for them!

**Comment by ncw** [comment]
That is fab!  Can you update the [overview](https://github.com/ncw/rclone/blob/master/docs/content/overview.md)?  I think it is out of date WRT your latest changes.

Thanks

**Comment by breunigs** [comment]
Thanks for the reminder, it's updated now.
