### ISSUE TITLE
Snap package can't read/write configuration file.

### ISSUE THREAD

**Issue by Prajjwal** [ncw/rclone#1618]
This is an `Ubuntu 16.04` machine, with rclone installed as follows:

`sudo snap install rclone`

I'm on version `1.36`

Every time I try to create a new remote, it walks me through all the steps, and then fails to write the file. When I write the configuration file manually, and try to run `rclone config`, it fails to even read the file.

```
2017/08/22 08:16:49 Failed to load config file "/home/prajjwal/.rclone.conf": open /home/prajjwal/.rclone.conf: permission denied
```

What I've tried:

* reinstalling it
* `chown`
* `chmod 0777 /home/prajjwal/.rclone.conf` (just to test it, still doesn't work)
* Moving the configuration with various permissions to `~/.config/rclone/rclone.conf`.
* Created the configuration at `/root/.rclone.conf`, and ran `sudo rclone config`. Same error, it can't open `/root/.rclone.conf`.

Here are the current permissions on the file:

```
Access: (0777/-rwxrwxrwx)  Uid: ( 1001/prajjwal)   Gid: (    0/    root)
```

I can confirm that the binaries downloaded off the website work with the exact same configuration on an identical server.

Any help appreciated.

**Comment by breunigs** [comment]
Try to install the snap in classic mode (something like `snap install --classic rclone` if I remember correctly). You might have to uninstall the previous version). Alternatively you can connect rclone with the home interface, so roughly `snap connect rclone:home :home`.

**Comment by breunigs** [comment]
Ah sorry, the last one will not work apparently: "Can access non-hidden files in user's $HOME and gvfs mounted directories owned by the user to read/write/lock" https://snapcraft.io/docs/reference/interfaces . I guess you must install rclone in classic mode then.

**Comment by Prajjwal** [comment]
@breunigs 

`snap install --classic rclone` worked perfectly. Thank you!

**Comment by ncw** [comment]
@breunigs is this something which should go in the docs?

**Comment by breunigs** [comment]
@ncw it already is: https://rclone.org/install/#installation-with-snap `sudo snap install rclone --classic`. I am actually leaning towards removing the snap docs, since it currently fails to build from source (#1595) and is stuck on 1.36, last I checked.

**Comment by ncw** [comment]
@breunigs Ah OK!  Perhaps the snap package was a mistake - I'm happy with you removing the docs if you want.  Especially since there is an actual ubuntu package for rclone now.

**Comment by Prajjwal** [comment]
But there's no `rclone` package in the official Ubuntu 16.04 repositories, and snap is the most convenient way of installing it there. Is there an official backports PPA? I don't want to compile from source, nor use the precompiled binaries, because managing dependencies outside the package manager is an additional headache.

**Comment by breunigs** [comment]
go builds fat binaries which contain all needed dependencies – so you really only need the binary for you architecture if you just want to run rclone.

**Comment by breunigs** [comment]
@ncw I thought about this and removing the docs seems to be the best approach for now. With 1.38 released, the snap version will be two versions behind and the build service fails for reasons I don't understand (it builds locally in a clean env. On [the CI it fails on go get](https://launchpadlibrarian.net/336079902/buildlog_snap_ubuntu_yakkety_arm64_rclone_BUILDING.txt.gz)?). Of course, once someone steps up and fixes this, we can always revert the change.

I am wondering, though, how to remove the previous snap. It doesn't seem all that obvious which version is current or maintained, when there's both the snap version as well as the Debian one (which I presume is the one available in Ubuntu).
