### ISSUE TITLE
Panic while deduping google drive

### ISSUE THREAD

**Issue by josiah2009** [ncw/rclone#1619]
While trying to dedupe my google drive, it will run for about an hour then it will panic and segfault.
I can provide a full log if needed.

> What is your rclone version (eg output from `rclone -V`)

rclone v1.37-101-g0158ab69β
- os/arch: linux/amd64
- go version: go1.8.3

> Which OS you are using and how many bits (eg Windows 7, 64 bit)

Debian sid amd64

> Which cloud storage system are you using? (eg Google Drive)

Google Drive

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

rclone dedupe --dedupe-mode newest gcd: -vvv

> A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

2017/08/23 15:48:44 INFO  : gtt8regaeqgoq2vrqvcdkl7tko/j9pdlbqq02j085j920oguqoklg/8ib4719b84ua0dpd9bgvgahmjt003ps8nhj8r45659t0bhsnf9ld5egof9j8nin2rpo1rr8k55meu: Merging contents of duplicate directories
2017/08/23 15:48:44 INFO  : gtt8regaeqgoq2vrqvcdkl7tko/j9pdlbqq02j085j920oguqoklg/8ib4719b84ua0dpd9bgvgahmjt003ps8nhj8r45659t0bhsnf9ld5egof9j8nin2rpo1rr8k55meu: merging "kr8n2v8fk97bt68mhnjlb0l17tq6shmgtbvs68oc1fsndeuismp0dh0f80qa2o96efu2o8uteb12u"
2017/08/23 15:48:46 INFO  : gtt8regaeqgoq2vrqvcdkl7tko/j9pdlbqq02j085j920oguqoklg/8ib4719b84ua0dpd9bgvgahmjt003ps8nhj8r45659t0bhsnf9ld5egof9j8nin2rpo1rr8k55meu: merging "np30or7v726tes8a84plb0729c"
2017/08/23 15:48:47 INFO  : gtt8regaeqgoq2vrqvcdkl7tko/j9pdlbqq02j085j920oguqoklg/8ib4719b84ua0dpd9bgvgahmjt003ps8nhj8r45659t0bhsnf9ld5egof9j8nin2rpo1rr8k55meu: merging "us40q49j4luktib244jnd2ogd0"
2017/08/23 15:48:47 INFO  : gtt8regaeqgoq2vrqvcdkl7tko/j9pdlbqq02j085j920oguqoklg/8ib4719b84ua0dpd9bgvgahmjt003ps8nhj8r45659t0bhsnf9ld5egof9j8nin2rpo1rr8k55meu: merging "pptot47u71ft660chel8al274s"
2017/08/23 15:48:48 INFO  : gtt8regaeqgoq2vrqvcdkl7tko/j9pdlbqq02j085j920oguqoklg/8ib4719b84ua0dpd9bgvgahmjt003ps8nhj8r45659t0bhsnf9ld5egof9j8nin2rpo1rr8k55meu: merging "n0sgedqquoqdoi18ncham9iav4"
2017/08/23 15:48:49 INFO  : gtt8regaeqgoq2vrqvcdkl7tko/j9pdlbqq02j085j920oguqoklg/8ib4719b84ua0dpd9bgvgahmjt003ps8nhj8r45659t0bhsnf9ld5egof9j8nin2rpo1rr8k55meu: merging "1bbncjkpr5jidj2a23dk4dn1s8"
2017/08/23 15:48:50 INFO  : gtt8regaeqgoq2vrqvcdkl7tko/j9pdlbqq02j085j920oguqoklg/8ib4719b84ua0dpd9bgvgahmjt003ps8nhj8r45659t0bhsnf9ld5egof9j8nin2rpo1rr8k55meu: merging "k6m6tah5mlhahkv0tgf35fe4i8"
2017/08/23 15:48:52 INFO  : gtt8regaeqgoq2vrqvcdkl7tko/j9pdlbqq02j085j920oguqoklg/im14gfavd8ievvjqmm5v5oggu2sp2eerljar77t2olk4f53sp2bp1enjbtj6t5ql59hah573rsfoen1063t4u270i4tg0ssv1ql25c0: Merging contents of duplicate directories
2017/08/23 15:48:53 INFO  : gtt8regaeqgoq2vrqvcdkl7tko/j9pdlbqq02j085j920oguqoklg/im14gfavd8ievvjqmm5v5oggu2sp2eerljar77t2olk4f53sp2bp1enjbtj6t5ql59hah573rsfoen1063t4u270i4tg0ssv1ql25c0: merging "1bbncjkpr5jidj2a23dk4dn1s8"
2017/08/23 15:48:54 INFO  : gtt8regaeqgoq2vrqvcdkl7tko/j9pdlbqq02j085j920oguqoklg/im14gfavd8ievvjqmm5v5oggu2sp2eerljar77t2olk4f53sp2bp1enjbtj6t5ql59hah573rsfoen1063t4u270i4tg0ssv1ql25c0: merging "n0sgedqquoqdoi18ncham9iav4"
2017/08/23 15:48:55 INFO  : gtt8regaeqgoq2vrqvcdkl7tko/j9pdlbqq02j085j920oguqoklg/nh9dce5gct92dhv5s2stk1lah043ms62c5pe3i8r3cgtbgj1sj72iq84jlvnleo4ssc2koo09ipb2: Merging contents of duplicate directories
2017/08/23 15:48:56 INFO  : gtt8regaeqgoq2vrqvcdkl7tko/j9pdlbqq02j085j920oguqoklg/nh9dce5gct92dhv5s2stk1lah043ms62c5pe3i8r3cgtbgj1sj72iq84jlvnleo4ssc2koo09ipb2: merging "n0sgedqquoqdoi18ncham9iav4"
2017/08/23 15:48:57 INFO  : gtt8regaeqgoq2vrqvcdkl7tko/j9pdlbqq02j085j920oguqoklg/nh9dce5gct92dhv5s2stk1lah043ms62c5pe3i8r3cgtbgj1sj72iq84jlvnleo4ssc2koo09ipb2: merging "np30or7v726tes8a84plb0729c"
2017/08/23 15:48:59 INFO  : gtt8regaeqgoq2vrqvcdkl7tko/j9pdlbqq02j085j920oguqoklg/nh9dce5gct92dhv5s2stk1lah043ms62c5pe3i8r3cgtbgj1sj72iq84jlvnleo4ssc2koo09ipb2: merging "1bbncjkpr5jidj2a23dk4dn1s8"
2017/08/23 15:48:59 INFO  : gtt8regaeqgoq2vrqvcdkl7tko/j9pdlbqq02j085j920oguqoklg/nh9dce5gct92dhv5s2stk1lah043ms62c5pe3i8r3cgtbgj1sj72iq84jlvnleo4ssc2koo09ipb2: merging "k6m6tah5mlhahkv0tgf35fe4i8"
2017/08/23 15:49:00 INFO  : gtt8regaeqgoq2vrqvcdkl7tko/j9pdlbqq02j085j920oguqoklg/nh9dce5gct92dhv5s2stk1lah043ms62c5pe3i8r3cgtbgj1sj72iq84jlvnleo4ssc2koo09ipb2: merging "v7lkm1ub2dqdu7jq0puh63ohsn707l2bh97mu8dp78hnv4fduehehasaa90l6t9fe40ep52ct284a"
2017/08/23 15:49:01 DEBUG : pacer: Rate limited, sleeping for 1.10653003s (1 consecutive low level retries)
2017/08/23 15:49:01 DEBUG : pacer: low level retry 1/10 (error googleapi: Error 403: Rate Limit Exceeded, rateLimitExceeded)
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x210 pc=0x971a72]

goroutine 1 [running]:
github.com/ncw/rclone/drive.(*Fs).MergeDirs.func2(0xc4201d09c0, 0xc4203541b0, 0xe92007)
        /home/travis/gopath/src/github.com/ncw/rclone/drive/drive.go:753 +0xf2
github.com/ncw/rclone/pacer.(*Pacer).call(0xc4201d09c0, 0xc420016180, 0xa, 0xdea460, 0x1)
        /home/travis/gopath/src/github.com/ncw/rclone/pacer/pacer.go:334 +0x71
github.com/ncw/rclone/pacer.(*Pacer).Call(0xc4201d09c0, 0xc420016180, 0xe79055, 0xa)
        /home/travis/gopath/src/github.com/ncw/rclone/pacer/pacer.go:357 +0x66
github.com/ncw/rclone/drive.(*Fs).MergeDirs(0xc4201d4f00, 0xc420443060, 0x2, 0x2, 0x0, 0x0)
        /home/travis/gopath/src/github.com/ncw/rclone/drive/drive.go:756 +0x3be
github.com/ncw/rclone/fs.(MergeDirser).MergeDirs-fm(0xc420443060, 0x2, 0x2, 0x29, 0x0)
        /home/travis/gopath/src/github.com/ncw/rclone/fs/fs.go:425 +0x4d
github.com/ncw/rclone/fs.dedupeMergeDuplicateDirs(0x1365700, 0xc4201d4f00, 0xc420892000, 0x37e, 0x400, 0x0, 0x0)
        /home/travis/gopath/src/github.com/ncw/rclone/fs/operations.go:1391 +0x1d4
github.com/ncw/rclone/fs.Deduplicate(0x1365700, 0xc4201d4f00, 0x3, 0x5, 0xc4201263c0)
        /home/travis/gopath/src/github.com/ncw/rclone/fs/operations.go:1419 +0x16c
github.com/ncw/rclone/cmd/dedupe.glob..func1.1(0x0, 0xe58080)
        /home/travis/gopath/src/github.com/ncw/rclone/cmd/dedupe/dedupe.go:114 +0x3f
github.com/ncw/rclone/cmd.Run(0xc420170000, 0x13ab760, 0xc420603ce0)
        /home/travis/gopath/src/github.com/ncw/rclone/cmd/cmd.go:244 +0x8c
github.com/ncw/rclone/cmd/dedupe.glob..func1(0x13ab760, 0xc420175880, 0x1, 0x4)
        /home/travis/gopath/src/github.com/ncw/rclone/cmd/dedupe/dedupe.go:115 +0xde
github.com/ncw/rclone/vendor/github.com/spf13/cobra.(*Command).execute(0x13ab760, 0xc4201757c0, 0x4, 0x4, 0x13ab760, 0xc4201757c0)
        /home/travis/gopath/src/github.com/ncw/rclone/vendor/github.com/spf13/cobra/command.go:651 +0x23a
github.com/ncw/rclone/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x13aa220, 0xc4201c6af0, 0x0, 0x0)
        /home/travis/gopath/src/github.com/ncw/rclone/vendor/github.com/spf13/cobra/command.go:726 +0x339
github.com/ncw/rclone/vendor/github.com/spf13/cobra.(*Command).Execute(0x13aa220, 0x0, 0x20)
        /home/travis/gopath/src/github.com/ncw/rclone/vendor/github.com/spf13/cobra/command.go:685 +0x2b
main.main()
        /home/travis/gopath/src/github.com/ncw/rclone/rclone.go:15 +0x31

**Comment by captainswain** [comment]
I have encountered the same issues.

**Comment by ncw** [comment]
I'm not sure exactly what is going on here :-(

It looks like dstDir in drive/drive.go  MergeDirs is nil.  I can't think how that can happen!

How repeatable is this?  If I send you an rclone with lots of debugging code can you run it for me?

**Comment by josiah2009** [comment]
I diagnosed it as only occurring when the patch request fails on the first try due to 403 or similar. This seems to be due to f.svc.Files.Patch returning nil and overwriting the info value.
I was able to just ignore the info result on drive.go#L754 and I have yet to have any errors after running it on my full gdrive. I have submitted a pull request with my changes.

**Comment by ncw** [comment]
Thanks for your fix - I'm going to close this now.
