### ISSUE TITLE
Should be possible to suppress case sensitivity warnings

### ISSUE THREAD

**Issue by jikamens** [ncw/rclone#1622]
> What is your rclone version (eg output from `rclone -V`)

v1.35-DEV

> Which OS you are using and how many bits (eg Windows 7, 64 bit)

Ubuntu 17.04 64-bit

> Which cloud storage system are you using? (eg Google Drive)

Backblaze B2

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

rclone sync

> A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

```
2017/08/24 11:43:55 [elided]: Warning: File found with same name but different case on Encrypted B2 bucket [elided] path [elided]/
```

These warnings don't matter to me, since both Linux and Backblaze B2 are case-sensitive. I don't want to see them. There should be a command-line flag to suppress them.

**Comment by breunigs** [comment]
I agree, it does seem surprising to see this message on your B2+Linux combo. I skimmed over the code and it looks like the `readFilesMap` and `readFilesMaps` methods could be adapted to check if either source or destination are case insensitive and only then show the message. Although that code also does Unicode normalization, which might be useful to keep. 

As an immediate workaround something like `rclone sync … | grep -v "File found with same name but different case on"` should do. Alternatively, are you interested in providing a patch?

**Comment by jikamens** [comment]
>Alternatively, are you interested in providing a patch?

I wish I had time to hack on this, but considering I just had to spend several days rebuilding my family's backup infrastructure after CrashPlan announced it was closing up shop on its Home product, I don't think I can spare any more time right now. Sorry.

**Comment by ncw** [comment]
I think if you try 1.37 or [the latest beta](https://beta.rclone.org) then it won't do this any more.

**Comment by jikamens** [comment]
Apparently so, thanks.
