### ISSUE TITLE
Deploying a Static Site from Travis

### ISSUE THREAD

**Issue by knpwrs** [ncw/rclone#1628]
Is there an effective way to deploy a static site to S3 from Travis using rclone? I'd like to `sync` (modify destination only) to an S3 bucket from Travis without having to go through the `config` command first. Ideally configuration would be done with environment variables.

**Comment by pskuza** [comment]
You can include a already configured .rclone.conf or have some sort of script read travis.yml variables and create a valid .rclone.conf file from it.

Either way, encrypt the file or env variables of course. See https://docs.travis-ci.com/user/encrypting-files/ and https://docs.travis-ci.com/user/encryption-keys/

**Comment by knpwrs** [comment]
Cool, thanks!
