### ISSUE TITLE
Instructions on finding duplicates - code or pseudo-code?

### ISSUE THREAD

**Issue by CottonEaster** [ncw/rclone#1629]
It seems unclear whether

`rclone lsl drive:dupes`

on

https://rclone.org/commands/rclone_dedupe/

is code or pseudo-code. Certainly I can't get it to run as code.

**Comment by breunigs** [comment]
`rclone lsl drive:dupes` is an example. Namely, it runs command `lsl` (https://rclone.org/commands/rclone_lsl/) on a remote named `drive` for folder `dupes`. 

In the next block, rclone is invoked like this: `rclone dedupe drive:dupes` is executed – which runs command `dedupe` ona remote named `drive` for folder `dupes`.

Makes sense?

**Comment by CottonEaster** [comment]
Ah, my mistake, then. I failed to realise that 'dupes' - without a slash - could be a folder name. Rather I thought that what we had here was a special command, even though, as you point out, the `lsl` command exists and is documented.
