### ISSUE TITLE
support for mega.nz

### ISSUE THREAD

**Issue by hachre** [ncw/rclone#163]
none of the mega open source sync clients do actual syncing... therefore it would be nice to have mega support in rclone :)

**Comment by ncw** [comment]
There looks to be quite a complete [go library](https://github.com/t3rm1n4l/go-mega) which is promising!

**Comment by HeroCC** [comment]
+1, I use Mega for a few backups since it gives 50GB free, and it would be nice if rclone supported it.

**Comment by sacasumo** [comment]
+1

**Comment by giulianozorzi** [comment]
+1 that would be awesome !

**Comment by 15siegela** [comment]
+1 I have a lot of content on mega and it's encrypted by default.

**Comment by kiwiapple87** [comment]
+1

**Comment by gaenserich** [comment]
+1

**Comment by rauar** [comment]
+1

**Comment by ricary37** [comment]
free space GB/upload speed MB/SEC/download speed MB/SEC:
mega.nz 50/2/8
hubic 25/1/1.2
so mega.nz should be added :)

**Comment by h4y44** [comment]
+1

**Comment by bonyboy** [comment]
+1

**Comment by ase1116** [comment]
+1

**Comment by ase1116** [comment]
FYI
https://www.reddit.com/r/linux/comments/5qmqgi/mega_disclosing_the_source_code/

**Comment by beigexperience** [comment]
Yes please

**Comment by rif** [comment]
+1

**Comment by PaceyIV** [comment]
+1
SDK of the mega service is available here https://github.com/meganz/sdk

**Comment by apasotti** [comment]
+1

**Comment by rivman** [comment]
+1 
Please

**Comment by dessant** [comment]
Yes, please use the thumbs up button instead.

**Comment by espindula** [comment]
+1

**Comment by TechJennings** [comment]
I would love this :) 3+TB on mega and having this feature would make migration so much easier

**Comment by niranjanshr13** [comment]
Online Service to added: mega.nz

Found this awesome github repo: "https://github.com/t3rm1n4l/go-mega"

It is written in go, and all the basic functionality of rclone is already made; hope you can create a wrapper for it.

**Comment by extensionsapp** [comment]
+1

**Comment by TimZander** [comment]
+1

**Comment by chmercesmoreira** [comment]
+1

**Comment by dogear42** [comment]
+1

**Comment by ddomingues1970** [comment]
+1

**Comment by Lillecarl** [comment]
There's already a fuse mount for MEGA here: https://github.com/matteoserva/MegaFuse (Which could be ported to Go & rclone so we get the awesome featureset of rclone and the familiar (and really great) config system and known commandset for sync, copy etc...

The fact that there's already a FUSE mount is great, then we can determine how the API is to be used for FUSE mounting already :)

**Comment by ardhipoetra** [comment]
+1 for mega support

**Comment by AlTech98** [comment]
+1

**Comment by yashodhank** [comment]
+1

**Comment by acs-ferreira** [comment]
+1

**Comment by Toontje** [comment]
+1

**Comment by dessant** [comment]
@ncw, could you please clean up the thread, or lock it?

**Comment by chmercesmoreira** [comment]
@dessant Why don't you just unsubscribe from this thread?

**Comment by dessant** [comment]
@chmercesmoreira, because I am interested in the feature, and its progress.

**Comment by chmercesmoreira** [comment]
@dessant Good point.

**Comment by sudhanshu502** [comment]
Please add mega support.

**Comment by oddmean** [comment]
Well, guys, should I wait or nobody just cares about mega.nz support? That'll be just great!

**Comment by ncw** [comment]
I have been working on mega.nz support - I'm planning to get it into 1.40, but I'll post a beta here in a week or two.

I have taken over maintainership of the go library so I can put the features rclone needs into it.  I have a working remote now, but it needs some work doing before I can send it out to test.

**Comment by afarazit** [comment]
Is there an update for this?

**Comment by ncw** [comment]
@afarazit after 1.39 is released I'll post a beta for people to try

**Comment by gerardo-junior** [comment]
Is there any stable build already with this feature?

**Comment by KonradHolubek** [comment]
+1 ... any update on this ?

**Comment by michael3F** [comment]
+1

**Comment by Decxcraft** [comment]
+1...Any news?

**Comment by bobrooney** [comment]
+1

**Comment by avigard** [comment]
It is not worth the hassle anymore. When you sign up to MEGA you will get 50gb, but after 30 days you will lose 35GB of it. For more information look here:

https://www.reddit.com/r/megalinks/comments/6ehzhl/meta_mega_moving_away_from_50gb_free_storage_to/

**Comment by maxisme** [comment]
@avigard ridiculous - why don't they just offer 15GB... Any ideas what happens if you upload a 50GB file? Lol.

**Comment by Snehvide** [comment]
@avigard @maxisme Nonsense. It's still 15 GB, which is more than starting 2 GB on Dropbox. It's still 50 GB for old account owners, i.e. probably _most of them_. And that's only for _free_. It's not like paid customers magically can't use rclone, or wouldn't want to.

I'd be very happy to see Mega support in rclone.

**Comment by spvkgn** [comment]
+1

**Comment by ncw** [comment]
Here is the first beta of a backend for rclone with mega.nz support.

Here are [the docs for the mega backend](https://github.com/ncw/rclone/blob/mega/docs/content/mega.md).

This uses the [go-mega](https://github.com/t3rm1n4l/go-mega) library which I've become a maintainer for.  I've fixed it up for use with rclone.  The mega protocol is undocumented save for their open source C++ program (which isn't easy to follow!) so I expect there are many bugs in the backend.  It does, however, pass all of rclone's integration tests.

If anyone would like to test, please feel free.  If you find a bug, probably better to open a separate issue with instructions on how I can reproduce the problem and and a log.

I'm aiming to merge this in time for the 1.41 release (due at the end of April) if there aren't too many problems with it!

https://beta.rclone.org/v1.40-064-gce770478-mega/

**Comment by ncw** [comment]
Here is the next version of the code - fixes
  * corrupted uploads when setting --transfers high
  * creating multiple directories
  * opening too many sockets
  * lots of races!

https://beta.rclone.org/v1.40-071-g681edcdb-mega/ (uploaded in 15-30 mins)

**Comment by ncw** [comment]
I've merged this to master here

https://beta.rclone.org/v1.40-093-g1f255a85/ (uploaded in 15-30 mins)

and it will be in [the latest beta](https://beta.rclone.org) from now on and in the 1.41 release!

**Comment by ncw** [comment]
I'm going to close this issue now :-)  If anyone finds any bugs, please make a new issue - thanks.
