### ISSUE TITLE
B2 server-side versioning renames and rclone filename encryption incompatible

### ISSUE THREAD

**Issue by keithgh1** [ncw/rclone#1632]
When you have B2 "lifecycle settings" set to include versioning, and you upload a new file in the same directory, with the same filename, then the B2 server automatically renames the older file to include a date and time stamp.

The documented behavior is here

https://www.backblaze.com/b2/docs/file_versions.html

and

https://www.backblaze.com/b2/docs/lifecycle_rules.html (describes which versions to keep etc)

Due to the filenames being encrypted locally by rclone prior to uploading, this automatic, server-side renaming of older versions causes the associated filenames to be a mix of ciphertext and a plaintext date/time stamp.

The exact format used by BackBlaze is TBD. I don't have that information easily available.

When rclone attempts to decrypt this now-modified filename, the decryption fails and rclone throws an error (visible with more verbose debugging enabled) saying that the file has an "invalid filename" and skips processing this file.

Ideally, rclone could identify when a B2 encrypted remote, using filename encryption, with B2 versioning enabled server-side, sees an "invalid filename", could have an additional decryption attempt, by properly parsing the now-modified filename into two parts. The first part, the original encrypted filename, could run through the decryption process normally. The second part, the date/time stamp, would be appended onto the original plaintext filename (result of part1 decryption)

This would allow rclone filename encryption and B2 versioning to work together.

This issue is being filed per ncw. Some discussion is in this thread https://forum.rclone.org/t/backblaze-b2-humming-along-as-a-replacement-for-acd/2580/25

**Comment by ncw** [comment]
Someone beat you to making the issue !  Can you add your info to #1627 please?

BTW it is rclone that makes the filenames with suffixes - not b2.  I just get a load of files with the same name but different timestamps from the b2 API.

**Comment by keithgh1** [comment]
Alright copied a slightly modified version of this to #1627, and closed this as a dupe. Thanks.
