### ISSUE TITLE
--no-local-unicode-normalization or --local-no-unicode-normalization?

### ISSUE THREAD

**Issue by d--j** [ncw/rclone#1633]
The [documentation](https://github.com/ncw/rclone/blob/master/docs/content/local.md#--no-local-unicode-normalization) calls the flag `--no-local-unicode-normalization` but the [source code ](https://github.com/ncw/rclone/blob/master/local/local.go#L27) (and thus the CLI usage help) calls the flag `--local-no-unicode-normalization`.

One of them should be changed so that source code and documentation are in sync.  
I think `--no-local-unicode-normalization` makes more sense and is more consistent with the other flags (e.g. `--no-update-modtime` or `--no-gzip-encoding`) but that would be a breaking change.

**Comment by ncw** [comment]
Well spotted!

I think we'll have to fix the docs.  The `--local` prefix indicates that this flag only works with the local file system and that is probably more important to have that first.

Fancy sending a PR?
