### ISSUE TITLE
Add --min-atime/--max-atime filters

### ISSUE THREAD

**Issue by ei-grad** [ncw/rclone#1634]
Though it is currently possible to use `find -atime +N` + `rclone --files-from` combination to get such behaviour, it would be very convinient to have this filters right in rclone.

Why someone could need to filter files with atime? It was a question for me too, before I found this in mount(8) man page `relatime` section:

> Since Linux 2.6.30, the file's last access time is always updated if it is more than 1 day old.

http://man7.org/linux/man-pages/man8/mount.8.html

**Comment by ncw** [comment]
Unfortunately rclone doesn't have the concept of atime as it isn't supported by cloud providers, only of mtime.

The filtering would have to work in the local module which I don't really want to do as none of the other modules do filtering (they are supposed to be dumb interfaces to the cloud storage systems).

**Comment by ei-grad** [comment]
Sounds fair enought. Will just continue to use rclone with `find` for local atime filtering :).
