### ISSUE TITLE
There should be a way to log REST API calls

### ISSUE THREAD

**Issue by jikamens** [ncw/rclone#1638]
I'm trying to figure out what rclone is doing that's consuming a lot of class C B2 transactions, but I can't, because as far as I can tell (and I've delved into the source code to check), there's no way to tell rclone to log the individual requests that it sends to B2.

More generally, it seems to me like rest/rest.go should generally have support for logging requests when some reasonably high verbosity level is requested by the user.

**Comment by ncw** [comment]
For logging you want `-vv` with `--dump-bodies` or `--dump-headers`

And to reduce the class C transactions with B2, try `--fast-list`.

**Comment by jikamens** [comment]
I should have found this. Sorry to bug you. :-/
