### ISSUE TITLE
--ignore-size doesn't work with check

### ISSUE THREAD

**Issue by sjb1024** [ncw/rclone#1643]
When using the check command, --ignore-size appears not to work.

rclone v1.37

Confirmed by ncw by looking at source (see https://forum.rclone.org/t/issue-with-ignore-size-when-using-check/3749)

**Comment by ncw** [comment]
Not sure when this crept in.  It is because check no longer calls the `equal` function...

Easy to fix though...

Please try this beta and re-open if it doesn't work for you!

https://beta.rclone.org/v1.37-116-gcbea0602/ (uploaded in 15-30 mins)

(I expect it will say hash mis-match now, but I'm not 100% sure)

**Comment by sjb1024** [comment]
Hi, this doesn't seem to be working for me - still getting ERROR lines with "Sizes differ".  Am using the exact command I use with sync (including --ignore-sizes) but just replacing sync with check.

I'm using the osx-amd64 build.

**Comment by ncw** [comment]
Can you post a log with `-vv` please?

**Comment by sjb1024** [comment]
[for-1643.txt](https://github.com/ncw/rclone/files/1270195/for-1643.txt)

Attached.

**Comment by ncw** [comment]
I see from the log that you are still using 1.37? Double check with `rclone version`.  Have you got both on your path maybe?

    2017/09/01 13:32:12 DEBUG : rclone: Version "v1.37" starting with parameters ...

**Comment by sjb1024** [comment]
Dammit - sorry I'd thought it was using the one in the current directory but it was using one from the path.  As you suggested originally, there's hash mismatches now.  See new log.
[for-1643-2.txt](https://github.com/ncw/rclone/files/1270273/for-1643-2.txt)

**Comment by ncw** [comment]
Glad it is working.

Not sure what I can do about the hash mis-matches - Onedrive did change your image by the look of it.  Can you download a few of the images with errors and see whether onedrive did actually change them or it is reporting the hash wrong?

**Comment by sjb1024** [comment]
Yes, I think OneDrive has messed with the images - the sizes of those files when you download them don't quite match the original.  Not sure why it's just happening with some files.     Why doesn't the same command with sync pick up the hash differences?  Is sync ignoring the has when --ignore-size is used?  I'd expect check and sync to find the same results - or am I missing something?

**Comment by ncw** [comment]
> Why doesn't the same command with sync pick up the hash differences? Is sync ignoring the has when --ignore-size is used? I'd expect check and sync to find the same results - or am I missing something?

`check` always checks hashes, whereas `sync` will only check hashes if the modification times are identical or you used the `--checksum` flag.

**Comment by ncw** [comment]
I'm going to close this as i think it is done now.
