### ISSUE TITLE
Verbose : human-readable values

### ISSUE THREAD

**Issue by AntoineGR** [ncw/rclone#165]
When running, rclone will periodically output a report :

```
Transferred:   11435486519 Bytes (8856.65 kByte/s)
Errors:                 0
Checks:                 0
Transferred:         1028
Elapsed time:     21m0.9s
```

Although very precise the "Bytes" unit is not very user friendly.
I could be great to have an option to output MBytes or GBytes values instead.
(rsync uses the "-h" argument for that)

**Comment by ncw** [comment]
Good idea!  Easy to do. How about something like the output of `rclone size` ?

```
Total size: 563.957G (605543949787 bytes)
```

**Comment by AntoineGR** [comment]
Very good, both readable and precise.
Then maybe split the average transfer rate on another line to be easy on the user's eyes (big numbers are tiring ahah)

    Transferred:   78.049 GB (78049487453 Bytes)
    Average rate :  7.3 MB/s (7258.43 KByte/s)
    Errors:                 0
    Checks:                 0
    Transferred:         9576
    Elapsed time:   2h55m0.9s

**Comment by AntoineGR** [comment]
By the way, it seems like Rclone is pretty stable ;)
![rclone](https://cloud.githubusercontent.com/assets/2418938/10427302/d3b7769a-70e8-11e5-8b10-dbd137c06833.jpg)
(almost 2TB over 3 days, without a single error)

**Comment by ncw** [comment]
@AntoineGR excellent news!

**Comment by xerrni** [comment]
@ncw 
It`s already implemented.

**Comment by ncw** [comment]
@xerrni  well spotted!  We now have transfers which look like this

```
Transferred:   663.606 MBytes (224.676 MBytes/s)
Errors:                 0
Checks:                 0
Transferred:        12749
Elapsed time:        2.9s
```
