### ISSUE TITLE
Large B2 transfer starts over from scratch after b2_upload_part fails?

### ISSUE THREAD

**Issue by jikamens** [ncw/rclone#1656]
Either rclone restarted a large backup from scratch after uploading many GB of it because a single request failed, without retrying the failed request, or it's lying about the percentage complete the upload is and how long it's going to take to finish it in the logging it's doing after the failed request.

Neither of these is a good option. :-/

Note: this is a crypt destination on top of a B2 bucket (as the name implies).

```
2017/09/03 21:42:45 INFO  : 
Transferred:   8.623 GBytes (2.132 MBytes/s)
Errors:                 0
Checks:                12
Transferred:            0
Elapsed time:    1h9m1.6s
Transferring:
 *                 filename-elided.tar.bz2: 20% done, 1.880 MBytes/s, ETA: 5h9m27s

2017/09/03 21:43:17 ERROR : filename-elided.tar.bz2: Failed to copy: Post https://pod-000-1042-11.backblaze.com/b2api/v1/b2_upload_part/id-elided/0004: net/http: HTTP/1.x transport connection broken: http: ContentLength=100663336 with Body length 99938772
2017/09/03 21:43:17 ERROR : Encrypted drive 'B2-encrypted:archives/': not deleting files as there were IO errors
2017/09/03 21:43:17 ERROR : Encrypted drive 'B2-encrypted:archives/': not deleting directories as there were IO errors
2017/09/03 21:43:17 ERROR : Attempt 1/3 failed with 1 errors and: Post https://pod-000-1042-11.backblaze.com/b2api/v1/b2_upload_part/id-elided/0004: net/http: HTTP/1.x transport connection broken: http: ContentLength=100663336 with Body length 99938772
2017/09/03 21:43:17 INFO  : Encrypted drive 'B2-encrypted:archives/': Waiting for checks to finish
2017/09/03 21:43:17 INFO  : Encrypted drive 'B2-encrypted:archives/': Waiting for transfers to finish
2017/09/03 21:43:45 INFO  : 
Transferred:   8.998 GBytes (2.193 MBytes/s)
Errors:                 0
Checks:                24
Transferred:            0
Elapsed time:   1h10m1.6s
Transferring:
 *                 filename-elided.tar.bz2:  0% done, 67.783 MBytes/s, ETA: 10m39s

2017/09/03 21:44:45 INFO  : 
Transferred:   8.998 GBytes (2.162 MBytes/s)
Errors:                 0
Checks:                24
Transferred:            0
Elapsed time:   1h11m1.6s
Transferring:
 *                 filename-elided.tar.bz2:  0% done, 1.240 MBytes/s, ETA: 9h42m57s

2017/09/03 21:45:45 INFO  : 
Transferred:   9.092 GBytes (2.154 MBytes/s)
Errors:                 0
Checks:                24
Transferred:            0
Elapsed time:   1h12m1.6s
Transferring:
 *                 filename-elided.tar.bz2:  1% done, 164.905 kBytes/s, ETA: 74h37m29s
```

**Comment by ncw** [comment]
> Either rclone restarted a large backup from scratch after uploading many GB of it because a single request failed, without retrying the failed request

If you want to see the retries rclone does then you need to supply the `-vv` flag.

It looks from your log that rclone did indeed abandon the upload :-(  rclone tries to classify errors into stuff worth retrying (eg 500 Internal Server error) and stuff not worth retrying (like 400 bad arguments).

I just had a look through the go source and that error is reported as a plain error from the http transport code which means rclone will classify it as a fatal error and abort the upload.

Now this is clearly a mistake - rclone should have retried that error however the http layer didn't give it any clues.

I'll put a special case in for this error in the handling code.

**Comment by ncw** [comment]
In #1660 I added a lot more error types which will retry properly and I think it should fix this problem.

I'm going to close this ticket - please re-open if you are still having problems.
