### ISSUE TITLE
Implement the sync/copy/move directory-per-directory operation on check/cryptcheck so as to avoid running out of memory when processing very large dirtrees

### ISSUE THREAD

**Issue by DurvalMenezes** [ncw/rclone#1657]
> When filing an issue, please include the following information if possible as well as a description of 
> the problem.  Make sure you test with the latest beta of rclone.
>
>    https://beta.rclone.org/
>    https://rclone.org/downloads/

Tested with rclone v1.37 and v1.37-104-ge96c5b5f.

> If you've just got a question or aren't sure if you've found a bug then please use the [rclone forum]
> (https://forum.rclone.org/) instead of filing an issue.

This started as a topic on the forum, see https://forum.rclone.org/t/rclone-cryptcheck-running-out-of-memory/3650

> What is your rclone version (eg output from `rclone -V`)

See above. 

> Which OS you are using and how many bits (eg Windows 7, 64 bit)

Linux, Devuan 1.0.0 Jessie, amd64.

> Which cloud storage system are you using? (eg Google Drive)

Encrypted Google Drive. 

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

rclone cryptcheck /REDACTED egd:REDACTED

> A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

See forum topic linked above.

**Comment by ncw** [comment]
As I wrote in the forum I've made a beta with an initial (not merged to master) version of this here

https://pub.rclone.org/v1.37-120-g08217c79-sync-refactorβ/

**Comment by ncw** [comment]
I've merged this to master now - please re-open if you find any problems.

https://beta.rclone.org/v1.37-149-g4ac9a650/ (uploaded in 15-30 mins)
