### ISSUE TITLE
Expired authorisation tokens with Backblaze B2 large file uploads 

### ISSUE THREAD

**Issue by eodrap** [ncw/rclone#1660]
> What is your rclone version (eg output from `rclone -V`)

2017/09/04 13:21:47 DEBUG : rclone: Version "v1.37" starting with parameters ["rclone" "--fast-list" "--verbose" "--verbose" "--buffer-size=256M" "--checkers=64" "--transfers=32" "--b2-chunk-size=256M" "--b2-upload-cutoff=256M" "copy" "/Volumes/xxx/xxx.tar.gz" "crypt_backblaze:xxx/"]

> Which OS you are using and how many bits (eg Windows 7, 64 bit)

macOS 10.12.6 running on a MacBook Pro 11,3 (late 2013)

> Which cloud storage system are you using? (eg Google Drive)

Backblaze B2 with crypt (standard filename encryption, underlying remote includes a path (backblaze:bucket))

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

rclone copy xxx.tar.gz crypt_backblaze:xxx/

Where xxx.tar.gz is a ~200GB file on a VeraCrypt whole disk encryption USB 3.0 volume.
Where xxx/ is an existing folder in the crypt bucket.
See above for parameters used.

> A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

A large file / chunked copy operation has failed after running for ~27 hours. The logs show that some chunks began to fail after 24 hours with the B2 response 401 expired_auth_token. Other chunks uploaded after the first B2 401 response were successfully uploaded. Eventually a B2 500 internal_error response was received which triggered a low level retry cycle from rclon. This failed with a broken pipe and the operation was retried, my internet connection did not drop (router shows continuous DSL uptime with no errors recorded).

I've previously used the same version of rclone and parameters to upload a similar size archive. This worked fine. I'm not sure if this is the same underlying issue fixed in rclone v1.36 (ticket #825) which explains the B2 401 responses, or an example of B2 API rate limiting which may explain the B2 500 responses and broken pipe. Let me know if you need anything else, and thanks for all your hard work with rclone. It makes (encrypted) cloud storage straightforward. Logs below -

```
2017/09/05 14:18:54 DEBUG : xxx: Done sending chunk 475
2017/09/05 14:18:55 DEBUG : xxx: Sending chunk 511 length 268435456
2017/09/05 14:18:55 DEBUG : xxx: Didn't find object to account part transfer
2017/09/05 14:18:55 DEBUG : B2 bucket xxx path xxx/: Unauthorized: Authorization token has expired (401 expired_auth_token)
2017/09/05 14:18:56 DEBUG : xxx: Clearing part upload URL because of error: Authorization token has expired (401 expired_auth_token)
2017/09/05 14:18:56 DEBUG : pacer: Rate limited, increasing sleep to 20ms
2017/09/05 14:18:56 DEBUG : pacer: low level retry 1/10 (error Authorization token has expired (401 expired_auth_token))
2017/09/05 14:18:56 DEBUG : xxx: Sending chunk 511 length 268435456
2017/09/05 14:18:56 DEBUG : pacer: Reducing sleep to 10ms
2017/09/05 14:18:56 DEBUG : xxx: Didn't find object to account part transfer

2017/09/05 14:25:31 DEBUG : xxx: Done sending chunk 491
2017/09/05 14:25:32 DEBUG : xxx: Sending chunk 513 length 268435456
2017/09/05 14:25:32 DEBUG : xxx: Didn't find object to account part transfer
2017/09/05 14:25:39 DEBUG : xxx: Done sending chunk 473
2017/09/05 14:25:43 DEBUG : xxx: Sending chunk 514 length 268435456
2017/09/05 14:25:43 DEBUG : xxx: Didn't find object to account part transfer
2017/09/05 14:25:43 DEBUG : B2 bucket xxx path xxx/: Unauthorized: Authorization token has expired (401 expired_auth_token)
2017/09/05 14:25:44 DEBUG : xxx: Clearing part upload URL because of error: Authorization token has expired (401 expired_auth_token)
2017/09/05 14:25:44 DEBUG : pacer: Rate limited, increasing sleep to 20ms
2017/09/05 14:25:44 DEBUG : pacer: low level retry 1/10 (error Authorization token has expired (401 expired_auth_token))
2017/09/05 14:25:44 DEBUG : xxx: Sending chunk 514 length 268435456
2017/09/05 14:25:45 DEBUG : pacer: Reducing sleep to 10ms
2017/09/05 14:25:45 DEBUG : xxx: Didn't find object to account part transfer

2017/09/05 14:29:14 DEBUG : xxx: Done sending chunk 478
2017/09/05 14:29:14 DEBUG : xxx: Sending chunk 515 length 268435456
2017/09/05 14:29:14 DEBUG : xxx: Didn't find object to account part transfer
2017/09/05 14:29:15 DEBUG : B2 bucket xxx path xxx/: Unauthorized: Authorization token has expired (401 expired_auth_token)
2017/09/05 14:29:16 DEBUG : xxx: Clearing part upload URL because of error: Authorization token has expired (401 expired_auth_token)
2017/09/05 14:29:16 DEBUG : pacer: Rate limited, increasing sleep to 20ms
2017/09/05 14:29:16 DEBUG : pacer: low level retry 1/10 (error Authorization token has expired (401 expired_auth_token))
2017/09/05 14:29:16 DEBUG : xxx: Sending chunk 515 length 268435456
2017/09/05 14:29:16 DEBUG : pacer: Reducing sleep to 10ms
2017/09/05 14:29:16 DEBUG : xxx: Didn't find object to account part transfer
2017/09/05 14:29:42 DEBUG : xxx: Done sending chunk 477
2017/09/05 14:29:43 DEBUG : xxx: Sending chunk 516 length 268435456
2017/09/05 14:29:43 DEBUG : xxx: Didn't find object to account part transfer
2017/09/05 14:29:43 DEBUG : B2 bucket xxx path xxx/: Unauthorized: Authorization token has expired (401 expired_auth_token)
2017/09/05 14:29:44 DEBUG : xxx: Clearing part upload URL because of error: Authorization token has expired (401 expired_auth_token)
2017/09/05 14:29:44 DEBUG : pacer: Rate limited, increasing sleep to 20ms
2017/09/05 14:29:44 DEBUG : pacer: low level retry 1/10 (error Authorization token has expired (401 expired_auth_token))
2017/09/05 14:29:44 DEBUG : xxx: Sending chunk 516 length 268435456
2017/09/05 14:29:45 DEBUG : pacer: Reducing sleep to 10ms
2017/09/05 14:29:45 DEBUG : xxx: Didn't find object to account part transfer
2017/09/05 14:29:46 DEBUG : B2 bucket xxx path xxx/: Setting sleep to 1s after error: c001_v0001044_t0004 is too busy (503 service_unavailable)
2017/09/05 14:29:46 DEBUG : xxx: Clearing part upload URL because of error: c001_v0001044_t0004 is too busy (503 service_unavailable)
2017/09/05 14:29:46 DEBUG : pacer: Rate limited, increasing sleep to 1s
2017/09/05 14:29:46 DEBUG : pacer: low level retry 2/10 (error c001_v0001044_t0004 is too busy (503 service_unavailable))
2017/09/05 14:29:46 DEBUG : xxx: Sending chunk 516 length 268435456
2017/09/05 14:29:47 DEBUG : pacer: Reducing sleep to 500ms
2017/09/05 14:29:47 DEBUG : xxx: Didn't find object to account part transfer

2017/09/05 14:30:35 DEBUG : pacer: Reducing sleep to 250ms
2017/09/05 14:30:35 DEBUG : xxx: Done sending chunk 496
2017/09/05 14:30:36 DEBUG : xxx: Sending chunk 517 length 268435456
2017/09/05 14:30:36 DEBUG : xxx: Didn't find object to account part transfer

2017/09/05 17:32:44 DEBUG : xxx: Clearing part upload URL because of error: Interrupted (500 internal_error)
2017/09/05 17:32:44 DEBUG : pacer: Rate limited, increasing sleep to 20ms
2017/09/05 17:32:44 DEBUG : pacer: low level retry 1/10 (error Interrupted (500 internal_error))
2017/09/05 17:32:44 DEBUG : xxx: Sending chunk 578 length 268435456
2017/09/05 17:32:44 DEBUG : xxx: Clearing part upload URL because of error: Interrupted (500 internal_error)
2017/09/05 17:32:44 DEBUG : pacer: Rate limited, increasing sleep to 40ms
2017/09/05 17:32:44 DEBUG : pacer: low level retry 1/10 (error Interrupted (500 internal_error))
2017/09/05 17:32:44 DEBUG : xxx: Sending chunk 548 length 268435456
2017/09/05 17:32:45 DEBUG : pacer: Reducing sleep to 20ms
2017/09/05 17:32:45 DEBUG : xxx: Didn't find object to account part transfer
2017/09/05 17:32:45 DEBUG : pacer: Reducing sleep to 10ms
2017/09/05 17:32:45 DEBUG : xxx: Didn't find object to account part transfer
2017/09/05 17:32:45 DEBUG : xxx: Error sending chunk 581: Post https://pod-000-1044-19.backblaze.com/b2api/v1/b2_upload_part/xxx write tcp 192.168.0.100:55531->206.190.208.170:443: write: broken pipe
2017/09/05 17:32:46 DEBUG : xxx: Sending chunk 586 length 268435456
2017/09/05 17:32:46 DEBUG : xxx: Didn't find object to account part transfer
2017/09/05 17:32:47 DEBUG : xxx: Error sending chunk 586: Post https://pod-000-1044-19.backblaze.com/b2api/v1/b2_upload_part/xxx dial tcp 206.190.208.170:443: getsockopt: connection refused
```

**Comment by ncw** [comment]
Do you have a bit more of that log?  I'd like to see what happened after the "Error sending chunk 586".

It might be that rclone considered the "connection refused" error a fatal error and gave up at that point, I'm not sure from the log.

**Comment by eodrap** [comment]
Thanks very much for the reply, and for fixing my broken formatting in the original post (spotted it but was snowed under after posting).

I've attached the full log below. The second attempt copy operation is at 98% without any other B2 500 responses, however if you look at the logs you can see sporadic B2 401 responses occurring in attempt two. These are being handled by your low level retry code. B2 is also offering plenty of 503 responses when busy. Could it be that when B2 is busy uploads of some chunks slow to ridiculously low speeds (>24 hours per chunk) and the authorisation tokens expire? The existing low level retry mechanism appears to cover this, even if rclone aborted long running chunks and requested a new code the result would be the same (retry the chunk). Would rclone be able to request a new access token mid upload (I suspect not)? This may be a symptom of B2 being busy rather than a problem with rclone, sorry if I'm wasting your time.

Let me know if you need anything else, thanks again.

[rclone.txt](https://github.com/ncw/rclone/files/1284115/rclone.txt)

**Comment by ncw** [comment]
I have fixed these errors here

https://beta.rclone.org/v1.37-139-g798502b2/ (uploaded in 15-30 mins)

Please re-open if it doesn't work or you find more error conditions!
