### ISSUE TITLE
Change the default for --drive-use-trash

### ISSUE THREAD

**Issue by ncw** [ncw/rclone#1661]
For historical reasons the drive backend defaulted to permanent deletion rather than using the trash.

This has caused data loss for users :-(

Change the default and update the documentation accordingly.

**Comment by desimaniac** [comment]
Great feature!

**Comment by ishuah** [comment]
Is anyone working on this issue?

**Comment by desimaniac** [comment]
Yes, the person who created the issue.

**Comment by daylightbrightledlight** [comment]
I agree with @ncw. The default should be changed to trash.

**Comment by ncw** [comment]
I've done this now - please find it here

https://beta.rclone.org/v1.37-140-ge0eabc75/ (uploaded in 15-30 mins)
