### ISSUE TITLE
Dropbox date and time is incorrect via rclone but correct on web interface

### ISSUE THREAD

**Issue by zenjabba** [ncw/rclone#1662]
> What is your rclone version (eg output from `rclone -V`)

rclone v1.37 and rclone 1.37-117-g58f7b4edB

> Which OS you are using and how many bits (eg Windows 7, 64 bit)

linux 64bit

> Which cloud storage system are you using? (eg Google Drive)

dropbox

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

rclone mount

-rw-r--r-- 1 root root 28098354 Aug 30  1754 GLEE - You're Having My Baby (Full Performance) HD.mp4

<img width="1531" alt="screen shot 2017-09-06 at 1 58 54 pm" src="https://user-images.githubusercontent.com/679864/30126941-955d0ba2-930b-11e7-93e5-fecede300623.png">

**Comment by ncw** [comment]
How did you upload the file?

What does `rclone lsl` on the same file say?

**Comment by zenjabba** [comment]
28098354 2017-07-13 20:47:57.000000000 Glee Music Videos/GLEE - You're Having My Baby (Full Performance) HD.mp4

**Comment by khurshid-alam** [comment]
Same here.

**Comment by zenjabba** [comment]
I uploaded via rclone copy from google drive.

**Comment by ncw** [comment]
@zenjabba wrote
> 28098354 2017-07-13 20:47:57.000000000

That looks correct, so it is just rclone mount that seems to be wrong...  Can you give me your command line for mount please?

Also can you try stopping the mount and starting it again, or sending it a SIGHUP to get it to flush its buffer cache to see if that changes it?

**Comment by zenjabba** [comment]
Can confirm no change after both unmounting and remounting and also sending SIGHUP via kill.

**Comment by zenjabba** [comment]
/sbin/rclone-beta mount dropbox:/ /home/thompsons/plexdropbox/ --config /home/thompsons/.rclone.conf --allow-other --no-modtime --dir-cache-time 1m --log-file=/var/log/zenjabbamount-logfile.log -v --read-only

**Comment by ncw** [comment]
You've set `--no-modtime` in there.  Remove that option and it should work.

**Comment by zenjabba** [comment]
Feel like an idiot... fixed

**Comment by ncw** [comment]
@zenjabba no worries!
