### ISSUE TITLE
Rclone shows filenames with certain characters as odd paths

### ISSUE THREAD

**Issue by desimaniac** [ncw/rclone#1663]
Tranfer shows:

```
 2017-09-07 12:33:38,265 - UTILS    -               run_command() :: '2017/09/07 12:33:38 INFO  : TV/Nashville 2012/Season 04/Nashville.2012.S04E09.Three\xe2\x80\x99s.a.Crowd.720p.WEB.h264-SONARR.mkv: Copied (new)'
```

The filepath is 
```
TV/Nashville 2012/Season 04/Nashville.2012.S04E09.Three’s.a.Crowd.720p.WEB.h264-SONARR
```

And it shows the same on Google Drive. So the transfers are going thru ok, just the transfer log shows it as that. 

My info:
rclone 1.37
Ubuntu 16
Google Drive

**Comment by ncw** [comment]
The `\xe2\x80\x99` is the hex code for the UTF-8 character `’` in `Three’s` so that is understandable if a bit weird.

```
>>> u"’"
u'\u2019'
>>> u"’".encode("utf-8")
'\xe2\x80\x99'
>>> 
```

I don't think rclone will have output that though - it will have just output the UTF-8. Did some part of your log processing pipeline escape the non-ascii characters?

**Comment by desimaniac** [comment]
Yeah, it is being saved in a log via a python script. I'll look into that. Thanks.

**Comment by ncw** [comment]
OK.  I'll close this then - please re-open if you find it is something rclone is doing!
