### ISSUE TITLE
Feature request - create sharing links for files

### ISSUE THREAD

**Issue by mstgrv** [ncw/rclone#1677]
It would be amazing if rclone could generate sharing links for applicable remotes (Dropbox, Google Drive, Box, etc.).

Obviously couldn’t be done with encrypted remotes, but for files on unencrypted remotes that support generating URLs to share files with other people, it would be awesome to be able to do this directly from rclone.

**Comment by breunigs** [comment]
Good feature request. I think it might already being worked on in #1562 , so please take a look there.
