### ISSUE TITLE
Support for "limited" filesizes on cloud providers

### ISSUE THREAD

**Issue by zenjabba** [ncw/rclone#1678]
Can we have an option to "support" limited filesize cloud drives by having rclone massage the filenames and splitting the files into support sizes and merging them to the rclone mount?

ie, OneDrive supports 15GB max size, getting rclone to split the file into "14GB" chunks and automagically merge them when being pulled down via either rclone ls, rclone copy/move or rclone mount.

**Comment by NumberedThought** [comment]
:thumbsup:  This would greatly help with my workflow

**Comment by hthighway** [comment]
👍 this would definitely increase the usefulness of OneDrive

**Comment by mjf14** [comment]
Yes, as a recent onedrive user this would be great!

**Comment by vuur** [comment]
This would be awesome!

**Comment by martinbowling** [comment]
Omg this would make my day, definitely a much needed feature for onedrive

**Comment by ncw** [comment]
I think this is a duplicate of #497

**Comment by zenjabba** [comment]
Yup, after reading through it, the same option would be great. I was happy with 10GB sizes, but 8kb is fine as well.. the only issue I forsee with tiny files is that lots of small files will cripple some providers.
