### ISSUE TITLE
runtime: failed to create new OS thread (have 2049 already; errno=12) fatal error: runtime.newosproc

### ISSUE THREAD

**Issue by Dave3o3** [ncw/rclone#1683]
with latest macOS beta (`rclone-v1.37-139-g798502b2β-osx-amd64`) on macOS 10.12.6:

I transferred from Dropbox remote to Google Drive:

`rclone copy -c -v dropbox:Folder\ Name gdrive:Folder\ Name`

Got this after 4 hours and 10 GB of transferred data:

```
runtime: failed to create new OS thread (have 2049 already; errno=12)
fatal error: runtime.newosproc
```

stack trace attached 
[stack.txt](https://github.com/ncw/rclone/files/1306713/stack.txt)

**Comment by ncw** [comment]
That trace has 3105 goroutines in it so something is leaking goroutines.

It looks like the 2048 threads are all resolving DNS.  They were all created by

    net.(*Resolver).goLookupIPCNAMEOrder

Is there something weird going on with your DNS?  Do you have a virus checker maybe?  I can't find any reports ot go bugs about this.

Did you leave `--transfers` and `--checkers` at their default value?

**Comment by Dave3o3** [comment]
> Is there something weird going on with your DNS? Do you have a virus checker maybe? I can't find any reports ot go bugs about this.

Yeah, I use Malwarebytes, but had no issues with local-to-remote transfers. I'll retry on another machine.

> Did you leave `--transfers` and `--checkers` at their default value?

yep

**Comment by Dave3o3** [comment]
I'll close this for now because I'll proceed with another migration approach. Had no issues on Debian 9 btw.
