### ISSUE TITLE
feature request: support for cloud@mail.ru

### ISSUE THREAD

**Issue by Dees7** [ncw/rclone#1696]
Please, make [cloud@mail.ru](https://cloud.mail.ru) support.

It may be [helpful](https://github.com/yar229/WebDavMailRuCloud)

**Comment by timofonic** [comment]
@Dees7 There's [CloudCross](/MasterSoft24/CloudCross), a russian project that's somewhat similar to Rclone but done in C++ (but it uses Qt, welcome to bloatland...). It supports far fewer protocols, but Cloud.Mail.Ru is one of them.

**Comment by dmak** [comment]
Can be used as a reference: [MailRu C++ implementation in CloudCross](https://github.com/MasterSoft24/CloudCross/tree/master/ccross-app/src/MailRu).

**Comment by ivandeex** [comment]
duplicate of #591

**Comment by ncw** [comment]
Please see #591 - development is underway there thanks to @ivandeex 

I'll close this so we don't get confused!
