### ISSUE TITLE
feature requested: tab completion; with prototype included.

### ISSUE THREAD

**Issue by niranjanshr13** [ncw/rclone#1697]
Tab completion:
Eg: rclone {TAB}(show all the command from Available Commands) {TAB}(listremotes)  

small prototype:
``` 
_rclone()
{local cur=${COMP_WORDS[COMP_CWORD]};
COMPREPLY=( $(compgen -W "listremotes lsd" -- $cur));
}
```
```
complete -F _rclone rclone
```
So my idea is to make "Avaiable Commands", so sort of distinguish from other. 
Current help page for rclone:

# Available Commands: (current) #
>  authorize       Remote authorization.
  cat             Concatenates any files and sends them to stdout.
  check           Checks the files in the source and destination match.
  cleanup         Clean up the remote if possible
  config          Enter an interactive configuration session.
  copy            Copy files from source to dest, skipping already copied
  copyto          Copy files from source to dest, skipping already copied
  cryptcheck      Cryptcheck checks the integrity of a crypted remote.
  dbhashsum       Produces a Dropbbox hash file for all the objects in the path.
  dedupe          Interactively find duplicate files delete/rename them.
  delete          Remove the contents of path.
  genautocomplete Output bash completion script for rclone.
  gendocs         Output markdown docs for rclone to the directory supplied.
  help            Help about any command
  listremotes     List all the remotes in the config file.
  ls              List all the objects in the path with size and path.
  lsd             List all directories/containers/buckets in the path.
  lsjson          List directories and objects in the path in JSON format.
  lsl             List all the objects path with modification time, size and path.
  md5sum          Produces an md5sum file for all the objects in the path.
  mkdir           Make the path if it doesn't already exist.
  mount           Mount the remote as a mountpoint. **EXPERIMENTAL**
  move            Move files from source to dest.
  moveto          Move file or directory from source to dest.
  ncdu            Explore a remote with a text based user interface.
  obscure         Obscure password for use in the rclone.conf
  purge           Remove the path and all of its contents.
  rmdir           Remove the path if empty.
  rmdirs          Remove empty directories under the path.
  sha1sum         Produces an sha1sum file for all the objects in the path.
  size            Prints the total size and number of objects in remote:path.
  sync            Make source and dest identical, modifying destination only.
  version         Show the version number.

# New "Avaiable Commands"(my way) #
Available Commands:
`**  authorize       Remote authorization.`
`**  cat             Concatenates any files and sends them to stdout.`
`**  check           Checks the files in the source and destination match.`
`**  cleanup         Clean up the remote if possible`
`*  config          Enter an interactive configuration session.`
`**  copy            Copy files from source to dest, skipping already copied`
`**  copyto          Copy files from source to dest, skipping already copied`
`**  cryptcheck      Cryptcheck checks the integrity of a crypted remote.`
`**  dbhashsum       Produces a Dropbbox hash file for all the objects in the path.`
`**  dedupe          Interactively find duplicate files delete/rename them.`
`**  delete          Remove the contents of path.`
`**  genautocomplete Output bash completion script for rclone.`
`**  gendocs         Output markdown docs for rclone to the directory supplied.`
`**  help            Help about any command`
`**  listremotes     List all the remotes in the config file.`
`**  ls              List all the objects in the path with size and path.`
`**  lsd             List all directories/containers/buckets in the path.`
`**  lsjson          List directories and objects in the path in JSON format.`
`**  lsl             List all the objects path with modification time, size and path.`
`**  md5sum          Produces an md5sum file for all the objects in the path.`
`**  mkdir           Make the path if it doesn't already exist.`
`**  mount           Mount the remote as a mountpoint. **EXPERIMENTAL**`
`**  move            Move files from source to dest.`
`**  moveto          Move file or directory from source to dest.`
`**  ncdu            Explore a remote with a text based user interface.`
`**  obscure         Obscure password for use in the rclone.conf`
`**  purge           Remove the path and all of its contents.`
`**  rmdir           Remove the path if empty.`
`**  rmdirs          Remove empty directories under the path.`
`**  sha1sum         Produces an sha1sum file for all the objects in the path.`
`**  size            Prints the total size and number of objects in remote:path.`
`**  sync            Make source and dest identical, modifying destination only.`
`**  version         Show the version number.`

function my bashrc:
```
_rclone()
{ local cur=${COMP_WORDS[COMP_CWORD]}; 
COMPREPLY=( $(compgen -W "$(rclone --help | grep "**" | awk {'print $2'})"  -- $cur));
}
```  
```
complete -F _rclone rclone
```
A small modification to you help page, `"**"`(2 asterisk) in front of "Avaiable Commands".

**Comment by niranjanshr13** [comment]
had to change, because there already asterisk(*), so i thought why not use two "**" to distinguish line.  
you can replace 2 asterisk (**) with any distinguish letter.

**Comment by niranjanshr13** [comment]
there was already "genautocomplete"

**Comment by checktravis** [comment]
I am running

```
rclone v1.43.1
- os/arch: linux/amd64
- go version: go1.11
```

And while I did discover the impressive "genautocomplete" command just this afternoon (thanks for that), I don't think it fulfills this request. I also am interested in seeing the results of "listremotes" when I tab after a command. 

I have already ran `rclone genautocomplete bash` and that gets me half way there, but if I type

```
rclone lsd [TAB]
```


I don't see my remotes, I see a listing of the current working directory.

**Comment by ncw** [comment]
> And while I did discover the impressive "genautocomplete" command just this afternoon (thanks for that), I don't think it fulfills this request. I also am interested in seeing the results of "listremotes" when I tab after a command.
> 
> I have already ran `rclone genautocomplete bash` and that gets me half way there, but if I type
> 
> ```
> rclone lsd [TAB]
> ```
> I don't see my remotes, I see a listing of the current working directory.

Yes I'd like that too...

genautocomplete comes almost for free when using the cobra and pflag libraries.  Here are the cobra docs on how to add extra completion stuff if anyone wants to have a go

https://github.com/spf13/cobra/blob/master/bash_completions.md
