### ISSUE TITLE
When Rclone has Dropbox mounted, warning on move

### ISSUE THREAD

**Issue by zenjabba** [ncw/rclone#1699]
Rclone-Beta 1.37

2017/09/22 20:55:12 WARNING: API `Move` is deprecated
2017/09/22 20:55:12 Use API `MoveV2` instead
2017/09/22 21:09:49 WARNING: API `Move` is deprecated
2017/09/22 21:09:49 Use API `MoveV2` instead
2017/09/22 21:09:52 WARNING: API `Move` is deprecated
2017/09/22 21:09:52 Use API `MoveV2` instead

**Comment by ncw** [comment]
Well spotted - thanks.  Should be easy to fix

**Comment by ncw** [comment]
Hmm, this uncovered a bug in the dropbox SDK which I reported here https://github.com/dropbox/dropbox-sdk-go-unofficial/issues/27 and am fixing here https://github.com/dropbox/dropbox-sdk-go-unofficial/pull/28

**Comment by ncw** [comment]
I've fixed the upstream issue, and fixed the warnings in rclone

https://beta.rclone.org/v1.37-170-g0e76e35b/ (uploaded in 15-30 mins)
