### ISSUE TITLE
how not to copy a specific path

### ISSUE THREAD

**Issue by oliveriojnn** [ncw/rclone#1707]
Today I am running every 5 minutes the following command:

/usr/sbin/rclone copy meudrive:/Storage1/EDITORA/ /srv/Storage1/EDITORA/

But I'd like NOT to COPY files that are within a particular path: meudrive:/Storage1/EDITORA/ILUSTRAS/VIVER VALORES 2017/FUNDAMENTAL

Is there any way to do this?

**Comment by ncw** [comment]
I answered this on the forum so I'm going to close this issue.
