### ISSUE TITLE
dropbox: unable to rename directories via mount command

### ISSUE THREAD

**Issue by hthighway** [ncw/rclone#1708]
rclone v1.37-167-g6f2a6dfbβ
- os/arch: linux/amd64
- go version: go1.9

OS: Ubuntu 16.04
Cloud Provider: Dropbox

Using filebot against an rclone mount of dropbox returns the following error

`2017/09/29 12:21:53 INFO  : Dropbox root '': Modify window is 1s`
`2017/09/29 12:32:16 ERROR : media/Movies/Movie.Name.1999: Dir.Rename error: Error in call to API function "files/get_metadata": request body: path: The root folder is unsupported.`

**Comment by zenjabba** [comment]
Looking at the dropbox API, is the error `media/Movies/Movie.Name.1999` needs to be `/media/Movies/Movie.Name.1999`

**Comment by chienb** [comment]
API endpoints turned off as of yesterday 9/28

https://blogs.dropbox.com/developers/2016/06/api-v1-deprecated/

**Comment by zenjabba** [comment]
rclone beta is using V2 as far as I can tell

**Comment by ncw** [comment]
rclone 1.37 and above support dropbox v2 API.  [I just released v1.38](https://rclone.org/downloads/)

**Comment by ncw** [comment]
@hthighway can you make a reproducer for me of this using standard unix tools, eg `mv XXX YYY`? I'm not sure exactly what filebot does.

**Comment by hthighway** [comment]
Tried using `mv` and got same error in the rclone log 
`2017/09/30 18:56:52 ERROR : media/Movies/Movie.Name.(XXXX): Dir.Rename error: Error in call to API function "files/
get_metadata": request body: path: The root folder is unsupported.`  
and the `mv` command returned 
`mv /mnt/dropbox/media/Movies/movie.name.(XXXX) /mnt/dropbox/media/Movies/new.name
mv: cannot move '/mnt/dropbox/media/Movies/movie.name.(XXXX)' to '/mnt/dropbox/media/Movies/new.name': Input/output error`

**Comment by ncw** [comment]
@hthighway thanks, I managed to reproduce the problem like this

    $ rclone mount -vv dropbox: ~/mnt/tmp/

    $ mv ~/mnt/tmp/test ~/mnt/tmp/test2
    mv: cannot move '/home/ncw/mnt/tmp/test' to '/home/ncw/mnt/tmp/test2': Input/output error

The log giving

    2017/10/02 09:55:02 ERROR : test: Dir.Rename error: Error in call to API function "files/get_metadata": request body: path: The root folder is unsupported.
    2017/10/02 09:55:02 DEBUG : /: >Rename: err=Error in call to API function "files/get_metadata": request body: path: The root folder is unsupported.

Digging in further...

    rclone mount -vv --dump-bodies dropbox: ~/mnt/tmp/

```
2017/10/02 09:57:02 DEBUG : HTTP REQUEST (req 0xc420100200)
2017/10/02 09:57:02 DEBUG : POST /2/files/get_metadata HTTP/1.1
Host: api.dropboxapi.com
User-Agent: rclone/v1.38-009-g6393acf4-pcloud
Content-Length: 107
Authorization: XXXX
Content-Type: application/json
Accept-Encoding: gzip

{"path":"/","include_media_info":false,"include_deleted":false,"include_has_explicit_shared_members":false}
```

```
2017/10/02 09:57:02 DEBUG : HTTP RESPONSE (req 0xc420100200)
2017/10/02 09:57:02 DEBUG : HTTP/1.1 400 Bad Request
Transfer-Encoding: chunked
Connection: keep-alive
Content-Disposition: attachment; filename='error'
Content-Security-Policy: sandbox; frame-ancestors 'none'
Content-Type: text/plain; charset=utf-8
Date: Mon, 02 Oct 2017 08:57:02 GMT
Server: nginx
X-Content-Type-Options: nosniff
X-Dropbox-Request-Id: 7d3515a9eaf822acb9cd056ce2dc7b57
X-Frame-Options: DENY

67
Error in call to API function "files/get_metadata": request body: path: The root folder is unsupported.
0
```

So rclone seems to be calling `get_metadata` on `/` which isn't supported.

**Comment by ncw** [comment]
I've fixed this here - please re-open the issue if you have any problem with it.

https://beta.rclone.org/v1.38-011-gb7521c0f/ (uploaded in 15-30 mins)
