### ISSUE TITLE
Remote names with spaces are unusable

### ISSUE THREAD

**Issue by dustinrc** [ncw/rclone#171]
Being naive and uncreative in my first run with rclone, I named my remote `amazon cloud`. Any attempt to use this remote name results in rclone looking in the current directory on the local filesystem and ending in error. No combination of quotes or backslashes (e.g., `"amazon cloud":`, `amazon\ cloud:`) helped. I am using Bash in OSX. A check/warning at the command line or some note in the documentation would be helpful. Great util, by the way!

**Comment by ncw** [comment]
I would expect them to work with spaces. I'll check out why not shortly!

**Comment by ncw** [comment]
Ah yes I see why!  What I shall do is check new remote names against `fs.matcher` then tell the user the remote name is invalid.  I'll allow spaces too!

**Comment by dustinrc** [comment]
Are you referring to [here](https://github.com/ncw/rclone/blob/6344c3051caf06c3ecd2da5148bd01391ef22b99/amazonclouddrive/amazonclouddrive.go#L118)? So, different remote types could have different rules for names, correct?

**Comment by ncw** [comment]
I've released this in v1.24

Thanks for the report

Nick
