### ISSUE TITLE
Rclone can benefit from storing checksums alongside files in the backup set

### ISSUE THREAD

**Issue by kriston** [ncw/rclone#1714]
> What is your rclone version (eg output from `rclone -V`)
rclone v1.37

> Which OS you are using and how many bits (eg Windows 7, 64 bit)
Ubuntu 16.04.3, 32-bit

> Which cloud storage system are you using? (eg Google Drive)
Backblaze b2 with encryption

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone sync

> A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
n/a

When rclone is using an encryption driver the server-side checksums are not available for comparing whether files need to be updated.  At the current time, checksums are not checked, but file sizes and dates are checked for encrypted stores.

To use the more exact method of comparing checksums with the stored file, the checksum of the file should be stored alongside each file before encryption.  In this way, the rclone --checksum command will work (it does not work otherwise).

Also, when storing checksums in the pre-encryption side of the file store we can benefit from using rclone --checksum --ignore-size --ignore-times to have a true backup.

This avoids silent data corruption when a file that's considered for backup has the same size and time but the entire file contains garbage data.

**Comment by kriston** [comment]
This is mentioned similarly in https://github.com/ncw/rclone/issues/1712.

I have posted comments there to suggest this implementation.

**Comment by ncw** [comment]
> the checksum of the file should be stored alongside each file before encryption. In this way, the rclone --checksum command will work (it does not work otherwise).

You don't want to store the unencrypted checksum as you've given away a decryption crib if you do that.  The checksum would have to be encrypted.

Some schemes for adding metadata have already been proposed in #1337 for example.  It isn't straight forward though as some remotes can store metadata (kind of like a file attribute) but some can't, so to work well it would have to be a file system overlay.  This would enable other things like storing longer file names, splitting big files etc.

I'm going to close issue this in favour of #1712 which if implemented would obviate the need for additional metadata.
