### ISSUE TITLE
corrupted on transfer: sizes differ

### ISSUE THREAD

**Issue by leolivier** [ncw/rclone#1718]
On OneDrive, I get a lot of errors like this one:
```
2017/10/06 05:50:23 ERROR : Photos/2009/San Francisco/San francisco Loulou/Photo0376.jpg: corrupted on transfer: sizes differ 105608 vs 87114
```
with the command:
`rclone -v sync OneDrive:/ /mnt/ssd/data/OneDrive`

If I run the same sync command again, I get exactly the same errors, always on the same files. 
There are two distinct cases with exactly the same error:
- Either, when I look at the file on onedrive, it looks ok. If I download the file from the onedrive website, the file is ok.
- Or the file does not exist on OneDrive (I can't see it on the web site)

I'm using rclone v1.38 on raspbian stretch and on Linux Mint 18 with the same errors on same files.
I tried the latest beta (17/10/02), same...

**Comment by Tgomn92** [comment]
rclone -v sync OneDrive:/ /mnt/ssd/data/OneDrive

**Comment by ncw** [comment]
I suspect this is the same as #454 and #399 for which I implemented the `--ignore-size` option.

For some reason, with some photos, onedrive tells rclone they are one size, but actually they are another size.

Try that and see if it works?

**Comment by leolivier** [comment]
Thanks @ncw , it works with the --ignore-size option.
