### ISSUE TITLE
Swift : purge subdirectory output error

### ISSUE THREAD

**Issue by axtux** [ncw/rclone#172]
Hello,

I get 2 errors when purging a swift subdirectory with :
`$ ./rclone purge swift:container/subdirectory`

First issue, purge doesn't work as is for folders created within swift. ls command doesn't work either. I have to run the command mkdir on the subdirectory before it can be purged.

Second issue, rclone try to delete container. It should not. Here's the output :
> 2015/10/13 03:49:54 Attempt 1/3 failed with 2 errors and: Container Not Empty
> 2015/10/13 03:49:54 Waiting for deletions to finish
> 2015/10/13 03:49:55 Attempt 2/3 failed with 2 errors and: Container Not Empty
> 2015/10/13 03:49:55 Waiting for deletions to finish
> 2015/10/13 03:49:55 Attempt 3/3 failed with 2 errors and: Container Not Empty
> 2015/10/13 03:49:55 Failed to purge: Container Not Empty

EDIT: Those issues seem to be related to the way my Swift provider is managing directories. I get a third issue when using `./rclone sync swift:container/sub local`. Directories in sub are created as 0-byte-files (and I get errors for all files in those directories).

Regards,
Axtux

**Comment by ncw** [comment]
> purge doesn't work as is for folders created within swift. ls command doesn't work either. I have to run the command mkdir on the subdirectory before it can be purged.

How did you originally create the folders.  Can you give an example so I can reproduce the problem?

> 2015/10/13 03:49:54 Attempt 1/3 failed with 2 errors and: Container Not Empty
> 2015/10/13 03:49:54 Waiting for deletions to finish

Yes, I think that is a bug.  It shouldn't be attempting to delete the container if you are using a sub-directory.  The same bug is probably in `s3` and `google cloud storage`!

> EDIT: Those issues seem to be related to the way my Swift provider is managing directories. I get a third issue when using ./rclone sync swift:container/sub local. Directories in sub are created as 0-byte-files (and I get errors for all files in those directories).

That is the old style way of creating pseudo directories in swift.  I thought rclone ignored them, but checking the code apparently it doesn't, so that is probably a bug.

How did you create those directories? Using the swift tool?

Who is your provider? And which version of Swift or Openstack are you using?

Thanks

Nick

**Comment by axtux** [comment]
My provider is Hubic (from OVH) and I'm creating folders from their client. I searched their docs and forum to know how their client is creating folder but didn't find any information about it. I'll try to get more informations from my swift server itself. Currently, Linux swift client refuse to authenticate with my gateway which only support auth v1.0. Do you have any docs about the way folders are created in swift ?

**Comment by ncw** [comment]
Directory Markers are zero-length objects which have the metadata content-type set to "application/directory".

It sounds like that is what the client is creating and rclone isn't ignoring them like it should.

Most clients don't bother creating them though as swift now deals quite well with so called pseudo directories.

**Comment by axtux** [comment]
You're right. I was able to check with Python client and I get those headers : `'content-length': '0'` and `'content-type': 'application/directory'`. Python client is not supporting them neither. I'll try to fix that too.

**Comment by ncw** [comment]
@axtux thanks for confirming that - I'll think about how to fix properly.  It will require an implementation of `Purger` for swift if we filter the 0 length files out...

**Comment by axtux** [comment]
The more I play with it, the more I understand how it works. Swift Python client is only checking that `content-type` equals `text/directory` see https://github.com/openstack/python-swiftclient/blob/master/swiftclient/service.py#L1130 not sure why as my directories have `content-type` set to `application/directory` but it could be useful to check both. I think size could be checked too but at least `content-type` as 0-length files could exist.

IMO, what should be changed :
- purge : don't try to delete container if purging subdirectory
- purge : rclone should delete those directories (not sure why there is an error here)
- sync : ignoring them (in both directions)

**Comment by xgiovio** [comment]
yes. It seems to be the same problem. Do you have any eta for the fix or workaround? Thank you

**Comment by ncw** [comment]
@xgiovio I'll try to do it this week - cross fingers!

**Comment by ncw** [comment]
@axtux @xgiovio All these issues should be fixed in v1.24 - let me know if they aren't

Thanks

Nick

**Comment by axtux** [comment]
Thanks for fixing so fast :-)
