### ISSUE TITLE
feature request: relative root in remotes for rclone mount

### ISSUE THREAD

**Issue by karlkleinpaste** [ncw/rclone#1720]
For a variety of security reasons, some remotes (esp. FTP servers) restrict permissions on the root directory, though providing ordinary access to subdirectories. For example, an FTP archive site I use regularly has its root dir set for 751 permissions, unreadable by the server itself; however, the subdirectory where archives are kept is public knowledge, in /pub/x/y/z, which can be reached because the root's other-execute bit is set -- the anon ftp user can "cd /pub/x/y/z" directly, and then find what he's looking for. If there are other directories besides pub in the root, the anon ftp user cannot see them.

rclone mount cannot cope with this because it fails to read the root directory as seen from FTP.

It would be highly useful if a remote's configuration could specify a subdirectory which should be considered the effective root directory that is referenced, rather than simply the topmost. Semantically, it could be considered similar to a chroot dir.

**Comment by ncw** [comment]
Can't you just pass the root required into the rclone mount parameter, eg

    rclone mount ftp:/sub/dir

or does that not work?

**Comment by karlkleinpaste** [comment]
ok ... i'm a dummy. yes, it's exactly that. i should have reviewed the man page better. sorry. for some reason i was operating on the belief that the remote's root had to be mounted.
