### ISSUE TITLE
rclone creates a new directory with Cyrillic name instead of using an existing one

### ISSUE THREAD

**Issue by vensko** [ncw/rclone#1723]
> What is your rclone version (eg output from `rclone -V`)
rclone v1.38
- os/arch: windows/amd64
- go version: go1.9

> Which OS you are using and how many bits (eg Windows 7, 64 bit)

Windows 10 64-bit
Ubuntu 16.04.3 LTS 64-bit

> Which cloud storage system are you using? (eg Google Drive)

Google Drive

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

rclone copy 1.mp3 "GoogleDrive:Ляпис Трубецкой"

> Log does not show anything unusual.

rclone is unable to find a path with Cyrillic symbols in it (destination or its parent) and creates new directories with duplicate names.

For instance,
> rclone copy 1.mp3 "GoogleDrive:Ляпис Трубецкой"
> rclone copy 1.mp3 "GoogleDrive:Ляпис Трубецкой"
> rclone copy 1.mp3 "GoogleDrive:Ляпис Трубецкой"

will create three directories "Ляпис Трубецкой" in root directory and reupload the file each time.

This behaviour presents in both Windows and Ubuntu.

Latin unicode names work as intended, the problem is specific to Cyrillic.

**Comment by ncw** [comment]
This is [a known issue in google drive](https://issuetracker.google.com/issues/64468406) which was acknowledged on 18th August 2017, so hopefully they will fix it soon.

This is discussed further in #1675

If google don't fix it soon then I'll figure out a work-around.

**Comment by B4dM4n** [comment]
I will close this issue, as a workaround is merged in #1675.
