### ISSUE TITLE
rclone copy deletes files on destination

### ISSUE THREAD

**Issue by disimone** [ncw/rclone#1724]
Hi,

this is a followup on #474

As suggested by @ncw, I ran with -vv, which indeed at least explains why files are being deleted.

The problem appears to be that the destination files (on dropbox), have for some reason modification time set to the day I uploaded them (which was also done using rclone copy).

The local files have kept the "real" modification date.

When running rclone copy it says:

`2017/10/08 10:52:17 DEBUG : filename.ext: src and dst identical but can't set mod time without deleting and re-uploading`

and then proceeds to delete the files from dropbox and upload again. Unfortunately, we are talking about almost 500GB of data here, and I would rather not transfer everything again.

Is there an option to ignore the conflicting modification dates? Any idea as of why the previous upload has the wrong modification date? I would like to be sure that new uploads don't have the same problem again in the future.

Thanks for your help,

Andrea.

**Comment by ncw** [comment]
> Is there an option to ignore the conflicting modification dates?

You can do a `--checksum` or a `--size-only` sync

> Any idea as of why the previous upload has the wrong modification date?

It was done with  a pre 1.37 rclone which used the v1 API which couldn't set modification dates at all.

Unfortunately the v2 API doesn't have a way of setting modification dates without uploading the whole file :-(

> I would like to be sure that new uploads don't have the same problem again in the future.

All new uploads should be fine.

**Comment by breunigs** [comment]
There's also `--no-update-modtime` which *just* ignores the modtimes, but leaves other sync/compare options as is. It will still print the warnings, though.

**Comment by disimone** [comment]
Thanks for your suggestions, things work ok now.
