### ISSUE TITLE
Just tested with Hubic and it doesn't work

### ISSUE THREAD

**Issue by intergleam** [ncw/rclone#1726]
When filing an issue, please include the following information if possible as well as a description of the problem.  Make sure you test with the latest beta of rclone.

    https://beta.rclone.org/
    https://rclone.org/downloads/

If you've just got a question or aren't sure if you've found a bug then please use the [rclone forum](https://forum.rclone.org/) instead of filing an issue.

> What is your rclone version (eg output from `rclone -V`)
rclone v1.38
- os/arch: linux/amd64
- go version: go1.9

> Which OS you are using and how many bits (eg Windows 7, 64 bit)
Ubuntu 17

> Which cloud storage system are you using? (eg Google Drive)
Hubic

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
` rclone ls remote:
2017/10/08 18:10:25 ERROR : xxxx: error listing: bucket or container name is needed in remote`

also nothing is being copied on 
`rclone copy /home/osboxes/temp remote:ooo`

> A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

```
osboxes@osboxes:~/temp$ rclone copy /home/osboxes/temp remote:ooo -vv
2017/10/08 18:19:56 DEBUG : Using config file from "/home/osboxes/.config/rclone/rclone.conf"
2017/10/08 18:19:56 DEBUG : rclone: Version "v1.38" starting with parameters ["rclone" "copy" "/home/osboxes/temp" "remote:ooo" "-vv"]
2017/10/08 18:19:57 DEBUG : Hubic: Got swift credentials (expiry 2017-10-09 17:03:14 +0200 +0200 in 23h43m16.461334562s)
2017/10/08 18:19:57 INFO  : Hubic Swift container ooo: Modify window is 1ns
2017/10/08 18:19:59 INFO  : Hubic Swift container ooo: Waiting for checks to finish
2017/10/08 18:19:59 DEBUG : 5MB.zip: Size and modification time the same (differ by 0s, within tolerance 1ns)
2017/10/08 18:19:59 DEBUG : 5MB.zip: Unchanged skipping
2017/10/08 18:19:59 INFO  : Hubic Swift container ooo: Waiting for transfers to finish
2017/10/08 18:19:59 INFO  : 
Transferred:      0 Bytes (0 Bytes/s)
Errors:                 0
Checks:                 1
Transferred:            0
Elapsed time:        3.6s

2017/10/08 18:19:59 DEBUG : Go routines at exit 7
2017/10/08 18:19:59 DEBUG : rclone: Version "v1.38" finishing with parameters ["rclone" "copy" "/home/osboxes/temp" "remote:ooo" "-vv"]

```

**Comment by nagualcode** [comment]
I tried to use hubic some time ago, and in the end it was terrible, I would not recommend hubic, it seems like a beta-test project.

**Comment by ncw** [comment]
Note that you need rclone lsd to list the containers.

And your copy has worked - rclone has worked out that file is already uploaded.

Rclone and hubic shoukd work OK together, I regularly run the integration tests against Hubic.

**Comment by intergleam** [comment]
may be it worked, but there are no files in my hubic account

**Comment by intergleam** [comment]
ok i can copy there and back locally, only I don't see files via web Hubic UI. Any idea why?

**Comment by ncw** [comment]
You can only see files in the container called `default` in the Hubic UI.

**Comment by intergleam** [comment]
thanks

**Comment by ncw** [comment]
No worries!  I'll close this now.
