### ISSUE TITLE
Every change in local folder shared with drive get's undone after a few seconds

### ISSUE THREAD

**Issue by dodekaeder** [ncw/rclone#173]
Im runnning rclone on debian jessie.

Everytime I make a change in the local folder I shared my google drive with, it get's undone
after a few seconds. Feels like rclone doesn't upload anything but mirrors the shared gdrive.

Is the basic configuration when just running <code>rclone config</code> with <code>auto-config = y</code> supposed to be like this?

**Comment by ncw** [comment]
> Everytime I make a change in the local folder I shared my google drive with, it get's undone
after a few seconds.

Are you using something else to sync this directory as well as `rclone`?  If you are that will cause problems.  You could run rclone on a separate directory (locally and in drive) to any other syncing systems.

Can you show the commands you use to run rclone, what happens and what you expected to happen?

>  Feels like rclone doesn't upload anything but mirrors the shared gdrive.

rclone is a one-way syncing program.  So if you run it like this it will sync from drive to local, mirroring the drive to local disk.

    rclone sync drive:Folder LocalFolder

And like this to sync the other way from local to drive, mirroring your local folder to the remote drive.

    rclone sync LocalFolder drive:Folder 

Drive doesn't do bi-directional sync yet like the google drive client does (it might in the future).

**Comment by ncw** [comment]
Just wondering if you'd had a chance to look at my reply? 

Thanks

Nick

**Comment by dodekaeder** [comment]
Of course I did. But, by a lack of deeper insight in "those hings" I just stopped using it.
I don't really know if there was a problem despite that I dreamed of a bi-sync.
functionality or if there was a problem with my system setup. (usually I just setup a new linux when I lost the trace of my system setup).

**Comment by ncw** [comment]
@dodekaeder sorry we couldn't make it work for you.  There are lots of happy users of rclone with drive so it is possible to make it work - let me know if you want to have another go some time.
