### ISSUE TITLE
B2: "http: unexpected EOF reading trailer"

### ISSUE THREAD

**Issue by jikamens** [ncw/rclone#1730]
> What is your rclone version (eg output from `rclone -V`)

```
rclone v1.37-112-g09fbbdbbβ
- os/arch: linux/amd64
- go version: go1.9
```

> Which OS you are using and how many bits (eg Windows 7, 64 bit)

Ubuntu 17.04 64-bit

> Which cloud storage system are you using? (eg Google Drive)

Crypt on top of B2

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

It was an `rclone check` invocation of a local directory against a remote crypt destination on top of B2.

> A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

This is an intermittent problem which I've just seen once, so I can't reproduce it and therefore can't send you a log (this is also why the version reported above is not the current version of rclone; I can't reproduce the issue with the current version, though I will install the current version now so that if it happens again it will be on a more recent version). This is what I saw in the error output:

>```
>2017/10/09 07:38:18 ERROR : Encrypted drive 'B2-encrypted:mac-backup': Error building file list: error listing: Encrypted drive 'B2-encrypted:mac-backup': http: unexpected EOF reading trailer
>2017/10/09 07:38:18 Failed to check: error listing: Encrypted drive 'B2-encrypted:mac-backup': http: unexpected EOF reading trailer
>```

I think maybe there is some error catch / retry logic that needs to be added here?

Thanks!

**Comment by ncw** [comment]
That error `unexpected EOF reading trailer` is from the go http library, and as far as I can see what it is doing is reading an Http trailer (like an http header but at the end of the body).  Http trailers aren't used very often and I don't think B2 uses them, so what I suspect is happening is that the network connection closed.

I've made this error retriable which should fix the problem

https://beta.rclone.org/v1.38-018-g3eb7f52e/ (uploaded in 15-30 mins)
