### ISSUE TITLE
Backblaze B2 large file copy fault tolerance

### ISSUE THREAD

**Issue by eodrap** [ncw/rclone#1733]
> What is your rclone version (eg output from `rclone -V`)

rclone v1.38

> Which OS you are using and how many bits (eg Windows 7, 64 bit)

macOS 10.12.6 64-bit

> Which cloud storage system are you using? (eg Google Drive)

Backblaze B2 with crypt

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

rclone: Version "v1.38" starting with parameters ["rclone" "--fast-list" "--verbose" "--verbose" "--buffer-size=256M" "--checkers=64" "--transfers=32" "--b2-chunk-size=256M" "--b2-upload-cutoff=256M" "--low-level-retries=1000" "--retries=500" "copy" "xxx.tar.gz" "crypt_backblaze:xxx/"]

> A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

Large file copies (~180GB) to Backblaze B2 are failing on individual chunks, with a mix of the following errors -

-  HTTP/1.x transport connection broken: http: ContentLength=268435496 with Body length 86749635
- HTTP/1.x transport connection broken: write tcp x.x.x.x:56063->206.190.208.233:443: write: broken pipe
- Post https://pod-000-1093-18.backblaze.com/xxx: read tcp x.x.x.x:56064->206.190.208.249:443: read: operation timed out
- pacer: low level retry 1/1000 (error Authorization token has expired (401 expired_auth_token))
-- **Similar to #1660**

My internet connection isn't dropping but I suspect my WLAN connection is. I've restarted the transfer using a wired connection but it's going over the same Powerline switches as the wireless APs so I expect issues to continue.

Would it be possible for rclone / Backblaze to be fault tolerant when individual chunks fail? The behaviour at the moment seems to be that a single chunk fails due to a temporary connection drop and this causes the entire transfer to be restarted. I've set high --retries and --low-level-retries values, these work but still require the full transfer operation to be restarted. I was able to upload with v1.37 after multiple attempts, I've not tested in the earlier version but I've made 4x upload attempts all failing in similar ways (issue with a single chunk brings the whole operation down). rclone sync operations with are fault tolerant by virtue of transferring many small files, this is specific to large file transfer and many chunks.

Apologies if this request is asking for the impossible, I appreciate that the behaviour may be down to the Backblaze API. Thanks again for the brilliant work with rclone.

Here is some debugging output from rclone -

```
2017/10/07 18:22:45 DEBUG : xxx: Done sending chunk 37
2017/10/07 18:22:45 DEBUG : xxx: Cancelling large file upload due to error: Post https://pod-000-1092-03.backblaze.com/xxx: net/http: HTTP/1.x transport connection broken: http: ContentLength=268435496 with Body length 86749635
2017/10/07 18:22:52 ERROR : xxx.tar.gz: Failed to copy: Post https://pod-000-1092-03.backblaze.com/xxx: net/http: HTTP/1.x transport connection broken: http: ContentLength=268435496 with Body length 86749635
2017/10/07 18:22:52 ERROR : Attempt 1/3 failed with 1 errors and: Post https://pod-000-1092-03.backblaze.com/xxx: net/http: HTTP/1.x transport connection broken: http: ContentLength=268435496 with Body length 86749635

2017/10/07 18:22:45 DEBUG : xxx: Done sending chunk 37
2017/10/07 18:22:45 DEBUG : xxx: Cancelling large file upload due to error: Post https://pod-000-1092-03.backblaze.com/xxx: net/http: HTTP/1.x transport connection broken: http: ContentLength=268435496 with Body length 86749635
2017/10/07 18:22:52 ERROR : xxx.tar.gz: Failed to copy: Post https://pod-000-1092-03.backblaze.com/xxx: net/http: HTTP/1.x transport connection broken: http: ContentLength=268435496 with Body length 86749635
2017/10/07 18:22:52 ERROR : Attempt 1/3 failed with 1 errors and: Post https://pod-000-1092-03.backblaze.com/xxx: net/http: HTTP/1.x transport connection broken: http: ContentLength=268435496 with Body length 86749635

2017/10/09 21:39:23 DEBUG : xxx: Done sending chunk 121
2017/10/09 21:39:23 DEBUG : xxx: Cancelling large file upload due to error: Post https://pod-000-1093-09.backblaze.com/xxx: http: ContentLength=268435496 with Body length 0
2017/10/09 21:39:29 ERROR : xxx.tar.gz: Failed to copy: Post https://pod-000-1093-09.backblaze.com/xxx: http: ContentLength=268435496 with Body length 0
2017/10/09 21:39:29 ERROR : Attempt 3/500 failed with 1 errors and: Post https://pod-000-1093-09.backblaze.com/xxx: http: ContentLength=268435496 with Body length 0

2017/10/09 21:39:23 DEBUG : xxx: Done sending chunk 121
2017/10/09 21:39:23 DEBUG : xxx: Cancelling large file upload due to error: Post https://pod-000-1093-09.backblaze.com/xxx: http: ContentLength=268435496 with Body length 0
2017/10/09 21:39:29 ERROR : xxx.tar.gz: Failed to copy: Post https://pod-000-1093-09.backblaze.com/xxx: http: ContentLength=268435496 with Body length 0
2017/10/09 21:39:29 ERROR : Attempt 3/500 failed with 1 errors and: Post https://pod-000-1093-09.backblaze.com/xxx: http: ContentLength=268435496 with Body length 0

2017/10/10 06:04:29 DEBUG : xxx: Done sending chunk 16
2017/10/10 06:04:29 DEBUG : xxx: Sending chunk 59 length 268435456
2017/10/10 06:04:29 DEBUG : xxx: Didn't find object to account part transfer
2017/10/10 06:05:06 DEBUG : xxx: Error sending chunk 15: Post https://pod-000-1093-02.backblaze.com/xxx: net/http: HTTP/1.x transport connection broken: write tcp x.x.x.x:56063->206.190.208.233:443: write: broken pipe
2017/10/10 06:05:06 DEBUG : xxx: Sending chunk 60 length 268435456
2017/10/10 06:05:06 DEBUG : xxx: Didn't find object to account part transfer
2017/10/10 06:05:10 INFO  : 
Transferred:   139.966 GBytes (1.649 MBytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:   24h9m2.5s
Transferring:
 *                           xxx.tar.gz:  8% done, 14.694 MBytes/s, ETA: 3h3m13s

2017/10/10 06:05:15 DEBUG : xxx: Clearing part upload URL because of error: Post https://pod-000-1093-18.backblaze.com/xxx: read tcp x.x.x.x:56064->206.190.208.249:443: read: operation timed out
2017/10/10 06:05:15 DEBUG : pacer: Rate limited, increasing sleep to 20ms
2017/10/10 06:05:15 DEBUG : pacer: low level retry 1/1000 (error Post https://pod-000-1093-18.backblaze.com/xxx: read tcp x.x.x.x:56064->206.190.208.249:443: read: operation timed out)
2017/10/10 06:05:15 DEBUG : xxx: Sending chunk 59 length 268435456
2017/10/10 06:05:16 DEBUG : B2 bucket xxx path xxx/: Unauthorized: Authorization token has expired (401 expired_auth_token)
2017/10/10 06:05:17 DEBUG : xxx: Clearing part upload URL because of error: Post https://pod-000-1093-15.backblaze.com/xxx: read tcp x.x.x.x:56051->206.190.208.246:443: read: operation timed out
2017/10/10 06:05:17 DEBUG : pacer: Rate limited, increasing sleep to 40ms
2017/10/10 06:05:17 DEBUG : pacer: low level retry 1/1000 (error Post https://pod-000-1093-15.backblaze.com/xxx: read tcp x.x.x.x:56051->206.190.208.246:443: read: operation timed out)
2017/10/10 06:05:17 DEBUG : xxx: Sending chunk 39 length 268435456
2017/10/10 06:05:17 DEBUG : pacer: Reducing sleep to 20ms
2017/10/10 06:05:17 DEBUG : pacer: Rate limited, increasing sleep to 40ms
2017/10/10 06:05:17 DEBUG : pacer: low level retry 1/1000 (error Authorization token has expired (401 expired_auth_token))
2017/10/10 06:05:17 DEBUG : pacer: Reducing sleep to 20ms
2017/10/10 06:05:17 DEBUG : xxx: Didn't find object to account part transfer
2017/10/10 06:05:17 DEBUG : pacer: Reducing sleep to 10ms
2017/10/10 06:05:17 DEBUG : xxx: Didn't find object to account part transfer
2017/10/10 06:05:41 DEBUG : xxx: Error sending chunk 40: Post https://pod-000-1093-01.backblaze.com/xxx: read tcp x.x.x.x:56053->206.190.208.232:443: read: network is down
2017/10/10 06:05:44 DEBUG : xxx: Error sending chunk 55: Post https://pod-000-1093-13.backblaze.com/xxx: read tcp x.x.x.x:56069->206.190.208.244:443: read: network is down
```

**Comment by ncw** [comment]
What rclone attempts to do is classify errors into errors which are worth retrying and those which aren't.

This classification is hard to get right though!

It looks like from your log the only fatal errors were these (the other errors were retried).

It should be relatively easy to make these errors retriable

```
2017/10/07 18:22:52 ERROR : Attempt 1/3 failed with 1 errors and: Post https://pod-000-1092-03.backblaze.com/xxx: net/http: HTTP/1.x transport connection broken: http: ContentLength=268435496 with Body length 86749635
2017/10/07 18:22:52 ERROR : Attempt 1/3 failed with 1 errors and: Post https://pod-000-1092-03.backblaze.com/xxx: net/http: HTTP/1.x transport connection broken: http: ContentLength=268435496 with Body length 86749635
2017/10/09 21:39:29 ERROR : Attempt 3/500 failed with 1 errors and: Post https://pod-000-1093-09.backblaze.com/xxx: http: ContentLength=268435496 with Body length 0
2017/10/09 21:39:29 ERROR : Attempt 3/500 failed with 1 errors and: Post https://pod-000-1093-09.backblaze.com/xxx: http: ContentLength=268435496 with Body length 0
```

It looks like both of these errors are internal net/http errors which aren't exported so I'll have to look for the error strings

```
$ git grep 'transport connection broken'
src/net/http/transport.go:              return fmt.Errorf("net/http: HTTP/1.x transport connection broken: %v", err)
$ git grep 'Body length'
length 8"),
src/net/http/transfer.go:               return fmt.Errorf("http: ContentLength=%d with Body length %d",
```

**Comment by ncw** [comment]
I've added these errors to be retried - please re-open if you find more errors which need the same treatment!

https://beta.rclone.org/v1.38-021-g43ced30f/ (uploaded in 15-30 mins)

**Comment by eodrap** [comment]
Thanks very much for the prompt replies and fix, @ncw!

I'm happy to test these - I can only see Windows builds via the link. Are these changes included in https://beta.rclone.org/rclone-beta-latest-osx-amd64.zip? It has a modification date of today 20:03.

**Comment by eodrap** [comment]
@ncw jumped the gun - can see the commit beta build now. Testing, will let you know how it goes. Thanks again for all the hard work and for rclone!

**Comment by eodrap** [comment]
@ncw The retry behaviour is working with content-length errors, but although rclone tries to retry it doesn't seem like the errors can be recovered from -

2017/10/10 22:02:43 DEBUG : pacer: Reducing sleep to 160ms
2017/10/10 22:02:43 DEBUG : xxx: Didn't find object to account part transfer
2017/10/10 22:02:43 DEBUG : xxx: Clearing part upload URL because of error: Post https://pod-000-1044-14.backblaze.com/b2api/v1/b2_upload_part/xxx http: ContentLength=268435496 with Body length 0
2017/10/10 22:02:43 DEBUG : pacer: Rate limited, increasing sleep to 320ms
2017/10/10 22:02:43 DEBUG : pacer: low level retry 4/10 (error Post https://pod-000-1044-14.backblaze.com/b2api/v1/b2_upload_part/xxx http: ContentLength=268435496 with Body length 0)
2017/10/10 22:02:43 DEBUG : xxx: Sending chunk 22 length 268435456
2017/10/10 22:02:44 DEBUG : pacer: Reducing sleep to 160ms
2017/10/10 22:02:44 DEBUG : xxx: Didn't find object to account part transfer
2017/10/10 22:02:44 DEBUG : xxx: Clearing part upload URL because of error: Post https://pod-000-1044-04.backblaze.com/b2api/v1/b2_upload_part/xxx http: ContentLength=268435496 with Body length 0
2017/10/10 22:02:44 DEBUG : pacer: Rate limited, increasing sleep to 320ms
2017/10/10 22:02:44 DEBUG : pacer: low level retry 5/10 (error Post https://pod-000-1044-04.backblaze.com/b2api/v1/b2_upload_part/xxx http: ContentLength=268435496 with Body length 0)
2017/10/10 22:02:44 DEBUG : xxx: Sending chunk 22 length 268435456
2017/10/10 22:02:45 DEBUG : pacer: Reducing sleep to 160ms
2017/10/10 22:02:45 DEBUG : xxx: Didn't find object to account part transfer
2017/10/10 22:02:45 DEBUG : xxx: Clearing part upload URL because of error: Post https://pod-000-1044-16.backblaze.com/b2api/v1/b2_upload_part/xxx http: ContentLength=268435496 with Body length 0
2017/10/10 22:02:45 DEBUG : pacer: Rate limited, increasing sleep to 320ms
2017/10/10 22:02:45 DEBUG : pacer: low level retry 6/10 (error Post https://pod-000-1044-16.backblaze.com/b2api/v1/b2_upload_part/xxx http: ContentLength=268435496 with Body length 0)
2017/10/10 22:02:45 DEBUG : xxx: Sending chunk 22 length 268435456
2017/10/10 22:02:46 DEBUG : pacer: Reducing sleep to 160ms
2017/10/10 22:02:46 DEBUG : xxx: Didn't find object to account part transfer
2017/10/10 22:02:46 DEBUG : xxx: Clearing part upload URL because of error: Post https://pod-000-1044-02.backblaze.com/b2api/v1/b2_upload_part/xxx http: ContentLength=268435496 with Body length 0
2017/10/10 22:02:46 DEBUG : pacer: Rate limited, increasing sleep to 320ms
2017/10/10 22:02:46 DEBUG : pacer: low level retry 7/10 (error Post https://pod-000-1044-02.backblaze.com/b2api/v1/b2_upload_part/xxx http: ContentLength=268435496 with Body length 0)
2017/10/10 22:02:46 DEBUG : xxx: Sending chunk 22 length 268435456
2017/10/10 22:02:47 DEBUG : pacer: Reducing sleep to 160ms
2017/10/10 22:02:47 DEBUG : xxx: Didn't find object to account part transfer
2017/10/10 22:02:47 DEBUG : xxx: Clearing part upload URL because of error: Post https://pod-000-1044-14.backblaze.com/b2api/v1/b2_upload_part/xxx http: ContentLength=268435496 with Body length 0
2017/10/10 22:02:47 DEBUG : pacer: Rate limited, increasing sleep to 320ms
2017/10/10 22:02:47 DEBUG : pacer: low level retry 8/10 (error Post https://pod-000-1044-14.backblaze.com/b2api/v1/b2_upload_part/xxx http: ContentLength=268435496 with Body length 0)
2017/10/10 22:02:47 DEBUG : xxx: Sending chunk 22 length 268435456
2017/10/10 22:02:48 DEBUG : pacer: Reducing sleep to 160ms
2017/10/10 22:02:48 DEBUG : xxx: Didn't find object to account part transfer
2017/10/10 22:02:49 DEBUG : xxx: Clearing part upload URL because of error: Post https://pod-000-1044-19.backblaze.com/b2api/v1/b2_upload_part/xxx http: ContentLength=268435496 with Body length 0
2017/10/10 22:02:49 DEBUG : pacer: Rate limited, increasing sleep to 320ms
2017/10/10 22:02:49 DEBUG : pacer: low level retry 9/10 (error Post https://pod-000-1044-19.backblaze.com/b2api/v1/b2_upload_part/xxx http: ContentLength=268435496 with Body length 0)
2017/10/10 22:02:49 DEBUG : xxx: Sending chunk 22 length 268435456
2017/10/10 22:02:49 DEBUG : pacer: Reducing sleep to 160ms
2017/10/10 22:02:49 DEBUG : xxx: Didn't find object to account part transfer
2017/10/10 22:02:50 DEBUG : xxx: Clearing part upload URL because of error: Post https://pod-000-1044-14.backblaze.com/b2api/v1/b2_upload_part/xxx http: ContentLength=268435496 with Body length 0
2017/10/10 22:02:50 DEBUG : pacer: Rate limited, increasing sleep to 320ms
2017/10/10 22:02:50 DEBUG : pacer: low level retry 10/10 (error Post https://pod-000-1044-14.backblaze.com/b2api/v1/b2_upload_part/xxx http: ContentLength=268435496 with Body length 0)
2017/10/10 22:02:50 DEBUG : xxx: Error sending chunk 22: Post https://pod-000-1044-14.backblaze.com/b2api/v1/b2_upload_part/xxx http: ContentLength=268435496 with Body length 0

I've left a WAN ping running and it hasn't dropped at all. Perhaps it's the B2 API at fault? It looks like it has gone away -

2017/10/10 22:10:39 DEBUG : xxx: Clearing part upload URL because of error: Post https://pod-000-1044-04.backblaze.com/b2api/v1/b2_upload_part/xxx dial tcp 206.190.208.155:443: getsockopt: connection refused
2017/10/10 22:10:39 DEBUG : pacer: Rate limited, increasing sleep to 1.28s
2017/10/10 22:10:39 DEBUG : pacer: low level retry 8/10 (error Post https://pod-000-1044-04.backblaze.com/b2api/v1/b2_upload_part/xxx dial tcp 206.190.208.155:443: getsockopt: connection refused)
2017/10/10 22:10:40 DEBUG : xxx: Sending chunk 31 length 268435456
2017/10/10 22:10:41 DEBUG : pacer: Reducing sleep to 640ms
2017/10/10 22:10:41 DEBUG : xxx: Didn't find object to account part transfer
2017/10/10 22:10:41 DEBUG : xxx: Clearing part upload URL because of error: Post https://pod-000-1044-04.backblaze.com/b2api/v1/b2_upload_part/xxx dial tcp 206.190.208.155:443: getsockopt: connection refused

I'm watching the logs now and different chunks are all encountering content length errors and are at various low level retry passes (using the default of 10 low level retries). This looks like attempted recovery confusion -

2017/10/10 22:14:09 DEBUG : xxx: Clearing part upload URL because of error: Not enough members for write of xxx: neighbor_down; neighbor_down (500 internal_error)

I've attached full logs for the session in case there's a pattern emerging. Let me know if there's any additional testing which I can do - happy to try with bumped up low level retries to see if things eventually recover. It's still stumbling on with later chunks, I'll update the ticket in the morning and let you know if it eventually recovers. Low level retry limit 10/10 on a chunk doesn't bring the entire operation down.
[rclone.log](https://github.com/ncw/rclone/files/1373466/rclone.log)

**Comment by eodrap** [comment]
Hi again @ncw - rclone hasn't moved on (progress feedback shows no extra uploaded data or percentage complete increase) after the first "body length 0" errors. It attempts low level retries but these never trigger a full retry. The full log above is still representative, last output before cancelling -

```
2017/10/11 03:39:08 DEBUG : pacer: Reducing sleep to 2m30s
2017/10/11 03:39:08 DEBUG : xxx: Didn't find object to account part transfer
2017/10/11 03:39:09 DEBUG : xxx: Clearing part upload URL because of error: Post https://pod-000-1044-09.backblaze.com/b2api/v1/b2_upload_part/xxx http: ContentLength=268435496 with Body length 0
2017/10/11 03:39:09 DEBUG : pacer: Rate limited, increasing sleep to 5m0s
2017/10/11 03:39:09 DEBUG : pacer: low level retry 2/10 (error Post https://pod-000-1044-09.backblaze.com/b2api/v1/b2_upload_part/xxx http: ContentLength=268435496 with Body length 0)
```

**Comment by eodrap** [comment]
@ncw please can this be reopened.

**Comment by ncw** [comment]
The log looks like something went wrong at backblaze.  You can see it trying different pods in the requests, but it isn't having luck with any of them.

What I would expect to happen is that the low-level retries will run out eventually (may take some time since backblaze's timeouts are quite long - in your log it has got to 5 minutes) and it will do a full retry of the whole sync.

I think backblaze recommend you keep trying for something like 30 minutes in case a pod has failed and needs restarting.

**Comment by eodrap** [comment]
Thanks @ncw. It does look like it's a Backblaze issue... in testing with v1.38 I'd got to 91% over a few days (!) and then -

`2017/11/29 18:25:33 DEBUG : xxx: Cancelling large file upload due to error: Post https://pod-000-1039-10.backblaze.com/b2api/v1/b2_upload_part/xxx: net/http: HTTP/1.x transport connection broken: http: ContentLength=268435496 with Body length 268292549
2017/11/29 18:25:43 ERROR : 201711061446.tar.gz: Failed to copy: Post https://pod-000-1039-10.backblaze.com/b2api/v1/b2_upload_part/xxx: net/http: HTTP/1.x transport connection broken: http: ContentLength=268435496 with Body length 268292549
2017/11/29 18:25:43 ERROR : Attempt 2/3 failed with 1 errors and: Post https://pod-000-1039-10.backblaze.com/b2api/v1/b2_upload_part/xxx: net/http: HTTP/1.x transport connection broken: http: ContentLength=268435496 with Body length 268292549`

At this point rclone recovers but restarts from the beginning.

Is this a limitation of the Backblaze B2 API - transfers cannot be resumed? No drops in my connection so it looks like large files and B2 don't play nicely.

**Comment by ncw** [comment]
@eodrap Please use [the latest beta](https://beta.rclone.org) - I've put a lot of fixes in recently for large file uploads with dropbox.  The error above would have been retried with the beta and it would have gone through.

**Comment by eodrap** [comment]
Thanks @ncw. I've tested v1.38-195-g47450ba3β, the new transfer rate and progress reporting is a nice touch! I'm still getting errors which bring down the transfer -

`2017/11/30 21:40:23 DEBUG : pacer: low level retry 10/10 (error Post https://pod-000-1038-11.backblaze.com/b2api/v1/b2_upload_part/xxx/0004: http: ContentLength=268435496 with Body length 0)
2017/11/30 21:40:23 DEBUG : xxx: Error sending chunk 117: Post https://pod-000-1038-11.backblaze.com/b2api/v1/b2_upload_part/xxx/0004: http: ContentLength=268435496 with Body length 0`

Full log is attached. Would you suggest in this case I increase the --low-level-retries (I'm using the default)? Is there a timeout / retry delay option worth changing?

Thanks as always for the support.

[rclone-v1.38-195-g47450ba3β.log](https://github.com/ncw/rclone/files/1520567/rclone-v1.38-195-g47450ba3.log)

**Comment by ncw** [comment]
I think that is a bug...

@breunigs looking at this code in the [transferChunk](https://github.com/ncw/rclone/blob/master/b2/upload.go#L184) function - when a retry happens, the buffer has already been read by the first time round the loop so is empty on the second time round the loop.  This is the cause of the `http: ContentLength=268435496 with Body length 0` error above.

Before 234bfae0d5dfc2be4eff1c101f1fd89055232a2a and b510c70c1ef2bd41eee962dc04fbbe0880edebd6  this used to [look like this](https://github.com/ncw/rclone/blob/384724fd111252cac51271b1da4bc4110b32f2be/b2/upload.go#L130) - it makes a new `bytes.Buffer` every Call so the retries work properly.

Since we already have the entire block in memory at this point, maybe the `hashAppendingReader` is overkill here? Perhaps we should just calculate the sha and add it on the end of buf?

Thoughts?

**Comment by ncw** [comment]
I've put a fix for this here

https://beta.rclone.org/v1.38-228-g0914ec31/ (uploaded in 15-30 mins)

@eodrap can you have a go with that and report back please?  What you should find is that segments of large file uploads can fail now, but will be retried.

@breunigs in 0914ec316c6521da19180969a8e6610039e15949  I made the minimal possible fix just moving the creation of the hash appending reader into the retry loop.  This is inefficient in the retry case (it is re-hashing the data) but I think that since retries aren't common this is good enough.

**Comment by eodrap** [comment]
@ncw bingo, it works now! Low level retries were triggered during the transfer but progress was not lost and the transfer completed successfully.

Well done and thanks for your efforts on fixing this!

**Comment by ncw** [comment]
Excellent and thanks for a) the report, b) testing, and c) being persistent - much appreciated :-)
