### ISSUE TITLE
Question: Does rclone contact githut for module import

### ISSUE THREAD

**Issue by xflou** [ncw/rclone#1749]
Hello,
I"m interested in using rclone, but noticed that some of the files are imported from:

"github.com/ncw/rclone/fs", "github.com/pkg/errors"  as an example. 

My question is, does rclone do this for all transactions? Also, can these modules or libraries be installed locally instead so the program does not have contact github every time? 

Thanks!

**Comment by ncw** [comment]
Those files are only imported when compiling rclone. Once rclone is compiled then it doesn't fetch anything from anywhere. When you download it, it is already compiled.

**Comment by ncw** [comment]
Hopefully that answers your question!

**Comment by xflou** [comment]
Yes it does. Thanks very much!
