### ISSUE TITLE
Issue with usage documentation in the --log-level section

### ISSUE THREAD

**Issue by edgarsuit** [ncw/rclone#1755]
Issue on documentation page here: https://rclone.org/docs/

The first line of the `--log-level` section states that `INFO` is the default log level value, but the `NOTICE` section states that it's the default log level. It appears that `NOTICE` is in fact the default log level, so the first line in the section needs to be updated.

**Comment by ncw** [comment]
Well spotted!  Fancy sending a pull request?

**Comment by edgarsuit** [comment]
Hah, I'd love to, but I have no idea how to do that. I could try to figure it out, but I might bork your whole project.

**Comment by edgarsuit** [comment]
Ok I think I figured it out. Hopefully I didn't just set fire to everyone's crap.
