### ISSUE TITLE
Slow uploads unless ip bound

### ISSUE THREAD

**Issue by MrRobot245** [ncw/rclone#1758]
Uploading to Google Drive from a VPS with 1000/250 only gets around 12-17 megabit upload unless I bind the ipv4 address to the command. With it bound i get ~220.

Server on SYS BHS farm

rclone 1.38
Ubuntu 17.04
Google Drive

**Comment by ncw** [comment]
If you don't bind and IPv4 address, then rclone will use IPv6 if available.  Is that what is happening?  Check with `netstat -tuanp` or similar.

**Comment by MrRobot245** [comment]
Looks like its just an issue with OVH limiting uploads on ipv6, binding it to the ipv4 address gets advertised speeds from my host
