### ISSUE TITLE
[Feature request] rclone lsjson with encryption mapping

### ISSUE THREAD

**Issue by mesca** [ncw/rclone#1765]
A `-M` flag for the `lsjon` command would include the encryption mapping on `crypt` remotes. It would give the same info as `--crypt-show-mapping`, but directly in the JSON object, not on STDERR.

**Comment by ncw** [comment]
That is a nice idea!

**Comment by kubatasiemski** [comment]
Hi,
I would like to work with this issue.

**Comment by ncw** [comment]
@kubatasiemski - Great - thanks!

**Comment by ncw** [comment]
Please find this in the beta

https://beta.rclone.org/v1.39-218-gacae10cd/ (uploaded in 15-30 mins)

Please re-open if you have a problem with it.

Thanks @kubatasiemski for implementing it :-)
