### ISSUE TITLE
Feature Request gDrive: new rclone command for quotaBytesTotal

### ISSUE THREAD

**Issue by ajkis** [ncw/rclone#1768]
It would be great if we had rclone command to query gdrive with quotaBytesTotal.
With that we could easily control our daily upload so we dont hit the upload block eg
we pull the quota at begining the day and stop our cron upload once we are close to max quota.

Current upload daily limit is 750GB.

**Comment by ncw** [comment]
I think the quota is total number of bytes you can store in the drive rather than a daily upload limit.

```
 "quotaBytesTotal": "18253611008",
 "quotaBytesUsed": "9087605659",
```

Is what I get for my 17GB limited drive

BTW rclone fetches it already at the start of using drive you can see it with `-vv --dump-bodies`.  It doesn't do anything with the quota though.

**Comment by ajkis** [comment]
Basically we could use rclone quota or usage that would return current drive size without the number of objects. Since currently this takes quite a long time to preform ( eg 15 minutes + )

**Comment by ajkis** [comment]
Ah yes i just saw, that you get info with dump headers eg quotaBytesTotal is the current size. 

Atm Iam getting the info with rclone lsd remote: then do this on log file `cat $LogFile | grep "quotaBytesTotal" | xargs | cut -d " " -f 2`

**Comment by MurzNN** [comment]
Can we use same way to calculate not the total, but per-folder `quotaBytesTotal` report? I searching some tool, that will generate per-folder quota usage report for all folders in my gdrive.

**Comment by ncw** [comment]
Note that this is now supported with `rclone about drive:` for reading the total quota.

@MurzNN I'll leave the per file quota to your other issue #3135 and close this one.
