### ISSUE TITLE
rclone tries to PUT swift segments container every time

### ISSUE THREAD

**Issue by johnl** [ncw/rclone#1769]
I'm using rclone v1.38 with an OpenStack Swift cluster.

When setting the `--swift-chunk-size` option rclone splits large files into chunks which it stores in a separate swift container, named the same as the destination container but with `_segments` added on the end.

I'm using credentials for Swift that don't have authorisation to create or update containers, only objects within them. So I create the container manually with another set of credentials.

but then rclone sends a PUT request to the `_segments` container - it looks like it blindly does this rather than checking if it already exists. It receives a 403 forbidden code from Swift of course. it just retries a few times and gives up.

I think that it should make a HEAD request on the container to see if it already exists first and skip the PUT if it already does.

Also worth noting is that rclone seems not to give any hint what it's doing regarding chunks/segments. I've tried running it with all the verbose options but it never mentions the _segments container use at all. It only says:

`2017/10/24 12:34:43 ERROR : DSC_1345.MOV: Failed to copy: Operation forbidden`

which is rather misleading!

**Comment by johnl** [comment]
this patch works for me - I can't see any tests that need updating for this specific code, let me know if I missed something.

**Comment by ncw** [comment]
Thanks for fixing this!  Unfortunately the integration tests don't test the large file handling as it would involve transferring a lot of data...
