### ISSUE TITLE
CPU load when uploading

### ISSUE THREAD

**Issue by axtux** [ncw/rclone#177]
Hello,

Recently, I ran rclone from my NAS Dlink DNS-320L (I don't recommend it but now, I'll go with it). When I upload to webdav using curl, my CPU load goes from 10% to 30% and transfer speed is 3MB/s. When I upload to swift using rclone (even a simple copy), my CPU load goes from 10% to 100% and transfer speed is 1,5MB/s. I was wondering if this was normal as I didn't think data transfer could be so CPU intensive.

Regards,
Axtux

**Comment by klauspost** [comment]
What CPU is in that machine?

My guess is that it is SSL eating up the CPU. 

@ncw - is pprof included in rclone? Can we do a cpu profile?

**Comment by axtux** [comment]
It's an old ARMv5 (Marvell Kirkwood 88F6702). You're right, I had not thought about SSL. Uploading to secure webdav load CPU to 100% and upload speed is about 2,85MB. I'll try to find an other way to upload. I'll try with a Raspberry Pi 2 (which is an ARMv7).

**Comment by ncw** [comment]
It is very likely the SSL.  Go implements its own SSL which isn't quite as CPU efficient as openssl which might explain the 1.5 MB/s vs 2.85 MB/s difference.

You can run the profiler with rclone using the `--cpuprofile=rclone.prof` flag.  This will make a file called `rclone.prof` which you can then examine with the go tools `go tool pprof rclone rclone.prof`, then the command `top20` usually will tell you what is going on.  If you'd prefer, email me the `rclone.prof` file (along with the exact version of rclone you are using or the binary if you compiled it yourself) and I'll analyse it and post the results here!

**Comment by klauspost** [comment]
Close? I don't think there is anything we can do. SSL will be faster on x64 in 1.6 now that it looks as if  [CL 8968](https://go-review.googlesource.com/#/c/8968/) will land. But unless someone converts it to ARM it will remain as it is.

**Comment by ncw** [comment]
I'm going to close this as it seems the CPU load is due to

  * SSL performance on a slow processor
  * Go SSL routines not being as fast as they could be

We can't do anything about the first, and the second will improve over time I'm sure, but neither can be fixed by your humble rclone developers!

Thanks for the report

Nick

**Comment by rindeal** [comment]
And what about [OpenSSL bindings for Go](https://github.com/spacemonkeygo/openssl)? On RaspberryPi B+ it's 1,2MB/s with Go and 3 MB/s with curl+OpenSSL.

**Comment by ncw** [comment]
@rindeal I'd consider an alternate build for ARM using openssl.  Fancy sending a Pull request?

**Comment by rindeal** [comment]
@ncw I'm sorry, but I've never written a line in Go and this doesn't look like a trivial thing to do.

**Comment by ncw** [comment]
@rindeal - I'm ever hopeful :-)  Actually I think the code changes would be quite easy as the library is a drop in replacement for the go http library, but making the build will be painful as it will need a full cross compile environment for ARM and all the libraries.

**Comment by rindeal** [comment]
I wish it'd be as you say, but the docs say "near-drop-in" replacement for **tls** library. Also the author has this to say:
```go
// TODO: http client integration
// holy crap, getting this integrated nicely with the Go stdlib HTTP client
// stack so that it does proxying, connection pooling, and most importantly
// hostname verification is really hard. So much stuff is hardcoded to just use
// the built-in TLS lib. I think to get this to work either some crazy
// hacktackery beyond me, an almost straight up fork of the HTTP client, or
// serious stdlib internal refactoring is necessary.
// even more so, good luck getting openssl to use the operating system default
// root certificates if the user doesn't provide any. sadlol
// NOTE: if you're going to try and write your own round tripper, at least use
//  openssl.Dial, or equivalent logic
```
In case it gets incorporated somehow, I hope it will be able to use the system-wide OpenSSL library installed on every Linux box. If you were talking about Go libs, I can compile them natively on my more powerful ARM boards.

**Comment by Neustradamus** [comment]
@axtux: For information:

Note that D-Link DNS-320L and DNS-325 are supported in OpenWrt:
- https://github.com/openwrt/openwrt/pull/17924
- https://github.com/openwrt/openwrt/pull/16803
- https://github.com/openwrt/openwrt/pull/15433
