### ISSUE TITLE
Unable to copy a single file from Google Drive

### ISSUE THREAD

**Issue by dbareiro** [ncw/rclone#1772]
Hi, Nick!

I am using `rclone` (`rclone-v1.38-linux-amd64.zip`) on Debian Jessie but I am not able to copy a single file:

```
$ ./rclone ls remote:Educ.ar
     4629 IDC-EQUIPAMIENTO.xlsx
```

```
$ ./rclone copy remote:Educ.ar/IDC-EQUIPAMIENTO.xlsx .
2017/10/25 13:53:58 ERROR : : error reading source directory: directory not found
2017/10/25 13:53:58 ERROR : Attempt 1/3 failed with 1 errors
2017/10/25 13:53:58 ERROR : : error reading source directory: directory not found
2017/10/25 13:53:58 ERROR : Attempt 2/3 failed with 1 errors
2017/10/25 13:53:58 ERROR : : error reading source directory: directory not found
2017/10/25 13:53:58 ERROR : Attempt 3/3 failed with 1 errors
```

Maybe I'm missing something?

Thanks in advance.

Kind regards,
Daniel

**Comment by dbareiro** [comment]
Hi, naeloob.

Thank you very much. That worked. Is it always necessary to use `--include` to copy a single file?

Kind regards,
Daniel

**Comment by naeloob** [comment]
Rclone is a tool to copy/sync complete folders, so if you want just a file you have to filter for it.

Remote:Path
You cannot put a filename on the path part. If you want to filter to copy just something from that path you must filter with filter parameters : include, exclude, filters...

**Comment by dbareiro** [comment]
Hi again, naeloob.

> Remote:Path
> You cannot put a filename on the path part. If you want to filter to 
> copy just something from that path you must filter with filter 
> parameters: include, exclude, filters...
>
> Rclone was looking for the Educ.ar/IDC-EQUIPAMIENTO.xlsx directory... 
> and cannot find it.

Thanks for your reply and the clarification.

Maybe my mistake was thinking the path could contain a filename at the end. When I read the documentation I saw some about that; for example when using the `copyto` parameter [1]. In fact, I had also tried using the `copyto` parameter but it did not work either.

Kind regards,
Daniel

[1] https://rclone.org/commands/rclone_copyto/

**Comment by ncw** [comment]
Sorry for not responding sooner.

Yes you should be able to copy single files as you have written.

However because this file is a google doc and not an actual file, it isn't working.

This is a bug which needs fixing!

However the workaround suggested by @naeloob using `--include` will work find for google docs and google files.

**Comment by dbareiro** [comment]
Hi, Nick!

Thank you for confirming that it is a bug. In the meantime I will use the workaround mentioned by @naeloob.

Kind regards,
Daniel
