### ISSUE TITLE
GO TLS issue: remote error: tls: bad record MAC

### ISSUE THREAD

**Issue by awb99** [ncw/rclone#1774]
An older ticket has been closed (https://github.com/ncw/rclone/issues/1254) , but I believe the underlying problem never has been closed. There is a go / TLS issue somewehere. This is the detailed log in pastebin: https://pastebin.com/L7MhHXiF

> What is your rclone version (eg output from `rclone -V`)

rclone 1.38

> Which OS you are using and how many bits (eg Windows 7, 64 bit)

debian stretch

> Which cloud storage system are you using? (eg Google Drive)

Google Drive and Dropbox

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

    rclone copy /var/backups/mongobackups/17-10-26backup_cititrip.tar flodropbox:rclone/cititripdb --log-level DEBUG  --dump-headers  | nc termbin.com 9999

> A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

 https://pastebin.com/L7MhHXiF

**Comment by ncw** [comment]
The error in question being `remote error: tls: bad record MAC`.

How reproducable is this bug?  I haven't seen it in testing.

It is likely a bug in the go TLS (or possibly in the dropbox TLS).

Can you reproduce with [the latest beta](https://beta.rclone.org) which I compiled with the latest go release (which had some TLS fixes)?

If so we should probably report a bug on go. Ideally we need a small-ish test case which reproduces the problem reasonably often.

**Comment by awb99** [comment]
I have done some more testing on the machine where this error occurs. When I remotely try to get data via rsync a similar error happens. I found this: https://unix.stackexchange.com/questions/328912/ssh-dispatch-run-fatal-message-authentication-code-incorrect/330359

**Comment by awb99** [comment]
@ncw :+1:  Thanks!  Unfortunately, I have the same issue on the beta.  I have had quite a few issues with bad certificates with other apps in the past. I don't think this issue is really a problem of rclone or go. I guess it is much deeper than that  (kernel / distributon level). 

Bug Report:

rclone gets can synchronize small files to google drive and to dropbox. Syncing.  large files (60 MB) get randomly erros: "remote error: tls: bad record MAC". Pats of the blocks are uploaded, but then in one block at some time this error comes; even with 5000 retries it will not work.

operating system: a fresh Debian Jessie that gets upgraded  to "Debian Stretch", x86-64 architecture

also effected apps: 1. rsync, 2. scp
ssh is working.

**Comment by awb99** [comment]
I now have run the SAME install commands on a fresh Debian STRETCH server; so the only difference has been that the errors occurred on a Debian JESSIE server witih "apt-get dist-upgrade". The fresh STRETCH server runs without any errors.

**Comment by ncw** [comment]
Sorry for the delay in responding.  I have noted that this can be caused by checksum offload in the NIC causing bad packets, and disabling the offload fixes it.

I'm glad you've fixed it now though.

**Comment by loganmarchione** [comment]
For anyone that finds this, I had the same issue and @ncw's suggestion of disabling checksum offloading fixed it. I used [this link](https://michael.mulqueen.me.uk/2018/08/disable-offloading-netplan-ubuntu/) for Ubuntu 18.04.
