### ISSUE TITLE
How to print less data to txt file

### ISSUE THREAD

**Issue by abarber229** [ncw/rclone#1775]
It's not really an issue but rather looking for advice on how to clear up the output file. Thank you in advance for the advice and suggestions.

> rclone v1.38-031-gef134660

> What is your rclone version (eg output from `rclone -V`)

> Windows 10 

> Google Drive

> rclone -q lsl "remote:path" > c:\Temp\Logs\filename.txt

I'm trying to gather a report of files from Google Drive for a particular folder. Here is the command I ran "rclone -q lsl "remote:path" > c:\Temp\Logs\filename.txt". It prints out the items that I need, however it also prints extra data that I don't need. See the screenshot below. I tried importing the data into excel but can't get it all separated like I would like. Is there a way to not print the data before the "foldername\filename". I briefly looked through the documentation but didn't see anything for a print less data command. 

![image](https://user-images.githubusercontent.com/26965604/32080214-6cf7d7d0-ba7c-11e7-84c0-1db41b7b1dc7.png)

**Comment by ncw** [comment]
There is the experimental `ls2` command which isn't listed and I reserve the right to remove when I've thought of a better name for it!  You can use `-R` with it to get a recursive listing.

**Comment by abarber229** [comment]
Perfect!
