### ISSUE TITLE
Rclone + Ubuntu Server 14 + Google Drive

### ISSUE THREAD

**Issue by klierik** [ncw/rclone#178]
Hello.

Can you tell me please what i need todo while i config rclone?
Its as just installed, first run:
```
$ rclone config
2015/10/22 19:33:07 Failed to load config file /home/user/.rclone.conf - using defaults: open /home/user/.rclone.conf: no such file or directory
No remotes found - make a new one
n) New remote
q) Quit config
n/q> n
name> gdrive
What type of source is it?
Choose a number from below
 1) swift
 2) s3
 3) local
 4) google cloud storage
 5) dropbox
 6) drive
 7) amazon cloud drive
type> 6
Google Application Client Id - leave blank normally.
client_id>
Google Application Client Secret - leave blank normally.
client_secret>
Remote config
Use auto config?
 * Say Y if not sure
 * Say N if you are working on a remote or headless machine or Y didn't work
y) Yes
n) No
y/n> y
If your browser doesn't open automatically go to the following link: http://127.0.0.1:53682/auth
Log in and authorize rclone for access
Waiting for code...
```

hmm.. so what next? It is Ubuntu server and i connect via SSH. How-to open `http://127.0.0.1:53682/auth` ???

PS: i tried open by ip `http://192.168.1.101:53682/auth` with out any lucky :(

Thanks

**Comment by zeshanb** [comment]
Hello there Aleksej,

Simply open this url http://127.0.0.1:53682/auth in a web browser to
authorize your rclone installation to access Google Drive. You will have to
login to your drive account on the same browser window.

**Comment by ncw** [comment]
The easiest option is to say N to auto config. That works on a remote server.

**Comment by klierik** [comment]
thanks for reply.
@zeshanb, it I's impossible because where is no GUI — It is Ubuntu Server w/o even monitor so i connect via ssh
@ncw, thanks you — it works.

**Comment by diego-vieira** [comment]
Strange, I don't have that option using v1.25
```
The easiest option is to say N to auto config. That works on a remote server.
```

```
oot@readynas:~# rclone config
2015/11/19 10:58:04 Failed to load config file /root/.rclone.conf - using defaults: open /root/.rclone.conf: no such file or directory
No remotes found - make a new one
n) New remote
q) Quit config
n/q> n
name> amazon-cloud
What type of source is it?
Choose a number from below
 1) amazon cloud drive
 2) drive
 3) dropbox
 4) google cloud storage
 5) swift
 6) hubic
 7) local
 8) onedrive
 9) s3
type> 1
Amazon Application Client Id - leave blank normally.
client_id> 
Amazon Application Client Secret - leave blank normally.
client_secret> 
Remote config
If your browser doesn't open automatically go to the following link: http://127.0.0.1:53682/auth
Log in and authorize rclone for access
Waiting for code...
```

**Comment by ncw** [comment]
@diego-vieira The original question was about drive. I'm afraid that ACD doesn't have a non-auto config mode. If you are trying to set rclone up on a headless box then set it up locally and copy the config file.  See the first item in the FAQ for how to do that. http://rclone.org/faq/

Hope that helps. 

Nick

**Comment by diego-vieira** [comment]
@ncw sorry about that, that will do.
Thank you!

**Comment by danoc** [comment]
@diego-vieira – Which rclone build did you download to get it to work on the ReadyNAS? I have a Duo V1 but can't figure out which OS it runs on.
