### ISSUE TITLE
Pauses on uploading - Dropbox

### ISSUE THREAD

**Issue by laurfx** [ncw/rclone#1783]
Problem: 

Rclone doesn't upload the files continues it pauses on transfer, pauses around 24 seconds, is this normal or it's a issue?

I test it on 3 different VPS and is the same issue, also rclone copy do the same thing.

> What is your rclone version (eg output from `rclone -V`)

rclone v1.38
- os/arch: linux/amd64
- go version: go1.9

> Which OS you are using and how many bits (eg Windows 7, 64 bit)

CentOS Linux release 7.3.1611 (Core)

> Which cloud storage system are you using? (eg Google Drive)

Dropbox

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

rclone clone mount dropbox:/ /dropbox/ --debug-fuse --log-file=/var/log/fuse.log -vv

> A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

2017/10/30 11:56:19 DEBUG : Backups/Customers/CUSTOMER/files/.10-22-2017-00_00_01.tar.gz.47P2gB (w): Write: len=131072, offset=821428224
2017/10/30 11:56:19 DEBUG : Backups/Customers/CUSTOMER/files/.10-22-2017-00_00_01.tar.gz.47P2gB (w): >Write: written=131072, err=<nil>
2017/10/30 11:56:19 DEBUG : fuse: -> [ID=0x4df1] Write 131072
2017/10/30 11:56:19 DEBUG : fuse: <- Getxattr [ID=0x4df2 Node=0x15 Uid=0 Gid=0 Pid=14180] "security.capability" 0 @0
2017/10/30 11:56:19 DEBUG : fuse: -> [ID=0x4df2] Getxattr error=operation not supported
2017/10/30 11:56:19 DEBUG : fuse: <- Write [ID=0x4df3 Node=0x15 Uid=0 Gid=0 Pid=14180] 0x1 131072 @821559296 fl=0 lock=0 ffl=OpenReadWrite
2017/10/30 11:56:19 DEBUG : Backups/Customers/CUSTOMER/files/.10-22-2017-00_00_01.tar.gz.47P2gB (w): Write: len=131072, offset=821559296
2017/10/30 11:56:19 DEBUG : Backups/Customers/CUSTOMER/files/.10-22-2017-00_00_01.tar.gz.47P2gB (w): >Write: written=131072, err=<nil>
2017/10/30 11:56:19 DEBUG : fuse: -> [ID=0x4df3] Write 131072
2017/10/30 11:56:19 DEBUG : fuse: <- Write [ID=0x4df4 Node=0x15 Uid=0 Gid=0 Pid=14180] 0x1 131072 @821690368 fl=0 lock=0 ffl=OpenReadWrite
2017/10/30 11:56:19 DEBUG : Backups/Customers/CUSTOMER/files/.10-22-2017-00_00_01.tar.gz.47P2gB (w): Write: len=131072, offset=821690368
2017/10/30 11:56:19 DEBUG : Backups/Customers/CUSTOMER/files/.10-22-2017-00_00_01.tar.gz.47P2gB (w): >Write: written=131072, err=<nil>
2017/10/30 11:56:19 DEBUG : fuse: -> [ID=0x4df4] Write 131072
2017/10/30 11:56:19 DEBUG : fuse: <- Getxattr [ID=0x4df5 Node=0x15 Uid=0 Gid=0 Pid=14180] "security.capability" 0 @0
2017/10/30 11:56:19 DEBUG : fuse: -> [ID=0x4df5] Getxattr error=operation not supported
2017/10/30 11:56:19 DEBUG : fuse: <- Write [ID=0x4df6 Node=0x15 Uid=0 Gid=0 Pid=14180] 0x1 131072 @821821440 fl=0 lock=0 ffl=OpenReadWrite
2017/10/30 11:56:19 DEBUG : Backups/Customers/CUSTOMER/files/.10-22-2017-00_00_01.tar.gz.47P2gB (w): Write: len=131072, offset=821821440
2017/10/30 11:56:19 DEBUG : Backups/Customers/CUSTOMER/files/.10-22-2017-00_00_01.tar.gz.47P2gB (w): >Write: written=131072, err=<nil>
2017/10/30 11:56:19 DEBUG : fuse: -> [ID=0x4df6] Write 131072
2017/10/30 11:56:19 DEBUG : fuse: <- Write [ID=0x4df7 Node=0x15 Uid=0 Gid=0 Pid=14180] 0x1 131072 @821952512 fl=0 lock=0 ffl=OpenReadWrite
**2017/10/30 11:56:19 DEBUG : Backups/Customers/CUSTOMER/files/.10-22-2017-00_00_01.tar.gz.47P2gB (w): Write: len=131072, offset=821952512
2017/10/30 11:56:43 DEBUG : Backups/Customers/CUSTOMER/files/.10-22-2017-00_00_01.tar.gz.47P2gB: Streaming chunk 7/unknown**
2017/10/30 11:56:43 DEBUG : Backups/Customers/CUSTOMER/files/.10-22-2017-00_00_01.tar.gz.47P2gB (w): >Write: written=131072, err=<nil>
2017/10/30 11:56:43 DEBUG : fuse: -> [ID=0x4df7] Write 131072
2017/10/30 11:56:43 DEBUG : fuse: <- Getxattr [ID=0x4df8 Node=0x15 Uid=0 Gid=0 Pid=14180] "security.capability" 0 @0
2017/10/30 11:56:43 DEBUG : fuse: -> [ID=0x4df8] Getxattr error=operation not supported
2017/10/30 11:56:43 DEBUG : fuse: <- Write [ID=0x4df9 Node=0x15 Uid=0 Gid=0 Pid=14180] 0x1 131072 @822083584 fl=0 lock=0 ffl=OpenReadWrite
2017/10/30 11:56:43 DEBUG : Backups/Customers/CUSTOMER/files/.10-22-2017-00_00_01.tar.gz.47P2gB (w): Write: len=131072, offset=822083584
2017/10/30 11:56:43 DEBUG : Backups/Customers/CUSTOMER/files/.10-22-2017-00_00_01.tar.gz.47P2gB (w): >Write: written=131072, err=<nil>
2017/10/30 11:56:43 DEBUG : fuse: -> [ID=0x4df9] Write 131072
2017/10/30 11:56:43 DEBUG : fuse: <- Write [ID=0x4dfa Node=0x15 Uid=0 Gid=0 Pid=14180] 0x1 131072 @822214656 fl=0 lock=0 ffl=OpenReadWrite
2017/10/30 11:56:43 DEBUG : Backups/Customers/CUSTOMER/files/.10-22-2017-00_00_01.tar.gz.47P2gB (w): Write: len=131072, offset=822214656
2017/10/30 11:56:43 DEBUG : Backups/Customers/CUSTOMER/files/.10-22-2017-00_00_01.tar.gz.47P2gB (w): >Write: written=131072, err=<nil>
2017/10/30 11:56:43 DEBUG : fuse: -> [ID=0x4dfa] Write 131072
2017/10/30 11:56:43 DEBUG : fuse: <- Getxattr [ID=0x4dfb Node=0x15 Uid=0 Gid=0 Pid=14180] "security.capability" 0 @0
2017/10/30 11:56:43 DEBUG : fuse: -> [ID=0x4dfb] Getxattr error=operation not supported
2017/10/30 11:56:43 DEBUG : fuse: <- Write [ID=0x4dfc Node=0x15 Uid=0 Gid=0 Pid=14180] 0x1 131072 @822345728 fl=0 lock=0 ffl=OpenReadWrite
2017/10/30 11:56:43 DEBUG : Backups/Customers/CUSTOMER/files/.10-22-2017-00_00_01.tar.gz.47P2gB (w): Write: len=131072, offset=822345728

![dropbox](https://user-images.githubusercontent.com/15850553/32165693-4f3dfe48-bd6c-11e7-8f5e-1907c83ef3ec.jpg)

**Comment by ncw** [comment]
> Rclone doesn't upload the files continues it pauses on transfer, pauses around 24 seconds, is this normal or it's a issue?

rclone has to get acknowlegement from dropbox after each chunk before it starts the next one.  It can't keep sending them without that acknowledgement.

I asked about this in [the dropbox forum](https://www.dropboxforum.com/t5/API-support/Using-upload-session-append-v2-is-is-possible-to-upload-chunks/m-p/225845#M12296) - there isn't a solution.

So I think that pause is just rclone uploading the chunk which is quite large (128MB by default) then waiting for the dropbox response.  In your screen shot you seem to be getting 10MB/s transfer which seems reasonable.

BTW I recommend using `rclone copy` directly rather than using rsync to copy the file into the mount - that will be much more efficient.

**Comment by ncw** [comment]
I don't think I can fix this, so I'm going to close this issue.
