### ISSUE TITLE
Using the snap makes Rclone read-only

### ISSUE THREAD

**Issue by enoch85** [ncw/rclone#1784]
> What is your rclone version (eg output from `rclone -V`)

1.3.8

> Which OS you are using and how many bits (eg Windows 7, 64 bit)

Ubuntu 16.04 Server

> Which cloud storage system are you using? (eg Google Drive)

Google Drive

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

```
root@rclone:~# rclone copy GoogleBackup:/ /mnt/GoogleBackup:2017-10-30 -v
2017/10/30 14:59:10 INFO  : Local file system at /mnt/GoogleBackup:2017-10-30: Modify window is 1ms
2017/10/30 14:59:10 ERROR : Attempt 1/3 failed with 1 errors and: mkdir /mnt/GoogleBackup:2017-10-30: read-only file system
2017/10/30 14:59:10 ERROR : Attempt 2/3 failed with 1 errors and: mkdir /mnt/GoogleBackup:2017-10-30: read-only file system
2017/10/30 14:59:10 ERROR : Attempt 3/3 failed with 1 errors and: mkdir /mnt/GoogleBackup:2017-10-30: read-only file system
2017/10/30 14:59:10 Failed to copy: mkdir /mnt/GoogleBackup:2017-10-30: read-only file system
```

--------------------------------

I tested to remove the snap and run it with a binary, and it worked, so the snap is the error here. Worth noticing is that I ran it with --classic as described here: http://www.webupd8.org/2017/02/rclone-is-now-available-as-snap-package.html

**Comment by ncw** [comment]
We've abandoned the snap package as we've been unable to make it work properly :-(  Probably our fault, but we felt our time was better spent developing rclone that fighting with every package manager under the sun.

**Comment by enoch85** [comment]
@ncw I get that. No big deal really if there was a command to update. Sure, I can make a simple script my self and run it, but would be nice of you to provide it.

**Comment by ncw** [comment]
We've just introduced a [script install for rclone](https://github.com/ncw/rclone/blob/master/docs/content/install.md#script-installation)...

which is cross platform (exept windows) and we will maintain.

Hopefully that will help.

I'm going to close this issue now.

**Comment by enoch85** [comment]
Horaay!

**Comment by jackTaw88** [comment]
@enoch85 how did you installed? It gives this error:

> error: snap "rclone" is not compatible with --classic

I did not know that a snap package need to be compatible for classic installation.

* There is also a nix package of rclone. It is developed by rclone team?

**Comment by ncw** [comment]
> * There is also a nix package of rclone. It is developed by rclone team?

No, it is maintained by @danielfullmer
