### ISSUE TITLE
Can't authorize rclone with Dropbox

### ISSUE THREAD

**Issue by vkushnir** [ncw/rclone#1785]
Failed to configure token: invalid character 'g' looking for beginning of value

> What is your rclone version (eg output from `rclone -V`)
```
rclone v1.38
- os/arch: linux/amd64
- go version: go1.9
```
> Which OS you are using and how many bits (eg Windows 7, 64 bit)
```
Ubuntu 14.04.5
```
> Which cloud storage system are you using? (eg Google Drive)
```
Dropbox
```
> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
```
rclone config
```
> A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
```
Failed to configure token: invalid character 'g' looking for beginning of value
```

Seems like authorization method changed.

**Comment by ncw** [comment]
The auth method did change from v1 to V2 auth. Rclone is supposed to change it automatically for you but it looks like that didn't work for some reason. I assume that you used an older version of rclone and have upgraded?

Run through rclone config again and edit that remote. Don't change any values but do ask for the token again and it should start working.

**Comment by vkushnir** [comment]
I don't use rclone before. It is my first try.
```
Use auto config?
 * Say Y if not sure
 * Say N if you are working on a remote or headless machine
y) Yes
n) No
y/n> n
For this to work, you will need rclone available on a machine that has a web browser available.
Execute the following on your machine:
        rclone authorize "dropbox"
Then paste the result below:
result> g******-***********************
2017/11/01 09:53:31 Failed to configure token: invalid character 'g' looking for beginning of value
root@dcr01:~/rclone/rclone-v1.38-049-gd0b9baabβ-linux-amd64#
``` 
On remote machine when I press **Apply** on API Request Authorization it starts the endless process. I need remove **redirect_uri** field from request to receive auth code.
I also receive **invalid character 'v'** message for other Dropbox account.

**Comment by ncw** [comment]
Are you using the same versions of rclone at both ends?  From your log it looks like you are using a new version at the remote end and an old version at the local end?

**Comment by vkushnir** [comment]
I try version v1.38 on both ends with same results, same for Windows same for Linux. Version 1.38 beta only for Linux because it didn’t start on Windows.

**Comment by ncw** [comment]
When I run rclone authorize I get something like this

```
$ rclone authorize dropbox
If your browser doesn't open automatically go to the following link: http://127.0.0.1:53682/auth
Log in and authorize rclone for access
Waiting for code...
Got code
Paste the following into your remote machine --->
{"access_token":"XXXX","token_type":"bearer","expiry":"0001-01-01T00:00:00Z"}
<---End paste
```

So the thing you need to paste looks like

```
{"access_token":"XXXX","token_type":"bearer","expiry":"0001-01-01T00:00:00Z"}
```

Is that what you see?

**Comment by vkushnir** [comment]
Ok.
As I write early **Waiting for code** endless process. I get token “XXXX” form webpage and give to rclone.
Now I just replace XXXX to my token from you string and authorize rclone now. But it did’t work automatically.
Thank you. I can start testing it now.

**Comment by ncw** [comment]
Oh I see what you mean.

> I need remove redirect_uri field from request to receive auth code.

You probably have a local firewall blocking rclone's web server it uses for receiving the token back. Rclone runs a web server on http://127.0.0.1:53682/ during the oauth process.

**Comment by vkushnir** [comment]
Hm. Maybe. 
I can't reproduce that problem today. All works fine. Maybe it Dropbox temporary problem.
But I think better leave fully manual option.
