### ISSUE TITLE
invalid scope with amazon drive

### ISSUE THREAD

**Issue by tjamet** [ncw/rclone#1789]
Hi,

I am trying to run rclone to authenticate with amazon drive. version:
```
rclone -V
2017/10/31 23:52:51 NOTICE: Config file "/Users/thibault/.config/rclone/rclone.conf" not found - using defaults
rclone v1.38-DEV
- os/arch: darwin/amd64
- go version: go1.8
```

I have created a login with amazon application [here] (https://developer.amazon.com/lwa/sp/overview.html) and when I run 
```
rclone config
2017/10/31 23:42:22 NOTICE: Config file "~/.config/rclone/rclone.conf" not found - using defaults
No remotes found - make a new one
n) New remote
s) Set configuration password
q) Quit config
n/s/q> n
name> amazon
Type of storage to configure.
Choose a number from below, or type in your own value
 1 / Amazon Drive
   \ "amazon cloud drive"
 2 / Amazon S3 (also Dreamhost, Ceph, Minio)
   \ "s3"
 3 / Backblaze B2
   \ "b2"
 4 / Box
   \ "box"
 5 / Dropbox
   \ "dropbox"
 6 / Encrypt/Decrypt a remote
   \ "crypt"
 7 / FTP Connection
   \ "ftp"
 8 / Google Cloud Storage (this is not Google Drive)
   \ "google cloud storage"
 9 / Google Drive
   \ "drive"
10 / Hubic
   \ "hubic"
11 / Local Disk
   \ "local"
12 / Microsoft Azure Blob Storage
   \ "azureblob"
13 / Microsoft OneDrive
   \ "onedrive"
14 / Openstack Swift (Rackspace Cloud Files, Memset Memstore, OVH)
   \ "swift"
15 / Pcloud
   \ "pcloud"
16 / QingClound Object Storage
   \ "qingstor"
17 / SSH/SFTP Connection
   \ "sftp"
18 / Webdav
   \ "webdav"
19 / Yandex Disk
   \ "yandex"
20 / http Connection
   \ "http"
Storage> 1
Amazon Application Client Id - required.
client_id>
Amazon Application Client Secret - required.
client_secret>
Auth server URL - leave blank to use Amazon's.
auth_url>
Token server url - leave blank to use Amazon's.
token_url>
Remote config
Make sure your Redirect URL is set to "http://127.0.0.1:53682/" in your custom config.
Use auto config?
 * Say Y if not sure
 * Say N if you are working on a remote or headless machine
y) Yes
n) No
y/n> y
If your browser doesn't open automatically go to the following link: http://127.0.0.1:53682/auth
Log in and authorize rclone for access
Waiting for code...
```
my browser redirects to amazon and redirected to 
`https://www.amazon.com/ap/oa?access_type=offline&client_id=<...>&redirect_uri=http%3A%2F%2F127.0.0.1%3A53682%2F&response_type=code&scope=clouddrive%3Aread_all+clouddrive%3Awrite&state=<...>`
then
`http://127.0.0.1:53682/?error_description=An+unknown+scope+was+requested&state=<...>&error=invalid_scope`

Do you have an idea how to login?

**Comment by ncw** [comment]
I'm not sure it is possible to create the right kind of app any more - at least it wasn't last time I looked - Amazon seem to have taken away that functionality.

When you edit your security profile here: https://developer.amazon.com/iba-sp/overview.html

Click on your name and you need to see a "Web Settings" tab.

I can see that on my original rclone credentials which don't work any more, but if you try to create new ones I don't think you will see them.

If you are just trying to use amazon cloud drive then [see this forum post](https://forum.rclone.org/t/rclone-has-been-banned-from-amazon-drive/2314)

**Comment by ncw** [comment]
I'm going to close this now since I don't think it is something I can help with further.
