### ISSUE TITLE
Gdrive trying to sync existing file

### ISSUE THREAD

**Issue by Ferni7** [ncw/rclone#179]
I'm going a bit crazy here... running a sync from local drive to google drive and it keeps trying to upload a few .AVI files that already exist

The filesize and md5sum match, so no idea why... any help?

Z:\rclone>rclone --dry-run --transfers 1 --checksum --bwlimit 50k --exclude-from exclude-file.txt --config .rclone.conf -v sync "V:\Pictures\Wedding stuff\Wedding DAY\Wedding" "gdrive:rPhotos/Wedding stuff/Wedding DAY/Wedding"

...
2015/10/25 15:18:33 IMG_5702.JPG: Size and MD5SUM of src and dst objects identical
2015/10/25 15:18:33 IMG_5702.JPG: Unchanged skipping
2015/10/25 15:18:33 IMG_5703.JPG: Size and MD5SUM of src and dst objects identical
2015/10/25 15:18:33 IMG_5703.JPG: Unchanged skipping
2015/10/25 15:18:33 MVI_2628.AVI: Not copying as --dry-run
2015/10/25 15:18:33 MVI_2649.AVI: Not copying as --dry-run
2015/10/25 15:18:33 MVI_5662.AVI: Not copying as --dry-run
2015/10/25 15:18:33 MVI_5669.AVI: Not copying as --dry-run
2015/10/25 15:18:33 Thumbs.db: Excluding from sync
2015/10/25 15:18:33 MVI_5670.AVI: Not copying as --dry-run
2015/10/25 15:18:33 IMG_5701.JPG: Size and MD5SUM of src and dst objects identical
2015/10/25 15:18:33 IMG_5701.JPG: Unchanged skipping
2015/10/25 15:18:33 IMG_5704.JPG: Size and MD5SUM of src and dst objects identical
2015/10/25 15:18:33 IMG_5704.JPG: Unchanged skipping
2015/10/25 15:18:33 IMG_5705.JPG: Size and MD5SUM of src and dst objects identical
...

Z:\rclone>rclone ls "gdrive:rPhotos/Wedding Stuff/Wedding DAY/Wedding/MVI_2628.AVI"
711183066 MVI_2628.AVI

Transferred:            0 Bytes (   0.00 kByte/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:        5.6s

Z:\rclone>rclone md5sum "gdrive:rPhotos/Wedding Stuff/Wedding DAY/Wedding/MVI_2628.AVI"
392ec1a21a62150bb7fe03350b905161  MVI_2628.AVI

Transferred:            0 Bytes (   0.00 kByte/s)
Errors:                 0
Checks:                 1
Transferred:            0
Elapsed time:        7.1s

Z:\rclone>rclone ls "V:\Pictures\Wedding stuff\Wedding DAY\Wedding\MVI_2628.AVI"
711183066 MVI_2628.AVI

Transferred:            0 Bytes (   0.00 kByte/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:       100ms

Z:\rclone>rclone md5sum "V:\Pictures\Wedding stuff\Wedding DAY\Wedding\MVI_2628.AVI"
392ec1a21a62150bb7fe03350b905161  MVI_2628.AVI

Transferred:            0 Bytes (   0.00 kByte/s)
Errors:                 0
Checks:                 1
Transferred:            0
Elapsed time:         12s

**Comment by ncw** [comment]
I wonder if this is a duplicate file problem? Can you check in the google drive web interface that there aren't duplicate copies of the avi files? If there are, delete all but one and the sync should work properly after that.

Sometimes rclone causes duplicate files on drive and I haven't figured out why yet!

**Comment by Ferni7** [comment]
If i search for "MVI_2628.AVI" in the google drive webif, I only get the one match.. but it does find an additional file in the trash that matches.. but that would probably only be because I was playing around trying to get it to work... I'll remove that from trash and try again later...

**Comment by Ferni7** [comment]
Tested again making sure only 1 MVI_2628.AVI is there and it still wants to transfer it....

Any more ideas?

**Comment by ncw** [comment]
Can you send me the output when you do the copy without `--dry-run` but with the other flags you used?  That would be useful information.  Rclone logs whether it is updating an existing file or not.

Can you try doing

    rclone ls "gdrive:rPhotos/Wedding stuff/Wedding DAY/Wedding" > files.txt

Then search in `files.txt` for `MVI_2628.AVI` and see whether it is in there more than once? And the size is as you expect.  Replacing `ls` with `md5sum` and repeating would be useful too. That should check the directory traversal code is working as expected.

The results of

    rclone -v check "V:\Pictures\Wedding stuff\Wedding DAY\Wedding" "gdrive:rPhotos/Wedding stuff/Wedding DAY/Wedding"

Would be interesting too (check doesn't support excludes yet (see #169) so there will be a bit of noise in there).

What happens if you try the sync without `--checksum`?

Have you tried the sync with `--size-only`?

Thanks for helping me work out what is going on!

Nick

**Comment by Ferni7** [comment]
Sorry for taking so long to get back to you, just been so busy.. Thanks for taking a look.

So rclone ls "gdrive:rPhotos/Wedding stuff/Wedding DAY/Wedding" > files.txt does not show the file MVI_2628.AVI at all, in fact it's showing no AVI files at all but looking through the drive.google.com webpage it shows 5.... 

Running rclone md5sum "gdrive:rPhotos/Wedding stuff/Wedding DAY/Wedding" doesn't list any of the AVI files either...

Output of check thinks the files don't exist in gdrive either... based on this it explains why it tries to upload again since ls/md5sum and check all report those files don't exist on google drive...

Z:\rclone>rclone -v check "V:\Pictures\Wedding stuff\Wedding DAY\Wedding" "gdrive:rPhotos/Wedding stuff/Wedding DAY/Wedding"
2015/11/07 14:03:36 Google drive root 'rPhotos/Wedding stuff/Wedding DAY/Wedding': Modify window is 1ms
2015/11/07 14:03:36 Google drive root 'rPhotos/Wedding stuff/Wedding DAY/Wedding': Building file list
2015/11/07 14:03:37 Google drive root 'rPhotos/Wedding stuff/Wedding DAY/Wedding': Finished reading
2015/11/07 14:03:37 Google drive root 'rPhotos/Wedding stuff/Wedding DAY/Wedding': 0 files not in Local file system at \\?\V:\Pictures\Wedding stuff\Wedding DAY\Wedding
2015/11/07 14:03:37 Local file system at \\?\V:\Pictures\Wedding stuff\Wedding DAY\Wedding: 6 files not in Google drive root 'rPhotos/Wedding stuff/Wedding DAY/Wedding'
2015/11/07 14:03:37 MVI_5670.AVI: File not in Google drive root 'rPhotos/Wedding stuff/Wedding DAY/Wedding'
2015/11/07 14:03:37 Thumbs.db: File not in Google drive root 'rPhotos/Wedding stuff/Wedding DAY/Wedding'
2015/11/07 14:03:37 MVI_5669.AVI: File not in Google drive root 'rPhotos/Wedding stuff/Wedding DAY/Wedding'
2015/11/07 14:03:37 MVI_2628.AVI: File not in Google drive root 'rPhotos/Wedding stuff/Wedding DAY/Wedding'
2015/11/07 14:03:37 MVI_5662.AVI: File not in Google drive root 'rPhotos/Wedding stuff/Wedding DAY/Wedding'
2015/11/07 14:03:37 MVI_2649.AVI: File not in Google drive root 'rPhotos/Wedding stuff/Wedding DAY/Wedding'
2015/11/07 14:03:37 Google drive root 'rPhotos/Wedding stuff/Wedding DAY/Wedding': Waiting for checks to finish
2015/11/07 14:03:37 IMG_5685.JPG: OK
2015/11/07 14:03:37 IMG_5688.JPG: OK
2015/11/07 14:03:37 IMG_5647.JPG: OK
2015/11/07 14:03:37 IMG_5682.JPG: OK
2015/11/07 14:03:37 IMG_5676.JPG: OK
2015/11/07 14:03:37 IMG_5666.JPG: OK
2015/11/07 14:03:37 IMG_5691.JPG: OK
2015/11/07 14:03:37 IMG_5673.JPG: OK
2015/11/07 14:03:37 IMG_5697.JPG: OK
2015/11/07 14:03:37 IMG_5690.JPG: OK
2015/11/07 14:03:37 IMG_5668.JPG: OK
2015/11/07 14:03:37 IMG_5692.JPG: OK
2015/11/07 14:03:37 IMG_5663.JPG: OK
2015/11/07 14:03:37 IMG_5660.JPG: OK
2015/11/07 14:03:37 IMG_5658.JPG: OK
2015/11/07 14:03:37 IMG_5649.JPG: OK
2015/11/07 14:03:37 IMG_5667.JPG: OK
2015/11/07 14:03:37 IMG_5713.JPG: OK
2015/11/07 14:03:37 IMG_5700.JPG: OK
2015/11/07 14:03:37 IMG_5686.JPG: OK
2015/11/07 14:03:37 IMG_5650.JPG: OK
2015/11/07 14:03:38 IMG_5675.JPG: OK
2015/11/07 14:03:38 IMG_5693.JPG: OK
2015/11/07 14:03:38 IMG_5645.JPG: OK
2015/11/07 14:03:38 IMG_5687.JPG: OK
2015/11/07 14:03:38 IMG_5677.JPG: OK
2015/11/07 14:03:38 IMG_5716.JPG: OK
2015/11/07 14:03:38 IMG_5654.JPG: OK
2015/11/07 14:03:38 IMG_5717.JPG: OK
2015/11/07 14:03:38 IMG_5681.JPG: OK
2015/11/07 14:03:38 IMG_5653.JPG: OK
2015/11/07 14:03:38 IMG_5659.JPG: OK
2015/11/07 14:03:38 IMG_5694.JPG: OK
2015/11/07 14:03:38 IMG_5689.JPG: OK
2015/11/07 14:03:38 IMG_5710.JPG: OK
2015/11/07 14:03:38 IMG_5683.JPG: OK
2015/11/07 14:03:38 IMG_5695.JPG: OK
2015/11/07 14:03:38 IMG_5674.JPG: OK
2015/11/07 14:03:38 IMG_5665.JPG: OK
2015/11/07 14:03:38 IMG_5648.JPG: OK
2015/11/07 14:03:38 IMG_5646.JPG: OK
2015/11/07 14:03:38 IMG_5698.JPG: OK
2015/11/07 14:03:38 IMG_5696.JPG: OK
2015/11/07 14:03:38 IMG_5701.JPG: OK
2015/11/07 14:03:38 IMG_5703.JPG: OK
2015/11/07 14:03:38 IMG_5679.JPG: OK
2015/11/07 14:03:38 IMG_5664.JPG: OK
2015/11/07 14:03:38 IMG_5704.JPG: OK
2015/11/07 14:03:38 IMG_5705.JPG: OK
2015/11/07 14:03:38 IMG_5678.JPG: OK
2015/11/07 14:03:38 IMG_5644.JPG: OK
2015/11/07 14:03:38 .picasa.ini: OK
2015/11/07 14:03:38 IMG_5655.JPG: OK
2015/11/07 14:03:38 IMG_5715.JPG: OK
2015/11/07 14:03:38 IMG_5672.JPG: OK
2015/11/07 14:03:38 IMG_5680.JPG: OK
2015/11/07 14:03:38 IMG_5657.JPG: OK
2015/11/07 14:03:38 IMG_5702.JPG: OK
2015/11/07 14:03:38 IMG_5684.JPG: OK
2015/11/07 14:03:38 IMG_5661.JPG: OK
2015/11/07 14:03:38 IMG_5706.JPG: OK
2015/11/07 14:03:38 IMG_5651.JPG: OK
2015/11/07 14:03:38 IMG_5671.JPG: OK
2015/11/07 14:03:38 IMG_5699.JPG: OK
2015/11/07 14:03:38 Google drive root 'rPhotos/Wedding stuff/Wedding DAY/Wedding': 6 differences found
2015/11/07 14:03:38 Failed to check: 6 differences found

**Comment by Ferni7** [comment]
So i did a bit more testing and moving one of the MVI files around... if i put it in rPhotos (drag/drop in google webif) then it finds it, but if i put it in rPhotos/Wedding stuff" then it doesn't... could it be to do with spaces in folder name for some reason?

Z:\rclone>rclone md5sum "gdrive:rPhotos/MVI_5670.AVI"
c686235f5e2d446d46f712eb0fd5c995  MVI_5670.AVI

Transferred:            0 Bytes (   0.00 kByte/s)
Errors:                 0
Checks:                 1
Transferred:            0
Elapsed time:        2.6s


Z:\rclone>rclone md5sum "gdrive:rPhotos/Wedding stuff/MVI_5670.AVI"
2015/11/07 14:10:38 Google drive root 'rPhotos/Wedding stuff/MVI_5670.AVI': Couldn't find root: Couldn't find directory: "rPhotos/Wedding stuff/MVI_5670.AVI"

Transferred:            0 Bytes (   0.00 kByte/s)
Errors:                 1
Checks:                 0
Transferred:            0
Elapsed time:        4.1s

**Comment by ncw** [comment]
Thanks for doing some good investigation.  It seems we are narrowing the problem down. I tried to reproduce the problem with some spaces in the directory names (good idea) but that didn't work, alas.

So it looks like
  * the files MVI_5670.AVI etc are on your drive
  * they don't appear in the rclone listing

I can't figure out why at the moment, but if you could do

     rclone -v --dump-bodies ls "gdrive:rPhotos/Wedding stuff/Wedding DAY/Wedding" >ls.log 2>&1

and email `ls.log` to me privately ( nick@craig-wood.com ) that might give me a clue!  The dump will have some `Authorization:` lines in so don't post it here .  I'll delete the log as soon as I'm finished analysing it. You can delete the `Authorization:` lines before sending it to me if you like.

Thanks

Nick

**Comment by Ferni7** [comment]
Sent :)

**Comment by ncw** [comment]
Hmm, so the AVI files aren't in the listing at all which explains rclone's behaviour perfectly.

Did you upload those files with rclone?  Or were they shared with you?

Can you try this?
  * goto the [google API explorer](https://developers.google.com/drive/v2/reference/files/list#try-it)
  * And put this as the q parameter `"0B6eUhdSrAP1zYkZrcWhSSmRIWk0" in parents`
  * That should list everything in that directory.
  * You'll have to authorize the API explorer first (flip the switch)

If that shows the AVI files then can you email me the output please!

Thanks

Nick

**Comment by Ferni7** [comment]
Yes I used rclone to upload the files (from my dream objects account in case it matters...)

I'm not sure if i'm doing this right but it's giving me an error... in the Files: list page i put "0B6eUhdSrAP1zYkZrcWhSSmRIWk0" no quotes in the 'q' field with nothing else and it says The value of the parameter 'q' is invalid.

400 OK
- SHOW HEADERS -
{
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "invalid",
    "message": "Invalid query",
    "locationType": "parameter",
    "location": "q"
   }
  ],
  "code": 400,
  "message": "Invalid query"
 }

**Comment by ncw** [comment]
You need to put exactly this in the q field

    "0B6eUhdSrAP1zYkZrcWhSSmRIWk0" in parents

And hopefully that will do something.

**Comment by Ferni7** [comment]
Ok, I'm so embarrassed... I ran your query in the API Explorer and no AVI, logged onto google drive webif again and noticed 2 directories "Wedding Stuff" and Wedding stuff" - I swear only 1 was showing up in google drive webif previously.

Anyway I'm now finally running my sync.. so sorry for wasting your time! Donation coming your way (it was coming your way anyway as i find rclone fits exactly what i was looking for!)

**Comment by ncw** [comment]
Aha! Thanks for clearing that up - I hate mysteries where code is concerned. Yes drive is case sensitive (just realised that the storage overview page has it exactly backwards!) 

You posted the command lines you used and if you look back in this thread you can see the difference there which I really should have spotted - so don't feel guilty! 

Glad we sorted out! 

Nick

**Comment by ncw** [comment]
I think we've sorted this one out now, so I'm going to close the issue.
