### ISSUE TITLE
no specific decryption instructions

### ISSUE THREAD

**Issue by ucwhatic** [ncw/rclone#1796]
I have spent the last 2 hours reading documentation and man pages trying to figure out exactly what the command is to get my crypt remote to decrypt the remote I set up? 

WHY SO CONFUSING??

Y U NO rclone decrypt ?

After reading https://rclone.org/crypt/ Im just more confused. Ctrl+H'ing "decrypt" on that page brings up exactly two results. Both within the first 3 lines of the page. Maybe they never got around to explaining it?? AT some point we will all need to decrypt these shares people. I needed them about 2 hours ago.

**Comment by ncw** [comment]
crypt does both encrypt and decrypt - that is why it is called crypt.

So if you write files into crypt it will encrypt them, and if you read files from it it will decrypt them.

Does that help?
