### ISSUE TITLE
 rclone tree --sort-ctime ---- gdrive --- crashing

### ISSUE THREAD

**Issue by trustbyte** [ncw/rclone#1797]
Hello,

rclone crashes when sorting by creation time of files on a google drive. Am i using wrong the command or is it a bug?
both stable and beta.

thanks!

`2017/11/05 10:18:15 DEBUG : Using config file from "/home/vlcrec/.config/rclone/rclone.conf"
2017/11/05 10:18:15 DEBUG : rclone: Version "v1.38-083-g68d0b5adβ" starting with parameters ["rclone" "tree" "-vv" "--sort-ctime" "--noindent" "-o" "/tmp/aici" "remote:seriale"]
2017/11/05 10:18:16 INFO  : Google drive root 'seriale': Modify window is 1ms
2017/11/05 10:18:16 DEBUG : Stat: filePath="/"
2017/11/05 10:18:16 DEBUG : >Stat: fi=, err=<nil>
2017/11/05 10:18:16 DEBUG : ReadDir: dir=/
2017/11/05 10:18:16 DEBUG : >ReadDir: names=[24-ser.asf Nov01-1801.asf Nov02-1801.asf Nov03-1801.asf Nov04-1801.asf Oct25-1759.asf Oct26-1759.asf Oct27-1759.asf Oct28-1759.asf Oct29-1759.asf Oct30-1801.asf Oct31-1801.asf], err=<nil>
2017/11/05 10:18:16 DEBUG : Stat: filePath="/24-ser.asf"
2017/11/05 10:18:16 DEBUG : >Stat: fi=24-ser.asf, err=<nil>
2017/11/05 10:18:16 DEBUG : Stat: filePath="/Nov01-1801.asf"
2017/11/05 10:18:16 DEBUG : >Stat: fi=Nov01-1801.asf, err=<nil>
2017/11/05 10:18:16 DEBUG : Stat: filePath="/Nov02-1801.asf"
2017/11/05 10:18:16 DEBUG : >Stat: fi=Nov02-1801.asf, err=<nil>
2017/11/05 10:18:16 DEBUG : Stat: filePath="/Nov03-1801.asf"
2017/11/05 10:18:16 DEBUG : >Stat: fi=Nov03-1801.asf, err=<nil>
2017/11/05 10:18:16 DEBUG : Stat: filePath="/Nov04-1801.asf"
2017/11/05 10:18:16 DEBUG : >Stat: fi=Nov04-1801.asf, err=<nil>
2017/11/05 10:18:16 DEBUG : Stat: filePath="/Oct25-1759.asf"
2017/11/05 10:18:16 DEBUG : >Stat: fi=Oct25-1759.asf, err=<nil>
2017/11/05 10:18:16 DEBUG : Stat: filePath="/Oct26-1759.asf"
2017/11/05 10:18:16 DEBUG : >Stat: fi=Oct26-1759.asf, err=<nil>
2017/11/05 10:18:16 DEBUG : Stat: filePath="/Oct27-1759.asf"
2017/11/05 10:18:16 DEBUG : >Stat: fi=Oct27-1759.asf, err=<nil>
2017/11/05 10:18:16 DEBUG : Stat: filePath="/Oct28-1759.asf"
2017/11/05 10:18:16 DEBUG : >Stat: fi=Oct28-1759.asf, err=<nil>
2017/11/05 10:18:16 DEBUG : Stat: filePath="/Oct29-1759.asf"
2017/11/05 10:18:16 DEBUG : >Stat: fi=Oct29-1759.asf, err=<nil>
2017/11/05 10:18:16 DEBUG : Stat: filePath="/Oct30-1801.asf"
2017/11/05 10:18:16 DEBUG : >Stat: fi=Oct30-1801.asf, err=<nil>
2017/11/05 10:18:16 DEBUG : Stat: filePath="/Oct31-1801.asf"
2017/11/05 10:18:16 DEBUG : >Stat: fi=Oct31-1801.asf, err=<nil>
panic: interface conversion: interface {} is nil, not *syscall.Stat_t

goroutine 1 [running]:
github.com/ncw/rclone/vendor/github.com/a8m/tree.CTimeSort(0x14a4240, 0xc42016b0f0, 0x14a4240, 0xc42016ace0, 0xc420109820)
        /home/travis/gopath/src/github.com/ncw/rclone/vendor/github.com/a8m/tree/csort_unix.go:11 +0xd4
github.com/ncw/rclone/vendor/github.com/a8m/tree.ByFunc.Less(0xc42017b180, 0xc, 0x10, 0xf4c610, 0x6, 0x0, 0x20)
        /home/travis/gopath/src/github.com/ncw/rclone/vendor/github.com/a8m/tree/sort.go:14 +0x6e
github.com/ncw/rclone/vendor/github.com/a8m/tree.(*ByFunc).Less(0xc4200df7e0, 0x6, 0x0, 0x411b2c)
        <autogenerated>:1 +0x6b
sort.quickSort(0x14a14c0, 0xc4200df7e0, 0x0, 0xc, 0x8)
        /home/travis/.gimme/versions/go1.9.2.linux.amd64/src/sort/sort.go:207 +0x1b2
sort.Sort(0x14a14c0, 0xc4200df7e0)
        /home/travis/.gimme/versions/go1.9.2.linux.amd64/src/sort/sort.go:220 +0x79
github.com/ncw/rclone/vendor/github.com/a8m/tree.(*Node).sort(0xc420050fc0, 0x1504540)
        /home/travis/gopath/src/github.com/ncw/rclone/vendor/github.com/a8m/tree/node.go:179 +0x1b8
github.com/ncw/rclone/vendor/github.com/a8m/tree.(*Node).Visit(0xc420050fc0, 0x1504540, 0xc4202885a0, 0x0)
        /home/travis/gopath/src/github.com/ncw/rclone/vendor/github.com/a8m/tree/node.go:152 +0x8a9
github.com/ncw/rclone/cmd/tree.Tree(0x14a6400, 0xc42017ac00, 0x1498980, 0xc42000c040, 0x1504540, 0x5, 0xc4200eb680)
        /home/travis/gopath/src/github.com/ncw/rclone/cmd/tree/tree.go:126 +0x18c
github.com/ncw/rclone/cmd/tree.glob..func1.1(0x149b800, 0xc420109b68)
        /home/travis/gopath/src/github.com/ncw/rclone/cmd/tree/tree.go:111 +0x54
github.com/ncw/rclone/cmd.Run(0x7ffe49290000, 0x14fb0e0, 0xc420109d00)
        /home/travis/gopath/src/github.com/ncw/rclone/cmd/cmd.go:246 +0xa7
github.com/ncw/rclone/cmd/tree.glob..func1(0x14fb0e0, 0xc4201971a0, 0x1, 0x6)
        /home/travis/gopath/src/github.com/ncw/rclone/cmd/tree/tree.go:110 +0x1c5
github.com/ncw/rclone/vendor/github.com/spf13/cobra.(*Command).execute(0x14fb0e0, 0xc4201970e0, 0x6, 0x6, 0x14fb0e0, 0xc4201970e0)
        /home/travis/gopath/src/github.com/ncw/rclone/vendor/github.com/spf13/cobra/command.go:654 +0x2a2
github.com/ncw/rclone/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x14f42a0, 0xc42023df70, 0x4046a4, 0xc42005a058)
        /home/travis/gopath/src/github.com/ncw/rclone/vendor/github.com/spf13/cobra/command.go:729 +0x2fe
github.com/ncw/rclone/vendor/github.com/spf13/cobra.(*Command).Execute(0x14f42a0, 0xc420217dc0, 0x20)
        /home/travis/gopath/src/github.com/ncw/rclone/vendor/github.com/spf13/cobra/command.go:688 +0x2b
main.main()
        /home/travis/gopath/src/github.com/ncw/rclone/rclone.go:15 +0x31
`

**Comment by ncw** [comment]
This looks like a bug in the tree library.  I'll fix it up in a bit!  Thanks for reporting.

**Comment by ncw** [comment]
I've fixed this in https://beta.rclone.org/v1.38-092-g8c8abfd6/ (uploaded in 15-30 mins)

Note that rclone doesn't support ctimes so this will be the same as --sort-mtime
