### ISSUE TITLE
sftp remote to specified folder : "too many colons in address"

### ISSUE THREAD

**Issue by sheepdestroyer** [ncw/rclone#1800]
rclone 1.38

I want to create a sftp remote to a different folder than the user's login folder by specifying the path as hostname:path but I get the error message : "too many colons in address".

For instance, with the root user, by only specifying the hostname, I would normally get a remote to /root/, but in order to get to /, I would like to be able to specify hostname:/ or hostname:~/../

**Comment by ncw** [comment]
If you want to do this you can set up the remote without the path then just supply it in the command line.

So you can set set up your remote like this

```
[myremote]
type = sftp
host = localhost
user = sftptest
port = 
pass = 
```

Then you should find `myremote:/` works just fine.

You can't set a starting folder in the remote at the moment.

**Comment by sheepdestroyer** [comment]
Yes, that works ; I wanted to be able to do that with RcloneBrowser which does not permit to manually set a path ; but I guess that should better be fixed by that project so I opened an issue there : https://github.com/mmozeiko/RcloneBrowser/issues/82

**Comment by ncw** [comment]
OK great!  I'll close this now then.
