### ISSUE TITLE
support password protected http and webdav sharing for "serve", with https

### ISSUE THREAD

**Issue by tvvid** [ncw/rclone#1802]
when rclone is serving files through serve command it shares files without password,
so it would be great enhancement to add secure https and password sharing options for serve webdav and http.

**Comment by easy90rider** [comment]
@ncw any update on this?

**Comment by ncw** [comment]
I'll do this soon...

I'm planning a htpasswd facility, but maybe supplying the username and password on the command line is useful - what do you think?

**Comment by easy90rider** [comment]
I think supplying U+P on the command line would be very useful. -in case one only needs password protected access once, or if there's a script that does the 

htpasswd is good on the long run. 

Personally I would use both.

**Comment by ncw** [comment]
I've done this here

https://beta.rclone.org/v1.39-154-g358c1fba/ (uploaded in 15-30 mins)

Here are the new flags to `serve http` and `serve webdav`

#### Authentication

By default this will serve files without needing a login.

You can either use an htpasswd file which can take lots of users, or
set a single username and password with the --user and --pass flags.

Use --htpasswd /path/to/htpasswd to provide an htpasswd file.  This is
in standard apache format and supports MD5, SHA1 and BCrypt for basic
authentication.  Bcrypt is recommended.

To create an htpasswd file:

    touch htpasswd
    htpasswd -B htpasswd user
    htpasswd -B htpasswd anotherUser

The password file can be updated while rclone is running.

Use --realm to set the authentication realm.

#### SSL/TLS

By default this will serve over http.  If you want you can serve over
https.  You will need to supply --cert and --key.
If you wish to do client side certificate validation then you will
need to supply --client-ca also.

----

I'm going to close this now - please comment or reopen if you have a problem.
