### ISSUE TITLE
sftp: no common algorithm for key exchange

### ISSUE THREAD

**Issue by grinsted** [ncw/rclone#1810]
I have a sftp remote and I get the error : "no common algorithm for key exchange. server offered [diffie-hellman-group-exchange-sha256]"

when i try to copy a file to it. 

> What is your rclone version (eg output from `rclone -V`)

v1.38-093-gc65734beta
linux/amd64
go 1.9.2

**Comment by ncw** [comment]
It looks like ""diffie-hellman-group-exchange-sha256" isn't supported by the [go ssh library](https://godoc.org/golang.org/x/crypto/ssh)

I see you found the upstream issue!

I don't know whether `diffie-hellman-group-exchange-sha256` is secure or not.  According to [the github crypto deprecation notice](https://githubengineering.com/crypto-deprecation-notice/) they are adding support for `diffie-hellman-group-exchange-sha256` so it can't be too terrible.

**Comment by salmanwaseem007** [comment]
I need support for [diffie-hellman-group-exchange-sha256]. Any idea when can this be added?

**Comment by breml** [comment]
@salmanwaseem007 There is some movement in https://github.com/golang/go/issues/17230 so maybe this will be added "soon-ish".

**Comment by fuyi** [comment]
@ncw The  support for`diffie-hellman-group-exchange-sha256` is now added to ssh library [here](https://github.com/golang/crypto/commit/57b3e21c3d5606066a87e63cfe07ec6b9f0db000). But as it states in the code:

> the key exchange algorithms diffie-hellman-group-exchange-sha1 and diffie-hellman-group-exchange-sha256 are not included in the default list

Rclone needs to opt in the support. Any idea how?

**Comment by breml** [comment]
@fuyi @ncw see here for an example how to opt-in for `diffie-hellman-group-exchange-sha256`: https://github.com/golang/crypto/blob/master/ssh/test/session_test.go#L420-L427

**Comment by ncw** [comment]
Does one of you want to send a pull request implementing this? Does it need to be optional?
