### ISSUE TITLE
--no-traverse flag is obsolete

### ISSUE THREAD

**Issue by ncw** [ncw/rclone#1813]
This doesn't appear to do anything any more.  The new sync method means we don't traverse the destination when we are doing a `copy` anyway so it is now irrelevant.

Deprecate and update the docs.

**Comment by ajkis** [comment]
Is there any new flag ?

**Comment by ncw** [comment]
> Is there any new flag ?

It isn't needed any more, and it actually doesn't do anything.

> Would --fast-list be faster when moving files from local to drive

Google drive doesn't support `--fast-list`, but in general `--fast-list` is usually (but not always) faster but it definitely uses more memory.

**Comment by xerrni** [comment]
It fixes this issue:
https://github.com/ncw/rclone/pull/1950
