### ISSUE TITLE
Question: Cleanup deleted directories?

### ISSUE THREAD

**Issue by jD91mZM2** [ncw/rclone#1819]
Hey! When I transfer now, a bunch of times I see old folders laying around (like renamed, deleted, et.c). I'm wondering how I get rid of those :)

**Note:** A lot of times I've `sync`ed it fails because of changed checksum. I've excluded those directories because they're not important anyways. So, while it *shouldn't* happen again, I still want to get rid of the old stuff.  
**Note 2**: I'm using Amazon S3.

*Sorry if this is the wrong place for questions*

**Comment by ncw** [comment]
Questions are best on [the rclone forum](https://forum.rclone.org/)...

Please post your question there along with which commands you are running and I'll try to work out what is happening!
