### ISSUE TITLE
Rclone --bwlimit | Weekday Schedule

### ISSUE THREAD

**Issue by MrCheeze96** [ncw/rclone#1822]
Hi

It would be nice to have the possibility to specify which days to apply a specific bandwidth limit.

See [my question in the forum](https://forum.rclone.org/t/rclone-bwlimit-weekday-schedule/4224):
> I’m looking for a way to setup different bandwidth limits depending on the day off the week. So I can for example use one limit for workdays and one for weekends. Note that I can’t just “turn off” the bandwidth limit as I have other stuff going on but I want to raise the speed a bit.

> If it is something that needs to be developed it would be good if it’s possible to specify by day (Mon, Tue, Wed, Thu, Fri, Sat, Sun), and to make some schedules easier, also by “workday” (Mon, Tue, Wed, Thu, Fri) and “weekend” (Sat, Sun).

**Comment by TenGumis** [comment]
I look through the code to find a solution. @ncw do you have any comments?

**Comment by ncw** [comment]
@TenGumis sorry for the delay in replying...

This is the place to look at: https://github.com/ncw/rclone/blob/master/fs/bwtimetable.go - you'd need to extend that to a weekly schedule.

I'm not sure exactly how the command line would look - I'd probably have a think about that first...

The internals would be easy enough to extend - adding a day of week and extending the timetable to allow a week.

**Comment by TenGumis** [comment]
@ncw 
You mean that I should extend BwTimeSlot to:
`type BwTimeSlot struct {
	HHMM         int
	DayOfTheWeek string
	Bandwidth    SizeSuffix
}`
Can string format be "dayOfWeek-hh:mm,banwidth"? ex: "Tue-10:00,1G"
Should we continue to accept the previous format without the day of the week?

**Comment by ncw** [comment]
@TenGumis sorry for the delay replying...
> You mean that I should extend BwTimeSlot to:
> `type BwTimeSlot struct { HHMM int DayOfTheWeek string Bandwidth SizeSuffix }`

Yes, something like that

> Can string format be "dayOfWeek-hh:mm,banwidth"? ex: "Tue-10:00,1G"

Looks OK!

> Should we continue to accept the previous format without the day of the week?

Yes.  Probably if you leave off the day of week it should mean all the days in the week.

**Comment by TenGumis** [comment]
@ncw I've got stuck
> Yes. Probably if you leave off the day of week it should mean all the days in the week.

So calling func (x *BwTimetable) Set(s string) should validate that when is inserted a table every or none slot must contain weekday? If yes where we should contain information about "mode"? In my opinion function LimitAt should have information about that. Make every weekday invalid (ex. -1) will be enough solution?

**Comment by ncw** [comment]
@TenGumis sorry I missed your comment.  It appears you've got over the problem in your pull request - is that correct?

**Comment by TenGumis** [comment]
Yes, I found a solution. 
Thanks for reply.

**Comment by ncw** [comment]
This has now been done thanks to @TenGumis 

https://beta.rclone.org/v1.42-005-g56e1e820/ (uploaded in 15-30 mins)

This will be in [the latest beta](https://beta.rclone.org) from now on and in v1.43
