### ISSUE TITLE
Can't tell if Object.Open supports RangeOption or not

### ISSUE THREAD

**Issue by ncw** [ncw/rclone#1825]
Remotes can optionally support RangeOption in Open.  It would be very useful if callers could know in advance which will work.

SeekOption is a required feature so this will work with all remotes.

Fix this by promoting RangeOption could to be a required option - this will need a bit of wrapping with a LimitedReader for remotes which really don't support it.  That would be relatively easy - the wrapping code will be the same for all the remotes so can be written once in `fs/`.

This needs a test also which should check for
  * start and/or end being -1
  * end being bigger than the  length of the object
  * see https://tools.ietf.org/html/rfc7233#section-2.1 for other possble ideas

Once implemented we can use to
  * [x] make `cat` more efficient.
  * [x] make `cryptcheck` fetch of the nonce more efficient (using RangeOption)
  * [ ] optionally make mount use it to read all its data rather than streaming.
  * [x] remove patch preventing the checks running on CI
  * [x] add RangeOption to mandatory options
  * [x] remove seek option in cache

From #1585

**Comment by B4dM4n** [comment]
So the goal of this issue is to implement RangeOption in every remote?
If that's the case i would go one step further and remove `fs.SeekOption{Offset:x}` as it is equivalent to `fs.RangeOption{Start: x, End: -1}`. It could be replaced by
```go
func SeekOption(offset int64) *RangeOption {
  return &RangeOption{Start: offset, End: -1}
}
```
If range support is implemented for all remotes even this could be obsolete.

I will look into some remotes and try to add `RangeOption` support.

**Comment by B4dM4n** [comment]
While reading into the crypt remote i realized a design issue in the approach taken in #1987.
When a remote implements `io.Seeker`, like crypt does, `Open(&fs.RangeOption{...})` is useless, as the `io.Seeker` interface is the preferred method.
So chunked reading for `backend -> crypt -> vfs` will be hard to implement, as a new interface like `RangeSeeker` would be needed throughout the whole project.

From my current view into the project structure a better approach could be `backend -> chunked-reader -> crypt -> vfs`. The chunked-reader could implement `io.ReadCloser + io.Seeker + fs.RangeSeeker`, where `fs.RangeSeeker` will request  the underlying `Object` 
```go
type RangeSeeker interface {
  // RangeSeek behaves like a call to Seek(offset int64, whence int) with the
  // addition of only requesting length bytes from the underlying remote
  func RangeSeek(offset int64, whence int, length int64) (int64, error)
}
```
A `Read` call beyond the requested length of `RangeSeek` will trigger a new `Open` following the normal chunk reading rules

This way all operations could benefit from chunked-reading and operation which depend on small seeks can (like crypt and cache) can use `RangeSeek`.

**Comment by ncw** [comment]
@B4dM4n wrote
> So the goal of this issue is to implement RangeOption in every remote?

Yes

> If that's the case i would go one step further and remove fs.SeekOption{Offset:x} as it is equivalent to fs.RangeOption{Start: x, End: -1}. It could be replaced by

That is a good idea :-)

I've made a start with this

I've added a test to make RangeOption manadatory for remotes in 8653944a6daa2f21e2ad73de723dd136e65a420c and fixed up onedrive and azureblob.

This still leaves

* box - I think this may be OK, it is just that box seems to be broken...
* cache
* crypt
* ftp
* local
* sftp

> I will look into some remotes and try to add RangeOption support.

If you'd like to have a go at any of these @B4dM4n then please let me know which so we don't duplicate effort.

Note that the integration tests for all the remotes run once per day with [the results here](https://pub.rclone.org/integration-tests/).

**Comment by ncw** [comment]
@B4dM4n wrote
> While reading into the crypt remote i realized a design issue in the approach taken in #1987.
> When a remote implements `io.Seeker`, like crypt does, `Open(&fs.RangeOption{...})` is useless, as the `io.Seeker` interface is the preferred method.

Yes you are right - I had forgotten about this...  

As far as I remember I settled on that design as an efficiency measure.  When implementing `fs.SeekOption` (and hence `RangeOption`) the crypt remote needs to read the nonce from the start of the file, so reopening the file is bad because it throws the nonce away and causes an extra `open, read nonce, close` for each seek.

I solved the problem by implementing Seek on the file handle which kept the nonce.

It would be possible to solve that problem in a different way, say by passing the old file handle as an `OldFIleHandle` option or an argument to `RangeOption`, or for the crypt backend to maintain a cache of nonces or to make a `Reopen` optional entry point.  This would then make RangeOption efficient again and we could remove the code which calls `Seek`.

The crypt remote is the only one to support `Seek` on the file handle returned from `Open` I think.

> So chunked reading for `backend -> crypt -> vfs` will be hard to implement, as a new interface like `RangeSeeker` would be needed throughout the whole project.
>
> From my current view into the project structure a better approach could be `backend -> chunked-reader -> crypt -> vfs`. The chunked-reader could implement `io.ReadCloser + io.Seeker + fs.RangeSeeker`, where `fs.RangeSeeker` will request  the underlying `Object` 
```go
type RangeSeeker interface {
  // RangeSeek behaves like a call to Seek(offset int64, whence int) with the
  // addition of only requesting length bytes from the underlying remote
  func RangeSeek(offset int64, whence int, length int64) (int64, error)
}
```
> A `Read` call beyond the requested length of `RangeSeek` will trigger a new `Open` following the normal chunk reading rules
>
> This way all operations could benefit from chunked-reading and operation which depend on small seeks can (like crypt and cache) can use `RangeSeek`.

That sounds like more work than fixing up RangeOption for crypt but would it give more benefit - what do you think?

**Comment by B4dM4n** [comment]
> That sounds like more work than fixing up RangeOption for crypt but would it give more benefit - what do you think?

That's pretty much what i worked on today :sweat_smile:
I wrote a general purpose `ChunkedReader` which takes a `Object` and returns a chunked, seek-able reader:
B4dM4n/rclone@8a230c79bf0b2554401d9acb044ab6ed8069e6d7
And a quick and dirty implementation in the crypt remote:
B4dM4n/rclone@ad1cff8a1daab83dc3ac68558801d8a3c2dc61bc

My idea is, that every remote which fetches files via HTTP returns an `ChunkedReader` from `Open`, so that all operations can benefit from it.

>If you'd like to have a go at any of these @B4dM4n then please let me know which so we don't duplicate effort.

I can look at the ftp and sftp remotes next and fix `RangeOption` support.

**Comment by ncw** [comment]
> I wrote a general purpose ChunkedReader which takes a Object and returns a chunked, seek-able reader:

A nice abstraction and ChunkReader looks neat in the crypt code :-)

About the RangeSeeker interface: I'm wondering whether `RangeSeek(offset int64, whence int, length int64) (int64, error)` might be better expressed as two methods `io.Seeker` and `SetChunkSize(length int64)`. This would have several advantages I think.

> My idea is, that every remote which fetches files via HTTP returns an ChunkedReader from Open, so that all operations can benefit from it.

At the moment it looks like NewChunkedReader wraps an existing object - I'm having a little trouble working out what Open would look like if it returned a NewChunkedReader - how would it reopen the streams?

My preference would be for Open to return an interface rather than a concrete type. So a  new interface which was `io.Reader`, `io.Seeker`, `io.Closer` and `SetChunkSize` which was implemented by ChunkedReader.

> I can look at the ftp and sftp remotes next and fix RangeOption support.

Great thanks!

I've fixed up box.  I was looking at supporting RangeOption for crypt which will touch much of the same code in your code above.  I think supporting RangeOption would be easier with the ChunkedReader in place.

A tricky bit is how exactly the chunk size would get propagated down when ChunkReader wraps crypt object which wraps chunk reader which wraps non-crypt object.  I suppose when the Crypt.Open is called with a RangeOption it resets the chunk size in its wrapped ChunkReader...

Do you want me to go ahead and implement RangeOption for crypt or shall we use some form of ChunkedReader to do it?

**Comment by ncw** [comment]
Note in a6833b68cafc322384f44b07e5a6c2857c66f362 I factored the code you wrote for the local into RangeOption and readers.LimitedReadCloser so I could implement RangeOption for cache in 88e0770f2d3542a1f5f4a759b2a267ce6aa43e3c. This will probably be useful for ftp and sftp!

**Comment by B4dM4n** [comment]
Your refactored code was very helpful.
Implementing `RangeOption` for crypt seems to be the fasted method of getting range support working for vfs.
The long term goal should be changing the returned interface from `Open`, to allow all `fs.operations` to use seeking and ranging.

> My preference would be for Open to return an interface rather than a concrete type. So a new interface which was io.Reader, io.Seeker, io.Closer and SetChunkSize which was implemented by ChunkedReader.

What should `SetChunkSize` accomplish in your opinion? Should it control the `chunkSize` or set the 'next chunk to Open' size of a `ChunkedReader`? In my opinion the second option would be the better approach. The general `chunkSize` should not be changed after creation of the `ChunkedReader`.

> At the moment it looks like NewChunkedReader wraps an existing object - I'm having a little trouble working out what Open would look like if it returned a NewChunkedReader - how would it reopen the streams?

How about this interface:
```go
type SizedOpener func(options ...OpenOption) (io.ReadCloser, int64, error)

func NewChunkedReader(o SizedOpener, initialChunkSize int64, chunkGrowth bool) *ChunkedReader {}
```
The `SizedOpener` returns the size of the object in addition to the `ReadCloser`. Both values are only information's the `ChunkedReader` needs.
This way remotes using http can look like this:
```go
func (o *Object) Open(options ...fs.OpenOption) (in io.ReadCloser, err error) {
  return fs.NewChunkedReader(o.open, o.fs.chunkSize, o.fs.chunkGrowth).Open(...options)
}
```

**Comment by ncw** [comment]
> Your refactored code was very helpful.

And thanks for your patches updating the remotes.

> Implementing RangeOption for crypt seems to be the fasted method of getting range support working for vfs.

Agreed.  The current abstraction is rather clunky...

> The long term goal should be changing the returned interface from Open, to allow all fs.operations to use seeking and ranging.

I think this is a worthy goal and it would be helpful.

It might be that we should start by returning the new interface from crypt only, then the places that care (the vfs layer and cache) can assert a wider interface, falling back to RangeOption etc.  Or maybe we should make a new optional interface for Fs (see below).

> What should SetChunkSize accomplish in your opinion? Should it control the chunkSize or set the 'next chunk to Open' size of a ChunkedReader? In my opinion the second option would be the better approach.  The general chunkSize should not be changed after creation of the ChunkedReader.

The point of setting the chunk size is to control the buffering and latency.  It isn't a precise thing... so I was thinking that `SetChunkSize` would set the `chunkSize` member in the `ChunkedReader` and next time `Open` needed to be called it would use that chunk size. If you haven't called `Read`  yet then that will affect the first chunk.

Is that what you were thinking?

> How about this interface:

```go
type SizedOpener func(options ...OpenOption) (io.ReadCloser, int64, error)
func NewChunkedReader(o SizedOpener, initialChunkSize int64, chunkGrowth bool) *ChunkedReader {}
```

That makes me think that `type SizedOpener` is just a cut down set of the `Object` interface, namely `Open` and `Size`, which makes me think what we should probably be doing is making a new optional interface `OpenChunked` on Fs (say).  For backends which care (like crypt) then can implement it themselves.  For all? the other backends, you can just wrap the normal object in a ChunkedReader.  We can write a utility function to check for the optional interface and use that, or return a ChunkedReader wrapped object.

**Comment by ncw** [comment]
Note that I updated the interface for `RangeOption.Decode` slightly in fe52502f19cfb9db24a6bf971487fa3fb8a1f9d8 so that it takes a limit = -1 to mean unlimited.  I did this to make it clearer that the limit is a special value and out of bounds, whereas 0 looks like it might be an OK limit.

**Comment by ncw** [comment]
@B4dM4n do you want me to take your `Chunked Reader` code and start whacking on it to make the crypt `RangeOption` work, or are you working on something?

**Comment by B4dM4n** [comment]
Sure, you can work on this. I'm busy enough with debugging the vfs changes.

**Comment by ncw** [comment]
I think this issue is done now.  There is outstanding work to make mount use RangeOption, but there is a PR open for that already.
