### ISSUE TITLE
Win64 : Mount broken since rclone-v1.38-096-g9fbff7bc-windows-amd64 version.

### ISSUE THREAD

**Issue by naeloob** [ncw/rclone#1827]
From rclone-v1.38-096-g9fbff7bc-windows-amd64 and high versions, mount command exits with error.

```
d:\Soft\rclone-v1.35-windows-amd64\rclone-v1.38-096-g9fbff7bc-windows-amd64>rclone.exe mount Bol: s: -vv
2017/11/15 18:14:53 DEBUG : Using config file from "C:\\Users\\Dell\\.rclone.conf"
2017/11/15 18:14:53 DEBUG : rclone: Version "v1.38-096-g9fbff7bc" starting with parameters ["rclone.exe" "mount" "Bol:" "s:" "-vv"]
2017/11/15 18:14:53 DEBUG : pacer: Rate limited, sleeping for 1.167960419s (1 consecutive low level retries)
2017/11/15 18:14:53 DEBUG : pacer: low level retry 1/10 (error googleapi: Error 403: Rate Limit Exceeded, rateLimitExceeded)
2017/11/15 18:14:53 DEBUG : pacer: Rate limited, sleeping for 2.21224271s (2 consecutive low level retries)
2017/11/15 18:14:53 DEBUG : pacer: low level retry 2/10 (error googleapi: Error 403: Rate Limit Exceeded, rateLimitExceeded)
2017/11/15 18:14:55 DEBUG : pacer: Resetting sleep to minimum 10ms on success
2017/11/15 18:14:55 INFO  : Google drive root '': Modify window is 1ms
2017/11/15 18:14:55 Fatal error: Can not open: s:: open s:: The system can not find the specified path.
```

The same command with rclone-v1.38-095-g413faa99-windows-amd64 , or lower, version can mount the remote.

Edit : I have a suspect : https://github.com/ncw/rclone/commit/9fbff7bcabb0b649751bb283a56a462f3cae707d

Edit 2 : Tried adding a final slash, a not existing path and an existing path... all failed.
```
d:\Soft\rclone-v1.35-windows-amd64\rclone-v1.38-096-g9fbff7bc-windows-amd64>rclone.exe mount Bol: s:\ -vv
2017/11/15 18:26:38 DEBUG : Using config file from "C:\\Users\\Dell\\.rclone.conf"
2017/11/15 18:26:38 DEBUG : rclone: Version "v1.38-096-g9fbff7bc" starting with parameters ["rclone.exe" "mount" "Bol:" "s:\\" "-vv"]
2017/11/15 18:26:38 INFO  : Google drive root '': Modify window is 1ms
2017/11/15 18:26:38 Fatal error: Can not open: s:\: open s:\: The system can not find the specified path.

d:\Soft\rclone-v1.35-windows-amd64\rclone-v1.38-096-g9fbff7bc-windows-amd64>rclone.exe mount Bol: d:\soft\rclone-v1.35-windows-amd64\TestMount
2017/11/15 18:27:09 Fatal error: Can not open: d:\soft\rclone-v1.35-windows-amd64\TestMount: open d:\soft\rclone-v1.35-windows-amd64\TestMount: The system can not find the specified path.

d:\Soft\rclone-v1.35-windows-amd64\rclone-v1.38-096-g9fbff7bc-windows-amd64>rclone.exe mount Bol: d:\soft\rclone-v1.35-windows-amd64\TestMount
Cannot create WinFsp-FUSE file system: mount point in use.
2017/11/15 18:27:28 ERROR : Google drive root '': Mount failed
2017/11/15 18:27:28 Fatal error: failed to mount FUSE fs: mount stopped before calling Init: mount failed
```
I created d:\soft\rclone-v1.35-windows-amd64\TestMount between the two last test.

**Comment by ishuah** [comment]
I've successfully reproduced this issue on Microsoft Windows Server 2016.
- rclone-v1.38-095-g413faa99-windows-amd64: successfully mounts
- rclone-v1.38-096-g9fbff7bc-windows-amd64: fails with
`Fatal error: Can not open: d:: open d:: The system can not find the specified path.`
Command: `rclone.exe mount box: d:`

**Comment by ishuah** [comment]
@naeloob try using the `--allow-non-empty` flag. This lets you skip `checkMountEmpty`.

Since you have to specify an unused (therefore non-existent) drive letter on Windows, [cmd/mountlib/mount.go line 30](https://github.com/ncw/rclone/blob/9fbff7bcabb0b649751bb283a56a462f3cae707d/cmd/mountlib/mount.go#L30) returns an error.

**Comment by naeloob** [comment]
@ishuah Thanks!!
With --allow-non-empty flag i can mount an unused drive letter and a non existant Path.

**Comment by ncw** [comment]
Excellent debugging @ishuah - so that points to 9fbff7bcabb0b649751bb283a56a462f3cae707d being the problem.

It looks like under windows [according to the mount code](https://github.com/ncw/rclone/blob/master/cmd/cmount/mount.go#L99-L107) the mount point must not exists before mounting, so we probably shouldn't be calling checkMountEmpty at all on that platform.

Fancy sending a fix?

So on Windows
  * the mount point must **not** exist

Everything else
  * the mount point must exist
  * the mount point must be empty unless --allow-non-empty is called

**Comment by ishuah** [comment]
I'd be happy to push a patch for this

**Comment by ishuah** [comment]
Please find a beta with the fix in: https://beta.rclone.org/v1.38-105-g31d2fb4e/ (uploaded in 15-30 mins)
