### ISSUE TITLE
add --cache-max-total-size option for the new cache remote

### ISSUE THREAD

**Issue by seuffert** [ncw/rclone#1830]
I think it would be very beneficial to have an option that specifies a max total cache size for a cache remote.

If the cached chunks exceed this limit, the chunk with the oldest "access time" has to be purged before a new chunk can be saved.

e.g. _rclone mount --allow-other --cache-max-total-size 10G test-cache: /var/tmp/test-cache_

**Comment by ncw** [comment]
Good idea!

**Comment by remusb** [comment]
Yes, I agree. I actually organised the schema in Bolt to support this. I think I even have the interface for this but I haven't implemented it yet.

**Comment by remusb** [comment]
I have a PR open #1884 that needs to go in and after that I'll make a push to a couple of cache changes that will include this as well.

Cleanup will be performed based on disk usage now, not expire after some time. I'll ping back here once a beta is ready.

**Comment by remusb** [comment]
Hi @seuffert 

Here's the latest beta: https://beta.rclone.org/v1.38-217-gb48b5373/

You can now configure a max cache size.
The doc was updated too: https://github.com/ncw/rclone/blob/master/docs/content/cache.md

**Comment by seuffert** [comment]
@remusb thx! will test it

**Comment by remusb** [comment]
Closing the issue. Feel free to open a bug if you find issues with the feature @seuffert
