### ISSUE TITLE
Cache - Path not found 

### ISSUE THREAD

**Issue by FoGBaV** [ncw/rclone#1834]
rclone v1.38-105-g31d2fb4e
- os/arch: windows/amd64
- go version: go1.9.1

Windows 10 64 Bit

Gdrive Storage (Business unlimited)

ok … after complete deleting the cache dir and start from scratch - after getting into subdir following error comes up :

2017/11/18 11:39:32 ERROR : IO error: file is too short to be encrypted
2017/11/18 11:39:32 ERROR : worker-1 : failed caching chunk in storage 0: open cache/gcache/fas9qo4eirl3pntkfjqqmi08hs/kp70u7dtkqn63dl5caa9ikirc4/3ct4j7ed9lbofra5m5em55ed527v8tlm3qr5pgc3j4sasp0sunog/dmgjhbr77l4lto6ebr8jm4qfvnq16j69v5106lqkl0e8nie9o19ti21e1m7pf8oaacmj7u0livk7ki6ue28mqefpcgahrk0cu2102992noerbd4hvcsb3ag4qtevk59d/ir2h35b4b3085tagvinv7d3q3nn1mcktheg7gcbh8spqo0nmh700/0: Das System kann den angegebenen Pfad nicht finden.

Could not find the path - is it possible, that the path is to long (in cache dir) for Windows 10 ? (so storage in file system is not the best way to go ?)

Mounted dir then gets out of order - big dir has only one file left (the one i tried to open).

Gdrive -> Cache -> Crypt

Without Cache - everything accessable … same structure - same storage …

**Comment by ncw** [comment]
I think this is likely the cache not working properly on Windows  - what do you think @remusb ?

**Comment by remusb** [comment]
@ncw https://github.com/ncw/rclone/issues/1836#issuecomment-345819162
Same deal I suspect. There seems to be multiple issues on OS's different than my main. I'll setup some VMs this week to try and replicate these issues on them.

**Comment by remusb** [comment]
@FoGBaV on a Linux OS this was a permission issue. Just want to rule this out, I know Windows isn't that strict about this but there are some special cases like the C:\ drive where special permissions are needed to write files.

**Comment by remusb** [comment]
@FoGBaV I'm sorry for the delay. There's a new beta that I would like you to try and see if you exhibit the same issue.

https://beta.rclone.org/v1.38-217-gb48b5373/
The doc was updated with new configuration: https://github.com/ncw/rclone/blob/master/docs/content/cache.md 

I never managed to replicate the scenario you presented here but I also had some issues in setting up a Windows runtime for this too so maybe I just didn't do that right either.

**Comment by remusb** [comment]
New beta: https://beta.rclone.org/v1.38-238-g6f1ae00c/
from https://github.com/ncw/rclone/issues/1904

I'm fairly certain (as in other cases) that the issue was related to the linked one. But I'm still keeping it open on account of being on Windows and never really having a proper chance to dig better in it. I would appreciate your help if you can confirm that you're still seeing it with the recent beta.

Thank you

**Comment by remusb** [comment]
https://beta.rclone.org/v1.38-242-g0d4bff82/

New beta. Also related to paths and location on Windows

**Comment by FoGBaV** [comment]
Hi remusb - sorry for not beeing back here for long time ... i was quite busy in my job. 

Will test in detail tomorrow ... short test gives me a empty drive - log says it's catching first file ... but nothing comes up ... i will post logs tomorrow - and i will test on other pcs ..

Many thanks for your great effort !

**Comment by remusb** [comment]
Can you make sure to start again from an empty cache using the recent betas? And the config has suffered a minor change too. Can you post that as well?

Those logs don't even show cache being used at all. None of them come from it sadly.

**Comment by FoGBaV** [comment]
Hi remusb - sorry for the delay ... Cache works now ... rclone.Config Error on my system ... ups ... 8)

Will test ... first files started ok ... (Official 1.39 Version)

**Comment by remusb** [comment]
Hi @FoGBaV 

Found a bug in Windows related to this and pushed it with one of the recent enhancements. Can you give it a try if you're still interested? https://beta.rclone.org/v1.39-099-gb3d8b7e2/

Thanks

**Comment by remusb** [comment]
Closing this as it's likely the same cause as here: https://github.com/ncw/rclone/issues/1935

@FoGBaV if you encounter the issue again please feel free to reopen it.
