### ISSUE TITLE
Cache segfault

### ISSUE THREAD

**Issue by jrarseneau** [ncw/rclone#1835]
Hi all

After building my cache last night and running overnight things seemed good. When I I mounted my rclone cache remote and remounted I receive a segfault. 

Things were working really well though. Ran some Plex scans and no bans. 

Setup is:
Remote > Cache Remote > Encrypted Remote as per documentation. 

For my unmount command i execute and fusermount command on the folder. Not sure if this caused the cache dB to get corrupted as that’s what the error seems to be pointing to. 

Environment:
```
rclone v1.38-117-g409ba56fβ
- os/arch: linux/amd64
- go version: go1.9.2
```

Mount command:
`rclone mount gdceMedia: -v --stats=10s --allow-other --allow-non-empty --cache-db-path=$HOME/.config/rclone ~/.media/gd-decrypted`

Error:
```
2017/11/18 07:18:16 INFO  : gdcMedia: Storage DB path: /home/jarsenea/.config/rclone/gdcMedia.db
2017/11/18 07:18:17 ERROR : /home/jarsenea/.config/rclone/gdcMedia.db: error opening storage cache: failed to open a cache connection to "/home/jarsenea/.config/rclone/gdcMedia.db": timeout
2017/11/18 07:18:17 INFO  : gdcMedia: Chunk Memory: true
2017/11/18 07:18:17 INFO  : gdcMedia: Chunk Size: 5M
2017/11/18 07:18:17 INFO  : gdcMedia: Workers: 4
2017/11/18 07:18:17 INFO  : gdcMedia: File Age: 6h0m0s
2017/11/18 07:18:17 INFO  : gdcMedia: Chunk Age: 3h0m0s
2017/11/18 07:18:17 INFO  : gdcMedia: Cache Writes: false
2017/11/18 07:18:17 INFO  : cache: running chunks cleanup
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x1c0 pc=0x7e4e11]

goroutine 14 [running]:
github.com/ncw/rclone/vendor/github.com/coreos/bbolt.(*DB).beginRWTx(0x0, 0x0, 0x0, 0x0)
        /home/travis/gopath/src/github.com/ncw/rclone/vendor/github.com/coreos/bbolt/db.go:542 +0x41
github.com/ncw/rclone/vendor/github.com/coreos/bbolt.(*DB).Begin(0x0, 0xc400000001, 0xc420546dc0, 0x1d, 0x8035af)
        /home/travis/gopath/src/github.com/ncw/rclone/vendor/github.com/coreos/bbolt/db.go:497 +0x38
github.com/ncw/rclone/vendor/github.com/coreos/bbolt.(*DB).Update(0x0, 0xc42138af40, 0x0, 0x0)
        /home/travis/gopath/src/github.com/ncw/rclone/vendor/github.com/coreos/bbolt/db.go:633 +0x46
github.com/ncw/rclone/cache.(*Persistent).CleanChunksByAge(0xc420186340, 0x9d29229e000)
        /home/travis/gopath/src/github.com/ncw/rclone/cache/storage_persistent.go:493 +0xaa
github.com/ncw/rclone/cache.(*Fs).CleanUpCache(0xc4201c2a00, 0x0)
        /home/travis/gopath/src/github.com/ncw/rclone/cache/cache.go:908 +0xe0
created by github.com/ncw/rclone/cache.NewFs
        /home/travis/gopath/src/github.com/ncw/rclone/cache/cache.go:338 +0x133d
```

**Comment by ncw** [comment]
What appears to have happened is db is nil in cache/storage_persistent.go:493, which means db is nil in the Persistent struct.

That is consistent with this error

    2017/11/18 07:18:17 ERROR : /home/jarsenea/.config/rclone/gdcMedia.db: error opening storage cache: failed to open a cache connection to "/home/jarsenea/.config/rclone/gdcMedia.db": timeout

I'm not sure what caused that though - are you running two rclones at once maybe?

In [newPersistent](https://github.com/ncw/rclone/blob/master/cache/storage_persistent.go#L67-L81) do you think it should be returning that error @remusb ?

**Comment by jrarseneau** [comment]
Definitely not running multiple rclone's at once..

It seems to be happening randomly that when I unmount and then try to remount, I get this error.

I run rclone in a screen session and I usually unmount two ways:

1. kill the screen session using the command `screen -S rclone -X quit` (where rclone is the name of their screen session)
2. Unmount the path where the cache remote is mounted `fusermount -us /path/to/mount` (which also closes the screen process since rclone gets terminated.

Not sure if any of these ways could cause the DB to get corrupted in this fashion.

**Comment by remusb** [comment]
This isn't an error related to multiple writers using the same file. That has a more obvious error message.

I need to double check how that kill affects Bolt's handle on its file db. Although on a Mac I had my fair share of panics and had to force the unmount, I never had any issue reopening the file.
I'm sure I have some Linux VM to try it out with the screen combination.

@ncw Are you trapping SIGKILL somewhere in `fs` where I could hook into it too?

**Comment by ncw** [comment]
> @ncw Are you trapping SIGKILL somewhere in fs where I could hook into it too?

Alas you can't trap SIGKILL.  I'm trapping SIGQUIT and SIGTERM in mountlib.  You can add a Notify in the cache code and it will be delivered too I think.

**Comment by remusb** [comment]
Thanks @ncw I added that handle too. It seems to work fine.

@jrarseneau Sadly I wasn't able to reproduce it but since you mentioned it's intermittent I assume it's going to depend on what's the usage during that time (streaming, scanning or something). Otherwise the same steps with `screen`.

At any rate, I added some extra cleanup code around how the db is closed. Tell me if there's any change with this build: https://beta.rclone.org/v1.38-174-g569c1a2e/

**Comment by jrarseneau** [comment]
Hi @remusb

I’ll try the new beta. Ive has this happen a half dozen times now. When I unmount, it won’t remount at least 50% of the time. Database is corrupted

I should add that I’m running the database on a btrfs volume. Could that have anything to do with things?

Thanks

**Comment by jrarseneau** [comment]
@remusb @ncw 

I'm sorry to report that the new beta does not fix anything. I was watching some shows on my Sandbox Plex server, playback stopped, I then unmounted the rclone cache mount with the command `screen -S rclone -X quit`, attempted to remount and it spat the same error.

Error is below. I'm not sure what else to do, but it has to be something with your code. I've been using PlexDrive for months which has used both mongodb and now bolt and have never seen this issue with that software. The unmount command is the same as well for both rclone / plexdrive.

What else can we / I try to do in order to troubleshoot this?

```
2017/11/22 20:32:26 DEBUG : Using config file from "/home/jarsenea/.rclone.conf"
2017/11/22 20:32:26 DEBUG : rclone: Version "v1.38-174-g569c1a2eβ" starting with parameters ["rclone" "mount" "gdceMedia:" "/home/jarsenea/.media/gd-decrypted" "-vv" "--allow-other" "--allow-non-empty" "--cache-db-path=/home/jarsenea/.config/rclone" "--log-file=/home/jarsenea/.rclone.cache.log"]
2017/11/22 20:32:27 DEBUG : gdcMedia: wrapped gd:Media at root 
2017/11/22 20:32:27 INFO  : gdcMedia: Storage DB path: /home/jarsenea/.config/rclone/gdcMedia.db
2017/11/22 20:32:28 ERROR : /home/jarsenea/.config/rclone/gdcMedia.db: error opening storage cache: failed to open a cache connection to "/home/jarsenea/.config/rclone/gdcMedia.db": timeout
2017/11/22 20:32:28 INFO  : gdcMedia: Chunk Memory: true
2017/11/22 20:32:28 INFO  : gdcMedia: Chunk Size: 5M
2017/11/22 20:32:28 INFO  : gdcMedia: Workers: 4
2017/11/22 20:32:28 INFO  : gdcMedia: File Age: 24h0m0s
2017/11/22 20:32:28 INFO  : gdcMedia: Chunk Age: 1h30m0s
2017/11/22 20:32:28 INFO  : gdcMedia: Cache Writes: false
2017/11/22 20:32:28 INFO  : cache: running chunks cleanup
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x1c0 pc=0x7e7b71]

goroutine 16 [running]:
github.com/ncw/rclone/vendor/github.com/coreos/bbolt.(*DB).beginRWTx(0x0, 0x0, 0x0, 0x0)
        /home/travis/gopath/src/github.com/ncw/rclone/vendor/github.com/coreos/bbolt/db.go:542 +0x41
github.com/ncw/rclone/vendor/github.com/coreos/bbolt.(*DB).Begin(0x0, 0xc400000001, 0xc420058100, 0x1d, 0x80654f)
        /home/travis/gopath/src/github.com/ncw/rclone/vendor/github.com/coreos/bbolt/db.go:497 +0x38
github.com/ncw/rclone/vendor/github.com/coreos/bbolt.(*DB).Update(0x0, 0xc420471f40, 0x0, 0x0)
        /home/travis/gopath/src/github.com/ncw/rclone/vendor/github.com/coreos/bbolt/db.go:633 +0x46
github.com/ncw/rclone/cache.(*Persistent).CleanChunksByAge(0xc420161640, 0x4e94914f000)
        /home/travis/gopath/src/github.com/ncw/rclone/cache/storage_persistent.go:493 +0xaa
github.com/ncw/rclone/cache.(*Fs).CleanUpCache(0xc4201d2a00, 0x0)
        /home/travis/gopath/src/github.com/ncw/rclone/cache/cache.go:927 +0xe0
created by github.com/ncw/rclone/cache.NewFs
        /home/travis/gopath/src/github.com/ncw/rclone/cache/cache.go:355 +0x142a
```

**Comment by jrarseneau** [comment]
@remusb @ncw 
I think I figured it out!

I can now reproduce this.. Let me try to explain.

1. Plex is running in a docker with a volume pointing to $HOME/mnt/media
2. $HOME/mnt/media is a unionFS mount comprised of $HOME/.media/gd (rclone Drive remote) and $HOME/.media/local (local files)
3. When I issue my unmount command, it unmounts the UnionFS and kills the rclone screen session that contains the mount, but **Plex is still running**
4. If I try to remount while Plex is running, I get the error from rclone that the DB timeout has occurred
5. If i stop the Plex docker and attempt to re-mount, it works!

I've successfully reproduced this. So what I'm thinking is that docker/plex/process has a bind on the file system and when attempting to re-mount, something happens which causes the error.

It should be noted that I can mount a non-cache remote just fine, but the cache remote exhibits this error.

Here's a quick video (1m22s) showing the bug and reproducing it.
https://youtu.be/phdgzO72d9A

**Comment by riopardo** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  monitoramento@wktecno.com
    Domain wktecnomedia.com has exceeded the max emails per hour (339/300 (112%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
------ The body of the message is 5668 characters long; only the first
------ 5000 or so are included here.
Received: from o1.sgmail.github.com ([192.254.114.176]:26568)
	by hcomm35.dns-wk.info with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89)
	(envelope-from <bounces+848413-9a47-wao=agencia.pw@sgmail.github.com>)
	id 1eHguY-0006v2-67
	for wao@agencia.pw; Thu, 23 Nov 2017 00:07:07 -0200
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=0XQf9IICfj1x8uluMYu9z3aas4I=; b=i2TZ7Qv0dvtT3wwg
	hMwRxE7pE63FiMks82ZvVI41fI+t+dHK062BN7eKtVsd1Ha5VIz//nb4AD69aJSk
	E19dwYHwKTA5S7YvnZWXhJEEBnrw0Jtd0MexJ7BGfrLZ4wgsnv9F8ew5cHHXj4hg
	+TPAJDbin9ZgzLRfW2HZTU16R4w=
Received: by filter0600p1iad2.sendgrid.net with SMTP id filter0600p1iad2-7052-5A162D2C-5
        2017-11-23 02:06:36.105123965 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0008p1iad2.sendgrid.net (SG) with ESMTP id CyKY-vfQQUS5WqN11DlBxw
	for <wao@agencia.pw>; Thu, 23 Nov 2017 02:06:35.946 +0000 (UTC)
Date: Thu, 23 Nov 2017 02:06:36 +0000 (UTC)

**Comment by remusb** [comment]
@jrarseneau 

I found an issue on bolt that could be related to this. I updated the bolt dependency to see if it improves things on this issue. It definitely is related to the timeout you're facing. The fact that I can't really replicate it makes things a bit slow but I hope you can help to fix the issue.

Here's a new build for it: can you try it? 
[rclone-v1.38-189-g021d6aab-cacheβ-linux-amd64.zip](https://github.com/ncw/rclone/files/1513000/rclone-v1.38-189-g021d6aab-cache.-linux-amd64.zip)

If that doesn't help: can you check if there's a process opened that's using the cache file just before opening rclone again?
`/home/jarsenea/.config/rclone/gdcMedia.db: error opening storage cache: failed to open a cache connection to "/home/jarsenea/.config/rclone/gdcMedia.db": timeout`

It seems fuser would be good for it if you can install it:
`fuser -v -m /home/jarsenea/.config/rclone/gdcMedia.db`

**Comment by ncw** [comment]
I've been attempting to set up an integration test server and I noticed that it failed in an identical way

https://pub.rclone.org/integration-tests/2017-11/2017-11-29-153504/test_all-v1.38-193-g1c6cad22.txt

I suspect that is because it is running 4 processes using the same cache at once.  Once of them succeeded, the other 3 failed with this traceback

```
2017/11/29 12:24:45 2017/11/29 12:24:45 ERROR : /home/rclone/.cache/rclone/cache-backend/TestCache.db: error opening storage cache: failed to open a cache connection to "/home/rclone/.cache/rclone/cache-backend/TestCache.db": timeout
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x1c0 pc=0x7ef0d1]

goroutine 9 [running]:
github.com/ncw/rclone/vendor/github.com/coreos/bbolt.(*DB).beginRWTx(0x0, 0x0, 0x0, 0x0)
	/home/rclone/go/src/github.com/ncw/rclone/vendor/github.com/coreos/bbolt/db.go:542 +0x41
github.com/ncw/rclone/vendor/github.com/coreos/bbolt.(*DB).Begin(0x0, 0xc400000001, 0xc420157340, 0xc42002bef0, 0x80bb0f)
	/home/rclone/go/src/github.com/ncw/rclone/vendor/github.com/coreos/bbolt/db.go:497 +0x38
github.com/ncw/rclone/vendor/github.com/coreos/bbolt.(*DB).Update(0x0, 0xc42003cf40, 0x0, 0x0)
	/home/rclone/go/src/github.com/ncw/rclone/vendor/github.com/coreos/bbolt/db.go:633 +0x46
github.com/ncw/rclone/cache.(*Persistent).CleanChunksByAge(0xc4201572c0, 0x9d29229e000)
	/home/rclone/go/src/github.com/ncw/rclone/cache/storage_persistent.go:493 +0xaa
github.com/ncw/rclone/cache.(*Fs).CleanUpCache(0xc420104a00, 0x0)
	/home/rclone/go/src/github.com/ncw/rclone/cache/cache.go:927 +0xe0
created by github.com/ncw/rclone/cache.NewFs
	/home/rclone/go/src/github.com/ncw/rclone/cache/cache.go:355 +0x142a

```

To fix the traceback this needs to return an error instead of just logging it and its callers need to check it.

```go
// newPersistent builds a new wrapper and connects to the bolt.DB file
func newPersistent(dbPath string, refreshDb bool) *Persistent {
	dataPath := strings.TrimSuffix(dbPath, filepath.Ext(dbPath))

	b := &Persistent{
		dbPath:   dbPath,
		dataPath: dataPath,
	}

	err := b.Connect(refreshDb)
	if err != nil {
		fs.Errorf(dbPath, "error opening storage cache: %v", err)
	}

	return b
}
```

**Comment by remusb** [comment]
@ncw That's not something I would have wanted to do. That method is called with a lock and it must always return an existing handle or create a new one. That might have been a bold assumption from my part so I refactored to treat errors in opening a handle and also changed the lock to a more drastic one since this will happen at bootstrap only.

So:
- multiple rclone processes mounted on the same remote will gently fail with a helpful error message
- multiple initializations of the same cache remote on the same rclone process will still work (crypt in particular does this)

The latest build should do this: https://beta.rclone.org/v1.38-195-g47450ba3/

**Comment by ncw** [comment]
@remusb sounds like a great solution.  The main thing from my POV is to change the traceback into a helpful error message!

**Comment by jrarseneau** [comment]
I’m looking at these comments but just want to re-iterate that I have never had multiple rclone mounts on the cache. 

The errror as I was able to reproduce it occurs if a process is using the file path that rclone attempts to mount to. So my Plex running in docker tries to use /mnt/media and is running, attempting to mount the cache remote will throw this error. 

Shutdown Plex and the remote will mount.

**Comment by remusb** [comment]
@jrarseneau yes, that's still in my mind. 
The latest build would at least help us to see if there's an orphan rclone process that keeps a handle open on the cache file through better logging. It's also better to properly catch traces and report back an intuitive error.
We'll take it from there if you can confirm you're getting that error log with that build.

I'm also curious on the previous build https://github.com/ncw/rclone/files/1513000/rclone-v1.38-189-g021d6aab-cache.-linux-amd64.zip which uses an upgraded storage dependency and according to their issue logs should fix some timeout related bugs.

**Comment by remusb** [comment]
@jrarseneau on this one, I still can't reproduce and I'm not sure how to further proceed. Since you're running cache now, were you successful with any of the betas I've given? Or you simply changed something? If yes, what? Can help to indicate what the issue might have been.

**Comment by remusb** [comment]
Can you also try with the new beta please? It's the same one as the other ticket.

https://beta.rclone.org/v1.38-217-gb48b5373/

**Comment by jrarseneau** [comment]
Same happens with this beta, but there's no trace back.

Again, this only happens if Plex is started (in a docker container) and is looking for files where the rclone cache mount typically would be. Once plex is stopped, I can mount no problem. So it's not corrupting the DB as I initially expected, it really seems to be something related to file locking or something.

```
2017/12/09 21:03:58 DEBUG : Using config file from "/home/jarsenea/.rclone.conf"
2017/12/09 21:03:58 DEBUG : rclone: Version "v1.38-217-gb48b5373β" starting with parameters ["rclone-beta" "mount" "gdceMedia:" "/home/jarsenea/.media/cache" "-vv" "--allow-other" "--cache-db-path=/home/jarsenea/.config/rclone" "--log-file=/home/jarsenea/.rclone.cache.log"]
2017/12/09 21:03:59 DEBUG : gdcMedia: wrapped gd:Media at root 
2017/12/09 21:03:59 INFO  : gdcMedia: Connected to Plex server: http://127.0.0.1:32400
2017/12/09 21:03:59 INFO  : gdcMedia: Storage DB path: /home/jarsenea/.config/rclone/gdcMedia.db
2017/12/09 21:04:00 ERROR : /home/jarsenea/.config/rclone/gdcMedia.db: Error opening storage cache. Is there another rclone running on the same remote? failed to open a cache connection to "/home/jarsenea/.config/rclone/gdcMedia.db": timeout
2017/12/09 21:04:00 DEBUG : gdcMedia: wrapped gd:Media at root 
2017/12/09 21:04:00 INFO  : gdcMedia: Connected to Plex server: http://127.0.0.1:32400
2017/12/09 21:04:00 INFO  : gdcMedia: Storage DB path: /home/jarsenea/.config/rclone/gdcMedia.db
2017/12/09 21:04:02 ERROR : /home/jarsenea/.config/rclone/gdcMedia.db: Error opening storage cache. Is there another rclone running on the same remote? failed to open a cache connection to "/home/jarsenea/.config/rclone/gdcMedia.db": timeout
2017/12/09 21:04:02 Failed to create file system for "gdceMedia:": failed to make remote "gdcMedia:" to wrap: failed to start cache db: failed to open a cache connection to "/home/jarsenea/.config/rclone/gdcMedia.db": timeout
```

**Comment by remusb** [comment]
Ok, that's now a relatively simple use case to try out. I'll try it out in the near future as I'm trying to fix a panic which seems to happen much more often.

**Comment by jrarseneau** [comment]
Is this the panic? Got it last night around 2am:

```
2017/12/10 02:18:44 DEBUG : worker-0 <objeqqgrflb1sua7n1lp4jjvgp0h0l3pf5arc7sokt9r6aj2looeenk3bu2srqvrsl48apruo1ds0>: downloaded chunk 10M
2017/12/10 02:18:44 DEBUG : worker-0 <objeqqgrflb1sua7n1lp4jjvgp0h0l3pf5arc7sokt9r6aj2looeenk3bu2srqvrsl48apruo1ds0>: downloaded chunk 10M
panic: runtime error: slice bounds out of range

goroutine 158344 [running]:
github.com/ncw/rclone/cache.(*Handle).getChunk(0xc422733420, 0xa00000, 0xc422733458, 0xc421131cc0, 0xc421131d58, 0x5d4c32, 0xc420dcc020)
        /home/travis/gopath/src/github.com/ncw/rclone/cache/handle.go:235 +0x524
github.com/ncw/rclone/cache.(*Handle).Read(0xc422733420, 0xc4253dc000, 0x10010, 0x10010, 0x0, 0x0, 0x0)
        /home/travis/gopath/src/github.com/ncw/rclone/cache/handle.go:257 +0xd4
io.ReadAtLeast(0x7f4c5b4f8178, 0xc422733420, 0xc4253dc000, 0x10010, 0x10010, 0x10010, 0xf3cc40, 0xc420768000, 0x7f4c5b4f8178)
        /home/travis/.gimme/versions/go1.9.2.linux.amd64/src/io/io.go:309 +0x86
io.ReadFull(0x7f4c5b4f8178, 0xc422733420, 0xc4253dc000, 0x10010, 0x10010, 0xc420020000, 0xc420768018, 0xc420252e60)
        /home/travis/.gimme/versions/go1.9.2.linux.amd64/src/io/io.go:327 +0x58
github.com/ncw/rclone/crypt.(*decrypter).fillBuffer(0xc420768000, 0xff02d0, 0xc420768000)
        /home/travis/gopath/src/github.com/ncw/rclone/crypt/cipher.go:770 +0xaa
github.com/ncw/rclone/crypt.(*decrypter).Read(0xc420768000, 0xc420ca3000, 0xaf000, 0xaf000, 0x0, 0x0, 0x0)
        /home/travis/gopath/src/github.com/ncw/rclone/crypt/cipher.go:810 +0x15c
github.com/ncw/rclone/fs.ReadFill(0x7f4c63579a88, 0xc420768000, 0xc420c52000, 0x100000, 0x100000, 0xe6ef20, 0xeecf80, 0xeb0f00)
        /home/travis/gopath/src/github.com/ncw/rclone/fs/operations.go:918 +0x72
github.com/ncw/rclone/fs.(*buffer).read(0xc42037ce10, 0x7f4c63579a88, 0xc420768000, 0x7f4c63579a88, 0xc420768000)
        /home/travis/gopath/src/github.com/ncw/rclone/fs/buffer.go:255 +0x58
github.com/ncw/rclone/fs.(*asyncReader).init.func1(0xc4210d07e0)
        /home/travis/gopath/src/github.com/ncw/rclone/fs/buffer.go:85 +0x1e4
created by github.com/ncw/rclone/fs.(*asyncReader).init
        /home/travis/gopath/src/github.com/ncw/rclone/fs/buffer.go:73 +0x1ab
```

**Comment by remusb** [comment]
Yes. It's tracked on #1896

**Comment by jrarseneau** [comment]
@remusb

Would it help if I setup a VPS you could access to see this issue occur?

**Comment by jrarseneau** [comment]
@remusb this no longer seems to occur with the recent betas, so I'm going to close this as I can no longer reproduce it.
