### ISSUE TITLE
Empty folders are not copied on remote destination

### ISSUE THREAD

**Issue by Very-Nice-App** [ncw/rclone#1837]
> What is your rclone version (eg output from `rclone -V`)
v1.38-117-g409ba56fβ

> Which OS you are using and how many bits (eg Windows 7, 64 bit)
MacOs 10.13

> Which cloud storage system are you using? (eg Google Drive)
OneDrive Personal

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone -vv sync Sviluppo/Android\ Studio\ Projects/AnimalidellaFattoria onedrive:'Backup/Progetti Android/AnimalidellaFattoria'

> A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
[log.txt](https://github.com/ncw/rclone/files/1485485/log.txt)

Using stable and beta version (as suggested as reply to my post on forum) gives same result: no empty folders are created on the remote server.

**Comment by ncw** [comment]
Here is a demo of the problem

```
$ mkdir src
$ mkdir dst
$ tree src
src

0 directories, 0 files
$ mkdir src/a
$ tree src
src
└── a

1 directory, 0 files
$ rclone copy -vv src dst
2017/11/19 20:53:25 DEBUG : Using config file from "/home/ncw/.rclone.conf"
2017/11/19 20:53:25 DEBUG : rclone: Version "v1.38-148-g07e2e410-vfs-rw" starting with parameters ["rclone" "copy" "-vv" "src" "dst"]
2017/11/19 20:53:25 INFO  : Local file system at /tmp/dst: Modify window is 1ns
2017/11/19 20:53:25 INFO  : Local file system at /tmp/dst: Waiting for checks to finish
2017/11/19 20:53:25 INFO  : Local file system at /tmp/dst: Waiting for transfers to finish
2017/11/19 20:53:25 INFO  : 
Transferred:      0 Bytes (0 Bytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:          0s

2017/11/19 20:53:25 DEBUG : Go routines at exit 3
2017/11/19 20:53:25 DEBUG : rclone: Version "v1.38-148-g07e2e410-vfs-rw" finishing with parameters ["rclone" "copy" "-vv" "src" "dst"]
$ tree dst/
dst/

0 directories, 0 files
```

**Comment by ipod825** [comment]
Marked. I am writing a [vim-plugin](https://github.com/ipod825/vim-netranger) that requires this bug be fixed.

**Comment by aldones** [comment]
In light of #74cbdea, this ticket needs reopening.

**Comment by ipod825** [comment]
The `copyto`  command still fails:
```bash
$ rclone --version
rclone v1.42
- os/arch: linux/amd64
- go version: go1.10.1

$ mkdir -p src/a
$ mkdir dst
$ rclone copyto src/a dst/a
$ ls dst
$
```

**Comment by ncw** [comment]
@ipod825 thanks for the note.

@ishuah actually this seems to all about the root directory because if you replace `rclone copyto src/a dst/a` with `rclone copy src/a dst` it doesn't create dst in the same way.

**Comment by ishuah** [comment]
@ncw @ipod825 Looking into it

**Comment by ishuah** [comment]
@ncw `rclone copy src/a dst` doesn't create the empty directory on dst. I'm on `rclone v1.42-DEV`.
I'll start by writing tests for copy and copyto then work on fixing this.

**Comment by ncw** [comment]
Thanks again @ishuah  :-)

**Comment by danoe** [comment]
Can we have an option to decide if we want empty folders on the destination? I have many empty folders that i don't want to copy to the destination. For now i'll stick to 1.41.

**Comment by Hairo** [comment]
> Can we have an option to decide if we want empty folders on the destination? I have many empty folders that i don't want to copy to the destination. For now i'll stick to 1.41.

+1

**Comment by ishuah** [comment]
@ncw you're right, it's all about the root dir. 
Running `copy` and `copyto` with an additional empty dir nested demonstrates this behavior.
```
$ mkdir -p src/a/b
$ tree src
src
└── a
    └── b

2 directories, 0 files
$ mkdir dst
$ tree dst
dst

0 directories, 0 files
$ rclone copyto src/a dst/a
$ tree dst
dst
└── a
    └── b

2 directories, 0 files
$ rm -r dst && mkdir dst
$ tree dst
dst

0 directories, 0 files
$ rclone copy src/a dst
$ tree dst
dst
└── b

1 directory, 0 files
```
I like @danoe's suggestion. I think we should include a flag (`--copy-empty-src-dirs`) to include empty dirs in copy, same way we have `--delete-empty-src-dirs` on move

**Comment by aldones** [comment]
I would like to suggest copying empty src dirs to be the default behavior and, so, if it is decided to implement the option not to, but that to be triggered by a flag such as --dont-copy-empty-src-dirs.
The usual expectation for a copy is to be identical, so copying empty directories should be default.

**Comment by ncw** [comment]
@Hairo has made an issue about this at #2404

**Comment by ipod825** [comment]
Should this issue be open again? Is there any plan on when this will be settled?

**Comment by ncw** [comment]
@ipod825 I think this issue is fixed.  Note that some remotes (s3, b2, gcs - the bucket based ones) can't have empty directories anyway.

If you think there is still a problem, can you make a demo and open a new issue please - thanks

**Comment by ipod825** [comment]
Just as the example I've already mentioned.
The `copyto`  command still fails (Is there a flag to make it behavior differently? I search for `empty` in `copyto` document but found nothing):
```bash
$ rclone --version
rclone v1.43
- os/arch: linux/amd64
- go version: go1.11

$ mkdir -p src/a
$ mkdir dst
$ rclone copyto src/a dst/a
$ ls dst
$
```

**Comment by ncw** [comment]
@ipod825 can you make the above into a new issue please? It is a subtly different problem I think! Thanks

**Comment by ncw** [comment]
> Does this also apply to the rclone sync command? We are noticing that rclone sync to an AWS S3 does not create empty directories in S3.

S3 doesn't have a concept of directory, so rclone can't store empty directories there.  Some apps like cyberduck create a 0 sized object to mark directories - rclone doesn't do that though.

**Comment by ankur0493** [comment]
@ncw Is there a specific reason why we don't want to create empty sized objects to mark directories through RClone? Even empty directories created through GCP web UI do that

**Comment by ncw** [comment]
> Is there a specific reason why we don't want to create empty sized objects to mark directories through RClone? Even empty directories created through GCP web UI do that.

It uses more API calls to do it and they aren't necessary except in the specific case of empty directories...

Rclone could do it I suppose...

**Comment by archon810** [comment]
I'm using 1.47 and rclone doesn't copy empty dirs to Box. Is this a bug?

**Comment by ncw** [comment]
> I'm using 1.47 and rclone doesn't copy empty dirs to Box. Is this a bug?

    rclone copy --create-empty-src-dirs

is what you want

**Comment by ankur0493** [comment]
@ncw Just to confirm, rclone still doesn't support copying empty folders to bucket based destinations, right?

**Comment by ncw** [comment]
> @ncw Just to confirm, rclone still doesn't support copying empty folders to bucket based destinations, right?

Correct.  Bucket based locations can't have empty folders in rclone.

**Comment by adrianmihalko** [comment]
Can't we just in case of empty folder make a dummy hidden file? .emptyfolder or something like that.
