### ISSUE TITLE
Rclone with GFS works, but crypt on top does not.

### ISSUE THREAD

**Issue by justusiv** [ncw/rclone#1841]
SOLVED
User error

What is your rclone version (eg output from `rclone -V`)
1.38 
Which OS you are using and how many bits (eg Windows 7, 64 bit)
Win10x64 1709
Which cloud storage system are you using? (eg Google Drive)
Local Drive and Google Drive using Google File Stream

For the hell of it i tested out a local drive on the GFS. It appears to work just fine. Using a command like (rclone lsd "localdrive:g:My Drive\enc") However when using the "crypt" on top of this it just produces errors. 

I tried two differnt formats in the config. 

```
type = crypt
remote = "G:\My Drive\enc"
```

and

```
type = crypt
remote = "localdrive:g:My Drive\enc"
```

```
2017/11/17 17:00:44 NOTICE: Local file system at : Replacing invalid characters in "\\Users\\userABC\\\"g:\\My Drive\\enc\"" to "\\\\?\\C:\\Users\\userABC\\_g_\\My Drive\\enc_"
2017/11/17 17:00:44 NOTICE: Local file system at : Replacing invalid characters in "\\Users\\userABC\\\"g:\\My Drive\\enc\"" to "\\\\?\\C:\\Users\\userABC\\_g_\\My Drive\\enc_"
2017/11/17 17:00:44 ERROR : : error listing: directory not found
```

**Comment by ncw** [comment]
Oh, I see the problem.  You have quotes `"` around your remote names.

Try removing those and they both should work.

PS I thought I posted this earlier but it seems to have disappeared - maybe I forgot to press the button!  Thank heavens for [lazarus](https://chrome.google.com/webstore/detail/lazarus-form-recovery/loljledaigphbcpfhfmgopdkppkifgno?hl=en)!

**Comment by justusiv** [comment]
Ok i feel like a bonehead but i still cant get this to work.

```
[localgdrive]
type = local
nounc = true
```
```
PS C:\Users\userabc> rclone lsd localgdrive:g:
          -1 2017-11-18 21:18:39        -1 $RECYCLE.BIN
          -1 2017-11-18 21:18:39        -1 My Drive
```
```
[enclocalgdrive]
type = crypt
remote = localgdrive:g:My Drive\enc
filename_encryption = standard
password = REMOVED
password2 = REMOVED
```
```
PS C:\Users\userabc> rclone lsd enclocalgdrive:
PS C:\Users\userabc>
```

This is what i think it should be minus the quotes.

**Comment by ncw** [comment]
No worries - glad you got it to work.
