### ISSUE TITLE
rclone for google drive only

### ISSUE THREAD

**Issue by him4nsh** [ncw/rclone#1843]
can rclone be compiled for google drive only as the size of rclone is very large for different cloud storage.

**Comment by ncw** [comment]
Sure..

Just comment out the providers you don't need in [fs/all/all.go](https://github.com/ncw/rclone/blob/master/fs/all/all.go)  you can do the same things [to commands](https://github.com/ncw/rclone/blob/master/cmd/all/all.go)

I'll just note that although the binary is bit, a modern OS only loads the bits it needs into memory.
