### ISSUE TITLE
Problem with SFTP pub key authentication with password

### ISSUE THREAD

**Issue by carloshmm** [ncw/rclone#1847]
I already wrote about it here: https://github.com/ncw/rclone/issues/1494#issuecomment-345556996
But I think it needs an proper report here.

> Hey, I think this is related:
> How to deal with encrypted PEM SSH private keys? I mean, besides my key, I need to enter a password to decrypt it in order to access the server. There are currently three options on rclone:
> Password authentication: Discarded for me because my server doesn't allow password authentication, only pub key auth.
> Agent Authentication: It is not working on my system (Linux) even with a properly configured ssh-agent process running, ex: I already logged on my server typing my password and it gets stored during all the session, but rclone can't detect the ssh-agent, printing this message:
> ```
> Failed to create file system for "remote:path": couldn't connect to ssh-agent: Error connecting to SSH_AUTH_SOCK: dial unix /ssh-agent.socket: connect: no such file or directory
> ```
> I think that the rclone environment variable "SSH_AUTH_SOCK" is pointing to the wrong place, since the process ssh-agent on my system is storing the file 'ssh-agent.socket' on:
> ```
> /usr/bin/ssh-agent -a /run/user/1000/ssh-agent.socket
> ```
> Private Key authentication: Doesn't work since it needs the password for decrypt my private key. This message is appearing:
> ```
> Failed to create file system for "remote:path:": failed to parse private key file: ssh: cannot decode encrypted private keys
> ```

**Comment by ncw** [comment]
> How to deal with encrypted PEM SSH private keys?

The proper way of doing this is with an ssh-agent IHMO so let's concentrate on getting that to work.

> I think that the rclone environment variable "SSH_AUTH_SOCK" is pointing to the wrong place, since the process ssh-agent on my system is storing the file 'ssh-agent.socket' on:

It is up to you to set the `SSH_AUTH_SOCK` variable for rclone.

Which OS are you using?

**Comment by carloshmm** [comment]
I'm using Arch Linux, I'm using this script to mount the remote:
```
#!/bin/bash

/usr/bin/install -d -m 2770 -g shared /home/shared/remote >/dev/null 2>&1 &
sudo su - carloshmm -c "/usr/bin/rclone mount 'remote:/home/shared/Files' /home/shared/remote --read-only --dir-cache-time=30s --allow-other" >/dev/null 2>&1 &
```
I've modified this script to follow these instructions: https://github.com/ncw/rclone/issues/1218

```
#!/bin/bash

env | grep ssh

eval "$(ssh-agent -s)"

ssh-add ~/.ssh/privKey

env | grep ssh

/usr/bin/install -d -m 2770 -g shared /home/shared/remote >/dev/null 2>&1 &
sudo su - carloshmm -c "/usr/bin/rclone mount 'remote:/home/shared/Files' /home/shared/remote --read-only --dir-cache-time=30s --allow-other" >/dev/null 2>&1 &

eval "$(ssh-agent -k)"
```
Output:
```
SSH_AUTH_SOCK=/run/user/1000/ssh-agent.socket
Agent pid 3647
Enter passphrase for /home/carloshmm/.ssh/privKey: 
Identity added: /home/carloshmm/.ssh/privKey (/home/carloshmm/.ssh/privKey)
SSH_AUTH_SOCK=/tmp/ssh-aXEC3h2FTJBk/agent.3646
2017/11/21 12:38:08 Failed to create file system for "remote:/home/shared/Files": couldn't connect to ssh-agent: Error connecting to SSH_AUTH_SOCK: dial unix /ssh-agent.socket: connect: no such file or directory
Agent pid 3647 killed
```

**Comment by ncw** [comment]
My guess is that the sudo is the problem.  You'll need to use the `-E` flag to pass on the environment.

```
$ env | grep SSH
SSH_AUTH_SOCK=/tmp/ssh-tWZPR9pGRCR4/agent.4548
SSH_AGENT_PID=4692
$ sudo sh -c 'env | grep SSH'
SUDO_COMMAND=/bin/sh -c env | grep SSH
$ sudo -E sh -c 'env | grep SSH'
SSH_AGENT_PID=4692
SSH_AUTH_SOCK=/tmp/ssh-tWZPR9pGRCR4/agent.4548
SUDO_COMMAND=/bin/sh -c env | grep SSH
$ 
```

You shouldn't need to run `rclone mount` as root though - if the allow-other is causing you a problem then put this in `/etc/fuse.conf`

```
# Allow non-root users to specify the allow_other or allow_root mount options.
user_allow_other
```

**Comment by carloshmm** [comment]
You are right, it worked when I started running this command without sudo.
