### ISSUE TITLE
source directories are being deleted 

### ISSUE THREAD

**Issue by calisro** [ncw/rclone#1849]
Source directories are being deleted when empty even if they were not part of the include-from list.  I do not believe this should happen and ESPECIALLY not the base directory itself.  

#1642

HS -> mkdir cams

HS -> mkdir cams/test

HS -> touch cams/test/file

HS -> echo test/file > inc

HS -> mkdir /home/robert/cams2

HS -> rclone  --files-from /home/robert/inc  move /home/robert/cams /home/robert/cams2  -vv
2017/11/21 16:33:32 DEBUG : Using config file from "/home/robert/.rclone.conf"
2017/11/21 16:33:32 DEBUG : rclone: Version "v1.38-166-gcb6de4a2β" starting with parameters ["rclone" "--files-from" "/home/robert/inc" "move" "/home/robert/cams" "/home/robert/cams2" "-vv"]
2017/11/21 16:33:32 INFO  : Local file system at /home/robert/cams2: Modify window is 1ns
2017/11/21 16:33:32 DEBUG : test/file: Sizes differ (src 0 vs dst 2)
2017/11/21 16:33:32 INFO  : test/file: Deleted
2017/11/21 16:33:32 INFO  : Local file system at /home/robert/cams2: Waiting for checks to finish
2017/11/21 16:33:32 INFO  : test/file: Moved (server side)
2017/11/21 16:33:32 INFO  : Local file system at /home/robert/cams2: Waiting for transfers to finish
2017/11/21 16:33:32 DEBUG : test: Removing directory
2017/11/21 16:33:32 DEBUG : Local file system at /home/robert/cams: deleted 1 directories
2017/11/21 16:33:32 DEBUG : Local file system at /home/robert/cams: Removing directory
2017/11/21 16:33:32 INFO  : 
Transferred:      0 Bytes (0 Bytes/s)
Errors:                 0
Checks:                 2
Transferred:            1
Elapsed time:          0s

2017/11/21 16:33:32 DEBUG : Go routines at exit 3
2017/11/21 16:33:32 DEBUG : rclone: Version "v1.38-166-gcb6de4a2β" finishing with parameters ["rclone" "--files-from" "/home/robert/inc" "move" "/home/robert/cams" "/home/robert/cams2" "-vv"]
✓ robert [~] $
HS -> ls cams
ls: cannot access cams: No such file or directory

**Comment by ncw** [comment]
This must be a consequence of c65734ee694086b70f05994360db78b69c2ebf93

@ishuah have you got time to take a look?

**Comment by ishuah** [comment]
@ncw I'm on it

**Comment by ishuah** [comment]
I've made a PR (#1852) to address this.
The root source directory won't get deleted after move. Only empty directories included in the move will get deleted.

Would a flag (`--delete-root-src` or something) be useful for use cases where the root source needs to be deleted after move? Or am I just overthinking things? :)

**Comment by riopardo** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  monitoramento@wktecno.com
    Domain wktecnomedia.com has exceeded the max emails per hour (360/300 (120%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o5.sgmail.github.com ([192.254.113.10]:60819)
	by hcomm35.dns-wk.info with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89)
	(envelope-from <bounces+848413-9a47-wao=agencia.pw@sgmail.github.com>)
	id 1eHkJU-00087D-0a
	for wao@agencia.pw; Thu, 23 Nov 2017 03:44:45 -0200
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=3rmt9Lt3IVzWa1gsf+2KfgptvVk=; b=XkqBazimwKrfGhRJ
	QoPgmTSbT/rLVN9KdXDVweCrUhXz7qVAmJ1GFMrhAjI1cbkhBEF3pLaWSvlCFNIY
	JjQrYTTx2b+SMyFsV72J7xmP2oLe36mAQMfz00Lw1VYLTfOnK5rP4TPGenh5kz8o
	z9FMPlTvnKfdRb9bGfjbsLXsHo4=
Received: by filter0502p1iad2.sendgrid.net with SMTP id filter0502p1iad2-1372-5A166046-2
        2017-11-23 05:44:38.185733944 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0013p1iad2.sendgrid.net (SG) with ESMTP id rXNkmTW3RO-auVbGJJp0dw
	for <wao@agencia.pw>; Thu, 23 Nov 2017 05:44:38.273 +0000 (UTC)
Date: Thu, 23 Nov 2017 05:44:38 +0000 (UTC)

**Comment by ncw** [comment]
> Would a flag (--delete-root-src or something) be useful for use cases where the root source needs to be deleted after move? Or am I just overthinking things? :)

I think people can just use rmdir if they want that!

**Comment by ishuah** [comment]
Please find a beta with fix in: https://beta.rclone.org/v1.38-181-g6c62fced/ (Uploaded in 15-30 minutes)

**Comment by riopardo** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  monitoramento@wktecno.com
    Domain wktecnomedia.com has exceeded the max emails per hour (362/300 (120%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o3.sgmail.github.com ([192.254.112.98]:9255)
	by hcomm35.dns-wk.info with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89)
	(envelope-from <bounces+848413-9a47-wao=agencia.pw@sgmail.github.com>)
	id 1eHnoE-0008JN-J3
	for wao@agencia.pw; Thu, 23 Nov 2017 07:28:46 -0200
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=2Ci5QymubkD0XvAks+kZ31yVwTY=; b=FFXNMG38+NVxYJT9
	tO1AJYC0FShblyKO95WylU6FxI5Mc+UQJlb0eY3nvDA7ZXBOJ2fxmYs1ERHd2u4Z
	uD7B7z79W7+PwXBYE935PLU4DwtbY7JUwwlOnwyVaQyI+mFyR3Afw+rSNNQpEznC
	yOSfWhf6RxYh9K9Ub7YaoDRIJRo=
Received: by filter0179p1las1.sendgrid.net with SMTP id filter0179p1las1-29094-5A1694C3-5
        2017-11-23 09:28:35.784418828 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0004p1iad1.sendgrid.net (SG) with ESMTP id ufPE_1qeTge3gmgCVlj4pQ
	for <wao@agencia.pw>; Thu, 23 Nov 2017 09:28:35.644 +0000 (UTC)
Date: Thu, 23 Nov 2017 09:28:36 +0000 (UTC)

**Comment by syaifulnizamyahya** [comment]
I have test the beta with fix and I must say that while it doesnt delete root folder, it still delete all other folders(below root). I would like to have the old features/bug either by default or by options. I would like to manually delete the empty folder that I want, not auto by rclone.

**Comment by ajkis** [comment]
> I would like to manually delete the empty folder that I want, not auto by rclone.

Its in works : https://github.com/ncw/rclone/issues/1854#issuecomment-346662187
