### ISSUE TITLE
Fix AWS Release v0.10.0 introduced a breaking change to the SDK.

### ISSUE THREAD

**Issue by klauspost** [ncw/rclone#185]
I will take a look at it:

https://github.com/aws/aws-sdk-go#aws-sdk-for-go

**Comment by ncw** [comment]
Thanks Klaus

**Comment by ddragosd** [comment]
:+1: Terraform fixed it using hashicorp/terraform@cadbbba

**Comment by ncw** [comment]
Fixed with PR #187 - Thanks Klaus
