### ISSUE TITLE
WriteFileHandle: ReadAt: Can't read and write to file without cache (rclone mount+gocryptfs)

### ISSUE THREAD

**Issue by Nodens-** [ncw/rclone#1853]
> What is your rclone version (eg output from `rclone -V`)
rclone v1.38-DEV
- os/arch: linux/amd64
- go version: go1.9.1

built from git.

> Which OS you are using and how many bits (eg Windows 7, 64 bit)
Fedora 27 x64

> Which cloud storage system are you using? (eg Google Drive)
Google Drive

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone mount -vv --allow-other --default-permissions --write-back-cache gd: /Drive/.remote &
> A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

I have an existing gocryptfs encrypted directory tree on gdrive and current scheme is gocrypt->google-drive-ocamlfuse. I am trying to replace google-drive-ocamlfuse with rclone mount and this is the error I get when I try to copy files to the mount. 
I am attaching the -vv log 
[log.txt](https://github.com/ncw/rclone/files/1498574/log.txt)

**Comment by ncw** [comment]
The problem is that without cache, rclone can't open files read and write - that is just the way cloud storage systems work

So the `Open: flags=O_RDWR|O_CREATE|O_EXCL` means that the file was opened for Read/Write.  Without cache rclone will open the file for write in this case and give an error if it was read from.

To fix use `--cache-mode minimal` or any of the higher cache modes.

This cache code is relatively new so take care while testing.  I'm very interested to hear how you get on.

**Comment by riopardo** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  monitoramento@wktecno.com
    Domain wktecnomedia.com has exceeded the max emails per hour (354/300 (118%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o5.sgmail.github.com ([192.254.113.10]:25151)
	by hcomm35.dns-wk.info with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89)
	(envelope-from <bounces+848413-9a47-wao=agencia.pw@sgmail.github.com>)
	id 1eHof6-0003BA-7Y
	for wao@agencia.pw; Thu, 23 Nov 2017 08:23:21 -0200
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=qd/u9Nfney/9tZaKcBro/IxxjCo=; b=DwqR/v9YkA+Zs2LZ
	g/IgK+897nkmexI4CEW4edv0+L/cXhbQHpsIAqcuN/l5O8GhWVIDsOA37MMtWJ3a
	6LZRMYwHTeMbwbGXhXM5YKC9r7qP5pwm5byRNLFzgd6jfZZKpfEh1rU0Q/hTRhGZ
	chhLmGAtv7HoNOR1c0grNBWM3b8=
Received: by filter1256p1mdw1.sendgrid.net with SMTP id filter1256p1mdw1-4010-5A16A191-12
        2017-11-23 10:23:13.543861608 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0005p1iad1.sendgrid.net (SG) with ESMTP id AOTno-x7ThynH7PpDUdo9g
	for <wao@agencia.pw>; Thu, 23 Nov 2017 10:23:13.515 +0000 (UTC)
Date: Thu, 23 Nov 2017 10:23:13 +0000 (UTC)

**Comment by Nodens-** [comment]
I think I will go with --cache-mode writes and test in a minute.
What is the default value of --low-level-retries ?
I am assuming that --cache-max-age also clears any leftovers in cache from failed uploads, correct?

**Comment by Nodens-** [comment]
It works great so far. In fact the whole process of uploading is 1000% faster than google-drive-ocamlfuse. And non-blocking due to to proper cache implementation. I copied a few files back and forth and checked sha1 hashes. Seems to be working amazingly well!

I will keep running with -vv for a while while copying files so I can monitor for any issues. Then I will try and put a heavy load on it and test some more before I switch permanently.
Still I woulld like to know the default value of --low-level-retries and if -1 is a possible value for infinite retry before I close this:)

**Comment by Nodens-** [comment]
I found the default value for --low-level retries, it is listed in --help heh. It doesn't say if it akes -1 though so I'm assuming no.

I tried a rclone cachestats gd: to check if I it would show status of cache and got:

 panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x81a08e]

goroutine 1 [running]:
github.com/ncw/rclone/cmd/cachestats.glob..func1.1(0xc420351260, 0x3)
        /home/user/go/src/github.com/ncw/rclone/cmd/cachestats/cachestats.go:45 +0x1be
github.com/ncw/rclone/cmd.Run(0xc420180101, 0x15d9740, 0xc420125d08)
        /home/user/go/src/github.com/ncw/rclone/cmd/cmd.go:265 +0xa7
github.com/ncw/rclone/cmd/cachestats.glob..func1(0x15d9740, 0xc420181ab0, 0x1, 0x1)
        /home/user/go/src/github.com/ncw/rclone/cmd/cachestats/cachestats.go:41 +0x1aa
github.com/ncw/rclone/vendor/github.com/spf13/cobra.(*Command).execute(0x15d9740, 0xc420181a60, 0x1, 0x1, 0x15d9740, 0xc420181a60)
        /home/user/go/src/github.com/ncw/rclone/vendor/github.com/spf13/cobra/command.go:654 +0x2a2
github.com/ncw/rclone/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x15d92c0, 0xc420257f70, 0x4060b4, 0xc42007a058)
        /home/user/go/src/github.com/ncw/rclone/vendor/github.com/spf13/cobra/command.go:729 +0x2fe
github.com/ncw/rclone/vendor/github.com/spf13/cobra.(*Command).Execute(0x15d92c0, 0xc4202d6140, 0x20)
        /home/user/go/src/github.com/ncw/rclone/vendor/github.com/spf13/cobra/command.go:688 +0x2b
main.main()
        /home/user/go/src/github.com/ncw/rclone/rclone.go:15 +0x31

**Comment by ncw** [comment]
> It works great so far. In fact the whole process of uploading is 1000% faster than google-drive-ocamlfuse. And non-blocking due to to proper cache implementation. I copied a few files back and forth and checked sha1 hashes. Seems to be working amazingly well!

Great!  One thing to watch out for - it is a writeback cache so you need to make sure everything is uploaded before stopping the mount. There isn't a good way of doing that at the moment which I will fix soon.

> I found the default value for --low-level retries, it is listed in --help heh. It doesn't say if it akes -1 though so I'm assuming no.

If you want to turn it off then set it to 1 confusingly.  It is the total number of tries. I recommend not though as cloud storage systems can be unreliable at the best of times!

>  tried a rclone cachestats gd: to check if I it would show status of cache and got:

confusingly, and temporarily most likely, rclone has two caching systems, one for mount and a cache backend.  That command is for the cache backend - I've put this in a new issue #1855

**Comment by Nodens-** [comment]
> Great! One thing to watch out for - it is a writeback cache so you need to make sure everything is uploaded before stopping the mount. There isn't a good way of doing that at the moment which I will fix soon.

This is exactly why I tried the cachestats command. Trying to see if some kind of cache status is implemented as currently I see now way to see if the upload is finished except perhaps watching -vv output?

> If you want to turn it off then set it to 1 confusingly. It is the total number of tries. I recommend not though as cloud storage systems can be unreliable at the best of times!

I want to do the exact opposite, this is why I asked if it takes -1. I want it to keep trying ad infinitum. :) What is the max value?

**Comment by Nodens-** [comment]
Closing this. Although should probably make a new issue requesting a cache/progress status display enhancement for mount.

**Comment by ncw** [comment]
I'll just note that if you use `-v --stats 1m` then you will see stats printed every minute which will include files being transferred.  Not a perfect solution, but better than nothing!

**Comment by Nodens-** [comment]
I will start using this for monitoring. Although ideally a parameter that outputs if there's any transfer going on/files queued in cache that could be parsed in a script to check before unmounting or rebooting the server would be ideal!

**Comment by ncw** [comment]
@Nodens- I've put your suggestion in #1909 - thanks
