### ISSUE TITLE
Bug: add a --delete-empty-dirs flag on the move command instead of deleting empty dirs automatically

### ISSUE THREAD

**Issue by ajkis** [ncw/rclone#1854]
Latest rclone  v1.38-181 include removal of empty folders once rclone move is finished, however that is causing problems if other apps expect those paths.

I use the following setup:
Sonarr is pointing to /storage/local/series
Radarr is pointing to /storage/local/movies 
Rclone is moving from /storage/local remote: 

Once rclone is finished it will delete all empty folder so in this case /storage/local 

With previous version, I used script that would remove empty folders under ./local/movies & series.

It would be great if new flag was added that would skip removal of empty folders.

**Comment by ajkis** [comment]
@ishuah is empty folder removal triggered after everything is finished or does folders get removed immediately. There could be an easy solution without the flag if those folders are removed after everything is moved since in that case we could recreate them at the end of script.

**Comment by ishuah** [comment]
Directory removal is triggered after transfer is finished.
You're proposing to create the deleted directories with your own script after `move`, right?

**Comment by ajkis** [comment]
Is it after all transfers are finished or per transfer 

eg if i do 
rclone move /storage/local remote: 

and its transferring
/storage/local/movies/Title1 
/storage/local/series/TVshow1/Season 01

once ./movie/Title1 is transferred ( but series are still in progress ), will rclone immediately delete /storage/local/movies ... or that happens after all transfers are finished and then cleanup is preformed at the end. 
If thats the case then I could just recreate missing folders after rclone is finished, otherwise I would need to cron or inotify script that will keep recreating folders as soon as they are deleted.

**Comment by ishuah** [comment]
Now I understand your question.
Directory deletion happens after transfers are completed, you can recreate the missing directories after rclone is done.

**Comment by l3uddz** [comment]
i think it would be nicer if this option was itself a flag on the move command, e.g. ```--delete-empty-dirs``` as alot of people already use their own scripts to remove empty directories.

**Comment by ishuah** [comment]
@l3uddz great idea, I'm all for it.
what do you think, @ncw?

**Comment by ncw** [comment]
@ishuah a flag on just the move command is a good idea I think and saves the proliferation of global flags.

**Comment by ishuah** [comment]
Great! I'll put together a PR.

**Comment by ishuah** [comment]
Please find a beta version with a fix here: https://beta.rclone.org/v1.38-188-gaab8051f/ (Uploaded in 15-30 minutes)
