### ISSUE TITLE
curl install for rclone

### ISSUE THREAD

**Issue by ncw** [ncw/rclone#1856]
I was thinking about doing a curl install for rclone

    curl https://rclone.org/install.sh | sudo bash

and maybe

    curl https://rclone.org/install-beta.sh | sudo bash

But then the thought of writing lots of shell script which works on linux/os x/bsd made me think that someone else might like to have a go!

It should automate the download and install steps from here https://rclone.org/install/

**Comment by qaskai** [comment]
While I wait for clarification on other issue, I'll be happy to write this script.
There are no installation instructions for bsd systems, can I assume they will look the same as for Linux or macOS?

**Comment by ncw** [comment]
Super!

**Comment by qaskai** [comment]
Ok, I got the script tested and working on linux/osx/freebsd. NetBSD and OpenBSD require more effort to set up, so I think maybe when I'll create a PR someone will volunteer to test it on theirs OS.
One quick question - I noticed that there are only linux instructions for setting up manuals. Should it stay that way, not installing rclone manuals for other systems?

**Comment by ncw** [comment]
If you can install the man page for the other OSes that would be great.  I would have thought all the unixes would be very similar here.

**Comment by ncw** [comment]
This is now done and live - thank you @qaskai
