### ISSUE TITLE
Directory tree not available as soon as target dir is reported as mounted (rclone mount)

### ISSUE THREAD

**Issue by Nodens-** [ncw/rclone#1858]
> What is your rclone version (eg output from `rclone -V`)

    rclone v1.38-DEV

    os/arch: linux/amd64
    go version: go1.9.1

> Which OS you are using and how many bits (eg Windows 7, 64 bit)

Fedora 27 x64

> Which cloud storage system are you using? (eg Google Drive)

Google Drive
> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

rclone mount -vv --allow-other --default-permissions --cache-mode writes --log-file=/tmp/rclone.log gd: $1 &"

It seems that the directory tree is not available as soon as the target directory is reported to be mounted.
I am automounting using /etc/fstab in this way:

> gdfuse           /Drive/.remote  fuse    uid=1000,gid=500,user,_netdev   0 0
gocryptdrive    /Drive/remote   fuse    uid=1000,gid=500,user,_netdev,x-systemd.requires=/Drive/.remote   0 0

This works with google-drive-ocamlfuse. The x-systemd.requires parameter makes it so the second script is called when the directory passed is actually mounted.
In rclone mount case, the second script calling gocryptfs, fails with gocryptfs complaining that the cipherdir mountpoint (/Drive/.remote/cipherdir) is not available.
My workaround is to add a "sleep 3" to the gocryptfs script but that is basically an unreliable hack heh.

**Comment by ncw** [comment]
Nobody likes random sleeps ;-)

>  The x-systemd.requires parameter makes it so the second script is called when the directory passed is actually mounted.

How does that actually work?  The only mechanism I'm aware of was the one added in d8b3bf014db1d3bf3eaa0f552e5ef8983c11f23a in?

`rclone mount` doesn't fork into the background like most mount programs so I think that little `&` is causing your problems...

It might be that what you want to do is run

  rclone mount -vv --allow-other --default-permissions --cache-mode writes --log-file=/tmp/rclone.log gd: $1 &"

But then don't continue until the mount point is mounted something like

while [ "`ls /mount`" = "" ]; do sleep 1 ; echo "waiting for mount"; done

You could also mount stuff with systemd which will use notify

```
# cat /etc/systemd/system/rclone-mount.service
# Rclone mount on boot ( service file template - add aditional rclone parameters )
# Copy file to: /etc/systemd/system
# Set remote name (current acdcrypt), path to mount and User,Group (current plex)
# Register new service by typing:
# sudo systemctl daemon-reload
# sudo systemctl enable rclone-mount.service
# systemctl start rclone-mount.service
# systemctl enable NetworkManager-wait-online.service
# Usage:
# To unmount drive use
# systemctl stop rclone-mount.service
# To mount use:
# systemctl start rclone-mount.service

[Unit]
Description=rclone mount
Documentation=http://rclone.org/docs/
After=network-online.target

[Service]
Type=notify
User=www-data
Group=www-data
ExecStart=/usr/bin/rclone mount -v remote:path /mnt/mountpoint
ExecStop=/bin/fusermount -uz /mnt/mountpoint

[Install]
Wants=network-online.target
```

**Comment by Nodens-** [comment]
File systems mounted in /etc/fstab are handled by systemd anyhow (on systems with systemd of course :)). They are also initiated in parallel because of systemd and not sequentially like in the init era and this is what "x-systemd.requires" was implemented to solve.
"x-systemd.requires" is essentially the equivalent of a Requires= + After= statements in a systemd unit that bind to the equivalent .mount systemd unit that handles the mountpoint.
See here: https://www.freedesktop.org/software/systemd/man/systemd.mount.html
 What I am not sure is if you can actually use the same mechanism (notify) for this as well.

I had tried of using systemd units before but google-drive-ocamlfuse was not behaving very nice with it creating quite a bit of stalling both on boot and shutdown (one of the many things it was not behaving nice with :p) .
I will test again with systemd units and get back to you. In fact I prefer using systemd units because it handles stdout/stderr automatically as well.

**Comment by Nodens-** [comment]
Working great with systemd units. If anyone is interested in the configuration for proper dependecies with rclone+gocryptfs this is the setup I used which can be edited accordingly for your need:

> # cat /etc/systemd/system/rclone-mount.service
# Rclone mount on boot ( service file template - add aditional rclone parameters                                                                                                                                                              )
# Copy file to: /etc/systemd/system
# Set remote name (current acdcrypt), path to mount and User,Group (current plex                                                                                                                                                             )
# Register new service by typing:
# sudo systemctl daemon-reload
# sudo systemctl enable rclone-mount.service
# systemctl start rclone-mount.service
# systemctl enable NetworkManager-wait-online.service
# Usage:
# To unmount drive use
# systemctl stop rclone-mount.service
# To mount use:
# systemctl start rclone-mount.service

[Unit]
Description=rclone mount
Documentation=http://rclone.org/docs/
Requires=local-fs.target network-online.target
After=local-fs.target network-online.target
Before=gocryptdrive.service

[Service]
Type=notify
User=user_name
Group=group_name
ExecStart=/usr/local/bin/rclone mount -vv --allow-other --default-permissions --                                                                                                                                                             cache-mode writes --log-file=/tmp/rclone.log gd: /Drive/.remote
ExecStop=/bin/fusermount -zu /Drive/.remote

[Install]
WantedBy=network-online.target
Wants=gocryptdrive.service

and:

> [Unit]
Description=gocryptfs Mount Unit
Requires=local-fs.target network-online.target rclone.service
After=local-fs.target network-online.target rclone.service

[Service]
Type=forking
User=user_name
Group=group_name
ExecStart=/usr/local/bin/gocryptfs --allow_other --noprealloc -passfile /home/user_name/.gdcrypt /Drive/.remote/cipherdir /Drive/remote
ConditionPathIsDirectory=/Drive/.remote/cipherdir
ExecStop=/bin/fusermount -zu /Drive/remote
Restart=on-failure
RestartSec=5

[Install]
WantedBy=rclone.service

**Comment by ncw** [comment]
Very interesting - thank you!

I'll close this now as I think we've found a satisfactory solution.

**Comment by Nodens-** [comment]
I'm closing this. Not sure if you want to check if the notification can be implemented in general but you can reopen if that is the case.
