### ISSUE TITLE
err=cache open file failed: open /path/to/cache no such file or directory (rclone mount)

### ISSUE THREAD

**Issue by Nodens-** [ncw/rclone#1860]
> What is your rclone version (eg output from `rclone -V`)

    rclone v1.38-DEV
    os/arch: linux/amd64
    go version: go1.9.1

> Which OS you are using and how many bits (eg Windows 7, 64 bit)

Fedora 27 x64

> Which cloud storage system are you using? (eg Google Drive)

Google Drive

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

rclone mount -vv --allow-other --default-permissions --cache-mode writes --bwlimit=200K --log-file=/tmp/rclone.log gd: $1
+gocryptfs

> 2017/11/25 12:02:07 DEBUG : &{Wintermute/ece9etyShgx1rMhi029Piw/tuHKLE2e32EvxQgR0AcsQOnBACsVWohFLHNAf0TTFojxBW_wabmxTCzfo0H7Us5eEit-ccdL3Z-Ka1qQBOswjg/GeGRTQefIRg4rVrvQ6Lv_g (rw)}: >Read: read=0, err=cache open file failed: open /home/user/.cache/rclone/vfs/gd/Wintermute/ece9etyShgx1rMhi029Piw/tuHKLE2e32EvxQgR0AcsQOnBACsVWohFLHNAf0TTFojxBW_wabmxTCzfo0H7Us5eEit-ccdL3Z-Ka1qQBOswjg/GeGRTQefIRg4rVrvQ6Lv_g: no such file or directory

Copying directories with Midnite Commander (mc) to the mount. I got the above after a while.
Retrying the copy op in mc results in repetition of the error in the log.

I wonder if this is could be cache eviction related due to the bandwidth limit set to a low value?
Log attached.

[log.txt](https://github.com/ncw/rclone/files/1502971/log.txt)

**Comment by ncw** [comment]
Here are the lines in the log which mention that file

```
     23:2017/11/25 12:02:06 DEBUG : Wintermute/ece9etyShgx1rMhi029Piw/tuHKLE2e32EvxQgR0AcsQOnBACsVWohFLHNAf0TTFojxBW_wabmxTCzfo0H7Us5eEit-ccdL3Z-Ka1qQBOswjg/GeGRTQefIRg4rVrvQ6Lv_g: Attr: 
     24:2017/11/25 12:02:06 DEBUG : Wintermute/ece9etyShgx1rMhi029Piw/tuHKLE2e32EvxQgR0AcsQOnBACsVWohFLHNAf0TTFojxBW_wabmxTCzfo0H7Us5eEit-ccdL3Z-Ka1qQBOswjg/GeGRTQefIRg4rVrvQ6Lv_g: >Attr: a=valid=1m0s ino=0 size=0 mode=-rw-r--r--, err=<nil>
     25:2017/11/25 12:02:06 DEBUG : &{Wintermute/ece9etyShgx1rMhi029Piw/tuHKLE2e32EvxQgR0AcsQOnBACsVWohFLHNAf0TTFojxBW_wabmxTCzfo0H7Us5eEit-ccdL3Z-Ka1qQBOswjg/GeGRTQefIRg4rVrvQ6Lv_g (rw)}: Read: len=4096, offset=0
     26:2017/11/25 12:02:07 DEBUG : Wintermute/ece9etyShgx1rMhi029Piw/tuHKLE2e32EvxQgR0AcsQOnBACsVWohFLHNAf0TTFojxBW_wabmxTCzfo0H7Us5eEit-ccdL3Z-Ka1qQBOswjg/GeGRTQefIRg4rVrvQ6Lv_g: Opening cached copy with flags=O_RDWR|O_CREATE|O_EXCL
     27:2017/11/25 12:02:07 DEBUG : &{Wintermute/ece9etyShgx1rMhi029Piw/tuHKLE2e32EvxQgR0AcsQOnBACsVWohFLHNAf0TTFojxBW_wabmxTCzfo0H7Us5eEit-ccdL3Z-Ka1qQBOswjg/GeGRTQefIRg4rVrvQ6Lv_g (rw)}: >Read: read=0, err=cache open file failed: open /home/user/.cache/rclone/vfs/gd/Wintermute/ece9etyShgx1rMhi029Piw/tuHKLE2e32EvxQgR0AcsQOnBACsVWohFLHNAf0TTFojxBW_wabmxTCzfo0H7Us5eEit-ccdL3Z-Ka1qQBOswjg/GeGRTQefIRg4rVrvQ6Lv_g: no such file or directory
```

The file was opened for `O_RDWR|O_CREATE|O_EXCL` which means that the open should have created the file anew if it didn't exist.  However it didn't work, so I think an intermediate directory must be missing.

I wonder if the cache got cleaned and the intermediate directory got removed between the open (which I don't see in your log).

Can you check to see if the intermediate directories are missing?

Commenting this code out in `vfs/cache.go` will fix it if that is the problem.

```go
	// Now tidy up any empty directories
	err = fs.Rmdirs(c.f, "")
	if err != nil {
		fs.Errorf(c.f, "Failed to remove empty directories from cache: %v", err)
	}
```

Can you try that?  If that works then I'll think of a better fix!

PS I see that file was opened with O_EXCL which I think I probably need to take more care with, but I don't think it is the problem in this case.

**Comment by Nodens-** [comment]
Intermediate directory gets created at 11:21 then there's this:

[log.txt](https://github.com/ncw/rclone/files/1503027/log.txt)

The error comes shortly after. I didn't see it at first as the encrypted dir/file names make my eyes hurt when reading the log.
(Not attaching the entire log as it's huge heh)

I will try the commenting the snippet if you confirm this is actually it.

**Comment by ncw** [comment]
Yes that looks like exactly what I said, the handle was opened, a cache clean came along, then the underlying file was opened. So that tweak should fix it...

**Comment by Nodens-** [comment]
I have been getting "failure to remove from cache: no such file or directory"
I do not see the files removed prior to the message but perhaps I'm missing it.
I have checked and the files are actually deleted from cache and the parent directory is still there. Example file for quick search in the log is RP19oBEg85zLDeGoE2jfNw

Attaching 55mb log zipped.

[log.zip](https://github.com/ncw/rclone/files/1503742/log.zip)

**Comment by ncw** [comment]
I see what is happening.  This is because you have the cache in `writes` mode which means it deletes the file after it is uploaded.

```
 258724:2017/11/26 08:45:36 INFO  : Wintermute/ChyqJKILNSt1J8sdiBvVjA/eJEinkHgUw2quCjK-uK2ftgW3r8LKHM3aA4XZjfaJjd0smZJ6r4ZEHgCfaqwD2eh7cI3yc4sSiops4f9qK1pHA/RP19oBEg85zLDeGoE2jfNw: Copied (new)
 258725:2017/11/26 08:45:36 INFO  : Wintermute/ChyqJKILNSt1J8sdiBvVjA/eJEinkHgUw2quCjK-uK2ftgW3r8LKHM3aA4XZjfaJjd0smZJ6r4ZEHgCfaqwD2eh7cI3yc4sSiops4f9qK1pHA/RP19oBEg85zLDeGoE2jfNw: Deleted
 258726:2017/11/26 08:45:37 DEBUG : Wintermute/ChyqJKILNSt1J8sdiBvVjA/eJEinkHgUw2quCjK-uK2ftgW3r8LKHM3aA4XZjfaJjd0smZJ6r4ZEHgCfaqwD2eh7cI3yc4sSiops4f9qK1pHA/RP19oBEg85zLDeGoE2jfNw: transferred to remote
```

However I didn't remove the marker that the file exists in the cache.

The error is cosmetic only thankfully, but I'll fix it properly shortly.

**Comment by Nodens-** [comment]
Yes I thought it was something like that but better safe than sorry. I'm monitoring the logs constantly and will continue to do so for a least a week of 24/7 transfers to ensure the scheme works properly, before I start pushing real backup data. 

Regarding the original reported issue, if I understand correctly, this happens because the cleaning functionality happens to trigger in between 2 files copied from the same directory and finding the directory empty due to using writes mode, correct?
 The best way to fix it would be to check if new file copied has intermediate path directories available in cache and if not recreate the requested path so we can keep cleaning empty directories. But only if the copy has already failed once, so i/o performance is not affected.
I'm assuming cleaning function is running in its own thread so it needs to be paused from the moment a new file starts being copied to when it's fd is locked inside the cache directory since directories can not be locked.

**Comment by ncw** [comment]
Both those issue should be fixed here

https://beta.rclone.org/v1.38-192-g6d3df6f1/ (uploaded in 15-30 mins)

I've also checked all 96 of the possible open flags combinations and put some fixes in!

**Comment by Nodens-** [comment]
Great! Closing this.

**Comment by ncw** [comment]
Thanks for testing - please open more issues if you find more problems!

**Comment by Nodens-** [comment]
Cache eviction issue is happening again.

[rclone.zip](https://github.com/ncw/rclone/files/1520960/rclone.zip)

**Comment by ncw** [comment]
Sorry - I missed your message

I only see 1 error in your log

```
2017/12/01 02:07:00 ERROR : Wintermute/-p0rIIcSb1C2Yv12WUbL6A/v5klf_Sj-0wqfn1yVK1R-H1Ui5EyATX7UlcdFwZfrhiGlKAW5gx_hH4-kqq4fjpDnhY9KwoejPokZMt6m-iWeNtM4kBk2UXkP3g8xAMYDow/V-ukmpIXUt3Qm1zCFvtF1hg1d8AL0WJDL_pAHWzUVno: RWFileHandle.Release error: cache open file failed: open /home/user/.cache/rclone/vfs/gd/Wintermute/-p0rIIcSb1C2Yv12WUbL6A/v5klf_Sj-0wqfn1yVK1R-H1Ui5EyATX7UlcdFwZfrhiGlKAW5gx_hH4-kqq4fjpDnhY9KwoejPokZMt6m-iWeNtM4kBk2UXkP3g8xAMYDow/V-ukmpIXUt3Qm1zCFvtF1hg1d8AL0WJDL_pAHWzUVno: no such file or directory
```

That file doesn't appear elsewhere in your log file and it happened on release (close) of the file handle when the file was being opened.

So it looked like an empty file was being written so I think this probably isn't a cache interaction problem.

Which version of rclone were you using?

Can you reproduce this problem?  I really need to see a log with `-vv` to work out what is going on if possible.

**Comment by Nodens-** [comment]
No worries. :)
I am compiling from git and did not want to pull until I heard from you. My local repo is at

> 47450ba3266caf2c6e4a39b1da8dc5a2391488b5 (HEAD -> master, origin/master, origin/HEAD) cache: handle errors when bolt tries to start

I have switched back to -vv since it started happening again and I'm currently sitting on a 1gb log. The error happens intermittently but almost always when moving directories with lots of biggish files with mc so I believe it is the same issue. I have split the file to 400k line chunks and I'm zipping and attaching the last 3 chunks.
[rclone.zip](https://github.com/ncw/rclone/files/1560758/rclone.zip)

**Comment by ncw** [comment]
Thanks for the log - very helpful.

Here is the relevant log, so it looks like you are right - the cache cleaning is still deleting directories in use which is disappointing as c16ac697a9cd2b4814a28889b6a222a2c5ab4645 was supposed to fix that.

So between the Open (which created the directory) and the Read (when the file was actually opened in the cloud storage) a cache clean came along and removed the directory.

```
2017/12/11 16:57:13 DEBUG : Wintermute/XXA/XXB/XXC/XXD: Open: flags=O_RDWR|O_CREATE|O_EXCL
2017/12/11 16:57:13 DEBUG : Wintermute/XXA/XXB/XXC/XXD: >Open: fd=Wintermute/XXA/XXB/XXC/XXD (rw), err=<nil>
2017/12/11 16:57:13 DEBUG : Wintermute/XXA/XXB/XXC/: >Create: node=Wintermute/XXA/XXB/XXC/XXD, handle=&{Wintermute/XXA/XXB/XXC/XXD (rw)}, err=<nil>
2017/12/11 16:57:13 DEBUG : Wintermute/XXA/XXB/XXC/XXD: Attr: 
2017/12/11 16:57:13 DEBUG : Wintermute/XXA/XXB/XXC/XXD: >Attr: a=valid=1m0s ino=0 size=0 mode=-rw-r--r--, err=<nil>
2017/12/11 16:57:13 DEBUG : Wintermute/XXA/XXB/XXC/: Attr: 
2017/12/11 16:57:13 DEBUG : Wintermute/XXA/XXB/XXC/: >Attr: attr=valid=1m0s ino=0 size=0 mode=drwxr-xr-x, err=<nil>
2017/12/11 16:57:13 DEBUG : &{Wintermute/XXA/XXB/XXC/XXD (rw)}: Read: len=4096, offset=0

2017/12/11 16:57:13 DEBUG : Cleaning the cache

2017/12/11 16:57:14 DEBUG : Wintermute/XXA/XXB/XXC/XXD: Opening cached copy with flags=O_RDWR|O_CREATE|O_EXCL
2017/12/11 16:57:14 DEBUG : &{Wintermute/XXA/XXB/XXC/XXD (rw)}: >Read: read=0, err=cache open file failed: open /home/user/.cache/rclone/vfs/gd/Wintermute/XXA/XXB/XXC/XXD: no such file or directory
```

I'll work on a fix...

**Comment by ncw** [comment]
I've pushed a fix for this in 29d34426bc2ced9ca6ad083ac6f67d85b942e4b1

Let me know if it works for you :-)

https://beta.rclone.org/v1.38-236-g29d34426/ (uploaded in 15-30 mins)

**Comment by Nodens-** [comment]
Has not happened for a few days running straight. I'm closing this.

**Comment by ncw** [comment]
Thanks for testing :-)
