### ISSUE TITLE
Entry doesn't belong in directory "" (contains subdir)

### ISSUE THREAD

**Issue by askhalil** [ncw/rclone#1866]
I am trying to sync containers of OpenStack Swift but when it gets to some files that are in subdirectories, it fails and here is the output.

> What is your rclone version (eg output from `rclone -V`)
rclone v1.38
- os/arch: linux/amd64
- go version: go1.9

> Which OS you are using and how many bits (eg Windows 7, 64 bit)
Ubuntu 16.04

> Which cloud storage system are you using? (eg Google Drive)
OpenStack Swift

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone sync ruh:sso_db_backups jed:sso_db_backups -vv

> A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
2017/11/29 14:23:15 DEBUG : Using config file from "/home/cartwheel/.config/rclone/rclone.conf"
2017/11/29 14:23:15 DEBUG : rclone: Version "v1.38" starting with parameters ["rclone" "sync" "ruh:sso_db_backups" "jed:sso_db_backups" "-vv"]
2017/11/29 14:23:15 INFO  : Swift container sso_db_backups: Modify window is 1ns
2017/11/29 14:23:16 ERROR : /basebackups_005/base_00000001000001A500000098_00000040/extended_version.txt: Entry doesn't belong in directory "" (contains subdir) - ignoring
2017/11/29 14:23:16 ERROR : /basebackups_005/base_00000001000001A500000098_00000040/tar_partitions/part_00000000.tar.lzo: Entry doesn't belong in directory "" (contains subdir) - ignoring
2017/11/29 14:23:16 ERROR : /basebackups_005/base_00000001000001A500000098_00000040_backup_stop_sentinel.json: Entry doesn't belong in directory "" (contains subdir) - ignoring
2017/11/29 14:23:16 ERROR : /basebackups_005/base_00000001000001A50000009A_00000040/extended_version.txt: Entry doesn't belong in directory "" (contains subdir) - ignoring
2017/11/29 14:23:16 ERROR : /basebackups_005/base_00000001000001A50000009A_00000040/tar_partitions/part_00000000.tar.lzo: Entry doesn't belong in directory "" (contains subdir) - ignoring
2017/11/29 14:23:16 ERROR : /basebackups_005/base_00000001000001A50000009A_00000040_backup_stop_sentinel.json: Entry doesn't belong in directory "" (contains subdir) - ignoring
2017/11/29 14:23:16 ERROR : /basebackups_005/base_00000001000001A50000009C_00000040/extended_version.txt: Entry doesn't belong in directory "" (contains subdir) - ignoring
2017/11/29 14:23:16 ERROR : /basebackups_005/base_00000001000001A50000009C_00000040/tar_partitions/part_00000000.tar.lzo: Entry doesn't belong in directory "" (contains subdir) - ignoring
2017/11/29 14:23:16 ERROR : /basebackups_005/base_00000001000001A50000009C_00000040_backup_stop_sentinel.json: Entry doesn't belong in directory "" (contains subdir) - ignoring
2017/11/29 14:23:16 ERROR : /basebackups_005/base_00000001000001A50000009E_00000040/extended_version.txt: Entry doesn't belong in directory "" (contains subdir) - ignoring
2017/11/29 14:23:16 ERROR : /basebackups_005/base_00000001000001A50000009E_00000040/tar_partitions/part_00000000.tar.lzo: Entry doesn't belong in directory "" (contains subdir) - ignoring
2017/11/29 14:23:16 ERROR : /basebackups_005/base_00000001000001A50000009E_00000040_backup_stop_sentinel.json: Entry doesn't belong in directory "" (contains subdir) - ignoring
2017/11/29 14:23:16 ERROR : /basebackups_005/base_00000001000001A5000000A0_00000040/extended_version.txt: Entry doesn't belong in directory "" (contains subdir) - ignoring
2017/11/29 14:23:16 ERROR : /basebackups_005/base_00000001000001A5000000A0_00000040/tar_partitions/part_00000000.tar.lzo: Entry doesn't belong in directory "" (contains subdir) - ignoring
2017/11/29 14:23:16 ERROR : /basebackups_005/base_00000001000001A5000000A0_00000040_backup_stop_sentinel.json: Entry doesn't belong in directory "" (contains subdir) - ignoring
2017/11/29 14:23:16 ERROR : /basebackups_005/base_00000001000001A5000000A2_00000040/extended_version.txt: Entry doesn't belong in directory "" (contains subdir) - ignoring
2017/11/29 14:23:16 ERROR : /basebackups_005/base_00000001000001A5000000A2_00000040/tar_partitions/part_00000000.tar.lzo: Entry doesn't belong in directory "" (contains subdir) - ignoring
2017/11/29 14:23:16 ERROR : /basebackups_005/base_00000001000001A5000000A2_00000040_backup_stop_sentinel.json: Entry doesn't belong in directory "" (contains subdir) - ignoring
2017/11/29 14:23:16 ERROR : /basebackups_005/base_00000001000001A5000000A4_00000040/extended_version.txt: Entry doesn't belong in directory "" (contains subdir) - ignoring
2017/11/29 14:23:16 ERROR : /basebackups_005/base_00000001000001A5000000A4_00000040/tar_partitions/part_00000000.tar.lzo: Entry doesn't belong in directory "" (contains subdir) - ignoring
2017/11/29 14:23:16 ERROR : /basebackups_005/base_00000001000001A5000000A4_00000040_backup_stop_sentinel.json: Entry doesn't belong in directory "" (contains subdir) - ignoring
2017/11/29 14:23:16 ERROR : /basebackups_005/base_00000001000001A5000000A6_00000040/extended_version.txt: Entry doesn't belong in directory "" (contains subdir) - ignoring
2017/11/29 14:23:16 ERROR : /basebackups_005/base_00000001000001A5000000A6_00000040/tar_partitions/part_00000000.tar.lzo: Entry doesn't belong in directory "" (contains subdir) - ignoring
2017/11/29 14:23:16 ERROR : /basebackups_005/base_00000001000001A5000000A6_00000040_backup_stop_sentinel.json: Entry doesn't belong in directory "" (contains subdir) - ignoring
2017/11/29 14:23:16 ERROR : /basebackups_005/base_00000001000001A5000000A8_00000040/extended_version.txt: Entry doesn't belong in directory "" (contains subdir) - ignoring
2017/11/29 14:23:16 ERROR : /basebackups_005/base_00000001000001A5000000A8_00000040/tar_partitions/part_00000000.tar.lzo: Entry doesn't belong in directory "" (contains subdir) - ignoring
2017/11/29 14:23:16 ERROR : /basebackups_005/base_00000001000001A5000000A8_00000040_backup_stop_sentinel.json: Entry doesn't belong in directory "" (contains subdir) - ignoring
2017/11/29 14:23:16 ERROR : /basebackups_005/base_00000001000001A5000000AA_00000040/extended_version.txt: Entry doesn't belong in directory "" (contains subdir) - ignoring
2017/11/29 14:23:16 ERROR : /basebackups_005/base_00000001000001A5000000AA_00000040/tar_partitions/part_00000000.tar.lzo: Entry doesn't belong in directory "" (contains subdir) - ignoring
2017/11/29 14:23:16 ERROR : /basebackups_005/base_00000001000001A5000000AA_00000040_backup_stop_sentinel.json: Entry doesn't belong in directory "" (contains subdir) - ignoring
2017/11/29 14:23:16 INFO  : Swift container sso_db_backups: Waiting for checks to finish
2017/11/29 14:23:16 INFO  : Swift container sso_db_backups: Waiting for transfers to finish
2017/11/29 14:23:16 INFO  : Waiting for deletions to finish
2017/11/29 14:23:16 INFO  :
Transferred:      0 Bytes (0 Bytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:       700ms

2017/11/29 14:23:16 DEBUG : Go routines at exit 5
2017/11/29 14:23:16 DEBUG : rclone: Version "v1.38" finishing with parameters ["rclone" "sync" "ruh:sso_db_backups" "jed:sso_db_backups" "-vv"]

Please help

**Comment by ncw** [comment]
I think this is the same issue as #1816 - can you try the workaround in that issue and see if it works for you?

**Comment by askhalil** [comment]
I tried it on my MacOS and the same problem is occurring.

**Comment by ncw** [comment]
I'm closing this one in favour of  #1816 - please comment there.

**Comment by kac-** [comment]
@ncw I've got same messages while doing `ls` *FROM* **B2**.
Issue exists when an **appKey** doesn't have **readFiles** capability/access (i.e. **listFiles** only).
*b2-driver* on `ls` could use [b2_list_file_names](https://www.backblaze.com/b2/docs/b2_list_file_names.html) which returns names and sizes and requires only **listFiles** capability.
I *guess* that it calls/uses [b2_get_file_info](https://www.backblaze.com/b2/docs/b2_get_file_info.html) or so that requires **readFiles**.

**Comment by ncw** [comment]
@kac-  - did you try [the latest beta](https://beta.rclone.org)?  That has some specific fixes for b2 capabilities.  If it is still broken can you make a new issue please with an easy way to reproduce - thanks!
