### ISSUE TITLE
Mount a crypted mounted fuse

### ISSUE THREAD

**Issue by kaileu** [ncw/rclone#1869]
Hi i have the Problem that i want to Mount a crypted fuse from another program.
But if i Mount the Folder is empty. i guess it trys to Mount the underlying Folder which is of couse empty.

I am using the latest rclone. Mounting the crypted files directly works great but i Need this Feature for another fuse System because rclone don't Support it.

**Comment by ncw** [comment]
This is probably question best for the forum, but try the `--allow-other` flag on the rclone mount - that should help.

Also make sure your fuse config has `user_allow_other` in it.

```
$ cat /etc/fuse.conf
# /etc/fuse.conf - Configuration file for Filesystem in Userspace (FUSE)

# Set the maximum number of FUSE mounts allowed to non-root users.
# The default is 1000.
#mount_max = 1000

# Allow non-root users to specify the allow_other or allow_root mount options.
user_allow_other
```
