### ISSUE TITLE
[Feature Request] Repeat task with encrypted configuration

### ISSUE THREAD

**Issue by jbd70** [ncw/rclone#1871]
It would be nice if one could run rclone in a cronjob with an encrypted config file, and only need to enter the password once. Maybe with something like a `--repeat` flag? Not sure if that's possible but it would help me a lot. Awesome project. Thanks!

**Comment by jbd70** [comment]
Oh and just to clarify this is what I mean:

```
while true :
do
  rclone move /local/path remote_path:/
done
```

would become

`rclone move --repeat /local/path remote_path:/`

**Comment by ncw** [comment]
If you don't want to enter the pasword multiple times then use this [from the docs](https://rclone.org/docs/#configuration-encryption) in your script

```
read -s RCLONE_CONFIG_PASS
export RCLONE_CONFIG_PASS
```

I'm gong to close this as there is already a ticket about making rclone loop here #1119
