### ISSUE TITLE
[Feature Request] CACHE-DB-PATH parameter

### ISSUE THREAD

**Issue by PiscisSwimeatus** [ncw/rclone#1872]
Ability to define separate location for the db and the chunks.

**Comment by remusb** [comment]
Thank you @PiscisSwimeatus 

It's in the last beta: 
Docs updated too: https://github.com/ncw/rclone/blob/master/docs/content/cache.md#--cache-chunk-pathpath

It should be backwards compatible in the sense that if someone was giving a db-path until now will still work for them without having the need to specify a chunk-path. If you want them separate though, you can specify both options or just the last really.
