### ISSUE TITLE
[Feature Request] Add an option to tell rmdirs not to remove root directory

### ISSUE THREAD

**Issue by pei-lun** [ncw/rclone#1874]
As advised in my post on the forum ([How to use rmdirs remove empty subdirectories only? - question - rclone forum](https://forum.rclone.org/t/how-to-use-rmdirs-remove-empty-subdirectories-only/4369)), I make this issue for a new feature of `rmdirs`.

If I have empty subdirectories `/foo/bar` and `/foo/baz`, the root directory `/foo` will be removed after running `rclone rmdirs remote:/foo`. I suggest adding an option to tell `rmdirs` not to remove root directory.

**Comment by ncw** [comment]
This would mean adding a flag to the Rmdirs command in `cmd/rmdirs/rmdirs.go` say `--leave-root`, adding a boolean to `Rmdirs()` in `fs/operations.go` and skipping the Rmdir if the flag was set and the directory was "".

The tests should be updated too.

**Comment by lewapm** [comment]
I would like to solve this issue.

**Comment by ncw** [comment]
@lewapm do you mean you would like to contribute a fix for this?  Yes that would be great.

**Comment by ncw** [comment]
This has been done now here - thanks @lewapm by adding a `--leave-root` flag

https://beta.rclone.org/v1.38-230-g1b1593a8/ (uploaded in 15-30 mins)
