### ISSUE TITLE
BUG rclone sizem returns error listing: unexpected end of JSON input

### ISSUE THREAD

**Issue by ajkis** [ncw/rclone#1879]
> 2017/12/03 07:37:34 DEBUG : Using config file from "/home/plex/.config/rclone/rclone.conf"
> 2017/12/03 07:37:34 DEBUG : rclone: Version "v1.38-178-g8357a82eβ" starting with parameters ["rclone" "size" "dropbox:" "-vv" "--log-file=/home/plex/rcsize.log"]
> 2017/12/03 07:37:35 INFO  : Dropbox root '': Modify window is 1s
> 2017/12/03 07:38:31 ERROR : crypt/qbu2chuhnvlm4gjmeofgbfhjfk/77sh15g7ek83l35ul7ltsp5om8: error listing: unexpected end of JSON input
> 2017/12/03 07:38:31 ERROR : crypt/qbu2chuhnvlm4gjmeofgbfhjfk/6ta9ock8kojun3sqm7t2fdhh90nu1b9sp0h5nss1vvsdr03mp8eg/mbi5n02ae1vpobh1rod7dioak8: error listing: unexpected end of JSON input
> 2017/12/03 07:38:31 Failed to size: unexpected end of JSON input

After I used rclone dedupe dropbox: I received the following errors:

> 2017/12/03 07:47:34 DEBUG : Using config file from "/home/plex/.config/rclone/rclone.conf"
> 2017/12/03 07:47:34 DEBUG : rclone: Version "v1.38-178-g8357a82eβ" starting with parameters ["rclone" "size" "dropbox:" "-vv" "--log-file=/home/plex/rcsize.log"]
> 2017/12/03 07:47:35 DEBUG : pacer: Rate limited, increasing sleep to 20ms
> 2017/12/03 07:47:35 DEBUG : pacer: low level retry 1/10 (error too_many_requests/...)
> 2017/12/03 07:47:35 DEBUG : pacer: Rate limited, increasing sleep to 40ms
> 2017/12/03 07:47:35 DEBUG : pacer: low level retry 2/10 (error too_many_requests/)
> 2017/12/03 07:47:36 DEBUG : pacer: Rate limited, increasing sleep to 80ms
> 2017/12/03 07:47:36 DEBUG : pacer: low level retry 3/10 (error too_many_requests/.)
> 2017/12/03 07:47:36 DEBUG : pacer: Rate limited, increasing sleep to 160ms
> 2017/12/03 07:47:36 DEBUG : pacer: low level retry 4/10 (error too_many_requests/..)
> 2017/12/03 07:47:36 DEBUG : pacer: Rate limited, increasing sleep to 320ms
> 2017/12/03 07:47:36 DEBUG : pacer: low level retry 5/10 (error too_many_requests/..)
> 2017/12/03 07:47:36 DEBUG : pacer: Rate limited, increasing sleep to 640ms
> 2017/12/03 07:47:36 DEBUG : pacer: low level retry 6/10 (error too_many_requests/...)
> 2017/12/03 07:47:37 DEBUG : pacer: Rate limited, increasing sleep to 1.28s
> 2017/12/03 07:47:37 DEBUG : pacer: low level retry 7/10 (error too_many_requests/)
> 2017/12/03 07:47:37 DEBUG : pacer: Rate limited, increasing sleep to 2s
> 2017/12/03 07:47:37 DEBUG : pacer: low level retry 8/10 (error too_many_requests/...)
> 2017/12/03 07:47:38 DEBUG : pacer: low level retry 9/10 (error too_many_requests/...)
> 2017/12/03 07:47:41 DEBUG : pacer: low level retry 10/10 (error too_many_requests/..)
> 2017/12/03 07:47:41 INFO  : Dropbox root '': Modify window is 1s
> 2017/12/03 07:47:43 DEBUG : pacer: low level retry 1/10 (error too_many_requests/.)
> 2017/12/03 07:47:45 DEBUG : pacer: low level retry 2/10 (error too_many_requests/...)
> 2017/12/03 07:47:47 DEBUG : pacer: low level retry 3/10 (error too_many_requests/)
> 2017/12/03 07:47:49 DEBUG : pacer: low level retry 4/10 (error too_many_requests/..)
> 2017/12/03 07:47:51 DEBUG : pacer: low level retry 5/10 (error too_many_requests/..)
> 2017/12/03 07:47:53 DEBUG : pacer: low level retry 6/10 (error too_many_requests/...)
> 2017/12/03 07:47:55 DEBUG : pacer: low level retry 7/10 (error too_many_requests/..)
> 2017/12/03 07:47:57 DEBUG : pacer: low level retry 8/10 (error too_many_requests/)
> 2017/12/03 07:47:59 DEBUG : pacer: low level retry 9/10 (error too_many_requests/.)
> 2017/12/03 07:48:01 DEBUG : pacer: low level retry 10/10 (error too_many_requests/...)
> 2017/12/03 07:48:01 ERROR : : error listing: too_many_requests/...
> 2017/12/03 07:48:01 Failed to size: too_many_requests/...

**Comment by ncw** [comment]
I think this is probably a dropbox problem  Can you reproduce it with `--dump-headers` and paste the failing transaction?  I suspect it is the dropbox server returning a 500 error or something like that.

**Comment by ncw** [comment]
I'm pretty sure dropbox have fixed this in: https://github.com/dropbox/dropbox-sdk-go-unofficial/issues/36

I've pulled that into rclone now in 5061aaaf4673e8ab9199b6282ec11cbb5773556a so I'm going to close this now.
