### ISSUE TITLE
[BUG] mountpoint unavailable

### ISSUE THREAD

**Issue by atytel** [ncw/rclone#1882]
I'm using rclone v1.38-187 on windows 10. I was using mount in conjuction with plex to run my media. All of the sudden today after it working fine the minute before, i am unable to mount rclone to the drive letter I want. When I changed the drive letter it did not work also. In addition, was having an issue where it refused to pull the contents of one folder. Probobly just FUSE issues tho.

**Comment by ncw** [comment]
Can you make it so I can reproduce this problem?  I can't fix it unless I can reproduce it :-)

**Comment by atytel** [comment]
I was able to fix it by restarting sorry, forgot to close.
