### ISSUE TITLE
On encountering a dupe, rclone always copies the next item

### ISSUE THREAD

**Issue by diamondsw** [ncw/rclone#1883]
> What is your rclone version (eg output from `rclone -V`)
rclone v1.38
- os/arch: darwin/amd64
- go version: go1.9

> Which OS you are using and how many bits (eg Windows 7, 64 bit)
macOS 10.12.6, Debian 9/x64

> Which cloud storage system are you using? (eg Google Drive)
Google Drive (thus the dupes)

Sadly I'm catching up on bug reporting and I've since repaired all my dupes on Google Drive, so it may be a bit difficult to provide useful info. But here's what I was seeing:

When backing up to a crypted Google Drive (usually with sync, but also with copy), any time a duplicate item was encountered, the next item would be copied. This could be as simple as the next file in a folder, or more distressingly, entire directories if the next item was a directory! If there is a way I can manually create duplicates I'd be more than happy to help debug this and provide better information.

**Comment by ncw** [comment]
This, fortunately, is fixed now. It took me ages to work out what was going on - your description is absolutely perfect!

Try [the latest beta](https://beta.rclone.org) for the fix.

This is the fix: 00fe6d95daadd96b272266faa5441f4f3390f331
