### ISSUE TITLE
[BUG] Random folders inaccessible  

### ISSUE THREAD

**Issue by atytel** [ncw/rclone#1886]
> What is your rclone version (eg output from `rclone -V`)
v1.38-187
> Which OS you are using and how many bits (eg Windows 7, 64 bit)
Windows 10
> Which cloud storage system are you using? (eg Google Drive)
Google drive
> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone mount maindrive: q:

**Comment by ncw** [comment]
Can you provide more detail please?  A log with `-vv` would be helpful as would a description of how to reproduce the problem.

Thanks

**Comment by atytel** [comment]
https://pastebin.com/7Un3sXfu
Too long

**Comment by atytel** [comment]
As for recreation, the folder just has videos in it. so i can send u them if u think it would help

**Comment by atytel** [comment]
@ncw wanted to know if you need me to post anything else

**Comment by atytel** [comment]
Updating winfsp fixed it

**Comment by ncw** [comment]
Great news :-)
