### ISSUE TITLE
command and remote aliases

### ISSUE THREAD

**Issue by eadmaster** [ncw/rclone#1892]
Since i often mistake some commands (`cp` for `copy` and `list` for `ls`) i'd like to suggest adding an user-defined command aliasing feature.

Remote name aliases would be useful too for the same reason.
(could also help with common mispellings)

**Comment by phillibert** [comment]
Not sure of the particularities of your use case, but an alternative would be creating aliases within your shell environment.

**Comment by ncw** [comment]
Do you know of any examples of unix tools that do this that we could get some inspiration from?

**Comment by eadmaster** [comment]
I guess it is a job for bash functions:
```
alias gdrivecp="rclone copy"
gdrivels() { rclone ls gdrive:$1 --max-depth 1 -q; }
gdriveget() { rclone copy gdrive:$1 $2 -v; }
gdriveput() { rclone copy $1 gdrive:$2 -v; }
```

**Comment by eadmaster** [comment]
another solution:
make a wrapper rclone-launcher and add this to the top:
```
#!/bin/bash

[ "$1" = "list" ] && set ls "${@:2}"
[ "$1" = "cp" ] && set copy "${@:2}"

command -p rclone "$@"
_ES=$? ; [ $_ES -ne 127 ] && exit $_ES

$HOME/.local/bin/rclone "$@"
_ES=$? ; [ $_ES -ne 127 ] && exit $_ES

#else
exit 127

```
