### ISSUE TITLE
panic: runtime error: slice bounds out of range (crypt + cache)

### ISSUE THREAD

**Issue by zenjabba** [ncw/rclone#1896]
goroutine 1560249 [running]:
github.com/ncw/rclone/cache.(*Handle).getChunk(0xc464b92b80, 0x6400000, 0xc464b92bb8, 0x2, 0xc42b0aa7c4, 0x2, 0xc42b0aa678)
        /home/travis/gopath/src/github.com/ncw/rclone/cache/handle.go:213 +0x65a
github.com/ncw/rclone/cache.(*Handle).Read(0xc464b92b80, 0xc454e1c000, 0x1000, 0x100000, 0x0, 0x0, 0x0)
        /home/travis/gopath/src/github.com/ncw/rclone/cache/handle.go:226 +0xa4
github.com/ncw/rclone/fs.ReadFill(0x7fb6f2c613c0, 0xc464b92b80, 0xc454e1c000, 0x1000, 0x100000, 0xe6bf00, 0xf25be0, 0xeade00)
        /home/travis/gopath/src/github.com/ncw/rclone/fs/operations.go:918 +0x72
github.com/ncw/rclone/fs.(*buffer).read(0xc4218d9740, 0x7fb6f2c613c0, 0xc464b92b80, 0x7fb6f2c613c0, 0xc464b92b80)
        /home/travis/gopath/src/github.com/ncw/rclone/fs/buffer.go:255 +0x58
github.com/ncw/rclone/fs.(*asyncReader).init.func1(0xc431a67420)
        /home/travis/gopath/src/github.com/ncw/rclone/fs/buffer.go:85 +0x1e4
created by github.com/ncw/rclone/fs.(*asyncReader).init
        /home/travis/gopath/src/github.com/ncw/rclone/fs/buffer.go:73 +0x1ab

rclone v1.38-211-gbb3ba7b3β
- os/arch: linux/amd64
- go version: go1.9.2

**Comment by ncw** [comment]
This crashed here in getChunk - looks like the chunk was smaller than expected

```go
	// first chunk will be aligned with the start
	if offset > 0 {
		data = data[int(offset):]
	}
```

**Comment by remusb** [comment]
Thanks for the report @zenjabba . Would you be able to provide the exact file size (bytes) for which this happened and chunk size configured on `cache`? I'm curious if I can replicate it.

Also, it happens all the time?

**Comment by zenjabba** [comment]
type = cache
remote = streamer2_mount:/
chunk_size = 1m
info_age = 1h
chunk_age = 1m
warmup_age = 3h

It happens regularly when plex scans the mount.

**Comment by remusb** [comment]
I can’t pinpoint where it’s coming from. Simple math there that shouldn’t ever let that happen. Furthermore, I have never really seen this happening before during my scans and that type of issue should happen more frequent.

Anyway, the latest commit catches the panic, errors out the read cause I don’t understand when it happens and what should be that read about but I have added all the details I need to find out in the error log: `unexpected conditions during reading. current position: ...` I will need those errors with all their details to have some more data.

Thanks

**Comment by remusb** [comment]
https://beta.rclone.org/v1.38-223-g7c972d37/

**Comment by easy90rider** [comment]
@remusb do you need -vv logs for 217?

For 223 -v logs are enough? or should I give you -vv ones?

**Comment by remusb** [comment]
-v logs should be fine @easy90rider

**Comment by jrarseneau** [comment]
Got this bug too, will download the latest beta and see what happens and report back

**Comment by easy90rider** [comment]
@remusb 

It didn't crash!
I refreshed metadata for something containing 1001 files, 300-350 didn't have media info so Plex had to analyze them.

https://pastebin.com/RA53GxKZ  - renamed a few things...

It downloaded about 9.6GB of data, but as you can see it removed chunks.

**Comment by remusb** [comment]
@easy90rider I think I understand the issue now. Partially at least. The reader gets the last chunk a bit smaller than it should be compared to the entire file size. I've removed some logic which could have trimmed the last chunk but I'm not overly confident. It seems to be the last couple of kb so this won't really be noticeable for a movie playback.

Try out the latest beta when you have the chance. It's likely those errors won't appear anymore. Please do share the result when you can.

Tip: it seems you have a fairly large library. 5GB of cache is a bit small. That's why you're already seeing deletions during scanning. The total size you gave won't even be enough to get through a full library scan.
If you're low on disk you can still go like this but since Plex scans most of the time you will also generate a bit of traffic on the cloud provider too.

**Comment by remusb** [comment]
Last beta would be here: https://beta.rclone.org/v1.38-224-g829dd1ad/

**Comment by jrarseneau** [comment]
How big should the cache be? Any formula we could use?

**Comment by toomuchio** [comment]
@remusb I also encountered this error during testing, tried the latest beta didn't have it again.

Is there a value we can use for info_age that would cause it to never expire, I don't modify things outside of mount. So that would be ideal for me, even without changelog support.

@jrarseneau Use the biggest value you're comfortable with, and have the space for I'd say. More cache the better really. I have a spare 512GB SSD I'm intending to use just for this cache.

**Comment by zenjabba** [comment]
Given most of us update outside the mount, getting the file system updated would be a fantastic addon.

**Comment by zenjabba** [comment]
I've been trying the latest beta, and also have not seen the error re-appear.

**Comment by toomuchio** [comment]
I'd mentioned changelog updates once before, and it's in the todo list already. But I noticed I don't really update outside mount, except adding new stuff which would just get added to the cache anyway.

Renames, moves ect I only do within mount.

**Comment by easy90rider** [comment]
@remusb FYI I was scanning, not reading the entire file. In the log I only had one file that I read completely, aka. one that I played back.

All my files are mp4s that are web optimized, so the moov atom is at the beginning of the file structure. 

I can only suppose that Plex shouldn't read the end of the file, since it has all the info at the beginning. 

My library is around 4TB 👍 and yeah I am very low on disk space :-D 
Plex only scans when I ask it to scan. BTW Emby is much better when it comes to library scanning, it uses much less data.

**Comment by remusb** [comment]
closing this in favour of https://github.com/ncw/rclone/issues/1904

the panic covered here should be fixed now I hope

**Comment by DickVicious** [comment]
Hi,

I am getting an error after adding the cache remote to my config

```
2018/02/22 18:53:03 NOTICE: Encrypted drive 'GDrive-Enc:/': poll-interval is not supported by this remote
2018/02/22 18:53:16 fuse: panic in handler for Read [ID=0x6 Node=0x1 Uid=1001 Gid=1001 Pid=31348] 0x1 4096 @0x0 dir=true fl=0 lock=0 ffl=OpenReadOnly+OpenDirectory+OpenNonblock: runtime error: slice bounds out of range
goroutine 67 [running]:
github.com/ncw/rclone/vendor/bazil.org/fuse/fs.(*Server).serve.func2(0x15853a0, 0xc4201ee000, 0xc4202fdef8, 0xc4202fde6f)
        /home/ncw/go/src/github.com/ncw/rclone/vendor/bazil.org/fuse/fs/serve.go:857 +0x1b1
panic(0xe5ff40, 0x15cddc0)
        /opt/go/go1.9/src/runtime/panic.go:491 +0x283
github.com/ncw/rclone/cache.(*Directory).Remote(0xc4201a6ee0, 0x1a, 0x1a)
        /home/ncw/go/src/github.com/ncw/rclone/cache/directory.go:98 +0x117
github.com/ncw/rclone/cache.(*Persistent).GetDirEntries.func1(0xc4213b6540, 0xff02f8, 0xc4213b6540)
        /home/ncw/go/src/github.com/ncw/rclone/cache/storage_persistent.go:204 +0x2d5
github.com/ncw/rclone/vendor/github.com/coreos/bbolt.(*DB).View(0xc4200c83c0, 0xc420545420, 0x0, 0x0)
        /home/ncw/go/src/github.com/ncw/rclone/vendor/github.com/coreos/bbolt/db.go:680 +0x9a
github.com/ncw/rclone/cache.(*Persistent).GetDirEntries(0xc42052a190, 0xc4201a6ee0, 0x0, 0xc4201a6ee0, 0x8, 0x10, 0xc42031a930)
        /home/ncw/go/src/github.com/ncw/rclone/cache/storage_persistent.go:182 +0x7d
github.com/ncw/rclone/cache.(*Fs).List(0xc42011b520, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/ncw/go/src/github.com/ncw/rclone/cache/cache.go:461 +0xb3
github.com/ncw/rclone/crypt.(*Fs).List(0xc42052a820, 0x0, 0x0, 0x0, 0x20, 0xc42046d720, 0x45b236, 0x30c1)
        /home/ncw/go/src/github.com/ncw/rclone/crypt/crypt.go:236 +0x76
github.com/ncw/rclone/fs.ListDirSorted(0x158bae0, 0xc42052a820, 0x15eac00, 0x0, 0x0, 0x2b7b75a, 0xed03ebeb1, 0x15eac80, 0x805, 0x220de2)
        /home/ncw/go/src/github.com/ncw/rclone/fs/operations.go:629 +0x63
github.com/ncw/rclone/vfs.(*Dir)._readDir(0xc4201303f0, 0xff1700, 0xc420130450)
        /home/ncw/go/src/github.com/ncw/rclone/vfs/dir.go:182 +0x112
github.com/ncw/rclone/vfs.(*Dir).ReadDirAll(0xc4201303f0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/ncw/go/src/github.com/ncw/rclone/vfs/dir.go:301 +0xc2
github.com/ncw/rclone/cmd/mount.(*Dir).ReadDirAll(0xc420198148, 0x1587060, 0xc42042e140, 0x0, 0x0, 0x0, 0xed16570fd, 0x15eac80)
        /home/ncw/go/src/github.com/ncw/rclone/cmd/mount/dir.go:91 +0x1c4
github.com/ncw/rclone/vendor/bazil.org/fuse/fs.(*Server).handleRequest(0xc4201d46c0, 0x1587060, 0xc42042e140, 0x157b820, 0xc420198148, 0xc420053a80, 0x15853a0, 0xc4201ee000, 0xc4202fdef8, 0x0, ...)
        /home/ncw/go/src/github.com/ncw/rclone/vendor/bazil.org/fuse/fs/serve.go:1209 +0x3fe
github.com/ncw/rclone/vendor/bazil.org/fuse/fs.(*Server).serve(0xc4201d46c0, 0x15853a0, 0xc4201ee000)
        /home/ncw/go/src/github.com/ncw/rclone/vendor/bazil.org/fuse/fs/serve.go:878 +0x468
github.com/ncw/rclone/vendor/bazil.org/fuse/fs.(*Server).Serve.func1(0xc4201d46c0, 0x15853a0, 0xc4201ee000)
        /home/ncw/go/src/github.com/ncw/rclone/vendor/bazil.org/fuse/fs/serve.go:425 +0x6e
created by github.com/ncw/rclone/vendor/bazil.org/fuse/fs.(*Server).Serve
        /home/ncw/go/src/github.com/ncw/rclone/vendor/bazil.org/fuse/fs/serve.go:423 +0x35f

```

My config:
```
[GDrive]
type = drive
client_id = 
client_secret = 
token = {"access_token":"*****","token_type":"Bearer","refresh_token":"*****","expiry":"****"}

[GDrive-Enc]
type = crypt
remote = GDrive-Cache:/Folder
filename_encryption = standard
password = ****
password2 = ****

[GDrive-Cache]
type = cache
remote = GDrive:/
plex_url = http://127.0.0.1:32400
plex_username = ****
plex_password = ****
chunk_size = 10M
info_age = 1h
chunk_total_size = 10G
plex_token = ****
```

This config works fine when using regular commands. However, the error pops up after I run the mount command **and then attempt to list the directory of the mountpoint**
