### ISSUE TITLE
google cloud storage - manipulation beyond root path fails

### ISSUE THREAD

**Issue by briceburg** [ncw/rclone#19]
Manipulation commands that modify files/directories underneath a bucket fail silently using google cloud storage. Root path commands (such as bucket creation) do work. E.g. 

* `rclone mkdir google:my-bucket/test-dir`  will NOT create test-dir under my-bucket. 
* `rclone mkdir google:my-other-bucket` will create a bucket named _my_other_bucket_

The inability to manipulate files under buckets also breaks `sync` commands -- they appear to do nothing.

details
---------

rclone version 1.07  ,  precompiled amd64 binary from downloads.rclone.org

I've setup a google cloud storage remote named _google_ via `rclone config`  :

```
[google]
type=google cloud storage
client_id=__HIDDEN__
client_secret=__HIDDEN__
project_number=__HIDDEN__
object_acl=
bucket_acl=
token={"AccessToken":"__HIDDEN__","RefreshToken":"__HIDDEN__","Expiry":"2015-01-19T02:43:39.634659884-05:00","Extra":null}
```

I left the ACL fields empty, although previously had set them to projectPrivate

```

## list contents of iceburg-vault
#########################

[nesta@hartford ~]$ rclone --verbose=true ls google:iceburg-vault
2015/01/19 02:03:09 Storage bucket iceburg-vault: Modify window is 1ns
        0 manually-created-folder/

Transferred:            0 Bytes (   0.00 kByte/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:  5.395056198s

2015/01/19 02:03:14 *** Go routines at exit 9


## create a directory under iceburg-vault
#################################

[nesta@hartford ~]$ rclone --verbose=true mkdir google:iceburg-vault/test
2015/01/19 02:03:52 Storage bucket iceburg-vault path test/: Modify window is 1ns

Transferred:            0 Bytes (   0.00 kByte/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:  5.513743952s

2015/01/19 02:03:52 *** Go routines at exit 9


## list contents of iceburg-vault
#########################
# NOTE: it doesn't list "test", only the previously manually-created-folder...

[nesta@hartford ~]$ rclone --verbose=true ls google:iceburg-vault
2015/01/19 02:04:12 Storage bucket iceburg-vault: Modify window is 1ns
        0 manually-created-folder/

Transferred:            0 Bytes (   0.00 kByte/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:  5.394211563s

2015/01/19 02:04:17 *** Go routines at exit 9

**Comment by ncw** [comment]
I think this probably isn't a bug.  Google cloud storage doesn't actually store directories at all, so your first command

    rclone --verbose=true mkdir google:iceburg-vault/test

Will ensure that the container `iceburg-vault` is created, but it won't create a directory in GCS because there are no such things!

That explains why

    rclone --verbose=true ls google:iceburg-vault

doesn't show anything.

If you copy a file into test you will see something, eg

    $ rclone copy z gcs:floop/test
    $ rclone ls gcs:floop/test
       754576 z
    $ rclone ls gcs:floop
       754576 test/z
    $ rclone lsd gcs:floop
               0 0001-01-01 00:00:00         0 test

Hopefully that makes sense.

You say also "The inability to manipulate files under buckets also breaks sync commands -- they appear to do nothing" - can you provide an example?

As far as I can see syncing to google cloud storage is working fine

    $ mkdir testdir
    $ cd testdir
    $ echo 1 > one
    $ echo 2 > two
    $ ls -l
    total 8
    -rw-rw-r-- 1 ncw ncw 2 Jan 19 16:44 one
    -rw-rw-r-- 1 ncw ncw 2 Jan 19 16:44 two
    $ cd ..
    $ rclone sync testdir gcs:floop/test
    2015/01/19 16:45:32 Storage bucket floop path test/: Building file list
    2015/01/19 16:45:32 Storage bucket floop path test/: Waiting for checks to finish
    2015/01/19 16:45:32 Storage bucket floop path test/: Waiting for transfers to finish
    2015/01/19 16:45:33 Waiting for deletions to finish
    
    Transferred:            4 Bytes (   0.00 kByte/s)
    Errors:                 0
    Checks:                 0
    Transferred:            2
    Elapsed time:  2.444223806s
    
    $ rclone sync gcs:floop/test testdir-recovered
    2015/01/19 16:45:48 Local file system at testdir-recovered: Building file list
    2015/01/19 16:45:48 Local file system at testdir-recovered: Waiting for checks to finish
    2015/01/19 16:45:49 Local file system at testdir-recovered: Waiting for transfers to finish
    2015/01/19 16:45:49 Waiting for deletions to finish
    
    Transferred:            4 Bytes (   0.00 kByte/s)
    Errors:                 0
    Checks:                 0
    Transferred:            2
    Elapsed time:  1.172942466s
    
    $ ls -l testdir testdir-recovered/
    testdir:
    total 8
    -rw-rw-r-- 1 ncw ncw 2 Jan 19 16:44 one
    -rw-rw-r-- 1 ncw ncw 2 Jan 19 16:44 two
    
    testdir-recovered/:
    total 8
    -rw-rw-r-- 1 ncw ncw 2 Jan 19 16:44 one
    -rw-rw-r-- 1 ncw ncw 2 Jan 19 16:44 two
    
    $ rclone lsl gcs:floop/test
            2 2015-01-19 16:44:55.596390773 one
            2 2015-01-19 16:44:58.724390892 two
    
    Transferred:            0 Bytes (   0.00 kByte/s)
    Errors:                 0
    Checks:                 2
    Transferred:            0
    Elapsed time:  738.599123ms

**Comment by briceburg** [comment]
Nick,

this was user error. I assumed that sync works as the `cp` command, where it will create the file/folder "as named" at the destination. E.g. 

`rclone sync /myFolder google:myBucket`

would create  directory named "myFolder" in myBucket, and sync it with the contents of  /myFolder. 

I now realize you must call it as:

`rclone sync /myFolder google:myBucket/myFolder`

Thanks!

**Comment by ncw** [comment]
No problem!

I've considered making the command line semantics like rsync which does one thing or another depending on a trailing slash, but I decided to keep it simple.  Thanks for the heads up - I'll try to make the docs clearer.
