### ISSUE TITLE
Plex needs rclone up first, rclone needs Plex up first

### ISSUE THREAD

**Issue by zenjabba** [ncw/rclone#1903]
https://www.youtube.com/watch?v=kTcRRaXV-fg

2017/12/10 22:09:43 Failed to create file system for "googlePWH_cache:": failed to connect to the Plex API https://plex.xyz.com/: failed to obtain token: map[error:You appear to be having trouble signing in to an account. You may wish to try resetting your password at https://plex.tv/reset]

This is a small mixup, but rclone is systemd process that needs to come up first THEN after all the network mounts are active, we bring up Plex. Now, with you doing a check to plex before bringing up rclone, we are in a statemate. 

rclone v1.38-223-g7c972d37β
- os/arch: linux/amd64
- go version: go1.9.2

**Comment by ajkis** [comment]
My current setup is starting rclone.service systemd  after 
[Unit]
Description=rclone mount 
After=network-online.target

and I changed /lib/systemd/system/plexmediaserver.service to start
[Unit]
Description=Plex Media Server for Linux
After=rclone.service 

So basically rclone service will wait until network is online and plex will wait until rclone is up.

**Comment by remusb** [comment]
I can add a way to connect to Plex after it started it too, it shouldn't be a problem.
Until then, my opinion, there's no reason for Plex to not be able to start up without rclone. It won't see the files there, true but it doesn't do anything if they're not no?

**Comment by zenjabba** [comment]
Except when it’s running in a docker. If the mount isn’t there when the docker starts the plex docker, the files are never visible to the docker instance and needs to be shutdown and restarted.

**Comment by zenjabba** [comment]
@ajkis that process doesn't work when running Plex within a docker.

**Comment by remusb** [comment]
Ah, I see. I have another issue with docker to track so I have more reasons to test that scenario now.
Thanks for the report, I'll take a look at it.

**Comment by remusb** [comment]
@zenjabba https://beta.rclone.org/v1.38-225-g84701e37/ beta with the delayed connection to Plex. It will be done when the first read happens.

**Comment by zenjabba** [comment]
fixed
