### ISSUE TITLE
b2-hard-delete 400 file_not_present

### ISSUE THREAD

**Issue by atomi** [ncw/rclone#1905]
When filing an issue, please include the following information if possible as well as a description of the problem.  Make sure you test with the latest beta of rclone.

    https://beta.rclone.org/
    https://rclone.org/downloads/

If you've just got a question or aren't sure if you've found a bug then please use the [rclone forum](https://forum.rclone.org/) instead of filing an issue.

> What is your rclone version (eg output from `rclone -V`)

rclone v1.38-224-g829dd1ad

> Which OS you are using and how many bits (eg Windows 7, 64 bit)

Linux alarmpi 4.9.60-1-ARCH #1 SMP Sat Nov 4 02:45:06 UTC 2017 armv7l GNU/Linux

> Which cloud storage system are you using? (eg Google Drive)

B2 Backblaze 

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone sync -v --b2-hard-delete --checksum /home/atomi/snapshots b2:atomi/snapshots

> A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

example log

rclone[23373]: 2017/12/10 20:08:49 ERROR : snapshots/aff0b718fb9fa0f6387def95c50e5b544caf5a2009939ab451b1d4bbc1cd6791: Couldn't delete: failed to delete "snapshots/aff0b718fb9fa0f6387def95c50e5b544caf5a2009939ab451b1d4bbc1cd6791": File not present: snapshots/aff0b718fb9fa0f6387def95c50e5b544caf5a2009939ab451b1d4bbc1cd6791 4_z9ceb62c61c604b3d6a080c10_f11003750eb26cca6_d20171211_m040416_c001_v0001097_t0057 (400 file_not_present)

**Comment by ncw** [comment]
Does it do that every time?

Can you replicate it on a small part of the sync?

Can you attach a log with `-vv --dump responses` of the problem happening please? You'll need to remove `authorizationToken` from the first response.  If worried about posting publically, then email to me at nick@craig-wood.com please with subject line "issue 1905" - thanks!

**Comment by atomi** [comment]
> Does it do that every time?

Yes!

Can you replicate it on a small part of the sync?

https://gist.github.com/atomi/da795943c78e08837f4c021af7bfce5a

**Comment by ncw** [comment]
Thanks for sending that.  It looks like that there are some files rclone needs to delete.  b2 sends them in the listing, rclone sees that they don't exist in the source and tries to delete them but fails with that error.

eg

```
    {
      "action": "upload",
      "contentLength": 301440,
      "contentSha1": "c021f22cc8e7eccb995d7e2483cb0689ce91547a",
      "contentType": "application/octet-stream",
      "fileId": "4_z9ceb62c61c604b3d6a080c10_f1033bc5ec2411c76_d20171211_m161252_c001_v0001043_t0032",
      "fileInfo": {
        "src_last_modified_millis": "1513008745064"
      },
      "fileName": "snapshots/restic/data/cc/ccc429a08ab1bdb91eed3cdb6ea0d8d05e1d1df0f42a7df0c4e4d1d6272dde4b",
      "size": 301440,
      "uploadTimestamp": 1513008772000
    }
```

and

```
{
  "code": "file_not_present",
  "message": "File not present: data/cc/ccc429a08ab1bdb91eed3cdb6ea0d8d05e1d1df0f42a7df0c4e4d1d6272dde4b 4_z9ceb62c61c604b3d6a080c10_f1033bc5ec2411c76_d20171211_m161252_c001_v0001043_t0032",
  "status": 400
}
```

Unfortunately I don't see what rclone is sending with that dump, so if you could first make run the sync to make sure it transfers any files, then run it again with `-vv --dump bodies --retries 1` this will log all the traffic.  Since the sync is clean there won't be any of your file data in the dump.  Adding `--retries 1` will mean it doesn't retry.

Could you also try downloading one of those files rclone can't delete using rclone and the web interface?

Also can you try deleting one of those files using the web interface and see if it gives the same error?

So either rclone is sending something strange to b2, or b2 has reported files that can't be deleted - we'll find out shortly!

**Comment by ncw** [comment]
I just noticed that in the response the file name is wrong, so likely rclone is sending b2 the wrong file name.  I didn't think that mattered since rclone supplies the ID, but maybe it does...

Hold on sending me stuff, I'm just going to try something...

**Comment by atomi** [comment]
Yeah fwiw, downloading and deleting the file works fine in the B2 web interface although it translates forward slashes as `%2F` which I assume is normal i.e `snapshots%2Frestic%2Fsnapshots%2Fa8d3a4942453c449165066b138f3a6966602a0dee0f3f1175710c3641bf6e7ed` as the file name. 


I think that perhaps, adding a nested directory to the bucket could be the cause i.e `b2:alarmpi/snapshots/restic`  but the "filename" in the logs for hard deletes is missing `/snapshots/restic/` so maybe it's attempting a relative location without the prefix.

**Comment by ncw** [comment]
Hmm, in my testing b2 seems to be ignoring the file name when deleting by id.

Can you try this https://pub.rclone.org/v1.38-222-gff5cb663-issue-1905%CE%B2/ (uploaded in 15 mins or so) which has a fix to make rclone always send the correct file name and see if it makes any difference?

> Yeah fwiw, downloading and deleting the file works fine in the B2 web interface although it translates forward slashes as %2F which I assume is normal i.e snapshots%2Frestic%2Fsnapshots%2Fa8d3a4942453c449165066b138f3a6966602a0dee0f3f1175710c3641bf6e7ed as the file name.

Thanks for trying that and yes the / transation is normal

> I think that perhaps adding a nested directory to the bucket could be the cause i.e b2:foote22/snapshots/restic but the "filename" in the logs for hard deletes is missing /snapshots/restic/ so maybe it's attempting a relative location without the prefix.

That is my theory too, but we'll see!

**Comment by ncw** [comment]
Thanks for testing. I've merged that to master now - it will be in [the latest beta](https://beta.rclone.org) from now on, the first of which is

https://beta.rclone.org/v1.38-226-g66558213/ (uploaded in 15-30 mins)

**Comment by atomi** [comment]
Thanks again for all the solid code you've written! I really do appreciate it.
