### ISSUE TITLE
add SIGHUP support (flush cache) to CACHE remote

### ISSUE THREAD

**Issue by seuffert** [ncw/rclone#1906]
please add support for the SIGHUP signal to the new CACHE remote to manually flush the directory cache.

(see https://github.com/ncw/rclone/pull/1376)

**Comment by remusb** [comment]
Hi @seuffert 

This beta has SIGHUP support to clear all the cache when it catches that.
https://beta.rclone.org/v1.38-240-g8839e4ee/

Just send the signal and a log should appear in rclone: `TestCache:: Clearing cache from signal` if you're running with `-v`

Thanks

**Comment by seuffert** [comment]
thx @remusb , i will gladly test it and have a look at the code too :)
