### ISSUE TITLE
Drive lsl mangled return

### ISSUE THREAD

**Issue by JohanElsMindset** [ncw/rclone#1908]
rclone v1.38-224-g829dd1adβ
- os/arch: darwin/amd64 High Sierra 10.13.2
- go version: go1.9.2
- Google Drive Education Apps Account

./rclone -vv --config ./rclone.conf lsl gdrivemindsetteamem:users/201411/0165a74f-3f3d-4759-a2a1-8b1551b66454/LXERG1106.11.2014FS.mov/
2017/12/11 16:48:14 DEBUG : Using config file from "/Users/johanels/Development/mindset-media-manager/storage/app/rclone/rclone.conf"
2017/12/11 16:48:14 DEBUG : rclone: Version "v1.38-224-g829dd1adβ" starting with parameters ["./rclone" "-vv" "--config" "./rclone.conf" "lsl" "gdrivemindsetteamem:users/201411/0165a74f-3f3d-4759-a2a1-8b1551b66454/LXERG1106.11.2014FS.mov/"]
2017/12/11 16:48:15 INFO  : Google drive root 'users/201411/0165a74f-3f3d-4759-a2a1-8b1551b66454/LXERG1106.11.2014FS.mov': Modify window is 1ms
**/LXERG1106.11.2014FS.mov9:16:21.611000000 LXERG1106.11.2014FS.mov**
2017/12/11 16:48:16 DEBUG : Go routines at exit 4
2017/12/11 16:48:16 DEBUG : rclone: Version "v1.38-224-g829dd1adβ" finishing with parameters ["./rclone" "-vv" "--config" "./rclone.conf" "lsl" "gdrivemindsetteamem:users/201411/0165a74f-3f3d-4759-a2a1-8b1551b66454/LXERG1106.11.2014FS.mov/"]

The returned "/LXERG1106.11.2014FS.mov9:16:21.611000000 LXERG1106.11.2014FS.mov" is mangled and is happening on some files in the directory structure.

Most files return correct information.

I get the same with version 1.38

Please let me know how I can assist further.

Thank you

**Comment by JohanElsMindset** [comment]
I am getting exactly the same issue using the ls command:

clone --config storage/app/rclone/rclone.conf lsl gdrivemindsetteamem:users/201411/

   383227 2015-11-11 19:16:54.554000000 0c8872eb-e1bc-4ffd-95cf-04f188cd99c7/Topic Description_DAMS.jpg
   529076 2015-11-11 19:16:54.540000000 0b07e267-3903-48b1-8b80-ec8364285578/LXER_Gr12Economics_Final Exam Preparation P1 (Live)_03Nov2014.pdf
   699624 2015-11-11 19:16:21.619000000 01c118b6-7584-40af-ae0d-c33ca61a2fe7/LXER_Gr12Economics_Preparing for Paper 1_09Oct2014.pdf
   670947 2015-11-11 19:19:10.371000000 0d05967a-8b32-4b76-8cb9-50a536dec591/LXER_Gr12History_The Origins of the Cold War_04Nov2014.pdf
   823638 2015-11-11 19:19:16.758000000 0ebc7e7b-3a0f-43da-8391-3946b29c1b7e/LXER_Gr11LifeSciences_Paper 2 Exam Questions (Live)_05Nov2014.pdf
1014464424 2015-11-11 19:29:51.351000000 1b699a3b-72bc-4e9c-a568-d72223ed9330/E00201208.mov
   614788 2015-11-11 19:30:19.791000000 1c3b2037-75ea-4733-bb1f-adeafd1411f7/LXER_Gr12BusinessStudies_CAPS Exam Questions II_Nov2014.pdf
3331438420 2015-11-11 19:30:19.786000000 1ba31d3c-1565-47d0-9fd4-f3a7f122a38b/LESSON 3 - Simple Calculations and Fomulae 1.mov
9473986176 2015-11-11 19:32:08.997000000 1e18df70-58a1-4752-8bbc-ba3f6eb0b43b/LXER12ECON52014FS.mov
   979734 2015-11-11 19:32:09.014000000 20491fa7-2333-4211-92d8-34c0b601cd47/LXER_Gr12Geography_Final Exam Preparation P1 (Live)_29Oct2014.pdf
**/UKU40.mov 2015-11-11 19:16:48.130000000 081a90f6-2c27-4536-bc00-388e35bc8b1b/UKU40.mov/UKU40.mov**
**/E00200027.mov-11-11 19:16:38.972000000 06d19ab1-760a-4808-a935-2b3241578df7/E00200027.mov/E00200027.mov**
**/LXERG1106.11.2014FS.mov9:16:21.611000000 0165a74f-3f3d-4759-a2a1-8b1551b66454/LXERG1106.11.2014FS.mov/LXERG1106.11.2014FS.mov**
410811018 2015-11-11 19:32:12.546000000 206bff2f-0c2a-467e-adbe-2879fe8df617/UKU34.mov

Thank you,

**Comment by ncw** [comment]
Can you run this (or something like it)

    ./rclone --config storage/app/rclone/rclone.conf lsl gdrivemindsetteamem:users/201411/ -vv --dump-bodies 2>rclone.log >rclone.output

And post the two files please?  I suggest you zip them up together and attach them.

That should show exactly what google is sending rclone and will help pinpoint the problem.

Thanks

**Comment by JohanElsMindset** [comment]
Hi,

Well that seems to highlight the issue.

Seems the filename returned from Google ends on "^M"

I attach the two files.

Thank you,
[rclone.zip](https://github.com/ncw/rclone/files/1548704/rclone.zip)

**Comment by ncw** [comment]
Thanks for doing that.  Yes it looks like you are right.

It is very likely that is what it is actually called - google drive file names can have control characters.  Try renaming it in the drive interface?

How did it get uploaded?

**Comment by JohanElsMindset** [comment]
Rename in Gdrive interface did not resolve.

Files were uploaded using rclone from a Linux server.

Original on the Linux server has no escape characters in the filename.

**Comment by JohanElsMindset** [comment]
Okay, I think I need to check a couple of things this side.

The JSON response for that folder:

{"Path":"LXERG1106.11.2014FS.mov\r","Name":"LXERG1106.11.2014FS.mov\r","Size":-1,"ModTime":"2017-08-17T12:49:40.711Z","IsDir":true},
{"Path":"LXERG1106.11.2014FS.mov\r/LXERG1106.11.2014FS.mov","Name":"LXERG1106.11.2014FS.mov","Size":12441612504,"ModTime":"2015-11-11T18:16:21.611Z","IsDir":false}
]

Shows it is the folder with a line feed.

**Comment by JohanElsMindset** [comment]
I think you can close this issue, I will rewrite my code to use the JSON results and not ls.

Thank you for the help.

**Comment by ncw** [comment]
OK and no worries!
