### ISSUE TITLE
Error copying swift to Amazon Cloud Drive

### ISSUE THREAD

**Issue by xgiovio** [ncw/rclone#191]
Hello, correctly configured swift and acd. remotes name are : hubic and amazon
if i launche the following command:
rclone copy "hubic:mycontainer" "amazon:myfolder"

it shows me errors and for examples hubic's folders are being created as files on amazon side.

Bugs?
On my testing rclone is bugged like hell!

**Comment by ncw** [comment]
This has the same cause as #172 and #190 so I'm going to close as it is a duplicate.
