### ISSUE TITLE
ncdu command causes runtime error: slice out of range

### ISSUE THREAD

**Issue by PaddyTheShamrock** [ncw/rclone#1910]
I've found a crash issue with the ncdu command.

If I run it on my google drive, it loads the screen and starts doing a background list. If I move to an empty directory and then press the up arrow, rclone crashes with the below error.

I have a debug log as well, but it doesn't show anything more than the usual Google drive rate limiting etc.

> What is your rclone version (eg output from `rclone -V`)
**1.38 and tested with latest beta**

> Which OS you are using and how many bits (eg Windows 7, 64 bit)
**Ubuntu x86_64**

> Which cloud storage system are you using? (eg Google Drive)
**Google Drive**

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
**rclone ncdu GD:/**

> A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

```
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
github.com/ncw/rclone/cmd/ncdu.(*UI).Draw(0xc4200f0000, 0xffffffffffffffff, 0xc420541a08)
	/home/travis/gopath/src/github.com/ncw/rclone/cmd/ncdu/ncdu.go:204 +0xbdd
github.com/ncw/rclone/cmd/ncdu.(*UI).Show(0xc4200f0000, 0x0, 0x0)
	/home/travis/gopath/src/github.com/ncw/rclone/cmd/ncdu/ncdu.go:488 +0x185
github.com/ncw/rclone/cmd/ncdu.glob..func1.1(0x0, 0x4)
	/home/travis/gopath/src/github.com/ncw/rclone/cmd/ncdu/ncdu.go:51 +0x41
github.com/ncw/rclone/cmd.Run(0xc420130000, 0x15e4800, 0xc420541d08)
	/home/travis/gopath/src/github.com/ncw/rclone/cmd/cmd.go:265 +0xa7
github.com/ncw/rclone/cmd/ncdu.glob..func1(0x15e4800, 0xc420131dc0, 0x1, 0x1)
	/home/travis/gopath/src/github.com/ncw/rclone/cmd/ncdu/ncdu.go:50 +0xc9
github.com/ncw/rclone/vendor/github.com/spf13/cobra.(*Command).execute(0x15e4800, 0xc420131d70, 0x1, 0x1, 0x15e4800, 0xc420131d70)
	/home/travis/gopath/src/github.com/ncw/rclone/vendor/github.com/spf13/cobra/command.go:654 +0x2a2
github.com/ncw/rclone/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x15df040, 0xc4201e5f70, 0x4046a4, 0xc4200140b8)
	/home/travis/gopath/src/github.com/ncw/rclone/vendor/github.com/spf13/cobra/command.go:729 +0x2fe
github.com/ncw/rclone/vendor/github.com/spf13/cobra.(*Command).Execute(0x15df040, 0xc4201c5de0, 0x20)
	/home/travis/gopath/src/github.com/ncw/rclone/vendor/github.com/spf13/cobra/command.go:688 +0x2b
main.main()
	/home/travis/gopath/src/github.com/ncw/rclone/rclone.go:15 +0x31
```

**Comment by ncw** [comment]
I managed to replicate this thanks!

Will fix in a moment...

**Comment by ncw** [comment]
I've fixed this now - please find the fix here

https://beta.rclone.org/v1.38-227-g2cf808c8/ (uploaded in 15-30 mins)

Thanks for reporting

**Comment by PaddyTheShamrock** [comment]
Thanks for the fix. (and the awesome program!)
