### ISSUE TITLE
Disable cache age cleanup

### ISSUE THREAD

**Issue by cal2195** [ncw/rclone#1915]
Is there a way to disable the cache object age clean up, so that the cache will only delete local files if more space is needed?

The files on my remote never change, so expiring them locally except to make room for more files doesn't make sense!

Maybe being able to pass 0 or -1 to the cache age param? :)

> What is your rclone version (eg output from `rclone -V`)

rclone v1.38-226-g66558213β
os/arch: linux/amd64
go version: go1.9.2

> Which OS you are using and how many bits (eg Windows 7, 64 bit)

Arch Linux 64bit

> Which cloud storage system are you using? (eg Google Drive)

Google Drive

**Comment by easy90rider** [comment]
Not really relevant since https://github.com/ncw/rclone/issues/1830

**Comment by cal2195** [comment]
So does cache-age not exist now, or how to I make it only expire based on size? :)

**Comment by easy90rider** [comment]
Install latest beta and reconfigure rclone cache! 

you will end up with something like: 

```
--------------------
[cache]
type = cache
remote = remoteLocation:/
chunk_size = 5M
info_age = 24h
chunk_age = 1m
warmup_age = 3h
chunk_total_size = 5G
--------------------
```

**Comment by cal2195** [comment]
Ah, so chunk age is just the metadata now, not the actual data? :)

**Comment by easy90rider** [comment]
No, it's the age of a chunk, so how long it is kept in cache, but it is mostly ignored. @remusb might give you a better explanation.

But I saw chunks being removed only after I had more than the set 5GB of chunks.

**Comment by remusb** [comment]
chunk_age doesn't exist anymore sadly. It's going to be ignored. A future version will try to combine both.

All the other comments are correct until then so you should be good to configure chunk_total_size and it will work.

Thanks
