### ISSUE TITLE
cache - object not found

### ISSUE THREAD

**Issue by uffcd** [ncw/rclone#1917]
I have a problem that some files cannot be seen with cache:

`2017/12/14 13:47:00 ERROR : In Extremo/Sünder ohne Zügel/11 - In Extremo - Óskasteinar.mp3: error refreshing object: object not found`

Rest of the files in the directory are fine and the same file is ok without cache.
All files with problems have UTF-8 characters in the filename ...

**Comment by zenjabba** [comment]
I would paste it in this https://github.com/ncw/rclone/issues/1904 and close this one

**Comment by ncw** [comment]
@uffcd can you head over to #1904 please as this is a duplicate - thanks!
