### ISSUE TITLE
Cache Questions - Docs

### ISSUE THREAD

**Issue by cal2195** [ncw/rclone#1918]
Hey! :)

I know it's still in beta, but I'm just trying to figure out the best caching method between `--vfs-cache` and the cache backend.

Do the `--vfs-cache-mode` flags apply to the cache backend in regards to r/w and upload retries?

Also, how would using a torrent client directly on a mount work with the cache backend? Would the client need to be closed first to release the file?

Thanks :)

**Comment by ncw** [comment]
> Do the --vfs-cache-mode flags apply to the cache backend in regards to r/w and upload retries?

The vfs-cache modes apply to the rclone mount, not to the cache backend.  They are mostly about making the mount a more compatible file system but they may be sufficient caching for some purposes (eg serving beta.rclone.org which I what I'm using it for).

> Also, how would using a torrent client directly on a mount work with the cache backend? Would the client need to be closed first to release the file?

You would need to use `--vfs-cache-mode writes` or `full`.  When the torrent client closes the file, it will be uploaded.  I don't know whether you need to close the client or not to get it to close the file.

**Comment by ncw** [comment]
I'm going to add a bit to the cache docs about this.

**Comment by ncw** [comment]
I've explained the backend cache vs the vfs cache and the differences in the vfs cache modes in detail in the docs now so I'm going to close this.
