### ISSUE TITLE
Bandwidth Consumption vs Actual Data (Amazon Cloud)

### ISSUE THREAD

**Issue by TiGWolf** [ncw/rclone#192]
I have noticed an interesting trend with using rclone to transfer data to Amazon Cloud Drive. I am in the process of uploading approximately 400GB (190,000 files), but during this process the amount of data consumed during transfer vs actual data is approximately a factor of 10. For instance, early this morning (0200 to 0600) I transferred 16GB worth of files using a 100Mbit connection. Taking in account for overhead I would expect it to take less than an hour, but reality it took 4 hours completely saturating the network connection. Doing some simple math (45GB/hr for 100Mbit connection) it had pushed 180GB of data towards Amazon.

![graph_image](https://cloud.githubusercontent.com/assets/15611062/10881963/10846040-8135-11e5-84aa-743214097b6c.png)

**Comment by klauspost** [comment]
Interesting. I have not experienced that behavior.

What speed is the built-in stats showing? 
Are there any errors?
What does you commandline look like?

**Comment by ncw** [comment]
Here is a quick test I did

```
$ dd if=/dev/zero of=/tmp/1gb bs=1M count=1k
1024+0 records in
1024+0 records out
1073741824 bytes (1.1 GB) copied, 2.71206 s, 396 MB/s
$ ifconfig eth0
eth0      [snip]
          RX bytes:560186803 (560.1 MB)  TX bytes:226423925 (226.4 MB)

$ rclone --stats=10s -v copy 1gb acd:test10
2015/11/02 13:55:08 acd: Saving new token in config file
[snip]
2015/11/02 13:55:47 1gb: Copied (new)

Transferred:   1073741824 Bytes (25917.80 kByte/s)
Errors:                 0
Checks:                 0
Transferred:            1
Elapsed time:       40.4s

$ ifconfig eth0
eth0      [snip]
          RX bytes:590700646 (590.7 MB)  TX bytes:1360582953 (1.3 GB)
```

So a 1 GB file transferred using 1.056 GB of data for me so only about 5% overhead. (I tried it with a random file with identical results).

Binaries are uploaded with encoding to ACD which has an overhead but it shouldn't be 10x!

Did the transfer have lots of retries is the only thing I can think of - a log with the `-v` flag will show that.

**Comment by TiGWolf** [comment]
Are there different verbosity levels? -v vs -vvvv ?

**Comment by ncw** [comment]
@TiGWolf just the `-v`, unless you want to `--dump-headers` which is really only useful for developers!

**Comment by TiGWolf** [comment]
Alright I did verbose with the header dump. (Log file unzipped is large 118M)

Command used: rclone -v --dump-headers -c --checkers=10 --transfers=8 --stats=10s copy /EncData/ Amazon:EncData

I crunched the numbers of files and data transferred to Amazon:
2318 Files
2.6GB

Bandwidth consumed to accomplish this: > 30GB (Outbound - Blue Line)

![graph_image](https://cloud.githubusercontent.com/assets/15611062/10893097/f8e980a6-8174-11e5-976b-d044cfdcf4cd.png)


Log file: https://www.dropbox.com/s/8sgmjgjebbbjpzb/putty2.zip?dl=0

**Comment by klauspost** [comment]
It *seems* like it has transferred 39.55GB when the log ends. 39545913184 Bytes = 39.55 GB  (gigabytes)

**Comment by TiGWolf** [comment]
Now that sounds correct on transferred data, however when I look at Amazon's usage status it shows a much different amount of data.

When I started it said 327.6GB and 128,213 files, and currently it says 330.2GB and 130,531 files.

Bizarre

**Comment by ncw** [comment]
I can see that there were 7 retries in that transfer

```
F/F6/F65/F657/F6575E34680B7694C5075981679F2716
F/F6/F65/F65D/F65D0FBC282BE1E0E5A92868F70A99AD
F/F6/F6B/F6B6/F6B66F27FE4A3237FCFA9C651B5028EE
F/F7/F74/F74A/F74A4C1E7F2E64529384510861CC86AE
F/F7/F79/F79B/F79B80D1DE8A0AB296ACE33A7E86D26E
F/F8/F8C/F8C0/F8C0664C035B79300FBA6D0E5FD6361F
F/F8/F8C/F8C2/F8C2AD921C6B750E5CAFC22600BB6C5A
```

What is the total size of those files? If they total to > 30Gb then that is the problem.

**Comment by ncw** [comment]
I think I see the problem. This file starts transferring near the beginning but doesn't finish`.../A90/A903/A9031270513D28BB0AFB9D71DA9E0AE9` by the end.  It is > 50GB I think.  So 30 Gb of it get transferred but then rclone is stopped and Amazon discards the partial upload.

So I think if you can transfer this file to the end, then your bandwidth excesses will disappear, or you could just do a run transferring very large files with `--min-size=10G` (or try a run skipping it using `--max-size=10G`)

```
 * .../A90/A903/A9031270513D28BB0AFB9D71DA9E0AE9:  0% done. avg: 6956.9, cur: 3297.4 kByte/s. ETA: 5h38m3s
 * .../A90/A903/A9031270513D28BB0AFB9D71DA9E0AE9:  0% done. avg: 6317.1, cur: 4470.8 kByte/s. ETA: 4h9m7s
 * .../A90/A903/A9031270513D28BB0AFB9D71DA9E0AE9:  0% done. avg: 6387.5, cur: 5513.3 kByte/s. ETA: 3h21m48s
 * .../A90/A903/A9031270513D28BB0AFB9D71DA9E0AE9:  0% done. avg: 6088.8, cur: 5292.9 kByte/s. ETA: 3h30m3s
 * .../A90/A903/A9031270513D28BB0AFB9D71DA9E0AE9:  0% done. avg: 6160.9, cur: 5685.7 kByte/s. ETA: 3h15m21s
[snip]
 * .../A90/A903/A9031270513D28BB0AFB9D71DA9E0AE9: 44% done. avg: 6842.9, cur: 10657.6 kByte/s. ETA: 58m28s
 * .../A90/A903/A9031270513D28BB0AFB9D71DA9E0AE9: 44% done. avg: 6851.5, cur: 10620.3 kByte/s. ETA: 58m30s
 * .../A90/A903/A9031270513D28BB0AFB9D71DA9E0AE9: 44% done. avg: 6860.1, cur: 10589.9 kByte/s. ETA: 58m30s
```

**Comment by ncw** [comment]
@TiGWolf suggest you delete that zip as Klaus and I have a copy now

**Comment by TiGWolf** [comment]
Thanks for your help, and I already did.

**Comment by ncw** [comment]
@TiGWolf are you happy that we've explained the problem - can I close the issue now?

Thanks

Nick
