### ISSUE TITLE
`cryptencode` a file name

### ISSUE THREAD

**Issue by Saviq** [ncw/rclone#1923]
> What is your rclone version (eg output from `rclone -V`)
1.38

> Which OS you are using and how many bits (eg Windows 7, 64 bit)
Linux 64-bit

> Which cloud storage system are you using? (eg Google Drive)
Google Drive

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone cryptencode remote: tmp

> A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
```
Error: unknown command "cryptencode" for "rclone"
```

You can `cryptdecode` a file name to find out what it is on the crypted remote, but there's no way to `cryptencode` a name, if you need to find it on the remote itself.

**Comment by ncw** [comment]
That seems like a sensible idea!

**Comment by ncw** [comment]
@ishuah fancy having a go at this since you did cryptdecode?  We should have thought of this!  It could possibly be a flag on cryptdecode to save the proliferation of commands...

**Comment by ishuah** [comment]
@ncw yes! A flag like `--reverse` will work perfectly for this.

**Comment by ishuah** [comment]
Please find a beta version with a fix here: https://beta.rclone.org/v1.39-023-g0a7731cf/ (Uploaded in 15-30 minutes)

**Comment by TimetravelerDD** [comment]
just wanted to say thank you! That feature saved my day :-)
