### ISSUE TITLE
Cache & Crypt Mount: Subfolders disappearing after several minutes

### ISSUE THREAD

**Issue by floriansofianos** [ncw/rclone#1929]
What is your rclone version (eg output from `rclone -V`)
v1.38-238-g6f1ae00c

Which OS you are using and how many bits (eg Windows 7, 64 bit)
Windows server 2016 64bit

Which cloud storage system are you using? (eg Google Drive)
Google Drive

The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone mount googleenc: X:

A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
When I first run mount, all the files are there and there is no problem.
If I wait about 5 minutes, the issue starts appearing: the sub-folders are all gone.
I also have an error in the logs:
Entry doesn't belong in directory "" (contains subdir) - ignoring
[rclone-log-3.txt](https://github.com/ncw/rclone/files/1569869/rclone-log-3.txt)
I have attached the full log.

Also my config:
[googleenc]
type = crypt
remote = cache:
filename_encryption = standard
password = XXX
password2 = XXX

[cache]
type = cache
remote = gdrive:/Plex-Encrypted/
plex_url = http://127.0.0.1:32400
plex_username = XXX
plex_password = XXX
chunk_size = 20M
info_age = 24h
chunk_total_size = 180G
plex_token = XXX

Thanks for your great work!

**Comment by jrarseneau** [comment]
You should close this and move it to #1904 .. it's the same issue.

Also, make sure you've deleted your cache before running the new beta (1.38-238)

**Comment by floriansofianos** [comment]
Thanks @jrarseneau I'll do that.
I have started from scratch so I did not have any cache when first running the new beta.
