### ISSUE TITLE
Login to OneDrive get some error log

### ISSUE THREAD

**Issue by Whuihuan** [ncw/rclone#1941]
> What is your rclone version (eg output from `rclone -V`)
rclone v1.39
> Which OS you are using and how many bits (eg Windows 7, 64 bit)
Windows10,64 bit
> Which cloud storage system are you using? (eg Google Drive)
One Drive

WEB page show "Success Go back to rclone to continue", but rclone show message is "2017/12/24 13:39:30 Failed to configure token: failed to get token: oauth2: cannot fetch token: 401 Unauthorized
Response: {"error":"invalid_client","error_description":"The provided value for the 'client_secret' parameter is not valid."}"
I'm sure my Microsoft client secret is no wrong. How to do?

**Comment by kladiv** [comment]
+1 same error
OneDrive (Personal) in unusable right now

**Comment by ncw** [comment]
@Whuihuan you need to leave the "client_secret" blank most likely.

@kladiv try remaking the remote?

**Comment by kladiv** [comment]
@ncw I encounter the issue when used my personal "client_id" and "client_secret".
After 3600 error returned

**Comment by ncw** [comment]
@kladiv check the config file to see if your personal client_id and client_secret are still in there?  There have been situations where rclone has overwritten them which I thought were all fixed, but maybe not...

**Comment by kladiv** [comment]
@ncw 
both parameters are still there. E.g.
```
[onedrive]
type = onedrive
client_id = 07******-****-****-****-**********35
client_secret = a******************58=@
token = {"access_token":"Ew*****DQ8C","token_type":"bearer","refresh_token":"MCW*****Dg$$","expiry": "2018-01-15T23:11:06+01:00"}
```
After expiration:

```
2018/01/15 23:14:06 DEBUG : Using config file from "/home/rclone/.rclone.conf"
2018/01/15 23:14:06 DEBUG : rclone: Version "v1.39" starting with parameters ["rclone" "-vvv" "--config" "/home/rclone/.rclone.conf" "sync" "/mnt/dir" "onedrive:/rclone"]
2018/01/15 23:14:06 Failed to create file system for "onedrive:/rclone": failed to get root: Get https://api.onedrive.com/v1.0/drive/root:/: oauth2: cannot fetch token: 401 Unauthorized
Response: {"error":"invalid_client","error_description":"The provided value for the 'client_secret' parameter is not valid."}
```

**Comment by ncw** [comment]
@kladic - I don't have much of a clue as to what is going on, but I'd start by investigating the error `The provided value for the 'client_secret' parameter is not valid.`  So are you 100% sure of your client_secret and client_id ?

**Comment by kladiv** [comment]
@ncw: yes!
@Whuihuan: i think you can explain that problem too.

I think something goes wrong using custom client_id and client_secret. Is it possible rclone uses it's hardcoded client_secret for OneDrive remote refresh?

**Comment by ncw** [comment]
> I think something goes wrong using custom client_id and client_secret. Is it possible rclone uses it's hardcoded client_secret for OneDrive remote refres

The same code works for google drive with custom client_id's.  There could be some provider difference I don't know about.  I'd try using `-vv --dump-bodies` to capture the http transactions and see if I could work out what is going on.  When using dump bodies, set up a transfer of lots of small text files and use `--bwlimit` to make them transfer very slowly.

**Comment by Cnly** [comment]
Closing because this is obsolete.
