### ISSUE TITLE
Cache backend: Commands cannot be stopped with Ctrl-C

### ISSUE THREAD

**Issue by yesbox** [ncw/rclone#1946]
## Version
rclone v1.39
os/arch: linux/amd64
go version: go1.9.2

## Issue
The rclone ls and copy command cannot be stopped normally (with Ctrl-C) when used with the Cache backend. This may be true for other commands as well, those were the only ones I tried.

```
$ rclone ls gdrive_cached:
... (normal ls output)
^C
2017/12/26 12:41:51 ERROR : subdir/file1: failed to cache object: database not open
2017/12/26 12:41:51 ERROR : subdir/file2: failed to cache object: database not open
2017/12/26 12:41:51 ERROR : subdir: list: save error: database not open
... (continues querying the gdrive backend and printing database errors without stopping)
```

**Comment by ncw** [comment]
This looks like a bug.  In the cache backend we catch SIGINT, then do nothing...  This should propagate the signal somehow...

```go
	// Trap SIGINT and SIGTERM to close the DB handle gracefully
	c := make(chan os.Signal, 1)
	signal.Notify(c, syscall.SIGINT, syscall.SIGTERM, syscall.SIGHUP)
	go func() {
		for {
			s := <-c
			if s == syscall.SIGINT || s == syscall.SIGTERM {
				fs.Debugf(f, "Got signal: %v", s)
				f.cache.Close()
			} else if s == syscall.SIGHUP {
				fs.Infof(f, "Clearing cache from signal")
				f.DirCacheFlush()
			}
		}
	}()
```

**Comment by remusb** [comment]
Hi @ncw 

Would cmd.AtExit solve this issue?

**Comment by ncw** [comment]
> Would cmd.AtExit solve this issue?

Yes I think that would be perfect. I'd completely forgotten about cmd.AtExit!

It is probably in the wrong place now though...

I'll push a commit to move it to `lib/atexit.Register` in a moment.

I'm tryiing to make sure that backends only call stuff in `lib` and `fs` to that other uses of the backends don't involve pulling in any of the `cmd` infrastructure.

**Comment by remusb** [comment]
Hi @yesbox 

This beta should have the fix for this: https://beta.rclone.org/v1.39-099-gb3d8b7e2/

@ncw thanks, I already put it to good use :)
