### ISSUE TITLE
SMB: Samba shares

### ISSUE THREAD

**Issue by xv1t** [ncw/rclone#1947]
Hi!

Do you have any plans about the use of r-cloning via SMB/Samba/Windows hosts?

Thanx for rclone!

**Comment by ncw** [comment]
I'm not sure what you are trying to achieve?

Can you be more specific please?

Thanks!

**Comment by xv1t** [comment]
For example, am used a `smbclient` for popupalting `tar` archives from linux to windows hosts.

I Have to use tar archives, instead of sync of the directory.

It would be cool directly, without additional tools to sync smb.

**Comment by WillGunn** [comment]
If the share is mounted on your local system, rclone should work with it no problem.

**Comment by xv1t** [comment]
Yes, but without `root` permission i can't use `mount` command for `cifs` or `smbfs` remotes

**Comment by ncw** [comment]
@xv1t  I see...

I don't really want to implement the smb protocol in rclone - it is very big!  However there are workarounds - eg [mounting an smb share as non root](https://askubuntu.com/questions/24348/how-do-i-mount-samba-share-as-non-root-user)

**Comment by xv1t** [comment]
OK, thanx
