### ISSUE TITLE
Install script fails on Synology systems due to lack of unzip command

### ISSUE THREAD

**Issue by Webreaper** [ncw/rclone#1949]
The new install script for rclone fails on a Synology OS because Synology doesn't have the unzip command by default. Instead, Synology provides the 7z command. 

So if we replace the existing unzip command:

`unzip -a $rclone_zip -d $unzip_dir 
`
with this:

```
if hash unzip 2>/dev/null; then
	unzip -a $rclone_zip -d $unzip_dir 
else
	7z x $rclone_zip -o$unzip_dir
fi

```
the script will work on Synology.

**Comment by ncw** [comment]
@qaskai what do you think about making the script look for 7z if unzip isn't available?

it would be quite nice if the script errored at the start if neither is available as unzip isn't a standard install for eg, debian.

**Comment by qaskai** [comment]
Yeah, that’s a good idea. Now I wonder how I could fail to consider this problem while making the script! I’ll make a PR ASAP.

Also apologies to @Webreaper for the slow response.

**Comment by Webreaper** [comment]
Don't fret, it's really no biggie. Having a script at all is great! Thanks!

**Comment by ncw** [comment]
I've pushed up a new script to rclone.org which should work for you now - thanks to @qaskai  for the changed :-)
