### ISSUE TITLE
Unable to list files using webdav

### ISSUE THREAD

**Issue by gavinmporter** [ncw/rclone#1952]
Hi

I am trying to setup a webdav sync using www.mydrive.ch but rclone is unable to obtain a directory listing, so cannot sync. Problem is reproducible.

```
$ rclone -V
rclone v1.39
- os/arch: linux/amd64
- go version: go1.9.2
```

```
$ rclone -vv ls mydrive:
2017/12/31 09:25:43 DEBUG : rclone: Version "v1.39" starting with parameters ["rclone" "-vv" "ls" "mydrive:"]
2017/12/31 09:25:43 INFO  : webdav root '': Modify window not supported
2017/12/31 09:25:44 ERROR : : error listing: couldn't list files: parsing time "Sat, 30 Dec 2017 06:03:46 +0000" as "Mon, 02 Jan 2006 15:04:05 MST": cannot parse "+0000" as "MST"
```
The timestamp "Sat, 30 Dec 2017 06:03:46 +0000" is the creation timestamp for the first file in the root directory.

Also tested on beta rclone-v1.39-001-gb412c745β-linux-amd64

Possible fix: switch time format from RFC1123 to RFC1123Z in webdav/api/types.go
According to https://go-review.googlesource.com/c/go/+/18314/3/src/time/format.go RFC1123Z should be used instead of RFC1123 for servers.

Gavin

**Comment by ncw** [comment]
I've fixed this here

https://beta.rclone.org/v1.39-002-gef89f1f1/ (uploaded in 15-30 mins)

I can't change the time format as that will break the other webdav providers (eg nextcloud) so I've added in an alternative parsing format for mydrive.

**Comment by gavinmporter** [comment]
Confirmed fix works in the beta. Thanks.

**Comment by ncw** [comment]
Thanks. Let me know if you have any more problems with my drive and I'll fix them!

**Comment by Jisay** [comment]
Got the same problem :
```
rclone ls media: -vv
2018/01/12 19:12:53 DEBUG : Using config file from "/home/osmc/.config/rclone/rclone.conf"
2018/01/12 19:12:53 DEBUG : rclone: Version "v1.39-002-gef89f1f1β" starting with parameters ["rclone" "ls" "media:" "-vv"]
2018/01/12 19:12:53 INFO  : webdav root '': Modify window is 1s
2018/01/12 19:12:54 ERROR : : error listing: couldn't list files: parsing time "" as "Mon, 02 Jan 2006 15:04:05 -0700": cannot parse "" as "Mon"
2018/01/12 19:12:54 Failed to ls: couldn't list files: parsing time "" as "Mon, 02 Jan 2006 15:04:05 -0700": cannot parse "" as "Mon"
osmc@H42MediaCenter:~$ rclone -V
rclone v1.39-002-gef89f1f1β
- os/arch: linux/arm
- go version: go1.9.2
```

I have downloaded the beta version as you can see. Thanks for helping !

**Comment by Jisay** [comment]
OK, I found the problem!

The url of my nextcloud was not the right one. Maybe you should change your doc and specify that the webdav url is the one provided in the nextcloud doc : `https://example.com/nextcloud/remote.php/dav/files/USERNAME/` and not `https://example.com/nextcloud/remote.php/dav/`.

Seems to work like a charm now :-D

**Comment by geerew** [comment]
I've hit this issue as well:

```
rclone ls -vv remote:
2018/01/16 10:22:56 DEBUG : Using config file from "/root/.config/rclone/rclone.conf"
2018/01/16 10:22:56 DEBUG : rclone: Version "v1.39-027-g11da2a6cβ" starting with parameters ["rclone" "ls" "-vv" "remote:"]
2018/01/16 10:22:56 INFO  : webdav root '': Modify window not supported
2018/01/16 10:22:56 ERROR : Backup: error listing: couldn't list files: parsing time "Wed May 17 15:31:58 UTC 2017" as "Mon, 02 Jan 2006 15:04:05 -0700": cannot parse " May 17 15:31:58 UTC 2017" as ", "
2018/01/16 10:22:56 Failed to ls: couldn't list files: parsing time "Wed May 17 15:31:58 UTC 2017" as "Mon, 02 Jan 2006 15:04:05 -0700": cannot parse " May 17 15:31:58 UTC 2017" as ", "

```

I am running the latest beta:
```
rclone -V
rclone v1.39-027-g11da2a6cβ
- os/arch: linux/amd64
- go version: go1.9.2
```

**Comment by ncw** [comment]
@geerew which provider are you using for webdav?

 "Wed May 17 15:31:58 UTC 2017" looks like UnixDate format which isn't a valid time format for webdav.

I can add a parser in for it though easily enough.

**Comment by geerew** [comment]
Hi @ncw,

Thanks for the reply.

This is a webdav hosted by the company I work for. They are reluctant (as most companys are) to change things. 

I tested with the following and it seems to be working

`timeFormatU = time.UnixDate `

Thanks

**Comment by ncw** [comment]
@geerew can you try this and see if it fixes the problem please?

https://pub.rclone.org/v1.39-029-g2dd1fef5-webdav-time%CE%B2/

(I thought I posted this already, but apparently not!)

**Comment by geerew** [comment]
That works, thanks @ncw

**Comment by ncw** [comment]
Great thanks.. I'll merge that now.  It will be in the next beta

https://beta.rclone.org/v1.39-038-g59a8108f/ (uploaded in 15-30 mins)

**Comment by ncw** [comment]
@JC-LB This looks like a corruption in the pcloud data "Sat, 06 Oct J632 05:39:02 +0000" isn't a valid timestamp however you squint at it! If you can see this in the web interface I'd report it to pcloud support.

**Comment by JC-LB** [comment]
well seen, one of my files that was rclone copied from local to pcloud was missing dates, could not reimport it through rclone.
Removing it made everything back to normal.
Thanks
