### ISSUE TITLE
`mount` works like a charm but `df` reports incorrect total and free space with '1.0 P'

### ISSUE THREAD

**Issue by mo-han** [ncw/rclone#1956]
Tried mounting a PCloud and a Hubic remote, then `df` showed they have '1.0P/1.0P' space, I would be happy if they really have that large space.

**Comment by ncw** [comment]
:-)  Rclone doesn't support reading the actual size from the cloud provider - most cloud providers pretend you have an infinite storage capacity - rclone rounds that to 1 PB!

I'm not going to fix that - hopefully that isn't a big problem for you!

Nick
