### ISSUE TITLE
--exclude-if-present fails if rclone can't read directory

### ISSUE THREAD

**Issue by jaredmales** [ncw/rclone#1959]
Using the --exclude-if-present option, rclone fails if it encounters a directory which it doesn't have permissions to read (e.g. $HOME/gnupg).  Without --exclude-if-present, rclone silently ignores such directories.  I think it would be useful for this to be the behavior for --exclude-if-present too.

Adding the directory to the exclude list doesn't fix it (as probably expected since the docs say --exclude-if-present has priority).

Tested with:
rclone v1.39
- os/arch: linux/amd64
- go version: go1.9.2

And
rclone v1.39-002-gef89f1f1β
- os/arch: linux/amd64
- go version: go1.9.2
 
Command:
beta/rclone sync $HOME b2:backup-mx9 --transfers 32 --exclude-from excludes --exclude-if-present .rclone-ignore -vv --log-file=log.txt

In this case the 'excludes' file contains a single entry:
/.gnupg**

Full log attached, but the relevant errors are:
ERROR : : error reading source directory: lstat /home/jrmales/.gnupg/.rclone-ignore: permission denied
Failed to sync: not deleting files as there were IO errors

[log.txt](https://github.com/ncw/rclone/files/1608155/log.txt)

**Comment by ncw** [comment]
@idavydov do you fancy taking a look at this?

**Comment by idavydov** [comment]
It seems that Fs interface does not have a way to return ErrorPermissionDenied.

I see two quick workarounds.

1. FileExists returns false in case of any error.
2. We introduce ErrorPermissionDenied which will be (at least initially) implemented only for local fs.

I think it should fix the error; I'm not sure though how easy is it to write proper test for this.

**Comment by ncw** [comment]
I think option 1) is probably undesirable.  I'd probably go for option 2) as that is what rclone has being doing up until now - namely wrapping errors into its own error hierarchy.

**Comment by idavydov** [comment]
It seems that #1979 fixes the bug. However, there are no tests in it.

@ncw, do you have any suggestions on how to write them? Creating a mock fs with permissions seems virtually impossible. It should be possible to create a temporary directory and do testing there. However, this will work only on unix-like OSes.

E.g.
1. Create a temporary directory.
2. Create a filetree there.
3. Chmod one of the directories to 000
4. Call sync.Sync
5. Check the return code

P.S. Unfortunately upcoming weeks are going to be extremely busy, so I do not promise anything quickly.

**Comment by ncw** [comment]
This has been fixed by @idavydov - thanks!

Please find a test beta here

https://beta.rclone.org/v1.39-034-gacd55a8f/ (uploaded in 15-30 mins)

**Comment by ncw** [comment]
@idavydov wrote:

> Creating a mock fs with permissions seems virtually impossible. It should be possible to create a temporary directory and do testing there. However, this will work only on unix-like OSes.

That is the disadvantage with the kind of integration testing rclone does is that some of the error condtitions are hard to test.

It is a small enough patch that I'm happy to have without a test.

**Comment by jaredmales** [comment]
Just tested with v1.39-036-g2030dc13β-linux-amd64, --exclude-if-present worked as expected.  Thanks. 
 rclone is awesome!
