### ISSUE TITLE
x509 error with ARM binary

### ISSUE THREAD

**Issue by doph** [ncw/rclone#196]
I get the following error with the latest ARM binary:
2015/08/02 00:59:55 Failed to create file system for "acd:": Failed to get endpoints: Get https://drive.amazonaws.com/drive/v1/account/endpoint: x509: failed to load system roots and no roots provided

I've tried placing certificates in a handful of places hoping rclone will find them, with no luck.

**Comment by ncw** [comment]
Go tries to load the root certificates from these places on linux.

```
	"/etc/ssl/certs/ca-certificates.crt", // Debian/Ubuntu/Gentoo etc.
	"/etc/pki/tls/certs/ca-bundle.crt",   // Fedora/RHEL
	"/etc/ssl/ca-bundle.pem",             // OpenSUSE
	"/etc/pki/tls/cacert.pem",            // OpenELEC
```

You could try the `--no-check-certificate` flag but you'd have to compile your own as it hasn't made it into a release.

I should probably put this info in the docs as it isn't the first time someone has asked!

Let me know if that helps

**Comment by doph** [comment]
It did help, and I got it up and running. Thanks so much for the prompt reply!

In case it helps any one else:
I'm running rclone on an Asus router (ARMv7) (with RMerlin firmware) which didn't have a certificate bundle installed, nor an certificates update tool available (as it seems full distros have). So I made the directory (the first one you listed seemed to be the ticket), downloaded a bundle, and then set the system clock (which apparently wasn't set correctly by the router's firmware).

mkdir -p /etc/ssl/certs/
curl -o /etc/ssl/certs/ca-certificates.crt https://raw.githubusercontent.com/bagder/ca-bundle/master/ca-bundle.crt
ntpclient -s -h pool.ntp.org

**Comment by ncw** [comment]
@doph thanks for that.  I'm going to re-open this ticket to remind me to put something in the docs!

**Comment by ncw** [comment]
I put your suggestion for fixing in the FAQ entry - thank you very much for that.

**Comment by bengki** [comment]
I have same problem in my Buffalo NAS.
I followed step by step in FAQ and I got error when tried to import ca-bundle.crt into ca-certificate.crt.
The workaround was using -k option in curl command and then copy paste to using nano create ca-certificate.crt. And it worked.

Thanks

**Comment by ncw** [comment]
@bengki I guess using `-k` aka `--insecure` makes sense if the platform doesn't have a ca-bundle.  I'll put that in the FAQ - thanks.
