### ISSUE TITLE
Mount to nfs server directory 

### ISSUE THREAD

**Issue by atytel** [ncw/rclone#1960]
Is it possible to use rclone mount on a nfs server?

**Comment by ncw** [comment]
Do you mean serve an rclone mount via NFS? I'm not sure... Have you tried it?

**Comment by atytel** [comment]
yea i got it working, was a pain though

**Comment by dangmai** [comment]
@atytel do you mind if I asked how you got it working? I'm running into https://github.com/ncw/rclone/issues/2115 when I try to create new files in the nfs mount

**Comment by Wilsonfromdevon** [comment]
Were you able to get it working?

**Comment by ncw** [comment]
If any of you do manage to make it work some docs in [the rclone wiki](https://github.com/ncw/rclone/wiki) would be much appreciated :-)
