### ISSUE TITLE
Backblaze B2 -- Uploads fail during large uploads (100gb).

### ISSUE THREAD

**Issue by HighMans** [ncw/rclone#1964]
I've been getting a lot of B2 upload errors with regards to files > 100gb over the past 2 weeks. I haven't been able to get the log files, but now that I'm storing them, I'm finally able to see what's going on. Today an error showed up and caused by 150gb upload to fail at 95% and I think it'll happen again when I wake up in the morning. I'll post the log of what happens when it fails again.

> What is your rclone version (eg output from `rclone -V`)

    1.39

> Which OS you are using and how many bits (eg Windows 7, 64 bit)

    freebsd/amd64

> Which cloud storage system are you using? (eg Google Drive)

    Backblaze B2

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

     rclone sync /mnt/NAS1/Data B2:[BucketName] -vv --retries=7

> A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

Log too long, truncated around the error. If needed I can post more. 

    2018/01/07 01:03:14 DEBUG : [File] Clearing part upload URL because of error: c001_v0001011_t0023 is too busy (503 service_unavailable)
    2018/01/07 01:03:14 DEBUG : pacer: Rate limited, increasing sleep to 1s
    2018/01/07 01:03:14 DEBUG : pacer: low level retry 1/10 (error c001_v0001011_t0023 is too busy (503 service_unavailable))
    2018/01/07 01:03:14 DEBUG : [File]: Sending chunk 1907 length 100663296
    2018/01/07 01:03:16 DEBUG : pacer: Reducing sleep to 500ms
    2018/01/07 01:03:37 DEBUG : pacer: Reducing sleep to 250ms
    2018/01/07 01:03:37 DEBUG : [File]: Error sending chunk 1907: Post [Upload URL]: net/http: HTTP/1.x transport connection broken: http: ContentLength=100663336 with Body length 99590598
    2018/01/07 01:03:38 DEBUG : [File]: Sending chunk 1908 length 100663296
    2018/01/07 01:03:42 DEBUG : pacer: Reducing sleep to 125ms
    2018/01/07 01:03:42 DEBUG : [File]: Done sending chunk 1904
    2018/01/07 01:03:57 DEBUG : pacer: Reducing sleep to 62.5ms
    2018/01/07 01:03:57 DEBUG : [File]: Done sending chunk 1905
    2018/01/07 01:04:07 INFO  : 
    Transferred:   206.285 GBytes (5.262 MBytes/s)
    Errors:                 1
    Checks:              8701
    Transferred:            0
    Elapsed time:   11h9m0.8s
    Transferring:
     * ...p Job DESKTOP-DNFEJCQ2017-12-14T003015.vbk: 96% done, 3.956 MBytes/s, ETA: 26m49s
    
    2018/01/07 01:04:29 DEBUG : pacer: Reducing sleep to 31.25ms
    2018/01/07 01:04:29 DEBUG : [File]: Done sending chunk 1906
    2018/01/07 01:04:45 DEBUG : pacer: Reducing sleep to 15.625ms
    2018/01/07 01:04:45 DEBUG : [File]: Done sending chunk 1908
    2018/01/07 01:04:45 DEBUG : [File]: Cancelling large file upload due to error: Post [Upload URL]: net/http: HTTP/1.x transport connection broken: http: ContentLength=100663336 with Body length 99590598
    2018/01/07 01:05:07 INFO  : 
    Transferred:   206.344 GBytes (5.256 MBytes/s)
    Errors:                 1
    Checks:              8701
    Transferred:            0
    Elapsed time:  11h10m0.8s
    Transferring:
     * ...p Job DESKTOP-DNFEJCQ2017-12-14T003015.vbk: 96% done, 378.608 kBytes/s, ETA: 4h44m21s
    
    2018/01/07 01:05:28 DEBUG : pacer: Reducing sleep to 10ms
    2018/01/07 01:05:28 ERROR : [File]: Failed to copy: Post [Upload URL]: net/http: HTTP/1.x transport connection broken: http: ContentLength=100663336 with Body length 99590598
    2018/01/07 01:05:28 ERROR : B2 bucket HomeServer-FreeNAS: not deleting files as there were IO errors
    2018/01/07 01:05:28 ERROR : B2 bucket HomeServer-FreeNAS: not deleting directories as there were IO errors
    2018/01/07 01:05:28 ERROR : Attempt 1/7 failed with 2 errors and: Post [Upload URL]: net/http: HTTP/1.x transport connection broken: http: ContentLength=100663336 with Body length 99590598

**Comment by ncw** [comment]
I was just looking at your log - I'm not sure 100% what happened

rclone should have retried the error `[File]: Error sending chunk 1907: Post [Upload URL]: net/http: HTTP/1.x transport connection broken: http: ContentLength=10066` but didn't apparently...

Are you sure you were running 1.39?

Do you have any more of that log? Specifically I'd like to know if chunk 1907 got retried?

**Comment by HighMans** [comment]
I closed this issue because I added the "--transfers 32" flag. I'm 100% sure I'm running 1.39 since that's what rclone -V reported. 

I messed up the log, I missed some data beforehand. It does try to retry 3 times, but failed.

    Jan  7 01:03:14 freenas cronjob: 2018/01/07 01:03:14 DEBUG : [FILE]: Sending chunk 1907 length 100663296
    Jan  7 01:03:14 freenas cronjob: 2018/01/07 01:03:14 DEBUG : B2 bucket HomeServer-FreeNAS: Setting sleep to 1s after error: c001_v0001011_t0023 is too busy (503 service_unavailable)
    Jan  7 01:03:14 freenas cronjob: 2018/01/07 01:03:14 DEBUG : [FILE]: Clearing part upload URL because of error: c001_v0001011_t0023 is too busy (503 service_unavailable)
    Jan  7 01:03:14 freenas cronjob: 2018/01/07 01:03:14 DEBUG : pacer: Rate limited, increasing sleep to 1s
    Jan  7 01:03:14 freenas cronjob: 2018/01/07 01:03:14 DEBUG : pacer: low level retry 1/10 (error c001_v0001011_t0023 is too busy (503 service_unavailable))
    Jan  7 01:03:14 freenas cronjob: 2018/01/07 01:03:14 DEBUG : [FILE]: Sending chunk 1907 length 100663296
    Jan  7 01:03:16 freenas cronjob: 2018/01/07 01:03:16 DEBUG : pacer: Reducing sleep to 500ms
    Jan  7 01:03:37 freenas cronjob: 2018/01/07 01:03:37 DEBUG : pacer: Reducing sleep to 250ms
    Jan  7 01:03:37 freenas cronjob: 2018/01/07 01:03:37 DEBUG : [FILE]: Error sending chunk 1907: Post [LINK]: net/http: HTTP/1.x transport connection broken: http: ContentLength=100663336 with Body length 99590598
    Jan  7 01:03:38 freenas cronjob: 2018/01/07 01:03:38 DEBUG : [FILE]: Sending chunk 1908 length 100663296
    Jan  7 01:03:42 freenas cronjob: 2018/01/07 01:03:42 DEBUG : pacer: Reducing sleep to 125ms
    Jan  7 01:03:42 freenas cronjob: 2018/01/07 01:03:42 DEBUG : [FILE]: Done sending chunk 1904
    Jan  7 01:03:57 freenas cronjob: 2018/01/07 01:03:57 DEBUG : pacer: Reducing sleep to 62.5ms
    Jan  7 01:03:57 freenas cronjob: 2018/01/07 01:03:57 DEBUG : [FILE]: Done sending chunk 1905
    Jan  7 01:04:07 freenas cronjob: 2018/01/07 01:04:07 INFO  : 
    Jan  7 01:04:07 freenas cronjob: Transferred:   206.285 GBytes (5.262 MBytes/s)
    Jan  7 01:04:07 freenas cronjob: Errors:                 1
    Jan  7 01:04:07 freenas cronjob: Checks:              8701
    Jan  7 01:04:07 freenas cronjob: Transferred:            0
    Jan  7 01:04:07 freenas cronjob: Elapsed time:   11h9m0.8s
    Jan  7 01:04:07 freenas cronjob: Transferring:
    Jan  7 01:04:07 freenas cronjob:  * ...p Job DESKTOP-DNFEJCQ2017-12-14T003015.vbk: 96% done, 3.956 MBytes/s, ETA: 26m49s
    Jan  7 01:04:07 freenas cronjob: 
    Jan  7 01:04:29 freenas cronjob: 2018/01/07 01:04:29 DEBUG : pacer: Reducing sleep to 31.25ms
    Jan  7 01:04:29 freenas cronjob: 2018/01/07 01:04:29 DEBUG : [FILE]: Done sending chunk 1906
    Jan  7 01:04:45 freenas cronjob: 2018/01/07 01:04:45 DEBUG : pacer: Reducing sleep to 15.625ms
    Jan  7 01:04:45 freenas cronjob: 2018/01/07 01:04:45 DEBUG : [FILE]: Done sending chunk 1908
    Jan  7 01:04:45 freenas cronjob: 2018/01/07 01:04:45 DEBUG : [FILE]: Cancelling large file upload due to error: Post [LINK]: net/http: HTTP/1.x transport connection broken: http: ContentLength=100663336 with Body length 99590598
    Jan  7 01:05:07 freenas cronjob: 2018/01/07 01:05:07 INFO  : 
    Jan  7 01:05:07 freenas cronjob: Transferred:   206.344 GBytes (5.256 MBytes/s)
    Jan  7 01:05:07 freenas cronjob: Errors:                 1
    Jan  7 01:05:07 freenas cronjob: Checks:              8701
    Jan  7 01:05:07 freenas cronjob: Transferred:            0
    Jan  7 01:05:07 freenas cronjob: Elapsed time:  11h10m0.8s
    Jan  7 01:05:07 freenas cronjob: Transferring:
    Jan  7 01:05:07 freenas cronjob:  * ...p Job DESKTOP-DNFEJCQ2017-12-14T003015.vbk: 96% done, 378.608 kBytes/s, ETA: 4h44m21s
    Jan  7 01:05:07 freenas cronjob: 
    Jan  7 01:05:28 freenas cronjob: 2018/01/07 01:05:28 DEBUG : pacer: Reducing sleep to 10ms
    Jan  7 01:05:28 freenas cronjob: 2018/01/07 01:05:28 ERROR : [FILE]: Failed to copy: Post [LINK]: net/http: HTTP/1.x transport connection broken: http: ContentLength=100663336 with Body length 99590598
    Jan  7 01:05:28 freenas cronjob: 2018/01/07 01:05:28 ERROR : B2 bucket HomeServer-FreeNAS: not deleting files as there were IO errors
    Jan  7 01:05:28 freenas cronjob: 2018/01/07 01:05:28 ERROR : B2 bucket HomeServer-FreeNAS: not deleting directories as there were IO errors
    Jan  7 01:05:28 freenas cronjob: 2018/01/07 01:05:28 ERROR : Attempt 1/7 failed with 2 errors and: Post [LINK]: net/http: HTTP/1.x transport connection broken: http: ContentLength=100663336 with Body length 99590598

**Comment by ncw** [comment]
I'm still scratching my head over that log...

It looks like rclone didn't retry that error, but I've managed to add a patch to rclone to show that it definitely does retry that error!

Do you have the complete unedited log you could email me maybe?  nick@craig-wood.com ?

If not, then please make a new issue if it happens again!

Thanks
