### ISSUE TITLE
mount: make rename fall back to copy then delete (was unable to move files in mounted hubic)

### ISSUE THREAD

**Issue by thammi** [ncw/rclone#1965]
I mounted a hubic remote target and tried to move a file:

```
$ mv blub bla
mv: cannot move 'blub' to 'bla': Input/output error
```

My rclone command (`rclone mount -vv hubic_open:default ~/mnt/`) displayed the following error:

```
2018/01/07 20:06:10 DEBUG : /: Lookup: name="bla"
2018/01/07 20:06:10 DEBUG : /: >Lookup: node=<nil>, err=no such file or directory
2018/01/07 20:06:10 DEBUG : /: Lookup: name="blub"
2018/01/07 20:06:10 DEBUG : /: >Lookup: node=blub, err=<nil>
2018/01/07 20:06:10 DEBUG : blub: Attr: 
2018/01/07 20:06:10 DEBUG : blub: >Attr: a=valid=1m0s ino=0 size=4 mode=-rw-r--r--, err=<nil>
2018/01/07 20:06:10 DEBUG : /: Lookup: name="bla"
2018/01/07 20:06:10 DEBUG : /: >Lookup: node=<nil>, err=no such file or directory
2018/01/07 20:06:10 DEBUG : /: Lookup: name="bla"
2018/01/07 20:06:10 DEBUG : /: >Lookup: node=<nil>, err=no such file or directory
2018/01/07 20:06:10 DEBUG : /: Rename: oldName="blub", newName="bla", newDir=/
2018/01/07 20:06:10 ERROR : blub: Dir.Rename error: Fs "Hubic Swift container default" can't rename files (no Move)
2018/01/07 20:06:10 DEBUG : /: >Rename: err=Fs "Hubic Swift container default" can't rename files (no Move)
```

I am using rclone v1.37 on Debian 9.2 amd64. This limitation is not mentioned in the online documentation. Renaming inside mounts works using Dropbox.

Having this feature on hubic would be very useful to me. I am actually trying to rename inside an encrypted  storage based on the hubic target, so renaming using the webinterface is very hard.

**Comment by ncw** [comment]
openstack swift and hence hubic doesn't actually have a server side move.

It does have a server side copy though.  If you use `rclone move` to move things it will do a server side copy followed by a delete.

[It looks like I thought of implementing this](https://github.com/ncw/rclone/blob/master/vfs/dir.go#L445) in `rclone mount` but didn't yet.

I'll re-purpose this ticket to implement that.

In the mean time you can use `rclone move` to do it which isn't quite as convenient - sorry!

**Comment by thammi** [comment]
I tried using `rclone move` but ran into #515.

**Comment by ncw** [comment]
> I tried using rclone move but ran into #515.

That is unfortunate :-( I'd love to get some help with that or this issue if you've got the time!

**Comment by seonghobae** [comment]
I hope this someday. I'm using the Rstudio server on the mounted Swift device, but Rstudio cannot save the working image, that works with the rename.

**Comment by ncw** [comment]
I have attempted to fix this here

https://beta.rclone.org/branch/v1.43-096-ga9fc86f5-fix-2569-mount-move-beta/ (uploaded in 15-30 mins)

Feedback welcome :-)

**Comment by ncw** [comment]
I've merged this fix to master now, it will be in [the latest beta](https://beta.rclone.org) in 15-30 mins an in v1.44.
