### ISSUE TITLE
rclone is not working with one drive storage

### ISSUE THREAD

**Issue by him4nsh** [ncw/rclone#1969]
I am using rclone on windows 8 machine..with one drive as a storage option
unable to authorize  rclone with one drive..ie showing unable to complete your request ....

**Comment by ncw** [comment]
I just ran through a config and it is working fine for me.  Can you try again and post a screenshot or log of what you did and what happened please?

**Comment by him4nsh** [comment]
Now its working fine for me also ....actually there was a firewall issue in my network .
So thanks a lot ....

**Comment by ncw** [comment]
OK great - I'll close this now
