### ISSUE TITLE
onedrive: add support for Move and MoveDir

### ISSUE THREAD

**Issue by ncw** [ncw/rclone#197]
Onedrive is capable of Move and MoveDir with the [update method](https://dev.onedrive.com/items/move.htm)

**Comment by ncw** [comment]
To make --backup-dir work really well on onedrive this is needed.

(Fix the overview table when implemented!)

**Comment by ncw** [comment]
@olihey have you got time to look at this?

**Comment by olihey** [comment]
@ncw Sure, I can give it a try but not 2017, busy with day job :)

**Comment by olihey** [comment]
@ncw I am not sure what I should be doing here? Seems like you have implemented this already? At least in the Move method, or am I missing something?

**Comment by ncw** [comment]
@olihey I do seem to have done Move...  There is MoveDir to do too, but that is much less important than Move.

**Comment by ncw** [comment]
This is done - thanks @Cnly :-)

It will be in [the latest beta](https://beta.rclone.org) shortly and in v1.43

**Comment by ncw** [comment]
This is done now - thanks @Cnly :-)

https://beta.rclone.org/v1.42-083-gd95667b0/ (uploaded in 15-30 mins)
