### ISSUE TITLE
~/external_USB/cloud

### ISSUE THREAD

**Issue by perrett** [ncw/rclone#1970]
When filing an issue, please include the following information if possible as well as a description of the problem.  Make sure you test with the latest beta of rclone.

    https://beta.rclone.org/
    https://rclone.org/downloads/

If you've just got a question or aren't sure if you've found a bug then please use the [rclone forum](https://forum.rclone.org/) instead of filing an issue.

> What is your rclone version (eg output from `rclone -V`)

> Which OS you are using and how many bits (eg Windows 7, 64 bit)

> Which cloud storage system are you using? (eg Google Drive)

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

> A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

**Comment by ncw** [comment]
Was this opened by accident?

**Comment by ncw** [comment]
I shall close it, please re-open with more info if required!
