### ISSUE TITLE
Yandex.Disk Error: Eof on big files

### ISSUE THREAD

**Issue by RomanVolkov** [ncw/rclone#1976]
> What is your rclone version (eg output from `rclone -V`)

rclone v1.39
os/arch: linux/amd64
go version: go1.9.2

> Which OS you are using and how many bits (eg Windows 7, 64 bit)

Ubuntu 16.04.2 LTS

> Which cloud storage system are you using? (eg Google Drive)

Yandex.Disk

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

rclone copy --log-level=DEBUG --transfers 4 --size-only --buffer-size 500M wdmycloud: yandexdisk:wdmycloud
rclone copy wdmycloud: yandexdisk:wdmycloud
rclone copy --log-level=DEBUG --transfers 1 --buffer-size 500M wdmycloud: yandexdisk:wdmycloud

> A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

2018/01/14 16:59:46 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

2018/01/14 16:59:46 DEBUG : HTTP RESPONSE (req 0xc420457800)

2018/01/14 16:59:46 DEBUG : Error: EOF

2018/01/14 16:59:46 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

Initial discussion: https://forum.rclone.org/t/rclone-copy-stucks-at-99/4575/10

**Comment by RomanVolkov** [comment]
Tried to copy large files from local folder to the same ftp - works without problems. os: Mac OS

**Comment by ncw** [comment]
> Tried to copy large files from local folder to the same ftp - works without problems. os: Mac OS

Do you get the same errors copying the large files from local disk to Yandex?

Can you try your normal transfer without the `--buffer-size 500M`  flag? I'd like to see if that makes a different.

**Comment by RomanVolkov** [comment]
@ncw I'm still testing local approach. Sometimes it fails, want to understand dependence first

**Comment by ncw** [comment]
@RomanVolkov let me know your results when you are done please.

**Comment by RomanVolkov** [comment]
seems it works in case when I'm connecting direct to my NAS from local network.
Previously I did it from digital open vps, NAS is exposed via router. maybe router adds some networking issues.
I have copied many of 1gb files, seems I can close this issue.
thanks for your help. Maybe I'll get back to experiment with NAS - Router - VPS - Yandex again later for big files.

**Comment by ncw** [comment]
Glad you've got closer to finding the issue - thanks for testing.
