### ISSUE TITLE
Hubic error -  "invalid refresh token"

### ISSUE THREAD

**Issue by Santinell** [ncw/rclone#1989]
I am generating rclone.conf by myself (by using oauth from web site), all providers which I added - works perfectly, meanwhile Hubic is acting strange:
If `access_token` is still active (6 hours did't passed) and `expiry` in future
then it works. But if `access_token` isn't active or `expiry` in past - then I have error
about invalid refresh token...
Where I could make a mistake? Access and refresh tokens look good and normal (64 symbols)
scope for oauth is `credentials.r`
Maybe I need somehow refresh access token before doing `rclone copy`?

> What is your rclone version (eg output from `rclone -V`)

1.39
> Which OS you are using and how many bits (eg Windows 7, 64 bit)

Ubuntu 16.04 x64
> Which cloud storage system are you using? (eg Google Drive)

Hubic
> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

rclone --tpslimit 20 --tpslimit-burst 2 copy /d2c/backup "My Hubic:d2c-infn6eym2/romeo/backups/"
> A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

```
2018/01/19 12:20:02 DEBUG : Using config file from "/root/.config/rclone/rclone.conf" 
2018/01/19 12:20:02 INFO : Starting HTTP transaction limiter: max 20 transactions/s with burst 2 
2018/01/19 12:20:02 DEBUG : rclone: Version "v1.39" starting with parameters ["/usr/bin/rclone" "-vv" "--tpslimit" "20" "--tpslimit-burst" "2" "copy" "/d2c/backup" "My Hubic:d2c-infn6eym2/romeo/backups/"] 
2018/01/19 12:20:03 Failed to create file system for "My Hubic:d2c-infn6eym2/romeo/backups/": error authenticating swift connection: Get https://api.hubic.com/1.0/account/credentials: oauth2: cannot fetch token: 400 Response: {"error_description":"invalid refresh token","error":"invalid_request"}
```

rclone.conf

```
[My Hubic]
type = hubic
client_id =
client_secret =
token = {"access_token":"xxx","token_type":"Bearer","refresh_token":"xxx","expiry":"2018-01-19T12:19:19.240Z"}
```

**Comment by ncw** [comment]
> If access_token is still active (6 hours did't passed) and expiry in future
> then it works. But if access_token isn't active or expiry in past - then I have error
> about invalid refresh token...

The error message suggests that your refresh token is invalid `{"error_description":"invalid refresh token","error":"invalid_request"}` so I think that has got to be the most obvious explanation.

How exactly are you getting it?

> Maybe I need somehow refresh access token before doing rclone copy?

Rclone will use the refresh token to get a new access token whenever it expires.

My config file looks like this 

before refresh

```
[hubic]
type = hubic
client_id = 
client_secret = 
token = {"access_token":"XXX","token_type":"Bearer","refresh_token":"XXX","expiry":"2017-09-01T23:37:55.221295692+01:00"}
```

after refresh

```
[hubic]
type = hubic
client_id = 
client_secret = 
token = {"access_token":"XXX","token_type":"Bearer","refresh_token":"XXX","expiry":"2018-01-19T22:00:05.542032922Z"}
```

which doesn't look significantly different to yours...

**Comment by Santinell** [comment]
I am using nodejs package passport.js for getting oauth tokens:

```javascript
  passport.use('hubic', new OAuth2Strategy({
    authorizationURL: 'https://api.hubic.com/oauth/auth',
    tokenURL: 'https://api.hubic.com/oauth/token',
    clientID: config.hubic.clientID,
    clientSecret: config.hubic.clientSecret,
    callbackURL: `${env.API_HOST}/oauth/hubic/callback`,
    scope: ['credentials.r']
  }, ((accessToken, refreshToken, profile, cb) => {
      cb(null, {accessToken, refreshToken});
    })
  ));
```

and then I put them into rclone.conf file:

```javascript
return `[${name}]
type = hubic
client_id =
client_secret =
token = {"access_token":"${accessToken}","token_type":"Bearer","refresh_token":"${refreshToken}","expiry":"${(new Date()).toISOString()}"}`;
```

And I am wonder what can be wrong...

**Comment by Santinell** [comment]
Could you try to generate tokens and check them?
https://api.t4m.pw/oauth/hubic

**Comment by ncw** [comment]
You need to put your `client_id` and `client_secret` in the config otherwise the refresh token will fail I think since I see you aren't using rclone's client_id.

**Comment by Santinell** [comment]
I can’t do it because I am generating configs for our clients.
I don't think that this is secure to show them my `client_id` and `client_secret`.

I saw source code of rclone's hubic backend and you guys just use token and everything works fine...

**Comment by ncw** [comment]
> I saw source code of rclone's hubic backend and you guys just use token and everything works fine...

Yes you are right, just the refresh token is needed.

If you want to see what is going with token refresh on then try `rclone lsd -vv --dump bodies remote:` with one of your tokens and with rclone doing its thing normally and see if you can spot the difference.  Edit the expiry dates in the config file first so the tokens have expired, so the first thing rclone does is refresh the token.

**Comment by Santinell** [comment]
The same error...
```
2018/01/30 07:17:16 DEBUG : rclone: Version "v1.39" starting with parameters ["/usr/bin/rclone" "lsd" "-vv" "--dump" "bodies,headers" "My Hubic:"]
2018/01/30 07:17:16 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2018/01/30 07:17:16 DEBUG : HTTP REQUEST (req 0xc4200dd800)
2018/01/30 07:17:16 DEBUG : POST /oauth/token/ HTTP/1.1
Host: api.hubic.com
User-Agent: rclone/v1.39
Content-Length: 103
Authorization: XXXX
Content-Type: application/x-www-form-urlencoded
Accept-Encoding: gzip

grant_type=refresh_token&refresh_token=81CpfEOs1VIJN3cFbW4bnSZeGPn4EyfFEFCKyKb0FwsAhAq29R6HkgTWxOxAvaju
2018/01/30 07:17:16 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2018/01/30 07:17:21 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2018/01/30 07:17:21 DEBUG : HTTP RESPONSE (req 0xc4200dd800)
2018/01/30 07:17:21 DEBUG : HTTP/1.1 400 400
Transfer-Encoding: chunked
Content-Type: application/json
Date: Tue, 30 Jan 2018 07:17:21 GMT
Server: nginx/1.4.7
Set-Cookie: SERVERID403=4efc293a|WnAcB|WnAcB; path=/
Strict-Transport-Security: max-age=15768000

47
{"error_description":"invalid refresh token","error":"invalid_request"}
0

2018/01/30 07:17:21 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2018/01/30 07:17:21 Failed to create file system for "My Hubic:": error authenticating swift connection: Get https://api.hubic.com/1.0/account/credentials: oauth2: cannot fetch token: 400
Response: {"error_description":"invalid refresh token","error":"invalid_request"}
```
By the way what should be in Authorization header? In log just `XXXX`...
In documentation about 'Refresh access token' I see this text

`In this step, you need to authenticate your application. You can do this by passing client_id and client_secret in the post request, or (recommended) by using the HTTP Authorization header.`

That means that client_id and client_secret is required for refreshing by Hubic?
But how it works for your application?

**Comment by ncw** [comment]
> By the way what should be in Authorization header? In log just XXXX...

Add `--dump auth` to see that too.

> That means that client_id and client_secret is required for refreshing by Hubic?
But how refreshing token works for your application without this parameters?

It is passing them in the Authorization header.  Which is a base 64 encoded client_id:client_secret

So I was right originally, you do need the client_id and the client_secret - sorry!

**Comment by Santinell** [comment]
I've checked Authorization header and find out reason of problem
In Authorization header using your credentials:
`api_hubic_svWP970PvSWbw5G3PzrAqZ6X2uHeZBPI:Zanw6yd18CIoS3vDS3Cndi720DsipdyER7gNkCIKFT5IdduvDRkjn4PQwUclicfh`
That's why for proper refreshing token client_id and client_secret MUST be defined. (or user should generate tokens with your cli)
I think you should correct your documentation about Hubic.

**Comment by ncw** [comment]
@Santinell wrote:
> That's why for proper refreshing token client_id and client_secret MUST be defined. (or user should generate tokens with your cli)

That is what I said above "You need to put your client_id and client_secret in the config otherwise the refresh token will fail I think since I see you aren't using rclone's client_id."

> I think you should correct your documentation about Hubic.

What would you suggest?  This is a very non-standard use of rclone!

> By the way what users can do with our client_id and client_secret?

Not a lot.  Impersonate your app - that is about it.  It doesn't allow them access to any data they wouldn't be able to access otherwise.

**Comment by Santinell** [comment]
Thanks for your help!
