### ISSUE TITLE
Add native support for hubiC (swift / OAuth2)

### ISSUE THREAD

**Issue by roms2000** [ncw/rclone#200]
Could you add a native support for hubiC ?
Which is nearly like a swift (openstack) with OAuth2 support (like GoogleCloodStorage maybe)

API is describe here : 
https://api.hubic.com/
and Authentication is here :
https://api.hubic.com/sandbox/

**Comment by ncw** [comment]
I've been thinking about this already, so yes :-)

**Comment by roms2000** [comment]
Wooouh !
That's really great :-D
Thanks you for your quick reply

**Comment by Thinkscape** [comment]
:+1:

**Comment by ncw** [comment]
This is now live in v1.25

Please test and if you find any problems then open a new issue!

Thanks

Nick

**Comment by roms2000** [comment]
Really fast :)
Even authentication of the application is automatic and works very well.
For the moment, no problems. I'll bug reports, if any, in a few days.
Really thank you again.

**Comment by roms2000** [comment]
Pretty stable after 5 days of work and syncing average 1Tb.

**Comment by ncw** [comment]
@roms2000 Great news! Thanks for the update.
