### ISSUE TITLE
"Corruptred on Transfer" only when mounted

### ISSUE THREAD

**Issue by goldme21** [ncw/rclone#2002]
I have a Google Drive account that I set up using rclone. I have configured the drive in rclone (not encrypted) and mounted that using:

`/usr/bin/rclone mount --allow-other --ignore-checksum --uid 1000 --gid 1000 --config /root/.config/rclone/rclone.conf plex_write: /media/gdrive`

This works perfectly and I can copy anything. I then set up a remote on a subfolder in this drive and mount it like this:
`/usr/bin/rclone mount --allow-other --config /root/.config/rclone/rclone.conf enc_write: /media/media`

The encrypted mount is writable and readable. If I copy a small file (text file with "test" in it) in the file explorer to the encrypted mount it works perfectly. As soon I copy a bigger file (like 14MB) then the file gets copied but I get a "Corrupted on transfer" error in de syslog. I also see an "error closing file: input/output error" in the file explorer. The same happens when I use rclone from the command line to write to the encrypted mounted directory.

The file however does get copied. So if I diff it (from the encrypted folder) with the original file: the files are identical. No corruption what so ever.

If I use rclone by writing to the share (without the mount):
rclone -vv copy dolby_unfold_v1_lossless-DWEU.m2ts enc_write:/

This works perfectly. No problem. I can find the file and everything.

> What is your rclone version (eg output from `rclone -V`)
rclone v1.39
- os/arch: linux/amd64
- go version: go1.9.2

> Which OS you are using and how many bits (eg Windows 7, 64 bit)
Ubuntu Mate 
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial

> Which cloud storage system are you using? (eg Google Drive)
Google Drive

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone -vv copy dolby-test-tones_7_1_2.mp4 /media/media/

> A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

> Jan 23 10:27:52 nas rclone[1527]: 2018/01/23 10:27:52 DEBUG : &{dolby_conductor_lossless-DWEU.m2ts (w)}: >Write: written=2048, err=<nil>
Jan 23 10:27:52 nas rclone[1527]: 2018/01/23 10:27:52 DEBUG : dolby_conductor_lossless-DWEU.m2ts: Attr:
Jan 23 10:27:52 nas rclone[1527]: 2018/01/23 10:27:52 DEBUG : dolby_conductor_lossless-DWEU.m2ts: >Attr: a=valid=1m0s ino=0 size=56985600 mode=-rw-r--r--, err=<nil>
Jan 23 10:27:52 nas rclone[1527]: 2018/01/23 10:27:52 DEBUG : &{dolby_conductor_lossless-DWEU.m2ts (w)}: Flush:
Jan 23 10:27:53 nas rclone[1527]: 2018/01/23 10:27:53 DEBUG : dolby_conductor_lossless-DWEU.m2ts: Modification times differ by -236.939µs: 2018-01-23 10:27:49.100236939 +0100 CET m=+55.385801319, 2018-01-23 10:27:49.1 +0100 CET
Jan 23 10:27:53 nas rclone[1527]: 2018/01/23 10:27:53 ERROR : dolby_conductor_lossless-DWEU.m2ts: corrupted on transfer
Jan 23 10:27:53 nas rclone[1527]: 2018/01/23 10:27:53 ERROR : dolby_conductor_lossless-DWEU.m2ts: WriteFileHandle.New Rcat failed: corrupted on transfer
Jan 23 10:27:53 nas rclone[1527]: 2018/01/23 10:27:53 ERROR : dolby_conductor_lossless-DWEU.m2ts: WriteFileHandle.Flush error: corrupted on transfer
Jan 23 10:27:53 nas rclone[1527]: 2018/01/23 10:27:53 DEBUG : &{dolby_conductor_lossless-DWEU.m2ts (w)}: >Flush: err=corrupted on transfer
Jan 23 10:27:53 nas rclone[1527]: 2018/01/23 10:27:53 DEBUG : &{dolby_conductor_lossless-DWEU.m2ts (w)}: Release:
Jan 23 10:27:53 nas rclone[1527]: 2018/01/23 10:27:53 DEBUG : dolby_conductor_lossless-DWEU.m2ts: WriteFileHandle.Release nothing to do
Jan 23 10:27:53 nas rclone[1527]: 2018/01/23 10:27:53 DEBUG : &{dolby_conductor_lossless-DWEU.m2ts (w)}: >Release: err=<nil>
Jan 23 10:27:53 nas rclone[1527]: 2018/01/23 10:27:53 DEBUG : /: Attr:
Jan 23 10:27:53 nas rclone[1527]: 2018/01/23 10:27:53 DEBUG : /: >Attr: attr=valid=1m0s ino=0 size=0 mode=drwxr-xr-x, err=<nil>
Jan 23 10:27:53 nas rclone[1527]: 2018/01/23 10:27:53 DEBUG : /: Lookup: name=".Trash"
Jan 23 10:27:53 nas rclone[1527]: 2018/01/23 10:27:53 DEBUG : /: >Lookup: node=<nil>, err=no such file or directory
Jan 23 10:27:53 nas rclone[1527]: 2018/01/23 10:27:53 DEBUG : /: Lookup: name=".Trash-1000"
Jan 23 10:27:53 nas rclone[1527]: 2018/01/23 10:27:53 DEBUG : /: >Lookup: node=<nil>, err=no such file or directory
Jan 23 10:27:53 nas rclone[1527]: 2018/01/23 10:27:53 DEBUG : : Statfs:
Jan 23 10:27:53 nas rclone[1527]: 2018/01/23 10:27:53 DEBUG : : >Statfs: stat={Blocks:274877906944 Bfree:274877906944 Bavail:274877906944 Files:1000000000 Ffree:1000000000 Bsize:4096 Namelen:255 Frsize:4096}, err=<nil>

**Comment by ncw** [comment]
This

>  Modification times differ by -236.939µs: 2018-01-23 10:27:49.100236939 +0100 CET m=+55.385801319, 2018-01-23 10:27:49.1 +0100 CET

Is the problem.

That also explains why it works without crypt but doesn't with it as it can check the checksum without crypt

You can work-around this problem using `--modify-window 1s` - can you try that?

It looks like rclone isn't calculating the modify window when running the mount command.  That is bad because operations.Rcat needs the modify window to be calculated.

**Comment by goldme21** [comment]
Will do as soon as my Google Drive ban has ended and report back :)

Thanks for the great analysis! You are doing a great job.

**Comment by breunigs** [comment]
I believe the bug has been fixed inadvertently through 291954babab85975c38a2db9cd1e93aaca77cb1c to the switch to `cmd.NewFsDir` which does call `CalculateModifyWindow`. I added a testcase in #2319 to ensure it doesn't accidentally break again.
