### ISSUE TITLE
Dropbox for business folders outside users default not supported

### ISSUE THREAD

**Issue by w0rkrb** [ncw/rclone#2003]
When connecting to Dropbox for business it is not possible to view files outside the specific users default folder, e.g.

Organisations-top-level-folder
              |_______  Users own default folder - This is the one listed when running rclone -ls Dropbox:
              |_______ Company folder A - Not listed / accessible
              |_______ Company folder B - Not listed / accessible
              etc
Based on conversation in the rclone forum ( https://forum.rclone.org/t/dropbox-for-business-how-do-i-backup-of-all-company-folders/4642 ) it appears this is not currently supported due to the Business specific API differing from standard Dropbox. 

> rclone version = 1.39

> Linux 64 bit ( Ubuntu 16.04 )

> Dropbox for Business

> The command you were trying to run: rclone lsd Dropbox-tp:

> A log from the command:

rclone -vv lsd Dropbox-tp:
2018/01/23 16:49:01 DEBUG : Using config file from "/root/.rclone.conf"
2018/01/23 16:49:01 DEBUG : rclone: Version "v1.39" starting with parameters ["./rclone" "-vv" "lsd" "Dropbox-tp:"]
2018/01/23 16:49:02 INFO  : Dropbox root '': Modify window is 1s
          -1 2018-01-23 16:49:03        -1 PowerShell-PowerUp
          -1 2018-01-23 16:49:03        -1 Ultimate Windows Tweaker 4.3
2018/01/23 16:49:03 DEBUG : Go routines at exit 4
2018/01/23 16:49:03 DEBUG : rclone: Version "v1.39" finishing with parameters ["./rclone" "-vv" "lsd" "Dropbox-tp:"]

**Comment by ncw** [comment]
If anyone wants me to work on this, then I'll need access to a dropbox for business account - any takers?

**Comment by icepuma** [comment]
@ncw I sent you an email regarding your request :+1:

**Comment by ncw** [comment]
I made a first attempt at this here.

To access the root of the dropbox for business use a leading `/`

So `rclone lsf dropbox:` lists your home directory whereas `rclone lsf dropbox:\` lists the root of the dropbox for business.

I'm not sure where I like this or not - let me know what you think!

https://beta.rclone.org/v1.41-071-g7ab458da-dropbox-business/ (uploaded in 15-30 mins)

**Comment by ncw** [comment]
Is everyone happy with this?  Ie the idea of using an additional `/` to access the root of a dropbox for business?

If so I'll write a few more docs and merge it!

**Comment by icepuma** [comment]
@w0rkrb Does it work for you?

**Comment by w0rkrb** [comment]
@icepuma Sounds good to me. Sorry I didn't join the conversation sooner, I'm currently out of the country with limited internet access.

**Comment by ncw** [comment]
I've merged this now here

https://beta.rclone.org/v1.41-104-gd1892896/ (uploaded in 15-30 mins)

Here are the docs

### Dropbox for business ###

Rclone supports Dropbox for business and Team Folders.

When using Dropbox for business `remote:` and `remote:path/to/file`
will refer to your personal folder.

If you wish to see Team Folders you must use a leading `/` in the
path, so `rclone lsd remote:/` will refer to the root and show you all
Team Folders and your User Folder.

You can then use team folders like this `remote:/TeamFolder` and
`remote:/TeamFolder/path/to/file`.

A leading `/` for a Dropbox personal account will do nothing, but it
will take an extra HTTP transaction so it should be avoided.

**Comment by ncw** [comment]
@nsamanta glad you got it working. It is documented here: https://rclone.org/dropbox/#dropbox-for-business

Could we improve that?
