### ISSUE TITLE
--track-renames doesn't work with 'copy' command on Google Drive

### ISSUE THREAD

**Issue by jschwalbe** [ncw/rclone#2008]
_Version:_
rclone v1.39
- os/arch: darwin/amd64
- go version: go1.9.2

_Command:_
`rclone copy /Volumes/WD3TB/TV/Aerial\ America/ gdrive:/TV/WD3TB/Aerial\ America/ -vv --track-renames --size-only --transfers 1`

Here's the setup: I previously uploaded a file (name: `file`) to Google Drive via rclone. Then I change the name on my local computer to `samefile`. Here's the output (slightly trimmed for conciseness):
```
2018/01/23 20:03:15 DEBUG : Using config file from "/Users/username/.rclone.conf"
2018/01/23 20:03:15 DEBUG : rclone: Version "v1.39" starting with parameters ["rclone" "copy" "-vv" "/Volumes/WD3TB/TV/Aerial America/" "gdrive:/TV/WD3TB/Aerial America/" "-vv" "--track-renames" "--size-only" "--transfers" "1"]
<snipped a few pacer rate limited errors>
2018/01/23 20:03:20 INFO  : Google drive root 'TV/WD3TB/Aerial America': Modify window is 1s
2018/01/23 20:03:20 INFO  : Google drive root 'TV/WD3TB/Aerial America': Making map for --track-renames
2018/01/23 20:03:20 INFO  : Google drive root 'TV/WD3TB/Aerial America': Finished making map for --track-renames
2018/01/23 20:03:20 INFO  : Google drive root 'TV/WD3TB/Aerial America': Waiting for checks to finish
2018/01/23 20:03:20 INFO  : Google drive root 'TV/WD3TB/Aerial America': Waiting for renames to finish
2018/01/23 20:03:22 INFO  : samefile: Copied (new)
2018/01/23 20:03:31 DEBUG : America in Color - The 1920s.mp4: Sending chunk 0 length 8388608
^C
```

As you can see, rclone copied `samefile` over as if it were a new file. Then it begins sending over the next file (which also is already uploaded, just with a different name). 

Curiously, this also happens when a file is moved to another folder (which I thought was supposed to be covered as well by `--track-renames`). For example: Directory1/file is already on Google Drive. On my computer move file to Directory1/subdirectoryA/file and rclone begins a brand new upload (a duplicate copy). 

Any thoughts? Am I using `--track-renames` incorrectly? Thanks much

**Comment by ncw** [comment]
Note that `--track-renames` does tracking of renames - what you are asking it to do is track a server side copy...

on drive before the copy you have

  * file

on drive after the copy you have

  * file
  * samefile

So a server side copy was required *not* a rename.

However if you had used "rclone sync" instead of copy, then instead of deleting "file" and uploading "samefile" it would have renamed "file" into "samefile", eg

```
$ mv t3/file2.txt  t3/file3.txt 
$ rclone -vv --track-renames sync t3 drive:test/t3
2018/01/24 11:41:07 INFO  : Google drive root 'test/t3': Making map for --track-renames
2018/01/24 11:41:07 INFO  : Google drive root 'test/t3': Finished making map for --track-renames
2018/01/24 11:41:07 INFO  : Google drive root 'test/t3': Waiting for checks to finish
2018/01/24 11:41:07 INFO  : Google drive root 'test/t3': Waiting for renames to finish
2018/01/24 11:41:08 INFO  : file2.txt: Moved (server side)
2018/01/24 11:41:08 INFO  : file3.txt: Renamed from "file2.txt"
2018/01/24 11:41:08 INFO  : Google drive root 'test/t3': Waiting for transfers to finish
2018/01/24 11:41:08 INFO  : Waiting for deletions to finish
```

So what I think is that the docs are wrong stating that  `--track-renames` will work with `rclone copy`.  It does kind of work in a theoretical way but it will never do anything useful as copy never deletes any files in the destination.  The same with `rclone move`.

I'll correct the docs!

**Comment by jschwalbe** [comment]
I was on vacation, sorry for the delay in my reply. 

If what I'm understanding is true, then when I do the copy command with --track-renames, it shouldn't be uploading "samefile" a second time, but doing a server-side copy? I'm not sure it's doing that as is.

**Comment by ncw** [comment]
No, what I'm saying is that it won't do a server side copy, it only does server side renames.

**Comment by jschwalbe** [comment]
But if the file is identical, shouldn't it do a server side copy? (In other words, is there a way to check to see if the to-be-uploaded file already exists on the server? Should there be?)

**Comment by ncw** [comment]
> But if the file is identical, shouldn't it do a server side copy?

That would be a different flag `--track-copies` or something like that which we haven't written.

When doing an rclone sync it is very obvious which files to check when implementing `--track-renames` - the ones that are about to be deleted at the end of the sync.  However with `--track-copies` you'd have to check every file in the sync so it could be quite expensive in terms of memory.  You'd have to first load the directory listing into memory, then do the sync/copy/move and check for an existing file match before doing an actual copy.

Certainly not impossible!

**Comment by ncw** [comment]
I've "fixed" this by adding an error message if you attempt to use --track-renames with move or copy.

**Comment by Qwatuz** [comment]
Is there any possibility to support copy with --track-renames @ncw ? Quite often I want to copy remote to remote and keep file names on one remote, without creating dupes.

Sync would force a rename however copy would leave the file names as original on destination and only copy/create missing files which is perfect.

**Comment by ncw** [comment]
@Qwatuz it is possible, but non trivial! See my comment above: https://github.com/rclone/rclone/issues/2008#issuecomment-365343427

**Comment by Qwatuz** [comment]
> 
> 
> @Qwatuz it is possible, but non trivial! See my comment above: [#2008 (comment)](https://github.com/rclone/rclone/issues/2008#issuecomment-365343427)

Thanks for the quick reply! I assumed it was all in memory for `--track-renames` but now I see how it works.

Hopefully one day there may be higher demand.
