### ISSUE TITLE
rClone - Cache problem / Windows / Linux 

### ISSUE THREAD

**Issue by rodeoric** [ncw/rclone#2009]
> What is your rclone version (eg output from `rclone -V`)

rclone v1.39
os/arch: windows/amd64
go version: go1.9.2

> Which OS you are using and how many bits (eg Windows 7, 64 bit)

Windows 10, 64bit

> Which cloud storage system are you using? (eg Google Drive)

Google Drive

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

rclone -v mount --allow-non-empty --allow-other --max-read-ahead 200M --drive-chunk-size 128M --checkers 40 --dir-cache-time 30m --transfers=32 google1: /cloud_drive/googlestorage1 &

```
2018/01/24 03:42:28 ERROR : winfsp-1.2.17346.msi: WriteFileHandle: Truncate: Can't change size without cache
2018/01/24 03:42:38 ERROR : winfsp-1.2.17346.msi: WriteFileHandle: ReadAt: Can't read and write to file without cache 
```

I had 3 different problems at the moment. 1 is already solved. 

I think the main problem is the cache option on my systems. On Windows i get always the errors your can see above. 

The second problem is when i stream from my root server i can stream with this mount "4k" without anyproblems directly out of my google drive. I started setting up a new server with ubuntu 16.04. and setup rClone, but from this server it is impossible to stream cause the stream is wholte time freezing. I think it is not a hardware problem cause those are dedicated 4 and 8 core servers, i think it is a big cache problem with mounting. 

#1 Informations the main linux system: (all working perfectly including streaming): 
Intel G850
32 GB Ram
8 TB HDD
10 Gbit/s

#2 Informations about second linux system: (streaming not possible, whole files lagging, freezing):
Ubuntu 16.04. -64 Bit
Intel C2750 Avoton - 16 GB RAM and SSD for Hostsystem. 
1 Gbit/s

#3 Informations about my windows system: (Truncate Error with reading/writing files on the drive):
AMD Ryzen1800x
32 GB Ram
M2 SSD
200 MBit/s

Any idea which options i can try for streaming from linux and using my crypted rClone drive over windows for moving files on it ?

Best Regards

**Comment by ncw** [comment]
> I think the main problem is the cache option on my systems. On Windows i get always the errors your can see above.

Can you tell me what you are doing to get those errors on windows?

The error is telling you to use `--vfs-cache-mode` which I should probably change to make clearer.

via email you said
> The thing with `--vfs-cache-mode writes`
> 
> I already tried this, but then it is reading the full file first into my pc and it copy the full file in the vfs folder. This is not a good way i think cause it use a lot of writs on my M2. 

In order to debug this I need to be able to reproduce the problem - can you give me a simple sequence of commands on Windows I can replicate the problem with?

It would be helpful if you run with `-vv` and post more of the log so I can see what lead up to the errors.

**Comment by rodeoric** [comment]
Hello, 

right now i am fighting with linux, since i setup a new g drive nothing is working anymore. 

I use the same mounting command for all my gdrives like i said on the upper comment. 

But i always get this errors now. I never ever had such a long log just if something failed i got a message in command lock but now i got hundreds of messages with the same informations. I cant upload anything right now, i was waiting over 24 hours to be sure it is not ratelimited problem. 

https://drive.google.com/uc?id=1Vi1ZwrZ75BFMIuU2Wa5kJDUTdMKi1FFI

I tried it with --vfs-cache-mode writes , when i try to upload something with one of the 2 cache modes, nothing is working, it is uploading to 100% but saving nothing on drive. It is just crazy, i dont understand why this happens ....

Any idea ncw ? Like i told you in my mail a solution, could you fix this ?

**Comment by ncw** [comment]
> I tried it with --vfs-cache-mode writes , when i try to upload something with one of the 2 cache modes, nothing is working, it is uploading to 100% but saving nothing on drive. It is just crazy, i dont understand why this happens ....

Can you send a log with `-vv` of that happening please.  Use the `--log-file rclone.log` to send it to a file.

**Comment by rodeoric** [comment]
Hello, 

i will try this as soon as possible. My first try failed, it was generating a log file with hundreds of magebyte just for uploading 1 single file with around 20 gb.

**Comment by rodeoric** [comment]
Hello, 

here is the logi on GDrive, you need to Download it cause it is rly rly huge. But the errors are inside so i think you can do something with it. I use UltraEdit top open this big file. 

https://drive.google.com/open?id=156YwKhxAXQxmx1WJ1QyX0ZMSPBil5mzz

Best Regards

**Comment by ncw** [comment]
Thanks for the log.

I think the problem is caused by this

```
2018/02/04 22:55:04 ERROR : file.mkv: WriteFileHandle.New Rcat failed: googleapi: Error 403: Rate Limit Exceeded, rateLimitExceeded
```

Which means a failed upload.

Whatever it is doing the uploading then tries to seek to retry and gets this error

```
2018/02/04 22:55:04 ERROR : file.mkv: WriteFileHandle.Write: can't seek in file without --vfs-cache-mode >= writes
```

Unfortunately uploads without `--vfs-cache-mode writes` can't be retried so it means they will just fail.

I suggest you use `--vfs-cache-mode writes` which will use more disk IO on your local system.  I don't think you'll get it to work reliably without it though.

**Comment by rodeoric** [comment]
Hm, thank you for your response. 

Which mounting command would you use in my position ?

**Comment by rodeoric** [comment]
Hello 24 days no response,

i think you dont care about. So i doppred it. My 0,3 BTC Donation i will spend on a another way. 

Thank you anyway for your anwears before.

Thhis problem can be closed. Thx

**Comment by ncw** [comment]
Sorry for the delay in responding - there are a lot of issues on rclone!

It would be worth trying with [the latest beta](https://beta.rclone.org) as there have been lots of VFS fixes recently.

Questions about the best setup for things would be best directed to [the rclone forum](https://forum.rclone.org/) where you'll find lots of users who can advise you.
