### ISSUE TITLE
v1.2.4 doesn't compile with gccgo

### ISSUE THREAD

**Issue by felixonmars** [ncw/rclone#201]
v1.2.3 compiled without a problem here, but v1.2.4 fails with the following error:

```
# github.com/ncw/rclone/onedrive/api
.gopath/src/github.com/ncw/rclone/onedrive/api/types.go:74:29: error: reference to undefined field or method 'AppendFormat'
  out = (*time.Time)(t).UTC().AppendFormat(out, timeFormat)
                             ^
```

Looks like the method was added since Go 1.5, but current gccgo is still at go 1.4.2. Would it be possible to continue gccgo support in the current situation?

**Comment by ncw** [comment]
Yes, I'll fix that. Rclone is supporting go 1.3 to 1.5 at the moment. I didn't notice that the travis build had broken because of the OS X build failure :-( 

I wonder if travis  supports gccgo  ...
