### ISSUE TITLE
Cache VFS write and backend

### ISSUE THREAD

**Issue by JAC2703** [ncw/rclone#2012]
When filing an issue, please include the following information if possible as well as a description of the problem.  Make sure you test with the latest beta of rclone.

    https://beta.rclone.org/
    https://rclone.org/downloads/

If you've just got a question or aren't sure if you've found a bug then please use the [rclone forum](https://forum.rclone.org/) instead of filing an issue.

> What is your rclone version (eg output from `rclone -V`)
`rclone v1.39-045-ga80d8a21β
- os/arch: linux/amd64
- go version: go1.9.2`

Also tried the non-beta

> Which OS you are using and how many bits (eg Windows 7, 64 bit)
Linux, x64 (Ubuntu in LXC)

> Which cloud storage system are you using? (eg Google Drive)
Google Drive

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
`/bin/rclone mount --config=/root/.config/rclone/rclone.conf --allow-other --cache-writes --vfs-cache-mode=writes --cache-dir=/tmp/rclone/vfs --cache-db-path=/tmp/rclone/cache --dir-cache-time=3600m enc:/ /mnt/gdrive`

I have 3 remotes configured, google-drive -> cache backend -> crypt - with the final one being mounted.

It seems that when a file is opened for write on the mount point, it is first cached in the vfs cache directory. Perfect! In addition, when I open files for read they are cached by the back end cache. Perfect! I've added the `--cache-writes` switch in the hope that writes will be added to the back end cache. 

Now it sort of works... Using a 1GB file I've monitored the cache directories and noticed that the data is first moved to the vfs cache directory, very soon after it's added to the cache-backend directory (it takes a few seconds to populate, I presume because it's being chunked into (default) 5MB chunks). At this point I beleive the file is also being uploaded to the remote (Google Drive in this case). The data then disappears from the vfs cache path (as it should) but it also seems to be removed from the cache-backend directory. 

It looks like something isn't right - the vfs cache clear is causing the backend cache to remove it's data.

**Comment by ncw** [comment]
> Now it sort of works... Using a 1GB file I've monitored the cache directories and noticed that the data is first moved to the vfs cache directory, very soon after it's added to the cache-backend directory (it takes a few seconds to populate, I presume because it's being chunked into (default) 5MB chunks). At this point I beleive the file is also being uploaded to the remote (Google Drive in this case). The data then disappears from the vfs cache path (as it should) but it also seems to be removed from the cache-backend directory.

Everything except the `also seems to be removed from the cache-backend directory` seems to be working as it should.

@remusb thoughts?

**Comment by ncw** [comment]
Can you also try this without the cache remote in the picture, so `google-drive -> crypt` so we can narrow down the problem?

**Comment by remusb** [comment]
`--dir-cache-time=3600m`
What's your cache's `info_age`?

One thing I've noticed in the recent work I did is that a higher dir-cache-time than the cache backend time will make things go fuzzy. It looks like I've got rid of all the quirks I had in the tests by just making sure that `dir-cache-time` is lower than `info_age`.

Ultimately,  https://github.com/ncw/rclone/issues/1936 this will turn in a PR (I hope in the next day or so) which contains better handling for this.

**Comment by remusb** [comment]
@ncw is there a way for backends to signal back to the vfs cache dir to forget about a path?

**Comment by JAC2703** [comment]
@remusb I haven't set that myself, so the default of 6h.

**Comment by remusb** [comment]
@JAC2703 

Ok. Can you try the other way around? Make `--dir-cache-time` 5h for example? Or just leave it to its default (I believe 15m) if you don't have a specific need for it.

It really doesn't make sense to `--dir-cache-time` larger now that I think more about it. It's the first caching layer when using mount so if you set that higher than cache's info_age then it will prevent cache's expiration to work.

I might even add a warning about it when cache starts up if it detects this. (I already added a doc section for this)

**Comment by ncw** [comment]
@remusb wrote
> @ncw is there a way for backends to signal back to the vfs cache dir to forget about a path? (couldn't find one)

The way of doing it is using `fs.DirChangeNotify` and returning paths of directories that you wish the VFS to forget.

**Comment by JAC2703** [comment]
@remusb 

With them both set to the same, the behavior is the same (cache is still cleared).
`--dir-cache-time=3600m --cache-info-age=3600m`

And the same again when `--dir-cache-time` is less than `--cache-info-age` 
`--dir-cache-time=3500m --cache-info-age=3600m`

I saw a recent commit around a temp upload path switch indicating things are uploaded in the background after a set time. Any idea when that will make BETA? It sounds ideal for what I'm after :)

**Comment by remusb** [comment]
@JAC2703 `--vfs-cache-mode=writes` ok, I see. I actually never tried playing with the other options of the VFS caching layer. I need to start tinkering with this. I expect the cache tests to run in to the issue you mentioned. 

As for the background upload, it should already be in a beta. Try the latest or the direct one: https://beta.rclone.org/v1.39-093-g40af98b0/
Make sure to read the doc changes too: https://github.com/ncw/rclone/blob/master/docs/content/cache.md#offline-uploading
I need to write a forum post about it soon

I'm taking this issue as part of cache to get back to it and run the tests on the `--vfs-cache-mode=writes` mode.

**Comment by JAC2703** [comment]
@remusb great, thanks! If you need anything further, give me a shout. 

Re beta 093 - it seems that only Windows binaries are built? 

I've already seen the docs in the commit notes - it seems to do exactly what I'm after - I'm actually trying to use the `--vfs-cache-mode=writes` to be an upload cache so what you're building is going to be perfect and will remove my need got vfs-cache!

**Comment by remusb** [comment]
Hmm yeah, not sure why only those are built. This is a recent fix for another issue but has the same features in it: https://beta.rclone.org/v1.39-099-gb3d8b7e2/

**Comment by JAC2703** [comment]
Thanks - this behavies strangly with `--cache-writes` in that nothing seems to end up in the `--cache-tmp-upload-path` directory, but it does end up in the `--cache-db-path` directories.

I guess I shouldn't really be using the `--cache-writes`? I think I want to though, as although it's duplication for a time they are different caches. For example when the upload completes (after the specified time) it's deleted, however I may still need to cache it as part of the main cache - if that makes any sense at all?! ;)

**Comment by remusb** [comment]
Let's move this discussion here: https://github.com/ncw/rclone/issues/1936

**Comment by remusb** [comment]
Back to the original issue. I'm trying to write a test to verify this behaviour. So far, nothing. Is this still happening with the latest beta (the ones that you downloaded for temp uploads)? It's sadly impossible for me to go back to 1.39 with the refactored test cases.

@JAC2703

**Comment by remusb** [comment]
We're passed quite a few releases and this area was heavily refactored so I'm going to close this issue
