### ISSUE TITLE
Unable to use onedrive business, error occurred

### ISSUE THREAD

**Issue by gh0o0st** [ncw/rclone#2013]
When filing an issue, please include the following information if possible as well as a description of the problem.  Make sure you test with the latest beta of rclone.

    https://beta.rclone.org/
    https://rclone.org/downloads/

If you've just got a question or aren't sure if you've found a bug then please use the [rclone forum](https://forum.rclone.org/) instead of filing an issue.

> What is your rclone version (eg output from `rclone -V`)

rclone v1.39
- os/arch: darwin/amd64
- go version: go1.9.2

> Which OS you are using and how many bits (eg Windows 7, 64 bit)

macOS High Sierra 10.13.3

> Which cloud storage system are you using? (eg Google Drive)

onedrive business

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

rclone authorize "onedrive"

> A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

~$ rclone authorize "onedrive" -vv

2018/01/25 15:07:33 DEBUG : rclone: Version "v1.39" starting with parameters ["rclone" "authorize" "onedrive" "-vv"]
Choose OneDrive account type?
 * Say b for a OneDrive business account
 * Say p for a personal OneDrive account
b) Business
p) Personal
b/p> b
2018/01/25 15:07:37 DEBUG : Starting auth server on 127.0.0.1:53682
If your browser doesn't open automatically go to the following link: http://127.0.0.1:53682/auth
Log in and authorize rclone for access
Waiting for code...
2018/01/25 15:07:50 DEBUG : Received request on auth server
2018/01/25 15:07:50 DEBUG : No code found on request
2018/01/25 15:07:50 DEBUG : Closing auth server
2018/01/25 15:07:50 Failed to configure token: failed to get code

the URL has some useful information:
> http://localhost:53682/?error=access_denied&error_description=AADSTS65005%3a+Using+application+%27rclone%27+is+currently+not+supported+for+your+organization+domain.com+because+it+is+in+an+unmanaged+state.+An+administrator+needs+to+claim+ownership+of+the+company+by+DNS+validation+of+domain.com+before+the+application+rclone+can+be+provisioned.%0d%0aTrace+ID%3a+c553ca1b-2a85-4e5b-b6d3-5bfd911c0700%0d%0aCorrelation+ID%3a+883784c6-4ff4-40a7-9e3c-f1cb827ae32b%0d%0aTimestamp%3a+2018-01-25+06%3a59%3a44Z&state=3d1c48224432ec82ae40d4d48b54982b

I decode it to the following for easy to read
> http://localhost:53682/?error=access_denied&error_description=AADSTS65005: Using application 'rclone' is currently not supported for your organization domain.com because it is in an unmanaged state. An administrator needs to claim ownership of the company by DNS validation of domain.com before the application rclone can be provisioned.
> Trace ID: c553ca1b-2a85-4e5b-b6d3-5bfd911c0700
> Correlation ID: 883784c6-4ff4-40a7-9e3c-f1cb827ae32b
> Timestamp: 2018-01-25 06:59:44Z&state=3d1c48224432ec82ae40d4d48b54982b

Is there a way that can fix this?

**Comment by olihey** [comment]
@gh0o0st Please look at #1975

**Comment by gh0o0st** [comment]
thank you, I saw that too. Seems I can't use it then
