### ISSUE TITLE
rclone does not refresh Swift authentication token

### ISSUE THREAD

**Issue by vkukk** [ncw/rclone#2018]
rclone v1.39
- os/arch: linux/amd64
- go version: go1.9.2

CentOS 6 64b

We have some long running sync jobs between different Swift providers. Syncing over million files. At some point we start getting 401s, token has expired. Shouldn't rclone refresh token? Because when server provides token, it will also provide expiry time and rclone could use that to refresh token, not just keep blindly retrying on 401.

**Comment by vkukk** [comment]
Repeating strange error message appears just after token expires:
2018/01/26 07:00:05 ERROR : Data/Contents/Content_7124/Screenshots/NormalWithZip/6bad0dac8ca94f4797da77b9e6159ece.jpg: Failed to calculate dst hash: Head /assets/Data/Contents/Content_7124/Screenshots/NormalWithZip/6bad0dac8ca
94f4797da77b9e6159ece.jpg: unsupported protocol scheme ""

What is this unsupported protocol scheme "" ?

**Comment by ncw** [comment]
> We have some long running sync jobs between different Swift providers. Syncing over million files. At some point we start getting 401s, token has expired. Shouldn't rclone refresh token?

rclone should refresh the token at that point.  Does it?

Here is the code in the swift libary rclone uses: https://github.com/ncw/swift/blob/master/swift.go#L665

Possibly related to: http://tracker.ceph.com/issues/22223 which I have seen personally if you are getting 403s not 401s.

> Because when server provides token, it will also provide expiry time and rclone could use that to refresh token, not just keep blindly retrying on 401.

v1 auth doesn't provide the expiry, but v2 and v3 auth do so that is a good idea.  It would work around that CEPH bug anyway

**Comment by ncw** [comment]
Can you try this beta - I think it will fix the problem.

https://pub.rclone.org/v1.39-143-gb1945d00%CE%B2/

**Comment by ncw** [comment]
I've applied this fix to master now - please re-open if it doesn't fix the problem - thanks.

**Comment by vkukk** [comment]
I've tested beta, it ran successfully after known token expiry time of 8 hours. Nothing is printed into log even in DEBUG mode, but it's working, not getting 401-s, so i think, this has been resolved.

Thank you!

**Comment by ncw** [comment]
Thanks for testing 😁
