### ISSUE TITLE
rclone not using App settings for dropbox

### ISSUE THREAD

**Issue by iwxfer** [ncw/rclone#2028]
Problem with rclone v1.39, not using App settings `app_key` nor `app_secret`. I created an app and trying to test for different **dropbox** clients. However, rclone only uses **rclone** default app for genrating authentication `access_token`

That is what rclone does:
![2018-01-29 11-28-09 dropbox - mozilla firefox](https://i.imgur.com/sD6NI4D.png)

I generated token within the dropbox admin as app owner. It worked fine changing rclone config file manually with the `access_token`.
![2018-01-29 11-30-17 dropbox - google chrome](https://user-images.githubusercontent.com/642371/35521513-ee7bd030-04e7-11e8-922d-0d335770d830.png)

**Comment by ncw** [comment]
I see the problem...  The names of the config items should be `client_id` and `client_secret`.

Try this

https://beta.rclone.org/v1.39-091-g1852a0e0/ (uploaded in 15-30 mins)

And if it doesn't work, re-open the issue - thanks!
