### ISSUE TITLE
Blackblaze b2 backup is stalled

### ISSUE THREAD

**Issue by tabacha** [ncw/rclone#2029]
When filing an issue, please include the following information if possible as well as a description of the problem.  Make sure you test with the latest beta of rclone.

    https://beta.rclone.org/
    https://rclone.org/downloads/

If you've just got a question or aren't sure if you've found a bug then please use the [rclone forum](https://forum.rclone.org/) instead of filing an issue.

> What is your rclone version (eg output from `rclone -V`)
( https://downloads.rclone.org/rclone-v1.39-freebsd-amd64.zip )

rclone v1.39
- os/arch: freebsd/amd64
- go version: go1.9.2

> Which OS you are using and how many bits (eg Windows 7, 64 bit)

A Freebsd Jail in a freenas system. 64 bits.

> Which cloud storage system are you using? (eg Google Drive)

blackblaze b2

with crypt

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

rclone-v1.39-freebsd-amd64/rclone sync -vv --log-file=rclone2.log --skip-links --transfers 1 --bwlimit 1500K /mnt/backup/ crypt:

> A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

https://anders.hamburg/tmp/rclone2.log

I have first tried with more --transfers 10 and then with --transfers 2 . After an hour there are only big files to sync left and all files are stalled.

**Comment by tabacha** [comment]
Same result with the latest beta:
rclone v1.39-045-ga80d8a21β
- os/arch: freebsd/amd64
- go version: go1.9.2


The end of the log looks like:
2018/01/29 18:48:20 INFO  : 
Transferred:   85.188 MBytes (1.364 MBytes/s)
Errors:                 0
Checks:               570
Transferred:            0
Elapsed time:      1m2.4s
Transferring:
 *               potter/spucki-2015-07-07.tar.gz:  3% /2.103G, 1.472M/s, 23m25s

2018/01/29 18:48:28 DEBUG : potter/spucki-2015-07-07.tar.gz.bin: Sending chunk 1 length 100663296
2018/01/29 18:48:28 DEBUG : potter/spucki-2015-07-07.tar.gz.bin: Didn't find object to account part transfer
2018/01/29 18:49:20 INFO  : 
Transferred:    96 MBytes (802.896 kBytes/s)
Errors:                 0
Checks:               570
Transferred:            0
Elapsed time:      2m2.4s
Transferring:
 *               potter/spucki-2015-07-07.tar.gz:  4% /2.103G, 47.927k/s, 12h12m47s

2018/01/29 18:50:20 INFO  : 
Transferred:    96 MBytes (538.821 kBytes/s)
Errors:                 0
Checks:               570
Transferred:            0
Elapsed time:      3m2.4s
Transferring:
 *               potter/spucki-2015-07-07.tar.gz:  4% /2.103G, 897/s, 667h48m30s

2018/01/29 18:51:20 INFO  : 
Transferred:    96 MBytes (405.472 kBytes/s)
Errors:                 0
Checks:               570
Transferred:            0
Elapsed time:      4m2.4s
Transferring:
 *               potter/spucki-2015-07-07.tar.gz:  4% /2.103G, 16/s, 36515h11m35s

2018/01/29 18:52:20 INFO  : 
Transferred:    96 MBytes (325.038 kBytes/s)
Errors:                 0
Checks:               570
Transferred:            0
Elapsed time:      5m2.4s
Transferring:
 *               potter/spucki-2015-07-07.tar.gz:  4% /2.103G, 0/s, 1996619h43m33s

**Comment by ncw** [comment]
Can you try without the `--bwlimit` option and see if that is causing the problem?

**Comment by tabacha** [comment]
I have left the last process with version ( v1.39-045-ga80d8a21β) doining his job over night. But with bandwith limit. After a while it continue to upload the file. The whole file was fineshed at 21:14:00

>  2018/01/29 21:13:20 INFO  :
>  Transferred:   2.103 GBytes (251.705 kBytes/s)
>  Errors:                 0
>  Checks:               570
>  Transferred:            0
>  Elapsed time:   2h26m2.4s
>  Transferring:
>   *               potter/spucki-2015-07-07.tar.gz: 100% /2.103G, 1.421k/s, 0s
>  2018/01/29 21:14:00 DEBUG : potter/spucki-2015-07-07.tar.gz.bin: Done sending chunk 23
>  2018/01/29 21:14:00 DEBUG : potter/spucki-2015-07-07.tar.gz.bin: Finishing large file upload with 23 parts
>  2018/01/29 21:14:06 INFO  : potter/spucki-2015-07-07.tar.gz: Copied (new)
> 

Full logile:

https://anders.hamburg/tmp/rclone3.log

I did not see any big upload in the network graph, and I see no big cpu peaks.

Other messages which looks not okay for me (from the log above):

> 2018/01/29 23:12:15 DEBUG : potter/home/elke.tar.gz.bin: Clearing part upload URL because of error: Not enough members for write of 4_z1e714498a9c0450e6d1b0918_f314a4e543fd397a6_d20180129_m212637_c000_v0001058_t0014: neighbor_down; neighbor_down (500 internal_error)
> 2018/01/29 23:12:15 DEBUG : pacer: Rate limited, increasing sleep to 20ms
> 2018/01/29 23:12:15 DEBUG : pacer: low level retry 1/10 (error Not enough members for write of 4_z1e714498a9c0450e6d1b0918_f314a4e543fd397a6_d20180129_m212637_c000_v0001058_t0014: neighbor_down; neighbor_down (500 internal_error))
> 2018/01/29 23:12:15 DEBUG : potter/home/elke.tar.gz.bin: Sending chunk 2 length 100663296
> 2018/01/29 23:12:16 DEBUG : pacer: Reducing sleep to 10ms
> 2018/01/29 23:12:16 DEBUG : potter/home/elke.tar.gz.bin: Didn't find object to account part transfer
>

**Comment by tabacha** [comment]
I have started process again without bandwith option and with default transfer.
Still the same:

> 2018/01/30 09:31:04 INFO  :
> Transferred:   422.199 MBytes (449.074 kBytes/s)
> Errors:                 0
> Checks:               586
> Transferred:           91
> Elapsed time:     16m2.7s
> Transferring:
>  *         merlin/opt/revengeofthetitans/gfx.jar:  0% /196.007M, 0/s, -
>  *   ...-sensation-kartentransfer20120823.tar.gz:  0% /6.102G, 0/s, -
>  *   ...erlin/root/OVM_EL5U5_X86_64_PVM_10GB.tgz:  0% /685.880M, 0/s, -
>  *   ...root/2017-01-11-raspbian-jessie-lite.img: 28% /1.295G, 0/s, 0s
> 
> 2018/01/30 09:32:04 INFO  :
> Transferred:   422.199 MBytes (422.729 kBytes/s)
> Errors:                 0
> Checks:               586
> Transferred:           91
> Elapsed time:     17m2.7s
> Transferring:
>  *         merlin/opt/revengeofthetitans/gfx.jar:  0% /196.007M, 0/s, -
>  *   ...-sensation-kartentransfer20120823.tar.gz:  0% /6.102G, 0/s, -
>  *   ...erlin/root/OVM_EL5U5_X86_64_PVM_10GB.tgz:  0% /685.880M, 0/s, -
>  *   ...root/2017-01-11-raspbian-jessie-lite.img: 28% /1.295G, 0/s, 0s
> 
> 2018/01/30 09:33:04 INFO  :
> Transferred:   422.199 MBytes (399.301 kBytes/s)
> Errors:                 0
> Checks:               586
> Transferred:           91
> Elapsed time:     18m2.7s
> Transferring:
>  *         merlin/opt/revengeofthetitans/gfx.jar:  0% /196.007M, 0/s, -
>  *   ...-sensation-kartentransfer20120823.tar.gz:  0% /6.102G, 0/s, -
>  *   ...erlin/root/OVM_EL5U5_X86_64_PVM_10GB.tgz:  0% /685.880M, 0/s, -
>  *   ...root/2017-01-11-raspbian-jessie-lite.img: 28% /1.295G, 0/s, 0s
> 
> 2018/01/30 09:34:04 INFO  :
> Transferred:   422.199 MBytes (378.336 kBytes/s)
> Errors:                 0
> Checks:               586
> Transferred:           91
> Elapsed time:     19m2.7s
> Transferring:
>  *         merlin/opt/revengeofthetitans/gfx.jar:  0% /196.007M, 0/s, -
>  *   ...-sensation-kartentransfer20120823.tar.gz:  0% /6.102G, 0/s, -
>  *   ...erlin/root/OVM_EL5U5_X86_64_PVM_10GB.tgz:  0% /685.880M, 0/s, -
>  *   ...root/2017-01-11-raspbian-jessie-lite.img: 28% /1.295G, 0/s, 0s
> 
> 2018/01/30 09:35:04 INFO  :
> Transferred:   422.199 MBytes (359.462 kBytes/s)
> Errors:                 0
> Checks:               586
> Transferred:           91
> Elapsed time:     20m2.7s
> Transferring:
>  *         merlin/opt/revengeofthetitans/gfx.jar:  0% /196.007M, 0/s, -
>  *   ...-sensation-kartentransfer20120823.tar.gz:  0% /6.102G, 0/s, -
>  *   ...erlin/root/OVM_EL5U5_X86_64_PVM_10GB.tgz:  0% /685.880M, 0/s, -
>  *   ...root/2017-01-11-raspbian-jessie-lite.img: 28% /1.295G, 0/s, 0s
> 

Output of top:

> last pid: 26716;  load averages:  0.68,  0.57,  0.36  up 9+14:17:06    09:38:55
> 13 processes:  1 running, 12 sleeping
> CPU:  0.6% user,  0.0% nice,  1.2% system,  0.0% interrupt, 98.2% idle
> Mem: 153M Active, 183M Inact, 6216M Wired, 227M Free
> ARC: 4859M Total, 2641M MFU, 1664M MRU, 4932K Anon, 120M Header, 429M Other
> Swap: 2048M Total, 277M Used, 1771M Free, 13% Inuse
> 
>   PID USERNAME    THR PRI NICE   SIZE    RES STATE   C   TIME    WCPU COMMAND
> 23811 root          9  22    0   495M   483M uwait   1   0:26   1.35% rclone
> 26691 root          1  20    0 20120K  2388K CPU1    1   0:00   0.02% top
> 71777 root          1  20    0 42668K   964K kqread  0   0:01   0.00% master
> 82477 root          1  20    0 10472K  1108K select  1   0:01   0.00% syslogd
> 82657 root          1  20    0 12564K   516K nanslp  1   0:01   0.00% cron
> 71779 postfix       1  20    0 44780K  1484K kqread  0   0:01   0.00% qmgr
>  5348 root          1  20    0 26624K  4136K select  0   0:00   0.00% tmux
>  5349 root          1  20    0 19600K  2120K pause   1   0:00   0.00% csh
> 22025 root          1  20    0 19676K  3344K pause   0   0:00   0.00% tcsh
> 17688 postfix       1  20    0 44728K  6120K kqread  1   0:00   0.00% pickup
> 85463 root          1  20    0 55676K  1820K select  1   0:00   0.00% sshd
> 89970 root          1  52    0  6244K  1488K nanslp  1   0:00   0.00% sleep
> 89967 root          1  52    0 13144K  2080K wait    1   0:00   0.00% sh
>

**Comment by ncw** [comment]
> I have started process again without bandwith option and with default transfer.

thanks for trying that.

I was just looking through your rclone3.log and I saw this

    2018/01/30 03:32:07 DEBUG : potter/home/finja.tar.gz.bin: Didn't find object to account part transfer

I think that must be happening because of crypt...

Can you try transferring some large files without crypt?  It shouldn't give that message and I'd like to see if that improves things for you.

Thanks

**Comment by tabacha** [comment]
> Can you try transferring some large files without crypt? It shouldn't give that message and I'd like to see if that improves things for you.

Yes, the message is not there. 

Also the timeing is what is expect:
>2018/01/30 13:51:57 DEBUG : kubuntu-12.04-desktop-i386.iso: Done sending chunk 1
2018/01/30 13:51:57 DEBUG : kubuntu-12.04-desktop-i386.iso: Sending chunk 6 length 100663296
2018/01/30 13:52:05 DEBUG : kubuntu-12.04-desktop-i386.iso: Done sending chunk 3
2018/01/30 13:52:06 DEBUG : kubuntu-12.04-desktop-i386.iso: Sending chunk 7 length 100663296

Logfile: 
https://anders.hamburg/tmp/rclone-copy-no-crypt.log

versus:

>2018/01/30 08:54:31 DEBUG : merlin/root/2017-01-11-raspbian-jessie-lite.img.bin: Done sending chunk 6
2018/01/30 08:55:20 INFO  :
Transferred:   4.477 GBytes (92.269 kBytes/s)
Errors:                 0
Checks:               585
Transferred:            7
Elapsed time:   14h8m2.4s
Transferring:
> *   ...root/2017-01-11-raspbian-jessie-lite.img: 48% /1.295G, 1.409M/s, 8m1s
>
>2018/01/30 08:55:36 DEBUG : merlin/root/2017-01-11-raspbian-jessie-lite.img.bin: Sending chunk 7 length 100663296
>2018/01/30 08:55:36 DEBUG : merlin/root/2017-01-11-raspbian-jessie-lite.img.bin: Didn't find object to account part transfer

**Comment by ncw** [comment]
Oh, I see what is going on...

Because of this message "Didn't find object to account part transfer" the code is accounting the reading of data into the b2 buffer instead of when it is sent like it is supposed to.

What you should find is the big files that appear stalled actually complete fine.  That message means we are reverting to the original behaviour in #602

It is clear to me that I need to fix this a different way - the fix in #1443 would fix this too I think

**Comment by tabacha** [comment]
Great that you found the bug. Thank you for your work. Do you need the logfiles on my webserver anymore?

**Comment by ncw** [comment]
>  Do you need the logfiles on my webserver anymore?

You can remove them now - thanks

**Comment by ncw** [comment]
I have fixed this here (hopefully!)  Please test and if it doesn't work then let me know on this issue!

Thanks

https://beta.rclone.org/v1.39-120-g82418c30/ (uploaded in 15-30 mins)

**Comment by tabacha** [comment]
Hi, there is only a Windows version of rclone in this directory. But I need a freebsd version to test.

**Comment by ncw** [comment]
I gave the builder a kick and it is now uploaded.
