### ISSUE TITLE
Copying large >10GB file from ACD fails

### ISSUE THREAD

**Issue by alexzeitgeist** [ncw/rclone#204]
Hello,

I have successfully synced content from Amazon Cloud Drive to Google Drive. Except for one large file which failed to copy. The file is ~11GB in size. Google Drive has sufficient storage available. This is what I'm getting:

```
rclone copy -v acd:/Videos/Raw/footage.m2ts drive:/Videos/Raw/              
.
2015/11/08 19:52:25 footage.m2ts: Failed to open: HTTP code 400: "400 Bad Request", reponse body: <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InvalidArgument</Code><Message>Only one auth mechanism allowed; only the X-Amz-Algorithm query parameter, Signature query string parameter or the Authorization header should be specified</Message><ArgumentName>Authorization</ArgumentName>
...
</Error>
2015/11/08 19:52:25 Attempt 1/3 failed with 1 errors
```

Before I successfully syncronized/copied around 300 GB of data without problem. It only failed on this file, which is also the only file that large (others are < 4GB).

I then tried copying the file from ACD to local instead, but got the same error. Downloading it via Amazon Cloud Drive Web gui works without problem.

rclone v1.24 (linux 64bit) used.

Cheers
Alex

**Comment by ncw** [comment]
The error message is an S3 error message.  Presumably ACD is based on S3, but I don't think it should be exposing S3 error messages, which makes me wonder whether this is an ACD problem.

I'm pretty sure the web gui uses a different API to the one used by rclone since it can, for example, delete files permanently which the published API can't.

Tomorrow I'll try a 10 GB file myself and see what happens.

Any thoughts @klauspost  ?

**Comment by alexzeitgeist** [comment]
@ncw good point about the web gui using a different method to access ACD.

Tested the download with another tool, acd_cli, and it worked.

```
$ docker-acdcli -v dl /Videos/Raw/footage.m2ts 
15-11-09 07:34:46.087 [INFO] [acd_cli] - Plugin leaf classes: TestPlugin
15-11-09 07:34:46.087 [INFO] [acd_cli] - TestPlugin attached.
15-11-09 07:34:46.087 [INFO] [acdcli.api.client] - Initializing ACD with path "/home/user/.cache/acd_cli".
15-11-09 07:34:46.087 [INFO] [acdcli.api.oauth] - AppspotOAuthHandler initialized
15-11-09 07:34:46.088 [INFO] [acdcli.cache.db] - Initializing cache with path "/home/user/.cache/acd_cli".
15-11-09 07:34:46.302 [INFO] [acdcli.cache.db] - Cache is initialized.
15-11-09 07:34:46.305 [INFO] [acdcli.cache.db] - DB schema version is 1.
15-11-09 07:34:46.327 [INFO] [acd_cli] - Last sync at 2015-11-09 07:30:24.625790.
15-11-09 07:34:46.413 [INFO] [acd_cli] - Resolved "/Videos/Raw/footage.m2ts" to "nDMe3qnFM1OgAiUXNpMFoq"
15-11-09 07:34:46.416 [INFO] [acdcli.utils.threading] - 1 jobs in queue.
15-11-09 07:34:46.421 [INFO] [acd_cli] - Downloading "footage.m2ts"
15-11-09 07:34:46.422 [INFO] [acdcli.api.backoff_req] - GET "https://content-na.drive.amazonaws.com/cdproxy/nodes/nDMe3qnFM1OgAiUXNpMFoq/content"
15-11-09 07:34:46.428 [INFO] [requests.packages.urllib3.connectionpool] - Starting new HTTPS connection (1): content-na.drive.amazonaws.com
15-11-09 07:34:47.024 [INFO] [requests.packages.urllib3.connectionpool] - Starting new HTTPS connection (1): cd-na-prod-content.s3.amazonaws.com

... download is starting ...
```

Interestingly, there is a [resolved issue](https://github.com/yadayada/acd_cli/issues/8) for acd_cli concering files larger than 10GB, with Amazon support acknowledging that there was an issue with downloading larger files. The current ["official" maximum file size](https://forums.developer.amazon.com/forums/thread.jspa?threadID=4610) for ACD is 50GB btw.

Anyhow, what's interesting is that the download of said file works with acd_cli. They have a [git commit](https://github.com/yadayada/acd_cli/commit/8cd8bd950b167160a42c98781153dc4bf3731a72) designated as a workaround for large files involving chunked/ranged downloads (in content.py).

**Comment by ncw** [comment]
Unfortunately I can't upload a >10GB file as I only have 10GB of quota :-(

**Comment by alexzeitgeist** [comment]
@ncw no problem. I used the --dump-bodies flag to get find more information where things might wrong.

The 11GB file was uploaded with Cloud Drive Desktop. Here is the associated JSON-encoded metadata (with some IDs removed for privacy reasons):

```
{"data":[{"eTagResponse":"cJwi8ziqd8I","id":"<removed>","kind":"FILE","version":3,"labels":[],"contentProperties":{"extension":"m2ts","size":11956715520,"contentType":"application/octet-stream","version":1,"md5":"28909758cf5ef75fc8cfc2a58b2b9317"},"createdDate":"2015-08-30T12:53:49.238Z","createdBy":"CloudDriveDesktop","restricted":false,"modifiedDate":"2015-08-30T22:14:45.746Z","name":"footage.m2ts","isShared":false,"parents":["<removed>"],"status":"AVAILABLE"}],"count":1}
```

In comparison, here the metadata from another file that was uploaded through a third party app using the ACD api:

```
{"data":[{"eTagResponse":"VaSg_YDsTa4","id":"<removed>","kind":"FILE","version":2,"labels":[],"contentProperties":{"extension":"cmuprops","size":80140,"contentType":"application/xml","version":1,"md5":"0fbab9ecbbdc9ade6d07712348600eeb"},"createdDate":"2015-08-29T10:17:02.889Z","createdBy":"SyncBackPro","restricted":false,"modifiedDate":"2015-08-29T10:17:03.201Z","name":"footage.cmuprops","isShared":false,"parents":["<removed>"],"status":"AVAILABLE"}],"count":1}
```

Notice how it shows different fields for "version"? Anyhow, in the next step, when rclone requests the 11GB file with GET /cdproxy/nodes/<removedid>/content HTTP/1.1, it receives the following response.

```
2015/11/09 16:38:11 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2015/11/09 16:38:12 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2015/11/09 16:38:12 HTTP RESPONSE
2015/11/09 16:38:12 HTTP/1.1 302 Found
Connection: keep-alive
Date: Mon, 09 Nov 2015 15:38:12 GMT
Location: https://cd-na-prod-content.s3.amazonaws.com/idremoved?response-content-disposition=attachment%3B%20filename%3D%22footage.m2ts%22&response-content-type=application%2Foctet-stream&x-amz-security-token=<token>&AWSAccessKeyId=<accesskeyid>&Expires=1447083792&Signature=<signature>
Server: Amazon-Cloud-Drive
X-Amzn-Requestid: <requestid>
Content-Length: 0
```

This is different from a normal response which looks like this:

```
2015/11/09 16:42:14 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2015/11/09 16:42:15 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2015/11/09 16:42:15 HTTP RESPONSE
2015/11/09 16:42:15 HTTP/1.1 200 OK
Content-Length: 80140
Cache-Control: public, max-age=7200
Connection: keep-alive
Content-Disposition: attachment; filename=footage.cmuprops
Content-Type: application/xml
Date: Mon, 09 Nov 2015 15:42:15 GMT
Etag: "0fbab9ecbbdc9ade6d07712348600eeb"
Server: Amazon-Cloud-Drive
X-Amzn-Requestid: <requestid>

<the actual file content>
```

So when rclone receives the 302 redirect in the case of the 11GB file, it makes another request query that looks like this:

```
GET /<removedid>?response-content-disposition=attachment%3B%20filename%3D%22footage.m2ts%22&response-content-type=application%2Foctet-stream&x-amz-security-token=<token>&AWSAccessKeyId=<accessid>&Expires=1447083792&Signature=<signature> HTTP/1.1
Host: cd-na-prod-content.s3.amazonaws.com
```

Which then causes the HTTP/1.1 400 Bad Request error that we've already seen in my first post:

```
<Error><Code>InvalidArgument</Code><Message>Only one auth mechanism allowed; only the X-Amz-Algorithm query parameter, Signature query string parameter or the Authorization header should be specified</Message><ArgumentName>Authorization</ArgumentName><ArgumentValue>removed</ArgumentValue><RequestId>requestid</RequestId><HostId>hostid</HostId></Error>
```

Perhaps, if rclone was to strip out the query strings containing the S3-related information that it receives in the 302 redirect response, the error might disappear?

**Comment by ncw** [comment]
Excellent detective work - the error message now makes sense.

The redirected request is going to S3 - `cd-na-prod-content.s3.amazonaws.com`

S3 is getting auth info from the URL but rclone will be adding an `Authorization:` line with the oauth credentials for ACD also which is confusing it.

The best way to fix this is for rclone not to put in the `Authorization:` header if it detects that it has been redirected to S3, or maybe if there is `Signature` in the URL string.

I don't think stripping the query strings will work as then it will be sending ACD auth to S3.

I'm not quite sure how to code this though! Perhaps putting in a redirect policy which stops redirecting when it gets a 301 with a `Signature` in the URL.  The 301 would be returned to the client and it could then do another fetch using a non oauth client...  It might be that this can be fixed in the oauth transport. Needs a bit of thought.

**Comment by alexzeitgeist** [comment]
No problem, I am glad if I can help. Apparantly the version attribute in the node's metadata is incremented each time the content or metadata is modified; so it's unrelated here.

I did a quick look at how acd_cli processes the request (using the Python Requests library), and practically, it works because it drops the Authorization header (as you suggested) in the redirected request while keeping the S3 query string parameters intact. In fact, I couldn't see any logic in the code that would participate the redirect. Rather, it's the Python Requests library that by default drops authorization headers when you get redirected off-host. ;) If you are interested, there is some discussion related to this [over here](https://github.com/kennethreitz/requests/issues/627).

**Comment by ncw** [comment]
That link is very interesting.  It makes me wonder if the current behaviour is a bug in the [oauth library](https://github.com/golang/oauth2).  Will investigate further.

**Comment by alexzeitgeist** [comment]
Yes, the oauth library implements the http.RoundTripper interface in which they set the authentication header for [any http request](https://github.com/golang/oauth2/blob/038cb4adce85ed41e285c2e7cc6221a92bfa44aa/transport.go#L46).

I don't know if this can be considered a bug. Probably, if you assume that you ought to remove authentication headers when redirecting to a new host (RFC specs aren't clear about it, but consensus seems that you should remove them to prevent information leakage).

**Comment by JensMagnus** [comment]
Any news? This is still an issue with ACD and with files larger than 10GB.

**Comment by ncw** [comment]
Don't worry we haven't forgotten about it! We've been thinking about it ☺

**Comment by JensMagnus** [comment]
Glad to hear that. Is there an ETA?

**Comment by victor21813** [comment]
I have the same problem, anything good NEWS?

**Comment by ncw** [comment]
Hmm, I just had another look at this.  The error message from amazon has changed giving a 400 error message immediately.

This means that unfortunately I can't fix this in rclone.  It does mean that amazon is working on large file handling though which is good, but at the moment It looks like that files bigger than 10GB can't be downloaded by any means (including by the web site - which was working).

There is a [forum thread](https://www.amazon.com/gp/help/customer/forums/ref=cs_hc_g_pg_next?ie=UTF8&forumID=Fx1SKFFP8U1B6N5&cdThread=Tx3HYABOMJUH2PE&cdPage=2&cdSort=oldest) about this too.

```
2016/01/22 13:21:46 HTTP REQUEST
2016/01/22 13:21:46 GET /cdproxy/nodes/3e4ts-snip-Aw/content HTTP/1.1
Host: content-eu.drive.amazonaws.com
User-Agent: rclone/v1.26
Accept-Encoding: gzip
```

```
2016/01/22 13:21:46 HTTP RESPONSE
2016/01/22 13:21:46 HTTP/1.1 400 Bad Request
Content-Length: 46
Connection: keep-alive
Content-Type: application/vnd.error+json
Date: Fri, 22 Jan 2016 13:20:39 GMT
Server: Amazon-Cloud-Drive
X-Amzn-Requestid: 7cd83496-snip

{"message":"Currently unsupported file size."}
```

**Comment by ncw** [comment]
I found a moderately definitive statement from amazon on the [developers forum](https://forums.developer.amazon.com/forums/thread.jspa?threadID=8815&tstart=0) from Sep 11, 2015 

> Currently, there's a maximum download size of 10GB, so we don't recommend allowing uploads larger than this. However, the API has no upper restriction on upload file size. The download limitation should be removed in the future. 

I should probably put this in the docs...

**Comment by JensMagnus** [comment]
Just FYI you can download files larger than 10GB from their website: 
https://www.amazon.com/clouddrive

Although, you have to select each file and press download one at a time. You cannot download folders and the speed is absolutely shit.

**Comment by victor21813** [comment]
NO, it means past.
Amazon allow you to download your files!
I just download a 37GB file from Amazon cloud yesterday and finished!
I download completely with jdownloader 2 and no problem.
And try using chrome to download was fine too.(but I cancel it , afraid Internet corrupt)
If you want to confirm or test, I can send you a file link large than 10GB to try.

https://www.amazon.com/gp/help/customer/display.html?nodeId=201376660
This is for multi files download, more than 5GB or 1000 files can't be download.
But I can download one of them large than 5GB in single.

**Comment by ncw** [comment]
I tried downloading a 12GB file from the web interface and it failed right at the start (using chrome/linux).  It didn't give any sort of error message though I can see it made a "400 Bad request" in the javascript console, which agrees with my findings with rclone.

If you can send me a file link to test that would be very useful ( private email nick@craig-wood.com ).

I wonder if jdownloader is using a different mechanism for downloading - I'll try with it later.

**Comment by victor21813** [comment]
I send the email to you.
jdownloader is really good at download.
I can give it one Amazon cloud file link with lots of files include, and jdownloader can download them in the same time.
I think jdownloader download 1 file a time and 10 files do 10 times request.(Still single download)

**Comment by ncw** [comment]
@victor21813 thanks for the links - I've done some investigation and I think the thing to do for large files on amazon cloud drive would be to request a `tempLink` and download them without auth from that link.

[Getting file metadata section](https://developer.amazon.com/public/apis/experience/cloud-drive/content/nodes)

That should be a direct download from S3 which doesn't have any limits.

I haven't tried it yet though - I'll let you know how it goes!

**Comment by ncw** [comment]
I have fixed the download of files > 10GB using the tempLink approach.

Here is a beta for you all to try!

http://pub.rclone.org/v1.26-50-gd4df3f2%CE%B2/

Thanks for any feedback

Nick

**Comment by victor21813** [comment]
Thanks for this!
I am testing now and seems like pretty good.
It really help me a lot for copy files to another cloud.
I will keep testing it.
Thanks again.
