### ISSUE TITLE
--LOG-LEVEL=DEBUG no output

### ISSUE THREAD

**Issue by PiscisSwimeatus** [ncw/rclone#2043]
> What is your rclone version (eg output from `rclone -V`)
v1.39-104-ga6227f34β

> Which OS you are using and how many bits (eg Windows 7, 64 bit)
Ubuntu 16.04

--LOG-LEVEL=DEBUG no longer output any debug information.
-vv still works.

**Comment by ncw** [comment]
This must have got broken in the code reshuffle - well spotted @PiscisSwimeatus 

I'll take this one since I broke it!

**Comment by ncw** [comment]
Fixed!  Find it here

https://beta.rclone.org/v1.39-113-g6fb868e0/ (uploaded in 15-30 mins)

**Comment by PiscisSwimeatus** [comment]
Tested ok with 115, thanks
