### ISSUE TITLE
Offline uploading - checking functionality

### ISSUE THREAD

**Issue by daniel-loader** [ncw/rclone#2044]
When filing an issue, please include the following information if possible as well as a description of the problem.  Make sure you test with the latest beta of rclone.

    https://beta.rclone.org/
    https://rclone.org/downloads/

If you've just got a question or aren't sure if you've found a bug then please use the [rclone forum](https://forum.rclone.org/) instead of filing an issue.

> What is your rclone version (eg output from `rclone -V`)
- rclone v1.39-115-g8722403bβ    
      
> Which OS you are using and how many bits (eg Windows 7, 64 bit)
- os/arch: linux/amd64         
- go version: go1.9.3    

> Which cloud storage system are you using? (eg Google Drive)
- Google Drive

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
- rclone mount google-media-cached: /data/downloads/cloud --cache-tmp-upload--
path=/home/user/.cache/rclone/cache-upload --cache-chunk-no-memory --allow-other --vfs-cache-mode minimal -vv

> A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
- No log entries seem to pertain to question.

So reading the new documentation on the commit for this feature and running the latest beta I gave it a go, in a stress test of sorts - trying to torrent to the mount directly (may or may not be practical but felt it the best way to stress many reads and writes on file parts.)

The documentation implies it'll continue purging the cache-tmp-upload directory if the process or operating system is restarted (or cache flushes). I've restarted the mount as I was tweaking the chunk size and there's no upload activity and the cache-upload directory isn't shrinking every so often like it was prior to the process termination. 

The file (1 of 12 that didn't upload) is visible when `ls`ing in the mounted directory but missing from the remote when mounted in a different non cached directory.

So is this a bug? If so is there any logs/information I can provide to help?

**Comment by ncw** [comment]
@remusb thoughts?

**Comment by daniel-loader** [comment]
For extra clarification sighups don't interrupt the upload so that's
working as advertised. I've since flushed the upload directory and files on
Google drive to try again to see if I can replicate it. Figured if I can't
debug it the least I can do is confirm it happening under reproducible
situations.

**Comment by remusb** [comment]
Did you changed the root of the remote by any chance? 

Ultimately, a `-v` log would help to see if something got stuck. Though an error is reported in that case and would be visible without it.

**Comment by daniel-loader** [comment]
Mhmm no I just reran the same command to mount with a edited config to
change the chunk size from 5 to 10. It's yet to happen again since then
with multiple remounts. Could be related to altered chunk size?

**Comment by remusb** [comment]
It shouldn't affect the offline upload directly but changing the chunk size will most likely invalidate every cached data. I should add that in the docs really. But I understand you purged the cache which is correct to do when you change the chunk size.

It won't be hard to add such a test case though to see if there's any issue there.

**Comment by daniel-loader** [comment]
Okay so trying again I have behaviour where nothing uploads now.

I ran the following in the `/data/downloads/cloud/tmp` directory
```
wget http://www.jell.yfish.us/media/jellyfish-15-mbps-hd-h264.mkv
```
Logs here (just sits here and no new entries after a few minutes):

```
root@titanium:/data/downloads# rclone mount google-media-cached: /data/downloads/cloud --cache-tmp-upload-path=/home/user/.cache/rclone/cache-upload --cache-chunk-no-memory --cache-writes --allow-other --vfs-cache-mode minimal -v
2018/02/03 21:57:30 INFO  : google-media: Cache DB path: /home/user/.cache/rclone/cache-backend/google-media.db
2018/02/03 21:57:30 INFO  : google-media: Cache chunk path: /home/user/.cache/rclone/cache-backend/google-media
2018/02/03 21:57:30 INFO  : google-media: Chunk Memory: false
2018/02/03 21:57:30 INFO  : google-media: Chunk Size: 10M
2018/02/03 21:57:30 INFO  : google-media: Chunk Total Size: 4G
2018/02/03 21:57:30 INFO  : google-media: Chunk Clean Interval: 1m0s
2018/02/03 21:57:30 INFO  : google-media: Workers: 4
2018/02/03 21:57:30 INFO  : google-media: File Age: 3h0m0s
2018/02/03 21:57:30 INFO  : google-media: Cache Writes: enabled
2018/02/03 21:57:30 INFO  : google-media: Upload Temp Rest Time: 15m0s
2018/02/03 21:57:30 INFO  : google-media: Upload Temp FS: /home/user/.cache/rclone/cache-upload
2018/02/03 21:57:31 INFO  : google-media: Cache DB path: /home/user/.cache/rclone/cache-backend/google-media.db
2018/02/03 21:57:31 INFO  : google-media: Cache chunk path: /home/user/.cache/rclone/cache-backend/google-media
2018/02/03 21:57:31 INFO  : google-media: Chunk Memory: false
2018/02/03 21:57:31 INFO  : google-media: Chunk Size: 10M
2018/02/03 21:57:31 INFO  : google-media: Chunk Total Size: 4G
2018/02/03 21:57:31 INFO  : google-media: Chunk Clean Interval: 1m0s
2018/02/03 21:57:31 INFO  : google-media: Workers: 4
2018/02/03 21:57:31 INFO  : google-media: File Age: 3h0m0s
2018/02/03 21:57:31 INFO  : google-media: Cache Writes: enabled
2018/02/03 21:57:31 INFO  : google-media: Upload Temp Rest Time: 15m0s
2018/02/03 21:57:31 INFO  : google-media: Upload Temp FS: /home/spicypixel/.cache/rclone/cache-upload
2018/02/03 21:57:31 INFO  : Encrypted drive 'google-media-cached:': Modify window is 1ms
2018/02/03 21:57:31 NOTICE: Encrypted drive 'google-media-cached:': poll-interval is not supported by this remote
2018/02/03 21:58:10 INFO  : Cache remote google-media:: Clearing cache from signal
2018/02/03 21:58:10 INFO  : Cache remote google-media:: Clearing cache from signal
2018/02/03 21:58:49 INFO  : pae280o2b0tn4g0ld5j7kfsjts/bff4nqa2mea62mrm87859iml7mc8pnoaclrg8nng4fs7jkpg8uq0: put: uploaded in temp fs
2018/02/03 21:58:49 INFO  : pae280o2b0tn4g0ld5j7kfsjts/bff4nqa2mea62mrm87859iml7mc8pnoaclrg8nng4fs7jkpg8uq0: put: queued for upload
2018/02/03 21:58:49 INFO  : pae280o2b0tn4g0ld5j7kfsjts: put: cache expired

```

However, it's populated the cache:

```
# du /home/user/.cache/rclone/ -h --max-depth 1     
                                       
4.0K    ./vfs                          
54M     ./cache-upload                 
11M     ./cache-backend                
64M     .                              
```

Files show obviously when using `ls` in the directory, but aren't being copied to google.

**Comment by daniel-loader** [comment]
Think we can close this now, adjusting the timer to 2 mins seems to be a better value for me, you you anyway!

**Comment by remusb** [comment]
Oh right. https://github.com/ncw/rclone/blob/master/docs/content/cache.md#--cache-tmp-wait-timeduration
You can read about it here. 

The use case with this is not to accomplish real time read/write. That's something that VFS already achieves pretty great I think (haven't tested but read others using it).
My intention for this is to have files temporarily available locally for intensive reading (think torrenting as an example). After some time passes, those files will naturally lead to less reading and can be moved to the cloud provider.
