### ISSUE TITLE
Expiry date of credential pour hubic too short

### ISSUE THREAD

**Issue by webafrancois** [ncw/rclone#2047]
I use rclone to backup my data to hubic and every token get by hubic is too short, just a day.
I can only do a rclone config to get another token.

> What is your rclone version (eg output from `rclone -V`)
- os/arch: linux/amd64
- go version: go1.9.2

> Which OS you are using and how many bits (eg Windows 7, 64 bit)

Ubuntu Linux 16.04.3 LTS

> Which cloud storage system are you using? (eg Google Drive)

hubic

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

rclone config 
and 
rclone copy -u -L "source" backupserveur:default/ServeurMaison

After the expiry date, I've the log :
2018/02/04 17:00:03 Failed to create file system for "backupserveur:default/ServeurMaison": error authenticating swift connection: failed to get credentials: 401

And if I try, at 19:23 february 4th, i've got the token :
{"access_token":"xxxx","token_type":"Bearer","refresh_token":"xxx","expiry":"2018-02-05T01:17:26.117877988+01:00"}

My .config/rclone/rclone.conf is :
```
[backupserveur]
type = hubic
client_id = 
client_secret = 
token = {"access_token":"xxx","token_type":"Bearer","refresh_token":"xxx","expiry":"2018-02-05T01:17:26.117877988+01:00"}
```

How to get a expiry date more long ?

Thanks

**Comment by ncw** [comment]
Rclone should refresh the token automatically when it expires.

Can you send a log with `-vv` of the problem occurring please?

**Comment by webafrancois** [comment]
it's OK, rclone well refresh the date !
Today it's : 2018-02-09T23:00:06
and I didn't run the rclone config anymore.
I believed that it was just a date done by hubic.

That's ok for me, my backup rocks !
