### ISSUE TITLE
Add APPEND flag/option to append to log file rather than create new one

### ISSUE THREAD

**Issue by ljr9600** [ncw/rclone#2059]
Any chance that we can APPEND to the log file, rather than clobber it and recreate it each time? I like to log all my transfers, and if I forgot to change the log file name, it gets wiped. Could the default be APPEND? (ask around and see what people want).

Suggested option: 

--log-file-append

**Comment by ncw** [comment]
A flag is easy enough.

I'd consider changing the default to append though which seems sensible.

Can you do a bit of research and see what other command line utilities that generate logs do?  That is usually the way I decide on this sort of thing!

**Comment by ljr9600** [comment]
tail uses -a, and the only example i can find.  

I like: --log-file-append.

**Comment by 1024mb** [comment]
> 
> 
> A flag is easy enough.
> 
> I'd consider changing the default to append though which seems sensible.
> 
> Can you do a bit of research and see what other command line utilities that generate logs do? That is usually the way I decide on this sort of thing!

Was this ever included? I don't understand why this was closed, I couldn't find anything on the docs.  

Please, consider adding this. I would also like to have logs for all the Rclone transfers and a flag would be the easiest way to get it instead of changing the default for everyone.

**Comment by ncw** [comment]
Yes the log file is appended to without an extra flag.

I'm not 100% sure which commit this happened in but it has been in rclone since at least v1.40

**Comment by 1024mb** [comment]
Thanks! The documentation doesn't clarify this (or informs about it) or I missed something in there? Would be great if you could put this information in the documentation.

**Comment by ncw** [comment]
> Thanks! The documentation doesn't clarify this (or informs about it) or I missed something in there? Would be great if you could put this information in the documentation.

I stuck something in the docs which will go live for 1.53.1

**Comment by ljr9600** [comment]
Thank you!  Great to see that this is in there since v1.40...I didn't know, and will use it now, rather than piping through 'tail -a...'
