### ISSUE TITLE
slow time getting lists for files - also using checkers

### ISSUE THREAD

**Issue by xgiovio** [ncw/rclone#206]
hello,
listing directory should use content-length only for 0 files with manifest metadata (large objects)

For normal objects i don't understand why rclone use 8 default checkers to obtain files list.

using the python command line 
>swift list -l container_name/path

 you can have an immediate list of all files with relative sizes. Only the reported sizes for large objects are wrong and should be grabbed checking the content-length metadata.

Am i wrong? thank you

**Comment by ncw** [comment]
`rclone` uses the checkers to read the modification time only.

So if you do `rclone ls swift:container` which doesn't need the mod time, it is much quicker than `rclone lsl swift:container` which does.

Likewise doing a sync with the `--size-only` flag will be much quicker.  You can use the `--checksum` flag to avoid the checkers too, but then you will incur the cost of an MD5SUM on the local filesystem.

**Comment by xgiovio** [comment]
Done with size-only, the time is the same. Tested onna folfer with 40k files.
Swift commandline return list in 3/4 seconds.
Rclone 45 minutes.

Can you please add or fix the option for readind metadata only for manifests?
Ps. The swift list -l return also the mod time, you don't have to check the metadata when using checkers.

**Comment by ncw** [comment]
> Done with size-only, the time is the same. Tested onna folfer with 40k files.
> Swift commandline return list in 3/4 seconds.
> Rclone 45 minutes.

What exactly did you do? Please post the command lines.

Did you try `rclone ls container:bucket` ? That should be very quick.

> Can you please add or fix the option for readind metadata only for manifests?

I don't understand what you mean here?

> The swift list -l return also the mod time, you don't have to check the metadata when using checkers.

The time returned here is the time that the object was uploaded.  This is useless for syncing purposes as you can't set it.  rclone stores the mod time of the uploaded file in `X-Object-Meta-Mtime` the same way the swift program does.

So when you do `rclone lsl` it is showing you the value of `X-Object-Meta-Mtime` as the time, whereas `swift list -l` is showing you the `Last-Modified`.

**Comment by xgiovio** [comment]
>What exactly did you do? Please post the command lines.

rclone.exe copy "local/path" "hubic:remote/path" -n -v --size-only
if i do swift list -l container/path i have an answer in seconds. I don't think rclone is comparing something because i can see only network activity in the firewall and nothing on harddriver

> rclone ls container:bucket

done, and I need this list during size-only comparison. size are already reported minus manifests that are reported as zero and should be checked for content-length

> So when you do rclone lsl it is showing you the value of X-Object-Meta-Mtime as the time, whereas swift list -l is showing you the Last-Modified

understood. so i'ts important to get metadata for all files to obtaing mtimes. But... for size-only it's useless and it should only grab file size from directory listing and do few http calls only to files with 0 bytes to see if the are normal files (no manifest e so 0 byte long) or long file (manifest present e so the length isn't that reported from directory listing but from content-length metadata)

**Comment by ncw** [comment]
One thing that occurs to me - is it possible that all, or a lot of your files have been segmented?  That would explain things...

**Comment by xgiovio** [comment]
No, for example on a folder there are 300k files, all normal but it takes age to build list. I will take some tests and post results on the --size-only discussion. Thanks

**Comment by ncw** [comment]
I think we've identified the problem in #208 so I'm going to close this ticket

**Comment by xgiovio** [comment]
yes,right
