### ISSUE TITLE
Fatal error: unknown flag: --vfs-cache-dir

### ISSUE THREAD

**Issue by PiscisSwimeatus** [ncw/rclone#2067]
> What is your rclone version (eg output from `rclone -V`)
rclone v1.39-128-gb33e3f77
- os/arch: windows/amd64
- go version: go1.9.2
> Which OS you are using and how many bits (eg Windows 7, 64 bit)
Windows Server 2016
> Which cloud storage system are you using? (eg Google Drive)
Google Drive
> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

rclone.exe mount CacheG3: Z: `
--config "C:\rclone\rclone.conf" `
--log-level=ERROR `
--drive-chunk-size=8M `
--drive-use-trash=false `
--cache-chunk-path="C:\rclone" `
--cache-chunk-size=8M `
--cache-db-path="C:\rclone" `
--cache-info-age=192h `
--cache-total-chunk-size=16G `
--cache-workers=32 `
--vfs-cache-mode=writes `
--vfs-cache-dir="C:\rclone"

> A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

Fatal error: unknown flag: --vfs-cache-dir

**Comment by ncw** [comment]
Ah yes, that is old docs.. the correct option is `--cache-dir`.  Will fixup shortly - thanks for reporting.

**Comment by riker65** [comment]
Hi 
I still get this error for this flag:

`2019/11/03 17:30:28 Fatal error: unknown flag: --vfs-cache-mode`
