### ISSUE TITLE
google drive : feedback on the new polling for changes feature

### ISSUE THREAD

**Issue by jmoriau** [ncw/rclone#2068]
Hi,

I just tried the latest commit from @remusb and I was wondering if it was really necessary to expire the whole directory when detecting some changes ?
I think the relevant block is here : [L431](https://github.com/ncw/rclone/commit/b33e3f779c84ab7207e04ee06f12d7895909b742#diff-97fa9f3f2a305c2948bd97dee700fe5bR431)

The issue I'm having with this is as follow : 
- I have a few directories with a lot of files, say more than 20k
- Each time there's some change in this directory, it will one by one expire all the files and then recache all of them
- The expiring/recaching process is very slow, it takes a very long time, during which the drive is unavailable.

Wouldn't it be possible to only expire the changed files instead of the whole directory where one file changed ?
Because right now it makes the drive unusable, as it spends more expiring then recaching, than being avaiable.

Best regards

**Comment by remusb** [comment]
Since the original issue for the enhancement is still open, can we move the conversation there? -> https://github.com/ncw/rclone/issues/1937
