### ISSUE TITLE
Files listing bug

### ISSUE THREAD

**Issue by Bezk** [ncw/rclone#2070]
Why i do receiving result by request with close slash? It's equal` ?prefix=fdd6483a090b47f08ea7ea8ab83cb7b5/&delimiter=/`, but i expect receive result by `?prefix=fdd6483a090b47f08ea7ea8ab83cb7b5&delimiter=`, because i no see files at root:
`fdd6483a090b47f08ea7ea8ab83cb7b5.gif`
`fdd6483a090b47f08ea7ea8ab83cb7b5.original`

> What is your rclone version (eg output from `rclone -V`)

`rclone v1.38 - os/arch: freebsd/amd64 - go version: go1.9.2`

> Which OS you are using and how many bits (eg Windows 7, 64 bit)

macOS 10.13.2

> Which cloud storage system are you using? (eg Google Drive)

Swift (ceph)

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

`rclone ls ceph:media/fdd6483a090b47f08ea7ea8ab83cb7b5`

> A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

```rclone -vv ls ceph:media/fdd6483a090b47f08ea7ea8ab83cb7b5
2018/02/12 18:57:33 DEBUG : Using config file from "/home/anatoly/.rclone.conf"
2018/02/12 18:57:33 DEBUG : rclone: Version "v1.38" starting with parameters ["rclone" "-vv" "ls" "ceph:media/fdd6483a090b47f08ea7ea8ab83cb7b5"]
2018/02/12 18:57:33 INFO  : Swift container media path fdd6483a090b47f08ea7ea8ab83cb7b5/: Modify window is 1ns
    19944 100x100.gif
    23556 110x110.gif
    27660 120x120.gif
    31780 130x130.gif
    36005 140x140.gif
    40655 150x150.gif
    45704 160x160.gif
    50898 170x170.gif
    56359 180x180.gif
    62071 190x190.gif
    65940 200x200.gif
     6799 50x50.gif
     8820 60x60.gif
    11235 70x70.gif
    13837 80x80.gif
    16623 90x90.gif
2018/02/12 18:57:33 DEBUG : Go routines at exit 4
2018/02/12 18:57:33 DEBUG : rclone: Version "v1.38" finishing with parameters ["rclone" "-vv" "ls" "ceph:media/fdd6483a090b47f08ea7ea8ab83cb7b5"]```

**Comment by ncw** [comment]
Can you show me the command which did not work?  `rclone ls ceph:media/fdd6483a090b47f08ea7ea8ab83cb7b5` appeared to work fine.

**Comment by Bezk** [comment]
@ncw yep, fine, but with incorrect request to storage.

```
| => rclone ls ceph:media/fdd6483a090b47f08ea7ea8ab83cb7b5
    19944 100x100.gif
    23556 110x110.gif
    27660 120x120.gif
    31780 130x130.gif
    36005 140x140.gif
    40655 150x150.gif
    45704 160x160.gif
    50898 170x170.gif
    56359 180x180.gif
    62071 190x190.gif
    65940 200x200.gif
     6799 50x50.gif
     8820 60x60.gif
    11235 70x70.gif
    13837 80x80.gif
    16623 90x90.gif
```

aka 
```
media/fdd6483a090b47f08ea7ea8ab83cb7b5/10x10.gif
media/fdd6483a090b47f08ea7ea8ab83cb7b5/20x20.gif
[...] etc.
```
It's equal request to storage with params: 
`?prefix=fdd6483a090b47f08ea7ea8ab83cb7b5/&delimiter=/` (with backslashes)

What i expect:
```
media/fdd6483a090b47f08ea7ea8ab83cb7b5.original (not inside)
media/fdd6483a090b47f08ea7ea8ab83cb7b5.gif (not inside)
media/fdd6483a090b47f08ea7ea8ab83cb7b5/10x10.gif
media/fdd6483a090b47f08ea7ea8ab83cb7b5/10x10.gif
media/fdd6483a090b47f08ea7ea8ab83cb7b5/20x20.gif
```
It's equal request to storage with params: 
`?prefix=fdd6483a090b47f08ea7ea8ab83cb7b5&delimiter=` (without slashes)

If i want get result from inside, i would be request with backslash:
```
| => rclone ls ceph:media/fdd6483a090b47f08ea7ea8ab83cb7b5/
    19944 100x100.gif
    23556 110x110.gif
    27660 120x120.gif
    31780 130x130.gif
    36005 140x140.gif
    40655 150x150.gif
    45704 160x160.gif
    50898 170x170.gif
    56359 180x180.gif
    62071 190x190.gif
    65940 200x200.gif
     6799 50x50.gif
     8820 60x60.gif
    11235 70x70.gif
    13837 80x80.gif
    16623 90x90.gif
```

Maybe its incorrect for local filesystem, but with same time it's correct for like a openstack storages.
Also, maybe, how i think, need requesting files at root as `rclone ls ceph:media` with filters, but in root very many more files, and local sorting with filtering not fine idea, if i can requests all in one from storage without other actions.

**Comment by ncw** [comment]
That isn't the way rclone works...  Rclone tries to make all storage systems look the same so it works with eg google drive or the local filesystem or ceph

If you want the things with that prefix in the `media` directory then you could do

    rclone ls --include "/fdd6483a090b47f08ea7ea8ab83cb7b5**" ceph:media

**Comment by Bezk** [comment]
@ncw time difference

```
________________________________________________________________________________
| ~/Documents @ Fry (bezk) 
| => date && rclone ls --include "/fd83e8ff364f4f1889e28677be6e985e**" ceph:media && date
среда, 14 февраля 2018 г. 19:26:18 (MSK)
    16075 fd83e8ff364f4f1889e28677be6e985e.gif
    21583 fd83e8ff364f4f1889e28677be6e985e.original
     7897 fd83e8ff364f4f1889e28677be6e985e/100x100.gif
     9136 fd83e8ff364f4f1889e28677be6e985e/110x110.gif
    10771 fd83e8ff364f4f1889e28677be6e985e/120x120.gif
    12469 fd83e8ff364f4f1889e28677be6e985e/130x130.gif
    13918 fd83e8ff364f4f1889e28677be6e985e/140x140.gif
    16075 fd83e8ff364f4f1889e28677be6e985e/150x150.gif
    17675 fd83e8ff364f4f1889e28677be6e985e/160x160.gif
    19874 fd83e8ff364f4f1889e28677be6e985e/170x170.gif
    22047 fd83e8ff364f4f1889e28677be6e985e/180x180.gif
    23843 fd83e8ff364f4f1889e28677be6e985e/190x190.gif
    22774 fd83e8ff364f4f1889e28677be6e985e/200x200.gif
     2708 fd83e8ff364f4f1889e28677be6e985e/50x50.gif
     3604 fd83e8ff364f4f1889e28677be6e985e/60x60.gif
     4538 fd83e8ff364f4f1889e28677be6e985e/70x70.gif
     5565 fd83e8ff364f4f1889e28677be6e985e/80x80.gif
     6814 fd83e8ff364f4f1889e28677be6e985e/90x90.gif
среда, 14 февраля 2018 г. 19:26:36 (MSK)
________________________________________________________________________________
| ~/Documents @ Fry (bezk) 
| => date && rclone ls ceph:media/fd83e8ff364f4f1889e28677be6e985e && date
среда, 14 февраля 2018 г. 19:26:49 (MSK)
     7897 100x100.gif
     9136 110x110.gif
    10771 120x120.gif
    12469 130x130.gif
    13918 140x140.gif
    16075 150x150.gif
    17675 160x160.gif
    19874 170x170.gif
    22047 180x180.gif
    23843 190x190.gif
    22774 200x200.gif
     2708 50x50.gif
     3604 60x60.gif
     4538 70x70.gif
     5565 80x80.gif
     6814 90x90.gif
среда, 14 февраля 2018 г. 19:26:52 (MSK)
________________________________________________________________________________
```

**Comment by Bezk** [comment]
also difference output between 
[with slashes](https://s3.teasernet.com/media/?prefix=fd83e8ff364f4f1889e28677be6e985e/&delimiter=/)
[without slashes](https://s3.teasernet.com/media/?prefix=fd83e8ff364f4f1889e28677be6e985e&delimiter=)

**Comment by ncw** [comment]
You could do it with two commands also

    rclone ls ceph:media/fdd6483a090b47f08ea7ea8ab83cb7b5
    rclone ls --include "/fdd6483a090b47f08ea7ea8ab83cb7b5*" ceph:media

What are you trying to achieve?
