### ISSUE TITLE
Unexpected message about symlinks from rclone

### ISSUE THREAD

**Issue by angelog0** [ncw/rclone#2071]
> What is your rclone version (eg output from `rclone -V`)

$ rclone -V
rclone v1.38 (from MacPorts package)
- os/arch: darwin/amd64
- go version: go1.9.2

> Which OS you are using and how many bits (eg Windows 7, 64 bit)

macOS 10.13.3 + MacPorts, 64 bit

> Which cloud storage system are you using? (eg Google Drive)

Google Drive

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

$ rclone copy README.md gdrive:
2018/02/12 16:39:18 NOTICE: backup: Can't follow symlink without -L/--copy-links

The directory which contains README.md has also a symlink

backup -> Documents/backup

WHY then, rclone outputs the message

2018/02/12 16:39:18 NOTICE: backup: Can't follow symlink without -L/--copy-links

?

I notice this: if the folder contains the symlinks foo1, foo2, foo3 etc. and I want to copy just a text file bar.txt, rclone emits a similar message for each symlink foo1, foo2, foo3 ...

The same happens on GNU/Linux Mint 64 bit.

Why is rclone looking at the symlinks that the folder contains?

Is this to be expected?

**Comment by ncw** [comment]
That is how rclone works... It is a bit counter-intuitive I would agree.

Essentially `rclone copy README.md gdrive:` does a copy from `.` but with filters applied to only match README.md.

If you don't want to see that error you can use `rclone copyto README.md gdrive:README.md`

**Comment by angelog0** [comment]
@ncw , thanks for clarification..

 Angelo
