### ISSUE TITLE
Rclone : Failed to configure drive: unexpected end of JSON input

### ISSUE THREAD

**Issue by kensemui** [ncw/rclone#2072]
Hi everyone,

I got an issue when I tried to mount my Google Drive remote on my server (Ubuntu 14.04 64 bits).

I can see my remote with rclone config but cannot mount it.

**Name**                            
Enc_Plex  (crypt)
Gdrive_Plex  (drive)

Tried different version of rclone (v1.36/v1.38/v1.39) but still the same error message : 

>> sudo rclone mount -vv --allow-other --allow-non-empty Enc_Plex: /mnt/Enc/

**2018/02/13 22:22:11 DEBUG : rclone: Version "v1.36" starting with parameters ["rclone" "mount" "-vv" "--allow-other" "--allow-non-empty" "Enc_Plex:" "/mnt/Enc/"]
2018/02/13 22:22:11 Failed to configure drive: unexpected end of JSON input**

by the way, I took my rclone.conf from my first server (Debian Jessie with rclone v1.36, that works well) and drop it on /home/user/.config/rclone/

Does someone have some clues ?
Maybe something wrong with the token ?

Thanks !

**Comment by ncw** [comment]
> 2018/02/13 22:22:11 Failed to configure drive: unexpected end of JSON input

That suggests that the token is incorrect in the `.rclone.conf`.  It is supposed to be valid JSON and that message says it isn't.

Check the config and see whether it looks OK.

**Comment by kensemui** [comment]
Hi, 

Thanks for the quick answer.

I think there is a problem with the token too, but I gave my rclone.conf to my friend and he can mount my google Drive remote... (with the same token)

**Comment by kensemui** [comment]
alright...
Just tried with another option and it works fine !

>> rclone mount Enc_Plex: /mnt/Enc/ --allow-other --no-modtime &

Thanks for your time ! :)
