### ISSUE TITLE
Why can't I compile from source

### ISSUE THREAD

**Issue by jeremybrown82** [ncw/rclone#2073]
Why can't I compile from source? Is there something the dev is hiding in the binary?

When filing an issue, please include the following information if possible as well as a description of the problem.  Make sure you test with the latest beta of rclone.

    https://beta.rclone.org/
    https://rclone.org/downloads/

If you've just got a question or aren't sure if you've found a bug then please use the [rclone forum](https://forum.rclone.org/) instead of filing an issue.

> What is your rclone version (eg output from `rclone -V`)

> Which OS you are using and how many bits (eg Windows 7, 64 bit)

> Which cloud storage system are you using? (eg Google Drive)

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

> A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

**Comment by ncw** [comment]
> Why can't I compile from source?

You should be able to compile from source - what did you try?

**Comment by jeremybrown82** [comment]
I cloned the git and did make && sudo make install
There is no configure file.
jeremybrown82@s125553:~/rclone$ make && sudo make install
bash: go: command not found
bash: go: command not found
bash: go: command not found
make: Warning: File `Makefile' has modification time 1.6e+04 s in the future
touch fs/version.go
go install -v --ldflags "-s -X github.com/ncw/rclone/fs.Version=v1.39-138-gff6a7142"
bash: go: command not found
make: *** [rclone] Error 127

**Comment by naeloob** [comment]
So this... "bash: go: command not found"
You don't have go compiler installed or you don't have it on your Path.

**Comment by daniel-loader** [comment]
Seems a bit aggressive to accuse the author up front when you've not got a compiler installed for the source code.

**Comment by jeremybrown82** [comment]
Sorry, I've had a couple bad experiences with installing something from git hub and getting compromised.

**Comment by ncw** [comment]
> Sorry, I've had a couple bad experiences with installing something from git hub and getting compromised.

No worries.  The rclone repo contains everything that goes into the binary.  Filippo Valsorda even wrote a blog showing that [the rclone binaries are perfectly reproducible from the source](https://blog.filippo.io/reproducing-go-binaries-byte-by-byte/)
