### ISSUE TITLE
cryptdecode logs into underlying remote, costing money?

### ISSUE THREAD

**Issue by jikamens** [ncw/rclone#2075]
As far as I can tell -- and I may be confused, I'm not certain -- when I use `rclone cryptdecode` on an encrypted remote which is backed by a Backblaze B2 remote, logs into the backing remote before doing the filename decode.

This costs money, since Backblaze charges for login transactions.

It also takes time for the login, which arguably should be instantaneous.

Rclone shouldn't access the backing remote at all when doing cryptdecode.

**Comment by ncw** [comment]
Yes you are right it does.

It creates the remote which involves initialising the underlying remote.

There is probably a better way of doing this!

**Comment by B4dM4n** [comment]
Beta [v1.39-173-gaeefa34f](https://beta.rclone.org/v1.39-173-gaeefa34f/) contains a solution for the mentioned behavior.

`cryptdecode` will no longer access the wrapped remote from now on.

**Comment by jikamens** [comment]
Amazing, thanks.
