### ISSUE TITLE
Bug Failed to copy: upload failed: unexpected end of JSON input

### ISSUE THREAD

**Issue by dgobrito** [ncw/rclone#2086]
Hi,

rclone v1.39
- os/arch: linux/amd64
- go version: go1.9.2
- Dropbox
- Command: rclone copy /home/test/ Dropbox:/backup/test/ --retries 1 --log-file=$LOG
- Log:
2018/02/21 19:35:22 ERROR : ***/umain.~ddp: Failed to copy: upload failed: unexpected end of JSON input
2018/02/21 23:29:02 ERROR : ***/ACBr_Trunk2/.svn/pristine/36/369e28ad94e8a099c94d8dcf91acc93957e14562.svn-base: Failed to copy: upload failed: unexpected end of JSON input
2018/02/21 23:29:03 ERROR : ***/Parsing.dcu: Failed to copy: upload failed: unexpected end of JSON input
Thanks!

**Comment by ncw** [comment]
I think this is fixed already... Try [the latest beta](https://beta.rclone.org)!

**Comment by notjoe** [comment]
Confirmed to be fixed for me in the beta.

**Comment by ncw** [comment]
Great thanks for testing. I'll close this now.
