### ISSUE TITLE
Sync deleting destination files even with --update

### ISSUE THREAD

**Issue by glmdev** [ncw/rclone#2088]
I'm using rclone version 1.38 beta with Microsoft OneDrive as a remote.

I'm trying to synchronize a local folder to the remote using the following command:

`rclone sync -u -vv ~/Desktop OneDrive:Desktop`

Files/Folders that have changed on the local side are properly uploaded to the remote, however any remote files that exist in the OneDrive:Desktop folder that _aren't_ on the local side (say, if they were created since the files were originally downloaded locally) are deleted.

Directories Before:
Local (~/Desktop):
`
Folder1
File.txt
NewFile.txt
`

Remote (OneDrive:Desktop):
`
Folder1
File.txt
ADifferentFile.txt
`

Directories After:
Local (~/Desktop):
`
Folder1
File.txt
NewFile.txt
`

Remote (OneDrive:Desktop):
`
Folder1
File.txt
NewFile.txt
`

Output from -vv:
```
Syncing Local to Cloud
2018/02/22 15:33:34 DEBUG : Using config file from "/home/glmdev/.config/rclone/rclone.conf"
2018/02/22 15:33:34 DEBUG : rclone: Version "v1.38β" starting with parameters ["/home/glmdev/.odsync/rclone/rclone" "sync" "--update" "-vv" "/home/glmdev/Desktop" "OneDrive:Desktop"]
2018/02/22 15:33:35 INFO  : One drive root 'Desktop': Modify window is 1s
2018/02/22 15:33:35 DEBUG : Stuff/BAK_0345.JPG: Destination mod time is within 1s of source and sizes identical, skipping
2018/02/22 15:33:35 DEBUG : Stuff/red_dot.mp4: Destination mod time is within 1s of source and sizes identical, skipping
2018/02/22 15:33:35 DEBUG : Stuff/RESUME.docx: Destination mod time is within 1s of source and sizes identical, skipping

... etc ...

2018/02/22 15:33:36 DEBUG : Stuff/DCIM/100CANON/IMG_0062.JPG: Destination mod time is within 1s of source and sizes identical, skipping
2018/02/22 15:33:36 INFO  : One drive root 'Desktop': Waiting for checks to finish
2018/02/22 15:33:36 INFO  : One drive root 'Desktop': Waiting for transfers to finish
2018/02/22 15:33:36 INFO  : robert/._odcs_keep: Copied (new)   <-- the local-side only file
2018/02/22 15:33:36 INFO  : Waiting for deletions to finish
2018/02/22 15:33:36 INFO  : newfiletest2.txt: Deleted  <-- the server-side only file
2018/02/22 15:33:36 INFO  : 
Transferred:      0 Bytes (0 Bytes/s)
Errors:                 0
Checks:               160
Transferred:            1
Elapsed time:        1.9s

2018/02/22 15:33:36 DEBUG : Go routines at exit 18
2018/02/22 15:33:36 DEBUG : rclone: Version "v1.38β" finishing with parameters ["/home/glmdev/.odsync/rclone/rclone" "sync" "--update" "-vv" "/home/glmdev/Desktop" "OneDrive:Desktop"]
Local to Cloud Sync Completed
```

Am I configuring something improperly, or is this not how the --update flag is supposed to work?

**Comment by glmdev** [comment]
Fundamentally, can rclone tell the difference between a file deleted from the source and a file that never existed on the source in the first place, only the destination?

**Comment by naeloob** [comment]
That's the way sync command works.
Did you read the rclone documentation? -> https://rclone.org/commands/rclone_sync/
First sentence : "Make source and dest identical, modifying destination only."

I think that you want to use the copy command.
https://rclone.org/commands/rclone_copy/

**Comment by dushoff** [comment]
Well, the question was specifically about --update, which one could at least hope would respect deletion and creation dates -- certainly this would be a very useful functionality.
