### ISSUE TITLE
Trying to sync everything except photos

### ISSUE THREAD

**Issue by RobertLHarris** [ncw/rclone#209]
I have this command: 
   /usr/sbin/rclone sync -v --dry-run --exclude "Google Photos/**" GoogleDrive/ GoogleDrive:/

I'm trying to set up a sync from my local system to my Drive.  The issue is my laptop doesn't have room for my photos so I'm excluding them on the pull down sync.  When I run the above command it still complains about the Photos as if it's not excluding them and I would really prefer if it doesn't delete my photos.

**Comment by ncw** [comment]
I think this is the same problem as #205 - what do you think?

**Comment by RobertLHarris** [comment]
Yes, that looks to be similar behavior.

**Comment by ncw** [comment]
I'll fix #205 soon - I suggest you don't use `sync` with `--exclude` until then.  You could use `copy` though.

**Comment by RobertLHarris** [comment]
Thanks.

**Comment by ncw** [comment]
I've fixed this in v1.25.

I've spent some time thinking about the algorithm and writing unit tests, but I'd appreciate a second opinion!  If you find a problem then please open another issue.

Thanks

Nick
