### ISSUE TITLE
(not an issue) Improve reliability on low bandwidth / high latency links

### ISSUE THREAD

**Issue by drpau** [ncw/rclone#2090]
i currently have a cable connection which unfortunately is a shared medium.  During the night, my 100mbit connection typically goes down to ~3mbit.

With such a low bandwidth link, when doing things like library scan / attempting to play something it consumes as much bandwidth that i have available and therefore typically drops the rclone mount.

Is there a way of increasing tolerance on rclone before losing the mount????

**Comment by ncw** [comment]
When you say "losing the mount" what do you mean?  What are the errors in the log from `rclone mount`?

That should give a clue as to what needs tweaking.

**Comment by drpau** [comment]
@ncw i have changed my setup now - with another thread you are helping me in, i wont be able to replicate this now, so i cant provide feedback sorry. 

from memory though - there was no essential feedback provided verbosely of the error but, due to the link being conjested/low bandwidth whatever poll'ing or measure to maintain the connection, had been lost therefore the mount path was lost and rclone process stopped.

**Comment by ncw** [comment]
OK, no worries!  If you should happen to find the error then please re-open the issue - thanks!
