### ISSUE TITLE
Allow copying a single file?

### ISSUE THREAD

**Issue by ChrisSLT** [ncw/rclone#21]
I don't know what's involved, but it would be great to be able to copy or move a single file either from local to cloud, cloud to local, or between 2 cloud providers.  

Yours is the only stable tool I know of that connects to each of these different cloud providers so it would be invaluable to be able to copy/move individual files between them from the command line!

**Comment by ncw** [comment]
You can do this already

Copy `file1.txt` into the bucket

    rclone copy file1.txt memstore:test-bucket

Retreive `file1.txt` back again into the current directory

    rclone copy memstore:test-bucket/file1.txt .

It isn't entirely intuitive, I'd agree!

**Comment by ChrisSLT** [comment]
Thank you - quite intuitive, works great.  I must have misunderstood the documentation.  It says you can't sync individual files. 

Are you planning to add other rsync features like include, exclude, max file size, things like that?

**Comment by ncw** [comment]
I'll try to make the docs clearer about copying single files.

Yes I'd like to add include, exclude and max-size flags at some point!

**Comment by ChrisSLT** [comment]
Thanks, no worries.

I also took a look at Hugo thanks to you, pretty cool.

**Comment by khurshid-alam** [comment]
@ncw 

Why doesn't it work for files without extension?

For example:
`rclone copy -u -v Dropbox:Backups/Home@Desk/.bash_history /home/pcuser/`

It simply fails with no such source **Dropbox:Backups/Home@Desk/.bash_history** ?

**Comment by ncw** [comment]
@khurshid-alam that should work fine - check you've got the path right to the file.  If you still can't make it work can we take it to [the rclone forum](https://forum.rclone.org/) - thanks.
