### ISSUE TITLE
Document fs specific flags on their pages

### ISSUE THREAD

**Issue by nodughere** [ncw/rclone#210]
I see that a 5GB chunk has been added to rclone for large file uploads.  As an enhancement possibly allow a flag for users to select a smaller chunk size than 5GB.  The reason for this would be that smaller chunks can be easier to replicate between low bandwidth regions.

Doug

**Comment by xgiovio** [comment]
>--swift-chunk-size=5G

 Above this size files will be chunked into a _segments container.

**Comment by ncw** [comment]
@nodughere is `--swift-chunk-size` sufficient?

If so please close the ticket, if not then explain further

Thanks

Nick

**Comment by nodughere** [comment]
Thanks.  I see it in the help list for rclone.  I didn't see it in the docs on the rclone site.  When you have time, maybe you could update the docs page.

**Comment by ncw** [comment]
Yes you are right that these aren't documented!

I'm going to reopen and re-purpose this ticket to that end.

**Comment by ncw** [comment]
The new docs are live and on the website now - thanks!
