### ISSUE TITLE
typo in documentation

### ISSUE THREAD

**Issue by wolfv6** [ncw/rclone#2101]
On page https://github.com/ncw/rclone/blob/test/docs/content/docs.md#logging
4 log levels (Error, Notice, Info, Debug) should be all caps:  ERROR, NOTICE, INFO, DEBUG

Not sure it that's right.  If you say it should be changed, I can make a pull request.

**Comment by ncw** [comment]
I've merged your pull request in fe8a275a5683048473c7060ceab84ff9219da55b

Can you create your pull request on the rclone repo next time not on your repo?  I only noticed it by accident!

Thanks

Nick
