### ISSUE TITLE
Make documentation easier to read

### ISSUE THREAD

**Issue by Toontje** [ncw/rclone#2103]
Please make the content box for the documentation bigger or the font smaller so the test is easier to read.
![screen shot 2018-02-27 at 12 15 53](https://user-images.githubusercontent.com/4884243/36725961-56b47968-1bb8-11e8-86b1-c10ef8885f11.jpg)

**Comment by ncw** [comment]
That is a bit of a mess isn't it...

I'll see what I can do - thanks!
