### ISSUE TITLE
Not able to create log file?

### ISSUE THREAD

**Issue by Toontje** [ncw/rclone#2104]
When filing an issue, please include the following information if possible as well as a description of the problem.  Make sure you test with the latest beta of rclone.

    https://beta.rclone.org/
    https://rclone.org/downloads/

If you've just got a question or aren't sure if you've found a bug then please use the [rclone forum](https://forum.rclone.org/) instead of filing an issue.

> What is your rclone version (eg output from `rclone -V`)
rclone v1.39
- os/arch: darwin/amd64
- go version: go1.9.2

> Which OS you are using and how many bits (eg Windows 7, 64 bit)
OSX 10.12.6

> Which cloud storage system are you using? (eg Google Drive)
DropBox

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
```
rclone copy --filter-from ~/rcloneFilters.txt -L -u -n /Users/tmachielsen Dropbox:/Backup --log-file=~/backup.log --log-level=INFO
2018/02/27 12:30:17 Failed to open log file: open ~/backup.log: no such file or directory
```

> A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
```
rclone copy --filter-from ~/rcloneFilters.txt -L -u -n /Users/tmachielsen DropboxImpinj:/Backup --log-file=~/backup.log --log-level=INFO -vv
2018/02/27 12:41:38 Failed to open log file: open ~/backup.log: no such file or directory

```

**Comment by B4dM4n** [comment]
As you can see in the log, rclone is trying to create `backup.log` in the folder `~`, which does not exist.
Shells only expand `~` at the beginning of a parameter.

You could use `--log-file ~/backup.log` or `--log-file=$HOME/backup.log` to fix your problem.
