### ISSUE TITLE
Resume downloads if the reader fails

### ISSUE THREAD

**Issue by ncw** [ncw/rclone#2108]
If there is an error reading data, then rclone could re-open the reader with a Seek and carry on.  This could be implemented in operations.Copy()

Rclone could potentially parallelise downloads also using Range Requests.  This would need an additional interface in the local Fs.

From [this comment](https://github.com/ncw/rclone/issues/497#issuecomment-426639213):
> I'd like to suggest adding an option similar to wget "-c" for "rclone copy" and/or "rclone sync", so that when executed again they would continue the download insetad of starting it again.

**Comment by neeqkowlah** [comment]
Sorry for my poor english ;)
I try to restore a backup from Hubic. A big file :o( 25Go 
But rclone copy command always failed with an unexpected EOF.
The problem come surely from the connection to Hubic. The error happened randomly, and when rclone retry, it tells that sizes differ and so it start from beginning. 
Is there any option to resume the copy from size already downloaded ?
Thank you very much.

**Comment by chenxuuu** [comment]
I have the same problem, when I download large files, it always fail with `Removing partially written file on error: read tcp 192.168.123.75:46742->13.107.136.9:443: i/o timeout`. then it redownload, then fail again...
OneDrive

**Comment by ncw** [comment]
@chenxuuu this issue would fix your problem I think.  Just need to implement it!

**Comment by fullofcaffeine** [comment]
+1 I also stumbled upon a scenario where this feature would be extremely useful and save me a lot of time and bandwidth.

**Comment by chenxuuu** [comment]
now I use `--dry-run` to get list of my files
then use https://github.com/cnbeining/onedrivecmd/ with `-hack` option (download with aria2) to solve this problem now....
yeah... aria2 is faster 😂

**Comment by ncw** [comment]
I've merged this to master now which means it will be in [the latest beta](https://beta.rclone.org) in 15-30 mins and released in v1.47
