### ISSUE TITLE
onedrive: Ignore OneNote links

### ISSUE THREAD

**Issue by ismail** [ncw/rclone#211]
In OneDrive, OneNote links live under Documents folder and they seem to be a URL links to the actual onenote.com link. Currently rclone gives an error when encountered such files:

2015/11/10 11:18:27 Documents/Quick Notes: Failed to open: itemNotFound: The specified item does not exist, or does not have content.
2015/11/10 11:18:27 Documents/Computing: Failed to open: itemNotFound: The specified item does not exist, or does not have content.
2015/11/10 11:18:27 Documents/Programming: Failed to open: itemNotFound: The specified item does not exist, or does not have content.

It would be nice to ignore them.

**Comment by wlmpie** [comment]
I would love this feauture as onenote links are now messing up my automated onedrive backup to my openmediavault server.

ERROR : <onenotelink  in onedrive Documents folder>: Failed to copy: failed to open source object: itemNotFound: The specified item does not exist, or does not have content.

currently I have to move the links to another folder to get rid of the errors.

**Comment by ncw** [comment]
Does anyone fancy fixing this?  Reading [the docs](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/resources/driveitem), working out how rclone can identify the onenote links?

In fact if someone just did that doc reading bit, I'd be willing to do the code!

**Comment by Modelmat** [comment]
I'd very much like this to be fixed.
I know many items end with the `.one` file extension, could this be filtered?
It might be a bit overkill, but might it be possible to find out this information through the OneNote api?

**Comment by ncw** [comment]
> I'd very much like this to be fixed.
> I know many items end with the `.one` file extension, could this be filtered?
> It might be a bit overkill, but might it be possible to find out this information through the OneNote api?

@Cnly do you have any ideas here?

**Comment by Cnly** [comment]
It is possible to distinguish OneNote files from normal files. They don't end in `.one`, though.

We can read the `package` field when getting metadata for a file. https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/resources/package

**Comment by chipgoon** [comment]
Thank you!  My OneDrive backup on FreeNas is choking with the OneNote files

**Comment by Cnly** [comment]
Hello everyone :) I've just created a patch for this. I'd request you to help test out the code. You can find downloads [here](https://beta.rclone.org/branch/v1.43-117-g72b7008d-onedrive-ignore-onenote-files-211-beta/) or, if you prefer, build the code yourself.

Since OneNote files are special items that look like files but behave like folders, please feel free to comment if you find anything wrong.

**Comment by ncw** [comment]
This is now in [the latest beta](https://beta.rclone.org) and will be in 1.44

**Comment by wlmpie** [comment]
I tried the latest beta, but got errors accessing onedrive

2018/10/03 22:46:17 Unable to get drive_id and drive_type. If you are upgrading from older versions of rclone, please run `rclone config` and re-configure this backend.

after running rclone config I got:

2018/10/03 22:48:26 Failed to query available drives: HTTP error 401 (401 Unauthorized) returned body: "{\r\n  \"error\": {\r\n    \"code\": \"InvalidAuthenticationToken\",\r\n    \"message\": \"CompactToken parsing failed with error code: 8004920A\",\r\n    \"innerError\": {\r\n      \"request-id\": \"xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx\",\r\n      \"date\": \"2018-10-03T20:48:26\"\r\n    }\r\n  }\r\n}"

So I installed the latest stable version and it worked again, and still got the onenote error (which is to be expected). I did the authorization however with the stable rclone version on a windows desktop and used the beta version on debian. Maybe this is the cause of the above errors or is there a bug?

**Comment by Modelmat** [comment]
remove the drive config manually and try again, for me I got the same error - I don't believe config works across versions.

**Comment by Cnly** [comment]
@wlmpie I think we should have fixed that problem and you should be able to migrate your config just by re-configuring the backend.

I saw you mentioned that "after running rclone config" you got that error. May I confirm whether you had just run `rclone config`, or you had run `rclone config` _and_ gone through the configuration again? If you had done the latter with the latest beta but you still got that error, please open a new issue about that. Many thanks!

**Comment by wlmpie** [comment]
Everything works!
Tried the latest beta again, but as it runs on a linux server (openmediavault) I had to do the authorization on a desktop machine. Previously I did not use the beta version on this desktop windows machine and got the wrong configuration. This time I used the latest beta on the server as well as the desktop and now everything works. And it does ignore my onenote links. 
So this bug is fixed. 
Many Thanks for that and sorry for my ignorance on using rclone config across versions.

**Comment by ncw** [comment]
> Is this actually fixed? Using 1.44 with OneDrive Business and it chokes trying to sync all the ".one" files. I am doing this on behalf of someone else so I'll have to learn more about the file - it might be slightly different than the original issue. The error is totally different than reported here though. It says:
> 
> "Failed to copy: activityLimitReached: The application or user has been throttled"

That sounds more like some kind of rate limiting that an re-occurrence of this issue.  Though if it just does it on the.one files, that is odd.

If you can make a reproduction then it might be worth making a new issue
