### ISSUE TITLE
rclone only works with sudo prefix... 

### ISSUE THREAD

**Issue by atanasj** [ncw/rclone#2114]
#### What is the problem you are having with rclone?

When initially trying to run `rclone config`, I was not able to configure. I got the below error. 

```
2018/03/05 20:46:06 Failed to create temp file for new config: open /Users/atanas/.config/rclone/rclone.conf865267437: permission denied
```

Following this, I ran `sudo rclone config`, but still no luck. I checked the config location `"/Users/atanas/.config/rclone/" and there was no `rclone.conf` file. So I created one, and tried the above steps again. No luck with `rclone config`, but worked with `sudo` prefix, and I was able to get the relevant tokens for the `remote` connections. 

However, when trying to run `rclone sync` I got an error (see below). However, `sync` worked when run with `sudo` prefix. 

I'm trying to setup `rclone` for use with [`rcloneosx`](https://github.com/rsyncOSX/rcloneosx), so I really need to be able to run without the `sudo` prefix (and I'm assuming that this is how `rclone` would *normally* work).

#### What is your rclone version (eg output from `rclone -V`)

```
rclone v1.39
- os/arch: darwin/amd64
- go version: go1.9.2
```

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

```
macOS 10.13.3
64bit
```

####  Which cloud storage system are you using? (eg Google Drive)

```
onedrive
box
```

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
```
rclone sync "Users/atanas/Google Drive" onedrivePhD:gdrive --verbose
```

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

```
Atanass-MacBook-Pro:~ atanas$ rclone -vv sync "/Users/atanas/Google Drive" onedrivePhD:gdrive
2018/03/05 20:43:57 DEBUG : Using config file from "/Users/atanas/.config/rclone/rclone.conf"
2018/03/05 20:43:57 DEBUG : rclone: Version "v1.39" starting with parameters ["rclone" "-vv" "sync" "/Users/atanas/Google Drive" "one
drivePhD:gdrive"]
2018/03/05 20:43:57 DEBUG : One drive root 'gdrive': Token expired but no uploads in progress - doing nothing
2018/03/05 20:43:59 Failed to create temp file for new config: open /Users/atanas/.config/rclone/rclone.conf586019659: permission denied
```

Thanks in advance---your help is greatly appreciated. 

Regards,
Atanas.

**Comment by ncw** [comment]
What you need to do is change the ownership of your rclone config directory and all the files within... Something like

    sudo chown -R atanas /Users/atanas/.config/rclone

should fix it.

This will have happened on a run of rclone with sudo I expect.

**Comment by atanasj** [comment]
That did the trick, thank you. As an aside, I just did a quick test of syncing the same folder to by `onedrive` and `box` accounts. Onedrive was significantly slower. Anyway, issues closed.
