### ISSUE TITLE
s3: SignatureDoesNotMatch for objects with spaces in the name with Ceph

### ISSUE THREAD

**Issue by svanschie** [ncw/rclone#2120]
#### What is the problem you are having with rclone?
When syncing an S3 bucket which contains objects with spaces in their names, a SignatureDoesNotMatch error is shown when those files are attempted to be synced.

#### What is your rclone version (eg output from `rclone -V`)
Tried both the lastest stable and the latest beta:

<pre>
# rclone -V
rclone v1.39
- os/arch: linux/amd64
- go version: go1.9.2
</pre>

<pre>
# rclone -V
rclone v1.39-207-g01753329β
- os/arch: linux/amd64
- go version: go1.10
</pre>

Also tried v1.38, which had the same issue.

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

<pre>
# uname -a
Linux backup01 4.10.0-28-generic #32~16.04.2-Ubuntu SMP Thu Jul 20 10:19:48 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial
</pre>

####  Which cloud storage system are you using? (eg Google Drive)
S3 (Ceph)

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

Bucket containing a file both with and without spaces:
<pre>
# rclone tree MYS3:rclone-issue/ 
/
├── filename with spaces
└── filenamewithoutspaces

0 directories, 2 files

# rclone -vv sync MYS3:rclone-issue/ /tmp/rclone-issue/
2018/03/07 11:14:56 DEBUG : Using config file from "/root/.config/rclone/rclone.conf"
2018/03/07 11:14:56 DEBUG : rclone: Version "v1.39" starting with parameters ["rclone" "-vv" "sync" "MYS3:rclone-issue/" "/tmp/rclone-issue/"]
2018/03/07 11:14:56 DEBUG : MYS3: Using v2 auth
2018/03/07 11:14:56 INFO  : Local file system at /tmp/rclone-issue: Modify window is 1ns
2018/03/07 11:14:56 INFO  : Local file system at /tmp/rclone-issue: Waiting for checks to finish
2018/03/07 11:14:56 ERROR : filename with spaces: Failed to copy: failed to open source object: SignatureDoesNotMatch: 
	status code: 403, request id: tx000000000000000fc3b42-005a9fbba0-cfaefbb-default, host id: 
2018/03/07 11:14:56 DEBUG : filenamewithoutspaces: Size and modification time the same (differ by 0s, within tolerance 1ns)
2018/03/07 11:14:56 DEBUG : filenamewithoutspaces: Unchanged skipping
2018/03/07 11:14:56 INFO  : Local file system at /tmp/rclone-issue: Waiting for transfers to finish
2018/03/07 11:14:56 ERROR : Local file system at /tmp/rclone-issue: not deleting files as there were IO errors
2018/03/07 11:14:56 ERROR : Local file system at /tmp/rclone-issue: not deleting directories as there were IO errors
2018/03/07 11:14:56 ERROR : Attempt 1/3 failed with 1 errors and: failed to open source object: SignatureDoesNotMatch: 
	status code: 403, request id: tx000000000000000fc3b42-005a9fbba0-cfaefbb-default, host id: 
2018/03/07 11:14:56 INFO  : Local file system at /tmp/rclone-issue: Waiting for checks to finish
2018/03/07 11:14:56 ERROR : filename with spaces: Failed to copy: failed to open source object: SignatureDoesNotMatch: 
	status code: 403, request id: tx000000000000001599992-005a9fbba0-c6ecac4-default, host id: 
2018/03/07 11:14:56 DEBUG : filenamewithoutspaces: Size and modification time the same (differ by 0s, within tolerance 1ns)
2018/03/07 11:14:56 DEBUG : filenamewithoutspaces: Unchanged skipping
2018/03/07 11:14:56 INFO  : Local file system at /tmp/rclone-issue: Waiting for transfers to finish
2018/03/07 11:14:56 ERROR : Local file system at /tmp/rclone-issue: not deleting files as there were IO errors
2018/03/07 11:14:56 ERROR : Local file system at /tmp/rclone-issue: not deleting directories as there were IO errors
2018/03/07 11:14:56 ERROR : Attempt 2/3 failed with 1 errors and: failed to open source object: SignatureDoesNotMatch: 
	status code: 403, request id: tx000000000000001599992-005a9fbba0-c6ecac4-default, host id: 
2018/03/07 11:14:56 INFO  : Local file system at /tmp/rclone-issue: Waiting for checks to finish
2018/03/07 11:14:56 ERROR : filename with spaces: Failed to copy: failed to open source object: SignatureDoesNotMatch: 
	status code: 403, request id: tx000000000000000fc3b45-005a9fbba0-cfaefbb-default, host id: 
2018/03/07 11:14:56 DEBUG : filenamewithoutspaces: Size and modification time the same (differ by 0s, within tolerance 1ns)
2018/03/07 11:14:56 DEBUG : filenamewithoutspaces: Unchanged skipping
2018/03/07 11:14:56 INFO  : Local file system at /tmp/rclone-issue: Waiting for transfers to finish
2018/03/07 11:14:56 ERROR : Local file system at /tmp/rclone-issue: not deleting files as there were IO errors
2018/03/07 11:14:56 ERROR : Local file system at /tmp/rclone-issue: not deleting directories as there were IO errors
2018/03/07 11:14:56 ERROR : Attempt 3/3 failed with 1 errors and: failed to open source object: SignatureDoesNotMatch: 
	status code: 403, request id: tx000000000000000fc3b45-005a9fbba0-cfaefbb-default, host id: 
2018/03/07 11:14:56 Failed to sync: failed to open source object: SignatureDoesNotMatch: 
	status code: 403, request id: tx000000000000000fc3b45-005a9fbba0-cfaefbb-default, host id: 
</pre>

After removing the object with spaces in the name all goes fine:
<pre>
# rclone tree MYS3:rclone-issue/ 
/
└── filenamewithoutspaces

0 directories, 1 files

# rclone -vv sync MYS3:rclone-issue/ /tmp/rclone-issue/
2018/03/07 11:15:44 DEBUG : Using config file from "/root/.config/rclone/rclone.conf"
2018/03/07 11:15:44 DEBUG : rclone: Version "v1.39" starting with parameters ["rclone" "-vv" "sync" "MYS3:rclone-issue/" "/tmp/rclone-issue/"]
2018/03/07 11:15:44 DEBUG : MYS3: Using v2 auth
2018/03/07 11:15:44 INFO  : Local file system at /tmp/rclone-issue: Modify window is 1ns
2018/03/07 11:15:44 INFO  : Local file system at /tmp/rclone-issue: Waiting for checks to finish
2018/03/07 11:15:44 DEBUG : filenamewithoutspaces: Size and modification time the same (differ by 0s, within tolerance 1ns)
2018/03/07 11:15:44 DEBUG : filenamewithoutspaces: Unchanged skipping
2018/03/07 11:15:44 INFO  : Local file system at /tmp/rclone-issue: Waiting for transfers to finish
2018/03/07 11:15:44 INFO  : Waiting for deletions to finish
2018/03/07 11:15:44 INFO  : 
Transferred:      0 Bytes (0 Bytes/s)
Errors:                 0
Checks:                 1
Transferred:            0
Elapsed time:          0s

2018/03/07 11:15:44 DEBUG : Go routines at exit 5
2018/03/07 11:15:44 DEBUG : rclone: Version "v1.39" finishing with parameters ["rclone" "-vv" "sync" "MYS3:rclone-issue/" "/tmp/rclone-issue/"]
</pre>

Both objects were identical, apart from the name.

**Comment by ncw** [comment]
I tried this on a Ceph Luminous cluster I have access to without problems.

```
$ rclone mkdir cephs3:issue-2120
$ echo "hello" | rclone rcat cephs3:issue-2120/"filename with spaces"
$ rclone --retries 1 -vv sync cephs3:issue-2120 /tmp/issue-2120
2018/03/07 15:44:29 DEBUG : Using config file from "/home/ncw/.rclone.conf"
2018/03/07 15:44:29 DEBUG : rclone: Version "v1.39-210-g316dac25" starting with parameters ["rclone" "--retries" "1" "-vv" "sync" "cephs3:issue-2120" "/tmp/issue-2120"]
2018/03/07 15:44:29 INFO  : Local file system at /tmp/issue-2120: Modify window is 1ns
2018/03/07 15:44:29 INFO  : Local file system at /tmp/issue-2120: Waiting for checks to finish
2018/03/07 15:44:29 INFO  : Local file system at /tmp/issue-2120: Waiting for transfers to finish
2018/03/07 15:44:29 INFO  : filename with spaces: Copied (new)
2018/03/07 15:44:29 INFO  : Waiting for deletions to finish
2018/03/07 15:44:29 INFO  : 
Transferred:      6 Bytes (57 Bytes/s)
Errors:                 0
Checks:                 0
Transferred:            1
Elapsed time:       100ms

2018/03/07 15:44:29 DEBUG : Go routines at exit 5
2018/03/07 15:44:29 DEBUG : rclone: Version "v1.39-210-g316dac25" finishing with parameters ["rclone" "--retries" "1" "-vv" "sync" "cephs3:issue-2120" "/tmp/issue-2120"]
```

I also tried it against Dreamhost

```
$ echo "hello" | rclone rcat dreamhost:issue-2120/"filename with spaces"
$ rclone ls dreamhost:issue-2120
        6 filename with spaces
$ rclone --retries 1 -vv sync dreamhost:issue-2120 /tmp/issue-2120-dreamhost2
2018/03/07 15:48:37 DEBUG : Using config file from "/home/ncw/.rclone.conf"
2018/03/07 15:48:37 DEBUG : rclone: Version "v1.39-210-g316dac25" starting with parameters ["rclone" "--retries" "1" "-vv" "sync" "dreamhost:issue-2120" "/tmp/issue-2120-dreamhost2"]
2018/03/07 15:48:37 INFO  : Local file system at /tmp/issue-2120-dreamhost2: Modify window is 1ns
2018/03/07 15:48:38 INFO  : Local file system at /tmp/issue-2120-dreamhost2: Waiting for checks to finish
2018/03/07 15:48:38 INFO  : Local file system at /tmp/issue-2120-dreamhost2: Waiting for transfers to finish
2018/03/07 15:48:38 INFO  : filename with spaces: Copied (new)
2018/03/07 15:48:38 INFO  : Waiting for deletions to finish
2018/03/07 15:48:38 INFO  : 
Transferred:      6 Bytes (4 Bytes/s)
Errors:                 0
Checks:                 0
Transferred:            1
Elapsed time:        1.2s

2018/03/07 15:48:38 DEBUG : Go routines at exit 5
2018/03/07 15:48:38 DEBUG : rclone: Version "v1.39-210-g316dac25" finishing with parameters ["rclone" "--retries" "1" "-vv" "sync" "dreamhost:issue-2120" "/tmp/issue-2120-dreamhost2"]
```

Which version of Ceph are you using?

**Comment by svanschie** [comment]
I'm currently on Ceph 12.2.2, will be upgrading to 12.2.4 pretty soon though.

When creating an object with spaces in the name the same way you did, I also get a SignatureDoesNotMatch error. Want to wait until I upgraded to 12.2.4 and see if that does anything?

**Comment by ncw** [comment]
Mmm, sorry I've been testing Kraken not Luminous.

One thing that occurs to me is which auth are you using?

I'm using v4 now

```
[cephtest]
type = s3
env_auth = false
access_key_id = XXX
secret_access_key = XXX
region = 
endpoint = https://XXX.com:8080
location_constraint = 
acl = 
server_side_encryption = 
storage_class = 
```

Whereas if you set it up [according to the docs](https://rclone.org/s3/#ceph)  you'll be using v2

```
access_key_id = Whatever
secret_access_key = Whatever
endpoint = https://ceph.endpoint.goes.here/
region = other-v2-signature
```

If you are using v4 can you try v2 and vice versa?  Should just be a case of setting the region to say "other-v2-signature" or leaving it blank.

I just tried v2-auth and it looks like it is broken

```
$ rclone cat cephtestv2:issue-2120/
2018/03/08 14:06:17 ERROR : filename with spaces: Failed to open: SignatureDoesNotMatch: 
	status code: 403, request id: tx000000000000001c35660-005aa14359-2176ea1, host id: 
```

So I think switching to v4 auth should fix it.  If so then I should probably update the docs to recommend v4 auth.

I wonder which version of CEPH implemented v4 auth...  [Seems like it was Jewel](https://stackoverflow.com/questions/38640824/ceph-s3-radosgw-403)

v2 auth doesn't work at all with dreamhost either.

**Comment by svanschie** [comment]
Good catch, I was indeed using the v2 signature. Just tried it with v4, which seems to work without problems.

**Comment by ncw** [comment]
I've fixed the docs to change the configuration advice for CEPH to use v4 auth now :-)
