### ISSUE TITLE
Default values for --min-age/--max-age displaying wrong in help

### ISSUE THREAD

**Issue by ncw** [ncw/rclone#2121]
The default values for `--min-age` and `--max-age` aren't showing correctly in the help

```
$ rclone -h | grep 2562047h
      --max-age time.Duration               Don't transfer any file older than this in s or suffix ms|s|m|h|d|w|M|y (default 2562047h47m16.854775807s)
      --min-age time.Duration               Don't transfer any file younger than this in s or suffix ms|s|m|h|d|w|M|y (default 2562047h47m16.854775807s)
```

**Comment by kubatasiemski** [comment]
What is the correct way to show it?
It can be displayed as:
`2562047h47m16.854775807s -> 2562047h 47m 16.85s`
or with days:
`106751d 23h 47m 16.85s`
or somethins like:
`292y 171d 47m 16.85s`

**Comment by ascendbruce** [comment]
I would love to help on this one 😃 

But I probably need quite some time to figure out how to do it. So please don't wait for me

**Comment by ncw** [comment]
I think the output changed from rclone 1.39 - I don't remember seeing those values before, but maybe I'm wrong, I made this issue to investigate as those values are very ugly! 

Ideally they would say something like "off".

**Comment by ascendbruce** [comment]
My finding so far:

With rclone v1.39 (installed from homebrew):

```
      --max-age string                      Don't transfer any file older than this in s or suffix ms|s|m|h|d|w|M|y
      --min-age string                      Don't transfer any file younger than this in s or suffix ms|s|m|h|d|w|M|y
```

With rclone v1.39-218-gacae10cd-master:

```
      --max-age time.Duration               Don't transfer any file older than this in s or suffix ms|s|m|h|d|w|M|y (default 2562047h47m16.854775807s)
      --min-age time.Duration               Don't transfer any file younger than this in s or suffix ms|s|m|h|d|w|M|y (default 2562047h47m16.854775807s)
```

**Comment by ncw** [comment]
I've fixed this here

https://beta.rclone.org/v1.39-233-g0c9dc006/ (uploaded in 15-30 mins)

It was caused by a change in cobra showing default values where it didn't used to.  I made the default values look sensible so it now looks like this

      --max-age duration                    Don't transfer any file older than this in s or suffix ms|s|m|h|d|w|M|y (default off)
      --min-age duration                    Don't transfer any file younger than this in s or suffix ms|s|m|h|d|w|M|y (default off)
