### ISSUE TITLE
Rclone mount does not support UTF-8 characters such as "ç" "é" and etc

### ISSUE THREAD

**Issue by Nottt** [ncw/rclone#2125]
#### What is the problem you are having with rclone?

Can't rename files if I want to use anything with accents, "ç" or similar, they will also display like this if they are named like that in the cloud.

![untitled](https://user-images.githubusercontent.com/13532436/37185531-97cf8456-231f-11e8-810f-2de550391208.png)

#### What is your rclone version (eg output from `rclone -V`)

rclone v1.37

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

W7 x64

####  Which cloud storage system are you using? (eg Google Drive)
Google drive

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone mount

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
no error on logs

Windows also does not have any issues with such characters, and this also happens in Linux

**Comment by ncw** [comment]
Rclone uses UTF-8 internally and externally for character encoding.  If your computers (Linux is the biggest culprit here) aren't set to use UTF-8 locale then you can get strange looking file names.

Those filenames look like double encoded UTF-8.  If you can paste one in the issue, I can check.

On Windows, do the file names appear correct if you do `rclone ls drive:path/to/file`?

How about on Linux?

How do they appear in the drive web interface?

Maybe the files got uploaded from a system which wasn't set to UTF-8 and the names are mangled?

**Comment by Nottt** [comment]
The files always show correctly on the drive web interface. They never show correctly, either with rclone ls or rclone mount, no matter the system.

To test, I created a new folder on google drive using the web interface, put a file there with "é" "á" and "ç" and rclone ls display them correctly. 

Now the interesting part, rclone mount on linux don't display them correctly if I do `ls` in the directory: 

![image](https://user-images.githubusercontent.com/13532436/37227027-92f3f458-23ba-11e8-9edd-d7b98dec90d0.png)

This seems to carry over to my windows samba share so that's why I see them incorrectly on Windows.

**Comment by ncw** [comment]
What do you get if you run `locale` on the linux box?

If you don't see lots of mentions of `UTF-8` then you need to reconfigure your locale.

**Comment by Nottt** [comment]
You are correct, it was in fact a issue on my end.

I had to enable ` PAM ` on ` /etc/ssh/sshd_config `  so my remote shells
would load the correct `UTF-8  locale, and I also had to edit ` smb.conf `
and add this :

```
 unix charset = UTF8
  display charset = UTF8
```

Now it display any characters without issues. Sorry for this! Thanks so
much!

**Comment by Nottt** [comment]
You are correct, it was in fact a issue on my end.

I had to enable ` PAM ` on ` /etc/ssh/sshd_config `  so my remote shells
would load the correct `UTF-8  locale, and I also had to edit ` smb.conf `
and add this :

```
unix charset = UTF8
display charset = UTF8
```

Now it display any characters without issues. Sorry for this! Thanks so
much!

**Comment by ncw** [comment]
Glad to help :-)

Linux is a bit behind Windows and macOS in this respect in that the latter 2 will always have UTF-8 support whereas Linux only mostly has it by default.
