### ISSUE TITLE
install.sh creates .config/rclone directory owned by root

### ISSUE THREAD

**Issue by ncw** [ncw/rclone#2127]
Running `sudo rclone version` creates a `.config/rclone` directory owned by root.

This should be fixed by
  * making version not need the config file (see also #2096)
  * fixing install.sh to not create the config file in the user's home directory
    * `rclone version --config /dev/null` seems like a reasonable work-around, or maybe touch an empty file first.

**Comment by ncw** [comment]
Seems to work :-)

**Comment by pendashteh** [comment]
This issue is not resolved yet.
