### ISSUE TITLE
add `--max-depth` argument for `ls`

### ISSUE THREAD

**Issue by cdepillabout** [ncw/rclone#213]
A `--max-depth` argument for the `ls` command would be nice.  It would work like `find`'s `-maxdepth` flag.

Sometimes I only want to see the files in the very top level of my dropbox.  I don't want to list ALL files in my dropbox account.

It would kind of be similar to the `lsd` command, but more flexible.

**Comment by ncw** [comment]
A `--max-depth` is a nice idea.

It could work for copy/sync too probably.

**Comment by ncw** [comment]
In the interest of trying to make consistent tools, here is how `du` defines `--max-depth`

```
 -d, --max-depth=N     print the total for a directory (or file, with --all)
                          only if it is N or fewer levels below the command
                          line argument;  --max-depth=0 is the same as
                          --summarize
```

`find` defines `-maxdepth`, but then `find` does a lot of mad things ;-)

**Comment by left1000** [comment]
it'd be nice if rclone copy could use --max-depth automatically to avoid issues like these: https://github.com/ncw/rclone/issues/263

is there anyway for rclone copy "source" "remote" to check the max depth of subdirectories in my local "source" and then use that same max depth when ls'ing the remote? (useful for services like ACD where it's own report on it's own list of files is very buggy)
