### ISSUE TITLE
Duplicate object found in destination notified while using rclone copy -update

### ISSUE THREAD

**Issue by cychanglab** [ncw/rclone#2131]
#### What is the problem you are having with rclone?
Duplicate object found in destination notified while using rclone copy -update whereas the local file was newer. Should not appear after checking the local file is actually more recent than the remote's. 

#### What is your rclone version (eg output from `rclone -V`)
1.39

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Windows 10, 64 bit

####  Which cloud storage system are you using? (eg Google Drive)
Google Drive

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone copy "C:\Users\lab\Desktop\FSIL2018" "google:fifagamelite@fifaxlabs.com\WIP" --update --excluded-from exclude.txt

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
2018/03/12 06:48:13 DEBUG : Using config file from "C:\\Users\\lab\\.config\\rclone\\rclone.conf"
2018/03/12 06:48:13 DEBUG : rclone: Version "v1.39" starting with parameters ["rclone" "copy" "C:\\Users\\lab\\Desktop\\FSIL2018" "google:fifagamelite@fifaxlabs.com\\WIP" "-vv" "--update" "--exclude-from" "exclude.txt"]
2018/03/12 06:48:13 DEBUG : pacer: Rate limited, sleeping for 1.63964395s (1 consecutive low level retries)
2018/03/12 06:48:13 DEBUG : pacer: low level retry 1/10 (error googleapi: Error 403: Rate Limit Exceeded, rateLimitExceeded)
2018/03/12 06:48:13 DEBUG : pacer: Rate limited, sleeping for 2.968964963s (2 consecutive low level retries)
2018/03/12 06:48:13 DEBUG : pacer: low level retry 2/10 (error googleapi: Error 403: Rate Limit Exceeded, rateLimitExceeded)
2018/03/12 06:48:15 DEBUG : pacer: Resetting sleep to minimum 10ms on success
2018/03/12 06:48:18 INFO  : Google drive root 'fifagamelite@fifaxlabs.com/WIP': Modify window is 1ms
2018/03/12 06:48:18 DEBUG : fsilsync.lnk: Excluded from sync (and deletion)
**2018/03/12 06:48:21 NOTICE: PlayerScout.xlsx: Duplicate object found in destination - ignoring
2018/03/12 06:48:21 DEBUG : PlayerScout.xlsx: Destination is older than source, transferring**
2018/03/12 06:48:21 INFO  : Google drive root 'fifagamelite@fifaxlabs.com/WIP': Waiting for checks to finish
2018/03/12 06:48:21 INFO  : Google drive root 'fifagamelite@fifaxlabs.com/WIP': Waiting for transfers to finish
2018/03/12 06:48:22 DEBUG : PlayerScout.xlsx: Sending chunk 0 length 8388608
2018/03/12 06:48:57 DEBUG : PlayerScout.xlsx: Sending chunk 8388608 length 1139702
2018/03/12 06:49:03 INFO  : PlayerScout.xlsx: Copied (replaced existing)
2018/03/12 06:49:03 INFO  :
Transferred:   9.087 MBytes (186.878 kBytes/s)
Errors:                 0
Checks:                 1
Transferred:            1
Elapsed time:       49.7s

2018/03/12 06:49:03 DEBUG : Go routines at exit 6
2018/03/12 06:49:03 DEBUG : rclone: Version "v1.39" finishing with parameters ["rclone" "copy" "C:\\Users\\lab\\Desktop\\FSIL2018" "google:fifagamelite@fifaxlabs.com\\WIP" "-vv" "--update" "--exclude-from" "exclude.txt"]

**Comment by ascendbruce** [comment]
Hi @cychanglab 

> Duplicate object found in destination notified while using rclone copy -update whereas the local file was newer. Should not appear after checking the local file is actually more recent than the remote's.

According to https://rclone.org/docs/#u-update, it seems that `--update` doesn't care much about if the source is newer or not, rather, it cares about the destination:

> -u, --update
> This forces rclone to skip any files which exist on the destination and have a modified time that is newer than the source file.
> ...
> This can be useful when transferring to a remote which doesn’t support mod times directly as it is more accurate than a --size-only check and faster than using --checksum.

Have you tried rclone copy without `--update` option?

**Comment by ncw** [comment]
If you find duplicate objects than you need to run rclone dedupe and things will run sensibly after that.

https://rclone.org/commands/rclone_dedupe/

**Comment by cychanglab** [comment]
Without --update it still displayed the notice of duplicate objects, same as the exercise with the option enabled. But no more complaints for me as the program itself invaluable for my productivity despite some minor encounters. Thank you both for the detailed explanations!

**Comment by ncw** [comment]
No problems.

I suggest you run [rclone dedupe](https://rclone.org/commands/rclone_dedupe/) on your drive to get rid of the duplicates since rclone does not deal well with them.

I'll close this for the moment - please re-open if this doesn't fix it.
