### ISSUE TITLE
vfs: filter files or directories called '.' or '..' from listings

### ISSUE THREAD

**Issue by ncw** [ncw/rclone#2135]
Files or directories called '.' or '..' are allowed in object storage systems and in drive for instance, but they confuse file system based things no end.

Filter any files or directories called '.' or '..' from the VFS directory listings (maybe with a debug).

**Comment by TenGumis** [comment]
@ncwI want to work on it.

**Comment by ncw** [comment]
@TenGumis - great!

It should be just a question of filtering them out in this function

https://github.com/ncw/rclone/blob/d5b2ec32f10bdb053e39dc172680b8723c459706/vfs/dir.go#L171
