### ISSUE TITLE
no rclone command on mounted cache remote

### ISSUE THREAD

**Issue by dual-oo** [ncw/rclone#2136]
I have the issue https://github.com/ncw/rclone/issues/1974 too.
But I have no / in remote

my config GD > cache > crypt > mount

[GD1]
type = drive
client_id =
client_secret =
service_account_file =
token =

[GD1_crypt]
type = crypt
remote = GD1_cache:crypt
filename_encryption = standard
directory_name_encryption = true
password =
password2 =

[GD1_cache]
type = cache
remote = GD1:
plex_url =
plex_username =
plex_password =
chunk_size = 8M
info_age = 8h
chunk_total_size = 10G

**Comment by ncw** [comment]
Can you post the panic please, plus a description of what you were doing and any log messages?

**Comment by dual-oo** [comment]
**i have mounted GD1_crypt with:**
rclone mount GD1_crypt: /mount --allow-non-empty --allow-other --cache-db-purge --cache-info-age=6h --cache-workers=10 --cache-chunk-size=8M --cache-total-chunk-size=10G --log-file="/logs/rclone_mount.log" &

**after that i will move a test MKV through GD > cache > crypt remote**
rclone move test.mkv GD1_crypt:temp
2018/03/13 21:26:04 ERROR : /root/.cache/rclone/cache-backend/GD1_cache.db: Error opening storage cache. Is there another rclone running on the same remote? failed to open a cache connection to "/root/.cache/rclone/cache-backend/GD1_cache.db": timeout
2018/03/13 21:26:06 ERROR : /root/.cache/rclone/cache-backend/GD1_cache.db: Error opening storage cache. Is there another rclone running on the same remote? failed to open a cache connection to "/root/.cache/rclone/cache-backend/GD1_cache.db": timeout
2018/03/13 21:26:06 Failed to create file system for "GD1_mount:temp": failed to make remote "GD1_cache:crypt/a01sis8n4j16t8k105s7h79ff0" to wrap: failed to start cache db: failed to open a cache connection to "/root/.cache/rclone/cache-backend/GD1_cache.db": timeout

**Comment by ncw** [comment]
I see...

> Error opening storage cache. Is there another rclone running on the same remote? failed to open a cache connection to "/root/.cache/rclone/cache-backend/GD1_cache.db": timeout

The error is saying that you can't run a mount, and another rclone command which uses the cache at the same time.

So either copy the file directly into the mount which should work fine, or make another remote **without** the cache and use that.

**Comment by dual-oo** [comment]
Thanks for the help! I got it.

**Comment by ncw** [comment]
No worries 😁

**Comment by oldsweatyman** [comment]
I'm also getting this error. Does anyone mind explaining a little further? I'm not understanding how to circumvent the issue.

How do I "make another remote without the cache" ?

Setup is similar to op: gdrive -> gcache -> gcrypt

Do I need to make **another** "crypt" remote (lets name it gcopy) of "gcrypt" THEN use my sync/copy/etc commands? 

example:
rclone sync /path/to/copy **gcopy**

**Comment by ncw** [comment]
> Do I need to make **another** "crypt" remote (lets name it gcopy) of "gcrypt" THEN use my sync/copy/etc commands?

Yes that is right, make a gcopy which is `gdrive -> gcrypt`

**Comment by oldsweatyman** [comment]
Thank you very much.

**Comment by oldsweatyman** [comment]
apologies for continuing to bother, im just still having some issues... can't wrap my head around it.

my setup: 

[gdrive]
type = drive
client_id =
client_secret =
service_account_file =
token =

[gcache]
type = cache
remote = gdrive:/gdrive
plex_url =
plex_username =
plex_password =
chunk_size = 5M
info_age = 1d
chunk_total_size = 10G

[gcrypt]
type = crypt
remote = gcache:/crypt
filename_encryption = standard
directory_name_encryption = true
password = *** ENCRYPTED ***
password2 = *** ENCRYPTED ***

[gcopy]
type = crypt
remote = gdrive:
filename_encryption = standard
directory_name_encryption = true
password = *** ENCRYPTED ***
password2 = *** ENCRYPTED ***

command im running: rclone sync /path/to/test/ gcopy:/NAS/path/to/test -P

i can't get files to show up on the mount. errors im getting from the mount: 

2020/02/24 22:35:06 NOTICE: Encrypted drive 'gcrypt:': ChangeNotify was unable to decrypt "gdrive/crypt": illegal base32 data at input byte 6
2020/02/24 22:38:06 NOTICE: Encrypted drive 'gcrypt:': ChangeNotify was unable to decrypt "gdrive": illegal base32 data at input byte 6
2020/02/24 22:38:06 NOTICE: Encrypted drive 'gcrypt:': ChangeNotify was unable to decrypt "gdrive/crypt": illegal base32 data at input byte 6

**Comment by ncw** [comment]
I think the remote is wrong in your `gcopy` - I think it needs to be `gdrive:/gdrive/crypt`

**Comment by oldsweatyman** [comment]
I switched it to your recommendation:

[gcopy]
type = crypt
remote = gdrive:/gdrive/crypt/
filename_encryption = standard
directory_name_encryption = true
password = *** ENCRYPTED ***
password2 = *** ENCRYPTED ***

i used the following commands:

rclone mount gcrypt: G: --allow-other --allow-non-empty --cache-db-purge --buffer-size 32M --use-mmap --dir-cache-time 72h --drive-chunk-size 16M  --timeout 1h  --vfs-cache-mode minimal --vfs-read-chunk-size 128M --vfs-read-chunk-size-limit 1G &

rclone sync C:\Users\Admin\Downloads\test.txt gcopy:

i still get the following error from the mount:

2020/02/25 08:51:41 NOTICE: Encrypted drive 'gcrypt:': ChangeNotify was unable to decrypt "sjqcif5v10cl3khit2ovub3poo": Bad PKCS#7 padding - too long

**Comment by oldsweatyman** [comment]
jeeze.. i figured out what was happening, silly mistake. for anyone else who has the problem:

**error i was making:** 

**i made the "gcopy" remote (gdrive:/gdrive/crypt), i was using the "n) new remote" command option** 

**correction:**

use the **"c) copy remote"** option -> selecting "gcrypt" -> change the remote path of the copy to gdrive:/gdrive/crypt -> success

I believe the "new" encryption was not compatible with the original one, and therefore I was getting an error.
