### ISSUE TITLE
Enable rclone asking for SSH password when needed

### ISSUE THREAD

**Issue by rawtaz** [ncw/rclone#2137]
#### What is the problem you are having with rclone?
Unable to have it ask for a password for an SFTP remote.

#### What is your rclone version (eg output from `rclone -V`)
rclone v1.39-DEV
- os/arch: darwin/amd64
- go version: go1.9

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
macOS 10.12.x, 64 bit

####  Which cloud storage system are you using? (eg Google Drive)
None, but SFTP.

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone copy a:foo b:bar

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
$ rclone -vv copy a:foo b:bar
2018/03/13 20:54:43 DEBUG : Using config file from "/Users/user/.config/rclone/rclone.conf"
2018/03/13 20:54:43 DEBUG : rclone: Version "v1.39-DEV" starting with parameters ["rclone" "-vv" "copy" "a:foo" "b:bar"]
2018/03/13 20:54:44 Failed to create file system for "b:bar": NewFs: couldn't connect SSH: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain

#### Point being
According to the documentation, it seems that you cannot have rclone ask for the SSH password when using the SFTP backend. If you don't put a `pass` or `pass_file` in the config, it will try to use the agent or keys, which naturally won't prompt for a password.

I would like to request that there's a way of having rclone ask for the SSH password if one hasn't specified a password or public keys aren't used. Either by simply configuring this somehow, or by an argument like `--ask-ssh-password`. The latter would be an explicit action by the user, in case you don't want this to be a default behavior. It would obviously only apply to SSH/SFTP, unless you name it in a more neutral way and have it apply to other relevant backends as well, if any.

**Comment by ncw** [comment]
An explicit option would be easy to add I think `--sftp-ask-password`.  This could just ask the user for the password at the point it is needed.

This could also be used in the FTP remote.

This would be reasonably straight forward - fancy having a go?

**Comment by rawtaz** [comment]
You mean having a Go :-) I'm happy to hear that you consider it a useful feature!

My Go is more or less non-existent, as is my time, but if I get a feel for it some dark night I will look into it. Can't make any promises though :)

For this specific case where I needed to transfer some files I just used `rsync` instead, so it's not a critical problem for me or anything. Let's keep it open and see who gets to it first!

**Comment by rawtaz** [comment]
Is there a guide anywhere on how to set up a clone of rclone sources for development? Just basic having source -> modifying it -> building it -> running it to test.

With e.g. [restic](https://restic.net) I can just clone the repository and run `go run build.go` in the resulting folder after modifying things, pretty neat. But what's the workflow with rclone sources?

**Comment by ncw** [comment]
> With e.g. restic I can just clone the repository and run go run build.go in the resulting folder after modifying things, pretty neat. But what's the workflow with rclone sources?

rclone is a standard go project, so just running `go build` in rclone's root directory will build it.

**Comment by rawtaz** [comment]
This might not be the place to ask but I know of none better, so..

In https://github.com/ncw/rclone/search?utf8=%E2%9C%93&q=ReadPassword&type= I see that there are two files providing one and the same function name, and this function is used in config.go. But how/where in the build process is it determined which one of these files is the one that's used? I grepped for "config_password" in the source tree but got no relevant hits.

I'm just trying to figure out what the proper way to prompt the user for a password is (in the end I need it in a string), and using the ReadPassword function from either of these files seems like a good idea. I'm not sure if you'd prefer one importing those modules and using them as they're named config, or if you'd prefer that one duplicate or rearrange the code so ReadPassword exists in a more neutral but central place. Feel free to chime in.

**Comment by rawtaz** [comment]
Hm. I'm pretty close to working code for this issue. But I hit a snag - it doesn't seem that my rclone attempts password authentication at all.

Even if I enter a password for the remote in the config (and one for the config itself), and run rclone, it gives me this instead of a successful login (the below is without any patches, just latest master):

~~~
$ rclone copy ~/test.txt myremote:test.txt
Enter configuration password:
password:
2018/03/14 16:47:53 Failed to create file system for "myremote.txt": NewFs: couldn't connect SSH: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none], no supported methods remain
~~~

Based on the `[none]` and of course the unsuccessful login, it seems that the `sshConfig.Auth = append(sshConfig.Auth, ssh.Password(clearpass))` in sftp.go never has any effect.

This is also consistent with the very first thing I tried manually when first digging into the code - I simply added `sshConfig.Auth = append(sshConfig.Auth, ssh.Password("myrealpassword"))` to verify that I could have some control over the code, but it didn't work either.

Any ideas why this might be? Once I get that working I think I can soon file a PR.

**Comment by ncw** [comment]
> I'm just trying to figure out what the proper way to prompt the user for a password is (in the end I need it in a string), and using the ReadPassword() function from fs/config seems like a good idea.

That seems fine to me :-)

> Any ideas why this might be?

If you put a password into the rclone config file (obscured) does it work?  I just tried and it does still work for me.

Are you putting two `ssh.Password` entries in maybe?

You could always push up a branch and link it so I can see the actual code - that might make debugging easier!

**Comment by rawtaz** [comment]
Putting a password into the config is what I did, yes. I used the guide to do so (edited the remote, chose to enter a password, saved the remote, set a password for the entire configuration, quit). Are you saying I should try to do it manually? The entire config is a hash basically :)

The code I reproduced it with above is without any patches or changes - it's just the pure rclone master branch unmodified. Compiled with Go 1.10 on macOS 10.12.

Just now I changed the relevant section to this:
~~~
        // Auth from password if specified
        if pass != "" {
                clearpass, err := obscure.Reveal(pass)
                if err != nil {
                        return nil, err
                }
                fmt.Println("BEFORE APPEND")
                sshConfig.Auth = append(sshConfig.Auth, ssh.Password(clearpass))
                fmt.Println("AFTER APPEND")
        }
~~~

This yields the following output after a rebuild:
~~~
$ go build && ./rclone copy ~/test.txt myremote:test.txt
Enter configuration password:
password:
BEFORE APPEND
AFTER APPEND
2018/03/14 22:45:34 Failed to create file system for "myremote:test.txt": NewFs: couldn't connect SSH: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none], no supported methods remain
~~~

I fail to see what I could be doing wrong here. Does it work for you it you use the guide to set the password for the remote? Then again, if the append of the password method to `Auth` was successful, it would say more than `[none]`, right?

What does your rclone say if you give it an invalid password, does it have anything more than `[none]` in the brackets? If yes, then for some reason the password method is not added as expected for me, but it is for you.

What system are you on BTW, are you testing with macOS too?

**Comment by rawtaz** [comment]
Figured it out! There was a problem with the SSH connection to the server in question. That one's on me :)

However, it's still very unclear to me why `[none]` is listed in the attempted methods both when `ssh.Password()` is appended and when it is not, and/or why something else representing the password method is not listed in the attempted methods when `ssh.Password()` is appended. I mean, we get `publickey` added to the list of attempted methods when that one is added, so.. This sure doesn't help a beginner with Go :-)

**Comment by ncw** [comment]
> Figured it out! There was a problem with the SSH connection to the server in question. That one's on me :)

:-)

> However, it's still very unclear to me why [none] is listed in the attempted methods

Possibly related to the server problems? SSH authentication is reasonably tricky so I guess it isn't always easy for the ssh library I use to come up with good error messages.

**Comment by rawtaz** [comment]
I don't understand why that would depend on the connection working or not. Surely the SSH lib should know what methods it's supposed to try, and be able to report on that? I feel it's inconsistent to the point that it's a bug. If we add the publickey method, that method is listed in the attempted methods. If we add the password method, that method is not listed in the attempted methods. That's inconsistent.

**Comment by rawtaz** [comment]
Hm, GitHub apparently doesn't use 80 characters width to cut off text..

**Comment by ncw** [comment]
> I feel it's inconsistent to the point that it's a bug

I'm not sure it is a bug in rclone though, I suspect a bug in in [pkg/sftp](https://github.com/pkg/sftp)...

**Comment by rawtaz** [comment]
Thanks! Adding FTP to the list of TODOs.
