### ISSUE TITLE
minor typos in docs

### ISSUE THREAD

**Issue by insulsa** [ncw/rclone#214]
in /docs/content/onedrive.md#Limitations

>Note that One Drive is case sensitive so you can't have a
>file called "Hello.doc" and one called "hello.doc".

here "sensitive" is use become "insensitive".

and in /docs/content/docs.md#Options

`These are the binary units,
eg 2**10, 2**20, 2**30 respectively.`

numeric power operator `**` make surrounded 10,2 rendered **strong** in markdown.

**Comment by ncw** [comment]
Thanks or those!  In fact I notices that I've got case sensitive and insensitive completely mixed up in the overview too!

**Comment by ncw** [comment]
These are live and on the website now - thanks!
