### ISSUE TITLE
s3: improve configurator for different service providers

### ISSUE THREAD

**Issue by ncw** [ncw/rclone#2140]
At the moment the s3 configurator is very biased towards AWS.

Perhaps a hierarchical approach would be a good idea so that first the user chooses a provider
  * Amazon
  * Digital Ocean
  * IBM COS
  * Wasabi 
  * CEPH
  * Other

Then based on those choices gets another list with relevant endpoints to choose from.

See #2124 for IBM COS configuration.

**Comment by gbadanahatti** [comment]
@ncw, did u have a design in mind for this? would like to take a crack at this.

**Comment by ncw** [comment]
@gbadanahatti all the config entry is done in one place at the moment so I'd like something which extends that framework in some way.

The simplest thing I can thing of would be too add a Provider string to reach config example entry. So aws or IBM etc (defined as constants). Then one of the first questions could be to choose the provider. If provider is set then the config backend could filter the examples to only show the relevant ones.

That would be very simple...

I'm not at my computer at the moment but I can go into more detail later if you want.

**Comment by gbadanahatti** [comment]
@ncw: Thanks!! Tried to translate to code. Let me know what you think.

1. In s3.go during Registration of FS:

                **Options: []fs.Option{ {
                       Name: "SubProvider",
                        Help: "Choose the S3 provider.",
                        Examples: []fs.OptionExample {
                        {
                                Value: "AWS",
                                Help: " Choose this option to configure Storage to AWS S3",

                        },
                        {
                                Value: "IBMCOS",
                                Help: "Choose this option to the configure Storage to IBM COS S3",
                        },
                 },**

2. Each Option gets tagged to a particular Sub Provider:

                       **{
                        Name: "env_auth",
                        Help: "Get AWS credentials from runtime (environment variables or EC2/ECS meta data if no env vars). Only applies if access_key_id and secret_access_key is blank.",
                        SubProvider: "AWS",
                        Examples: []fs.OptionExample{
                                {
                                        Value: "false",
                                        Help:  "Enter AWS credentials in the next step",
                                }, {
                                        Value: "true",
                                        Help:  "Get AWS credentials from the environment (env vars or IAM)",
                                },
                        },
                }, {
                        Name: "access_key_id",
                        Help: "AWS Access Key ID - leave blank for anonymous access or runtime credentials.",
                        SubProvider: "AWS,IBMCOS",**

3. The Config backend handles Configs based on the SubProviders:

**func NewRemote(name string) {
        newType := ChooseOption(fsOption())
        getConfigData().SetValue(name, "type", newType)
        fs := fs.MustFind(newType)
        for _, option := range fs.Options {
                var subProvider = getConfigData().MustValue(name, "SubProvider", "")
                if (option.SubProvider != "") {
                    if strings.Contains(option.SubProvider, subProvider) {
                      getConfigData().SetValue(name, option.Name, ChooseOption(&option))
                  }
                } else {
                   getConfigData().SetValue(name, option.Name, ChooseOption(&option))
                }
        }
        RemoteConfig(name)
        if OkRemote(name) {
                SaveConfig()
                return
        }
        EditRemote(fs, name)
}**

4. Option Struct will add a new field for SubProvider:

**type Option struct {
        Name       string
        Help       string
        SubProvider string
        Optional   bool
        IsPassword bool
        Examples   OptionExamples `json:",omitempty"`
}**

**Comment by ncw** [comment]
@gbadanahatti 

> 1. In s3.go during Registration of FS:

Yes that looks about right.  I prefer `Provider` rather than `SubProvider` though - easier for people to understand.

> 2. Each Option gets tagged to a particular Sub Provider:

Do we need to tag each Option?  I was thinking that we only needed to tag the `fs.OptionExample`s.  These contain the really provider specific stuff like the endpoints.  And they then should only need a single tag.

**Comment by gbadanahatti** [comment]
@ncw. Thanks!
The motivation for tagging options was really for the reason that some options are not relevant for IBM COS (and probably for others in the future) for example, SSE option and storage classes are not relevant, so I wanted to skip over those options completely.

**Comment by ncw** [comment]
@gbadanahatti wrote:
> The motivation for tagging options was really for the reason that some options are not relevant for IBM COS (and probably for others in the future) for example, SSE option and storage classes are not relevant, so I wanted to skip over those options completely.

Oh fine.  We probably need to tag both the Option and the OptionExample or were you thinking we'd just make complete new Options for each provider?

**Comment by gbadanahatti** [comment]
@ncw. The thought was that we make new options for each provider. I have that ready.
 I see that having tags for OptionExample will be beneficial as well. I will add that.

**Comment by ncw** [comment]
Thanks for your help with this @gbadanahatti I think this issue is now done :-)
