### ISSUE TITLE
Files greater than 50GB are attempted when uploading to Amazon Cloud Drive

### ISSUE THREAD

**Issue by michaelthwaite** [ncw/rclone#215]
When syncing up to ACD, files larger than 50GB (the limit) are attempted and then fail at completion (after some hours of copying). I think that they should be rejected with an error when discovered in the sync. Each time the sync is attempted the upload is attempted again.

And, thanks for a great utility, I've moved TBs with this tool already!

**Comment by ncw** [comment]
That is a good idea.  Do you have a link to a doc where Amazon state that 50GB is the limit - I can't seem to find a definitive answer.

Thanks for the suggestion and glad you like rclone!

**Comment by michaelthwaite** [comment]
Well, it's somewhere in the last three days of Googleing to find a good command line sync utility :-)

Here's what I know:
I was using GoodSync initially - a GUI based solution that was throwing errors on large files. I'm running that again to see if I can catch the exact error. I'm also testing a 68GB file on the Amazon Desktop App as well.

Here's the output from rclone at 99% copy complete on a large file of 68GB

---
Transferring:
 *                             BackupHistory.tgz: 77% done. avg: 3203.9, cur: 10436.1 kByte/s. ETA: 28m0s
 *  Google Drive/Google Drive backup 2014-10.zip: 99% done. avg: 3549.0, cur: 8952.9 kByte/s. ETA: 20s

2015/11/14 00:42:00 pacer: Rate limited, sleeping for 430.193442ms (1 retries)
2015/11/14 00:42:00 Google Drive/Google Drive backup 2014-10.zip: Received error: HTTP code 500: "500 Internal Server Error", reponse body: {"message":"Internal failure"}
 - retrying 1/10
---

Here again after getting to 100% of another large file:

---
Transferring:
 *                             BackupHistory.tgz: 100% done. avg: 3678.5, cur: 3038.1 kByte/s. ETA: 0s
 *  Google Drive/Google Drive backup 2014-10.zip: 39% done. avg: 11407.1, cur: 16208.0 kByte/s. ETA: 41m11s

2015/11/14 01:20:35 pacer: Rate limited, sleeping for 552.437724ms (2 retries)
2015/11/14 01:20:35 BackupHistory.tgz: Received error: HTTP code 500: "500 Internal Server Error", reponse body: {"message":"Internal failure"}
 - retrying 1/10
---

And again with the first file as it was tried again (some hours later):

---
Transferring:
 *                             BackupHistory.tgz: 41% done. avg: 8503.1, cur: 9268.1 kByte/s. ETA: 1h21m22s
 *  Google Drive/Google Drive backup 2014-10.zip: 100% done. avg: 10798.5, cur: 10758.0 kByte/s. ETA: 0s

2015/11/14 02:24:46 pacer: Rate limited, sleeping for 1.579800709s (3 retries)
2015/11/14 02:24:46 Google Drive/Google Drive backup 2014-10.zip: Received error: HTTP code 500: "500 Internal Server Error", reponse body: {"message":"Internal failure"}
 - retrying 2/10
2015/11/14 02:24:47 acd: Saving new token in config file
---

It's a lousy error from Amazon!

I'm sorry to give you such a difficult, well, time consuming, issue as it takes a good hour to copy that amount of data.

I'll check back in with the results of the desktop app and GoodSync big file copy to see what they report.

MPT

**Comment by michaelthwaite** [comment]
Update: Amazon Cloud App: It did the same, copied 68GB then, just started again.

**Comment by ncw** [comment]
Here is the best statement from Amazon that I've found [about the 50GB limit](https://forums.developer.amazon.com/forums/thread.jspa?threadID=4610)

You could use `--max-size=50GB` on the command line to get rclone to skip these files which would be a workaround. 

Rclone can upload files bigger than 10GB but it has a problem downloading them at the moment -  see #204

**Comment by michaelthwaite** [comment]
Update: GoodSync failed to copy up a large file (128GB) with this error:

2015-11-14 13:35:02: == Sync Started by Analyze And Sync Command
2015-11-14 13:35:02: File Systems limited number of parallel threads to 4
2015-11-14 13:35:02: Start only 1 threads, limited by tasks to run
2015-11-14 22:08:31: Copy New '/Users/michael/tmp/bigfile128' -> 'amazoncd://drive.amazonaws.com/test/bigfile128'
- ERROR: Copying file: Server says: Bad Request (status code 400): Cannot complete upload
2015-11-14 22:08:32: Reconnected Folders in the main Sync thread after >= 30 min of inactivity
2015-11-14 22:08:34: == Sync Complete. Time: 08:33:32, Speed: 4.3 MB/s, OK: 0, Errors: 1
2015-11-14 22:08:34:

**Comment by ncw** [comment]
What I can do is put a 50GB max size for transfer in the acd remote.  This will give an error when you try to upload/download a file of that size.  I'd probably control that with a flag `--acd-max-size` which defaults to 50GB.

To not see the error and have a clean sync you'd need to use the `--max-size=50GB` command line option (the error it returns could suggest that).

What do you think?

(See also my previous comment)

**Comment by michaelthwaite** [comment]
I'm getting nervous now as, there's supposed to be a 10GB max download size and I've been able to download bigger files and, reading the developer forum indicates that Amazon is constantly working to increase file size limits. Ideally, they should (we should lobby them to) include a max file size indicator in the API so that you can build to that.

Any flag you put in today could be invalidated tomorrow - especially since the Amazon app fails as well, it may be a legitimate bug. Perhaps, if an upload fails with a 500 error at the end, it should be marked and not re-tried - the issue that I had was that rclone would retry again, effectively wasting many hours.

For now, perhaps a warning in the release notes and I'll using your existing  --max-size=50GB flag. Thoughts?

**Comment by michaelthwaite** [comment]
FYI, I found the reference to the 50GB limit - https://github.com/yadayada/acd_cli

**Comment by felixbuenemann** [comment]
Btw. I tried to find the actual maximum today, but didn't find the exact value.

I tested:

* 50 GiB – 408 and never appeared (same amount of bytes as `--max-size 50G`)
* 49 GiB – 408 and never appeared
* 50 GB (46.566 GiB) – worked (408 and appeared after ~15min)
* 50 GB + 1 Byte – worked (408 and appeared after ~15min)
* 50,000 MiB (48.828 GiB) – worked (408 and appeared after ~15min)
* 50,000 MiB + 1 Byte – worked (408 and appeared after ~15min)

So the actual limit appears to be somewhere between 50 GB and 49 GIB.

I did give up after spending around 600 GB of intra region traffic…

**Comment by ncw** [comment]
@felixbuenemann nice one. Fancy sending a pull request to adjust the values in 4ce2a84?

**Comment by felixbuenemann** [comment]
Yes, I can do that. I should run at least a second test at the 50 GiB and 49 GiB values, to make sure it wasn't coincidence that those files didn't appear.

**Comment by felixbuenemann** [comment]
I checked with the Mac client and it limits the file size to exactly 50,000 MiB so we should use the same limit. I also had a failed upload when trying rclone copy with a 48.91 GiB file.

I'll open a PR shortly.
