### ISSUE TITLE
cache to add an empty if it receives a notification

### ISSUE THREAD

**Issue by remusb** [ncw/rclone#2155]
started from here: https://github.com/ncw/rclone/issues/2117

basically: cache should be able to create a dir on the fly when it gets notifications related to it.

**Comment by seuffert** [comment]
if possible please also include nested folders (e.g. /old/dir/newly/created/nested/folder)

**Comment by remusb** [comment]
Yeah, it should create every component of the absolute OR expire it if it exists.

**Comment by seuffert** [comment]
@remusb are you already on this? otherwise i might give it a swing

**Comment by remusb** [comment]
I wanted to start on it but I got a terrible cold and too much work related stuff lately. Take it if you want

@seuffert

**Comment by seuffert** [comment]
@remusb sorry i couldn't start on this, also caught the flu :( will ping back here after i recovered

**Comment by stokkes** [comment]
Hi guys, 

Any chance this is being worked on? This may be one of the final components to a legitimate cache solution that stays updated across multiple hosts.

Thank you for your efforts!

**Comment by Qwatuz** [comment]
@remusb @seuffert have you guys recovered from the cold/flu? :smiley:

**Comment by jrarseneau** [comment]
Thank you for all your hard work on this @remusb @seuffert !

**Comment by remusb** [comment]
Beta for this: https://beta.rclone.org/v1.41-106-gaaa85916/
Turned out to be a bit more simpler than I imagined.

@jrarseneau @seuffert @stokkes @Qwatuz
