### ISSUE TITLE
Add link to rclone QNAP app

### ISSUE THREAD

**Issue by Cadish** [ncw/rclone#2156]
There is a QNAP app to easily install rclone on a QNAP NAS. I believe it would be useful to add this to the documentation of rclone.

Download of apps: https://qnapclub.eu/nl/qpkg/330
Support forum: https://forum.qnap.com/viewtopic.php?f=320&t=123914

**Comment by ncw** [comment]
To start with stick it in [the rclone wiki](https://github.com/ncw/rclone/wiki) - perhaps in a new page 3rd party installers?

There are quite a few other installers (eg brew) that I don't maintain that could go on that page.

**Comment by Cadish** [comment]
Great! Didn't know that page existed. 
Added.

**Comment by ncw** [comment]
Thanks for doing that :-)
