### ISSUE TITLE
rclone sync fails to delete versioned files on B2 (400 already_hidden)

### ISSUE THREAD

**Issue by cowwoc** [ncw/rclone#2159]
#### What is the problem you are having with rclone?
"rclone sync" fails to delete files on B2

#### What is your rclone version (eg output from `rclone -V`)
rclone v1.40
- os/arch: windows/amd64
- go version: go1.10

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Windows 10, 64bit

####  Which cloud storage system are you using? (eg Google Drive)
B2

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
`rclone sync --stats-log-level NOTICE --fast-list --delete-excluded --transfers=10 -vv --exclude "My Documents/**" --exclude "NetHood/**" --exclude "Start Menu/**" --exclude "SendTo/**" --exclude "Templates/**" --exclude "Application Data/**" --exclude "PrintHood/**" --exclude "Cookies/**" --exclude "Recent/**" --exclude "Local Settings/**" --exclude "My Music/**" --exclude "My Videos/**" --exclude "Favorites/**" --exclude "My Pictures/**" --exclude "NTUSER.DAT*" --exclude "ntuser.dat*" --exclude "AppData/Roaming/Microsoft/Windows/Recent/**" c:/users/gili "encrypted:gili"`

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
rclone runs for a while and at the end it tries to delete files from B2:

`2018/03/21 03:31:51 ERROR : AppData/Roaming/Dashlane/5.6.0.15520/ressources/NewResources/MainWindow/Services/Payments/card-edit-red.png: Couldn't delete: failed to hide "gili/AppData/Roaming/Dashlane/5.6.0.15520/ressources/NewResources/MainWindow/Services/Payments/card-edit-red.png.bin": File already hidden: gili/AppData/Roaming/Dashlane/5.6.0.15520/ressources/NewResources/MainWindow/Services/Payments/card-edit-red.png.bin (400 already_hidden)`

I get this error 100% of the time when running my backup. The files in question remain on the B2 server. The problem might have to do with the fact that B2 contains multiple versions of this file (so there are multiple filenames corresponding to this same file on the server).

**Comment by cowwoc** [comment]
Closing this issue because I now believe this was a race condition of sorts. I believe "400 already_hidden" means that the file is marked as deleted on the server but prior versions exist. In this case, I am okay with prior versions being kept ("hidden" is probably b2's terminology for marked as deleted but has older versions).

**Comment by ncw** [comment]
@cowwoc you are correct that "400 already_hidden" means the file is already deleted.

However rclone shouldn't be trying to delete the file if it is already hidden as it shouldn't appear in the directory listings.

Does it do it on just these particular files?

if you do

    rclone ls --fast-list encrypted:gili/AppData/Roaming/Dashlane/5.6.0.15520/ressources/NewResources/MainWindow/Services/Payments/

Do you see the `card-edit-red.png` files in the listing?

I'm wondering whether the files could have got into a funny state at B2 somehow?

**Comment by cowwoc** [comment]
> Do you see the card-edit-red.png files in the listing?

No. But if I add `--b2-versions` I see:

```
1510 card-edit-red.png-v2018-03-16-233409-000
```

Also, I haven't seen the "400 already_hidden" error repeat itself. It seems that B2 marked the files as deleted in spite of the error, so rerunning the same command does not result in the same error because the files are already hidden.

Remember that I have `--transfers 10` set, which is why I'm thinking maybe there is a race-condition going on. Anyway, unless you have any ideas on how to reproduce this problem (I no longer do) then I think we can close this issue. I will reopen it if I ever see the error again.
