### ISSUE TITLE
Malformed rule error

### ISSUE THREAD

**Issue by enkia** [ncw/rclone#216]
I get the following error:
```bash
2015/11/14 12:42:23 Failed to load filters: Malformed rule "_gsdata_/**"
```

...when using:
```bash
rclone sync --checksum --bwlimit=1M --filter-from="rclone-filters.txt" acd:sites ~/sites
```

But no errors when using:

```bash
rclone sync --checksum --bwlimit=400k --filter-from="rclone-filters.txt" ~/sites acd:sites
```

This is my **rclone-filters.txt** file:
```
- _gsdata_/**
- _saved_/**
- node_modules/**
- bower_components/**
- **.git/**
- .DS_Store
- Thumbs.db
- .vagrant/**
- .sass-cache/**
- **.bower**
- .debris/**
- *.com*
- Icon?
- .otto/**
- files/cache/**
- files/tmp/**
+ .gitignore
```

I just updated to **v1.25** and received no malformed rule errors prior to the update. I updated to [fix this issue.](https://github.com/ncw/rclone/issues/205)

**Comment by ncw** [comment]
I tried to reproduce this but failed.

The filtering code didn't change from v1.24 to v1.25.

That error comes from the bit of code where rclone is checking that the rules start with `+ ` or `- `.

So it looks like one of these
  * maybe there is an invisible control char in your filters file
  * maybe rclone's line parser isn't working on your platform

So to help resolve that, can you
  * email me a zip (I don't want email to interfere with the line endings hence the zip) of the `rclone-filters.txt` file (to nick@craig-wood.com) or alternatively post a hex dump of the file (eg using `xxd -g1 rclone-filters,txt` if using linux)
  * tell me which platform (OS, 32/64 bits, OS version) you are using
  * double check you get different behaviours with the same file for rclone v1.24 and v1.25 - I find that hardest of all to understand so I'd really appreciate a double check.

Thanks

Nick

```go
func (f *Filter) AddRule(rule string) error {
	switch {
	case rule == "!":
		f.Clear()
		return nil
	case strings.HasPrefix(rule, "- "):
		return f.Add(false, rule[2:])
	case strings.HasPrefix(rule, "+ "):
		return f.Add(true, rule[2:])
	}
	return fmt.Errorf("Malformed rule %q", rule)
}
```

**Comment by enkia** [comment]
I did some further troubleshooting at your request and found that the problem lies elsewhere. At first I thought it was an issue using rclone with aliases because I got no errors using v1.25 when not using this alias:

```
alias pullsites='rclone sync --checksum --bwlimit=1M --filter-from="rclone-filters.txt" acd:sites ~/sites'
```

The baffling thing is, though, that through tinkering around with the alias and switching around rclone versions, using the alias, not using the alias, etc, I've stopped getting the error completely on one computer and started getting a different error on another computer using the alias or not.

```
2015/11/15 10:47:33 Starting bandwidth limiter at 1MBytes/s
2015/11/15 10:47:33 Unknown command "acd:sites"
```

I get this error using either version of rclone even though `rclone lsd acd:sites` works. So basically, I broke rclone on one of my macs. :)

I'm using OSX El Capitan on both computers. Here's the hex dump but the issue doesn't seem to be with the filters file itself. 

```
0000000: 2d205f6773646174615f2f2a2a0a2d20  - _gsdata_/**.-
0000010: 5f73617665645f2f2a2a0a2d206e6f64  _saved_/**.- nod
0000020: 655f6d6f64756c65732f2a2a0a2d2062  e_modules/**.- b
0000030: 6f7765725f636f6d706f6e656e74732f  ower_components/
0000040: 2a2a0a2d202a2a2e6769742f2a2a0a2d  **.- **.git/**.-
0000050: 202e44535f53746f72650a2d20546875   .DS_Store.- Thu
0000060: 6d62732e64620a2d202e76616772616e  mbs.db.- .vagran
0000070: 742f2a2a0a2d202e736173732d636163  t/**.- .sass-cac
0000080: 68652f2a2a0a2d202a2a2e626f776572  he/**.- **.bower
0000090: 2a2a0a2d202e6465627269732f2a2a0a  **.- .debris/**.
00000a0: 2d202a2e636f6d2a0a2d2049636f6e3f  - *.com*.- Icon?
00000b0: 0a2d202e6f74746f2f2a2a0a2d206669  .- .otto/**.- fi
00000c0: 6c65732f63616368652f2a2a0a2d2066  les/cache/**.- f
00000d0: 696c65732f746d702f2a2a0a2b202e67  iles/tmp/**.+ .g
00000e0: 697469676e6f72650a0a0a            itignore...
```

**Comment by ncw** [comment]
Glad you've managed to fix it.

If you do see the error again and can reproduce it then do reopen the issue.

Thanks

Nick
