### ISSUE TITLE
Ftp with connections limits

### ISSUE THREAD

**Issue by Speedy37** [ncw/rclone#2166]
#### What is the problem you are having with rclone?

I'm unable to limit the number of parallel FTP connections rclone is making.

#### What is your rclone version (eg output from `rclone -V`)
v1.40-DEV (master)

#### Which OS you are using and how many bits 

Alpine Linux 3.7 docker (https://hub.docker.com/r/speedy37/docker-restic-rclone/)

####  Which cloud storage system are you using? (eg Google Drive)

OVH backup FTP

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

rclone ls ftp:

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

```
2018/03/22 10:35:05 ERROR : ftp://my_host:21: Error while Logging in into my_host:21: 421 I can't accept more than 3 connections as the same user
```

Looking at the ftp backend code, I saw that the pool size is unlimited, having the possibility to limit that would be great.

**Comment by ncw** [comment]
You should be able to limit the number of ftp connections to 2 with with `--checkers 1` and `--transfers 1`.

Those control rclone concurrency.  It should really say that in the ftp and the sftp documentation though!

**Comment by Speedy37** [comment]
At least the "ls" command doesn't seem respect --checkers 1 and --transfers 1.

I did use --transfers 1 in the first place (the backup stage), it worked.
But some restic commands like ls/check/... use ls.

**Comment by gsauthof** [comment]
Hm, `rclone ls ftp:` fails for me in the described way:

    530 Sorry, the maximum number of clients (1) from your host are already connected.

But `rclone --checkers 1 --transfers 1 ls ftp:` does help and all files are displayed.

(rclone v1.44)

I plan to use that rclone destination with restic - is there a work-around to limit the number of connections in that scenario? For example via a key in `~/.config/rclone/rclone.conf` or an environment variable?

**Comment by Speedy37** [comment]
So far, I've only been able to limit rclone/restic to a max of 2 connections.

```
export RCLONE_CHECKERS=1
export RCLONE_TRANSFERS=1
/usr/local/bin/restic -o rclone.connections=2 ...
```

**Comment by ncw** [comment]
> So far, I've only been able to limit rclone/restic to a max of 2 connections.
> 
> ```
> export RCLONE_CHECKERS=1
> export RCLONE_TRANSFERS=1
> /usr/local/bin/restic -o rclone.connections=2 ...
> ```

Do you want to warm up your pull request to add a token dispenser with a flag to control the concurrency?

**Comment by Speedy37** [comment]
I don't have time for this right now.

**Comment by gsauthof** [comment]
(meanwhile I found `RCLONE_*` in the rclone manual, but I was still missing the `-o rclone.connections=...` restic option in my last experiments).

Unfortunately, this only works for the init/backup/forget restic commands - and not for prune. With prune I still get a bunch of `530 Sorry, the maximum number of clients (1) from your host are already connected`  messages (I use `rclone.connections=1` because the server really enforces a limit of 1 connection).

However, the restic prune still finishes with success:

    [..]
    finding old index files
    saved new indexes as [e4218bc4]
    remove 8 old index files
    [0:00] 100.00%  8 / 8 packs deleted
    done

**Comment by ncw** [comment]
Try this - I added an `--ftp-concurrency` flag.  You can also put `concurrency = 1` in your ftp remote config.

https://beta.rclone.org/branch/v1.46.0-021-gc21543bb-fix-2166-ftp-concurrency-beta/ (uploaded in 15-30 mins)

**Comment by ncw** [comment]
I've merged this to master now which means it will be in [the latest beta](https://beta.rclone.org) in 15-30 mins and released in v1.47

**Comment by mikolysz** [comment]
This is also an issue for Webdav.

The server I need to connect to bans you if you use more than 1 connection at a time, with manual intervention required from the admin staff to reverse the ban, so using `--checkers` and `--transfers` won't work, as that can only limit you to 2 connections maximum.

**Comment by ncw** [comment]
@mikolysz try `--checkers 1 --transfers 1 --check-first`
