### ISSUE TITLE
OneDrive sync very slow

### ISSUE THREAD

**Issue by TripleEmcoder** [ncw/rclone#217]
I am comparing second sync times for One Drive and Google Drive - they are drastically different for comparable accounts.

OneDrive:
Transferred:       835614 Bytes (   0.07 kByte/s)
Errors:               105
Checks:             25710
Transferred:          315
Elapsed time:   3h14m9.2s

Google Drive:
Transferred:    363128432 Bytes ( 708.39 kByte/s)
Errors:                 0
Checks:              7165
Transferred:          101
Elapsed time:     8m20.5s

What could be the cause of this? Both syncs were run separately with --checkers=1 --transfers=1 because it was on an ARM system with limited multithreading.

**Comment by ncw** [comment]
Can you do a like for like comparison - that would be useful.  What you've posted above the accounts look quite different.

Does the sync go wrong and need to get retried?

I recommend for drive and onedrive you don't set `--checkers=1` - that will really slow down the syncs as it will slow down directory traversal.  You can leave `--transfers=1`.

Here is a quick test I performed

Drive initial sync
```
Transferred:    179349706 Bytes ( 248.44 kByte/s)
Errors:                 0
Checks:              1416
Transferred:         1392
Elapsed time:    11m44.9s
```

Onedrive initial sync
```
Transferred:    182651899 Bytes ( 160.50 kByte/s)
Errors:                 0
Checks:              3954
Transferred:         1522
Elapsed time:    18m31.3s
```

Second sync drive
```
Transferred:            0 Bytes (   0.00 kByte/s)
Errors:                 0
Checks:              1391
Transferred:            0
Elapsed time:        7.1s
```

Second sync onedrive
```
Transferred:      4357352 Bytes (  92.85 kByte/s)
Errors:                 0
Checks:              2770
Transferred:           22
Elapsed time:       45.8s
```

I just discovered #218 which may be related - do any of your files have a `+` in the name?

**Comment by TripleEmcoder** [comment]
Yes, I do have some files with + in them, but as far as I understand #218 this only causes them to be reuploaded/redownloaded. None of these files are particularly large, so I don't believe this is the reason of the slowdown.

I know my OneDrive account is a bit bigger - 3.5x more checks, but the running time was 22.5x longer.

Is it possible that OneDrive is throttling access on their end? How does rclone identify to the server if no application client ids are provided during account configuration?

**Comment by ncw** [comment]
#218 will cause the sync to be retried - 3 times by default. Do you see that? 

Rclone uses its own application client ids if you left them blank.

**Comment by TripleEmcoder** [comment]
But you mean it will retry that single file with a +? Or do you mean it will do everything 3 times?

**Comment by ncw** [comment]
Both! It will retry the file and if that fail retry the sync 3 times...

**Comment by ncw** [comment]
I did a comparison between drive and onedrive.  For me One drive is 2.3x slower than drive.  I don't know whether that is because one drive is slower than drive, or the rclone code for one drive isn't optimised as much as it should be.

I suspect your massive time difference is due to #218 though

## Drive ##

```
Transferred:    489935279 Bytes ( 896.30 kByte/s)
Errors:                 0
Checks:                 0
Transferred:         1141
Elapsed time:     8m53.8s
```

## One Drive ##

```
Transferred:    492778198 Bytes ( 386.08 kByte/s)
Errors:                 0
Checks:              1136
Transferred:         1146
Elapsed time:    20m46.4s
```

This had one retry to tidy up 5 failed files which took an extra 4 minutes

**Comment by ncw** [comment]
I'm going to close this as I don't think I can do anything about it - I think it is Microsoft's infrastructure which is probably faster now anyway!
