### ISSUE TITLE
FTP mkParentDir fail if parent dir is not existing (when copying files)

### ISSUE THREAD

**Issue by easy90rider** [ncw/rclone#2181]
#### What is the problem you are having with rclone?
Copying files via FTP will fail if the file is in a subfolder of a subfolder.

-v log:
ERROR : existing/toBeCreated/toBeCreated/toBeCreated/fileToBeCopied.ext: Failed to copy: Put mkParentDir failed: 550 Action not taken

#### What is your rclone version (eg output from `rclone -V`)
issue is present in v1.39-v1.40

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Windows 10 64bit

####  Which cloud storage system are you using? (eg Google Drive)
FTP

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone copy local ftp

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
only relevant part is kept:
https://pastebin.com/Zu1pY1pP

**Comment by ncw** [comment]
Which FTP server is this?

I'm going to need to replicate this to fix it, any suggestions?

**Comment by easy90rider** [comment]
It's one used by my ISP ( ftp://storage.rcs-rds.ro/ ). 
I think they use some 'home made' server. I will try to find out exactly what they use.
Is there a way to find out what they use? (some linux commands, for ex?)

**Comment by ncw** [comment]
Yes it does look home made!

```
$ telnet storage.rcs-rds.ro ftp
220 Digi Storage FTP 1.0
```

BTW I note they support webdav too: https://storage.rcs-rds.ro/help/webdav (well maybe - I can't read what it says on the page!) and rclone has a [webdav backend](https://rclone.org/webdav/)

**Comment by easy90rider** [comment]
> $ telnet storage.rcs-rds.ro ftp
> 220 Digi Storage FTP 1.0

Oh, I got this too, I just wasn't 100% sure it is the server info.

I will open a ticket with them too, maybe they can tell me the server they used to make their own.

If not, I will have to use webdav. I have before...

BTW, filezilla doesn't have this issue.

**Comment by ncw** [comment]
> BTW, filezilla doesn't have this issue.

FileZilla is a very clever bit of software with lots of workarounds for odd FTP servers!

BTW It might be worth trying [the latest beta](https://beta.rclone.org) as I updated the FTP library to latest in it.  I didn't check the changelog so there might be no difference.

**Comment by easy90rider** [comment]
No, sadly the issue is still there...

I did try the webdav, but it seems there are issues with that too, it copied everything almost twice, after that I did another copy via FTP and it copied only the new files. 
I even tried webdav with --ignore-existing.

**Comment by ncw** [comment]
@easy90rider is there any chance you could get me a login to this FTP server? Or maybe I could borrow yours for a short while?  Email me at nick@craig-wood.com if you think that would be possible (put a link to this issue in the email so I have some context) - thanks.

**Comment by easy90rider** [comment]
@ncw the support from the ISP / provider called me and they promised that they will send a test user. 
As soon as I have that I will send it to you.

**Comment by qodo** [comment]
I am seeing this issue too possibly with a custom FTP server.
I can provide some test login credentials if this would help diagnose the issue?

Thanks,

**Comment by ncw** [comment]
@easy90rider thank you for the credentials!  I've used them to fix the issue.

https://beta.rclone.org/v1.40-126-gae562b5a/ (uploaded in 15-30 mins)

This will be in [the latest beta](https://beta.rclone.org) from now on and in 1.41.

Please re-open if it doesn't fix the problem for you.  Rclone's integration tests work against that server now which is good!

@qodo can you test that too and if it doesn't work then make a new issue and send some test credentials! - thanks!

**Comment by ncw** [comment]
@easy90rider thanks for testing :-)
