### ISSUE TITLE
Time is different when viewed through type = cache

### ISSUE THREAD

**Issue by zenjabba** [ncw/rclone#2183]
Version 1.40 (Release)

```
root@plexstreamer1:/etc/systemd/system# rclone lsd misc:/
          -1 2018-02-20 01:24:42        -1 Plex
root@plexstreamer1:/etc/systemd/system# rclone lsd misc_cache:/
          -1 2018-02-19 20:24:42        -1 Plex
```

**Comment by ncw** [comment]
Which one is correct?

And what is your timezone?  I'm guessing one of those is correct and the other is the time at GMT/UTC.

**Comment by zenjabba** [comment]
Both are correct.. one is EST one is GMT but it’s the same location. basically the cache one seems to be using GMT even though everything else is using system timezone

**Comment by ncw** [comment]
@remusb thoughts?

**Comment by remusb** [comment]
There's nothing in cache that I can think of that calculates time apart from cache expiry and that is not an information exposed outside of cache.

Information is cached though as is file data so isn't it just a cached timestamp there? Is it the modified date?

**Comment by ncw** [comment]
Ls will be reading the modtime from the cache backend. Go times have timezone baked in so I guess that that has been lost on a round-trip through the cache or maybe ls is displaying it wrong... AFK right now otherwise I would investigate further.

**Comment by remusb** [comment]
Ah I understand better now. So it's likely in the JSON conversion where this is lost. Probably the default conversion strips of the timezone info in Go but they're essentially the same point in time.

Typically the formatter should output in a strict format (system or some hardcoded timezone) from all sources. But if cache is the only one that behaves like this then I can probably manipulate the returned TS in the interfaces to match the system timezone.

**Comment by ncw** [comment]
@remusb just had a squint at the code - you are using the standard serializer for `time.Time` which does include the timezone and this seems to [correctly round trip through json](https://play.golang.org/p/f5-T2w6T9Sa).

> Typically the formatter should output in a strict format (system or some hardcoded timezone) from all sources. But if cache is the only one that behaves like this then I can probably manipulate the returned TS in the interfaces to match the system timezone.

Yes it should... Let me see what it is doing...

```go
func ListDir(f fs.Fs, w io.Writer) error {
//...
				syncFprintf(w, "%12d %13s %9d %s\n", dir.Size(), dir.ModTime().Format("2006-01-
```

Wheras the implementation for `lsl` has `.Local()` in like it should.

```go
		syncFprintf(w, "%9d %s %s\n", o.Size(), modTime.Local().Format("2006-01-02 15:04:05.000000000"), o.Remote())
```

So I think fixing this will probably fix the original problem, with no changes needed to the cache backend.

@zenjabba can you give this a go to see if it fixes the problem please?

https://beta.rclone.org/v1.40-031-g8a7b63de-lsd-timezone/ (uploaded in 15-30 mins)

**Comment by zenjabba** [comment]
will test tonight.

**Comment by zenjabba** [comment]
root@plexstreamer1:~/streamerthompsons# rclone lsd source:
          -1 2017-12-01 23:54:20        -1 s5dri5l6lhg70tqicfopng89h4
root@plexstreamer1:~/streamerthompsons# rclone lsd source_cache:
          -1 2017-12-01 23:54:20        -1 source

Fixed
