### ISSUE TITLE
rc-addr not adhered to for rc commands

### ISSUE THREAD

**Issue by esticle** [ncw/rclone#2184]
Hi,

Trying out the rc flag I noticed it works as expected for a mount:

```
user@mybox:~/tmp$ ps auxww | grep rclone
user    5843 16.0 10.1 1033124 826204 ?      Sl   Mar26 160:42 rclone --config /home/user/.rclone-gdrive.conf mount --allow-other --dir-cache-time=1m --cache-tmp-upload-path=/home/user/.cache/rclone-gdrive-cache-upload --cache-db-path=/home/user/.cache/rclone-gdrive-cache-upload --cache-chunk-size=8M --cache-info-age=6h --cache-tmp-wait-time=10m --cache-workers=2 --buffer-size=16M --attr-timeout=1s --cache-writes --rc --rc-addr=192.168.99.44:5572  gdrive-data-cache-crypt: /mnt/rclone-gdrive

user@mybox:~/tmp$ netstat -an | grep 5572
tcp        0      0 192.168.99.44:5572      0.0.0.0:*               LISTEN
```

However notice that when using the 'rc' flag with '--rc-addr' spesified it stlil tries to connect to localhost:

```
user@mybox:~/tmp$ rclone rc --rc-addr=192.168.99.44:5572 cache/expire remote=gdrive-data-cache-crypt:.removemefromcache/
2018/03/27 08:58:09 Failed to rc: connection failed: Post http://localhost:5572/cache/expire: dial tcp 127.0.0.1:5572: connect: connection refused
```

Should 'rc' not honour 'rc-addr' ?

Tried this up to v1.40-025-g1ba3ffdc / 26 March nightly

Thanks!

**Comment by ncw** [comment]
Hmm, the docs are inconsistent with the code!

I intended to make the --rc-addr flag work but it seems to actually be reading from a --url flag :-(

**Comment by esticle** [comment]
Excellent thanks! - slight ask for a feature request - would be nice to listen on multiple IP's/ports - specifying --rc-addr twice takes the last value.

**Comment by remusb** [comment]
@esticle what's the use case for that? You want multiple servers on the same rclone process or just listening on multiple interfaces?

The first should be done externally through a LB-like or reverse proxy.

**Comment by ncw** [comment]
@esticle you can listen on all IPs easily enough, just omit the host, eg `:8080`

**Comment by esticle** [comment]
Thanks @ncw was not aware!

@remusb purely for _also_ listening on 127.0.0.1 since the 'rc' command uses that if 'addr' is not specified but since I can listen on all interfaces it does not matter.

Thanks gents!

**Comment by daniel-loader** [comment]
Is the --rc-addr flag working now?

**Comment by ncw** [comment]
I've fixed this in

https://beta.rclone.org/v1.40-130-gd8e88f10/ (uploaded in 15-30 mins)
