### ISSUE TITLE
rc: add trigger upload for cache remote

### ISSUE THREAD

**Issue by daniel-loader** [ncw/rclone#2188]
Would it be possible to add a manual trigger to override the existing timer set at mount time?
Thoughts @remusb?

Something along the lines of `rclone rc cache/upload` optionally have `rclone rc cache/upload remote=path/to/file/in/queue` to pull it from queue and start immediately, possibly concurrently if the queue is already processing an upload. 

Functionality of the former would just be along the lines of "if files in upload cache, start upload now in order they were written".

**Comment by remusb** [comment]
What's the use case for it @daniel-loader ? Cache will try and make things transparent to the readers about files in the queue. It will allow reading, updates (if it hasn't started uploading already).

**Comment by daniel-loader** [comment]
Originally it was because occasionally I'd get a huge backlog of files uploading and want one done urgently and because I can't operate on the same mount that has a cache due to the database lock (when using crypt) it was frustrating it you've got an hour long queue. 

My solution was to move to a gigabit pipe. Hah. So really can mark this closed
