### ISSUE TITLE
Add a SIGINFO handler

### ISSUE THREAD

**Issue by kubatasiemski** [ncw/rclone#2189]
During copying large file sometimes we want to know the progress. The idea (based on cp (macOS) behaviour) is to print information about progress of copying when rclone receives a siginfo. 

>$ rclone sync source/ex.am dest/ex.am
>$ (press ctrl + T)
>$ filename 16%

To know more about cp behaviour on macOS please look: https://developer.apple.com/legacy/library/documentation/Darwin/Reference/ManPages/man1/cp.1.html
*This issue is based on discussion in #2180

**Comment by kubatasiemski** [comment]
I am going to work on that. If anybody know about what signal is send when ctrl+t is pressed in terminal please let mi know. I know only behaviour on macOS.

**Comment by ncw** [comment]
As far as I can see SIGINFO is a synonym for SIGPWR in macOS/BSD.  There doesn't appear to be a mapping to the keyboard for linux.  You can test [with this program](https://play.golang.org/p/64-jQ9wJIu3).

I don't think there are any spare signals on linux that are mapped to keys.

So this feature would be darwin/*BSD only most likely...

**Comment by kubatasiemski** [comment]
As I see each cloud has his own function to upload file, so I have to add some code in each of them. If it will work only on macOS, maybe it is too much work for not very useful functionality :/.

**Comment by ncw** [comment]
If you use the `-v` flag, rclone will show stats every 1 minute by default.

I see the SIGINFO being useful if you didn't specify `-v` and you want to know what is going on.

**Comment by ncw** [comment]
This was done in de8c7d8e45c5ec12bb018d8e85242cfdf1ce1356 :-)
