### ISSUE TITLE
dropbox/crypt with obfuscate incompatibility

### ISSUE THREAD

**Issue by TowerBR** [ncw/rclone#2191]
#### What is the problem you are having with rclone?
Errors are being generated when listing a remote storage (Dropbox) with the file name obfuscation option enabled, as related in [this forum topic](https://forum.rclone.org/t/error-listing-encrypted-storage/5184).
```
filename_encryption = obfuscate
directory_name_encryption = true
```

#### What is your rclone version (eg output from `rclone -V`)
rclone v1.40
os/arch: windows/amd64
go version: go1.10

####  Which cloud storage system are you using? (eg Google Drive)
Dropbox

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
```rclone ls [storage]: --crypt-show-mapping```

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
```
NOTICE: [original_folder_name_without_crypt]: Encrypts to "194._bjhxrph-igpchu4--gradct_rgxeidvgpupsd"
ERROR : [original_folder_name_without_crypt]: error listing: directory not found
Failed to ls: directory not found
```

**Comment by ncw** [comment]
From the forum: 

I see what is happening now... 

I set up a crypt with filename obfuscation pointing at dropbox

```
$ rclone mkdir obfuscate:folder_name_without_crypt
$ echo "hello" | rclone rcat obfuscate:folder_name_without_crypt/hello
$ rclone ls obfuscate: --crypt-show-mapping2018/03/28 21:21:44 NOTICE: foldeR_name_WiThoUT_cRYpT: Encrypts to "128.pyvnob_xkwo_gsdryed_mbizd"
2018/03/28 21:21:45 NOTICE: foldeR_name_WiThoUT_cRYpT/hello: Encrypts to "128.pyvnob_xkwo_gsdryed_mbizd/20.jgnnq"
        6 foldeR_name_WiThoUT_cRYpT/hello
```

Underlying looks like

```
$ rclone ls dropbox:test/obfuscate
       54 128.pyvnob_xkwo_gsdryed_mbizd/20.jgnnq
```

So what it looks like is that something lowercased the obfuscated name for some reason.

Dropbox is case insensitive but it normally preserves the case of names.  I wonder if it doesn't preserve the case of directories.

```
$ rclone mkdir dropbox:test/HelloHello
$ rclone lsd dropbox:test
          -1 2018-03-28 21:27:55        -1 hellohello
          -1 2018-03-28 21:27:55        -1 obfuscate
```

Ah, I see, it is rclone lowercasing the root for some reason that I need to investigate.

**Comment by ncw** [comment]
Here is a fix for the problem.  Note that you'll have to remove any wrongly created directories and create them again.

```
$ rclone ls obfuscate: --crypt-show-mapping
2018/04/05 15:32:59 NOTICE: foldeR_name_WiThoUT_cRYpT: Encrypts to "128.pyvnob_xkwo_gsdryed_mbizd"
2018/04/05 15:33:00 NOTICE: foldeR_name_WiThoUT_cRYpT/hello: Encrypts to "128.pyvnob_xkwo_gsdryed_mbizd/20.jgnnq"
        6 foldeR_name_WiThoUT_cRYpT/hello
$ rclone purge obfuscate:folder_name_without_crypt
$ rclone mkdir obfuscate:folder_name_without_crypt
$ echo "hello" | rclone rcat obfuscate:folder_name_without_crypt/hello
$ rclone ls obfuscate: --crypt-show-mapping
2018/04/05 15:33:33 NOTICE: folder_name_without_crypt: Encrypts to "128.pyvnoB_xkwo_GsDryED_mBIzD"
2018/04/05 15:33:34 NOTICE: folder_name_without_crypt/hello: Encrypts to "128.pyvnoB_xkwo_GsDryED_mBIzD/20.jgnnq"
        6 folder_name_without_crypt/hello
```

https://beta.rclone.org/v1.40-043-gb63ebf47-fix-2191/ (uploaded in 15-30 mins)

**Comment by TowerBR** [comment]
Thanks Nick!

I think it will be kind of difficult to identify the affected folders. Better clean everything up and start the upload again, right?

**Comment by ncw** [comment]
> I think it will be kind of difficult to identify the affected folders. Better clean everything up and start the upload again, right?

Yes probably.

Let me know how it goes - I haven't merged this fix to master yet - I'd like some feed back from you first :-)

Thanks

**Comment by ncw** [comment]
I have merged this now as I want it to get some wider testing.  @TowerBR let me know if it is working for you - thanks

**Comment by TowerBR** [comment]
Sorry for the delay in the response, I was dealing with the hashes issue and I forgot to reply here.

Yes it's all right:

Local folder:

```
/
├── PASTA1
│   ├── paSTa 1.2
│   │   └── teste1~.2.txt
│   └── teSTe1.txt
├── pAsTa3
│   └── TESTE3.txt
├── pasta2
│   └── teste2.txt
└── teste0.txt
```

Remote with ```filename_encryption = obfuscate```:

```
2018/04/10 09:32:41 NOTICE: pasta2: Encrypts to "75.KvNOv1"
2018/04/10 09:32:41 NOTICE: PASTA1: Encrypts to "170.fQijQ6"
2018/04/10 09:32:41 NOTICE: pAsTa3: Encrypts to "12.xIAbi2"
2018/04/10 09:32:41 NOTICE: teste0.txt: Encrypts to "227.QBPQB8.QUQ"
2018/04/10 09:32:41 NOTICE: pasta2/teste2.txt: Encrypts to "75.KvNOv1/229.SDRSD3.SWS"
2018/04/10 09:32:42 NOTICE: PASTA1/paSTa 1.2: Encrypts to "170.fQijQ6/138.yjbcj 0.1"
2018/04/10 09:32:42 NOTICE: PASTA1/teSTe1.txt: Encrypts to "170.fQijQ6/164.Docdo9.DHD"
2018/04/10 09:32:42 NOTICE: pAsTa3/TESTE3.txt: Encrypts to "12.xIAbi2/70.jUijU7.JNJ"
2018/04/10 09:32:42 NOTICE: PASTA1/paSTa 1.2/teste1~.2.txt: Encrypts to "170.fQijQ6/138.yjbcj 0.1/194.ItHIt3~.4.IMI"
```


Remote with ```filename_encryption = standard```:

```
2018/04/10 09:32:36 NOTICE: pasta2: Encrypts to "4goh9ll75o3nv5mlr1s66e7np0"
2018/04/10 09:32:36 NOTICE: pAsTa3: Encrypts to "41t3tss9hlgp5pdg08pr7m5pnk"
2018/04/10 09:32:36 NOTICE: PASTA1: Encrypts to "aj6di3jagciu6c9dfjf1o0hnto"
2018/04/10 09:32:36 NOTICE: teste0.txt: Encrypts to "kilrq20cphp05lhtuas0bjkhms"
2018/04/10 09:32:37 NOTICE: pasta2/teste2.txt: Encrypts to "4goh9ll75o3nv5mlr1s66e7np0/g5bd6boe5pi5edan6ha0k7iir4"
2018/04/10 09:32:37 NOTICE: PASTA1/paSTa 1.2: Encrypts to "aj6di3jagciu6c9dfjf1o0hnto/hc7jvetrtdc3jaap7dl05kacjo"
2018/04/10 09:32:37 NOTICE: PASTA1/teSTe1.txt: Encrypts to "aj6di3jagciu6c9dfjf1o0hnto/pgva0u3dt1hrng7oh3sa5nf3kc"
2018/04/10 09:32:37 NOTICE: pAsTa3/TESTE3.txt: Encrypts to "41t3tss9hlgp5pdg08pr7m5pnk/fj6k5vhiv7rt7k9npg7p82plug"
2018/04/10 09:32:38 NOTICE: PASTA1/paSTa 1.2/teste1~.2.txt: Encrypts to "aj6di3jagciu6c9dfjf1o0hnto/hc7jvetrtdc3jaap7dl05kacjo/khiop9ksk8ilcnb0b99u49l8bc"
```


Thanks a lot!

**Comment by ncw** [comment]
Thanks for testing :-)
