### ISSUE TITLE
--backup-dir with GCS requires storage.buckets.get ACL

### ISSUE THREAD

**Issue by prattmic** [ncw/rclone#2193]
#### What is the problem you are having with rclone?

AFAICT, this is #1590, but applied specifically to --backup-dir.

`rclone sync <anything> <gcs remote>/folder` works just fine with a service account that only has the "Storage Object Admin" role.

However, `rclone sync <anything> <gcs remote>/folder --backup-dir <gcs remote>/other-folder` fails when it needs to actually create a backup file with an error like:

```
2018/03/31 14:41:48 ERROR : SOURCE_FILE: Failed to copy: failed to get bucket: googleapi: Error 403: SERVICE_ACCOUNT@PROJECT.iam.gserviceaccount.com does not have storage.buckets.get access to BUCKET., forbidden
2018/03/31 14:41:48 ERROR : SOURCE_FILE: Not deleting source as copy failed: failed to get bucket: googleapi: Error 403: SERVICE_ACCOUNT@PROJECT.iam.gserviceaccount.com does not have storage.buckets.get access to BUCKET., forbidden
2018/03/31 14:41:48 ERROR : SOURCE_FILE: Couldn't move into backup dir: failed to get bucket: googleapi: Error 403: SERVICE_ACCOUNT@PROJECT.iam.gserviceaccount.com does not have storage.buckets.get access to BUCKET., forbidden
```

It works if I add the service account to the "Storage Legacy Bucket Reader" role, which includes "storage.buckets.get", but it is not clear why that should be required since normal sync works just fine without it. sync even created the initial folder the first time.

#### What is your rclone version (eg output from `rclone -V`)

```
$ rclone -V
rclone v1.40
- os/arch: linux/amd64
- go version: go1.10
```

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

Debian testing, x86_64, Linux 4.14

####  Which cloud storage system are you using? (eg Google Drive)

Google Cloud Storage

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

See above.

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

I only used one `-v` above. Let me know if you'd like me to reproduce with `-vv`, but I think the issue is clear.

**Comment by ncw** [comment]
Could you try a run with -vv and --dump bodies and post the failing transaction?

That will let me work out which bit of code is causing the problem.

Thanks

**Comment by prattmic** [comment]
Log below.

------

I think the immediate issue is the unconditional Mkdir in Fs.Copy: https://github.com/ncw/rclone/blob/e42cee5e029125497033d249e3995e7e235becc5/backend/googlecloudstorage/googlecloudstorage.go#L672

I believe the flow is:

1. `pairChecker` calls `NewObject` to try to find "BACKUP_DIR/CHANGED_FILE": https://github.com/ncw/rclone/blob/a8267d16282099f1135c4652fb5900dcd1690e14/fs/sync/sync.go#L220
2. `NewObject` makes the `GET /storage/v1/b/BUCKET/o/BACKUP_DIR%2FCHANGED_FILE?alt=json` call to see if the file exists. It returns 404, so NewObject returns nil, err.
3. `pairChecker` calls `operations.Move` with nil dst.
4. `googlecloudstorage.Fs` doesn't implement `Move`, so `operations.Move` calls `operations.Copy`, which calls `googlecloudstorage.Fs.Copy`.
5. `googlecloudstorage.Fs.Copy` calls `googlecloudstorage.Fs.Mkdir`, which calls `f.svc.Buckets.Get`. This causes the `GET /storage/v1/b/BUCKET?alt=json` call, which ultimately returns 403.
6. `Mkdir` fails, so `Copy` fails.

The obvious fix would be for `Copy` to ignore 403 errors from `Mkdir`. In my case, that should fix things since the bucket does indeed exist and is accessible, but if the bucket isn't accessible it could cause confusion later with some kind of permission error when creating objects.

That said, I imagine such a fallback must already exist in the main upload path, since my normal uploads worked fine without `storage.buckets.get`.

I had a similar issue with restic, and implemented ignore of bucket.get 403 errors there: https://github.com/restic/restic/pull/1281

------

Here's what I believe are all of the relative parts of the log (unrelated concurrent operations make it a bit tricky to follow):

```
2018/03/31 23:49:56 DEBUG : CHANGED_FILE: Modification times differ by -184h46m40.906s: 2018-03-31 23:00:39.421 +0000 UTC, 2018-03-24 06:13:58.515 +0000 UTC
2018/03/31 23:49:56 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2018/03/31 23:49:56 DEBUG : HTTP REQUEST (req 0xc42013b900)
2018/03/31 23:49:56 DEBUG : GET /storage/v1/b/BUCKET/o/BACKUP_DIR%2FCHANGED_FILE?alt=json HTTP/1.1
Host: www.googleapis.com
User-Agent: rclone/v1.40
Authorization: XXXX
Accept-Encoding: gzip

2018/03/31 23:49:56 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2018/03/31 23:49:56 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2018/03/31 23:49:56 DEBUG : HTTP RESPONSE (req 0xc42013b900)
2018/03/31 23:49:56 DEBUG : HTTP/1.1 404 Not Found
Content-Length: 339
Alt-Svc: hq=":443"; ma=2592000; quic=51303432; quic=51303431; quic=51303339; quic=51303335,quic=":443"; ma=2592000; v="42,41,39,35"
Cache-Control: private, max-age=0
Content-Type: application/json; charset=UTF-8
Date: Sun, 01 Apr 2018 06:49:56 GMT
Expires: Sun, 01 Apr 2018 06:49:56 GMT
Server: UploadServer
Vary: Origin
Vary: X-Origin
X-Guploader-Uploadid: UPLOADID (is this sensitive?)

{
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "notFound",
    "message": "No such object: BUCKET/BACKUP_DIR/CHANGED_FILE"
   }
  ],
  "code": 404,
  "message": "No such object: BUCKET/BACKUP_DIR/CHANGED_FILE"
 }
}
2018/03/31 23:49:56 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2018/03/31 23:49:56 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2018/03/31 23:49:56 DEBUG : HTTP REQUEST (req 0xc42013a400)
2018/03/31 23:49:56 DEBUG : GET /storage/v1/b/BUCKET?alt=json HTTP/1.1
Host: www.googleapis.com
User-Agent: rclone/v1.40
Authorization: XXXX
Accept-Encoding: gzip

2018/03/31 23:49:56 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2018/03/31 23:49:57 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2018/03/31 23:49:57 DEBUG : HTTP RESPONSE (req 0xc4202ea500)
2018/03/31 23:49:57 DEBUG : HTTP/1.1 403 Forbidden
Content-Length: 414
Alt-Svc: hq=":443"; ma=2592000; quic=51303432; quic=51303431; quic=51303339; quic=51303335,quic=":443"; ma=2592000; v="42,41,39,35"
Cache-Control: private, max-age=0
Content-Type: application/json; charset=UTF-8
Date: Sun, 01 Apr 2018 06:49:57 GMT
Expires: Sun, 01 Apr 2018 06:49:57 GMT
Server: UploadServer
Vary: Origin
Vary: X-Origin
X-Guploader-Uploadid: UPLOAD_ID

{
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "forbidden",
    "message": "SERVICE_ACCOUNT does not have storage.buckets.get access to BUCKET."
   }
  ],
  "code": 403,
  "message": "SERVICE_ACCOUNT does not have storage.buckets.get access to BUCKET."
 }
}
2018/03/31 23:49:57 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2018/03/31 23:49:57 ERROR : CHANGED_FILE: Failed to copy: failed to get bucket: googleapi: Error 403: SERVICE_ACCOUNT does not have storage.buckets.get access to BUCKET., forbidden
2018/03/31 23:49:57 ERROR : CHANGED_FILE: Not deleting source as copy failed: failed to get bucket: googleapi: Error 403: SERVICE_ACCOUNT does not have storage.buckets.get access to BUCKET., forbidden
```

**Comment by prattmic** [comment]
Hm, I missed the `bucketOK` check at the beginning of `Mkdir` my `--backup-dir` is in the same bucket as the destination, so I'm not sure why `bucketOK` wouldn't already be true.

**Comment by ncw** [comment]
@prattmic excellent investigation and I think your conclusions are good.

> Hm, I missed the bucketOK check at the beginning of Mkdir my --backup-dir is in the same bucket as the destination, so I'm not sure why bucketOK wouldn't already be true.

The reason it isn't true is that backup-dir acts on a separate remote with its own copy of `bucketOK`.  This is inelegant, but I haven't figured out a way around it yet.

I guess rclone could attempt to list the bucket instead of calling `f.svc.Buckets.Get(f.bucket).Do()` - do you think that would work?  It could do a list returning only 1 item (say) to make it efficient.

**Comment by prattmic** [comment]
I'm not super familiar with the GCS API, but I don't see any reason that wouldn't work. Even if there are no files, I'd imagine we'd get a successful, but empty, response.

**Comment by prattmic** [comment]
Yup, that fixes it!

**Comment by ncw** [comment]
Great - thanks for testing.  I've merged this now so it will be in [the latest beta](https://beta.rclone.org) from now on.
