### ISSUE TITLE
Unable to write to an encfs mount with rclone cache

### ISSUE THREAD

**Issue by mjefferys** [ncw/rclone#2198]
#### What is the problem you are having with rclone?
When trying to write to any file in the encfs mount point that is reading from my rclone cache no files can be written.

My rclone cached remote is mounted via the command below, then the encfs mount is mounted with:
encfs /home/michael/mediaenc/ /home/michael/mediacache/

Writing anything to /home/michael/mediacache/ fails. 

If I mount the Google Drive remote directly without using the the cached remote. Writing works perfectly. But obviously the cached remote would be vastly superior and should behave the same way?

Attached are my logs

#### What is your rclone version (eg output from `rclone -V`)
rclone v1.40
- os/arch: linux/amd64
- go version: go1.10

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Ubuntu 16.04 64bit

####  Which cloud storage system are you using? (eg Google Drive)
Google Drive

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
/usr/bin/rclone mount gdcache:/ /home/michael/mediaenc    --allow-other    --allow-non-empty    --dir-cache-time=160h    --cache-chunk-size=10M    --cache-info-age=168h    --cache-workers=5    --attr-timeout=1s --umask 002    --rc    --cache-tmp-upload-path /home/michael/.config/rclone/upload    --cache-tmp-wait-time 30m    --cache-db-path /home/michael/.config/rclone 

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

2018/04/02 19:45:18 INFO  : gdcache: Upload Temp FS: /home/michael/.config/rclone/upload
2018/04/02 19:45:18 DEBUG : Adding path "cache/expire" to remote control registry
2018/04/02 19:45:18 INFO  : Cache remote gdcache:: Modify window is 1ms
2018/04/02 19:45:18 DEBUG : Cache remote gdcache:: Mounting on "/home/michael/mediaenc"
2018/04/02 19:45:18 DEBUG : Cache remote gdcache:: subscribing to ChangeNotify
2018/04/02 19:45:18 DEBUG : vfs cache root is "/home/michael/.cache/rclone/vfs/gdcache"
2018/04/02 19:45:18 DEBUG : Adding path "vfs/forget" to remote control registry
2018/04/02 19:45:18 DEBUG : : Root:
2018/04/02 19:45:18 DEBUG : : >Root: node=/, err=<nil>
2018/04/02 19:45:18 INFO  : PrTMUeo4xf1hObf21CRrA-mN/SlRry6rb8Q4QDTcovQAvmUMu: background upload: started upload
2018/04/02 19:45:19 DEBUG : Google drive root 'Media': Checking for changes on remote
2018/04/02 19:45:19 DEBUG : PrTMUeo4xf1hObf21CRrA-mN/SlRry6rb8Q4QDTcovQAvmUMu: Couldn't find file - need to transfer
2018/04/02 19:45:19 DEBUG : Google drive root 'Media': All changes were processed. Waiting for more.
2018/04/02 19:45:20 INFO  : PrTMUeo4xf1hObf21CRrA-mN/SlRry6rb8Q4QDTcovQAvmUMu: Copied (new)
2018/04/02 19:45:20 INFO  : PrTMUeo4xf1hObf21CRrA-mN/SlRry6rb8Q4QDTcovQAvmUMu: Deleted
2018/04/02 19:45:20 INFO  : PrTMUeo4xf1hObf21CRrA-mN/SlRry6rb8Q4QDTcovQAvmUMu: background upload: uploaded entry
2018/04/02 19:45:20 DEBUG : PrTMUeo4xf1hObf21CRrA-mN: cache: expired PrTMUeo4xf1hObf21CRrA-mN
2018/04/02 19:45:20 DEBUG : PrTMUeo4xf1hObf21CRrA-mN: cache: expired
2018/04/02 19:45:20 INFO  : PrTMUeo4xf1hObf21CRrA-mN/SlRry6rb8Q4QDTcovQAvmUMu: finished background upload
2018/04/02 19:45:21 DEBUG : /: Attr:
2018/04/02 19:45:21 DEBUG : /: >Attr: attr=valid=1s ino=0 size=0 mode=drwxrwxr-x, err=<nil>
2018/04/02 19:45:21 DEBUG : /: Lookup: name="k4vQfVTK4dbMvMJmym8-KLiI"
2018/04/02 19:45:21 DEBUG : Cache remote gdcache:: list ''
2018/04/02 19:45:21 DEBUG : 4srkxre75uU-Zr4UnMDStOCp: pending upload found
2018/04/02 19:45:21 DEBUG : nNko-pbGPMCrsBIbirQmVMUm: pending upload found
2018/04/02 19:45:21 DEBUG : testfile: pending upload found
2018/04/02 19:45:21 DEBUG : : list: cold listing: 2018-03-26 19:45:20.978566395 +0200 CEST
2018/04/02 19:45:21 DEBUG : : list: read 3 from temp fs
2018/04/02 19:45:21 DEBUG : : list: temp fs entries: [4srkxre75uU-Zr4UnMDStOCp nNko-pbGPMCrsBIbirQmVMUm testfile]
2018/04/02 19:45:21 DEBUG : 4srkxre75uU-Zr4UnMDStOCp: pending upload found
2018/04/02 19:45:21 DEBUG : 4srkxre75uU-Zr4UnMDStOCp: list: cached temp object
2018/04/02 19:45:21 DEBUG : nNko-pbGPMCrsBIbirQmVMUm: pending upload found
2018/04/02 19:45:21 DEBUG : nNko-pbGPMCrsBIbirQmVMUm: list: cached temp object
2018/04/02 19:45:21 DEBUG : testfile: pending upload found
2018/04/02 19:45:21 DEBUG : testfile: list: cached temp object
2018/04/02 19:45:21 DEBUG : : list: read 8 from source
2018/04/02 19:45:21 DEBUG : : list: source entries: [share .encfs6.xml PrTMUeo4xf1hObf21CRrA-mN JTLVRsXiqJRETCxHlfYP5Eu4 bTubLu4BUgV-bvjh,Ii1Qrxo SGOZ6ZuR6rmT0ZpSEn0edYLw j1iOXu3LOUQXAR1DzdWZ2A9u 58cY31EQr3P0jCv4Q7iLmwWx]
2018/04/02 19:45:21 DEBUG : : list: cached dir: share
2018/04/02 19:45:21 DEBUG : : list: cached object: .encfs6.xml
2018/04/02 19:45:21 DEBUG : : list: cached dir: JTLVRsXiqJRETCxHlfYP5Eu4
2018/04/02 19:45:21 DEBUG : : list: cached dir: bTubLu4BUgV-bvjh,Ii1Qrxo
2018/04/02 19:45:21 DEBUG : : list: cached dir: SGOZ6ZuR6rmT0ZpSEn0edYLw
2018/04/02 19:45:21 DEBUG : : list: cached dir: j1iOXu3LOUQXAR1DzdWZ2A9u
2018/04/02 19:45:21 DEBUG : : list: cached dir: 58cY31EQr3P0jCv4Q7iLmwWx
2018/04/02 19:45:21 DEBUG : : list: cached dir: '', cache ts: 2018-04-02 19:45:21.911877126 +0200 CEST m=+3.683529715
2018/04/02 19:45:21 DEBUG : /: >Lookup: node=<nil>, err=no such file or directory
2018/04/02 19:45:21 DEBUG : /: Lookup: name="nNko-pbGPMCrsBIbirQmVMUm"
2018/04/02 19:45:21 DEBUG : /: >Lookup: node=nNko-pbGPMCrsBIbirQmVMUm, err=<nil>
2018/04/02 19:45:21 DEBUG : nNko-pbGPMCrsBIbirQmVMUm: Attr:
2018/04/02 19:45:21 DEBUG : nNko-pbGPMCrsBIbirQmVMUm: >Attr: a=valid=1s ino=0 size=0 mode=-rw-rw-r--, err=<nil>
2018/04/02 19:45:21 DEBUG : nNko-pbGPMCrsBIbirQmVMUm: Open: flags=OpenReadOnly
2018/04/02 19:45:21 DEBUG : nNko-pbGPMCrsBIbirQmVMUm: Open: flags=O_RDONLY
2018/04/02 19:45:21 DEBUG : nNko-pbGPMCrsBIbirQmVMUm: >Open: fd=nNko-pbGPMCrsBIbirQmVMUm (r), err=<nil>
2018/04/02 19:45:21 DEBUG : nNko-pbGPMCrsBIbirQmVMUm: >Open: fh=&{nNko-pbGPMCrsBIbirQmVMUm (r)}, err=<nil>
2018/04/02 19:45:21 DEBUG : &{nNko-pbGPMCrsBIbirQmVMUm (r)}: Read: len=4096, offset=0
2018/04/02 19:45:21 DEBUG : &{nNko-pbGPMCrsBIbirQmVMUm (r)}: >Read: read=0, err=<nil>

**Comment by remusb** [comment]
How does it fail? There doesn't seem to be any error log in here. Is the OS complaining about something? encfs? rclone doesn't seem to be.

**Comment by mjefferys** [comment]
So I can for example successfully do 'touch testfile' but I cannot write any data to it

`michael@saturn:~/mediacache⟫ touch testfile
michael@saturn:~/mediacache⟫ echo "test data" > testfile
bash: echo: write error: Input/output error
1 michael@saturn:~/mediacache⟫ cat testfile
michael@saturn:~/mediacache⟫
`
Not sure where else to look

**Comment by mjefferys** [comment]
The same commands in /medienc which is the encrypted cache mount work perfectly.

`michael@saturn:~/mediaenc⟫ touch testfile`
`michael@saturn:~/mediaenc⟫ echo "test data" > testfile`
`michael@saturn:~/mediaenc⟫ cat testfile`
`test data`
`michael@saturn:~/mediaenc⟫`

**Comment by mjefferys** [comment]
Thanks for your input, i've played some more with it this morning and actually managed to get some useful info out out of the log that I must have missed before.

2018/04/05 12:04:23 DEBUG : XZdpfPmdZ2FI0Oet0UJ9mhrj: Attr:
2018/04/05 12:04:23 DEBUG : XZdpfPmdZ2FI0Oet0UJ9mhrj: >Attr: a=valid=1s ino=0 size=0 mode=-rw-rw-r--, err=<nil>
2018/04/05 12:04:23 DEBUG : XZdpfPmdZ2FI0Oet0UJ9mhrj: Open: flags=OpenReadWrite
2018/04/05 12:04:23 DEBUG : XZdpfPmdZ2FI0Oet0UJ9mhrj: Open: flags=O_RDWR
2018/04/05 12:04:23 DEBUG : XZdpfPmdZ2FI0Oet0UJ9mhrj: >Open: fd=XZdpfPmdZ2FI0Oet0UJ9mhrj (w), err=<nil>
2018/04/05 12:04:23 DEBUG : XZdpfPmdZ2FI0Oet0UJ9mhrj: >Open: fh=&{XZdpfPmdZ2FI0Oet0UJ9mhrj (w)}, err=<nil>
2018/04/05 12:04:23 DEBUG : XZdpfPmdZ2FI0Oet0UJ9mhrj: Setattr: a=Setattr [ID=0x192 Node=0x6 Uid=1000 Gid=1000 Pid=5480] size=8 handle=0x1 lockowner
2018/04/05 12:04:23 DEBUG : XZdpfPmdZ2FI0Oet0UJ9mhrj: Truncating 1 file handles
2018/04/05 12:04:23 ERROR : XZdpfPmdZ2FI0Oet0UJ9mhrj: WriteFileHandle: Truncate: Can't change size without --vfs-cache-mode >= writes
2018/04/05 12:04:23 DEBUG : XZdpfPmdZ2FI0Oet0UJ9mhrj: >Setattr: err=operation not permitted
2018/04/05 12:04:23 DEBUG : XZdpfPmdZ2FI0Oet0UJ9mhrj: Fsync:
2018/04/05 12:04:23 DEBUG : XZdpfPmdZ2FI0Oet0UJ9mhrj: >Fsync: err=<nil>
2018/04/05 12:04:23 DEBUG : &{XZdpfPmdZ2FI0Oet0UJ9mhrj (w)}: Flush:
2018/04/05 12:04:23 DEBUG : XZdpfPmdZ2FI0Oet0UJ9mhrj: WriteFileHandle.Flush unwritten handle, writing 0 bytes to avoid race conditions
2018/04/05 12:04:23 ERROR : XZdpfPmdZ2FI0Oet0UJ9mhrj: WriteFileHandle: Can't open for write without O_TRUNC on existing file without --vfs-cache-mode >= writes
2018/04/05 12:04:23 DEBUG : &{XZdpfPmdZ2FI0Oet0UJ9mhrj (w)}: >Flush: err=operation not permitted
2018/04/05 12:04:23 DEBUG : &{XZdpfPmdZ2FI0Oet0UJ9mhrj (w)}: Flush:
2018/04/05 12:04:23 DEBUG : XZdpfPmdZ2FI0Oet0UJ9mhrj: WriteFileHandle.Flush unwritten handle, writing 0 bytes to avoid race conditions
2018/04/05 12:04:23 ERROR : XZdpfPmdZ2FI0Oet0UJ9mhrj: WriteFileHandle: Can't open for write without O_TRUNC on existing file without --vfs-cache-mode >= writes
2018/04/05 12:04:23 DEBUG : &{XZdpfPmdZ2FI0Oet0UJ9mhrj (w)}: >Flush: err=operation not permitted
2018/04/05 12:04:23 DEBUG : &{XZdpfPmdZ2FI0Oet0UJ9mhrj (w)}: Flush:
2018/04/05 12:04:23 DEBUG : XZdpfPmdZ2FI0Oet0UJ9mhrj: WriteFileHandle.Flush unwritten handle, writing 0 bytes to avoid race conditions
2018/04/05 12:04:23 ERROR : XZdpfPmdZ2FI0Oet0UJ9mhrj: WriteFileHandle: Can't open for write without O_TRUNC on existing file without --vfs-cache-mode >= writes
2018/04/05 12:04:23 DEBUG : &{XZdpfPmdZ2FI0Oet0UJ9mhrj (w)}: >Flush: err=operation not permitted
2018/04/05 12:04:23 DEBUG : &{XZdpfPmdZ2FI0Oet0UJ9mhrj (w)}: Release:
2018/04/05 12:04:23 DEBUG : XZdpfPmdZ2FI0Oet0UJ9mhrj: WriteFileHandle.Release closing
2018/04/05 12:04:23 DEBUG : &{XZdpfPmdZ2FI0Oet0UJ9mhrj (w)}: >Release: err=<nil>

Ok cool, so I need to enable --vfs-cache-mode=writes great. So with my updated mount command:

/usr/bin/rclone mount gdcache:/ /home/michael/mediaenc    --allow-other    --allow-non-empty    --dir-cache-time=160h    --cache-chunk-size=10M    --cache-info-age=168h    --cache-workers=5    --attr-timeout=1s --umask 002    --rc    --cache-tmp-upload-path /home/michael/.config/rclone/upload --cache-db-path /home/michael/.config/rclone -vv --cache-writes --vfs-cache-mode=writes

I am now able to succesfully run:

`michael@saturn:~/mediacache⟫ echo "more test data" > testfile`
`michael@saturn:~/mediacache⟫ cat testfile`
`more test data`
`michael@saturn:~/mediacache⟫`

So that's some progress.

I'm not sure what the implications of --vfs-cache-mode=writes is. But I guess I'm hitting an expected behavior and this isn't actually a bug?

**Comment by ncw** [comment]
Here is an older issue about the same thing which explains what is going on: https://github.com/ncw/rclone/issues/961

When that issue was made we didn't have --vfs-cache-mode=writes but I think it would have fixed it.

I'll just adjust that issue now!

**Comment by remusb** [comment]
Seems like this can be closed now.
