### ISSUE TITLE
Sync Method with Drive

### ISSUE THREAD

**Issue by dav1303** [ncw/rclone#220]
Hi

On source : D:\Test\A\1.pdf

First Time : I launch rclone with sync method => TEST\A\1.pdf was created on drive
Second Time : Deletion on source of the subfolder A containing the file 1.PDF
Third Time : I Launch rclone with Sync Method and nothing changes on Drive

The file was deleted but the subfolder stills present on Drive

Regards

**Comment by ncw** [comment]
This is a known bug I'm afraid - see http://rclone.org/bugs/

I'm planning on fixing it eventually though - see #100 for progress.

Thanks for the report

Nick
