### ISSUE TITLE
-s3-chunk-size int option for S3 users

### ISSUE THREAD

**Issue by sparrowjack63** [ncw/rclone#2203]
Hi! 

Please could you add an option like “-s3-chunk-size int”, it will be be very usefull for s3 users :)

Thanks !

**Comment by ncw** [comment]
This should be a question of adding a new flag then using it as the default for `u.PartSize` instead of `s3manager.MinUploadPartSize` in [this bit of code](https://github.com/ncw/rclone/blob/master/backend/s3/s3.go#L1043).

Fancy having a go?

**Comment by sparrowjack63** [comment]
I supposed we have to used a flag in function "init()" of file s3.go : 
flags.VarP(&chunkSize, "s3-chunk-size", "", "Upload chunk size in MB.")

But before we had to declare a const "chunkSize".
An after in function "update" we have to used it : 
u.PartSize = chunkSize

May be something like that (or not) ? but I 'm not used to programming in go, it would take me a lot of time to do it well :(

**Comment by ncw** [comment]
No worries!

I made an initial attempt here - let me know if it works for you!

https://beta.rclone.org/v1.40-040-gef58b6a5-s3-chunk-size/ (uploaded in 15-30 mins)

**Comment by sparrowjack63** [comment]
Thank you very much !
I tested it and it work as expected :)
For s3 users, we can now have better rate transfer (x2 for me).
It would be great to integrate it in the next stable release !

**Comment by ncw** [comment]
What setting are you using? I'd be interested in any experiments that you've run.

**Comment by sparrowjack63** [comment]
I used --s3-chunk-size=100M to transfer 2GB file : rclone copy source remote:/bucket  --s3-chunk-size=100M 
My network has low latency and good network bandwidth, with this use case, making too small chunks (5M) for transferring big file is not helping to have the bests performances.

**Comment by ncw** [comment]
Thanks for the update.  I've merged this now and updated the docs so it will be in [the latest beta](https://beta.rclone.org) from now on!

**Comment by EuropeanaDevelopment** [comment]
Just tested this beta functionality against a file size of 50GB and used various integers values (50M, 500M and 1000M) but the file is not getting transferred. Using this binary without this flag also causes the same file not getting transferred. However smaller file sizes are getting transferred properly. Please advice, thank you.

**Comment by ncw** [comment]
@EuropeanaDevelopment - when you say not getting transferred - how do you know?  What does the log say?  Can you try running with `-vv` and post the output?

**Comment by EuropeanaDevelopment** [comment]
```$ /usr/bin/rclone_beta copy --s3-chunk-size=50M --s3-acl private artifactory/20180331.020100.zip IBM:europeana-backup/upload -vv
2018/04/25 15:38:15 DEBUG : rclone: Version "v1.40-116-gbe8bd896β" starting with parameters ["/usr/bin/rclone_beta" "copy" "--s3-chunk-size=50M" "--s3-acl" "private" "artifactory/20180331.020100.zip" "IBM:europeana-backup/upload" "-vv"]
2018/04/25 15:38:15 DEBUG : Using config file from "/home/jenkins/.config/rclone/rclone.conf"
2018/04/25 15:38:16 INFO  : S3 bucket europeana-backup path upload/: Modify window is 1ns
2018/04/25 15:38:16 DEBUG : 20180407.020102.tmp.zip: Excluded from sync (and deletion)
2018/04/25 15:38:16 DEBUG : 20180414.020102.tmp.zip: Excluded from sync (and deletion)
2018/04/25 15:38:16 DEBUG : 20180421.020101.tmp.zip: Excluded from sync (and deletion)
2018/04/25 15:38:16 INFO  : S3 bucket europeana-backup path upload/: Waiting for checks to finish
2018/04/25 15:38:16 INFO  : S3 bucket europeana-backup path upload/: Waiting for transfers to finish
2018/04/25 15:39:16 INFO  :
Transferred:      0 Bytes (0 Bytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:      1m0.3s
Transferring:
 *                           20180331.020100.zip:  0% /41.113G, 0/s, -

2018/04/25 15:40:16 INFO  :
Transferred:      0 Bytes (0 Bytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:      2m0.3s
Transferring:
 *                           20180331.020100.zip:  0% /41.113G, 0/s, -

2018/04/25 15:41:16 INFO  :
Transferred:      0 Bytes (0 Bytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:      3m0.3s
Transferring:
 *                           20180331.020100.zip:  0% /41.113G, 0/s, -

2018/04/25 15:42:16 INFO  :
Transferred:      0 Bytes (0 Bytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:      4m0.3s
Transferring:
 *                           20180331.020100.zip:  0% /41.113G, 0/s, -

2018/04/25 15:43:16 INFO  :
Transferred:      0 Bytes (0 Bytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:      5m0.3s
Transferring:
 *                           20180331.020100.zip:  0% /41.113G, 0/s, -```

**Comment by EuropeanaDevelopment** [comment]
```
# /usr/bin/rclone_beta -V
rclone v1.40-116-gbe8bd896β
- os/arch: linux/386
- go version: go1.10.1
```

**Comment by EuropeanaDevelopment** [comment]
It works in conjuction with flag --s3-disable-checksum. Thank you.

**Comment by ncw** [comment]
@EuropeanaDevelopment wrote:
> It works in conjuction with flag --s3-disable-checksum

Great!  It would have worked eventually without - it just takes a long time to sha1sum a 42GB file.
