### ISSUE TITLE
in Docker on OverlayFS, rclone doesn't work

### ISSUE THREAD

**Issue by Dmitry1987** [ncw/rclone#2204]
#### What is the problem you are having with rclone?
in Docker on OverlayFS, rclone doesn't work.  If docker on AUFS, all runs fine.

#### What is your rclone version (eg output from `rclone -V`)
v1.40 

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
ubuntu

####  Which cloud storage system are you using? (eg Google Drive)
S3

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone copy buckets:mybucket/myfolder /tmp/remote_files

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
```

2018/04/04 01:30:01 INFO  : Starting bandwidth limiter at 80MBytes/s
2018/04/04 01:41:52 INFO  : Local file system at /tmp/remote_files: Modify window is 1ns
2018/04/04 01:42:52 INFO  :
Transferred:      0 Bytes (0 Bytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:      12m51s
...
...
...
2018/04/04 01:52:52 INFO  :
Transferred:      0 Bytes (0 Bytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:      22m51s

2018/04/04 01:53:48 ERROR : : error reading source directory: RequestError: send request failed
caused by: Get https://s3.amazonaws.com/mybucket?delimiter=%2F&max-keys=1000&prefix=data%2F: dial tcp: i/o timeout
2018/04/04 01:53:48 INFO  : Local file system at /tmp/remote_files: Waiting for checks to finish
2018/04/04 01:53:48 INFO  : Local file system at /tmp/remote_files: Waiting for transfers to finish
2018/04/04 01:53:48 ERROR : Attempt 1/3 failed with 1 errors
2018/04/04 01:53:52 INFO  :
Transferred:      0 Bytes (0 Bytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:      23m51s

2018/04/04 01:54:52 INFO  :
Transferred:      0 Bytes (0 Bytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:      24m51s

```

seems like the local filesystem drives him crazy :) .   I tried on my mac (working), on ubuntu with AUFS docker filesystem (working), and ubuntu with OverlayFS filesystem not working :(  the output above. I run rclone in alpine container (custom with our related stuff) to copy things from s3 and do extra manipulations on a mounted folder from host.  

the /tmp/remote_files is some host machine folder mounted into container.  BUT the issue is same even if i don't mount the folder (just leave the ephemeral docker storage as is).

Any ideas what's wrong with this combo of docker+overlayfs?  

thanks in advance :)

**Comment by Dmitry1987** [comment]
important note:  the config file, credentials to s3, all perfectly fine. **same settings** are working on Mac and Ubuntu, just doesn't work on ubuntu with overlayfs docker.

**Comment by ncw** [comment]
This is the error

    ERROR : : error reading source directory: RequestError: send request failed caused by: Get https://s3.amazonaws.com/mybucket?delimiter=%2F&max-keys=1000&prefix=data%2F: dial tcp: i/o timeout

Which the important bit is `dial tcp: i/o timeout`

So it seems to be some kind of networking problem from the docker container to the outside world.

**Comment by Dmitry1987** [comment]
Hi @ncw , you are right! silly me.... It was actually a custom networking on these hosts, i had to attach my containers to another network and not the default 'bridge' :) 
I didn't checked if my container has network access at all... were blaming the rclone and the filesystem :D 

Thank you 👍

**Comment by ncw** [comment]
No worries!
