### ISSUE TITLE
rc: getpid

### ISSUE THREAD

**Issue by pyhedgehog** [ncw/rclone#2211]
I have several cloud storages, so I have to start several `rc serve` processes.
How should I select which process to signal/stop/kill?
I propose new `rc/pid` call that returns pid of server process.
I already have implementation - PR will follow soon.
Maybe it's not solution you want, and first I should ask how this situation should be handled "in ideal world"?

**Comment by daniel-loader** [comment]
I like this, as it stands now I check PID via htop by filtering some of the mount path but I can definitely get behind a tool that lists it, more so if it outputs data in a way that can be used in scripts.

Example would be polling rclone rc getpid for a list of mount names, mount paths and their associated pids. Feel like spitting it into three columns that AWK can easily parse would be handy, if not, CSV. 

With some creative scripting you could write a bash function to take the PWD, work out which mount the directory is a child of, and then send the correct formatted cache/expire command so you can call that bash routine wherever you're at when in terminal.

Would be extremely useful to me at least!

**Comment by ncw** [comment]
@pyhedgehog What do you use the pid for?

> How should I select which process to signal/stop/kill?

Maybe the rc should be able to signal/stop/kill the rclone then you wouldn't need to do any parsing?

I like the `rc/pid` call though - nice idea!

**Comment by daniel-loader** [comment]
Yeah I guess my thought was if you can identify the PID of the PWD in bash you can work out the rc-addr to send a message to. Either way any process that allows scripting to have a context aware method to talk to the right rclone instance is welcome.

**Comment by pyhedgehog** [comment]
@ncw, stop rc command would be pretty, but pid will be useful nevertheless - it can be used for monitoring (i.e. `pwait $(rclone rc rc/pid|jq .pid)`).
Another reason for this way was that I could implement it fast.

**Comment by ncw** [comment]
Code looks great now thanks.  Can you add the documentation in https://github.com/ncw/rclone/blob/master/docs/content/rc.md

One day I intend that documentation to be auto generated but we aren't quite there yet :-(

**Comment by pyhedgehog** [comment]
@ncw, docs added.

**Comment by ncw** [comment]
Note that in 9ab2521ef2ec00fcf74fd85834609b740652b752 I renamed `rc/pid` to `core/pid` as I decided that the `core` prefix was more appropriate than the `rc` one which is just about controlling the remote control.

Sorry for the inconvenience!
