### ISSUE TITLE
Slow upload to Gdrive with SoYouStart (OVH) dedicated server. 

### ISSUE THREAD

**Issue by zawack** [ncw/rclone#2216]
#### What is the problem you are having with rclone?

When uploading data to gdrive we got only around 6 Mb/s. Our dedicated server provider (SYS/OVH) allow us a guaranty bandwidth of 250 Mb/s. 

#### What is your rclone version (eg output from `rclone -V`)

rclone v1.40
- os/arch: linux/arm
- go version: go1.10

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

Ubuntu Linux i386 arm. 

####  Which cloud storage system are you using? (eg Google Drive)

Google Drive (G-Suite Business).

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

nohup rclone move --transfers 1 /home/ZAWACK/2/ storage:/guillaumesoucy/

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)  

root@storage:~# rclone -vv move --transfers 1 /home/ZAWACK/2/ storage:/guillaumesoucy/
2018/04/06 00:56:58 DEBUG : rclone: Version "v1.40" starting with parameters ["rclone" "-vv" "move" "--transfers" "1" "/home/ZAWACK/2/" "storage:/guillaumesoucy/"]
2018/04/06 00:56:58 DEBUG : Using config file from "/root/.config/rclone/rclone.conf"
2018/04/06 00:57:02 INFO  : Google drive root 'guillaumesoucy': Modify window is 1ms
2018/04/06 00:57:04 DEBUG : **removed-file-name**: Sending chunk 0 length 8388608
^C

**Comment by ncw** [comment]
Note that rclone normally reports transfer rates in MBytes/s not MBit/s.

Are you transferring big files or lots of small files?  Lots of small files is very slow with google drive.  You can try increasing `--transfers` which may help a bit.

You can increase the drive transfer rate by increasing --drive-chunk-size at the cost of memory.

I can transfer a 100MB file to drive at 12.5 MBytes/s which is 100 Mbit/s.

**Comment by amlopin** [comment]
I have the same issue with my SoYouStart. I can upload to 25Mb/s (which is my guarantee bandwidth) but with rclone I can not go over 5Mb/s in each transfer. I know the issue with the ARM Storage SYS with the kernel (https://www.lowendtalk.com/discussion/146114/new-soyoustart-2018-prices#latest) , maybe kernel problems...

**Comment by ncw** [comment]
SSL via go is quite slow on ARM as it doesn't use particularly efficient code or crypt acceleration.

I even wrote a [patch for the go standard library](https://go-review.googlesource.com/c/go/+/38366), unfortunately it hasn't been merged due to licensing difficulties :-(

**Comment by amlopin** [comment]
I´ve checked and uploading crypt not go over 5Mb/s but uncrypt is around 11-12Mb/s with one transfer... anyway I'm not in a rush  :-D 
 Thanks Nick

**Comment by ncw** [comment]
Ok I'm going to close this issue as I don't think I can do anything about it in rclone.

The ARM crypto slowness is being worked on in the go compiler and go1.11 will be a bit better.  We really need the go std library to use ARM crypto accelerators where available.  Hopefully this will happen at some point in the future with a future version of go.
