### ISSUE TITLE
KMS for S3 file creation

### ISSUE THREAD

**Issue by MatthewVance** [ncw/rclone#2217]
#### What is the problem you are having with rclone?
An issue was reported on the [forum](https://forum.rclone.org/t/kms-for-s3-file-creation/5255) where a KMS policy is preventing rclone from working with AWS S3. The policy reported as causing the issue was: 

```
{  
   “Version”:“2012-10-17”,
   “Id”:“PutObjPolicy”,
   “Statement”:[  
      {  
         “Sid”:“DenyUnEncryptedObjectUploads”,
         “Effect”:“Deny”,
         “Principal”:"",
         “Action”:         “s3:PutObject”,
         “Resource”:"arn:aws:s3:::YourBucket/",
         “Condition”:{  
            “StringNotEquals”:{  
               “s3:               x-amz-server-side-encryption”:               “aws:kms”
            }
         }
      }
   ]
}
```

I am submitting the issue on behalf of the original reporter and do not have answers to the standard issue questions.

It appears rclone needs to support the `--server-side-encryption aws:kms` and `--sse-kms-key-id <value>` flags as available in the AWS S3 CLI. See [AWS S3 Sync](https://docs.aws.amazon.com/cli/latest/reference/s3/sync.html) for an example.

I’m not 100% sure, but a quick look at the SDK looks like the s3crypto service may contain what’s needed to implement this: https://docs.aws.amazon.com/sdk-for-go/api/service/s3/s3crypto/

Good general AWS documentation about S3 and KMS encryption is available at:
- https://docs.aws.amazon.com/kms/latest/developerguide/services-s3.html#sse
- https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingServerSideEncryption.html
- https://aws.amazon.com/blogs/security/how-to-prevent-uploads-of-unencrypted-objects-to-amazon-s3/

**Comment by bsteiss** [comment]
So I had this problem.  I am not a developer nor do I pretend to be one but I believe I was able to make this work.  I did some preliminary testing and it seems to useing the correct

.  I have attached the s3.go file I modified.  Just run rclone.config and you will need to set the server_side_encryption to aws:kms . and you will get a new option for sse_kms_key_id which you can provide the arn of the key you want to use...
[s3.go.txt](https://github.com/ncw/rclone/files/2324874/s3.go.txt)

**Comment by ncw** [comment]
Thanks to @bsteiss this is now implemented :-)

https://beta.rclone.org/v1.42-152-gf243d2a3/ (uploaded in 15-30 mins)
