### ISSUE TITLE
bwlimit is uneven in the presence of buffering

### ISSUE THREAD

**Issue by ncw** [ncw/rclone#222]
Because the bwlimit limits the `io.Reader` when reading into a buffer it only limits the speed of reading into the buffer, not the actual upload speed.

This is a problem in particular with S3/Drive and multipart files. 

It is correct in the long term, but is burstier than it should be.

Could potentially fix by putting the limiter into the transport, or lower down the stack somehow.

**Comment by klauspost** [comment]
`B2` is also broken AFAICT, since it copies all files to temporary storage due to sha1 calculation.

**Comment by ncw** [comment]
There is now a method for fixing this in in 037a000 using fs.AccountByPart.  The b2 case is now fixed but the drive and s3 need fixing

**Comment by ncw** [comment]
This is now properly fixed for all remotes in #1443 except for s3 which does its own buffering and has its own issue.
