### ISSUE TITLE
Password prompt is output to --log-file

### ISSUE THREAD

**Issue by msalini** [ncw/rclone#2220]
Hi there,

this has been discussed in forum.
When the config password is enabled, the log file displays the password prompt line, and It should not be there.

I use rclone 1.40 on a linux i386 architecture.

Thanks,

Marco

**Comment by ncw** [comment]
Currently when `--log-file` is engaged it redirects stderr to the log file.

However we write the password prompts to stderr so these end up in the log file too.

What we should probably do is not do the redirection until we've asked for the password, or somehow keep the old stderr handle and get the password prompt routines to use that.

**Comment by TowerBR** [comment]
Just to remember that when using environment variables (which is very comfortable), the log only shows:

```2018/04/04 21:14:30 DEBUG: Using RCLONE_CONFIG_PASS password.```

**Comment by ncw** [comment]
This is now fixed in [the latest beta](https://beta.rclone.org) which will be released in 1.42.
