### ISSUE TITLE
JSON output for size command

### ISSUE THREAD

**Issue by mholt** [ncw/rclone#2234]
I'd like to request a feature (or be pointed to a workaround, if it exists): simply that there is an option for JSON output for the `rclone size` command. Unfortunately, some/several storage providers don't appear to return bucket or folder sizes with their API. So I guess the only way to do it reliably is to count the size item-by-item.

Is there a way to get a nice, standard (i.e. always in bytes), machine-readable output of `rclone size`? If not, do I have permission to submit a PR to implement it? :smile: Maybe as simple as a `--json` flag (as opposed to a whole separate command like `lsjson`)

Edit: Also, it [looks like](https://github.com/ncw/rclone/blob/d5b2ec32f10bdb053e39dc172680b8723c459706/fs/operations/operations.go#L893-L896) the `size` command is fairly efficient - can you confirm that this does not, in fact, load the entire (potentially huge) bucket into memory and instead performs a traversal one chunk at a time? If so, that's awesome. :+1: Any experiences on how fast it is with really big buckets?

**Comment by ncw** [comment]
> I'd like to request a feature (or be pointed to a workaround, if it exists): simply that there is an option for JSON output for the rclone size command. Unfortunately, some/several storage providers don't appear to return bucket or folder sizes with their API. So I guess the only way to do it reliably is to count the size item-by-item.

Indeed it is a bit hit and miss whether one provider or another returns the size.

Note there is the nacent `rclone quota` command here #2064 

> Is there a way to get a nice, standard (i.e. always in bytes), machine-readable output of rclone size? If not, do I have permission to submit a PR to implement it? smile Maybe as simple as a --json flag (as opposed to a whole separate command like lsjson)

I'd be happy to receive a `--json` flag PR for size!  The way we've done this [elsewhere in rclone](https://github.com/ncw/rclone/blob/master/cmd/lsjson/lsjson.go#L37) is just to define a go struct then dump it in native go style.

> Edit: Also, it looks like the size command is fairly efficient - can you confirm that this does not, in fact, load the entire (potentially huge) bucket into memory and instead performs a traversal one chunk at a time? If so, that's awesome. ￼

What it does (by default) is list the bucket a directory at a time using up to `--checkers` threads.  Each directory listing is paged by the provider into typically 100-1000 entries.  These will be converted to objects, which are consumed by `size` then left to the mercy of the garbage collector.

So at no time does it load everything in at once.  However if you use the `--fast-list` flag then it will load the whole listing into memory first.  (Though it occurs to me now that `--fast-list` is doing too much work for `rclone size` - it is designed to make the listing consistent across remotes for syncing).

>  Any experiences on how fast it is with really big buckets?

That depends on whether there are lots of files with small directories etc, but here is some anecdata.  Running on a swift (openstack/CEPH) bucket I get

(with the default `--checkers 8`)

```
$ time rclone size swift:bucket
Total objects: 816112
Total size: 140.407 GBytes (150761000412 Bytes)

real	9m44.213s
user	1m51.753s
sys	0m39.042s
```

Memory usage < 40M

```
$ time rclone --fast-list size swift:bucket
Total objects: 816112
Total size: 140.407 GBytes (150761000412 Bytes)

real	1m17.616s
user	0m17.907s
sys	0m2.557s
```

Memory usage >400M (after 30s forgot to look later!)

```
$ time rclone --checkers 64 size swift:bucket
Total objects: 816112
Total size: 140.407 GBytes (150761000412 Bytes)

real	3m5.084s
user	1m19.879s
sys	0m22.300s
```

Compare with `lsd` which does work for swift...

```
$ rclone lsd swift: | grep bucket
129674146972 2018-04-12 15:03:59    816112 bucket
 21086853440 2018-04-12 15:03:59         4 bucket_segments
```
