### ISSUE TITLE
Incorrect error message from Google Drive on export

### ISSUE THREAD

**Issue by odinian** [ncw/rclone#2235]
#### What is the problem you are having with rclone?
When using one of the commands to export files from G Suite, if the file is too large (> 10MB, although this isn't documented by Google), the API will throw an error. The problem is the error from Google is "This file is too large to be exported.", but the http response is "403 Forbidden". clone is reporting the 403 Forbidden, but not the "fin is too large".

To replicate, make a Slides deck with some large photos/images, then try to copy from Google Drive using rclone (copy, copy, or sync).

#### What is your rclone version (eg output from `rclone -V`)
1.40

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
OS X

####  Which cloud storage system are you using? (eg Google Drive)
Google Drive

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone copyto gsuite:/test /Volumes/more/g_suite2/ 

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

--dump report:
2018/04/11 11:31:42 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2018/04/11 11:31:42 INFO  : Local file system at /Volumes/more/g_suite2: Waiting for checks to finish
2018/04/11 11:31:42 INFO  : Local file system at /Volumes/more/g_suite2: Waiting for transfers to finish
2018/04/11 11:31:42 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2018/04/11 11:31:42 DEBUG : HTTP REQUEST (req 0xc420144e00)
2018/04/11 11:31:42 DEBUG : GET /drive/v3/files/<file ID redacted>/export?mimeType=application%2Fvnd.openxmlformats-officedocument.presentationml.presentation HTTP/1.1
Host: www.googleapis.com
User-Agent: rclone/v1.40
Authorization: XXXX
Accept-Encoding: gzip

2018/04/11 11:31:42 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2018/04/11 11:31:52 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2018/04/11 11:31:52 DEBUG : HTTP RESPONSE (req 0xc420144e00)
2018/04/11 11:31:52 DEBUG : HTTP/1.1 403 Forbidden
Transfer-Encoding: chunked
Alt-Svc: hq=":443"; ma=2592000; quic=51303433; quic=51303432; quic=51303431; quic=51303339; quic=51303335,quic=":443"; ma=2592000; v="43,42,41,39,35"
Cache-Control: private, max-age=0
Content-Type: application/json; charset=UTF-8
Date: Wed, 11 Apr 2018 17:31:52 GMT
Expires: Wed, 11 Apr 2018 17:31:52 GMT
Server: GSE
Vary: Origin
Vary: X-Origin
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Xss-Protection: 1; mode=block

ee
{
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "exportSizeLimitExceeded",
    "message": "This file is too large to be exported."
   }
  ],
  "code": 403,
  "message": "This file is too large to be exported."
 }
}

command line results:
2018/04/11 13:57:38 Failed to copyto: failed to open source object: bad response: 403: 403 Forbidden

**Comment by ncw** [comment]
This should have been fixed in e82452ce9a88f949f7f8aa3c6aff143216ce2c0c which should be in [the latest beta](https://beta.rclone.org) now.

Can you make another issue with the workarounds for downloading the large docs in too please?

**Comment by odinian** [comment]
I tried the beta, and the error reporting looks much better!

Failed to copyto: failed to open source object: open file failed: googleapi: Error 403: This file is too large to be exported., exportSizeLimitExceeded

**Comment by mneiger** [comment]
the problem seems identical with #2243

**Comment by ncw** [comment]
That is great! I'll close this now then.

**Comment by odinian** [comment]
Sorry about my ignorance, but how long does it take for a fix like this to get rolled into a release?

**Comment by ncw** [comment]
@odinian It will be in the 1.41 release which is planned for 29th April 2018 so about a week!
