### ISSUE TITLE
Failed to rc: operation "cache/expire" failed: remote control command failed: / doesn't exist in cache

### ISSUE THREAD

**Issue by PiscisSwimeatus** [ncw/rclone#2237]
#### What is the problem you are having with rclone?

Unable to expire the whole cache

#### What is your rclone version (eg output from `rclone -V`)

rclone v1.40-055-gaef1f16a-go-versionβ
- os/arch: linux/amd64
- go version: go1.10.1

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

Ubuntu 16.04

####  Which cloud storage system are you using? (eg Google Drive)

Google Drive

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

aj@HetznerEX61:~⟫ rclone rc cache/expire remote=/ withData=true
{
        "error": "remote control command failed: / doesn't exist in cache",
        "input": {
                "remote": "/",
                "withData": "true"
        }
}
2018/04/12 13:22:46 Failed to rc: operation "cache/expire" failed: remote control command failed: / doesn't exist in cache

Testing a subfolder works fine:

1 aj@HetznerEX61:~⟫ rclone rc cache/expire remote=/Miscellaneous withData=true
{
        "message": "cached directory cleared: /Miscellaneous",
        "status": "ok"
}

**Comment by ncw** [comment]
Can you try just `clone rc cache/expire remote= withData=true` and see if that works?

**Comment by daniel-loader** [comment]
This is my bad when I updated the documentation I could have sworn you could evict stuff on the root level of the cache and included it in the PR, went back and tried it now and got the same result as this issue.

I guess it's worth looking at to be able to purge the cache at the root level without doing a SIGHUP to lose the data too, thoughts @remusb ?

**Comment by remusb** [comment]
Yep. Not sure if there's some limitation there that could prevent it but it's worth trying

**Comment by remusb** [comment]
This should be fixed in https://beta.rclone.org/v1.41-102-g13ccb398-test-remusb/
It's a branch build. Seems GIT had issues building a beta from the master today.

@ncw same here :( https://github.com/ncw/rclone/issues/2205

**Comment by ncw** [comment]
I had another commit to push which I've done so the beta should be in

https://beta.rclone.org/v1.41-104-gd1892896/ (uploaded in 15-30 mins)

**Comment by remusb** [comment]
Here's the working beta: https://beta.rclone.org/v1.41-105-g4df17949/
