### ISSUE TITLE
Feature request: Add Backblaze B2 as storage backend 

### ISSUE THREAD

**Issue by ech1965** [ncw/rclone#224]
https://www.backblaze.com/b2/cloud-storage.html

Looks like a attractive alternative to Amazon S3...

**Comment by ncw** [comment]
Good idea! I've been  on the waitlist for some time now - just waiting for my invite.

**Comment by durval-menezes** [comment]
Even better, please also add their "consumer" product, "Backblaze Unlimited Backup". That would make a great alternative/competition for Amazon Cloud Storage (currently 20% cheaper on a 2-year basis).

**Comment by ncw** [comment]
@durval-menezes I don't think there is a public API for that is there?

**Comment by McBochi** [comment]
They don't provide one and I think reverse engineering is not the best idea in this case.  
Got an invite already and am playing around a bit, implementing another backend for B2 should be pretty straight forward. However they for example "only" feature a SHA1 hash and not a MD5 one, so syncing would need some more effort to work.

**Comment by ncw** [comment]
I have made a prototype for a b2 backend.  There are several problems with it though, the major one being that to upload files we need to know the sha1 in advance.  I've worked around this by copying the data into a tempfile but it isn't optimal.

I'm having a problem uploading certain file names too for reasons I haven't figured out yet - I suspect a bug in B2...

When it working slightly better I'll put a beta out for you to try.

**Comment by cbess** [comment]
@ncw I recently cloned the project to add B2 support as well. I'm glad to see you're already got something working. I'd like to help if possible, I received access to it and would like to use it with `rsync`. Thanks for providing this great tool and Go lang code!

**Comment by ncw** [comment]
The beta is ready! Should be fully functional.  Let me know!

http://pub.rclone.org/v1.25-20-g42c3005%CE%B2/

**Comment by ncw** [comment]
I just remembered I forgot to put the directory listing paging in, so it will be limited to 1000 objects in a bucket - fix coming soon!

**Comment by cbess** [comment]
Dude, awesome! I'll test it when you make it available. Thanks again for working on it.

**Comment by cbess** [comment]
And I'm guessing that the branch is still unavailable. @ncw Are you going to merge it into master soon, or...?

**Comment by ncw** [comment]
@cbess you can download a binary from the link above http://pub.rclone.org/v1.25-20-g42c3005%CE%B2/ - I'll merge to master after a bit of feedback so please test!

**Comment by cbess** [comment]
I've tested it on a simple text file, its working as expected. I'm using **rclone-v1.25-20-g42c3005β-linux-386.zip**. I've tested `config`, `ls`, `lsd`, `sync` and `copy`. I'm going to throw a couple thousand files at it soon, hopefully over the weekend. I'll let you know what happens.

**Comment by cbess** [comment]
I appreciate the comments on the func signatures. @ncw I have a small request, please throw some extra comments in there to help me learn some more about how to add *other* backend support, namely the connection/auth portions.

**Comment by ncw** [comment]
Here is a new beta with the 1000 file limit fixed: http://pub.rclone.org/v1.25-21-gfd120b3%CE%B2/

**Comment by ncw** [comment]
@cbess Thanks for testing. I don't know if you saw the CONTRIBUTING.md file I put up today which has a section on how to write a new backend.  Not a lot of stuff on auth though!

**Comment by cbess** [comment]
No prob. Nice, I didn't see it, but I'm check it out now. I added a link in the `readme` to maybe prevent others from missing it as well. See #267.

**Comment by Sunako** [comment]
@ncw Just wondering by any chance did you send your [gist](https://gist.github.com/ncw/166dabf352b399f1cc1c) to the Backblaze people? If so did they ever respond about the X-Bz-Content-Sha1 and fileinfo concerns?

**Comment by ncw** [comment]
@Sunako I did yes via twitter and their support system, but I haven't heard anything back from them.

We have a plan to avoid the tempfile (see discussions in #282). This also requires the internal hashing changes in #292.

I still think Backblaze should change the interface though - it makes it a lot less useful as a cloud storage system than all the other ones I've implemented as you can't stream to it.

**Comment by Sunako** [comment]
@ncw I saw that sha1 pull a bit ago, didn't know about #282 though, looks good.

I will try to bug a few people I know internally at backblaze, see if I can't get some info or maybe make them aware of those concerns.

**Comment by ncw** [comment]
@Sunako thanks!
