### ISSUE TITLE
move and moveto commands cause folder linking on Google Drive

### ISSUE THREAD

**Issue by kaczmarkiewiczp** [ncw/rclone#2245]
#### What is the problem you are having with rclone?
When using the move and moveto commands in Google Drive on directories, the source gets "linked" to the destination. The source directory doesn't get deleted (even when using --delete-after flag), and renaming or deleting either the source or destination will affect both of them. On Google Drive web, it shows that the source is located in two places (source and destination).

#### What is your rclone version (eg output from `rclone -V`)
1.40

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
linux/amd64

####  Which cloud storage system are you using? (eg Google Drive)
Google Drive

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
`rsync move drive:test/move/srcDir drive:test/move/Folder/srcDir`
`rsync moveto drive:test/move/srcDir drive:test/move/Folder/srcDir`

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
```
$ rclone lsf -R drive:test/move
Folder/
srcDir/
$
$ rclone -vv move drive:test/move/srcDir drive:test/move/Folder/srcDir
2018/04/13 11:34:01 DEBUG : rclone: Version "v1.40" starting with parameters ["rclone" "-vv" "move" "drive:test/move/srcDir" "drive:test/move/Folder/srcDir"]
2018/04/13 11:34:01 DEBUG : Using config file from "/home/user/.config/rclone/rclone.conf"
2018/04/13 11:34:08 INFO  : Encrypted drive 'drive:test/move/Folder/srcDir': Modify window is 1ms
2018/04/13 11:34:08 DEBUG : Encrypted drive 'drive:test/move/Folder/srcDir': Using server side directory move
2018/04/13 11:34:08 INFO  : Encrypted drive 'drive:test/move/Folder/srcDir': Server side directory move succeeded
2018/04/13 11:34:08 INFO  : 
Transferred:      0 Bytes (0 Bytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:        7.6s

2018/04/13 11:34:08 DEBUG : 5 go routines active
2018/04/13 11:34:08 DEBUG : rclone: Version "v1.40" finishing with parameters ["rclone" "-vv" "move" "drive:test/move/srcDir" "drive:test/move/Folder/srcDir"]
$
$ rclone lsf -R drive:test/move
Folder/
srcDir/
Folder/srcDir/
$
$ rclone -vv moveto drive:test/move/srcDir drive:test/move/newDir
2018/04/13 11:36:23 DEBUG : rclone: Version "v1.40" starting with parameters ["rclone" "-vv" "moveto" "drive:test/move/srcDir" "drive:test/move/newDir"]
2018/04/13 11:36:23 DEBUG : Using config file from "/home/user/.config/rclone/rclone.conf"
2018/04/13 11:36:36 INFO  : Encrypted drive 'drive:test/move/newDir': Modify window is 1ms
2018/04/13 11:36:36 DEBUG : Encrypted drive 'drive:test/move/newDir': Using server side directory move
2018/04/13 11:36:37 INFO  : Encrypted drive 'drive:test/move/newDir': Server side directory move succeeded
2018/04/13 11:36:37 INFO  : 
Transferred:      0 Bytes (0 Bytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:       13.8s

2018/04/13 11:36:37 DEBUG : 5 go routines active
2018/04/13 11:36:37 DEBUG : rclone: Version "v1.40" finishing with parameters ["rclone" "-vv" "moveto" "drive:test/move/srcDir" "drive:test/move/newDir"]
$
$ rclone lsf -R drive:test/move
Folder/
newDir/
Folder/newDir/
```

**Comment by odinian** [comment]
I think this is because Google's "folder" is just a parent ID field, and the Parent ID field can be multi value. The rclone move should create the new parent id, but needs to remove the old one after a successful write.

**Comment by ncw** [comment]
This used to work... I wonder when it stopped...

Should be easy enough to find out with git bisect

**Comment by ncw** [comment]
Testing with git bisect...

Save this script as `test-drive.sh`

```
#!/bin/sh

set -e

go install
rclone purge drive:test/move --retries 1 || true
rclone mkdir drive:test/move/Folder
rclone mkdir drive:test/move/srcDir
rclone -vv move drive:test/move/srcDir drive:test/move/Folder/srcDir
if rclone ls drive:test/move/srcDir ; then
    echo "Dir found - bad"
    exit 1
else
    echo "Dir not found good"
fi
```

Then

```
git checkout master
git bisect start
git bisect bad
git checkout v1.39
git bisect good
git bisect run ./test-drive.sh
```

Finds in a little while 07f20dd1fd6f89b9ebdefdc8964a8e9ee9aa9892 is the first bad commit

```
commit 07f20dd1fd6f89b9ebdefdc8964a8e9ee9aa9892
Author: Fabian Möller <fabianm88@gmail.com>
Date:   Wed Jan 24 00:46:41 2018 +0100

    drive: migrate to api v3

:040000 040000 aad5e99c16dab297c5f79c505bb4d303d2497953 35a6b83de5afb909d3f83c9dfc29b9c2d7c20247 M	backend
bisect run success
```

Which is perhaps not surprising...

Looking at the transaction dump, it appears to be using the wrong ID as the src parent - it is using the ID of the directory, not the ID of its parent.

Will have a go at fixing now...

**Comment by ncw** [comment]
I've fixed this here - please re-open if you have any more problems!

https://beta.rclone.org/v1.40-084-g3d5106e5/ (uploaded in 15-30 mins)
