### ISSUE TITLE
Transfers fail with http remote and .txt/.html files

### ISSUE THREAD

**Issue by eemailme** [ncw/rclone#2247]
#### What is the problem you are having with rclone?
When copying items from an `http` remote, some .txt and .html files fail to transfer with the error:
`corrupted on transfer: sizes differ 0 vs XXXXXX`

This is only happening with plaintext files (but not every one of them.)
It occurs when using Google Drive and a local dir as the destination.

I noticed in Google Drive's trash, the deleted file is the correct size. So it seems to not realize that the size is actually correct and gets reported a size of 0 for some reason, assuming the transfer failed.

#### What is your rclone version (eg output from `rclone -V`)
rclone v1.38
- os/arch: windows/amd64
- go version: go1.9

Also tried with:
rclone v1.40
- os/arch: linux/amd64
- go version: go1.10

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Windows 10x64, Ubuntu 16.04x64

####  Which cloud storage system are you using? (eg Google Drive)
http

#### Rclone config

```
[stuff]
type = http
url = https://the-eye.eu/public/rom/Amiga/GameBase%20Amiga%20v1.6/Extras/Instructions/S
```

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
`rclone --config=test.conf -vv copy stuff: stuff`

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
https://txt.jha.sh/github/2018/04/13/g32xl/rclone-log.txt

**Comment by jahands** [comment]
I'm doing --ignore-size for now to get around this issue.

**Comment by ncw** [comment]
I've fixed this here

https://beta.rclone.org/v1.40-086-gb8381408/ (uploaded in 15-30 mins)

Please let me know if it doesn't work for you - I tried it on your remote config and it fixed it for me :-)
