### ISSUE TITLE
Upload releases to github too

### ISSUE THREAD

**Issue by ncw** [ncw/rclone#225]
Upload rclone releases to github too so there is redundancy.

**Comment by Raynok** [comment]
Great, look forward.

**Comment by kevfromireland** [comment]
This is what we use to upload our product to GitHub Releases (https://github.com/aktau/github-release)

**Comment by ncw** [comment]
I've uploaded all the historical releases to github too.

Note that if you want to find the latest (for example) linux amd64 release on github, you can get the URL like this.

```
curl -s https://api.github.com/repos/ncw/rclone/releases | grep browser_download_url | grep linux-amd64 | head -n 1 | cut -d '"' -f 4
```

Which prints
```
https://github.com/ncw/rclone/releases/download/v1.25/rclone-v1.25-linux-amd64.zip
```
