### ISSUE TITLE
Mount regression in 1.40?

### ISSUE THREAD

**Issue by Wicked0ne** [ncw/rclone#2250]
#### What is the problem you are having with rclone?
rclone mount does not work as it used to

#### What is your rclone version (eg output from `rclone -V`)
It's broken on 1.40 and works on 1.39

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Ubuntu linux 16.04 x64

####  Which cloud storage system are you using? (eg Google Drive)
Google Drive
#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone mount DriveStorage: /mnt/local/ --allow-other

I run a file server with rclone mouting my google drive acccount locally. I then share that mount locally with samba and this has worked excellent up until 1.40.

With version 1.40 this no longer works and causes whatever program that is trying to access the mount point to freeze for a few mins. 

I do not see anything in the logs that is obvious. I've also reproduced this on a separate machine of mine(2nd machine is also using ubuntu 16.04 x64) and have the same results.

setup simple samba share at /mnt/samba
rclone-1.39 mount GDrive: /mnt/samba/gdrive --allow-other # Works
rclone-1.40 mount GDrive: /mnt/samba/gdrive --allow-other # Does not work

Please let me know what other information you might need to look into this.

**Comment by ncw** [comment]
Can you try the latest beta please? beta.rclone.org

**Comment by Wicked0ne** [comment]
@ncw Thanks for getting back, I just tested out the latest beta and it seems to have fixed the issue I was having.

**Comment by ncw** [comment]
This was fixed in 98a924602f71564fb88f14b1fd3009cca06936d3.  You can also work-around it by setting `--attr-timeout 1s`

I'll close this now.
