### ISSUE TITLE
Cache [Drive]: new subfolders are not detected

### ISSUE THREAD

**Issue by stokkes** [ncw/rclone#2251]
### rclone version

```
rclone v1.40-082-gdc247d21β
- os/arch: linux/amd64
- go version: go1.10.1
```

### backend 

Drive -> cache -> crypt

### mount command

```
/usr/bin/rclone mount crypt-cache: /mnt/media \
   --allow-other \
   --allow-non-empty \
   --dir-cache-time=1m \
   --cache-db-purge \
   --cache-chunk-size=10M \
   --cache-info-age=168h \
   --cache-workers=5 \
   --cache-db-path /opt/rclone \
   --syslog \
   --umask 002 \
   --rc \
   --log-level INFO
```

### How to recreate

This requires the cache remote be mounted on **two** hosts:

**on host 1**

`mkdir /mnt/media/111`
`touch /mnt/media/111/file.txt`

**on host 2** (after the 1 minute dir cache time)

`ls /mnt/media/111`

**result on host 2**
`ls: cannot access '/mnt/media/111': No such file or directory`

### Why this is a major problem

If any new folder is created within a folder that is already in the cache, rclone will not detect that folder. 

The impact is that if you're adding a new movie folder, new tv show, new tv show season, these will **never** be picked up by the 2nd host until the cache expires on its own. 

Yes you can manually evict the cache but that shouldn't be necessary. 

Needless to say this is a pretty serious bug. This should never happen.

**Comment by jrarseneau** [comment]
I think this is the same as #2117 and #2155 , can @remusb or @seuffert confirm?

I'm a bit confused if this has been resolved or not. the last comment in #2117 from @remusb indicates beta 031 should fix it but that doesn't seem to be the cast (that comment is newer also than the latest comment on #2117), leading me to believe some work was done, but maybe not updated on the other issue?

Thanks

**Comment by Krandor1** [comment]
2177 is a different issue.  That is the addition of a new file to an existing directory which was a bug that crept in and has been fixed.  

2155 is the directory issue and does not appear to be taken care of yet.

**Comment by B4dM4n** [comment]
I can reproduce this behavior without `cache` using google-drive.
New folders are not recognized by `poll-interval`.

I will open a PR to fix this issue.

**Comment by stokkes** [comment]
@B4dM4n @ncw 

Thank you so much! This appears to fixed the problem on the latest beta. 

I'm curious, does this technically resolve #2155 as well?
