### ISSUE TITLE
Rclone wont mount windows 10

### ISSUE THREAD

**Issue by herohamp** [ncw/rclone#2254]
#### What is the problem you are having with rclone?
rclone wont mount on windows

#### What is your rclone version (eg output from `rclone -V`)
C:\Users\herohamp\Documents\commands>rclone -V
rclone v1.40
- os/arch: windows/amd64
- go version: go1.10

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Windows 10 64 Bit

####  Which cloud storage system are you using? (eg Google Drive)
Google Drive

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone mount music: M: -vv

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

C:\Users\herohamp\Documents\commands>rclone mount music: M: -vv
2018/04/15 15:43:12 DEBUG : rclone: Version "v1.40" starting with parameters ["rclone" "mount" "music:" "M:" "-vv"]
2018/04/15 15:43:12 DEBUG : Using config file from "C:\\Users\\herohamp\\.config\\rclone\\rclone.conf"
2018/04/15 15:43:12 INFO  : Google drive root '': Modify window is 1ms
2018/04/15 15:43:12 DEBUG : Google drive root '': Mounting on "M:"
2018/04/15 15:43:12 DEBUG : vfs cache root is "C:\\Users\\herohamp\\AppData\\Local\\rclone\\vfs\\music"
2018/04/15 15:43:12 DEBUG : Adding path "vfs/forget" to remote control registry
2018/04/15 15:43:12 DEBUG : Google drive root '': Mounting with options: ["-o" "fsname=music:" "-o" "subtype=rclone" "-o" "max_readahead=131072" "-o" "attr_timeout=0" "-o" "atomic_o_trunc" "-o" "uid=-1" "-o" "gid=-1" "--FileSystemName=rclone"]
panic: cgofuse: cannot find winfsp

goroutine 20 [running]:
github.com/ncw/rclone/vendor/github.com/billziss-gh/cgofuse/fuse.(*FileSystemHost).Mount(0xc0422b4ed0, 0xc0420280d0, 0x2, 0xc04230a500, 0xf, 0x14, 0x0)
        C:/gopath/src/github.com/ncw/rclone/vendor/github.com/billziss-gh/cgofuse/fuse/host.go:1131 +0x4fa
github.com/ncw/rclone/cmd/cmount.mount.func1(0xc0422b4ed0, 0xc0420280d0, 0x2, 0xc04230a500, 0xf, 0x14, 0x10739c0, 0xc0423a0000, 0xc0422b2660)
        C:/gopath/src/github.com/ncw/rclone/cmd/cmount/mount.go:142 +0x71
created by github.com/ncw/rclone/cmd/cmount.mount
        C:/gopath/src/github.com/ncw/rclone/cmd/cmount/mount.go:140 +0x3d4

**Comment by ncw** [comment]
This is the relevant line from the log `panic: cgofuse: cannot find winfsp`

So it looks like you need to install (or reinstall) [WinFSP](https://github.com/billziss-gh/winfsp/releases/latest).

**Comment by bobloadmire** [comment]
i've installed winFSP and i'm still receiving this error

**Comment by ncw** [comment]
> i've installed winFSP and i'm still receiving this error

Can you post the log and traceback you get?

**Comment by beirenwuze** [comment]
Hello，i've installed winFSP and i'm still receiving this error。
2023/09/12 20:19:07 NOTICE: Serving remote control on http://127.0.0.1:19090/
2023/09/12 20:19:09 Fatal error: failed to mount FUSE fs: mount stopped before calling Init: mount failed: cgofuse: cannot find winfsp
I dont know how to handle it.

**Comment by ncw** [comment]
@beirenwuze please [post on the rclone forum](https://forum.rclone.org/) about this - thanks!
