### ISSUE TITLE
webdav: leading slash confuses directory listing

### ISSUE THREAD

**Issue by thanaus** [ncw/rclone#2257]
Hello,

Thanks for this tool. It's very simple to use it and very amazing about functionnality !

#### What is the problem you are having with rclone?
I have an issue while deleting files from NextCloud storage system. There's no deletetion at all.

#### What is your rclone version (eg output from `rclone -V`)
rclone v1.40
- os/arch: linux/amd64
- go version: go1.10

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Linux rclone 3.16.0-4-amd64 #1 SMP Debian 3.16.43-2+deb8u5 (2017-09-19) x86_64 GNU/Linux

####  Which cloud storage system are you using? (eg Google Drive)
Webdav - NextCloud

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
./rclone --config ../../core/config/rclone.conf delete 90:/test/plugin_info

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
2018/04/16 09:39:28 DEBUG : rclone: Version "v1.40" starting with parameters ["./rclone" "-vv" "--config" "../../core/config/rclone.conf" "delete" "90:/test/plugin_info"]
2018/04/16 09:39:28 DEBUG : Using config file from "/var/www/html/plugins/cloudsyncpro/core/config/rclone.conf"
2018/04/16 09:39:28 INFO  : webdav root '/test/plugin_info': Modify window is 1s
2018/04/16 09:39:28 INFO  : Waiting for deletions to finish
2018/04/16 09:39:28 DEBUG : Item with unknown path received: "/remote.php/webdav/test/plugin_info/", "/test/plugin_info/"
2018/04/16 09:39:28 DEBUG : Item with unknown path received: "/remote.php/webdav/test/plugin_info/configuration.php", "/test/plugin_info/"
2018/04/16 09:39:28 DEBUG : Item with unknown path received: "/remote.php/webdav/test/plugin_info/info.json", "/test/plugin_info/"
2018/04/16 09:39:28 DEBUG : Item with unknown path received: "/remote.php/webdav/test/plugin_info/info.xml", "/test/plugin_info/"
2018/04/16 09:39:28 DEBUG : Item with unknown path received: "/remote.php/webdav/test/plugin_info/install.php", "/test/plugin_info/"
2018/04/16 09:39:28 DEBUG : Item with unknown path received: "/remote.php/webdav/test/plugin_info/netatmopro_icon.png", "/test/plugin_info/"
2018/04/16 09:39:28 DEBUG : 2 go routines active
2018/04/16 09:39:28 DEBUG : rclone: Version "v1.40" finishing with parameters ["./rclone" "-vv" "--config" "../../core/config/rclone.conf" "delete" "90:/test/plugin_info"]

**Comment by thanaus** [comment]
Do you need an access to my nextcloud in order to reproduce this issue ?

For information, I think it's not only an issue with deletion.
This is logs for 'ls' command :
2018/04/19 02:55:53 INFO  : webdav root '/': Modify window is 1s
2018/04/19 02:55:53 ERROR : remote.php/webdav: Entry doesn't belong in directory "" (contains subdir) - ignoring
2018/04/19 02:55:53 ERROR : remote.php/webdav/Documents: Entry doesn't belong in directory "" (contains subdir) - ignoring
2018/04/19 02:55:53 ERROR : remote.php/webdav/Nextcloud Manual.pdf: Entry doesn't belong in directory "" (contains subdir) - ignoring
2018/04/19 02:55:53 ERROR : remote.php/webdav/Nextcloud.mp4: Entry doesn't belong in directory "" (contains subdir) - ignoring
2018/04/19 02:55:53 ERROR : remote.php/webdav/Photos: Entry doesn't belong in directory "" (contains subdir) - ignoring
2018/04/19 02:55:53 ERROR : remote.php/webdav/test: Entry doesn't belong in directory "" (contains subdir) - ignoring

Regards,

**Comment by ncw** [comment]
It looks like that your nextcloud remote is somehow mis-configured as in it is giving back URLs that rclone is not expecting.

Does the url look like this in the config? Make sure the case is correct and it ends with a /

    url = https://nextcloud.example.com/remote.php/webdav/

**Comment by thanaus** [comment]
The URL of my config is ending with a /

[90]
type = webdav
url = https://xxxx.xxx.org/remote.php/webdav/
vendor = nextcloud
user = thanaus
pass = [xxx]

How to investigate this issue ?

**Comment by thanaus** [comment]
I just sent you an email with credentials.
Thanks a lot !

Regards,

**Comment by thanaus** [comment]
Thanks a lot !!!!
You were very fast in the analysis and correction. All my congratulations

**Comment by ncw** [comment]
This is now fixed :-)  Find it here

https://beta.rclone.org/v1.40-106-g56ce7843/ (uploaded in 15-30 mins)

or in [the latest beta](https://beta.rclone.org) or in 1.41 when it is released.
