### ISSUE TITLE
Implement -u/--update so creation times can be used on all remotes (eg acd)

### ISSUE THREAD

**Issue by michaelthwaite** [ncw/rclone#226]
Amazon Cloud drive doesn't have the modified date but does have create date. Could we add a flag or set the default behavior on ACD to allow the checker to compare remote createdate with local modified date?

Background: I'm syncing from 2TB (future 8TB) to Cloud Drive in various chunks and folders and it's going great unfortunately, each time I re-sync I'm having to re-calculate local md5s on all of the files on a remote drive, that takes about 1 week. Maintaining a local md5 db might also be an option but, I think comparing my local modified date to the remote create date then deleting & recopying would be superb - it'd also leave older files in the trash on the remote which would be a benefit. Thanks.

**Comment by ncw** [comment]
Unfortunately the creation date can't be set, so it will be the time the file was uploaded.  rclone checks for timestamps being equal in the sync so I don't think this will work as it stands.  You can see the times rclone has if you do an `rclone lsl` - these will show the created date on acd.

I think you might be asking could rclone use the acd creation date and check if it is older than the current modified date on the file?  That isn't the way it works at the moment - it is a pure equality check.

There is a precedent for this in rsync which has this flag and it would probably be a reasonably easy to implement.

        -u, --update                skip files that are newer on the receiver

That could then ignore the Precision of the ModTime too.

I wouldn't want to do this by default though, but having it controlled by a flag seems like a reasonable idea.

1 week of md5s is a lot though!  We've had some ideas about caching the md5 calculation in #157 which would help.

However you might find the `--size-only` flag is good enough for what you need.

      --size-only[=false]: Skip based on size only, not mod-time or checksum

**Comment by michaelthwaite** [comment]
That's great and what I'm looking for - use the create time from ACD and compare that to my local modified time.

Size is unfortunately not a reliable measure with what I'm doing - I have a lot of sparse-images that generate a lot of identically sized files, changes in them reflect in the modified date (and md5 checksum) but not the size.

A flag to say --use-remote-create-date as the modified time would be perfect! Thanks.

**Comment by ncw** [comment]
I think `--newer` is probably the best we can do, but I think that would work for you just fine provided the clock of your source machine is correct.

**Comment by michaelthwaite** [comment]
Sounds good.

**Comment by axtux** [comment]
If you want to complain to Amazon https://forums.developer.amazon.com/forums/thread.jspa?threadID=8762&tstart=0

**Comment by ncw** [comment]
I've implemented `-u` / `--update` in 280ac26464417033224b97f74f6f92f932ddcb1d.  You can find a beta of the feature here

http://pub.rclone.org/v1.27-51-g280ac26%CE%B2/

Thanks for suggesting it

Nick
