### ISSUE TITLE
Error reading files in subdirectory of Onedrive root folder

### ISSUE THREAD

**Issue by ACParucker** [ncw/rclone#2260]
#### What is the problem you are having with rclone?
rclone can't read my local files.
I have a directory (d:\onedrive) with is my onedrive base directory and it's sync with my onedrive account.
Any file in this folder or subdirectories rclone can't read now. 
In others directories rclone can read correct.
I have 2 one drive accounts. My official account sync with d:\onedrive and another onedrive account I use to clone this directory.
Last week it's work fine. Today it's not.

#### What is your rclone version (eg output from `rclone -V`)
Tried with:
rclone v1.40
- os/arch: windows/amd64
- go version: go1.10

Also tried with:
rclone v1.40-086-gb8381408
- os/arch: windows/amd64
- go version: go1.10

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Windows 10 Home Single Language
Version 1709
Build 16299.371

####  Which cloud storage system are you using? (eg Google Drive)
OneDrive.
Installed version: Version 2018
Build: 18.044.0301.0006

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone copy D:\OneDrive\BKP_TMP\new.pdf Clone-OneDrive:BKP

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
rclone -vv copy D:\OneDrive\BKP_TMP\new.pdf Clone-OneDrive:BKP > log.txt
2018/04/17 19:20:06 DEBUG : rclone: Version "v1.40" starting with parameters ["rclone" "-vv" "copy" "D:\\OneDrive\\BKP_TMP\\new.pdf" "Clone-OneDrive:BKP"]
2018/04/17 19:20:06 DEBUG : Using config file from "C:\\Users\\ACParucker\\.config\\rclone\\rclone.conf"
2018/04/17 19:20:07 INFO  : One drive root 'BKP': Modify window is 1s
2018/04/17 19:20:07 ERROR : : error reading source directory: failed to read directory "": Readdir \\?\D:\OneDrive\BKP_TMP\new.pdf: O sistema não pode encontrar o caminho especificado.
2018/04/17 19:20:07 INFO  : One drive root 'BKP': Waiting for checks to finish
2018/04/17 19:20:07 INFO  : One drive root 'BKP': Waiting for transfers to finish
2018/04/17 19:20:07 ERROR : Attempt 1/3 failed with 1 errors
2018/04/17 19:20:07 ERROR : : error reading source directory: failed to read directory "": Readdir \\?\D:\OneDrive\BKP_TMP\new.pdf: O sistema não pode encontrar o caminho especificado.
2018/04/17 19:20:07 INFO  : One drive root 'BKP': Waiting for checks to finish
2018/04/17 19:20:07 INFO  : One drive root 'BKP': Waiting for transfers to finish
2018/04/17 19:20:07 ERROR : Attempt 2/3 failed with 1 errors
2018/04/17 19:20:08 ERROR : : error reading source directory: failed to read directory "": Readdir \\?\D:\OneDrive\BKP_TMP\new.pdf: O sistema não pode encontrar o caminho especificado.
2018/04/17 19:20:08 INFO  : One drive root 'BKP': Waiting for checks to finish
2018/04/17 19:20:08 INFO  : One drive root 'BKP': Waiting for transfers to finish
2018/04/17 19:20:08 ERROR : Attempt 3/3 failed with 1 errors
2018/04/17 19:20:08 INFO  :
Transferred:      0 Bytes (0 Bytes/s)
Errors:                 1
Checks:                 0
Transferred:            0
Elapsed time:        1.6s

2018/04/17 19:20:08 DEBUG : 5 go routines active

**Comment by ACParucker** [comment]
Hi.

I found an option in OneDrive config:
Files on Demand
[x] Save space and download files as you use them.

I don't know where this shit come from.
I never saw that and never checked this.
Some files and folders in my disk was compressed or just links to cloud.

I unchecked this and after OneDrive processing for a while my files are here.
rclone now can read my files.


# Solution
Uncheck this option in OneDrive config

**Files on Demand
**[x]** Save space and download files as you use them.**

**Comment by ncw** [comment]
Glad you found the solution and thanks for sharing it :-)

I'll close this now, but it will be here if anyone else has the same problem.
