### ISSUE TITLE
Rclone fails with a very large directory in Box remote

### ISSUE THREAD

**Issue by lunitin** [ncw/rclone#2261]
#### What is the problem you are having with rclone?
Rclone using crypt suddenly stopped working and now can't interact with remote.

#### What is your rclone version (eg output from `rclone -V`)
Verified on 1.39, 1.40, and  1.40-086-gb8381408

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Linux 64bit

####  Which cloud storage system are you using? (eg Google Drive)
Box

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
Most interaction commands fail, ls, lsd, copy, etc.

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
$ ./rclone -vv lsd box:
2018/04/18 10:23:03 DEBUG : rclone: Version "v1.40-086-gb8381408β" starting with parameters ["./rclone" "-vv" "lsd" "box:"]
2018/04/18 10:23:03 DEBUG : Using config file from "/home/user/.config/rclone/rclone.conf"
2018/04/18 10:23:03 INFO  : box root '': Modify window is 1s
2018/04/18 10:23:04 ERROR : : error listing: couldn't list files: json: cannot unmarshal number 1.0034576983313e+14 into Go struct field Item.size of type int64
2018/04/18 10:23:04 Failed to lsd: couldn't list files: json: cannot unmarshal number 1.0034576983313e+14 into Go struct field Item.size of type int64

$ rclone -vv lsd box_crypt:
2018/04/18 10:26:40 DEBUG : rclone: Version "v1.40" starting with parameters ["rclone" "-vv" "lsd" "box_crypt:"]
2018/04/18 10:26:40 DEBUG : Using config file from "/home/user/.config/rclone/rclone.conf"
2018/04/18 10:26:42 Failed to create file system for "box_crypt:": failed to make remote "box:backup" to wrap: couldn't list files: json: cannot unmarshal number 1.0034576983313e+14 into Go struct field Item.size of type int64

I would rather not post the full output from --dump-bodies, but I expect that this folder highlights the error:

{"type":"folder","id":"11110266858","etag":"0","sequence_id":"0","name":"backup","size":1.0034576985781e+14,"created_at":"2016-08-29T13:14:14-07:00","modified_at":"2018-04-18T10:10:37-07:00","content_created_at":"2016-08-29T13:14:14-07:00","content_modified_at":"2018-04-18T10:10:37-07:00","item_status":"active"}

**Comment by lunitin** [comment]
This patch has resolved the issue. Confirmed that ls, lsd, copy and encrypted versions of those are all working.

**Comment by ncw** [comment]
Thank you for testing :-)  I've merged this to master in

https://beta.rclone.org/v1.40-094-ga0c65dec/ (uploaded in 15-30 mins)

and to [the latest beta](https://beta.rclone.org) and v1.41 when it is released.
