### ISSUE TITLE
Unable to create bucket. Throws region error even though the right region has been selected.

### ISSUE THREAD

**Issue by tejkonganda** [ncw/rclone#2266]
Hi there,

**Running rclone v1.40**

I created an s3 config file using rclone config create and passed in a few parameters as key, value pairs.

This was my rclone config create command -

**_rclone config create remote s3 access_key_id XXX secret_access_key YYY region us-west-1 location_constraint us-west-1_**

In the end my config looks like this -

**[remote]
type = s3
config_automatic = yes //set this to no and tried. Still didn’t work.
access_key_id = XXX
secret_access_key = YYY
region = us-west-1
location_constraint = us-west-1**

I was able to list buckets running **_rclone lsd remote:_**

I deleted all the buckets and want to create a new one. Every time I run **_rclone mkdir remote:bucket_**, I get an error like this -

_2018/04/20 12:53:48 ERROR : Attempt 1/3 failed with 1 errors and: BucketRegionError: incorrect region, the bucket is not in ‘us-west-1’ region
status code: 301, request id: , host id:
2018/04/20 12:53:48 ERROR : Attempt 2/3 failed with 1 errors and: BucketRegionError: incorrect region, the bucket is not in ‘us-west-1’ region
status code: 301, request id: , host id:
2018/04/20 12:53:48 ERROR : Attempt 3/3 failed with 1 errors and: BucketRegionError: incorrect region, the bucket is not in ‘us-west-1’ region
status code: 301, request id: , host id:
2018/04/20 12:53:48 Failed to mkdir: BucketRegionError: incorrect region, the bucket is not in ‘us-west-1’ region
status code: 301, request id: , host id:_

What am I doing wrong? Any help will be greatly appreciated.

Thanks.
Tej

**Comment by ncw** [comment]
> What am I doing wrong? Any help will be greatly appreciated.

I'm guessing you are trying to create a bucket which already exists.

s3 buckets are globally unique, so you need to find a unique name.  You can't use `bucket` as that is already taken!

**Comment by tejkonganda** [comment]
You're right Nick. Thank you so much. I tried using a unique name and it worked.
Can we not use old bucket names even if they have been deleted?

**Comment by tejkonganda** [comment]
Ok. Thanks again.

**Comment by ncw** [comment]
No worries!  I'll close this now.
