### ISSUE TITLE
webdav: make Etag be a content based hash

### ISSUE THREAD

**Issue by beredim** [ncw/rclone#2273]
Can someone explain how the Etag value is calculated when using 'serve webdav' ?

Unfortunately, I have no knowledge in the Go language, and after browsing through the code couldn't find any info.

Is it a standard hash, is it dependent on metadata other than actual file contents (e.g creation date/time), is it impported from another package, etc???

**Comment by ncw** [comment]
From the source:

https://github.com/golang/net/blob/5f9ae10d9af5b1c89ae6904293b14b064d4ada23/webdav/prop.go#L405-L410

```go
func findETag(ctx context.Context, fs FileSystem, ls LockSystem, name string, fi os.FileInfo) (string, error) {
	// The Apache http 2.4 web server by default concatenates the
	// modification time and size of a file. We replicate the heuristic
	// with nanosecond granularity.
	return fmt.Sprintf(`"%x%x"`, fi.ModTime().UnixNano(), fi.Size()), nil
}
```

So it is a hexified version of modification time accurate to the nanosecond and file size.

**Comment by ncw** [comment]
BTW why do you need to know?

**Comment by beredim** [comment]
Thanks for the answer.

I was hoping to use the Etag header in a PUT response to verify that a webdav upload completed without error. 
Of course, that can only be done if Etag was computed using a standard algorithm and based solely on file data (e.g. MD5 of the file like Amazon does in S3)
Unfortunately, I see this is not the case.

Would you consider re-implementing the Etag calculation algorithm to use a standard hash function? After all, rclone already has a check function, so I guess you have tackled this issue for most remotes implementations.

**Comment by ncw** [comment]
Ah I see.  I re-purposed this issue to make rclone use a content hash as the ETag.

I also submitted my patch to the upstream library to enable it, see https://github.com/golang/go/issues/22577 and https://golang.org/cl/109217

**Comment by ncw** [comment]
Go team have merged my patch so this is now unblocked!

I think I'll probably make this a parameter to the `serve webdav` command where you can choose which hash you want to use - sound reasonable?  Say `--etag-hash MD5`.  Or maybe `--etag-hash auto` where rclone just picks the first hash available on the remote...

Also if you are serving local files, calculating the hash will cause lots of disk and CPU so you probably want to be able to enable and disable it.

**Comment by beredim** [comment]
So, maybe `--etag-hash auto` for local files should fall back to the existing metadata approach ?
After all, most filesystems don't offer a content hash anyway.

**Comment by ncw** [comment]
I've had a go at this now.

See `rclone serve webdav --help` for the `--etag-hash` parameter docs.

https://beta.rclone.org/v1.41-093-gc5554b3d-fix-2273-webdav/ (uploaded in 15-30 mins)

**Comment by ncw** [comment]
This is merged in

https://beta.rclone.org/v1.42-139-g502d8b0c/ (uploaded in 15-30 mins)

And will be in [the latest beta](https://beta.rclone.org) from now on and 1.43
