### ISSUE TITLE
--verbose logs everything to stderr

### ISSUE THREAD

**Issue by marcopaganini** [ncw/rclone#228]
When --verbose is activated, all messages are logged to stderr instead of stdout. This makes it difficult to tell "real" error messages apart from regular verbose messages.

A typical scenario I can think of is nightly backups: I want verbose enabled, so I can save the output to a log for later analysis, but I want anything output to stderr to result in an email, since something might have gone wrong during the backup.

I can probably submit a pull request with a fix for this, if deemed desirable.

**Comment by ncw** [comment]
Is this normal practice for unix commands?  Don't debugs & errors normally go to the same place.

Can you think of an example program where they don't?

Potentially this would interact with the `--log-file` option so some care would be needed there.

I see how it would be useful to you though.

Potentially this could be a flag `--log-debug-to-stdout` or something like that?

**Comment by marcopaganini** [comment]
The problem is that there is no praxis for verbose/debug messages, but IMHO, they should go to stdout. rsync, for example, does exactly that:

```shell
$ mkdir /tmp/a /tmp/b
$ touch /tmp/a/aaa /tmp/a/bbb

# Let's make sure there is output
$ rsync -avn /tmp/a /tmp/b
sending incremental file list
a/
a/aaa
a/bbb
a/ccc

sent 146 bytes  received 29 bytes  350.00 bytes/sec
total size is 0  speedup is 0.00 (DRY RUN)

# Now, let's redirect stdout and leave stderr alone
$ rsync -avn /tmp/a /tmp/b >/dev/null
(nothing)

# Let's try a path that doesn't exist
$ rsync -avn /tmp/does_not_exist /tmp/b >/dev/null
rsync: link_stat "/tmp/does_not_exist" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1183) [sender=3.1.0]
```
rdiff-backup has similar (but somewhat more convoluted) behavior.

The beauty of having stderr with only true error messages is that is allows the clean separation of "normal operation" and "failure" output.

**Comment by wouterv** [comment]
+1

**Comment by wouterv** [comment]
I would love to have this option. Now I have to do a lot of grepping and sedding to check the output of rclone if something went wrong.

If only errors would go to stderr and all other output to stdout, I could just check if there was nothing written to stderr.

We use it with out monitoring system to check whether a nightly backup had run ok.

**Comment by wouterv** [comment]
Also, using -q didnt help, because that still outputs stuff like:

```
Errors:                 0
Checks:                 0
Transferred:           64
Elapsed time:        3.8s
```

**Comment by ncw** [comment]
Does someone fancy having a go at this?  It should be relatively straight forward...  in `fs.go` adjusting the `Log`, `Debug` and `ErrorLog` functions.  Might need to make a new go logger which logs to stdout.

I'd probably prefer to have the output of `Log` and `ErrorLog` go to stderr, but the output of `Debug` (which is what you get when you pass the `-v` flag) go to stdout.

`-q` suppresses the `Log` function.

The final stats print needs a bit of working out what flags that should appear with (probably not `-q`!).

> We use it with out monitoring system to check whether a nightly backup had run ok.

rclone should reliably return an exit code for monitoring whether it succeeded or failed.

**Comment by wouterv** [comment]
@ncw oops, I didnt realize I could just use the exit code. Silly me. Thanks!

**Comment by kpabba** [comment]
@ncw 

First of all, let me thank all the developers working on this, it works like a charm.

I'm using ACD and as mentioned in this thread I have the same issue looking at the log files because there's lot of info in it.

What I want to do...

Any errors for a given rclone command plus the last piece of info each command outputs at the end (Summary of files/bits transferred and the duration of time it to took to run that command).

All the errors like below
```
2015/12/28 19:50:52 PhotosLibrary/Photos Library 9.55.20 PM.photoslibrary/Masters/2013/07
/31/20130731-215027/DSC04098.JPG: Received error: HTTP code 409: "409 Conflict", reponse 
body: {"logref":"35dbb896-adc6-11e5-b1bb-7f2eb97d1295","message":"Node with the name 
dsc04098.jpg already exists under parentId dxrkTC5BTaudD71iJBhbtQ conflicting NodeId: 
4vLN4NlkRDSTgd62sfbWFw","code":"NAME_ALREADY_EXISTS","info":
{"nodeId":"4vLN4NlkRDSTgd62sfbWFw"}}
```
Plus the LAST (Only the last one, not at a set time interval) log details of a command like below
```
...................................
Total objects: 162240
Total size: 72.708G (78070079828 bytes)

Transferred:            0 Bytes (   0.00 kByte/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:    10m50.2s
```

I tried using `>logfile`, `2>logfile`, `>logfile 2>&1` and the `exit code` too but couldn't quite do it. Is there an easy way to do it or does it need new development?

**Comment by ncw** [comment]
I've now made debug output go to standard output and important stuff to stderr.

I also fixed all the other things which should have been obeying that (eg the transferred log).

See this beta for testing http://pub.rclone.org/v1.29-1-gbb75d80-53-gf17cb1b%CE%B2/

@kpabba you should find `rclone -v ... >debug-logfile 2>importatnt-errors` does what you want

**Comment by kpabba** [comment]
@nwc,

I tried your suggestion, all looks good, most of the data now goes to debug file but there is still a little more (minutely updates) than required info getting into the ```important-errors``` file too, as seen below. Below is the tail part of the ```important-errors``` file. 

```
.............
.............
2016/06/09 19:39:53 PhotosLibrary/Photos Library 9.55.20 PM.photoslibrary/Masters/2013/07
/31/20130731-215027/DSC04098.JPG: Received error: HTTP code 409: "409 Conflict", reponse 
body: {"logref":"35dbb896-adc6-11e5-b1bb-7f2eb97d1295","message":"Node with the name 
dsc04098.jpg already exists under parentId dxrkTC5BTaudD71iJBhbtQ conflicting NodeId: 
4vLN4NlkRDSTgd62sfbWFw","code":"NAME_ALREADY_EXISTS","info":
{"nodeId":"4vLN4NlkRDSTgd62sfbWFw"}}
.............
**Trimmed all the minutely updates
.............
2016/06/09 20:01:53 
Transferred:     129.769MBytes (16Byte/s)
Errors:                 0
Checks:            131557
Transferred:           77
Elapsed time:   2h16m1.9s
Transferring:
 * ....20 PM.photoslibrary/database/Library.apdb: 13% done. avg:  236.9, cur:  212.3 kByte/s. ETA: 7m22s
 * ....55.20 PM.photoslibrary/database/Person.db: 52% done. avg:  332.9, cur:  193.8 kByte/s. ETA: 4m40s
 * ...20 PM.photoslibrary/database/metaSchema.db: 55% done. avg:  161.8, cur:  171.6 kByte/s. ETA: 43s
 * ...rs/2016/06/08/20160608-021018/IMG_9834.MOV: 19% done. avg:  160.8, cur:  165.0 kByte/s. ETA: 4m3s

2016/06/09 20:02:53 
Transferred:     172.349MBytes (21Byte/s)
Errors:                 0
Checks:            135045
Transferred:           81
Elapsed time:   2h17m1.9s
Transferring:
 * ....20 PM.photoslibrary/database/Library.apdb: 22% done. avg:  199.1, cur:  147.9 kByte/s. ETA: 9m31s
 * ....55.20 PM.photoslibrary/database/Person.db: 62% done. avg:  296.1, cur:  170.8 kByte/s. ETA: 4m12s
 * ...rs/2016/06/08/20160608-021018/IMG_9834.MOV: 48% done. avg:  201.4, cur:  287.0 kByte/s. ETA: 1m29s
 * ...rs/2016/06/08/20160608-021543/IMG_9857.JPG: 100% done. avg:   94.9, cur:  233.5 kByte/s. ETA: 0s

2016/06/09 20:03:14 Amazon cloud drive root 'UseMe/mirror/PhotosLibrary': Waiting for checks to finish
2016/06/09 20:03:14 Amazon cloud drive root 'UseMe/mirror/PhotosLibrary': Waiting for transfers to finish
2016/06/09 20:03:53 
Transferred:     214.853MBytes (26Byte/s)
Errors:                 0
Checks:            167519
Transferred:           96
Elapsed time:   2h18m1.9s
Transferring:
 * ....20 PM.photoslibrary/database/Library.apdb: 36% done. avg:  217.7, cur:  229.2 kByte/s. ETA: 5m1s
 * ....55.20 PM.photoslibrary/database/Person.db: 71% done. avg:  272.6, cur:  201.2 kByte/s. ETA: 2m40s
 * ...Thumbnails/Segments/Thumb64Segment_15.data: 34% done. avg:  144.2, cur:  162.7 kByte/s. ETA: 1m3s
 * ...rs/2016/06/08/20160608-021018/IMG_9834.MOV: 72% done. avg:  198.9, cur:  166.9 kByte/s. ETA: 1m23s

2016/06/09 20:04:53 
Transferred:     257.329MBytes (31Byte/s)
Errors:                 0
Checks:            167519
Transferred:           96
Elapsed time:   2h19m1.9s
Transferring:
 * ....20 PM.photoslibrary/database/Library.apdb: 46% done. avg:  210.0, cur:  181.7 kByte/s. ETA: 5m19s
 * ....55.20 PM.photoslibrary/database/Person.db: 82% done. avg:  261.6, cur:  187.2 kByte/s. ETA: 1m46s
 * ...Thumbnails/Segments/Thumb64Segment_15.data: 94% done. avg:  152.1, cur:  167.9 kByte/s. ETA: 5s
 * ...rs/2016/06/08/20160608-021018/IMG_9834.MOV: 92% done. avg:  192.8, cur:  176.3 kByte/s. ETA: 19s

2016/06/09 20:05:53 
Transferred:     299.057MBytes (36Byte/s)
Errors:                 0
Checks:            167519
Transferred:          102
Elapsed time:   2h20m1.9s
Transferring:
 * ....20 PM.photoslibrary/database/Library.apdb: 64% done. avg:  231.7, cur:  353.3 kByte/s. ETA: 1m49s
 * ....55.20 PM.photoslibrary/database/Person.db: 99% done. avg:  269.8, cur:  341.7 kByte/s. ETA: 2s

2016/06/09 20:06:50 Amazon cloud drive root 'UseMe/mirror/PhotosLibrary': Waiting for deletes to finish (during+after)
2016/06/09 20:06:50 
Transferred:     337.739MBytes (40Byte/s)
Errors:                 0
Checks:            167519
Transferred:          104
Elapsed time:  2h20m59.6s

```

I was hoping to have just the below and nothing else in the ```important-errors``` file.

```
***Any errors like below***
2016/06/09 19:39:53 PhotosLibrary/Photos Library 9.55.20 PM.photoslibrary/Masters/2013/07
/31/20130731-215027/DSC04098.JPG: Received error: HTTP code 409: "409 Conflict", reponse 
body: {"logref":"35dbb896-adc6-11e5-b1bb-7f2eb97d1295","message":"Node with the name 
dsc04098.jpg already exists under parentId dxrkTC5BTaudD71iJBhbtQ conflicting NodeId: 
4vLN4NlkRDSTgd62sfbWFw","code":"NAME_ALREADY_EXISTS","info":
{"nodeId":"4vLN4NlkRDSTgd62sfbWFw"}}

***Plus just the last section of the log for a given command, like below***

2016/06/09 20:06:50 Amazon cloud drive root 'UseMe/mirror/PhotosLibrary': Waiting for deletes to finish (during+after)
2016/06/09 20:06:50 
Transferred:     337.739MBytes (40Byte/s)
Errors:                 0
Checks:            167519
Transferred:          104
Elapsed time:  2h20m59.6s
```

Thanks

**Comment by ncw** [comment]
I view the status updates as important info that rclone hasn't died.  You can change their frequency or disable them with the `--stats` flag

      --stats duration                 Interval to print stats (0 to disable) (default 1m0s)

**Comment by kpabba** [comment]
Thanks, that completes everything what I wanted.
