### ISSUE TITLE
4shared: Ignoring item with bad status ["HTTP/1.1 200"]

### ISSUE THREAD

**Issue by rodarima** [ncw/rclone#2281]
Hi,

I can't list the files in my 4shared drive using WebDav. The error is the following:
```
hop% rclone -vv ls 4shared:
2018/04/29 18:23:08 DEBUG : test.jpg: Ignoring item with bad status ["HTTP/1.1 200"]
```
It seems that they are not using the standard, with `--dump-bodies` I see the ` OK` last part is missing.
```
<D:status>HTTP/1.1 200</D:status>
```
The [RFC4918](https://tools.ietf.org/html/rfc4918#section-14.28) states that the status line, as defined in the [RFC2616](https://tools.ietf.org/html/rfc2616#section-6.1) should contain the `Reason-Phrase`:
```
   The first line of a Response message is the Status-Line, consisting
   of the protocol version followed by a numeric status code and its
   associated textual phrase, with each element separated by SP
   characters. No CR or LF is allowed except in the final CRLF sequence.

       Status-Line = HTTP-Version SP Status-Code SP Reason-Phrase CRLF
```

The status is recognized as an error because the regex is not capturing the line:
```
var parseStatus = regexp.MustCompile(`^HTTP/[0-9.]+\s+(\d+)\s+(.*)$`)
```
Not sure if it breaks something else if we allow the last subgroup to be optional:
```
hop% git diff
diff --git a/backend/webdav/api/types.go b/backend/webdav/api/types.go
index 845cd64a..9a130f30 100644
--- a/backend/webdav/api/types.go
+++ b/backend/webdav/api/types.go
@@ -66,7 +66,7 @@ type Prop struct {
 }
 
 // Parse a status of the form "HTTP/1.1 200 OK",
-var parseStatus = regexp.MustCompile(`^HTTP/[0-9.]+\s+(\d+)\s+(.*)$`)
+var parseStatus = regexp.MustCompile(`^HTTP/[0-9.]+\s+(\d+)(\s+(.*))?$`)
 
 // StatusOK examines the Status and returns an OK flag
 func (p *Prop) StatusOK() bool {
```
Maybe a new special vendor rule would be a better option. With the proposed change I'm able to work with 4shared:
```
hop% ./rclone ls 4shared:    
  2259544 test.jpg
```

**Comment by ncw** [comment]
Excellent debugging - well done.

Ignorng the `OK` seems reasonable since the important part is the `200` and the code doesn't actually use the message.

Do you want to send a pull request with your change?

Perhaps we should change it to this as the second set of capturing brackets isn't used?

```go
// Parse the return code from a status of the form "HTTP/1.1 200 OK",
var parseStatus = regexp.MustCompile(`^HTTP/[0-9.]+\s+(\d+)`)
```

**Comment by rodarima** [comment]
Yes, seems more clear to me. I added a pull request with the change ignoring the Reason-Phrase.

**Comment by ncw** [comment]
Please find a beta for this here:

https://beta.rclone.org/v1.41-008-g50dc5fe9/ (uploaded in 15-30 mins)

this will be in [the latest beta](https://beta.rclone.org) from now on and in v1.42.
