### ISSUE TITLE
--cache-tmp-upload-path folders not being cleaned up

### ISSUE THREAD

**Issue by iamjrock** [ncw/rclone#2282]
**What is the problem you are having with rclone?**
On OSX and Linux, when using --cache-tmp-upload-path folders flag, after copying any nested files and their parent folders, the parent folders are left behind in the --cache-tmp-upload-path folder.

**What is your rclone version (eg output from `rclone -V`)**
Latest rclone 1.4.1 beta (sorry, not at the machine right now so cannot run rclone -V).

**Which OS you are using and how many bits (eg Windows 7, 64 bit)**
OSX High Sierra 64 bit.
However this has been reported as an issue on Linux as well.

**Which cloud storage system are you using? (eg Google Drive)**
G Suite Drive

**The command you were trying to run (eg `rclone copy /tmp remote:tmp`)**
Any rclone mount command that uses the --cache-tmp-upload-path flag.

**A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)**
Sorry, not at the machine right now so cannot run rclone.

**Comment by remusb** [comment]
This should be it. https://beta.rclone.org/v1.41-093-g4e8e5fed/ (other flavours will appear in a few minutes)

After every upload is done, rclone will go up the directory chain and delete it if it's empty.

This won't delete existing folders though so do a manual cleanup before (one last time).

**Comment by iamjrock** [comment]
Thx @remusb - works well.
