### ISSUE TITLE
Typo: Command cryptdecode needs 2 arguments mininum

### ISSUE THREAD

**Issue by NoLooseEnds** [ncw/rclone#2283]
Hi there is an typo in the output of the cryptdecode command.

> Command cryptdecode needs 2 arguments mininum

Minimum has the typo.

**Comment by ncw** [comment]
Want to send a pull request?

**Comment by ncw** [comment]
Here is the line which needs fixing

https://github.com/ncw/rclone/blob/50dc5fe92eaacd55d3fa233c494d313f081d9545/cmd/cmd.go#L357

Thanks

**Comment by NoLooseEnds** [comment]
Yes, I'm still pretty new to this, but I think I managed to do it. :) 

https://github.com/ncw/rclone/pull/2285

**Comment by ncw** [comment]
@NoLooseEnds thank you very much!  This fix will be in [the latest beta](https://beta.rclone.org) from now on and in 1.42.  It probably won't make it to the website until 1.42 either.
