### ISSUE TITLE
Delete equivalent of copyto

### ISSUE THREAD

**Issue by jdwilsonjr** [ncw/rclone#2286]
Here by request from https://forum.rclone.org/t/delete-equivalent-of-copyto/5291/5

#### What is the problem you are having with rclone?
No problems thank you.

In my world I use ls, lsd, and lsjson and THEN apply local logic to act on a specific file or folder.

Suggesting here a delete equivalent of copyto.

Nick favors "rclone deletefile" ... hmmm ... which expands the mind:

rclone deleteFile
rclone deleteFolder ( purge !? )
rclone copyFile ( copyTo !? )
rclone copyFolder

#### What is your rclone version (eg output from `rclone -V`)
1.41

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Winders

####  Which cloud storage system are you using? (eg Google Drive)
Big 3 (Amazon, Azure, Google) BLOBs and SFTP

**Comment by ncw** [comment]
Thank you for making the issue. It should make a nice issue for a new contributor to the project - do you want to do it?

**Comment by jdwilsonjr** [comment]
Nick,Hmmm ... Well I have never done such a thing and zero knowledge of the GO language !?I am a productivity consultant creating automation scripts.Appreciate the nod but deem myself unqualified and so will wait patiently.JD  -------- Original Message --------From: Nick Craig-Wood Date: Tue, May 01, 2018 4:45 am Thank you for making the issue. It should make a nice issue for a new contributor to the project - do you want to do it? —You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by qaskai** [comment]
Hi,
I'll try to solve this issue this week. I've contributed earlier, but didn't touch any of the go code, so I would like to take a shot on what seems to be an easy issue at first to get familiarized with the project.
Cheers!

**Comment by ncw** [comment]
@qaskai great!  Let me know if you need any help.
