### ISSUE TITLE
OSX mount fixes

### ISSUE THREAD

**Issue by iamjrock** [ncw/rclone#2287]
This issue captures various fixes required for OSX.  Full details are available in this thread:

https://forum.rclone.org/t/osx-sierra-high-sierra-can-only-copy-large-files-to-cache-mount-if-nested/5504

Fixes can be summarised as:

1) Remove special characters : and / from the volume name
1.b) Allow volname to be overridden with a flag.

2) Remove noapplexattr from the default config
2.b) Optionally allow it to be added back with a flag.

3) Change the exit code for the xattr calls to ENOSYS to stop OSXFUSE repeatedly calling them.

**Comment by ncw** [comment]
I've made a first attempt at these fixes

https://beta.rclone.org/v1.41-014-gb15b4078-fix-2287-osx-mount/ (uploaded in 15-30 mins)

Can you have a test please and make sure they are working for you!

Note the addition of `--volname`, `--noappledouble` and `--noapplexattr` flags.

**Comment by iamjrock** [comment]
As reported with more detail in the forum [here]([https://forum.rclone.org/t/osx-sierra-high-sierra-can-only-copy-large-files-to-cache-mount-if-nested/5504/43?u=jrock)), this binary seems to fix the issue on High Sierra, thx!

**Comment by ncw** [comment]
@iamjrock thanks for testing!

I've merged this to master now so will be in [the latest beta](https://beta.rclone.org) (in 15-30 mins) and in 1.42.
