### ISSUE TITLE
The amount of disk space incorrent when mount Team Drives (gdrive) in Windows 10

### ISSUE THREAD

**Issue by Rhilip** [ncw/rclone#2288]
#### What is the problem you are having with rclone?

When use rclone and winfsp to mount Google Team Drives in Windows 10, The amount of disk space is not corrent. The amount of disk space should bigger than 1TB or unlimited , but it looks like the space of personal Google Drive, such as 15G.

> The config of rclone shows like:
![Config](https://i.loli.net/2018/05/02/5ae9be5c81731.jpg)

> The result after mount command.  The size of My Drive is 17G, but not 15G. And the it tells `LocalDisk(X:), 16.9G available, 17G total`
![Mount](https://i.loli.net/2018/05/02/5ae9c02ec0e44.jpg)

#### What is your rclone version (eg output from `rclone -V`)

rclone v1.41             
- os/arch: windows/amd64 
- go version: go1.10     

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

Windows 10, 64 bit, 1709

####  Which cloud storage system are you using? (eg Google Drive)

Google Drive

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

`rclone mount GDrive:/ x: --cache-dir F:\Temp --vfs-cache-mode writes`

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

```
λ rclone mount GDrive:/ x: --cache-dir F:\Temp --vfs-cache-mode writes -vv
2018/05/02 21:26:38 DEBUG : rclone: Version "v1.41" starting with parameters ["rclone" "mount" "GDrive:/" "x:" "--cache-dir" "F:\\Temp" "--vfs-cache-mode" "writes" "-vv"]
2018/05/02 21:26:38 DEBUG : Using config file from "C:\\Users\\Rhili\\.config\\rclone\\rclone.conf"
2018/05/02 21:26:38 INFO  : Google drive root '': Modify window is 1ms
2018/05/02 21:26:38 DEBUG : Google drive root '': Mounting on "x:"
2018/05/02 21:26:38 DEBUG : vfs cache root is "F:\\Temp\\vfs\\GDrive"
2018/05/02 21:26:38 DEBUG : Adding path "vfs/forget" to remote control registry
2018/05/02 21:26:38 DEBUG : Google drive root '': Mounting with options: ["-o" "fsname=GDrive:" "-o" "subtype=rclone" "-o" "max_readahead=131072" "-o" "attr_timeout=1" "-o" "atomic_o_trunc" "-o" "uid=-1" "-o" "gid=-1" "--FileSystemName=rclone"]
2018/05/02 21:26:38 DEBUG : Google drive root '': Init:
2018/05/02 21:26:38 DEBUG : Google drive root '': >Init:
2018/05/02 21:26:38 DEBUG : /: Statfs:
2018/05/02 21:26:39 DEBUG : Google drive root '': Checking for changes on remote
2018/05/02 21:26:39 DEBUG : /: >Statfs: stat={Bsize:4096 Frsize:4096 Blocks:4456448 Bfree:4434990 Bavail:4404964 Files:1000000000 Ffree:1000000000 Favail:0 Fsid:0 Flag:0 Namemax:255}, errc=0
2018/05/02 21:26:39 DEBUG : /: Getattr: fh=0xFFFFFFFFFFFFFFFF
2018/05/02 21:26:39 DEBUG : /: >Getattr: errc=0
The service rclone has been started.
2018/05/02 21:26:39 DEBUG : /: Statfs:
2018/05/02 21:26:39 DEBUG : /: >Statfs: stat={Bsize:4096 Frsize:4096 Blocks:4456448 Bfree:4434990 Bavail:4404964 Files:1000000000 Ffree:1000000000 Favail:0 Fsid:0 Flag:0 Namemax:255}, errc=0
2018/05/02 21:26:39 DEBUG : /: Getattr: fh=0xFFFFFFFFFFFFFFFF
2018/05/02 21:26:39 DEBUG : /: >Getattr: errc=0
2018/05/02 21:26:39 DEBUG : /: Getattr: fh=0xFFFFFFFFFFFFFFFF
2018/05/02 21:26:39 DEBUG : /: >Getattr: errc=0
2018/05/02 21:26:39 DEBUG : /: Opendir:
2018/05/02 21:26:39 DEBUG : /: OpenFile: flags=O_RDONLY, perm=-rwxrwxrwx
2018/05/02 21:26:39 DEBUG : /: >OpenFile: fd=/ (r), err=<nil>
2018/05/02 21:26:39 DEBUG : /: >Opendir: errc=0, fh=0x0
2018/05/02 21:26:39 DEBUG : /: Releasedir: fh=0x0
2018/05/02 21:26:39 DEBUG : /: >Releasedir: errc=0
2018/05/02 21:26:39 DEBUG : /: Getattr: fh=0xFFFFFFFFFFFFFFFF
2018/05/02 21:26:39 DEBUG : /: >Getattr: errc=0
2018/05/02 21:26:39 DEBUG : /: Getattr: fh=0xFFFFFFFFFFFFFFFF
2018/05/02 21:26:39 DEBUG : /: >Getattr: errc=0
2018/05/02 21:26:39 DEBUG : /: Opendir:
2018/05/02 21:26:39 DEBUG : /: OpenFile: flags=O_RDONLY, perm=-rwxrwxrwx
2018/05/02 21:26:39 DEBUG : /: >OpenFile: fd=/ (r), err=<nil>
2018/05/02 21:26:39 DEBUG : /: >Opendir: errc=0, fh=0x0
2018/05/02 21:26:39 DEBUG : /: Releasedir: fh=0x0
2018/05/02 21:26:39 DEBUG : /: >Releasedir: errc=0
2018/05/02 21:26:39 DEBUG : /: Getattr: fh=0xFFFFFFFFFFFFFFFF
2018/05/02 21:26:39 DEBUG : /: >Getattr: errc=0
2018/05/02 21:26:39 DEBUG : /: Getattr: fh=0xFFFFFFFFFFFFFFFF
2018/05/02 21:26:39 DEBUG : /: >Getattr: errc=0
2018/05/02 21:26:39 DEBUG : /: Opendir:
2018/05/02 21:26:39 DEBUG : /: OpenFile: flags=O_RDONLY, perm=-rwxrwxrwx
2018/05/02 21:26:39 DEBUG : /: >OpenFile: fd=/ (r), err=<nil>
2018/05/02 21:26:39 DEBUG : /: >Opendir: errc=0, fh=0x0
2018/05/02 21:26:39 DEBUG : /: Releasedir: fh=0x0
2018/05/02 21:26:39 DEBUG : /: >Releasedir: errc=0
2018/05/02 21:26:39 DEBUG : Google drive root '': All changes were processed. Waiting for more.
```

**Comment by ncw** [comment]
Yes this looks like a bug.

I can't find an API for reading the quota or bytes used for a team drive, so I'll just return that these are unknown.

This should fix your problem:

https://beta.rclone.org/v1.41-011-gfe25cb9c/ (uploaded in 15-30 mins)

**Comment by HotMykeul** [comment]
Thanks you for the fix, it work well but it do not work with encrypted google team drive. It shows:
![image](https://user-images.githubusercontent.com/1063311/40859843-6a2bad66-65e3-11e8-9f40-d378f15a5307.png)

Nothing is inside this drive, it is empty.

**Comment by ncw** [comment]
@HotMykeul so are you saying if you mount the `teamdrive:` the space is OK, but if you mount it wrapped in a crypt it isn't?  I'm having trouble working out how that could happen as the crypt should just pass the info straight on.

**Comment by HotMykeul** [comment]
Yes, I had removed all remotes and recreated, now I have a 3,9P drive. I do not know what can have caused this, maybe windows cache or old remotes created with v1.41.
I closed the issue
