### ISSUE TITLE
Verbose mode is too verbose.

### ISSUE THREAD

**Issue by marcopaganini** [ncw/rclone#229]
It appears we only have one level of verbosity. A single --verbose will send all messages to stderr. We need multiple levels (a la rsync) and the first one should produce a user friendly listing of files being synced and a summary at the end. The second level could include all reasons why things happened or didn't happen, such as "timestamp too old", "not copied due to dry-run mode", etc.

**Comment by ncw** [comment]
I just read the man page for rsync again and it has lots of control here - any bits you'd suggest that rclone should incorporate?

**Comment by marcopaganini** [comment]
I'd say the most common use of --verbose would be to see the the files that are being transferred, and possibly their sizes. I've looked (briefly) at the code and have two possible suggestions:

1) Change the command line parsing to allow multiple "-v" and increase the verbose level accordingly. verbose=1 would show just the files being transferred and verbose=2 would show everything that plain "--verbose" shows today (basically, everything.) This method would allow even more verbose levels, and things could be broken down further. So, maybe verbose=1 shows filenames, verbose=2 shows filenames, sizes and transfer rates, verbose=3 shows everything, etc.

2) I noticed that you have a DebugLog function. Maybe introducing a --debug command-line option would be easier? In this case, it would be possible to reduce the scope of --verbose to just display the filenames, and introduce a new --debug command line option what would display everything (as --verbose behaves today).

**Comment by ncw** [comment]
This is a nice idea for an improvement.

**Comment by Darkvater** [comment]
Love this program! I second the verbosity request; a summary of files request is very useful to have logged.

**Comment by Simes** [comment]
I second this too, an output option which is just the list of files transferred would also be useful in automation.

**Comment by RomeSilvanus** [comment]
I also would prefer this function. I often transfer a lot of files from Dropbox to my server and rclone just tells me everything it's doing, which is not really helpful.

I don't need and want to know that something hasn't changed and thus doesn't get copied. I only want to see the deletions and new files, exactly like rsync does it.

**Comment by ncw** [comment]
This is now done in the latest beta!
