### ISSUE TITLE
BUG: failed to authenticate decrypted block - bad password?

### ISSUE THREAD

**Issue by tynor88** [ncw/rclone#2290]
#### What is the problem you are having with rclone?
Cannot download a file from my Google Drive encrypted remote. Out of 700 files, only this one fails with: 

> failed to authenticate decrypted block - bad password?

 I tried multiple times and same error after 74% of the file download progress.
I tried to download the encrypted file (which goes fine) locally and created a local encrypted remote, and the same happens. This is suggested in other bug reports with this error.

#### What is your rclone version (eg output from `rclone -V`)
rclone v1.41-011-gfe25cb9c (latest beta)
Tried with latest stable as well.

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
- os/arch: windows/amd64
- go version: go1.10

####  Which cloud storage system are you using? (eg Google Drive)
Google Drive

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone.exe copy --ignore-existing --verbose --transfers 10 --checkers 4 --contimeout 60s --timeout 300s --retries 1 --low-level-retries 10 --stats 1s GDriveEncrypted:file1.jpg C:\Users\Master\Desktop

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

> 2018/05/03 17:35:00 NOTICE: file1.jpg: Removing partially written file on error: failed to authenticate decrypted block - bad password?
> 2018/05/03 17:35:00 ERROR : file1.jpg: Failed to copy: failed to authenticate decrypted block - bad password?
> 2018/05/03 17:35:00 ERROR : Attempt 1/1 failed with 1 errors and: failed to authenticate decrypted block - bad password?
> 2018/05/03 17:35:00 Failed to copy: failed to authenticate decrypted block - bad password?

**Comment by ncw** [comment]
It looks like that file is corrupted. The signature for a block is failing.

As to why that file is corrupted - there are probably two explanations
  1. the file got corrupted in the upload process
  2. the file got corrupted in storage

Can you run [rclone cryptcheck](https://rclone.org/commands/rclone_cryptcheck/) on that file?

That will give us some idea as to whether the block was corrupted on upload or corrupted in the storage.  If the cryptcheck fails then it option 2 is very likely.  If it passes then it could be option 1 or option 2.

Do you know which version of rclone you uploaded the file with?  In rclone 1.35 there was a bug which could corrupt transfers which were between two remote crypts.

How did you upload the file was it just from local disk?

**Comment by tynor88** [comment]
> the file got corrupted in the upload process
I always upload a folder multiple times, so that it can run the check multiple times. Would this still be the case then? I certainly did it 3 times for this particular folder.

> the file got corrupted in storage
Sounds worrying if that is the case 👎 

> Can you run rclone cryptcheck on that file?
I can not run rclone cryptcheck, as I don't have the original files anymore. Anything else I can try?

> Do you know which version of rclone you uploaded the file with? In rclone 1.35 there was a bug which could corrupt transfers which were between two remote crypts.
It was 1.38 stable.

> How did you upload the file was it just from local disk?
SMB share on windows

**Comment by ncw** [comment]
> I always upload a folder multiple times, so that it can run the check multiple times. Would this still be the case then? I certainly did it 3 times for this particular folder.

Did you run `rclone cryptcheck` or `rclone check`?

> Anything else I can try?

Here is a test rclone with a new flag

      --crypt-pass-corrupted-blocks         Pass through corrupted blocks.

[rclone-v1.41-030-gaa5c5ec5-fix-2290-crypt-no-check.zip](https://github.com/ncw/rclone/files/1980519/rclone-v1.41-030-gaa5c5ec5-fix-2290-crypt-no-check.zip)

This will not produce that error, but it will log it.  Maybe only one block is corrupted in which cause you'll get your entire file back minus a 64k block.  Depending on what type of file it is this may be useful.

You can do the copy from your local crypt to save you downloading it again.

It is possible that it might be corrupted from there to the end (that is what the 1.35 bug did) though.

Can you try that and see what it does?

**Comment by tynor88** [comment]
> Did you run rclone cryptcheck or rclone check?
rclone copy --dry-run --ignore-existing --checksum --verbose --transfers 10 --checkers 4 --contimeout 60s --timeout 300s --retries 3 --low-level-retries 10 \\samba GDriveCrypt:dir

So i guess that is using `rclone check` and not `cryptcheck`. Is this a big difference? Is it possible to run as part of a copy?
> Can you try that and see what it does?

Thanks for providing that version. It seems it's corrupted to the end. I get this log output:
```
... skipped 200 lines ....
2018/05/08 19:06:07 ERROR : passing corrupted block
2018/05/08 19:06:07 ERROR : passing corrupted block
2018/05/08 19:06:07 ERROR : passing corrupted block
2018/05/08 19:06:07 ERROR : passing corrupted block
2018/05/08 19:06:07 ERROR : passing corrupted block
2018/05/08 19:06:07 NOTICE: file1.jpg: Removing partially written file on error: unexpected EOF
```

**Comment by ncw** [comment]
> When uploading i used:
> rclone copy --dry-run --ignore-existing --checksum --verbose --transfers 10 --checkers 4 --contimeout 60s --timeout 300s --retries 3 --low-level-retries 10 \\samba GDriveCrypt:dir
>
> So i guess that is using rclone check and not cryptcheck

During uploads, rclone does the equivalent of `rclone check`.

I like to verify uploads with `rclone check`  or `rclone cryptcheck` if using crypt seperately.

> Is this a big difference?

Running `rclone cryptcheck` would have detected the error but `rclone check` won't.

>  Is it possible to run as part of a copy?

Not currently but it is a very good idea.  I've made an issue #2303 with some ideas on how to implement it.

> Thanks for providing that version. It seems it's corrupted to the end. I get this log output:

:-(

That is an identical symptoms to the problem which was fixed in v1.36.  It could also be something else or the file corrupted on the remote (probably unlikely).

I guess the questions remaining are:
  * can you replicate this problem with 1.41?
  * are you 100% sure you uploaded with 1.38 and not an earlier version?

If you want to recover the file as much as you can, then you can use `rclone cat remote:path > file` and you will get the data that is available.

**Comment by tynor88** [comment]
> Not currently but it is a very good idea. I've made an issue #2303 with some ideas on how to implement it.

Cool, i will follow progress on that feature and eventually use it once it's developed 👍 

> - can you replicate this problem with 1.41?

I havn't tried that, but i will surely let you know if i experience similar behavior. I've transfered TB's of data with rclone, and never experienced this before. So i will have a hard time replicating this :-D

> - are you 100% sure you uploaded with 1.38 and not an earlier version?

Affirmative. I was doing it with RcloneBrowser, and was using a fork which was using the new stat output introduced in 1.38 (this commit: https://github.com/LORDofDOOM/RcloneBrowser/commit/f7382c9203a293b2bab80ea1cdc1fe46fbc7facc)

**Comment by ncw** [comment]
I've done the checks while uploading in #2303 

You'll find that in [the latest beta](https://beta.rclone.org) in about 15 mins!

**Comment by tynor88** [comment]
Great, I will switch over to this version. Thanks for the swift update!
