### ISSUE TITLE
failed to authenticate to Plex: failed to obtain token: map

### ISSUE THREAD

**Issue by camjac251** [ncw/rclone#2293]
I'm trying to get rclone to add itself again as a Plex client to obtain a new token but am unable to. I've tried removing the current plex devices that rclone has made, adding in a blank `plex_token = `, not having one, removing the rclone cache folder, but all seem to fail in fixing the problem. I'm currently using the stable version right now 1.41. Can't try beta at the moment due to the site being down.

Here's the log output I got
`failed to authenticate to Plex: failed to obtain token: map[error:Internal Server Error status:500]`

and my config

```nginx
[gdrive]
type = drive
client_id = ***.apps.googleusercontent.com
client_secret = ***
scope = 
root_folder_id = 
service_account_file = 
token = 

[gcache]
type = cache
remote = gdrive:files
plex_url = http://localhost:not32400
plex_username = myemail@gmail.com
plex_password = pass
chunk_size = 
info_age = 
chunk_total_size = 32G
plex_token = 

[gmedia]
type = crypt
remote = gcache:
filename_encryption = standard
directory_name_encryption = true
password = **
password2 = **
```

**Comment by ncw** [comment]
>  Can't try beta at the moment due to the site being down.

Apologies for that!  It is back now.  It was a hosting provider glitch...

> failed to authenticate to Plex: failed to obtain token: map[error:Internal Server Error status:500]

Hmm. that kind of indicates that there might be something up with plex.  Can you check its logs?

**Comment by camjac251** [comment]
I don't know what I am looking for in the plex logs. I tried looking in the Plex Media Server.log for any fail message but couldn't find any. Then I tried verbose and debug logging, same thing.

**Comment by ncw** [comment]
@camjac251 I think it is probably best if you ask this question on [the rclone forum](https://forum.rclone.org/) as there are people there at lot more knowledgeable than me about Plex (I know basically nothing!).

**Comment by animosity22** [comment]
I'd delete all the plex info and run rclone config and re-enter it back in.

You may either have hit a very unlucky time the Plex API was down or perhaps a typo in the password.

**Comment by camjac251** [comment]
Thank you for your responses. I wasn't aware that the password would be salted or at least different than what you enter on the config. I wasn't using the rclone config command initially, just the raw database file which seemed to never accept the password and I know why now.

For anyone else who has the same issue, it's required to type in the password using the `rclone config` command instead of editing the file itself.

**Comment by remusb** [comment]
Great that you found out what the issue is. Interesting that Plex returns a 500 instead of something like 403.
