### ISSUE TITLE
ONE DRIVE 

### ISSUE THREAD

**Issue by stefanoghazzali** [ncw/rclone#2298]
Hi RClone Support Team - Tried logging on to your forum would not allow me to sign up with Github,FB,Twitter or any of the methods - kept on getting error 'Perhaps you did not authorise the request even though in GitHub the request was authorised so have to post here sorry.

Is there option in the conf file or anywhere that eliminates the need for throttling and also that creates a longer than 1 hour token for OneDrive (business) as working on headless machines dont want to re authorise every time I want to sync a file 

Hi Guys - I am having the problem that my account keeps on getting Throttled Failed to create file system for “onedrive:“: failed to get root: activityLimitReached: throttledRequest: The request has been throttled can anyone help

Kind Regards 
Stefano :)

**Comment by ncw** [comment]
> Hi RClone Support Team - Tried logging on to your forum would not allow me to sign up with Github,FB,Twitter or any of the methods - kept on getting error 'Perhaps you did not authorise the request even though in GitHub the request was authorised so have to post here sorry.

:-(  I haven't heard any other reports of it not working - I'll take a look!

> Is there option in the conf file or anywhere that eliminates the need for throttling and also that creates a longer than 1 hour token for OneDrive (business) as working on headless machines dont want to re authorise every time I want to sync a file

The tokens should be automatically refreshed before the one hour expires.

As for the throttling  - have you been doing lots of transfers?  You can throttle rclone by using the `--tpslimit` flag.

Can you send a log with `-vv` of the failing to create filesystem please?

**Comment by stefanoghazzali** [comment]
Hi @ncw sure thing will send them first thing in the morning (after the cron jobs run)as it is appearing to work now 

Not being doing lots of transfers only about 10 per hour ??? should that make a difference 

More tomorrow morning thanks 
Stefano :)

**Comment by stefanoghazzali** [comment]
I have attached the log of the throttling request and there is nothing in the conf file that relates to throttling - I can attach that also if needed

[Log.txt](https://github.com/ncw/rclone/files/1984110/Log.txt)

Thanks in advance
Stefano :)

**Comment by stefanoghazzali** [comment]
You can close issue now - the refresh token worked in the cron many thanks

**Comment by ncw** [comment]
> I have attached the log of the throttling requests

It looks like all those requests were retried successfully after a while which is good.

> You can close issue now - the refresh token worked in the cron many thanks

Great :-)
