### ISSUE TITLE
Feature request — Use Unix pipe as a source file

### ISSUE THREAD

**Issue by hombit** [ncw/rclone#230]
It would be great if we can use stdin or a pipe as a source path. May be something like this?

```
tar -cz /path/with/million/files | rclone copy remote:path
```

Or at least something like this:

```
mkfifo /tmp/million_files.tar.gz
tar -cz /path/with/million/files > /tmp/million_files.tar.gz
rclone /tmp/million_files.tar.gz remote:path
```

Thank you!

**Comment by ncw** [comment]
I think this a nice idea.

Unfortunately not all the cloud storage systems can stream data - they need to know the size in advance.

I think it would need a different internal interface probably, as the current upload interface needs the size.

**Comment by thiell** [comment]
+1

**Comment by harrytuttle** [comment]
What about the other way? I was searching for something like "rclone cat remote:path | xz -d > file" and came here.

**Comment by ncw** [comment]
@harrytuttle I just implemented an rclone cat command actually!  It will be in v1.33.

I think I need to solve the unknown size problem to make FUSE work properly so this ticket will probably be possible then (piping stuff to rclone for upload).

**Comment by harrytuttle** [comment]
Ah, a commit 18 hour ago, i'd call that serendipity! And that fuse mount command sounds super slick for sure. Thanks!

**Comment by RaymondSchnyder** [comment]
Sorry if i have to bump this, but i dont get the rclone cat Command... It looks like he can only output data from the cloud, but not take output from my tar generated archive...

**Comment by ncw** [comment]
@RaymondSchnyder You'll want #1001 which is the `rcat` command coming in 1.37 with any luck!

**Comment by eborisch** [comment]
I've put together a wrapper tool tonight that can support piping data into and out of an rclone destination. It's certainly alpha-level, so use at your own risk, and let me know how it works for you. I tested piping in a zfs send into and encrypted store, and later retrieving it to a zfs recv.

[https://github.com/eborisch/rpipe](url)

As you can read there:

```
Works by creating temporary files of size --chunksize in --tempdir, and
uploading those. By default runs two 'jobs', such that an upload can be
occuring while the next chunk is being built. As such, tempdir needs to
be able to hold two chunks. They are deleted and checksum-ed along the
way, and verified during retrieval.

Make sure that your destination doesn't exist (purge it first.) This will
likely be added as a default step on a future version.

Examples:
    <some source> | rpipe.py remote:some/empty/loc
    <some source> | rpipe.py --nocheck crypt:an/encrypted/loc
                    ^ As we can't check the md5s of the deposited files on an
                      encrypted store...
    rpipe.py --replay remote:some/empty/loc | <some sink>
    rpipe.py --replay --nocheck crypt:an/ecrypted/loc | <some sink>

```

**Comment by raphink** [comment]
@ncw I don't see the `rcat` command in the master branch. Is it actually already committed?

**Comment by ncw** [comment]
Rcat isn't done yet - soon hopefully!

**Comment by killdaclick** [comment]
Any update on piping input to rclone?

**Comment by ncw** [comment]
Yes, you can do this with `rclone rcat`

so something like


echo "hello" | rclone rcat remote:hello.txt
