### ISSUE TITLE
Redirect URL mismatch

### ISSUE THREAD

**Issue by ikarus23** [ncw/rclone#2306]
#### What is the problem you are having with rclone?
When using the auto config for a Dropbox remote, rclone says my redirect URL should be `http://127.0.0.1:<port>`. But the redirect URL actually used by auto config is `http://localhost:<port>`! This results in an error since 127.0.0.1 != localhost for Dropbox.

#### What is your rclone version (eg output from `rclone -V`)
rclone v1.41
- os/arch: linux/amd64
- go version: go1.10.1

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Arch Linux, 64 bit

####  Which cloud storage system are you using? (eg Google Drive)
Dropbox

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
`rclone config`

**Comment by ncw** [comment]
Both rclone and the dropbox developer app console agree that the redirect URL should be `http://localhost:53682/`

![image](https://user-images.githubusercontent.com/536803/39956883-0138ed4e-55e1-11e8-92b5-2bc4a2e8e04e.png)


What exactly do you mean by this - can you paste some messages maybe?
> When using the auto config for a Dropbox remote, rclone says my redirect URL should be http://127.0.0.1:<port>.

Have you made your own app credentials?

How does the error manifest itself?

**Comment by ikarus23** [comment]
Hi! Well, this is a bit confusing since I just now noticed that the message is only displayed when using a Dropbox app (fill out client_id and client_secret). This is my rclone output
```
[...]

Storage> 7
Dropbox App Client Id - leave blank normally.
client_id> xxxxxxxxxx
Dropbox App Client Secret - leave blank normally.
client_secret> xxxxxxxxxxxx
Remote config
Make sure your Redirect URL is set to "http://127.0.0.1:53682/" in your custom config.
Use auto config?
 * Say Y if not sure
 * Say N if you are working on a remote or headless machine
y) Yes
n) No
y/n> 
```
As you can see, it is telling me to use `http://127.0.0.1:53682/`. If I use it as redirect url it fails. If I use `http://localhost:53682/` it works. Therefore, I think, rclone should suggest using `http://localhost:53682/` instead of `http://127.0.0.1:53682/`

BTW: Thanks for this great tool! ;)

**Comment by ncw** [comment]
I see!

I've fixed this now

https://beta.rclone.org/v1.41-058-ge62d2fd3/ (uploaded in 15-30 mins)

This will be in [the latest beta](https://beta.rclone.org) from now on and 1.42

Thanks for explaining the problem :-)

**Comment by ikarus23** [comment]
Thanks for fixing!
