### ISSUE TITLE
HTTP Code 409 with ACD

### ISSUE THREAD

**Issue by dmitrym0** [ncw/rclone#231]
Hello Nick,

I apologize if I'm missing something obvious, but I attempted to upload my photos to ACD with rclone. At some point the process was interrupted and now I'm seeing a lot of these:

```
2015/11/29 21:56:33 .AppleDouble/ichat icons: Received error: HTTP code 409: "409 Conflict", reponse body: {"logref":"1bb9fb1a-9727-11e5-ac20-3d230a60e35e","message":"Node with the name ichat icons already exists under parentId 9NU9QrZETEaaI1PnwypY0g conflicting NodeId: YJ4F3SS8SyWFSOfBDNeSqw","code":"NAME_ALREADY_EXISTS","info":{"nodeId":"YJ4F3SS8SyWFSOfBDNeSqw"}}
 - retrying 3/10
```

Nothing is being copied right now. Is this expected behavior? I would've thought that once an existing file is encountered if the checksums match the sync process advances. Right now it seems to stall and retry for a while.

**Comment by AlexisEvo** [comment]
Do you have two files/folders there that are named the same, but have different capitalization? Amazon Cloud Drive ignores casing, while ACD tries to upload it as is (which can result in conflicts).

**Comment by ncw** [comment]
@AlexisEvo That could well be it.

@dmitrym0 the other possibility is that it is some problem with eventual consistency that retrying the sync will fix - it certainly isn't expected behaviour.

**Comment by dmitrym0** [comment]
Thanks gentlemen, I will look into the capitalization issue. It's certainly a possibility. Looks like the troublesome files timed out and rclone is off copying the rest of the archive.

**Comment by dmitrym0** [comment]
I'm continuing on my quest to backup all my pics to ACD and I hit this problem again today. I did some investigating and @AlexisEvo is right:

```
-rwxr-xr-x    1 dmitry pictures 20466098 Nov 26  2011 DSC_3862.NEF
-rwxr--r--    1 dmitry pictures 20466098 Nov 26  2011 dsc_3862.nef
```

Not sure how this happened. I'll have to go through my collection and hopefully deduplicate my pictures.

**Comment by ncw** [comment]
Glad you got to the bottom of it and thanks for the update. Nick
