### ISSUE TITLE
--files-from and -L together fails

### ISSUE THREAD

**Issue by johanels** [ncw/rclone#2312]
Hi,

rclone v1.41
- os/arch: linux/amd64
- go version: go1.10

I have a folder with symbolic links, of which some are broken.

I'm creating a files-from to only use the working symbolic links.

when I pass this file 

rclone copy --files-from files-from.txt /home gdrive:/home

it runs correctly, but every file is reported as:

2018/05/15 16:26:41 NOTICE: 123.txt: Can't follow symlink without -L/--copy-links

If I then add the -L

rclone copy -L --files-from files-from.txt /home gdrive:/home

The run fails with

2018/05/15 16:31:58 INFO  : Google drive root 'home': Modify window is 1ms
2018/05/15 16:31:58 ERROR : : error reading source directory: stat /home/random.txt: no such file or directory
2018/05/15 16:31:58 INFO  : Google drive root 'home': Waiting for checks to finish
2018/05/15 16:31:58 INFO  : Google drive root 'home': Waiting for transfers to finish
2018/05/15 16:31:58 ERROR : Attempt 1/3 failed with 1 errors
2018/05/15 16:31:59 ERROR : : error reading source directory: stat /home/random.txt: no such file or directory
2018/05/15 16:31:59 INFO  : Google drive root 'home': Waiting for checks to finish
2018/05/15 16:31:59 INFO  : Google drive root 'home': Waiting for transfers to finish
2018/05/15 16:31:59 ERROR : Attempt 2/3 failed with 1 errors
2018/05/15 16:31:59 ERROR : : error reading source directory: stat /home/random.txt: no such file or directory
2018/05/15 16:31:59 INFO  : Google drive root 'home': Waiting for checks to finish
2018/05/15 16:31:59 INFO  : Google drive root 'home': Waiting for transfers to finish
2018/05/15 16:31:59 ERROR : Attempt 3/3 failed with 1 errors
2018/05/15 16:31:59 INFO  :
Transferred:      0 Bytes (0 Bytes/s)
Errors:                 1
Checks:                 0
Transferred:            0
Elapsed time:        2.7s

The file /home/random.txt is a symbolic link where the source is missing, so broken.

It seems that --from-file is ignored when -L is added into the command line.

Thank you,

**Comment by jakunow** [comment]
Hi,

Using rclone v1.41 as well.

To add on top of that and make it more general, it seems that any of the filtering options (**--exclude**, **--exclude-from**) are behaving the same way when **-L/--copy-links** option is used. Seems that symlinks are evaluated before processing filtering.

This issue has been already mentioned on the [forum](https://forum.rclone.org/t/issues-with-exclude-and-symlinks/2148)

**Comment by ncw** [comment]
Do either of you want to help fix this?  I can walk you through it if you want.

**Comment by TenGumis** [comment]
@ncw 
I can do that. You can give me some hints if you have ;)

**Comment by ncw** [comment]
@TenGumis I think this is the problem code

https://github.com/ncw/rclone/blob/05edb5f501a107e763e437322f269c6879b84de6/backend/local/local.go#L247-L251

We just want to change the error handling here to call `fs.Errorf(...)` to log message, and `fs.CountError(err)` to count an error in the sync, then skip that object out of the sync (`continue` the loop).  Might want to wrap the error in a `fserrors.NoRetryError()`, eg `fs.CountError(fserrors.NoRetryError(err))` so the sync doesn't get retried to retry this error.

Give it a test manually then write a unit test.  Don't run the unit test on windows as it doesn't have symlinks.

**Comment by ncw** [comment]
This has been fixed now - see 9b827be41874f781e7d985becbfdda4684e68503 and look for it in [the latest beta](https://beta.rclone.org)
