### ISSUE TITLE
`--bwlimit` causes upload errors on Amazon Cloud Drive

### ISSUE THREAD

**Issue by AlexisEvo** [ncw/rclone#232]
It looks like --bwlimit is causing issues with uploading files to Amazon Cloud Drive. Occasionally I'll get errors like:

2015/11/30 01:40:45 03 - 비오는 압구정.flac: Failed to copy: HTTP code 504: "504 GATEWAY_TIMEOUT", no response body

At first I thought ACD was just having issues, but then realized that whenever I run it without --bwlimit, the errors disappear entirely. I ran two tests, uploading the same dataset (mix of mp3/flac, 3-30 MB, as well as cue/logs/rare images) to 5,000 uploads. With --bwlimit, 538 errors, without bwlimit, 2 errors. This is consistently reproducible with several days of testing (after realizing this was occurring, I switched to manually toggling bwlimit as my internet needs adjust, the pattern has held up at least a dozen times).

Arch Linux 64 bit
rclone v1.23 (built from AUR package)
~10 mbit upload

**Comment by ncw** [comment]
I recently fixed #170 which may be at the root of this.

I've uploaded a beta release - can you try with this and see if the problem persists?

http://pub.rclone.org/v1.25-8-g8cab32c%CE%B2/

Thanks

Nick

**Comment by AlexisEvo** [comment]
That seems to be the case, running v1.25-8-g8cab32cβ with --bwlimit and 0 errors after 300 uploads. Thanks :)

**Comment by ncw** [comment]
Thanks for checking that out.

The fix will be in the next release.

**Comment by ncw** [comment]
That is now fixed!
