### ISSUE TITLE
[Feature Request] Sleep before retrying

### ISSUE THREAD

**Issue by bjdag1234** [ncw/rclone#2339]
#### What is the problem you are having with rclone?
This is a problem with plexdrive crashing but nonetheless I also wanted a delay for rclone's retries to allow the whatever backend being used to reconnect before retrying the transfer.

A sleep-before-retry <time> parameter would be nice.
e.g:
```sh
$ rclone copy --sleep-before-retry 3s source destination
```

#### What is your rclone version (eg output from `rclone -V`)
rclone v1.41
- os/arch: linux/amd64
- go version: go1.10

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Ubuntu 18.04 / 64-bits

####  Which cloud storage system are you using? (eg Google Drive)
Plexdrive mount backend for a crypted drive to avoid being account banned/file download quota limit
drive = /mnt/plexdrive/crypted-drive

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone copy -vv --stats 30s --retries 15 --low-level-retries 10 --exclude-from exclude.txt drive: /mnt/pool/

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
[excerpt.log](https://github.com/ncw/rclone/files/2075255/excerpt.log)

**Comment by bjdag1234** [comment]
Yes a minimum time between the last error in run n and the start of run n+1, is more like it.

I'm not proficient in go, but can you point me to the code for retries or runs and ill try doing a PR on this.

**Comment by bjdag1234** [comment]
thank you for pointing the code. I'll try studying go and code as I go along.

yes, ```--retries-sleep``` would be appropriate and would make it easier for people to see it on the commands overview/manual.

I'll see what I can do, for now I'm using the following as alternative:

```while ! rclone <blahblah>; do sleep 5; done``` in a bash script to do this. it just checks the return code if its not zero, then retries again. 

but I think this will be better implemented in go code and as a built in feature.

**Comment by ncw** [comment]
Let me know if you get stuck and I'll see if I can help.

**Comment by ncw** [comment]
This is done now - thanks to @bjdag1234 

It can be found in

https://beta.rclone.org/v1.41-091-g334ef280/ (uploaded in 15-30 mins)
