### ISSUE TITLE
Yandex Disk storage backend

### ISSUE THREAD

**Issue by dibu28** [ncw/rclone#234]
Hi.
I've created [Yandex Disk](https://disk.yandex.com/) cloud storage backend for rclone.

Already working:
* rclone opetations: copy, sync, ls, lsl(size, md5, modificationTime)
* uploading/downloading/removing/listing files
* creating directories

I've tested syncronization and copying to and from the cloud a bit

Not working yet:
* lsd operation (will add later)
* empty folders not created/removed yet

Needed:
* no documentation yet
* not everything is covered with unit tests
* maybe api part need some refactoring

I will cleanup code and posting it a bit later.

If you're interested, I think you need to register oAuth app with Yandex Disk https://tech.yandex.com/oauth/  for rClone.

As of today I think Yandex Disk offering somwhere about 10Gb for free.

**Comment by ncw** [comment]
That is fantastic news - thanks!

I suggest you put a branch up somewhere and I'll comment on it.

Note that `empty folders not created/removed yet` is a general problem with rclone - see #100

> not everything is covered with unit tests

Hopefully you've worked out that running `go generate` in `fstest/fstests` will generate an integration test.  This needs a remote set up called something like "TestYandex" (depends on exactly what you called the Fs). If your remote can pass this, and the integrations tests in `fs` - run `go test -v -remote TestYandex:` you are doing very well!

I'll register an oauth for rclone and send you the details.

Look forwards to seeing the code :-)

Nick

**Comment by dibu28** [comment]
Thank you.
I will prepare the code and let you know.

Is it better to put code and api code into a separate project like "github.com/dibu28/rclone_yandex" and just import it in rclone.go or put it all into the folder called 'yandex' inside rclone folder and import ./yandex in rclone.go

**Comment by dibu28** [comment]
Please review the code at: https://github.com/dibu28/rclone/tree/rclone_yandex

Compiled and tested rclone commands (copy, sync, move, ls, lsl, md5) they are working.

Some functions still need to be implemented.
Please tell me if something should be fixed, implemented?
I also have some questions about rclone objects.

**Comment by ncw** [comment]
Thanks for that! I'll send you some feedback tomorrow.

> Is it better to put code and api code into a separate project like "github.com/dibu28/rclone_yandex" and just import it in rclone.go or put it all into the folder called 'yandex' inside rclone folder and import ./yandex in rclone.go

If you think the API stuff is re-usable elsewhere (the `yandex_disk_api`) then you might want separate that on your own github.  The rest of the stuff (and the api if you decide) should go in a yandex folder and the import in rclone.go is the right way to go.

>  also have some questions about rclone objects.

You can ask here, or send me email to nick@craig-wood.com whichever you prefer!

**Comment by dibu28** [comment]
I've used credentials that you've sent to me. There is a little problem with call back url:
Then I try to get a token I get an error: "400 redirect_uri does not match the Callback URL defined for the client"
This is because you've set callback url to: http://127.0.0.1:53682/ in yandex control panel but rclone(oauthutil.go) sends http://localhost:53682/ url in request to oAuth.
You can change callback url in Yandex oAuth control panel to http://localhost:53682/

**Comment by ncw** [comment]
Instead of using `RedirectLocalhostURL` use `RedirectURL` that has the http://127.0.0.1:53682/ address

**Comment by dibu28** [comment]
>If you think the API stuff is re-usable elsewhere (the yandex_disk_api) then you might want separate that on your own github. The rest of the stuff (and the api if you decide) should go in a yandex folder and the import in rclone.go is the right way to go.

I don't think it is re-usable now. And I've only implemented parts needed for rclone. I think would be better for now to leave it in the yandex_disk_api sub folder.

>You can ask here, or send me email to nick@craig-wood.com whichever you prefer!
I've sent you my questions

**Comment by dibu28** [comment]
> Instead of using `RedirectLocalhostURL` use `RedirectURL` that has the http://127.0.0.1:53682/ address

Done. Now using rclone credentials.

**Comment by dibu28** [comment]
Tested. Upload some files using new token.

oAuth page:
![ya_access](https://cloud.githubusercontent.com/assets/446262/11533654/0bb29678-9935-11e5-8c3e-beec3f0ad447.png)

**Comment by dibu28** [comment]
I've fixed all bugs in yandex rclone backend at
https://github.com/dibu28/yandex

It is now passes all unit tests and all tests with "go vet", "golint", "errcheck" and "go fmt".

Please, can you review the code. And if every thing is OK can we merge it to rclone?

**Comment by ncw** [comment]
I will merge this shortly!
