### ISSUE TITLE
sync Chinese naming files or Chinese naming folders error

### ISSUE THREAD

**Issue by lengzer** [ncw/rclone#2341]
sync Chinese naming files or Chinese naming folders error，and lsd is Random code；
server is windows10 http and client is windows10

is it has an parameter to set it？

error code ：
C:\Users\11\Downloads\rclone-v1.41-windows-amd64>rclone.exe sync remote:20171222 e:/test
2018/06/07 00:39:40 ERROR : �½��ļ���: error reading source directory: error listing "\xd0½\xa8\xceļ\xfe\xbc\xd0/": failed to readDir: HTTP Error 500: 500 Internal Server Error
2018/06/07 00:39:40 ERROR : Local file system at \\?\e:\test: not deleting files as there were IO errors
2018/06/07 00:39:40 ERROR : Local file system at \\?\e:\test: not deleting directories as there were IO errors
2018/06/07 00:39:40 ERROR : Attempt 1/3 failed with 1 errors and: not deleting files as there were IO errors
2018/06/07 00:39:40 ERROR : �½��ļ���: error reading source directory: error listing "\xd0½\xa8\xceļ\xfe\xbc\xd0/": failed to readDir: HTTP Error 500: 500 Internal Server Error
2018/06/07 00:39:41 ERROR : Local file system at \\?\e:\test: not deleting files as there were IO errors
2018/06/07 00:39:41 ERROR : Local file system at \\?\e:\test: not deleting directories as there were IO errors
2018/06/07 00:39:41 ERROR : Attempt 2/3 failed with 1 errors and: not deleting files as there were IO errors
2018/06/07 00:39:41 ERROR : �½��ļ���: error reading source directory: error listing "\xd0½\xa8\xceļ\xfe\xbc\xd0/": failed to readDir: HTTP Error 500: 500 Internal Server Error
2018/06/07 00:39:41 ERROR : Local file system at \\?\e:\test: not deleting files as there were IO errors
2018/06/07 00:39:41 ERROR : Local file system at \\?\e:\test: not deleting directories as there were IO errors
2018/06/07 00:39:41 ERROR : Attempt 3/3 failed with 1 errors and: not deleting files as there were IO errors
2018/06/07 00:39:41 Failed to sync: not deleting files as there were IO errors

C:\Users\11\Downloads\rclone-v1.41-windows-amd64>rclone.exe sync remote:20171222 e:/test

**Comment by thri1hous** [comment]
Why did this get closed? Was it ever fixed? Been struggling with Chinese characters in file names for so long
