### ISSUE TITLE
exclude-from doesn't work on Mac

### ISSUE THREAD

**Issue by utdrmac** [ncw/rclone#235]
When multiple --exclude options on the CLI failed to work properly, I attempted to use an exclude file. But that too failed to work. See the attempts below.

```
asura:~ drmac$ more ~/.rclone-exclude.conf
# exclude these files from backups
.DS_Store
.localized
.com.apple.timemachine.supported
asura:~ drmac$ 
asura:~ drmac$ rclone --verbose --checksum --exclude-from=~/.rclone-exclude.conf ~/Public/ acd:asura/Public/
2015/12/01 20:09:21 Failed to load filters: open ~/.rclone-exclude.conf: no such file or directory
asura:~ drmac$
asura:~ drmac$ rclone --verbose --checksum --exclude-from ~/.rclone-exclude.conf ~/Public/ acd:asura/Public/
2015/12/01 20:09:29 Unknown command "/users/drmac/public/"
asura:~ drmac$
asura:~ drmac$ rclone --verbose --checksum --exclude-from .rclone-exclude.conf ~/Public/ acd:asura/Public/
2015/12/01 20:09:37 Unknown command "/users/drmac/public/"
asura:~ drmac$
asura:~ drmac$ rclone --verbose --checksum --exclude-from=.rclone-exclude.conf ~/Public/ acd:asura/Public/
2015/12/01 20:09:41 Unknown command "/users/drmac/public/"
asura:~ drmac$
```

**Comment by ncw** [comment]
Looks like your second and subsequent attempts did load the filter file, but we're just  missing a command, eg copy or ls. 

`~` is interpreted by the shell not rclone and by the look of it osx's shell doesn't like the tilde being inside a string.

**Comment by utdrmac** [comment]
Oh crap. I see the mistake. Sorry for wigging out. PEBKAC. :smile: This worked fine:
   ` asura:~ drmac$ rclone --verbose --checksum --exclude-from ~/.rclone-exclude.conf sync ~/Public/ acd:asura/Public/`

**Comment by ncw** [comment]
No worries - glad it is working now! Nick
