### ISSUE TITLE
rclone mount hangs on macOS Mojave trying to perform a DNS lookup

### ISSUE THREAD

**Issue by as-com** [ncw/rclone#2355]
#### What is the problem you are having with rclone?
Title

Also, any processes that attempt to perform I/O hang while rclone is "running."

#### What is your rclone version (eg output from `rclone -V`)
rclone v1.42-005-g56e1e820β
- os/arch: darwin/amd64
- go version: go1.10.1

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
macOS Mojave Developer Preview 2 10.14 Beta (18A314h)

####  Which cloud storage system are you using? (eg Google Drive)
Google Drive

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
/Volumes/pool/Users/andrew/Downloads/rclone-v1.42-005-g56e1e820β-osx-amd64/rclone mount --vfs-cache-mode writes --no-modtime -vv google: ./rclone-mnt/google

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
2018/06/20 19:41:59 DEBUG : rclone: Version "v1.42-005-g56e1e820β" starting with parameters ["/Volumes/pool/Users/andrew/Downloads/rclone-v1.42-005-g56e1e820β-osx-amd64/rclone" "mount" "--vfs-cache-mode" "writes" "--no-modtime" "-vv" "google:" "./rclone-mnt/google"]
2018/06/20 19:41:59 DEBUG : Using config file from "/Users/andrew/.config/rclone/rclone.conf"
2018/06/20 19:41:59 DEBUG : Google drive root '': Mounting on "./rclone-mnt/google"
2018/06/20 19:41:59 DEBUG : vfs cache root is "/Users/andrew/Library/Caches/rclone/vfs/google"
2018/06/20 19:41:59 DEBUG : Adding path "vfs/forget" to remote control registry
2018/06/20 19:41:59 DEBUG : : Root:
2018/06/20 19:41:59 DEBUG : : >Root: node=/, err=<nil>
2018/06/20 19:41:59 DEBUG : Cleaning the cache
2018/06/20 19:41:59 DEBUG : [redacted]: updateTime: setting atime to 2018-06-20 19:19:26.968302104 -0400 EDT
2018/06/20 19:41:59 DEBUG : [redacted]: updateTime: setting atime to 2018-06-20 19:19:30.645737709 -0400 EDT
2018/06/20 19:41:59 DEBUG : : Statfs:
2018/06/20 19:41:59 DEBUG : /: Attr:
2018/06/20 19:41:59 DEBUG : /: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-xr-x, err=<nil>
2018/06/20 19:41:59 DEBUG : : Statfs:
2018/06/20 19:41:59 DEBUG : : Statfs:
^C2018/06/20 19:42:27 DEBUG : cache cleaner exiting
2018/06/20 19:42:39 DEBUG : pacer: Rate limited, sleeping for 1.20911096s (1 consecutive low level retries)
2018/06/20 19:42:39 DEBUG : pacer: low level retry 1/10 (error Get https://www.googleapis.com/drive/v3/changes/startPageToken?alt=json&supportsTeamDrives=false: dial tcp: lookup www.googleapis.com on 8.8.4.4:53: read udp 192.168.1.127:65219->8.8.4.4:53: i/o timeout)
2018/06/20 19:42:39 DEBUG : pacer: Rate limited, sleeping for 2.368627977s (2 consecutive low level retries)
2018/06/20 19:42:39 DEBUG : pacer: low level retry 1/10 (error Get https://www.googleapis.com/drive/v3/about?alt=json&fields=storageQuota: dial tcp: lookup www.googleapis.com on 8.8.4.4:53: read udp 192.168.1.127:65219->8.8.4.4:53: i/o timeout)
2018/06/20 19:43:19 DEBUG : pacer: Rate limited, sleeping for 4.515950855s (3 consecutive low level retries)
2018/06/20 19:43:19 DEBUG : pacer: low level retry 2/10 (error Get https://www.googleapis.com/drive/v3/about?alt=json&fields=storageQuota: dial tcp: lookup www.googleapis.com on 8.8.4.4:53: read udp 192.168.1.127:57274->8.8.4.4:53: i/o timeout)
2018/06/20 19:43:19 DEBUG : pacer: Rate limited, sleeping for 8.427815009s (4 consecutive low level retries)
2018/06/20 19:43:19 DEBUG : pacer: low level retry 2/10 (error Get https://www.googleapis.com/drive/v3/changes/startPageToken?alt=json&supportsTeamDrives=false: dial tcp: lookup www.googleapis.com on 8.8.4.4:53: read udp 192.168.1.127:57274->8.8.4.4:53: i/o timeout)
2018/06/20 19:43:59 DEBUG : rclone: Version "v1.42-005-g56e1e820β" finishing with parameters ["/Volumes/pool/Users/andrew/Downloads/rclone-v1.42-005-g56e1e820β-osx-amd64/rclone" "mount" "--vfs-cache-mode" "writes" "--no-modtime" "-vv" "google:" "./rclone-mnt/google

**Comment by ncw** [comment]
Can you try [compiling rclone from source](https://rclone.org/install/#install-from-source) and see if that works?

Could you also try this binary: https://1031-17803236-gh.circle-artifacts.com/0/tmp/rclone.dist/rclone-darwin-10.6-amd64

Can you try something really simple like `rclone -vv lsd google:` and see if it the binary you've already tried and the above 2 work or give the same error?

Do you have some sort of firewall? What appears to be happening is that rclone is doing the DNS lookups properly but they are being blocked somewhere

> lookup www.googleapis.com on 8.8.4.4:53: read udp 192.168.1.127:57274->8.8.4.4:53: i/o timeout

If you try the above two binaries then they will use the OS facilities for DNS lookup instead rather than doing them directly.

Thanks for your help.

**Comment by ncw** [comment]
I suspect that doing this issue will solve your problem: https://github.com/ncw/rclone/issues/2309

I don't have a mac so I'll need some testing help!

**Comment by as-com** [comment]
> Can you try something really simple like rclone -vv lsd google: and see if it the binary you've already tried and the above 2 work or give the same error?

Yes, and I can confirm that things work as usual. I believe it has to do with FUSE blocking system I/O while rclone tries to do I/O...

> Do you have some sort of firewall? What appears to be happening is that rclone is doing the DNS lookups properly but they are being blocked somewhere

I do have Little Snitch installed, but rclone was given full permission to access any server.

> Could you also try this binary: 1031-17803236-gh.circle-artifacts.com/0/tmp/rclone.dist/rclone-darwin-10.6-amd64

This binary works as expected. However, #2356 is still not fixed (bavail = 0).

Let me compile from source and I'll let you know how it goes.

**Comment by ncw** [comment]
Ok thanks for testing.  I think #2309 is the way forward here, so building rclone native on the mac which I can do using travis.  It is mostly a bit of fiddling with the build process as the binaries are already being built just not distributed.

**Comment by ncw** [comment]
Could you try this build?

https://beta.rclone.org/branch/v1.42-010-gc018ba01-fix-2309-macos-native-build/rclone-v1.42-010-gc018ba01-fix-2309-macos-native-build%CE%B2-osx-amd64.zip

That is built natively on travis and hopefully should fix the problem.  Assuming that works OK that will be 2309 done.

**Comment by ncw** [comment]
Actually I forgot to set the cgo flag, so can you try this one instead

https://beta.rclone.org/branch/v1.42-011-g073b0deb-fix-2309-macos-native-build/ (uploaded in 15-30 mins)

And if you could run `ldd rclone` and post the results that would be super helpful!

Thanks

**Comment by as-com** [comment]
```
~/Downloads/rclone-v1.42-011-g073b0deb-fix-2309-macos-native-buildβ-osx-amd64
❯ otool -L rclone
rclone:
	/usr/lib/libSystem.B.dylib (compatibility version 0.0.0, current version 0.0.0)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 0.0.0, current version 0.0.0)
	/System/Library/Frameworks/Security.framework/Versions/A/Security (compatibility version 0.0.0, current version 0.0.0)
```

Yep, this build seems to work fine. The mount does not hang.

I think the reason why my non-beta install was working was because I installed it with Homebrew, which probably built the bottle natively.

**Comment by ncw** [comment]
Thank you for testing (and translating `ldd` for me!).

I'll make that the default build from now on - here is the first master build with it.

https://beta.rclone.org/v1.42-013-g6b424213/ (uploaded in 15-30 mins)

This will be in [the latest beta](https://beta.rclone.org) and in v1.43 when it is release.

I'll close this issue now.
