### ISSUE TITLE
G-drive  exportSizeLimitExceeded

### ISSUE THREAD

**Issue by igoreshkas** [ncw/rclone#2357]
Hi, how to solve the problem with exportSizeLimitExceeded
#### What is the problem you are having with rclone?
%File Name:Failed to copy: failed to open source object: open file failed: googleapi: Error 403: This file is too large to be exported., exportSizeLimitExceeded
#### What is your rclone version (eg output from `rclone -V`)
rclone v1.42
- os/arch: linux/amd64
- go version: go1.10.1
#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Debian GNU/Linux 9.4 (stretch)
####  Which cloud storage system are you using? (eg Google Drive)
Google Drive

**Comment by ncw** [comment]
Try this flag

      --drive-alternate-export              Use alternate export URLs for google documents export.

**Comment by ncw** [comment]
...Also see the docs on what it does: https://rclone.org/drive/#drive-alternate-export

**Comment by igoreshkas** [comment]
thx)
