### ISSUE TITLE
Audit API Calls

### ISSUE THREAD

**Issue by alex-phillips** [ncw/rclone#2358]
Is there a way to output every API call that rclone makes against certain providers (i.e., S3)? This would be good to know since they charge per API call and type. I noticed that I don't get this information via the --debug flag.

**Comment by ncw** [comment]
The way to do this is with `--dump headers` which will show the headers of all HTTP transactions.

If you are wanting to optimise s3 transactions, make sure you use `--fast-list` to optimise the listings and  `--size-only` or `--checksum` to stop rclone having to read the metadata with another transaction.

Also see this bit in the docs: https://rclone.org/s3/#update-and-use-server-modtime

**Comment by alex-phillips** [comment]
So it sounds like that rclone needs a separate API all to S3 to get objects modtime? But it looks like the listobjects API call does return the modtime (https://docs.aws.amazon.com/AmazonS3/latest/API/v2-RESTBucketGET.html). Unless you are making a different call in fastlist?

**Comment by alex-phillips** [comment]
Perfect, this is exactly what we needed. Thanks!
