### ISSUE TITLE
rclone.org is currently down

### ISSUE THREAD

**Issue by DaveidWeba** [ncw/rclone#2359]
It's been inaccessible for the last 5 hours at least. Is there a status page available for the community to monitor?

![rclone_down](https://user-images.githubusercontent.com/34089153/41836903-10ba8e9c-782a-11e8-98a0-925b6ed92597.png)

**Comment by ncw** [comment]
Thanks for that.  I managed to miss the uptimerobot notification :-(

It is now up!
