### ISSUE TITLE
rclone appends path to webdav URL, which breaks a GET URL with variables

### ISSUE THREAD

**Issue by onnozweers** [ncw/rclone#2360]
Hi,

I think I've found a bug. I have an URL with a Macaroon for authentication, like this:

    https://server/?authz=token

but that fails with an "unauthorized" error, where curl just gets the file or directory (so the token is fine). In the server log, I saw this URL:

    https://server/?authz=token//

So I tried this URL to "disconnect" the // from the token:

    https://server/?authz=token&

And indeed, that works again! But then I try to upload a file:

    https://server/?authz=token&/test-webdav

This breaks, the server does not understand it. It appears there is not much else I can do with such GET URLs. May I suggest paths are inserted before variables of a GET URL and not appended at the end?

Thanks!
Onno

**Comment by ncw** [comment]
Hmm, yes, that does indeed look like a bug.

Can you supply the macaroon as a header instead of a URL parameter?  That would be easier to implement?

Which WebDAV server is this?

**Comment by onnozweers** [comment]
Yes, providing the macaroon in a header is possible. So https://github.com/ncw/rclone/issues/59 would provide a workaround, in this case.

**Comment by onnozweers** [comment]
The WebDAV server is dCache, in which we currently have 43 petabyte of scientific data (from CERN's LHC, Lofar radio astronomy, Project MinE ALS/MND research, Virgo gravitational wave detector, Tropomi atmosphere measuring satellite and many more). It would be awesome if we could disclose some of this data with rclone this way!

**Comment by ncw** [comment]
Thanks for the info - very helpful.

I've implemented a bearer token input for the webdav client.  It will ask for it in the initial setup - leave username and password blank.

Let me know if that works!

https://beta.rclone.org/v1.42-010-gb01921d0-fix-2360-macaroon/ (uploaded in 15-30 mins)

**Comment by onnozweers** [comment]
Thanks for your fast and very elegant solution (I like that the bearer token is defined in the remote!)

It seems to work in a quick download test:

    onno$ rclone-v1.42-010-gb01921d0-fix-2360-macaroonβ-linux-amd64/rclone --verbose=10 copy macaroon-1:/users/onno/diskandtape/test1 test-macaroon1
    2018/06/25 18:07:36 DEBUG : rclone: Version "v1.42-010-gb01921d0-fix-2360-macaroonβ" starting with parameters ["rclone-v1.42-010-gb01921d0-fix-2360-macaroonβ-linux-amd64/rclone" "--verbose=10" "copy" "macaroon-1:/users/onno/diskandtape/test1" "test-macaroon1"]
    2018/06/25 18:07:36 DEBUG : Using config file from "/home/onno/.config/rclone/rclone.conf"
    2018/06/25 18:07:36 DEBUG : test1: Couldn't find file - need to transfer
    2018/06/25 18:07:36 INFO  : test1: Copied (new)
    2018/06/25 18:07:36 INFO  : 
    Transferred:   1.059 kBytes (5.631 kBytes/s)
    Errors:                 0
    Checks:                 0
    Transferred:            1
    Elapsed time:       100ms

    2018/06/25 18:07:36 DEBUG : 5 go routines active
    2018/06/25 18:07:36 DEBUG : rclone: Version "v1.42-010-gb01921d0-fix-2360-macaroonβ" finishing with parameters ["rclone-v1.42-010-gb01921d0-fix-2360-macaroonβ-linux-amd64/rclone" "--verbose=10" "copy" "macaroon-1:/users/onno/diskandtape/test1" "test-macaroon1"]

The result:

    onno$ ls -l test-macaroon1/
    total 4
    -rw-rw-r--. 1 onno onno 1084 Jun 13 10:53 test1

I don't understand the difference in bytes but the contents of the file seem OK.

I'll try some more tests later today.

**Comment by ncw** [comment]
I don't understand the difference in bytes but the contents of the file seem OK.

Did you mean this?

    1.059*1024 = 1084.416

Thanks for testing.  I'll write some docs and merge it! Let me know if you find any problems.

**Comment by ncw** [comment]
I've merged this to master here:

https://beta.rclone.org/v1.42-012-gfa051ff9/ (uploaded in 15-30 mins)

Let me know if it all works - thanks

**Comment by onnozweers** [comment]
Uploading with rclone-v1.42-012-gfa051ff9β using a macaroon works fine!

```
onno$ rclone-v1.42-012-gfa051ff9β-linux-amd64/rclone --verbose=10 copy test-webdav macaroon-1:
2018/06/25 23:26:36 DEBUG : rclone: Version "v1.42-012-gfa051ff9β" starting with parameters ["rclone-v1.42-012-gfa051ff9β-linux-amd64/rclone" "--verbose=10" "copy" "test-webdav" "macaroon-1:"]
2018/06/25 23:26:36 DEBUG : Using config file from "/home/onno/.config/rclone/rclone.conf"
2018/06/25 23:26:36 DEBUG : test-webdav: Couldn't find file - need to transfer
2018/06/25 23:26:37 INFO  : test-webdav: Copied (new)
2018/06/25 23:26:37 INFO  : 
Transferred:     12 Bytes (25 Bytes/s)
Errors:                 0
Checks:                 0
Transferred:            1
Elapsed time:       400ms

2018/06/25 23:26:37 DEBUG : 3 go routines active
2018/06/25 23:26:37 DEBUG : rclone: Version "v1.42-012-gfa051ff9β" finishing with parameters ["rclone-v1.42-012-gfa051ff9β-linux-amd64/rclone" "--verbose=10" "copy" "test-webdav" "macaroon-1:"]
```

We'll continue testing the coming weeks and if there are bugs we'll let you know.

**Comment by onnozweers** [comment]
> 1.059*1024 = 1084.416

Ah, of course... Had overlooked the `k`.

**Comment by ncw** [comment]
Great - thanks for testing :-)

**Comment by onnozweers** [comment]
I did some more tests, it seems to work perfectly. I've created a script that can generate an rclone config with a token. https://github.com/onnozweers/dcache-scripts/blob/master/get-share-link

**Comment by ncw** [comment]
Excellent :-)  I like your script.  Do you want to send a pull request [for the docs](https://github.com/ncw/rclone/blob/master/docs/content/webdav.md#dcache) and add  sentence or two about your script and a link?

Also if you correct anything I already wrote about dCache that would be great too!
