### ISSUE TITLE
Port new Azure Blob Storage SDK

### ISSUE THREAD

**Issue by sandeepkru** [ncw/rclone#2362]
Currently `rclone` uses `https://github.com/Azure/azure-sdk-for-go/tree/master/storage` azure storage SDK, as per official documentation this is in **maintenance only mode and will be deprecated** in near future. 

There is new blob storage SDK published by Microsoft - [Azure Blob Storage SDK](https://github.com/Azure/azure-storage-blob-go ) which will continue to be main stream on all changes related to Blob. This latest SDK has new improvements and supports  "Set Tier" functionality on blobs which is prerequisite addressing [Issue #2091 ](https://github.com/ncw/rclone/issues/2091)

`rclone` needs to port from deprecated SDK to new one.

**Comment by ncw** [comment]
Thanks for looking at this @sandeepkru - most appreciated.

Let me know if you need any help.

**Comment by sandeepkru** [comment]
@ncw  - I'm almost ready to send PR, some of the integration tests are failing due to comparing values in correct time zones. I'm seeing same behavior even in master branch as well.

Example:
Modification time difference too big |1ns| > 1ns (2001-02-02 20:05:06.5 -0800 PST vs 2001-02-03 04:05:06.499999999 +0000 UTC) (precision 1ns)

Is there any test config I need to tweak to handle this correctly? I didn't spend time looking into this further.

**Comment by sandeepkru** [comment]
I see that it is not time zones, it is just time precession

**Comment by ncw** [comment]
> Modification time difference too big |1ns| > 1ns (2001-02-02 20:05:06.5 -0800 PST vs 2001-02-03 04:05:06.499999999 +0000 UTC) (precision 1ns)

So that looks like that the time difference  `|1ns| ` is equal to the precision of `1ns` and hence out of bounds.  I don't know why that should be!

I run both sets of tests every day - you can see the results here: https://pub.rclone.org/integration-tests/ - I haven't seen any azureblob failures.

I wonder if this is to do with the file system of your local machine?  What kind of machine are you running and what sort of filesystem is /tmp ? What do you see if you do `ls -l --full-time` on files in /tmp - are they accurate to 1ns?

This could be related to this commit 4009fb67c80086ae220cbccc6a6ca1d7aa2af621 which has 2 folloup fixes 1c7558195929f3df9f23ece38d6229d0307dc510 and 
 ba43acb6aa703ed64b4c9671b36d31354bbd9f5b

**Comment by sandeepkru** [comment]
> I wonder if this is to do with the file system of your local machine? What kind of machine are you running and what sort of filesystem is /tmp ? What do you see if you do ls -l --full-time on files in /tmp - are they accurate to 1ns?

I'm using MacBook, below is OS specification and filesystem is APFS. I couldn't do ls with `--full-time` since I'm not using GNU ls
      System Version: macOS 10.13.3 (17D102)
      Kernel Version: Darwin 17.4.0

I believe this issue is same as [someone reported here](https://github.com/golang/go/issues/22037)
See below values on my machine
```console
○ → go version
go version go1.9.2 darwin/amd64
```
```console
fmt.Println("Time in Nano Seconds - ", time.Now().UnixNano())
Time in Nano Seconds -  1530535800524587000 -> doesn't fill at nano seconds
fmt.Println("time.Now() - ", time.Now())
2018-07-02 05:50:00.524596 -0700 PDT m=+0.000443813
```

However before sending pull request, I changed temporarily test config locally to `us` precision and I was able to continue with that.

**Comment by ncw** [comment]
Interesting analysis on the times and thanks for the link to the go bug.

Can you tell me exactly which tests fail?

I'd like to know what `fs.GetModifyWindow()` returns on your machine (you can run this https://play.golang.org/p/Xw2YbBioT3o ).  It sounds like it should be returning 1uS at which the tests would work but it is actually returning 1nS.  Or possibly a call to GetModifyWindow is missing.

**Comment by sandeepkru** [comment]
>  Can you tell me exactly which tests fail?

Almost all tests fail since most of them comparing times.

Yup, it is 1uS

``` console
Modify window is 1µs
```

**Comment by ncw** [comment]
Since `GetModifyWindow()` is producing the correct result, then it means that rclone isn't calling it in the right place.

I managed to replicate your problems with

```go
diff --git a/backend/local/local.go b/backend/local/local.go
index aaff49a1..b020bc28 100644
--- a/backend/local/local.go
+++ b/backend/local/local.go
@@ -619,7 +619,7 @@ func (o *Object) Size() int64 {
 
 // ModTime returns the modification time of the object
 func (o *Object) ModTime() time.Time {
-       return o.modTime
+       return o.modTime.Truncate(time.Microsecond)
 }
 
 // SetModTime sets the modification time of the local fs object
```

Which should make them easy to fix up.

**Comment by ncw** [comment]
I made a new issue for this #2381

It shouldn't be too difficult to fix!

**Comment by sandeepkru** [comment]
> Which should make them easy to fix up.

Thanks for the repro, I'll fix this.

**Comment by ncw** [comment]
Thank you for your work on this @sandeepkru :-)

I'll leave this issue open until we've fixed the last remaining integration test once https://github.com/Azure/azure-storage-blob-go/issues/52 has been fixed.

**Comment by sandeepkru** [comment]
Closing this since we have fixed integration tests.
