### ISSUE TITLE
rclone reporting incorrect directory listings in Mega

### ISSUE THREAD

**Issue by beergeekdotcom** [ncw/rclone#2366]
#### What is the problem you are having with rclone?

Rclone is not properly interpreting changes to an account from Mega.nz. Mega has implemented some sort of a cache system that returns old results and changes to those results.

This issue was reported to Mega and this was the response from Mathias Ortmann at Mega:

> Okay, we have solved the mystery:
> 
> rclone and megatools are not using our SDK. Therefore, they are unable to
> receive updates to the account state.
> 
> What we do on our side to reduce loading times for properly implemented
> clients is to take snapshots of accounts that have exceeded a certain
> threshold size (such as yours). When you log in, you get that snapshot
> (which is very fast) plus the delta updates that have happened since
> the snapshot was taken (which is also very fast). Your client is then
> supposed to apply those delta updates to get a correct view of the
> remote state. If the client fails to do so, the view remains outdated.
> 
> We could now simply send rclone a freshly generated copy of your account
> state every time it asks. However, if the account is large, this will
> take a while and, worse, cause infrastructure load at our end that we
> are keen to avoid.
> 
> Furthermore, we don’t really see rclone as particularly useful if it
> doesn’t get updates in real time, but has to poll for it?
> 
> We strongly urge the authors of rclone to do things properly. Our SDK
> hides all the complexity in relation to delta update processing and
> gives the app developer convenient notifications of actual state
> notifications at a fairly high level of abstraction.

#### What is your rclone version (eg output from `rclone -V`)
rclone v1.42
- os/arch: darwin/amd64
- go version: go1.10.3

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Mac OSX 10.13.4
and Debian 9

####  Which cloud storage system are you using? (eg Google Drive)
Mega

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone ls mega:/TV

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

2018/06/29 09:12:23 DEBUG : rclone: Version "v1.42" starting with parameters ["rclone" "-vv" "ls" "mega:/TV"]
2018/06/29 09:12:23 DEBUG : Using config file from "/Users/jscott/.config/rclone/rclone.conf"
972934170 Romesh - Talking To Comedians/Romesh - Talking To Comedians, In Caffs About Growing Up (18 August 2017).mp4
790770168 Romesh - Talking To Comedians/Romesh - Talking To Comedians, In Pubs About Comedy (27 March 2017).mp4
993336246 Romesh - Talking To Comedians/Romesh - Talking To Comedians, In a Pie and Mash Shop (24 June 2018).mp4
2018/06/29 09:12:27 DEBUG : 7 go routines active
2018/06/29 09:12:27 DEBUG : rclone: Version "v1.42" finishing with parameters ["rclone" "-vv" "ls" "mega:/TV"]

Note that the results do not match what is currently in that directory according to their web interface at mega.nz -- that directory currently contains a few hundred files.  But the above state was correct at one point in time.

**Comment by ndom91** [comment]
Any chance of a linux version? :)

**Comment by ncw** [comment]
@ndom91 there should be one now - the builds upload at different rates!

**Comment by ndom91** [comment]
Perfect. The linux build seems to work great!

Output:
```
$(ndo@ndo4)-(~/Downloads/rclone-v1.42-016-ga0e348b2-fix-2366-megaβ-linux-amd64)-(01:50  Sa Jun 30)->
$(jobs:0)-(5 files, 22Mb)-> rclone ls mega:ndoX_backup/daily
3715089171 backup-configs-ndo2-Jun-25-18.tar.gz
3715520207 backup-configs-ndo2-Jun-26-18.tar.gz
3715803705 backup-configs-ndo2-Jun-27-18.tar.gz
3716337253 backup-configs-ndo2-Jun-28-18.tar.gz
3659346076 backup-configs-ndo2-Jun-29-18.tar.gz
3659124509 backup-configs-ndo2-Jun-30-18.tar.gz
        8 potato.txt
```

**Comment by ncw** [comment]
Great! Let me know if you see any problems with it.

**Comment by ndom91** [comment]
I've done a bit of testing with it including running my backup scripts, etc. as well as playing content through plex through the mounted mega remote and everything seems to be in working order.

Thanks again for the quick work on this and thanks to @beergeekdotcom for communicating with mega and getting this problem identified so quickly!

**Comment by ncw** [comment]
Thank you for testing.

I've merged that to master now so it will be in

https://beta.rclone.org/v1.42-018-g794e55de/ (uploaded in 15-30 mins) and [the latest beta](https://beta.rclone.org) from now on.
