### ISSUE TITLE
How to use "rclone dedupe" command in Mega?

### ISSUE THREAD

**Issue by kchiayen** [ncw/rclone#2367]
#### What is the problem you are having with rclone?
I try to use "rclone dedupe" command remove duplicate files in Mega 
but rclone don't show anything or message 
How to use "rclone dedupe" command in Mega?

#### What is your rclone version (eg output from `rclone -V`)
1.42

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
windows 64 bit

####  Which cloud storage system are you using? (eg Google Drive)
Mega

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone dedupe --config mega.txt mega:gitBackup -vv

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
2018/06/30 11:45:48 DEBUG : rclone: Version "v1.42" starting with parameters ["r
clone" "dedupe" "--config" "mega.txt" "mega:gitBackup" "-vv"]
2018/06/30 11:45:48 DEBUG : Using config file from "D:\\rclone-v1.42-windows-amd
64\\mega.txt"
2018/06/30 11:45:50 INFO  : mega root 'gitBackup': Looking for duplicates using
interactive mode.
2018/06/30 11:45:50 DEBUG : 5 go routines active
2018/06/30 11:45:50 DEBUG : rclone: Version "v1.42" finishing with parameters ["
rclone" "dedupe" "--config" "mega.txt" "mega:gitBackup" "-vv"]

**Comment by ncw** [comment]
It should work like this

```
$ rclone dedupe mega:
2018/06/30 12:40:58 NOTICE: newname.txt: Found 2 duplicates - deleting identical copies
newname.txt: 2 duplicates remain
  1:           31 bytes, 2018-04-23 15:57:44.000000000, None          hash type not supported
  2:           31 bytes, 2018-06-30 10:43:21.000000000, None          hash type not supported
s) Skip and do nothing
k) Keep just one (choose which in next step)
r) Rename all to be different (by changing file.jpg to file-1.jpg)
s/k/r> k
Enter the number of the file to keep> 1
2018/06/30 12:41:12 NOTICE: newname.txt: Deleted 1 extra copies
```

Note that dedupe is only for removing identically named files.

**Comment by ncw** [comment]
You can't do that with `rclone dedupe`.

mega doesn't support content hashes so it will have to be a size comparison.

You will have to do some scripting I think.  Take a look at [rclone lsf](https://rclone.org/commands/rclone_lsf/) that is good for input for a script.

**Comment by kchiayen** [comment]
Hi ncw:
thank you advice,
I try to combine "rclone lsf" with other command, it is work
very thank you
