### ISSUE TITLE
sync on hubic will reupload fragmented files

### ISSUE THREAD

**Issue by arsiesys** [ncw/rclone#237]
Hello,

Thanks for rclone ;).

It seems that when I am trying to sync a directory composed by some fragmented files (upload by rclone prevously), it will reupload the fragmented files each time. Probably because rclone detect the index file size and not the full file size.

Regards

**Comment by ncw** [comment]
By fragmented files, you mean files bigger than 5GB I take it? Or were these uploaded by a different tool?

I shouldn't do that!

Can you report
  * rclone version
  * OS version
  * command line you are using
  * output of that command with `-v` flag (edit the output to remove anything confidential)

Thanks

Nick

**Comment by arsiesys** [comment]
Yes, i mean files bigger than 5GB (11GB in this case).

rclone version : 1.25
os : ubuntu server 14.04
command used :  rclone sync /var/lib/lxd/containers/XXXXX/ hubic:containername -v --dry-run

First time, it was upload by swift CLI, so, as is there only one file concerned, I removed it (including fragment file associated) and start a "rclone copy", the file was re-uploaded (and fragmented in 3 fragments on "containername_segments"). After that, if i retry a rclone sync, it will re-upload this file each time.

Command output : 
2015/12/02 15:05:35 Hubic: Got swift credentials (expiry 2015-12-03 11:41:34 +0100 CET in 20h35m58.991934932s)
2015/12/02 15:05:35 Hubic Swift container containername: Modify window is 1ns
2015/12/02 15:05:35 Hubic Swift container scontainername: Building file list
2015/12/02 15:05:35 Hubic Swift container containername: Waiting for checks to finish
... skiped files logs because same size/time ...
2015/12/02 15:05:41 A_FILE.ext: Sizes differ
2015/12/02 15:05:41 A_FILE.ext: Not copying as --dry-run
2015/12/02 15:05:46 Hubic Swift container containername: Waiting for transfers to finish
2015/12/02 15:05:46 Waiting for deletions to finish

Transferred:            0 Bytes (   0.00 kByte/s)
Errors:                 0
Checks:               791
Transferred:            1
Elapsed time:       11.3s

2015/12/02 15:05:46 Go routines at exit 14

**Comment by ncw** [comment]
Thanks for that.

Hmmm `A_FILE.ext: Sizes differ` is odd...

What does `rclone ls` say the size of  `A_FILE.ext` is and what is its size when you do `ls -l` on it?

**Comment by arsiesys** [comment]
On rclone ls, it say "0".
ls -l : 10738383407

Exactly the same thing with swift cli, fragmented files are listed with a size of "0". If I check the segment container, fragments are present with the correct size (2*5GB and a small file) and I can download the file without issue.

**Comment by ncw** [comment]
Yes that looks like a bug (or return of a fixed bug!)

I'll fix it in a bit and sent a beta for you to try

**Comment by ncw** [comment]
I've fixed that and uploaded a beta for you to try - let me know how it goes!

http://pub.rclone.org/v1.25-10-g646143d%CE%B2/

Thanks

Nick

**Comment by arsiesys** [comment]
Hello ncw !

Just tested and work perfectly !
rclone sync = ok
rclone ls = ok, it show the full size of the concerned file

Thanks !

**Comment by ncw** [comment]
Great!  It will be in the next release.
