### ISSUE TITLE
delete-empty-src-dirs not deleting folders.

### ISSUE THREAD

**Issue by KurtzPT** [ncw/rclone#2372]
Command used: rclone move -vv -L --delete-empty-src-dirs --ignore-existing --fast-list --stats=30s --drive-chunk-size=256M --buffer-size=256M "/home/user1/data/upload/" gdrive:

After uploading everything, every folder inside /home/user1/data/upload/ will still be there.

The log doesn't show anything interesting at the end:

> 2018/07/02 11:34:56 DEBUG : 5 go routines active
> 2018/07/02 11:34:56 DEBUG : rclone: Version "v1.42" finishing with parameters ["rclone" "move" "-vv" "-L" "--delete-empty-src-dirs" "--ignore-existing" "--fast-list" "--stats=30s" "--drive-chunk-size=256M" "--buffer-size=256M" "/home/user1/data/upload/" "gdrive:"

**Comment by ncw** [comment]
I can confirm this...

```
$ mkdir -p src/dir
$ echo hello > src/dir/file.txt
$ tree src
src
└── dir
    └── file.txt

1 directory, 1 file
$ rclone move -vv --delete-empty-src-dirs --disable DirMove src dst
2018/07/02 14:04:14 DEBUG : rclone: Version "v1.42-016-g97beff53" starting with parameters ["rclone" "move" "-vv" "--delete-empty-src-dirs" "--disable" "DirMove" "src" "dst"]
2018/07/02 14:04:14 DEBUG : Using config file from "/home/ncw/.rclone.conf"
2018/07/02 14:04:14 DEBUG : Reset feature "DirMove"
2018/07/02 14:04:14 DEBUG : Reset feature "DirMove"
2018/07/02 14:04:14 INFO  : Local file system at /tmp/dst: Waiting for checks to finish
2018/07/02 14:04:14 INFO  : Local file system at /tmp/dst: Waiting for transfers to finish
2018/07/02 14:04:14 INFO  : dir/file.txt: Moved (server side)
2018/07/02 14:04:14 INFO  : 
Transferred:      0 Bytes (0 Bytes/s)
Errors:                 0
Checks:                 0
Transferred:            1
Elapsed time:          0s

2018/07/02 14:04:14 DEBUG : 2 go routines active
2018/07/02 14:04:14 DEBUG : rclone: Version "v1.42-016-g97beff53" finishing with parameters ["rclone" "move" "-vv" "--delete-empty-src-dirs" "--disable" "DirMove" "src" "dst"]
$ 
$ tree src
src
└── dir

1 directory, 0 files
$ tree dst
dst
└── dir
    └── file.txt

1 directory, 1 file
```

It does work with 1.41 - a bit of bisecting reveals this is the problem

```
commit 737aed8412c28641fcd82755b74346b00e9e1cd9
Author: ishuah <kariuki@ishuah.com>
Date:   Mon May 14 20:16:56 2018 +0300

    Ensure items in srcEmptyDirs are actually empty

:040000 040000 e86f9cf64558491328cef3833970e26ac9fed51d 8da1b952c1eb90a2064b46714dcc38faaab6333d M	fs
```

Any ideas why 737aed8412c28641fcd82755b74346b00e9e1cd9 broke this @ishuah ?

It would be a good software engineering to first make a failing test then fix it

**Comment by ishuah** [comment]
@KurtzPT I see where it's breaking.

I added a line [to remove a dir from the `srcEmptyDirs` map if the dir has/had a file](https://github.com/ncw/rclone/commit/737aed8412c28641fcd82755b74346b00e9e1cd9#diff-d8b244ed617bc56f995832314f1fef10R741). So when processing a `move`, all dirs which had files before the move won't be in the `srcEmptyDirs` map, meaning they won't be deleted.

Testing with an empty second src dir proves this:
```
$ mkdir -p src/dir
$ mkdir src/dir2
$ echo hello > src/dir/hello.txt
$ tree src
src
├── dir
│   └── file.txt
└── dir2

2 directories, 1 file
$ rclone move -vv --delete-empty-src-dirs --disable DirMove src dst
2018/07/11 15:29:15 DEBUG : rclone: Version "v1.42" starting with parameters ["rclone" "move" "-vv" "--delete-empty-src-dirs" "--disable" "DirMove" "src" "dst"]
2018/07/11 15:29:15 DEBUG : Using config file from "/Users/ishuahkariuki/.config/rclone/rclone.conf"
2018/07/11 15:29:15 DEBUG : Reset feature "DirMove"
2018/07/11 15:29:15 DEBUG : Reset feature "DirMove"
2018/07/11 15:29:15 INFO  : Local file system at /Users/ishuahkariuki/Workshop/go_workshop/src/github.com/ncw/lab/dst: Waiting for checks to finish
2018/07/11 15:29:15 INFO  : Local file system at /Users/ishuahkariuki/Workshop/go_workshop/src/github.com/ncw/lab/dst: Waiting for transfers to finish
2018/07/11 15:29:15 INFO  : dir/file.txt: Moved (server side)
2018/07/11 15:29:15 DEBUG : Local file system at /Users/ishuahkariuki/Workshop/go_workshop/src/github.com/ncw/lab/dst: copied 1 directories
2018/07/11 15:29:15 DEBUG : dir2: Removing directory
2018/07/11 15:29:15 DEBUG : Local file system at /Users/ishuahkariuki/Workshop/go_workshop/src/github.com/ncw/lab/src: deleted 1 directories
2018/07/11 15:29:15 INFO  :
Transferred:      0 Bytes (0 Bytes/s)
Errors:                 0
Checks:                 0
Transferred:            1
Elapsed time:          0s

2018/07/11 15:29:15 DEBUG : 4 go routines active
2018/07/11 15:29:15 DEBUG : rclone: Version "v1.42" finishing with parameters ["rclone" "move" "-vv" "--delete-empty-src-dirs" "--disable" "DirMove" "src" "dst"]
$ tree src
src
└── dir

1 directory, 0 files
$ tree dst
dst
├── dir
│   └── file.txt
└── dir2

2 directories, 1 file
```
@ncw I'll write proper tests for this before fixing it.

**Comment by ncw** [comment]
Thanks @ishuah :-)

**Comment by ncw** [comment]
@ishuah has fixed this now

https://beta.rclone.org/v1.42-050-gdcc74fa4/ (uploaded in 15-30 mins)

This will be in [the latest beta](https://beta.rclone.org) from now on and v1.43

**Comment by WeKnowMC** [comment]
I am using version 1.43 and I am still experiencing this. Is it possible that the fix has been missed out of 1.43?

**Comment by ncw** [comment]
@WeKnowMC that fix is definitely in 1.43

The problem as I reformulated in my reply to the original issue is fixed (I just checked), but there may be more problems!

Can you make an example like the one I made above showing the problem and make a [new issue on github](https://github.com/ncw/rclone/issues/new) with that in?

Thanks

**Comment by andreluisos** [comment]
Mine (v1.45) still isn't deleting.

**Comment by ishuah** [comment]
@andreluisos thank you for your feedback! 
Can you create [a new issue](https://github.com/ncw/rclone/issues/new) with an example illustrating your issue?
