### ISSUE TITLE
Can't Mount Encrypted Remote

### ISSUE THREAD

**Issue by peewee5** [ncw/rclone#2374]
#### What is the problem you are having with rclone?
I am no longer able to view the files in my encrypted mount.  I have an encrypted mount in Google Drive that I have transferred quite a bit of data too.  I moved my Plex server so I was unmounting and then going to remount my drive after switching the Plex settings in in the gcache remote but now none of the files are showing up.  It's almost like a completely new encrypted mount, but I can still see all of the data in my old mount encrypted in drive.  Is there something that I need to do in order to point my mount command at the correct mount?

#### What is your rclone version (eg output from `rclone -V`)
rclone v1.42

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
- os/arch: linux/amd64

####  Which cloud storage system are you using? (eg Google Drive)
Google Drive

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone mount -vv --allow-other --gid 1005 --umask 0002 --bwlimit 9M --allow-non-empty gcrypt:

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
 rclone: Version "v1.42" starting with parameters ["rclone" "mount" "-vv" "--allow-other" "--gid" "1005" "--umask" "0002" "--bwlimit" "9M" "--allow-non-empty" "gcrypt:" "/home/michael/docker/shared/gdrive/"]
2018/07/02 11:25:23 DEBUG : Using config file from "/home/USER/.config/rclone/rclone.conf"
2018/07/02 11:25:23 INFO  : Starting bandwidth limiter at 9MBytes/s
2018/07/02 11:25:23 DEBUG : Encrypted drive 'gcrypt:': Mounting on "/homeUSERl/docker/shared/gdrive/"
2018/07/02 11:25:23 INFO  : Encrypted drive 'gcrypt:': poll-interval is not supported by this remote
2018/07/02 11:25:23 DEBUG : Adding path "vfs/forget" to remote control registry
2018/07/02 11:25:23 DEBUG : : Root:
2018/07/02 11:25:23 DEBUG : : >Root: node=/, err=<nil>

**Comment by ncw** [comment]
Sorry for the delay in responding.

How did you configure the mount on the new server?  Did you copy the config or set up from scratch?

I suspect you probably did the latter and have accidentally pointed the remote to a different google drive when you did the token part of it in the browser.

I've done this several times - it is easy to get mixed up if you have lots of accounts.  To make sure you are using the account you think you are you can use an incognito window in Chrome (or your favourite browsers equivalent).

**Comment by peewee5** [comment]
I did do the latter as you suspected. To avoid this in the future you are saying that I should copy the rclone config after setup, correct? Once I do that on the new system will the new remotes just be present when I pull up the config and I can mount as normal?

**Comment by ncw** [comment]
>  To avoid this in the future you are saying that I should copy the rclone config after setup, correct?

Yes that is right.  Use `rclone config file` to show where the config file is or should be and just copy it from machine to machine.

> Once I do that on the new system will the new remotes just be present when I pull up the config and I can mount as normal?

Yes :-)

I'l close this now since we've got to the bottom of it!
