### ISSUE TITLE
webdav: add hash support to owncloud and nextcloud

### ISSUE THREAD

**Issue by sp31415t1** [ncw/rclone#2379]
can you add hash support.
pasting from  https://github.com/ncw/rclone/issues/2373

It seems that they added file hash recently, but they forget about the documentation.

I only found that (and its others references) : https://github.com/owncloud/client/issues/6153

It is also possible to do an integrity check (file hash) on upload : https://doc.owncloud.org/desktop/2.4/architecture.html#upload
But it is another subject.

For nextcloud documentation, there is a property '{http://owncloud.org/ns}checksums':
https://docs.nextcloud.com/server/14/developer_manual/client_apis/WebDAV/index.html
maybe the requested hash

**Comment by ncw** [comment]
I also asked some questions on the owncloud forum and there were lots of helpful answers

    https://central.owncloud.org/t/reading-hashes-md5-or-sha1-via-webdav/14348

It looks like the checksums can be read at the same time rclone is doing the directory listings which is very helpful.

**Comment by sp31415t1** [comment]
Hi,
Can you indicate the help you're looking for ?
Regards,

**Comment by ncw** [comment]
@sp31415t1 
> Can you indicate the help you're looking for ?
Sure!  I'm looking for someone to
1. find out exactly how owncloud/nextcloud support hashes - if you read through the exchange above you'll see there are still some uncertainties
2. implement that in rclone in the webdav backend

Ideally someone could do both, but help with 1. would be appreciated too.

**Comment by sp31415t1** [comment]
I look a bit into documentations. That may help in having a better point of view.

https://docs.nextcloud.com/server/15/developer_manual/client_apis/WebDAV/basic.html
Is explaining how to get hash (checksums for PROPFIND request)
I tried it on a fresh nextcloud instance (15.0.2), whitout getting any value.

https://github.com/nextcloud/server/issues/6129
Is explaining that checksums are only stored if provided by client (at upload)

https://github.com/nextcloud/server/issues/11138
I'm not sure to have well understood (thanks to my poor english skill), but it looks like that the previous behaviour may be changed in near future (nextcloud 16)

hash can be present, but it is only depending on the client which had uploaded the file (so not reliable).

owncloud documentation is explaining how to upload with a file hash
https://doc.owncloud.org/desktop/2.4/architecture.html#checksum-algorithm-negotiation
Do you think it may be a good feature to implement ?

I read code, I don't have enough skill to make it.

**Comment by ncw** [comment]
@sp31415t1 wrote:
> I look a bit into documentations. That may help in having a better point of view.

Thank you

> https://docs.nextcloud.com/server/15/developer_manual/client_apis/WebDAV/basic.html
> Is explaining how to get hash (checksums for PROPFIND request)
> I tried it on a fresh nextcloud instance (15.0.2), whitout getting any value.
> 
> [nextcloud/server#6129](https://github.com/nextcloud/server/issues/6129)
> Is explaining that checksums are only stored if provided by client (at upload)

Ah, OK.  This is something rclone could do .

> [nextcloud/server#11138](https://github.com/nextcloud/server/issues/11138)
> I'm not sure to have well understood (thanks to my poor english skill), but it looks like that the previous behaviour may be changed in near future (nextcloud 16)

From reading that, I think it is not implemented yet.  There is a change in progress, but it isn't merged.

> hash can be present, but it is only depending on the client which had uploaded the file (so not reliable).
> 
> owncloud documentation is explaining how to upload with a file hash
> https://doc.owncloud.org/desktop/2.4/architecture.html#checksum-algorithm-negotiation

Ah ha!  That would be very easy to implement in rclone.

> Do you think it may be a good feature to implement ?

Yes I do.

It would be really easy for rclone to add an SHA1 for the upload.  And it looks like the server will check it so that is good for data integrity.

Reading the checksums out of the listing looks reasonably straightforward too.

> I read code, I don't have enough skill to make it.

Well you did the hard work finding the facts out, I did the easy bit!  Below is a version of rclone which supports SHA1 and MD5 checksums on owncloud and nextcloud.  It uses SHA1 or MD5 as an upload integrity test and will report the checksums in `rclone md5sum` and `rclone sha1sum`. 

https://beta.rclone.org/branch/v1.45-109-g36e02181-fix-2379-owncloud-hashes-beta/ (uploaded in 15-30 mins)

I found that with my owncloud installation files already had both MD5 and SHA1 checksums.

Wheras with my installation of nextcloud the sha1sums were stored if they were uploaded with sha1sums.

**Comment by ncw** [comment]
Here is a slight update - forgot to read the hashes on a code path.  I also updated the docs.

https://beta.rclone.org/branch/v1.45-109-g87927825-fix-2379-owncloud-hashes-beta/ (uploaded in 15-30 mins)

**Comment by sp31415t1** [comment]
I only made test with a nextcloud instance, but it is working.
Plus sha1 hash is visble when doing a PROPFIND request with checksums prop.
Thanks a lot

**Comment by ncw** [comment]
Thanks for testing.

I've merged this to master now which means it will be in [the latest beta](https://beta.rclone.org) in 15-30 mins and released in v1.46
