### ISSUE TITLE
g grive transfers corrupting?

### ISSUE THREAD

**Issue by calisro** [ncw/rclone#238]
What is going on here?  each sync on a folder from drive to a local file system is arbitrarily saying they are new or different but nothing is changing on the source (g drive).  If I do a md5sum on one of hte files before and after, I see the md5 is changing (flip/flopping).  What the heck.

**first run**
┌[ ✓ robert [/data/bin] $
└─> rclone sync -v "$SRCDIR/2010/08" "$DESTDIR/2010/08" 2>&1 | egrep -v "identical|Unchanged|Reading|Finished reading|within tolerance"2015/12/02 13:05:44 Local file system at /data/Google Photos-sheila/2010/08: Modify window is 1ms
2015/12/02 13:05:44 Local file system at /data/Google Photos-sheila/2010/08: Building file list
2015/12/02 13:05:44 Local file system at /data/Google Photos-sheila/2010/08: Waiting for checks to finish
2015/12/02 13:05:45 Local file system at /data/Google Photos-sheila/2010/08: Waiting for transfers to finish
**2015/12/02 13:05:45 qikvideo-2010-08-29-20-43-14.png: Copied (new)**
2015/12/02 13:05:45 qikvideo-2010-08-30-00-58-32.png: Copied (new)
2015/12/02 13:05:45 qikvideo-2010-08-30-00-59-08.png: Copied (new)
2015/12/02 13:05:45 Waiting for deletions to finish

Transferred:         3415 Bytes (   2.05 kByte/s)
Errors:                 0
Checks:                 8
Transferred:            3
Elapsed time:        1.6s

2015/12/02 13:05:45 Go routines at exit 24

┌[ ✓ robert [/data/Google Photos-sheila/2010/08] $
└─> md5sum qikvideo-2010-08-29-20-43-14.png
**27215e62f6cc56eccab20109cbc0be51  qikvideo-2010-08-29-20-43-14.png**

**Next run:**
┌[ ✓ robert [/data/bin] $
└─> rclone sync $OPTS -v "$SRCDIR/2010/08" "$DESTDIR/2010/08" 2>&1 | egrep -v "identical|Unchanged|Reading|Finished reading|within tolerance"
2015/12/02 13:10:51 Local file system at /data/Google Photos-sheila/2010/08: Modify window is 1ms
2015/12/02 13:10:51 Local file system at /data/Google Photos-sheila/2010/08: Building file list
2015/12/02 13:10:51 Local file system at /data/Google Photos-sheila/2010/08: Waiting for checks to finish
2015/12/02 13:10:51 Local file system at /data/Google Photos-sheila/2010/08: Waiting for transfers to finish
2015/12/02 13:10:52 qikvideo-2010-08-30-00-59-08.png: Copied (new)
**2015/12/02 13:10:52 qikvideo-2010-08-29-20-43-14.png: Copied (new)**
2015/12/02 13:10:52 qikvideo-2010-08-30-00-58-32.png: Copied (new)
2015/12/02 13:10:52 Waiting for deletions to finish

Transferred:         3415 Bytes (   1.86 kByte/s)
Errors:                 0
Checks:                 8
Transferred:            3
Elapsed time:        1.7s

2015/12/02 13:10:52 Go routines at exit 24

┌[ ✓ robert [/data/Google Photos-sheila/2010/08] $
└─> md5sum qikvideo-2010-08-29-20-43-14.png
**24d803d642f9e473c8aee234fcf6fde2  qikvideo-2010-08-29-20-43-14.png**

**third run**

┌[ ✓ robert [/data/bin] $
└─> rclone sync $OPTS -v "$SRCDIR/2010/08" "$DESTDIR/2010/08" 2>&1 | egrep -v "identical|Unchanged|Reading|Finished reading|within tolerance"2015/12/02 13:12:26 Local file system at /data/Google Photos-sheila/2010/08: Modify window is 1ms
2015/12/02 13:12:26 Local file system at /data/Google Photos-sheila/2010/08: Building file list
2015/12/02 13:12:26 Local file system at /data/Google Photos-sheila/2010/08: Waiting for checks to finish
2015/12/02 13:12:26 qikvideo-2010-08-29-20-43-14.png: Sizes differ
2015/12/02 13:12:26 qikvideo-2010-08-30-00-58-32.png: Sizes differ
2015/12/02 13:12:26 qikvideo-2010-08-30-00-59-08.png: Sizes differ
2015/12/02 13:12:26 Local file system at /data/Google Photos-sheila/2010/08: Waiting for transfers to finish
2015/12/02 13:12:26 qikvideo-2010-08-30-00-59-08.png: Copied (new)
**2015/12/02 13:12:26 qikvideo-2010-08-29-20-43-14.png: Copied (new)**
2015/12/02 13:12:26 qikvideo-2010-08-30-00-58-32.png: Copied (new)
2015/12/02 13:12:26 qikvideo-2010-08-30-00-59-08.png: Copied (updated existing)
**2015/12/02 13:12:27 qikvideo-2010-08-29-20-43-14.png: Copied (updated existing)**
2015/12/02 13:12:27 qikvideo-2010-08-30-00-58-32.png: Copied (updated existing)
2015/12/02 13:12:27 Waiting for deletions to finish

Transferred:         6301 Bytes (   3.62 kByte/s)
Errors:                 0
Checks:                 8
Transferred:            6
Elapsed time:        1.7s

2015/12/02 13:12:27 Go routines at exit 28

┌[ ✓ robert [/data/Google Photos-sheila/2010/08] $
└─> md5sum qikvideo-2010-08-29-20-43-14.png
**27215e62f6cc56eccab20109cbc0be51  qikvideo-2010-08-29-20-43-14.png**

**Comment by calisro** [comment]
Actually I dug more and even if I issue the following, it generates different md5sums.  

What is up with this? 

┌[ ✓ robert [/data/bin] $
└─> rclone md5sum "$SRCDIR/2010/08"
27215e62f6cc56eccab20109cbc0be51  qikvideo-2010-08-29-20-43-14.png
52148698e4f5cc169531d181fab3d5d5  qikvideo-2010-08-30-00-58-32.png
186df2eb94d1d98f97d77629c45ad792  IMAG0002.jpg
68d63fb99adcb10150a38e5d932e8e32  IMAG0001.jpg
24d803d642f9e473c8aee234fcf6fde2  qikvideo-2010-08-29-20-43-14.png
344650df816e6087c9bc2fe8bdfc20a1  qikvideo-2010-08-30-00-59-08.png
8b913abba39d739298fe398e8b6792b8  qikvideo-2010-08-30-00-59-08.png
6fb2651bc3d7315128b88490f20f6c51  qikvideo-2010-08-30-00-58-32.png
e1280a574148b97374556fd0db321a2a  IMAG0006.jpg
b813e8470b87f152f085fcdf80f6169f  IMAG0005.jpg
639ea90534ca636599294c31accd8a7d  IMAG0012.jpg

Transferred:            0 Bytes (   0.00 kByte/s)
Errors:                 0
Checks:                11
Transferred:            0
Elapsed time:          1s

┌[ ✓ robert [/data/bin] $
└─> rclone md5sum "$SRCDIR/2010/08"
27215e62f6cc56eccab20109cbc0be51  qikvideo-2010-08-29-20-43-14.png
b813e8470b87f152f085fcdf80f6169f  IMAG0005.jpg
24d803d642f9e473c8aee234fcf6fde2  qikvideo-2010-08-29-20-43-14.png
344650df816e6087c9bc2fe8bdfc20a1  qikvideo-2010-08-30-00-59-08.png
639ea90534ca636599294c31accd8a7d  IMAG0012.jpg
186df2eb94d1d98f97d77629c45ad792  IMAG0002.jpg
68d63fb99adcb10150a38e5d932e8e32  IMAG0001.jpg
8b913abba39d739298fe398e8b6792b8  qikvideo-2010-08-30-00-59-08.png
6fb2651bc3d7315128b88490f20f6c51  qikvideo-2010-08-30-00-58-32.png
52148698e4f5cc169531d181fab3d5d5  qikvideo-2010-08-30-00-58-32.png
e1280a574148b97374556fd0db321a2a  IMAG0006.jpg

Transferred:            0 Bytes (   0.00 kByte/s)
Errors:                 0
Checks:                11
Transferred:            0
Elapsed time:        1.5s

┌[ ✓ robert [/data/bin] $
└─> rclone md5sum "$SRCDIR/2010/08"
27215e62f6cc56eccab20109cbc0be51  qikvideo-2010-08-29-20-43-14.png
6fb2651bc3d7315128b88490f20f6c51  qikvideo-2010-08-30-00-58-32.png
639ea90534ca636599294c31accd8a7d  IMAG0012.jpg
186df2eb94d1d98f97d77629c45ad792  IMAG0002.jpg
68d63fb99adcb10150a38e5d932e8e32  IMAG0001.jpg
344650df816e6087c9bc2fe8bdfc20a1  qikvideo-2010-08-30-00-59-08.png
52148698e4f5cc169531d181fab3d5d5  qikvideo-2010-08-30-00-58-32.png
8b913abba39d739298fe398e8b6792b8  qikvideo-2010-08-30-00-59-08.png
24d803d642f9e473c8aee234fcf6fde2  qikvideo-2010-08-29-20-43-14.png
b813e8470b87f152f085fcdf80f6169f  IMAG0005.jpg
e1280a574148b97374556fd0db321a2a  IMAG0006.jpg

Transferred:            0 Bytes (   0.00 kByte/s)
Errors:                 0
Checks:                11
Transferred:            0
Elapsed time:          1s

┌[ ✓ robert [/data/bin] $
└─> rclone md5sum "$SRCDIR/2010/08"
27215e62f6cc56eccab20109cbc0be51  qikvideo-2010-08-29-20-43-14.png
344650df816e6087c9bc2fe8bdfc20a1  qikvideo-2010-08-30-00-59-08.png
639ea90534ca636599294c31accd8a7d  IMAG0012.jpg
186df2eb94d1d98f97d77629c45ad792  IMAG0002.jpg
68d63fb99adcb10150a38e5d932e8e32  IMAG0001.jpg
6fb2651bc3d7315128b88490f20f6c51  qikvideo-2010-08-30-00-58-32.png
8b913abba39d739298fe398e8b6792b8  qikvideo-2010-08-30-00-59-08.png
24d803d642f9e473c8aee234fcf6fde2  qikvideo-2010-08-29-20-43-14.png
e1280a574148b97374556fd0db321a2a  IMAG0006.jpg
52148698e4f5cc169531d181fab3d5d5  qikvideo-2010-08-30-00-58-32.png
b813e8470b87f152f085fcdf80f6169f  IMAG0005.jpg

Transferred:            0 Bytes (   0.00 kByte/s)
Errors:                 0
Checks:                11
Transferred:            0
Elapsed time:        1.4s

**Comment by calisro** [comment]
Interestingly enough.  the 'check' command doesn't say there are differences but the sync command above does.

┌[ ✓ robert [/data/bin] $
└─> rclone check "$SRCDIR/2010/08" "$DESTDIR/2010/08"
2015/12/02 13:25:48 Local file system at /data/Google Photos-sheila/2010/08: Building file list
2015/12/02 13:25:49 qikvideo-2010-08-29-20-43-14.png: Duplicate file detected
2015/12/02 13:25:49 qikvideo-2010-08-30-00-59-08.png: Duplicate file detected
2015/12/02 13:25:49 qikvideo-2010-08-30-00-58-32.png: Duplicate file detected
2015/12/02 13:25:49 Local file system at /data/Google Photos-sheila/2010/08: 0 files not in Google drive root 'Google Photos/2010/08'
2015/12/02 13:25:49 Google drive root 'Google Photos/2010/08': 0 files not in Local file system at /data/Google Photos-sheila/2010/08
2015/12/02 13:25:49 Local file system at /data/Google Photos-sheila/2010/08: Waiting for checks to finish
2015/12/02 13:25:49 Local file system at /data/Google Photos-sheila/2010/08: 0 differences found

Transferred:            0 Bytes (   0.00 kByte/s)
Errors:                 0
Checks:                 8
Transferred:            0
Elapsed time:        1.9s

┌[ ✓ robert [/data/bin] $
└─> rclone check "$SRCDIR/2010/08" "$DESTDIR/2010/08"
2015/12/02 13:27:17 Local file system at /data/Google Photos-sheila/2010/08: Building file list
2015/12/02 13:27:17 qikvideo-2010-08-29-20-43-14.png: Duplicate file detected
2015/12/02 13:27:17 qikvideo-2010-08-30-00-59-08.png: Duplicate file detected
2015/12/02 13:27:17 qikvideo-2010-08-30-00-58-32.png: Duplicate file detected
2015/12/02 13:27:17 Local file system at /data/Google Photos-sheila/2010/08: 0 files not in Google drive root 'Google Photos/2010/08'
2015/12/02 13:27:17 Google drive root 'Google Photos/2010/08': 0 files not in Local file system at /data/Google Photos-sheila/2010/08
2015/12/02 13:27:17 Local file system at /data/Google Photos-sheila/2010/08: Waiting for checks to finish
2015/12/02 13:27:17 Local file system at /data/Google Photos-sheila/2010/08: 0 differences found

Transferred:            0 Bytes (   0.00 kByte/s)
Errors:                 0
Checks:                 8
Transferred:            0
Elapsed time:        1.2s

**Comment by calisro** [comment]
If I attempt to only transfer ONE file rather than the whole directory, it also works as expected.
┌[ ✓ robert [/data/bin] $
└─> rclone sync $OPTS -v "$SRCDIR/2010/08/qikvideo-2010-08-30-00-59-08.png" "$DESTDIR/2010/08/qikvideo-2010-08-30-00-59-08.png" 2>&1 | egrep -v "identical|Unchanged|Reading|Finished reading|within tolerance"
2015/12/02 13:36:31 Local file system at /data/Google Photos-sheila/2010/08 limited to 1 objects: Modify window is 1ms
2015/12/02 13:36:31 Local file system at /data/Google Photos-sheila/2010/08 limited to 1 objects: Building file list
2015/12/02 13:36:31 Local file system at /data/Google Photos-sheila/2010/08 limited to 1 objects: Waiting for checks to finish
2015/12/02 13:36:31 Local file system at /data/Google Photos-sheila/2010/08 limited to 1 objects: Waiting for transfers to finish
2015/12/02 13:36:31 Waiting for deletions to finish

Transferred:            0 Bytes (   0.00 kByte/s)
Errors:                 0
Checks:                 1
**Transferred:            0**
Elapsed time:        1.6s

2015/12/02 13:36:31 Go routines at exit 9

**Comment by ncw** [comment]
It looks like you have duplicate files with the same name (see the output of the check command). If you delete the duplicates (with the drive Web interface) then it should work properly after that. 

As to what caused the duplicates? This is a known issue #28 which I haven't tracked down yet.

**Comment by calisro** [comment]
What is interesting here though is that the 'Google Photos' folder is a 'special' folder in that it is essentially a view in google drive to your photos.google.com photos.  When Android devices upload images, they go into photos.google.com and then are represented in the 'Google Photos' folder on drive.

That being said, the files are created by google themselves via their automated uploads from android devices (or essentially any other photos added to photos.google.com).

I've done a bit more testing and I cannot recreate this problem outside of that 'special' folder (I tried 3 different google accounts).  It does happen consistently when using those folders through for all 3 accounts.  

Thanks for the comment about the duplicates as that seems to have solved a hand full of them.  but the others (there are hundreds) do not have duplicates in drive.

**Comment by ncw** [comment]
Thanks for doing the investigation. I didn't know you could get a "Google Photos" folder in your drive - thanks for the heads up, that is very useful!

Interesting to see that even google have problems with duplicate files in drive - glad I'm not the only one!

There is an issue about removing duplicates #41 which I'd like to do at some point too.
