### ISSUE TITLE
I just want to ask, does the support not use under docker?

### ISSUE THREAD

**Issue by XWolcen** [ncw/rclone#2383]
Because I tried to deploy rclone in a container in docker, or deploy rclone on the host machine, no matter what I try to use mount --bind or other methods, the mounted googledrive directory can not be accessed by other containers, is there any way to deal with it? ?

Thank you, developer!

**Comment by ncw** [comment]
rclone does work in docker, however setting up rclone mounts in docker needs some extra stuff which I'm not an expert on.

I suggest you search and if you don't find anything ask in [the rclone forum](https://forum.rclone.org/) as there are lots of knowlegable users there.

**Comment by XWolcen** [comment]
thanks again, i get it.
