### ISSUE TITLE
checking 2 AWS buckets for differences - "slice bounds out of range"

### ISSUE THREAD

**Issue by meelislubi** [ncw/rclone#2388]
Hi, 

I'm trying to check differences between two AWS bucket directories.
I have been able to reproduce this with both latest stable and latest beta.
For most directories it works fine but occasionally with specific folders i get the following error:

rclone -vv check eu1:eu-central-1-something/publish/x/y/ seoul:ap-northeast-2-something/publish/x/y/

2018/07/09 11:33:21 DEBUG : rclone: Version "v1.42-028-g4c2fbf9bβ" starting with parameters ["rclone" "-vv" "check" "eu1:eu-central-1-something/publish/x/y/" "seoul:ap-northeast-2-something/publish/x/y/"]
2018/07/09 11:33:21 DEBUG : Using RCLONE_CONFIG_PASS password.
2018/07/09 11:33:21 DEBUG : Using config file from "/home/<removed>/.config/rclone/rclone.conf"
2018/07/09 11:33:22 INFO  : S3 bucket ap-northeast-2-something path publish/x/y/: Waiting for checks to finish
panic: runtime error: slice bounds out of range

goroutine 84 [running]:
github.com/ncw/rclone/backend/s3.(*Fs).list(0xc42039adc0, 0x0, 0x0, 0xc4206a1f01, 0xc42057e4e0, 0x0, 0xc4206a1dc0)
        /home/travis/gopath/src/github.com/ncw/rclone/backend/s3/s3.go:869 +0xc11
github.com/ncw/rclone/backend/s3.(*Fs).ListR(0xc42039adc0, 0x0, 0x0, 0xc4205741e0, 0xfaf401, 0xc4205741e0)
        /home/travis/gopath/src/github.com/ncw/rclone/backend/s3/s3.go:1000 +0xd1
github.com/ncw/rclone/fs.(ListRer).ListR-fm(0x0, 0x0, 0xc4205741e0, 0xc42057e4a0, 0xc4206a1e38)
        /home/travis/gopath/src/github.com/ncw/rclone/fs/fs.go:494 +0x4d
github.com/ncw/rclone/fs/walk.walkRDirTree(0x11f0580, 0xc42039adc0, 0x0, 0x0, 0xc4206a1e00, 0xffffffffffffffff, 0xc420383220, 0xc42007c600, 0x39cd7a73c711b152, 0xc4206a1eb0)
        /home/travis/gopath/src/github.com/ncw/rclone/fs/walk/walk.go:359 +0x147
github.com/ncw/rclone/fs/walk.NewDirTree(0x11f0580, 0xc42039adc0, 0x0, 0x0, 0x0, 0xffffffffffffffff, 0x8, 0xc4206a1ec0, 0x7ffffffe)
        /home/travis/gopath/src/github.com/ncw/rclone/fs/walk/walk.go:458 +0x11f
github.com/ncw/rclone/fs/march.(*March).makeListDir.func2(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/travis/gopath/src/github.com/ncw/rclone/fs/march/march.go:89 +0x251
github.com/ncw/rclone/fs/march.(*March).processJob.func1(0xc420557bd0, 0xc420171600, 0x0, 0x0, 0x0, 0x0, 0x7ffffffe, 0x7ffffffe, 0x0, 0xc420550860, ...)
        /home/travis/gopath/src/github.com/ncw/rclone/fs/march/march.go:348 +0x6c
created by github.com/ncw/rclone/fs/march.(*March).processJob
        /home/travis/gopath/src/github.com/ncw/rclone/fs/march/march.go:346 +0xe6e

**Comment by meelislubi** [comment]
Seems to be related to --fast-check
if i disabled fast-check if seems to work:

export RCLONE_FAST_LIST=false;
export RCLONE_BUFFER_SIZE=10M;
export RCLONE_CHECKERS=50;
export RCLONE_TRANSFERS=50;
export RCLONE_TPSLIMIT_BURST=80;
export RCLONE_TIMEOUT=30s;
export RCLONE_STATS=1m;
export RCLONE_STATS_UNIT=bits;
export RCLONE_STATS_LOG_LEVEL="INFO";
export RCLONE_LOG_LEVEL="INFO";

**Comment by ncw** [comment]
I think this should fix it.  I don't know how no-one noticed this before!

https://beta.rclone.org/branch/v1.42-030-g793f594b-fix-2388-s3-fast-list/ (uploaded in 15-30 mins)

Let me know if it does - thanks.

**Comment by meelislubi** [comment]
seems to be working fine 👍 
thanks.

**Comment by ncw** [comment]
Great, thanks for testing.

This fix will be in

https://beta.rclone.org/v1.42-030-g793f594b/ (uploaded in 15-30 mins)

[the latest beta](https://beta.rclone.org) from now on and 1.43
