### ISSUE TITLE
Problem: Azure listChunkSize is not configurable

### ISSUE THREAD

**Issue by scollazo** [ncw/rclone#2390]
#### What is the problem you are having with rclone?

In one of my instances, Rclone fails to list the cointainer files when using --fast-list.

I was able to work around this by changing the default value for [listChunkSize](https://github.com/ncw/rclone/blob/master/backend/azureblob/azureblob.go#L39) from 5000 to 1000 (tried 2500, but also failed in this host) and rebuilding rclone.

It would be nice to have this as a command line option.

#### What is your rclone version (eg output from `rclone -V`)

rclone v1.42
- os/arch: linux/amd64
- go version: go1.10.1

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

Ubuntu 16.04 64 bits

####  Which cloud storage system are you using? (eg Google Drive)

Azure

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

```
rclone sync -v --fast-list /path-to-folder azure-rclone:container --backup-dir azure-rclone:container-changes/$(date +%Y)/$(date +%m)/$(date +%d)-$(date +%H%M%S)
```

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

```
018/07/06 05:49:52 DEBUG : rclone: Version "v1.42" starting with par
ameters ["rclone" "sync" "-vv" "--fast-list" "/path-to-upload" "azure-rclone:container" "--backup-dir"  "azure-rclone:container-changes/2018/07/06-054952"]
2018/07/06 05:49:52 DEBUG : Using config file from "/root/.config/rclone/rclone.conf"
2018/07/06 05:50:27 DEBUG : pacer: Rate limited, increasing sleep to 20ms
2018/07/06 05:50:27 DEBUG : pacer: low level retry 1/10 (error read tcp XX.XX.XX.XX:49490 >XX.XX.XX.XX:443: read: connection reset by peer)
2018/07/06 05:50:52 INFO  : 
Transferred:      0 Bytes (0 Bytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:      1m0.4s

2018/07/06 05:51:03 DEBUG : pacer: Rate limited, increasing sleep to 40ms
2018/07/06 05:51:03 DEBUG : pacer: low level retry 2/10 (error read tcp XX.XX.XX.XX:49510->XX.XX.XX.XX:443: read: connection reset by peer)
2018/07/06 05:51:34 DEBUG : pacer: Rate limited, increasing sleep to 80ms
2018/07/06 05:51:34 DEBUG : pacer: low level retry 3/10 (error read tcp XX.XX.XX.XX:49550->XX.XX.XX.XX:443: read: connection reset by peer)
2018/07/06 05:51:52 INFO  : 
Transferred:      0 Bytes (0 Bytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:      2m0.4s

```

Retries continue until 10.

**Comment by ncw** [comment]
We are just about to merge #2371 which is an update to use the new SDK.  This may or may not fix this problem - can you try this beta and see whether it does?

https://beta.rclone.org/branch/v1.42-030-ge24fe271-sandeepkru-azureBlobSDKPort/ (uploaded in 15-30 mins)

@sandeepkru any thoughts?

**Comment by scollazo** [comment]
@ncw , version v1.42-030-ge24fe271  doesn't seem to fix it:

```
[...]
018/07/11 15:28:02 INFO  :
Transferred:      0 Bytes (0 Bytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:        3m0s

2018/07/11 15:28:05 DEBUG : pacer: Rate limited, increasing sleep to 20
ms
2018/07/11 15:28:05 DEBUG : pacer: low level retry 1/10 (error -> githu
b.com/ncw/rclone/vendor/github.com/Azure/azure-storage-blob-go/2017-07-
29/azblob.NewResponseError, /home/travis/gopath/src/github.com/ncw/rclo
ne/vendor/github.com/Azure/azure-storage-blob-go/2017-07-29/azblob/zz_g
enerated_response_error.go:29
===== RESPONSE ERROR (ServiceCode=) =====
Description=failed to read response body, Details: (none)
   GET https://XXXX.blob.core.windows.net/XXXX?com
p=list&delimiter=&include=metadata&maxresults=5000&restype=container&ti
meout=61
   Authorization: REDACTED
   User-Agent: [Azure-Storage/0.1 (go1.10.1; linux)]
   X-Ms-Client-Request-Id: [XXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXX]
   X-Ms-Date: [Wed, 11 Jul 2018 19:27:26 GMT]
   X-Ms-Version: [2017-07-29]
   --------------------------------------------------------------------------------
   RESPONSE Status: 200 OK
   Content-Type: [application/xml]  
   Date: [Wed, 11 Jul 2018 19:27:31 GMT]
   Server: [Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0]
   X-Ms-Request-Id: [7ccc4720-501e-0004-694d-1968da000000]
   X-Ms-Version: [2017-07-29]


read tcp XX.XX.XX.XX:58454->XX.XX.XX.XX:443: read: connection reset by peer
)
2018/07/11 15:32:02 INFO  :
Transferred:      0 Bytes (0 Bytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:        7m0s

2018/07/11 15:33:02 INFO  :
Transferred:      0 Bytes (0 Bytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:        8m0s

2018/07/11 15:34:02 INFO  :
Transferred:      0 Bytes (0 Bytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:        9m0s


2018/07/11 15:34:49 DEBUG : pacer: Rate limited, increasing sleep to 80ms
2018/07/11 15:34:49 DEBUG : pacer: low level retry 3/10 (error -> github.com/ncw/rclone/vendor/github.com/Azure/azure-storage-blob-go/2017-07-29/azblob.NewResponseError, /home/travis/gopath/src/github.com/ncw/rclone/vendor/github.com/Azure/azure-storage-blob-go/2017-07-29/azblob/zz_generated_response_error.go:29

```
I added the command line option in https://github.com/ncw/rclone/compare/master...scollazo:wip/configure-azure-chunk-list-size?expand=1 ,  but not sure if it's worth a PR, or you want to take another approach

**Comment by sandeepkru** [comment]
@scollazo - I tried to repro this with directory containing 10K files, each file of 1K size and I was able to copy without any issues
```console
Transferred:   9.767 MBytes (48.452 kBytes/s)
Errors:                 0
Checks:                 0
Transferred:        10001
Elapsed time:     3m26.4s

2018/07/11 19:53:20 DEBUG : 15 go routines active
2018/07/11 19:53:20 DEBUG : rclone: Version "v1.42-DEV" finishing with parameters ["rclone" "copy" "--fast-list" "-vv" "~/tmpfiles/" "azblob:tmp2"]

```
Do you think it is something specific on client side? 

```console
rclone v1.42-DEV
- os/arch: linux/amd64
- go version: go1.8.3
```
Either way having configurable value might be good option as well, if you and Nick are fine, I can pull your changes into my PR addressing #2371

**Comment by scollazo** [comment]
This is only happening in one of my environments, I did some tests, and it failed with a folder with 30k files between 2 kilobytes and 4 megabytes, but I can't rule out problems client side.

Using my modified version, I was able to sync ~700k files without issues.

If @ncw agrees, I'm fine with this.

**Comment by ncw** [comment]
I don't really understand why changing the chunk size from 5000 to 1000 fixes it?  Is it because of some internal timeout at Azure meaning that the longer listing fails?

Is this actually an Azure issue?

The docs say [5000 should be OK](https://docs.microsoft.com/en-us/rest/api/storageservices/list-blobs) so I'm puzzled.

**Comment by ncw** [comment]
Looking at the link @scollazo posted it looks like we could set the `timeout` URL parameter.

    GET https://myaccount.blob.core.windows.net?comp=list&timeout=20

How long are the requests taking at the moment - are they 30 seconds or less?  I can't see what the default timeout is.  I think it might set the timeout to the max of 30 seconds as it is.

You can see if you use `-vv --dump headers` and look at the timestamps.

**Comment by scollazo** [comment]
This is happening in other of my test servers, I'll work on it.

**Comment by ncw** [comment]
This will be in [the latest beta](https://beta.rclone.org) in 15 mins and in v1.44 - thanks @scollazo
