### ISSUE TITLE
rclone.conf issues

### ISSUE THREAD

**Issue by gh0sti** [ncw/rclone#2391]
#### What is the problem you are having with rclone?
cant start over wont let me delete or copy, just stuck with the rclone.conf file can't modify it.

#### What is your rclone version (eg output from `rclone -V`)
v1.42

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
linux (its on a seedbox can't figure it out)

####  Which cloud storage system are you using? (eg Google Drive)
google drive

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
trying to d a remote, copy, ect gives me this error.
Failed to save config after 10 tries: Failed to create temp file for new config: open /home/user/.config/rclone/rclone.conf920998464: read-only file system

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
Using config file from "/home/user/.config/rclone/rclone.conf"
2018/07/12 03:31:55 Failed to create file system for "remote:tmp": didn't find section in config file

**Comment by ncw** [comment]
Rclone appears to think that the user has a read only file system.

Is that correct?

You can use the `--config` flag to point the config file to a place where rclone does have read write access.

**Comment by gh0sti** [comment]
what would the full command look like?

**Comment by ncw** [comment]
Just add `--config /path/to/new/rclone.config` to your rclone command line.

I'm afraid I don't know anything about seedboxes so can't suggest an actual research.

You might want to investigate why`/home` is read only though - that doesn't seem right.

**Comment by ncw** [comment]
I'm going to close this since it isn't an rclone issue.  If you need more help I suggest asking in [the rclone forum](https://forum.rclone.org/).

**Comment by ossie-git** [comment]
I ran into this issue as well.  The problem was that I had previously run rclone as the root user.  Changing ownership to the user running rclone fixed it.
