### ISSUE TITLE
"Use --config flag to workaround." with --config supplied.

### ISSUE THREAD

**Issue by cnrd** [ncw/rclone#2397]
#### What is the problem you are having with rclone?
rclone is throwing errors about no HOME dir, even with `--config` supplied:

```bash
INFO: 2018/07/14 02:07:15 ERROR : Couldn't find home directory or read HOME or XDG_CONFIG_HOME environment variables.
INFO: 2018/07/14 02:07:15 ERROR : Defaulting to storing config in current directory.
INFO: 2018/07/14 02:07:15 ERROR : Use --config flag to workaround.
INFO: 2018/07/14 02:07:15 ERROR : Error was: user: Current not implemented on linux/amd64
```
#### What is your rclone version (eg output from `rclone -V`)

```bash
rclone v1.42
- os/arch: linux/amd64
- go version: go1.10.1
```

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Proxmox 5.2

####  Which cloud storage system are you using? (eg Google Drive)
Google Drive

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
`/usr/bin/rclone copy -v --config /root/.config/rclone/rclone.conf $tarfile remote:path`

**Comment by ncw** [comment]
I've fixed this here

https://beta.rclone.org/v1.42-036-gdbb4b2c9/ (uploaded in 15-30 mins)

Let me know if it works for you.

Thanks for reporting
