### ISSUE TITLE
Download restart on "connection reset by peer" 

### ISSUE THREAD

**Issue by carsonhh** [ncw/rclone#2398]
I am downloading large files (greater than 200GB each) from Ceph storage. I constantly see these failure after 100GB in -->
`Removing partially written file on error: read tcp 10.242.67.49:54860->155.101.11.35:443: read: connection reset by peer`

This seems like an obvious place where the download should be automatically resumed rather than deleting the file and starting all over as it currently does.

**Comment by ncw** [comment]
I think this is covered by #2108 which should be relatively easy to implement.

**Comment by ncw** [comment]
I'm going to close this issue in favour of that one - can you subscribe to that one please?

Thanks
