### ISSUE TITLE
missing subdirectories

### ISSUE THREAD

**Issue by pmagnuson** [ncw/rclone#240]
Having an issue with "rclone -vn copy bin dest:bin"

bin has 2 subdirectories  disksink & rclone

output reports on files in the rclone directory, but not the disksink directory.  When the -n is omitted, files are not copied.

**Comment by ncw** [comment]
Can you send the output of rclone with `-v` please? Edit it if necessary to preserve privacy. Also rclone version, which OS you are using and which remote? Thanks

**Comment by pmagnuson** [comment]
Nick,

Thank you very much for responding and investigating this.  rclone looks
like a great tool and I want to build a little more confidence in it.

I have included some information here.  I seem to get the same results with
-n or not. rclone seems to be skipping over the directory dsink.

thanks again for looking at this.

Phil


My bin directory looks like:
>tree bin
bin
├── dsink
│   └── drivesink
│       ├── static
│       └── templates
└── rclone
    ├── README.html
    ├── README.txt
    ├── rclone
    └── rclone.1

The output of rclone:

>bin/rclone/rclone -nv copy bin acd:bin

2015/12/05 10:59:14 acd: Saving new token in config file
2015/12/05 10:59:15 Amazon cloud drive root 'bin': Modify window not
supported
2015/12/05 10:59:15 Amazon cloud drive root 'bin': Building file list
2015/12/05 10:59:15 Amazon cloud drive root 'bin': Finished reading
2015/12/05 10:59:15 Amazon cloud drive root 'bin': Waiting for checks to
finish
2015/12/05 10:59:15 .DS_Store: Not copying as --dry-run
2015/12/05 10:59:15 rclone/README.html: Not copying as --dry-run
2015/12/05 10:59:15 rclone/README.txt: Not copying as --dry-run
2015/12/05 10:59:15 rclone/rclone: Not copying as --dry-run
2015/12/05 10:59:15 rclone/rclone.1: Not copying as --dry-run
2015/12/05 10:59:15 Amazon cloud drive root 'bin': Waiting for transfers to
finish

Transferred:            0 Bytes (   0.00 kByte/s)
Errors:                 0
Checks:                 0
Transferred:            5
Elapsed time:        2.2s

2015/12/05 10:59:15 Go routines at exit 14

**Comment by ncw** [comment]
I don't think there are any files under the dsink directory (that is what it looks like from the tree output) are there? 

Rclone only copies files - it will make the directories if there are files in them. That means it won't copy empty directories or delete directories when empty. 

If you look at issue #100 you'll see thoughts on improving thus aspect of rclone.

**Comment by pmagnuson** [comment]
you are correct.  my bad.

great job.  I'll be using rclone and following the progress.  haven't
learned go yet or I would pitch in.

Thank you so much.
Phil

**Comment by ncw** [comment]
No problems!  Feel free to make more issues if you have more problems.

Nick
