### ISSUE TITLE
Where is the cache files? [Seemingly stupid question.] :) 

### ISSUE THREAD

**Issue by drpau** [ncw/rclone#2400]
#### What is the problem you are having with rclone?
I am trying to see the cache files come in, and also remove themselves after the time allocated in the cache window.

I have set a custom cache db path (--cache-db-path=/volume1/rclone_cache) in my mount command i use.  From reading the mount wiki, the cache db chunks follow the db path but append the remote to the end so my cache should be in /volume1/rclone_cache/cache (as cache is my remote name).  and it is...

i see both cache.db and cache directory (in /volume1/rclone_cache).
when i go into the cache directory, i also get all of the directories.

however, when i am playing a video, i monitor the directory and i see the modified timestamp change, but never do i see any files in the directory.  My presumption were that they were hidden, however they are not.  

for example:
```
ash-4.3# cd /volume1/Data/rclone_cache/Movies/Ferdinand\ \(2017\)/
ash-4.3# ls -lt
total 0
drwxr-xr-x 1 root root 0 Jul 16 12:28 Ferdinand (2017) [BLURAY-1080P PROPER][AAC 5.1][X264]-RARBG.mp4
drwxr-xr-x 1 root root 0 Jul  9 03:38 Ferdinand (2017) [BLURAY-2160P][TRUEHD 7.1][X264]-POOP.mkv
drwxr-xr-x 1 root root 0 Jul  8 21:00 Ferdinand (2017) - [BLURAY-1080P][DTS 5.1][X264]-DRONES.mkv
ash-4.3# cd Ferdinand\ \(2017\)\ \[BLURAY-1080P\ PROPER\]\[AAC\ 5.1\]\[X264\]-RARBG.mp4/
ash-4.3# ls
ash-4.3# ls -al
total 0
ash-4.3#
```
#### What is your rclone version (eg output from `rclone -V`)
beta 1.42-038

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
linux

####  Which cloud storage system are you using? (eg Google Drive)
google drive

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

first i mount rclone line normal with:
`/volume1/rclone1.42-038/rclone mount this_one: /mnt/gdrive.de/ --allow-other --config=/volume1/rclone1.40.conf --cache-db-path=/volume1/rclone_cache > /tmp/rclone.log 2>&1 &`
then i run:
`/volume1/rclone1.42-038/rclone mount cache_list: /volume1/Data/rclone_cache --config=/volume1/rclone1.40.conf --read-only --allow-other &
`
a copy of my config:
```
ash-4.3# cat rclone1.40.conf
[gdrive_mount]
type = drive
client_id = **********
client_secret = **********
scope = drive
root_folder_id =
service_account_file =
token = {"access_token":"**********","expiry":"2018-07-16T13:29:24.306204509+10:00"}

[cache]
type = cache
remote = gdrive_mount:
plex_url = http://127.0.0.1:32400
plex_username = ******
plex_password = *********
chunk_size = 5M
info_age = 12h
chunk_total_size = 10G
plex_token = ************

[this_one]
type = crypt
remote = cache:
filename_encryption = standard
directory_name_encryption = true
password = *************
password2 = **************

[cache_list]
type = crypt
remote = /volume1/rclone_cache/cache/
filename_encryption = standard
directory_name_encryption = true
password = ***************
password2 = ***************
ash-4.3#
```

**Comment by animosity22** [comment]
When you play a file or something along those lines, you download 'chunks' of the file. Those are stored based on the settings and cleaned up based on these settings:

```
      --cache-chunk-clean-interval string   Interval at which chunk cleanup runs (default "1m")
      --cache-chunk-no-memory               Disable the in-memory cache for storing chunks during streaming
      --cache-chunk-path string             Directory to cached chunk files (default "/home/felix/.cache/rclone/cache-backend")
      --cache-chunk-size string             The size of a chunk (default "5M")
```

The 'cache.db' is the listing of all the files and folders that you have in your remote.

Those are all stored based on these settings:

```
    --cache-db-path string                Directory to cache DB (default "/home/felix/.cache/rclone/cache-backend")
      --cache-db-purge                      Purge the cache DB before
      --cache-db-wait-time duration         How long to wait for the DB to be available - 0 is unlimited (default 1s)
      --cache-dir string                    Directory rclone will use for caching. (default "/home/felix/.cache/rclone")
```

The directory you are mounting is going to contain all your files and folders.

I'm not sure why you have 2 mounts but the second mount:

```
/volume1/rclone1.42-038/rclone mount cache_list: /volume1/Data/rclone_cache --config=/volume1/rclone1.40.conf --read-only --allow-other &
```
Is the one where you don't specify a cache-db location so it's going to store the chunks in the default location.

**Comment by drpau** [comment]
thanks @animosity22, i dont set ant of the first tags as i understand once you set the cache-db-path the chunk storage follows it.  therefore the cache is stored in /volume1/rclone_cache/cache/ 

the second mount which you talk about, is only a mount of the above location, decrypted. as the /volume1/rclone_cache/cache directory contains encrypted file and folder names, in order to view these, i need to see them decrypted.  Therefore i mount a crypt, of the cache location.  There is no cache associated with the remote "cache_list"  this is purely for "seeing the cache"

**Comment by animosity22** [comment]
I can't figure out why you have 2 mounts and what mount is actually playing.

Normal flow would be GD->Cache->Decrypt and you mount the Decrypt and that's your files and such.

In my rclone, I name them GD ->Gcache->Gmedia

My mount would be like:

```
clone cmount gmedia: /gmedia \
   --allow-other \
   --dir-cache-time 48h \
   --cache-total-chunk-size 10G \
   --cache-chunk-path /dev/shm \
   --cache-chunk-size 32M \
   --cache-tmp-upload-path /data/rclone \
   --cache-tmp-wait-time 60m \
   --cache-info-age 40h \
   --cache-db-path /dev/shm \
   --cache-dir /dev/shm \
   --buffer-size 0M \
   --log-level INFO 
```

The cache files are stored in /dev/shm/gmedia/files here with /dev/shm/gmedia.db:

```
felix@gemini:/dev/shm$ ls -al
total 88
drwxrwxrwt  3 root  root     160 Jul 16 21:07 .
drwxr-xr-x 20 root  root    4260 Jul 12 07:59 ..
drwxr-xr-x  2 felix felix     40 Jul 16 21:07 gcache
-rw-r--r--  1 felix felix 131072 Jul 16 21:07 gcache.db
```
I ran a mediainfo command and you can see as an example, there are now chunks in the directory that weren't before with the encrypted filenames.

```
felix@gemini:/dev/shm$ cd gcache
felix@gemini:/dev/shm/gcache$ ls
felix@gemini:/dev/shm/gcache$ time mediainfo "/test/Radarr_Movies/1922 (2017)/1922 (2017).mkv" | grep blah

real	0m53.734s
user	0m0.368s
sys	0m0.486s
felix@gemini:/dev/shm/gcache$ ls
s1n6gn87oo537vvls13nahl6co
felix@gemini:/dev/shm/gcache$ ls -alR | wc -l
81
felix@gemini:/dev/shm/gcache$ ls -alR | more
.:
total 0
drwxr-xr-x 3 felix felix  60 Jul 16 21:08 .
drwxrwxrwt 3 root  root  160 Jul 16 21:07 ..
drwxr-xr-x 3 felix felix  60 Jul 16 21:08 s1n6gn87oo537vvls13nahl6co

./s1n6gn87oo537vvls13nahl6co:
total 0
drwxr-xr-x 3 felix felix 60 Jul 16 21:08 .
drwxr-xr-x 3 felix felix 60 Jul 16 21:08 ..
drwxr-xr-x 3 felix felix 60 Jul 16 21:08 0p2og5mb3m65n44d3jqeqsn818

./s1n6gn87oo537vvls13nahl6co/0p2og5mb3m65n44d3jqeqsn818:
total 0
drwxr-xr-x 3 felix felix   60 Jul 16 21:08 .
drwxr-xr-x 3 felix felix   60 Jul 16 21:08 ..
drwxr-xr-x 2 felix felix 1220 Jul 16 21:09 rh2rqknk2fp5rcav0l2ic9qubo

./s1n6gn87oo537vvls13nahl6co/0p2og5mb3m65n44d3jqeqsn818/rh2rqknk2fp5rcav0l2ic9qubo:
total 1919280
drwxr-xr-x 2 felix felix     1220 Jul 16 21:09 .
drwxr-xr-x 3 felix felix       60 Jul 16 21:08 ..
-rwxr-xr-x 1 felix felix 33554432 Jul 16 21:08 0
-rwxr-xr-x 1 felix felix 33554432 Jul 16 21:08 100663296
-rwxr-xr-x 1 felix felix 33554432 Jul 16 21:09 1006632960
-rwxr-xr-x 1 felix felix 33554432 Jul 16 21:09 1040187392
-rwxr-xr-x 1 felix felix 33554432 Jul 16 21:09 1073741824
```

So if you are reading from the mount that has the cache area defined, you'll see chunks created as you access files there.

**Comment by drpau** [comment]
Hi @animosity22, just to clarify, im doing 2 things.

1: mounting an encrypted gdrive volume, to play plex stuff.
that process is: Gdrive>cache>decrypt (from my config this is gdrive_mount: > cache: > this_one: ) 

therefore the cache when mounted is encrypted and not able to be easily viewed (as their real filenames).

2: 
the second item I do is (from my config) cache_list: 
this is to decrypt my cache: (from part 1) in a readable manner.  this has nothing to do with part 1 at all in its operation, it is purely to see and read the files and filenames of what is mounted.

-----------

the reason for doing part 2, is i want to see where my cache files are being stored, when im playing a video (and in the top example i was playing ferdinand).

When i played ferdinand using the "1:" mount process above, the video plays fine.  However i can not see the downloaded chunks in my cache.  

to see the downloaded chunks, im using "2:" above.

Im trying to see it while im playing therefore there wouldnt be an expiry as such as they are currently being used, even if it was just 1 part of the chunk.

When i start playing the movie, i see the timestamp of the folder in the cache location change to the current time, but no files inside it.

i expect to see (going off my config above):
browse to /volume1/rclone_cache/cache/Movies/Ferdinand (2017)/Ferdinand (2017) [BLURAY-1080P PROPER][AAC 5.1][X264]-RARBG.mp4/

then see a list of chunk files in that folder:
chunk1, chunk2 etc... i see nothing in that folder, and the folder is 0bytes throughout playing.

**Comment by animosity22** [comment]
If you remove mount #2 and try to read a file, you'll see the encrypted names being built as chunks as you are caching with rclone the encrypted file names as that's what the cache is expecting.

It looks like you are overmounting the chunk area trying to decrypt it so you can see the names which I would surmise, breaks the cache.

**Comment by drpau** [comment]
ah ha! right, well maybe so, and thats probably the issue i have.  i thought that as chunks would have come down, they would just "appear" in the folder and whatever is viewing that folder, would see the files in there. let me test.......
--------------

ok just coming back from testing - playing ferdinand.

I have done the 2 following tests:
1: playing Ferdinand with only mount process 1 initialised.
what i can see is the following:
(keep in mind the time where i am is currently 17th if July, ~12:30pm - midday)
```
ash-4.3# cd /volume1/rclone_cache/
ash-4.3# ls -tal | head -5
total 32976
-rw-r--r-- 1 root root 50450432 Jul 17 12:25 cache.db
drwxr-xr-x 1 root root     1444 Jul 17 11:37 ..
drwxr-xr-x 1 root root      104 Jun 15 11:22 cache
drwxr-xr-x 1 root root       26 Jun 14 21:56 .
ash-4.3# cd cache
ash-4.3# ls -tal | head -5
total 0
drwxr-xr-x 1 root root  26566 Jul 17 01:38 8h4****
drwxr-xr-x 1 root root 151718 Jul 17 00:15 nj****
drwxr-xr-x 1 root root    104 Jun 15 11:22 .
drwxr-xr-x 1 root root     26 Jun 14 21:56 ..
ash-4.3# cd nj****/
ash-4.3# ls -tal | head -5
total 0
drwxr-xr-x 1 root root    512 Jul 17 00:26 rb****
drwxr-xr-x 1 root root    668 Jul 17 00:22 *****5fi0
drwxr-xr-x 1 root root   1492 Jul 17 00:21 **m090
drwxr-xr-x 1 root root    618 Jul 17 00:17 **osg

*** = censored appropriately... obviously long filenames
```
so this tells me of my /volume1/rclone_cache/cache/nj**** directory, that the last directory used was "rb****"


then to identify what movie "rb****" is, i mount my 2: mount above, i can see that this is not Ferdinand

```
ash-4.3# cd /volume1/Data/rclone_cache
ash-4.3# cd Movies/
ash-4.3# ls -tal | head -5
total 0
drwxr-xr-x 1 root root 0 Jul 17 00:26 Once Upon a Time in America (1984)
drwxr-xr-x 1 root root 0 Jul 17 00:22 Gladiator (2000)
drwxr-xr-x 1 root root 0 Jul 17 00:21 Bleeding Steel (2017)
drwxr-xr-x 1 root root 0 Jul 17 00:17 Loving Pablo (2018)
ash-4.3#
```
i am confident (by doing the same process to identify the directory of the movie above) that the directory starting with nj is my Movies directory.

----------------
another test of something that i have not played before and therefore is not already in my cache.  I saw no difference, the last folder modified was the same one as above, (rb****).  the folder "should" have modified as the cache chunks would come down into it. Or does a folder timestamp not get modified when files get added to it?

It looks like either my "cache chunks" are not being stored where i am saying (/volume1/rclone_cache/<remote name>) even though the cache db, and other folder structures are there, or the chunks entering the folder, are not changing the timestamp on the folder.

**Comment by animosity22** [comment]
If you want to validate the crypt name, just use:

clone --crypt-show-mapping ls <cryptremote>:directory

The chunks will match the encrypted names.

The directory may or may not update depending on the file system and mount options that you have. I personally have atime off on mine so it doesn't update.

**Comment by drpau** [comment]
thanks, i just gave that a go, and confirmed the process above to the correct directory.

any clues on what i should do about trying to find the chunks?  my presumption is that they are there and are working - its just not something i can see.

**Comment by animosity22** [comment]
If you want to add another mount so you can auto decrypt the chunks, change your mount command to mount the chunk area to somewhere else.

I made:

```
[chunks]
type = crypt
remote = /dev/shm/gcache
filename_encryption = standard
passwords out
```

and mounted that via:
```
rclone mount chunks: /test1 --allow-other
```

if I go into test1, I can see my chunks decrypted:

```
felix@gemini:/test1$ ls -alR
.:
total 0
drwxrwxr-x 1 felix felix 0 Jul 16 23:05 Radarr_Movies

./Radarr_Movies:
total 0
drwxrwxr-x 1 felix felix 0 Jul 16 23:05 'Unsane (2018)'

'./Radarr_Movies/Unsane (2018)':
total 0
drwxrwxr-x 1 felix felix 0 Jul 16 23:05 'Unsane (2018).mkv'

'./Radarr_Movies/Unsane (2018)/Unsane (2018).mkv':
```

as I think that's what you were going for, but you don't want to overmount, which I am surprised worked without using --allow-non-empty

**Comment by drpau** [comment]
@animosity22 isnt that exactly what i have done?

```
[cache_list]
type = crypt
remote = /volume1/rclone_cache/cache/
filename_encryption = standard
directory_name_encryption = true
password = ***************
password2 = ***************
```

to compare our 2 remotes:

**types:** 
same

**remote:** 
yours is your --cache-chunk-path (/dev/shm) 
mine is my --cache-db-path (/volume1/rclone_cache) - and as per the manual, the chunk path, follows the db path.

> This config follows the --cache-db-path. If you specify a custom location for --cache-db-path and don’t specify one for --cache-chunk-path then --cache-chunk-path will use the same path as --cache-db-path.


**filename_encryption**
same

**passwords**
well doesnt matter in this case.

your mount command
`rclone mount chunks: /test1 --allow-other`

my mount command (with removed folder paths for easier reading)
rclone mount cache_list: /volume1/Data/rclone_cache --config=/volume1/rclone1.40.conf --read-only --allow-other &

there are slight differences in the paths, im mounting the rclone cache: to /volume1/rclone_cache and im reading the decrypted cache from a mount point /volume1/**Data**/rclone_cache

is that the confusion?

**Comment by animosity22** [comment]
Ah yes, I do see now. I misread the earlier post as they are separate.

So I guess back to your question with that sorted, are you not seeing encrypted chunks in #1 and the decrypted stuff in #2? I played back some stuff and was able to see in both locations.

**Comment by drpau** [comment]
no dramas @animosity22.
yep thats correct , in part.

the reason i say in part, is because when i look (and lets call it easier to understand names than my mount point) at my "encrypted rclone cache location" i am looking for a folder which has a timestamp of "now" as i start playing. 

If i saw a folder with a current date and time, i would go into that directory and as i ls, i would seemily see new chunks entering that folder as the movie played.

Im not seeing the folders date and time change so its hard to verify which folder it is.  Thats why i created the second mount.

So with the second mount, i can easily tell which folder and file im going to, and even if i mount that after the movie started playing (assuming i would get the list of files as it was when it mounted but may not get refreshed chunks in real time), i would see those chunks in the directory of the movie playing.

**Comment by animosity22** [comment]
So the problem you are seeing that the time on the directory is not updating? You can see the chunks in the folder, but not sure which folder.

What are the mount options on your directory that you are writing the chunks to?

```
felix@gemini:~$ mount | grep /dev/sda2
/dev/sda2 on / type ext4 (rw,relatime,data=ordered)
```

So for me:

```
    relatime
              Update inode access times relative to modify or change time.  Access time is only updated if the previous access
              time  was  earlier  than  the  current modify or change time.  (Similar to noatime, but it doesn't break mutt or
              other applications that need to know if a file has been read since the last time it was modified.)
```

**Comment by ncw** [comment]
Glad you got it working.  I'll close this now.
