### ISSUE TITLE
S3 compatible need to support virtual hosted style(oss/nos)

### ISSUE THREAD

**Issue by xiaolei0125** [ncw/rclone#2401]
current rclone s3 compatible  type only supported path style,  not virtual hosted style.
so rclone can not work with aliyun oss or netease cos.

eg:
path style:  oss-cn-shenzhen.aliyuncs.com:/mybucket/myfile
virtual hosted style:  mybucket.oss-cn-shenzhen.aliyuncs.com/myfile

rclone config
[oss]
type = s3
provider = Other
env_auth = false
access_key_id = LTAIyxxxxxxx
secret_access_key = plbDdxvBIuxxxxxxx
region =
endpoint = oss-cn-shenzhen.aliyuncs.com
location_constraint =
acl = public-read

rclone.exe --dump headers --log-level DEBUG lsd oss:mybucket
2018/07/16 18:14:40 DEBUG : GET /mybucket?delimiter=%2F&max-keys=1000&prefix= HTTP/1.1
Host: oss-cn-shenzhen.aliyuncs.com
User-Agent: rclone/v1.42
Authorization: XXXX
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20180716T101440Z
Accept-Encoding: gzip

2018/07/16 18:14:52 DEBUG : HTTP RESPONSE (req 0xc04235f800)
2018/07/16 18:14:52 DEBUG : HTTP/1.1 403 Forbidden
Content-Length: 260
Connection: keep-alive
Content-Type: application/xml
Date: Mon, 16 Jul 2018 10:14:53 GMT
Server: AliyunOSS
X-Amz-Request-Id: 5B4C701DB79FD65569BE0437

2018/07/16 18:14:52 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2018/07/16 18:14:52 ERROR : : error listing: SecondLevelDomainForbidden: Please use virtual hosted style to access.
        status code: 403, request id: 5B4C701DB79FD65569BE0437, host id:
2018/07/16 18:14:52 Failed to lsd: SecondLevelDomainForbidden: Please use virtual hosted style to access.
        status code: 403, request id: 5B4C701DB79FD65569BE0437, host id:

**Comment by ncw** [comment]
Rclone uses the aws official SDK.  Can you work out what rclone would need to do in the SDK: https://docs.aws.amazon.com/sdk-for-go/api/service/s3/ in order to enable this?

The code is here if you want to look at it: https://github.com/ncw/rclone/blob/master/backend/s3/s3.go

**Comment by xiaolei0125** [comment]
@ncw Thanks for you reply.  
in  https://github.com/ncw/rclone/blob/master/backend/s3/s3.go  code: 
	awsConfig := aws.NewConfig().
		WithRegion(opt.Region).
		WithMaxRetries(maxRetries).
		WithCredentials(cred).
		WithEndpoint(opt.Endpoint).
		WithHTTPClient(fshttp.NewClient(fs.Config)).
		WithS3ForcePathStyle(true)

    I think "WithS3ForcePathStyle(true)"  should be modified to allow user to configure options， such as true or false, 
    WithS3ForcePathStyle(false) can support many cloud object storage service, such as aliyun oss and netease nos which only support virtual hosted style.

**Comment by ncw** [comment]
Ah, OK!

Try this with `--s3-force-path-style=false` and let me know if it fixes the problem.

You can also set this in the config file in the advanced section

https://beta.rclone.org/branch/v1.42-052-g56eeebc4-fix-2401-s3-path-style/ (uploaded in 15-30 mins)

If that works, would you document how to set up rclone with aliyun and netease?

**Comment by xiaolei0125** [comment]
@ncw Thank you for adding this new features.

I have tested it for aliyun oss and netease nos on windows and Linux, with --s3-force-path-style=false or  advanced section, everything works fine.  

so rclone with "--s3-force-path-style=false"  can support some cloud object storage providers, such as aliyun oss and netease nos which compatible S3 API but not support path style.

**Comment by xiaolei0125** [comment]
This is a  document  show how to set up rclone with aliyun oss (netease nos has a similar configuration, only endpoint and access key is different) 

# rclone config
Current remotes:

Name                 Type
====                 ====
b2                   b2
cos                  s3
nos                  s3
od1                  webdav

e) Edit existing remote
n) New remote
d) Delete remote
r) Rename remote
c) Copy remote
s) Set configuration password
q) Quit config
e/n/d/r/c/s/q> n
name> oss
Type of storage to configure.
Enter a string value. Press Enter for the default ("").
Choose a number from below, or type in your own value
 1 / Alias for a existing remote
   \ "alias"
 2 / Amazon Drive
   \ "amazon cloud drive"
 3 / Amazon S3 Compliant Storage Providers (AWS, Ceph, Dreamhost, IBM COS, Minio)
   \ "s3"
 4 / Backblaze B2
   \ "b2"
 5 / Box
   \ "box"
 6 / Cache a remote
   \ "cache"
 7 / Dropbox
   \ "dropbox"
 8 / Encrypt/Decrypt a remote
   \ "crypt"
 9 / FTP Connection
   \ "ftp"
10 / Google Cloud Storage (this is not Google Drive)
   \ "google cloud storage"
11 / Google Drive
   \ "drive"
12 / Hubic
   \ "hubic"
13 / Local Disk
   \ "local"
14 / Mega
   \ "mega"
15 / Microsoft Azure Blob Storage
   \ "azureblob"
16 / Microsoft OneDrive
   \ "onedrive"
17 / OpenDrive
   \ "opendrive"
18 / Openstack Swift (Rackspace Cloud Files, Memset Memstore, OVH)
   \ "swift"
19 / Pcloud
   \ "pcloud"
20 / QingCloud Object Storage
   \ "qingstor"
21 / SSH/SFTP Connection
   \ "sftp"
22 / Webdav
   \ "webdav"
23 / Yandex Disk
   \ "yandex"
24 / http Connection
   \ "http"
Storage> 3
Choose your S3 provider.
Enter a string value. Press Enter for the default ("").
Choose a number from below, or type in your own value
 1 / Amazon Web Services (AWS) S3
   \ "AWS"
 2 / Ceph Object Storage
   \ "Ceph"
 3 / Digital Ocean Spaces
   \ "DigitalOcean"
 4 / Dreamhost DreamObjects
   \ "Dreamhost"
 5 / IBM COS S3
   \ "IBMCOS"
 6 / Minio Object Storage
   \ "Minio"
 7 / Wasabi Object Storage
   \ "Wasabi"
 8 / Any other S3 compatible provider
   \ "Other"
provider> 8
Get AWS credentials from runtime (environment variables or EC2/ECS meta data if no env vars).
Only applies if access_key_id and secret_access_key is blank.
Enter a boolean value (true or false). Press Enter for the default ("false").
Choose a number from below, or type in your own value
 1 / Enter AWS credentials in the next step
   \ "false"
 2 / Get AWS credentials from the environment (env vars or IAM)
   \ "true"
env_auth> 1
AWS Access Key ID.
Leave blank for anonymous access or runtime credentials.
Enter a string value. Press Enter for the default ("").
access_key_id> LTAxxxxxxxxxxxx
AWS Secret Access Key (password)
Leave blank for anonymous access or runtime credentials.
Enter a string value. Press Enter for the default ("").
secret_access_key> plbDxxxxxxxxxxxxxxxxx
Region to connect to.
Leave blank if you are using an S3 clone and you don't have a region.
Enter a string value. Press Enter for the default ("").
Choose a number from below, or type in your own value
 1 / Use this if unsure. Will use v4 signatures and an empty region.
   \ ""
 2 / Use this only if v4 signatures don't work, eg pre Jewel/v10 CEPH.
   \ "other-v2-signature"
region> 1
Endpoint for S3 API.
Required when using an S3 clone.
Enter a string value. Press Enter for the default ("").
Choose a number from below, or type in your own value
endpoint> oss-cn-shenzhen.aliyuncs.com
Location constraint - must be set to match the Region.
Leave blank if not sure. Used when creating buckets only.
Enter a string value. Press Enter for the default ("").
location_constraint> 
Canned ACL used when creating buckets and/or storing objects in S3.
For more info visit https://docs.aws.amazon.com/AmazonS3/latest/dev/acl-overview.html#canned-acl
Enter a string value. Press Enter for the default ("").
Choose a number from below, or type in your own value
 1 / Owner gets FULL_CONTROL. No one else has access rights (default).
   \ "private"
 2 / Owner gets FULL_CONTROL. The AllUsers group gets READ access.
   \ "public-read"
   / Owner gets FULL_CONTROL. The AllUsers group gets READ and WRITE access.
 3 | Granting this on a bucket is generally not recommended.
   \ "public-read-write"
 4 / Owner gets FULL_CONTROL. The AuthenticatedUsers group gets READ access.
   \ "authenticated-read"
   / Object owner gets FULL_CONTROL. Bucket owner gets READ access.
 5 | If you specify this canned ACL when creating a bucket, Amazon S3 ignores it.
   \ "bucket-owner-read"
   / Both the object owner and the bucket owner get FULL_CONTROL over the object.
 6 | If you specify this canned ACL when creating a bucket, Amazon S3 ignores it.
   \ "bucket-owner-full-control"
acl> 2
Edit advanced config? (y/n)
y) Yes
n) No
y/n> y
Chunk size to use for uploading
Enter a size with suffix k,M,G,T. Press Enter for the default ("5M").
chunk_size> 
Don't store MD5 checksum with object metadata
Enter a boolean value (true or false). Press Enter for the default ("false").
disable_checksum> 
An AWS session token
Enter a string value. Press Enter for the default ("").
session_token> 
Concurrency for multipart uploads.
Enter a signed integer. Press Enter for the default ("2").
upload_concurrency> 
If true use path style access if false use virtual hosted style.
Some providers (eg Aliyun OSS or Netease COS) require this.
Enter a boolean value (true or false). Press Enter for the default ("true").
force_path_style> false 
Remote config
--------------------
[oss]
type = s3
provider = Other
env_auth = false
access_key_id = LTxxxxxxxxx
secret_access_key = plbxxxxxxxxxxxxx
endpoint = oss-cn-shenzhen.aliyuncs.com
acl = public-read
force_path_style = false
--------------------
y) Yes this is OK
e) Edit this remote
d) Delete this remote
y/e/d> y
Current remotes:

Name                 Type
====                 ====
b2                   b2
cos                  s3
nos                  s3
od1                  webdav
oss                  s3

e) Edit existing remote
n) New remote
d) Delete remote
r) Rename remote
c) Copy remote
s) Set configuration password
q) Quit config
e/n/d/r/c/s/q> q

# rclone lsd oss:
          -1 2017-10-04 12:30:26        -1 deploy-py
# rclone ls oss:deploy-py 
 58875714 Tesseract-OCR.zip
  8510976 chromedriver.exe

**Comment by xiaolei0125** [comment]
This is a document show how to set up rclone with aliyun oss (netease nos has a similar configuration, only endpoint and access key is different) , see the attach files.
[config_rclone_with_aliyun_oss.txt](https://github.com/ncw/rclone/files/2212872/config_rclone_with_aliyun_oss.txt)

**Comment by ncw** [comment]
Thank you for testing.

I've merged this to master and I've edited your doc slightly and merged that too in 01af8e290595a7c80f843c740c02c3a3fdac2c4b - thank you very much indeed :-)

https://beta.rclone.org/v1.42-055-g01af8e29/ (uploaded in 15-30 mins)

This will be in [the latest beta](https://beta.rclone.org) and v1.43
