### ISSUE TITLE
Feature Suggestion: Print Rclone Output When Using Remote Control

### ISSUE THREAD

**Issue by photomatix18** [ncw/rclone#2405]
It would be nice to be able to use the rc command to show the rclone stats. Basically, have it print the output of the rclone task via remote control.

**Comment by ncw** [comment]
Thanks for making this issue.

Would you like to help implement it?

**Comment by photomatix18** [comment]
No problem. I honestly wouldn't have a clue where to start. I don't know
anything about programming. 🙂

**Comment by reddi1** [comment]
Here is my implementation for rc stats output: 44755ebb7d1542ccee43e8fdbb02dfeb867f6815
But I couldn't get the autogen for the rcdocs to run.

**Comment by ncw** [comment]
@reddi1 - nice one!  Don't worry about the autogen if you can't make it work - I can do that.  Do you want to send a pull request with that in?

**Comment by ncw** [comment]
This is now done and will be in [the latest beta](https://beta.rclone.org) in 15-30 mins.

The docs are here: https://github.com/ncw/rclone/blob/master/docs/content/rc.md#corestats-returns-stats-about-current-transfers

(which I now see need a bit of formatting!)
