### ISSUE TITLE
Improvement: Mega empty trash or hard deleting files

### ISSUE THREAD

**Issue by sixfingers76** [ncw/rclone#2409]
Hi,

It would be great to have the possibility of empty the Mega trash after deleting or syncing files, or at least to have the possibility of "hard deleting" the files instead of moving it to Mega trash. 

My issue is that I have to manually empty my Mega trash two times a day because there are a lot of deleted files in it due to sync processes. If I do not do it, I will be run out of space in Mega.

Thank you for your great job!

Kind regards,

Javier

**Comment by ncw** [comment]
Implementing `--mega-hard-delete` would be very easy.

I wanted to make a global `--hard-delete` flag for rclone.

Emptying the trash wouldn't be too tricky either.

Fancy helping with any of these?

**Comment by sixfingers76** [comment]
It would be awesome any of your proposals!

--hard-delete flag for rclone would be great. At the first stage it could be valid for Mega (just Mega or any other platforms you decide) and in the future for others. That is only my suggestion that I think it is on the same page as your idea, but of course it is up to you.

Thank you very much for your help!

Kind regars,

Javier

**Comment by ncw** [comment]
I'll do the `--mega-hard-delete` flag first as it is really easy.  A `--hard-delete` flag is a little tricker so can come later.

Here it is with `--mega-hard-delete`.  Note that you can also set it in the config file (use the advanced config for mega in `rclone config`).

https://beta.rclone.org/branch/v1.42-063-gccf53448-fix-2409-mega-hard-delete/ (uploaded in 15-30 mins)

How does that work for you?

**Comment by sixfingers76** [comment]
It worked like a charm!

Thank you very much for your fast and great support, and also for your awesome software!

Best regards,

Javier

**Comment by ncw** [comment]
I've merged that to master now along with some docs

You can find it here

https://beta.rclone.org/v1.42-065-gf9eb9c89/ (uploaded in 15-30 mins)

It will be in [the latest beta](https://beta.rclone.org) from now on and in the 1.43 release.

**Comment by caspertone2003** [comment]
@ncw 

> Emptying the trash wouldn't be too tricky either.

Hi,
Any advance on this one?
TIA,
CT

**Comment by caspertone2003** [comment]
@ncw 

Could you include this subject in the roadmap?

The only way I found has been to build a rather convoluted batch to list trash (using megatools !)
and then recursively delete the elements found. If those are too many, the batch fails because of limitations of batch variable length. Way around is to use a for /f, then it fails if there are not only ANSI characters. If there are too many not only ANSI filenames in the Trash, only way is going to browser access...

Thanks again,
CT

**Comment by ncw** [comment]
> The only way I found has been to build a rather convoluted batch to list trash (using megatools !)
> and then recursively delete the elements found. If those are too many, the batch fails because of limitations of batch variable length. Way around is to use a for /f, then it fails if there are not only ANSI characters. If there are too many not only ANSI filenames in the Trash, only way is going to browser access...

Do you mean emptying the trash on mega? Can you please make a [new issue](https://github.com/ncw/rclone/issues/new/choose) about that.  Do you want to help implement it?

**Comment by caspertone2003** [comment]
@ncw 
Thanks Nick.
Yes, the point is emptying the trash on mega.
I will open a new issue, and I can help providing info on my experience and help to debug any code, but I am not knowledgeable to code or make PRs... really sorry, just a kind of "smart user".
CT

**Comment by caspertone2003** [comment]
https://github.com/ncw/rclone/issues/3138

**Comment by ncw** [comment]
Trash emptying is now implemented which means it will be in [the latest beta](https://beta.rclone.org) in 15-30 mins and released in v1.48
