### ISSUE TITLE
Files not visible on GDrive

### ISSUE THREAD

**Issue by dav1303** [ncw/rclone#241]
Hi

We have launch a heavy migration (1 To = Over 1 Million Files) with Folders and subfolders and when we access drive we have got this error  : The server as encountered an error please try again later 

The files are not visible

Our folders are shared with other users

When I launch a new migration with rclone the log file indicates that the file already exist

Regards

**Comment by ncw** [comment]
Any chance you could send me a log of the problem with `rclone -v`?

Which rclone version are you using?

Which OS are you running rclone from?

The `500 The server as encountered an error please try again later` error unfortunately is not uncommon with drive.  It may be the cause of issue #28 which may be affecting you and is still outstanding.

**Comment by ncw** [comment]
I should also have said, rclone is designed so that if you get an error in the sync, and you will undoubtledly get lots syncling 1,000,000 files, then just retry the sync and rclone will tidy up what next.  You can  use the `--retry` flag to help also.

**Comment by ncw** [comment]
Did you have any luck getting a log of the problem?

Did retrying the sync work properly?

Thanks

Nick

**Comment by dav1303** [comment]
Hi Nick

It seems that this issue is probably related to drive API Or Drive Web UI because files are already in drive but not visible.

I can't give you log file sorry

Thanks for the follow
