### ISSUE TITLE
Notice/Info not working on Debian

### ISSUE THREAD

**Issue by animosity22** [ncw/rclone#2412]
#### What is the problem you are having with rclone
Log level with INFO and NOTICE or -v is not generating any logging information on Debian 9.

#### What is your rclone version (eg output from `rclone -V`)
rclone v1.42
- os/arch: linux/amd64
- go version: go1.10.1

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Debian 9

####  Which cloud storage system are you using? (eg Google Drive)
Google Drive

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
```
root@gemini:~# cat /etc/systemd/system/gmedia-rclone.service
[Unit]
Description=RClone Service
PartOf=gmedia.service

[Service]
Type=notify
ExecStart=/usr/bin/rclone mount gcrypt: /GD \
   --allow-other \
   --dir-cache-time 48h \
   --vfs-read-chunk-size 32M \
   --vfs-read-chunk-size-limit 2G \
   --buffer-size 512M \
   --umask 002 \
   --bind 192.168.1.30 \
   --log-level INFO \
   --log-file /home/felix/logs/rclone.log
ExecStop=/bin/fusermount -uz /GD
Restart=on-failure
User=felix
Group=felix

[Install]
WantedBy=gmedia.service
```

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

As an example, if I turn logging up to DEBUG or -vv, I can get a log file:

```
2018/07/24 11:13:48 DEBUG : : >Statfs: stat={Blocks:274877906944 Bfree:262750031364 Bavail:274877906944 Files:1000000000 Ffree:1000000000 Bsize:4096 Namelen:255 Frsize:4096}, err=<nil>
2018/07/24 11:13:48 DEBUG : rclone: Version "v1.42" finishing with parameters ["/usr/bin/rclone" "mount" "gcrypt:" "/GD" "--allow-other" "--dir-cache-time" "48h" "--vfs-read-chunk-size" "32M" "--vfs-read-chunk-size-limit" "2G" "--buffer-size" "512M" "--umask" "002" "--bind" "192.168.1.30" "--log-level" "DEBUG" "--log-file" "/home/felix/logs/rclone.log"]
```

If it's NOTICE or INFO, I get nothing created.

**Comment by B4dM4n** [comment]
`rclone mount` will not log very much in `notice` or `info` mode.

When I enable `--rc` the following line shows up in the log file or the console:
```
2018/07/24 20:28:36 NOTICE: Serving remote control on http://127.0.0.1:5572/
```

Are there any log lines you miss in particular?

**Comment by animosity22** [comment]
The INFO lines with the start / stop of the mount. New files being copied if I'm use cache-mode writes.

**Comment by B4dM4n** [comment]
The start/stop line are `DEBUG` level. Only the `... Copied (new)` lines are `INFO` level which sows up for me with `--log-level INFO`.

```
2018/07/24 21:24:03 INFO  : date.txt: Copied (new)
```

Would you prefer to see some more messages with `--log-level INFO`?

**Comment by animosity22** [comment]
Hmm. That's super strange as I can see now the start / stops aren't there, but I did test with a copy and that populated.

I think from my perspective, I'd like to see the 403s in the logs without having to run DEBUG to see when they occur and just general start and stop of the mount in the logs.

**Comment by animosity22** [comment]
I'll open a separate item as this was user error and not a bug.
