### ISSUE TITLE
Google documents have size -1

### ISSUE THREAD

**Issue by Fabian42** [ncw/rclone#2413]
Rclone sees Google documents as having a size of -1, which messes up everything that relies on these sizes. A proper handling would be to create a local file with the content of the document, or even better: A link to the Google document. That's also what the official client for Windows does.

More info and discussion so far here: https://github.com/cjnaz/rclonesync-V2/issues/1#issuecomment-407823320
and here: https://github.com/cjnaz/RCloneSync/issues/22

**Comment by B4dM4n** [comment]
Treating Google documents as real files will probably always have some drawbacks, since there is no lossless mapping between the two formats.

Representing them as some kind of link file has already been discussed [here](#1349).
I will close this issue in favor of the old one.
