### ISSUE TITLE
rclone sync is not deleting directories—it's only removing their contents. (Amazon Cloud Drive)

### ISSUE THREAD

**Issue by Wowfunhappy** [ncw/rclone#242]
I had a local directory Disk/Audiobooks/Mistborn, inside of which are a bunch of mp3 files making up the book's various chapters. I then ran rclone sync Disk Amazon:Archive

Later, I deleted the Mistborn folder from my Audiobooks directory, and ran rclone sync again. Even though all of the mp3 files inside of the Mistborn folder get deleted, the directory itself does not go away.

This is just one example. Directories consistently seem to not get deleted—only their contents does.

**Comment by ncw** [comment]
Yes it is the expected behaviour by me, but one I'd like to fix. Subscribe to the issue if you want updates on it. 

Cheers 

Nick

**Comment by arbrebinaire** [comment]
To keep rclone on par with rsync, directories should be deleted on target when absent on source.  I have the same problem.

Thanks for all the work.
