### ISSUE TITLE
Add switch to disable datetime output in log messages

### ISSUE THREAD

**Issue by cjnaz** [ncw/rclone#2424]
#### What is the problem you are having with rclone?
Having the DateTime field on rclone log messages hinders testing of 3rd party tools, such as https://github.com/cjnaz/rclonesync-V2.  Enhancement request:  Add switch to disable the DateTime field on rclone log messages.

#### What is your rclone version (eg output from `rclone -V`)
$ /bin/rclone -V
rclone v1.42
- os/arch: linux/amd64
- go version: go1.10.1

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Centos 7, 64 bit

**Comment by cjnaz** [comment]
With an empty list of comma separated log format options then there would be no date/time log?  Or support a "none" keyword/option.

Sounds good.  Not a priority.  Currently I just have to manually look at the results of 1 test case.

cjn

**Comment by ncw** [comment]
> With an empty list of comma separated log format options then there would be no date/time log? Or support a "none" keyword/option.

I'd probably do both a "none" and accept "".

**Comment by cjnaz** [comment]
Hi Nick,
I'll sign up for this one.  Should be an easy step in.  I'll need to figure out how to set up the Go dev environment.  Quick outline of what I'll need to setup/install, please.
Probably not for several weeks.  
cjn

**Comment by ncw** [comment]
Great @cjnaz that would be fab!

To develop you'll need to [install go](https://golang.org/doc/install), make sure you have git and a text editor.

First step is

    go get github.com/ncw/rclone

this will checkout rclone into `~/go/src/github.com/ncw/rclone`.  If you don't like this location then set GOPATH.

Then `cd ~/go/src/github.com/ncw/rclone` and go build to build rclone into the current directory.

Simple as that!

Recommended - install [goimports](https://godoc.org/golang.org/x/tools/cmd/goimports) and put it in your editor save hook.

Also put `~/go/bin` on your PATH is a good idea.

To send a pull request, fork the rclone project on github, then in `~/go/src/github.com/ncw/rclone` add your new repo as another upstream and push to that.  Go to the web interface to generate a PR.  This will run rclone's tests.   Checkout the Makefile to see what they do.

Happy hacking!

**Comment by cjnaz** [comment]
I'll try to get to this minor enhancement in the next week or so.  For the
bisync topic I will have time freeing up at the beginning of September,
fyi.  However,  if we integrate bisync then I won't need this logging
enhancement.   :)

**Comment by ncw** [comment]
Thanks to @dcpu that is now done :-)

https://beta.rclone.org/v1.43-018-gd3afef3e-beta/ (uploaded in 15-30 mins)
