### ISSUE TITLE
ls or copy file error for Onedrive Business(using webdav sharepoint)

### ISSUE THREAD

**Issue by xiaolei0125** [ncw/rclone#2426]
@hensur , @ncw 

this issue related to:
onedrive: Onedrive Business Support for organizations in an unamanged state (mostly universities) #1975  [#1975](https://github.com/ncw/rclone/issues/1975)

This is a problem to ls or copy file in webdav (onedrive sharepoint) , for example:
When ls, copy or sync from a source directory, it work fine.
rclone ls od1:song
rclone copy od1:song/  ./mylocal

But when ls or copy from a source file,, it has error:
rclone  ls od1:song/my.mp3
rclone copy od1:song/my.mp3  ./mylocal
ERROR : : error reading source directory: directory not found

Using rclone --dump headers --log-level DEBUG ls od1:song/my.mp3 to debug:
DEBUG : HTTP REQUEST (req 0xc4203ea300)
DEBUG : PROPFIND /personal/xxx_xxx_edu/Documents/song/my.mp3 HTTP/1.1
Host: xxx-my.sharepoint.com
DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
DEBUG : HTTP RESPONSE (req 0xc4203ea300)
DEBUG : HTTP/1.1 404 NOT FOUND
 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
ERROR : : error listing: directory not found
Failed to ls: directory not found

Using rclone --dump headers --log-level DEBUG ls od1:song/  to debug:
DEBUG : HTTP REQUEST (req 0xc420310e00)
DEBUG : PROPFIND /personal/xxx_xxx_edu/Documents/song/  HTTP/1.1
DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
DEBUG : HTTP RESPONSE (req 0xc420310e00)
DEBUG : HTTP/1.1 207 MULTI-STATUS
DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
  4750661 my.mp3
  3898990 test.mp3

**Comment by ncw** [comment]
Which version of rclone are you using?  Have you tried [the latest beta](https://beta.rclone.org)?

I don't understand why sharepoint is returning "404" on the PROPFIND of the file - any ideas?

This might work as a work-around

    rclone ls --include /my.mp3 od1:song/
    rclone copy --include /my.mp3 od1:song/ ./mylocal

**Comment by xiaolei0125** [comment]
@ncw Thanks for your reply.

I have tried rclone v1.42 and latest version,  still has 404 on the PROPFIND,  But rclone work fine with other webdav server except sharepoint.

rclone copy --include /my.mp3 od1:song/ ./mylocal  can work-around.
but rclone copy from local to sharepoint still failed since same problem(404 on the PROPFIND)

I'm not sure,  I think this maybe a sharepoint webdav issue， no idea how to solve it. 

@hensur , Do you have same issue?

**Comment by xiaolei0125** [comment]
@ncw 
Run cmd:  rclone --dump headers --log-level DEBUG ls od1:song/my.mp3:
DEBUG : PROPFIND /personal/xxx_xxx_edu/Documents/song/my.mp3 HTTP/1.1
Host: xxx-my.sharepoint.com
User-Agent: rclone/v1.42-060
Cookie: xxx
Depth: 1
Accept-Encoding: gzip
Got:  HTTP/1.1 404 NOT FOUND

Then I use postman tool to test ：
PROPFIND  https://xxx-my.sharepoint.com/personal/xxx_xxx_edu/Documents/song/my.mp3
Depth: 0
Got: HTTP/1.1 207 MULTI-STATUS,  and response detail info for my.mp3 file

So only change "Depth: 1" to "Depth: 0" in http header can make sharepoint webdav response normal.
I can do some testing， But i don't know how to fix it,  can you help me ?

**Comment by hensur** [comment]
I'll look into it in a few hours. Thanks for the testing with postman. That makes it a lot easier for me.

**Comment by hensur** [comment]
@xiaolei0125 
I just pushed my changes to https://github.com/hensur/rclone/tree/sharepoint-webdav-2436

If you have a 64-bit linux, here is a binary with these changes: https://mirror.hensur.de/rclone

Or you can compile it yourself:
```
go get github.com/ncw/rclone
cd $GOPATH
git remote add sharepoint https://github.com/hensur/rclone
git checkout sharepoint/sharepoint-webdav-2436
go build
```
I hope these instructions work, the binary should then be in the current directory.

**Comment by xiaolei0125** [comment]
@hensur Thank you very much.
I have test it with this command:
```
rclone ls od1:song/my.mp3
rclone copy od1:song/my.mp3 ./mylocal
```
Both command work fine with sharepiont.


**But this is another issue about rclone serve webdav with sharepiont:**

Normally,  use command "rclone copy  ./my.mp3  od1:song/" copy local file to remote,  it work fine like this:
```
DEBUG : HTTP REQUEST (req 0xc4203a2900)
DEBUG : PUT /personal/xxx_xxx_edu/Documents/song/my.mp3 HTTP/1.1
Host: xxx-my.sharepoint.com
User-Agent: rclone/v1.42-DEV
Content-Length: 3956946
Accept-Encoding: gzip

DEBUG : <<<<<<<<<<<<<<<<
DEBUG : HTTP RESPONSE (req 0xc420018400)
DEBUG : HTTP/1.1 201 CREATED
Content-Length: 0
Accept-Ranges: bytes
Cache-Control: private,max-age=0
Date: Fri, 03 Aug 2018 07:55:25 GMT
Etag: "{DF959FB6-F304-4973-AAC3-3D0A13DDFB01},1"
```

But use "rclone serve webdav --vfs-cache-mode writes  od1:song/ " as a webdav server,  in webdav client, i can't copy local file to it,  the rclone serve report error:
```
ERROR : my.mp3: Failed to copy: object not found
ERROR : my.mp3(0xc420087080): failed to transfer file from cache to remote: object not found
```
I dump headers:
```
DEBUG : HTTP REQUEST (req 0xc4202cf200)
DEBUG : PUT /personal/xxx_xxx_edu/Documents/song/my.mp3 HTTP/1.1
Host: xxx-my.sharepoint.com
User-Agent: rclone/v1.42-DEV
Content-Length: 0
DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<
DEBUG : HTTP RESPONSE (req 0xc4202cf200)
DEBUG : HTTP/1.1 200 OK
Transfer-Encoding: chunked

DEBUG : HTTP REQUEST (req 0xc4200eb200)
DEBUG : PROPFIND /personal/xxx_xxx_edu/Documents/song/my.mp3 HTTP/1.1
Host: xxx-my.sharepoint.com
User-Agent: rclone/v1.42-DEV
Depth: 0
DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<
DEBUG : HTTP RESPONSE (req 0xc4200eb200)
DEBUG : HTTP/1.1 404 NOT FOUND
```
   I test and found use "Content-Length: 0" in PUT header to sharepoint,  sharepoint just reponse "200 OK" and not really creating a file,  then use PROPFIND for new uploaded file, sharepoint just reponse "404 NOT FOUND" 

   **so only use "Content-Length:  size" with actual file size in PUT header, sharepoint will reponse "201 CREATED" and creating a file.**

   So what confuses me is why rclone use different Content-Length value  for same file 
 between different commands "rclone copy  ./my.mp3  od1:song/"  and "rclone serve webdav  od1:song/" ,   Is this a webdav serve problem ?  

   @ncw Do you have any ideas about this problem?

**Comment by ncw** [comment]
@hensur - excellent work!  Will take a look at the PR over the weekend (at  gopherconuk at the momen!)

**Comment by xiaolei0125** [comment]
@hensur，Your fix did solve my problem,  rclone command, such as ls, copy from local to sharepoint , or copy from sharepoint to local are work fine.

@ncw  There is another issue that can't upload file about rclone serve webdav(sharepoint) and windows 10 webclient(a built-in map network driver as webdav client),   But  some other webdav client  I have tested, are work fine with rclone serve webdav(sharepoint).

I think this issue has nothing to do with hensur's fix,  even with rclone serve webdav.  
I posted it here, just want to let more people know.

Run "rclone serve webdav --vfs-cache-mode writes od1:song/ " as a webdav server, 
Then map network driver(webdav)  in windows 10,  upload file to sharepoint failed: 
```
DEBUG : webdav root '': File to upload is small (0 bytes), uploading instead of streaming
DEBUG : HTTP REQUEST (req 0xc420660c00)
DEBUG : PUT /personal/xxx_xxx_edu/Documents/song/my.mp3 HTTP/1.1
Host: xxx-my.sharepoint.com
Content-Length: 0
DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<
DEBUG : HTTP RESPONSE (req 0xc420660c00)
DEBUG : HTTP/1.1 200 OK
Transfer-Encoding: chunked  
```
I test and found use "Content-Length: 0" in PUT header to sharepoint, sharepoint just reponse "200 OK" and not really creating a file, then use PROPFIND for new uploaded file, sharepoint just reponse "404 NOT FOUND" .  
So what confuses me is why windows 10 webdav client cause "rclone serve webdav" can't get file size?    

But use Android webdav client(ES FileExplore or Solid Explore) with rclone serve webdav,  it upload file 
 to sharepoint success, and rclone serve webdav can get file size normally.
```
DEBUG : webdav root '': Target remote doesn't support streaming uploads, creating temporary local FS to spool file
DEBUG : my.mp3: Sizes identical
DEBUG : HTTP REQUEST (req 0xc4202d0400)
DEBUG : PUT /personal/xxx_xxx_edu/Documents/song/my.mp3 HTTP/1.1
Host: xxx-my.sharepoint.com
Content-Length: 3898990
DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
DEBUG : HTTP RESPONSE (req 0xc4202d0400)
DEBUG : HTTP/1.1 201 CREATED
```

So only use "Content-Length: size" with actual file size in PUT header, sharepoint will reponse "201 CREATED" and creating a file success.

**Comment by ncw** [comment]
I've merged @hensur  's fix here

https://beta.rclone.org/v1.42-066-g1f3778db/ (uploaded in 15-30 mins)

Please give it a go and report back - thanks!

@xiaolei0125 - can you please make a [new issue on github](https://github.com/ncw/rclone/issues/new) with that info in and we can see about a fix - thanks.

**Comment by xiaolei0125** [comment]
@ncw  Thank for you merged hensur 's fix and build this beta version.

I have tested rclone v1.42-066-g1f3778db on windows and linux. 
Both are work fine with webdav(sharepiont), Thanks.

I already make a new issue for windows 10 webclent :
Failed to upload file to sharepoint(webdav) via Windows 10 webdav client #2441
