### ISSUE TITLE
Dropbox Upload Failure "invalid_account_type/feature"

### ISSUE THREAD

**Issue by xCryptic** [ncw/rclone#2427]
#### What is the problem you are having with rclone?
Dropbox Upload Failure

#### What is your rclone version (eg output from `rclone -V`)
rclone v1.42-062-gf72eade7β
- os/arch: linux/amd64
- go version: go1.10.1

(I also tried non-beta as well)

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
linux x64

####  Which cloud storage system are you using? (eg Google Drive)
Dropbox

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone -vv copy '/media/sdw1/cryptic/action.log' dbox:/'test'

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

```
2018/07/31 17:21:37 DEBUG : rclone: Version "v1.42-062-gf72eade7β" starting with
 parameters ["rclone" "-vv" "copy" "/media/sdw1/cryptic/action.log" "dbox:/test"]
2018/07/31 17:21:37 DEBUG : Using config file from "/media/sdw1/cryptic/.config$rclone/rclone.conf"
2018/07/31 17:21:38 DEBUG : Dropbox root 'test': Using root namespace "35016209$4"
2018/07/31 17:21:38 DEBUG : action.log: Couldn't find file - need to transfer
2018/07/31 17:21:39 ERROR : action.log: Failed to copy: upload failed: invalid_$ccount_type/feature/.
2018/07/31 17:21:39 ERROR : Attempt 1/3 failed with 1 errors and: upload failed$ invalid_account_type/feature/.
2018/07/31 17:21:39 DEBUG : action.log: Couldn't find file - need to transfer
2018/07/31 17:21:40 ERROR : action.log: Failed to copy: upload failed: invalid_$
ccount_type/feature/..
2018/07/31 17:21:40 ERROR : Attempt 2/3 failed with 1 errors and: upload failed$
 invalid_account_type/feature/..
2018/07/31 17:21:40 DEBUG : action.log: Couldn't find file - need to transfer
2018/07/31 17:21:40 ERROR : action.log: Failed to copy: upload failed: invalid_$
ccount_type/feature/
2018/07/31 17:21:40 ERROR : Attempt 3/3 failed with 1 errors and: upload failed$
 invalid_account_type/feature/
2018/07/31 17:21:40 Failed to copy: upload failed: invalid_account_type/feature$
```

For a little bit of background: I've been using rclone just fine for months now, and suddenly this error pops up. I can upload to the account just fine on the web version of dropbox. I can also download files using rclone just fine. Just uploading has that issue. I tested another account, and it works fine. I'd say this is an account issue, but it doesn't make sense if I can still upload on the web version and download using rclone...

One more thing I forgot to mention: this account has dropbox business.

**Comment by ncw** [comment]
Can you do a log with

    rclone --retries 1 --dump responses -vv copy '/media/sdw1/cryptic/action.log' dbox:/'test'

And post it please?

Hopefully that will shed a bit more light!

**Comment by xCryptic** [comment]
Actually this error is no longer persisting without any changes on my end. Oddly enough, after this happened, I now have to include my personal folder in dropbox in part of the upload/download directory. Before, it wasn't needed. As an example, it went from

`rclone -vv copy '/media/sdw1/cryptic/action.log' dbox:/'test'`
to
`rclone -vv copy '/media/sdw1/cryptic/action.log' dbox:/'dropbox name/test'`

My best guess is they modified some things in their api and it was throwing that error during that time for some reason.

**Comment by ncw** [comment]
Yes if you are using the `/` rooted method, then I'd expect a `test` folder in your personal folder to be at `dbox:/'dropbox name/test'` however you should be able to access your personal folder directly at `dbox:test`

Strange it should have worked at all - in my testing that didn't work ever...

**Comment by xCryptic** [comment]
Ok so I'm back with an update. It looks like this error is being caused by the account running out of API calls. I'm guessing they lowered the amount an account is allowed to have since I've never had this issue before. But, both times this has happened, I got an email saying I've used 80% of my API calls. They reset the 1st of every month, so that explains why it started working again on the 1st.

The reason why I thought it was a different issue is because the error message itself is ambiguous and there should be a different error message for API limits (plus the directory change).

**Comment by ncw** [comment]
That is a very strange message for running out of API calls...

I couldn't find it in any of Dropbox's docs either.

It might be worth adding a section to [the dropbox docs in the limitations section](https://github.com/ncw/rclone/blob/master/docs/content/dropbox.md#limitations) explaining the error message .

What do you think? Fancy sending a PR for that?

**Comment by xCryptic** [comment]
I managed to find it in dropbox's API. It's still quite vague though...

![img](https://i.imgur.com/hLxTIxx.png)

**Comment by diwakergupta** [comment]
@ncw @xCryptic yes, that's the expected behavior. I know the error code could be clearer. You can see the documentation here:

https://www.dropbox.com/developers/reference/data-transport-limit

**Comment by xCryptic** [comment]
So in that link, it says

```
API apps should avoid making unnecessary data transport calls. If using upload sessions, do not use an unnecessarily small chunk size. Using a small chunk size, i.e., the amount of data sent per call, will increase the number of data transport calls used.
```

Does more recent versions of rclone use smaller chunk sizes? I've been using an older version for the longest time and updated about a month or so ago.

And is there a way to increase chunk sizes so I won't run out too quickly? The majority of what I do is upload so it'd be really helpful.

**Comment by ncw** [comment]
> is there a way to increase chunk sizes so I won't run out too quickly? The majority of what I do is upload so it'd be really helpful.

You can use this flag.  Note that the chunks are buffered in memory so they can be retried.

      --dropbox-chunk-size SizeSuffix         Upload chunk size. Max 150M. (default 48M)

In previous versions of rclone it didn't buffer the chunks and it used a bigger value (128M) so I guess this might be making the difference.

**Comment by xCryptic** [comment]
Thanks. Is there a way to make it use 128mb default without having to use the flag?

**Comment by ncw** [comment]
> Thanks. Is there a way to make it use 128mb default without having to use the flag?

Sure... If you use [the latest beta](https://beta.rclone.org) then you can set it in the config file.  Reconfigure the remote and look in the advanced config.

(You can also set an environment variable).

**Comment by ncw** [comment]
I think we've got to the bottom of this, so I'm going to close it now
