### ISSUE TITLE
Feature Request: Support B2 application keys

### ISSUE THREAD

**Issue by stevesbrain** [ncw/rclone#2428]
Hey - since the release of the B2 [application keys](https://www.backblaze.com/b2/docs/application_keys.html), it would be great if rclone can support per-bucket keys! As far as I can tell, the only modification needed is to make the call to b2_list_buckets only try and list the bucket we're attempting to use:

> In an application key restricted to one bucket, listing buckets is only allowed if you provide the bucket's name or ID in the b2_list_buckets request. 
> https://www.backblaze.com/b2/docs/application_keys.html

As it stands currently, the following error occurs when attempting to perform an action with a single-bucket key:

```
$ rclone ls b2-api:/ -vv
2018/08/01 09:55:36 DEBUG : rclone: Version v1.42 starting with parameters [rclone ls b2-api:/ -vv]
2018/08/01 09:55:36 DEBUG : Using config file from /home/user/.config/rclone/rclone.conf
2018/08/01 09:55:38 DEBUG : B2 bucket : Unauthorized: Unknown 401  (401 unauthorized)
2018/08/01 09:55:38 DEBUG : pacer: Rate limited, increasing sleep to 20ms
2018/08/01 09:55:38 DEBUG : pacer: low level retry 1/10 (error Unknown 401  (401 unauthorized))
```
Rclone config is the same as when using master ID + key, except only using application key + ID instead. 

Thanks :)

**Comment by hit-xchvpit** [comment]
Second this one. Thought it was just some mistyped ID/key until I found this issue. Even created a second app key for testing but still the same result.

Remote tree listing test also throws an error, and possibly with every custom app key authentication:
```
$ rclone tree remote: -vv
2018/08/01 17:15:57 DEBUG : rclone: Version "v1.42" starting with parameters ["rclone" "tree" "remote:" "-vv"]
2018/08/01 17:16:06 DEBUG : Using config file from "/home/user/.config/rclone/rclone.conf"
2018/08/01 17:16:07 DEBUG : pacer: Rate limited, increasing sleep to 20ms
2018/08/01 17:16:07 DEBUG : pacer: low level retry 1/10 (error Invalid authorization (401 unauthorized))
2018/08/01 17:16:07 DEBUG : pacer: Rate limited, increasing sleep to 40ms
2018/08/01 17:16:07 DEBUG : pacer: low level retry 2/10 (error Invalid authorization (401 unauthorized))
2018/08/01 17:16:07 DEBUG : pacer: Rate limited, increasing sleep to 80ms
2018/08/01 17:16:07 DEBUG : pacer: low level retry 3/10 (error Invalid authorization (401 unauthorized))
...
2018/08/01 17:16:13 DEBUG : pacer: Rate limited, increasing sleep to 10.24s
2018/08/01 17:16:13 DEBUG : pacer: low level retry 10/10 (error Invalid authorization (401 unauthorized))
2018/08/01 17:16:13 Failed to create file system for "remote:": failed to authorize account: failed to authenticate: Invalid authorization (401 unauthorized)
```

**Comment by ncw** [comment]
I had an experiment with this...

Note that you need to put the `applicationKeyId` into the config as `account` - this will get over the 401 error you are seeing.

```
[b2]
type = b2
account = abcdef123456
key = 0014b7xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
endpoint = 

[b2app]
type = b2
account = 001abcdef1234560000000001
key = K001Xoxxxxxxxxxxxxxxxxxxxxxxxxx
endpoint = 
```

I've made a patch to limit the buckets to just the bucket in the key (if it is limited) and that seems to work quite well.

Can you give this a go?  I haven't updated the docs yet.  Having to substitute the  `applicationKeyId` as the `account` is going to need a bit of explaining in the docs and the configurator. 

https://beta.rclone.org/branch/v1.42-063-g7a17a804-fix-2428-b2-app-key/ (uploaded in 15-30 mins)

**Comment by hit-xchvpit** [comment]
Can confirm, works on app keys with limited buckets now on beta!

`applicationKeyId` is what I initially used but then it didn't seem work so I tried the master acc ID instead, though still to no avail earlier. It actually makes sense that the new specific `applicationKeyId` should be used instead of the main one for this feature.

Great work man, Thanks for the quick fix.

**Comment by stevesbrain** [comment]
@ncw Can confirm beta works as expected here - thanks so much for the quick turnaround on this :) Look forward to when this hits release :)

**Comment by ncw** [comment]
Great - thanks for testing :-)

I'll re-open this to remind me to write docs and merge to master!

**Comment by ncw** [comment]
I've added some docs and merged this to master now :-)

This will be in

https://beta.rclone.org/v1.42-068-ga119ca9f/ (uploaded in 15-30 mins)

and in [the latest beta](https://beta.rclone.org) from then and v1.43 when it is released.

**Comment by gslin** [comment]
I can use `rclone lsd` to list, but I cannot use `rclone copy` to upload file:

```
gslin@colo-sbd-1 [~] [08:38] rclone -vv copy ~/tmp/www.tar.gz gslin-b2:gslin-backup-colo-sbd-1/
2018/08/17 08:38:35 DEBUG : rclone: Version "v1.42-101-geb84b58dβ" starting with parameters ["rclone" "-vv" "copy" "/h
ome/gslin/tmp/www.tar.gz" "gslin-b2:gslin-backup-colo-sbd-1/"]
2018/08/17 08:38:35 DEBUG : Using config file from "/home/gslin/.config/rclone/rclone.conf"
2018/08/17 08:38:36 DEBUG : www.tar.gz: Couldn't find file - need to transfer
2018/08/17 08:38:36 DEBUG : B2 bucket gslin-backup-colo-sbd-1: Unauthorized: Unknown 401  (401 unauthorized)
2018/08/17 08:38:36 DEBUG : pacer: Rate limited, increasing sleep to 20ms
2018/08/17 08:38:36 DEBUG : pacer: low level retry 1/10 (error Unknown 401  (401 unauthorized))
2018/08/17 08:38:36 DEBUG : B2 bucket gslin-backup-colo-sbd-1: Unauthorized: Unknown 401  (401 unauthorized)
2018/08/17 08:38:36 DEBUG : pacer: Reducing sleep to 10ms
2018/08/17 08:38:36 DEBUG : pacer: Rate limited, increasing sleep to 20ms
```

```
gslin@colo-sbd-1 [~] [08:38] cat ~/.config/rclone/rclone.conf
[gslin-b2]
type = b2
account = 0012xxxxxxxxxxx0000000009
key = K001Xxxxxxxxxxxxxxxxxxxxxxxxxxx
```

**Comment by stevesbrain** [comment]
Silly question - but does that key have write permissions, and are those permissions for that bucket? :)

**Comment by gslin** [comment]
Yes:

![https://i.imgur.com/09H4isv.png](https://i.imgur.com/09H4isv.png)

**Comment by ncw** [comment]
I managed to replicate this with my test credentials.  Something must have changed at b2 since they were working fine....

I made a fix here - can you give it a go please?

https://beta.rclone.org/branch/v1.42-112-g7c911bf2-fix-2428-b2-app/ (uploaded in 15-30 mins)

Thanks

**Comment by gslin** [comment]
Yes, v1.42-112-g7c911bf2-fix-2428-b2-app is working, thanks :-)

**Comment by ncw** [comment]
Thanks for testing :-)

I've merged this to master now here

https://beta.rclone.org/v1.42-112-g7c911bf2/ (uploaded in 15-30 mins)

This will be in [the latest beta](https://beta.rclone.org) from now on and in 1.43

**Comment by andrekutianski** [comment]
For me works nicely with (and only) version 1.41

**Comment by striker-x** [comment]
Thank you!! Works perfectly here, version 1.42.

**Comment by joelifer** [comment]
Is this still working? I can't seem to get it going on 1.42 or 1.43 using the applicationKeyId as account. I've tried leaving key blank, using my master key, app key, account id and a fake value in the key field. Always returns a 401 unauthorized. What needs to be put under key if applicationKeyId is used for account?

**Comment by xaionaro** [comment]
I have the same problem. The same application ID and application Key works with restic. ID and key were copy&pasted (there's no typo).

**Comment by jackcaesar** [comment]
Is there any chance that this issue still occurs For macOS on version 1.48, could the fix not have been added for all OSs..?

I am having the exact symptoms described above (ability to ls the B2 remote, but getting unauthorised 401 exactly as above when trying to copy from the remote to local), yet am on version 1.48.

Using the rclone config from macOS I am also able to write files TO the B2 remote (from local or another remote). The only thing I cannot do is "download" (copy from) the files...

I then take the EXACT rclone config file from macOS and paste it on Ubuntu, and copy from (i.e download) works just fine (as does ls, copy to, etc).

Any ideas?

Thanks


From macOS 10.14.5:

rclone --version
rclone v1.48.0
- os/arch: darwin/amd64
- go version: go1.12.6

From Ubuntu 16.04:

rclone v1.48.0
- os/arch: linux/amd64
- go version: go1.12.6
