### ISSUE TITLE
Can't upload to Google Drive (Didn't find section in config file) error

### ISSUE THREAD

**Issue by lonerunner** [ncw/rclone#243]
I am trying to setup remote uploading some of the files from my server to Google Drive but i can't make it work nor on the server not on my own desktop pc. Both PC's are on linux, but once i have it all setup i get an error:

`Failed to create file system for "remote:backup": Didn't find section in config file`

I followed a guide from the website http://rclone.org/drive/ and everything went ok with config but once i try to upload a file:

`rclone copy /home/aleksandar/Pictures/background.jpg remote:backup`

i get an error as i described above. It's the same on both, my PC and my server.

**Comment by lonerunner** [comment]
Alright i get it, i misunderstood the docs.

In the docs you refer to the new remote as `name> remote`

And i named mine as `GoogleDrive`. Didn't paid attention to the guide carefully and i got the error.

So using it as a: `rclone copy /home/aleksandar/Pictures/background.jpg GoogleDrive:backup` all works fine.

By the way in the Docs there is a bit of difference than in setup. In selection of remote in the docs the list goes like

`What type of source is it?
Choose a number from below
 1) swift
 2) s3
 3) local
 4) drive
type> 4`

While in the configuration the list is a bit different and `drive` is number `2` now. I guess the doc's is not just updated to the latest list of remote drives, nothing problematic just mention it.

**Comment by ncw** [comment]
Thanks for the update; glad you got it working. You are right I don't keep those numbers up to date - perhaps I should.
