### ISSUE TITLE
Incorrect or missed Content-type based on file extension on move from local to Swift

### ISSUE THREAD

**Issue by tarik23** [ncw/rclone#2437]
#### What is the problem you are having with rclone?
Problem with setting correct Content-type to storage object on move command from machine with centOS 7 to Swift OpenStack.

File extension is mp4. Must have content-type video/mp4 on storage, but i have applilcation/octet-stream instead in result metadata. Therefore have problems with video players in browser. They need to get correct content-type

#### What is your rclone version (eg output from `rclone -V`)
rclone: Version “v1.42-056-g9c90b5e7β”

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
centOS 7, 64 bit

####  Which cloud storage system are you using? (eg Google Drive)
Swift OpenStack

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
[“rclone” “move” “/usr/records/st-ot -default_1533044441540_4fa6bbd0-94c7-11e8-a9b1-4108482fa2db.mp4” “swift-1:other- type-server-video-records/default” “–config” “/root/.config/rclone/rclone.conf” “-vv”]

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
2018/08/01 13:00:25 DEBUG : rclone: Version "v1.42-056-g9c90b5e7β" starting with                                                                       parameters ["rclone" "move" "/records/st-ot-                                                                      default_1533117530140_7b18b520-9571-11e8-bf57-e9d2024dba5c.mp4" "swift-1:other-t                                                                      ype-server-video-records/default" "--config" "/root/.config/rclone/rclone.conf"                                                                       "-vv"]
2018/08/01 13:00:25 DEBUG : Using config file from "/root/.config/rclone/rclone.                                                                      conf"
2018/08/01 13:00:26 DEBUG : st-ot-default_1533117530140_7b18b520-9571-11e8-bf57-                                                                      e9d2024dba5c.mp4: Couldn't find file - need to transfer
2018/08/01 13:00:26 INFO  : st-ot-default_1533117530140_7b18b520-9571-11e8-bf57-                                                                      e9d2024dba5c.mp4: Copied (new)
2018/08/01 13:00:26 INFO  : st-ot-default_1533117530140_7b18b520-9571-11e8-bf57-                                                                      e9d2024dba5c.mp4: Deleted
2018/08/01 13:00:26 INFO  :
Transferred:   9.018 MBytes (10.816 MBytes/s)
Errors:                 0
Checks:                 1
Transferred:            1
Elapsed time:       800ms

2018/08/01 13:00:26 DEBUG : 5 go routines active
2018/08/01 13:00:26 DEBUG : rclone: Version "v1.42-056-g9c90b5e7β" finishing wit                                                                      h parameters ["rclone" "move" "/records/st-ot                                                                      -default_1533117530140_7b18b520-9571-11e8-bf57-e9d2024dba5c.mp4" "swift-1:other-                                                                      type-server-video-records/default" "--config" "/root/.config/rclone/rclone.conf"                                                                       "-vv"]

Wrote 3 days ago at forum about this using question label. But now I think this is a real issue.
Sorry. Have no idea how to add label to my issue. Looks like not trivial action.

**Comment by ncw** [comment]
Sorry for the delay in responding, currently at a conference!

What do you see if you do this on an .mp4 file?

```
$ rclone lsf --csv -F pm rust.sh 
rust.sh,text/x-sh; charset=utf-8
```

rclone uses your system's Mimetypes when reading from local so these need to be set up correctly.

**Comment by tarik23** [comment]
command returns "application/octet-stream".
thanks for advice. tried to search how to change this, but no luck. is any suggestions how to change this?

**Comment by ncw** [comment]
Here is a walkthrough for how to do it for Redhat enterprise which should work on centos

https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/desktop_migration_and_administration_guide/file_formats

**Comment by tarik23** [comment]
Thanks for information. I have no gnome installed on the server machine and I found that video/mp4 is common mime type which one is already specified in default freedesktop.org.xml. I did the "update-mime-database /usr/share/mime" and all files uner that folder updated. 

I restarted machine, but still have "rclone lsf --csv -F pm myfile.mp4" as "application/octet-stream". 


I have "video/mp4" type in /usr/share/mime/type file

Tried another mp4 file - same result.

Is any other reason why rclone does not get iformation for mime type cache?

**Comment by ncw** [comment]
Rclone uses the go standard library to [look up mime types](https://golang.org/pkg/mime/#TypeByExtension).

> The built-in table is small but on unix it is augmented by the local system's mime.types file(s) if available under one or more of these names:
> 
> /etc/mime.types
> /etc/apache2/mime.types
> /etc/apache/mime.types

Do you have one of those files?  Does it have mp4 defined in it?

Here is what I see on Ubuntu

```
$ grep mp4 /etc/mime.types 
audio/mp4a-latm
video/mp4					mp4
video/mp4v-es
```

**Comment by tarik23** [comment]
I added new one mime.types file founded in the internet to /etc and now "rclone lsf --csv -F pm xxx.mp4" returns "video/mp4". 

I tested the Content-Type returned from OpenStack by http request from new copied files - now it is "video/mp4".

Problem solved. Thank you very much.

Another abstract question - why I had no mime.types file in my default centoOS 7 system...

**Comment by ncw** [comment]
> Problem solved. Thank you very much.

Great :-)

> Another abstract question - why I had no mime.types file in my default centoOS 7 system...

A good question, but not one I can answer! I don't have any experience with centos, just debian & ubuntu.
