### ISSUE TITLE
S3 Compatible (Aruba) - whitespace filename fail to copy with v2 Auth

### ISSUE THREAD

**Issue by gianlucacuomo** [ncw/rclone#2438]
#### What is the problem you are having with rclone?

rclone sync fail to copy on a S3 bucket when there are white spaces in filename or path

#### What is your rclone version (eg output from `rclone -V`)

rclone v1.42-065-gf9eb9c89β
- os/arch: linux/amd64
- go version: go1.10.1

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

Linux Ubuntu Server 18.04

####  Which cloud storage system are you using? (eg Google Drive)

Other S3 Compatible, (Aruba Object Storage, not compatible with v4 signature)

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

 rclone sync --ignore-existing /home/administrator/fileserver Aruba:backup.fileserver/fileserver

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
2018/08/03 15:54:06 DEBUG : rclone: Version "v1.42-065-gf9eb9c89β" starting with parameters ["rclone" "-vv" "sync" "--ignore-existing" "/home/administrator/fileserver" "Aruba:backup.fileserver/fileserver"]
2018/08/03 15:54:06 DEBUG : Using config file from "/home/administrator/.config/rclone/rclone.conf"
2018/08/03 15:54:06 DEBUG : Using v2 auth
2018/08/03 15:54:07 DEBUG : Condivisioni/.DS_Store: Destination exists, skipping
2018/08/03 15:54:37 ERROR : Condivisioni/ServerAmica/backup SQLserver 2000/IacpBilancio2005.bak: Failed to copy: SignatureDoesNotMatch: 
	status code: 403, request id: , host id: 
2018/08/03 15:56:01 INFO  : Condivisioni/ServerAmica/ServerAmica01/Canon_dr_3080c/DriveScanner/aec6712u/Utility/RESDEV.DLL: Copied (new)

**Comment by ncw** [comment]
I see you are using the v2 auth - does Aruba work with v4 auth?  I recommend using that if you can.

The v2 auth doesn't get used much.

Can you send the failing transaction with `-vv --dump bodies` please?

If you are having problem making v4 auth, probably the top tip is to leave the region blank.

**Comment by gianlucacuomo** [comment]
Sorry for the late answer.

Here's the requested transaction, I've also tried leaving the region blank but that doesn't resolve the issue :(

2018/08/20 13:56:26 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2018/08/20 13:56:26 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2018/08/20 13:56:26 DEBUG : HTTP REQUEST (req 0xc420283800)
2018/08/20 13:56:26 DEBUG : POST /backup.fileserver/fileserver/Condivisioni/cartellina%20fustellata%20piscinastore.it.eps?uploads= HTTP/1.1
Host: r1-it.storage.cloud.it
User-Agent: rclone/v1.42-065-gf9eb9c89β
Content-Length: 0
Authorization: XXXX
Content-Type: application/postscript
Date: Mon, 20 Aug 2018 13:56:26 UTC
X-Amz-Acl: private
X-Amz-Meta-Md5chksum: wqTz5XsBILlNgXsaJy6k5w==
X-Amz-Meta-Mtime: 1488194813
Accept-Encoding: gzip

2018/08/20 13:56:26 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2018/08/20 13:56:26 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2018/08/20 13:56:26 DEBUG : HTTP RESPONSE (req 0xc424ed0400)
2018/08/20 13:56:26 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2018/08/20 13:56:26 DEBUG : HTTP RESPONSE (req 0xc424ed0900)
2018/08/20 13:56:26 DEBUG : HTTP/1.1 403 Forbidden
Connection: close
Content-Length: 110
Cache-Control: no-cache
Content-Type: application/xml
Date: Mon, 20 Aug 2018 13:56:26 GMT
Server: RestServer/1.0

<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>SignatureDoesNotMatch</Code>
<Message></Message>
</Error>
2018/08/20 13:56:26 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2018/08/20 13:56:26 ERROR : Condivisioni/cartellina fustellata piscinastore.it copia.eps.zip: Failed to copy: SignatureDoesNotMatch: 
	status code: 403, request id: , host id: 
2018/08/20 13:56:26 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2018/08/20 13:56:26 DEBUG : HTTP RESPONSE (req 0xc424ed1100)
2018/08/20 13:56:26 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2018/08/20 13:56:26 DEBUG : HTTP RESPONSE (req 0xc424ed1400)
2018/08/20 13:56:26 DEBUG : HTTP/1.1 200 OK
Connection: close
Content-Length: 1422
Cache-Control: no-cache
Content-Type: application/xml
Date: Mon, 20 Aug 2018 13:56:26 GMT
Server: RestServer/1.0

**Comment by ncw** [comment]
Did the v4 auth work for files without spaces in the file name?

If so I'm kind of inclined to say that this is a bug in Aruba's S3 implementation.  Rclone works with a lot of S3 providers (AWS, Digital Ocean, Wasabi, IBM, Dreamhost, Minio...) and none of them have this problem with spaces in the file name.  Also rclone uses the [official maintained by AWS go SDK](https://github.com/aws/aws-sdk-go) which presumably does the signature calculation correctly.

I'll sign up for a trial account and see if I can work out what is happening.

**Comment by ncw** [comment]
> I can't even see the buckets list with v4 auth

The response indicates that v4 auth should work I think.

Are there any docs you can see?

Could you lend me access to your account?  I can't make the free trial work!

**Comment by scargr** [comment]
any development about it? I'm in the identical situation.
> The response indicates that v4 auth should work I think.
I set two remotes, onewith v2 and one with v4
rclone lsd remote_v4: gives "Failed to lsd: AuthMethodNotRecognized"
The one with v2 syncs perfectly except for filenames or directories with spaces

test/test dir/filename -> Failed to copy: SignatureDoesNotMatch
test/testdir/file name -> Failed to copy: SignatureDoesNotMatch
test/testdir/filename -> All OK

**Comment by gianlucacuomo** [comment]
I'm sorry, I couldn't keep on trying so I've opted for another solution

**Comment by ncw** [comment]
I managed to reproduce this with s3

```
$ echo "hello" | rclone rcat --s3-v2-auth "s3useast:rclone-test-useast/dir/file with space2.txt"
2018/10/09 11:35:23 ERROR : file with space2.txt: Failed to copy: SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your key and signing method.
	status code: 403, request id: 882D8CA9669576BB, host id: hKslnqX02qB2tqgb3xh4HoXgdcy1o9vg28mkT3RuC0GqKZ05WIaYwrNNUBWXXvYnXfV+cm04Hgw=
2018/10/09 11:35:23 Failed to rcat: SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your key and signing method.
	status code: 403, request id: 882D8CA9669576BB, host id: hKslnqX02qB2tqgb3xh4HoXgdcy1o9vg28mkT3RuC0GqKZ05WIaYwrNNUBWXXvYnXfV+cm04Hgw=
```

So it is a bug in the v2 signer...

I'll re-open this - @gianlucacuomo click unsubscribe if you dont wish to see notifications.

**Comment by ncw** [comment]
I fixed the v2 signer working with AWS - can you test it works with Aruba please?

https://beta.rclone.org/branch/v1.43-139-g87ef3cc6-fix-2438-s3-v2-sign-beta/ (uploaded in 15-30 mins)

Thanks

**Comment by scargr** [comment]
>  can you test it works with Aruba please?

Seems to work perfectly, but....why windows? :) cant' troubleshoot the right way on win

test/test dir/filename -> All OK
test/testdir/file name -> All OK
test/testdir/filename -> All OK

**Comment by ncw** [comment]
Thanks for testing  I've merged this to master now so it will be in [the latest beta](https://beta.rclone.org) in 15 mins and in the 1.44 release.
