### ISSUE TITLE
impossible to log on

### ISSUE THREAD

**Issue by ManuCart** [ncw/rclone#244]
Hello,
I work with ssh and it's not possible for me to log on to onedrive with this adress :
http://127.0.0.1:53682/auth
With older rclone version it was possible I think.
What can I do?

**Comment by ncw** [comment]
You are right - this has changed in recent-ish rclones to make the fully automatic process the default.

Which remote are you using?

With (for example) drive you can use the more manual process like this

```
Use auto config?
 * Say Y if not sure
 * Say N if you are working on a remote or headless machine or Y didn't work
y) Yes
n) No
y/n> N
If your browser doesn't open automatically go to the following link: https://accounts.google.com/o/oauth2/auth?client_id=20226481564...
```

That isn't possible with all the remotes though.

Failing that you can copy the config file - see [the second question in the FAQ](http://rclone.org/faq/) for details

**Comment by ManuCart** [comment]
I don't have the opion ````Use auto config```` when I doing ````rclone config```` for a one drive account

**Comment by ManuCart** [comment]
I just read your FAQ but the onedrive storage is a new target for me

**Comment by ncw** [comment]
With Onedrive there isn't a manual fallback for the auth (Microsoft don't support it) do you'll have to use the copy the config from another machine technique in the FAQ.

**Comment by ManuCart** [comment]
No it's a new config for onedrive

**Comment by ncw** [comment]
You will have to copy the config with OneDrive

**Comment by ncw** [comment]
Hopefully that got it working for you - please re-open if not!

Thanks

Nick
