### ISSUE TITLE
Failure to login in with certain accounts of mega

### ISSUE THREAD

**Issue by caspertone2003** [ncw/rclone#2443]
#### What is the problem you are having with rclone?
I am able to use rclone with mega with one account (account A) but not with another (acctount B).
I can login via web interface with account A and with account B.
But with account B I get <2018/08/05 12:16:18 Failed to create file system for "megaremotemachine:": couldn't login: Object (typically, node or user) not found>

#### What is your rclone version (eg output from `rclone -V`)
rclone-v1.42-windows-amd64.zip and some of 1.42 betas

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
W10 64

####  Which cloud storage system are you using? (eg Google Drive)
mega

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
just list the directory

rclone ls megaremotemachine: -vv --config remote.cnf

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

2018/08/05 12:16:18 Failed to create file system for "megaremotemachine:": couldn't login: Object (typically, node or user) not found

**Comment by ncw** [comment]
I have managed to verify this.

Could you try creating users with different lengths with passwords of different lengths and we can see if it is related to that?

**Comment by caspertone2003** [comment]
Will do. Need some time...

**Comment by caspertone2003** [comment]
I found it!
if in username (email address) at least a letter is written in CAPITAL... fails!

CT

**Comment by ncw** [comment]
Well done! That is a massive clue - thank you very much :-) (Apologies for the delay in responding I've been travelling).

In fact if you just lowercase the email in the rclone config the example you gave me will work!

So this looks like an easy fix - lowercase the email address.

A big of digging in the megacmd source code convinces me that it is the correct fix.  So I've fixed that in the source library here https://github.com/t3rm1n4l/go-mega/commit/854bf31d998b151cf5f94529c815bc4c67322949

And here is an rclone binary with that fix in - can you see if it works for you?

https://beta.rclone.org/branch/v1.42-108-ge5a8b2b6-fix-2452-mega-email/ (uploaded in 15-30 mins)

**Comment by caspertone2003** [comment]
Goes perfect!
While knowing the quirk it was not necessary, it is nice to have in handled.
Thanks for fixing it!
CT

**Comment by ncw** [comment]
@caspertone2003 great - thanks for testing.  I've merged that now

https://beta.rclone.org/v1.42-110-g6c5ccf26/ (uploaded in 15-30 mins)

It will be in [the latest beta](https://beta.rclone.org) from now on and in 1.43.

> Thanks for fixing it!

Actually you did all the hard work figuring out the problem for which I am very grateful - thank you :-)
