### ISSUE TITLE
Allow creation of backends from command line parameters

### ISSUE THREAD

**Issue by ncw** [ncw/rclone#2449]
Now we can specify all the backend config as command line parameters, it would be nice to have a way to create backends on the command line.

Say `--make-remote name=type` so `--make-remote dst=b2`. You can already so this with env variables so adding a command line flag for this would be easy I think.

You could then specify everything you need for a transfer on the command line

    rclone sync /path b2:bucket --make-remote b2=b2 --b2-account=12312312 --b2-key=12312123

Another idea was to use the special remote syntax `:type:path` eg `:b2:bucket` which would create a b2 remote using the command line parameters.  This is less typing, but less flexible as you wouldn't be able to configure two b2 remotes on the command line.  Eg

    rclone sync /path :+1: b2:bucket --b2-account=12312312 --b2-key=12312123

This would be very useful syntax for one off sftp or http remotes.

From [this thread](https://forum.rclone.org/t/can-rclone-be-run-solely-with-command-line-options-no-config-no-env-vars/6314/) in the forum.

**Comment by ncw** [comment]
Here is a beta with the `:type:` idea

https://beta.rclone.org/branch/v1.42-093-gd7c9abcf-fix-2449-create-backend/ (uploaded in 15-30 mins)

**Comment by ncw** [comment]
This is merged in

https://beta.rclone.org/v1.42-139-g502d8b0c/ (uploaded in 15-30 mins)

And will be in [the latest beta](https://beta.rclone.org) from now on and 1.43

**Comment by mir3z** [comment]
Is this feature documented somewhere? If it allows to create remote on the fly, then how to provide the rest of the configuration? If I'm providing token via env var to existing token - it works. If I'm doing the same but for remote created on the fly I got an error `empty token found - please run rclone config again`

**Comment by ncw** [comment]
There are some docs here: https://rclone.org/docs/#backend-path-to-dir

You can provide the config via command line options or via environment variables.

**Comment by ecthiender** [comment]
Hey all, (and @ncw ) ,

Is the `--make-remote` flag removed in recent versions? I cannot find it in the recent versions, and I could not find anything in the [changelog](https://rclone.org/changelog/) either about this.

**Comment by ncw** [comment]
@ecthiender checkout https://rclone.org/commands/rclone_config_create/ for creating backends programatically or use the `:backend:` syntax as described here: https://rclone.org/docs/#syntax-of-remote-paths

> I had this working with previous versions via the `--make-remote` flag,

I don't think the `--make-remote` flag ever got merged.

**Comment by ecthiender** [comment]
Thanks for replying! The `:backend:` will do the job for me. 

A minor concern, I have a script which uses rclone and recently it stopped working. And hence the comment above. Strange that you mention `--make-remote` never got merged, because my script uses `--make-remote` (and now it fails with no such flag error). FWIW, the script is 1-1.5 years old and use to work fine and used rclone from Arch Linux package repo. I don't run this script regularly hence I recently found out the error when I try to run it after a few months. Anyway, this is just a side not, and shouldn't concern you much.

**Comment by ncw** [comment]
> Strange that you mention `--make-remote` never got merged, because my script uses `--make-remote` (and now it fails with no such flag error).

I grepped the git log and the changelog - I don't think I ever merged or even implemented that flag which is odd! The commits attached to this issue all talk about the `:backend:` syntax which is a much better idea IMHO.

**Comment by cameronbraid** [comment]
How do you use this feature between two different s3 backends ?

**Comment by ncw** [comment]
> How do you use this feature between two different s3 backends ?

You have to make remotes - the on the fly syntax isn't powerful enough to deal with two backends of the same type. I had an idea to fix this with putting the config in the on the fly syntax so :s3,endpoint=blah,region=blah: but I haven't done that yet!

**Comment by rikhuijzer** [comment]
> @ecthiender checkout https://rclone.org/commands/rclone_config_create/ for creating backends programatically or use the `:backend:` syntax as described here: https://rclone.org/docs/#syntax-of-remote-paths
> 
> > I had this working with previous versions via the `--make-remote` flag,
> 
> I don't think the `--make-remote` flag ever got merged.

This is awesome! Exactly what I was looking for. Thanks, @ncw! I couldn't find this from https://forum.rclone.org/t/can-rclone-be-run-solely-with-command-line-options-no-config-no-env-vars/6314/5 and the topic is closed. Maybe you could save some people time by pointing to this issue from there?

**Comment by WillSquire** [comment]
Documentation on this was a real struggle for me. In the hopes this helps others, here’s an inline command to backup a DigitalOcean Spaces bucket locally to `./bucket`:

```sh
rclone sync \
    --s3-provider="DigitalOcean" \
    --s3-env-auth="false" \
    --s3-access-key-id=$STORAGE_ACCESS_KEY_ID \
    --s3-secret-access-key=$STORAGE_ACCESS_SECRET \
    --s3-endpoint=$STORAGE_ENDPOINT \
    --s3-acl=private \
    :s3:$STORAGE_BUCKET \
    “./bucket"
```

Replace the `$VARS` where appropriate. I’m not a fan of side-effect powdered code where it can be helped (i.e. `rclone.conf`), so making this more ‘functional’ was a deal breaker.

**Comment by narainaDewasi** [comment]
```shell
rclone sync \
    --s3-provider="DigitalOcean" \
    --s3-env-auth="false" \
    --s3-access-key-id=$STORAGE_ACCESS_KEY_ID \
    --s3-secret-access-key=$STORAGE_ACCESS_SECRET \
    --s3-endpoint=$STORAGE_ENDPOINT \
    --s3-acl=private \
    :s3:$STORAGE_BUCKET \
    “./bucket"
``` 

This is awesome! Exactly what I was looking for. Thanks, @WillSquire 

can you provide me the source of this command, nd also if there is same flags for google drive .
e.g. => --drive-access-token="sadfasf"

actually i dont want to keep my drive credentials in config file, thank you.

**Comment by miryam1003** [comment]
@WillSquire thank you for the detailed comment!

Do you know if there's a way to sync between 2 different s3 remotes, too?
I have 2 different s3 remotes that i want to sync between without using the rclone.conf file and i have no idea how to do that.. 
I've searched everywhere and this post was the closest solution to my issue.

**Comment by ncw** [comment]
@miryam1003 if you want to use two different remotes then you will need to use a [connection string](https://rclone.org/docs/#connection-strings) - if you need more help than that please ask [on the rclone forum](https://forum.rclone.org/) about this

Connection strings are the preferred way of doing this in modern rclone though the quoting rules can get a bit tricky.
