### ISSUE TITLE
Make Chocolatey package for rclone

### ISSUE THREAD

**Issue by timofonic** [ncw/rclone#245]
Hi.

Are there a possibility if rclone get into Chocolatey?

Kind regards.

**Comment by ncw** [comment]
Do you mean https://chocolatey.org/ ?  If so that doesn't seem to be a general purpose file storage system.  I may be misunderstanding though!  If you could post a link to any APIs you could find that would be useful.

Thanks

Nick

**Comment by zeshanb** [comment]
@ncw According to wiki (https://github.com/chocolatey/choco/wiki)
Chocolatey is a package manager for windows similar to how apt-get is used
on linux to install programs.

There is a self contained binary available on rClone website
http://rclone.org/downloads/. According to chocolatey wiki (
https://github.com/chocolatey/choco/wiki/CreatePackagesQuickStart) basic
example might work.

**Comment by timofonic** [comment]
Yes. Sorry for not explaining enough, I was in a hurry. 

Chocolatey becomes very handy when dealing with Windows, Mac really: Is a bit to nice a platform  to install and upgrade software compared with average Linux distributions. 

On December 10, 2015 5:47:06 PM CET, "Zeshan B." <notifications@github.com> wrote:
>@ncw According to wiki (https://github.com/chocolatey/choco/wiki)
>Chocolatey is a package manager for windows similar to how apt-get is
>used
>on linux to install programs.
>
>There is a self contained binary available on rClone website
>http://rclone.org/downloads/. According to chocolatey wiki (
>https://github.com/chocolatey/choco/wiki/CreatePackagesQuickStart)
>basic
>example might work.
>
>
>
>On Thu, Dec 10, 2015 at 7:53 AM Nick Craig-Wood
><notifications@github.com>
>wrote:
>
>> Do you mean https://chocolatey.org/ ? If so that doesn't seem to be a
>> general purpose file storage system. I may be misunderstanding
>though! If
>> you could post a link to any APIs you could find that would be
>useful.
>>
>> Thanks
>>
>> Nick
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/ncw/rclone/issues/245#issuecomment-163602815>.
>>
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/ncw/rclone/issues/245#issuecomment-163683939

-- 
Enviado desde mi dispositivo Android con K-9 Mail. Por favor disculpa mi brevedad.

**Comment by ncw** [comment]
Ah I see - you mean package rclone for Chocolatey.

Good idea!

This would be a perfect thing for someone to contribute to rclone, someone who  has used Choclatey before and who uses Windows.

**Comment by breunigs** [comment]
I believe there is such a package now: https://chocolatey.org/packages/rclone

**Comment by ncw** [comment]
Thanks @breunigs - I'll close this issue now.
