### ISSUE TITLE
Jottacloud: Upload without md5 no longer supported. Use header JMd5. (Bad Request)

### ISSUE THREAD

**Issue by olihey** [ncw/rclone#2462]
#### What is the problem you are having with rclone?
Get error "Upload without md5 no longer supported. Use header JMd5. (Bad Request)" when uploading files.
The weird thing is that I already copied over 1 TB of files into Jottacloud but suddenly these messages appeared.

#### What is your rclone version (eg output from `rclone -V`)
rclone/v1.42-099-g751bfd45β

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Linux arm64

####  Which cloud storage system are you using? (eg Google Drive)
Jottacloud 

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone sync genc:/fotos jenc:/fotos -v --stats=0m5s --transfers=12

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
`2018/08/14 10:18:59 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2018/08/14 10:18:59 DEBUG : HTTP REQUEST (req 0x44201c9100)
2018/08/14 10:18:59 DEBUG : POST /jfs/xxxxxx/Jotta/Archive/enc/rknteor33698etn6ep3ujak624/bs0m85n6307etaqsmlvvkmr0es/llat37i7b6f8ascc5af2edqbv8/fo858cksneeb9iao2sflh2ehuo/64c66d8s4ok9cena7mcoav68no?umode=nomultipart HTTP/1.1
Host: www.jottacloud.com
User-Agent: rclone/v1.42-099-g751bfd45β
Content-Length: 1094919
Authorization: XXXX
Content-Type: application/octet-stream
Jmodified: 2017-07-25-T05:19:08Z
Jsize: 1094919
Accept-Encoding: gzip

2018/08/14 10:18:59 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2018/08/14 10:19:00 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2018/08/14 10:19:00 DEBUG : HTTP RESPONSE (req 0x44201c9100)
2018/08/14 10:19:00 DEBUG : HTTP/1.1 400 Bad Request
Connection: close
Transfer-Encoding: chunked
Content-Type: text/xml
Date: Tue, 14 Aug 2018 10:18:59 GMT
Strict-Transport-Security: max-age= 31536000
X-Id: 941012035096
X-Resp: 124

2018/08/14 10:19:00 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2018/08/14 10:19:00 ERROR : alle/2007/1/07_150004_0.jpg: Failed to copy: Error 400: java.lang.IllegalArgumentException: Upload without md5 no longer supported. Use header JMd5. (Bad Request)
2018/08/14 10:19:00 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>`

**Comment by cvillabrille** [comment]
Same here,

- Linux ARM
- rclone v1.42-099-g751bfd45β
- os/arch: linux/arm
- go version: go1.10.1
- Kernel Linux dataRock64 4.4.126-rockchip-ayufan-239 #1 SMP Sun May 27 18:38:24 UTC 2018 aarch64 GNU/Linux
- Test were done with a 6.5Mb file.
- Mount options are: 
`/usr/bin/rclone mount --allow-other --config /etc/rclone.conf --transfers 20 --checkers 1 --timeout 240m --tpslimit 19 --tpslimit-burst 1 --attr-timeout 1m --low-level-retries 100 --log-file /data/duplicati_db/tmp/mount.opendrive.jotta --no-modtime --bwlimit 0 --contimeout 15s --retries 3 --stats 0 --timeout 30s dRock-Jotta:dataRock64/ /mnt/JottaCloud`


No matter if it's copying over the mount point...

> root@dataRock64:/data# cp timecapsule_berry.sqlite  /mnt/JottaCloud/
> 2018/08/14 14:15:18 ERROR : opendrive_timecapsule_berry.sqlite: Failed to copy: Error 400: java.lang.IllegalArgumentException: Upload without md5 no longer supported. Use header JMd5. (Bad Request)
> 2018/08/14 14:15:18 ERROR : timecapsule_berry.sqlite: WriteFileHandle.New Rcat failed: Error 400: java.lang.IllegalArgumentException: Upload without md5 no longer supported. Use header JMd5. (Bad Request)
> 2018/08/14 14:15:18 ERROR : timecapsule_berry.sqlite: WriteFileHandle.Flush error: Error 400: java.lang.IllegalArgumentException: Upload without md5 no longer supported. Use header JMd5. (Bad Request)
> cp: failed to close '/mnt/JottaCloud/opendrive_timecapsule_berry.sqlite': Input/output error


Or rclone copy/sync

```
rclone sync timecapsule_berry.sqlite  dRock-Jotta:dataRock64/ --stats 3s
rclone copy timecapsule_berry.sqlite  dRock-Jotta:dataRock64/ --stats 3s
```

> 2018/08/14 14:16:47 ERROR : timecapsule_berry.sqlite: Failed to copy: Error 400: java.lang.IllegalArgumentException: Upload without md5 no longer supported. Use header JMd5. (Bad Request)
> 2018/08/14 14:16:47 ERROR : Attempt 1/3 failed with 1 errors and: Error 400: java.lang.IllegalArgumentException: Upload without md5 no longer supported. Use header JMd5. (Bad Request)
> 2018/08/14 14:17:36 ERROR : Attempt 2/3 succeeded
> root@dataRock64:/data # 

In the end it shows "Attempt 2/3 succeeded", I have checked it through Jotta management web page and looks the file is there uploaded

Is that error (md5) something we need to be worry about?

**Comment by olihey** [comment]
> Is that error (md5) something we need to be worry about?

I don't think so. I assume Jottacloud wants to have the MD5 of the file before upload so it can verify the integrity of the file during upload. That's maybe problematic when you copy from one service to another and can't get the MD5 from the source file because you would need to download the entire file first and then calculate the MD5 before even start the upload 🤔

**Comment by cvillabrille** [comment]
Well, 

I have made another test.
Having this mount options done

` /usr/bin/rclone mount --allow-other --config /etc/rclone.conf --transfers 20 --checkers 1 --timeout 240m --tpslimit 19 --tpslimit-burst 1 --attr-timeout 1m --low-level-retries 100 --log-file /data/duplicati_db/tmp/mount.opendrive.jotta --no-modtime --bwlimit 0 --contimeout 15s --retries 3 --stats 0 --timeout 30s dRock-Jotta:dataRock64/ /mnt/JottaCloud`

I have initialized an storage repository for duplicacy (a way to fully test an upload)

```
# duplicacy init -e  -storage-name JottaCloud_rclone test_du /mnt/JottaCloud/duplicacy
Enter storage password for /mnt/JottaCloud/duplicacy:**************************
Re-enter storage password:**************************
/dataready/Videos/Videos_iPhone will be backed up to /mnt/JottaCloud/duplicacy with id test_dup
```

I have done an initial backup of 1.7G  with :

`duplicacy -v backup -stats -t nas -threads 60 -storage JottaCloud_rclone`

While I could achieve the _Ludicrous Speed_of 7.5 Mb/s...

> Uploaded chunk 338 size 9904874, 7.66MB/s 00:00:09 96.1%
> Uploaded chunk 292 size 4386552, 7.53MB/s 00:00:08 96.4%
> Uploaded chunk 263 size 7357673, 7.39MB/s 00:00:08 96.8%
> Uploaded chunk 308 size 4039785, 7.34MB/s 00:00:07 97.0%
> Listing snapshots/
> Listing snapshots/test_iphone/
> Listing chunks/
> Backup for /dataready/Videos/Videos_iPhone at revision 1 completed
> Files: 36 total, 1,672M bytes; 36 new, 1,672M bytes
> File chunks: 338 total, 1,672M bytes; 338 new, 1,672M bytes, 1,678M bytes uploaded
> Metadata chunks: 3 total, 55K bytes; 3 new, 55K bytes, 28K bytes uploaded
> All chunks: 341 total, 1,672M bytes; 341 new, 1,672M bytes, 1,678M bytes uploaded
> Total running time: 00:04:08


.. it was full of errors 

> 2018/08/14 14:50:51 ERROR : duplicacy/chunks/d4/123dea0b66bfbb7844eadc74029f182216240b15ed041a41e657867d8b8509.dyfahseu.tmp: Failed to copy: Error 400: java.lang.IllegalArgumentException: Upload without md5 no longer supported. Use header JMd5. (Bad Request)
> 2018/08/14 14:50:51 ERROR : duplicacy/chunks/d4/123dea0b66bfbb7844eadc74029f182216240b15ed041a41e657867d8b8509.dyfahseu.tmp: WriteFileHandle.New Rcat failed: Error 400: java.lang.IllegalArgumentException: Upload without md5 no longer supported. Use header JMd5. (Bad Request)
> 2018/08/14 14:50:51 ERROR : duplicacy/chunks/d4/123dea0b66bfbb7844eadc74029f182216240b15ed041a41e657867d8b8509.dyfahseu.tmp: WriteFileHandle.Flush error: Error 400: java.lang.IllegalArgumentException: Upload without md5 no longer supported. Use header JMd5. (Bad Request)

If I try to list any snapshot, there is no data

> $ duplicacy list -a -files -chunks -storage JottaCloud_rclone
> Storage set to /mnt/JottaCloud/duplicacy
> $


Actually, first time I tried to initialize the storage, it generated some errors for md5 causing the config file required for duplicacy to work, to do not exist.


>  $ duplicacy init -e  -storage-name JootaCloud_rclone test_iphone /mnt/JottaCloud/duplicacy/
> Enter storage password for /mnt/JottaCloud/duplicacy/:*********************
> Re-enter storage password:*********************
> 2018/08/14 14:42:18 ERROR : duplicacy/config.mzdqounq.tmp: Failed to copy: Error 400: java.lang.IllegalArgumentException: Upload without md5 no longer supported. Use header JMd5. (Bad Request)
> 2018/08/14 14:42:18 ERROR : duplicacy/config.mzdqounq.tmp: WriteFileHandle.New Rcat failed: Error 400: java.lang.IllegalArgumentException: Upload without md5 no longer supported. Use header JMd5. (Bad Request)
> 2018/08/14 14:42:18 ERROR : duplicacy/config.mzdqounq.tmp: WriteFileHandle.Flush error: Error 400: java.lang.IllegalArgumentException: Upload without md5 no longer supported. Use header JMd5. (Bad Request)

While on the second attempt, it worked.

I understand rcloen mount is yet under beta, however, I guess the errors are related to non-uploaded files. While I have seen with rclone sync/copy the attempts are re-tried... maybe it's worth to take a look to it. 

What do you think?

(thanks in advance for the JottaCloud implementation by the way)

**Comment by olihey** [comment]
Hehe, I think I have found the issue.

Here: https://github.com/ncw/rclone/blob/007c7757d434deaf53d8b969353d85843506456e/backend/jottacloud/jottacloud.go#L766

```
md5, err := src.Hash(hash.MD5)
if err != nil {
	opts.ExtraHeaders["JMd5"] = md5
	opts.Parameters.Set("cphash", md5)
}
```

The **NOT** equal is wrong, it should be equal **==**. Basically what it says now only set the `JMd5` header if we get an error 🤣 when it should be if the `src.Hash()` returns NO error set the header.

Can somebody please fix that I am not able to do this at the moment?

**Comment by olihey** [comment]
Okay, I added a pull request with a fix for this #2463 
BUT this only now works if a MD5 is available, meaning the source supports it. When for example copying files from an encrypted Google Drive to an encrypted Jottacloud still fails with the error.

Not sure how to handle this? One would have to download the file completely, decrypt, encrypt again, calculate the MD5 and upload it to Jottacloud. Sounds like a bad way to do this :(

**Comment by buengese** [comment]
Argh 🤦‍♂️. You are indeed right. I can probably fix cases where MD5 is not supported later but it won‘t be great.

**Comment by cvillabrille** [comment]
You rock!!,

Correct me if I am wrong but, if you plan to copy files from one cloud to another, you still have to download the file entirely to copy it, right?, hence, in parallel you can calculate the md5 for the already downloaded file before upload it to Jotta.

In regards of the MD5, this is how Jotta software works. Before uploading any file, it calculates the md5 of each and every file in the folder you choose to upload. Makes sense it is waiting for the same header for any software trying to upload files to Jotta.

Thanks a lot for finding the issue. Let's make more test when new version will be released.

**Comment by olihey** [comment]
Made a little test and tried setting the `JMd5` header but with an empty string and I get
```2018/08/14 17:29:43 ERROR : 2012/1/21_133522_0.arw: Failed to copy: Error 400: java.lang.IllegalArgumentException: Upload without md5 no longer supported. Use header JMd5. (Bad Request)```

So it seems that the MD5 is now a must for Jottacloud. I also saw the same as @cvillabrille that the client creates a checksum of every file before download.

@ncw: Does rclone already have something in store for cases like this where a backend requires a MD5 BEFORE upload?

**Comment by vb0** [comment]
Should this work for local->jotta (might sound stupid but is the src.Hash available for local)?

**Comment by olihey** [comment]
Yes, with the fix it‘s possible to upload from local. At least I tried it and it worked. Copying from other backends that provide a MD5 should also work. We are basically just screwed as soon as the crypt backend is used as this does not provide a MD5.

**Comment by jkaberg** [comment]
I guessing Jotta does a staged rollout of whatever they use for backend, thats why it still works for some uploads

**Comment by vb0** [comment]
Is there any workaround possible in the meantime to allow upload to crypt remote over jotta? Tried mounting the cleartext remote can't write files there. A cache remote wouldn't help either as far as I can tell.

**Comment by cvillabrille** [comment]
I have downloaded today the latest rclone-beta-latest-linux-arm.zip rclone v1.42-101-geb84b58dβ and tested the JottaCloud JMD5 issue which, as per below output, still persists....

With rclone only:

>  rclone copy IMG_9692.MOV  dRock-Jotta:dataRock64/ --stats 3s
> 2018/08/17 18:06:33 ERROR : IMG_9692.MOV: Failed to copy: Error 400: java.lang.IllegalArgumentException: Upload without md5 no longer supported. Use header JMd5. (Bad Request)
> 2018/08/17 18:06:33 ERROR : Attempt 1/3 failed with 1 errors and: Error 400: java.lang.IllegalArgumentException: Upload without md5 no longer supported. Use header JMd5. (Bad Request)
> 2018/08/17 18:06:35 ERROR : IMG_9692.MOV: Failed to copy: Error 400: java.lang.IllegalArgumentException: Upload without md5 no longer supported. Use header JMd5. (Bad Request)
> 2018/08/17 18:06:35 ERROR : Attempt 2/3 failed with 1 errors and: Error 400: java.lang.IllegalArgumentException: Upload without md5 no longer supported. Use header JMd5. (Bad Request)


Or with rclone mount using duplicacy...

> 2018/08/17 16:33:00 ERROR : duplicacy/chunks/c6/92a0cda7799029563f371f6b1e896120b67bdd27eb6bf31e771aa8fcd952d3.pfrsvwkh.tmp: Failed to copy: Error 400: java.lang.IllegalArgumentException: Upload without md5 no longer supported. Use header JMd5. (Bad Request)
> 2018/08/17 16:33:04 ERROR : duplicacy/chunks/c6/92a0cda7799029563f371f6b1e896120b67bdd27eb6bf31e771aa8fcd952d3.pfrsvwkh.tmp: WriteFileHandle.New Rcat failed: Error 400: java.lang.IllegalArgumentException: Upload without md5 no longer supported. Use header JMd5. (Bad Request)
> 2018/08/17 16:33:04 ERROR : duplicacy/chunks/c6/92a0cda7799029563f371f6b1e896120b67bdd27eb6bf31e771aa8fcd952d3.pfrsvwkh.tmp: WriteFileHandle.Flush error: Error 400: java.lang.IllegalArgumentException: Upload without md5 no longer supported. Use header JMd5. (Bad Request)
> 

I will wait for another rclone version to confirm whether the #2466 fix the issue.

Thanks @olihey for pushing this fix.

**Comment by cvillabrille** [comment]
I have tested during last two days the JottaCloud fix #2466 from @olihey with a direct mount and copy commands and, while the backup will take longer than the passed two days, I can conclude it has been a successful fix for the uploads running from local. I have uploaded around 500Gb with no issues. I could not test yet "cloning" any other cloud storage (google cloud, hubic, or any other to JottaCloud for instance), but at least the promised fix for the JMD5 header is working.

Much appreciated and well done. Be sure by the end of month I will contribute to "buy flowers (and other pretty things)" :)

Keep doing such a right things team.

**Comment by olihey** [comment]
I have been copying my 8 TB Google drive to Jotta cloud using the beta for the last days. It's working great, only the local caching required is a bit hard to handle. Had to increase the disk space for the VPS I am using to make sure I am not running out of disk space.

@ncw is it somehow possible for the jottecloud backend to figure out if a file is available locally. So if I do a sync from a local folder we could skip creating a copy locally and just create the MD5?

**Comment by ncw** [comment]
I've merged @olihey 's fixes into a branch and added a few of my own here - please test and report back!

https://beta.rclone.org/branch/v1.42-120-g86a21af4-fix-2462-jottacloud-md5/ (uploaded in 15-30 mins) (uploaded in 15-30 mins)

----

@olihey wrote:
>  is it somehow possible for the jottecloud backend to figure out if a file is available locally. So if I do a sync from a local folder we could skip creating a copy locally and just create the MD5?

If you are just copying from local then that is exactly what it will do.  However I think you are copying from crypt. It would in theory be possible for the `f.newObjectInfo(src)` passed here to support Hash() if crypt was wrapping something local.  It would have to read the file crypt then hash it which would be a little time consuming but probably cheaper than copying it.

https://github.com/ncw/rclone/blob/7712a0e111c7a37571f3fb796fe29dd9f44e5cfa/backend/crypt/crypt.go#L338

**Comment by vb0** [comment]
I'm testing rclone-v1.42-120-g86a21af4-fix-2462-jottacloud-md5β-linux-amd64, now I'm using --jottacloud-md5-memory-limit=1000M, nothing to report for some tens of GBs (I tested first with the default for some tens of GBs too).

Other than that I was using before an earlier (self) built with just the first simple fix, that worked too for about 1.5TBs...
Everything is sync local->crypt/jotta.

**Comment by cvillabrille** [comment]
Tested proposed version with some GBs through the mount option directly with Jotta. Source of data is duplicacy encrypted —> to Jotta through rclone mount

No issues yet.


From time to time rclone mount hungs (more or less after 4 hours uploading), but a restart on rclone process works like a charm and uploads continue normally. Rclone hungs are 100% sure not related to this fix.

Considered as a success fix.

**Comment by ncw** [comment]
Thanks for testing :-)

I've merged this to master here

https://beta.rclone.org/v1.42-123-gf9cf70e3/ (uploaded in 15-30 mins)

This fix will be in [the latest beta](https://beta.rclone.org) from now on and v1.43.

**Comment by cvillabrille** [comment]
Agree on closing.

Tested this morning with several Gbs with "rclone copy" option too. No issues at all. Everything uploaded with no error...

Thanks to both for the contribution. I will do mine. Be sure.
