### ISSUE TITLE
SWIFT, forcing storage_url in config not working

### ISSUE THREAD

**Issue by 131** [ncw/rclone#2464]
#### What is the problem you are having with rclone?
Forcing storage_url in rclone.conf (swift) is not working

#### What is your rclone version (eg output from `rclone -V`)
rclone v1.42
- os/arch: linux/amd64
- go version: go1.10.1

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Linux acsfrlt-j8shv32 4.4.0-43-Microsoft #1-Microsoft Wed Dec 31 14:42:53 PST 2014 x86_64 x86_64 x86_64 GNU/Linux

####  Which cloud storage system are you using? (eg Google Drive)
swift

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone ls remote:tmp

```
[remote]
type = swift
env_auth = false
auth_version = 3
auth = https://auth.cloud.ovh.net/v3/
endpoint_type = public
storage_url = <redacted>
tenant_domain = default
tenant = <redacted>
domain = default
user = <redacted>
key = <redacted>
region = GRA3

```
**Yet, using export OS_STORAGE_URL & OS_AUTH_TOKEN env vars from swift auth works fine.**

Is there something i'm missing ?

**Comment by 131** [comment]
```
me@laptop:/mnt/c/Users/fleurent $ rclone ls -vv --dump  headers remote:Anime
2018/08/14 19:36:19 DEBUG : rclone: Version "v1.42" starting with parameters ["rclone" "ls" "-vv" "--dump" "headers" "remote:Anime"]
2018/08/14 19:36:19 DEBUG : Using config file from "/home/ivs/.config/rclone/rclone.conf"
2018/08/14 19:36:19 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2018/08/14 19:36:19 DEBUG : HTTP REQUEST (req 0xc42039ef00)
2018/08/14 19:36:19 DEBUG : POST /v3/auth/tokens HTTP/1.1
2018/08/14 19:36:20 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2018/08/14 19:36:20 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2018/08/14 19:36:20 DEBUG : HTTP REQUEST (req 0xc4201c6000)
2018/08/14 19:36:20 DEBUG : GET /v1/<redacted no good NOT USING storage_url here>  /Anime?delimiter=%2F&format=json&limit=1000 HTTP/1.1

```

**Comment by ncw** [comment]
You need to put the `auth_token` in too otherwise rclone will use the (user, key) to fetch a new one which will override the storage url.

If you  use [the latest beta](https://beta.rclone.org) you can supply these on the command line too

      --swift-auth-token string               Auth Token from alternate authentication - optional (OS_AUTH_TOKEN)
      --swift-storage-url string              Storage URL - optional (OS_STORAGE_URL)

**Comment by ncw** [comment]
After studying the code a bit more, I think it is a bug and here is a potential fix - can you give it a go?

With this you should be able to supply auth_token or storage_url and rclone will fetch the missing one from the auth server.

https://beta.rclone.org/branch/v1.42-126-g577fcd31-fix-2464-swift-auth/ (uploaded in 15-30 mins)

**Comment by ncw** [comment]
This is merged in

https://beta.rclone.org/v1.42-139-g502d8b0c/ (uploaded in 15-30 mins)

And will be in [the latest beta](https://beta.rclone.org) from now on and 1.43
