### ISSUE TITLE
Add support for merging remotes

### ISSUE THREAD

**Issue by felixbrucker** [ncw/rclone#2467]
I use rclone to export remotes/part of remotes via the http serve command. This works quite well.
However my remotes use the same structure and just add content to it. As such it would be great to be able to export that as a single directory via http serve.

As of right now the only way to achieve this (at least that i know of) is to use the fuse mount option, use a 3rd party fuse based merge-fs like mergerfs etc, and then export that merged fuse mount. This is a lot of overhead and not working on machines without fuse support.

I searched the issues and there is one similar to this, but proposing to implement this via the fuse mount, which doesn't really improve the situation described above, i'll link it here for reference: https://github.com/ncw/rclone/issues/909

I know this probably is more work to do (and there exists a workaround mentioned above), so i'll leave it here and see if anybody wants to have this as well.

**Comment by vb0** [comment]
If I understand the request correctly this could be extremely useful in many cases. For example if you want to backup one large disk/folder to a couple (smaller) portable drives, a very common scenario for offline backups. You don't need to split the source, to take care what folders go on which drive, just connect the drives and let the software pick a place to put stuff on either drive.

**Comment by felixbrucker** [comment]
I thought more of a read-only approach to just export multiple remotes as a single directory structure which should be easier. However a way to write to such a merged remote could be done as well.

**Comment by ncw** [comment]
This would be best implemented as a remote which wraps other remotes.  You could read from all remotes, but only write to one of them.

You'd also want to define what happens when the same file is in all the backend remotes.

It doesn't sound too tricky - fancy having a go?

**Comment by vb0** [comment]
Write support (which isn't in the original scope of this issue, I didn't want to hijack it) is actually a little more complicated than writing just to one remote - it involves writing to any of the remotes if it involves an existing files you want to change. And this is not only for delete and move but also for copy when you want to overwrite existing files. We need probably to get some inspiration for all the corner cases from mergerfs or similar.

**Comment by felixbrucker** [comment]
@ncw Unfortunately i have never used go and looking at the code i don't understand much, so i'll pass.

However i'm putting up a bounty of 20$ via PayPal or BTC to get this implemented, everybody is welcome to implement this feature and claim the bounty.

**Comment by felixbrucker** [comment]
@ncw I took a deeper look at go and rclone and got it working read-only in a "make it work" fashion.

Some stuff i'm not sure about how to handle correctly are:

- parsing the remote list and validating it directly. For now i assume a comma separated list of remotes (`remote1:/,remote2:/` etc) which gets parsed in a string slice. I assume there is a better way?
- As a go novice i added functions copy pasta style from the http remote as its read-only as well and most just throw an `errorReadOnly` till my IDE didn't complain anymore.
- For now if some objects exist on multiple remotes the last remote overrides all others. While this isn't that bad, one might want the freshest object instead of the one defined by the remote ordering.
- Completely unsure about the `Features`, just left it the same as the http remote for now.

You can see the changes here: https://github.com/ncw/rclone/compare/master...felixbrucker:merge-remote

**Comment by ncw** [comment]
@felixbrucker - that sounds great!

> parsing the remote list and validating it directly. For now i assume a comma separated list of remotes (remote1:/,remote2:/ etc) which gets parsed in a string slice. I assume there is a better way?

The rclone config system isn't wildly sophisticated - it is key => value.  I see from your code you made a `RemoteList` type - that looks good.  I'd probably call it `CSV` or something like that as it is more general purpose that just a list of remotes.  There are also other places it could be used!  This should have a test.

> As a go novice i added functions copy pasta style from the http remote as its read-only as well and most just throw an errorReadOnly till my IDE didn't complain anymore.

:-)

> For now if some objects exist on multiple remotes the first/last remote overrides all others. While this isn't that bad, one might want the freshest object instead of the one defined by the remote ordering.

I'd say define what it does and we can change alter the behaviour with a config option later if we want.

> Completely unsure about the Features, just left it the same as the http remote for now.

The features should be an intersection of the optional features you implement and the features the backend(s) implement.  Here is how the crypt backend does it - you want something similar just over all the backends.

https://github.com/ncw/rclone/blob/6dc5aa74542d7b07714cd108f8452ebedcc73bf5/backend/crypt/crypt.go#L150-L159

> You can see the changes here: master...felixbrucker:merge-remote

I don't think that is up to date is it?

I was thinking about the name "merge".  I suspect that "union" might mean more to more people since we are doing what [unionfs](https://en.wikipedia.org/wiki/UnionFS) does - what do you think?

We need to think about some tests for the backend.  Normally backends run the integration test suite, but that only works for read/write backends.

**Comment by B4dM4n** [comment]
I also played around with a merge remote and came up with a list implementation for configuration like this:
https://play.golang.org/p/oxJ00DtdFBO

It has the advantage to support quoting and could be space separated, which looks a bit cleaner to me.

I think it should be put in the `fs/config` package since it's behavior is specific to the config system.

**Comment by ncw** [comment]
@B4dM4n - I like your `List` config.  I note that we could use this in the drive backend also.  My first thought was use the CSV parser too. Why don't you send a PR for that then it will be less for @felixbrucker to do.

**Comment by ncw** [comment]
@B4dM4n has done [fs.CommaSepList](https://godoc.org/github.com/ncw/rclone/fs#CommaSepList) and [fs.SpaceSepList](https://godoc.org/github.com/ncw/rclone/fs#SpaceSepList) which should make your life easier @felixbrucker

**Comment by felixbrucker** [comment]
Thanks, i'll have a look soon

**Comment by felixbrucker** [comment]
While testing some stuff i noticed at least the http remote does not throw a `fs.ErrorIsFile` error if the root is a file. How do you suggest to handle this scenario?

Example:
```
[drive-test]
type = drive
scope = drive.readonly
token = "..."

[http-test]
type = http
url = https://user:pass@somehost.com

[union-test]
type = union
remotes = drive-test:/http http-test:/
```

`rclone copy union-test:"/somedir/somefile.ext" "C:\Users\Felix\Desktop"`

In this example it'll create the drive remote which throws an `fs.ErrorIsFile` because the root is `drive-test:/http/somedir/somefile.ext`, however the http remote does not throw such an error and accepts the file root path. Currently i "forward" the `fs.ErrorIsFile` error at the end of the union fs creation so other commands like copy which rely on this info work. However now when trying to list the entries `dir` is set to `somefile.ext` while for drive this works as `root` is `drive-test:/http/somedir` for http it tries to stat `https://user:pass@somehost.com/somedir/somefile.ext/somefile.ext` which obviously does not work.

Suggestions?

I have committed my changes done so far here. https://github.com/felixbrucker/rclone/tree/merge-remote (the link posted previously will still work and is updated automatically)

**Comment by felixbrucker** [comment]
Additionally (unrelated) i think the features need to be populated with "support everything" before looping through all remotes to get the intersection. Right now i only create a new Features object which i believe has no support for anything enabled by default. Would i just enable all features manually in the constructor or is there a better way?

**Comment by ncw** [comment]
> While testing some stuff i noticed at least the http remote does not throw a fs.ErrorIsFile error if the root is a file. How do you suggest to handle this scenario?

Any thing that is integration tested will obey strict semantics.  However the http remote isn't integration tested as it isn't a read/write remote...  So I think you've found a bug, but I think it will be the only remote with that bug (cross fingers!).  Can you please make a [new issue on github](https://github.com/ncw/rclone/issues/new) about that and we can fix!

I think that what should happen is that if any of the merged remotes throw `fs.ErrorIsFile` then you should return that error and that remote immediately.  You don't need a union mount in this case as it will only be used to read one file.

> Additionally (unrelated) i think the features need to be populated with "support everything" before looping through all remotes to get the intersection. Right now i only create a new Features object which i believe has no support for anything enabled by default. Would i just enable all features manually in the constructor or is there a better way?

Here is what the crypt backend does.  The `Fill` fills in potential support by introspecting the methods.  The Mask then masks them off according to the wrappedFs support.

I think you want to call `Mask` one time for each of your union mounts.  I don't think you want to call `WrapsFs`.

```go
	// the features here are ones we could support, and they are
	// ANDed with the ones from wrappedFs
	f.features = (&fs.Features{
		CaseInsensitive:         cipher.NameEncryptionMode() == NameEncryptionOff,
		DuplicateFiles:          true,
		ReadMimeType:            false, // MimeTypes not supported with crypt
		WriteMimeType:           false,
		BucketBased:             true,
		CanHaveEmptyDirectories: true,
	}).Fill(f).Mask(wrappedFs).WrapsFs(f, wrappedFs)
```

**Comment by felixbrucker** [comment]
Thanks, created the issue here: https://github.com/ncw/rclone/issues/2489

>You don't need a union mount in this case as it will only be used to read one file.

Indeed, good catch!

> Here is what the crypt backend does. The Fill fills in potential support by introspecting the methods. The Mask then masks them off according to the wrappedFs support.

> I think you want to call Mask one time for each of your union mounts. I don't think you want to call WrapsFs.

Ah i see (hopefully), i'll change it accordingly

**Comment by felixbrucker** [comment]
I have submitted a WIP PR, where i also added write support by just passing these requests to the last remote. Is that sufficient?
Another thing i'm not sure about is docs: i should probably write up how union works and remove that part from the Description and/or Help text for the remote config option?

Another thing i noticed was when i added the union_test package in the same way as eg. drive uses it. The integration tests are skipped because no config file was found. On my windows machine i currently don't have make installed so i couldn't test if it was related to that, i just ran gotest from my ide (which also reported a total of 14 failed tests, 1563 passed tests and 1312 ignored tests, not sure if that should be like this).

**Comment by connesc** [comment]
This is very promising IMHO! :+1: 

As a possible extension, each member of the union could be prefixed with a kind of _mount point_. In other words, it would craft a virtual file hierarchy by aggregating multiple remotes. Overlapping sub-trees (if any), would still need the currently implemented behavior.

This would allow, for exemple, to expose multiple cloud storage through a single `rclone serve`. Or maybe to spread a local directory to multiple remotes through a single `rclone sync`.

**Comment by felixbrucker** [comment]
@connesc i'm not sure i can follow exactly, can you elaborate and/or show and example hierarchy?

**Comment by connesc** [comment]
@felixbrucker Yes you're right, this needs some clarification. But don't get me wrong, I don't want to add any work/delay for the first version of union remotes. This is just an open thinking. :innocent: 

Well, first, let's consider this hypothetical config:

```
[concrete1]
type = typeX
...

[concrete2]
type = typeY
...

[concrete3]
type = typeZ
...

[virtual]
type = union
remotes = concrete1:/foo concrete2:/bar@/bar concrete2:/baz@/baz/qux concrete3:/bar@/bar
```

I have arbitrary chosen to specify union members like this: `<remote name>:<remote path>[@<mount point>]`.

Then, let's consider the following content for concrete remotes (ie. non-union remotes):

```
concrete1:     concrete2:    concrete3:
  foo/           bar/          bar/
    item1          item3         item3
    item2          item5         item6
    bar/         baz/
      item3        item7
      item4        item8
                 qux/
                   item9
```

And now, this is how I would expect the `virtual` union to look like:

```
virtual:
  item1 (from concrete1:/foo/item1)
  item2 (from concrete1:/foo/item2)
  bar/
    item3 (from concrete3:/bar/item3, which overrides concrete2:/bar/item3, which overrides concrete1:/foo/bar/item3)
    item4 (from concrete1:/foo/bar/item4)
    item5 (from concrete2:/bar/item5)
    item6 (from concrete3:/bar/item6)
  baz/
    qux/
      item7 (from concrete2:/baz/item7)
      item8 (from concrete2:/baz/item8)
```

I guess this may look over-complicated, but I have chosen to cover several cases to provide more context. To help reasoning, this can be virtually seen as a succession of Unix `mount` commands, with the ability to traverse layers until the target file is found.

All of this is actually not far from [union mounting](https://en.wikipedia.org/wiki/Union_mount) (such as [OverlayFS](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/Documentation/filesystems/overlayfs.txt)). Implementing this here could probably be very powerful, while remaining rather lightweight.

Let me know if it makes more sense now :wink:

**Comment by felixbrucker** [comment]
Indeed, thanks for the detailed explanation!

Yeah, i'd assume it would be a little bit more work as i suppose i'd need to manage the (virtual) paths myself in the union fs. I like the concept of mounts, i'll take a look and see if i can make it work.

**Comment by felixbrucker** [comment]
@connesc i played around a little but at least for me it seems this involves more overhead than i expected, we could add it as a feature later on.

That being said i'll play around some more

**Comment by connesc** [comment]
@felixbrucker Of course, let's keep focus :wink: 

I hope I will have time to help with this in the following days.

**Comment by ErAzOr2k** [comment]
Thank you very much so far. This seems to be a great feature :)

Would it be possible to add extra parameters, which allows to rename or delete files on all merged remotes instead of just the write remote? With this, we would have something like a synchronisation between the remotes.

**Comment by felixbrucker** [comment]
@ErAzOr2k write support is experimental, i only did some test with copying to it, nothing more. AFAIK to support server side move/rename one needs the Mover interface implemented (which i currently do not). What someone could implement is the same walk/union logic currently used in `List` into all other kind of methods, including remove etc. Is that what you are referring to? Basically executing all operations on the exact same objects presented by the union?

I planned this remote as read-only initially as that's what i require, but for the testintegration's sake i added write support. Feel free to improve this as you please ;)

**Comment by vb0** [comment]
Yes, "proper" write support would be nice (albeit a little complicated to implement and bound to run into all kinds of corner cases if we have to reinvent the wheel and can't re-use some code from another project that already ironed out such issues). Otherwise probably we should have some warning about the write support that writes only to one remote because it will make it behave really strange: you could list files but not remove them (this would create serious problems for sync too), uploaded files won't overwrite existing files if they're on any other disk but the last one (and will take double the space in total) and so on.

**Comment by felixbrucker** [comment]
@vb0 Where would such a warning be best put?

i included a small paragraph in the docs, we should probably make that bold etc?
https://github.com/ncw/rclone/pull/2491/files#diff-171e6ef83db1aad50c1d859d10168943R21

**Comment by vb0** [comment]
I was thinking about a very short explanation/warning at run-time when defining the remote although I'm at a loss how to make it "pop" in a short phrase without going into a list of examples for what can go wrong.

**Comment by felixbrucker** [comment]
i already added it in the config creation, might not be "popping" enough, yeah

https://github.com/ncw/rclone/pull/2491/files#diff-171e6ef83db1aad50c1d859d10168943R102

**Comment by ErAzOr2k** [comment]
> Basically executing all operations on the exact same objects presented by the union?
Yes, this is exactly I thought of

**Comment by ncw** [comment]
@ErAzOr2k wrote:
> Would it be possible to add extra parameters, which allows to rename or delete files on all merged remotes instead of just the write remote? With this, we would have something like a synchronisation between the remotes.

I think that is a different remote, a RAID remote maybe?

**Comment by felixbrucker** [comment]
This is now available on master (https://github.com/ncw/rclone/commit/9e3ea3c6acbf1f427d82914ac8cc4ef91281ea8d), closing here

**Comment by vc7ee** [comment]
I'm also interested in "raid (0)" remote, if I copy to raid:, then in the background it copies/moves to both remote1: and remote2: That way I wouldn't need to have cron go against rate limits, when trying to do rclone copy remote1: remote2:
