### ISSUE TITLE
Google Drive: Corrupted on transfer

### ISSUE THREAD

**Issue by spiffytech** [ncw/rclone#247]
When syncing my Google Drive to my local hard disk, I get this error every time I attempt a sync. Interestingly, the reported different sizes stay the same across rclone runs.

```
2015/12/09 23:23:09 Local file system at /home/spiffytech/gdrive: Building file list
2015/12/09 23:23:09 Local file system at /home/spiffytech/gdrive: Waiting for checks to finish
2015/12/09 23:23:21 Google Photos/2015/11/2015-11-13.jpg: Corrupted on transfer: sizes differ 696383 vs 721229
2015/12/09 23:23:21 Google Photos/2015/11/2015-11-13.jpg: Failed to copy: lstat /home/spiffytech/gdrive/Google Photos/2015/11/2015-11-13.jpg: no such file or directory
2015/12/09 23:23:23 Google Photos/2015/02/2015-02-28.jpg: Corrupted on transfer: sizes differ 1918275 vs 1978386
2015/12/09 23:23:40 Local file system at /home/spiffytech/gdrive: Waiting for transfers to finish
2015/12/09 23:23:40 Google Photos/2013/02/IMG_20130216_135417.jpg: Corrupted on transfer: sizes differ 485372 vs 592856
2015/12/09 23:23:40 Google Photos/2013/02/IMG_20130216_135417.jpg: Failed to copy: lstat /home/spiffytech/gdrive/Google Photos/2013/02/IMG_20130216_135417.jpg: no such file or directory
2015/12/09 23:23:40 Local file system at /home/spiffytech/gdrive: Not deleting files as there were IO errors
2015/12/09 23:23:40 Attempt 1/3 failed with 5 errors
2015/12/09 23:23:40 Local file system at /home/spiffytech/gdrive: Building file list
2015/12/09 23:23:40 Local file system at /home/spiffytech/gdrive: Waiting for checks to finish
2015/12/09 23:23:42 Google Photos/2015/11/2015-11-13.jpg: Corrupted on transfer: sizes differ 512433 vs 708745
2015/12/09 23:23:42 Google Photos/2015/11/2015-11-13.jpg: Failed to copy: lstat /home/spiffytech/gdrive/Google Photos/2015/11/2015-11-13.jpg: no such file or directory
2015/12/09 23:23:43 Google Photos/2015/11/2015-11-13.jpg: Failed to copy: lstat /home/spiffytech/gdrive/Google Photos/2015/11/2015-11-13.jpg: no such file or directory
2015/12/09 23:23:43 Google Photos/2015/11/2015-11-13.jpg: Failed to copy: lstat /home/spiffytech/gdrive/Google Photos/2015/11/2015-11-13.jpg: no such file or directory
2015/12/09 23:24:05 Local file system at /home/spiffytech/gdrive: Waiting for transfers to finish
2015/12/09 23:24:05 Local file system at /home/spiffytech/gdrive: Not deleting files as there were IO errors
2015/12/09 23:24:05 Attempt 2/3 failed with 4 errors
2015/12/09 23:24:05 Local file system at /home/spiffytech/gdrive: Building file list
2015/12/09 23:24:05 Local file system at /home/spiffytech/gdrive: Waiting for checks to finish
2015/12/09 23:24:09 
Transferred:    197734483 Bytes (3200.92 kByte/s)
Errors:                 0
Checks:             10181
Transferred:          116
Elapsed time:      1m0.3s
Checking:
 * Google Photos/2014/09/IMG_20140907_125341491.jpg
 * Google Photos/2014/09/IMG_20140907_125453872_HDR.jpg
Transferring:
 * ...tos/2014/10/IMG_20141001_104220093_HDR.jpg:  7% done. avg: 6043.5, cur:    0.0 kByte/s. ETA: -
 * ...tos/2014/10/IMG_20141001_104434518_HDR.jpg: 20% done. avg: 3638.0, cur:    0.0 kByte/s. ETA: -
 * Google Photos/2014/10/IMG_20141001_104150978_HDR.jpg
 * Google Photos/2014/10/IMG_20141001_104203277_HDR.jpg

2015/12/09 23:24:20 Google Photos/2014/08/rwby_front.png: Corrupted on transfer: sizes differ 2958799 vs 3371822
2015/12/09 23:24:31 Local file system at /home/spiffytech/gdrive: Waiting for transfers to finish
2015/12/09 23:24:31 Local file system at /home/spiffytech/gdrive: Not deleting files as there were IO errors
2015/12/09 23:24:31 Attempt 3/3 failed with 1 errors

Transferred:    288221355 Bytes (3437.25 kByte/s)
Errors:                 1
Checks:             13945
Transferred:          156
Elapsed time:     1m21.8s
```

**Comment by ncw** [comment]
I suspect you have a duplicated file.  I've had a separate report of their being duplicates in "Google Photos".  Can you have a check in the web interface and see if there are two copies of that file?

Thanks

Nick

**Comment by spiffytech** [comment]
Confirmed, there are duplicate files with those filenames in google drive. 

What do you think is the solution here? It would be great if rclone gracefully handled this peculiar "feature" of Google Drive - maybe downloading the files to <filename>.1.jpg or something?

**Comment by ncw** [comment]
There has been a persistent problem with rclone uploading duplicates which I haven't fixed yet #28 However it looks like Google photos has the same problem when it uploads photos from a phone. This is kind of reassuring that Google have the same problem with drive too! 

As for downloading duplicates with a different name - that is possible. What I'd have to do is detect them in the drive directory listing code and alter the external name there. One would want a consistent mapping so appending the internal file id might be necessary. That might not work out though if rclone uploads a duplicate - it will keep uploading  the same file. 

I'll have a think. It might be that a deduplicate option for rclone is easiest all round. What would you think of that? It would manually ask you about the duplicates and could offer to rename them or delete all but one.

**Comment by ncw** [comment]
Certainly rclone should warn the user about duplicates better that the above message though!

**Comment by spiffytech** [comment]
The photos in my Google Photos with duplicate filenames are actually different photos, so deduplicating by filename wouldn't be appropriate - data would be lost if duplicates were deleted. Perhaps rclone could download all versions, then deduplicate by md5sum?

Downloading all duplicates, doing md5sum, discarding the dupes and renaming the uniques sounds like the safest path to me.

A nice-to have would be for an rclone push to fix the files in Google Drive after deduplication/renaming/whatever has happened on an rclone pull, so that my laptop and Drive match. Not sure if that behavior is part of what you mean by altering the external filenames in the Drive directory listing.

Re: manually asking: my preference would be for rclone to choose a safe default behavior that can be overridden by a command-line flag. That way Google's defective photo app won't stall my automated Google Drive syncs.

**Comment by ncw** [comment]
I've done the `rclone dedupe` command which should hep with this.

It isn't perfect but it will get better!

I'm going to close this ticket

**Comment by Darkvater** [comment]
I have the same issue when syncing from onedrive to google drive, however I have checked and there are not duplicates. Doesn't matter how often I try to sync some files simply will not appear. It seems to mostly happen with small file sizes? I will do another full sync and get you a list to confirm this theory. Using rclone 1.28

> 2016/03/17 23:31:38 goofs/new_trains_bug.png: Corrupted on transfer: sizes differ 126097 vs 68994
2016/03/17 23:31:38 goofs/new_trains_bug.png: Removing failed copy                                                                                           2016/03/17 23:31:39 server/images/13_lang.gif: Corrupted on transfer: sizes differ 677 vs 80
2016/03/17 23:31:39 server/images/13_lang.gif: Removing failed copy

**Comment by ncw** [comment]
@Darkvater if you are still having the problem, can you open a new ticket with a log (with `-v`) - thanks Nick

**Comment by Darkvater** [comment]
Yes, the problem still exists, let me open a new ticket
