### ISSUE TITLE
files uploaded to hubiC are not listed in the browser

### ISSUE THREAD

**Issue by claisan** [ncw/rclone#248]
I can use the rclone perfectly via terminal, but uploaded files do not appear when I access the hubiC by the browser (https://hubic.com/home/browser/#). It's like if they were hidden but there.

**Comment by claisan** [comment]
Sorry, I see my problem. HubiC has a folder called "default". I need send my files and folders to there if I want to see it in browser mode.

**Comment by barsanuphe** [comment]
you can also go to 
   https://hubic.com/home/browser/#containername/ 
then 
   https://hubic.com/home/browser/#containername
It should show your files. 
Yes, it's awful, but storage is cheap.

**Comment by claisan** [comment]
Yeah, this works too. I didn't know. Thanks!

**Comment by ncw** [comment]
Glad you got it sorted out.  Would a bit in the docs help here do you think?

**Comment by dibu28** [comment]
First time I've tried Hubic backend it was not obvious that I have to use "default" container to access files in hubic. And It is not mentioned in rclone docs. I've only found it in hubic api docs.

**Comment by barsanuphe** [comment]
You don't *have* to use the default container. It's just that your files will not show (easily) in the web interface or at all in the android app if you don't. But the files are there and can be accessed by other means, including of course rclone.

Maybe a quick word in the docs might save other people some time, though...

**Comment by rlapray** [comment]
I completely agree, I'm having this problem right now, and here I am browsing through closed tickets.

**Comment by ncw** [comment]
@rlapray fancy suggesting an update to the hubic docs?

**Comment by rlapray** [comment]
You're right : https://github.com/ncw/rclone/pull/503

**Comment by fredericofs** [comment]
How do you create a bucket outside "default" ? seems impossible to me...

**Comment by ncw** [comment]
rclone mkdir hubic:bucket

Should work when ovh fix hubic: http://status.ovh.co.uk/?do=details&id=12305

**Comment by komw** [comment]
I have the similar problem with rclone and hubic app. I'm uploading my files to default/some_directory bucket, and It is visible by browser app. I see all my files, and directories. But when I use a android app, I see only a some_directory directory, but it is empty. I've tried to use a desktop app, and windows application see that files. After synchronization on my windows app this files appears also in hubic android app. Of course I don't want to synchronize this files to my desktop to make it visible. Is there any other option?

**Comment by ncw** [comment]
@komw is this a specific problem with the android app?  Which one is it?

**Comment by komw** [comment]
It is hard to say is it a specific problem with this android apps, because all files is listed in web version, and files from official desktop app is also visible in android app. Only files from rclone are not visible in android app (maybe some permissions for those files?)
I'm using an official android hubic application.

**Comment by ncw** [comment]
@komw try creating a directory with the android app then uploading some files into it with rclone - does that work?

**Comment by komw** [comment]
The same situation. On the phone directory is empty, on web-browser I see my files.

**Comment by metal3d** [comment]
@komw  Copying on "default" bucket does the job. But that's right that's not trivial. I spent 1h to understand what I did bad.
You should do:

```
rclone sync Images Hubic:default/Images
```
I wonder if I can move bucket to bucket (I'm waiting my sync to finish, Hubic is slow) but I should be able to do:

```
rclone move Hubic:Images Hubic:default/Images
```

**Comment by ncw** [comment]
@metal3d moving from bucket to bucket should work fine
