### ISSUE TITLE
Mega - failure if public-private key creation" was not done.

### ISSUE THREAD

**Issue by caspertone2003** [ncw/rclone#2480]
Trying to list mega account size (using rclone browser and rclone1.42 branch), while the "Public - Private key creation" has not been done in mega, produces :

panic: runtime error: index out of range

goroutine 1 [running]:
github.com/ncw/rclone/vendor/github.com/t3rm1n4l/go-mega.getMPI(0x1816830, 0x0, 0x0, 0x1816830, 0x0, 0x0, 0x0)
	C:/gopath/src/github.com/ncw/rclone/vendor/github.com/t3rm1n4l/go-mega/utils.go:174 +0x126
github.com/ncw/rclone/vendor/github.com/t3rm1n4l/go-mega.decryptSessionId(0xc042299898, 0x0, 0x20, 0xc042299878, 0x0, 0x20, 0xc0423bf0e0, 0x10, 0x12, 0x1506a8, ...)
	C:/gopath/src/github.com/ncw/rclone/vendor/github.com/t3rm1n4l/go-mega/utils.go:244 +
0x154
github.com/ncw/rclone/vendor/github.com/t3rm1n4l/go-mega.(*Mega).Login(0xc04237e0e0, 0xc0420a29c7, 0x31, 0xc0423328e0, 0xf, 0x0, 0xc0420a6050)
	C:/gopath/src/github.com/ncw/rclone/vendor/github.com/t3rm1n4l/go-mega/mega.go:493 +0x4da
github.com/ncw/rclone/backend/mega.NewFs(0xc0420a6050, 0x47, 0xc0420a6050, 0x0, 0x11c3820, 0xc0423700c0, 0x0, 0x0, 0x0, 0x0)
	C:/gopath/src/github.com/ncw/rclone/backend/mega/mega.go:200 +0x5fb
github.com/ncw/rclone/fs.NewFs(0xc0420a6050, 0x48, 0xc04205d200, 0xc0420a6050, 0x47, 0xc0420a6050)
	C:/gopath/src/github.com/ncw/rclone/fs/fs.go:1002 +0xbc
github.com/ncw/rclone/cmd.NewFsFile(0xc0420a6050, 0x48, 0xc042360800, 0xc042368000, 0xc042299be0, 0x5e1bf7)
	C:/gopath/src/github.com/ncw/rclone/cmd/cmd.go:161 +0x99
github.com/ncw/rclone/cmd.newFsFileAddFilter(0xc0420a6050, 0x48, 0xc042299c98, 0xc0420ca800, 0xc042087d10, 0xc042299cc0)
	C:/gopath/src/github.com/ncw/rclone/cmd/cmd.go:179 +0x54
github.com/ncw/rclone/cmd.NewFsSrc(0xc042087dd0, 0x1, 0x3, 0xc042087dd0, 0x1)
	C:/gopath/src/github.com/ncw/rclone/cmd/cmd.go:201 +0x48
github.com/ncw/rclone/cmd/size.glob..func1(0x17e7f40, 0xc042087dd0, 0x1, 0x3)
	C:/gopath/src/github.com/ncw/rclone/cmd/size/size.go:26 +0x88
github.com/ncw/rclone/vendor/github.com/spf13/cobra.(*Command).execute(0x17e7f40, 0xc042087d10, 0x3, 0x3, 0x17e7f40, 0xc042087d10)
	C:/gopath/src/github.com/ncw/rclone/vendor/github.com/spf13/cobra/command.go:766 +0x2c8
github.com/ncw/rclone/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x17dfa40, 0x0, 0x0, 0x0)
	C:/gopath/src/github.com/ncw/rclone/vendor/github.com/spf13/cobra/command.go:852 +0x311
github.com/ncw/rclone/vendor/github.com/spf13/cobra.(*Command).Execute(0x17dfa40, 0x0, 0x17e88c0)
	C:/gopath/src/github.com/ncw/rclone/vendor/github.com/spf13/cobra/command.go:800 +0x32
github.com/ncw/rclone/cmd.Main()
	C:/gopath/src/github.com/ncw/rclone/cmd/cmd.go:545 +0x3d
main.main()
	C:/gopath/src/github.com/ncw/rclone/rclone.go:14 +0x27

It is normal that it is unable to get the information or to work properly, but perhaps failure can be avoided and information provided about the error...

Thanks,
CT

**Comment by ncw** [comment]
This is a bug in t3rm1n4l/go-mega. It isn't checking its errors, so it needs something like this

```diff
diff --git a/utils.go b/utils.go
index 959dc5d..7f2e4ae 100644
--- a/utils.go
+++ b/utils.go
@@ -9,6 +9,7 @@ import (
 	"encoding/binary"
 	"encoding/json"
 	"errors"
+	"fmt"
 	"math/big"
 	"net"
 	"net/http"
@@ -79,7 +80,7 @@ func base64urlencode(b []byte) []byte {
 
 // base64urldecode decodes the byte slice b using base64 url decoding.
 // It adds required '=' padding before decoding.
-func base64urldecode(b []byte) []byte {
+func base64urldecode(b []byte) ([]byte, error) {
 	enc := base64.URLEncoding
 	padSize := 4 - len(b)%4
 
@@ -92,8 +93,11 @@ func base64urldecode(b []byte) []byte {
 
 	decSize := enc.DecodedLen(len(b))
 	buf := make([]byte, decSize)
-	n, _ := enc.Decode(buf, b)
-	return buf[:n]
+	n, err := enc.Decode(buf, b)
+	if err != nil {
+		return nil, fmt.Errorf("Failed to base64urldecode(%q): %v", b, err)
+	}
+	return buf[:n], nil
 }
 
 // base64_to_a32 converts base64 encoded byte slice b to uint32 slice.
```

And the errors rippled up.

Do you know why the bug happened - is it repeatable?

**Comment by caspertone2003** [comment]
Create a mega account or use one available which you can delete its contents
Ensure you can log in via web. Logout.
Follow in the web the "I forgot password procedure" Do not log in via browser at the end.
Try with rclone. Breaks.
Then, log in via web. You will see the message "creating encryption key" or alike.
Logout.
Now try with rclone. Success.

**Comment by ncw** [comment]
Thanks for the explanation.  I'll fix the go-mega library and write some stuff in the rclone docs - unless you wanted to send a PR to patch

**Comment by caspertone2003** [comment]
feel free...
i am unable to propose a patch...
