### ISSUE TITLE
Can't rename google drive document when doing rclone dedupe

### ISSUE THREAD

**Issue by snoringcat** [ncw/rclone#2483]
#### What is the problem you are having with rclone?
i cannot rename files when using dedupe command on remote Google Drive.

#### What is your rclone version (eg output from `rclone -V`)

1.42
#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
freebsd

####  Which cloud storage system are you using? (eg Google Drive)
Google drive

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone dedupe mydrive:
and then : 
r) Rename all to be different

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

2018/08/23 14:00:08 ERROR : TEST.docx: Failed to rename: can't move a Google document

**Comment by B4dM4n** [comment]
This already covered by #2479.

When it's merged documents can be renamed without problems. The only limitation will be that the file extension has to be the same, but dedupe will do this.

**Comment by B4dM4n** [comment]
There has been progress for this issue:
#2479 is a work in progress rewrite of the drive documents handling. 
If anyone wants to help testing the new implementation, there is a beta branch containing the changes: 
https://beta.rclone.org/branch/v1.42-162-g6a66967c-drive-documents/

**Keep in mind this is not tested thoroughly yet and therefore be considered experimental.**

Please post any feedback in #2479. Updated releases will also be anounced there.

**Comment by B4dM4n** [comment]
#2479 has been merged lately.

This issue should be fixed since https://beta.rclone.org/v1.43-112-ga20fae03-beta/, the [latest beta](https://beta.rclone.org/) and in v1.44
