### ISSUE TITLE
S3 sync returning weird "method not allowed" - 405 error

### ISSUE THREAD

**Issue by dfduarte** [ncw/rclone#2484]
#### What is the problem you are having with rclone?
405 errors - Method not allowed when syncronizing from local to aws

#### What is your rclone version (eg output from `rclone -V`)
rclone v1.42
- os/arch: linux/amd64
- go version: go1.10.1

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Linux Shelly 4.15.0-32-generic #35~16.04.1-Ubuntu SMP Fri Aug 10 21:54:34 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

####  Which cloud storage system are you using? (eg Google Drive)
AWS S3

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
`rclone sync local:/home/diego/storages/Dropbox AWS:/dduarte-remote-sync/Dropbox/ -vv` 

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

$ rclone sync local:/home/diego/storages/Dropbox AWS:/dduarte-remote-sync/Dropbox/ -vv
2018/08/24 00:18:38 DEBUG : rclone: Version "v1.42" starting with parameters ["rclone" "sync" "local:/home/diego/storages/Dropbox" "AWS:/dduarte-remote-sync/Dropbox/" "-vv"]
2018/08/24 00:18:38 DEBUG : Using config file from "/home/diego/.config/rclone/rclone.conf"
2018/08/24 00:18:39 ERROR : Keys.zip: Failed to copy: MethodNotAllowed: Method Not Allowed
	status code: 405, request id: 295B286C9DA33818, host id: wksupYff+4XBd37lLq2pVYgla8c5XIj1rAh7NVv5KWUkgJGJlczanVFaKW1B0BHW/mP+O1nNh4o=
2018/08/24 00:18:39 ERROR : 1_continuous-integration-improving-software-quality-and-reducing-risk-the-addison-wesley-signature-series.9780321336385.28309.pdf: Failed to copy: MethodNotAllowed: Method Not Allowed
	status code: 405, request id: 5A2C3B7BA2CD44E6, host id: iciezfafloAqtcCo9JHbfu1rKu34Uj7brXNf0xK7h3Cfy/mrfx5Cj3VpMUwDjVOO1SwUy/sODLY=
2018/08/24 00:18:40 ERROR : Business Result Upper Intermediate Student's book (1).pdf: Failed to copy: MethodNotAllowed: Method Not Allowed
	status code: 405, request id: EC054B2545C1F8C0, host id: wc3ReaPS0qNSKrlxMaO1a2rJ+jw2JfnmSkDaCHr4P6TvRPmbQHn5j7wqRW1YxYs/dnzym8HKo1c=
2018/08/24 00:18:40 ERROR : ENGLISH PRONUNCIATION FOR BRAZILIANS.pdf: Failed to copy: MethodNotAllowed: Method Not Allowed
	status code: 405, request id: B02062933F221E69, host id: AUJHebnaJYUaU6OctSul6jWpbxzpEwNpkP6GrKA1RcylOHYqcysBdLqADu5CnQv7g6D/wKLzHbw=
2018/08/24 00:18:40 ERROR : OneDrive_GetStarted (1).pdf: Failed to copy: MethodNotAllowed: Method Not Allowed
	status code: 405, request id: 6522148119C1289F, host id: wil8uh+htWiOgFl+pRIgKTgjKkV+2AbC5zzT0YAHTiuGfmWPDjJ8HDPOwNd070IYz50EIHHbIUI=
2018/08/24 00:18:40 ERROR : OneDrive_GetStarted.pdf: Failed to copy: MethodNotAllowed: Method Not Allowed
	status code: 405, request id: C9924D6958D4E7F1, host id: EiSni3NO8G9Rw4OpdHRgMBwMCMBCCNpd+dxEWGEifFJqwRPuJTUkJ/QKvOFc6T3pUx8XiKn9Vh4=
2018/08/24 00:18:40 ERROR : Photo on 3-23-17 at 4.57 PM #2.jpg: Failed to copy: MethodNotAllowed: Method Not Allowed
	status code: 405, request id: 8CE150BC3E4E8F35, host id: 1urhF3NjaDmxndP1mFfFTo6CC4W4v35d0Oxv1Ug6omX9d1JyWeVkopLm79S+3emAybwBzfV29+E=
2018/08/24 00:18:40 ERROR : ac-vpc.zip: Failed to copy: MethodNotAllowed: Method Not Allowed
	status code: 405, request id: CF1A89900FEA8323, host id: 7h3vjT/rfLIymAm/hwIGqPQ0D8naguCBddZLFYIsJsmBIurGrFhkFWMTqs7OvT3y7SvFBCf92Bc=
2018/08/24 00:18:41 ERROR : nat-backup.zip: Failed to copy: MethodNotAllowed: Method Not Allowed
	status code: 405, request id: 4085B78AEB05EBD7, host id: ZI4yiDhK/JaTkOVsUD45qmv9AmVhA/g49rAMs6VEq3bZzR03S0M7AVb5iUcKly62/s4T+rlyt3M=
^C
================SNIP HERE==================

**Comment by ncw** [comment]
I think if you change `AWS:/dduarte-remote-sync/Dropbox/` to `AWS:dduarte-remote-sync/Dropbox/`, ie drop the slash before the bucket name, I think it will work.

I think this is a bug in rclone!

**Comment by dfduarte** [comment]
@ncw It worked after removing the slash `/`, thanks. Also, just noticed that the documentation states this too. I didn't notice because I assumed that was similar to some other endpoints, and like the s3 uri (s3://).

I'll close this since this is not necessary. Sorry for the bugging.

**Comment by diegofduarte** [comment]
Thanks for the kind help @ncw . I'll test it when possible

**Comment by dfduarte** [comment]
Thanks for the kind help @ncw . I'll test it when possible
