### ISSUE TITLE
http remote does not throw `fs.ErrorIsFile`

### ISSUE THREAD

**Issue by felixbrucker** [ncw/rclone#2489]
#### What is the problem you are having with rclone?
Currently if there is a file called on a http remote with eg. the copy command there is no `fs.ErrorIsFile` error created like with (all) other remotes.

#### What is your rclone version (eg output from `rclone -V`)
Current master (1.42)

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
windows 8.1 x64

####  Which cloud storage system are you using? (eg Google Drive)
http

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
`rclone copy http-test:"/somedir/somefile.ext" "C:\Users\Felix\Desktop"`

**Comment by ncw** [comment]
Thanks for reporting.  This is probably quite easy, along with a test :-)

**Comment by ncw** [comment]
I'm having trouble replicating this...

```
$ rclone config show httptest
--------------------
[httptest]
type = http
url = https://downloads.rclone.org/
--------------------
```

```
$ rclone copy httptest:v1.42/version.txt /tmp
$ rm /tmp/version.txt 
$ rclone copy httptest:/v1.42/version.txt /tmp
$
```
@felixbrucker - can you help?

**Comment by felixbrucker** [comment]
Indeed, it is working as expected, i must have messed things up while toying around with the union remote. It doesn't return the error if the file/dir does not exist, but that is fine. I guess i though the file had to be on the http remote while it was on some other remote actually.

**Comment by ncw** [comment]
I see.  Yes you only get the error if the file exists.  No worries!
