### ISSUE TITLE
Recursion not working?

### ISSUE THREAD

**Issue by guestisp** [ncw/rclone#2492]
I'm trying to sync multiple dirs to a remote S3 bucket.

this is what I have:
```
# cat /tmp/backuplist 
/var/www/*
/var/spool/backups/*
/etc/*
```

and this is the executed command:
`rclone sync --include-from /tmp/backuplist / amazon_s3:mybucket`

This should clone starting from `/` but including only what I've wrote in `/tmp/backuplist`

Currently, only the first level of `/etc/` is synced or a `.bash_history` file in `/var/www`

Am I miss something ?
What I'm trying to get is a daily (or multiple times per day, maybe once per hours), rotated, backup made with choosen directory (I don't need to sync the whole server, I have many snapshots for that)

**Comment by B4dM4n** [comment]
To include everything below a directory `**` has to be used. `*` only matches one path component (one directory level).

In your case this would mean:
```
/var/www/**
/var/spool/backups/**
/etc/**
```

**Comment by ncw** [comment]
@B4dM4n I've been thinking of changing the filtering so a thing with a trailing slash "dir/" means "dir/**" - this might generate less issues of this type?

**Comment by guestisp** [comment]
@ncw absolutely. +1

**Comment by B4dM4n** [comment]
That sounds reasonable.

There shouldn't be any interference with existing filters, since a `dir/` does not include any files currently.

**Comment by ncw** [comment]
OK I'm going to close this issue and I've written the filter/ thing on the list!
