### ISSUE TITLE
Unable to change permission to 777

### ISSUE THREAD

**Issue by ZeusGamingPlay** [ncw/rclone#2496]
When i'am trying to mount a onedrive business plan account to my VPS (for free picture hosting service with chevereto),it turned out to be a problem is that the chevereto requires all folders to be 0777 root:root.But after mounting, the 'image' folder became a 0755 and could not be switched back,what the hell...

**Comment by ZeusGamingPlay** [comment]
hmm...i tried again with nohup to keep rclone running but it turned out to be this...
`2018/08/30 09:46:36 Failed to create file system for "onedrive:/chevereto": failed to get root: activityLimitReached: throttledRequest: The request has been throttled`

**Comment by B4dM4n** [comment]
This error could be the same as #2406.

To test the file permissions, you can also use a local directory as a test remote:
```
rclone mount --umask=0 /tmp/test_remote /mnt/temp
```
The file permissions will be the same as for a cloud remote.

**Comment by B4dM4n** [comment]
I'm closing this issue since the problem should be resolved.

Feel free to reopen this or create a new issue if the problem persists.
