### ISSUE TITLE
one driver error in china  business account

### ISSUE THREAD

**Issue by miewx** [ncw/rclone#2500]
i use rclone authorize "onedrive", and change https://login.microsoftonline.cn to https://login.partner.microsoftonline.cn 

`

https://login.partner.microsoftonline.cn/common/oauth2/authorize?access_type=offline&client_id=52857fec-4bc2-483f-9f1b-5fe28e97532c&redirect_uri=http%3A%2F%2Flocalhost%3A53682%2F&resource=https%3A%2F%2Fapi.office.com%2Fdiscovery%2F&response_type=code&state=f2afd001507a071e79df76bae0691fc5
`
but show error

AADSTS70001: Application with identifier '52857fec-4bc2-483f-9f1b-5fe28e97532c' was not found in the directory 2f4cdd30-8012-4252-ae54-c5a5854df1be

![image](https://user-images.githubusercontent.com/26247733/44782109-b55e7a00-abb8-11e8-81c7-ae2ddf37dbc6.png)

**Comment by Cnly** [comment]
Hi, according to https://docs.microsoft.com/en-us/previous-versions/office/office-365-api/api/o365-china-endpoints, the legacy API will not work well with O365 by 21Vianet. Could you please have a try with the new Graph API? You can find rclone with support for that [here](https://beta.rclone.org/branch/v1.42-133-gb874bc22-Cnly-graph/). Thanks!

**Comment by ncw** [comment]
The graph support has now been merged to [the latest beta](https://beta.rclone.org) - can you try that?
