### ISSUE TITLE
s3 add pacer to retry directory listings

### ISSUE THREAD

**Issue by craig-miskell-fluxfederation** [ncw/rclone#2503]
#### What is the problem you are having with rclone?
When doing large (75M files) copies to AWS S3 (region is in another country, with ~30ms latency and occasionally slightly glitchy networks), rclone will report "error reading destination directory: SerializationError: failed to decode REST XML response caused by: unexpected EOF".  It's not wrong, but it is just a transient error and a retry would very likely succeed and allow the whole operation to succeed cleanly

#### What is your rclone version (eg output from `rclone -V`)
1.42

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Ubuntu 16.04 64 bit

####  Which cloud storage system are you using? (eg Google Drive)
AWS S3

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone copy --retries 1 --size-only --immutable --ignore-checksum --max-delete 0 --no-gzip-encoding /some/local/dir aws-${REGION}:somebucketname

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
Sorry, it'd be huge.  The relevant lines are:
2018/08/30 08:08:06 ERROR : <redacted directory name>: error reading destination directory: SerializationError: failed to decode REST XML response
caused by: unexpected EOF

It seems to me that making the directory listing code use low-level retries might help, or else making S3 use Pacer to handle retries.  But my Go isn't strong enough yet to help write a patch .  Happy to test any potential fixes in real-world scenarios, if it'd help.

**Comment by ncw** [comment]
Yes you are right, s3 does not use the pacer or implement low level retries.

It could and it should!

The reason it doesn't is that it was one of the first backends implemented and because s3 is so very reliable, no-one has complained before!

A quick grep indicates that these backends are missing pacers too

- ftp
- http
- qingstor
- s3
- sftp
- swift
- yandex

**Comment by ncw** [comment]
BTW here is the diff from the last time I did this to a backend: 9698a2babb1a3fdb69be60af81b3fe48cdcc0f73

It is mostly a pretty mechanical addition.  The only thing to watch out for is that the Update routine needs a CallNoRetry.

Does that look simple enough for you to have a go at?

**Comment by craig-miskell-fluxfederation** [comment]
It does look fairly straight forward and I'll give it a go.  If you don't hear from me in 3 days, send a rescue party as I will likely have been kidnapped by a grue. :)

**Comment by ncw** [comment]
@craig-miskell-fluxfederation I saw your WIP commit - looking good!  Setting minSleepTime to 0 will mean that all the retries are done immediately which seems a little unfriendly, especially since one of the errors is 503 slow down...

**Comment by craig-miskell-fluxfederation** [comment]
Thanks.  I started with minSleep at 10ms, but that inserts a 10ms sleep between every single API call, even those that were successful.  My small test syncs more than doubled in run time (from 7-8 minutes, up to 18minutes), so my 2 hour syncs were going to be a nightmare.

Pacer is clearly wanting to be a generic rate limiter as well as a retrier, and I only think we need the retry behaviour (with backoff in that situation, of course) for S3.  But now that I read the pacer code, I see how minSleep 0 will lead to never backing off.  Drat.  1ms had a much less noticeable effect, but it still seems like an arbitrary delay if all the requests are succeeding.  Not sure what the true right answer is here, but I'd be ok with starting at 1ms minSleep for now.

Regardless, the code to date hasn't fixed my problem.  Somehow the error is slipping out and not causing a retry.  I have either missed some call, or something more unusual is going on.  I shall continue my trek.

**Comment by craig-miskell-fluxfederation** [comment]
Oh I think I need to make ShouldRetry notice this particular error and return True in that case.  I shall rustle something up.

**Comment by craig-miskell-fluxfederation** [comment]
That makes sense re error handling.  I've rejigged my handling, and am running some tests (although the particular errors I'm trying to handle are now occuring less often).

Once I've nailed that down (I'm hopeful of confirming the fix for my situation by end of today) I'll look at a custom pacer engine for S3 (no delay in the happy path, but backing off on errors).

**Comment by craig-miskell-fluxfederation** [comment]
Confirm error handling works as desired, for my particular error.  

Looking at pacer implementation tomorrow.
