### ISSUE TITLE
Stats default and/or documentation

### ISSUE THREAD

**Issue by matthijskooijman** [ncw/rclone#2507]
I was a bit confused on how to get progress reports / stats from rclone. Just running a `sync` command did not give any output. Adding `-v` seems to show every file copy, which is a bit verbose. I was looking for a progress indication or regular summary, and found `--stats`. The documentation for that option says the default is 1 minute, so I expected to see stats output after a minute, but that never happened.

Looking more, I found #1180, which tells me that the default stats output happens at a more verbose log level, so you have to pass `-v`, or `--stats-log-level NOTICE`. However:
 - Typically, I'd think you want stats output, and not a full file list, so having to add `-v` seems counterproductive. In my setup, this even mixed up stats and file listing output in a way that didn't look too clear (I believe stats were written on top of the file list, with the file list showing through), but that might be something weird in my terminal setup.
 - Changing the stats log level seems a bit user-unfriendly, though it is clean from an implementation perspective.
 - It would have been nice if this was documented better. In particular, perhaps the `--stats` option should not that the default is 1 minute, but the output is hidden by default needing either `-v`, or `--stats-log-level NOTICE`. Doing so would have prevented some user surprise on my end.

#### What is your rclone version (eg output from `rclone -V`)
rclone v1.42
- os/arch: linux/arm
- go version: go1.10.1

**Comment by matthijskooijman** [comment]
> I agree... Probably adding --stats should force -v... I wonder whose scripts that would break if I changed it though!

Not sure - if `--stats` also forces all `INFO` output, including detailed file lists, I would be surprised. I'd rather expect `--stats` to be shown regardless of the log level without changing it (but that would involve changing the log level of stats messages to a higher level, which might not really be expected either...).

> I expect what you really want is to use the --progress or -P flag which you'll find in the latest beta.

Ah, that sounds good inded :-)

> I'd love a doc patch for that if you felt like writing one. You only need to patch the docs/content/docs.md file - everything else is auto generated.

I'll see if I can find some time for that (but frankly, I've been spending way to much time on backup setup already and really just need to get something working and then back to real work...).

**Comment by darthShadow** [comment]
@ncw I am willing to submit a patch for this but I am not sure how to go about making this more clear. These lines explain it pretty clearly:

>Stats are logged at INFO level by default which means they won't show at default log level NOTICE. Use --stats-log-level NOTICE or -v to make them show. See the Logging section for more info on log levels.

Does something else also need to be clarified?

**Comment by matthijskooijman** [comment]
@darthShadow, As for docs, that indeed seems sufficient. Where did you find these?

IIRC I've been looking at `--help` output (and https://rclone.org/commands/rclone_copy/ which is effectively also just the same, I think), which does not have this remark. I'm not sure if `--help` output is the right place to add something like this (it would need to be very concise, then).

**Comment by darthShadow** [comment]
@matthijskooijman These were in the [Usage](https://rclone.org/docs/#stats-time) docs

**Comment by ncw** [comment]
@darthShadow wrote
> Does something else also need to be clarified?

Those docs look quite good.  I guess it is a question of are they easy enough to find?

I wonder whether it might be worth calling out the `--progress` flag there too which gives the user continuously updated stats, which I think is probably what most people really want instead of adjusting the stats.

Maybe calling out `--progress` in some of the intro text...

What do you think?

**Comment by darthShadow** [comment]
I also checked the `rsync` help page and they too don't seem to highlight the `--progress` flag anywhere.

I could add a line in the `sync` & `copy` docs to specify using the `--progress` flag for viewing the stats. Would that be more helpful, @matthijskooijman ?

**Comment by matthijskooijman** [comment]
Yup, that would probably help :-)

**Comment by ncw** [comment]
@darthShadow vey happy to receive a PR with that in :-)

**Comment by darthShadow** [comment]
@ncw Sorry, haven't had much free time the past few weeks. Will try to get this done by this weekend.
