### ISSUE TITLE
question: use as a library

### ISSUE THREAD

**Issue by gedw99** [ncw/rclone#251]
Use Case:
i am writing code that talks to S3 and local.
The code will be deployed locally and on s3.

So can this code be used as a library?
Is the interface for S3 and local the same ?

thanks in advance !!

**Comment by ncw** [comment]
If you look at the main rclone program you'll see it just uses the rest of the code as a library.

https://github.com/ncw/rclone/blob/master/rclone.go

You specify which remotes you want compiled in by the includes.

The interface for the local an s3 are identical and defined in https://github.com/ncw/rclone/blob/master/fs/fs.go

Those interfaces have been very stable, but I don't guarantee I won't change them!

If I was making some code to run with rclone internals then I'd probably copy `rclone.go` and start from there.  Using the rclone config file and concept of remotes will simplify your life (as in you configure stuff with rclone).

**Comment by gedw99** [comment]
@ncw awesome stuff. thanks. I will dig in in the new year.
