### ISSUE TITLE
Avoid creation of directory %USERPROFILE%\.config\rclone when using --config or RCLONE_CONFIG

### ISSUE THREAD

**Issue by albertony** [ncw/rclone#2514]
I'm trying out version 1.43 on Windows, and want to specify a custom location for the config file (to run it as "stealth" as possible). I can then use command line argument `--config=<configfile>` or environment variable `set RCLONE_CONFIG=<configfile>`. But even if I do, rclone creates an empty directory `%USERPROFILE%\.config\rclone`. I find that I have to specify environment variable XDG_CONFIG_HOME to avoid this. When looking into the source file `fs/config/config.go` and function `makeConfigPath`, I'm wondering if this could be avoided with a minor code change: At [line 121](https://github.com/ncw/rclone/blob/c6c74cb86992303fec6584c6e0561a0efae1a849/fs/config/config.go#L121-L128) it sets local variables xdgdir and xdgcfgdir based on the value of homedir, and then at [line 151](https://github.com/ncw/rclone/blob/c6c74cb86992303fec6584c6e0561a0efae1a849/fs/config/config.go#L151-L157) it creates the actual folder path given by xdgcfgdir, before at line [167](https://github.com/ncw/rclone/blob/c6c74cb86992303fec6584c6e0561a0efae1a849/fs/config/config.go#L167-L173) it checks for `--config` or `RCLONE_CONFIG`.. When user has specified `--config` or `RCLONE_CONFIG`, should this take priority so the logic searching for home and xdgdir can then just be skipped?

**Comment by ncw** [comment]
> When user has specified --config or RCLONE_CONFIG, should this take priority so the logic searching for home and xdgdir can then just be skipped?

Yes it should.

Would you like to send a pull request with this change?

**Comment by albertony** [comment]
Sure, I am not very familiar with Go, but I can try..

**Comment by albertony** [comment]
I have given it a shot. I was a bit confused about the logic around default (and several of them) vs custom path, but made it so that the description of `--config` from `rclone -h` reports what would have been used as path by default if `--config` was not specified. E.g. `rclone --config \path\to\my.config -h` reports default path to be according to $XDG_CONFIG_HOME (or $HOME) and not considering the path given by `--config`. The main change is that when `--config` (or `RCLONE_CONFIG`) is specified there is no attempt at creating folders, so for instance if no existing config file or rclone config directory exists and XDG_CONFIG_HOME is specified then the default is reported to be $XDG_CONFIG_HOME/rclone/rclone.conf without checking that it is actually possible to create it.

**Comment by ncw** [comment]
@albertony thanks for fixing it - I think the code is cleaner and more maintainable now :-)

Find the fix in [the latest beta](https://beta.rclone.org) in 15-30 mins.
