### ISSUE TITLE
--cache-total-chunk-size= missing in v1.43

### ISSUE THREAD

**Issue by irule311** [ncw/rclone#2519]
#### What is the problem you are having with rclone?
Rclone doesn't seem to recognize --cache-total-chunk-size= in v1.43 when using rclone mount. It worked in v1.42. I am not sure if this was done on purpose, but it was not mentioned in the changelogs and the docs still mention it.

#### What is your rclone version (eg output from `rclone -V`)
v1.43

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Tested on Ubuntu server and Windows 10, 64 bit

####  Which cloud storage system are you using? (eg Google Drive)
Google Drive

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone mount 

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
It immediately fails to mount with an unknown flag "--cache-total-chunk-size=10G"

**Comment by darthShadow** [comment]
As per `rclone --help` it's now named `--cache-chunk-total-size` instead of `--cache-total-chunk-size`, probably to keep it inline with the other `cache` flags. I don't think the docs have been updated to reflect this change.
