### ISSUE TITLE
delete before downloading

### ISSUE THREAD

**Issue by fredericofs** [ncw/rclone#252]
Is it possible to delete files from destination, before downloading files from source, during a sync job? 
Because the disk may be full / near the limit, when the sync starts, and it will fail

**Comment by ncw** [comment]
rsync has these options

```
            --delete-before         receiver deletes before xfer, not during
            --delete-during         receiver deletes during the transfer
            --delete-delay          find deletions during, delete after
            --delete-after          receiver deletes after transfer, not during
```

rclone currently implements `--delete-after`.  I think you are asking for `--delete-before` - does that sound correct?

**Comment by fredericofs** [comment]
yes! --delete-before

**Comment by axtux** [comment]
Good idea ! It also makes sense when making a snapshot backups with hardlinks on Linux
