### ISSUE TITLE
onedrive: uploading empty files causes SEGV

### ISSUE THREAD

**Issue by Cnly** [ncw/rclone#2520]
This bug as described in the title can be reproduced with the current repo version (with Graph) of code.

The direct cause of the bug is that when `size` is `0` in the function [`uploadMultipart`](https://github.com/ncw/rclone/blob/master/backend/onedrive/onedrive.go#L1329), the upload for-loop is skipped. Therefore, `info` is `nil`. Then when `info` is dereferenced, there will be SEGV.

Graph's multi-part upload API does not support 0-size files (`{"error":{"code":"invalidRequest","message":"The Content-Range header is missing or malformed."}}`). So to allow upload of empty files, we must use [single-part upload](https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/api/driveitem_put_content). But the [problem](https://github.com/ncw/rclone/pull/2472#issuecomment-414108942) with single-part upload is we'll either lose `modtime`, or create two versions of the same file. I think this needs to be discussed before changes can be made.

Personally I would prefer allowing single-part upload for empty files and setting `modtime` afterwards. Creating multiple versions of empty files won't occupy space, after all.

I believe this bug is related to [this failure](https://github.com/ncw/rclone/pull/2472#issuecomment-417960848) and [this forum post](https://forum.rclone.org/t/onedrive-impersonation/6576/5).

Update: The current code can download empty files without any problem.

**Comment by ncw** [comment]
> Personally I would prefer allowing single-part upload for empty files and setting modtime afterwards. Creating multiple versions of empty files won't occupy space, after all.

That sounds like the right fix to me. modtime is important and I don't think two versions of a 0 length file will matter to anyone.

Note that I've had problems uploading 0 length files to other remotes, eg amazon cloud drive - I think it is another one of those corner cases!

**Comment by Cnly** [comment]
Should have been fixed. Good news is that my ODfB doesn't create a new version for empty files on modtime change. Bad news is that non-empty files remain problematic. :/

**Comment by ncw** [comment]
Nice one!  You can check the integration tests tomorrow morning: https://pub.rclone.org/integration-tests/
