### ISSUE TITLE
rclone drive-formats copy/export one file from google drive - error reading source directory: directory not found  

### ISSUE THREAD

**Issue by araczkowski** [ncw/rclone#2521]
#### What is the problem you are having with rclone?
I'm trying to copy/export one docx file from Google Drive and convert it to txt

I'm using the command
``` rclone copy GD:test/test.docx /tmp/test --drive-formats txt```

the output is:
``` ERROR : : error reading source directory: directory not found ```

if I do this for directory:
``` rclone copy GD:test /tmp/test --drive-formats txt```
all is fine

#### What is your rclone version (eg output from `rclone -V`)
v1.43

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
linux/amd64

####  Which cloud storage system are you using? (eg Google Drive)
Google Drive

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone copy 

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

```
2018/09/04 10:12:18 DEBUG : rclone: Version "v1.43" starting with parameters ["rclone" "copy" "dysk-rysiek:test/ok.docx" "/tmp/test" "--config" "/sdcard/rclone/rclone.conf" "--drive-formats" "txt" "-vv"]
2018/09/04 10:12:18 DEBUG : Using config file from "/sdcard/rclone/rclone.conf"
2018/09/04 10:12:20 ERROR : : error reading source directory: directory not found
2018/09/04 10:12:20 INFO  : Local file system at /tmp/test: Waiting for checks to finish
2018/09/04 10:12:20 INFO  : Local file system at /tmp/test: Waiting for transfers to finish
2018/09/04 10:12:20 ERROR : Attempt 1/3 failed with 1 errors
2018/09/04 10:12:20 ERROR : : error reading source directory: directory not found
2018/09/04 10:12:20 INFO  : Local file system at /tmp/test: Waiting for checks to finish
2018/09/04 10:12:20 INFO  : Local file system at /tmp/test: Waiting for transfers to finish
2018/09/04 10:12:20 ERROR : Attempt 2/3 failed with 1 errors
2018/09/04 10:12:20 ERROR : : error reading source directory: directory not found
2018/09/04 10:12:20 INFO  : Local file system at /tmp/test: Waiting for checks to finish
2018/09/04 10:12:20 INFO  : Local file system at /tmp/test: Waiting for transfers to finish
2018/09/04 10:12:20 ERROR : Attempt 3/3 failed with 1 errors
2018/09/04 10:12:20 INFO  : 
Transferred:   	         0 / 0 Bytes, -, 0 Bytes/s, ETA -
Errors:                 1
Checks:                 0 / 0, -
Transferred:            0 / 0, -
Elapsed time:        2.7s
```

Is there any way to use drive-formats for one file? Thanks you in advance for any tips.
This project is awesome! :)

**Comment by B4dM4n** [comment]
`--drive-formats` will change the file extension used by rclone to access the file.

You should see a `test.txt` file when doing a ls:
```
rclone ls GD:test --drive-formats txt
```

This will also be the file name doing the copy.

**Comment by araczkowski** [comment]
thx @B4dM4n  for this info 

I just did:
``` rclone ls GD:test ```

the output is:
``` test.docx```

then I did:
``` rclone copy GD:test/test.txt /tmp/test --drive-formats txt```

I'm little bit surprised but it works, I'm not sure if this is feature or a bug


PS
but this way no success
``` rclone ls GD:test  --drive-formats txt```

the output is:
``` test.txt```

then I did:
``` rclone copy GD:test/test.txt /tmp/test```
```error reading source directory: directory not found```

**Comment by B4dM4n** [comment]
`--drive-formats` has to be set for all commands, like all other command line flags. It only changes how `rclone` sees documents for the current invocation of `rclone`.

Your copy command should look like this:
```
rclone copy --drive-formats txt GD:test/test.txt /tmp/test
```

**Comment by araczkowski** [comment]
thanks for info @B4dM4n. 
True - flag in each command works OK.
So no isuee - I'm closing this
