### ISSUE TITLE
After upgrading to 1.43 google cloud storage remote stopped working

### ISSUE THREAD

**Issue by shamil** [ncw/rclone#2523]
After upgrading to 1.43 google cloud storage remote stopped working
Reverting back to 1.42 resolved the issue.

#### Rclone version
```
rclone v1.43
- os/arch: linux/amd64
- go version: go1.11
```

####  Cloud storage system

Google Cloud Storage

#### The command

```shell
rclone -vv ls gcp:
```

#### A log from the above command

```
2018/09/04 12:36:07 DEBUG : rclone: Version "v1.43" starting with parameters ["rclone" "-vv" "ls" "gcp:"]
2018/09/04 12:36:07 DEBUG : Using config file from "/home/dummy/.config/rclone/rclone.conf"
2018/09/04 12:36:07 Failed to create file system for "gcp:": failed to configure Google Cloud Storage: empty token found - please run rclone config again
```

#### Rclone configuration for the `gcp` remote

```ini
[gcp]
type = google cloud storage
service_account_file = /tmp/gcp.json
```

**Comment by B4dM4n** [comment]
I looks like there has been a typo introduced that has been unnoticed during the config rewrite.

This is probably the cause (and fix) of the issue:
```patch
diff --git a/backend/googlecloudstorage/googlecloudstorage.go b/backend/googlecloudstorage/googlecloudstorage.go
index 1d74bccaf..2f47d9156 100644
--- a/backend/googlecloudstorage/googlecloudstorage.go
+++ b/backend/googlecloudstorage/googlecloudstorage.go
@@ -345,7 +345,7 @@ func NewFs(name, root string, m configmap.Mapper) (fs.Fs, error) {
        }
 
        // try loading service account credentials from env variable, then from a file
-       if opt.ServiceAccountCredentials != "" && opt.ServiceAccountFile != "" {
+       if opt.ServiceAccountCredentials == "" && opt.ServiceAccountFile != "" {
                loadedCreds, err := ioutil.ReadFile(os.ExpandEnv(opt.ServiceAccountFile))
                if err != nil {
                        return nil, errors.Wrap(err, "error opening service account credentials file")
```

There are two possible workarounds you can try until it is fixed:
```
[gcp]
type = google cloud storage
service_account_credentials = content of /tmp/gcp.json
```
or
```
[gcp]
type = google cloud storage
service_account_file = /tmp/gcp.json
service_account_credentials = ignored
```
The later workaround will fail once the problem is solved though.

**Comment by ncw** [comment]
Thanks for fixing this @B4dM4n - my fault!

This should be fixed here

https://beta.rclone.org/v1.43-032-g6b8b9d19-beta/ (uploaded in 15-30 mins)

And in [the latest beta](https://beta.rclone.org) from then and 1.44 when released.

**Comment by arnoldvilleneuve** [comment]
Don't know what I am doing wrong but I have the same issue with v1.48

rcloneone:
arnold@rclonelinux1:~/rclone-v1.48.0-linux-amd64$ rclone ls rcloneone:
2019/08/14 19:31:58 Failed to create file system for "rcloneone:": failed configuring Google Cloud Storage Service Account: error processing credentials: invalid character 'r' looking for beginning of value
arnold@rclonelinux1:~/rclone-v1.48.0-linux-amd64$ rclone ls rcloneone:rclonestore
2019/08/14 19:32:25 Failed to create file system for "rcloneone:rclonestore": failed configuring Google Cloud Storage Service Account: error processing credentials: invalid character 'r' looking for beginning of value
arnold@rclonelinux1:~/rclone-v1.48.0-linux-amd64$

rcloneone]
type = google cloud storage
project_number = 482564684504
service_account_file = /home/arnold/rclone-v1.48.0-linux-amd64/rcloneone.json
service_account_credentials = rclonesa@rcloneone-249818.iam.gserviceaccount.com
object_acl = bucketOwnerFullControl
bucket_acl = private
location = us-central1
storage_class = REGIONAL

ERROR MSG

arnold@rclonelinux1:~/rclone-v1.48.0-linux-amd64$ rclone ls rclone2:
2019/08/14 20:48:46 Failed to create file system for "rclone2:": failed configuring Google Cloud Storage Service Account: error processing credentials: invalid character 'r' looking for beginning of value

**Comment by buengese** [comment]
This is not the same issue. Please open new issue and keep to the issue template. Your error message there might be a problem with your config file. Please try reconfiguring your backend using rclone config.

**Comment by ncw** [comment]
> service_account_file = /home/arnold/rclone-v1.48.0-linux-amd64/rcloneone.json
> service_account_credentials = [rclonesa@rcloneone-249818.iam.gserviceaccount.com](mailto:rclonesa@rcloneone-249818.iam.gserviceaccount.com)

Delete the `service_account_credentials` line or paste the contents of the file into `service_account_credentials` and remove the `service_account_file` line.

**Comment by arnoldvilleneuve** [comment]
yep, figured that out yesterday and it worked like a charm 
working on Rtray and Rbrowser access from a remote workstation down
also working on a GCP virtual machine with VNC access to gui desktop 
    On Thursday, August 15, 2019, 10:36:40 a.m. EDT, Nick Craig-Wood <notifications@github.com> wrote:  
 
 

service_account_file = /home/arnold/rclone-v1.48.0-linux-amd64/rcloneone.json
service_account_credentials = rclonesa@rcloneone-249818.iam.gserviceaccount.com


Delete the service_account_credentials line or paste the contents of the file into service_account_credentials and remove the service_account_file line.
