### ISSUE TITLE
onedrive: improve upgrade to graph procedure

### ISSUE THREAD

**Issue by ncw** [ncw/rclone#2527]
I think the upgrade procedure could work slightly better - if you start with an old remote like this

```
[onedrive]
type = onedrive
client_id = 
client_secret = 
token = {"access_token":"..."}
```

Then run `rclone config` then `e` to edit the remote, you get

```
$ rclone config 
Current remotes:

Name                 Type
====                 ====
[snip]

e) Edit existing remote
n) New remote
d) Delete remote
r) Rename remote
c) Copy remote
s) Set configuration password
q) Quit config
e/n/d/r/c/s/q> e
Choose a number from below, or type in an existing value
[snip]
remote> onedrive
--------------------
[onedrive]
type = onedrive
client_id = 
client_secret = 
token = {"access_token":"..."}
--------------------
Edit remote
Value "client_id" = ""
Edit? (y/n)>
y) Yes
n) No
y/n> n
Value "client_secret" = ""
Edit? (y/n)>
y) Yes
n) No
y/n> n
Edit advanced config? (y/n)
y) Yes
n) No
y/n> n
--------------------
[onedrive]
type = onedrive
client_id = 
client_secret = 
token = {"access_token":"..."}
--------------------
y) Yes this is OK
e) Edit this remote
d) Delete this remote
y/e/d> y
Remote config
Already have a token - refresh?
y) Yes
n) No
y/n> y
Use auto config?
 * Say Y if not sure
 * Say N if you are working on a remote or headless machine
y) Yes
n) No
y/n> y
If your browser doesn't open automatically go to the following link: http://127.0.0.1:53682/auth
Log in and authorize rclone for access
Waiting for code...
Got code
Choose a number from below, or type in an existing value
 1 / OneDrive Personal or Business
   \ "onedrive"
 2 / Root Sharepoint site
   \ "sharepoint"
 3 / Type in driveID
   \ "driveid"
 4 / Type in SiteID
   \ "siteid"
 5 / Search a Sharepoint site
   \ "search"
Your choice> 1
Found 1 drives, please select the one you want to use:
0:  (personal) id=XXXXXXXXX
Chose drive to use:> 0
Found drive 'root' of type 'personal', URL: https://onedrive.live.com/?cid=XXXXXXX
Is that okay?
y) Yes
n) No
y/n> y
Current remotes:

Name                 Type
====                 ====
[snip]

e) Edit existing remote
n) New remote
d) Delete remote
r) Rename remote
c) Copy remote
s) Set configuration password
q) Quit config
e/n/d/r/c/s/q> q
```

```
$ rclone lsd onedrive:
2018/09/02 16:32:12 Unable to get drive_id and drive_type. If you are upgrading from older versions of rclone, please run `rclone config` and re-configure this backend.
```

```
$ rclone config show onedrive
--------------------
[onedrive]
type = onedrive
client_id = 
client_secret = 
token = {"access_token":"..."}
--------------------
```

So the `drive_id` and the `drive_type` don't save for some reason.

Can you have a look at this please @Cnly ?  It probably isn't the onedrive backend's fault!

From #2472

**Comment by jarusak** [comment]
I ran into this same problem about 3 hours ago :) after a throttling issue that prompted an upgrade -  is this now incorporated into the latest  windows-amd64 beta at https://beta.rclone.org/?

**Comment by Cnly** [comment]
@jarusak 

> However, I still have the same problem after successfully getting the code and choosing 1 for a One Drive Business account

According to the error message you posted, this is not the same problem. `Failed to query available drives: HTTP error 429` is an error returned by Microsoft. But it's a little weird to me, because 429 means `too many requests` instead of `bad request`.

Actually, it seems your two errors are of the same type - throttling. And you're having it with both the old and new API. You may try [Getting your own Client ID and Key](https://github.com/ncw/rclone/blob/master/docs/content/onedrive.md#getting-your-own-client-id-and-key) and see if it works. If not, maybe you'll have to wait for it to work itself out. :/

**Comment by jarusak** [comment]
Thanks and, yes, I see that now - subsequent attempts have been occasionally successful but very slow so I'll try the ID/Key route. Great API!
