### ISSUE TITLE
Microsoft OneDrive : Couple of problems

### ISSUE THREAD

**Issue by CarrotCruncher** [ncw/rclone#253]
Firstly, thanks for this tool, I've after something like this for ages.

I've set it up to sync some directories from my Dropbox account to both my Google Drive and Microsoft OneDrive accounts. The sync to Google Drive appears to work perfectly without issue. The Sync to Microsoft OneDrive generally works except for the following two types of error:

1. Failed to copy: unauthenticated: Must be authenticated to use '/drive' syntax

This seems to happen randomly, I have not been able to identify any commonality with the the files it fails on, when it happens, etc. Are you able to offer any explanation as to what this means?

2. Failed to copy: unexpected EOF

This seems to happen for any file that has to be chunked. The files I'm syncing range from a few bytes to hundreds of megabytes in size. Initially this was happening for any file that was over 10MB, so I set the "-onedrive-upload-cutoff" option to 100M and now it only fails for any file over 100MB. Is there a known issue with uploading chunked files to Microsoft OneDrive?

I have to say that I've not quite understood the explanation of the two options available for Microsoft One Drive:

>–onedrive-chunk-size=SIZE
>
>Above this size files will be chunked - must be multiple of 320k. The default is 10MB. Note that the >chunks will be buffered into memory.
>
>–onedrive-upload-cutoff=SIZE
>
>Cutoff for switching to chunked upload - must be <= 100MB. The default is 10MB.

specifically the "Above this size files will be chunked" statement. I thought "–onedrive-chunk-size" was the chunk size if a file had to be chunked, and "–onedrive-upload-cutoff" was the maximum size a file could be without having to be chunked. Have I misunderstood?

Please note I'm using rclone-v1.25-linux-amd64.zip on a Fedora 23 server and my upload connection speed is pretty bad, around 800kbps.

Many thanks.

**Comment by ncw** [comment]
> Failed to copy: unauthenticated: Must be authenticated to use '/drive' syntax

I think this must be a Onedrive error.  I've noticed that the onedrive API is a bit flakey at times.

> Failed to copy: unexpected EOF

I tried copying some large files and it seemed to work ok.

Can you send me a log with `rclone -v` of this happening please?  I suspect it might be your service provider throttling the connections - I've seen very similar things on my home internet connection.

> specifically the "Above this size files will be chunked" statement.

I think that is a mistake!  I'll correct the docs to something like

```
–onedrive-chunk-size=SIZE

The chunk size for large uploads - must be multiple of 320k. The default is 10MB. Note that the chunks will be buffered into memory.
```

**Comment by CarrotCruncher** [comment]
Thanks for the response. This is the output from command:
rclone -v --transfers=1 sync "Dropbox":"Documents" "Microsoft OneDrive":"Documents"

http://pastebin.com/PvQFxNSe

(I've removed all the lines containing "Sizes identical$" or "Unchanged skipping$" to keep it concise.)

**Comment by ncw** [comment]
Thanks for that.  If you copy one of the failing files to your hard disk first, then copy it to onedrive does it work?

I tried copying files form dropbox to onedrive like you are doing but I couldn't reproduce the problem.  You could try increasing the timeouts `--contimeout` and `--timeout` but I'm not hopeful that will help.

I suspect throttling by your ISP - have you tried to see if it works at a different time of day?

**Comment by CarrotCruncher** [comment]
Syncing from my local filesystem to both Google Drive and Microsoft OneDrive worked perfectly, without any errors.

Thinking about it, this is actually a better solution for me as I have the Dropbox client installed so that data is already being sync'd locally, and so I can avoid having to download all the data from Dropbox again before uploading it Google Drive and Microsoft OneDrive.

Many thanks for your assistance, and thanks again for a great tool.
