### ISSUE TITLE
Jottacloud backend and special characters

### ISSUE THREAD

**Issue by albertony** [ncw/rclone#2531]
I have a folder with name "Notepad++" in my Jottacloud account, but trying to "ls" it with rclone fails:
```
ERROR : Notepad++: error listing: directory not found
Failed to ls: directory not found
```
I guess it is because the backend implementation replaces special characters (including "+") with their FULLWIDTH Unicode equivalent. Shouldn't such characters be URL (percent) encoded instead? I know for a fact that in the Jottacloud API you can refer to paths with "+" in them using "%2B", "#" with "%23" etc..

**Comment by ncw** [comment]
Thoughts @buengese and @olihey ? Is `+` OK in Jottacloud filenames?

**Comment by buengese** [comment]
`+` is indeed allowed on Jottacloud. But even if we're wrongly replacing it with it's FULLWIDTH equivalent listing shouldn't fail.

**Comment by albertony** [comment]
No, maybe it shouldn't have failed? The file was uploaded outside of rclone, if that makes any difference.

I know that Jottacloud can handle these characters. A quick test: Upload a file "notepad++.exe" to Archive in the official WebUI. Then it can be found with the API, at url `https://jfs.jottacloud.com/jfs/<Username>/Jotta/Archive/<path>/notepad%2B%2B.exe`, where the returned XML says `<file name="notepad++.exe" ...`.

In C# I have used Uri.EscapeUriString, and found that at least "+" and "#" had to be escaped manually, but I don't know the complete list.. I could have just supplied a pull request, but was a bit unsure if there were any special reasons for rclone to use the unicode variants, since I can see that also the OneDrive and at some extent Box backends also does it..

**Comment by buengese** [comment]
I was wrong in my initial comment. The way ls is implemented right now it has to fail. The characters that get replaced should be reserved character i.e. you shouldn't be able to create files or folders with that name in web ui. I just rechecked all the characters we are currently replacing with jottacloud and appears `!, &, :, %, #, '` are actually ok too. 
I'm unsure if jottacloud changed there behavior there or if I made some mistake when initially testing those because I remember testing all of these extensively.

**Comment by albertony** [comment]
Strange. It is actually more than a year since my tests discovered that + and # had to be escaped extra, so I don't understand what was different in your tests.

**Comment by buengese** [comment]
Ok more testing, more strange results. I can create a folder folder names `test#` via API but not via webui. Additionally i can create a folder named `:test` on the Archive Mountpoint but not on the sync Mountpoint. 

Go allready url encodes `#`, `+` works if you URL encode it manually. I believe jottacloud's reserved characters need a lot more testing now.

**Comment by albertony** [comment]
I guess you are testing on Linux or OS X, as colon is not valid in filenames on Windows..

I have just done some testing on Windows: Generated a set of files, each with name consisting of a decimal code followed by the corresponding character for all characters within the range 0-879, which includes most relevant characters from Latin (basic, supplement, extended a and b, and IPA extensions), spacing modifiers and combining diacritical marks. I then used Jottacloud's web ui to upload the generated files, and then download them again. Then I compared the downloaded set of files with the original generated set:
- The set of generated files is 839 files, excluding files with characters not valid in Windows filenames: 0-31 (control characters), 34 (double quote), 42 (asterisk), 47 (forward slash), 58 (colon), 60 (less-than), 62 (greater-than), 63 (question mark), 92 (backslash), 124 (vertical line).
- The file with the character code 127 (DEL) are missing from Jottacloud, so it this character is not supported.
- The following characters are accepted in filenames by Jottacloud, but they are replaced with a different character:
   - 832 (Combining Grave Tone Mark) is replaced by 768 (Combining Grave Accent) when uploading to Jottacloud.
   - 833 (Combining Acute Tone Mark) is replaced by 769 (Combining Acute Accent)
   - 835 (Combining Greek Koronis) is replaced by 787 (Combining Comma Above)
   - 836 (Combining Greek Dialytika Tonos) is replaced by two characters 776 (Combining Diaeresis) and 769 (Combining Acute Accent).
- No difference if upload to Archive or Sync mountpoint.

So within the 1 byte range 0-255 all characters allowed in Windows except DEL (127) are supported by Jottacloud. Many of the more extended Unicode characters are also supported, but some of them will be replaced by similar looking characters (I did some not so systematic tests with many more Unicode characters than listed above, and saw the same).

Next thing is to find out which of the allowed characters must be percent encoded in the API requests, and which of them must be manually encoded because the default URL encoding functionality does not. I guess handling the characters in range 0-255 would be a good start..

**Comment by ncw** [comment]
@buengese wrote:
> Go allready url encodes #, + works if you URL encode it manually. I believe jottacloud's reserved characters need a lot more testing now.

If you comment out the replacement then you can use the debug command `rclone info jottacloud:testdir` which will try all possible characters and report stuff back.  It also creates stuff that is impossible to delete sometimes ;-)

@albertony:
Nice testing - I wouldn't worry too much about the characters >= 128 - unicode handling should deal with those (rclone has some special sauce here).

> So within the 1 byte range 0-255 all characters allowed in Windows except DEL (127) are supported by Jottacloud.

That is good to know. 

> Next thing is to find out which of the allowed characters must be percent encoded in the API requests, and which of them must be manually encoded because the default URL encoding functionality does not. I guess handling the characters in range 0-255 would be a good start..

This is covered by several RFCs so I would have hoped the standard way rclone does it would work.  It might be that we need to add `rest.URLPathEscape` in some more places.  The integration tests will flush these out.

**Comment by albertony** [comment]
So you basically suggest removing the special `replaceReservedChars` code and see what happens, when we just use the `URLPathEscape`?

**Comment by albertony** [comment]
So wouldn't something like [this](https://github.com/albertony/rclone/commit/a45e640309fa09c0596526a23db5d5c814ec97fc) be an improvement? I tortured it a bit with my "0-879" character files, and ls and copy (up and down) seem to work for all the same characters as in my test with the web ui.

It would not solve the issue with the `:` character, and I guess there could also be other characters that are possible to upload from Linux but which are not supported on Windows. I don't know how Jottacloud handles this, I mean when a Windows user downloads files uploaded from Linux..

**Comment by albertony** [comment]
> Lastly changing the replace behavior could potentially break stuff for people who have already created files with characters previously replaced. @ncw Is that a problem for you?

Sure, that is potentially a problem. But I think it is a greater problem that rclone cannot read existing files/folders with any of the characters that `replaceReservedChars` replaces. For example rclone can only handle items with "+" in them if they were uploaded by rclone, not if uploaded via official clients/UI. List commands abort with error when they reach my existing "Notepad++" folder, which is definitely not good.

I think it is best to remove the replacing, and to do it before the next release so that not even more files are uploaded with the current replacement logic. And would this be a breaking change? I think already uploaded files can be downloaded, but will not get the replaced characters transformed back to the original. Sure, not ideal, but probably acceptable?

**Comment by albertony** [comment]
Retested after merge of changes from @buengese in #2584. Works better now. But still possible to stumble.. I see the replaceReservedChars function is still in use, but now only replacing any of `\*<>?:;|"` (and space if first or last) with unicode equivalents. Of these only `;` are legal in filenames on Windows, but if I upload a file containing this using official client or web ui then rclone will not handle it:
` ERROR : filename with ; semicolon.txt: Failed to copy: failed to open source object: error 404: no.jotta.backup.errors.NoSuchPathException (Not Found)`.

Is now the main (only?) reason for the replaceReservedChars conversion to save the user from getting into trouble in a mixed Windows/Linux setup? If so, then shouldn't `;` also be allowed (removed from the list characters to be replaced)? I can supply a pull request, but wanted to be sure I understand your reasoning..

**Comment by buengese** [comment]
The intention is to replace all unsupported characters and prevent users from getting into trouble when using the web ui. The problem with `;` is that the web ui will just eat it and all following characters even though this is probably a bug in the web ui I decided to keep replacing it. I agree that replacing characters is not the most beautiful solution but we have to agree on something that works at least in 99% of cases. I'm fine with removing `*` from the replace list but I see no point in spending to much effort on a problem that will realistically affect less than 5% of users.

**Comment by albertony** [comment]
> The problem with ; is that the web ui will just eat it and all following characters...

Ah, I can see that behavior now - when attempting to create a new folder using the web ui. But creating it with rclone works fine (when I comment out the replacing of it), and then web ui can work with it without issues as far as I can see. And uploading a file with `;` in it works fine from web ui. So I would have removed it from the replace list. Then we are not replacing any of the characters which are valid in Windows, and handled (good enough) in web ui, which I think would be good.

Regarding the `*`, I guess it is not so important, as we are getting into marginal cases. It could wait until possibly someone decides to dig deeper into this can of worms..
