### ISSUE TITLE
[Feature request] Support --fast-list with Jottacloud

### ISSUE THREAD

**Issue by albertony** [ncw/rclone#2532]
By adding query parameter "mode=list" to the API request for a folder, you get all files and subfolders recursive, as a filedirlist XML. Is this what is needed to implement the ListR function, enabling the --fast-list flag?

**Comment by ncw** [comment]
Yes that is exactly what is needed for `ListR` and `--fast-list` support :-)

How does it work if you have 1,000,000 files - does it page the listing?

Would you like to have a go at this?

**Comment by albertony** [comment]
It does not page the results, as far as I know. I don't know if this means we have to do some kind of stream parsing for large XMLs, are there other backends doing something like that?

**Comment by ncw** [comment]
All the other backends use some sort of paging mechanism to give you 1,000 files in a chunk.

The XML parser in the REST module does do streaming though, but the result will be passed back in-memory.

Then again for `--fast-list` it does explicitly state in the help that it will use more memory.

I'd say implement it and see - we can always write caveats in the docs!
