### ISSUE TITLE
rclone cache mounted but not working ? process is running

### ISSUE THREAD

**Issue by gelsas** [ncw/rclone#2534]
(https://forum.rclone.org/t/rclone-cache-running-but-not-working/6691)

I mounted my gcache and set some options but it seems it is not uploading from the cache tmp upload path.

Below are my current cofigs and my mount command.

[gdrive2]
type = drive
client_id = CLIENTIDHERE
client_secret = CLIENTSECRETHERE
scope = drive
token = {“access_token”:“TOKENHERE”,“token_type”:“Bearer”,“refresh_token”:“STUFFHERE”,“expiry”:“2018-09-05T04:44:42.822412969+02:00”}

[gcache2]
type = cache
remote = gdrive2:/mediafiles
plex_url = http://IP:32400
plex_username = USERPLEX
plex_password = PASSPLEX
chunk_size = 5M
info_age = 1d
chunk_total_size = 10G

[gcrypt2]
type = crypt
remote = gcache2:/crypt
filename_encryption = standard
directory_name_encryption = true
password = PASS1
password2 = PASS2

rclone mount gcrypt2: /share/CACHEDEV1_DATA/External 
–allow-other 
–allow-non-empty 
–dir-cache-time 24h 
–cache-chunk-total-size 5G 
–cache-chunk-size 10M 
–cache-tmp-upload-path /share/CACHEDEV1_DATA/RcloneUploads 
–cache-tmp-wait-time 60m 
–cache-info-age 28h 
–cache-workers 5 
–buffer-size 100M 
–log-level INFO 
–log-file /share/CACHEDEV1_DATA/Public/rclone-test.log 
–umask 002

Shouldn’t now files which are put in RcloneUploads be uploaded after 60m ?

And just to be sure in Plex I need to point to /share/CACHEDEV1_DATA/External correct?

Furthermore I have also added the log from the rclone-test.log file:
2018/09/05 02:48:17 INFO : gcache2: Cache DB path: /root/.cache/rclone/cache-backend/gcache2.db
2018/09/05 02:48:17 INFO : gcache2: Cache chunk path: /root/.cache/rclone/cache-backend/gcache2
2018/09/05 02:48:17 INFO : gcache2: Chunk Memory: true
2018/09/05 02:48:17 INFO : gcache2: Chunk Size: 10M
2018/09/05 02:48:17 INFO : gcache2: Chunk Total Size: 5G
2018/09/05 02:48:17 INFO : gcache2: Chunk Clean Interval: 1m0s
2018/09/05 02:48:17 INFO : gcache2: Workers: 5
2018/09/05 02:48:17 INFO : gcache2: File Age: 1.1666666666666667d
2018/09/05 02:48:17 INFO : gcache2: Cache Writes: enabled
2018/09/05 02:48:17 INFO : gcache2: Upload Temp Rest Time: 1h0m0s
2018/09/05 02:48:17 INFO : gcache2: Upload Temp FS: /share/CACHEDEV1_DATA/RcloneUploads
2018/09/05 02:48:17 INFO : gcache2: Cache DB path: /root/.cache/rclone/cache-backend/gcache2.db
2018/09/05 02:48:17 INFO : gcache2: Cache chunk path: /root/.cache/rclone/cache-backend/gcache2
2018/09/05 02:48:17 INFO : gcache2: Chunk Memory: true
2018/09/05 02:48:17 INFO : gcache2: Chunk Size: 10M
2018/09/05 02:48:17 INFO : gcache2: Chunk Total Size: 5G
2018/09/05 02:48:17 INFO : gcache2: Chunk Clean Interval: 1m0s
2018/09/05 02:48:17 INFO : gcache2: Workers: 5
2018/09/05 02:48:17 INFO : gcache2: File Age: 1.1666666666666667d
2018/09/05 02:48:17 INFO : gcache2: Cache Writes: enabled
2018/09/05 02:48:17 INFO : gcache2: Upload Temp Rest Time: 1h0m0s
2018/09/05 02:48:17 INFO : gcache2: Upload Temp FS: /share/CACHEDEV1_DATA/RcloneUploads
2018/09/05 02:48:58 INFO : Cache remote gcache2:crypt: Clearing cache from signal
2018/09/05 02:48:58 INFO : Cache remote gcache2:crypt: Clearing cache from signal

And this is "grep" telling me:
[~] # ps -ef | grep rclone
6411 admin 10908 S rclone mount gcrypt2: /share/CACHEDEV1_DATA/External --allow-other --allow-non-empty --dir-cache-time 24h --cache-chunk-total-size 5G --cache-chunk-size 10M --cache-tmp-upload-path /share/CACHEDEV1_DATA/RcloneUploads --cache-tmp-wait-time 60m --cache-info-age 28h --cache-workers 5 --buffer-size 100M --log-level INFO --log-file /share/CACHEDEV1_DATA/Public/rclone-test.log --umask 002
12764 admin 1000 S grep rclone

What did I do wrong why is it not working?

**Comment by ncw** [comment]
It looks like you've made some progress on the forum issue, so I'm going to close this.
