### ISSUE TITLE
OneDrive and shared folders - listing issue

### ISSUE THREAD

**Issue by hogmac** [ncw/rclone#2536]
I just updated to the latest beta of rclone ( v1.43-036-g89be5cad-beta) on what Microsoft Graph code was merged into v 1.43, however on my personal OneDrive doing an rclone lsd on a Shared Folder only works on the first level of directories, example: `rclone lsd myonedrive:sharedfolder1/`.

Trying a `rclone lsd myonedrive:sharedfolder1/sharedfolder2/` delivers this error:
```
2018/09/05 00:32:31 ERROR : : error listing: directory not found
2018/09/05 00:32:31 Failed to lsd: directory not found.
```
I did checked and sharedfolder2 in fact exists in the directory tree (this works well ok on non-shared folders).

The same happens when trying to copy files from `myonedrive:sharedfolder1/sharedfolder2/` to my local instance as it says
```
2018/09/05 00:34:31 ERROR : : error listing: directory not found
2018/09/05 00:34:31 Failed to lsd: directory not found
```

Any ideas on why listing directories is not working properly on shared folders?

This may be related to what is described here [https://forum.rclone.org/t/rclone-is-not-working-outside-of-the-root-of-crypt-remote/6697/2](url) for crypt folders.

**Comment by Cnly** [comment]
Hi hogmac,

This is actually a [known](https://forum.rclone.org/t/onedrive-issues-crypt-drive-from-shared-folder-cant-delete-files/6607/10) and partially-fixed problem and it's related to Microsoft's limitation on the API for shared folders. We're still thinking about how to deal with it. I should have opened an issue earlier... But anyway, thanks for reporting!

**Comment by kusmierz** [comment]
@Cnly is this issue causing `sync` won't skip existing files on shared folder? Or is it another issue to report to?

```bash
adam@somewhere:~ # fallocate -l 100M foobar/test.dat
adam@somewhere:~ # ll foobar/
total 102408
drwxr-xr-x  2 adam adam      4096 Nov  3 14:10 .
drwx------ 35 adam adam      4096 Nov  3 14:10 ..
-rw-r--r--  1 adam adam 104857600 Nov  3 14:10 test.dat
adam@somewhere:~ # rclone sync ./foobar onedrive-shared:foobar -Pc --delete-during
Transferred:   	  100.024M / 100 MBytes, 100%, 2.372 MBytes/s, ETA -
Errors:                 0
Checks:                 0 / 0, -
Transferred:            0 / 1, 0%
Elapsed time:       42.1s
Transferring:
 *                                      test.dat: 100% /100M, 2.610M/s, -
# running again same command should skip `test.dat`, but it is not:
adam@somewhere:~ # rclone sync ./foobar onedrive-shared:foobar -Pc --delete-during
Transferred:   	  100.024M / 100 MBytes, 100%, 2.120 MBytes/s, ETA -
Errors:                 0
Checks:                 0 / 0, -
Transferred:            0 / 1, 0%
Elapsed time:       47.1s
Transferring:
 *                                      test.dat: 100% /100M, 1.886M/s, -
```

**Comment by Cnly** [comment]
@kusmierz Can you re-run that command with `-vv` flag? We should be able to see what's happening with more debug logs!

**Comment by kusmierz** [comment]
sure (just change 100M file to 10M):
```
2018/11/05 08:18:37 DEBUG : rclone: Version "v1.44" starting with parameters ["rclone" "-vv" "sync" "./foobar" "onedrive-shared:foobar" "-c" "--delete-during"]
2018/11/05 08:18:37 DEBUG : Using config file from "/home/adam/.config/rclone/rclone.conf"
2018/11/05 08:18:41 INFO  : Waiting for deletions to finish
2018/11/05 08:18:41 INFO  : Encrypted drive 'onedrive-shared:foobar': Waiting for checks to finish
2018/11/05 08:18:41 INFO  : Encrypted drive 'onedrive-shared:foobar': Waiting for transfers to finish
2018/11/05 08:18:43 DEBUG : hv1frabrt9evhqr1fjmokg6fnk: Starting multipart upload
2018/11/05 08:18:43 DEBUG : hv1frabrt9evhqr1fjmokg6fnk: Uploading segment 0/10488352 size 10485760
2018/11/05 08:18:48 DEBUG : hv1frabrt9evhqr1fjmokg6fnk: Uploading segment 10485760/10488352 size 2592
2018/11/05 08:18:48 INFO  : test.dat: Copied (new)
2018/11/05 08:18:48 INFO  : 
Transferred:   	   10.002M / 10.002 MBytes, 100%, 910.421 kBytes/s, ETA 0s
Errors:                 0
Checks:                 0 / 0, -
Transferred:            1 / 1, 100%
Elapsed time:       11.2s

2018/11/05 08:18:48 DEBUG : 8 go routines active
2018/11/05 08:18:48 DEBUG : rclone: Version "v1.44" finishing with parameters ["rclone" "-vv" "sync" "./foobar" "onedrive-shared:foobar" "-c" "--delete-during"]
```

**Comment by saisimha** [comment]
> 
> 
> @Cnly is this issue causing `sync` won't skip existing files on shared folder? Or is it another issue to report to?
> 
> ```shell
> adam@somewhere:~ # fallocate -l 100M foobar/test.dat
> adam@somewhere:~ # ll foobar/
> total 102408
> drwxr-xr-x  2 adam adam      4096 Nov  3 14:10 .
> drwx------ 35 adam adam      4096 Nov  3 14:10 ..
> -rw-r--r--  1 adam adam 104857600 Nov  3 14:10 test.dat
> adam@somewhere:~ # rclone sync ./foobar onedrive-shared:foobar -Pc --delete-during
> Transferred:   	  100.024M / 100 MBytes, 100%, 2.372 MBytes/s, ETA -
> Errors:                 0
> Checks:                 0 / 0, -
> Transferred:            0 / 1, 0%
> Elapsed time:       42.1s
> Transferring:
>  *                                      test.dat: 100% /100M, 2.610M/s, -
> # running again same command should skip `test.dat`, but it is not:
> adam@somewhere:~ # rclone sync ./foobar onedrive-shared:foobar -Pc --delete-during
> Transferred:   	  100.024M / 100 MBytes, 100%, 2.120 MBytes/s, ETA -
> Errors:                 0
> Checks:                 0 / 0, -
> Transferred:            0 / 1, 0%
> Elapsed time:       47.1s
> Transferring:
>  *                                      test.dat: 100% /100M, 1.886M/s, -
> ```

same issue wit onedrive shared folders..  sync or copy uploading files again...is there an y work around ?

**Comment by Cnly** [comment]
Thank you all for reporting the issues with shared folders. I've got some time to sit down and try to fix the compatibility recently, and now I'd like to ask you to help test things out. You can download the beta here: https://beta.rclone.org/branch/v1.45-043-g108ec53c-onedrive-sharedfolders-beta/ and check if you're still having the problems. Please let me know if there's anything. :)

**Comment by kusmierz** [comment]
nice Christmas present, thank you @Cnly :)

I've tested with my sample data as seen above (`onedrive-shared` is encrypted btw):
```bash
adam@somewhere:~ $ dd if=/dev/urandom of=./foobar/test.dat bs=1024 count=102400
102400+0 records in
102400+0 records out
104857600 bytes (105 MB, 100 MiB) copied, 0.738168 s, 142 MB/s
adam@somewhere:~ $ ll foobar/
total 102412
drwxr-xr-x  2 root root      4096 Dec 26 12:02 .
drwxr-xr-x 50 adam adam      4096 Dec 26 12:02 ..
-rw-r--r--  1 root root 104857600 Dec 26 12:04 test.dat
adam@somewhere:~ $ sha1sum foobar/test.dat 
ce60b5c901d84416fd662f890e9dd8c958879cad  foobar/test.dat
adam@somewhere:~ $ rclone sync ./foobar onedrive-shared:foobar -Pc --delete-during
Transferred:   	  100.024M / 100.024 MBytes, 100%, 419.628 kBytes/s, ETA 0s
Errors:                 0
Checks:                 1 / 1, 100%
Transferred:            1 / 1, 100%
Elapsed time:        4m4s
adam@somewhere:~ $ rclone sync ./foobar onedrive-shared:foobar -Pc --delete-during
Transferred:   	         0 / 0 Bytes, -, 0 Bytes/s, ETA -
Errors:                 0
Checks:                 1 / 1, 100%
Transferred:            0 / 0, -
Elapsed time:        2.4s
# checking even more...
adam@somewhere:~ $ rclone copyto onedrive-shared:foobar/test.dat ./foobar/test.copied.dat
adam@somewhere:~ $ sha1sum foobar/test.copied.dat 
ce60b5c901d84416fd662f890e9dd8c958879cad  foobar/test.copied.dat
adam@somewhere:~ $ diff -s foobar/*
Files foobar/test.copied.dat and foobar/test.dat are identical
adam@somewhere:~ $ rclone ls onedrive-shared:foobar
104857600 test.dat
adam@somewhere:~ $ rclone delete onedrive-shared:foobar/test.dat
adam@somewhere:~ $ rclone ls onedrive-shared:foobar
adam@somewhere:~ $ rclone rmdir onedrive-shared:foobar
adam@somewhere:~ $ rclone ls onedrive-shared:foobar
2018/12/26 12:15:20 ERROR : : error listing: directory not found
2018/12/26 12:15:20 Failed to ls: directory not found
adam@somewhere:~ $ rclone lsd onedrive-shared:
adam@somewhere:~ $ 
```

listing:
```bash
adam@somewhere:~ $ rclone lsd onedrive-shared:
          -1 2018-12-26 12:13:09         1 Photos
          -1 2018-12-26 12:08:50         1 foobar
adam@somewhere:~ $ rclone lsd onedrive-shared:Photos
          -1 2018-12-26 12:13:18        27 Something
adam@somewhere:~ $ rclone lsd onedrive-shared:Photos/Something
          -1 2018-12-26 10:38:24         2 2005
          -1 2018-12-26 10:39:09         3 2006
          -1 2018-12-26 12:13:24         8 2007
          -1 2018-12-26 12:13:22        10 2008
          -1 2018-12-26 12:10:19         6 2009
          -1 2018-12-26 12:13:20         6 2010
          -1 2018-12-26 12:06:12         3 2011
          -1 2018-12-26 12:13:25         9 2012
          -1 2018-12-26 12:13:21         3 2013
          -1 2018-12-26 12:13:23         8 2014
          -1 2018-12-26 12:04:08         5 2015
          -1 2018-12-26 11:58:18         5 2016
          -1 2018-11-03 13:53:27         3 2017
          -1 2018-10-09 10:20:34         8 2018
adam@somewhere:~ $ rclone lsd onedrive-shared:Photos/Something/2005
          -1 2018-12-26 10:38:24         2 10
          -1 2018-12-26 10:36:41        21 Unknown
```

works like a charm as far as I can see :)

now I'm uploading ~250G (20k+ files), I'll post here `rclone sync`'s output later.

**Comment by hogmac** [comment]
This is just great! Thanks @Cnly 

Doing some quick tests - everything for shared folders seems to be working ok as on non-shared ones.  Also renaming over on a mounted drive is also now possible. :)

**Comment by kusmierz** [comment]
First run:
```
Transferred:   	  256.345G / 256.345 GBytes, 100%, 18.806 MBytes/s, ETA 0s
Errors:                 0
Checks:               990 / 990, 100%
Transferred:        25199 / 25199, 100%
Elapsed time:  3h52m38.1s
```
second run:
```
Transferred:   	         0 / 0 Bytes, -, 0 Bytes/s, ETA -
Errors:                 0
Checks:             26186 / 26186, 100%
Transferred:            0 / 0, -
Elapsed time:       43.8s
```
quick check:
```
# find . -type f | wc -l
26186
# touch test
# rclone sync . onedrive-shared:Something -Pu --transfers 50 --delete-during
Transferred:   	        32 / 32 Bytes, 100%, 0 Bytes/s, ETA 0s
Errors:                 0
Checks:             26186 / 26186, 100%
Transferred:            1 / 1, 100%
Elapsed time:       38.7s
# rm test
# rclone sync . onedrive-shared:Something -Pu --transfers 50 --delete-during
je onedrive-photos:Zdjęcia/Moje -Pu --transfers 100 --delete-during
Transferred:   	         0 / 0 Bytes, -, 0 Bytes/s, ETA -
Errors:                 0
Checks:             26187 / 26187, 100%
Transferred:            0 / 0, -
Elapsed time:       40.6s
```
Despite last summary has no info about removed file, but everything seems to work correctly ;)

**Comment by Brandhor** [comment]
> 
> 
> @Brandhor Are you testing with the patched version which you can find here: [#2536 (comment)](https://github.com/ncw/rclone/issues/2536#issuecomment-449932896) ?

yes although unlike the hogmac I can't see the shared folders at all, only the files that I have in my onedrive

**Comment by Cnly** [comment]
> > @Brandhor Are you testing with the patched version which you can find here: [#2536 (comment)](https://github.com/ncw/rclone/issues/2536#issuecomment-449932896) ?
> 
> yes although unlike the hogmac I can't see the shared folders at all, only the files that I have in my onedrive

That would be weird. Can you elaborate on the symptom? Are you sure you can see the shared folders appearing in the "Files" tab of your OneDrive? Those folders should show up in the listing of the root directory no matter what version of rclone you're using.

**Comment by Brandhor** [comment]
> 
> 
> > > @Brandhor Are you testing with the patched version which you can find here: [#2536 (comment)](https://github.com/ncw/rclone/issues/2536#issuecomment-449932896) ?
> > 
> > 
> > yes although unlike the hogmac I can't see the shared folders at all, only the files that I have in my onedrive
> 
> That would be weird. Can you elaborate on the symptom? Are you sure you can see the shared folders appearing in the "Files" tab of your OneDrive? Those folders should show up in the listing of the root directory no matter what version of rclone you're using.

onedrive for business is a bit different, I see the folder under "shared with me" but I can't add them to my files unless I copy the whole folder which is really slow and at that point I would just be accessing my version of the file instead of the shared one

**Comment by fcastilloec** [comment]
@Cnly How do you then sync shared folder on OneDrive Business with rclone? I couldn't find any other issue in Github about this. Should I open a new issue, or is there a workaround that I wasn't able to find?

**Comment by Cnly** [comment]
@fcastilloec I don't think OneDrive Business has an equivalent feature or API. Perhaps you may use SharePoint for that?

**Comment by VGerris** [comment]
Hi, I have the exact same issue with OneDrive Business. My own folder works fine, but the shared folder doesn't appear. Since this is the same option under the config screen, I think this issue should apply? The thing that makes this works on Windows and I suppose MacOS is that when one presses sync in the webinterface, it opens the OneDrive client which makes the mapping in the file browser. Since we have no such client, it doesn't seem to work.
I tried the trial of this tool : https://www.expandrive.com/ and that works, it shows the shared folder, but $49 for a license is kind of crazy if you ask me.

It looks like OneDrive Business is sharepoint, as that is what the domain name suggests when I access it. Hence I tried some options for it, but I'm unable to get the shared folder to show up.
I also tried decoding the token to see if the path is in there readable so I can change it, but it's not. 
It's clearly possible to make this work, it would be great if the devs can shed some light, I'm happy to help out and test.

It also quite apparent that if you want anything to work cross platform, that you have to stay away from Microsoft products. It would have been trivial for them to create a Linux client.

**Comment by VGerris** [comment]
> @Brandhor OneDrive for Business doesn't allow users to add shared folders to their own drives. This issue is only applicable to OneDrive Personal. :)

Hi, this is true when it comes to how to do that in the webinterface. Instead users can use the sync button, which pretty much maps the shared drive IF there is a fat client (Windows/Mac). On Ubuntu, xdg-open is triggered and some link with a tenantID can be seen. That apparently tells the client how to mount it. To fix this in rclone, one way could be to handle that call, but perhaps easier would be to look at how the expandrive tool did it, because it's simply there, just like in the webinterface.

**Comment by VGerris** [comment]
I found a workaround. The shared folder has it's own path which can be reached with webdav.
The config is :
[onedrive]
type = webdav
url = https://domain.sharepoint.com/personal/email_withunderscore_from_shared_user_link/Documents
vendor = sharepoint
user = myemail@domain
pass = encrypted pass

This allows me to have a separate mount to the shared folder which will do for the moment. The proper and preferred way I think  would be to have the shared folders show up in the same share for onedrive, like ExpanDrive does.

**Comment by asdffdsazqqq** [comment]
hello @VGerris,
i have not been able to get your workaround to work.

the shared folder is not listed using `rclone lsd` and the files inside are not listed using `rclone ls`

does your solution still work?

thanks,

**Comment by vanplus** [comment]
You can create shortcut for Shared with me files, then you rclone visit it in 'My files'

[https://github.com/rclone/rclone/issues/4062#issuecomment-1340528773](https://github.com/rclone/rclone/issues/4062#issuecomment-1340528773)

**Comment by RustyClanker** [comment]
The workaround I found was pulling the sharedWithMe listing from the Microsoft Graph API and using the drive_id in a new rclone.conf entry (with my access_token) for the path I was looking for; YMMV.

# rclone: Adding OneDrive Shared Paths

> This is for OneDrive for Business

- Configure OneDrive normally in rclone using your account and generate an access token
- Request `https://graph.microsoft.com/v1.0/me/drive/sharedWithMe` from the Microsoft Graph API using your access token

  ```bash
  curl -H "Content-Type: application/json" -H "Authorization: bearer [access token]" 'https://graph.microsoft.com/v1.0/me/drive/sharedWithMe' > output_file_for_easy_parsing
  ```

- Find the `drive_id` for the shared path in the output file
- In `$HOME/.config/rclone/rclone.conf` add a new entry for the shared path using your access token with the `drive_id` set to the one found in the output file
- Test the entry by running `rclone lsd [SHARED_PATH_ENTRY_NAME]:/[shared_path]`
- The above should return a listing of any containers in it

**Comment by RustyClanker** [comment]
> @RustyClanker hmm rclone could do that as part of the setup or when a `--onedrive-shared-with-me` flag is passed in. Do you want to have a go at making a patch for rclone to do that?

@ncw I haven't done any Go programming, but I'm not adverse to poking around and seeing if I can get something working. And I apologize, I should have paid attention to this issue being closed and responded to issue [4062](https://github.com/rclone/rclone/issues/4062) instead.

**Comment by KDreynolds** [comment]
If needed, I can take a crack at this.
