### ISSUE TITLE
Feature Request: Don't show global flags in `rclone <cmd> --help`

### ISSUE THREAD

**Issue by sgsunder** [ncw/rclone#2541]
When using the `rclone <cmd> --help` to lookup the usage of a subcommand, most of the output is taken up by the list of global flags. This forces users to scroll up a lot just to see the relevant help text for the command.

Instead I would suggest moving this list of global flags to a command like `rclone --help globalflags` or similar, and add a note like `Use "rclone --help globalflags" for more information about global flags.` on the bottom of every other help command.

**Comment by ncw** [comment]
Excellent idea!  I had the same thought myself but didn't manage to squeeze it into the 1.43 release.

I was thinking to remove all the backend flags which would remove 257 of the flags (but show them with --help backend or some other flag), but that still leaves 92.  This would make the default output look like rsync which has 132 flags by default.

Do you think that would be enough of a fix?

I like your idea of chopping all the global flags off for `rclone command --help`. What about for `rclone help`?  or just `rclone`?

Another thing I could do is curate the Global flags, so by default not show the backend flags or the less important flags.  I get a list of about 60 if I do that.

Another idea would be to split the flags up so only the flags which apply to any given command are shown.  This would be quite tricky and wouldn't cut the list down at all in some important cases (eg `sync` or `copy` or `move`)

What I'd like to see most is if anyone has any prior art on this.  What do other programs with 100s of options do?

**Comment by sgsunder** [comment]
For anyone reading this experiencing the same issue:
A quick workaround right now is to run `rclone <cmd> --help | sed '/Global Flags:/,$d'`
____________________

I've only started using rclone about a week ago, so I'm not sure what would be the most syntax-consistent way of doing this, but this would be my suggestion:

- As already mentioned, `rclone <cmd> --help` and `rclone help <cmd>` can drop all the global flags.
- `rclone`, `rclone --help`, and `rclone help` will show the following: 

```
Rclone is a command line program to sync files and directories to and
from various cloud storage systems and using file transfer services.

Features

  * MD5/SHA1 hashes checked at all times for file integrity
  * Timestamps preserved on files
  * Partial syncs supported on a whole file basis
  * Copy mode to just copy new/changed files
  * Sync (one way) mode to make a directory identical
  * Check mode to check for file hash equality
  * Can sync to and from network, eg two different cloud accounts

See the home page for installation, usage, documentation, changelog
and configuration walkthroughs.

  * https://rclone.org/

Usage:
  rclone [flags]
  rclone [command]

Use "rclone help flags" for more information about global flags.
Use "rclone help commands" for more information about subcommands.
Use "rclone help services" for a list of supported services.
```

- `rclone help flags` will show the list of global flags (basically the output of `rclone help | sed '0,/Flags:/d'` on the current version)
- `rclone help commands` will show the list of commands (basically the output of `rclone help | sed '0,/Available Commands:/d' | sed '/Flags:/,$d'` on the current version)
- `rclone help services` will show the list of services that's printed at the top of the current `rclone help` command

**Comment by ncw** [comment]
I like it.

I'd probably use `rclone help backends`.  Then that leads on to `rclone help backend s3` to just see the s3 flags.  rclone could show the environment variable and config file equivalents too.

Perhaps an `rclone help all` to show everything like it does at the moment.

Do you fancy working on this BTW?

**Comment by sgsunder** [comment]
Sounds good!

I'm not sure if/when I would have a chance to contribute, but feel free to keep pinging me for input, etc.

**Comment by ncw** [comment]
@sgsunder no worries.  I'll try to get this done for 1.44 using your ideas above.

**Comment by sgsunder** [comment]
I like it!

Two small things I've noticed:

1. `./rclone --help | less -N` spits out this string on line 32:

```
help            Sync files and directories to and from local and remote object stores - v1.43-129-ge4538afe-help-beta
```
Which I'm guessing is just a simple typo or copy/paste error somewhere in the code.

2. When viewing help information for a subcommand, e.g `rclone copy --help`, the bottom text will say:

```
Use "rclone copy [command] --help" for more information about a command.
```
instead of 
```
Use "rclone [command] --help" for more information about a command.
```

I'm not sure if this is intentional or not, but it might be confusing for other users. This may make sense for subcommands which have their own sub-subcommands, but it seems misleading for simpler commands like `copy`

**Comment by ncw** [comment]
I've fixed those things (and a few other little niggles) here:

https://beta.rclone.org/branch/v1.43-135-gef5adbb0-help-beta/ (uploaded in 15-30 mins)

Hopefully I haven't broken anything else!

**Comment by ncw** [comment]
I've merged this to master now so it will be in [the latest beta](https://beta.rclone.org) in 15-30 mins and in v1.44

Thank you for suggesting the changes and testing them :-)

Let me know if there is anything else you think needs fixing.
