### ISSUE TITLE
Question: confirm --fast-list for Drive is working

### ISSUE THREAD

**Issue by drpau** [ncw/rclone#2542]
#### What is the problem you are having with rclone?

Not a problem but a question.  Does the --fast-list command only work when mounting a Google Drive mount directly, or does it work if the mount is:
Gdrive -->cache-->crypt

I have gone through the "advanced config" in the wizard across all remotes, and can not see a reference to --fast-list therefore i am putting it in my command to launch rclone.  But because my rclone mount command, mounts a crypt remote, is it applying the --fast-list to the crypt remote only?  If so, how do i enable it against my remote called [gdrive_mount]?

#### What is your rclone version (eg output from `rclone -V`)
1.43-039

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Linux Syn 3.10.105 #23739 SMP Tue Jul 10 00:16:03 CST 2018 x86_64 GNU/Linux synology_braswell_916+

####  Which cloud storage system are you using? (eg Google Drive)
Google Drive

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
/volume1/rclone1.43-039/rclone mount this_one: /mnt/gdrive.de/ --allow-other --config=/volume1/rclone1.43.conf --fast-list --cache-db-path=/volumeUSB1/usbshare > /tmp/rclone.log 2>&1 &

#### a copy of my config

```
ash-4.3# cat ../rclone1.43.conf
[gdrive_mount]
type = drive
client_id = *********
client_secret = *********
scope = drive
root_folder_id =
service_account_file =
token = *********

[cache]
type = cache
remote = gdrive_mount:
plex_url = http://127.0.0.1:32400
plex_username = drp
plex_password = *********
chunk_size = 5M
info_age = 12h
chunk_total_size = 400G
plex_token = *********

[this_one]
type = crypt
remote = cache:
filename_encryption = standard
directory_name_encryption = true
password = *********
password2 = *********

ash-4.3#
```

**Comment by drpau** [comment]
No problems - thank you, yes it does answer it. Hopefully it will work soon with mount 👍 thanks again.

**Comment by B4dM4n** [comment]
Notice that `--fast-list` for the drive backend is only faster when listing many folders. Up to around 200 folders the normal listing can be faster than `--fast-list`.

There is also a way to use `--fast-list` with mount. The [cache/refresh](https://rclone.org/rc/#vfs-refresh-refresh-the-directory-cache) rc command will use the `--fast-list` implementation for updating the directory cache of a whole directory tree.

**Comment by ncw** [comment]
> There is also a way to use --fast-list with mount. The cache/refresh rc command will use the --fast-list implementation for updating the directory cache of a whole directory tree.

I'd forgotten about that - excellent feature @B4dM4n :-)

**Comment by tcf909** [comment]
running rclone rc cache/refresh results in a 405 status.

Did cache/refresh ever get implemented? I don't see it documented on the website.

**Comment by B4dM4n** [comment]
It is implemented and documented:
https://rclone.org/rc/#vfs-refresh-refresh-the-directory-cache

Can you post the used commands and the output of `rclone version`?

**Comment by B4dM4n** [comment]
`vfs/refresh` will only refresh the dir cache, which is controlled by `--dir-cache-time`, by forcing a directory listing of the mounted remote.

 When using cache, this would only read what the cache remote has stored.

I'm closing this issue, since it is about `--fast-list` and answered. If you still have a problem with `vfs/refresh`, feel free to open a new issue.
