### ISSUE TITLE
Add chunked files to integration tests

### ISSUE THREAD

**Issue by ncw** [ncw/rclone#2549]
In order to avoid a repeat of #2518 we need to implement some integration tests for doing chunked uploads of files.

This needs to test the chunking but also upload a small file to save on the costs of the integration tests!

This might need a bit of config per backend to say what size of file to upload to test the chunked uploading .

Maybe a function to set set the `chunk-size` parameter to minimize the size of the file which needs to be uploaded.

This needs to happen for all remotes, so maybe it should error if the parameters aren't set.

**Comment by B4dM4n** [comment]
A easy way to pass the config would be to use the `fstests.Opt` struct with a optional test only interface to set the `Fs` chunk size.
```go
// fstests.go
package fstests

type ChunkedUploadConfig struct {
	// Minimum allowed chunk size
	MinChunkSize fs.SizeSuffix
	// Maximum allowed chunk size, <= 0 is no limit
	MaxChunkSize fs.SizeSuffix
	// Rounds the given chunk size up to the next valid value
	// nil will disable rounding
	// e.g. the next power of 2
	CeilChunkSize func(fs.SizeSuffix) fs.SizeSuffix
}

// SetUploadChunkSizer is a test only interface to change the configured UploadChunkSize at runtime.
type SetUploadChunkSizer interface {
	// Change the configured ChunkSize.
	// Will only be called while no transfer is in progress
	SetUploadChunkSize(fs.SizeSuffix) error
}

// Opt is options for Run
type Opt struct {
	...
	ChunkedUpload            ChunkedUploadConfig
}
```
The zero value of `ChunkedUploadConfig` would be valid and represent no lower limit, no upper limit and no rounding function. The only difference would be if the `Fs` implements `fstests.SetUploadChunkSizer` or not.
This should be done for tests only, to avoid changing the chunk size during normal operation.
For the drive backend the implementation would look like this:
```go
// drive_test.go
package drive

func TestIntegration(t *testing.T) {
	fstests.Run(t, &fstests.Opt{
		RemoteName: "TestDrive:",
		NilObject:  (*Object)(nil),
		ChunkedUpload: fstests.ChunkedUploadConfig{
			MinChunkSize:  minimumChunkSize,
			CeilChunkSize: fstests.NextPowerOfTwo,
		},
	})
}

func (f *Fs) SetUploadChunkSize(cs fs.SizeSuffix) error {
	return f.setUploadChunkSize(cs)
}

var _ fstests.SetUploadChunkSizer = (*Fs)(nil)

// drive.go
package drive

func (f *Fs) setUploadChunkSize(cs fs.SizeSuffix) error {
	if !isPowerOfTwo(int64(cs)) {
		return errors.Errorf("%v isn't a power of two", cs)
	}
	if cs < minimumChunkSize {
		return errors.Errorf("%s is less than %s", cs, minimumChunkSize)
	}
	f.opt.ChunkSize = cs
	return nil
}
```

Based on the returned settings, the integration test can generate a few values between min and max, use the `CeilChunkSize` func to allow the `Fs` to round the generated number to a valid value and update the configured value using the `SetUploadChunkSizer` interface.

Is this be the kind of configuration you had in mind?

**Comment by ncw** [comment]
> Is this be the kind of configuration you had in mind?

I think that looks very comprehensive :-)  

`SetUploadChunkSize` should probably return the old value so it can be reset by the tests.

Were you thinking that if the remote didn't define `SetUploadChunkSize` it would try some larger uploads anyway?  I think that is a good idea!

I made an io.Reader for this sort of testing which might be useful...

https://github.com/ncw/rclone/blob/e07a850be3b360dc74916440bd548e35a46afd78/backend/jottacloud/jottacloud_internal_test.go#L14-L32

As for how big the uploads and downloads should be...
s3 costs $0.09p/GB (gcs, azure etc are similar)...

So assuming we are uploading then downloading the file then deleting it, I'd like to keep the data transfer under 300MB ideally which we would transfer 150MB of files up then transfer them down again.  This will put my bills up by ~$1/month for s3 (similar for gcs and azure).  I can live with that!

These tests will be run on home internet connections too.  Mine is 50 Mbit/s down and 20 Mbit/s up so 150 MB would take 24 seconds to upload and 60 seconds to download (theoretically).  However some of the providers are quite slow with transfers of ~1MB/s :-(

So I think smaller total data transfer is better!  Maybe we could have a flag to enable larger data transfer or set the max transferred data? What do you think?

Do you want to work on this issue?

**Comment by B4dM4n** [comment]
> SetUploadChunkSize should probably return the old value so it can be reset by the tests.

Good point, resetting the `Fs` to the state before the test is the correct way.

> As for how big the uploads and downloads should be...

For most remotes this doesn't need to be big. Only `drive` (`256 k`), `onedrive` (`320 k`) and `b2` (`5 M`) have minimum chunk sizes and only `b2` is paid, so the test sizes can be small, e.g. start at `10 k` up to `1 M`. The values should be a combination of `uneven`, `factor 10` and `power of 2` to find broken block calculations.

The final numbers should depend on the number of test combinations.

> Maybe we could have a flag to enable larger data transfer or set the max transferred data? What do you think?

A configurable `max-chunk-size` flag or similar would be nice. This could be used to reduce the regular transfer volume and perform more extensive tests before a release.

> Do you want to work on this issue?

Sure , I can work on this. The scaffolding is already done. just the actual test is missing :smile:
https://github.com/B4dM4n/rclone/tree/fstest-chunked-upload

**Comment by ncw** [comment]
This is done now - closing :-)
