### ISSUE TITLE
Google Drive: Only sync files owned by authenticated user

### ISSUE THREAD

**Issue by bjornharrtell** [ncw/rclone#255]
Firstly, thanks alot for rclone I like it alot. :)

I'm missing but one thing, or at least I fail to understand how it can be done. I'd like to sync only the files that I own as the authenticated user. This information is in the file resource metadata for Google Drive (https://developers.google.com/drive/v2/reference/files) `isAuthenticatedUser` in `owners`.

PS. I actually made a google drive sync program in Scala a while back that works but has a flawed sync logic which I think rclone seem to do much better. In my program I use the mentioned metadata to only consider owned files. For reference that code is here:
https://github.com/bjornharrtell/gdrivesync/blob/master/src/main/scala/org/wololo/gdrivesync/DriveMetaFetcher.scala#L44

**Comment by ncw** [comment]
Sorry missed this issue when it came in!

What do you think about adding a flag for this?  `--drive-authenticated-only` or something like that?

Fancy having a go at a patch?

**Comment by bjornharrtell** [comment]
Yes I'll have a go :) Perhaps `--drive-auth-owner-only`?

**Comment by ncw** [comment]
Sounds good!

**Comment by bjornharrtell** [comment]
Thinking it might make sense to add an bool Owned property to the Object interface and support this case with a filer (perhaps only supported by Drive)... what do you think?

**Comment by ncw** [comment]
I'd say just make it for drive with a flag for the first attempt - I'd like to get the feature working first, before thinking about generalizing it.

**Comment by ncw** [comment]
This fix for this is merged - thank you very much!  It will be in the next release.
