### ISSUE TITLE
Allow -V/--version option without decrypting config

### ISSUE THREAD

**Issue by pgalbavy-itrs** [ncw/rclone#2551]
#### What is the problem you are having with rclone?

"rclone -V" prompts me to decrypt my config file

#### What is your rclone version (eg output from `rclone -V`)

wish I knew... that's sort of the problem. But in reality it's 1.38

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

Linux / Windows

####  Which cloud storage system are you using? (eg Google Drive)

Various

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

rclone -V

**Comment by sjug** [comment]
This is fixed in current versions of rclone at least in 1.42+

**Comment by ncw** [comment]
@sjug yes you are right, this is fixed in the latest rclone.

I shall close this now then :-)
