### ISSUE TITLE
Unable to Sync OneDrive to another

### ISSUE THREAD

**Issue by HitmanUK1** [ncw/rclone#2559]
This used to work stop maybe 2 weeks ago.
Getting the following Errors:

2018/09/09 00:32:34 ERROR : : error reading destination directory: couldn't list files: unauthenticated: invalidSignature: Token contains invalid signature.
2018/09/09 00:32:34 INFO  : One drive root 'Work/1': Waiting for checks to finish
2018/09/09 00:32:34 INFO  : One drive root 'Work/1': Waiting for transfers to finish
2018/09/09 00:32:34 ERROR : One drive root 'Work/1': not deleting files as there were IO errors
2018/09/09 00:32:34 ERROR : One drive root 'Work/1': not deleting directories as there were IO errors
2018/09/09 00:32:34 ERROR : Attempt 1/3 failed with 1 errors and: not deleting files as there were IO errors
2018/09/09 00:32:34 ERROR : : error reading destination directory: couldn't list files: unauthenticated: invalidSignature: Token contains invalid signature.
2018/09/09 00:32:34 INFO  : One drive root 'Work/1': Waiting for checks to finish
2018/09/09 00:32:34 INFO  : One drive root 'Work/1': Waiting for transfers to finish
2018/09/09 00:32:34 ERROR : One drive root 'Work/1': not deleting files as there were IO errors
2018/09/09 00:32:34 ERROR : One drive root 'Work/1': not deleting directories as there were IO errors
2018/09/09 00:32:34 ERROR : Attempt 2/3 failed with 1 errors and: not deleting files as there were IO errors
2018/09/09 00:32:34 ERROR : : error reading destination directory: couldn't list files: unauthenticated: invalidSignature: Token contains invalid signature.
2018/09/09 00:32:34 INFO  : One drive root 'Work/1': Waiting for checks to finish
2018/09/09 00:32:34 INFO  : One drive root 'Work/1': Waiting for transfers to finish
2018/09/09 00:32:34 ERROR : One drive root 'Work/1': not deleting files as there were IO errors
2018/09/09 00:32:34 ERROR : One drive root 'Work/1': not deleting directories as there were IO errors
2018/09/09 00:32:34 ERROR : Attempt 3/3 failed with 1 errors and: not deleting files as there were IO errors
2018/09/09 00:32:34 Failed to sync: not deleting files as there were IO errors

I have tried to delete the folder but getting the same isssue, if I can the location I get the following:
2018/09/09 00:35:28 DEBUG : Using config file from "/boot/config/plugins/rclone/.rclone.conf"
2018/09/09 00:35:30 ERROR : 2/bookmark - IE.htm: Failed to copy: failed to make directory: unauthenticated: invalidSignature: Token contains invalid signature.
2018/09/09 00:35:31 ERROR : 2/Projects/Setup DRAC Management on PRTG.docx: Failed to copy: failed to make directory: unauthenticated: invalidSignature: Token contains invalid signature.
2018/09/09 00:35:32 ERROR : Information/Documents/17468C10: Failed to copy: failed to make directory: unauthenticated: invalidSignature: Token contains invalid signature.

Unsure if this a new M$ change but any help would be super, I like to sync work Onedrive to my Personal.

Thanks,

**Comment by Cnly** [comment]
Hi @HitmanUK1,
Could you please provide the following details so we can diagnose the problem more easily:

- Rclone version (eg output from rclone -V)
- Which OS you are using and how many bits (eg Windows 7, 64 bit)
- The command you were trying to run (eg rclone copy /tmp remote:tmp)
- A log of the command with the -vv flag (eg output from rclone -vv copy /tmp remote:tmp) (If the log contains secrets then edit the file with a text editor first to obscure them)

Thanks!

**Comment by HitmanUK1** [comment]
Rclone: Version "v1.43.1" starting with parameters
Ubuntu and Docker
rclone copy OneDrive-CNC:Desktop OneDrive-PT:Work/CNC --no-update-modtime --ignore-existing -v

rclone copy OneDrive-1:Desktop OneDrive-PT:Work/1 --no-update-modtime --ignore-existing -vv2018/09/09 16:03:23 DEBUG : rclone: Version "v1.43.1" starting with parameters ["rcloneorig" "--config" "/boot/config/plugins/rclone/.rclone.conf" "copy" "OneDrive-1:Desktop" "OneDrive-PT:Work/1" "--no-update-modtime" "--ignore-existing" "-vv"]
2018/09/09 16:03:23 DEBUG : Using config file from "/boot/config/plugins/rclone/.rclone.conf"
2018/09/09 16:03:24 DEBUG : Keeping previous permissions for config file: -rwxrwxrwx
2018/09/09 16:03:24 DEBUG : OneDrive-1: Saved new token in config file
2018/09/09 16:03:26 DEBUG : Keeping previous permissions for config file: -rwxrwxrwx
2018/09/09 16:03:26 DEBUG : OneDrive-PT: Saved new token in config file
2018/09/09 16:03:28 ERROR : : error reading destination directory: couldn't list files: unauthenticated: invalidSignature: Token contains invalid signature.
2018/09/09 16:03:28 INFO  : One drive root 'Work/1': Waiting for checks to finish
2018/09/09 16:03:28 INFO  : One drive root 'Work/1': Waiting for transfers to finish
2018/09/09 16:03:28 ERROR : Attempt 1/3 failed with 1 errors
2018/09/09 16:03:28 ERROR : : error reading destination directory: couldn't list files: unauthenticated: invalidSignature: Token contains invalid signature.
2018/09/09 16:03:28 INFO  : One drive root 'Work/1': Waiting for checks to finish
2018/09/09 16:03:28 INFO  : One drive root 'Work/1': Waiting for transfers to finish
2018/09/09 16:03:28 ERROR : Attempt 2/3 failed with 1 errors
2018/09/09 16:03:28 ERROR : : error reading destination directory: couldn't list files: unauthenticated: invalidSignature: Token contains invalid signature.
2018/09/09 16:03:28 INFO  : One drive root 'Work/1': Waiting for checks to finish
2018/09/09 16:03:28 INFO  : One drive root 'Work/1': Waiting for transfers to finish
2018/09/09 16:03:28 ERROR : Attempt 3/3 failed with 1 errors
2018/09/09 16:03:28 INFO  :
Transferred:             0 / 0 Bytes, -, 0 Bytes/s, ETA -
Errors:                 1
Checks:                 0 / 0, -
Transferred:            0 / 0, -
Elapsed time:        5.5s

2018/09/09 16:03:28 DEBUG : 14 go routines active

**Comment by Cnly** [comment]
Thanks @HitmanUK1, but rclone v1.43.1 is still using the legacy and deprecated API for OneDrive. Could you have a try with the latest beta version, which comes with the new Graph API (currently https://beta.rclone.org/v1.43-057-g5b1c162f-beta/)? Note that rclone may ask you to re-configure your OneDrive backends.

**Comment by HitmanUK1** [comment]
Thanks for getting back to me so quick, see below the error I get when trying to setup the new API:

2018/09/09 16:36:00 Failed to query available drives: HTTP error 401 (401 Unauthorized) returned body: "{\r\n  \"error\": {\r\n    \"code\": \"InvalidAuthenticationToken\",\r\n    \"message\": \"CompactToken parsing failed with error code: 8004920A\",\r\n    \"innerError\": {\r\n      \"request-id\": \"645dce49-cff3-45e9-9a01-ecc500f67c10\",\r\n      \"date\": \"2018-09-09T15:36:00\"\r\n    }\r\n  }\r\n}"

**Comment by Cnly** [comment]
@HitmanUK1 Are you using custom Client ID / Key? If so, please try setting them back to default, or getting a new pair [here](https://github.com/ncw/rclone/blob/master/docs/content/onedrive.md#getting-your-own-client-id-and-key), as Client ID / Key for the old and new API aren't compatible.

**Comment by HitmanUK1** [comment]
Hi, Can confirm that the issue is with the Plugin/Docker itself, as it works perfectly on windows.
Thanks for your help.

**Comment by HitmanUK1** [comment]
Sorry, tried again and getting the same issue on Windows too..
Can confirm I wasn't using a Client ID / Key, Have tried but getting a error saying Microsoft cant proceed with request.

**Comment by chenxuuu** [comment]
I have the same problem in 1.43.1 
but I try this in 1.43-125 , it's ok
