### ISSUE TITLE
Please add rclone.1 to the repository

### ISSUE THREAD

**Issue by yurivict** [ncw/rclone#256]
My package manager tells me that installing 'pandoc' will take an additional 3GB of disk space. This is a lot for converting just one man page.

**Comment by ncw** [comment]
I'm not keen on adding auto generated files to the repository.  The pandoc usage is rather excessive though!

What is your use case?

**Comment by yurivict** [comment]
I made the FreeBSD package for rclone. But I had to exclude the man page because of this problem. It is easy to build rclone itself, but then just to build the one small man page you need  to cause the build process to rebuild 3GB worth of binaries, pulled by pandoc. This seems excessive.

**Comment by ncw** [comment]
OK I'll do this for the next release (I'll check in the other forms of the manual as well).
