### ISSUE TITLE
rclone mount with sharepoint(webdav), Got 403 FORBIDDEN whenever it running time close to 24 hours

### ISSUE THREAD

**Issue by xiaolei0125** [ncw/rclone#2562]
Please refer to rclone forum： [403 FORBIDDEN WebDev problem](https://forum.rclone.org/t/403-forbidden-webdev-problem/6290)

**This is my webdav sharepoint config and command:**
my rclone config for webdav sharepoint
[od1]
type = webdav
url = https://xxx-my.sharepoint.com/personal/xxxx_edu/Documents
vendor = sharepoint
user = xxxx@xxxx.edu
pass = xxxxxxx

Run rclone mount:
`rclone mount --dump headers --log-level DEBUG --allow-other od1: /mnt/od1 --syslog &`

**Error Message**
I can’t access /mnt/od1 whenever the “rclone mount” running time is close to 24 hours.
`ls /mnt/od1/
ls: reading directory ‘/mnt/od1/’: Input/output error
`

The debug error message for rclone mount is :
`rclone[5204]: /: >ReadDirAll: item=-1, err=couldn’t list files: 403 FORBIDDEN: 403 FORBIDDEN
X-Msdavext_error: 917656; Access denied. Before opening files in this location， you must first browse to the website and select the option to login automatically
`

I need to kill rclone mount and rerun to make it normal.

**Comment by xiaolei0125** [comment]
**I google and find this:** 
 [Problem with connecting to SharePoint Online in Office 365 with PowerShell, SharePoint Designer and other 3. party tools](https://blog.areflyen.no/2017/06/18/problem-with-connecting-to-sharepoint-online-in-office-365-with-powershell-sharepoint-designer-and-other-3-party-tools/)

**This is it suggested solution:**
1. Start using modern authentication (recommended)
2. Re-enable support for legacy apps (temporary fix)
Using “SharePoint Online Management Shell” login in with “Connect-SPOService”.

But I am not a manager of sharepoint, I don't have the authority to do these.

**Comment by xiaolei0125** [comment]
`rcloue mount` did work at beginning, then stop working after about 24 hours(close to).

I need to kill rclone mount and rerun it make rclone mount working again.

@ncw As you said, that probably means the token(cookie/session) expired for sharepoint(webdav).

Is there a solution that refresh token to work around this issue?

**Comment by ncw** [comment]
@hensur since you contributed this code originally, do you have any ideas here?

Do we know how long the cookie should last?  If so maybe we should just set a timer to refresh it every 12 hours (say).

What do you think?

**Comment by xiaolei0125** [comment]
@hensur Do you have time to help check this issue?  thanks.

**Comment by hensur** [comment]
@xiaolei0125 yes, I'll look into it.

**Comment by ncw** [comment]
Yyou might find this helpful @hensur 

https://github.com/ncw/rclone/blob/b18595ae07473937de6c2dd8de90dd81376c47a2/lib/oauthutil/renew.go#L17-L22

Which is a system for renewing oauth2 tokens.  Or it might be overkill - maybe just renewing the sharepoint cookie every 12 hours will be enough...

**Comment by hensur** [comment]
Sharepoint returns Session Cookies, they don't have a expiry date. I think we can only guess that the session will probably expire after 24 hours.

Thanks for the hint @ncw :)
I had a look at it, but I think it might be overkill, as you already said. I think it should be enough to just request new cookies after 12hrs and set them again in the http client.

I just created a simple cookieRenew struct in the odrvcookie package:
https://github.com/hensur/rclone/tree/bugfix-2562

I'll leave it running for some time to check if this solves the problem. :)

**Comment by ncw** [comment]
@hensur wrote
> Sharepoint returns Session Cookies, they don't have a expiry date. I think we can only guess that the session will probably expire after 24 hours.

Seems plausible!

> Thanks for the hint @ncw :)
> I had a look at it, but I think it might be overkill, as you already said. I think it should be enough to just request new cookies after 12hrs and set them again in the http client.

Sounds fine to me.

> I just created a simple cookieRenew struct in the odrvcookie package:
> https://github.com/hensur/rclone/tree/bugfix-2562
> 
> I'll leave it running for some time to check if this solves the problem. :)

Ace!

**Comment by xiaolei0125** [comment]
@hensur  Is there a version I can help with testing?

**Comment by ncw** [comment]
I pulled @hensur 's branch and pushed it to the rclone repo to make a beta for you to test @xiaolei0125 

https://beta.rclone.org/branch/v1.43-077-gecb3f043-hensur-bugfix-2562-beta/ (uploaded in 15-30 mins)

**Comment by ncw** [comment]
@hensur want to make a pull request from that branch?

**Comment by hensur** [comment]
@ncw here it is: https://github.com/ncw/rclone/pull/2611
My rclone mount is still working as well. I think the fix works :)

**Comment by ncw** [comment]
Ace!  I've merged the PR here

https://beta.rclone.org/v1.43-116-g22ac80e8-beta/ (uploaded in 15-30 mins)

this will be in [the latest beta](https://beta.rclone.org) then and in 1.44 - thank you @hensur :-)
