### ISSUE TITLE
x509: certificate signed by unknown authority 

### ISSUE THREAD

**Issue by tony-sunjian** [ncw/rclone#2566]
#### What is the problem you are having with rclone?
when i input the verification code> rclone can not get the token, and returns --->
 Failed to configure token: failed to get token: Post https://accounts.google.com/o/oauth2/token: x509: certificate signed by unknown authority 

#### What is your rclone version (eg output from `rclone -V`)
rclone v1.43.1
- os/arch: linux/mipsle
- go version: go1.11

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
 linux/mipsle

####  Which cloud storage system are you using? (eg Google Drive)
google drive

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
./rclone config

**Comment by tony-sunjian** [comment]
i used it on an openwrt device,      system:  LEDE14.07  CPU: mt7621a

**Comment by B4dM4n** [comment]
The device is probably missing the system CA certificates. 
Installing https://openwrt.org/packages/pkgdata/ca-bundle could help.

**Comment by tony-sunjian** [comment]
@B4dM4n  it is useful , Install PKG_NAME：ca-certificates,  can figure it out

thank you so much

**Comment by 1265578519** [comment]
--no-check-certificate 我找到解决办法了！
https://github.com/rclone/rclone/issues/6928
