### ISSUE TITLE
Add option to delete file/folder in `rclone ncdu`

### ISSUE THREAD

**Issue by NurdTurd** [ncw/rclone#2571]
Add option to delete file/folder in `rclone ncdu`

As in, you are over a file and can hit `d` like in normal `ncdu`.

**Comment by ncw** [comment]
I've wanted this a lot but haven't had time to implement it.

Fancy giving it a go?

**Comment by NurdTurd** [comment]
I don't know a thing about Go unfortunately, was hoping someone else would write out the feature. 😕

**Comment by ncw** [comment]
No worries, someone (maybe even me!) will get round to it sooner or later I'm sure :-)

**Comment by ncw** [comment]
@hensur you rock - thank you!

**Comment by NurdTurd** [comment]
@hensur Thank you so much!

**Comment by NurdTurd** [comment]
So will this be introduced in the next version of rclone?

**Comment by ncw** [comment]
I've just merged this - thank you @hensur so find it in [the latest beta](https://beta.rclone.org) in 15-30 mins and in v1.45 :-)
