### ISSUE TITLE
Webdav error listing

### ISSUE THREAD

**Issue by Sergi0O** [ncw/rclone#2574]
Hello, I am trying to use rclone with my university webdav folder, but when I run `ls` command I receive the following error:

`2018/09/12 22:34:41 ERROR : : error listing: couldn't list files: parsing time "Fri, 7 Sep 2018 08:49:58 GMT" as "Mon Jan _2 15:04:05 MST 2006": cannot parse ", 7 Sep 2018 08:49:58 GMT" as " "`

When I list only directories `lsd` and there is no file it works fine.
I am using rclone v1.43.1 with Windows and Manjaro Linux.

**Comment by ncw** [comment]
This is your universities server not following the RFC which states that RFC1123 time should be used which has leading 0s!  I have put a work-around into rclone here:

Can you give it a test please?

https://beta.rclone.org/branch/v1.43-075-g4b67c9ad-fix-2574-webdav-time-beta/ (uploaded in 15-30 mins)

**Comment by Sergi0O** [comment]
> This is your universities server not following the RFC which states that RFC1123 time should be used which has leading 0s! I have put a work-around into rclone here:
> 
> Can you give it a test please?
> 
> https://beta.rclone.org/branch/v1.43-075-g4b67c9ad-fix-2574-webdav-time-beta/ (uploaded in 15-30 mins)

It works now, thank you.

**Comment by ncw** [comment]
Thanks for testing.  I've merged that to master now and it will be in [the latest beta](https://beta.rclone.org) in 15-30 mins and in v1.44 when released.
