### ISSUE TITLE
Rclone RC - Add support for CORS to http interface

### ISSUE THREAD

**Issue by frenos** [ncw/rclone#2575]
Hey,
just a little feature request for the rc http interface.

I'm currently building a small angular app to display the status of rclone and in the future also allow changing settings. It's supposed to fully run in your browser and communicate directly with rclone, without any backend etc.

Currently we can't access the http interface directly from a browser because every browser sends an "OPTIONS" request first to check for CORS.

Can we get a either a flag to add our specific sites or a flag to turn CORS off (e.g. set Access-Control-Allow-Origin: *)?

#### What is your rclone version (eg output from `rclone -V`)
rclone v1.43.1
- os/arch: linux/amd64
- go version: go1.11

**Comment by ncw** [comment]
I don't know a great deal about CORS but in principle I'm fine with this.  Perhaps a flag to control the CORS setting for rc would be the best option? Is turning it off unconditionally safe?

Another thing that comes to mind is that rclone rc could serve your html/js/css files which would mean that CORS wouldn't be necessary?

**Comment by frenos** [comment]
If we could give a folder for rclone rc to serve, that would also work fine. Depends on what is easier to implement.
I don't think allowing everything will worsen security as currently rclone takes post request from anywhere, it's just the browser that blocks them. So if I turn off all the security features in the browser it works fine. Currently I proxy all requests through a small python server on my dev machine.

So to implement CORS with the same security implications as now (e.g. no security and allow everyone to make requests) we need two things:

1. Also allow OPTIONS requests, the response body doesn't matter.
2. Send the header "Access-Control-Allow-Origin: *" with every response.

I started looking at the source but have never programmed in go. If I can get something done I'll open a pull request. But I am of course grateful for everyone taking time to implement this or even give hints where to look in the code.

**Comment by ncw** [comment]
Here is a rough outline of what would need to be done.

# For step 1 - OPTIONS

The http handler is here

https://github.com/ncw/rclone/blob/b3d8bc61aceabae9e1dc927a60c21f8444add1ba/fs/rc/rc.go#L80

What is in that function needs factoring into a different function `handlePOST` say, and that function needs to dispatch on `r.Method` for `POST` and `OPTIONS` - you'd write the `handleOPTIONS` function.

This would open the door to serving GET requests for serving the index etc...

# For step 2 - add CORS

What you want to do is in the main handler function add something like:

```go
                w.Header().Add("Access-Control-Allow-Origin", "*")
```

**Comment by ncw** [comment]
I'll close this since it is done!
