### ISSUE TITLE
rclone linux do not work if folder got : mark

### ISSUE THREAD

**Issue by jlahtela** [ncw/rclone#2576]
#### What is the problem you are having with rclone?
I try to lsd or copy folder with : mark it is not possible to do.
It it is "path" anything after it do not work

Example command
rclonde lds B2:foler1/dos:/folder2

#### What is your rclone version (eg output from `rclone -V`)
rclone v1.43.1
- os/arch: linux/amd64
- go version: go1.11

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Manjaro

####  Which cloud storage system are you using? (eg Google Drive)
BackBlaze B2

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclonde lds B2:foler1/dos:/folder2
rclone copy B2:foler2/dos:/folder2 B2:newbucket/newfolder

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
[jesse@Paradox ~]$ rclone -vv lsd B2:BackupPunakone/CBB_PUNAKONE/c:/users
2018/09/13 23:00:40 DEBUG : rclone: Version "v1.43.1" starting with parameters ["rclone" "-vv" "lsd" "B2:BackupPunakone/CBB_PUNAKONE/c:/users"]
2018/09/13 23:00:40 DEBUG : Using config file from "/home/jesse/.config/rclone/rclone.conf"
2018/09/13 23:01:01 DEBUG : 4 go routines active
2018/09/13 23:01:01 DEBUG : rclone: Version "v1.43.1" finishing with parameters ["rclone" "-vv" "lsd" "B2:BackupPunakone/CBB_PUNAKONE/c:/users"]
[jesse@Paradox ~]$

**Comment by jlahtela** [comment]
Actually something odd going on... because today darning day this worked on Windows computer.
No it do not work even with it!

**Comment by ncw** [comment]
I think the problem you are having here is that b2 can't store **empty** folders.  If you put a file in the folder then I think it will work.

```
$ echo hello > file.txt
$ rclone copy file.txt b2:test-isos/test/c:
$ rclone ls b2:test-isos/test/
        6 c:/file.txt
```

**Comment by jlahtela** [comment]
Thanks for suggesting solution.

However that “folder” is not empty. There is an another folder inside that.

These folders have been created by CloudBerry backup software what took backup from windows machine. After c: “folder” there is folders and eventually files.

Do not know why it behaves like this now. On Backblaze webui I can browse files and folders without any issues.

**Comment by jlahtela** [comment]
Oh fufufuuuu... I wrote command again and it worked.

This is embarrassing... it is not c it is C.
Well fixed... next time I check better! ;)
