### ISSUE TITLE
Dropbox Business Feature; --dropbox-impersonate 

### ISSUE THREAD

**Issue by jake-stripe** [ncw/rclone#2577]
Hello There,

One of my favorite things about rclone is it's ability to utilize a Gsuite service account with the `--drive-impersonate <gsuite-email>` flag. I would love to see this functionality brought to Dropbox in the form of `--dropbox-impersonate <dropbox-account-id>`

*Docs:* The feature is a a part of the [buisness api](https://www.dropbox.com/developers/documentation/http/teams#teams-member-file-access), 

*Creds:* A Dropbox admin needs to provision a key with the *Team member management* scope. 

*REST API Specifics:* The only real change to api calls is the addition of an extra header in the request; `Dropbox-API-Select-User: team_member_id`
Unfortunately you are required to provide the member-id, rather than a email address, but this is the only odd bit.

*[golang client](https://github.com/dropbox/dropbox-sdk-go-unofficial/blob/master/dropbox/files/client.go)*: You configure the client with `dbx.Config.AsMemberID`

Thanks very much for your time and happy rclone-ing :)

-Jake

**Comment by ncw** [comment]
That seems like a reasonable request :-)

Do you want to implement it?  It seems like you've done quite a lot of the work already!

Unfortunately I don't have access to a dropbox for business account at the moment.

**Comment by jake-stripe** [comment]
@ncw I am new to golang, so the results might be a bit interesting; but I am totally willing to give it a shot :)

**Comment by ncw** [comment]
If you want to give it a go, I'm willing to help guide you through it!  Let me know where you get stuck and I'll try to help :-)

**Comment by jake-stripe** [comment]
Ok I got item one working with a new `--dropbox-impersonate` flag. Next up is translating an `Email` to `TeamMemberId`. cc @adunham-stripe.

**Comment by ncw** [comment]
Great :-)  Translating the Email presumably only needs to be done once at the start?

**Comment by jake-stripe** [comment]
@ncw correct

**Comment by jake-stripe** [comment]
@ncw sorry for the delay. I should have some time to poke at this this weekend :)

**Comment by jake-stripe** [comment]
Hi @ncw i've been using the following branch off and on for the last few months without issue. Please let me know what you think of it. In my opinion the error handling I added is a bit blunt... I'd love any advice you could provide on how I might improve it.

https://github.com/ncw/rclone/pull/2719
