### ISSUE TITLE
Issue with special character

### ISSUE THREAD

**Issue by abraaocaldas** [ncw/rclone#258]
When the folder name have this character ->  ©
Rclone cannot copy to amazon cloud drive, no error message is show, but the upload is marked as completed.

**Comment by ncw** [comment]
I uploaded a file called  `©.txt` and viewed it in the web interface just fine.  I also downloaded it with rclone.

Can you send me a log of it going wrong? Of make me an example that I can reproduce?

Thanks

Nick

```
$ mkdir /tmp/z
$ echo "Hello" >/tmp/z/©.txt
$ cat /tmp/z/©.txt 
Hello

$ rclone -v copy /tmp/z acd:test-copyright-symbol
2015/12/23 11:03:13 acd: Saving new token in config file
2015/12/23 11:03:14 test-copyright-symbol: Failed to read info: Node not found
2015/12/23 11:03:14 Amazon cloud drive root 'test-copyright-symbol': Modify window not supported
2015/12/23 11:03:15 Amazon cloud drive root 'test-copyright-symbol': Building file list
2015/12/23 11:03:15 Amazon cloud drive root 'test-copyright-symbol': Finished reading 
2015/12/23 11:03:15 Amazon cloud drive root 'test-copyright-symbol': Waiting for checks to finish
2015/12/23 11:03:15 Amazon cloud drive root 'test-copyright-symbol': Waiting for transfers to finish
2015/12/23 11:03:16 ©.txt: Copied (new)

Transferred:            6 Bytes (   0.00 kByte/s)
Errors:                 0
Checks:                 0
Transferred:            1
Elapsed time:        3.2s

2015/12/23 11:03:16 Go routines at exit 16


$ rclone -v copy /tmp/z acd:test-copyright-symbol
2015/12/23 11:03:32 Amazon cloud drive root 'test-copyright-symbol': Modify window not supported
2015/12/23 11:03:32 Amazon cloud drive root 'test-copyright-symbol': Building file list
2015/12/23 11:03:32 Amazon cloud drive root 'test-copyright-symbol': Finished reading 
2015/12/23 11:03:32 Amazon cloud drive root 'test-copyright-symbol': Waiting for checks to finish
2015/12/23 11:03:32 ©.txt: Sizes identical
2015/12/23 11:03:32 ©.txt: Unchanged skipping
2015/12/23 11:03:32 Amazon cloud drive root 'test-copyright-symbol': Waiting for transfers to finish

Transferred:            0 Bytes (   0.00 kByte/s)
Errors:                 0
Checks:                 1
Transferred:            0
Elapsed time:       600ms

2015/12/23 11:03:32 Go routines at exit 13

$ rclone -v copy acd:test-copyright-symbol /tmp/zz
2015/12/23 11:05:11 Amazon cloud drive root 'test-copyright-symbol': Modify window not supported
2015/12/23 11:05:11 Local file system at /tmp/zz: Building file list
2015/12/23 11:05:11 Local file system at /tmp/zz: Waiting for checks to finish
2015/12/23 11:05:11 Amazon cloud drive root 'test-copyright-symbol': Finished reading 
2015/12/23 11:05:11 Local file system at /tmp/zz: Waiting for transfers to finish
2015/12/23 11:05:11 ©.txt: Copied (new)

Transferred:            6 Bytes (   0.01 kByte/s)
Errors:                 0
Checks:                 0
Transferred:            1
Elapsed time:          1s

2015/12/23 11:05:11 Go routines at exit 15


$ cat /tmp/zz/©.txt 
Hello
```

**Comment by abraaocaldas** [comment]
Hello, I don´t know why the issue happens, but I´m having trouble with characters like this:

é ó í á ã õ ç è à ì

2015/12/23 19:43:56 A Hist▒ria da Geologia /A Hist▒ria da Geologia - Epis▒dio 1.mkv: Failed to open: open /root/toupload/A Hist�ria da Geologia /A Hist�ria da Geologia - Epis�dio 1.mkv: no such file or directory

![acentuado](https://cloud.githubusercontent.com/assets/3661806/11983773/81ecf542-a98c-11e5-8072-224196a56d64.png)

My Locale:

LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=

Running rclone v1.25 for ARM on Ubuntu 14.04.2 LTS ->  GNU/Linux 3.2.34-30 armv7l - Marvell (Proprietary)

**Comment by ncw** [comment]
Ah, I suspect your file system is storing file names in latin1, not UTF-8.  rclone expects the local filing system to be in UTF-8 which all modern filing systems are.

You can see that because your terminal is set to UTF-8 but when you run `ls` you get `?` in your file names instead of the accented characters.

I did a bit of searching - you might find this helpful: http://serverfault.com/questions/54911/debian-how-to-convert-filesystem-from-iso-8859-1-into-utf-8

If you do convert your filing system to UTF-8 then rclone should work fine!

**Comment by ncw** [comment]
You should probably check out [the local file system docs](http://rclone.org/local/) too which has a section on encoding.

**Comment by abraaocaldas** [comment]
Thank you, I found a solution, just convert all files to utf-8 :)

convmv -f latin1 -t utf8 -r /pathto

**Comment by ncw** [comment]
Great - that is what I would have done :-)
