### ISSUE TITLE
Yandex.Disk: implement full support for Yandex REST API

### ISSUE THREAD

**Issue by Snousmoumryk** [ncw/rclone#2586]
Current **rclone 1.43** version doesn't [support ](https://rclone.org/overview/#optional-features) all available Yandex.Disk features.
Original code for rclone [Yandex disk backend](https://github.com/dibu28/yandex) was written by @dibu28 in late 2015 and is a bit outdated.
I'd suggest implementing support for at least moving/copying files and directories using [Yandex REST API](https://tech.yandex.com/disk/api/concepts/about-docpage/?ncrnd=4445) (link to rclone forum [thread](https://forum.rclone.org/t/unable-to-move-file-on-yandex-disk-falls-back-to-download-upload-delete/6801))

- [copy a file or folder](https://tech.yandex.com/disk/api/reference/copy-docpage/)
- [move a file or folder](https://tech.yandex.com/disk/api/reference/move-docpage/)

**Comment by ncw** [comment]
Thank you for making this issue :-)

@dibu28 wrote the original code - would you like to add these?

It should be reasonably straight forward to add `Move`, `MoveDir` and `Copy`...

Though looking at the Yandex code it is one of the early remotes so I think it would benefit from being re-written to use the rest library which would be a bit more work.

**Comment by ncw** [comment]
@buengese - fantastic :-)

**Comment by Snousmoumryk** [comment]
@buengese @ncw 
Breathless and ready to test
