### ISSUE TITLE
HowTo Update rclone?

### ISSUE THREAD

**Issue by klierik** [ncw/rclone#259]
Good day.

I have some problems with rclone and a lot of "Duplicate file detected".
```
$ rclone -V
clone v1.23
```

It seems i need update rclone to latest version to fix this, correct?

So, can you tell me please how update rclone via Go?

Thanks

**Comment by ncw** [comment]
Either download the binary at http://rclone.org/downloads/ or if you have a go install

    go get -u -v -f github.com/ncw/rclone

Will produce an updated binary in `$GOPATH/bin`

I hope that helps!

**Comment by klierik** [comment]
Thanks a lot! It is work for me.

**Comment by ncw** [comment]
Glad that helped
