### ISSUE TITLE
rclone config bug

### ISSUE THREAD

**Issue by ChrisSLT** [ncw/rclone#26]
With the latest version, there is a small bug when you make a new remote:

1.  Make a new remote of type "Drive"
2.  After you paste in the token, and click "y" that it's OK, it then asks you for the name again - it leads you back in a loop.  You have to type CTRL-C to escape it.

**Comment by ChrisSLT** [comment]
oops - see you already have this one..  i'll close it

**Comment by ncw** [comment]
I have fixed, this already but it hasn't made it to a release yet - watch out for 1.10!
