### ISSUE TITLE
Rclone , Not running by crontab

### ISSUE THREAD

**Issue by Sumanthsas3** [ncw/rclone#260]
When ever I am scheduling a rclone copy by crontab , I am getting  this error

Failed to create file system for "GDrive:/TestingMain": Couldn't read info about Drive: Get https://www.googleapis.com/drive/v2/about?alt=json: dial tcp: lookup www.googleapis.com on 10.245.65.10:53: no such host

Scenario: 
1. Crontask under root
2. Crontask to trigger rclone to copy a file to the following path in google drive "GDrive:/TestingMain"

**Comment by ncw** [comment]
Which OS are you using?

It looks like that DNS resolution isn't working under cron.

Does it happen every time, or does it work sometimes?

Do you have any name resolver environment variables set normally, eg `RES_OPTIONS` - these won't be set under cron.

**Comment by ncw** [comment]
Did you get anywhere looking at this?

**Comment by Sumanthsas3** [comment]
Hi Nick,

I am using Fedora.

May be DNS Resolution is not working under cron.

It is happening when I run through cron only.. Everytime not running
through cron.

I did not set any name resolver environment variables.

Any solution ??

On Sat, Jan 2, 2016 at 6:22 PM, Nick Craig-Wood <notifications@github.com>
wrote:

> Did you get anywhere looking at this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ncw/rclone/issues/260#issuecomment-168388712>.
>



-- 
Thanks and Regards,
Sumanth Nagendla,
Contact no: 07204344246.

**Comment by ncw** [comment]
Did you manage to make this work?

You might get more help posting to a fedora forum - I don't think it is an rclone problem specifically.

**Comment by ncw** [comment]
I think this isn't an rclone bug so I'm going to close this ticket.

I'm sorry I haven't been able to help you work out what is going on - you might get more help from a general Fedora / linux forum.

Please re-open if you do discover it is an rclone bug.

Thanks

Nick

**Comment by marco69v** [comment]
sorry, i have the same problem. I think that running inside cron, rclone is not able to read any (default) conf file, so it should be enough to use  --config /root/.rclone.conf ? can it be ?

**Comment by mejje** [comment]
Sumanthsas3: try with setting env var GODEBUG=netdns=go

**Comment by ncw** [comment]
@mejje good suggestion.  The next release of rclone v1.30 will be compiled like that by default, so it might be worth retrying with that.
