### ISSUE TITLE
Improve `rclone cleanup` to remove partially uploaded files on Backblaze B2

### ISSUE THREAD

**Issue by fuxoft** [ncw/rclone#2617]
There is currently no way to way to use `rclone` to remove partially uploaded large files on Backblaze B2. This would be an ideal addition to the existing `rclone cleanup`.

**Comment by GlitterCakes** [comment]
Yes please, this functionality would be very useful.

**Comment by ncw** [comment]
Anyone want to have a go at this?

**Comment by ncw** [comment]
> Is it worth differentiating between uploads that may still be in progress and old uploads that have failed? One option would be to check the upload timestamp and only delete if the upload was started some time ago (e.g. more than 12 hours / a day)?

I think that would probably be sensible - only to delete uploads which were started more than 24 hours ago.
