### ISSUE TITLE
The Union mount needs to implement the optional Methods Move, Copy, DirMove etc.

### ISSUE THREAD

**Issue by nimbuz** [ncw/rclone#2619]
Issue as references here:

https://forum.rclone.org/t/plex-gdrive-using-union-mount/7024/22?u=nimbuz

Example of error:
"2018/10/02 10:08:22 ERROR : Bull (2016)/Season 3/Bull.(2016).S03E02.Jury.Duty.HDTV-720p.KILLERS.mkv.partial~: Dir.Rename error: Fs “union root ‘’” can’t rename files (no server side Move or Copy)"

Tentative solution: "The Union mount needs to implement the optional Methods Move, Copy, DirMove etc. It might be better to embed the fs for this"

**Comment by ncw** [comment]
Here is an initial attempt at this

https://beta.rclone.org/branch/v1.43-130-gd90eccd6-fix-2619-union-beta/ (uploaded in 15-30 mins)

can you have a go and see if it fixes that problem?

**Comment by nimbuz** [comment]
This fix only has software for windows and osx. I'm running linux, so unfortunately I can't test it with those packages, sorry!

**Comment by ncw** [comment]
@nimbuz the build failed, I've kicked it and the linux binaries are there now - can you have a test please?

Thanks

**Comment by nimbuz** [comment]
The union remote type doesn't seem to be included in that beta branch. I will need one that includes the fix and the new union feature.

**Comment by nimbuz** [comment]
I tried to install your new branch, however I have to go through the hassle of making it a plugin to fit into unraid (https://github.com/nimbuz/rclone-unraid/blob/beta/plugin/rclone.plg).
I think it works, however I'm unable to create a union mount through the config. Are you seeing the same?

**Comment by nimbuz** [comment]
I tried my best at a plugin, and I think I made it work. However I'm unable to create a union remote through the config. You seeing the same?

**Comment by ncw** [comment]
@nimbuz - sorry I'm not an unraid user, so I'm not sure what is going on :-(  The beta shouldn't have changed the union backend config at all.

**Comment by nimbuz** [comment]
@ncw It seems wierd. Windows does the same thing. This is what I'm getting when trying to make a remote on windows. Are you able to create a union remote?
![image](https://user-images.githubusercontent.com/18343339/46570625-48809180-c967-11e8-9c36-a958ecb07989.png)

**Comment by nimbuz** [comment]
@ncw Unfortunately I won't be able to test it on my system, before the fix is pushed to the main beta branch. However the implementation of --move should fix the issue. I tried installing the fix on windows, and I'm seeing the union remote now, so it seems to be working.
I won't be able to test it though, sorry.

**Comment by ncw** [comment]
OK, I've merged that to master and it will be in [the latest beta](https://beta.rclone.org) in 15-30 mins.

**Comment by nimbuz** [comment]
I’ve been running the beta for a few days now, and it’s running wonderfully. Good job on it!
The way it copies to the union folder, and then afterwards moves it to the correct local folder seems a bit slow however (I assume that’s what it’s doing), but it’s obviously not too big of an issue with fast hard drives.
