### ISSUE TITLE
Console output does not properly get cleared before updating it

### ISSUE THREAD

**Issue by SL-Gundam** [ncw/rclone#2623]
#### What is the problem you are having with rclone?
Just wanted to let you know that with the Windows 10 1809 update the console does not clear old output properly. In Windows 10 1803 this was not an issue but with 1809 it is. See the effect below and compare it to other screenshots from #2501 

![image](https://user-images.githubusercontent.com/912973/46435761-6aa3c500-c757-11e8-871f-4db9d342935a.png)

When the issue from #2501 is not present and we have normal output the end of the transferring lines contains a countdown timer to completion for that file. As it counts down you get multiple "s" at the end because it starts as "1h5m10s" which becomes smaller and eventually showing "1ssssss"

#### What is your rclone version (output from `rclone version`)
1.43.1

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Windows 10 1809

####  Which cloud storage system are you using? (eg Google Drive)
Google Drive

**Comment by SL-Gundam** [comment]
Here is how it would look without the #2501 issue
![image](https://user-images.githubusercontent.com/912973/46491824-1c043280-c80c-11e8-911f-ad71baec88a2.png)

**Comment by SL-Gundam** [comment]
release build
same thing in powershell
rclone ncdu seems to work without issues

**Comment by SL-Gundam** [comment]
I found a workaround to fix this
I enabled "Use legacy console" and that resolved it for me

![image](https://user-images.githubusercontent.com/912973/46573277-4cc2a400-c993-11e8-9cc3-8e6e75d1ae8d.png)

**Comment by ncw** [comment]
The fix I made for #2501 may help here - I'm not sure.

https://beta.rclone.org/branch/v1.43-137-g60dac68f-fix-2501-progress-errors-beta/ (uploaded in 15-30 mins)

**Comment by SL-Gundam** [comment]
#2501 https://beta.rclone.org/branch/v1.43-138-gf6c174e9-fix-2501-progress-errors-beta/ makes no difference for the issue in this ticket.

**Comment by ncw** [comment]
@SL-Gundam are there any release notes from Microsoft which might pertain to this?

**Comment by SL-Gundam** [comment]
Not that i have found so far. If i do i will let you know

**Comment by SL-Gundam** [comment]
Reported this issue here: https://github.com/Microsoft/console/issues/289

**Comment by SL-Gundam** [comment]
Has been fixed by Microsoft in Windows 10 1903

**Comment by ncw** [comment]
> Has been fixed by Microsoft in Windows 10 1903

Hooray :-)  Well done for reporting it upstream and getting it fixed.
