### ISSUE TITLE
Documentation inaccuracy

### ISSUE THREAD

**Issue by Miladiir** [ncw/rclone#2625]
#### What is the problem you are having with rclone?

Documentation inaccuracy
#### Notes:

Case Insensitive

"If a cloud storage systems is case sensitive then it is possible to have two files which differ only in case, eg file.txt and FILE.txt. If a cloud storage system is case insensitive then that isn’t possible."

It's actually the other way round. Case sensitive filesystems don't allow two filenames that only differ in case. "FILE.txt" vs "file.txt" is not allowed. A case insensitive filesystem would in turn allow both files to coexist.
That mistake carries throughout the following sentences. The notes about OS and case sensitivity are correct.

**Comment by darthShadow** [comment]
The documentation is correct unless the definition of case-sensitivity is different for cloud storage systems.

Taken from [Wikipedia](https://en.wikipedia.org/wiki/Case_sensitivity):

> In computers, uppercase and lowercase text may be treated as **distinct** (case sensitivity) or **equivalent** (case insensitivity)

**Comment by Miladiir** [comment]
Yeah, im an idiot :)
