### ISSUE TITLE
High memory usage when performing sync to azure blob storage

### ISSUE THREAD

**Issue by Foritus** [ncw/rclone#2628]
#### Output of `rclone version`

$ ./rclone version
rclone v1.43-136-g87e1efa9-beta
- os/arch: linux/amd64
- go version: go1.11.1

#### Describe the issue
Based on this forum thread: https://forum.rclone.org/t/high-memory-usage-when-performing-sync/7085/2

I’m encountering some pretty high memory usage when performing a sync from the local filesystem to a remote encrypted fs (which itself wraps an azure blob storage account). I suspect this may be because I have quite a lot of smallish files to sync. Key info:

Command being run: rclone --config /path/to/my/version/controlled/rclone.conf --checksum --retries 20 --suffix 2018-10-04 --backup-dir azure-encrypted:/backups.history/ --quiet --bwlimit 384k sync /home/backup-user/backups/ azure-encrypted:/backups

Rclone Version: 1.42 (also repros on latest beta, v1.43-136-g87e1efa9-beta)
Total size of files being sync’ed: 855GB
Number of files being sync’ed: 1,098,342 (1098342 without locale-specific separators)

The backup is using 5.325GB of physical RAM (12.408GB virtual), which seems pretty extreme.

Profiling data:
![profile001](https://user-images.githubusercontent.com/601930/46576827-47358000-c9cc-11e8-9045-a100cd6a46fd.png)

```
(pprof) text
Showing nodes accounting for 2268.21MB, 84.14% of 2695.62MB total
Dropped 117 nodes (cum <= 13.48MB)
Showing top 10 nodes out of 104
flat flat% sum% cum cum%
960.02MB 35.61% 35.61% 960.02MB 35.61% encoding/xml.copyValue
608.13MB 22.56% 58.17% 611.13MB 22.67% github /ncw/rclone/vendor/github.com/Azure/azure-storage-blob-go/2018-03-28/azblob.(*Metadata).UnmarshalXML
168.52MB 6.25% 64.43% 224.02MB 8.31% github /ncw/rclone/backend/azureblob.(*Fs).newObjectWithInfo
117.02MB 4.34% 68.77% 117.02MB 4.34% strings.Join
81MB 3.00% 71.77% 81MB 3.00% github /ncw/rclone/vendor/github.com/rfjakob/eme.tabulateL
79.50MB 2.95% 74.72% 79.50MB 2.95% strings.ToUpper
74.02MB 2.75% 77.47% 74.02MB 2.75% github /ncw/rclone/fs/asyncreader.newBuffer
72MB 2.67% 80.14% 153MB 5.68% github /ncw/rclone/vendor/github.com/rfjakob/eme.Transform
55.50MB 2.06% 82.20% 55.50MB 2.06% encoding/base64.(*Encoding).EncodeToString
52.50MB 1.95% 84.14% 52.50MB 1.95% encoding/base32.(*Encoding).DecodeString
```

**Comment by ncw** [comment]
This might be a bug in Azure/azure-storage-blob-go

I made 1000 files on azure and used `rclone memtest` on them

```
2018/10/07 08:08:01 NOTICE: 1001 objects took 629688 bytes, 629.1 bytes/object
2018/10/07 08:08:01 NOTICE: System memory changed from 72284408 to 72284408 bytes a change of 0 bytes
```

So each object takes roughly 630 bytes

So if you had 1098342 objects all loaded into memory, we'd expect that to take about 630*1098342 = 649MB not 5-12GB of RAM!

Also you aren't using `--fast-list` so I would expect those objects to be in RAM anyway.

I'll run some tests to see if I can see what is going on.  @sandeepkru do you have any thoughts?

**Comment by ncw** [comment]
@Foritus can you post your config (`rclone config show`) with the sensitive bits XXX-ed out please?

Can you desribe the distribution of those 1M files?  How many files per directory on average/maximum

This should print the directories with the most files - I'm just interested in the numbers not the directory names:

    find /home/backup-user/backups/  -type d -exec sh -c 'echo {} `ls {} | wc -l`' \; | sort -n | head

**Comment by Foritus** [comment]
```
[azure]
type = azureblob
account = XXXXXXXXXXXXXXXXXXXXXXXXXXXX
key = XXXXXXXXXXXXXXXXXXXXXXXXXXXX
endpoint =

[azure-encrypted]
type = crypt
remote = azure:encrypted/
filename_encryption = standard
password = XXXXXXXXXXXXXXXXXXXXXXXXXXXX
password2 = XXXXXXXXXXXXXXXXXXXXXXXXXXXX
```

I had trouble getting that shell script to handle file paths with spaces in them (this folder also contains backups from a Windows machine), so I whipped up a quick python script instead and computed some simple stats.

Total directories: 257581
Total files: 1118387
Average directory size: 4.34
Median directory size: 1

Top 10 largest directories by file-count:
FIle count: 7780, Directory backups/var.backups/lib/dpkg/info
File count: 7404, Directory backups/var.backups/lib/smartmontools
File count: 6942, Directory backups/usr.backups/include/linux
File count: 4574, Directory backups/var.backups/log
File count: 4304, Directory backups/var/lib/dpkg/info
File count: 3051, Directory backups/usr.backups/share/man/man1
File count: 2841, Directory backups/var.backups/lib/apt/lists
File count: 2442, Directory backups/usr.backups/share/icons/ubuntu-mono-light/status/22
File count: 2061, Directory backups/usr.backups/share/icons/ubuntu-mono-dark/status/22
File count: 1793, Directory backups/usr/share/man/man3

**Comment by sandeepkru** [comment]
I'm also trying to run some tests to check on this, will update once I've more details.

**Comment by OliverEvans96** [comment]
I'm seeing a similar memory ballooning when syncinc to google drive - any updates?

**Comment by ncw** [comment]
@OliverEvans96 wrote:
> I'm seeing a similar memory ballooning when syncinc to google drive - any updates?

This issue is definitely a problem with Azure blob storage. 

If you think there is a new problem then can you try again with [the latest beta](https://beta.rclone.org) and if it shows the problem could you follow the instructions here: https://rclone.org/rc/#debugging-rclone-with-pprof - run the sync for a while with the `--rc` parameter then do a memory profile.

Post the text or graphical output of that in please a [new issue on github](https://github.com/ncw/rclone/issues/new) and I'll take a look  - thanks

**Comment by Foritus** [comment]
Had it running for a couple of hours and it's only using 1.2GB atm (and way less CPU too), so significantly less than before. I'll keep it running and let you know if it changes 😄

**Comment by Foritus** [comment]
Update: I checked back and it's ballooned up to 7.312GB of RAM now. A quick look at the profiler shows a lot of Azure SDK XML objects like before. Interestingly the profiler thinks the app's heap usage is "only" 3GB, but the OS shows its resident working set as 7.3GB. 

![heap](https://user-images.githubusercontent.com/601930/48278409-4d909f00-e445-11e8-8086-dacfaf61712c.png)

`Showing nodes accounting for 3122.94MB, 99.18% of 3148.62MB total
Dropped 59 nodes (cum <= 15.74MB)
      flat  flat%   sum%        cum   cum%
 1268.21MB 40.28% 40.28%  1268.21MB 40.28%  encoding/xml.copyValue
  757.67MB 24.06% 64.34%   757.67MB 24.06%  github.com/ncw/rclone/vendor/github.com/Azure/azure-storage-blob-go/azblob.(*Metadata).UnmarshalXML
  291.06MB  9.24% 73.59%   291.06MB  9.24%  strings.Join
  222.52MB  7.07% 80.65%   282.53MB  8.97%  github.com/ncw/rclone/backend/azureblob.(*Fs).newObjectWithInfo
   78.50MB  2.49% 83.15%    78.50MB  2.49%  github.com/ncw/rclone/vendor/github.com/rfjakob/eme.tabulateL
   76.50MB  2.43% 85.58%    76.50MB  2.43%  github.com/ncw/rclone/backend/crypt.(*Fs).newObject (inline)
   72.75MB  2.31% 87.89%   330.80MB 10.51%  github.com/ncw/rclone/fs/sync.(*syncCopyMove).DstOnly
      64MB  2.03% 89.92%       64MB  2.03%  strings.ToUpper
      60MB  1.91% 91.82%       60MB  1.91%  encoding/base64.(*Encoding).EncodeToString
      51MB  1.62% 93.44%   129.50MB  4.11%  github.com/ncw/rclone/vendor/github.com/rfjakob/eme.Transform
      44MB  1.40% 94.84%       44MB  1.40%  encoding/base32.(*Encoding).DecodeString
      33MB  1.05% 95.89%  2090.37MB 66.39%  encoding/xml.(*Decoder).unmarshal
   31.50MB  1.00% 96.89%    31.50MB  1.00%  encoding/xml.(*Decoder).name
   20.01MB  0.64% 97.53%    20.01MB  0.64%  github.com/ncw/rclone/vendor/github.com/Azure/azure-storage-blob-go/azblob.uploadStream.func1`

**Comment by Foritus** [comment]
Aha, I didn't realise that Go doesn't do heap compaction. Learn something every day. ⭐️ 

The --retries was a holdover from a year or two ago when the Azure SDK would occasionally not refresh the access token in time and I'd get http 400 access denied for some uploads. As far as I can tell, rclone is not retrying uploads at the moment, and running without the --retries flag does not seem to reduce memory usage.

I've attached the the list of running goroutines, it looks dominated by fs/march as you suspected.

[goroutines.txt](https://github.com/ncw/rclone/files/2568458/goroutines.txt)

Transfer stats:
```
Transferred:             0 / 0 Bytes, -, 0 Bytes/s, ETA -
Errors:                 0
Checks:            574753 / 574753, 100%
Transferred:            0 / 0, -
Elapsed time:     22m0.6s
```

and rclone rc core/memstats:

```
$ ./rclone rc core/memstats
{
        "Alloc": 4058290560,
        "BuckHashSys": 14338808,
        "Frees": 4821464966,
        "GCSys": 258273280,
        "HeapAlloc": 4058290560,
        "HeapIdle": 887554048,
        "HeapInuse": 4206526464,
        "HeapObjects": 90405131,
        "HeapReleased": 0,
        "HeapSys": 5094080512,
        "MCacheInuse": 6912,
        "MCacheSys": 16384,
        "MSpanInuse": 77613784,
        "MSpanSys": 91963392,
        "Mallocs": 4911870097,
        "OtherSys": 9387360,
        "StackInuse": 6193152,
        "StackSys": 6193152,
        "Sys": 5474252888,
        "TotalAlloc": 155852088112
}
```

I can try and replicate it with a bunch of randomly generated files and give you a heap dump if that would help? :)

**Comment by ncw** [comment]
Thank you for that.

I've investigated the goroutine buildup in `fs/march`.  That shouldn't be pinning any objects in memory so I don't think it can be the cause of the leak.

I'm going to try to reproduce the problem by uploading 100,000 files to azure...  I'm going to try with crypt and if that failes with --backup-dir too!

I'll report back shortly...

```
goroutine profile: total 1890
1841 @ 0x42ddcb 0x43dd7d 0x8f22f2 0x45bd91
#	0x8f22f1	github.com/ncw/rclone/fs/march.(*March).Run.func1.1+0x1a1	/home/travis/gopath/src/github.com/ncw/rclone/fs/march/march.go:149

8 @ 0x42ddcb 0x42de73 0x43e92c 0x43e569 0x466674 0x8f0fbe 0x8f253a 0x45bd91
#	0x43e568	sync.runtime_Semacquire+0x38				/home/travis/.gimme/versions/go1.11.2.linux.amd64/src/runtime/sema.go:56
#	0x466673	sync.(*WaitGroup).Wait+0x63				/home/travis/.gimme/versions/go1.11.2.linux.amd64/src/sync/waitgroup.go:130
#	0x8f0fbd	github.com/ncw/rclone/fs/march.(*March).processJob+0xed	/home/travis/gopath/src/github.com/ncw/rclone/fs/march/march.go:360
#	0x8f2539	github.com/ncw/rclone/fs/march.(*March).Run.func1+0x1e9	/home/travis/gopath/src/github.com/ncw/rclone/fs/march/march.go:142
```

**Comment by ncw** [comment]
I'm having trouble replicating this :-(

My experiments with 100,000 crypted files didn't show the problem.

Can you reproduce the problem in a smaller problem set?

**Comment by ncw** [comment]
I've tried everything I can think of to replicate the problem.  I haven't been able to get the RSS above 80MB though.

Could you attach the result of listing the encrypted bucket?

    rclone ls azure:underlying_bucket > listing
    gzip -9 listing

So I can have a listing of your bucket with encrypted file names and sizes?

If you are unhappy with posting that publicly then you could email it to me at nick@craig-wood.com.

Thanks :-)

**Comment by Foritus** [comment]
It's running at the moment. It's taken about an hour so far :D Interestingly it seems to be using about 2GB of RAM so far just doing "rclone ls azure:encrypted". I'll report back with the details once it's done (and might have to email you the file as it might end up too big to post here)

**Comment by ncw** [comment]
> Interestingly it seems to be using about 2GB of RAM so far just doing "rclone ls azure:encrypted".

That is an extraordinary amount of RAM for a listing!  Which must surely be another clue that the problem is below the sync layer.

When it has finished, would you mind adding the `--rc` parameter, letting it balloon up a bit (to 1GB say) and doing a memory profile?  That would be a useful thing to do - thanks.

**Comment by ncw** [comment]
Just checking - you are doing this with a recent beta?

**Comment by Foritus** [comment]
This is with rclone-v1.44-071-g9322f4ba-beta-linux-amd64

**Comment by Foritus** [comment]
Emailed you a copy of the ls output (it was way too big to post here :D)

**Comment by ncw** [comment]
Thanks for your memory dump and listing (I'm downloading it now!).  Will peruse some more in the morning it is late here now :-)

**Comment by Foritus** [comment]
I think you may have cracked it. Running with --delete-during has kept the working set steady at 200MB for the past couple of hours :) I'll leave it running overnight and report back.

**Comment by Foritus** [comment]
Perhaps I spoke too soon. Half an hour later it's ballooned up to 3.2GB working set. 

![lsheap](https://user-images.githubusercontent.com/601930/48379218-4bd80d00-e6cb-11e8-8a85-15ee76feb211.png)
[lsheap.txt](https://github.com/ncw/rclone/files/2573899/lsheap.txt)
[goroutines.txt](https://github.com/ncw/rclone/files/2573900/goroutines.txt)

**Comment by ncw** [comment]
> I think you may have cracked it. Running with --delete-during has kept the working set steady at 200MB for the past couple of hours :) I'll leave it running overnight and report back.

Maybe I should make this the default when using `--backup-dir` - the files are safe, just in the backup dir.


> Perhaps I spoke too soon. Half an hour later it's ballooned up to 3.2GB working set.

According to the memory dump, rclone is using 1386MB of RAM.

There are about 880,000 azureblob objects in memory and about 845,000 crypt objects in memory.

In the file listing you sent me there are 4 really big directories

```
443656 /tmp/issue-2628/l296lk0s2v5h6b5qhmghpb1g68/rpcqfvvbv6ahjn5ospvohuh7a4/rq42e46ags0fqeqf926d4lmf9s/jlvjj9fppo10ka0732abh4ef44/n7qt10iesd61i2mred8hlelir8/god0v3qql6lib1bjquea4jhrts/tu1e2fjrprq5cuqle7ubrpq7hg/ic3r6td5p77l2jptcv89647524/3t8t4sd13vb28vrm92tm85uhuo/n7qt10iesd61i2mred8hlelir8/pg9b84i9jspbiobc3pfct0gfl0/l8q10092mj32f7tm8id5qdij90/vuhlslpb6ov2oa9jkh1alugm60/93g5ov2e86s1kk9vvc5je4dit0/uuk3ltcjb4i03ju4j814a5fqmk/81uluk7i3o3lhs2vpm6igv19dvq6us6j7bahcm22toi85oc5ll7g/pnu0pok2o6c24u3g29rmibecog/iaps2tkab6jj7bkuro29c8rb50
443540 /tmp/issue-2628/l296lk0s2v5h6b5qhmghpb1g68/j2v8rs16di9513nf7dqvrdclio/rq42e46ags0fqeqf926d4lmf9s/jlvjj9fppo10ka0732abh4ef44/n7qt10iesd61i2mred8hlelir8/god0v3qql6lib1bjquea4jhrts/tu1e2fjrprq5cuqle7ubrpq7hg/ic3r6td5p77l2jptcv89647524/3t8t4sd13vb28vrm92tm85uhuo/n7qt10iesd61i2mred8hlelir8/pg9b84i9jspbiobc3pfct0gfl0/l8q10092mj32f7tm8id5qdij90/vuhlslpb6ov2oa9jkh1alugm60/93g5ov2e86s1kk9vvc5je4dit0/uuk3ltcjb4i03ju4j814a5fqmk/81uluk7i3o3lhs2vpm6igv19dvq6us6j7bahcm22toi85oc5ll7g/pnu0pok2o6c24u3g29rmibecog/iaps2tkab6jj7bkuro29c8rb50
375441 /tmp/issue-2628/92fpgng40hgb707hu5uuef0puk/j2v8rs16di9513nf7dqvrdclio/rq42e46ags0fqeqf926d4lmf9s/jlvjj9fppo10ka0732abh4ef44/n7qt10iesd61i2mred8hlelir8/god0v3qql6lib1bjquea4jhrts/tu1e2fjrprq5cuqle7ubrpq7hg/ic3r6td5p77l2jptcv89647524/3t8t4sd13vb28vrm92tm85uhuo/n7qt10iesd61i2mred8hlelir8/pg9b84i9jspbiobc3pfct0gfl0/l8q10092mj32f7tm8id5qdij90/vuhlslpb6ov2oa9jkh1alugm60/93g5ov2e86s1kk9vvc5je4dit0/uuk3ltcjb4i03ju4j814a5fqmk/81uluk7i3o3lhs2vpm6igv19dvq6us6j7bahcm22toi85oc5ll7g/pnu0pok2o6c24u3g29rmibecog/iaps2tkab6jj7bkuro29c8rb50
375324 /tmp/issue-2628/92fpgng40hgb707hu5uuef0puk/rpcqfvvbv6ahjn5ospvohuh7a4/rq42e46ags0fqeqf926d4lmf9s/jlvjj9fppo10ka0732abh4ef44/n7qt10iesd61i2mred8hlelir8/god0v3qql6lib1bjquea4jhrts/tu1e2fjrprq5cuqle7ubrpq7hg/ic3r6td5p77l2jptcv89647524/3t8t4sd13vb28vrm92tm85uhuo/n7qt10iesd61i2mred8hlelir8/pg9b84i9jspbiobc3pfct0gfl0/l8q10092mj32f7tm8id5qdij90/vuhlslpb6ov2oa9jkh1alugm60/93g5ov2e86s1kk9vvc5je4dit0/uuk3ltcjb4i03ju4j814a5fqmk/81uluk7i3o3lhs2vpm6igv19dvq6us6j7bahcm22toi85oc5ll7g/pnu0pok2o6c24u3g29rmibecog/iaps2tkab6jj7bkuro29c8rb50
```

So a couple of those directories could easily explain the 800k objects in memory

rclone max memory use should be proportional to (--checkers) * (max items in a directory)

**Comment by Foritus** [comment]
Confirmed, mystery solved :) I've been running a backup job for the last 24 hours to a fresh azure container and it's stayed at a comfortable 200MB. 

Turns out those folders containing hundreds of thousands of files are from a desktop PC backing backing up copies of the Firefox "safe browsing" known-bad-website data. Which changes every day and is of course pointless to back up anyway :D 

Sorry for the wild goose chase!

**Comment by ncw** [comment]
> Confirmed, mystery solved :) I've been running a backup job for the last 24 hours to a fresh azure container and it's stayed at a comfortable 200MB.
> 
> Turns out those folders containing hundreds of thousands of files are from a desktop PC backing backing up copies of the Firefox "safe browsing" known-bad-website data. Which changes every day and is of course pointless to back up anyway :D
> 
> Sorry for the wild goose chase!

I'm glad we got to the bottom of it :-)

rclone has a problem with lots of files in a single directory and I haven't figured out the best way of fixing that yet.

Time looking at the code to try to improve it is never wasted :-)
