### ISSUE TITLE
on ACD directories with many files cannot properly by sync'd.

### ISSUE THREAD

**Issue by left1000** [ncw/rclone#263]
When uploading 100,000 or more files rclone will often get stuck trying to read the ls list of files from ACD.
This will result in a large number of errors that say "file with this name already exists" because it will not find the file then it will add it to the list of files to upload then when it's time to upload it'll find it already existed.

Even worse this will often result in the checks portion of rclone getting stuck, literally forever, for some files. This means that when I want to sync 100,000-1,000,000 files or so to ACD I simply can't.

I don't blame rclone, it's probably all ACD's fault, but I am wondering if anything could be done to help this out? perhaps rclone could save a ls from acd? allowing rclone some command to generate a full ls? allowing the user to run it a few times? to make sure they have a good ls? then start the sync using that locally stored ls? I don't know...

I started just uploading large 7z files of my largest folders instead.

another sub issue here is thusly, if remote:E:\ contains let's say 10subfolders and those 10subfolders contain 1,000,000 files... and I want to upload a single file directly to "remote:E" instead of just confirming that file isn't one of the ten things in the root directory it will demand to check all 1,000,000 files (or well maybe not "check" but the ls command will be for all subdirectories)... this has resulted in me wanting to upload to "remote:incoming" then use ACD's shitty website to move the file back to "remote:E"...

ideally the ls rclone runs from ACD would only check subdirectories it needs to? this would speed things up a lot especially because ACD's response to ls is very buggy.

**Comment by Wowfunhappy** [comment]
I have begun noticing this lately as well. Something must have changed on ACD's backend because this did not used to happen.

**Comment by left1000** [comment]
had no trouble at all with a folder with 30,000 files in it this week, so it might only come up when a folder on acd has 100,000-300,000 or more files (roughly) like the folders I had been testing out the week before that.

**Comment by zeshanb** [comment]
No sure. Looking at line 244 on swift.go there is a default 256 object list
limit for some reason. One would need to know the requirements of Auth API
being used and configs made by data host Admin.

@ncw Is rClone trying to host objects(Fs) in a object(fs) before
transporting? Is there a way to find out the data throttle requirements
while listing and transferring?

**Comment by ncw** [comment]
Can you post a log with `-v` of this happening please? If it is too long for here then stick it on pastebin, or email it to me directly if it has sensitive stuff you don't want to share with the world.

Thanks

Nick

**Comment by left1000** [comment]
now that I think of it... I have both used --bwlimit AND not used --bwlimit.... when NOT using --bwlimit I got all the same 504 errors BUT each file only uploaded once... I do believe some of the files which were uploaded 2or3 times in a row (with each copy being presumably perfect) were with --bwlimit.

I'll generate a -v of one of these situations later, these huge files take me a long time to upload so I guess getting to the -v of the situation will take quite a while.

**Comment by left1000** [comment]
I will attempt to generate the same situation again, I only had 10-20 such errors total when uploading a million files over a two week span... so I may not be able to trigger the problem again.

**Comment by ncw** [comment]
Thanks for posting the errors.  Those look like winsock errors, ie your machine's TCP stack complaining that it couldn't connect.

https://www.nsoftware.com/kb/xml/07240801.rst

As for what causes it - it might be Amazon, your ISP, your router/firewall it is difficult to know.

rclone shouldn't go mad at this point, it should just carry on so there may be something which needs tweaking.  If you can get me a log of it going wrong that would be super helpful.

....

I realise I didn't do a good job of answering your original question, so I shall now!

> When uploading 100,000 or more files rclone will often get stuck trying to read the ls list of files from ACD.
This will result in a large number of errors that say "file with this name already exists" because it will not find the file then it will add it to the list of files to upload then when it's time to upload it'll find it already existed.

Is that 100,000 files in one directory? Or 100,000 files spread out over many directories?

> Even worse this will often result in the checks portion of rclone getting stuck, literally forever, for some files. This means that when I want to sync 100,000-1,000,000 files or so to ACD I simply can't

I'm not sure why it gets stuck - is there anything in the log?

> I don't blame rclone, it's probably all ACD's fault, but I am wondering if anything could be done to help this out? perhaps rclone could save a ls from acd? allowing rclone some command to generate a full ls? allowing the user to run it a few times? to make sure they have a good ls? then start the sync using that locally stored ls? I don't know...

I've certainly considered this - see #180 

> I started just uploading large 7z files of my largest folders instead.

> another sub issue here is thusly, if remote:E:\ contains let's say 10subfolders and those 10subfolders contain 1,000,000 files... and I want to upload a single file directly to "remote:E" instead of just confirming that file isn't one of the ten things in the root directory it will demand to check all 1,000,000 files (or well maybe not "check" but the ls command will be for all subdirectories)... this has resulted in me wanting to upload to "remote:incoming" then use ACD's shitty website to move the file back to "remote:E"...

That is a problem I've known about for a while #8.  I haven't thought of a satisfactory solution though - for syncing lots of files it is much faster to list the remote, but for syncing just a few it is faster not to - how can we tell which to use?  Maybe I could add in a command line flag `--no-traverse` or something like that.?

Note that sync always has to traverse the remote file system.

> ideally the ls rclone runs from ACD would only check subdirectories it needs to? this would speed things up a lot especially because ACD's response to ls is very buggy.

**Comment by left1000** [comment]
the error I posted above appears unrelated to the error I described in this thread. I've gotten the rclone operation stuck again though. Made 30,000checks, then spent 2hours stuck on the same four small image files making no progress, the verbose log file is 80megabytes do you want to take a look at it?

what seems to be happening is it gives me the same file with that name already exists error endlessly for all time.... My guess is that somehow ACD's list is faulty and leaves a file out, so rclone tries to upload a new copy...then it finds the copy already exists... it retries the upload ten times listing 1/10 2/10 3/10...etc then it tries the 10th time retry 10/10 then... it tries again endlessly for all time :-/


80megabytes is too big for an email but if I edit out 29,000 perfectly fine checks I should be able to get the filesize down and email you the log.  The edited portion I guess has the error that matters is only 27kilobytes

**Comment by ncw** [comment]
I have seen the 409 issue in the integration tests too.  The integration tests used to pass perfectly every time with ACD, and now they are more like 50/50, with 409 error and complete stall, which sounds very much like the same symptoms.

I'm not 100% convinced this is an rclone issue rather than just ACD being overloaded, but we'll try to get to the bottom of the problem and fix it or work around.

**Comment by left1000** [comment]
Oh I agree it's a problem on ACD's end but rclone could hopefully be rewritten to get around this issue. If I ctrl-c rclone and start a new similar command rclone and ACD will instantly keep working on at it.  It seems like maybe ACD is overloaded for a minute or two and then rclone gets stuck in an infinite loop so that even if ACD gets unclogged rclone stays in it's infinite loop forever until I force close it.

If there was an easy way to create some sort of rclone copy progress list of files to transfers that could be worked on and resumed then maybe a user could ctrl-c forceclose rclone and restart it halfway through the transfer list?  or maybe after 10 409's in a row rclone could just skip those files entirely and at the end count them as errors?

If I ask rclone to sync 100,000 files I'd rather have 10errors than 0errors and 33,000sync'd files and 67,000files rclone froze before getting to look at.

Right now my best solution is to just keep uploading my local harddrive contents to new remote folders endlessly because as long as the target folder on the cloud is empty there can be no 409 errors and so there can be no 409 infinite loop.

**Comment by ncw** [comment]
I agree 100% with you.  rclone isn't supposed to hang indefinitely - at most it is supposed to hack for `--timeout` so something is up there.

Hopefully we'll work something out for this soon!

**Comment by Wowfunhappy** [comment]
Sorry for the noobish question, but what is the easiest way to have bash (in OS X) write rclone's verbose log to a text file so I can share it?

**Comment by isaiah36** [comment]
All important data is backing up, so I'm reporting this in case it is helpful to the developers, not for support particularly.  This is the log output from the ACD transfers

2016/01/04 04:57:58 CLASSICAL/The Sound of Everest/Front.jpg: Failed to copy: HTTP code 409: "409 Conflict", reponse body: {"logref":"a2727a0f-b2c9-11e5-8d39-fd0c5bf37a35","message":"Node with the name front.jpg already exists under parentId F27gnDnvTS6p19bp6hu8Tw conflicting NodeId: TZ2Z86TpQq6RUEG0KOCZ8A","code":"NAME_ALREADY_EXISTS","info":{"nodeId":"TZ2Z86TpQq6RUEG0KOCZ8A"}}
2016/01/04 04:57:58 Amazon cloud drive root 'Music': Not deleting files as there were IO errors
2016/01/04 04:57:58 Attempt 3/3 failed with 1 errors

There can be dozens of these sometimes, all caused usually by a small handful of files.

**Comment by Wowfunhappy** [comment]
This issue has completely fixed itself for me as of Monday. There was about a week and a half where I couldn't back up my hard drive to ACD, at all—now it's working again perfectly. I guess Amazon reverted/fixed whatever had changed on their backend.

**Comment by left1000** [comment]
yes! me too! ACD is sync'ing flawlessly and checking quickly without errors!

it'd still be nice for rclone to handle BAD cloud service performance more robustly though by fixing this issue even if it not currently effecting me anymore.

**Comment by ncw** [comment]
I'd like to fix the getting stuck issue.  Interestingly I still see it with the integration tests so I've got something to work on!

eg

    cd fs
    go test -v -remote TestAmazonCloudDrive:

shows the problem quite regularly.

**Comment by isaiah36** [comment]
Amazon and Google are competitors in the space, so I figure Amazon may not be excessively keen to support the Go language.  Pretty sure NCW will figure it out, whatever it is.  :)

**Comment by isaiah36** [comment]
My problem may have been something to do with case sensitivity.  The remote had a file called 'Front.JPG' and the local a file called 'Front.jpg' and the sync would fail.  I manually deleted the remote file, and now ACD sync completes with no errors.

**Comment by ncw** [comment]
@isaiah36 that will certainly stop the sync completing - sounds like ACD is having a good day if that was the only problem!

**Comment by ncw** [comment]
I've made a beta for you to try: http://pub.rclone.org/v1.26-34-gde3cf5e%CE%B2/ which should hopefully help.

Any feedback much appreciated.

**Comment by isaiah36** [comment]
Thank you!  Everything has been working smoothly by crontab, but I'll be happy to try out the beta.

**Comment by isaiah36** [comment]
The beta did not work.  It worked for checking files and not doing any transfers, but in the case that required transfers to be made I did not receive a log by email, and ACD does not show the new files.  I am switching back to the older version.

**Comment by left1000** [comment]
where can I download 1.27 for windows? I didn't find it here: 
http://rclone.org/downloads/

**Comment by ncw** [comment]
@left1000 it isn't quite released yet! Should be in a day or two.

**Comment by ncw** [comment]
I made another beta here: http://pub.rclone.org/v1.26-38-g6cb0de4%CE%B2/

**Comment by isaiah36** [comment]
You may want to consider making the last log entry be "Deletions finished" after the "Waiting for deletions to finish" entry that is currently the last entry before the final summary.  This way there will be a way to know if there has been a failure of deletions.

**Comment by left1000** [comment]
oh hey, just want to mention, usings rclonev1.29 I am still getting thousands of 409 error for name already exists.

I think rclone is resolving them better than it did in the past by far, however the original remote ls to compare to local ls is probably still working poorly? (what other cause is there for thousands of 409's?)

**Comment by Wowfunhappy** [comment]
Sigh. After working perfectly since this past winter, I'm suddenly running into this error again as of yesterday. I've been running rclone for the past 24 errors and have been unable to sync _anything_. I'm running the latest version.

I've put a verbose log [here](http://pastebin.com) in case you need it. It's VERY long though. Let me know if you need a non-verbose version (or something else).

Of note: I'm aware that there are a lot of errors early on that read "Warning: File found with same name but different case on amazon drive root 'Archive'". These messages were appearing even when rclone was still syncing fine, and I don't really understand where they're coming from. My local system is OS X, which doesn't allow you to have two files with the same name but different cases.

With any luck, this issue will mysteriously disappear after a week like it did last time...
