### ISSUE TITLE
restic serve with jottacloud: Leaking TCP Connections

### ISSUE THREAD

**Issue by buengese** [ncw/rclone#2637]
#### What is the problem you are having with rclone?
Rclone is leaking TCP connections. (More than 1000 open connections so it's running into the file descriptor limit)

#### What is your rclone version (output from `rclone version`)
rclone v1.43.1
- os/arch: freebsd/amd64
- go version: go1.11

####  Which cloud storage system are you using? (eg Google Drive)
Jottacloud

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone serve restic

I haven't managed to reproduce this intentionally and it has only happened on 2 occasions so far but I'm still trying to do so. I already rechecked the Jottacloud backend but all connections opened there should get closed so I doubt it's related to this backend. Will update this if I manage to reproduce it.

**Comment by ncw** [comment]
If you can get it to do it again `kill -QUIT` the rclone process - that will generate a backtrace of all goroutines which is usually enough to work out what is happening.

**Comment by jkaberg** [comment]
Just wanted to pitch in and say I've seen this as well. I backup 878648 files which is 253.7 GiB using restic->rclone (rclone is the one giving the errors). The backup runs fine (restic backup ...), however the prune job will kick out file descriptor limit errors and eventually hang the entire job. 

For now I just set the ulimit to something high, however not very ideal.

**Comment by ncw** [comment]
@jkaberg if you can get it to do it reliably, can you try the `kill -QUIT` thing please and post the backtrace?

**Comment by buengese** [comment]
I finally managed to reproduce it created a backtrace. However the information in the backtrace doensn't look particularly useful to me.

I've attached it here as it is obviously very long.

[screenlog.txt](https://github.com/ncw/rclone/files/2472950/screenlog.txt)

**Comment by jkaberg** [comment]
@ncw, forgot to enable redirect output so I didn't get all of it. Let me know if you need the complete trace


[output.log](https://github.com/ncw/rclone/files/2473329/output.log)

**Comment by ncw** [comment]
> I finally managed to reproduce it and created a backtrace. However the information in the backtrace doesn't look particularly useful to me.

Yes you are right.  I was hoping to see the goroutine creator be somewhere useful but it is in the http persistent connection handler.

```
goroutine 636846 [select, 933 minutes]:
net/http.(*persistConn).writeLoop(0xc000794240)
	/home/travis/.gimme/versions/go1.11.linux.amd64/src/net/http/transport.go:1885 +0x113
created by net/http.(*Transport).dialConn
	/home/travis/.gimme/versions/go1.11.linux.amd64/src/net/http/transport.go:1339 +0x966
```

I think I see the problem though...

https://github.com/ncw/rclone/blob/249a523dd3646d6933bcff19bdd633b3d0ba693f/backend/jottacloud/jottacloud.go#L1096-L1100

This needs to close the body of the response as the `CallXML(&opts, nil, nil)`  won't close the resp.Body.

I'm not sure the rest library code is correct though, I think this bit of code should be closing the Body.

https://github.com/ncw/rclone/blob/249a523dd3646d6933bcff19bdd633b3d0ba693f/lib/rest/rest.go#L388-L397

(Normally tt is the `decode` which closes the body)

@buengese can you try  this patch and see if that fixes the problem?

```patch
diff --git a/lib/rest/rest.go b/lib/rest/rest.go
index 2f473026a..9acbac79a 100644
--- a/lib/rest/rest.go
+++ b/lib/rest/rest.go
@@ -390,7 +390,7 @@ func (api *Client) callCodec(opts *Opts, request interface{}, response interface
 		return resp, err
 	}
 	if response == nil || opts.NoResponse {
-		return resp, nil
+		return resp, resp.Body.Close()
 	}
 	err = decode(resp, response)
 	return resp, err
```

**Comment by buengese** [comment]
Ah yeah I see. I'll let it run for a while but I'm already pretty sure that this will fix it because the number of open connections did correlate perfectly with the number of deletes in my log.

I agree it would be reasonable for `CallXML()` to close Body if you give nil as the response even though there's really no reason to use `CallXML()` over `Call()` in the case of `Remove()` because there's really no XML involved.

**Comment by ncw** [comment]
> Ah yeah I see. I'll let it run for a while but I'm already pretty sure that this will fix it because the number of open connections did correlate perfectly with the number of deletes in my log.

Great!

> 
> I agree it would be reasonable for `CallXML()` to close Body if you give nil as the response even though there's really no reason to use `CallXML()` over `Call()` in the case of `Remove()` because there's really no XML involved.

I'm going to have to do a code review to see exactly how CallXML and CallJSON have been used, then update the docs for them to say exactly what should happen!

I'll post a potential fix in a bit.

**Comment by ncw** [comment]
Here is a quick review of where CallXML/CallJSON are used with a `nil` response

    $ git grep -l 'Call\(XML\|JSON\)(.*, nil)'

- backend/box/upload.go - Body is read and closed
- backend/jottacloud/jottacloud.go - Remove: Body ignored - **Need to set opt.NoResponse**
- backend/onedrive/onedrive.go - Copy: Body ignored - opt.NoResponse is already set
- backend/opendrive/opendrive.go - deleteObject: Body ignored - opt.NoResponse is already set 
- backend/opendrive/opendrive.go - SetModTime: Body ignored - opt.NoResponse is already set
- backend/webdav/webdav.go - purgeCheck: Body ignored - opt.NoResponse is already set 

So I think the bug is that the jottacloud backend needed to set `NoResponse` in the Delete call options.

However none of that is clear from reading the rest module docs, so I've updated those and put more comments in to help future readers.

These fixes are in the `fix-2637-leak-beta` branch and a release is below

https://beta.rclone.org/branch/v1.43-152-g1ac6761f-fix-2637-leak-beta/ (uploaded in 15-30 mins)

I'd appreciate it if you could give that a test - thanks

**Comment by jkaberg** [comment]
@ncw no linux build? :cry:

**Comment by ncw** [comment]
The build had a hiccough...  I've merged this to master now - find it in

https://beta.rclone.org/v1.43-155-gade252f1-beta/ (uploaded in 15-30 mins)

and in [the latest beta](https://beta.rclone.org) at that point too.
