### ISSUE TITLE
[SOLVED] After config with Google drive rclone copying to local dir

### ISSUE THREAD

**Issue by isaiah36** [ncw/rclone#264]
Hello,

I ran rclone config to setup my Google drive as remote destination. It appeared to go ok. But running copy or sync commands only creates a directory called Gdrive (given name) in my home directory, and copies all data into it. Nothing is being sent to Google drive.

Isaiah

**Comment by garypaduana** [comment]
What is the exact rclone command you are executing?  Replace any personal info in the paths with generic info if desired.

**Comment by ncw** [comment]
My guess I'd that you forgot the colon after the Gdrive,  eg

  rclone copy stuff Gdrive:directory

**Comment by isaiah36** [comment]
Thanks, Gary and Nick!  It looks like the missing : was the problem.  I had manually uploaded my Documents folder to Google drive via web browser in the meanwhile.  So now I am running a sync with Gdrive:Documents as the target, and it seems to be going fine.

Gary, the exact command is - /usr/sbin/rclone sync /home/isaiah/Documents Gdrive:Documents
I was trying this before - /usr/sbin/rclone copy /home/isaiah/Documents Gdrive

Presumably I can setup a daily cron job now and automate this.  I'll be back if I screw it up, I'm a technical noob. 

Thanks again!

**Comment by isaiah36** [comment]
Just to be sure, do I designate sub directories on Gdrive with a : or a /?  Should it be 'Gdrive:Pictures/Senayit-Adanech' or 'Gdrive:Pictures:Senayit-Adanech'?

TIA

**Comment by garypaduana** [comment]
Isaiah, you will want to use `/` to designate subdirectories on a remote drive.

    $ rclone ls ACD:TEST/123
        10 test.groovy

    Transferred:            0 Bytes (   0.00 kByte/s)
    Errors:                 0
    Checks:                 0
    Transferred:            0
    Elapsed time:        2.3s

**Comment by isaiah36** [comment]
Thanks, Gary! and a very merry X'mas to both of you!

**Comment by ncw** [comment]
Glad it is solved now!
