### ISSUE TITLE
OneDrive file size limits

### ISSUE THREAD

**Issue by kristianrl** [ncw/rclone#2641]
#### What is the problem you are having with rclone?

OneDrive only supports files up to 15 GB, however, rclone attempts uploading files that are larger.
See
https://support.office.com/en-us/article/sharepoint-online-limits-8f34ff47-b749-408b-abc0-b605e1f6d498?ui=en-US&rs=en-US&ad=US

Could you fix this by checking file size prior to upload and returning an error message if the file size is too large.

#### What is your rclone version (output from `rclone version`)

# rclone version
rclone v1.42
- os/arch: linux/arm
- go version: go1.10.1

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

Linux

####  Which cloud storage system are you using? (eg Google Drive)

OneDrive

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

N/A

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

N/A

**Comment by ncw** [comment]
I'm reluctant to put arbitrary numbers like that in rclone which Microsoft can change at any time...

I'm not sure that limit is correct - I see 15GB for Onedrive for Business and 20GB for onedrive which I guess proves my point.

I wonder if there is a way to query this with the API.

You could use `--max-size 15G` to ignore files that are too big.

@Cnly thoughts?

**Comment by Cnly** [comment]
> 15GB for Onedrive for Business and 20GB for onedrive

Yes, it's surprising that Business accounts have a lower limit.

> I wonder if there is a way to query this with the API.

I don't remember something like that... But they have this [`maxFileSizeExceeded`](https://developer.microsoft.com/en-us/graph/docs/concepts/errors) error code which I guess (not tested) will be returned when the file really exceeds the limit. @kristianrl Do you think you have any problem with this? :) (Correct me if the server just silently fails or something like that)

**Comment by kristianrl** [comment]
I never got around to writing back, but the `--max-size 15G` worked well for me.

As I recall, the transfer just timed out, but this has to do with Microsoft throttling my transfer speed to around 1,5 Mbit/sec.

You are welcome to close this ticket if you do not consider it a bug.
