### ISSUE TITLE
OpenDrive inconsistently failing on files >10GB

### ISSUE THREAD

**Issue by Repairmanmanman** [ncw/rclone#2646]
#### What is the problem you are having with rclone?

I’ve been trying to back up some things to OpenDrive through rclone. Mostly it works fine, but it seems to choke on individual files bigger than 10GB or so. There’s no explicit error (that I saw), it just tries to upload them over and over. It gets to the end, looks like it worked, then starts again.

I am aware that there was originally a problem with large files with the WebDav mode on OpenDrive, but this is using the new OpenDrive mode in 1.42, with encryption if it matters.

The chance of failure seems to increase with size. Files just slightly larger than 10GB worked eventually, but if it’s much more than that (one file I’m testing with is about 15GB), I haven’t been able to get it to upload cleanly.

According to OpenDrive, there are no file size limits for their service, so at least theoretically this should work.

Original forum thread here:
https://forum.rclone.org/t/opendrive-inconsistently-failing-on-files-10gb/6473

#### What is your rclone version (output from `rclone version`)

rclone v1.42
- os/arch: linux/amd64
- go version: go1.10.3

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

Arch Linux 64-bit

####  Which cloud storage system are you using? (eg Google Drive)

OpenDrive

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

rclone sync -vv -L --checkers 16 --transfers 16 /data OpenDrive_Crypt:/

(However the following log is from a test command where I only uploaded a single file. Same result either way though.)

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

Relevant bit as determined by ncw:

2018/08/16 14:30:08 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2018/08/16 14:30:08 DEBUG : encryptedXXXX: Uploading chunk 1632, size=10485760, remain=14566075
2018/08/16 14:30:08 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2018/08/16 14:30:08 DEBUG : HTTP REQUEST (req 0xc420100200)
2018/08/16 14:30:08 DEBUG : POST /api/v1/upload/upload_file_chunk.json HTTP/1.1
Host: dev.opendrive.com
User-Agent: rclone/v1.42
Content-Length: 10487308
Content-Type: multipart/form-data; boundary=e6009437e443da64c4cc7bcad81ceb2826c39d8cf2fe7c575e69854af8ae
Accept-Encoding: gzip

2018/08/16 14:30:08 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2018/08/16 14:30:11 INFO  : 
Transferred:   159.605 GBytes (1.464 MBytes/s)
Errors:                 0
Checks:                 1
Transferred:            0
Elapsed time:   31h1m1.1s
Transferring:
 *   ...XXX: 100% /15.957G, 1.071M/s, 0s

2018/08/16 14:30:17 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2018/08/16 14:30:17 DEBUG : HTTP RESPONSE (req 0xc420100200)
2018/08/16 14:30:17 DEBUG : HTTP/1.1 200 OK
Transfer-Encoding: chunked
Access-Control-Allow-Origin: *
Cache-Control: no-cache, must-revalidate
Connection: keep-alive
Content-Language: en
Content-Type: application/json; charset=utf-8
Date: Thu, 16 Aug 2018 19:30:17 GMT
Expires: 0
Last-Modified: Thu, 16 Aug 2018 19:30:17 GMT
Server: nginx
Serverid: s7
X-Powered-By: OpenDrive.com

19
{"TotalWritten":10485760}
0

2018/08/16 14:30:17 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2018/08/16 14:30:17 DEBUG : encryptedXXXX: Uploading chunk 1633, size=10485760, remain=4080315
2018/08/16 14:30:17 ERROR : XXX: Failed to copy: failed to create file: EOF

**Comment by ncw** [comment]
It might be that these are just networking glitches.  It appears rclone didn't retry the block when it should have done though.

Here is a fix which will make the retries work properly, which hopefully will fix the problem

https://beta.rclone.org/branch/v1.43-153-g3cca20a9-fix-2646-opendrive-upload-beta/ (uploaded in 15-30 mins)

**Comment by ncw** [comment]
The build failed for that one, try this one instead :-)

https://beta.rclone.org/branch/v1.43-161-g33cb6515-fix-2646-opendrive-upload-beta/ (uploaded in 15-30 mins)

**Comment by Repairmanmanman** [comment]
I uploaded with that binary, and while it did retry a couple times, all my large files eventually uploaded and verified.

**Comment by ncw** [comment]
@Repairmanmanman thanks for testing :-)

It did exactly what I was hoping which is great.

I've merged that fix to master now it will be in [the latest beta](https://beta.rclone.org) in 15-30 mins and in v1.45
