### ISSUE TITLE
azureblob: support rclone's custom transport to fix --dump XXX

### ISSUE THREAD

**Issue by ncw** [ncw/rclone#2654]
I noticed while debugging azureblob recently that it doesn't support `-vv --dump headers`.  This is because It doesn't use [rclone's http Transport](https://github.com/ncw/rclone/blob/7f0b2042925b88c0f510df15026fdb1f7b5a8601/fs/fshttp/http.go#L118) like it should be.

I couldn't figure out how to add it immediately so [I asked a question](https://github.com/Azure/azure-storage-blob-go/issues/79) on how to and I received this reply

> Yes, it is possible to do. We do consider it a more advanced scenario. You can see an example of us doing it with our AzCopy utility [here](https://github.com/Azure/azure-storage-azcopy/blob/f967afe7fdf05b42e376abafff4d65bee295514a/ste/mgr-JobPartMgr.go#L65).
> 
> Basically, you have to call pipeline package's NewPipeline function passing in pipeline.Options after setting the HTTPSender field to the desired httpClient/transport you desire. NewPipeline also requires a slice of pipeline.Factory objects (which are also completely customizable but considered an advanced scenario) to manually configure pipeline policies such as telemetry, request IDs, credentials, retries, logging, etc. azblob's NewPipeline [function](https://github.com/Azure/azure-storage-blob-go/blob/67440baa31716bc29c9d0c48b1653f9afad3909b/2017-07-29/azblob/zc_pipeline.go) does this for you to address the common user case. You do NOT have to call azblob's NewPipeline to create a pipeline, you can manually create a pipeline to have more control over it.

It looks moderately complicated though!

@sandeepkru do you fancy having a go at this?

**Comment by sandeepkru** [comment]
@ncw I'll work on this, it may take one week to get this done (hope it's fine).

**Comment by ncw** [comment]
That sounds great - thank you :-)

**Comment by ncw** [comment]
@sandeepkru I'm going to do this one as I needed it to look at another issue

**Comment by ncw** [comment]
This is now in [the latest beta](https://beta.rclone.org) and will be released in 1.46
