### ISSUE TITLE
Filters not behaving as expected

### ISSUE THREAD

**Issue by victoriastuart** [ncw/rclone#2659]
Posted to https://forum.rclone.org/t/rclone-script-filters-to-back-up-from-linux-to-dropbox-with-includes-excludes/7202/2 but no answer (yet).

---
With the following command,

```
rclone sync --ignore-size --tpslimit 10 --skip-links  \
/home/victoria/   'dropbox:backups/victoria'  --filter-from \
/home/victoria/backups/rclone/rclone_filters.txt
```

and this “exclude everything else” [not explicitly included (`+`) or excluded (`-`)]

`- *`

at the end of my filters file, I am still getting folders such as

```
.gem/
anaconda2/
Desktop/
```

etc., appearing in Dropbox despite them not being listed (`+`) in my filters file. Shouldn’t they be excluded by the

`- *`

flag?

I also get the same result if I explicitly exclude them, e.g.

```
- .gem/**
- anaconda2/**
- Desktop/**
```

in that filters file. What am I doing incorrectly?

**Comment by ncw** [comment]
I've replied to this on the forum.  I'l close this one.
