### ISSUE TITLE
Implement `--low-level-retries` flag

### ISSUE THREAD

**Issue by kpabba** [ncw/rclone#266]
Hi,

I'm using rclone on raspberrypi to sync data on external HDD to amazon cloud. Below is the commend I'm using but the number of retries is always 10 even with the retries=1 set.

*Command:*
rclone --retries=1 sync /media/dir300/UseMe/ amzcld:UseMe/

*Log:*
2015/12/28 19:50:52 PhotosLibrary/Photos Library 9.55.20 PM.photoslibrary/Masters/2013/07/31/20130731-215027/DSC04098.JPG: Received error: HTTP code 409: "409 Conflict", reponse body: {"logref":"35dbb896-adc6-11e5-b1bb-7f2eb97d1295","message":"Node with the name dsc04098.jpg already exists under parentId dxrkTC5BTaudD71iJBhbtQ conflicting NodeId: 4vLN4NlkRDSTgd62sfbWFw","code":"NAME_ALREADY_EXISTS","info":{"nodeId":"4vLN4NlkRDSTgd62sfbWFw"}}
 **- retrying 4/10**
2015/12/28 19:51:12

**Comment by ncw** [comment]
That is a different sort of retry, one done on each HTTP transaction and there isn't a command line flag to adjust that :-(

The `--retries` flag makes rclone try the whole sync again rather than that one operation.

The error above might be caused by having two files with differing case `DSC04098.JPG` and `dsc04098.jpg` - amazon cloud drive doesn't allow that.

**Comment by kpabba** [comment]
Hmm,

Thanks for pointing that out ncw. In my case, I have thousands of pictures in my Apple photo Library (About 42 GB) which I'm trying to back up to Amazon Cloud Drive (ACD). I don't see a way to rename the all the duplicate file names unless there is an easy way that I don't know.

**Background:**
*Initial try-* Initially when I tried to use rclone to backup the pics from my Photos Library (on NAS), it copied almost everything(40 GB) in about 24 hrs but I had to cancel it for other reasons. At this point I was hoping that I can re issue the rclone command and it would pick up the rest (About 2GB) of the stuff and finish in a couple of hours at the max.

*Subsequent tries-* I've tried the same command for about 4 or 5 times now and had to cancel every time after about 24 hours, except for the latest try which is still going on after 2 days. All this for the remaining 2GB left. In the standard output, I see a lot of retries which I wrote in the first post above. So far, it has transferred about 200 MB out of the 2 GB left.

**Final Goal:**
I want to schedule rclone between my rbpi NAS and ACD on a weekly basis. This should backup all the new additions of the NAS to ACD. Can this be achieved in a fairly decent amount of time using RCLONE, please let me know.  

**Questions:**
1. Looks like ACD doesn't allow the same name files even in different directories, is that true?
2. Is there a way to exclude the same name files using RCLONE command?
3. Is my *Final Goal* described above possible with RCLONE at all?

Thanks for answering lot of questions on this forum ncw.

**Comment by ncw** [comment]
It might not be a duplicate file name - the error is suggestive of that but it could be something else.

> Thanks for pointing that out ncw. In my case, I have thousands of pictures in my Apple photo Library (About 42 GB) which I'm trying to back up to Amazon Cloud Drive (ACD). I don't see a way to rename the all the duplicate file names unless there is an easy way that I don't know.

You can use a bit of shell magic like this to find them

    cd directory/where/files/are
    find . -type f -print | tr '[:upper:]' '[:lower:]' | sort | uniq -c | grep -v '^ *1'

You should check.  It might just be ACD being flakey...

> Background:
> Initial try- Initially when I tried to use rclone to backup the pics from my Photos Library (on NAS), it copied almost everything(40 GB) in about 24 hrs but I had to cancel it for other reasons. At this point I was hoping that I can re issue the rclone command and it would pick up the rest (About 2GB) of the stuff and finish in a couple of hours at the max.

That is how it is supposed to work, yes.

> Subsequent tries- I've tried the same command for about 4 or 5 times now and had to cancel every time after about 24 hours, except for the latest try which is still going on after 2 days. All this for the remaining 2GB left. In the standard output, I see a lot of retries which I wrote in the first post above. So far, it has transferred about 200 MB out of the 2 GB left.

This could be related to #263 - do you have lots of files in one directory?

> Questions:
> 1. Looks like ACD doesn't allow the same name files even in different directories, is that true?

No, it should be fine with same name in different directories.

> 2. Is there a way to exclude the same name files using RCLONE command

Not at the moment, but good idea!

> OR limit HTTP transaction retries too?

That is another good idea - I could make a `--low-level-retries` flag
or something like that which would default to 10.

> 3. Is my Final Goal described above possible with RCLONE at all?

You are using rclone exactly how it is supposed to be used.  It should carry on where it left off and your Final Goal should work fine.

The fact it isn't working probably means either a bug in rclone, or a bug in ACD itself.

> Suggestions:
> 1. Could the retries flag be renamed or the retries word in the standard out put generated be renamed to avoid the confusion.

I'd prefer to add a `--low-level-retries` flag - what do you think of that?

**Comment by kpabba** [comment]
>You can use a bit of shell magic like this to find them
>
>```
>cd directory/where/files/are```
>find . -type f -print | tr '[:upper:]' '[:lower:]' | sort | uniq -c | grep -v '^ *1'
>```

Yes, if there is no other way to do it with RCLONE, I'll have to come up with some shell script to deal with individual files and folder but I'd like to avoid it as much as possible to keep it simple and easy to maintain.

>This could be related to #263 - do you have lots of files in one directory?

yes, it's photo library which MAC builds for you when you add pictures to the apple's *PHOTOS* app. It creates it's own sub directories and adds links to files on demand(to recognize faces and organize based on events, dates and such) and does a lot of other stuff when new photos are added to the app.

>        Is there a way to exclude the same name files using RCLONE command
>Not at the moment, but good idea!

Yes, if RCLONE can exclude duplicates with in the same directory (cases and spaces or anything which makes them different but are very very similar otherwise). flag could be ```--duplicates``` or something.

>I'd prefer to add a --low-level-retries flag - what do you think of that?
Yes, though the flag name is a bit long, it's okay as it's a bit clear but, the word *-retrying x/10* in the standardout/log should be changed to something like *low-level-try x/10*.


**More Questions :)**
1. Given my situation and where I'm now, what would be best for me to do at this point to 
    a. Do the initial clone
    b. Avoid the files already RCLONE had problems with in the subsequent scheduled RCLONE runs, because if the first clone failed to copy a few files, the chances are they would fail again and it's better to ignore them during the second run.

2. What's your take on one of the below solutions by *ameir in #180*
>I have tried the following projects, and one thing it does that I think is clever is maintain a local cache of remote file metadata in sqlite:
>https://github.com/alex-phillips/clouddrive-node
>https://github.com/alex-phillips/clouddrive-php

**More Suggestions :)**
1. Add ```rclone -h``` command's output to the ```man rclone``` command's output because it took a while for me to figure out how to use the *retries flag*. Since I didn't find the retries switch usage in man, I was trying different things expecting it to stop the retrying and when it never did, I always though it was my usage which had the problem until I got the exact syntax with *rclone -h*. Finally, after I was certain that I was using the command properly, I asked this question here.

**Comment by kpabba** [comment]
Hi nwc,

Just wanted to post a quick update. I spot checked some of the files rclone complained about being duplicate but didn't find any duplicates with that file name (both upper and lower case) on amazon or on my NAS drive.

**Comment by ncw** [comment]
Thanks for checking the duplicates.

I made a ticket about the retries documentation #278

The remote metadata caching in #180 is certainly interesting - if you want to discuss more then please do it on that ticket.

I think your original issue is caused by the general problems with amazon cloud drive which people are having at the moment which I'm hoping to find a work-around for.

However I'm going to use this ticket to implement a `--low-level-retries` flag and make your suggested change to the debug messages.

**Comment by kpabba** [comment]
Hi nwc,

Can you please include this change (--low-level-retries) in the next release? :)

Thanks

**Comment by ncw** [comment]
You should find that 1.27 is much improved in this regards. 

I did about half of this already but there was too much in 1.27 to put it in too.  Hopefully I'll get it in 1.28

**Comment by kpabba** [comment]
Yes, 1.27 is much better and I successfully finished my backup to ACD with the same command I used before. 

Only question at this point though is, it took about an hour to check that there were no differences between my drive and ACD when I ran it for the second time, is that expected time for 75GB of data with over 90,000 files?

**Comment by ncw** [comment]
That is taking much longer than it takes me..

For my Images collection (60k files, 550GB) it takes 1 minute and 20 seconds to do a "do nothing" sync.

Have you got a huge number of files in a single directory?

How long does `rclone size` take on the source and the destination of the sync?  That will give you and idea of where the bottleneck is.

**Comment by kpabba** [comment]
Wow, that's fast compared to mine. I tried your suggestion and got the below results.

**On RasperryPi:**

```
>amzcld:UseMe/mirror
...........
Total objects: 162240
Total size: 72.708G (78070079828 bytes)

Transferred:            0 Bytes (   0.00 kByte/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:    10m50.2s

>rclone size amzcld:UseMe/mirror
Total objects: 159311
Total size: 72.382G (77719793919 bytes)

Transferred:            0 Bytes (   0.00 kByte/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:    55m47.6s
```
