### ISSUE TITLE
rclone doesn't provide Content-type header when accessing webdav server

### ISSUE THREAD

**Issue by chrissv** [ncw/rclone#2664]
#### What is the problem you are having with rclone?
I am accessing a webdav server which requires Content-type headers for all PUT operations. It appears rclone never provides that header when rclone is accessing a webdav server.

#### What is your rclone version (output from `rclone version`)
Tried with both the latest release and latest beta:
rclone v1.43.1
- os/arch: linux/amd64
- go version: go1.11

rclone v1.44-004-ge8d0a363-beta
- os/arch: linux/amd64
- go version: go1.11.1

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Linux server 4.4.0-137-generic #163-Ubuntu SMP Mon Sep 24 13:14:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

####  Which cloud storage system are you using? (eg Google Drive)
A NextCloud server (v13 something)

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone sync -vv data/webdav.log hostit:data --dump requests,responses --checkers 1 --transfers 1 --low-level-retries 1

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
2018/10/17 20:45:26 DEBUG : rclone: Version "v1.43.1" starting with parameters ["rclone" "copy" "-vv" "data/webdav.log" "hostit:data" \
"--checkers" "1" "--transfers" "1" "--low-level-retries" "1" "--retries" "1"]
2018/10/17 20:45:26 DEBUG : Using config file from "/root/.config/rclone/rclone.conf"
2018/10/17 20:45:28 DEBUG : webdav.log: Couldn't find file - need to transfer
2018/10/17 20:45:31 ERROR : webdav.log: Failed to copy: 406 Not Acceptable
2018/10/17 20:45:31 ERROR : Attempt 1/1 failed with 1 errors and: 406 Not Acceptable
2018/10/17 20:45:31 Failed to copy: 406 Not Acceptable

Attached file "issue.log" with extra information by adding flags "--dump requests,responses"

**Comment by chrissv** [comment]
[issue.log](https://github.com/ncw/rclone/files/2489790/issue.log)

**Comment by chrissv** [comment]
I tried the beta referenced above, and the PUT transactions were accepted by the hosting server I deal with. It looks like it fixes the problem.

**Comment by ncw** [comment]
@chrissv Thanks for testing.  I've merged that to master now, it will be in [the latest beta](https://beta.rclone.org) in 15-30 mins and in v1.45.
