### ISSUE TITLE
Use google batch requests for fs.walk

### ISSUE THREAD

**Issue by devbrian** [ncw/rclone#2673]
#### What is your current rclone version (output from `rclone version`)?
1.44

#### What problem are you are trying to solve?
Greatly improve Dedupe time

#### How do you think rclone should be changed to solve that?
Improve fs.walk to use google batch requests, currently it takes over 24hours per dedupe cycle to build my directory list.  If fs.walk used batch requests, this could be completed in well under an hour.

**Comment by devbrian** [comment]
> The official Go package for drive does not support batch requests at this moment.
> 
> Have you tried to add the `--fast-list` flag to your dedupe command? This ist substantially faster than the regular method.
> 
> The `--fast-list` implementation does not use batch requests, but combines multiple directory lists into one command. It is currently hard coded to 50 folders per call, but this could made configurable.
> 
> How many folders are you trying to list? The last time I tested, I got 40k folders in 18min.

Thanks, this fixed my issue.

**Comment by devbrian** [comment]
@B4dM4n Does rclone dedupe actually exit when it finishes and does a full run of not finding any issues? Or does it just run forever?

**Comment by B4dM4n** [comment]
Good to hear.

I will close it then.
