### ISSUE TITLE
move with --dry-run creates empty folders in Google Drive

### ISSUE THREAD

**Issue by orange-buffalo** [ncw/rclone#2676]
#### Output of `rclone version`
```
$ rclone version
rclone v1.44
- os/arch: linux/amd64
- go version: go1.11.1
```
##### Short story
`move` with `--dry-run` creates empty folders in Google Drive.
##### Details
On a local machine, there is a folder `/tmp/move-source` with a file and sub-folder with another file:
```
$ ls -R
.:
nested-folder  source-file.txt

./nested-folder:
nested-source-file.txt
```
On Google Drive (configured in `rclone` as `gdrive`), there is an empty folder `move-target`.

Execute `rclone --dry-run move /tmp/move-source gdrive:/move-target`
Output is as expected:
```
2018/10/21 09:32:58 NOTICE: source-file.txt: Not moving as --dry-run
2018/10/21 09:32:58 NOTICE: nested-folder/nested-source-file.txt: Not moving as --dry-run
```
But there is a folder `nested-folder` created in Google Drive:
```
You created an item in
    move-target
        nested-folder
```
#### Interesting facts
* Running `copy` with the same setup does not create empty folders.
* Running `sync` with the same setup does not create empty folders.
* There was a similar issue fixed in 1.28: #342

**Comment by ncw** [comment]
I managed to replicate this locally too

```
cd /tmp/
mkdir dsrc
cd dsrc
mkdir dir
touch dir/sub
cd ..
mkdir ddst
rclone move --disable DirMove -vv --dry-run dsrc/ ddst
tree ddst/
```

The `--disable DirMove` was necessary to disable server side directory moves.

I've fixed this here

https://beta.rclone.org/branch/v1.44-037-g03add58e-fix-2676-move-mkdir-beta/ (uploaded in 15-30 mins)

Can you give it a test please?

Thanks

**Comment by orange-buffalo** [comment]
I've checked this version and it works just as expected - no new folders in Google Drive and also output highlights that folders are not created:
```
$ ./rclone --dry-run move /tmp/move-source gdrive:/move-target
2018/11/05 09:01:33 NOTICE: source-file.txt: Not moving as --dry-run
2018/11/05 09:01:33 NOTICE: nested-folder/nested-source-file.txt: Not moving as --dry-run
2018/11/05 09:01:33 NOTICE: nested-folder: Not making directory as dry run is set
```
Thank you for the fix!

**Comment by ncw** [comment]
I've merged that to master now thanks.

The fix will be in [the latest beta](https://beta.rclone.org) in 15-30 mins and in v1.45 when release :-)

**Comment by orange-buffalo** [comment]
Great, many thanks!
