### ISSUE TITLE
rclone config ondrive Personal last step error: 

### ISSUE THREAD

**Issue by guoxiangke** [ncw/rclone#2677]
#### What is the problem you are having with rclone?

rclone config ondrive Personal last step error: 
Failed to query available drives: Get https://graph.microsoft.com/v1.0/me/drives: dial tcp: lookup graph.microsoft.com on [::1]:53: read udp [::1]:48585->[::1]:53: read: connection refused

#### What is your rclone version (output from `rclone version`)

$ rclone version
rclone v1.44
- os/arch: linux/arm64
- go version: go1.11.1
####  Which cloud storage system are you using? (eg Google Drive)

ondrive

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

rclone config
2018/10/21 02:40:28 DEBUG : onedrive: Saved new token in config file
Choose a number from below, or type in an existing value
 1 / OneDrive Personal or Business
   \ "onedrive"
 2 / Root Sharepoint site
   \ "sharepoint"
 3 / Type in driveID
   \ "driveid"
 4 / Type in SiteID
   \ "siteid"
 5 / Search a Sharepoint site
   \ "search"
Your choice> 1
2018/10/21 02:40:49 Failed to query available drives: Get https://graph.microsoft.com/v1.0/me/drives: dial tcp: lookup graph.microsoft.com on [::1]:53: read udp [::1]:42292->[::1]:53: read: connection refused

**Comment by Cnly** [comment]
Hi @guoxiangke, this is most likely not a problem of rclone. There seems to be some problems with your network. Please check the DNS config on your local system.

**Comment by guoxiangke** [comment]
ok.thanks I'll check.
