### ISSUE TITLE
rclone mount Windows: Provide drive label

### ISSUE THREAD

**Issue by chrissv** [ncw/rclone#2679]
#### What is your current rclone version (output from `rclone version`)?
rclone v1.43.1
- os/arch: windows/amd64
- go version: go1.11

#### What problem are you are trying to solve?
When running "rclone mount" in Windows, the resulting drive shows up with the label "Local Disk"
If there are multiple rclone remotes mounted, it is difficult to tell them apart.
In windows, you can name a drive (by clicking on the name by the drive letter).

Side note: It seems I can rename a mounted rclone drive. But it appears Windows associates the name with the drive letter, instead of the rclone remote name. So if I mount a different remote on the same drive letter, the old name shows up - not desired operation.

This request is to let me provide the Windows drive name with the "rclone mount" command.
Even if I change the name after the remote is mounted, the next time I mount the remote, I want it to use the provided label.

#### How do you think rclone should be changed to solve that?
By a command-line argument:
rclone mount --label="MyDriveName" remote: F:

**Comment by ncw** [comment]
Rclone has a `--volname` flag for this purpose which didn't work on Windows.  It turns out it was really easy to make it work on Windows - can you have a go with this?

https://beta.rclone.org/branch/v1.44-006-g7c270b74-fix-2679-windows-volname-beta/ (uploaded in 15-30 mins)

**Comment by chrissv** [comment]
My apologies I did not notice the `--volname` flag. But as you mentioned, it didn't work in Windows, so this would have been a bug report instead of a feature request.

I tried the beta you provided, and it fixes the problem 100%, and operates as I intended.

Good job!

**Comment by ncw** [comment]
Oops I forgot to merge this.

It will be in [the latest beta](https://beta.rclone.org) in 15-30 mins and in the v1.45 release

**Comment by chrissv** [comment]
Sounds good. I was wondering why I didn't see this fixed in the recent beta versions.
I just verified the fix in `rclone v1.44-081-gb3704597-beta`
