### ISSUE TITLE
Don't recurse into directories which are excluded by filter

### ISSUE THREAD

**Issue by bardamatic** [ncw/rclone#268]
Hi ncw,

From working with filtering rules, I noticed that rclone expands through the entire directory structure even when excluding some files.  In my setup this leads to a (infinite?) recursion of a directory that is mounted within the directory structure I am trying to sync.

For example, I have /mnt/bind which is a bind mount of /

Now if I try to sync /mnt/bind, it fails.

I believe the reason is because within /mnt/bind is this same mount point recurring over and over again i.e.
/mnt/bind/mnt/bind/mnt...

I have put this particular directory in the exclude-files.txt trying the following exclude rules for 4 separate attempts:
/mnt/** 
/mnt** 
mnt/**
mnt**

I believe all of these function the same way for this example.  

The log reports back that this directory /mnt/ is in fact being properly excluded but rclone continues to traverse the total /mnt/ directory, attempting to report back the name of everything that was excluded.  In doing this traverse, it logs filename too long errors.

I think this is the expected behaviour for name based matching, but an enhancement could be to have rclone stop traversing a directory structure that matched to be excluded, but I have no idea how possible that is.

One way around this is to use rclone in series, where each new instance is responsible for a different specific directory within /mnt/bind versus something more global.  This way I can manually skip the /mnt/bind/mnt/ directory.

That being said, I really appreciate rclone.  Thanks for all the hard work.

**Comment by ncw** [comment]
Thanks for analysing that - I agree with you.

I can think of two ways of fixing your problem.

  * Get the remotes which understand directories to stop recursing on excluded directories.  This would be the most efficient fix.  At minimum I could to this for the local filesystem.
  * Get the local filesystem driver to keep a note of the inode number of each directory it scans and skip directories it has already scanned.  This would speciffically solve the mount bind issue.

I should note that rsync also has issues with mount bind directories - It doesn't skip them with the `-x` flag like you might expect.

**Comment by cbcoursera1** [comment]
I'd just like to add that this would be helpful for users who just have a huge number of directories that they want to exclude.

My Lightroom catalog has 85K files in 63K folders, so you can imagine the time required to create an index of this on a remote - and even locally.

To make things quicker, I've decided to only backup 44 files and 14 folders from the catalog. So even though rclone doesn't need to sift through 63K folders on the remote, it still spends nearly 60 seconds recursing through all the directories that I have no interest in on the local.

Hope this can be implemented, it would be a great enhancement!

**Comment by CristianDeluxe** [comment]
To add more reasons, in my ubuntu, rclone shows errors in /proc/ directory with some processes that were closed before rclone was able to check it.

**Comment by ncw** [comment]
This should work properly in the latest beta - fancy giving it a go?

http://pub.rclone.org/v1.29-28-g36700d3%CE%B2/

**Comment by CristianDeluxe** [comment]
Seems to be working for me, nice work :) 👍

**Comment by ncw** [comment]
Great - thanks for testing

**Comment by ncw** [comment]
This will be in the next release
