### ISSUE TITLE
[Suggestion] `--immutable-source` and `--immutable-destination` options

### ISSUE THREAD

**Issue by kuraga** [ncw/rclone#2686]
Good day!

Thank you for `rclone`! It's a new era of backup for me (via Yandex Disk storage - it's unusable because of freezing via WebDAV).

We have `--immutable` option. Suggest to introduce `--immutable-source` and `--immutable-destination` options.

Reason: during backup operations I want to be sure that my source is untouched.

BTW @ncv, a question: if `rclone` doesn't need to modify some objecs during this command, does it open it in read-only mode (if possible)? For simplicity, does it open files with `'r'` flag if storage is `local`?

Thanks.

**Comment by ncw** [comment]
> Thank you for `rclone`! It's a new era of backup for me (via Yandex Disk storage - it's unusable because of freezing via WebDAV).

:-)  The [Yandex backend is being re-written here](https://github.com/ncw/rclone/pull/2695) BTW



> We have `--immutable` option. Suggest to introduce `--immutable-source` and `--immutable-destination` options.

The source is never changed so rclone is effectively `--immutable-source` already I think.



> BTW  a question: if `rclone` doesn't need to modify some objecs during this command, does it open it in read-only mode (if possible)? For simplicity, does it open files with `'r'` flag if storage is `local`?

In the local backend, rclone only opens with O_RDONLY when reading files.

This is the same through all the remotes (though they have differing implementations).

**Comment by kuraga** [comment]
> > Thank you for rclone! It's a new era of backup for me (via Yandex Disk storage - it's unusable because of freezing via WebDAV).
>
> :-) The Yandex backend is being re-written here BTW

Yandex.Disk is unusable via WebDAV. Not via rclone :-)

> The source is never changed so rclone is effectively `--immutable-source` already I think.

Yes. I misunderstood something.

Thanks.

**Comment by ncw** [comment]
> Yandex.Disk is unusable via WebDAV. Not via rclone :-)

Shortly it will be even better :-)

> Yes. I misunderstood something.

No worries!
