### ISSUE TITLE
Replace `home/ncw` with `$HOME`?

### ISSUE THREAD

**Issue by kuraga** [ncw/rclone#2687]
Hello, @ncw !

I saw `/home/ncw` in documentation many times. `git grep 'home/ncw'` on you repository and replace `home/ncw` with `$HOME`, maybe?

Thanks.

**Comment by ncw** [comment]
Well spotted.

You can ignore any that are outside `docs/content` - all the other docs are auto generated.

These seem to be nearly all in the `docs/commands` - these are generated by this Makefile targe

```
commanddocs: rclone
        rclone gendocs docs/content/commands/
```

So an ideal fix would be to fix the `gendocs` command, or maybe add a post-processor into the make command - maybe a bit of `sed` to do the replacements?
