### ISSUE TITLE
Request: Implement rsync-like exclude/include

### ISSUE THREAD

**Issue by ChrisSLT** [ncw/rclone#27]
I know you are focused on working out kinks with Drive and S3, but when you're ready for new features:

It would be terrific to have the following abilities work exactly as they do in rsync.  Here is a prioritized list:

1) --max-size and --min-size.  Why? - with backing up to cloud storage, it is important not to waste time accidentally backing up a 2GB movie file or something when you're backing up someone's Documents folder...

2) --exclude-from.  I hope you will stick as closely as you can to Rsync's exact behavior here.  The AWS CLI team is going off and reinventing the wheel with their exclude/include function and it's really frustrating/unecessary, when the rsync community has spent years coming up with an elegant and totally functional solution.  The best part about rsync's is you can list the excludes in a file, so the actual command remains elegant and easy to read.
  
Thanks!

**Comment by ncw** [comment]
For min/max we are talking about

            --max-size=SIZE         don't transfer any file larger than SIZE
            --min-size=SIZE         don't transfer any file smaller than SIZE

For include/exclude we are talking about these flags

        -f, --filter=RULE           add a file-filtering RULE
            --exclude=PATTERN       exclude files matching PATTERN
            --exclude-from=FILE     read exclude patterns from FILE
            --include=PATTERN       don't exclude files matching PATTERN
            --include-from=FILE     read include patterns from FILE

You'd probably want the related

            --delete-excluded       also delete excluded files from dest dirs
        -C, --cvs-exclude           auto-ignore files in the same way CVS does

rsync include exclude patterns are quite complicated!  I'd probably implement just include (+) and exclude (-) rules to start with.

**Comment by ChrisSLT** [comment]
Yes, these features would be really helpful in a production environment where I'm not there to be sure rclone doesn't waste time accidentally syncing huge files (hence limiting by max-size) or whole directories that shouldn't be included.  

I can imagine this is a fair bit of work?

**Comment by mullenkamp** [comment]
I would be particularly interested in the --files-from option in rsync to specify specific directories to sync rather than running multiple instances of rclone for separate directories.

''''
     --files-from=FILE       read list of source-file names from FILE
''''

**Comment by ChrisSLT** [comment]
rsync also has a great way to point to a file with all directories to exclude

**Comment by AntoineGR** [comment]
+1 very interested, to exclude small metadata files that hog syncing (excluding with min-size or file extension in my case)

**Comment by shawnbissell** [comment]
+1 would really like to be able to exclude metadata files

**Comment by bdarcus** [comment]
+1 on this.

**Comment by ncw** [comment]
OK that is quite a lot of votes for this issue - I'll try to get it in the next release!

**Comment by kruglikov** [comment]
+1 for --exclude

**Comment by ncw** [comment]
I've released this feature in rclone 1.22.

See the [filtering docs](http://rclone.org/filtering/) for more info!

If you have any suggestions for improvements (eg to the docs!) or find any problems, please open a new issue!

**Comment by klauspost** [comment]
Wow - nice!

**Comment by bdarcus** [comment]
Thanks Nick!

**Comment by ChrisSLT** [comment]
Great! Thank you!

**Comment by shawnbissell** [comment]
Great thanks!

**Comment by shawnbissell** [comment]
@ncw Just started reading the docs and noticed this line 
"Rclone implements bash style {a,b,c} glob matching which rclone doesn’t." 
should it say "rsync doesn't" at the end?

**Comment by ncw** [comment]
@shawnbissell well spotted - I'll fix that now!

**Comment by AntoineGR** [comment]
Working perfectly !
Thank you so much :)

**Comment by sphakka** [comment]
IIUC, `--cvs-exclude` is not implemented: that would be a nice time saver. Any plan for that?

**Comment by sphakka** [comment]
> > IIUC, `--cvs-exclude` is not implemented: that would be a nice time saver. Any plan for that?
> 
> Not currently... Though `--cvfs-exclude` seems like a misnomer in this git world!

Ha, ha, what about `--git-exclude` then?? Thanks for the list :-)

**Comment by ptman** [comment]
--scm-exclude? --vcs-exclude? or --common-exclude? (might include *.swp and *~ and similar as well)

**Comment by ankur0493** [comment]
@ncw Why do we ignore other filtering rules when using `--files-from`?
