### ISSUE TITLE
Windows WinFsp mount as a folder don't functioned

### ISSUE THREAD

**Issue by cyberpunkbln** [ncw/rclone#2702]
#### What is the problem you are having with rclone?

When i mount under Windows 10 and Folder/Remote into a folder (rclone.exe mount Enrypted-Local: c:\Users\cp\rclone-container) then i can access the folder and the root of the folder but when i go into Dirs/folder in the folder, then i became an error message that windows dont' can find the folder. But filenames and dir with one letter functioned.

Driveletter functioned perfectly when i try to mount, like all dokany winfsp apps.

Is this an restriction from winfsp?

Or give it any chance that i can mount rclone-encrypted-remotes/locales into an folder/dir.

I have forgot. I use only NTFSnot FAT32/exFAT or so.

#### What is your rclone version (output from `rclone version`)
1.44

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Windows 10

####  Which cloud storage system are you using? (eg Google Drive)
Local

Thx

**Comment by ncw** [comment]
> Is this an restriction from winfsp?

As far as I know, WinFSP can only mount to a drive letter.  At least that is how I've always used it.

Have you seen any docs to suggest otherwise?

**Comment by cyberpunkbln** [comment]
Hello,

thx for your reply. No i only wonder that i can mount it as folders. I use winfsp for drives, too. But it will be a great function for this and for the first look its functioned.
