### ISSUE TITLE
--bwlimit Not respected

### ISSUE THREAD

**Issue by tibmeister** [ncw/rclone#2711]
#### What is the problem you are having with rclone?
Using --bwlimit 512k to limit the utilized bandwidth.  My upload is still becoming saturated (5M) that I can correlate directly to rclone.

#### What is your rclone version (output from `rclone version`)
1.44

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Ubuntu 14.04.5 LTS x64

####  Which cloud storage system are you using? (eg Google Drive)
OneDrive

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone sync --bwlimit 512k

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
2018/10/28 19:50:38 DEBUG : rclone: Version "v1.44" starting with parameters ["rclone" "sync" "/home/ubuntu" "oDrive:opti_back/home/" "--skip-links" "--update" "--bwlimit" "512k" "--filter-from" "/home/ubuntu/rclone-filter.txt" "-vv"]
2018/10/28 19:50:38 DEBUG : Using config file from "/home/ubuntu/.config/rclone/rclone.conf"
2018/10/28 19:50:38 INFO  : Starting bandwidth limiter at 512kBytes/s

**Comment by ncw** [comment]
Note that rclone measures its bandwidth limits in kBytes so 512k is 512kBytes/s which is approx 5Mbit/s.

If you want 512kbit/s then use `--bwlimit 64k`

**Comment by tibmeister** [comment]
Interesting, if I use --bwlimit 512k with --progress, I get things limited at the anticipated 512k, but I can see that my traffic increase to my WAN router is < 700k, so maybe there's something odd in the code???
I do notice that if I schedule using crontab and the 512k, then the uplink get's saturated and I also see a couple dozen instanced running with ps aux, so not sure what's going on there either.
I will keep testing and seeing if I can get a better pattern, but good to know the desired setting is in kBytes and not Kbits.

**Comment by tibmeister** [comment]
Ok, I think I tracked it down.  When running from crontab, it starts multiple instances, here's the ps aux | grep rclone output

`ubuntu   23011  0.0  0.0   4444   644 ?        Ss   21:35   0:00 /bin/sh -c rclone sync /home/ubuntu oDrive:opti_back/home/ --skip-links --update --bwlimit 196k --filter-from /home/ubuntu/rclone-filter.txt --drive-list-chunk 100 --fast-l
ist --onedrive-chunk-size 640k --syslog >/dev/null 2>&1
ubuntu   23015 17.1  0.4 128628 25580 ?        Sl   21:35   0:02 rclone sync /home/ubuntu oDrive:opti_back/home/ --skip-links --update --bwlimit 196k --filter-from /home/ubuntu/rclone-filter.txt --drive-list-chunk 100 --fast-list --onedr
ive-chunk-size 640k --syslog
ubuntu   23161  0.0  0.0  10708   924 pts/4    S+   21:35   0:00 grep --color=auto rclone`

My crontab entry is as follows, just for testing, but the plan is to have it run at 4am every day.

`35 21 30 10 * rclone sync /home/ubuntu oDrive:opti_back/home/ --skip-links --update --bwlimit 196k --filter-from /home/ubuntu/rclone-filter.txt --drive-list-chunk 100 --fast-list --onedrive-chunk-size 640k --syslog >/dev/null 2>&1`

**Comment by ncw** [comment]
Did one rclone not finish before the other one started?

An easy way to ensure only one rclone find at once is to use the --rc flag.

**Comment by tibmeister** [comment]
I thought that at first, but the output from ps aux above is from a single crontab entry that ran at 21:35.  I took the capture at 21:36, so somehow it spawned a child.  Let me try with the --rc flag and see what happens.

**Comment by ncw** [comment]
> I thought that at first, but the output from ps aux above is from a single crontab entry that ran at 21:35. I took the capture at 21:36, so somehow it spawned a child. Let me try with the --rc flag and see what happens.

I edited your comment to fix the formatting and what happened is clear now!  One process is the shell, which forked the rclone process, so there is only one rclone running.

**Comment by ncw** [comment]
I think we are done here so I'm going to close this :-)
