### ISSUE TITLE
WebDav: Another Time  Format Issue

### ISSUE THREAD

**Issue by rhemberger** [ncw/rclone#2712]
#### What is the problem you are having with rclone?
I am trying to setup a webdav sync using webdav.komfortcloud.de (Kabel Deutschland / Vodafone) but rclone is unable to obtain a directory listing, so cannot sync. Problem is reproducible. They use time format RFC3339.

#### What is your rclone version (output from `rclone version`)
```
$ rclone -V
rclone v1.44
- os/arch: linux/amd64
- go version: go1.11.1
```

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
`Linux ubuntu 4.18.0-10-generic x86_64 `

####  Which cloud storage system are you using? (eg Google Drive)
WebDav: https://kabel.vodafone.de/tarife/meinedienste/cloud_speicher

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
`rclone -vv ls komfortcloud:`

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
$ rclone -vv ls komfortcloud:
```
2018/10/29 17:55:54 DEBUG : rclone: Version "v1.44" starting with parameters ["rclone" "-vv" "ls" "komfortcloud:"]
2018/10/29 17:55:54 DEBUG : Using config file from "/home/rhemberger/.config/rclone/rclone.conf"
2018/10/29 17:55:54 ERROR : : error listing: couldn't list files: parsing time "2018-02-28T20:24:24Z" as "Mon, _2 Jan 2006 15:04:05 MST": cannot parse "2018-02-28T20:24:24Z" as "Mon"
2018/10/29 17:55:54 Failed to ls: couldn't list files: parsing time "2018-02-28T20:24:24Z" as "Mon, _2 Jan 2006 15:04:05 MST": cannot parse "2018-02-28T20:24:24Z" as "Mon"
```

**Comment by ncw** [comment]
Fancy sending a patch to fix this?  It should just be a question of putting time.RFC3339 into this list

https://github.com/ncw/rclone/blob/04a0da1f9284891d8138a35252d873564617d7f5/backend/webdav/api/types.go#L142-L148
