### ISSUE TITLE
Add 2FA support for jottacloud 

### ISSUE THREAD

**Issue by Naguz** [ncw/rclone#2722]
#### What is your current rclone version (output from `rclone version`)?
v1.43 AFAIK the feature is not added in 1.44

#### What problem are you are trying to solve?
Backing up to jottacloud with two factor enabled
Now, this results in: 
Failed to create file system for "jottapriv:freenas": couldn't get account info: failed to get endpoint url: error 401: org.springframework.security.authentication.BadCredentialsException: Invalid. Basic-auth disabled when 2FA is activated. (Unauthorized)

#### How do you think rclone should be changed to solve that?
Handle Two factor authentication for jottacloud
The official (beta) cli-client jotta-cli (https://docs.jottacloud.com/jottacloud-command-line-tool) handles this. The login process triggers a two factor SMS, and it asks you for the OTP before trying to connect. I would guess it gets some kind of device token or other to authenticate, as it stores this for future connections.

**Comment by ncw** [comment]
We've just merged support for this (thanks @buengese ) which means it will be in [the latest beta](https://beta.rclone.org) in 15-30 mins and released in v1.46

**Comment by jinie** [comment]
Installed and testing right now. Have a ~6TB restic backup running through rclone to Jotta, so we'll see how it behaves :)
