### ISSUE TITLE
"Illegal instruction" on MIPS architecture

### ISSUE THREAD

**Issue by tony-sunjian** [ncw/rclone#2725]
#### Output of `rclone version`

V1.44

#### Describe the issue

device: Thunder Timecloud  
cpu: MT 7621AT
linux core version:4.4.153
system: LEDE Reboot 17.01.6 r3979-2252731af4 / LuCI lede-17.01 branch (git-18.201.27126-7bf0367)

i download the  rclone-v1.44-linux-mipsle .
i runs well on linux core version:3.14  and system : LEDE14.07
today i update the system. and the linux core updated  to 4.4.153

when i sun the script  ./rclone config

it returns "Illegal instruction"

how can i  solve the problem

**Comment by Cnly** [comment]
I found a [post](https://forum.rclone.org/t/rclone-with-lede-openwrt-router/5607) highly relevant on the forum. And we have https://github.com/ncw/rclone/pull/2724. @ncw maybe we should test the PR and then merge it?

@tony-sunjian I plan to build the binaries for that PR now and should be able to put them here in a while. Can you help with the testing?

**Comment by tony-sunjian** [comment]
@Cnly  no problem, do you need the ssh? or what should i do

**Comment by tony-sunjian** [comment]
@Cnly  still returns "Illegal instruction", i can send you the ssh account,

**Comment by tony-sunjian** [comment]
@Cnly do y have telegram , add 15851972815 ,then i send you ssh

**Comment by tony-sunjian** [comment]
@Cnly or e-mail what ever

**Comment by tony-sunjian** [comment]
> [rclone-v1.44-037-g148b0de7-beta-linux-mipsle.zip](https://github.com/ncw/rclone/files/2549296/rclone-v1.44-037-g148b0de7-beta-linux-mipsle.zip)
> 
> @tony-sunjian Can you have a try with this version? Thanks.

my email : 717114806@qq.com

**Comment by Cnly** [comment]
@tony-sunjian I checked the config again and it seems the arch name is not correct in the PR. This version should work:

[rclone-v1.44-037-g148b0de7-beta-linux-mipsle.zip](https://github.com/ncw/rclone/files/2549458/rclone-v1.44-037-g148b0de7-beta-linux-mipsle.zip)

But if you want to send me something like credentials, that's okay too and you can reach me at minecnly@gmail.com. I may not be able to do remote tests right away, though.

**Comment by tony-sunjian** [comment]
@Cnly i send you ssh account , you may try it

**Comment by tony-sunjian** [comment]
> @tony-sunjian I checked the config again and it seems the arch name is not correct in the PR. This version should work:
> 
> [rclone-v1.44-037-g148b0de7-beta-linux-mipsle.zip](https://github.com/ncw/rclone/files/2549458/rclone-v1.44-037-g148b0de7-beta-linux-mipsle.zip)
> 
> But if you want to send me something like credentials, that's okay too and you can reach me at [minecnly@gmail.com](mailto:minecnly@gmail.com). I may not be able to do remote tests right away, though.

sorry, still  returns "Illegal instruction"

**Comment by sedlund** [comment]
@Cnly you will have to build with:
GOARCH=mipsle GOMIPS=softfloat go build -a

If you have a previous build and then change GOMIPS=softfloat, you have to pass -a to go build to force rebuild of everything

**Comment by sedlund** [comment]
@tony-sunjian 
No, it does not have FPU.

OpenWRT had the kernel configured to enable FPU emulation with kernel 3.14 which is why it worked.  When they switched to the 4.x kernel code base the kernel defaults to not enable FPU emulation - I think they just forgot to enable it - as they still build packages and ship packages (nodejs and others) that require FPU to work.

**Comment by tony-sunjian** [comment]
> @tony-sunjian
> No, it does not have FPU.
> 
> OpenWRT had the kernel configured to enable FPU emulation with kernel 3.14 which is why it worked. When they switched to the 4.x kernel code base the kernel defaults to not enable FPU emulation - I think they just forgot to enable it - as they still build and ship packages (nodejs and others) that require FPU to work.

i'v already  send a bug report to openwrt 
https://bugs.openwrt.org/index.php?do=details&task_id=1929

**Comment by Cnly** [comment]
@sedlund thanks for the tip! It seems I've made the same mistake as the one in that forum post! :P

I tried with a clean build of the PR on @tony-sunjian your device and it runs with no error. Thanks for your help! Version output:

```
rclone v1.44-042-g4a6cfbeb-patch-1-beta
- os/arch: linux/mipsle
- go version: go1.11.2
```

**Comment by tony-sunjian** [comment]
> @sedlund thanks for the tip! It seems I've made the same mistake as the one in that forum post! :P
> 
> I tried with a clean build of the PR on @tony-sunjian your device and it runs with no error. Thanks for your help! Version output:
> 
> ```
> rclone v1.44-042-g4a6cfbeb-patch-1-beta
> - os/arch: linux/mipsle
> - go version: go1.11.2
> ```

thanks a lot, i seen the rclone.new  file , it runs well! perfect!

**Comment by ncw** [comment]
I've merged @sedlund 's PR to enable softfloat now - thank you!

This will be in [the latest beta](https://beta.rclone.org) in 15-30 mins and release in v1.45.
