### ISSUE TITLE
Swift Memstore uploads fail without admin privileges

### ISSUE THREAD

**Issue by analbeard** [ncw/rclone#273]
Hi Nick

As discussed, I'm unable to upload (sync) to a container on Memstore using anything other than the admin user - this appears to be due to rclone creating a PUT request even when the container exists which of course fails if I don't have admin privileges.

Thanks

Simon

**Comment by ncw** [comment]
This should be easy to fix with a bit of checking before mkdir.  Should probably do this in s3/gcs too as this operation in s3 has been troublesome in the past with third party implementations.
