### ISSUE TITLE
Ability to set new permanent path for rclone.conf file - QNAP Problem

### ISSUE THREAD

**Issue by gelsas** [ncw/rclone#2731]
On QNAP the config file is created in the root directory of the NAS.

The problem with QNAP NASes is that everything which is created in the root folder will be gone after an restart/reboot of the system because the root directory is on the RAMDISK.

Can we somehow find a solution for this? That would help me alot!

**Comment by ncw** [comment]
How are you accessing the QNAP?  sftp?

Try not using a leading /, so `qnap:file` rather than `qnap:/file`.

Can you give an example command  with log and show what your config looks like (without the passwords/tokens) please?

Thanks

**Comment by gelsas** [comment]
Via SFTP

The problem is not my config or something like that.
The problem is just the location where rclone creates the config file: 
2018/11/09 13:32:59 NOTICE: Config file "/root/.config/rclone/rclone.conf" not found - using defaults

Everything folder which is inside the /root/ folder on QNAPs will be gone after a reboot because it is stored in RAMDISK.

**Comment by gelsas** [comment]
Should I still post my rclone.conf here ?

**Comment by gelsas** [comment]
Thank you that was the solution. My bad for not realizing it earlier. I will close this issue.
