### ISSUE TITLE
jottacloud: java.lang.IllegalArgumentException: Unable to validate decoded path

### ISSUE THREAD

**Issue by mholt** [ncw/rclone#2734]
#### What is the problem you are having with rclone?

Connecting to a Jottacloud backend gives this error:

```
2018/11/09 11:08:44 Failed to create file system for "jottacloud:foo": couldn't get account info: failed to get endpoint url: error 400: java.lang.IllegalArgumentException: Unable to validate decoded path: /my+email@example.com (Bad Request)
```

After going to Jottacloud settings and changing my email address to one that does not have a `+` character in it, it worked, with that being the only change.

Not sure if the bug lies with rclone or in Jottacloud. I assume rclone is not producing the java exception. :wink:

Discovered this while reporting #2733.

#### What is your rclone version (output from `rclone version`)

```
rclone v1.44-DEV
- os/arch: darwin/amd64
- go version: go1.11
```

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

macOS, 64bit

####  Which cloud storage system are you using? (eg Google Drive)

Jottacloud

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

```
RCLONE_CONFIG_JOTTACLOUD_TYPE=jottacloud RCLONE_CONFIG_JOTTACLOUD_MOUNTPOINT=Archive RCLONE_CONFIG_JOTTACLOUD_PASS=my-password-yes-its-correct RCLONE_CONFIG_JOTTACLOUD_USER=my+email@example.com rclone copy /foo jottacloud:foo
```

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

Let me know if this is needed -- I will happily provide it, but it will take me a little time because of how rclone is integrated with our application.

**Comment by ncw** [comment]
Hmm, this looks like a URL escaping problem which has been problematic in the past at Jottacloud.

@buengese or @olihey any thoughts?

**Comment by buengese** [comment]
This is very weird the '+' in the email address should get escaped.
https://github.com/ncw/rclone/blob/c4b0a37b212bb147c118949d960baf2fa0ba31c2/backend/jottacloud/jottacloud.go#L202
I'll need to this myself but this in potentially another bug in the Jottacloud API. I'd be interested if it works with official client though they're most likely using a different method to retrieve the account id.

**Comment by ncw** [comment]
I wonder whether this particular function needs the standard URL escape as `urlPathEscape` is special.

https://github.com/ncw/rclone/blob/c4b0a37b212bb147c118949d960baf2fa0ba31c2/backend/jottacloud/jottacloud.go#L244-L247

Though the error message reported had `+` in, indicating it did get decoded.

**Comment by buengese** [comment]
No this doesn't work either. It'll result in 
```
2018/11/11 15:28:12 Failed to create file system for "jtest:": couldn't get account info: failed to get endpoint url: error 401: org.springframework.security.authentication.BadCredentialsException: No such user/email (Unauthorized)
```
I don't really see an easy way to fix this right now. I'll need to look into the official client again.

**Comment by ncw** [comment]
> No this doesn't work either.

Sounds like it is a Jottacloud bug then... Unless the oficial client deals with it!

**Comment by jkaberg** [comment]
@mholt if you can find you're unique jotta user id (browse the API endpoints), you can use that as well (to login)..

This is what I do :-)

**Comment by buengese** [comment]
I just checked it with the official client and it does fail exactly the same way it's definitely a bug in their API.

**Comment by mholt** [comment]
Thanks for checking, @buengese .

I'm content with closing this, then, since it's not an rclone issue.
