### ISSUE TITLE
`--ignore-existing` to skip updating files that exist on receiver

### ISSUE THREAD

**Issue by ff-b4** [ncw/rclone#274]
ncw,

Can we get a --name-only option for ACD ignoring the mod time, md5 and size?

**Comment by klauspost** [comment]
Could you elaborate on the use case for that feature?

**Comment by ff-b4** [comment]
It will round out the options available for ACD. I.e. we have the md5 mod date, and size-only, also known to us is the file name on ACD.

Another use case is when encrypting files on the fly before they are uploaded to ACD. I can use gpg to encrypt a file and the size and md5 will be different every time, so it will essentially update this file on ACD.  Adding the --name-only option should mitigate this.

**Comment by klauspost** [comment]
So in effect it is a "skip-existing-files" behaviour?

**Comment by ff-b4** [comment]
That's what I'm picturing. If the option --name-only is set and you come across a file of the same name on ACD, it should skip this file.

**Comment by ncw** [comment]
Back to the rsync man page I see these useful looking options...

```
            --existing              skip creating new files on receiver
            --ignore-existing       skip updating files that exist on receiver
```

I think the second one of these would be equivalent to `--name-only` but better named and with a precedent from rsync.

How does that sound?

**Comment by ff-b4** [comment]
I think that is along the lines of what I was mentioning, thanks for the find.

**Comment by klauspost** [comment]
Added PR #276.
