### ISSUE TITLE
mount creates duplicate files on Google Drive

### ISSUE THREAD

**Issue by dreamstorpi** [ncw/rclone#2742]
#### Output of `rclone version`
rclone v1.42β
- os/arch: linux/amd64
- go version: go1.10.1

Fedora 28, xfce4, thunar file manager

I am reporting this issue because I am using the latest beta version of rclone and using mount.

#### Describe the issue
I am using this rclone command:

rclone mount cda:choeurdelaude/  /home/hwright/choeurdelaude/ --vfs-cache-mode full --cache-dir /home/hwright/.rclone --delete-before

with this config file:

[cda]
type = drive
client_id = 
client_secret = 
scope = drive
root_folder_id = 
service_account_file = 
token = {"access_token":"01234567890123456789","token_type":"Bearer","refresh_token":"0123456789"}

(access tokens are modified for this posting)

a) Run the command = my google drive is mounted.
b) Create a directory 'rclone test' on local machine using thunar = directory is created on Google Drive
c) Create an empty file in rclone test on local machine = empty file is created in rclone test on GD
d) Add data to empty file on local machine with Geany and save = duplicate file is created in rclone test directory on GD. My original empty file remains and a new one is added with different length.
e) add more data to file with Geany = a third duplicate is created with new length on GD.

Repeat as many times as you like. Each time you get a duplicate on the GD. Duplicates are not shown in the local mount

BUT WAIT, things get worse.

Unmount on local machine = GD is unmounted
Issue same mount command again = GD is mounted
Modify test file = OH NO! The last made changes have been lost. The file is empty! ie put back to its original state when it was first created.

Are there some parameters that I am missing?

Using dedupe does not seem to me to be a solution unless it can be invoked silently on the mount command because when would I run it? I don't really want to start having to make a shut down script to do that. 

Let me know what other information I can provide to help solve this issue.

I have scanned the issues and it does appear that there are a number of similar issues but none relating to mount. It seems this is a long running issue but since I am using the latest beta, I thought it worth reporting.

**Comment by ncw** [comment]
I tried to replicate this issue with geany on Ubuntu 18.10 but I didn't succeed - it all worked perfectly :-(

The latest version of [rclone is 1.44](https://rclone.org/downloads/) - can you try with that?

It is probably a variant of #28 but if you can get it to do it reliably it may not be.

Can you attach a log with `-vv` from the mount please if you can get it to go wrong with 1.44?  If you could start a new mount then work through your steps a)-e) then stop the mount and attache the log that would be perfect.

> Unmount on local machine = GD is unmounted
> Issue same mount command again = GD is mounted
> Modify test file = OH NO! The last made changes have been lost. The file is empty! ie put back to its original state when it was first created

The new file is on google drive almost certainly, just not being shown to you.

**Comment by dreamstorpi** [comment]
Hello Nick, 
I have installed version 1.44 - I cannot replicate the problem.
No duplicate files are created and the data is not lost after unmount.
Thanks for your help.

**Comment by ncw** [comment]
@dreamstorpi that is good news!

I'll close this issue again - we can always re-open it if the problem comes up again.
