### ISSUE TITLE
MD5SUM not working on GDRIVE

### ISSUE THREAD

**Issue by NunoHiggs** [ncw/rclone#2745]
#### Output of `rclone version`

# rclone --version
rclone v1.43.1
- os/arch: linux/amd64
- go version: go1.11

#### Describe the issue

I cannot see or validade any md5sum's on files already on gdrive.
I don't know if this is a bubu on my part but what i get is a lot of UNSUPPORTED:

# rclone md5sum -vv --tpslimit 1 --tpslimit-burst 1 API1SHARE1:
2018/11/18 19:45:16 DEBUG : rclone: Version "v1.43.1" starting with parameters ["rclone" "md5sum" "-vv" "--tpslimit" "1" "--tpslimit-burst" "1" "API1SHARE1:"]
2018/11/18 19:45:16 DEBUG : Using config file from "/root/.rclone.conf"
2018/11/18 19:45:16 INFO  : Starting HTTP transaction limiter: max 1 transactions/s with burst 1
     		     UNSUPPORTED  SHARE03/DIR/File1.mp4
                     UNSUPPORTED  SHARE03/DIR/File2.mp4
                     UNSUPPORTED  SHARE03/DIR/File3.mp4
                     UNSUPPORTED  SHARE03/DIR/File4.mp4
                     UNSUPPORTED  SHARE03/DIR/File5.mp4
                     UNSUPPORTED  SHARE03/DIR/File6.mp4

Am i missing something or is this a legitimate bug?
The same thing happens with the hashum flag and the following parameters:

  * MD5
  * SHA-1
  * QuickXorHash

So either gdrive does not support hashing, or there is a bug.

Thanks,
Nuno

**Comment by ncw** [comment]
Google drive should work with md5sum.

Are you using a drive wrapped with crypt?  Crypt doesn't support md5sums.

**Comment by NunoHiggs** [comment]
Went getto on it, mounted it as a fuse drive and compared it with the md5sum tool. 
Result: I've opened a new bug report. This can be closed.

Thanks for your help.
