### ISSUE TITLE
corrupted on transfer: QuickXorHash hash differ

### ISSUE THREAD

**Issue by ghost** [ncw/rclone#2753]
#### Output of `rclone version`
rclone v1.44-099-g26e2f1a9-beta
- os/arch: linux/386
- go version: go1.11.2

#### Describe the issue
When copying .xlxs files **to** a sharepoint, I get the error:
corrupted on transfer: sizes differ
When adding the --ignore-size arg, I get the error:
corrupted on transfer: QuickXorHash hash differ

**Comment by ncw** [comment]
I think this issue is a duplicate of #2599 which we are working on a solution for.
