### ISSUE TITLE
Error copying files from Google Drive to OneDrive - suggestion

### ISSUE THREAD

**Issue by gabriellluz** [ncw/rclone#2769]
Hi there.

I have problems copying or moving files and folders from Google Drive to OneDrive due to filename restrictions. Some folders inside my Google Drive has names with spaces and non allowed characters. Everyday I get updates on my Google Drive from other people. It's a lof of people sharing files and I just can't tell them to fix the filenames themselves.
What I want rclone to do is:
- fix filenames and folder names before uploading to OneDrive. It should work even for me. I copy from Google to OneDrive.

There should be a flag in rclone such "--fix-filenames-before". It might be useful to other accounts.

The name can not contain any of the following characters:
" Quotation mark
# Number sign
% Percent Sign 
& Ampersand
* Asterisk 
: Colon
< Less than Symbol 
> Greater than Symbol
? Question Mark 
\ Backslash
{ Left Brace 
} Right Brace
| Pipe 
~ Tilde
/ Slash

2. The name cannot begin or end with a period
3. The name cannot contain a double period
4. The name cannot start or end with a space: 
Bad " Game files", Good: "Game files"
Bad "Game files ", Good: "Game files"

**Comment by ncw** [comment]
This is in progress at the moment.  @B4dM4n is doing a big refactor of the file name handling within rclone and this should fix it up :-)

See #2633 for more info.

**Comment by gabriellluz** [comment]
Oh really? Thanks a lot, Sir. I'll close it.
