### ISSUE TITLE
Add support for forced case insensitivity

### ISSUE THREAD

**Issue by simkin** [ncw/rclone#2773]
#### What is your current rclone version (output from `rclone version`)?
1.35

#### What problem are you are trying to solve?
Preventing clone/sync of duplicate files, for which only the casing differs, regardless if the source/target file-systems having cases sensitive filesystems (e.g. most/all linux systems)

e.g. files “Application A.doc” and “application a.doc” are now treated as two different files, I hope to be able to set a flag so they are treated as one and the same.

#### How do you think rclone should be changed to solve that?
Add a flag that can either be combined or superseded with/by "--ignore-existing" so a file will NOT be copied/synced when the existing filename is the same, even if the casing is different 
(e.g. --ignore-existing-case-insensitive)

Forum link: https://forum.rclone.org/t/copy-sync-how-to-ignore-casing-when-checking-for-duplicates/7715

**Comment by ncw** [comment]
Do do this would mean adding a new flag say `--ignore-case-sync` and then using it here

https://github.com/ncw/rclone/blob/50452207d912447197c149cb3aa96ae7c26ef838/fs/march/march.go#L63-L65

Do you want to have a go doing this?

**Comment by simkin** [comment]
I am afraid I lack the technical skills to assess the correctness of the implementation but if you ask me to test your implementation, I am happy to help out. Does this require me compile the binaries from source?

**Comment by ncw** [comment]
> I am afraid I lack the technical skills to assess the correctness of the implementation but if you ask me to test your implementation, I am happy to help out. Does this require me compile the binaries from source?

Usually I make beta releases for people to test so no compiling required.

**Comment by ncw** [comment]
I've merged this to master now which means it will be in [the latest beta](https://beta.rclone.org) in 15-30 mins and released in v1.48 - thank you @garry415 for implementing the feature.
