### ISSUE TITLE
swift: Non segmented upload with vfs-cache off

### ISSUE THREAD

**Issue by 131** [ncw/rclone#2776]
Hi
#### What is your current rclone version (output from `rclone version`)?
=> v1.45
#### What problem are you are trying to solve?
I dont' want to have chunked file on rclone mount vfs-cache-mode off
#### How do you think rclone should be changed to solve that?
Using the fruncate call it receive from the kernel, rclone might guess the upcoming file size

####

I'm copying files on a W10 rclone mount directory (swift backend, vfs-cache-mode **off** ). And i'm having chunked file upload.

I understand that using vfs-cache-mode off makes file size detection harder, hence rclone is falling back quickly to chunk based upload (i could play with à 5Gb cutoff, but playing with memory is not so good)

What i do not understand is that before writing to a file, the OS/kernel seems to truncate the file to the desired size - and rclone trace this information. Could'nt you keep this information for the upload (and detect that here my 28MB file is far from the 5G limit !) ?

2018/11/26 22:28:53 DEBUG : test/SQLiteStudio-3.2.1.zip: >Open: fd=test/SQLiteStudio-3.2.1.zip (w), err=<nil>
2018/11/26 22:28:53 DEBUG : /test/SQLiteStudio-3.2.1.zip: Truncate: size=28808600, fh=0x0
2018/11/26 22:28:53 ERROR : test/SQLiteStudio-3.2.1.zip: WriteFileHandle: Truncate: Can't change size without --vfs-cache-mode >= writes
...
2018/11/26 22:28:54 DEBUG : test/SQLiteStudio-3.2.1.zip: Uploading segment file "test/SQLiteStudio-3.2.1.zip/1543267734.0999914/-1/00000000" into "repository_files_segments"

**Comment by ncw** [comment]
> What i do not understand is that before writing to a file, the OS/kernel seems to truncate the file to the desired size - and rclone trace this information. Could'nt you keep this information for the upload (and detect that here my 28MB file is far from the 5G limit !) ?

Interesting observation.

I suspect it is somewhat dependent on what application you use to do the copying so I'm not sure it would be reliable.

If you don't mind a bit of in-memory buffering then you can increase this

      --streaming-upload-cutoff int   Cutoff for switching to chunked upload if file size is unknown. Upload starts after reaching cutoff or when file ends. (default 100k)

Or on disk buffering with `--vfs-cache-mode writes`

It would be possible to make a new swift flag say `--swift-stream-no-chunks` which would mean that it would use non chunked uploads.  This would limit the streamed upload to 5GB which is pretty large - maybe that should be the default mode.

I agree that chunked files in swift are really annoying...  Perhaps the better flag might be `--swift-disable-chunked-upload` which never does a chunked upload and fails for files bigger than 5GB.

Thoughts?

**Comment by 131** [comment]
Ok, using fruncate informations is tempting, but i understand now that it cannot be relied upon. (I spend hours trying to understand/strace what's kernel32/CopyFile internal behavior, or even find a proper documentation, with no success - here i can just tell that explorer.exe "copy" & "paste" behavior truncate file properly each time i tried.

I've also browse [gnu cp](https://github.com/coreutils/coreutils/blob/master/src/copy.c#L561) source code, but i cannot tell / understand if the fruncate will be called at all.

I do not want to rely on vfs-cache write (i don't like this behavior, i want my CP progress bar to be meaningfull and my user to know the file is beeing uploaded), and again, streaming-upload-cutof is not a solution for GB file size.

So i'll gladly support your new flag idea \o/..
I guess most rclone operation do know the file size properly (and can fallback to chunked file when reaching the 5gb limit). But `rclone rcat` or `rclone mount` cannot. As most cases are working fine, i'll say the `swift-disable-chunked-upload` would be a little excessive (but according to KISS, maybe the path to choose)

Today, copying a 8Gb file on a rclone mount WOULD work, and we cannot break that, so using `swift-stream-no-chunks` with default on would be a regression, so in the end, i'll say `swift-stream-no-chunks` default off would be the best choice.

**Comment by ncw** [comment]
> So i'll gladly support your new flag idea \o/..

Great :-)

> I guess most rclone operation do know the file size properly (and can fallback to chunked file when reaching the 5gb limit). But `rclone rcat` or `rclone mount` cannot. As most cases are working fine, i'll say the `swift-disable-chunked-upload` would be a little excessive (but according to KISS, maybe the path to choose)

Yes they do know the sizes.  This flag will specifically affect rcat and mount which I've called out in the help.


> Today, copying a 8Gb file on a rclone mount WOULD work, and we cannot break that, so using `swift-stream-no-chunks` with default on would be a regression, so in the end, i'll say `swift-stream-no-chunks` default off would be the best choice.

I'm tempted to set it on as I hate segmented files, but you are right - I don't want to break existing work flows.

I implemented `--swift-no-chunk` - can you give it a go and tell me what you think?  You can set it on the command line or in the config:

https://beta.rclone.org/branch/v1.45-006-ga2a36fb2-fix-2776-swift-no-segment-beta/ (uploaded in 15-30 mins)

**Comment by 131** [comment]
tested against `rclone-v1.45-006-ga2a36fb2-fix-2776-swift-no-segment-beta-windows-386`.

* rclone mount  with `--swift-no-chunk` => file are'nt chunked, as expected.
* without the `--swift-no-chunk`, chunks are present, as expected.

Thank you so much for this.

**Comment by ncw** [comment]
Great thanks for testing :-)  I'll merge this now.

It will be in [the latest beta](https://beta.rclone.org) in 15-30 mins and in v1.46.
