### ISSUE TITLE
Add Openstack application credential support

### ISSUE THREAD

**Issue by kayrus** [ncw/rclone#2777]
#### What is your current rclone version (output from `rclone version`)?

1.45

#### What problem are you are trying to solve?

Openstack application credential is not supported: https://docs.openstack.org/keystone/queens/user/application_credentials.html

Here is the [code example](https://github.com/gophercloud/gophercloud/blob/3a7818a07cfc862267a0b03635075a444c92dcda/openstack/auth_env.go#L41..L43) on how it is done in gophercloud

#### How do you think rclone should be changed to solve that?

Handle application credentials. [API reference](https://developer.openstack.org/api-ref/identity/v3/index.html?expanded=authenticating-with-an-application-credential-detail#application-credentials).

**Comment by ncw** [comment]
I think this would need to go into the underlying library https://github.com/ncw/swift first.

Then using the `env_auth` option in rclone would just work.

Would you like to work on this?
