### ISSUE TITLE
Failed to create file system

### ISSUE THREAD

**Issue by Aquarian-Age** [ncw/rclone#2797]
#### What is the problem you are having with rclone?

There is no problem with version 1.40. There is an error when upgrading to 1.45.
After upgrading to version 1.45, I added the yandex network disk and then the following problem
```
2018/11/28 12:29:13 Failed to create file system for "onedrive:": unable to get drive_id and drive_type - if you are upgrading from older versions of rclone, please run `rclone config` and re-configure this backend
```

#### What is your rclone version (output from `rclone version`)
```
 rclone -V
rclone v1.45
- os/arch: linux/amd64
- go version: go1.11.2
```

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

Linux 64bit

####  Which cloud storage system are you using? (eg Google Drive)

onedrive

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

```
rclone -Luv --log-file=/home/xuan/logs/rclone_sync_Documents_to_onedrive.log --delete-excluded --exclude vnote_notebooks/** --exclude /security/topspeedsnail/** --exclude /security/learn-hacking/** --exclude Xblog/lufficc/** --exclude MyLife/_book/** sync /home/xuan/Documents/ onedrive:openSUSE-doc

rclone lsd onedrive:
```

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
```
rclone -vv lsd onedrive:
2018/11/28 12:36:58 DEBUG : rclone: Version "v1.45" starting with parameters ["rclone-1.45" "-vv" "lsd" "onedrive:"]
2018/11/28 12:36:58 DEBUG : Using config file from "/root/.config/rclone/rclone.conf"
2018/11/28 12:36:58 Failed to create file system for "onedrive:": unable to get drive_id and drive_type - if you are upgrading from older versions of rclone, please run `rclone config` and re-configure this backend
```

**Comment by 131** [comment]
The error message state :  `if you are upgrading from older versions of rclone, please run `rclone config` and re-configure this backend`, did you try that ?

**Comment by Cnly** [comment]
@Aquarian-Age You don't need to re-configure all drives; just the OneDrive ones. This is because rclone has migrated to the new API for OneDrive - we had to do this because the old API is being phased out.

**Comment by Aquarian-Age** [comment]
@Cnly OK Thank you very much

**Comment by Aquarian-Age** [comment]
@Cnly 
Use auto config?
 * Say Y if not sure
 * Say N if you are working on a remote or headless machine
y) Yes
n) No
y/n> y
If your browser doesn't open automatically go to the following link: http://127.0.0.1:53682/auth
Log in and authorize rclone for access
Waiting for code...
Got code
Choose a number from below, or type in an existing value
 1 / OneDrive Personal or Business
   \ "onedrive"
 2 / Root Sharepoint site
   \ "sharepoint"
 3 / Type in driveID
   \ "driveid"
 4 / Type in SiteID
   \ "siteid"
 5 / Search a Sharepoint site
   \ "search"
Your choice> ???

Every one has tried it, it’s not right.
