### ISSUE TITLE
Failed to copy: NotImplemented: A header you provided implies functionality that is not implemented

### ISSUE THREAD

**Issue by zen** [ncw/rclone#2798]
#### What is the problem you are having with rclone?

Rclone fails to sync some files
Failed to copy: NotImplemented: A header you provided implies functionality that is not implemented
        status code: 501, request id: 6BAC367485838EA0
Suspected file is SQLITE db backup, gzipped, but it didn't work with just a backup as well. 

#### What is your rclone version (output from `rclone version`)
/usr/bin/rclone version
rclone v1.36

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Linux hass 4.15.0-36-generic #39-Ubuntu SMP Mon Sep 24 16:19:09 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.1 LTS
Release:        18.04
Codename:       bionic

####  Which cloud storage system are you using? (eg Google Drive)
Wasabi S3

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
In the log

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

`rclone --exclude-from $EXCLUDE_FILE --delete-excluded sync $source wasabi_hass:redacted -vv
2018/11/28 17:52:26 DEBUG : rclone: Version "v1.36" starting with parameters ["rclone" "--exclude-from" "/mnt/data/hass/.rcloneignore" "--delete-excluded" "sync" "/mnt/data/hass" "wasabi_hass:redacted" "-vv"]
2018/11/28 17:52:26 INFO  : S3 bucket redacted: Modify window is 1ns
2018/11/28 17:52:27 DEBUG : home-assistant_v2.db: Excluded from sync (and deletion)
2018/11/28 17:52:27 DEBUG : home-assistant.log: Excluded from sync (and deletion)
2018/11/28 17:52:27 DEBUG : automation_weather.yaml: Size and modification time the same (differ by 0s, within tolerance 1ns)
2018/11/28 17:52:27 DEBUG : automation_weather.yaml: Unchanged skipping
2018/11/28 17:52:27 DEBUG : .HA_VERSION: Size and modification time the same (differ by 0s, within tolerance 1ns)
2018/11/28 17:52:27 DEBUG : .HA_VERSION: Unchanged skipping
2018/11/28 17:52:28 DEBUG : .rcloneignore: Size and modification time the same (differ by 0s, within tolerance 1ns)
2018/11/28 17:52:28 DEBUG : .rcloneignore: Unchanged skipping
2018/11/28 17:52:28 DEBUG : groups.yaml: Sizes differ
2018/11/28 17:52:28 DEBUG : .uuid: Size and modification time the same (differ by 0s, within tolerance 1ns)
2018/11/28 17:52:28 DEBUG : .uuid: Unchanged skipping
2018/11/28 17:52:28 DEBUG : alexa_media.pickle: Size and modification time the same (differ by 0s, within tolerance 1ns)
2018/11/28 17:52:28 DEBUG : alexa_media.pickle: Unchanged skipping
2018/11/28 17:52:28 DEBUG : automations.yaml: Size and modification time the same (differ by 0s, within tolerance 1ns)
2018/11/28 17:52:28 DEBUG : automations.yaml: Unchanged skipping
2018/11/28 17:52:28 DEBUG : binary_sensors.yaml: Size and modification time the same (differ by 0s, within tolerance 1ns)
2018/11/28 17:52:28 DEBUG : binary_sensors.yaml: Unchanged skipping
2018/11/28 17:52:28 DEBUG : sensors.yaml: Sizes differ
2018/11/28 17:52:28 DEBUG : automation_zigbee.yaml: Size and modification time the same (differ by 0s, within tolerance 1ns)
2018/11/28 17:52:28 DEBUG : automation_zigbee.yaml: Unchanged skipping
2018/11/28 17:52:28 DEBUG : configuration.yaml: Size and modification time the same (differ by 0s, within tolerance 1ns)
2018/11/28 17:52:28 DEBUG : configuration.yaml: Unchanged skipping
2018/11/28 17:52:28 DEBUG : customize.yaml: Size and modification time the same (differ by 0s, within tolerance 1ns)
2018/11/28 17:52:28 DEBUG : customize.yaml: Unchanged skipping
2018/11/28 17:52:28 DEBUG : lights.yaml: Size and modification time the same (differ by 0s, within tolerance 1ns)
2018/11/28 17:52:28 DEBUG : lights.yaml: Unchanged skipping
2018/11/28 17:52:28 DEBUG : notify.yaml: Size and modification time the same (differ by 0s, within tolerance 1ns)
2018/11/28 17:52:28 DEBUG : notify.yaml: Unchanged skipping
2018/11/28 17:52:28 DEBUG : .scripts/rclone_sync.sh: Sizes differ
2018/11/28 17:52:28 DEBUG : secrets.yaml: Modification times differ by -47h8m51.47061308s: 2018-11-27 23:57:38.812561962 +0100 CET, 2018-11-26 00:48:47.341948882 +0100 CET
2018/11/28 17:52:28 DEBUG : scripts.yaml: Size and modification time the same (differ by 0s, within tolerance 1ns)
2018/11/28 17:52:28 DEBUG : scripts.yaml: Unchanged skipping
2018/11/28 17:52:28 DEBUG : switches.yaml: Size and modification time the same (differ by 0s, within tolerance 1ns)
2018/11/28 17:52:28 DEBUG : switches.yaml: Unchanged skipping
2018/11/28 17:52:28 INFO  : groups.yaml: Copied (replaced existing)
2018/11/28 17:52:28 DEBUG : .cloud/production_auth.json: Size and modification time the same (differ by 0s, within tolerance 1ns)
2018/11/28 17:52:28 DEBUG : .cloud/production_auth.json: Unchanged skipping
2018/11/28 17:52:28 DEBUG : scenes/scenes_lights.yaml: Size and modification time the same (differ by 0s, within tolerance 1ns)
2018/11/28 17:52:28 DEBUG : scenes/scenes_lights.yaml: Unchanged skipping
2018/11/28 17:52:28 DEBUG : automation/automation_notifications.yaml: Size and modification time the same (differ by 0s, within tolerance 1ns)
2018/11/28 17:52:28 DEBUG : automation/automation_notifications.yaml: Unchanged skipping
2018/11/28 17:52:28 DEBUG : automation/automation_lights.yaml: Size and modification time the same (differ by 0s, within tolerance 1ns)
2018/11/28 17:52:28 DEBUG : automation/automation_lights.yaml: Unchanged skipping
2018/11/28 17:52:28 DEBUG : .storage/cloud: Size and modification time the same (differ by 0s, within tolerance 1ns)
2018/11/28 17:52:28 DEBUG : .storage/cloud: Unchanged skipping
2018/11/28 17:52:28 DEBUG : .storage/auth_provider.homeassistant: Size and modification time the same (differ by 0s, within tolerance 1ns)
2018/11/28 17:52:28 DEBUG : .storage/auth_provider.homeassistant: Unchanged skipping
2018/11/28 17:52:28 DEBUG : .storage/auth: Modification times differ by -1h27m3.000009679s: 2018-11-28 17:20:31.004280566 +0100 CET, 2018-11-28 15:53:28.004270887 +0100 CET
2018/11/28 17:52:28 DEBUG : .storage/core.config_entries: Size and modification time the same (differ by 0s, within tolerance 1ns)
2018/11/28 17:52:28 DEBUG : .storage/core.config_entries: Unchanged skipping
2018/11/28 17:52:28 DEBUG : .storage/auth: MD5 = c2cfe42293689834f538f5ef4c2b01fa (Local file system at /mnt/data/hass)
2018/11/28 17:52:28 DEBUG : .storage/auth: MD5 = 04df944c98874e26b02abdc058f4c39f (S3 bucket redacted)
2018/11/28 17:52:28 DEBUG : .storage/auth: MD5 differ
2018/11/28 17:52:28 INFO  : .scripts/rclone_sync.sh: Copied (replaced existing)
2018/11/28 17:52:28 DEBUG : .storage/core.entity_registry: Size and modification time the same (differ by 0s, within tolerance 1ns)
2018/11/28 17:52:28 DEBUG : .storage/core.entity_registry: Unchanged skipping
2018/11/28 17:52:28 INFO  : sensors.yaml: Copied (replaced existing)
2018/11/28 17:52:28 DEBUG : .storage/onboarding: Size and modification time the same (differ by 0s, within tolerance 1ns)
2018/11/28 17:52:28 DEBUG : .storage/onboarding: Unchanged skipping
2018/11/28 17:52:28 DEBUG : custom_components/media_player/alexa.py: Size and modification time the same (differ by 0s, within tolerance 1ns)
2018/11/28 17:52:28 DEBUG : custom_components/media_player/alexa.py: Unchanged skipping
2018/11/28 17:52:28 DEBUG : custom_components/notify/smsapi.py: Size and modification time the same (differ by 0s, within tolerance 1ns)
2018/11/28 17:52:28 DEBUG : custom_components/notify/smsapi.py: Unchanged skipping
2018/11/28 17:52:28 DEBUG : custom_components/media_player/__pycache__/alexa.cpython-36.pyc: Size and modification time the same (differ by 0s, within tolerance 1ns)
2018/11/28 17:52:28 DEBUG : custom_components/media_player/__pycache__/alexa.cpython-36.pyc: Unchanged skipping
2018/11/28 17:52:28 DEBUG : custom_components/notify/__pycache__/smsapi.cpython-36.pyc: Size and modification time the same (differ by 0s, within tolerance 1ns)
2018/11/28 17:52:28 DEBUG : custom_components/notify/__pycache__/smsapi.cpython-36.pyc: Unchanged skipping
2018/11/28 17:52:28 INFO  : .storage/auth: Copied (replaced existing)
2018/11/28 17:52:29 INFO  : S3 bucket redacted: Waiting for checks to finish
2018/11/28 17:53:09 ERROR : db_backup.sq3.gz: Failed to copy: NotImplemented: A header you provided implies functionality that is not implemented
        status code: 501, request id: 15F72FAB3F0FCAFA
2018/11/28 17:53:19 ERROR : secrets.yaml: Failed to set modification time: NotImplemented: A header you provided implies functionality that is not implemented
        status code: 501, request id: 61B20A517FE50DA7
2018/11/28 17:53:19 DEBUG : secrets.yaml: Unchanged skipping
2018/11/28 17:53:19 INFO  : S3 bucket redacted: Waiting for transfers to finish
2018/11/28 17:53:19 ERROR : S3 bucket redacted: not deleting files as there were IO errors
2018/11/28 17:53:19 ERROR : Attempt 1/3 failed with 2 errors and: NotImplemented: A header you provided implies functionality that is not implemented
        status code: 501, request id: 15F72FAB3F0FCAFA
2018/11/28 17:53:19 DEBUG : home-assistant_v2.db: Excluded from sync (and deletion)
2018/11/28 17:53:19 DEBUG : home-assistant.log: Excluded from sync (and deletion)
2018/11/28 17:53:19 DEBUG : .HA_VERSION: Size and modification time the same (differ by 0s, within tolerance 1ns)
2018/11/28 17:53:19 DEBUG : .HA_VERSION: Unchanged skipping
2018/11/28 17:53:19 DEBUG : .uuid: Size and modification time the same (differ by 0s, within tolerance 1ns)
2018/11/28 17:53:19 DEBUG : .uuid: Unchanged skipping
2018/11/28 17:53:19 DEBUG : automation_weather.yaml: Size and modification time the same (differ by 0s, within tolerance 1ns)
2018/11/28 17:53:19 DEBUG : automation_weather.yaml: Unchanged skipping
2018/11/28 17:53:19 DEBUG : binary_sensors.yaml: Size and modification time the same (differ by 0s, within tolerance 1ns)
2018/11/28 17:53:19 DEBUG : binary_sensors.yaml: Unchanged skipping
2018/11/28 17:53:19 DEBUG : automation_zigbee.yaml: Size and modification time the same (differ by 0s, within tolerance 1ns)
2018/11/28 17:53:19 DEBUG : automation_zigbee.yaml: Unchanged skipping
2018/11/28 17:53:19 DEBUG : automations.yaml: Size and modification time the same (differ by 0s, within tolerance 1ns)
2018/11/28 17:53:19 DEBUG : automations.yaml: Unchanged skipping
2018/11/28 17:53:19 DEBUG : .rcloneignore: Size and modification time the same (differ by 0s, within tolerance 1ns)
2018/11/28 17:53:19 DEBUG : .rcloneignore: Unchanged skipping
2018/11/28 17:53:19 DEBUG : alexa_media.pickle: Size and modification time the same (differ by 0s, within tolerance 1ns)
2018/11/28 17:53:19 DEBUG : alexa_media.pickle: Unchanged skipping
2018/11/28 17:53:19 DEBUG : configuration.yaml: Size and modification time the same (differ by 0s, within tolerance 1ns)
2018/11/28 17:53:19 DEBUG : configuration.yaml: Unchanged skipping
2018/11/28 17:53:19 DEBUG : customize.yaml: Size and modification time the same (differ by 0s, within tolerance 1ns)
2018/11/28 17:53:19 DEBUG : customize.yaml: Unchanged skipping
2018/11/28 17:53:19 DEBUG : groups.yaml: Size and modification time the same (differ by 0s, within tolerance 1ns)
2018/11/28 17:53:19 DEBUG : groups.yaml: Unchanged skipping
2018/11/28 17:53:19 DEBUG : lights.yaml: Size and modification time the same (differ by 0s, within tolerance 1ns)
2018/11/28 17:53:19 DEBUG : lights.yaml: Unchanged skipping
2018/11/28 17:53:19 DEBUG : notify.yaml: Size and modification time the same (differ by 0s, within tolerance 1ns)
2018/11/28 17:53:19 DEBUG : notify.yaml: Unchanged skipping
2018/11/28 17:53:19 DEBUG : scripts.yaml: Size and modification time the same (differ by 0s, within tolerance 1ns)
2018/11/28 17:53:19 DEBUG : scripts.yaml: Unchanged skipping
2018/11/28 17:53:19 DEBUG : secrets.yaml: Modification times differ by -47h8m51.47061308s: 2018-11-27 23:57:38.812561962 +0100 CET, 2018-11-26 00:48:47.341948882 +0100 CET
2018/11/28 17:53:19 DEBUG : sensors.yaml: Size and modification time the same (differ by 0s, within tolerance 1ns)
2018/11/28 17:53:19 DEBUG : sensors.yaml: Unchanged skipping
2018/11/28 17:53:20 DEBUG : switches.yaml: Size and modification time the same (differ by 0s, within tolerance 1ns)
2018/11/28 17:53:20 DEBUG : switches.yaml: Unchanged skipping
2018/11/28 17:53:20 DEBUG : .cloud/production_auth.json: Size and modification time the same (differ by 0s, within tolerance 1ns)
2018/11/28 17:53:20 DEBUG : .cloud/production_auth.json: Unchanged skipping
2018/11/28 17:53:20 DEBUG : .scripts/rclone_sync.sh: Size and modification time the same (differ by 0s, within tolerance 1ns)
2018/11/28 17:53:20 DEBUG : .scripts/rclone_sync.sh: Unchanged skipping
2018/11/28 17:53:20 DEBUG : .storage/auth_provider.homeassistant: Size and modification time the same (differ by 0s, within tolerance 1ns)
2018/11/28 17:53:20 DEBUG : .storage/auth_provider.homeassistant: Unchanged skipping
2018/11/28 17:53:20 DEBUG : .storage/auth: Size and modification time the same (differ by 0s, within tolerance 1ns)
2018/11/28 17:53:20 DEBUG : .storage/auth: Unchanged skipping
2018/11/28 17:53:20 DEBUG : .storage/core.config_entries: Size and modification time the same (differ by 0s, within tolerance 1ns)
2018/11/28 17:53:20 DEBUG : .storage/core.config_entries: Unchanged skipping
2018/11/28 17:53:20 DEBUG : .storage/cloud: Size and modification time the same (differ by 0s, within tolerance 1ns)
2018/11/28 17:53:20 DEBUG : .storage/cloud: Unchanged skipping
2018/11/28 17:53:20 DEBUG : .storage/core.entity_registry: Size and modification time the same (differ by 0s, within tolerance 1ns)
2018/11/28 17:53:20 DEBUG : .storage/core.entity_registry: Unchanged skipping
2018/11/28 17:53:20 DEBUG : .storage/onboarding: Size and modification time the same (differ by 0s, within tolerance 1ns)
2018/11/28 17:53:20 DEBUG : .storage/onboarding: Unchanged skipping
2018/11/28 17:53:20 DEBUG : automation/automation_lights.yaml: Size and modification time the same (differ by 0s, within tolerance 1ns)
2018/11/28 17:53:20 DEBUG : automation/automation_lights.yaml: Unchanged skipping
2018/11/28 17:53:20 DEBUG : automation/automation_notifications.yaml: Size and modification time the same (differ by 0s, within tolerance 1ns)
2018/11/28 17:53:20 DEBUG : automation/automation_notifications.yaml: Unchanged skipping
2018/11/28 17:53:20 DEBUG : scenes/scenes_lights.yaml: Size and modification time the same (differ by 0s, within tolerance 1ns)
2018/11/28 17:53:20 DEBUG : scenes/scenes_lights.yaml: Unchanged skipping
2018/11/28 17:53:20 DEBUG : custom_components/media_player/alexa.py: Size and modification time the same (differ by 0s, within tolerance 1ns)
2018/11/28 17:53:20 DEBUG : custom_components/media_player/alexa.py: Unchanged skipping
2018/11/28 17:53:20 DEBUG : custom_components/notify/smsapi.py: Size and modification time the same (differ by 0s, within tolerance 1ns)
2018/11/28 17:53:20 DEBUG : custom_components/notify/smsapi.py: Unchanged skipping
2018/11/28 17:53:20 DEBUG : custom_components/media_player/__pycache__/alexa.cpython-36.pyc: Size and modification time the same (differ by 0s, within tolerance 1ns)
2018/11/28 17:53:20 DEBUG : custom_components/media_player/__pycache__/alexa.cpython-36.pyc: Unchanged skipping
2018/11/28 17:53:20 DEBUG : custom_components/notify/__pycache__/smsapi.cpython-36.pyc: Size and modification time the same (differ by 0s, within tolerance 1ns)
2018/11/28 17:53:20 DEBUG : custom_components/notify/__pycache__/smsapi.cpython-36.pyc: Unchanged skipping
2018/11/28 17:53:21 INFO  : S3 bucket redacted: Waiting for checks to finish
2018/11/28 17:53:26 INFO  :
Transferred:   10.012 MBytes (170.837 kBytes/s)
Errors:                 0
Checks:                63
Transferred:            4
Elapsed time:        1m0s
Checking:
 * secrets.yaml
Transferring:
 *                              db_backup.sq3.gz:  7% done, 3.319 MBytes/s, ETA: 18s

2018/11/28 17:54:04 ERROR : db_backup.sq3.gz: Failed to copy: NotImplemented: A header you provided implies functionality that is not implemented
        status code: 501, request id: 6BAC367485838EA0
2018/11/28 17:54:08 ERROR : secrets.yaml: Failed to set modification time: NotImplemented: A header you provided implies functionality that is not implemented
        status code: 501, request id: 781BBDEF8CAB33C9
2018/11/28 17:54:08 DEBUG : secrets.yaml: Unchanged skipping
2018/11/28 17:54:08 INFO  : S3 bucket redacted: Waiting for transfers to finish
2018/11/28 17:54:08 ERROR : S3 bucket redacted: not deleting files as there were IO errors
2018/11/28 17:54:08 ERROR : Attempt 2/3 failed with 2 errors and: NotImplemented: A header you provided implies functionality that is not implemented
        status code: 501, request id: 6BAC367485838EA0
2018/11/28 17:54:08 DEBUG : home-assistant_v2.db: Excluded from sync (and deletion)
2018/11/28 17:54:08 DEBUG : home-assistant.log: Excluded from sync (and deletion)
2018/11/28 17:54:08 DEBUG : .HA_VERSION: Size and modification time the same (differ by 0s, within tolerance 1ns)
2018/11/28 17:54:08 DEBUG : .HA_VERSION: Unchanged skipping
2018/11/28 17:54:08 DEBUG : automation_weather.yaml: Size and modification time the same (differ by 0s, within tolerance 1ns)
2018/11/28 17:54:08 DEBUG : automation_weather.yaml: Unchanged skipping
2018/11/28 17:54:08 DEBUG : .rcloneignore: Size and modification time the same (differ by 0s, within tolerance 1ns)
2018/11/28 17:54:08 DEBUG : .rcloneignore: Unchanged skipping
2018/11/28 17:54:08 DEBUG : .uuid: Size and modification time the same (differ by 0s, within tolerance 1ns)
2018/11/28 17:54:08 DEBUG : .uuid: Unchanged skipping
2018/11/28 17:54:08 DEBUG : binary_sensors.yaml: Size and modification time the same (differ by 0s, within tolerance 1ns)
2018/11/28 17:54:08 DEBUG : binary_sensors.yaml: Unchanged skipping
2018/11/28 17:54:08 DEBUG : alexa_media.pickle: Size and modification time the same (differ by 0s, within tolerance 1ns)
2018/11/28 17:54:08 DEBUG : alexa_media.pickle: Unchanged skipping
2018/11/28 17:54:08 DEBUG : automations.yaml: Size and modification time the same (differ by 0s, within tolerance 1ns)
2018/11/28 17:54:08 DEBUG : automations.yaml: Unchanged skipping
2018/11/28 17:54:08 DEBUG : automation_zigbee.yaml: Size and modification time the same (differ by 0s, within tolerance 1ns)
2018/11/28 17:54:08 DEBUG : automation_zigbee.yaml: Unchanged skipping
2018/11/28 17:54:08 DEBUG : configuration.yaml: Size and modification time the same (differ by 0s, within tolerance 1ns)
2018/11/28 17:54:08 DEBUG : configuration.yaml: Unchanged skipping
2018/11/28 17:54:08 DEBUG : customize.yaml: Size and modification time the same (differ by 0s, within tolerance 1ns)
2018/11/28 17:54:08 DEBUG : customize.yaml: Unchanged skipping
2018/11/28 17:54:08 DEBUG : groups.yaml: Size and modification time the same (differ by 0s, within tolerance 1ns)
2018/11/28 17:54:08 DEBUG : groups.yaml: Unchanged skipping
2018/11/28 17:54:08 DEBUG : notify.yaml: Size and modification time the same (differ by 0s, within tolerance 1ns)
2018/11/28 17:54:08 DEBUG : notify.yaml: Unchanged skipping
2018/11/28 17:54:08 DEBUG : lights.yaml: Size and modification time the same (differ by 0s, within tolerance 1ns)
2018/11/28 17:54:08 DEBUG : lights.yaml: Unchanged skipping
2018/11/28 17:54:08 DEBUG : scripts.yaml: Size and modification time the same (differ by 0s, within tolerance 1ns)
2018/11/28 17:54:08 DEBUG : scripts.yaml: Unchanged skipping
2018/11/28 17:54:08 DEBUG : secrets.yaml: Modification times differ by -47h8m51.47061308s: 2018-11-27 23:57:38.812561962 +0100 CET, 2018-11-26 00:48:47.341948882 +0100 CET
2018/11/28 17:54:08 DEBUG : sensors.yaml: Size and modification time the same (differ by 0s, within tolerance 1ns)
2018/11/28 17:54:08 DEBUG : sensors.yaml: Unchanged skipping
2018/11/28 17:54:08 DEBUG : switches.yaml: Size and modification time the same (differ by 0s, within tolerance 1ns)
2018/11/28 17:54:08 DEBUG : switches.yaml: Unchanged skipping
2018/11/28 17:54:08 DEBUG : .storage/auth: Size and modification time the same (differ by 0s, within tolerance 1ns)
2018/11/28 17:54:08 DEBUG : .storage/auth: Unchanged skipping
2018/11/28 17:54:08 DEBUG : .storage/core.entity_registry: Size and modification time the same (differ by 0s, within tolerance 1ns)
2018/11/28 17:54:08 DEBUG : .storage/core.entity_registry: Unchanged skipping
2018/11/28 17:54:08 DEBUG : .storage/cloud: Size and modification time the same (differ by 0s, within tolerance 1ns)
2018/11/28 17:54:08 DEBUG : .storage/cloud: Unchanged skipping
2018/11/28 17:54:08 DEBUG : .storage/core.config_entries: Size and modification time the same (differ by 0s, within tolerance 1ns)
2018/11/28 17:54:08 DEBUG : .storage/core.config_entries: Unchanged skipping
2018/11/28 17:54:08 DEBUG : .storage/auth_provider.homeassistant: Size and modification time the same (differ by 0s, within tolerance 1ns)
2018/11/28 17:54:08 DEBUG : .storage/auth_provider.homeassistant: Unchanged skipping
2018/11/28 17:54:08 DEBUG : .storage/onboarding: Size and modification time the same (differ by 0s, within tolerance 1ns)
2018/11/28 17:54:08 DEBUG : .storage/onboarding: Unchanged skipping
2018/11/28 17:54:08 DEBUG : .cloud/production_auth.json: Size and modification time the same (differ by 0s, within tolerance 1ns)
2018/11/28 17:54:08 DEBUG : .cloud/production_auth.json: Unchanged skipping
2018/11/28 17:54:08 DEBUG : scenes/scenes_lights.yaml: Size and modification time the same (differ by 0s, within tolerance 1ns)
2018/11/28 17:54:08 DEBUG : scenes/scenes_lights.yaml: Unchanged skipping
2018/11/28 17:54:08 DEBUG : .scripts/rclone_sync.sh: Size and modification time the same (differ by 0s, within tolerance 1ns)
2018/11/28 17:54:08 DEBUG : .scripts/rclone_sync.sh: Unchanged skipping
2018/11/28 17:54:08 DEBUG : automation/automation_lights.yaml: Size and modification time the same (differ by 0s, within tolerance 1ns)
2018/11/28 17:54:08 DEBUG : automation/automation_lights.yaml: Unchanged skipping
2018/11/28 17:54:08 DEBUG : automation/automation_notifications.yaml: Size and modification time the same (differ by 0s, within tolerance 1ns)
2018/11/28 17:54:08 DEBUG : automation/automation_notifications.yaml: Unchanged skipping
2018/11/28 17:54:08 DEBUG : custom_components/notify/smsapi.py: Size and modification time the same (differ by 0s, within tolerance 1ns)
2018/11/28 17:54:08 DEBUG : custom_components/notify/smsapi.py: Unchanged skipping
2018/11/28 17:54:08 DEBUG : custom_components/media_player/alexa.py: Size and modification time the same (differ by 0s, within tolerance 1ns)
2018/11/28 17:54:08 DEBUG : custom_components/media_player/alexa.py: Unchanged skipping
2018/11/28 17:54:09 DEBUG : custom_components/media_player/__pycache__/alexa.cpython-36.pyc: Size and modification time the same (differ by 0s, within tolerance 1ns)
2018/11/28 17:54:09 DEBUG : custom_components/media_player/__pycache__/alexa.cpython-36.pyc: Unchanged skipping
2018/11/28 17:54:09 DEBUG : custom_components/notify/__pycache__/smsapi.cpython-36.pyc: Size and modification time the same (differ by 0s, within tolerance 1ns)
2018/11/28 17:54:09 DEBUG : custom_components/notify/__pycache__/smsapi.cpython-36.pyc: Unchanged skipping
2018/11/28 17:54:09 INFO  : S3 bucket redacted: Waiting for checks to finish
2018/11/28 17:54:26 INFO  :
Transferred:   15.012 MBytes (128.090 kBytes/s)
Errors:                 0
Checks:                95
Transferred:            4
Elapsed time:        2m0s
Checking:
 * secrets.yaml
Transferring:
 *                              db_backup.sq3.gz:  7% done, 1.584 MBytes/s, ETA: 37s

2018/11/28 17:54:48 ERROR : secrets.yaml: Failed to set modification time: NotImplemented: A header you provided implies functionality that is not implemented
        status code: 501, request id: 904FC5EC14D600A1
2018/11/28 17:54:48 DEBUG : secrets.yaml: Unchanged skipping
2018/11/28 17:54:48 INFO  : S3 bucket redacted: Waiting for transfers to finish
2018/11/28 17:54:48 ERROR : db_backup.sq3.gz: Failed to copy: NotImplemented: A header you provided implies functionality that is not implemented
        status code: 501, request id: 2DE1A62FB2CE97B5
2018/11/28 17:54:48 ERROR : S3 bucket redacted: not deleting files as there were IO errors
2018/11/28 17:54:48 ERROR : Attempt 3/3 failed with 2 errors and: NotImplemented: A header you provided implies functionality that is not implemented
        status code: 501, request id: 2DE1A62FB2CE97B5
2018/11/28 17:54:48 Failed to sync: NotImplemented: A header you provided implies functionality that is not implemented
        status code: 501, request id: 2DE1A62FB2CE97B5`

**Comment by ncw** [comment]
> 2018/11/28 17:53:09 ERROR : db_backup.sq3.gz: Failed to copy: NotImplemented: A header you provided implies functionality that is not implemented
> status code: 501, request id: 15F72FAB3F0FCAFA
> 2018/11/28 17:53:19 ERROR : secrets.yaml: Failed to set modification time: NotImplemented: A header you provided implies functionality that is not implemented

Hmm, not sure what is going on here.

I don't currently have a Wasabi account alas.

Can you try the most recent version of rclone  [the latest release](https://rclone.org/downloads/)

Can you also try your sync with `-vv --dump responses --retries 1` and attach that log, or at least the failing REQUEST and RESPONSE.

**Comment by ncw** [comment]
> Interesting. I installed most recent version 1.4 and everything is working correctly. Thanks!

Glad it is working for you now :-)
