### ISSUE TITLE
Slow list / download for Azure Blob Storage

### ISSUE THREAD

**Issue by sheerun** [ncw/rclone#2799]
#### What is the problem you are having with rclone?

I have container on Azure Blob Storage with 30M files. Listing these files (and downloading them) is slow and limited to around 100/second. With simple ruby script I'm able to reach 1000/second for listing. It also affects download speed which is capped to around 100/second.

```ruby
require 'azure/storage/blob'

client = Azure::Storage::Blob::BlobService.create(storage_account_name: 'yyy', storage_access_key: 'xxxx')

marker = nil
while true
  blobs = client.list_blobs('rails', max_results: 5000, marker: marker)
  marker = blobs.continuation_token
  puts blobs.map { |b| b.name }.join("\n")
  break if marker.nil? || marker.empty?
end
```

#### What is your rclone version (output from `rclone version`)

```
rclone v1.45-006-geb412537-beta
- os/arch: linux/amd64
- go version: go1.11.2
```

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

Ubuntu 18.04.1 LTS

####  Which cloud storage system are you using? (eg Google Drive)

Azure Blob Storage

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

rclone lsf --files-only --recursive azure://rails

or 

rclone copy azure://rails /mnt/data/rails --transfers 100 --checkers 100

I tried different combinations of flags to speed it up but no results

**Comment by sheerun** [comment]
Not to mention rclone uses thousands of transactions (practically one per file?) while ruby script is using few according to metrics dashboard (one per page).

**Comment by ncw** [comment]
Consider using `--checksum` or `--size-only` so rclone doesn't have to read the modification time from the metadata - this will reduce the number of transactions greatly.

How are the files arranged - are they in directories or are they all in one directory?

You could also use `--fast-list` but that will use **a lot** of memory perhaps 1k per object.

> Listing these files (and downloading them) is slow and limited to around 100/second.

Yes the azure blob backend has a minimum time between transactions of 10ms hence the 100/second.

This is probably a mistake.  We implemented a pacer for s3 recently which in the happy case of things working properly doesn't delay.  This should probably be applied to all the enterprise class backends eg azure/googlecloudstorage/swift

This isn't user twiddleable at the moment alas.

You could try adjusting this to see what happens...

https://github.com/ncw/rclone/blob/50452207d912447197c149cb3aa96ae7c26ef838/backend/azureblob/azureblob.go#L38

**Comment by ncw** [comment]
@sandeepkru what do you think about reducing the minimum sleep between requests to 0?

**Comment by sheerun** [comment]
In this bucket we have two kinds of directories, but I don't think it matters as files are copied the same speed for both of them: 1. directory with millions of directories inside, each of millions directories has around 5 files. 2. directory with millions of html files inside, flat structure

I tried all available flags that can potentially speed this up but they don't work (including `--size-only`, `--checksum`). Besides `lsf` is slow as well and it doesn't have these.

> Yes the azure blob backend has a minimum time between transactions of 10ms hence the 100/second.

Why would you need 100 transactions to read 100 files? My ruby code reads 5000 files in one transaction. For `lsf` I don't need anything except filenames and for copying I enable all flags that require any metadata to be present so they just can use filenames.

**Comment by sheerun** [comment]
(of course when it comes to copying it would be nice to have ability to go beyond 100/s but for file listing it's a must have) :)

**Comment by ncw** [comment]
> I tried all available flags that can potentially speed this up but they don't work (including `--size-only`, `--checksum`). Besides `lsf` is slow as well and it doesn't have these.

I was wrong about needing an extra transaction to read the modification time - it is supplied in the directory listings so that explains your result.

> Why would you need 100 transactions to read 100 files? My ruby code reads 5000 files in one transaction. For `lsf` I don't need anything except filenames and for copying I enable all flags that disable needing any metadata to be present, so rclone can use "List Blobs" instead of checking each file individually.

rclone will be reading directories in chunks of 5000 too.  It will buffer them in memory until it has read the whole directory before acting on it though.

So the answer is it shouldn't do...

Here is a beta for you to try.  I changed over to using the s3 pacer so it now doesn't sleep at all betwen requests.  I also enabled `-vv --dump requests` - you can use this to see how many HTTP requests rclone is really making.

https://beta.rclone.org/branch/v1.45-011-gba8aa73a-fix-2654-azureblob-client-beta/ (uploaded in 15-30 mins)

Note that if you want to speed up lsf, you can use `--checkers` with it too.

**Comment by sheerun** [comment]
Thank you I'll try this after I'll deal with the upload of 30M of files I've downloaded from Azure (it took 4 days) to DigitalOcean. The upload speed seems even worse at 30/second and 5Mb/s which means it'll take next 10 days for me to upload everything.. Do you think it can be similar story?

**Comment by sheerun** [comment]
btw. the command I use for uploading is: `rclone copy /mnt/data/ada/rails s3://ada/rails --transfers=12 --checkers=1 --syslog --pr
ogress --ignore-existing --size-only`. I cannot increase transfers concurrency because upload speed slows down (maybe I'm being throttled), number of checkes doesn't matter. bwlimit and tpslimit don't matter as well.

**Comment by ncw** [comment]
> Thank you I'll try this after I'll deal with the upload of 30M of files I've downloaded from Azure (it took 4 days) to DigitalOcean. The upload speed seems even worse at 30/second and 5Mb/s which means it'll take next 12 days for me to upload everything.. Do you think it can be similar story?

Great

> The upload speed seems even worse at 30/second and 5Mb/s which means it'll take next 12 days for me to upload everything.. Do you think it can be similar story?

The s3 pacer is already unrestricted if you are using rclone 1.44 or the beta.

I suspect it is rate limiting somewhere, maybe DO or your ISP.

> btw. the command I use for uploading is: `rclone copy /mnt/data/foobar/rails s3://foobar/rails --transfers=12 --checkers=1 --syslog --progress --ignore-existing --size-only`. I cannot increase transfers concurrency because upload speed slows down (maybe I'm being throttled), number of checkers doesn't matter. bwlimit and tpslimit don't matter as well.

How big are the files you are uploading?  It might be that the `--s3-upload-cutoff` flag is what you want which I'm just about to merge.

**Comment by sheerun** [comment]
The files are very small from 50kb to max 500kb

**Comment by ncw** [comment]
I've merged the fix to the azure pacer and it will be in [the latest beta](https://beta.rclone.org) in 15-30 mins and in v1.46

If you try [the latest beta](https://beta.rclone.org) you should find the s3 backend is faster too.

**Comment by sheerun** [comment]
Great work @ncw, thank you :)
