### ISSUE TITLE
--exclude-from (in combination with --include-from) doesn't seem to work in my case

### ISSUE THREAD

**Issue by vesper8** [ncw/rclone#280]
Hi there,

I'm trying to sync my SOME applications folder on my mac with dropbox. I've manage to make it work using an include-from filter. But then I keep getting a lot of noise about thumbs.db and .ds_store files and I'm trying to quiet that down. The -q flag doesn't seem to be doing anything about that, and using the exclude-from as posted below is also not causing those warnings/errors to go away.

```
~/rclone/rclone sync -q --include-from include-applications.txt --exclude-from exclude-applications.txt /Applications remote:#MAC/BACKUP/Applications
```

here's my include-applications.txt (usually contains way more than one app but now only has one for testing)
```
4K Video Downloader.app/**
```

and here's my exclude-applications.txt

```
Thumbs.db
.DS_Store
```

and here's the console output
```
~/rclone  ./syncDropboxApplications.sh
~/rclone/rclone sync -q --include-from include-applications.txt --exclude-from exclude-applications.txt /Applications remote:#MAC/BACKUP/Applications
2016/01/06 17:06:21 4K Video Downloader.app/Contents/Frameworks/QtGui.framework/Versions/.DS_Store: File name disallowed - not uploading
2016/01/06 17:06:21 4K Video Downloader.app/Contents/Frameworks/QtGui.framework/Versions/.DS_Store: Corrupted on transfer: sizes differ 6148 vs 0
2016/01/06 17:06:21 4K Video Downloader.app/Contents/Frameworks/QtGui.framework/Versions/5/.DS_Store: File name disallowed - not uploading
2016/01/06 17:06:21 4K Video Downloader.app/Contents/Frameworks/QtGui.framework/Versions/5/.DS_Store: Corrupted on transfer: sizes differ 6148 vs 0
2016/01/06 17:06:21 4K Video Downloader.app/Contents/Frameworks/QtGui.framework/.DS_Store: File name disallowed - not uploading
2016/01/06 17:06:21 4K Video Downloader.app/Contents/Frameworks/QtGui.framework/.DS_Store: Corrupted on transfer: sizes differ 6148 vs 0
2016/01/06 17:06:21 4K Video Downloader.app/Contents/Frameworks/QtNetwork.framework/.DS_Store: File name disallowed - not uploading
2016/01/06 17:06:21 4K Video Downloader.app/Contents/Frameworks/QtNetwork.framework/.DS_Store: Corrupted on transfer: sizes differ 6148 vs 0
2016/01/06 17:06:22 4K Video Downloader.app/Contents/Frameworks/QtNetwork.framework/Versions/.DS_Store: File name disallowed - not uploading
2016/01/06 17:06:22 4K Video Downloader.app/Contents/Frameworks/QtNetwork.framework/Versions/.DS_Store: Corrupted on transfer: sizes differ 6148 vs 0
2016/01/06 17:06:26
Transferred:            0 Bytes (   0.00 kByte/s)
Errors:                 5
Checks:                76
Transferred:            5
Elapsed time:      1m1.4s

2016/01/06 17:10:37 Dropbox root '#MAC/BACKUP/Applications': Not deleting files as there were IO errors

Transferred:            0 Bytes (   0.00 kByte/s)
Errors:                 5
Checks:               228
Transferred:           15
Elapsed time:     5m12.1s
```

**Comment by ncw** [comment]
Noise about thumbs.db and .ds_store files not quitenened by `-q` is a bug which should be easy to fix.

Using `--include-from` and `--exclude-from` together is problematic, because the `--include-from` adds an implicit `--exclude *` at the end of the filter list.

It does say that in [the docs](http://rclone.org/filtering/), but perhaps it isn't clear enough that using `--include*` and `--exclude*` together won't work.

There is a solution though, use the `--filter-from` flag.

In an ideal world you'd be able to use `--include x --exclude y --include z` on the command line, but rclone's command line parser isn't clever enough to deal with duplicated entries, so I went for the implicit `--exclude *` entry.  I guess I could make that sink to the end of the filter list, so when you did `---include x --exclude y` the `--exclude *` would be moved to the end of the list.

**Comment by vesper8** [comment]
Thanks for the clarifications.

So are you suggesting that instead of using a combination of --include-from and --exclude-from, I get rid of both of those and use a single --filter-from instead?

Because I just tried using a combination of --include-from and --filter-from and got the same results as before.

Command:
```
~/rclone/rclone sync --include-from include-applications.txt --filter-from filter-applications.txt /Applications remote:#MAC/BACKUP/Applications
```

Here's the content of my filter-applications.txt
```
- Thumbs.db
- .DS_Store
```

So to achieve what I'm trying to achieve I should only use a single --filter-from and it should look like this?

```
+ Some Application.app/**
+ Another Aplication.app/**
- Thumbs.db
- .DS_Store
```

?

**Comment by ncw** [comment]
Yes one `--filter-from` file is your only option at the moment.

**Comment by vesper8** [comment]
Cool, trying this out now.

I'm trying to do a dry run with verbosity mode on and I'm wishing there was a way to have the verbose mode only show what it is including for sync and not show everything that it's excluding as well. I know I saw another issue relating to having different levels of verbosity.. maybe you could include that as an option.

Thanks for the quick support!

**Comment by vesper8** [comment]
Hey again,

I still can't get it to work properly. It's still making noise about the .DS_Store files

Here's my command:
```
~/rclone/rclone sync --filter-from filter-applications.txt /Applications remote:#MAC/BACKUP/Applications
```

And the content of my filter-applications.txt
```
+ 4K Video Downloader.app/**
- Thumbs.db
- .DS_Store
# exclude everything else
- *%
```

Is the line that tries to exclude .DS_Store wrong?

**Comment by vesper8** [comment]
ah nevermind seems like I solved it.. I remember you writing something about the order being important. Moved the exclusions at the top and now it seems to be working :)

**Comment by ncw** [comment]
I made a new issue #287 with the `-q` observation.

I'm going to leave this open to remind me to add a bit to the docs about not using include and exclude together.

Thanks

Nick

**Comment by ncw** [comment]
I've made a small tweak to the include filters so it adds the exclude rule right at the end of the filter list (after everything else).  This means that your original usage would work now.  I've also added some more  stuff to the docs about it.

**Comment by faxotherapy** [comment]
It seems to be a recurring theme. Mixing file/folder exclusion with file/folder inclusion is problematic. I spent half a day trying to figure out how to exclude a folder browsing the web, reading the doc and going to the forum. No success.

Maximum frutstration. We find a nice tool such as *rclone* to solve what we want to do, but we must take an entire day to master it. So many options, choosing the best parameter combination, making trials, etc.

`Include.txt`

```
/abc/**
/def/**
/ghi/**
/jkl/**
```

`Exclude.txt`

```
/def/xyz/not_this_one/
```
Above, folders `abc`, `def`, `ghi`, `jkl` resides in my **home** directory.

The command:

```
rclone --include-from Include.txt --exclude-from Exclude.txt sync ~/ Project:/Users/Hilda/MEGA/SAS/
```

Result: the folder `not_this_one/` is still present.

I combined `--include-from` with `--filter` with no success. Using `--filter`, file `Exclude.txt` would become:

```
- /def/xyz/not_this_one/
```

Result: not working. Folder still present.

I tried the solution involving only `--filter from`:

```
+ /abc/**
+ /def/**
+ /ghi/**
+ /jkl/**

- /def/xyz/not_this_one/
```

Result: not working. Folder still present.

So, in the end, what is the THE command to perform what I want?

Thanks for your support.

**Comment by vesper8** [comment]
@faxotherapy using --filter-from is the correct approach. The order MATTERS. See my comment above? This is mentioned in the docs as well

It goes from top to bottom, as soon as it hits a rule that MATCHES then it stops looking for more rules

So your +/def/** is saying include everything from /def/ so it does that

If you want to include everything in the /def/ except for the /def/xyz/ then you must move the exclusion to the top

**Comment by faxotherapy** [comment]
Thanks for your reply. Switching to `--filter-from` does not work for me even for simply including folders. *rclone* persists copying <u>everything</u> from my home directory.

```
rclone sync --filter-from folders-filter.txt ~ Projet:/Users/Hilda/MEGA/SAS/
```

With `folders-filter.txt` as follows:

```
+ bin/**
+ ABI/**
```

Basically, I want to do a complete sync of the above two folders that sit in my home directory. 

However, when I use instead `--include-from` I have no problem at all:

```
rclone --include-from folders.txt sync ~/ Projet:/Users/Hilda/MEGA/SAS/ 
```

Where `folders.txt` is…

```
/bin/**
/ABI/**
```

I'd like to use the version with `--filter-from` since it allows combination of include and exclude.

**Comment by faxotherapy** [comment]
Apologies for my ignorance; `folders-filter.txt` should be instead:
```
+ bin/**
+ ABI/**
- *
```

Thanks again for your help.
