### ISSUE TITLE
Request to have manual configuration of Backblaze downloadUrl

### ISSUE THREAD

**Issue by roobandev** [ncw/rclone#2808]
#### What is your current rclone version (output from `rclone version`)?
rclone v1.45
- os/arch: linux/amd64
- go version: go1.11.2

#### What problem are you are trying to solve?
When moving files, rclone downloads file and re-uploads for backblaze, which results in bandwidth usage during downloads.

#### How do you think rclone should be changed to solve that?
Recently cloudflare and backblaze made a bandwidth alliance, so if you could possible separate api url and ask for download url in backblaze configuration during setup, this problem can be solved by providing the download url for cloudflare enabled url rather than direct api.

**Comment by roobandev** [comment]
Yeah.

To provide more information on it. Below is the link i followed to create a cloudflare cdn url for my B2 bucket
https://help.backblaze.com/hc/en-us/articles/217666928-Using-Backblaze-B2-with-the-Cloudflare-CDN

I will be using it to access/download files without and bandwidth charges :)

**Comment by ncw** [comment]
Do you want to have a go at implementing it?

**Comment by roobandev** [comment]
Sure.

**Comment by ncw** [comment]
What you need to do is make a new option say "download_url"

https://github.com/ncw/rclone/blob/107293c80e2e55e8abb024a9610c2a456f027046/backend/b2/b2.go#L114

https://github.com/ncw/rclone/blob/107293c80e2e55e8abb024a9610c2a456f027046/backend/b2/b2.go#L127

 and use it here


https://github.com/ncw/rclone/blob/107293c80e2e55e8abb024a9610c2a456f027046/backend/b2/b2.go#L1274

Let me know if you need more help than that

**Comment by ncw** [comment]
I've merged a fix for this (thanks @trettet ) to master now which means it will be in [the latest beta](https://beta.rclone.org) in 15-30 mins and released in v1.47
