### ISSUE TITLE
Spaces in remote directory

### ISSUE THREAD

**Issue by dingho** [ncw/rclone#281]
I'm trying to copy local files to a remote sub-dir on Amazon Cloud drive.  My command is as follows:

rclone copy e:\my files ACD:docs\my files

Rclone seems to treat the last word 'files' as another argument.

**Comment by ncw** [comment]
Try quotes round it, eg

    rclone copy "e:\my files" "ACD:docs\my files"

That should fix it!

**Comment by klauspost** [comment]
Reopen, if quotes doesn't fix it.

**Comment by dingho** [comment]
Thanks.  Quotes fixed it.  I was trying it with quotes previously but in the wrong spot.  ie. ACD:tv\"my files"

**Comment by gskaruz** [comment]
I have a similar issue.
Following command works fine
`rclone --config rclone.conf copy p:\DyskNormalny\www\ RB2Crypt: -v `
but this one not
`rclone --config rclone.conf copy "p:\DyskNormalny\www\" RB2Crypt: -v`

The reason I put the path in quotations is that I also need to send a folder with a space in name
`rclone --config rclone.conf copy "P:\DyskNormalny\My Stuff DVD01\" RB2Crypt: -v`

Error message: "Command copy needs 2 arguments minimum".
rclone v.1.36, using B2 as a destination

**Comment by ncw** [comment]
@gskaruz In the windows shell, inside a `"` delimited string, `\"` is an escaped `"`, so  you can't end a `"` delimited string with `\"`.

Rclone doesn't need it anyway, so I suggest just using

    rclone --config rclone.conf copy "P:\DyskNormalny\My Stuff DVD01" RB2Crypt: -v

**Comment by gskaruz** [comment]
@ncw Great, now it works!

**Comment by zokaiG** [comment]
Hi, I'm having a similar problem with onedrive. I'm on ubuntu 18.04 trying to access onedrive files using the following command:
`rclone --include "*.jpg" copy onedrive-rclone:Directory/Another Dir/ /home/myusr/docs/ `
And it reports the following error:
`Failed to copy: error reading source directory "": directory not found`

**Comment by ncw** [comment]
@zokaiG put the arguments with the space in in double quotes " and all should be well

**Comment by zokaiG** [comment]
Hi, @ncw!

I tried it with double quotes " too and it did not work...
`rclone --include "2020*" copy onedrive-rclone:"Images/Camera Roll/" /home/usr/Documents/Photos/`

Do you think this might be a problem with the way OneDrive handles it?

PS: It works for other folders that do not have space in the name, such as:
`rclone --include "2016*" copy onedrive-rclone:"Images/Profile_Pictures/" /home/usr/Documents/Photos/`

I really appreciate any help you can provide!

**Comment by ncw** [comment]
@zokaiG - can you open up a post on [the rclone forum](https://forum.rclone.org/) and fill in the template there and I or someone else will help you there - thamks!

**Comment by zokaiG** [comment]
I went to the forum to ask for help, but while reading the forum I realized I was using rclone v1.36. So I updated it and it worked just fine!

Thank you for the help! :smile:

**Comment by rulatir** [comment]
Experiencing the same issue as of rclone 1.57 with:

```
rclone copy "rulatir-google:Pałac Pakoszów" zuu-s3:zuu-websites/palac-pakoszow/user --progress
```
The error is:
```
2021-12-28 08:36:27 ERROR : Google drive root 'Pałac Pakoszów': error reading source root directory: directory not found
2021-12-28 08:36:27 ERROR : Attempt 1/3 failed with 1 errors and: directory not found
2021-12-28 08:36:27 ERROR : Google drive root 'Pałac Pakoszów': error reading source root directory: directory not found
2021-12-28 08:36:27 ERROR : Attempt 2/3 failed with 1 errors and: directory not found
2021-12-28 08:36:28 ERROR : Google drive root 'Pałac Pakoszów': error reading source root directory: directory not found
2021-12-28 08:36:28 ERROR : Attempt 3/3 failed with 1 errors and: directory not found
```

The same directory `Pałac Pakoszów` is perfectly visible and readable with `rclone mount`.
