### ISSUE TITLE
Failed to create file system

### ISSUE THREAD

**Issue by ArthurGing** [ncw/rclone#2812]
#### What is the problem you are having with rclone?
 Is there any way to refresh token of onedrive?
 I can't do anything  after  token expired (it needs 60 minutes)

#### What is your rclone version (output from `rclone version`)

1.45

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

linux 64 bit

####  Which cloud storage system are you using? (eg Google Drive)

onedrive  

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

lsl, copy, move

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
Failed to create file system for "arthur:": failed to get root: InvalidAuthenticationToken: CompactToken validation failed with reason code: 80049228.

**Comment by ncw** [comment]
So you run rclone, get it authorized and it works.

Then you wait > 1 hour and rclone gives you `CompactToken validation failed with reason code: 80049228.`

Is that right?

Can you run the failing command again with `-vv --dump bodies` and post the result?  Feel free to XXX out anything that you think looks secret.

What kind of onedrive are you using? Personal, Business, Sharepoint, other?

If you do `rclone config show arthur` you should see your token,  It should look something like this (it will all be one one line and the XXX are very long.  Can you make sure it has a `refresh_token` in there?

```json
token = {
"access_token":"XXX",
"token_type":"Bearer",
"refresh_token":"XXX",
"expiry":"2018-11-29T16:10:46.368783193Z"
}
```

**Comment by ArthurGing** [comment]
Thank you for the prompt reply.
I have solved this issue.
The root cause is that I was trying to generate a rclone.conf manually, and I gave it the wrong format of token expiry time (without float point)

I have another question about rclone.
How to get the response like this when upload the file using 'copyto' with '--dump responses' option .
{"id":"1atPrqmdGYFs5g9O5IGbYHWH_H0LMzAyT","name":"a.jpg","mimeType":"image/jpeg","trashed":false,"parents":["0ALz5qmZf5tz2Uk9PVA"],"webViewLink":"XXXX","createdTime":"2018-12-04T04:00:49.161Z","modifiedTime":"2018-11-26T01:46:11.817Z","md5Checksum":"afb87ca3b67c593daa70b7377b4668b5","size":"49773"}

Best regards

**Comment by ArthurGing** [comment]
Thank you for the prompt reply.
I guess Uploading files using 'copyto' may call api of cloud, so I am trying to get response with '--dump responses', but it show nothing. Is there any way to get response?

Best regards

**Comment by ncw** [comment]
> I guess Uploading files using 'copyto' may call api of cloud, so I am trying to get response with '--dump responses', but it show nothing. Is there any way to get response?

When I try that I see the response.  Don't forget `-vv`!

```
2018/12/05 10:51:57 DEBUG : HTTP RESPONSE (req 0xc0004aeb00)
2018/12/05 10:51:57 DEBUG : HTTP/1.1 201 Created
Content-Type: application/json; charset=utf-8
Date: Wed, 05 Dec 2018 10:51:57 GMT
P3p: CP="BUS CUR CONo FIN IVDo ONL OUR PHY SAMo TELo"
Strict-Transport-Security: max-age=31536000; includeSubDomains
Www-Authenticate: Bearer realm="OneDriveAPI", error="invalid_token", error_description="Invalid auth token"
X-Asmversion: UNKNOWN; 19.161.1128.2006
X-Msedge-Ref: Ref A: 48E0A333677C455EA636FA9904C82087 Ref B: LON21EDGE1014 Ref C: 2018-12-05T10:51:57Z
X-Msnserver: AM3PPF2A98B041F

{"createdBy":{"application":{"displayName":"rclone","id":"48211038"},"user":{"id":...
```

**Comment by ArthurGing** [comment]
Thank you for your help.
 I see the response after adding -vv, thanks a lot.

**Comment by ncw** [comment]
Great!  I think we are done here so I'll close this issue.
