### ISSUE TITLE
Any way to use aria2c  to download large files directly to mounted remote drive?

### ISSUE THREAD

**Issue by ron159** [ncw/rclone#2817]
#### What is your current rclone version (output from `rclone version`)?
rclone v1.45
#### What problem are you are trying to solve?
I want to mount Google Drive as a local storage and use aria2c to download large files (required space more than my hard drive has.) directly to it.

#### How do you think rclone should be changed to solve that?
I have tried.But aria2c just shows :File truncation failed.cause:Operation not permitted.

**Comment by ncw** [comment]
If you want to fix ` :File truncation failed.cause:Operation not permitted.` then you'll need `--vfs-cache-mode writes`, however that will mean files are buffered on your disk which defeats the purpose...

What protocol are you using for downloading?

**Comment by ron159** [comment]
Thanks for your reply!
This error is caused by http.I also test a torrent link ,it shows:Failed to seek the file.
Could i adjust the buffer size?so that to avoid it bigger than my hard drive size?

**Comment by ron159** [comment]
> If you want to fix ` :File truncation failed.cause:Operation not permitted.` then you'll need `--vfs-cache-mode writes`, however that will mean files are buffered on your disk which defeats the purpose...
> 
> What protocol are you using for downloading?



> If you want to fix ` :File truncation failed.cause:Operation not permitted.` then you'll need `--vfs-cache-mode writes`, however that will mean files are buffered on your disk which defeats the purpose...
> 
> What protocol are you using for downloading?

Thanks for your reply!
This error is caused by http.I also test a torrent link ,it shows:Failed to seek the file.
Could i adjust the buffer size?so that to avoid it bigger than my hard drive size?

**Comment by ron159** [comment]
> If you want to fix ` :File truncation failed.cause:Operation not permitted.` then you'll need `--vfs-cache-mode writes`, however that will mean files are buffered on your disk which defeats the purpose...
> 
> What protocol are you using for downloading?

Got the reason why i can't do so.
Anyway,thanks for your wonderful work.

**Comment by Juancollado2003** [comment]
I had a similar problem that I solved using xargs, my goal is to download a list of mkv to then move them to my rclone server like this:

assuming "file" is a list of url one by line 

cat file | xargs -I % sh -c '{ aria2c --on-download-complete=/root/test.sh -x3 -c --save-session out.txt --file-allocation=prealloc --connect-timeout=5 -t5 -m1 --retry-wait=1 -UIPTVSmartersPro --async-dns=false --retry-wait=1 %; sleep 120; }'

So xargs will print "file" to pipe every 120s and aria2c will execute the script test.sh on every download completed

Here is my test.sh in case someone need it

#!/bin/bash 
a=$3
b=$(echo $3 | sed 's\/tmp/aria2c/\\g') 
sed -i '1d' /tmp/aria2c/mkv2
rclone moveto $a db4:k4/$b
echo "The file [$a]"
echo "Was move to [db4:k4/$b]"
