### ISSUE TITLE
allow webdav to also serve http methods.

### ISSUE THREAD

**Issue by calisro** [ncw/rclone#2824]
reference: https://forum.rclone.org/t/webdav-serve-http-pages-also/7878/3

Enhancement to allow webdav to optionally also serve GET/HEAD/PUT requests like a normal http server essentially combining the two functions into one so that there is no need to run separate ports to have both services running. This is typical with nginx implementations of davs and would be helpful.

**Comment by ncw** [comment]
It should be quite straightforward to combine the http remote with the webdav remote or import the functionality from the one into the other.

Would anyone like to have a go at this?

**Comment by calisro** [comment]
Brilliant!  Cant wait to test it out.  Will reduce complexity of running multiple rclones behind caddy servers for me! Thanks.
