### ISSUE TITLE
panic: runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by marekk1717** [ncw/rclone#2825]
#### What is the problem you are having with rclone?

During the sync of 2 OneDrive for Business accounts with encryption enabled, rclone throw the following error
panic: runtime error: slice bounds out of range

#### What is your rclone version (output from `rclone version`)

1.41

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

Ubuntu 16.04

####  Which cloud storage system are you using? (eg Google Drive)

OneDrive

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

rclone sync crypt1:/ crypt2:/

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

goroutine 402791 [running]:
github.com/ncw/rclone/lib/readers.(*RepeatableReader).Read(0xc4202ec270, 0xc420539000, 0x1000, 0x1000, 0xc42d2b4c60, 0xc42d2b4c50, 0xc420453aa0)
        /home/ncw/go/src/github.com/ncw/rclone/lib/readers/repeatable.go:56 +0x260
net/http.transferBodyReader.Read(0xc42147d9a0, 0xc420539000, 0x1000, 0x1000, 0x56c, 0x0, 0xc42025d948)
        /opt/go/go1.10/src/net/http/transfer.go:60 +0x56
io.(*LimitedReader).Read(0xc4203cb2a0, 0xc420539000, 0x1000, 0x1000, 0x56c, 0x0, 0x0)
        /opt/go/go1.10/src/io/io.go:446 +0x63
bufio.(*Writer).ReadFrom(0xc42025d940, 0x112d460, 0xc4203cb2a0, 0x7fe2032d9a68, 0xc42025d940, 0x1)
        /opt/go/go1.10/src/bufio/bufio.go:703 +0xcd
io.copyBuffer(0x112c360, 0xc42025d940, 0x112d460, 0xc4203cb2a0, 0x0, 0x0, 0x0, 0xf0bda0, 0xc421487a01, 0xc4203cb2a0)
        /opt/go/go1.10/src/io/io.go:386 +0x31a
io.Copy(0x112c360, 0xc42025d940, 0x112d460, 0xc4203cb2a0, 0xc420539ca2, 0x101dd8e, 0x2)
        /opt/go/go1.10/src/io/io.go:362 +0x5a
net/http.(*transferWriter).WriteBody(0xc42147d9a0, 0x112c360, 0xc42025d940, 0x2, 0x2)
        /opt/go/go1.10/src/net/http/transfer.go:337 +0x5fa
net/http.(*Request).write(0xc4203aa700, 0x112c360, 0xc42025d940, 0x0, 0xc42030ed20, 0x0, 0x0, 0x0)
        /opt/go/go1.10/src/net/http/request.go:622 +0x6b2
net/http.(*persistConn).writeLoop(0xc4203f2fc0)
        /opt/go/go1.10/src/net/http/transport.go:1825 +0x1ea
created by net/http.(*Transport).dialConn
        /opt/go/go1.10/src/net/http/transport.go:1238 +0x97f

**Comment by ncw** [comment]
I'm reasonably sure that this was fixed in #2572 with ee700ec01a1b308022580e8544cb539bbec57ec6

So if you try the latest release which is 1.45 you should find it is fixed.
