### ISSUE TITLE
serve not reporting logon failures

### ISSUE THREAD

**Issue by calisro** [ncw/rclone#2834]
I'm using both http and davs (and i'm sure ftp and others need to be included here).  They are not reporting authentication failures to the log at any log level.  These should be INFO level logging for authentication failures.  The RC remote should also report this.

rclone: Version "v1.45-022-gfc654a4c-beta" 

rclone: Version "v1.45-022-gfc654a4c-beta" starting with parameters ["rclone" "-vvvv" "serve" "http" "unionedmedia:" "--stats=0" "--addr" ":xxxx" "--cert" "xxxx "--key" "xxxx" "--user" "xxxx" "--pass" "xxxx" "--realm" "Authorized users only" "--checkers" "10" "--transfers" "10" "--read-only" "--dir-cache-time=48h" "--buffer-size" "150M" "--vfs-cache-mode" "writes" "--vfs-read-chunk-size-limit" "600M" "--rc" "--rc-addr" ":xxxx" "--rc-user" "xxxx" "--rc-pass" "xxxx"]

**Comment by ncw** [comment]
Do you mean authentication failures when someone tries to log into the http or dav server?

This is controlled by the 	github.com/abbot/go-http-auth library which doesn't appear to log things on auth failure :-(

**Comment by calisro** [comment]
Yes authentication failure logging...  Interesting.  Leaves us open to brute force with with no ability to see it is happening.  I wanted to plug fail2ban to scrape the log files.

**Comment by ncw** [comment]
I figured out how to put the bits of the library together to make logs

https://beta.rclone.org/branch/v1.45-032-gfbdba864-fix-2834-auth-logging-beta/ (uploaded in 15-30 mins)

This produces logs like this

```
2018/12/13 12:13:44 INFO  : /: 127.0.0.1:39696: Basic auth challenge sent
2018/12/13 12:13:54 INFO  : /: 127.0.0.1:40050: Unauthorized request from ncw
```

What do you think?
- do the logs look ok?
- do you want the username on them?  It would be much easier without :-)

**Comment by calisro** [comment]
The logs look good. That beta does include the username which I think is important. I'm not using that with fail2ban but I think that would be consistent with other http services. The current beta looks great. Thanks Nick.

**Comment by ncw** [comment]
Thanks for testing.

I've merged that into master now it will be in [the latest beta](https://beta.rclone.org) in 15-30 mins and in v1.46 when released.

Do you think the log messages need documenting?  I saw your fail2ban config - very useful.

**Comment by calisro** [comment]
I cant see much to document.  Perhaps just a blurb on serve pages that authentication failures are logged at INFO level.  But its pretty straight forward.  

The only other thing that came to mind today was serve FTP which has the same issue.  You mind if I open another issue for Serve FTP?

This is how the log looks for vsftp:

```
Fri Dec 14 09:38:35 2018 [pid 16242] CONNECT: Client "X.X.X.X"
Fri Dec 14 09:38:37 2018 [pid 16248] [calisro] OK LOGIN: Client "X.X.X.X"
Fri Dec 14 09:38:38 2018 [pid 16247] [calisro] OK UPLOAD: Client "X.X.X.X", "/XXXXX/XXXXX.jpg", 412934 bytes, 295.34Kbyte/sec
Fri Dec 14 09:38:41 2018 [pid 16265] CONNECT: Client "X.X.X.X"
Fri Dec 14 09:38:41 2018 [pid 16262] [calisro] OK LOGIN: Client "X.X.X.X"
Fri Dec 14 09:38:55 2018 [pid 16238] [sdf] FAIL LOGIN: Client "X.X.X.X"
```

They post pend all lines with hte IP address which is useful but depending on the complexity the minimum I think should be similar to these two lines:

Preconnection:
```
Fri Dec 14 09:38:41 2018 [pid 16265] CONNECT: Client "X.X.X.X"
```

Login Successful:
```
Fri Dec 14 09:38:41 2018 [pid 16262] [calisro] OK LOGIN: Client "X.X.X.X"
```

Login Failure:
```
Fri Dec 14 09:38:55 2018 [pid 16238] [sdf] FAIL LOGIN: Client "X.X.X.X"
```

**Comment by calisro** [comment]
I don't know much about rustic but that should really be included as well.  Really anything under serve should have this done.

**Comment by ncw** [comment]
> The only other thing that came to mind today was serve FTP which has the same issue. You mind if I open another issue for Serve FTP?

Yes, please do

> I don't know much about rustic but that should really be included as well. Really anything under serve should have this done.

restic is HTTP based as is webdav so these are now both covered.
