### ISSUE TITLE
Parallelizing Rclone with --checkers thread when using --files-from

### ISSUE THREAD

**Issue by nishkalprakash** [ncw/rclone#2835]
#### What is your current rclone version (output from `rclone version`)?
rclone v1.45
- os/arch: windows/amd64
- go version: go1.11

#### What problem are you are trying to solve?
I am trying to Transfer files from HTTP remote to a GD remote using a --files-from flag which has over 10k entries. Rclone seems to be checking if each file in the --file-from exists, one at a time.

#### How do you think rclone should be changed to solve that?
This process of checking if files exist could be parallelized with checkers.
This would make this process run much faster.

**Comment by ncw** [comment]
I've had a go at this here

https://beta.rclone.org/branch/v1.45-033-ga3a64a74-fix-2835-parallel-files-from-beta/ (uploaded in 15-30 mins)

Can you test please?

Try different numbers in --checkers

**Comment by nishkalprakash** [comment]
Will test.

The link is not found.
"404 Not Found"

**Comment by ncw** [comment]
Ok that needs a fix! WIll reply with another URL shortly!

**Comment by ncw** [comment]
It is there now!  I paste the above message when the CI build starts.  It takes ~30 mins and usually works, so I can go off and do other things at that point.

**Comment by nishkalprakash** [comment]
I started the transfer 20 mins back, the transfer didn't start until now,
but then i realised that the file had 50k links, so i stopped that.

So i tried on a test file with 1k links, and 
--checkers 50 which completed checking in 14 sec,
--checkers 4, completed checking in 107 sec...

So i guess it was a success.
Great Job.
Thank you.

**Comment by ncw** [comment]
Thanks for testing :-)

I've merged that to master now - you can find it in [the latest beta](https://beta.rclone.org) in 15-30 mins and in v1.46 when it is released!
