### ISSUE TITLE
 B2 backend uploads to wrong bucket if application key does not allow uploading to the right one

### ISSUE THREAD

**Issue by nicoulaj** [ncw/rclone#2839]
#### What is the problem you are having with rclone?
B2 backend uploads to wrong bucket if application key does not allow uploading to the right one.

Steps to repoduce:

 * In B2 web UI, create two buckets, `bucket1` and `bucket2`
 * Create an application key with R+W access to `bucket1` only
 * Configure it in rclone
 * Try uploading to `bucket2` using rclone (`rclone sync dir b2:bucket2`)

Expected output:
rclone fails with a permission error (`can't write to bucket2`)

Actual output:
rclone uploads everything and overwrites `bucket1`.

#### What is your rclone version (output from `rclone version`)
```
rclone v1.42
- os/arch: linux/amd64
- go version: go1.9.4
```

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
CentOS 7.6.1810 x86_64

####  Which cloud storage system are you using? (eg Google Drive)
B2

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
```
rclone sync --stats-log-level NOTICE --transfers 32 myrepo b2:mybucket
```

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
N/A

**Comment by ncw** [comment]
Can you try this with the [the latest release](https://rclone.org/downloads/) please ? I'm pretty sure we've fixed that bug already, but not 100% certain!

Thanks

**Comment by nicoulaj** [comment]
Just tested it on rclone v1.45, the bug is still here.

**Comment by ncw** [comment]
Thanks!  I'll try to replicate then figure out the problem.

**Comment by ncw** [comment]
I've replicated the problem.

Here is a fix - can you give it go please?

https://beta.rclone.org/branch/v1.45-034-g045aad08-fix-2839-b2app-key-beta/ (uploaded in 15-30 mins)

b2 have added an extra field `bucketName` in the [API call return](https://www.backblaze.com/b2/docs/b2_authorize_account.html) which makes checking the bucket name is the one the user asked for much easier. I expect this problem was the reason why!

**Comment by ncw** [comment]
Thanks for testing :-)

I've merged this now - it will be in [the latest beta](https://beta.rclone.org) in 15-30 mins and in v1.46 when released.

**Comment by arjones85** [comment]
Thanks for fixing this. Just got bit by this bug under 1.45 and was super confused on what the heck was happening.

**Comment by ncw** [comment]
> Thanks for fixing this. Just got bit by this bug under 1.45 and was super confused on what the heck was happening.

Yes it is a very confusing bug!  Hopefully it didn't cause too many problems.
