### ISSUE TITLE
dedupe for sftp

### ISSUE THREAD

**Issue by eurodomenii** [ncw/rclone#2840]
Dedupe feature is working for sftp? 
Thx!

**Comment by ncw** [comment]
> Dedupe feature is working for sftp?
> Thx!

No it doesn't work for sftp.  It is only for getting rid of identical file names which I don't think are possible on sftp.

**Comment by ncw** [comment]
That isn't what dedupe does (though there is an issue to do that).

What I'd do is this to show the duplicates

```
  rclone md5sum sftpremote:path | tee MD5SUM
  sort < MD5SUM  > MD5SUM.sorted
  uniq -w32 -D < MD5SUM.sorted  | cut -c35- | less
```

You can then use something like this(untested)  to delete the first duplicate

```
  uniq -w32 -d < MD5SUM.sorted   | cut -c35- | xargs -i rclone delete sftpremote:path/{}
```
