### ISSUE TITLE
serve ftp doesn't appear to be closing file handles.

### ISSUE THREAD

**Issue by calisro** [ncw/rclone#2845]
I've watched my system run out of open files every few hours since I started using serve ftp.  I check and Just see the open files rises with each incoming file until it dies.

```
cd /proc
for pid in [0-9]*; do     echo "PID = $pid with $(ls /proc/$pid/fd/ | wc -l) file descriptors"; done | sort -rn -k5 | head | while read -r _ _ pid _ fdcount _; do   command=$(ps -o cmd -p "$pid" -hc);   printf "pid = %5d with %4d fds: %s\n" "$pid" "$fdcount" "$command"; done

root@cloudc:/data/bin# ./fds
pid =  2031 with  149 fds: rclone
<cut>
```

**Comment by ncw** [comment]
Can you narrow it down to a particular activity? Uploading/downloading/listing etc?

**Comment by calisro** [comment]
This is while uploading on my server. I don't use it for downloads at all.

**Comment by calisro** [comment]
If you tell me what kind of debugging settings I can set I can do that and recreate it pretty quickly

**Comment by ncw** [comment]
The most helpful thing would be if you can get the sever to leak some file handles (more is better!) then kill the process with SIGINT.  This will produce a backtrace to stderr of all the running go-routines - this is usually enough to figure out where the leak comes from.

**Comment by calisro** [comment]
Killing SIGINT isn't producing a back trace.

**Comment by calisro** [comment]
I may have figured out what is happening though.  The devices that I have uploading to the FTP server have a AUTO setting where it will figure out if it is a PORT or PASV connection.  These cannot use PORT because of a NAT and a firewall.  It looks like the way it works is for each connection it will try PORT and fallback to PASV.  I changed that setting on those devices specifically to PASV and I don't see file handles creeping up.

It looks like on the rclone side when PORT is tried, those connections perhaps don't timeout quick enough and creep up file handles till they do.  But there are more connections coming in than can be timed out.  I've been running now for a bit and the open files count is remaining consistent.

**Comment by ncw** [comment]
> Killing SIGINT isn't producing a back trace.

:man_facepalming: I mean `kill -QUIT` or `CTRL-\` - sorry!


> It looks like on the rclone side when PORT is tried, those connections perhaps don't timeout quick enough and creep up file handles till they do. But there are more connections coming in than can be timed out. I've been running now for a bit and the open files count is remaining consistent.

Ah I see.  If you can get the backtrace then I can see exactly which bit of code that is.  I suspect the timeout code (in the upstream ftp library) needs fixing, you are correct.

**Comment by calisro** [comment]
[stack.gz](https://github.com/ncw/rclone/files/2696027/stack.gz)

**Comment by ncw** [comment]
Thanks for that - very helpful :-)

There are ~650 of this go routine traceback

```
goroutine 8 [semacquire, 51 minutes]:
sync.runtime_SemacquireMutex(0xc0001640bc, 0xc00014c100)
        /home/travis/.gimme/versions/go1.11.2.linux.amd64/src/runtime/sema.go:71 +0x3d
sync.(*Mutex).Lock(0xc0001640b8)
        /home/travis/.gimme/versions/go1.11.2.linux.amd64/src/sync/mutex.go:134 +0xff
github.com/ncw/rclone/vendor/github.com/goftp/server.(*ftpPassiveSocket).Close(0xc000164070, 0x0, 0x0)
        /home/travis/gopath/src/github.com/ncw/rclone/vendor/github.com/goftp/server/socket.go:196 +0x42
github.com/ncw/rclone/vendor/github.com/goftp/server.(*Conn).Close(0xc00009a680)
        /home/travis/gopath/src/github.com/ncw/rclone/vendor/github.com/goftp/server/conn.go:132 +0x60
github.com/ncw/rclone/vendor/github.com/goftp/server.commandQuit.Execute(0xc00009a680, 0x0, 0x0)
        /home/travis/gopath/src/github.com/ncw/rclone/vendor/github.com/goftp/server/cmd.go:671 +0x57
github.com/ncw/rclone/vendor/github.com/goftp/server.(*Conn).receiveLine(0xc00009a680, 0xc00038e666, 0x6)
        /home/travis/gopath/src/github.com/ncw/rclone/vendor/github.com/goftp/server/conn.go:165 +0x169
github.com/ncw/rclone/vendor/github.com/goftp/server.(*Conn).Serve(0xc00009a680)
        /home/travis/gopath/src/github.com/ncw/rclone/vendor/github.com/goftp/server/conn.go:116 +0x100
created by github.com/ncw/rclone/vendor/github.com/goftp/server.(*Server).Serve
        /home/travis/gopath/src/github.com/ncw/rclone/vendor/github.com/goftp/server/server.go:263 +0x21d
```

And the same number of these

```
goroutine 43 [IO wait, 51 minutes]:
internal/poll.runtime_pollWait(0x7f77df9dba20, 0x72, 0x0)
        /home/travis/.gimme/versions/go1.11.2.linux.amd64/src/runtime/netpoll.go:173 +0x66
internal/poll.(*pollDesc).wait(0xc00014ce98, 0x72, 0xc000149300, 0x0, 0x0)
        /home/travis/.gimme/versions/go1.11.2.linux.amd64/src/internal/poll/fd_poll_runtime.go:85 +0x9a
internal/poll.(*pollDesc).waitRead(0xc00014ce98, 0xffffffffffffff00, 0x0, 0x0)
        /home/travis/.gimme/versions/go1.11.2.linux.amd64/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Accept(0xc00014ce80, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/travis/.gimme/versions/go1.11.2.linux.amd64/src/internal/poll/fd_unix.go:384 +0x1a0
net.(*netFD).accept(0xc00014ce80, 0x0, 0x0, 0x0)
        /home/travis/.gimme/versions/go1.11.2.linux.amd64/src/net/fd_unix.go:238 +0x42
net.(*TCPListener).accept(0xc000142020, 0x42adc2, 0x8, 0xc000149380)
        /home/travis/.gimme/versions/go1.11.2.linux.amd64/src/net/tcpsock_posix.go:139 +0x2e
net.(*TCPListener).Accept(0xc000142020, 0x12890b8, 0xc000164048, 0x0, 0x0)
        /home/travis/.gimme/versions/go1.11.2.linux.amd64/src/net/tcpsock.go:260 +0x47
github.com/ncw/rclone/vendor/github.com/goftp/server.(*ftpPassiveSocket).GoListenAndServe.func1(0xc000164000, 0x13c4860, 0xc000142020)
        /home/travis/gopath/src/github.com/ncw/rclone/vendor/github.com/goftp/server/socket.go:235 +0x65
created by github.com/ncw/rclone/vendor/github.com/goftp/server.(*ftpPassiveSocket).GoListenAndServe
        /home/travis/gopath/src/github.com/ncw/rclone/vendor/github.com/goftp/server/socket.go:232 +0x326
```

The second of those is waiting for a connection which never comes - I suspect that is the result of the PORT connection which never arrives and I think that is causing the mutex to be locked which is causing the first one.

Can you try this?

I set a timeout for 60 seconds (which is the default value vsftp uses) - I think that should fix the issue.

https://beta.rclone.org/branch/v1.45-036-g1d96f9a1-fix-2845-serve-ftp-beta/ (uploaded in 15-30 mins)

I patched rclone's vendored copy of the upstream library - if it works for you then I'll submit the patch upstream properly.

**Comment by calisro** [comment]
Testing now..  

Just thinking though.  Even with a 60 second timeout, its possible to spam a ftp site with port requests and DOS the server  pretty easily by filling open files.  Perhaps a flag to to force PORT,PASV, BOTH?  I wonder how vsftp handles this.  I left vsftpd server on BOTH but I still didn't see the open files climb at all.  Right now open files with rclone is climbing with the new beta (slower though)  and as long as requests come quicker than 1 a minute, it will continue if I understood properly.

**Comment by ncw** [comment]
I sent the patch upstream here: https://github.com/goftp/server/pull/62
