### ISSUE TITLE
nil pointer crash with -P switch when running as Jenkins job

### ISSUE THREAD

**Issue by Lyve1981** [ncw/rclone#2846]
Jenkins is a CI system, while doing many other things, it displays the console output on a web page. I assume that the output of -P/progress is not compatible / the ansiParser cannot handle it somehow or ansiParser itself is nil? Unfortunately I don't have any go knowledge.

Repro is 100% and very simple, see below.

#### What is the problem you are having with rclone?
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0xa0 pc=0xe2c855]

#### What is your rclone version (output from `rclone version`)
rclone v1.45
- os/arch: windows/amd64
- go version: go1.11

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Windows 7 64 Bit

####  Which cloud storage system are you using? (eg Google Drive)
none / local copy in a very simple repro

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone -vv -P sync d:\temp c:\temp 

The relevant problem is the -P switch, if I omit -P it works fine. If I run the same command in a regular batch file, it's fine, too.

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
```
rclone -vv -P sync d:\temp c:\temp 
2018/12/17 21:33:13 DEBUG : rclone: Version "v1.45" starting with parameters ["c:\\Apps\\rclone\\rclone" "-vv" "-P" "sync" "d:\\temp" "c:\\temp"]
2018/12/17 21:33:13 DEBUG : Using config file from "C:\\Users\\tvserverWin7\\.config\\rclone\\rclone.conf"
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0xa0 pc=0xe2c855]

goroutine 33 [running]:
github.com/ncw/rclone/vendor/github.com/Azure/go-ansiterm.(*AnsiParser).execute(0xc000446340, 0x1d, 0x20)
	C:/gopath/src/github.com/ncw/rclone/vendor/github.com/Azure/go-ansiterm/parser_actions.go:118 +0x35
github.com/ncw/rclone/vendor/github.com/Azure/go-ansiterm.groundState.Handle(0x128c216, 0x6, 0xc000446340, 0xa, 0xc0004601a0, 0x192, 0x192, 0xc000089958)
	C:/gopath/src/github.com/ncw/rclone/vendor/github.com/Azure/go-ansiterm/ground_state.go:20 +0x17e
github.com/ncw/rclone/vendor/github.com/Azure/go-ansiterm.(*AnsiParser).handle(0xc000446340, 0x10a, 0x1a0, 0x18f)
	C:/gopath/src/github.com/ncw/rclone/vendor/github.com/Azure/go-ansiterm/parser.go:109 +0x4d
github.com/ncw/rclone/vendor/github.com/Azure/go-ansiterm.(*AnsiParser).Parse(0xc000446340, 0xc000460340, 0x18f, 0x1a0, 0x18f, 0x1a0, 0x0)
	C:/gopath/src/github.com/ncw/rclone/vendor/github.com/Azure/go-ansiterm/parser.go:99 +0x5f
github.com/ncw/rclone/cmd.writeToTerminal(0xc00045e000, 0x18f, 0x1b8)
	C:/gopath/src/github.com/ncw/rclone/cmd/progress_windows.go:33 +0x14b
github.com/ncw/rclone/cmd.printProgress(0xc00002a320, 0x4b)
	C:/gopath/src/github.com/ncw/rclone/cmd/progress.go:124 +0x38d
github.com/ncw/rclone/cmd.startProgress.func1(0x128bf06, 0xc00002c8d0, 0x2f)
	C:/gopath/src/github.com/ncw/rclone/cmd/progress.go:35 +0x167
github.com/ncw/rclone/fs.LogPrintf(0x106, 0x121d160, 0xc0002ff4a0, 0x1293195, 0xc, 0x0, 0x0, 0x0)
	C:/gopath/src/github.com/ncw/rclone/fs/log.go:82 +0xa2
github.com/ncw/rclone/fs.Infof(0x121d160, 0xc0002ff4a0, 0x1293195, 0xc, 0x0, 0x0, 0x0)
	C:/gopath/src/github.com/ncw/rclone/fs/log.go:116 +0x8c
github.com/ncw/rclone/fs/operations.Copy(0x1431040, 0xc0000a1480, 0x0, 0xc000054f60, 0xc000354a20, 0x21, 0x14310c0, 0xc0002ff4a0, 0x0, 0x0, ...)
	C:/gopath/src/github.com/ncw/rclone/fs/operations/operations.go:356 +0x59d
github.com/ncw/rclone/fs/sync.(*syncCopyMove).pairCopyOrMove(0xc000264700, 0xc000322a40, 0x1431040, 0xc0000a1480, 0xc0002647d8)
	C:/gopath/src/github.com/ncw/rclone/fs/sync/sync.go:280 +0x243
created by github.com/ncw/rclone/fs/sync.(*syncCopyMove).startTransfers
	C:/gopath/src/github.com/ncw/rclone/fs/sync/sync.go:306 +0xa6

C:\Program Files (x86)\Jenkins\workspace\test_rclone_crash>exit 2 
Build step 'Execute Windows batch command' marked build as failure
Finished: FAILURE
```

**Comment by ncw** [comment]
I've had a go at fixing this here - could you test it with and without Jenkins please?

https://beta.rclone.org/branch/v1.45-036-g40eeac58-fix-2846-win-progress-beta/ (uploaded in 15-30 mins)

Thank you

**Comment by Lyve1981** [comment]
Sorry for the slow response, yes indeed that fixes it. It outputs

> ERROR : Failed to start progress: windows terminal: initialization failed

as expected, thanks for the very fast fix!

**Comment by ncw** [comment]
Thanks for testing :-)

I've merged this fix to master now, it will be in [the latest beta](https://beta.rclone.org) in 15-30 mins and released with 1.46

**Comment by ctonsing** [comment]
Apologies for hijacking this thread somewhat, but I am seeing this output

`ERROR : Failed to start progress: windows terminal: initialization failed`

when executing rclone with --progress from within a Java process on Windows and I'm trying to understand if there is a way to still obtain the progress output when using it in this way?

**Comment by ncw** [comment]
> Apologies for hijacking this thread somewhat, but I am seeing this output
> 
> `ERROR : Failed to start progress: windows terminal: initialization failed`
> 
> when executing rclone with --progress from within a Java process on Windows and I'm trying to understand if there is a way to still obtain the progress output when using it in this way?

I would use `-v --stats 1s` to get the stats to print regularly - that is probably easier to parse from a Java program.  You can also use the [rclone API to read the stats](https://rclone.org/rc/#core-stats-returns-stats-about-current-transfers)

**Comment by ctonsing** [comment]
> 
> I would use `-v --stats 1s` to get the stats to print regularly - that is probably easier to parse from a Java program. You can also use the [rclone API to read the stats](https://rclone.org/rc/#core-stats-returns-stats-about-current-transfers)

Thank you very much for your prompt reply and for pointing me in the right direction, much appreciated!
