### ISSUE TITLE
Sync not deleting old files from remote drive

### ISSUE THREAD

**Issue by isaiah36** [ncw/rclone#285]
Hello,

I am using the sync command straight, without any options, but I find older directories are not being deleted from the remote drive.  In other words, the remote is not an exact replica of the local.  For example, a renamed folder is there with both new name and old name, with all of the files inside both.

What am I missing?  I re-read the Read Me file, and if I understand it correctly, a straight sync command is what I should be using to keep the remote as an exact replica of the local.  

Thanks!

Isaiah

**Comment by ncw** [comment]
Do you mean directories, or files within those directories?  rclone doesn't manage empty directories (see #100) at the moment.

If it isn't just empty directories, then can you post a log with `-v` of rclone running please?

Thanks

Nick

**Comment by isaiah36** [comment]
No, not empties.  The files are all inside.  Sorry to be such a dummy, but can you give me the exact command?  Where should I place the -v?

**Comment by isaiah36** [comment]
OK, I intuited that correctly.  I did a sync but all of the verbose output does not show in the terminal window.  I attached what was in the terminal in a text file.  I can get the rest of the log if I know where it is stored.  I did not see a rclone entry in /var/log.

[rclone-log.txt](https://github.com/ncw/rclone/files/82825/rclone-log.txt)

**Comment by ncw** [comment]
You can use the `--log-file` option to save the output to a file which you might find easier.

I can see it deleting old stuff at the end of the sync.

What might have happened is if there was an error in the sync, it doesn't delete stuff.

Looks like the sync completed correctly this time (according to that log), so it will have deleted the old stuff - can you check?

**Comment by isaiah36** [comment]
I just browsed the ACD via web and saw the empty directories.  The files are indeed being deleted.  Now I am doubting myself.  I manually deleted through web browser a directory with duplicate content earlier, and the total space usage went down as if files were deleted, not just empty directories.  I will keep checking again to see if remote deletions are failing some times, but as of now I am in doubt about my previous experience.

**Comment by isaiah36** [comment]
Is empty folder deletion coming soon?

**Comment by isaiah36** [comment]
It emails me a log after completing the daily cron job, so saving it to file is not necessary for my purposes.

**Comment by ncw** [comment]
Well if you had an errored sync that explains everything

**Comment by isaiah36** [comment]
Thanks, NCW!  I did have what appeared to me as fitting the description, "errored sync" several days in a row.  All is well now, after fixing that pesky file that wouldn't let rclone replace it.  

What I notice is that my file manager reports my Music folder as 1.0 Tb and my Videos folder as 12 Gb, so my ACD should say 1.012 Tb.  In fact it says 949.9 Gb for total storage used.  Any explanation for that difference?

**Comment by isaiah36** [comment]
ACD web interface has a 'Size' column but it doesn't actually report any numbers there.

**Comment by ncw** [comment]
Try running

    rclone size remote:dir

That will add up what rclone thinks you've got. 

Quite often file managers round up the sizes of things to the nearest disk block (4k say) so I wouldn't be surprised if they are different. Rclone size will tell you how many files there are - try comparing that too.

**Comment by isaiah36** [comment]
From rclone --
Total objects: 37118
Total size: 938.733G (1007956981276 bytes)

From file manager --
44,604 items, totalling 1.0 TB

Looks like the total number of bytes is about the same.

**Comment by isaiah36** [comment]
I checked the local directory with rclone --
Total objects: 37141
Total size: 939.019G (1008263991519 bytes)

That sounds about right considering the files added since last sync.  The file manager could be counting hidden items or something like that.

Thanks, NCW!

**Comment by ncw** [comment]
Good thinking to check the local directory with rclone!

**Comment by isaiah36** [comment]
Thank you, sir!  :)

**Comment by isaiah36** [comment]
No errors in sync, and deletions made from remote.  I manually cleaned the Trash folder out in the web browser.  (I searched for the empty folders and deleted them, a chore I expect I'll tire of pretty soon.)  There is no longer an "issue", NCW, if you want to close this one out.

**Comment by ncw** [comment]
I'll add a little more explanation to the docs
