### ISSUE TITLE
Onedrive: Failed to copy: failed to make directory: invalidRequest: One of the provided arguments is not acceptable.

### ISSUE THREAD

**Issue by marekk1717** [ncw/rclone#2853]
#### What is the problem you are having with rclone?

Sync to encrypted OneDrive:
2018/12/20 16:59:01 ERROR : xxxxxx/xxxxxxxxxxxxxx/xxxxxxxxxxxxxxxxxxxx/xxx.txt: Failed to copy: invalidRequest: One of the provided arguments is not acceptable.

**How can I check which argument is not acceptable?**

#### What is your rclone version (output from `rclone version`)

1.45

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

ubuntu 18.04
windows

####  Which cloud storage system are you using? (eg Google Drive)

OneDrive for business

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

rclone sync E:\backup crypt2:\folder\

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

2018/12/20 16:59:01 ERROR : xxxxxx/xxxxxxxxxxxxxx/xxxxxxxxxxxxxxxxxxxx/xxx.txt: Failed to copy: invalidRequest: One of the provided arguments is not acceptable.

**Comment by Cnly** [comment]
I think this is because your file path is too loooong. OneDrive has a limit on the URL length. It's about 400 characters if I remember. :) This happens more frequently if you're encrypting filenames because that lengthens them. Can you shorten the file path by reducing the number of nested folders or shorten the file/folder names and try again? Thanks!

**Comment by Cnly** [comment]
I'm closing this issue for now because it's been inactive for a pretty long time and that it's probably a limitation of OneDrive. Please feel free to re-open if needed.

**Comment by ttarchala** [comment]
I'm affected by this problem myself. Even though it is indeed a limitation of OneDrive - I've just tested myself that I can't make a path longer than 400 characters - it makes rclone with OneDrive remotes pretty unreliable as a backup solution for an arbitrary directory, with real life scenarios where people have lots of nested subdirectories.

Perhaps it would be possible to shorten the directory names on OneDrive, and store the real file name in some metadata, or in a specially named file inside the directory?

**Comment by ljk5403** [comment]
I'm also affected by this problem, and I found that the same file with a long name can be stored when not encrypted while cause an error when use the encryption. So are there any ways to avoid this problem without change file name?

**Comment by Cnly** [comment]
Sadly there doesn't seem to be a way around this yet. :( But https://github.com/rclone/rclone/issues/675 may be a possibility in the future.

**Comment by ljk5403** [comment]
Since we encrypt the file, maybe we can add a header to it to store file name ? Just an idea, I am not expert in this field, please ignore it if impossible🤣

**Comment by major-mayer** [comment]
I have found a solution for this problem. 
You can use the new "--crype-filename-encoding" flag to shorten encrypted filenames a lot: https://rclone.org/crypt/#crypt-filename-encoding
This is still a bit experimental though: https://github.com/rclone/rclone/issues/6803

**Comment by mkrohn** [comment]
> I have found a solution for this problem. You can use the new "--crype-filename-encoding" flag to shorten encrypted filenames a lot: https://rclone.org/crypt/#crypt-filename-encoding This is still a bit experimental though: [#6803](https://github.com/rclone/rclone/issues/6803)

Great !
