### ISSUE TITLE
rclone sync doesn't terminate when quotaExceeded

### ISSUE THREAD

**Issue by sogood007** [ncw/rclone#286]
When I use rclone sync on google drive with 15GB quota, because rclone didn't delete before upload, I exceed my quota. I kept getting this error for each file. 

 Received error: Chunk upload failed - retry: code=403, err=googleapi: Error 403: The user has exceeded their Drive storage quota, quotaExceeded - retrying 1/10

It kept retrying for each file and it end up blow up my ISP uploaded bandwidth quota.

**Comment by ncw** [comment]
This would be relatively easy to detect, but rclone doesn't have a fatal error notification in the sync.  It is highly concurrent so just exiting would break other in progress transfers which might suceed.  Needs a bit of thought.

**Comment by ncw** [comment]
rclone does have an error which it knows it shouldn't retry now so this would be easy to implement.

**Comment by arthurhanlon** [comment]
Hi there, sorry to revive this but I am now seeing this issue with Backblaze B2 whilst doing some tests. The free storage quota has been reached so when I run, the log file simply states 403 storage_cap_exceeded and the rclone process never actually ends. Is there perhaps a flag that I'm missing?

Sadly I am using the standard packaged version that comes with Freenas so the version is lagging a little but note that in the changelog, v1.31 should "Treat 403 errors (eg cap exceeded) as fatal."?

rclone v1.38
- os/arch: freebsd/amd64
- go version: go1.10.1

**Comment by ncw** [comment]
> Hi there, sorry to revive this but I am now seeing this issue with Backblaze B2 whilst doing some tests. The free storage quota has been reached so when I run, the log file simply states 403 storage_cap_exceeded and the rclone process never actually ends.

What does it do?  Does it hang?

Can you try again with [the latest beta](https://beta.rclone.org) and if it is still a problem open a new issue with logs - thanks!

**Comment by arthurhanlon** [comment]
It was just hanging, nothing reflected int he logs. Now running the following:

rclone v1.42-025-g25ec7f5cβ
- os/arch: freebsd/amd64
- go version: go1.10.1

The process now exits with error code 7 which I presume is correct?

**Comment by ncw** [comment]
> It was just hanging, nothing reflected int he logs

OK

>  Now running the following:
> The process now exits with error code 7 which I presume is correct?

Yes it is now working.  I think the fixes I put in while making the `--max-transfer` flag have fixed your issue too.

**Comment by ncw** [comment]
I think this is now working as expected so I'm going to close this.
