### ISSUE TITLE
rclone move recreates folders even when empty

### ISSUE THREAD

**Issue by JRWR** [ncw/rclone#2869]
for the rclone move command every time it goes to upload it remakes the directory tree on the remote

My current command line is

`rclone move -vv --checkers=50 --transfers=40 --drive-chunk-size=64M --stats=10s --no-traverse --exclude .\* /home12/jrwr/incoming/ google:/incoming/`

and outputs this: 
```
2018/12/28 01:43:37 DEBUG : tumblr2-test/pietja: Making directory
2018/12/28 01:43:37 DEBUG : tumblr-static-test: Making directory
2018/12/28 01:43:37 DEBUG : tumblr2-test: Making directory
2018/12/28 01:43:37 DEBUG : tumblr-static-test/JRWR: Making directory
2018/12/28 01:43:37 DEBUG : tumblr2-test/DLoader: Making directory
2018/12/28 01:43:37 DEBUG : tumblr2-test/SUNDAY: Making directory

```

with directories with a boatload of subdirectories, it causes a ton of API calls, (Thanks for adding in no-traverse!) I also noticed that if you use cache not on top of mount, these mkdir command clean out the file cache causing too many misses. now what I expected was that it could check if the path existed and if not to make the path, but not remake the folders every single time.

**Comment by ncw** [comment]
Yes I think this a problem.  It is working as designed but it isn't what users expect!

This was introduced in #1837 by  d758e1908ee679948f0503cb6b961a4d67bc8491 to copy empty directories.

However if you filter all the files out then rclone thinks you have lots of empty directories and creates them all.

Perhaps a compromise would be to skip making the empty directories completely if any filtering is active?

What do you think? @JRWR and also @ishuah since you wrote that original code?

**Comment by ncw** [comment]
I think your problem might be different to the one above...

You have lots of empty directories in the source already...

What you could do is add `--delete-empty-src-dirs` to the `rclone move` command - this will remove the empty source directories.  (Or run `rclone rmdirs` before the move).

Maybe you are right a flag not to create empty directories for `rclone sync/copy/move` would be the right thing.

**Comment by JRWR** [comment]
Well the interesting thing is, the dirs Exist already on the source, but it just keeps remaking them. but ya, a flag to ignore empty dirs syncing to the remote

**Comment by Dave3o3** [comment]
> Maybe you are right a flag not to create empty directories for `rclone sync/copy/move` would be the right thing.

If this applies even when using filters, it would help a lot! :)

**Comment by wlerin** [comment]
I think the right thing would be a flag *to* create empty directories. While I can see the use for it, I can't imagine why that should be the default behaviour.

**Comment by mattatgiinsure** [comment]
Recreating empty directories on `rclone copy` seems to invalidate the advice in the `copy` documentation:

> See the --no-traverse option for controlling whether rclone lists the destination directory or not. Supplying this option when copying a small number of files into a large destination can speed transfers up greatly.

> For example, if you have many files in /path/to/src but only a few of them change every day, you can to copy all the files which have changed recently very efficiently like this:

> rclone copy --max-age 24h --no-traverse /path/to/src remote:

I'm watching `rclone copy --max-age ... --no-traverse` take a long time to recreate directories unnecessarily.
