### ISSUE TITLE
Just to thank you for this awesome application and to glad you for all efforts!

### ISSUE THREAD

**Issue by bunset** [ncw/rclone#288]
Hi,
I am a mac user with ACD unlimited and I was using GoodSync while it was nearly impossible to use because, it was very slow, hours, to wait until analyze process detects which files to backup and later, it had mistakes with datetime of files comparison from acd with local. After several support tickets I was desperate with this this program or with ACD, and with official acd program for mac desktop, which is weird and primitive. I didn't know what to do then, ...but looking for some more deep on goole with terms 'sync amazon cloud drive' , second page of results, and Here you are!. I discover your project, I installed it with some patience and carefully, and it works!. I started to use. 
After 1 week and half of use everyday, and with big some 1,5TB backups with thousands of photos and videos. I just have good words for rclone project. I am now creating lauchd plists to cron backups properly in El Capitan, and creating sh files to starts my backups at intervals and when a filesystem is mounted to let me do backups when usb drivers are connected. I have log files saved for every backup and all is working very well.
The performance is really fast and good with optic fiber internet in my case from Spain, awesome experience. 
I would like to tell you how good and valuable is your project, efficient team and specials thanks to Nick for being the 'chef' of all this magic of code.
Continue ahead, you are the best!
Best regards,
David

**Comment by ncw** [comment]
Thanks you very much for the kind words and I'm glad you are enjoying rclone.

-- Nick
