### ISSUE TITLE
Add a `tar` command to output directory as tar compatible format

### ISSUE THREAD

**Issue by QuantumGhost** [ncw/rclone#2891]
#### What is your current rclone version (output from `rclone version`)?

```
rclone v1.45
- os/arch: darwin/amd64
- go version: go1.11.2
```

#### What problem are you are trying to solve?

I'm trying to migrating files from Dropbox to Onedrive. I first tried `rclone copy`. However, some files were not copied due to [filename restrictions of Onedrive](https://v.gd/Gr0sBU) (more specifically, some filenames contain `:`). I have to compress all the files in the directory as zip and then copy the archive to Onedrive.

#### How do you think rclone should be changed to solve that?

If `rclone` can have a command `tar` and output tar compatible format, I can just pipe `rclone tar OLD_REMOTE:OLD_PATH | gzip |  rclone rcat NEW_REMOETE:NEW_PATH/archive.tar.gz`.

**Comment by QuantumGhost** [comment]
Yep, thanks.

**Comment by dckc** [comment]
Please label this as **duplicate** to save others from thinking it's done, like I did :)
