### ISSUE TITLE
Feature request b2-disable-checksum

### ISSUE THREAD

**Issue by samofe** [ncw/rclone#2892]
#### Output of `rclone version`
rclone v1.45
- os/arch: windows/amd64
- go version: go1.11

#### Describe the issue
Requesting the --b2-disable-checksum option for transfer of very large files (1 TB) that can take > 24 hours to hash before transfer starts, as discussed in this forum topic: https://forum.rclone.org/t/hashing-during-upload/7433
For non-encrypted files not having SHA1 on the file might be an acceptable tradeoff for the speed of transfer gained, so should be okay and desirable for some users to have this option.

**Comment by samofe** [comment]
I would love to, but I have no experience with the project and in fact have just joined github. It would take too long for me to get up to speed to be of any use. Very sorry about that but to make this request is all I can do at the moment.

**Comment by didil** [comment]
is this issue done now that the pull request b2: added disable sha1sum flag #2927 is merged  ?

**Comment by ncw** [comment]
I've merged this to master now which means it will be in [the latest beta](https://beta.rclone.org) in 15-30 mins and released in v1.46
