### ISSUE TITLE
Can't set tier with crypt backend

### ISSUE THREAD

**Issue by micbase** [ncw/rclone#2895]
#### What is the problem you are having with rclone?
I'm using crypt backend with Azure Blob, I think Azure Blob backend supports SetTier feature, but crypt doesn't pass it though. I can't set the tier from archive to cool, so I can't really retrieve the file. I guess I can grab the encrypted path, and set tier from there, but it's not convenient, and requires some scripting. 

#### What is your rclone version (output from `rclone version`)
1.45

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Ubuntu Server 18.04.1, 64 bit

####  Which cloud storage system are you using? (eg Google Drive)
Azure Blob

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone settier Cool encrypted_azure_blob:/file

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
2019/01/05 13:04:43 DEBUG : rclone: Version "v1.45" starting with parameters ["rclone" "settier" "Cool" "encrypted_azure_blob:/file" "-vv"]
2019/01/05 13:04:43 DEBUG : Using config file from "/root/.config/rclone/rclone.conf"
2019/01/05 13:04:45 Failed to settier: Remote encrypted_azure_blob does not support settier

**Comment by ncw** [comment]
This requires a wrapper for the SetTier function in the crypt backend....

I think the wrapper Fses require some tests to make sure they do wrap the things they are supposed to too.

**Comment by sandeepkru** [comment]
I'll take a look on this and fix it

**Comment by ncw** [comment]
> I'll take a look on this and fix it

Thank you :-)

**Comment by ncw** [comment]
Here is a beta with this implemented - please give it a go!

https://beta.rclone.org/branch/v1.46.0-112-g716bb755-fix-2895-optional-methods-beta/ (uploaded in 15-30 mins)

**Comment by ncw** [comment]
I've merged this to master now which means it will be in [the latest beta](https://beta.rclone.org) in 15-30 mins and released in v1.48
