### ISSUE TITLE
"Failed to create file system for "remote:": Didn't find section in config file"

### ISSUE THREAD

**Issue by nfshr** [ncw/rclone#290]
rclone was set up as advised in the docs via auto-config for google-drive (choice 9, "drive"). Set up went ok and token was received. Config was left at default when possible. Now i get the following err when trying to connect:

$ rclone ls remote:
2016/01/10 19:16:52 Failed to create file system for "remote:": Didn't find section in config file

Any Ideas why this happens? Couldn't find anything in the docs/Google.

OS: Arch; rclone: community/rclone 1.26-1

**Comment by klauspost** [comment]
Replace `remote` with the name you gave your drive.

Use `rclone config` to see the name of your remote.

**Comment by nfshr** [comment]
Oh, ok, thx! :)

**Comment by venkatnaidu** [comment]
rclone installed ubuntu . when i run rclone lsd remote:     
giving this error 
Failed to create file system for "remote:": Didn't find section in config file
Current remotes:

Name                 Type
====                 ====
test-wed-bulk        s3
wed-bulk-upload      s3

venkatnaidu@ecadmin-Vostro-460:~$ rclone ls test-wed-bulk:
2016/03/30 16:20:26 S3 bucket : Can't list objects at root - choose a bucket using lsd

Transferred:            0 Bytes (   0.00 kByte/s)
Errors:                 1
Checks:                 0
Transferred:            0
Elapsed time:           0

**Comment by xinmeng1** [comment]
thx

**Comment by Aireezz** [comment]
I'm having this same issue yet I have specified it with the name I gave the drive.

Drive name = encrypted
Files located under

Main folder -Media
 sub folders -
                    Tv
                    Movies
                    Music

i run this command            rclone mount encrytped:media /mnt/googledrive &


I have also tried specifying a sub folder like this.   rclone mount encrytped:media/tv /mnt/googledrive &

No luck, any thoughts?

**Comment by Flash619** [comment]
I have the exact same issue when using a crypt remote type. If I try secret:myfolder/ It get "didn't find section in config file".

**Comment by razzmatazzrr** [comment]
What is this part in the rclone config about?

service_account_file> /home/foo/myJSONfile.json # This is where the JSON file goes!

Can I leave this blank? I've set a root_folder_id. All I want to do is copy and delete jpgs from a folder on my raspberry pi, however when I try run this...

rclone -v move /home/pi/timelapse remote:tent --delete-after --include *.jpg --include *.log

then it tells me, "Failed to create file system for "remote:tent": didn't find section in config file".

I'd love to know how to sync files to my google drive. Trying to make a timelapse. I don't want to run out of storage on my pi halfway through the timelapse.

**Comment by henriquebs12** [comment]
> Replace `remote` with the name you gave your drive.
> 
> Use `rclone config` to see the name of your remote.

Your simple comment probably saved thousand of users. Poor UX writing from the rclone documentation site. If it had some examples over there, it shouldn't happen. Sometimes devs think everbody think the same way they do. Thanks for the help.

**Comment by Inambe** [comment]
For me it was that I was running `rclone ls google-drive` and not `rclone ls google-drive:/`

**Comment by xuexxd** [comment]
Yes,i have solved the same problem. The wiki documentation is very unclear

**Comment by ncw** [comment]
Always happy to take fixes to the docs if anyone would like to do them.

Note the docs are here - https://github.com/rclone/rclone/tree/master/docs/content and you can click the edit icon on the docs and submit a fix all from your browser :-)

**Comment by SephReed** [comment]
Derp.  `Dropbox: !== DropBox:`

**Comment by Feriman22** [comment]
I had the same problem with MEGA. The problem was that I updated the rclone and the new version does not support MEGA Cloud.

The solution is to downgrade the existing version:

```
wget https://github.com/rclone/rclone/releases/download/v1.59.2/rclone-v1.59.2-linux-arm64.deb -P /tmp
sudo dpkg --install /tmp/rclone-v1.59.2-linux-arm64.deb
rm -f /tmp/rclone-v1.59.2-linux-arm64.deb
```

And stay on this version:
`sudo apt-mark hold rclone`

**Comment by sebastianaa92** [comment]
> Replace `remote` with the name you gave your drive.
> 
> Use `rclone config` to see the name of your remote.

i'm stupid hahaha it was this simple... ty bro

**Comment by mirekphd** [comment]
I think this bug is caused by using an undefined name "remote", so the simplest solution is not using it, like this:
```
rclone serve webdav "/tmp" 
``` 
(instead of the failing `rclone serve webdav "remote:/tmp"`)
