### ISSUE TITLE
Doubts about transfer speed

### ISSUE THREAD

**Issue by ffelipek07** [ncw/rclone#2900]
I am performing a sync from an FTP source location to a s3 target. With these parameters below, but the transfer rate is very low, below 3 Mb / s could you help me?

Command applied:

/usr/bin/rclone sync -uv --timeout=600s --drive-chunk-size=512M --drive-upload-cutoff=1G --buffer-size=1G --ignore-existing --transfers=10 --checkers=64 --ignore-size --progress source: destination:bucket-1502971486 --log-file /var/log/rclone/sync_storage-PROD.log

Version Rclone
rclone v1.45
- os/arch: linux/amd64
- go version: go1.11.2

Thank you

**Comment by ncw** [comment]
> I am performing a sync from an FTP source location to a s3 target. With these parameters below, but the transfer rate is very low, below 3 Mb / s could you help me?

How are you measuring the transfer?

Rclone measures transfers in Mega Bytes /s  normally.

Try transferring from the FTP server to your local disk - what sort of speed do you get there?

> --drive-chunk-size=512M --drive-upload-cutoff=1G

Remove these options as you aren't using the google drive backend

> --buffer-size=1G 

This seems excessive?  1GB of memory per transfer?  I'd remove it completely as the default of 16MB works quite well.

**Comment by ncw** [comment]
Transferred to forum: https://forum.rclone.org/t/slow-speed-transfer-ftp-to-s3/8234
