### ISSUE TITLE
rclone sync --newermt "yyyy-mm-dd HH:mm:ss"

### ISSUE THREAD

**Issue by cores-system** [ncw/rclone#2901]
Hello, thanks for the great software.
Unfortunately, I could not find an analogue of "-newermt" as in the https://ru.wikipedia.org/wiki/Find command

I want to use the "rclone sync" command not only to keep the current copy of the data, but also a copy of the data for a certain period of time.

Example:
`` `
Start time: 2019-01-08
rclone sync /infolder remote:/master
rclone sync --newermt "2019-01-07 00:00:00" /infolder remote:/ 2019-01-07

Start time: 2019-01-09
rclone sync /infolder remote:/master
rclone sync --newermt "2019-01-08 00:00:00" /infolder remote:/ 2019-01-08

Start time: 2019-01-10
rclone sync /infolder remote:/master
rclone sync --newermt "2019-01-09 00:00:00" /infolder remote:/ 2019-01-09
`` `

That is, the current copy of the data is stored in "remote:/master", and the files that have been changed in a certain day are stored in folders 2019-01-0 *.

**Comment by ncw** [comment]
You can make this work with these flags I think with a bit of work.

      --max-age duration    Only transfer files younger than this in s or suffix ms|s|m|h|d|w|M|y (default off)
      --min-age duration    Only transfer files older than this in s or suffix ms|s|m|h|d|w|M|y (default off)

**Comment by cores-system** [comment]
@ncw , Thank you, but this is not exactly.
I found another way, the topic can be closed.

```
find /infolder -type f -newermt "2019-09-01 00:00:00" ! -newermt "2019-10-01 00:00:00" | sed "s%/infolder%%g" > files-from.txt
	
if [[ -f "files-from.txt" && -s "files-from.txt" ]]; then 
   rclone copy --files-from files-from.txt /infolder remote:/`date +%d-%m-%Y --date='-1 day'`
fi
```
