### ISSUE TITLE
update flag comment for checksum to avoid confusion

### ISSUE THREAD

**Issue by calisro** [ncw/rclone#2903]
As seem here, there is always confusion on crypts about checksums and the --checksum flag which can cause people to believe its using checksum when they have in fact made things worst by disabling it.

https://forum.rclone.org/t/s3-takes-too-long-checksum-misses-excel-files/8269/6

Propose to change the descriptions like this:

-c, --checksum Skip based on checksum & size, not mod-time & size

to

-c, --checksum Skip based on checksum & size, not mod-time & size. If checksums don't exist(crypt), then just size.

Alternatively (or in addition to), warn the user in the log based on the remote.

**Comment by ncw** [comment]
Great idea

How about

    -c, --checksum Skip based on checksum (if available) & size, not mod-time & size.

A warning in the log is a great idea, so if someone started a sync with `--checksum` on a remote with no hashes (or maybe with no hashes in common for the source and destination) it could log

    --checksum in use but source and destination have no hashes in common - falling back to --size-only

Something like that?

This should probably be a NOTICE log level so it appears without `-v`.

Sound OK?

**Comment by calisro** [comment]
I think that's perfect.

**Comment by ncw** [comment]
I've done that now - find it in [the latest beta](https://beta.rclone.org) in 15-30 mins and in 1.46 - thanks for suggesting it :-)

**Comment by calisro** [comment]
Thanks as always
