### ISSUE TITLE
Batch Local and Remote and/or password batch

### ISSUE THREAD

**Issue by cyberpunkbln** [ncw/rclone#2904]
Hello,

at the moment all are fine and i use rclone under windows to mount an encrypted remote. This remote has subdirectorys. And i want this subdirectorys mount once per directory Remote:/User/User/Docs,Pics and so on, under a special folder called Enc under Docs/Pics and so on.

At the moment i mount this once under a Local-Directory and make a junction from Doc/Pics...Enc to this folder. All its fine.

But i want to use the Directory-Tree in the encrypted-local-volume directly with 2 Feature-Requests. Or one when i think about it;). I don't want to give rclone the password for every subdir in the remote that i want mount in the local.

1. The logically Feature: Make an rclone command to put the pw in the memory or leave it stay for the following batch-commands:

rclone.exe input_password ********
rcclone.exe batch command for every mount from the Remote:/SubDir to the Local:SubDir.
rclone.exe remove_password

But his feature is an pure memory and logistic overload;).

2. Some mechanism that make batch mounts possible in one rclone instance (my prefered feature).
With an extra batch-file where like an csv remote and local are inserted or as an command extension

rclone.exe mount --csv-file *.rclone.batch --other options

rclone.exe mount -batch=remote1,local1 -batch="remote2","local2" or and so on.

But its not important, i like the mechanism that rclone only the local mounted folder delete after closing rclone;) and i can use my dir-structure in the remote.

thx

**Comment by ncw** [comment]
> The logically Feature: Make an rclone command to put the pw in the memory or leave it stay for the following batch-commands:

For the batch password part you want the windows equivalent of this

```
read -s RCLONE_CONFIG_PASS
export RCLONE_CONFIG_PASS
```

I think this might work (untested).  It reads the password into the environment variable and rclone will pick it up from there so no need to enter it multiple times.

```
set /p RCLONE_CONFIG_PASS=Password:
```

> Some mechanism that make batch mounts possible in one rclone instance (my prefered feature).
With an extra batch-file where like an csv remote and local are inserted or as an command extension

Hmm, if mounting was supported via the [rc](https://rclone.org/rc/) then this would be achievable.

**Comment by cyberpunkbln** [comment]
thx cool Environment-Variable:), with this i can make me an special rclone-shell where i can access all my rclone-mount-scripts (batchys:)). This resolve the main problem of my issue very well and i can close this but one last question:

Can one rclone-service/instance handle multiple mounting cmds or is it system important that only one instance can excactly handle one mount cmd? I my opinion is think is it once encryption and multiple call FUSE-Driver to mount?

**Comment by ncw** [comment]
> thx cool Environment-Variable:

:-)




> Can one rclone-service/instance handle multiple mounting cmds

Not at the moment.

You will need one rclone per mount.
