### ISSUE TITLE
Feature Request: Support remote 1fichier

### ISSUE THREAD

**Issue by acs-ferreira** [ncw/rclone#2908]
API: https://1fichier.com/api.html
An example in GO: https://github.com/cryptix/go-fichier

10€/yr for unlimited cloud storage: https://1fichier.com/tarifs.html?lg=en
_(I work with them for 5yrs and i store more than 20TB)_

**Comment by ncw** [comment]
Anyone like to help with this?

If you'd like to see this then please +1 the above!

**Comment by acs-ferreira** [comment]
Sorry never learned (yet) Golang, otherwise would be glad to write this.

Actually, i'm trying to use their (very limited, only uploads to root and no `mkdir` or other things...) FTP but i get an error at every upload with `rclone`:

`Failed to copy: update getinfo: object not found`

No problem with any FTP client (like Filezilla or Cyberduck).

**Comment by ncw** [comment]
@acs-ferreira wrote:
> Can provide an FTP account at their end for testing if needed.

That would be very useful :-)

Can you email details to nick@craig-wood.com with subject "rclone issue 2908" - thanks :-)

**Comment by acs-ferreira** [comment]
@ncw details had been sent.

**Comment by ncw** [comment]
> Actually, i'm trying to use their FTP (very limited, only uploads to root and no `mkdir` or other things...) but i get an error at every upload with `rclone`

In our email exchange we established that the 1fichier FTP acts very much like an anonymous FTP. The `LIST dir` command is broken and files can't be downloaded and directories can't be made.  Those limitations made us think that making rclone work with the 1fichier FTP wouldn't be easily possible.

**Comment by acs-ferreira** [comment]
I believe this is not true as the API does not use the FTP at all. The FTP is provided by them only if the API or the Web upload can't be used.

The API is actually used trough PHP and it works perfectly fine. :blush:

**Comment by ncw** [comment]
> So, use Rclone with the FTP will not work (one should use cURL instead) but Rclone with their API _should_ work fine.

That is exactly what I meant, apologies if it wasn't clear :-)

**Comment by bingoxo** [comment]
@ncw  can you look at this please : https://gitlab.com/BylonAkila/astreamfs and implement it with 1fichier (and uptobox)

**Comment by JannickNijholt** [comment]
Would be great if this could be implemented!

**Comment by ncw** [comment]
First beta is here of the 1ficher backend if anyone wants to have a go:

https://beta.rclone.org/branch/v1.48.0-031-ga8f7dbed-fichier-beta/ (uploaded in 15-30 mins)

**Comment by ncw** [comment]
I've merged this to master now which means it will be in [the latest beta](https://beta.rclone.org) in 15-30 mins and released in v1.49

Testing and bug reports appreciated!

**Comment by acs-ferreira** [comment]
Can this mounted with a classic `rclone mount` ?

**Comment by ncw** [comment]
> Can this mounted with a classic `rclone mount` ?

Sure!
