### ISSUE TITLE
fs/oprations_test.go assumes fixed order of execution

### ISSUE THREAD

**Issue by klauspost** [ncw/rclone#291]
It seems like https://github.com/ncw/rclone/blob/master/fs/operations_test.go assumes a fixed order of execution to work.

I am 95% certain that I read somewhere, that assuming a fixed execution order is a bad practice, and the execution order may very well change in the future. Furthermore it of course breaks `-test.run=Something`, since each test isn't set up separately.

**Comment by ncw** [comment]
Yes you are correct.  The `fstest/fstests/fstests.go` are the same.  One of things I'd like to fix but have never got round to it!

**Comment by klauspost** [comment]
Awesome work!

**Comment by ncw** [comment]
Thanks! I spent a lot of time on them trying to make them easy to understand in isolation. I spent even more time fixing them to work with ACD which has a rather idiosyncratic notion of eventual consistently in its directory listing!
