### ISSUE TITLE
Make stats the same format when a transfer has not started as when it has started

### ISSUE THREAD

**Issue by ealgase** [ncw/rclone#2910]
#### What is the problem you are having with rclone?

When a file is copied at the exact moment the minutely progress report is shown (with `-v`), the formatting of the minutely progress report is messed up.

#### What is your rclone version (output from `rclone version`)

v1.44 (but the code for this has not changed in v1.45)

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

Linux, 64 bit

####  Which cloud storage system are you using? (eg Google Drive)

Google Drive

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

`rclone move Folder Drive:Folder -vv --ignore-existing`

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

The log is incredibly long (this was a transfer of hundreds of files), here is the relevant portion:
```
2019/01/13 21:25:12 DEBUG : pacer: Rate limited, sleeping for 2.899432105s (2 consecutive low level retries)
2019/01/13 21:25:12 DEBUG : pacer: low level retry 2/10 (error googleapi: Error 403: Rate Limit Exceeded, rateLimitExceeded)
2019/01/13 21:25:14 DEBUG : pacer: Rate limited, sleeping for 4.627803471s (3 consecutive low level retries)
2019/01/13 21:25:14 DEBUG : pacer: low level retry 3/10 (error googleapi: Error 403: Rate Limit Exceeded, rateLimitExceeded)
2019/01/13 21:25:16 DEBUG : pacer: Resetting sleep to minimum 10ms on success
2019/01/13 21:25:16 INFO  : Trailer Theme (Livestream Version) - Sonic Mania WmjZPVkyJ4E.mkv: Copied (new)
2019/01/13 21:25:16 INFO  : 
Transferred:        1.341G / 8.603 GBytes, 16%, 1.086 MBytes/s, ETA 1h54m5s
Errors:                 0
Checks:              8868 / 8868, 100%
Transferred:          156 / 823, 19%
Elapsed time:     21m3.9s
Checking:
 * Trailer Theme (Livestream Version) - Sonic Mania WmjZPVkyJ4E.mkv
Transferring:
 *     Trailer Theme (In-Ga…ania hTBnJ3wqtZ0.mkv: 54% /24.659M, 458.308k/s, 24s
 *     Trailer Theme (Lives…ania OfVIquQcFsw.mkv: 100% /2.426M, 225.787k/s, 0s
 *     Trailer Theme (Radio…ania Stc-DmYW_cU.mkv:  0% /16.901M, 0/s, -
 * Trailer Theme (Livestream Version) - Sonic Mania WmjZPVkyJ4E.mkv

2019/01/13 21:25:16 INFO  : Trailer Theme (Livestream Version) - Sonic Mania WmjZPVkyJ4E.mkv: Deleted
2019/01/13 21:25:17 INFO  : Trailer Theme (Livestream Version) - Sonic Mania OfVIquQcFsw.mkv: Copied (new)
2019/01/13 21:25:17 INFO  : Trailer Theme (Livestream Version) - Sonic Mania OfVIquQcFsw.mkv: Deleted
2019/01/13 21:25:17 DEBUG : Trailer Theme (Radio Version) - Sonic Mania Stc-DmYW_cU.mkv: Sending chunk 0 length 8388608
```

The last line of the progress report isn't indented and doesn't show `100% /FILESIZE, SPEED/s, 0s`.

**Comment by ncw** [comment]
> The last line of the progress report isn't indented and doesn't show 100% /FILESIZE, SPEED/s, 0s.

That means the transfer hasn't started yet.

However I've been meaning to fix it because the indented/not-indented nature looks really terrible with `--progress` where you see the files jumping around all the time.

I've adjusted the subject, and I'll fix in a moment!

**Comment by ncw** [comment]
I've fixed this here

https://beta.rclone.org/v1.45-091-g5990573c-beta/ (uploaded in 15-30 mins)

It will be in [the latest beta](https://beta.rclone.org) at the same time and in v1.46 when it is released

**Comment by ealgase** [comment]
Great, thank you!
