### ISSUE TITLE
fuse: panic in handler for Rename - runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by xkvnn** [ncw/rclone#2911]
#### What is the problem you are having with rclone?
The disk mounted on Ubuntu Server. Rename file from Windows via samba service.

#### What is your rclone version (output from `rclone version`)
v1.45

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Ubuntu Server 18.04 64 bit

####  Which cloud storage system are you using? (eg Google Drive)
Google Drive

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
> rclone mount drive: /mnt/GDrive1/ --allow-non-empty --allow-other -no-modtime --dir-cache-time 1h

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

```
2019/01/14 13:06:56 DEBUG : Media/: Rename: oldName="01 - 1080p.mkv", newName="01.mkv", newDir=Media/
2019/01/14 13:06:56 NOTICE: Media/01 - 1080p.mkv: Not moving as --dry-run
2019/01/14 13:06:56 DEBUG : Media/01 - 1080p.mkv: Updating file with <nil> 0xc0003af400
2019/01/14 13:06:56 DEBUG : Media/: >Rename: err=<nil>
2019/01/14 13:06:56 fuse: panic in handler for Rename [ID=0x230 Node=0x10 Uid=1000 Gid=1004 Pid=22603] from "01 - 1080p.mkv" to dirnode 0x10 "01.mkv": runtime error: invalid memory address or nil pointer dereference
goroutine 620 [running]:
github.com/ncw/rclone/vendor/bazil.org/fuse/fs.(*Server).serve.func2(0x13a8f40, 0xc0000726c0, 0xc00048fef8, 0xc00048fe77)
        /home/travis/gopath/src/github.com/ncw/rclone/vendor/bazil.org/fuse/fs/serve.go:857 +0x1ac
panic(0x1066d80, 0x1cf2f20)
        /home/travis/.gimme/versions/go1.11.2.linux.amd64/src/runtime/panic.go:513 +0x1b9
github.com/ncw/rclone/vfs.(*File).rename.func1(0x1126500, 0xc00063b860)
        /home/travis/gopath/src/github.com/ncw/rclone/vfs/file.go:132 +0x267
github.com/ncw/rclone/vfs.(*File).rename(0xc0003af400, 0xc000520360, 0xc0002ceb00, 0x1c, 0xc000454580, 0x1)
        /home/travis/gopath/src/github.com/ncw/rclone/vfs/file.go:148 +0x22f
github.com/ncw/rclone/vfs.(*Dir).Rename(0xc000520360, 0xc0004f2270, 0x24, 0xc0002ceb00, 0x1c, 0xc000520360, 0x1, 0xc00063b830)
        /home/travis/gopath/src/github.com/ncw/rclone/vfs/dir.go:569 +0x712
github.com/ncw/rclone/cmd/mount.(*Dir).Rename(0xc0000b00b0, 0x13aa840, 0xc0004115c0, 0xc0000726c0, 0x139d900, 0xc0000b00b0, 0x1, 0x1)
        /home/travis/gopath/src/github.com/ncw/rclone/cmd/mount/dir.go:166 +0x30f
github.com/ncw/rclone/vendor/bazil.org/fuse/fs.(*Server).handleRequest(0xc0001343c0, 0x13aa840, 0xc0004115c0, 0x139d900, 0xc0000b00b0, 0xc000507f80, 0x13a8f40, 0xc0000726c0, 0xc00048fef8, 0x0, ...)
        /home/travis/gopath/src/github.com/ncw/rclone/vendor/bazil.org/fuse/fs/serve.go:1335 +0x228b
github.com/ncw/rclone/vendor/bazil.org/fuse/fs.(*Server).serve(0xc0001343c0, 0x13a8f40, 0xc0000726c0)
        /home/travis/gopath/src/github.com/ncw/rclone/vendor/bazil.org/fuse/fs/serve.go:878 +0x410
github.com/ncw/rclone/vendor/bazil.org/fuse/fs.(*Server).Serve.func1(0xc0001343c0, 0x13a8f40, 0xc0000726c0)
        /home/travis/gopath/src/github.com/ncw/rclone/vendor/bazil.org/fuse/fs/serve.go:425 +0x6e
created by github.com/ncw/rclone/vendor/bazil.org/fuse/fs.(*Server).Serve
        /home/travis/gopath/src/github.com/ncw/rclone/vendor/bazil.org/fuse/fs/serve.go:423 +0x31e
2019/01/14 13:06:56 DEBUG : Media/01 - 1080p.mkv: Open: flags=OpenReadOnly+0x20000
```

Updated by ncw to Fix formatting

**Comment by ncw** [comment]
Can you see if you can replicate with [the latest beta](https://beta.rclone.org)?  There have been quite a few VFS fixes since 1.45.

Is this a repeatable problem?

How did you replicate it - just with the rename?

Is your config just a google drive? Or are you using cache?

Did you edit the log?  In this log

    Media/01 - 1080p.mkv: Updating file with 0xc0003af400

I'd expected to see an object name or `<nil>` before the hex number.  Maybe the `<nil>` got eaten somewhere as it looks like it did in a different log.

What it looks like is that in this code `operations.Move` returned a `nil` object, which most likely was returned by the drive backend server side move code

```go
	renameCall := func() error {
		newPath := path.Join(destDir.path, newName)
		dstOverwritten, _ := f.d.f.NewObject(newPath)
		newObject, err := operations.Move(f.d.f, dstOverwritten, newPath, f.o)
		if err != nil {
			fs.Errorf(f.Path(), "File.Rename error: %v", err)
			return err
		}
		// Update the node with the new details
		fs.Debugf(f.o, "Updating file with %v %p", newObject, f) // Media/01 - 1080p.mkv: Updating file with 0xc0003af400
		// f.rename(destDir, newObject)
		f.mu.Lock()
		f.o = newObject
		f.d = destDir
		f.leaf = path.Base(newObject.Remote()) // PANIC - newObject nil here?????
		f.pendingRenameFun = nil
		f.mu.Unlock()
		return nil
	}
```

If you can replicate this easily, can you try with `-vv --dump bodies`.  Don't read or write any files otherwise the log will be too big, just try to do the rename!

Thanks

**Comment by ncw** [comment]
Just looked at the raw source of your post, I can see

     Media/01 - 1080p.mkv: Updating file with <nil> 0xc0003af400

Which confirms the `nil` object hypothesis.  Please answer the questions above if you can!

**Comment by ncw** [comment]
Ah I see the problem

> 2019/01/14 13:06:56 NOTICE: Media/01 - 1080p.mkv: Not moving as --dry-run

So it looks like you had --dry-run set, so rclone didn't actually do the move.  That is why `operations.Move` returned `nil` and explains the panic fully.

Assuming that you can't replicate this without `--dry-run` then this is the fix

https://beta.rclone.org/v1.45-090-gbd11d3cb-beta/ (uploaded in 15-30 mins)

Which will be in [the latest beta](https://beta.rclone.org) in 15-30 mins too and in v1.46 when released.

**Comment by xkvnn** [comment]
_I don't run any command with `--dry-run`_

#### Is this a repeatable problem?
Yes, It always.

#### How did you replicate it - just with the rename?
- Mount with command
`rclone mount drive: /mnt/GDrive1/ --allow-non-empty --allow-other -no-modtime --dir-cache-time 1h -vv --dump bodies`
- Run `cd` to folder and move file
`mv "[KOGA] Acchi Kocchi - 01 - 1080p.mkv" "[KOGA] Acchi Kocchi - 01.mkv"`

#### Is your config just a google drive? Or are you using cache?
Yes, just Google Drive. I don't use with cache config

#### Did you edit the log? In this log
`Media/01 - 1080p.mkv: Updating file with 0xc0003af400`
Have `<nil>` before the hex number. And now I realize that Markdown removes it.

_I've just test with latest beta (https://beta.rclone.org/v1.45-090-gbd11d3cb-beta/) and still can't rename files._
```2019/01/14 20:57:36 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2019/01/14 20:57:36 DEBUG : Media/Anime/Pack_01/Acchi Kocchi/S01/: >Lookup: node=<nil>, err=no such file or directory
2019/01/14 20:57:36 DEBUG : Media/Anime/Pack_01/Acchi Kocchi/S01/: Lookup: name="[KOGA] Acchi Kocchi - 01 - 1080p.mkv"
2019/01/14 20:57:36 DEBUG : Media/Anime/Pack_01/Acchi Kocchi/S01/: >Lookup: node=Media/Anime/Pack_01/Acchi Kocchi/S01/[KOGA] Acchi Kocchi - 01 - 1080p.mkv, err=<nil>
2019/01/14 20:57:36 DEBUG : Media/Anime/Pack_01/Acchi Kocchi/S01/[KOGA] Acchi Kocchi - 01 - 1080p.mkv: Attr: 
2019/01/14 20:57:36 DEBUG : Media/Anime/Pack_01/Acchi Kocchi/S01/[KOGA] Acchi Kocchi - 01 - 1080p.mkv: >Attr: a=valid=1s ino=0 size=545186996 mode=-rw-rw-r--, err=<nil>
2019/01/14 20:57:36 DEBUG : Media/Anime/Pack_01/Acchi Kocchi/S01/: Lookup: name="[KOGA] Acchi Kocchi - 01.mkv"
2019/01/14 20:57:36 DEBUG : Media/Anime/Pack_01/Acchi Kocchi/S01/: >Lookup: node=<nil>, err=no such file or directory
2019/01/14 20:57:36 DEBUG : Media/Anime/Pack_01/Acchi Kocchi/S01/: Lookup: name="[KOGA] Acchi Kocchi - 01.mkv"
2019/01/14 20:57:36 DEBUG : Media/Anime/Pack_01/Acchi Kocchi/S01/: >Lookup: node=<nil>, err=no such file or directory
2019/01/14 20:57:36 DEBUG : Media/Anime/Pack_01/Acchi Kocchi/S01/: Rename: oldName="[KOGA] Acchi Kocchi - 01 - 1080p.mkv", newName="[KOGA] Acchi Kocchi - 01.mkv", newDir=Media/Anime/Pack_01/Acchi Kocchi/S01/
2019/01/14 20:57:36 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2019/01/14 20:57:36 DEBUG : HTTP REQUEST (req 0xc000136b00)
2019/01/14 20:57:36 DEBUG : GET /drive/v3/files?alt=json&fields=files%28id%2Cname%2Csize%2Cmd5Checksum%2Ctrashed%2CmodifiedTime%2CcreatedTime%2CmimeType%2Cparents%2CwebViewLink%29%2CnextPageToken&pageSize=1000&prettyPrint=false&q=trashed%3Dfalse+and+%28%271oKAT8KvJtv8W3qgum9yzn2NEwF1d2i_T%27+in+parents%29+and+%28name%3D%27%5BKOGA%5D+Acchi+Kocchi+-+01.mkv%27%29+and+mimeType%21%3D%27application%2Fvnd.google-apps.folder%27 HTTP/1.1
Host: www.googleapis.com
User-Agent: rclone/v1.45-090-gbd11d3cb-beta
Authorization: XXXX
Accept-Encoding: gzip

2019/01/14 20:57:36 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2019/01/14 20:57:37 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2019/01/14 20:57:37 DEBUG : HTTP RESPONSE (req 0xc000136b00)
2019/01/14 20:57:37 DEBUG : HTTP/1.1 200 OK
Transfer-Encoding: chunked
Alt-Svc: quic=":443"; ma=2592000; v="44,43,39,35"
Cache-Control: private, max-age=0, must-revalidate, no-transform
Content-Type: application/json; charset=UTF-8
Date: Mon, 14 Jan 2019 13:57:37 GMT
Expires: Mon, 14 Jan 2019 13:57:37 GMT
Server: GSE
Vary: Origin
Vary: X-Origin
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Xss-Protection: 1; mode=block

c
{"files":[]}
0

2019/01/14 20:57:37 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2019/01/14 20:57:37 NOTICE: Media/Anime/Pack_01/Acchi Kocchi/S01/[KOGA] Acchi Kocchi - 01 - 1080p.mkv: Not moving as --dry-run
2019/01/14 20:57:37 ERROR : Media/Anime/Pack_01/Acchi Kocchi/S01/[KOGA] Acchi Kocchi - 01 - 1080p.mkv: File.Rename rename failed: nil object returned
2019/01/14 20:57:37 ERROR : Media/Anime/Pack_01/Acchi Kocchi/S01/[KOGA] Acchi Kocchi - 01 - 1080p.mkv: Dir.Rename error: rename failed: nil object returned
2019/01/14 20:57:37 DEBUG : Media/Anime/Pack_01/Acchi Kocchi/S01/: >Rename: err=rename failed: nil object returned
2019/01/14 20:57:52 DEBUG : Google drive root 'khanh_tma': Checking for changes on remote
2019/01/14 20:57:52 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>```

**Comment by ncw** [comment]
Your log says you have got `--dry-run` set

> 2019/01/14 20:57:37 NOTICE: Media/Anime/Pack_01/Acchi Kocchi/S01/[KOGA] Acchi Kocchi - 01 - 1080p.mkv: Not moving as --dry-run

Maybe it is set in the environment?  What do you see if you do

    env | grep RCLONE

**Comment by xkvnn** [comment]
I only run with `rclone mount drive: /mnt/GDrive1/ --allow-non-empty --allow-other -no-modtime --dir-cache-time 1h -vv --dump bodies` and don't have any ENV set for rclone

**Comment by ncw** [comment]
> I only run with `rclone mount drive: /mnt/GDrive1/ --allow-non-empty --allow-other -no-modtime --dir-cache-time 1h -vv --dump bodies` and don't have any ENV set for rclone

Ah, ha!  I see the problem.  You've written `-no-modtime` (one dash) instead of `--no-modtime` (two dashes).  This means that rclone is intepreting this as combined single letter flags `-n`, `-o '-modtime'`.  `-n` being `--dry-run` and `-o` being a fuse option.

If you use `--no-modtime` instead, I think it will work as expected.

**Comment by xkvnn** [comment]
Ok, everything works fine now.
Sorry about my mistake.

**Comment by ncw** [comment]
> Ok, everything works fine now.
> Sorry about my mistake.

No worries.  It was a very subtle mistake and I'm suprised you didn't get an error from rclone - you just got unlucky that the `-n` flag is falid and the `-o` flag takes a parameter!
