### ISSUE TITLE
sync creates public listable bucket with --s3-acl=public-read

### ISSUE THREAD

**Issue by hyperknot** [ncw/rclone#2918]
#### What is the problem you are having with rclone?
The standard way of hosting a static website on S3 is to make the bucket private and upload files with public-read permissions.

For this, I'm using rclone sync with `--s3-acl=public-read`. This works well.

My problem is, that if the sync command creates the bucket (silently), then it becomes a public listable bucket when using `--s3-acl=public-read` for the synced files.

There are two concepts here, which are somehow mixed with rclone sync.
- bucket's policy
- the different files' policy within the bucket.

I believe a sync command's --s3-acl=public-read should only apply to the uploaded files.
I personally think that sync shouldn't create buckets, but that's probably a historical decision in rclone and will never change for backward compatibility.

I don't know what would be the best solution now, but at least printing a line about "Creating public readable bucket: {bucketname}" would be very important, in my opinion.

#### What is your rclone version (output from `rclone version`)
```
rclone v1.45
- os/arch: darwin/amd64
- go version: go1.11.2
```

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
macOS 10.14.2

####  Which cloud storage system are you using? (eg Google Drive)
AWS S3

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
`rclone sync --s3-acl=public-read`

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
```
2019/01/16 02:19:49 DEBUG : rclone: Version "v1.45" starting with parameters ["rclone" "sync" "--s3-region=eu-central-1" "-vv" "--s3-acl=public-read" "export/" "s3:pgmeteo.hyperknot.com"]
Enter configuration password:
password:
2019/01/16 02:19:52 DEBUG : Using config file from "/Users/user/.config/rclone/rclone.conf"
2019/01/16 02:19:53 DEBUG : pacer: Reducing sleep to 0s
2019/01/16 02:19:53 INFO  : S3 bucket pgmeteo.hyperknot.com: Waiting for checks to finish
2019/01/16 02:19:53 INFO  : S3 bucket pgmeteo.hyperknot.com: Waiting for transfers to finish
2019/01/16 02:19:54 INFO  : images/favicon.png: Copied (new)
2019/01/16 02:19:54 INFO  : css/skeleton.css: Copied (new)
2019/01/16 02:19:54 INFO  : css/normalize.css: Copied (new)
2019/01/16 02:19:54 INFO  : index.html: Copied (new)
2019/01/16 02:19:54 INFO  : Waiting for deletions to finish
2019/01/16 02:19:54 INFO  :
Transferred:   	   93.217k / 93.217 kBytes, 100%, 18.481 kBytes/s, ETA 0s
Errors:                 0
Checks:                 0 / 0, -
Transferred:            4 / 4, 100%
Elapsed time:          5s

2019/01/16 02:19:54 DEBUG : 13 go routines active
2019/01/16 02:19:54 DEBUG : rclone: Version "v1.45" finishing with parameters ["rclone" "sync" "--s3-region=eu-central-1" "-vv" "--s3-acl=public-read" "export/" "s3:pgmeteo.hyperknot.com"]
```

**Comment by hyperknot** [comment]
I agree. I think the improvements would be:
- log a line when a bucket is deleted
- log a line when a bucket is created, specifying the ACL name
- add `--s3-bucket-acl`

**Comment by hyperknot** [comment]
> Ah. What ACL would be appropriate here? If you make the bucket "private" can "public" objects still be read?

Yes, and that's the default of the aws cli.

**Comment by ncw** [comment]
> I agree. I think the improvements would be:
> 
> * log a line when a bucket is deleted
> * log a line when a bucket is created, specifying the ACL name
> * add `--s3-bucket-acl`

I've made these changes here - can you have a go?

https://beta.rclone.org/branch/v1.45-095-g3e41f7d7-fix-2918-bucket-acl-beta/ (uploaded in 15-30 mins)

**Comment by hyperknot** [comment]
The new build works perfectly! Is it a policy that nothing is logged without `-v`?

**Comment by hyperknot** [comment]
Then I think it's perfect as it is.

**Comment by ncw** [comment]
Thanks :-)

I'll close this now.

**Comment by ncw** [comment]
I've merged the code to master which will be in [the latest beta](https://beta.rclone.org) in 15-30 mins and in v1.46
