### ISSUE TITLE
rclone 1.45: rc memory leak

### ISSUE THREAD

**Issue by splitice** [ncw/rclone#2929]
#### What is the problem you are having with rclone?

Memory leak when uploading files with:

```
rclone rc operations/copyfile srcFs= srcRemote=/mnt/Media/large.foo dstFs=crypt: dstRemote=media/large.foo
```

Memory builds up and up with every file upload. Tested with large files (2-3GB each). Other operations including mkdir where performed between testing however on their own did not seem to leak memory.

Builds up to approx 4GB ram on my system, before it OOMs.

#### What is your rclone version (output from `rclone version`)

```
rclone v1.45
- os/arch: linux/amd64
- go version: go1.11.2
```

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

Ubuntu

```
Linux localhost 4.15.0-33-generic #36-Ubuntu SMP Wed Aug 15 16:00:05 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

####  Which cloud storage system are you using? (eg Google Drive)

Google Drive + Crypt

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

```
rclone rc operations/copyfile [...]
```

to an instance running with:

```
/usr/bin/rclone mount crypt:media /mnt/Media.back --rc --rc-no-auth --dir-cache-time 48h --vfs-read-chunk-size 32M --vfs-read-chunk-size-limit 256M --vfs-cache-mode writes --config /root/.config/rclone/rclone.conf --allow-other --cache-workers=1 --buffer-size=256M --no-modtime --fast-list --delete-during --timeout=2m --transfers=4 --use-server-modtime --tpslimit 5 --tpslimit-burst 10 --retries 8 --no-gzip-encoding --checksum --bwlimit 50M --drive-chunk-size 32M --drive-v2-download-min-size 8M
```

No files are being read at the time on the fuse mount.

**Comment by ncw** [comment]
Can you make a memory profile using the instructions here: https://rclone.org/rc/#debugging-rclone-with-pprof and post the results?

Also running `kill -QUIT <pid>` on the `rclone mount` would be useful when it has got lots of memory in use and posting its output.  You'll probably need to `fusermount -z -u /mnt/Media.back` after doing that.

Thanks

**Comment by splitice** [comment]
Will do, however as this is a production environment I can't continue purposefully bloating the process.

I'll see what I can do about setting up a test box as soon as I have a free moment. I'm guessing I need go-lang go for the first request (sorry, largely unfamiliar with Go)?

**Comment by ncw** [comment]
> Will do, however as this is a production environment I can't continue purposefully bloating the process.
> 
> I'll see what I can do about setting up a test box as soon as I have a free moment. I'm guessing I need go-lang go for the first request (sorry, largely unfamiliar with Go)?

You can run the profiling stuff without using any more memory provided it has bloated a bit if you see what I mean.  Yes you'll need to [install go](https://golang.org/dl/) for that, it isn't too hard though.

I did try to replicate this with local copying, but with no joy.


In your original description you wrote this, but I couldn't make it work with `srcFs=` - it just gave me "Object not found errors" I needed to put `srcFs=/`?

> rclone rc operations/copyfile srcFs= srcRemote=/mnt/Media/large.foo dstFs=crypt: dstRemote=media/large.foo

**Comment by splitice** [comment]
srcFs="" is what I am using.

**Comment by splitice** [comment]
Heres a dump with a mild case (230MB) after a couple uploads: https://transfer.sh/gIiyj/pprof.rclone.alloc_objects.alloc_space.inuse_objects.inuse_space.002.pb.gz

Looking at the memory consumption patterns.

1. each operation/copyfile immediately grows the memory usage by approx 200MB (uploading 200MB files - file size?)
2. if stacked in parallel this multiplies
3. upon completion most of the usage remains however it appears to gradually reduce (GC? or some ttl based cache?)
4. if another upload follows the same patterns as point 1

**Comment by splitice** [comment]
Some evidence that seems to support a GC issue.

```
# go tool pprof -text http://localhost:5572/debug/pprof/heap; ps aux | grep rclone | grep "\\-rc"
Fetching profile over HTTP from http://localhost:5572/debug/pprof/heap
Saved profile in /root/pprof/pprof.rclone.alloc_objects.alloc_space.inuse_objects.inuse_space.008.pb.gz
File: rclone
Type: inuse_space
Time: Jan 22, 2019 at 10:35pm (EST)
Showing nodes accounting for 108.35MB, 98.63% of 109.85MB total
Dropped 13 nodes (cum <= 0.55MB)
      flat  flat%   sum%        cum   cum%
   67.08MB 61.06% 61.06%    67.08MB 61.06%  github.com/ncw/rclone/fs/asyncreader.newBuffer (inline)
      32MB 29.13% 90.19%       32MB 29.13%  github.com/ncw/rclone/backend/drive.(*resumableUpload).Upload
    4.50MB  4.10% 94.29%     4.50MB  4.10%  encoding/json.(*decodeState).literalStore
    2.50MB  2.28% 96.57%     2.50MB  2.28%  strings.Join
    1.16MB  1.05% 97.62%     1.16MB  1.05%  github.com/ncw/rclone/lib/dircache.(*DirCache).Put
    0.62MB  0.56% 98.18%     0.62MB  0.56%  github.com/ncw/rclone/vendor/bazil.org/fuse/fs.(*Server).saveNode
    0.50MB  0.46% 98.63%     1.50MB  1.37%  github.com/ncw/rclone/vfs.(*Dir)._readDirFromEntries
         0     0% 98.63%     4.50MB  4.10%  encoding/json.(*Decoder).Decode
         0     0% 98.63%        1MB  0.91%  encoding/json.(*decodeState).array
         0     0% 98.63%     4.50MB  4.10%  encoding/json.(*decodeState).object
         0     0% 98.63%     4.50MB  4.10%  encoding/json.(*decodeState).unmarshal
         0     0% 98.63%     4.50MB  4.10%  encoding/json.(*decodeState).value
         0     0% 98.63%     4.66MB  4.24%  github.com/ncw/rclone/backend/crypt.(*Fs).List
         0     0% 98.63%       32MB 29.13%  github.com/ncw/rclone/backend/crypt.(*Fs).Put
         0     0% 98.63%        1MB  0.91%  github.com/ncw/rclone/backend/crypt.(*Fs).encryptEntries
         0     0% 98.63%       32MB 29.13%  github.com/ncw/rclone/backend/crypt.(*Fs).put
         0     0% 98.63%     3.50MB  3.19%  github.com/ncw/rclone/backend/crypt.(*Object).Open
         0     0% 98.63%     3.50MB  3.19%  github.com/ncw/rclone/backend/crypt.(*Object).Open.func1
         0     0% 98.63%     3.50MB  3.19%  github.com/ncw/rclone/backend/crypt.(*cipher).DecryptDataSeek
         0     0% 98.63%        1MB  0.91%  github.com/ncw/rclone/backend/crypt.(*cipher).decryptFileName
         0     0% 98.63%     3.50MB  3.19%  github.com/ncw/rclone/backend/crypt.(*cipher).newDecrypterSeek
         0     0% 98.63%     3.66MB  3.33%  github.com/ncw/rclone/backend/drive.(*Fs).List
         0     0% 98.63%     2.66MB  2.42%  github.com/ncw/rclone/backend/drive.(*Fs).List.func1
         0     0% 98.63%       32MB 29.13%  github.com/ncw/rclone/backend/drive.(*Fs).Put
         0     0% 98.63%       32MB 29.13%  github.com/ncw/rclone/backend/drive.(*Fs).PutUnchecked
         0     0% 98.63%       32MB 29.13%  github.com/ncw/rclone/backend/drive.(*Fs).Upload
         0     0% 98.63%     1.16MB  1.05%  github.com/ncw/rclone/backend/drive.(*Fs).itemToDirEntry
         0     0% 98.63%     3.66MB  3.33%  github.com/ncw/rclone/backend/drive.(*Fs).list
         0     0% 98.63%        1MB  0.91%  github.com/ncw/rclone/backend/drive.(*Fs).list.func1
         0     0% 98.63%     3.50MB  3.19%  github.com/ncw/rclone/backend/drive.(*Object).Open
         0     0% 98.63%     3.50MB  3.19%  github.com/ncw/rclone/backend/drive.(*Object).Open.func1
         0     0% 98.63%     5.16MB  4.69%  github.com/ncw/rclone/cmd/mount.(*Dir).Lookup
         0     0% 98.63%        1MB  0.91%  github.com/ncw/rclone/cmd/mount.(*Dir).ReadDirAll
         0     0% 98.63%     3.50MB  3.19%  github.com/ncw/rclone/cmd/mount.(*FileHandle).Read
         0     0% 98.63%       32MB 29.13%  github.com/ncw/rclone/fs.Fs.Put-fm
         0     0% 98.63%    67.08MB 61.06%  github.com/ncw/rclone/fs/asyncreader.(*AsyncReader).getBuffer
         0     0% 98.63%    67.08MB 61.06%  github.com/ncw/rclone/fs/asyncreader.(*AsyncReader).init.func1
         0     0% 98.63%    67.08MB 61.06%  github.com/ncw/rclone/fs/asyncreader.glob..func1
         0     0% 98.63%     3.50MB  3.19%  github.com/ncw/rclone/fs/chunkedreader.(*ChunkedReader).Open
         0     0% 98.63%     3.50MB  3.19%  github.com/ncw/rclone/fs/chunkedreader.(*ChunkedReader).openRange
         0     0% 98.63%     4.66MB  4.24%  github.com/ncw/rclone/fs/list.DirSorted
         0     0% 98.63%       32MB 29.13%  github.com/ncw/rclone/fs/operations.Copy
         0     0% 98.63%       32MB 29.13%  github.com/ncw/rclone/fs/operations.init.2.func1
         0     0% 98.63%       32MB 29.13%  github.com/ncw/rclone/fs/operations.moveOrCopyFile
         0     0% 98.63%       32MB 29.13%  github.com/ncw/rclone/fs/operations.rcMoveOrCopyFile
         0     0% 98.63%       32MB 29.13%  github.com/ncw/rclone/fs/rc/rcserver.(*Server).handlePost
         0     0% 98.63%       32MB 29.13%  github.com/ncw/rclone/fs/rc/rcserver.(*Server).handler
         0     0% 98.63%       32MB 29.13%  github.com/ncw/rclone/fs/rc/rcserver.(*Server).handler-fm
         0     0% 98.63%     4.50MB  4.10%  github.com/ncw/rclone/lib/pacer.(*Pacer).Call
         0     0% 98.63%     4.50MB  4.10%  github.com/ncw/rclone/lib/pacer.(*Pacer).call
         0     0% 98.63%    10.27MB  9.35%  github.com/ncw/rclone/vendor/bazil.org/fuse/fs.(*Server).Serve.func1
         0     0% 98.63%    10.27MB  9.35%  github.com/ncw/rclone/vendor/bazil.org/fuse/fs.(*Server).handleRequest
         0     0% 98.63%     0.62MB  0.56%  github.com/ncw/rclone/vendor/bazil.org/fuse/fs.(*Server).saveLookup
         0     0% 98.63%    10.27MB  9.35%  github.com/ncw/rclone/vendor/bazil.org/fuse/fs.(*Server).serve
         0     0% 98.63%     3.50MB  3.19%  github.com/ncw/rclone/vendor/google.golang.org/api/drive/v2.(*FilesGetCall).Do
         0     0% 98.63%        1MB  0.91%  github.com/ncw/rclone/vendor/google.golang.org/api/drive/v3.(*FilesListCall).Do
         0     0% 98.63%     4.50MB  4.10%  github.com/ncw/rclone/vendor/google.golang.org/api/gensupport.DecodeResponse
         0     0% 98.63%        1MB  0.91%  github.com/ncw/rclone/vfs.(*Dir).ReadDirAll
         0     0% 98.63%     5.16MB  4.69%  github.com/ncw/rclone/vfs.(*Dir).Stat
         0     0% 98.63%     6.16MB  5.60%  github.com/ncw/rclone/vfs.(*Dir)._readDir
         0     0% 98.63%     5.16MB  4.69%  github.com/ncw/rclone/vfs.(*Dir).stat
         0     0% 98.63%     3.50MB  3.19%  github.com/ncw/rclone/vfs.(*ReadFileHandle).ReadAt
         0     0% 98.63%     3.50MB  3.19%  github.com/ncw/rclone/vfs.(*ReadFileHandle).openPending
         0     0% 98.63%     3.50MB  3.19%  github.com/ncw/rclone/vfs.(*ReadFileHandle).readAt
         0     0% 98.63%       32MB 29.13%  net/http.(*ServeMux).ServeHTTP
         0     0% 98.63%       32MB 29.13%  net/http.(*conn).serve
         0     0% 98.63%       32MB 29.13%  net/http.HandlerFunc.ServeHTTP
         0     0% 98.63%       32MB 29.13%  net/http.serverHandler.ServeHTTP
         0     0% 98.63%     1.50MB  1.37%  path.Join
         0     0% 98.63%    67.08MB 61.06%  sync.(*Pool).Get
root     15087  6.1 10.4 2838084 423756 ?      S<sl Jan21 104:47 /usr/bin/rclone mount crypt:media /mnt/Media.back --rc --rc-no-auth --dir-cache-time 48h --vfs-read-chunk-size 32M --vfs-read-chunk-size-limit 256M --vfs-cache-mode writes --config /root/.config/rclone/rclone.conf --allow-other --cache-workers=1 --buffer-size=256M --no-modtime --fast-list --delete-during --timeout=2m --transfers=4 --use-server-modtime --tpslimit 5 --tpslimit-burst 10 --retries 8 --no-gzip-encoding --checksum --bwlimit 50M --drive-chunk-size 32M --drive-v2-download-min-size 8M
```

423M is significantly above the profiled result of 109.85MB

**Comment by ncw** [comment]
Yes that looks like go thinks it is using 109MB whereas it is using 423MB of memory from the OS.

Ah, you are using `--buffer-size=256M` which means whenever you do any sort of transfer above 256M rclone will be allocating 256M of memory. Decreasing this number will help a lot.

It does take some time for memory to be returned to the OS.

I made a branch which I've just warmed up which uses mmap to allocate memory for the async buffers which returns the memory to the OS instantly.  You could try that?

https://beta.rclone.org/branch/v1.45-103-ga8d8fe04-mmap-beta/ (uploaded in 15-30 mins)

**Comment by splitice** [comment]
I'll give that a try.

Does buffer size apply when transferring from a local source to a remote destination (e.g the operation I've been performing)? If so that's a miscalculation on my part.

It's enabled for me so that I can get higher performance when reading drive(crypt) with applications like Plex which do many small consecutive reads. It seems to help (although I'm yet to do technical benchmarks on all the flags I have)l.

**Comment by ncw** [comment]
> Does buffer size apply when transferring from a local source to a remote destination (e.g the operation I've been performing)?

It applies for any transfer, local or remote.

> If so that's a miscalculation on my part. While I would hope the memory would be returned much sooner it would certainly explain some initial growth.

Go has a bit of a problem returning memory to the OS - it tends to hang on to it which is a bit annoying.
 
> It's enabled for me so that I can get higher performance when reading drive(crypt) with applications like Plex which do many small consecutive reads. It seems to help (although I'm yet to do technical benchmarks on all the flags I have)l.

**Comment by splitice** [comment]
I haven't switched to that beta build yet however the service crashed during the night (OOM at an RSS of 25GB) and restarted into a new instance with ```--buffer-size=64M```.

```
[360817.902122] Out of memory: Kill process 15087 (rclone) score 349 or sacrifice child
[360817.902276] Killed process 15087 (rclone) total-vm:4531404kB, anon-rss:2547380kB, file-rss:452kB, shmem-rss:0k
```

When a transfer is active there is now a memory usage of approx 200MB. A significant reduction, so buffer-size explains some of the growth.

**Comment by ncw** [comment]
> When a transfer is active there is now a memory usage of approx 200MB. A significant reduction, so buffer-size explains some of the growth.

The buffer size reduction should certainly help.

> Killed process 15087 (rclone) total-vm:4531404kB, anon-rss:2547380kB, file-rss:452kB, shmem-rss:0k

I make that 2.5GB not 25GB

**Comment by splitice** [comment]
Yes 2.5GB (perhaps you still needed your coffee mate).

Your beta branch appears to resolve the issue completely. rclone is currently sitting at 7MB (!!) after 8 hours.

I left `ps aux | grep rclone` writing to a log file all night and the biggest peak I can find is 2 cycles (~4 minutes) at above 400MB with 2 simultaneous uploads. That's much improved.

**Comment by ncw** [comment]
> Yes 2.5GB (perhaps you still needed your coffee mate).

;-)
 
> Your beta branch appears to resolve the issue completely. rclone is currently sitting at 7MB (!!) after 8 hours.

Great!

> I left `ps aux | grep rclone` writing to a log file all night and the biggest peak I can find is 2 cycles (~4 minutes) at above 400MB with 2 simultaneous uploads. That's much improved.

:-)

I'm going to think about whether to merge this for the 1.46 cycle - it is a fundamental change so I might wait for the 1.47 cycle.  I could make a feature flag I suppose --enable-mmap-allocations or something like that... What do you think?

**Comment by splitice** [comment]
I'd suggest ```--use-mmap-allocations=1```. it keeps your options open to easily make it default in the future (which I see as likely, the improvement is night and day).

**Comment by splitice** [comment]
I haven't completely traced or debugged it yet but it appears there might be another area like this in the cache subsystem, appears to be to do with the reading and (particularly) writing of cache files. Is there a similar set of buffers allocated here in go space that could perhaps benifit from mmap?

**Comment by ncw** [comment]
> I've started #2940 as a testing ground for cache changes.

:-)

Note that you have to be careful with the mmap-ed memory.  As it wasn't allocated by the go memory allocation it knows nothing about it. Consequently you must be careful that it doesn't leak out and get used by other parts of rclone, if that happens, when the mmap block gets freed, the other part of rclone will crash as the memory it was expecting is no longer there.  I've audited the asyncreader to make sure it doesn't leak memory to other parts of rclone.

**Comment by splitice** [comment]
I ended up just using buffer recycling instead of mmap, slightly less efficient but more go native.

**Comment by ncw** [comment]
I'm going to close this now since we now have the `--user-mmap` flag and a better scheme of memory recycling that sync.Pool which seems to love holding onto memory!
