### ISSUE TITLE
onedrive: integration tests failing

### ISSUE THREAD

**Issue by ncw** [ncw/rclone#2930]
This integration test is consistently failing with the onedrive backend

    cd backend/onedrive
    go test -v -run TestIntegration/FsMkdir/FsPutFiles/FsDirMove -verbose

Giving this result

```
$ go test -v -run TestIntegration/FsMkdir/FsPutFiles/FsDirMove -verbose
[snip]
--- FAIL: TestIntegration (21.06s)
    fstests.go:339: Using remote "TestOneDrive:"
    --- FAIL: TestIntegration/FsMkdir (11.92s)
        --- FAIL: TestIntegration/FsMkdir/FsPutFiles (11.44s)
            --- FAIL: TestIntegration/FsMkdir/FsPutFiles/FsDirMove (5.70s)
                require.go:794: 
                    	Error Trace:	fstests.go:1029
                    	Error:      	Received unexpected error:
                    	            	can't move directory - incompatible remotes
                    	            	github.com/ncw/rclone/fs.init
                    	            		/home/ncw/go/src/github.com/ncw/rclone/fs/fs.go:49
                    	            	github.com/ncw/rclone/backend/onedrive.init
                    	            		<autogenerated>:1
                    	            	main.init
                    	            		<autogenerated>:1
                    	            	runtime.main
                    	            		/opt/go/go1.11/src/runtime/proc.go:189
                    	            	runtime.goexit
                    	            		/opt/go/go1.11/src/runtime/asm_amd64.s:1333
                    	Test:       	TestIntegration/FsMkdir/FsPutFiles/FsDirMove
[snip]
```

Commenting out this bit of code causes it to work

```diff
--- a/backend/onedrive/onedrive.go
+++ b/backend/onedrive/onedrive.go
@@ -1092,7 +1092,7 @@ func (f *Fs) DirMove(src fs.Fs, srcRemote, dstRemote string) error {
 	if dstDriveID != srcDriveID {
 		// https://docs.microsoft.com/en-us/graph/api/driveitem-move?view=graph-rest-1.0
 		// "Items cannot be moved between Drives using this request."
-		return fs.ErrorCantDirMove
+		// return fs.ErrorCantDirMove
 	}
 
 	// Check destination does not exist
```

This change was introduced as part of 49da220b653d7912c5efeaf6b2656c9d704d33ce so relatively recently by @Cnly 

Can you take a look @Cnly ? Thanks :-)

**Comment by Cnly** [comment]
@ncw I tried to make a quick fix on [`onedrive-root-id-normalise-2930`](https://github.com/ncw/rclone/commit/937a560f1e4417131e217c306a9ec2380140fd28); now it looks good on my machine. Is it possible to have the integration tests run on that branch?

**Comment by ncw** [comment]
> @ncw I tried to make a quick fix on [`onedrive-root-id-normalise-2930`](https://github.com/ncw/rclone/commit/937a560f1e4417131e217c306a9ec2380140fd28); now it looks good on my machine. Is it possible to have the integration tests run on that branch?

It isn't easy unfortunately...

However i tested them on my machine with this which is exactly what the integration tests do:

    go install ./...
    test_all -backends onedrive

And it all passed so can you merge that branch please :-)

![image](https://user-images.githubusercontent.com/536803/51676212-d98a7f80-1fcd-11e9-82b8-b770050b1c07.png)

**Comment by Cnly** [comment]
Thanks, it's now merged.
