### ISSUE TITLE
rclone sync not detecting overlapping remotes

### ISSUE THREAD

**Issue by ScuttleSE** [ncw/rclone#2932]
#### Output of `rclone version`
rclone v1.45

#### Describe the issue
I have a job that syncs file from one google drive to another (server side copy). I have added the source drive to the destination drive as a view only folder, so the remotes are "gdrive1:RemoteCopy" and "gdrive1:LocalCopy"

At the end of a rclone sync-job, rclone tries to delete files from the remote copy. The folder is added as "view only", so this of course fails, but why would rclone try to delete from source in the first place:

commandline is:

`rclone -vvv --drive-impersonate user@example.com sync "gdrive1:RemoteCopy" gdrive1:LocalCopy"`

I am using a service account on gdrive to impersonate user@example.com

**Comment by ncw** [comment]
Can you attach a full log with `-vv` of this happening please?  Maybe make a small example so the log doesn't get too big.  Thanks

**Comment by ScuttleSE** [comment]
It only seems to happen when I do a sync of lots of files, so the logfile is quite large, if it's ok with you, I'll send it privately in an email

**Comment by ncw** [comment]
An email would be great . Can you put a link to this issue in please. nick@craig-wood.com

**Comment by ScuttleSE** [comment]
Any update on this?

**Comment by ncw** [comment]
Sorry your email went missing.  Found it now!

All the errors look like this

    2019/01/24 18:40:58 ERROR : remote/XXX/YYY: Couldn't delete: googleapi: Error 403: The user does not have sufficient permissions for this

According to your command line you were running `rclone sync "dom-01:remote" "dom-01:"`

What it looks like is that your source and destination overlap.  So `sync` is trying to make the source look the same as the destination - it is therefore trying to remove files which don't belong in the destination.  Since this includes the source "remote" directory, then that explains what you are seeing.

So I think the bug here is that rclone isn't warning you that the source and destination overlap like it should.

**Comment by ScuttleSE** [comment]
Hm, that is a bit confusing. I thought my command-line would make the destination-directory look like the source-directory, without touching source. I.e, some kind of one-way sync.

**Comment by polaco1782** [comment]
Lost all my files due to this. rclone deleted all files on my local storage, not the destination.

**Comment by ScuttleSE** [comment]
Ooooh, now I think I see the error of my ways

I have the remote drive mounted on my destination, and since that remote drive isn't mounted on source it would be deleted, yeah

**Comment by polaco1782** [comment]
> Ooooh, now I think I see the error of my ways
> 
> I have the remote drive mounted on my destination, and since that remote drive isn't mounted on source it would be deleted, yeah

Welcome aboard

**Comment by ncw** [comment]
Yes this needs fixing, but the bug is that rclone should have stopped you doing it.  I've changed the title accordingly.

**Comment by ncw** [comment]
I've made a fix which will cause rclone to bomb out on overlapping remotes - can you give it a try?

https://beta.rclone.org/branch/v1.46.0-024-gd777657d-fix-2932-overlap-beta/ (uploaded in 15-30 mins)

@polaco1782 hopefully this would have helped you too.  What command were you running?

**Comment by ScuttleSE** [comment]
`2019/02/14 17:26:52 DEBUG : rclone: Version "v1.46.0-024-gd777657d-fix-2932-overlap-beta" starting with parameters ["/samba/backups/rclone/beta/rclone" "-vv" "--log-file" "/samba/backups/rclone/limitedjobs_run.log.beta" "--config" "/samba/backups/rclone/.rclone.conf" "--exclude" "*/@eaDir/*" "--drive-impersonate" "account@example.com" "sync" "test:remote" "test:"]
2019/02/14 17:26:52 DEBUG : Using config file from "/samba/backups/rclone/.rclone.conf"
2019/02/14 17:26:53 ERROR : Fatal error received - not attempting retries
2019/02/14 17:26:53 Failed to sync: can't sync or move files on overlapping remotes
`

**Comment by ncw** [comment]
Thanks for testing.

I've merged this to master now which means it will be in [the latest beta](https://beta.rclone.org) in 15-30 mins and released in v1.47
