### ISSUE TITLE
"No space available" when copying file to webdav mount on windows

### ISSUE THREAD

**Issue by homeii** [ncw/rclone#2934]
#### What is the problem you are having with rclone?

Windows explorer says "No space available" when copying file to webdav mount on windows

#### What is your rclone version (output from `rclone version`)

rclone v1.45-100-ga2341cc4-beta
- os/arch: windows/386
- go version: go1.11
(cannot download the latest beta because it says Connection closed at byte 0.)

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

Windows 7 32bit
Windows 10 64bit with rclone 32bit 
(64bit version worked well on windows 10 x64)

####  Which cloud storage system are you using? (eg Google Drive)

Self-hosted Nextcloud

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

`rclone --config r.conf mount davtest:/ V:  --vfs-cache-mode=writes -vv`
after that i tried to copy a txt file sized 4.00kb into the disk but it says "No space available", 0B remains.

Downloading,deleting and renaming files or editing files with applications such as word worked well.
Copying files using "copy" command worked well.

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
See log file

[rclone.log](https://github.com/ncw/rclone/files/2794729/rclone.log)

**Comment by ncw** [comment]
What does explorer say as to the free/used capacity of the disk `V:`?

I understand you to have tried the 64 bit version and that works OK?

I suspect the values are getting trucated to 0 on 32 bit somehow.

The relevant part of the log is this

```
2019/01/25 13:19:25 DEBUG : /: >Statfs: stat={Bsize:4096 Frsize:4096 Blocks:274877906944 Bfree:274877906944 Bavail:274877906944 Files:1000000000 Ffree:1000000000 Favail:0 Fsid:0 Flag:0 Namemax:255}, errc=0
```

Rclone is declaring 274877906944 blocks available which is bigger than 2^32

Try this which clips the max size to a 32 bit integer

https://beta.rclone.org/branch/v1.45-105-g39836631-fix-2934-win-mount-beta/ (uploaded in 15-30 mins)

**Comment by homeii** [comment]
This beta version worked well on both windows7 32bit and windows 10 64bit with 32bit rclone.Thanks very much.

**Comment by homeii** [comment]
Now it says there are 15tb available instead of 0.Anything worked greatly.

**Comment by ncw** [comment]
I've merged this to master now which means it will be in [the latest beta](https://beta.rclone.org) in 15-30 mins and released in v1.46

**Comment by homeii** [comment]
Thanks very much.

By the way I think getting the real disk free/used space from Nextcloud may be a better idea,like what rclone did when mounting onedrive,for example.

**Comment by homeii** [comment]
> > By the way I think getting the real disk free/used space from Nextcloud may be a better idea,like what rclone did when mounting onedrive,for example.
> 
> If you can find out how to do this, then please make a [new issue on github](https://github.com/ncw/rclone/issues/new/choose) with links to the API docs please as we'll see what we can do! Or maybe you'd like to have a go?

The solution is posted in #2937 .I'm not familiar with go so I'm sorry I can't help to make it works.
