### ISSUE TITLE
onedrive Failed to query available drives: HTTP error 401 (401 Unauthorized)

### ISSUE THREAD

**Issue by guoxiangke** [ncw/rclone#2936]
#### What is the problem you are having with rclone?
remote server config onedrive not work

![untitled](https://user-images.githubusercontent.com/1160703/51778137-28095c80-213b-11e9-864a-93004ec21439.gif)
#### What is your rclone version (output from `rclone version`)

ubuntu@VM-0-6-ubuntu:~/rclone-v1.45-linux-amd64$ rclone version
rclone v1.45

os/arch: linux/amd64
go version: go1.11.2

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

ubuntu@VM-0-6-ubuntu:~/rclone-v1.45-linux-amd64$ uname -a
Linux VM-0-6-ubuntu 4.15.0-29-generic #31-Ubuntu SMP Tue Jul 17 15:39:52 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
####  Which cloud storage system are you using? (eg Google Drive)

onedrive

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

rclone config

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

none

**Comment by Cnly** [comment]
I noticed that in the lower terminal in your gif the output is like this:

```
Choose OneDrive account type?
 * Say b for a OneDrive business account
 * Say p for a personal OneDrive account
```

The corresponding snippet of code for this output only existed in rclone versions _prior_ to v1.45, which means the rclone in which you run `rclone authorize "onedrive"` is too old and is using the obsolete and deprecated API for OneDrive that is incompatible with the newer rclone (in your upper screen) that you're using.

So the solution is to update the rclone in your lower screen to a more recent version, most preferably the same as the other rclone you're using.

**Comment by guoxiangke** [comment]
> I noticed that in the lower terminal in your gif the output is like this:
> 
> ```
> Choose OneDrive account type?
>  * Say b for a OneDrive business account
>  * Say p for a personal OneDrive account
> ```
> The corresponding snippet of code for this output only existed in rclone versions _prior_ to v1.44, which means the rclone in which you run `rclone authorize "onedrive"` is too old and is using the obsolete and deprecated API for OneDrive that is incompatible with the newer rclone (in your upper screen) that you're using.
> 
> So the solution is to update the rclone in your lower screen to a more recent version, most preferably the same as the other rclone you're using.
> 
> EDIT: I wrote "_prior_ to v1.45" which is incorrect.

Thanks, Your are right, I update my local rclone version. & now it works. thanks
