### ISSUE TITLE
How to decrpyt files without rclone

### ISSUE THREAD

**Issue by jackTaw88** [ncw/rclone#2951]
Hi,

I know the password. What is the way to decrypt a file which is uploaded by rclone encrypt mode?

Thank you

**Comment by calisro** [comment]
I realize your issue says without rclone, but is there a reason to do it outside of rclone?  I believe the answer that will come is that you will need to develop something to decrypt it using the same encryption methods but that is essentially doing what rclone already does.

**Comment by jackTaw88** [comment]
@calisto yes. you understand me correctly.

the reasons:

1- if I go to another machine and I download spesific file manually from browser. I don't trust the computer and I don't want to give my complete rclone-config-file. (For example I can login to microsoft drive without password with a temporary one time password.)

2- I don't know how rclone works. I am worried if rclone will blocked/banned by cloud providers. I had seen something about that, but I did not understand it clearly.

I can ignore the above concerns if:
- I can decrypt the files with rclone, if I download the files locally (manually from my browser)
- There is a simple way to decrypt the downloaded files

Thank you

**Comment by ncw** [comment]
> * I can decrypt the files with rclone, if I download the files locally (manually from my browser)

This is easy to do - you make a crypt and you point the "remote" parameter to a local directory.  Stick the files in there and they will be decryptable.

> * There is a simple way to decrypt the downloaded files

There is a javascript implementation of rclone crypt here:

https://github.com/FWeinb/rclone-js

**Comment by jackTaw88** [comment]
Thank you
