### ISSUE TITLE
Use semver for releases

### ISSUE THREAD

**Issue by myitcv** [ncw/rclone#2960]
#### What is the problem you are having with rclone?

Unable to get the latest version of `rclone` using the `go` tool in module mode.

#### What is your rclone version (output from `rclone version`)

n/a

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

Linux 64bit.

####  Which cloud storage system are you using? (eg Google Drive)

n/a

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

In module-mode, `github.com/ncw/rclone` will only work with valid semver versions. Hence:

```
cd $(mktemp -d)
go mod init mod
go get github.com/ncw/rclone
go list -m github.com/ncw/rclone
```

gives:

```
github.com/ncw/rclone v1.43.1
```

That is to say, it is not possible to add a module requirement for a release of `github.com/ncw/rclone` other than for valid semver versions (`1.43.1` is the latest valid semver version).

In Go 1.12 this will also affect `go get` outside of a module context now that https://github.com/golang/go/issues/24250 has landed:

```
GO111MODULE=on go get github.com/ncw/rclone
$GOPATH/bin/rclone version
```

gives:

```
rclone v1.43.1
- os/arch: linux/amd64
- go version: go1.12beta2
```

Given that rclone has already moved to using modules for its dependencies, this is the preferred way of installing via the `go` tool.

So where people are looking to:

* add rclone as a requirement for their module
* install rclone "globally" on their system using module-mode

they will have to resort to doing:

```
go get github.com/ncw/rclone@master
```

or a specific commit, which seems less than ideal.

It would be sufficient to add additional tags as part of the release process, but not sure how that would sit with your release process. For example, in addition to tagging [`v1.46`](https://github.com/ncw/rclone/tree/v1.46), you could also tag `v1.46.0`. Yes the version reported by `rclone --version` would/might still read `v1.46`, but at least the `go` tool in module mode would be able to resolve to a valid semver version.

**Comment by ncw** [comment]
Yes, I've always gone for Major.Minor with rclone with an implicit patch level .0.  Alas that turns out not to be quite semvar compliant :-(

I hasn't realised that making 1.43.1 makes that the only version go modules will pick up.

I'll put a 1.46.0 tag on the repo now and have a think about the best way forward for the future.

Thank you for letting me know about this!

**Comment by ncw** [comment]
I did a bit of experimenting and I think v1.X.Y versions won't break anything.  I've updated the Makefile so the next time I do a release it will make that sort of tag and I've pushed a v1.46.0 tag so hopefully we are all good!

**Comment by myitcv** [comment]
> I've pushed a v1.46.0 tag so hopefully we are all good!

Looks good to me (repeated same test above).

> Thank you for letting me know about this!

My pleasure. 

Thank you for all the amazing work you've done and continue to do on rclone.

**Comment by ncw** [comment]
Thanks for testing :-)

I've changed the build process to use semvar compliant tags so next release should use them automatically (cross fingers!).

I'll leave this issue open until 1.47.0 is released!
