### ISSUE TITLE
ls crashes for WebDav remote with strconv.ParseInt: parsing "true": invalid syntax

### ISSUE THREAD

**Issue by berndulum** [ncw/rclone#2964]
#### What is the problem you are having with rclone?

Running the ls command with a WebDav remote for the german provider 1&1 gives an error:
`strconv.ParseInt: parsing "true": invalid syntax`

But creating a new folder with `mkdir` is working. Uploading a new file uploads the file, but fails on the client with the same error as above. 

#### What is your rclone version (output from `rclone version`)
rclone v1.46.0-006-gef5e1909-beta
- os/arch: linux/arm
- go version: go1.11.5

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

Ubuntu 16.04.5 LTS
Linux version 3.10.106-149 (root@1604_builder_armhf) (gcc version 4.9.4 (Ubuntu/Linaro 4.9.4-2ubuntu1~16.04) ) #1 SMP PREEMPT Tue Sep 26 04:41:09 UTC 2017

####  Which cloud storage system are you using? (eg Google Drive)

WebDav with 1&1 Onlinespeicher (https://sd2dav.1und1.de)

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
`rclone ls 1u1:`

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

```2019/02/10 11:26:02 DEBUG : rclone: Version "v1.46.0-006-gef5e1909-beta" starting with parameters ["rclone" "-vv" "ls" "1u1:"]
2019/02/10 11:26:02 DEBUG : Using config file from "/home/user/.config/rclone/rclone.conf"
2019/02/10 11:26:04 ERROR : : error listing: couldn't list files: strconv.ParseInt: parsing "true": invalid syntax
2019/02/10 11:26:04 Failed to ls: couldn't list files: strconv.ParseInt: parsing "true": invalid syntax
```

Here are the logs with `-dump bodies` with an empty folder:
```
$ rclone -vv --dump bodies ls 1u1:folder
2019/02/10 11:50:37 DEBUG : rclone: Version "v1.46.0-006-gef5e1909-beta" starting with parameters ["rclone" "-vv" "--dump" "bodies" "ls" "1u1:folder"]
2019/02/10 11:50:37 DEBUG : Using config file from "/home/user/.config/rclone/rclone.conf"
2019/02/10 11:50:37 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2019/02/10 11:50:37 DEBUG : HTTP REQUEST (req 0x1b32080)
2019/02/10 11:50:37 DEBUG : PROPFIND /folder HTTP/1.1
Host: sd2dav.1und1.de
User-Agent: rclone/v1.46.0-006-gef5e1909-beta
Authorization: XXXX
Depth: 1
Accept-Encoding: gzip

2019/02/10 11:50:37 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2019/02/10 11:50:39 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2019/02/10 11:50:39 DEBUG : HTTP RESPONSE (req 0x1b32080)
2019/02/10 11:50:39 DEBUG : HTTP/1.1 207 Multi-Status
Cache-Control: no-cache
Content-Security-Policy: default-src 'none'
Content-Type: text/xml;charset=UTF-8
Date: Sun, 10 Feb 2019 10:50:39 GMT
Referrer-Policy: origin
Server: Apache
Strict-Transport-Security: max-age=15552001
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Request-Id: XGAB-6wTOQQAAAE71RYAAABD
X-Ui-Internal-Gurid-Suffix: XGAB-6wTOQQAAAE71RYAAABD
X-Ui-Version: 1.6.2497.3/1.6.2497.3
X-Xss-Protection: 1; mode=block

<?xml version="1.0" encoding="UTF-8" standalone="no"?><D:multistatus xmlns:D="DAV:"><D:response><D:href>/folder/</D:href><D:propstat><D:prop><D:creationdate>2019-02-10T10:13:55Z</D:creationdate><D:getcontentlanguage>de</D:getcontentlanguage><D:getetag>AAABaNbmKsEAAAFo1uYqwQ</D:getetag><D:getlastmodified>Sun, 10 Feb 2019 10:13:55 GMT</D:getlastmodified><D:iscollection>true</D:iscollection><ns666:Win32LastModifiedTime xmlns:ns666="urn:schemas-microsoft-com:">Sun, 10 Feb 2019 10:13:55 GMT</ns666:Win32LastModifiedTime><ns666:Win32LastAccessTime xmlns:ns666="urn:schemas-microsoft-com:">Sun, 10 Feb 2019 10:13:55 GMT</ns666:Win32LastAccessTime><D:getcontentlength>0</D:getcontentlength><D:resourcetype><D:collection/></D:resourcetype><ns666:Win32FileAttributes xmlns:ns666="urn:schemas-microsoft-com:">0</ns666:Win32FileAttributes><D:displayname>folder</D:displayname><D:getcontenttype>httpd/unix-directory</D:getcontenttype><ns666:Win32CreationTime xmlns:ns666="urn:schemas-microsoft-com:">Sun, 10 Feb 2019 10:13:55 GMT</ns666:Win32CreationTime></D:prop><D:status>HTTP/1.1 200 OK</D:status></D:propstat></D:response></D:multistatus>
2019/02/10 11:50:39 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2019/02/10 11:50:39 Failed to create file system for "1u1:folder": read metadata failed: strconv.ParseInt: parsing "true": invalid syntax

```

**Comment by ncw** [comment]
Ah, standards! Does this remote work with rclone 1.45?

Here is a work-around for that, can you give it a go please?  

https://beta.rclone.org/branch/v1.46.0-012-g78a30bd5-fix-2964-webdav-beta/ (uploaded in 15-30 mins)

**Comment by berndulum** [comment]
It is working with both v1.45 and the new workaround (v1.46-012). 

Thanks for the fast patch!

**Comment by ncw** [comment]
I've merged this to master now which means it will be in [the latest beta](https://beta.rclone.org) in 15-30 mins and released in v1.47



> It is working with both v1.45 and the new workaround (v1.46-012).

Good to know.  This problem was a consequence of a work-around I put in in the 1.45 dev cycle for #2716

There are lots of WebDAV implementations, each one slightly different apparently!

> Thanks for the fast patch!

No probs!  And thanks for a great bug report with a `--dump bodies` - just what I needed to fix the problem.

**Comment by gcp5678** [comment]
strconv.ParseInt: parsing "NaN": invalid syntax

**Comment by gcp5678** [comment]
win10 rclone v1.51.0, I have this problem.

**Comment by Yexiaoxing** [comment]
Hi @gcp5678 Could you please open a new issue and provide us more information?
