### ISSUE TITLE
Additional HTTPS remote flags

### ISSUE THREAD

**Issue by aliron19** [ncw/rclone#2966]
I really appreciate [Mr. Craig-Wood](https://forum.rclone.org/u/ncw) suggestion at [rclone forum](https://forum.rclone.org/t/how-to-use-a-custom-ca-certificate/8676) to add the following three additional flags to deal with some authentication issues that HTTPS remotes may arise:

    --ca-cert string          Client side certificate authority used to verify the server
    --client-cert string      Client side SSL certificate PEM key (concatenation of certificate and CA certificate)
    --client-key string       Client side SSL Private PEM key

The first one, `--ca-cert string`, would allow to use rclone with a HTTPS remote which uses a custom CA, or certificate, without having to use `--no-check-certificate` (which is a really bad idea and should only be used as a last resort), and without having to install any certificate on the system rclone would be executed (to keep this wonderful tool fully portable). 

The other two of them, `--client-cert string` and `--client-key string`, would permit rclone to authenticate to the server with a custom SSL certificate, to improve the overall security scheme instead of using basic HTTP credentials.

Thank you very much.

**Comment by ncw** [comment]
I have had a go at this here

https://beta.rclone.org/branch/v1.46.0-013-gb4da74fd-fix-2966-ssl-flags-beta/ (uploaded in 15-30 mins)

Can you have a test?

**Comment by aliron19** [comment]
I've tested that beta version on a Windows 10 Pro machine (64 bits), and the `--ca-cert` works like a charm. 

However, I've just noticed a small detail. Many other tools (curl, restic, etc.) use `--cacert` (without the dash between `ca` and `cert`) to validate the server against a custom certificate. So, if it doens't break any rclone naming convention, would it be possible to rename that flag to `--cacert` instead? It would be easier to remember, I think. 

Anyway, thank you very much for your **quick** response.

**Comment by ncw** [comment]
> I've tested that beta version on a Windows 10 Pro machine (64 bits), and the `--ca-cert` works like a charm.

Excellent :-)

> So, if it doens't break any rclone naming convention, would it be possible to rename that flag to `--cacert` instead? It would be easier to remember, I think.

That is a good suggestion and I try to stay compatible with other programs where possible.  On reflection I think I'd rather leave it how it is as rclone has rather a lot of ssl related options using the `thing`-`thing` convention so `--ca-cert` fits in better there.

Client options

      --ca-cert string         CA certificate used to verify servers
      --client-cert string     Client SSL certificate (PEM) for mutual TLS auth
      --client-key string      Client SSL private key (PEM) for mutual TLS auth

Sever options (eg `rclone serve http`)

      --cert string            SSL PEM key (concatenation of certificate and CA certificate)
      --client-ca string       Client certificate authority to verify clients with
      --key string             SSL PEM Private key

rc server options

      --rc-cert string        SSL PEM key (concatenation of certificate and CA certificate)
      --rc-client-ca string   Client certificate authority to verify clients with
      --rc-key string         SSL PEM Private key

I note also that wget uses `--ca-certificate` just to be similar but different!

I thought the flag parsing library allowed aliases, but it doesn't alas!

I've merged this to master now which means it will be in [the latest beta](https://beta.rclone.org) in 15-30 mins and released in v1.47
