### ISSUE TITLE
Dreamhost datacenter relocated in 2018

### ISSUE THREAD

**Issue by RTH10260** [ncw/rclone#2974]
The default configuration file for rclone at [https://github.com/ncw/rclone/blob/master/backend/s3/s3.go#L348-L351](
https://github.com/ncw/rclone/blob/master/backend/s3/s3.go#L348-L351) still points to the old now inactive endpoint.

old: “objects-us-west-1.dream.io”
new: “objects-us-east-1.dream.io”

Someone please fix this as I don’t have the experience.

**Comment by ncw** [comment]
Thanks for the report.

I've merged a fix for this to master now which means it will be in [the latest beta](https://beta.rclone.org) in 15-30 mins and released in v1.46
