### ISSUE TITLE
Rclone creates (or logs that is creating) empty directories on every sync

### ISSUE THREAD

**Issue by ncw** [ncw/rclone#2977]
#### What is the problem you are having with rclone?

Rclone creates (or logs that is creating) empty directories on every sync

#### What is your rclone version (output from `rclone version`)

Current git

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

Linux, 64

####  Which cloud storage system are you using? (eg Google Drive)

Local file system for testing

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

```
cd /tmp
mkdir t1
mkdir t1/empty
rclone -vv copy t1 t2
rclone -vv copy t1 t2
```

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

Both the copy commands produce this log

```
2019/02/15 11:02:38 DEBUG : empty: Making directory
```

Rclone should know while it is traversing the tree about the empty directories in the source so it shouldn't have to make them.

**Comment by ishuah** [comment]
@ncw mind if I take this?

**Comment by ncw** [comment]
> @ncw mind if I take this?

That would be great thanks!  Sorry for the delay responding - I've been away.

**Comment by Nestar47** [comment]
This appears to also be related to #2800

**Comment by ishuah** [comment]
This should be fixed in 1b52f8d2a5f95905e3ce9b6e843e6242cae8683c

**Comment by Nestar47** [comment]
Cool, It also made it into one of the beta builds I'm testing for a separate issue, so I'll turn on -vv for one of the scripts and see what it looks like.

**Comment by Nestar47** [comment]
Yup, worked well. No mention of copying directories at the end anymore.

**Comment by ncw** [comment]
Excellent news!  I'll close this issue now then.
