### ISSUE TITLE
Local file list

### ISSUE THREAD

**Issue by cowai** [ncw/rclone#299]
Hi,
First I would like to say that this software is awesome and I see so many possibilities to use this for. Great work!
In my test I have around 100K at around 5GB total. Only scanning for changes takes over an hours in my test, and would really benefit from having a local file list cache. Since Rclone will be the only interface for my backend (hubic) there wont be any problems with that. 

In the future I want to backup around 10TB to hubic but that would take days even if nothing changed. 

Any thoughts on this?

**Comment by klauspost** [comment]
Wow that is slow. I think the most generally usable solution would be to speed up the Swift directory lister, maybe by making it more concurrent. I cannot immediately wrap my head around the current code, but there may be a good place to insert it.

Local caches that cannot be easily validated is a can of worms. Any "use-at-your-own-risk" functionality is a huge support burden, since people rarely read the disclaimers or has problems understanding the implications. However, if Swift cannot be made working at reasonable speed, it may be an option.

**Comment by ncw** [comment]
Reading the modification times from the remote is slow with swift/hubic - I think that is the problem.  When you do a listing you get size/name/md5sum but not modtime for all files very efficiently, but to get the modtime takes another http transaction.

You should find that `--size-only` is very much quicker.

I backup 25,000 pictures to swift regularly.  A no changes sync with `--size-only` takes 13s where as it takes 3 minutes 30 seconds without -  16x faster.

We've been discussing a local cache of hashes which would speed up the `--checksum` case enormously and that would become as fast as `--size-only` but much more accurate.

**Comment by cowai** [comment]
Testing with size-only took around 6 minutes in my first test. So it definitly much faster.
I am in the moment of making a program that will build local file list and be able to pick a command from a list of "providers" and store which provider it uses. My problem is finding a database that is fast enough to keep up with the directory listing. I have 1.8 million files so loading a database into ram is also not trivial as I dont want to use 500mb just for a file list.

Do you have a suggestion for a local cache which is faster than walking through a huge pool?

**Comment by ncw** [comment]
Glad `--size-only` worked its magic!

As for local file list DB - sqlite is hard to beat for this.

rclone will at some point gain a local cache of files I'm sure!

**Comment by timwhite** [comment]
Local cache of checksums would really help. I have > 800Gb of photos I backup to Hubic, I'm trialling size-only now to speedup my copy, and then would look at using checksum based sync on a regular basis to verify all files

**Comment by cowai** [comment]
Local cache of modtime, size and checksum is best. Because then it could always check against modtime and size, but have extra testing done with checksum as well when preferrend. --size-only is really not ideal in a lot of cases.
I am planning on backup multiple of terabytes with rclone and using checksum too often would mean my server wouldn't do anything else than to read and hash out files.

**Comment by ncw** [comment]
I think this ticket is done now.  We have the not perfect `--size-only` work-around and there are other tickets about metadata caches.
