### ISSUE TITLE
Sudo not needed for installation

### ISSUE THREAD

**Issue by jackbow** [ncw/rclone#2991]
#### Output of 1.46 on macOS
```
rclone v1.46 has successfully installed.
Now run "rclone config" for setup. Check https://rclone.org/docs/ for more details.
```
rclone seems to install fine without needing sudo as recommended at [rclone.org/downloads](https://rclone.org/downloads/). If only certain systems need access to sudo, I think it should be specifically stated so that others can install without sudo.

**Comment by animosity22** [comment]
By default, it is needed on MacOS as it installs in /usr/local/bin, which the normal user doesn't have read/write to.

**Comment by jackbow** [comment]
Yeah, I may've changed some permissions in the past and forgotten.
