### ISSUE TITLE
Jottacloud fails when running on more than one machine

### ISSUE THREAD

**Issue by olihey** [ncw/rclone#2995]
#### What is the problem you are having with rclone?
There is a problem running rclone with the same Jottcloud account on more than one machine.
When I setup the remote on one machine it works fine. Right afterwards I create a remote with the same account on another machine and it works there just fine, but on this first machine I get

> ./rclone -vv lsd jc:/
> 2019/02/23 08:09:46 DEBUG : rclone: Version "v1.46.0-028-g972e27a8-beta" starting with parameters ["./rclone" "-vv" "lsd" "jc:/"]
> 2019/02/23 08:09:46 DEBUG : Using config file from "/root/.config/rclone/rclone.conf"
> 2019/02/23 08:09:46 Failed to create file system for "jc:/": couldn't get account info: failed to get endpoint url: error 401: org.springframework.security.authentication.BadCredentialsException: No username for this token. (Unauthorized)

And if I re-create the remote on the first machine it fails afterwards on the second.

Now this is a bit tricky, as this seems to be a limitation on Jottacloud’s endpoint. I assume that’s because we share the same client_id/client_secret in rclone. Seems like we need to create a new “client” for each rclone instance running, see here: [https://github.com/ttyridal/aiojotta/wiki/Jotta-protocol-3.-Authentication#token-authentication](https://github.com/ttyridal/aiojotta/wiki/Jotta-protocol-3.-Authentication#token-authentication)

A solution might be to offer to create such a per machine client_id/client_secret when setting up the remote?!? Although it's only required if the user wants to use rclone with the same account on multiple machines, maybe the option to automatically create such a credentials pair should be buried in the "Advanced options" section for the Jottacloud remote config.

#### What is your rclone version (output from `rclone version`)
1.46

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Windows & Linux

####  Which cloud storage system are you using? (eg Google Drive)
Jottacloud

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
Does not matter

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
```root@v22018106992474666:~/rclone-v1.46.0-028-g972e27a8-beta-linux-amd64# ./rclone -vv lsd jc:/
2019/02/23 08:08:40 DEBUG : rclone: Version "v1.46.0-028-g972e27a8-beta" starting with parameters ["./rclone" "-vv" "lsd" "jc:/"]
2019/02/23 08:08:40 DEBUG : Using config file from "/root/.config/rclone/rclone.conf"
          -1 2019-02-23 08:08:40        -1 _temp
          -1 2019-02-23 08:08:40        -1 backup
          -1 2019-02-23 08:08:40        -1 books
          -1 2019-02-23 08:08:40        -1 enc
          -1 2019-02-23 08:08:40        -1 games
          -1 2019-02-23 08:08:40        -1 iTunes
          -1 2019-02-23 08:08:40        -1 movies
          -1 2019-02-23 08:08:40        -1 music
          -1 2019-02-23 08:08:40        -1 tv
2019/02/23 08:08:40 DEBUG : 5 go routines active
2019/02/23 08:08:40 DEBUG : rclone: Version "v1.46.0-028-g972e27a8-beta" finishing with parameters ["./rclone" "-vv" "lsd" "jc:/"]
root@v22018106992474666:~/rclone-v1.46.0-028-g972e27a8-beta-linux-amd64# ./rclone -vv lsd jc:/
2019/02/23 08:09:13 DEBUG : rclone: Version "v1.46.0-028-g972e27a8-beta" starting with parameters ["./rclone" "-vv" "lsd" "jc:/"]
2019/02/23 08:09:13 DEBUG : Using config file from "/root/.config/rclone/rclone.conf"
2019/02/23 08:09:13 Failed to create file system for "jc:/": couldn't get account info: failed to get endpoint url: error 401: org.springframework.security.authentication.BadCredentialsException: No username for this token. (Unauthorized)```

**Comment by buengese** [comment]
Just as a note for you I plan to implement this but not before next weekend (just in case you want to look into it yourself)

**Comment by olihey** [comment]
Thanks for taking care of this. No I just did some looking around and it seems the official Jottacloud CLI tool is registering a new device for each installation, see this [issue](https://github.com/jotta/jotta-cli-issues/issues/59) here.
So the most sensible way might be to create a new device each time the user creates a new remote in rclone. But I am not sure.
We might then also need to specify that it will not be possible to copy a rclone.conf from one machine to another anymore as a created remote is device specific.

**Comment by CHRONiCiTY** [comment]
Any news on this?

**Comment by Lyve1981** [comment]
Same for me:

Repro:
- Generate a token on machine A & start upload
- Generate a token on machine B & start upload
- Notice that you will start getting 401 unauthorized errors on machine A as soon as you generated the token on machine B.

It is possible to copy the token from the config file from machine B to machine A, but this will break after some hours because the tokens are refreshed regularly.

The only solid workaround is to downgrade all machines but one to rclone 1.45 which doesn't use tokens but user/pass for authentication instead.
