### ISSUE TITLE
Cache backend: Commands cannot be stopped with Ctrl-C

### ISSUE THREAD

**Issue by cowwoc** [ncw/rclone#2997]
rclone v1.46
- os/arch: windows/amd64
- go version: go1.11

I seem to have the same problem mentioned in https://github.com/ncw/rclone/issues/1946.

When I run "rclone lsd -R" against a cache backend hitting CTRL+C is ignored. If I run the same command against the underlying backend being cached (in my case "local") then CTRL+C works fine.

**Comment by ncw** [comment]
I managed to replicate this on linux.

It seems to happen
- while there are lots of writes going into the cache
- it only happens with SIGINT (CTRL-C), SIGQUIT and SIGINT work fine

...

I realised we have a fix for this in the pipeline already 12c8ee4b4b19b3e1efb86cf5ed91864a81b293f2 so I've merged that.

I've merged this to master now which means it will be in [the latest beta](https://beta.rclone.org) in 15-30 mins and released in v1.47

Can you give it a test?

**Comment by cowwoc** [comment]
@ncw rclone-v1.46.0-051-gf6eb5c69-beta-windows-amd64 worked perfectly for me. Thank you.

**Comment by ncw** [comment]
Great - thanks for testing - I'll close this now.

This will be released in v1.47.
