### ISSUE TITLE
--drive-impersonate - no longer works with v 1.46 or higher

### ISSUE THREAD

**Issue by Expello** [ncw/rclone#3010]
#### What is the problem you are having with rclone?

I have an GSuite Account with one user and with rclone v 1.44 & 1.45 i can use --drive-impersonate without any problems. But no longer works with v 1.46 or higher (incl. the last beta)

With v 1.46 i get the following error:
`2019/02/28 08:14:19 Failed to ncdu: ncdu directory listing: ncdu listing failed: Get https://www.googleapis.com/drive/v3/files/root?alt=json&fields=id&prettyPrint=false&supportsTeamDrives=false: oauth2: cannot fetch token: 401 Unauthorized
Response: {
  "error": "unauthorized_client",
  "error_description": "Client is unauthorized to retrieve access tokens using this method, or client not authorized for any of the scopes requested."
}`

The command (NCDU) is not relevant, because the same error also occurs with copy or move

#### What is your rclone version (output from `rclone version`)

rclone-beta-latest-windows-amd64.zip - 26.02.2019, 16:40:04 (1.46)

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

Windows 10 64bit

####  Which cloud storage system are you using? (eg Google Drive)

Google Drive (GSuit)

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

`rclone ncdu --fast-list --drive-impersonate user@domain.com GDC:`

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

`2019/02/28 08:14:19 Failed to ncdu: ncdu directory listing: ncdu listing failed: Get https://www.googleapis.com/drive/v3/files/root?alt=json&fields=id&prettyPrint=false&supportsTeamDrives=false: oauth2: cannot fetch token: 401 Unauthorized
Response: {
  "error": "unauthorized_client",
  "error_description": "Client is unauthorized to retrieve access tokens using this method, or client not authorized for any of the scopes requested."
}`

**Comment by ncw** [comment]
I suspect this is caused by b8280521a5cc4bce22442b3b17f67ec9980eb3c9

I made a beta with that commit reverted - can you try that?

https://beta.rclone.org/branch/v1.46.0-046-g5dc6c2a0-fix-3010-impersonate-beta/ (uploaded in 15-30 mins)

The effect of that was to use fix a bug which was using the default scopes, rather than the ones defined in the config.

What scopes do you have in your config?

Can you try widening them?

**Comment by Expello** [comment]
No Windows release under your link:
https://beta.rclone.org/branch/v1.46.0-046-g5dc6c2a0-fix-3010-impersonate-beta/

With this version i received the same error:
https://beta.rclone.org/branch/v1.46.0-046-ge3bceb90-test-beta/rclone-v1.46.0-046-ge3bceb90-test-beta-windows-amd64.zip

This is my config:

`[GD]
type = drive
scope = drive.file
service_account_file = C:\Users\XXXX\.config\rclone\XXXX.json
client_id = 
client_secret = 
use_trash = false

[GDC]
type = crypt
remote = GD:
filename_encryption = standard
directory_name_encryption = true
password = 1234
password2 = 1234`

**Comment by ncw** [comment]
> No Windows release under your link:

Ah, sorry, it didn't build... Try this one

https://beta.rclone.org/branch/v1.46.0-047-g5a8a6fbd-fix-3010-impersonate-beta/ (uploaded in 15-30 mins)

> scope = drive.file

Can you try setting this to `scope = drive` then trying again with v1.46 - I suspect that will work.

**Comment by Expello** [comment]
With

https://beta.rclone.org/branch/v1.46.0-047-g5a8a6fbd-fix-3010-impersonate-beta/

It works! :-)

scope = drive

and v 1.46 also works!

thank you very much for your excellent support

**Comment by ncw** [comment]
> With
> 
> https://beta.rclone.org/branch/v1.46.0-047-g5a8a6fbd-fix-3010-impersonate-beta/
> 
> It works! :-)
> 
> scope = drive
> 
> and v 1.46 also works!
> 
> thank you very much for your excellent support

Thanks for testing :-)

v1.46 is working as intended now with the correct scope.

I'm inclined not to make any code changes now we've identified the problem.

I think the fact you setup was working in v1.45 was actually a bug.

What do you think?

**Comment by Expello** [comment]
Yes, you're right, but it wasn't quite clear to me at first. ;-)

I would find it very user-friendly if the manual is adapted and or the program gives a hint.
