### ISSUE TITLE
[rcd/rc] include/filter options are ignored

### ISSUE THREAD

**Issue by jparal** [ncw/rclone#3018]
#### What is the problem you are having with rclone?

When running rclone as a daemon using `rclone rcd`, the filter/include/exclude options set by client or REST API are ignored.

#### What is your rclone version (output from `rclone version`)

rclone v1.46.0-053-gd233efbf-beta
- os/arch: linux/amd64
- go version: go1.12

The latest stable v1.46.0 is also affected.

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

To reproduce run following:

`touch /tmp/pic.jpg /tmp/pic.png`
`rclone rcd --rc-no-auth`
`rclone rc options/set --json '{"filter": {"IncludeRule": ["*.jpg"]}}'`
{}

`rclone rc operations/list fs="" remote=/tmp | grep Path`
“Path”: “/tmp/pic.jpg”,
“Path”: “/tmp/pic.png”,

The expected result should be just the jpg file.

**Comment by ncw** [comment]
What is happening here is that the filter options are being set, but they aren't being implemented.

To implement, this needs to be called.

    	filter.Active, err = filter.NewFilter(&filterflags.Opt)

Here is a beta with that fix - can you give it a go?

https://beta.rclone.org/branch/v1.46.0-058-g12ec7657-fix-3018-rc-reload-beta/ (uploaded in 15-30 mins)

**Comment by jparal** [comment]
I tested the beta version. the filtering is working now. thanks for the lightning speed of fixing this.

**Comment by ncw** [comment]
Thank you for testing :-)

I've merged this to master now which means it will be in [the latest beta](https://beta.rclone.org) in 15-30 mins and released in v1.47
