### ISSUE TITLE
OneDrive 2 factor authentication

### ISSUE THREAD

**Issue by fredster1** [ncw/rclone#3022]
Hi. Our company has started to use two-factor authentication on email addresses. This seems to have blocked rclone from being able to copy into the OneDrive account. Rclone has been running perfectly (thank you to the rclone dev team) until this change. I looked through the docs but found no solution. Thanks.

**Comment by ncw** [comment]
@Cnly thoughts about how difficult this might be?

**Comment by Cnly** [comment]
Hi @fredster1, by "blocked rclone from being able to copy," do you mean it's specifically the write access that is denied? Can you provide some output from rclone when you see the problem? And is your admin installing some new access control rules?

In my opinion I don't think a 2FA itself _should_ affect rclone, because you should be prompted for e.g., a one-time code on Microsoft's website, not by rclone. But that's just my guess.

**Comment by ncw** [comment]
@fredster1 can you describe what you did and paste what error messages you got from rclone?

**Comment by fredster1** [comment]
Here is the error I am getting back.  

2019/03/04 03:30:03 Failed to create file system for "onedrive:ENTIRESERVER": failed to get root: Get https://graph.microsoft.com/v1.0/drives/b!q25_ba7pO0aw0lOX3xLKNSVj3GVXkKFGiiMuMlQYYfBfm1mkaCAgS4NjfUgJhrsS/root: oauth2: cannot fetch token: 400 Bad Request
Response: {"error":"invalid_grant","error_description":"AADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access '00000003-0000-0000-c000-000000000000'.\r\nTrace ID: 09311df9-bd14-4a4c-ace5-362468420000\r\nCorrelation ID: a1f9ae7a-1e9f-40e9-a761-a40b27a57489\r\nTimestamp: 2019-03-04 11:30:03Z","error_codes":[50076],"timestamp":"2019-03-04 11:30:03Z","trace_id":"09311df9-bd14-4a4c-ace5-362468420000","correlation_id":"a1f9ae7a-1e9f-40e9-a761-a40b27a57489","claims":"{\"access_token\":{\"capolids\":{\"essential\":true,\"values\":[\"69cc2b46-d2f6-44f5-91dc-0d8148e1597b\"]}}}","suberror":"basic_action"}

**Comment by Cnly** [comment]
@fredster1 your info is helpful, thanks! I've found some relative info from [Developer guidance for Azure Active Directory conditional access | Microsoft Docs](https://docs.microsoft.com/en-us/azure/active-directory/develop/conditional-access-dev-guide) (page title somewhat obscure to me) and am trying to make some changes.

**Comment by Cnly** [comment]
With some quick testing I found that re-obtaining a refresh token seems to solve this problem and no code changes are needed. @fredster1 Can you try running `rclone config` and then choose to edit your OneDrive remote, and then say yes when it asks whether you want to refresh the token? Please feel free to comment if you're still having problems after that. :)

**Comment by fredster1** [comment]
Hi Cnly, Everything works now.  After your suggestion, I also thought of just clearing all of the cookies and cache in the browser just for a fresh start. I also deleted the onedrive remote entry in rclone. Thanks so much!

**Comment by Cnly** [comment]
Thanks for reporting back and I'll close this for now. Feel free to re-open if you see further problems.

**Comment by ncw** [comment]
Is this something we should put in the docs @Cnly ?

**Comment by Cnly** [comment]
> Is this something we should put in the docs @Cnly ?

I think that's a good idea; it'll be done in a while.

**Comment by michaelulmer** [comment]
Is it possible to use rclone with OneDrive 2fa authentication for Privat and Company o365? I can't use device passwords.

**Comment by ncw** [comment]
Running `rclone config reconnect remote:` should get the token and fix any problems :crossed_fingers:
