### ISSUE TITLE
Add Prefetching for file and dir stats

### ISSUE THREAD

**Issue by fionera** [ncw/rclone#3023]
#### What is your current rclone version (output from `rclone version`)?
1.46.0

#### What problem are you are trying to solve?
Faster dir listing, as example for `rclone mount`

#### How do you think rclone should be changed to solve that?
Add an argument to prefetch all files and folders into the Cache. Also it could be good for that to not delete the whole dir cache. Instead it should be looked for changes

**Comment by ncw** [comment]
You can do this already with the [remote control](https://rclone.org/rc/), and in particular the [vfs/refresh](https://rclone.org/rc/#vfs-refresh-refresh-the-directory-cache) with the `recursive=true` parameter.

If you want all the metadata cached locally, then use the [cache backend](https://rclone.org/cache/)
