### ISSUE TITLE
Use Google Drive Changes API for finding changes

### ISSUE THREAD

**Issue by fionera** [ncw/rclone#3024]
#### What is your current rclone version (output from `rclone version`)?
1.46.0

#### What problem are you are trying to solve?
In addition to https://github.com/ncw/rclone/issues/3023 the cache remote could check if it is using the google drive remote and use the Changes API for dir listing, since it should much faster.

#### How do you think rclone should be changed to solve that?
Checking in the cache remote if its using the drive remote or use it in the drive remote directly and then use the changes API for listing files and their data/changes

**Comment by ncw** [comment]
> In addition to #3023 the cache remote could check if it is using the google drive remote and use the Changes API for dir listing, since it should much faster.

The cache backend uses the changes API for updates, but not for listing.  What makes you think it would be faster for listing?

**Comment by fionera** [comment]
I dont know if its just the feeling but the dir listing seems much faster in plexdrive and its using only the changes API. Can you say me where the cache remote uses the changes API? I didnt saw it...

**Comment by ncw** [comment]
The changes API is only polled every `--poll-interval` which is 1 minute by default.
