### ISSUE TITLE
Wrong total upload size reported while uploading

### ISSUE THREAD

**Issue by trapd00r** [ncw/rclone#3027]
#### What is the problem you are having with rclone?

Yesterday I started uploading a local directory of mine to gdrive. It all works great, except that the total size reported is wrong, and it keeps on adding up. The directory in question consists of **584G** of data.

```
Transferred:       96.481G / 141.056 GBytes, 68%, 1.532 MBytes/s, ETA 8h16m42s
Transferred:       96.804G / 141.412 GBytes, 68%, 1.530 MBytes/s, ETA 8h17m44s
```

#### What is your rclone version (output from `rclone version`)

```
rclone v1.46
- os/arch: linux/amd64
- go version: go1.11.5

```

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

Archlinux 64bit

####  Which cloud storage system are you using? (eg Google Drive)

Google drive

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

`rclone -v copy data/ drive:`

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

```
Transferred:       97.115G / 141.701 GBytes, 69%, 1.526 MBytes/s, ETA 8h18m39s
Errors:                 0
Checks:                 0 / 0, -
Transferred:        16838 / 26850, 63%
Elapsed time:   18h6m8.1s

```

**Comment by ncw** [comment]
This is because you have more than 10,000 files.

By default rclone only gets 10,000 files *ahead* so as not to use up too much memory.

You can set this flag here if you want rclone to get further ahead at the cost of using more memory.

      --max-backlog int     Maximum number of objects in sync or check backlog. (default 10000)

Likely it will become irrelevant after the first sync though!

**Comment by trapd00r** [comment]
Thank you, that's all I wanted to know (I couldn't label the issue as "likely only a question" myself. Closing!

**Comment by ncw** [comment]
> Thank you, that's all I wanted to know (I couldn't label the issue as "likely only a question" myself. Closing!

No worries!

I should probably put this in the FAQ....

How does something like

- Q> the total size reported in a sync is wrong and keeps changing
- A> It is likely you have more than 10,000 files that need to be synced. By default rclone only gets 10,000 files ahead in a sync so as not to use up too much memory. You can change this default with the `--max-backlog` flag

Would that help do you think?

**Comment by trapd00r** [comment]
Yeah, looks good! Thanks for a great tool, it seems damn stable so far:
```

Transferred:      142.925G / 197.767 GBytes, 72%, 1.422 MBytes/s, ETA 10h58m7s
Errors:                 0
Checks:                 0 / 0, -
Transferred:        26060 / 36072, 72%
Elapsed time:  28h35m8.1s
```
