### ISSUE TITLE
--suffix position in the file-name

### ISSUE THREAD

**Issue by Nestar47** [ncw/rclone#3032]
#### What is your current rclone version (output from `rclone version`)?

rclone v1.46
- os/arch: windows/amd64
- go version: go1.11

#### What problem are you are trying to solve?

Using `--suffix .%date:~-10,2%-%date:~-7,2%-%date:~-4,4%`
Adds .Day-Month-Year to the end of the file-name. Google drive seems to detect this and when the file is accessed using File-Stream that suffix is put prior to the file extension (Ensuring that the file will still open as normal), However this behavior is not consistent and when viewed from the google drive UI it will show the proper name (as adjusted by rclone when using --suffix).

![explorer_2019-03-06_09-02-21](https://user-images.githubusercontent.com/47841759/53980694-9b0cd800-40d6-11e9-8f12-e279b5f2b475.png)

It would actually be useful for rclone to be able to deliberately put the suffix prior to the extension.

https://forum.rclone.org/t/odd-suffix-behavior-team-drives/9034

#### How do you think rclone should be changed to solve that?

A new flag --suffix-preserve-extension
To re-locate the added string prior to the extension (if it exists)

**Comment by ncw** [comment]
OK I've had a go at this here

I called the flag `--suffix-keep-extension`

Does it work for you?

https://beta.rclone.org/branch/v1.46.0-067-g1a019292-fix-3032-suffix-keep-extension-beta/ (uploaded in 15-30 mins)

**Comment by Nestar47** [comment]
Alright, replaced it in my folder and updated the scripts.
Will let you know how it went after it runs tonight.

**Comment by Nestar47** [comment]
Works perfect, Thanks

![explorer_2019-03-12_08-24-46](https://user-images.githubusercontent.com/47841759/54203486-5b603a80-44a0-11e9-8085-29a7945e2b06.png)

**Comment by ncw** [comment]
Thanks for testing.

I've merged this to master now which means it will be in [the latest beta](https://beta.rclone.org) in 15-30 mins and released in v1.47
