### ISSUE TITLE
Cache file list on `serve`

### ISSUE THREAD

**Issue by ThatNerdyPikachu** [ncw/rclone#3038]
#### What is your current rclone version (output from `rclone version`)?
rclone v1.46

#### What problem are you are trying to solve?
While using ``serve`` with a lot of files in a Google Drive remote -- even just requesting the file list takes a while.

#### How do you think rclone should be changed to solve that?
I think rclone can cache the list -- similar to how it does files.

Edit: Would the cache storage system help me with this?

**Comment by ncw** [comment]
You can do this with the [cache backend](https://rclone.org/cache/) - it will cache metadata for you
