### ISSUE TITLE
Onedrive graph API failing

### ISSUE THREAD

**Issue by qx-juilliard** [ncw/rclone#3039]
#### What is the problem you are having with rclone?

Cannot ls item for some folders

#### What is your rclone version (output from `rclone version`)

1.46

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

Ubuntu 18.04.2

####  Which cloud storage system are you using? (eg Google Drive)

Onedrive business

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

rclone ls

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

See below for longer description

---

My apologies in advance because I believe this bug is not reproducible since I believe it's only happens for a particular folder I happen to be working on.

Recently, when I try to run the command:

`rclone ls onedrive:path/to/this/strange/folder`

it tells me

```
2019/03/09 23:52:16 Failed to create file system for "qx:backup/phone/photo": "photo": is a not a regular file

```

Use `-vv --dump headers --dump bodies` enables me to locate the following error (I removed two sensitive pieces of information and used the placeholders `my_drive_id` and `my_path_id`):

```
2019/03/09 23:52:16 DEBUG : HTTP REQUEST (req 0xc000606100)
2019/03/09 23:52:16 DEBUG : GET /v1.0/drives/b!my_drive_id/items/my_path_id:/photo HTTP/1.1
Host: graph.microsoft.com
User-Agent: rclone/v1.46
Authorization: XXXX
Accept-Encoding: gzip

2019/03/09 23:52:16 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2019/03/09 23:52:16 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2019/03/09 23:52:16 DEBUG : HTTP RESPONSE (req 0xc000606100)
2019/03/09 23:52:16 DEBUG : HTTP/1.1 400 Bad Request
Transfer-Encoding: chunked
Cache-Control: private
Client-Request-Id: 3f4dee5b-dee4-48ab-804d-2797e609c1f5
Content-Type: application/json
Date: Sun, 10 Mar 2019 04:52:16 GMT
Duration: 363.3902
Odata-Version: 4.0
Request-Id: 3f4dee5b-dee4-48ab-804d-2797e609c1f5
Strict-Transport-Security: max-age=31536000
X-Ms-Ags-Diagnostic: {"ServerInfo":{"DataCenter":"East US","Slice":"SliceC","Ring":"5","ScaleUnit":"002","RoleInstance":"AGSFE_IN_51","ADSiteName":"EUS"}}

1de
{{
  "error": {
    "code": "BadRequest",
    "message": "The Path property 'drives('b%my_drive_id')/items('my_path_id%3A')/photo' of ODataMessageWriterSetting.ODataUri must end with the navigation property which the contained elements being written belong to.",
    "innerError": {
      "request-id": "3f4dee5b-dee4-48ab-804d-2797e609c1f5",
      "date": "2019-03-10T04:52:16"
    }
  }
}
0

2019/03/09 23:52:16 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2019/03/09 23:52:16 DEBUG : Couldn't decode error response: invalid character '{' looking for beginning of object key string
```

I believe I found the answer to this after I looked up Onedrive's api reference here: https://docs.microsoft.com/en-us/graph/api/driveitem-get?view=graph-rest-1.0

## Possible cause of the problem

Currently, rclone uses the following URL scheme, which works but I couldn't find matching ones in the official api reference:

```
GET /drives/{drive-id}/items/{item-id}:/{item-path}
```

---

The following is taken from the api reference, as we can see the above URL scheme used by rclone as of v1.46 is found nowhere here

```
GET /drives/{drive-id}/items/{item-id}
GET /drives/{drive-id}/root:/{item-path}
GET /groups/{group-id}/drive/items/{item-id}
GET /groups/{group-id}/drive/root:/{item-path}
GET /me/drive/items/{item-id}
GET /me/drive/root:/{item-path}
GET /sites/{siteId}/drive/items/{itemId}
GET /sites/{siteId}/drive/root:/{item-path}
GET /users/{userId}/drive/items/{itemId}
GET /users/{userId}/drive/root:/{item-path}
```

I am able to verify this in microsofts' [graph explorer](https://developer.microsoft.com/en-us/graph/graph-explorer), meaning that: given the folder that I had problem with,

- doing `GET /drives/{drive-id}/items/{item-id}:/{item-path}` gives me the exact error that I encountered in rclone
- removing the last segment, and doing `GET /drives/{drive-id}/items/{item-id}` produces correct response

Again, sorry about this bug being not reproducible, since I cannot share my onedrive folder id here.

**Comment by qx-juilliard** [comment]
After digging around for a bit, I am actually quite interested in why the current API call **does** work.

Based on [this page](https://docs.microsoft.com/en-us/graph/api/resources/driveitem?view=graph-rest-1.0), it says

> There are two primary ways of addressing a driveItem resource:
>
> By the driveItem unique identifier using drive/items/{item-id}
> By file system path using /drive/root:/path/to/file 

But based on the changes since [this commit](https://github.com/ncw/rclone/commit/49da220b653d7912c5efeaf6b2656c9d704d33ce), we have a new function called `readMetaDataForPathRelativeToID` that seems to do the trick of combining both **item id** and **path relative to the item id**.

Could this be the cause of the problem?

**Comment by Cnly** [comment]
Thanks for reporting the problem and helping debugging it! Actually, the path style of `/drives/ef8a24cc458790df/items/ef8a24cc458790df!105:/src/main.cpp` comes from [this comment in OneDrive/onedrive-api-docs#908](https://github.com/OneDrive/onedrive-api-docs/issues/908#issuecomment-417488480).

I understand that you may not be able to share more details for privacy concerns, but sometimes strange things do happen to specific OneDrive items, examples including https://github.com/ncw/rclone/issues/2720 and https://github.com/ncw/rclone/issues/2859. If you believe that your folder is special, can you also play with it a bit (E.g., renaming, moving) and see how the problem can be narrowed down? That may be very helpful for the problem :)

**Comment by qx-juilliard** [comment]
thanks for the reply, as of this morning I rolled back to v1.45 and thing went back to normal, so I think the issue is about the undocumented api call mentioned above.

I'll reinstall v1.46 tonight and try renaming and moving the folder around to narrow down the problem.

Though I'm pretty sure now that it's the bug on the microsoft side, I'm still trying to figure out the meaning of the error message `The Path property 'drives('b%my_drive_id')/items('my_path_id%3A')/path' of ODataMessageWriterSetting.ODataUri must end with the navigation property which the contained elements being written belong to.`

**Comment by qx-juilliard** [comment]
**folks I found a way to reproduce the bug!!!**

Following the simple instructions below to reproduce the error:

1. Open up your onedrive
1. Literally, anywhere, make a folder named **photo**
1. `rclone ls` it (or any other operation like `rclone size``rclone lsd`)

You'll get the error described in this issue. I tested this on my personal onedrive account and was able to reproduce the error.

Yes, the essence of the bug is any **folder with the name "photo"**

I don't know why this bug happens, probably because "photo" is a reserved word in microsoft's backend?

**Comment by Cnly** [comment]
Thanks! Just did a quick test and can confirm this. Also tested with the workaround I used in #2720 and that seems to fix the problem, too. (The workaround is to put a colon at the end of the path, as in `/drives/{drive-id}/items/{item-id}:`) Considering #2720 has been there a long time without Microsoft's fixing the problem, I think we'd better just use the workaround.

**Comment by Cnly** [comment]
The workaround has been prepared (again) for rclone v1.46 and it can be found here: https://beta.rclone.org/branch/v1.46.0-067-gc67df55c-onedrive-path-colon-beta/

I'd like to ask people who're affected by this issue to help test it out. If there's no problem, I'll merge it into master.

**Comment by Cnly** [comment]
I've merged the workaround into master. Please feel free to re-open if you're still seeing problems.

**Comment by qx-juilliard** [comment]
Perfect, thanks! :100:
