### ISSUE TITLE
rclone dedupe documentation issue

### ISSUE THREAD

**Issue by caspertone2003** [ncw/rclone#3040]
https://rclone.org/commands/rclone_dedupe/ states that

Only useful with Google Drive which can have duplicate file names.

https://rclone.org/mega/ states that

Duplicated files
Mega can have two files with exactly the same name and path (unlike a normal file system).

Duplicated files cause problems with the syncing and you will see messages in the log about duplicates.

Use rclone dedupe to fix duplicated files.

Thanks
CT

Besides that, I tried dedupe with mega

After dedupe said no copies, a download operation (with --verbose )  issued several notices like:

2019/03/10 02:17:29 NOTICE: Abc.jpg: Duplicate object found in source - ignoring

Seems dedupe in mega is not able to fully dedupe...

**Comment by ncw** [comment]
Yes, dedupe does work with mega so those docs are wrong.

> After dedupe said no copies, a download operation (with --verbose ) issued several notices like:
> 
> 2019/03/10 02:17:29 NOTICE: Abc.jpg: Duplicate object found in source - ignoring

I've not seen this happen.  What happens if you run dedupe again - does it spot it?

**Comment by caspertone2003** [comment]
No, it does not spot it.
Anyhow looks that the remote might have some issues in their file system or such, as it produced other errors also (reported in another thread).
I have been able to move without issues all the contents, and remote is empty.
I propose to close the issue until further installment of the behaviour.
Thanks.
