### ISSUE TITLE
HTTP: add support for PushShift

### ISSUE THREAD

**Issue by ealgase** [ncw/rclone#3053]
#### What is your current rclone version (output from `rclone version`)?

v1.46

#### What problem are you are trying to solve?

Conveniently copying files from the website files.pushshift.io

#### How do you think rclone should be changed to solve that?

Rclone supports many HTTP interfaces and while files.pushshift.io is somewhat supported it doesn't work very well.  Since the framework is there adding support for the site shouldn't be too difficult.

**Comment by ncw** [comment]
I have some pending changes which I think fix the problem - can you give them a go?

https://beta.rclone.org/branch/v1.46.0-078-gbb5ac8ef-fix-http-html-dir-beta/ (uploaded in 15-30 mins)

Use like this

    rclone lsl --http-no-slash --http-url http://files.pushshift.io/ :http:

**Comment by ealgase** [comment]
Works for me, thanks!

**Comment by ncw** [comment]
Thanks for testing :-)

I've merged this to master now which means it will be in [the latest beta](https://beta.rclone.org) in 15-30 mins and released in v1.47
