### ISSUE TITLE
Authorization code

### ISSUE THREAD

**Issue by emresaracoglu** [ncw/rclone#3056]
That's great! I was using Windows based software before. The software was working fine and stable but the upload speed was very slow (max: 3-4mb) with **Rclone** it is at least 30mb in second.

The Google drive file is loading, but this is not possible for OneDrive for me, because I using minimal CentOS 7 and I cant use a web browser in the operation system.

```
Remote config
Use auto config?
 * Say Y if not sure
 * Say N if you are working on a remote or headless machine
y) Yes
n) No
y/n> n
For this to work, you will need rclone available on a machine that has a web browser available.
Execute the following on your machine:
        rclone authorize "onedrive"
Then paste the result below:
result>
```

How can I get the authorization code? Is there a way to do that?
Thank you for this application!

**Comment by animosity22** [comment]
You need to install rclone on a machine that has a webrowser and run the command 

rclone authorize "onedrive"

that will prompt a browser and you enter in the code on the original machine.

Basically, follow the directions printed :)

**Comment by Cnly** [comment]
Also, a reminder would be to ensure that you're using rclone => v1.44 on both your server and your computer that has a browser, if you're using it with OneDrive.

**Comment by emresaracoglu** [comment]
I installed CentOS 7 Desktop on the virtual machine. I have established a connection with a Microsoft account, but I am getting this error

```
Choose a number from below, or type in an existing value
 1 / OneDrive Personal or Business
   \ "onedrive"
 2 / Root Sharepoint site
   \ "sharepoint"
 3 / Type in driveID
   \ "driveid"
 4 / Type in SiteID
   \ "siteid"
 5 / Search a Sharepoint site
   \ "search"
Your choice> 1
Found 1 drives, please select the one you want to use:
0: OneDrive (business) id=b!uMJJJA5I[HIDDEN]gVSL7YpQNTFCi4
Chose drive to use:> 0
2019/03/16 22:31:46 Failed to query root for drive b!uMJJJA5ISEa56[HIDDEN]TdRqtzFzgVSL7YpQNTFCi4: HTTP error 429 (429 ) returned body: "{\r\n  \"error\": {\r\n    \"code\": \"activityLimitReached\",\r\n    \"message\": \"The request has been throttled\",\r\n    \"innerError\": {\r\n      \"request-id\": \"ff38882[HIDDEN]-8e82-e33478e4b98b\",\r\n      \"date\": \"2019-03-16T19:31:46\"\r\n    }\r\n  }\r\n}"
```

What could be the reason?

**Comment by animosity22** [comment]
rclone version shows what?

You can use any computer with a browser and run the rclone authorize btw so you don't need to install desktop.

**Comment by emresaracoglu** [comment]
Version 1.46

**Comment by animosity22** [comment]
Looks like you are throttled based on the message "activityLimitReached"

Maybe check with your admin to see what's going on.

**Comment by emresaracoglu** [comment]
I sent an email to the OneDrive team. I'm guessing it's the Goodsync application installed _(I mentioned in the first message)_ on the virtual machine that synchronizes the files. 
**Thank you** for your time @animosity22
