### ISSUE TITLE
Detail filtered path

### ISSUE THREAD

**Issue by wernight** [ncw/rclone#306]
https://github.com/ncw/rclone/blob/master/docs/content/filtering.md could state if the filter pattern is applied to the *relative path*, path *as provided* through CLI, or *absolute path* or the *local* file name.

**Comment by ncw** [comment]
Do you fancy making a pull request with your suggestions?

Thanks

Nick

**Comment by wernight** [comment]
If you could first explain how it works, yes sure.

**Comment by wernight** [comment]
Can someone tell if: Filter pattern applies to source or destination, relative (and relative to what) or absolute file path?

**Comment by ncw** [comment]
Filtering applies to the source, or more accurately it is applied during the listing process.

All paths in rclone are relative to the root of the remote - if you want to see what rclone is matching run `rclone ls` with your filters.
