### ISSUE TITLE
Team Drives: duplicate files with copyto and --ignore-times

### ISSUE THREAD

**Issue by jbd70** [ncw/rclone#3067]
#### What is the problem you are having with rclone?

`rclone copyto --ignore-times` creates duplicate files when doing server side copies from one team drive to another.

These messages are produced when copying duplicate files:

Across TDs: `Transferring unconditionally as --ignore-times is in use` (creates dupe)

Within My Drive: `don't need to copy/move <file>, it is already at target location` (no dupe)

Ideally these would behave the same. More importantly:

#### What am I trying to do?

Change the "creator" of all files in `td-dest:` -- a mirror of `td-source:` -- from a non-service account to a set of service accounts, on a schedule.

I'm able to achieve this (very inefficiently) using a script that:

- Takes input from `rclone lsjson -R td-source:`
- Creates server side copies using concurrent `copyto` commands, thus changing the "creator."

  - E.g.: `rclone copyto td-source:path/to/file td-dest:path/to/file --drive-service-account-file /path/to/service.json --ignore-times`

- Removes the old files using `rclone dedupe --dedupe-mode newest td-dest:`

What I would prefer to do is just overwrite the files on `td-dest:` in one go.

If this is possible, it might make sense for the `--no-traverse` flag to enable this behavior.

Should I create a separate feature request for this?

#### What is your rclone version (output from `rclone version`)

    rclone v1.46.0-103-g8d29d69a-beta
    - os/arch: linux/amd64
    - go version: go1.12.1

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

Debian 9 x64

#### Which cloud storage system are you using? (eg Google Drive)

Google Drive

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

Team drives

    rclone -vvv --log-file ~/Documents/rclone_issue_tds.log touch td-source-test:foo >>~/Documents/rclone_issue_tds.log
    rclone -vvv --log-file ~/Documents/rclone_issue_tds.log touch td-dest-test:foo >>~/Documents/rclone_issue_tds.log
    rclone -vvv --log-file ~/Documents/rclone_issue_tds.log lsl td-source-test: >>~/Documents/rclone_issue_tds.log
    rclone -vvv --log-file ~/Documents/rclone_issue_tds.log lsl td-dest-test: >>~/Documents/rclone_issue_tds.log
    rclone -vvv --log-file ~/Documents/rclone_issue_tds.log copyto td-source-test:foo td-dest-test:foo --ignore-times >>~/Documents/rclone_issue_tds.log
    rclone -vvv --log-file ~/Documents/rclone_issue_tds.log lsl td-dest-test: >>~/Documents/rclone_issue_tds.log
    rclone -vvv --log-file ~/Documents/rclone_issue_tds.log copyto td-source-test:foo td-dest-test:foo --ignore-times >>~/Documents/rclone_issue_tds.log
    rclone -vvv --log-file ~/Documents/rclone_issue_tds.log lsl td-dest-test: >>~/Documents/rclone_issue_tds.log
    rclone -vvv --log-file ~/Documents/rclone_issue_tds.log copyto td-source-test:foo td-dest-test:foo --ignore-times >>~/Documents/rclone_issue_tds.log
    rclone -vvv --log-file ~/Documents/rclone_issue_tds.log lsl td-dest-test: >>~/Documents/rclone_issue_tds.log

My Drive

    rclone -vvv --log-file ~/Documents/rclone_issue_mydrive.log touch mydrive:foo >>~/Documents/rclone_issue_mydrive.log
    rclone -vvv --log-file ~/Documents/rclone_issue_mydrive.log touch mydrive:foo >>~/Documents/rclone_issue_mydrive.log
    rclone -vvv --log-file ~/Documents/rclone_issue_mydrive.log lsl mydrive: >>~/Documents/rclone_issue_mydrive.log
    rclone -vvv --log-file ~/Documents/rclone_issue_mydrive.log lsl mydrive: >>~/Documents/rclone_issue_mydrive.log
    rclone -vvv --log-file ~/Documents/rclone_issue_mydrive.log copyto mydrive:foo mydrive:foo --ignore-times >>~/Documents/rclone_issue_mydrive.log
    rclone -vvv --log-file ~/Documents/rclone_issue_mydrive.log lsl mydrive: >>~/Documents/rclone_issue_mydrive.log
    rclone -vvv --log-file ~/Documents/rclone_issue_mydrive.log copyto mydrive:foo mydrive:foo --ignore-times >>~/Documents/rclone_issue_mydrive.log
    rclone -vvv --log-file ~/Documents/rclone_issue_mydrive.log lsl mydrive: >>~/Documents/rclone_issue_mydrive.log
    rclone -vvv --log-file ~/Documents/rclone_issue_mydrive.log copyto mydrive:foo mydrive:foo --ignore-times >>~/Documents/rclone_issue_mydrive.log
    rclone -vvv --log-file ~/Documents/rclone_issue_mydrive.log lsl mydrive: >>~/Documents/rclone_issue_mydrive.log

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

Team drives

    2019/03/22 16:39:20 DEBUG : rclone: Version "v1.46.0-103-g8d29d69a-beta" starting with parameters ["rclone" "-vvv" "--log-file" "/home/user/Documents/rclone_issue_tds.log" "touch" "td-source-test:foo"]
    2019/03/22 16:39:20 DEBUG : Using config file from "/home/user/.config/rclone/rclone.conf"
    2019/03/22 16:39:22 DEBUG : 4 go routines active
    2019/03/22 16:39:22 DEBUG : rclone: Version "v1.46.0-103-g8d29d69a-beta" finishing with parameters ["rclone" "-vvv" "--log-file" "/home/user/Documents/rclone_issue_tds.log" "touch" "td-source-test:foo"]
    2019/03/22 16:39:22 DEBUG : rclone: Version "v1.46.0-103-g8d29d69a-beta" starting with parameters ["rclone" "-vvv" "--log-file" "/home/user/Documents/rclone_issue_tds.log" "touch" "td-dest-test:foo"]
    2019/03/22 16:39:22 DEBUG : Using config file from "/home/user/.config/rclone/rclone.conf"
    2019/03/22 16:39:23 DEBUG : 4 go routines active
    2019/03/22 16:39:23 DEBUG : rclone: Version "v1.46.0-103-g8d29d69a-beta" finishing with parameters ["rclone" "-vvv" "--log-file" "/home/user/Documents/rclone_issue_tds.log" "touch" "td-dest-test:foo"]
    2019/03/22 16:39:23 DEBUG : rclone: Version "v1.46.0-103-g8d29d69a-beta" starting with parameters ["rclone" "-vvv" "--log-file" "/home/user/Documents/rclone_issue_tds.log" "lsl" "td-source-test:"]
    2019/03/22 16:39:23 DEBUG : Using config file from "/home/user/.config/rclone/rclone.conf"
            0 2019-03-22 16:39:20.577000000 foo
    2019/03/22 16:39:24 DEBUG : 4 go routines active
    2019/03/22 16:39:24 DEBUG : rclone: Version "v1.46.0-103-g8d29d69a-beta" finishing with parameters ["rclone" "-vvv" "--log-file" "/home/user/Documents/rclone_issue_tds.log" "lsl" "td-source-test:"]
    2019/03/22 16:39:24 DEBUG : rclone: Version "v1.46.0-103-g8d29d69a-beta" starting with parameters ["rclone" "-vvv" "--log-file" "/home/user/Documents/rclone_issue_tds.log" "lsl" "td-dest-test:"]
    2019/03/22 16:39:24 DEBUG : Using config file from "/home/user/.config/rclone/rclone.conf"
            0 2019-03-22 16:39:22.246000000 foo
    2019/03/22 16:39:24 DEBUG : 4 go routines active
    2019/03/22 16:39:24 DEBUG : rclone: Version "v1.46.0-103-g8d29d69a-beta" finishing with parameters ["rclone" "-vvv" "--log-file" "/home/user/Documents/rclone_issue_tds.log" "lsl" "td-dest-test:"]
    2019/03/22 16:39:24 DEBUG : rclone: Version "v1.46.0-103-g8d29d69a-beta" starting with parameters ["rclone" "-vvv" "--log-file" "/home/user/Documents/rclone_issue_tds.log" "copyto" "td-source-test:foo" "td-dest-test:foo" "--ignore-times"]
    2019/03/22 16:39:24 DEBUG : Using config file from "/home/user/.config/rclone/rclone.conf"
    2019/03/22 16:39:25 DEBUG : foo: Transferring unconditionally as --ignore-times is in use
    2019/03/22 16:39:26 INFO  : foo: Copied (server side copy)
    2019/03/22 16:39:26 INFO  :
    Transferred:   	         0 / 0 Bytes, -, 0 Bytes/s, ETA -
    Errors:                 0
    Checks:                 0 / 0, -
    Transferred:            1 / 1, 100%
    Elapsed time:        2.1s

    2019/03/22 16:39:26 DEBUG : 4 go routines active
    2019/03/22 16:39:26 DEBUG : rclone: Version "v1.46.0-103-g8d29d69a-beta" finishing with parameters ["rclone" "-vvv" "--log-file" "/home/user/Documents/rclone_issue_tds.log" "copyto" "td-source-test:foo" "td-dest-test:foo" "--ignore-times"]
    2019/03/22 16:39:26 DEBUG : rclone: Version "v1.46.0-103-g8d29d69a-beta" starting with parameters ["rclone" "-vvv" "--log-file" "/home/user/Documents/rclone_issue_tds.log" "lsl" "td-dest-test:"]
    2019/03/22 16:39:26 DEBUG : Using config file from "/home/user/.config/rclone/rclone.conf"
            0 2019-03-22 16:39:22.246000000 foo
            0 2019-03-22 16:39:20.577000000 foo
    2019/03/22 16:39:26 DEBUG : 4 go routines active
    2019/03/22 16:39:26 DEBUG : rclone: Version "v1.46.0-103-g8d29d69a-beta" finishing with parameters ["rclone" "-vvv" "--log-file" "/home/user/Documents/rclone_issue_tds.log" "lsl" "td-dest-test:"]
    2019/03/22 16:39:26 DEBUG : rclone: Version "v1.46.0-103-g8d29d69a-beta" starting with parameters ["rclone" "-vvv" "--log-file" "/home/user/Documents/rclone_issue_tds.log" "copyto" "td-source-test:foo" "td-dest-test:foo" "--ignore-times"]
    2019/03/22 16:39:26 DEBUG : Using config file from "/home/user/.config/rclone/rclone.conf"
    2019/03/22 16:39:28 DEBUG : foo: Transferring unconditionally as --ignore-times is in use
    2019/03/22 16:39:29 INFO  : foo: Copied (server side copy)
    2019/03/22 16:39:29 INFO  :
    Transferred:   	         0 / 0 Bytes, -, 0 Bytes/s, ETA -
    Errors:                 0
    Checks:                 0 / 0, -
    Transferred:            1 / 1, 100%
    Elapsed time:        2.2s

    2019/03/22 16:39:29 DEBUG : 4 go routines active
    2019/03/22 16:39:29 DEBUG : rclone: Version "v1.46.0-103-g8d29d69a-beta" finishing with parameters ["rclone" "-vvv" "--log-file" "/home/user/Documents/rclone_issue_tds.log" "copyto" "td-source-test:foo" "td-dest-test:foo" "--ignore-times"]
    2019/03/22 16:39:29 DEBUG : rclone: Version "v1.46.0-103-g8d29d69a-beta" starting with parameters ["rclone" "-vvv" "--log-file" "/home/user/Documents/rclone_issue_tds.log" "lsl" "td-dest-test:"]
    2019/03/22 16:39:29 DEBUG : Using config file from "/home/user/.config/rclone/rclone.conf"
            0 2019-03-22 16:39:22.246000000 foo
            0 2019-03-22 16:39:20.577000000 foo
            0 2019-03-22 16:39:20.577000000 foo
    2019/03/22 16:39:29 DEBUG : 4 go routines active
    2019/03/22 16:39:29 DEBUG : rclone: Version "v1.46.0-103-g8d29d69a-beta" finishing with parameters ["rclone" "-vvv" "--log-file" "/home/user/Documents/rclone_issue_tds.log" "lsl" "td-dest-test:"]
    2019/03/22 16:39:29 DEBUG : rclone: Version "v1.46.0-103-g8d29d69a-beta" starting with parameters ["rclone" "-vvv" "--log-file" "/home/user/Documents/rclone_issue_tds.log" "copyto" "td-source-test:foo" "td-dest-test:foo" "--ignore-times"]
    2019/03/22 16:39:29 DEBUG : Using config file from "/home/user/.config/rclone/rclone.conf"
    2019/03/22 16:39:30 DEBUG : foo: Transferring unconditionally as --ignore-times is in use
    2019/03/22 16:39:31 INFO  : foo: Copied (server side copy)
    2019/03/22 16:39:31 INFO  :
    Transferred:   	         0 / 0 Bytes, -, 0 Bytes/s, ETA -
    Errors:                 0
    Checks:                 0 / 0, -
    Transferred:            1 / 1, 100%
    Elapsed time:        1.9s

    2019/03/22 16:39:31 DEBUG : 4 go routines active
    2019/03/22 16:39:31 DEBUG : rclone: Version "v1.46.0-103-g8d29d69a-beta" finishing with parameters ["rclone" "-vvv" "--log-file" "/home/user/Documents/rclone_issue_tds.log" "copyto" "td-source-test:foo" "td-dest-test:foo" "--ignore-times"]
    2019/03/22 16:39:31 DEBUG : rclone: Version "v1.46.0-103-g8d29d69a-beta" starting with parameters ["rclone" "-vvv" "--log-file" "/home/user/Documents/rclone_issue_tds.log" "lsl" "td-dest-test:"]
    2019/03/22 16:39:31 DEBUG : Using config file from "/home/user/.config/rclone/rclone.conf"
            0 2019-03-22 16:39:22.246000000 foo
            0 2019-03-22 16:39:20.577000000 foo
            0 2019-03-22 16:39:20.577000000 foo
            0 2019-03-22 16:39:20.577000000 foo
    2019/03/22 16:39:31 DEBUG : 4 go routines active
    2019/03/22 16:39:31 DEBUG : rclone: Version "v1.46.0-103-g8d29d69a-beta" finishing with parameters ["rclone" "-vvv" "--log-file" "/home/user/Documents/rclone_issue_tds.log" "lsl" "td-dest-test:"]

My Drive

    2019/03/22 16:43:02 DEBUG : rclone: Version "v1.46.0-103-g8d29d69a-beta" starting with parameters ["rclone" "-vvv" "--log-file" "/home/user/Documents/rclone_issue_mydrive.log" "touch" "mydrive:foo"]
    2019/03/22 16:43:02 DEBUG : Using config file from "/home/user/.config/rclone/rclone.conf"
    2019/03/22 16:43:02 DEBUG : mydrive: Loaded invalid token from config file - ignoring
    2019/03/22 16:43:02 DEBUG : Keeping previous permissions for config file: -rw-r--r--
    2019/03/22 16:43:02 DEBUG : mydrive: Saved new token in config file
    2019/03/22 16:43:04 DEBUG : 6 go routines active
    2019/03/22 16:43:04 DEBUG : rclone: Version "v1.46.0-103-g8d29d69a-beta" finishing with parameters ["rclone" "-vvv" "--log-file" "/home/user/Documents/rclone_issue_mydrive.log" "touch" "mydrive:foo"]
    2019/03/22 16:43:04 DEBUG : rclone: Version "v1.46.0-103-g8d29d69a-beta" starting with parameters ["rclone" "-vvv" "--log-file" "/home/user/Documents/rclone_issue_mydrive.log" "touch" "mydrive:foo"]
    2019/03/22 16:43:04 DEBUG : Using config file from "/home/user/.config/rclone/rclone.conf"
    2019/03/22 16:43:05 DEBUG : 4 go routines active
    2019/03/22 16:43:05 DEBUG : rclone: Version "v1.46.0-103-g8d29d69a-beta" finishing with parameters ["rclone" "-vvv" "--log-file" "/home/user/Documents/rclone_issue_mydrive.log" "touch" "mydrive:foo"]
    2019/03/22 16:43:05 DEBUG : rclone: Version "v1.46.0-103-g8d29d69a-beta" starting with parameters ["rclone" "-vvv" "--log-file" "/home/user/Documents/rclone_issue_mydrive.log" "lsl" "mydrive:"]
    2019/03/22 16:43:05 DEBUG : Using config file from "/home/user/.config/rclone/rclone.conf"
            0 2019-03-22 16:43:04.488000000 foo
    2019/03/22 16:43:06 DEBUG : 4 go routines active
    2019/03/22 16:43:06 DEBUG : rclone: Version "v1.46.0-103-g8d29d69a-beta" finishing with parameters ["rclone" "-vvv" "--log-file" "/home/user/Documents/rclone_issue_mydrive.log" "lsl" "mydrive:"]
    2019/03/22 16:43:06 DEBUG : rclone: Version "v1.46.0-103-g8d29d69a-beta" starting with parameters ["rclone" "-vvv" "--log-file" "/home/user/Documents/rclone_issue_mydrive.log" "lsl" "mydrive:"]
    2019/03/22 16:43:06 DEBUG : Using config file from "/home/user/.config/rclone/rclone.conf"
            0 2019-03-22 16:43:04.488000000 foo
    2019/03/22 16:43:06 DEBUG : 4 go routines active
    2019/03/22 16:43:06 DEBUG : rclone: Version "v1.46.0-103-g8d29d69a-beta" finishing with parameters ["rclone" "-vvv" "--log-file" "/home/user/Documents/rclone_issue_mydrive.log" "lsl" "mydrive:"]
    2019/03/22 16:43:06 DEBUG : rclone: Version "v1.46.0-103-g8d29d69a-beta" starting with parameters ["rclone" "-vvv" "--log-file" "/home/user/Documents/rclone_issue_mydrive.log" "copyto" "mydrive:foo" "mydrive:foo" "--ignore-times"]
    2019/03/22 16:43:06 DEBUG : Using config file from "/home/user/.config/rclone/rclone.conf"
    2019/03/22 16:43:07 DEBUG : Google drive root '': don't need to copy/move foo, it is already at target location
    2019/03/22 16:43:07 INFO  :
    Transferred:   	         0 / 0 Bytes, -, 0 Bytes/s, ETA -
    Errors:                 0
    Checks:                 0 / 0, -
    Transferred:            0 / 0, -
    Elapsed time:        1.2s

    2019/03/22 16:43:07 DEBUG : 4 go routines active
    2019/03/22 16:43:07 DEBUG : rclone: Version "v1.46.0-103-g8d29d69a-beta" finishing with parameters ["rclone" "-vvv" "--log-file" "/home/user/Documents/rclone_issue_mydrive.log" "copyto" "mydrive:foo" "mydrive:foo" "--ignore-times"]
    2019/03/22 16:43:07 DEBUG : rclone: Version "v1.46.0-103-g8d29d69a-beta" starting with parameters ["rclone" "-vvv" "--log-file" "/home/user/Documents/rclone_issue_mydrive.log" "lsl" "mydrive:"]
    2019/03/22 16:43:07 DEBUG : Using config file from "/home/user/.config/rclone/rclone.conf"
            0 2019-03-22 16:43:04.488000000 foo
    2019/03/22 16:43:08 DEBUG : 4 go routines active
    2019/03/22 16:43:08 DEBUG : rclone: Version "v1.46.0-103-g8d29d69a-beta" finishing with parameters ["rclone" "-vvv" "--log-file" "/home/user/Documents/rclone_issue_mydrive.log" "lsl" "mydrive:"]
    2019/03/22 16:43:08 DEBUG : rclone: Version "v1.46.0-103-g8d29d69a-beta" starting with parameters ["rclone" "-vvv" "--log-file" "/home/user/Documents/rclone_issue_mydrive.log" "copyto" "mydrive:foo" "mydrive:foo" "--ignore-times"]
    2019/03/22 16:43:08 DEBUG : Using config file from "/home/user/.config/rclone/rclone.conf"
    2019/03/22 16:43:09 DEBUG : Google drive root '': don't need to copy/move foo, it is already at target location
    2019/03/22 16:43:09 INFO  :
    Transferred:   	         0 / 0 Bytes, -, 0 Bytes/s, ETA -
    Errors:                 0
    Checks:                 0 / 0, -
    Transferred:            0 / 0, -
    Elapsed time:       600ms

    2019/03/22 16:43:09 DEBUG : 4 go routines active
    2019/03/22 16:43:09 DEBUG : rclone: Version "v1.46.0-103-g8d29d69a-beta" finishing with parameters ["rclone" "-vvv" "--log-file" "/home/user/Documents/rclone_issue_mydrive.log" "copyto" "mydrive:foo" "mydrive:foo" "--ignore-times"]
    2019/03/22 16:43:09 DEBUG : rclone: Version "v1.46.0-103-g8d29d69a-beta" starting with parameters ["rclone" "-vvv" "--log-file" "/home/user/Documents/rclone_issue_mydrive.log" "lsl" "mydrive:"]
    2019/03/22 16:43:09 DEBUG : Using config file from "/home/user/.config/rclone/rclone.conf"
            0 2019-03-22 16:43:04.488000000 foo
    2019/03/22 16:43:09 DEBUG : 4 go routines active
    2019/03/22 16:43:09 DEBUG : rclone: Version "v1.46.0-103-g8d29d69a-beta" finishing with parameters ["rclone" "-vvv" "--log-file" "/home/user/Documents/rclone_issue_mydrive.log" "lsl" "mydrive:"]
    2019/03/22 16:43:09 DEBUG : rclone: Version "v1.46.0-103-g8d29d69a-beta" starting with parameters ["rclone" "-vvv" "--log-file" "/home/user/Documents/rclone_issue_mydrive.log" "copyto" "mydrive:foo" "mydrive:foo" "--ignore-times"]
    2019/03/22 16:43:09 DEBUG : Using config file from "/home/user/.config/rclone/rclone.conf"
    2019/03/22 16:43:10 DEBUG : Google drive root '': don't need to copy/move foo, it is already at target location
    2019/03/22 16:43:10 INFO  :
    Transferred:   	         0 / 0 Bytes, -, 0 Bytes/s, ETA -
    Errors:                 0
    Checks:                 0 / 0, -
    Transferred:            0 / 0, -
    Elapsed time:       600ms

    2019/03/22 16:43:10 DEBUG : 4 go routines active
    2019/03/22 16:43:10 DEBUG : rclone: Version "v1.46.0-103-g8d29d69a-beta" finishing with parameters ["rclone" "-vvv" "--log-file" "/home/user/Documents/rclone_issue_mydrive.log" "copyto" "mydrive:foo" "mydrive:foo" "--ignore-times"]
    2019/03/22 16:43:10 DEBUG : rclone: Version "v1.46.0-103-g8d29d69a-beta" starting with parameters ["rclone" "-vvv" "--log-file" "/home/user/Documents/rclone_issue_mydrive.log" "lsl" "mydrive:"]
    2019/03/22 16:43:10 DEBUG : Using config file from "/home/user/.config/rclone/rclone.conf"
            0 2019-03-22 16:43:04.488000000 foo
    2019/03/22 16:43:10 DEBUG : 4 go routines active
    2019/03/22 16:43:10 DEBUG : rclone: Version "v1.46.0-103-g8d29d69a-beta" finishing with parameters ["rclone" "-vvv" "--log-file" "/home/user/Documents/rclone_issue_mydrive.log" "lsl" "mydrive:"]

**Comment by ncw** [comment]
> `rclone copyto --ignore-times` creates duplicate files when doing server side copies from one team drive to another.

Yes you are right.  The underlying server side copy mechanism in the drive backend does not check for an existing file.  This means that it will upload a duplicate.

I think what is required is that the server side copy routine
- checks for an existing file, if it exists it stores the ID
- does the server side copy
- if successful remove the file with the stored ID

I implemented this here - does it work for you?

https://beta.rclone.org/branch/v1.46.0-109-g1b5b9f13-fix-3067-drive-copy-beta/ (uploaded in 15-30 mins)

I'm not 100% happy with this as it does an extra transaction but to fix that I'd need to change the internal API for server side copy.

**Comment by zen-jd** [comment]
Just tested, works great. Thanks!

**Comment by jbd70** [comment]
Works great, thank you!

**Comment by ncw** [comment]
I've merged this to master now which means it will be in [the latest beta](https://beta.rclone.org) in 15-30 mins and released in v1.47

Thanks for testing
