### ISSUE TITLE
Jottacloud: Add mountpoint "Backed up files"

### ISSUE THREAD

**Issue by CHRONiCiTY** [ncw/rclone#3069]
#### What is your current rclone version (output from `rclone version`)?
rclone v1.46
- os/arch: freebsd/amd64
- go version: go1.11.5

#### What problem are you are trying to solve?
As I've previously only used the Jottacloud desktop client to back up my files, all my files are now in the section "Backed up files", under a device name which gets automatically created from the computer name running the client.
I do not use "Sync" as you can only use it for ONE folder and you also can't use file/folder exclusions.
I also do not use the "Archive" since the desktop client cannot directly upload to Archive anyway, files can only be moved to "Archive" from "Backed up files" manually through the Jottacloud website which renders the feature pretty much useless. You also can't move them back to "Backed up files" once done.

As I now want to use rclone instead, and rclone for some reason doesn't have that section available under mount points, I'd end up uploading everything again and then have duplicates as rclone doesn't checksum against the files already there under "Backed up files".
That's just not very feasible with large backups.

#### How do you think rclone should be changed to solve that?
Add "Backed up files" to the mount point selection in rclone config for Jottacloud remotes.
Also adding the ability to add devices (computer name) would probably solve the bug about not being to able to use rclone from two rclone sessions at the same time since they would have separate device names.

Jottaclouds own command line client has both these features but unfortunately it really blows in every other way.

**Comment by ncw** [comment]
You can put in your own value for the `mountpoint` configuration - did you try putting in the name of your device name you see in the web interface?

**Comment by CHRONiCiTY** [comment]
> 
> 
> You can put in your own value for the `mountpoint` configuration - did you try putting in the name of your device name you see in the web interface?

That's pretty much the first thing I tried. Added a mountpoint 'backup' as that's what the URL says when you click "Backed up files", just like "Archive" says 'archive' and "Sync" says 'sync'. That didn't work.
I also just now tried adding the device name and then also what the URL for that device name says but neither work unfortunately.

**Comment by ncw** [comment]
@buengese and @olihey do you have an ideas on how to mount your backed up files on Jottacloud?

**Comment by CHRONiCiTY** [comment]
You can access jottacloud's xml output by going to https://www.jottacloud.com/jfs/yourjottausername/ and there you'll have a list of any devices you have on your account. The default mountpoints Archive and Sync are located under a default "device" called Jotta so the URL becomes either https://www.jottacloud.com/jfs/yourjottausername/**jotta**/archive/ or https://www.jottacloud.com/jfs/yourjottausername/**jotta**/sync/.

Devices that have been created by the desktop client do not end up in the jotta path, they end up directly under https://www.jottacloud.com/jfs/yourjottausername/**devicename**/

I'm not a programmer or coder to save my life but looking at the source files of rclone, it looks like maybe the jottacloud remote is hardcoded to use the path **jotta** before any mountpoint you select or add in the remote config so by trying to add your device name as a mountpoint you end up at https://www.jottacloud.com/jfs/yourjottausername/jotta/devicename/ which obviously won't work.

It might be as simple as allowing users to select the device (and then maybe + mountpoint) in the remote config. Or maybe there might be some restrictions on jottacloud's side for accessing any "device" other than the default jotta when using anything else except the desktop client.

**Comment by CHRONiCiTY** [comment]
Hehe, I actually managed to trick the remote config to go up a directory.
Your device page by itself won't list anything as you still need to add in the mountpoint but by adding **../**DEVICENAME/ONEOFMYMOUNTPOINTS as the mountpoint in the remote config I was able to access my files under that particular mountpoint.
Becomes a hassle though if you have several mountpoint like I do, I guess I would have to clone the remote for every mountpoint I have. :)

**Comment by buengese** [comment]
Jottacloud has this concept of devices which are supposed to represent different instances of the official client. Mount points are specific to a device. We currently don't support this concept at all instead we use the "Jotta" device for all operations. The "Jotta" device is special and contains the Archive, Sync and Shared mount points visible in the Web UI but has no access to backup mount points of other devices. What is required here is proper support for different devices which I'd planned for a while but just haven't had the time to do yet.

Also I really couldn't think of an intuitive way the implement this when I initially wrote the Jottacloud client given the fact that both devices and mount points are can technically by the user and are almost (but not quite) like normal directories.

**Comment by CHRONiCiTY** [comment]
Dang, I thought I could make it work with my "clever" workaround but actually copying anything to it fails with this fun message:
ERROR : Attempt 1/3 failed with 1 errors and: HTTP error 404 (404 Not Found) returned body: "{\"code\":404,\"message\":\"Invalid path: ../DEVICENAME/MOUNTPOINT/DIR/File.file\",\"cause\":\"\",\"error_id\":\"NoSuchFileException\",\"x-id\":\"b2-4ODldg3p7RxZ\"}"

Weird that other commands like listing stuff works though! Back on square one. :(

**Comment by olihey** [comment]
You can cheat a bit
I have a device "WINAS" in my backup folder. When you setup the remote use the following as mountpoint `../<DEVICENAME>/`, so in my case `../WINAS/`.
Now, somehow you can't see the root listing for the backup of your device, but if you directly ask for a folder in the root of your backup it works.
So, In my WINAS backup I have two folder, `scripts` and `Shared`. And I can get the listings like this (I called my remote `jb`:
```
D:\scripts>rclone.exe ls jb:/scripts/
      590 backup.sh
     2965 cloudbackup.cmd
     2040 cloudbackup.sh
     2804 exif.py
  8271392 exiftool.exe
 61480960 ffmpeg.exe
      257 jdownloader2.service
      939 n26_to_sage_convert.py
     8756 papershift.py
   119501 rapidmovies.json
     3195 rapidmovies.py
 26780160 rclone-beta.exe
     1681 rclone.conf
 24131072 rclone.exe
     5321 sample.xlsx
      177 sshsocks.service
     8158 tvnas.py
     8147 tvnas_old.py
     7552 tvup.py
```

**Comment by CHRONiCiTY** [comment]
> 
> 
> You can cheat a bit
> I have a device "WINAS" in my backup folder. When you setup the remote use the following as mountpoint `../<DEVICENAME>/`, so in my case `../WINAS/`.
> Now, somehow you can't see the root listing for the backup of your device, but if you directly ask for a folder in the root of your backup it works.
> So, In my WINAS backup I have two folder, `scripts` and `Shared`. And I can get the listings like this (I called my remote `jb`:
> 
> ```
> D:\scripts>rclone.exe ls jb:/scripts/
>       590 backup.sh
>      2965 cloudbackup.cmd
>      2040 cloudbackup.sh
>      2804 exif.py
>   8271392 exiftool.exe
>  61480960 ffmpeg.exe
>       257 jdownloader2.service
>       939 n26_to_sage_convert.py
>      8756 papershift.py
>    119501 rapidmovies.json
>      3195 rapidmovies.py
>  26780160 rclone-beta.exe
>      1681 rclone.conf
>  24131072 rclone.exe
>      5321 sample.xlsx
>       177 sshsocks.service
>      8158 tvnas.py
>      8147 tvnas_old.py
>      7552 tvup.py
> ```

If you check my reply above you'll see that actually copying to it won't work.
I actually compiled rclone from source and modified the devicename in jottacloud.go to match mine but I'm still getting the above error when actually trying to copy something to one of my mountpoints.

I think I've gotten as far as I can with this on my own. :(

**Comment by BartSiwek** [comment]
Not exactly contributing to the discussion, but I tried more or less the same things as @CHRONiCiTY and would like this feature as well.

**Comment by BartSiwek** [comment]
I was thinking about contributing but it seems the API is not documented enough for me to o that.
I was able to figure out that we need to [create a device](https://github.com/ttyridal/aiojotta/wiki/Jotta-protocol-4.2-JFS-operations#create-device) and [create a mountpoint](https://github.com/ttyridal/aiojotta/wiki/Jotta-protocol-4.2-JFS-operations#create-mountpoint) which works fine.
After that we should start uploading files, but I can't seem to find a way to make calls to https://api.jottacloud.com/files/v1/allocate use a non-default device.

Duplicati seems to not be using the api.jottacloud.com and goes straight to up.jottacloud.com.

Any advice on the matter?

**Comment by olihey** [comment]
@BartSiwek We switched to api.jottacloud.com to support resume of uploads. That's the only reason.

My gut feeling is the following, the upload to backup is only allowed for the same device. So, if you have the offical JottaClient doing backups for a certain device, this devices gets an unique client_id/client_secret similar to the new setup process in rclone. I assume that when you try to upload a file into a backup (directory) from a another client the backend will not allow this.

Since Archive and Sync are suppose to be used from multiple client the upload/download from any client registered for the account works.

You might can try using an pre 1.4.6 version of rclone to play around which is not using the API endpoint at all or try to sniff the client_id / client_secret from the device your want to access the backups from.

**Comment by ncw** [comment]
@buengese has made an attempt to implement this.

Any testing appreciated :-)

https://beta.rclone.org/branch/v1.47.0-075-g854d083d-jotta_mountpoints-beta/ (uploaded in 15-30 mins) (uploaded in 15-30 mins)
