### ISSUE TITLE
Support for Jottacloud

### ISSUE THREAD

**Issue by cowai** [ncw/rclone#307]
Hi,
I just wanted to show you my interest in https://www.jottacloud.com as it would in my opinion, fit very well with rclone.
The deal is unlimited (although I've heard they stop you at ~10TB) backup for 7.5euros/month. So for those with a lot of data, this seems comparable to Hubic.
 There is a python library that can be used as a reference of the API: https://github.com/havardgulldahl/jottalib. 

Jottacloud is known for its privacy concerns and has a "Canary" on its blog too: https://www.jottacloud.com/blog.

Maybe this could be of interest?

**Comment by ncw** [comment]
I had a brief look at the python code and it looks like rclone could interface with it.  Having no official API documentation is a little unusual, but the python code is better than nothing!

**Comment by cowai** [comment]
Yes it's a shame there is no official document on this.
But @havardgulldahl has most of the cases covered in his code.

If this had been a random cloud provider offering 100GB for ~10 euros/month then I wouldn't care for this at all. But it is'nt, its a really good deal :)

**Comment by havardgulldahl** [comment]
This is really interesting. From the perspective of `jottalib`, just getting the extensive test suite of rclone to run without errors would be a great boon.

So please let me know if there's anything we should do to help out with the integration. 

And file issues over at https://github.com/havardgulldahl/jottalib/issues if there's anything amiss. 

Thanks!

**Comment by pedrosimao** [comment]
Considering the ACD shut down, I think this Issue is back to life?

**Comment by ziziz** [comment]
I dont know how I managed before 'unlimited storage'. Support for rklone in Jottacloud would be a upgrade to my whole digital life :-)

**Comment by jkaberg** [comment]
The storage limit has since then been removed from the TOS, now they operate with an "fair use" policy.

> Users with an Individual account may use the Service for normal individual usage. Although Jottacloud does not limit bandwidth or storage on Unlimited subscription plans, we reserve the right to limit excessive use and abuse of the Service. If a user’s total storage and network usage greatly exceeds the normal usage of an average Jottacloud user, and/or indicates that the Service is being uses for other than normal individual use, this may in some cases be deemed as abuse of the Service.

https://www.jottacloud.com/en/terms.html

**Comment by ncw** [comment]
I'm going to close this since it is all working :-)
