### ISSUE TITLE
Document rclone exit code

### ISSUE THREAD

**Issue by ncw** [ncw/rclone#308]
Document that rclone sets non zero exit code on errors

**Comment by kflu** [comment]
The "fix" only says in case of failure a non-zero exit code is returned, that's not so useful. 

Can each non-zero exit code and its failure reason be clearly documented, or as least mention which source file to look at for the mapping from error codes to failure reasons.

**Comment by ncw** [comment]
@kflu I've fixed the documentation here: http://rclone.org/docs/#exit-code
