### ISSUE TITLE
rclone mount is not working for mega.nz

### ISSUE THREAD

**Issue by kyaky** [ncw/rclone#3080]
#### What is the problem you are having with rclone?

rclone mount is not working for mega.nz

#### What is your rclone version (output from `rclone version`)

rclone v1.46
- os/arch: linux/amd64
- go version: go1.11.5

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

CentOS

####  Which cloud storage system are you using? (eg Google Drive)

Mega.nz

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

clone mount mega: /mnt/mega

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

[root@hpws mnt]# rclone -vv mount mega: /mnt/mega --debug-fuse --mega-debug
2019/03/28 12:19:26 DEBUG : rclone: Version "v1.46" starting with parameters ["rclone" "-vv" "mount" "mega:" "/mnt/mega" "--debug-fuse" "--mega-debug"]
2019/03/28 12:19:26 DEBUG : Using config file from "/root/.config/rclone/rclone.conf"
2019/03/28 12:19:29 DEBUG : *go-mega*: Waiting for events to be finished for 5s
2019/03/28 12:19:29 DEBUG : *go-mega*: Signalling events received
2019/03/28 12:19:29 DEBUG : *go-mega*: Events received

#it's stuck at "Event received"

**Comment by ncw** [comment]
Does

    rclone lsf mega:

Do something sensible (list your files)?

**Comment by kyaky** [comment]
thanks for your reply, NCW.

"rclone lsf mega: " works, but just the mount doesn't work and not showing anything.

**Comment by kyaky** [comment]
just a update on how to reproduce this problem.

sudo mkdir /mnt/megamount
sudo rclone mount MegaProfile:Directory /mnt/megamount &

it works for the first time.

if process killed or terminated, and try the above command to mount again, it returns:

Fatal error: Can not open: /mnt/megamount: open /mnt/megamount: transport endpoint is not connected

**Comment by kyaky** [comment]
problem solved by clear mount point

**Comment by Slikkit** [comment]
Apologies to resurrect such an old thread. 

What do you mean by "problem solved by clear mount point" ?

Can you please provide the command? I am having the same issues. `rclone ls remote:/` This works find, but I can't seem to mount this remote.
