### ISSUE TITLE
Rclone Sync Stuck At 99%

### ISSUE THREAD

**Issue by Cubuss** [ncw/rclone#3081]
#### What is the problem you are having with rclone?
rcclone sync keeps hanging on the last file stuck at 99%

#### What is your rclone version (output from `rclone version`)

Rclone 1.46

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Windows 10 64 bit

####  Which cloud storage system are you using? (eg Google Drive)
Google Drive

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

rclone -vP sync gdrive:/directory gdrive:/directry-v

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
Transferred:            0 / 1

**Comment by Cubuss** [comment]
https://imgur.com/a/fPfLEwO

**Comment by animosity22** [comment]
Do you have the logs ?

**Comment by Cubuss** [comment]
https://pastebin.com/VrZkfGU6

**Comment by animosity22** [comment]
Missing a lot of the log there which has your command you are running so a bit of guessing.

You should use your own API key.
You are getting a lot of rate limit errors so you are seeing it 'stuck' because it's constantly retrying and sleeping for long periods of time.
You can only transfer 750GB per day and you'll see 403 rate limits once you hit that error, which also slows things down.

Seeing the full command would really help.

**Comment by Cubuss** [comment]
> 
> 
> Missing a lot of the log there which has your command you are running so a bit of guessing.
> 
> You should use your own API key.
> You are getting a lot of rate limit errors so you are seeing it 'stuck' because it's constantly retrying and sleeping for long periods of time.
> You can only transfer 750GB per day and you'll see 403 rate limits once you hit that error, which also slows things down.
> 
> Seeing the full command would really help.

Im getting this daily even tough i havent reached the google drive bandiwht limit,

Also im getting the same when i use `--bwlimit=8.5m`

**Comment by animosity22** [comment]
Seeing the full command you are running would be super helpful.

**Comment by Cubuss** [comment]
> 
> 
> Seeing the full command you are running would be super helpful.

rclone -vP --bwlimit=8.5m sync gdrive:/location gdrive:/location -vv

**Comment by animosity22** [comment]
You should create and use your own API key as that will help with the rate limiting errors.

https://rclone.org/drive/#making-your-own-client-id

Google only allows ~3 file creations per second and you can only push about 10 transactions per second. 

You'd want to turn down the transfers or checkers to remove some of the 403s and use 5/5 or something along those lines.

If you re-run it with your own key and share the debug log, we can see what it is doing.

**Comment by Cubuss** [comment]
used own API key and its wroking normaly now
