### ISSUE TITLE
add encrypted path to the lsjson output

### ISSUE THREAD

**Issue by calisro** [ncw/rclone#3094]
For hte lsjson output, it would be good to be able to use it to trace where in a path a file is located and match that against the encrypted names.  Since rclone already has this data it should be fairly easy to add to the output for a new field so as not to break existing code that relies on that output.  My suggestion is that it is structured exactly like the existing unencrypted 'path'  (which goes all the way to include the file/directory name) so as to be consistent.

https://forum.rclone.org/t/encrypt-file-names-on-crypt-google-drive/9418/12

**Comment by ncw** [comment]
I think that the `lsjson --encrypted` flag is what you want.  If you use that on a crypt remote, it will show the encrypted file names...

**Comment by calisro** [comment]
That will give the encrypted name without the encrypted path. I was looking for the path as well.

**Comment by ncw** [comment]
> @ncw Let me know if you're okay with a pull request for this to add the path.

Yes please - that would be great!

**Comment by calisro** [comment]
https://github.com/ncw/rclone/pull/3108

Done.
