### ISSUE TITLE
What's next in testing rclone for Drive?

### ISSUE THREAD

**Issue by ChrisSLT** [ncw/rclone#31]
Hi Nick,
 It looks like rclone is doing better with Drive.  I would like to move it into a production environment where I'd script uploads and downloads with Drive.  Before doing so, I wanted to know if you had any reservations based on how it's working for you?  Are there any tests you'd like help running?

1 question is whether, if it encounters errors, it will automatically re-run?

Thanks again for all of this great work.

**Comment by ncw** [comment]
Drive is working much better than it used to.

It isn't perfect though - I have some more improvements I'd like to make.

However if it fails to upload a file, re-running rclone will fix it.

So if you are worried about that, you could run rclone more than once in your script - the first time it will almost always transfer everything, but if it didn't you could run it again.

I could implement a `--retries N` flag which would make rclone retry a sync until successful or it tried N times.

So I think you should give it a go, and if you find bugs, then please report them!

**Comment by ChrisSLT** [comment]
I think the --retries flag just as you describe it above would be great.

I'll give it a go.  

Again - really great tool, much appreciated.

**Comment by ncw** [comment]
Let me know if you have any problems.

I've made a note of the `--retries` idea in the notes.txt file so I'll close this now.
