### ISSUE TITLE
Rclone doesn't act properly when using --files-from when copying from GDrive with lots of files.

### ISSUE THREAD

**Issue by bmmcginty** [ncw/rclone#3102]
#### What is the problem you are having with rclone?
When copying files from a large remote, --include-from doesn't work as expected.
Each remote file gets queried separately, before the main transfer even starts.
See discussion here:
https://forum.rclone.org/t/is-it-possible-to-disable-checkers/9413

#### What is your rclone version (output from `rclone version`)
rclone v1.46
- os/arch: linux/amd64
- go version: go1.12.1 

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Debian Linux, 64 bit

####  Which cloud storage system are you using? (eg Google Drive)
Google Drive

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone copy gdrive:test/ copy2/ --files-from ls2.txt -v -v --stats 10s --log-file log.download2.5m.fastlist --fast-list

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
Attached. It's large, because this problem only shows up once you have a certain number of files in your remote, that you're trying to pull.
[rclone.log](https://github.com/ncw/rclone/files/3051890/rclone.log)

**Comment by calisro** [comment]
I'm also experiencing this.  The process I use has been in place for years.  Suddenly anything around over 200 files in the --files-from starts spitting pacer messages that never complete.  It seems like something merged in the past couple months in the beta has introduced this behavior as this process was always using thousands in the files-from.

+ rclone -vv --drive-use-trash=false --low-level-retries 2 --retries 2 --ignore-times --files-from xxxx move xxxxx xxxxx
2019/04/08 11:29:30 DEBUG : rclone: Version "v1.46.0-069-g229898dc-beta" starting with parameters ["rclone" "-vv" "--drive-use-trash=false" "--low-level-retries" "2" "--retries" "2" "--ignore-times" "--files-from" "xxxx" "move" "xxxx" "xxxx"]
2019/04/08 11:29:30 DEBUG : Using config file from "/root/.rclone.conf"
2019/04/08 11:29:30 INFO  : Starting bandwidth limiter at 8MBytes/s
2019/04/08 11:29:39 DEBUG : pacer: Reducing sleep to 58.734471ms
2019/04/08 11:29:39 DEBUG : pacer: Reducing sleep to 149.168649ms
2019/04/08 11:29:39 DEBUG : pacer: Reducing sleep to 243.015531ms
2019/04/08 11:29:39 DEBUG : pacer: Reducing sleep to 196.892494ms
2019/04/08 11:29:39 DEBUG : pacer: Reducing sleep to 266.978008ms
2019/04/08 11:29:39 DEBUG : pacer: Reducing sleep to 359.503301ms
2019/04/08 11:29:40 DEBUG : pacer: Reducing sleep to 205.654928ms
2019/04/08 11:29:40 DEBUG : pacer: Reducing sleep to 0s
2019/04/08 11:29:40 DEBUG : pacer: Reducing sleep to 75.290874ms
2019/04/08 11:29:40 DEBUG : pacer: Reducing sleep to 100.409309ms
2019/04/08 11:29:40 DEBUG : pacer: Reducing sleep to 140.106659ms
2019/04/08 11:29:41 DEBUG : pacer: Reducing sleep to 209.219919ms
2019/04/08 11:29:41 DEBUG : pacer: Reducing sleep to 272.228499ms
2019/04/08 11:29:41 DEBUG : pacer: Reducing sleep to 341.953162ms
2019/04/08 11:29:41 DEBUG : pacer: Reducing sleep to 281.33635ms
2019/04/08 11:29:41 DEBUG : pacer: Reducing sleep to 155.352457ms

**Comment by ncw** [comment]
This change was made in c5ac96e9e7afd2e11b69233ed3671e8ad05d24a9 which was released in v1.45.

> Make --files-from only read the objects specified and don't scan directories
> 
> Before this change using --files-from would scan all the directories
> that the files could possibly be in causing rclone to do more work
> that was necessary.
> 
> After this change, rclone constructs an in memory tree using the
> --fast-list mechanism but from all of the files in the --files-from
> list and without scanning any directories.
> 
> Any objects that are not found in the --files-from list are ignored
> silently.
> 
> This mechanism is used for sync/copy/move (march) and all of the
> listing commands ls/lsf/md5sum/etc (walk).

It came up in the forum too:

https://forum.rclone.org/t/using-files-from-with-drive-hammers-the-api/8726

And here is a potential fix using the `--files-from-no-traverse` flag

https://beta.rclone.org/branch/v1.46.0-019-gf97cbd3b-fix-files-from-traverse-beta/

I wonder whether I made a mistake with the new `--files-from` behaviour, or should add some heuristic to turn it on and off...

Perhaps `--fast-list` should turn it off and force it to use the whole listing...

And there is a very similar issue here #3095

Any thoughts?  Should I
- disable the new behaviour?
- disable it just for google drive?
- disable it with a heuristic of some kind?
- disable it with a flag?

Any other ideas?

**Comment by ncw** [comment]
I warmed up the beta here

https://beta.rclone.org/branch/v1.46.0-114-geb6ff029-fix-files-from-traverse-beta/ (uploaded in 15-30 mins)

Enable the workaround with `--files-from-traverse`

**Comment by bmmcginty** [comment]
I honestly thought at first that --files-from was a simpler version of --include-from. Maybe the new behavior (the gdrive error causing one) should be disabled on any remote that requires you to poll metadata for each file separately? I seem to recall that that's what this was doing.

**Comment by ncw** [comment]
> I honestly thought at first that --files-from was a simpler version of --include-from.

Yes and that is exactly what it was until the change...

Maybe the best course of action would be to only enable the new behaviour if the user supplies the [--no-traverse](https://rclone.org/docs/#no-traverse) flag making it opt-in rather than opt-out.  That would probably make a lot of sense.

**Comment by ncw** [comment]
I've fixed this here - testing appreciated :-) I changed tack and made the default behavior as it was, and you'll need the `--no-traverse flag` to enable the new behaviour.  So in your case you don't want the `--no-traverse` flag.

    filter: Make --files-from traverse as before unless --no-traverse is set
    
    In c5ac96e9e7 we made --files-from only read the objects specified and
    don't scan directories.
    
    This caused problems with Google drive (very very slow) and B2
    (excessive API consumption) so it was decided to make the old
    behaviour (traversing the directories) the default with --files-from
    and use the existing --no-traverse flag (which has exactly the right
    semantics) to enable the new non scanning behaviour.


https://beta.rclone.org/branch/v1.46.0-114-gc7bf473c-fix-files-from-traverse-beta/ (uploaded in 15-30 mins)

**Comment by ncw** [comment]
I've merged this to master now which means it will be in [the latest beta](https://beta.rclone.org) in 15-30 mins and released in v1.47
