### ISSUE TITLE
moveto deletes file when trying to do a case-sensitive rename. 

### ISSUE THREAD

**Issue by Arhimandril** [ncw/rclone#3104]
#### What is the problem you are having with rclone?

When using the `moveto` command to rename the file by changing it's case, the file gets deleted instead of renamed in some environments.

#### What is your rclone version (output from `rclone version`)

v1.46.0-112-g1c301f9f-beta

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

Windows 7, 64 bit

####  Which cloud storage system are you using? (eg Google Drive)

Windows Local, Jottacloud

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

rclone moveto R:\test.bin R:\TEST.bin

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

```
2019/04/08 19:02:14 DEBUG : rclone: Version "v1.46.0-112-g1c301f9f-beta" starting with parameters ["[...]\\rclone.exe" "moveto" "R:\\test.bin" "R:\\TEST.bin" "-vv"]
2019/04/08 19:02:14 DEBUG : Using config file from "[...]\\rclone.conf"
2019/04/08 19:02:14 DEBUG : test.bin: Size and modification time the same (differ by 0s, within tolerance 100ns)
2019/04/08 19:02:14 DEBUG : test.bin: Unchanged skipping
2019/04/08 19:02:14 INFO  : test.bin: Deleted
2019/04/08 19:02:14 INFO  :
Transferred:            0 / 0 Bytes, -, 0 Bytes/s, ETA -
Errors:                 0
Checks:                 2 / 2, 100%
Transferred:            0 / 0, -
Elapsed time:       200ms

2019/04/08 19:02:14 DEBUG : 2 go routines active
```

**Comment by ncw** [comment]
Thanks for reporting this - I've verified the problem.

This needs a bit of extra logic to detect if the source and destination files are the same in a case insensitive way (if the fs supports it) and not do the delete here.

https://github.com/ncw/rclone/blob/1c301f9f7ab8bf00d04331acc26b5195820ed1cf/fs/operations/operations.go#L400-L407

**Comment by gary-kim** [comment]
I'm assuming this will be just a matter of checking if the remote is case insensitive then check if the name is the same in a case insensitive way. I'll make a pull request.
