### ISSUE TITLE
Add CLI option to force transfer speeds to be displayed consistently

### ISSUE THREAD

**Issue by lotekjunky** [ncw/rclone#3106]
When using the -P option, transfer speeds are displayed in megabytes/sec.  Typically when moving data or measuring througput, bandwidth is displayed in megabits/sec. Storing data is usually displayed in megabytes. It gets really confusing when MOVING stored data, so I get why rclone is displaying in MB instead of mb. (Some would argue that it is doing this correctly, I can't argue against that but it would make my life easier if I had the option to change the label)

Adding a command line switch, such as --display-bandwidth=megabits or --display-bandwidth=kilobits would make the display easier to read, conform with typical measurement practices, and make the interface more consistent. (Speed is also reported for each active transfer, but it is displayed as KB. I'm less concerned about this and more interested in seeing the aggregate speed displayed as I requested).

It's my own dumb fault, but I just spent a week trying to figure out why my uploads to google drive were maxing out at 1.5 Mb/sec when I thought it was showing me 1.5 mb/sec. 1.5MB = 12mb, my max upload speed from my ISP.

**Comment by animosity22** [comment]
I didn't realize this, but it already exists:

 --stats-unit string                            Show data rate in stats as either 'bits' or 'bytes'/s (default "bytes")

The default is bytes rather than bits though.

**Comment by ncw** [comment]
I'll close this since `--stats-unit` should fit the requirement.  If it doesn't then let me know!

**Comment by lotekjunky** [comment]
Yes, this suffices. Sorry I didn't know about this switch until after I opened the request... I looked through the docs and apparently missed it too. The only thing left to say about stas-units is that it displays megabits with a capital M in the transferring section. It also has a capital M in the combined throughput section, but it suffices the M with the word "bits", so this is not a HUGE deal as well. Thanks for everything you do.

**Comment by ncw** [comment]
> Yes, this suffices. Sorry I didn't know about this switch until after I opened the request... I looked through the docs and apparently missed it too. 

No worries!

> The only thing left to say about stas-units is that it displays megabits with a capital M in the transferring section. It also has a capital M in the combined throughput section, but it suffixes the M with the word "bits", so this is not a HUGE deal as well. Thanks for everything you do.

I think the `M` should always be capitalized as it is an [SI prefix](https://en.wikipedia.org/wiki/Metric_prefix#List_of_SI_prefixes), small `m` would mean `milli`. I did do a physics degree so maybe that is just me ;-)

**Comment by lotekjunky** [comment]
Hi folks, I just thought I would drop a note here that states the ETA when using --stats-units bits is way off. I'm thinking maybe the math behind it is looking at the bits and thinking it is bytes as the time is roughly 1/8 the time I would expect it to be.

Take a look at the elapsed time, the percentage complete and the ETA. Of course this appears to be just aesthetics, but it does appear to be a bug, so I thought I would let you know. Thanks!

[quote]
UID@flamflam:/mnt/Arcade$ rclone -vP --bwlimit=1.2m --transfers=2 --checkers=10 --tpslimit=10 --drive-chunk-size=32M --stats-unit=bits --log-file=/home/UID/rclone-logs/arcade.log copy  "/mnt/raid1/Arcade" "crypt:arcade"
Transferred:       66.206G / 411.645 GBytes, 16%, 9.589 MBits/s, ETA 10h14m50s
Errors:                 0
Checks:                 0 / 0, -
Transferred:          130 / 728, 18%
Elapsed time:  15h42m42.5s
Transferring:
 *                                  Contrast.rar: 44% /1003.078M, 4.833M/s, 15m19s
 *                                    Jumper.rar: 46% /1.974G, 4.763M/s, 30m30s
[/quote]

**Comment by animosity22** [comment]
If you are seeing a separate item, I'd raise a new topic as this one is closed out.
