### ISSUE TITLE
Problem when using rclone as a context menu - upload task

### ISSUE THREAD

**Issue by gabriellluz** [ncw/rclone#3112]
#### What is your rclone version (output from `rclone version`)
rclone v1.46.0-121-ga28239f0-beta

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Windows 7, 64 bit

####  Which cloud storage system are you using? (eg Google Drive)
Any

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone copy ....

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
Not applicable.

What I'm trying to do is create a context menu entry like this on Windows: "send APK file to X folder".
Unfortunately, I can't and I get a message like this: "This is a command line tool. You need to open cmd.exe and run it from there" . I think it might be a problem with rclone because I can create context menues with other tools.

**Comment by ncw** [comment]
Ah...

I think you've got two possible solutions.  Wrap your rclone command in a `.bat` or `.ps` script.

Or recompile rclone with `go build -ldflags "-H windowsgui" ` then it will be a "windows gui" binary. I'm not 100% sure this will work but it might be worth a try!

**Comment by gabriellluz** [comment]
Thanks. That fixed the issue.
