### ISSUE TITLE
Missing fileextensions from some files in google drive

### ISSUE THREAD

**Issue by saikpr** [ncw/rclone#3113]
#### What is the problem you are having with rclone?
Turns out some of the files uploaded to Google Drive doesn't have file extensions in their name. For instance, a file named "HelloWorld" of type=pdf will have have name as "HelloWorld" and won't contain the file extension.
I discovered this while using `rclone mount` option, but is also reproducible using `rclone ls`

#### What is your rclone version (output from `rclone version`)
Tested on 
```
rclone v1.46
- os/arch: darwin/amd64
- go version: go1.11.5
```
and 
```
rclone v1.46
- os/arch: linux/amd64
- go version: go1.11.5
```

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

Mac, Debian 

####  Which cloud storage system are you using? (eg Google Drive)

Google Drive

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
`rclone ls drive:foldername`

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

```
rclone ls -vv personaldrive:documents/college_documents_transcript_degree/Class\ 12th\ Results
2019/04/13 01:10:19 DEBUG : rclone: Version "v1.46" starting with parameters ["rclone" "ls" "-vv" "personaldrive:documents/college_documents_transcript_degree/Class 12th Results"]
2019/04/13 01:10:19 DEBUG : Using config file from "/home/sainyam/.config/rclone/rclone.conf"
    69869 BITSAT SCORE 374
   147957 CBSE12 Results.pdf
    55991 MANIPAL BTECH Rank-609
2019/04/13 01:10:21 DEBUG : 4 go routines active
2019/04/13 01:10:21 DEBUG : rclone: Version "v1.46" finishing with parameters ["rclone" "ls" "-vv" "personaldrive:documents/college_documents_transcript_degree/Class 12th Results"]
```

#### Possible Remedy
I was looking through the code, it might be helpful to use code similar to https://github.com/ncw/rclone/blob/master/backend/drive/drive.go#L1308 to check if there is no file extension, then to use MIME Type or maybe check if the mime type and last few characters don't match then append the mime type to the file?

**Comment by ncw** [comment]
I'm not sure I understand the problem.

In general rclone doesn't put extensions on your file, that is up to you.

There are some exceptions to this when using the google drive import and export mechanisms - is that what you mean?

**Comment by saikpr** [comment]
I do understand that rclone "generally" doesn't add extensions except maybe when it tries to do dedupe(where it removes and then adds) or maybe when trying to export gdocs kind of time.

But my concern is a bit orthogonal to the this, from my understanding for some very old files which were uploaded to google docs (google drive didn't exist at that time) don't contain an extension like ".pdf" in their name. 
As part of their migration from google docs to drive, they added the files to drive but forgot to add the file extension to files.

Let's say the cut off date is X (after which they migrated to the new api)
for t<X if we would have uploaded a file name "hello.pdf" to google docs. Today this will appear as "hello" with mime type as pdf
for t>X any file uploaded contains the file extension in it's name.

I just realized that this happens on very old file, and in Google backup and sync, they take care of this case by adding an extension whenever the mime type is not binary.

**Comment by ncw** [comment]
So those files are missing extensions on google drive by the sound of it.

You could use rclone to help find those files and rename them.

So you could do something like this to generate a CSV of files without extensions and their mime types

    rclone lsf --exclude "*.*" -R --files-only --csv --format mp drive:

You could then feed this into a script to rename the files.

**Comment by saikpr** [comment]
Thanks a lot, this worked with some tweaks.
Let me know how should I close this issue.

Thanks
Sainyam
sainyam.me <https://sai.page.link/homepage>

**Comment by ncw** [comment]
Glad it worked.  I'll close this now.
