### ISSUE TITLE
gdrive server-side copy results in 404 errors

### ISSUE THREAD

**Issue by calisro** [ncw/rclone#3119]
Reference thread:

https://forum.rclone.org/t/gdrive-to-gdrive-error-404-file-not-found/9621/10

When syncing two different gdrive remotes, i'm seeing 404 errors coming in the api and failures.  When I disable the server-side copy the sync works correctly using "--disable copy".

`rclone sync robgs:cloudp/12el63s90885tg9u16iea5vtps/ao2c93qnjv533s8eoufko2p264/o59hc3g2a6qalng7k8mpmql28c pinagd:cloudp/12el63s90885tg9u16iea5vtps/ao2c93qnjv533s8eoufko2p264/o59hc3g2a6qalng7k8mpmql28c -vv --log-file=test.log --dump-bodies `

I've run this with dump bodies just to see where the errors are coming from and here is the 404 and the info leading up to it.

```
2019/04/18 08:43:02 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2019/04/18 08:43:02 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2019/04/18 08:43:02 DEBUG : HTTP REQUEST (req 0xc000120d00)
2019/04/18 08:43:02 DEBUG : POST /drive/v3/files/1myq3teYU4hfZUtwLq_u9gYwaWm_M5FNO/copy?alt=json&fields=id%2Cname%2Csize%2Cmd5Checksum%2Ctrashed%2CmodifiedTime%2CcreatedTime%2CmimeType%2Cparents%2CwebViewLink&keepRevisionForever=false&prettyPrint=false&supportsTeamDrives=false HTTP/1.1^M
Host: www.googleapis.com^M
User-Agent: rclone/v1.47.0-015-gaba15f11-beta^M
Content-Length: 215^M
Authorization: XXXX
Content-Type: application/json^M
Accept-Encoding: gzip^M
^M
{"description":"3i1g4iietqhggevatdgvq83v54","mimeType":"application/octet-stream","modifiedTime":"2019-03-27T20:03:42.648000000Z","name":"3i1g4iietqhggevatdgvq83v54","parents":["1dsH1bNv4_zrilBLIkFco49J0maPpxjl6"]}
2019/04/18 08:43:02 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2019/04/18 08:43:02 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2019/04/18 08:43:02 DEBUG : HTTP RESPONSE (req 0xc000120d00)
2019/04/18 08:43:02 DEBUG : HTTP/1.1 404 Not Found^M
Transfer-Encoding: chunked^M
Alt-Svc: quic=":443"; ma=2592000; v="46,44,43,39"^M
Cache-Control: private, max-age=0^M
Content-Type: application/json; charset=UTF-8^M
Date: Thu, 18 Apr 2019 12:43:02 GMT^M
Expires: Thu, 18 Apr 2019 12:43:02 GMT^M
Server: GSE^M
Vary: Origin^M
Vary: X-Origin^M
X-Content-Type-Options: nosniff^M
X-Frame-Options: SAMEORIGIN^M
X-Xss-Protection: 1; mode=block^M
^M
f6^M
{"error":{"errors":[{"domain":"global","reason":"notFound","message":"File not found: 1myq3teYU4hfZUtwLq_u9gYwaWm_M5FNO.","locationType":"parameter","location":"fileId"}],"code":404,"message":"File not found: 1myq3teYU4hfZUtwLq_u9gYwaWm_M5FNO."}}^M
0^M

root@cloudc:/data/bin# rclone lsjson robgs:cloudp/12el63s90885tg9u16iea5vtps/ao2c93qnjv533s8eoufko2p264/o59hc3g2a6qalng7k8mpmql28c
[
{"Path":"011nn2buif0v9dj091nd6u7sss","Name":"011nn2buif0v9dj091nd6u7sss","Size":5312,"MimeType":"application/octet-stream","ModTime":"2019-03-28T03:01:15.954Z","IsDir":false,"ID":"1qG1ucee_RkGWauRXzvsVRyjZ5s7ZouBg"},
{"Path":"3dfk7t6ff837dkm84kjviga1r8","Name":"3dfk7t6ff837dkm84kjviga1r8","Size":89623,"MimeType":"application/octet-stream","ModTime":"2019-03-27T17:11:10.804Z","IsDir":false,"ID":"1ZwK9Sem5PClKExyRmkA6_nM3ovn75SjV"},
{"Path":"3i1g4iietqhggevatdgvq83v54","Name":"3i1g4iietqhggevatdgvq83v54","Size":3309246,"MimeType":"application/octet-stream","ModTime":"2019-03-27T20:03:42.648Z","IsDir":false,"ID":"1myq3teYU4hfZUtwLq_u9gYwaWm_M5FNO"},
{"Path":"c562if70fm08du49pla2f9b2k8","Name":"c562if70fm08du49pla2f9b2k8","Size":95231,"MimeType":"application/octet-stream","ModTime":"2019-03-28T00:18:18.856Z","IsDir":false,"ID":"1RARk89nar7MwnY81sSV5oFnieobbGAwo"},
{"Path":"g8kg77r6lmb6tidovn7dg1a1g8","Name":"g8kg77r6lmb6tidovn7dg1a1g8","Size":6955,"MimeType":"application/octet-stream","ModTime":"2019-03-28T00:15:30.900Z","IsDir":false,"ID":"1sPfgXitLV2Ti9hRvFXoLrZALOFVSEA_K"},
{"Path":"gnr65g6hljq95f8f4uoldem888","Name":"gnr65g6hljq95f8f4uoldem888","Size":1072958,"MimeType":"application/octet-stream","ModTime":"2019-03-28T00:15:16.476Z","IsDir":false,"ID":"1lfYFSykIkv1J9afiufuVWSVLiAPAliQy"},
{"Path":"kbbmlqgruieun7ar0rm3a10tt0","Name":"kbbmlqgruieun7ar0rm3a10tt0","Size":2040,"MimeType":"application/octet-stream","ModTime":"2019-03-28T00:40:13.880Z","IsDir":false,"ID":"1mVr1b1wfNMpDbLPKYzwOEYXJgc8WEqym"},
{"Path":"obilalmb2cf58b6js0velfddqc","Name":"obilalmb2cf58b6js0velfddqc","Size":6121,"MimeType":"application/octet-stream","ModTime":"2019-03-28T02:16:16.786Z","IsDir":false,"ID":"1E71s4A3A2yRX7-ppnJEdDwIPbnty6HEa"},
{"Path":"ub0n2us8icde3qt4s9ihr96214","Name":"ub0n2us8icde3qt4s9ihr96214","Size":29644,"MimeType":"application/octet-stream","ModTime":"2019-03-28T03:01:18.722Z","IsDir":false,"ID":"1VZ74DLGpYEOn6Z2-NdOkV1toRg5V2EaN"},
{"Path":"uv710v07a8934pjtcjqtd6i3vg","Name":"uv710v07a8934pjtcjqtd6i3vg","Size":16834,"MimeType":"application/octet-stream","ModTime":"2019-03-28T00:40:16.532Z","IsDir":false,"ID":"1Y8goJZexNCqacqp_s0xoqzHwHpqPPsug"}


```

**Comment by ncw** [comment]
This appears to be a consequence of #2728 and 55b9a4ed309f6f442cde0a70d50dddc476e91243

The original issue was about team drives, however this seems to be about normal (non-team) drives.

@fionera any thoughts? Does this only work for team drives?

**Comment by fionera** [comment]
Yes that totally normal, since the copy request is issued on the destination remote, it also uses the user of it. So when you are copying to a drive where the destination user doesn't have access to the source it returns a 404. Also when using normal to teamdrive or reverse it needs the patch from #3097 . I already thought about making an additional check that when using serverside over different remotes that it automatically disables serverside when it gets that error.

**Comment by calisro** [comment]
So in order to benefit from the server side copies on a non-team drive, what does the user have to actually do?  Share the folder with the destination?  If that is the case, this really isn't any different than simply clicking the 'add to my drive'  after the sharing and syncing using the existing remote:

rclone sync remote1:sharedfolder remote1:destfolder

Am I correct?  If so, this really needs to be a OPT IN, rather than a OPT OUT feature.  Most people won't have shared a folder with a different account when syncing between remotes.

**Comment by fionera** [comment]
For normal drive the destination need to be shared with, yes, either as everyone or direct share. But 'add to my drive' doesn't create a copy, but instead links it.

**Comment by calisro** [comment]
Yes I know it doesn't actually copy it. But when you link to it, you can essentially do what this is doing by copying from the same remote for source to destination.

Since most people will not have "shared" the directory be default, do we think this should be "opt in" rather?

**Comment by fionera** [comment]
This patch should fix it... I sadly cannot test it currently.

```
Index: backend/drive/drive.go
<+>UTF-8
===================================================================
--- backend/drive/drive.go	(revision aba15f11d85dbb0b137f4b9f8d009d4c6fd7e47a)
+++ backend/drive/drive.go	(date 1555618170655)
@@ -1887,6 +1887,14 @@
 		return shouldRetry(err)
 	})
 	if err != nil {
+		if gerr, ok := err.(*googleapi.Error); ok {
+			// When using ServerSide copy, return ErrorCantCopy if it got a 404
+			if gerr.Code == 404 {
+				fs.Debugf(src, "Can't copy - cannot find file. Trying normal copy")
+				return nil, fs.ErrorCantCopy
+			}
+		}
+
 		return nil, err
 	}
 	newObject, err := f.newObjectWithInfo(remote, info)
@@ -2037,6 +2045,14 @@
 		return shouldRetry(err)
 	})
 	if err != nil {
+		if gerr, ok := err.(*googleapi.Error); ok {
+			// When using ServerSide move, return ErrorCantMove if it got a 404
+			if gerr.Code == 404 {
+				fs.Debugf(src, "Can't move - cannot find file. Trying normal move")
+				return nil, fs.ErrorCantMove
+			}
+		}
+
 		return nil, err
 	}
 ```

**Comment by calisro** [comment]
If i'm reading this correctly, won't that mean that **for each and every file** that is part of a copy/move operation that it'll fail first with a 404 and then switch to a regular copy?  My concern is that the majority of users do not 'share' the folder between remotes which seems to be required to enable this to work so the majority of users will face many 404s and more API hits and slower operations because of the failure test.

Is my concern not correct?

**Comment by fionera** [comment]
yes it first tries to use serverside copy and then switch. The normal user mostly doesn't copy between multiple users, so this case wont happen that often

**Comment by calisro** [comment]
I tend to disagree. In the case of non-teamdrive users most users who copy between remotes and between gdrive remotes and by that very nature they are using two different users.

**Comment by fionera** [comment]
I could disable serverside for the whole session if it doesn't have access to the other remote.

**Comment by calisro** [comment]
That sounds like a good option to me. If it's possible to determine the access doesn't exist and to disable for the session, I think that would be good rather than for each file.

**Comment by fionera** [comment]
This disables serverside when occurring this problem.

```
Index: backend/drive/drive.go
<+>UTF-8
===================================================================
--- backend/drive/drive.go	(revision aba15f11d85dbb0b137f4b9f8d009d4c6fd7e47a)
+++ backend/drive/drive.go	(date 1555690330766)
@@ -1887,6 +1887,15 @@
 		return shouldRetry(err)
 	})
 	if err != nil {
+		if gerr, ok := err.(*googleapi.Error); ok {
+			// When using ServerSide copy, return ErrorCantCopy if it got a 404
+			if gerr.Code == 404 {
+				fs.Debugf(src, "Can't copy - cannot find file. Disabling server side")
+				f.features.Move = nil
+				return nil, fs.ErrorCantCopy
+			}
+		}
+
 		return nil, err
 	}
 	newObject, err := f.newObjectWithInfo(remote, info)
@@ -2037,6 +2046,15 @@
 		return shouldRetry(err)
 	})
 	if err != nil {
+		if gerr, ok := err.(*googleapi.Error); ok {
+			// When using ServerSide move, return ErrorCantMove if it got a 404
+			if gerr.Code == 404 {
+				fs.Debugf(src, "Can't move - cannot find file. Disabling server side")
+				f.features.Copy = nil
+				return nil, fs.ErrorCantMove
+			}
+		}
+
 		return nil, err
 	}
```

**Comment by desimaniac** [comment]
@fionera could we get this PRed now that the other one got merged ?

**Comment by fionera** [comment]
Yes but it has to be tested. I currently cannot test it...

**Comment by lotekjunky** [comment]
If the user has full drive access to both remotes, could rclone not issue API commands to properly set the permissions on the source?

**Comment by fionera** [comment]
technically yes but this can be introduce a lot of complexity and errors

**Comment by calisro** [comment]
I tested this under my scenario and it still seems to attempt a server-side copy for each file resulting in 404s before each and every copy.

**Comment by lotekjunky** [comment]
> 
> 
> technically yes but this can be introduce a lot of complexity and errors

fair enough, I can completely understand that. Thanks for answering.

**Comment by calisro** [comment]
@fionera Is there another patch I can test?  or can we convert this to 'opt-in' rather than 'opt-out'?    

My personal feeling is this really should be 'opt-in' as server side copies have far more stringent quotas than regular copies.  But that is better answered by @ncw  I think as whether it should be a opt-in or opt-out.

**Comment by ncw** [comment]
> My personal feeling is this really should be 'opt-in' as server side copies have far more stringent quotas than regular copies. But that is better answered by @ncw I think as whether it should be a opt-in or opt-out.

I'm tempted to revert back to the old behavior of only allowing server side copies in the same remote, **unless** the user provides a flag.

What does everyone else think?

**Comment by calisro** [comment]
Are we still thinking of reverting this change and making it a flag?

**Comment by ncw** [comment]
> Are we still thinking of reverting this change and making it a flag?

I've done that here.  The flag to enable it again is called `--drive-server-side-across-configs`

Can you give it a test?

https://beta.rclone.org/branch/v1.47.0-099-ge55b2fa0-fix-3119-drive-copy-beta/ (uploaded in 15-30 mins)

**Comment by calisro** [comment]
Sure. I can.  Nothing there.  I assume it failed to build?

**Comment by 88lex** [comment]
@ncw Before merging this into base can you (or someone on your team) double check regarding server-side copy limits?  ```server side copies have far more stringent quotas than regular copies```

I've been doing server-side syncs/copies for quite a while now and am seeing exactly the same limit  (to/from/between My Drive and Team Drives) as we get with non-server-side copies. That is, the 750GB/day limit applies to both.

If that is the case then this change would be forcing rclone to use the slower and more resource expensive download/upload method by default rather than the fast/easy server-side copies.

If I am wrong, no problem. I'll just use the new flag on the several accounts where I get 750GB/day server-side. ;=)

**Comment by ncw** [comment]
https://beta.rclone.org/branch/v1.47.0-102-gaa819575-fix-3119-drive-copy-beta/ (uploaded in 15-30 mins)
@calisro 
> Sure. I can. Nothing there. I assume it failed to build?

I forgot to push it :blush:

https://beta.rclone.org/branch/v1.47.0-102-gaa819575-fix-3119-drive-copy-beta/ (uploaded in 15-30 mins)

@88lex wrote:




> If that is the case then this change would be forcing rclone to use the slower and more resource expensive download/upload method by default rather than the fast/easy server-side copies.

Yes it will.  It might be that once we've figured out how to do it reliably we can re-enable the feature by default.  The problem is that there are too many cases where it breaks at the moment right now.

> If I am wrong, no problem. I'll just use the new flag on the several accounts where I get 750GB/day server-side. ;=)

The new flag is there for exactly that purpose :-)

**Comment by calisro** [comment]
"the 750GB/day limit applies to both."

I've heard reports of this. That helps. 

The biggest issue with enabling this by default is that by default it'll fail with a 404 unless permissions are granted between accounts. A user needs to actually do something to enable it to work so it only makes sense that in the cli that it should be enabled with a flag.  If there cli could grant permissions needed itself then enabling this by default would make sense to me at least.

**Comment by 88lex** [comment]
> "the 750GB/day limit applies to both."
> 
> I've heard reports of this. That helps.
> 
> The biggest issue with enabling this by default is that by default it'll fail with a 404 unless permissions are granted between accounts. A user needs to actually do something to enable it to work so it only makes sense that in the cli that it should be enabled with a flag. If there cli could grant permissions needed itself then enabling this by default would make sense to me at least.

If I understand correctly, you are saying it fails by default if cross account permissions have not been granted, rather failing-over to --disable move,copy type DL/UL behavior if server-side is unavailable?  

If that's the case, understood. Makes perfect sense to force DL/UL by default rather than a full fail.

**Comment by calisro** [comment]
This appears to work as far as reverting the change.  I cannot test at the moment the actual flag works correctly to 'enable' the SS transfers though.

**Comment by 88lex** [comment]
@ncw Would it be possible to to include a brief alternative flag in addition to 
`--drive-server-side-across-configs`  ?

Thank you ;-)

**Comment by calisro** [comment]
Any suggestions for alternative? 🤔

**Comment by 88lex** [comment]
> Any suggestions for alternative? 🤔

The main flag is long but clarity is great, so it is fine. Perhaps `--drive-server-side-across-accounts` might be a tad more clear?

When I said alternative I meant a single letter variant. As -v is used for --verbose, perhaps use `-a` or `-A` if one of those is not already in use.

```-a, --drive-server-side-across-accounts     Force server side when transferring across multiple accounts.```

**Comment by ncw** [comment]
> > Any suggestions for alternative? thinking
> 
> The main flag is long but clarity is great, so it is fine. Perhaps `--drive-server-side-across-accounts` might be a tad more clear, but no bother either way.

I've merged the original flag name now.

> When I said alternative I meant a single letter variant. As -v is used for --verbose, perhaps use `-a` or `-A` if one of those is not already in use.
> 
> `-a, --drive-server-side-across-accounts Force server side when transferring across multiple accounts.`

I don't want to add any more global short flags as they contstrain what can be done in the sub commands.

Note that you can put `server_side_across_accounts = true` in your drive configs so you never have to type it again!

**Comment by 88lex** [comment]
> > > Any suggestions for alternative? thinking
> > 
> > 
> > The main flag is long but clarity is great, so it is fine. Perhaps `--drive-server-side-across-accounts` might be a tad more clear, but no bother either way.
> 
> I've merged the original flag name now.
> 
> > When I said alternative I meant a single letter variant. As -v is used for --verbose, perhaps use `-a` or `-A` if one of those is not already in use.
> > `-a, --drive-server-side-across-accounts Force server side when transferring across multiple accounts.`
> 
> I don't want to add any more global short flags as they contstrain what can be done in the sub commands.
> 
> Note that you can put `server_side_across_accounts = true` in your drive configs so you never have to type it again!

Thank you @ncw .  The suggestion about adding it to the config saves a lot of (lazy person) typing.

In your reply to me did you mean `server_side_across_accounts` or `server_side_across_configs`?  I think the latter.

**Comment by ncw** [comment]
> In your reply to me did you mean `server_side_across_accounts` or `server_side_across_configs`? I think the latter.

Errm,yess

#### --drive-server-side-across-configs

Allow server side operations (eg copy) to work across different drive configs.

This can be useful if you wish to do a server side copy between two
different Google drives.  Note that this isn't enabled by default
because it isn't easy to tell if it will work beween any two
configurations.

- Config:      server_side_across_configs
- Env Var:     RCLONE_DRIVE_SERVER_SIDE_ACROSS_CONFIGS
- Type:        bool
- Default:     false

**Comment by silversegarra** [comment]
Hello, first great job...
I tried "sync" side by side, with a Google Drive ---» TeamDrive, or Google Drive ---» Google and it doesn't works for me... I receive the same error :(

**Comment by ncw** [comment]
> Hello, first great job...
> I tried "sync" side by side, with a Google Drive ---» TeamDrive, or Google Drive ---» Google and it doesn't works for me... I receive the same error :(

If you get an error, then you need to drop the `--drive-server-side-across-configs` flag.

**Comment by silversegarra** [comment]
Thanks for answering, that it whats happens now
[image: image.png]

ssegarra@gmail.com



Silver Segarra

**Comment by silversegarra** [comment]
> > Hello, first great job...
> > I tried "sync" side by side, with a Google Drive ---» TeamDrive, or Google Drive ---» Google and it doesn't works for me... I receive the same error :(
> 
> If you get an error, then you need to drop the `--drive-server-side-across-configs` flag.

Hello, what I found, after trying everything, is the "Server side copy", doesn't work well, on Synology for some reason... I tried with the same command, in my laptop, with linux, and it works perfect...

**Comment by ncw** [comment]
> Hello, what I found, after trying everything, isthat the "Server side copy", doesn't work well on Synology for some reason... I tried with the same command, in my laptop, with linux, and it works perfect...

Can you make a new issue about this with more details please? (fill in the form).

Thanks!

**Comment by ncw** [comment]
@fionera - just had a thought about this...

It might be as simple as checking the `canCopy` field in the [files resources](https://developers.google.com/drive/api/v3/reference/files#resource) to fix properly?  This could be done without trying the file and getting the 404 so would be quick.

The Copy routine could just return fs.ErrorCantCopy to engage the fallback path.

What do you think would this work?

If so then we can default --drive-server-side-across-configs to true.

Does anyone have some examples to test with (perhaps using -vv --dump bodies, or the [API explorer](https://developers.google.com/drive/api/v3/reference/files/copy)

**Comment by fionera** [comment]
The canCopy field is for permission stuff, because you can disable downloading for specific roles. It would also give a 404 since the user cannot access the file.

**Comment by ncw** [comment]
> The canCopy field is for permission stuff, because you can disable downloading for specific roles. It would also give a 404 since the user cannot access the file.

Ah, so you are saying `canCopy` could be `true` but it would still give a 404?

Any other ideas?  Is there some way we could check permissions from the info in a file resource?

I'd like to get this working properly, but I don't want to do an extra transaction per copy if possible.

**Comment by fionera** [comment]
> Ah, so you are saying `canCopy` could be `true` but it would still give a 404?

No I think It the request for this info would be a 404

**Comment by ncw** [comment]
> > Ah, so you are saying `canCopy` could be `true` but it would still give a 404?
> 
> No I think the request for this info would be a 404

I see what you mean... The user of the destination drive doesn't have permission to read the file info and getting the source user to read it will likely return `canCopy = true` which isn't useful.

**Comment by fionera** [comment]
How about disabling serverside completely when there is a 404 and allow overriding that check with a param

**Comment by ncw** [comment]
> How about disabling serverside completely when there is a 404 and allow overriding that check with a param

That would need to be done on a per-remote basis I think so keep a map of remotes which you can't copy from.

I really don't like the 404 error though - it is very crude! Can we find a more precise method?  Maybe listing the source remote with the destination credentials?

**Comment by Nottt** [comment]
I had the same issue. It's strange because it seemed to affect 50% of the files only.

I'm a member of a team drive with read-only access and I'm uploading to another teamdrive I created myself. What I don't understand is why this only happened to half the files, it should either work for everything or none. 

I thought permissions in a teamdrive worked in a standard way, so there's no way there's a file there I can copy or others I can't if I have read access?

**Comment by ncw** [comment]
> @ncw Hi Nick, I am sorry to bring out this old issues, but was this problem solved?
> 
> i was ok two weeks ago doing server side copy, but today i am getting many 404 erros doing server side copy.
> 
> tried the stable release and the latest beta.

404 errors are permissions errors as far as I know so check the permissions.
