### ISSUE TITLE
Caching for read only files

### ISSUE THREAD

**Issue by cafarm** [ncw/rclone#3124]
#### What is your current rclone version (output from `rclone version`)?
```bash
$ rclone version
rclone v1.47.0
- os/arch: darwin/amd64
- go version: go1.12.4
```

#### What problem are you are trying to solve?
rclone does not currently cache read-only files which means it always retrieve chunks from the backend even if it has retrieved them previously. It seems like performance could be significantly improved for read-only files if they were able to be cached locally.

#### How do you think rclone should be changed to solve that?
rclone should cache read-only files like it currently caches read-write files.

**Comment by mcafaro** [comment]
Sorry, I just discovered the cache backend that addresses this request. Please close.

**Comment by animosity22** [comment]
@mcafaro - you can just hit the close button at the bottom as you have the ability to close it yourself.
