### ISSUE TITLE
[Cosmetic) Alias for a[n] existing remote

### ISSUE THREAD

**Issue by vc7ee** [ncw/rclone#3125]
When configuring a remote, alias: description has a typo
`2 / Alias for a existing remote
   \ "alias"
`
There should be an `an` instead of an `a` before  existing.
This typo is everywhere (GitHub search found 8 pages worth of the same typo).

**Comment by animosity22** [comment]
I made a pull request to fix that.

https://github.com/ncw/rclone/pull/3133

**Comment by ncw** [comment]
That is merged now - thank you @animosity22 .  The website will be updated at the next release.
