### ISSUE TITLE
gDrive rclone ls with display quotaBytesTotal instead of fileSize

### ISSUE THREAD

**Issue by MurzNN** [ncw/rclone#3135]
At now `rclone ls` command on Google Drive displays only real file size (`fileSize` argument from Google API).

Is this possible to switch `rclone` display number value from `fileSize` to `quotaBytesTotal` (or add `quotaBytesTotal` as second number in output), for understanding file quota usage in my gDrive?

If not possible, can you accept this as feature request, so implement something like `rclone ls --size=quota`?

Same feature also will be very useful for other storage providers too.

**Comment by MurzNN** [comment]
There are exists also `rclone size` command, that displays total size of files in folder, but it miss argument to calculate quotaBytesTotal API value from file instead of fileSize, so add same argument to `size` function will be great too.

**Comment by ncw** [comment]
I see what you mean looking at [the drive v3 docs](https://developers.google.com/drive/api/v3/reference/files#resource).

We could make a flag which caused rclone to read the size of things as `quotaBytesTotal` easily enough - say `--drive-size-as-quota`.  However this would break syncing very badly if it was set for a sync!  This would make `rclone ls` and `rclone size` both calculate the quotas.

Would you like to work on that?

Note that you can use `rclone about remote:` to see information about the total quota.

**Comment by MurzNN** [comment]
Thanks for quick reply! Making flag like `--drive-size-as-quota` will be good solution, for don't break syncing can we enable it only for `ls` and `size` modes, and ignore in other modes? I want to work on this, but I'm not so good programmer in Go, I know only PHP and JS :( So I can help only with testing...

**Comment by garrmcnu** [comment]
Added `--drive-size-as-quota` flag as suggested to show `quotaBytesUsed` for file size (looks like `quotaBytesTotal` is the v2 API).

**Comment by ncw** [comment]
I've merged this to master now which means it will be in [the latest beta](https://beta.rclone.org) in 15-30 mins and released in v1.48
