### ISSUE TITLE
Empty Trash (in particular in Mega)

### ISSUE THREAD

**Issue by caspertone2003** [ncw/rclone#3138]
While using cloud storage, one of the challenges is always being under storage limit. Good practice is to delete not needed material.

Each of the remotes have a different approach, but, usually, deleted items are temporarily stored in a "to be finally deleted" area -TBFDA, that is usually purged after x days of staying there.

The space used by that TBFDA is counted towards storage limits. So, if one is short, the best is to force an inmediate purge TBFDA. "native" web interfaces allow to do it; unsure if APIs provide the function.

I did not find a mean to force purge of TBFDA in rclone for Mega.

In Mega, there are several "system" folders, one is /Root and other is /Trash
The only way to do this that I found in CMD was to use megatools, that allows to list /Trash and to delete item by item in /Trash.

I have not found any way to use (list, delete items) mega /Trash with rclone (but documentation is so vast that I might be wrong....). rlcone ls megaremote:File is always refering to /Root/File.  But in W10 CMD has also some issues. When there are too many items to delete including non-ANSI names.... web interface is the only resort I found.

I believe rclone can profit from stablishing a framework to purge TBFDA, so that internally could use the best way for each remote, and avoid the pitfalls with non-ANSI names; besides, it could be done with just a single login/logout session.

(I have been pested lately for what it seems throttling by mega in terms of how often one logins/logouts, as some rclone operations produce sucesive login/logout - this is still under investigation).

For mega, the algorithm is not complex:
a) login
b) list recursively contents of /Trash
c) delete each item under /Trash and any folder under /Trash
d) list remaining empty space (optional)
e) logout

TIA,
CT

**Comment by gary-kim** [comment]
We have `rclone cleanup` for emptying trash on the remote but it is not implemented for Mega. I can give it a try it will take a few days. I'm a bit busy at the moment.

**Comment by caspertone2003** [comment]
@gary-kim 
Sorry for missing mega cleanup!
Thanks for such fast implementation. I have already spent 10 hours trying to polish my cmd ;-(((

I am not fully knowledgeable of how this PR/releases/etc. works. When should I expect an executable having this feature? Would it be available in https://beta.rclone.org/ ?

Thanks again!

**Comment by gary-kim** [comment]
It should be available on the <https://beta.rclone.org> site once the pull request gets merged.

**Comment by ncw** [comment]
I've merged this to master now which means it will be in [the latest beta](https://beta.rclone.org) in 15-30 mins and released in v1.48 - thank you very much @gary-kim

**Comment by caspertone2003** [comment]
@gary-kim @ncw 
Thanks both for making this happen.

I tried the lastest beta, I must confess I am a little perplex. Even running with -vvv I got no message either from ok or not ok. So, it is a bit uncomfortable. Perhaps output could be free space before and after... So, I cannot confirm by know that works as expected....

I would like to know about the syntax, 
https://rclone.org/commands/rclone_cleanup/ indicates that one should use remote:foder
So, for mega should I use remote:Trash ? (not written in documentation nor in mega page)
What for is needed the Folder? Perhaps it would be clearer just to provide the remote...

Last two points,

- https://rclone.org/overview/ has not carried the modification to include mega in the list of cleanup remotes.

- https://rclone.org/commands/rclone_cleanup/ : add the following info from /overview/

If the server can’t do CleanUp then rclone cleanup will return an error.

**Comment by gary-kim** [comment]
> I would like to know about the syntax,
> So, for mega should I use remote:Trash ? (not written in documentation nor in mega page)

You would use cleanup with syntax such as `rclone cleanup remote:`. Whatever path you put in will be ignored.

> 
> Last two points,
> 
> * https://rclone.org/overview/ has not carried the modification to include mega in the list of cleanup remotes.

The website gets updated at every release. The change is already reflected here: <https://tip.rclone.org/overview/>. It will be on <https://rclone.org/overview/> when v1.48 is released.

**Comment by caspertone2003** [comment]
Thanks!

**Comment by caspertone2003** [comment]
@gary-kim @ncw 
I can confirm it works perfectly!
I am still uneasy at not having an explicit ok/nok response, but I imagine errorlevel is working and can be checked.
Thanks again,
CT

**Comment by ncw** [comment]
> @gary-kim @ncw
> I can confirm it works perfectly!
> I am still uneasy at not having an explicit ok/nok response, but I imagine errorlevel is working and can be checked.
> Thanks again,
> CT

I've stuck some logs in for -v (shows total to delete) and -vv (shows each thing to be deleted).

I've merged this to master now which means it will be in [the latest beta](https://beta.rclone.org) in 15-30 mins

**Comment by caspertone2003** [comment]
@ncw 

Tested -v and -vvv

Nice for mega ;-)
No deletion related output for drive ;-(

CT

**Comment by ncw** [comment]
> No deletion related output for drive ;-(

All rclone does in this case is call the empty trash API once so not a lot to report on :-(
