### ISSUE TITLE
Plix help mount drive remote rclone centos 6.10

### ISSUE THREAD

**Issue by leopkks** [ncw/rclone#3144]
rclone mount --log-file "C:\rclone\logs\rclone.log" --log-level INFO --allow-non-empty --allow-other --default-permissions --fuse-flag sync_read --tpslimit 10 --tpslimit-burst 10 --dir-cache-time=160h --buffer-size=64M --attr-timeout=1s --vfs-read-chunk-size=2M --vfs-read-chunk-size-limit=2G --vfs-cache-max-age=5m --vfs-cache-mode=writes --cache-dir "D:\DriveFSCache\X" Filmes: X: --config "C:\Users\Windows-10\.config\rclone\rclone.conf"

need linux commands to mount a remote hd within centos 6.10
I tried to use a programming here but it is giving error
failed to mount FUSE fs: fusermount

I need a code that works to create a remote drive
in the cents 6.10
so I can access the contents
without having to download
examples mp3 mp4 avi pdf
as well as update them by the remote drive

**Comment by Cnly** [comment]
Hi @leopkks,

regarding the error `failed to mount FUSE fs`, you may want to take a look at this forum thread: https://forum.rclone.org/t/cant-mount-with-rclone-fusemount-missing/488. And if you're seeing other similar problems or need further help setting up rclone, posting on the [forum](https://forum.rclone.org) is actually a better choice :)

**Comment by leopkks** [comment]
> 
> 
> Hi @leopkks,
> 
> regarding the error `failed to mount FUSE fs`, you may want to take a look at this forum thread: https://forum.rclone.org/t/cant-mount-with-rclone-fusemount-missing/488. And if you're seeing other similar problems or need further help setting up rclone, posting on the [forum](https://forum.rclone.org) is actually a better choice :)

I did the installation in centos 6.10

yum install fuse
but still giving error
when I try to mount a unit
of errors
directory does not exist
I want to mount a drive like I did on windows
remote
as an external networked HD.

I need a command to solve

if you get ubuntu

or centos 7

would be using an external unit to mount the

https://github.com/astrada/google-drive-ocamlfuse

need to mount a networked HD where
you can access the folders as if you are local

if possible send me commands to solve the problem.

**Comment by leopkks** [comment]
rclone mount gdrive: /mnt/gdrive --config=/root/.config/rclone/rclone.conf --allow-non-empty --allow-other --buffer-size 256M --dir-cache-time 72h --drive-chunk-size 32M --log-level INFO --log-file /root/rclone/rclone.log --vfs-read-chunk-size 128M --vfs-read-chunk-size-limit off
erro
2019/04/28 15:13:02 Fatal error: failed to mount FUSE fs: mountpoint does not exist: /mnt/gdrive

rclone mount --log-file "/root/rclone/rclone.log" --log-level INFO --allow-non-empty --allow-other --default-permissions --fuse-flag sync_read --tpslimit 10 --tpslimit-burst 10 --dir-cache-time=160h --buffer-size=64M --attr-timeout=1s --vfs-read-chunk-size=2M --vfs-read-chunk-size-limit=2G --vfs-cache-max-age=5m --vfs-cache-mode=writes --cache-dir "/root/gcache" gdrive: /mnt/gdrive --config "/root/.config/rclone/rclone.conf"

2019/04/28 15:15:36 INFO  : Starting HTTP transaction limiter: max 10 transactions/s with burst 10
2019/04/28 15:15:36 Fatal error: failed to mount FUSE fs: mountpoint does not exist: /mnt/gdrive

**Comment by leopkks** [comment]
Traduzir do: Inglês
336/5000
I got the wheel controls

2019/04/28 16:25:48 INFO: Starting HTTP transaction limiter: max 10 transactions / s with burst 10
2019/04/28 16:25:48 mount helper error: fusermount: failed to mount mountpoint / gdrive: Transport endpoint is not connected
2019/04/28 16:25:48 Fatal error: failed to mount FUSE fs: fusermount: exit status 1


rclone mount --log-file "/root/rclone/rclone.log" --log-level INFO --allow-non-empty --allow-other --default-permissions --fuse-flag sync_read --tpslimit 10 --tpslimit-burst 10 --dir-cache-time=160h --buffer-size=64M --attr-timeout=1s --vfs-read-chunk-size=2M --vfs-read-chunk-size-limit=2G --vfs-cache-max-age=5m --vfs-cache-mode=writes --cache-dir "/root/gcache" gdrive: /gdrive --config "/root/.config/rclone/rclone.conf"


centos 6.10

**Comment by leopkks** [comment]
I found a solution using these commands
it is necessary
create a folder

if you have a better command
attach



rclone mount --log-file "/tmp/rclone.log" --log-level INFO --allow-non-empty --allow-other --default-permissions --fuse-flag sync_read --tpslimit 8 --tpslimit-burst 5 --dir-cache-time=1m --cache-chunk-size=32M  --cache-info-age=168h --cache-workers=5 --buffer-size=256M --attr-timeout=1s --vfs-read-chunk-size=2M --vfs-read-chunk-size-limit=4G --vfs-cache-max-age=5m --vfs-cache-mode=writes --cache-dir "/root/gcache" gdrive: /path/to/media --config "/root/.config/rclone/rclone.conf"
