### ISSUE TITLE
FTPS support

### ISSUE THREAD

**Issue by aliron19** [ncw/rclone#3146]
#### What is your current rclone version (output from `rclone version`)?
rclone v1.47.0
- os/arch: windows/amd64
- go version: go1.11

#### What problem are you are trying to solve?
Adding support for FTP over SSL/TLS (aka FTPS). 

#### How do you think rclone should be changed to solve that?
According to some rclone forum topics (for example: [this one](https://forum.rclone.org/t/ssl-connect-over-ftp-mount-from-rclone/4249/2), or [this one](https://forum.rclone.org/t/rclone-ftp-support/2320/26)), there have been some previous interest about adding FTPS support to rclone. However, as the [underlying ftp library](https://github.com/jlaffaye/ftp) that rclone is using didn't support FTPS, it was extremely difficult to achieve.

The good news are that recently, that go library [has been updated to support implicit FTPS](https://github.com/jlaffaye/ftp/pull/121), so I wonder if it would be feasible to implement FTPS into rclone now.

Thank you.

**Comment by ncw** [comment]
Thanks for pointing that out.

Do you want to have a go at integrating FTPS support?

**Comment by aliron19** [comment]
Sure! If I can help you to betatest this feature, let me know how should I proceed.

**Comment by gary-kim** [comment]
I have a go at implementing support. Should probably add this as one of the options in the config for the remote.
