### ISSUE TITLE
Failed to update remote mtime: NoSuchKey: The specified key does not exist

### ISSUE THREAD

**Issue by geoffraeder** [ncw/rclone#315]
Copying from Cloudfiles > S3 and seeing this error on some items.  Can you provide additional details as to what's causing this?  I'm assuming this is related to updating the modification time.

Thanks in advance.  This tool has been really helpful.

**Comment by ncw** [comment]
The mtime is the key on S3 the modification time is stored.

This error actually means that the file "key" that was being updated doesn't exist.

http://www.benhallbenhall.com/2013/01/amazon-s3-error-key-exist/

It probably means that the transfer of that file failed in some way earlier.

Retrying the sync should fix it

**Comment by geoffraeder** [comment]
Thanks for the quick reply.  I'll keep an eye on it next copy.

I also notice that I get 408 request time-out's from Cloudfiles when performing checks.  Should I up the timeout, or do you think this is an issue with the Rackspace server?

**Comment by ncw** [comment]
The 408 comes from the server so upping the rclone timeout probably won't help. I have found that cloud files gets  very busy at times.

**Comment by geoffraeder** [comment]
Ok.  Sorry to keep bugging you, but I also see a lot of this in the output and wondering if I should ignore it or be concerned that copies/checks are failing.  Did some looking around, but it's not clear to me what this actually indicates.

`Unsolicited response received on idle HTTP channel starting with "H"; err=<nil>`

**Comment by ncw** [comment]
That is exciting! Never seen that before. Can you post the whole log line with a few logs before and after?

**Comment by geoffraeder** [comment]
Seems to happen after every check...

2016/01/22 19:52:02 
Transferred:            0 Bytes (   0.00 kByte/s)
Errors:                 0
Checks:                49
Transferred:            0
Elapsed time:      2m0.9s
Checking:
 * Apache/2ABA8D89-AB91-4BF0-95A4-94F5904AA961.png
 * Apache/35C8B81E-EB19-4085-A575-70D717ADFCD7.jpg
 * Apache/39B89A8F-C534-4AA5-87B2-89A18526177F.jpg
 * Apache/3A4D2CF4-0868-491B-A5CB-2EB47E756A5F.jpg
 * Apache/3A74C6A9-5C8B-4D9D-9D20-5F6B41F85B8F.jpg
 * Apache/3B0A473C-32AF-4B9A-9D5D-FFF0D8AADF3D.jpg
 * Apache/3CF9819C-8FDD-43DB-9CE0-D174363B5630.png
 * Apache/3D480626-9ABE-403B-B173-E67287FF8464.jpg

2016/01/22 19:52:26 Unsolicited response received on idle HTTP channel starting with "H"; err=<nil>
2016/01/22 19:52:26 Unsolicited response received on idle HTTP channel starting with "H"; err=<nil>
2016/01/22 19:52:26 Unsolicited response received on idle HTTP channel starting with "H"; err=<nil>
2016/01/22 19:52:26 Unsolicited response received on idle HTTP channel starting with "H"; err=<nil>
2016/01/22 19:52:26 Unsolicited response received on idle HTTP channel starting with "H"; err=<nil>
2016/01/22 19:52:26 Unsolicited response received on idle HTTP channel starting with "H"; err=<nil>
2016/01/22 19:52:26 Unsolicited response received on idle HTTP channel starting with "H"; err=<nil>
2016/01/22 19:52:38 Unsolicited response received on idle HTTP channel starting with "H"; err=<nil>
2016/01/22 19:52:38 Unsolicited response received on idle HTTP channel starting with "H"; err=<nil>
2016/01/22 19:52:59 Unsolicited response received on idle HTTP channel starting with "H"; err=<nil>
2016/01/22 19:52:59 Unsolicited response received on idle HTTP channel starting with "H"; err=<nil>
2016/01/22 19:52:59 Unsolicited response received on idle HTTP channel starting with "H"; err=<nil>
2016/01/22 19:52:59 Unsolicited response received on idle HTTP channel starting with "H"; err=<nil>
2016/01/22 19:53:02 
Transferred:            0 Bytes (   0.00 kByte/s)
Errors:                 0
Checks:              2376
Transferred:            0
Elapsed time:      3m0.9s
Checking:
 * Thomas/144E5FFE-0B37-49AF-A62C-92E7211DAFE0.png
 * Thomas/1C446942-B201-44BF-9FA9-DC2A9EB934DE.png
 * Thomas/1CB1AFD1-ADF8-4A5B-9BC0-E439C57AD282.png
 * Thomas/1CC49756-7394-46F9-9E85-964CEB70850A.jpg
 * Thomas/1CE280B7-7CB2-40DC-8404-D2389FF77BAD.jpg
 * Thomas/1CE3CBEF-20B4-43BB-BCA2-38C7E9B4032C.jpg
 * Thomas/1CF88C8F-807C-4929-AF8A-4D74FAC3A2CC.png
 * Thomas/1D0AB102-E9EE-4A22-A5AD-7C0F76FF6764.png

2016/01/22 19:53:17 Unsolicited response received on idle HTTP channel starting with "H"; err=<nil>
2016/01/22 19:53:17 Unsolicited response received on idle HTTP channel starting with "H"; err=<nil>
2016/01/22 19:53:17 Unsolicited response received on idle HTTP channel starting with "H"; err=<nil>
2016/01/22 19:53:17 Unsolicited response received on idle HTTP channel starting with "H"; err=<nil>
2016/01/22 19:53:17 Unsolicited response received on idle HTTP channel starting with "H"; err=<nil>
2016/01/22 19:53:30 Unsolicited response received on idle HTTP channel starting with "H"; err=<nil>
2016/01/22 19:53:30 Unsolicited response received on idle HTTP channel starting with "H"; err=<nil>
2016/01/22 19:53:45 Unsolicited response received on idle HTTP channel starting with "H"; err=<nil>
2016/01/22 19:53:45 Unsolicited response received on idle HTTP channel starting with "H"; err=<nil>
2016/01/22 19:53:45 Unsolicited response received on idle HTTP channel starting with "H"; err=<nil>
2016/01/22 19:54:02

**Comment by geoffraeder** [comment]
FWIW, I'm running rclone v1.26 AMD64 on Amazon Linux AMI 2015.09.

**Comment by geoffraeder** [comment]
Still stumped by the original issue.  The file does exist.  I can use AWS CLI tools to download it.  Is it possible that it's an issue with the filename?  An encoding issue or something?

`119P_9183_Plasite+4550-ProductFlyer-0515.pdf: Failed to update remote mtime: NoSuchKey: The specified key does not exist.
	status code: 404, request id: `

**Comment by ncw** [comment]
So what that error means is that rclone went to set the modification time on the file, but s3 said it didn't exist which is strange indeed.

The `Unsolicited response received on idle HTTP channel starting with "H"` is strange also.

Both of those things make me wonder about your environment - I haven't seen either of those problems before.

Are you using the pre-compiled binary or did you compile it yourself?  If you compiled it yourself, can you try the pre-compiled binary?

Is it going through some sort of HTTP proxy?

Can you try the transfer on a machine which isn't within EC2?

It might be an eventual consistency thing.  If you retry the sync does it work afterwards?  Or is that file always a problem?

I tried a test with a file of that name on s3 and that didn't seem to be the problem. rclone could set the modification time just fine.

Does `rclone ls` list the file properly?  If so can you send me a snip from the listing?

**Comment by geoffraeder** [comment]
Thanks a lot for responding...

I'm running the pre-compiled binary on EC2.  I'll give it a try on my OS X dev machine.

Here's the output from `rclone ls` which shows the file exists:

>rclone ls S3:\<remote-file-path\>/119P_9183_Plasite+4550-ProductFlyer-0515.pdf
>   679524 119P_9183_Plasite+4550-ProductFlyer-0515.pdf
>
>Transferred:            0 Bytes (   0.00 kByte/s)
>Errors:                 0
>Checks:                 0
>Transferred:            0
>Elapsed time:           0

**Comment by geoffraeder** [comment]
I may be on to something... Ran a copy of a single file with verbose output.  Seems the file content is the same, but the mod time changed.  Essentially, the file was overwritten it seems.  I believe rclone is attempting to update the mod time, but not uploading the object since it didn't change.  The AWS docs indicate that metadata can only be set at the time of uploading the object and not after.  Does this sound right?  Although, if this is the case, the error message is a bit misleading since the file is there.

<pre><code>
rclone -v --contimeout 10m0s --checkers 4 copy Cloudfiles:&lt;remote-file-path>/119P_9183_Plasite+4550-ProductFlyer-0515.pdf S3:&lt;remote-file-path>/119P_9183_Plasite+4550-ProductFlyer-0515.pdf
2016/01/26 13:17:25 S3 bucket production-files.truqcapp.com path data/brandcc/carboline/ limited to 1 objects: Modify window is 1ns
2016/01/26 13:17:25 S3 bucket production-files.truqcapp.com path data/brandcc/carboline/ limited to 1 objects: Building file list
2016/01/26 13:17:25 S3 bucket production-files.truqcapp.com path data/brandcc/carboline/ limited to 1 objects: Waiting for checks to finish
2016/01/26 13:17:25 119P_9183_Plasite+4550-ProductFlyer-0515.pdf: Modification times differ by -184h0m29s: 2016-01-23 08:02:05 +0000 UTC, 2016-01-15 11:01:36 -0500 EST
2016/01/26 13:17:25 119P_9183_Plasite+4550-ProductFlyer-0515.pdf: Failed to update remote mtime: NoSuchKey: The specified key does not exist.
	status code: 404, request id: 
2016/01/26 13:17:25 119P_9183_Plasite+4550-ProductFlyer-0515.pdf: Size and MD5SUM of src and dst objects identical
2016/01/26 13:17:25 119P_9183_Plasite+4550-ProductFlyer-0515.pdf: Unchanged skipping
2016/01/26 13:17:25 S3 bucket production-files.truqcapp.com path data/brandcc/carboline/ limited to 1 objects: Waiting for transfers to finish
2016/01/26 13:17:25 Attempt 1/3 failed with 1 errors
2016/01/26 13:17:25 S3 bucket production-files.truqcapp.com path data/brandcc/carboline/ limited to 1 objects: Building file list
2016/01/26 13:17:25 S3 bucket production-files.truqcapp.com path data/brandcc/carboline/ limited to 1 objects: Waiting for checks to finish
2016/01/26 13:17:25 119P_9183_Plasite+4550-ProductFlyer-0515.pdf: Size and modification time the same (differ by 0, within tolerance 1ns)
2016/01/26 13:17:25 119P_9183_Plasite+4550-ProductFlyer-0515.pdf: Unchanged skipping
2016/01/26 13:17:25 S3 bucket production-files.truqcapp.com path data/brandcc/carboline/ limited to 1 objects: Waiting for transfers to finish

Transferred:            0 Bytes (   0.00 kByte/s)
Errors:                 0
Checks:                 2
Transferred:            0
Elapsed time:        2.2s

2016/01/26 13:17:25 Go routines at exit 19
</code></pre>

**Comment by geoffraeder** [comment]
Hmm, not sure about my theory above.  Performed more of a manual test and it all seemed to work ok.

**Comment by geoffraeder** [comment]
Additional testing reveals that the presence of a '+' in the filename causes the issue.  Tested multiple times updating files with and without a '+' and updates with '+' in the filename failed to update modified time.

**Comment by ncw** [comment]
You can set the meta data after the object has been uploaded  using a COPY. 

It seems plausible that the + is causing the problem, but I can't replicate the problem. 

Did you try from your osx machine? 

Can you write a shell script that reproduces the problem? 

Eg

    mkdir /tmp/test
    echo 'hello' > /tmp/test/file-with+44.pdf
    rclone sync /tmp/test s3:mytest49
    touch /tmp/test/file*
    rclone sync /tmp/test s3:mytest49 

Something like that should reproduce the problem - but I couldn't make it. 

It might be to do with the path of the file too. 

Does your bucket name really have < > in? That could be the problem.

**Comment by geoffraeder** [comment]
I was able to reproduce the problem with the script you suggested.

Regarding the bucket name, I just used a placeholder as to not expose details publicly.

**Comment by ncw** [comment]
I feel stupid now, because I just ran the script I sent you and it reproduces the problem for me now just fine!

```
2016/01/27 17:06:43 HTTP REQUEST
2016/01/27 17:06:43 PUT http://s3.amazonaws.com/mytest50/file-with%2B44.pdf HTTP/1.1
Host: s3.amazonaws.com
User-Agent: rclone/v1.26
Content-Length: 0
Authorization: AWS4-HMAC-SHA256 Credenti[snip]
Content-Type: application/pdf
X-Amz-Acl: 
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Copy-Source: mytest50/file-with+44.pdf
X-Amz-Date: 20160127T170643Z
X-Amz-Meta-Mtime: 1453914402.34825253
X-Amz-Metadata-Directive: REPLACE
Accept-Encoding: gzip
```

```
2016/01/27 17:06:43 HTTP RESPONSE
2016/01/27 17:06:43 HTTP/1.1 404 Not Found
Transfer-Encoding: chunked
Content-Type: application/xml
Date: Wed, 27 Jan 2016 17:06:42 GMT
Server: AmazonS3
X-Amz-Id-2: 55baDyXyzc+SSEIWHVJ+yvSo+BW1Lr8yOdTg5nRuleC59dodpeWJAbSMFytup75eYps/6j3u4T8=
X-Amz-Request-Id: 56F1855EE2332F05

f8
<Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Key>file-with 44.pdf</Key><RequestId>56F1855EE2332F05</RequestId><HostId>55baDyXyzc+SSEIWHVJ+yvSo+BW1Lr8yOdTg5nRuleC59dodpeWJAbSMFytup75eYps/6j3u4T8=</HostId></Error>
0
```

Which makes the problem blindingly obvious - `<Key>file-with 44.pdf</Key>` is a give away.

I've fixed this and uploaded a beta for you to try

http://pub.rclone.org/v1.26-48-gcae19df%CE%B2/

If it doesn't fix it for you then please re-open the ticket!

**Comment by geoffraeder** [comment]
Thanks for implementing a fix so quickly!  Much appreciated.  I'll give it a try.

**Comment by geoffraeder** [comment]
Hmm, this new version seems to be resulting in out of memory errors.

**Comment by ncw** [comment]
Once transfers start memory should be stable. Can you see if it goes up while transfers are in progress? Maybe there is a memory leak. It is probably unrelated to this issue though.

**Comment by geoffraeder** [comment]
Seems to be happening prior to any transfers starting.

**Comment by arunpal-kiwi** [comment]
Hi i am using minio 3.0.6 . its working fine for upload file in java .But it give me a error while i am trying to download a file

error occured
ErrorResponse(code=NoSuchKey, message=The specified key does not exist., bucketName=null, objectName=null, resource=/resourse-server/284/health/1509086845373.doc, requestId=3L137, hostId=3L137)
request={method=GET, url=http://host:port/bucketName/284/health/1509086845373.doc, headers=Range: bytes=0-
Host: hostname:portnumber
User-Agent: Minio (amd64; amd64) minio-java/dev
x-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
x-amz-date: 20171028T063134Z
Authorization: AWS4-HMAC-SHA256 Credential=REDACTED/20171028/us-east-1/s3/aws4_request, SignedHeaders=host;range;x-amz-content-sha256;x-amz-date, Signature=REDACTED
}
response={code=404, headers=Accept-Ranges: bytes
Content-Type: application/xml
Server: Minio/RELEASE.2017-07-24T18-27-35Z (linux; amd64)
Vary: Origin
X-Amz-Request-Id: 14F1A834C5D82B02
Date: Sat, 28 Oct 2017 06:31:34 GMT
Transfer-Encoding: chunked
}
please help me

**Comment by ncw** [comment]
@mudkipme can you please make a [new issue on github](https://github.com/ncw/rclone/issues/new) about this and fill in the info there like which cloud provider, what command you were using and a log - thanks!
