### ISSUE TITLE
Set scheduling time and create snapshot for backup

### ISSUE THREAD

**Issue by Danissss** [ncw/rclone#3152]
#### Describe the issue
I am thinking to use rclone for backing up my google drive on remote server.

May I ask how to setup the schedule timeline? 
Should I set the time inside code like [this](https://github.com/ncw/rclone/blob/master/fs/bwtimetable.go)? 

If I accidentally delete some file (potentially all the file) in google drive, I am afraid of it will affect it with my backup. 
Is that possible to create snapshot of the backup through rclone?

Thanks!

**Comment by calisro** [comment]
You can use Cron or any schedule tool to run it. And you can use the --backup-dir to keep replaced/deleted files on a sync. You also though would have the Google trash.

**Comment by Danissss** [comment]
Thank you
