### ISSUE TITLE
Creating a new remote FTP via HTTP API doesnot encrypt the password

### ISSUE THREAD

**Issue by sauravhaloi** [ncw/rclone#3153]
#### What is the problem you are having with rclone?
I tried using the HTTP API in rclone to create a new config for an FTP backend. Here is what I did in details:

Start the remote control HTTP server:
```
$ export RCLONE_CONFIG_PASS="MyPassword"
$ rclone rcd --rc-no-auth
2019/05/01 14:01:46 NOTICE: Serving remote control on http://127.0.0.1:5572/
```
Create a new FTP config using the HTTP API with cURL:
```
$ curl -iX POST   http://127.0.0.1:5572/config/create   -H 'Accept: application/json'   -H 'Content-Type: application/json'   -H 'cache-control: no-cache'   -d '{
    "name": "MyTestFTP",
    "type": "ftp",
    "parameters": {
        "host": "localhost",
        "user": "ftpuser",
        "port": 21,
        "pass": "ftppass",
        "concurrency": 0
    }
}'
HTTP/1.1 200 OK
Access-Control-Allow-Headers: 
Access-Control-Allow-Origin: *
Date: Wed, 01 May 2019 08:36:54 GMT
Content-Length: 3
Content-Type: text/plain; charset=utf-8

{}

```
View the created config:
```
$ rclone config show

[MyTestFTP]
type = ftp
pass = ftppass
port = 21
user = ftpuser
concurrency = 0
host = localhost
```
Try mounting the remote FTP location:
```
$ rclone mount MyTestFTP: /tmp/ftp --dir-cache-time 2s --poll-interval 1s
2019/05/01 14:09:02 Failed to create file system for "MyTestFTP:": NewFS decrypt password: input too short when revealing password - is it obscured?
```

So, basically rclone did not encrypt the password while creating the FTP config, but the mount command of rclone by default expects an encrypted password

If the do the same config creation via the command line as below, the password is encrypted by default:
```
$ rclone config create MyTestFTP ftp concurrency 0 host localhost port 21 user ftpuser pass ftppass
Remote config
--------------------
[MyTestFTP]
type = ftp
user = ftpuser
pass = *** ENCRYPTED ***
concurrency = 0
host = localhost
port = 21
--------------------
```
Thus there is a mismatch in the HTTP API for config creation as opposed to by the command line. Did I miss anything?

#### What is your rclone version (output from `rclone version`)
rclone v1.47.0
- os/arch: linux/amd64
- go version: go1.12.4

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
```
$ uname -a
Linux inspiron 4.15.0-48-generic #51-Ubuntu SMP Wed Apr 3 08:28:49 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic
```

####  Which cloud storage system are you using? (eg Google Drive)
FTP server, vsftpd 3.0.3-9build1 for Ubuntu 18.04LTS

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
```
rclone mount MyTestFTP: /tmp/ftp --dir-cache-time 2s --poll-interval 1s
```
#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
N/A

**Comment by ncw** [comment]
You should be able to use the [config/password](https://rclone.org/rc/#config-password-password-the-config-for-a-remote) call to create encrypted passwords.

> If the do the same config creation via the command line as below, the password is encrypted by default:

Actually if you look at the config file you see an unencrypted password

```
[MyTestFTP]
type = ftp
user = ftpuser
pass = ftppass
concurrency = 0
host = localhost
port = 21
```

The `config/create` and `config/password` map directly onto `rclone config create` and `rclone config password`.

It would be possible to change `config/create` to encrypt passwords, but this would be a backwards incompatible change which I try to avoid if possible!

**Comment by sauravhaloi** [comment]
Thanks @ncw for your response.
So, is there a way through which I can tell ```rclone mount``` command to use an unencrypted password for an FTP backend? It seems ```rclone mount``` by default tries to decrypt the password:

```
// NewFs constructs an Fs from the path, container:path
func NewFs(name, root string, m configmap.Mapper) (ff fs.Fs, err error) {
	// defer fs.Trace(nil, "name=%q, root=%q", name, root)("fs=%v, err=%v", &ff, &err)
	// Parse config into Options struct
	opt := new(Options)
	err = configstruct.Set(m, opt)
	if err != nil {
		return nil, err
	}
	pass, err := obscure.Reveal(opt.Pass)
	if err != nil {
		return nil, errors.Wrap(err, "NewFS decrypt password")
	}
...
...
```
which leads to error: ```Failed to create file system for "FTP:": NewFS decrypt password: input too short when revealing password - is it obscured?```

**Comment by ncw** [comment]
> So, is there a way through which I can tell `rclone mount` command to use an unencrypted password

That is the FTP backend and at the moment it requires all passwords to be encrypted.

There is an issue here for an `--no-obscure` flag https://github.com/ncw/rclone/issues/2265 which would solve your problem.

You can set the encrypted password like this using two rc calls

```
curl -iX POST   http://127.0.0.1:5572/config/create   -H 'Accept: application/json'   -H 'Content-Type: application/json'   -H 'cache-control: no-cache'   -d '{
    "name": "MyTestFTP",
    "type": "ftp",
    "parameters": {
        "host": "localhost",
        "user": "ftpuser",
        "port": 21,
        "concurrency": 0
    }
}'
```

then

```
curl -iX POST   http://127.0.0.1:5572/config/password   -H 'Accept: application/json'   -H 'Content-Type: application/json'   -H 'cache-control: no-cache'   -d '{
    "name": "MyTestFTP",
    "parameters": {"pass": "ftpass"}
}'
```

**Comment by sauravhaloi** [comment]
Thank you @ncw, Your suggestions should suffice my need for now. I am closing this issue.
