### ISSUE TITLE
serve ftp: advertise configured passive addr

### ISSUE THREAD

**Issue by calisro** [ncw/rclone#3158]
vsftpd alllows us to set a advertised ip address for PASSIVE connections so that if a ftp server is located behind a firewall and the client is also behind its own firewall that the connection can be advertised to the client correctly.  An example would be a ftp server on GCP which has a VMs external ip address behind a device.

pasv_address=X.X.X.X

can we add a similar parameter to rclone serve ftp to allow this?

pasv_address
Use this option to override the IP address that vsftpd will advertise in response to the PASV command. Provide a numeric IP address, unless pasv_addr_resolve is enabled, in which case you can provide a hostname which will be DNS resolved for you at startup.
Default: (none - the address is taken from the incoming connected socket)

The issue is that the address currently advertised on rclone is the address on the incoming socket which confuses a client to connecting to the internal interface of a VM on GCP for example resulting in failures.

**Comment by ncw** [comment]
I think this should be a question of setting the `PublicIp` in the [ServerOpts](https://godoc.org/github.com/goftp/server#ServerOpts) structure from a config variable  `--ftp-public-ip` maybe.

Do you fancy having a go at this?

**Comment by calisro** [comment]
```
       ftpopt := &ftp.ServerOpts{
                Name:           "Rclone FTP Server",
                WelcomeMessage: "Welcome on Rclone FTP Server",
                Factory: &DriverFactory{
                        vfs: vfs.New(f, &vfsflags.Opt),
                },
                Hostname:     host,
                Port:         portNum,
                PassivePorts: opt.PassivePorts,
                PublicIp: "<REDACTED_IP_ADDRESS>",
                Auth: &Auth{
                        BasicUser: opt.BasicUser,
                        BasicPass: opt.BasicPass,
                },
                Logger: &Logger{},
                //TODO implement a maximum of https://godoc.org/github.com/goftp/server#ServerOpts
        }

```

Just for grins I simply hard-coded it to see if it worked.  It also failed to get a data connection.

**Comment by calisro** [comment]
https://github.com/goftp/server/issues/25

I saw this issue but setting the publicip with the port also does not address the problem.

**Comment by calisro** [comment]
Hmm.  Saw this:

https://github.com/goftp/server/issues/25

Adding a port to the IP address fixed this issue.
