### ISSUE TITLE
rclone mount on android tv box with no root

### ISSUE THREAD

**Issue by thetorx** [ncw/rclone#3160]
hi there,
i'm trying to mount a gdrive partition with rclone (1.47) on an android tv box (xiaomi mi box s).
i managed to access in ssh but i have no root privileges, and when i try to mount i get this:

`2019/05/03 14:49:56 mount helper error: fusermount: failed to open /dev/fuse: Permission denied
2019/05/03 14:49:56 Fatal error: failed to mount FUSE fs: fusermount: exit status 1`

i think it's because i don't have root privileges no change to make a su.

any idea how to solve this? it's sooooo annoying....

thanks a lot

**Comment by calisro** [comment]
This is a android limitation.  Not really anything rclone can address.  Even with root its hard to mount file systems and make them accessible across user spaces on android.

**Comment by thetorx** [comment]
i think the issue is that rclone is trying to use fusermount that, by default, tries to use /dev/fuse where my user has insufficient rights.
is there any way to istruct rclone/fusermount to user another path where my user is the owner? sorry if it's a silly question, but i am not really a *nix user and i don't really know what fusermount or fuse are.
thanks

**Comment by calisro** [comment]
"This is a android limitation. Not really anything rclone can address. Even with root its hard to mount file systems and make them accessible across user spaces on android."

Nope.  You can't.

**Comment by ncw** [comment]
Thanks @calisro for providing the definitive answer.  I'll close this now - thanks.
