### ISSUE TITLE
Large files (>35GB) not uploading properly to Google Drive mount

### ISSUE THREAD

**Issue by ctlaltdefeat** [ncw/rclone#3167]
#### What is the problem you are having with rclone?
Large files are not being uploaded correctly to an encrypted Google Drive mount.
The filesystem 'cp' command gives the following error:
```cp: error writing 'gdrive/file.txt': Input/output error```
and the file is left in an incomplete state in the remote.

It should be noted that the equivalent 'rclone copy' finishes successfully.

Steps to reproduce:

Create a Google Drive remote and then an encrypted remote for it.
Create a large file:
```dd if=/dev/zero of=file.txt count=1024 bs=40048576```
Mount with the following parameters:
```rclone mount --config=rclone.conf --allow-other --dir-cache-time 24h --buffer-size 2K --drive-chunk-size 512M --vfs-read-chunk-size 128M --vfs-read-chunk-size-limit off --vfs-cache-max-age 12h --poll-interval 15s --transfers 12 --drive-pacer-min-sleep 20ms --vfs-cache-mode writes gdrive_encrypted:/ gdrive/ -vv```
Copy created file:
```cp file.txt gdrive/```
Wait for the error, which should occur after the file is (incompletely) allocated on the remote, but before the uploading of the actual chunks begins, if that makes sense.

Other important info:
I have enough space on disk for the VFS cache of the file.
Smaller files work perfectly well.
The rclone logs do not seem to have any relevant info that I can see and they're full with irrelevant file accesses, but if I should be on the look out for a specific line let me know.

#### What is your rclone version (output from `rclone version`)
1.47

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Linux 64 bit

####  Which cloud storage system are you using? (eg Google Drive)
Google Drive

**Comment by ncw** [comment]
Interesting.  I haven't managed to reproduce yet as my machine doesn't have enough free disk space!

> The rclone logs do not seem to have any relevant info that I can see and they're full with irrelevant file accesses, but if I should be on the look out for a specific line let me know.

There should be at least one ERROR log to match that `cp: error writing 'gdrive/file.txt': Input/output error` log message - debug logs around there would be good.

**Comment by ctlaltdefeat** [comment]
Sorry, I figured it out and it appears it's unrelated to rclone. 
systemd was suppressing log messages due to so many being similar, but once I disabled that I saw that that the VFS cache was stored in my /tmp/ partition, and that it's on a separate partition with less storage.
I'll try setting the VFS cache to a different location and if there's still an issue (unlikely) I'll reopen this issue.
