### ISSUE TITLE
Support Rclone auto start in docker on mount

### ISSUE THREAD

**Issue by leopkks** [ncw/rclone#3168]
I have this command below running in a docker container with ubuntu 18.04
need a script when the container is restarted
upload a command in mount
to ride
server configuration
4 of DISCO RAM 20 GB HD
use mount to access remote files
in google drive total 500 GB of data
where to create a virtual disk for access
but with the command I reported below is not being opened
because a container docker has no way to use the command
scree r inside the container
I need commands where I mount the script inside the docker container
so he is executing to be able to access the files.
I'm waiting and thank you from ja
follow example ...
of the script below that I am using.
are scripts where they are accessed from mp4 mp3 pdf. mkv .rar .zip
these are the scripts I have on google drive,

rclone mount   --allow-non-empty --allow-other --default-permissions --tpslimit 10 --tpslimit-burst 10 --dir-cache-time=160h --buffer-size=64M --attr-timeout=1s --vfs-read-chunk-size=2M  --vfs-read-chunk-size-limit=2G --vfs-cache-max-age=5m  --vfs-cache-mode=writes --cache-dir "/path/cache" drive: /path/drive --config "/root/.config/rclone/rclone.conf"

**Comment by ncw** [comment]
I think you'd be better asking this on [the rclone forum](https://forum.rclone.org/) as your question is more about how to use docker than rclone - thanks.
