### ISSUE TITLE
Optional Configuration Encryption

### ISSUE THREAD

**Issue by klauspost** [ncw/rclone#317]
There should be an option to encrypt the configuration file. 

Edit: This proposal is for the entire file. For most use cases this is fine, and I don't want to go into the additional complexity for encrypting selected fields.

* [x] Encrypted file detection. Could just be a magic file start value.
* [x] Determine encryption method/file encoding. (secretbox+base64?)
* [x] Add option to `rclone config` to add/remove configuration encryption.
* [x] Add detection for encrypted configuration and ask for password.
* [x] Add tests.
* [x] Add documentation.

I have forked [goconfig](https://github.com/klauspost/goconfig), so it can read/save from memory. The current implementation writes data to a temporary file before loading, and can only write to disk.

According to the internets [nacl secretbox](https://godoc.org/golang.org/x/crypto/nacl/secretbox) is a good generic implementation, which offers both encryption and validation. ~~We don't need the nonce functionality per se, but we can have a static nonce for password validation.~~

For this we need a 32 byte key. A [SHA256](https://golang.org/pkg/crypto/sha256/) of the password should be plenty - we can even add global salt for a very slight security increase. This *will not be saved*, but will be used for sealing/unsealing the package. 

The goal is to still allow configuration to be copied from one machine to another.

**Comment by klauspost** [comment]
I added a PR.

I didn't encounter any issues, so if it is ok, I will move on to adding tests and documentation.

**Comment by ncw** [comment]
I made a rather important comment on the PR about the nonce...

I think the approach looks fine.

You might find the goconfig author will take a PR from you - I've found him responsive in the past. The reason why I used that library rather than any other was that was the only one I could find which had write support at the time.

**Comment by klauspost** [comment]
Re `goconfig`: I guess if I didn't change the interface I would have a better chance. That said it would be easy to change the interface back.

I just assumed that it would be a struggle, since he states "This library is under bug fix only mode, which means no more features will be added".

**Comment by ncw** [comment]
This was done in bfd7601cf9c1fb39653b30e8c2fbeb512778bb87
