### ISSUE TITLE
TestCachePurgeOverQuota fails or finds no directory

### ISSUE THREAD

**Issue by RizzerOnGitHub** [ncw/rclone#3173]
#### What is the problem you are having with rclone?

The TestCachePurgeOverQuota test is either not finding a directory or failing.

#### What is your rclone version (output from `rclone version`)

v1.47

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

Debian unstable 64bit (amd64)

go test -vet=off -v -p 4 github.com/ncw/rclone/vfs (I think)

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

Try to build rclone for debian.  On my own computer TestCachePurgeOverQuota reports an error, but the test passes:

        run.go:168: Remote "Local file system at /tmp/rclone308180609", Local "Local file system at /tmp/rclone836669420", Modify Window "1ns"
    === RUN   TestCachePurgeOverQuota
    2019/05/07 11:14:07 ERROR : : error listing: directory not found
    --- PASS: TestCachePurgeOverQuota (0.00s)

On Debian machines, however the test fails:

        run.go:168: Remote "Local file system at /tmp/rclone750152608", Local "Local file system at /tmp/rclone546073727", Modify Window "1ns"
    === RUN   TestCachePurgeOverQuota
    2019/05/07 08:22:17 ERROR : : error listing: directory not found
    --- FAIL: TestCachePurgeOverQuota (0.00s)
        run.go:168: Remote "Local file system at /tmp/rclone750152608", Local "Local file system at /tmp/rclone546073727", Modify Window "1ns"
        require.go:794: 
            	Error Trace:	cache_test.go:507
            	Error:      	Received unexpected error:
            	            	mkdir /sbuild-nonexistent: permission denied
            	            	make cache directory failed
            	            	github.com/ncw/rclone/vfs.(*cache).mkdir
                	            		/<<BUILDDIR>>/rclone-1.47.0+ex1/obj-x86_64-linux-gnu/src/github.com/ncw/rclone/vfs/cache.go:152
            	            	github.com/ncw/rclone/vfs.TestCachePurgeOverQuota
            	            		/<<BUILDDIR>>/rclone-1.47.0+ex1/obj-x86_64-linux-gnu/src/github.com/ncw/rclone/vfs/cache_test.go:506
            	            	testing.tRunner
            	            		/usr/lib/go-1.11/src/testing/testing.go:827
            	            	runtime.goexit
            	            		/usr/lib/go-1.11/src/runtime/asm_amd64.s:1333
            	Test:       	TestCachePurgeOverQuota

Is this kind of fragility in the TestCachePurgeOverQuota test expected?

**Comment by RizzerOnGitHub** [comment]
The full Debian log can be found at
https://buildd.debian.org/status/package.php?p=rclone&suite=experimental
e.g. for amd64:
https://buildd.debian.org/status/fetch.php?pkg=rclone&arch=amd64&ver=1.47.0%2Bex1-3&stamp=1557217419&raw=0

**Comment by ncw** [comment]
> Is this kind of fragility in the TestCachePurgeOverQuota test expected?

No...  You can ignore the `error listing: directory not found` log, that is normal I think.

What it looks like is that rclone is failing to make a local cache directory.  I'm guessing $HOME is set to `/sbuild-nonexistent` which will be the problem.

Setting `$XDG_CACHE_HOME` would work around the problem I think.

**Comment by RizzerOnGitHub** [comment]
I currently do have XDG_CONFIG_HOME set, `export XDG_CONFIG_HOME=/dev/null`.  I set it to /dev/null because on my own machine the tests were picking up my personal rclone.conf, which isn't appropriate when building

What is an appropriate path for XDG_CACHE_HOME in the context of an independent build? $(CURDIR)/build or somesuch?

**Comment by ncw** [comment]
> What is an appropriate path for XDG_CACHE_HOME in the context of an independent build? $(CURDIR)/build or somesuch?

Yes a temporary directory you'll delete after sounds fine.

**Comment by RizzerOnGitHub** [comment]
Thanks. I'll try setting XDG_CONFIG_HOME and XDG_CACHE_HOME to the same build dir, unless you warn me against that.

**Comment by RizzerOnGitHub** [comment]
Thanks again Nick.  I've got successful builds after setting XDG_CONFIG_HOME and XDG_CACHE_HOME  to $(CURDIR)/buildtest.

That's a satisfactory fix for me, but I'll leave this bug open for you to decide whether this workaround is sufficient to close the bug or whether more robustness should be added in the code.

**Comment by ncw** [comment]
Great, glad you got it working.

I think being able to set those env vars should be good enough so I'll close this - it will be searchable for anyone who has the same problem in the future.
