### ISSUE TITLE
bash: line 157: mandb: command not found

### ISSUE THREAD

**Issue by Sopor** [ncw/rclone#3175]
When i installed rclone i got this error message:
`bash: line 157: mandb: command not found`

Instead of showing this error message it must be easy to check if mandb exists and instead show  a nice message and tell the user that rclone will still work but the help can be limited when the `man` command is not available.

rclone v1.47.0

Linux dietpi 4.14.98-v7+

**Comment by TenZdenda** [comment]
same problem

**Comment by ncw** [comment]
That is a great idea - fancy sending a Pull Request?
