### ISSUE TITLE
Issues when excluding permission denied directories

### ISSUE THREAD

**Issue by Jikeh** [ncw/rclone#3179]
I'm running rclone on Android7 with Termux. I'm trying to copy the SD mountpoint over a Google Team Drive, but i'm getting permission denied errors because of the .android_secure folder: 

`2019-05-09 17:26:47 ERROR : Attempt 1/3 failed with 1 errors and: failed to read directory "": lstat /storage/SD/.android_secure: permission denied`

Excluding the folder (`--exclude /.android_secure/**`) doesn't change anything. It seems there is no way to skip this folder, and after 3 retries rclone quits.

```
rclone v1.47.0
- os/arch: android/arm64
- go version: go1.12.2
Android 7, ARMv8-A 64-bit
```
Any way I could skip folders that give permission denied errors?

**Comment by ncw** [comment]
Unfortunately the filtering works at a layer above the local backend which is where the error is generated...

I haven't figured out a sensible workaround for that.  To fix properly I need the local backend to read the flters and ignore errors for files/directories which are excluded.

A workaround might be to introduce a new flag which causes the local backend to ignore errors.  There is one already `--skip-links` for symlinks, maybe we need `--ignore-permissions-errors` or something like that.

**Comment by Jikeh** [comment]
A `--ignore-permissions-errors` flag would be perfect, since there is no way to keep rclone from stopping when this type of errors happen. Playing with `--retries ` and  `--retries-sleep` doesn't work either since it keeps hanging on that one first directory and doesn't continue.

**Comment by ncw** [comment]
I had a different idea so I went back to see how rsync deals with this problem.  What it does is log errors and report an error on exit, but otherwise runs normally just without the files/directories it can't access.  It also doesn't do the delete phase of a sync operation.

I made rclone do exactly the same logging errors in the listing phase and reporting an error at the end of the command.  This also stops the delete phase of a sync (this is old code).

What do you think?

https://beta.rclone.org/branch/v1.47.0-064-gffed9847-fix-3179-local-perms-beta/ (uploaded in 15-30 mins)

**Comment by Jikeh** [comment]
I'm having a hard time installing the beta package inside the Termux environment, however, I've created a few root-owned dirs (v1.47.0 stable, in a regular linux environment) to simulate denied access and the error I'm getting is slightly different: 
`2019-05-12 22:10:39 ERROR : PermDir: error reading source directory: failed to open directory "PermDir": open /home/rcloneTest/PermDir: permission denied`

In the previous case regarding the .android_secure dir I'd get an lstat read error: 
`2019-05-09 17:26:47 ERROR : Attempt 1/3 failed with 1 errors and: failed to read directory "": lstat /storage/SD/.android_secure: permission denied`

Also, in the test run it continued to copy the other files and won't stop because of the error.
I obviously don't expect support for the Termux environment so I'm planning for a little script that does the filtering beforehand for rclone, but regarding the `--ignore-permissions-errors ` flag it would still be useful in many other cases. Your idea to emulate rsync's behavior is fine, but in the sync case I believe it should offer an option to proceed to the delete phase as well regardless of the error.

**Comment by ncw** [comment]
> Also, in the test run it continued to copy the other files and won't stop because of the error.

Good - that is what it is supposed to do.

> Your idea to emulate rsync's behavior is fine, but in the sync case I believe it would be useful for it to offer an option to proceed to the delete phase as well regardless of the error.

Rclone already has a flag for that `--ignore-errors` (stolen from rsync!)

I'm not 100% convinced that what I've done is the right solution, but getting closer to rsync's behaviour seems like a win.

BTW I have this exact problem with my /tmp directory with dead rclone mounts which give a similar error

**Comment by Jikeh** [comment]
> Rclone already has a flag for that `--ignore-errors` (stolen from rsync!)

Right! I forgot about that flag. Seems like the right solution then.
> BTW I have this exact problem with my /tmp directory with dead rclone mounts which give a similar error

You mean the lstat read error? If your fix makes it so it runs normally and skips the files/directories it can't access then I believe it solves the problem.

**Comment by ncw** [comment]
OK great!

I'll merge this then. I think it will make a lot of rclone users happy, though it may have some unintended consequences - we'll see!
