### ISSUE TITLE
Use a Tab delimited file to upload files to remote

### ISSUE THREAD

**Issue by manishgupta24** [ncw/rclone#3180]
Hi,

I have a TSV file getting generated from another service which has a format like
`Path\tName\tSize\...` etc.
Currently Rclone takes the source directory and does its own scan (os walk). I want to use this report instead of scan and upload all the files/folders listed in the file to the remote.

How can I do that? I am open to make some changes in rclone code to do this. Any guidance would be appreciated.

Thanks

**Comment by ncw** [comment]
Rclone can take a file with one filename per line using the [--files-from](https://rclone.org/filtering/#files-from-read-list-of-source-file-names) flag.

I would use sed/python/perl to transform your input TSV into the file that rclone needs - you'll end up with a script which is only a few lines long.

**Comment by manishgupta24** [comment]
Hi Nick if I use the --files-from flag, will the folder scan/walk happen?

**Comment by ncw** [comment]
> Hi Nick if I use the --files-from flag, will the folder scan/walk happen?

No it won't.

**Comment by manishgupta24** [comment]
Thanks
