### ISSUE TITLE
exported variables not working like before

### ISSUE THREAD

**Issue by calisro** [ncw/rclone#3201]
Previously I had a sudo setup to run rclone as a root user.  As of the latest beta, this has broken:

```
vpnuser@cloudc:~$  export RCLONE_CONFIG=/root/.rclone.conf
vpnuser@cloudc:~$ rclone listremotes
<REDACTED>
vpnuser@cloudc:~$ sudo rclone listremotes
2019/05/15 13:33:57 NOTICE: Config file "/data/vpnuser/.config/rclone/rclone.conf" not found - using defaults
```

Then I do this in a different terminal to put back the old version ( I did NOT log out of the shell above btw)....  
`root@cloudc:/bin# mv rclone rclone1 && mv rclone.v1.47.0-015-gaba15f11-beta rclone`

And all works:
```
vpnuser@cloudc:~$ sudo rclone listremotes
<REDACTED>
vpnuser@cloudc:~$ 
```

Did anything change with the way environmental variables are handled?

The version this is failing on is:
rclone v1.47.0-067-g9c6f3ae8-beta
- os/arch: linux/amd64
- go version: go1.12.5

**Comment by calisro** [comment]
Hmm.  Not sure if this is an environ variable problem or if rclone just is no longer reading the home directory the same.  I saw a commit changing the home directory behavior.  I'd suspect that has something to do with this?  I can obviously change the sudo to work around this easily if needed.

**Comment by ncw** [comment]
Yes the home directory detection changed recently to use a much better library than the code we had already.

I didn't think it would break stuff - thanks for the heads up as I'm sure you won't be the only one.
