### ISSUE TITLE
Support for Google Drive File Stream (GDFS)

### ISSUE THREAD

**Issue by SL-Gundam** [ncw/rclone#3207]
With the recent issues with Google Drive and Rclone i tried several things to improve the situation including the suggested --user-agent parameter. While it seems to improve the situation, it wasn't a complete return to the old situation

One of the things i tried is Google Drive File Stream (GDFS) in combination with Rclone. This worked pretty good (especially for downloading and RcloneBrowser) since google does not seem to limit their own tools in commands or bandwidth.
I also noticed some drawbacks/issues
- No bandwidth limiter available in GDFS
- Temporary upload cache required for GDFS
- If you close Rclone mid transfer GDFS will upload the complete file even though it was incomplete
- An issue which made uploading files using this method get corrupted. (this is why i'm creating this issue)
- Time decimal difference between local and GDFS

Here is what i did
- Install GDFS
- Create the necessary config in Rclone

\---------------------------
[cryptGDstream]
type = crypt
remote = localGDstream:G:\My Drive\Crypt
filename_encryption = standard
directory_name_encryption = true
password = *****
password2 = *****

[localGDstream]
type = local
\---------------------------

I was hoping you would be willing to add support for GDFS or atleast fix the encountered issue below

#### What is the problem you are having with rclone?
GDFS creates a virtual drive in Windows. This drive does not seem to support the full set of commands normal drives do when it comes to files.

It seems that Rclone writes its files with certain chunks. Trimming down the file after the last chunk is written. GDFS does not support this trimming down at the end of writing the file

This causes errors in size and checksum

Another issue was that GDFS only uses 3 decimals for the time while the local system uses 7 decimals. This causes it find modifications that do not exist.
2019/05/16 01:50:49 DEBUG : Voltcraft Energy Logger data/ProcmonConfiguration.pmc: Modification times differ by -381.5µs: 2016-04-29 23:35:17.6803815 +0200 CEST, 2016-04-29 23:35:17.680 +0200 CEST
2019/05/16 01:50:49 NOTICE: Voltcraft Energy Logger data/ProcmonConfiguration.pmc: Not copying as --dry-run

I'm hoping its possible to add support for using GDFS in combination with Rclone

#### What is your rclone version (output from `rclone version`)
Tried both of these
rclone-v1.47.0-070-g8c550363-beta-windows-amd64.zip
rclone-v1.47.0-windows-amd64.zip

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Windows 10 1809 x64

####  Which cloud storage system are you using? (eg Google Drive)
Google Drive

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
C:\rclone\test\rclone.exe sync --transfers 1 --fast-list --delete-after --delete-excluded --exclude-from "C:/rclone/Configs/Exclusions.txt" --progress --log-file "C:\Users\User\Desktop\MirrorD Log\Rclone TEST.log" --log-level DEBUG D:/test/ cryptGDstream:TEST

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

\---------------------------
2019/05/16 19:34:14 DEBUG : rclone: Version "v1.47.0" starting with parameters ["C:\\rclone\\test\\rclone.exe" "sync" "--transfers" "1" "--fast-list" "--delete-after" "--delete-excluded" "--exclude-from" "C:/rclone/Configs/Exclusions.txt" "--progress" "--log-file" "C:\\Users\\User\\Desktop\\MirrorD Log\\Rclone TEST 2019-05-16 193414.log" "--log-level" "DEBUG" "D:/test/" "cryptGDstream:TEST"]
2019/05/16 19:34:14 DEBUG : Using config file from "C:\\Users\\User\\.config\\rclone\\rclone.conf"
2019/05/16 19:34:14 INFO  : Encrypted drive 'cryptGDstream:TEST': Waiting for checks to finish
2019/05/16 19:34:14 INFO  : Encrypted drive 'cryptGDstream:TEST': Waiting for transfers to finish
2019/05/16 19:34:14 ERROR : Mirror D_NAS 2019-05-15 010002.105.log: corrupted on transfer: sizes differ 9919 vs 10192
2019/05/16 19:34:14 INFO  : Mirror D_NAS 2019-05-15 010002.105.log: Removing failed copy
2019/05/16 19:34:14 ERROR : Mirror D_NAS 2019-05-16 010002.307.log: corrupted on transfer: sizes differ 7978 vs 8144
2019/05/16 19:34:14 INFO  : Mirror D_NAS 2019-05-16 010002.307.log: Removing failed copy
\---------------------------

\---------------------------
2019/05/16 01:50:49 DEBUG : Voltcraft Energy Logger data/ProcmonConfiguration.pmc: Modification times differ by -381.5µs: 2016-04-29 23:35:17.6803815 +0200 CEST, 2016-04-29 23:35:17.680 +0200 CEST
2019/05/16 01:50:49 NOTICE: Voltcraft Energy Logger data/ProcmonConfiguration.pmc: Not copying as --dry-run
\---------------------------

**Comment by ncw** [comment]
> It seems that Rclone writes its files with certain chunks. Trimming down the file after the last chunk is written. GDFS does not support this trimming down at the end of writing the file
> 
> This causes errors in size and checksum

Do any files get transferred properly?

> 2019/05/16 19:34:14 ERROR : Mirror D_NAS 2019-05-15 010002.105.log: corrupted on transfer: sizes differ 9919 vs 10192

Might that have been caused by the log changing size during the transfer?


> Another issue was that GDFS only uses 3 decimals for the time while the local system uses 7 decimals. This causes it find modifications that do not exist.
> 2019/05/16 01:50:49 DEBUG : Voltcraft Energy Logger data/ProcmonConfiguration.pmc: Modification times differ by -381.5µs: 2016-04-29 23:35:17.6803815 +0200 CEST, 2016-04-29 23:35:17.680 +0200 CEST
> 2019/05/16 01:50:49 NOTICE: Voltcraft Energy Logger data/ProcmonConfiguration.pmc: Not copying as --dry-run

This is easy to fix using the `--modify-window` flag.  For 3 decimal places of time, you want `--modify-window 1ms`.

**Comment by SL-Gundam** [comment]
No files get transferred properly

The files in question are just some test files i dropped in the folder so they did not change

**Comment by SL-Gundam** [comment]
If you want to test it yourself i can provide you with a temporary gsuite account

**Comment by SL-Gundam** [comment]
We might need to scrap this idea because of the way GDFS deals with long filenames

2019/05/19 19:04:58 DEBUG : 9f0ie842lm70lum1jmjh868gts/m33um0aq2lu225rft08fg8go9roivuvj8pu06hnuo9nbqo40o5rcmdsqjt0tikcotnl4os5kg69nvvjj0hfk6clcl4e1nodsbm8hvlbmleckgnso1bpead29ht7fdnu~pejejcoli22nohkn30uqc8fbfrdkm7pqgup7cocak1c7c0sm19o4jj7irtk74khjf6ovjoll9kg0mntq9j9f75ubuk3p26mt1fs0nl9q8d6ldqq0mud66cjfnspm6kq: Skipping undecryptable file name: illegal base32 data at input byte 127

It basically removes part of the filename (right in the middle) and replaces it with ~ to get itself to 255 characters

**Comment by ncw** [comment]
> None get transferred properly
> 
> The files in question are just some test files i dropped in the folder so they did not change

So it sounds like something rclone is doing is not agreeing with GDFS.  As far as I know rclone doesn't do anything too strange.  Maybe the preallocate is upsetting it somehow.

There isn't a flag to turn that off, but you could comment it out these 4 lines

https://github.com/ncw/rclone/blob/cff85f0b9551881be535a4847b56742451e6b476/backend/local/local.go#L977-L980

> It basically removes part of the filename (right in the middle) and replaces it with ~ to get itself to 255 characters

:nauseated_face: really!

**Comment by SL-Gundam** [comment]
It might be the prealloc. I've checked the content of the correct file against the one being uploaded and there only NULL characters at the end to fill out the file to the sizes mentioned.

I'm closing this issue. I will reopen once GDFS does not fuck up the filenames

**Comment by lightc786** [comment]
SL-Gundam, do you know if GDFS 255 character issue has been resolved? I'm looking whether I can use GDFS with rclone crypt to get two way syncing of an encrypted folder

**Comment by SL-Gundam** [comment]
You can easily verify this without causing issues. Just don't let Rclone sync against it
This has not changed

![image](https://user-images.githubusercontent.com/912973/95739833-badd8800-0c8b-11eb-9320-779561f0bbaf.png)

**Comment by lightc786** [comment]
Yeah, I verified this myself after posting my message but had not had a chance to come back here to update my post. I guess I will try to use rclonesync-v2 to automate some of my emulation setup between PCs.  By the way, Gundam is awesome. Not sure if you're into any of the games, but I've been playing ExVsFB recently on rpcs3 and the performance has improved a ton since a year ago.
