### ISSUE TITLE
google drive auth without browser

### ISSUE THREAD

**Issue by x09** [ncw/rclone#321]
i have remote shell on server. no graphics, no browsers, text only..

I have a problem with authorization rclone (step - go to http://127.0.0.1:53682/auth)
I try use links, elinks, links2, w3m - nothing (javascript in text browsers is very big problem)

May be add somthing as -no-browser-auth option of skicka ( https://github.com/google/skicka ) for some as i am?.

**Comment by ncw** [comment]
Run through the config again, but answer `N` to this question. 

```
Use auto config?
 * Say Y if not sure
 * Say N if you are working on a remote or headless machine or Y didn't work
```

Go to the link in your desktop browser and paste the token.

**Comment by x09** [comment]
wow) my eyes)) thanks!

**Comment by ncw** [comment]
No problem!

**Comment by CumaliTurkmenoglu** [comment]
> Run through the config again, but answer `N` to this question.
> 
> ```
> Use auto config?
>  * Say Y if not sure
>  * Say N if you are working on a remote or headless machine or Y didn't work
> ```
> 
> Go to the link in your desktop browser and paste the token.

How about Google Drive config_verification_code? How can I authorize Rclone without using the url that provided for GDrive auth 2.0?

Thank you


`Use auto config?
 * Say Y if not sure
 * Say N if you are working on a remote or headless machine

y) Yes (default)
n) No
y/n> n
Verification code

Go to this URL, authenticate then paste the code here.

https://accounts.google.com/o/oauth2/auth?access_type=offline&client_id=202264815644.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&response_type=code&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive&state=gCIb_xHpnRkvu94TOwWTEw

Enter a string value. Press Enter for the default ("").
config_verification_code> `

**Comment by ncw** [comment]
> How about Google Drive config_verification_code? How can I authorize Rclone without using the url that provided for GDrive auth 2.0?

If you can't use oauth then you will need to make a service account, or copy the config from a machine which can use oauth.

**Comment by thisnugroho** [comment]
is it possible to this in one line command (?)

**Comment by simonliu009** [comment]
I used `ssh -L localhost:53682:localhost:53682 username@remote_server` to set up a tunnel.
When question `Use auto config` shows up, type in "Y"
```shell
Use auto config?
 * Say Y if not sure
 * Say N if you are working on a remote or headless machine or Y didn't work
 ```
Then copy and paste the auth url `http://127.0.0.1:53682/auth?state=xxxxxxxxxxxx`   to the browser on your local machine, complete the auth and it is done!

**Comment by ncw** [comment]
@simonliu009 neat!

Maybe we should add that as a 3rd option here: https://rclone.org/remote_setup/ as it is quite easy for linux/macOS users at least.

Want to send a pull request to https://github.com/rclone/rclone/blob/master/docs/content/remote_setup.md ?

**Comment by simonliu009** [comment]
@ncw 
Already sent the pull request.
I hope I did it right.

**Comment by FresBlueMan** [comment]
selected n and how to get authorize url?
y) Yes (default)
n) No
y/n> n

Option config_token.
For this to work, you will need rclone available on a machine that has
a web browser available.
For more help and alternate methods see: https://rclone.org/remote_setup/
Execute the following on the machine with the web browser (same rclone
version recommended):
        rclone authorize "drive" "eyJzY29wZSI6ImRyaXZlIn0"
Then paste the result.
Enter a value.
config_token>

**Comment by ncw** [comment]
The instructions are printed - these should work:

Execute the following on the machine with the web browser (same rclone
version recommended):

    rclone authorize "drive" "eyJzY29wZSI6ImRyaXZlIn0"

Then paste the result.

**Comment by stroodle96** [comment]
I am having the same problem. When I run the authorize command on another machine that is not headless I get an error saying "Invalid Number of arguments: 2". 
Any ideas what's causing this?

**Comment by jzebedee** [comment]
> I am having the same problem. When I run the authorize command on another machine that is not headless I get an error saying "Invalid Number of arguments: 2". Any ideas what's causing this?

I had this issue while using an old version of rclone from my distro packages (`rclone (1.53.3-4ubuntu1)`). After uninstalling it and installing the latest `rclone v1.61.1`, the problem resolved.

**Comment by Feedy88** [comment]
> I am having the same problem. When I run the authorize command on another machine that is not headless I get an error saying "Invalid Number of arguments: 2". Any ideas what's causing this?

I had the same issue, for me ensuring using the same version also fixed it. Make sure to use the install script from rclone.org, as apt installed a quite old version on my lxc
