### ISSUE TITLE
Trash deletion in remote g. drive - not working?

### ISSUE THREAD

**Issue by caspertone2003** [ncw/rclone#3211]
Using rclone v1.47.0-073-gcff85f0b-beta @ W10 x64
Trying to empty Trash in a G. Drive remote.

Doing

rclone about remote:
rclone cleanup remote:
rclone about remote:

In cleanup used -v, -vv, -vvv (produces information but not related to cleanup...)

Size of Trash before and after is same. No output related to deletion.

Potential bug?

thanks,
TIA

**Comment by ncw** [comment]
I think emptying the trash happens in the background somewhat asyncrhonously.  People have reported it taking 24 hours for lots of trash.  It doesn't mention that in [the API docs though](https://developers.google.com/drive/api/v3/reference/files/emptyTrash).

This could do with a note [in the docs](https://github.com/ncw/rclone/blob/master/docs/content/drive.md)...

**Comment by caspertone2003** [comment]
thanks, will observe and report back.
CT

**Comment by caspertone2003** [comment]
@ncw 

Thanks again.
Confirmed, trash is cleaned.

Proposed text for docs

If you wish to empty your trash you can use the rclone cleanup remote: command which will permanently delete all your trashed files. This command does not take any path arguments.
Note that Google Drive takes some time lapse (minutes to days) to empty trash - beware that cleanup does not happen instantly and no output is echoed, so there will be no confirmation even using -v, -vv nor -vvv.

CT

**Comment by ncw** [comment]
Great :-)

I've lightly edited your text and stuck it in the docs - thank you :-)

 9aac2d6965222c6ae8483695e5835ec3737eed8a
