### ISSUE TITLE
Fatal error unknown command

### ISSUE THREAD

**Issue by FloLaco** [ncw/rclone#3217]
#### What is the problem you are having with rclone?

When I try to use the option `--allow-other`, I get a fatal error

#### What is your rclone version (output from `rclone version`)

rclone v1.47.0
- os/arch: linux/arm64
- go version: go1.12.4

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

OS                   : Debian GNU/Linux 9
Arch                 : aarch64 (64 Bit)

####  Which cloud storage system are you using? (eg Google Drive)

One Drive

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

`/usr/bin/rclone --vfs-cache-mode writes --allow-other --uid 110 --gid 115 --umask 002  mount onedrive: /mnt/OneDrive/`

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

```
root@rian-arm:~# /usr/bin/rclone --vfs-cache-mode writes --allow-other --uid 110 --gid 115 --umask 002  mount onedrive: /mnt/OneDrive/
Error: unknown command "110" for "rclone"
Run 'rclone --help' for usage.
2019/05/21 20:25:32 Fatal error: unknown command "110" for "rclone"

root@rian-arm:~# export RCLONE_ALLOW_OTHER=true

root@rian-arm:~# /usr/bin/rclone -vv --vfs-cache-mode writes --uid 110 --gid 115 --umask 002  mount onedrive: /mnt/OneDrive/
2019/05/21 21:16:46 Couldn't find flag "allow-other"
```

**Comment by Cnly** [comment]
Hi, you need to use the mount-specific flags after the `mount` command. Please change your command into the following and try again:

`/usr/bin/rclone mount --vfs-cache-mode writes --allow-other --uid 110 --gid 115 --umask 002 onedrive: /mnt/OneDrive/`

**Comment by FloLaco** [comment]
Thank you, it's working with the mount before
