### ISSUE TITLE
--backup-dir doesn't work for single file copy/move

### ISSUE THREAD

**Issue by Cnly** [ncw/rclone#3219]
#### What is the problem you are having with rclone?

`rclone.1` [says](https://github.com/ncw/rclone/blob/a0d4fdb2fa34c7f6ac5a86021d16403713499aaf/rclone.1#L4547) `--backup-dir` works for "sync, copy or move", but in fact it only works for `sync`. From the code it seems this option is only implemented for `sync`, and if that is the case the doc should be refined.

#### What is your rclone version (output from `rclone version`)

```
rclone v1.47.0-074-g81fad0f0-beta
- os/arch: linux/amd64
- go version: go1.12.5
```

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

`Debian GNU/Linux 10 (buster), x86_64`

####  Which cloud storage system are you using? (eg Google Drive)

Any backends should be the same.

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

`rclone -vv move myfile remote:afolder --backup-dir remote:backupdir`

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

```
2019/05/22 16:21:52 DEBUG : rclone: Version "v1.47.0-074-g81fad0f0-beta" starting with parameters ["rclone" "-vv" "move" "myfile" "remote:afolder" "--backup-dir" "remote:backupdir"]
2019/05/22 16:21:52 DEBUG : Using config file from "/home/me/.config/rclone/rclone.conf"
2019/05/22 16:21:56 DEBUG : myfile: Sizes differ (src 30217 vs dst 3218)
2019/05/22 16:21:56 DEBUG : myfile: Starting multipart upload
2019/05/22 16:21:56 DEBUG : myfile: Uploading segment 0/30217 size 30217
2019/05/22 16:21:57 INFO  : myfile: Copied (replaced existing)
2019/05/22 16:21:57 INFO  : myfile: Deleted
2019/05/22 16:21:57 INFO  :
Transferred:       29.509k / 29.509 kBytes, 100%, 5.984 kBytes/s, ETA 0s
Errors:                 0
Checks:                 2 / 2, 100%
Transferred:            1 / 1, 100%
Elapsed time:        4.9s

2019/05/22 16:21:57 DEBUG : 9 go routines active
2019/05/22 16:21:57 DEBUG : rclone: Version "v1.47.0-074-g81fad0f0-beta" finishing with parameters ["rclone" "-vv" "move" "myfile" "remote:afolder" "--backup-dir" "remote:backupdir"]
```

**Comment by ncw** [comment]
I'm under the impression that `--backup-dir` should work for move and copy and it did appear to in my tests below using the local backend.  I tried a test with onedrive with identical results.

Which backend did you use for your tests?

## Copy test

```
$ date -Is > a/one
$ date -Is > b/one
$ 
$ tree a
a
└── one

0 directories, 1 file
$ tree b
b
└── one

0 directories, 1 file
$ tree a-backup
a-backup

0 directories, 0 files
$ rclone -vv copy b a --backup-dir a-backup
2019/05/22 20:33:32 DEBUG : rclone: Version "v1.47.0-075-gd70d9484-fix-3210-b2-copy-beta" starting with parameters ["rclone" "-vv" "copy" "b" "a" "--backup-dir" "a-backup"]
2019/05/22 20:33:32 DEBUG : Using config file from "/home/ncw/.rclone.conf"
2019/05/22 20:33:32 INFO  : Local file system at /tmp/a: Waiting for checks to finish
2019/05/22 20:33:32 DEBUG : one: Modification times differ by -2.108011217s: 2019-05-22 20:33:11.72847651 +0100 BST, 2019-05-22 20:33:09.620465293 +0100 BST
2019/05/22 20:33:32 DEBUG : one: MD5 = 3dc1a751d4623d47b9701729d71570a1 (Local file system at /tmp/b)
2019/05/22 20:33:32 DEBUG : one: MD5 = 20ffc7074def254bdbf04e055f06ed43 (Local file system at /tmp/a)
2019/05/22 20:33:32 DEBUG : one: MD5 differ
2019/05/22 20:33:32 INFO  : one: Moved (server side)
2019/05/22 20:33:32 INFO  : Local file system at /tmp/a: Waiting for transfers to finish
2019/05/22 20:33:32 INFO  : one: Copied (new)
2019/05/22 20:33:32 INFO  : 
Transferred:   	        26 / 26 Bytes, 100%, 2.289 kBytes/s, ETA 0s
Errors:                 0
Checks:                 2 / 2, 100%
Transferred:            1 / 1, 100%
Elapsed time:          0s

2019/05/22 20:33:32 DEBUG : 3 go routines active
2019/05/22 20:33:32 DEBUG : rclone: Version "v1.47.0-075-gd70d9484-fix-3210-b2-copy-beta" finishing with parameters ["rclone" "-vv" "copy" "b" "a" "--backup-dir" "a-backup"]
$ tree a
a
└── one

0 directories, 1 file
$ tree a-backup
a-backup
└── one

0 directories, 1 file
```

## Move test

```
$ date -Is > b/one
$ date -Is > a/one
$ rm a-backup/one 
$ tree a
a
└── one

0 directories, 1 file
$ tree b
b
└── one

0 directories, 1 file
$ tree a-backup/
a-backup/

0 directories, 0 files
$ 
$ rclone -vv move b a --backup-dir a-backup
2019/05/22 20:35:06 DEBUG : rclone: Version "v1.47.0-075-gd70d9484-fix-3210-b2-copy-beta" starting with parameters ["rclone" "-vv" "move" "b" "a" "--backup-dir" "a-backup"]
2019/05/22 20:35:06 DEBUG : Using config file from "/home/ncw/.rclone.conf"
2019/05/22 20:35:06 DEBUG : Local file system at /tmp/a: Using server side directory move
2019/05/22 20:35:06 INFO  : Local file system at /tmp/a: Server side directory move failed - fallback to file moves: can't copy directory - destination already exists
2019/05/22 20:35:06 DEBUG : one: Modification times differ by 3.564019065s: 2019-05-22 20:34:40.252948804 +0100 BST, 2019-05-22 20:34:43.816967869 +0100 BST
2019/05/22 20:35:06 DEBUG : one: MD5 = 107a6ea2f17e4f2c36de8139641246db (Local file system at /tmp/b)
2019/05/22 20:35:06 DEBUG : one: MD5 = 220f8cd6100d3884f26f2639269d5a69 (Local file system at /tmp/a)
2019/05/22 20:35:06 DEBUG : one: MD5 differ
2019/05/22 20:35:06 INFO  : one: Moved (server side)
2019/05/22 20:35:06 INFO  : one: Moved (server side)
2019/05/22 20:35:06 INFO  : Local file system at /tmp/a: Waiting for checks to finish
2019/05/22 20:35:06 INFO  : Local file system at /tmp/a: Waiting for transfers to finish
2019/05/22 20:35:06 INFO  : 
Transferred:   	         0 / 0 Bytes, -, 0 Bytes/s, ETA -
Errors:                 0
Checks:                 3 / 3, 100%
Transferred:            0 / 0, -
Elapsed time:          0s

2019/05/22 20:35:06 DEBUG : 4 go routines active
2019/05/22 20:35:06 DEBUG : rclone: Version "v1.47.0-075-gd70d9484-fix-3210-b2-copy-beta" finishing with parameters ["rclone" "-vv" "move" "b" "a" "--backup-dir" "a-backup"]
$ 
$ 
$ tree a
a
└── one

0 directories, 1 file
$ tree a-backup
a-backup
└── one

0 directories, 1 file
```

**Comment by Cnly** [comment]
I was using OneDrive, but I think I found the problem. In [cmd/copy](https://github.com/ncw/rclone/blob/master/cmd/copy/copy.go#L75), rclone runs a sync if src is a directory and runs a CopyFile operation if it is a single file. Your commands are doing this on directories so `--backup-dir` works.

**Comment by ncw** [comment]
Gotcha :-)

So just after this in `moveOrCopyFile`

https://github.com/ncw/rclone/blob/9aac2d6965222c6ae8483695e5835ec3737eed8a/fs/operations/operations.go#L1469-L1475

We need to implement this bit of logic which does the moving to the backup dir.

https://github.com/ncw/rclone/blob/9aac2d6965222c6ae8483695e5835ec3737eed8a/fs/sync/sync.go#L227-L241

That opens a whole can of worms about where the backupDir comes from...

I'll work on that!

**Comment by ncw** [comment]
Ok I fixed that here (in the fix-3219 branch)

https://beta.rclone.org/branch/v1.47.0-078-gb19f6572-fix-3219-beta/ (uploaded in 15-30 mins)

I implemented an Fs cache along the way which is something I've been meaning to do...

Care to give it a go?

**Comment by Cnly** [comment]
Thanks, that was fast. I did some testing and found a segfault:

```
github.com/ncw/rclone/fs/operations.moveOrCopyFile(0x177e8c0, 0xc000187040, 0x0, 0x0, 0x7ffd06b28e64, 0x5, 0x7ffd06b28e64, 0x5, 0xc0001de001, 0x0, ...)
        rclone/fs/operations/operations.go:1452 +0xe9
github.com/ncw/rclone/fs/operations.CopyFile(...)
        rclone/fs/operations/operations.go:1513
github.com/ncw/rclone/cmd/copy.glob..func1.1(0xc0005c4be0, 0x48)
        rclone/cmd/copy/copy.go:79 +0xbe
```

with the command `rclone -vv copy a.txt testdir --backup-dir backupdir`, which seems to be caused by this incorrect handling of error:

https://github.com/ncw/rclone/blob/b19f6572d7199b17aeeb173aa87dab09be544c36/fs/cache/cache.go#L30-L35

`NewFs` may return a non-`nil` `fs` with the error `fs.ErrorIsFile`.

**Comment by ncw** [comment]
> `NewFs` may return a non-`nil` `fs` with the error `fs.ErrorIsFile`.

Ah, well spotted!

Try this!

https://beta.rclone.org/branch/v1.47.0-078-gc94b7f62-fix-3219-beta/ (uploaded in 15-30 mins)

**Comment by Cnly** [comment]
I found no problems with the new version so far; we should be good to go. :)

**Comment by ncw** [comment]
Thanks for testing - I merged that now.

**Comment by yparitcher** [comment]
While trying to implement --suffix without --backup-dir i ran into this bug.

```
rclone v1.48.0
- os/arch: linux/amd64
- go version: go1.12.5
```

right now you check for the existence of --backup-dir in move & copy, however in sync there are a few sanity checks in newSyncCopyMove() that are not done here, for example not allowing the backup directory to be the same as the src or dst

https://github.com/ncw/rclone/blob/4549305fec833bf50516d287002cdba6548695c9/fs/sync/sync.go#L134-L142

so right now a command like:
```
rclone copy local/one.txt dest --backup-dir=local
```
will overwrite the src or error.


Unless you want to duplicate the checks and all --backup-dir and --suffix code, it might better to make a separate function somewhere (in config?) that gets passed the src, dst, backupdir, and suffix, that returns the final backup directory and suffix or an error.
this can then be called by any of the primitives if either backupdir or suffix flags are used.

this will also make implementing #2801 simpler.

if you think that is a good idea i and can point me where to put it i will start on it.
thanks
