### ISSUE TITLE
How to execute silently

### ISSUE THREAD

**Issue by Lionel09** [ncw/rclone#322]
I'm trying to execute ```rclone``` silently to have only execution log in a log file

Is it possible to have no output at all in the console?

I've tried without success:
```
rclone sync /mybackup/path remote:container --log-file="/var/log/rclone.log"
 ```
```
rclone sync /mybackup/path remote:container > "/var/log/rclone.log"
 ```

**Comment by ncw** [comment]
This should do the trick

    rclone sync /mybackup/path remote:container > "/var/log/rclone.log" 2>&1

**Comment by Lionel09** [comment]
Thanks a lot!
