### ISSUE TITLE
Taking into account ctime when using min/max age

### ISSUE THREAD

**Issue by ellisonpatterson** [ncw/rclone#3237]
#### What is your current rclone version (output from `rclone version`)?
1.47.0

#### What problem are you are trying to solve?
Allow utilizing min/max age when running, for example, `rclone move`, to target a file based on it's change time rather than just its modify time.

#### How do you think rclone should be changed to solve that?
Maybe add a parameter `--use-local-ctime` or something to only select files based on time criteria for local files. Nothing with any external APIs, just for files on the server.

**Comment by ncw** [comment]
Rclone only has a concept of one time per object.

You could use a parameter `--local-use-ctime` to make that time be the ctime of the object for the local file system.

This would mean that the object would be synced using the ctime and the ctime would end up on the remote server.

This problem might be better solved with`find .... > list-of-files` then `rclone copy --files-from list-of-files`?

**Comment by ellisonpatterson** [comment]
Alright I'll just do that, for anyone curious I'm using these parameters for `find`:
`find /mnt/move -type f -cmin -240 -printf "%P\n" > /folder/move.log`
With `-240` meaning anything older than 240 minutes.

**Comment by ellisonpatterson** [comment]
Alright sounds good, I'm using these parameters for the `find` command:
`find /mnt/move -type f -cmin +120 -printf "%P\n" > /folder/move.log`
Where it outputs the files relative to the same path defined as the source with `rclone copy` (/mnt/move) and also moves files with a ctime older than 120 minutes.
