### ISSUE TITLE
--exclude not working with path in double quotes

### ISSUE THREAD

**Issue by cdancette** [ncw/rclone#3238]
#### What is the problem you are having with rclone?

The option --exclude doesn't work with a path that is in double quotes.

Example: `rclone sync /home/me server:home --exclude ".cache/**"` doesn't exclude the .cache directory. 

But doing the same command with `--exclude .cache/**` works.

Not sure this is expected

#### What is your rclone version (output from `rclone version`)
rclone v1.47.0
- os/arch: linux/amd64
- go version: go1.12.4

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

linux, ubuntu 19.04

####  Which cloud storage system are you using? (eg Google Drive)

GDrive, jottacloud, hard drive

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

`rclone sync -x -P -v --links $SRC $DEST --backup-dir $OLD --suffix ".$date" --exclude ".cache/**"`

**Comment by Cnly** [comment]
Hi,

I did some testing and I think it's working for me. Maybe you could change double quotes into single quotes and try again?

```
$ rclone -V
rclone v1.47.0-074-g81fad0f0-beta
- os/arch: linux/amd64
- go version: go1.12.5

$ rclone --dry-run sync . /tmp/destdir
2019/05/31 14:38:11 NOTICE: a.txt: Not copying as --dry-run
2019/05/31 14:38:11 NOTICE: c.txt: Not copying as --dry-run
2019/05/31 14:38:11 NOTICE: b.txt: Not copying as --dry-run
2019/05/31 14:38:11 NOTICE: deepdir/d.txt: Not copying as --dry-run

$ rclone --dry-run sync . /tmp/destdir --exclude deepdir/**
2019/05/31 14:38:01 NOTICE: a.txt: Not copying as --dry-run
2019/05/31 14:38:01 NOTICE: b.txt: Not copying as --dry-run
2019/05/31 14:38:01 NOTICE: c.txt: Not copying as --dry-run
$ rclone --dry-run sync . /tmp/destdir --exclude "deepdir/**"
2019/05/31 14:38:06 NOTICE: a.txt: Not copying as --dry-run
2019/05/31 14:38:06 NOTICE: b.txt: Not copying as --dry-run
2019/05/31 14:38:06 NOTICE: c.txt: Not copying as --dry-run
$ rclone --dry-run sync . /tmp/destdir --exclude 'deepdir/**'
2019/05/31 14:38:19 NOTICE: a.txt: Not copying as --dry-run
2019/05/31 14:38:19 NOTICE: c.txt: Not copying as --dry-run
2019/05/31 14:38:19 NOTICE: b.txt: Not copying as --dry-run
```

**Comment by ncw** [comment]
> Example: `rclone sync /home/me server:home --exclude ".cache/**"` doesn't exclude the .cache directory.

Can you run that with `-vv` and post the first line of the output

```
$ rclone -vv sync /home/me nonexistent:home --exclude ".cache/**"
2019/06/03 17:48:36 DEBUG : rclone: Version "v1.47.0-DEV" starting with parameters ["rclone" "-vv" "sync" "/home/me" "nonexistent:home" "--exclude" ".cache/**"]
```

That will show exactly what the shell is passing to rclone.

Which shell are you using?

**Comment by cdancette** [comment]
Hi,
The output :
```
$  rclone -vv sync /home/me nonexistent:home --exclude ".cache/**"

2019/06/03 20:45:55 DEBUG : rclone: Version "v1.47.0" starting with parameters ["rclone" "-vv" "sync" "/home/me" "nonexistent:home" "--exclude" ".cache/**"]
2019/06/03 20:45:55 DEBUG : Using config file from "/home/coco/.config/rclone/rclone.conf"
2019/06/03 20:45:55 Failed to create file system for "nonexistent:home": didn't find section in config file
```

Actually with your input I found the problem.
I had the command in a script like this : 
```
#!/bin/bash
exclude='--exclude ".cache/**"'
rclone -vv sync /home/me nonexistent:home $exclude
```

And this will escape the double quotes : the debug is
```
2019/06/03 22:02:22 DEBUG : rclone: Version "v1.47.0" starting with parameters ["rclone" "-vv" "sync" "/home/me" "nonexistent:home" "--exclude" "\".cache/**\""]
```

**Comment by ncw** [comment]
> Thank you very much for your answer, i fixed the script !

Excellent :-)  That is why I put that debug in, it helps debugging scripts!
