### ISSUE TITLE
Solved: Slow GoogleDrive again... ReadFileHandle.Read error: low level retry 1/10: unexpected EOF (Google Server issues)

### ISSUE THREAD

**Issue by snickers2k** [ncw/rclone#3244]
Seems like the same issue like before. Every segment takes years to load.
2019/06/02 21:36:08 ERROR : xxxxxxxxxxxx.mkv: ReadFileHandle.Read error: low level retry 1/10: unexpected EOF

**Comment by Nanodragon999** [comment]
Yes, you're not the only one
check https://status.cloud.google.com/incident/compute/19003
and probably this too https://www.google.com/appsstatus#hl=en&v=status

**Comment by snickers2k** [comment]
Thanks for that info.
