### ISSUE TITLE
serve restic: Support for private repositories in restic http server functionality

### ISSUE THREAD

**Issue by apollo13** [ncw/rclone#3247]
#### What is your current rclone version (output from `rclone version`)?

```
rclone v1.47.0
- os/arch: linux/amd64
- go version: go1.11.6
```

#### What problem are you are trying to solve?

Use `rclone serve restic` as restic backend and limit users to their own repositories.

#### How do you think rclone should be changed to solve that?

It would be great if `rclone serve restic` supported the `--private-repos` flag like the original rest server from restic does:
```
      --private-repos       users can only access their private repo
```
This would limit users to a subpath of `/<username>/`

**Comment by ncw** [comment]
At the moment the restic server is almost entirely agnostic in terms of paths. 

Are you supplying users via basic auth and an htpasswd file?

Do you want to work on this feature?

**Comment by apollo13** [comment]
> Are you supplying users via basic auth and an htpasswd file?

Yes

> Do you want to work on this feature?

I'd like to but I have never written a line go in my life :)

**Comment by ncw** [comment]
I'm happy to help you or anyone else develop this :-)

**Comment by apollo13** [comment]
Ok, I'll open a draft PR over the next days and try my best.

**Comment by ncw** [comment]
> Ok, I'll open a draft PR over the next days and try my best.

That would be great.  Let me know if you need any help.

**Comment by apollo13** [comment]
Ok, I started looking at the code and managed to add a new flag. I am currently wondering how I should pass the username from

https://github.com/ncw/rclone/blob/b7800e96d72d7daf559c6db69fc465bccec04c92/cmd/serve/httplib/httplib.go#L153

on to the restic handler without breaking all the other backends :)

**Comment by ncw** [comment]
> Ok, I started looking at the code and managed to add a new flag. I am currently wondering how I should pass the username from
> 
> https://github.com/ncw/rclone/blob/b7800e96d72d7daf559c6db69fc465bccec04c92/cmd/serve/httplib/httplib.go#L153
> 
> on to the restic handler without breaking all the other backends :)

The easiest way would be to stick it in the http.Request, so r.Header.Set("X-Remote-User", username) or something like that.

The restic handler will have access to that.  There is probably a standard for the name of the header to use!

**Comment by apollo13** [comment]
I have started #3249 -- it seems to work so far. How would I go about reading the common name out of the client certificates (if used)?

**Comment by apollo13** [comment]
Actually I just realized that one could use htpasswd and client certs, not that it exactly makes sense…

**Comment by ncw** [comment]
> I have started #3249 -- it seems to work so far. How would I go about reading the common name out of the client certificates (if used)?

Errm...  I did a bit of reading but I didn't find out how to :-( Does the original restic server do this?  Maybe we can look in there?

**Comment by apollo13** [comment]
It does not support client certs at all :)

**Comment by ncw** [comment]
> It does not support client certs at all :)

Might have to ask for help if that is a feature you want to support!

**Comment by apollo13** [comment]
I think I'd be fine without for now. After all the foundation is there and it can be added later.
