### ISSUE TITLE
Rclone copy --files-from tag takes some time before staring the migration

### ISSUE THREAD

**Issue by manishgupta24** [ncw/rclone#3248]
Hi

I am trying to upload a folder using copy command and I am passing a list of files using `--files-from` tag. If I use copy without this tag the migration starts immediately. But when using this tag, Rclone waits for some time before the files start copying to destination.

The wait time depends on the number of files I am trying to migrate with the `--files-from` tag, from few seconds to more than 15 minutes and above.

I tested it with a folder containing around 5k files and the initial wait time was around 45 minutes.

I looked into the code and this might be happening because Rclone creates a DirTree for the list of files provided with the tag. https://github.com/ncw/rclone/blob/a28239f005aeb290528e8373d5b99d2efa34c870/fs/walk/walk.go#L714-L715

My question is why does this take more time as compared to the Folder Walk using `os.Walk`, since we are passing the absolute path. Is there any way to shorten this wait time or better bypass this?

**Comment by ncw** [comment]
Which backend are you using?  Google drive is particularly slow with `--files-from`. 

Which version of rclone are you using?

With --files-from rclone finds all the files first before starting the transfers as you've noted.

In [the latest beta](https://beta.rclone.org) I changed the algorithm so that it will now traverse directories to find the files from list, unless you use --no-traverse when it will use the 1.47 behaviour.

So give [the latest beta](https://beta.rclone.org) a go and see if that fixes your problem.

**Comment by manishgupta24** [comment]
My Source is a local Windows Directory and My destination is Google Cloud Storage bucket.
I am using Rclone version 1.45.

> In the latest beta I changed the algorithm so that it will now traverse directories to find the files from the list, unless you use --no-traverse when it will use the 1.47 behavior.

How is it different from not passing a list of files using --files-from tag? By default the rclone traverses the directory given as argument with copy command?

**Comment by ncw** [comment]
> How is it different from not passing a list of files using --files-from tag? By default the rclone traverses the directory given as argument with copy command.

You still pass the list of files with `--files-from`, rclone v1.48 beta just converts that into a filter which turns out to be as efficient as trying to find each file individually (as v1.47 does).

**Comment by manishgupta24** [comment]
> rclone v1.48 beta just converts that into a filter ...
Hi, The latest version is rclone v1.47.0-128-g22368b99-beta according to version.txt on [Rclone beta](https://beta.rclone.org). Where can I find the version 1.48 beta ?

**Comment by ncw** [comment]
> > rclone v1.48 beta just converts that into a filter ...
> 
> Hi, The latest version is rclone v1.47.0-128-g22368b99-beta according to version.txt on [Rclone beta](https://beta.rclone.org). Where can I find the version 1.48 beta ?

That is the 1.48 beta it is 1.47 + a lot but isn't 1.48 yet!

**Comment by manishgupta24** [comment]
Thanks It worked.
