### ISSUE TITLE
Mysterious disappearance of local files

### ISSUE THREAD

**Issue by isaiah36** [ncw/rclone#325]
Hello,

I discovered quite by accident, while repairing playlists in my music player, that some of my music files had disappeared.  The folders are still there, sub folders and their files are still there, but the music, image and text files in the main folder are gone!  I am not sure that rclone did it, but I can't think what else might have happened.  I use Linux because the file system is reliable, in my experience anyway.

The only thing I can think of is that a massive amount of data (about 170 GB) was being copied and pasted into the synced drive from an USB drive, when rclone was launched by crontab.  The 2 processes ran simultaneously for about 2 minutes at most, before the copy-paste operation completed without any error messages.  The sync operation on the new data is still running as I type this.  Could this have caused the accidental deletions?

Also, is there a command that will make rclone list all directories with less than 100 MB of data?  I want to discover all the folders that suffered deletions.  There are too many to inspect manually.  Very luckily for me, I will have access to most of the music for another 2-3 weeks, so I can still replace the deleted files, but this experience has put a real fright in me.  I am wondering if I should stop using automated sync, and update the cloud drive manually via web browser.

Thanks for your time and attention!

**Comment by ncw** [comment]
The only time rclone deletes data is if you are using the sync command (not copy) and only from the destination. So what was the command running on the crontab? If it was syncing data to the cloud then it wasn't rclone.

Can you paste the command you were running on the crontab and the command you were using to copy data into the synced drive, that is the two commands that were running at once.

**Comment by ncw** [comment]
The Unix command

    du -m | sort -rn | tail -n 100

WIll list the 100 directories with the least content starting from the current directory.

**Comment by isaiah36** [comment]
The crontab command is /usr/sbin/rclone sync /home/isaiah/Music Adrive:Music.  I don't know the text of the command for the copy-paste operation.  I was using the Caja file manager that comes with the Mate desktop.  It used to be called Nautilus in the Gnome desktop before the project forked.

I am going to try and remember not to be writing to the drive when rclone is running.  Some sort of glitch happened.  I have replaced the files I know about.

**Comment by isaiah36** [comment]
Thanks for that, NCW!

**Comment by ncw** [comment]
` /usr/sbin/rclone sync /home/isaiah/Music Adrive:Music` only reads data from `/home/isaiah/Music` so I think it is unlikely rclone deleted any files in there.

Did you run out of disk space at one point?  That might explain it?

**Comment by isaiah36** [comment]
Nope, plenty of drive space.  I am more inclined myself to blame the glitch on this edition of Linux, which behaves more like Windows than any Linux I can ever remember using.  Rclone doesn't strike me as erratic or buggy.

**Comment by ncw** [comment]
I'm going to close this as I don't think we are going to get to the bottom of it! If you have any more info then please re-open.  Thanks, Nick.
