### ISSUE TITLE
[Question] Decrypt with external CLI utillity

### ISSUE THREAD

**Issue by amgxv** [ncw/rclone#3251]
Hi, i'm just testing the crypt feature of rclone and I have a little question

Is there any way to decrypt files encrypted with **rclone** with a CLI utillity like _openssl_? Do I have to decrypt files mandatorily with rclone?
That feature is awesome, but i want to reduce the impact of losing files.

Thanks so much!

**Comment by ncw** [comment]
There isn't an external utility to decrypt rclone files.

However you can encrypted files on a local directory and set up a crypt remote to decrypt them quite easily.

**Comment by amgxv** [comment]
I think I'll do that!

Thanks for the fast answer!
