### ISSUE TITLE
Locally deleted files aren't deleted on the cloud

### ISSUE THREAD

**Issue by yurivict** [ncw/rclone#326]
It worked before, but from some point previously deleted files aren't deleted on the google drive any more, and this causes 'quote exceeded' error.

**Comment by yurivict** [comment]
This seems to be a full Trash folder issue.

**Comment by ncw** [comment]
Do you have the error produced when the delete failed?

I might put that in the docs with the resolution if you do.

Thanks

Nick

**Comment by yurivict** [comment]
I store backups of fixed size on Google Drive, up to count=3. Older ones are deleted. It worked until few days ago, then quota began to fail. When I looked, I saw that Trash folder was full of older files. I assumed the older files get to Trash through a API deletion for some reason, because I didn't even login to Google Drive myself.

I will watch it for a few more days and see what happens. Can't tell with certainty what is wrong.

**Comment by ncw** [comment]
Normally rclone deletes stuff permanently via the trash.  It does make revisions though.

Here are the bits from the docs

### Revisions ###

Google drive stores revisions of files.  When you upload a change to
an existing file to google drive using rclone it will create a new
revision of that file.

Revisions follow the standard google policy which at time of writing
was

  * They are deleted after 30 days or 100 revisions (whatever comes first).
  * They do not count towards a user storage quota.

### Deleting files ###

By default rclone will delete files permanently when requested.  If
sending them to the trash is required instead then use the
`--drive-use-trash` flag.
