### ISSUE TITLE
Multiple calls to LoadConfig() to force a reload of the config file

### ISSUE THREAD

**Issue by maran** [ncw/rclone#3268]
I'm trying to use Rclone as a library but running into some issues that I wanted to run by you guys.

I'm implementing Rclone into a long running process in such a way that the Rclone config might change while the process is running. I'm trying to pick up changes of the config file in order to always display the latest remotes using `config.FileSections()`. However after it cached the config it will use the cache, even if the underlying config file changes (by manually editing the file or using `rclone config`)

My first instinct was to just call `LoadConfig()` before `FileSections()` but I noticed some other methods being called in `LoadConfig()` and I therefor was not sure if it's safe to call `LoadConfig()` multiple times. Is it safe to do so? And if not could you recommend an other way to ensure I always have the most up to date data from the config file?

**Comment by ncw** [comment]
Calling `config.FileGetFresh` will ensure the config file is up to date.

**Comment by maran** [comment]
Yes but it will only return the specific key and value. It won't update the global defined config so if you call` FileSections()` after you will still read a stale config file.

**Comment by ncw** [comment]
Do you want to send a PR for a `FileRefresh()` call?

**Comment by maran** [comment]
Thanks! I will :)
