### ISSUE TITLE
Flags missing on rclone.org?

### ISSUE THREAD

**Issue by saikpr** [ncw/rclone#3273]
Hi, not sure if this is a CDN issue or recent change but "Options inherited from parent commands" section is missing 

Old documentation : https://web.archive.org/web/20190204094858/https://rclone.org/commands/rclone_about/
and new : https://rclone.org/commands/rclone_about/

**Comment by gary-kim** [comment]
There was a change during the `v1.48.0` development process that removed it.
f544234e2638968c7247de65c1854be87c1e8002

**Comment by ncw** [comment]
I made this change deliberately as I thought the documentation was getting too difficult to read

There was some discussion of this in the forum.

I came up with a compromise

> How about as a compromise, I bring back the global flags which aren't backend specific? (except for the local flags which have short options like -l)
> 
> I think it is the proliferation of backend flags which makes it hard to read and they are all documented on the backend pages.

What do you think of that?

**Comment by saikpr** [comment]
Honestly as a programmer I am fan of big-old man pages, makes it easy to grep and search (take pytorch doc for example : https://pytorch.org/docs/stable/torch.html its approximately 87 pages of text on that one page)

But I can understand that it might easily scare people, so is completely justifiable.

If global flags are same across different commands, a quick fix might be to introduce a new page with global flags and add that under "SEE ALSO" section

**Comment by saikpr** [comment]
To be a bit more clear, I definitely agree that this is a welcoming change. It took me a bit of curve to understand that I don't (maybe even won't) care about 99% of those. 
I would love to still be able to grep or search on http doc. `man rclone | grep -B 5 "word"` gets a bit quirky because of all the examples, and thus I used to search on the web page.

Hope that makes more sense now?

**Comment by ncw** [comment]
I'll have a go at this and try a few things!

Note that you can search the command line flags with `rclone help flags <search_string>`, eg

```
$ rclone help flags max
Usage:
  rclone help flags [<regexp to match>] [flags]

Flags:
  -h, --help   help for flags

Global Flags:
      --max-age Duration          Only transfer files younger than this in s or suffix ms|s|m|h|d|w|M|y (default off)
      --max-backlog int           Maximum number of objects in sync or check backlog. (default 10000)
      --max-delete int            When synchronizing, limit the number of deletes (default -1)
      --max-depth int             If set limits the recursion depth to this. (default -1)
      --max-size SizeSuffix       Only transfer files smaller than this in k or suffix b|k|M|G (default off)
      --max-transfer SizeSuffix   Maximum size of data to transfer. (default off)
      --rc-max-header-bytes int   Maximum size of request header (default 4096)

Backend Flags:


Use "rclone [command] --help" for more information about a command.
Use "rclone help flags" for to see the global flags.
Use "rclone help backends" for a list of supported services.
```

**Comment by saikpr** [comment]
Thanks a lot for this, BTW I really like `rclone` made my life 100 times more easier.

**Comment by ncw** [comment]
I've had a go at fixing this.

On each command page I've added a link to a global flags page

https://tip.rclone.org/commands/rclone_size/

which links to

https://tip.rclone.org/flags/

Let me know what you think?

I'll release it to rclone.org in due course if everyone likes it!

**Comment by gary-kim** [comment]
Looks good. Remote specific flags can be seen on their page as well as the flags page and there is a single proper place to see a list of global flags. I like it.

**Comment by ncw** [comment]
I've put this live on rclone.org now :-)
