### ISSUE TITLE
Implement --compare-dest & --copy-dest from rsync

### ISSUE THREAD

**Issue by yparitcher** [ncw/rclone#3278]
#### What is your current rclone version (output from `rclone version`)?
```
rclone v1.48.0
- os/arch: linux/amd64
- go version: go1.12.5
```

#### What problem are you are trying to solve?

i would like to implement rsync's --compare-dest & --copy-dest flags to complement the existing --backup-dir to help with incremental backup strategies 

from the rsync man page:
```
--compare-dest=DIR
    This option instructs rsync to use DIR on the destination machine as an 
additional hierarchy to compare destination files against doing transfers 
(if the files are missing in the destination directory). If a file is found in 
DIR that is identical to the sender's file, the file will NOT be transferred 
to the destination directory. This is useful for creating a sparse backup of 
just files that have changed from an earlier backup. 

--copy-dest=DIR
    This option behaves like --compare-dest, but rsync will also copy unchanged 
files found in DIR to the destination directory using a local copy. This is useful 
for doing transfers to a new destination while leaving existing files intact, and 
then doing a flash-cutover when all files have been successfully transferred. 
```
#### How do you think rclone should be changed to solve that?

I would add the appropriate flags in fs/config/configflags/configflags.go & fs/config.go

then implement a check here in `NeedTransfer` on the compare dir to either return false or do a server side copy
https://github.com/ncw/rclone/blob/71a19a1972a7c1d85f966e199b1677379105834b/fs/operations/operations.go#L1399-L1406
add tests in fs/sync/sync_test.go & docs

please let me know if that is good and i will submit a pull request

**Comment by ncw** [comment]
Apologies for the delay in responding to this - I'm a bit behind!

I think this looks like a good feature of rsync - one I wasn't aware of.

Will review the Pull requests shortly.
