### ISSUE TITLE
Shutdown after finishing a command

### ISSUE THREAD

**Issue by ctrlnot** [ncw/rclone#3279]
Not sure if this appropriate to be implemented on rclone but it would be nice to have. I use windows and for now, I just set an automatic shutdown depending on the estimated finish time of the command running. If there's a better way to deal this, I'm willing to learn it. Thanks!

**Comment by ncw** [comment]
> Not sure if this appropriate to be implemented on rclone but it would be nice to have. I use windows and for now, I just set an automatic shutdown depending on the estimated finish time of the command running. If there's a better way to deal this, I'm willing to learn it. Thanks!

I think this should probably be the job of a batch script, so you put `rclone ...` in the batch script, followed by the command to shut your machine down which I think is `shutdown /s`
