### ISSUE TITLE
Google API errors (logs attached)

### ISSUE THREAD

**Issue by isaiah36** [ncw/rclone#328]
Hello,

I am reporting this because it may be of interest.  The first log reports the anomalous behaviour, and the strange responses from Google server.  The second log reports what has happened 2 days in a row after the initial error.  It appears new files are being transferred anyway, and the source files are on an SSD, so I am in rather less of a panic about it.

[rclone-error-log.txt](https://github.com/ncw/rclone/files/110022/rclone-error-log.txt)
[rclone-error-log-2.txt](https://github.com/ncw/rclone/files/110027/rclone-error-log-2.txt)

**Comment by ncw** [comment]
I've had a look at the logs.

There are a lot of 403 rate limit exceeded errors which are normal with google drive. Google throttle the rate of upload to about 2 files per second.

The ` Failed to copy: Post https://www.googleapis.com/upload/drive/v2/files?alt=json&uploadType=resumable: http: ContentLength=193 with Body length 0` are unusual.

Could your ISP be throttling those - killing the connections?  I know some ISPs do exactly that.

And the final thing I noticed is that there are lot of duplicates.  Sometimes people see one or two, but you have a lot more than that.  It makes me think maybe it is your ISP killing connections...

**Comment by isaiah36** [comment]
I think it's unlikely but I will check with the ISP.  We pay for a premium class of service, and this system is connected via ethernet cable.  The bit torrent client does not appear to be getting throttled.

Today's log is attached.  The duplicate file issue is the only one persisting.
[rclone-log-2016-01-30.txt](https://github.com/ncw/rclone/files/110950/rclone-log-2016-01-30.txt)

**Comment by ncw** [comment]
If you want to fix the dupes, then you can try the dedupe command in this beta.

http://pub.rclone.org/v1.26-51-g3101a7f%CE%B2/

### rclone dedupe remote:path ###

Interactively find duplicate files and offer to delete all but one or
rename them to be different. Only useful with Google Drive which can
have duplicate file names.

```
$ rclone dedupe drive:dupes
2016/01/31 14:13:11 Google drive root 'dupes': Looking for duplicates
two.txt: Found 3 duplicates
  1:       564374 bytes, 2016-01-31 14:07:22.159000000, md5sum 7594e7dc9fc28f727c42ee3e0749de81
  2:      1744073 bytes, 2016-01-31 14:07:12.490000000, md5sum 851957f7fb6f0bc4ce76be966d336802
  3:      6048320 bytes, 2016-01-31 14:07:02.111000000, md5sum 1eedaa9fe86fd4b8632e2ac549403b36
s) Skip and do nothing
k) Keep just one (choose which in next step)
r) Rename all to be different (by changing file.jpg to file-1.jpg)
s/k/r> r
two-1.txt: renamed from: two.txt
two-2.txt: renamed from: two.txt
two-3.txt: renamed from: two.txt
one.txt: Found 2 duplicates
  1:         6579 bytes, 2016-01-31 14:05:01.235000000, md5sum 2b76c776249409d925ae7ccd49aea59b
  2:         6579 bytes, 2016-01-31 12:50:30.318000000, md5sum 2b76c776249409d925ae7ccd49aea59b
s) Skip and do nothing
k) Keep just one (choose which in next step)
r) Rename all to be different (by changing file.jpg to file-1.jpg)
s/k/r> k
Enter the number of the file to keep> 2
one.txt: Deleted 1 extra copies
```

The result being

```
$ rclone lsl drive:dupes
   564374 2016-01-31 14:07:22.159000000 two-1.txt
  1744073 2016-01-31 14:07:12.490000000 two-2.txt
  6048320 2016-01-31 14:07:02.111000000 two-3.txt
     6579 2016-01-31 12:50:30.318000000 one.txt
```

**Comment by isaiah36** [comment]
The dedupe has been running for 3 hours now.  I have manually confirmed deletion of all the dupes I believe.  It is presumably scouring the rest of the drive.

**Comment by isaiah36** [comment]
Should the dedupe process be running for 6 hours?  The total data is less than 5 GB.

**Comment by isaiah36** [comment]
Sorry, I had not realized it was waiting for confirmations from me.  Process complete.

**Comment by isaiah36** [comment]
I am leaving the beta in place to run by crontab.

**Comment by ncw** [comment]
I'm going to close this now as we haven't made any progress on the ticket recently.  Please re-open if more info turns up!  Thanks Nick
