### ISSUE TITLE
Cannot connect to Azure storage emulator

### ISSUE THREAD

**Issue by Infarch** [ncw/rclone#3281]
It seems that **rclone** cannot be configured for connecting to **Azure storage emulator**.

I tried both the latest stable and beta releases (windows-amd64) with the same result.

The problem comes from different urls for accessing Azure cloud and local emulator. More information could be read here: https://docs.microsoft.com/en-us/azure/storage/common/storage-use-emulator.

So, because I need a non-standard URL, I'm trying to use endpoints. This is my config below:

```
[blob]
type = azureblob
account = devstoreaccount1
key = Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==
endpoint = http://127.0.0.1:10000/devstoreaccount1/ 
```
By the way **rclone** produces wrong URLs: `https://devstoreaccount1.http://127.0.0.1:10000/devstoreaccount1/...` instead of `http://127.0.0.1:10000/devstoreaccount1/...`.

See also a topic on **rclone** forum: https://forum.rclone.org/t/connecting-to-azure-emulator/10532

I think that **rclone**, in case of Azure storage, should either be able to either specify complete URLs instead of parts, or support emulators as an additional data source type (may be the best solution).

**Comment by ncw** [comment]
What do you think @sandeepkru ?

**Comment by sandeepkru** [comment]
I don't remember if had Emulator support with older SDK, but I do remember that when ported to new SDK, emulator testing was not done. However, it should be fairly easy to add, I'll take look on it and send out fix soon.

**Comment by sandeepkru** [comment]
Closing this since change is already merge, please let me know if there are any concerns.
