### ISSUE TITLE
rclone ls or lsf -R commands raised multiple requests to storage server？

### ISSUE THREAD

**Issue by nosaJ886** [ncw/rclone#3287]
rclone -R :  

rclone v1.45   
--os/arch: linux/amd64
--go version: go1.11.2

Server version:

Redhat enterprise Linux server 7.6 (Maipo)

Running command: 

rclone lsf --files-only -R ecs://....xxxxx..../

The remote storage is Dell ECS.

Problem: My application needs to run 30+ above commands in parallel and when these commands are running, the ECS storage server encounterd high latency issue and caused ECS hung.  

So the questions are: 
How the recursive listing works in rclone? 
How many requests would be sending to the storage server per command ? Won't be per request per command?  Any multi-threading happened in rclone when -R enabled?  
Any methods to avoid this?

Thanks...

**Comment by ncw** [comment]
What backend does `Dell ECS` use - the s3 backend?

If you upgrade to 1.48 you'll find `rclone lsf -R` will only use one call only (plus additional paged request) rather than one per directory.

> How the recursive listing works in rclone?

In 1.48 in by issuing a single list recursive command.  In 1.45 by issuing list commands per "directory"

> How many requests would be sending to the storage server per command ?

In 1.45 one per directory

> Won't be per request per command? Any multi-threading happened in rclone when -R enabled?

Rclone will use `--checkers` threads.  You can change that parameter to decrease the amount of concurrent work rclone does.

**Comment by nosaJ886** [comment]
> What backend does Dell ECS use - the s3 backend?

 Dell ECS  implements S3 protocal as well, so we also used rclone to connect ECS.

> If you upgrade to 1.48 you'll find rclone lsf -R will only use one call only (plus additional paged request) rather than one per directory. 

OK will try to upgrade to 1.48 

> Rclone will use --checkers threads. You can change that parameter to decrease the amount of concurrent work rclone does.

So how many checker are used by default, if I don't specify it.

**Comment by seonghobae** [comment]
> > Rclone will use --checkers threads. You can change that parameter to decrease the amount of concurrent work rclone does.
> 
> So how many checker are used by default, if I don't specify it.

Default is 8

**Comment by nosaJ886** [comment]
ok, thanks @ncw @seonghobae

**Comment by ncw** [comment]
No worries!  I'll close this now
