### ISSUE TITLE
can't create new azure blob remote with connection string

### ISSUE THREAD

**Issue by dtenenba** [ncw/rclone#3296]
#### What is the problem you are having with rclone?

There is no way to create an Azure Blob remote using a connection string and key.
In some cases (like mine) this is the only information we have about a given Azure storage container. 
Details:
https://forum.rclone.org/t/problem-creating-an-azureblob-remote/10610

#### What is your rclone version (output from `rclone version`)

```
rclone v1.47.0
- os/arch: darwin/amd64
- go version: go1.12.4
```

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

macOS 10.14.5, 64-bit

####  Which cloud storage system are you using? (eg Google Drive)

Azure Blob

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

rclone config

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

N/A.

**Comment by ncw** [comment]
@sandeepkru we lost the connection string configuration when we updated to the new SDK if I remember rightly.

Is it easy to put back?

If not then we should update the help when you configure a remote since it mentions connection strings and there is nowhere to enter one!

**Comment by dtenenba** [comment]
BTW, it turns out the account name is part of the connection string, so if during `rclone config` I fill int he account name and key fields, I end up with a working config. So maybe this is just an issue of documenting this procedure.

**Comment by sandeepkru** [comment]
Azure storage is deprecating connection string concept hence they did not support it in new SDks, based on the communication back then with them. We decided to remove connection string from rclone code and we do not have any config options for it https://github.com/ncw/rclone/blob/master/backend/azureblob/azureblob.go#L60. I'll update the help details to remove `Connection String` which is bug here and caused confusion. Thanks @dtenenba for pointing this out.

**Comment by ncw** [comment]
I think this is the confusing bit in the configurator

```
Storage Account Name (leave blank to use connection string or SAS URL)
Enter a string value. Press Enter for the default ("").
account> 
Storage Account Key (leave blank to use connection string or SAS URL)
Enter a string value. Press Enter for the default ("").
key> 
SAS URL for container level access only
(leave blank if using account/key or connection string)
Enter a string value. Press Enter for the default ("").
sas_url> 
```

**Comment by sandeepkru** [comment]
Agree, cleaning it up, just merged the emulator support change, will close this soon.

**Comment by sandeepkru** [comment]
Modified config help text to avoid confusion, changes are merge hence closing the issue.
