### ISSUE TITLE
Allow multiple files to be uploaded at the same time

### ISSUE THREAD

**Issue by ZacharyDuBois** [ncw/rclone#331]
In addition to my issue #310, it would be awesome to add the ability to upload X files at a time to speed up massive uploads.

**Comment by ncw** [comment]
Rclone already does that.  See the `--transfers` flag which is set to 4 by default.

**Comment by ZacharyDuBois** [comment]
Man, how did I miss that. My bad :) Keep up the awesome project! See if you can get it in the apt/brew/etc repos!
