### ISSUE TITLE
Speed Issues Transfering from the GDrive Folder to Local Drive V1.48

### ISSUE THREAD

**Issue by vaccarieli** [ncw/rclone#3313]
Hi it seems this version, has issues related to transfering files from cloud folde drive to my local drive ( PC ), this is the config I always use to do so,

rclone copy "Gdrive:hhh/folder/folder" "Z:\folder\folder" -P

rclone sync "Gdrive:hhh/folder/folder" "Z:\folder\folder" -P

NOTE: Only happens with this version 1.48. as I just went back to the 1.47. cuz it works just fine no delay, all good so far.

**Comment by ncw** [comment]
What sort of issues are you having?

Can you post a log with `-vv` of the issues?

**Comment by vaccarieli** [comment]
sorry to bother, was my mistake my bandwith.
