### ISSUE TITLE
Make: Build Fail

### ISSUE THREAD

**Issue by yparitcher** [ncw/rclone#3317]
#### What is the problem you are having with rclone?

when running make i get a go.mod: checksum mismatch.

this is an issue with the gobuffalo/packr dependency (resolved by updating) documented here: https://github.com/gobuffalo/packr/issues/213

this was introduced in #246
also #246 doubles the amount of dependencies in go.mod and go.sum for one extra library, was that expected?

#### What is your rclone version (output from `rclone version`)

master

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

linux 64bit

####  Which cloud storage system are you using? (eg Google Drive)

any

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

make

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

```
verifying github.com/gobuffalo/packr/v2@v2.4.0/go.mod: checksum mismatch
	downloaded: h1:ra341gygw9/61nSjAbfwcwh8IrYL4WmR4IsPkPBhQiY=
	go.sum:     h1:tj7r/7WvgPz0qgtdtKjlbAiGglcdbM02mq/Bv25LsOA=
```

**Comment by ncw** [comment]
> #### What is the problem you are having with rclone?
> when running make i get a go.mod: checksum mismatch.
> 
> this is an issue with the gobuffalo/packr dependency (resolved by updating) documented here: [gobuffalo/packr#213](https://github.com/gobuffalo/packr/issues/213)
> 
> this was introduced in #246
> also #246 doubles the amount of dependencies in go.mod and go.sum for one extra library, was that expected?

There isn't an issue #246 which one did you mean?

I'm interested in reducing the dependencies if we can!

> #### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
> ```
> verifying github.com/gobuffalo/packr/v2@v2.4.0/go.mod: checksum mismatch
> 	downloaded: h1:ra341gygw9/61nSjAbfwcwh8IrYL4WmR4IsPkPBhQiY=
> 	go.sum:     h1:tj7r/7WvgPz0qgtdtKjlbAiGglcdbM02mq/Bv25LsOA=
> ```

Ah, this is the real problem: https://github.com/gobuffalo/packr/issues/213#issuecomment-505620338

> Ok, the problem should be solved now. It appears that the v2.4.0 got shifted to a different commit somehow.
> 
> If you still get the problem, it's because Go is now caching the wrong commit.
> 
> $ (sudo) rm -rfv $GOPATH/pkg/mod/github.com/gobuffalo/packr
> Should clear it for you.
> 
> Sorry for the problems folks!

So it looks like the commit has been moved back so clearing the cache should fix it.

**Comment by ncw** [comment]
In fact I have no idea why gobuffalo is even in the go.mod

Given that rclone vendors its dependencies, there are no references to it anywhere in the code

```
$ git grep -l github.com/gobuffalo
go.mod
go.sum
```

I deleted go.sum and the vendor directory, ran `go mod tidy` and `go mod vendor` and I seem to have purged gobuffalo from the system.

I don't understand why `go mod tidy` didn't do that when I ran it a week or so ago as part of d61ba7ef78966b0903b623d18d258fbba923f712

In fact go modules is mostly a mystery to me!

I've pushed this to master and checked this builds with and without modules - can you confirm it is working for you?

**Comment by yparitcher** [comment]
it works now,
sorry I meant 2d0e9885bd78f23f0957f36a81b065afda2fc714 however on the github website it has a 246 next to it

**Comment by yparitcher** [comment]
I found https://github.com/golang/go/wiki/Modules helpful in explaining modules especially:
> By default, go commands like go build ignore the vendor directory when in module mode.
The -mod=vendor flag (e.g., go build -mod=vendor) instructs the go commands to use the main module's top-level vendor directory to satisfy dependencies. The go commands in this mode therefore ignore the dependency descriptions in go.mod and assume that the vendor directory holds the correct copies of dependencies. Note that only the main module's top-level vendor directory is used; vendor directories in other locations are still ignored.
Some people will want to routinely opt-in to vendoring by setting a GOFLAGS=-mod=vendor environment variable.

which is why by default (from go 1.11) make downloads all the modules instead of relying on the vendor folder, if you want to change this add `GOFLAGS=-mod=vendor ` to the makefile

also from the faq:

> Why does 'go mod tidy' record indirect and test dependencies in my 'go.mod'?
> 
> The modules system records precise dependency requirements in your go.mod. (For more details, see the go.mod concepts section above or the go.mod tip documentation).
> 
> go mod tidy updates your current go.mod to include the dependencies needed for tests in your module — if a test fails, we must know which dependencies were used in order to reproduce the failure.
> 
> go mod tidy also ensures your current go.mod reflects the dependency requirements for all possible combinations of OS, architecture, and build tags (as described here). In contrast, other commands like go build and go test only update go.mod to provide the packages imported by the requested packages under the current GOOS, GOARCH, and build tags (which is one reason go mod tidy might add requirements that were not added by go build or similar).
> 
> If a dependency of your module does not itself have a go.mod (e.g., because the dependency has not yet opted in to modules itself), or if its go.mod file is missing one or more of its dependencies (e.g., because the module author did not run go mod tidy), then the missing transitive dependencies will be added to your module's requirements, along with an // indirect comment to indicate that the dependency is not from a direct import within your module.
>
> Note that this also means that any missing test dependencies from your direct or indirect dependencies will also be recorded in your go.mod. (An example of when this is important: go test all runs the tests of all direct and indirect dependencies of your module, which is one way to validate that your current combination of versions work together. If a test fails in one of your dependencies when you run go test all, it is important to have a complete set of test dependency information recorded so that you have reproducible go test all behavior).
> 
> Another reason you might have // indirect dependencies in your go.mod file is if you have upgraded (or downgraded) one of your indirect dependencies beyond what is required by your direct dependencies, such as if you ran go get -u or go get foo@1.2.3. The go tooling needs a place to record those new versions, and it does so in your go.mod file (and it does not reach down into your dependencies to modify their go.mod files).
> 
> In general, the behaviors described above are part of how modules provide 100% reproducible builds and tests by recording precise dependency information.
> 
> If you are curious as to why a particular module is showing up in your go.mod, you can run go mod why -m <module> to answer that question. Other useful tools for inspecting requirements and versions include go mod graph and go list -m all

which is why `go get -u & go mod tidy` is not always the best.

**Comment by ncw** [comment]
> it works now,
> sorry I meant [2d0e988](https://github.com/ncw/rclone/commit/2d0e9885bd78f23f0957f36a81b065afda2fc714) however on the github website it has a 246 next to it

Thanks - don't think I reviewed that pull request well enough!

I think this was the root of the problem since I merged that after I last did `go mod tidy`.

Note that after I rebuilt the vendor directory there were no files added, removed or changed by it, so I think this was entirely a go.sum problem caused by that PR.

I'm attempting to have rclone buildable with and without modules.  Normally I build it without modules.

> which is why by default (from go 1.11) make downloads all the modules instead of relying on the vendor folder, if you want to change this add GOFLAGS=-mod=vendor to the makefile

I think that is fine if someone wants to use modules, or do you think I should change that so if someone invokes `make` not in GOPATH it uses the vendored modules?  However if they just invoke `go build` then they will get the existing behaviour which will make it inconsistent.

> which is why go get -u & go mod tidy is not always the best.

The procedure I use for updating the dependencies in in the Makefile.  I do this with `go mod` and vendor all the modules.

```makefile
# Update dependencies
update:
	GO111MODULE=on go get -u ./...
	GO111MODULE=on go mod tidy
	GO111MODULE=on go mod vendor
```

Do you think that is correct?

**Comment by yparitcher** [comment]
i am new to go, so am not a reliable source on the matter, but


> I'm attempting to have rclone buildable with and without modules. Normally I build it without modules.
> 
> > which is why by default (from go 1.11) make downloads all the modules instead of relying on the vendor folder, if you want to change this add GOFLAGS=-mod=vendor to the makefile
> 
> I think that is fine if someone wants to use modules, or do you think I should change that so if someone invokes `make` not in GOPATH it uses the vendored modules? However if they just invoke `go build` then they will get the existing behaviour which will make it inconsistent.

i think it is fine to have the makefile do either or by default, however whatever the default is should be tested by the CI also which would have caught this bug.
> 
> > which is why go get -u & go mod tidy is not always the best.
> 
> The procedure I use for updating the dependencies in in the Makefile. I do this with `go mod` and vendor all the modules.
> 
> ```makefile
> # Update dependencies
> update:
> 	GO111MODULE=on go get -u ./...
> 	GO111MODULE=on go mod tidy
> 	GO111MODULE=on go mod vendor
> ```
> 
> Do you think that is correct?

i was just quoting the wiki before, i really am not an expert and don't know, sorry

**Comment by ncw** [comment]
> i am new to go, so am not a reliable source on the matter, but

I think the problem is that we are all new to modules!

> i think it is fine to have the makefile do either or by default, however whatever the default is should be tested by the CI also which would have caught this bug.

Yes this occurred to me too!  I have added a with modules builder now dcaee0016a73b1759af2d75b9c56f4caad077275 which effectively does a `make` in a non modules environment.

**Comment by yparitcher** [comment]
perfect

> > i am new to go, so am not a reliable source on the matter, but
> 
> I think the problem is that we are all new to modules!
> 
> > i think it is fine to have the makefile do either or by default, however whatever the default is should be tested by the CI also which would have caught this bug.
> 
> Yes this occurred to me too! I have added a with modules builder now [dcaee00](https://github.com/ncw/rclone/commit/dcaee0016a73b1759af2d75b9c56f4caad077275) which effectively does a `make` in a non modules environment.

perfect
