### ISSUE TITLE
Notify error 403

### ISSUE THREAD

**Issue by alebupal** [ncw/rclone#3328]
Hello, when google exceeds the daily limit of 750 gb (error 403) rclone does not warn and stays in a loop trying to copy files.
It shows the googleapi error message (error 403) but it still works and does not stop or cancel.
Ideally, if you exceed the limit of googleapi (error 403) rclone should stop giving an output code other than 0.
Airexplorer (another drive account management program) when it exceeds the limit for directly, I suppose it can be done.

I leave a log of error 403:
[log.log](https://github.com/ncw/rclone/files/3361482/log.log)

I explained myself well?

Greetings and thank you!

**Comment by ncw** [comment]
I could make this error `userRateLimitExceeded` a fatal error so rclone stops the sync immediately.

> 2019/07/05 08:37:05 ERROR : test1.mkv: Failed to copy: googleapi: Error 403: User rate limit exceeded., userRateLimitExceeded

However this error can ocurr in other situations.  Google recommends exponential backoff and retry in their docs (which is what rclone does)

https://developers.google.com/drive/api/v3/handle-errors#403_user_rate_limit_exceeded

I wish google had a clearer error like `userQuotaExceeded` or something like that, so rclone would know for definite the 750GB limit was breached.

**Comment by alebupal** [comment]
> I could make this error `userRateLimitExceeded` a fatal error so rclone stops the sync immediately.
> 
> > 2019/07/05 08:37:05 ERROR : test1.mkv: Failed to copy: googleapi: Error 403: User rate limit exceeded., userRateLimitExceeded
> 
> However this error can ocurr in other situations. Google recommends exponential backoff and retry in their docs (which is what rclone does)
> 
> https://developers.google.com/drive/api/v3/handle-errors#403_user_rate_limit_exceeded
> 
> I wish google had a clearer error like `userQuotaExceeded` or something like that, so rclone would know for definite the 750GB limit was breached.

Hi, first of all thank you for answering, it is true that google is not clear on this.
But I see well that when rclone makes x attempts to copy a file, rclone stops and does not enter a loop.
Or allow the user the possibility to configure if it has to be stopped or not. Even choose the number of attempts allowed.

**Comment by ncw** [comment]
You can choose how many tries rclone does with `--low-level-retries` and `--retries`

**Comment by ncw** [comment]
If you use the `-vv` flag you'll see what rclone is doing.

**Comment by alebupal** [comment]
But the problem is that files of a few kb are copied until there is no more and he continues to try to transfer a large file leaving the error 403.
 For that reason I ask that with the 403 of an error and rclone stop.

 You could add a flag that is yes or no, that indicates whether you rclone for or keep trying infinitely.

**Comment by animosity22** [comment]
The problem is that the error "userRateLimitExceeded" can occur naturally if you want go over you API request per second and it can be going over your quota.

Changing it to a fatal error and stopping would be bad and break many other functions and is definitely not advisable to do that.

It's better to just limit your bandwidth or control it via other methods since it is a shared error.

**Comment by alebupal** [comment]
I understand what you say. For that reason I propose to create an optional flag that when drive returns x number of errors 403 stop rclone.

**Comment by animosity22** [comment]
When you tweak/tune though, getting 403s is pretty common as you try to maximize performance. I don't see much use as getting more errors isn't that much of a problem. 

You have other ways to stop rclone like max-transfers or using a bwlimit to ensure you don't hit daily quotas. It's not a good bang for the bucks effort imo.

**Comment by alebupal** [comment]
Ok, if this thread is not viable, it can be closed.
thanks and greetings to all!

**Comment by ivandeex** [comment]
Similar to #4872
