### ISSUE TITLE
rclone rc vfs/refresh unknown key "_async"

### ISSUE THREAD

**Issue by putty182** [ncw/rclone#3346]
#### Output of `rclone version`
rclone v1.48.0 linux/amd64 go1.12.6

#### Describe the issue

[rc#special-parameters](https://rclone.org/rc/#special-parameters) doco implies _async should work for all commands, but it doesn't seem to be 100% implemented for the command `vfs/refresh`.

````
bash-5.0# rclone rc vfs/refresh dir=folder recursive=true _async=true
{
        "jobid": 4
}

bash-5.0# rclone rc job/status jobid=4
{
        "duration": 0.000078449,
        "endTime": "2019-07-14T10:25:27.957123647Z",
        "error": "unknown key \"_async\"",
        "finished": true,
        "id": 4,
        "output": {},
        "startTime": "2019-07-14T10:25:27.957045227Z",
        "success": false
}
````

**Comment by buengese** [comment]
Should be fixed in the latest beta. No missing support just a small mistake when parsing parameters.
