### ISSUE TITLE
Config file encrypted by itself

### ISSUE THREAD

**Issue by agncr** [ncw/rclone#3352]
#### What is the problem you are having with rclone?
I'm installing rclone into a container with vagrant. 
- Fresh installation of Debian Stretch with Vagrant
- Run rclone install script: `curl https://rclone.org/install.sh | sudo bash`
- Create mount and config directory: `sudo mkdir -p /etc/rclone & /mnt/remote`
- Copy unencrypted rclone config to /etc/rclone: `sudo cp ~/rclone.conf /etc/rclone`
- Copy systemd service: `sudo cp ~/mount.service /etc/systemd/system/`
- Enable and stard the service
-> rclone config file gets encrypted

Although the file is unencrypted, i have the following entry in my service file: Environment="RCLONE_CONFIG_PASS=pass" (the file was encrypted in the past). If i delete this line from the service file, reinstall the vm, push my service and config file onto the machine again and start the service, it won't get encrypted. It stays unencrypted.

So somehow rclone encrypts my configuration file, when the environment variable RCLONE_CONFIG_PASS in the service file is set.

#### What is your rclone version (output from `rclone version`)
rclone v1.48.0
rclone v1.48.0-067-g0a1169e6-beta
(both tested)

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Debian Stretch 64 bit (inside Vagrant)

####  Which cloud storage system are you using? (eg Google Drive)
Google Drive

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
ExecStart=/usr/bin/rclone -vvvvvvvv mount \
        --allow-other \
        --config=/etc/rclone/rclone.conf \
        --log-file=/home/vagrant/rclone.log \
        team: /mnt/remote

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
2019/07/16 14:02:33 DEBUG : rclone: Version "v1.48.0" starting with parameters ["/usr/bin/rclone" "-vvvvvvvv" "mount" "--allow-other" "--config=/etc/rclone/rclone.conf" "--log-file=/home/vagrant/rclone.log" "team:" "/mnt/remote"]  
2019/07/16 14:02:33 DEBUG : Using RCLONE_CONFIG_PASS password.
2019/07/16 14:02:33 DEBUG : Using config file from "/etc/rclone/rclone.conf"
2019/07/16 14:02:33 DEBUG : Encrypted drive 'team:': Mounting on "/mnt/remote"
2019/07/16 14:02:33 DEBUG : drive_team: Loaded invalid token from config file - ignoring
2019/07/16 14:02:34 DEBUG : Keeping previous permissions for config file: -rw-r--r--
2019/07/16 14:02:34 DEBUG : drive_team: Saved new token in config file
2019/07/16 14:02:34 DEBUG : Adding path "vfs/forget" to remote control registry
2019/07/16 14:02:34 DEBUG : Adding path "vfs/refresh" to remote control registry
2019/07/16 14:02:34 DEBUG : Adding path "vfs/poll-interval" to remote control registry
2019/07/16 14:02:34 DEBUG : : Root:
2019/07/16 14:02:34 DEBUG : : >Root: node=/, err=<nil>
2019/07/16 14:03:34 DEBUG : Google drive root '': Checking for changes on remote

**Comment by animosity22** [comment]
Pretty sure that's by design:

https://github.com/ncw/rclone/issues/3127

If you set the variable, it'll encrypt it.

**Comment by agncr** [comment]
Ah, that makes sense. :+1:
