### ISSUE TITLE
1fichier: list error

### ISSUE THREAD

**Issue by kz0** [ncw/rclone#3359]
#### What is the problem you are having with rclone?
Listing dirs from 1fichier 

#### What is your rclone version (output from `rclone version`)
rclone v1.48.0-067-g0a1169e6-beta
- os/arch: linux/amd64
- go version: go1.12.7

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Linux 4.9.53-5.ph2-esx x86_64

####  Which cloud storage system are you using? (eg Google Drive)
1fichier

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone lsd 1fichier:

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
2019/07/19 21:54:56 DEBUG : rclone: Version "v1.48.0-067-g0a1169e6-beta" starting with parameters ["rclone" "lsd" "1fichier:" "-vv"]
2019/07/19 21:54:56 DEBUG : Using config file from "/root/.config/rclone/rclone.conf"
2019/07/19 21:54:57 ERROR : : error listing: couldn't list folders: json: cannot unmarshal number into Go struct field Folder.pass of type string
2019/07/19 21:54:57 Failed to lsd with 2 errors: last error was: couldn't list folders: json: cannot unmarshal number into Go struct field Folder.pass of type string

**Comment by buengese** [comment]
Should be fixed in the latest beta available [here](https://beta.rclone.org/) in few minutes.
