### ISSUE TITLE
Can't create symlinks inside an rclone mount

### ISSUE THREAD

**Issue by thekiefs** [ncw/rclone#3361]
#### What is the problem you are having with rclone?
I want to create a symlink inside an rclone mount linking to an outside directory. I then want that symlink followed and uploaded. Unfortunately I get an "I/O error" whenever I try to create a symlink inside the rclone mount directory.

#### What is your rclone version (output from `rclone version`)
rclone v1.48.0
- os/arch: android/arm64
- go version: go1.12.6

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Android

####  Which cloud storage system are you using? (eg Google Drive)
Google Drive

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
ln -s /data/media/0/test.txt /data/media/0/Drive/test.txt
ln: /data/media/0/Drive/test.txt: I/O error

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
N/A

Post here: https://forum.rclone.org/t/can-i-create-symlinks-or-hardlinks-shortcuts-inside-a-mount/9802

**Comment by animosity22** [comment]
That would be this issue:

https://github.com/ncw/rclone/issues/2975

**Comment by thekiefs** [comment]
Would that also include creating a symlink on a gdrive mount, and then having the drive mount follow that symlink and upload it?

**Comment by ncw** [comment]
> Would that also include creating a symlink on a gdrive mount, and then having the drive mount follow that symlink and upload it?

Yes, that would use the same mechanism as `--links` for storing symlinks and for making them work in rclone mount.

I'll close this since I think #2975 covers it.
