### ISSUE TITLE
Windows scheduler fails to sync

### ISSUE THREAD

**Issue by mrx23dot** [ncw/rclone#3364]
#### What is the problem you are having with rclone?
Starting rclone batch file from Win7 x64 scheduler fails, in the log it says:
2019/07/21 20:23:26 ERROR : Failed to start progress: windows terminal: initialization failed
Then rclone.exe just hangs in idle in the background.

using mode: run whether user logged in or not, Run with highest privs, **Hidden**

#### What is your rclone version (output from `rclone version`)
rclone v1.48.0 32bit

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Win7 x64

####  Which cloud storage system are you using? (eg Google Drive)
from local HDD to remote FTP

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone sync "D:\DRIVE" extFTP:/Volume_1/ --ignore-errors --log-level WARNING --progress --checkers 4  --transfers 4

works perfectly if I start this manually from a batch file

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
2019/07/21 20:23:26 ERROR : Failed to start progress: windows terminal: initialization failed
Then rclone.exe just hangs in idle in the background.

**Comment by ncw** [comment]
I think you'll need to remove `--progress` as rclone isn't running in a terminal.

**Comment by mrx23dot** [comment]
works, although it would be nice to have it tolerated

**Comment by buengese** [comment]
Could be done but there really is no point in using the progress flag when running without a terminal.
