### ISSUE TITLE
Upload big files with swift ?

### ISSUE THREAD

**Issue by Nico83500** [ncw/rclone#341]
Hi,
I'm using python Swift client but I would like to try rclone, both on Windows 7.
I have a hubic account and I'm using Hubic2SwiftGate. It works without problem with python Swift client and rclone but I have a problem with big files (larger than 10 GB) : rclone says Too Large Object.
I don't have this problem with python Swift client.
Is it possible to copy files bigger than 5 GB ?
I'm using this command line :
rclone.exe --swift-chunk-size 1073741824 copy "File to copy.ext" remote:"default/Dest folder"
Thank you !

**Comment by Nico83500** [comment]
Ok I was wrong, --swift-chunk-size option must be 1G instead of the value in bytes (1073741824). But both values seems to be equal, 2^30 = 1073741824

**Comment by ncw** [comment]
The value is in Kbytes if you don't supply a unit. You shouldn't need to use --swift-chunk-size at all though - the default should work just fine.
