### ISSUE TITLE
--dry-run creates folders  

### ISSUE THREAD

**Issue by mrrnlds** [ncw/rclone#342]
Hi,
Found some odd behavior regarding folders with Google drive:

rclone version: v1.27
system: Ubuntu 14.04.3 LTS x86_64

#### Issue 1: --dry-run created a folder 
The command `rclone --dry-run sync TestFolder/ gdrive:TestFolder`
created an empty `TestFolder` on my Google Drive. Here is the Drive Activity log:

```
You created an item in
rclone • 4:49 PM
Google Drive Folder
My Drive
Google Drive Folder
TestFolder
```

But since this was a `--dry-run`, I expected only a **report** that `TestFolder` would be created.

#### Issue 2: empty folders not deleted after sync
After properly creating `TestFolder` and its hierarchy on Drive with 
```
rclone sync TestFolder/ gdrive:TestFolder
```
my Drive Activity log shows creation of files and the subfolder `test folder 2` (as expected):
```
You created an item in
rclone • 5:02 PM
Google Drive Folder
TestFolder
Text
test.txt

You created an item in
rclone • 5:02 PM
Google Drive Folder
test folder 2
Text
test2.txt

You created an item in
rclone • 5:02 PM
Google Drive Folder
TestFolder
Google Drive Folder
test folder 2
```

But then I delete the contents of `TestFolder` on my local system:
```
cd TestFolder; rm -rf *
```
and resync with 
```
rclone sync TestFolder/ gdrive:TestFolder
```
I belive this should leave an empty `TestFolder` on my Drive, but the Activity log shows only:
```
You permanently deleted 2 items
rclone • 5:11 PM
Text
test2.txt
Text
test.txt
```
and leaves behind the folder `test folder 2` even though it was deleted locally.

If if do: `rclone -v ls gdrive:TestFolder` I get:
```
2016/02/06 17:26:39 Google drive root 'TestFolder': Modify window is 1ms
2016/02/06 17:26:39 Google drive root 'TestFolder': Reading test folder 2/
2016/02/06 17:26:39 Google drive root 'TestFolder': Finished reading test folder 2/
2016/02/06 17:26:39 Google drive root 'TestFolder': Finished reading 
```
so rclone is seeing the left-behind empty folder `test folder 2`; this is verified also with lsd:
```
rclone lsd gdrive:TestFolder
-1 2016-02-06 22:02:16        -1 test folder 2
````
But I expected rclone to delete the empty folder `test folder 2`

I encountered this while syncing a number of local folders after some local changes. 

Let me know if I am missing something... 

But thanks for a great tool; better than other options!

**Comment by ncw** [comment]
Issue 1 is a bug - thanks for pointing that out. 

Issue 2 is a known problem with rclone. Rclone doesn't really understand directories - see #100 

I may do a stop gap measure to get rclone to delete empty directories which would fix most of the problems.

**Comment by mrrnlds** [comment]
Thanks for the quick follow up!

Sorry I missed the earlier discussion on Issue 2, I'm a new user. A 'delete empty directories' step at the end of sync would be most welcome.

**Comment by ncw** [comment]
This also happens with swift so is likely a missing check in `operations.go`.

**Comment by ncw** [comment]
The fix for creating directories on `--dry-run` will be in the next release - thanks for reporting it.

Nick

**Comment by orange-buffalo** [comment]
@ncw Unfortunately, this is reproduced on 1.44. When running `move` with `--dry-run`, empty folders are created in Google Drive.

**Comment by ncw** [comment]
@orange-buffalo can you please make a [new issue on github](https://github.com/ncw/rclone/issues/new) about this with a sequence of commands to reproduce please - thanks :-)

**Comment by orange-buffalo** [comment]
@ncw, sure thing, created #2676. Thanks for your fast response!
