### ISSUE TITLE
Cannot upload files >10MB to Amazon Cloud

### ISSUE THREAD

**Issue by jkrinke** [ncw/rclone#343]
rclone 1.27 fails to upload any file larger than 10MB to Amazon Cloud.  It generates the following error message:
Failed to copy: HTTP code 400: "400 Bad Request", reponse body: {"message":"Cannot complete upload"}

**Comment by ncw** [comment]
It is working for me.

I suspect a temporary glitch at Amazon.

Can you post the output of the command with the `-v` flag if you are
still having a problem?  Also tell me which platform and whether there
is anything special about your Internet connection (eg a proxy).

```
$ rclone -v copy 100MB acd:100-mb-test
2016/02/07 20:08:56 acd: Saving new token in config file
2016/02/07 20:08:57 100-mb-test: Failed to read info: Node not found
2016/02/07 20:08:57 Amazon cloud drive root '100-mb-test': Modify window not supported
2016/02/07 20:08:57 Amazon cloud drive root '100-mb-test': Building file list
2016/02/07 20:08:57 Amazon cloud drive root '100-mb-test': Reading ""
2016/02/07 20:08:58 Amazon cloud drive root '100-mb-test': Finished reading ""
2016/02/07 20:08:58 Amazon cloud drive root '100-mb-test': Waiting for checks to finish
2016/02/07 20:08:58 Amazon cloud drive root '100-mb-test': Waiting for transfers to finish
2016/02/07 20:09:47 100MB: Copied (new)

$ rclone lsl acd:100-mb-test
104857600 2016-02-07 20:09:46.982000000 100MB
```

**Comment by jkrinke** [comment]
I have further investigated the issue. It actually has nothing to do with Amazon and it is not the write that fails.  Here is the situation that causes the failure:

The original file is on a NAS that is mounted via cifs. Reading a large file on the cifs share (>10MB) fails if done with rclone (and it is only rclone that cannot read the file):

$ rclone copy FAIL /tmp
2016/02/09 18:18:47 Local file system at /tmp: Building file list
2016/02/09 18:18:47 Local file system at /tmp: Waiting for checks to finish
2016/02/09 18:18:47 Local file system at /tmp: Waiting for transfers to finish
2016/02/09 18:18:49 FAIL: Failed to copy: read /afs/media/Pictures/2007/FAIL: input/output error
2016/02/09 18:18:49 Attempt 1/3 failed with 1 errors
...

**Comment by ncw** [comment]
That is interesting....

I presume you are using CIFS on a linux machine?

[This thread](https://bbs.archlinux.org/viewtopic.php?id=126328)  looks relevant maybe.

Just to be sure you can `cp` the file onto the linux machine?

**Comment by jkrinke** [comment]
Thanks for the hint with the thread.  It was not the problem mentioned in the thread, but it is due to a problem in the samba server of the NAS, where the server and the client negotiated too large rsize and wsize values.

So it is not a problem with rclone at all, it only appeared with rclone as no other tool reads files in chunks that large.

Thanks for the help!

**Comment by ncw** [comment]
Well done for finding the issue - a tricky one to track down.

I'll close this now we've come to the bottom of it.

Thanks

Nick
