### ISSUE TITLE
Unknown command delete

### ISSUE THREAD

**Issue by marshallmarshall** [ncw/rclone#344]
Documentation for v1.27 references two options for removing files, purge and delete, but when attempting to use delete get 'Unknown command "delete" '.

Purge removes the path and contents, whereas delete removes just the contents -- for my purposes delete is preferable, leaving a folder that I can still refer to and fill later.

Any plan to reinstate delete or remove it from the documentation?

**Comment by ncw** [comment]
Delete works for me with v1.27.  Can you post the command line you are trying?

**Comment by marshallmarshall** [comment]
Command line and response are as follows:
pi@raspberrypi:~ $ rclone delete gdrive:line_status
2016/02/07 15:57:16 Unknown command "delete"
Where gdrive is the configured remote, line_status is the folder I want to empty.
If instead I enter
    rclone purge gdrive:line_status
command executes without problem, removing line_status folder completely.

When I run "rclone help" there is no mention of delete as a subcommand. Also, it states that this is v1.26, though I downloaded 1.27.
System is Raspbian Jessie on a Raspberry Pi.  Downloaded zip for Linux ARM 32 bit from http://rclone.org/downloads/, followed installation instructions verbatim from http://rclone.org/install/.

Forgive me if I'm making a stupid mistake here, but there's nothing obvious that jumps out at me.

**Comment by ncw** [comment]
Sounds like you do have 1.26.I wonder if you got a cached version of the download page - I update it on every release. Can you try downloading rclone again?

**Comment by marshallmarshall** [comment]
Dowloaded again and delete is now present.
"rclone help" shows that it's v1.27 rather than previous 1.26.
All fixed, thanks.
