### ISSUE TITLE
Dropbox: modification times?

### ISSUE THREAD

**Issue by don311** [ncw/rclone#345]
I'm a relatively new user of rclone - apologies if this is a silly question, but I didn't see an answer in the searches I tried...

http://rclone.org/dropbox says:
> Dropbox doesn’t have the capability of storing modification times or MD5SUMs so syncs will effectively have the `--size-only` flag set.

What makes you believe that Dropbox doesn't store modification times?  My experience - with Dropbox's own sync program, on Linux - is that it does indeed store/preserve mod times, to a precision of 1 second on sync'd copies.  Is that metadata not available through the interface that rclone uses?

I'm using rclone v1.26 on Fedora 21 64-bit.  `rclone copy`  from a local file to Dropbox doesn't preserve mod time -- if it's a new file, the mod time is the time of the copy.  I assume that's due to the implied `--size-only` option..?

**Comment by ncw** [comment]
That statement should really say that Dropbox's public API doesn't allow the modification time to be set. They have a private API which does for their own syncer. 

Here us a thread on the Dropbox support forum

https://www.dropboxforum.com/hc/en-us/community/posts/202299459-API-v2-set-metadata-mtime

**Comment by don311** [comment]
Thanks for the clarification, ncw.  Sounds as though they're considering enhancing the API to allow it - here's hoping they do...

I do understand the point that file mod time isn't a generally robust way to detect whether files need to be sync'd, as it's independent of file content.  (From what I see in the man page, rclone normally does use mtime (and size) to detect changes, which is good enough for my current use case.  Unfortunately MD5SUMs aren't an option for Dropbox either, apparently.)  In any case, from a user standpoint, it would just be nice to have that metadata copied through.

**Comment by ncw** [comment]
Actually I think the v2 api does allow setting modification times - the `client_modified` attribute: [See upload docs](https://www.dropbox.com/developers/documentation/http/documentation#files-upload)

I haven't found way you can set them on an existing object though which rclone needs in an ideal world.

For normal operation (not with dropbox) rclone sets the mod time to be exactly the same as the local mod time which is quite a sensitive way of detecting whether files need syncing.  If rclone can't set the mod time it is still useful, but rclone can't currently use it as part of the sync.

I posted a [question on the dev forum](https://www.dropboxforum.com/hc/en-us/community/posts/204666633-Is-it-possible-to-set-client-modified-on-an-existing-file-in-v2-API-)...

The v2 api still doesn't return any form of checksum though.

**Comment by ncw** [comment]
I made a ticket #348 to remind me to think about how I can do sync on a remote which can't set the mod time on an existing object.  This would be useful for b2 also.

**Comment by khurshid-alam** [comment]
@ncw I can clearly modify client_modified timestamp when using their official python client. Even if dropbox server sets that we could use --modify-window 10s to force rclone to think that files are same.

At the moment sync simply doesn't work. For example,

`rclone sync -u --no-update-modtime -v rc Dropbox:/Public/rc`

This simply copies same files dropbox each time I run it. It say `replaced existing` but nothing changes on dropbox. Why?

**Comment by ncw** [comment]
@khurshid-alam can you make sure you are using [the latest beta](https://beta.rclone.org) which uses the dropbox v2 API?

**Comment by khurshid-alam** [comment]
I am already using it. 

rclone v1.37-121-gfe536f3fβ
- os/arch: linux/386
- go version: go1.9

**Comment by khurshid-alam** [comment]
@ncw Did beta version support dropbox modify time ? It may be related to #1662

**Comment by ncw** [comment]
@khurshid-alam what is happening is that `-u` is telling rclone to always transfer the file as it is newer.  However dropbox has a bug which means when you update a file and **only** change the client_modified, it doesn't actually change the client modified :-(  Dropbox assumes the file is the same I think.

Normally rclone works around this by deleting the file first when it wants to update the modification time.

So either do the sync without `-u --no-update-modtime` or delete the offending file first.

**Comment by khurshid-alam** [comment]
@ncw 

From doc 

> -u, --update                            Skip files that are newer on the destination.

So why does it tell rclone to always transfer files which are newer? It's not clear to me


So I guess  I should use `-c --no-update-modtime` ?

**Comment by ncw** [comment]
@khurshid-alam 

`-u` is most useful for remotes which don't store modtimes.

Your proposed `-c --no-update-modtime` looks OK I think.

**Comment by khurshid-alam** [comment]
@ncw 
Ok. with` -c` it works but I still want it to be compare with modification time. Because with '-u' it doesn't overwrite new files on destination. How do I skip new files on destination without it?


>However dropbox has a bug which means when you update a file and only change the client_modified, it doesn't actually change the client modified

Now that I checked it fails to set. the `client modified`. :disappointed: 

>Normally rclone works around this by deleting the file first when it wants to update the modification time.

This workaround doesn't work for me. Now I am only using

`rclone sync -u -v rc Dropbox:/Public/rc`

Rclone should delete the file first (if size is the same but mod time is different) and then copy/sync it. No?
