### ISSUE TITLE
Implement a move command

### ISSUE THREAD

**Issue by ChrisSLT** [ncw/rclone#35]
Part of keeping things in sync is moving files from one place to another via Drive.  Could you implement a command that moves all files from one place to another.  Basically, it copies them and then after verifies successful copy on receiving end, deletes on source end?

**Comment by ncw** [comment]
Nice idea - thanks.

I'm working on server side copies at the moment which this would fit in nicely with.

**Comment by ncw** [comment]
Tech design:
  * make new optional interfaces `Mover` and `DirMover`
  * make a new rclone command "move"
    * This will attempt to use `DirMover` if available
    * if not it will attempt to use `Mover` on each file
    * if that doesn't work it will copy then delete the source
      * copy will use `Copier` interface if available

FS
  * Drive: can implement `Mover` and `DirMover` this using [this api](https://developers.google.com/drive/v2/reference/files/patch)

See also #99

**Comment by ncw** [comment]
@ChrisSLT thanks for the feature request!  Let me know how you get on and open a new ticket if you find issues.

I've factored the server side move stuff out of this to #115

**Comment by ChrisSLT** [comment]
Terrific!

On Fri, Aug 28, 2015 at 5:59 AM, Nick Craig-Wood <notifications@github.com>
wrote:

> @ChrisSLT <https://github.com/ChrisSLT> thanks for the feature request!
> Let me know how you get on and open a new ticket if you find issues.
>
> I've factored the server side move stuff out of this to #115
> <https://github.com/ncw/rclone/issues/115>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ncw/rclone/issues/35#issuecomment-135724256>.
>



-- 
347.708.6549
