### ISSUE TITLE
how to build a static binary

### ISSUE THREAD

**Issue by harupong** [ncw/rclone#351]
Is there a preferred/recommended way to do the static build for rclone?

I'm trying to run rclone on Alpine Linux, which btw is the popluar distro for Docker container, but I get the following error:

    /bin/sh: rclone: not found

After some googling, I found [golang-alpine - Build golang binaries for alpine linux](http://www.blang.io/posts/2015-04_golang-alpine-build-golang-binaries-for-alpine-linux/) and tried the following to do the **static build**:

    go get -d github.com/ncw/rclone
    cd $GOPATH/src/github.com/ncw/rclone
    CGO_ENABLED=0 go build -a -installsuffix cgo
    ldd rclone # => "not a dynamic executable"

I was able to run the generated binary on Alpine Linux, but still wondering if this is a preferred/recommended way to build rclone statically.

My environment is as follows:

```
$ go version
go version go1.5.3 linux/amd64
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.3 LTS
Release:        14.04
Codename:       trusty
$ uname -a
Linux ip-172-31-24-97 3.13.0-74-generic #118-Ubuntu SMP Thu Dec 17 22:52:10 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by ncw** [comment]
Note that go binaries as compiled in the default manner are nearly static.  They rely on the system resolver and not a lot else.

What you've written looks like a good way of building completely static binary.

Note also that the binaries I release on the downloads page are all static, except for the amd64 one for some reason (probably because that is my build platform).

**Comment by harupong** [comment]
Thanks for the confirmation and clarification!! I'm really new to Go, and your advice helps me a lot.

**Comment by pataquets** [comment]
@harupong : FYI, a Dockerfile has been added in #3459.
