### ISSUE TITLE
S3 Storage Type

### ISSUE THREAD

**Issue by dolabriform** [ncw/rclone#352]
Hi Nick
I'm guessing this is a feature request, I can't see a way at the moment to specify the storage type for S3?

I'd like to be able to specify S3 IA, or even Reduced Redundancy to reduce the costs of storing the data.

Thanks

David

**Comment by ncw** [comment]
Good idea!

This would involve setting `x-amz-storage-class: REDUCED_REDUNDANCY` at the time the object was uploaded.

It looks like this would be supported by the aws sdk

```go
api.go: // @enum ObjectStorageClass
api.go: ObjectStorageClassStandard = "STANDARD"
api.go: // @enum ObjectStorageClass
api.go: ObjectStorageClassReducedRedundancy = "REDUCED_REDUNDANCY"
api.go: // @enum ObjectStorageClass
api.go: ObjectStorageClassGlacier = "GLACIER"
api.go: // @enum ObjectVersionStorageClass
api.go: ObjectVersionStorageClassStandard = "STANDARD"
api.go: // @enum StorageClass
api.go: StorageClassStandard = "STANDARD"
api.go: // @enum StorageClass
api.go: StorageClassReducedRedundancy = "REDUCED_REDUNDANCY"
api.go: // @enum StorageClass
api.go: StorageClassStandardIa = "STANDARD_IA"
api.go: // @enum TransitionStorageClass
api.go: TransitionStorageClassGlacier = "GLACIER"
api.go: // @enum TransitionStorageClass
api.go: TransitionStorageClassStandardIa = "STANDARD_IA"
```

This could be made as either a command like flag `--s3-storage-class` or as a config file option. I'd probably favour the former.

**Comment by dolabriform** [comment]
Thanks for responding so quickly.
I agree, it should be a command line flag.

**Comment by bruno222** [comment]
Hello guys!

This feature is already implemented or it is still on TO-DO list? I didn't find any info on Documentation.

STANDARD_IA is half price of the default STANDARD...

Thanks!

**Comment by mdeboer** [comment]
+1 on this one. I would like to see it implemented soon, saves a ton of money!

**Comment by ncw** [comment]
I'll try to get it done soon.  Or someone could send a pull request?

**Comment by askot** [comment]
Hi, this PR https://github.com/ncw/rclone/pull/672 implements setting storage class for s3 uploads.

**Comment by ncw** [comment]
I'm away at the moment. Will review next week :-)

**Comment by ncw** [comment]
This has been done in #672 

Here is a beta to try: http://pub.rclone.org/v1.33-22-g7227a26%CE%B2/
