### ISSUE TITLE
Failed to copy: Object Corrupted on gzipped files at rackspace

### ISSUE THREAD

**Issue by wouterv** [ncw/rclone#353]
* rclone v1.27
* Ubuntu 14.04.2 LTS (GNU/Linux 3.13.0-43-generic x86_64)
* Command trying to run: ./rclone -v copy rackspace:bdb_test_abacus.nl_blobs /tmp/blobs

When running, files that we compressed with gzip arent copied, but reported as corrupted:

`
2016/02/14 08:36:24 8ebfaecd-e29e-49f4-baae-1e10039f0d3f_print_multiple.xml: Failed to copy: Object Corrupted
`
On rackspace side, we added the header: Content-Encoding: gzip, but we leave the content-type to the original file (for example: text/plain). This way we can use rackspace side compression which all browsers understand.

For non-gzipped files everything works file.

**Comment by wouterv** [comment]
Here's an example with header dump:

```
2016/02/14 08:59:31 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2016/02/14 08:59:31 b6fae2b1-5c8c-463a-a1aa-2e7e60eb9374_null: Failed to copy: Object Corrupted
2016/02/14 08:59:31 b6fae2b1-5c8c-463a-a1aa-2e7e60eb9374_null: Removing failed copy
2016/02/14 08:59:31 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2016/02/14 08:59:31 HTTP RESPONSE
2016/02/14 08:59:31 HTTP/1.1 200 OK
Content-Length: 357
Accept-Ranges: bytes
Content-Encoding: gzip
Content-Type: text/xml
Date: Sun, 14 Feb 2016 07:59:31 GMT
Etag: cbf0434915d671ac594b8fefca13f812
Last-Modified: Sat, 13 Feb 2016 05:02:13 GMT
X-Timestamp: 1455339732.71171
X-Trans-Id: tx1d7bcb93680f4d84a8a9c-0056c033e3lon3
```

**Comment by ncw** [comment]
Can you tell me how to reproduce the problem?

I tried this to my rackspace cloudfiles account

```
$ rclone -v copy . rackspace:gzs
2016/02/14 16:52:32 Swift container gzs: Modify window is 1ns
2016/02/14 16:52:35 Swift container gzs: Building file list
2016/02/14 16:52:35 Swift container gzs: Waiting for checks to finish
2016/02/14 16:52:35 Swift container gzs: Waiting for transfers to finish
2016/02/14 16:52:37 file.gz: Copied (new)
```

But it didn't produce the error.

You said above

> On rackspace side, we added the header: Content-Encoding: gzip, but we leave the content-type to the original file (for example: text/plain).

How did you do that?

What I suspect is happending is that rclone is comparing the md5sum of the gzipped file locally, with the md5sum of the ungzipped data - since they differ rclone is deleting the file.

**Comment by wouterv** [comment]
You should be able to reproduce it like this:

- Create or pick a txt file with some content
- Gzip it
- Remove the .gz extenstion (soo it again has filename ending with .txt)
- Upload to rackspace
- Add Content-Enconding: gzip header

So:
```
$ echo 'bla bla' > foo.txt
$ gzip foo.txt 
$ mv foo.txt.gz foo.txt
```
Upload to rackspace, add the Content-Encodig: gzip header
Try to copy:
```
$ ./rclone copy rkspace:test /tmp/foo
$ ./rclone copy rkspace:test /tmp/bar
2016/02/14 18:26:17 Local file system at /tmp/bar: Building file list
2016/02/14 18:26:17 Local file system at /tmp/bar: Waiting for checks to finish
2016/02/14 18:26:17 Local file system at /tmp/bar: Waiting for transfers to finish
2016/02/14 18:26:17 foo.txt: Failed to copy: Object Corrupted
2016/02/14 18:26:17 Attempt 1/3 failed with 1 errors
2016/02/14 18:26:17 Local file system at /tmp/bar: Building file list
2016/02/14 18:26:17 Local file system at /tmp/bar: Waiting for checks to finish
2016/02/14 18:26:17 Local file system at /tmp/bar: Waiting for transfers to finish
2016/02/14 18:26:17 foo.txt: Failed to copy: Object Corrupted
2016/02/14 18:26:17 Attempt 2/3 failed with 1 errors
2016/02/14 18:26:17 Local file system at /tmp/bar: Building file list
2016/02/14 18:26:18 Local file system at /tmp/bar: Waiting for checks to finish
2016/02/14 18:26:18 Local file system at /tmp/bar: Waiting for transfers to finish
2016/02/14 18:26:18 foo.txt: Failed to copy: Object Corrupted
2016/02/14 18:26:18 Attempt 3/3 failed with 1 errors

Transferred:           24 Bytes (   0.03 kByte/s)
Errors:                 1
Checks:                 0
Transferred:            3
Elapsed time:       700ms
```

**Comment by ncw** [comment]
How do you add the `Content-Encoding: gzip` header?  I can't replicate the problem until I can figure that out!

I see what is happening though...  rclone is obeying the `Content-Encoding: gzip` header and decompressing the file.  This file doesn't match the md5sum of what was uploaded - hence the corrupted error.

Removing the default `Accept-Encoding: gzip` that golang uses is easy enough, but that would likely affect performance for other uses (eg directory listings).

I put a binary [here](http://pub.rclone.org/rclone-no-gzip/rclone) for you to try.

**Comment by wouterv** [comment]
The fix works, thanks!

To set the header, use the settings next to the file like so:

![1 screenshot-edit-headers](https://cloud.githubusercontent.com/assets/616997/13035866/c48282fe-d359-11e5-9bee-dd176c4c360c.png)

and select the Content-Encoding, fill in gzip and click the plus icon:
![2 screenshot-add-header](https://cloud.githubusercontent.com/assets/616997/13035869/d6d97336-d359-11e5-9728-2e5909a2a6c3.png)

**Comment by ncw** [comment]
Thanks for testing that out and the explanation.

I think what I'll do is add an option something like `--no-gzip-encoding` to turn off the default `Accept-Encoding: gzip` which should fix your problem, and won't affect other users.

**Comment by wouterv** [comment]
Thank you!

**Comment by ncw** [comment]
This is done now - please find it in the v1.28 release.

-- Nick

**Comment by wouterv** [comment]
Thanks. Works like a charm.

**Comment by tat** [comment]
FYI AWS CloudTrail files (*.json.gz) also expose the same issue, i.e. sync doesn't work without the --no-gzip-encoding option.   

To reproduce just enable cloudtrail and try to sync the AWS generated files.

Great tool anyway, thanks :)

**Comment by mmilitzer** [comment]
I have the same problem than the original poster and the "--no-gzip-encoding" option is not really a complete solution. 

I'm syncing two swift containers with rclone and some of the files in the source container are compressed and have the "Content-Encoding" meta-data set to "gzip". The "--no-gzip-encoding" option makes the hard errors ("Failed to copy: Object Corrupted") disappear and so data is synced then but the problem is that the "Content-Encoding" meta-data is not preserved for the destination object.

So after sync, I have a gzip compressed file in the destination container that is not marked as gzip compressed (there's no "Content-Encoding: gzip" header on the destination object). Therefore, downloading the synced object from the destination fails (or rather, you get a still compressed, binary body with "Content-Type: text/xml").

Ideally, rclone should also copy the object's meta-data from source to destination so to preserve the "Content-Encoding: gzip" header.
