### ISSUE TITLE
b2: when using a subdir does a metadata read for every file when listing

### ISSUE THREAD

**Issue by padelt** [ncw/rclone#356]
So I tried `rclone` against a file tree with ~130.000 files in ~3.300 directories, totaling ~720GiB.

```
rclone copy --dump-headers --dump-filters --dump-bodies --log-file ~/rclone.log --dry-run --size-only --verbose --ignore-existing /home/pa/some/dir b2target:bucketname/targetdir/
```
Soon after, Backblaze notified me that my API call limit was about to be reached.
Turns out, `rclone` seems to request the remote filenames file by file instead of using the upper limit of 1000 files per API request. The log looks like an endless stream of this:
```
2016/02/15 13:14:58 HTTP REQUEST
2016/02/15 13:14:58 POST /b2api/v1/b2_list_file_names HTTP/1.1
Host: api001.backblaze.com
User-Agent: rclone/v1.27
...

{"bucketId":"5xxxc9baxxxxxxx95dxxxc12","startFileName":"some/path/to/one/file.txt","maxFileCount":1}
```
Note the `maxFileCount` is 1 but should be much larger.

I tried to locate the problem in the code but I can't find why `MaxFileCount` should be one here:
https://github.com/ncw/rclone/blob/master/b2/b2.go#L280

Any hints?

**Comment by ncw** [comment]
This will be rclone doing metadata reads in `readMetaData` - it does these size 1 lists to find the ID of a file given a file name.

During a copy the files should be read with the list in big chunks (of 1000).  You can see this working if you do `rclone --dump-bodies ls b2:bucket`.  

If the object didn't come from a directory read then rclone has to do a metadata read to read the ID and hence the modtime / sha1.

I'm having trouble working out how in the normal course of operations `readMetaData` should ever get called!

If you do a `--size-only` sync then it shouldn't read the sha1 or the modtime so shouldn't need to do a metadata read, so I don't understand your result.

What was the exact command line that returned those size 1 directory reads?

(I tried the command line you posted but I didn't get any metadata reads.)

Thanks

Nick

**Comment by padelt** [comment]
In the meantime I suspected that the root cause would be a file tree that was not uploaded initially by `rclone` but by the b2 command line tool (thus maybe missing some extra metadata or something like that).
So I generated a file tree with 60 files in 3 subdirectories in total and executed:
```
rclone copy --dump-headers --dump-filters --dump-bodies --log-file ./rclone.log --dry-run --size-only --verbose --ignore-existing . b2pabilder:b2test20160218/somedir/
```
First I ran it without `--dry-run`, checked that the files are actually visible in the B2 backend and then ran the commandline a second time (as above). The log of that second run is available at
https://philipp.adelt.net/temp/rclone.log.cleaned
Just search for "/b2api/v1/b2_list_file_names" and marvel at the magnificence of 63 such requests to check a filetree of 60 files.

Also, the order is strange:

1. Authorize
1. List buckets (why??)
1. List files one by one (<-- PROBLEM)
1. Create bucket (what the heck??)
1. List all files in one go (as expected!)
1. Skipping everything as all is there.

HTH to find the root cause. As a side note, I find the behaviour rather irritating. Listing buckets is unneeded and trying to (re)create the bucket without being asked to by the user is unexpected at the very least.

**Comment by ncw** [comment]
After some effort I've managed to reproduce this! Thanks for helping me pin it down.

It turns out that the problem is to do with the `/somedir/` - if you just use a bucket `b2pabilder:b2test20160218` then everything will work as expected.

When I've fixed the problem I'll post a beta here for you to try.

And for the answer to your questions

> Authorize
> List buckets (why??)

The reason why rclone does list buckets is to get the ID of the bucket given the name.  There isn't an API call to do that (if you can find one I'd be grateful!).

> List files one by one (<-- PROBLEM)
> Create bucket (what the heck??)

rclone creates the destination bucket when you are about to write to it. (It also does when doing `--dry-run` see #342 which will get fixed shortly!)

It is easier to try to create the bucket than to check it exists.

> List all files in one go (as expected!)
> Skipping everything as all is there.

**Comment by ncw** [comment]
I've fixed this now. Turned out to be a stupid problem in the read metadata function!

Here is a beta for you to try - please re-open the ticket if it doesn't work as expected!

http://pub.rclone.org/v1.27-18-g85a0f25%CE%B2/

Thanks

Nick

**Comment by padelt** [comment]
I am happy to confirm that no excessive calls are made anymore. Thanks!!! :-)

**Comment by ncw** [comment]
Thanks for testing it :-)
