### ISSUE TITLE
rclone not returning expected error code on Windows

### ISSUE THREAD

**Issue by jackools** [ncw/rclone#357]
I run a startup script on windows 7 ultimate 32-bit to backup some documents to dropbox automatically as soon as windows starts. My script checks the exit code generated by rclone and shows error message if it is not 0. The problem is when there is no internet connection rclone exits with exit code of 0 !
rclone tries 3 times to connect to dropbox and ends with error each time. But at the end it shows no errors !

![13_2016-02-12_141544](https://cloud.githubusercontent.com/assets/536803/13076727/3ab79c5e-d4ac-11e5-8a3c-b88f861a67fa.jpg)

**Comment by ncw** [comment]
Could you try this again with `echo %ERRORLEVEL%` after rclone has run?

As you can see when I try it in my Windows 7 VM, disabling networking with Virtualbox, I get the correct error level.

Thanks

Nick

![rclone-error-return](https://cloud.githubusercontent.com/assets/536803/13076801/c9d2046a-d4ac-11e5-8171-7085165e660f.png)

**Comment by klauspost** [comment]
@jackools - did Nick's proposal help you?

**Comment by jackools** [comment]
Yes. I found the problem. There was an error in my script which caused errorlevel for rclone to be always 0.
I added setlocal enabledelayedexpansion to the start of my script and the problem is solved.
This had nothing to do with rclone exit code and was a windows CMD problem.
Cheers.
