### ISSUE TITLE
Using rclone as a library

### ISSUE THREAD

**Issue by netbrain** [ncw/rclone#361]
Hi i'm looking for some pointers on how to use rclone as a library for another application. Is it even possible? Or would you not recommend it? 

I've tried looking at some of the code, but i haven't had much success. I'm guessing that somehow I have to configure a Fs object before using it. What would be the proper way to create a Fs object thats properly initialized for usage?

Thank you for your time.

**Comment by ncw** [comment]
It depends on exactly how dis-entangled you want it from rclone itself.

Provided you don't mind using the rclone config file, and its flags, then it is quite easy...

Create your fs using `f, err := fs.NewFs(remote)` where `remote` is the remote path you'd normally use in rclone.

See what an Fs object can do by looking in `fs/fs.go`.

See the main rclone.go file and you'll see that you don't need a lot of code to get going.

We don't guarantee any stable interfaces for rclone though.

**Comment by netbrain** [comment]
Thank you! decided to go with a native library instead.

**Comment by ianvonseggern1** [comment]
Hello, I'm also curious about using rclone as a golang library. To that end I have ".config/rclone/rclone.conf" in the users home directory. It seems I need to do something to load these before I can call `f, err := fs.NewFs(remote)` though. What do I need to call to load the config file? (I did enough digging to realize `fs.Registry` is empty. I'm just not sure what the best way to populate it with the contents of the rclone.conf file is?). Thanks!!

**Comment by ncw** [comment]
@ianvonseggern1 It is my aim that the rclone backends should be re-usable easily in other go code.  We took a significant step in that direction recently with the backend config re-org.

However if you don't mind bringing along rclone's config machinery then it shouldn't be too tricky.

Here is a very simple program to list the root of a backend called `drive:`

Note you need to `_` import the backends you are using.

```golang
package main

import (
	"fmt"
	"log"

	_ "github.com/ncw/rclone/backend/drive"
	"github.com/ncw/rclone/fs"
)

func main() {
	f, err := fs.NewFs("drive:")
	if err != nil {
		log.Fatal(err)
	}
	entries, err := f.List("")
	if err != nil {
		log.Fatal(err)
	}
	fmt.Println(entries)
}
```

**Comment by ianvonseggern1** [comment]
Awesome, worked like a charm. Thank you!!

**Comment by chaoqing** [comment]
With the nice os filesystem compatible interface provide by afero package, I created a wrapper for rclone: https://github.com/chaoqing/afero/blob/e47db790683a213a35daa9d222a611cda5452204/rclonefs/bind_test.go#L26

I also implemented a bind filesystem works very much like Linux mount but inside golang context, which means no Root permission needed. See https://github.com/chaoqing/afero/blob/e47db790683a213a35daa9d222a611cda5452204/rclonefs/bind_test.go#L40

**Comment by liningpan** [comment]
For anyone who wants to use rclone as a library, you need to call `configfile.Install()` before `fs.NewFs`. Otherwise you will get an error `didn't find section in config file`, even though rclone knows where to find the config file.

```go
import "github.com/rclone/rclone/fs/config/configfile"

...
configfile.Install()
f, err := fs.NewFs("drive:")
...

```

**Comment by vedantroy** [comment]
Is this still possible? It seems like the APIs have changed, s.t we need to pass in a `Context?

**Comment by ncw** [comment]
@vedantroy the internal API of rclone isn't considered to be stable.

However we have [librclone](https://pkg.go.dev/github.com/rclone/rclone/librclone) now which gives you in memory access to the rc server which can be considered stable;

**Comment by 7qqq** [comment]
T

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by xu-chen-313** [comment]
Recently, I was looking at the native library of rclone1.62.2, but it is difficult for a novice Xiaobai to understand. I hope there is a demo provided, so it is easy to start.

**Comment by ncw** [comment]
Here is a very simple example of how to use `librclone`


```go
package main

import (
	"log"
	"time"

	"github.com/rclone/rclone/librclone/librclone"

	_ "github.com/rclone/rclone/backend/all"   // import all backends
	_ "github.com/rclone/rclone/fs/operations" // import operations/* rc commands
	_ "github.com/rclone/rclone/fs/sync"       // import sync/*
)

func main() {
	librclone.Initialize()
	defer librclone.Finalize()

	out, status := librclone.RPC("core/bwlimit", "{\"rate\": \"1M\"}")
	log.Println(status)
	log.Println(out)

	out, status = librclone.RPC("operations/copyfile", `{"dstFs":"/tmp","dstRemote":"1G.copy","srcFs":"/tmp","srcRemote":"1G", "_async": true}`)
	log.Println(status)
	log.Println(out)

	for {
		time.Sleep(time.Second)
		out, status := librclone.RPC("core/stats", "")
		log.Println(status)
		log.Println(out)
	}
}
```

**Comment by xu-chen-313** [comment]
Is there no need to use configuration files here?

**Comment by ncw** [comment]
@xu-chen-313 you can use configuration files or you can create [on the fly remotes](https://rclone.org/docs/#connection-strings) - up to you.

**Comment by xu-chen-313** [comment]
@ncw 
I want to create an Alias remote object, the following is my code, but the result is that both remote and err are nil.I guess there is a problem with the configuration of keyvalues, but there is no template for me to refer to.

func CreateConnection() error {
	// 创建上下文对象
	ctx := context.Background()

	keyValues := rc.Params{
		"access_key_id":     AccEssKeyId,
		"secret_access_key": accessKeySecret,
		"endpoint":          insideChina,
		"provider":          "Alibaba",
		"acl":               "private",
		"region":            "South China 1",
	}

	// 创建一个新配置
	remote, err := config.CreateRemote(ctx, "aliyun", "s3", keyValues, config.UpdateRemoteOpt{})
	if err != nil {
		return err
	}

	fmt.Println("remote: ", remote)
	fmt.Println("err: ", err)
	return err
}

**Comment by fgc0109** [comment]
@chenyh1101 还是用阿里的库吧
我研究了好几天 这个太重了 也不适合作为库
5M的文件加了这个变成50M
