### ISSUE TITLE
Log output Issue

### ISSUE THREAD

**Issue by Zvon** [ncw/rclone#363]
I have the following running:

`/Applications/rclone/./rclone --log-file /Applications/rclone/rclone.log --include-from /Applications/rclone/include-file.txt copy $UserDir GDrive:`

I only get the following in the log file:

```
2016/02/19 12:41:24 Can't redirect stderr to file
2016/02/19 12:41:29 Google drive root '': Building file list
2016/02/19 12:42:13 Google drive root '': Waiting for checks to finish
2016/02/19 12:42:13 Google drive root '': Waiting for transfers to finish
```

This is what shows up in the terminal window:

```
Transferred:            0 Bytes (   0.00 kByte/s)
Errors:                 0
Checks:              1377
Transferred:            0
Elapsed time:       43.5s
```

shouldn't this second snippet also log to the log file?  I must be missing something simple but i can't identify it.

Thanks!

**Comment by ncw** [comment]
The `Can't redirect stderr to file` is the reason I think.  It shouldn't be saying that!

Which OS are you running on and how many bits? I'm guessing OSX...

I see the problem, I've made up a build tag `unix` in `redirect_stderr.go` - easy enough to fix!

In the mean time you can use command line redirection if you want

    rclone commands  > rclone.log 2>&1

**Comment by Zvon** [comment]
Nice that'll work for now! thanks man

**Comment by ncw** [comment]
This is fixed now and will be in the next release.

Here is a beta with the fix in if you want to try it.

http://pub.rclone.org/v1.27-30-gb5c5209%CE%B2/

**Comment by anyheck** [comment]
I am using the Solaris AMD64 of v1.33 on OmniOS r151018 and I get the "Can't redirect stderr to file" warning at the beginning of the logfile although there is plenty of output afterwards. The target is dropbox.

`rclone  -c --exclude Thumbs.db --log-file logfile.log copy project dropbox:project`

**Comment by ncw** [comment]
@anyheck - I made a new issue for this #698 - please subscribe to that issue for updates - thanks!

**Comment by anyheck** [comment]
I appreciate your work. Thank you very much.
