### ISSUE TITLE
rclone cannot read a encfs --reverse'd directory

### ISSUE THREAD

**Issue by zachron** [ncw/rclone#364]
I am trying to rclone a directory structure that is a encfs --reverse file system, and when i run this  './rclone -v --bwlimit=1M --transfers=1 copy /encrypteddirectory acd:directory' all it returns for every file is '2016/02/19 15:01:23 5Q6YSJOW3CUSPLSOBSB5KCN6USP4J: Can't transfer non file/directory'

debug info: using rclone 1.27 on a linux 64 bit machine

**Comment by ncw** [comment]
Can you run stat  on that file and post what is says please?

**Comment by klauspost** [comment]
Maybe related to #261?

I made a [test program](https://gist.github.com/klauspost/5f87caf402a8abf369d5), that may be able to help here. It requires that you have Go installed.

If you put it into a file called `test.go` and runs `go run test.go "/encrypteddirectory"` it may be able to give us some additional information.

**Comment by zachron** [comment]
@ncw :
here is a stat on one of the file in that encfs --reverse filesystem:
 File: ‘ID3FPB2XOP55L5LJ6D75LWOQINK7JW7PVMLTJWRCOX54XLM2NIXOGCC’
  Size: 6481            Blocks: 16         IO Block: 4096   regular file
Device: 17h/23d Inode: 4245726     Links: 1
Access: (0644/-rw-r--r--)  Uid: ( 1001/   zachron)   Gid: ( 1006/   zachron)
Access: 2010-02-15 18:17:24.000000000 -0700
Modify: 2010-02-15 18:17:24.000000000 -0700
Change: 2010-02-15 18:17:24.000000000 -0700
 Birth: -

**Comment by zachron** [comment]
@klauspost 
here is the output from your test program:

Current dir: "encback"
Main dir Stat:
Name "encback"
Size 4096
IsDir true
Mode.IsDir true
Mode.IsRegular false
Mode.String drwxr-xr-x
Mode.Perm: -rwxr-xr-x

Readdir results:
---
Name "7MK5A7NPCMRZCGIR3TRMS2YYT3Z2N"
Size 4096
IsDir true
Mode.IsDir true
Mode.IsRegular false
Mode.String drwxr-xr-x
Mode.Perm: -rwxr-xr-x
---
Name "NEMXPQCLQFQYXUYTCMHGP7O2OX2BJ"
Size 16384
IsDir true
Mode.IsDir true
Mode.IsRegular false
Mode.String drwxr-xr-x
Mode.Perm: -rwxr-xr-x
---
Name "R5HTKUMYQ6BJNZUZGCX3TNGH7SNWP"
Size 4096
IsDir true
Mode.IsDir true
Mode.IsRegular false
Mode.String drwxr-xr-x
Mode.Perm: -rwxr-xr-x
---
Name "VCLEHE6G2L5FPB73T2DZNH6W5KJBD"
Size 1100
IsDir false
Mode.IsDir false
Mode.IsRegular true
Mode.String -rw-r--r--
Mode.Perm: -rw-r--r--
Success

**Comment by klauspost** [comment]
Thanks - there is nothing jumps out right away.

What is `5Q6YSJOW3CUSPLSOBSB5KCN6USP4J`- a file, or a directory, you seem to have both?

If it is possible for you to post the error and info on the same file, that would help.

**Comment by zachron** [comment]
the error is the same for all the files and directories inside the encfs --reverse file system. i did not think it would matter, since the error is the same for all, so i just randomly chose one when i wrote the initial bug report.

**Comment by ncw** [comment]
I attempted to replicate this but failed - the copy to acd worked perfectly!

Can you adjust the script below so I can replicate the problem?

(I tried on ubuntu 15.10 amd64.)

Thanks

Nick

```
encfs /tmp/encrypted /tmp/visible
cp -av testfiles/ visible/
rclone -v copy encrypted acd:encfs-test
fusermount -u visible/
```

**Comment by zachron** [comment]
sure. i did a sync, but copy (as in yours) does the same thing. in my example visible would have already had files in it, but you can copy them in after its created

encfs --reverse /tmp/visible /tmp/encrypted
cp -av testfiles/ visible/
rclone -v sync encrypted acd:encfs-test
fusermount -u encrypted

**Comment by ncw** [comment]
Ooops, forgot the `--reverse` in my first test.

Still no luck reproducing though.

I'm trying encfs 1.8.1-3 on Ubuntu 15.10 - how about you?

**Comment by zachron** [comment]
i am running encfs 1.8.1 on gentoo

**Comment by ncw** [comment]
Can you try the latest beta? http://pub.rclone.org/v1.27-23-ga3b4c8a%CE%B2/ - that was compiled with go 1.6 so has the latest runtime - maybe stuff got fixed there? I don't have a lot of hope, but it is worth a try!

**Comment by zachron** [comment]
yeah it did not make a difference. i wonder if there is a difference in the setup of encfs that is causing mine to break.

**Comment by zachron** [comment]
a related question that might help track this down, should i be getting the "Can't transfer non file/directory" error for ln -s 'd files?

**Comment by ncw** [comment]
A symlink would count as a non/file directory yes - you can't transfer those with rclone.  There are already issues about that!

**Comment by ncw** [comment]
Is there any chance you could tar up some files that fail for you and send them to me? I'd like to make sure we are testing the same thing!

If you could send two tars of both the encrypted files and the unencrypted files that would be really useful.

Obviously don't send me anything confidential!

Thanks

Nick

**Comment by codefolder** [comment]
Hope this is the same issue here. When I first mount the entire home directory (about 40Gb) with the --reverse option, then try to sync the mount to Google Drive, rclone simply hangs.

I did a workaround where a bash script calls rclone sequentially for each folder in the mounted home (at least this works), but this is far from ideal.

**Comment by zachron** [comment]
@ncw apparently after putting together a sample set of files/directories and checking to see if it worked (it did which was surprising to me) i went back and tried the original directory and it suddenly started working. no idea why. thanks for the help though.

**Comment by ncw** [comment]
@zachron Strange!  Let me know if you manage to get a reproduce!

**Comment by ncw** [comment]
@codefolder How many files in that 40GB? It would be interesting if you tried `rclone size /home/unencrypted` and `rclone size /home/encrypted` and see if they both complete and how long they take.

In general I haven't found fuse based filesystems particularly reliable so I hope it isn't just encfs flaking out!

**Comment by codefolder** [comment]
Well, interesting...

rclone size ~ finished in 15 mins ok as follows:

Total objects: 200988
Total size: 51.981G (55814482381 bytes)

Transferred:            0 Bytes (   0.00 kByte/s)
Errors:                     0
Checks:                   0
Transferred:            0
Elapsed time:    14m45.6s

However, no luck with fuse here: when run on the encrypted mount HDD activity stops after several mins, and now at minute 25 rclone has been hanging for a while. Irrevocably :)

Maybe it's fuse after all... Can rclone incorporate routines to mitigate it? (Like the bash routine I mentioned, perhaps?..)

**Comment by codefolder** [comment]
Update:

rclone --verbose size ./encrypted gives exactly the same error @zachron started out this issue with!

ALL files show a similar message:

2016/02/25 22:22:04 E5zqHfOlPS-8wzzjts6fA7U8/vav8YiYu6VEXvL0xRSW-wWpu/9GUaVSokmFGEbT8otcr6-ge8/3tZjHFUFoTKCiP6KXZ9,Dm4C/2BZE6B-K1BePqsKgMBTtqaIX/IkUz7iZTLlQ3aO,tv1dE,HGxsB7tg177NmyRxeJZd,vVP-: Can't transfer non file/directory

**Comment by ncw** [comment]
Are you sure that the files it mentions really aren't symlinks?

Here is the function that produces that error.

That error is only produced if the file is a symlink, named pipe, socket or device.

```go
// Storable returns a boolean showing if this object is storable
func (o *Object) Storable() bool {
	mode := o.info.Mode()
	if mode&(os.ModeSymlink|os.ModeNamedPipe|os.ModeSocket|os.ModeDevice) != 0 {
		fs.Debug(o, "Can't transfer non file/directory")
		return false
	} else if mode&os.ModeDir != 0 {
		// fs.Debug(o, "Skipping directory")
		return false
	}
	return true
}
```

I've been trying to replicate the problem but it all just seems to work for me :-(

```
$ rclone size /tmp/encrypted
Total objects: 225455
Total size: 7.039G (7558589897 bytes)

Transferred:            0 Bytes (   0.00 kByte/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:         12s

$ rclone size ~/Code
Total objects: 225455
Total size: 7.039G (7558589897 bytes)

Transferred:            0 Bytes (   0.00 kByte/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:        1.7s
```

What version of encfs & linux are you using @codefolder ?

**Comment by ncw** [comment]
I'm going to close this as we haven't made any progress on it.  I'm pretty sure it is an encfs problem but I could be wrong.  Please re-open if you have any more thoughts.
