### ISSUE TITLE
upload speed to Amazon Cloud drive  fix about 256Kbyte/s

### ISSUE THREAD

**Issue by PK130** [ncw/rclone#368]
rclone 1.27, Windows Server 2003R2 , 32 bit, Internet 10Mbit
i:\rclone\rclone.exe   --size-only --transfers 1  -v --max-age 1M copy i:\arch am:arch

if --transfer = 4, each file upload with speed 256Kbyte

**Comment by PK130** [comment]
PS
Upload speed from:
windows server 2012R2  about 500Kbyte/s
Windows 7 SP1 about 1022Kbyte/s

**Comment by ncw** [comment]
I understand you to be saying that using `--transfers 1` files upload at 256 kByte/s whereas if you use `--transfers 4` then you get 4 files, each uploading at 256 kBytes/s.

I can transfer files in excess of 30 MB/s to amazon cloud drive.

Are you sure your provider isn't limiting the speed of each TCP connection? It is possible that amazon is limiting the speed too.

Could you try the test to an alternative provider (eg google drive?)

> PS
> Upload speed from:
> windows server 2012R2 about 500Kbyte/s
> Windows 7 SP1 about 1022Kbyte/s

How did you measure these?

With rclone?

On the same network?

On the same hardware?

Thanks

Nick

**Comment by PK130** [comment]
All my probe from same LAN, 
Server 2003 and 2012 it a virtual server on same host 
With rclone
my provider not limiting speed

**Comment by ncw** [comment]
So this could be something to do with the virtual machine networking?

| OS | VM | Speed |
| --- | --- | --- |
| Server 2003 | Yes | 256 KByte/s |
| Server 2012 | Yes| 500 KByte/s | 
| Win 7 | No | 1022 KByte/s |

Which Virtualisation are you using? Can you try a different one?

**Comment by PK130** [comment]
I using Vmware Vsphere 5.5 virtualisation, the other can not try.
Win 7 is not virtual.
I have tried to upload to other cloud(google and yandex disk) , where the speed is normal(about 10Mb).

**Comment by PK130** [comment]
I found a virtual server 2012 with which rclone copies with normal speed. I suspect that the problem is in the network stack configuration . I'll try to find the differences.

**Comment by ncw** [comment]
Let me know what you find - thanks.

**Comment by ncw** [comment]
I'm going to close this as I think we've established this is to do with the virtual machine networking.  Please re-open if you find otherwise!

Thanks

Nick
