### ISSUE TITLE
Question: Can I generate a list of files between local and remote whose checksums don't match?

### ISSUE THREAD

**Issue by Wowfunhappy** [ncw/rclone#370]
Hello! I hope this is okay to post here, since it isn't an issue with rclone per se. I'm pretty sure there's a way to do this, I just can't quite figure out for myself what the command is I need to run.

Windows recently decided to delete a bunch of files off of my hard drive. (Side note, if Windows ever says that a disc needs to be repaired, back up EVERYTHING before saying yes; the repair deleted some files which I know were perfectly fine!). I was able to recover these files via testdisc's undelete tool, but I'm now somewhat concerned about the integrity of my data.

I have a one-month-old backup of this hard disc sitting on Amazon Cloud Drive.

I would like to generate a list of files on my hard drive whose checksums do not match the ones on ACD. I do not want to do any actual syncing, because there are some files that I've updated since the last time I ran rclone. Furthermore, I'd like to ignore any files that don't exist on BOTH my hard disc and ACD.

What is the best way to accomplish this? I think I need to use --dry-run, but I'm not sure exactly what parameters I need to give. Thank you so much!

**Comment by ncw** [comment]
Use the `rclone check` command that is what it is for. You might want the `-v` flag too. This will tell you about files which don't exist in one place or the other and tell you about checksum mismatches on files which exist in both places.

**Comment by Wowfunhappy** [comment]
*facepalm*

I'm an idiot. I completely missed that section of the documentation, I guess because it's shorter than the sections around it.

This helped a lot, thank you! It wasn't perfect because I also got a lot of data about files that were only on either the source or destination, but I was able to filter most of it out!

**Comment by ncw** [comment]
Glad you found that useful :-)
