### ISSUE TITLE
onedrive client secret?

### ISSUE THREAD

**Issue by fd0** [ncw/rclone#372]
Hey,

I'd like to add support for Microsoft OneDrive to [restic](https://github.com/restic/restic), a fast and secure backup program written in Go. I've seen that in order to interface with the OneDrive API, an applications needs to be registered with Microsoft and needs to present, among others, a Client-Secret, which is to be kept secret.

rclone just includes the Client-Secret in the source code (https://github.com/ncw/rclone/blob/master/onedrive/onedrive.go#L27-L28), which is pragmatic, but possibly violates their TOS. The process described at https://auth0.com/docs/connections/social/microsoft-account in step 4 displays the web form, next to the Client-Secret the following text is printed: "For security purposes, don't share your client secret with anyone". How is that supposed to work? You'd still need to include the Client-Secret in an application, or not?

Is it allowed/accepted to include the Client-Secret in the source of an Open Source application? Did you get a special permit from Microsoft? Did you ask them about it?

Thanks for your response!

**Comment by ncw** [comment]
The client secret is obfuscated so it isn't directly I'm the code - that was the best I could come up with. 

If you think through all the possible ways of having a client secret in an open source program you'll see that there aren't any better solutions, unless you want to run an auth server and handle all your users auth (with the attendant risk) which I wasn't willing to do. 

All the client secret allows is for someone to impersonate your app, there is no possibility of user data being disclosed so I deem it to be low risk. 

No I didn't ask Microsoft about it!

**Comment by fd0** [comment]
Hey, thanks for the clarification!
