### ISSUE TITLE
b2: Failed to upload: more than one upload using auth token 400 bad request

### ISSUE THREAD

**Issue by padelt** [ncw/rclone#373]
I am trying `--transfers 2` against b2. In the logs, every several minutes I get one of these.

Using `--transfers 1` stops the problem. 4 makes it logged a lot more.

> What is your rclone version (eg output from `rclone -V`)

rclone-v1.27-18-g85a0f25-beta

> Which OS you are using and how many bits (eg Windows 7, 64 bit)

Raspberry Pi 2: Linux hostname 4.1.13-v7+ #826 SMP PREEMPT Fri Nov 13 20:19:03 GMT 2015 armv7l GNU/Linux

> Which cloud storage system are you using? (eg Google Drive)

Backblaze B2

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

`rclone copy --transfers 2 --log-file ~/rclone.log --size-only --verbose --ignore-existing /home/pa/sourcedir b2target:bucketname/targetdir/`

> A log from the command with the `-v` flag (eg output from `rclone -v copy /tmp remote:tmp`)

`2016/02/29 08:41:12 sourcdir/subdir/filename.ext: Failed to copy: Failed to upload: more than one upload using auth token 3_201602xxxxxx48_aexxxxxx808xxxxxx05xxx39_dcxxxxx9c18xxxxxxxcd84c2xxxxxxxxxx957xx4_001_upld (400 bad_request)`

**Comment by ncw** [comment]
I've fixed this already in 6b6b43402b14a607695d9c05bff643c1837c81ea (there wasn't an issue about it so don't feel bad about not finding it!).

This didn't used to happen - I think Backblaze must be enforcing the one upload URL per thread rule which rclone wasn't obeying properly before (something I managed to miss from the docs).

So if you try the latest beta http://pub.rclone.org/v1.27-45-ge6f340d%CE%B2/ you should find that is fixed.

**Comment by padelt** [comment]
Great, thanks! After some mintes of log watching, it looks like I can confirm that the message is gone. Again, thanks a lot for the work on rclone and of course for the quick response!
