### ISSUE TITLE
rclone file limit bug

### ISSUE THREAD

**Issue by bucrepus** [ncw/rclone#374]
v1.27 Windows 7/8.1 x64
Dropbox

File limit bug / setting?

When I issue the command:
rclone purge remote:..path

I get the error:
2016/03/01 14:58:41 Attempt 1/3 failed with 1 errors and: There are too many files involved in this operation. and so forth.. and after the last retry..
2016/03/01 14:59:05 Failed to purge: There are too many files involved in this operation.

I can upload / list / perform other functions with no issue. I have tried from two diff. internet connection locations with same results. The error displays fairly quickly after the command is issued. There are approx. 750K files in various approx. 150 subdirectories

**Comment by ncw** [comment]
This looks like it is a dropbox limitation - it can only operate on 10,000 files at once.  rclone sends a single command to dropbox to do a purge but dropbox immediately replies with that error.

http://stackoverflow.com/questions/24843780/dropbox-core-api-10000-file-move-strategy

You could try doing `rclone delete ...` instead.  This will be much slower, but it should work.

If that works I'll document the work-around in the dropbox docs.

Thanks

Nick

**Comment by ncw** [comment]
Did you have a go with `rclone delete`?
