### ISSUE TITLE
Add progress display (stats) for the whole operation

### ISSUE THREAD

**Issue by Thinkscape** [ncw/rclone#379]
## What happens now:
By default, rclone shows total bytes transferred and progress for each transfer thread (each file being transferred). For example `sync local remote:location` shows transferred bytes + 4 lines for 4 threads uploading 4 individual files to the remote backend.

![image](https://cloud.githubusercontent.com/assets/270528/13523491/0ec89132-e1f6-11e5-8471-1b4e157ec753.png)

## What should happen:
Rclone should display the total progress (and ETA) of the requested operation, i.e. a `sync` operation, which is effectively:
> progress = transfered_files / total_files * 100%

The current progress display is not very useful, unless someone `syncs` a single file or manually checks the source size and compares against `Transferred`.

IMO The current per-thread progress status should live within `--verbose` progress display for diagnosing stuff like backend rate-limits or transfer limits. By default, rclone should display **total** progress of operation and **total throughput** of all threads - total download/upload speed maintained.

Maybe something inspired by curl progress? 
![](http://i.stack.imgur.com/m7O1i.png)

Or like wget ?
![](http://www.thelinuxterminal.com/wp-content/uploads/2014/10/wget-download-1140x344_c.png)
![](http://4.bp.blogspot.com/-DlhB25swqEs/UZe0CPLAv6I/AAAAAAAAAIc/Ig5nSOpv2fw/s1600/Progress+Label.png)

**Comment by klauspost** [comment]
Let me give this a shot.

**Comment by klauspost** [comment]
`rclone` starts transfer before it knows how all of which files it will transfer. This is so hash checking can be done meanwhile we are uploading.

We know how many files/bytes we will be checking in total when we have read the source file system. That means the metrics we can supply are:

```
Checked:         41253175 of 46673371 bytes (88.39%), 461 of 1172 files
Transferred:     17330604 of 17342459 queued bytes (415.53 kByte/s), 22 files
Errors:                 0
Elapsed time:       40.7s
```
Note the "queued" in the "transferred" stats. That number will keep growing, and cannot be used for an ETA, because we are only checking a few files ahead of the ones we are transferring.

As for showing individual transfers only in verbose mode, I do agree, but @ncw will have to approve changing the default behaviour.

**Comment by Thinkscape** [comment]
I'm not sure where I should comment now, as #389 overlaps.

I get the challenge. As the total bytes is a rolling metric, it might not be complete. However, that will depend on the dataset size, number of files and performance of "checkers". It's quite possible, that in many cases users will get the actual, final total number of bytes queued in a few seconds from starting. I do feel like it should be possible to represent that in an ETA and progress report.

So let's modify the example a bit:
````
Checked:         41253175 of 46673371 bytes (88.39%), 461 of 1172 files
Transferred:     17330604 of 17342459 queued bytes (40%, 415.53 kByte/s), 22 of 300 files
Errors:                 0
Elapsed time:       40.7s
````

Notice i've added percentage for transferred.
Now for the percentage, a stacked progress bar would do fine.

Here's an example for when there's a lot of files to check and the transfer takes more than the checking.

````
Synchronizing [>                                         ] 0%  1401 kByte/s
Synchronizing [==>                                       ] 0%  1401 kByte/s
Synchronizing [====>                                     ] 1%  1401 kByte/s
Synchronizing [#====>                                    ] 5%  1401 kByte/s
Synchronizing [#####=========>                           ] 10%  1401 kByte/s
Synchronizing [###########===========>                   ] 15%  1401 kByte/s
Synchronizing [#################========================>] 26%  1401 kByte/s
Synchronizing [#######################===================] 51%  1401 kByte/s
Synchronizing [##########################################] 100% 1401 kByte/s  
````

The `==>` bar is for checking and deletions, the `###` bar is transfer of new and modified files.

The total progress would be a product of both:
`total_progress = (checked_files / total_files) * (transferred_files / files_to_transfer)`

That means:
* the assumption is transfer is slower that checks,
* when checked all files (100%) but transferred 50%, total progress = 50%.
* when checked 50% files and transferred 0 files, total progress = 0%
* when checked 50% files and transferred 50% of queued files, total progress = 25%
* yes, when checking is slow and there's a lot of files, the total progress might go down, but that's why the visualization will give the user a better picture of what's happening.
* ETA should be a derivative of total progress.

````
Synchronizing [#######################===================] 31%  1401 kByte/s ETA 25m
````

**Comment by klauspost** [comment]
You assume we know "files_to_transfer" - we do not, because checks need to finish before we know if we should transfer, and there is a limited "queue" (default 4) of files waiting to transfer, so checks are not done before there is space in the transfer queue. 

Transfer will never be "22 of 300 files", because there isn't space for 278 files in the transfer queue.

**Comment by Thinkscape** [comment]
I guess I didn't fully understand your current queue implementation.
Does that mean, that all checks will be suspended once the queue is full with 4 items ?

**Comment by Thinkscape** [comment]
Nah, I've done some experiments. Nothing meaningful can be produced without sacrificing the original design, which I'm quite fond of, really. I will however propose some better, non-verbose, status display in the other ticket.

**Comment by klauspost** [comment]
Agree. Just to elaborate - I see "late" checking as a positive feature. If you are doing a transfer that takes a lot of time, it will transfer files that are changed during the transfer and hasn't been checked yet.

**Comment by Thinkscape** [comment]
That's what I meant :-) It's effectively a rolling operation. It's also lower resource and can be faster with larger sets. Maybe in the future we can have a mode flag which would allow for more rsync-esque operation with pre-scanning and queueing all changes, as this can have its advantages in some scenarios.

**Comment by bobbintb** [comment]
Whatever is done, the percentage complete needs to be based on size, not number of files as OP suggests. If I am transferring 99 small image files only a few k each and one 10gb video and it transfers the images first it's going to tell me I am 99% done transferring when I am really less than 1% done.

**Comment by evulhotdog** [comment]
@Thinkscape What do you think about doing something similar to a rolling progress bar design, similar to docker's pull. This would only need to show current files/transfers, as sort of a live progress.

**Comment by Thinkscape** [comment]
Yep, make sense. Showing any form of progress would be nice. For @bobbintb example, having progress bar for large files, as well as having number of files transferred and remaining, would make it easier to understand the overall progress.

**Comment by timofonic** [comment]
Any news? :D

**Comment by Artefact2** [comment]
Something similar to `rsync --info=progress2` would be amazing.

~~~
105.45M 13% 602.83kB/s 0:02:50 (xfr#495, ir-chk=1020/3825)
~~~

Printed as they are, the stats are too spammy, esp. considering they keep printing new lines instead of writing over the previous stat block.

**Comment by peixotorms** [comment]
Not sure if this would be useful, but for those remotes with ssh/sftp we can get a list of files to transfer via rsync -avzm --stats --safe-links --ignore-existing --dry-run  --human-readable /path/to/somewhere 192.168.1.2:/data/ > /tmp/transfer.log

It's also possible to obtain the amount of files to be transferred and it's size in a few seconds (took me 2 seconds to scan through 250 GB of small files). Something like this: `http://kristau.net/blog/20/`

Even if most providers don't support this, perhaps it can be used for those that support it.

I think it would be great to have some sort of cumulative progress.
One line with cumulative data for:
- transferred MB
- current speed
- total files transferred
- size of the queue (count + MB), or some sort of progress for how many were checked.

**Comment by dandv** [comment]
@Thinkscape what's up with the Xwinner Sweepstakes image in the OP?

**Comment by evulhotdog** [comment]
@dandv I don't remember that being there when it was originally posted. Wondering if someones account got compromised and it changed the uploaded pic?

**Comment by NoLooseEnds** [comment]
What is the status of this? I would love this, especially on the initial upload.

This is status on one of my servers right now, I have a ish idea of how big the backup is, and I can sort of calculate it – but it would be great to have a progressbar of some sort.

```
Transferred:   2299.227 GBytes (1.427 MBytes/s)
Errors:                 9
Checks:             91767
Transferred:       271365
Elapsed time:  458h17m1.1s
´´´

**Comment by ncw** [comment]
I have finally fixed this here:

https://beta.rclone.org/v1.42-104-g6390dec7/ (uploaded in 15-30 mins)

It does it by keeping a backlog (10,000 by default settable with --max-backlog) of files to upload.

I've also added --stats-one-line which mimics rsyncs --progress=info2.  (Actuall --progress support to come in #2347)

**Comment by Artefact2** [comment]
Testing this nèw in v1.43, `--progress --stats-one-line` works like a charm. It's consise and tells you what you need to know. This makes `rclone` so much better to use! Thank you very much for working on this.
