### ISSUE TITLE
Unable to access hubic storage - Swift container : Can't list objects at root 

### ISSUE THREAD

**Issue by raphag** [ncw/rclone#380]
Hello,

I don't manage to access my hubic storage

rclone v1.28
Linux 64 (Ubuntu 12.04)
Hubic

Here is what I get :

comp1$ ./rclone -V
rclone v1.28
comp1$ ./rclone -v ls hubic:/
2016/03/05 11:24:54 Hubic: Got swift credentials (expiry 2016-03-06 10:50:28 +0100 CET in 23h25m33.477192427s)
2016/03/05 11:24:54 Hubic Swift container : Modify window is 1ns
2016/03/05 11:24:54 Swift container : Can't list objects at root - choose a container using lsd

Transferred:            0 Bytes (   0.00 kByte/s)
Errors:                 1
Checks:                 0
Transferred:            0
Elapsed time:       300ms

2016/03/05 11:24:54 Go routines at exit 5

And it is able only to list root objects : 

comp1$ ./rclone -v lsd hubic:/
2016/03/05 11:25:15 Hubic: Got swift credentials (expiry 2016-03-06 10:50:28 +0100 CET in 23h25m12.770143193s)
2016/03/05 11:25:15 Hubic Swift container : Modify window is 1ns
   680073422 0001-01-01 00:00:00        10 .Trash-1000
           0 0001-01-01 00:00:00         3 .Trash-1001
   798825217 0001-01-01 00:00:00     16906 HubiC-DeskBackup_GMailBackup.encfs
   277495463 0001-01-01 00:00:00        89 HubiC-DeskBackup_GMailBackup.encfs_segments
    11859108 0001-01-01 00:00:00        52 HubiC-DeskBackup_GMailBackup.encfs_versions
112282098660 0001-01-01 00:00:00     35968 default
 11410511681 0001-01-01 00:00:00       124 default_segments

Transferred:            0 Bytes (   0.00 kByte/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:       600ms

2016/03/05 11:25:15 Go routines at exit 5

Thanks !

**Comment by ncw** [comment]
You have to list a bucket - all actions on hubic except for `lsd` work on buckets.

eg `./rclone -v ls hubic:default`

Hope that helps

Nick

**Comment by raphag** [comment]
Thanks Nick !

It's much better !
I didn't know about buckets ... but I will look closer !

Thanks again
Raphael

**Comment by ncw** [comment]
No problems!
