### ISSUE TITLE
Feature Request: Support for Sharepoint Online

### ISSUE THREAD

**Issue by mark-orion** [ncw/rclone#382]
Great Project! I would like to suggest support for Sharepoint Online. The big difference between Sharepoint Server and the Online version of Microsoft Sharepoint is that the online version does not support basic authentication for WebDav (only claims based auth). This is a showstopper for almost all non-windows WebDav clients. Looking at the clever way how rclone authenticates with onedrives makes it a prime candidate for me to get around the authentication problems with Sharepoint Online.

**Comment by ncw** [comment]
If rclone supported webdav + the correct authentication scheme would that be enough to make it work with sharepoint online?

**Comment by davidovitch** [comment]
It should work in principle with webdav: http://howto.unixdev.net/Linux-SharePoint.html
...but there are authentication related issues that prevent if from working right now:
* https://superuser.com/questions/851483/mount-sharepoint-online-office-365-in-linux
* https://stackoverflow.com/questions/9871270/mounting-webdav-shares-using-davfs2

**Comment by Cnly** [comment]
I'm reading through some old bugs and I came across this one. I think this has already been supported? Can we close it?

**Comment by ncw** [comment]
Yes this is supported by the [webdav backend](https://rclone.org/webdav/#sharepoint) now so I'll close this
