### ISSUE TITLE
Model sync deletion after rsync

### ISSUE THREAD

**Issue by InAnimaTe** [ncw/rclone#384]
From the docs:

> Destination is updated to match source, including deleting files if necessary.

I feel, like rsync, this should be explicitly defined by the user using the `--delete` flag. However, if this just isn't going to happy, what about a `--no-delete` flag?

Just wondering what others think about the current way it works in contrast to how rsync does things. Again, I would obviously love to see option and flag parity with rsync as close as possible, but if there are just certain things that won't be done, I understand that.

**Comment by ncw** [comment]
Just use `copy` as the verb instead of `sync` - that is the only difference between the two.

**Comment by InAnimaTe** [comment]
I suppose....

**Comment by ashayh** [comment]
The rclone commands are of the type `rclone verb source destination`. This implies the action should happen only on the destination. But the `sync` verb deletes source files. This is counter intuitive behavior. Also I imagine a number of people using rclone will be former rsync users. It would therefore be a good default to _not_ delete by default on source when syncing.

**Comment by ncw** [comment]
@ashayh rclone works exactly like rsync - it only deletes files on the **destination** when using the `sync` verb.

**Comment by ashayh** [comment]
Hmm .. when I do a dry run with `-n` I see such messages in the output: `2016/07/03 18:47:27 Nikon/Maui/DSC_6152.NEF: Not deleting as --dry-run` . This particular file is in the source, not destination. This sounds as if it would have deleted the file on source or (destination?). Either way, I did not ask to delete anything anywhere, so why should I see this message in the dry run? Because of this message, I chose to use `copy` instead of sync. I'm using version 1.30 built from source on Linux. If what you say is correct maybe this output needs fixing?

**Comment by ncw** [comment]
@ashayh Strange - that isn't how I think it works... Have you got the source and destintation the wrong way round?  It goes `rclone sync source destination`?  Can you post the command line you are using please? And can you see that file in either the source or the destination - maybe it got in the destination in the wrong place?

**Comment by ashayh** [comment]
Here is the command I ran: `rclone -n sync Nikon AMZN: `
Here I am in the directory where the `Nikon` sub directory is present, and AMZN is a Clouddrive endpoint in ~/.rclone.conf. I ran it multiple times always in dry-run and each time I saw `deleted` in the output.

**Comment by ncw** [comment]
I think maybe you want to use `rclone -n sync Nikon AMZN:Nikon`.  What I suspect is that you've uploaded some files already to acd but you are syncing them into a different place and it is showing you that you would delete some files if you were to sync like that.
