### ISSUE TITLE
fatal error: concurrent map read and map write

### ISSUE THREAD

**Issue by aleritty** [ncw/rclone#385]
Quite every time I run rclone I obtain this blocking error.

> What is your rclone version (eg output from `rclone -V`)
rclone v1.28

> Which OS you are using and how many bits (eg Windows 7, 64 bit)
Ubuntu 12.04 (Linux 3.2.61) x86_64

> Which cloud storage system are you using? (eg Google Drive)
Google Drive for work

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone sync /home/$USER/sciumegu.it/nuovidown "sciu-drive:Materiale vecchio sciumegu"

> A log from the command with the `-v` flag (eg output from `rclone -v copy /tmp remote:tmp`)
2016/03/09 12:48:56 Google drive root 'Materiale vecchio sciumegu': Modify window is 1ms
2016/03/09 12:48:56 Google drive root 'Materiale vecchio sciumegu': Building file list
2016/03/09 12:48:56 Local file system at /home/sciumegu/sciumegu.it/nuovidown: Replacing invalid UTF-8 characters in "primo-anno/2010-2011/biochimica-1/Testi esame di idoneit\x85 del 14 gennaio 2013.pdf"
2016/03/09 12:48:56 Local file system at /home/sciumegu/sciumegu.it/nuovidown: Replacing invalid UTF-8 characters in "primo-anno/2010-2011/biochimica-2/Mos\x8a - Riassunto Biochimica 2.pdf"
2016/03/09 12:48:56 quarto-anno/2014-2015/gastroenterologia/Gastroenterologia.pdf: Warning: File found with same name but different case on Local file system at /home/sciumegu/sciumegu.it/nuovidown
2016/03/09 12:48:56 Local file system at /home/sciumegu/sciumegu.it/nuovidown: Replacing invalid UTF-8 characters in "quinto-anno/2010-2011/ginecologia/2- Infertilit\x85.ppt"
2016/03/09 12:48:56 Local file system at /home/sciumegu/sciumegu.it/nuovidown: Replacing invalid UTF-8 characters in "quinto-anno/2010-2011/ginecologia/MIP e Sterilit\x85 - SIGO 2007.ppt"
2016/03/09 12:48:56 Local file system at /home/sciumegu/sciumegu.it/nuovidown: Replacing invalid UTF-8 characters in "quinto-anno/2014-2015/psichiatria/Personalit\x85 e disturbi di personalit\x85.pdf"
2016/03/09 12:48:56 Local file system at /home/sciumegu/sciumegu.it/nuovidown: Replacing invalid UTF-8 characters in "secondo-anno/2013-2014/fisiologia-2/Generalit\x99 sul Sistema Motorio.pdf"
2016/03/09 12:48:56 Local file system at /home/sciumegu/sciumegu.it/nuovidown: Replacing invalid UTF-8 characters in "secondo-anno/2014-2015/fisiologia-2/Generalit\x85 sul Sistema Motorio.pdf"
2016/03/09 12:48:56 Local file system at /home/sciumegu/sciumegu.it/nuovidown: Replacing invalid UTF-8 characters in "secondo-anno/2014-2015/fisiologia-2/Plasticit\x85 e Memoria.pdf"
2016/03/09 12:48:56 Local file system at /home/sciumegu/sciumegu.it/nuovidown: Replacing invalid UTF-8 characters in "secondo-anno/2014-2015/fisiologia-2/Propriet+\xa0 Passive.pdf"
2016/03/09 12:48:56 Local file system at /home/sciumegu/sciumegu.it/nuovidown: Replacing invalid UTF-8 characters in "secondo-anno/2014-2015/fisiologia-2/Propriet\x85 Passive.pdf"
2016/03/09 12:48:56 Local file system at /home/sciumegu/sciumegu.it/nuovidown: Replacing invalid UTF-8 characters in "sesto-anno/2011-2012/chirurgia-2/Lezione carcinoma ano 6\xf8 anno.ppt"
2016/03/09 12:48:56 Local file system at /home/sciumegu/sciumegu.it/nuovidown: Replacing invalid UTF-8 characters in "sesto-anno/2011-2012/chirurgia-2/Pancreatite acuta 6\xf8 anno.ppt"
2016/03/09 12:48:56 Local file system at /home/sciumegu/sciumegu.it/nuovidown: Replacing invalid UTF-8 characters in "sesto-anno/2012-2013/igiene/Corso medicina 6\xf8anno (1 modulo).ppt"
2016/03/09 12:48:56 Local file system at /home/sciumegu/sciumegu.it/nuovidown: Replacing invalid UTF-8 characters in "sesto-anno/2012-2013/igiene/Corso medicina 6\xf8anno (3 modulo).ppt"
2016/03/09 12:48:56 Local file system at /home/sciumegu/sciumegu.it/nuovidown: Replacing invalid UTF-8 characters in "sesto-anno/2012-2013/igiene/Corso medicina 6\xf8anno (4 modulo).ppt"
2016/03/09 12:48:56 Local file system at /home/sciumegu/sciumegu.it/nuovidown: Replacing invalid UTF-8 characters in "sesto-anno/2012-2013/igiene/Corso medicina 6\xf8anno (5 modulo).ppt"
2016/03/09 12:48:56 Local file system at /home/sciumegu/sciumegu.it/nuovidown: Replacing invalid UTF-8 characters in "sesto-anno/2012-2013/igiene/Corso medicina 6\xf8anno (6 modulo).ppt"
2016/03/09 12:48:56 Local file system at /home/sciumegu/sciumegu.it/nuovidown: Replacing invalid UTF-8 characters in "sesto-anno/2012-2013/igiene/Corso medicina 6\xf8anno (7 modulo).ppt"
2016/03/09 12:48:56 Local file system at /home/sciumegu/sciumegu.it/nuovidown: Replacing invalid UTF-8 characters in "sesto-anno/2012-2013/medicina-2/10\xf8 approccio al paziente con episodi sincopali.ppt"
2016/03/09 12:48:56 Local file system at /home/sciumegu/sciumegu.it/nuovidown: Replacing invalid UTF-8 characters in "sesto-anno/2012-2013/medicina-2/11\xf8 paziente iperteso.ppt"
fatal error: concurrent map read and map write

goroutine 28 [running]:
runtime.throw(0xc7f360, 0x21)
	/usr/local/go/src/runtime/panic.go:530 +0x90 fp=0xc82003bb38 sp=0xc82003bb20
runtime.mapaccess2_faststr(0x997240, 0xc82012d050, 0xc82065d525, 0x53, 0x0, 0x0)
	/usr/local/go/src/runtime/hashmap_fast.go:307 +0x5b fp=0xc82003bb98 sp=0xc82003bb38
github.com/ncw/rclone/local.(*Fs).cleanUtf8(0xc820154410, 0xc82065d525, 0x53, 0x0, 0x0)
	/home/ncw/Code/Go/src/github.com/ncw/rclone/local/local.go:178 +0xb6 fp=0xc82003bcd0 sp=0xc82003bb98
github.com/ncw/rclone/local.(*Object).Remote(0xc8206661c0, 0x0, 0x0)
	/home/ncw/Code/Go/src/github.com/ncw/rclone/local/local.go:441 +0x47 fp=0xc82003bd00 sp=0xc82003bcd0
github.com/ncw/rclone/fs.readFilesMap(0x2b13e4e5d10, 0xc820154410, 0x0, 0x0)
	/home/ncw/Code/Go/src/github.com/ncw/rclone/fs/operations.go:443 +0x183 fp=0xc82003bed0 sp=0xc82003bd00
github.com/ncw/rclone/fs.syncCopyMove.func2(0xc82002e028, 0x2b13e4e5d10, 0xc820154410, 0xc820452890, 0xc820508300)
	/home/ncw/Code/Go/src/github.com/ncw/rclone/fs/operations.go:502 +0x42 fp=0xc82003bf88 sp=0xc82003bed0
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc82003bf90 sp=0xc82003bf88
created by github.com/ncw/rclone/fs.syncCopyMove
	/home/ncw/Code/Go/src/github.com/ncw/rclone/fs/operations.go:508 +0x2be

goroutine 1 [semacquire]:
sync.runtime_Semacquire(0xc82045289c)
	/usr/local/go/src/runtime/sema.go:47 +0x26
sync.(*WaitGroup).Wait(0xc820452890)
	/usr/local/go/src/sync/waitgroup.go:127 +0xb4
github.com/ncw/rclone/fs.syncCopyMove(0x2b13e4f1730, 0xc820073260, 0x2b13e4e5d10, 0xc820154410, 0x400001, 0x0, 0x0)
	/home/ncw/Code/Go/src/github.com/ncw/rclone/fs/operations.go:548 +0x38d
github.com/ncw/rclone/fs.Sync(0x2b13e4f1730, 0xc820073260, 0x2b13e4e5d10, 0xc820154410, 0x0, 0x0)
	/home/ncw/Code/Go/src/github.com/ncw/rclone/fs/operations.go:615 +0x55
main.glob.func2(0x2b13e4f1730, 0xc820073260, 0x2b13e4e5d10, 0xc820154410, 0x0, 0x0)
	/home/ncw/Code/Go/src/github.com/ncw/rclone/rclone.go:83 +0x4b
main.main()
	/home/ncw/Code/Go/src/github.com/ncw/rclone/rclone.go:480 +0xa1f

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1

goroutine 11 [IO wait]:
net.runtime_pollWait(0x2b13e4ef3a8, 0x72, 0xc820521000)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc8201a83e0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8201a83e0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8201a8380, 0xc820521000, 0x1000, 0x1000, 0x0, 0x2b13e4e1028, 0xc8200740a0)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc82002e018, 0xc820521000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
github.com/mreiferson/go-httpclient.(*rwTimeoutConn).Read(0xc820010240, 0xc820521000, 0x1000, 0x1000, 0xd, 0x0, 0x0)
	/home/ncw/Code/Go/src/github.com/mreiferson/go-httpclient/httpclient.go:228 +0x17f
crypto/tls.(*block).readFromUntil(0xc8200123c0, 0x2b13d49f1d8, 0xc820010240, 0x5, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:460 +0xcc
crypto/tls.(*Conn).readRecord(0xc820300000, 0xd29517, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:562 +0x2d1
crypto/tls.(*Conn).Read(0xc820300000, 0xc820195000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:939 +0x167
net/http.noteEOFReader.Read(0x2b13d4a56d0, 0xc820300000, 0xc82019e3a8, 0xc820195000, 0x1000, 0x1000, 0x409853, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:1683 +0x67
net/http.(*noteEOFReader).Read(0xc8201e0b00, 0xc820195000, 0x1000, 0x1000, 0xc82004bd0d, 0x0, 0x0)
	<autogenerated>:284 +0xd0
bufio.(*Reader).fill(0xc820303260)
	/usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Peek(0xc820303260, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:132 +0xcc
net/http.(*persistConn).readLoop(0xc82019e340)
	/usr/local/go/src/net/http/transport.go:1069 +0x177
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:853 +0x10a6

goroutine 26 [chan receive]:
main.StartStats.func1()
	/home/ncw/Code/Go/src/github.com/ncw/rclone/rclone.go:390 +0x53
created by main.StartStats
	/home/ncw/Code/Go/src/github.com/ncw/rclone/rclone.go:393 +0x40

goroutine 12 [select]:
net/http.(*persistConn).writeLoop(0xc82019e340)
	/usr/local/go/src/net/http/transport.go:1273 +0x472
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:854 +0x10cb

goroutine 36 [select]:
net/http.(*persistConn).roundTrip(0xc82019e340, 0xc820446030, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:1469 +0xf1f
net/http.(*Transport).RoundTrip(0xc8200e8480, 0xc8204c80e0, 0x456bd0, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:320 +0x9bb
github.com/mreiferson/go-httpclient.(*Transport).RoundTrip(0xc8201a8000, 0xc8204c80e0, 0xc8204c80e0, 0x0, 0x0)
	/home/ncw/Code/Go/src/github.com/mreiferson/go-httpclient/httpclient.go:201 +0x2d2
golang.org/x/oauth2.(*Transport).RoundTrip(0xc82012d320, 0xc820420fc0, 0xc82012d320, 0x0, 0x0)
	/home/ncw/Code/Go/src/golang.org/x/oauth2/transport.go:48 +0x234
net/http.send(0xc820420fc0, 0x2b13e4e5f50, 0xc82012d320, 0x0, 0x0, 0x0, 0xc8202f0000, 0x0, 0x0)
	/usr/local/go/src/net/http/client.go:260 +0x6b7
net/http.(*Client).send(0xc82012d350, 0xc820420fc0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/client.go:155 +0x185
net/http.(*Client).doFollowingRedirects(0xc82012d350, 0xc820420fc0, 0xd29028, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/client.go:475 +0x8a4
net/http.(*Client).Do(0xc82012d350, 0xc820420fc0, 0xa, 0x0, 0x0)
	/usr/local/go/src/net/http/client.go:188 +0xff
google.golang.org/api/drive/v2.(*FilesListCall).doRequest(0xc820559da0, 0xbd1e28, 0x4, 0x0, 0x0, 0x0)
	/home/ncw/Code/Go/src/google.golang.org/api/drive/v2/drive-gen.go:5837 +0x4f2
google.golang.org/api/drive/v2.(*FilesListCall).Do(0xc820559da0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/ncw/Code/Go/src/google.golang.org/api/drive/v2/drive-gen.go:5849 +0x9f
github.com/ncw/rclone/drive.(*Fs).listAll.func1(0xc8200731a0, 0x0, 0x0)
	/home/ncw/Code/Go/src/github.com/ncw/rclone/drive/drive.go:219 +0x53
github.com/ncw/rclone/pacer.(*Pacer).call(0xc8200731a0, 0xc820559d80, 0xa, 0x0, 0x0)
	/home/ncw/Code/Go/src/github.com/ncw/rclone/pacer/pacer.go:261 +0x82
github.com/ncw/rclone/pacer.(*Pacer).Call(0xc8200731a0, 0xc820559d80, 0x0, 0x0)
	/home/ncw/Code/Go/src/github.com/ncw/rclone/pacer/pacer.go:284 +0x7a
github.com/ncw/rclone/drive.(*Fs).listAll(0xc820073260, 0xc8201b8080, 0x1c, 0x0, 0x0, 0xc820060000, 0xc820559e98, 0xc820065300, 0x0, 0x0)
	/home/ncw/Code/Go/src/github.com/ncw/rclone/drive/drive.go:221 +0x999
github.com/ncw/rclone/drive.(*Fs).listDirRecursive(0xc820073260, 0xc8201b8080, 0x1c, 0x0, 0x0, 0xc8205183c0, 0x0, 0x0)
	/home/ncw/Code/Go/src/github.com/ncw/rclone/drive/drive.go:506 +0xf5
github.com/ncw/rclone/drive.(*Fs).List.func1(0xc8205183c0, 0xc820073260)
	/home/ncw/Code/Go/src/github.com/ncw/rclone/drive/drive.go:528 +0x225
created by github.com/ncw/rclone/drive.(*Fs).List
	/home/ncw/Code/Go/src/github.com/ncw/rclone/drive/drive.go:534 +0x64

goroutine 27 [chan receive]:
github.com/ncw/rclone/fs.readFilesMap(0x2b13e4f1730, 0xc820073260, 0x0, 0x0)
	/home/ncw/Code/Go/src/github.com/ncw/rclone/fs/operations.go:442 +0x14f
github.com/ncw/rclone/fs.syncCopyMove.func1(0xc82002e010, 0x2b13e4f1730, 0xc820073260, 0xc820452890)
	/home/ncw/Code/Go/src/github.com/ncw/rclone/fs/operations.go:496 +0x40
created by github.com/ncw/rclone/fs.syncCopyMove
	/home/ncw/Code/Go/src/github.com/ncw/rclone/fs/operations.go:498 +0x26b

goroutine 29 [chan receive]:
github.com/ncw/rclone/fs.syncCopyMove.func3(0xc820508301, 0x2b13e4f1730, 0xc820073260, 0xc8204528a0, 0xc820508360, 0xc82002e010, 0xc82002e028)
	/home/ncw/Code/Go/src/github.com/ncw/rclone/fs/operations.go:524 +0x8e
created by github.com/ncw/rclone/fs.syncCopyMove
	/home/ncw/Code/Go/src/github.com/ncw/rclone/fs/operations.go:545 +0x37c

goroutine 30 [runnable]:
os.fillFileStatFromSys(0xc820665520, 0xc820663f80, 0x56)
	/usr/local/go/src/os/stat_linux.go:12
os.Lstat(0xc820663f80, 0x56, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/os/file_unix.go:187 +0x1af
path/filepath.walk(0xc82000bd10, 0x44, 0x2b13e4e5c28, 0xc820665040, 0xc82004df50, 0x0, 0x0)
	/usr/local/go/src/path/filepath/path.go:368 +0x3a3
path/filepath.walk(0xc820652100, 0x39, 0x2b13e4e5c28, 0xc82064e410, 0xc82004df50, 0x0, 0x0)
	/usr/local/go/src/path/filepath/path.go:374 +0x4fc
path/filepath.walk(0xc820389650, 0x2f, 0x2b13e4e5c28, 0xc82063e9c0, 0xc82004df50, 0x0, 0x0)
	/usr/local/go/src/path/filepath/path.go:374 +0x4fc
path/filepath.walk(0x398ddf90d9c, 0x24, 0x2b13e4e5c28, 0xc8205404e0, 0xc82004df50, 0x0, 0x0)
	/usr/local/go/src/path/filepath/path.go:374 +0x4fc
path/filepath.Walk(0x398ddf90d9c, 0x24, 0xc82004df50, 0x0, 0x0)
	/usr/local/go/src/path/filepath/path.go:396 +0xe1
github.com/ncw/rclone/local.(*Fs).List.func1(0xc820154410, 0xc820508420)
	/home/ncw/Code/Go/src/github.com/ncw/rclone/local/local.go:141 +0x84
created by github.com/ncw/rclone/local.(*Fs).List
	/home/ncw/Code/Go/src/github.com/ncw/rclone/local/local.go:169 +0x64

**Comment by klauspost** [comment]
The [warned map](https://github.com/ncw/rclone/blob/master/local/local.go#L45) should have a mutex.

**Comment by ncw** [comment]
This is fixed now - you can find a beta to test here

http://pub.rclone.org/v1.28-7-ge57c440%CE%B2/

Thanks for the report

Nick

**Comment by aleritty** [comment]
Tried some times now and error didn't occur anymore.
Thank you!

**Comment by ncw** [comment]
Thanks for reporting the bug and testing the fix :-)

**Comment by trumblejoe** [comment]
Hello, I just recieved this error. Details below.

What is your rclone version (eg output from rclone -V)
rclone v1.41 -os/arch linux/amd64 -go version go1.10 

Which OS you are using and how many bits (eg Windows 7, 64 bit)
Linux lw701 4.9.0-6-amd64 #1 SMP Debian 4.9.88-1+deb9u1 (2018-05-07) x86_64 GNU/Linux

Which cloud storage system are you using? (eg Google Drive)
Google Drive for work

The command you were trying to run (eg rclone copy /tmp remote:tmp)
Plex Scan of newly created library.

Here are my mount commands, rclone cache of encrypted remote files, with gocryptfs to decrypt the local cache per recommended best practices.

rclone mount gdriveCryptCache: files/rclone/gdriveCrypt \
   --allow-other \
   --dir-cache-time 160h \
   --vfs-cache-mode=writes \
   --cache-chunk-size 10M \
   --cache-info-age 168h \
   --cache-workers 8 \
   --buffer-size 0M \
   --fuse-flag sync_read \
   --umask 000 \
   --log-level INFO \
   --log-file .tmp/gdriveCryptCache-cache.log &

gocryptfs -allow_other -ko sync "files/rclone/gdriveCrypt" "files/rclone/gdriveCryptPlain"


[gdriveCryptCache-cache.log](https://github.com/ncw/rclone/files/2164239/gdriveCryptCache-cache.log)

My logs are attached.

**Comment by ncw** [comment]
@trumblejoe thanks for reporting this.  Can you please make a [new issue on github](https://github.com/ncw/rclone/issues/new) about this with the above in - it had a completely different cause.  Thanks.
