### ISSUE TITLE
Add --delete-none option

### ISSUE THREAD

**Issue by mmmmmat** [ncw/rclone#388]
It would be cool to have a 'safe' rclone sync command that I can run on a directory, knowing that if a cat on the keyboard/randomly clicking child/virus/etc had deleted a load of local files, those files wouldn't then get deleted from the remote.

iirc, rsync requires --delete to be explicitly specified for any remote files to be removed.

Apologies if I've misread the docs and this is already possible.

**Comment by klauspost** [comment]
Isn't that just `rclone copy`, or am I misreading your request?

**Comment by mmmmmat** [comment]
Looking at it now, it seems amazing that I missed something so obvious.

How embarrassing.

**Comment by klauspost** [comment]
No problem - happens to all of us from time to time (and those who claim otherwise are lying)

**Comment by eldy** [comment]
I did the same mistakes. May be adding the option --delete just to say for ths yo umust use the "copy" command will avoid this because it is the way rsync works (option --delete). It will save a lot of time to find this --delete option...
