### ISSUE TITLE
Possible to rclone Truecrypt or Veracrypt Container

### ISSUE THREAD

**Issue by aggied** [ncw/rclone#391]
I'm interested in using rclone for incremental backups of an encrypted container from Truecrypt/Veracrypt to Amazon Cloud Drive. I'm not talking about using rclone on a mounted (decrypted) container, but on the actual encrypted container file itself. This would allow for a simple solution to have both encryption locally as well as in the offsite backup. Can't seem to find anything conclusive, but based on what I'm reading about inability to perform partial transfers, my hunch is that this will not be possible? The only way to do this would be to upload the entire container each time?

**Comment by ncw** [comment]
How are the encrypted files stored? If it is one big file then you are right. However if it is lots of smaller files (say one per file on the disk) rclone will sync that fine in an incremental way.

**Comment by aggied** [comment]
Thanks for the response @ncw . It would most likely be the former -- one big file. I am new to TrueCrypt/VeraCrypt, but unless I'm mistaken the concept of automatically encrypting/encrypting each file on disk isn't really where those tools shine. The concept is you either a) encrypt the entire partition and decrypt at boot, or b) create an encrypted "container" that gets mounted as a virtual volume after boot. Either way, the data is encrypted on disk should it fall into the wrong hands. 

I'm hoping there are some folks who might chime, but if not I'll go ahead an close this out shortly.

**Comment by ncw** [comment]
I'm going to close this now - please feel free to re-open if necessary!
