### ISSUE TITLE
S3 access fails with error "panic: interface conversion:"

### ISSUE THREAD

**Issue by helmingstay** [ncw/rclone#396]
When filing an issue, please include the following information if
possible as well as a description of the problem.

I can list my existing S3 buckets, but cannot view their contents or create a new bucket.
I get the same error in both cases:
```panic: interface conversion: interface {} is string, not *string```
I tried upgrading with "go get github.com/ncw/rclone", same issue.

> What is your rclone version (eg output from `rclone -V`)

rclone v1.27

> Which OS you are using and how many bits (eg Windows 7, 64 bit)

Linux 4.3.0-1-amd64 #1 SMP Debian 4.3.3-7 x86_64

> Which cloud storage system are you using? (eg Google Drive)

S3 (google drive works fine)

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

## working
rclone lsd remote: 
## errors
rclone lsd remote:existing_bucket
rclone mkdir remote:unique_name_here

> A log from the command with the `-v` flag (eg output from `rclone -v copy /tmp remote:tmp`)

[working.txt](https://github.com/ncw/rclone/files/179146/working.txt)
[lsd.txt](https://github.com/ncw/rclone/files/179147/lsd.txt)
[mkdir.txt](https://github.com/ncw/rclone/files/179148/mkdir.txt)

**Comment by helmingstay** [comment]
I did not realize a vanilla ```go get``` did not upgrade.
Used  ```go get -u github.com/ncw/rclone``` to upgrade to 1.28, working fine now.

**Comment by ncw** [comment]
Glad you sorted it. 

Nick
