### ISSUE TITLE
drive: increase chunk size and document

### ISSUE THREAD

**Issue by canonlp** [ncw/rclone#397]
rclone version: 1.28

I have a 1gbps line but my upload to Google Drive seems to fluctuate between 700KBPS - 5MBPS. Is this the speed most people are getting? Is there a way to increase the speed and use all my available bandwidth or is this part of GDrive's limit? This is for single file operations.

**Comment by ncw** [comment]
At work where we have a 1 Gbit/s connection, I can get 2-300 Mbit/s transfers on big files.

I suspect you are probably transferring lots of relatively small files?  Google drive has some heavy duty rate limiting which limits uploads to about 2 per second.

You can try increasing `--transfers` to see if that helps.

Also you might get more speed if you try the latest beta which has some tweaks for google drive in

http://pub.rclone.org/v1.28-9-g9dccf91%CE%B2/

**Comment by canonlp** [comment]
No, I am usually transferring only 1 file at a time. Anywhere from 500mb to 5gb. So they're not small files. I'll try the --transfers and the beta version.

**Comment by canonlp** [comment]
I tried using the beta version, when I get the version number, does it list out 1.28-9?

**Comment by ncw** [comment]
Interesting...  Note that rclone will buffer that 128M in memory and by default will do 4 transfers at once, so that will take 0.5GB of memory.

Would you mind seeing how small a chunksize gives the most significant improvement? I might change the default, but 128M is too big for the default.

Thanks

Nick

**Comment by canonlp** [comment]
I've tested out on a 1gb file. Just for fun, I made the chunk size even larger to see what gains are to be had. Seems like 256M is the sweet spot for me with the most improvement. Note: I am only transferring 1 file at a time so 256mb of memory is fine for my system. 

| Chunk Size  | Current Speed @ 10s (kByte/s)  |  Avg Speed On Completion (kByte/s) |  Elapsed Time |
|:-:|---|---|---|
| 16M  | 30188.9  | 26586.0  | 40.7s  |
| 32M  | 40300.7  | 34474.6  | 33.3s  |
| 64M  | 53506.6  | 40354.4  | 29.2s  |
| 128M  | 91145.3  | 45579.3  | 27.9s  |
|  256M  | 123024.5  | 54203.9  | 24.6s  |
|  512M  | 113839.6  | 53992.4  | 26.3s  |

**Comment by ncw** [comment]
I did a few more tests and it looks like the bigger the buffer, the faster the transfer!  Google also recommends increasing the chunk size to as large as possible.

I don't want to increase the default memory usage of rclone too much, so I propose to make the default chunk size 8 MB and write a note in the docs that if you are transferring large files then bigger is better!

![drive-speed](https://cloud.githubusercontent.com/assets/536803/14474109/379b642e-00f3-11e6-80c1-7aacaea7f197.png)

**Comment by kennyparsons** [comment]
@ncw If I dont have gig speeds, would I need to keep my chunk size below my upload speed for optimal performance?

**Comment by ncw** [comment]
> If I dont have gig speeds, would I need to keep my chunk size below my upload speed for optimal performance?

I can't make a simple recommendation - you'll have to experiment. Usually bigger chunk size makes it faster up to some point where it saturates. Exactly what that point is for you I don't know.

For Gig speeds you'll probably want a chunk size of 32M minimum.

**Comment by rahulroy9202** [comment]
Does this have any impact on download speeds?

**Comment by ncw** [comment]
This has no effect on download speeds.
