### ISSUE TITLE
Tidy LimitedFs creation

### ISSUE THREAD

**Issue by ncw** [ncw/rclone#398]
Return a sentinel error from NewFs - ErrorIsAFile rather than putting the logic to create a LimitedFs into every Fs.

This will make each Fs simpler at the expense of more operations.  However the LimitedFs idiom isn't commonly used on remotes and is very inflexible.

**Comment by klauspost** [comment]
Good idea.

**Comment by ncw** [comment]
Done in 1a87b693765522cf9abf99ef1c20a9d1549bba18
