### ISSUE TITLE
config: Authentication redirect is wrong when adding the second backend.

### ISSUE THREAD

**Issue by klauspost** [ncw/rclone#402]
It appears there is an issue when re-starting a web server in Go, where old ServeMux functions are used when restarting a server.

I have filed this issue: https://github.com/golang/go/issues/14927

This means that if you add two different backends, the server will redirect to the authURL of *first* server. For instance, if you add an ACD and then a Drive backend, the Drive authentication will redirect you to the ACD authentication page.

I have tried "clean" ways of fixing this, but I cannot make anything work consistently. The only "sort-of" solution I can come up with is to keep the server running and update the authURL.

**Comment by klauspost** [comment]
You are awesome @ncw -  adding `w.Header().Set("Connection", "close")` fixes the issue.

I will submit a PR shortly.

**Comment by ncw** [comment]
This is fixed in f8101771c96047442f8f9a7c38c5eb9ec0f1648d - thanks Klaus.
