### ISSUE TITLE
--retries 1 --low-level-retries 1, Sends the file twice on failure. Expected behavior would be send only once.

### ISSUE THREAD

**Issue by justusiv** [ncw/rclone#406]
1.28 Linux 64bit
Amazon Cloud drive using command
rclone upload --retries 1 --low-level-retries 1 source dest 
I am receiving lots of known errors(408) because of the delays of ACD. The files make it there after a delay so i only want to send the file once to save bandwidth. Even with those retries set to 1, it receives the error and sends the file a second time.

**Comment by ncw** [comment]
Probably an off-by-one error in the acd pacer would be my guess..

**Comment by klauspost** [comment]
Unless I am misreading your post, it seems to do what you ask it. It does one "try", and one "re-try", so it will try two times in total.

**Comment by justusiv** [comment]
Does it do low-level-retries automatically? I basically want this option disabled for my runs. With the 408 error the file gets to the location just fine just a few minutes late showing up.

**Comment by ncw** [comment]
The retries option should really be called tries so set to 1 should mean 1 try.

That was my intention too with the low-level-retries flag, but something has gone wrong somewhere!

**Comment by ncw** [comment]
The fix for this will be in the 1.30 release which will be shortly!
