### ISSUE TITLE
add AuthVersion to swift configuration

### ISSUE THREAD

**Issue by mikeifomin** [ncw/rclone#407]
I recently tried to connect one of the opanstack provider `AuthUrl` == https://auth.selcdn.ru/ (no auto detect version in URL)
So rclone trace me an error:
```
Can't find AuthVersion in AuthUrl - set explicitly
```

But there is no way to set `AuthVersion` from rclone explicitly.

**Comment by ncw** [comment]
Well spotted.  When I've fixed this I'll link a beta for you to try.

**Comment by ncw** [comment]
I've fixed this now.

Here is a beta with the fix: http://pub.rclone.org/v1.29-41-g1fce83b%CE%B2/

Please re-open if it doesn't work!

Thanks

Nick
