### ISSUE TITLE
Require Go 1.5 for compilation

### ISSUE THREAD

**Issue by klauspost** [ncw/rclone#408]
It seems the `google.golang.org/cloud` package now requires Go 1.5, otherwise this error is reported `google.golang.org/cloud/compute/metadata/metadata.go:191: req.Cancel undefined (type *http.Request has no field or method Cancel)`.

Should we add it to the docs and remove 1.4 from the Travis CI?

Furthermore, we could add a file with a build guard which produces an error message. That should reduce the support required for this issue in the future.
```Go
//+build !go1.5

package main

// Upgrade to Go version 1.5 to compile.
func init() { Go_version_1_5_required_for_compilation() }
```

Produces:

```
$go build
# github.com/ncw/rclone
.\version.go:6: undefined: Go_version_1_5_required_for_compilation
```

**Comment by ncw** [comment]
Nice idea - let's do that :-)

I think supporting 2 go versions should be our minimum ambition.
