### ISSUE TITLE
feature request: an option to delete duplicates during sync

### ISSUE THREAD

**Issue by benfry** [ncw/rclone#41]
With the new "duplicate file found" message, can we have a command line option to delete these duplicates as they're found? 

Apologies if I've just missed this in the documentation—I didn't see anything there.

**Comment by ncw** [comment]
Good idea!  I'll see if I can add a flag to do this.

**Comment by benfry** [comment]
Oh, I dunno—start anywhere. I've got 8 or 9 or a dozen of 'em in some cases. 

(I kid, I kid... I fully understand the delicacy of this sort of thing.) 

Thanks for considering it.

**Comment by juniormonkey** [comment]
If they're truly duplicates (identical filename, hash, creation time, etc) does it matter which gets deleted?

**Comment by ncw** [comment]
@juniormonkey good point!

**Comment by stickenhoffen** [comment]
Just stumbled on this, I too am seeing some duplicates. Would be great to have this feature.

Thanks.

**Comment by gustavorochakv** [comment]
Adding a +1 on this. I'm using rclone to transfer a couple of very large directories (a few TB in total, distributed over hundreds of thousands of files) on Google Drive, and that led to thousands of duplicate files.
This is only getting worse over time, since our cron job adds a few dozen additional duplicates every day.
If our Google Drive plan did not have unlimited storage, this would be a pretty serious issue.

**Comment by calisro** [comment]
The only thing I will say is they are not true duplicates. @juniormonkey   Mine had different md5, sizes in some cases, and dates.  I agree with an option to do it but care as to how to select the one to delete needs to be thought about.

**Comment by ncw** [comment]
I have made the dedupe command which you can try in this beta

http://pub.rclone.org/v1.26-51-g3101a7f%CE%B2/

### rclone dedupe remote:path ###

Interactively find duplicate files and offer to delete all but one or
rename them to be different. Only useful with Google Drive which can
have duplicate file names.

```
$ rclone dedupe drive:dupes
2016/01/31 14:13:11 Google drive root 'dupes': Looking for duplicates
two.txt: Found 3 duplicates
  1:       564374 bytes, 2016-01-31 14:07:22.159000000, md5sum 7594e7dc9fc28f727c42ee3e0749de81
  2:      1744073 bytes, 2016-01-31 14:07:12.490000000, md5sum 851957f7fb6f0bc4ce76be966d336802
  3:      6048320 bytes, 2016-01-31 14:07:02.111000000, md5sum 1eedaa9fe86fd4b8632e2ac549403b36
s) Skip and do nothing
k) Keep just one (choose which in next step)
r) Rename all to be different (by changing file.jpg to file-1.jpg)
s/k/r> r
two-1.txt: renamed from: two.txt
two-2.txt: renamed from: two.txt
two-3.txt: renamed from: two.txt
one.txt: Found 2 duplicates
  1:         6579 bytes, 2016-01-31 14:05:01.235000000, md5sum 2b76c776249409d925ae7ccd49aea59b
  2:         6579 bytes, 2016-01-31 12:50:30.318000000, md5sum 2b76c776249409d925ae7ccd49aea59b
s) Skip and do nothing
k) Keep just one (choose which in next step)
r) Rename all to be different (by changing file.jpg to file-1.jpg)
s/k/r> k
Enter the number of the file to keep> 2
one.txt: Deleted 1 extra copies
```

The result being

```
$ rclone lsl drive:dupes
   564374 2016-01-31 14:07:22.159000000 two-1.txt
  1744073 2016-01-31 14:07:12.490000000 two-2.txt
  6048320 2016-01-31 14:07:02.111000000 two-3.txt
     6579 2016-01-31 12:50:30.318000000 one.txt
```
