### ISSUE TITLE
Password prompt syntax

### ISSUE THREAD

**Issue by leighklotz** [ncw/rclone#410]
It would be nice if the password prompt ended with a ":" instead of a ">" so that expect scripts and other tools (e.g. emacs) could recognize that it's a password and not echo.

Change
		fmt.Print("password>")
to
		fmt.Print("password:")

or make this configurable.

**Comment by klauspost** [comment]
I've got no strong feeling about it, so I added a PR.

**Comment by ncw** [comment]
Sorry, late to the party!  Yes a prompt ending in `:` seems to be the unix standard.

@leighklotz can you submit your pull request to this repo.  Note that you only need to change the markdown docs as the other docs are auto generated.
