### ISSUE TITLE
--no-recurse or --recurse flag

### ISSUE THREAD

**Issue by lickdragon** [ncw/rclone#412]
Hello!
   It would be nice to provide the ability to not recurse into subdirectories while copying files.
   The problem I'm having is that I ask rclone to copy a local directory, let's say it is empty, to a remote directory of the same name, which has lots and lots of subdirectories and files.
   Instead of just copying over nothing and exiting, rclone proceeds to list all the remote subdirs and files first.
   With rsync, the default behavior is to not recurse without the -r flag.  But with rclone the behavior is to recurse by default.  So I'm hoping for either a --no-recurse or --recurse flag, depending on what you want the default behavior to be .  :)
   This might be related to #395 .

Thanks for the nice tool!
C.

rclone version 1.28
Debian 64-bit
Google Drive

**Comment by ncw** [comment]
Soon I'll add a max depth command line argument which will fix this :-) 

Also note the bugs section in the manual which mentions this specifically!

**Comment by lickdragon** [comment]
Thanks for pointing out the bugs section and the eventual maxdepth command!
C.
