### ISSUE TITLE
Hi i would like to have acl:public  , private in s3 like while storing object in s3 bucket it should be private ,while reading bucket should be public

### ISSUE THREAD

**Issue by venkatnaidu** [ncw/rclone#413]
When filing an issue, please include the following information if
possible as well as a description of the problem.

> What is your rclone version (eg output from `rclone -V`)

> Which OS you are using and how many bits (eg Windows 7, 64 bit)

> Which cloud storage system are you using? (eg Google Drive)

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

> A log from the command with the `-v` flag (eg output from `rclone -v copy /tmp remote:tmp`)

**Comment by venkatnaidu** [comment]
rclone v1.28 
OS:ubuntu 64 bit 
Cloud Storage:S3

**Comment by ncw** [comment]
So you mean only you can write to the bucket but anyone can read? 

Rclone can't do that at the moment but you can do it externally,  eg

http://havecamerawilltravel.com/photographer/how-allow-public-access-amazon-bucket

Is this something you need to do once or many times?

**Comment by venkatnaidu** [comment]
Yes exactly writing to bucket should be private and anyone can read it without write option except the admin. i'm uploading some pics data it should be access through url like publishing

**Comment by ncw** [comment]
I think doing this is probably out of scope for rclone, but if anyone sends a PR I'll look kindly upon it!
