### ISSUE TITLE
configuration of a new S3 remote requires region selection, but my buckets have no region

### ISSUE THREAD

**Issue by garypaduana** [ncw/rclone#414]
> What is your rclone version (eg output from `rclone -V`)
1.28

> Which OS you are using and how many bits (eg Windows 7, 64 bit)
OSX 10.11.2

> Which cloud storage system are you using? (eg Google Drive)
Amazon S3

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
`rclone -v ls M_S3:rpmhost`

> A log from the command with the `-v` flag (eg output from `rclone -v copy /tmp remote:tmp`)

    gary-macbook:~ garypaduana$ rclone -v ls M_S3:rpmhost
    2016/03/31 13:29:42 S3 bucket rpmhost: Modify window is 1ns
    2016/03/31 13:29:42 S3 bucket rpmhost: Couldn't read bucket "rpmhost": BucketRegionError: incorrect region, the bucket is not in 'us-east-1' region
        status code: 301, request id:

    Transferred:            0 Bytes (   0.00 kByte/s)
    Errors:                 1
    Checks:                 0
    Transferred:            0
    Elapsed time:       400ms

    2016/03/31 13:29:42 Go routines at exit 4

![s3](https://cloud.githubusercontent.com/assets/4510602/14190102/d0ac8aec-f745-11e5-8cf3-5d3e802f46c8.png)

How should I configure the remote to use the global region?  Even without the region specified in the config, it defaults to `us-east-1` at runtime.

    [M_S3]
    type = s3
    env_auth = false
    access_key_id = <value>
    secret_access_key = <value>
    region = us-east-1
    endpoint =
    location_constraint =

**Comment by ncw** [comment]
As far as I know there isn't a global region in s3 eg - http://docs.aws.amazon.com/general/latest/gr/rande.html#s3_region

So I suspect  the bucket was created  in a different region to us-East-1 (which is the default). 

You could try some likely candidates to see what happens. (I can't find an easy way to discover which region a bucket is in!) 

I hope that helps 

Nick

**Comment by garypaduana** [comment]
Nick,
Thank you for that suggestion.  It turns out the bucket was located in `us-west-2`.  It's interesting how the S3 web UI shows global instead of defining which region is actually being used.  Sorry for not exhausting all options before opening this issue.

**Comment by ncw** [comment]
No worries, glad I could help.
