### ISSUE TITLE
Move command deletes source diretory

### ISSUE THREAD

**Issue by mongo-56** [ncw/rclone#416]
When issuing a move command, after completion it deletes the source directory, is there a way to leave the source directory in place and just move its contents?

for example I have _/home/user/files/_ and that directory contains two files, _/one.txt_ and _/two.txt_ and I only want to move the .txt files to the remote directory, not the _/files/_ directory.

At the moment I am using the move command, 

`rclone move /home/user/files/ remote:directory/`

This creates _remote:/directory/one.txt_ and _/two.txt_ but it removes the source directory _/files/_.
Is there a way to copy and then delete or move just the .txt files from the source directory without deleting it
?
> What is your rclone version (eg output from `rclone -V`)

rclone v1.28

> Which OS you are using and how many bits (eg Windows 7, 64 bit)

Linux (Ubunut 15.10 Server)

> Which cloud storage system are you using? (eg Google Drive)

Amazon Cloud Storage

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

rclone move /home/user/files/ remote:directory/

> A log from the command with the `-v` flag (eg output from `rclone -v copy /tmp remote:tmp`)

**Comment by mongo-56** [comment]
After reading the documentation a little more, I found the following;

move source:path dest:path

> Moves the source to the destination.
> 
> If there are no filters in use this is equivalent to a copy followed by a purge, but may using server side operations to speed it up if possible.
> 
> If filters are in use then it is equivalent to a copy followed by delete, followed by an rmdir (which only removes the directory if empty). The individual file moves will be moved with srver side operations if possible.
> 
> Important: Since this can cause data loss, test first with the –dry-run flag. 

Is there anyway to execute the move command without the `rmdir` at the end?

**Comment by mongo-56** [comment]
Because I want this to work as a cronjob, I have found a work around, for the ease of use I have created a simple bash script that cron calls every 6 hours.

```
#!/bin/bash

#Move the files to the cloud
rclone move --transfers=10 /home/user/files/ remote:directory/ &&

#If successful, check if directory exists, if not create it
mkdir -p /home/user/files/ 
```

This fixes my problem.

**Comment by ncw** [comment]
You've arrived at the solution I would recommend :-)

You could use `rclone mkdir /home/user/files/` if you wanted instead of the `mkdir -p`
