### ISSUE TITLE
Google Drive - uploaded docx files appears as archives 

### ISSUE THREAD

**Issue by mdalacu** [ncw/rclone#417]
Hi, i have synct a lot of office files with this very useful tool. All the docx files appears as archive/zip file. I thik it is related with setting the mime type.
I have found an similar problem with another sync tool.( https://github.com/odeke-em/drive/issues/154 )
I am using rclone v1.28 - 2016-03-01 on a Windows Server 2012R2
Thank you.

**Comment by ncw** [comment]
rclone uses [the TypeByExtension function](https://golang.org/pkg/mime/#TypeByExtension) to turn an extension into a mime type.

If I try this on my linux machine it works perfectly, setting the correct mime type `"mimeType":"application/vnd.openxmlformats-officedocument.wordprocessingml.document"`

On windows this uses the registry to work out the mime type.

Does the server that you uploaded the docs from have Word installed on it? I suspect it doesn't know the mime type for `docx` documents.  Maybe if you installed the free Word viewer that would help?

**Comment by mdalacu** [comment]
Yes, you are right. I do not have MS Office installed on that server and i will never have it...expensive shit :-)))
Now, what can i do?
Thank you for your quick reply.

**Comment by mdalacu** [comment]
Still no go...
I have installed Libre Office 5.1.1 and have made all the file associations. In the registry they look ok.
What is strange is that some of the uploaded files do have the correct type associated for both .docx and .xlsx. All the doc or xls file are ok. Maybe the query for the file type from registry some time fails?
Thx.

**Comment by mdalacu** [comment]
I have a lot of duplicated files....runing dedupe now.

**Comment by ncw** [comment]
I have figured out what is going on I think - it is when a `.docx` file gets updated that the mime type gets corrupted.

To verify
  1. upload `test.docx`
  2. edit `test.docx`
  3. upload it again - at this point it will change to a zip

Here is a beta with a fix.  It won't fix any files you've uploaded already unfortunately but it should fix the problem in the future.

http://pub.rclone.org/v1.28-23-g6cc9c09%CE%B2/

**Comment by ncw** [comment]
Feel free to re-open if this doesn't fix your problem!

Thanks

Nick

**Comment by mdalacu** [comment]
Thanks, i will test the beta tomorrow.
The problem is that i have erased everything forom GDrived because of duplicate files problem and uploaded a fresh copy of files using rclone sync. The mime type was unknown for all the docx files. Maybe it is something on my side...but i don't know what. 
I will post tomorrow the test result. Thanks again.

**Comment by mdalacu** [comment]
I have tested it and the same result ...file type unknown.
I have uploaded a docx file with Google Drive web page from latest Firefox...same result...file type unknown. If i upload the same file from another computer all is ok.
So there is something wrong on my side...if you have any idea how i can address this fell free to tell me. I am pulling my hair out already :-)

**Comment by ncw** [comment]
Did you try installing the word viewer to see if that gets the mime type correct?

https://support.microsoft.com/en-us/kb/891090

Also there is a small program you can try [here](http://pub.rclone.org/mimetype.zip) which will print the mimetype the same way rclone does it.  Pass it a docx file and see what it prints.

```
> mimetype.exe z.docx
".docx" is "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
```

That is what it should print!

**Comment by dav1303** [comment]
Hi

You need to install word / excel and power point viewer.

That solves your issue

Regards

**Comment by mdalacu** [comment]
Hi this is my output for mimeype.exe
`".docx" is "application/vnd.openxmlformats-officedocument.wordprocessingml"` so...missing .document, but in another app like "FileTypesMan" it lists the entry s above but , "percived as document."
That word viewer is for old formats ,doc, not docx.
I am stuck.

**Comment by ncw** [comment]
Thanks for trying that binary.  Odd result!

You need to install a viewer which can view `.docx` files I think.

According to https://support.microsoft.com/en-us/kb/891090 you need the word viewer and the Microsoft Office Compatibility Pack for Word, Excel, and PowerPoint 2007 and later versions' file formats which you can get from here: http://www.microsoft.com/downloads/details.aspx?familyid=941B3470-3AE9-4AEE-8F43-C6BB74CD1466&displaylang=en

**Comment by mdalacu** [comment]
Thank you, i can confirm that installing wordviewer and compatibility pack as described by **ncw** solves my issue. Now, all the files uploads with the correct type. Thank you all for this.
Regards.
Marius.

**Comment by ncw** [comment]
Great!  I think what I'll do is put this in the FAQ so if anyone has this problem in the future they will know what to do.
