### ISSUE TITLE
rclone check appears to not recognize --size-only option (does sum check)

### ISSUE THREAD

**Issue by jpercyasnet** [ncw/rclone#419]
When filing an issue, please include the following information if
possible as well as a description of the problem.

> What is your rclone version (eg output from `rclone -V`) v1.28

> Which OS you are using and how many bits (eg Windows 7, 64 bit) Linux 64bit (Linuxmint)

> Which cloud storage system are you using? (eg Google Drive) Amazon Cloud Drive, but using fuse; so it appears as a local drive

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`) rclone --size-only check source dest.

> A log from the command with the `-v` flag (eg output from `rclone -v copy /tmp remote:tmp`) not much information except I do not have a .rclone.conf file.
just installed the program and ran the check but very slow, because it appears to be doing the MD5SUM check (which I do not want it to do).

**Comment by ncw** [comment]
Yes this looks like a bug!  It is easy to fix - I'll post a beta for you to try a bit later.

**Comment by ncw** [comment]
Here is a beta with the fix in: http://pub.rclone.org/v1.28-27-g0f8e7c3%CE%B2/

Have a go and re-open the ticket if you find any problems

Thanks

Nick

**Comment by jpercyasnet** [comment]
Tested the beta version and the check went super fast.
