### ISSUE TITLE
Google Drive client vs. rclone

### ISSUE THREAD

**Issue by rtg20** [ncw/rclone#421]
Hi, the Google Drive client was giving me grief (kept crashing) so I used the latest rclone on Server 2012 to upload some files to Google Drive. It seemed to work ok. 

I left rclone for ~2.5 days. Then I killed it (Ctrl-C), and tried the Google Drive client again. I hoped that rclone would help the Google Drive client 'catch up'.

What's happening instead is that the Google Drive client is downloading a bunch of files from Google Drive that didn't change!

Does anyone know what's going on? It's like rclone changed something subtle with the files?

thanks!

**Comment by ncw** [comment]
The only thing that I can think of is that rclone set the modification time.

Conjecture
  * drive client uploads the file but doesn't set the modification time
  * rclone then sets the modification time (which you can do without uploading the file again)
  * drive client then thinks the file has changed and downloads it again.

This is just a guess - I haven't used the drive client and I don't know how it works!

**Comment by rtg20** [comment]
Sounds plausible. Thanks for the reply.
Is there a way to disable rclone changing the modification time?

Thanks

Richard

**Comment by ncw** [comment]
Using `--checksum` or `--size-only` will stop this. Check the docs to see what those do: http://rclone.org/docs/

**Comment by rtg20** [comment]
I'll try it. Thanks so much.

**Comment by ncw** [comment]
I'm going to close this now - please re-open or open a new ticket if you need anything else!

**Comment by rtg20** [comment]
Been thinking about this...I was using the checksum like you suggested and it works, but it slows things down. I think I will drop that option though since I completely stopped using the Google Drive client.

However, is there a way to stop rclone changing the modification time, without using checksum or size-only?

thanks!

**Comment by ncw** [comment]
No there isn't.  I could make a flag - fancy making a new ticket with that suggestion?

**Comment by rtg20** [comment]
ok done, #511.

thanks!
