### ISSUE TITLE
improve efficiency of copy command for single files

### ISSUE THREAD

**Issue by hashbackup** [ncw/rclone#422]
I'm developing a backup program, HashBackup, that can send backup files to destinations.  After a customer wrote in to say he was going to use rclone to sync his backup to ACD (not directly supported by HB), I realized I could write an HB shell destination script to use rclone for send, get, and rm operations.  It just uses the copy and delete operations on single files, by using --include <filename> (implying exclude everything else).  It works great, and is easy to setup.  Thanks!

But when copying a single file, either from local-to-remote, or remote-to-local, rclone reads the entire remote object list.  It seems like for local-to-remote copy, rclone only needs to build the local list of files and check them against the remote.  (I will try -I when it's released; I'd rather it didn't do any remote checks and just transfer the file.)  For remote-to-local copy, it seems like rclone would only need to traverse the remote object list if there are wildcards involved in the filter list.  For a simple --include <filename> that isn't a wildcard, it could just copy the one file and be done.

Here is a remote-to-local copy:

Running command: rclone -v  --no-gzip-encoding --include DESTID copy b2:hashbackup /home/jim/hb/tmpbGxzl1.b2
2016/04/05 20:18:26 B2 bucket hashbackup: Modify window not supported
2016/04/05 20:18:26 Local file system at /home/jim/hb/tmpbGxzl1.b2: Building file list
(below files are all on B2, not local)
2016/04/05 20:18:28 arc.0.0: Excluded from sync (and deletion)
2016/04/05 20:18:28 arc.1.0: Excluded from sync (and deletion)
2016/04/05 20:18:28 dest.db: Excluded from sync (and deletion)
2016/04/05 20:18:28 hb.db.0: Excluded from sync (and deletion)
2016/04/05 20:18:28 hb.db.1: Excluded from sync (and deletion)
2016/04/05 20:18:28 test/arc.0.0: Excluded from sync (and deletion)
2016/04/05 20:18:28 test/arc.0.1: Excluded from sync (and deletion)
2016/04/05 20:18:28 test/arc.0.10: Excluded from sync (and deletion)
2016/04/05 20:18:28 test/arc.0.12: Excluded from sync (and deletion)
2016/04/05 20:18:28 test/arc.0.2: Excluded from sync (and deletion)
2016/04/05 20:18:28 test/arc.0.3: Excluded from sync (and deletion)
2016/04/05 20:18:28 test/arc.0.4: Excluded from sync (and deletion)
2016/04/05 20:18:28 test/arc.0.6: Excluded from sync (and deletion)
2016/04/05 20:18:28 test/arc.0.7: Excluded from sync (and deletion)
2016/04/05 20:18:28 test/arc.0.9: Excluded from sync (and deletion)
2016/04/05 20:18:28 test/arc.1.0: Excluded from sync (and deletion)
2016/04/05 20:18:28 test/hb.db.0: Excluded from sync (and deletion)
2016/04/05 20:18:28 Local file system at /home/jim/hb/tmpbGxzl1.b2: Waiting for checks to finish
2016/04/05 20:18:28 Local file system at /home/jim/hb/tmpbGxzl1.b2: Waiting for transfers to finish
2016/04/05 20:18:29 DESTID: Copied (new)

Here is a local-to-remote copy:

Running command: rclone -v  --include DESTID copy /home/jim/hb/tmppkcpii.b2 b2:hashbackup
2016/04/05 20:19:59 B2 bucket hashbackup: Modify window not supported
2016/04/05 20:20:00 B2 bucket hashbackup: Building file list
2016/04/05 20:20:02 arc.0.0: Excluded from sync (and deletion)
2016/04/05 20:20:02 arc.1.0: Excluded from sync (and deletion)
2016/04/05 20:20:02 dest.db: Excluded from sync (and deletion)
2016/04/05 20:20:02 hb.db.0: Excluded from sync (and deletion)
2016/04/05 20:20:02 hb.db.1: Excluded from sync (and deletion)
2016/04/05 20:20:02 test/arc.0.0: Excluded from sync (and deletion)
2016/04/05 20:20:02 test/arc.0.1: Excluded from sync (and deletion)
2016/04/05 20:20:02 test/arc.0.10: Excluded from sync (and deletion)
2016/04/05 20:20:02 test/arc.0.12: Excluded from sync (and deletion)
2016/04/05 20:20:02 test/arc.0.2: Excluded from sync (and deletion)
2016/04/05 20:20:02 test/arc.0.3: Excluded from sync (and deletion)
2016/04/05 20:20:02 test/arc.0.4: Excluded from sync (and deletion)
2016/04/05 20:20:02 test/arc.0.6: Excluded from sync (and deletion)
2016/04/05 20:20:02 test/arc.0.7: Excluded from sync (and deletion)
2016/04/05 20:20:02 test/arc.0.9: Excluded from sync (and deletion)
2016/04/05 20:20:02 test/arc.1.0: Excluded from sync (and deletion)
2016/04/05 20:20:02 test/hb.db.0: Excluded from sync (and deletion)
2016/04/05 20:20:02 B2 bucket hashbackup: Waiting for checks to finish
2016/04/05 20:20:02 DESTID: Sizes identical
2016/04/05 20:20:02 DESTID: Unchanged skipping
2016/04/05 20:20:02 B2 bucket hashbackup: Waiting for transfers to finish

It works great when deleting files, and doesn't list the remote directory.  This example is a little messy because B2 and Hubic are executing concurrently:

HB shell [29839] command: rm ['dest.db']
Running command: rclone -c -v  --include dest.db delete b2:hashbackup
HB shell [29843] command: rm ['DESTID']
Running command: rclone -c -v  --include DESTID delete hubic:test
HB shell [29849] command: rm ['DESTID']
Running command: rclone -c -v  --include DESTID delete b2:hashbackup
HB shell [29850] command: rm ['dest.db']
Running command: rclone -c -v  --include dest.db delete hubic:test
2016/04/05 21:04:34 B2 bucket hashbackup: Modify window not supported
2016/04/05 21:04:34 Waiting for deletions to finish
2016/04/05 21:04:35 B2 bucket hashbackup: Modify window not supported
2016/04/05 21:04:35 Waiting for deletions to finish
2016/04/05 21:04:36 Hubic: Got swift credentials (expiry 2016-04-06 16:42:50 +0200 +0200 in 13h38m13.988498139s)
2016/04/05 21:04:36 Hubic Swift container test: Modify window is 1ns
2016/04/05 21:04:36 Waiting for deletions to finish
2016/04/05 21:04:36 Hubic: Got swift credentials (expiry 2016-04-06 16:42:50 +0200 +0200 in 13h38m13.885441402s)
2016/04/05 21:04:36 Hubic Swift container test: Modify window is 1ns
2016/04/05 21:04:36 Waiting for deletions to finish

Transferred:            0 Bytes (   0.00 kByte/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:        1.8s

2016/04/05 21:04:36 Go routines at exit 4
Removed dest.db from hubic
2016/04/05 21:04:38 dest.db: Deleted

Transferred:            0 Bytes (   0.00 kByte/s)
Errors:                 0
Checks:                 1
Transferred:            0
Elapsed time:        4.3s

2016/04/05 21:04:38 Go routines at exit 6
Removed dest.db from b2
2016/04/05 21:04:38 DESTID: Deleted

Transferred:            0 Bytes (   0.00 kByte/s)
Errors:                 0
Checks:                 1
Transferred:            0
Elapsed time:        4.5s

2016/04/05 21:04:38 Go routines at exit 4
Removed DESTID from hubic
2016/04/05 21:04:40 DESTID: Deleted

Transferred:            0 Bytes (   0.00 kByte/s)
Errors:                 0
Checks:                 1
Transferred:            0
Elapsed time:        5.7s

2016/04/05 21:04:40 Go routines at exit 6
Removed DESTID from b2
All backups removed

Thanks again for an interesting tool that lets HashBackup interface with even more destinations!

**Comment by ncw** [comment]
This will get fixed shortly as part of the directory listing refactor!

**Comment by hashbackup** [comment]
Great, thanks!

On 4/6/16, Nick Craig-Wood <notifications@github.com> wrote:
> This will get fixed shortly as part of the directory listing refactor!
>
> ---
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/ncw/rclone/issues/422#issuecomment-206246622


-- 
HashBackup: easy onsite and offsite Unix backup
http://www.hashbackup.com

**Comment by ncw** [comment]
This has been fixed as part of af4ef8ad8d1dcae105138d8046d6793c89de9a7b and f6a053df6e0ec83a8a4fce9db436285d99cafba5 .

**Comment by hashbackup** [comment]
Hi Nick - I added --no-traverse, and now can copy files from local to remote without any directory listings.  That's good!

But when copying files from remote to local, rclone 1.35 is still doing a remote directory listing when it doesn't have to.  Here is a session transcript with debugging (the ... in the pathname I added for posting):
```
Running command: rclone -c -q --stats=0 -v --no-traverse --no-gzip-encoding --include hb.db.2 copy acd:test /Users/.../hbrclone/tmpWBlEYl.acd
2017/01/09 22:14:53 rclone: Version "v1.35" starting with parameters ["rclone" "-c" "-q" "--stats=0" "-v" "--no-traverse" "--no-gzip-encoding" "--include" "hb.db.2" "copy" "acd:test" "/Users/.../hbrclone/tmpWBlEYl.acd"]
2017/01/09 22:15:00 amazon drive root 'test': Modify window not supported
2017/01/09 22:15:00 amazon drive root 'test': Reading ""
2017/01/09 22:15:00 amazon drive root 'test': Finished reading ""
2017/01/09 22:15:00 arc.0.0: Excluded from sync (and deletion)
2017/01/09 22:15:00 hb.db.1: Excluded from sync (and deletion)
2017/01/09 22:15:00 DESTID: Excluded from sync (and deletion)
2017/01/09 22:15:00 arc.2.0: Excluded from sync (and deletion)
2017/01/09 22:15:00 hb.db.0: Excluded from sync (and deletion)
2017/01/09 22:15:00 dest.db: Excluded from sync (and deletion)
2017/01/09 22:15:00 hb.db.2: Copied (new)
2017/01/09 22:15:00 Go routines at exit 10
```
Is there any way I can suppress this remote directory listing?  On a large backup, say 5TB, there would be 50K 100MB arc files on the remote side.  To restore just 10 of these would require downloading 500K directory entries.

Thanks for any tips you might have!

**Comment by hashbackup** [comment]
Nevermind, looks like copyto does not do directory listings.  Thanks!

**Comment by ncw** [comment]
Or instead of doing `--include hb.db.2 copy acd:test` you could do `copy acd:test/hb.db.2` assuming I'm undersdanding what you are doing correctly.

If you want to avoid directory traversals using more than one file, then use the `--files-from` option.
