### ISSUE TITLE
"Error 400: Media type 'SKP' is not supported" when uploading sketchup files to Google Drive

### ISSUE THREAD

**Issue by gustavorochakv** [ncw/rclone#424]
When trying to upload SketchUp files (.skp) to Google Drive the upload fails with the following error message:
`Failed to copy: googleapi: Error 400: Media type 'SKP' is not supported. Valid media types: [*/*], badContent`

This happens on rclone 1.28 running on Windows 7, it was working fine on rclone 1.27 running on Linux (I haven't been able to test whether this happens on rclone 1.28 on Linux or of it works on 1.27 on Windows).
The rclone command used on both cases was `rclone sync`

The error does not happen when uploading SketchUp backup files (.skb), which are essentially .skp files with a different extension.

The Windows computer uploading the file does have SketchUp installed with the proper filetype associations. The Linux computer that successfully uploaded these files did not have SketchUp installed.

**Comment by ncw** [comment]
Can you download this little program: http://pub.rclone.org/mimetype.zip

and run it with a sketchup file as a parameter on the windows computer

It should print out the mime type that Windows thinks `.skp` files are.

I suspect it is going to print out `SKP` which isn't a valid mime type.  I think what the message from google means is that it doesn't have a `/` in.

I can put a work-around in to just revert to `application/octet-stream` if there isn't a `/` in the mime type.

**Comment by gustavorochakv** [comment]
You're right, the output is `".skp" is "SKP"`
I also ran the program on other Windows boxes with SketchUp installed, the output is always the same.
On Windows PCs without SketchUp installed the output is `" .skp" is ""`.

A workaround for invalid mime types would be a good, on the meantime I'll just change the mimetype in the registry for a valid option on this particular machine.

**Comment by ncw** [comment]
Here is a beta with the fix in: http://pub.rclone.org/v1.28-27-g0f8e7c3%CE%B2/

Have a go and re-open the ticket if you find any problems

Thanks

Nick

**Comment by gustavorochakv** [comment]
The beta worked flawlessly, thank you very much.
