### ISSUE TITLE
cross compile rclone for ppc854x

### ISSUE THREAD

**Issue by wpicco** [ncw/rclone#425]
Hi all,
I'm trying to install rclone on my synology NAS, that is pretty old (DS408, that means 8 years old), but works like a charm.
It is equipped with a Freescale mpc8543 PPC Processor (also referred as ppc854x). 

I realized that I have to build rclone from source, perhaps cross compiling it starting from a standard linux box?
No idea about the steps, I downloaded the rclone source, and I was expecting to go through the usual configure / make / make install, but the instructions are saying to use gox.
Can someone share some light on how to cross compile? I saw an executable called "cross-compile" within the source files, but I don't know how to specify the parameters for the ppc854x...

Sorry if some of this does not make sense...I'm not an expert and I'm looking for some advice.
Thanks! 
Walter

**Comment by ncw** [comment]
Assuming that this is either a ppc64 or  ppc64le (64-bit PowerPC big- and little-endian) chip, then you are in luck, provided it is running linux 2.6.23 or later.

As for how to cross compile, first set up a go enviroment (on windows/mac/linux it doesn't matter).  See: https://golang.org/doc/install

You will also need git installed.

Here are some instructions for linux/mac - not sure exactly how env vars work on windows.

Make sure GOPATH is set, eg

    export GOPATH=~/bin/go

    go get github.com/ncw/rclone
    cd $GOPATH/src/github.com/ncw/rclone

Now for the cross compile bit

    GOOS=linux GOARCH=ppc64 go build

This will make an rclone binary in the current directory.  Try ppc64le also if you don't know exactly which one to try.

**Comment by wpicco** [comment]
Will try!
Thank you very much!

Walter
