### ISSUE TITLE
rclone v1.28 on ARM (Western Digital NAS)

### ISSUE THREAD

**Issue by fparnigoni** [ncw/rclone#426]
[rclone_err.txt](https://github.com/ncw/rclone/files/208682/rclone_err.txt)

rclone version: 1.28
OS: ARMv7l  (on Western Digital NAS)
# uname -a

Linux NasWD 3.2.26 #1 SMP Thu Jul 9 11:14:15 PDT 2015 wd-2.4-rel armv7l GNU/Linux
The command: GOTRACEBACK=system rclone config

**Comment by ncw** [comment]
Thanks for sending that.  I'm not having much luck working out what is going on though!

Can you try downloading the go compiler from https://storage.googleapis.com/golang/go1.6.linux-armv6l.tar.gz and see if that works?  Just run the go binary with no arguments and see if it prints something sensible.

If the compiler does work you could try building rclone locally.

Can you also paste the result of `cat /proc/cpuinfo`.

Thanks

Nick

**Comment by fparnigoni** [comment]
Thanks for reply:

 cat /proc/cpuinfo

Processor       : ARMv7 Processor rev 1 (v7l)
processor       : 0
BogoMIPS        : 1299.25
processor       : 1
BogoMIPS        : 1292.69
Features        : swp half thumb fastmult vfp edsp neon vfpv3 tls
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x2
CPU part        : 0xc09
CPU revision    : 1
Hardware        : Comcerto 2000 EVM
Revision        : 0001
Serial          : 0000000000000000

After download (and tar ....) the go command prints:
Segmentation fault

fulvio

**Comment by ncw** [comment]
Here is a build of the tip of rclone development built with the tip of the go compiler - see if that helps!

http://pub.rclone.org/rclone-v1.28-28-g9539bbf-arm-go-tip.zip

**Comment by fparnigoni** [comment]
[rclone-v1.28-28-g9539bbf-arm-go-tip_errors.txt](https://github.com/ncw/rclone/files/215839/rclone-v1.28-28-g9539bbf-arm-go-tip_errors.txt)

The command:
GOTRACEBACK=system rclone-v1.28-28-g9539bbf-arm-go-tip config

See attached file.

Thanks
fulvio

**Comment by ncw** [comment]
Thanks for trying that - I'm going to ask for some more help on the Go developer mailing list.

I think that this is an incompatibility between the go compiler or runtime and your ARM based system, rather than anything rclone is doing.

**Comment by ncw** [comment]
It looks like this is caused by the kernel on your device being compiled with a 64k page size which isn't supported by go at the moment
  * golang/go#10180
  * golang/go#12480

There is a patch for the compiler to support this, but the compiler internals have changed a lot since then, so I couldn't apply it.

Hopefully those bugs will get fixed soon and then rclone will just start working.

**Comment by fparnigoni** [comment]
Ok, I wait for the fix
Thanks

**Comment by rmoriz** [comment]
I've a Western Digital My Cloud Mirror NAS:

```
# getconf PAGESIZE
32768
```

So looks like there are at least 3 different possible configurations in use by popular ARM devices. Still, Golang has no runtime support. :(

**Comment by rmoriz** [comment]
rclone-v1.33-linux-arm:
```runtime: kernel page size (32768) is larger than runtime page size (4096)```

**Comment by ncw** [comment]
This is a go runtime problem unfortunately :-(

I'll find the go bug report later..

**Comment by ncw** [comment]
Reading the go bug reports looks like this will be fixed for go 1.8. If I get time I'll back port the patch to go 1.7 and post a build of rclone.

**Comment by cscetbon** [comment]
Hey guys, 
any news on this ? I met the same issue with the last arm binary

**Comment by ncw** [comment]
I looked through the bugs above and it looks like the problem may be fixed in the development version of Go.

I've compiled up two versions of rclone for you all to test. There is an ARMv6 version and an ARMv7 version - it would be interesting if you could try both.

http://pub.rclone.org/rclone-v1.33-63-gace1e21-tip-arm.zip

The above was compiled with 

    go version devel +56d35d4 Sun Oct 9 00:22:59 2016 +0000 linux/amd64

**Comment by cscetbon** [comment]
@ncw I don't have the issue anymore. I'm gonna test it and tell you if anything else doesn't work. Thank you

**Comment by fparnigoni** [comment]
On my device (Western Digital NAS) the rclone-armv7 doesn't work, rclone-armv6 works properly from NAS to Dropbox, no errors found.
Nick, thank you very much.

fulvio

**Comment by ncw** [comment]
Great thanks for testing.

Go 1.8 is due to be released in Feb 2017 so rclone will support these devices officially then.  In the mean time you can use that binary, or give me a nudge on this ticket and I'll compile you a new one.

**Comment by pranspach** [comment]
1.34 has a lot of great features/fixes for crypt & mounting. Do you have a 1.34 build with Go's dev branch? 

I haven't searched around enough, but do you have build instructions that I can adapt to use Go's dev branch to build this?

**Comment by ncw** [comment]
If you install the go 1.8 beta, set GOPATH, then

    go get -u github.com/ncw/rclone

Will build it for you.

I did a beta build using `go version devel +41908a5 Thu Dec 1 02:54:21 2016 +0000 linux/amd64` which is the go 1.8 beta1.  You can find that here: http://pub.rclone.org/v1.34-48-gc24da0b%CE%B2/

**Comment by DTrace001** [comment]
Having similar issues.  Trying to get golang to compile/run on these boxes are a PITA with the 64K size. I thought the 1.8 versions were suppose to set 64k if it detected arm but not sure that is the case.

`# uname -a
Linux WDMyCloud 3.2.26 #1 SMP Thu Jul 9 11:14:15 PDT 2015 wd-2.4-rel armv7l GNU/Linux`

`# getconf PAGESIZE
65536`

Armv7 version form previous post.
```
# ./rclone-armv7
unexpected fault address 0x486bdc
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x2 addr=0x486bdc pc=0x486bdc]
goroutine 1 [running, locked to thread]:
runtime.throw(0x58c4d0, 0x5)
	/home/ncw/Code/go/src/runtime/panic.go:587 +0x70 fp=0x10b39f20 sp=0x10b39f14
runtime.sigpanic()
	/home/ncw/Code/go/src/runtime/signal_unix.go:279 +0x20c fp=0x10b39f44 sp=0x10b39f20
github.com/cpuguy83/go-md2man/vendor/github.com/shurcooL/sanitized_anchor_name.init()
	/home/ncw/Code/go/src/github.com/cpuguy83/go-md2man/vendor/github.com/shurcooL/sanitized_anchor_name/main.go:30 fp=0x10b39f48 sp=0x10b39f48
github.com/cpuguy83/go-md2man/vendor/github.com/russross/blackfriday.init()
	/home/ncw/Code/go/src/github.com/cpuguy83/go-md2man/vendor/github.com/russross/blackfriday/smartypants.go:401 +0x44 fp=0x10b39f88 sp=0x10b39f48
github.com/cpuguy83/go-md2man/md2man.init()
	/home/ncw/Code/go/src/github.com/cpuguy83/go-md2man/md2man/roff.go:283 +0x40 fp=0x10b39f8c sp=0x10b39f88
github.com/spf13/cobra/doc.init()
	/home/ncw/Code/go/src/github.com/spf13/cobra/doc/util.go:39 +0x60 fp=0x10b39f90 sp=0x10b39f8c
github.com/ncw/rclone/cmd/gendocs.init()
	/home/ncw/Code/go/src/github.com/ncw/rclone/cmd/gendocs/gendocs.go:56 +0x60 fp=0x10b39f94 sp=0x10b39f90
github.com/ncw/rclone/cmd/all.init()
	/home/ncw/Code/go/src/github.com/ncw/rclone/cmd/all/all.go:33 +0x68 fp=0x10b39f98 sp=0x10b39f94
main.init()
	/home/ncw/Code/go/src/github.com/ncw/rclone/rclone.go:19 +0x48 fp=0x10b39f9c sp=0x10b39f98
runtime.main()
	/home/ncw/Code/go/src/runtime/proc.go:172 +0x18c fp=0x10b39fc4 sp=0x10b39f9c
runtime.goexit()
	/home/ncw/Code/go/src/runtime/asm_arm.s:992 +0x4 fp=0x10b39fc4 sp=0x10b39fc4`
```
Most recent 1.34.48 
```
# ./rclone
unexpected fault address 0x586df0
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x2 addr=0x586df0 pc=0x586df0]

goroutine 1 [running, locked to thread]:
runtime.throw(0x6c3815, 0x5)
	/opt/go/go1.8/src/runtime/panic.go:596 +0x70 fp=0x10d33f94 sp=0x10d33f88
runtime.sigpanic()
	/opt/go/go1.8/src/runtime/signal_unix.go:276 +0x20c fp=0x10d33fb8 sp=0x10d33f94
main.init()
	/home/ncw/go/src/github.com/ncw/rclone/rclone.go:19 fp=0x10d33fbc sp=0x10d33fbc
runtime.main()
	/opt/go/go1.8/src/runtime/proc.go:173 +0x198 fp=0x10d33fe4 sp=0x10d33fbc
runtime.goexit()
	/opt/go/go1.8/src/runtime/asm_arm.s:1017 +0x4 fp=0x10d33fe4 sp=0x10d33fe4
```

**Comment by ncw** [comment]
@DTrace001 I've uploaded the latest rclone compiled with the latest go for you to try.

http://pub.rclone.org/rclone-v1.34-75-gcbfec0d-arm-go-tip.zip

I've also included a `hello` binary which should just print hello world.

Can you try that too please?

Assuming one or both of those fails, then please post the output for both and also the output of `cat /proc/cpuinfo`

I'm not sure whether 64k pages are supposed to be working properly for go 1.8 - I'll ask on the developer mailing list once I've got your results.

**Comment by DTrace001** [comment]
Here are the outputs you requested:

```
# getconf PAGESIZE
65536
```
```
# uname -a
Linux WDMyCloud 3.2.26 #1 SMP Thu Jul 9 11:14:15 PDT 2015 wd-2.4-rel armv7l GNU/Linux
```
```
# cat /proc/cpuinfo
Processor	: ARMv7 Processor rev 1 (v7l)
processor	: 0
BogoMIPS	: 1299.25

processor	: 1
BogoMIPS	: 1292.69

Features	: swp half thumb fastmult vfp edsp neon vfpv3 tls
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x2
CPU part	: 0xc09
CPU revision	: 1

Hardware	: Comcerto 2000 EVM
Revision	: 0001
Serial		: 0000000000000000
```
```
# ./rclone
unexpected fault address 0x5893b0
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x2 addr=0x5893b0 pc=0x5893b0]

goroutine 1 [running, locked to thread]:
runtime.throw(0x6c6c8a, 0x5)
	/opt/go/go1.8/src/runtime/panic.go:596 +0x70 fp=0x10d33f94 sp=0x10d33f88
runtime.sigpanic()
	/opt/go/go1.8/src/runtime/signal_unix.go:297 +0x20c fp=0x10d33fb8 sp=0x10d33f94
main.init()
	/home/ncw/go/src/github.com/ncw/rclone/rclone.go:19 fp=0x10d33fbc sp=0x10d33fbc
runtime.main()
	/opt/go/go1.8/src/runtime/proc.go:173 +0x198 fp=0x10d33fe4 sp=0x10d33fbc
runtime.goexit()
	/opt/go/go1.8/src/runtime/asm_arm.s:1017 +0x4 fp=0x10d33fe4 sp=0x10d33fe4
```
```
# ./hello
unexpected fault address 0x88868
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x2 addr=0x88868 pc=0x88868]

goroutine 1 [running, locked to thread]:
runtime.throw(0xa454f, 0x5)
	/opt/go/go1.8/src/runtime/panic.go:596 +0x70 fp=0x10433f94 sp=0x10433f88
runtime.sigpanic()
	/opt/go/go1.8/src/runtime/signal_unix.go:297 +0x20c fp=0x10433fb8 sp=0x10433f94
main.init()
	/home/ncw/go/src/github.com/ncw/rclone/rclone-v1.34-75-gcbfec0d-arm-go-tip/hello.go:8 fp=0x10433fbc sp=0x10433fbc
runtime.main()
	/opt/go/go1.8/src/runtime/proc.go:173 +0x198 fp=0x10433fe4 sp=0x10433fbc
runtime.goexit()
	/opt/go/go1.8/src/runtime/asm_arm.s:1017 +0x4 fp=0x10433fe4 sp=0x10433fe4
```

**Comment by ncw** [comment]
@DTrace001 thanks for that.  I'll ask on the go developers list and see if anyone has any ideas.

**Comment by DTrace001** [comment]
@ncw Thanks for looking into this !

**Comment by ncw** [comment]
I asked on the dev mailing list and they said to open an issue which I have done here: https://github.com/golang/go/issues/18408 - I'm hoping that @DTrace001 will respond to requests for more info about the hardware etc on that issue - I'm happy to continue compiling stuff if required.

**Comment by ncw** [comment]
After golang/go#18408 has been declared fixed, I've rebuild the compiler with the fix and rebuild rclone for you to have a go with.

http://pub.rclone.org/rclone-v1.35-13-ge1a49ca-arm-go-tip.zip

**Comment by kmanley** [comment]
I just tried it and it seems to work on my WD My Cloud which is also arm7 with 64k pages, thank you!

**Comment by fparnigoni** [comment]
+1
It works properly.
Thanks

**Comment by ncw** [comment]
Thanks for testing. I'll start using go 1.8 to compile rclone when it is formally released. I think this will be in time for the next rclone release if things go to plan.

**Comment by DTrace001** [comment]
Sorry for the late reply. It does work as others have already mentioned.
