### ISSUE TITLE
Display in MB's instead of kByte

### ISSUE THREAD

**Issue by sbcrumb** [ncw/rclone#428]
Is there a way I can simply display results in -v and then it is done copying in MB's instead of kBytes?
Something little more human readable?
Transferred:   193651128918 Bytes (19959.84 kByte/s)
Errors:                 1
Checks:               232
Transferred:          114
Elapsed time:  2h37m54.6s

**Comment by pmwoodward3** [comment]
+1 I would love to have this too.

**Comment by ncw** [comment]
This should be easy to do!

**Comment by HenrikBengtsson** [comment]
Note the difference between IEC and SI unit standards:

IEC: KiB (1024 bytes), MiB (1024^2 bytes), GiB (1024^3 bytes), TiB (1024^4 bytes), ...
SI: kB (1000 bytes), MB (1000^2 bytes), GB (1000^3 bytes), TB (1000^4 bytes), ...

There are lots of home-cooked alternatives out there (I'm guilty too), but the above two are the two main standards and adopted by most OSes etc.

From the example output it looks like your kByte/s is KiB/s.  If you go with KB/s, please change to base 10.

My $0.02

**Comment by ncw** [comment]
I've done this.  You can check it out in: http://pub.rclone.org/v1.29-48-ge2788aa%CE%B2/

The units are the binary units as used in the rest of rclone.
