### ISSUE TITLE
Make the difference betwen drive and google cloud storage clearer

### ISSUE THREAD

**Issue by ijaaz** [ncw/rclone#43]
Hi, I just installed rclone via AUR and followed the tutorial on rclone.org, but I seem to keep getting this error: `2015/03/25 22:29:59 Failed to copy: Can't make bucket without project number`

Would anyone know what I'm doing wrong?

Here's my rc file:

```rc
[remote]
type = google cloud storage
client_id = 
client_secret = 
project_number = 
object_acl =
bucket_acl =
token = {"AccessToken":"XXXXXXXXXXXXXXXXXXX","RefreshToken":"XXXXXXXXXXXX","Expiry":"2015-03-25T23:20:45.958816454-04:00","Extra":null}

**Comment by zeshanb** [comment]
Muhammad,

Create a client id on cloud console. You can also create a bucket there for
file storage.

login to cloud.Google.com with your gmail id.

Regards,
Zeshan

**Comment by ncw** [comment]
@mtello you said "google drive" in your subject but you have "google cloud storage" in your config file. If you want "google cloud storage" then follow @zeshanb advice, otherwise remake the remote using [these instructions](http://rclone.org/drive/) choosing "drive" as a source type

**Comment by mtello** [comment]
Thanks for all the help!!

**Comment by gwarah** [comment]
I've got the same trap. I've also selected the wrong options  "google cloud storage" because the correct was named as "drive" instead "google drive".

**Comment by zeshanb** [comment]
It's not a trap..it's a cli wizard to make it easy to configure rclone.

**Comment by gwarah** [comment]
Sure. But this wizard has a term resulting in the same misunderstanding for at last two users. I believe the word "trap" in my last post  was misinterpreted. 

Well, anyway now rclone it's working fine. I hope others users don't have our interpretation :)

**Comment by ncw** [comment]
I'll improve this in the next release - the chooser will look something like this

```
Type of storage to configure.
Choose a number from below, or type in your own value
 * Amazon Cloud Drive
 1) amazon cloud drive
 * Backblaze B2
 2) b2
 * Google Drive
 3) drive
 * Dropbox
 4) dropbox
 * Google Cloud Storage (this is not Google Drive)
 5) google cloud storage
 * Hubic
 6) hubic
 * Local Disk
 7) local
 * Microsoft OneDrive
 8) onedrive
 * Amazon S3 (also Dreamhost, Ceph)
 9) s3
 * Openstack Swift (Rackspace Cloud Files, Memset Memstore, OVH)
10) swift
 * Yandex Disk
11) yandex
```
