### ISSUE TITLE
rclone retries impossible-to-correct errors

### ISSUE THREAD

**Issue by hashbackup** [ncw/rclone#430]
Got an error from ACD that I couldn't upload anything more (403 Forbidden, NO_ACTIVE_SUBSCRIPTION), but rclone (v1.28) still retries transfers.

2016/04/10 19:14:24 arc.13.19: Excluded from sync (and deletion)
2016/04/10 19:16:45 arc.13.55: Failed to copy: HTTP code 403: "403 Forbidden", reponse body: {"logref":"4a9e4881-ff72-11e5-9b89-71496b2f065b","message":"File size exceeds account allowance.","code":"NO_ACTIVE_SUBSCRIPTION_FOUND"}
2016/04/10 19:16:45 Amazon cloud drive root 'test': Reading ""
2016/04/10 19:16:45 arc.11.4: Excluded from sync (and deletion)

**Comment by ncw** [comment]
rclone doesn't retry 403 errors from amazon directly, but if `--retries` is in effect it will retry the whole sync.

Is that what you are seeing?

**Comment by hashbackup** [comment]
Yep.  I am abusing rclone a bit, because I'm using it for single file transfers.

HashBackup also does 3 retries with backoff.  Maybe I should just
disable either HB retries or rclone high-level retries.  I set
low-level retries to 2.

Since HB doesn't get a lot of error status information from rclone
other than an exit code, what would be ideal is for HB to do no
retries and let rclone handle them all, since rclone has more details
about the error and could make better decisions about what errors to
retry and what errors are pointless to retry.

In my single-file case, a 403 shouldn't be retried.

On 4/12/16, Nick Craig-Wood <notifications@github.com> wrote:
> rclone doesn't retry 403 errors from amazon directly, but if `--retries` is
> in effect it will retry the whole sync.
>
> Is that what you are seeing?
>
> ---
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/ncw/rclone/issues/430#issuecomment-209076760


-- 
HashBackup: easy onsite and offsite Unix backup
http://www.hashbackup.com

**Comment by ncw** [comment]
rclone has the concept of errors it must retry now, so implementing this should be relatively easy.

Any takers?

**Comment by hashbackup** [comment]
Hi Nick - I would take a look at this, even though I don't know Go,
but to be honest, the throttling that companies are doing on their
"unlimited" cloud drives is the biggest problem for my users.  That
could be because HashBackup is using rclone on individual files rather
than a complete directory, not sure.

On 7/15/16, Nick Craig-Wood <notifications@github.com> wrote:
> rclone has the concept of errors it must retry now, so implementing this
> should be relatively easy.
>
> Any takers?
>
> ---
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/ncw/rclone/issues/430#issuecomment-232985947


-- 
HashBackup: easy onsite and offsite Unix backup
http://www.hashbackup.com

**Comment by ncw** [comment]
Any help much appreciated - rclone is getting quite popular and it is difficult keeping up!

I note that the new rclone v1.32 is much more efficient at copying single files which hopefully you'll find helpful.
