### ISSUE TITLE
copy command returns 0 status when file doesn't exist on remote

### ISSUE THREAD

**Issue by hashbackup** [ncw/rclone#431]
HashBackup uses the rclone copy command to fetch files from remotes, using --include filename.  If a file doesn't exist on the remote, it appears rclone is returning a zero status.  I can see how that would make sense for a sync command, but not for a copy command.

rclone 1.28, ACD, OSX

**Comment by ncw** [comment]
What you are saying is that on copy, if no files were matched then return an error.

I'm not sure I want to make that the default, but it could be a flag which would be useful for `sync`, `size` etc.

How about `--error-if-no-files` or something like that?

**Comment by hashbackup** [comment]
I worked around it by checking if the file exists after running
rclone.  I reported it in case you didn't realize it worked that way.
 Whatever you think is best.

On 4/12/16, Nick Craig-Wood <notifications@github.com> wrote:
> What you are saying is that on copy, if no files were matched then return an
> error.
>
> I'm not sure I want to make that the default, but it could be a flag which
> would be useful for `sync`, `size` etc.
>
> How about `--error-if-no-files` or something like that?
>
> ---
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/ncw/rclone/issues/431#issuecomment-209075830


-- 
HashBackup: easy onsite and offsite Unix backup
http://www.hashbackup.com

**Comment by hashbackup** [comment]
As it turns out, I think it's better for HashBackup that there is no error when rclone does a remote -> local copy and the file doesn't exist.  I get a 0 exit status but no file, so that indicates the file wasn't there, whereas if rclone exited non-zero, I wouldn't know whether to retry because of a network problem or whether the file didn't exist.  So I'm liking the way it works now.

Today rclone does directory-directory operations.  As a suggestion for the future, if you want to include individual file operations, maybe that could be done in a compatible way by:

  rclone copy rem:dir/file  localdir

ie, if the source is not a directory but is a file, then copy just that 1 file.  This avoids the --include <file> syntax, would be compatible (I think) with the way it works today, and you could set the exit status non-zero in this case if the file didn't exist on the remote.
