### ISSUE TITLE
Drive is not retrying EOF errors

### ISSUE THREAD

**Issue by ceptonit** [ncw/rclone#432]
Out of 8 transfers, only 3 succeeded.
Each file I'm trying to transfer is 15GB+

> Transferred:   154508449430 Bytes (1986.31 kByte/s)
Errors:                 5
Checks:                 0
Transferred:            8
Elapsed time:   21h6m3.6s

The 3 files that got transferred:
> rclone ls remote:myfolder 
39788006262 file1.gpg
27893756205 file2.gpg
32535615987 file3.gpg

The failed transfers occur in no specific pattern. The last failed transfer occurred at 40% of its upload while the previous failed one occurred at 88%.

The error message I get for each failed transfer is (name_of_file and upload_id being different for each file):
`2016/04/12 10:42:58 name_of_file.gpg: Failed to copy: Post https://www.googleapis.com/upload/drive/v2/files?alt=json&uploadType=resumable&upload_id=AEnB2UppLwkI0aXEX-RA8ijCFrt9l9dTLkEsckEzdVQoDCJs2AfudCIkoBvxxrrosVl1IU3Y78weWV6i7-SsifjFPynQ3YsJfA: EOF`

I'm maxing out my upload speed so no problem there.
I also tried transferring 1 file at the time, but the reliability is the same.

> What is your rclone version (eg output from `rclone -V`)
Rclone v1.28

> Which OS you are using and how many bits (eg Windows 7, 64 bit)
Ubuntu 14.04 64bit

> Which cloud storage system are you using? (eg Google Drive)
Google Drive

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone --checksum --transfers=2 --drive-chunk-size=16M retries 8 --exclude *.DS_Store sync /tank/files/ remote:myfolder

**Comment by ncw** [comment]
Can you send me a log with `-v` please?  That will show the progress of the individual chunks.  rclone should be retrying the chunks if it gets an error.

Also you could try the latest Beta which has some drive related changes: http://pub.rclone.org/v1.28-27-g0f8e7c3%CE%B2/

Thanks

Nick

**Comment by ceptonit** [comment]
I'm gonna try your latest beta, use the -v flag and let you know asap.

**Comment by ceptonit** [comment]
So I tried again (beta v1.28-27) and stopped after 4 transfers, 3 of which failed.

> Transferred:   23991744543 Bytes (1506.98 kByte/s)
Errors:                 3
Checks:                 0
Transferred:            4

I've attached the log.
[rclone.txt](https://github.com/ncw/rclone/files/216439/rclone.txt)

**Comment by ncw** [comment]
Thanks for the log - I see what is happening.

rclone isn't retrying the chunk on EOF errors - it is treating those as fatal errors.

I'll post a beta with a fix for you to try

**Comment by ceptonit** [comment]
I'm not sure if I was supposed to reply or not.
Been checking for a new beta but I couldn't find one for linux-amd64.

Or is it that you didn't find a fix yet? It's no big deal as I can just wait for v1.30.

Best regards

**Comment by ncw** [comment]
I haven't made a beta yet, but I will soon!

**Comment by ncw** [comment]
This was implemented in 1752ee3c and you should find it works in the latest beta http://pub.rclone.org/v1.29-33-g085677d%CE%B2/

If not, please re-open the ticket!

Thanks

Nick
