### ISSUE TITLE
dedupe not working

### ISSUE THREAD

**Issue by rtg20** [ncw/rclone#433]
Hi, I have a LOT of duplicates on my Google Drive. I read issue #338 and downloaded the beta version referenced therein.

The command 

rclone lsl drive:dupes

works beautifully - all the duplicates are immediately listed.

However, when I try to dedupe, it can't find any duplicates. I tried the newest mode and also interactive mode.

Any ideas?

thanks. :-)

**Comment by ncw** [comment]
Can you post a log with -v and the command you are running please? Also which OS are you running? 

The latest beta is http://pub.rclone.org/v1.28-27-g0f8e7c3%CE%B2/

Can you try that (if that wasn't the one you tried) 

Thanks 

Nick

**Comment by rtg20** [comment]
Hi Nick I am so sorry - In the course of gathering the requested info I misread the documentation for the lsl command. After further investigation, everything is working properly. Thank you!

**Comment by ncw** [comment]
Don't worry easily done!
