### ISSUE TITLE
Can I get the activity logs from Google drive?

### ISSUE THREAD

**Issue by afakharany93** [ncw/rclone#435]
Hi,
I use an Ubuntu-64 machine, rclone v1.28 to connect with Google drive.
Id like to ask if I could use rclone to obtain the activity logs of my google drive folders and files?
Best regards.

**Comment by ncw** [comment]
There is a drive API for this, but I'm afraid rclone doesn't implement it.

I didn't have any luck searching for a different solution either - sorry!

**Comment by ncw** [comment]
I think this is out of scope for rclone, so I'm going to close this ticket.
