### ISSUE TITLE
Go routines at exit 27

### ISSUE THREAD

**Issue by rtg20** [ncw/rclone#436]
Hi, this is for rclone v.1.28-27 on Ubuntu 64 bit. 

I ran this command

./rclone dedupe --dedupe-mode newest Google_Drive:RoboBackup/Friday/AVImarkSQL/Attachments

It runs great for half an hr or so - then it quits with the error

Go routines at exit 27

any ideas? thanks!

**Comment by ncw** [comment]
That isn't an error message, it is just an info message and quite normal.

I would guess that it didn't find any duplicates.

Try it with `-v` so it prints more stuff.

**Comment by rtg20** [comment]
Oh ok, thank you. :-)
