### ISSUE TITLE
Illegal instruction

### ISSUE THREAD

**Issue by edd3a** [ncw/rclone#437]
When filing an issue, please include the following information if
possible as well as a description of the problem.
Installed binary from http://downloads.rclone.org/rclone-v1.28-linux-386.zip. Execution of it, regardless of passed options, leads to "illegal instruction" message.

> What is your rclone version (eg output from `rclone -V`)

Latest version from the website (see above).

> Which OS you are using and how many bits (eg Windows 7, 64 bit)

Debbian Jessie 32bits. Kernel: 3.16.0-4-686-pae #1 SMP Debian 3.16.7-ckt20-1+deb8u4 (2016-02-29) i686 GNU/Linux

> Which cloud storage system are you using? (eg Google Drive)

Trying google drive.

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

reclone -V, reclone config

> A log from the command with the `-v` flag (eg output from `rclone -v copy /tmp remote:tmp`)

THANKS.

**Comment by ncw** [comment]
Did it print anything else other than illegal instruction?  If so can you paste it here please.

What sort of hardware is it?

Can you paste the result of `cat /proc/cpuinfo`?

Can you confirm that the md5sum of the binary is

```
$ md5sum rclone
b4d6fd906383477fd68857469d0c1513  rclone
```

Thanks

**Comment by edd3a** [comment]
b4d6fd906383477fd68857469d0c1513  rclone

A golden oldie.

processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 8
model name	: Pentium III (Coppermine)
stepping	: 6
microcode	: 0x8
cpu MHz		: 863.862
cache size	: 256 KB
physical id	: 0
siblings	: 1
core id		: 0
cpu cores	: 1
apicid		: 0
initial apicid	: 0
fdiv_bug	: no
f00f_bug	: no
coma_bug	: no
fpu		: yes
fpu_exception	: yes
cpuid level	: 2
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 sep mtrr pge mca cmov pse36 mmx fxsr sse
bogomips	: 1727.72
clflush size	: 32
cache_alignment	: 32
address sizes	: 36 bits physical, 32 bits virtual
power management:

**Comment by klauspost** [comment]
Pentium III doesn't have SSE2. I believe you have to set `GO386=387` environment variable when compiling to use legacy float point instructions.

**Comment by edd3a** [comment]
Ok. I am using the binary though, not trying to compile from source.

**Comment by klauspost** [comment]
Exactly. Unfortunately you will have to compile your own to get a version without SSE2 instructions.

**Comment by edd3a** [comment]
If I were to install the binary for the raspberry pi (pi B, or Pi2), would it work without having to compile anything?

**Comment by ncw** [comment]
@edd3a I'm not currently doing a 386 with 387 build.

Here is one for you to try which I built with the command (as suggested by @klauspost - thanks!)

```
GO386=387 GOARCH=386 GOOS=linux go build -v
```

http://pub.rclone.org/rclone-v1.28-30-gdd36264-387-387.zip

Let me know if that works or not!

**Comment by edd3a** [comment]
I will try that! Thanks. I am also trying the arm version successfully. Very cool! 

I have downloaded the binary, and will let yo know how i get on.

**Comment by edd3a** [comment]
Havent gotten around to testing it, but, I will let you know.

**Comment by ncw** [comment]
This will be fixed when I start compiling rclone with go 1.7 which will be 1st august I think

**Comment by ncw** [comment]
Go 1.7 released now so this fix will be in v1.33.

Here is a beta to try: http://pub.rclone.org/v1.32-17-g3f71078%CE%B2/ - please re-open if it doesn't work!

**Comment by wtangerine** [comment]
This issue is back. Tried to install rclone on a i386 debian-based OS running on a [very] old Via CPU without SSE2. Installed but wouldn't work - "Illegal instruction". Had to compile both Go and then rclone (more precisely, had to compile Go twice due to modern versions of Go being released with source code that has to be compiled with Go 1.4 or later). Quite a mess. But hey, it is all working quite nicely in the end!

**Comment by ncw** [comment]
@wtangerine glad you found a work-around.

I could add a  GO386=387 official build, but I'm not sure it is worth it - what do you think?

**Comment by wtangerine** [comment]
I think that probably the number of people who need this is minuscule, and they are probably used to compiling things. However look at the process I went through to get rclone working:

- download rclone binary, install, get the "illegal instruction" error
- google the error, figure out how to compile rclone with Go, uninstall rclone
- install Go supplied by the distribution, try to compile rclone, get an error because rclone depends on a higher version of Go
- google the error, figure out rclone dependencies, download Go binary, install, get "Illegal instruction"
- uninstall Go, figure out Go compilation, download Go 1.4 sources, compile Go 1.4, figure out how to use it to bootsrap modern Go version compilation
- Compile modern Go using Go 1.4 bootstrapper
- Compile rclone, install

As you can see, this is far beyond "make && sudo make install".

So if compilation without SSE2 won't cause any issues or degrade performance for existing users, I think that GO386=387 in the official build will save a few hours of frustration to those precious few who try to use rclone on old machines.

**Comment by ncw** [comment]
I think just about all linux installations are 64 bit now-a-days so slowing down the 386 build a bit for increased compatibility sounds like a reasonable plan. Alternatively I could make a new build -386-no-sse.

Can you try this binary and see if it works for you?  I cross compiled this with `GOARCH=386 GO386=387 go build`.

[rclone-v1.36-22-gbc25190-no-sse.zip](https://github.com/ncw/rclone/files/910717/rclone-v1.36-22-gbc25190-no-sse.zip)

**Comment by wtangerine** [comment]
Thanks! I'll back up the installation tomorrow (I wanted to do this anyway) and then I'll test the build. This is a production machine already.

BTW I've been working on a bash script to automate backups with rclone, maybe will upload it to github sometime soon (once I come up with some name for it). I guess it would look amateur'ish to the pro's (actually this is my first bash script ever and I'm not much of a coder) but it's configurable, has CLI, has some error handling logic and automates compression, encryption, setting CPU and I/O priorities etc. Thought you might be glad to hear.

**Comment by ncw** [comment]
@wtangerine no rush!  I expect that build to work (cross fingers).

**Comment by wtangerine** [comment]
Sorry about the delay, finally tested the build and... illegal instruction.
This is what I get in dmesg:
```
traps: rclone[4337] trap invalid opcode ip:807aa43 sp:bff900ac error:0
 in rclone[8048000+5f5000]
```

**Comment by wtangerine** [comment]
For reference, attached is my non-SSE2 executable.
Had to change the extension from .zip to .docx because for some reason, github refused to accept it as .zip.

[rclone.docx](https://github.com/ncw/rclone/files/981403/rclone.docx)

**Comment by ncw** [comment]
> not sure if that makes any difference but the "file" command reports my executable as dynamically linked, while your executable as statically linked.

I'm confused by "my executable" and "your executable".  How did you generate your executable?  Does it work?

The executable I sent you was statically linked.

Here is the latest rclone beta compiled with  `GOARCH=386 GO386=387 go build`
[rclone-v1.36-48-g58a82cd-no-sse.zip](https://github.com/ncw/rclone/files/981640/rclone-v1.36-48-g58a82cd-no-sse.zip)

I tried to see if I could see those instructions you mentioned. 

```
$ objdump -d rclone | grep ucomisd
$ objdump -d rclone | grep movq
 8049351:	0f 6f 00             	movq   (%eax),%mm0
 8049354:	0f 7f 44 24 08       	movq   %mm0,0x8(%esp)
 80496d5:	0f 6f 00             	movq   (%eax),%mm0
 80496d8:	0f 7f 03             	movq   %mm0,(%ebx)
 80496f1:	0f 6f 44 24 08       	movq   0x8(%esp),%mm0
 80496f6:	0f 7f 00             	movq   %mm0,(%eax)
 80946e4:	f3 0f 7e 00          	movq   (%eax),%xmm0
```

The "0f 6f 00" instruction is in your original list.  This is part of the implementation of sync/atomic.LoadUint64 which makes sense as these routines are written in assembler.

This looks like this (from src/sync/atomic/asm_386.s)

```
TEXT ·LoadUint64(SB),NOSPLIT,$0-12
	MOVL	addr+0(FP), AX
	TESTL	$7, AX
	JZ	2(PC)
	MOVL	0, AX // crash with nil ptr deref
	// MOVQ and EMMS were introduced on the Pentium MMX.
	// MOVQ (%EAX), %MM0
	BYTE $0x0f; BYTE $0x6f; BYTE $0x00
	// MOVQ %MM0, 0x8(%ESP)
	BYTE $0x0f; BYTE $0x7f; BYTE $0x44; BYTE $0x24; BYTE $0x08
	EMMS
	RET
```

Which seems to claim that those instructions should work.

Can you work out which instruction exactly you are getting the "illegal instruction" fault on?  You should be able to do this by running rclone with gdb, wait for it to fault, then run "layout asm".

**Comment by wtangerine** [comment]
Referring to "my executable", I meant the one that I compiled myself. Which is working.

Probably that whole discussion doesn't matter much now because your latest build runs without "illegal instruction" here (didn't actually tried to use it yet, just ran it without arguments). I wonder what changed?

**Comment by wtangerine** [comment]
Just for fun, I tried to debug the previous build (the one where I got "illegal instruction"), here's what I got with "layout asm":
  `>│0x807aa43 <runtime.check+51>    movsd  %xmm0,0x30(%esp)`

**Comment by ncw** [comment]
From rclone-v1.36-22-gbc25190-no-sse.zip which does fault

```
0807aa10 <runtime.check>:
 807aa10:       65 8b 0d 00 00 00 00    mov    %gs:0x0,%ecx
 807aa17:       8b 89 fc ff ff ff       mov    -0x4(%ecx),%ecx
 807aa1d:       3b 61 08                cmp    0x8(%ecx),%esp
 807aa20:       0f 86 85 04 00 00       jbe    807aeab <runtime.check+0x49b>
 807aa26:       83 ec 40                sub    $0x40,%esp
 807aa29:       c7 44 24 24 00 00 00    movl   $0x0,0x24(%esp)
 807aa30:       00 
 807aa31:       0f 57 c0                xorps  %xmm0,%xmm0
 807aa34:       f3 0f 11 44 24 20       movss  %xmm0,0x20(%esp)
 807aa3a:       f3 0f 11 44 24 1c       movss  %xmm0,0x1c(%esp)
 807aa40:       0f 57 c0                xorps  %xmm0,%xmm0
 807aa43:       f2 0f 11 44 24 30       movsd  %xmm0,0x30(%esp) # FAULT HERE
 807aa49:       f2 0f 11 44 24 28       movsd  %xmm0,0x28(%esp)
 807aa4f:       c7 44 24 3c 00 00 00    movl   $0x0,0x3c(%esp)
 807aa56:       00 
```

From rclone-v1.36-48-g58a82cd-no-sse.zip which doesn't fault

```
0807ae20 <runtime.check>:
 807ae20:       65 8b 0d 00 00 00 00    mov    %gs:0x0,%ecx
 807ae27:       8b 89 fc ff ff ff       mov    -0x4(%ecx),%ecx
 807ae2d:       3b 61 08                cmp    0x8(%ecx),%esp
 807ae30:       0f 86 20 05 00 00       jbe    807b356 <runtime.check+0x536>
 807ae36:       83 ec 48                sub    $0x48,%esp
 807ae39:       c7 44 24 24 00 00 00    movl   $0x0,0x24(%esp)
 807ae40:       00 
 807ae41:       d9 05 38 04 85 08       flds   0x8850438
 807ae47:       d9 c0                   fld    %st(0)
 807ae49:       d9 5c 24 20             fstps  0x20(%esp)
 807ae4d:       d9 c0                   fld    %st(0)
 807ae4f:       d9 5c 24 1c             fstps  0x1c(%esp)
 807ae53:       dd 05 a8 04 85 08       fldl   0x88504a8
 807ae59:       dd d9                   fstp   %st(1)
 807ae5b:       d9 c0                   fld    %st(0)
 807ae5d:       dd 5c 24 30             fstpl  0x30(%esp)
 807ae61:       d9 c0                   fld    %st(0)
 807ae63:       dd 5c 24 28             fstpl  0x28(%esp)
 807ae67:       c7 44 24 44 00 00 00    movl   $0x0,0x44(%esp)
 807ae6e:       00 
```

So it seems clear that the compiler has generated completely different instructions!


The first was build with go1.8 the second with go1.8.1

I had a look throught the release notes and I can't see anything which could cause that.

The only conclusion I can draw is that I somehow messed up the compile and didn't compile it with `GO386=387` :-(

Can you test rclone-v1.36-48-g58a82cd-no-sse.zip a bit more to see if it works for transfers etc?

**Comment by wtangerine** [comment]
Tested the "config" command and the "copy" command. Works fine as far as I can tell.

**Comment by ncw** [comment]
@wtangerine great.

I added `GO386=387` to the offical 386 build.  So you should find that the latest beta works for you

https://beta.rclone.org/v1.36-49-g5135ff7/ (uploaded in 15-30 mins)

Can you give it a quick test for me please?

Thanks

**Comment by wtangerine** [comment]
Yep, tested commands config, copy, ls with Google Drive - latest beta working fine here.
Thanks for fixing this!

**Comment by ncw** [comment]
Excellent :-)

Will close this (again) now.
