### ISSUE TITLE
transfer interrupted and acts like finished

### ISSUE THREAD

**Issue by databaseindays** [ncw/rclone#438]
I used rclone and have it configured pretty well. I already used it to sync my documents folder to Google drive and that was like several hours and all went well and I can sync and add new files and it only adds the new files. 

So then I decided to sync my other folders with video and audio files and all. I knew that would take way longer but I was prepared.

After about 27 hours, I was making changes to my hosts file, for some reason and so i had to restart my network-manager on Ubuntu. And Rclone came to a halt and never restarted properly, which I cant blame it, so I decided to control C rclone, reboot my computer and then just restart the rclone sync command. just simple rcone sync. I expected it to run, and sync what was not on gogle drive, and continue to sync for like a day or 2 more as there was a lot of files, but it only ran for like 5 minutes and finished like the 2 folders were sync'd. no errors NO files uploaded. 

So is this a bug or is it that rclone can not finish an interupped sync? which to me is a bug.
I also tried rclone copy to see if this would start over or something. but it basically did the same thing. 3 minutes and done, no files added.

So in troubleshooting i go to google drive to see if maybe by some miracle, all the files were already synced, but no they were not. folders on drive were missing stuff that were still in local folder.

I am copyying from an external HD to google drive. im attaching a log of the output of of my rclone -v sync so you can see that.

Searhing google I found nothing on this kind of behavior with rclone. 

I just need guidence on what is going on and how to continue and not waste the 27 hours of the partial sync. thanks

> What is your rclone version (eg output from `rclone -V`) 
v1.28

> Which OS you are using and how many bits (eg Windows 7, 64 bit)
Ubuntu 14.04 64 bit
> Which cloud storage system are you using? (eg Google Drive)
Google Drive
> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone sync "/media/norman/Seagate Expansion Drive/spiritual Info" drive:/corsair/Spiritual-Info/ -v
and also
rclone copy "/media/norman/Seagate Expansion Drive/spiritual Info" drive:/corsair/Spiritual-Info/ -v

> A log from the command with the `-v` flag (eg output from `rclone -v copy /tmp remote:tmp`)

**Comment by databaseindays** [comment]
2 things:
1. I forgot to upload my log file as promised.
2. I noticed rclone was still running so log was not available yet. I also noticed that it appears to be actually syncing today, as I see files are being added. so it looks like it is now working. I tried it several times yesterday and it would not do this, so im guessing the change of date somehow made everything fine. 

So hold off on this issue and I will post log and status of completion when it finally finishes synching, which may take a day or 2. :-)

thanks

**Comment by ncw** [comment]
rclone will restart an interrupted sync just fine, however note that the sync works on a file by file basis, so if it was half way through transferring a big file then it will have to start again with that file.  That only really makes a difference if you are transferring HUGE files though.

**Comment by databaseindays** [comment]
yes, it is finishing now, but I promise you I tried to restart the same day and it kept skipping the files like they were all already uploaded. But NOW a day later, it is working fine, so may be some anomaly. After my sync finishes I will do a test of this and let you know my finding in a few days.

**Comment by databaseindays** [comment]
OK so my results were that the sync did restart back where it left off THIS time, but when I tried to do it, soon after halting it, it would act as described. It was not till the next day did it work when I ran the exact same command. So it is buggy somewhere when a command fails it will not run as supposed to right after.

I just opened another issue which is almost the same. I tried to sync a different folder and i may have entered a folder that didnt exist or incorrect and it ended in 1 error. all other attempts to sync to that remote drive folder are not executing. just running for a second and reporting nothing was done. See that issue I just opened. Im sure it will run tomorrow once something internally resets. maybe it is because it is the same date or something. Try to repeat this yourself. run a sync with a bad path locally to a remote drive, have it fail with error. fix the error and run sync again. chances are you will see the odd behavior I am mentioning. You may close this one at your disgression as I have the other one open.

**Comment by ncw** [comment]
I'm going to close this issue as I haven't been able to reproduce the problem.
