### ISSUE TITLE
"Deletes any files that exist in source that don't exist in destination" - optional

### ISSUE THREAD

**Issue by bobobo1618** [ncw/rclone#44]
This is from the sync command documentation.

Am I correct in my interpretation here:
- Create a bunch of files
- Copy a bunch of files to Drive
- Make a new file
- Run `sync <local> <remote>`
- New file is deleted

If so, I would very much like for this to be optional. If not, the documentation needs to be a bit clearer. When I sync, I'd prefer it if files that don't exist locally are deleted on the remote rather than the reverse.

**Comment by ncw** [comment]
The documentation is a bit confusing - sorry! Your interpretation isn't correct you'll be glad to know. There is another ticket about this #39 and here is the new suggested wording for the docs

    Sync the source to the destination, changing the destination only.  Doesn't transfer
    unchanged files, testing first by modification time then by
    size.  Destination is updated to match source, including deleting files if necessary.
    Since this can cause data loss, test first with the --dry-run flag.

So your example would become

  * Create a bunch of files
  * Copy a bunch of files to Drive
  * Make a new file
  * Run `sync <local> <remote>`
  * New file is copied to Drive
  * Delete the new file locally
  * Run `sync <local> <remote>`
  * New file is deleted from Drive

**Comment by dennybaa** [comment]
When you delete new file locally, is the file placed into trash bin or deleted right away?

**Comment by ncw** [comment]
The file is permanently deleted using the [delete method](https://developers.google.com/drive/v2/reference/#Files)

If you wanted the file to go to the trash then I could use the trash method instead.  Maybe this should be an option?

**Comment by dennybaa** [comment]
I'll try to redefine the question a bit. I was interested about delete in context of syncing. So when I delete file locally how would  sync behave? Completely remove a file on the remote GDrive or place it into bin.

**Comment by ncw** [comment]
In the context of syncing, when you delete a file locally

    rm local/file

Then sync

    rclone sync local drive:local

The copy on drive will be deleted permanently, not put into the trash / bin.

I could make it put it into the trash / bin with an option - either a command line flag, or an option when the drive remote is set up.

**Comment by dennybaa** [comment]
I think it's a generally good idea useful for users. For example, grive as I've heard works this way, but it's already dead project anyway.

**Comment by ncw** [comment]
I'm fixing the docs in #39

I'll turn this ticket into a feature request ticket for trashing files instead of deleting them.

**Comment by zeshanb** [comment]
I've made a short screen capture video to show the difference between Sync and Copy when using rClone. Hope this helps:

https://github.com/zeshanb/rclone-video-tutorials/blob/master/docs/static/videos/Using-rClone-difference-between-copy-and-sync.mp4?raw=true

Regards,
Zeshan

**Comment by ncw** [comment]
@zeshanb Wow that is amazing - thanks! I'd like to put it up somewhere so I can embed it in the rclone website - I'll send you an email to discuss

**Comment by zeshanb** [comment]
@Nick Thanks. I tried to make these unbranded and generic as possible, so
anyone can use these. These are h264 videos and can easily be embedded
using html5 video tag. Hope it's a good addition to rClone docs.

https://github.com/zeshanb/rclone-video-tutorials

**Comment by ncw** [comment]
Trashing files instead of deleting them was done in #82 so I think this is all done now
