### ISSUE TITLE
Failed to copy: open /path/dir: is a directory

### ISSUE THREAD

**Issue by fredericofs** [ncw/rclone#440]
I am syncing buckets ==> local.
Some buckets have subfolders with files.
Rclone sync all those subfolders and its files ok. But at the end of the sync job I get error menssages for each subfolder, like this:

2016/04/19 02:01:35 bar/: Failed to copy: open /foo/bar.: is a directory

It ia annoying because this counts as error attempts.

> What is your rclone version (eg output from `rclone -V`)

rclone v1.28
> Which OS you are using and how many bits (eg Windows 7, 64 bit)

Linux 4.1.19+ #858 Tue Mar 15 15:52:03 GMT 2016 armv6l GNU/Linux
> Which cloud storage system are you using? (eg Google Drive)

DreamObjects (Ceph/s3)
> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

rclone sync
> A log from the command with the `-v` flag (eg output from `rclone -v copy /tmp remote:tmp`)

2016/04/19 02:01:35  bar/: Failed to copy: open /foo/bar: is a directory

**Comment by ncw** [comment]
How did you upload those files to dreamhost?

Is there a 0 sized file or something like that marking each directory?

If you do `rclone ls dreamhost:bucket` do you see files marking the directories?

**Comment by fredericofs** [comment]
I have uploaded the files to the server using a GUI tool named CYBERDUCK. Indeed there is a 0 sized file marking each directory.
I made a test uploading some "files inside subfolders" with rclone to the server, and yes it does not create such 0 sized files for folder names.
Is there any I can do do fix this without deleting/reuploading all the files again?

Out of curiosity, during those tests I found that if there is an empty folder inside a bucket, rclone will create an empty file with the name of the folder, instead of creating an empty folder.  Awscli tool, for example, wont download the empty folder (or create a file with its name) at all.
Another find is that awscli does not delete a destination folder, after it has become empty, while rsync do (and that is good in my opinion).

Thats all

**Comment by ncw** [comment]
Here are some ideas for work-arounds

You could ignore all zero length files by adding `--min-size 0.001k` to the sync (syntax to be improved in #449)

You could delete all the zero length files (this actually would delete all 0 and 1 length files beware - see #450)

    rclone -v --dry-run --max-size 0.001k delete remote:path

Remove `--dry-run` if happy.

**Comment by jordigg** [comment]
Got into the same problem with GCE Buckets. Used the web UI from Google to upload some files and folders (drag and drop) from my machine.
Now just syncs what exists on the bucket but doesn't delete what's no longer there.
`rclone ls` lists all contents juts fine on remote, no errors on the log file when syncing.
I tried `create folder on remote -> sync -> remove from remote -> sync` and everything works fine.

Any idea why is not deleting them? The folders contain files. Nothing is being deleted.

**Comment by ncw** [comment]
@jordigg I don't understand exactly what you mean?  Can you make a new issue, preferably with a log of the problem?  Thanks Nick

**Comment by ncw** [comment]
I'm going to close this ticket now as I think we've finished the discussion.  Thanks, Nick
