### ISSUE TITLE
new sync not transferring files, and without much info

### ISSUE THREAD

**Issue by databaseindays** [ncw/rclone#441]
here is command and output. it last 1 second and should be many many files. folders are correct.
rclone sync /home/norman/Desktop/html/ drive:/corsair/html -v > output.txt
2016/04/19 11:29:56 Google drive root 'corsair/html': Modify window is 1ms
2016/04/19 11:29:56 Google drive root 'corsair/html': Building file list
2016/04/19 11:29:56 Google drive root 'corsair/html': Finished reading 
2016/04/19 11:29:56 Google drive root 'corsair/html': Waiting for checks to finish
2016/04/19 11:29:56 Google drive root 'corsair/html': Starting deletion
2016/04/19 11:29:56 Waiting for deletions to finish
2016/04/19 11:29:56 Google drive root 'corsair/html': Waiting for transfers to finish
2016/04/19 11:29:56 Google drive root 'corsair/html': Waiting for deletes to finish (during+after)
2016/04/19 11:29:56 Google drive root 'corsair/html': Deletion finished

Transferred:            0 Bytes (   0.00 kByte/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:        1.1s

2016/04/19 11:29:56 Go routines at exit 5

When filing an issue, please include the following information if
possible as well as a description of the problem.

> What is your rclone version (eg output from `rclone -V`)

1.28

> Which OS you are using and how many bits (eg Windows 7, 64 bit)

ubuntu 64 bit

> Which cloud storage system are you using? (eg Google Drive)

google drive

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

shown above

> A log from the command with the `-v` flag (eg output from `rclone -v copy /tmp remote:tmp`)

shown above . output never goes to file for some reason. file is blank. other command leave output in file is used > output.txt after command and so it should have, but it does not, so I pasted it above. My experience is that rclone works until it does not work and its sporadic. it may work tomorrow, kike the other issue i have open.

**Comment by ncw** [comment]
That command looks like rclone correctly synced the data - what makes you think it didn't?

What does

    rclone check /home/norman/Desktop/html/ drive:/corsair/html

And

    rclone size /home/norman/Desktop/html/
    rclone size drive:/corsair/html

say?

(To get the data into the file use `2>&1` after the `> output`)

**Comment by databaseindays** [comment]
rclone check  /home/norman/Desktop/html/ drive:/corsair/html -v 
2016/04/19 13:08:05 drive: Saving new token in config file
2016/04/19 13:08:06 Google drive root 'corsair/html': Modify window is 1ms
2016/04/19 13:08:06 Local file system at /home/norman/Desktop/html: Building file list
2016/04/19 13:08:06 Google drive root 'corsair/html': Building file list
2016/04/19 13:08:06 Google drive root 'corsair/html': Done building file list
2016/04/19 13:08:06 Google drive root 'corsair/html': Finished reading 
2016/04/19 13:08:06 Google drive root 'corsair/html': Done building file list
2016/04/19 13:08:06 Google drive root 'corsair/html': 0 files not in Local file system at /home/norman/Desktop/html
2016/04/19 13:08:06 Local file system at /home/norman/Desktop/html: 0 files not in Google drive root 'corsair/html'
2016/04/19 13:08:06 Google drive root 'corsair/html': Waiting for checks to finish
2016/04/19 13:08:06 Google drive root 'corsair/html': 0 differences found

Transferred:            0 Bytes (   0.00 kByte/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:        1.7s

rclone size  /home/norman/Desktop/html/ 
Total objects: 0
Total size: 0 (0 bytes)

Transferred:            0 Bytes (   0.00 kByte/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:           0

now  I know its reporting that the local html folder is empty, but I ASSURE you its filled with all my sites and a ton of files. Im a web developer I just checked to be sure and lots of folders, im even working on some now in an editor, so rclone reporting is false. Ill let you know if it starts to work again later, like the other issue did. And it never created a folder on google drive either.

**Comment by databaseindays** [comment]
OK I think I know why. The folder on my Desktop was a symbolic to /var/www/htnl. So it looks like rclone does not follow those. closing as resolved. :-)
