### ISSUE TITLE
Failed to copy?

### ISSUE THREAD

**Issue by rtg20** [ncw/rclone#442]
Hi I finally have rclone v1.28 working pretty well - WAY better than the other Google Drive sync tools I've tried, including the paid ones and Google's client. Thanks so much for a great program!

I am using Server 2012 (Windows 64 bit). Here's the command I am using

.\rclone.exe --log-file=rclone2.txt --checkers 2 --transfers 2 --size-only --exclude DBBackup sync F:\Drive\RoboBackup\Monday Google_Drive:RoboBackup\Monday

Here's an error:

2016/04/19 08:14:16 AVImarkSQL/signatur/23544/393554.png: Received error: googleapi: Error 403: Rate Limit Exceeded, rateLimitExceeded - low level retry 1/10
2016/04/19 08:14:24 AVImarkSQL/Attachments/9057/Po/CCF10202015records.pdf: Failed to copy: Post https://www.googleapis.com/upload/drive/v2/files?alt=json&uploadType=resumable: http: ContentLength=206 with Body length 0
2016/04/19 08:14:36 AVImarkSQL/Attachments/23537/Thumbs.db: Received error: googleapi: Error 403: Rate Limit Exceeded, rateLimitExceeded - low level retry 1/10
2016/04/19 08:15:03 AVImarkSQL/signatur/9707/394038.png: Received error: googleapi: Error 403: Rate Limit Exceeded, rateLimitExceeded - low level retry 1/10
2016/04/19 08:15:05 AVImarkSQL/signatur/9707/394038.png: Received error: googleapi: Error 403: Rate Limit Exceeded, rateLimitExceeded - low level retry 2/10
2016/04/19 08:15:08
Transferred:    391478457 Bytes (  62.85 kByte/s)
Errors:                13
Checks:             41505
Transferred:          687
Elapsed time:  1h41m22.7s
Transferring:
 *                        AVImarkSQL/logdata.mps: 74% done. avg:   74.4, cur:   73.4 kByte/s. ETA: 21m41s
 *           AVImarkSQL/signatur/9707/394038.png: 100% done. avg:    3.9, cur:    6.0 kByte/s. ETA: 0s

I read the docs and previous issues about these errors. It looks like the file that caused the problem was eventually transferred (last line of the log). I already specified checkers and transfers in the command. Are there any other ways to mitigate these errors?

thank you!!!!!!!!

**Comment by ncw** [comment]
Firstly that is what Google drive does.  rclone does its best to retry stuff and it normally works pretty well.

It is worth trying v1.29 (just out) which has had the google drive retry schedule tweaked - that should improve things.

You shouldn't need to change checkers / transfers

You can keep retrying the sync until it runs with 0 errors (or use the `--retries` flag).

**Comment by rtg20** [comment]
... Ok now it's not working. :-(

2016/04/21 00:18:44 DBBackup: Failed to copy: Posthttps
<https://www.googleapis.com/upload/drive/v2/files/0B2VS5Wi09HJnaGJGMzQzaXVuVWM?alt=json&setModifiedDate=true&uploadType=resumable&upload_id=AEnB2Uq-1QWvYElu0TsqTtLtCCB-9gy_yk7hfISQS_vIxOYPhKdgXwUC_geANZ2TsY7ze5H4zkClCJg-iJPMnLNsFAznUGcZVA>
://
<https://www.googleapis.com/upload/drive/v2/files/0B2VS5Wi09HJnaGJGMzQzaXVuVWM?alt=json&setModifiedDate=true&uploadType=resumable&upload_id=AEnB2Uq-1QWvYElu0TsqTtLtCCB-9gy_yk7hfISQS_vIxOYPhKdgXwUC_geANZ2TsY7ze5H4zkClCJg-iJPMnLNsFAznUGcZVA>
www.googleapis.com
<https://www.googleapis.com/upload/drive/v2/files/0B2VS5Wi09HJnaGJGMzQzaXVuVWM?alt=json&setModifiedDate=true&uploadType=resumable&upload_id=AEnB2Uq-1QWvYElu0TsqTtLtCCB-9gy_yk7hfISQS_vIxOYPhKdgXwUC_geANZ2TsY7ze5H4zkClCJg-iJPMnLNsFAznUGcZVA>
/upload/drive/v2/files/0B2VS5Wi09HJnaGJGMzQzaXVuVWM?alt=
<https://www.googleapis.com/upload/drive/v2/files/0B2VS5Wi09HJnaGJGMzQzaXVuVWM?alt=json&setModifiedDate=true&uploadType=resumable&upload_id=AEnB2Uq-1QWvYElu0TsqTtLtCCB-9gy_yk7hfISQS_vIxOYPhKdgXwUC_geANZ2TsY7ze5H4zkClCJg-iJPMnLNsFAznUGcZVA>
json
<https://www.googleapis.com/upload/drive/v2/files/0B2VS5Wi09HJnaGJGMzQzaXVuVWM?alt=json&setModifiedDate=true&uploadType=resumable&upload_id=AEnB2Uq-1QWvYElu0TsqTtLtCCB-9gy_yk7hfISQS_vIxOYPhKdgXwUC_geANZ2TsY7ze5H4zkClCJg-iJPMnLNsFAznUGcZVA>
&
<https://www.googleapis.com/upload/drive/v2/files/0B2VS5Wi09HJnaGJGMzQzaXVuVWM?alt=json&setModifiedDate=true&uploadType=resumable&upload_id=AEnB2Uq-1QWvYElu0TsqTtLtCCB-9gy_yk7hfISQS_vIxOYPhKdgXwUC_geANZ2TsY7ze5H4zkClCJg-iJPMnLNsFAznUGcZVA>
setModifiedDate
<https://www.googleapis.com/upload/drive/v2/files/0B2VS5Wi09HJnaGJGMzQzaXVuVWM?alt=json&setModifiedDate=true&uploadType=resumable&upload_id=AEnB2Uq-1QWvYElu0TsqTtLtCCB-9gy_yk7hfISQS_vIxOYPhKdgXwUC_geANZ2TsY7ze5H4zkClCJg-iJPMnLNsFAznUGcZVA>
=true&
<https://www.googleapis.com/upload/drive/v2/files/0B2VS5Wi09HJnaGJGMzQzaXVuVWM?alt=json&setModifiedDate=true&uploadType=resumable&upload_id=AEnB2Uq-1QWvYElu0TsqTtLtCCB-9gy_yk7hfISQS_vIxOYPhKdgXwUC_geANZ2TsY7ze5H4zkClCJg-iJPMnLNsFAznUGcZVA>
uploadType
<https://www.googleapis.com/upload/drive/v2/files/0B2VS5Wi09HJnaGJGMzQzaXVuVWM?alt=json&setModifiedDate=true&uploadType=resumable&upload_id=AEnB2Uq-1QWvYElu0TsqTtLtCCB-9gy_yk7hfISQS_vIxOYPhKdgXwUC_geANZ2TsY7ze5H4zkClCJg-iJPMnLNsFAznUGcZVA>
=resumable&upload_
<https://www.googleapis.com/upload/drive/v2/files/0B2VS5Wi09HJnaGJGMzQzaXVuVWM?alt=json&setModifiedDate=true&uploadType=resumable&upload_id=AEnB2Uq-1QWvYElu0TsqTtLtCCB-9gy_yk7hfISQS_vIxOYPhKdgXwUC_geANZ2TsY7ze5H4zkClCJg-iJPMnLNsFAznUGcZVA>
id
<https://www.googleapis.com/upload/drive/v2/files/0B2VS5Wi09HJnaGJGMzQzaXVuVWM?alt=json&setModifiedDate=true&uploadType=resumable&upload_id=AEnB2Uq-1QWvYElu0TsqTtLtCCB-9gy_yk7hfISQS_vIxOYPhKdgXwUC_geANZ2TsY7ze5H4zkClCJg-iJPMnLNsFAznUGcZVA>
=
<https://www.googleapis.com/upload/drive/v2/files/0B2VS5Wi09HJnaGJGMzQzaXVuVWM?alt=json&setModifiedDate=true&uploadType=resumable&upload_id=AEnB2Uq-1QWvYElu0TsqTtLtCCB-9gy_yk7hfISQS_vIxOYPhKdgXwUC_geANZ2TsY7ze5H4zkClCJg-iJPMnLNsFAznUGcZVA>
AEnB2Uq-1QWvYElu0TsqTtLtCCB-9gy
<https://www.googleapis.com/upload/drive/v2/files/0B2VS5Wi09HJnaGJGMzQzaXVuVWM?alt=json&setModifiedDate=true&uploadType=resumable&upload_id=AEnB2Uq-1QWvYElu0TsqTtLtCCB-9gy_yk7hfISQS_vIxOYPhKdgXwUC_geANZ2TsY7ze5H4zkClCJg-iJPMnLNsFAznUGcZVA>
_
<https://www.googleapis.com/upload/drive/v2/files/0B2VS5Wi09HJnaGJGMzQzaXVuVWM?alt=json&setModifiedDate=true&uploadType=resumable&upload_id=AEnB2Uq-1QWvYElu0TsqTtLtCCB-9gy_yk7hfISQS_vIxOYPhKdgXwUC_geANZ2TsY7ze5H4zkClCJg-iJPMnLNsFAznUGcZVA>
yk7hfISQS
<https://www.googleapis.com/upload/drive/v2/files/0B2VS5Wi09HJnaGJGMzQzaXVuVWM?alt=json&setModifiedDate=true&uploadType=resumable&upload_id=AEnB2Uq-1QWvYElu0TsqTtLtCCB-9gy_yk7hfISQS_vIxOYPhKdgXwUC_geANZ2TsY7ze5H4zkClCJg-iJPMnLNsFAznUGcZVA>
_
<https://www.googleapis.com/upload/drive/v2/files/0B2VS5Wi09HJnaGJGMzQzaXVuVWM?alt=json&setModifiedDate=true&uploadType=resumable&upload_id=AEnB2Uq-1QWvYElu0TsqTtLtCCB-9gy_yk7hfISQS_vIxOYPhKdgXwUC_geANZ2TsY7ze5H4zkClCJg-iJPMnLNsFAznUGcZVA>
vIxOYPhKdgXwUC
<https://www.googleapis.com/upload/drive/v2/files/0B2VS5Wi09HJnaGJGMzQzaXVuVWM?alt=json&setModifiedDate=true&uploadType=resumable&upload_id=AEnB2Uq-1QWvYElu0TsqTtLtCCB-9gy_yk7hfISQS_vIxOYPhKdgXwUC_geANZ2TsY7ze5H4zkClCJg-iJPMnLNsFAznUGcZVA>
_
<https://www.googleapis.com/upload/drive/v2/files/0B2VS5Wi09HJnaGJGMzQzaXVuVWM?alt=json&setModifiedDate=true&uploadType=resumable&upload_id=AEnB2Uq-1QWvYElu0TsqTtLtCCB-9gy_yk7hfISQS_vIxOYPhKdgXwUC_geANZ2TsY7ze5H4zkClCJg-iJPMnLNsFAznUGcZVA>
geANZ2TsY7ze5H4zkClCJg-
<https://www.googleapis.com/upload/drive/v2/files/0B2VS5Wi09HJnaGJGMzQzaXVuVWM?alt=json&setModifiedDate=true&uploadType=resumable&upload_id=AEnB2Uq-1QWvYElu0TsqTtLtCCB-9gy_yk7hfISQS_vIxOYPhKdgXwUC_geANZ2TsY7ze5H4zkClCJg-iJPMnLNsFAznUGcZVA>
iJPMnLNsFAznUGcZVA
<https://www.googleapis.com/upload/drive/v2/files/0B2VS5Wi09HJnaGJGMzQzaXVuVWM?alt=json&setModifiedDate=true&uploadType=resumable&upload_id=AEnB2Uq-1QWvYElu0TsqTtLtCCB-9gy_yk7hfISQS_vIxOYPhKdgXwUC_geANZ2TsY7ze5H4zkClCJg-iJPMnLNsFAznUGcZVA>:
Post https <https://accounts.google.com/o/oauth2/token>://
<https://accounts.google.com/o/oauth2/token>accounts.google.com
<https://accounts.google.com/o/oauth2/token>/o/
<https://accounts.google.com/o/oauth2/token>oauth2
<https://accounts.google.com/o/oauth2/token>/token
<https://accounts.google.com/o/oauth2/token>: EOF
2016/04/21 00:19:22
Transferred:    436207616 Bytes (  99.30 kByte/s)
Errors:                 1
Checks:                 3
Transferred:            2
Elapsed time:    1h11m30s
Transferring:
 * DBBackup

2016/04/21 00:19:43 Attempt 3/3 failed with 1 errors

And

2016/04/21 00:25:53 Failed to create file system for
"Google_Drive:RoboBackup\\Wednesday": Couldn't read info about Drive: Get
https://www.googleapis.com/drive/v2/about?alt=json: read tcp
192.168.1.2:54815->216.58.216.42:443: wsarecv: An established connection
was aborted by the software in your host machine

Should I try the new version and see how it goes?

Thanks

Richard

**Comment by ncw** [comment]
EOF errors usually indicate something wrong with Google Drive or your internet connection.

The other error `An established connection
was aborted by the software in your host machine` means the same thing.

It could be your ISP closing connections at busy periods - I've seen that, or your router dropping connections - can you try using a different internet connection?

It is worth trying v1.29 as it has a number of google drive fixes.

**Comment by rtg20** [comment]
Thanks for the reply. Can't test with a different internet connection, but I just put v1.29 on the server, hopefully that will fix the problem. thanks again for the help!

**Comment by rtg20** [comment]
...ok it's not working with v1. 29

Transferred:   1275068416 Bytes (  98.61 kByte/s)
Errors:                 0
Checks:                 0
Transferred:            2
Elapsed time:  3h30m27.5s
Transferring:
 *                                      DBBackup: 39% done. avg:   98.9, cur:    0.0 kByte/s. ETA: 444459h8m19s

2016/04/29 02:39:37 DBBackup: Failed to copy: Post https://www.googleapis.com/upload/drive/v2/files?alt=json&uploadType=resumable&upload_id=AEnB2UrwQZiamUZjKz8rHoFgxnYUniM3S3UYC9TjEp5N7pSSm-m_L91Whi19kOBDHdty-dwXCGgo0f4x_kJ5qeEFo54c62lJxA: write tcp 192.168.1.2:52046->172.217.0.10:443: wsasend: An existing connection was forcibly closed by the remote host.
2016/04/29 02:39:38 Attempt 3/3 failed with 1 errors


Please help. Thanks.

**Comment by ncw** [comment]
I made a patch for rclone which treats those sort of errors as worth retrying which should help when uploading big files.

Find the beta here

http://pub.rclone.org/v1.29-14-g1752ee3%CE%B2/

Let me know how you get on!

Thanks

Nick

**Comment by rtg20** [comment]
just installed it, thanks so much, will let you know.

Richard

**Comment by rtg20** [comment]
So far, so good! Thanks again. :-)

**Comment by rtg20** [comment]
...ok this is weird, looks like it gets to 100% and then fails???

2016/05/08 11:56:31 
Transferred:   4685393408 Bytes (  99.23 kByte/s)
Errors:                 0
Checks:                 3
Transferred:            2
Elapsed time:  12h48m30.5s
Transferring:
 *                                      DBBackup: 99% done. avg:   99.9, cur:    0.0 kByte/s. ETA: 121250h30m10s

2016/05/08 11:57:31 
Transferred:   4706720768 Bytes (  99.55 kByte/s)
Errors:                 0
Checks:                 3
Transferred:            2
Elapsed time:  12h49m30.5s
Transferring:
 *                                      DBBackup: 100% done. avg:  100.7, cur:  222.2 kByte/s. ETA: 0s

2016/05/08 11:58:31 
Transferred:   4706720768 Bytes (  99.42 kByte/s)
Errors:                 0
Checks:                 3
Transferred:            2
Elapsed time:  12h50m30.5s
Transferring:
 *                                      DBBackup: 100% done. avg:  100.4, cur:    4.1 kByte/s. ETA: 0s

2016/05/08 11:59:31 
Transferred:   4706720768 Bytes (  99.29 kByte/s)
Errors:                 0
Checks:                 3
Transferred:            2
Elapsed time:  12h51m30.5s
Transferring:
 *                                      DBBackup: 100% done. avg:  100.1, cur:    0.1 kByte/s. ETA: 0s

2016/05/08 12:00:07 DBBackup: Failed to copy: googleapi: Error 404: File not found: 0B2VS5Wi09HJnMnVPM054aEd6dVE, notFound
2016/05/08 12:00:07 Attempt 3/3 failed with 1 errors

**Comment by rtg20** [comment]
Here's another, similar error. This is with 1.29. 

2016/05/31 08:24:24 DBBackup: Failed to copy: Post https://www.googleapis.com/upload/drive/v2/files?alt=json&uploadType=resumable&upload_id=AEnB2UoISsLPR49CkviX37oJ6Ns_xCsFwsdLGzvDNldOLvZkLW_yEowOC0H32VM-Xjwxxog1y--fgY910VTnZEWt9eO5MDMfCQ: write tcp 192.168.1.2:64128->216.58.219.10:443: wsasend: An existing connection was forcibly closed by the remote host.
2016/05/31 08:24:25 Attempt 3/3 failed with 1 errors

**Comment by ncw** [comment]
How big was the file it got stuck on?

Can you try again with the `-v` flag and see if it does some low level retries?

**Comment by rtg20** [comment]
It's a 2 GB file. Today, it restarted on its own:

 *                                      DBBackup: 71% done. avg:   93.4, cur:    0.0 kByte/s. ETA: 2247384h53m52.580896768s

2016/06/01 03:55:39 DBBackup: Failed to copy: Post https://www.googleapis.com/upload/drive/v2/files/0B2VS5Wi09HJnejUtT0xHaThVb1U?alt=json&setModifiedDate=true&uploadType=resumable&upload_id=AEnB2UrJTaiZUF5Bc6EyEC8VjXTWxIvQNkSaManUpxCGphBg8J9Pp6090GfavS0IE6XYM7yTgYlUbffft2Oy34mNsLD98uWzNA: write tcp 192.168.1.2:64941->216.58.219.42:443: wsasend: An existing connection was forcibly closed by the remote host.
2016/06/01 03:55:41 Attempt 1/3 failed with 1 errors
2016/06/01 03:55:41 Google drive root 'RoboBackup/Tuesday/AVImarkSQL/DBBackup': Building file list
2016/06/01 03:55:41 Google drive root 'RoboBackup/Tuesday/AVImarkSQL/DBBackup': Waiting for checks to finish
2016/06/01 03:55:41 Google drive root 'RoboBackup/Tuesday/AVImarkSQL/DBBackup': Waiting for transfers to finish
2016/06/01 03:56:29 
Transferred:   1577058304 Bytes (  94.91 kByte/s)
Errors:                 0
Checks:                 1
Transferred:            1
Elapsed time:  4h30m26.1s
Transferring:



It's the only file that's causing problems, but by far the most important (our entire database!). We backup every day and I reckon it properly backs up maybe 6 out of 7 times per week. Would be great to improve this, do you have any ideas? I will add the -v flag for the run tonight. thanks!

**Comment by ncw** [comment]
If you could post a log with `-v` that would be very helpful. Of if you wanted to email me with it privately that would be fine too ( nick@craig-wood.com ).

I want to make sure the low-level retries are working with the beta for that `wsaend` error before speculating on how to improve the situation!

Thanks

Nick

**Comment by rtg20** [comment]
Thanks. Looks like it worked great last night. Next time it fails I'll post
the log.

**Comment by rtg20** [comment]
ok it failed again, please see here.

2016/06/06 08:49:20 
Transferred:   3388997632 Bytes (  98.55 kByte/s)
Errors:                 0
Checks:                 1
Transferred:            2
Elapsed time:  9h19m41.4s
Transferring:
 *                                      DBBackup: 35% done. avg:  115.9, cur:   25.9 kByte/s. ETA: 14h36m56s

2016/06/06 08:50:09 DBBackup: Failed to copy: Post https://www.googleapis.com/upload/drive/v2/files?alt=json&uploadType=resumable&upload_id=AEnB2Ur6M7qFEzCEKeC5vehnlVQMb-SwPzs20NFThl0jvzmxime4xhDkl7c7-OSa_D2v0Uz-ddR5cXucRRAXAjL6flsH12BxHA: write tcp 192.168.1.2:58128->216.58.216.10:443: wsasend: An existing connection was forcibly closed by the remote host.
2016/06/06 08:50:09 DBBackup: Removing failed copy
2016/06/06 08:50:10 Google_Drive: Saving new token in config file
2016/06/06 08:50:10 DBBackup: Failed to remove failed copy: googleapi: got HTTP response code 404 with body: Not Found
2016/06/06 08:50:10 Attempt 3/3 failed with 1 errors
2016/06/06 08:50:10 Go routines at exit 6




please advise. thank you so much!!!!

**Comment by rtg20** [comment]
Just emailed the entire log to you, did you receive?

Thanks

Richard

**Comment by ncw** [comment]
Thanks for the log.  I can see the retry didn't work :-(  You can see it trying the chunks, and when it gets the `wsaend` error, it just gives up.

I have an idea as to why - I'll post a beta for you to try in a little while!

**Comment by rtg20** [comment]
Thank you!

**Comment by ncw** [comment]
Here is a new beta for you to try - hopefully this will work!

http://pub.rclone.org/v1.29-1-gbb75d80-53-gf17cb1b%CE%B2/

**Comment by rtg20** [comment]
Thanks! I'll try it tonight and report back.

**Comment by ncw** [comment]
Third time lucky!

http://pub.rclone.org/v1.29-1-gbb75d80-55-g7fe653c%CE%B2/

**Comment by ncw** [comment]
This appears to be fixed now :-)

Follow up bug in #520
