### ISSUE TITLE
Trace/breakpoint trap

### ISSUE THREAD

**Issue by pjbca** [ncw/rclone#447]
"Trace/breakpoint trap" error occurs when I run "rclone" from command line.
This is a show-stopper, cannot run rclone.
Rclone version: rclone-v1.29-linux-386

Fresh download and unzip of binary using this procedure:

wget http://downloads.rclone.org/rclone-v1.29-linux-386.zip
unzip rclone-v1.29-linux-386.zip
cd rclone-v1.29-linux-386
#copy binary file
sudo cp rclone /usr/sbin/
sudo chown root:root /usr/sbin/rclone
sudo chmod 755 /usr/sbin/rclone
#install manpage
sudo mkdir -p /usr/local/share/man/man1
sudo cp rclone.1 /usr/local/share/man/man1/
sudo mandb 

System info:
Amazon virtual machine (instance)

Linux distro: (output from cat /etc/*-release at command line)
NAME="Amazon Linux AMI"
VERSION="2016.03"
ID="amzn"
ID_LIKE="rhel fedora"
VERSION_ID="2016.03"
PRETTY_NAME="Amazon Linux AMI 2016.03"
ANSI_COLOR="0;33"
CPE_NAME="cpe:/o:amazon:linux:2016.03:ga"
HOME_URL="http://aws.amazon.com/amazon-linux-ami/"
Amazon Linux AMI release 2016.03

CPU info (output from lscpu at command line):
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                1
On-line CPU(s) list:   0
Thread(s) per core:    1
Core(s) per socket:    1
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 62
Model name:            Intel(R) Xeon(R) CPU E5-2670 v2 @ 2.50GHz
Stepping:              4
CPU MHz:               2494.080
BogoMIPS:              4988.16
Hypervisor vendor:     Xen
Virtualization type:   full
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              25600K
NUMA node0 CPU(s):     0

**Comment by ncw** [comment]
Try the amd64 version would be my guess.

**Comment by marrco** [comment]
same issue here with 1.27 and 1.29 on a debian jessie OVZ virtual server. 
1.27 used to work without issues. Problem happened after an apt-get upgrade

**Comment by ncw** [comment]
Are you using the 32 bit or 64 bit version of rclone?  What about your OS is it 32 or 64 bit?

Can you send a log of the error please?

I suspect this is the problem: http://william.shallum.net/random-notes/32-bit-golang-trace-breakpoint-trap-modify_ldt-enosys

So can you try `echo 1 > /proc/sys/kernel/modify_ldt` ?

**Comment by ncw** [comment]
Looks like this is a known issue in the go runtime which will be fixed for the next go release (due on around 1st August) golang/go#14795 .

Here is a release of rclone compiled with go-tip for you to try

http://pub.rclone.org/rclone-v1.29-29-gcadf202-tip.zip

**Comment by joe-walker** [comment]
I have had the same problem on a 32-bit CentOS server with rclone 1.27 and 1.29. ncw's version compiled with go-tip fixed the problem.

**Comment by marrco** [comment]
Issue was with 32 bit version. Good news is that http://pub.rclone.org/rclone-v1.29-29-gcadf202-tip.zip solved the problem.

thanks ncw!

**Comment by ncw** [comment]
This will be fixed when go 1.7 is released and I make new new rclone release with it - some time after 1st August most likely.

**Comment by ncw** [comment]
Go 1.7 released now so this fix will be in v1.33.

Here is a beta to try: http://pub.rclone.org/v1.32-17-g3f71078%CE%B2/ - please re-open if it doesn't work!

**Comment by pythonInRelay** [comment]
I just got this error when installing the latest version of boostnote .deb from the official website and running the commands above to change ownership... So is this not fixed even in Dec 2019?
