### ISSUE TITLE
support for amazon cloud drive?

### ISSUE THREAD

**Issue by SoundGoof** [ncw/rclone#45]
https://developer.amazon.com/public/apis/experience/cloud-drive/

**Comment by SoundGoof** [comment]
https://github.com/handyman5/acd_fuse

**Comment by mike503** [comment]
+1

I've tried acd_fuse, it seems sporadically slow and weird (I blame FUSE) and there's some visibility differences between the filesystem and the web UI on Amazon which I don't know who is to blame.

One thing I would request is before doing that, if there can be encryption applied beforehand.

file | encrypt > remote

**Comment by ncw** [comment]
A good idea - thanks. It certainly looks possible...

As for encryption - my plan would be to put that into rclone as a encrypting local filesystem which would make it available for all remote file system types.

**Comment by mreinhardt** [comment]
+1

Going to check out the API right now and may submit a pull request within the next couple of weeks.

**Comment by driemekasten** [comment]
+1

Would be nice to see support for acd.

**Comment by shawnbissell** [comment]
+1 
The ACD App for mac provided by Amazon really sucks. I would really like to have rclone support for ACD.

**Comment by jbuchbinder** [comment]
https://github.com/sgeb/acdcli and its backing library https://github.com/sgeb/go-acd might help.

**Comment by ncw** [comment]
@jbuchbinder cool - thanks!

**Comment by hongkongkiwi** [comment]
I'm using ACD_CLI, it's pretty good! Would be great to get this integrated into rclone :-) :+1:

**Comment by resipsa2917** [comment]
Yes, please integrate into rclone :+1:

**Comment by ncw** [comment]
Support for Amazon Cloud Drive is now live in v1.20.  It should be pretty stable, but if you find any issues with it then you know what to do!

Thanks

Nick

**Comment by OldGlory747** [comment]
Any chance of rclone latest ver being compiled for windows? Struggling with compiling on my end.

**Comment by ncw** [comment]
@OldGlory747 Find it on the downloads page http://rclone.org/downloads/ :-)

**Comment by OldGlory747** [comment]
That was my mistake :) Was grabbing it from here:
http://www.craig-wood.com/nick/pub/rclone/windows/
Thanks much!!

**Comment by ncw** [comment]
@OldGlory747 Gosh, those are ancient builds - I didn't even know they were there!  Did you see a link to them somewhere I need to change?

**Comment by OldGlory747** [comment]
Haha, nope, just good old fashion Google.

**Comment by ncw** [comment]
@OldGlory747 Ah OK!  I've deleted those, so hopefully they will disappear from the google search soon. Thanks for letting me know.
