### ISSUE TITLE
OSX Error checking changes on files with accents

### ISSUE THREAD

**Issue by eduardbosch** [ncw/rclone#451]
### VERSION:

rclone v1.29

### COMPUTER:

64bit
Mac OS 10.11.4 Beta (15E33e)
MacBook Pro (Retina, 15-inch, Early 2013)
2,7 GHz Intel Core i7
16 GB 1600 MHz DDR3
NVIDIA GeForce GT 650M 1024 MB

### REMOTE SERVICE:

Google Drive

### COMMAND:

./rclone copy -v "remote:/path/o/file" "path/to/local/file"

### LOG:

There is no strange in the log. See problem section below to know what happens.

----

### PROBLEM:

When I have files with accents in its name, rclone does not find then and downloads it every time and it says "path/to/file: Copied (new)".

If I change the name and remove the accent, everything goes ok. I.e. _revisión.doc_ -> _revision.doc_.

I think this should be a simple problem due to string comparison encoding.

Thanks for this great utility!

**Comment by ncw** [comment]
Can you send a log with `rclone -v` please?

I suspect this is related to unicode normalisation on OS X file systems - see #194

Unfortunately I don't have access to a mac to test :-(

**Comment by eduardbosch** [comment]
Here you are :)

I will be really happy to help with this! I tried to compile the project before, but I've never used GO, so I didn't succeed. Is there any tutorial to compile this project?

Thanks a lot!

```
sudo ./rclone copy -v "drive-edu:/Projectes/ClimbAround/company/documentation/UX&Usability/Análisis de datos qualitativos.docx" "drive-edu/climbaround/company/documentation/UX&Usability/Análisis de datos qualitativos.docx"
Enter configuration password:
password>
2016/04/22 22:47:57 Análisis de datos qualitativos.docx: Couldn't find object
2016/04/22 22:47:57 Local file system at /Users/ebosch/Downloads/rclone-v1.29-osx-amd64/drive-edu/climbaround/company/documentation/UX&Usability limited to 1 objects: Modify window is 1s
2016/04/22 22:47:57 Local file system at /Users/ebosch/Downloads/rclone-v1.29-osx-amd64/drive-edu/climbaround/company/documentation/UX&Usability limited to 1 objects: Building file list
2016/04/22 22:47:58 Google drive root 'Projectes/ClimbAround/company/documentation/UX&Usability/Análisis de datos qualitativos.docx': Couldn't find root: Couldn't find directory: "Projectes/ClimbAround/company/documentation/UX&Usability/Análisis de datos qualitativos.docx"
2016/04/22 22:47:58 Local file system at /Users/ebosch/Downloads/rclone-v1.29-osx-amd64/drive-edu/climbaround/company/documentation/UX&Usability limited to 1 objects: Waiting for checks to finish
2016/04/22 22:47:58 Local file system at /Users/ebosch/Downloads/rclone-v1.29-osx-amd64/drive-edu/climbaround/company/documentation/UX&Usability limited to 1 objects: Waiting for transfers to finish
2016/04/22 22:47:58 Attempt 1/3 failed with 1 errors
2016/04/22 22:47:58 Local file system at /Users/ebosch/Downloads/rclone-v1.29-osx-amd64/drive-edu/climbaround/company/documentation/UX&Usability limited to 1 objects: Building file list
2016/04/22 22:47:58 Google drive root 'Projectes/ClimbAround/company/documentation/UX&Usability/Análisis de datos qualitativos.docx': Couldn't find root: Couldn't find directory: "Projectes/ClimbAround/company/documentation/UX&Usability/Análisis de datos qualitativos.docx"
2016/04/22 22:47:58 Local file system at /Users/ebosch/Downloads/rclone-v1.29-osx-amd64/drive-edu/climbaround/company/documentation/UX&Usability limited to 1 objects: Waiting for checks to finish
2016/04/22 22:47:58 Local file system at /Users/ebosch/Downloads/rclone-v1.29-osx-amd64/drive-edu/climbaround/company/documentation/UX&Usability limited to 1 objects: Waiting for transfers to finish
2016/04/22 22:47:58 Attempt 2/3 failed with 1 errors
2016/04/22 22:47:58 Local file system at /Users/ebosch/Downloads/rclone-v1.29-osx-amd64/drive-edu/climbaround/company/documentation/UX&Usability limited to 1 objects: Building file list
2016/04/22 22:47:58 Google drive root 'Projectes/ClimbAround/company/documentation/UX&Usability/Análisis de datos qualitativos.docx': Couldn't find root: Couldn't find directory: "Projectes/ClimbAround/company/documentation/UX&Usability/Análisis de datos qualitativos.docx"
2016/04/22 22:47:58 Local file system at /Users/ebosch/Downloads/rclone-v1.29-osx-amd64/drive-edu/climbaround/company/documentation/UX&Usability limited to 1 objects: Waiting for checks to finish
2016/04/22 22:47:58 Local file system at /Users/ebosch/Downloads/rclone-v1.29-osx-amd64/drive-edu/climbaround/company/documentation/UX&Usability limited to 1 objects: Waiting for transfers to finish
2016/04/22 22:47:58 Attempt 3/3 failed with 1 errors

Transferred:            0 Bytes (   0.00 kByte/s)
Errors:                 1
Checks:                 0
Transferred:            0
Elapsed time:        9.1s

2016/04/22 22:47:58 Go routines at exit 4
```

**Comment by ncw** [comment]
There are some notes (somewhat brief!) on how to setup go and install rclone for compiling  in [CONTRIBUTING.md](https://github.com/ncw/rclone/blob/master/CONTRIBUTING.md)

Fixing #194 will fix this.

What is needed is a function which normalises OS X filenames into UTF-8, and a function which does the reverse.  These then need to be applied in the local file system (one in cleanUtf8Name). It isn't a completely straight forward change!

**Comment by ncw** [comment]
I have borrowed a mac from work for the weekend to have a go at this.

**Comment by ncw** [comment]
I have fixed this now.  Here is a beta for you to try.  Please re-open the ticket if you have any problems with it!

http://pub.rclone.org/v1.29-16-g8b2f6fa%CE%B2/

**Comment by eduardbosch** [comment]
I've checked this beta and works like a charm!

Sorry not for saying anything before! I wanted to contribute, but I don't have a lot of time now.

Thanks for fixing this :)

**Comment by ncw** [comment]
@eduardbosch thanks for testing! If you get time to contribute one day then at least the test suite will pass on OS X now ;-)
