### ISSUE TITLE
bucket_to_bucket_sync: Failed to copy: NoSuchKey: status code: 404

### ISSUE THREAD

**Issue by fredericofs** [ncw/rclone#452]
During a bucket to bucket sync I end up with many files beign not tranfered along with the following erros msgs:
Failed to copy: NoSuchKey: status code: 404, request id: tx000000000000000ee5b4f-00571a7e33-ce02589-default
No idea of what if the difference between a sucessfully transfered file and those that generated errors.

When filing an issue, please include the following information if
possible as well as a description of the problem.

> What is your rclone version (eg output from `rclone -V`)

> Which OS you are using and how many bits (eg Windows 7, 64 bit)
Raspbian Jessie
> Which cloud storage system are you using? (eg Google Drive
Dream Objects (ceph)
> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone sync remote:bucket1 remote:bucket2

> A log from the command with the `-v` flag (eg output from `rclone -v copy /tmp remote:tmp`)

2016/04/22 16:40:22 S3 bucket temakividsbkp: Waiting for checks to finish
2016/04/22 16:40:22 S3 bucket temakividsbkp: Deletion finished
2016/04/22 16:40:22 filmes/Dreams Are For Everyone-132880568-1280x720.h264: Failed to copy: NoSuchKey: 
	status code: 404, request id: tx000000000000000302dc8-00571a7e26-ceaecab-default
2016/04/22 16:40:22 filmes/Pure Bathing Culture 'Dream the Dare'-77418151.h264: Failed to copy: NoSuchKey: 
	status code: 404, request id: tx000000000000000ee582a-00571a7e26-ce02589-default
2016/04/22 16:40:23 filmes/Let Go Or Be Dragged-145074165-1920x1080.h264: Failed to copy: NoSuchKey: 
	status code: 404, request id: tx000000000000000ef48b5-00571a7e26-cdaa817-default
2016/04/22 16:40:23 filmes/Lakeland Winter-161353632-1920x1080.h264: Failed to copy: NoSuchKey:

**Comment by fredericofs** [comment]
I can succesfully download those same files to local folder using rclone. The problem is exclusive to bucket>bucket sync

**Comment by ncw** [comment]
Bucket to bucket sync uses a server side copy.

I wonder if there is an oddity with that and Ceph.

Did all the files that failed to copy have spaces in the names maybe?

**Comment by ncw** [comment]
It would be interesting if you could run the copy with `--dump-bodies` and paste here failing transaction (remove any Authorization: lines first).

**Comment by ncw** [comment]
I think this is very likely the same problem as #586 - ceph failing to decode the `X-Amz-Copy-Source` header properly.

**Comment by ncw** [comment]
I'm going to close this in favour of #586 where we are waiting for dreamhost to update ceph to fix this problem.
