### ISSUE TITLE
Syntax for conf file ?

### ISSUE THREAD

**Issue by vincegre** [ncw/rclone#453]
Hi

I'm playing with rclone on FreeNAS but I'd like to rclone multiple sources to multiple destinations. After reading documentation it looks like you can setup all rclones to do in the config file but how ? what syntax to use ? Cound not find anything on website !

Thanks for that great tool

Vincèn

> What is your rclone version (eg output from `rclone -V`)
1.29
> Which OS you are using and how many bits (eg Windows 7, 64 bit)
FreeNAS 9.3 64 bits
> Which cloud storage system are you using? (eg Google Drive)
Google Drive Unlimited

**Comment by vincegre** [comment]
No one has any ideas ?

Thanks

**Comment by ncw** [comment]
Rclone syncs one source to one destination at a time.

When you run rclone config it creates a different section in the config file under the name you give it. 

So of you create two remotes, one for Google drive called gd and the other for amazon cloud drive called acd then you can sync to them with two separate commands, eg

    rclone sync /path/to/source gd:backup
    rclone sync /path/to/source acd:backup

I hope that helps!

**Comment by vincegre** [comment]
Thanks but what I'd like is to list in config file all sync to do so it can execute them one by one easily each time I start it from a cron. I'm concerned to create a loop if I start each task automatically in Cron and that a task is restarted when previous same task is still running..

**Comment by ncw** [comment]
I'd suggest you write a little shell script with the syncs you want, and use one of the techniques from here

https://ma.ttias.be/prevent-cronjobs-from-overlapping-in-linux/

To make sure that only one copy of the shell script executes at once

**Comment by vincegre** [comment]
Is it still possible to list all sync to do in the config file so when I run one instance of rclone it executes each sync one after the other ?

**Comment by ncw** [comment]
Not at the moment. I think the best sort of config file for that would be a shell/powershell script.

**Comment by tony5** [comment]
maybe use more then one config file and use the  --config directive in your cron.
should do what you want.
rclone -h for more options

**Comment by ncw** [comment]
I'm going to close this as I think the original question has been answered.
