### ISSUE TITLE
Error when downloading jpgs from Onedrive

### ISSUE THREAD

**Issue by carlos-granados** [ncw/rclone#454]
I am trying to use rclone to sync a Onedrive folder to a Ubuntu machine running in Amazon AWS and I am getting some errors when processing some files. These files are all jpgs and the problems I see are similar to this:

"2016/04/23 19:56:03 Maria Duenas/Mision olvido (252)/cover.jpg: Corrupted on transfer: sizes differ 35395 vs 22482"

I have attached here the file that gives the error. It does not happen with all jpgs, some transfer fine but it only happens with jpg files, does not happen with other kind of files

![cover](https://cloud.githubusercontent.com/assets/1383106/14763738/c70ca34c-0996-11e6-8f5d-e07001aa22a1.jpg)

More info below

> What is your rclone version (eg output from `rclone -V`)

v1.29

> Which OS you are using and how many bits (eg Windows 7, 64 bit)

Ubuntu 64bit running headless in Amazon AWS

> Which cloud storage system are you using? (eg Google Drive)

Onedrive

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

rclone sync granados-onedrive:/Libros/Biblioteca Biblioteca

> A log from the command with the `-v` flag (eg output from `rclone -v copy /tmp remote:tmp`)

Too big to paste here, attaching as doc file
[rclone -log.docx](https://github.com/ncw/rclone/files/233134/rclone.-log.docx)

**Comment by ncw** [comment]
I'm pretty sure this is the same problem as #399

This is caused by a known bug in onedrive which they haven't been fixing for the last 18 months!

I'm leaning towards the `--no-check-size` option as you'll see from that which is a work-around.

**Comment by carlos-granados** [comment]
Yes, that seems the same problem, so I am going to close this. The `--no-check-size` option seems a nice solution

**Comment by ncw** [comment]
I've implemented an `--ignore-size` flag which you can use to work-around this issue.  I've verified it does the right thing.

Here is a beta with that fix in for you to try.

http://pub.rclone.org/v1.29-1-gbb75d80-62-g46135d8%CE%B2/
