### ISSUE TITLE
Automatically syncing while filesystem changes?

### ISSUE THREAD

**Issue by nodegin** [ncw/rclone#457]
Hi, I try to create a text file `text.txt` under `/data/test` then run the command `rclone sync /data/test acd:/test`, and I saw the ACD is updated, then I try to edit the content of `text.txt` but seems rclone doesn't syncing changes.
It there any ability to enable rclone act like Dropbox to sync the filesystem automatically?
Thanks a lot.

> What is your rclone version (eg output from `rclone -V`)
> `rclone v1.29`
> Which OS you are using and how many bits (eg Windows 7, 64 bit)
> `Ubuntu armv7l`
> Which cloud storage system are you using? (eg Google Drive)
> `Amazon Cloud Drive`
> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
> `rclone sync /data/test acd:/test`
> A log from the command with the `-v` flag (eg output from `rclone -v copy /tmp remote:tmp`)

```
2016/04/27 18:56:17 Amazon cloud drive root 'test': Modify window not supported
2016/04/27 18:56:17 Amazon cloud drive root 'test': Building file list
2016/04/27 18:56:17 Amazon cloud drive root 'test': Reading ""
2016/04/27 18:56:18 Amazon cloud drive root 'test': Finished reading ""
2016/04/27 18:56:18 Amazon cloud drive root 'test': Waiting for checks to finish
2016/04/27 18:56:18 Amazon cloud drive root 'test': Starting deletion
2016/04/27 18:56:18 Waiting for deletions to finish
2016/04/27 18:56:18 text.txt: Sizes differ
2016/04/27 18:56:18 Amazon cloud drive root 'test': Waiting for transfers to finish
2016/04/27 18:56:18 Amazon cloud drive root 'test': Deletion finished
2016/04/27 18:56:21 text.txt: Copied (updated existing)
2016/04/27 18:56:21 Amazon cloud drive root 'test': Waiting for deletes to finish (during+after)

Transferred:           12 Bytes (   0.00 kByte/s)
Errors:                 0
Checks:                 1
Transferred:            1
Elapsed time:        8.1s

2016/04/27 18:56:21 Go routines at exit 5
```

**Comment by ncw** [comment]
rclone doesn't run in the background (at the moment) it only syncs when you run it.

If you want to sync regularly then you can run it off cron.

There is a ticket about adding the ability to run as a daemon and listen to file system events #249 - any help appreciated!

Thanks

Nick

**Comment by nodegin** [comment]
Good to know that

**Comment by icaroerasmo** [comment]
any news about this?!

**Comment by radman0x** [comment]
this is late, but wouldn't just a naive "watch -n INTERVAL rclone XXXX" successfully run rclone periodically? I've tested and watch won't start a new process until the previous has finished. This is in response to the comments providing scripts to run rclone in this manner.

**Comment by ncw** [comment]
> this is late, but wouldn't just a naive "watch -n INTERVAL rclone XXXX" successfully run rclone periodically? I've tested and watch won't start a new process until the previous has finished. This is in response to the comments providing scripts to run rclone in this manner.

`watch`- good tip!  You can also run rclone with the `--rc` parameter - you can only have one running per rc port.

**Comment by rifazn** [comment]
How can you have the same effect as `watch` with `--rc`?

**Comment by ncw** [comment]
If you run `--rc` then you can only have one rclone running at once listening to the default port.
