### ISSUE TITLE
whatis parse for rclone(1) failed

### ISSUE THREAD

**Issue by oviliz** [ncw/rclone#458]
Hi,
following the Linux install guide, http://rclone.org/install/, I encountered this error while doing performing the last command, sudo mandb (these are the latest records):
```
Processing manual pages under /usr/local/share/man...
Updating index cache for path `/usr/local/share/man/man1'. Wait...mandb: warning: /usr/local/share/man/man1/rclone.1: whatis parse for rclone(1) failed
done.
Checking for stray cats under /usr/local/share/man...
Checking for stray cats under /var/cache/man/local...
1 man subdirectory contained newer manual pages.
1 manual page was added.
0 stray cats were added.
0 old database entries were purged.
```
I'm trying to install/use rclone v1.29 (rclone-v1.29-linux-amd64) on Ubuntu 14.04 LTS.

Even when trying to grab the rclone version is printing a failed error:
```
root@mysrv:~/rclone-v1.29-linux-amd64# rclone -V
2016/04/28 13:13:41 Failed to load config file "/root/.rclone.conf" - using defaults: open /root/.rclone.conf: no such file or directory
rclone v1.29
```

Is rclone not compatible with Ubuntu 14.04 LTS?

**Comment by ncw** [comment]
I don't think the `whatis parse for rclone(1) failed` is a problem - it is only a warning.  It probably means rclone won't appear in the whatis database.

As for `Failed to load config file "/root/.rclone.conf" - using defaults: open /root/.rclone.conf: no such file or directory` - then next step is to run `rclone config` to make the configuration for the remote fs.

So yes rclone should work fine with ubuntu 14.04 (I develop it on ubuntu!).

**Comment by oviliz** [comment]
Yes, forgot to update. Seem to work properly. Thanks @ncw .
