### ISSUE TITLE
rclone v1.29 : panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by mistur** [ncw/rclone#459]
Hello,

I have a issue when I try to sync 2 buckets from 2 ceph cluster (infernalis). I have tried from 2 hosts, one in Centos 6.7 and one in Ubuntu 16.04

Centos 6.7 : 

> What is your rclone version (eg output from `rclone -V`)

$ rclone -V
rclone v1.29

> Which OS you are using and how many bits (eg Windows 7, 64 bit)

$ cat /etc/redhat-release 
CentOS release 6.7 (Final)
$ uname -a
Linux icadmin006 2.6.32-573.el6.x86_64 #1 SMP Thu Jul 23 15:44:03 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

> Which cloud storage system are you using? (eg Google Drive)

ceph infernalis

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

$ rclone -v  sync testreplicated:Replicated/ betaerasure:Benchmark/

Replicated/ is a directory with ~ 130K files

> A log from the command with the `-v` flag (eg output from `rclone -v copy /tmp remote:tmp`)

$ rclone -v  sync testreplicated:Replicated/ betaerasure:Benchmark/
2016/04/28 15:35:04 testreplicated: Using v2 auth
2016/04/28 15:35:04 betaerasure: Using v2 auth
2016/04/28 15:35:04 S3 bucket Benchmark: Modify window is 1ns
2016/04/28 15:35:04 S3 bucket Benchmark: Building file list
2016/04/28 15:35:20 S3 bucket Benchmark: Starting deletion
2016/04/28 15:35:20 Waiting for deletions to finish
2016/04/28 15:35:20 S3 bucket Benchmark: Deletion finished
2016/04/28 15:35:20 S3 bucket Benchmark: Waiting for checks to finish
2016/04/28 15:35:20 md5sum/32MB/32MB_17690.md5: Copied (new)
2016/04/28 15:35:20 md5sum/32MB/32MB_26704.md5: Copied (new)
2016/04/28 15:35:21 md5sum/32MB/32MB_32049.md5: Copied (new)
2016/04/28 15:35:21 md5sum/32MB/32MB_5217.md5: Copied (new)
2016/04/28 15:35:21 md5sum/256MB/256MB_1992.md5: Copied (new)
2016/04/28 15:35:21 md5sum/32MB/32MB_32560.md5: Copied (new)
2016/04/28 15:35:21 md5sum/64MB/64MB_4014.md5: Copied (new)
2016/04/28 15:35:21 md5sum/32MB/32MB_10146.md5: Copied (new)
2016/04/28 15:35:21 md5sum/64MB/64MB_3508.md5: Copied (new)
2016/04/28 15:35:22 md5sum/64MB/64MB_3643.md5: Copied (new)
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x8b43a5]

goroutine 131 [running]:
panic(0xadd0e0, 0xc82000e0f0)
        /usr/local/go/src/runtime/panic.go:464 +0x3e6
github.com/aws/aws-sdk-go/service/s3/s3manager.(*multiuploader).upload(0xc82023c4e0, 0x7fab180f91a8, 0xc82508c7e0, 0x0, 0x0, 0x0)
        /home/ncw/Code/Go/src/github.com/aws/aws-sdk-go/service/s3/s3manager/upload.go:559 +0xaa5
github.com/aws/aws-sdk-go/service/s3/s3manager.(*uploader).upload(0xc824bf5ae0, 0xc824bf5ae0, 0x0, 0x0)
        /home/ncw/Code/Go/src/github.com/aws/aws-sdk-go/service/s3/s3manager/upload.go:361 +0x9ca
github.com/aws/aws-sdk-go/service/s3/s3manager.Uploader.Upload(0x500000, 0x2, 0x0, 0x2710, 0x7fab18073028, 0xc8200ae1f8, 0xc820116780, 0x0, 0x0, 0x0, ...)
        /home/ncw/Code/Go/src/github.com/aws/aws-sdk-go/service/s3/s3manager/upload.go:329 +0x15a
github.com/ncw/rclone/s3.(*Object).Update(0xc824e799f0, 0x7fab180d31b0, 0xc8204543c0, 0x7fab180d31d8, 0xc820cdd3b0, 0x0, 0x0)
        /home/ncw/Code/Go/src/github.com/ncw/rclone/s3/s3.go:787 +0x4ef
github.com/ncw/rclone/s3.(*Fs).Put(0xc8200a3440, 0x7fab180d31b0, 0xc8204543c0, 0x7fab180d31d8, 0xc820cdd3b0, 0x0, 0x0, 0x0, 0x0)
        /home/ncw/Code/Go/src/github.com/ncw/rclone/s3/s3.go:505 +0x10c
github.com/ncw/rclone/fs.Copy(0x7fab180f9040, 0xc8200a3440, 0x0, 0x0, 0x7fab19f36d78, 0xc820cdd3b0)
        /home/ncw/Code/Go/src/github.com/ncw/rclone/fs/operations.go:236 +0x1934
github.com/ncw/rclone/fs.PairCopier(0xc82040ed80, 0x7fab180f9040, 0xc8200a3440, 0xc8226c0c70)
        /home/ncw/Code/Go/src/github.com/ncw/rclone/fs/operations.go:382 +0x1d7
created by github.com/ncw/rclone/fs.syncCopyMove
        /home/ncw/Code/Go/src/github.com/ncw/rclone/fs/operations.go:597 +0x619

Ubuntu 16.04 :

> What is your rclone version (eg output from `rclone -V`)

$ rclone -V
rclone v1.29

> Which OS you are using and how many bits (eg Windows 7, 64 bit)

$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04 LTS"
$ uname -a
Linux kveikur 4.5.2-040502-generic #201604200335 SMP Wed Apr 20 07:37:26 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

> Which cloud storage system are you using? (eg Google Drive)

ceph infernalis

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

$ rclone -v  sync testreplicated:Replicated/ betaerasure:Benchmark/

Replicated/ is a directory with ~ 130K files

> A log from the command with the `-v` flag (eg output from `rclone -v copy /tmp remote:tmp`)

$ rclone -v  sync testreplicated:Replicated/ betaerasure:Benchmark/
2016/04/28 15:41:32 testreplicated: Using v2 auth
2016/04/28 15:41:32 betaerasure: Using v2 auth
2016/04/28 15:41:32 S3 bucket Benchmark: Modify window is 1ns
2016/04/28 15:41:32 S3 bucket Benchmark: Building file list
2016/04/28 15:41:49 S3 bucket Benchmark: Waiting for checks to finish
2016/04/28 15:41:49 S3 bucket Benchmark: Starting deletion
2016/04/28 15:41:49 Waiting for deletions to finish
2016/04/28 15:41:49 S3 bucket Benchmark: Deletion finished
2016/04/28 15:41:49 md5sum/32MB/32MB_17644.md5: Copied (new)
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x8b43a5]

goroutine 47 [running]:
panic(0xadd0e0, 0xc820010140)
	/usr/local/go/src/runtime/panic.go:464 +0x3e6
github.com/aws/aws-sdk-go/service/s3/s3manager.(*multiuploader).upload(0xc8204e6840, 0x7f1fab060010, 0xc8251e5200, 0x0, 0x0, 0x0)
	/home/ncw/Code/Go/src/github.com/aws/aws-sdk-go/service/s3/s3manager/upload.go:559 +0xaa5
github.com/aws/aws-sdk-go/service/s3/s3manager.(*uploader).upload(0xc8252305a0, 0xc8252305a0, 0x0, 0x0)
	/home/ncw/Code/Go/src/github.com/aws/aws-sdk-go/service/s3/s3manager/upload.go:361 +0x9ca
github.com/aws/aws-sdk-go/service/s3/s3manager.Uploader.Upload(0x500000, 0x2, 0x0, 0x2710, 0x7f1fa0e42450, 0xc820030218, 0xc825236000, 0x0, 0x0, 0x0, ...)
	/home/ncw/Code/Go/src/github.com/aws/aws-sdk-go/service/s3/s3manager/upload.go:329 +0x15a
github.com/ncw/rclone/s3.(*Object).Update(0xc8252de050, 0x7f1faafba1f8, 0xc82024bc20, 0x7f1faafba220, 0xc8209a74f0, 0x0, 0x0)
	/home/ncw/Code/Go/src/github.com/ncw/rclone/s3/s3.go:787 +0x4ef
github.com/ncw/rclone/s3.(*Fs).Put(0xc820067440, 0x7f1faafba1f8, 0xc82024bc20, 0x7f1faafba220, 0xc8209a74f0, 0x0, 0x0, 0x0, 0x0)
	/home/ncw/Code/Go/src/github.com/ncw/rclone/s3/s3.go:505 +0x10c
github.com/ncw/rclone/fs.Copy(0x7f1fab05fea8, 0xc820067440, 0x0, 0x0, 0x7f1fab021a98, 0xc8209a74f0)
	/home/ncw/Code/Go/src/github.com/ncw/rclone/fs/operations.go:236 +0x1934
github.com/ncw/rclone/fs.PairCopier(0xc820066660, 0x7f1fab05fea8, 0xc820067440, 0xc822a04670)
	/home/ncw/Code/Go/src/github.com/ncw/rclone/fs/operations.go:382 +0x1d7
created by github.com/ncw/rclone/fs.syncCopyMove
	/home/ncw/Code/Go/src/github.com/ncw/rclone/fs/operations.go:597 +0x619

**Comment by zioproto** [comment]
@mistur add the details of your rclone.conf file to the ticket.

**Comment by mistur** [comment]
extract of my .rclone.conf :

```
[betaerasure]
type = s3
access_key_id = ***
secret_access_key = ***
region = other-v2-signature
endpoint = https://datasets.localdomain/

[testreplicated]
type = s3
access_key_id = ***
secret_access_key = ***
region = other-v2-signature
endpoint = https://datatest.localdomain/
```

**Comment by ncw** [comment]
A little bit of following the backtrace reveals the crash is here

github.com/aws/aws-sdk-go/service/s3/s3manager/upload.go:559
```go
	return &UploadOutput{
		Location:  *complete.Location, // this is nil
		VersionID: complete.VersionId,
		UploadID:  u.uploadID,
	}, nil
```

Which means that ceph is returning the `CompleteMultipartUploadOutput` struct with a nil `Location`.

I don't know whether this is valid or not but this patch to the AWS library should stop the crash

```patch
diff --git a/service/s3/s3manager/upload.go b/service/s3/s3manager/upload.go
index 4132bcb..b2d1afd 100644
--- a/service/s3/s3manager/upload.go
+++ b/service/s3/s3manager/upload.go
@@ -8,6 +8,7 @@ import (
        "sync"
        "time"
 
+       "github.com/aws/aws-sdk-go/aws"
        "github.com/aws/aws-sdk-go/aws/awserr"
        "github.com/aws/aws-sdk-go/aws/awsutil"
        "github.com/aws/aws-sdk-go/aws/client"
@@ -556,7 +557,7 @@ func (u *multiuploader) upload(firstBuf io.ReadSeeker) (*UploadOutput, error) {
                }
        }
        return &UploadOutput{
-               Location:  *complete.Location,
+               Location:  aws.StringValue(complete.Location),
                VersionID: complete.VersionId,
                UploadID:  u.uploadID,
        }, nil
```

Here is a build of rclone with that patch (for linux/amd64) - let me know what happens with that!  If it works I'll try to upstream the patch to the aws library.

http://pub.rclone.org/rclone-v1.29-aws-patch.zip

**Comment by mistur** [comment]
Hello

sync in progress, your patch seem to fix this issue, thanks !

Yoann

**Comment by ncw** [comment]
Great!  I'll propose it upstream - thanks for testing.

**Comment by Cammy-the-block** [comment]
Howdy, I'm having a similar problem. I tried using the patch to no avail. If I run 

     $ sudo rclone --drive-chunk-size=256M copy /backup-20160504.tar.gz.gpg remote:Backups
I get the following error

     2016/05/05 19:38:07 Google drive root 'Backups': Building file list
    panic: runtime error: invalid memory address or nil pointer dereference
    [signal 0xb code=0x1 addr=0x40 pc=0x4dcfcd]

    goroutine 36 [running]:
    panic(0xae9fc0, 0xc8200120f0)
	    /usr/local/go/src/runtime/panic.go:481 +0x3e6
    github.com/ncw/rclone/fs.readFilesMap(0x7f0871914dd8, 0xc8201111a0, 0x0, 0x0)
	    /home/ncw/Code/Go/src/github.com/ncw/rclone/fs/operations.go:463 +0x17d
    github.com/ncw/rclone/fs.syncCopyMove.func2(0xc82002c030, 0x7f0871914dd8, 0xc8201111a0, 0xc8204b90e0, 0xc8203020c0)
	    /home/ncw/Code/Go/src/github.com/ncw/rclone/fs/operations.go:522 +0x42
    created by github.com/ncw/rclone/fs.syncCopyMove
	    /home/ncw/Code/Go/src/github.com/ncw/rclone/fs/operations.go:528 +0x2be

However if change directories to `/` and run the following command

    $ sudo rclone --drive-chunk-size=256M copy backup-20160504.tar.gz.gpg remote:Backups

then it works perfectly fine.

**Comment by ncw** [comment]
The patch has been accepted upstream which means it will be in the next release :-)

**Comment by hereisderek** [comment]
I'm having the same error (but possibly different cause)

`allen-mac:Dota 2 allenfeng$ rclone copy ./Dota\ 2\ 2019.08.11\ -\ 21.06.30.02.mp4  q:/Video/GameDVR
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x60 pc=0x159fba9]

goroutine 1 [running]:
github.com/rclone/rclone/fs/operations.moveOrCopyFile(0x243f7e0, 0xc0000ee000, 0x2453780, 0xc0005e4780, 0x0, 0x0, 0x7ffeefbffc9e, 0x23, 0x7ffeefbffc9e, 0x23, ...)
        /Users/travis/gopath/src/github.com/rclone/rclone/fs/operations/operations.go:1640 +0xe9
github.com/rclone/rclone/fs/operations.CopyFile(...)
        /Users/travis/gopath/src/github.com/rclone/rclone/fs/operations/operations.go:1743
github.com/rclone/rclone/cmd/copy.glob..func1.1(0xc0005b2200, 0xc000711b08)
        /Users/travis/gopath/src/github.com/rclone/rclone/cmd/copy/copy.go:81 +0xf3
github.com/rclone/rclone/cmd.Run(0xc000330101, 0x30048c0, 0xc000711d38)
        /Users/travis/gopath/src/github.com/rclone/rclone/cmd/cmd.go:234 +0xbb
github.com/rclone/rclone/cmd/copy.glob..func1(0x30048c0, 0xc000330880, 0x2, 0x2)
        /Users/travis/gopath/src/github.com/rclone/rclone/cmd/copy/copy.go:77 +0x129
github.com/rclone/rclone/vendor/github.com/spf13/cobra.(*Command).execute(0x30048c0, 0xc000330720, 0x2, 0x2, 0x30048c0, 0xc000330720)
        /Users/travis/gopath/src/github.com/rclone/rclone/vendor/github.com/spf13/cobra/command.go:830 +0x2ae
github.com/rclone/rclone/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x3001940, 0x5d52438a, 0x3017da0, 0xc0000bc058)
        /Users/travis/gopath/src/github.com/rclone/rclone/vendor/github.com/spf13/cobra/command.go:914 +0x2fc
github.com/rclone/rclone/vendor/github.com/spf13/cobra.(*Command).Execute(...)
        /Users/travis/gopath/src/github.com/rclone/rclone/vendor/github.com/spf13/cobra/command.go:864
github.com/rclone/rclone/cmd.Main()
        /Users/travis/gopath/src/github.com/rclone/rclone/cmd/cmd.go:499 +0x96
main.main()
        /Users/travis/gopath/src/github.com/rclone/rclone/rclone.go:13 +0x20`

**Comment by ncw** [comment]
@hereisderek can you make a new issue with this in please and fill in the issue template - thanks
