### ISSUE TITLE
hangs / downloads 0 ( without verbose)

### ISSUE THREAD

**Issue by fredericofs** [ncw/rclone#461]
When using rclone to sync bucket1 and bucket2 from the same ceph server and user account, bucket1 works flawlessly, bucket2 used to work, now rclone just hangs.

A simple rclone ls or sync command for bucket2 results in hang and after some minutes I see many messages of 0 bytes, exactly like this:

A sync command, result in many messages like this:
Transferred:            0 Bytes (   0.00 kByte/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:      1m0.1s

2016/04/28 14:48:34 
Transferred:            0 Bytes (   0.00 kByte/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:      2m0.1s

For each file...

I am clueless.

When filing an issue, please include the following information if
possible as well as a description of the problem.

> What is your rclone version (eg output from `rclone -V`)
rclone v1.28
> Which OS you are using and how many bits (eg Windows 7, 64 bit)
Raspbian 
> Which cloud storage system are you using? (eg Google Drive)
DreamObjects (CEPH)
> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone copy and rclone ls
> A log from the command with the `-v` flag (eg output from `rclone -v copy /tmp remote:tmp`)

Building file list
2016/04/28 14:47:34 
Transferred:            0 Bytes (   0.00 kByte/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:      1m0.1s

2016/04/28 14:48:34 
Transferred:            0 Bytes (   0.00 kByte/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:      2m0.1s

2016/04/28 14:49:34 
Transferred:            0 Bytes (   0.00 kByte/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:      3m0.1s

2016/04/28 14:50:34 
Transferred:            0 Bytes (   0.00 kByte/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:      4m0.1s

2016/04/28 14:51:34 
Transferred:            0 Bytes (   0.00 kByte/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:      5m0.1s

2016/04/28 14:52:34 
Transferred:            0 Bytes (   0.00 kByte/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:      6m0.1s

2016/04/28 14:53:34 
Transferred:            0 Bytes (   0.00 kByte/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:      7m0.1s

2016/04/28 14:54:34 
Transferred:            0 Bytes (   0.00 kByte/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:      8m0.1s

**Comment by fredericofs** [comment]
Closed as it seems a problem with the server

**Comment by ncw** [comment]
If you get this again then try with -v and -dump-headers and that will give us some idea what is going on.
