### ISSUE TITLE
Bind 0.0.0.0 instead of localhost

### ISSUE THREAD

**Issue by nodegin** [ncw/rclone#469]
I have installed rclone on a machine without GUI.

I try to connect with Google Drive and rclone's OAuth page located at localhost,

so I just use then command `w3m http://127.0.0.1:53682/auth` which browses the page using command line browser w3m

however, w3m seems doesn't got support for JavaScript, so I can't authorize rclone to access.

And because of rclone listening on localhost 127.0.0.1, I cannot browse the webpage using another machine comes with GUI

So modifying rclone and listen on 0.0.0.0 would be a nice idea, thanks a lot.

**Comment by ncw** [comment]
Check out this page which has some different ways of configuring rclone remotely: http://rclone.org/remote_setup/

I don't think binding rclone to 0.0.0.0 would work unfortunately, as as part of the setup of oauth apps you need to specify the actual address used for the return.  127.0.0.1 is what I've specified so that is what you have to use.

**Comment by nodegin** [comment]
@ncw I see, thanks for quick responding.

**Comment by Paradroyd** [comment]
I have this running on several headless PIs. I just did the initial setup on one of them while logged in through ssh, said "no" to automatic  setup, pasted the auth request into my local Chrome, then pasted the answer back into the ssh window, pretty much exactly as described here: http://rclone.org/remote_setup/ 
Then after I had all of the services set up that way, and after securing my rclone config with a password, I just used scp to copy .rcopy.config to my other headless PIs. Now it works on all of them and I didn't have to request 9 different sets of credentials.

This really works amazingly well. I use it with kpcli to access my current keepass database, among other things.
http://www.linux-magazine.com/Online/Blogs/Productivity-Sauce/kpcli-Work-with-KeePass-Databases-from-the-Command-Line

**Comment by nodegin** [comment]
Actually I solved this by installing nginx on the machine and reverse proxying to authorize on another machine

**Comment by ncw** [comment]
@nodegin that is clever! I think `rclone auth` is easier but YMMV!

**Comment by nodegin** [comment]
@ncw I don't know that approach at the time so I used nginx, maybe I try `rclone auth` next time!

**Comment by deive** [comment]
If it helps I `sudo apt-get install chromium` then you can use localhost as it is running from the linux VM.

**Comment by theorician** [comment]
@ncw Hi. I'm really sorry for resurrecting an ancient thread, but I'm just wondering what the exact problem is here. 

AFAIUI, it doesn't actually matter what port the server binds to. As long as what the _browser_ is connecting to is correct, that's all that matters.

In the case that @nodegin suggested here, which is standard ops for docker: 
* the server binds to 0.0.0.0, 
* your redirect URL is still 127.0.0.1, 
* I'll open up 127.0.0.1 in my browser,

and everybody is happy. The redirect goes back to 127.0.0.1 which will be routed into the container.

What part am I missing here?

**Comment by ncw** [comment]
@theorician interesting idea and would work perfectly in docker containrs.

We bind to localhost for security reasons - rclone doesn't ever bind listening sockets to anything other than 127.0.0.1 by default - it takes specific user action to change it.

I'd accept a PR to make it configurable.

**Comment by theorician** [comment]
Yeah this is something that's strictly for use in a container environment.

Unfortunately I know no Go, but I'll have a poke around. Might take me a while. :)

**Comment by ncw** [comment]
@theorician what you need to do is make this

https://github.com/rclone/rclone/blob/927e721a25aa720bc28b2be463d4cae049e80651/lib/oauthutil/oauthutil.go#L42-L43

Configurable with a flag. Or maybe it could auto detect running in a container?

**Comment by ginjo** [comment]
@ncw  thanks for pointing out the location in the source code. I made a small change, built the binary, and my problem is solved! I can now run rclone entirely within a Docker container, and I can connect to the auth server from outside the container.

@theorician , building Go binaries is pretty simple, especially if you do it within a container of the official Go image from Dockerhub.
* Git clone the rclone repo.
* Run a golang container, making sure to mount the rclone repo within it.
* Cd to the rclone repo, ```go build```.

One thing to note is that the ```bindAddress``` variable in the code referenced by @ncw is unfortunately used for settings other than just the http-listen bind address. If you change the main definition of ```bindAddress```, it will also be used in the auth server URL, the redirect URL and the token URL, which of course won't work. So instead, I only changed the actual bind-address argument in the call to the ```net.Listen``` method.

Quick-n-dirty hard coded change [rclone/lib/oauthutil/oauthutil.go](https://github.com/rclone/rclone/blob/927e721a25aa720bc28b2be463d4cae049e80651/lib/oauthutil/oauthutil.go#L849)
```s.listener, err = net.Listen("tcp", "0.0.0.0:53682")```

To improve the code properly, one would probably want to separate the ```bindAddress``` var from its other uses and create a new var for those other uses.

If anyone is interested in my modified binary (from rclone master 2023-07-27, alpine linux 3.18.0), I can post it somewhere.

**Comment by ncw** [comment]
This should really be a config flag - if you wanted to make a PR for that then I'd take it @theorician 

I note also that we came up with a method of using an ssh tunnel which is quite easy and might work in your case: https://rclone.org/remote_setup/#configuring-using-ssh-tunnel
