### ISSUE TITLE
Rclone Crashes on panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by Cammy-the-block** [ncw/rclone#471]
Howdy, I'm having a similar problem. I am running the rclone version from [here.](https://github.com/ncw/rclone/issues/459#issuecomment-215465624) I'm running Ubuntu 15.10 64 bit with 16GB of RAM and trying to upload to Google Drive. I tried using the patch to no avail. If I run 

     $ sudo rclone --drive-chunk-size=256M copy /backup-20160504.tar.gz.gpg remote:Backups
I get the following error

    sudo rclone --drive-chunk-size=256M -v copy /backup-20160504.tar.gz.gpg remote:Backups
    2016/05/05 19:59:20 backup-20160504.tar.gz.gpg: Failed to stat /home/cameron/backup-20160504.tar.gz.gpg: lstat /home/cameron/backup-20160504.tar.gz.gpg: no such file or directory
    2016/05/05 19:59:21 Google drive root 'Backups': Modify window is 1ms
    2016/05/05 19:59:21 Google drive root 'Backups': Building file list
    panic: runtime error: invalid memory address or nil pointer dereference
    [signal 0xb code=0x1 addr=0x40 pc=0x4dcfcd]

    goroutine 37 [running]:
    panic(0xae9fc0, 0xc8200140f0)
	    /usr/local/go/src/runtime/panic.go:481 +0x3e6
    github.com/ncw/rclone/fs.readFilesMap(0x7f055e3a1e78, 0xc8201111a0, 0x0, 0x0)
    	/home/ncw/Code/Go/src/github.com/ncw/rclone/fs/operations.go:463 +0x17d
    github.com/ncw/rclone/fs.syncCopyMove.func2(0xc8201b0048, 0x7f055e3a1e78, 0xc8201111a0, 0xc820449ea0, 0xc82046e420)
	    /home/ncw/Code/Go/src/github.com/ncw/rclone/fs/operations.go:522 +0x42
    created by github.com/ncw/rclone/fs.syncCopyMove
    	/home/ncw/Code/Go/src/github.com/ncw/rclone/fs/operations.go:528 +0x2be

However if change directories to `/` and run the following command

    $ sudo rclone --drive-chunk-size=256M -v copy backup-20160504.tar.gz.gpg remote:Backups

then it works, just with speeds alternative between 2000 kBytes/s and 0 kBytes/s.

   
    2016/05/05 20:00:56 pacer: Rate limited, increasing sleep to 2s
    2016/05/05 20:00:56 pacer: low level retry 1/10
    2016/05/05 20:00:56 pacer: low level retry 2/10
    2016/05/05 20:00:59 pacer: Reducing sleep to 10ms
    2016/05/05 20:01:01 Google drive root 'Backups': Modify window is 1ms
    2016/05/05 20:01:01 Google drive root 'Backups': Building file list
    2016/05/05 20:01:01 Google drive root 'Backups': Finished reading 
    2016/05/05 20:01:01 Google drive root 'Backups': Waiting for checks to finish
    2016/05/05 20:01:01 Google drive root 'Backups': Waiting for transfers to finish
    2016/05/05 20:01:02 backup-20160504.tar.gz.gpg: Sending chunk 0 length 268435456
    2016/05/05 20:02:01 
    Transferred:    268435456 Bytes (4074.56 kByte/s)
    Errors:                 0
    Checks:                 0
    Transferred:            0
    Elapsed time:      1m4.3s
    Transferring:
     *                    backup-20160504.tar.gz.gpg:  4% done. avg: 4397.0, cur: 5475.5 kByte/s. ETA: 16m8s

    2016/05/05 20:03:01 
    Transferred:    268435456 Bytes (2108.34 kByte/s)
    Errors:                 0
    Checks:                 0
    Transferred:            0
    Elapsed time:      2m4.3s
    Transferring:
     *                    backup-20160504.tar.gz.gpg:  4% done. avg: 2191.5, cur:  100.1 kByte/s. ETA: 14h42m52s

    2016/05/05 20:04:01 
    Transferred:    268435456 Bytes (1422.09 kByte/s)
    Errors:                 0
    Checks:                 0
    Transferred:            0
    Elapsed time:      3m4.3s
    Transferring:
     *                    backup-20160504.tar.gz.gpg:  4% done. avg: 1459.4, cur:    1.8 kByte/s. ETA: 804h34m56s

    2016/05/05 20:05:01 
    Transferred:    268435456 Bytes (1072.88 kByte/s)
    Errors:                 0
    Checks:                 0
    Transferred:            0
    Elapsed time:      4m4.3s
    Transferring:
     *                    backup-20160504.tar.gz.gpg:  4% done. avg: 1094.0, cur:    0.0 kByte/s. ETA: 43993h52m42s

    2016/05/05 20:06:01 
    Transferred:    268435456 Bytes ( 861.36 kByte/s)
    Errors:                 0
    Checks:                 0
    Transferred:            0
    Elapsed time:      5m4.3s
    Transferring:
     *                    backup-20160504.tar.gz.gpg:  4% done. avg:  874.9, cur:    0.0 kByte/s. ETA: 2405547h53m10s

    2016/05/05 20:07:01 
    Transferred:    268435456 Bytes ( 719.51 kByte/s)
    Errors:                 0
    Checks:                 0
    Transferred:            0
    Elapsed time:      6m4.3s
    Transferring:
     *                    backup-20160504.tar.gz.gpg:  4% done. avg:  728.9, cur:    0.0 kByte/s. ETA: 0s

    2016/05/05 20:07:51 backup-20160504.tar.gz.gpg: Sending chunk 268435456 length 268435456
    2016/05/05 20:08:01 
    Transferred:    536870912 Bytes (1235.55 kByte/s)
    Errors:                 0
    Checks:                 0
    Transferred:            0
    Elapsed time:      7m4.3s
    Transferring:
     *                    backup-20160504.tar.gz.gpg:  9% done. avg: 1249.4, cur: 9280.2 kByte/s. ETA: 9m3s

**Comment by ncw** [comment]
I think this is the root cause of the error

    2016/05/05 19:59:20 backup-20160504.tar.gz.gpg: Failed to stat /home/cameron/backup-20160504.tar.gz.gpg: lstat /home/cameron/backup-20160504.tar.gz.gpg: no such file or directory

It shouldn't cause a nil pointer deref - I'll investigate why it does that later.

**Comment by ncw** [comment]
I've fixed this now.

Here is a beta for you to try - please re-open the ticket if you have issues with it.

Thanks

http://pub.rclone.org/v1.29-18-gd205dc2%CE%B2/

PS The strange upload bandwidths you see are caused by the large chunk size you are using.  You can see by the overall stats that the transfer is progressing in a regular fashion.

**Comment by Cammy-the-block** [comment]
Thank you so much! It works with the download you provided. 

What is the recommend chunk size in terms of performance? I have 16 GB of RAM so memory usage certainly isn't a large issue.

**Comment by ncw** [comment]
Here is the result of a test I did so the bigger the better!

![drive-speed](https://cloud.githubusercontent.com/assets/536803/14474109/379b642e-00f3-11e6-80c1-7aacaea7f197.png)
