### ISSUE TITLE
Implement `copyto` and `moveto` for single file copies and moves

### ISSUE THREAD

**Issue by nodegin** [ncw/rclone#476]
Hi, just wondering if I can specify a filename when copying a file to destination.

Let's say I have a file called `0123456789.jpg` under `/tmp`,

and I want to upload to my Google Drive's `/images` with filename `hello.jpg`

so I try to run `rclone copy /tmp/0123456789.jpg gdrive:/images/hello.jpg`

but this command seems going to create 2 folder in Drive: `images` and `hello.jpg`

so the image resulted in `/images/hello.jpg/0123456789.jpg`.

Is there any method to achieve something like custom filename?

Maybe I missed something in the docs, if so really sorry for that,

thank you and have a nice day.

**Comment by hashbackup** [comment]
Here's what I did in HashBackup:

1. Create a directory in /tmp.  The name doesn't matter, call it xyz
2. link or copy 0123456789.jpg to /tmp/xyz/hello.jpg
3. rclone copy /tmp/xyz gdrive/images
4. rm -rf /tmp/xyz

**Comment by nodegin** [comment]
@hashbackup Yes, this would be the last resort if rclone doesn't supports custom filename...

**Comment by ncw** [comment]
rclone doesn't support custom filenames for the copy at the moment.  All the machinery is there, rclone just doesn't have a way to express it.  A new command `copyfile` might be the way to go.

**Comment by nodegin** [comment]
@ncw that's sounds good, how about `copyto`?

**Comment by ncw** [comment]
@nodgin good!  There is also the related `moveto`

**Comment by ncw** [comment]
I'm going to implement two new commands `cp` and `mv` which will work like their unix counterparts and will fix this problem.

**Comment by ncw** [comment]
I changed my mind after some effort trying to implement the semantics of `cp` and `mv` which really don't fit a system that needs lots of retries (they aren't idempotent).

So I implemented `moveto` and `copyto` as originally planned.

Find a beta here http://beta.rclone.org/v1.34-43-gc265f45/ (will be uploaded in 15-30 mins).
