### ISSUE TITLE
Configurations requiring a web browser

### ISSUE THREAD

**Issue by jpfleury** [ncw/rclone#477]
Hi,

It's not a bug report but a question about configurations requiring a web browser, for example Hubic. Is it only for the initial configuration, then we'll be able to run rclone indefinitely in a script to interact with our cloud account without any manual intervention?

Thanks a lot!

**Comment by klauspost** [comment]
What is your question?

**Comment by ncw** [comment]
You only need the web browser for the initial configuration. Rclone will run fine after that without. 

You can also configure rclone remotely - see http://rclone.org/remote_setup/

**Comment by jpfleury** [comment]
Thanks a lot for this quick answer!
