### ISSUE TITLE
Does rclone support hard links?

### ISSUE THREAD

**Issue by tgharib** [ncw/rclone#478]
> What is your rclone version (eg output from `rclone -V`)
v1.29
> Which OS you are using and how many bits (eg Windows 7, 64 bit)
Archlinux 64-bit
> Which cloud storage system are you using? (eg Google Drive)
Google Drive

Does rclone support hard links? I tried looking for information but couldn't find anything.

**Comment by ncw** [comment]
rclone doesn't care whether a file is a hardlink or not (and neither does linux in general) so will transfer it just find.

```
$ echo "hello" > a
$ ln a b
$ ls -l
total 8
-rw-rw-r-- 2 ncw ncw 6 May  9 11:38 a
-rw-rw-r-- 2 ncw ncw 6 May  9 11:38 b
```

If you try to sync that directory, rclone will sync files a and b, but it will treat them as completely separate so sync the data twice.

rclone doesn't support anything like the `-H` flag for rsync.

**Comment by tgharib** [comment]
Ah, thanks for the info! Also, I just realized the H flag would be impossible since cloud providers don't support hard links.

**Comment by brianjmurrell** [comment]
> Ah, thanks for the info! Also, I just realized the H flag would be impossible since cloud providers don't support hard links.

This is not a universal truth and it's a shame that rclone does not preserve hard links.

**Comment by Masamune3210** [comment]
I mean it's open source, if you have the talent, time, and want to have it implemented you could give it a shot
