### ISSUE TITLE
how to write a plugin to support another storage type?

### ISSUE THREAD

**Issue by listeng** [ncw/rclone#479]
I want to write a plugin for other object storage service which I'm using like s3, but I didn't find any document about it. Could you write some text about it? Thanks.

**Comment by ncw** [comment]
There are some notes in [CONTRIBUTING.md ](https://github.com/ncw/rclone/blob/master/CONTRIBUTING.md).  Not exactly a step by step guide, but it will give you a starting point!

Start by studying one of the other remotes (if it is like s3 then start from there).
