### ISSUE TITLE
Drive: "Shared with me" not visible

### ISSUE THREAD

**Issue by philiprhoades** [ncw/rclone#48]
I got rclone working without too much trouble (Fedora 21 x86_64) - compared to gsync - it is very nice! - thanks!

. . but it looks like using "lsd" does not show the "Shared with me" folder - is that fixable? 

More thanks in advance!

Regards,
Phil.

**Comment by ncw** [comment]
It probably needs a/another directory traversal with the `sharedWithMe` flag
set in the directory listing...

Perhaps it is possible to add `(sharedWithMe or !sharedWithMe)` [docs](https://developers.google.com/drive/web/search-parameters)

**Comment by glahue** [comment]
Has there been any progress on this?

**Comment by ncw** [comment]
@glahue alas no! Pull requests always appreciated ;-)

**Comment by mcoffin** [comment]
For people coming to this issue from a search, you can workaround this and access the files by adding things from *Shared with Me* to *My Drive* with the *Add to Drive* option, then just accessing them as one would normally from `rclone`.

**Comment by ncw** [comment]
@mcoffin thanks for that

**Comment by doplu** [comment]
Hello, The tip for "mcoffin" is nice but when your Google Drive is almost full, it is annoying. In my case I have "Google Photo" folders from relatives in "Shared with me". But currently, I can just make a copy ("add to drive") once in a while and each time I am not sure how much space I will need. ;( Also I noticed that the content of the folder "Shared with me"  https://drive.google.com/drive/shared-with-me is different than the content of https://drive.google.com/drive/search?q=-owner:me Here appears all google drive links that the user has click through in the past (not just the documents inside "Shared with me")! It would be nice if this could also be copied. ;) Thanks in advance ;)

**Comment by mcoffin** [comment]
Well adding it to your drive I don't think takes up additional amounts of your storage space, but I could be wrong.

**Comment by doplu** [comment]
@mcoffin , Many thanks I haven't realized yet that it didn't count against my Google Drive storage !
Source:
_Does "Add to My Drive" mean that a file's size will now also be counted against my capacity?_ 
https://productforums.google.com/forum/#!topic/drive/ktqxJnRBHno

These infos may also help others :
_Does removing your access to folders in "my drive" delete them from your drive?_
https://productforums.google.com/forum/#!topic/drive/VSquOTiKsZA

_Can I safely rename the Google Photos folder?_
https://productforums.google.com/forum/#!topic/drive/bzT-st9nlNI

Thanks again ;)

**Comment by jacobperron** [comment]
> For people coming to this issue from a search, you can workaround this and access the files by adding things from Shared with Me to My Drive with the Add to Drive option, then just accessing them as one would normally from rclone.

Running into this issue on OneDrive, but this solution does not appear to work. 

There is only one directory on my remote drive, `TheirSharedDir`, which I added to my drive after it was shared with me. Attempting to list the directories gives an empty result:
```sh
$ rclone lsd MyOneDrive:
```
However, the directory does appear as a file:
```sh
$ rclone ls MyOneDrive:
        0 TheirSharedDir
```

Attempting to copy from remote to my local machine throws the following error:
```sh
2017/03/02 11:11:51 ERROR : TheirSharedDir: Failed to copy: failed to open source object: itemNotFound: The specified item does not exist, or does not have content.
2017/03/02 11:11:51 ERROR : Attempt 1/3 failed with 1 errors and: failed to open source object: itemNotFound: The specified item does not exist, or does not have content.
2017/03/02 11:11:52 ERROR : TheirSharedDir: Failed to copy: failed to open source object: itemNotFound: The specified item does not exist, or does not have content.
2017/03/02 11:11:52 ERROR : Attempt 2/3 failed with 1 errors and: failed to open source object: itemNotFound: The specified item does not exist, or does not have content.
2017/03/02 11:11:52 ERROR : TheirSharedDir: Failed to copy: failed to open source object: itemNotFound: The specified item does not exist, or does not have content.
2017/03/02 11:11:52 ERROR : Attempt 3/3 failed with 1 errors and: failed to open source object: itemNotFound: The specified item does not exist, or does not have content.
2017/03/02 11:11:52 Failed to copy: failed to open source object: itemNotFound: The specified item does not exist, or does not have content.
```

Any ideas?

**Comment by ncw** [comment]
@jacobperron I think this is a separate issue as this is about Google Drive in particular.

So can you open a new issue with the info above in please?

Thanks

**Comment by jacobperron** [comment]
@ncw Done -> #1200

**Comment by qnorsten** [comment]
I just wanted to update everyone interest in this issue. 

I decided to try and learn some go programming by trying  to implement this feature with a similar to solution to one of the alternatives mentioned inhttps://github.com/ncw/rclone/issues/885#issuecomment-286143858 for Team Drives: 

That is to create a Pseudo Directory "Shared with Me" and within that a all the shared directories and files that the api lists. 
But I might have taken on more than I can chew right now.  I have no experience coding in the GO-language and I am not really familiar with the rclone codebase yet. 

In theory it should not be that difficult passing the flag sharedWithMe to the query in list all, lists the root of the Shared with me folder at least. 
I should be able to figure out after a lot of trial and error, how to modify the code to do both the regular listing and the sharedWithMe listing. But I am not sure how to implement the Pseudo folder.
Do you have any idea about that @ncw ? Or is there a better solution then implementing a pseudo folder? 

Will try and keep you updated with my progress, but might need some tips and help later on. The finished code will also probably look like a mess and require some clean up.

**Comment by gustavorochakv** [comment]
You can get the Shared With me Content passing "sharedWithMe" on the query string, that should work on both v2 and v3 of the Drive API (I believe go is using v2).

I'm not sure how you're planning to add this, but it would probably be something along the lines of:

`query = append(query, "sharedWithMe")`

inside the listAll function.

Just bear in mind that my knowledge of go is close to non existent, that's what I came up with after a quick look at the drive.go source file, so I might be completely off on this one.

**Comment by ncw** [comment]
I think making a Pseudo directory is probably the wrong direction to go in though as it doesn't really fit the way drive works and if you work against the grain of the underlying tech then it causes you problems further down the way!

I'd make a command line flag to start with as that is easy

```go
	driveSharedWithMe      = fs.BoolP("drive-shared-with-me", "", false, "Only show files that are shared with me")
```

then in listAll do something like

```go
	if *driveSharedWithMe {
		query = append(query, "sharedWithMe")
        }
```

And see if that works.

If it does, then adding a config option as well would be the thing to do I expect...

**Comment by danny8376** [comment]
Find some problem with this approach with copy/sync

**Comment by ncw** [comment]
@danny8376 good point.  If it was a config option then you could have a shared with me remote and a non shared with me remote which would allow copying like that.  Perhaps a bit inconvenient.

**Comment by ncw** [comment]
Please find the first iteration of --drive-shared-with-me in

    https://beta.rclone.org/v1.36-11-g9ab4c19/ (uploaded in 15-30 mins)

Thanks @danny8376

**Comment by lcasey001** [comment]
If I understood the PR correctly if this is enabled it will only show the "shared with me" files/directories only and not the main files/directories ? If you were to then use rclone to mount the parent would you then be able to copy between then two via server side ?

**Comment by ncw** [comment]
@lcasey001 you are correct - this won't allow you to do a server side copy...

**Comment by uglygus** [comment]
I can report that `--drive-shared-with`-me is working beautifully for me using:
rclone v1.36-22-gbc25190β

Thank you for implementing this!

**Comment by carlyuanliu** [comment]
I successfully archived the 'shared with' directory using --drive-shared-with-me on version 1.29.  Now I have a copy of the shared files (elsewhere), in case they withdraw the sharing for whatever reason.
Thanks to the wonderful people working on the amazing product.

**Comment by ncw** [comment]
@carlyuanliu - thanks!

I'm going to close this now since `--drive-shared-with-me` is the fix for this issue!  Any other issues, please make a new one.

**Comment by pras92** [comment]
I know the topic is closed, just wanted to share this anyway, since it's reported that `--drive-shared-with-me` doesn't support server side copy. 

Maybe the root ID is a feature introduced after closure of this topic, still i wanted to leave this for users who might stumble with this issue in future. 

I just created a new remote for the required shared drive, using root` root_folder_id`. The said ID for a shared drive is much smaller in length than a regular folder I, i used it regardless and it worked.

**Comment by ludwig-gramberg** [comment]
> I know the topic is closed, just wanted to share this anyway, since it's reported that `--drive-shared-with-me` doesn't support server side copy.
> 
> Maybe the root ID is a feature introduced after closure of this topic, still i wanted to leave this for users who might stumble with this issue in future.
> 
> I just created a new remote for the required shared drive, using root` root_folder_id`. **The length of the said ID for a shared drive is much smaller** than that for a regular folder, i used it regardless and it worked. Server side copy works this way.

I can confirm: two folders have been shared with me. I had to define two targets each with the `root_folder_id` of the shared folder and then I was able to sync them.
