### ISSUE TITLE
Scale back request rate on "429: Rate exceeded" errors

### ISSUE THREAD

**Issue by DairyDTP** [ncw/rclone#482]
Hitting a bunch of these errors on a rclone, version v1.29, Ubuntu 14.04, 64bit, Amazon Cloud Drive

```
 Received error: HTTP code 429: "429 Too Many Requests", reponse body: {"logref":"<uuid>","message":"Rate exceeded","code":""}
  low level retry 1/10
 Received error: HTTP code 429: "429 Too Many Requests", reponse body: {"logref":"<uuid>","message":"Concurrent Access on same node. Please back off.","code":""}
 Received error: HTTP code 500: "500 Internal Server Error", reponse body: {"message":"Internal failure"}

```
This is on a "copy" transfer of a very large number of small files. That's not very surprising, but maybe there's a way to scale back or limit rclone's request rate when these errors come back from amazon to proactively avoid them?

Hit the same error with --transfers=20 as well as on =50

**Comment by ncw** [comment]
Rclone backs off in the Amazon approved way on 429 errors then retries the file. 

500 errors are a bit more unusual - perhaps a problem at Amazon? 

It is quite normal to see errors transferring files. 

You should find the low level retries or the full retries clears them up though. Check the number of errors that rclone outputs in  it's final message.

**Comment by DairyDTP** [comment]
Looks like they mostly appear together, one 500, a bunch of 429, every now and then also:

` Received error: HTTP code 504: "504 GATEWAY_TIMEOUT", no response body
`

I'll let the copy finish, but I think the retries are working. Thanks!
