### ISSUE TITLE
ACD destination checks do not seem to be working for existing files

### ISSUE THREAD

**Issue by a5m0** [ncw/rclone#483]
I ran this command:

`rclone --min-age 30d --checksum --bwlimit 4M --exclude excludefolder/** move /home/user/localfiles/ remoteacd:backup/folder`

I then interrupted it to give another process more bandwidth, but when I go back to run it again I am getting constant:

` Failed to copy: HTTP code 409: "409 Conflict", reponse body: {"logref":"fxxxxx","message":"Node with the name xxx already exists under parentId xxxx conflicting NodeId: xxxx","code":"NAME_ALREADY_EX
ISTS","info":{"nodeId":"xxxx"}}`

I have checked and these files were successfully uploaded (checked md5sum locally and then did an acd_cli find-md5 and verified the file existed where it should).

Shouldn't the --checksum verify these files were already moved and delete the local copy? Trying a copy gave the same results with just errors instead of checks...

**Comment by ncw** [comment]
`rclone move` should work exactly like `rclone copy src dst` followed by `rclone purge src`, and yes `--checksum` should verify the checksums.

Note that you can verify all the checksums with `rclone check src dst`.

The "409 conflict" errors probably indicate that the directory listing went wrong.  Can you check the logs for errors there and paste them here please? This might be related to #475 also.

I'm currently working on the whole directory listing thing - at the moment it doesn't pass errors back properly.

Can you also tell me which platform you are on so I can send you a beta to try?

**Comment by ncw** [comment]
Just looking at your other issue makes me realise the reason the files didn't get deleted is that there were IO errors in the copy phase.  You should see `Not deleting files as there were IO errors` in the log.

**Comment by a5m0** [comment]
I am on rclone 1.29 on ubuntu x64. I looked in the logs (ran with -v) and I don't see any errors during the directory read, just lots of Reading/Finished Reading then lots of  Failed to copy: HTTP code 409: "409 Conflict" then Not deleting files as there were IO errors.

**Comment by a5m0** [comment]
These files are already transferred because I ctrl-c'd an earlier move, but they should be checksum checked and the rest of the transfer resumed...

**Comment by ncw** [comment]
Are the troublesome files in a directory with 100s or 1000s of other files? If so this is very likely #475

**Comment by a5m0** [comment]
The individual sub-directory that it's having trouble moving stuff into isn't that big (80 directories, 700 files), but the top level ACD directory has 2000 directories, containing 15,000 files.

**Comment by ncw** [comment]
I'm pretty sure that the fix for #475 will fix this.  I'll post a more tested beta for you to try over the weekend most likely.

**Comment by a5m0** [comment]
Sounds good, thank you for all the effort!

**Comment by ncw** [comment]
Here is a beta for you to try which has the fix in: http://pub.rclone.org/v1.29-28-g36700d3%CE%B2/

**Comment by a5m0** [comment]
Running it, looks better (marking errors as transferred), but can't tell that it's doing checks, and I ran it with --checksum

Errors:                 6
Checks:                 0
Transferred:            6

**Comment by ncw** [comment]
Any chance you could send me a log with -v of this?

**Comment by a5m0** [comment]
Sure thing, sent you an email.

**Comment by left1000** [comment]
btw isn't this issue and issue #475  and issue #263  all the same issue?

amazon fails to properly report ls for massive numbers of files. they always have. that said rclone 1.29 works 1000% better at processing these errors than rclone 1.26 did.

I just figured I'd mention my issue in this comment just in case the older comments were at all helpful.

**Comment by a5m0** [comment]
Would it be possible if a conflict is reported to have rclone actually do a check so it doesn't error and not finish the move/delete operation?

**Comment by a5m0** [comment]
any updates or new findings that would fix this?

**Comment by ncw** [comment]
Sorry your log got lost in my INBOX!

This is puzzling about your log

First we get this

```
2016/05/16 22:59:35 GLkzH8Vi1v4CyzjUqcwXYYMB/23pSIXvypFQ6TyR2VawjeoWy/jO1nG9PfZwFosS1nbLysIeuv/DZ19IzpLWNFNlTJaXJEWE856O3uDa0SEtgKXSENGGnpQZnH,xgsVqymHAY,XEXY1qAIwbFA7qWRUInP-KOCusk5q: Excluded from sync (and deletion)
```

And then this

```
2016/05/16 23:00:56 GLkzH8Vi1v4CyzjUqcwXYYMB/23pSIXvypFQ6TyR2VawjeoWy/jO1nG9PfZwFosS1nbLysIeuv/DZ19IzpLWNFNlTJaXJEWE856O3uDa0SEtgKXSENGGnpQZnH,xgsVqymHAY,XEXY1qAIwbFA7qWRUInP-KOCusk5q: Failed to copy: HTTP code 409: "409 Conflict", reponse body: {"logref":"0c109899-1bba-11e6-ac16-03d37e08e7dc","message":"Node with the name dz19izplwnfnltjaxjewe856o3uda0setgkxsenggnpqznh,xgsvqymhay,xexy1qaiwbfa7qwruinp-kocusk5q already exists under parentId jpbRd_tKTs64C_QJJVBG_w conflicting NodeId: uLHNHnvOStSWKmtKvqaZZQ","code":"NAME_ALREADY_EXISTS","info":{"nodeId":"uLHNHnvOStSWKmtKvqaZZQ"}}
```

So what that seems to me is that your exclude rule matched for ACD, but somehow didn't match for the local file system.

So when rclone came to copy the local file it didn't know it was supposed to be over-writing an existing file and hence created a duplicate.

This explains the consistent 409 errors perfectly.

But why is that happening?

Is it possible that your excludefolder doesn't have the same case as the actual folder in your local fs?

Hmm, or I wonder if it is the `--min-age 30d` that is the problem.  ACD doesn't support date based syncing but it will still be applying `--min-age 30d` to the folder which it shouldn't be. So if your file on ACD is > 30d old, but the file on the local file system is < 30d old then this would explain the problem perfectly.  The dates on ACD are the time the file was uploaded.

Does that make sense to you?

Can you verify this please?  If you send me the results of these two commands I can check the dates and make sure that makes sense (or you can if you prefer - just find a file whch had a 409 conflict and compare the dates for it).

    rclone lsl /home/user/localfiles/
    rclone lsl remoteacd:backup/folder

So assuming this is the problem, then I need to make the destination fs filtering ignore times and sizes (basically anything which could be changed by a new upload).

I'm going to consider the whole copy logic too as the equivalent problem with google drive is a duplicated file.  Getting the Upload method to check for an existing file first would slow things down though.

**Comment by ncw** [comment]
I realised the above approach won't work so here is a different tack - check in acd and drive to see if the file exists before uploading.  This will prevent 409 errors (and duplicate files in drive's case) but slow the upload down slightly.

Can you give this beta a test a go and see what happens?

http://pub.rclone.org/v1.29-1-gbb75d80-56-g9579d50%CE%B2/

Thanks

Nick

**Comment by ncw** [comment]
I've committed this to master now - if it doesn't fix the issue - please re-open it!

Thanks

Nick

**Comment by a5m0** [comment]
Not getting all the 409 errors now, but it doesn't look like it's respecting my --checksum flag because the checks are listed as 0, so I'm not sure it's deleting source files that were already transferred either, but a step in the right direction thanks!

Transferred:            0Bytes (0Byte/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:     1m30.7s
2016/06/14 04:06:05 Go routines at exit 6
