### ISSUE TITLE
Starting bandwidth limiter at xxBytes/s prints to stdout regardless of --log-file switch

### ISSUE THREAD

**Issue by KarmaPoliceT2** [ncw/rclone#486]
Version: rclone v1.29
OS: ubuntu 16.04
Cloud Storage: ACD
Command: rclone --log-file tmp.txt move src dst (same behavior with copy)

When using the --log-file switch just about everything goes to the log file except the "Starting bandwidth limiter at xxBytes/s"  which goes to stdout regardless of the switch

Should be a pretty easy fix to just switch that message output to log.printf from the current Log implementation in fs/accounting.go

**Comment by ncw** [comment]
Well spotted!  Fancy doing me a Pull request?

**Comment by ncw** [comment]
This will be in the v1.30 release
