### ISSUE TITLE
Format for filters?

### ISSUE THREAD

**Issue by hjmangalam** [ncw/rclone#489]
rclone version  **1.29** on **CentOS 6.6** referencing  **Google Drive**

This is trivial, but I can't get the rclone globbing to work and due to the dearth of explicit example on line, can't figure it out. I've read the /filtering page but it doesn't show any examples in context
 I have a Drive object set, with a number of dirs pushed into it with rclone.

the overall ls/lsl/lsd commands work fine:

```
$ rclone -v ls gdrv:boards/sayas
2016/05/17 12:50:55 gdrv: Saving new token in config file
2016/05/17 12:50:55 pacer: Rate limited, increasing sleep to 2s
2016/05/17 12:50:55 pacer: low level retry 1/10
2016/05/17 12:50:55 pacer: low level retry 2/10
2016/05/17 12:50:57 pacer: Reducing sleep to 10ms
2016/05/17 12:50:59 Google drive root 'boards/sayas': Modify window is 1ms
  3428416 IMG_3263.JPG
  4008368 IMG_3264.JPG
...
  1531444 IMAG0956.jpg
  3496035 IMG_3269.JPG

```
and specific file references work fine:

```
$ rclone -v ls gdrv:boards/sayas/IMAG0944.jpg
2016/05/17 12:52:58 Google drive root 'boards/sayas' limited to 1 objects: Modify window is 1ms
  2088686 IMAG0944.jpg

```
But trying to use the filtering does not:

```
$ rclone -v ls gdrv:boards/sayas/\*.jpg
2016/05/17 12:53:36 pacer: Rate limited, increasing sleep to 2s
2016/05/17 12:53:36 pacer: low level retry 1/10
2016/05/17 12:53:36 pacer: low level retry 2/10
2016/05/17 12:53:38 pacer: Reducing sleep to 10ms
2016/05/17 12:53:41 *.jpg: Couldn't find object
2016/05/17 12:53:41 Google drive root 'boards/sayas/*.jpg': Modify window is 1ms
2016/05/17 12:53:41 Google drive root 'boards/sayas/*.jpg': Couldn't find root: Couldn't find directory: "boards/sayas/*.jpg"

```
```
$ rclone -v ls gdrv:boards/sayas/IMG_\*
2016/05/17 12:54:32 IMG_*: Couldn't find object
2016/05/17 12:54:32 Google drive root 'boards/sayas/IMG_*': Modify window is 1ms
2016/05/17 12:54:32 Google drive root 'boards/sayas/IMG_*': Couldn't find root: Couldn't find directory: "boards/sayas/IMG_*"

```
Single or double quoting the target also fail in the identical way:
```
$ rclone -v ls 'gdrv:boards/sayas/IMG_\*'
2016/05/17 12:54:59 IMG_\*: Couldn't find object
2016/05/17 12:54:59 Google drive root 'boards/sayas/IMG_\*': Modify window is 1ms
2016/05/17 12:54:59 Google drive root 'boards/sayas/IMG_\*': Couldn't find root: Couldn't find directory: "boards/sayas/IMG_\\*"

```
 ```
$ rclone -v ls gdrv:'IMG_*'
2016/05/17 13:04:02 IMG_*: Couldn't find object
2016/05/17 13:04:02 Google drive root 'IMG_*': Modify window is 1ms
2016/05/17 13:04:02 Google drive root 'IMG_*': Couldn't find root: Couldn't find directory: "IMG_*"

```

I'm clearly missing something here...what is it?  Quoting, special escaping? The phrase "Couldn't find root:" is a hint, but google returns precious little in that regard.

**Comment by zeshanb** [comment]
Try placing a / in config for drive resource. boards/sayas/

**Comment by hjmangalam** [comment]
Thanks for replying so quickly, but I don't know what this means.  Is there a doc for how the config file is structured?  In my config file is:

```
[gdrivefs]
type = drive
client_id =
client_secret =
token = {"access_token":"..secret..","token_type":"

[google-dra]
type = google cloud storage
client_id =
client_secret =
project_number =
object_acl = private
bucket_acl = authenticatedRead
token = {"access_token":".secret..","token_type":"

[gdrv]
type = drive
client_id =
client_secret =
token = {"access_token":".secret..","token_type":"
```
There's no indication of how/what to place a '/' in the config file for any resource.

**Comment by zeshanb** [comment]
Login to console.developers.Google.com and follow these instructions in
YouTube video on how to generate a API key

https://youtu.be/KKyIVFzkR2A

**Comment by zeshanb** [comment]
Sorry, I misread. You are only having issues with filter options.

**Comment by ncw** [comment]
The filtering rules can only be used in one of the filter command line flags, so

    rclone -v ls gdrv:boards/sayas/\*.jpg

Won't do what you think unfortunately - it will be trying to list a directory called `boards/sayas/*.jpg`

What will work is something like this

    rclone -v --include "*.jpg" ls gdrv:boards/sayas/

Apologies for the confusion!

rclone could conceivably convert what you wrote into the equivalent with the `--include` flag.

**Comment by hjmangalam** [comment]
Hi Nick, Thanks for the clarification note and your work on rclone - truly a transformational way of working with the cloud.  Your modification did work as described. I may be glob-spoiled but the filters documentation seems to strongly imply that the filters worked as I initially thought.  Since my original approach is the more *nixy way of doing things, perhaps a few examples of the rclone methodology of filters would be worthwhile including in future edits to the filters page?
thanks again.

**Comment by ncw** [comment]
I've added this to the filtering docs - thanks for the suggestions

Note also that rclone filter globs can only be used in one of the
filter command line flags, not in the specification of the remote, so
`rclone copy "remote:dir*.jpg" /path/to/dir` won't work - what is
required is `rclone --include "*.jpg" copy remote:dir /path/to/dir`
