### ISSUE TITLE
Drive: Rclone doesn't sync Google Docs

### ISSUE THREAD

**Issue by philiprhoades** [ncw/rclone#49]
Attached is a screen capture of my G Drive showing all the folders and some of the files.

![screenshot-20150424-174336](https://cloud.githubusercontent.com/assets/1153703/7314813/56948522-eaab-11e4-9e8d-78fd41a42f65.png)

Below is what:

rclone lsd GD: | sort -k 5

shows:

          -1 2014-06-28 09:18:09        -1 CNASALERC
          -1 2013-04-28 17:12:33        -1 Drive Sync Images
          -1 2013-03-20 08:38:03        -1 HandWrittenNotes
          -1 2014-07-03 08:23:16        -1 Health
          -1 2015-04-09 14:01:41        -1 Kathalina
          -1 2015-03-03 00:35:17        -1 LESTp
          -1 2014-08-20 17:11:08        -1 LEV
          -1 2013-03-27 07:53:36        -1 My Tracks
          -1 2014-07-13 07:36:47        -1 PhD_UNSW
          -1 2015-02-21 02:00:25        -1 SMSs
          -1 2014-06-05 08:02:51        -1 Writing
          -1 2015-04-22 11:31:58        -1 video

ie ALL the folders.  Below is what:

rclone copy GD:/ ./

gives:

drwxrws---   3 phil phil      4096 Apr 24 14:05 Drive Sync Images
drwxrws---   2 phil phil      4096 Apr 24 14:10 HandWrittenNotes
drwxrws---   2 phil phil      4096 Apr 24 14:02 Kathalina
drwxrws---   2 phil phil      4096 Apr 24 14:05 LEV
drwxrws---   2 phil phil      4096 Apr 24 14:06 My Tracks
drwxrws---   2 phil phil      4096 Apr 24 14:05 PhD_UNSW
drwxrws---   2 phil phil      4096 Apr 24 14:05 SMSs
drwxrws---   6 phil phil      4096 Apr 24 14:06 Writing
-rw-rw-r--   1 phil phil    151613 Feb 15  2014 AguadoSec02No10_gnote2_3_24pt.pdf
-rw-rw-r--   1 phil phil     44509 Feb 15  2014 JulioSalvadorSagreras_1_p07.pdf
-rw-rw-r--   1 phil phil    123555 Feb 12  2014 Julio_Salvador_Sagreras_Las_Primeras_Lecciones_de_guitarra.xml
-rw-rw-r--   1 phil phil       139 Feb 13  2014 Julio_Salvador_Sagreras_Las_Primeras_Lecciones_de_guitarra_p10_w7.mid
-rw-rw-r--   1 phil phil       652 Feb 12  2014 Julio_Salvador_Sagreras_Las_Primeras_Lecciones_de_guitarra_p2.mid
-rw-rw-r--   1 phil phil   2319437 Feb 20  2012 Report20209_1.png
-rw-rw-r--   1 phil phil   1688514 Feb 20  2012 Report20209_2.png
-rw-rw-r--   1 phil phil       933 Mar  7 14:18 SajeCrt.txt
-rw-rw-r--   1 phil phil     36164 Apr 24 17:45 Screenshot-042415-17:43:36.png
-rw-rw-r--   1 phil phil       602 Feb 16  2014 ssh-dss.txt
-rw-rw-r--   1 phil phil       240 Feb  3 15:19 t.csv

ie missing folders and files.

So between the lsd and the copy commands, something goes wrong . . ideas?

Thanks,

Phil.

**Comment by ncw** [comment]
Did `rclone copy` produce any errors?  Drive is a little unreliable sometimes, so you might need to run the copy again.  rclone won't attempt to copy any files it has copied already, so this should be nice and quick.

rclone only copies files at the moment, it doesn't copy google documents as these aren't stored as files in drive (even though they look like they are) - that probably explains the missing things.  rclone won't create local directories it isn't creating any files, but they will show up on `rclone lsd`.

**Comment by philiprhoades** [comment]
No - no errors at all. In fact I renamed a Drive file and reran rclone and it only copied the renamed file but nothing else ie it continued to ignore the dirs and files it missed the first time.  I am wondering if this is related problem to a Drive issue that sometimes occurs on Chrome - which makes it look like dirs and files are missing on Drive but are clearly visible either from FireFox or G Drive for Android - but I don't think it is really . .

> rclone only copies files at the moment, it doesn't copy google documents as these aren't stored as files in drive (even though they look like they are) - that probably explains the missing things. rclone won't create local directories it isn't creating any files, but they will show up on rclone lsd.

Ah . . that is probably it . . I will check - that will be a problem though of course . . is there a way around that?

**Comment by ncw** [comment]
There are a couple of problems with rclone downloading google documents.  These are

  1. These files don't have md5sums so the integrity checking rclone does won't work
    * possibly could be worked around though by doing a HEAD request on the `exportLink`
  2. These files can be downloaded using the `exportLinks` which are exported in the [files resource](https://developers.google.com/drive/v2/reference/files), however they are exported in multiple formats
    * should rclone just pick a format to download?
      * if so how?  User preference?
    * The file name is missing its extension - should rclone add a file version with the extension?
    * Should rclone download all the formats?
    * A quick test indicates that for a document it offers `docx, odt, rtf, html, txt, pdf` formats for export

**Comment by philiprhoades** [comment]
> A quick test indicates that for a document it offers docx, odt, rtf, html, txt, pdf formats for export

If it was me, I would probably default it to ODT - but I guess it would be nice for it to be user configurable.

**Comment by philiprhoades** [comment]
That should be "OD?" I guess . .

**Comment by philiprhoades** [comment]
Another thought:

Downloading multiple files or directory(ies) via the Drive I/F automatically invokes zipping up the files / folders - could this be implemented as an interim measure for backing up via rclone? - ie it would be nice to have a scriptable backup procedure for Drive.

Thanks!

**Comment by mullenkamp** [comment]
Implementing the option to download converted google documents and have them recognized as such on a reverse sync would be a great option (especially for backing up google docs). 
Google already has an API for Drive that allows you to specify a file type to download the various google documents:
https://developers.google.com/drive/web/manage-downloads#downloading_google_documents

This has already been implemented in an open source google drive mounting program:
https://github.com/astrada/google-drive-ocamlfuse/wiki/Exportable-formats

I hope this helps...Thanks again for a nice copy program.

**Comment by ncw** [comment]
Server side copy / move needs to work with docs also

**Comment by kruglikov** [comment]
+1 vote for this enchanement
Since I'm just duplicationg data from my Google Drive to local folder, for me would be great at least to 
download google documents in any format.

**Comment by ttarakanoff** [comment]
+1 for this feature

**Comment by mikecentiq** [comment]
FWIW, I just spent about 20 minutes trying to figure out why rclone wasn't working for me. It "wasn't working for me" because all of the things that appear in Google Drive for me are actually from Google Docs. Perhaps this information should be added to the man page, and maybe in the "-v" output?

**Comment by ncw** [comment]
@mikecentiq both good ideas - I made a ticket about it #250. Sorry for the frustrating time! -- Nick

**Comment by michaelthwaite** [comment]
+1 for Google Docs copy down to txt/pdf/docx/odt, etc.

**Comment by TimJWatts** [comment]
Hiya - Tim Watts from Kings College (University of) London here.

Really really like rclone - it's a nice "unix way" implementation. Pity about the Google Docs lack of support. My opinion for what it's worth:

1) I suggest to pick an export format, any format and run with that as soon as possible. That should at least solve 90% of the use cases (I want to back up my Drive etc).

2) Perhaps adding a config option later to choose a preferred format would be very neat, but I suspect most people would be happy to have something by way of a backup. eg a manual Download bundles a zip with MS compatible files - this is sensible. LibreOffice would also be perfect sensible (as anyone can make use of those files if needs must).

I am not sure how to handle the sync-right followed by sync-left problem (converting file formats to and from a foreign format is bound to break any attempt to checksum) but having a good one way copy would be most awesome!

Bad form on Google IMHO - if they'd made their Drive interface orthogonal, then the action of getting a Google Doc would cause a transparent export to at least a default format and the action of putting it would do the same as "Upload" in the web interface (which is a preference to auto convert or not).

All the best and good luck :)

Tim

**Comment by ncw** [comment]
Thanks @TimJWatts for getting me out of analysis paralysis!  I have made an implementation which I'll put into the next release unless anyone finds any serious problems with it!

Here is a link to a beta to try

http://pub.rclone.org/v1.26-50-geb8c1b1%CE%B2/

Note that this doesn't address server side copy or move...

And here are the docs

#### --drive-formats ####

Google documents can only be exported from Google drive.  When rclone
downloads a Google doc it chooses a format to download depending upon
this setting.

By default the formats are `docx,xlsx,pptx,svg` which are a sensible
default for an editable document.

When choosing a format, rclone runs down the list provided in order
and chooses the first file format the doc can be exported as from the
list. If the file can't be exported to a format on the formats list,
then rclone will choose a format from the default list.

If you prefer an archive copy then you might use `--drive-formats
pdf`, or if you prefer openoffice/libreoffice formats you might use
`--drive-formats ods,odt`.

Note that rclone adds the extension to the google doc, so if it is
calles `My Spreadsheet` on google docs, it will be exported as `My
Spreadsheet.xlsx` or `My Spreadsheet.pdf` etc.

Here are the possible extensions with their corresponding mime types.

| Extension | Mime Type | Description |
| --------- |-----------| ------------|
| csv  | text/csv | Standard CSV format for Spreadsheets |
| doc  | application/msword | Micosoft Office Document |
| docx | application/vnd.openxmlformats-officedocument.wordprocessingml.document | Microsoft Office Document |
| html | text/html | An HTML Document |
| jpg  | image/jpeg | A JPEG Image File |
| ods  | application/vnd.oasis.opendocument.spreadsheet | Openoffice Spreadsheet |
| ods  | application/x-vnd.oasis.opendocument.spreadsheet | Openoffice Spreadsheet |
| odt  | application/vnd.oasis.opendocument.text | Openoffice Document |
| pdf  | application/pdf | Adobe PDF Format |
| png  | image/png | PNG Image Format|
| pptx | application/vnd.openxmlformats-officedocument.presentationml.presentation | Microsoft Office Powerpoint |
| rtf  | application/rtf | Rich Text Format |
| svg  | image/svg+xml | Scalable Vector Graphics Format |
| txt  | text/plain | Plain Text |
| xls  | application/vnd.ms-excel | Microsoft Office Spreadsheet |
| xlsx | application/vnd.openxmlformats-officedocument.spreadsheetml.sheet | Microsoft Office Spreadsheet |
| zip  | application/zip | A ZIP file of HTML, Images CSS |

**Comment by dolabriform** [comment]
Hi Nick

I've just got around to trying the beta today, and it's not transferring
the google docs.

Maybe I'm doing something wrong... I've tried with and without specifying
drive-formats:

rclone -v  sync drive: S3:bucket --drive-formats pdf

rclone -v  sync drive: S3:bucket

Both commands do not export drive docs.

Regards

David

On 31 January 2016 at 18:10, Nick Craig-Wood <notifications@github.com>
wrote:

> Closed #49 <https://github.com/ncw/rclone/issues/49> via 558bc2e
> <https://github.com/ncw/rclone/commit/558bc2e132688f21f7142be3c42ed697c5cc136f>
> .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ncw/rclone/issues/49#event-533228583>.
>



-- 
--------------------
David White
07525 807295

**Comment by michaelthwaite** [comment]
I’m experiencing the same with 1.27 - I’ve had it work but now it seems to skip over Google Docs.

MPT

**Comment by ncw** [comment]
@dolabriform @michaelthwaite Curious - it works for me.

![gdocs](https://cloud.githubusercontent.com/assets/536803/12751690/8ba730c6-c9b6-11e5-9bd0-463fd3e5068f.png)

```
$ rclone ls drive:GDocs
     5570 Drawings.svg
     4297 Docs.docx
     3516 Sheets.xlsx
    27579 Slides.pptx

$ rclone copy drive:GDocs /tmp/adfsf
2016/02/02 14:06:16 Local file system at /tmp/adfsf: Building file list
2016/02/02 14:06:17 Local file system at /tmp/adfsf: Waiting for checks to finish
2016/02/02 14:06:17 Local file system at /tmp/adfsf: Waiting for transfers to finish

Transferred:        40962 Bytes (  14.49 kByte/s)
Errors:                 0
Checks:                 0
Transferred:            4
Elapsed time:        2.7s

$ ls /tmp/adfsf/
Docs.docx  Drawings.svg  Sheets.xlsx  Slides.pptx

$ rclone copy drive:GDocs /tmp/adfsf
2016/02/02 14:06:33 Local file system at /tmp/adfsf: Building file list
2016/02/02 14:06:35 Local file system at /tmp/adfsf: Waiting for checks to finish
2016/02/02 14:06:35 Local file system at /tmp/adfsf: Waiting for transfers to finish

Transferred:            0 Bytes (   0.00 kByte/s)
Errors:                 0
Checks:                 4
Transferred:            0
Elapsed time:          2s
```

Can you post a log with `rclone -v` of what happens?

**Comment by dolabriform** [comment]
Hi Nick

I think I've worked out the problem....

If I do an ls from the root of drive, ie:

rclone ls drive:

It doesn't show any google docs but it does show all other file types in
the root and all sub folders

However if I do an ls with a folder name, ie

rclone -v ls drive2:test

It lists all the google docs files!

rclone -v ls drive2:test

2016/02/02 14:48:40 Google drive root 'test': Modify window is 1ms

2016/02/02 14:48:40 Google drive root 'test': Finished reading

     4306 test-doc.docx

     3589 test-sheet.xlsx

Transferred:            0 Bytes (   0.00 kByte/s)

Errors:                 0

Checks:                 0

Transferred:            0

Elapsed time:        1.2s

2016/02/02 14:48:41 Go routines at exit 15

I hope that helps

Regards

David


On 2 February 2016 at 14:17, Nick Craig-Wood <notifications@github.com>
wrote:

> @dolabriform <https://github.com/dolabriform> @michaelthwaite
> <https://github.com/michaelthwaite> Curious - it works for me.
>
> [image: gdocs]
> <https://cloud.githubusercontent.com/assets/536803/12751690/8ba730c6-c9b6-11e5-9bd0-463fd3e5068f.png>
>
> $ rclone ls drive:GDocs
>      5570 Drawings.svg
>      4297 Docs.docx
>      3516 Sheets.xlsx
>     27579 Slides.pptx
>
> $ rclone copy drive:GDocs /tmp/adfsf
> 2016/02/02 14:06:16 Local file system at /tmp/adfsf: Building file list
> 2016/02/02 14:06:17 Local file system at /tmp/adfsf: Waiting for checks to finish
> 2016/02/02 14:06:17 Local file system at /tmp/adfsf: Waiting for transfers to finish
>
> Transferred:        40962 Bytes (  14.49 kByte/s)
> Errors:                 0
> Checks:                 0
> Transferred:            4
> Elapsed time:        2.7s
>
> $ ls /tmp/adfsf/
> Docs.docx  Drawings.svg  Sheets.xlsx  Slides.pptx
>
> $ rclone copy drive:GDocs /tmp/adfsf
> 2016/02/02 14:06:33 Local file system at /tmp/adfsf: Building file list
> 2016/02/02 14:06:35 Local file system at /tmp/adfsf: Waiting for checks to finish
> 2016/02/02 14:06:35 Local file system at /tmp/adfsf: Waiting for transfers to finish
>
> Transferred:            0 Bytes (   0.00 kByte/s)
> Errors:                 0
> Checks:                 4
> Transferred:            0
> Elapsed time:          2s
>
> Can you post a log with rclone -v of what happens?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ncw/rclone/issues/49#issuecomment-178593725>.
>



-- 
--------------------
David White
07525 807295

**Comment by philiprhoades** [comment]
Nick,


On 2016-02-03 01:17, Nick Craig-Wood wrote:
> @dolabriform [1] @michaelthwaite [2] Curious - it works for me.
> 
>  [3]
> 
> $ rclone ls drive:GDocs
>      5570 Drawings.svg
>      4297 Docs.docx
>      3516 Sheets.xlsx
>     27579 Slides.pptx


None of those are native GDs are they? (GDs native files don't show 
extensions in the GDs environment).  I can only clone non-GD . .

P.


> $ rclone copy drive:GDocs /tmp/adfsf
> 2016/02/02 14:06:16 Local file system at /tmp/adfsf: Building file
> list
> 2016/02/02 14:06:17 Local file system at /tmp/adfsf: Waiting for
> checks to finish
> 2016/02/02 14:06:17 Local file system at /tmp/adfsf: Waiting for
> transfers to finish
> 
> Transferred:        40962 Bytes (  14.49 kByte/s)
> Errors:                 0
> Checks:                 0
> Transferred:            4
> Elapsed time:        2.7s
> 
> $ ls /tmp/adfsf/
> Docs.docx  Drawings.svg  Sheets.xlsx  Slides.pptx
> 
> $ rclone copy drive:GDocs /tmp/adfsf
> 2016/02/02 14:06:33 Local file system at /tmp/adfsf: Building file
> list
> 2016/02/02 14:06:35 Local file system at /tmp/adfsf: Waiting for
> checks to finish
> 2016/02/02 14:06:35 Local file system at /tmp/adfsf: Waiting for
> transfers to finish
> 
> Transferred:            0 Bytes (   0.00 kByte/s)
> Errors:                 0
> Checks:                 4
> Transferred:            0
> Elapsed time:          2s
> 
> Can you post a log with rclone -v of what happens?
> 
> --
> Reply to this email directly or view it on GitHub [4].
> 
> 	*
> 
> Links:
> ------
> [1] https://github.com/dolabriform
> [2] https://github.com/michaelthwaite
> [3]
> https://cloud.githubusercontent.com/assets/536803/12751690/8ba730c6-c9b6-11e5-9bd0-463fd3e5068f.png
> [4] https://github.com/ncw/rclone/issues/49#issuecomment-178593725

-- 
Philip Rhoades

PO Box 896
Cowra  NSW  2794
Australia
E-mail:  phil@pricom.com.au

**Comment by philiprhoades** [comment]
dolabriform,


On 2016-02-03 01:49, dolabriform wrote:
> Hi Nick
> 
> I think I've worked out the problem....
> 
> If I do an ls from the root of drive, ie:
> 
> rclone ls drive:
> 
> It doesn't show any google docs but it does show all other file types
> in
> the root and all sub folders
> 
> However if I do an ls with a folder name, ie
> 
> rclone -v ls drive2:test
> 
> It lists all the google docs files!
> 
> rclone -v ls drive2:test


That does not fix the problem for me . .

P.


> 2016/02/02 14:48:40 Google drive root 'test': Modify window is 1ms
> 
> 2016/02/02 14:48:40 Google drive root 'test': Finished reading
> 
> 4306 test-doc.docx
> 
> 3589 test-sheet.xlsx
> 
> Transferred: 0 Bytes ( 0.00 kByte/s)
> 
> Errors: 0
> 
> Checks: 0
> 
> Transferred: 0
> 
> Elapsed time: 1.2s
> 
> 2016/02/02 14:48:41 Go routines at exit 15
> 
> I hope that helps
> 
> Regards
> 
> David
> 
> On 2 February 2016 at 14:17, Nick Craig-Wood
> <notifications@github.com>
> wrote:
> 
>> @dolabriform <https://github.com/dolabriform> @michaelthwaite
>> <https://github.com/michaelthwaite> Curious - it works for me.
>> 
>> [image: gdocs]
>> 
> <https://cloud.githubusercontent.com/assets/536803/12751690/8ba730c6-c9b6-11e5-9bd0-463fd3e5068f.png>
>> 
>> $ rclone ls drive:GDocs
>> 5570 Drawings.svg
>> 4297 Docs.docx
>> 3516 Sheets.xlsx
>> 27579 Slides.pptx
>> 
>> $ rclone copy drive:GDocs /tmp/adfsf
>> 2016/02/02 14:06:16 Local file system at /tmp/adfsf: Building file
> list
>> 2016/02/02 14:06:17 Local file system at /tmp/adfsf: Waiting for
> checks to finish
>> 2016/02/02 14:06:17 Local file system at /tmp/adfsf: Waiting for
> transfers to finish
>> 
>> Transferred: 40962 Bytes ( 14.49 kByte/s)
>> Errors: 0
>> Checks: 0
>> Transferred: 4
>> Elapsed time: 2.7s
>> 
>> $ ls /tmp/adfsf/
>> Docs.docx Drawings.svg Sheets.xlsx Slides.pptx
>> 
>> $ rclone copy drive:GDocs /tmp/adfsf
>> 2016/02/02 14:06:33 Local file system at /tmp/adfsf: Building file
> list
>> 2016/02/02 14:06:35 Local file system at /tmp/adfsf: Waiting for
> checks to finish
>> 2016/02/02 14:06:35 Local file system at /tmp/adfsf: Waiting for
> transfers to finish
>> 
>> Transferred: 0 Bytes ( 0.00 kByte/s)
>> Errors: 0
>> Checks: 4
>> Transferred: 0
>> Elapsed time: 2s
>> 
>> Can you post a log with rclone -v of what happens?
>> 
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/ncw/rclone/issues/49#issuecomment-178593725>.
>> 
> 
> --
> --------------------
> David White
> 07525 807295
> --
> Reply to this email directly or view it on GitHub [1].
> 
> 	*
> 
> Links:
> ------
> [1] https://github.com/ncw/rclone/issues/49#issuecomment-178610025

-- 
Philip Rhoades

PO Box 896
Cowra  NSW  2794
Australia
E-mail:  phil@pricom.com.au

**Comment by philiprhoades** [comment]
dolabriform,

GitHub is stuffing up the formatting of the previous note - trying 
again:


On 2016-02-03 01:49, dolabriform wrote:
> Hi Nick
> 
> I think I've worked out the problem....
> 
> If I do an ls from the root of drive, ie:
> 
> rclone ls drive:
> 
> It doesn't show any google docs but it does show all other file types
> in
> the root and all sub folders
> 
> However if I do an ls with a folder name, ie
> 
> rclone -v ls drive2:test
> 
> It lists all the google docs files!
> 
> rclone -v ls drive2:test


That does not fix the problem for me . .

P.

-- 
Philip Rhoades

PO Box 896
Cowra  NSW  2794
Australia
E-mail:  phil@pricom.com.au

**Comment by ncw** [comment]
@dolabriform I can confirm that google docs aren't showing up properly when you list from the root.  I've made a ticket for it #336.  I suspect the fix for that will fix @philiprhoades problems too.

Any more comments about this to issue #336 please and I'll post a beta there when I've got to the bottom of it!

@philiprhoades wrote:
> >       5570 Drawings.svg
> >       4297 Docs.docx
> >       3516 Sheets.xlsx
> >      27579 Slides.pptx

> None of those are native GDs are they? (GDs native files don't show
> extensions in the GDs environment).  I can only clone non-GD..

They are exported versions of the native google docs - that is why
they have extensions.

**Comment by ncw** [comment]
I found a work-around `--drive-full-list=false` should fix it....

**Comment by dolabriform** [comment]
I can confirm that works :)

On 2 February 2016 at 17:05, Nick Craig-Wood <notifications@github.com>
wrote:

> I found a work-around --drive-full-list=false should fix it....
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ncw/rclone/issues/49#issuecomment-178690711>.
>



-- 
--------------------
David White
07525 807295

**Comment by philiprhoades** [comment]
People,


On 2016-02-03 04:23, dolabriform wrote:
> I can confirm that works :)


This works - correctly displaying a single PDF:

   rclone --drive-full-list=false ls gd:ABiC

None of these work to display two Writer files:

   rclone -v --drive-full-list=false ls gd:CNASALERC
   rclone --drive-full-list=false ls gd:CNASALERC
   rclone --drive-full-list=true ls gd:CNASALERC
   rclone --drive-full-list=false ls gd:CNASALERC/

P.


> On 2 February 2016 at 17:05, Nick Craig-Wood
> <notifications@github.com>
> wrote:
> 
>> I found a work-around --drive-full-list=false should fix it....
>> 
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/ncw/rclone/issues/49#issuecomment-178690711>.
>> 
> 
> --
> --------------------
> David White
> 07525 807295
> --
> Reply to this email directly or view it on GitHub [1].
> 
> 	*
> 
> Links:
> ------
> [1] https://github.com/ncw/rclone/issues/49#issuecomment-178699311

-- 
Philip Rhoades

PO Box 896
Cowra  NSW  2794
Australia
E-mail:  phil@pricom.com.au

**Comment by ncw** [comment]
@philiprhoades wrote
> None of these work to display two Writer files:
>  rclone -v --drive-full-list=false ls gd:CNASALERC    

Can you make sure you have permission to export these files? Right click on them in the drive web interface and select download and see if that works.

Also you say "Writer file" are these "Google Docs" files or something different?

If you can tell me how to reproduce the problem that would be really helpful!

Thanks

Nick

**Comment by philiprhoades** [comment]
Nick,


On 2016-02-04 00:55, Nick Craig-Wood wrote:
> @philiprhoades [1] wrote
> 
>> None of these work to display two Writer files:
>> rclone -v --drive-full-list=false ls gd:CNASALERC
> 
> Can you make sure you have permission to export these files? Right
> click on them in the drive web interface and select download and see
> if that works.


Yes, they are all my files and I can download all of them.


> Also you say "Writer file" are these "Google Docs" files or something
> different?


Native Google Writer files - I just used the word "Writer" to 
differentiate them from Calc files etc.


> If you can tell me how to reproduce the problem that would be really
> helpful!


Sorry, my fault - I was using 1.26 from another bin - updated and now I 
correctly get this:


rclone --drive-full-list=true ls gd:CNASALERC
      4523 0_ChromeForceReDisplay.docx
      9202 PotentialForCollaboration_PHR_SSA.docx

Transferred:            0 Bytes (   0.00 kByte/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:        2.8s


If I download - can I specify converting to ODT instead of DOCX?

Thanks!

Phil.
-- 
Philip Rhoades

PO Box 896
Cowra  NSW  2794
Australia
E-mail:  phil@pricom.com.au

**Comment by michaelthwaite** [comment]
All syncing correctly now with --drive-full-list=false 

MPT

**Comment by ncw** [comment]
Here is a beta which should work without the `--drive-full-list=true` work-around: http://pub.rclone.org/v1.27-1-g5dd387f%CE%B2/

**Comment by philiprhoades** [comment]
Nick,

Looks good!

Thanks!

Phil.


On 2016-02-07 03:44, Nick Craig-Wood wrote:
> Here is a beta which should work without the --drive-full-list=true
> work-around: http://pub.rclone.org/v1.27-1-g5dd387f%CE%B2/
> 
> --
> Reply to this email directly or view it on GitHub [1].
> 
> 	*
> 
> Links:
> ------
> [1] https://github.com/ncw/rclone/issues/49#issuecomment-180808036

-- 
Philip Rhoades

PO Box 896
Cowra  NSW  2794
Australia
E-mail:  phil@pricom.com.au

**Comment by robchallen** [comment]
Nick

I'm finding RClone very useful. Many thanks for your work on it. I'm using v1.27 release binaries on ubuntu trusty. Im posting this here because it seems connected to this issue but maybe is a new thing.

There seem to be some inconsistencies on the --drive-formats selection of export format for google docs IF the sync is started at root - as the following set of dry runs hope to illustrate. The "How we can help" Drive file is variously exported as odt or docx, seemingly ignoring the --drive-formats option if the sync is started from root (the behaviour differs between syncs, possibly at random) but seems to always be exported as requested as odt if the sync is started in a lower level directory.

Hope this helps
Rob

```
terminological@yoda:~$ rclone -n --drive-full-list=false --drive-formats "ods,odt" sync drive: ./GDrive/
2016/02/12 10:43:20 Local file system at /home/terminological/GDrive: Building file list
2016/02/12 10:43:28 Local file system at /home/terminological/GDrive: Waiting for checks to finish
2016/02/12 10:43:28 Waiting for deletions to finish
<snip>
2016/02/12 10:43:28 company/marketing/How we can help.docx: Not copying as --dry-run
2016/02/12 10:43:28 Local file system at /home/terminological/GDrive: Waiting for transfers to finish
2016/02/12 10:43:28 Local file system at /home/terminological/GDrive: Waiting for deletes to finish (during+after)

Transferred:            0 Bytes (   0.00 kByte/s)
Errors:                 0
Checks:                38
Transferred:            9
Elapsed time:        8.3s

terminological@yoda:~$ rclone -n --drive-full-list=false --drive-formats "odt,ods" sync drive: ./GDrive/
2016/02/12 10:44:49 Local file system at /home/terminological/GDrive: Building file list
2016/02/12 10:44:55 Local file system at /home/terminological/GDrive: Waiting for checks to finish
2016/02/12 10:44:55 Waiting for deletions to finish
<snip>
2016/02/12 10:44:55 company/marketing/How we can help.odt: Not copying as --dry-run
<snip>
2016/02/12 10:44:55 Local file system at /home/terminological/GDrive: Waiting for transfers to finish
2016/02/12 10:44:55 Local file system at /home/terminological/GDrive: Waiting for deletes to finish (during+after)

Transferred:            0 Bytes (   0.00 kByte/s)
Errors:                 0
Checks:                38
Transferred:            9
Elapsed time:        6.6s

terminological@yoda:~$ rclone -n --drive-full-list=false --drive-formats "odt,ods" sync drive: ./GDrive/ | grep company
2016/02/12 10:45:52 Local file system at /home/terminological/GDrive: Building file list
2016/02/12 10:45:57 Local file system at /home/terminological/GDrive: Waiting for checks to finish
2016/02/12 10:45:57 Waiting for deletions to finish
<snip>
2016/02/12 10:45:57 company/marketing/How we can help.docx: Not copying as --dry-run
<snip>
2016/02/12 10:45:57 Local file system at /home/terminological/GDrive: Waiting for transfers to finish
2016/02/12 10:45:57 Local file system at /home/terminological/GDrive: Waiting for deletes to finish (during+after)

Transferred:            0 Bytes (   0.00 kByte/s)
Errors:                 0
Checks:                38
Transferred:            9
Elapsed time:        6.3s

terminological@yoda:~$ rclone -n --drive-full-list=false --drive-formats "ods,odt" sync drive:/company/marketing ./GDrive/company/marketing
2016/02/12 10:46:52 Local file system at /home/terminological/GDrive/company/marketing: Building file list
2016/02/12 10:46:53 Local file system at /home/terminological/GDrive/company/marketing: Waiting for checks to finish
2016/02/12 10:46:53 Waiting for deletions to finish
2016/02/12 10:46:53 How we can help.odt: Not copying as --dry-run
2016/02/12 10:46:53 Local file system at /home/terminological/GDrive/company/marketing: Waiting for transfers to finish
2016/02/12 10:46:53 Local file system at /home/terminological/GDrive/company/marketing: Waiting for deletes to finish (during+after)

Transferred:            0 Bytes (   0.00 kByte/s)
Errors:                 0
Checks:                 8
Transferred:            1
Elapsed time:        1.7s

terminological@yoda:~$ rclone -n --drive-full-list=false --drive-formats "odt,ods" sync drive:/company/marketing ./GDrive/company/marketing
2016/02/12 10:47:04 Local file system at /home/terminological/GDrive/company/marketing: Building file list
2016/02/12 10:47:05 Local file system at /home/terminological/GDrive/company/marketing: Waiting for checks to finish
2016/02/12 10:47:05 Waiting for deletions to finish
2016/02/12 10:47:05 How we can help.odt: Not copying as --dry-run
2016/02/12 10:47:05 Local file system at /home/terminological/GDrive/company/marketing: Waiting for transfers to finish
2016/02/12 10:47:05 Local file system at /home/terminological/GDrive/company/marketing: Waiting for deletes to finish (during+after)

Transferred:            0 Bytes (   0.00 kByte/s)
Errors:                 0
Checks:                 8
Transferred:            1
Elapsed time:        1.7s

terminological@yoda:~$ 

```

**Comment by dolabriform** [comment]
I've tested the beta without the work around and it's working for me.

Thanks for all your hard work on this Nick!

On 6 February 2016 at 16:44, Nick Craig-Wood <notifications@github.com>
wrote:

> Here is a beta which should work without the --drive-full-list=true
> work-around: http://pub.rclone.org/v1.27-1-g5dd387f%CE%B2/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ncw/rclone/issues/49#issuecomment-180808036>.
>



-- 
--------------------
David White
07525 807295

**Comment by ncw** [comment]
@robchallen wrote
> There seem to be some inconsistencies on the --drive-formats selection of export format for google docs

I've fixed this in #336 - there is a beta on that ticket for you to try - comments there please :-)

**Comment by philiprhoades** [comment]
Nick,


On 2016-02-13 00:59, Nick Craig-Wood wrote:
> @robchallen [1] wrote
> 
>> There seem to be some inconsistencies on the --drive-formats
>> selection of export format for google docs
> 
> I've fixed this in #336 [2] - there is a beta on that ticket for you
> to try - comments there please :-)


Using rclone-v1.27-linux-amd64.zip from the web site (I presume this is 
the correct one? - on a previous download unzipping gave a dir: 
rclone-v1.27-1-g5dd387f#U03b2-linux-amd64 - so at least I could tell 
there was a difference), with this command:

   rclone -v sync --drive-full-list=false --drive-formats "ods,odt" gd: .

mostly it worked with od[st] files produced but I still got a few .docx 
and .xlsx files - not sure why, they seem to be a roughly even spread of 
date age stamps . .

Thanks,

Phil.
-- 
Philip Rhoades

PO Box 896
Cowra  NSW  2794
Australia
E-mail:  phil@pricom.com.au

**Comment by ncw** [comment]
@philiprhoades Try the binary from here: http://pub.rclone.org/v1.27-1-g5dd387f%CE%B2/ - that should be the right one. - Can you put coments #336 about that please? Thanks Nick

**Comment by philiprhoades** [comment]
Nick,


On 2016-02-15 04:02, Nick Craig-Wood wrote:
> @philiprhoades [1] Try the binary from here:
> http://pub.rclone.org/v1.27-1-g5dd387f%CE%B2/ - that should be the
> right one.


I'm confused - that has an old date on it "2016-02-06 16:41:35" - I 
thought there had been another change since then?

Also, clicking on that file to save it gives a file name "download" 
instead of the file name.


> - Can you put coments #336 [2] about that please? Thanks


Will do.

P.
-- 
Philip Rhoades

PO Box 896
Cowra  NSW  2794
Australia
E-mail:  phil@pricom.com.au

**Comment by ncw** [comment]
@philiprhoades sorry for the confusion.  That link should link to the right code to try.

A beta's link on the website is a good idea - I'd need to make the beta's a bit differently though as at the moment I make them with individual branches of code I want people to check.

> and then compared the .odt and .ods files that DID work with the previous version and although they both open OK, the files have different cksums - not sure why they converted differently but still open OK . 

Google seems to convert the files on the fly each time, and they are sometimes different - I don't know why!  Maybe they have a timestamp in or something like that.

**Comment by TimJWatts** [comment]
I just wanted to say: thanks @ncw for a very elegant implementation. This might just cost one of the online "we backup Google" services a sale! (We only really use GDocs so that's what we care most about).

**Comment by dolabriform** [comment]
I'd like to second that!

On Monday, 15 February 2016, Tim Watts <notifications@github.com> wrote:

> I just wanted to say: thanks @ncw <https://github.com/ncw> for a very
> elegant implementation. This might just cost one of the online "we backup
> Google" services a sale! (We only really use GDocs so that's what we care
> most about).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ncw/rclone/issues/49#issuecomment-184349552>.
>


-- 
--------------------
David White
07525 807295
