### ISSUE TITLE
S3 server-side encryption

### ISSUE THREAD

**Issue by geoffraeder** [ncw/rclone#491]
Is there a way to specify server-side encryption when rclone uploads an object to S3?  I did notice this open ticket for the ability to set addition headers https://github.com/ncw/rclone/issues/59, which would likely do the trick.  Is there any other way that I might be missing?

Thanks in advance.

**Comment by ncw** [comment]
Not at the moment, sorry.

I'm not really familiar with how server side encryption works with S3 - would #59 solve the problem for you?

I'm planning on implementing client side encryption soon in #219 which might also be of interest.

**Comment by geoffraeder** [comment]
I believe #59 would solve the problem as you can specify the x-amz-server-side-encryption header in the request.  Also, looking at the source code, from what I can tell, it looks possible to specify ServerSideEncryption in the s3manager.UploadInput struct.  Looks like this is configured on line 778 in s3.go.  Wondering of that would work.

**Comment by geoffraeder** [comment]
BTW, rclone has been working great for us, so thanks.  We were able to successfully migrate from Rackspace to AWS.

**Comment by ncw** [comment]
Server side encryption for S3 will be in the 1.30 release which is imminent
