### ISSUE TITLE
Linux FUSE support

### ISSUE THREAD

**Issue by fantom-x** [ncw/rclone#494]
Are there plans to implement FUSE support so that it is possible to mount a cloud drive as a local filesystem?

**Comment by garypaduana** [comment]
check out acd_cli if you haven't yet.  it may offer exactly what you're looking for.

**Comment by ncw** [comment]
No rclone doesn't have a FUSE interface sorry!  I did consider writing one - it would be a nice project for someone to use the rclone internals to implement it.

**Comment by fantom-x** [comment]
That is the idea; just wanted to make sure that there is currently no active development going on.

**Comment by zjpleau** [comment]
acd_cli has been having major problems with the token staying authenticated for the past several days. Checking to see if rclone would be a good replacement but doesn't look like it since you can't mount it as a directory.

**Comment by garypaduana** [comment]
@zjpleau rclone is having the same authentication issues unfortunately

**Comment by ncw** [comment]
I'm going to include this as an experimental feature in the next release.  It seems to work reasonably well...  I'll post a beta here for people to test before then.

**Comment by isaiah36** [comment]
So, one can copy and paste to the cloud from the file manager, is that the idea?  No more terminal command line required?

**Comment by ncw** [comment]
@isaiah36 file systems expect things to be 100% reliable, whereas cloud storage systems are a long way from 100% reliable.  The rclone command copes with this with lots of retries - we won't be able to use those in the fuse mount without taking local copies of all the uploads.  I might do that in the future, but for the moment `rclone mount` won't do that, so will be less reliable than the rclone command. It remains to be seen exactly how useful it is!

So to answer your question, yes you'll be able to view your cloud system in the file manager, but it won't be as reliable as using the rclone command.

**Comment by isaiah36** [comment]
Got it. Thanks.

**Comment by ncw** [comment]
I have merged this to master. It needs lots of testing - I haven't tried it on OS X (and I don't know how to set up FUSE on OSX) - so I could do with some help with testing and docs for OS X.

Here is the the beta.  Note I've marked this as experimental.

http://pub.rclone.org/v1.32-25-gf22029b%CE%B2/

Do `rclone help mount` to see the docs.

**Comment by Trentflix** [comment]
I just tried the beta you linked to. Does the Windows version have mount support? I just tried `rclone help mount` and `rclone mount [remote]` and received 'unknown command' errors.

**Comment by ncw** [comment]
@Trentflix no the windows version doesn't support mount alas.  AFAIK windows doesn't have FUSE support.  It is only for Linux, FreeBSD and OS X at the moment.

**Comment by Trentflix** [comment]
Makes sense, maybe something like [the Dokan Windows FUSE module](https://github.com/dokan-dev/dokany/wiki/FUSE) could be implemented in the future. This is what [ACDDokanNet](https://github.com/Rambalac/ACDDokanNet) uses. This and encryption are a very exciting step forward. Thank you for all of your work!

**Comment by ncw** [comment]
This is merged now and will be part of the v1.33 release.

Here is a beta: http://pub.rclone.org/v1.32-34-g037a000%CE%B2/

If you find any problems please open a new issue.

Thanks

Nick
