### ISSUE TITLE
Disk full - where are temp files stored?

### ISSUE THREAD

**Issue by wtluke** [ncw/rclone#495]
Hi,

Just noticed my local disk is full. Unfortunately, I didn't specify a log file for -v so I don't know where the temp files created were stored. Two commands run:

`/usr/sbin/rclone --checksum -v sync local:/home/pi drop:/pi/backups --exclude-from /home/pi/rcloneexclude.txt`

`/usr/sbin/rclone --checksum -v sync drop:/pi/backups google:/pi/backups`

I saw that there was a bug a few months ago about Google Drive creating local/temp copies of files before uploading, so I presume that's what has happened, but I can't find the directory where these may have been stored (and the full disk is preventing me doing much). Could anyone help point me in the right direction?

I thought it was all going too well!

Thanks

Will

**Comment by klauspost** [comment]
What is the destination filesystem? Google drive? What OS are you running on? Linux? Which rclone version? 

If it stores anything it will be in `/tmp`, but IIRC we no longer create temporary files when uploading from local filesystem.

**Comment by ncw** [comment]
rclone almost never needs a temporary file copy (only when copying from a remote which doesn't support SHA1 to blackblaze b2), and never when the local disk is one of the remotes.  

Temp files are stored in /tmp or TMPDIR.

On linux, `ncdu` is a great tool for finding out where all your disk space went.

**Comment by wtluke** [comment]
I'm a complete idiot. Sorry to waste everyone's time. A rogue script had filled it up and I naively assumed it was rclone - which, can I say, is utterly awesome.

Back in my box

W.

**Comment by ncw** [comment]
@wtluke no worries - we've all been there :-)

**Comment by seonghobae** [comment]
How about OneDrive? I'm experiencing disk full when try to sync OneDrive to Google cloud storage with gcsfuse.

**Comment by ncw** [comment]
@seonghobae if you use rclone to sync directly from OneDrive to Google cloud storage then you shouldn't get disk full errors.
