### ISSUE TITLE
Why copy to Google Drive will recursively list all files in target directory?

### ISSUE THREAD

**Issue by mayli** [ncw/rclone#500]
I am testing rclone copy with `rclone -v copy ./test drive:/test/`. The local test folder contains only a single file "a", the remove test folder has a sub dir contains tons of files. My question is why rclone will list the the src folder(and other sub dirs) recursively when there only a single file to copy?

When filing an issue, please include the following information if
possible as well as a description of the problem.

> What is your rclone version (eg output from `rclone -V`)
rclone v1.29
> Which OS you are using and how many bits (eg Windows 7, 64 bit)
linux 64bit
> Which cloud storage system are you using? (eg Google Drive)
google drive
> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone -v copy ./test drive:/test/
> A log from the command with the `-v` flag (eg output from `rclone -v copy /tmp remote:tmp`)

```
.......
2016/05/25 22:40:07 Google drive root 'test': Finished reading src/code.google.com/p/google-api-go-client/.hg/store/data/googleapi/internal/
2016/05/25 22:40:07 Google drive root 'test': Finished reading src/code.google.com/p/google-api-go-client/.hg/store/data/googleapi/
2016/05/25 22:40:07 Google drive root 'test': Finished reading src/code.google.com/p/google-api-go-client/.hg/store/data/
2016/05/25 22:40:07 Google drive root 'test': Finished reading src/code.google.com/p/google-api-go-client/.hg/store/
2016/05/25 22:40:07 Google drive root 'test': Finished reading src/code.google.com/p/google-api-go-client/.hg/
2016/05/25 22:40:07 Google drive root 'test': Finished reading src/code.google.com/p/google-api-go-client/
2016/05/25 22:40:07 Google drive root 'test': Finished reading src/code.google.com/p/
2016/05/25 22:40:07 Google drive root 'test': Finished reading src/code.google.com/
2016/05/25 22:40:07 Google drive root 'test': Finished reading src/
2016/05/25 22:40:07 Google drive root 'test': Finished reading
2016/05/25 22:40:07 Google drive root 'test': Waiting for checks to finish
2016/05/25 22:40:07 Google drive root 'test': Waiting for transfers to finish
2016/05/25 22:40:09 a: Copied (new)
```

**Comment by ncw** [comment]
This is a known problem - see #8 

I have recently done something which will help here - you can use an include filter to only include files on the top directory eg `--include "/*"` and that will now stop rclone recursing the destination.

If you know the list of files to transfer you can also use `--files-from`

You'll need this beta though

http://pub.rclone.org/v1.29-28-g36700d3%CE%B2/

**Comment by mayli** [comment]
Thanks for the explanation, will try the beta builds.
Closing this issue as dup with #8
