### ISSUE TITLE
ACD: HTTP code 401: "401 Unauthorized", reponse body: {"message":"Token has expired"}

### ISSUE THREAD

**Issue by bunset** [ncw/rclone#501]
Hello Nick! Nice to say you hello again!, I continue using rclone for my backups to amazon, but from one week ago is difficult to get a backup

Many times I get this message.
My last backup was with any progress from 8 hours ago and I have checked with easy command like lsd

------------
rclone lsd remote:
2016/05/26 14:23:33 Failed to create file system for "remote:": Failed to get endpoints: HTTP code 401: "401 Unauthorized", reponse body: {"message":"Token has expired"}
--------------------

MacBook-Pro-13:bin David$ rclone -V
rclone v1.29
MacBook-Pro-13:bin David$ rclone -v lsd remote:
2016/05/26 14:28:00 pacer: Rate limited, sleeping for 666.145821ms (1 consecutive low level retries)
2016/05/26 14:28:00 pacer: low level retry 1/10
2016/05/26 14:28:00 pacer: Rate limited, sleeping for 235.010051ms (2 consecutive low level retries)
2016/05/26 14:28:00 pacer: low level retry 2/10
2016/05/26 14:28:01 pacer: Rate limited, sleeping for 287.113937ms (3 consecutive low level retries)
2016/05/26 14:28:01 pacer: low level retry 3/10
2016/05/26 14:28:01 pacer: Rate limited, sleeping for 4.54916732s (4 consecutive low level retries)
2016/05/26 14:28:01 pacer: low level retry 4/10
2016/05/26 14:28:01 pacer: Rate limited, sleeping for 7.632969758s (5 consecutive low level retries)
2016/05/26 14:28:01 pacer: low level retry 5/10
2016/05/26 14:28:06 pacer: Rate limited, sleeping for 21.331776148s (6 consecutive low level retries)
2016/05/26 14:28:06 pacer: low level retry 6/10
2016/05/26 14:28:13 pacer: Rate limited, sleeping for 29.183117216s (7 consecutive low level retries)
2016/05/26 14:28:13 pacer: low level retry 7/10
2016/05/26 14:28:35 pacer: Rate limited, sleeping for 1m28.480279449s (8 consecutive low level retries)
2016/05/26 14:28:35 pacer: low level retry 8/10
2016/05/26 14:29:04 pacer: Rate limited, sleeping for 54.760398084s (9 consecutive low level retries)
2016/05/26 14:29:04 pacer: low level retry 9/10
2016/05/26 14:30:33 pacer: Rate limited, sleeping for 2m35.414458836s (9 consecutive low level retries)
2016/05/26 14:30:33 pacer: low level retry 10/10
2016/05/26 14:30:33 Failed to create file system for "remote:": Failed to get endpoints: HTTP code 401: "401 Unauthorized", reponse body: {"message":"Token has expired"}
MacBook-Pro-13:bin David$ 
--------------------------------------------------------------

Some days ago, I recreated the token and the installation of rclone but it doesn't fix it.
Do you know what to do ?

Thank you and kind regards,
David

> What is your rclone version (eg output from `rclone -V`)
1.29
> Which OS you are using and how many bits (eg Windows 7, 64 bit)
Mac El Capitan
> Which cloud storage system are you using? (eg Google Drive)
Amazon Cloud Drive
> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone lsd remote:
> A log from the command with the `-v` flag (eg output from `rclone -v copy /tmp remote:tmp`)

**Comment by ncw** [comment]
Alas this seems to be a problem with amazon.

Here is a test for you to try: http://pub.rclone.org/v1.29-30-g53ead43%CE%B2/

It redoes the oauth on 401 errors. This has worked for some users...

There is a thread on the forum about the 401 errors:

 https://forums.developer.amazon.com/questions/27740/401-messagetoken-has-expired.html

Please add your complaints there too!

**Comment by bunset** [comment]
Thank you Nick as always, I have checked with your new version http://pub.rclone.org/v1.29-30-g53ead43β/rclone-v1.29-30-g53ead43β-osx-386.zip, and I continue receiving the same error trying lsd.

**Comment by ncw** [comment]
Can you paste a bit of log with `-v` starting from the first 401 error?

**Comment by ncw** [comment]
Here is a second attempt to fix the 401 errors - I think this one will work properly (cross fingers!)

http://pub.rclone.org/v1.29-30-g33611be%CE%B2/

**Comment by bunset** [comment]
Crossing fingers!. Testing Nick your new version!
At the moment the backup is reading well from acd. 
My first backup is done successfully!
It is now with my second backup. 
I let it running tonight and tomorrow I send you my log and my feedback. 
I don't know if it is for your version of because now it is nice moment on amazon server, we see you and I keep you informed!

Thank you very much! Champion!

David

**Comment by bunset** [comment]
Hi Nick!
My feedback here!
With news with your new version, I have done several backups and they are going very well, very fast, very happy yesterday and today!.
The 401 error happens, but rclone does retry and retry and it continues.

One thing please, I would like to use the condition, exit code 0 of rclone, in a sh batch file, to send me an email with backup is well done, and then I can delete my computer folders knowing all files are backed up in my backup acd. 
My question is, Are you sure, exit code 0 means, backups perfect, and is it a good signal to do my deletions because all is well backed up?


Cheers. Kind regards,
David

**Comment by ncw** [comment]
@bunset good news!  I have a further small patch to work around the occasional 403 errors during authentication which I'll post in a few minutes.

Yes rclone will exit with a non-zero exit code if there were any errors it couldn't retry.  If it doesn't then that is a bug and please report an issue!

**Comment by ncw** [comment]
OK Here is beta 3 which
  * does a re-authentication on 401 errors (working as per attempt 2)
  * does a retry on that particular 403 error

http://pub.rclone.org/v1.29-33-g085677d%CE%B2/

In my testing this works perfectly now - hopefully it will for you too.

**Comment by bunset** [comment]
I have installed your new beta, last version did work very well in past 2 days doing backup all time.
I give you my feedback in some days with this new beta.

Thank you very much Nick
