### ISSUE TITLE
Can't make case insensitive filters

### ISSUE THREAD

**Issue by ed1chandler** [ncw/rclone#502]
Hopefully an easy question...

How do you specify a flag, such as the "i" flag for case-insensitivity?

**Comment by ncw** [comment]
A very good question! 

Short answer - you can't at the moment. 

It is probably essential if you are working with case insensitive file systems though. 

Easy would be to add a flag say --filters-case-insensitive which makes all filters case insensitive. (I should check the rsync man page too)  

Harder would be to make it settable for each glob. There are some ideas here: http://unix.stackexchange.com/questions/48770/how-to-match-case-insensitive-patterns-with-ls

What do you think?

**Comment by ed1chandler** [comment]
I think I'm just going to have to deal with "[Jj][Pp][Gg]" for now. ;-)

**Comment by ncw** [comment]
:-)

I'm going to re-open this as I'd quite like to add the flag option at some point!

**Comment by mjsr** [comment]
Why not use something similar to find? Prepend 'i' in the flag name to indicate that it's case insensitive:

`-name "FooBar"` vs `-iname "FooBar"`

**Comment by 2600box** [comment]
how would the -name/-iname function work with Rclone? I don't see that making sense without restructuring the way Rclone works.

ncw's suggestion of `--filters-case-insensitive` flag makes more sense.

Looking forward to this.

**Comment by calisro** [comment]
The flag isn't very robust though.  Its all or nothing.  It would have been better to have the case sensitivity within each include/exclude. 

Perhaps within the 'filter' flags only something like this gets implemented:
--filter "+i file.JpG" 

where the i represents that line is case insensitive.  That would also allow building more flags unto each rule in the future if required.

**Comment by 2600box** [comment]
we still need this

**Comment by cowwoc** [comment]
@ncw If the underlying file-system is case-insensitive then it never makes sense to use case-sensitive filtering. On Windows, I believe the FS is always case-insensitive. On Mac, I forget whether case-sensitivity is system-wide or on a per-drive basis.

In any case, I suggest that rclone detect whether the FS is case-insensitive and in such cases always interpret filters applied on it as case-insensitive (no flags required).

**Comment by ncw** [comment]
@cowwoc 
> In any case, I suggest that rclone detect whether the FS is case-insensitive and in such cases always interpret filters applied on it as case-insensitive (no flags required).

Alas it is impossible to guess, the only way to be sure is to write a file.
.
That said rclone knows pretty accurately whether a backend is case insensitive or not...

**Comment by ncw** [comment]
I've implemented the `--ignore-case` flag here:

https://beta.rclone.org/branch/v1.44-080-g16f797a7-ignore-case-beta/ (uploaded in 15-30 mins)

**Comment by ncw** [comment]
This is now merged to master and will be in [the latest beta](https://beta.rclone.org) in 15-30 mins.  It will be released in v1.45.
