### ISSUE TITLE
Modification time for Amazon Cloud Drive

### ISSUE THREAD

**Issue by fantom-x** [ncw/rclone#505]
Hi, is it possible to implement mod time support for ACD? I know the API itself does not support it, but they do support properties on the Node object: can that be used to store a mod time? ACD might be the best of the bunch cost/benefit wise, but not preserving time stamps makes it somewhat crippled.

**Comment by ncw** [comment]
I agree that this is a good idea - such a good idea that there is already an issue about it at #371 !

Can I suggest you follow that issue and I'll close this one as a duplicate.

Thanks

Nick
