### ISSUE TITLE
extra --exclude options are ignored

### ISSUE THREAD

**Issue by yotann** [ncw/rclone#506]
If I provide more than one `--exclude` option to rclone, it ignores all but the last option. For example:

```
$ touch AAA
$ touch BBB
$ rclone ls --exclude AAA --exclude BBB .
        0 AAA
```

Rclone should either combine the options or exit with an error message. At the very least, the docs should mention this limitation.

> What is your rclone version (eg output from `rclone -V`)

rclone v1.29

> Which OS you are using and how many bits (eg Windows 7, 64 bit)

Arch Linux 64-bit

**Comment by ncw** [comment]
Yes you are right...

I thought I wrote this in the docs but obviously not!

The command line parser I'm using for rclone can't do repeated options.

I made an issue about it not giving an error here spf13/pflag#72

In the mean time there are several workarounds as you've doubtless discovered
  * use `--exclude-from`
  * use a glob pattern, eg `--exclude "{AAA,BBB}"`
  * use `--filter-from`

The last is the most general purpose.
