### ISSUE TITLE
rclone vs Robocopy?

### ISSUE THREAD

**Issue by rtg20** [ncw/rclone#508]
Hi, I was just wondering if anyone knew why rclone is much slower for local destinations than Robocopy?

https://technet.microsoft.com/en-us/library/cc733145(v=ws.11).aspx

I use rclone for Google drive and backing up to a local NAS. Maybe I am doing something wrong?

**Comment by ncw** [comment]
Do you mean copying stuff from `C:` to `D:`?

And by much slower, how much slower?

One of the reasons will be that rclone is doing MD5SUMs of the files to check the data integrity.

I'd expect the platform native copying tool to be faster than rclone though in general.

Here is `rclone` vs `cp` on my linux box on the rclone source tree - here rclone is about 50% the speed of cp.  I tried it on a directory of bigger files (ISOs) and rclone was about 75% the speed of cp.

```
$ time cp -a . /tmp/rclone-cp-1

real	0m1.459s
user	0m0.012s
sys	0m0.496s
```

```
$ time rclone copy . /tmp/rclone-rclone-1
2016/06/06 13:57:33 Local file system at /home/ncw/Code/Go/src/github.com/ncw/rclone: Building file list
2016/06/06 13:57:33 Local file system at /tmp/rclone-rclone-1: Building file list
2016/06/06 13:57:35 Local file system at /tmp/rclone-rclone-1: Waiting for checks to finish
2016/06/06 13:57:35 Local file system at /tmp/rclone-rclone-1: Waiting for transfers to finish
2016/06/06 13:57:36 
Transferred:     627.875MBytes (188.573kByte/s)
Errors:                 0
Checks:                 0
Transferred:         2620
Elapsed time:        3.3s

real	0m3.338s
user	0m6.912s
sys	0m0.952s
```

**Comment by rtg20** [comment]
oh ok thanks for the info. I didn't realize it was checking MD5. That would explain it then. Thank you!

**Comment by ncw** [comment]
No problems!
