### ISSUE TITLE
Question: Is there any command to check files in source folder are in destination folder and they are same?

### ISSUE THREAD

**Issue by bunset** [ncw/rclone#509]
Hi Nick!
I copy a local source folder "Pictures" with some pictures, adding it to a destination folder "Pictures" in acd with the same name that my local folder. So in my destination folder I have the files new copied files from my local folder, plus old files copied in past backup times and deleted from my local folder. 
I would like a command in rclone to compare and just tell me if files in local folder are present and they are all the same in my acd destination folder. Not considering old files added past times because they was deleted from my local Pictures.

Is it posible Nick?

Thank you!

When filing an issue, please include the following information if
possible as well as a description of the problem.

> What is your rclone version (eg output from `rclone -V`)
1.29
> Which OS you are using and how many bits (eg Windows 7, 64 bit)
mac capitan
> Which cloud storage system are you using? (eg Google Drive)
ACD
> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

> A log from the command with the `-v` flag (eg output from `rclone -v copy /tmp remote:tmp`)

**Comment by ncw** [comment]
If you do a `rclone --dry-run copy local remote:` then it will list any files that needs updating from the local to the remote.

Is that what you mean?

**Comment by bunset** [comment]
It can be, let me explain you with this phrase.
I need it lists any files presents in local, and no presents in remote, or needs updating in remote.

Thank you very much and regards!

**Comment by ncw** [comment]
I think `rclone --dry-run copy local remote:` will do exactly that.

**Comment by bunset** [comment]
Fantastic, I am seeing that Transferred = 0 and Errors = 0 means that all in local is equal in remote, 
I am creating a bash file which it runs normal rclone copy and next rclone --dry-run copy, then I would like to add this "read rclone --dry-run copy log file and, if Transferred=0 and Errors=0, then send me an email telling me that "backup comparation: files in source are present in remote and they are equal".

How can I do the part "if Transferred=0 and Errors=0"?
Do you know any awk or similar to check this?

Thank you very much
David

**Comment by ncw** [comment]
Sorry, not a shell expert :-(

I'm going to close this now as I think we've got to the bottom of the rclone stuff.

Thanks

Nick
