### ISSUE TITLE
"Unknown command" when attempting glob matching with exclude

### ISSUE THREAD

**Issue by boozedog** [ncw/rclone#510]
When filing an issue, please include the following information if
possible as well as a description of the problem.

> What is your rclone version (eg output from `rclone -V`)
rclone v1.29

> Which OS you are using and how many bits (eg Windows 7, 64 bit)
Mac OS X 10.11.5 64 bit

> Which cloud storage system are you using? (eg Google Drive)
S3

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
`rclone -n --exclude {one,two}_potato sync ~/test s3:test`

Response:
`2016/06/05 12:38:10 Unknown command "two_potato"`

**Comment by boozedog** [comment]
ugh, needed single quotes around the exclude value ...

`rclone -n --exclude '{one,two}_potato' sync ~/test s3:test`

**Comment by ncw** [comment]
Easy mistake to make.  +1 for use of potato as a nonce word ;-)
