### ISSUE TITLE
Stop rclone changing modification time

### ISSUE THREAD

**Issue by rtg20** [ncw/rclone#511]
Here's my suggestion: a command-line option to stop rclone changing the modification time without using checksum or size-only. When the modification time changes, it can confuse the Google Drive client and result in duplicate files. Use of checksum works, but slows down the sync.

thank you!

**Comment by rtg20** [comment]
Thanks for considering this one. Also I had another idea, perhaps rclone could check checksums on the remote storage and restore modification times if they matched the source file? This would help people who use the official Google Drive client.  It could be a command line option.

**Comment by ncw** [comment]
This is in the v1.31 release :-)

**Comment by jondavidjohn** [comment]
Would it make sense to always use `--no-update-modtime` AND `--ignore-times` together?  If we're not modifying the modified time on the destination, we probably don't want to use it to check for file updates?
