### ISSUE TITLE
How to rclone move without deleting base folder from source?

### ISSUE THREAD

**Issue by jerblack** [ncw/rclone#512]
Hello, I'm using rclone 1.29 on Ubuntu Mate 16.04, and I'm trying to move the contents of a local folder to a folder on Google Drive. What I'm seeing is that once the move finishes, the base folder that was specified as a source is getting deleted too. The command I am using looks like this:

rclone --retries 50 move /home/user/encrypted google_drive:transfer

I just want the contents of that encrypted folder moved, but the encrypted folder itself is being removed at the end of the move as well. I tried appending a / to the src path, and that didn't seem to make a difference. The base folder still gets deleted with a / appended. How can I move the contents of a folder without removing the folder itself?

Thanks.

**Comment by jerblack** [comment]
I saw that someone else posted a similar problem, and they say they fixed it by creating a file in the base of the source folder and using --exclude on that file. That does work (as a workaround) but it also fails to delete the other folders from the source once they are emptied, so using that option would mean I am left with a bunch of empty folders after a move.

**Comment by ncw** [comment]
I don't think there is a single option for that at the moment in rclone!

`move` is equivalent to `copy` followed by `purge`.

There is a good reason for using purge - deleting the empty directories as you've discovered, and also it is a lot more efficient on some remotes.

If you apply filters, then `move` becomes equivalent to `copy` followed by `delete`.  rclone currently doesn't delete the empty directories (but likely it will in the near future).

I'd probably suggest you use the `move` without the filters, then use a `mkdir` afterwards to re-create the directory - would that work for you?

**Comment by jerblack** [comment]
I didn't want to delete the folder because it's part of a FUSE mount, but I did figure out how to work around the problem by using an exclude file and then deleting the empty folders after the move with find.

```sh
SRC=/home/$USER/torrents/encrypted
DST=google_drive:transfer
rclone --exclude /hold --retries 50 move $SRC $DST
find $SRC -empty -type d -delete
```
