### ISSUE TITLE
Change of Google Cloud Storage's JSON API 

### ISSUE THREAD

**Issue by pjrobertson** [ncw/rclone#513]
Using rclone v1.27 (originally on v1.07) on Linux 64 bit, connecting to Google Buckets.
Command is:
`/rclone -v sync dir_to_sync google:google_bucket`

Hi all, apologies if this has already been answered/fixed.
I have been using rclone to sync to Google's buckets for some time now, and yesterday I got an email from Google saying the software I was using to sync needs updating/adjusting.
Is this something you guys are aware of/have already fixed? I was originally using rclone 1.07 and have just updated to v1.27, but I am unsure if the problem is fixed in this version.

Here's the email:

> Dear Google Cloud Storage JSON API customer,

> Important: An upcoming change to improve Google Cloud Storage's JSON API request validation will cause some of the types of object uploads that you have made recently to be rejected as invalid requests.

> Google Cloud Storage is making a bug-fix change to ensure that objects are always given the Content-Type intended by the uploader. You are being contacted as a project-owner of a project whose buckets have received upload requests in the last two weeks that would, under the new validation, be rejected because the Content-Type as specified by the media does not match the Content-Type as specified by the metadata. The following buckets, listed by project, have been identified as having received such upload requests:

> [my_bucket]

> If you upload content using:

> uploadType=media, there is nothing to address in that code path, as this upload type is not impacted by the change.
> uploadType=multipart, then if you specify a contentType in the JSON body of the first part, and you specify a Content-Type header of the second part, and they do not match, the request will be rejected.
> uploadType=resumable, then if you specify a contentType in the JSON body of the request to initiate the resumable upload session, and you specify a X-Upload-Content-Type header on that same request, and they do not match, the request will be rejected.
> From our analysis, of the tiny fraction of customers who are affected by this change, all are using https://github.com/google/google-api-go-client. The Go client defaults to trying to auto-determine the > Content-Type of the Media provided for upload and often conflicts with any custom contentType that was provided in the object's metadata. This behavior can be suppressed with the MediaOptions.ContentType("") as [described here](https://godoc.org/google.golang.org/api/googleapi#ContentType), with code that looks like:

> result, err := svc.Objects.Insert("BUCKET", &storage.Object{Name: "OBJECT", ContentType:"example/foo"}).Media(file, googleapi.ContentType(""))

> This capacity was added with [this commit](https://github.com/google/google-api-go-client/commit/e61f6e00cdf8b78313641288c50f6e2d4e3d749c), so update your Go client, and update your code.

> We plan to make the change on 1st August 2016. We are monitoring the requests that would be affected by this change, and will send out reminders leading up to the change date. If you have any questions or concerns, please do not hesitate to contact us.

**Comment by gdubicki** [comment]
I am using rclone built from source, commit 3bdad260, and I got this email from Google too.

But note that the files that Google detected may have been created by some previous version of rclone, which I have tested on my buckets before.

**Comment by pjrobertson** [comment]
FWIW I’m pretty sure I’ve only ever used rclone v1.07 to send files to Google. I set up a script to backup to Google’s buckets once and have never touched it since.

**Comment by ncw** [comment]
No I haven't seen this - thanks for bringing it to my attention.

I'll investigate further and if any fix is needed I'll get it into the next release.

**Comment by ncw** [comment]
I have updated the google api package I build against and put the recommended fix in.

Here is a beta for you to try: http://pub.rclone.org/v1.29-1-gbb75d80-54-g6617157%CE%B2/

Please re-open if you find any problems

**Comment by pjrobertson** [comment]
Thanks! I'm not sure if Google will re-notify us in the future, but we can for sure try it out
