### ISSUE TITLE
Transfer files to Googledrive created double folders

### ISSUE THREAD

**Issue by HyperCriSiS** [ncw/rclone#516]
Hi,

I transferred data to Googledrive and rclone created the folders that where already on Googledrive a second time with the same name?
Whats wrong there?
And can I move only files and keep folders?

Thanks,
Hyper

**Comment by ncw** [comment]
I think this is probably #28 - sometimes rclone manages to create duplicates :-(  This has got a lot better over the years but still isn't perfectly fixed.

You can use the `rclone dedupe` command to help manage the problem, or remove duplicates by hand - rclone doesn't mind.

**Comment by HyperCriSiS** [comment]
I just wonder, if it dedupes the folder won't it skip the files in the folder then?
I remember having a duplicate file warning and I did not have dedupe enabled.
Beside that, there was also no duplicate file. Strange thing :)

**Comment by HyperCriSiS** [comment]
Just found out google-api allows duplicates, as the name is just an attribute.
One the one side this is really nice, but in this case it sucks :(

**Comment by ncw** [comment]
dedupe will help you remove the duplicate files.

The duplicate file names are rather annoying but don't happen too often.

**Comment by ncw** [comment]
Can you post the comand line you used for the transfer too please?

**Comment by robjlg** [comment]
Hello, I also end up with a lot of duplicates. I have discovered that this happen when building file list fails and rclone tray to upload a file that is already on drive (instead of update it).

Increasing  retries have reduced duplicates.

Is it possible to not sync if there are errors when building the list?  Maybe a command  flag  for this option.

Thank you

Roberto

**Comment by ncw** [comment]
Have you tried the latest release? It will abort if the listing fails and it double check the file doesn't exist before uploading so I hope it might help your issues.

**Comment by robjlg** [comment]
I was using rclone v1.29.  Will download and try 1.30

Thank you

**Comment by ncw** [comment]
I'm going to close this as we have #28 open to track this issue
