### ISSUE TITLE
Unable to get initial authorization from Amazon Cloud Drive

### ISSUE THREAD

**Issue by dvpetta** [ncw/rclone#519]
Hello,

Thanks for the app, can't wait for it to work!

Having trouble with my first set up of rclone.  I got as far as running config, logging into my amazon account within rclone, "Y" for auto config, browser opens up to the http://127.0.0.1:53682/auth website only to return this error message:

http://imgur.com/IGMpJKt

Using latest version of rclone v 1.29
Mac OSX latest 10.11.5
Amazon Cloud Drive
Attempted to run\
**_Remote config
Use auto config?
 * Say Y if not sure
 * Say N if you are working on a remote or headless machine
y) Yes
n) No
y/n> y
If your browser doesn't open automatically go to the following link: http://127.0.0.1:53682/auth
Log in and authorize rclone for access
Waiting for code..._**

Very new to terminal and not too sure what I'm doing but thank you in advance for your help.

Daniel

**Comment by ncw** [comment]
I see what happened. 

When you configured rclone you put your email as the client id. You need to leave that blank and it should work. 

Hope that helps. 

Nick

**Comment by dvpetta** [comment]
OK thank you. That helped!

One other question.  I have already uploaded about half of my nas to the amazon cloud and want rclone to upload the remaining data.  

Now that I have fully configured rclone (I think!) I'm not sure if I should use:

    copy source:path dest:path
or
    sync source:path dest:path

Not sure the best way of going about this as it's 3TB in total, 2TB of which are on the cloud now.

Thanks!

**Comment by ncw** [comment]
Either should work.  Use `copy` if you don't want to delete stuff in amazon cloud.  Use `sync` if you want to delete stuff in the cloud that is no longer on your NAS.

Either way, experiment with the `--dry-run` flag first.
