### ISSUE TITLE
Support for sFTP

### ISSUE THREAD

**Issue by austinginder** [ncw/rclone#521]
Not sure if this is on wishlist yet but having sFTP support would be awesome. I currently run a lftp script to pull down files then rclone to push files to Dropbox. Would be ideal to use rclone for both syncs. Maybe this library would be a good starting point: https://github.com/pkg/sftp.

**Comment by ncw** [comment]
Thanks for the suggestion.

That library looks very good and has all the primitives rclone would need I think.

**Comment by jhuscott** [comment]
+1

**Comment by stevenmills** [comment]
+1

**Comment by ncw** [comment]
Here is a beta of the SFTP support: http://pub.rclone.org/v1.35-60-g74801de-sftp%CE%B2/

Any testing much appreciated!

**Comment by ncw** [comment]
Here is a slightly better beta which won't flake out after 1024 files!

http://pub.rclone.org/v1.35-60-gfdb7dfe-sftp%CE%B2/

**Comment by ncw** [comment]
I have merged this to master now - see here for a beta:

http://beta.rclone.org/v1.35-74-g48cdedc/

Any feedback much appreciated

**Comment by kubark42** [comment]
> Any feedback much appreciated

Used directions at https://github.com/ncw/rclone/blob/48cdedc97b238a18bdc33b6930e3a6af0ffd8e9d/docs/content/sftp.md. Using a password worked great! 

However, when working with the same server, I couldn't get `ssh-agent` to work:
```
rclone-v1.35-158-g4652db3β-osx-amd64/rclone lsd seit:
2017/03/06 14:33:52 Failed to create file system for "seit:": couldn't connect ssh: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
```

And yet when I do an `ssh remote_server_foo.bar.com` I can log in perfectly with the key, i.e. no password request.

Here's the config:
```
[seit]
type = sftp
host = remote_server_foo.bar.com
user = kenz
port = 
pass = 
--------------------
Edit remote
Value "host" = "remote_server_foo.bar.com"
Edit? (y/n)>
y) Yes
n) No
```

After it didn't work, I edited the config to add a password and it worked again. So I'm fairly sure I configured everything else properly.

**Comment by ncw** [comment]
@kubark42 Hmm, I wonder if that is an OS X problem.  Can you make a new issue with the above in please?

Thanks
