### ISSUE TITLE
s3: please support arbitrary non-Amazon S3 providers

### ISSUE THREAD

**Issue by robbat2** [ncw/rclone#522]
Please support S3 providers other than Amazon, including self-hosted options.

Open source implementing the S3 API (partial list):
http://docs.ceph.com/docs/master/radosgw/s3/
https://www.minio.io/
http://www.skylable.com/products/libres3/
https://github.com/scality/S3
https://github.com/cloudfoundry-attic/vblob
https://github.com/basho/riak_cs
http://s3ninja.net/

It'll need to support both the v2 & v4 signature algorithms as well as the different S3 path formats (eg bucket name in hostname vs path).

**Comment by ncw** [comment]
rclone does support arbitrary S3 providers with v2 and v4 auth - check the docs here: http://rclone.org/s3/

You just specify your endpoint in the config.

Many people use it with Ceph (eg Dreamhost).

**Comment by robbat2** [comment]
Maybe need to make it more visible in the documentation. I'm going to open a bunch of separate bugs on  missing functionality from those that I'm finding.
