### ISSUE TITLE
Mac: Along days using rclone in my batch backups I get several rclone process in my process list and they never killed

### ISSUE THREAD

**Issue by bunset** [ncw/rclone#525]
Hello Nick
rclone continue working very well here but I want to comment a little detail. I have seen that my process list in cpu is getting lot of rclone never killed along days of backups, using 0%cpu and staying endless. Would it possible any mechanism to kill automatically all these no useful process abandoned?.

Thank you and kind regards
David
 

When filing an issue, please include the following information if
possible as well as a description of the problem.

> What is your rclone version (eg output from `rclone -V`)
1.29
> Which OS you are using and how many bits (eg Windows 7, 64 bit)
mac el capitan
> Which cloud storage system are you using? (eg Google Drive)
acd
> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone copy local remote
> A log from the command with the `-v` flag (eg output from `rclone -v copy /tmp remote:tmp`)

**Comment by ncw** [comment]
Are you running rclone off the crontab?

If so how do you check it has finished before starting the next one?

Are you using any flags?

Can you see why those rclones stopped from the log?

It would be easy to add a `--time-limit` flag which just killed rclone if that much time had elapsed - would that help?

**Comment by bunset** [comment]
I call rclone from a .sh file, my sh file is invoked from Automator, (if you don't know it, Automator is a Mac program that lets you define actions to run when an specific event happens), I my case I have it configured to run my sh batch program when I plug my external usb drive.
In my sh batch program I have an if condition to run only rclone if there isn't any other instance of clone in my process list. All is working well excepts usually rclone is not autokilled at the end and it remains in process list, so I usually, before doing my backup I check if there is any dead instance of rclone and I kill them manually.

Your suggestion about --time-limit flag I think doesn't fit for me because sometimes my clone backup is done in some hours and sometimes is done in 3 or 4 days because I backup a full usb hard disk.

My rclone sentence is like this:
rclone -v copy /Volumes/Macbook13\ 500GB/reportajes/ remote:10-1/reportajes/ 

Thank you Nick!

**Comment by bunset** [comment]
I forgot to tell you how I check if any other rclone instance is running:

Inside my sh this is my if:

if pgrep rclone;
then
 echo "you can't run rclone backup now because there is another rclone in execution"
else
     rclone copy ......
fi

**Comment by bunset** [comment]
I will paste you here how rclones stopped from the logs.

**Comment by ncw** [comment]
Are you still having problems with this?

**Comment by ncw** [comment]
I'm going to close this as I haven't heard from you for a while, please re-open if you have more info.

**Comment by magefesa** [comment]
Hi ! I m trying to execute Rclone from a sh file, the rclone is working well when i execute from terminal, but if i include on sh file, automator says "unknown command Rclone"... Please any ideas ? 

Thanks a lot  !

**Comment by ncw** [comment]
@magefesa I suggest you ask for help on the [forum](https://forum.rclone.org/).
