### ISSUE TITLE
rclone is rebooting my mac

### ISSUE THREAD

**Issue by juliantoledo** [ncw/rclone#526]
> What is your rclone version (eg output from `rclone -V`)
rclone v1.29

> Which OS you are using and how many bits (eg Windows 7, 64 bit)
Mac OS X 10.11.5

> Which cloud storage system are you using? (eg Google Drive)
Amazon Cloud Drive

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

> A log from the command with the `-v` flag (eg output from `rclone -v copy /tmp remote:tmp`)
6/16/16 10:50:36.000 PM kernel[0]: process rclone-bin[6526] caught causing excessive wakeups. Observed wakeups rate (per sec): 4185; Maximum permitted wakeups rate (per sec): 150; Observation period: 300 seconds; Task lifetime number of wakeups: 45016
6/16/16 10:50:36.318 PM spindump[512]: Saved wakeups_resource.diag report for rclone-bin version ??? (???) to /Library/Logs/DiagnosticReports/rclone-bin_2016-06-16-225036_iMac.wakeups_resource.diag

**Comment by klauspost** [comment]
It is probably a system stability issue unrelated to (but triggered by) rclone. In general no application should be able to crash your computer.

Found this somewhere on the net:

>These messages and reports are normal. They neither indicate a problem with the computer or the App. They only indicate that System Monitor is using services of the operating system core (kernel) more often as OS X is expecting it for average applications. Software developers can use such reports to reduce the energy consumption created by Apps.

**Comment by ncw** [comment]
I'm going to close this as I don't think it is an rclone problem.

The logs you pasted are indicative of rclone doing lots of work - it might be that this is overheating your CPU and triggering instability.  You could check with a CPU stress testing tool.
