### ISSUE TITLE
rclone (hubiC) not uploading/syncing empty folders

### ISSUE THREAD

**Issue by Tazintosh** [ncw/rclone#527]
Hello guys,

Not sure if it's the standard behavior but it feels wrong to me.
When I run a sync or copy command to my hubiC storage, I've noticed that local empty folders were not uploaded to my hubiC.

Using rclone 1.29
Running on Mac OS X 10.11.5
The command I run is like:
`rclone sync -v --transfers=20 /localPath hubic:remotePath`

**Comment by ncw** [comment]
That is expected behaviour, for two reasons.

The first is that rclone doesn't manage directories at the moment #100 

The second is that hubic is based on swift, and swift only stores objects, not directories.

**Comment by Tazintosh** [comment]
Ok, thanks for the answer ncw.
