### ISSUE TITLE
dropbox: case insensitivity causes duplicated files

### ISSUE THREAD

**Issue by shalupov** [ncw/rclone#53]
I'm trying to sync Dropbox to my local machine (Linux) with rclone -v -n sync dropbox:/ ~/data

```
$ rclone -v -n sync dropbox:/ ~/data 2>&1 | grep -i Console2
2015/05/03 22:48:14 tools/Console2/Console.exe: Not copying as --dry-run       
2015/05/03 22:48:14 tools/Console2/console.chm: Not copying as --dry-run       
2015/05/03 22:48:14 tools/Console2/FreeImage.dll: Not copying as --dry-run     
2015/05/03 22:48:14 tools/Console2/ConsoleHook.dll: Not copying as --dry-run   
2015/05/03 22:48:14 tools/Console2/FreeImagePlus.dll: Not copying as --dry-run 
2015/05/03 22:48:14 tools/Console2/console.xml: Not copying as --dry-run       
2015/05/03 22:48:28 Tools/Console2/console.chm: Not deleting as --dry-run      
2015/05/03 22:48:29 Tools/Console2/ConsoleHook.dll: Not deleting as --dry-run  
2015/05/03 22:48:29 Tools/Console2/FreeImagePlus.dll: Not deleting as --dry-run
2015/05/03 22:48:29 Tools/Console2/FreeImage.dll: Not deleting as --dry-run    
2015/05/03 22:48:29 Tools/Console2/console.xml: Not deleting as --dry-run      
2015/05/03 22:48:29 Tools/Console2/Console.exe: Not deleting as --dry-run      
```
while
```
$ rclone lsd dropbox:/
[...]
           0 0001-01-01 00:00:00        -1 Tools
[...]

$ rclone lsd dropbox:/Tools
[...]
           0 0001-01-01 00:00:00        -1 Console2
[...]

$ ls -la ~/data
[...]
drwxrwxrwx 18 dropboxbackup dropboxbackup       19 May  1 17:57 Tools
[...]
```

Looks like some case problem.

Thank you!

**Comment by ncw** [comment]
I forgot to write this in the docs, but dropbox is case insensitive which explains some of the above.

I tried to replicate this but I couldn't yet...

Is it just the the tools directory which appears duplicated?  Where did it come from?  Did you upload it?

Can you make a reproducer for me so I can see the problem on my dropbox account?

Thanks

Nick

**Comment by zeshanb** [comment]
I would use rClone wizard (rclone config) to create a local file system
config as well instead of using:

~/data

Maybe call it downloadto: . This should resolve the issue.

All the best,

Zeshan

**Comment by shalupov** [comment]
Thanks, it'll try to reproduce it on standalone account. I'll also try rclone config for local file system (just in case).

**Comment by shalupov** [comment]
I've found https://www.dropboxforum.com/hc/communities/public/questions/201665409-Wrong-character-case-of-folder-name-when-calling-listFolder-using-Sync-API?locale=en-us

Looks like only last path component is case-reliable:
> Dropbox and the API itself are case insensitive, so in some cases you will see this behavior. (We realize this is non-ideal of course and are looking into ways to improve.) That said, the best solution here is to do a case-insensitive search in your code too.
>  Also, the last path component will always be the expected case though, so alternatively you can build up the paths manually on your side just using those.

**Comment by shalupov** [comment]
I've checked (via printf), Dropbox API returns paths in different cases in Entry.Path.
Also stripRoot works incorrectly in that case.

**Comment by ncw** [comment]
@shalupov thanks for the investigation - that link is useful.

I'll have a think on how to make rclone ignore the case in paths.

The easiest way would be just to lower case everything, but that isn't ideal as people really like the case in their file names to be correct!

The other way will involve building an internal map of paths in lower case.  This should be possible since the last component is always case-reliable.

**Comment by ncw** [comment]
I've made a note about this in the rclone docs which will appear shortly at http://rclone.org/drive/
