### ISSUE TITLE
b2: make large file upload multi-threaded

### ISSUE THREAD

**Issue by ncw** [ncw/rclone#531]
Upload many chunks at once for the large file upload.

This should be quite straightforward.

Will probably want a flag to control how many threads per large file upload as each thread will use 96MB of memory. Perhaps set this to `--transfers` and use a token system to make sure we don't exceed that many in total, so max memory use remains at 96MB * `--transfers`.

**Comment by ncw** [comment]
Here is a beta for this feature: http://pub.rclone.org/v1.30-21-g018fe80%CE%B2/

**Comment by ZacharyDuBois** [comment]
👍
