### ISSUE TITLE
rclone sync a file bigger than 5GB to Amazon S3 throws "Failed to read set modification time: InvalidRequest: The specified copy source is larger than the maximum allowable size for a copy source" error

### ISSUE THREAD

**Issue by sutees** [ncw/rclone#534]
**Issue?**
I'm using rclone to sync file against Amazon S3. When it sync a file bigger than 5GB, it will throws the error " Failed to read set modification time: InvalidRequest: The specified copy source is larger than the maximum allowable size for a copy source: 5368709120". However, the file gets uploaded to Amazon S3 but the "rcloen sync" command keep throw the error and I'm unable to write a script to wrap rclone properly as it return status is "1".

**What is your rclone version (eg output from `rclone -V`)**
rclone v1.30

**Which OS you are using and how many bits (eg Windows 7, 64 bit)**
Oracle Linux Server release 6.7, 64-bit

**Which cloud storage system are you using? (eg Google Drive)**
Amazon S3

**The command you were trying to run (eg `rclone copy /tmp remote:tmp`)**
rclone sync --retries 1 -v "/a/local/folder/on/my/local/host/A-7GB-file.zip" "s3-ap-southeast-1:my-s3-bucket-name/a/remote/folder/"

**A log from the command with the `-v` flag (eg output from `rclone -v copy /tmp remote:tmp`)**

[root@my-server-name scripts]# rclone sync --retries 1 -v "/a/local/folder/on/my/local/host/A-7GB-file.zip" "s3-ap-southeast-1:my-s3-bucket-name/a/remote/folder/" ; echo "Status:$?"
2016/06/19 15:40:22 rclone: Version "v1.30" starting with parameters ["rclone" "sync" "--retries" "1" "-v" "/a/local/folder/on/my/local/host/A-7GB-file.zip" "s3-ap-southeast-1:my-s3-bucket-name/a/remote/folder/"]
2016/06/19 15:40:23 S3 bucket my-s3-bucket-name path a/remote/folder/: Modify window is 1ns
2016/06/19 15:40:23 Local file system at /a/local/folder/on/my/local/host limited to 1 objects: Building file list
2016/06/19 15:40:23 Local file system at /a/local/folder/on/my/local/host limited to 1 objects: Done building file list
2016/06/19 15:40:23 S3 bucket my-s3-bucket-name path a/remote/folder/: Building file list
2016/06/19 15:40:23 S3 bucket my-s3-bucket-name path a/remote/folder/: Done building file list
2016/06/19 15:40:23 S3 bucket my-s3-bucket-name path a/remote/folder/: Waiting for checks to finish
2016/06/19 15:40:23 S3 bucket my-s3-bucket-name path a/remote/folder/: Starting deletion
2016/06/19 15:40:23 Waiting for deletions to finish
2016/06/19 15:40:23 S3 bucket my-s3-bucket-name path a/remote/folder/: Deletion finished
2016/06/19 15:40:23 A-7GB-file.zip: Modification times differ by 1038h2m23.924884376s: 2016-04-20 19:17:38 +0700 ICT, 2016-06-03 01:20:01.924884376 +0700 ICT
2016/06/19 15:41:23
Transferred:            0Bytes (0Byte/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:      1m0.3s
Checking:
 * A-7GB-file.zip

2016/06/19 15:42:23
Transferred:            0Bytes (0Byte/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:      2m0.3s
Checking:
 * A-7GB-file.zip

2016/06/19 15:43:23
Transferred:            0Bytes (0Byte/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:      3m0.3s
Checking:
 * A-7GB-file.zip

2016/06/19 15:43:52 A-7GB-file.zip: Failed to read set modification time: InvalidRequest: The specified copy source is larger than the maximum allowable size for a copy source: 5368709120
        status code: 400, request id: 6FDF181A1ABAC07A
2016/06/19 15:43:52 A-7GB-file.zip: Size of src and dst objects identical
2016/06/19 15:43:52 A-7GB-file.zip: Unchanged skipping
2016/06/19 15:43:52 S3 bucket my-s3-bucket-name path a/remote/folder/: Waiting for transfers to finish
2016/06/19 15:43:52 S3 bucket my-s3-bucket-name path a/remote/folder/: Waiting for deletes to finish (during+after)
2016/06/19 15:43:52 Attempt 1/1 failed with 1 errors
2016/06/19 15:43:52
Transferred:            0Bytes (0Byte/s)
Errors:                 1
Checks:                 1
Transferred:            0
Elapsed time:     3m29.4s
2016/06/19 15:43:52 Go routines at exit 2
Status:1
[root@my-server-name scripts]#

**Comment by ncw** [comment]
This is because the [COPY](http://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectCOPY.html) command used to set the metadata can't set metadata on files bigger than 5 GB.

I think an acceptable work-around would be just to ignore requests to set the metadata for files > 5GB.

I've implemented this in the beta below:

http://pub.rclone.org/v1.30-3-ga67c746%CE%B2/

Please re-open the ticket if it doesn't work properly!

Thanks

Nick

**Comment by sutees** [comment]
I would like to confirmed the issue is now fixed in [http://pub.rclone.org/v1.30-3-ga67c746%CE%B2/](http://pub.rclone.org/v1.30-3-ga67c746%CE%B2/).

**Comment by limbo127** [comment]
rclone v1.44 same issue here : 
rclone copy
2018/11/08 09:41:52 ERROR : ccb5c080-34d4-11e1-b525-eca86bf92546-1515836867.cebox: Failed to copy: InvalidRequest: The specified copy source is larger than the maximum allowable size for a copy source: 5368709120
	status code: 400, request id: 543636144E523144, host id: 7/tvHywd3avqEkFdDaw6d0T4KlOiubh1JQBGwuZsCQiQ53/NtMvUOWBjNmUPmHen2YzYHfK8f9E=

**Comment by ncw** [comment]
@limbo127 
> rclone v1.44 same issue here :
> rclone copy
> 2018/11/08 09:41:52 ERROR : ccb5c080-34d4-11e1-b525-eca86bf92546-1515836867.cebox: Failed to copy: InvalidRequest: The specified copy source is larger than the maximum allowable size for a copy source: 5368709120
> status code: 400, request id: 543636144E523144, host id: 7/tvHywd3avqEkFdDaw6d0T4KlOiubh1JQBGwuZsCQiQ53/NtMvUOWBjNmUPmHen2YzYHfK8f9E=

Can you please make a [new issue on github](https://github.com/ncw/rclone/issues/new) about this and fill in all the info in the issue template - thanks :-)
