### ISSUE TITLE
Google Drive : Cannot rename a file in remote

### ISSUE THREAD

**Issue by ishanthilina** [ncw/rclone#535]
RClone version : rclone v1.30
OS : Fedora 23 64 bit
Cloud System : Google Drive
Command Ran : ./rclone sync ~/gdrive/Photo\ Archive/ GDrive:Photo\ Archive

There's a file named FILE1 in my remote (Google Drive). The same file is in local machine as well. Then I renamed the file in GDrive to File 2 (using the web browser). After running the sync command again, I can see that the FILE2 has been deleted and FILE1 has again been uploaded to Drive.

Shouldn't the ideal behaviour be renaming the local copy of FILE1 to FILE2?

Part of the log  (wwtest = FILE2, test = FILE1) :

> 2016/06/19 14:27:51 2006/wwtest: Deleted
2016/06/19 14:27:51 Google drive root 'Photo Archive': Deletion finished
2016/06/19 14:27:52 pacer: Rate limited, increasing sleep to 2s
2016/06/19 14:27:52 pacer: low level retry 1/1 (error googleapi: Error 403: Rate Limit Exceeded, rateLimitExceeded)
2016/06/19 14:27:52 2006/test: Received error: googleapi: Error 403: Rate Limit Exceeded, rateLimitExceeded - low level retry 1/10
2016/06/19 14:27:52 2006/test: Removing failed copy
2016/06/19 14:27:52 pacer: Reducing sleep to 10ms
2016/06/19 14:27:52 2006/test: Failed to remove failed copy: googleapi: got HTTP response code 404 with body: Not Found
2016/06/19 14:27:56 2006/test: Copied (new)
2016/06/19 14:27:56 Google drive root 'Photo Archive': Waiting for deletes to finish (during+after)

**Comment by klauspost** [comment]
You assume a two-way sync. rclone does not do that, it synchronizes from the source to the destination.

You are syncing FROM your local drive TO the remote gdrive. Therefore it will make your gdrive look like your local drive..
