### ISSUE TITLE
Support for HTTP proxy

### ISSUE THREAD

**Issue by JensRantil** [ncw/rclone#538]
At least S3 is using HTTP for communication. Would be nice if rclone could support using an HTTP proxy where applicable. Preferably, by picking up `http_proxy`/`https_proxy` from environment variables and/or allowing a configuration property for it.

**Comment by ncw** [comment]
Actually it does already!

See the FAQ (could maybe be a better place for this info!)

## Can I use rclone with an HTTP proxy? ##

Yes. rclone will use the environment variables HTTP_PROXY, HTTPS_PROXY and NO_PROXY, similar to cURL and other programs.

HTTPS_PROXY takes precedence over HTTP_PROXY for https requests.

The environment values may be either a complete URL or a “host[:port]“, in which case the “http” scheme is assumed.

The NO_PROXY allows you to disable the proxy for specific hosts. Hosts must be comma separated, and can contain domains or parts. For instance “foo.com” also matches “bar.foo.com”.

**Comment by ncw** [comment]
Hopefully the above helped.  I'm going to close this now.

**Comment by JensRantil** [comment]
Sorry, that helped. Thanks!
