### ISSUE TITLE
Google Drive not Updating. Maybe...

### ISSUE THREAD

**Issue by kc6ufm** [ncw/rclone#539]
Using rclone 1.30 on Linux Mint 17.2 Cinnamon 32 bit.

Install went perfect, manual very complete and easy to follow, and all seems well. Configuration went smooth and easy.

Gave the command `rclone copy Test01 remote:Test01` and there were no errors.

BUT...

When I go to Google Drive on the web or on my phone, the files (just a test bunch) and directories do not appear.

Give the `rclone ls remote:` or `rclone lsd remote:` commands produce the file/directory lists expected from the copy session.

I suspect I'm doing something stupid and the answer will embarrass me to no end, but I'm fresh out of ideas!

Thanks for any feedback and help.

**Comment by ncw** [comment]
I just tried this with my computer and it worked fine.  I uploaded a file to drive then saw it appear on my phone and on the drive website.

Is is possible that you connected rclone to a different google drive by accident during the signup process?

You could try `rclone config` again to make sure.

It could be a google problem I suppose - some caching layer not working properly.

Nothing obvious springs to mind!

**Comment by kc6ufm** [comment]
Ah ha!

Your comment about connecting to the right drive was the key! It seems rclone opens the default web browser to get the token, and I had missed that. The default browser on my system is associated with a different Google user than I wanted to use.

So I went to the `http://127.0.0.1:53682/auth` link manually in the secondary browser (with the Google account I want to use with rclone), got the token there, and voilà! All is now working as it should.

That's what I get for not paying attention to the browser window rclone was opening!

Many thanks!

**Comment by ncw** [comment]
Glad it is sorted! By all means suggest some words for the docs or the signup process if you think it could be improved.
