### ISSUE TITLE
FTP support

### ISSUE THREAD

**Issue by jakop345** [ncw/rclone#540]
pls add ftp support.

**Comment by ncw** [comment]
Certainly something I'd consider adding should enough people want it or I receive a pull request for it :-)

**Comment by xtechgamer735** [comment]
+1

**Comment by erse80** [comment]
+1

**Comment by zeshanb** [comment]
-1 sorry

IMHO purpose of rclone seems to be to store and retrieve data that sits
behind Application Programming Interface(API).

**Comment by zioproto** [comment]
+1

We use rclone to move big data from ftp to object storage. At the moment we have to mount the ftp server with fusefs as a local file system. The performance is not good, it would be much better to have rclone able to speak FTP

**Comment by arcimboldo** [comment]
+1

There are many scientific datasets stored on ftp servers right now, and they might stay there for "legacy" reasons. However, having a copy on a cloud storage would allow new applications to be written more cloud-friendly and help the migration from filesystem based data management to API-based.

**Comment by ncw** [comment]
I think FTP sits well with rclone.  The trouble with it is that it is a rather loosely defined protocol and the whole control channel & data channel thing will make rclone's life more complicated.  The first thing to do would be to evaluate the various FTP client libraries available.

**Comment by austinginder** [comment]
+1

Also mentioned sFTP here: https://github.com/ncw/rclone/issues/521

**Comment by zeshanb** [comment]
@nick

Would you like a list of available ftp libraries in a spreadsheet format or
CSV is okay? Also, what column names do you prefer for the available
libraries?

**Comment by ncw** [comment]
In the this issue [as a table](https://help.github.com/articles/organizing-information-with-tables/) would be perfect.  Don't mind about column names.  Thanks in advance!

**Comment by zeshanb** [comment]
| Path | Synopsis |
| ------------- | ------------- |
| github.com/jlaffaye/ftp | Package ftp implements a FTP client as described in RFC 959. |
| github.com/deuill/sleepy/core/server | Package server contains the core server functionality for Sleepy, including the RPC service, the embedded HTTP server for files uploaded via Sleepy, and an FTP server, containing a subset of functionality required for uploading files to Sleepy in an efficient manner.|
|github.com/smira/aptly/http| Package http provides all HTTP (and FTP)-related operations|
| github.com/mingzhi/hgt/genome/report | This package is to retreive prokaryotes information from the folder of GENOME_REPORTS in NCBI ftp.|
| github.com/yob/graval|An experimental FTP server framework.|
| github.com/smira/go-ftp-protocol/protocol | Package protocol implements ftp:/​/​ scheme plugin for http.Transport|
| github.com/remogatto/ftpget | Fetch files from FTP |
| bitbucket.org/zombiezen/ftp | Package ftp provides a minimal FTP client as defined in RFC 959. |
| github.com/goftp/ftp | Package ftp implements a FTP client as described in RFC 959. |
| github.com/felixge/go-ardrone/net/ftp| Package ftp provides ftp access to the ardrone. |
| github.com/​dabamos/​openadms/​monitoring/​module/​transfer/​ftp| Package ftp provides a module to transfer files via ftp. |
| github.com/​MG-RAST/​Shock/​vendor/​github.com/​jum/​tinyftp | Package tinyftp implements a small subset of FTP, enough to retrieve directory listings and files (including resume support). |
| github.com/mezzato/ftp4go | Package ftp implements an FTP client. |
| github.com/secsy/goftp | Package goftp provides a high-level FTP client for go. |
| github.com/MDrollette/ftp4go | Package ftp implements an FTP client. |
| ------------- | ------------- |
| ------------- | ------------- |
| ------------- | ------------- |

**Comment by ncw** [comment]
Thanks @zeshanb :-)

**Comment by julianvmodesto** [comment]
+1! 👍

**Comment by zeshanb** [comment]
Most welcome :)

**Comment by Bobses** [comment]
+1
I'd like ftp support for rclone.

**Comment by jhuscott** [comment]
+1

**Comment by vdelacerda** [comment]
Great app and FTP support would be very useful ;)

**Comment by unvency** [comment]
+10

@ncw Hopefully, these are enough supporters? :)

**Comment by ncw** [comment]
Please find a beta of the FTP backend here

https://beta.rclone.org/v1.36-114-gcdacf026/ (uploaded in 15-30 mins)

Please open new issues if you find any.
