### ISSUE TITLE
Tidy stats output format

### ISSUE THREAD

**Issue by habskilla** [ncw/rclone#541]
When filing an issue, please include the following information if
possible as well as a description of the problem.

> What is your rclone version (eg output from `rclone -V`)
1.30
> Which OS you are using and how many bits (eg Windows 7, 64 bit)
Linux cublinux-basement 4.2.0-38-generic #45~14.04.1-Ubuntu SMP Thu Jun 9 09:27:51 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

> Which cloud storage system are you using? (eg Google Drive)
Amazon Cloud Drive
> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone copy --dry-run /mnt/archive/Backups/Basement-Backups acd:/Backups/Basement-Backups >/tmp/transfer 2>&1

Pre v1.30 the output summary was like so:
Transferred:            0 Bytes (   0.00 kByte/s)
v1.30 changed to this:
Transferred:            0Bytes (0Byte/s)

**Comment by ncw** [comment]
It did change, yes, in order to fulfil #428 

Is that a problem for you?

**Comment by habskilla** [comment]
No problem.  But, can you add a space for readability?
0 Bytes (0 Byte/s)

**Comment by ncw** [comment]
OK I'll see what I can do!
