### ISSUE TITLE
-q output is blank

### ISSUE THREAD

**Issue by habskilla** [ncw/rclone#542]
When filing an issue, please include the following information if
possible as well as a description of the problem.

> What is your rclone version (eg output from `rclone -V`)
v1.30
> Which OS you are using and how many bits (eg Windows 7, 64 bit)
Linux cublinux-basement 4.2.0-38-generic #45~14.04.1-Ubuntu SMP Thu Jun 9 09:27:51 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
> Which cloud storage system are you using? (eg Google Drive)
Amazon Cloud Drive
> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone copy -q --dry-run /mnt/archive/Backups/Basement-Backups acd:/Backups/Basement-Backups
> A log from the command with the `-v` flag (eg output from `rclone -v copy /tmp remote:tmp`)

I'm seeing no output if I use -q

**Comment by ncw** [comment]
`-q` only shows errors - if there weren't any it will show nothing at all.

You probably don't want to use `--dry-run` and `-q` as it won't show you the files it was thinking of copying.

What were you expecting to see?

**Comment by habskilla** [comment]
-q used to show this:
habskilla@cublinux-basement:~/scripts$ rclone copy -q --dry-run /mnt/archive/Backups/Fileserver-Backups acd:/Backups/Fileserver-Backups

Transferred:            0 Bytes (   0.00 kByte/s)
Errors:                 0
Checks:                92
Transferred:            0
Elapsed time:        2.6s

I'd grep out the number of files transferred and do a bunch of things if greater than zero.

**Comment by habskilla** [comment]
rclone v1.32:
0 Bytes (0 Bytes/s) 

Thanks!
