### ISSUE TITLE
Not enough members for write

### ISSUE THREAD

**Issue by hajes** [ncw/rclone#543]
Most files were copied (from very same folder) to server but last two or three are in endless loop with funny errors.

Both files have around 4GB. File size limit???

> What is your rclone version (eg output from `rclone -V`)
1.3

> Which OS you are using and how many bits (eg Windows 7, 64 bit)
Mac OS X 10.11.5

> Which cloud storage system are you using? (eg Google Drive)
Backblaze B2

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone copy -vuc

> A log from the command with the `-v` flag (eg output from `rclone -v copy /tmp remote:tmp`)

2016/06/22 05:07:09 pacer: Rate limited, increasing sleep to 2s
2016/06/22 05:07:09 pacer: low level retry 1/1 (error Not enough members for write of 4_z2c4731fb0384db29583e081c_f1163c041caad6176_d20160622_m005633_c001_v0001031_t0018: class org.apache.http.conn.ConnectTimeoutException - Connect to member-04.vault:8180 [member-04.vault/192.168.243.14] failed: connect timed out; class org.apache.http.conn.ConnectTimeoutException - Connect to member-05.vault:8180 [member-05.vault/192.168.243.15] failed: connect timed out (500 internal_error))
2016/06/22 05:07:09 (2016-06-02) storm in Germany by Braunau/MVI_0069.MP4: Received error: Not enough members for write of 4_z2c4731fb0384db29583e081c_f1163c041caad6176_d20160622_m005633_c001_v0001031_t0018: class org.apache.http.conn.ConnectTimeoutException - Connect to member-04.vault:8180 [member-04.vault/192.168.243.14] failed: connect timed out; class org.apache.http.conn.ConnectTimeoutException - Connect to member-05.vault:8180 [member-05.vault/192.168.243.15] failed: connect timed out (500 internal_error) - low level retry 3/10
2016/06/22 05:07:09 (2016-06-02) storm in Germany by Braunau/MVI_0069.MP4: Removing failed copy
2016/06/22 05:07:11 pacer: Reducing sleep to 1.5s
2016/06/22 05:07:11 (2016-06-02) storm in Germany by Braunau/MVI_0069.MP4: Failed to remove failed copy: failed to delete file: File not present: _ARCHIV/Video Projects/(2016-06-02) storm in Germany by Braunau/MVI_0069.MP4 (400 no_such_file)
2016/06/22 05:07:59

**Comment by ncw** [comment]
Strange! Looks like some sort of B2 internal error. 

Did the files copy eventually? 

You could try setting `--b2-cutoff 1G` so it tries to upload them in chunks.

**Comment by hajes** [comment]
`--b2-upload-cutoff` works. All files uploaded

**Comment by ncw** [comment]
I just read the [integration checklist again](https://www.backblaze.com/b2/docs/integration_checklist.html) backblaze recommend

> When uploading files larger than 200MB, use the large files support to break up the files into parts and upload the parts in parallel.

So I'll change the default for the `--b2-upload-cutoff` to 200MB in the next release.

**Comment by ncw** [comment]
I've changed the default now.

You can try the latest version with lots of b2 changes here.

http://pub.rclone.org/v1.30-26-gcc62871%CE%B2/
