### ISSUE TITLE
Amazon cloud drive: Recommended max number of files per folder?

### ISSUE THREAD

**Issue by arogan** [ncw/rclone#544]
This is more of a question than an issue.  I noticed while using amazon cloud drive performance drops way off as the number of files increase for a given folder.  If i'm uploading a file to an existing acd folder with say 50,000 files it uploads at a MUCH slower rate.  If I upload the same file to a blank remote folder on acd I get full speed again.  So my question is what is the recommended maximum number of files should I have in an acd folder before transfer speeds really begin to suffer?

**Comment by ncw** [comment]
It would be interesting to dig down into exactly why you are seeing what you are seeing and whether it is an rclone problem or an ACD problem.

It certainly takes longer to list big folders and rclone has to list the folder before transferring.

I could believe that the uploading a file into a directory with 50k files might take an extra few seconds as amazon has to check the directory for duplicates before uploading the file.  Is that what you are seeing?

It might be this change on rclone's side which is making the difference df1092ef33416e562ea22050640c94f38fa2df0f which checks for duplicates before uploading.

How long is the pause before each upload with a big directory do you think (assuming you are seeing that).

I would guess you are uploading lots of small files - is that the case?

**Comment by arogan** [comment]
I'll start with a little bit of background.  I'm currently writing a little .net c# cli program that wraps rclone and only uses rclone as an upload/download engine and only really a single file at a time.  My program takes a file of any size, breaks it into 100MB chunks, calls those chunks with a guid and a sequence number (GUID_NNNN), encrypts the chunks client side, and tracks the mapping of the real path\filename to guid in a local sqlite database.  Then I use rclone to upload the chunks to a remote acd path something like remote:rcCloudStreamer.  Since I basically flatten the structure on the remote side and every file is guaranteed unique (guids) I don't ever change the remote path.  Everything just gets dumped into a single remote folder.  I'm up to 48,000 of these chunks all in a single amazon cloud drive folder.  I blank folder takes maybe 5 min to upload a 1.5GB file (broken down to 100mb chunks) but now it takes 2 hrs in my populated folder.  I was getting ready to release my application as open source to git hub until I noticed this issue.  I'll try generating some detailed logs if that would help.  Here are some regular logs that I have right now.  FYI, I'm on gigapower so I have around 900/900 so It's not my internet.

Here are some logs of a few of the 100MB chunks getting uploaded using rclone (windows 10 x64)

Good (empty remote folder):
06/22/2016 11:19:16.9993 PM  2016/06/22 23:19:16 Local file system at \\?\d:\chunks limited to 1 objects: Building file list
06/22/2016 11:19:17.0028 PM  2016/06/22 23:19:16 Amazon cloud drive root 'rcCloudStreamerTest': Building file list
06/22/2016 11:19:17.6079 PM  2016/06/22 23:19:17 Amazon cloud drive root 'rcCloudStreamerTest': Waiting for checks to finish
06/22/2016 11:19:17.6124 PM  2016/06/22 23:19:17 Amazon cloud drive root 'rcCloudStreamerTest': Waiting for transfers to finish
06/22/2016 11:19:42.8267 PM  2016/06/22 23:19:42 
06/22/2016 11:19:42.8287 PM  Transferred:     100.000MBytes (3.748MByte/s)
06/22/2016 11:19:42.8296 PM  
06/22/2016 11:19:42.8316 PM  Errors:                 0
06/22/2016 11:19:42.8345 PM  Checks:                 0
06/22/2016 11:19:42.8365 PM  Transferred:            1
06/22/2016 11:19:42.8374 PM  Elapsed time:       26.6s
06/22/2016 11:19:42.8394 PM  
06/22/2016 11:19:42.8404 PM  exit code: 0
06/22/2016 11:19:43.7878 PM  Encrypting data
06/22/2016 11:19:43.8118 PM  2016/06/22 23:19:43 Local file system at \\?\d:\chunks limited to 1 objects: Building file list
06/22/2016 11:19:43.8163 PM  2016/06/22 23:19:43 Amazon cloud drive root 'rcCloudStreamerTest': Building file list
06/22/2016 11:19:44.4519 PM  2016/06/22 23:19:44 Amazon cloud drive root 'rcCloudStreamerTest': Waiting for checks to finish
06/22/2016 11:19:44.4559 PM  2016/06/22 23:19:44 Amazon cloud drive root 'rcCloudStreamerTest': Waiting for transfers to finish
06/22/2016 11:20:10.3220 PM  2016/06/22 23:20:10 
06/22/2016 11:20:10.3240 PM  Transferred:     100.000MBytes (3.644MByte/s)
06/22/2016 11:20:10.3280 PM  Errors:                 0
06/22/2016 11:20:10.3295 PM  Checks:                 0
06/22/2016 11:20:10.3315 PM  Transferred:            1
06/22/2016 11:20:10.3240 PM  
06/22/2016 11:20:10.3330 PM  Elapsed time:       27.4s
06/22/2016 11:20:10.3355 PM  
06/22/2016 11:20:10.3365 PM  exit code: 0
06/22/2016 11:20:11.2117 PM  2016/06/22 23:20:11 Local file system at \\?\d:\chunks limited to 1 objects: Building file list
06/22/2016 11:20:11.2152 PM  2016/06/22 23:20:11 Amazon cloud drive root 'rcCloudStreamerTest': Building file list
06/22/2016 11:20:11.9037 PM  2016/06/22 23:20:11 Amazon cloud drive root 'rcCloudStreamerTest': Waiting for checks to finish
06/22/2016 11:20:11.9072 PM  2016/06/22 23:20:11 Amazon cloud drive root 'rcCloudStreamerTest': Waiting for transfers to finish
06/22/2016 11:20:40.2271 PM  2016/06/22 23:20:40 
06/22/2016 11:20:40.2291 PM  
06/22/2016 11:20:40.2291 PM  Transferred:     100.000MBytes (3.350MByte/s)
06/22/2016 11:20:40.2336 PM  Errors:                 0
06/22/2016 11:20:40.2351 PM  Checks:                 0
06/22/2016 11:20:40.2366 PM  Transferred:            1
06/22/2016 11:20:40.2376 PM  Elapsed time:       29.8s
06/22/2016 11:20:40.2391 PM  
06/22/2016 11:20:40.2401 PM  exit code: 0

bad (48,000 files in remote folder):
06/22/2016 11:00:40.1143 PM  2016/06/22 23:00:40 Local file system at \\?\d:\chunks limited to 1 objects: Building file list
06/22/2016 11:00:40.1143 PM  2016/06/22 23:00:40 Amazon cloud drive root 'rcCloudStreamer': Building file list
06/22/2016 11:01:02.6888 PM  2016/06/22 23:01:02 Amazon cloud drive root 'rcCloudStreamer': Waiting for checks to finish
06/22/2016 11:01:02.6888 PM  2016/06/22 23:01:02 Amazon cloud drive root 'rcCloudStreamer': Waiting for transfers to finish
06/22/2016 11:01:05.1081 PM  2016/06/22 23:01:05 
06/22/2016 11:01:05.1081 PM  Transferred:       3.094MBytes (26.212kByte/s)
06/22/2016 11:01:05.1081 PM  Errors:                 0
06/22/2016 11:01:05.1081 PM  Checks:                 0
06/22/2016 11:01:05.1081 PM  Transferred:            0
06/22/2016 11:01:05.1081 PM  Elapsed time:      2m0.8s
06/22/2016 11:01:05.1086 PM  Transferring:
06/22/2016 11:01:05.1086 PM   *         4572fe4d83404d868870797fffcfe69d_0029:  3% done. avg: 1734.7, cur: 1114.2 kByte/s. ETA: 1m29s
06/22/2016 11:01:40.0515 PM  2016/06/22 23:01:40 
06/22/2016 11:01:40.0520 PM  Transferred:     100.000MBytes (657.240kByte/s)
06/22/2016 11:01:40.0520 PM  Errors:                 0
06/22/2016 11:01:40.0520 PM  Checks:                 0
06/22/2016 11:01:40.0520 PM  Transferred:            1
06/22/2016 11:01:40.0520 PM  Elapsed time:     2m35.8s
06/22/2016 11:01:40.0540 PM  
06/22/2016 11:01:40.0545 PM  
06/22/2016 11:01:40.0610 PM  exit code: 0
06/22/2016 11:01:40.1145 PM  2016/06/22 23:01:40 
06/22/2016 11:01:40.1145 PM  Transferred:            0Bytes (0Byte/s)
06/22/2016 11:01:40.1145 PM  Errors:                 0
06/22/2016 11:01:40.1145 PM  Checks:                 0
06/22/2016 11:01:40.1145 PM  Transferred:            0
06/22/2016 11:01:40.1150 PM  Elapsed time:      1m0.8s
06/22/2016 11:01:40.1150 PM  
06/22/2016 11:01:40.9746 PM  2016/06/22 23:01:40 Local file system at \\?\d:\chunks limited to 1 objects: Building file list
06/22/2016 11:01:40.9746 PM  2016/06/22 23:01:40 Amazon cloud drive root 'rcCloudStreamer': Building file list
06/22/2016 11:02:39.5275 PM  2016/06/22 23:02:39 Amazon cloud drive root 'rcCloudStreamer': Waiting for checks to finish
06/22/2016 11:02:39.5280 PM  2016/06/22 23:02:39 Amazon cloud drive root 'rcCloudStreamer': Waiting for transfers to finish
06/22/2016 11:02:40.1146 PM  2016/06/22 23:02:40 
06/22/2016 11:02:40.1151 PM  Transferred:         128kBytes (1.059kByte/s)
06/22/2016 11:02:40.1151 PM  Errors:                 0
06/22/2016 11:02:40.1151 PM  Checks:                 0
06/22/2016 11:02:40.1151 PM  Transferred:            0
06/22/2016 11:02:40.1151 PM  Elapsed time:      2m0.8s
06/22/2016 11:02:40.1151 PM  Transferring:
06/22/2016 11:02:40.1151 PM   *         e80f3558361740e2bcc774b1826b6d8c_0000:  0% done. avg:  885.7, cur:    0.0 kByte/s. ETA: -
06/22/2016 11:02:40.1156 PM  
06/22/2016 11:02:40.9757 PM  2016/06/22 23:02:40 
06/22/2016 11:02:40.9757 PM  Transferred:            0Bytes (0Byte/s)
06/22/2016 11:02:40.9757 PM  Errors:                 0
06/22/2016 11:02:40.9757 PM  Checks:                 0
06/22/2016 11:02:40.9757 PM  Transferred:            0
06/22/2016 11:02:40.9757 PM  Elapsed time:      1m0.8s
06/22/2016 11:02:40.9762 PM  
06/22/2016 11:03:01.4716 PM  2016/06/22 23:03:01 
06/22/2016 11:03:01.4716 PM  Transferred:     100.000MBytes (720.017kByte/s)
06/22/2016 11:03:01.4716 PM  Errors:                 0
06/22/2016 11:03:01.4716 PM  Checks:                 0
06/22/2016 11:03:01.4716 PM  Transferred:            1
06/22/2016 11:03:01.4716 PM  Elapsed time:     2m22.2s
06/22/2016 11:03:01.4735 PM  
06/22/2016 11:03:01.4735 PM  
06/22/2016 11:03:01.4805 PM  exit code: 0
06/22/2016 11:03:02.3220 PM  2016/06/22 23:03:02 Local file system at \\?\d:\chunks limited to 1 objects: Building file list
06/22/2016 11:03:02.3220 PM  2016/06/22 23:03:02 Amazon cloud drive root 'rcCloudStreamer': Building file list
06/22/2016 11:03:40.9760 PM  2016/06/22 23:03:40 
06/22/2016 11:03:40.9760 PM  Transferred:            0Bytes (0Byte/s)
06/22/2016 11:03:40.9760 PM  Errors:                 0
06/22/2016 11:03:40.9760 PM  Checks:                 0
06/22/2016 11:03:40.9760 PM  Transferred:            0
06/22/2016 11:03:40.9765 PM  Elapsed time:      2m0.8s
06/22/2016 11:03:40.9765 PM  
06/22/2016 11:03:49.2079 PM  2016/06/22 23:03:49 Amazon cloud drive root 'rcCloudStreamer': Waiting for checks to finish
06/22/2016 11:03:49.2084 PM  2016/06/22 23:03:49 Amazon cloud drive root 'rcCloudStreamer': Waiting for transfers to finish
06/22/2016 11:04:02.3233 PM  2016/06/22 23:04:02 
06/22/2016 11:04:02.3233 PM  Transferred:            0Bytes (0Byte/s)
06/22/2016 11:04:02.3233 PM  Errors:                 0
06/22/2016 11:04:02.3233 PM  Checks:                 0
06/22/2016 11:04:02.3238 PM  Transferred:            0
06/22/2016 11:04:02.3238 PM  Elapsed time:      1m0.8s
06/22/2016 11:04:02.3238 PM  
06/22/2016 11:04:09.8819 PM  2016/06/22 23:04:09 
06/22/2016 11:04:09.8824 PM  Transferred:     100.000MBytes (683.622kByte/s)
06/22/2016 11:04:09.8824 PM  Errors:                 0
06/22/2016 11:04:09.8824 PM  Checks:                 0
06/22/2016 11:04:09.8824 PM  Transferred:            1
06/22/2016 11:04:09.8824 PM  Elapsed time:     2m29.7s
06/22/2016 11:04:09.8849 PM  
06/22/2016 11:04:09.8849 PM  
06/22/2016 11:04:09.8969 PM  exit code: 0
06/22/2016 11:04:10.7685 PM  2016/06/22 23:04:10 Local file system at \\?\d:\chunks limited to 1 objects: Building file list
06/22/2016 11:04:10.7685 PM  2016/06/22 23:04:10 Amazon cloud drive root 'rcCloudStreamer': Building file list
06/22/2016 11:05:02.1093 PM  2016/06/22 23:05:02 Amazon cloud drive root 'rcCloudStreamer': Waiting for checks to finish
06/22/2016 11:05:02.1098 PM  2016/06/22 23:05:02 Amazon cloud drive root 'rcCloudStreamer': Waiting for transfers to finish
06/22/2016 11:05:02.3228 PM  2016/06/22 23:05:02 
06/22/2016 11:05:02.3233 PM  Transferred:            0Bytes (0Byte/s)
06/22/2016 11:05:02.3233 PM  Errors:                 0
06/22/2016 11:05:02.3233 PM  Checks:                 0
06/22/2016 11:05:02.3233 PM  Transferred:            0
06/22/2016 11:05:02.3233 PM  Elapsed time:      2m0.8s
06/22/2016 11:05:02.3233 PM  Transferring:
06/22/2016 11:05:02.3233 PM   *         e80f3558361740e2bcc774b1826b6d8c_0001:  0% done. avg:    0.0, cur:    0.0 kByte/s. ETA: -
06/22/2016 11:05:02.3233 PM  
06/22/2016 11:05:10.7690 PM  2016/06/22 23:05:10 
06/22/2016 11:05:10.7690 PM  Transferred:            0Bytes (0Byte/s)
06/22/2016 11:05:10.7690 PM  Errors:                 0
06/22/2016 11:05:10.7690 PM  Checks:                 0
06/22/2016 11:05:10.7690 PM  Transferred:            0
06/22/2016 11:05:10.7695 PM  Elapsed time:      1m0.8s
06/22/2016 11:05:10.7695 PM  
06/22/2016 11:05:30.4678 PM  2016/06/22 23:05:30 
06/22/2016 11:05:30.4678 PM  Transferred:     100.000MBytes (687.447kByte/s)
06/22/2016 11:05:30.4683 PM  Errors:                 0
06/22/2016 11:05:30.4683 PM  Checks:                 0
06/22/2016 11:05:30.4683 PM  Transferred:            1
06/22/2016 11:05:30.4683 PM  Elapsed time:     2m28.9s
06/22/2016 11:05:30.4703 PM  
06/22/2016 11:05:30.4708 PM  
06/22/2016 11:05:30.4768 PM  exit code: 0
06/22/2016 11:05:31.4884 PM  2016/06/22 23:05:31 Local file system at \\?\d:\chunks limited to 1 objects: Building file list
06/22/2016 11:05:31.4884 PM  2016/06/22 23:05:31 Amazon cloud drive root 'rcCloudStreamer': Building file list
06/22/2016 11:06:10.7691 PM  2016/06/22 23:06:10 
06/22/2016 11:06:10.7691 PM  Transferred:            0Bytes (0Byte/s)
06/22/2016 11:06:10.7691 PM  Errors:                 0
06/22/2016 11:06:10.7691 PM  Checks:                 0
06/22/2016 11:06:10.7691 PM  Transferred:            0
06/22/2016 11:06:10.7691 PM  Elapsed time:      2m0.8s
06/22/2016 11:06:10.7696 PM  
06/22/2016 11:06:18.3504 PM  2016/06/22 23:06:18 Amazon cloud drive root 'rcCloudStreamer': Waiting for checks to finish
06/22/2016 11:06:18.3509 PM  2016/06/22 23:06:18 Amazon cloud drive root 'rcCloudStreamer': Waiting for transfers to finish
06/22/2016 11:06:31.4892 PM  2016/06/22 23:06:31 
06/22/2016 11:06:31.4892 PM  Transferred:            0Bytes (0Byte/s)
06/22/2016 11:06:31.4892 PM  Errors:                 0
06/22/2016 11:06:31.4892 PM  Checks:                 0
06/22/2016 11:06:31.4892 PM  Transferred:            0
06/22/2016 11:06:31.4897 PM  Elapsed time:      1m0.9s
06/22/2016 11:06:31.4897 PM  
06/22/2016 11:06:41.6102 PM  2016/06/22 23:06:41 
06/22/2016 11:06:41.6107 PM  Transferred:     100.000MBytes (675.090kByte/s)
06/22/2016 11:06:41.6107 PM  Errors:                 0
06/22/2016 11:06:41.6107 PM  Checks:                 0
06/22/2016 11:06:41.6107 PM  Transferred:            1
06/22/2016 11:06:41.6107 PM  Elapsed time:     2m31.6s
06/22/2016 11:06:41.6137 PM  
06/22/2016 11:06:41.6137 PM  
06/22/2016 11:06:41.6212 PM  exit code: 0
06/22/2016 11:06:41.6217 PM  Attempt: 1; Running: c:\apps\rclone\rclone.exe copy "d:\chunks\4572fe4d83404d868870797fffcfe69d_0032" "remote:rcCloudStreamer"
06/22/2016 11:06:42.5633 PM  2016/06/22 23:06:42 Local file system at \\?\d:\chunks limited to 1 objects: Building file list
06/22/2016 11:06:42.5663 PM  2016/06/22 23:06:42 Amazon cloud drive root 'rcCloudStreamer': Building file list
06/22/2016 11:07:31.4894 PM  2016/06/22 23:07:31 
06/22/2016 11:07:31.4894 PM  Transferred:            0Bytes (0Byte/s)
06/22/2016 11:07:31.4894 PM  Errors:                 0
06/22/2016 11:07:31.4894 PM  Checks:                 0
06/22/2016 11:07:31.4894 PM  Transferred:            0
06/22/2016 11:07:31.4894 PM  Elapsed time:      2m0.9s
06/22/2016 11:07:31.4899 PM  
06/22/2016 11:07:42.5639 PM  2016/06/22 23:07:42 
06/22/2016 11:07:42.5639 PM  Transferred:            0Bytes (0Byte/s)
06/22/2016 11:07:42.5639 PM  Errors:                 0
06/22/2016 11:07:42.5639 PM  Checks:                 0
06/22/2016 11:07:42.5639 PM  Transferred:            0
06/22/2016 11:07:42.5644 PM  Elapsed time:      1m0.9s
06/22/2016 11:07:42.5644 PM  
06/22/2016 11:08:31.4889 PM  2016/06/22 23:08:31 
06/22/2016 11:08:31.4889 PM  Transferred:            0Bytes (0Byte/s)
06/22/2016 11:08:31.4889 PM  Errors:                 0
06/22/2016 11:08:31.4889 PM  Checks:                 0
06/22/2016 11:08:31.4889 PM  Transferred:            0
06/22/2016 11:08:31.4889 PM  Elapsed time:      3m0.9s
06/22/2016 11:08:31.4894 PM  
06/22/2016 11:08:42.5637 PM  2016/06/22 23:08:42 
06/22/2016 11:08:42.5637 PM  Transferred:            0Bytes (0Byte/s)
06/22/2016 11:08:42.5637 PM  Errors:                 0
06/22/2016 11:08:42.5637 PM  Checks:                 0
06/22/2016 11:08:42.5637 PM  Transferred:            0
06/22/2016 11:08:42.5637 PM  Elapsed time:      2m0.9s
06/22/2016 11:08:42.5637 PM  
06/22/2016 11:08:57.4901 PM  2016/06/22 23:08:57 Amazon cloud drive root 'rcCloudStreamer': Waiting for checks to finish
06/22/2016 11:08:57.4910 PM  2016/06/22 23:08:57 Amazon cloud drive root 'rcCloudStreamer': Waiting for transfers to finish
06/22/2016 11:09:18.9252 PM  2016/06/22 23:09:18 
06/22/2016 11:09:18.9262 PM  Transferred:     100.000MBytes (448.301kByte/s)
06/22/2016 11:09:18.9262 PM  Errors:                 0
06/22/2016 11:09:18.9262 PM  Checks:                 0
06/22/2016 11:09:18.9262 PM  Transferred:            1
06/22/2016 11:09:18.9262 PM  Elapsed time:     3m48.4s
06/22/2016 11:09:18.9282 PM  
06/22/2016 11:09:18.9282 PM  
06/22/2016 11:09:18.9350 PM  exit code: 0

example command line call I'm using:
c:\apps\rclone\rclone.exe copy "d:\chunks\4572fe4d83404d868870797fffcfe69d_0032" "remote:rcCloudStreamer"

I can generate verbose logs if that would help.  I know I'm  probably quite the fringe case but I'm thinking about working around this issue by creating sequential remote sub folders maybe every 10,000 files or so or whatever the threshold should be.  But if this is something that can be fixed in rclone (mabye even a blind upload switch?) that would be even better.

**Comment by ncw** [comment]
I did a test uploading 50,000 files (using the default transfers 4).  That took 3h47m31 so on average 3.6 files per second.

The first 1000 files were uploaded at 3.73 files / second, the last 1000 at 3.66 so no real difference there.

However I see what is the problem with your log...

rclone takes 22 seconds listing the remote directory before transferring a 100 MB chunk when there are 50k files in the remote directory.

This is as noted in #8 

Now that I've  put df1092e in, I could stop copy traversing the remote file system at all.  This would have several advantages in your case.  I'll put a `--no-traverse` flag in as an experiment and I'll post a beta here.

**Comment by arogan** [comment]
Yes, I'm use case is exactly #8, copy a one file at a time with rclone into an acd folder with many files.  Sounds like --no-traverse is exactly what I need.  Thanks.

**Comment by ncw** [comment]
Here is a beta with the `--no-traverse` flag - let me know what you thin!

http://pub.rclone.org/v1.30-11-g22ab4e4%CE%B2/

**Comment by arogan** [comment]
Just tested it, and it's working great.  Thanks!

**Comment by ncw** [comment]
Excellent - thanks
