### ISSUE TITLE
Why `rclone copy` checks file list from S3 bucket?

### ISSUE THREAD

**Issue by ei-grad** [ncw/rclone#546]
Probably, one of the common use cases for rclone with S3 is to upload new files from local folder, which could be done via `cron.daily` like `rclone copy --max-age=25h <local> <s3:bucket>`.

The problem with this case is that `rclone copy` first checks the bucket file list, which could be very expensive operation (more than 1 hour for my case), while it could just start checking and uploading files from local folder. What is wrong?

**Comment by ncw** [comment]
Yes you are right.  This is the same issue as #8 - I'm in the process of fixing this and will post a beta when it is ready.

**Comment by ncw** [comment]
Here is a beta with a `--no-traverse` flag which should help.

Let me know how you get on.

http://pub.rclone.org/v1.30-11-g22ab4e4%CE%B2/

**Comment by danzig666** [comment]
That's great!
Now my daily backup job completes in 10 minutes. Was over 90 minutes before.

**Comment by lorenzoferrarajr** [comment]
Could this work also for ACD?

**Comment by ncw** [comment]
@lorenzoferrarajr It will work for all the remotes, yes.

**Comment by lorenzoferrarajr** [comment]
Thank you @ncw, the `--no-traverse` option works great also on Amazon Cloud Drive.
