### ISSUE TITLE
Dropbox: datastore API is deprecated - find alternative

### ISSUE THREAD

**Issue by ncw** [ncw/rclone#55]
[Datastore API is being deprecated](https://blogs.dropbox.com/developers/2015/04/deprecating-the-sync-and-datastore-apis/).

Support ends October 2015, endopoints will be removed in April 2016.

rclone uses the datastore API for storing metadata about the files (md5sum and modification date).

Need an alternative...

Ideally store the metadata on the objects, but this doesn't appear to be possible with the new API.

**Comment by austinginder** [comment]
Maybe Dropbox can help.

> The Datastore API is somewhat unique in that it, unlike the Core API, deals with non-file data, so we’re working directly with individual developers to help them migrate to an alternative. Existing apps built using the Datastore API will continue to work in the meantime.

Looking through their comments, it looks like they direct developers to contact them directly: https://www.dropbox.com/developers/contact.

**Comment by ncw** [comment]
@austinginder I think I might take a different approach and stop storing metadata at all for dropbox.  This would downgrade the syncs somewhat so the MD5SUMs wouldn't be checked and every sync would be a `--size-only` sync.  However it would have the advantage of making dropbox a lot more reliable and faster.

I'll try contacting them anyway and see what happens!

**Comment by austinginder** [comment]
That would be great if possible. I currently only check the size when doing a sync to Dropbox.

**Comment by ncw** [comment]
I had a chat with Dropbox support and they come up with a couple of new ideas - [Parse](https://www.parse.com/) or [Firebase](https://www.firebase.com/)

I think the options are
  1. Store the data in a file manually (eg in one big json file, or lots of little ones)
  2. Downgrade dropbox to a size only backend
  3. Use a 3rd party database to store the metadata eg [Parse](https://www.parse.com/) or [Firebase](https://www.firebase.com/)

All of these options could potentially work with other cloud providers (eg Microsoft) which don't provide MD5SUMs or Dates.

I think Option 1) would work, but I know from bitter experience that keeping that file up to date will be very complicated and it will be prone to corruption. Using one metadata file per file would work better, but that has the disadvantage that they would all appear in the dropbox interface.

Option 2) fits in well with rclone's philosophy of small and lightweight.  It would be fairly straight forward to implement and lower the barrier to entry for new cloud storage providers.

Option 3) would work too, but I'm not a big fan of using two different providers to solve the metadata problem.

My preferred choice would be option 2)

**Comment by austinginder** [comment]
Likewise option 2 would be great. I'm using rclone to incrementally backup to my Dropbox Business account. This works out amazingly as my Dropbox account as unlimited revisions. Thanks for the quick response and for doing the research.

**Comment by darren12345** [comment]
Would option 1 work if you saved the json files locally but set rclone to ignore them for syncing (as .dropbox files are now - or is that a function of the API rather than rclone)?

**Comment by ncw** [comment]
@darren12345 yes that would work but it wouldn't be ideal as there is stuff that can get out of sync (the local .json file and the remote cloud storage)

**Comment by darren12345** [comment]
But my point was that the json files would only be saved locally and not synced at all - referring to your point:
>Using one metadata file per file would work better, but that has the disadvantage that they would all appear in the dropbox interface.

The json file can store the same data the datastore currently does (md5 hash etc) to be used for comparison if required. One obvious downside is that the json file(s) would have to be generated on each local instance before syncing could commence.

Or have you considered something like SQLite to store metadata?

**Comment by darren12345** [comment]
Hi Nick. So does this mean that rclone only compares sizes by default when syncing with Dropbox now or is it also checking mtime (not sure if that's possible with the Dropbox API)? Thanks for your work on this.

**Comment by ncw** [comment]
Yes it only compares sizes (not mtime) which is less than perfect, but for nearly all use cases it is good enough.  I hope that doesn't inconvenience you too much.

I may at some point add a DB or json file or something like that, but I decided not to for the moment.

**Comment by darren12345** [comment]
No, that's peachy. Like you say, it will be good enough in 99% of cases I should think.
