### ISSUE TITLE
[Dropbox] HTTP error 461 - don't retry

### ISSUE THREAD

**Issue by ywLBhGk2noZLbY7** [ncw/rclone#551]
Hi, I'm running RClone version 1.3 and I'm trying to migrate Dropbox files to Google Drive for a friend, however, it seems to be erroring out on one of her files with HTTP error code 461. From what I can tell from Google (Can't find official documentation), it seems to be related with a DMCA strike:-

https://forum.choiceofgames.com/t/dropbox-461-restricted-content/7636
https://forum.synology.com/enu/viewtopic.php?t=109199#p423968

Etc...

>2016/06/29 07:50:32 ${FILE}: Failed to copy: failed to open source object: unexpected HTTP status code 461

Currently rclone attempts to copy it `--retries` times before erroring out. I think if you encounter a 461 error, there's no point retrying it (DMCA strike won't be removed between attempts) and the process should continue ignoring that file, outputting an error to stderr/at the end of the programs run.

**Comment by ncw** [comment]
Thanks for reporting that.

Currently rclone doesn't have a mechanism for an error so fatal it shouldn't retry so I'd need to build that first!

**Comment by ncw** [comment]
Here is a beta with a fix for that: http://pub.rclone.org/v1.30-26-gcc62871%CE%B2/

Let me know if it works!
