### ISSUE TITLE
B2: Bug or infrastructure issues still?

### ISSUE THREAD

**Issue by mdeboer** [ncw/rclone#555]
I had a lot of trouble uploading to B2 so I switched back to AWS (which works super smooth and fast). Today I decided to try again but it started out right away with 503 errors. This makes me wonder if it's their infrastructure (as other clients face often face the same issue) or that it's a bug in handling the upload URL's. It seems the same node is hit, even on the second attempt and with the error when it's down. It seems to me that on a 503 you should try another node? It's not worth it polling the same node again until it comes back up. But is this an implementation issue or general infrastructure problem?

> What is your rclone version (eg output from `rclone -V`)
rclone v1.3.0

> Which OS you are using and how many bits (eg Windows 7, 64 bit)
CentOS 7

> Which cloud storage system are you using? (eg Google Drive)
Backblaze

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone move /a backblaze:mybucket/folder

> A log from the command with the `-v` flag (eg output from `rclone -v copy /tmp remote:tmp`)
2016/07/02 13:58:54 ###: Received error: c001_v0001029_t0037 is too busy (503 service_unavailable) - low level retry 1/10
2016/07/02 13:59:00 ###: Received error: c001_v0001029_t0037 is too busy (503 service_unavailable) - low level retry 1/10
2016/07/02 13:59:01 ###: Received error: c001_v0001029_t0037 is too busy (503 service_unavailable) - low level retry 1/10
2016/07/02 13:59:02 ###: Received error: c001_v0001029_t0037 is too busy (503 service_unavailable) - low level retry 2/10
2016/07/02 13:59:03 ###: Received error: c001_v0001029_t0037 is too busy (503 service_unavailable) - low level retry 1/10
2016/07/02 13:59:04 ###: Received error: c001_v0001029_t0037 is too busy (503 service_unavailable) - low level retry 1/10

(### are substituted filenames and not the real file names)

**Comment by zeshanb** [comment]
How to manage the 503 status after line 187 in this file rclone
<https://github.com/ncw/rclone/tree/3f7b2c1adec9c5292d212e7cdf912216041b72dd>
/b2
<https://github.com/ncw/rclone/tree/3f7b2c1adec9c5292d212e7cdf912216041b72dd/b2>/upload.go
and by using the existing demo java like code displayed in
https://www.backblaze.com/b2/docs/uploading.html *?*

 ..if (status == 503 /*Service Unavailable*/) {..

go lang is way out of scope for me, sorry.

**Comment by atweiden** [comment]
I had the same experience with B2. At the end of syncing, rclone appears to check if there are any errors, and if so it retries the entire sync. So it ends up working, but it can take a while.

**Comment by ncw** [comment]
I have been working on bringing rclone exactly into compliance for b2 as part of #420 . I'm almost there - I'll post a beta for you to try here to see if it makes any improvement.

**Comment by ncw** [comment]
...but yes you are right, the current 503 error handling is wrong and I've fixed that now.

**Comment by ncw** [comment]
Here is a beta with the corrected error handling code: http://pub.rclone.org/v1.30-21-g018fe80%CE%B2/

It has quite a lot of other b2 features also (see #420 for the list) so testing apreciated!

**Comment by mdeboer** [comment]
@ncw will do! Keep up the good work 👍

**Comment by ncw** [comment]
I've pushed out the v1.31 release with this fix in.  Let me know if you see any problems.

Thanks

Nick
