### ISSUE TITLE
Suggest: List of the rclone volumes created

### ISSUE THREAD

**Issue by gwarah** [ncw/rclone#558]
> What is your rclone version (eg output from `rclone -V`): 1.30

> Which OS you are using and how many bits (eg Windows 7, 64 bit): Ubuntu 16.04

> Which cloud storage system are you using? (eg Google Drive): google drive and dropbox

> The command suggested (eg `rclone get-volumes`):

> Output expected:

In my case would be like this bellow:

```
Name                 Type
====                 ====
dropbox01            dropbox
grive-lhmp1967       drive

```
> Why?

It would be useful to scripts multi cloud provider:

```
#/bin/bash
for for volume in `rclone --list-volumes | grep.... `; do
      rclone sync $volume....
done
```

I believe there's data files I could get this information but I prefer get it by a command. Hope this issue could improve this project.

**Comment by ncw** [comment]
A new verb for rclone would be the way to go for this, eg `rclone list-remotes` maybe.

Note that rclone doesn't currently store the bit after the `:` in the config file which might make your plan harder.

This would be relatively easy to implement I think - nice idea!

**Comment by ncw** [comment]
Even easier now we have cobra

**Comment by ncw** [comment]
I've done this now - find it in this beta http://beta.rclone.org/v1.33-63-gace1e21/ in about 15 minutes!

**Comment by gwarah** [comment]
Oh, great ncw! I'm gonna update and test it ASAP.

**Comment by DurvalMenezes** [comment]
Hello, 

Just downloaded and tested it, seems to be working great here. Just two observations:

1) The rclone.1 manpage doesn't seem to list the listremotes command yet; 
2) The output includes just the remote names; perhaps add a "-l" or similar option so more data (for example, cloud type) is also listed?

Cheers, 
 -- 
   Durval.

**Comment by ncw** [comment]
Thanks for testing. 

The man page will get updated at the next release. I normally do that as part of the release but maybe I should do that for the betas too. 

 I already did -l give it a go! 

    rclone listremotes -h

Should show you the help

**Comment by DurvalMenezes** [comment]
Hi Nick, 

> rclone listremotes -h
> Should show you the help

Just checked, and indeed it does:

> rclone listremotes lists all the available remotes from the config file.
> 
> When uses with the -l flag it lists the types too.
> 
> Usage:
>   rclone listremotes [flags]
> 
> Flags:
>   -l, --long   Show the type as well as names.

Testing -l:

> ACD:    amazon cloud drive
> ACDE: crypt

So all is good!

Cheers, 
-- 
   Durval.
