### ISSUE TITLE
Stop removing a failed copy

### ISSUE THREAD

**Issue by ncw** [ncw/rclone#559]
Stop removing the failed copy

For most remotes a failed copy means that the upload wasn't successful and the file won't be there anyway so we are wasting resources trying to delete it after failing to upload it.

In practice it is more likely that the file was signaled in error but is actually OK (eg ACD proxy problems)

Our aim is to never leave a file which is corrupt.

The scenarios where we should remove a failed copy
- The local fs - failed files will leave files that are half copied.
  - could fix this in the local fs though
- in the unlikely event that the MD5SUM/SHA1SUM didn't match after upload
- we should delete the corrupted file
- files which are uploaded in chunks (eg swift) might be readable before the last chunk has been uploaded - should probably fix this in the remote

**Comment by romusz** [comment]
was about to file an new issue when i came across this one - it confirms my observations.
i'm getting significant number of:
`Received error: Put https://content-na.drive.amazonaws.com/cdproxy/nodes/0x4Po_W4Q42SeObg0iH6XQ/content: net/http: timeout awaiting response headers - low level retry 4/10`

found in the source code that in such cases the file is deleted from destination. if, instead the code compared the checksum of destination file, or simply not delete the file but returned a transfer error (subject to `--retries` parameter) that would prevent the file being re-uploaded several times.

don't know your codebase enough (or go for that matter) to send a pr - will be on the lookout for the fix. thanks in advance.

**Comment by zstadler** [comment]
This is not just a matter of efficiency. With the Amazon Drive quality of service and my internet connection quality, it is practically impossible to up load a large file.

It seems like after each low level retry the transfer is re-initiated. When trying to upload a 4.5Gb file,  the transfer was repeatedly reset to "0% done" with a similar message:
```
2016/08/05 23:26:34 pacer: Rate limited, sleeping for 235.010051ms (1 consecutive low level retries)
2016/08/05 23:26:34 pacer: low level retry 1/1 (error HTTP code 400: "400 Bad Request", reponse body: {"message":"Cannot complete upload"}
)
2016/08/05 23:26:34 XXXXXX.zip: Received error: HTTP code 400: "400 Bad Request", reponse body: {"message":"Cannot complete upload"}
 - low level retry 4/10
2016/08/05 23:26:42 Amazon_Drive: Saving new token in config file
2016/08/05 23:26:44 pacer: Resetting sleep to minimum 20ms on success
```

```rclone: Version "v1.32"```

**Comment by ncw** [comment]
I have posted a potential fix for the Amazon problem to #606.  I forgot about this ticket when I was doing it though.

What I could do instead is implement this ticket and make sure 400 errors, 504 GATEWAY_TIMEOUT and 408 GATEWAY TIMEOUT return errors that shouldn't be retried from amazon cloud drive.

The one possible downside is the eventual consistency of amazon directory listings - when you upload something it doesn't always appear in the directory listing for a while (seconds usually), so if you uploaded a file, got this sort of error, then immediately restarted the sync then it would upload it again and get a different error at the end.

The fix I posted in #606 only deals with the TIMEOUT errors and not "400 Bad request", so probably what is required is a combination of these two fixes.

**Comment by zstadler** [comment]
I suppose the directory listing delay issue can impact many scenarios, not only when the upload was interrupted and resumed. If so, I think the benefits of using a partially-loaded file are greater than the potential issues.

Please also check if the following error really requires the removal of the remote failed copy
```
2016/08/06 23:51:47 pacer: Rate limited, sleeping for 947.77941ms (1 consecutive low level retries)
2016/08/06 23:51:47 pacer: low level retry 1/1 (error Post https://content-na.drive.amazonaws.com/cdproxy/nodes?suppress=deduplication: write tcp 192.168.1.14:58880->52.72.69.9:443: wsasend: An existing connection was forcibly closed by the remote host.)
2016/08/06 23:51:47 XXXXXX.zip: Received error: Post https://content-na.drive.amazonaws.com/cdproxy/nodes?suppress=deduplication: write tcp 192.168.1.14:58880->52.72.69.9:443: wsasend: An existing connection was forcibly closed by the remote host. - low level retry 1/10
```

**Comment by ncw** [comment]
That error is a really useful one to retry - gets used a lot in drive uploads. 

The proper solution would be for amazon to implement a chucked head like all the other providers! 

Maybe the best solution in the meantime would be for rclone to detect if it had sent the last byte of the file or not. If it hadn't then the file definitely isn't complete. If it had then it could check for it (several times if necessary).  I  could probably implement this at a high level... Will think further.

**Comment by romusz** [comment]
For what it's worth, I reverted to v1.29 (from v1.30) and it takes care of the issue. The uploads error out but the higher-level retries see files already uploaded. (v1.29 does not delete the file on error).

**Comment by zstadler** [comment]
I've taken the latest built http://pub.rclone.org/v1.32-18-g29ab7ea%CE%B2/ published as part of #606, but it seems like the upload is still restarted from zero after a "504 GATEWAY_TIMEOUT" error.
See the [relevant section](http://pastebin.com/raw/QxsMSgbA) of the log file.

**Comment by ncw** [comment]
@zstadler Did the file get to nearly 100% first?

At the moment if a 504 happens and the file isn't found after a minute it will be retried.  I should probably make that waiting time longer than 1 minute.

I think I'll have a go at implementing this issue this evening.

**Comment by zstadler** [comment]
@ncw No, the [relevant section](http://pastebin.com/raw/QxsMSgbA) of the log file says that the file was only 17% done when a 504 happened.

Perhaps the recovery delay should be closer to the IO idle timeout (default 5m0s).

**Comment by ncw** [comment]
@zstadler if not all the file got sent then the work-arounds won't be effective - a retry is the only option.

Do you have the whole log file I could look at - I't like to see whether the token refreshing worked or not?

**Comment by zstadler** [comment]
Apparently, I have misunderstood this issue, thinking a **failed copy** it is likely to be a **partial** copy, and that keeping it will allow rclone to resume the upload to Amazon Drive. 

@ncw The token refreshing seems to work fine. For example:
```
2016/08/09 08:19:21 amazon drive root 'XXX': Token expired - 4 uploads in progress - refreshing
2016/08/09 08:19:23 Amazon_Drive: Saving new token in config file
2016/08/09 08:19:24 amazon drive root 'XXX': Token refresh successful
```

**Comment by ncw** [comment]
Unfortunately you can't resume an upload with ACD - the API isn't rich enough :-(

Thanks for the token refreshing log.  I'm hoping that will make a difference.

**Comment by zstadler** [comment]
By the way, were you able to get an invitation to the "[invite-only updated RESTful API](https://webcache.googleusercontent.com/search?q=cache:B7w7LdHc_zEJ:https://developer.amazon.com/public/apis/experience/cloud-drive/+&cd=1&hl=iw&ct=clnk&gl=il&client=firefox-b-ab)"?
My request was denied...

**Comment by ncw** [comment]
@zstadler my request was denied too :-(

**Comment by ncw** [comment]
I've done this in http://beta.rclone.org/v1.33-102-g441951a/ (will be uploaded in 15-30 mins)

**Comment by zstadler** [comment]
@ncw Thanks for the fix.

However, I will not be able to test it as I cancelled my ACD subscription before the end of the trial period. 

A large number of files, mostly larger than 1Gb, could not be uploaded after more than 2 months of trying.

**Comment by ncw** [comment]
@zstadler thanks for letting me know.
