### ISSUE TITLE
Google drive upload slow

### ISSUE THREAD

**Issue by DominicBoettger** [ncw/rclone#560]
> What is your rclone version (eg output from `rclone -V`)
1.30

> Which OS you are using and how many bits (eg Windows 7, 64 bit)
Ubuntu 14.04

> Which cloud storage system are you using? (eg Google Drive)
Google drive

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone sync 

The drive upload is painfully slow. The original drive client upload is MUCH faster. I always get a 403 Rate Limit exceeded error. I try to upload about 1TB of data and this will last for the next month to get finished..... Will it help to add a api key via the dev console and add client_id and client secret?

Thanks
Dominic

**Comment by ncw** [comment]
Are you uploading lots of small files? That is the worst case for drive.

Google has a lot of rate limiting, per client, per application per cluster as far as I can see.  You can get caught up in one of those rate limits. rclone has 1 billion operations per day quota from google and it is using nothing like that.

The Google drive client uses a different API to the one rclone uses an unpublished one :-(

Some people have reported that adding their own credentials does help - I'd be interested to hear if it does.

**Comment by DominicBoettger** [comment]
Yes, i am uploading a lot of files. I created a new entity in the developer console and now i am waiting for the response of the google team to increase my limits. I will post my results.

**Comment by ncw** [comment]
You could also try increasing `--transfers` to see if that helps.

**Comment by DominicBoettger** [comment]
I tried to ad client_id and client_secret created with my user. And if i now try to authenticate i get a 
 Failed to configure token: failed to get token: oauth2: cannot fetch token: 401 Unauthorized

The type is still drive.

**Comment by balazer** [comment]
Starting today, Google Drive became so slow that every attempt to copy to Google Drive would fail, never getting past the stage of "building file list", even if I set a large number of retries.  It repeatedly produced rateLimitExceeded errors.  Listing a directory at times was as slow as about one file per second.

So I set up my own client ID, and now things are working alright.  A couple of weeks ago I was getting 25 MB/s uploads. I'm getting 1.3 MB/s uploads now, but that might be because I'm uploading a lot of small files at the moment.

**Comment by doplu** [comment]
@balazer , Could you please add some details how you got client_id and client_secret ? I have tried to create one following these guidelines, but I am lost ! https://developers.google.com/identity/sign-in/web/devconsole-project
Thanks in advance ;)

**Comment by ncw** [comment]
Very useful information thanks @balazer 

I can see myself that it is running extremely slowly now :-(

I'll try tweaking the parameters of the rate limiter and see if I can improve things.  I suspect I might need to talk to someone at google to resolve the problem though.

If someone wanted to contribute a tutorial or list of instructions on how to get your own developer ID then I can include them in the rclone docs.

**Comment by davekr8** [comment]
https://console.developers.google.com

- [ ]  Select a project
   - [ ]  Create a project ...
      - fill in : Project name, etc, confirm.
      done !

- [ ]  API Manager 
   - [ ]  Overview
      - [ ]  Google Apps APIs
         - [ ]  Drive API
         - Enable
         - [ ]  Go to Credentials 
         - Google Drive API
         - Other UI
         - User data
         No need to be specific with the data ! 
                       
Result:
**Client ID
Client secret**

**Comment by balazer** [comment]
To create your own Google Drive client ID for rclone:

1. Log into the Google API Console at https://console.developers.google.com/ with your Google account . It doesn't matter what Google account you use. (It need not be the same account as the Google Drive you want to access)
2. Create a project, if you don't have one already.
3. With your project selected, in the API Manager under Overview, Google APIs, Google Apps APIs, click Drive API.
4. Click Enable. 
5. Click Go to Credentials.
6. In the credentials wizard:  Which API are you using? Google Drive API.  Where will you be calling the API from? Other UI. What data will you be accessing? User data.  Click "What credentials do I need?" 
7. Click "Create client ID". (the default name is fine)
8. Enter a "Product name shown to users".  This is the name that will be shown when rclone asks for permission to access your Google Drive.  I used "my-rclone".  Click Continue.
9. Download the client credentials in JSON format.  Click Done.
10. Use rclone config to add a new remote or edit an existing remote.  Enter the client_id and client_secret from the JSON file.

**Comment by doplu** [comment]
Many thanks @balazer & @davekr8 ! ;) 
I don't which method is the best, but I have just tested @balazer 's one and it seems to work fine for me so far. ;)
Many thanks to both of you for the help. I much appreciated. ;)

**Comment by ncw** [comment]
@balazer  @davekr8 thanks for the writeups - I'll put a combination of those into the google drive docs.

I've been in correspondence with google about rclone rate limits.  Apparently there **is** a global rate limit for rclone which **isn't** visible in the developer console!

Google have raised it to 300 Queries/second (from 100 Queries / second) and this has made rclone much more usable.  I think it could do with being higher still, but I don't think google want to raise it too quickly.

**Comment by davekr8** [comment]
well, i am running rclone on my own api keys and i realized a large ration of 
client errors / successfull request (s.below). 

is the a possible feature in the drive api to lower the erroneous payload of requests ? 

![stats](https://cloud.githubusercontent.com/assets/12131511/16871437/2d5e79be-4a87-11e6-9198-5509760dbd13.jpg)

**Comment by ncw** [comment]
The client errors are almost certainly 403 - rate limit exceeded.  That is drive's way of telling rclone to back off. There are lots of rate limits in drive - a per project one which isn't listed in the developers console and uploads per second and other invisible limits.

rclone tries to send stuff quickly, then backs off as it receives 403 errors.  This is the way it is supposed to work, but it is a bit annoying!

**Comment by davekr8** [comment]
i realized that mainly the checkers causes my errors ... reducing them to 2 completely avoids the 403 type...

but i thought of unsing batch type of requests (s. [https://developers.google.com/drive/v3/web/batch](https://developers.google.com/drive/v3/web/batch) for details). i haven't any idea if you already considered that design pattern of batch-requests in your code, or if it is too specific as only drive use it, to integrate it. but from my point of view, for drive it would worth to give a try.

**Comment by willpolley** [comment]
The upload limit is very curious since there seems to not be a download rate limit. I can only upload around 200Mbps max and can saturate my 1Gbps download.

https://www.dropbox.com/s/hsa4in3mysr7m6a/Screen%20Shot%202016-07-23%20at%2011.13.16%20AM.png?dl=0

**Comment by ncw** [comment]
The google developers told me that there are lots of other invisible (to me) rate limits.  I'm pretty sure one at least is uploads/second.  I would be suprised if another limited the total upload rate - I've never exceeded 200 Mbit/s on our 1 Gbit/s connection at work either.

**Comment by zeshanb** [comment]
@Nick

Was there a throttle option? I assumed -bw-limit option was a throttle
option eg #mbps , #kbps.

Regards,
Zeshan

**Comment by ncw** [comment]
@zeshanb `--bw-limit` is rclone's throttle - I was talking about Google Drive's throttling which we can't see and have no control over :-(

**Comment by ncw** [comment]
I'm going to write the conclusions of this up into the drive docs including instructions on how to make a drive developer's account.

**Comment by braderhart** [comment]
Wow, what a difference making my own client_id. Minio or Ceph is next on my list!

https://rclone.org/drive/#making-your-own-client-id

**Comment by chocolatkey** [comment]
After creating my own API key and starting an upload (both from apps for education a.k.a. unlimited account) I was able to achieve ~450Mbit/s speeds for around an hours, and then I was suddenly given 402 unauthorized.
![image](https://user-images.githubusercontent.com/13407784/33801250-05bd4644-dd0a-11e7-98d3-d9a9cdd9eac6.png)
I created new auth clients and new developer console projects, but I am now throttled to about 6Mbit/s. I was only uploading large files, so the amount of requests I was making was nowhere near the limits:
![image](https://user-images.githubusercontent.com/13407784/33801257-8652872e-dd0a-11e7-99cf-0b36eb8f68f7.png)
Is this this another one of their 'hidden' rate limits?

**Comment by braderhart** [comment]
Same issue here as ell.

**Comment by chocolatkey** [comment]
this is funny, i'm back to high speeds, i'm going to see how it plays out:
![image](https://user-images.githubusercontent.com/13407784/33802805-00e0b52c-dd35-11e7-842f-8a1e49606e8b.png)

**Comment by evulhotdog** [comment]
Google drive has a hard limit of 750gb of data allowed uploaded in a 24 hour period. I believe the OP in this issue is related to that, not throttling as the later comments have posted.

**Comment by chocolatkey** [comment]
@evulhotdog thanks for that info, that explains why I was reduced to 0 after uploading around that much.
