### ISSUE TITLE
SWIFT tenant option is mandatory but interactive config session say optional

### ISSUE THREAD

**Issue by zioproto** [ncw/rclone#563]
When filing an issue, please include the following information if
possible as well as a description of the problem.

> What is your rclone version (eg output from `rclone -V`)

rclone v1.29

> Which OS you are using and how many bits (eg Windows 7, 64 bit)

Mac OS X 64bit

> Which cloud storage system are you using? (eg Google Drive)

Swift

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

rclone config

> A log from the command with the `-v` flag (eg output from `rclone -v copy /tmp remote:tmp`)

During the interactive setup of the remote we have

    Tenant name - optional
But from issue #460 we know that the Tenant is mandatory for the swift remote to make authentication properly working.

**Comment by ncw** [comment]
Tenant is optional for v1 auth which rclone supports.  You are right it needs to be filled in otherwise.

I've fixed that in the help string.

Thanks for pointing that out.
