### ISSUE TITLE
Suggestion : copy to Google Drive and convert files to Google Doc format

### ISSUE THREAD

**Issue by doplu** [ncw/rclone#565]
Hello,
First, thank you for creating this great program. ;)

It is already possible to Copy files from let's say Amazon Drive to Google Drive. But, unless error from my part, it would be great if we could convert them to the Google Doc format.
_Example:_ pdf file in Amazon Drive being copied To Google Drive and converted there to a Google Document.

_**This may be the needed info** :_
Importing to Google Docs types 
https://developers.google.com/drive/v3/web/manage-uploads#importing_to_google_docs_types_wzxhzdk8wzxhzdk9

Thanks in advance ;)

**Comment by dav1303** [comment]
+1

**Comment by B4dM4n** [comment]
Since there are some duplicate issues now I will close this one in favor of #2046.
