### ISSUE TITLE
New S3 Region: Asia Pacific (Mumbai)

### ISSUE THREAD

**Issue by cg-cnu** [ncw/rclone#567]
Trying to setup S3 and found the new S3 Region **Asia Pacific (Mumbai)** missing in the list of available Regions.  Using Rclone v1.30 on CentOS Linux release 7.1.1503, x86_64.

**Comment by ncw** [comment]
I've fixed this - fancy giving the beta a go?

http://pub.rclone.org/v1.30-28-g2a1d4b7%CE%B2/

**Comment by cg-cnu** [comment]
I gave it a shot! It works, thanks.

**Comment by ncw** [comment]
@cg-cnu thanks for testing :-)
