### ISSUE TITLE
amazon.tld

### ISSUE THREAD

**Issue by jujes** [ncw/rclone#569]
### amazon.es 

My Amazon Cloud Drive is managed in amazon.es and think is the same issue for all other amazon.tld when try set up..

someone can tell me how connect whit this kind of domain?

thanks in advance,

> What is your rclone version (eg output from `)

**rclone v1.30**

> Which OS you are using and how many bits (eg Windows 7, 64 bit)

**ubuntu 16.04**

> Which cloud storage system are you using? (eg Google Drive)

**amazon cloud drive**

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

**rclone config**

**Comment by ncw** [comment]
I know it works for .co.uk so I would have thought it would just work for .es.

The setup in http://rclone.org/amazonclouddrive/ should work. If it doesn't then let me know what errors you get.

**Comment by jujes** [comment]
@ncw it's work :+1: 
:100:

**Comment by ncw** [comment]
Super :-)
