### ISSUE TITLE
How to upload directories to Amazon drive, not just the directory contents?

### ISSUE THREAD

**Issue by arahman91** [ncw/rclone#570]
When trying to follow directions to upload directories to Amazon Cloud drive (rclone copy /source/directory remote:folder) it only uploads the directory contents, not the directory.  

What command to use to upload the dirctory too, not just the contents?

**Comment by ncw** [comment]
Just name the folder that you want stuff to go in on the end of the remote string. 

So for your example 

rclone copy /source/directory remote:folder/directory

**Comment by arahman91** [comment]
Was hoping rclone could do it by itself...is this some current limitation?

**Comment by ncw** [comment]
If you prefer you could do this

    rclone copy --include "/directory/**" /source remote:folder

Rclone works by copying from directory to directory (If you are familiar with rsync that is with putting a `/` on the end of the directories being synced).

I decided not to do what rsync does and do different things as to whether you put a `/` on the end of the path or not as it is a source of great confusion for people and any number of gotchas.
