### ISSUE TITLE
build binary from source

### ISSUE THREAD

**Issue by uddipan** [ncw/rclone#571]
Hi Nick,

I am using the latest rclone version on OSX. Is there a way to generate the binary from source? 
For example if I want to add a few prints and then build the binary. Will running the makefile be enough?

Thanks

**Comment by lorenzoferrarajr** [comment]
Hi @uddipan,
maybe this is what you're searching for: https://github.com/ncw/rclone/blob/master/CONTRIBUTING.md#submitting-a-pull-request

**Comment by ncw** [comment]
As @lorenzoferrarajr suggests a truncated version of the submitting a pull request instructions will work.

You'll need a Go environment set up with GOPATH set.  See [the Go getting started docs](https://golang.org/doc/install) for more info.

Then install rclone and all of its dependencies

    go get github.com/ncw/rclone

Look at the source code

    cd $GOPATH/src/github.com/ncw/rclone

Rebuild the source code

    go install

NB The binary is in `$GOPATH/bin` - most go developers put that on their PATH.

You don't need the makefile for development - it is only used for making releases.

**Comment by uddipan** [comment]
awesome !!

Thanks a lot
