### ISSUE TITLE
Better message when "updated existing"?

### ISSUE THREAD

**Issue by lorenzoferrarajr** [ncw/rclone#574]
First things first: thank you for working on this great tool!

I'm running rclone with the copy command and, for some files, I get this:

    2016/07/08 20:42:14 rclone: Version "v1.30-28-g2a1d4b7β" starting with parameters ["rclone" "-v" "--no-traverse" "--transfers=4" "--verbose" "--checksum" "--max-size=50G" "copy" "/Volumes/ZooeyOne" "acd:ZooeyOne"]
    2016/07/08 20:42:16 Amazon cloud drive root 'ZooeyOne': Modify window not supported
    2016/07/08 20:42:17 .DS_Store: Hash differ
    2016/07/08 20:42:18 .DS_Store: Copied (updated existing)

But what does "updated existing" mean? Is it appending to the file or is it replacing the file? I imagine it's replacing the file... if so, could you use "replaced existing"?

More info:

- rclone version: rclone v1.30-11-g22ab4e4β
- os: OS X 10.11.5 (Darwin Kernel Version 15.5.0: x86_64)
- service: Amazon Cloud Drive
- command: `rclone -v --no-traverse --transfers=4 --verbose --checksum --max-size=50G copy /Volumes/ZooeyOne acd:ZooeyOne`

**Comment by ncw** [comment]
Yes you are right, "replaced existing" would be more accurate.  I've fixed this - it will be in the next beta.
