### ISSUE TITLE
GoogleDrive: Move just deletes files

### ISSUE THREAD

**Issue by monarchdodra** [ncw/rclone#577]
Just lost a month's/4GB worth of photos. The files I can restore the files themselves from backup, but my albums, shares and related metadata are wrecked.

Furthermore, I validated with dry run this would work correctly, but the dry run did not actually list all operations (see below).

In particular, I'd have wished any deleted files would appear in my trash. I did not find a "use trash" option, which would have been nice.

This is a spectacularly bad experience for me.

> What is your rclone version (eg output from `rclone -V`)
rclone v1.30

> Which OS you are using and how many bits (eg Windows 7, 64 bit)
Ubuntu 16.04 LTS
64

> Which cloud storage system are you using? (eg Google Drive)
Google Drive

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone move --include '*201601*' nous:Photos/2016 nous:Photos/2016/2016-01

> A log from the command with the `-v` flag (eg output from `rclone -v copy /tmp remote:tmp`)
Since the files were deleted, here is a log with other files (useless info grepped out):
rclone move -v --include '*Monde*' nous:Photos/2016 nous:Photos/2016/2016-01

2016/07/09 21:05:40 rclone: Version "v1.30" starting with parameters ["/bin/rclone" "move" "-v" "--include" "*Monde*" "nous:Photos/2016" "nous:Photos/2016/2016-01"]
2016/07/09 21:06:39 TapisMondeOxybul.jpg: Moved
2016/07/09 21:06:39 Waiting for deletions to finish
2016/07/09 21:06:58 
Transferred:            0Bytes (0Byte/s)
Errors:                 0
Checks:                 0
Transferred:            1
Elapsed time:     1m17.7s

2016/07/09 21:07:19 2016-01/TapisMondeOxybul.jpg: Deleted
2016/07/09 21:07:21 
Transferred:            0Bytes (0Byte/s)
Errors:                 0
Checks:                 1
Transferred:            1
Elapsed time:     1m40.6s
2016/07/09 21:07:21 Go routines at exit 6

I'm noticing "2016-01/TapisMondeOxybul.jpg: Deleted": Are we deleting the destination file !?

Also, with --dry-run:
2016/07/09 21:15:08 rclone: Version "v1.30" starting with parameters ["/bin/rclone" "move" "-v" "--dry-run" "--include" "*Eau*" "nous:Photos/2016" "nous:Photos/2016/2016-01"]
2016/07/09 21:15:48 TableSableEauOxybul.jpg: Not moving as --dry-run
2016/07/09 21:15:48 Waiting for deletions to finish
2016/07/09 21:16:10 
Transferred:            0Bytes (0Byte/s)
Errors:                 0
Checks:                 0
Transferred:            1
Elapsed time:      1m1.6s

2016/07/09 21:16:10 TableSableEauOxybul.jpg: Not deleting as --dry-run
2016/07/09 21:16:20 
Transferred:            0Bytes (0Byte/s)
Errors:                 0
Checks:                 0
Transferred:            1
Elapsed time:     1m12.2s
2016/07/09 21:16:20 Go routines at exit 6

Notice how this time, "TableSableEauOxybul.jpg: Not deleting as --dry-run" the deleted file does not see, to be the destiation file

**Comment by monarchdodra** [comment]
I'm realizing I over grepped the previous log. Here is the output:
cat verbose | grep -Ev "low level retry|Excluded from sync|sleep"
2016/07/09 21:05:40 rclone: Version "v1.30" starting with parameters ["/bin/rclone30" "move" "-v" "--include" "*Monde*" "nous:Photos/2016" "nous:Photos/2016/2016-01"]
2016/07/09 21:05:58 Google drive root 'Photos/2016/2016-01': Modify window is 1ms
2016/07/09 21:05:58 Google drive root 'Photos/2016': Building file list
2016/07/09 21:05:58 Google drive root 'Photos/2016': Reading ""
2016/07/09 21:05:58 Google drive root 'Photos/2016/2016-01': Building file list
2016/07/09 21:05:58 Google drive root 'Photos/2016/2016-01': Reading ""
2016/07/09 21:05:58 Google drive root 'Photos/2016/2016-01': Finished reading ""
2016/07/09 21:05:58 Google drive root 'Photos/2016/2016-01': Done building file list
2016/07/09 21:06:38 Google drive root 'Photos/2016': Finished reading ""
2016/07/09 21:06:38 Google drive root 'Photos/2016': Reading "2016-01/"
2016/07/09 21:06:39 Google drive root 'Photos/2016': Finished reading "2016-01/"
2016/07/09 21:06:39 Google drive root 'Photos/2016': Done building file list
2016/07/09 21:06:39 Google drive root 'Photos/2016/2016-01': Waiting for checks to finish
2016/07/09 21:06:39 Google drive root 'Photos/2016/2016-01': Waiting for transfers to finish
2016/07/09 21:06:39 TapisMondeOxybul.jpg: Moved
2016/07/09 21:06:39 Waiting for deletions to finish
2016/07/09 21:06:39 Google drive root 'Photos/2016': Reading ""
2016/07/09 21:06:58 
Transferred:            0Bytes (0Byte/s)
Errors:                 0
Checks:                 0
Transferred:            1
Elapsed time:     1m17.7s

2016/07/09 21:07:10 Google drive root 'Photos/2016': Finished reading ""
2016/07/09 21:07:10 Google drive root 'Photos/2016': Reading "2016-01/"
2016/07/09 21:07:10 Google drive root 'Photos/2016': Finished reading "2016-01/"
2016/07/09 21:07:19 2016-01/TapisMondeOxybul.jpg: Deleted
2016/07/09 21:07:21 
Transferred:            0Bytes (0Byte/s)
Errors:                 0
Checks:                 1
Transferred:            1
Elapsed time:     1m40.6s
2016/07/09 21:07:21 Go routines at exit 6

**Comment by monarchdodra** [comment]
Actually, it seems that any move on the same remote just deletes your files for Google Drive >:( This is awful!

$/bin/rclone move -v nous:test.txt nous:Folder
2016/07/09 22:18:22 rclone: Version "v1.30" starting with parameters ["/home/happypal/bin/rclone30" "move" "-v" "nous:test.txt" "nous:Folder"]
2016/07/09 22:18:41 Google drive root 'Folder': Modify window is 1ms
2016/07/09 22:18:41 <nil>: Can't move directory - not same remote type
2016/07/09 22:18:41 Google drive root 'Folder': Using server side directory move
2016/07/09 22:18:41 Google drive root 'Folder': Server side directory move failed - fallback to copy/delete: can't move directory - incompatible remotes
2016/07/09 22:18:41 Google drive root '' limited to 1 objects: Building file list
2016/07/09 22:18:41 Google drive root 'Folder': Building file list
2016/07/09 22:18:41 Google drive root '' limited to 1 objects: Done building file list
2016/07/09 22:18:41 Google drive root 'Folder': Reading ""
2016/07/09 22:18:41 Google drive root 'Folder': Finished reading ""
2016/07/09 22:18:41 Google drive root 'Folder': Done building file list
2016/07/09 22:18:41 Google drive root 'Folder': Waiting for checks to finish
2016/07/09 22:18:41 Google drive root 'Folder': Waiting for transfers to finish
2016/07/09 22:18:41 test.txt: Moved
2016/07/09 22:18:41 Waiting for deletions to finish
2016/07/09 22:18:48 test.txt: Deleted
2016/07/09 22:18:48 
Transferred:            0Bytes (0Byte/s)
Errors:                 0
Checks:                 1
Transferred:            1
Elapsed time:       25.9s
2016/07/09 22:18:48 Go routines at exit 7

Result: Folder is created. file is moved then deleted. The UI confirms this:
Youpermanently deleted an item
rclone • 10:18 PM
Text
test.txt

**Comment by ncw** [comment]
Ach, I'm sorry :-(

I think this is the same issue as #512. I need to disallow moves from source to source/destination as this is equivalent to a copy source to destination then a delete of the source :-(

You can use the –drive-use-trash flag if you want deletions to go into the trash. Not much use to you now though. 

I will have a think on how to prevent this in the future. 

Many Apologies 

Nick

**Comment by monarchdodra** [comment]
> You can use the –drive-use-trash flag

I missed that. Thanks.

> I think this is the same issue as #512. I need to disallow moves from source to source/destination as this is equivalent to a copy source to destination then a delete of the source :-(

What has me confused here about this comment is that I can clearly see from the history that my file was actually moved, not copied.

If move was actually a copy then a purge (I assume purge==delete?), then this would not be a problem? So I assume this means rclone understands that the source/path are on the same remote? In which case it could also know not to do the delete? (I can imagine it depends on every cloud service type of course).

Or am I missing something? Is rclone currently incapable of moving files in a given remote?

I'm just asking to try to learn. I can imagine it might not actually be this simple given these meta file systems...

**Comment by ncw** [comment]
Rclone will move it if the underlying remote is capable of it which drive is. 

I'm not at my computer at the moment - I'll take a look at the source tomorrow and come up with something definitive.

**Comment by ncw** [comment]
OK I've fixed this in this beta: http://pub.rclone.org/v1.30-30-g4f2daa6%CE%B2/

I've decided to re-work the way move works to make it more what people expect.

Here is the new help

### move source:path dest:path ###

Moves the contents of the source directory to the destination
directory. Rclone will error if the source and destination
overlap.

If no filters are in use and if possible this will server side move
`source:path` into `dest:path`. After this `source:path` will no
longer longer exist.

Otherwise for each file in `source:path` selected by the filters (if
any) this will move it into `dest:path`.  If possible a server side
move will be used, otherwise it will copy it (server side if possible)
into `dest:path` then delete the original (if no errors on copy) in
`source:path`.

**Important**: Since this can cause data loss, test first with the
--dry-run flag.

**Comment by ncw** [comment]
I've pushed out the v1.31 release with this fix in.
