### ISSUE TITLE
Backblaze B2: large files continually re-uploaded during sync operation

### ISSUE THREAD

**Issue by joemiller** [ncw/rclone#582]
When filing an issue, please include the following information if
possible as well as a description of the problem.

> What is your rclone version (eg output from `rclone -V`)
rclone v1.30-21-g018fe80β

> Which OS you are using and how many bits (eg Windows 7, 64 bit)
ubuntu 14.04, 3.13.0-83-generic, amd64

> Which cloud storage system are you using? (eg Google Drive)
backblaze B2

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
```
rclone sync --stats=5s --retries=10 --checkers=32 --bwlimit=1.3m --transfers=32 -v /files/photos b2:BUCKET/files/photos
```

> A log from the command with the `-v` flag (eg output from `rclone -v copy /tmp remote:tmp`)
too long to paste, but I could follow up with relevant parts or a gist.

I am trying to do an `rclone sync` of a local directory to the B2 service. Everything seems fine except for large files. There are several thousand files in this directory but only one that is over the large file limit (5GB) of the B2 api. Every time I run the `sync` operation the large file is re-uploaded. Also it seems like the large file is not uploaded to the correct path.

For example, the directory hiearchy I am sync'ing is `/files/photos` -> `BUCKET/files/photos`. The large file is `/files/photos/wedding-photos.zip` which should be uploaded to `BUCKET/files/photos/wedding-photos.zip` but instead it is landing at the root of the bucket: `BUCKET/wedding-photos.zip`.

Summary: The upload seems to complete OK, for what it's worth, it just ends up in the wrong place on the destination and is uploaded everytime a `sync` is run.

I am using the v1.30-21-g018fe80β build which I found in another thread about Backblaze bugs/imiprovements.

**Comment by ncw** [comment]
I can see I've messed that up!

Can you try this beta for me please?

http://pub.rclone.org/rclone-v1.31-2-g41917eb.zip

Thanks

Nick

**Comment by joemiller** [comment]
@ncw perfect! 👍 fixed.

This is such a great project, BTW. Thanks for all of your hard work.

**Comment by ncw** [comment]
Thanks for testing! I'm going to put a new release out with that fix in ASAP!
