### ISSUE TITLE
Backblaze B2: large files ignore destination directory

### ISSUE THREAD

**Issue by GrahamCobb** [ncw/rclone#584]
When copying a directory containing a single large file to B2, the destination directory was ignored and the file appeared in the top level in the bucket.

It seemed to work with small files (a few bytes).  The large file, which didn't work, was about 1.1GB.

> What is your rclone version (eg output from `rclone -V`)

rclone v1.31

> Which OS you are using and how many bits (eg Windows 7, 64 bit)

Linux, 64-bit

> Which cloud storage system are you using? (eg Google Drive)

Backblaze B2

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

rclone -v copy /tmp/rclone-test/ b2:test-b2backend-grc/rclone/test

The directory /tmp/rclone-test contained one file, about 1.1GB.

> A log from the command with the `-v` flag (eg output from `rclone -v copy /tmp remote:tmp`)

The issue form doesn't seem to want to attach my log, so here it is as a Gist: https://gist.github.com/GrahamCobb/a109903a247930fd7e836b3f64c107a4

**Comment by ncw** [comment]
I've fixed this in 1.32 which I released specially to cure this problem :-)

**Comment by GrahamCobb** [comment]
Thanks.  I will have to learn to type up my bug reports faster :-)

1.32 does, indeed, fix this.
