### ISSUE TITLE
Backblaze B2 sync SIGSEGV crash after 6 hours

### ISSUE THREAD

**Issue by GrahamCobb** [ncw/rclone#585]
After doing a few small tests over the last few days, I set rclone going with a real workload last night.  It was syncing 66GB to a previously empty "folder".  As this was an upload from home I am expecting it to take about 24 hours.

However, it crashed after about 6 hours.  I have attached the log with all the backtraces.  At a quick glance I can't see which thread actually caused the crash.

I am half expecting it was a Backblaze problem: after all this is a new account and I have just added a credit card; maybe it limits how much space you can take up until it processes a payment or something?  But, in any case, I presume the intention is that rclone would report an error, not crash.

I have not yet retried the operation: that will happen tonight.  But I thought I would report it now in case there is something that can be fixed quickly or that I can change to workround it.

When filing an issue, please include the following information if
possible as well as a description of the problem.

> What is your rclone version (eg output from `rclone -V`)

rclone v1.32
I have checked this time that there isn't a new release :-)

> Which OS you are using and how many bits (eg Windows 7, 64 bit)

Debian testing, 64

> Which cloud storage system are you using? (eg Google Drive)

Backblaze B2

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone sync --delete-after /nas/backup/DAR-archive/novatech/ b2:XXXX/rclone/nas/backup/DAR-archive/novatech/

> A log from the command with the `-v` flag (eg output from `rclone -v copy /tmp remote:tmp`)

I have attached the log, with backtraces, but with the stats output removed (there was a lot of it -- I still have it if you want it).  This was not a "-v" log (let me know if you want me to add that for the next run).

[Not sure what is wrong with the New Issue form, or with using it from firefox-esr, but it won't let me attach the log.  I have, again, added it as a Gist: https://gist.github.com/GrahamCobb/926ae43cd5a39512a5c5c5d1d5e935a3 ]

**Comment by ncw** [comment]
That looks like a crash in the Go runtime while it is doing garbage collection.

rclone doesn't use cgo or unsafe so it is unlikely to be an rclone problem unless there is some weird race condition... However I can't see an bug against the go runtime which fits this.

Can you try http://pub.rclone.org/rclone-v1.31-2-g41917eb-go1.7rc1.zip which is 1.32 but compiled with the latest not quite released yet go compiler + runtime.

I could also send you a version with the race detector compiled in which would be useful to know if this is an rclone problem.

@klauspost anything spring to mind?

**Comment by GrahamCobb** [comment]
I will use that version of rclone in tonight's run.  I note that -V says it is 1.31, not 1.32.  Does that version include the B2 remote directory fix?

**Comment by ncw** [comment]
It does yes.

**Comment by GrahamCobb** [comment]
I can report that the copies have now finished (after a few attempts) with the special version you supplied without reproducing the same error (there was a different error which looks unrelated so I will report separately).

I will leave it running -- it runs every night but the directory which is being cloned is only updated monthly (unless I extend it to further directories, which I will do sometime).  I will report back if I see it again.

**Comment by ncw** [comment]
Thanks for testing.

Go 1.7 should be out by the time I release v1.33 so the fix should be in then.

**Comment by ncw** [comment]
I'm using go 1.7 now it has been released.

Here is a beta compiled with 1.7: http://pub.rclone.org/v1.32-22-gb4f2ada%CE%B2/

Please re-open this ticket if you see this problem again!

Thanks
