### ISSUE TITLE
s3: dreamhost: server side copy of non ascii characters fails

### ISSUE THREAD

**Issue by nagualcode** [ncw/rclone#586]
From osx terminal, when I sync one bucket to another bucket (server side), I can see that files with simples characters and no spaces, are copied ok, 
files with complex characters and spaces between files, results in errors like these:

2016/07/15 11:16:14 06 - When My 'a.odf: Failed to copy: NoSuchKey: 
    status code: 404, request id: tx00000000000000000dee2-005788f02e-e20c70e-default

When filing an issue, please include the following information if
possible as well as a description of the problem.

> What is your rclone version (eg output from `rclone -V`)

rclone v1.29

> Which OS you are using and how many bits (eg Windows 7, 64 bit)

OSX El Cap.

> Locale:

LANG=
LC_COLLATE="C"
LC_CTYPE="UTF-8"
LC_MESSAGES="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_ALL=

> Which cloud storage system are you using? (eg Google Drive)

DreamObjects

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

copy and sync

**Comment by ncw** [comment]
Interesting... I just tried a test with s3 and it worked fine.

```
$ echo hello > /tmp/"complex character £100.txt"
$ rclone copy /tmp/"complex character £100.txt" s3:utf8-test
$ rclone copy s3:utf8-test  s3:utf8-test2
2016/07/15 15:27:57 S3 bucket utf8-test2: Waiting for checks to finish
2016/07/15 15:27:57 S3 bucket utf8-test2: Waiting for transfers to finish
2016/07/15 15:27:58 
Transferred:      0 Bytes (0 Bytes/s)
Errors:                 0
Checks:                 0
Transferred:            1
Elapsed time:          9s
```

However if I try the same test with dreamhost

```
rclone copy /tmp/"complex character £100.txt" dreamhost:utf8-tes
rclone -v --dump-bodies --retries 1 copy dreamhost:utf8-test  dreamhost:utf8-test2
```

I get the same error as you

```
2016/07/15 15:29:45 complex character £100.txt: Failed to copy: NoSuchKey: 
	status code: 404, request id: tx000000000000000019ea9-005788f359-e20c137-default
2016/07/15 15:29:45 Attempt 1/1 failed with 1 errors and: NoSuchKey: 
	status code: 404, request id: tx000000000000000019ea9-005788f359-e20c137-default
2016/07/15 15:29:45 Failed to copy: NoSuchKey: 
	status code: 404, request id: tx000000000000000019ea9-005788f359-e20c137-default
```

Here is the troublesome HTTP transaction

```
2016/07/15 15:29:45 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2016/07/15 15:29:45 HTTP REQUEST
2016/07/15 15:29:45 PUT /utf8-test2/complex%20character%20%C2%A3100.txt HTTP/1.1
Host: objects-us-west-1.dream.io
User-Agent: rclone/v1.32
Content-Length: 0
Authorization: DELETED
Date: Fri, 15 Jul 2016 14:29:45 UTC
X-Amz-Copy-Source: utf8-test%2Fcomplex+character+%C2%A3100.txt
X-Amz-Metadata-Directive: COPY
Accept-Encoding: gzip

2016/07/15 15:29:45 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2016/07/15 15:29:45 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2016/07/15 15:29:45 HTTP RESPONSE
2016/07/15 15:29:45 HTTP/1.1 404 Not Found
Content-Length: 75
Accept-Ranges: bytes
Content-Type: application/xml
Date: Fri, 15 Jul 2016 14:29:45 GMT
X-Amz-Request-Id: tx000000000000000019ea9-005788f359-e20c137-default

<?xml version="1.0" encoding="UTF-8"?><Error><Code>NoSuchKey</Code></Error>
2016/07/15 15:29:45 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
```

What I suspect is that Dreamhost (and thus CEPH) isn't URL decoding the `X-Amz-Copy-Source` header properly in the request. It says in the [s3 COPY docs](http://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectCOPY.html) that "This string must be URL-encoded."

I put that URL encoding in to fix #315 which was a very similar problem with S3.

The [CEPH docs on COPY](http://docs.ceph.com/docs/hammer/radosgw/s3/objectops/) don't mention the URL encoding so I suspect this is a bug in CEPH being out of compliance with the S3 spec.

It is possible that it is [CEPH issue 8202](http://tracker.ceph.com/issues/8202) but I'm not 100% certain.

I'll submit a ticket with dreamhost and see what they say!

**Comment by ncw** [comment]
I received a very helpful response from Dreamhost support

> Thanks for the info.  We are actually already looking into something
> similar.  The DreamObjects system runs on Ceph, and we are waiting for a
> new release to drop really soon so we can verify whether it has a fit in
> it for this issue or not.  I will add a comment to our internal tracker
> to update that github issue as well, and can keep your ticket open to
> notify you if you wish as well, when we have the new release tested and
> pushed and can test it.

**Comment by ncw** [comment]
Tested just now, still not working :-(

**Comment by ncw** [comment]
Tested again - still not working.

**Comment by ncw** [comment]
Tested after dreamhost upgrade but not change unfortunately.

**Comment by ncw** [comment]
This came up again so I reported a CEPH bug here: http://tracker.ceph.com/issues/22121

**Comment by ncw** [comment]
This is now fixed by dreamhost in the CEPH Luminous release - hooray!

I'll leave this issue open a bit longer until the fix is merged upstream.

**Comment by ncw** [comment]
Looks like the fix is in progress at CEPH so I'm going to close this now.
