### ISSUE TITLE
Backblaze B2: token expires after ~ 24hours of transfer

### ISSUE THREAD

**Issue by joemiller** [ncw/rclone#588]
When filing an issue, please include the following information if
possible as well as a description of the problem.

> What is your rclone version (eg output from `rclone -V`)
rclone v1.31

> Which OS you are using and how many bits (eg Windows 7, 64 bit)
linux amd64

> Which cloud storage system are you using? (eg Google Drive)
backblaze b2

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone sync

> A log from the command with the `-v` flag (eg output from `rclone -v copy /tmp remote:tmp`)

I had a long sync running to backblaze B2 and after about 24 hours it started throwing errors about token expiration. I haven't checked the B2 API docs but my assumption is that rclone may need to refresh its token periodically for very long xfers.

error:

```
07:07:15 2016/07/16 07:07:15 
07:07:15 Transferred:   127.499 GBytes (1.497 MBytes/s)
07:07:15 Errors:                 9
07:07:15 Checks:               114
07:07:15 Transferred:         3776
07:07:15 Elapsed time:  24h14m0.3s
07:07:15 Transferring:
07:07:15  *    windows-8-x86_64.vbox/windows-8-x86_64.vdi: 100% done. avg:   96.3, cur:  934.9 kByte/s. ETA: 0s
07:07:15 
07:07:52 2016/07/16 07:07:52 B2 bucket FOO path files/vm/: not deleting files as there were IO errors
07:07:52 2016/07/16 07:07:52 Attempt 1/10 failed with 9 errors and: not deleting files as there were IO errors
07:07:55 2016/07/16 07:07:55 B2 bucket FOO path files/vm/: Waiting for checks to finish
07:07:55 2016/07/16 07:07:55 B2 bucket FOO path files/vm/: Waiting for transfers to finish
07:08:00 2016/07/16 07:08:00 macbook-windows-7-x64.vmwarevm/appListCache/appData/xyz.appicon: Failed to copy: Authorization token has expired (401 expired_auth_token)
```

The API key used to configure the B2 api (in `~/.rclone.conf`) is still good as stopping/starting the xfer again works fine, so I imagine it's just some kind of session token that is expiring.

**Comment by ncw** [comment]
Rclone should have refreshed it's tokens and carried on. 

Judging from the fact you only had 9 errors the sync worked pretty well. 

Any chance you could get me a log with -v of this happening? 

You should upgrade to 1.32 there is a bug with B2 in 1.31 BTW.

**Comment by joemiller** [comment]
Ok, I updated to 1.32. I am not sure I can re-create the error efficiently as it would require another long, large upload which I need to avoid due to ISP bandwidth limits. I will close this bug for now and re-open if it re-occurs.

**Comment by nemobis** [comment]
(Thanks for rclone, it's fantastic.) I saw this error on 1.35-DEV while doing some concurrent long-running `sync -c` jobs. They got some hundreds GB uploaded and then nothing for an entire day. I've now restarted them with verbose mode, I'll let you know if the error reappears.

**Comment by nemobis** [comment]
Yep, this is definitely still happening (I have several uploads which stopped after 24 hours exactly and some 1200 GiB uploaded), but I don't have the output from the previous verbose run. Maybe next week.

**Comment by ncw** [comment]
@nemobis a log with `-vv` with the latest beta is what is needed to track down problems - thanks!

**Comment by nemobis** [comment]
Ok, will try.

**Comment by nemobis** [comment]
I cannot reproduce the issue with the latest beta.
