### ISSUE TITLE
Multiple rclone calls

### ISSUE THREAD

**Issue by damianoporta** [ncw/rclone#590]
When filing an issue, please include the following information if
possible as well as a description of the problem.

> What is your rclone version (eg output from `rclone -V`)
rclone v1.32
> Which OS you are using and how many bits (eg Windows 7, 64 bit)
Ubuntu 16.04
> Which cloud storage system are you using? (eg Google Drive)
Amazon Cloud Drive
> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone copy
> A log from the command with the `-v` flag (eg output from `rclone -v copy /tmp remote:tmp`)
it is not an error

Hi! I just wondering if i can use rclone copy on multiple connections. ( i mean execute simultaneus `rclone copy` on different shells) Is there a limit?

Thank you for your awesome tool!

**Comment by ncw** [comment]
You can run as many rclones as you like.

Note that Amazon/Google rate limit you on your user details so you might find running multiple copies slows all of them down.

The only potential problem is that when rclone refreshes the token for Amazon Drive it will write it back to the config file. I don't think this will cause a problem with multiple rclones writing to it though, you'll get the result of the last one to write to it.
