### ISSUE TITLE
Windows access denied

### ISSUE THREAD

**Issue by itsrabie** [ncw/rclone#599]
> What is your rclone version (eg output from `rclone -V`)

v1.32

> Which OS you are using and how many bits (eg Windows 7, 64 bit)

Windows 7, 64-bit 

> Which cloud storage system are you using? (eg Google Drive)

Amazon Cloud Drive

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

rclone --filter-from filter-file.txt --stats=5s --transfers=5 --verbose --log-file=A5.txt sync A:/ ACD:"A drive" 

> A log from the command with the `-v` flag (eg output from `rclone -v copy /tmp remote:tmp`)

2016/07/28 12:25:02 rclone: Version "v1.32" starting with parameters ["rclone" "--filter-from" "filter-file.txt" "--stats=5s" "--transfers=5" "--verbose" "--log-file=A5.txt" "sync" "A:/" "ACD:A drive"]
2016/07/28 12:59:44 amazon drive root 'A drive of HTPC': Waiting for transfers to finish
2016/07/28 12:59:44 amazon drive root 'A drive of HTPC': not deleting files as there were IO errors
2016/07/28 12:59:44 Attempt 3/3 failed with 0 errors and: failed to open directory "\\\\?\\A:\\data\\HTPC_20151119-000002": open \\?\A:\data\HTPC_20151119-000002: Access is denied.
2016/07/28 12:59:44 Failed to sync: failed to open directory "\\\\?\\A:\\data\\HTPC_20151119-000002": open \\?\A:\data\HTPC_20151119-000002: Access is denied.

Whenever it tries to upload files from folders that require Administrator access, it fails pretty quickly. I'd like to be able to upload these files without any issue.

**Comment by ncw** [comment]
Can you run rclone as administrator?

**Comment by itsrabie** [comment]
I thought I was, but it looks like I was not. The problem is gone now.

**Comment by trajpar** [comment]
How do you run rclone as administrator?

I'm on Windows and am using the runas command.

**Comment by ncw** [comment]
I'm afraid I'm not  windows expert. Can any one help?

**Comment by zeshanb** [comment]
@trajpar 

Although "run as" should be sufficient. Following article on technet explains ways to enable Administrator account in Windows 7.

[https://social.technet.microsoft.com/wiki/contents/articles/3040.enable-disable-the-local-hidden-built-in-administrator-account-in-windows-7.aspx](https://social.technet.microsoft.com/wiki/contents/articles/3040.enable-disable-the-local-hidden-built-in-administrator-account-in-windows-7.aspx)
