### ISSUE TITLE
sync from local to drive remove files but not folders

### ISSUE THREAD

**Issue by jpambrun** [ncw/rclone#60]
Syncing from local to gDrive with "rclone sync doc gd:doc" removed files that were deleted locally as expected but left some empty folders.

**Comment by ncw** [comment]
rclone only cares about objects, directories don't actually exist on most cloud storage systems (eg s3, swift), so you are correct empy directories will be left behind.

I haven't thought of a satisfactory way round this yet though!

**Comment by ncw** [comment]
I've updated the docs about this issue here

http://rclone.org/bugs/

I'm going to close this issue as I don't have a plan for changing this at the moment.
