### ISSUE TITLE
failed to get endpoints on Android

### ISSUE THREAD

**Issue by uwe-schwarz** [ncw/rclone#600]
When filing an issue, please include the following information if
possible as well as a description of the problem.

> What is your rclone version (eg output from `rclone -V`)
v1.32

> Which OS you are using and how many bits (eg Windows 7, 64 bit)
Android N (Beta 5)

> Which cloud storage system are you using? (eg Google Drive)
Amazon Cloud Drive

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone ls remote:/

> A log from the command with the `-v` flag (eg output from `rclone -v copy /tmp remote:tmp`)
2016/07/30 17:33:34 rclone: Version "v1.32" starting with parameters ["./rclone" "-v" "ls" "acd:"]
2016/07/30 17:33:34 Failed to create file system for "acd:": failed to get endpoints: Get https://drive.amazonaws.com/drive/v1/account/endpoint: dial tcp: lookup drive.amazonaws.com on [::1]:53: read udp [::1]:33597->[::1]:53: read: connection refused

Happened also during registration, got around that by using remote authorization. There is no dns running on localhost, default DNS-Server should be 8.8.8.8.

**Comment by ncw** [comment]
How did you compile rclone?  I found rclone worked perfectly when I compiled it on my phone with Termux which I believe has some patches for the Go runtime to integrate better with Android.

**Comment by uwe-schwarz** [comment]
I used the binary from http://downloads.rclone.org/rclone-current-linux-arm.zip, I will try compiling it later.

**Comment by ncw** [comment]
Of course! I (stupidly) didn't think that someone would try running that on Android. I should probably do an android release too.  I wonder if go 1.7 has an Android OS build target yet...

**Comment by uwe-schwarz** [comment]
go get github.com/ncw/rclone fails with this:

# runtime/cgo
/data/data/com.termux/files/usr/tmp//ccJJC943.s: Assembler messages:
/data/data/com.termux/files/usr/tmp//ccJJC943.s: Warning: end of file in comment; newline inserted
# runtime/cgo
/data/data/com.termux/files/usr/tmp/go-build253962900/runtime/cgo/_obj/gcc_linux_arm64.o: In function `threadentry':
../../usr/lib/go/src/runtime/cgo/gcc_linux_arm64.c:54: undefined reference to `crosscall1'
collect2: error: ld returned 1 exit status

I don't think this is related to rclone, but I got no time for now to debug this further. Go version is 1.7beta2 android/arm64. If you have a working package I would gladly test it, otherwise this needs to wait a few more days till I find time to debug this further :)

**Comment by ncw** [comment]
I think if you then try `go install github.com/ncw/rclone` it will work.

I put my build here for you: http://pub.rclone.org/rclone-android-arm-v1.32.gz if you want to give it a go!

**Comment by uwe-schwarz** [comment]
go install fails with "undefined: syscall.Dup2", but looks definitely more promising. Your version works just fine :) (I will stick to that for now)

**Comment by ncw** [comment]
I'm going to close this for now as I'm not really supporting rclone on Android right now, but I'm glad we've made it work to some extent!

**Comment by justusiv** [comment]
OK so i set this up today at work and had it working..... I used the arm64 it worked. i was uploading. at some point i started getting the same messages "Failed to create file system for ACD" "read: connection refused" 
Like i said this was working hours ago and just stopped. :/

**Comment by szhu** [comment]
> I put my build here for you: `http://pub.rclone.org/rclone-android-arm-v1.32.gz` if you want to give it a go!

@ncw This is perfect! Can you link to it from the rclone downloads page?

**Comment by Cubox-** [comment]
As I mentionned in #674:

If anyone have this issue with DNS not being accessed for rclone's arm build on Android, create the /etc/resolv.conf file and populate it with a DNS server on your phone.
