### ISSUE TITLE
ACD: Continuous "Failed to copy: HTTP cod 504: "504 GATEWAY_TIMEOUT", no response body" error

### ISSUE THREAD

**Issue by taylorwmj** [ncw/rclone#606]
rclone version: v1.32
OS: Ubuntu Server 16.04.1
Storage: Amazon Cloud Drive
Command: `rclone sync -v --stats=10s --low-level-retries=1 --log-file=<file_path> --transfers=3 /tmp/.PlexMedia MediaServerBackup:/PMS/`
[Log File](https://github.com/ncw/rclone/files/404149/rclone_log_20160804.txt)

I've been doing an initial seeding of my home server and upload has been really good for the most part. I've been able to upload about 7.5 TB in the last week and have not had many errors (perhaps 3% of files uploading would fail). 

However, I've killed rclone syncs at various times over the last week for various reasons. However, now it appears all the files (they're starting to be the larger files as well) are beginning to not only transfer, but also receive the 504 error. Every now and again one of the files transfers without error, but I nearly will have a 1 to 1 match of files transferred to errors. All the errors are the `504 GATEWAY_TIMEOUT` errors.

Is there something that is causing this or that I can do to avert this? Thanks

**Comment by ncw** [comment]
I haven't found a way to avert this yet, sorry :-(  This has come up recently in #601 - if you look in there you'll see links to the amazon developers forum where this issue has been discussed.

There seem to be two types of errors
  * 408 REQUEST_TIMEOUT
 * 504 GATEWAY_TIMEOUT

There is speculation on the developers forum that this is caused by hashing on the remote end before the file becomes visible, but the file has actually been uploaded OK.

What I could do as a workaround is if I get one of those errors, wait for a bit (say for 1 minute) and check to see if the file is actually uploaded.  If it is then don't return an error, otherwise return the gateway error.

I've made a patch with this idea for you to try.

 http://pub.rclone.org/rclone-v1.32-16-gf18e289.zip

If you could upload a log with -v of how it works that would be much appreciated.

Thanks

Nick

**Comment by zod-melodic** [comment]
I'll try this over the weekend and let you know how it works!

**Comment by isaiah36** [comment]
I have a 56 Gb upload coming up this weekend, with many long files, so I'll give it a try and log it to file.

**Comment by ncw** [comment]
Here is a full build for all architectures

http://pub.rclone.org/v1.32-16-gf18e289%CE%B2/

**Comment by taylorwmj** [comment]
Awesome! Thanks so much for the quick fix attempt! No need to apologize about poor error handling on Amazon's end.

**Comment by isaiah36** [comment]
Ok, I installed the beta.  I was getting sleepy, so I copied and pasted the command in from a sticky note on my desktop, forgetting to add the '-v' and log file bit!  Anyway, the final output was

> 2016/08/06 12:41:21 
Transferred:   65.653 GBytes (1.389 MBytes/s)
Errors:                 0
Checks:                87
Transferred:           29
Elapsed time:  13h26m58.1s

It completed the batch in one swing at the ballpark speed of 5 Gb/hour.  By contrast my previous backup of 174 Gb took a little under 60 hours.  Judging by today's performance the beta would have completed that batch in about 35 hours.  So, I give the beta a strong thumbs up!

That NCW is such a busybee, I tell ya, always buzzing away at something or other.  :)

**Comment by taylorwmj** [comment]
@ncw tried the patch...still got an error. A bit different this time. 
[Log](https://github.com/ncw/rclone/files/405109/rclone_log_20160804.txt)

**Comment by isaiah36** [comment]
I used the Amazon desktop app to upload a 9.8 Gb file, and cancelled it after 4 hours 45 minutes, because it should have completed in less than half that time.  Then about 10 minutes later I ran a copy command with the beta on the Linux system and got this

> 2016/08/07 13:53:11 Attempt 1/3 failed with 0 errors and: HTTP code 429: "429 Too Many Requests", reponse body: {"logref":"ce687c99-5cc7-11e6-aa7b-f54206d79a82","message":"System unavailable. Please back off for a while and try again later"}

It did make the connection on automatic retry.  It is probably not a big deal but I thought I might as well report it.

**Comment by taylorwmj** [comment]
@isaiah36 why are you discussing the beta in this issue's thread? Bit confused here...

**Comment by isaiah36** [comment]
@taylorwmj because the beta was posted here, and I was alerted to this thread by NCW because it has the same sort of issue I am having with Amazon

**Comment by isaiah36** [comment]
One of the two files restarted after 37%.

**Comment by isaiah36** [comment]
Restarted again at 37% -- looks like back to square one I'm afraid.

**Comment by taylorwmj** [comment]
@isaiah36 you opened a separate issue for your bug. While both my bug and your bug may be addressed by a _patch_ (not a _beta_ per se) posted in my issue thread, for the sake of keeping things clean and orderly you need to keep your replies in your issue thread, not this one. That way, once your issue is resolved you can close it, even if mine isn't. Thanks!

**Comment by isaiah36** [comment]
Okay, Mr. Fastidious, you can have the sanctity of your thread.  :)

**Comment by ncw** [comment]
@isaiah36 Would really like to see a log with -v if possible.  I can't do anything to fix the restarting before 99% that really is Amazon's problem :-(

**Comment by isaiah36** [comment]
@ncw I will be sure to log the next attempt.

**Comment by ncw** [comment]
Here is a new attempt at a fix.  May fix the partial uploads, but may explode as it isn't very well tested.

http://pub.rclone.org/v1.32-18-gaffc483%CE%B2/

**Comment by ncw** [comment]
OK here is another attempt, a bit better tested:

http://pub.rclone.org/v1.32-18-gaffc483%CE%B2/

**Comment by ncw** [comment]
With correct URL this time: http://pub.rclone.org/v1.32-18-g29ab7ea%CE%B2/

**Comment by Conroman16** [comment]
I haven't chimed in on this issue yet but I've been following it, as I've been dealing with the same issue.  Currently testing your most recent link and will report back afterward

**Comment by Conroman16** [comment]
Well, it worked for one of the two large files.  The job is still running but here's the relevant part of the log: http://pastebin.com/raw/uA2JQjeQ

**Comment by ncw** [comment]
@Conroman16 thanks for that and for your analysis.

Looks like maybe it could do with waiting for longer than a minute for the file to appear. I don't know what to think about that 500 error - maybe it did get uploaded properly and #559 would fix it.

**Comment by ncw** [comment]
I've reworked the patch again with the following changes.  On a failed upload we
  * detect if we uploaded the file to 100% - if we didn't do nothing
  * do this for any upload error (so might get round the 500 error in @Conroman16 log)
  * increase timeout to 2 minutes - timeout might need to vary with file size?
  * made timeout configurable with `--acd-upload-wait-time` - perhaps set it large when uploading huge files?

Here is the beta: http://pub.rclone.org/v1.32-18-gf7562dc%CE%B2/

**Comment by taylorwmj** [comment]
@ncw the newest patch seems to be working. I did have one file timeout and error, even with the 2 minute timeout. I have killed that sync job, increased timeout to 4 min but it'll be a while before another file completes as am now backing up files close to 30-40 GB. I should be able to know in less than an hour.

**Comment by Conroman16** [comment]
@ncw That newest patch seems to be working for me as well, even without increasing the timeout.  [Here's the log from this round of testing](http://pastebin.com/raw/QJ8pWXbx).

Thanks for being so quick on these fixes!  I really appreciate it and I imagine @taylorwmj does as well.

**Comment by Conroman16** [comment]
@ncw I let your newest beta loose on my nightly VM backups last night with `--acd-upload-wait-time=10m0s` and it went rather well.  The only issue I ran into was a 500 error which went on for the entire 10 minute wait time and caused a re-upload.  Of course, from my understanding, that problem is on Amazon's side and not with rclone.  [Here's the full log](http://pastebin.com/raw/kXdy9UXK).

**Comment by taylorwmj** [comment]
@ncw the most recent patch seems to have resolved much of these issues. The timeout function also does seem to help. On some of the larger files, the body response would eventually timeout, but that was on Amazon's end I'm assuming as when I would go check, the file would be there. At this point, I'm going to close this. Thanks for the help!

**Comment by ncw** [comment]
I've merged this to master and it will be in the v1.33 release - thanks for your help testing.
