### ISSUE TITLE
Amazon Drive : Getting a "list of files" in a txt file ?

### ISSUE THREAD

**Issue by doplu** [ncw/rclone#607]
Hello,

Is it possible to create a list of files for Amazon Drive and save it in a txt file (example: path+filename+extension) ?
I am asking this because I find that it is very difficult for me to use the Amazon Drive' web search engine (filtering results is difficult when I need to search some keyword(s). It does not understand well "keyword").

Thanks in advance ;)

**Comment by ncw** [comment]
Hope that helps!
