### ISSUE TITLE
securing oauth2 credentials

### ISSUE THREAD

**Issue by lesaux** [ncw/rclone#609]
I am using rclone between AWS and GCP. I would like to have multiple users run rclone on a server.

I don't like the idea of sharing a service account credential json file on my server, as I wouldn't want other users to extract it and reuse it elsewhere.

I also don't like the idea of sharing `client_id`, `client_secret` and `refresh_token` with all my users. They could reuse those credentials elsewhere as well.

So I am using simple user account auth, without providing client_id and client_secret in the rclone.conf file. Rclone works fine until my token expires, at which point it fails because it cannot renew the token on it's own. 

My thoughts are to provide the auth_token through an http auth proxy, and update rclone.conf myself on regular basis.

Does anyone have thoughts on this? Am I not right in trying to hide the client_id and client_secret from my users? Is there a better approach?

**Comment by ncw** [comment]
Are you letting users use rclone directly or are you scripting it for a specific task.  If the latter then you should probably run the rclone job as a separate unix user (or even root) so the user won't be able to read any of the config.

**Comment by lesaux** [comment]
Unfortunately my users are running rclone directly.
So I have setup an "http service" on another box that responds with an auth_token, expiry and refresh_token.
I have scripted to update the rclone.conf file on regular basis. This way I am not sharing client_id and client_secret with my users.

If rclone was running in GCE, it might be possible to make it use the token found in the instance metadata server (same with an instance IAM role - or even assume role - In which case support for an external token refresh command might be handy).

My use case is very specific, and probably won't interest too many people.

**Comment by ncw** [comment]
So running rclone as root (say) doing something simple like `rclone lsd remote:` to refresh the token, then editing the rclone.conf removing the secret stuff except for the token and copying that .rclone.conf into the users home directories.  That should work just fine I would have thought.  If the users are doing really long transfers which span the hour of the token lifetime then rclone won't be able to refresh it though.

**Comment by ncw** [comment]
I hope that was of some help!
