### ISSUE TITLE
Copying: A quicker way

### ISSUE THREAD

**Issue by alexcouper** [ncw/rclone#61]
### Use Case

I'm using rclone as an incremental backup tool between a swift cluster and s3.

### Expectation

The first time the backup is run, it will take a while as it is copying lots of data for a bucket over.

Subsequent runs should be an order of magnitude quicker. seconds/minutes rather than hours/days.

### Actual results 

Bucket size: 26GB, 49907 files.
1st run: 6 hrs.
2nd run 1 hr+ (just performing the checks)

### Question
If I run ``check`` after the 1st run, I can see all the files added to the cluster since the last backup. This takes approx 60 seconds.

Looking at the docs:
  - ``check`` compares md5 + size and prints out any discrepancies.
  - ``copy`` compares modification time and size, before deciding whether to copy.

I'm assuming that the difference in performance is due to the different attributes compared. 

Is there a reason for not only ever caring about md5?

**Comment by ncw** [comment]
That would be quite a good performance optimisation...

For some remotes md5sum is easy to calculate (eg swift) and some it isn't (eg local filesystem), same with reading the modification time.

In the case of s3 and swift the md5sum is easy to fetch, whereas the modification time is harder as it requires an extra transaction - hence the difference in speed.

To implement the above I'd need to make each remote express a preference for md5sum/modification time or no preference, then `copy` and `sync` could take note of these.

I'll have a think - thanks for the idea.

**Comment by ncw** [comment]
The simplest possible thing would be to implement (from the rsync man page)

```
-c, --checksum              skip based on checksum, not mod-time & size
```

Then you could use this flag for copying between swift and s3 directly
