### ISSUE TITLE
Copying a specific object should not require "listing" permissions

### ISSUE THREAD

**Issue by jamshid** [ncw/rclone#610]
> What is your rclone version (eg output from `rclone -V`)
rclone v1.32
> Which OS you are using and how many bits (eg Windows 7, 64 bit)
macos El Capitan
> Which cloud storage system are you using? (eg Google Drive)
S3-compatible
> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

I would like copy an object that I have the full URL to, but I do not otherwise have permissions in the bucket.
```
rclone -v --dump-headers  copy example:tools/update.sh /tmp/update.sh
```

This HEADs the object update.sh just fine, but then it tries to do a listing of the "tools" bucket, which I don't have permission to do, and the copy fails.

The listing seems unnecessary. Ideally rclone would either not do the listing, or ignore any errors and just copy the object.

> A log from the command with the `-v` flag (eg output from `rclone -v copy /tmp remote:tmp`)
```
2016/08/09 19:34:56 rclone: Version "v1.32" starting with parameters ["rclone" "-v" "--dump-headers" "copy" "example:tools/update.sh" "/tmp/update.sh"]
2016/08/09 19:34:56 example: Using v2 auth
2016/08/09 19:34:56 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2016/08/09 19:34:56 HTTP REQUEST
2016/08/09 19:34:56 HEAD /tools/update.sh HTTP/1.1
Host: support.example.com
User-Agent: rclone/v1.32
Authorization: AWS 6bbfc19e5f901061805cce3fa77f18ff:kivrpkHoVolMQDz/U5QOyMbc2pM=
Date: Wed, 10 Aug 2016 00:34:56 UTC

2016/08/09 19:34:56 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2016/08/09 19:34:57 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2016/08/09 19:34:57 HTTP RESPONSE
2016/08/09 19:34:57 HTTP/1.1 200 OK
Content-Length: 2265
Content-Type: application/foo
Via: 1.1 support.example.com (foo)
X-Amz-Request-Id: 5B532AEEACE3E235

2016/08/09 19:38:08 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2016/08/09 19:38:08 Local file system at /tmp/update.sh: Waiting for checks to finish
2016/08/09 19:38:08 Local file system at /tmp/update.sh: Waiting for transfers to finish
2016/08/09 19:38:08 Attempt 1/3 failed with 0 errors and: AccessDenied: Access Denied
	status code: 403, request id: 5B532AEEACE3E235
2016/08/09 19:38:08 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2016/08/09 19:38:08 HTTP REQUEST
2016/08/09 19:38:08 GET /tools?delimiter=&max-keys=1024&prefix= HTTP/1.1
Host: support.example.com
User-Agent: rclone/v1.32
Authorization: AWS 6bbfc19e5f901061805cce3fa77f18ff:vl4XpoOMeLfpirEBgtz/odDkWxs=
Date: Wed, 10 Aug 2016 00:38:08 UTC
Accept-Encoding: gzip
...
2016/08/09 19:38:08 Local file system at /tmp/update.sh: Waiting for transfers to finish
2016/08/09 19:38:08 Attempt 3/3 failed with 0 errors and: AccessDenied: Access Denied
	status code: 403, request id: 1987A29B6F079938
2016/08/09 19:38:08 Failed to copy: AccessDenied: Access Denied
	status code: 403, request id: 1987A29B6F079938
```

**Comment by ncw** [comment]
Your analysis is spot on and I agree with you.

The reason rclone works as it does is so that it can re-use the sync machinery for single file copies.

However it ocurrs to me that these could be done in a much simpler way if just copying a single file - I don't know why I didn't think of that before!

**Comment by ncw** [comment]
Potentially all operations which makes sense on a single file can use this (eg `delete`)

**Comment by ncw** [comment]
I've fixed this in http://beta.rclone.org/v1.33-55-g98804cb/ (it will take 15 mins to appear).  Have a go and re-open the ticket if there is a problem.

Thanks

Nick
