### ISSUE TITLE
Repeated redundent "doing nothing" messages

### ISSUE THREAD

**Issue by zstadler** [ncw/rclone#611]
There are 6066 messages in one second, all saying:
```
2016/08/11 09:12:01 amazon drive root 'XXX': Token expired but no uploads in progress - doing nothing
```

I believe one message should be enough when the token expiration is detected.

> What is your rclone version (eg output from `rclone -V`)
v1.32-18-g29ab7eaβ
> Which OS you are using and how many bits (eg Windows 7, 64 bit)
Windows 10, 64 bit
> Which cloud storage system are you using? (eg Google Drive)
Amzon Drive
> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone --checksum --contimeout=10m --retries 10 --verbose --transfers 6 --log-file "XXX" sync XXX "Amazon_Drive:XXX" --max-size 5M
> A log from the command with the `-v` flag (eg output from `rclone -v copy /tmp remote:tmp`)
See above

**Comment by ncw** [comment]
Ha!  That looks like a bug ;-)  Will fix as part of the beta - thanks.

**Comment by ncw** [comment]
This is fixed now: see http://pub.rclone.org/v1.32-20-g2ebeed6%CE%B2/
