### ISSUE TITLE
Failed to open source object error

### ISSUE THREAD

**Issue by austinginder** [ncw/rclone#612]
When using the sync command to push files into Dropbox I'm getting a bunch of errors `Failed to copy: failed to open source object: open /root/Backup/image-�%80%93-150x150.jpg: no such file or directory`

I suspect it has to do the weird characters in the file names. This appears to be having issues calling the files locally and never actually attempts to push them to Dropbox. Any way to either skip these files or allow rclone to handle file names with special characters? 

> What is your rclone version (eg output from `rclone -V`)
**rclone v1.32**

> Which OS you are using and how many bits (eg Windows 7, 64 bit)
**CentOS v6, 64bit**

> Which cloud storage system are you using? (eg Google Drive)
**Dropbox**

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
**rclone -v --dropbox-chunk-size=128M --contimeout=5s --transfers=1 --log-file="$logs_path/site-$website-dropbox.txt" sync $path/$domain Anchor-Dropbox:backup/Sites/$domain**

> **It's part of a script so the variables are filled dynamically. The explicit dropbox chunk, contimeout and transfers is simply there as I was playing around with some performance issues.** 

> A log from the command with the `-v` flag (eg output from `rclone -v copy /tmp remote:tmp`)
**2016/08/12 07:25:19 wp-content/uploads/2013/07/ScreeMaggie-Sottero-?80%93-Gianna-150x150.jpg: Failed to copy: failed to open source object: open /root/Backup/domain.com/wp-content/uploads/2013/07/ScreeMaggie-Sottero-�%80%93-Gianna-150x150.jpg: no such file or directory**

See screenshot: https://cloudup.com/c7cDD8GW4z7

**Comment by ncw** [comment]
I suspect this is the issue discussed in [the rclone local docs](http://rclone.org/local/) - see the filenames section, namely that you have non UTF-8 file names.

This is easy to fix with convmv though.

**Comment by trolley** [comment]
I'm also getting this error but on Mac with one particular file named "10 - Who You Are ≠ Where You Are.m4a":

2016/08/14 20:28:40 10 - Who You Are ≠ Where You Are.m4a: Failed to copy: failed to open source object: open /Users/trolley/Documents/Ripped Music/Archived Music/Into It. Over It_/Standards/10 - Who You Are ≠ Where You Are.m4a: no such file or directory

Should I log a separate bug report?

**Comment by ncw** [comment]
@trolley that is probably a different problem - part of the never ending OSX file name normalisation saga (sigh!). Can you make a new issue please and if you could cut any paste the filename as 'ls'  sees it too then I'll compare the Unicode code points. Thanks

**Comment by trolley** [comment]
Thanks @ncw. Sorry for the delay, I just logged issue #623 for this.

**Comment by austinginder** [comment]
Yes it appears to be an encoding related. Interesting enough when I do a locale command I'm showing the file system is UTF-8. See full output. 

```
# locale
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

These files were created on another web server and were sync to the local server using lftp mirror. When I do a ls it looks like this: /wp-content/uploads/2013/07/Screenshot-?%80%93-Below-150x150.jpg. After doing `convmv -f latin-1 -t utf-8 Screenshot-?%80%93-Below.jpg --notest` the file was then named Screenshot-â%80%93-Below.jpg and successfully synced. Thanks for the tip about convmv.

**Comment by ncw** [comment]
@austinginder Great - glad it worked! Though it looks like that filename has really been through the works.  I suspect the sequence `â%80%93` actually represents the utf-8 sequence `\xe2\x80\x93` which is Unicode Character 'EN DASH' (U+2013) or `–`.
