### ISSUE TITLE
work without config

### ISSUE THREAD

**Issue by vtolstov** [ncw/rclone#616]
i want to create some plugin to put artifacts after build to cloud storage (swift/s3).
Does it possible to work with rclone without creating config (specify all via command line or via environment variables) ?

**Comment by ncw** [comment]
It isn't possible at the moment.  For S3 you can read the auth info from the environment or iam but you still need a config file.

It is a good idea though.  Perhaps the config file could be passed as an environment variable in some form?

**Comment by vtolstov** [comment]
I thinks that if all config variables from file may be specified via PREFIX that equal to profile name variable in env this is fine.
So all rclone stuff can work as before, but readed from env, after that from file...

**Comment by ncw** [comment]
This is now done.  Please see this beta

http://beta.rclone.org/v1.35-13-ge1a49ca/ (uploaded in 15-30 mins)

Here are notes from the docs

Environment Variables
---------------------

Rclone can be configured entirely using environment variables.  These
can be used to set defaults for options or config file entries.

### Options ###

Every option in rclone can have its default set by environment
variable.

To find the name of the environment variable, first take the long
option name, strip the leading `--`, change `-` to `_`, make
upper case and prepend `RCLONE_`.

For example to always set `--stats 5s`, set the environment variable
`RCLONE_STATS=5s`.  If you set stats on the command line this will
override the environment variable setting.

Or to always use the trash in drive `--drive-use-trash`, set
`RCLONE_DRIVE_USE_TRASH=true`.

The same parser is used for the options and the environment variables
so they take exactly the same form.

### Config file ###

You can set defaults for values in the config file on an individual
remote basis.  If you want to use this feature, you will need to
discover the name of the config items that you want.  The easiest way
is to run through `rclone config` by hand, then look in the config
file to see what the values are (the config file can be found by
looking at the help for `--config` in `rclone help`).

To find the name of the environment variable, you need to set, take
`RCLONE_` + name of remote + `_` + name of config file option and make
it all uppercase.

For example to configure an S3 remote named `mys3:` without a config
file (using unix ways of setting environment variables):

```
$ export RCLONE_CONFIG_MYS3_TYPE=s3
$ export RCLONE_CONFIG_MYS3_ACCESS_KEY_ID=XXX
$ export RCLONE_CONFIG_MYS3_SECRET_ACCESS_KEY=XXX
$ rclone lsd MYS3:
          -1 2016-09-21 12:54:21        -1 my-bucket
$ rclone listremotes | grep mys3
mys3:
```

Note that if you want to create a remote using environment variables
you must create the `..._TYPE` variable as above.

### Other environment variables ###

  * RCLONE_CONFIG_PASS` set to contain your config file password (see [Configuration Encryption](#configuration-encryption) section)
  * HTTP_PROXY, HTTPS_PROXY and NO_PROXY (or the lowercase versions thereof).
    * HTTPS_PROXY takes precedence over HTTP_PROXY for https requests.
    * The environment values may be either a complete URL or a "host[:port]" for, in which case the "http" scheme is assumed.

**Comment by vtolstov** [comment]
I'm configr that this works fine.

**Comment by YenForYang** [comment]
Getting an error now when setting RCLONE_VERBOSE=true for the latest beta (99):

Invalid value for environment variable "RCLONE_VERBOSE": strconv.ParseInt: parsing "true": invalid syntax

**Comment by ncw** [comment]
Yes that was an consequence of the new logging levels that the fact you can have `-vv` which is the same as `-v=2`.  Thanks for pointing it out!

**Comment by vtolstov** [comment]
i'm write drone ci plugin that uses rclone to sync artifact from builder to storage. does it possible to get list of all env variables that depends on storage ? (without to run rclone config)

**Comment by ncw** [comment]
@vtolstov not currently.  If you want to see them all you can do this

```patch
diff --git a/fs/flags.go b/fs/flags.go
index 8b221ba..05a9ecb 100644
--- a/fs/flags.go
+++ b/fs/flags.go
@@ -244,6 +244,7 @@ func optionToEnv(name string) string {
 // sets the default from the environment if possible.
 func setDefaultFromEnv(name string) {
        key := optionToEnv(name)
+       log.Printf("env for %q is %q", name, key)
        newValue, found := os.LookupEnv(key)
        if found {
                flag := pflag.Lookup(name)
```
