### ISSUE TITLE
Support for Jottacloud

### ISSUE THREAD

**Issue by jkaberg** [ncw/rclone#617]
I was wondering if you would consider implementing Jottacloud into rclone? Jottacloud is an cloud provider located in Norway/Europe, which is among the few cloud providers not located in the US (and therefor not under any obligation to comply with NSA etc.). They operate with an "unlimited" plan (in reality 10 TB as per the TOS) for private customers charging £7.50 a month. 

There is no official API documentation, altho an [official reply has been made](http://forum.jotta.no/jotta/topics/jotta_api_for_remote_storage_fetch#reply_14928642) which greenlights hacking/sniffing the API.

Thuss an unofficial [python wrapper lib](https://github.com/havardgulldahl/jottalib) has been made, which works sometimes. 

The soruce of the wrapper interface can be found [here](https://github.com/havardgulldahl/jottalib/blob/master/src/jottalib/JFS.py). Since it's unstable and not actively maintained I'm wondering if rclone would consider adopting Jottacloud into the mix? 

The lack of Linux support from Jotta has been frustrating to say the least (ref threads @ Jotta forums: [1](http://forum.jotta.no/jotta/topics/jottacloud_in_linux) [2](http://forum.jotta.no/jotta/topics/rsync_st_tte_backup_direkte_fra_nas) [3](http://forum.jotta.no/jotta/topics/can_i_use_webdav_in_jottaclioud_or_anything_like_that)).

[Jottacloud website](https://www.jottacloud.com/)

**Comment by ncw** [comment]
I'll certainly consider it - thanks for the suggestion.

**Comment by havardgulldahl** [comment]
Hello, `jottalib` maintainer here.

I just wanted to weigh in and say that while `jottalib` certainly *is* maintained (new release every 3 months), and being used daily for backups, @jkaberg is right in one regard: support for rsync like functionality is admittedly not superb. And it's not on the roadmap in the near future either, unless someone steps up to write the code.

So I certainly see the value in `rclone` support for Jottacloud.  And maybe a `go` implementation of the Jottacloud protocol would inspire something similar in `jottalib`. So if you decide to have a crack at it, @ncw, I'll be happy to help out, or answer any questions you may have.

**Comment by ziziz** [comment]
This would really make a massive improvement to jottacloud, making it comparable with the 'high-end-providers' in terms of functionality! :)

**Comment by jkaberg** [comment]
Just checked in on this an noticed it's a dupe of https://github.com/ncw/rclone/issues/307, closeing
