### ISSUE TITLE
drive: sync with pinned true

### ISSUE THREAD

**Issue by robjlg** [ncw/rclone#619]
drive: sync with pinned true

Hello, as described by gustavorochakv on issue #39, files sync on drive have versions that stays for 30 days. 

Files can be upload (update) to drive with the pinned option set to true, so, this new upload version will stay forever. ( https://developers.google.com/drive/v2/reference/files/update#parameters )

Is it possible to create an rclone command line option to make all uploaded files in the current sync command to have this pinned set true?

Thank you

**Comment by gustavorochakv** [comment]
If I remember correctly,  the update command would return an error when trying to upload a pinned revision of a file whose pinned revision limit (200 versions) has been reached. On those cases it would simply fail to create a revision, instead of creating an unpinned revision. 
Something along the lines of what is described on [this Balsamiq Q&A answer](https://support.balsamiq.com/plugins/maximumrevisions/).

As a side note, on the new Google Drive API (v3) this parameter is apparently now called keepRevisionForever. I am not entirely sure whether there has also been a behaviour change on the new API.

**Comment by robjlg** [comment]
Yes, I think this is the expected behavior.  Maybe, this v3 parameter new name is just a name change to better reflect its function.

This drive files versions feature is very good but its 30 days limit is too short. Being able to make pinned syncs at specifics times, lets say every 2 days, will allow to extend this a lot more. When a file reach this 200 limit, I will have to manually unpin some versions.

rclone could act like below:
  
rclone    sync    --pinned   /local_path    DRIVE:/remote    --log-file=pinned.log

try to upload with pinned set true.
     if error, 
          report to the log file and 
          try again with pinned set to off 

A grep at the log file should tell me which files I need to take care.

The GDRIVE program ( https://github.com/prasmussen/gdrive ) can list all versions of a file, but can not change its pinned status. I will suggest them this feature.

Thank you

**Comment by robjlg** [comment]
Yes, I think this is the expected behavior.  Maybe, this v3 parameter new name is just a name change to better reflect its function.

This drive files versions feature is very good but its 30 days limit is too short. Being able to make pinned syncs at specifics times, lets say every 2 days, will allow to extend this a lot more. When a file reach this 200 limit, I will have to manually unpin some versions.

rclone could act like below:
  
rclone    sync    --pinned   /local_path    DRIVE:/remote    --log-file=pinned.log

try to upload with pinned set true.
     if error, 
          report to the log file and 
          try again with pinned set to off 

A grep at the log file should tell me which files I need to take care.

The GDRIVE program ( https://github.com/prasmussen/gdrive ) can list all versions of a file, but can not change its pinned status. I will suggest them this feature.

Thank you
