### ISSUE TITLE
Plus signs (+) in filename mirrored as spaces or fails to mirror

### ISSUE THREAD

**Issue by devinkwok** [ncw/rclone#620]
Hi,

Thanks for all the hard work on rclone! I've been using it to make offsite backups of my data to Microsoft OneDrive, and I noticed filenames with plus signs (+) were returning `File not in Local file system at /home/devin/d/data` in my logs. It appears rclone is replacing "+" with spaces (`tes+t.txt` becomes `tes t.txt`), and failing to copy filenames that start with "+" (`+test.txt` fails to copy). I'm pretty sure "+" is a valid character in both Windows and Linux, and I had no trouble copying the same files to OneDrive manually. I also tried syncing with rclone to Google Drive, and did not have this issue.

Using a dummy folder ~/tmp, I collected the following info:

- Version: rclone v1.32
- OS: Windows 10 x64 and Ubuntu 16.04 x64
- Destination: Microsoft OneDrive (Google Drive works as expected)
- Commands: `rclone sync "/home/me/tmp" "onedrive:tmp" -v --retries 1` and `rclone copy "/home/me/tmp" "onedrive:tmp" -v --retries 1` both fail.
- Comparing the directories:

Source is `rclone ls "/home/me/tmp" -q`:
<pre>
        6 test3.t+xt
        5 test+a.txt
        6 +test.txt
        5 a/test+a.txt
</pre>
Destination `rclone ls "onedrive:tmp" -q` is missing a file, other filenames changed:
<pre>
        5 test a.txt
        6 test3.t xt
        5 a/test a.txt
</pre>
- Sample log:
<pre>2016/08/16 23:45:10 rclone: Version "v1.32" starting with parameters ["rclone" "sync" "/home/me/tmp" "onedrive:tmp" "--config" ".rclone.conf" "-v" "--retries" "1"]
2016/08/16 23:45:11 One drive root 'tmp': Modify window is 1s
2016/08/16 23:45:11 One drive root 'tmp': Reading ""
2016/08/16 23:45:11 One drive root 'tmp': Finished reading ""
2016/08/16 23:45:11 One drive root 'tmp': Waiting for checks to finish
2016/08/16 23:45:11 One drive root 'tmp': Waiting for transfers to finish
2016/08/16 23:45:12 +test.txt: Failed to copy: invalidRequest: nameContainsInvalidCharacters: Path (/LiveFolders/tmp/ test.txt) contains invalid leading character.
2016/08/16 23:45:12 +test.txt: Removing failed copy
2016/08/16 23:45:13 test+a.txt: Copied (new)
2016/08/16 23:45:13 test3.t+xt: Copied (new)
2016/08/16 23:45:13 +test.txt: Failed to remove failed copy: invalidRequest: generalException: API not found
2016/08/16 23:45:13 a/test+a.txt: Copied (new)
2016/08/16 23:45:13 One drive root 'tmp': not deleting files as there were IO errors
2016/08/16 23:45:13 Attempt 1/1 failed with 1 errors and: not deleting files as there were IO errors
2016/08/16 23:45:13 Failed to sync: not deleting files as there were IO errors</pre>

**Comment by zeshanb** [comment]
Please try your command without placing paths around quotes. Dry run option
is to see what changes will take affect without causing any changes.

rclone sync --dry-run /home/me/tmp onedrive:tmp

rclone copy --dry-run /home/me/tmp onedrive:tmp

Please try this filter option flag with your command..

rclone copy  --include *+*.* --dry-run /home/me/tmp onedrive:tmp

Regards,
Zeshan

**Comment by devinkwok** [comment]
Tried `rclone sync /home/me/tmp onedrive:tmp` and `rclone copy /home/me/tmp onedrive:tmp` without quotes, no difference. Dry run outputs without errors:
<pre>
2016/08/17 14:15:36 rclone: Version "v1.32" starting with parameters ["rclone" "copy" "/home/me/tmp" "onedrive:tmp" "-v" "--config" ".rclone.conf" "--retries" "1" "--dry-run"]
2016/08/17 14:15:37 One drive root 'tmp': Modify window is 1s
2016/08/17 14:15:37 One drive root 'tmp': Not making directory as dry run is set
2016/08/17 14:15:37 One drive root 'tmp': Reading ""
2016/08/17 14:15:37 One drive root 'tmp': Finished reading ""
2016/08/17 14:15:37 One drive root 'tmp': Waiting for checks to finish
2016/08/17 14:15:37 One drive root 'tmp': Waiting for transfers to finish
2016/08/17 14:15:37 test+a.txt: Not copying as --dry-run
2016/08/17 14:15:37 test3.t+xt: Not copying as --dry-run
2016/08/17 14:15:37 +test.txt: Not copying as --dry-run
2016/08/17 14:15:37 a/test+a.txt: Not copying as --dry-run
2016/08/17 14:15:37 
Transferred:      0 Bytes (0 Bytes/s)
Errors:                 0
Checks:                 0
Transferred:            4
Elapsed time:        1.4s
2016/08/17 14:15:37 Go routines at exit 2
</pre>
The filter options --include *+*.* excludes test3.t+xt from copying, and still fails to copy +test.txt:
<pre>
2016/08/17 14:17:15 rclone: Version "v1.32" starting with parameters ["rclone" "copy" "/home/me/tmp" "onedrive:tmp" "-v" "--config" ".rclone.conf" "--retries" "1" "--include" "*+*.*"]
2016/08/17 14:17:16 One drive root 'tmp': Modify window is 1s
2016/08/17 14:17:16 One drive root 'tmp': Reading ""
2016/08/17 14:17:16 test3.t+xt: Excluded from sync (and deletion)
2016/08/17 14:17:16 One drive root 'tmp': Finished reading ""
2016/08/17 14:17:16 One drive root 'tmp': Waiting for checks to finish
2016/08/17 14:17:16 One drive root 'tmp': Waiting for transfers to finish
2016/08/17 14:17:17 +test.txt: Failed to copy: invalidRequest: nameContainsInvalidCharacters: Path (/LiveFolders/tmp/ test.txt) contains invalid leading character.
2016/08/17 14:17:17 +test.txt: Removing failed copy
2016/08/17 14:17:17 +test.txt: Failed to remove failed copy: invalidRequest: generalException: API not found
2016/08/17 14:17:17 test+a.txt: Copied (new)
2016/08/17 14:17:18 a/test+a.txt: Copied (new)
2016/08/17 14:17:18 Attempt 1/1 failed with 1 errors and: invalidRequest: nameContainsInvalidCharacters: Path (/LiveFolders/tmp/ test.txt) contains invalid leading character.
2016/08/17 14:17:18 Failed to copy: invalidRequest: nameContainsInvalidCharacters: Path (/LiveFolders/tmp/ test.txt) contains invalid leading character.
</pre>

It looks like + is being silently replaced by spaces, and since spaces are invalid at the start of filenames on OneDrive, they cause the error `Failed to copy: invalidRequest: nameContainsInvalidCharacters: Path (/LiveFolders/tmp/ test.txt) contains invalid leading character`. Maybe it's a character encoding issue? I tested the URI path characters from [https://dev.onedrive.com/misc/path-encoding.htm](https://dev.onedrive.com/misc/path-encoding.htm), and when OneDrive replaces invalid characters like ~ with ～, rclone doesn't seem to print those codepoints correctly (`～` shows as `я╜Ю` in terminal). I haven't figured out exactly what's going on, but I've forked the project and I'll do some digging when I have time.

**Comment by ncw** [comment]
This is probably related to #218 .

The `+` being translated to ` ` means that it is to do with URL encoding going wrong.

> when OneDrive replaces invalid characters like ~ with ～

It is rclone doing those replacements. I suspect the reason why they don't display is that your terminal is not displaying UTF-8 characters.  rclone expects everything to be using UTF-8.

**Comment by zeshanb** [comment]
To confirm, Is it possible to run terminal with UTF-8.

I came across this distribution independent article online.

https://perlgeek.de/en/article/set-up-a-clean-utf8-environment

Regards,
Zeshan

**Comment by ncw** [comment]
I've fixed this in the beta

http://pub.rclone.org/v1.32-34-g037a000%CE%B2/

Which will be part of the v1.33 release

Please re-open if you find any problems with it!

**Comment by screen-saksrepo** [comment]
Hi
I'm using OneDrive connector in a Logic App and found the same issue, as of Oct. 2020. The + sign in a filename is replaced by a single space when trying to get the content. However, the filenames are well picked up when listing the folder content. See pictures attached. 

![error-getcontent](https://user-images.githubusercontent.com/39949042/95583155-a2733080-0a33-11eb-9874-6fa237a22450.png)
![listfiles](https://user-images.githubusercontent.com/39949042/95583164-a56e2100-0a33-11eb-8717-592ca0c62b10.png)
![error1](https://user-images.githubusercontent.com/39949042/95583170-a737e480-0a33-11eb-8760-80205e8c9a20.png)

Thank you
Fernando

**Comment by ncw** [comment]
@screen-saksrepo is this using rclone anywhere? If so I can't see where :-)

**Comment by C0rn3j** [comment]
```
rclone v1.53.4
- os/arch: linux/amd64
- go version: go1.15.7
```
Also running into this just now.

Filename `01 - 2 + 2 = 5.mp3` ends up like so on OneDrive
![image](https://user-images.githubusercontent.com/1641362/106622817-48fbb800-6574-11eb-98d3-a5bd0a468b48.png)


```
[0] % rclone -v --bwlimit 2M copy ~/Nextcloud/HugeFiles/Music onedrive:Music
2021/02/02 16:29:29 INFO  : Starting bandwidth limiter at 2MBytes/s
2021/02/02 16:29:45 INFO  : Radiohead - Hail To the Thief/01 - 2 + 2 = 5.mp3: Copied (new)
2021/02/02 16:29:45 INFO  : 
Transferred:        7.913M / 7.913 MBytes, 100%, 1.582 MBytes/s, ETA 0s
Checks:              2241 / 2241, 100%
Transferred:            1 / 1, 100%
Elapsed time:        15.6s


[0] % rclone -v --bwlimit 2M copy ~/Nextcloud/HugeFiles/Music onedrive:Music
2021/02/02 16:29:53 INFO  : Starting bandwidth limiter at 2MBytes/s
2021/02/02 16:30:08 INFO  : Radiohead - Hail To the Thief/01 - 2 + 2 = 5.mp3: Copied (new)
2021/02/02 16:30:08 INFO  : 
Transferred:        7.913M / 7.913 MBytes, 100%, 1.767 MBytes/s, ETA 0s
Checks:              2241 / 2241, 100%
Transferred:            1 / 1, 100%
Elapsed time:        14.7s
```

rclone keeps trying to sync it on each run.

Also have the same issue with `07 - Bangers + Mash.mp3`

Weirdly enough, after running rclone multiple times I end up in this state.

![image](https://user-images.githubusercontent.com/1641362/106624775-4d28d500-6576-11eb-909e-10a427794f6c.png)

**Comment by ncw** [comment]
@C0rn3j - can you open a new issue with this in please? Something weird is going on definitely!

**Comment by C0rn3j** [comment]
@ncw wasn't sure if I should since my issue was pretty much identical, did so now though
