### ISSUE TITLE
Local deletion fails when there is a folder inaccessible by rclone

### ISSUE THREAD

**Issue by RomeSilvanus** [ncw/rclone#624]
* Ubuntu 16.04 x64
* rclone v1.32
* Dropbox
* Command: `rclone -v sync Dropbox:Folder/ ~/www/Folder/`
* Log (last 5 lines): 
 
> 2016/08/18 15:29:41 [redacted]: Unchanged skipping
> 2016/08/18 15:29:41 Local file system at /home/user/www/Folder: Waiting for transfers to finish
> 2016/08/18 15:29:41 Local file system at /home/user/www/Folder: not deleting files as there were IO errors
> 2016/08/18 15:29:41 Attempt 3/3 failed with 2 errors and: not deleting files as there were IO errors
> 2016/08/18 15:29:41 Failed to sync: not deleting files as there were IO errors

This happens on all three attempts. On every sync.

#### I have the following situation:
I wan to sync this folder from my Dropbox account down to my server. Which works, but whenever I change something in the Dropbox and run the sync again it will not delete files and folders. 

####  What the problem is:
I also have BitTorrent Sync running on this folder to share it with other people. But BTSync requires a '.sync' folder inside the folder it is supposed to share. I made this folder manually and set the permissions to btsync:btsync (the btsync user) to avoid it being deleted by tools like rclone and other file operations like rm. rclone now wants to delete this folder because it does not exist in the Dropbox, and because it can't, it fails and doesn't delete anything at all. Not even the files I deleted from my Dropbox, it will just leave them there for me to clean up manually, which isn't very convenient with 70000> files.

The same also happens when I delete the folder contents (minus the .sync folder) and let rclone redownload all the files. Is there any way to exclude the .sync folder (or any local folder it can't access) from rclone?  (--exclude .sync did not work)

I also tried it out a second time. I made a new folder, put a .sync folder inside and changed the owner to www-data:www-data. rclone failed in the same way.

**Comment by ncw** [comment]
I think an exclude should fix it like this,

    rclone -v --exclude "/.sync/**" sync Dropbox:Folder/ ~/www/Folder/

should do it which means exclude an object called ".sync" at the sync root (hence the leading `/`) and all the stuff under it - the `/**`.

`--exclude .sync` excludes any **file** called sync anywhere in the hierarchy.

**Comment by RomeSilvanus** [comment]
@ncw This actually worked. Thanks.

Though I found another error with a different folder. I could find a few issues which talked about something similar but nothing specific to Dropbox.

> 2016/08/18 17:47:50 folder/p1 (40).jpg: Failed to copy: failed to open source object: unexpected HTTP status code 460
2016/08/18 17:47:50 Local file system at /home/user/www/Folder: not deleting files as there were IO errors
2016/08/18 17:47:50 Failed to sync: not deleting files as there were IO errors

This happens for a bunch of different kinds of files. From what I've read 460 is a file that has been blocked by Dropbox for some reason. I can view the file on the Dropbox website, but when I try to create a link to it it just says that there was an error. rclone will still try 3 times to copy these files. This does not stop it from deleting files though, but only with the --delete-before option. With --delete-during / standard behaviour it still fails to delete files.

I just though I'd let you know as there was no issue about this.

**Comment by ncw** [comment]
I think 460 means that that file possibly has a virus - if you contact dropbox they can help you apparently.

The not deleting files if there was an io error is a safety feature.

I note that rsync has the `--ignore-errors` option which means `delete even if there are I/O errors` - I could implement that.

**Comment by RomeSilvanus** [comment]
These are all video (.mp4) and picture files. Some of which I myself converted with Handbrake.
Due to the content of some of these files I'd rather not tell Dropbox to take a look at these. Maybe if I can find a safe file somewhere to show them.

An option to ignore errors and delete anyway would be useful, for me and other people I think.

**Comment by ncw** [comment]
I've put the ignore errors into #642 if you want to subscribe to that.

I'm going to close this ticket now in favour of that one.

**Comment by CottonEaster** [comment]
I have this problem, or something like it. I encountered it first on rclone 1.2. To try to fix it, I installed rclone 1.3.7. But the problem seems to persist.

The problem, more specifically, is this: I tell rclone to back up (sync) `/etc/folderA`. I do _not_ tell it to backup `/etc/folderB`, which is a system folder with special permissions. (For, I use an `--include-from` flag and file, and that file does not include that folder.) Indeed, I tell rclone explicitly (via an `--exclude-from` flag and file) to ignore `/etc/folderB`. _However_, Rclone still reports as follows:

`error reading source directory "/etc/folderB" [. . .] permission denied.`

(Perhaps it is worth adding this: RcloneBrowser does not give me to understand that  `/etc/folderB` exists already within the backup.)

Please advise!

**Comment by yecarrillo** [comment]
I found similar issues when sync google file types. Excluding the solved the problem:
`--exclude *.gdoc --exclude *.gsheet --exclude *.gdraw`

**Comment by ncw** [comment]
> Apparently, rclone also does not like Google Drive folder names with forward slashes. (I realize now this was a stupid thing to do, but I didn't know it would cause a weird error like this.)
> Renaming the folder on Google Drive made the error below go away.
> 
> ```
> 2018/12/06 15:18:13 ERROR : Local file system at /mnt/MyLocalPath: not deleting files as there were IO errors
> 2018/12/06 15:18:13 ERROR : Attempt 1/3 failed with 0 errors and: error reading source directory "Scanned Mail/Letters": directory not found
> ```
> (Also: Unsure if there is another "IO errors" issue more similar than this old one?)

If you want to refer to google files with `/` in then use this unicode equivalent `／`

**Comment by Capitalmind** [comment]
I was having this issue and only had it when I was trying to use wildcards in a filename and filenames with spaces where I was forced to use quotes as the wild card stops being a wildcard when in quotes. When I provided the exact path the sync worked fine.
