### ISSUE TITLE
Sending files to Amazon Cloud Drive

### ISSUE THREAD

**Issue by psmanek** [ncw/rclone#629]
Hi, there is a problem. When sending big files, 28GB, 20GB or 12GB with copy command rclone sends them (they appear on web ui). But when it runs again, rclone deletes random files and send them again ;/ Files are huge so it takes very long time to send them again. Any ideas?

---

rclone 1.32
OS X El Capitan
Amazon Cloud Drive
rclone --max-size=50G --stats=1s copy /Backup/Folder/Path/ amazon:Temp

**Comment by ncw** [comment]
I've fixed this already hopefully!  See the comments in #605 and the beta I posted at the end.

http://pub.rclone.org/v1.32-20-g2ebeed6%CE%B2/

**Comment by ncw** [comment]
This fix is now in the v1.33 release.
