### ISSUE TITLE
Can't copy any on cloud.

### ISSUE THREAD

**Issue by AntoWkill** [ncw/rclone#630]
Im using rclone v1.32 and Centos 7 64bit.
Im trying to upload to cloud server (OpenStack) my backups of my VPS server (all file are more than 5gb) so when i try to upload rclone divide it in segment, when the upload finish alwaise i have this error: 2016/08/19 22:01:31 vzdump-qemu-299-2016_08_13-01_18_10: Failed to copy: Object Corrupted
2016/08/19 22:01:31 vzdump-qemu-299-2016_08_13-01_18_10: Removing failed copy
2016/08/19 22:01:31 vzdump-qemu-299-2016_08_13-01_18_10: Failed to remove failed copy: HTTP Error: 409: 409 Conflict
2016/08/19 22:01:31 Attempt 1/3 failed with 1 errors and: Object Corrupted
2016/08/19 22:01:33 Swift container : Waiting for checks to finish
2016/08/19 22:01:33 Swift container : Waiting for transfers to finish
2016/08/19 22:01:36 vzdump-qemu-299-2016_08_13-01_18_10.vma.lzo: Uploading segment file "vzdump-qemu-299-2016_08_13-01_18_10/1471636896.654936342/8361892778/00000000" into "_segments"

After rclone found the corruption (i check and file is perfectly working) try again to upload it.

How i can upload without corruption?

**Comment by ncw** [comment]
Are you updating the same file over and over again?

The 409 conflict suggests it is this propblem: http://docs.openstack.org/developer/swift/overview_large_objects.html#retrieving-a-large-object

So I might need to update the manifest after an update.

Can you send a log with -v of the whole upload please?  Attach it as file.

Which cloud provider are you using? Is it vanilla openstack or ceph?

**Comment by ncw** [comment]
Can you answer the questions in the above?

Thanks

Nick
