### ISSUE TITLE
"--" shown as "—" (long dash) in headers in docs

### ISSUE THREAD

**Issue by gdubicki** [ncw/rclone#632]
(Sorry if this is not the right place to report it - I haven't found the repo from which rclone.org website is generated from.)

The docs there have "--" replaced with "—" (a long dash) in headers (at least h3s). This is misleading.

<img width="1438" alt="screen shot 2016-08-22 at 16 04 51" src="https://cloud.githubusercontent.com/assets/566632/17857515/5176c0d6-6882-11e6-8569-309ab0b37d7f.png">

**Comment by ncw** [comment]
Well spotted.  I'll fix that up, thanks

**Comment by ncw** [comment]
This will appear on the website after I release 1.33 - thanks for spotting this.

**Comment by gdubicki** [comment]
Thanks for fixing it! Actually I didn't just spot it on the website though - I copy & pasted that long dash into my code and spent some time resolving the issue while having the strangest error messages.. :P
