### ISSUE TITLE
Drive : No support for ODP

### ISSUE THREAD

**Issue by Mhardi** [ncw/rclone#634]
> What is your rclone version 

Using rclone 1.32

> Which OS you are using and how many bits

Windows 10, 64 bit

> Which cloud storage system are you using? 

Google Drive

> The command you were trying to run

rclone --dry-run --bwlimit 10M -v --config Myrclone.conf --drive-formats ods,odt,odp,svg copy PersoGdriveConf: HubicConf:

> A log from the command with the `-v` flag

2016/08/22 18:48:53 PersoGdriveConf: Saving new token in config file
2016/08/22 18:48:53 Failed to create file system for "PersoGdriveConf:": couldn't find mime type for extension "odp"

> Description of issue and - I believe - solution

I don't have MSOffice Installed, only OpenOffice. So I wanted to have ODS,ODP,ODT which are the 3 openOffice doc format https://www.openoffice.org/why/why_odf.html

But **rclone doesn't seem to recognise ODP**. Which would be in line[ with the documentation where the ods/spreadsheet format appears twice in the table but the ODP/Presentation format doesn't.](http://rclone.org/drive/) So I guess it's just a typo. But it would be cool if it could be fixed :+1: 

![2016-08-22 18_55_54-google drive](https://cloud.githubusercontent.com/assets/1762858/17874642/fe88ff24-689a-11e6-9b99-43c1403ae054.png)

**Comment by zeshanb** [comment]
OpenOffice documents need to be exported to  MS Office type files before
using rClone to transfer them to Google Drive. Due to Google Drive not
supporting Open Office file types.

In Open Office from file -> export menu.

Regards,
Zeshan

**Comment by Mhardi** [comment]
Thanks for the info, but I actually want to export them FROM drive, not TO Drive.

**Comment by zeshanb** [comment]
Most welcome. This may point to possible reason:

https://productforums.google.com/forum/m/#!topic/docs/S6IkdnuH91E

Regards,
Zeshan

**Comment by ncw** [comment]
I think @zeshanb is right - google don't seem to be offering `odp` as an export type for presentations, only `pptx`.

Note that ods appears twice in the table because there are two subtly different spellings of the mime type for it.

When I query a presentation for export formats I get this - so do ODP :-(

```javascript
  {
   "source": "application/vnd.google-apps.presentation",
   "targets": [
    "application/vnd.openxmlformats-officedocument.presentationml.presentation",
    "application/pdf",
    "text/plain"
   ]
  }
```

**Comment by Mhardi** [comment]
All right then. Sorry to have have taken up your time :)
And thanks a lot for your answers!

Mathieu.

**Comment by ncw** [comment]
No problems - sorry we can't fix this one!
