### ISSUE TITLE
Can't play video with FUSE

### ISSUE THREAD

**Issue by TARSooper** [ncw/rclone#638]
> What is your rclone version (eg output from `rclone -V`)
rclone v1.33-DEV

> Which OS you are using and how many bits (eg Windows 7, 64 bit)
Arch Linux 64bit

> Which cloud storage system are you using? (eg Google Drive)
Amazon Drive (with encryption)

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone mount test:/  /mnt/tes --debug-fuse -v

> A log from the command with the `-v` flag (eg output from `rclone -v copy /tmp remote:tmp`)
http://pastebin.com/BBjxNAJS

For whatever reason whenever I try to play a media file with mpv it just crashes after a few seconds, and meanwhile rclone starts showing the same error over and over again.

**Comment by ncw** [comment]
I see what happened - everything was going swimmingly until something else opened the file and closed it again.

This is most likely a bug as I had problems with that particular bit of code in development.

```
2016/08/25 11:30:06 [GJM] Planetarian ~Chiisana Hoshi no Yume~ - 01 [575CC989].mkv: ReadFileHandle.Open
2016/08/25 11:30:06 [GJM] Planetarian ~Chiisana Hoshi no Yume~ - 01 [575CC989].mkv: ReadFileHandle.Open OK
2016/08/25 11:30:06 fuse: -> [ID=0x4b8] Read 4096
2016/08/25 11:30:06 fuse: <- Read [ID=0x4b9 Node=0x2 Uid=1000 Gid=1000 Pid=6468] 0x1 4096 @0x4af000 dir=false fl=0 lock=0 ffl=OpenReadOnly
2016/08/25 11:30:06 [GJM] Planetarian ~Chiisana Hoshi no Yume~ - 01 [575CC989].mkv: ReadFileHandle.Open
2016/08/25 11:30:06 [GJM] Planetarian ~Chiisana Hoshi no Yume~ - 01 [575CC989].mkv: ReadFileHandle.Open OK
2016/08/25 11:30:06 fuse: -> [ID=0x4b9] Read 4096
2016/08/25 11:30:06 fuse: <- Flush [ID=0x4ba Node=0x2 Uid=1000 Gid=1000 Pid=6496] 0x1 fl=0x0 lk=0x6d3730d5a34b8c1a
2016/08/25 11:30:06 [GJM] Planetarian ~Chiisana Hoshi no Yume~ - 01 [575CC989].mkv: ReadFileHandle.Flush
2016/08/25 11:30:06 [GJM] Planetarian ~Chiisana Hoshi no Yume~ - 01 [575CC989].mkv: ReadFileHandle.Flush OK
2016/08/25 11:30:06 fuse: -> [ID=0x4ba] Flush
2016/08/25 11:30:06 fuse: <- Read [ID=0x4bb Node=0x2 Uid=1000 Gid=1000 Pid=6468] 0x1 4096 @0x4b0000 dir=false fl=0 lock=0 ffl=OpenReadOnly
2016/08/25 11:30:06 [GJM] Planetarian ~Chiisana Hoshi no Yume~ - 01 [575CC989].mkv: ReadFileHandle.Open
2016/08/25 11:30:06 fuse: -> [ID=0x4bb] Read error=EIO: Attempt to use closed file handle
2016/08/25 11:30:06 fuse: <- Read [ID=0x4bc Node=0x2 Uid=1000 Gid=1000 Pid=6468] 0x1 4096 @0x4b0000 dir=false fl=0 lock=0 ffl=OpenReadOnly
```

Thanks for the report - will attempt a fix and put a beta for you to try here.

**Comment by ncw** [comment]
Have a go with this beta and see if it fixes the problem: http://pub.rclone.org/v1.33-17-g7b80335-fuse-seek%CE%B2/

Note that seeking doesn't work over crypt yet so it might not work for you yet!

**Comment by TARSooper** [comment]
Thanks for fixing it, plays just fine now, can't wait for seeking to be done :)
