### ISSUE TITLE
rclone config text "Remote to encrypt/decrypt." can be made more clear

### ISSUE THREAD

**Issue by askielboe** [ncw/rclone#640]
When trying to follow the instructions from `rclone config`, without consulting the online documentation, it's likely that one will misinterpret the following question:

    Remote to encrypt/decrypt.
    remote> 

Unless you understand the crypt implementation of `rclone`, this could sound like you need to specify just the name of the remote (e.g. `remote> acd`). Whereas in fact you are asked to provide a remote *and* a path (`remote> acd:path`).

Specifying just the remote name will create a locally encrypted folder with that name (as explained in the [documentation on crypt](http://rclone.org/crypt/)).

I think it would make `rclone config` more intuitive for the casual user if this was changed to something like:

    Remote path to encrypt/decrypt.
    remote>

---

> What is your rclone version (eg output from `rclone -V`)

rclone 1.33

> Which OS you are using and how many bits (eg Windows 7, 64 bit)

OS X El Capitan (10.11.6, 64-bit)

> Which cloud storage system are you using? (eg Google Drive)

Amazon Cloud Drive

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

rclone config

> A log from the command with the `-v` flag (eg output from `rclone -v copy /tmp remote:tmp`)

    e) Edit existing remote
    n) New remote
    d) Delete remote
    s) Set configuration password
    q) Quit config
    e/n/d/s/q> n
    name> acde
    Type of storage to configure.
    Choose a number from below, or type in your own value
     1 / Amazon Drive
       \ "amazon cloud drive"
     2 / Amazon S3 (also Dreamhost, Ceph, Minio)
       \ "s3"
     3 / Backblaze B2
       \ "b2"
     4 / Dropbox
       \ "dropbox"
     5 / Encrypt/Decrypt a remote
       \ "crypt"
     6 / Google Cloud Storage (this is not Google Drive)
       \ "google cloud storage"
     7 / Google Drive
       \ "drive"
     8 / Hubic
       \ "hubic"
     9 / Local Disk
       \ "local"
    10 / Microsoft OneDrive
       \ "onedrive"
    11 / Openstack Swift (Rackspace Cloud Files, Memset Memstore, OVH)
       \ "swift"
    12 / Yandex Disk
       \ "yandex"
    Storage> 5
    Remote to encrypt/decrypt.
    remote> acd

**Comment by ncw** [comment]
Yes you are absolutely right.  I think I'll put an example in there too, something like

```
Remote path to encrypt/decrypt (eg remote:path/to/dir)
remote> 
```

**Comment by paranoidi** [comment]
This really burned my fingers, I ended up having local directories in the name of another remote bunch of times.

**Comment by pmow** [comment]
Thank you so much for this, I was about to open an issue because I searched and didn't find - I decided to review all open issues just in case, and presto.

In my case, specifying just the remote: allowed uploads, but then I'd find the uploads were gone after a minute or so, sometimes on the next run.  It was driving me crazy!

**Comment by ncw** [comment]
I've clarified the above in d83074ae05e8ec79ebca745c76da86894180204c and fe53caf99777944b7498423f9e7318c05e82c1c9
