### ISSUE TITLE
Rename providers with 'config'

### ISSUE THREAD

**Issue by Technifocal** [ncw/rclone#641]
With the RClone update of v1.33, I want to start using the `crypt` provider for nearly all of my `rclone` uses, but I want to keep the names of my RClone providers the same (I.E. `ACUS` or `OneDrive`), this means I have to rename my existing providers and make new `crypt` providers with the existing names to point at them.

Maybe I'm blind, but I can't find any documentation on how to do that using `rclone config`, without editing `%USERPROFILE%\.rclone.conf` (Which personally I think is a poor place to put a config file, instead of `%APPDATA%\rclone\rclone.conf`, but that's another issue entirely).

Is there a way to do this using the `rclone` interface, without deleting and reauthorizing all of my providers again?

**Comment by ncw** [comment]
You can't rename a remote at the moment no, but I think it is a good idea and not too tricky.

In the meantime editing the config file is your best bet.

**Comment by ncw** [comment]
I've done this (along with copy) - find it in

http://beta.rclone.org/v1.35-50-g2192805/ (uploaded in 15-30 mins)
