### ISSUE TITLE
Implement --ignore-errors

### ISSUE THREAD

**Issue by ncw** [ncw/rclone#642]
rsync has the `--ignore-errors` option which means delete even if there are I/O errors.  This woud be useful sometimes.

See #624 for discussion.

**Comment by bivald** [comment]
Would this also allow to continue uploading if a directory can't be read? (Permission denied) #1385

**Comment by CottonEaster** [comment]
I have a problem along the lines of those discussed on this page. I encountered the problem first on rclone 1.2. To try to fix it, I installed rclone 1.3.7. But the problem seems to persist.

The problem, more specifically, is this: I tell rclone to back up (sync) /etc/folderA. I do not tell it to backup /etc/folderB, which is a system folder with special permissions. (For, I use an --include-from flag and file, and that file does not include that folder.) Indeed, I tell rclone explicitly (via an --exclude-from flag and file) to ignore /etc/folderB. However, Rclone still reports as follows:

error reading source directory "/etc/folderB" [. . .] permission denied.

(Perhaps it is worth adding this: RcloneBrowser does not give me to understand that /etc/folderB exists already within the backup.)

Please advise!

**Comment by CottonEaster** [comment]
Sorry - I spoke to soon. There was an error in my backup setup, such that it wasn't trying to sync anything. Now that it is trying to sync things, I get problems.

Here's my setup.

**rclone command**

```
rclone \
	sync \
	-q \
	--include-from "$LISTS"/etc_include \
	--bwlimit=3M \
	--ask-password=false \
	--tpslimit "$TPSLIMIT" \
	--tpslimit-burst "$TPSLIMIT_BURST" "$sourcePath" "$destinationPath"
```

**etc_include file**

```
# etc_include
# Backups using this should have /etc as their local root

# ================
# Individual files
# ================

/rc.local
/fstab

# ===============================
# Folders
# Format: /<folder>/**
==================================

/auto.master.d/**
/autofs/**
/cron.d/**
/cron.daily/**
/cron.hourly/**
/cron.monthly/**
/cron.weekly/**
/udev/rules.d/**

# EOF
```

**Output to screen**
```
2017/08/27 02:38:09 ERROR : Encrypted drive 'erclone:/etc/': not deleting files as there were IO errors
2017/08/27 02:38:09 ERROR : Attempt 1/3 failed with 0 errors and: error reading source directory "ssl/private": failed to open directory "ssl/private": open /etc/ssl/private: permission denied
2017/08/27 02:38:13 ERROR : Encrypted drive 'erclone:/etc/': not deleting files as there were IO errors
2017/08/27 02:38:13 ERROR : Attempt 2/3 failed with 0 errors and: error reading source directory "ssl/private": failed to open directory "ssl/private": open /etc/ssl/private: permission denied
2017/08/27 02:38:15 ERROR : Encrypted drive 'erclone:/etc/': not deleting files as there were IO errors
2017/08/27 02:38:15 ERROR : Attempt 3/3 failed with 0 errors and: error reading source directory "polkit-1/localauthority": failed to open directory "polkit-1/localauthority": open /etc/polkit-1/localauthority: permission denied
2017/08/27 02:38:15 Failed to sync: error reading source directory "polkit-1/localauthority": failed to open directory "polkit-1/localauthority": open /etc/polkit-1/localauthority: permission denied
```

**Comment by TenGumis** [comment]
I want to take that issue. Can you give me more detailed description?

**Comment by ncw** [comment]
@TenGumis - great!

Here is a quick sketch

First in `fs/config.go` add a new flag `IgnoreErrors` in the `Config` struct.

In `fs/config/configflags/configflags.go` add a command line parameter for `--ignore-errors`

    --ignore-errors         delete even if there are I/O errors

In `fs/sync/sync.go` look for all the places that `fs.ErrorNotDeleting` and `fs.ErrorNotDeletingDirs` are returned.  These need masking with `fs.Config.IgnoreErrors` so the error isn't returned if `fs.Config.IgnoreErrors` is set.

In `fs/sync/sync_test.go` write a test... I would probably add an extra bit on the end of `TestSyncAfterRemovingAFileAndAddingAFileSubDirWithErrors` which sets the flag and checks the deletions happen.

**Comment by anuthaharinimn** [comment]
I'm getting this can anyone help me on this, Attempt 3/3 failed with 2 errors and: not deleting files as there were IO errors
2019/10/30 20:18:52 Failed to sync: not deleting files as there were IO errors

**Comment by ncw** [comment]
@anuthaharinimn 
> I'm getting this can anyone help me on this, while I trying to sync the data from my drive to my instance using Jenkins.

You'd probably be better posting on [the rclone forum](https://forum.rclone.org/) with a bit more detail like what command you used and log messages - thanks!
