### ISSUE TITLE
--dry-run refuses to simulate creation of a directory

### ISSUE THREAD

**Issue by ywLBhGk2noZLbY7** [ncw/rclone#649]
RClone v1.33, running:-

`rclone --dry-run move provider1:/data provider2:/data`

I get:-

`2016/08/26 12:08:11 amazon drive root 'data': Not making directory as dry run is set`
`2016/08/26 12:08:11 Attempt 1/3 failed with 0 errors and: directory not found`
`2016/08/26 12:08:11 amazon drive root 'data': Not making directory as dry run is set`
`2016/08/26 12:08:11 Attempt 2/3 failed with 0 errors and: directory not found`
`2016/08/26 12:08:11 amazon drive root 'data': Not making directory as dry run is set`
`2016/08/26 12:08:11 Attempt 3/3 failed with 0 errors and: directory not found`
`2016/08/26 12:08:11 Failed to move: directory not found`

Instead of the simulation of the directory being created, which is what I assume `--dry-run` is suppose to do.

**Comment by ncw** [comment]
Just do a `rclone mkdir provider2:/data` first and then `--dry-run` will have a directory tree to work on and show you something sensible.

**Comment by ncw** [comment]
Hopefully that answered your question
