### ISSUE TITLE
Sharing Google Drive Remotes

### ISSUE THREAD

**Issue by tarpack** [ncw/rclone#652]
I'm a new user to rclone. I setup a Google Drive remote following the [instructions](http://rclone.org/drive/). It works great.

Now I want to use the same remote on a second machine. My first thought was that I could just copy the relevant entry in `~/.rclone.conf` to the second machine, allowing both machines to share the same access token. But I see that the token has an "expiry" entry. Is that something that is updated? Meaning that if I copy the entry to a second machine, I'll eventually run into a conflict?

Is it better to just run `rclone config` on the second machine and setup the remote with the same type and name but generating a new token?

**Comment by ncw** [comment]
You can copy the config file and it will work just fine even on two machines at once. 

Rclone will refresh the token once it expires.
