### ISSUE TITLE
fuse mount options

### ISSUE THREAD

**Issue by ichbinder** [ncw/rclone#653]
Hi,
It would be relay nice if you can add the fuse mount options like --gid, --uid, --umask, --allow-other etc. .
Br
ichbinder

**Comment by ncw** [comment]
Great idea. I'd like read only too. Have any suggestions for fuse apps with a good set of command line options I can look at?

**Comment by RXWatcher1** [comment]
https://github.com/yadayada/acd_cli/blob/master/acd_cli.py

I believe thats a complete mount option. The allow-other is something I could really use. It seems like the mounts are owned by root:root and not the user who executed the mount command. Is that normal?

**Comment by ncw** [comment]
On 28 August 2016 7:27:30 a.m. RXWatcher1 <notifications@github.com> wrote:

> https://github.com/yadayada/acd_cli/blob/master/acd_cli.py
>
> I believe thats a complete mount option.

Thanks

> The allow-other is something I could really use. It seems like the mounts 
> are owned by root:root and not the user who executed the mount command. Is 
> that normal?

I didn't have any problems with Ubuntu 16.04 making and using the mounts.

Not at computer until next week so that is all I've got right now!

**Comment by RXWatcher1** [comment]
I would appreciate it if you can check if the mounts are owned by root when you get time. Mine are but I can write to them with the mount user. The issue I'm running into is my plex cant read them. Its setup as a different user/group than the user that mounted the rclone. It wont see into the mounts. If I unmount them then it will see into them so its the mount thats causing the issue. Thats where I think the allow-other would help. Thanks for all the efforts on this.

**Comment by paranoidi** [comment]
This is desperately needed, mounts are not visible in Kodi over SMB at all.

**Comment by paranoidi** [comment]
@ncw AFAIK fuse mounts are visible to user who mounted them. When trying to access them over Samba which is not running as same user those are not visible. I briefly looked over the fuse library used and it seemed like it supports the options so it should be relatively easy to add the support (my go knowledge is zero). Any chance getting this on next release? :)

**Comment by ncw** [comment]
Here is a beta with as many fuse flags as I could find. See `rclone mount -h` to see them!

http://pub.rclone.org/v1.33-13-g7be4c3a-fuse-flags%CE%B2/

**Comment by justusiv** [comment]
Just setup a mount last night that needs --allow-other. Perfect timing... will test when i get time, and report back.

**Comment by calisro** [comment]
These are what I use on various fuse mounts for various reasons.  Sone in acdcli and some in unionfs.  
allow_other
allow_root
umask
gid
uid
default_permissions
use_ino
suid
ro
nonempty

**Comment by ncw** [comment]
Yes I thought `suid` was probably not sensible on a cloud fs since rclone doesn't support custom permissions at all.

`use_ino` would mean rclone would have to make up inode numbers - might as well get fuse to do it so I think that option isn't useful.

**Comment by justusiv** [comment]
Tested --allow-other.
Working for me.

Thanks for this!

**Comment by paranoidi** [comment]
> mount helper error: fusermount: option allow_other only allowed if 'user_allow_other' is set in /etc/fuse.conf

I have option set in fuse.conf, user added into fuse group ... no idea why that happens

**Comment by paranoidi** [comment]
Ah, ubuntu has incorrect permissions as default and message was not indicating read issues. Works perfectly now!

**Comment by ncw** [comment]
Thanks for testing - I'll merge this to master now.
