### ISSUE TITLE
Subdirectories specified when using rclone command are ignored

### ISSUE THREAD

**Issue by rourke750** [ncw/rclone#655]
When filing an issue, please include the following information if
possible as well as a description of the problem.  Make sure you are
using the [latest version of rclone](http://rclone.org/downloads/).

> What is your rclone version (eg output from `rclone -V`)
rclone v1.33

> Which OS you are using and how many bits (eg Windows 7, 64 bit)
ubuntu 16.04 64 bit.

> Which cloud storage system are you using? (eg Google Drive)
Amazon cloud drive.

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone ==transfers=5 sync /home/rourke/Desktop/test/ secret:test/

> A log from the command with the `-v` flag (eg output from `rclone -v copy /tmp remote:tmp`)
rclone/rclone -v --transfers=5 sync /home/rourke/Desktop/test/ secret:test
2016/08/27 09:49:51 rclone: Version "v1.33" starting with parameters ["rclone/rclone" "-v" "--transfers=5" "sync" "/home/rourke/Desktop/test/" "secret:test"]
2016/08/27 09:49:52 amazon: Saving new token in config file
2016/08/27 09:49:54 Encrypted amazon drive root 'backup/movies/0p5ohk94qrcijn5dqodttaag80': Modify window not supported
2016/08/27 09:49:55 amazon drive root 'backup/movies/0p5ohk94qrcijn5dqodttaag80': Reading ""
2016/08/27 09:49:55 amazon drive root 'backup/movies/0p5ohk94qrcijn5dqodttaag80': Finished reading ""
2016/08/27 09:49:55 Encrypted amazon drive root 'backup/movies/0p5ohk94qrcijn5dqodttaag80': Waiting for checks to finish
2016/08/27 09:49:55 Encrypted amazon drive root 'backup/movies/0p5ohk94qrcijn5dqodttaag80': Waiting for transfers to finish
2016/08/27 09:49:55 fsdfsdfds: Copied (new)

Config that i set up had type = crypt, remote = amazon:backup/movies, filename_encryptions = standard, then both a password and salt password.

**Comment by ncw** [comment]
It looks like it is working to me. 

It copied a single file  fsdfsdfds into the remote. 

Note that the directory path "test" has been encrypted to 0p5ohk94qrcijn5dqodttaag80 which is as it should be. 

If you do

    rclone ls secret: 

What do you see? Hopefully you'll see "test/fsdfsdfds" in the output. 

If you done want the "test" part encrypted then you need to make a new Crypt with that in the remote.

**Comment by rourke750** [comment]
Ah I see.  Thanks for checking it out.

**Comment by ncw** [comment]
No problems. I should probably attempt to make this clearer in the docs. 

I'm going to reopen this ticket to remind me.
