### ISSUE TITLE
Support HTTPS on downloads

### ISSUE THREAD

**Issue by emilstahl** [ncw/rclone#657]
```
$ curl -I https://downloads.rclone.org/rclone-current-linux-amd64.zip
curl: (51) Unable to communicate securely with peer: requested domain name does not match the server's certificate.
```
😒

**Comment by ncw** [comment]
Will have a think on the best way forward. I think there is an https domain name I could advertise. 

Note you can also download the releases from github which will be https.

**Comment by ncw** [comment]
You can find the downloads with https here: https://downloads-rclone-org-7d7d567e.cdn.memsites.com/

And also here: https://github.com/ncw/rclone/releases/latest
