### ISSUE TITLE
mound only as root

### ISSUE THREAD

**Issue by tola5** [ncw/rclone#658]
the problem are when I mound it are only as root and then my docker plex server cant read it and SMB also cant see any file only from cmd can see the files :-(

> What is your rclone version (eg output from `rclone -V`)
1.33
> Which OS you are using and how many bits (eg Windows 7, 64 bit)
Unraid
> Which cloud storage system are you using? (eg Google Drive)
amazon cloud drive  (ACD)
> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone mount secret:/Plex/ /mnt/user/Tower/test/

sorry if this it not the place are new on github

**Comment by ncw** [comment]
I'm away at the moment. I'll investigate when I get back.

**Comment by ichbinder** [comment]
the problem is also reported here: #653

**Comment by ncw** [comment]
Yes this is a duplicate of #653 - please subscribe to that issue for updates.
