### ISSUE TITLE
Duplicate issue with GDrive !!!

### ISSUE THREAD

**Issue by vincegre** [ncw/rclone#659]
Hi,

I encounter the issue of Duplicate file detected error with GDrive. I do only sync from my NAS to Drive and if I check duplicate rclone indicates I find them well on Drive. Is there a way to resolve that problem ? out of emptying directories concerned on Drive and doing the sync again ???

Thanks

Vincèn

> What is your rclone version (eg output from `rclone -V`)
> 1.32
> 
> Which OS you are using and how many bits (eg Windows 7, 64 bit)
> FreeNAS 9.3 (FreeBSD 64 bits)
> 
> Which cloud storage system are you using? (eg Google Drive)
> Google Drive unlimited (Google Apps)
> 
> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
> rclone sync /localstorage /Drive:remotedirectory
> 
> A log from the command with the `-v` flag (eg output from `rclone -v copy /tmp remote:tmp`)
> [rclone.backup.tar.gz](https://github.com/ncw/rclone/files/444249/rclone.backup.tar.gz)

**Comment by vincegre** [comment]
No solution ??

**Comment by ncw** [comment]
I'm away at the moment with limited Internet (GPRS!) will study your issue 
when I get back next week.

**Comment by vincegre** [comment]
Héhé sure, no problem ;) Thanks

**Comment by calisro** [comment]
Cant you run rclone's dedupe?  You can try with the --dry-run option first to see what it would find.  Maybe I misunderstood though.

rclone dedupe

**Comment by ncw** [comment]
I looked through your log file and I didn't see any errors?  Did you log stdout and stderr to different places?  (By default the output for `-v` goes to stdout whereas the log messages go to stderr.)  You can use the `--log-file` option to get them in the same place.

**Comment by ncw** [comment]
Hopefully `rclone dedupe` solved your problem.  If not please re-open!
