### ISSUE TITLE
ubuntu 14.04 error on install

### ISSUE THREAD

**Issue by tagplus5** [ncw/rclone#660]
When filing an issue, please include the following information if
possible as well as a description of the problem.  Make sure you are
using the [latest version of rclone](http://rclone.org/downloads/).

> What is your rclone version (eg output from `rclone -V`)
error on install
> Which OS you are using and how many bits (eg Windows 7, 64 bit)
ubuntu server 14.04, 64bit
> Which cloud storage system are you using? (eg Google Drive)
none
> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
none
> A log from the command with the `-v` flag (eg output from `rclone -v copy /tmp remote:tmp`)
none

go 1.6
on install
```
go get github.com/ncw/rclone
```
i get error
```
go/src/github.com/ncw/rclone/googlecloudstorage/googlecloudstorage.go:666: undefined: googleapi.SetOpaque
```

**Comment by mitchellwrosen** [comment]
Grepping the codebase for "googleapi", I see no specification of a version range. I suppose that means that the latest commit on master is used when building? So then this package breaks every time any upstream third party API makes a backwards-incompatible change? Is that how the `go` toolchain works?

**Comment by smihir** [comment]
@mitchellwrosen go get downloads the named packages from the HEAD of the default branch of the repository but does not update a package which is locally present unless you specify the[ -u flag](https://golang.org/cmd/go/).

To make sure that a package does not break every time any upstream 3rd party API makes an incompatible change it should make use of **Vendoring** by adopting any one of the available [management tools](https://github.com/golang/go/wiki/PackageManagementTools).

**Comment by mitchellwrosen** [comment]
Has rclone been equipped with such a vendoring tool? The instructions in
the readme simply say to use "go get".

**Comment by smihir** [comment]
rclone build process does not support vendoring and so the process is broken for anyone who does not have the correct version of "googleapi".

But if you want to use rclone you can download the pre-compiled packages for your platform from [here](https://github.com/ncw/rclone/releases)

**Comment by mitchellwrosen** [comment]
Thanks!

**Comment by simos** [comment]
There was a change in "googleapi" a few days ago that caused this issue.
The result is that SetOpaque is deprecated (well, not supported any more)
and RawPath is required instead.

See report #663
