### ISSUE TITLE
Adding command line options to config file

### ISSUE THREAD

**Issue by chepurko** [ncw/rclone#661]
When filing an issue, please include the following information if
possible as well as a description of the problem.  Make sure you are
using the [latest version of rclone](http://rclone.org/downloads/).

> What is your rclone version (eg output from `rclone -V`)
> rclone v1.32
> 
> Which OS you are using and how many bits (eg Windows 7, 64 bit)
> Ubuntu 16.04 64-bit
> 
> Which cloud storage system are you using? (eg Google Drive)
> Google Drive
> 
> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
> `rclone sync`
> 
> A log from the command with the `-v` flag (eg output from `rclone -v copy /tmp remote:tmp`)

Does `rclone` support adding command line options into the `.rclone.conf` file? For example, I'd like `rclone` to always use `--drive-formats ods,odt` instead of typing it in every time. So does the configuration file work just like a regular key/value list with the command-line options as well?

**Comment by chepurko** [comment]
Any word on this? Or is the .rclone.conf file only for the initial setup configurations (type, token, etc.)?

**Comment by ncw** [comment]
It doesn't support it yet, but it is a great idea. 

What I want to do is make any of the command line options for a remote work in the config file too. Thus would need a little bit of reorganisation but isn't too tricky.

**Comment by ncw** [comment]
Note to self: an alternative would be to have an :env: section with environment variables to set in - that might work quite well.

**Comment by cal2195** [comment]
Allowing all config options to be present in the one file would make life a lot easier when switching system and reducing the lenght of commands! :smile:

**Comment by cjnaz** [comment]
Bump.

Note that the [current documentation](https://rclone.org/docs/#config-file) "_You can set defaults for values in the config file on an individual remote basis._" kinda suggests that this is supported now (in 1.42).  It is suggested to run through rclone config "_to discover the name of the config items that you want._"  I'm wanting to set/change the --drive-formats default for docs to .otd, which I gather is not (currently) supported in the config file, and I wont discover the correct config string by running through rclone config.

The documentation could be clarified.  Is it concise to say that _the config file may be edited (only) for the items listed for the given remote, as created by rclone config_?

I've tried several invalid items in the config file, with no error messages.  A feature/bug may be to output error messages for invalid lines in the config file.

**Comment by ncw** [comment]
@cjnaz I'm currently working on unifying the backend config so you will be able to configure everything about each backend via command line flag, environment variable or config file.

If you want to see the definitive list of what goes in the config file then you can use

    rclone config providers

> I've tried several invalid items in the config file, with no error messages. A feature/bug may be to output error messages for invalid lines in the config file.

It is difficult to provide warnings and maintain both forward and backwards compatibility, but not impossible.

**Comment by jikamens** [comment]
Thanks @ncw!

**Comment by cjnaz** [comment]
Perhaps a default quiet behavior when unsupported config switches are found, and a --config-lint switch to output invalid lines for debug/validation?

**Comment by ncw** [comment]
All the backend config items are now addable to the config file.  You can use `rclone config` then see the advanced config to see them.

There is more work to do to add the non-backend config, but this issue is clearly about the backend config, so I'm going to close it now.

**Comment by YenForYang** [comment]
Any possibility of supporting options globally?

Like `--fast-list` (which could be considered a missing option for `drive` file config) or `--suffix`.

Or even on a "remote" level -- like setting `chunk_size` and `upload_cutoff` for all `drive` type remotes.

**Comment by ncw** [comment]
> Any possibility of supporting options globally?
> 
> Like `--fast-list` (which could be considered a missing option for `drive` file config) or `--suffix`.

I'm planning to do that in this issue #2697
 
> Or even on a "remote" level -- like setting `chunk_size` and `upload_cutoff` for all `drive` type remotes.

You can do this with environment variables `RCLONE_DRIVE_CHUNK_SIZE` but you can't set those in the config.  However I see no reason why those options couldn't be set in the "global config"
