### ISSUE TITLE
rclone over ssh ?

### ISSUE THREAD

**Issue by kmatt** [ncw/rclone#662]
Is it in scope for this project to copy to a remote server over an ssh connection? I did not find a syntax for that operation in the docs.

This would be duplication of functionality already available in rsync, but in an environment where files are moved to both cloud and local-network hosts, standardizing on rclone would be useful.

I do use rclone to move files to internal servers that publish NFS mounts, but not all do.

**Comment by gnewton** [comment]
+10

**Comment by 0xmohit** [comment]
https://github.com/ncw/rclone/blob/master/notes.txt#L25

**Comment by kmatt** [comment]
Already in the todo list.

**Comment by hailthemelody** [comment]
Pardon the necrobump, but for those searching I've been using `sshfs` (ssh file system) to map remote systems to local drives as a workaround until this feature is implemented. It's been working great.

**Comment by ncw** [comment]
@hailthemelody if you try the latest beta, you'll find it has sftp support which works over ssh.  Most servers which support ssh seem to support sftp over ssh.

**Comment by hailthemelody** [comment]
Thanks for this!
