### ISSUE TITLE
Build failure due to googleapi dependency

### ISSUE THREAD

**Issue by rmdashrf** [ncw/rclone#663]
Package `github.com/ncw/rclone/googlecloudstorage` has a dependency on `google.golang.org/api/googleapi`.

`google.golang.org/api/googleapi` removes the `SetOpaque` method [in this changeset](https://code-review.googlesource.com/#/c/7112/) .

This causes the following build error:

```
go version go1.7 linux/amd64
go install -v ./...
github.com/ncw/rclone/googlecloudstorage
# github.com/ncw/rclone/googlecloudstorage
googlecloudstorage/googlecloudstorage.go:666: undefined: googleapi.SetOpaque
Makefile:7: recipe for target 'rclone' failed
make: *** [rclone] Error 2
```

**Comment by simos** [comment]
Here is the bug report for the change,
https://github.com/google/google-api-go-client/issues/161

RawPath can be used instead of "SetOpaque".

**Comment by rmdashrf** [comment]
Sorry, did not see that you already had filed an issue for this. Closing this duplicate.
