### ISSUE TITLE
Amazon drive, overwrite?

### ISSUE THREAD

**Issue by pmwoodward3** [ncw/rclone#664]
Hey, 

I'm getting a ton of 409 (duplicate name) errors using rclone and Amazon drive.

Is there anyway that rclone can get a flag to overwrite files that have the same name on Amazon Drive if they are different? Because for the life of me I can't seem to find a way to make that happen.

Thanks

**Comment by ncw** [comment]
Rclone is supposed to do that automatically.

However amazon drive's directory listings are very eventually consistent 
which make it hard.

Do you have lots of files which differ only by case? Eg FILE .TXT and 
file.txt that can cause the same problem as AD is case insensitive.

**Comment by pmwoodward3** [comment]
I actually am running into this issue with my media files. Typical situation is after upgrading a file, so lets say I have some series thats 720p and I replaced it with the bluray version at 1080p, but the name remains the same so plex doesn't panic, ei Series S01EXX.Whatever. The next time I sync to Amazon Drive it gives me the 409 error saying there is already something with that name.

That's my use case, am I doing something wrong?

**Comment by ncw** [comment]
Sound fine, but check you got the case exactly the same. If you didn't 
rclone will think they are different files and amazon will give that error.

**Comment by ncw** [comment]
I'm going to close this now - please re-open if you find out more
