### ISSUE TITLE
Is it possible to get file download link with rclone from Google Drive?

### ISSUE THREAD

**Issue by xpresservers** [ncw/rclone#667]
Hi,

I am storing my backups to Google Drive using rclone. I want to know if it is possible to get the sharable link with rclone or not. I mean file sharing link. I am generating an output email after backup transfer to Google Drive with the help of rclone and want to include direct download link in email.

Regards,
Hassan

**Comment by zeshanb** [comment]
Shareable links are related to Google drive's web interface. Download links
are available for Google cloud storage, a separate storage service more
suitable for this purpose.

Would require implementation of an added feature for rClone to export
public accessible links and file names to log file.

Regards,
Zeshan
