### ISSUE TITLE
Feature Request: .gitignore style exclusion/inclusion rules

### ISSUE THREAD

**Issue by dolkensp** [ncw/rclone#671]
I would like to be able to add **.rcignore** or similar files to directories and have the rules treated in much the same way as .gitignore files in git.

This has the potential to greatly simplify the command line execution of rclone, as no complicated exclusion/inclusion lists are required as command line arguments.

**Comment by ncw** [comment]
Is there any precedence for this in a different tool? I'm a great one for standards to follow if there are any!

**Comment by ncw** [comment]
I think this feature would complicate rclone's internals too much, sorry, so I'm going to close this issue.

**Comment by fenollp** [comment]
Don't know of any standard solution, on the contrary I believe no major client (Dropbox, Copy.com, SyncThing, OwnCloud, ...) support .gitignores (or similar). Symlinks is the other dodgy subject.

The closest thing to a standard is http://konolige.com/dbignore/ but really it's an unmaintained platform-specific hack that used to work :)

It would be great to have this be part of rclone! I have been looking for this for years and if time is lacking maybe point us to where we should start to implement this.

Thanks

**Comment by fenollp** [comment]
Adding `--exclude-from-gitignore` could be a modified `--exclude-from` that recursively adds rules found in `.gitignore` files, respecting the gitignore rules format. Being careful not to leak rules out of scopes and all.

A `--exclude-from-rcloneignore` is thus just `--exclude-from` plus the recursive detection of `.rcloneignore` files.

**Comment by ikzk** [comment]
Any plan for this feature now? To add such support before synchronization we can simply traverse the directory to find all `.rcloneignore` and generate a `--exclude-from` file from them? It seems to me in this way we only need little change to exsiting code.

**Comment by ncw** [comment]
@ikzk rclone now has this flag which I think is what you want.  It got fixed recently so I recommend trying with [the latest beta](https://beta.rclone.org).

    --exclude-if-present string           Exclude directories if filename is present

**Comment by dolkensp** [comment]
@ncw that's slightly different, in that you're excluding entire directories.

I was more looking at a way to add exclude lists at a directory level.

So if you back up a video project, you might ignore temporary files for that project by adding an rcignore file.

If you backup a .net project, you'd have a similar copy to your gitignore file

Etc

I see you responded to me way back when I first raised the ticket. .gitignore is the exact syntax I was thinking. I wrote my own tool similar to rclone before finding rclone, which obeyed those same files.

Just gives flexibility around backing up an entire directory tree, but allowing smaller modules/projects/etc within add filters where necessary, without affecting the entire tree.

**Comment by ikzk** [comment]
@ncw Thanks. In my case I have some PKGBUILDs in a directory and the packages generated by those PKGBUILDs. I only want to backup PKGBUILDs, and `--exclude-if-present` cannot do this..

**Comment by ncw** [comment]
I think what I'd do is write a `.gitignore` files to rclone --filter-from converter.  That would be reasonably straight forward I think and see how that looked...

**Comment by fenollp** [comment]
Maybe https://github.com/monochromegane/go-gitignore can help?

**Comment by westofer** [comment]
anyupdates?

**Comment by ncw** [comment]
Anyone want to have a go at this?

**Comment by fanzhuyifan** [comment]
Any updates? I am also quite interested in this feature and I can try to find some free time in the next two months. (And learn Go first) In the mean time, how do you think this feature should combine with the existing filtering rules of rclone?

**Comment by fanzhuyifan** [comment]
I have been thinking about this and right now I have some questions. Supporting .rcignore while syncing from a local directory would make a lot of sense, but what about when syncing from a remote directory in cloud storage to a local directory? The .rcignore files are all in the cloud, so we have to fetch them if we want them to have any impact. But if they ignore themselves, then we would have to delete them again after fetching them, which seems a bit cumbersome. What are people's thoughts on this?

**Comment by fanzhuyifan** [comment]
When syncing from a local path, an alternate way would be to use a separate tool to generate a list of files to sync, and then pipe that list to rclone. I think that would be better than having the functionality build into rclone itself, since the two functions are clearly separable,  it is easier to support, and allows for more customization.

**Comment by peter-dolkens** [comment]
To answer your previous question I'd simply make .rcignore an illegal
ignore - .rcignore files are *always* synced, precisely to prevent this
complexity.

Otherwise you get the issue of what files to copy back down too.

I'd suggest that rclone should look for an .rcignore file in any
source/destination - resolve any conflicts, and only then should it proceed
to iterate the remaining files in the directory.

**Comment by fanzhuyifan** [comment]
Could you elaborate a bit on what it means to consider .rcignore files in a destination?

**Comment by fanzhuyifan** [comment]
Right now I am pretty convinced that using a separate tool to generate a list of files from .rcignore files and passing that list to rclone via --include-from would be a good solution. It is easily implemented (no changes are needed to rsync at all) and cleanly separates parsing the rules from the main rclone program. Is there any reason why we choose to modify rclone itself in favor of that simple solution?

**Comment by xlambein** [comment]
In case anyone finds this and is looking for a solution that relies on `.gitignore` files, I made a script that generates a list of ignores in the format of `--filter-from`:
```bash
#!/bin/sh

gitignores=$(fd -IH '^\.gitignore$' "$@")

for path in $gitignores
do
  for exclude in $(cat $path | xargs -I{} fd -IH --glob {} $(dirname $path))
  do
    pattern=$(echo $exclude | sed -e "s#^$@##")
    if [[ -d "$exclude" ]]
    then
      echo "- $pattern/**"
    else
      echo "- $pattern"
    fi
  done
done
```
It takes a path as single argument, into which it recurses to find all `.gitignore`s.  This should be re-run everytime you do a backup.  I have a script that does something like this:
```bash
gitignore_excludes=$(mktemp)

./gitignore-to-rclone.sh my/folder/to/backup > $gitignore_excludes

rclone sync --filter-from $gitignore_excludes \
  my/folder/to/backup \
  remote:backup
```

**Comment by xax** [comment]
> Is there any precedence for this in a different tool? I'm a great one for standards to follow if there are any!

See `rsync`'s **-F** option, which ”*look[s] for per-directory `.rsync-filter` files that have been sprinkled through the hierarchy and use their rules to filter the files in the transfer“*. [→ https://download.samba.org/pub/rsync/rsync.html ]

rclone could re-use the very same files.

**Comment by brianjmurrell** [comment]
> When syncing from a local path, an alternate way would be to use a separate tool to generate a list of files to sync, and then pipe that list to rclone. I think that would be better than having the functionality build into rclone itself, since the two functions are clearly separable, it is easier to support, and allows for more customization.

Except now you are traversing the whole tree to be backed up twice.  Once to enumerate the excludes and then again to do the operation.

Since an `.rcignore` file in a given directory only affects that directory and it's children, it doesn't seem like it ought to complicate things overly so to read the file while processing the tree.

**Comment by jonathanMelly** [comment]
> Is there any precedence for this in a different tool? I'm a great one for standards to follow if there are any!

[Kopia](https://kopia.io/), a great backup tool that integrates well with rclone uses that : https://kopia.io/docs/advanced/kopiaignore/

For me it is the easiest way of getting rid of messages like
`firefox/profile/parent.lock: Failed to calculate src hash`

As i just have to put a .xxxignore file in firefox dir with an entry "parent.lock" and that's it !
