### ISSUE TITLE
Cannot encrypt and copy to B2

### ISSUE THREAD

**Issue by mchouque** [ncw/rclone#673]
Hello,

I'm trying to copy a directory tree to an encrypted folder on B2 and it fails miserably.

I know it's not the encryption part because I can upload small files. Given the trace, I guess it could have to do with big files? My tree has both small and large (around 600M) files.

Let me know if you need more info...

My config is as follow:
[b2]
type = b2
account = xxx
key = yyyyy
endpoint = 

[b2_encrypted]
type = crypt
remote = b2:some-folder
filename_encryption = standard
password = wwwwww
password2 = yyyyyyyy

#### What is your rclone version (eg output from `rclone -V`)
v1.33-2-g140a3d0
(used that one to go around this bug https://github.com/ncw/rclone/issues/644)

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Fedora 24, x86_64, 64 bits

#### Which cloud storage system are you using? (eg Google Drive)
Backblaze B2

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone -v copy . b2_encrypted:

#### A log from the command with the `-v` flag (eg output from `rclone -v copy /tmp remote:tmp`)

I uploaded the trace as a gist: https://gist.github.com/mchouque/5429794a1ce2bc5b2334c9c5be98e2e6

**Comment by ncw** [comment]
I'm away at them moment with limited Internet connection. I'll study this 
early next week.

**Comment by mchouque** [comment]
No rush but thanks for the update. I'll look at it in the meantime: a good reason to learn more about go.

**Comment by ncw** [comment]
I've fixed this in this beta

http://pub.rclone.org/v1.33-6-g2eaac80%CE%B2/

Please re-open if it still causes problems

**Comment by mchouque** [comment]
Works perfectly, thanks about that!
