### ISSUE TITLE
Just a Question. Do you have this for Androids

### ISSUE THREAD

**Issue by MrsChubsCollins** [ncw/rclone#674]
When filing an issue, please include the following information if
possible as well as a description of the problem.  Make sure you are
using the [latest version of rclone](http://rclone.org/downloads/).

> What is your rclone version (eg output from `rclone -V`)
> 
> Which OS you are using and how many bits (eg Windows 7, 64 bit)
> 
> Which cloud storage system are you using? (eg Google Drive)
> 
> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
> 
> A log from the command with the `-v` flag (eg output from `rclone -v copy /tmp remote:tmp`)

**Comment by zeshanb** [comment]
Not sure. Found this neat article on how to allow usage of Go package in
Android and iOS:

https://godoc.org/golang.org/x/mobile/cmd/gobind

Regards,
Zeshan

**Comment by justusiv** [comment]
I have used rclone on android using the following app.
https://play.google.com/store/apps/details?id=com.termux&hl=en

**Comment by ncw** [comment]
You can compile rclone on Android using Termux and use it from the command 
line there.

I'm not currently building releases for Android though so you'll have to 
build it yourself.

**Comment by justusiv** [comment]
Just thought i would through in a quick update. I just used the compiled one for linux arm and it worked for a few hours but then started throwing errors. See this issue.
https://github.com/ncw/rclone/issues/600
Long story short its hit or miss right now.

**Comment by ncw** [comment]
The ARM linux one doesn't have the right android bits in in.  android != linux especially when it comes to system services like DNS.

You can try this one: http://pub.rclone.org/rclone-android-arm-v1.32.gz

Or build one from source with Termux.

**Comment by justusiv** [comment]
Just thought i would throw out some more information... Like i said i had this working, then it stopped then it started again. I found the secret sauce(short term).
If i have my mobile hotspot activated it works. (DNS issue that your talking about? that hotspot fixes?!?)
Reboot phone throws the same error as always. "read: connection refused" activate hotspot, works fine.

**Comment by zeshanb** [comment]
Usually preferred to isolate the OS related and hardware issues first. By
getting a generic Android phone with standard Android OS without the
manufacturer "icing".

When reporting these types of issues one needs to mention the phone
hardware maker, model of phone, and Android OS version name and number.

**Comment by zeshanb** [comment]
This project already on this issue:

https://github.com/CloudRail

Unfortunately rClone doesn't seem to be intended for use with mobile
devices.

Regards,
Zeshan

**Comment by justusiv** [comment]
I am just reporting my findings. I have it working so....
My phone is a Nexus 6P running MTC20F (latest Marshmellow)
ncw analysis of dns being broken seems legit. For some reason toggling on Hotspot resolves the issue for me.

**Comment by ncw** [comment]
I built the current code with termux and uploaded the result - try this.  It should work better than the linux-arm version.

http://pub.rclone.org/rclone-android-arm-v1.33.gz

I should probably write some instructions on how to do this - it isn't too hard.

**Comment by justusiv** [comment]
Just tried the rclone-android-arm-v1.33.gz i had no difference in results.
Works fine with hotspot on. gives the "read: connection refused" when off.
Not sure if it matters but the way i am doing it is i have to type su into termux then i copy rclone to /data/data/com.termux/file/usr/bin
then chmod 777 rclone 
then i can use it as long as i run su on ther terminal first. 
Not sure if anything i am doing would create the error i am seeing.

**Comment by justusiv** [comment]
Just to keep adding info.
I setup rclone without su and had the same issue.

**Comment by calisro** [comment]
For anyone with this running, were they able to use the fuse mount via rclone?  My phone isn't rooted so I couldn't test it.  The actual syncing and such seems to work ok on android so far.

**Comment by justusiv** [comment]
I have not. Will list error in a few.

**Comment by justusiv** [comment]
Just thought i would add. I added a second storage location on google drive. Same issue. blah blah connection refused.
Anything i saw related to this was only on Amazon Cloud Drive so i just wanted to make a note that i am seeing it on other storage.

**Comment by justusiv** [comment]
Just another thing i noticed. I setup acd_cli for grins just to test on my android device using termux. It works just fine without my hotspot being on.

**Comment by Cubox-** [comment]
If anyone have this issue with DNS not being accessed for rclone's arm build on Android, create the /etc/resolv.conf file and populate it with a DNS server on your phone.
Thanks for pointing that rclone was working with hotspot on.

**Comment by ncw** [comment]
We now have [how to build rclone for termux in the wiki](https://github.com/ncw/rclone/wiki/rclone-on-Android-with-Termux) so I'm going to close this question.
