### ISSUE TITLE
undefined SetOpaque - nothing installed in $GOPATH/bin

### ISSUE THREAD

**Issue by nigelhorne** [ncw/rclone#676]
When filing an issue, please include the following information if
possible as well as a description of the problem.  Make sure you are
using the [latest version of rclone](http://rclone.org/downloads/).

> What is your rclone version (eg output from `rclone -V`)
rclone: not found

> Which OS you are using and how many bits (eg Windows 7, 64 bit)
Debian Jessie

> Which cloud storage system are you using? (eg Google Drive)
Google Drive

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
$ go get github.com/ncw/rclone

> A log from the command with the `-v` flag (eg output from `rclone -v copy /tmp remote:tmp`)
# github.com/ncw/rclone/googlecloudstorage
../go/src/github.com/ncw/rclone/googlecloudstorage/googlecloudstorage.go:666: undefined: googleapi.SetOpaque

**Comment by ncw** [comment]
This is being fixed in #665. I'm away at the moment - I'll merge it early next week. You could try that fix in the meantime.

**Comment by nigelhorne** [comment]
Thanks.
