### ISSUE TITLE
new feature request: open encrypted files from client devices

### ISSUE THREAD

**Issue by dan-cristian** [ncw/rclone#679]
Provide a way to decrypt and open encrypted cloud files on a client device (browser, mobile phone, etc). e.g. I have an encrypted document (using rclone crypt) on Amazon Drive and I want to open it from my Android phone, or from my PC.

**Comment by ncw** [comment]
Your only option is to install rclone at the moment.  PC is straight forward.  You can use Termux on android to compile and run rclone on Android...
