### ISSUE TITLE
Mounted filesystem doesn't get updated

### ISSUE THREAD

**Issue by uwe-schwarz** [ncw/rclone#680]
> What is your rclone version (eg output from `rclone -V`)
1.33

> Which OS you are using and how many bits (eg Windows 7, 64 bit)
OS X 10.11.6

> Which cloud storage system are you using? (eg Google Drive)
Google Drive, crypted Google Drive

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone -q mount gdrive: mnt
or
rclone -q mount crypt: mnt

Mounting is working perfectly, but the content doesn't get updated, easy to reproduce:
rclone mkdir gdrive:test
rclone copy test1 gdrive:test/
rclone mount gdrive: mnt
cd mnt/test
ls -l test1 # <- this gives a correct result
rclone copy test2 gdrive:test/
ls -l test2 # <- no such file (even after waiting for over an hour)

I can understand that the meta-information is cached, but there should be a timeout for this; maybe something in the range of about 10-15 minutes.

**Comment by ncw** [comment]
Yes I need to put some metadata caching timeouts in you are right. I'll add it to the list. 

Thanks 

Nick

**Comment by RXWatcher1** [comment]
can you please make the cache timeout value settable?

**Comment by talisto** [comment]
I'd find it very useful to be able to manually trigger the metadata to be updated, rather than having to wait for the cache to expire.

**Comment by jkaberg** [comment]
I'd love to see an default timeout (60s or so), overridden by an option (example: --cache-timeout=10m)

**Comment by ncw** [comment]
I've fixed that in: http://beta.rclone.org/v1.33-71-ga02edb9/ (uploaded in 15 mins)

With a new flag `--dir-cache-time` which has a default of 5 minutes.  It seems to work well in my testing.

@talisto re manual trigger of cache flush - I suggest you make another ticket with about that.

**Comment by scriptzteam** [comment]
Thx!
