### ISSUE TITLE
[Enquiry] upload/download

### ISSUE THREAD

**Issue by lsching17** [ncw/rclone#681]
I am testing Amazon Cloud Drive

For rclone's feature

       MD5/SHA1 hashes checked at all times for file integrity

Does this means that rclone will double-check the MD5/SHA1 hashes after upload/download files  everytimes?

For the following option

      --bwlimit int                     Bandwidth limit in kBytes/s, or use suffix b|k|M|G

Does this works for both upload/download? is it the global limit or the limit of a single connection only?

**Comment by ncw** [comment]
Yes rclone checks md5/sha1 where available for upload and download. 

Bwlimit is a global limit per rclone for upload and download combined. Note that not all the traffic is limited, eg directory listings only data transfers.

**Comment by lsching17** [comment]
i don't know if i understand the process correctly:

Transfer (checksum at the same time) -> upload/Download done -> verify the computed checksum against stored hash -> process complete

**Comment by ncw** [comment]
When rclone uploads a file it computes the checksum as it goes. When it is uploaded it queries the cloud provider for what it thinks the checksum is and checks they match. 

For download it asks the cloud provider for the checksum then downloads the file computing the checksum on the fly and checks it at the end.

**Comment by lsching17** [comment]
thx for the information.
