### ISSUE TITLE
Configuration file changes are lost if rclone is running

### ISSUE THREAD

**Issue by paranoidi** [ncw/rclone#682]
> What is your rclone version (eg output from `rclone -V`)

rclone v1.33

> Which OS you are using and how many bits (eg Windows 7, 64 bit)

ubuntu server, 14.04

> Which cloud storage system are you using? (eg Google Drive)

amazon

When modifying .rclone.conf while existing rclone process is running any changes are lost as running process rewrites configuration file back to disk (updates token?).

This is especially disastrous if user has added encrypted remote and started transferring files to it as keys are lost.

**Comment by ncw** [comment]
Yes you are correct, this is a problem.

I'll get the oauth module to read in the config file first before changing it - that should narrow the window for bad things to happen greatly.

**Comment by ncw** [comment]
I've fixed this problem.  There is a beta here: http://beta.rclone.org/v1.34-73-g1b2dda8/ (uploaded in 15-30 mins) for you to try if you want.
