### ISSUE TITLE
[ACD] Files bigger than 15 GB does not remove after /move upload?

### ISSUE THREAD

**Issue by Powerbless** [ncw/rclone#685]
![unbenannt](https://cloud.githubusercontent.com/assets/22020778/18263664/1ae5691a-740c-11e6-8370-a85830268ac1.jpg)
Hello,

this Programm is realy awesome! It works nice but i think i have found a small bug. I Upload my amazon folder with the /move command. this works sometimes greate but i think files bigger than ~15GB would not be deleted from harddisk after uploading. The File is still on ACD after upload! but it was not deleted from HDD. When the upload finish, he upload the File new again and again and again. The file from first upload in ACD is still OK/Hash OK!

> What is your rclone version (eg output from `rclone -V`)
> newest from Homepage yesterday
> 
> Which OS you are using and how many bits (eg Windows 7, 64 bit)
> Windows 10 64bit Enterprise bevore 2 days fresh installed and up to date
> Windows 10 Premium 32bit same issue
> 
> Which cloud storage system are you using? (eg Google Drive)
> Amazon Cloud Drive Unimited Plan
> 
> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
> rclone move E:/_amazon_upload amazon:encfsmp
> 
> A log from the command with the `-v` flag (eg output from `rclone -v copy /tmp remote:tmp`)

...s6nSBoL2DLueOrSQO/FFSe4tyDNf1btBPNIKqCMHOe: 95% done. avg:  776.9, cur: 1278.2 kByte/s. ETA: 10m25s

2016/09/03 15:50:13 
Transferred:   95.452 GBytes (2.004 MBytes/s)
Errors:                 0
Checks:                18
Transferred:           17
Elapsed time:  13h33m1.7s
Transferring:
- ...s6nSBoL2DLueOrSQO/FFSe4tyDNf1btBPNIKqCMHOe: 95% done. avg:  779.6, cur: 1682.4 kByte/s. ETA: 6m55s

2016/09/03 15:51:13 
Transferred:   95.546 GBytes (2.003 MBytes/s)
Errors:                 0
Checks:                18
Transferred:           17
Elapsed time:  13h34m1.7s
Transferring:
- ...s6nSBoL2DLueOrSQO/FFSe4tyDNf1btBPNIKqCMHOe: 96% done. avg:  782.2, cur: 1704.4 kByte/s. ETA: 5m52s

2016/09/03 15:52:13 
Transferred:   95.629 GBytes (2.002 MBytes/s)
Errors:                 0
Checks:                18
Transferred:           17
Elapsed time:  13h35m1.7s
Transferring:
- ...s6nSBoL2DLueOrSQO/FFSe4tyDNf1btBPNIKqCMHOe: 96% done. avg:  784.2, cur: 1421.5 kByte/s. ETA: 6m0s

2016/09/03 15:53:13 
Transferred:   95.724 GBytes (2.002 MBytes/s)
Errors:                 0
Checks:                18
Transferred:           17
Elapsed time:  13h36m1.7s
Transferring:
- ...s6nSBoL2DLueOrSQO/FFSe4tyDNf1btBPNIKqCMHOe: 97% done. avg:  786.7, cur: 1703.0 kByte/s. ETA: 4m2s

2016/09/03 15:54:13 
Transferred:   95.811 GBytes (2.001 MBytes/s)
Errors:                 0
Checks:                18
Transferred:           17
Elapsed time:  13h37m1.7s
Transferring:
- ...s6nSBoL2DLueOrSQO/FFSe4tyDNf1btBPNIKqCMHOe: 98% done. avg:  788.9, cur: 1497.4 kByte/s. ETA: 3m35s

2016/09/03 15:55:13 
Transferred:   95.904 GBytes (2.001 MBytes/s)
Errors:                 0
Checks:                18
Transferred:           17
Elapsed time:  13h38m1.7s
Transferring:
- ...s6nSBoL2DLueOrSQO/FFSe4tyDNf1btBPNIKqCMHOe: 98% done. avg:  791.3, cur: 1718.7 kByte/s. ETA: 2m11s

2016/09/03 15:56:13 
Transferred:   96.000 GBytes (2.000 MBytes/s)
Errors:                 0
Checks:                18
Transferred:           17
Elapsed time:  13h39m1.7s
Transferring:
- ...s6nSBoL2DLueOrSQO/FFSe4tyDNf1btBPNIKqCMHOe: 99% done. avg:  793.9, cur: 1560.0 kByte/s. ETA: 1m20s

2016/09/03 15:57:13 
Transferred:   96.099 GBytes (2.000 MBytes/s)
Errors:                 0
Checks:                18
Transferred:           17
Elapsed time:  13h40m1.7s
Transferring:
- ...s6nSBoL2DLueOrSQO/FFSe4tyDNf1btBPNIKqCMHOe: 99% done. avg:  796.7, cur: 1732.1 kByte/s. ETA: 11s

2016/09/03 15:58:13 
Transferred:   96.119 GBytes (1.998 MBytes/s)
Errors:                 0
Checks:                18
Transferred:           17
Elapsed time:  13h41m1.7s
Transferring:
- ...s6nSBoL2DLueOrSQO/FFSe4tyDNf1btBPNIKqCMHOe: 100% done. avg:  795.4, cur:   74.4 kByte/s. ETA: 0s

2016/09/03 15:59:13 
Transferred:   96.172 GBytes (1.997 MBytes/s)
Errors:                 0
Checks:                18
Transferred:           17
Elapsed time:  13h42m1.7s
Transferring:
- ...s6nSBoL2DLueOrSQO/FFSe4tyDNf1btBPNIKqCMHOe:  0% done. avg: 1170.4, cur: 1180.3 kByte/s. ETA: 3h50m44s

2016/09/03 16:00:13 
Transferred:   96.239 GBytes (1.996 MBytes/s)
Errors:                 0
Checks:                18
Transferred:           17
Elapsed time:  13h43m1.7s
Transferring:
- ...s6nSBoL2DLueOrSQO/FFSe4tyDNf1btBPNIKqCMHOe:  0% done. avg: 1176.7, cur: 1236.7 kByte/s. ETA: 3h39m15s

2016/09/03 16:01:13 
Transferred:   96.309 GBytes (1.995 MBytes/s)
Errors:                 0
Checks:                18
Transferred:           17
Elapsed time:  13h44m1.7s
Transferring:
- ...s6nSBoL2DLueOrSQO/FFSe4tyDNf1btBPNIKqCMHOe:  1% done. avg: 1190.7, cur: 1150.5 kByte/s. ETA: 3h54m37s

2016/09/03 16:02:13 
Transferred:   96.381 GBytes (1.994 MBytes/s)
Errors:                 0
Checks:                18
Transferred:           17
Elapsed time:  13h45m1.7s
Transferring:
- ...s6nSBoL2DLueOrSQO/FFSe4tyDNf1btBPNIKqCMHOe:  1% done. avg: 1207.7, cur: 1270.5 kByte/s. ETA: 3h31m28s

2016/09/03 16:03:13 
Transferred:   96.473 GBytes (1.993 MBytes/s)
Errors:                 0
Checks:                18
Transferred:           17
Elapsed time:  13h46m1.7s
Transferring:
- ...s6nSBoL2DLueOrSQO/FFSe4tyDNf1btBPNIKqCMHOe:  2% done. avg: 1291.2, cur: 1733.2 kByte/s. ETA: 2h34m5s

2016/09/03 16:04:13 
Transferred:   96.550 GBytes (1.992 MBytes/s)
Errors:                 0
Checks:                18
Transferred:           17
Elapsed time:  13h47m1.7s
Transferring:
- ...s6nSBoL2DLueOrSQO/FFSe4tyDNf1btBPNIKqCMHOe:  2% done. avg: 1301.1, cur: 1615.3 kByte/s. ETA: 2h44m30s

2016/09/03 16:05:13 
Transferred:   96.643 GBytes (1.992 MBytes/s)
Errors:                 0
Checks:                18
Transferred:           17
Elapsed time:  13h48m1.7s
Transferring:
- ...s6nSBoL2DLueOrSQO/FFSe4tyDNf1btBPNIKqCMHOe:  3% done. avg: 1347.5, cur: 1649.5 kByte/s. ETA: 2h40m6s

2016/09/03 16:06:13 
Transferred:   96.719 GBytes (1.991 MBytes/s)
Errors:                 0
Checks:                18
Transferred:           17
Elapsed time:  13h49m1.7s
Transferring:
- ...s6nSBoL2DLueOrSQO/FFSe4tyDNf1btBPNIKqCMHOe:  3% done. avg: 1346.0, cur: 1340.7 kByte/s. ETA: 3h16m0s

2016/09/03 16:07:13 
Transferred:   96.803 GBytes (1.990 MBytes/s)
Errors:                 0
Checks:                18
Transferred:           17
Elapsed time:  13h50m1.7s
Transferring:
- ...s6nSBoL2DLueOrSQO/FFSe4tyDNf1btBPNIKqCMHOe:  4% done. avg: 1359.0, cur: 1507.9 kByte/s. ETA: 2h53m17s

2016/09/03 16:08:13 
Transferred:   96.891 GBytes (1.990 MBytes/s)
Errors:                 0
Checks:                18
Transferred:

**Comment by ncw** [comment]
This is probably some error at the end of uploading the file to amazon which I'd quite common. I really need to see a log with -v to be certain of what is happening around the time when it goes from 100% to 0%.

**Comment by Powerbless** [comment]
ok i will test it. is this Command right?(will work?)
rclone move --log-file=FILE.log -v E:/_amazon_upload amazon:encfsmp

because i dont see now the status of upload. When rclone produce the log file? only on Error? or every time?

**Comment by ncw** [comment]
That command looks good.  rclone writes continuously to the log file.  If you were on unix you would `tail` the file to see what is in it.  Not sure what the equivalent for windows is - sorry!

**Comment by Powerbless** [comment]
i am still uploading since 6 hourse but now, there is nothing Log-File createt. or will rclone only create the log if there comes up a problem?

**Comment by ncw** [comment]
There should be a FILE.log in the directory where you started rclone from.

**Comment by Powerbless** [comment]
Done.

i have the log and here is the position where the First Upload from the file ends and then a new starts(the same file twice)

yte/s. ETA: 1m24s

2016/09/07 14:11:57 
Transferred:   24.240 GBytes (1.029 MBytes/s)
Errors:                 0
Checks:                 1
Transferred:            0
Elapsed time:   6h42m1.3s
Transferring:
 * ...1W67DZdOpXAgzc-c-/FFSe4tyDNf1btBPNIKqCMHOe: 99% done. avg: 1054.6, cur: 1088.4 kByte/s. ETA: 38s

2016/09/07 14:12:42 pacer: Rate limited, sleeping for 947.77941ms (1 consecutive low level retries)
2016/09/07 14:12:42 pacer: low level retry 1/1 (error HTTP code 500: "500 Internal Server Error", reponse body: {"message":"Internal failure"}
)
2016/09/07 14:12:42 tOIKw4zAGjlaX5OO4HVMGsKv/usHoGsSdcnakN0tygwwMQIjJZlXM9YJTWDgbmQ6XxC7IaM7e6RM0QYo,lrkFkjvCk5A6tXP-UI0xukN4QI,8vpZvUxZwl1W67DZdOpXAgzc-c-/FFSe4tyDNf1btBPNIKqCMHOe: Received error: HTTP code 500: "500 Internal Server Error", reponse body: {"message":"Internal failure"}
 - low level retry 1/10
2016/09/07 14:12:43 amazon: Saving new token in config file
2016/09/07 14:12:44 pacer: Resetting sleep to minimum 20ms on success
2016/09/07 14:12:57 
Transferred:   24.296 GBytes (1.029 MBytes/s)
Errors:                 0
Checks:                 1
Transferred:            0
Elapsed time:   6h43m1.3s
Transferring:
 * ...1W67DZdOpXAgzc-c-/FFSe4tyDNf1btBPNIKqCMHOe:  0% done. avg: 1279.1, cur: 1214.8 kByte/s. ETA: 5h49m4s

2016/09/07 14:13:57 
Transferred:   24.344 GBytes (1.028 MBytes/s)
Errors:                 0
Checks:                 1
Transferred:            0
Elapsed time:   6h44m1.3s
Transferring:
 * ...1W67DZdOpXAgzc-c-/FFSe4tyDNf1btBPNIKqCMHOe:  0% done. avg:  91

**Comment by ncw** [comment]
> low level retry 1/1 (error HTTP code 500: "500 Internal Server Error", reponse body: {"message":"Internal failure"}

Is amazon erroring after receiving the file.

There isn't a lot rclone can do after that other than retry the file.
