### ISSUE TITLE
Backblaze B2 transfers with an encrypted destination do not complete

### ISSUE THREAD

**Issue by bittylicious** [ncw/rclone#686]
Linked from #533 

I have a B2 remote called "remote" and a secret remote going to this called "secret". I'm using the command line:

rclone -I -v sync etc secret:flibble/etc2 2>&1

The -I is there because I was getting errors where it wouldn't transfer because the modification times are the same, which is strange because the directory is empty on B2. This might be an indicator.

This is using the rclone beta provided by @ncw version v1.33-6-g2eaac80β running on Ubuntu 16.04 amd64.

The output is, with a few lines removed:

> 2016/09/06 09:49:04 rclone: Version "v1.33-6-g2eaac80β" starting with parameters ["./home/marc/git/rclone-v1.33-6-g2eaac80β-linux-amd64/rclone" "-I" "-v" "sync" "etc" "secret:flibble/etc2"]
> 2016/09/06 09:49:04 Encrypted Local file system at /remote/berbg28gsc22d0pktgipsqshkg/n9nn9n1mk24irmrt29gu5ce7ek: Modify window is 1ns
> 2016/09/06 09:49:04 resolv.conf: Can't transfer non file/directory
> 2016/09/06 09:49:05 legal: Uploading unconditionally as --ignore-times is in use
> 2016/09/06 09:49:05 login.defs: Uploading unconditionally as --ignore-times is in use
> 2016/09/06 09:49:05 mtab: Can't transfer non file/directory
> 2016/09/06 09:49:05 upstart-xsessions: Uploading unconditionally as --ignore-times is in use
> 2016/09/06 09:49:05 vdpau_wrapper.cfg: Uploading unconditionally as --ignore-times is in use
> ....many, many other files uploading unconditionally
> 2016/09/06 09:49:30 fonts/conf.avail/58-dejavu-lgc-sans-mono.conf: Copied (replaced existing)
> 2016/09/06 09:49:30 fonts/conf.avail/57-dejavu-sans-mono.conf: Copied (replaced existing)
> 2016/09/06 09:49:30 ssl/certs/java/cacerts: Copied (replaced existing)
> 2016/09/06 09:49:30 Waiting for deletions to finish
> 2016/09/06 09:49:30 
> Transferred:   8.023 MBytes (322.229 kBytes/s)
> Errors:                 0
> Checks:              1869
> Transferred:         1869
> Elapsed time:       25.4s
> 2016/09/06 09:49:30 Go routines at exit 2

This actually completes near instantly, but you see different timestamps because I used less. Nothing is actually transferred to B2 from what I can tell.

**Comment by ncw** [comment]
It looks like a total of 8 MBytes of files were transferred.

What do you see when you do `rclone ls secret:flibble/etc`

How are you looking to see whether files are transferred or not? What do you see on the web interface?

And in the definition of your crypt remote did you chose a bucket, eg `b2:bucket` as the docs recommend?  If you didn't then rclone will have created a new funny named bucket (lots of lower case letters and numbers) to store `flibble` in. That might be confusing things.

**Comment by bittylicious** [comment]
Hi,

OK, I've got there in the end. It is because the crypt remote didn't have a bucket specified. I think it was copying the files locally instead. So human error, but perhaps an enhancement would be to warn about locally copied files, missing buckets or something similar.

I've left my thought process below in any case:

____________

I agree it looks like there was a transfer. For the whole lot to finish within a second makes me think that nothing was transferred.

The web interface shows no files in the etc2 directory and no additional buckets or directories having been created.

Interestingly, `rcclone ls secret:flibble/etc2` does show all the files (and returns instantly, like it's not actually connecting to a remote host):

>         8 hostname
>        18 subuid
>      1078 group-
>        12 debian_version
>     67946 mailcap
>      1094 group
>       436 hosts.sbak
> ...

But doing `rclone ls remote:flibble/etc2` shows nothing (and takes a few seconds):

>         0 .bzEmpty
> 2016/09/06 10:35:49 
> Transferred:      0 Bytes (0 Bytes/s)
> Errors:                 0
> Checks:                 0
> Transferred:            0
> Elapsed time:        2.5s

In the definition of the crypt remote, no, I did not specify the bucket. However, as I'm doing it on the command line (the bucket name being flibble) should this make a difference? I certainly don't see any additional buckets having been created. [and then I created a new crypt remote and it worked]

__________________

Many thanks for your help here, and it looks like the transfer and sha1 issue is fully resolved as I see properly encrypted files, with encrypted filenames, in B2 now.

**Comment by ncw** [comment]
Ah, so you put as your remote in `remote` rather than `remote:` or `remote:bucket`.  I'll try to make the docs a bit clearer here.  Maybe I can get the crypt to give a warning (though I do use crypt a lot to and from local disk for testing).

I'm glad you've got to the bottom of it, and I'll leave this ticket open to remind me to put some more stuff in the docs.

**Comment by bittylicious** [comment]
Yes, that's exactly right. I guess in this case, it acts like scp when you don't have a host (i.e. a ":").

**Comment by ncw** [comment]
I've fixed this with this text

```
Remote to encrypt/decrypt.
Normally should contain a ':' and a path, eg "myremote:path/to/dir",
"myremote:bucket" or maybe "myremote:" (not recommended).
```
