### ISSUE TITLE
Can't build - u.RawPath is undefined

### ISSUE THREAD

**Issue by nigelhorne** [ncw/rclone#688]
When filing an issue, please include the following information if
possible as well as a description of the problem.  Make sure you are
using the [latest version of rclone](http://rclone.org/downloads/).

> What is your rclone version (eg output from `rclone -V`)
> rclone won't install
> 
> Which OS you are using and how many bits (eg Windows 7, 64 bit)
> Linux
> 
> Which cloud storage system are you using? (eg Google Drive)
> Google drive
> 
> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
> go get github.com/ncw/rclone
> 
> A log from the command with the `-v` flag (eg output from `rclone -v copy /tmp remote:tmp`)
# golang.org/x/crypto/poly1305

go/src/golang.org/x/crypto/poly1305/poly1305_arm.s:26 syntax error, last name: R9
go/src/golang.org/x/crypto/poly1305/poly1305_arm.s:29 syntax error, last name: R9
go/src/golang.org/x/crypto/poly1305/poly1305_arm.s:34 syntax error, last name: R9
go/src/golang.org/x/crypto/poly1305/poly1305_arm.s:61 syntax error, last name: R9
go/src/golang.org/x/crypto/poly1305/poly1305_arm.s:74 syntax error, last name: R9
go/src/golang.org/x/crypto/poly1305/poly1305_arm.s:111 syntax error, last name: R9
go/src/golang.org/x/crypto/poly1305/poly1305_arm.s:123 syntax error, last name: R9
go/src/golang.org/x/crypto/poly1305/poly1305_arm.s:124 syntax error, last name: R9
go/src/golang.org/x/crypto/poly1305/poly1305_arm.s:139 syntax error, last name: R9
go/src/golang.org/x/crypto/poly1305/poly1305_arm.s:140 syntax error, last name: R9
go/src/golang.org/x/crypto/poly1305/poly1305_arm.s:149 syntax error, last name: R9
too many errors
# golang.org/x/net/context/ctxhttp

go/src/golang.org/x/net/context/ctxhttp/ctxhttp_pre17.go:36: req.Cancel undefined (type *http.Request has no field or method Cancel)
# golang.org/x/oauth2/jws

go/src/golang.org/x/oauth2/jws/jws.go:75: undefined: base64.RawURLEncoding
go/src/golang.org/x/oauth2/jws/jws.go:93: undefined: base64.RawURLEncoding
go/src/golang.org/x/oauth2/jws/jws.go:113: undefined: base64.RawURLEncoding
go/src/golang.org/x/oauth2/jws/jws.go:124: undefined: base64.RawURLEncoding
go/src/golang.org/x/oauth2/jws/jws.go:151: undefined: base64.RawURLEncoding
go/src/golang.org/x/oauth2/jws/jws.go:174: undefined: base64.RawURLEncoding
# google.golang.org/api/googleapi

go/src/google.golang.org/api/googleapi/googleapi.go:289: u.RawPath undefined (type *url.URL has no field or method RawPath)

**Comment by ncw** [comment]
Looks like you are using a pre go 1.5 compiler. Check the output of

    go version

You should have got a compile error from `cmd/versioncheck.go` about a missing function `Go_version_1_5_required_for_compilation` - maybe that check isn't working properly any more.

Can you try with a later go compiler?

**Comment by nigelhorne** [comment]
On 9/6/16 3:52 PM, Nick Craig-Wood wrote:
>
> Looks like you are using a pre go 1.5 compiler. Check the output of
>
> |go version |
>
> You should have got a compile error from |cmd/versioncheck.go| about a 
> missing function |Go_version_1_5_required_for_compilation| - maybe 
> that check isn't working properly any more.
>

go version go1.3.3 linux/arm
>
> Can you try with a later go compiler?
>

That's the one that's installed.  I'd rather not download and compile a 
new version just for this.  I'll have to try another machine.

-Nigel

**Comment by ncw** [comment]
You can always use one of the prebuilt versions at rclone.org/downloads

**Comment by ncw** [comment]
Eg http://downloads.rclone.org/rclone-v1.33-linux-arm.zip

**Comment by ncw** [comment]
This is fixed with vendoring now.
