### ISSUE TITLE
Timestamps on directories not preserved

### ISSUE THREAD

**Issue by ManuCart** [ncw/rclone#69]
Hello,
When using rclone with sync option local to local,
The date and time from the destination is not the prseved as the original file

**Comment by ncw** [comment]
Thanks for your report.

I just tried this on linux and it does preserve the timestamp when I tried `rclone sync local1 local2` and used `ls -l` to check the timestamps.

Can you tell me
  * which OS you are using?
  * which filing system?
  * how you tell the date and time isn't preserved?

Thanks

Nick

**Comment by ManuCart** [comment]
This is the "last modified" time stamp on directories
Using Raspbian, and did not remove empty directories when using sync

**Comment by ncw** [comment]
Ah ha!  As far as rclone is concerned directories don't actually exist, which means
  * timestamps aren't preserved
  * it doesn't remove empty directories when it should

I'd like to fix the second of those, but the first I don't have a plan to fix.

I'll add something to the docs to make it clear the limitations.

Thanks for the report

Nick

**Comment by ncw** [comment]
I've updated the rclone docs trying to explain these issues a bit better.  See http://rclone.org/bugs/

Thank you very much for the report

Nick
