### ISSUE TITLE
Transfers to Amazon Cloud seem slow when using fuse mount.

### ISSUE THREAD

**Issue by ShapeShifter499** [ncw/rclone#690]
I use rclone v1.33-DEV on a Arch Linux 64bit system. Using rclone as a mount uploads and downloads are far slower than just using sync. Any ideas why?   

I upload using a cellular connection which nets me around 20-30Mbps or 2-3MB/s upload AND download.
My sync speeds are near or a max speed however using fuse mount I see speeds around 700KB/s upload and download. 

Hope I used those network speed terms correctly.

**Comment by ncw** [comment]
Not sure exactly why.  Probably because FUSE is using lots of small buffers...

I'll investigate next time I'm looking at the FUSE code.

**Comment by calisro** [comment]
For what it is worth.  I am seeing similar performance with crypt mount or via a regular sync.  It is mostly maxing out my 100Mb connection.  I usually have to bandwidth limit it.

─> rsync --progress "somefile.mp4" ~/
somefile.mp4
    225,738,752  43%   12.04MB/s    0:00:24

**Comment by erpalma** [comment]
I have the same issue. My 50 mbit connection is usually maxed using sync or even acd_cli mount, but when using rclone mount the download speed is fluctuating with a very low (~10mbit) average speed. The problem seems getting worse when using encfs on top of rclone.

**Comment by ncw** [comment]
Give this a try - I put some more buffering in as an experiment

http://pub.rclone.org/v1.34-39-g7be5724-fuse-buffer%CE%B2/

**Comment by ncw** [comment]
I've merged this to master now: http://beta.rclone.org/v1.34-48-gc24da0b/ (will be uploaded in 15-30 mins)

**Comment by erpalma** [comment]
With the master I can now reach about 2MB/s, a bit better than before but still far below my 50mbit connection.
