### ISSUE TITLE
Access Denied while copying AppData

### ISSUE THREAD

**Issue by Ahava** [ncw/rclone#692]
> What is your rclone version (eg output from `rclone -V`)

rclone v1.33

> Which OS you are using and how many bits (eg Windows 7, 64 bit)

Windows 10 Anniversary Update, 64 bit

> Which cloud storage system are you using? (eg Google Drive)

Amazon Cloud Drive

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

rclone copy --bwlimit=.6M  --max-size=50G --verbose --stats=10s --checkers 16 "C:\Users\wanja" ACDEnc:\Users\wanja

> A log from the command with the `-v` flag (eg output from `rclone -v copy /tmp remote:tmp`)

2016/09/07 08:15:54 Failed to copy: failed to open directory "\\\\?\\C:\\Users\\wanja\\Anwendungsdaten": open \\?\C:\Users\wanja\Anwendungsdaten: Access is denied. (Anwendungsdaten is the german name for AppData, the folder is showing up as AppData in the explorer though)

I get the same error even when running rclone as an administrator.

**Comment by ncw** [comment]
I've managed to replicate this with Windows 7

```
X:\rclone>rclone.exe ls C:\Users\Dev
     5052 .rclone.conf
     4883 rclone.conf
  2628754 Downloads/rclone-v1.12-windows-386.zip
  4005419 Downloads/rclone-v1.27-windows-386.zip
      402 Favorites/desktop.ini
      580 Links/desktop.ini
      431 Links/Desktop.lnk
2016/09/07 20:42:30 failed to open directory "\\\\?\\C:\\Users\\Dev\\Application
 Data": open \\?\C:\Users\Dev\Application Data: Access is denied.
```

Using dir to take a look is a bit more helpful

```
X:\rclone>dir /ah "C:\Users\Dev"
 Volume in drive C has no label.
 Volume Serial Number is 5CD1-D250

 Directory of C:\Users\Dev

04/05/2011  14:29    <DIR>          AppData
04/05/2011  14:29    <JUNCTION>     Application Data [C:\Users\Dev\AppData\Roami
ng]
04/05/2011  14:29    <JUNCTION>     Cookies [C:\Users\Dev\AppData\Roaming\Micros
oft\Windows\Cookies]
04/05/2011  14:29    <JUNCTION>     Local Settings [C:\Users\Dev\AppData\Local]
04/05/2011  14:29    <JUNCTION>     My Documents [C:\Users\Dev\Documents]
04/05/2011  14:29    <JUNCTION>     NetHood [C:\Users\Dev\AppData\Roaming\Micros
oft\Windows\Network Shortcuts]
07/09/2016  20:51           786,432 NTUSER.DAT
07/09/2016  20:51           230,400 ntuser.dat.LOG1
04/05/2011  14:29                 0 ntuser.dat.LOG2
04/05/2011  15:16            65,536 NTUSER.DAT{6cced2f1-6e01-11de-8bed-001e0bcd1
824}.TM.blf
04/05/2011  15:16           524,288 NTUSER.DAT{6cced2f1-6e01-11de-8bed-001e0bcd1
824}.TMContainer00000000000000000001.regtrans-ms
04/05/2011  15:16           524,288 NTUSER.DAT{6cced2f1-6e01-11de-8bed-001e0bcd1
824}.TMContainer00000000000000000002.regtrans-ms
04/05/2011  14:29                20 ntuser.ini
04/05/2011  14:29    <JUNCTION>     PrintHood [C:\Users\Dev\AppData\Roaming\Micr
osoft\Windows\Printer Shortcuts]
04/05/2011  14:29    <JUNCTION>     Recent [C:\Users\Dev\AppData\Roaming\Microso
ft\Windows\Recent]
04/05/2011  14:29    <JUNCTION>     SendTo [C:\Users\Dev\AppData\Roaming\Microso
ft\Windows\SendTo]
04/05/2011  14:29    <JUNCTION>     Start Menu [C:\Users\Dev\AppData\Roaming\Mic
rosoft\Windows\Start Menu]
04/05/2011  14:29    <JUNCTION>     Templates [C:\Users\Dev\AppData\Roaming\Micr
osoft\Windows\Templates]
               7 File(s)      2,130,964 bytes
              11 Dir(s)   6,889,426,944 bytes free

X:\rclone>dir /ah "C:\Users\Dev\Application Data"
 Volume in drive C has no label.
 Volume Serial Number is 5CD1-D250

 Directory of C:\Users\Dev\Application Data

File Not Found

X:\rclone>
```

So maybe rclone needs to be doing something different with windows junction points...

I note that `filepath.Walk` uses `Lstat` on each file name read like this

```go
func readDirNames(dirname string) ([]string, error) {
	f, err := os.Open(dirname)
	if err != nil {
		return nil, err
	}
	names, err := f.Readdirnames(-1)
	f.Close()
	if err != nil {
		return nil, err
	}
	sort.Strings(names)
	return names, nil
}
```

rather than using `Readdir(1024)` like we do at the moment which stats each file.

This might fix #614 also.

I'll make a test with this a bit later and if it works I'll post a beta for you to try.

**Comment by ncw** [comment]
Here is a beta with a potential fix: http://pub.rclone.org/v1.33-8-ga02273e%CE%B2/

Let me know how you get on!

Thanks

**Comment by Ahava** [comment]
I left it running for about two hours now and it seems to work. Files from AppData get uploaded. Thanks!

**Comment by ncw** [comment]
I'll merge this to master now.
