### ISSUE TITLE
Mount Encrypted Remote (decrypted)

### ISSUE THREAD

**Issue by Trentflix** [ncw/rclone#695]
Mounting an unencrypted remote works as expected however I had assumed that you could mount an encrypted remote and the decrypted contents would appear and be accessible (if this is not the case, this would be a welcome enhancement). Upon running the mount command with an encrypted remote it just mounts an empty directory. Is this what's expected?

**Comment by ncw** [comment]
It should work. Can you supply some more details? Which remote, what crypt settings and the command line you used to mount. Thanks!

**Comment by Trentflix** [comment]
Ubuntu 16.04, ACD and Google Drive both encrypted and unencrypted remotes

ACD= unencrypted remote; EACD=encrypted remote

Crypt settings were encrypt filenames, no salt, user-generated password. (It didn't ask for password bit-strength as it shows in the docs). All Remotes were created in Windows but I copy/pasted the config file to Linux and it sees all remotes.

rclone mount EACD:/ /path/to/local/
rclone mount EGD:/subfolder/ /path/to/local2/

Also tried rclone mount GD:/CRYPT/ /path/to/local/ where the encrypted remote was created but then it just shows the encrypted files.

**Comment by ncw** [comment]
I just tried an encrypted remote on ACD and it worked as I expected.

Can you try `rclone ls EACD:` - does that show files? If not then the `rclone mount` won't work.

What exactly did you put in the config of the crypt?  Here is what mine looks like for comparison

```
[secretacd]
type = crypt
remote = acd:secret
filename_encryption = standard
password = SNIP
password2 = SNIP
```

and here is a sample run

```
$ rclone -q ls secretacd:
 36700160 ubuntu-13.04-mini-netboot-amd64.iso
      131 MD5SUMS.xubuntu-15.10-desktop-amd64.iso
      131 MD5SUMS.xubuntu-13.04
$ rclone -q ls acd:secret
      179 pjacqd7vm8q6eulc3k09u0lvk6aldh8l6t3f60rn0jffjocatlv2so43qjriiggr2kqv4a537kaj6
      179 91k62k7em7t7abi5on8t3hj3pek41lg9vvra8tlk9nj3lb9hf3gg
 36709152 q0fiipdq5vdor6jbbovsj08ug2bir2cteo4b899qnl069b8c84lgr77jn8s2vmfevb7romnjr9ahi
$ rclone mount secretacd:/ ~/mnt/tmp/ &
[2] 25236
$ ls -l ~/mnt/tmp/
total 0
-rw-r--r-- 1 root root      131 Sep  5 18:28 MD5SUMS.xubuntu-13.04
-rw-r--r-- 1 root root      131 Sep  5 18:28 MD5SUMS.xubuntu-15.10-desktop-amd64.iso
-rw-r--r-- 1 root root 36700160 Sep  5 18:30 ubuntu-13.04-mini-netboot-amd64.iso
$ fusermount -u ~/mnt/tmp/
```

Note that you don't need the leading and trailing slashes - I don't think they affect anything though.

**Comment by Trentflix** [comment]
running the ls command brought back "directory does not exist" looking in the config the remote was:

remote = EACD:\CRYPT
changing it to EACD:CRYPT solved the issue.

I was still able to upload files to it in Windows without any issues but the slash caused problems when moving to Linux.

Thank you for your help!

**Comment by ncw** [comment]
No problems! I think I'll get rclone to check the remote names for back slashes.
