### ISSUE TITLE
Extremely slow with HubiC

### ISSUE THREAD

**Issue by romanrm** [ncw/rclone#697]
rclone v1.33 on Debian 8 amd64

```
$ rclone lsd -v hubic:default/
2016/09/08 12:15:09 rclone: Version "v1.33" starting with parameters ["rclone" "lsd" "-v" "hubic:default/"]
2016/09/08 12:15:09 Hubic: Got swift credentials (expiry 2016-09-09 07:29:28 +0200 +0200 in 22h14m18.035418118s)
2016/09/08 12:15:09 Hubic Swift container default: Modify window is 1ns
           0 0001-01-01 00:00:00         0 e
           0 0001-01-01 00:00:00         0 h
2016/09/08 12:15:41 
Transferred:      0 Bytes (0 Bytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:       32.2s
2016/09/08 12:15:41 Go routines at exit 2
```

For comparison mounting with 'svfs':

```
$ fusermount -u /mnt/hubic/
$ time (svfs mount --allow-other --os-connect-timeout=2m --os-segment-size=5120 --default-uid=1000 --default-gid=1000 --hubic-authorization=xxx --hubic-refresh-token=xxx --device hubic --mountpoint /mnt/hubic & sleep 1; ls -la /mnt/hubic/default/)
total 0
drwx------ 1 rm rm 4096 Jul 23  2014 e
drwx------ 1 rm rm 4096 Dec 25  2015 h
drwx------ 1 rm rm 4096 Jun  5  2014 .ovhPub

real    0m2.140s
user    0m0.000s
sys 0m0.000s
```

And here it even got the mtimes of directories, all in about 1 second. Using 'hubicfuse' the performance is similar to svfs.

Also tried using the "mount" mode of rclone, same problem, listing a single directory with 7-10 files can take up to several minutes -- even with the "--no-modtime" option.

I hoped to use rclone because I have some reliability issues with the tools which mount FUSE FS, but why is it so slow? This is basically unusable, sync will take forever (killed it after 50 minutes, whereas my normal rsync to svfs or hubicfuse completes in less than 30) and of course it doesn't cache the dir structure locally between runs.  Is there any way to speed it up?

**Comment by romanrm** [comment]
Here **ALL** you need to parse and show a directory list is received in the very first response within 1 second, even complete with all hashes and mtimes -- but nope, rclone continues to do HEAD requests on each item for whatever reason, spending 39 seconds more on that. And yet it still fails to show proper mtimes in the end.

```
$ rclone lsd -v --dump-headers --dump-bodies hubic:default/
2016/09/08 12:43:57 rclone: Version "v1.33" starting with parameters ["rclone" "lsd" "-v" "--dump-headers" "--dump-bodies" "hubic:default/"]
2016/09/08 12:43:57 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2016/09/08 12:43:57 HTTP REQUEST
2016/09/08 12:43:57 GET /1.0/account/credentials HTTP/1.1
Host: api.hubic.com
User-Agent: rclone/v1.33
Authorization: Bearer xxx
Accept-Encoding: gzip

2016/09/08 12:43:57 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2016/09/08 12:43:58 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2016/09/08 12:43:58 HTTP RESPONSE
2016/09/08 12:43:58 HTTP/1.1 200 OK
Transfer-Encoding: chunked
Access-Control-Allow-Origin: *
Cache-Control: private
Content-Type: application/json; charset=utf8
Date: Thu, 08 Sep 2016 07:43:58 GMT
Server: nginx/1.4.7
Set-Cookie: SERVERID403=xxx; path=/
Strict-Transport-Security: max-age=15768000

a5
{"token":"xxx","endpoint":"https://lb1040.hubic.ovh.net/v1/AUTH_xxx","expires":"2016-09-09T07:29:28+02:00"}
0

2016/09/08 12:43:58 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2016/09/08 12:43:58 Hubic: Got swift credentials (expiry 2016-09-09 07:29:28 +0200 +0200 in 21h45m29.644758005s)
2016/09/08 12:43:58 Hubic Swift container default: Modify window is 1ns
2016/09/08 12:43:58 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2016/09/08 12:43:58 HTTP REQUEST
2016/09/08 12:43:58 GET /v1/AUTH_xxx/default?delimiter=%2F&format=json&limit=256 HTTP/1.1
Host: lb1040.hubic.ovh.net
User-Agent: rclone/v1.33
X-Auth-Token: xxx
Accept-Encoding: gzip

2016/09/08 12:43:58 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2016/09/08 12:43:58 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2016/09/08 12:43:58 HTTP RESPONSE
2016/09/08 12:43:58 HTTP/1.1 200 OK
Connection: close
Content-Length: 519
Accept-Ranges: bytes
Content-Type: application/json; charset=utf-8
Date: Thu, 08 Sep 2016 07:43:58 GMT
X-Container-Bytes-Used: xxx
X-Container-Meta-Access-Control-Allow-Origin: https://hubic.com
X-Container-Object-Count: 36325
X-Storage-Policy: Policy-1
X-Timestamp: 1401961579.53792
X-Trans-Id: xxx

[{"hash": "d41d8cd98f00b204e9800998ecf8427e", "last_modified": "2014-06-05T11:41:47.013420", "bytes": 0, "name": ".ovhPub", "content_type": "application/directory"}, {"hash": "d41d8cd98f00b204e9800998ecf8427e", "last_modified": "2014-07-23T11:22:38.836430", "bytes": 0, "name": "e", "content_type": "application/directory"}, {"subdir": "e/"}, {"hash": "d41d8cd98f00b204e9800998ecf8427e", "last_modified": "2015-12-25T16:03:40.815460", "bytes": 0, "name": "h", "content_type": "application/directory"}, {"subdir": "h/"}]
2016/09/08 12:43:58 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2016/09/08 12:43:58 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2016/09/08 12:43:58 HTTP REQUEST
2016/09/08 12:43:58 HEAD /v1/AUTH_xxx/default/.ovhPub HTTP/1.1
Host: lb1040.hubic.ovh.net
User-Agent: rclone/v1.33
X-Auth-Token: xxx

2016/09/08 12:43:58 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2016/09/08 12:44:33 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2016/09/08 12:44:33 HTTP RESPONSE
2016/09/08 12:44:33 HTTP/1.1 200 OK
Connection: close
Accept-Ranges: bytes
Content-Type: application/directory
Date: Thu, 08 Sep 2016 07:44:33 GMT
Etag: xxx
Last-Modified: Thu, 05 Jun 2014 11:41:48 GMT
X-Timestamp: 1401968507.01342
X-Trans-Id: xxx
Content-Length: 0

2016/09/08 12:44:33 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2016/09/08 12:44:33 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2016/09/08 12:44:33 HTTP REQUEST
2016/09/08 12:44:33 HEAD /v1/AUTH_xxx/default/e HTTP/1.1
Host: lb1040.hubic.ovh.net
User-Agent: rclone/v1.33
X-Auth-Token: xxx

2016/09/08 12:44:33 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2016/09/08 12:44:34 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2016/09/08 12:44:34 HTTP RESPONSE
2016/09/08 12:44:34 HTTP/1.1 200 OK
Connection: close
Accept-Ranges: bytes
Content-Type: application/directory
Date: Thu, 08 Sep 2016 07:44:34 GMT
Etag: xxx
Last-Modified: Wed, 23 Jul 2014 11:22:39 GMT
X-Timestamp: 1406114558.83643
X-Trans-Id: xxx
Content-Length: 0

2016/09/08 12:44:34 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
           0 0001-01-01 00:00:00         0 e
2016/09/08 12:44:34 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2016/09/08 12:44:34 HTTP REQUEST
2016/09/08 12:44:34 HEAD /v1/AUTH_xxx/default/h HTTP/1.1
Host: lb1040.hubic.ovh.net
User-Agent: rclone/v1.33
X-Auth-Token: xxx

2016/09/08 12:44:34 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2016/09/08 12:44:36 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2016/09/08 12:44:36 HTTP RESPONSE
2016/09/08 12:44:36 HTTP/1.1 200 OK
Connection: close
Accept-Ranges: bytes
Content-Type: application/directory
Date: Thu, 08 Sep 2016 07:44:36 GMT
Etag: xxx
Last-Modified: Fri, 25 Dec 2015 16:03:41 GMT
X-Timestamp: 1451059420.81546
X-Trans-Id: xxx
Content-Length: 0

2016/09/08 12:44:36 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
           0 0001-01-01 00:00:00         0 h
2016/09/08 12:44:36 
Transferred:      0 Bytes (0 Bytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:       38.7s
2016/09/08 12:44:36 Go routines at exit 2
```

**Comment by barsanuphe** [comment]
This has also been my experience, Hubic syncing is very slow, whereas Amazon Drive, for example, is quite fast.
For the same folder (~1.2Tb), syncing to Hubic would take days where Amazon Drive takes minutes.

**Comment by ncw** [comment]
rclone shouldn't do head requests on all the objects, it will only do it on zero sized objects which might be dynamic large objects (to read their size correctly). Those 3 HEAD requests are taking over 30 seconds which I think has to be hubic's fault!

From the code

```go
	// Note that due to a quirk of swift, dynamic large objects are
	// returned as 0 bytes in the listing.  Correct this here by
	// making sure we read the full metadata for all 0 byte files.
```

In general hubic does seem incredibly slow when I try to use it.  I'm getting about 30 kByte/s ~ 300 kBit/s upload from our 1 Gbit/s connection!  Doing an `rclone lsl` (so HEAD request for each file) on a bucket with 114 files takes 37s.  If I try that on a different swift cluster it returns in 400 ms.

> I hoped to use rclone because I have some reliability issues with the tools which mount FUSE FS, but why is it so slow? This is basically unusable, sync will take forever (killed it after 50 minutes, whereas my normal rsync to svfs or hubicfuse completes in less than 30) and of course it doesn't cache the dir structure locally between runs. Is there any way to speed it up?

IMHO You would be much better using rclone directly instead of using rsync over a fuse mount. To get max performance, experiment with the number of `--checkers` and `--transfers`. rclone does lots of retries and concurrent operations which the rsync/FUSE combo won't, making it much more reliable. You can skip using the modtime (so skip a HEAD request) by using --checksum or --size-only.

**Comment by romanrm** [comment]
> it will only do it on zero sized objects which might be dynamic large objects (to read their size correctly).

"content_type": "application/directory" <- these can't be dynamic large objects, right? Seems to be a potential optimization to skip that HEAD request if the object type is a directory. When there's lots of directories, this will bring a huge speed improvement.

> You would be much better using rclone directly instead of using rsync over a fuse mount. 

That's what I wanted to do, except that currently rsync over svfs or hubicfuse FUSE mounts performs way better than rclone directly. 

> experiment with the number of --checkers and --transfers

HubiC is currently capped to 10 Mbit, and from what I could see that's per entire account, no matter how many parallel mounts or sessions -- so doesn't seem to be a good idea to upload several files in parallel (if the session fails for some reason, they fail all at once).

> You can skip using the modtime (so skip a HEAD request) 

Is there really a need to HEAD request for modtime? In my dump "last_modified" fields are returned as a part of the bulk JSON list.

**Comment by ncw** [comment]
> "content_type": "application/directory" <- these can't be dynamic large objects, right? Seems to be a potential optimization to skip that HEAD request if the object type is a directory. When there's lots of directories, this will bring a huge speed improvement.

Great idea.  I made an issue with that #703 - please subscribe to that and I'll post a beta in due course.

>> You would be much better using rclone directly instead of using rsync over a fuse mount.

> That's what I wanted to do, except that currently rsync over svfs or hubicfuse FUSE mounts performs way faster than rclone directly (except some reliability problems).

I'm surprised!  Can you do a time comparison for me? Make sure that svfs/hubicfuse has finished syncing its buffers at the end of the test. (Ha, just noticed that I contributed the rename a file code to hubicfuse or to its ancestor  cloudfuse!)

> Is there really a need to HEAD request for modtime? In my dump "last_modified" fields are returned as a part of the bulk JSON list.

The last_modified field is the time the object was uploaded.  rclone tries to preserve the modification time of the file so it stores it in some metadata which requires a HEAD request to retrieve.

**Comment by romanrm** [comment]
> I'm surprised! Can you do a time comparison for me?

Currently it won't be a fair comparison, since rclone does a lot more requests as demonstrated above (and a potential fix is identified). For a ballpark figure, as mentioned earlier rclone run didn't complete in 50 minutes, whereas my normal rsync walkthrough of an svfs/hubicfuse takes less than 30. I could try it again and see what does it take, 1/2/3/12 hours? but what will be the value of that.

> rclone tries to preserve the modification time of the file so it stores it in some metadata which requires a HEAD request to retrieve.

Is there an option to not do that? Currently I'm using the --size-only mode with rsync, as what I am storing is a media file archive, and those files don't get their content modified, ever.

**Comment by ncw** [comment]
I made a fix for #703 - here is a beta with the fix in: http://pub.rclone.org/v1.33-11-g346d4c5%CE%B2/

Maybe you could try a benchmark now?

> > rclone tries to preserve the modification time of the file so it stores it in some metadata which requires a HEAD request to retrieve.

> Is there an option to not do that? Currently I'm using the --size-only mode with rsync, as what I am storing is a media file archive, and those files don't get their content modified, ever.

It is free to store the mtime when creating the object.  Use the `--checksum` or `--size-only` flags to stop rclone checking it when doing a sync.

**Comment by romanrm** [comment]
Indeed it is now much faster!! A dry run now completes in under 3 minutes:
```
Transferred:      0 Bytes (0 Bytes/s)
Errors:                 0
Checks:             28624
Transferred:           68
Elapsed time:     2m48.5s
2016/09/08 23:36:06 Go routines at exit 2
```
Thanks!

I also got rid of all the segmented files (svfs uses segment size of 256M by default, so it segmented a large portion of stuff I uploaded with it), since they bring such a performance penalty.

**Comment by ncw** [comment]
Excellent, that looks more like it :-)

**Comment by doplu** [comment]
Hello, I don't if this help but Hubic team gave detailed technical explanations here on why they are so slow:
https://forums.hubic.com/showthread.php?174279-Performance-problems-and-stability

**Comment by romanrm** [comment]
Thanks, the base problem which I reported has been already solved (so this bug can be closed when a version including the fix is released); the file/directory structure comparisons are now very fast with rclone, much better than mounting with the FUSE tools.

As for HubiC stability in general, I still get "503 Service Unavailable" errors very often halfway during actual upload attempts, probably due to what is posted in that thread, but this happens no matter which upload or mounting software is used, so it doesn't seem rclone related.

**Comment by ncw** [comment]
This has been released now so I'm going to close thos.
