### ISSUE TITLE
Support linux/arm64 build

### ISSUE THREAD

**Issue by ncw** [ncw/rclone#699]
Now we are using go1.7 there are more architectures we could be building for.  linux/arm64 is quite an important one - there may be others I've missed.

To add a new build architecture it is a matter of editing `cross-compile.sh` and `docs/content/downloads.md.in`

**Comment by justusiv** [comment]
Just compiled on my arm64 android devices.
Appears to have worked just fine :)

**Comment by ncw** [comment]
Excellent!  Arm64 Linux builds will be part of rclone's normal build now.
