### ISSUE TITLE
Error logging and quiet mode

### ISSUE THREAD

**Issue by shalupov** [ncw/rclone#70]
I'm trying to set up rclone in a cron job. I've found it's not easy to make rclone output quiet.

-q flag actually has two flaws:
* it suppresses all logging (even error one)
* it prints stats after running a command

I think it's better to always print error messages in quiet mode and make stats output optional if no errors encountered.

I do not mind implementing this myself after discussing it with you.

**Comment by ncw** [comment]
Sounds very sensible, and if you want to have a go I'd be happy to review the pull request.

Thanks

Nick
