### ISSUE TITLE
google drive remote disappears from list

### ISSUE THREAD

**Issue by peixotorms** [ncw/rclone#701]
Hi,

I configured 2 remotes, one for hubic and another one for google drive.
What's happening is, everything works fine for a while but for instance, the next day my backup script didn't back it up to google drive... and when I check, the "google" remote is gone from rclone config.

This happened a few times already, is it that the google drive remote expires and then it's removed from my list of remotes? I noticed hubic is still there, only the google remote is gone.

I have removed the hubic remote and left only the google drive active.
I have also added a password to protect the configuration, so let's see if it disappears this way.

I am the only person with access to the server, a debian jessie server.

Any idea how come only the google drive remote disappears?
Anywhere I can debug rclone to find out why it disappears?

Thanks

**Comment by ncw** [comment]
I think this is probably the same issue as #682 - did you have rclone running for drive when you made the config for hubic?

If you make the configs while rclone isn't running the config won't disappear.  I'll fix the problem properly in #682

**Comment by peixotorms** [comment]
Hi, it may have been possible that it was doing the backup to hubic (since it's so slow) while I added google drive. Thanks for the tips, will try to add it when it's not running and see.

**Comment by ncw** [comment]
Great.  I'll do the fix in #682 - please re-open if you find anything new.

Thanks
