### ISSUE TITLE
How "crypt" folder handle non-repeating errors (e.g. network timeout)

### ISSUE THREAD

**Issue by lsching17** [ncw/rclone#702]
rclone v1.33, Windows 7 x64. Amazon cloud drive

i have a "crypt" folder (standard encryption) on Amazon cloud drive.

I uploaded and then download (both by "sync" command) for verification

several files failed with message "Failed to copy: failed to authenicate decrypted block - bad password?"

When i restart the download process, the files can be successfully downloaded.

Do "crypt" folder retried automatically like other cloud drive for non-repeating errors (e.g. network timeout)?

**Comment by ncw** [comment]
Yes crypt should retry files under control of the `--retries` and `--low-level-retries` flags as normal.

That particular error `Failed to copy: failed to authenicate decrypted block - bad password?` I think is caused by a broken network connection rather than an actual corruption.

**Comment by lsching17** [comment]
Does checksum error belong to high-level retries or low level retries?

Could this be fixed? actually Checksum error<>network error, and it is very misleading.

**Comment by ncw** [comment]
That error will probably be a high level retry. 

Yes I will fix the misleading error.

**Comment by ncw** [comment]
The misleading error has now been fixed so I'm going to close this.
