### ISSUE TITLE
--delete-during is on by default for sync?

### ISSUE THREAD

**Issue by romanrm** [ncw/rclone#705]
Hello,

I was surprised to find that --delete-during option seems to be enabled by default, with no obvious way to disable any deletions. Compare rclone's options:

```
$ rclone --help | grep delete
...
      --delete-after                    When synchronizing, delete files on destination after transfering
      --delete-before                   When synchronizing, delete files on destination before transfering
      --delete-during                   When synchronizing, delete files during transfer (default)
      --delete-excluded                 Delete files on dest excluded from sync
```

with rsync:

```
$ rsync --help | grep delete
     --del                   an alias for --delete-during
     --delete                delete extraneous files from destination dirs
     --delete-before         receiver deletes before transfer, not during
     --delete-during         receiver deletes during the transfer
     --delete-delay          find deletions during, delete after
     --delete-after          receiver deletes after transfer, not during
     --delete-excluded       also delete excluded files from destination dirs
     --ignore-errors         delete even if there are I/O errors
     --max-delete=NUM        don't delete more than NUM files

```

As you can see with rsync none of these are enabled by default, and there's also a safeguard option of --max-delete available, to prevent accidental nuking of the entire destination contents (by specifying a wrong or inaccessible sync source). According to the main page, --delete enables --delete-during in recent versions. But the user still has to explicitly request deletions via using one of them.

Is there currently a way to use rclone sync without any deletions on destination?

If not, can you please consider bringing this more in line with rsync, i.e. no deletions by default, require a "--delete" or "--del" to enable them, and possibly implement a --max-delete safeguard as well.

Thanks!

**Comment by ncw** [comment]
If you don't want deletions use rclone copy rather than rclone sync. Copy never deletes anything. 

--max-delete sounds like a good addition.
