### ISSUE TITLE
Failed upload attempts should not count as "Transferred"

### ISSUE THREAD

**Issue by romanrm** [ncw/rclone#708]
Hello,

Let's say I get an upload error with HubiC:
```
2016/09/09 00:20:00 ...: Failed to copy: HTTP Error: 503: 503 Service Unavailable
2016/09/09 00:20:00 ...: Removing failed copy
...
2016/09/09 00:20:06 HTTP REQUEST
2016/09/09 00:20:06 DELETE
...
2016/09/09 00:20:08 HTTP RESPONSE
2016/09/09 00:20:08 HTTP/1.1 404 Not Found
```
OK, it didn't get uploaded, and there's even no partial copy to delete.

But it still counts as "Transferred" in stats:
```
Transferred:   817.161 MBytes (1.501 MBytes/s)
Errors:                 4
Checks:             14271
Transferred:            4
Elapsed time:      9m4.2s
```
The other 3 were like that also. Nothing got uploaded so far -- I'd expect stats to say "Errors: 4, Transferred: 0" at this point.

After getting two files uploaded successfully:
```
Transferred:   1.664 GBytes (2.018 MBytes/s)
Errors:                 4
Checks:             14271
Transferred:            6
Elapsed time:     14m4.2s
```

This all is even more confusing since (if I'm not mistaken) when 2nd and 3rd attempt to upload previously transferred files are performed, those ALSO increment "Transferred", and also no matter succeeded or failed.

IMO the "Transferred" stat should only count files which were successfully uploaded ("201 Created" in terms of HubiC), and count each file only once, no matter how many attempts.

Thanks

**Comment by ncw** [comment]
Seems sensible! Will do.

**Comment by ncw** [comment]
I have fixed this here: http://pub.rclone.org/v1.33-19-g83ba597%CE%B2/

Please re-open if you find any problems with it
