### ISSUE TITLE
Add an auto-update or check for update mechanism

### ISSUE THREAD

**Issue by TheTrueTom** [ncw/rclone#709]
> What is your rclone version (eg output from `rclone -V`)
> 1.33
> 
> Which OS you are using and how many bits (eg Windows 7, 64 bit)
> macOS El Capitan

As a first step I think it would be useful to include in rclone a mechanism such that it would warn the user if a new version of rclone is available. This could take the form of a simple message such as ('An update of rclone is available, go download it at rclone.org')

Better yet and as a second step it would be cool to have it check for an update and ask if it should auto-update before starting the job.

For people using rclone a lot in script, it would be nice to add a --no-autoupdate option to prevent the script from being blocked by a prompt for update.

I'm aware this is not high priority but it would be useful for people like me who too rarely go on the website to check for an updated version.

**Comment by justusiv** [comment]
There is a section for "Downloads for scripting". You could make your own update script with not much effort.

**Comment by ncw** [comment]
It would be reasonably easy to do this. 

I'm not  in favour of checking all the time though, Id make an update command probably. 

I don't know what I'd do about updating the docs though - rclone knows where the user installed the binary but not the docs. Maybe I'd separate the two...

**Comment by TheTrueTom** [comment]
@justusiv I know it's easy to make a small update script. Unfortunately not everyone knows scripting, if it's not too hard to do it would make a big difference for some users I believe.

@ncw I agree that it doesn't have to run every time. However having an automatic check from time to time (once a month?) can be useful to some. Maybe add an option in the config to change the frequency update?

**Comment by marrie** [comment]
I agree. I can't script well, an option that can be set when running config would be nice, a choice to choose when to check for updates and weather to include betas as part of said updates would also be good as well for those of us that want to beta test rclone.

**Comment by ncw** [comment]
This is now covered by the [script auto download](https://github.com/ncw/rclone/blob/master/docs/content/install.md#script-installation)

It won't download rclone again if it hasn't changed.
