### ISSUE TITLE
How to decrypt an encrypted file from a remote downloaded outside rclone?

### ISSUE THREAD

**Issue by EmilioMoreno** [ncw/rclone#710]
Hi 
i am doing tests with 1.33/linux  and ACD for storing some TB of files in ACD with encryption and be able to later browse and read them via rclone mount, all my tests so far have been successful but i am concerned about Rclone stop working with/being banned by Amazon for some obscure reason only known by them..

In that scenario we would be left with a lot of encrypted files which i would be able to sync/dowload/using other tools, but is there a way, obviously knowning both passwords to decrypt them locally?

**Comment by calisro** [comment]
In your scenerio, you could use another tool (like acd_cli) or amazon website itself to download the "encrypted" files from ACD and then still use rclone to decrypt them locally.  I (same as you) would like to be able to decrypt them with a 2nd tool but I haven't found a way yet.  I suppose someone could just pull the pieces from rclone's crypt and create a standalone utility but why bother since rclone can do it locally.

**Comment by EmilioMoreno** [comment]
That was my idea, but i have not found a way to do it with rclone. I have downloaded with acd_cli an encrypted folder and its encrypted files, and now I have to decrypt them, but I do not know how to do it with rclone.

I have tried to create a "local remote" in the config and then create an "encrypted remote" based on the plain one as you would do with acd, but I have not manage to get them working.

Assuming you have a folder with encrypted files and folders inside it -a typical folder/subfolders/files structure- can you please elaborate how to decrypt them?

**Comment by calisro** [comment]
It worked for me.  This is what I did.  

1. I copied a folder from my acd crypted volume to my local drive.  Lets say /home/robert/encdata
2. create a local 'remote'.  we'll call it local
3. create a crypted 'remote' based on the local remote with a path to the directory where you've downloaded your encyrpted data from acd.  Don't worry too much what you use for the passwords and hashes.  We'll replace them anyway.  i.e. We'll call it local-crypt and we'll reference local:/home/robert/encdata
4. save the config.
5. Edit the .rclone.conf file and replace the password1/password2 with the values from your amazon drive configuration.
6. mount it.  

Really, you can bypass the config wizard and just edit the .rclone.conf file yourself and paste these lines:
`
[local]
type = local
nounc =

[local-crypt]
type = crypt
remote = local:/home/robert/g
filename_encryption = standard
password = (PASSWORD_FROM_ENC_REMOTE)
password2 = (PASSWORD2_FROM_ENC_REMOTE)

`

**Comment by ncw** [comment]
@calisro nice walk through. I test crypt like this so it is definitely supported.

**Comment by calisro** [comment]
@ncw Might be a valid enhancement on the passwords/hashes to have a 3rd option for a RAW data input.  So people can use the wizard to clone a crypted volume and paste the actual keys rather than having to edit the .rclone.conf.  Just a thought.

**Comment by EmilioMoreno** [comment]
Thanks @calisro for the explanation, I will give it a try as soon as I get back to my main computer. I have no problem either editing the pass values directly on the .config file or using the original pass values to generate them in the wizard, what got me confused was the creation and usage of local remotes.

I would suggest that the creation of local remote in general and this particular scenario about decrypting a alternative downloaded file or folder gets into the documentation, happy to help if required.

**Comment by EmilioMoreno** [comment]
As expected by you two, my tests have worked flawlessly. I have done them cross-platform to make sure no problem arises from running rclone under different OS. I have uploaded several files and dirs from Synology NAS (intel), running rclone x64 Linux version and downloaded ad decrypted them under MAC, 64bits, both mounting the drive with osxfuse or syncing/copying.

I suggest again to update the documentation detailing this process, but  beyond that, nothing to change, it works great, thanks!

**Comment by stayupthetree** [comment]
Sorry for reviving this, but I was following @calisro but I am on Windows. mount isn't an option. Is there no way to decrypt in Windows?

**Comment by calisro** [comment]
You can.  instead of mount in step 6, you can just copy it somewhere else and it will be decrypted. 

rclone ls local-crypt:/ 
rclone copy local-crypt: /some/dir
