### ISSUE TITLE
acd: Stop waiting for files to appear when we got a 429 error

### ISSUE THREAD

**Issue by calisro** [ncw/rclone#712]
> What is your rclone version (eg output from `rclone -V`)
v1.33
> Which OS you are using and how many bits (eg Windows 7, 64 bit)
Linux Debian 64bit
> Which cloud storage system are you using? (eg Google Drive)
ACD
> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone sync -v /data/Media2 robacd-crypt:/
> A log from the command with the `-v` flag (eg output from `rclone -v copy /tmp remote:tmp`)

I see lots of failures for many different reasons to ACD.  Is there an ability to reduce the amount of time/retries for these type of failures?  Currently it waits 24 times (about 2 minutes) to verify the file was not uploaded correctly.  In the end 99.9% of the time the file does not exist and it just re-uploads it.  I'd like to cut down on the time and only try a few times thus reducing the sync times.  

┌[ ✓ robert [/tmp] $
└─> cat rclone.out | grep Wildflowers\/folder.jpg
2016/09/09 09:32:32 &{Music/Tom Petty/Wildflowers/folder.jpg 0xc42013d8f0}: Error detected after finished upload - waiting to see if object was uploaded correctly: HTTP code 429: "429 Too Many Requests", reponse body: {"message":"HTTP status code\u003d[429] RequestId\u003d[dc28ddba-7691-11e6-b3b6-43cce1d313ba] Rate exceeded"}
2016/09/09 09:32:32 &{Music/Tom Petty/Wildflowers/folder.jpg 0xc42013d8f0}: Object not found - waiting (1/24)
2016/09/09 09:32:37 &{Music/Tom Petty/Wildflowers/folder.jpg 0xc42013d8f0}: Object not found - waiting (2/24)
2016/09/09 09:32:42 &{Music/Tom Petty/Wildflowers/folder.jpg 0xc42013d8f0}: Object not found - waiting (3/24)
2016/09/09 09:32:47 &{Music/Tom Petty/Wildflowers/folder.jpg 0xc42013d8f0}: Object not found - waiting (4/24)
2016/09/09 09:32:52 &{Music/Tom Petty/Wildflowers/folder.jpg 0xc42013d8f0}: Object not found - waiting (5/24)
2016/09/09 09:32:57 &{Music/Tom Petty/Wildflowers/folder.jpg 0xc42013d8f0}: Object not found - waiting (6/24)

**Comment by ncw** [comment]
Use the `--acd-upload-wait-time` flag to reduce that time limit.

It really shouldn't be waiting on a 429 error though - I need to fix that.

**Comment by ncw** [comment]
I've fixed this here: http://pub.rclone.org/v1.33-19-g83ba597%CE%B2/

Please re-open if you find any problems with it

**Comment by felixbuenemann** [comment]
@ncw I see the opposite behavior, where rclone *should* wait for the file to appear on 429 errors. So it re-uploads file when not needed on the latest beta.

**Comment by ncw** [comment]
@felixbuenemann I think if amazon give you a 429 the file hasn't been uploaded properly - what makes you think otherwise?

**Comment by felixbuenemann** [comment]
Here's an example log, where the file appeared after the 429 error (I aborted the re-upload with Ctrl+C and checked the ACD Web UI to confirm the file was already there):

```
2016/10/14 08:09:46 
Transferred:   217.666 GBytes (491.589 kBytes/s)
Errors:                 0
Checks:                30
Transferred:           39
Elapsed time:  128h58m7.7s
Transferring:
 *                                   bigfile.img: 99% done. avg:  499.9, cur:  500.7 kByte/s. ETA: 5s

2016/10/14 08:10:17 pacer: Rate limited, sleeping for 300.159908ms (1 consecutive low level retries)
2016/10/14 08:10:17 pacer: low level retry 1/1 (error HTTP code 429: "429 Too Many Requests", reponse body: {"logref":"df9ed002-91d4-11e6-8484-fbfc7cdd26ec","message":"Rate exceeded","code":""}
)
2016/10/14 08:10:17 bigfile.img: Received error: HTTP code 429: "429 Too Many Requests", reponse body: {"logref":"df9ed002-91d4-11e6-8484-fbfc7cdd26ec","message":"Rate exceeded","code":""}
 - low level retry 1/10
2016/10/14 08:10:17 pacer: Resetting sleep to minimum 20ms on success
2016/10/14 08:10:46 
Transferred:   217.683 GBytes (491.563 kBytes/s)
Errors:                 0
Checks:                30
Transferred:           39
Elapsed time:  128h59m7.7s
Transferring:
 *                                   bigfile.img:  0% done. avg:  511.6, cur:  530.1 kByte/s. ETA: 2h23m36s
```

So far the only error I've seen where the file did not appear after the transfer went to 100% was 500 errors (it did appear on 504 errors).

I guess the differences between the two cases would be if the error occurs at the beginning of the data transfer or after it has finished.

**Comment by ncw** [comment]
@felixbuenemann the code without the patch above does exactly that - it waits for any kind of error provided that rclone has uploaded all the data.

I think maybe getting the timing more accurate and reverting the above patch might be the best solution.

I'll re-open this to remind me to think about it.

**Comment by felixbuenemann** [comment]
> I think maybe getting the timing more accurate and reverting the above patch might be the best solution.

Yes, that seems like a reasonable solution, because waiting mostly hurts upload of many small files, which would no longer enter the wait loop with the dynamic wait time.

**Comment by ncw** [comment]
OK here is my latest attempt to fix this problem.  See below for changed docs.

http://pub.rclone.org/v1.33-66-g2e20a0f-acd-timeout%CE%B2/

Any feedback very welcome, with suggestions for the default parameter values.  In my tests I successfully uploaded a range of file sizes up to 15 GB.  The tests weren't successful before I introduced the extra 2m sleep.

#### --acd-upload-wait-time=TIME, --acd-upload-wait-per-gb=TIME, --acd-upload-wait-limit=TIME ####

Sometimes Amazon Drive gives an error when a file has been fully
uploaded but the file appears anyway after a little while.  This
happens sometimes for files over 1GB in size and nearly every time for
files bigger than 10GB. These parameters control the time rclone waits
for the file to appear.

If the upload took less than `--acd-upload-wait-limit` (default 60s),
then we go ahead an upload it again as that will be quicker.

We wait `--acd-upload-wait-time` (default 2m) for the file to appear,
with an additional `--acd-upload-wait-per-gb` (default 30s) per GB of
the uploaded file.

These values were determined empirically by observing lots of uploads
of big files for a range of file sizes.

Upload with the `-v` flag to see more info about what rclone is doing
in this situation.

**Comment by felixbuenemann** [comment]
I've switched to the new build and am uploading a folder with lots of file in the 10GB range with the default settings. I've set stats delay to 15m so I can see what happened after a couple of days.

Btw. it would be great if rclone could print the filename of the file it is about to upload once, so one doesn't have to wait for the stats delay to see which file is currently uploaded.

**Comment by ncw** [comment]
I've merged this to master here: http://beta.rclone.org/v1.33-76-g5b83270/ (will be uploaded in 15-30 mins)

Let me know if you find any problems and I'll re-open the ticket if you do!
