### ISSUE TITLE
Getting error x509

### ISSUE THREAD

**Issue by Cadish** [ncw/rclone#713]
> What is your rclone version (eg output from `rclone -V`)
rclone v1.33

> Which OS you are using and how many bits (eg Windows 7, 64 bit)
QNAP QTS 4.2.2

> Which cloud storage system are you using? (eg Google Drive)
Amazon Cloud Drive

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
`rclone sync /share/Media/Photos ACD:/Photos --bwlimit 8M --checkers=16 --contimeout=5m --transfers=8 --retries=100 --stats 10s --drive-chunk-size 1024k --delete-excluded -c --dry-run -v`

> A log from the command with the `-v` flag (eg output from `rclone -v copy /tmp remote:tmp`)
`2016/09/09 19:56:19 Failed to create file system for "ACD:/Photos": failed to get endpoints: Get https://drive.amazonaws.com/drive/v1/account/endpoint: Post https://api.amazon.com/auth/o2/token: x509: certificate signed by unknown authority`

To setup my config, I created the config on my Macbook Pro, and entered the config via the headless configuration. 

Any idea what's going wrong?

Thanks
Cadish

**Comment by ncw** [comment]
This will probably help: http://rclone.org/faq/#rclone-gives-x509-failed-to-load-system-roots-and-no-roots-provided-error

I suspect you'll need to update the ssl roots - judging by the error message you have some already. 

You can also use --no-check-certificate which is insecure.

**Comment by Cadish** [comment]
Searched through Google for this, but didn't see this FAQ. Thanks for your swift reply: it's working now.

Thanks!

**Comment by ncw** [comment]
No problems. The error message you got wasn't exactly the one in the FAQ so don't feel bad about not finding it!
