### ISSUE TITLE
encrypted local filesystem(s) issue.

### ISSUE THREAD

**Issue by RXWatcher1** [ncw/rclone#714]
> What is your rclone version (eg output from `rclone -V`)
rclone v1.33-13-g7be4c3a-fuse-flagsβ

> Which OS you are using and how many bits (eg Windows 7, 64 bit)
Ubuntu 16.04

> Which cloud storage system are you using? (eg Google Drive)
Amazon Cloud Drive

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone ls eacd:
> A log from the command with the `-v` flag (eg output from `rclone -v copy /tmp remote:tmp`)
2016/09/11 00:54:56 rclone: Version "v1.33-13-g7be4c3a-fuse-flagsβ" starting with parameters ["rclone" "ls" "eacd:" "-v"]
2016/09/11 00:54:56 Encrypted Local file system at /home/jim/acd: Modify window is 1ns
2016/09/11 00:54:56
Transferred:      0 Bytes (0 Bytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:          0s
2016/09/11 00:54:56 Go routines at exit 2

config:
[eacd]
type = crypt
remote = acd
filename_encryption = standard
password = some_code
password2 = some_code

acd=remote
eacd: encrypted remote

The files I see if I do a "rclone ls eacd:" depend on where I was when I issued the rclone copy or rclone move command.

Example:
in /home/jim and issue rclone copy /local/path/to/files eacd:media/movies
it will create a /home/jim/acd and encrypt the files and upload them.
I can see them if I do a "rclone ls eacd:"

If I move to a different directory: /home/jim/mytest/dir/
and do "acd ls eacd:" it will be empty IF I havent ever been in that directory and uploaded something while in that directory. If I have uploaded something while in that directory I will see the files I uploaded while in the directory but not the files I uploaded from /home/jim

If I move back to /home/jim and do the "rclone ls eacd:" I will see the files I uploaded from that directory but no others.

I believe it depends on where the 'acd' encrypted local file system is. The one it makes before it uploads. Would it make sense to have that be in a consistent location? Like the users home directory?
 It appears to be the same size as the files that upload. If I look at my /home/jim/acd directory, its the size of the files I uploaded from there and if I look at my other one in /home/jim/mytest/dir/ its the size of the files I uploaded from there.

Does it ever flush and delete or refresh?

I've noticed my 'mount' and 'size' commands behave the same way.

**Comment by ncw** [comment]
Ah I see.  I think this is a doc issue rather as you aren't the first person to have this problem. You need to put a : after the remote name,  so `remote = acd:` otherwise you are just copying files to a local directory called acd. 

I should probably get the crypt remote to warn you or ask for confirmation if you enter a remote without a ":".

**Comment by RXWatcher1** [comment]
Yes, that was it. Thank you!
