### ISSUE TITLE
Error on Growing Files While Copying

### ISSUE THREAD

**Issue by DairyDTP** [ncw/rclone#717]
It appears that rclone first checks local filesize against the cloud, and then tries to use that filesize to PUT the file into the cloud. If however, the local file has grown in the meantime, this will error out.

I think it's more desirable to have a partial file uploaded (maybe even resume the upload later), than to just hit an error. Think about growing log files.

> What is your rclone version (eg output from `rclone -V`)
> rclone v1.33
> 
> Which OS you are using and how many bits (eg Windows 7, 64 bit)
> AMD64 
> 
> Which cloud storage system are you using? (eg Google Drive)
> OVH Openstack Swift
> 
> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
>  ./rclone --transfers 20 --verbose copy ~/foo/123/ foo:foo/123/
> 
> A log from the command with the `-v` flag (eg output from `rclone -v copy /tmp remote:tmp`)
> Attempt 3/3 failed with 13 errors and: Put https://storage.sbg1.cloud.ovh.net/v1/AUTH_.../foo/123/baz.abc: http: ContentLength=194392 with Body length 294032

**Comment by ncw** [comment]
Not sure what to do here - I don't see how rclone can do anything with a file that is changing.  You can't (in general) change files that have been uploaded to cloud storage systems.

**Comment by ncw** [comment]
I'm going to close this as I don't think there is a solution :-(

**Comment by bmiller59** [comment]
@ncw Thanks for rclone! The issue I encounter is when I am trying to backup a live directory like a dovecot folder, or a folder with log files, which has files that are constantly being appended to. Would it be possible to have an option to check the length at the start of the process to set the content-length and transfer only the content-length even if additional content has been added? That might be one solution.

**Comment by ncw** [comment]
@bmiller59 You should find this flag (also config setting) does what you want.

      --local-no-check-updated           Don't check to see if the files change during upload
