### ISSUE TITLE
Mount directories don't get removed

### ISSUE THREAD

**Issue by calisro** [ncw/rclone#719]
When filing an issue, please include the following information if
possible as well as a description of the problem.  Make sure you are
using the [latest version of rclone](http://rclone.org/downloads/).

> What is your rclone version (eg output from `rclone -V`)
1.33
> Which OS you are using and how many bits (eg Windows 7, 64 bit)
Linux 64
> Which cloud storage system are you using? (eg Google Drive)
ACD
> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

> A log from the command with the `-v` flag (eg output from `rclone -v copy /tmp remote:tmp`)

rclone -v --config=/home/robert/.rclone.conf mount robacd:/ ./c 2>&1 | tee -a rclone.log

┌[ ✓ robert [~] $
└─> cd c
┌[ ✓ robert [~/c] $
└─> mkdir test1
┌[ ✓ robert [~/c] $
└─> cd test1
┌[ ✓ robert [~/c/test1] $
└─> touch a b c
┌[ ✓ robert [~/c/test1] $
└─> cd ..
┌[ ✓ robert [~/c] $
└─> rm -rf test1
┌[ ✓ robert [~/c] $
└─> rclone lsd robacd:/
          -1 2016-03-07 17:03:20        -1 cloude
          -1 2016-04-21 18:09:31        -1 Pictures
          -1 2016-09-12 00:19:32        -1 cloudm
          **-1 2016-09-12 11:53:52        -1 test1**

[rclone.log.gz](https://github.com/ncw/rclone/files/467227/rclone.log.gz)

**Comment by calisro** [comment]
I just saw this.

https://github.com/ncw/rclone/issues/242

This is a duplicate then but this problem has larger issues on a mounted file system since when the directory is deleted, the mount thinks its gone but it isn't.  :)

This can be closed as a duplicate though.,

**Comment by ncw** [comment]
Yes #100 is the master ticket for this which will get fixed, we are getting closer!
