### ISSUE TITLE
Enhancement: Allow a 'delete to' directory similar to rsync's backup feature

### ISSUE THREAD

**Issue by calisro** [ncw/rclone#720]
Background:  Amazon Cloud Drive doesn't allow a user to 'empty' the trash.  I get hundreds of thousands of 'deleted' files because of the way in which rclone removes files rather than directories.  To make the problem even worse, Amazon only lets a user delete 1000 'objects' at a time.   Worse yet they don't provide an API to do it programatically.  I've actually had to create a iMacros browser job to purge it which I run periodically overnight to 'empty' the trash. :)

The way Amazon 'deletes' work is if a DIRECTORY is deleted, it puts the 'directory' object in the trash and then you can permanently delete that directory even if it contains hundreds of thousands of files.  You simply delete the ONE directory.  When files are deleted individually, all the files individually get put in the trash instead and you'd need to delete EACH file separately up to 1000 at a time via the GUI.

My thought is if we create a delete mechanism similar to rsync where we could specify a directory that deletes go to rather than actually deleting the files, then we could could go through and make purging the trash easier. Simply delete the directory to the trash and then to empty the trash, simply delete the directory once in a while.

rsync provides a similar functionality.
rsync:
 -b, --backup                make backups (see --suffix & --backup-dir)
     --backup-dir=DIR        make backups into hierarchy based in DIR
     --suffix=SUFFIX         set backup suffix (default ~ w/o --backup-dir)

I was thinking we could have the same options in rclone.  

The --backup tells rclone to move the files rather than delete them.  If a --backup-dir is not specified, it would (same as rsync) simply move them in the same hierarchy as they are in now but suffix them.  The default in rsync is the tilde but we could use a date-time or some other default if we wanted to.

The --backup-dir would move them directly to the backup-dir with the suffix (default if not specified).  We could follow the same functionality in rsync to create the hierarchy but we don't have to either.

The --suffix would let us override the default suffix.

So we would then specify --backup and optionally the other two depending on our needs and rclone wouldn't use the trash any longer.  It would backup via 'moves' to locations/naming we specify.  This also fixes the ACD problem of not being ale to empty the trash because we could then place entire folders in the trash and then purge it because we only need to 'delete permanently' the one record of the directory.

Thoughts?

**Comment by ncw** [comment]
Great idea - I've also found it really annoying emptying 1000s of items from the trash! Probably why I have 7,500 items in there at the moment!

There is a ticket about `--backup` and `--backup-dir` in #98 

There is also some related stuff in #18

**Comment by ncw** [comment]
I note that this would require #721 (which I just made) also.

**Comment by calisro** [comment]
I believe this is, for the most part, addressed. Closing this in favor of https://github.com/ncw/rclone/issues/98
