### ISSUE TITLE
Amazon drive - make it support Move and MoveDir

### ISSUE THREAD

**Issue by ncw** [ncw/rclone#721]
Amazon Drive could support Move and MoveDir but doesn't at the moment.  This would use the PATCH calls for nodes and dirs.

I don't think Amazon Drive can support Copy thought.

**Comment by Wowfunhappy** [comment]
> I don't think Amazon Drive can support Copy thought.

For what it's worth, the official web interface doesn't support copy either, so I'm pretty sure it's an intentional limitation (to keep people from using too much "unlimited storage").

**Comment by ncw** [comment]
I've merged this into #122

**Comment by eharris** [comment]
Requesting an update of http://rclone.org/overview/ to reflect that these options are now supported.

**Comment by ncw** [comment]
@eharris this will be updated when I make the next release which is now 20 days overdue, but RealLife	™ keeps getting in the way ;-)
