### ISSUE TITLE
Put rclone mount in the background

### ISSUE THREAD

**Issue by buttpain** [ncw/rclone#723]
Version: rclone v1.33

OS: Ubuntu 16.04

Cloud Storage: Amazon Cloud Drive

I have been trying to mount my amazon cloud drive, but unfortunately whenever I do it just stays stuck like this : https://gyazo.com/6b644e8b54c7c5fb4fca3144f86f536c

I can open other putty sessions so I know the machine hasn't frozen, but for some reason it's seems unable to mount.

**Comment by ncw** [comment]
The mount command doesn't run in the background. So stick an & on the end of the command and it will behave like you are expecting.

I will emphasize this in the docs as it is different to most fuse mounts. However it is hard getting go stuff to run in the background.

I should probably spend some more time trying to figure that out!

**Comment by robdidop** [comment]
I was totally confused when I tried to launch the rclone mount without the '&' at the end.
Please make this more obvious when mounting.

**Comment by ncw** [comment]
@robdidop I've moved this up to a feature request so I can actually put rclone mount in the background like it is supposed to be!

**Comment by ncw** [comment]
This looks like a good library

https://github.com/sevlyar/go-daemon

Also need to add `-f` or `--foreground` to not daemonise.
