### ISSUE TITLE
Support for server to server?

### ISSUE THREAD

**Issue by hjmangalam** [ncw/rclone#726]
This has probably been asked .. frequently, but does not apparently appear in the FAQs.
Can rclone support server to server transfers as opposed to server to cloud transfers? If not, is it being considered?

I've read the local filesystem bits and that's an option for some configs, but not nearly as useful as the server to server.

There have been some attempts at parallelizing rsync (fpsync, gnu parallel+rsync, parsync), but it seems that rclone would be a better solution in many cases.

Best wishes & and thanks for your work on the extraordinary rclone.
hjm

**Comment by ncw** [comment]
It is something I've been thinking about but have never written into an issue.

An `rclone serve` command would be the way forwards which might serve stuff over http/HTTPS or maybe would run over SSH. It could be quite simple...

You could have a go with minio (see rclone.org/s3 ) which runs an s3 server locally and works with rclone.

**Comment by ncw** [comment]
I put the serve idea in a new ticket #/1007 so I'm going to close this one
