### ISSUE TITLE
Automatic Mounting on reboot

### ISSUE THREAD

**Issue by RXWatcher1** [ncw/rclone#727]
Any ideas on how to make that happen? If there isnt anything can I please put in a enhancement request for it. I have tried a mount script in my users crontab for @restart and in /etc/rc.local. Neither worked.

Thank you!

**Comment by ncw** [comment]
You can put fuse mounts in the fstab - at least that is what the docs say, but I haven't tried it.

There may be a problem with that because rclone mount doesn't run in the background yet.

**Comment by RXWatcher1** [comment]
I'll give it a try. Thanks!

**Comment by ncw** [comment]
Let me know if it works or not!

**Comment by calisro** [comment]
You may want to just consider creating a script and calling it out of either systemd or out of /etc/fstab.  The problem you will run into with using /etc/fstab is that the system will attempt to mount those remotes before your network is ready.  

The KISS method would be adding something like this in /etc/rc.local

STATE="error"
while [  $STATE == "error" ]; do
    STATE=$(ping -q -w 1 -c 1 `ip r | grep default | cut -d ' ' -f 3` > /dev/null && echo ok || echo error)
    sleep 2
 done
/data/bin/cloudfs.sh mount >> /data/log/cloudfs.log

where /data/bin/cloudfs.sh is your script to mount the drive.

**Comment by calisro** [comment]
Hey, this is cool:
https://acd-cli.readthedocs.io/en/latest/FUSE.html#mount-options

**Comment by RXWatcher1** [comment]
I was thinking of how to make this more generic. List the user, options like --allow other in fstab to support more than one person or remote for the mount script. Look how ceph does it. example in the header:

https://github.com/ceph/ceph/blob/master/src/mount.fuse.ceph

**Comment by calisro** [comment]
Well.  This is my attempt at what you are looking for.

**Add entry in /etc/fstab:**
```
rclonemount#robert#local:/data/Media2      /home/robert/test    fuse  defaults   0 0
rclonemount#robert#local:/data/Media2      /home/robert/test    fuse  read-only,config=/home/robert/.rclone.conf   0 0
```


**file: /usr/bin/rclonemount**
```
#!/bin/sh
#
# Helper to mount rclone-fuse from /etc/fstab.  To use, add an entry
# like:
#
# # DEVICE                                   PATH                 TYPE  OPTIONS
# rclonemount#robert#local:/data/Media2      /home/robert/test    fuse  _netdev,defaults   0 0
# rclonemount#robert#local:/data/Media2      /home/robert/test    fuse  read-only,config=/home/robert/.rclone.conf   0 0
#
# where the device field is a comma-separated list of options to pass on
# the command line.  The examples above, for example, specify that
# rclone-fuse will authenticated as client.robert and client.deluge
# (respectively), and the second example also sets the 'config' option to
# '/home/robert/rclone.conf' via the rclone-fuse command line.  Any valid
# rclone-fuse can be passed in this way.
set -e

# id is mandatory. Specifiy 'root' if you want it run as root.
id=`echo $1 | cut -d '#' -f 1`
# path is mandatory. 
path=`echo $1 | cut -d '#' -f 2`
shift
mountpoint=$1; shift

while [ "$1" = "-o" ]
do
        shift
done

opts=$1

# strip out 'dev' option; rclone doesn't like it
opts=`echo $opts | sed 's/,dev//' | sed 's/dev,//'`
# strip out 'dev' option; rclone doesn't like it and its the default anyway
opts=`echo $opts | sed 's/,rw//' | sed 's/rw,//'`
# strip out 'suid option; rclone doesn't like it
opts=`echo $opts | sed 's/,suid//' | sed 's/suid,//' | sed 's/suid//'`

# convert device string to options
opts='--'`echo $opts | sed 's/,/ --/g'`

# go
su - $id -c "rclone $opts mount $path $mountpoint" &
```

**Comment by RXWatcher1** [comment]
wow. Thank you so much!

This should get put into the docs.

**Comment by calisro** [comment]
no problem.  Note that the _netdev is 'special' in that it will tell mount  NOT to mount it. :)  Which means you'll need something to mount it when the network is up or add logic to the rclonemount scirpt to wait on it and remote the _netdev from the options.

**Comment by RXWatcher1** [comment]
this is working with one small tweak:
su - $id -c "rclone mount $path $mountpoint $opts" &

rclone wants the options at the end.

**Comment by marcel5** [comment]
Tried your bash script but getting this error:
/usr/bin/rclonemount: 27: shift: can't shift that many

any idea how to solve this?

**Comment by darkdragon-001** [comment]
Progress tracked in #992.
