### ISSUE TITLE
Question:  Warning: File found with same name but different case on Encrypted amazon drive root

### ISSUE THREAD

**Issue by calisro** [ncw/rclone#728]
Just a question.  Should I be concerned about this at all?  On the encryption side, a file name will always hash out to the same encypted name.  Here it says it is the 'same name but different case' which i though was a bit odd.  Since they are all 'Folder.jpg', I would think it would be the same name exactly and perhaps the error message is actually just incorrect.

EDIT:  I see. The *actual* file is folder vs Folder in different directories.  I guess that is what it is flagging.  But should I be concerned?  I guess the only way I would run into a problem is if both those files existed in the SAME directory, correct?  i.e. both Folder.jpg and folder.jpg in the same directory.  but I would have still thought that the encrypted volume STILL should handle that with a different hash for both Folder and folder.

2016/09/12 19:35:42 Music/R.E.M/Dead Letter Office/Folder.jpg: Warning: File found with same name but different case on Encrypted amazon drive root 'cloudm'
2016/09/12 19:35:42 Music/R.E.M/Out Of Time/Folder.jpg: Warning: File found with same name but different case on Encrypted amazon drive root 'cloudm'
2016/09/12 19:35:42 Music/Led Zeppelin/Houses of the Holy/Folder.jpg: Warning: File found with same name but different case on Encrypted amazon drive root 'cloudm'
2016/09/12 19:35:43 Music/R.E.M/Murmur/Folder.jpg: Warning: File found with same name but different case on Encrypted amazon drive root 'cloudm'
2016/09/12 19:35:43 Music/R.E.M/Lifes Rich Pageant/folder.jpg: Warning: File found with same name but different case on Encrypted amazon drive root 'cloudm'

**Comment by ncw** [comment]
To get that message you need to have two files with the same name and different case.  This can be n the same directory

  * `Music/R.E.M/Dead Letter Office/Folder.jpg`
  * `Music/R.E.M/Dead Letter Office/Folder.jpg`

Or two different directories like this

* `Music/R.E.M/Dead Letter Office/Folder.jpg`
* `Music/r.e.m/Dead Letter Office/Folder.jpg`

The error is only a warning and won't affect you with an encrypted file system with encrypted names.  It is there for transfers to from Windows / OS X or unencrypted ACD where it would be a problem.

**Comment by calisro** [comment]
That was my thinking as well.  I know in encfs you have to ensure that the underlying encrypted algorithm you select is compliant with a case insensitive file system (like on ACD).  I was concerned that the files underlying the crypt file system here could be at risk as I am not as familiar with crypt as I am with encfs.  Thanks for confirming.

**Comment by calisro** [comment]
and for others, it looks like the crypted filesystem itself is case sensitive so this seems to work and it perfectly acceptable:

┌[ ✓ robert [~] $
└─> mkdir test
┌[ ✓ robert [~] $
└─> cd test
┌[ ✓ robert [~/test] $
└─> touch abc
┌[ ✓ robert [~/test] $
└─> touch aBc
┌[ ✓ robert [~/test] $
└─> touch abC
┌[ ✗ robert [~/test] $
└─> rclone copy local:/home/robert/test/ robacd-crypt:/test
2016/09/13 13:48:46 Encrypted amazon drive root 'cloudm/js4fll2u3v7vhg0livfaqblq6g': Waiting for checks to finish
2016/09/13 13:48:46 Encrypted amazon drive root 'cloudm/js4fll2u3v7vhg0livfaqblq6g': Waiting for transfers to finish
2016/09/13 13:48:48 
Transferred:      0 Bytes (0 Bytes/s)
Errors:                 0
Checks:                 0
Transferred:            3
Elapsed time:        2.7s
┌[ ✓ robert [~/test] $
└─> rclone lsl robacd-crypt:/test
        0 2016-09-13 13:48:47.633000000 abc
        0 2016-09-13 13:48:47.853000000 abC
        0 2016-09-13 13:48:48.101000000 aBc
2016/09/13 13:49:05 
Transferred:      0 Bytes (0 Bytes/s)
Errors:                 0
Checks:                 3
Transferred:            0
Elapsed time:        2.3s
┌[ ✓ robert [~/test] $
└─> rclone lsl robacd:/cloudm/js4fll2u3v7vhg0livfaqblq6g
       32 2016-09-13 13:48:47.633000000 69esa7r0dsr4a3lkr1vvhhv6io
       32 2016-09-13 13:48:47.853000000 m06qebc633ivtbkbqjo2qrghvs
       32 2016-09-13 13:48:48.101000000 45d23v0nbet8jmthtmjfpg8uhg
2016/09/13 13:49:48 
Transferred:      0 Bytes (0 Bytes/s)
Errors:                 0
Checks:                 3
Transferred:            0
Elapsed time:       700ms

**Comment by ncw** [comment]
Yes you are right, the crypted file system is case sensitive, even when running on a case insensitive remote -something I should probably put in the docs somewhere.

**Comment by DurvalMenezes** [comment]
Thanks @calisro and @ncw for this post, really clarified things for me as I'm getting a ton of those messages. For those that come a-googling, I want to point out that the similar message "Warning: File found with same name but different case **on Local file system at**" means exactly the same thing, but on the local filesystem and (unless you are planning to copy it to a case-insensitive filesystem) it can also be safely ignored.
