### ISSUE TITLE
logout cloud drive

### ISSUE THREAD

**Issue by lsching17** [ncw/rclone#729]
rclone v1.33, Windows 7 x64. Amazon cloud drive

I login amazon cloud drive via rclone and sent the configuration file to my family to backup.

The backup completed and i want to revoke the access token.

How do i "logout" the cloud drive?

**Comment by ncw** [comment]
If you go to the amazon drive web page, then click the menu in the top right corner - go to "Account Settings" then under "Manage Third Party Apps", click on manage settings, you'll get to a page where you can remove rcone from your account.

You'll need to go through the registration process if you want to use it again.

**Comment by lsching17** [comment]
Thanks

But i find out that there is only 1 "rclone" application there, and removing it logout "ALL" my rclone folders of amazon.

i guess that is the limitation of amazon?

**Comment by ncw** [comment]
Yes I'm afraid that is an Amazon limitation.

**Comment by lsching17** [comment]
thanks for your help very much
