### ISSUE TITLE
Failed to load config file "/root/.rclone.conf"

### ISSUE THREAD

**Issue by kiwiapple87** [ncw/rclone#730]
When filing an issue, please include the following information if
possible as well as a description of the problem.  Make sure you are
using the [latest version of rclone](http://rclone.org/downloads/).

> What is your rclone version (eg output from `rclone -V`)
> **1.33-DEV**
> Which OS you are using and how many bits (eg Windows 7, 64 bit)
> **Arch Linux 64 bit**
> Which cloud storage system are you using? (eg Google Drive)
> **Google Drive**
> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
> **sudo rclone --dry-run --exclude-from ~/usr/rclone/exclude_file.txt sync source:/ remote:Archlinux**
> A log from the command with the `-v` flag (eg output from `rclone -v copy /tmp remote:tmp`)

**I am getting this error when I try to run the above command**
2016/09/14 09:54:17 Failed to load config file "/root/.rclone.conf" - using defaults: open /root/.rclone.conf: no such file or directory
2016/09/14 09:54:17 Failed to create file system for "source:/": didn't find section in config file

I went through the prompts from the command 'rclone config' to create the .rclone.conf file.

How do I change where it looks for .rclone.conf? I have it is my /home/alex directory not in /root.

**Comment by justusiv** [comment]
To me it sounds like you ran the config not as root then you are running rclone as root.
Either way you can specify which conf file to point to with this command. Pulled straight from the docs

--config=CONFIG_FILE
Specify the location of the rclone config file. Normally this is in your home directory as a file called .rclone.conf. If you run rclone -h and look at the help for the --config option you will see where the default location is for you. Use this flag to override the config location, eg rclone --config=".myconfig" .config.

**Comment by kiwiapple87** [comment]
Ah thank you

**Comment by ncw** [comment]
Glad it is sorted - will close now
