### ISSUE TITLE
internal errors with b2

### ISSUE THREAD

**Issue by marrie** [ncw/rclone#732]
When filing an issue, please include the following information if
possible as well as a description of the problem.  Make sure you are
using the [latest version of rclone](http://rclone.org/downloads/).

> What is your rclone version (eg output from `rclone -V`) 1.33

> Which OS you are using and how many bits (eg Windows 7, 64 bit)

Mac os el capitan 64 bit
> Which cloud storage system are you using? (eg Google Drive)

Backblaze b2
> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

Rclone sync
> A log from the command with the `-v` flag (eg output from `rclone -v copy /tmp remote:tmp`)

[log.zip](https://github.com/ncw/rclone/files/473903/log.zip)

When using the rclone sync (I've seen this wiht the rclone copy to) I'll get unable to remove copy internal error. I noticed it today at about 19:00 or maybe a bit earlier. Do I need to run a rclone cleanup on the flder to make sure it does remove these versions or is somethingg broken someware? Sorry the log file is so big.

**Comment by ncw** [comment]
It looks like this is the same issue as #689 - you have a file called "Icon" with a carriage return on the end.

I'll post a beta when I've done a fix for it.

In the mean time you could add `--exclude 'Icon?'` to your command line to not sync those files.

**Comment by marrie** [comment]
Actually I was referring to the section that went



2016/09/14 19:10:36 Robert Jordan/Robert Jordan - 05 - The Fires of Heaven/Jordan, Robert - 05 - The Fires of Heaven/53 Chapter 52_ Choices.mp3: Clearing upload URL because of error: Not enough members for write of 4_zb048f0bb5d84d7865b660a15_f103707d48c08a63b_d20160915_m014628_c000_v0001010_t0017: neighbor_down; neighbor_down (500 internal_error)
2016/09/14 19:10:36 pacer: Rate limited, increasing sleep to 20ms
2016/09/14 19:10:36 pacer: low level retry 1/1 (error Not enough members for write of 4_zb048f0bb5d84d7865b660a15_f103707d48c08a63b_d20160915_m014628_c000_v0001010_t0017: neighbor_down; neighbor_down (500 internal_error))
2016/09/14 19:10:36 Robert Jordan/Robert Jordan - 05 - The Fires of Heaven/Jordan, Robert - 05 - The Fires of Heaven/53 Chapter 52_ Choices.mp3: Failed to copy: Not enough members for write of 4_zb048f0bb5d84d7865b660a15_f103707d48c08a63b_d20160915_m014628_c000_v0001010_t0017: neighbor_down; neighbor_down (500 internal_error)
2016/09/14 19:10:36 Robert Jordan/Robert Jordan - 05 - The Fires of Heaven/Jordan, Robert - 05 - The Fires of Heaven/53 Chapter 52_ Choices.mp3: Removing failed copy
2016/09/14 19:10:36 pacer: Reducing sleep to 10ms
2016/09/14 19:10:36 Robert Jordan/Robert Jordan - 05 - The Fires of Heaven/Jordan, Robert - 05 - The Fires of Heaven/53 Chapter 52_ Choices.mp3: Failed to remove failed copy: failed to delete file: File not present: 3archives/books/Robert Jordan/Robert Jordan - 05 - The Fires of Heaven/Jordan, Robert - 05 - The Fires of Heaven/53 Chapter 52_ Choices.mp3 (400 no_such_file)
2016/09/14 19:10:37 graphic audio/Eileen Wilks/World of the Lupi/6 Blood Magic/6 Blood Magic.rar: Sending chunk 6 length 100663296
 

Also  the excerpt


2016/09/14 18:51:44 Robert Jordan/Robert Jordan - 06 - Lord of Chaos/Jordan, Robert - 06 - Lord of Chaos/49 Chapter 45_ A Bitter Thought.mp3: Failed to remove failed copy: failed to delete file: File not present: 3archives/books/Robert Jordan/Robert Jordan - 06 - Lord of Chaos/Jordan, Robert - 06 - Lord of Chaos/49 Chapter 45_ A Bitter Thought.mp3 (400 no_such_file)
2016/09/14 18:51:44 auto biographies/Claire McCaskill Plenty Ladylike/Claire McCaskill Plenty Ladylike/Plenty Ladylike Description.txt: Failed to remove failed copy: failed to delete file: File not present: 3archives/books/auto biographies/Claire McCaskill Plenty Ladylike/Claire McCaskill Plenty Ladylike/Plenty Ladylike Description.txt (400 no_such_file)

So why won't rclone  remove them in the destination ? My source is fine, I have these files.

**Comment by ncw** [comment]
When there is an upload failure rclone deletes the upload so you don't get a partial upload (something I'm going to modify in #559). If it didn't get uploaded then the delete fails.

**Comment by marrie** [comment]
Ah, Ok.  So I  or anyone else  don't really need to worry about those then?

Thanks.

**Comment by ncw** [comment]
No need to worry :-)
