### ISSUE TITLE
rclone SYNC option should be able to modify BOTH destination AND source.

### ISSUE THREAD

**Issue by MoonShadow-NM** [ncw/rclone#736]
The issue that I am having, is there is no way to run this as a cronjob and reliably sync files between my computer and Dropbox.
GOAL: To have files synchronized between local and Dropbox.  So, if a file changes at either location, it is updates at the other location.

Examples:

SOURCE: Dropbox
DESTINATION: local
OPERATION: copy -u
OUTCOME: Older file NOT copied to local (which is good)

SOURCE: Dropbox
DESTINATION: local
OPERATION: sync -u
OUTCOME: Older file in Dropbox not copied to local (which is good), newer file on local NOT copied to Dropbox (not an actual sync)
EXPECTED OUTCOME: Newer file on local copied to Dropbox (remote).  Or to reword this, the newer file in EITHER location is copied (synced) to the other location.

> What is your rclone version (eg output from `rclone -V`)
1.33

> Which OS you are using and how many bits (eg Windows 7, 64 bit)
Ubuntu 16.04 x86_64

> Which cloud storage system are you using? (eg Google Drive)
Dropbox

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone sync -u dropbox: /home/moonshadow/Dropbox/

> A log from the command with the `-v` flag (eg output from `rclone -v copy /tmp remote:tmp`)
N/A

**Comment by ncw** [comment]
What you really want is biderectional sync: #/118

I'm going to close this as a duplicate - can you press the subscribe button on that issue and you'll get notifications of updates there.

**Comment by MoonShadow-NM** [comment]
Thanks.  That's it!
