### ISSUE TITLE
Strange error chtimes operation not permitted

### ISSUE THREAD

**Issue by polanskya** [ncw/rclone#738]
I am trying to clone copy between  directory on linux to a windows shared mounted   using "cifs". 

All the new files that needs to be created on the target system , fail with the Error " Failed to copy: chtimes /mnt/ntserver/TestDeploy/boma/Functions/storeFunctions.asp: operation not permitted" 
 
However the file does make it to the distention.. 

Any idea what could be the problem?

> What is your rclone version (eg output from `rclone -V`)

1.33

> Which OS you are using and how many bits (eg Windows 7, 64 bit)

Source : Debian Linux 64, Target: Windows Server 2012 Mounted share: 
(mount -v -t cifs  //serverIP/dev /mnt/ntserver -o credentials=/etc/smb_credentials.txt,file_mode=0777,dir_mode=0777)

> Which cloud storage system are you using? (eg Google Drive)

Local  copy from linux to windows cifs mounted share

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

> A log from the command with the `-v` flag (eg output from `rclone -v copy /tmp remote:tmp`)

```
rclone copy --exclude-from=target-exclude-list.txt --size-only=true --verbose --transfers=5 --modify-window=15s --checkers=12 --no-update-modtime=true  /var/lib/jenkins/workspace/boma   /mnt/ntserver/TestDeploy/boma
```

Error : 
```
2016/09/20 15:36:31 Functions/storeFunctions.asp: Failed to copy: chtimes /mnt/ntserver/TestDeploy/boma/Functions/storeFunctions.asp: operation not permitted
2016/09/20 15:36:31 Attempt 1/3 failed with 1 errors and: chtimes /mnt/ntserver/TestDeploy/boma/Functions/storeFunctions.asp: operation not permitted
```

The file eventually makes it to the server..

**Comment by ncw** [comment]
Are the files on the CIFS mount owned by the user using rclone?  rclone is probably trying to update the modtimes on files that user doesn't own.

Check the files on the mount, eg `ls -l /mnt/ntserver/TestDeploy/boma/Functions` to see which user owns them.

**Comment by polanskya** [comment]
on an mount with ls -l files owned by "root" .. The process that run "rclone" command are run as  "jenkins" user. 

Is there good  way to fix this?

**Comment by ncw** [comment]
That looks like the right solution :-)

**Comment by ncw** [comment]
I see you made another issue about the info printing (good idea)

So I'll close this one now
