### ISSUE TITLE
Additional log levels - eg to see files transfers  only

### ISSUE THREAD

**Issue by polanskya** [ncw/rclone#739]
Is there a way to tune the log message to print information for files / folders that are being copied? in Regular mode, it does not tell you what files are being copied, but you get final statistics.. in Verbose mode, i get too much information that includes analysts and skipping of the files.. 
I am trying to log only artifacts that are being copied to the destination.. 

I am doing "rclon copy"  - v 1.3.3
Thanks

**Comment by marrie** [comment]
I'm also wondering a similar thing. See the issue I just filed Maybe a combination of my question and your issue?

**Comment by ncw** [comment]
There isn't a way of doing that at the moment.  What would you like to see - a `--log-transferred` flag or something like that?

**Comment by marrie** [comment]
Maybe a log level flag something like

--log-levels-transfers

So you can have something like

--log-level=debug
--log-level=verbose
--log-level=transfers

And if you don't want to see any of it just do 

-q

in  Your script a along with the --log-file=filename.log

Thoughts? I hope I understand what the poster and you were saying.

**Comment by ncw** [comment]
Yes something like that seems sensible.

At the moment there are 3 log levels

  * errors only `-q`
  * info (no flag)
  * debug `-v`

We'd need to slip a fourth one in, say

  * errors only `-q` `--log-level errors`
  * info (no flag) `--log-level info`
  * transfers `--log-level transfers`
  * debug `-v` `--log-level debug`

The transfers level should log the Copied lines that you get from `-v` and any deleted lines, but nothing else (no skipping etc)

**Comment by marrie** [comment]
sounds like a good idea.  Still getting used to scripting, so that was off the top of my head.

Hopefully the original poster will chime in with their idea.

**Comment by polanskya** [comment]
I was able to scrap the rclone output in my calling go programm.. Here is what i did if anyone intrestead: 

c := exec.Command(rclone, rcloneArgs...)

var outbuf, errbuf bytes.Buffer
	c.Stdout = &outbuf
	c.Stderr = &errbuf
	c.Run()
	//log.Warning("Waiting for command to finish...")
	done := make(chan error, 1)
	go func() {
		done <- c.Wait()
	}()
	resp := buildRcloneResponse(outbuf, errbuf)


.....
func buildRcloneResponse(outbuf bytes.Buffer, errbuf bytes.Buffer) map[string]map[int]string {
	resp := make(map[string]map[int]string)
//Scann sterror for summary
	scanner := bufio.NewScanner(&errbuf)
	summaryResp := make(map[int]string)
	i := 0
	for scanner.Scan() {

		s := strings.TrimSpace(scanner.Text())
		// Take usefull summary
		if strings.HasPrefix(s, "Transferred") || strings.HasPrefix(s, "Errors") || strings.HasPrefix(s, "Checks") || strings.HasPrefix(s, "Elapsed") {
			summaryResp[i] = s
			i++
			//log.Warning("se:", s)
		}
	}

	if i > 0 {
		resp["summary"] = summaryResp
		i = 0
	}
	detailResp := make(map[int]string)
	scanner = bufio.NewScanner(&outbuf)
//scan stout for file transfer details
	for scanner.Scan() {
		s := strings.TrimSpace(scanner.Text())
		//log.Warning("$" + s + "$")
// Strip stuff that not needed 
		if strings.Contains(s, "Go routines") || strings.Contains(s, "Sizes identical") || strings.Contains(s, "Unchanged skipping") ||
			strings.Contains(s, "rclone: Version") || strings.Contains(s, "Local file system at") || strings.Contains(s, "Sizes differ") {
			continue
		}
		 else {
// Strip out log date from
		sub := s[20:len(s)]
		detailResp[i] = sub
		i++
	
	}

	if i > 0 {
		resp["detail"] = detailResp
	}

	return resp
}

**Comment by calisro** [comment]
My suggestion is to classify the log entries better and use a level approach like 'WARN|ERROR|CRTICAL|FATAL" etc. Then we can just select the verbosity level.

We could then prefix each level in the log for a greppable/searchable reasons. 

ERROR: <entry>
WARN: <entry>
…

**Comment by ncw** [comment]
After a bit of thought about this, I think that I should take rclone back to its rsync roots and make -v only show file transfers and do this

- errors only `-q` `--log-level errors`
- info (no flag) `--log-level info`
- transfers `-v` `--log-level transfers`
- debug `-vv` `--log-level debug`

At the moment transfers and debug are combined into one level.  I'd split them and into transfers I'd put any files which were

  * uploaded
  * downloaded
  * renamed
  * server side copied
  * server side moved
  * deleted

Everything else would go into the debug level which I'd make a shortcut of -vv to use.

I'm also proposing to send all logs to stderr by default (at the moment the -v log goes to stdout).

Being able to send the logs to [syslog](https://golang.org/pkg/log/syslog/) would be extremely useful, so I propose adding a --syslog optionc (especially for rclone mount) and in that case the rclone log levels should probably match up with syslog levels

  * LOG_EMERG      system is unusable
  * LOG_ALERT      action must be taken immediately
  * LOG_CRIT       critical conditions
  * LOG_ERR        error conditions
  * LOG_WARNING    warning conditions
  * LOG_NOTICE     normal, but significant, condition
  * LOG_INFO       informational message
  * LOG_DEBUG      debug-level message

I'd propose making the 4 levels match up like this

- errors only `-q` `--log-level errors` - LOG_ERR
- info (no flag) `--log-level info` - LOG_NOTICE
- transfers `-v` `--log-level transfers` - LOG_INFO
- debug `-vv` `--log-level debug`  LOG_DEBUG

As for @calisro's suggestion of prefixing the log messages with an identifier - I'm not sure about that.  It could be an option?

**Comment by calisro** [comment]
Is there a reason why you'd default to stderr vs stdout?  If someone is enabling logging, they'll want it without having to do "2>&1" or something.  

Im trying to see if I would be able to use the new log scheme in my approach but i'm not sure.  What I do today is this:

 rclone sync "remote:/" 2>&1 | egrep -v "$CRYPTLOGFILTER"

For the LOGFILTERs I prune out things that clutter my logs and I have no use for as follows:

LOGFILTER="eading|Sizes identical|Unchanged skipping|time the same|Excluding from sync|transfer non file/directory|Excluded from sync|Size and MD5 of src and dst objects identical"
CRYPTLOGFILTER="$LOGFILTER|File found with same name but different case"

What are you intending on sending to INFO (default) versus the transfers/debug?  I'm just trying to see how that matches up to my pruning.

**Comment by ncw** [comment]
@calisro 
> Is there a reason why you'd default to stderr vs stdout?
Sorry that was a typo!  Have corrected the above post - logs will go to stdout!

I think all the things in your LOGFILTER would be in the debug level so you'd need `-vv` to see them.

Not sure about "File found with same name but different case" - is that a debug or an info?  It is currently an info.  Why do you see that in your transfers?

> What are you intending on sending to INFO (default) versus the transfers/debug? I'm just trying to see how that matches up to my pruning.

I plan to leave info (default) level pretty much as is.  That doesn't receive a lot of logs normally anyway.

The transfers level will match up with what you want to see I think - that is my intention.

**Comment by ncw** [comment]
I have reworked the logging - please have a go with it in this beta

http://beta.rclone.org/v1.35-87-g006227b/ (uploaded in 15-30 mins)

Here are the bits from the docs

## Logging ##

rclone has 4 levels of logging, `Error`, `Notice`, `Info` and `Debug`.

By default rclone logs to standard error.  This means you can redirect
standard error and still see the normal output of rclone commands (eg
`rclone ls`).

By default rclone will produce `Error` and `Notice` level messages.

If you use the `-q` flag, rclone will only produce `Error` messages.

If you use the `-v` flag, rclone will produce `Error`, `Notice` and
`Info` messages.

If you use the `-vv` flag, rclone will produce `Error`, `Notice`,
`Info` and `Debug` messages.

You can also control the log levels with the `--log-level` flag.

If you use the `--log-file=FILE` option, rclone will redirect `Error`,
`Info` and `Debug` messages along with standard error to FILE.

If you use the `--syslog` flag then rclone will log to syslog and the
`--syslog-facility` control which facility it uses.

Rclone prefixes all log messages with their level in capitals, eg INFO
which makes it easy to grep the log file for different kinds of
information.

**Comment by ncw** [comment]
I messed up with that beta - try this one instead http://beta.rclone.org/v1.35-92-g18c75a8/ (uploaded in 15-30 mins)

**Comment by hongkongkiwi** [comment]
After this discussion is there a conclusion on how I can log transfers only? 

Right now I have this line in my INFO log:

`2018/05/12 15:03:15 INFO  : Google drive root '': Modify window is 1s`

I don't want this, I only want to log files that have had some action taken, e.g. copied new or something

**Comment by ncw** [comment]
@hongkongkiwi the INFO level will be nearly all file transfers but there are a few other things in there.  There isn't a way at the moment to only show file transfers.
