### ISSUE TITLE
'Name already exists' and I/O error on ACD

### ISSUE THREAD

**Issue by isaiah36** [ncw/rclone#740]
When filing an issue, please include the following information if
possible as well as a description of the problem.  Make sure you are
using the [latest version of rclone](http://rclone.org/downloads/).

> What is your rclone version (eg output from `rclone -V`)
v1.33

> Which OS you are using and how many bits (eg Windows 7, 64 bit)
Ubuntu 16 64bit

> Which cloud storage system are you using? (eg Google Drive)
Amazon

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
sync

> A log from the command with the `-v` flag (eg output from `rclone -v copy /tmp remote:tmp`)
[rclone-log-0921.txt](https://github.com/ncw/rclone/files/485579/rclone-log-0921.txt)

I am getting these for a few days now.  Remote deletions fail due to I/O error.  It started with a single file with extension JPG in all caps.  Changing it to lower case solved it for a couple of days.  

Now it seems to have nothing to do with that, or it may have since I have not manually inspected the directories.  I know I changed the extensions to lower case for some files, but that mission is not complete yet because Windows does not do case sensitive search, and the Ubuntu search does not work at all.

TIA

**Comment by isaiah36** [comment]
I used the Batch Rename Utility to change all JPG extensions to jpg.  I cannot delete them from ACD because it does not do case sensitive search.  Is there a command that will make rclone delete all files with .JPG extension in a case sensitive manner?

**Comment by ncw** [comment]
Looking at your log, it looks like those `.JPG` files are causing the problem.

If you do

    rclone ls --include "*.JPG" remote:path

rclone will show you the JPG files.  rclone is always case sensitive.

If happy with the list you can then do

    rclone delete --include "*.JPG" remote:path

**Comment by isaiah36** [comment]
Thank you!  The sync tonight should replace all the deleted files.  I'll confirm after checking the log in the morning.

**Comment by isaiah36** [comment]
Clean log. Deletions completed. Thank you!
