### ISSUE TITLE
ACD error HTTP code 409 conflict NAME_ALREADY_EXISTS

### ISSUE THREAD

**Issue by lanrat** [ncw/rclone#742]
When syncing my music directory to ACD I have a few files that I get `NAME_ALREADY_EXISTS` errors on. I have checked using the web interface and these files do not already exist. Below is the verbose info and logs for just one for the files.

> What is your rclone version (eg output from `rclone -V`)

`rclone v1.33`

> Which OS you are using and how many bits (eg Windows 7, 64 bit)

Debian Linux 8 (Jessie)

> Which cloud storage system are you using? (eg Google Drive)

Amazon Cloud Drive

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

`/rclone --config rclone.conf --verbose --log-file errorv.log sync "~/media/Music/Music/Red Hot Chili Peppers/Under the Covers/08. Red Hot Chili Peppers - Castles Made of Sand.mp3" "acd:media/Music/Red Hot Chili Peppers/Under the Covers/08. Red Hot Chili Peppers - Castles Made of Sand.mp3"`

> A log from the command with the `-v` flag (eg output from `rclone -v copy /tmp remote:tmp`)

```
2016/09/21 19:16:28 rclone: Version "v1.33" starting with parameters ["./rclone" "--config" "rclone.conf" "--verbose" "--log-file" "errorv.log" "sync" "~/media/Music/Music/Red Hot Chili Peppers/Under the Covers/08. Red Hot Chili Peppers - Castles Made of Sand.mp3" "acd:media/Music/Red Hot Chili Peppers/Under the Covers/08. Red Hot Chili Peppers - Castles Made of Sand.mp3"]
2016/09/21 19:16:30 amazon drive root 'media/Music/Red Hot Chili Peppers/Under the Covers/08. Red Hot Chili Peppers - Castles Made of Sand.mp3': Modify window not supported
2016/09/21 19:16:30 Attempt 1/3 failed with 1 errors and: failed to make directory: HTTP code 409: "409 Conflict", reponse body: {"code":"NAME_ALREADY_EXISTS","logref":"9329d64f-806a-11e6-87b7-2f71c05fbae6","message":"Node with the name under the covers already exists under parentId YEB9_4-FSzOiZsHqhHho-g conflicting NodeId: iP7FiYBXQ1mITK9A02ZJkQ","info":{"nodeId":"iP7FiYBXQ1mITK9A02ZJkQ"}}
2016/09/21 19:16:30 Attempt 2/3 failed with 1 errors and: failed to make directory: HTTP code 409: "409 Conflict", reponse body: {"code":"NAME_ALREADY_EXISTS","logref":"934e27ba-806a-11e6-8356-95c96e77ed68","message":"Node with the name under the covers already exists under parentId YEB9_4-FSzOiZsHqhHho-g conflicting NodeId: iP7FiYBXQ1mITK9A02ZJkQ","info":{"nodeId":"iP7FiYBXQ1mITK9A02ZJkQ"}}
2016/09/21 19:16:31 Attempt 3/3 failed with 1 errors and: failed to make directory: HTTP code 409: "409 Conflict", reponse body: {"code":"NAME_ALREADY_EXISTS","logref":"937250a0-806a-11e6-9fe6-5b24b6ff85d0","message":"Node with the name under the covers already exists under parentId YEB9_4-FSzOiZsHqhHho-g conflicting NodeId: iP7FiYBXQ1mITK9A02ZJkQ","info":{"nodeId":"iP7FiYBXQ1mITK9A02ZJkQ"}}
2016/09/21 19:16:31 Failed to sync: failed to make directory: HTTP code 409: "409 Conflict", reponse body: {"code":"NAME_ALREADY_EXISTS","logref":"937250a0-806a-11e6-9fe6-5b24b6ff85d0","message":"Node with the name under the covers already exists under parentId YEB9_4-FSzOiZsHqhHho-g conflicting NodeId: iP7FiYBXQ1mITK9A02ZJkQ","info":{"nodeId":"iP7FiYBXQ1mITK9A02ZJkQ"}}
```

I have tried deleting my entire Music folder and re-uploading it but that seems to double the amount of files that produced errors. It seems as if deleting does not always work fully. (the files are not viewable in the web interface)

Possibly unrelated, but I did just switch from using [acd_cli](https://github.com/yadayada/acd_cli) to rclone. One of the reasons for switching is because acd_cli would throw LOTS of errors on my media.

**Comment by javier-gotham2** [comment]
I'm geting the same kind of issues. First time I have used rclone or ACD

2016/09/22 02:35:28 IMAGES/Microsoft/WINDOWS 10/Win10_1511_English_x64.iso: Failed to copy: failed to make directory: HTTP code 409: "409 Conflict", r
eponse body: {"code":"NAME_ALREADY_EXISTS","logref":"c08a9e83-808e-11e6-aa5d-c147e65afed4","message":"Node with the name windows 10 already exists und
er parentId IAodEDmfS5WiX1DO2lQxHA conflicting NodeId: QpLQk-OVTualgTomlHaQKQ","info":{"nodeId":"QpLQk-OVTualgTomlHaQKQ"}}
2016/09/22 02:35:28 IMAGES/Microsoft/WINDOWS 10/10586.0.151029-1700.TH2_Release_IOTCoreRPi_armFRE.ISO: Failed to copy: failed to make directory: HTTP 
code 409: "409 Conflict", reponse body: {"code":"NAME_ALREADY_EXISTS","logref":"c0a41941-808e-11e6-a8dc-b5cf3e680a4b","message":"Node with the name wi
ndows 10 already exists under parentId IAodEDmfS5WiX1DO2lQxHA conflicting NodeId: QpLQk-OVTualgTomlHaQKQ","info":{"nodeId":"QpLQk-OVTualgTomlHaQKQ"}}
2016/09/22 02:35:28 IMAGES/Microsoft/WINDOWS 10/en_windows_10_pro_10159_x64_dvd.iso: Failed to copy: failed to make directory: HTTP code 409: "409 Con
flict", reponse body: {"code":"NAME_ALREADY_EXISTS","logref":"c0bf69fc-808e-11e6-af0e-53aa35e62307","message":"Node with the name windows 10 already e
xists under parentId IAodEDmfS5WiX1DO2lQxHA conflicting NodeId: QpLQk-OVTualgTomlHaQKQ","info":{"nodeId":"QpLQk-OVTualgTomlHaQKQ"}}
2016/09/22 02:35:44 amazon drive root 'data': Waiting for checks to finish
2016/09/22 02:35:44 amazon drive root 'data': Waiting for transfers to finish
2016/09/22 02:35:44 Attempt 1/3 failed with 3 errors and: failed to make directory: HTTP code 409: "409 Conflict", reponse body: {"code":"NAME_ALREADY
_EXISTS","logref":"c0bf69fc-808e-11e6-af0e-53aa35e62307","message":"Node with the name windows 10 already exists under parentId IAodEDmfS5WiX1DO2lQxHA
 conflicting NodeId: QpLQk-OVTualgTomlHaQKQ","info":{"nodeId":"QpLQk-OVTualgTomlHaQKQ"}}
2016/09/22 02:35:47


The file does exist from a previous copy and subsequent sync.

**Comment by ncw** [comment]
@lanrat What ACD seems to be saying is that you have a directory called "under the covers" and another called "Under the Covers".  rlone treats these as separate directories, but ACD treats them as the same, hence the conflict error.

Can you check if acd_cli uploaded the directory as "under the covers" maybe?  That would explain the problem

**Comment by ncw** [comment]
@javier-gotham2 you seem to have a similar problem with "windows 10" and "WINDOWS 10".  I'd guess you are using windows so that is unlikely to be actually the case.

Can you check what the directory is actually called - and also sending a log with -v would be helpful.

**Comment by lanrat** [comment]
@ncw You are correct, I have multiple folders with different capitalization. Since running into this issue I've deleted my entire "Music" directory on ACD and re-uploaded it using rclone, so I'm not sure which one acd_cli used.

For future reference, I used the following command to find all my naming conflicts on my local file system and fixed them.
`find . | sort | uniq -Di`
Then I deleted them from ACD, and re-ran rclone with no issues!

You are free to close this issue once you help @javier-gotham2.

**Comment by javier-gotham2** [comment]
@ncw I'm actually running this from a linux vm where I have my zfs storage box mounted to.

It just happens to be a windows 10 iso ACD is complaining about.

@lanrat I'm going to check for dups as @ncw did.

I'll report back. I may have some created that I haven't noticed.

**Comment by javier-gotham2** [comment]
@lanrat @ncw and what do you know:

./data/IMAGES/Microsoft/Windows 10
./data/IMAGES/Microsoft/WINDOWS 10


plus a few more.  Thanks guys. And thanks for rclone.

I have been telling all my friends about it.

- J
