### ISSUE TITLE
1.33 build posted for *BSD is actually 1.26

### ISSUE THREAD

**Issue by xor-zz** [ncw/rclone#745]
When filing an issue, please include the following information if
possible as well as a description of the problem.  Make sure you are
using the [latest version of rclone](http://rclone.org/downloads/).

Using the download for FreeBSD or NetBSD, for example:

http://downloads.rclone.org/rclone-current-freebsd-amd64.zip

or 

http://downloads.rclone.org/rclone-v1.33-freebsd-amd64.zip

Actually provides rclone 1.26.

> What is your rclone version (eg output from `rclone -V`)
rclone v1.26
> Which OS you are using and how many bits (eg Windows 7, 64 bit)
FreeNAS 64 Bit (FreeBSD)

**Comment by ncw** [comment]
I just checked - those both are v1.33 - did you get an old cached version maybe?

**Comment by xor-zz** [comment]
The zip is named 1.33 but the executable is actually 1.26 - downloaded
direct from the links available on rclone.org last night around 9pm
Pacific.

I can try again a bit later today.

**Comment by xor-zz** [comment]
Just checked again.  The package is named 1.33 but the binary you get is 1.26.  This can also be confirmed by the lack of support for Crypt in the binary.

To repro:

wget http://downloads.rclone.org/rclone-v1.33-freebsd-amd64.zip
unzip rclone-v1.33-freebsd-amd64.zip
cd rclone-v1.33-freebsd-amd64
rclone -V

Expected output:
rclone v1.33

Actual Output:
[root@freenas ~/Test/rclone-v1.33-freebsd-amd64]# rclone -V                     
rclone v1.26

**Comment by xor-zz** [comment]
Same behavior with the download on Github. With this download:

https://github.com/ncw/rclone/releases/download/v1.33/rclone-v1.33-freebsd-amd64.zip

I also tested the NetBSD and OpenBSD builds for both x86 and amd64.  All all 1.26.  I don't have a machine to test the ARM builds.

Also tested the Windows build which is properly 1.33.

**Comment by xor-zz** [comment]
As of this evening it appears to have resolved itself, just rechecked the github link I posted above. Not sure if a change was made or just some weird CDN caching behavior.

**Comment by xor-zz** [comment]
pebkac.  It was a path definition issue.  The binaries were correct all along.  Sorry!
