### ISSUE TITLE
x509: certificate is valid for {domain}, not {domain} during cloud-cloud transfers

### ISSUE THREAD

**Issue by jedinborough** [ncw/rclone#749]
Is there a flag or setting that I should use when copying from one cloud provider to another? I'm getting a certificate error when copying from onedrive to amazon cloud drive.

What is your rclone version (eg output from `rclone -V`)
rclone v1.29

Which OS you are using and how many bits (eg Windows 7, 64 bit)
Linux 64 bit

Which cloud storage system are you using? (eg Google Drive)
OneDrive, Amazon Cloud Drive

The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
`rclone copy 1drv_remote:dir acd_remote:dir`

A log from the command with the `-v` flag (eg output from `rclone -v copy /tmp remote:tmp`)
`x509: certificate is valid for {domain}, not public-dm2pap001.files.1drv.com`

**Comment by ncw** [comment]
I don't think this is anything particularly to do with copying from one cloud store to another.

It looks like this is a problem with onedrive.

Does it work if you include `--no-check-certificate` ?

I suspect it is a mis-configuration by the onedrive team which they will fix quickly - so does it still do it?

**Comment by ncw** [comment]
Is this working now?

**Comment by ncw** [comment]
I'm going to assume this is fixed now - if not please re-open!
