### ISSUE TITLE
"Corrupted on transfer: md5sums differ" error when syncing from Dropbox

### ISSUE THREAD

**Issue by darren12345** [ncw/rclone#75]
Hi. 

The issue appears to be similar to this one https://github.com/ncw/rclone/issues/56 but for Dropbox.

If I sync a folder from my server to Dropbox with rclone it works fine. However, if I then edit a file in that folder on my desktop and let it sync back with the Dropbox client, syncing that folder back from Dropbox to my server with rclone results in the following error:

darren@serverb3:~$ rclone sync dropbox:test/ /home/darren/test/ 
2015/06/04 18:22:01 Local file system at /home/darren/test: Building file list
2015/06/04 18:22:01 Local file system at /home/darren/test: Waiting for checks to finish
2015/06/04 18:22:01 Local file system at /home/darren/test: Waiting for transfers to finish
2015/06/04 18:22:02 article.txt: Corrupted on transfer: md5sums differ "6d260cdf0d8daccde07c1e784e272a96" vs "c7d5a97500b067da2297babf56950a01"
2015/06/04 18:22:02 Local file system at /home/darren/test: Not deleting files as there were IO errors

Transferred:         3509 Bytes (   1.43 kByte/s)
Errors:                 1
Checks:                 0
Transferred:            1
Elapsed time:  2.395469184s

System info:
darren@serverb3:~$ rclone -V
rclone v1.14
darren@serverb3:~$ uname -a
Linux serverb3 2.6.39.4-11 #1 Tue Apr 3 21:45:12 FET 2012 armv5tel GNU/Linux

**Comment by ncw** [comment]
I will look into this at the weekend - thanks for the report!

**Comment by ncw** [comment]
Ok I've had a chance to think about this now.

Unfortunately dropbox doesn't store MD5SUMs of objects - rclone has to upload them into an ancillary database which dropbox call a datastore.  This means that this is happening

  * you upload file with rclone - db is correct
  * desktop client uploads a change to the file - db is now out of date
  * you download the file with rclone - db is out of date - rclone complains about corrupt MD5SUMs

So I think this is expected behaviour (if not very helpful).

Possible solutions
  * A work-around would be to make sure rclone syncs to a different directory to the desktop client.
  * Alternatively I could add a flag to rclone to tell it to ignore the MD5SUMs and download stuff anyway.
  * Or radically stop storing MD5SUMs and mtimes in the datastore.  I might have to do this anyway as dropbox are dropping support for datastores.

At minimum I need to add stuff to the dropbox docs explaining the situation!

Any further ideas?

Thanks

Nick

**Comment by darren12345** [comment]
I noticed there were no hashes stored on the Dropbox side for files that didn't come from rclone. 

I don't suppose there's a way of forcing rclone to generate a hash on a file that is stored in Dropbox without downloading it first?

But yes, the deprecation of the datastore API is an embuggerance and it seems almost not worth fixing this problem because of it anyway. Much better to put some effort into coming up with an alternative solution. 

I suppose you could store hashes and other metadata in a related file (possibly using dotted file names so at least they'd be hidden in *nix, if not Windows). But this wouldn't solve the original problem I've reported.

I suppose ideally you'd want a switch that will tell rclone to either ignore hashes, mtimes or both when syncing.

**Comment by ncw** [comment]
> I don't suppose there's a way of forcing rclone to generate a hash on a file that is stored in Dropbox without downloading it first?

Alas, no.

> I suppose ideally you'd want a switch that will tell rclone to either ignore hashes, mtimes or both when syncing.

Rclone recently gained a `--checksum` flag which only uses the checksums not the md5sums,  this speeds up transfers between two remotes (eg s3 and swift).

I'll implement a `--size-only` flag which just checks the size when syncing.

**Comment by ncw** [comment]
I've updated the dropbox docs and implemented the `--size-only` flag in v1.15 which should work around your problems.

Thanks for the report and please re-open the ticket if you find a problem with the fix.

**Comment by darren12345** [comment]
Thanks Nick. I'll give it a try.

**Comment by darren12345** [comment]
Hi Nick. Sorry for my idicocy but is the syntax meant to be --size-only, --size-only=false or --size-only=true? I've tried all three and still get the md5sum conflicts. However, I'm also having the same thing with the --checksum option so I must be formatting the command wrong. Thanks.

**Comment by ncw** [comment]
`rclone --size-only` is what I would write, but `--size-only=true` is a valid alternative.

I can confirm that `--size-only` doesn't fix your problem - I made an exact reproducer in my dropbox account - something I should have done first :-(

re-opening the ticket for a better fix!

**Comment by ncw** [comment]
I'm just about to upload a new version to fix that - please re-open the ticket if there are still problems!  

Thanks

Nick

**Comment by darren12345** [comment]
Thanks for your continued support. Small thing - I'm trying to get the 1.16 using "go get" but it's downloading 1.15 still. Is there a switch that needs to be flicked somewhere?

**Comment by ncw** [comment]
Try go get -u -v -f ./... in the rclone directory to update rclone and its dependencies

**Comment by darren12345** [comment]
It works! Thanks.
