### ISSUE TITLE
No connexion with Amazon Drive

### ISSUE THREAD

**Issue by Setsuneh** [ncw/rclone#752]
Hi,

Enabled to connect on http://127.0.0.1:53682/auth  => No connexion
No iptables, and no ufw on my machine.

> What is your rclone version (eg output from `rclone -V`)
> root@ns371840:~# rclone -V
> 2016/09/30 21:42:12 Failed to load config file "/root/.rclone.conf" - using defaults: open /root/.rclone.conf: no such file or directory rclone v1.33
> 
> Which OS you are using and how many bits (eg Windows 7, 64 bit)
> Proxmox 4.X 
> 
> Which cloud storage system are you using? (eg Google Drive)
> Amazon Drive
> 
> A log from the command with the `-v` flag (eg output from `rclone -v copy /tmp remote:tmp`)
> root@ns371840:~# rclone -v copy /tmp remote:tmp
> 2016/09/30 21:43:02 Failed to load config file "/root/.rclone.conf" - using defaults: open /root/.rclone.conf: no such file or directory
> 2016/09/30 21:43:02 rclone: Version "v1.33" starting with parameters ["rclone" "-v" "copy" "/tmp" "remote:tmp"]
> 2016/09/30 21:43:02 Failed to create file system for "remote:tmp": didn't find section in config file

Thanks :)

**Comment by ncw** [comment]
Is your web browser running on the Proxmox machine? If not then follow the instructions here: http://rclone.org/remote_setup/
