### ISSUE TITLE
Amazon cloud unable to authorize

### ISSUE THREAD

**Issue by scriptzteam** [ncw/rclone#756]
```
   When you click "Okay", we'll provide rclone:
     * Ability to modify your Cloud Drive content.
     * Ability to read your Cloud Drive content.

   By clicking "Okay", you also accept: Cloud Drive Terms of Use
   (BUTTON) Cancel (BUTTON) Okay
```

when i am on lynx i push enter on (BUTTON) Okay and all i got was" Alert!: Unable to access document."??

**Comment by ncw** [comment]
If you are using lynx you are probably trying to authorize remotely.

Read here for a better way of doing it: http://rclone.org/remote_setup/

**Comment by scriptzteam** [comment]
Done, but now after adding 50 checkers and 50 transfers after a little while i got this whoa xD

`created by github.com/ncw/rclone/fs.NewAccount
        /home/ncw/Code/Go/src/github.com/ncw/rclone/fs/accounting.go:274 +0x1a7

goroutine 6327 [chan receive]:
net/http.(*Transport).dialConn(0xc94f41e0, 0x8915420, 0xc933c110, 0x0, 0xca20d040, 0x5, 0xc96c9830, 0x22, 0x0, 0x0, ...)
        /usr/local/go/src/net/http/transport.go:1034 +0x8d3
net/http.(*Transport).getConn.func4(0xc94f41e0, 0x8915420, 0xc933c110, 0xcb0bcfa0, 0xce90b300)
        /usr/local/go/src/net/http/transport.go:880 +0x48
created by net/http.(*Transport).getConn
        /usr/local/go/src/net/http/transport.go:882 +0x3a0

goroutine 6281 [runnable]:
net.runtime_pollWait(0xb8f53920, 0x72, 0xca3b1c00)
        /usr/local/go/src/runtime/netpoll.go:160 +0x55
net.(*pollDesc).wait(0xce90bfb8, 0x72, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:73 +0x35
net.(*pollDesc).waitRead(0xce90bfb8, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:78 +0x33
net.(*netFD).Read(0xce90bf80, 0xca3b1c00, 0x400, 0x400, 0x0, 0x89128e0, 0xc933c0a8)
        /usr/local/go/src/net/fd_unix.go:243 +0x1c2
net.(*conn).Read(0xcb0d2b30, 0xca3b1c00, 0x400, 0x400, 0x893d980, 0x0, 0x0)
        /usr/local/go/src/net/net.go:173 +0xa9
github.com/mreiferson/go-httpclient.(*rwTimeoutConn).Read(0xdb06ae60, 0xca3b1c00, 0x400, 0x400, 0x20, 0x0, 0x0)
        /home/ncw/Code/Go/src/github.com/mreiferson/go-httpclient/httpclient.go:228 +0x1bb
crypto/tls.(*block).readFromUntil(0xc9dfb9a0, 0xb9096b80, 0xdb06ae60, 0x5, 0x0, 0x0)
        /usr/local/go/src/crypto/tls/conn.go:472 +0xa4
crypto/tls.(*Conn).readRecord(0xcad92600, 0xcae66c16, 0x0, 0x0)
        /usr/local/go/src/crypto/tls/conn.go:574 +0x22a
crypto/tls.(*Conn).readHandshake(0xcad92600, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/crypto/tls/conn.go:925 +0xb9
crypto/tls.(*Conn).clientHandshake(0xcad92600, 0x0, 0x0)
        /usr/local/go/src/crypto/tls/handshake_client.go:159 +0xd29
crypto/tls.(*Conn).Handshake(0xcad92600, 0x0, 0x0)
        /usr/local/go/src/crypto/tls/conn.go:1232 +0x183
net/http.(*Transport).dialConn.func3(0xcad92600, 0x0, 0xcfa6cf80)
        /usr/local/go/src/net/http/transport.go:1028 +0x21
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:1033 +0x8a1

goroutine 6333 [select]:
net/http.(*persistConn).writeLoop(0xce998990)
        /usr/local/go/src/net/http/transport.go:1641 +0x2ba
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:1058 +0xdc5`

**Comment by ncw** [comment]
Unfortunately that is missing the top of the error message which contains the really important bit :-(

You can use `--log-file` to capture the errors or redirect the output.

Can you repeat the problem and get the start of the problem - preferably with the `-v` flag?

It might be worth trying the latest Beta too: http://pub.rclone.org/v1.33-24-gbfe6f29%CE%B2/

**Comment by scriptzteam** [comment]
I just little hacked it and got lynx url pasted on my PC CHROME BROWSER and verified :)

**Comment by scriptzteam** [comment]
And the error comes from "fatal error: heapBitsForSpan: base out of range" i think so as its the first line of error

**Comment by ncw** [comment]
> And the error comes from "fatal error: heapBitsForSpan: base out of range" i think so as its the first line of error

That is a serious internal error from the go runtime!

Can you reproduce that with the latest beta?

**Comment by ncw** [comment]
I'm going to close this as the main issue is fixed.  If you can reproduce the "fatal error: heapBitsForSpan: base out of range" please open another ticket.

Thanks

**Comment by ncw** [comment]
Just in case anyone is interested the heapBitsForSpan error has been fixed in go1.8.3: https://github.com/golang/go/issues/20259
