### ISSUE TITLE
Is there a way for deleting of source after upload complete on acd?

### ISSUE THREAD

**Issue by scriptzteam** [ncw/rclone#757]
Is there a way for deleting of source after upload complete on acd?

Thx!

**Comment by helioshosting** [comment]
Use move --delete-after

**Comment by scriptzteam** [comment]
thx, i read in docs this "Specifying --delete-after will delay deletion of files until all new/updated files have been successfully transfered.", means it delete souce or destination? since i need to remove source

**Comment by RXWatcher1** [comment]
the 'move' option is what you want. It will copy to acd and remove source afterwards. It will leave the source folders however but those can be cleaned up with a simple statement to remove empty folders.

There is a bug in move but it's fixed in this beta: https://github.com/ncw/rclone/issues/751
