### ISSUE TITLE
suggestion: a better way to rotate logs

### ISSUE THREAD

**Issue by marrie** [ncw/rclone#760]
Hello. Using the latest rclone on mac os sierra 64 bit my log output is quite large. Is there a command that will split logs by day, or even by the hour? This would make it easier for me to manage looking at logs should something go wrong. I won't paste in log stuff here as it is quite big, but this is just a suggestion anyway.

**Comment by RXWatcher1** [comment]
I would recommend looking into LogRotate. It works well on linux:
http://www.getmacapps.info/install-logrotate-on-macos

**Comment by marrie** [comment]
I could do that, however for some reason I'm getting a command not found when running the thing, maybe it does not yet work with sierra. Is there a way to do this in rclone? At least, for now?

**Comment by ncw** [comment]
There isn't a way to do this directly with rclone at the moment

You could script it like this though...

    rclone copy/sync .....  2>&1 | split -l 1000 - rclone.log

Don't use `--log-file` in the above.

Which will split the output of rclone into files with 1000 lines in each.  Use `split --help` for more options.

**Comment by marrie** [comment]
Interesting I didn't see that in  the read me. I'll look again though, thanks for that. I hope someone else finds this useful as well in case they also cannot get logrotate to work.

**Comment by marrie** [comment]
Yep got it. I can then just remove the files later. Thanks for that. I forgot about the  \  and all of that. Brings back memmories of another back up system I used to use.

Anyway for now this will work, thanks again.

**Comment by ncw** [comment]
Glad you got it working :-)
