### ISSUE TITLE
rclone move overwrite

### ISSUE THREAD

**Issue by reinierkors** [ncw/rclone#761]
When moving files to ACD:

```
rclone move ~/Main acd:/Main
```

How can I make it overwrite files that are different? In the current doc it says: 

> Rclone will error if the source and destination overlap.

I want it to overwrite files if they already exist and if they are different.

**Comment by ncw** [comment]
The source and the destination don't overlap in your example, one is on the local disk, the other is on acd so it should work fine.

If you did

    rclone move acd:Main acd:/Main/Sub

Then they would overlap

**Comment by reinierkors** [comment]
I see, so when using move it will overwrite?

**Comment by ncw** [comment]
It will use the same logic as sync or copy - by default it will overwrite if it is different, otherwise it will just delete the source.

**Comment by ncw** [comment]
I think you should find this is fixed in the latest beta: http://beta.rclone.org/v1.35-19-g499766f/

**Comment by georgeAustralia** [comment]
I issued the command for Amazon cloud drive:

rclone move remote:images/acbd remote:images

I got this error message:

amazon drive root 'images': can't move files on overlapping remotes
 Failed to move: can't move files on overlapping remotes

I then checked images/abcd folder.  The files are still there, not erased.
