### ISSUE TITLE
 rclone doesnt honor the --no-check-certificate flags in 1.33

### ISSUE THREAD

**Issue by outbackdingo** [ncw/rclone#763]
seems rclone doesnt honor the --no-check-certificate flags in 1.33
using Fedora

rclone --no-check-certificate mkdir s3:backup
2016/10/05 00:01:00 Attempt 1/3 failed with 1 errors and: BadRequest: Bad Request
        status code: 400, request id: libres3_17107f5560deb908aadce262de4df380_25784_4_1475593260.88
2016/10/05 00:01:00 Attempt 2/3 failed with 1 errors and: BadRequest: Bad Request
        status code: 400, request id: libres3_17107f5560deb908aadce262de4df380_25784_5_1475593260.88
2016/10/05 00:01:00 Attempt 3/3 failed with 1 errors and: BadRequest: Bad Request
        status code: 400, request id: libres3_17107f5560deb908aadce262de4df380_25784_6_1475593260.88
2016/10/05 00:01:00 Failed to mkdir: BadRequest: Bad Request
        status code: 400, request id: libres3_17107f5560deb908aadce262de4df380_25784_6_1475593260.88
[root@localhost ~]# rclone mkdir s3:backup
2016/10/05 00:02:47 
Transferred:      0 Bytes (0 Bytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:        1m0s

2016/10/05 00:03:16 Attempt 1/3 failed with 1 errors and: RequestError: send request failed
caused by: Head https://s3.optimcloud.com:443/backup: dial tcp: lookup s3.optimcloud.com on [fe80::7aa3:51ff:fe10:3ffe%enp2s0f1]:53: dial udp [fe80::7aa3:51ff:fe10:3ffe%enp2s0f1]:53: i/o timeout
2016/10/05 00:03:47 
Transferred:      0 Bytes (0 Bytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:        2m0s

2016/10/05 00:04:17 Attempt 2/3 failed with 1 errors and: RequestError: send request failed
caused by: Head https://s3.optimcloud.com:443/backup: x509: certificate signed by unknown authority
2016/10/05 00:04:47 
Transferred:      0 Bytes (0 Bytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:        3m0s

2016/10/05 00:05:34 Attempt 3/3 failed with 1 errors and: RequestError: send request failed
caused by: Head https://s3.optimcloud.com:443/backup: x509: certificate signed by unknown authority
2016/10/05 00:05:34 Failed to mkdir: RequestError: send request failed
caused by: Head https://s3.optimcloud.com:443/backup: x509: certificate signed by unknown authority

**Comment by ncw** [comment]
It is possible this got fixed as part of 0cb9bb3b54397ff2dd7a563194d1ec98ca9cedaa - so can you give a recent beta a try, eg http://pub.rclone.org/v1.33-31-g9ea20ba%CE%B2/

**Comment by outbackdingo** [comment]
Nope seems its not... 
rclone -V
rclone v1.33-31-g9ea20baβ

rclone --no-check-certificate lsl s3:
2016/10/05 00:16:42 InvalidURI: Failed to parse the specified URI.
        status code: 400, request id: libres3_17107f5560deb908aadce262de4df380_25784_15_1475594202.16
[root@localhost ~]# rclone --no-check-certificate lsl s3:
2016/10/05 00:38:25 InvalidURI: Failed to parse the specified URI.
        status code: 400, request id: libres3_17107f5560deb908aadce262de4df380_25784_16_1475595505.34
[root@localhost ~]# rclone --no-check-certificate mkdir s3:backup
2016/10/05 00:38:37 Attempt 1/3 failed with 1 errors and: BadRequest: Bad Request
        status code: 400, request id: libres3_17107f5560deb908aadce262de4df380_25784_17_1475595517.5
2016/10/05 00:38:37 Attempt 2/3 failed with 1 errors and: BadRequest: Bad Request
        status code: 400, request id: libres3_17107f5560deb908aadce262de4df380_25784_18_1475595517.5
2016/10/05 00:38:37 Attempt 3/3 failed with 1 errors and: BadRequest: Bad Request
        status code: 400, request id: libres3_17107f5560deb908aadce262de4df380_25784_19_1475595517.5
2016/10/05 00:38:37 Failed to mkdir: BadRequest: Bad Request
        status code: 400, request id: libres3_17107f5560deb908aadce262de4df380_25784_19_1475595517.5

**Comment by ncw** [comment]
None of the above errors say `x509: certificate signed by unknown authority` which is what the `--no-check-certificate` prevents.

What are you trying to connect to?  Have you tried using `-v` and `--dump-bodies` to debug what is going on?

**Comment by ncw** [comment]
Did you figure this out?

**Comment by outbackdingo** [comment]
no, gave up on rclone and went to find another app  that works

**Comment by ncw** [comment]
Ok!
