### ISSUE TITLE
Empty folders

### ISSUE THREAD

**Issue by psmanek** [ncw/rclone#764]
Hello,

v1.33 leaves empty folders. Simple test. Make sync. Change folder name in source. In destination new folder have all files as it should, but old folder still exists. Files are gone, but folders are still there.

Thanks

**Comment by ncw** [comment]
This is a known problem. See issue #100

**Comment by scriptzteam** [comment]
what about we will have something in rclone like this:

`rclone move ...` will got option `rclone move --delete ...` possible?

**Comment by ncw** [comment]
@scriptzteam I'm not sure I understand what you mean - move will delete the files but won't delete the empty directories until #100 is fixed.

**Comment by scriptzteam** [comment]
yes i mean the prefix `--delete` will be used as to remove empty dirs or `--delete-empty`
