### ISSUE TITLE
Detect renaming folders or files

### ISSUE THREAD

**Issue by psmanek** [ncw/rclone#765]
Hi,

is there any way to check if folders was only renamed? It would be very useful for large folders. Clone would only rename folder, instead of uploading it again.

thanks

**Comment by ncw** [comment]
What you are talking about is detecting renames.  For remotes which support a hash it would possible.

**Comment by eharris** [comment]
Although this ticket was opened earlier, is it a duplicate of #888?

**Comment by ncw** [comment]
This has now been implemented with the --track-renames flag
