### ISSUE TITLE
Rclone mount not refreshing directory

### ISSUE THREAD

**Issue by reticentnz** [ncw/rclone#767]
When doing a 'ls' in a mounted rclone directory following a 'rclone move' none of the new files are shown. I cannot ascertain through the documentation what the expected behaviour is - are users supposed to umount and then remount the directory in order to see the new files or is this refresh mechanism supposed to happen automatically?

I'm on Debian 8, running 1.33, and are using amazon cloud drive with encryption.

The uploads are indeed working as their encrypted counterparts can be seen in the web gui (and also after a remount)

**Comment by reticentnz** [comment]
I have created a bash script to unmount / mount this every evening after the rclone upload. It's not ideal but seems to work OK. I'd be interested to know whether this function is likely to built in at some point.

**Comment by ncw** [comment]
I think this is the same issue as #680 which I'm planning to fix for the next release.

**Comment by reticentnz** [comment]
@ncw Thanks - They do look like the same. I'll close this one.

**Comment by scriptzteam** [comment]
Hope for the fix going live soon :)
