### ISSUE TITLE
OS X Fuse Issue

### ISSUE THREAD

**Issue by spencercharest** [ncw/rclone#768]
When filing an issue, please include the following information if
possible as well as a description of the problem.  Make sure you test
with the [latest beta of rclone](http://rclone.org/downloads/).

> What is your rclone version (eg output from `rclone -V`)

rclone v1.33-41-g4847c56β

> Which OS you are using and how many bits (eg Windows 7, 64 bit)

macOS Sierra 64 Bit

> Which cloud storage system are you using? (eg Google Drive)

Google Drive (encrypted)
Amazon Cloud Drive (encrypted)

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

rclone mount remote:folder ~/mount 

> A log from the command with the `-v` flag (eg output from `rclone -v copy /tmp remote:tmp`)

2016/10/05 11:49:34 Encrypted amazon drive root 'rvt9adj21phi9s74vcdshrkq3o': Modify window not supported
2016/10/05 11:49:34 Encrypted amazon drive root 'rvt9adj21phi9s74vcdshrkq3o': Root()
2016/10/05 11:49:34 : Dir.Attr
2016/10/05 11:49:34 : Dir.Attr

When mounting with rclone I receive the following error every time I try to access a file in the remote path.

ReadFileHandle.Flush error: Attempt to use closed file handle

**Comment by ncw** [comment]
I've just committed a fix for #638 to master which may fix this: 

http://beta.rclone.org/v1.33-49-gde80a54/ 

Note that I don't have a mac so haven't tested very much of the fuse code on OS X.  I'd be interested if you might want to contribute anything to the docs on how to set it up on OS X.

**Comment by spencercharest** [comment]
That did fix the issue but it really slowed down my connection to the remote. On the stable release 1.33 rsync from the mounted remote to my local machine runs at about 33 MB/s while the new beta was running at less than 300 Kb/s.

I would be happy to contribute an installation guide for OS X for the docs. I'm very new to coding and this would be my first time contributing something like that but I think I could do a good job. Is it pretty standard to just write a step by step in MD?

**Comment by ncw** [comment]
Wow,  that is a lot slower! 

I wonder why? 

Can you try a plain cp rather than an rsync and compare the versions? 

A step by step in markdown would be perfect. I can wedge that in the docs or you can send me a pull request whichever you prefer.

**Comment by spencercharest** [comment]
Copy is about the same on the beta and stable release. Each is at about 10MB/s. I am trying to stream video through the FUSE mount which is what is going really slow. 

I should be able to do a write up tomorrow. I really appreciate your help. This is a really fantastic tool and I can see through messaged and commits that you are very responsive to users and work really hard on it. Just wanted to say thanks! Do you accept donations anywhere since the tool is free?

**Comment by ncw** [comment]
Thanks for that and it is what I expected.  Note that seeking is really slow for `rclone mount` - and I suspect rsync does quite a bit of seeking.

In http://beta.rclone.org/v1.33-51-gf45b3c8/ I added a `--no-seek` flag - can you see what difference that makes?

See [the donations page](http://rclone.org/donate/) for the other thing!

**Comment by spencercharest** [comment]
[macOS.MD.zip](https://github.com/ncw/rclone/files/514165/macOS.MD.zip)

Here is the MD I wrote up. Pretty simple and pretty similar to the linux example. I wasn't sure if you wanted to frame it as an 'example' since obviously the version numbers will change. If you were looking more for an example of how to do it through GUI I can do that as well. I just figured if someone was using rclone they would be at least be a bit comfortable with the command line.

I am getting a 'file not found' for the new beta that you linked.

**Comment by ncw** [comment]
Thank you very much for the docs - they look great.  I've edited them a bit to take the current version numbers out: See http://rclone.org/install/ - does that still work OK?

If you could do a paragraph on how to install FUSE for macOS as well that would be very useful :-)  Maybe there is a doc I could link to?

I messed up the build - here is the new beta: http://beta.rclone.org/v1.33-52-gaedad89/

**Comment by spencercharest** [comment]
On this newest beta both --no-seek and no flags are both very slow. Less than 200 Kb/s.

**Comment by ncw** [comment]
@spencercharest 
> On this newest beta both --no-seek and no flags are both very slow. Less than 200 Kb/s.

:-( I'll try to find out what is going on...

**Comment by spencercharest** [comment]
No rush. I understand Mac is not a priority. Worst case I can just use rclone inside an linux VM.

I am not sure how to install FUSE outside of the GUI so I just added a link to the downloads page and said to download and follow prompts to install.

[macOS.MD.zip](https://github.com/ncw/rclone/files/514358/macOS.MD.zip)

**Comment by derdon89** [comment]
Is there a solution or workaround available?
I have the very same problem.
No problem uploading files but mounted with fuse i will only get between 200 - 300 kb/s 
Using the latest Beta of rclone on Mac OS 10.12

**Comment by derdon89** [comment]
To add: Same Computer on Linux 16.04 LTS on a VM is working.

**Comment by ncw** [comment]
Is this still a problem with rclone 1.35?

**Comment by spencercharest** [comment]
@ncw no issues on 1.35. It is working amazingly!

**Comment by ncw** [comment]
@spencercharest excellent news!  I'll close this isse then!
