### ISSUE TITLE
rclone iterates through a large bucket to operate on a single object

### ISSUE THREAD

**Issue by DanielDent** [ncw/rclone#769]
I have a swift bucket at Hubic with many thousands of objects in it, without any folder hierarchy. Copying a single object from this bucket is quite slow. It looks like rclone first iterates through the entirety of a 'folder' before performing an operation on a single object.

> What is your rclone version (eg output from `rclone -V`)
rclone v1.33
> Which OS you are using and how many bits (eg Windows 7, 64 bit)
Debian Linux 64 bit
> Which cloud storage system are you using? (eg Google Drive)
Hubic
> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone copy -v hubic:GA/afile .
> A log from the command with the `-v` flag (eg output from `rclone -v copy /tmp remote:tmp`)
rclone copy -v hubic:GA/afile .
2016/10/05 16:24:19 rclone: Version "v1.33" starting with parameters ["rclone" "copy" "-v" "hubic:GA/afile" "."]
2016/10/05 16:24:20 Hubic: Got swift credentials (expiry 2016-10-07 00:52:33 +0200 +0200 in 23h28m12.913624349s)
2016/10/05 16:24:21 Local file system at /tmp/asd/9: Modify window is 1ns
2016/10/05 16:24:21 existingfile1: Excluded from sync (and deletion)
2016/10/05 16:24:21 existingfile2: Excluded from sync (and deletion)
2016/10/05 16:24:21 existingfile3: Excluded from sync (and deletion)
... and so-on ...

Deleting a single object is also quite slow:

rclone -v delete hubic:GA/thisisfile
2016/10/05 16:19:21 rclone: Version "v1.33" starting with parameters ["rclone" "-v" "delete" "hubic:GA/thisisfile"]
2016/10/05 16:19:22 Hubic: Got swift credentials (expiry 2016-10-07 00:52:33 +0200 +0200 in 23h33m10.930861748s)
2016/10/05 16:19:22 Hubic Swift container GA: Modify window is 1ns
2016/10/05 16:19:22 Waiting for deletions to finish
2016/10/05 16:20:22 
Transferred:      0 Bytes (0 Bytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:        1m1s

2016/10/05 16:21:22 
Transferred:      0 Bytes (0 Bytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:        2m1s

2016/10/05 16:22:22 
Transferred:      0 Bytes (0 Bytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:        3m1s

2016/10/05 16:23:22 
Transferred:      0 Bytes (0 Bytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:        4m1s

2016/10/05 16:24:22 
Transferred:      0 Bytes (0 Bytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:        5m1s

2016/10/05 16:25:22 
Transferred:      0 Bytes (0 Bytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:        6m1s

2016/10/05 16:26:22 
Transferred:      0 Bytes (0 Bytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:        7m1s

2016/10/05 16:27:14 thisisfile: Deleted
2016/10/05 16:27:14 
Transferred:      0 Bytes (0 Bytes/s)
Errors:                 0
Checks:                 1
Transferred:            0
Elapsed time:     7m52.6s
2016/10/05 16:27:14 Go routines at exit 2

**Comment by ncw** [comment]
I think this is the same issue as #610 which I'm planning to fix for the next release.

**Comment by DanielDent** [comment]
Yes it does, sorry for the dupe, I did not notice that issue.

**Comment by ncw** [comment]
I've fixed this in http://beta.rclone.org/v1.33-55-g98804cb/ (it will take 15 mins to appear).  Have a go and re-open the ticket if there is a problem.

Thanks

Nick
