### ISSUE TITLE
Dropbox: Problem syncing some folders - probably due to case insensitivity.

### ISSUE THREAD

**Issue by darren12345** [ncw/rclone#77]
Hi Nick,

I'm having a problem with syncing some (but not all) folders. I'm sure it's down to the case (in)sensitivity of Dropbox but I can't understand why it's only happening with some folders. This is the command I'm running:

rclone sync -v --size-only dropbox:Documents/ local:/home/darren/test/

Some files (particularly in the Finance folder) are causing the following error and not syncing:

2015/06/11 11:07:11 /documents/finance/2010/Vacuum Belts.pdf: Failed to open: file does not exist

In Dropbox, the path is actually /Documents/Finance/ - note the upper case D and F - but like I said, I don't know why it seems to only be affecting the Finance folder. Other sub-folders of Documents (also containing an upper-case first letter) are syncing OK.

**Comment by ncw** [comment]
This is the same issue as #53 I think.  We are currently working  on a fix #65 , but it is proving trickier than we first thought!

I put a note about this in the [dropbox docs](http://rclone.org/dropbox/) recently.

**Comment by darren12345** [comment]
Yes, appears to be the same issue. I had a quick look at that one
and didn't think it was the same problem, but a more thorough
read-through confirms it is. Thanks. 

On 11/06/2015 11:29, Nick
Craig-Wood wrote: 

> This is the same issue as #53 [1] I think. We are
currently working on a fix #65 [2] , but it is proving trickier than we
first thought! 
> 
> I put a note about this in the dropbox docs [3]
recently. 
> 
> --
> Reply to this email directly or view it on GitHub
[4].
 

Links:
------
[1] https://github.com/ncw/rclone/issues/53
[2]
https://github.com/ncw/rclone/pull/65
[3] http://rclone.org/dropbox/
[4]
https://github.com/ncw/rclone/issues/77#issuecomment-111080089

**Comment by ncw** [comment]
This should be fixed by #65 - let me know if it isn't.

Thanks for the report

Nick

**Comment by darren12345** [comment]
Seems to work a treat. Thanks very much for your efforts. 

On
14/06/2015 15:49, Nick Craig-Wood wrote: 

> This should be fixed by #65
[1] - let me know if it isn't. 
> 
> Thanks for the report 
> 
> Nick 
>

> --
> Reply to this email directly or view it on GitHub [2].



Links:
------
[1] https://github.com/ncw/rclone/pull/65
[2]
https://github.com/ncw/rclone/issues/77#issuecomment-111837425
