### ISSUE TITLE
Inconsistencies accessing rclone mount from different services

### ISSUE THREAD

**Issue by reticentnz** [ncw/rclone#772]
Hi, I've noticed after mounting an amazon cloud drive with rclone mount that I can access files with the local system (i.e bash) but not other services. For example,  I cannot copy files via SCP, or nginx when using this same mount point.  I have attempted to SCP a file with root and this results in a generic (winSCP) error. Same with nginx.

I assume this is a permission issue as I notice the files don't have execute permissions (I'm not 100% sure if this is required in order to download files using the above method). Directory traversal works fine, I can browse through any of the trees, I just can't download files.

ls -alh
drwxr-xr-x 1 root root 0 Oct  6 16:12 Directory
cd Directory
ls -alh
-rw-r--r-- 1 root root  81M Oct  6 11:11 File

I have played around with various umasks to no avail. I also tried a read-only mount and this doesn't make any difference.

I do a 'cp File /tmp/' and this works fine suggesting  the permission on the local system is OK.

Any thoughts?

Cheers

> What is your rclone version (eg output from `rclone -V`)

rclone v1.33-41-g90aee8c-fix-timeoutÎ²

> Which OS you are using and how many bits (eg Windows 7, 64 bit)

Debian 8 64bit

> Which cloud storage system are you using? (eg Google Drive)

Amazon Cloud Drive

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

rclone mount Crypt: /home/acd/ --allow-other &

> A log from the command with the `-v` flag (eg output from `rclone -v copy /tmp remote:tmp`)

**Comment by ncw** [comment]
`--allow-other` is what you need so that users other than the user that did the mounting can read the files.  Not having that will give you the permissions denied errors when accessing files with root.

Maybe you need `--allow-root` too?

What do the permissions look like - do an `ls -l` of some files you are having a problem with and post them here...

**Comment by reticentnz** [comment]
@ncw Thanks for getting back to me. 

I'm already using --allow-root (and it doesn't look like fuse lets you use both together). In my original post I already have some of the outputs of 'ls -l'. It shows single files have this:

-rw-r--r-- 1 root root 81M Oct 6 11:11 hello.txt

Doesn't really look right to me? Even with a umask of 000 I don't seem to get execute permissions on the files.

**Comment by ncw** [comment]
You don't need the execute bit for files only directories. 

Have you tried adding user_allow_other to /etc/fuse.conf? You need that in order to make allow other and allow root work.

**Comment by reticentnz** [comment]
Yep, it's setup there already. The more I look at this the less I think it's a permission error. 

Nginx reports this in the error log:

2016/10/06 22:25:52 [crit] 13735#0: *13387 pread() "/var/www/media/hello.txt" failed (29: Illegal seek) while sending response to client

If it were a permission error I'd get a 403 (which I can replicate by changing the permissions on a file). I'd read something in another issue log saying that seeking isn't supported. Does the way nginx gets file require this? The same thing happens when using SCP though.

**Comment by ncw** [comment]
It would be worth re-testing with the latest beta: http://beta.rclone.org/v1.33-52-gaedad89/ which does definitely support seek.

**Comment by reticentnz** [comment]
Aha! Looks like that has fixed the issue.  Thanks so much for providing this fix. OK to mark this as resolved!

**Comment by ncw** [comment]
Excellent :-)
