### ISSUE TITLE
rclone fails to work under windows...

### ISSUE THREAD

**Issue by jonathanproteowizard** [ncw/rclone#773]
running in a "administrator" cmd window on win7-64:
rclone is 1.33

C:>dir
 Volume in drive C is OS
 Volume Serial Number is F603-C5EB

 Directory of C:\

18/09/2012  02:20    <DIR>          dell
28/08/2012  21:17    <DIR>          Drivers
06/12/2013  01:05    <DIR>          inetpub
28/08/2012  13:01    <DIR>          Intel
13/07/2009  20:20    <DIR>          PerfLogs
06/07/2016  10:14    <DIR>          PKI-SERVICE
05/10/2016  16:54    <DIR>          Program Files
28/07/2016  17:16    <DIR>          Program Files (x86)
18/12/2013  04:21    <DIR>          Users
21/09/2015  12:50    <DIR>          Windows
               0 File(s)              0 bytes
              10 Dir(s)  94,459,953,152 bytes free

C:>Users\Operetta\Desktop\rclone-v1.33-windows-amd64\rclone.exe sync Users Amazon:rclone/oprt
2016/10/06 11:08:33 amazon drive root 'rclone/oprt': Waiting for checks to finish
2016/10/06 11:08:33 amazon drive root 'rclone/oprt': Waiting for transfers to finish
2016/10/06 11:08:34 amazon drive root 'rclone/oprt': not deleting files as there were IO errors
2016/10/06 11:08:34 Attempt 1/3 failed with 0 errors and: failed to open directory "\\?\C:\Users\Default User": open \?\C:\Users\Default User: Access is denied.
2016/10/06 11:08:34 amazon drive root 'rclone/oprt': Waiting for checks to finish
2016/10/06 11:08:34 amazon drive root 'rclone/oprt': Waiting for transfers to finish
2016/10/06 11:08:40 amazon drive root 'rclone/oprt': not deleting files as there were IO errors
2016/10/06 11:08:40 Attempt 2/3 failed with 0 errors and: failed to open directory "\\?\C:\Users\Default User": open \?\C:\Users\Default User: Access is denied.
2016/10/06 11:08:40 amazon drive root 'rclone/oprt': Waiting for checks to finish
2016/10/06 11:08:40 amazon drive root 'rclone/oprt': Waiting for transfers to finish
2016/10/06 11:08:40 amazon drive root 'rclone/oprt': not deleting files as there were IO errors
2016/10/06 11:08:40 Attempt 3/3 failed with 0 errors and: failed to open directory "\\?\C:\Users\Default User": open \?\C:\Users\Default User: Access is denied.
2016/10/06 11:08:40 Failed to sync: failed to open directory "\\?\C:\Users\Default User": open \?\C:\Users\Default User: Access is denied.

C:>

**Comment by justusiv** [comment]
Is this related to this issue that was closed?
https://github.com/ncw/rclone/issues/692
"c:\Users\Default User" is a a junction point for
"c:\Users\Default"

rclone.exe sync "c:\Users\Default User" Amazon:rclone/testdefault
rclone.exe sync "c:\Users\Default" Amazon:rclone/testdefault

Do these do anything different?
Also do you really need to backup your default profile :P

**Comment by ncw** [comment]
@justusiv good thinking.  That was merged to master so will be in the latest beta: http://beta.rclone.org/v1.33-55-g98804cb/

(Not a windows expert so help much appreciated!)

**Comment by ncw** [comment]
I'm going to assume this is fixed now - please re-open if not.
