### ISSUE TITLE
FUSE: Better transfer speed with crypt while using seek

### ISSUE THREAD

**Issue by jkaberg** [ncw/rclone#774]
Per title. Currently seeing roughly 1MB/s (crypt+ACD), without crypt I can easily get 16MB/s (pure ACD).

People reported similar in the old seek issue https://github.com/ncw/rclone/issues/707

I totally buy that crypt is slower, no questions about that. It's just that I think/hope it could be a little bit faster then this :-)

**Comment by ncw** [comment]
Are those figures without using rclone mount? If not can you try using rclone directly without FUSE and report the timings?

**Comment by jkaberg** [comment]
This is with the mount option. Can you give me an example you'd like me to test?

**Comment by justusiv** [comment]
1.33-52
I wanna say first off my speeds stink, due to my provider. i am talking like 10Mbps. 
I did a test with the same file. First using mounted crypt. It would bounce between 1-5Mbps and when i tried to sync it showed an updated image but never started playing again. 
Next i test with a mounted none crypt. Maybe just a smidge faster 2-5Mbps this time i could seek and it would take about 5 or 6 seconds and start playing again.
the final test was using cat file | vlc- This time i was receiving about 7Mbps steady. When i attempted a seek it just broke. 

This was on ubuntu 16.04 and used the default media player accept when i cat to vlc. 
Just my observations. nothing formal here and my speeds stink always not just with rclone :)

**Comment by reticentnz** [comment]
I've been playing around with this and I have the same problems. If I rclone mount both the Encrypted and Decrypted remotes and download with nginx (which I believe uses seek) I get:

Encrypted: 6Mb/s
Decrypted: 300kb/s

This is not CPU related as the system is basically idle while these downloads are happening. I'm on 50mb/s internet at home so the 6Mb/s figure above is essentially line speed. The slow speeds on the decrypted files means using vlc/kodi is basically unusable for higher bit rate files and buffers indefinately.

Happy to do any tests you may require to investigate this.

**Comment by ncw** [comment]
Thanks for the tests.

I'm not sure what is going on here!

Observations suggest it is most likely it is something to do with the crypt code and seeking but I haven't figured it out yet!

It could also be something that has changed (eg the fuse library I'm using) - I'll try to narrow it down more.

**Comment by Trentflix** [comment]
I don't think it's actually Crypt I think it's seek:

Copy/pasting a file from my Encrypted ACD mount I get speeds of 17MB/s when I try to play the video file with the built in video player I get 150-600 KB/s.

**Comment by Trentflix** [comment]
One more test: I tried playing the same video file from my non-encrypted ACD mount and got 300-600KB/s. So Crypt didn't make much of a difference for me, just seeking.

**Comment by ncw** [comment]
Good results thanks. How are you measuring the speed while seeking? Maybe I need to write some benchmarks to formalise that.

**Comment by Trentflix** [comment]
I'm just watching Bmon for 60 seconds while performing these action..

**Comment by suneetk92** [comment]
Hi,
I'm also facing similar issue. 
I have set up rclone crypt + ACD for uploading data and rclone mount/FUSE to download.
While uploading data I get uploading speed of 10mbps [Max for my connection]
While copying/downloading data from mount point I get speed varying between 10mbps - 20mbps [Max down speed for my connection is 20mbps]
But while streaming a video from Plex using rclone FUSE mount point I get speed varying between 0.5mbps - 2mbps only. 

Note: Currently using rclone-v1.33-64 Beta version.

**Comment by ncw** [comment]
I have fixed this in : http://beta.rclone.org/v1.33-69-gd8d1102/ (will be uploaded in 15 mins)

There was a bug in the seek implementation which was causing it to seek on every read which really killed the performance.

I only figured out what was going on by playing videos from ACD with vlc - so thank you all for your tips.

**Comment by spencercharest** [comment]
YES! Thanks for your hard work @ncw! Very excited to implement this!

**Comment by suneetk92** [comment]
Thanks :) :)
Now I'm having a smooth playback from plex.

**Comment by reticentnz** [comment]
@ncw I've just installed this version and it doesn't seem to have made any difference for me :(

root@frog:~# rclone --version
rclone v1.33-69-gd8d1102β
