### ISSUE TITLE
Slow upload ACD

### ISSUE THREAD

**Issue by solidstudio** [ncw/rclone#775]
Hi i'm uploading some images to ACD and getting around 1.5 mb/s, when I run a speed test my upload is 12 mb/s any tips on how to improve my speed.

**Comment by ncw** [comment]
Speed tests will report in 12 MBit/s wheras rclone reports as 1.5 MByte/s which is approx 15 Mbit/s - so maybe you are actually doing OK?

You could also try the latest beta: http://beta.rclone.org/v1.33-52-gaedad89/ which has some ACD fixes.

**Comment by solidstudio** [comment]
my bad thanks for highlighting

**Comment by ncw** [comment]
No worries!
