### ISSUE TITLE
rclone move question

### ISSUE THREAD

**Issue by scriptzteam** [ncw/rclone#776]
probably i am wrong or dont understand how all works or i am just dumb xD

so i just did `rclone move` with `--ignore-existing --verbose --transfers=500 --checkers=1 --low-level-retries 1 --size-only --no-update-modtime --min-age 2d --checksum`, all goes well but in next rclone more command run i still see this in log : 

```
2016/10/07 18:15:19 PATH/file.ext: Excluded from sync (and deletion)
2016/10/07 18:15:19 PATH/file.ext: Excluded from sync (and deletion)
```

so the problem is the EMPTY dirs? since i have empty dirs on my source and it always checks or compare source and dir? can it just be dir skipped if its already on dest, i do not care size,time,checksum, just if exist folder skip it... does it also have cache? as i see it always checks the same dirs everytime i run the command, and i need to skip folders that exists

**Comment by ncw** [comment]
Sorry I missed this question...

The only thing which can be causing those errors is `--min-age 2d` - this means all files older than 2 days which maybe wasn't what you intended?

`PATH/file.ext` will be excluded because it is newer than 2 days old.
