### ISSUE TITLE
getting errors when starting back up of a folder

### ISSUE THREAD

**Issue by marrie** [ncw/rclone#777]
Rclone version 1.33
Mac os sierra 64 bit

[log file zipped](https://github.com/ncw/rclone/files/517453/outputmusic.log.zip)

When starting the script I have for the folder for the first time I get api errors as if the resource can't be found. Can this be due to the fact that I'm reaching my daily cap? I have that set at about 900 gig but I can't upload that much in a day. This is using b2 by the way. I know this is not much help but hopefully what I provided will work.

**Comment by ncw** [comment]
The error id

     dial tcp: lookup pod-000-1010-11.backblaze.com on 8.8.8.8:53: dial udp 8.8.8.8:53: i/o timeout

Which means that your dns couldn't be contacted or didn't know the answer. 

This can happen if your link is very busy - did the file transfers start? Or is there something else running using bandwidth?

**Comment by marrie** [comment]
No, there was nothing. I was at the time behind a proxi,  however my books script was running just fine.   I've gotten that error though even when I was not behind the proxi. And no transfers started, it just quit. I didn't get my prompt back though, and hhad to brake the script.

**Comment by ncw** [comment]
Does rclone ever get going or are the Dns errors transient?

**Comment by marrie** [comment]
Not for this folder. I'll keep playing with it to see if I can get it to start.  Maybe something at my isps side broke. Lol! I've seen that error before but usually it just fixes itself and starts so sync on its marry way.
