### ISSUE TITLE
Copy simultaneous to the same account

### ISSUE THREAD

**Issue by dbareiro** [ncw/rclone#78]
Hi, Nick.

I currently have a script running as cron job at a certain time to copy files using rclone to a Drive account. I was thinking about running the same script on another server at the same time to copy files to the same location on the same Drive account.

Do you think that to copy files from different sources to the same destination at the same time could cause some inconvenience?

Thanks in advance.

Best regards,
Daniel

**Comment by ncw** [comment]
As long as you are using `rclone copy` not `rclone sync` things will go fine.

I assume you aren't copying the same files, but if you are the latest uploaded should win.

I wouldn't expect rclone or google drive to get confused, but if it does make an issue!

**Comment by dbareiro** [comment]
Hi, Nick.

Thanks for your prompt reply.

> As long as you are using ```rclone copy``` not ```rclone sync``` things will go fine.

Yes, I'm using ```rclone copy```. I've modified the title of the issue to avoid confusion if someone has the same doubt.

By the way, I was not sure if the ```sync``` option was valid for use with Drive because I did not see it [documented](http://rclone.org/drive/) and in others storage systems like S3 I saw it documented.

To set up the same Google Drive account on other servers is necessary to obtain a different token from Google or would it be sufficient copying the ```[remote]``` block to each configuration file?

> I assume you aren't copying the same files, but if you are the latest uploaded should win.

Sure, I understand. No, in this case, the files on each host that I am copying have different names.

> I wouldn't expect rclone or google drive to get confused, but if it does make an issue!

Thank you for your comments. I will try it and if I get some unexpected behavior, I'll let you know.

Best regards,
Daniel

**Comment by ncw** [comment]
> By the way, I was not sure if the sync option was valid for use with Drive because I did not see it documented and in others storage systems like S3 I saw it documented.

`rclone sync` does work on drive!  Those are examples in the docs, rather than what each system can and can't do - maybe I should make that clearer.

> To set up the same Google Drive account on other servers is necessary to obtain a different token from Google or would it be sufficient copying the [remote] block to each configuration file?

You should be able to just copy the config - that is what I do, though I haven't tried it from two different locations simultaneously so it is conceivable drive might complain about that.

**Comment by dbareiro** [comment]
Hi, Nick.

> ```rclone sync``` does work on drive! Those are examples in the docs, rather than what each system can and can't do - maybe I should make that clearer.

If all options are valid on all storage systems, maybe to avoid doubts it be desirable put it in writing. Just a suggestion :-)

Talking about documentation, I think you have a broken link [here](http://rclone.org/install/). In the "Usage section" link. I think this should point to rclone.org/docs instead of rclone.org/usage.

>> To set up the same Google Drive account on other servers is necessary to obtain a different token from Google or would it be sufficient copying the [remote] block to each configuration file?

> You should be able to just copy the config - that is what I do, though I haven't tried it from two different locations simultaneously so it is conceivable drive might complain about that.

Yes, probably. Perhaps to avoid this I get a new token of Google.

Thanks for your reply.

Best regards,
Daniel

**Comment by dbareiro** [comment]
Hi Nick.

To give you an update on this topic I will say that I did a test using the following scenario: copying a file with the same name from two different sources to the same Drive account, starting the process at the same time (cron job).

Here is the result:

```
# rclone lsl remote:Backup | grep veterinary | sort -k4

Transferred:            0 Bytes (   0.00 kByte/s)
Errors:                 0
Checks:               135
Transferred:            0
Elapsed time:  984.15479ms

  3618055 2015-06-11 06:00:36.908000000 mysql/2015-06/mysqldump.veterinary.20150610_2300.sql.gz
  3618033 2015-06-12 06:00:47.067000000 mysql/2015-06/mysqldump.veterinary.20150611_2300.sql.gz
  3618034 2015-06-13 06:00:40.964000000 mysql/2015-06/mysqldump.veterinary.20150612_2300.sql.gz
  3618035 2015-06-14 06:01:01.901000000 mysql/2015-06/mysqldump.veterinary.20150613_2300.sql.gz
  3618035 2015-06-14 06:01:01.901000000 mysql/2015-06/mysqldump.veterinary.20150613_2300.sql.gz
  3618033 2015-06-15 06:00:47.435000000 mysql/2015-06/mysqldump.veterinary.20150614_2300.sql.gz
  3618033 2015-06-15 06:00:47.435000000 mysql/2015-06/mysqldump.veterinary.20150614_2300.sql.gz
  3618034 2015-06-16 06:00:59.027000000 mysql/2015-06/mysqldump.veterinary.20150615_2300.sql.gz
  3618034 2015-06-16 06:01:05.191000000 mysql/2015-06/mysqldump.veterinary.20150615_2300.sql.gz
 98311351 2015-06-11 07:01:36.793000000 ps382038.dreamhostps.com/2015-06/veterinary.berlin.to_20150610.tar.gz
 98311351 2015-06-12 07:01:21.344000000 ps382038.dreamhostps.com/2015-06/veterinary.berlin.to_20150611.tar.gz
 98311351 2015-06-13 07:01:22.784000000 ps382038.dreamhostps.com/2015-06/veterinary.berlin.to_20150612.tar.gz
 98311351 2015-06-14 11:37:41.606000000 ps382038.dreamhostps.com/2015-06/veterinary.berlin.to_20150613.tar.gz
 98592147 2015-06-15 07:11:39.572000000 ps382038.dreamhostps.com/2015-06/veterinary.berlin.to_20150614.tar.gz
 98431339 2015-06-16 07:10:47.294000000 ps382038.dreamhostps.com/2015-06/veterinary.berlin.to_20150615.tar.gz
```

As you can see, there are some files that were duplicates. What do you think may have been the cause?

The curious thing is that while all files of "veterinary" were copied from two different sources, only some are duplicated.

Thanks in advance.

Best regards,
Daniel

**Comment by dbareiro** [comment]
Hi, Nick.

A little more of information (reports of the execution of scripts on both servers):

server1:
```
######################## Synchronizing against Google Drive #######################
========================== Synchronizing database backups =========================
STARTING TIME: 16-06-2015 - 00:00:02
STATUS: Synchronization successfully completed.
ENDING TIME: 16-06-2015 - 00:00:09
========================== Synchronizing website backups ==========================
* [16-06-2015 - 00:01:19] Creating temporary tarball for website veterinary.berlin.to (20150615)
* [16-06-2015 - 00:01:28] Synchronizing website backups for veterinary.berlin.to
* [16-06-2015 - 00:02:04] STATUS: Synchronization successfully completed.
* [16-06-2015 - 00:02:04] Removing temporary tarball for website veterinary.berlin.to
-----------------------------------------------------------------------------------
###################################################################################
```

server2:
```
######################## Synchronizing against Google Drive #######################
========================== Synchronizing database backups =========================
STARTING TIME: 16-06-2015 - 00:00:02
STATUS: Synchronization successfully completed.
ENDING TIME: 16-06-2015 - 00:00:09
========================== Synchronizing website backups ==========================
* [16-06-2015 - 00:10:39] Creating temporary tarball for website veterinary.berlin.to (20150615)
* [16-06-2015 - 00:10:47] Synchronizing website backups for veterinary.berlin.to
* [16-06-2015 - 00:11:12] STATUS: Synchronization successfully completed.
* [16-06-2015 - 00:11:12] Removing temporary tarball for website veterinary.berlin.to
-----------------------------------------------------------------------------------
###################################################################################
```

From what I see, here only is overlapped the window of time for copying database dumps. That may explain why the duplicates occurs on this group of files. Note that both servers also copied other dumps but with different names.

Best regards,
Daniel

**Comment by dbareiro** [comment]
Hi, Nick.

In previous days:

Server1 (14-06-2015):
```
######################## Synchronizing against Google Drive #######################
========================== Synchronizing database backups =========================
STARTING TIME: 15-06-2015 - 00:00:03
STATUS: Synchronization successfully completed.
ENDING TIME: 15-06-2015 - 00:00:07
========================== Synchronizing website backups ==========================
* [15-06-2015 - 00:01:17] Creating temporary tarball for website veterinary.berlin.to (20150614)
* [15-06-2015 - 00:01:26] Synchronizing website backups for veterinary.berlin.to
* [15-06-2015 - 00:02:00] STATUS: Synchronization successfully completed.
* [15-06-2015 - 00:02:00] Removing temporary tarball for website veterinary.berlin.to
-----------------------------------------------------------------------------------
###################################################################################
```
Server2 (14-06-2015):
```
######################## Synchronizing against Google Drive #######################
========================== Synchronizing database backups =========================
STARTING TIME: 15-06-2015 - 00:00:02
STATUS: Synchronization successfully completed.
ENDING TIME: 15-06-2015 - 00:00:07
========================== Synchronizing website backups ==========================
* [15-06-2015 - 00:11:31] Creating temporary tarball for website veterinary.berlin.to (20150614)
* [15-06-2015 - 00:11:39] Synchronizing website backups for veterinary.berlin.to
* [15-06-2015 - 00:11:57] STATUS: Synchronization successfully completed.
* [15-06-2015 - 00:11:57] Removing temporary tarball for website veterinary.berlin.to
-----------------------------------------------------------------------------------
###################################################################################
```

And:

Server1 (13-06-2015):
```
######################## Synchronizing against Google Drive #######################
========================== Synchronizing database backups =========================
STARTING TIME: 14-06-2015 - 00:00:02
STATUS: Synchronization successfully completed.
ENDING TIME: 14-06-2015 - 00:00:06
========================== Synchronizing website backups ==========================
* [14-06-2015 - 00:01:14] Creating temporary tarball for website veterinary.berlin.to (20150613)
* [14-06-2015 - 00:01:22] Synchronizing website backups for veterinary.berlin.to
* [14-06-2015 - 00:02:01] STATUS: Synchronization successfully completed.
* [14-06-2015 - 00:02:01] Removing temporary tarball for website veterinary.berlin.to
-----------------------------------------------------------------------------------
###################################################################################
```
Server2: (13-06-2015)
```
######################## Synchronizing against Google Drive #######################
========================== Synchronizing database backups =========================
STARTING TIME: 14-06-2015 - 00:00:01
STATUS: Synchronization successfully completed.
ENDING TIME: 14-06-2015 - 00:00:07
========================== Synchronizing website backups ==========================
* [14-06-2015 - 00:10:54] Creating temporary tarball for website veterinary.berlin.to (20150613)
* [14-06-2015 - 00:10:54] Synchronizing website backups for veterinary.berlin.to
* [14-06-2015 - 00:10:55] STATUS: Synchronization successfully completed.
* [14-06-2015 - 00:10:55] Removing temporary tarball for website veterinary.berlin.to
-----------------------------------------------------------------------------------
###################################################################################
```

Here we can also see that there is overlap between the windows for copying of dumps on both days. Unfortunately I erased the reports of the day 10,11 and 12. If there were no overlap, then that would explain the cause of the duplicates. Although still having overlapping chances are that there has been some condition on the network which could have done that both copying operations had been done in different moments of time. Although would be assumptions.

I'm not sure how else could provide more information. Even timestamps for each pair of duplicate files is the same.


Best regards,
Daniel

**Comment by dbareiro** [comment]
Hi, Nick.

I've verified via web that duplicates are also displayed in this way:

![veterinary_duplicates](https://cloud.githubusercontent.com/assets/7597354/8215531/eaffcb4c-1506-11e5-9ad2-5e6c542703e4.png)

As the only way to choose each specific file is via web (since I have no way of knowing what will download rclone as both have the same name), I downloaded both files for 20150616 (previously renaming):

```
viper@orion:/tmp/veterinary$ ll
total 7072
-rw-r--r-- 1 viper viper 3618034 jun 17 14:54 mysqldump.veterinary.20150616_2300-1.sql.gz
-rw-r--r-- 1 viper viper 3618034 jun 17 14:55 mysqldump.veterinary.20150616_2300-2.sql.gz
```
Here we can see that the two files are different:
```
viper@orion:/tmp/veterinary$ md5sum mysqldump.veterinary.20150616_2300-*
4b8f5a027290ab232005450e4983e1be  mysqldump.veterinary.20150616_2300-1.sql.gz
35a9be3018f3f731811ecf23958c2ddd  mysqldump.veterinary.20150616_2300-2.sql.gz
```
The difference between the two files is curious :-)

```
viper@orion:/tmp/veterinary$ diff mysqldump.veterinary.20150616_2300-1.sql mysqldump.veterinary.20150616_2300-2.sql
2593c2593
< -- Dump completed on 2015-06-16 23:01:07
---
> -- Dump completed on 2015-06-16 23:00:55
```

Among the files of 20160615 appear to be no differences:
```
viper@orion:/tmp/veterinary$ md5sum mysqldump.veterinary.20150615*
c77ad4f6d7da45b1ecc0ded490338c60  mysqldump.veterinary.20150615_2300-1.sql.gz
c77ad4f6d7da45b1ecc0ded490338c60  mysqldump.veterinary.20150615_2300-2.sql.gz
```

Among the files of 20150614 there are differences:
```
viper@orion:/tmp/veterinary$ md5sum mysqldump.veterinary.20150614*
0931f1cc510956aeee7c37b5824e30ca  mysqldump.veterinary.20150614_2300-1.sql.gz
e9e44f4487e8915bf0ca7ee0b92e08ab  mysqldump.veterinary.20150614_2300-2.sql.gz
```

The difference is similar to files generated on 20150616:
```
viper@orion:/tmp/veterinary$ diff mysqldump.veterinary.20150614*
2593c2593
< -- Dump completed on 2015-06-14 23:00:56
---
> -- Dump completed on 2015-06-14 23:00:47
```

Among the files of 20150613 there are also differences:
```
viper@orion:/tmp/veterinary$ md5sum mysqldump.veterinary.20150613*
4329bba58ffb8a4f86219e2b8e0dbcca  mysqldump.veterinary.20150613_2300-1.sql.gz
89a8d3c77087725ee6b48558e787e0f0  mysqldump.veterinary.20150613_2300-2.sql.gz
```

Similar to that seen before:
```
viper@orion:/tmp/veterinary$ diff mysqldump.veterinary.20150613_2300-1.sql mysqldump.veterinary.20150613_2300-2.sql
2593c2593
< -- Dump completed on 2015-06-13 23:01:09
---
> -- Dump completed on 2015-06-13 23:01:01
```

I'm not sure if this will be useful, but I found it interesting to mention it.

Thanks.

Best regards,
Daniel

**Comment by ncw** [comment]
Thanks for doing that testing.  I'm not suprised that running two rclones at exactly the same time causes duplicates - rclone traverses the drive at the start of the run so won't actually notice new files added during the run.

Note that you can examine the duplicates with `rclone lsl` and `rclone md5sum` that will print the duplicates.

I should probably revise my original advice into the FAQ, something like this.  What do you think?

----
### Using rclone from multiple locations at the same time ###

You can use rclone from multiple places at the same time if you choose different subdirectory for the output, eg

    Server A> rclone sync /tmp/whatever remote:ServerA
    Server B> rclone sync /tmp/whatever remote:ServerB

If you sync to the same directory then you should use `rclone copy` otherwise the two rclones may delete each others files, eg

    Server A> rclone copy /tmp/whatever remote:Backup
    Server B> rclone copy /tmp/whatever remote:Backup

The file names you upload from Server A and Server B should be different in this case, otherwise some file systems (eg Drive) may make duplicates.

**Comment by dbareiro** [comment]
Hi, Nick.

Thanks for your reply.

I think it is a successful advice. Moreover, when the documentation becomes ever more complete, users have more confidence in using ```rclone``` because they have in mind that we looked at different test scenarios.

I have not seen a FAQ section on rclone.org. Where it is?

Best regards,
Daniel

**Comment by ncw** [comment]
The FAQ is in preparation - I haven't put it up yet!

**Comment by dbareiro** [comment]
Hi, Nick.

> The FAQ is in preparation - I haven't put it up yet! 

Thank you for taking the time to develop it. Surely it will be very useful!

Best regards,
Daniel

**Comment by ncw** [comment]
See the FAQ here!

http://rclone.org/faq/

Thanks for the report
