### ISSUE TITLE
Publish new release, that includes the SetOpaque fix

### ISSUE THREAD

**Issue by krieghof** [ncw/rclone#780]
It is not possible to compile the latest release of rclone, because of the api changes.
The master branch is possible to compile because it already includes the SetOpaque fix.
For standard users this is no problem, but it makes it hard to package for distros.

**Comment by ncw** [comment]
I see what you mean...

I have considered making a release branch with fixes like that on to get a 1.33.1, 1.33.2, 1.33.3 which would have just the essential bug fixes in from the 1.33 release.

Is that the kind of thing you mean?

Which distro are you packaging for?

**Comment by krieghof** [comment]
Yeah that is exactly what i mean. 
I wanted to package for Solus, but i need to use a release as source, i could also use a commit as source but this is not common.

**Comment by krieghof** [comment]
Do you have any idea when you will release a new version?

**Comment by ncw** [comment]
Very soon!

For your purposes I need to use one of the vendoring solutions for go otherwise the build won't be deterministic.  I've made a new issue about this #816 and will try to do this for the next release.  This will fix the issue permanently!

**Comment by krieghof** [comment]
Looks like this bug is fixed now

**Comment by ncw** [comment]
@krieghof it is indeed!  Will close now
