### ISSUE TITLE
Downloading rclone from an IPv6 only host is impossible

### ISSUE THREAD

**Issue by jvhaarst** [ncw/rclone#782]
I have a host that is connected through only IPv6.
When I try to download rclone, it fails.
Digging further reveals that downloads.rclone.org is only connected through IPv4:

<pre>
dig downloads.rclone.org

; <<>> DiG 9.9.5-3ubuntu0.9-Ubuntu <<>> downloads.rclone.org
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 34637
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;downloads.rclone.org.          IN      A

;; ANSWER SECTION:
downloads.rclone.org.   3599    IN      CNAME   downloads-rclone-org.7d7d567e.cdn.memsites.com.
downloads-rclone-org.7d7d567e.cdn.memsites.com. 599 IN A 77.73.5.145

;; Query time: 204 msec
;; SERVER: 2001:4860:4860::8888#53(2001:4860:4860::8888)
;; WHEN: Mon Oct 10 06:23:38 EDT 2016
;; MSG SIZE  rcvd: 125
</pre>

For now, I'll just copy rclone over from a server that is dualstack.

I have signed up for a free MEMSET MEMSTORE myself to see if it possible to enable IPv6 there, so it might be a simple fix.

**Comment by ncw** [comment]
The github mirror doesn't support IPv6 either :-(

Does your IPv6 network not have an IPv4 gateway?

**Comment by jvhaarst** [comment]
Nope, that is what I use this machine for, to test whether services can be reached by IPv6.
It's sort of a quality check for a service, no IPv6 is an indication that they provider isn't very up to date..

**Comment by DurvalMenezes** [comment]
@ncw, I have a VPS where I have both IPv4 and IPv6 connectivity, and where I already run Apache. If you want, I can set a "Proxy" redirection there so people with just IPv6 connectivity can access it to download rclone, while MEMSET doesn't fix it.

**Comment by jvhaarst** [comment]
@DurvalMenezes I think it's better to wait for MEMSET to respond, and if they can't/won't fix look for options.

**Comment by ncw** [comment]
I see!  I work at Memset so I'll see what is going on with IPv6 support :-)

**Comment by jvhaarst** [comment]
This is the answer I got :

> I can confirm that Memstore is currently not accessible over IPv6.
> This is in the pipeline, but does require some changes on our end.

So not, now, maybe later.

**Comment by ncw** [comment]
I've moved the downloads onto its own server now so this should be accessible via IPv6.  It is possible the DNS hasn't finished propagating yet so if it doesn't work immediately wait an hour and try again!
