### ISSUE TITLE
Google Drive Issue 403

### ISSUE THREAD

**Issue by spencercharest** [ncw/rclone#785]
When filing an issue, please include the following information if
possible as well as a description of the problem.  Make sure you test
with the [latest beta of rclone](http://rclone.org/downloads/).

> What is your rclone version (eg output from `rclone -V`)
1.33
> Which OS you are using and how many bits (eg Windows 7, 64 bit)
Ubuntu 14.04 64 bit
> Which cloud storage system are you using? (eg Google Drive)
Google Drive(encrypted)
> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone copy
> A log from the command with the `-v` flag (eg output from `rclone -v copy /tmp remote:tmp`)
2016/10/12 03:43:20 Local file system at /home/spencercharest/test: Waiting for checks to finish
2016/10/12 03:43:20 Local file system at /home/spencercharest/test: Waiting for transfers to finish
2016/10/12 03:43:20 Atlanta - S01E07 - B.A.N..mkv: Failed to copy: failed to open source object: bad response: 403: 403 Forbidden
2016/10/12 03:43:20 Attempt 1/3 failed with 1 errors and: failed to open source object: bad response: 403: 403 Forbidden
2016/10/12 03:43:20 Google drive root 'rvt9adj21phi9s74vcdshrkq3o/vgsmkfpb8q2f7on8kkgmvr1vhg/c02dkvh41cfdh9sirgbbaqo9bs/3npmbr6junlt8ra808beogqa30': Reading ""
2016/10/12 03:43:21 Google drive root 'rvt9adj21phi9s74vcdshrkq3o/vgsmkfpb8q2f7on8kkgmvr1vhg/c02dkvh41cfdh9sirgbbaqo9bs/3npmbr6junlt8ra808beogqa30': Finished reading ""
2016/10/12 03:43:21 Local file system at /home/spencercharest/test: Waiting for checks to finish
2016/10/12 03:43:21 Local file system at /home/spencercharest/test: Waiting for transfers to finish
2016/10/12 03:43:21 Atlanta - S01E07 - B.A.N..mkv: Failed to copy: failed to open source object: bad response: 403: 403 Forbidden
2016/10/12 03:43:21 Attempt 2/3 failed with 1 errors and: failed to open source object: bad response: 403: 403 Forbidden
2016/10/12 03:43:21 Google drive root 'rvt9adj21phi9s74vcdshrkq3o/vgsmkfpb8q2f7on8kkgmvr1vhg/c02dkvh41cfdh9sirgbbaqo9bs/3npmbr6junlt8ra808beogqa30': Reading ""
2016/10/12 03:43:21 Google drive root 'rvt9adj21phi9s74vcdshrkq3o/vgsmkfpb8q2f7on8kkgmvr1vhg/c02dkvh41cfdh9sirgbbaqo9bs/3npmbr6junlt8ra808beogqa30': Finished reading ""
2016/10/12 03:43:21 Local file system at /home/spencercharest/test: Waiting for checks to finish
2016/10/12 03:43:21 Local file system at /home/spencercharest/test: Waiting for transfers to finish
2016/10/12 03:43:21 Atlanta - S01E07 - B.A.N..mkv: Failed to copy: failed to open source object: bad response: 403: 403 Forbidden
2016/10/12 03:43:21 Attempt 3/3 failed with 1 errors and: failed to open source object: bad response: 403: 403 Forbidden
2016/10/12 03:43:21 Failed to copy: failed to open source object: bad response: 403: 403 Forbidden

I just started encountering this error today. It has been working fine for days. I can upload fine but can't copy.

**Comment by ncw** [comment]
403 errors are normal as part of using google drive - they are drive's way of telling rclone to slow down.  rclone should slow down and drive be happy with that.

Can you run rclone with the `-v` flag and attach the output please?

Thanks

Nick

**Comment by spencercharest** [comment]
The output above was run with -v

**Comment by spencercharest** [comment]
It started working normally again today. Maybe it was just an issue with Drive? ACD was working fine the entire time I was having issues with dive.

**Comment by ncw** [comment]
Drive has lots of internal resource limits - maybe you tripped one of those and had to wait for it to reset.

**Comment by spencercharest** [comment]
Hey @ncw do you happen to know what the limit is? It appears I've been exceeding download limits. I've done some research but haven't been able to find anything concrete.

**Comment by ncw** [comment]
@spencercharest no - google don't publish them so we are left guessing!
