### ISSUE TITLE
Moving servers - question about .rclone.conf

### ISSUE THREAD

**Issue by scriptzteam** [ncw/rclone#787]
So i using latest ubuntu 16.04.1 LTS and latest stable rclone 1.33

My question is if i copy from my old server file in /root/.rclone.conf into new server on the same location will it works? Or do i need re-auh ?

**Comment by danzig666** [comment]
It just works, no need for reauth.

**Comment by scriptzteam** [comment]
Not works - Failed to create file system for "secret:/TEST": didn't find section in config file

**Comment by scriptzteam** [comment]
```
./rclone config
No remotes found - make a new one
n) New remote
s) Set configuration password
q) Quit config
n/s/q>

```

**Comment by scriptzteam** [comment]
Aha it works i just needed to copy it from /root into /home/user/.rclone.conf

**Comment by ncw** [comment]
FYI there is an FAQ about this: http://rclone.org/faq/#can-i-copy-the-config-from-one-machine-to-another
