### ISSUE TITLE
Sync transfers a lot more data than file sizes?

### ISSUE THREAD

**Issue by ArminXG** [ncw/rclone#791]
Hello,

I am using rclone v1.33 with the crypt feature on amazonclouddrive.
Running on raspberry Pi 3 with raspian.

I started a rclone sync of one directory containing 10 big files (from 5M to 80G), together about 170GB. My upstream speed is just 10Mbit/s, so I know it will take longer. But it is running for days now and it should be already finished. One file is left and still being uploaded (the big 80G file).
The curious thing is that rclone gives me the status every minute like:

`Transferred:   433.574 GBytes (1.105 MBytes/s)
Errors:                 0
Checks:                 2
Transferred:            7
Elapsed time:  111h38m9.9s
Transferring:
-                           Zenbook_home.tar.xz: 58% done. avg: 1125.8, cur: 1133.1 kByte/s. ETA: 8h51m2s
  `

The speed looks okay, but why Transferred:   433.574 GBytes ?
The file to upload are just 170GB. What is this "Transferred" value telling me?

Armin

**Comment by ncw** [comment]
What has probably happened is that some files have needed to be uploaded again.  You can see this in the log - use `-v` for more info.

There is a problem with uploading very large files to ACD - I suggest you try this beta: http://pub.rclone.org/v1.33-66-g2e20a0f-acd-timeout%CE%B2/ which has a fix designed to work around exactly that problem.

**Comment by l3uddz** [comment]
been getting this alot with ~10GB files, will be trying the beta next time need to sync some large files.

**Comment by ArminXG** [comment]
Confirmed, the upload is restarted from the beginning at some point due to an error. But acd-timeout beta doesn't help. The problem stays. -v gives me this after some time:
`
Upload error detected but didn't finish upload: Post https://content-eu.drive.amazonaws.com/cdproxy/nodes?suppress=deduplication: write tcp 192.168.50.2:41572->54.76.75.204:443: write: connection reset by peer

pacer: Rate limited, sleeping for 772.702441ms (1 consecutive low level retries)

pacer: low level retry 1/1 (error Post https://content-eu.drive.amazonaws.com/cdproxy/nodes?suppress=deduplication: write tcp 192.168.50.2:41572->54.76.75.204:443: write: connection reset by peer)

Received error: Post https://content-eu.drive.amazonaws.com/cdproxy/nodes?suppress=deduplication: write tcp 192.168.50.2:41572->54.76.75.204:443: write: connection reset by peer - low level retry 1/10
`

**Comment by ladude626** [comment]
I have the same issues too. Files appear to upload complete at 100% but would restart from the beginning.

**Comment by Stonedestroyer** [comment]
Is the issue not that Amazon only supports files upto 50GB so it would keep getting restarted and never uploaded? 
https://forums.developer.amazon.com/questions/22038/support-for-chunked-transfer-encoding.html
https://github.com/ncw/rclone/issues/215

**Comment by ncw** [comment]
@Stonedestroyer  You can't upload files bigger than 50GB - there is a bit in the docs about it with a workaround: http://rclone.org/amazonclouddrive/#limitations
