### ISSUE TITLE
--min-age and something like always include file regex possible ?

### ISSUE THREAD

**Issue by scriptzteam** [ncw/rclone#792]
I am running latest 1.33 and wanted to ask if its possible when i have set --min-age to always include for example file *.sfv, as *.sfv is changing always it is never 2days old, so something like --always-include *some_regex*

**Comment by ncw** [comment]
The rclone filter rules aren't powerful enough for that. You'll have to run rclone twice to achieve what you want - exclude *.sfv in the first run then include in the second.

**Comment by scriptzteam** [comment]
Understand, thx :)
