### ISSUE TITLE
New feature to delete old file versions on B2.

### ISSUE THREAD

**Issue by jackools** [ncw/rclone#794]
I saw this option in B2 CLI help, _**--keepDays N**_ (When the destination is B2, you have the option of leaving older versions in place. Specifying _--keepDays_ will delete any older versions more than the given number of days old, based on the modification time of the file. This option is not available when the destination is a local folder.)
It's a good idea to implement a similar option in rclone. And it would be great if the option takes 0 as the #days to disable B2 file versions feature and delete the old files instantly.

**Comment by ncw** [comment]
Good idea.

**Comment by DBaakman** [comment]
Now Backblaze has introduced Lifecycle Rules (https://www.backblaze.com/b2/docs/lifecycle_rules.html), maybe this enhancement has less priority.

Personally, I'm considering rclone for a (secondary) backup to b2. And having a way to keep multiple versions of a file, but also being able to purge old versions after a time, was a feature I'd really like. So, I was very interested in this enhancement. But the Lifecycle Rule can fulfill the requirement I have.

**Comment by ncw** [comment]
@DBaakman thanks for your comment.  I'm going to close this now as the b2 lifecycle rules seem perfect and it saves adding another b2 only feature.

**Comment by poleguy** [comment]
I have created a little script wrapped around b2 command line tools that will purge only old files older than a certain number of days. https://github.com/poleguy/b2purge
I have run this on my own b2 backup data because my bucket was configured to keep everything (the default) and it seems that changing the backblaze rules to set a lifecycle time only applies the lifecycle to newly uploaded files.

**Comment by jelther** [comment]
For anyone coming here in 2024:  if you're using a S3 bucket on B2, you can purge older files using `boto3` so you can save space (if you , like me , forgot to only mark as last version of files in your bucket).

Worked fine for me!

**Comment by ncw** [comment]
Note that you can now set the lifecycle rules with rclone

### lifecycle

Read or set the lifecycle for a bucket

    rclone backend lifecycle remote: [options] [<arguments>+]

This command can be used to read or set the lifecycle for a bucket.

Usage Examples:

To show the current lifecycle rules:

    rclone backend lifecycle b2:bucket

This will dump something like this showing the lifecycle rules.

    [
        {
            "daysFromHidingToDeleting": 1,
            "daysFromUploadingToHiding": null,
            "fileNamePrefix": ""
        }
    ]

If there are no lifecycle rules (the default) then it will just return [].

To reset the current lifecycle rules:

    rclone backend lifecycle b2:bucket -o daysFromHidingToDeleting=30
    rclone backend lifecycle b2:bucket -o daysFromUploadingToHiding=5 -o daysFromHidingToDeleting=1

This will run and then print the new lifecycle rules as above.

Rclone only lets you set lifecycles for the whole bucket with the
fileNamePrefix = "".

You can't disable versioning with B2. The best you can do is to set
the daysFromHidingToDeleting to 1 day. You can enable hard_delete in
the config also which will mean deletions won't cause versions but
overwrites will still cause versions to be made.

    rclone backend lifecycle b2:bucket -o daysFromHidingToDeleting=1

See: https://www.backblaze.com/docs/cloud-storage-lifecycle-rules


Options:

- "daysFromHidingToDeleting": After a file has been hidden for this many days it is deleted. 0 is off.
- "daysFromUploadingToHiding": This many days after uploading a file is hidden
