### ISSUE TITLE
'--bwlimit' honored when using 'mount'?

### ISSUE THREAD

**Issue by arionl** [ncw/rclone#796]
I noticed that when I'm copying a file via a FUSE mount, the value I specified for `--bwlimit` doesn't seem to be honored. I'm validating this by watching `iftop` and the output of `rsync -ahr --progress`. I specified `--bwlimit=3M` I'm seeing ~5M actual.

> What is your rclone version (eg output from `rclone -V`)

rclone v1.33-64-gbc414b6β

> Which OS you are using and how many bits (eg Windows 7, 64 bit)

Ubuntu 14.04.02 64bit

> Which cloud storage system are you using? (eg Google Drive)

Amazon Cloud Drive + Crypt

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

`rclone -v --acd-upload-wait-time 15m --bwlimit=3M --config /opt/rclone/rclone.conf mount acdcrypt: /mnt/acdcrypt --allow-other`

> A log from the command with the `-v` flag (eg output from `rclone -v copy /tmp remote:tmp`)

Don't know if this would be helpful, missed the top of the output and now its mostly `WriteFileHandle.Write OK (131072 bytes written)`.

**Comment by ncw** [comment]
I don't think the bandwidth limiting is working at all with rclone mount!

Do you agree - what if you try a really small `--bwlimit` do you get the same speed?

**Comment by arionl** [comment]
Confirmed, I tried with ```--bwlimit=100k``` and still saw about the same speed as I measured above (~5M).

**Comment by ncw** [comment]
Here is a test version of rclone where bwlimit should work with rclone mount

http://pub.rclone.org/v1.34-39-g7be5724-fuse-buffer%CE%B2/

**Comment by ncw** [comment]
I've merged this to master now: http://beta.rclone.org/v1.34-48-gc24da0b/ (will be uploaded in 15-30 mins)
