### ISSUE TITLE
Misleading message from rclone check

### ISSUE THREAD

**Issue by ebridges** [ncw/rclone#798]
> What is your rclone version (eg output from `rclone -V`)

```
$ rclone -V
rclone v1.33-6-g2eaac80β
```

> Which OS you are using and how many bits (eg Windows 7, 64 bit)

```
$ uname -a
Darwin home 15.5.0 Darwin Kernel Version 15.5.0: Tue Apr 19 18:36:36 PDT 2016; root:xnu-3248.50.21~8/RELEASE_X86_64 x86_64
```

> Which cloud storage system are you using? (eg Google Drive)

N/A

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

`rclone -q check ~/src ~/des`

When rclone check is run, the last line of the output is reporting:

```
$ rclone -q check ~/src ~/des
2016/10/16 10:40:55 hello/Hello.txt: File not in Local file system at ~/des
2016/10/16 10:40:55 Failed to check: 1 differences found
```

The final line is misleading in that `check` has not failed (or perhaps I'm misunderstanding the context of that message).

I was unable to find where that message actually gets output, using:

`find . -name '*.go' -exec grep  'Failed to check' {} \;`

Given a pointer on how to locate that log message would be glad to rephrase it.

**Comment by ncw** [comment]
That message is a generic this command failed message produced here.  So when `rclone XXX` with error YYY, it prints `Failed to XXX: YYY`

https://github.com/ncw/rclone/blob/master/cmd/cmd.go#L188

The other part of the error is made here

https://github.com/ncw/rclone/blob/master/fs/operations.go#L564

**Comment by ebridges** [comment]
The simplest way I guess I could approach this would be to just do this:

```
        if differences > 0 {
-               return errors.Errorf("%d differences found", differences)
+               ErrorLog("Summary: %d differences found.", differences)
        }
```

But would like to be clear that there are no other implications to not returning any errors there.  It seems fine, and the previous way seems to be overloading the concept of an error just to log some information -- so this could rationalize it a bit more.

**Comment by ncw** [comment]
check needs to return an error so rclone knows to return an exit code.

It needn't be that error though...

Interestingly this is also being discussed on the forum: https://forum.rclone.org/t/pipe-into-text-or-grep-not-working/58/5

Where the suggestion is that rclone should be writing the output of check to stdout.  In that case then I should probably change the error returned to be a bit more generic.  Though in your diff it is an error so probably go to stderr (and hence ErrorLog).

**Comment by ebridges** [comment]
Is it true that the `Check` function needs to return an error?  [L578](https://github.com/ncw/rclone/blob/master/fs/operations.go#L578) is returning `nil`.

I assumed `nil` in this context would mean that the command executed successfully, which would appear to be the case in this situation.

**Comment by ncw** [comment]
@ebridges the Check function returns an error either if something went wrong, or a difference was found.  The final nil is if everything was OK and no differences were found.

I'd be happy to receive a rewording of the error message if you can come up with something :-)

**Comment by ebridges** [comment]
@ncw Thanks for the follow up on this!

Forgive me, but I'm confused why a difference is being considered an error condition in this case.

Also, if `nil` is returned from the check command, the only significant implication to that would be that [`cmd.go#L188`](https://github.com/ncw/rclone/blob/master/cmd/cmd.go#L188) would not print a "Fatal" log message.

I push back on this because the original issue that I raised was that the wording (as logged on `L188`) is `Failed to check: ...` which is incorrect: the check did succeed and found differences.

**Comment by ncw** [comment]
@ebridges the point of the `rclone check` command is to ask the question - are all my files uploaded correctly.  The unix convention in this case is to return an error if everything isn't OK.  This means you can script `rclone check` command and do something if there is something wrong.  For instance the unix `grep` command works in a similar way - if it finds something it doesn't return and error, but if it doesn't is does return an error even though the grep command ran correctly.
