### ISSUE TITLE
Drobpox: Can't sync file - cannot unmarshal number error?

### ISSUE THREAD

**Issue by darren12345** [ncw/rclone#80]
Hi Nick,

What does this error mean? The only thing unusual about this directory is that there are some large files (several GB). Is there a file size limit?

```
darren@serverb3:~$ rclone -v sync --size-only  dropbox:Videos/ /home/storage/video/ --dry-run
2015/06/15 13:21:32 Dropbox root 'Videos': Open rclone datastore
2015/06/15 13:21:33 Local file system at /home/storage/video: Modify window is 1s
2015/06/15 13:21:33 Local file system at /home/storage/video: Building file list
2015/06/15 13:21:33 Local file system at /home/storage/video: Waiting for checks to finish
2015/06/15 13:21:33 Dropbox root 'Videos': Open rclone datastore finished
2015/06/15 13:21:33 Dropbox root 'Videos': Couldn't list: json: cannot unmarshal number 5099896832 into Go value of type int
2015/06/15 13:21:33 Local file system at /home/storage/video: Waiting for transfers to finish
2015/06/15 13:21:33 Local file system at /home/storage/video: Not deleting files as there were IO errors

Transferred:            0 Bytes (   0.00 kByte/s)
Errors:                 1
Checks:                 0
Transferred:            0
Elapsed time:  1.848898883s

2015/06/15 13:21:33 Go routines at exit 12
darren@serverb3:~$ rclone -V
rclone v1.17
```
Thanks.

**Comment by ncw** [comment]
I'd say you have a file bigger than 2 GB and that you are running on a 32 bit machine.

It will work if you try it on a 64 bit machine most likely.

However that does look like a bug

In `github.com/stacktic/dropbox/dropbox.go` it looks like the below should be an `int64` instead of an `int`.

```go
type Entry struct {
	Bytes                int       `json:"bytes,omitempty"`        // Size of the file in bytes.
```

I'll investigate further - thanks.

**Comment by darren12345** [comment]
Thanks Nick. Yes, it's a 32-bit box so that's probably it.

**Comment by darren12345** [comment]
Just FYI, on the same box I seem to be able to download a >4GB file from Dropbox using this script: https://github.com/andreafabrizi/Dropbox-Uploader so it's not necessarily a problem to download big files on 32-bit systems.

**Comment by ncw** [comment]
You are right, it is a bug in the dropbox library I'm using.  I'll submit a fix to the author, but it will require a breaking interface change so I don't know how well it will go down.

**Comment by ncw** [comment]
Upstream issue stacktic/dropbox#19 created

**Comment by ncw** [comment]
Proposed fix for the above stacktic/dropbox#20

**Comment by darren12345** [comment]
Works a treat now. many thanks.

**Comment by ncw** [comment]
This has now made it to the v1.18 release

Thanks for the report
