### ISSUE TITLE
Azure Blob Support

### ISSUE THREAD

**Issue by jordannielsen** [ncw/rclone#801]
When filing an issue, please include the following information if
possible as well as a description of the problem.  Make sure you test
with the [latest beta of rclone](http://rclone.org/downloads/).

> What is your rclone version (eg output from `rclone -V`)
> 
> Which OS you are using and how many bits (eg Windows 7, 64 bit)
> 
> Which cloud storage system are you using? (eg Google Drive)
> 
> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
> 
> A log from the command with the `-v` flag (eg output from `rclone -v copy /tmp remote:tmp`)

**Comment by ncw** [comment]
Is that the equivalent of S3?  Can you link the API docs?

**Comment by zuzzurro** [comment]
https://msdn.microsoft.com/en-us/library/azure/dd179355.aspx

**Comment by zuzzurro** [comment]
Do you think that support Azure Blob storage would be feasible? Is that link what you were looking for? I for sure would love to see that supported.

**Comment by zuzzurro** [comment]
https://github.com/Azure/azure-sdk-for-go

This may be of help?

**Comment by mappu** [comment]
Another golang project providing filesystem-like abstraction over cloud storage is: docker registry.

Their FS abstraction is here: https://github.com/docker/distribution/blob/master/registry/storage/driver

Their Azure Blob implementation is here: https://github.com/docker/distribution/blob/master/registry/storage/driver/azure/azure.go

**Comment by ncw** [comment]
The Azure SDK looks complete and supported:  https://godoc.org/github.com/Azure/azure-sdk-for-go/storage

Anyone fancy having a go at this?

**Comment by ncw** [comment]
I've uploaded a beta for this here:

https://pub.rclone.org/v1.37-042-gae0654ec-azure%CE%B2/ 

Please test and give feed back!

[Docs for azure blob storage](https://github.com/ncw/rclone/blob/azure/docs/content/azureblob.md)

**Comment by ncw** [comment]
Thanks to @adragomir for the initial implementation.

**Comment by ncw** [comment]
I've merged this to master now - find it here

https://beta.rclone.org/v1.37-063-gee6a35d7/ (uploaded in 15-30 mins)

[Docs for azure blob storage](https://github.com/ncw/rclone/blob/master/docs/content/azureblob.md)

Please test!

**Comment by dnadeem** [comment]
Testing now. Will post with results.

**Comment by zuzzurro** [comment]
I tested it ultra quickly and I was able to connect and do a listing. I did
not try to copy anything yet. Only thing I noticed is that most of the
listing fields were not valued.
Will test more..

**Comment by fd0** [comment]
I have played around with it a little, it seems that listing an empty container is treated as an error.

**Comment by ncw** [comment]
@fd0 I'm not seeing that

```
 $ rclone mkdir azure:new-empty-bucket
 $ rclone ls azure:new-empty-bucket
```

How are you seeing the error?

**Comment by ncw** [comment]
@zuzzurro 

> Only thing I noticed is that most of the listing fields were not valued.

Not sure I understand what you mean.  Can you paste an example?

**Comment by fd0** [comment]
> How are you seeing the error?

For an existing container `restic-dev-an` (created via the web console):
```
$ ./rclone ls azure:restic-dev-an
2017/08/06 17:08:15 ERROR : : error listing: directory not found
2017/08/06 17:08:15 Failed to ls: directory not found
[1]    15286 exit 1     ./rclone ls azure:restic-dev-an

$ ./rclone sync notes.txt azure:restic-dev-an
2017/08/06 17:08:37 ERROR : Ignoring --no-traverse with sync

$ ./rclone ls azure:restic-dev-an
     1492 notes.txt 

$ ./rclone purge azure:restic-dev-an

$ ./rclone ls azure:restic-dev-an     
2017/08/06 17:10:59 ERROR : : error listing: directory not found
2017/08/06 17:10:59 Failed to ls: directory not found
[1]    16379 exit 1     ./rclone ls azure:restic-dev-an
```

With debug:
```
$ ./rclone -vv --dump-headers ls azure:restic-dev-an
2017/08/06 17:12:14 DEBUG : rclone: Version "v1.37-DEV" starting with parameters ["./rclone" "-vv" "--dump-headers" "ls" "azure:restic-dev-an"]
2017/08/06 17:12:14 INFO  : Azure container restic-dev-an: Modify window is 1ns
2017/08/06 17:12:14 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2017/08/06 17:12:14 DEBUG : HTTP REQUEST (req 0xc420215000)
2017/08/06 17:12:14 DEBUG : GET /restic-dev-an?comp=list&delimiter=%2F&include=metadata&maxresults=5000&restype=container HTTP/1.1
Host: restictesting.blob.core.windows.net
User-Agent: rclone/v1.37-DEV
Authorization: XXXX
x-ms-date: Sun, 06 Aug 2017 15:12:14 GMT
x-ms-version: 2017-04-17
Accept-Encoding: gzip
2017/08/06 17:12:14 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2017/08/06 17:12:14 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2017/08/06 17:12:14 DEBUG : HTTP RESPONSE (req 0xc420215000)
2017/08/06 17:12:14 DEBUG : HTTP/1.1 404 The specified container does not exist.
Content-Length: 225
Content-Type: application/xml
Date: Sun, 06 Aug 2017 15:12:15 GMT
Server: Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0
X-Ms-Request-Id: 1b5c7b42-0001-00ba-20c6-0e6153000000
X-Ms-Version: 2017-04-17
2017/08/06 17:12:14 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2017/08/06 17:12:14 ERROR : : error listing: directory not found
2017/08/06 17:12:14 Failed to ls: directory not found
[1]    16733 exit 1     ./rclone -vv --dump-headers ls azure:restic-dev-an
```

**Comment by fd0** [comment]
Oh, hm, it looks like `rclone purge` removes the container. So the 404 is correct. I wonder why I did not see that earlier, so everything is probably all right.

**Comment by ncw** [comment]
> Oh, hm, it looks like `rclone purge` removes the container. So the 404 is correct. I wonder why I did not see that earlier, so everything is probably all right.

Yes `rclone purge` does remove the container.

I thought your problem was going to be around removing and making containers very quickly - there is some kind of timeout mechanism in azure which gives you this error if you do

```
2017/08/06 20:11:34 ERROR : Attempt 1/3 failed with 1 errors and: failed to make container: storage: service returned error: StatusCode=409, ErrorCode=ContainerBeingDeleted, ErrorMessage=The specified container is being deleted. Try operation later.
RequestId:183b3692-0001-0020-5ee7-0ef6d8000000
```

**Comment by dnadeem** [comment]
No issues copying and downloading 10gb to Azure.

**Comment by zuzzurro** [comment]
Sorry I was not at my terminal when I wrote: 
>     Only thing I noticed is that most of the listing fields were not valued.

I should have said: A couple of fields show as -1, like this:

```
me@localhost> ./rclone lsd mediaservice:
          -1 2017-08-09 14:38:49        -1 $root
          -1 2017-08-09 14:38:49        -1 activation
          -1 2017-08-09 14:38:49        -1 asset-00045b22-4c41-4f2a-a603-e96aad193ff7
```

**Comment by ncw** [comment]
@zuzzurro I think that is as expected - I don't think azure can tell you number of files or size of a container, however it can tell you the date it was last modified which I wasn't reading.  I've put that in now, you'll find it in

https://beta.rclone.org/v1.37-089-g28708743/ (uploaded in 15-30 mins)

**Comment by ncw** [comment]
I'm going to mark this issue complete now - please report any issues as a new issue!

Thanks
