### ISSUE TITLE
Packet Drops when just rclone is running

### ISSUE THREAD

**Issue by robins** [ncw/rclone#807]
On a Pi2 connected to an otherwise 4-device home-wifi, I see that since 2 days the pi drops 15-20% of packets when rclone is copying. 

The Pi is doing nothing else and is available for any further commands that you may want me to check and revert with logs.

I am logging in with my laptop and can clearly see lags in ssh when rclone runs (in screen). The odd thing is rclone COPY / SYNC commands worked perfectly fine 2 days back and was copying over the same setup at ~10mbps or so. I do have unattended-upgrades installed and this could be the handy-work of some update that happened in the interim without me knowing. 

Some basic observations are given below:

* top shows nothing. 5% on an average, nothing else but rclone (given below).
* atop shows nothing interesting as well (I think).
* netstat -s gives a ton of packet loss / socket locked etc.. which I can't understand. Am ok to run / get back with more commands in case you need anything else.
* mtr shows the clear reason why ssh / copy is slow.. I just don't know why this is only when rclone is running. As soon as I kill rclone (running in screen) packet drops gone, ssh typing lag goes away!

```
pi@raspberrypi:~/v $ rclone --version
rclone v1.33-DEV
pi@raspberrypi:~/v $ rclone version
rclone v1.33-DEV
pi@raspberrypi:~/v $ uname -a
Linux raspberrypi 4.4.21-v7+ #911 SMP Thu Sep 15 14:22:38 BST 2016 armv7l GNU/Linux
pi@raspberrypi:~/v $ cat /etc/debian_version
8.0
pi@raspberrypi:~/v $ rclone -v copy gdrive:Abc Abc
.... 
2016/10/20 19:58:48
Transferred:   18.610 MBytes (14.905 kBytes/s)
Errors:                 0
Checks:                12
Transferred:            7
Elapsed time:    21m18.4s
Transferring:
 *                  Nov 30/t/20131123_102613.jpg: 90% done. avg:    3.3, cur:    0.8 kByte/s. ETA: 3m54s
 *                  Nov 30/t/20131123_124651.mp4:  2% done. avg:    3.6, cur:    0.0 kByte/s. ETA: 596523h14m7s
 *                  Nov 30/t/20131123_143556.mp4:  0% done. avg:    0.0, cur:    0.0 kByte/s. ETA: -
 *                  Nov 30/t/20131123_144302.mp4:  0% done. avg:    0.0, cur:    0.0 kByte/s. ETA: -

2016/10/20 19:59:48
Transferred:   18.642 MBytes (14.262 kBytes/s)
Errors:                 0
Checks:                12
Transferred:            7
Elapsed time:    22m18.4s
Transferring:
 *                  Nov 30/t/20131123_102613.jpg: 92% done. avg:    3.0, cur:    1.1 kByte/s. ETA: 2m21s
 *                  Nov 30/t/20131123_124651.mp4:  2% done. avg:    3.4, cur:    0.0 kByte/s. ETA: 596523h14m7s
 *                  Nov 30/t/20131123_143556.mp4:  0% done. avg:    0.0, cur:    0.0 kByte/s. ETA: -
 *                  Nov 30/t/20131123_144302.mp4:  0% done. avg:    0.0, cur:    0.0 kByte/s. ETA: -

2016/10/20 20:00:48
Transferred:   18.767 MBytes (13.741 kBytes/s)
Errors:                 0
Checks:                12
Transferred:            7
Elapsed time:    23m18.4s
Transferring:
 *                  Nov 30/t/20131123_102613.jpg: 98% done. avg:    3.0, cur:    1.0 kByte/s. ETA: 35s
 *                  Nov 30/t/20131123_124651.mp4:  2% done. avg:    3.2, cur:    0.0 kByte/s. ETA: 596523h14m7s
 *                  Nov 30/t/20131123_143556.mp4:  0% done. avg:    0.0, cur:    0.0 kByte/s. ETA: -
 *                  Nov 30/t/20131123_144302.mp4:  0% done. avg:    0.0, cur:    0.0 kByte/s. ETA: -
^C

pi@raspberrypi:~/v $ top c
top - 20:04:20 up 1 day,  8:50,  1 user,  load average: 0.01, 0.05, 0.06
Tasks: 124 total,   1 running, 123 sleeping,   0 stopped,   0 zombie
%Cpu(s):  0.2 us,  0.3 sy,  0.7 ni, 98.7 id,  0.0 wa,  0.0 hi,  0.1 si,  0.0 st
KiB Mem:    947740 total,   634596 used,   313144 free,    38360 buffers
KiB Swap:   102396 total,      104 used,   102292 free.   518716 cached Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
12897 pi        39  19  853568  13432   9020 S   3.0  1.4   0:00.96 rclone -v copy gdrive:Ana/2013 2013
12905 pi        20   0    5148   2524   2108 R   1.0  0.3   0:00.10 top c
  733 root      20   0   35640   5740   4056 S   0.3  0.6   0:09.13 /usr/sbin/smbd -D
12876 root      20   0       0      0      0 S   0.3  0.0   0:00.19 [kworker/0:0]
    1 root      20   0    5416   3476   2340 S   0.0  0.4   0:11.36 /sbin/init

    
----------------------
    
ATOP - raspberrypi        2016/10/20  20:05:55        ------         10s elapsed
PRC | sys    0.09s | user   0.20s | #proc    126 | #zombie    0 | #exit      1 |
CPU | sys       1% | user      2% | irq       0% | idle    397% | wait      0% |
cpu | sys       1% | user      2% | irq       0% | idle     98% | cpu000 w  0% |
cpu | sys       0% | user      0% | irq       0% | idle    100% | cpu002 w  0% |
cpu | sys       0% | user      0% | irq       0% | idle    100% | cpu001 w  0% |
cpu | sys       0% | user      0% | irq       0% | idle    100% | cpu003 w  0% |
CPL | avg1    0.18 | avg5    0.08 | avg15   0.07 | csw     3183 | intr   16124 |
MEM | tot   925.5M | free  280.1M | cache 462.6M | buff   37.5M | slab   31.4M |
SWP | tot   100.0M | free   99.9M |              | vmcom 209.7M | vmlim 562.8M |
DSK |      mmcblk0 | busy      0% | read       0 | write     17 | avio 1.76 ms |
NET | transport    | tcpi     137 | tcpo     144 | udpi       0 | udpo       0 |
NET | network      | ipi      147 | ipo      145 | ipfrw      0 | deliv    137 |
NET | wlan0   ---- | pcki     148 | pcko     146 | si  156 Kbps | so   17 Kbps |

  PID  SYSCPU  USRCPU  VGROW  RGROW  RDDSK  WRDSK ST EXC S  CPU CMD
12897   0.02s   0.12s     0K     0K     0K     0K --   - S   1% rclone
12930   0.05s   0.05s     0K     0K     0K     0K --   - R   1% atop
12924   0.00s   0.02s     0K     0K     0K     0K --   - S   0% kworker/0:2
  721   0.00s   0.01s     0K     0K     0K     4K --   - S   0% nmbd
11845   0.01s   0.00s     0K     0K     0K     0K --   - S   0% sshd
   92   0.01s   0.00s     0K     0K     0K     0K --   - S   0% usb-storage
    1   0.00s   0.00s     0K     0K     0K     0K --   - S   0% systemd
12926   0.00s   0.00s     0K     0K     0K     0K --   - S   0% less
   80   0.00s   0.00s     0K     0K     0K     0K --   - S   0% mmcqd/0
   93   0.00s   0.00s     0K     0K     0K     0K --   - S   0% jbd2/mmcblk0p2
12932   0.00s   0.00s     0K     0K      -      - NE   0 E   0% <nmbd>
-----------------------------
                                    My traceroute  [v0.85]
raspberrypi (0.0.0.0)                                                 Thu Oct 20 20:11:33 2016
Keys:  Help   Display mode   Restart statistics   Order of fields   quit
                                                      Packets               Pings
 Host                                               Loss%   Snt   Last   Avg  Best  Wrst StDev
 1. onhub.here                                      60.0%     5   79.2 114.0  79.2 148.7  49.1


```

**Comment by ncw** [comment]
Rclone tries very hard to maximise bandwidth usage. However this can cause problems which can be alleviated with the --bwlimit flag. 

That said 14 kBytes/s isn't exactly fast so it looks like there is something else going on. 

Where do you see the packet loss with mtr - is it at your router or further up the network?

Try scp some files to and from the pi to your laptop to see what sort of speed you get.

My guess would be something up with your local network. You could try rebooting your router and see if that helps. If it doesn't give the pi the same treatment. 

It would also be worth taking a look at dmesg to see if there is anything in there from the network interface. 

Hope something in the above is useful! 

Nick

**Comment by robins** [comment]
Thanks for a prompt response. I'll answer point-wise.
* MTR is run on the Pi to the router which is the first hop. Hope that clarifies.
* I didn't do a file transfer to my laptop (also on the same router and only 2 hops, but considering that the SSH typing suddenly becomes 'far' better once rclone is killed, I am not hoping much here either.
* Other devices (including my laptop) stream Youtube / regular browsing is pretty snappy, so I doubt much there. Though when the MTR was done there was nothing else running on the network.
* bwlimit: Let me try this and get back, however, considering that ntop / top don't show much I am not hoping much here either.
* restart Pi: Let me try this too, and it could actually be a one-off and if so, we can say that this is outside rclone (and close the ticket).
* Restart router: Low hopes again, but would check and revert. This is the Google OnHub and generally very good with connectivity / patches and never seen such issues in the past ~10 months of use.

**Comment by ncw** [comment]
> I didn't do a file transfer to my laptop (also on the same router and only 2 hops, but considering that the SSH typing suddenly becomes 'far' better once rclone is killed, I am not hoping much here either.

I meant try the bit file transfer without rclone running and see if you get the same effect.

**Comment by robins** [comment]
Well good news and bad news:

Bad News:
* I couldn't trace the issue. The Router & Pi weren't restarted and file transfer was speedy when rclone was down. The netstat -s (from earlier) and screenshot showing file-transfer when rclone is not running is attached.

Good News:
* The issue seems to have gone away, so am closing the ticket.

*My Guess*: Looks like Google Drive was throttling my downloads earlier in the morning and somehow rclone was able to jam my Pi. Since I can't replicate, I am closing this ticket. Will reopen in case I see this issue again.

![ss_winscp_filetransfer](https://cloud.githubusercontent.com/assets/1807/19597151/82c624ac-97de-11e6-84a8-e23aa364d5ff.png)

**Comment by ncw** [comment]
OK - glad it is working!
