### ISSUE TITLE
Rclone Mount dies when closing terminal

### ISSUE THREAD

**Issue by Trentflix** [ncw/rclone#808]
rclone mount encryptedremote: /path/to/mount --allow-other &
Ubuntu 14.04 x64
"v1.33-69-gd8d1102β"

If I close the terminal it was launched from even with the '&' at the end the mount dies with the error message "Transport endpoint is not connected". Is this expected? Any way around this?

**Comment by ncw** [comment]
This will fix that

    nohup rclone mount encryptedremote: /path/to/mount --allow-other </dev/null >/dev/null 2>&1 &

rclone mount doesn't daemonise itself at the moment.  It probably should, or at least have an option to do so.

In [this thread on the forum](https://forum.rclone.org/t/mounting-acd-with-decryption-for-reading/64/11) Buba_metola posted a recipe for using rclone mount with systemd.

You could also run it in a screen which is cheap and easy!
