### ISSUE TITLE
Sonarr + rclone + crypt + mount + ACD

### ISSUE THREAD

**Issue by suneetk92** [ncw/rclone#809]
Hi,
I have mounted a ACD using rclone crypt mount. And using Sonarr to manage my Seasons collection. (Sonarr is pointed to mounted location)
After my torrent client download the file(Local). Sonarr tries to rename the file and move the file to my mounted location but it fails everytime.
In the logs I get the below:
2016/10/21 15:12:16 TV Shows/Vikings/Season 04/Vikings - 04x01 - A Good Treason - SDTV - x264 AAC.mp4.partial~: WriteFileHandle.Flush error: Post https://content-na.drive.amazonaws.com/cdproxy/nodes?suppress=deduplication: http: ContentLength=540 with Body length 390787417
2016/10/21 15:12:16 TV Shows/Vikings/Season 04/Vikings - 04x01 - A Good Treason - SDTV - x264 AAC.mp4.partial~: WriteFileHandle.Flush error: Attempt to use closed file handle
2016/10/21 15:12:16 TV Shows/Vikings/Season 04/Vikings - 04x01 - A Good Treason - SDTV - x264 AAC.mp4.partial~: Dir.Rename error: no such file or directory
2016/10/21 15:12:19 TV Shows/Vikings/Season 04/Vikings - 04x01 - A Good Treason - SDTV - x264 AAC.mp4.partial~: Dir.Remove error: no such file or directory

Seems like Sonarr tries to transfer the file in parts and thus causing some issue. 
I tried above setup by removing the crypt. But its causing the same error. 

Please let me know if you need any other logs.

Thanks

**Comment by suneetk92** [comment]
Also When I sync my Plex Library. Pointed towards mounted location. I get below errors:
2016/10/21 15:44:32 Anime/Looney Tunes/Looney Tunes Vol 1/Looney.tunes.e39.1080p bluray x265 HEVC-Lewiswill[UTR].mkv: ReadFileHandle.Read error: file already closed
2016/10/21 15:44:43 Anime/The Legend Of Korra/Season 00/The Legend Of Korra S00E00 S2 Scene Bending Harmonic Convergence x265 HEVC-ByteShare[UTR].mkv: ReadFileHandle.Read error: file already closed

**Comment by ncw** [comment]
The problem I suspect is that ACD doesn't support renames: https://github.com/ncw/rclone/issues/122

I don't recommend you upload files with the mount - use rclone copy for that as it will be a lot more reliable.

**Comment by garypaduana** [comment]
@ncw, I've been able to rename files using acdcli.  Just throwing that out there in case you weren't aware of potentially an undocumented capability.

**Comment by ncw** [comment]
I'm going to close this as #835 covers the rename issue.
