### ISSUE TITLE
--allow-other does not work on Synology

### ISSUE THREAD

**Issue by christophfe** [ncw/rclone#811]
Hi,

could you please check why the --allow-other flag from beta versions (I tried several) can't work on a Synology ?

Error:
Modify window not supported
Fatal error: failed to mount FUSE fs: fusermount: signal: segmentation fault

Thanks for your support,
BR
Chris

When filing an issue, please include the following information if
possible as well as a description of the problem.  Make sure you test
with the [latest beta of rclone](http://rclone.org/downloads/).

> What is your rclone version (eg output from `rclone -V`)
> rclone v1.33-13-g7be4c3a-fuse-flagsβ
> 
> Which OS you are using and how many bits (eg Windows 7, 64 bit)
> Synology DSM Linux i386 / Xpenology
> 
> Which cloud storage system are you using? (eg Google Drive)
> Amazon Cloud Drive
> 
> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
>  ./rclone mount -v secret: /volume1/2TB1/ddd --allow-other
> 
> A log from the command with the `-v` flag (eg output from `rclone -v copy /tmp remote:tmp`)
> ProLiant> ./rclone mount -v secret: /volume1/2TB1/ddd --allow-other
> 2016/10/22 13:15:51 rclone: Version "v1.33-13-g7be4c3a-fuse-flagsβ" starting with parameters ["./rclone" "mount" "-v" "secret:" "/volume1/2TB1/ddd" "--allow-other"]
> 2016/10/22 13:15:53 Encrypted amazon drive root 'Test': Modify window not supported
> 2016/10/22 13:15:53 Fatal error: failed to mount FUSE fs: fusermount: signal: segmentation fault

**Comment by ncw** [comment]
You need this in your `/etc/fuse.conf` in order to use `--allow-other`

```
# Allow non-root users to specify the allow_other or allow_root mount options.
user_allow_other
```

Not sure that is the problem though - the segmentation fault looks strange.

Does it work without the `--allow-other`?

**Comment by christophfe** [comment]
Hi thanks for your reply - I have already this entry in my config of /etc/fuce.conf

What I can clearly observe is that I get this segmentation fault just on beta versions on the Synology where the additional flags are implemented. 

This (stable release) version: rclone-v1.33-linux-386.zip -> works perfectly on my Synology and I can mount acd and gdrive with crypt, whoever I would need the allow-other options as well.

Trying with several of the beta versions all end up with:

Encrypted amazon drive root 'Proliant': Modify window not supported
Fatal error: failed to mount FUSE fs: fusermount: signal: segmentation faul

**Comment by ncw** [comment]
This area of code has been moving quite quickly in recent days!  I've fixed two major bugs one of which may be yours.  Can you try the latest beta: http://beta.rclone.org/v1.33-85-g6846a1c/ and see if that fixes the segmentation fault?

**Comment by christophfe** [comment]
Hi thanks for the feedback & update - I tried the latest beta however the error keeps the same on the synology. I'll check with upcoming betas as well.

Thanks

**Comment by ncw** [comment]
This error `Fatal error: failed to mount FUSE fs: fusermount: signal: segmentation fault` means that rclone tried to do a FUSE mount and the kernel didn't understand and blew up.

I think there probably isn't anything rclone can do about this.

I don't know whether you can upgrade the kernel in the synology, or check out other people using FUSE mounts on it?

**Comment by ncw** [comment]
I'm going to close this as I haven't heard back from you so I hope it is all working now!
