### ISSUE TITLE
FUSE: Transfer speed with crypt while using seek and nginx

### ISSUE THREAD

**Issue by reticentnz** [ncw/rclone#815]
This issues seems to mostly be a repeat of #774 which appears to be fixed in some scenarios but not all. 

I have an encrypted mounted amazon cloud drive share which is available in nginx [as a directory listing] and have found the speed issue still exists here. File copies are between 100-400Kb/s where as copies from bash run at full speed.

Strangely, I can use other applications such as SCP and get full speed with this [where as I didn't pre v1.33-69-gd8d1102]. Other comments in that issue appear to suggest it has been fixed in other applications too. 

Is this something unique with the way nginx uses seek?

**Comment by ncw** [comment]
It could be nginx usage patterns I guess...

If you run the mount with `-v` and take a look at the output what do you see.  Maybe you could post some logs here?

I have sped up the seeking for crypt+fuse which you can try here: http://beta.rclone.org/v1.33-79-g77b975d/ which might help.

**Comment by reticentnz** [comment]
Hi @NCW, thanks for your response.

I have installed 1.33-79 and this actually breaks the nginx transfers completely.

2016/10/24 12:50:21 Linux/debian-8.6.0-amd64-CD-1.iso: File.Open
2016/10/24 12:50:21 Linux/debian-8.6.0-amd64-CD-1.iso: ReadFileHandle.Read size 131072 offset 0
2016/10/24 12:50:21 Linux/debian-8.6.0-amd64-CD-1.iso: ReadFileHandle.Read OK
2016/10/24 12:50:21 Linux/debian-8.6.0-amd64-CD-1.iso: ReadFileHandle.Read size 131072 offset 131072
2016/10/24 12:50:21 Linux/debian-8.6.0-amd64-CD-1.iso: ReadFileHandle.Read OK
2016/10/24 12:50:21 Linux/debian-8.6.0-amd64-CD-1.iso: ReadFileHandle.Read size 131072 offset 262144
2016/10/24 12:50:21 Linux/debian-8.6.0-amd64-CD-1.iso: ReadFileHandle.Read size 131072 offset 393216
2016/10/24 12:50:21 Linux/debian-8.6.0-amd64-CD-1.iso: ReadFileHandle.seek from 262144 to 393216 (io.Seeker)
2016/10/24 12:50:21 Linux/debian-8.6.0-amd64-CD-1.iso: ReadFileHandle.Read error: http: read on closed response body
2016/10/24 12:50:21 Linux/debian-8.6.0-amd64-CD-1.iso: ReadFileHandle.Read size 4096 offset 327680
2016/10/24 12:50:21 Linux/debian-8.6.0-amd64-CD-1.iso: ReadFileHandle.seek from 262144 to 327680 (io.Seeker)
2016/10/24 12:50:21 Linux/debian-8.6.0-amd64-CD-1.iso: ReadFileHandle.Read io.Seeker failed: http: read on closed response body
2016/10/24 12:50:22 Linux/debian-8.6.0-amd64-CD-1.iso: ReadFileHandle.Read error: http: read on closed response body
2016/10/24 12:50:22 Linux/debian-8.6.0-amd64-CD-1.iso: ReadFileHandle.Read size 4096 offset 262144
2016/10/24 12:50:22 Linux/debian-8.6.0-amd64-CD-1.iso: ReadFileHandle.seek from 393216 to 262144 (io.Seeker)
2016/10/24 12:50:22 Linux/debian-8.6.0-amd64-CD-1.iso: ReadFileHandle.Read io.Seeker failed: http: read on closed response body
2016/10/24 12:50:22 Linux/debian-8.6.0-amd64-CD-1.iso: File.Attr
2016/10/24 12:50:22 Linux/debian-8.6.0-amd64-CD-1.iso: ReadFileHandle.Read size 4096 offset 262144
2016/10/24 12:50:22 Linux/debian-8.6.0-amd64-CD-1.iso: ReadFileHandle.seek from 393216 to 262144 (io.Seeker)
2016/10/24 12:50:22 Linux/debian-8.6.0-amd64-CD-1.iso: ReadFileHandle.Read io.Seeker failed: http: read on closed response body
2016/10/24 12:50:22 Linux/debian-8.6.0-amd64-CD-1.iso: ReadFileHandle.Read size 4096 offset 262144
2016/10/24 12:50:22 Linux/debian-8.6.0-amd64-CD-1.iso: ReadFileHandle.seek from 393216 to 262144 (io.Seeker)
2016/10/24 12:50:22 Linux/debian-8.6.0-amd64-CD-1.iso: ReadFileHandle.Read io.Seeker failed: http: read on closed response body
2016/10/24 12:50:22 Linux/debian-8.6.0-amd64-CD-1.iso: ReadFileHandle.Flush
2016/10/24 12:50:22 Linux/debian-8.6.0-amd64-CD-1.iso: ReadFileHandle.Flush OK
2016/10/24 12:50:22 Linux/debian-8.6.0-amd64-CD-1.iso: ReadFileHandle.Flush
2016/10/24 12:50:22 Linux/debian-8.6.0-amd64-CD-1.iso: ReadFileHandle.Flush OK
2016/10/24 12:50:22 Linux/debian-8.6.0-amd64-CD-1.iso: ReadFileHandle.Release closing
2016/10/24 12:50:22 Linux/debian-8.6.0-amd64-CD-1.iso: ReadFileHandle.Release OK

**Comment by calisro** [comment]
Issue #802 seems related.

**Comment by calisro** [comment]
Yes, I have this issue as well. I posted a debug with headers in the #802 issue because it seems related.  The usage pattern on nginx is that it will attempt seek where-as cp or scp, mv, etc do not.

**Comment by reticentnz** [comment]
@calisro Are you using this through UnionFS as well? I saw your comment on #823 and it turns out that is my issues as well. I'd neglected to mention I am using Union FS in my setup too. If I point nginx at the native rclone mount rather than the unionfs view of it everything works great! (fast transfers too).

**Comment by calisro** [comment]
Ah! @reticentnz Good call.  I've changed my test to OUTSIDE my unionfs mounts and it sure does fly.  No errors.  The issue is somehow inter-tangled with unionfs specifically.  I placed the rclone fuse ON TOP of the unionfs thinking that it wouldn't have impact since FUSE is layering.  It should hit the rclone mount first but something else is going on apparently.  Good call here.  Would still be good to get this fixed!   Now I can test this out of KODI which is now also going to be a awesome test.

**Comment by reticentnz** [comment]
KODI supports SFTP as a remote video source by the way - the UnionFS works fine with that. I think my preference would still be to use HTTP/S with nginx but it's another workable solution for the time being.

**Comment by calisro** [comment]
What I did was create a BIND mount ontop of my unionfs mounts. :) and pointed nginx there.  And no issues. 
sudo mount --bind $UNIONED_MEDIA /var/www/base/Media

**Comment by reticentnz** [comment]
This is now resolved by the same fix for #823.

http://beta.rclone.org/v1.33-83-g8710741/
