### ISSUE TITLE
Seeking files (head, tail etc)

### ISSUE THREAD

**Issue by joshbaptiste** [ncw/rclone#819]
I have a use case where I want to deliberately copy video files from Amazon cloud and seek to end downloading a portion of the beginning and a portion to the end, (zero byte padding in the middle) creating local Linux sparse files. 

```
Amazon:     1G [**********]
My Drive: 100M [**.......*]
```

I know this can be done with the beta via Fuse/seek() but I use a container based VPS provider that that doesn't support loading the Fuse kernel module at the moment. Is it possible for cat/copy to support such a feature to have a specified byte range to download?

**Comment by ncw** [comment]
Ultimatel the cloud storage systems all support some variant of [http range](https://tools.ietf.org/html/rfc7233).  They don't all support all the features though if I remember rightly.  A sort of minimum subset would be to return a section of a file.

I could see this translating into flags for rclone

    --head N      - fetch the first N bytes of the file
    --tail N      - fetch the last N bytes of the file
    --range N-N   - fetch from bytes N to M in the file

Which would all be mutually exclusive.

I think all the cloud storage systems could support that.

That isn't exactly what you asked for - is it useful enough?

**Comment by joshbaptiste** [comment]
ah  yes indeed,
I could fork and write it myself as i'm wrapping my head around Go, just
not sure where to start in the codebase

**Comment by ncw** [comment]
The easiest way to write this would be to make the flags just apply to the `rclone cat` command.

Here is a quick runthrough of what you would need to do

You would put the flag handling in [cat.go](https://github.com/ncw/rclone/blob/master/cmd/cat/cat.go) see [mount.go](https://github.com/ncw/rclone/blob/master/cmd/mount/mount.go) as to how to add flags to a specific command.

You'd then decode the flags into a [RangeOption](https://github.com/ncw/rclone/blob/master/fs/options.go#L24) which you would pass to `fs.Cat` as an extra parameter, and you'd change the implementation of `fs.Cat` to take that extra parameter and pass it to the [`o.Open()` call](https://github.com/ncw/rclone/blob/master/fs/operations.go#L1053)

You'd then write some docs and a test in `fs/operations_test.go` for the extra parameter for Cat.

**Comment by naeloob** [comment]
I'm interested to have this enhancement.
Just in case you take in count how "popular" is an enhancement to make the step.

Thanks in Advanced

**Comment by ncw** [comment]
tail would be particularly useful for detecting corruptions introduced by #902 in #999 so I'm going to try to get `rclone head` and `rclone tail` into 1.36.

**Comment by naeloob** [comment]
This will work on Crypt remote too? I mean, it will retuns the unencrypted N bytes of a remote crypt?
If it's not too dificult, can we get Range too? 
Thank you in Advance.

Regards,

**Comment by ncw** [comment]
Yes it would work on crypt too. I don't think range is too hard either.

**Comment by naeloob** [comment]
Great!!
Thank you for the support.

**Comment by ncw** [comment]
I've implemented this in the following beta

http://beta.rclone.org/v1.35-76-gd091d4a/ (uploaded in 15-30 mins)

It should work for all remote types.

```
You can use it like this to output a single file

    rclone cat remote:path/to/file

Or like this to output any file in dir or subdirectories.

    rclone cat remote:path/to/dir

Or like this to output any .txt files in dir or subdirectories.

    rclone --include "*.txt" cat remote:path/to/dir

Use the --head flag to print characters only at the start, --tail for
the end and --offset and --count to print a section in the middle.
Note that if offset is negative it will count from the end, so
--offset -1 --count 1 is equivalent to --tail 1.

Usage:
  rclone cat remote:path [flags]

Flags:
      --count int    Only print N characters. (default -1)
      --discard      Discard the output instead of printing.
      --head int     Only print the first N characters.
      --offset int   Start printing at offset N (or from end if -ve).
      --tail int     Only print the last N characters.

```

**Comment by yanniand** [comment]
Hello, thanks a lot for the hints. 
Is there a way to "tail -f" to continuously tail a file that is being appended? I use Azure blob storage accounts for storing audit logs. It creates a blob container per item, under which it stored the blob files. The log files get created every hour. The log entries get appended every few seconds.

**Comment by xSeekTruthx** [comment]
> Hello, thanks a lot for the hints. Is there a way to "tail -f" to continuously tail a file that is being appended? I use Azure blob storage accounts for storing audit logs. It creates a blob container per item, under which it stored the blob files. The log files get created every hour. The log entries get appended every few seconds.

I second this. Currently every time I run, the only way it appears in terminal as it updates each file seems to be to remove the --log-file, and only use --progress and --verbose... however I would like it to be logged and show the progress as well.

**Comment by xSeekTruthx** [comment]
I second this... would like for verbose progress to show on screen for each file, and stay there while also being appended to the log file. Tried using tail to no avail.
