### ISSUE TITLE
feature Request 

### ISSUE THREAD

**Issue by f3rr311** [ncw/rclone#822]
Please delete if wrong place as I don't see any feature requests section,

It would be amazing to see if the program can copy files that have not been accessed in so many days or what not

**Comment by ncw** [comment]
You can use the `--min-age` and `--max-age` flags from [the filtering](http://rclone.org/filtering/) commands.  These filter on modified date.

Is that what you want, or do you want to filter on accessed date?

**Comment by ncw** [comment]
I'm assuming that was what you wanted - if not, please reopen!
