### ISSUE TITLE
b2: token expires after 24 hours

### ISSUE THREAD

**Issue by marrie** [ncw/rclone#825]
Using latest beta on mac os 64 bit. I get the error that the token has expired.  I think Iv'e filed this before but not sure. Here is my log file if you need it.

[log file in zip format](https://github.com/ncw/rclone/files/555026/outputarchives.logac.zip)

**Comment by ncw** [comment]
I see what has happened.  You started your upload at `2016/10/25 20:49:40` and got the first `401 expired_auth_token` message at `2016/10/26 20:50:30` so almost exactly 24 hours later.

According to [the b2 api docs](https://www.backblaze.com/b2/docs/b2_authorize_account.html)

> An authorization token to use with all calls, other than b2_authorize_account, that need an Authorization header. This authorization token is valid for at most 24 hours.

So rclone either needs to get a new authorization token when it gets an  `401 expired_auth_token` error, or it needs to fetch one at regular intervals.

**Comment by marrie** [comment]
Makes sense. Ok, now what? I guess I restart the script every few hours? A bit counter intuitive if I'm running this on a server. I guess that can be a workaround for now. Thoughts? It's no big deal at least a work around can be done.

**Comment by ncw** [comment]
restart the script would be a work-around yes.

I'll fix soon and post a beta for you to try here.

**Comment by marrie** [comment]
No worries. Is this documented anywhere in the read me file so others don't have this issue? I don't recall seeing it, but that would be a suggestion until something can be worked out. I don't mind restarting the script. I have to anyway when I stream and or teach. Take your time on this one.

**Comment by ncw** [comment]
I've attempted to fix this in this beta: http://beta.rclone.org/v1.34-04-g4105da2/ (will be uploaded in 15-30 mins)

Can you have a go with it and see if it fixes this issue for you please?

Thanks

Nick

**Comment by jdeluyck** [comment]
Unfortunately, the latest beta doesn't fix the problem:

`Upload started:
2016/11/25` 23:27:04
Transferred:   55.314 MBytes (924.719 kBytes/s)
Errors:                 0
Checks:              2164
Transferred:            5
Elapsed time:      1m1.2s
Transferring:
 *                                   index.95049: 69% done. avg:  783.4, cur:  664.8 kByte/s. ETA: 13s
 *                                  data/8/80883: 30% done. avg:  512.5, cur:  406.0 kByte/s. ETA: 16s
 *                                  data/8/89253: 18% done. avg:  671.7, cur:  599.1 kByte/s. ETA: 11s
 *                                  data/8/89384: 66% done. avg:  447.6, cur:  433.0 kByte/s. ETA: 5s`

Upload going strong, until these messages start popping up

`2016/11/26 23:32:55 data/7/75098: Failed to copy: Authorization token has expired (401 expired_auth_token)
2016/11/26 23:33:04
Transferred:   172.717 GBytes (2.037 MBytes/s)
Errors:                 9
Checks:             35182
Transferred:        26049
Elapsed time:   24h7m1.2s
Transferring:
 *                                  data/7/71914:  0% done. avg:    0.0, cur:    0.0 kByte/s. ETA: -`

The messages keep coming, and it seems to be uploading *something* still, but at a snail's pace.
From that time until now:
`2016/11/27 10:44:04
Transferred:   172.778 GBytes (1.392 MBytes/s)
Errors:               136
Checks:             35307
Transferred:        26049
Elapsed time:  35h18m1.2s
Transferring:
 *                                  data/7/73508:  0% done. avg:    0.0, cur:    0.0 kByte/s. ETA: -
 * data/7/71388
 * data/8/86717
 * data/8/89931`

Still getting those expiry messages frequently in the output.

**Comment by understand-ca** [comment]
I've encountered this error as well with v1.35.

I'm not sure if it makes a difference, but in my case I'm doing a sync from local > crypt > b2

**Comment by ncw** [comment]
OK, thanks for the report.  Will try another fix attempt and post it here in due course!

**Comment by ncw** [comment]
I managed to replicate this with a test flag `--b2-test-mode expire_some_account_authorization_tokens` and I've fixed the problem.

Please find it in this beta

http://beta.rclone.org/v1.35-36-ga4bf22e/ (uploaded in 15-30 mins)

Let me know how you get on.

Thanks

Nick

**Comment by bshiner** [comment]
> I've encountered this error as well with v1.35.
> I'm not sure if it makes a difference, but in my case I'm doing a sync from local > crypt > b2

Sorry, previous comment was using the wrong GitHub account.

Thanks for the quick response. I'll start another test going shortly and let you know.

**Comment by bshiner** [comment]
My sync has been running for the last 29 hours with no errors so far.

**Comment by ncw** [comment]
Good news! Thanks for testing.

**Comment by marrie** [comment]
I'll find out tomorrow if the token will expire as well. I've had this upload going for about 7 hours now,  and it will take 17 more hours to upload 32 gigs. So we'll see if it expires by about 6:30 pm pst as that will be about 25 hours after I started the process.

Thanks for looking into this.

**Comment by ncw** [comment]
@marrie Thanks for testing too. Cross fingers!

**Comment by bshiner** [comment]
Sync running for the last 125 hours.

**Comment by ncw** [comment]
@bshiner wrote
> Sync running for the last 125 hours.

Excellent!

I'll close this issue now - thanks everyone for testing.  It will be in the official 1.36 release.
