### ISSUE TITLE
Feature Request: use different IP address for upload/download/mount for ACD

### ISSUE THREAD

**Issue by ladude626** [ncw/rclone#826]
I notice that when I'm uploading, especially with high number of concurrent upload to ACD, my mount directory becomes unresponsive. I think it's because when I'm uploading at 20-25MB/s, it's saturating the bandwidth for ACD's server.

I got around this issue by using 2 different users, one for upload, and another one for mount (user "root" for upload and user "plex" for mount). I was able creating a different "/etc/hosts" file for root that points content-na.drive.amazonaws.com at a specific IP address. Running dns query on "content-na.drive.amazonaws.com", it will produce multiple IP address (A records). You can pick of any of the available IPs. I then used this tool https://github.com/bAndie91/libnss_homehosts  to allow each user to have their own hosts file. For me I create a hosts file for root that pointed content-na.drive.amazonaws.com to a specific IP:

```
52.7.68.18 content-na.drive.amazonaws.com
```

I would be a good feature to have this implemented direct in rclone. Maybe for each instant of rclone that's used for upload, download, or mount, a random IP address can be selected from the A records. This will potentially increase speed throughout.

**Comment by ncw** [comment]
Interesting idea - not sure how I'd implement it.

It is the kind of thing I might expect the go name resolver to do for me...

A [little experiment](https://play.golang.org/p/j3XWDSzO6G) indicates that it returns IPs in random order which is good...

```
$ ./LookupIP content-na.drive.amazonaws.com
"content-na.drive.amazonaws.com": 54.88.149.237
"content-na.drive.amazonaws.com": 54.85.147.124
"content-na.drive.amazonaws.com": 54.87.96.13
"content-na.drive.amazonaws.com": 54.84.119.41
"content-na.drive.amazonaws.com": 54.210.228.88
"content-na.drive.amazonaws.com": 54.210.230.197
"content-na.drive.amazonaws.com": 54.210.230.84
"content-na.drive.amazonaws.com": 54.84.77.98
$ ./LookupIP content-na.drive.amazonaws.com
"content-na.drive.amazonaws.com": 54.85.147.124
"content-na.drive.amazonaws.com": 54.87.96.13
"content-na.drive.amazonaws.com": 54.84.119.41
"content-na.drive.amazonaws.com": 54.210.228.88
"content-na.drive.amazonaws.com": 54.210.230.197
"content-na.drive.amazonaws.com": 54.210.230.84
"content-na.drive.amazonaws.com": 54.84.77.98
"content-na.drive.amazonaws.com": 54.88.149.237
$ ./LookupIP content-na.drive.amazonaws.com
"content-na.drive.amazonaws.com": 54.87.96.13
"content-na.drive.amazonaws.com": 54.84.119.41
"content-na.drive.amazonaws.com": 54.210.228.88
"content-na.drive.amazonaws.com": 54.210.230.197
"content-na.drive.amazonaws.com": 54.210.230.84
"content-na.drive.amazonaws.com": 54.84.77.98
"content-na.drive.amazonaws.com": 54.88.149.237
"content-na.drive.amazonaws.com": 54.85.147.124
```

Another [little test](https://play.golang.org/p/91imBybSI7) indicates that Dial chooses a different IP each time

```
$ ./dial content-na.drive.amazonaws.com:443
"content-na.drive.amazonaws.com:443": 52.73.248.252:443: <nil>
"content-na.drive.amazonaws.com:443": 52.72.145.30:443: <nil>
"content-na.drive.amazonaws.com:443": 52.73.155.106:443: <nil>
"content-na.drive.amazonaws.com:443": 52.72.168.2:443: <nil>
```

So I would kind of expect rclone to work like that already.

It might be worth trying this before running rclone.

```
export GODEBUG=netdns=go    # force pure Go resolver
```

Also check with `netstat -tnp` to see which addresses rclone does connect to.

When I try it

```
$ netstat -tnp | grep rclone
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
tcp        0      0 192.168.1.149:47218     54.76.70.53:443         ESTABLISHED 8824/rclone     
tcp        0      0 192.168.1.149:53986     54.239.34.70:443        ESTABLISHED 8824/rclone     
tcp        0      0 192.168.1.149:56176     54.72.49.85:443         ESTABLISHED 8824/rclone     
tcp        0      0 192.168.1.149:53964     54.239.34.70:443        ESTABLISHED 8824/rclone     
tcp        0      0 192.168.1.149:56172     54.72.49.85:443         ESTABLISHED 8824/rclone     
tcp        0      0 192.168.1.149:37940     205.251.243.243:443     ESTABLISHED 8824/rclone     
tcp        0      0 192.168.1.149:53992     54.239.34.70:443        ESTABLISHED 8824/rclone     
tcp        0      0 192.168.1.149:38328     54.77.75.54:443         ESTABLISHED 8824/rclone     
tcp        0    709 192.168.1.149:38332     54.77.75.54:443         ESTABLISHED 8824/rclone     
tcp        0      0 192.168.1.149:53996     54.239.34.70:443        ESTABLISHED 8824/rclone     
tcp        0      0 192.168.1.149:54000     54.239.34.70:443        ESTABLISHED 8824/rclone     
tcp        0      0 192.168.1.149:47216     54.76.70.53:443         ESTABLISHED 8824/rclone     
tcp        0    709 192.168.1.149:38334     54.77.75.54:443         ESTABLISHED 8824/rclone     
tcp        0    709 192.168.1.149:56174     54.72.49.85:443         ESTABLISHED 8824/rclone     
tcp        0      0 192.168.1.149:38326     54.77.75.54:443         ESTABLISHED 8824/rclone     
tcp        0      0 192.168.1.149:53988     54.239.34.70:443        ESTABLISHED 8824/rclone     
tcp        0      0 192.168.1.149:53990     54.239.34.70:443        ESTABLISHED 8824/rclone     
tcp        0      0 192.168.1.149:56178     54.72.49.85:443         ESTABLISHED 8824/rclone     
tcp        0      0 192.168.1.149:56180     54.72.49.85:443         ESTABLISHED 8824/rclone     
tcp        0      0 192.168.1.149:38330     54.77.75.54:443         ESTABLISHED 8824/rclone     
tcp        0      0 192.168.1.149:53998     54.239.34.70:443        ESTABLISHED 8824/rclone     
tcp        0      0 192.168.1.149:54002     54.239.34.70:443        ESTABLISHED 8824/rclone     
tcp        0      0 192.168.1.149:53994     54.239.34.70:443        ESTABLISHED 8824/rclone     
```

I see that rclone does indeed connect to lots of different IPs

**Comment by jkaberg** [comment]
I got a 1gbit line here, and I usualy do uploads around 8-900mbit ( against EU-West, Germany)

You sure you're not saturating your ISP @ladude626 ?

**Comment by ladude626** [comment]
I'm on a 1000mbps connection, also in Germany but using US ACD server. Fastest I can get is about 30Mbps. 

So it looks like rclone is already using random IPs for each of it's instances?

**Comment by jkaberg** [comment]
I'm on a 1000mbps connection, also in Germany but **using US ACD server**.

Thats your problem right there. Change to EU based servers (located in Germany) and you'll be a lot better of. 

I get thoes speed's and I'm located in Norway.

**Comment by ladude626** [comment]
I have a US ACD account though. I'm not sure I can use a US account with EU based server.

**Comment by ncw** [comment]
I think rclone is already doing random IPs with `export GODEBUG=netdns=go` so I'm going to close this as it would be very difficult for me to change the built in behaviour.
