### ISSUE TITLE
checksum not working on crypt

### ISSUE THREAD

**Issue by calisro** [ncw/rclone#829]
I'm using the latest beta on Linux against ACD.  I have a command line that looks like this:
 rclone \
  --bwlimit=10000 \
  --config="$RCLONECONF" \
  --acd-upload-wait-time=10s \
  --config="$RCLONECONF" \
  --checksum \
 copy $OPT -v "/data/Media1" "acd-crypt:/" 

I set up a test case where I changed a letter in an xml file so that it retains the same size and ran the copy.  It did not update that file.  It looks like it is still doing the comparisons based on size rather than checksum.  

Is checksum not supported on crypt?  Or am I just doing something dumb and need more coffee?

**Comment by ncw** [comment]
Checksum isn't supported on crypt. I think I updated the docs with that in recently (so it isn't on the website yet). 

It will be when I do the high security name encryption mode.

**Comment by calisro** [comment]
Oh man. :|  And since acd doesn't support mod times, only size would be used.  I guess I can add a space to my xml files before syncing them with a find command.

**Comment by calisro** [comment]
I guess I could use rsync to do a chksum sync for only the files I care about (xml mostly).

**Comment by calisro** [comment]
Anyone finding this and need a work around.  Here is mine using bash.

create a rclone mount of the crypt acd drive.  we'll call it acd-crypt here and we'll mount in on /data/Media2

```
TMPFILE=/tmp/rclonefilelist.txt

rsync  --inplace -rlvxi --checksum -n --out-format="%n"  /data/Media1/ /data/Media2/ | egrep -v "/$|^sent|^total|^sending" | tee $TMPFILE

rclone --include-from $TMPFILE  copy  -v "/data/Media1/" "acd-crypt:/"  --ignore-times

rm -f $TMPFILE
```
