### ISSUE TITLE
Command to remove empty directories

### ISSUE THREAD

**Issue by ncw** [ncw/rclone#831]
Make a new rclone command which will remove empty directories - based on http://pub.rclone.org/rclone-delete-empty-dirs.py3

As it stands this isn't very efficient as it makes a new remote for each directory deleting.

Examine whether to change the Rmdir/Mkdir calls to take a directory parameter.

Factored from #100

**Comment by ncw** [comment]
Beta here: http://beta.rclone.org/v1.34-25-gf3365dd/

**Comment by Wowfunhappy** [comment]
Beta is working great here! macOS X 64bit.
