### ISSUE TITLE
rclone slow copy from google storage

### ISSUE THREAD

**Issue by grinsted** [ncw/rclone#833]
I'd like to use rclone to copy public datasets from the google storage cloud. My problem is that it is really slow in comparison to `gsutil copy`. Specifically I want to work with this dataset:
https://cloud.google.com/storage/docs/public-datasets/sentinel-2

And i am testing first with this 50 mb file: gs://gcp-public-data-sentinel-2/index.csv.gz

So I configure a new "gs" google storage. I leave everything to its defaults, but enter a verification code (q: is that really necessary when i only want to download.)

I then execute:
`./rclone --verbose copy gs:gcp-public-data-sentinel-2/index.csv.gz .`

I used v1.33 for osx64

the verbose output is a huge list of million files scrolling past...
```
...
2016/10/29 10:45:55 tiles/01/C/DV/S2A_MSIL1C_20160304T203515_N0201_R085_T01CDV_20160309T000729.SAFE/GRANULE/S2A_OPER_MSI_L1C_TL_SGS__20160305T043523_A003657_T01CDV_N02.01/QI_DATA/S2A_OPER_MSK_DEFECT_SGS__20160305T043523_A003657_T01CDV_B10_MSIL1C.gml: Excluded from sync (and deletion)
2016/10/29 10:45:55 tiles/01/C/DV/S2A_MSIL1C_20160304T203515_N0201_R085_T01CDV_20160309T000729.SAFE/GRANULE/S2A_OPER_MSI_L1C_TL_SGS__20160305T043523_A003657_T01CDV_N02.01/QI_DATA/S2A_OPER_MSK_DEFECT_SGS__20160305T043523_A003657_T01CDV_B11_MSIL1C.gml: Excluded from sync (and deletion)
2016/10/29 10:45:55 tiles/01/C/DV/S2A_MSIL1C_20160304T203515_N0201_R085_T01CDV_20160309T000729.SAFE/GRANULE/S2A_OPER_MSI_L1C_TL_SGS__20160305T043523_A003657_T01CDV_N02.01/QI_DATA/S2A_OPER_MSK_DEFECT_SGS__20160305T043523_A003657_T01CDV_B12_MSIL1C.gml: Excluded from sync (and deletion)
2016/10/29 10:45:55 tiles/01/C/DV/S2A_MSIL1C_20160304T203515_N0201_R085_T01CDV_20160309T000729.SAFE/GRANULE/S2A_OPER_MSI_L1C_TL_SGS__20160305T043523_A003657_T01CDV_N02.01/QI_DATA/S2A_OPER_MSK_DEFECT_SGS__20160305T043523_A003657_T01CDV_B8A_MSIL1C.gml: Excluded from sync (and deletion)
...

```

**Comment by ncw** [comment]
Try the latest beta - I've improved this considerably!

http://beta.rclone.org/v1.33-85-g6846a1c/

**Comment by grinsted** [comment]
Fixed for me. thanks
