### ISSUE TITLE
Issues with reading from mount

### ISSUE THREAD

**Issue by yrh1** [ncw/rclone#836]
Hello
I am not very good with linux, but good at following instructions.
rclone with google drive crypt was working fine till I started playing around with unionfuse and ended up upgrading the beta for rclone as well. Now mount will not work. 
Using this to mount
rclone mount egoogle: /home/user/Google/ --allow-other --dir-cache-time=2m &

Tried removing unionfuse and rclone and starting over with rclone again, still unable to copy files from mount. Can see directory structure fine.
Using --allow-other and already edited fuse.conf

> What is your rclone version (eg output from `rclone -V`)
rclone v1.33-85-g6846a1cβ

> Which OS you are using and how many bits (eg Windows 7, 64 bit)
Ubuntu 16.04 64bit

> Which cloud storage system are you using? (eg Google Drive)

Google Drive

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

 Trying to copy from mounted folder to local folder
cp /home/user/googlemount/file.mkv /home/user/test/
or 
rclone copy /home/user/googlemount/file.mkv /home/user/

> A log from the command with the `-v` flag (eg output from `rclone -v copy /tmp remote:tmp`)

2016/10/30 19:28:40 rclone: Version "v1.33-85-g6846a1cβ" starting with parameter 
s ["rclone" "-v" "copy" "/home/user/Google/file.mkv" "/home/user/Test/"]
2016/10/30 19:28:40 Local file system at /home/user/Test: Modify window is 1ns
2016/10/30 19:28:40 Local file system at /home/user/Test: Waiting for checks to finish
2016/10/30 19:28:40 Local file system at /home/user/Test: Waiting for transfers to finish
2016/10/30 19:28:41 file.mkv: Failed to copy: failed to open source object: open /home/user/Goo      gle/file.mkv: input/output error
2016/10/30 19:28:41 Attempt 1/3 failed with 1 errors and: failed to open source  object: open /home/user/Google/file.mkv: input/output error
2016/10/30 19:28:41 Local file system at /home/user/Test: Waiting for checks to finish
2016/10/30 19:28:41 Local file system at /home/user/Test: Waiting for transfers to finish
2016/10/30 19:28:41 file.mkv: Failed to copy: failed to open source object: open /home/user/Google/file.mkv: input/output error
2016/10/30 19:28:41 Attempt 2/3 failed with 1 errors and: failed to open source object: open /home/user/Google/file.mkv: input/output error
2016/10/30 19:28:41 Local file system at /home/user/Test: Waiting for checks to finish
2016/10/30 19:28:41 Local file system at /home/user/Test: Waiting for transfers to finish
2016/10/30 19:28:41 file.mkv: Failed to copy: failed to open source object: open /home/user/Google/file.mkv: input/output error
2016/10/30 19:28:41 Attempt 3/3 failed with 1 errors and: failed to open source object: open /home/user/Google/file.mkv: input/output error
2016/10/30 19:28:41 Failed to copy: failed to open source object: open /home/user/Google/file.mkv: input/output error

**Comment by ncw** [comment]
Can you post the logs from the mount command `rclone mount egoogle: /home/user/Google/ --allow-other --dir-cache-time=2m &` - that should show what is going on.

**Comment by yrh1** [comment]
Searched around a bit more and then finally decided to go to drive.google.com using web browser. Was having issues downloading files from there as well. So, it seemed like a google issue and not rclone one.
Thanks
