### ISSUE TITLE
rclone is missing files on copy.

### ISSUE THREAD

**Issue by jxer** [ncw/rclone#837]
When filing an issue, please include the following information if possible as well as a description of the problem.  Make sure you test with the [latest beta of rclone](http://rclone.org/downloads/).

If you've just got a question then please use the [rclone forum](https://forum.rclone.org/) instead of filing an issue.

> What is your rclone version (eg output from `rclone -V`)
rclone: Version "v1.33" 
> Which OS you are using and how many bits (eg Windows 7, 64 bit)
debiian 8.3
> Which cloud storage system are you using? (eg Google Drive)
acd
> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

> A log from the command with the `-v` flag (eg output from `rclone -v copy /tmp remote:tmp`)
https://gyazo.com/323684a89050ef6cd22af05a77d25920

command log would be insane im trying to sync a 1.2 tb folder

**Comment by jxer** [comment]
now i am even finding on sync, deletes are not even completing across. am i the only one seeing this?

**Comment by ncw** [comment]
rclone doesn't delete empty directories at the moment - see #100 

Note that rclone doesn't do any deletions in the presence of errors.

**Comment by jxer** [comment]
ok what about it missing the files on copy? look at the screen shot above, doing a copy 6 times does nothing the files never get transferred, i have to rename them simply adding a space sometimes fixes it. out of 101 folders it only copied 96....

**Comment by calisro** [comment]
You didn't include the command you are running?  Are you using a mount?  Are you using crypt over acd?    Its also hard to tell without a log.

**Comment by jxer** [comment]
is there a way to get this thing to print a error when there is a problem? using -v is pointless when there is 5k worth of files im trying to copy

and im not sure what you need command wise, its a basic copy command with a bandwidth limiter and no traverse and now im using checksum as well, even though it takes significantly longer.

i am using a ACD mount, not rclone mount, no crypt from rclone, but as stated above i am using encfs over the acd mount, everything rclone is copying is encfs encrypted data.

**Comment by calisro** [comment]
Using '-v' is the way to get a verbose output and the output is intermingled with regular output.  You can redirect it to a file, gzip it, and then upload it.

For the command, in the future just paste the command you are using otherwise no one knows if you are using a mount or just a copy or a sync, or a move.  We also don't know if you are using a crypted remote or not but you've answered these now.  For example, crypt doesn't support checksum.  So it was good to know that crypt isn't being used.

Since you are combining the ACDCLI mount with rclone copy, have you verified that the data was correct on the ACDCLI mount when you issued the command for rclone?  I know acdcli mount keeps a cache of file nodes in a database and if those files changed outside of acdcli they may be out of sync with that database.  Also just because acdcli mount reports a file is there, are you sure that it actually exists (wasn't deleted) on the remote encfs yet still being reported from acdcli mount because of the caching?  

Just some things to check.

**Comment by jxer** [comment]
i am not using the acd mount WITH rclone, sorry maybe that wasn't clear. rclone is using a local enfcs directory and a direct upload to ACD. acd mount is only used to view the decrypted form and has no direct interaction with rclone

again look at the screenshot above, it completely missed the rar file, also simply changing a filename allowed one directory/file to be copied

rclone really needs to simply output an error when it hits one.

i will try to recreate this, it appears that checksum may actually be fixing the issue, but that changes the upload from 5-10 hours to 33 hours, and puts a beating io wise on the drives, but it is what it is

**Comment by calisro** [comment]
If you can narrow it down to one set of file(s) from the encfs reverse view, then it may be helpful to produce a log to look at.   

Based on what you said above (changing file name, using chksum fixes it) I wonder if the encfs reverse that you created is compatible with case insensitive storage.  Although unlikely, you can have two encfs files hash to the same encrypted name within the same directory.  That would cause you problems with loading those encfs files to ACD (case insensitive remote).  

> "To store EncFS on a file system that is case insensitive for lookup, (VFAT,
> NTFS, HFS+, etc), create it using expert mode and select B32Block or B32Stream
> as the filename cipher to use."

Also, if you knew, for example, that some rar file was missed, you could use encfsctl utility to show you what the encrypted name of that file would be so you can find it in the encfs reverse path to do some analysis.

> 
> https://www.ict.griffith.edu.au/anthony/info/crypto/encfs.hints
> 
>   encfsctl encode encfs_dir  filename
>       encrypts the given filename to the encrypted file path
>       (result includes the includes encfs_dir prefix)

Narrowing down / recreating the issue would be helpful.

**Comment by jxer** [comment]
This can be closed, after extensive debugging the issue is NOT with rclone, it has to do with the acdcli mount, even when dropping the acd mount and issue a sync, randomly files would not appear after a remount.

after troubleshooting through encryption (NOT FUN), it was found that rclone saw the file.

after multiple attempts to resync and not finding the random file missing. another computer was setup with acd mount and with a fresh db etc, shockingly all the files showed up on the acd mount,

sync again on the original computer, still can't see it, 

delete everything in acd cli, minus the oauth_data file and resync and presto, everything shows up!

yay another friggin bug. lucky not a rclone issue. i will be closing this.

@yadayada might want to take a look at this...
