### ISSUE TITLE
[Feature Request] Enable service account authentication for Google Drive

### ISSUE THREAD

**Issue by rasteiner** [ncw/rclone#839]
Service accounts should allow us to authenticate without user interaction, simplifying configuration for unattended or automated systems. 

This issue refers to [this discussion on the forum](https://forum.rclone.org/t/google-drive-with-service-account/121). 

I guess it could work in a similar way like this PR: https://github.com/ncw/rclone/pull/444

I would help with a PR, but I have no idea of `go lang`.

**Comment by ncw** [comment]
Thanks for writing this up.

**Comment by m6a-UdS** [comment]
+1 for this feature :-)

**Comment by aschmied** [comment]
+1 would love to have this

**Comment by ncw** [comment]
@mwitkow you did the work in #444 - would the same approach work here?  If so fancy adapting it?

**Comment by mwitkow** [comment]
I'm not sure whether you can use an IAM Service Account for Google Drive Oauth scope `https://www.googleapis.com/auth/drive`.

If it does, it should be as simple as replacing:
https://github.com/ncw/rclone/blob/master/drive/drive.go#L95
with something to
https://github.com/ncw/rclone/pull/444/files#diff-2016219251e33b0ab7f9e1f99585a44cR207

Unfortunately, I'm pretty short on time at the moment and don't have the time to experiment. Happy to help in comments though :)

**Comment by DimaSamodurov** [comment]
Note that several people may share files with the SA and in that case files will come from different Drives, different folders. Work with filtering and path handling may differ.

**Comment by ncw** [comment]
This has been implemented now - please find it in this beta

https://beta.rclone.org/v1.38-198-g56cfb810/

**Comment by dav1303** [comment]
How can I test it ?

**Comment by linckez** [comment]
+1 how to test it?

**Comment by ncw** [comment]
@dav1303 @linckez take a look in [the docs](https://play.golang.org/p/r4EMEi9t22) (which aren't on the website yet) and try with [the latest beta](https://beta.rclone.org).

**Comment by mattkaye** [comment]
@ncw
Your link to the docs is a golang snippet. I'm looking for the documentation on how to use this new feature, such as the documentation on the rclone site. Thanks!

**Comment by ncw** [comment]
@mattkaye here are [the service account docs](https://rclone.org/drive/#service-account-support).  If you are thinking about using a service account then you may want to check out #1491 also

**Comment by mattkaye** [comment]
@ncw 
Thanks for getting back to me so quickly. I already have a service account set up using rclone. I can only add to the service account drive, which is not what I want to do. From what I understand, I need to impersonate the user so I can add to their drive. I don't see a way of doing this vai rclone. 

The SDK would be much to slow for this. I have 5TB of data to upload. Maybe what I need to do is use a service account and set up a domain wide authority in the developer console. I'm not sure which direction to go here.

**Comment by dav1303** [comment]
Hi

Yes the domain wide délégation is the first step but you need also to
authorize the service account with the Drive scope on the admin console.

This steps are classical but the big challenge is to integrate that in
rclone to do the impersonation.

My last tests with the service account in a single account works but i
cannot see thé files on thé Drive UI.

I don't know if that issue is solved now ?

Regards

**Comment by mattkaye** [comment]
@dav1303 
Exactly, that's where I am right now. Service account created and working using rclone. I can only see the service account drive through the command line as expected. No idea how rclone can impersonate and push to a real users drive. I need that to happen so I can push 5TB of data to an account with unlimited drive space. Service accounts have only 15GB. I've been in contact with their customer support to verify this.

So it sounds like this is not yet possible with rclone? I guess the only other option is write some PHP code to do this using the SDK to do the impersonation, but that's not nearly as quick and robust as rclone. I can see that being very error prone : /

**Comment by ddurdle** [comment]
@mattkaye, It is doable.  I have scripts I developed that work at doing precisely this.

99% of the work is done by simply support service drives to see the contents stored with the service account.  There is only one small change needed.  With the token authentication where rclone passes in the iss, it also just needs to pass in a prn value.  This prn value will be the user account the service wants to impersonate.   This would be the simplest solution to implement -- allow the user to specify the username they want to impersonate and include a field to retrieve this value.  Then that connection can be saved as a service account to access that user's file.  If you want to access a different user, create a new connection with a different prn value.

Each token generated will be tied to accessing files owned by the provided prn value.

**Comment by mattkaye** [comment]
@ddurdle 
Do you have this code handy? Would you mind sharing a copy with me?

**Comment by ddurdle** [comment]
@mattkaye 
I had written a bunch of uploading scripts a few years ago.  I needed to revisit them yesterday to use a service account to automate some things on a domain I have.  I recalled I implemented this service account support back then.

I would actually prefer to use rclone for the task I have, so I started reviewing what change I had to make to my own scripts to get impersonation to work.  

Below is the snippet.  Since you authenticating with a service account is working with rclone, from what I read here, the next step is to include a prn parameter in the JSON request, where username is username@domain.  The returned token will be linked to this account.  So if you then do a retrieval of the drive contents, you would get the contents of the username@domain contents and not the service account's storage files.
`my  $URL = 'https://accounts.google.com/o/oauth2/token';


	use if pDrive::Config->ALLOW_SERVICE, JSON;
	use if pDrive::Config->ALLOW_SERVICE,JSON::WebToken;


	my $time = time;

	my $jwt = JSON::WebToken->encode(
    {
        # your service account id here
        iss   => $self->{_iss},
        scope => 'https://www.googleapis.com/auth/drive',
        aud   => 'https://accounts.google.com/o/oauth2/token',
        exp   => $time + 3600,
        iat   => $time,
        # To access the google admin sdk with a service account
        # the service account must act on behalf of an account
        # that has admin privileges on the domain
        # Otherwise the token will be returned but API calls
        # will generate a 403
        prn => $username,
    },
    $self->{_key},
    'RS256',
    { typ => 'JWT' }
);
	my $req = HTTP::Request->new(POST => $URL);

	$req->content_type("application/x-www-form-urlencoded");
	$req->protocol('HTTP/1.1');
	$req->content('grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Ajwt-bearer&assertion='.$jwt);
	my $res = $self->{_ua}->request($req);
`

**Comment by ncw** [comment]
@mattkaye @ddurdle 
Check out #1491 where I have posted a beta with `--drive-impersonate` so with a service account, rclone can impersonate a user.

@ddurdle That sounds like the missing piece to `--drive-impersonate` the prn... I shall study your code in a bit!

**Comment by ncw** [comment]
I have merged the `--drive-impersonate` flag to [the latest beta](https://beta.rclone.org) now, check out #1491 for instructions!
