### ISSUE TITLE
rclone has IO errors?

### ISSUE THREAD

**Issue by marrie** [ncw/rclone#841]
Rclone version: 

rclone v1.33-79-g77b975dβ

Mac os sierra

When using b2 I got ios errors after rclone uploaded everything. I've attached the log in its intirity. I don't knwo if this is back blazes issue or mine, but thought I'd report it anyway. There are some other issues as well inclding som eerros uploading files. Those are in the log as well.

Thanks.

Output log here](https://github.com/ncw/rclone/files/563298/output.log.zip)

**Comment by marrie** [comment]
Attached is another log for which this happens. I think.

[output music error log.zip](https://github.com/ncw/rclone/files/565651/output.music.error.log.zip)

**Comment by ncw** [comment]
What it looks like is `"sync" "/Volumes/music/3archives"` disappeared after the first retry.

Is that a network mount?  Could it have disappeared?  You could try mapping it to a drive letter and see if that helps - I think mounts are more likely to stick around like that.

**Comment by marrie** [comment]
Actually i mac os I can't mount that to a letter. It was an external drive, maybe it had gotten unplugged some how. I really don't remember. I actually saw the drie though i my computer's list. Oh well, I'll keep troubleshooting from this end.

Thanks.

**Comment by ncw** [comment]
Ah sorry, I thought you were on Windows!  Let me know if you find anything.
