### ISSUE TITLE
[Feature Request] last minute stats

### ISSUE THREAD

**Issue by IKShadow** [ncw/rclone#844]
Any chance adding one last minute stats eg instead of showing only whole session stats we get info what was the speed in last minute. 

The thing my sessions are usually couple of hours long ( 8h+) and I get huge speed inpact when transferring only few files compared to transferring 40, 50+ , so I would prefer to see last minute statistics whats current transfer speed as the couple of hours one, dont tell much.

**Comment by ncw** [comment]
The individual file transfer stats show the transfer rate of the individual files averages over a short period.

I could add a short time period transfer rate to the main stats easily enough though.

**Comment by ncw** [comment]
I'm going to close this as the `--stats` now show individual times for each files which I think should be sufficient.
