### ISSUE TITLE
[Suggestion] Add the original command line when Rclone has finished ?

### ISSUE THREAD

**Issue by doplu** [ncw/rclone#847]
Dear all,

Could it be possible to add the original command line when Rclone has finished its job ?
I am asking this because I run several instances on of my VPS with many different paths and after a moment I don't remember what exact path has just finished running ! 

Example : Rclone has finished its job :

2016/11/03 08:22:10
Transferred:   10.862 GBytes (4.794 MBytes/s)
Errors:                 0
Checks:                 0
Transferred:           46
Elapsed time:    38m39.9s

Would become something like:

2016/11/03 08:22:10
**_Original Command line executed : rclone  copy AD:'Photos/' GD:'Photos/'_**
Transferred:   10.862 GBytes (4.794 MBytes/s)
Errors:                 0
Checks:                 0
Transferred:           46
Elapsed time:    38m39.9s

Thanks in advance ;)

**Comment by ncw** [comment]
Excellent idea - I have the same problem when people sent me logs!  It would probably only appear with the -v flag though.

**Comment by ncw** [comment]
This is done in

http://beta.rclone.org/v1.35-128-g86cc9f3/ (uploaded in 15-30 mins)
