### ISSUE TITLE
ACD remote files/folders do not get deleted when local files/folders are deleted 

### ISSUE THREAD

**Issue by ShapeShifter499** [ncw/rclone#848]
I have a external drive with a bunch of files and a copy of my home directory. I was backing up to Amazon Cloud Drive and I noticed some non encrypted files got uploaded due to a few symlinks that got copied to the external drive with the copy of my home directory. I went through and removed all the symlinks that link outside of the backup directory and then ran rclone again. I expected rclone to remove files that no longer exist but it didn't. Seems like this is a bug, isn't sync supposed to remove files on the remote that no longer exist?

My system is Arch Linux 64 bit with rclone v1.33-DEV  and I was trying to upload to Amazon Cloud Drive.  

Command I used: sudo rclone --config /home/raansu/.rclone.conf -v sync /mnt/split/encrypted/ "amazon-cloud:My Drive"

Does this issue relate to issue #100 ?

**Comment by calisro** [comment]
Correct. rclone is supposed to remove files on the destination but it will leave the empty folders due to issue #100 .

**Comment by ShapeShifter499** [comment]
To clarify, I understand folders end up empty on remote due to issue #100 but that isn't the issue here.  Normal files are NOT being removed on remote when deleted on source.

For example I delete /somedir/SomeTextFile.txt on source, it continues to exist on the remote in the cloud.

**Comment by ShapeShifter499** [comment]
I just noticed this error message.

```
 2016/11/03 13:38:20 amazon drive root 'My Drive': not deleting files as there were IO errors
```

**Comment by davidafuller01** [comment]
Having a similar problem:
`2016/11/04 05:42:40 amazon drive root 'Pictures/myPictures': not deleting files as there were IO errors`
`2016/11/04 05:42:40 Attempt 3/3 failed with 0 errors and: directory not found`
`2016/11/04 05:42:40 Failed to sync: directory not found`
 
with this command syntax:
`rclone sync -v --log-file="/Users/foo/Downloads/rclone-log.txt" myPictures amazonCloudDrive:Pictures/myPictures`

Log file:
- [rclone-log.txt](https://github.com/ncw/rclone/files/571546/rclone-log.txt)

Environment:
- rclone v1.33
- macOS Sierra 10.12.1
- Amazon Cloud Drive

**Comment by ncw** [comment]
Yes if there were errors in `rclone sync` then it will not delete any files from the source.  I borrowed this idea from rsync and it is a good one to stop you losing your data when the network is flakey.

Look at the errors rclone logs and work out why you are getting errors - maybe they are something you can fix like permissions, or maybe you need to increase `--retries`.

In @davidafuller01 's case it looks like rclone can't open the source directory "myPictures".  The error message isn't very helpful here - I'll try to improve it!

In #642 I'm going to add an `--ignore-errors` flag which will allow you to run deletions locally if you really want to even if there were errors - click subscribe on that issue if you are interested in it.

**Comment by ncw** [comment]
@davidafuller01 I've improved the error message for that - in this beta: http://beta.rclone.org/v1.33-107-gff41b0d/

**Comment by davidafuller01** [comment]
@ncw http://beta.rclone.org/v1.33-107-gff41b0d/ seems to be working better.  It's not throwing the same errors.  Did you change something besides the error messages?  Are the changes you made included in the new v1.34?

**Comment by ncw** [comment]
@davidafuller01 
> @ncw http://beta.rclone.org/v1.33-107-gff41b0d/ seems to be working better. It's not throwing the same errors. Did you change something besides the error messages?

Yes there are quite a lot of changes from 1.33 in that version

> Are the changes you made included in the new v1.34?

Yes they are.

**Comment by davidafuller01** [comment]
@ncw I moved up to v1.34 and things seems to be humming along nicely. My issue has seemingly been resolved.  Not sure about @ShapeShifter499's though.

**Comment by ShapeShifter499** [comment]
I'll have to give it a test in a bit as my drive I was syncing has been moved to a new system. This system will have rclone installed.

**Comment by ncw** [comment]
I'm assuming this is all good now :-)
