### ISSUE TITLE
[Suggestion] Build binaries for MIPS32 architecture.

### ISSUE THREAD

**Issue by alecuba16** [ncw/rclone#849]
Please could you generate binaries for MIPS32 architecture (lots of openwrt routers)

Thanks!

**Comment by ncw** [comment]
The main go compilers only support `linux/mips64` and `linux/mips64le` 

For MIPS32 you'd have to use gccgo which I don't have much experience with.

Fancy working out how to do it?

**Comment by ncw** [comment]
Here would be the place to start: https://github.com/golang/go/wiki/GccgoCrossCompilation

**Comment by ncw** [comment]
Here would be the place to start: https://github.com/golang/go/wiki/GccgoCrossCompilation

**Comment by ncw** [comment]
Here would be the place to start: https://github.com/golang/go/wiki/GccgoCrossCompilation

**Comment by ncw** [comment]
Here would be the place to start: https://github.com/golang/go/wiki/GccgoCrossCompilation

**Comment by ncw** [comment]
Here would be the place to start: https://github.com/golang/go/wiki/GccgoCrossCompilation

**Comment by ncw** [comment]
Here would be the place to start: https://github.com/golang/go/wiki/GccgoCrossCompilation

**Comment by alecuba16** [comment]
Hello, I have no experience with go , but yes with C/C++ on MIPS / PIC / ARM... and others embedded devices with crosscompiling tools.

Maybe I can try port your code, but the following two weeks I'm a bit busy because my PhD.

**Comment by ncw** [comment]
It shouldn't need any sort of porting, just building the right cross compiler.

I think go 1.9 (out in about 9 months) may have native support for MIPS32.

**Comment by ncw** [comment]
Unexpectedly (to me anyway) mips32 support will be in go 1.8 which is in beta right now.  I attempted to compile a version for you to try but failed due to: https://github.com/golang/go/issues/18192  - I'm sure it will work soon though!

**Comment by alecuba16** [comment]
I was able to compile other go based tool to access to g drive under 1.8 "beta" for mips32 le  (gdrive) I will try the same with rclone :D

**Comment by jech** [comment]
It's not going to run on typical OpenWRT routers, see https://github.com/golang/go/issues/17984

**Comment by alecuba16** [comment]
@jech On two routers that  I have (RT-N56U and xiaomi mi router) both are based on  MT762x works propertly at least gdrive, just download my binaries and test ( MIPS 32 LE cpu only)....

I don't know if the compile result is not using emulated FPU/HW FPU, but it works....

**Comment by ncw** [comment]
I'm pretty confident that we'll have rclone building for mips32 quite soon. I don't know exactly what hardware is supported by the go runtime though.

**Comment by alecuba16** [comment]
@ncw I think that @jech  assumes like me that all MIPS32 based routers includes or not FPU.

My case, it includes FPU, maybe the routers that he's working on doesn't have.

**Comment by jech** [comment]
@alecuba16, I'm fairly positive that the 24KEc and 1004Kc cores have no FPU — it's the 24Kf and the 1004Kf that do.  I'm glad to hear that Go binaries work for you, I'd be interested to know the explanation.

**Comment by alecuba16** [comment]
@jech The only possibilities that I'm thinking now:

a)-Master of go compiler supports SW-FPU

b)-The gdrive code and its dependencies doesn't do any FPU compute, that is mostly improbable because it uses https, graph algorithms,and other dependencies that for sure there are floats... 

c)-The binary runs, lists files and help, but since I have no tested the connecting because I have to integrate the root certificates on tomato , since is a requirement for https connection. Anyway I can test on openwrt first that is easier to integrate the root certificates.

Anyway if you want , you can test my binaries for gdrive (sorry for the intrusion, just for testing purposes):

MIPS32be (big endian) : https://mega.nz/#!w59x2BIR!-A0bSwkqW-KCN-yZxrSw9r_17uSXwTHL9Jz1xEydKU4

MIPS32le (little endian): 
https://mega.nz/#!Eh0EwYaZ!8-qQgtEW3kXPSEoRQHhG5mk3QZ0VECxGyjeLuenlzoc

**Comment by jech** [comment]
Most probably your kernel has been compiled with the FPU emulator included.

**Comment by ncw** [comment]
OK the upstream golang/x/sys repo is fixed (swift work Go team!) so here are some binaries for mips and mipsle built with go 1.8beta1

  * mips - http://pub.rclone.org/rclone-v1.34-49-ge79a5de-mips.zip
  * mipsle - http://pub.rclone.org/rclone-v1.34-49-ge79a5de-mipsle.zip

Check out [how to install root certs also](http://rclone.org/faq/#rclone-gives-x509-failed-to-load-system-roots-and-no-roots-provided-error)

I'd be interested to know if these work!

rclone definitely uses floating point maths for the stats calculations BTW.

Do I need to build both mips and mipsle builds?  Are they both in use?

**Comment by alecuba16** [comment]
I think that big endian is almost for especial porpouses the most common is little endian,so if I would have to choice, little endian always

**Comment by ncw** [comment]
@alecuba16 thanks for the link!

**Comment by rajnmithun** [comment]
I am trying to run a go binary on RT-N56U with openWRT, when I run the binary it does nothing but take CPU 

The program is :
```
package main

func main() {
	print("hello world")
}
```
and build using `Go 1.8`
`env GOOS=linux GOARCH=mipsle go build -o test_mipsle`
produces
```
file test_mipsle
test_mipsle: ELF 32-bit LSB executable, MIPS, MIPS32 version 1 (SYSV), statically linked, not stripped
```

so I am not sure what am I missing.

@ncw @alecuba16 @jech where you able to get a `Go` binary running on RT-N56U?

Thanks.

**Comment by alecuba16** [comment]
@rajnmithun Check the arch of your binaries, the easiest way is copy a binary from your RT-N56U to your desktop pc and use file.

Then when you are sure your arch and your endian try again.

anyway upload your binary , since mine is little endian too , I will test for you.

**Comment by rajnmithun** [comment]
On the box
```
file /sbin/uci
/sbin/uci: ELF 32-bit LSB executable, MIPS, MIPS32 rel2 version 1, dynamically linked (uses shared libs), corrupted section header size
```
I have binary built which hangs [https://github.com/rajnmithun/playground/tree/master/test](url)

Thanks for the help.

**Comment by ncw** [comment]
Now that go 1.8 has been released I've integrated linux/mips and linux/mipsle into the release.  Please find them in this beta.  This will be in the 1.36 release.

http://beta.rclone.org/v1.35-119-g69a15ae/ (uploaded in 15-30 mins)

**Comment by ReneSch** [comment]
Hello,
i´ve tested with a little openwrt device, using the mipsle file
i´ve got a error
"root@OpenWrt:~# rclone
/usr/sbin/rclone: line 1: syntax error: unexpected "(" "
am i missing packages? What will i have to do to make it work?

**Comment by alecuba16** [comment]
@ReneSch You are running wrong architecture binary , check your architecture with file command on your openwrt or if you are unable to use file command install with ipkg/opkg or copy to a linux server/desktop.

**Comment by rajnmithun** [comment]
I had enable FPU for my openWRT firmware and I was able to run the binary.

**Comment by oczkers** [comment]
Is there any chance somebody can build mips32 be with sw-fpu?

**Comment by drinkmystery** [comment]
@oczkers
maybe Go 1.9
https://github.com/golang/go/issues/18162

**Comment by hereisderek** [comment]
uhm, any update on this?

although I'd doubt it'd be performant in any way

**Comment by ncw** [comment]
You should be able to build with `GOMIPS=softfloat` to use the soft floating point.
