### ISSUE TITLE
Enhancement: IAM role support

### ISSUE THREAD

**Issue by shawnbutts** [ncw/rclone#85]
http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/iam-roles-for-amazon-ec2.html

I'd love to use this.  But, without the IAM role support I really can't.

**Comment by zeshanb** [comment]
@Shawn When running rClone config please try the auth param. Please try
adding the additional IAM params required to End Point when running rClone
config wizard https://s3.amazonaws.com?TheParam=value&

?TheParam=Value&

http://docs.aws.amazon.com/AWSEC2/latest/APIReference/Query-Requests.html

**Comment by ncw** [comment]
I'm afraid I don't know very much about IAM roles.  If @zeshanb idea works I'd be happy to write it up in the docs.

This would probably be made easier by the branch I have for using the official AWS API...

**Comment by shawnbutts** [comment]
I couldn't get it to work.  
I'm sure this will work out of the box with the official AWS SDK.  

Thanks

**Comment by ncw** [comment]
Thanks for having a go

-- Nick
