### ISSUE TITLE
[Feature Request] Mountable Local Crypts in Windows to support third-party FUSE.

### ISSUE THREAD

**Issue by euricstone** [ncw/rclone#853]
My current build is Windows 10, NetDrive2, with Boxcryptor. NetDrive2 creates a FUSE mount for Google Drive (as well as other cloud services), and Boxcryptor mounts the NetDrive2 mount. This enables me to use Plex to scan and stream from X:/Z:/Media. X: being Boxcryptor (encryption), Z: being NetDrive FUSE mount.

I have successfully used rclone to create a crypt which mounts the NetDrive2 mount. I've done some basic terminal work so far, ls, lsd, copy, mkdir, purge. So in theory, if I could mount this crypt in Windows I would have a working solution until rclone mount is brought over fully to Windows (which I recognize might be quite awhile / never).

Put another way, what I'm looking for, is a way to mount an intermediary to decrypt the files being pulled from NetDrive2 (or whatever third-party FUSE mount someone may be using).

I'll be happy to provide you with any other information you may need, or to help you beta test. One last note for anyone else who reads this, I used the above as an example only, I don't recommend rclone copy -ing to a fuse mount, just rclone copy to the remote directly-it will skip a 'hop'.

I love rclone, it's really great, thanks.

> What is your rclone version (eg output from `rclone -V`)
rclone v1.33-77-g93e8440

> Which OS you are using and how many bits (eg Windows 7, 64 bit)
Windows 10, 64-bit

**Comment by ncw** [comment]
Do you have a linux box available to you?  Eg a rasperry PI, or maybe a VM?  You could use rlcone to mount a remote there, then export it using samba as a CIFS share to Windows.  That would probably work!

**Comment by jkaberg** [comment]
There is also https://github.com/dokan-dev/dokany. But I don't know how well that would fly with rclone at current state (probably not at all)

**Comment by euricstone** [comment]
Getting a dedicated box for linux...soon. So yes, that is an option (and in-fact running a linux Mint VM with rclone did work for some basic testing I ran, though I didn't get the samba share setup-Linux isn't my strength).

If, in the future, you do look into bringing rclone mount support to windows stay away from dokany, it is still terribly buggy and unstable from everything I've read. Given that I have a third-party fuse mount that I'm happy with I was just hoping I'd have a way to get away from using boxcryptor for encryption/decryption. File-name encryption, open-source, are just a few of the reasons I'd prefer to use rclone. I'm still going to be using rclone in my stack in other ways, so thanks for working on such a great project.

**Comment by ncw** [comment]
Glad you like rclone :-)  I will look into FUSE for windows when it has stabilised a bit for sure.

You might be better off asking this sort of thing on https://forum.rclone.org - there are lots of people trying to do similar things to you there.

**Comment by jkaberg** [comment]
@ncw I've been using Dokany (along with https://github.com/viciousviper/DokanCloudFS) for a few weeks now and it's very stable. Would you mind reconsidering? You already have the the FUSE functions in place, so it's a matter of using the [FUSE wrapper](https://github.com/dokan-dev/dokany/wiki/FUSE) for [Dokany](https://github.com/dokan-dev/dokany).

Mounting my crypt volumes on Windows would be a huge win (instead of on linux vm->smbfs which adds additional latency and the traditional VM overhead etc.).
