### ISSUE TITLE
General broken-ness with "rclone mount" on ACD encrypted remotes

### ISSUE THREAD

**Issue by DurvalMenezes** [ncw/rclone#856]
Hello,

As per the subject above.

First the required data: 
> What is your rclone version (eg output from `rclone -V`)

rclone v1.34 (but probably has been happening earlier, as I've only started using "rclone mount" on the latter v.1.33 betas).

> Which OS you are using and how many bits (eg Windows 7, 64 bit)

Linux 64-bit (Devuan Jessie 1.0-Beta).

> Which cloud storage system are you using? (eg Google Drive)

Amazon Cloud Drive, encrypted by rclone; 

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

rclone mount command: 
`rclone -v --debug-fuse --dump-headers --log-file=rclone_mount_ACDE.log mount ACDE:/ /home/rclone/ACDE
`

> A log from the command with the `-v` flag (eg output from `rclone -v copy /tmp remote:tmp`)
The log is very large and has lots of sensitive info. Will redact and post later if requested/necessary. 

So here's the first issue of this kind I was able to reproduce semi-reliably here: 

1. Mounting the remote as above and just listing the mountpoint with "ls -l":
```
total 0
drwxr-xr-x 1 rclone rclone         0 Nov  6 10:40 XXXXXXXXXXX0001
drwxr-xr-x 1 rclone rclone         0 Nov  6 10:40 XXXXXXXXXXX0002
drwxr-xr-x 1 rclone rclone         0 Nov  6 10:40 XXXXXXXXXXX0003a
drwxr-xr-x 1 rclone rclone         0 Nov  6 10:40 XXXXXXXXXXX0003b
drwxr-xr-x 1 rclone rclone         0 Nov  6 10:40 XXXXXXXXXXX0004a
drwxr-xr-x 1 rclone rclone         0 Nov  6 10:40 XXXXXXXXXXX0004b
drwxr-xr-x 1 rclone rclone         0 Nov  6 10:40 XXXXXXXXXXX0005
drwxr-xr-x 1 rclone rclone         0 Nov  6 10:40 XXXXXXXXXXX0006
drwxr-xr-x 1 rclone rclone         0 Nov  6 10:40 XXXXXXXXXXX0007
drwxr-xr-x 1 rclone rclone         0 Nov  6 10:40 XXXXXXXXXXX0008
drwxr-xr-x 1 rclone rclone         0 Nov  6 10:40 XXXXXXXXXXX0009
drwxr-xr-x 1 rclone rclone         0 Nov  6 10:40 XXXXXXXXXXX0010
-rw-r--r-- 1 rclone rclone 582582272 Nov  2 21:42 YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY_-_split_aa
drwxr-xr-x 1 rclone rclone         0 Nov  6 10:40 ZZZZZZZZZZZZ01
drwxr-xr-x 1 rclone rclone         0 Nov  6 10:40 WWWWWWWWWWWWWWWWWWWWW_20160917
```
I imediatelly suspected the `YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY_-_split_aa` file listed above, as my top-level ACDE: dir doesn't have *any* files. 

2. The above suspect is confirmed with an "rclone lsd ACDE:", to wit:
```
          -1 2016-10-03 06:12:11        -1 WWWWWWWWWWWWWWWWWWWWW_20160917
          -1 2016-10-07 19:24:20        -1 XXXXXXXXXXX0003a
          -1 2016-10-08 01:51:04        -1 XXXXXXXXXXX0002
          -1 2016-10-10 11:34:10        -1 XXXXXXXXXXX0006
          -1 2016-10-10 11:37:07        -1 XXXXXXXXXXX0003b
          -1 2016-10-17 11:20:33        -1 XXXXXXXXXXX0005
          -1 2016-10-20 11:39:49        -1 XXXXXXXXXXX0008
          -1 2016-10-16 03:25:33        -1 XXXXXXXXXXX0004b
          -1 2016-10-19 04:17:03        -1 XXXXXXXXXXX0007
          -1 2016-10-20 20:26:23        -1 XXXXXXXXXXX0009
          -1 2016-10-14 21:56:07        -1 XXXXXXXXXXX0004a
          -1 2016-10-25 23:48:01        -1 ZZZZZZZZZZZZ01
          -1 2016-10-27 11:09:08        -1 XXXXXXXXXXX0001
          -1 2016-10-30 16:04:41        -1 XXXXXXXXXXX0010
2016/11/06 10:58:14 
Transferred:      0 Bytes (0 Bytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:        1.6s
```

3. In fact, fishing around with `rclone lsl` shows the `YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY_-_split_aa` file is actually under the  `WWWWWWWWWWWWWWWWWWWWW_20160917` directory: 
```
	rclone lsl acdenc:WWWWWWWWWWWWWWWWWWWWW_20160917
		45000000000 2016-10-02 21:07:28.744000000 YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY_-_split_aa
		[...]
		2016/11/06 11:00:35 
		Transferred:      0 Bytes (0 Bytes/s)
		Errors:                 0
		Checks:                 9
		Transferred:            0
		Elapsed time:        1.8s
```

Note that not only the file is showing up at the wrong place, but also its metadata (size and time) are also corrupted. 

There's more "stuff" happening with other file operations in the mount (like file contents being silently corrupted", I will post it here when I'm able to reproduce it.

Cheers, 
    --
  Durval.

**Comment by ncw** [comment]
A quick thought... Try using ACDE: instead of ACDE:/ in your mount command line.

**Comment by ncw** [comment]
I note also that you've used two different remotes `ACDE:` and `acdenc:` in your tests.

What do you get if you do

    rclone -q ls --max-depth 1 ACDE:

Hopefully that will show the single file you see in your mount.  That is effectively what mount does anyway.

Note that `rclone lsd` doesn't show files, so your `rclone lsd ACDE:` isn't ever going to show that file.

For your final test you seem to be using `rclone lsl acdenc:` which is a different remote.

**Comment by DurvalMenezes** [comment]
Hello @ncw,

Sorry for the long delay getting back to you; just saw your response, for some reason I'm not receiving mails about this and other issues even tho I'm subscribed to them... :-/ More below: 

> A quick thought... Try using ACDE: instead of ACDE:/ in your mount command line.

Just did, exactly the same results. 

> I note also that you've used two different remotes ACDE: and acdenc: in your tests.

My mistake during editing my post... it's actually ACDE: all the way. 

> What do you get if you do
> `rclone -q ls --max-depth 1 ACDE:`
> Hopefully that will show the single file you see in your mount. That is effectively what mount does anyway.

You are correct, here's the output:
`582582272 YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY_-_split_aa
`

> Note that rclone lsd doesn't show files, so your rclone lsd ACDE: isn't ever going to show that file.

Oh! My mistake... I thought it was the equivalent of a 'ls -d DIR/*'... :-/

In fact, I checked using the ACD web tool and indeed there's a file with that size at the root of my account... which shouldn't be there, but anyway that was probably me messing up my upload somehow, and not rclone.

I'm closing this issue now, sorry for the false alarm.

Thanks, 
-- 
   Durval.
