### ISSUE TITLE
Amazon Cloud Drive mount fails on Raspberry Pi

### ISSUE THREAD

**Issue by zordiack** [ncw/rclone#857]
When filing an issue, please include the following information if possible as well as a description of the problem.  Make sure you test with the [latest beta of rclone](http://rclone.org/downloads/).

If you've just got a question then please use the [rclone forum](https://forum.rclone.org/) instead of filing an issue.

> What is your rclone version (eg output from `rclone -V`)
rclone v1.34-DEV (6.11.2016 git)

> Which OS you are using and how many bits (eg Windows 7, 64 bit)
Linux 64bit ARM (Raspberry Pi 3)

> Which cloud storage system are you using? (eg Google Drive)
Amazon Cloud Drive (both encrypted and not)

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone mount -v --debug-fuse --dump-headers acde: amazon/

> A log from the command with the `-v` flag (eg output from `rclone -v copy /tmp remote:tmp`)

pi@raspinas:~$ rclone mount -v --debug-fuse --dump-headers acde: amazon/
2016/11/06 17:55:10 rclone: Version "v1.34-DEV" starting with parameters ["rclone" "mount" "-v" "--debug-fuse" "--dump-headers" "acde:" "amazon/"]
2016/11/06 17:55:11 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2016/11/06 17:55:11 HTTP REQUEST (req 0x11da4180)
2016/11/06 17:55:11 GET /drive/v1/account/endpoint HTTP/1.1
Host: drive.amazonaws.com
User-Agent: rclone/v1.34-DEV
Authorization: XXXX
Accept-Encoding: gzip

2016/11/06 17:55:11 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2016/11/06 17:55:12 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2016/11/06 17:55:12 HTTP RESPONSE (req 0x11da4180)
2016/11/06 17:55:12 HTTP/1.1 200 OK
Cache-Control: no-store
Connection: keep-alive
Content-Type: application/json
Date: Sun, 06 Nov 2016 15:55:12 GMT
Pragma: no-cache
Server: Server
Vary: User-Agent
X-Amzn-Requestid: 66dba2a8-a439-11e6-8f31-313429e634b1

2016/11/06 17:55:12 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2016/11/06 17:55:12 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2016/11/06 17:55:12 HTTP REQUEST (req 0x10c0a480)
2016/11/06 17:55:12 GET /drive/v1/nodes?filters=kind%3AFOLDER+AND+isRoot%3Atrue HTTP/1.1
Host: cdws.us-east-1.amazonaws.com
User-Agent: rclone/v1.34-DEV
Authorization: XXXX
Accept-Encoding: gzip

2016/11/06 17:55:12 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2016/11/06 17:55:13 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2016/11/06 17:55:13 HTTP RESPONSE (req 0x10c0a480)
2016/11/06 17:55:13 HTTP/1.1 200 OK
Cache-Control: no-store
Connection: keep-alive
Content-Type: application/json
Date: Sun, 06 Nov 2016 15:55:13 GMT
Pragma: no-cache
Server: Server
Vary: User-Agent
X-Amzn-Requestid: 6770de30-a439-11e6-b2fd-41afa873d2c7

2016/11/06 17:55:13 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2016/11/06 17:55:13 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2016/11/06 17:55:13 HTTP REQUEST (req 0x10df2200)
2016/11/06 17:55:13 GET /drive/v1/account/endpoint HTTP/1.1
Host: drive.amazonaws.com
User-Agent: rclone/v1.34-DEV
Authorization: XXXX
Accept-Encoding: gzip

2016/11/06 17:55:13 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2016/11/06 17:55:14 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2016/11/06 17:55:14 HTTP RESPONSE (req 0x10df2200)
2016/11/06 17:55:14 HTTP/1.1 200 OK
Cache-Control: no-store
Connection: keep-alive
Content-Type: application/json
Date: Sun, 06 Nov 2016 15:55:14 GMT
Pragma: no-cache
Server: Server
Vary: User-Agent
X-Amzn-Requestid: 67a02bc8-a439-11e6-af7a-d15cdd98a493

2016/11/06 17:55:14 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2016/11/06 17:55:14 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2016/11/06 17:55:14 HTTP REQUEST (req 0x11da5180)
2016/11/06 17:55:14 GET /drive/v1/nodes?filters=kind%3AFOLDER+AND+isRoot%3Atrue HTTP/1.1
Host: cdws.us-east-1.amazonaws.com
User-Agent: rclone/v1.34-DEV
Authorization: XXXX
Accept-Encoding: gzip

2016/11/06 17:55:14 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2016/11/06 17:55:14 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2016/11/06 17:55:14 HTTP RESPONSE (req 0x11da5180)
2016/11/06 17:55:14 HTTP/1.1 200 OK
Cache-Control: no-store
Connection: keep-alive
Content-Type: application/json
Date: Sun, 06 Nov 2016 15:55:14 GMT
Pragma: no-cache
Server: Server
Vary: User-Agent
X-Amzn-Requestid: 67cdcb47-a439-11e6-bc4e-a92899490d7a

2016/11/06 17:55:14 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2016/11/06 17:55:14 Encrypted amazon drive root '': Modify window not supported
2016/11/06 17:55:14 Encrypted amazon drive root '': Mounting on "amazon/"
2016/11/06 17:55:14 Encrypted amazon drive root '': Root()

......

And then the process just hangs there and the mount is not succesful. The mounting used to work I think 2 weeks ago or so and now it's not working. I tried mounting encrypted and unencrypted, same results. Listing and uploading/downloading works, but mounting doesn't. When I kill the hanged mount with ^C, there is a non-working mount point existing:

pi@raspinas:~$ mount
....
acde: on /home/pi/amazon type fuse.rclone (rw,nosuid,nodev,relatime,user_id=1000,group_id=1000)

but it's not working at all and ls -la shows this:

pi@raspinas:~$ ls -la
ls: cannot access amazon: Transport endpoint is not connected
d?????????   ? ?    ?           ?            ? amazon

This seems FUSE/rclone related bug to me, but I haven't upgraded FUSE or anything related since this last worked, so it seems it's something related to rclone.

**Comment by ncw** [comment]
So does using `rclone ls acde:` work ok?

Are you using 32 bit ARM or 64 bit?

Can you try the beta's here: http://beta.rclone.org/ and try to find one which works and then work out where it stops working?  It might be that the update of the fuse library before the v1.34 release broke things.

**Comment by zordiack** [comment]
So does using rclone ls acde: work ok?
- Yes

Are you using 32 bit ARM or 64 bit?
- I guess it's actually 32bit, I was mistaken here

pi@raspinas:~$ uname -a
Linux raspinas 4.4.26-v7+ #915 SMP Thu Oct 20 17:08:44 BST 2016 armv7l GNU/Linux

Can you try the beta's here: http://beta.rclone.org/ and try to find one which works and then work out where it stops working? It might be that the update of the fuse library before the v1.34 release broke things.
- I wil try and will report back in a moment

**Comment by zordiack** [comment]
Scratch that, this is propably not rclone bug. I'm now unable to get mount to work with any beta version starting from 1.33-41, so something must have changed in this end after all. No idea what however.

**Comment by ncw** [comment]
@zordiack is there an old mount running somewhere? `mount | grep rclone` will show you, you can then use `fusermount -z -u` to unmount it.  If that fails reboot.

**Comment by zordiack** [comment]
No old mountpoints present, I even tried rebooting but it doesn't help. I can't find anything in the system logs either, the mount process just hangs. I just tested with acd_cli and it's mount seems to work so FUSE is not completely broken, it just doesn't work with rclone anymore for some reason.

**Comment by zordiack** [comment]
Okay I got a little further with strace and it seems to be a permission issue:

[pid  4776] openat(AT_FDCWD, ".", O_RDONLY|O_NONBLOCK|O_LARGEFILE|O_DIRECTORY|O_CLOEXEC) = 5
[pid  4776] getdents(5, /* 2 entries */, 32768) = 32
[pid  4776] getdents(5, /* 0 entries */, 32768) = 0
[pid  4776] close(5)                    = 0
[pid  4776] mount("acde:", ".", "fuse.rclone", MS_NOSUID|MS_NODEV, "fd=4,rootmode=40000,user_id=1000"...) = -1 EPERM (Operation not permitted)
[pid  4776] write(2, "fusermount: mount failed: Operat"..., 50) = 50
[pid  4775] <... read resumed> "fusermount: mount failed: Operat"..., 4096) = 50
[pid  4776] close(4 <unfinished ...>
[pid  4775] futex(0x909bfc, FUTEX_WAKE, 1 <unfinished ...>
[pid  4776] <... close resumed> )       = 0
[pid  4775] <... futex resumed> )       = 1
[pid  4776] exit_group(1)               = ?
[pid  4775] clock_gettime(CLOCK_REALTIME, {1478466364, 893913507}) = 0
[pid  4775] write(2, "2016/11/06 23:06:04 mount helper"..., 902016/11/06 23:06:04 mount helper error: fusermount: mount failed: Operation not permitted
) = 90

pi@raspinas:~$ ls -la /dev/fuse
crw-rw-rw- 1 root root 10, 229 Nov  6 22:48 /dev/fuse
pi@raspinas:~$ ls -la /usr/local/bin/fusermount
-rwxr-xr-x 1 root root 83596 Nov  6 20:31 /usr/local/bin/fusermount

I'm not sure what could be the problem, pi user should have access to fusermount binary and write access to /dev/fuse, I don't know what more does it need.

**Comment by zordiack** [comment]
Please remove this issue as there was no issue to begin with. The reason for confusion was that I didn't put rclone in the background... so it was working as it should have all the time... tl:dr this was a major user error ;)

**Comment by ncw** [comment]
No problems - glad you got to the bottom of it :-)
