### ISSUE TITLE
Inconsistent read speeds on ACD mount

### ISSUE THREAD

**Issue by ftruzzi** [ncw/rclone#858]
Hello, I've got the usual ACD + Plex + encfs setup going on a VPS and I'm noticing the following issue: while I can read some files at the maximum speed my home connection allows for (9-10MB/s), some are reading at an awfully slow speed which does not allow for streaming (400-700KB/s). 

This behavior is file-inconsistent in the sense that files that sometimes are "fast" can be slow after awhile and vice-versa.

Speeds for those files also tend to fluctuate a lot and there is no CPU, RAM or I/O bottleneck from what I can see. 

If that helps, a similar behavior happens using acd_cli.

> What is your rclone version (eg output from `rclone -V`)

rclone v.1.34

> Which OS you are using and how many bits (eg Windows 7, 64 bit)

Ubuntu 16.04 64bit

> Which cloud storage system are you using? (eg Google Drive)

Amazon Cloud Drive

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

rclone mount -v --allow-other --read-only --max-read-ahead 1024k acdremote:myfolder /home/myuser/myfolder

> A log from the command with the `-v` flag (eg output from `rclone -v copy /tmp remote:tmp`)

There isn't any difference in the logs between slow and fast files... just the speed the lines advance at!

**Comment by ncw** [comment]
> If that helps, a similar behavior happens using acd_cli.

That probably means it isn't rclone's fault.

It might be your ISP doing traffic shaping, or there might be packet loss on the link.

It would be worth taking a trawl through rclone's logs to see if it is having to do retries to fetch more stuff from amazon.

**Comment by ncw** [comment]
It might be worth you looking at [this thread](https://forum.rclone.org/t/acd-fuse-mount-still-not-working-with-plex/170/12) on the forum where setting `--max-read-ahead` is discussed and see if that helps.

**Comment by ftruzzi** [comment]
Thanks you for your reply! I'm already using the --max-read-ahead 1024k option. Now I'm trying to re-upload everything to ACD to a different folder using rclone encryption instead of encfs.

However, reading from the encfs decrypted ACD folder and reuploading is as fast as my connection allows (30MB/s) so I might be looking in the wrong place. I will let the upload finish and then do some more tests, both with encfs and crypt, with the --debug-fuse option enabled. 

I will post some more logs and let everyone know :)

**Comment by calisro** [comment]
It sounds like you are using plex/sftp on an encfs mount that sits ontop of an rclone mount.  Is this correct?

**Comment by ftruzzi** [comment]
Yeah that's correct. My main plex folder on ACD is encrypted with encfs and I'm mounting it either from rclone or acd_cli.

**Comment by calisro** [comment]
The slowness may related to the block size and cipher and the way encfs works in general.  You may actually get better performance by lowering the max-read-ahead to like 8k.  In my testing previously, I was able to sustain about 4MB/s using smaller sizes. Still not great but better.

**Comment by ftruzzi** [comment]
I think you're right - I've been doing some tests and whenever a file is downloading slow (about 1MB/s) I can go to to encrypted folder and download it at full speed.

It's probably an encfs issue and I will try experimenting with different config values. Thanks!

**Comment by ncw** [comment]
OK I'll close this issue then.  If you find it is rclone's fault then please re-open!
