### ISSUE TITLE
Google Photos folder giving error message

### ISSUE THREAD

**Issue by andrewbanchich** [ncw/rclone#859]
When filing an issue, please include the following information if possible as well as a description of the problem.  Make sure you test with the [latest beta of rclone](http://rclone.org/downloads/).

If you've just got a question then please use the [rclone forum](https://forum.rclone.org/) instead of filing an issue.

I set Google Drive to show Google Photos files in a "Google Photos" folder. I read that other people got syncing to work with this method, but I keep getting this error and nothing syncs.

> What is your rclone version (eg output from `rclone -V`)

1.34

> Which OS you are using and how many bits (eg Windows 7, 64 bit)

Ubuntu 16.10 64-bit

> Which cloud storage system are you using? (eg Google Drive)

Google Drive

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

rclone copy 'googledrive:Google Photos' .

> A log from the command with the `-v` flag (eg output from `rclone -v copy /tmp remote:tmp`)

Attempt 3/3 failed with 0 errors and: error listing source: Google drive root 'Google Photos': couldn't list directory: json: cannot unmarshal string into Go value of type float64

Failed to copy: error listing source: Google drive root 'Google Photos': couldn't list directory: json: cannot unmarshal string into Go value of type float64

**Comment by ncw** [comment]
Strange - It works for me, I just tried it now.

Did you tell photos to show your pictures in Drive?  Go to https://photos.google.com/settings and make sure the `Show Google Drive photos & videos in your Photos library` setting is set.

Assuming you did that already...

Does `rclone ls  'googledrive:Google Photos'` work?  I suspect it will fail in the same way.

If it does fail in the same way can you do

     rclone -v --dump-bodies --retries 1 ls  'googledrive:Google Photos' --log-file output.log.txt

Or if it doesn't do

     rclone -v --dump-bodies --retries 1 copy  'googledrive:Google Photos' /path/to/wherever --log-file output.log.txt

and post (or email it to me privately at nick@craig-wood.com if you prefer) the output.log.txt please.

Thanks

Nick

**Comment by ncw** [comment]
Looks like google have fixed the original bug, so come the next update of the vendor directory this should be fixed too!

**Comment by idcmp** [comment]
Is there a way to detect and skip the files causing this during a sync in v1.35?

**Comment by ncw** [comment]
No, I don't think so....

I'll update the vendor directory and post a beta here for you to try if you want?

**Comment by idcmp** [comment]
Hi Nick,

That would be most appreciated! 

I'm trying to backup Google Drive to B2 and after hours of success, it fails with:

    B2 bucket google-drive-backup: not deleting files as there were IO errors
    Attempt 25/25 failed with 3 errors and: error listing source: Google drive root '': couldn't list directory: json: cannot unmarshal string into Go value of type float64
    Failed to sync: error listing source: Google drive root '': couldn't list directory: json: cannot unmarshal string into Go value of type float64

Having read through this issue (and the upstream one), I believe I'm suffering from this.

**Comment by ncw** [comment]
I've updated the vendor directory, so hopefully you should find this fixed in the latest beta

http://beta.rclone.org/v1.35-117-g8ec57d1/

**Comment by idcmp** [comment]
This definitely gets through now, but even though I'm running with --ignore-existing, it's creating multiple copies of files on the destination (syncing drive -> b2), none of the destination files seem to have a timestamp that matches the creation, but in b2's "File Info", the src_last_modified_millis seems field  to be correct.

Should I open a separate issue for this?

**Comment by ncw** [comment]
Google photos are a bit prone to having duplicates - I suggest you run the `rclone dedupe` command [check the docs first](http://rclone.org/commands/rclone_dedupe/) and remove the duplicates, then try the sync again.

**Comment by idcmp** [comment]
Just wanted to give you an update that I've run dedupe and a fresh sync to a new b2 bucket is in progress using v1.35-117..

**Comment by idcmp** [comment]
Hey @ncw, this seems to fix it! Thanks muchly!

**Comment by ncw** [comment]
@idcmp great :-)

I'll close this issue now.
