### ISSUE TITLE
drive: strange syncing problem

### ISSUE THREAD

**Issue by AntoineGR** [ncw/rclone#86]
Hello,
I'm trying to use rclone to sync a 10TB NAS to Google Drive.
Currently working under OSX.

I did a first run with "rclone copy" : no problem, the 10TB uploaded smoothly (awesome).
But now when if I run "rclone sync" on the 10TB : every file is copied again, no skipping, as if every time/date/filesize had changed.

And here is the strange part :
if I try and run "rclone sync" on a small folder (20GB for instance), it works perfectly : every file is skipped as expected.

Any idea on what might cause the issue ? could it be a problem during "Building File List" (which took 32 minutes in my case) ?

**Comment by ncw** [comment]
(Sorry for the delay in replying - I've been on vacation)

If you run the big sync again does it still copy all the files or does it work properly?

I wonder if it could be something like your computer changing timezone, or going to DST...

Are you 100% sure you used the same destination for the `sync` and the `copy`?

If you use the -v flag to rclone it will print out a great deal of info, including why it is copying a file

Eg

     "Sizes differ"
     "Modification times differ by %s: %v, %v"
     "Size and modification time the same (differ by %s, within tolerance %s)"

If you can still reproduce the problem, examining those log lines would be very helpful and if you can paste a representative sample that would be great!

Thanks

**Comment by AntoineGR** [comment]
Well, I tried a few times and so far it's working correctly now !
I'll come back with a log if it occurs again...

**Comment by ncw** [comment]
@AntoineGR Thanks for trying!

**Comment by ncw** [comment]
I'll close this now - please re-open if you can reproduce.

Thanks

Nick
