### ISSUE TITLE
Can't store file with control characters (but worked previously)

### ISSUE THREAD

**Issue by diamondsw** [ncw/rclone#861]
> What is your rclone version (eg output from `rclone -V`)
rclone v1.34-03-g34e7ca9β
> Which OS you are using and how many bits (eg Windows 7, 64 bit)
Debian 8
> Which cloud storage system are you using? (eg Google Drive)
Amazon Cloud Drive
> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone sync /path amazon:/path --verbose
> A log from the command with the `-v` flag (eg output from `rclone -v copy /tmp remote:tmp`)
Local file system at /nfs/nas/Backup/Dante/: Can't store file with control characters: "Icon\r"

Previously rclone (v1.33) would store files with control characters (such as the unfortunately common "Icon\r" files created by Mac OS X - how I'd like to give that engineer a piece of my mind!). As of the latest beta, rclone no longer supports them and prints the above message, then proceeds to delete the files from Amazon Cloud Drive.

However, it appears that the files were successfully stored by v1.33, as the delete message from v1.34beta is "corrupted", e.g.
": Deletedarie/2/Icon"
What happened is the filename printed, and when it hit the /r at the end of "Icon/r" it reset the position to the start of the line - and then the ": Deleted" text overwrote beginning of the line. If the "\r" hadn't been stored on ACD, then the deletion wouldn't have that carriage return in the middle. So it looks like at least some cloud services support some control characters.

Honestly, it's not a big deal if these aren't backed up - it's a corner case for sure and control characters in filenames are evil. However, it's worth noting that there's at least one semi-useful case for them (Icon\r, and the related ._Icon\r when saved on foreign filesystems) and Amazon Cloud Drive at least stores them properly.

**Comment by ncw** [comment]
I put that in to fix #/689

Yes I agree with you about the engineer who came up with `Icon\r` files!

I could put a flag in to allow files with control characters - is that worth doing?  I think they should be disallowed by default.

**Comment by diamondsw** [comment]
Heh, so this all started with those infamous little files. Nah, I don't want to bloat your program with extra options for the user to understand and you to support. Since this is actively breaking some services, just leave it as-is (I can only imagine how difficult it would be to determine which services support which control characters!). Thanks for the background info!

**Comment by ncw** [comment]
Thanks for letting me know that you can store `\r` on ACD - that is a surprise!

As for the actual `Icon\r` files, I believe they are 100% resource fork which won't have been backed up properly by rclone anyway.

I'll close this issue for now, but it will remain in the archives should anyone else have a similar experience!

**Comment by diamondsw** [comment]
One extra comment, just for future reference. While the Icon\r files are resource fork normally, they get converted to data fork (._Icon\r) on foreign filesystems. Not advocating for re-adding support, just pointing out that there are some damn weird edge cases.

**Comment by msyquest** [comment]
Thank you, rclone changed everything for the best!

I would like to add to this thread even if its old.
Regarding the control character, they give me trouble uploading to Google Drive and Amazon drive. When I go in both of Gdrive and Adrive using the web page, I see double folder. Using the program CarotDAV to look, I see that the folders that are created in double have in fact %0D added to the folder name (the doubled one's).
From what I saw on Google, %0D is an equivalent to \r, and its a real pain :)

Do you know if its possible to have rclone cleaning those things before uploading? Or maybe, do you have an advice on what I could do to set things better before uploading? I am uploading from a Debian OS (Feralhosting's seedbox).

Kind Regards,
