### ISSUE TITLE
Google Photos sync issue

### ISSUE THREAD

**Issue by Denao2** [ncw/rclone#863]
When attempting to sync photos from Google Drive I get transfer errors with mismatched MD5 hash. Also had issues with duplicate files but this was resolved by rclone dedupe command. Log attached.

> What is your rclone version (eg output from `rclone -V`)

1.34

> Which OS you are using and how many bits (eg Windows 7, 64 bit)

Ubuntu 16.10 64 bit

> Which cloud storage system are you using? (eg Google Drive)
Google Drive
> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

rclone sync

> A log from the command with the `-v` flag (eg output from `rclone -v copy /tmp remote:tmp`)

> "Google Photos/2016/IMG_1297.JPG: corrupted on transfer: MD5 hash differ "c2ba623ffe6df003112f99e72f029c0c" vs "2ba5bafa4a7b8d080cd41764a68df806"

logging with -v 

gives the following for this file:

> 2016/11/08 15:14:13 Google Photos/2016/IMG_1297.JPG: Removing failed copy

I get similar issues with about 6 other files, all images.

Repeating the transfer yields the same errors.

**Comment by ncw** [comment]
So you don't have any duplicate files any more...

This looks like there has been a data corruption somewhere - Google's MD5 hash they stored when they stored the picture doesn't match the MD5 hash rclone calculates when it downloads the picture.

If I implement the `--ignore-checksum` flag from #793 then you would be able to download the files at least and see how corrupted they are.  It might be worth trying to download them via the web interface and have a look at them.

**Comment by ncw** [comment]
Can you try this which implements the --ignore-checksum command?

http://pub.rclone.org/v1.35-15-g82742f5-ignore-checksum%CE%B2/

**Comment by ncw** [comment]
I've merged this to master for the 1.36 release

Here is the beta - http://beta.rclone.org/v1.35-62-g9d331ce/ (uploaded in 15-30 mins)
