### ISSUE TITLE
limit checksum i/o

### ISSUE THREAD

**Issue by jxer** [ncw/rclone#864]
is there a way to limit how hard rclone is hitting the disks, im get errors during huge checks.

can i reduce its priority?

**Comment by ncw** [comment]
You can use standard linux tools to help like this (put in a shell script).

```
renice 19 $$
ionice -c 3 -p $$
rclone ....
```

What is the command line of the rclone command you are using?

**Comment by jxer** [comment]
i am using ionice -c2 n7 giving that a shot, the issue is my nfs mount, under heavy io it starts setting the folders and files to owner nobody, which starts breaking my applications..., ticket can be closed

**Comment by ncw** [comment]
:-(  I have had lots of horrible things go wrong with NFS in the past so I can't say I trust it any more!
