### ISSUE TITLE
member must have length less then 280

### ISSUE THREAD

**Issue by jxer** [ncw/rclone#865]
rclone 1.3.4
debian 8.3
encfs 1.9.1 per fil vectoring and block32 for case insensative

failed to satisfy constraint: Member must have length less than or equal to 280","code":""

are the file names too long?

**Comment by ncw** [comment]
This is a duplicate of #762 most likely.

I suspect you are using crypt where the file names can become too long to fit in amazon's limits.

**Comment by jxer** [comment]
yes, im using encfs, i renamed some folders, im hoping that is the issue, and not the file names themself
