### ISSUE TITLE
log enhancement: Include a thread number in verbose output

### ISSUE THREAD

**Issue by calisro** [ncw/rclone#866]
It would be good if as part of the output, we also include which thread is doing what.  Would help in debugging timelines in files.  Example:

2016/11/09 10:07:33 : File.Open
2016/11/09 10:07:35 : ReadFileHandle.Release OK
2016/11/09 10:07:35 : File.Open
2016/11/09 10:07:37 : ReadFileHandle.Release OK
2016/11/09 10:07:37 : File.Open
2016/11/09 10:07:38 : ReadFileHandle.Read size 16384 offset 0
2016/11/09 10:07:38 : ReadFileHandle.Read size 32768 offset 16384
2016/11/09 10:07:38 : ReadFileHandle.Read size 65536 offset 49152
2016/11/09 10:07:39 : ReadFileHandle.Read size 131072 offset 114688
2016/11/09 10:07:39 : ReadFileHandle.Read size 131072 offset 245760
2016/11/09 10:07:39 : File.Attr
2016/11/09 10:07:39 : ReadFileHandle.Read size 4096 offset 314191872
2016/11/09 10:07:39 : ReadFileHandle.seek from 376832 to 314191872
2016/11/09 10:07:40 : File.Attr
2016/11/09 10:07:40 : ReadFileHandle.Read size 131072 offset 376832
2016/11/09 10:07:40 : ReadFileHandle.seek from 314195200 to 376832
2016/11/09 10:07:41 : ReadFileHandle.Read size 131072 offset 507904
2016/11/09 10:07:42 : File.Attr
2016/11/09 10:07:42 : ReadFileHandle.Read size 131072 offset 638976

Here there are 3 open files.  If each line after the time had the thread, we could see what was going on during the playback of this file to assist in debugging.  We can match events later in the log with earlier entries.

2016/11/09 10:07:33 : (1) File.Open
2016/11/09 10:07:35 : (1) ReadFileHandle.Release OK
2016/11/09 10:07:35 : (2) File.Open
2016/11/09 10:07:37 : (2) ReadFileHandle.Release OK
2016/11/09 10:07:37 : (3) File.Open

**Comment by ncw** [comment]
That would depend on what info rclone gets from FUSE I suspect.  I'll have a think...

**Comment by calisro** [comment]
Closing this as I dont think its really needed any longer.
