### ISSUE TITLE
New "feature" Windows: Ignore directory based junction points just deleted 80GB of my stuff

### ISSUE THREAD

**Issue by danzig666** [ncw/rclone#867]
When filing an issue, please include the following information if possible as well as a description of the problem.  Make sure you test with the [latest beta of rclone](http://rclone.org/downloads/).

If you've just got a question then please use the [rclone forum](https://forum.rclone.org/) instead of filing an issue.

> What is your rclone version (eg output from `rclone -V`)
v1.34

> Which OS you are using and how many bits (eg Windows 7, 64 bit)
Windows 10 x64

> Which cloud storage system are you using? (eg Google Drive)
Google Drive

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone sync X:\ goo:X/ --log-file=goos_syncx%CDate%.log --bwlimit=2500k --size-only --exclude-from "exclude.txt" --drive-use-trash

Yesterday updated rclone to version 1.34, run my automated sync job, then realized that it trashed all files in my linked folder (junction to another drive).
I _could_ restore them from the Google Drive trash, but probably it would take longer than upload them again, as the trash restore function is kinda broken in drive (there were tens of thousand of files).

**Comment by ncw** [comment]
I'm sorry to hear that :-(

Just so I've got things straight
  * You used rclone 1.33 to upload files to drve using `rclone sync`
  * Somewhere in the directory tree there was a junction point to another drive
  * When you upgraded to 1.34 you ran the upload again, however
  * rclone ignored the junction point and deciding all the files were missing deleted all the files under it on Google Drive

is that correct?

I'm sorry that was an unexpected consequence of ignoring Junction points.  I didn't think rclone could read  junction points at all, but I'm obviously wrong about that.

What behaviour do you think rclone should have with Junction points?

**Comment by danzig666** [comment]
No harm done, already reuploaded everything (with version 1.33) :)
You got it right, it happened exactly the way you described it.
All versions prior 1.34 traversed directory junctions. I know that, because I use them a lot.
My suggestion is that rclone by default should treat junctions just as before (like directories). You could add an option to skip junction points.

**Comment by ncw** [comment]
What would you think about an option to not skip junction points?

As far as I understand it junction points are kind of like symlinks under unix.  `rsync` skips symlinks by default and so does `rclone`, but there is an option to allow `rsync` to follow symlinks.  I'm planning to implement that option `-L` in #40 for the next release.  It would seem to make sense to me to make `-L` mean follow junction points under Windows.

You'd then restore the v1.33 behaviour with `rsync -L`.

BTW How do you make your junction points?  I need to learn how to do it so I can understand them better!

**Comment by danzig666** [comment]
I'm ok with any option that makes it possible to sync my junctions :)

Junction points in windows are indeed very similar to unix symlinks, with a few caveats [explained here](http://superuser.com/questions/343074/directory-junction-vs-directory-symbolic-link). 
The real difference is usage adoption. Linux users understand (mostly) what symlinks are, and use them regularly, while very few windows users use symlinks/junctions deliberately. Windows itself has many junctions, just look at all the hidden junction points in the  `C:\Users\<username>` directory.

Creating junctions is easy:
`mklink /J c:\target d:\source` 

Another interesting use of windows symlinks is something like this (this one creates a directory hard link):
`mklink /d "c:\folder" "\\nas\e\folder"`

One more thing I discovered while testing symlinks/junctions:

You can also create symlinks to files in windows:
`mklink  D:\Temp\rclone\test.doc C:\Download\test.doc` 

Tried uploading this symlink with `rclone` 1.33:
`rclone copy D:\Temp\rclone\ goo:/test/link/ -v`
[Resulting log on pastebin](http://pastebin.com/4KZhgKAw)

Also tried it with `rclone` 1.34:
[Resulting log on pastebin](http://pastebin.com/kFaAFAgb)

**Comment by ncw** [comment]
`-L` is now implemented, so I'm closing this issue.
