### ISSUE TITLE
support XDG_CONFIG_HOME

### ISSUE THREAD

**Issue by legrostdg** [ncw/rclone#868]
I would be great to have rclone use $XDG_DATA_HOME/rclone/config, and then $HOME/.rclone.conf as a fallback.

**Comment by ncw** [comment]
I read from https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html that $XDG_CONFIG_HOME is probably what is required.

> $XDG_CONFIG_HOME defines the base directory relative to which user specific configuration files should be stored. If $XDG_CONFIG_HOME is either not set or empty, a default equal to $HOME/.config should be used.

That would fulful the request I've had in the past to get the config file into the `.config` dir.

**Comment by legrostdg** [comment]
Woops, you're absolutely right: I meant $XDG_CONFIG_HOME/rclone/config

**Comment by ncw** [comment]
Does anyone know what macOS does...  Is the XDG convention sensible here?

**Comment by legrostdg** [comment]
I don't think it is. https://stackoverflow.com/questions/3373948/equivalents-of-xdg-config-home-and-xdg-data-home-on-mac-os-x#5084892

**Comment by ncw** [comment]
This is now done!  See this beta

http://beta.rclone.org/v1.35-44-g8068ef9/ (uploaded in 15-30 mins)
