### ISSUE TITLE
Keep AUTH token with Swift

### ISSUE THREAD

**Issue by stradling** [ncw/rclone#869]
rclone 1.33-DEV, CentOS 6.8 (64 bit), Swift

The config file password is needed too prolifically. It's a great thing and one of the prime reasons that rclone is so great -- but it's also needed for rclone -V. Operations that don't require access to the password would benefit from some sort of .rclone_tmp.conf file that's created on the fly with some sort of expiration and without any of the plaintext passwords.

Specifically in the swift backend, it would be wonderful to be able to keep the AUTH_ token from Swift to allow passwordless operations over the (default) 24 hours that such a token works. Once that time is up, the .rclone_tmp.conf file is deleted or has the AUTH_ token removed, and the password for the .rclone.conf file is once again required.

This might also be useful for other backends -- I haven't given them much thought.

Thanks! Great product.

**Comment by ncw** [comment]
I see what you are getting at I think.  Did you have a specific use case in mind?

**Comment by stradling** [comment]
Since rclone is so useful, I find myself doing repeated operations with it (file uploads and deletions, manipulations, etc). At each touch, I have to re-enter the password for the config… not an incentive to keep an appropriately complex password. :)

The token can last (by default) a full day without needing the password again, so it would be useful to store that and have rclone able to manage authentication using the token.

Useful docs on how that works are here:

https://www.swiftstack.com/docs/cookbooks/swift_usage/auth.html <https://www.swiftstack.com/docs/cookbooks/swift_usage/auth.html>

Thanks for taking a look at this!

Cheers,

Alden

**Comment by ncw** [comment]
>  At each touch, I have to re-enter the password for the config… not an incentive to keep an appropriately complex password. :)

Did you know you can put the password in an environment variable?

Put this into a file (called `set-rclone-password` say)

```sh
#!/bin/echo Source this file don't run it

read -s RCLONE_CONFIG_PASS
export RCLONE_CONFIG_PASS
```

Then source it before you want to use rclone

```
$ . ~/bin/set-rclone-password 
$ echo $RCLONE_CONFIG_PASS
potato
```

**Comment by stradling** [comment]
That's very helpful-- I wasn't aware. :) Thanks.

**Comment by ncw** [comment]
I've put the shell magic for password reading in the docs now, so I'm going to close this issue
