### ISSUE TITLE
Amazon Drive change URLs?

### ISSUE THREAD

**Issue by darylstyrk** [ncw/rclone#870]
When filing an issue, please include the following information if possible as well as a description of the problem.  Make sure you test with the [latest beta of rclone](http://rclone.org/downloads/).

If you've just got a question then please use the [rclone forum](https://forum.rclone.org/) instead of filing an issue.

> What is your rclone version (eg output from `rclone -V`)

> Which OS you are using and how many bits (eg Windows 7, 64 bit)

> Which cloud storage system are you using? (eg Google Drive)

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

> A log from the command with the `-v` flag (eg output from `rclone -v copy /tmp remote:tmp`)

**Comment by darylstyrk** [comment]
Sorry that launched a bit early. I've a 600GB transfer in progress which has stopped with an unexpected timeout. Disregard for now I was trying to build a report but inadvertently sent this without any data. I'm looking into it and will update if needed.

Regards,

**Comment by ncw** [comment]
OK I'll close this one, then you can open a new one when you have all the details.
