### ISSUE TITLE
Allow repeated --include and --exclude flags now that pflags supports it

### ISSUE THREAD

**Issue by ncw** [ncw/rclone#875]
pflags now supports multiple flags so we can have multiple copies of each flag.

This still won't make it as flexible as rsync where you can have include, exclude, include, exclude - this will be parsed as include, include, exclude, exclude but it is probably worth doing.

**Comment by diamondsw** [comment]
Yes, I think this would address what I'm trying to do over in https://forum.rclone.org/t/best-way-to-use-multiple-filters-from-a-script/240/2 . The suggestion of a temp file was basically where I was at, although that involved a bunch of mess and cleanup. I'll look forward to a beta! :)

**Comment by diamondsw** [comment]
Alternatively, if there was some way to specify multiple patterns in a single argument to --exclude, --filter, etc, then I wouldn't necessarily need to pass in multiple arguments. But given that rsync already does it with multiple arguments it's probably best to copy that as people will expect some level of similarity (within reason).

**Comment by ncw** [comment]
I have fixed this in http://beta.rclone.org/v1.34-60-g2656a0e/ (uploaded in 15-30 mins)
