### ISSUE TITLE
ACD FUSE change default --max-read-ahead

### ISSUE THREAD

**Issue by scoopydude2002** [ncw/rclone#877]
Decided to add this to track adjustment to --max-read-ahead per discussion in the forum. As per forum user @calisro this value may need to be dynamically calculated and can be overwritten with a flag.

**Comment by ncw** [comment]
From my investigations ` --max-read-ahead` is pretty useless - the kernel caps it at 128k which is the default value so I can't see adjusting it dynamically being helpful.

Please re-open if you have some evidence otherwise!
