### ISSUE TITLE
Using sync with drive does not delete erased dirs in source from dest 

### ISSUE THREAD

**Issue by Asta1986** [ncw/rclone#88]
Using rclone-v1.17-linux-amd64 with google drive if I sync a folder with a sub-folder that contains a file and then delete the sub-folder from the source directory and sync again the file within the sub-folder is deleted but the empty directory remains in google drive. Maybe it is something I'm not doing right, anyway great job!

**Comment by ncw** [comment]
This is a known problem - see the bugs page: http://rclone.org/bugs/

Unfortunately object storage systems don't really understand directories, so it is difficult to manage them properly.  It is obvious when to create them, but not so obvious when to remove them!

**Comment by ncw** [comment]
I've made another issue to track the feature necessary here #100
