### ISSUE TITLE
Support configuration of S3 part size

### ISSUE THREAD

**Issue by jamshid** [ncw/rclone#880]
> What is your rclone version (eg output from `rclone -V`)

1.33-DEV

> Which OS you are using and how many bits (eg Windows 7, 64 bit)

OSX 10.11.6

> Which cloud storage system are you using? (eg Google Drive)

S3 compatible

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

rclone copy bigfile remote:tmp

Would be nice if I could configure the part size for S3 multipart uploads. Currently it defaults to MinUploadPartSize.

https://github.com/ncw/rclone/blob/cb40511807a03e922bd3fdd477fa41191bbfa62a/s3/s3.go#L884

**Comment by ncw** [comment]
The code adaptively increases it so that it can upload something without too many parts - what problems are you seeing with that?

**Comment by jamshid** [comment]
Sorry I should have been clear -- I'm not seeing any problems with current behavior, would just like to be able to configure the part size to see its effect on performance against an S3-compatible storage system. The part size affects the part writes, the "complete" operation, and performance of the final stream.
Maybe I'll try making the code changes and submit a pull request. 
Thanks for rclone, btw, it's awesome.

**Comment by ncw** [comment]
I see.  You could add a new flag `--s3-min-part-size` say which defaults to the current value and leave the increasing the part size algorithm alone.

**Comment by jamshid** [comment]
Sorry I haven't made a pull request yet... 
I added a `part_size` config file option but will rename to `s3_min_part_size` and add a corresponding command-line flag. And a test.
```
diff --git s3/s3.go s3/s3.go
index 0467272..60a2b27 100644
--- s3/s3.go
+++ s3/s3.go
@@ -231,6 +231,7 @@ type Fs struct {
 	locationConstraint string           // location constraint of new buckets
 	sse                string           // the type of server-side encryption
 	storageClass       string           // storage class
+        partSize           int              // desired part size, configured or command-line
 }
 
 // Object describes a s3 object
@@ -384,6 +385,7 @@ func NewFs(name, root string) (fs.Fs, error) {
 		locationConstraint: fs.ConfigFileGet(name, "location_constraint"),
 		sse:                fs.ConfigFileGet(name, "server_side_encryption"),
 		storageClass:       fs.ConfigFileGet(name, "storage_class"),
+                partSize:           fs.ConfigFileGetInt(name, "part_size"),
 	}
 	f.features = (&fs.Features{ReadMimeType: true, WriteMimeType: true}).Fill(f)
 	if *s3ACL != "" {
@@ -897,7 +899,12 @@ func (o *Object) Update(in io.Reader, src fs.ObjectInfo) error {
 		u.Concurrency = 2
 		u.LeavePartsOnError = false
 		u.S3 = o.fs.c
-		u.PartSize = s3manager.MinUploadPartSize
+                if o.fs.partSize > 0 {
+                        u.PartSize = int64(o.fs.partSize)
+                } else {
+                        u.PartSize = s3manager.MinUploadPartSize
+                }
+                fs.Logf(o, "Using PartSize %d", u.PartSize)
 		size := src.Size()
 
 		// Adjust PartSize until the number of parts is small enough.
```

**Comment by jamshid** [comment]
Closing as it looks like this feature was implemented as `--s3-chunk-size`. I don't know if it's only available via command-line or can also be set in config file. lhttps://github.com/ncw/rclone/issues/2203

**Comment by ncw** [comment]
You can set this as a flag or an environment variable. Soon you'll be able to set it on the config as I'm unifying the config methods shortly.
