### ISSUE TITLE
Upload Speed Bottleneck Because Of Encryption?

### ISSUE THREAD

**Issue by tharrisone** [ncw/rclone#882]
> What is your rclone version (eg output from `rclone -V`)
rclone v1.33-66-g2e20a0f-acd-timeoutβ

> Which OS you are using and how many bits (eg Windows 7, 64 bit)
64 Bit Ubuntu

> Which cloud storage system are you using? (eg Google Drive)
Amazon Drive/Google Cloud Drive

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
./rc -v copy /home/klepto/downloads/ ACDCEE:DL --transfers=40

When I uploaded around 1.4 TB of data to Amazon Drive or Google Cloud Storage it was always at 35mb/s but my current bandwidth has been tested to be at 300mb/s. So I thought that using the crypto might be limiting my bandwidth.

**Comment by Trentflix** [comment]
I'm uploading on average 650+mb/s to an Encrypted Google cloud and 450+ mb/s on Encrypted Amazon Cloud. I never noticed a difference on upload speeds between encrypted/un-encrypted transfer (all through the various 1.33 betas and 1.34, tested on Ubuntu and Windows).

**Comment by ncw** [comment]
Note that rclone measures bandwidth in MByte/s whereas line speeds are usually quoted in Mbit/s.

35 MByte/s is about 280 Mbit/s so I think it is probably doing OK!

**Comment by tharrisone** [comment]
Wow, that totally threw me off. I can't believe I didn't notice that.
Ok I'm getting old :P

I'll close this one in embarrassment.
