### ISSUE TITLE
[Feature Request] track file movement thru folders to prevent needless reuploading

### ISSUE THREAD

**Issue by jschwalbe** [ncw/rclone#888]
I propose that rclone track files as they move in and out of folders rather than deleting the file and then reuploading. 

## An illustrative example.
/main/Directory-1/Large-File.mp4

_From whatever OS interface you prefer, move Large-File.mp4 to Directory-2/_

```
$ mv /main/Directory-1/Large-File.mp4 /main/Directory-2/
$ rclone sync /main/ gdrive:/main/ (or something like that)

```
Currently this causes rclone to _delete_ the file from gdrive:/main/Directory-1 and then _reupload_ the same file (unchanged) to gdrive:/main/Directory-2 when really all that needs to happen is to simply "move" it.  The result is quite a bit of extra wasted upload bandwidth.

## How could this be done?
When a sync command is initiated, rclone should firstly determine which files are changing and then determine if any of the files are simply _moving_ rather than _completely missing_. A file match can be determined either by _filename_ and/or _md5_ hash, etc, or I'm sure some better more briliant method to be listed below. If the set criteria matches, then instead of deleting/reuploading, rclone just issues a `move` command within the service in play.

**Comment by ncw** [comment]
Nice idea!

**Comment by Wob76** [comment]
+1 Sounds like a solid improvement.

**Comment by jschwalbe** [comment]
I've been trying to figure out how to do this. I'm not a coder by trade but I have coded in the past - php, C++, java. Can anyone give me a point of reference to start? I'd like to try to contribute but doesn't seem like this might be a great first "let's code in go" foray.

**Comment by ncw** [comment]
@jschwalbe This would involve tweaking the sync engine in `fs/sync.go`.  I'd control this with an additional flag - `--track-renames` say.

If this flag was set, in [run()](https://github.com/ncw/rclone/blob/master/fs/sync.go#L415) I'd make sure both source and destination were traversed first (like the deleteBefore option).  Once traversed I'd do a separate phase doing the renames, adjusting the destination map on successful rename, then carry on doing the sync as usual.  This would need a unit test or two as I try to keep the core syncing routines fully covered.

Not the easiest first project, but it is of relatively narrow scope so not too bad.

Note: not all the remotes can do a server side rename (or a server side copy + delete) so you probably would want to ignore this option on those remotes as the move primitive would download and upload the file which would be less efficient than just uploading the new one. 

If you want to spend a bit of time studying go then [the go tour](https://tour.golang.org) is an excellent place to start.

**Comment by jschwalbe** [comment]
@ncw thanks for the guidance (and the great app)! What seemed like what would be a fairly simple task has become quite complicated for a newbie. I've spent probably 3-4 hours just trying to wrap my head around this project and I think it's safe to say that this is out of my league. :) 

### Here's the logic I can come up with:
1. add a --track-renames flag handler
2. within sync, run() will need to generate a list of src files and hash them
3. then we'd need to generate a list of files that are flagged to be deleted and get the hash for those
4. compare the two lists and if a hash/filesize/etc matches, then add it to a pair list
5. for each pair, skip the delete for that file and skip the upload for the matching file, and instead issue a move command

That's about as far as I can take this though. Happy to provide debugging support in the process though.

**Comment by ncw** [comment]
@jschwalbe no worries!  There are some easier issues if you want to help with something else.  Take a look through https://github.com/ncw/rclone/milestone/22 and see if anything catches your eye - or any other issue!

**Comment by bobbintb** [comment]
nice. looking forward to this.

**Comment by bep** [comment]
I can take a stab on implementing a PR for this. 

I have just uploaded my Lightroom RAW files collection to Google Drive, and I notice that most of the files badly needs better names ...

**Comment by ncw** [comment]
@bep that would be great!

This will involve adjusting fs/sync.go which is quite intricate, but it is fully tested.

What I'd do is make sure that the source map and dest map get loaded into memory in the `run` method (which will make it incompatible with `--no-traverse` - you want to follow the `--delete-before` code path).  When both maps are loaded then do the rename detection in a separate pass, removing things from the src and dst map when you do a successful rename.  Then fall through into the sync/copy/move proper.

The actual moves you want to do with the `Move` function.  This will fall back to download/upload if the remote doesn't implement `Move` or `Copy` which isn't ideal so if the remote doesn't support `Move` or `Copy` you probably want to ignore the `--track-rename` flag completely.

**Comment by bep** [comment]
Thanks for the tips -- I think I now understand the implementation, I may have some challenges writing tests for this, but I think I will just get it working first.

**Comment by ncw** [comment]
@bep let me know if you need any more pointers. Nick

**Comment by bep** [comment]
https://github.com/ncw/rclone/pull/963

**Comment by ncw** [comment]
Please find a beta with this in here: http://beta.rclone.org/v1.35-07-gf1221b5/ (uploaded in 15-30 mins)

**Comment by vesper8** [comment]
@ncw 

very interesting development that will hopefully save a lot of time and bandwidth when moving folders around.

However I am currently having a hell of a time getting a sync to work between my local folder and dropbox.. it does not delete old files.. and constantly runs into trouble with "Failed to grab locks".

I tried using the --delete-before flag in the hope that it would clean up all those folders that no longer exist on the source.

Now that I'm using the latest beta which includes this new feature, I am wondering what are the consequences of using it in combination with --delete-before ? 

Will it know not to delete files that have been simply relocated elsewhere if I use the --delete-before ?

**Comment by Techrocket9** [comment]
Did a working version of this feature make it into 1.36? I'm getting `ignoring --track-renames as the source and destination do not have a common hash`, and with a -v I see that it's reuploading and deleting instead of doing a move. Source system is Windows Server 2016 on a REFS volume. Remote is either of ACD or Google Drive run through crypt. According to the [table](http://rclone.org/overview/#optional-features), both ACD and Google Drive support Move and DirMove.

**Comment by ncw** [comment]
@Techrocket9 yes this made it into the release.  Unfortunately crypt doesn't support hashes :-(

**Comment by olanmatt** [comment]
@ncw Could you elaborate on this? Does `--track-renames` not work with encrypted remotes? If so, what is the limitation with hash support?

Thanks!

**Comment by ncw** [comment]
@olanmatt yes that is correct, `--track-renames` doesn't work with encrypted remotes :-(

**Comment by vesper8** [comment]
So Dropbox has encrypted remotes right? Sorry for not knowing.. but it seems track-rename isn't working on Dropbox so I assume it does

**Comment by Bazzu85** [comment]
Hi, any chance to make --track-renames work with encrypted remotes?

**Comment by ncw** [comment]
> Hi, any chance to make --track-renames work with encrypted remotes?

This could be done using the same mechanism that cryptcheck uses, so using the hash(encrypted_file).  To calculate this for a local file rclone has to download the nonce from the remote file, then encrypt the local file with the nonce and hash it on the fly.  This would work for --track-renames purpose.

If you please make a [new issue on github](https://github.com/ncw/rclone/issues/new) about this then I'll take a look!

**Comment by Bazzu85** [comment]
Done, thx

**Comment by dandv** [comment]
@Bazzu85 Linking to issues is harddd... #2721.

**Comment by Bazzu85** [comment]
> @Bazzu85 Linking to issues is harddd... #2721.

??
