### ISSUE TITLE
Error: Failed to create file system: connect: network is unreachable

### ISSUE THREAD

**Issue by rindeal** [ncw/rclone#889]
The problem is, rclone (Go resolver) issues A and AAAA queries at the same time and then tries to connect to the address from whichever response comes first, without falling back to the other one if the first one fails. Luckily A comes first most of the time, but not always.

Disabling IPV6 for all interfaces didn't help, I haven't try disabling the whole IPv6 stack, because I need it from time to time. My current workaround is teredo.

remote type: Google Drive
version: 1.33
OS: linux 4.1.35

command:
```
rclone copy ...
```

strace:
```
[pid 31637] socket(AF_INET, SOCK_STREAM, IPPROTO_TCP) = 3
[pid 31637] socket(AF_INET6, SOCK_STREAM, IPPROTO_TCP) = 3
[pid 31637] setsockopt(3, SOL_IPV6, IPV6_V6ONLY, [1], 4) = 0
[pid 31637] bind(3, {sa_family=AF_INET6, sin6_port=htons(0), inet_pton(AF_INET6, "::1", &sin6_addr), sin6_flowinfo=htonl(0), sin6_scope_id=0}, 28) = 0
[pid 31637] socket(AF_INET6, SOCK_STREAM, IPPROTO_TCP) = 4
[pid 31637] setsockopt(4, SOL_IPV6, IPV6_V6ONLY, [0], 4) = 0
[pid 31637] bind(4, {sa_family=AF_INET6, sin6_port=htons(0), inet_pton(AF_INET6, "::ffff:127.0.0.1", &sin6_addr), sin6_flowinfo=htonl(0), sin6_scope_id=0}, 28) = 0
[pid 31637] socket(AF_INET, SOCK_DGRAM|SOCK_CLOEXEC|SOCK_NONBLOCK, IPPROTO_IP) = 3
[pid 31637] setsockopt(3, SOL_SOCKET, SO_BROADCAST, [1], 4) = 0
[pid 31637] connect(3, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("<DNS1>")}, 16) = 0
[pid 31637] getsockname(3, {sa_family=AF_INET, sin_port=htons(49852), sin_addr=inet_addr("<MY_IPV4>")}, [112->16]) = 0
[pid 31641] socket(AF_INET, SOCK_DGRAM|SOCK_CLOEXEC|SOCK_NONBLOCK, IPPROTO_IP <unfinished ...>
[pid 31637] getpeername(3, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("<DNS1>")}, [112->16]) = 0
[pid 31641] <... socket resumed> )      = 5
[pid 31641] setsockopt(5, SOL_SOCKET, SO_BROADCAST, [1], 4) = 0
[pid 31641] connect(5, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("<DNS1>")}, 16) = 0
[pid 31641] getsockname(5, {sa_family=AF_INET, sin_port=htons(58894), sin_addr=inet_addr("<MY_IPV4>")}, [112->16]) = 0
[pid 31641] getpeername(5, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("<DNS1>")}, [112->16]) = 0
strace: Process 31642 attached
strace: Process 31643 attached
[pid 31641] socket(AF_INET6, SOCK_STREAM|SOCK_CLOEXEC|SOCK_NONBLOCK, IPPROTO_IP) = 3
[pid 31641] setsockopt(3, SOL_IPV6, IPV6_V6ONLY, [0], 4) = 0
[pid 31641] setsockopt(3, SOL_SOCKET, SO_BROADCAST, [1], 4) = 0
[pid 31641] connect(3, {sa_family=AF_INET6, sin6_port=htons(443), inet_pton(AF_INET6, "2a00:1450:4014:80d::200a", &sin6_addr), sin6_flowinfo=htonl(0), sin6_scope_id=0}, 28) = -1 ENETUNREACH (Network is unreachable)
2016/11/17 10:54:33 Failed to create file system for "<account>:<dir>/": couldn't read info about Drive: Get https://www.googleapis.com/drive/v2/about?alt=json: dial tcp [2a00:1450:4014:80d::200a]:443: connect: network is unreachable
```

**Comment by ncw** [comment]
You might want to check out using one of these

```
export GODEBUG=netdns=cgo   # force cgo resolver
```

The default with the precompiled binaries is the go resolver.  I'm not 100% sure trying to use the cgo resolver will work with the precompiled binaries so you might have to compile from source to try that.

This issue looks like essentially what you are reporting: https://github.com/golang/go/issues/17448

If so it is scheduled for go 1.9 fix which should be out in ~7 months.

You can also try configuring your preference in `/etc/gai/conf` (might not work with the go resolver).

**Comment by ncw** [comment]
As go1.9 has been released, I'm now compiling rclone with it.

You should find this issue is fixed in [the latest beta](https://beta.rclone.org).

I'm going to close this issue now, please re-open if you are still seeing the issue.

**Comment by victoriastuart** [comment]
`2018/10/28 11:29:42 ERROR : apps/eigen/eigen-eigen-b30b87236a1b/build_dir/doc/snippets/CMakeFiles/compile_Cwise_less.dir/DependInfo.cmake: Failed to copy: upload failed: Post https://content.dropboxapi.com/2/files/upload: dial tcp [2620:100:6016:8::a27d:108]:443: connect: network is unreachable`

Arch Linux: `community/rclone 1.43.1-1 [installed]`

**Comment by ncw** [comment]
@victoriastuart did you try disabling IPv6 since it doesn't seem to work for you?

**Comment by victoriastuart** [comment]
No; that's not trivial (or recommended), is it? Recommendations?

https://wiki.archlinux.org/index.php/IPv6#Disable_IPv6 >> "Note: The Arch kernel has IPv6 support built in directly, therefore a module cannot be blacklisted."

**Comment by ncw** [comment]
> No; that's not trivial (or recommended), is it? Recommendations?

I'm just saying rclone is trying to use your IPv6 since your computer supports it and it is configured.  This is the correct thing to do I think.  However your IPv6 isn't working which isn't rclone's fault.

If your IPv6 connection is flakey somehow then disabling IPv6 on your computer might be the best solution.

I normally do this by [editing /etc/gai.conf](https://community.rackspace.com/products/f/public-cloud-forum/5110/how-to-prefer-ipv4-over-ipv6-in-ubuntu-and-centos) - I'm not 100% sure this will work with rclone but might be worth a try.

**Comment by victoriastuart** [comment]
Thank you for your response (appreciated)!  You are correct: I *thought* I had IPv6 access, but in fact it's only IPv4.  :-(

I'm contacting my ISP re: that issue, and will report back here once I hear back from them.

**Comment by tiotobing** [comment]
I want to ask, where between getpeername() / getsockname() which is the source and destination IP?

`**getsockname(3, {sa_family=AF_INET, sin_port=htons(49852), sin_addr=inet_addr("<MY_IPV4>")}, [112->16]) = 0
 
getpeername(3, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("<DNS1>")}, [112->16]) = 0 [pid 31641] <... socket resumed> ) = 5**`

**Comment by ncw** [comment]
> I want to ask, where between getpeername() / getsockname() which is the source and destination IP?

getpeername gets the remote address, getsockname gets the local one I believe.

**Comment by tiotobing** [comment]
So , 
The Source is 
getsockname(3, {sa_family=AF_INET, sin_port=htons(49852), sin_addr=inet_addr("<MY_IPV4>")}, [112->16]) = 0

And 

Destination is 
getpeername(3, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("<DNS1>")}, [112->16])=0

Is it true?

**Comment by ncw** [comment]
> So ,
> The Source is
> getsockname(3, {sa_family=AF_INET, sin_port=htons(49852), sin_addr=inet_addr("<MY_IPV4>")}, [112->16]) = 0
> 
> And
> 
> Destination is
> getpeername(3, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("")}, [112->16])=0
> 
> Is it true?

Yes that is right I think.
