### ISSUE TITLE
Empty Folders

### ISSUE THREAD

**Issue by dav1303** [ncw/rclone#89]
Hi

Can you add an option to create empty folders

Regards

**Comment by ncw** [comment]
It might be possible to manage folders better for any cloud storage systems which understand the concept of folders (Drive is the only one at the moment) through use of some optional interfaces.

**Comment by dav1303** [comment]
Hi

Sorry but i don't understand

Regards

**Comment by ncw** [comment]
@dav1303 managing folders would require changing the internals of rclone.  It is possible to make it work with Google Drive, but not with Amazon S3 for example, so it would require a bit of thought.

**Comment by dav1303** [comment]
Hi Nick

Did you plan to done an update ?

Thanks

**Comment by ncw** [comment]
I've made another issue to track the feature necessary here #100
