### ISSUE TITLE
Deletion failed due to IO errors

### ISSUE THREAD

**Issue by Cadish** [ncw/rclone#893]
I've got this issue when trying to sync something: 

```
2016/11/18 20:09:04 Some/folder: Upload error detected but didn't finish upload: HTTP code 409: "409 Conflict", reponse body: {"logref":"xxxx","message":"Node with the name xxxx already exists under parentId xxxx conflicting NodeId: xxxx","code":"NAME_ALREADY_EXISTS","info":{"nodeId":"xxxx"}}
 ("409 Conflict")
...
2016/11/18 20:10:20 amazon drive root 'Some/folder': not deleting files as there were IO errors
2016/11/18 20:10:20 Attempt 1/3 failed with 4 errors and: not deleting files as there were IO errors
```

> What is your rclone version (eg output from rclone -V)
rclone v1.34

> Which OS you are using and how many bits (eg Windows 7, 64 bit)
QNAP QTS 4.2.2

> Which cloud storage system are you using? (eg Google Drive)
Amazon Cloud Drive

> The command you were trying to run (eg rclone copy /tmp remote:tmp)
rclone sync "some/folder" "ACD:/some/folder" --transfers=1 --checkers=1 -v --delete-during --exclude-from=/some/other/folder/rclone-exclude.txt --config=/some/other/folder/.rclone.conf

Could you indicate:

1. How to avoid the errors?
2. How I can ignore these errors? 

Thanks a lot!
Cadish

**Comment by ncw** [comment]
The sort of errors in your log happen. ACD gives all sorts of errors and rclone retries them.  Sometimes this involves retrying the entire sync.  Hopefully what happened is rclone retried the sync and everything was fine.

My first suggestion would be to retry the sync and see if it completes this time.

**Comment by diamondsw** [comment]
I've run into 409's most-often when there are files in the same directory with the same name, differing only by case. Amazon Drive can't store case-sensitive files.
