### ISSUE TITLE
rclone mount: implement statfs interface to show filesystem size

### ISSUE THREAD

**Issue by Stonedestroyer** [ncw/rclone#894]
When filing an issue, please include the following information if possible as well as a description of the problem.  Make sure you test with the [latest beta of rclone](http://rclone.org/downloads/).

If you've just got a question then please use the [rclone forum](https://forum.rclone.org/) instead of filing an issue.

> What is your rclone version (eg output from `rclone -V`)
rclone v1.34
> Which OS you are using and how many bits (eg Windows 7, 64 bit)
Debian 8 Jessie 64 bit
> Which cloud storage system are you using? (eg Google Drive)
Google Drive
> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone mount gdrive: /mnt/gdrive --allow-other
> A log from the command with the `-v` flag (eg output from `rclone -v copy /tmp remote:tmp`)

My issue is that rclone needs a max size on mount much like acd_cli does it. With no max size samba reports that there is errors due to the way df works on the mount. 

http://i.imgur.com/N7oTw4o.png

**Comment by ncw** [comment]
Do you need rclone to show non zero info on `df`?

```
$ rclone mount acd: ~/mnt/tmp/
$ df -h ~/mnt/tmp/
Filesystem      Size  Used Avail Use% Mounted on
acd:            0.0K  0.0K  0.0K    - ~/mnt/tmp
```

I'll have to make some stuff up to go in there - I don't want to do a full filing system scan to read the info.  What is important?  That there is some free space? That there is some space used?  I could make it return 1 MB used and 1 PB free or something like that.

What is the error that samba returns?

Note to self:  This requires implementing the statfs interface

```go
type FSStatfser interface {
	// Statfs is called to obtain file system metadata.
	// It should write that data to resp.
	Statfs(ctx context.Context, req *fuse.StatfsRequest, resp *fuse.StatfsResponse) error
}
```

**Comment by ncw** [comment]
...also what does acd_cli return for `df`?

**Comment by Stonedestroyer** [comment]
```
ACDFuse         100T  3.5T   97T   4% /mnt/amazon
```
This is what acd_cli returns, for samba the value needs atleast to be free space left I don't think it matters how much space. Samba returns error when I move files such as 
Additional 158 MB space required to move this file and so on. I think making it return 1 PB and 1 MB used will be fine.

**Comment by jkaberg** [comment]
acd_cli gets the used amount right cause it keeps tracks of all files and attribues on the drive in an local db, hence the ```acd_drive sync``` command

**Comment by ncw** [comment]
I've fixed this to return a static output

Find it in this beta http://beta.rclone.org/v1.34-23-gc41b67e/ (will be uploaded in 15-30 mins)

```
$ df /mnt/tmp/
Filesystem         1K-blocks  Used     Available Use% Mounted on
acd:           1099511627776     0 1099511627776   0% /mnt/tmp
$ df -h /mnt/tmp/
Filesystem      Size  Used Avail Use% Mounted on
acd:            1.0P     0  1.0P   0% /mnt/tmp
$ df -i /mnt/tmp/
Filesystem         Inodes IUsed      IFree IUse% Mounted on
acd:           1000000000     0 1000000000    0% /mnt/tmp
```

**Comment by aus** [comment]
For anyone having trouble using [mergerfs](https://github.com/trapexit/mergerfs) and rclone, you'll need either this rclone fix or [this](https://github.com/trapexit/mergerfs/commit/3c5351af93ed230845d08c695604976e7b1a5e97) mergerfs fix. Otherwise, mergerfs will segfault after it finds zeros from the `statfs` on the rclone filesystem.
