### ISSUE TITLE
[Feature Request] Mount: Use file cache heuristics when reading/seeking

### ISSUE THREAD

**Issue by jkaberg** [ncw/rclone#898]
Ref https://forum.rclone.org/t/acd-fuse-mount-still-not-working-with-plex/170/22

rclone mount should be smart, and try to anticipate if an read requires huge amounts of data. That way rclone can ramp up and fetch more data wich build a temporary local cache for faster reading/seeking

Something like this scenario:

1. rclone gets an request of a chunk, and retrieves it
2. gets another request, same chunk size: retrieves it
3. rclone gets a third request and now anticipates that there will be more requests and prefetches a small amount of chunks
4. half of the small chunk size is eaten up and rclone now understands that we mean to ultimately read the entire file so it ramps up to a big cache and fetches large amounts of chunks (perhaps 3x the small cache) at a time until the end of file

this would be more dynamic, and will most likely make ```--max-read-ahead``` obsolete

**Comment by flixajki** [comment]
great suggestion

**Comment by ncw** [comment]
I think this is now covered by the cache backend.
