### ISSUE TITLE
FUSE + ACD + Plex - frequent buffering when 2 users watch the same video

### ISSUE THREAD

**Issue by scoopydude2002** [ncw/rclone#899]
Using rclone v1.34. When using FUSE + ACD + Plex, I notice that if 2 users are watching the same video it buffers very frequently. This is occurring with both crypt and without cryp. Appears easy to reproduce. Using the following mount command:

    rclone mount --max-read-ahead 200M --checkers 300 --read-only acd: /local/mnt

**Comment by ncw** [comment]
Is this still a problem with the latest beta?

**Comment by scoopydude2002** [comment]
No longer an issue with the buffer option. Can you close this issue. Thanks.
