### ISSUE TITLE
windows: files over 256 chars path

### ISSUE THREAD

**Issue by dav1303** [ncw/rclone#90]
Hi

On windows file system if a file contains on Is path more than 256 characters the file Is not created on gdrive

Regards

**Comment by ncw** [comment]
This is annoyingly difficult to fix!  Will think about it.

**Comment by klauspost** [comment]
This could maybe be fixed by converting all paths in local filesystem to UNC paths, which could also be the fix for #124, #129 and #130.

**Comment by ncw** [comment]
@dav1303 This should be all fixed in the 1.20 release.  Thank you for the report and let us know (open a new issue) if you have any more problems.

Thanks

Nick
