### ISSUE TITLE
rclone sync - failed to open source object

### ISSUE THREAD

**Issue by canonlp** [ncw/rclone#906]
I'm currently having some problems with rclone sync from one gdrive to another gdrive. 

I get "Failed to copy: failed to open source object: bad response: 403: 403 Forbidden"

Ubuntu 15.10
Rclone V1.34-Dev

rclone sync gdrive1:Stuff gdrive2:Stuff

Is this a rate limit exceeding issue? Or something else?

**Comment by canonlp** [comment]
Also errors when trying to play from plex. With my gdrive mounted.

fuse: -> [ID=0x2b] Open error=EIO: bad response: 403: 403 Forbidden

**Comment by ncw** [comment]
Likely this is because you've hit drive's rate limits.  If you want a bit it will start working again.
