### ISSUE TITLE
rclone keeps deleting my OneDrive config

### ISSUE THREAD

**Issue by hyperexpert** [ncw/rclone#908]
rclone version: 1.34
Ubuntu server: 16.04..1 LTS
OneDrive and Amazon Drive

I have both Amazon Drive and OneDrive setup in rclone. However, rclone keeps wiping out my OneDrive configuration completely! It happens very randomly. I also do have my OneDrive mounted too. The mount stays active and I can pull files from it. But, the configuration for OneDrive is all gone. 

If I do `rclone config` or look at .config.conf in my home directory, I only see Amazon Drive there.

Why does it keep forgetting my OneDrive? Will it help if I get rid of Amazon Drive and only keep OneDrive?

**Comment by hyperexpert** [comment]
Ok, this is weird! I removed all of my configured accounts and started over. Only this time, I didn't add anything else beside OneDrive. It worked good for about an hour then all of the sudden, it removed my OneDrive config and added Amazon back all by itself! Is this even possible? Could there be another config file somewhere else overwriting my config in my home directory?

**Comment by ncw** [comment]
This is almost certainly #682 - that is you've got one rclone running while you are configuring it.

Does that make sense?

**Comment by hyperexpert** [comment]
Oh got it! Makes more sense. THANK YOU so much for working on a fix for this. Once everything is configured, it shouldn't be a problem anyways. I was just thinking it had something to do with my OneDrive.
