### ISSUE TITLE
Mount drops after compiling from source.

### ISSUE THREAD

**Issue by cejpe** [ncw/rclone#912]
When filing an issue, please include the following information if possible as well as a description of the problem.  Make sure you test with the [latest beta of rclone](http://rclone.org/downloads/).

If you've just got a question then please use the [rclone forum](https://forum.rclone.org/) instead of filing an issue.

> What is your rclone version (eg output from `rclone -V`)

I was using the version that allowed writing to ACD, I've since downgraded to v1.34-23-gc41b67eβ

> Which OS you are using and how many bits (eg Windows 7, 64 bit)

Ubuntu 14.04 64bit

> Which cloud storage system are you using? (eg Google Drive)

Happens on Google Drive and ACD

The mount will drop after sometime. It started happening when I attempted to write files directly to ACD. After some time I would get I/O errors and the mount would drop. (No logs unfortunately) I decided to downgrade to the latest available beta version, but the random mount dropping issue persists. This never happened before I compiled rclone from source. Sounds like it might be a FUSE issue, any ideas?

**Comment by ncw** [comment]
Can you get a log with `-v` of this happening?

**Comment by cejpe** [comment]
The last time it dropped I remounted it with -v, and it has not dropped yet (12+ hours) which is by far the longest it has lasted since this issue began. I'm wondering if when I tried writing to ACD the mount dropped because of an I/O error and even after downgrading to a more stable version the items that I had initially planned to write to ACD were still queued so to speak, which would cause intermittent drops.

I don't know how rclone works obviously so I don't know if those transfers would have been resumed in the background somehow.

In any case, during the next drop I'll be sure to post a log. Thanks for looking into it.

**Comment by cejpe** [comment]
Mount dropped, here's a log. Nothing looks out of the ordinary to me, but you're the expert ;)

http://pastebin.com/PmM36h6a

I changed the filenames to generic ones, each unique file was given a unique name, FILENAME, FILENAME2,  and FILENAME3.

**Comment by ncw** [comment]
No there doesn't appear to be anything out of the ordinary there!

Did the `rclone mount` process die completely at that point?  Is it possible it wrote stuff to stderr which you didn't capture?

**Comment by ncw** [comment]
I'm going to assume you got this working since I haven't heard from you for a while.
