### ISSUE TITLE
Copy or sync to Google Drive created several folders with same name in same location

### ISSUE THREAD

**Issue by qnorsten** [ncw/rclone#920]
Hello, I am currently running rclone to copy an encfs --reverse mounted folder to Google drive. 
I am running rclone on a virtual ubuntu 15.05 64 bit virtual machine where the unencrypted folder is shared over network (smdb)from the windows 64 host.  Then mounted with encfs --reverse and copied to google Drive. 

The ubuntu server is needed as I could not use encfs4win with rclone as described in (https://github.com/ncw/rclone/issues/261)  

I had to cancel the transfers a few times as the drive containg the virtual hardrive file ran out of space, but eventually the transfer was complete. 

Now I ended up with two folders with the same name, in the same path in Google Drive, in some case one of the folders are empty, but in some cases some files are in one of the folders and others in the other. When I mount the drive I can only see the content of one of each folders. Is there anyway to fix this, and what might have caused it?

Here is a print screen that shows the problem. 
http://imgur.com/a/IgMNy

> What is your rclone version (eg output from `rclone -V`)
rclone v1.34

> Which OS you are using and how many bits (eg Windows 7, 64 bit)
Ubuntu 15.05 64 bits in a Virtual machine on a Windows 7, 64 bit host ( to circumvent https://github.com/ncw/rclone/issues/261)  

> Which cloud storage system are you using? (eg Google Drive)
Google drive

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone copy ~/ngEn Remote:Nedladdat(F) --drive-chunk-size 128 M
 
> A log from the command with the `-v` flag (eg output from `rclone -v copy /tmp remote:tmp`)
Currently do not have a log, but can generate one if it is needed.

**Comment by qnorsten** [comment]
Here is some update. I managed to solve some of the problem by mounting the drive on windows and using a program to detect and delete empty folders, after that the correct folder with content showed up. 

After that the only duplicate folders with files in them remained. I am currently exploring options such as described here to try and solve it http://stackoverflow.com/questions/38690483/merge-folder-with-the-same-name-in-google-drive-using-google-script

After some searching on the internet, I see that this seem to be a general Google Drive error and not only an rclone error. It is still interesting to know why this happens/happened and if rclone can do anything to avoid it?

**Comment by ncw** [comment]
I don't know why this happens, but it does :-(  If you look back through rclone's issues you'll see lots about duplicate files on google drive.

There is the `rclone dedupe` command to help (and if you try the latest beta you can use `rclone rmdirs` to remove all empty directories)

What I should probably do is make a mode for `rclone dedupe` to merge those duplicated directories.  It isn't trivial to do unfortunately.

The duplicated directories are invisible to normal rclone copy etc, it can cope with them just fine.  But `rclone mount` has a problem with them.

You could also fix this by moving things about in the google drive web interface if there aren't too many of them.

**Comment by qnorsten** [comment]
Yea I found that when I searched around more, should proably have searched more thoroughly before posting (just did a quick search)

The rclone rmdirs was a bit helpful at least. :) Good addition, was faster then my other method to delete empty folders. 

Ideally dedupe should handle and merge these duplicated directories just as you say. That would be awesome, and sort of fix the problem. 

Currently I am trying to fix it manually but it is a lot of nested sub folders with lot of files in them. So it takes quite a while, might be easier just to delete everything and spend a few days re uploading  ~2 TB of files.

**Comment by ncw** [comment]
> Is the content of both duplicate folder copied to the computer if I use rclone copy Remote:Folder Localdrive:folder ?

You'll get all the contents of the duplicate folders merged which is probably what you want.

I'm going to close this now as it is covered in #28 #360 (and others!)
