### ISSUE TITLE
Improve move command (and add rename command)

### ISSUE THREAD

**Issue by pedrosimao** [ncw/rclone#928]
I was testing the move command today (with encrypted Amazon Cloud Drive), and I did try to move from Amazon Cloud inside Amazon Cloud itself. I tried to changed the folder name, only. But rclone started downloading and uploading everything all over.
So I realized two things:
1 - The move command is not working. If rclone was smarter it would simply rename the folder instead of trying to re-download everything.
2 - We are missing a rename command. This is especially useful for the encrypted backups, because  of the encrypted filenames. Otherwise we could simply use the cloud interface,given by the service provider, to rename each file and folder. But with encrypted version it is not possible since we don't know what name means what, and we don't know how to manually create encrypted names.

**Comment by pedrosimao** [comment]
Sorry, just saw there was already people asking for that.

**Comment by ncw** [comment]
Try the latest beta - it fixes all those issues and adds the `moveto` command which can be used to rename things.
