### ISSUE TITLE
Does Crypt work on Windows?

### ISSUE THREAD

**Issue by navigonic** [ncw/rclone#929]
I keep receiving a panic warning:

goroutine 1 [running]:
panic(0x938b80, 0x112e0220)
        /usr/local/go/src/runtime/panic.go:500 +0x331
log.Panicf(0x9f9be9, 0x3a, 0x1142513c, 0x2, 0x2)
        /usr/local/go/src/log/log.go:327 +0xb5
github.com/ncw/rclone/vendor/github.com/rfjakob/eme.Transform(0xc4df00, 0x113ea1e0, 0x11392b30, 0x10, 0x10, 0x11409200, 0x890, 0x900, 0x2f000001, 0x0, ...)
        /home/ncw/Code/Go/src/github.com/ncw/rclone/vendor/github.com/rfjakob/eme/eme.go:119 +0xebf
github.com/ncw/rclone/crypt.(*cipher).encryptSegment(0x11392af0, 0x113787dc, 0x880, 0x0, 0x0)
        /home/ncw/Code/Go/src/github.com/ncw/rclone/crypt/cipher.go:255 +0x11a
github.com/ncw/rclone/crypt.(*cipher).encryptFileName(0x11392af0, 0x1137600c, 0x4152, 0x0, 0x0)
        /home/ncw/Code/Go/src/github.com/ncw/rclone/crypt/cipher.go:291 +0xad
github.com/ncw/rclone/crypt.(*cipher).EncryptFileName(0x11392af0, 0x1137600c, 0x4152, 0x0, 0x0)
        /home/ncw/Code/Go/src/github.com/ncw/rclone/crypt/cipher.go:301 +0x7c
github.com/ncw/rclone/crypt.NewFs(0x11376000, 0xb, 0x1137600c, 0x4152, 0x0, 0x0, 0x0, 0x0)
        /home/ncw/Code/Go/src/github.com/ncw/rclone/crypt/crypt.go:75 +0x499
github.com/ncw/rclone/fs.NewFs(0x11376000, 0x415e, 0x0, 0x0, 0x0, 0x0)
        /home/ncw/Code/Go/src/github.com/ncw/rclone/fs/fs.go:452 +0xaa
github.com/ncw/rclone/crypt.NewFs(0x11396900, 0xb, 0x1139690c, 0x27cf, 0x0, 0x0, 0x0, 0x0)
        /home/ncw/Code/Go/src/github.com/ncw/rclone/crypt/crypt.go:76 +0x532
github.com/ncw/rclone/fs.NewFs(0x11396900, 0x27db, 0x0, 0x0, 0x0, 0x0)
        /home/ncw/Code/Go/src/github.com/ncw/rclone/fs/fs.go:452 +0xaa
github.com/ncw/rclone/crypt.NewFs(0x113ed800, 0xb, 0x113ed80c, 0x17e5, 0x0, 0x0, 0x0, 0x0)
        /home/ncw/Code/Go/src/github.com/ncw/rclone/crypt/crypt.go:76 +0x532
github.com/ncw/rclone/fs.NewFs(0x113ed800, 0x17f1, 0x0, 0x0, 0x0, 0x0)
        /home/ncw/Code/Go/src/github.com/ncw/rclone/fs/fs.go:452 +0xaa
github.com/ncw/rclone/crypt.NewFs(0x1132c000, 0xb, 0x1132c00c, 0xdfb, 0x0, 0x0, 0x0, 0x0)
        /home/ncw/Code/Go/src/github.com/ncw/rclone/crypt/crypt.go:76 +0x532
github.com/ncw/rclone/fs.NewFs(0x1132c000, 0xe07, 0x0, 0x0, 0x0, 0x0)
        /home/ncw/Code/Go/src/github.com/ncw/rclone/fs/fs.go:452 +0xaa
github.com/ncw/rclone/crypt.NewFs(0x11357b00, 0xb, 0x11357b0c, 0x7f8, 0x0, 0x0, 0x0, 0x0)
        /home/ncw/Code/Go/src/github.com/ncw/rclone/crypt/crypt.go:76 +0x532
github.com/ncw/rclone/fs.NewFs(0x11357b00, 0x804, 0x0, 0x0, 0x0, 0x0)
        /home/ncw/Code/Go/src/github.com/ncw/rclone/fs/fs.go:452 +0xaa
github.com/ncw/rclone/crypt.NewFs(0x11400000, 0xb, 0x1140000c, 0x459, 0x0, 0x0, 0x0, 0x0)
        /home/ncw/Code/Go/src/github.com/ncw/rclone/crypt/crypt.go:76 +0x532
github.com/ncw/rclone/fs.NewFs(0x11400000, 0x465, 0x0, 0x0, 0x0, 0x0)
        /home/ncw/Code/Go/src/github.com/ncw/rclone/fs/fs.go:452 +0xaa
github.com/ncw/rclone/crypt.NewFs(0x112f4500, 0xb, 0x112f450c, 0x23a, 0x0, 0x0, 0x0, 0x0)
        /home/ncw/Code/Go/src/github.com/ncw/rclone/crypt/crypt.go:76 +0x532
github.com/ncw/rclone/fs.NewFs(0x112f4500, 0x246, 0x0, 0x0, 0x0, 0x0)
        /home/ncw/Code/Go/src/github.com/ncw/rclone/fs/fs.go:452 +0xaa
github.com/ncw/rclone/crypt.NewFs(0x1132e240, 0xb, 0x1132e24c, 0x102, 0x0, 0x0, 0x0, 0x0)
        /home/ncw/Code/Go/src/github.com/ncw/rclone/crypt/crypt.go:76 +0x532
github.com/ncw/rclone/fs.NewFs(0x1132e240, 0x10e, 0x0, 0x0, 0x0, 0x0)
        /home/ncw/Code/Go/src/github.com/ncw/rclone/fs/fs.go:452 +0xaa
github.com/ncw/rclone/crypt.NewFs(0x113b07e0, 0xb, 0x113b07ec, 0x63, 0x0, 0x0, 0x0, 0x0)
        /home/ncw/Code/Go/src/github.com/ncw/rclone/crypt/crypt.go:76 +0x532
github.com/ncw/rclone/fs.NewFs(0x113b07e0, 0x6f, 0x0, 0x0, 0x0, 0x0)
        /home/ncw/Code/Go/src/github.com/ncw/rclone/fs/fs.go:452 +0xaa
github.com/ncw/rclone/crypt.NewFs(0x112c6330, 0xb, 0x112c633c, 0x12, 0x0, 0x0, 0x0, 0x0)
        /home/ncw/Code/Go/src/github.com/ncw/rclone/crypt/crypt.go:76 +0x532
github.com/ncw/rclone/fs.NewFs(0x112c6330, 0x1e, 0x0, 0x0, 0x0, 0x0)
        /home/ncw/Code/Go/src/github.com/ncw/rclone/fs/fs.go:452 +0xaa
github.com/ncw/rclone/cmd.newFsDst(0x112c6330, 0x1e, 0x0, 0x0)
        /home/ncw/Code/Go/src/github.com/ncw/rclone/cmd/cmd.go:126 +0x37
github.com/ncw/rclone/cmd.NewFsSrcDst(0x113ea600, 0x2, 0x3, 0x0, 0x0, 0x0, 0x0)
        /home/ncw/Code/Go/src/github.com/ncw/rclone/cmd/cmd.go:136 +0x82
github.com/ncw/rclone/cmd/copy.glob..func1(0xc73640, 0x113ea600, 0x2, 0x3)
        /home/ncw/Code/Go/src/github.com/ncw/rclone/cmd/copy/copy.go:58 +0x69
github.com/ncw/rclone/vendor/github.com/spf13/cobra.(*Command).execute(0xc73640, 0x113ea5a0, 0x3, 0x4, 0x0, 0x0)
        /home/ncw/Code/Go/src/github.com/ncw/rclone/vendor/github.com/spf13/cobra/command.go:636 +0x67c
github.com/ncw/rclone/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc72f80, 0xc73640, 0x0, 0x0)
        /home/ncw/Code/Go/src/github.com/ncw/rclone/vendor/github.com/spf13/cobra/command.go:722 +0x39d
github.com/ncw/rclone/vendor/github.com/spf13/cobra.(*Command).Execute(0xc72f80, 0x0, 0x0)
        /home/ncw/Code/Go/src/github.com/ncw/rclone/vendor/github.com/spf13/cobra/command.go:681 +0x2b
main.main()
        /home/ncw/Code/Go/src/github.com/ncw/rclone/rclone.go:15 +0x27

**Comment by ncw** [comment]
I think this is probably the same as #784

I think you've configured the crypt to point at itself.

The crypt needs to point at the underlying unencrypted remote.

Does that make sense?

I'm planning to warn about this in #927
