### ISSUE TITLE
[Feature Request] add a function that precache file when readed on Fuse

### ISSUE THREAD

**Issue by Njcki** [ncw/rclone#935]
Hi,
I think this could be a very very useful feature for Plex-addicted users.
When we start playing a video on Plex, download speed may vary a lot and it may even freeze for dozens of seconds. This is probably due to small size requests done by Plex and/or Fuse.
As you can see this is not going to happen when you use "cp" command.

That said, can you add a feature that starts precaching the entire file (obviously starting from the seek value and not always from the byte 0)? This could be enabled at mount time with a flag.

I know a similar feature should be done by readahead but it's not working as it should in this case.

Thanks
Niccolò Mencarini

**Comment by ncw** [comment]
After a bit of research, I don't think you can use read ahead to raise the value supplied by the kernel (which is 128k on linux), so no, it probably isn't working as expected.

However I've put in some in memory buffering  which reads up to 16M of the file before it is used which should help a lot in the latest beta: http://beta.rclone.org/v1.34-51-gcb9f1ee/ - fancy giving it a go?

**Comment by wreckedred** [comment]
Installed v1.34-51 and I am seeing outputs to stout from my mount I assume - can I redirect that to a file?
Interesting to see how slow my connection to ACD is though!

ubuntu@apex:~$ 2016/12/07 11:45:55 
Transferred:   67.075 MBytes (190.099 kBytes/s)
Errors:                 0
Checks:                 0
Transferred:            5
Elapsed time:      6m1.3s

2016/12/07 11:46:55 
Transferred:   89.450 MBytes (217.408 kBytes/s)
Errors:                 0
Checks:                 0
Transferred:            5
Elapsed time:      7m1.3s

2016/12/07 11:47:55 
Transferred:   106.075 MBytes (225.676 kBytes/s)
Errors:                 0
Checks:                 0
Transferred:            5
Elapsed time:      8m1.3s

**Comment by Njcki** [comment]
@ncw I already tried v1.34-48 last days (which should include the commit you are referring to), but I didn't see any huge improvement :(

**Comment by calisro** [comment]
@wreckedred  I don't think those numbers are quite what you are expecting.  These seem to be an average over the life of the mount rather than the life a file.  When the mount isn't doing anything it is bringing down the average.  

Try a utility and you'll see.  Like this:

**Comment by wreckedred** [comment]
@calisro Hey man thanks - exactly as you describe

rsync -avh --progress --inplace "/home/wreckedred/mntacd/pe/tv/Teen Wolf S06E03.mp4" .
sending incremental file list
Teen Wolf S06E03.mp4
        394.04M  51%   10.56MB/s    0:00:34  2016/12/07 17:24:55

**Comment by wreckedred** [comment]
With the latest beta I get statistics on the console printed every 60 seconds

wreckedred@apex:~$ rclone mount secretacd: /home/wreckedred/mntacd &
[1] 16598
wreckedred@apex:~$ 2016/12/07 17:37:27 
Transferred:      0 Bytes (0 Bytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:      1m1.4s

2016/12/07 17:38:27 
Transferred:      0 Bytes (0 Bytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:      2m1.4s

**Comment by calisro** [comment]
Yea, seems to be new.  you can turn it off with "--stats 0"

**Comment by tjeh** [comment]
Or just redirect it to a log file, which gives you the added bonus to see which files where accessed via the mount.

**Comment by ncw** [comment]
I put the stats printing in as part of fixing the bwlimit for mount which makes mount the same as the other commands. I can disable it if everyone hates it though...

**Comment by calisro** [comment]
I'd rather have it so its easier to see what it is doing.  It is easily turned off if needed.

**Comment by tjeh** [comment]
maybe just update the documentation for "mount" that you should include --stats=0

**Comment by wreckedred** [comment]
I would vote to keep it - very interesting data but the simple rclone mount
acd: g should be quiet

**Comment by cejpe** [comment]
Keep it imo. I'd just mount rclone in a screen or output the data to a log, it's good info.

**Comment by Njcki** [comment]
@ncw It appears that [this](https://github.com/Doloops/mcachefs) FUSE FS is doing what I was asking.
Sadly it's incomplete as seek does not work if the initial download is still going. And it appears to do not stop the download when the program close the file descriptor.
Anyway maybe you can have a look and take some parts.

**Comment by Njcki** [comment]
@ncw maybe the following project could be helpful :)
https://godoc.org/crast.us/smoothfs
https://github.com/crast/smoothfs

Let me know.

**Comment by flixajki** [comment]
@Njcki smoothfs looks really interesting, hopefully rclone can get few improvements in that direction.

**Comment by Njcki** [comment]
I think --buffer-size is a kind of what I was asking for.
This issue can be closed

**Comment by ajkis** [comment]
> This issue can be closed
You can close your own issues :)
