### ISSUE TITLE
100% CPU/drop in upload speed

### ISSUE THREAD

**Issue by diamondsw** [ncw/rclone#937]
> What is your rclone version (eg output from `rclone -V`)
rclone: Version "v1.34"

> Which OS you are using and how many bits (eg Windows 7, 64 bit)
Debian 8.5 64-bit

> Which cloud storage system are you using? (eg Google Drive)
Amazon Drive, crypt overlay

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
/usr/local/bin/rclone copy --verbose --stats 0 --no-traverse "amazon:Backup/Anime" "amazon-private:Backup/Anime"

> A log from the command with the `-v` flag (eg output from `rclone -v copy /tmp remote:tmp`)
[backup-log.txt](https://github.com/ncw/rclone/files/640519/backup-log.txt)

![backup-cpu](https://cloud.githubusercontent.com/assets/49737/21026548/b1b1ad24-bd52-11e6-9eef-475966c69e02.png)

I decided (belatedly) to encrypt my Amazon Drive data. I've been using rclone to copy everything down and back up to a crypt remote. Host is a Dell R710 server with 1Gbps connection to the internet and direct peering to AWS-East. Performance really shouldn't be an issue.

After a while, I found that CPU spikes to 100% and stays there permanently, and transmit performance drops. Sometimes steadily drifts down; other times it just craters to a few KB/sec. Once CPU pegs to 100% it *never* drops back. In the attached log, 100% CPU begins at 13:05. I don't see anything that jumps out - even if retries cause some lowered network performance, nothing should cause massive CPU use like this.

A few more details - while running my first attempts yesterday I achieved consistent 500Mbps transfer, with spikes up to the full 1Gbps. Since I wasn't seeing problems yet I didn't keep any logs or debugging information, but I know my setup is certainly capable of a *lot* more. I've also tried giving the VM more CPU and memory, up to 4 vCPU (~10Ghz) and 4GB of memory - no change; rclone still manages to consume 100% of all available CPUs (390% in top, for instance) without significant upload progress. Kill rclone and restart, and as soon as it churns through all the unchanged files it transfers away merrily - until it pegs again (you can see that in the graph attached - I killed an earlier pegged session and restarted it).

Ultimately this is making rclone unusable for this task. *Should* I even be using it for this (download from amazon, encrypt, upload back to amazon)?

**Comment by diamondsw** [comment]
strace shows remarkably little info. Just:
> root@backup jochs $ strace -p 1177
> Process 1177 attached
> futex(0xdf55f0, FUTEX_WAIT, 0, NULL

Also, a couple more images showing upload cratering eventually after a period of 100% CPU.
![backup2-cpu](https://cloud.githubusercontent.com/assets/49737/21027912/82e001a2-bd58-11e6-96f5-e14fcf2cafb4.png)
![backup2-upload](https://cloud.githubusercontent.com/assets/49737/21027913/853c6f08-bd58-11e6-8037-ba9a4ff80096.png)

**Comment by ncw** [comment]
Interesting! I would say this is a good use of rclone so it should work properly for this. 

What to the rclone logs say - can you post some of those? Logs with -v would be most helpful.  

What you could do is kill -QUIT the rclone process when it gets stuck and post the enormous traceback that will generate to stderr. If it is a livelock then that will tell us where it is hopefully. 

This process might be CPU limited (I'm not certain though)  - you are doing two encrypted https links plus rclone's own encryption. However I wouldn't expect it to grind to a halt. 

When it gets stuck is it doing something in particular? Uploading big file or small files? What to the rclone stats say at this point? 

Is that all the strace program printed? Looks very suspicious that it has livelocked...

**Comment by diamondsw** [comment]
Hi there - I posted a log above the first CPU graph (easy to miss with all the other stuff going on there!). Files in question were large-ish. Video files ranging from a handful of megabytes up to a couple hundred.

Agreed the strace was *very* abbreviated - that's indeed all it printed, and I left it for at least 10 seconds. Normally you'd get more info than you can handle, so something was very stuck. Next time I see it I'll try "kill -QUIT".

I also thought it was CPU-limited so I gave it more and more vCPU's, finally 4x2.4Ghz vCPUs, and it managed to soak it all up. Normally it runs with relatively minor CPU even on a single vCPU.

Is there any potential for a deadlock since I was reading and writing to the same remote (the destination is a crypt overlay of the source)?

**Comment by diamondsw** [comment]
Sadly not the same dataset, but when I copy with the local filesystem as the source everything has been fine for over 24 hours. Seems this only occurs between two remotes; I only have Amazon to test with so I don't know if this is between any two remotes, between any remote and itself, or something specific to Amazon Drive.

**Comment by johnpowell** [comment]
I can reproduce this issue. 

I ran into it last night when using sync and copy (tried both to be safe) to mirror from a unencrypted Google Drive to a encrypted ACD account (these are not mounts. Just vanilla). 

`rclone copy google:plex/HDMV amazonENC:plex`

It would simply start climbing my CPU usage in TOP and would hit 100% and then transfers would stall. 

I am using v 1.35 of rclone on a dedicated server at soyoustart running Ubuntu 14.04 if that helps. 

I'm not good at this stuff so if I can do anything to help you please treat me as a child.

**Comment by ncw** [comment]
I'm pretty sure this is the same issue as #902 

I think I've worked out what is happening here. I managed to reproduce it once, and it gave me enough of a clue.

Can you try this beta please and let me know how you get on:

http://beta.rclone.org/v1.35-41-g2abfae2/ (uploaded in 15-30 mins)

Thanks

Nick

**Comment by diamondsw** [comment]
Can confirm, everything looks good on the beta - no CPU spikes or bandwidth dropouts. Still trying to find the perfect mix of simultaneous transfers to take full advantage of my bandwidth, but it's been running well for a few hours.

**Comment by ncw** [comment]
@diamondsw excellent - thanks for testing
