### ISSUE TITLE
waiting for sync to finish Amazon cloud drive

### ISSUE THREAD

**Issue by tulamidan** [ncw/rclone#938]
I might have messed a bit with rclone and I am now in a state where I am no longer able to sync.

I have a linux system and my hdd is on btrfs

I have mixed up the sync order (rclone sync source :destination) which did a sort of sync and then finished.

Then I noticed my mistake and reversed the order to copy the files from my disk to amazon cloud drive.

Yet this fails with the error message:
amazon drive root "myfolder" : Waiting for checks to finish 
amazon drive root "myfolder" : Waiting for transfers to finish

waiting for deletions to finish

According to a few notes here I have tried the following:
- checked the hdd integrity
- made sure to use the correct user who mounted the disc and uses rclone
- tried the option --no-traverse

so far no success.

**Comment by ncw** [comment]
None of those things are errors - it looks like rclone thinks it worked successfully. Did rclone exit with an error (do `echo $?` after it ran to see)?

> I have mixed up the sync order (rclone sync source :destination) which did a sort of sync and then finished.

:-(

Was the destination empty when you did that?  If it was then rclone quite likely deleted all your local files. That is why it says in the manual to try `--dry-run` first.

So what does `rclone ls source:` say and `rclone ls dest:` say?

It would be helpful if you post a log and the actual commands you are using.

Also try adding the `-v` flag to see what is going on.

**Comment by tulamidan** [comment]
The local file system is say 100% and the remote destination is about 50% (half the files are already synced)

I did: rclone sync remote:Backup/ /mnt/sda/data/ instead of rclone sync /mnt/sda/data/  remote:Backup/nc

Echo $? => 0
rsync  ls source => the files and: Transferred: 0 Bytes,0 errors, 0 Checks, 0 Transferred
rsync ls remote =>the files and: Transferred: 0 Bytes,0 errors, 0 Checks, 0 Transferred

rsync  ls source => the two directories in my folder with the status 0
rsync ls remote =>  the two directories in my folder with the status -1

doing the sync with -v verbosity gives a ton of file checks "unchanged" or size identical.
and the Waiting for... messages. + the Hint: Go routines finished at exit 22

**Comment by tulamidan** [comment]
well the error did not go away and I went back to my backup (i did before the failed sync) since then it works again. Might still be an issue, but currently I can live with it.
