### ISSUE TITLE
b2: time out when uploading?

### ISSUE THREAD

**Issue by marrie** [ncw/rclone#943]
Version: rclone v1.33-79-g77b975dβ

ProductName:	Mac OS X
ProductVersion:	10.12.2
BuildVersion:	16C63a

When uploading I will encounter timeouts when uploading to b2. I have my low level retries set to 1 so should this in theory not happen? I've attached a log file which should help. It's not erbose, but I get the feeling I bugged this before.

[Uploading outputarchives.logag.zip…]()

Thanks

**Comment by ncw** [comment]
Timeouts happen - it is a fact of the internet.  I suggest you remove the setting of low level retries and leave it at the default - that will catch the timeouts and retry them - that is what it is for.

I couldn't see your log - it didn't seem to be attached.

**Comment by marrie** [comment]
I just love when  technology works! Not. Well, I'll give that a try. On a 8 mbps up connection I would not expect a lot of these to happen, but maybe either rclone or b2 was having a bad day, or both. We'll see if it attempts to try the file again. Can't wait for this to be released to the public soon.
