### ISSUE TITLE
Google Drive not uploading

### ISSUE THREAD

**Issue by canonlp** [ncw/rclone#945]
The speeds for uploading to gdrive lately has been slow. It would start around 40MB/s and drop to nearly zero. Today, it has not been uploading past the chuck size limit I set. So if I set it to 256M, the transferred amount is only 256Mb. If I set it to 128M, then only 128Mb. The speed drops to zero and I can't upload anything.

> What is your rclone version (eg output from `rclone -V`)
1.34-dev
> Which OS you are using and how many bits (eg Windows 7, 64 bit)
Ubuntu 15.10 64bit
> Which cloud storage system are you using? (eg Google Drive)
Google Drive
> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone copy --stats 10s --drive-chunk-sizze 256M .... gdrive:
> A log from the command with the `-v` flag (eg output from `rclone -v copy /tmp remote:tmp`)

**Comment by ncw** [comment]
Have you been uploading a lot of stuff?  It might be that you've used your quota up.  If you wait 24h it should all be back to normal.

The quota is invisible to the user, but that is what rclone users have figured out.

**Comment by jpat0000** [comment]
@ncw I have uploaded over 8 terabytes in a single day before, I don't know that there is an upload quota. Even after exceeding a quota which locks all downloading, uploading still works.

I have seen similar behavior before (using a large chunk size), but typically at the last chunk where it grinds to a halt at 100% completion for a minute or two before finally completing. This issue seemed to appear on one server, but not another during my testing. I suspect there may be other factors causing the problem.

**Comment by ncw** [comment]
@canonlp is this working again now?

**Comment by canonlp** [comment]
Did a clean install, still the same thing. I can't upload at 256M anymore. It has worked before. However, I can get it to upload fine at 32M. But it is still dodgy at best. Speed fluctuates a tonne. Trying to figure out if it server/hardware related

**Comment by ncw** [comment]
It would be worth checking out your router - rebooting or upgrading the firmware. Rclone works the network quite hard and I had multiple reports of people needing to do that.

**Comment by canonlp** [comment]
It's on a server though, so is there a way I can check that is the problem?

**Comment by canonlp** [comment]
I just tested this again, on a totally different server. Same thing is happening. I tried 2 different Google Drive accounts.

`rclone copy --checksum --stats 10s --drive-chunk-size 256M ubuntu-16.04.1-desktop-amd64.iso gdrive:
2016/12/18 15:49:26 Google drive root '': Waiting for checks to finish
2016/12/18 15:49:26 Google drive root '': Waiting for transfers to finish
2016/12/18 15:49:36
Transferred:   256 MBytes (21.832 MBytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:       11.7s
Transferring:
 \*              ubuntu-16.04.1-desktop-amd64.iso: 17% done. avg: 28078.0, cur: 53259.5 kByte/s. ETA: 22s

2016/12/18 15:49:46
Transferred:   256 MBytes (11.783 MBytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:       21.7s
Transferring:
\*               ubuntu-16.04.1-desktop-amd64.iso: 17% done. avg: 13557.1, cur: 27337.6 kByte/s. ETA: 44s

2016/12/18 15:49:56
Transferred:   256 MBytes (8.069 MBytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:       31.7s
Transferring:
\*              ubuntu-16.04.1-desktop-amd64.iso: 17% done. avg: 8935.8, cur: 14032.1 kByte/s. ETA: 1m26s`

Notice it only transferred 256 MB and won't transfer any more. The speed will also drop to 0. Unless BOTH my accounts are rate limited, I'm not sure what is really going on. The server I tried this on just now is a new one that hasn't been uploading to Gdrive at all.

**Comment by bep** [comment]
Just to note that grdive is syncing very good for me -- great speeds. I saturate my internet bandwidth easily.

**Comment by canonlp** [comment]
The transfer is working when I take out the --drive-chunk-size. It uploads at around 7MB/s and finishes. The problem occurs when I'm trying to upload using a big chunk size like 256M which has worked for me before, but not any more apparently.

**Comment by ncw** [comment]
@canonlp wrote:
> Notice it only transferred 256 MB and won't transfer any more. The speed will also drop to 0. Unless BOTH my accounts are rate limited, I'm not sure what is really going on. The server I tried this on just now is a new one that hasn't been uploading to Gdrive at all

The bandwidth stats are slightly misleading here as it hasn't actually transferred 256MB to google, only to an internal buffer to upload to google.  So it looks like your transfers aren't progressing at all.  You will see it shoot up to 256M with very fast transfer rates then gradually sink down again.

I fixed this behavior for chunked uploads for ACD and I should do the same for drive - see #968

I tried with the default `--drive-chunk-size` and with 256M and they both worked fine here.

Is it possible that you just aren't waiting long enough for the chunk to be uploaded?  How fast is your internet connection?

**Comment by canonlp** [comment]
It might be a server issue, since my other server is working fine. I have 1gbps connection. I asked the server support, but they said the network is congested. Would that explain why I can't upload at 256M? I could upload normally however, but really really slow.

**Comment by ghariib** [comment]
I'm having the same problem as canonlp:

The speed is really slow. We have a 100mbps connection (~10 mb/s upload) and every time i'm just getting something like 100kb/s. I've tried with my own client id and client secret, but the result was the same as with the predefined ones.

As you can see in the logs, it takes approximately 1m40s to upload 10 MBytes. (Upload speed around 102,4 kb/s)

I've tested it with the stable version beforehand and the result was the same

This is generated with the predefined ids:

>2017/04/11 12:48:10 DEBUG : rclone: Version "v1.36-22-gbc25190β" starting with parameters ["rclone" "-vvv" "--log-file" "/home/user/p.log" "copy" "--drive-chunk-size" "2M" "--stats" "10s" "1GB.zip" "opus:/test"]
>2017/04/11 12:48:15 DEBUG : pacer: Rate limited, sleeping for 1.287113937s (1 consecutive low level retries)
>2017/04/11 12:48:15 DEBUG : pacer: low level retry 1/10 (error googleapi: Error 403: Rate Limit Exceeded, rateLimitExceeded)
>2017/04/11 12:48:15 DEBUG : pacer: Resetting sleep to minimum 10ms on success
>2017/04/11 12:48:16 DEBUG : pacer: Rate limited, sleeping for 1.54916732s (1 consecutive low level retries)
>2017/04/11 12:48:16 DEBUG : pacer: low level retry 1/10 (error googleapi: Error 403: Rate Limit Exceeded, rateLimitExceeded)
>2017/04/11 12:48:16 DEBUG : pacer: Rate limited, sleeping for 2.632969758s (2 consecutive low level retries)
>2017/04/11 12:48:16 DEBUG : pacer: low level retry 2/10 (error googleapi: Error 403: Rate Limit Exceeded, rateLimitExceeded)
>2017/04/11 12:48:18 DEBUG : pacer: Resetting sleep to minimum 10ms on success
>2017/04/11 12:48:18 INFO  : Google drive root 'test': Modify window is 1ms
>2017/04/11 12:48:20 INFO  : Google drive root 'test': Waiting for checks to finish
>2017/04/11 12:48:20 INFO  : Google drive root 'test': Waiting for transfers to finish
>2017/04/11 12:48:21 DEBUG : 1GB.zip: Sending chunk 0 length 2097152
>2017/04/11 12:48:28 INFO  : 
>Transferred:     2 MBytes (112.433 kBytes/s)
>Errors:                 0
>Checks:                 0
>Transferred:            0
>Elapsed time:       18.2s
>Transferring:
> *                                       1GB.zip:  0% done, 1.339 MBytes/s, ETA: 12m42s
>
>2017/04/11 12:48:38 INFO  : 
>Transferred:     2 MBytes (72.584 kBytes/s)
>Errors:                 0
>Checks:                 0
>Transferred:            0
>Elapsed time:       28.2s
>Transferring:
> *                                       1GB.zip:  0% done, 704.048 kBytes/s, ETA: 24m46s
>
>2017/04/11 12:48:40 DEBUG : 1GB.zip: Sending chunk 2097152 length 2097152
>2017/04/11 12:48:48 INFO  : 
>Transferred:     4 MBytes (107.180 kBytes/s)
>Errors:                 0
>Checks:                 0
>Transferred:            0
>Elapsed time:       38.2s
>Transferring:
> *                                       1GB.zip:  0% done, 444.171 kBytes/s, ETA: 39m11s
>
>2017/04/11 12:48:57 DEBUG : 1GB.zip: Sending chunk 4194304 length 2097152
>2017/04/11 12:48:58 INFO  : 
>Transferred:     6 MBytes (127.428 kBytes/s)
>Errors:                 0
>Checks:                 0
>Transferred:            0
>Elapsed time:       48.2s
>Transferring:
> *                                       1GB.zip:  0% done, 360.672 kBytes/s, ETA: 48m10s
>
>2017/04/11 12:49:08 INFO  : 
>Transferred:     6 MBytes (105.537 kBytes/s)
>Errors:                 0
>Checks:                 0
>Transferred:            0
>Elapsed time:       58.2s
>Transferring:
> *                                       1GB.zip:  0% done, 185.129 kBytes/s, ETA: 1h33m50s
>
>2017/04/11 12:49:15 DEBUG : 1GB.zip: Sending chunk 6291456 length 2097152
>2017/04/11 12:49:18 INFO  : 
>Transferred:     8 MBytes (120.089 kBytes/s)
>Errors:                 0
>Checks:                 0
>Transferred:            0
>Elapsed time:      1m8.2s
>Transferring:
> *                                       1GB.zip:  0% done, 210.676 kBytes/s, ETA: 1h22m18s
>
>2017/04/11 12:49:28 INFO  : 
>Transferred:     8 MBytes (104.734 kBytes/s)
>Errors:                 0
>Checks:                 0
>Transferred:            0
>Elapsed time:     1m18.2s
>Transferring:
> *                                       1GB.zip:  0% done, 108.138 kBytes/s, ETA: 2h40m20s
>
>2017/04/11 12:49:34 DEBUG : 1GB.zip: Sending chunk 8388608 length 2097152
>2017/04/11 12:49:38 INFO  : 
>Transferred:    10 MBytes (116.078 kBytes/s)
>Errors:                 0
>Checks:                 0
>Transferred:            0
>Elapsed time:     1m28.2s
>Transferring:
> *                                       1GB.zip:  0% done, 163.684 kBytes/s, ETA: 1h45m43s
>
>2017/04/11 12:49:48 INFO  : 
>Transferred:    10 MBytes (104.259 kBytes/s)
>Errors:                 0
>Checks:                 0
>Transferred:            0
>Elapsed time:     1m38.2s
>Transferring:
> *                                       1GB.zip:  0% done, 84.017 kBytes/s, ETA: 3h25m58s
>
>2017/04/11 12:49:51 DEBUG : 1GB.zip: Sending chunk 10485760 length 2097152



And the following one is generated with my own ids:

>2017/04/11 13:22:23 DEBUG : rclone: Version "v1.36-22-gbc25190β" starting with parameters ["rclone" "-vvv" "--log-file" "/home/user/r.log" "copy" "--drive-chunk-size" "2M" "--stats" "10s" "1GB.zip" "opus:opus"]
>2017/04/11 13:22:29 INFO  : Google drive root 'opus': Modify window is 1ms
>2017/04/11 13:22:29 INFO  : Google drive root 'opus': Waiting for checks to finish
>2017/04/11 13:22:29 INFO  : Google drive root 'opus': Waiting for transfers to finish
>2017/04/11 13:22:30 DEBUG : 1GB.zip: Sending chunk 0 length 2097152
>2017/04/11 13:22:39 INFO  : 
>Transferred:     2 MBytes (130.813 kBytes/s)
>Errors:                 0
>Checks:                 0
>Transferred:            0
>Elapsed time:       15.6s
>Transferring:
> *                                       1GB.zip:  0% done, 1.173 MBytes/s, ETA: 14m31s
>
>2017/04/11 13:22:49 INFO  : 
>Transferred:     2 MBytes (79.823 kBytes/s)
>Errors:                 0
>Checks:                 0
>Transferred:            0
>Elapsed time:       25.6s
>Transferring:
> *                                       1GB.zip:  0% done, 616.381 kBytes/s, ETA: 28m17s
>
>2017/04/11 13:22:50 DEBUG : 1GB.zip: Sending chunk 2097152 length 2097152
>2017/04/11 13:22:59 INFO  : 
>Transferred:     4 MBytes (114.877 kBytes/s)
>Errors:                 0
>Checks:                 0
>Transferred:            0
>Elapsed time:       35.6s
>Transferring:
> *                                       1GB.zip:  0% done, 393.879 kBytes/s, ETA: 44m11s
>
>2017/04/11 13:23:09 DEBUG : 1GB.zip: Sending chunk 4194304 length 2097152
>2017/04/11 13:23:09 INFO  : 
>Transferred:     6 MBytes (134.571 kBytes/s)
>Errors:                 0
>Checks:                 0
>Transferred:            0
>Elapsed time:       45.6s
>Transferring:
> *                                       1GB.zip:  0% done, 202.174 kBytes/s, ETA: 1h25m56s
>
>2017/04/11 13:23:19 INFO  : 
>Transferred:     6 MBytes (110.393 kBytes/s)
>Errors:                 0
>Checks:                 0
>Transferred:            0
>Elapsed time:       55.6s
>Transferring:
> *                                       1GB.zip:  0% done, 176.548 kBytes/s, ETA: 1h38m24s
>
>2017/04/11 13:23:27 DEBUG : 1GB.zip: Sending chunk 6291456 length 2097152
>2017/04/11 13:23:29 INFO  : 
>Transferred:     8 MBytes (124.772 kBytes/s)
>Errors:                 0
>Checks:                 0
>Transferred:            0
>Elapsed time:      1m5.6s
>Transferring:
> *                                       1GB.zip:  0% done, 222.757 kBytes/s, ETA: 1h17m50s
>
>2017/04/11 13:23:39 INFO  : 
>Transferred:     8 MBytes (108.280 kBytes/s)
>Errors:                 0
>Checks:                 0
>Transferred:            0
>Elapsed time:     1m15.6s
>Transferring:
> *                                       1GB.zip:  0% done, 114.339 kBytes/s, ETA: 2h31m39s
>
>2017/04/11 13:23:45 DEBUG : 1GB.zip: Sending chunk 8388608 length 2097152
>2017/04/11 13:23:49 INFO  : 
>Transferred:    10 MBytes (119.549 kBytes/s)
>Errors:                 0
>Checks:                 0
>Transferred:            0
>Elapsed time:     1m25.6s
>Transferring:
> *                                       1GB.zip:  0% done, 166.948 kBytes/s, ETA: 1h43m39s
>
>2017/04/11 13:23:59 INFO  : 
>Transferred:    10 MBytes (107.051 kBytes/s)
>Errors:                 0
>Checks:                 0
>Transferred:            0
>Elapsed time:     1m35.6s
>Transferring:
> *                                       1GB.zip:  0% done, 85.692 kBytes/s, ETA: 3h21m56s
>
>2017/04/11 13:24:02 DEBUG : 1GB.zip: Sending chunk 10485760 length 2097152

**Comment by breunigs** [comment]
If you're still facing this issue you can give this beta a try. It will not fix your slowness issue, but at least the reporting per file should be accurate:
https://www.breunig.xyz/share/rclone-beta/v1.36-232-gb2b5c629-drive-accounting%CE%B2/

That being said, if the network is congested then this can absolutely explain why your upload speed is slow. If you're not quite sure what this implies, try to think of the internet as a road network. Depending on where you want to go, there might be traffic jams (congestion) on the way. It doesn't matter how fast you can get out of your town (your server's local link) if the highway is full (interconnection to others, e.g. Google). You can try a more expensive/better interconnected server provider and see if that solves the issue.
