### ISSUE TITLE
I/O error, 'NAME ALREADY EXISTS'

### ISSUE THREAD

**Issue by isaiah36** [ncw/rclone#948]
When filing an issue, please include the following information if possible as well as a description of the problem.  Make sure you test with the [latest beta of rclone](http://rclone.org/downloads/).

If you've just got a question then please use the [rclone forum](https://forum.rclone.org/) instead of filing an issue.

> What is your rclone version (eg output from `rclone -V`)
1.33, now 1.34-48-[latest beta]
> Which OS you are using and how many bits (eg Windows 7, 64 bit)
Ubuntu 16 64bit
> Which cloud storage system are you using? (eg Google Drive)
Amazon
> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
sync
> A log from the command with the `-v` flag (eg output from `rclone -v copy /tmp remote:tmp`)

> 2016/12/13 03:24:25 JAZZ/Lee Morgan - The Sidewinder - (24-96 Flac Vinyl)/Front.jpg: Failed to copy: HTTP code 409: "409 Conflict": response body: "{\"logref\":\"8e9abdb5-c10d-11e6-8479-35cd6177fe21\",\"message\":\"Node with the name front.jpg already exists under parentId JqXhsg-CSBKivnOkaTgccQ conflicting NodeId: R3eo3-MCRlOrQe9INoU5Sg\",\"code\":\"NAME_ALREADY_EXISTS\",\"info\":{\"nodeId\":\"R3eo3-MCRlOrQe9INoU5Sg\"}}"
2016/12/13 03:24:27 RAGAS/Ravi Shankar/Improvisations on the theme from Pather Panchali, Rageshri (24-96 Vinyl FLAC)/Cover.jpg: Failed to copy: HTTP code 409: "409 Conflict": response body: "{\"logref\":\"8fd97eb5-c10d-11e6-84f1-65a74819ec9f\",\"message\":\"Node with the name cover.jpg already exists under parentId 26MiRFHvQ9q78k6WdK2pOw conflicting NodeId: o1KWrH_wSxKj3uGNoisNdA\",\"code\":\"NAME_ALREADY_EXISTS\",\"info\":{\"nodeId\":\"o1KWrH_wSxKj3uGNoisNdA\"}}"
2016/12/13 03:24:52 iTunes/iTunes Media/Music/Doctor Zhivago OST/Cover.jpg: Failed to copy: HTTP code 409: "409 Conflict": response body: "{\"logref\":\"9e98faa8-c10d-11e6-901c-f9f834d312c2\",\"message\":\"Node with the name cover.jpg already exists under parentId XoAGBL9RR8qIaM89ys9ecg conflicting NodeId: WExtRhmeT9SA3SnyFe2JVQ\",\"code\":\"NAME_ALREADY_EXISTS\",\"info\":{\"nodeId\":\"WExtRhmeT9SA3SnyFe2JVQ\"}}"

Deletions have been failing again. It started shortly after my last issue with failing deletions, but I hadn't gotten around to reporting it.

**Comment by ncw** [comment]
Those "409 Conflict" errors are might be because you have files with names in the same case.  Eg `Front.jpg` and `front.jpg` - can you check that?  They sometimes happen because of ACD's eventual consistency and will be fixed by a retry.

> Deletions have been failing again. It started shortly after my last issue with failing deletions, but I hadn't gotten around to reporting it.

I don't see anything about deletiions in the log above

**Comment by isaiah36** [comment]
It is not a full log, only what I thought to be the relevant part of it.

> 2016/12/13 03:25:10 amazon drive root 'Music': not deleting files as there were IO errors
2016/12/13 03:25:10 Attempt 3/3 failed with 3 errors and: not deleting files as there were IO errors
2016/12/13 03:25:10 Failed to sync: not deleting files as there were IO errors

I deleted the files in question manually.  The next sync run should be fine.  I wish I could just forget about this backup but there is something up with it often.

**Comment by isaiah36** [comment]
Problem solved.

**Comment by ncw** [comment]
> I wish I could just forget about this backup but there is something up with it often.

rclone does its best to help you with lots of retries, at different levels, but sometimes it just can't!

> Problem solved.

Excellent!
