### ISSUE TITLE
encoding for google drive files

### ISSUE THREAD

**Issue by okhrustov** [ncw/rclone#95]
Encoding for google drive files with Russian naming looks fine while doing ls command but after copying files to local drive I can not see russian letters anymore. Looks like some re-encoding happens during download.

**Comment by ncw** [comment]
Which OS are you using? 

Can you send me the output of `rclone -v copy` (or some of it)?

Thanks

Nick

**Comment by zeshanb** [comment]
In Windows for example. The file system will need Russian language support.
This way windows explorer will show correct file names.

Example instructions for adding language support for Windows OS:
https://technet.microsoft.com/en-us/library/Hh825705.aspx

**Comment by ncw** [comment]
Drive supports full utf-8 file names which is good for all languages.

The windows API supports utf-16 which rclone uses which should also be good for all languages.

So this should work properly provided the windows support is installed.

One of the unit tests which I have run on Windows involves uploading and downloading Chinese character set files.

All that said, there could be a problem, so any help getting to the bottom of it most appreciated.

Thanks

Nick

**Comment by okhrustov** [comment]
sorted this out, it was unix console locale settings issue. rclone works just fine

**Comment by ncw** [comment]
@okhrustov excellent - thanks!

**Comment by okhrustov** [comment]
Howerver I noticed another strange thing with downloading files with UTF characters in filename


2015/08/12 13:37:40 Operations/Clients/Отчеты/_Архив/XXXXX/Отчет_XXXX 1-31.05.2014.xlsx: Failed to open: Get : unsupported protocol scheme ""


This happens during sync / copy from g-drive to local folder.

Manual retry for such files also not successful

$ rclone-v1.17-linux-amd64/rclone copy "g-rtg:to_backup/Operations/Clients/Отчеты/XXXXX/Old/Отчет_форма до 16.10.2013.xlsx" dest/
2015/08/12 15:10:33 Local file system at t4: Building file list
2015/08/12 15:10:33 Local file system at t4: Waiting for checks to finish
2015/08/12 15:10:33 Local file system at t4: Waiting for transfers to finish
2015/08/12 15:10:33 Отчет_форма до 16.10.2013.xlsx: Failed to open: Get : unsupported protocol scheme

**Comment by zeshanb** [comment]
Try surrounding the filename with single quote. Not sure if quote needs to
be escaped in Linux cli fashion.

' '
rclone-v1.17-linux-amd64/rclone copy
"g-rtg:to_backup/Operations/Clients/Отчеты/XXXXX/Old/'Отчетформа до
16.10.2013.xlsx'"

Or..

" "

rclone-v1.17-linux-amd64/rclone copy
"g-rtg:to_backup/Operations/Clients/Отчеты/XXXXX/Old/"Отчетформа до
16.10.2013.xlsx""

**Comment by okhrustov** [comment]
no luck

rclone-v1.17-linux-amd64/rclone copy "g-rtg:to_backup/Operations/Clients/Отчеты/proskater/Old/'Отчет_форма до 16.10.2013.xlsx'" t4
2015/08/12 18:06:27 Local file system at t4: Building file list
2015/08/12 18:06:27 Local file system at t4: Waiting for checks to finish
2015/08/12 18:06:28 Google drive root 'to_backup/Operations/Clients/Отчеты/proskater/Old/'Отчет_форма до 16.10.2013.xlsx'': Couldn't find root: Couldn't find directory: "to_backup/Operations/Clients/Отчеты/proskater/Old/'Отчет_форма до 16.10.2013.xlsx'"
2015/08/12 18:06:28 Local file system at t4: Waiting for transfers to finish


"" ends up with rclone help message -- like wrong syntax error.

**Comment by zeshanb** [comment]
Try placing a backslash right after..Отчетформа\ and до\

rclone-v1.17-linux-amd64/rclone copy
"g-rtg:to_backup/Operations/Clients/Отчеты/proskater/Old/Отчетформа\ до\
16.10.2013.xlsx"

http://unix.stackexchange.com/questions/57830/trouble-in-script-with-spaces-in-filename

**Comment by okhrustov** [comment]
2015/08/13 07:01:00 Google drive root 'to_backup/Operations/Clients/Отчеты/proskr/Old/Отчет_форма\ до\ 16.10.2013.xlsx': Couldn't find root: Couldn't find directory: "to_backup/Operations/Clients/Отчеты"

**Comment by ncw** [comment]
I tried to replicate your problem by creating directory trees with Cyrillic characters on gdrive and downloading them to my linux machine, but I haven't been able to.

The error you reported

> 2015/08/12 13:37:40 Operations/Clients/Отчеты/_Архив/XXXXX/Отчет_XXXX 1-31.05.2014.xlsx: Failed to open: Get : unsupported protocol scheme ""

Comes from the [go http transport](http://golang.org/src/net/http/transport.go#L209) and indicates it tried to process a URL without `http` or `https` which is really strange as the URLs used come straight from Google drive, from the directory listings.  It probably means the url is empty for some reason.

Can you do this for me which will tell me what google drive is returning...

  * Go to: https://developers.google.com/drive/v2/reference/files/list#try-it
  * Click the Authorize requests using OAuth 2.0
  * Agree to the access request in the popup
  * Enter this into the q box: `title contains '1-31.05.2014'`
  * Then click the EXECUTE button

This should return information about the troublesome file. I'm particularly interested in what the `downloadURL` is and what the `title` is. Can you email me the whole output (nick@craig-wood.com)?

Thanks

Nick

**Comment by ncw** [comment]
@okhrustov thanks for sending me that.  I can see that the xlsx file doesn't have a `downloadUrl` which is strange, but consistent with the problem.

How did that file get on your drive? Did you upload it, or create it with google docs? Did someone share it with you?

This file has an `md5Checksum` but no `downloadUrl` which isn't consistent with [the docs](https://developers.google.com/drive/v2/reference/files#resource).  It should have both or neither as far as I understand.

  * `downloadUrl`	string	Short lived download URL for the file. This is only populated for files with content stored in Drive.
  * `md5Checksum`	string	An MD5 checksum for the content of this file. This is populated only for files with content stored in Drive.

How many other files do you see this for?

**Comment by okhrustov** [comment]
Usually  files are uploaded to the cloud via Google Drive app for Windows /
Mac. Some files can be uploaded manually in the browser.

There are about ~50 files with such problem.

Oleg.

**Comment by ncw** [comment]
OK, with a bit of help from the Google Drive Developers forum I've got to the bottom of this.

That file has `"copyable": false`.  Consequently it has no `downloadURL`.  I suspect that file was shared with you originally and whoever shared it with you didn't allow you to copy it.

I need rclone to deal with those files a bit more sensibly as it just can't download them.

**Comment by okhrustov** [comment]
thank you for shedding light on this

**Comment by ncw** [comment]
I've reopened this as I want rclone to give a sensible error message

**Comment by ncw** [comment]
I've made the v1.18 release report this properly.

Thanks for your help
