### ISSUE TITLE
Simple differential clone recursive gDrive to gDrive

### ISSUE THREAD

**Issue by papyr** [ncw/rclone#951]
Hi this is awesome, just what I was looking for 🍰 

- I am using rclone v1.34 
- I tired it on Ubunutu 14.04 LTS and windows 7 Home and pro
- Using Google Drive to -> google drive
- `rclone copy remote:Gdrive_1 remote:Gdrive_2  //copying from one gDrive_1 to another gDrive_2` 

I am trying to do a clone and maintain the copy as a differential copy, can you please help me with the command syntax to copy everything recursively, if newer from gdrive_1 to gdrive_2

thanks

**Comment by jpat0000** [comment]
So, if I understand correctly, you want to make backups of one of your Google Drive folders to another Google Drive folder on the same Google account, and have any files which have been changed in the source folder overwrite the files in the destination folder, correct? I believe adding --update should do the trick.

An example command of what I might use:

rclone --no-traverse `(doesn't scan the destination for duplicates that exist in other folders, this can save a lot of time if you have many subdirectories)` --update `(only overwrite files with a new size/modtime)` --drive-chunk-size=64M `(Not sure if rclone downloads the folder and reuploads it, or does a server side copy, so this may be useless for your application, not sure.)` --transfers=6 `(More and more can help speed up your transfer speeds for both small files and large files, you may choose to use as many as 16 if you're transferring small files.)` copy remote:Gdrive_1 remote:Gdrive_2

**Comment by papyr** [comment]
@jpat0000 sorry for not clarifying better, 

I am trying to copy to a _new/separate account_  currently I have files in my account-folders and I want to copy them to another account folder recursively

**Comment by jpat0000** [comment]
@papyr You specified two folders on the same remote, which sparked the confusion. As you may already know, you will need to specify two remotes, your source remote connected to one Google Drive, and your second remote connected to another one. Example: remote: and remote1:

I believe rclone transfers recursively by default. You can name the destination folder on your second remote whatever you like, including `myOldDriveContent`  👍 

Let me know if I am missing anything.

**Comment by papyr** [comment]
Thanks, just a suggestion - it would be nice to a have a visual option to select and confirm the source and destination.

Also a way to check the status of the transfer over time, or get an email notification on progress

**Comment by ncw** [comment]
If you use the `-v` flag you'll get more info on the progress of the transfer.

I'm going to close this now as I think the original question is answered.
