### ISSUE TITLE
[Feature Request] One way sync ( flag not to delete files on destination)

### ISSUE THREAD

**Issue by nbittmann** [ncw/rclone#952]
Not sure if this has ever been asked before but I love how rclone integrates with Amazon drive and encryption makes it even better the only thing I'm missing is I would like to sync some folder e.g. once new files appear rerun the command and upload the new files but not to delete if a file has been deleted on the source.

E.g.

I've got dir A on my local machine with the following files:

example1
example2

Now I add 
example3 

Run the sync and the file is uploaded now I want the ability to remove example1 and if I rerun the sync command I want to keep the file on the remote location.

Maybe I'm missing something and this is already possible? Also I could not find if existing files are skipped via copy?

My test tell me copy option should do confirmation would be awesome!

Thanks

**Comment by ncw** [comment]
Yes, use the `copy` verb and it will do what you want - copy never deletes anything on the destination.

You can test first with --dry-run to see exactly what it does.

**Comment by DurvalMenezes** [comment]
Hello nbittmann,

Unless I missed something, what you want is already accomplished by using the command "rclone copy" instead of "rclone sync".


Cheers,
-- 
   Durval.

**Comment by DurvalMenezes** [comment]
Hello nbittmann,

Unless I missed something, what you want is already accomplished by using the command "rclone copy" instead of "rclone sync".


Cheers,
 -- 
   Durval.
