### ISSUE TITLE
Amazon Drive: rclone won't timeout idle transfer

### ISSUE THREAD

**Issue by darkyrie** [ncw/rclone#957]
> What is your rclone version (eg output from `rclone -V`)
rclone v1.34-71-g4482e75β

> Which OS you are using and how many bits (eg Windows 7, 64 bit)
Ubuntu 16.04.1

> Which cloud storage system are you using? (eg Google Drive)
Amazon Drive

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
`rclone move adrive:"blah/blah/" encrytped:"enc/blah/blah/" --verbose --stats=10s`

> A log from the command with the `-v` flag (eg output from `rclone -v copy /tmp remote:tmp`)
```
2016/12/16 08:26:55
Transferred:   56.539 GBytes (1.240 MBytes/s)
Errors:                 0
Checks:                90
Transferred:           90
Elapsed time:  12h58m23.8s
Transferring:
 * ...aaaaaa.mp4:  0% done. avg:    0.3, cur:    0.0 kByte/s. ETA: 0s
 * ...bbbbb.mp4:  1% done. avg:    0.1, cur:    0.0 kByte/s. ETA: 0s
 * ...ccccc.mp4:  1% done. avg:    0.1, cur:    0.0 kByte/s. ETA: 0s
 * ...ddddd.mp4:  0% done. avg:    0.2, cur:    0.0 kByte/s. ETA: 0s

2016/12/16 08:27:05
Transferred:   56.539 GBytes (1.239 MBytes/s)
Errors:                 0
Checks:                90
Transferred:           90
Elapsed time:  12h58m33.8s
Transferring:
 * ... aaaaaa.mp4:  0% done. avg:    0.3, cur:    0.0 kByte/s. ETA: 0s
 * ...bbbbb.mp4:  1% done. avg:    0.1, cur:    0.0 kByte/s. ETA: 0s
 * ...ccccc.mp4:  1% done. avg:    0.1, cur:    0.0 kByte/s. ETA: 0s
 * ...ddddd.mp4:  0% done. avg:    0.2, cur:    0.0 kByte/s. ETA: 0s
```

At this point of time, the files was stuck/idled for more than ten hours. rclone jsut won't timeout these files and retry. I also tried with different --timeout settings but to no avail.

**Comment by ncw** [comment]
Can you run with the `-v` flag and post the log please?

Have you set  `--acd-upload-wait-per-gb` to a very large value?

**Comment by darkyrie** [comment]
I already ran with verbose, and there was no errors of any kind. It simply would not transfer anymore. And no, I did not change the `--acd-upload-wait-per-gb` flag.

Both of the paths are on the same ACD account, so I think this was a problem with ACD itself. After that, I just download everything first, then upload later instead of copying directly. That way things are faster and more reliable.

**Comment by ncw** [comment]
OK - glad you've sorted it.  I'll close this now.
