### ISSUE TITLE
Add a delete threshold to sync (--max-delete)

### ISSUE THREAD

**Issue by bep** [ncw/rclone#959]
First, really great piece of software! Very fast!

It would nice to have some kind of `delete threshold` for `sync`. 

Motivation:

I use this to sync several disks with my photo catalog. Sort of like an ongoing backup.

Sometimes I delete files in source, but it is usually mostly add -- so if, say, 200 files are deleted from source, it would be nice to bail out early with a big bold error.

**Comment by bep** [comment]
Thinking a little about this and, while this would be very useful, I think I'm gonna implement a "dry run" with manual confirm in my workflow.

**Comment by ncw** [comment]
I usually look for rsync for guidance for this kind of thing.  In this case rsync has

    --max-delete=NUM        don't delete more than NUM files

which would be straightforward to implement.

**Comment by chimpy** [comment]
Very interested in this :)

**Comment by ncw** [comment]
Thanks for implementing this @bep.

Here is the beta with it in :-)

https://beta.rclone.org/v1.39-135-g771fbbe3/ (uploaded in 15-30 mins)
