### ISSUE TITLE
[CRITICAL BUG] ACD mount over ENCFS copy/move does not work anymore 

### ISSUE THREAD

**Issue by ajkis** [ncw/rclone#961]
Latest version 
Test copy file to unencrypted ACD drive.
acd:/storage# cp testing.txt /storage/acd/
cp: can't create '/storage/acd/testing.txt': I/O error
LOG: http://pastebin.com/jMUx2vJ9

Using same proceedure but copying directly on mount works. 
LOG:  http://pastebin.com/8X68Mr0k

I think this worked before, but i did not notice it as iam mainly using rclone move to upload files.  There are a lot of people who mounted their Plex directly to ACD drive as saving just subtitles was never a problem.

p.s. Deleting files on encfs unencrypted mount works.

**Comment by ncw** [comment]
If you are using root to copy something to a fuse filing system you need --allow-root and you need to allow that in /etc/fuse.conf

I tried the above on ubuntu 16.10 and it worked fine for me.

Which OS are you using?

If --allow-root + /etc/fuse.conf fix doesn't work, can you post the result of

    strace cp testing.txt /storage/acd/

**Comment by flixajki** [comment]
```
acd:/storage# strace cp testing4.txt /storage/acd/
execve("/bin/cp", ["cp", "testing4.txt", "/storage/acd/"], [/* 16 vars */]) = 0
arch_prctl(ARCH_SET_FS, 0x620854cdeb28) = 0
set_tid_address(0x620854cdeb60)         = 3753
mprotect(0x620854cdb000, 4096, PROT_READ) = 0
mprotect(0x43191056000, 16384, PROT_READ) = 0
getuid()                                = 0
stat("testing4.txt", {st_mode=S_IFREG|0644, st_size=10, ...}) = 0
stat("/storage/acd/", {st_mode=S_IFDIR|0777, st_size=4096, ...}) = 0
stat("testing4.txt", {st_mode=S_IFREG|0644, st_size=10, ...}) = 0
lstat("/storage/acd/testing4.txt", 0x71723fb18428) = -1 ENOENT (No such file or directory)
open("testing4.txt", O_RDONLY)          = 3
open("/storage/acd/testing4.txt", O_WRONLY|O_CREAT|O_EXCL, 0100644) = 4
sendfile(4, 3, NULL, 16777216)          = 10
sendfile(4, 3, NULL, 16777216)          = 0
close(4)                                = 0
close(3)                                = 0
exit_group(0)                           = ?
+++ exited with 0 +++
```
Mount option 
```
rclone mount \
       --allow-non-empty \
       --allow-root \
       --max-read-ahead 14G \
       --acd-templink-threshold 0 \
       --checkers 16 \
       --stats 0 \
       -v \
       --debug-fuse \
       --dump-headers \
       --log-file=/storage/rclone-mount.log \
       acd:/ /storage/.acd/ &
```

**Comment by flixajki** [comment]
Just in case if you missed it, copying/moving file directly on mount works. 
It fails only when trying to do the same on trough encfs 

Direct copy

> plex@flix /storage $ strace cp ftest.txt /storage/.acd/
> execve("/bin/cp", ["cp", "ftest.txt", "/storage/.acd/"], [/* 22 vars */]) = 0
> brk(NULL)                               = 0x1746000
> access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
> mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f2085fa5000
> access("/etc/ld.so.preload", R_OK)      = -1 ENOENT (No such file or directory)
> open("/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
> fstat(3, {st_mode=S_IFREG|0644, st_size=53202, ...}) = 0
> mmap(NULL, 53202, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7f2085f98000
> close(3)                                = 0
> access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
> open("/lib/x86_64-linux-gnu/libselinux.so.1", O_RDONLY|O_CLOEXEC) = 3
> read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\260Z\0\0\0\0\0\0"..., 832) = 832
> fstat(3, {st_mode=S_IFREG|0644, st_size=130224, ...}) = 0
> mmap(NULL, 2234080, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f2085b60000
> mprotect(0x7f2085b7f000, 2093056, PROT_NONE) = 0
> mmap(0x7f2085d7e000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x1e000) = 0x7f2085d7e000
> mmap(0x7f2085d80000, 5856, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f2085d80000
> close(3)                                = 0
> access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
> open("/lib/x86_64-linux-gnu/libacl.so.1", O_RDONLY|O_CLOEXEC) = 3
> read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\20\34\0\0\0\0\0\0"..., 832) = 832
> fstat(3, {st_mode=S_IFREG|0644, st_size=31232, ...}) = 0
> mmap(NULL, 2126336, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f2085958000
> mprotect(0x7f208595f000, 2093056, PROT_NONE) = 0
> mmap(0x7f2085b5e000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x6000) = 0x7f2085b5e000
> close(3)                                = 0
> access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
> open("/lib/x86_64-linux-gnu/libattr.so.1", O_RDONLY|O_CLOEXEC) = 3
> read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\300\20\0\0\0\0\0\0"..., 832) = 832
> fstat(3, {st_mode=S_IFREG|0644, st_size=18624, ...}) = 0
> mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f2085f97000
> mmap(NULL, 2113760, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f2085753000
> mprotect(0x7f2085757000, 2093056, PROT_NONE) = 0
> mmap(0x7f2085956000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x3000) = 0x7f2085956000
> close(3)                                = 0
> access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
> open("/lib/x86_64-linux-gnu/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
> read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0P\t\2\0\0\0\0\0"..., 832) = 832
> fstat(3, {st_mode=S_IFREG|0755, st_size=1864888, ...}) = 0
> mmap(NULL, 3967392, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f208538a000
> mprotect(0x7f2085549000, 2097152, PROT_NONE) = 0
> mmap(0x7f2085749000, 24576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x1bf000) = 0x7f2085749000
> mmap(0x7f208574f000, 14752, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f208574f000
> close(3)                                = 0
> access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
> open("/lib/x86_64-linux-gnu/libpcre.so.3", O_RDONLY|O_CLOEXEC) = 3
> read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0000\25\0\0\0\0\0\0"..., 832) = 832
> fstat(3, {st_mode=S_IFREG|0644, st_size=456632, ...}) = 0
> mmap(NULL, 2552072, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f208511a000
> mprotect(0x7f2085188000, 2097152, PROT_NONE) = 0
> mmap(0x7f2085388000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x6e000) = 0x7f2085388000
> close(3)                                = 0
> access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
> open("/lib/x86_64-linux-gnu/libdl.so.2", O_RDONLY|O_CLOEXEC) = 3
> read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\240\r\0\0\0\0\0\0"..., 832) = 832
> fstat(3, {st_mode=S_IFREG|0644, st_size=14608, ...}) = 0
> mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f2085f96000
> mmap(NULL, 2109680, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f2084f16000
> mprotect(0x7f2084f19000, 2093056, PROT_NONE) = 0
> mmap(0x7f2085118000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x2000) = 0x7f2085118000
> close(3)                                = 0
> access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
> open("/lib/x86_64-linux-gnu/libpthread.so.0", O_RDONLY|O_CLOEXEC) = 3
> read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\260`\0\0\0\0\0\0"..., 832) = 832
> fstat(3, {st_mode=S_IFREG|0755, st_size=138696, ...}) = 0
> mmap(NULL, 2212904, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f2084cf9000
> mprotect(0x7f2084d11000, 2093056, PROT_NONE) = 0
> mmap(0x7f2084f10000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x17000) = 0x7f2084f10000
> mmap(0x7f2084f12000, 13352, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f2084f12000
> close(3)                                = 0
> mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f2085f95000
> mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f2085f93000
> arch_prctl(ARCH_SET_FS, 0x7f2085f93800) = 0
> mprotect(0x7f2085749000, 16384, PROT_READ) = 0
> mprotect(0x7f2084f10000, 4096, PROT_READ) = 0
> mprotect(0x7f2085118000, 4096, PROT_READ) = 0
> mprotect(0x7f2085388000, 4096, PROT_READ) = 0
> mprotect(0x7f2085956000, 4096, PROT_READ) = 0
> mprotect(0x7f2085b5e000, 4096, PROT_READ) = 0
> mprotect(0x7f2085d7e000, 4096, PROT_READ) = 0
> mprotect(0x623000, 4096, PROT_READ)     = 0
> mprotect(0x7f2085fa7000, 4096, PROT_READ) = 0
> munmap(0x7f2085f98000, 53202)           = 0
> set_tid_address(0x7f2085f93ad0)         = 26459
> set_robust_list(0x7f2085f93ae0, 24)     = 0
> rt_sigaction(SIGRTMIN, {0x7f2084cfeb50, [], SA_RESTORER|SA_SIGINFO, 0x7f2084d0a390}, NULL, 8) = 0
> rt_sigaction(SIGRT_1, {0x7f2084cfebe0, [], SA_RESTORER|SA_RESTART|SA_SIGINFO, 0x7f2084d0a390}, NULL, 8) = 0
> rt_sigprocmask(SIG_UNBLOCK, [RTMIN RT_1], NULL, 8) = 0
> getrlimit(RLIMIT_STACK, {rlim_cur=8192*1024, rlim_max=RLIM64_INFINITY}) = 0
> statfs("/sys/fs/selinux", 0x7ffcb2c9fa10) = -1 ENOENT (No such file or directory)
> statfs("/selinux", 0x7ffcb2c9fa10)      = -1 ENOENT (No such file or directory)
> brk(NULL)                               = 0x1746000
> brk(0x1767000)                          = 0x1767000
> open("/proc/filesystems", O_RDONLY)     = 3
> fstat(3, {st_mode=S_IFREG|0444, st_size=0, ...}) = 0
> read(3, "nodev\tsysfs\nnodev\trootfs\nnodev\tr"..., 1024) = 369
> read(3, "", 1024)                       = 0
> close(3)                                = 0
> open("/usr/lib/locale/locale-archive", O_RDONLY|O_CLOEXEC) = 3
> fstat(3, {st_mode=S_IFREG|0644, st_size=2981280, ...}) = 0
> mmap(NULL, 2981280, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7f2084a21000
> close(3)                                = 0
> geteuid()                               = 1000
> stat("/storage/.acd/", {st_mode=S_IFDIR|0775, st_size=0, ...}) = 0
> stat("ftest.txt", {st_mode=S_IFREG|0664, st_size=0, ...}) = 0
> stat("/storage/.acd/ftest.txt", 0x7ffcb2c9f600) = -1 ENOENT (No such file or directory)
> open("ftest.txt", O_RDONLY)             = 3
> fstat(3, {st_mode=S_IFREG|0664, st_size=0, ...}) = 0
> open("/storage/.acd/ftest.txt", O_WRONLY|O_CREAT|O_EXCL, 0664) = 4
> fstat(4, {st_mode=S_IFREG|0664, st_size=0, ...}) = 0
> fadvise64(3, 0, 0, POSIX_FADV_SEQUENTIAL) = 0
> mmap(NULL, 139264, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f2085f71000
> read(3, "", 131072)                     = 0
> close(4)                                = 0
> close(3)                                = 0
> munmap(0x7f2085f71000, 139264)          = 0
> lseek(0, 0, SEEK_CUR)                   = -1 ESPIPE (Illegal seek)
> close(0)                                = 0
> close(1)                                = 0
> close(2)                                = 0
> exit_group(0)                           = ?
> +++ exited with 0 +++

**Comment by ncw** [comment]
This is what I think is happending.  When you do a normal cp not through encfs it opens the output file write only.  You can see that in the strace

> 2016/12/18 14:51:17 fuse: <- Open [ID=0x1f Node=0xe Uid=0 Gid=0 Pid=1880] dir=false fl=OpenReadWrite
2016/12/18 14:51:17 fuse: -> [ID=0x1f] Open error=EIO: can't open file - writer failed

However by the time that has gone through encfs it has become a ReadWrite.  What encfs appears to do is create the file then open it read write.

> 2016/12/18 14:51:17 fuse: <- Open [ID=0x1f Node=0xe Uid=0 Gid=0 Pid=1880] dir=false fl=OpenReadWrite
> 2016/12/18 14:51:17 fuse: -> [ID=0x1f] Open error=EIO: can't open file - writer failed

rclone can't open files read/write it can only open them read or write, not read and write - that is why you are getting the EIO.

I should put a debug in to make that a little clearer...

So it doesn't look like to me that that could ever work with encfs...

Did you have a version of rclone where that did work?  If so which version was that?

**Comment by flixajki** [comment]
Now to think about it i usually just deleted stuff never copied, and actually the copying part was something i was testing for someone else. 

Is there a way to fix it ?

**Comment by flixajki** [comment]
Maybe it would be better and/or easier to fix it with native encfs support https://github.com/ncw/rclone/issues/651

**Comment by naclander** [comment]
Hello, any progress on supporting this?

**Comment by ajthemacboy** [comment]
Did you find a solution?

**Comment by ajkis** [comment]
There is not solution for this yet. ( dont think there will be one any time soon )

**Comment by benrubson** [comment]
> rclone can't open files read/write it can only open them read or write, not read and write

@ncw, does rclone allows 2 file descriptors to the same file, one read and another write ?

**Comment by ncw** [comment]
@benrubson that is unlikely to work properly I'm afraid.

**Comment by ncw** [comment]
Anyone coming across this issue: note that using `--vfs-cache-mode writes` will likely fix the problem for you now with a recent rclone.
