### ISSUE TITLE
FIX Dropbox: HTTP/1.1 414 Request-URI Too Large (unexpected HTTP status code 414)

### ISSUE THREAD

**Issue by allanlaal** [ncw/rclone#969]
affects: rclone **v1.33**
OS: Ubuntu Mate 16-04 LTS
driver: **Dropbox**

### command:

	$ rclone copy -v --dump-headers --retries 1 -u L4:/afs/acn dropbox:/acn

### output:

	2016/12/23 18:10:04 rclone: Version "v1.33" starting with parameters ["rclone" "copy" "-v" "--dump-headers" "--retries" "1" "-u" "L4:/afs/acn" "dropbox:/acn"]
	2016/12/23 18:10:04 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
	2016/12/23 18:10:04 HTTP REQUEST
	2016/12/23 18:10:04 GET /1/metadata%2Fauto%2Facn?file_limit=10000&include_deleted=false&list=false&locale=en HTTP/1.1
	Host: api.dropbox.com
	User-Agent: Go-http-client/1.1
	Authorization: Bearer ******data-omitted-for-privacy-reasons: ~65 chars********
	Accept-Encoding: gzip

	2016/12/23 18:10:04 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
	2016/12/23 18:10:06 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
	2016/12/23 18:10:06 HTTP RESPONSE
	2016/12/23 18:10:06 HTTP/1.1 200 OK
	Content-Length: 254
	Cache-Control: no-cache
	Connection: keep-alive
	Content-Type: text/javascript
	Date: Fri, 23 Dec 2016 16:10:06 GMT
	Pragma: no-cache
	Server: nginx
	Set-Cookie: gvc=******data-omitted-for-privacy-reasons: ~53 chars********; expires=Wed, 22 Dec 2021 16:10:06 GMT; httponly; Path=/; secure
	User-Agent: 
	X-Content-Type-Options: nosniff
	X-Dropbox-Http-Protocol: None
	X-Dropbox-Request-Id: ******data-omitted-for-privacy-reasons: ~33 chars********
	X-Frame-Options: SAMEORIGIN
	X-Server-Response-Time: 174

	2016/12/23 18:10:06 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
	2016/12/23 18:10:06 Dropbox root 'acn': Modify window not supported
	2016/12/23 18:10:06 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
	2016/12/23 18:10:06 HTTP REQUEST
	2016/12/23 18:10:06 GET /1/metadata%2Fauto%2Facn?file_limit=10000&include_deleted=false&list=false&locale=en HTTP/1.1
	Host: api.dropbox.com
	User-Agent: Go-http-client/1.1
	Authorization: Bearer ******data-omitted-for-privacy-reasons: ~65 chars********
	Accept-Encoding: gzip

	2016/12/23 18:10:06 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
	2016/12/23 18:10:07 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
	2016/12/23 18:10:07 HTTP RESPONSE
	2016/12/23 18:10:07 HTTP/1.1 200 OK
	Content-Length: 254
	Cache-Control: no-cache
	Connection: keep-alive
	Content-Type: text/javascript
	Date: Fri, 23 Dec 2016 16:10:07 GMT
	Pragma: no-cache
	Server: nginx
	Set-Cookie: gvc=******data-omitted-for-privacy-reasons: ~53 chars********; expires=Wed, 22 Dec 2021 16:10:07 GMT; httponly; Path=/; secure
	User-Agent: 
	X-Content-Type-Options: nosniff
	X-Dropbox-Http-Protocol: None
	X-Dropbox-Request-Id: ******data-omitted-for-privacy-reasons: ~33 chars********
	X-Frame-Options: SAMEORIGIN
	X-Server-Response-Time: 1037

	2016/12/23 18:10:07 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
	2016/12/23 18:10:07 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
	2016/12/23 18:10:07 HTTP REQUEST
	2016/12/23 18:10:07 POST /1/delta?locale=en&path_prefix=%2Facn HTTP/1.1
	Host: api.dropbox.com
	User-Agent: Go-http-client/1.1
	Content-Length: 0
	Authorization: Bearer ******data-omitted-for-privacy-reasons: ~65 chars********
	Accept-Encoding: gzip

	2016/12/23 18:10:07 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
	2016/12/23 18:10:10 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
	2016/12/23 18:10:10 HTTP RESPONSE
	2016/12/23 18:10:10 HTTP/1.1 200 OK
	Transfer-Encoding: chunked
	Cache-Control: no-cache
	Connection: keep-alive
	Content-Type: text/javascript
	Date: Fri, 23 Dec 2016 16:10:10 GMT
	Pragma: no-cache
	Server: nginx
	Set-Cookie: gvc=******data-omitted-for-privacy-reasons: ~53 chars********; expires=Wed, 22 Dec 2021 16:10:10 GMT; httponly; Path=/; secure
	User-Agent: 
	X-Content-Type-Options: nosniff
	X-Dropbox-Http-Protocol: None
	X-Dropbox-Request-Id: ******data-omitted-for-privacy-reasons: ~33 chars********
	X-Frame-Options: SAMEORIGIN
	X-Server-Response-Time: 2954

	2016/12/23 18:10:10 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
	2016/12/23 18:10:11 Dropbox root 'acn': 2000 delta entries received
	2016/12/23 18:10:11 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
	2016/12/23 18:10:11 HTTP REQUEST
	2016/12/23 18:10:11 POST /1/delta?cursor=******data-omitted-for-privacy-reasons: ~9903 chars********&locale=en&path_prefix=%2Facn HTTP/1.1
	Host: api.dropbox.com
	User-Agent: Go-http-client/1.1
	Content-Length: 0
	Authorization: Bearer ******data-omitted-for-privacy-reasons: ~65 chars********
	Accept-Encoding: gzip

	2016/12/23 18:10:11 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
	2016/12/23 18:10:11 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
	2016/12/23 18:10:11 HTTP RESPONSE
	2016/12/23 18:10:11 HTTP/1.1 414 Request-URI Too Large
	Connection: close
	Content-Length: 11921
	Content-Type: text/html
	Date: Fri, 23 Dec 2016 16:10:11 GMT
	Etag: "580e8b2c-2e91"
	Server: nginx
	X-Dropbox-Request-Id: ******data-omitted-for-privacy-reasons: ~33 chars********

	2016/12/23 18:10:11 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
	2016/12/23 18:10:11 Attempt 1/1 failed with 0 errors and: couldn't list: unexpected HTTP status code 414
	2016/12/23 18:10:11 Failed to copy: couldn't list: unexpected HTTP status code 414

linked dropbox thread:
https://www.dropboxforum.com/t5/API-support/The-remote-server-returned-an-error-414-Request-URI-Too-Large/td-p/192840

**Comment by ncw** [comment]
Thanks for the helpful bug report and links.

This is probably a job for the v2 API conversion #349 

However it wouldn't be too difficult to fix now...

The fix needs to be done here: https://github.com/stacktic/dropbox/blob/master/dropbox.go#L734

Fancy having a go?

**Comment by ncw** [comment]
Dropbox v2 API has just hit master!

Can you retry this with the v2 API please?

https://beta.rclone.org/v1.36-144-g178ff62d/ (uploaded in 15-30 mins)

**Comment by ncw** [comment]
Bit of trouble building: beta now here: https://beta.rclone.org/v1.36-146-g71028e0f/

**Comment by ncw** [comment]
I think this is probably fixed by the V2 API which you can find in a current beta.  Please re-open if not!

Thanks
