### ISSUE TITLE
Please add support for Box

### ISSUE THREAD

**Issue by meanpenguin** [ncw/rclone#97]
Looks like there is pretty comprehensive documentation here...
https://developers.box.com/get-started/

The docs have moved here: https://box-content.readme.io/docs/get-started-with-the-box-api

Golang module: https://github.com/ttacon/box

**Comment by ncw** [comment]
Thanks for the request!

**Comment by clintbxtreme** [comment]
This would be very helpful! Please add!

**Comment by hohokus** [comment]
+1, especially if it can preserve file creation/modification dates

**Comment by newbery** [comment]
Too late for me... I could really use Box support right now :)
Oh well, keeping on eye on this just in case.

**Comment by Tankypon** [comment]
Would be really nice to have Box support :)
As newbery I express my concern for this remote storage and to keep on eye on this issue.

**Comment by emvizible** [comment]
I'll chime in on behalf of the high-performance computing cluster users at CWRU -- having access to Box would be beneficial for our users currently relying on Box to store TB-scale data

**Comment by markjamie** [comment]
This would be really useful!

**Comment by nclarkjudd** [comment]
Also interested in Box sync.

**Comment by theonewolf** [comment]
Enterprises would love Box.com support :smile:

Anything we can do to help out here?  Is the interface for adding a new cloud provider well defined in your Go codebase @ncw?

**Comment by jpontius** [comment]
:+1:  I would also love to have Box.com support.  I have unlimited space here due to University contract...

**Comment by ncw** [comment]
@theonewolf wrote
> Anything we can do to help out here? Is the interface for adding a new cloud provider well defined in your Go codebase

The process is documented here: https://github.com/ncw/rclone/blob/master/CONTRIBUTING.md#writing-a-new-backend

I've had 3 backends contributed by third parties so it is possible!

If I was doing it I would first look for a well supported go module for Box.  If there wasn't one, then I would use rclone's rest library (see the onedrive remote for an example) which is straight forward.  The most time consuming bit is turning the JSON interface into Go struct definitions.

**Comment by HaiNguyen007** [comment]
please support box.com, much useful for lots of users

**Comment by t-barrett** [comment]
Please add Box.com support!

**Comment by strelnikov** [comment]
+1

**Comment by coreycauble** [comment]
+1 There are no other sync apps out there of any real use for box. So this addition would be huge for all BOX users. Box supports ftp, webdav, and API access. The API looks like the way to go. They have SDKs for Java, Python, Javascript/NodeJS, but not golang.

**Comment by claytoncurtis** [comment]
How about some Box.com support?  As you can see there are many users that would benefit.

**Comment by leonelwilliams** [comment]
The man only has so much time and there's always lots to do

**Comment by ncw** [comment]
I'll put box.com support down for the 1.38 release as there is a lot of demand for it! I'll post betas here when it is ready for testing.

**Comment by claytoncurtis** [comment]
Thanks sooooo much!

/cc

**Comment by igalvan-illinois** [comment]
Box Support would be much appreciated by users in my environment, that's for sure!

**Comment by ncw** [comment]
Here is the first version of the box remote

https://beta.rclone.org/v1.37-013-g7b81f12d/ (uploaded in 15-30 mins)

And [here are the docs](https://github.com/ncw/rclone/blob/master/docs/content/box.md).

I'm not sure whether I've done enough things to publish the rclone app on box.com so if it doesn't work let me know!

**Comment by hohokus** [comment]
basic testing works for me.  able to copy & sync with no immediate issues.  tested w/ 25mb of assorted wallpaper jpgs, nothing fancy.

**Comment by ncw** [comment]
Here is a beta for all platforms (the previous one only built for windows)

https://beta.rclone.org/v1.37-023-gc3d6cc91

**Comment by gimpbully** [comment]
Working wonderfully.  So much faster than rclone+davfs2

**Comment by bdutro** [comment]
I'm getting the following error at the end of an upload:

> commit multipart upload failed 1/10 - trying again in 22 seconds

**Comment by guruevi** [comment]
Great work! Even works with Box Enterprise accounts although Box.com throttles your throughput to ~20Mbps.

Chunking doesn't seem to work. Any file over 50MB gets this error:
2017/07/31 23:25:26 ERROR : ASL-WM_new/WM02/WM02funct.tar.gz: Failed to copy: multipart upload failed to finalize: Error "parts_mismatch" (400): No matching part found on server for {"part_id":"855B90F8","offset":75497472,"size":8388608,"sha1":null}
2017/07/31 23:38:54 ERROR : Archives/fsl-4.0.0.tar.gz: Failed to copy: multipart upload failed to finalize: Error "parts_mismatch" (400): No matching part found on server for {"part_id":"9E58B5E5","offset":1400897536,"size":8388608,"sha1":null}
2017/08/01 00:08:35 ERROR : Archives/spm8.tar.gz: Failed to copy: multipart upload failed to finalize: Error "parts_mismatch" (400): No matching part found on server for {"part_id":"52E484DC","offset":33554432,"size":33554432,"sha1":null}
2017/08/01 00:08:57 ERROR : Archives/spm8b.tar.gz: Failed to copy: multipart upload failed to finalize: Error "parts_mismatch" (400): No matching part found on server for {"part_id":"C1C02DAA","offset":67108864,"size":27791545,"sha1":null}

**Comment by mikef5410** [comment]
Working here with an enterprise account auth'd via Okta.

Thanks!

-mikef

**Comment by ncw** [comment]
@guruevi I've fixed the parts_mismatch problem here

https://beta.rclone.org/v1.37-067-gee13ea74/ (uploaded in 15-30 mins)

It turns out that sometimes if you run the commit very quickly after the last chunk then box gives this error - I've just made rclone wait then retry in this case.

I can only upload 1GB files on the free account.  I'd be interested if someone could test the new beta with bigger files - I'm wondering whether the amount of time I need to wait for the commit to be successful needs to be increased.  Run the copy with `-vv` to see debugs like this

```
2017/08/05 19:58:16 DEBUG : 600MB: Uploading part 70/76 offset 552M/600.001M part size 8M
2017/08/05 19:58:16 DEBUG : 600MB: Uploading part 71/76 offset 560M/600.001M part size 8M
2017/08/05 19:58:16 DEBUG : 600MB: Uploading part 72/76 offset 568M/600.001M part size 8M
2017/08/05 19:58:16 DEBUG : 600MB: Uploading part 73/76 offset 576M/600.001M part size 8M
2017/08/05 19:58:16 DEBUG : 600MB: Uploading part 74/76 offset 584M/600.001M part size 8M
2017/08/05 19:58:16 DEBUG : 600MB: Uploading part 75/76 offset 592M/600.001M part size 8M
2017/08/05 19:58:16 DEBUG : 600MB: Uploading part 76/76 offset 600M/600.001M part size 8M
2017/08/05 19:58:19 DEBUG : 600MB: commit multipart upload failed 1/10 - trying again in 10 seconds (Error "parts_mismatch" (400): No matching part found on server for {"part_id":"3A570D76","offset":570425344,"size":8388608,"sha1":null})
2017/08/05 19:58:29 DEBUG : 600MB: commit multipart upload failed 2/10 - trying again in 30 seconds (not ready yet)
2017/08/05 19:58:59 DEBUG : 600MB: commit multipart upload failed 3/10 - trying again in 30 seconds (not ready yet)
2017/08/05 19:59:30 INFO  : 600MB: Copied (new)
```

**Comment by gimpbully** [comment]
Are there flags to enable multipart?  This is from a run on the v1.37-067-gee13ea74 beta

2017/08/05 14:24:24 INFO  : box root 'crypt/d7pn8iff83fuumeh22p3926apk': Modify window is 1s
2017/08/05 14:24:34 ERROR : an175tlk0guku0o81osn385kcs: Failed to copy: multipart upload create session failed: Error "file_size_limit_exceeded" (403): File size exceeds the folder owner's file size limit
2017/08/05 14:24:35 ERROR : av43tfg6hh68g66f3828d1fois: Failed to copy: multipart upload create session failed: Error "file_size_limit_exceeded" (403): File size exceeds the folder owner's file size limit
2017/08/05 14:24:35 ERROR : ejh2sdkep5ghe1sbkonqaqbn60: Failed to copy: multipart upload create session failed: Error "file_size_limit_exceeded" (403): File size exceeds the folder owner's file size limit
2017/08/05 14:24:35 ERROR : aoauthvbtcv717sm44lr4kqvv51f0dj33n7fkotpcahk73qsanvg: Failed to copy: multipart upload create session failed: Error "file_size_limit_exceeded" (403): File size exceeds the folder owner's file size limit
2017/08/05 14:24:36 ERROR : kbt5adrn722nnl9h9lqdcbnc60: Failed to copy: multipart upload create session failed: Error "file_size_limit_exceeded" (403): File size exceeds the folder owner's file size limit
2017/08/05 14:24:36 ERROR : c01jbng6d1uv7btpmrm4d2mco786mlofo29l7k4bs4abucmpkvcg: Failed to copy: multipart upload create session failed: Error "file_size_limit_exceeded" (403): File size exceeds the folder owner's file size limit
2017/08/05 14:24:37 ERROR : lplohji7mrlh1a10lv0ukif07ijbnbh698pfrcs3b6tb6qvbtoeg: Failed to copy: multipart upload create session failed: Error "file_size_limit_exceeded" (403): File size exceeds the folder owner's file size limit
2017/08/05 14:24:38 ERROR : q2scj3ee0ao8g72fdmj51041k15589lgc8n7nn0p9r1o8mgveb9g: Failed to copy: multipart upload create session failed: Error "file_size_limit_exceeded" (403): File size exceeds the folder owner's file size limit
2017/08/05 14:24:38 ERROR : sij8cftffg2mcnjnkhvch5e4g0v16hatu8g7qhmkhbpk0k15cbn0: Failed to copy: multipart upload create session failed: Error "file_size_limit_exceeded" (403): File size exceeds the folder owner's file size limit
2017/08/05 14:24:40 ERROR : skn4thc925m1qrc90ucbbfa36itnf3v5jh1u7aea66iutfjp0aj0: Failed to copy: multipart upload create session failed: Error "file_size_limit_exceeded" (403): File size exceeds the folder owner's file size limit

**Comment by ncw** [comment]
@gimpbully 

The error is this "file_size_limit_exceeded" (403): File size exceeds the folder owner's file size limit"

Accounts all have some file size limits on them it seems - check out the [pricing page](https://www.box.com/pricing/business).

**Comment by howff** [comment]
Thanks very much for implementing this!

I tested an enterprise account with a 5GB directory, the largest file being 1.8GB. It worked fine, except that it had to wait 2.5 minutes at the end. Here's the end of the -vv output:

2017/08/07 11:41:32 DEBUG : testfile: Uploading part 227/228 offset 1.766G/1.774G part size 8M
2017/08/07 11:41:34 DEBUG : testfile: Uploading part 228/228 offset 1.773G/1.774G part size 8M
2017/08/07 11:41:35 INFO  : 
Transferred:   5.076 GBytes (6.169 MBytes/s)
Elapsed time:     14m2.6s
Transferring:
 *                testfile: 100% done, 5.166 MBytes/s, ETA: 0s
2017/08/07 11:41:37 DEBUG : testfile: commit multipart upload failed 1/10 - trying again in 30 seconds (not ready yet)
2017/08/07 11:42:07 DEBUG : testfile: commit multipart upload failed 2/10 - trying again in 30 seconds (not ready yet)
2017/08/07 11:42:35 INFO  : 
Transferred:   5.076 GBytes (5.758 MBytes/s)
Elapsed time:     15m2.6s
Transferring:
 *                testfile: 100% done, 96.745 kBytes/s, ETA: 0s
2017/08/07 11:42:38 DEBUG : testfile: commit multipart upload failed 3/10 - trying again in 30 seconds (not ready yet)
2017/08/07 11:43:09 DEBUG : testfile: commit multipart upload failed 4/10 - trying again in 30 seconds (not ready yet)
2017/08/07 11:43:35 INFO  : 
Transferred:   5.076 GBytes (5.400 MBytes/s)
Elapsed time:     16m2.6s
Transferring:
 *                testfile: 100% done, 1.769 kBytes/s, ETA: 0s
2017/08/07 11:43:39 DEBUG : testfile: commit multipart upload failed 5/10 - trying again in 30 seconds (not ready yet)
2017/08/07 11:44:10 INFO  : testfile: Copied (new)
2017/08/07 11:44:10 INFO  : 
Transferred:   5.076 GBytes (5.210 MBytes/s)
Elapsed time:    16m37.7s
2017/08/07 11:44:10 DEBUG : Go routines at exit 5
2017/08/07 11:44:10 DEBUG : rclone: Version "v1.37-067-gee13ea74\u03b2" finishing with parameters ["/packages/local/bin/rclone-v1.37-067-gee13ea74-amd64" "-vv" "copy" "1250" "box:ocm_2017-07-07-1250"]

**Comment by ncw** [comment]
@howff Thanks for testing.

I think some level of waiting at the end of an upload is normal according to the API docs.  It doesn't go into how long though!

I think the backend is assembling the file and making a checksum at this point, I'm not 100% sure though. Amazon Cloud Drive does the same thing, just in a much less organized fashion!

**Comment by MattBlissett** [comment]
I think there's a problem with filenames with non-ASCII characters.  They are copied the first time a sync is run, but the second time they are copied again, then deleted.

```
$ rclone sync 'gbif:/path/' '/mnt/path/' --log-level DEBUG
...
2017/09/12 18:13:08 INFO  : Présentation__.pdf: Copied (new)
2017/09/12 18:13:08 INFO  : Waiting for deletions to finish
2017/09/12 18:13:08 INFO  : Présentation__.pdf: Deleted
...
```

Version "v1.37-067-gee13ea74β"

(I have removed part of the filename above, but there are thousands of similar cases in my log, all with French, Spanish, Arabic etc filenames.)

**Comment by MattBlissett** [comment]
Ah, I just found the `--local-no-unicode-normalization` option. That works around the problem.

**Comment by ncw** [comment]
@MattBlissett that is actually a bug I've fixed in the box code which I fixed while doing something else - I only just realized it was appropriate here.  This beta should fix the problem

https://beta.rclone.org/v1.37-141-g38cc2117/ (uploaded in 15-30 mins)

**Comment by ncw** [comment]
I'm going to mark this issue complete now - please report an issues as a new issue!

Thanks

**Comment by ccchan234** [comment]
hi~
may I ask is the Box.com version be the personal version or the business version?

thanks.

https://www.box.com/pricing

**Comment by guruevi** [comment]
@ccchan234: Rclone seems to work with both.

**Comment by ccchan234** [comment]
thx.

let me summarize what unlimited cloud work with rclone:

gsuit
opendrive
box

**Comment by monperrus** [comment]
A deleted folder is in trash folder "Bin". How to permanently delete something in "Bin" from rclone?

**Comment by ncw** [comment]
> A deleted folder is in trash folder "Bin". How to permanently delete something in "Bin" from rclone?

Box doesn't support permanently deleting files only deleting files from the trash.  
Here https://github.com/ncw/rclone/issues/575#issuecomment-330028744 we decided that cleaning the trash on box would be too time consuming.  We could re-visit that potentially.  Interested in helping out with that @monperrus  ?

**Comment by monperrus** [comment]
> Interested in helping out with that @monperrus ?

Thanks for the invitation but I don't speak go.

Should I open a new issue for this?

**Comment by ncw** [comment]
> > Interested in helping out with that @monperrus ?
> 
> Thanks for the invitation but I don't speak go.
> 
> Should I open a new issue for this?

Yes, please open a new issue.  It should be something like "Implement Cleanup on box".  If you could include links to here and to https://github.com/ncw/rclone/issues/575#issuecomment-330028744 that would be helpful - thanks :-)

**Comment by monperrus** [comment]
Issue opened, see #3059
