### ISSUE TITLE
Upload speed per file is not accurate

### ISSUE THREAD

**Issue by claell** [ncw/rclone#970]
> rclone version: rclone v1.34-DEV

> OS: Ubuntu 16.10 64 bit

> cloud storage system: Google Drive

> command I was trying to run (removed personal details): rclone copy /local/path/ Cloud:cloud/path --include *something*

As described in the title the upload speeds per file vary a lot, while I get a pretty constant overall upload speed displayed, for example `Transferred:   1.305 GBytes (584.462 kBytes/s)`

Here is a screenshot of the problem:
![bildschirmfoto vom 2016-12-24 11-04-38](https://cloud.githubusercontent.com/assets/6171135/21466372/c1166d12-c9c9-11e6-9253-429651089509.png)

As you can see the sum of the individual speeds does not result in the overall speed. Also the ETA is alternating alot and probably also not very accurate.

Maybe the smothing algorithm could be improved.

**Comment by reticentnz** [comment]
It's not an overall speed but an average speed over the last 5 minutes. The individual speeds is at that exact moment. If you transfer speeds wildly fluctuate as yours appear to be doing then you would expect the average will be a lot different. 

Looks fine to me.

**Comment by claell** [comment]
This is why I asked to also use average speeds for individual speeds for better ETAs and better information.

**Comment by reticentnz** [comment]
well I guess 'better' is subjective. No program I use [winscp, filezilla, chrome, windows transfers as examples] average the speed of individual file copy speeds.

**Comment by claell** [comment]
That is true, but I think an ETA should not be calculated based on such unreliable data.

And since this program only displays speed in certain intervalls an average speed would make sense here.

**Comment by ncw** [comment]
Assuming these are big files (> 8MB) then #968 will fix this problem.

**Comment by breunigs** [comment]
Here's a fresh beta with this fixed, give it a try:
https://www.breunig.xyz/share/rclone-beta/v1.36-232-gb2b5c629-drive-accounting%CE%B2/

This makes the reported upload speeds for individual files much more accurate. It's still a bit off from the reported global speed, but I guess that's either due to rounding or timing issues. In any case, it's now definitely in the same ball park, unlike before. Turned out this was really easy to fix, too, thanks to @yonjah's work.

**Comment by ncw** [comment]
Nice one @breunigs :-)
