### ISSUE TITLE
Directories are all multi-nested and level-mixed on ACD with crypto

### ISSUE THREAD

**Issue by gordan-bobic** [ncw/rclone#971]
> What is your rclone version (eg output from `rclone -V`)
rclone v1.34-DEV

> Which OS you are using and how many bits (eg Windows 7, 64 bit)
CentOS 7 64-bit

> Which cloud storage system are you using? (eg Google Drive)
Amazon Cloud Drive

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone sync local/path remote:/path

Upload completes fine, but directory structures are all duplicated down the directory tree. For example:

Host:
level1/level2/level3/file4.1
level1/level2/level3/file4.2
level1/level2/level3/file4.3

appears on ACD and on rclone fuse mount as:
level0/level1/level2/level3/file4.1
level0/level1/level2/level3/file4.2
level0/level1/level2/level3/file4.3
level0/level1/level3/file4.1
level0/level1/level3/file4.2
level0/level1/level3/file4.3
level1/level2/level3/file4.1
level1/level2/level3/file4.2
level1/level2/level3/file4.3
level1/level3/file4.1
level1/level3/file4.2
level1/level3/file4.3

This doesn't happen when uploading using other tools. I haven't tested with earlier versions, but this appears to be happening with both rclone 1.33 and 1.34

I don't know whether this only affects encrypted remotes.

Interestingly enough rclone ls remote:/ shows the paths correctly (it doesn't show the redundant shortened paths), but the multi-paths show up in the raw ACD directory layoud and using the fuse mount.

**Comment by ncw** [comment]
Please give a sequence of commands to Replicate the problem - thanks!

**Comment by gordan-bobic** [comment]
Create a directory tree with files on the 4th level down, similar to the above.
Create an ACD mount remote: and an encrypted ACD mount under remote:/crypt
Then just:

rclone sync level2 crypt:/level1/level2

rclone ls crypt:/ shows non-duplicated paths, but looking at ACD web interface, there is more than one directory at the top level (encrypted filenames). A closed inspection show that one of the folders also exists under the other, e.g.

abc123/efg456
efg456

rclone mount also shows the duplicated content at reduced levels (all content seems to be both at the expected level, AND at one level closer to the root. Obviously, unlike with ACD web interface the file names are legible on the rclone mount.

So somehow the directory on the 2nd level was created at first level, and the contents appear to be the same under both. I don't think the content was actually uploaded twice, but I haven't verified this by measuring the bandwidth consumed yet.

**Comment by ncw** [comment]
I haven't managed to reproduce this.  Can you still reproduce it?

> So perhaps this problem was a compound between something weird having happened in the past and a bug causing rmdir to not stick via the fuse mount?

That seems plausible!

If you can't still reproduce the issue then we should probably close it.

**Comment by gordan-bobic** [comment]
Agreed, I can't readily reproduce it on my data set any more right now.
What about the rmdir not sticking via the encrypted fuse mount?

**Comment by gordan-bobic** [comment]
Will close this and open a fresh bug for rmdir on the ACD fuse mount not having any effect (directory doesn't get deleted on ACD).
