### ISSUE TITLE
Support HTTP**S** on the main server

### ISSUE THREAD

**Issue by siscia** [ncw/rclone#975]
Please add the option to download the pre-build binaries file from a secure server.

**Comment by ncw** [comment]
There are two places you can download via https, both linked on the downloads page..

  * https://github.com/ncw/rclone/releases/tag/v1.34
  * https://downloads-rclone-org-7d7d567e.cdn.memsites.com/

that said I do plan to convert rclone.org into https very soon!

**Comment by siscia** [comment]
Sorry I meant that most people, such as myself, are simply going to do the few commands on the website.

That is the main reason why it should be served using HTTPS

Thanks for your excellent work :)
