### ISSUE TITLE
"Ignoring unknown object" when downloading binary files

### ISSUE THREAD

**Issue by raztus** [ncw/rclone#980]
**rclone version:** 1.34 (yeah, not the latest beta, but I think I can see the issue in `master`.)
**OS:** Ubuntu 16.04.1 x86_64
**cloud storage system:** Google Drive
**command:** `rclone sync` and `rclone copy`
**log from `rclone -v copy remote:Directory/Subdirectory .`:**
```
2017/01/02 15:30:20 redacted-filename.pdf: Ignoring unknown object

Errors:                 0
```

This has happened with a variety of .pdf and .docx files in my Google Drive, most of which are older than 2014 (only one from September 2014). My best guess is that Google didn't begin attaching md5 sums to the files until some time in 2014, given the code that checks for this metadata: https://github.com/ncw/rclone/blob/master/drive/drive.go#L470

**Workaround:** right click file in Google Drive > click download > click cancel (in browser). This pops up a message that says "Scanning for viruses...", and, I suppose, calculates the md5 sum.

The main fix I would suggest is that rclone should consider the [default case](https://github.com/ncw/rclone/blob/master/drive/drive.go#L500) to be an error, and should increment the Errors count in the output (and possibly a list of files that failed to download).

The secondary fix would be to find a way to have rclone cause Google Drive to recalculate the md5 sum.

**Comment by ncw** [comment]
I've not seen that before...

I've always found it a little unsatisfactory that rclone uses the existence or not of an MD5 to check whether something is a file or not but I didn't find anything better.

This is what it says [in the drive v2 api docs](https://developers.google.com/drive/v2/reference/files)

> md5Checksum	string	An MD5 checksum for the content of this file. This field is only populated for files with content stored in Drive; it is not populated for Google Docs or shortcut files.
	
> fileSize	long	The size of the file in bytes. This field is only populated for files with content stored in Drive; it is not populated for Google Docs or shortcut files.

So maybe changing `case item.Md5Checksum != "":` to `case item.Md5Checksum != "" || item.FileSize > 0:` would be a fix for you.

I made a binary with that fix in for you here http://pub.rclone.org/rclone-v1.35-11-g13bfe06-980-drive-files.zip

Can you give it a go?

Thanks

**Comment by raztus** [comment]
I had to dig through my Drive trash to find files that would fail, since I manually fixed most of them yesterday, but I managed to find two. Both of them failed with my current version of rclone (v1.34), and both downloaded successfully with no error on version v1.35-DEV.

The fix also looks sane to me, given the Google api docs you quoted. Thank you!

**Comment by ncw** [comment]
Thanks for testing - I'll merge tomorrow.

Do you think that an unknown object should cause the sync to fail? That would be the consequence of incrementing the errors.  Or do you think it should just be a higher level log?  I'm tending towards the latter - what do you think?

**Comment by raztus** [comment]
@ncw I definitely think it should be a higher level log, preferably one that would show up in the summary below. I'm not sure if that's possible in the existing code or not, but ideally I'd like to see this summary:

```
Transferred:   10.355 MBytes (421.314 kBytes/s)
Warnings:               2
Errors:                 0
Checks:                 0
Transferred:           93
Elapsed time:       25.1s
```

And possibly a section that prints the files that caused warnings or errors at the end.

**Comment by ncw** [comment]
I've merged this to master now, here is the beta

http://beta.rclone.org/v1.35-60-g28f9b9b/ (ready in 15-30 mins)
