### ISSUE TITLE
The new rename tracking feature is slow

### ISSUE THREAD

**Issue by bep** [ncw/rclone#984]
I have tested the current master with the `--track-ranames` flag set on one of my photo disks, 21 GB of fairly large RAW files, renamed 5 of them and then sync to another USB3 disk.

My implementation (https://github.com/bep/rclone/tree/renames):

```
Transferred:      0 Bytes (0 Bytes/s)
Errors:                 0
Checks:               346
Transferred:            0
Elapsed time:       10.5s
11.32s  user 2.34s system 88% cpu 15.432 total
avg shared (code):         0 KB
avg unshared (data/stack): 0 KB
total (sum):               0 KB
max memory:                175496 MB
page faults from disk:     3630
other page faults:         365136
````

Current master:

```
Transferred:   6.004 kBytes (15 Bytes/s)
Errors:                 0
Checks:               704
Transferred:            1
Elapsed time:     6m29.5s
110.73s  user 16.39s system 31% cpu 6:39.87 total
avg shared (code):         0 KB
avg unshared (data/stack): 0 KB
total (sum):               0 KB
max memory:                173104 MB
page faults from disk:     4112
other page faults:         696919
```

From the log it looks like it performs hashing of every file, which sounds very sub-optimal in all the common use cases I can think of.

I have repeated the test twice with similar results.

I will continue to use my own fork for the time being, but I thought I would give a heads up.

**Comment by ncw** [comment]
Eeek!  Will look at it tomorrow. It should be easy to fix though.

Thanks for testing.

**Comment by ncw** [comment]
OK I fixed that hopefully - I've put it in a fix-track-renames branch - can you have a go with that and see what you think?

Thanks

Nick

**Comment by bep** [comment]
OK, now it is just half as slow as my implementation for the test case above, which still sounds expensive, considering the added code complexity.

But, up to you.

**Comment by ncw** [comment]
Can you work out why it is slower? 

I note that it could be optimized further by only calculating the hashes of files which have a size which might match - that is probably the difference.

The trouble with your implementation is it has an [O(N^2) loop in](https://github.com/bep/rclone/blob/renames/fs/sync.go#L345), so if you, say, moved all your photos (10000 say) to a subdirectory and did a sync, then rclone would be doing 10000x10000 times around the loop

Will investigate some more tomorrow - past my bed time now, so probably none of the above makes any sense ;-)

**Comment by bep** [comment]
>Can you work out why it is slower?

Asking me to debug your code is a tall order.

As to algorithmic complexity, I assume both solutions is  O(N^2)  in the worst case scenario and also assuming that the hashes are cached on the file level, it should not make much difference. The only way I see around that would be to implement some folder renaming logic.

I did a quick test of that too, moving a folder with the same 21 GB of files (~350 files) one level down.

The fix-renames branch:

```
Transferred:   12.008 kBytes (16 Bytes/s)
Errors:                 0
Checks:               710
Transferred:            2
Elapsed time:     12m7.4s
191.83s  user 27.70s system 29% cpu 12:16.94 total
avg shared (code):         0 KB
avg unshared (data/stack): 0 KB
total (sum):               0 KB
max memory:                170560 MB
page faults from disk:     4153
other page faults:         694608
```

My code ((https://github.com/bep/rclone/tree/renames):

```
Transferred:   6.004 kBytes (10 Bytes/s)
Errors:                 0
Checks:                 2
Transferred:            1
Elapsed time:     9m41.7s
187.39s  user 26.75s system 36% cpu 9:51.66 total
avg shared (code):         0 KB
avg unshared (data/stack): 0 KB
total (sum):               0 KB
max memory:                173552 MB
page faults from disk:     3374
other page faults:         686099
````

I'm checking out of this discussion. It is your project, you do as you please. 

I can understand and sympathise with the motivation to guard your own code, so I will say this in the nicest possible way:

Taking pull requests and repeatedly asking for improvements, then saying "the only thing missing now is a test or two", and "oh, and could you add some documentation?". And when you finally "merge" it, you wipe out everything but the testing and the documentation without any discussion.

You should not get surprised when you don't get any "repeat Pull Requests" from people.

Ref. issue #888

**Comment by ncw** [comment]
Firstly I'd like to say thank you for your contribution.

I'm sorry you feel that I wiped out your code. I overstepped the mark in changing the code without discussing my concerns about it with you first.  Please accept my apologies.

Yes I am probably too picky about the code, and I'll try to take your comments on board for future pull requests.  I definitely haven't mastered the art of being an open source maintainer so I'm always willing to learn.

Thanks for your feedback

Nick

**Comment by bep** [comment]
>I'm sorry you feel that I wiped out your code.

You did wipe out my code and replaced it with some hard to understand and buggy code. No feelings involved.

**Comment by hraban** [comment]
@bep mate he's the project maintainer, the second he merges in "your code", it becomes his responsibility to maintain it. When it breaks, he has to fix it. During refactoring, he has to include that code. Really, the second it merges into his repo, it's not "your code" anymore. It's completely normal to ask for tests, documentation, refactoring, or to even simply reject a patch if it doesn't meet the maintainer's (subjective) standards. That's the point of being a maintainer.

I can't tell from a glance whose patch makes "more sense" or "is cleaner", so you may very well be objectively right, here. Nonetheless; your comment is uncalled for. Submit a PR, or don't, and move on. Don't make it personal.

Maintaining an open source project is more than just green lighting patches from strangers. It's unrewarding, ungrateful work, and comments like this can be demoralising.

**Comment by bep** [comment]
@hraban don't comment on something you have no clue about.

**Comment by hraban** [comment]
@bep If I lived by that rule, I would be mute.

**Comment by bep** [comment]
@hraban @leonwilliams I'm going to give you the benefit of doubts and assume you really don't understand this situation.

This isn't about someone rejecting or deleting my code. I do that all the time to others. That is fine.

**This is all about wasting peoples time. This was an ongoing PR for weeks with "this looks very good, but could you just adjust this part over there ... " and then ... boom PR removed without any explanation.***

That is bad maintainer manners from @ncw -- and I would assume he have learned a lesson from it.

**Comment by hraban** [comment]
Thank you for the context.
